### ISSUE TITLE
lnd refuses overpayment?

### ISSUE THREAD

**Issue by ZmnSCPxj** [lightningnetwork/lnd#1002]
### Background

https://github.com/lightningnetwork/lnd/blob/9b729654f62cefefa043ba296d0d558042a7dda7/htlcswitch/link.go#L1964-L1979

Suggests that lnd refuses overpayment of invoices.

Xref: https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md

> An _intermediate hop_ MUST NOT, but the _final node_:
>  - if the amount paid is less than the amount expected:
>    - MUST fail the HTLC.
>  - if the amount paid is more than twice the amount expected:
>    - SHOULD fail the HTLC.
>    - SHOULD return an `incorrect_payment_amount` error.
>      - Note: this allows the origin node to reduce information leakage by
>      altering the amount while not allowing for accidental gross overpayment.

Recently c-lightning added ability to automatically overpay: https://github.com/ElementsProject/lightning/pull/1257

This caused somebody to open an issue on c-lightning: https://github.com/ElementsProject/lightning/issues/1309

However specs seem to suggest that c-lightning behavior is within spec.

### Your environment

* version of `lnd` 9b729654f62cefefa043ba296d0d558042a7dda7
* which operating system (`uname -a` on *Nix) N/A
* version of `btcd`, `bitcoind`, or other backend N/A
* any other relevant environment details Sheer code review

### Steps to reproduce

Sheer code review

### Expected behaviour

lnd should accept `invoice <= payment <= invoice * 2`.

### Actual behaviour

lnd accepts only `invoice == payment`

**Comment by Roasbeef** [comment]
Automatically overpaying sounds like a _really_ bad idea. We've already seen users get touchy about the on-chain commitment fees they pay, randomly forcing the user to pay _twice_ the invoice amount is a bit much.

**Comment by ZmnSCPxj** [comment]
Fees will happen on-Lightning anyway (`fee_base`, `fee_per_millionth`). C-lightning `pay` command accepts a maximum fee rate as a percent of the payment amount.  The total amount that it will give out on the first hop will never exceed the maximum fee rate --- if it would, it recomputes the route and overpayment without even trying the route.

The overpayment is randomized between 0 to up to the maximum fee rate.

The effect is that overpayment tends to be lower the further you are from the payee, but this is not reliable --- C-lightning could overpay by a small amount with some probability even on a direct channel to the payee.

Note that C-lightning even does route randomization --- it will sometimes take non-optimal routes (even if it does not know the optimal route would fail). The only requirement is that, the first hop, will not be given more than the maximum fee rate deemed acceptable by the user.  This means that the maximum fee rate is a privacy parameter in C-lightning, and overpayment simply hides within the fees we are obliged to pay on-Lightning anyway.
