### ISSUE TITLE
typo on release notes

### ISSUE THREAD

**Issue by mattbourke** [lightningnetwork/lnd#1012]
### Background

very small typo `name fro being fully` on release notes.  
https://github.com/lightningnetwork/lnd/releases/tag/v0.4.1-beta

### Your environment

github

### Steps to reproduce

load https://github.com/lightningnetwork/lnd/releases/tag/v0.4.1-beta

### Expected behaviour

`name from being fully`

### Actual behaviour

`name fro being fully`  (note the missing 'r')

**Comment by Roasbeef** [comment]
Thanks! 

[Fixed](https://github.com/lightningnetwork/lnd/releases/tag/v0.4.1-beta) :)
