### ISSUE TITLE
flush balance before close

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1013]
### Background

feature request:

before closing, try to flush the balance to either side so one of the balances is 0 to make closing tx smaller. (by using a specially crafted pay-to-self transaction)

all rebalancing-before-close things has some ... i dunno... moral implications since it means when you close, you decide if you want to "cash out" everything to your onchain or if you want to force the other party to get the onchain.
but hey, smaller transactions onchain is always a good thing.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
The closing tx will already be smaller if one of the outputs is near dust. Don't see how we can actually "balance" without just donating funds to the other party.

**Comment by robtex** [comment]
## Initial state, A-B should be closed.

Node1|Balance1|Balance2|Node2
-|-|-|-
A|50|50|B
A|100|100|C

### To close A-B with one TXout, getting all 100
1. find a path A->C->...LN...->B->A
2. send 50 along that path. new state will be:

Node1|Balance1|Balance2|Node2
-|-|-|-
A|100|0|B
A|50|150|C

3. close A-B and claim all balance on-chain

### To close A-B with one TXout, without getting anything on chain

1.  find a path A->B->...LN...->C->A
2. send 50. new state will be:

Node1|Balance1|Balance2|Node2
-|-|-|-
A|0|100|B
A|150|50|C

3. close A-B and let B take all balance

(fees omitted for the sake of clarity)

**Comment by robtex** [comment]
i suggest you could do this with something like `closechannel --getall`  or `closechannel --leavall` . and/or you can do preclose-balancing automatically in either direction if you detect a balance like 3-97 or 97-3.
(while we are at it we can make a generic balance-channel api. something like 
`rebalance $outgoingchannel $incomingchannel $amount` )

i guess/hope however that if one node decides to close the channel, it will no longer be eligble for transactions, right? 
otherwise you could do it passively when the other party wants to close the channel, by pretending you didn't hear the first close request and instead you just send a final transaction.
that might create a very funny oscillator function though if the other party and you disagrees on who should take the balance onchain.

**Comment by Roasbeef** [comment]
This is possible today with the sendpayment API (allow circular routes), so a node management tool can implement this functionality outside of lnd.
