### ISSUE TITLE
Unable to build on NixOS

### ISSUE THREAD

**Issue by canndrew** [lightningnetwork/lnd#1015]
### Background

Following the build instructions doesn't work on NixOS.

### Your environment

I'm building the latest commit on master, 6fa93a78c18180a3bc77116b749b3c5e279d5a33. I have go and dep installed.

### Steps to reproduce

```
> # install go and dep
> export GOPATH=~/src/go
> cd ~/src/go
> git clone https://github.com/lightningnetwork/lnd
> cd lnd
> make
```

### Expected behaviour

It should start building.

### Actual behaviour

It prints:

```
Makefile:88: *** target pattern contains no '%'.  Stop.
```

As far as I can tell this is due to the Makefile expecting GOPATH to be a single path and not a colon-separated list of directories. This is unfortunate since NixOS sets GOPATH itself to point to where go and dep are installed.

**Comment by halseth** [comment]
you should not clone `lnd` directly into the `gopath`, but instead use `go get github.com/lightningnetwork/lnd`

**Comment by dannypaz** [comment]
@halseth would this be the same case for Docker? https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/Dockerfile#L16

**Comment by halseth** [comment]
yes, that command is more or less equivalent to `go get -d github.com/lightningnetwork/lnd` I think.

**Comment by Roasbeef** [comment]
The build instructions have recently been updated to display the commands run directly by the make file.
