### ISSUE TITLE
Add version data to `getnetworkinfo` RPC call

### ISSUE THREAD

**Issue by mecampbellsoup** [lightningnetwork/lnd#1016]
### Background

It would be nice to be able to query a node and ask what version of the LND software it is running. `bitcoind` exposes this information via the `getnetworkinfo` RPC call:

```
14:47:30 › bitcoin-cli getnetworkinfo | jq -r .version
160000
```

It seems like LND should copy this pattern, unless there is some reason why it is intentionally omitted?

**Comment by Roasbeef** [comment]
Fixed by #1020.
