### ISSUE TITLE
new command: lncli lookuppayment <payment_hash>

### ISSUE THREAD

**Issue by kinolva** [lightningnetwork/lnd#1018]
### Background
It would be REALLY helpful to be able to lookup a sent payment (as opposed to an invoice created) via the payment_hash. This is the logical foil of the _lncli lookupinvoice <payment_hash>_ function. Such a command would save having to manually search through _lncli listpayments_ to locate the relevant information pertaining to the payment_hash of a particular payment. When a user has hundreds or thousands of sent payments, this function would radically improve efficiency, as well as obviate the need to keep a 3rd layer app-side database of sent payments. 

Thus, the proposed syntax is: lncli lookuppayment <payment_hash>

Note: the function should return JSON formatted information similar to _lncli lookupinvoice <payment_hash>_, BEYOND what lncli listpayments provides. For example, it should include the "settled": true / false value, etc.

### Your environment
lnd 0.4.0

**Comment by kinolva** [comment]
vctt94: sure! (fine by me!)
Happy to be in dialog with you about it as well. This came up for me and another user on the freenode chat as we were sending payments to one another.

**Comment by Roasbeef** [comment]
`TrackPayment` does this now.

**Comment by kinolva** [comment]
Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
