### ISSUE TITLE
tx onchain extra transaction

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1021]
### Background

A channel was closed
The amount sent to my side was 1159 sat
Then it kind of bounced and made a new transaction to another address
One input and one output.
In the end I got 589 sat
Is it necessary to waste an extra transaction and extra fee like that?
What am i missing?

https://btc.com/bc1qxpmt8eyf3euj8692uy0q9f6z6ujxlmamm7dwff
```
        {
            "tx_hash": "e036dcbfb431b9260b62e4e3db8d9be7def40bc85808c7c0885d18facb992d1b",
            "amount": "589",
            "num_confirmations": 9,
            "block_hash": "000000000000000000129a4d1d61d99a6ee9045763c0fecb0433e2616bc2758c",
            "block_height": 516566,
            "time_stamp": "1522832088",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qrrs2t6wv5npajnnqxw4gvlzj6af902n8z4uhrh"
            ]
        }
```

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by robtex** [comment]
another example that probably is clearer
https://btc.com/bc1qkx6dm60wn3arxgh02lh7zla727yk92ly63wpel

**Comment by Roasbeef** [comment]
>Is it necessary to waste an extra transaction and extra fee like that?

That was just the transaction fee that was negotiated. The amount of `1159` is only _slightly_ above dust itself, so a fee of 500 satoshis is pretty minor itself.
