### ISSUE TITLE
multiple problems with seed dns

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1022]
### Background

just did a quick check since it seems lnd is trying to feed from a dns zone that isn't set up correctly.
this means that it is a bit chance if it works or not. actually it is kind of a miracle that it does work for some :)

while querying nodes.lightning.directory for A record, you get the following delegation:

```
; AUTHORITY SECTION:
lightning.directory.    86400   IN      NS      nodes.lightning.directory.
lightning.directory.    86400   IN      NS      nodes2.lightning.directory.

;; ADDITIONAL SECTION:
nodes.lightning.directory. 86400 IN     A       104.131.26.124
nodes2.lightning.directory. 86400 IN    A       104.131.26.124
```

some problems with this setup is:

1. one nameserver is called nodes, which is what we are querying for. 
2. both nameservers has the same glue records
3. the nameservers answer SERVFAIL for nodes2
4. the nameserves answer with a bunch of ips for nodes, those are not running dnsservers 
5. no idea what soa.nodes.lightning.directory is supposed to do. gives me ip 104.131.26.124. it seems to only answer dns
6. 104.131.26.124 answers SERVFAIL for ns for lightning.directory

```
$ lncli connect 03656a4c737b98b7ca5ad1ee4b411f5929f53552018b3925f341bcfa1c832287b7@104.131.26.124
[lncli] rpc error: code = OutOfRange desc = EOF
```

please fix those problems i can do a more complete audit if you wish.
quick fix is to call the nameserves ns and ns2 instead of reusing the name for the zone itself. but the nameservers must also be able to answer with the correct ip themselves, not blindly trusting on glue records.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
The `soa` record is just a hack to allow manual TCP resolution in the case that resolvers filter out our larger SRV records.

**Comment by Roasbeef** [comment]
`104.131.26.124` isn't a lightning node at all.

**Comment by Roasbeef** [comment]
Have you taken a look at this BOLT? https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md

**Comment by robtex** [comment]
ok, something on 104.131.26.124 is picking up on port 9735 though, so i guessed it was a lightning node.

i took a quick peek at the bolt before, however i'm trying to report about bugs on the dns setup itself from a dns operation point of view. maybe this should be reported elsewhere?
who is managing this dns?

the domain in the bolt `lseed.bitcoinstats.com` is set up much better (but not perfect imho).
for instance the nameserver there actually has another name than the zone, which is a good thing

```
lseed.bitcoinstats.com. 300     IN      NS      lseedns.bitcoinstats.com
```

compare
`dig +trace nodes.lightning.directory`
with 
`dig +trace lseed.bitcoinstats.com`

and check the nameservers the zone is delegated to from above
```
lightning.directory.	86400	IN	NS	nodes2.lightning.directory.
lightning.directory.	86400	IN	NS	nodes.lightning.directory.
```

and try querying them
`dig @nodes2.lightning.directory nodes.lightning.directory`
and
`dig @nodes.lightning.directory nodes.lightning.directory`

setups like this might very well create issues when seeding the nodes

**Comment by Roasbeef** [comment]
Yep this is the proper place to report issues with the current DNS infrastructure we use. The code is currently housed at https://github.com/Roasbeef/lseed, but hasn't yet been updated to the version currently deployed.

**Comment by lispmeister** [comment]
I'm picking this up again this month. Users will be able to run their own seeds more easily (including ready made Docker images and a Kubernetes chart). We will also need a patch to `lnd` to allow specifying the seeds you want to get service from at boot.

**Comment by Roasbeef** [comment]
Closing this as it isn't tied to the lnd release process, but we're tracking it elsewhere. You can also provide your own DNS seed now with the main config.
