### ISSUE TITLE
Rescanning slow on Windows 10 bitcoind localhost

### ISSUE THREAD

**Issue by SerafinTech** [lightningnetwork/lnd#1027]
When running Lnd mainnet with bitcoind, Scanning blocks takes forever.

Fixed by setting bitcoind.rpchost = 127.0.0.1:8332

Should set 127.0.0.1 as default vs localhost for bitcoind rpchost

**Comment by Roasbeef** [comment]
> Fixed by setting bitcoind.rpchost = 127.0.0.1:8332

How does this fix the issue? 

We're aware of the slowness. It's due to the fact that (compared to `btcd`), `bitcoind` doesn't have a nice API for checking to see if there're relevant items in a block. As a result, we're forced to _manually_ fetch and scan each block locally.

**Comment by SerafinTech** [comment]
Localhost is resolved to 127.0.0.1 for each rpc request and for some reason in windows 10 that process is taking about a second.

**Comment by Roasbeef** [comment]
Ahh, interesting! Odd that the resolution takes so long...
