### ISSUE TITLE
Feature request: stop without unlocking the wallet

### ISSUE THREAD

**Issue by bitonic-cjp** [lightningnetwork/lnd#1028]
The "stop" command currently requires the wallet to be unlocked. This is inconvenient when using scripts to start/stop LND, when those scripts don't have knowledge of the wallet passphrase and can't assume the wallet will always be unlocked.

I'd say that a script that has access to the admin macaroon is already sufficiently authorized to stop LND. Why require the wallet passphrase to stop the software?

Maybe this is not so important if LND does a proper shutdown when it receives SIGTERM. In that case, please document this behavior or point to the documentation.

**Comment by MDrollette** [comment]
Can this be closed now that SIGTERM is handled?

**Comment by wpaulino** [comment]
Not yet, I believe the [`StopDaemon`](https://github.com/lightningnetwork/lnd/blob/2a652455aaea661b147b6adca0ff51edcd268508/lnrpc/rpc.proto#L618) RPC would also need to be added to the [`WalletUnlocker`](https://github.com/lightningnetwork/lnd/blob/2a652455aaea661b147b6adca0ff51edcd268508/lnrpc/rpc.proto#L33) service.

**Comment by saubyk** [comment]
closing this issue, as unsure about the need for this feature. If LND is locked, it can be killed without any adverse impact, which the automated scripts should be able to handle in their logic.
