### ISSUE TITLE
private channel in describegraph

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1037]
### Background

channels that are private to the node are shown in `describegraph` .
can we add the `private` flag to describegraph so they are easier to filter out on visualizers etc?

**Comment by i25959341** [comment]
Can I work on this, please?

**Comment by i25959341** [comment]
What would be the best way to start on this issue?

**Comment by halseth** [comment]
Take a look at the `DescribeGraph` method in the `rpcserver`: https://github.com/lightningnetwork/lnd/blob/86ad6d318e0ba4d3e22e12baec1f37bc1471d44d/rpcserver.go#L2482

A private edge won't have an attached `AuthProof`, which can be used to filter out private channels: https://github.com/lightningnetwork/lnd/blob/86ad6d318e0ba4d3e22e12baec1f37bc1471d44d/channeldb/graph.go#L1251:6
