### ISSUE TITLE
witness_only still mentioned in Python docs

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lnd#1038]
### Background

"witness_only" is still mentioned in the Python docs, even though the parameter was removed in 0.4 according to the release notes (https://github.com/lightningnetwork/lnd/releases)

https://github.com/lightningnetwork/lnd/blob/117441b7d0b9ccbffdc24e47776c7df81d47f7e7/docs/grpc/python.md

### Your environment

master. Other details irrelevant since this is a doc error.

### Steps to reproduce

Irrelevant since doc error.

### Expected behaviour

No use of "witness_only"

### Actual behaviour

"witness_only" mentioned

**Comment by Roasbeef** [comment]
Ah, yes. Want to make the easy doc correction PR?

**Comment by i25959341** [comment]
decided to pick this quick one myself at  #1051
