### ISSUE TITLE
lnd with a reverse proxy

### ISSUE THREAD

**Issue by croll83** [lightningnetwork/lnd#1039]
### Background

Hi, first non-blocking issue here. 

My lnd is behind a reverse proxy (HAProxy) that rewrites the incoming peers ip (source ip in TCP packets) with the HAProxy IP (local LAN - 10.10.0.xx). On the first inbound connection they are included in my known peers db with the local ip even if they advertise a public external ip. They are able to open channel with me without problems. 

If I restart the lnd, it will start to try connections to such peers but it obviously fails (HAProxy doesn't listen for LN connections). The result is that all inbound-originated channels are not in the active state while outbound-originated channels are active, because outbound peers added by me are stored with the correct external ip:

```
lncli listpeers: 
        {
            "pub_key": "Peer1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "address": "PublicIP:9735",
            "bytes_sent": "521750",
            "bytes_recv": "594102",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": false,
            "ping_time": "103575"
        },
        {
            "pub_key": "Peer2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "address": "10.10.0.xx:48576",
            "bytes_sent": "48053339",
            "bytes_recv": "23482894",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "116070"
        }
```

If I try to get info about the Peer2 I can see his external ip:

```
lncli getnodeinfo Peer2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{
    "node": {
        "last_update": 1523036482,
        "pub_key": "Peer2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "alias": "XXXXXX",
        "addresses": [
            {
                "network": "tcp",
                "addr": "PublicIP:9735"
            }
        ],
        "color": "XXXXX"
    },
    "num_channels": XX,
    "total_capacity": "XXXXXXX"
}
```

If I try to manually connect to an inbound peer after the restart I receive this error message:

```
lncli connect Peer2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@PublicIP:9735
[lncli] rpc error: code = Unknown desc = connection attempt to Peer2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@PublicIP:9735 is pending
```

and in logs I can see that lnd is trying to use the info in known peers db about the node i'm trying to reach: 

```
lnd.log:
PEER: unable to read message from 10.10.0.XX:43282: read tcp 10.10.0.28:9735->10.10.0.XX:48576: use of closed network connection
```

I'm forced to rely on my peers that will initiate a connection to me in order to put the channel in the active state. In fact, if I take a connected incoming peer that was able to reconnect to me I get this:

```
lncli connect Peer3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@PublicIP:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 10.10.0.xx:44182
```

do you expect any issue (i.e. spoofing for DoS) if we try to store the peers using their advertised external ip instead of source ip of the tcp packet? we could set a fallback: if no advertised ip, store the source ip as it works now.

Thanks!

### My environment

* lnd 0.4
* OS: Linux 4.4.0-112-generic #135-Ubuntu 16.06
* bitcoind version 0.15.0100
* haproxy (official ubuntu repo) with frontend on the external ip listening on port 9735 and with backend on lnd machine on internal ip (10.10.0.0/24) on lnd listening port (9735)

### Steps to reproduce

Configure lnd behind haproxy (or even iptables/rinetd) and check the `lncli listpeers` output

### Expected behaviour

all peers configured with their external ip

### Actual behaviour

all inbound peers configured with the ip coming from the tcp packet?

**Comment by croll83** [comment]
Hi, after some more investigation I think that the relevant part of the code is in the server.go file, included in the peerConnected() method:

```
// peerConnected is a function that handles initialization a newly connected
// peer by adding it to the server's global list of all active peers, and
// starting all the goroutines the peer needs to function properly.
func (s *server) peerConnected(conn net.Conn, connReq *connmgr.ConnReq,
	inbound bool) {

	brontideConn := conn.(*brontide.Conn)
	addr := conn.RemoteAddr()
	pubKey := brontideConn.RemotePub()

	// We'll ensure that we locate the proper port to use within the peer's
	// address for reconnecting purposes.
	if tcpAddr, ok := addr.(*net.TCPAddr); ok {
		targetPort := s.fetchNodeAdvertisedPort(pubKey, tcpAddr)

		// Once we have the correct port, we'll make a new copy of the
		// address so we don't modify the underlying pointer directly.
		addr = &net.TCPAddr{
			IP:   tcpAddr.IP,
			Port: targetPort,
			Zone: tcpAddr.Zone,
		}
	}

	peerAddr := &lnwire.NetAddress{
		IdentityKey: pubKey,
		Address:     addr,
		ChainNet:    activeNetParams.Net,
	}

...

```

I think we should ensure that we locate the proper IP and port to use for reconnecting purposes:

```
if tcpAddr, ok := addr.(*net.TCPAddr); ok {
                targetIP := s.fetchNodeAdvertisedIP(pubKey)
		targetPort := s.fetchNodeAdvertisedPort(pubKey, tcpAddr)

		// Once we have the correct port, we'll make a new copy of the
		// address so we don't modify the underlying pointer directly.
		addr = &net.TCPAddr{
			IP:   targetIP,
			Port: targetPort,
			Zone: tcpAddr.Zone,
		}
	}
```

What I am proposing here is to retrive also the advertised IP from the Graph just like we do for the advertised port using the fetchNodeAdvertisedPort() method. We could simply add a similar method fetchNodeAdvertisedIP() or modify the existing one.

I would like to understand which are the drawbacks (security?) using this approach.

**Comment by Roasbeef** [comment]
> I think we should ensure that we locate the proper IP and port to use for reconnecting purposes:

How can we locate the proper IP, if the node _isn't_ advertise from the graph, and it was an inbound connection (and your proxy swapped out the true source IP)?

**Comment by croll83** [comment]
Btw this part is a comment found in the source file :)

I think 'we should ensure that we locate the proper IP and port to use for reconnecting purposes:'

**Comment by croll83** [comment]
So? anyone willing to make this small fix? I'm not a golang programmer, I can try to do a PR but I'm not sure it would be a good result. Anyone willing to support me?

**Comment by Roasbeef** [comment]
Yes, the fix would also be to attempt to fetch the advertised IP and use that instead for any inbound connections. This also has ramifications to accepting connections over hidden services.

**Comment by croll83** [comment]
I made some tests editing server.go and it seems to work better, but I still have problems with nodes who I don't have open channels with. 

I'm getting advertised ip from here: 

node, err := s.chanDB.ChannelGraph().FetchLightningNode(pub)

So if the incoming node do not have a channel with me it will return err.

Is there any other way to retrieve the advertised ip?

**Comment by wpaulino** [comment]
As of #1159, we now fetch the advertised address rather than only the port.
