### ISSUE TITLE
TemporaryChannelFailure

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#1044]
### Background

Trying to make a payment to bitrefill. Have direct channel open but it ends with error.
My channels: http://wklej.org/id/3402250/

I have tried to restart lnd, but didnt help. Then whole rasp pi, also didnt help.  Now each time i try to pay invoicei dont get any response to command. Also there is a lot of this in logs:

> HSWC: ChannelLink(516950:1850:1) revocation window exhausted, unable to send: 1

I also have tried to pay invoice to other nodes but its same result only diffrenece i see in payment number:

>  [TRC] HSWC: ChannelLink(516950:1850:1) revocation window exhausted, unable to send: 2

### Your environment

* version of `lnd`: 0.4.1
* which operating system: Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoin core 15.1

my channels

```
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174",
            "channel_point": "07b7f24ecf0b6e7a2bbd213df6bbc42aab4adaca691406026609e6e5d8a4027e:1",
            "chan_id": "568151743041110017",
            "capacity": "200000",
            "local_balance": "199095",
            "remote_balance": "0",
            "commit_fee": "905",
            "commit_weight": "600",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "282",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed",
            "channel_point": "3c6ff49e3932730e5f6906452b877b3e1fccdeda0f9899916f87d4e24d07339b:1",
            "chan_id": "568392536100044801",
            "capacity": "170000",
            "local_balance": "168009",
            "remote_balance": "0",
            "commit_fee": "1991",
            "commit_weight": "600",
            "fee_per_kw": "2750",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "1",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "039195c0969d69f9a25839cb44bd5e858bd9e3971638959f0e657bffa6692b43f1",
            "channel_point": "30fc360cc2fc46f1a8a412f7479601237fe961c49b78a4fbbe80c7637e6bb5b3:0",
            "chan_id": "568501387796873216",
            "capacity": "249000",
            "local_balance": "247942",
            "remote_balance": "0",
            "commit_fee": "1058",
            "commit_weight": "600",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "112",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "152",
                    "hash_lock": "SX+9AYnP0H3sZaCBra+evR3HlSHJSXfX+AUfJhT1JTQ=",
                    "expiration_height": 517367
                }
            ],
            "csv_delay": 144,
            "private": false
        }
    ]
}

```
query routes for bitrefill node:

http://wklej.org/id/3402282/txt/

### Steps to reproduce

To be honest no clue. I was closing and opening channels yesterday. Funny thing is one open channel generated txtid that cant be found in any blockchain explorer and after like 16h this btcs are still in limbo. Dunno if this have anything to do with my current problem

### Expected behaviour

Invoice should be paid.

### Actual behaviour

```
lncli payinvoice lnbc950u1pdv30s0pp56ujyea4ze8kx4k678l7dr9f5sje0pq38xd2j4y534u5y793z566sdphgf5hgun9ve5kcmpqx4skxwrzv5cxve348qmnwcesxqcrge3hv56rxdscqzysxqzuy445h23f009k8w52hhasf7cqf22pm22wfyd0t4ygrxnlnej8thgx3hrzt9qc5er3tr9jf5xmafrqf5kmscxek6gt7ewaqycar7zzt9xspgegh7k
{
        "payment_error": "unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0x1776b320)({\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  01 02 27 62 2d 4d d0 bc  18 4c a5 a1 af fe 0f 6c  |..'b-M...L.....l|\n  00000010  c7 87 27 86 2e e3 95 2b  91 0a 80 55 8e 8d 90 e4  |..'....+...U....|\n  00000020  5e 3b 0b 5f ba 26 13 34  74 32 0f 81 cb cd 05 28  |^;._.\u0026.4t2.....(|\n  00000030  8f f5 63 54 fa 10 79 c4  cb dc d3 28 0f 7a 60 cd  |..cT..y....(.z`.|\n },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 00000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26fddfb,\n ShortChannelID: (lnwire.ShortChannelID) 7:14509568:869,\n Timestamp: (uint32) 23238,\n Flags: (lnwire.ChanUpdateFlag) 16237,\n TimeLockDelta: (uint16) 0,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 3940649673949184 mSAT,\n BaseFee: (uint32) 0,\n FeeRate: (uint32) 65536000\n})\n)",
        "payment_preimage": "",
        "payment_route": null
}
```

Now after i restarted whole thing lncli payinvoice to any bitrefill invoice does nothing. It just freezes and there is no response.

Some logs after i restarted rasp: https://drive.google.com/open?id=1vM966Ld9tkhyAQcma0n92PvS6qvkNG0T

**Comment by halfik** [comment]
Ok i just opened channel to blockstream store and makde payment that went thorough.

> revocation window exhausted
is no longer appearing in longs.

I also check payment to bitrefill (after i closed all previous channels, including one with them) with out dirrect channel and also went thorough. First try didnt work there was probem with one of nodes in route but second one went ok.

**Comment by Roasbeef** [comment]
`TemporaryChannelFailure` means that (likely the final) route attempted didn't have enough available channel bandwidth. It's an in-protocol error and not indicative of a bug (as far as I can see within `lnd`). AFAIK, Bitrefill only has a single node, so if they're updating it or something, then it may not be very available. 

One of your channels looks like it desynchronized, this may have been to a node never responding to the messages required to update a channel. You'll likely need to force close that channel.
