### ISSUE TITLE
unable to close channel with active htlcs

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#1045]
### Background

Can close channel because there is pending htlcs:

> lncli listchannels
> {
>     "channels": [
>         {
>             "active": true,
>             "remote_pubkey": "039195c0969d69f9a25839cb44bd5e858bd9e3971638959f0e657bffa6692b43f1",
>             "channel_point": "30fc360cc2fc46f1a8a412f7479601237fe961c49b78a4fbbe80c7637e6bb5b3:0",
>             "chan_id": "568501387796873216",
>             "capacity": "249000",
>             "local_balance": "247942",
>             "remote_balance": "0",
>             "commit_fee": "1058",
>             "commit_weight": "600",
>             "fee_per_kw": "1250",
>             "unsettled_balance": "0",
>             "total_satoshis_sent": "0",
>             "total_satoshis_received": "0",
>             "num_updates": "114",
>             "pending_htlcs": [
>                 {
>                     "incoming": false,
>                     "amount": "152",
>                     "hash_lock": "SX+9AYnP0H3sZaCBra+evR3HlSHJSXfX+AUfJhT1JTQ=",
>                     "expiration_height": 517367
>                 }
>             ],
>             "csv_delay": 144,
>             "private": false
>         }
>     ]
> }

Thing is this pending htlcs is pengind since yesterday.

### Your environment

version of lnd: 0.4.1
which operating system: Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
version of btcd, bitcoind, or other backend: bitcoin core 15.1

### Steps to reproduce

No clue but maybe it has something to do with my other issue:
https://github.com/lightningnetwork/lnd/issues/1044

### Expected behaviour

htlcs shoudnt be pending for like 14-16h?

### Actual behaviour

> Close all active and inactive channels? Inactive channels will be closed unilaterally, so funds within them will be locked for a few blocks (CSV delay) before they can be spent. (yes/no): yes
> {
>         "remote_pub_key": "039195c0969d69f9a25839cb44bd5e858bd9e3971638959f0e657bffa6692b43f1",
>         "channel_point": "30fc360cc2fc46f1a8a412f7479601237fe961c49b78a4fbbe80c7637e6bb5b3:0",
>         "closing_txid": "",
>         "error": "unable to close channel: rpc error: code = Unknown desc = cannot co-op close channel with active htlcs"
> }

**Comment by Roasbeef** [comment]
If you have a channel with an active HTLC, then you'll need to force close it in the case that you wish to deliver the funds on-chain. 

> htlcs shoudnt be pending for like 14-16h?

Depends on the length of the route and the time locks involved.
