### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#1053]
### Background

Describe your issue here.

Left LND running, came back to it down. Started it back up and I get a start up crash every reboot.

### Your environment

* version of `lnd`  commit hash 13945de8060ad42e077988c1cf69e205dc11e528
* which operating system (`uname -a` on *Nix) . x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: btcd
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

StartLND, get 200 active chans on mainnet run for a while, but probably not too relevant.

### Expected behaviour

Tell us what should happen
No crasherino.

### Actual behaviour

Tell us what happens instead

Get a crash with the error below.
Starting up LND:
https://pastebin.com/QDLTqjcQ

Crash log:
https://pastebin.com/HLNuaTVL

**Comment by halseth** [comment]
Call to `ogHTLC := remoteUpdateLog.lookupHtlc(wireMsg.ID)` returns `nil`.

**Comment by Roasbeef** [comment]
Odd part here is that, on restart we get this, however it's actually a _pending open_ transaction. So there's no way that if could even get an HTLC add for the remote peer to cancel (which is what looks like is going on).
