### ISSUE TITLE
Peer/Channel incorrectly shows up as inactive, establishing new channels to them fails

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#1059]
### Background

An lnd node peered with, and opened a channel to, my node. At some later point the channel went inactive, despite both nodes still being up. Trying to establish new channels to the peer fails with "[lncli] rpc error: code = Unknown desc = unable to find peer ".

### Your environment

* version of `lnd`
lncli version 0.4.1 commit=aa3dab62410073301837a39681fcbaaaac434d8e
* which operating system (`uname -a` on *Nix)
Linux notabug 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.16.99.0-9b8b1079d
* any other relevant environment details

My node is 03aeca3b52e028b68c67d01a62eede65df55bda5cd04e4341ac42688d25fc151cd .

lncli listchannels
...
        {
            "active": false,
            "remote_pubkey": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
            "channel_point": "5c1c8d32833503860b5b7bcac586a0288e97ed5ed98c121f99adc3939c99ce11:0",
            "chan_id": "567054430495113216",
            "capacity": "200000",
            "local_balance": "0",
            "remote_balance": "199095",
            "commit_fee": "905",
            "commit_weight": "552",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "62",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
...

lncli getnodeinfo 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b
{
    "node": {
        "last_update": 1523294700,
        "pub_key": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
        "alias": "rompert.com🔵",
        "addresses": [
            {
                "network": "tcp",
                "addr": "167.99.50.31:9735"
            },
            {
                "network": "tcp",
                "addr": "[2604:a880:800:a1::1375:5001]:9735"
            }
        ],
        "color": "#0000ff"
    },
    "num_channels": 396,
    "total_capacity": "82934499"
}

### Steps to reproduce

Unknown. Perhaps have node 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b establish a channel with your node and wait for it to go inactive.

### Expected behaviour

A node that is up and has many healthy channels should be able to have a healthy channel with another node that has many healthy channels.

### Actual behaviour

Channel shows as inactive. New channels cannot be opened to peer.

**Comment by Roasbeef** [comment]
If the channel was shown as "inactive: false", then that means it didn't have an established connection to the remote peer. 

> A node that is up and has many healthy channels should be able to have a healthy channel with another node that has many healthy channels.

Number of channels doesn't matter. What matters is that you have a _connection_ to the other node. 

> Trying to establish new channels to the peer fails with "[lncli] rpc error: code = Unknown desc = unable to find peer "

Which means that you didn't have a connection to the other node.

**Comment by merehap** [comment]
Sorry, I forgot to mention that I was getting an "already connected to peer" error previously. Oddly that is not the case now that the remote peer has been restarted, so I'm no longer able to repro this. I'll close this for now and re-open if I'm able to repro again.
