### ISSUE TITLE
Half existing channel

### ISSUE THREAD

**Issue by cactuska** [lightningnetwork/lnd#1061]
### Background

I have tried the lnd in autopilot mode on BTC mainnet, and found that, I have a half existing channel

### Your environment

* version of `lnd`
lnd version 0.4.1-beta commit=

* which operating system (`uname -a` on *Nix)
Linux btcnode 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

* version of `btcd`, `bitcoind`, or other backend
Bitcoind /Satoshi:0.15.1/

* any other relevant environment details

### Steps to reproduce

I run my lnd as a service with autopilot on since a week, and everything worked, until I found that yesterday a channel was created, which is not existing on web explorers like https://1ml.com, or https://lnmainnet.gaben.win/

### Expected behaviour

Active channel, which is visible on the network

### Actual behaviour

I have a channel, with null object for node2_policy
{
    "channel_id": "568752076377751553",
    "chan_point": "7fd9eb9a5c06ddd92bad03a14f22e44e27dfded26dc805863e8b570b51b9538c:1",
    "last_update": 1523222531,
    "node1_pub": "02997ed208bb98c3433dbe18c231391fcd8c5cbe16fbd25b692239ce8c80d41541",
    "node2_pub": "03f8d1ae8e36d19ed96fefa02f6f6c33fe69ed2fff5ece582b013a92c9077ee396",
    "capacity": "x" - masked,
    "node1_policy": {
        "time_lock_delta": 144,
        "min_htlc": "0",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1"
    },
    "node2_policy": null
}
Channel state is false, and if I try to close the channel, i receive the following error:

$ lncli closechannel --funding_txid 7fd9eb9a5c06ddd92bad03a14f22e44e27dfded26dc805863e8b570b51b9538c
[lncli] rpc error: code = Unknown desc = unable to find channel

It seems this channel is only seen by my node.
I hope, I will receive my funding balace back once, but want to let you know about the issue

**Comment by Roasbeef** [comment]
> $ lncli closechannel --funding_txid 7fd9eb9a5c06ddd92bad03a14f22e44e27dfded26dc805863e8b570b51b9538c
> [lncli] rpc error: code = Unknown desc = unable to find channel

The remote peer isn't online, so in this case if you require the funds immediately, then you need to force close the channel.

**Comment by Roasbeef** [comment]
>  until I found that yesterday a channel was created, which is not existing on web explorers like https://1ml.com, or https://lnmainnet.gaben.win/


Explorers aren't authoritative, so don't worry if your channels don't show up or anything. Your node is the only source of truth concerning your channels.

**Comment by cactuska** [comment]
Thank you, but i think the remote node is online. I have a connectction with it:

[2018.04.09 - 22:37] ~/scripts $ lncli listpeers
{
    "peers": [
        {
            "pub_key": "03f8d1ae8e36d19ed96fefa02f6f6c33fe69ed2fff5ece582b013a92c9077ee396",
            "address": "159.89.127.22:9735",
            "bytes_sent": "16062584",
            "bytes_recv": "3001795",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": false,
            "ping_time": "122058"
        },

**Comment by Roasbeef** [comment]
It seems that the remote node just never advertised the channel, the solution is to force close the channel.

**Comment by Roasbeef** [comment]
If the remote node never completed the final steps needed to finalize the channel, then that's why it would be displayed as "inactive".

**Comment by cactuska** [comment]
Thanks, hope it helps others, if they have same symptoms in the future
