### ISSUE TITLE
Channel peer reconnection

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1063]
### Background

After LND restart channel peers are not getting connected.
I created the P2P and LND network according to https://dev.lightning.community/tutorial/01-lncli/index.html
### Your environment

* lnd version 0.4.1-beta commit=13945de8060ad42e077988c1cf69e205dc11e528
* Darwin admins-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* btcd version 0.12.0-beta
* simnet

### Steps to reproduce

Create the P2P and Channels according to https://dev.lightning.community/tutorial/01-lncli/index.html

lncli-alice connect  02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@localhost:10012

lncli-alice listpeers
{
    "peers": [
        {
            "pub_key": "02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219",
            "address": "127.0.0.1:**10012**",
            "bytes_sent": "2074",
            "bytes_recv": "2074",
            "sat_sent": "10000",
            "sat_recv": "0",
            "inbound": false,
            "ping_time": "0"
        }
    ]
}

Next, restart Alice

2018-04-10 00:11:51.908 [DBG] CMGR: Attempting to connect to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:**9735** (reqid 1)
2018-04-10 00:11:51.908 [DBG] CMGR: Failed to connect to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:**9735** (reqid 1): dial tcp 127.0.0.1:9735: connect: connection refused
2018-04-10 00:11:51.908 [DBG] CMGR: Retrying connection to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:**9735** (reqid 1) in 5s
2018-04-10 00:11:56.913 [DBG] CMGR: Attempting to connect to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:**9735** (reqid 1)
2018-04-10 00:11:56.913 [DBG] CMGR: Failed to connect to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:9735 (reqid 1): dial tcp 127.0.0.1:9735: connect: connection refused
2018-04-10 00:11:56.913 [DBG] CMGR: Retrying connection to 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@127.0.0.1:9735 (reqid 1) in 10s

Clearly, LND tries to restore the connection to the peer but is using the wrong port for that.

### Expected behaviour

Should connect

### Actual behaviour

Fail to connect and I need to restore the connection manually

**Comment by Roasbeef** [comment]
You're on localhost. If Both peers aren't properly advertising their IP's (using `--externalip`), then we don't know what port to use to reconnect. Note that the listening port is different from the port that's assigned when we accept an inbound connection.

**Comment by offerm** [comment]
Adding --externalip=localhost:10012 to bob's LND solved the problem and manually restore the connection solved the problem for later restarts.

I would consider to update the document at https://dev.lightning.community/tutorial/01-lncli/index.html  with this information, and a short explaination why the port used to create the conenction can't be used to restore it instead of the default LND port.

If Alice created a connection to Bob using 
lncli-alice connect 02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219@localhost:**10012**

I would expect that a restore of the connection will use the same port. 
Adding --externalip solves the problem but may also invite other nodes to connect to Bob while Bob may not like it.

**Comment by offerm** [comment]
Without the --externalip, after the connection from Alice to Bob established. Alice LND is well aware of the port that bob is using:
lncli-alice listpeers
{
"peers": [
{
"pub_key": "02d659831262497a85928521fe1f39f700df26276204e241f25d5d6a77a98f9219",
"address": "127.0.0.1:**10012**",
"bytes_sent": "2074",
"bytes_recv": "2074",
"sat_sent": "10000",
"sat_recv": "0",
"inbound": false,
"ping_time": "0"
}
]
}

looks to me this information is not kept to the persistent storage.

Let me know if I should dig into this.

**Comment by Roasbeef** [comment]
Ah realized a recent patch somehow was slightly incorrect. Pushing a fix shortly!
