### ISSUE TITLE
updatechanpolicy min_htlc

### ISSUE THREAD

**Issue by littleskunk** [lightningnetwork/lnd#1065]
### Background

updatechanpolicy can't change `min_htlc`

### Your environment

* lncli version 0.4.1
* LXC Debian Jessie
* Bitcoin Core RPC client version v0.16.0

### Steps to reproduce

`lncli updatechanpolicy --help`

### Expected behaviour

I would like to update `min_htlc` for all channels.

### Actual behaviour

`min_htlc` is missing.

**Comment by halseth** [comment]
I think `min_htlc` is a static parameter set during channel opening, and cannot be changed without a protocol change? https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#the-open_channel-message

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/1065#issuecomment-381067065
