### ISSUE TITLE
Routequery succeeds, payinvoice fails...timeout.

### ISSUE THREAD

**Issue by AmazingDroopy** [lightningnetwork/lnd#1069]
### Background

With 2 nodes running LND v0.4.1-beta on a raspberry pi (Courtesy to Stadicus) and both with active channels to the network it fails to pay an invoice or route a payment via public internet.

When adding a direct channel between the nodes, the payment succeeds.

### Your environment
Node A:

$ lncli getinfo
{
    "identity_pubkey": "035716176a55c5093c22d4199c811754313539a7149932cb07eb88a2419cb74ef2",
    "alias": "Amazing_Droopy_2 [LND]",
    "num_pending_channels": 0,
    "num_active_channels": 1,
    "num_peers": 6,
    "block_height": 517515,
    "block_hash": "000000000000000000008952fc103538d7d4050f0245f2e64ae0260914fa7e2d",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "035716176a55c5093c22d4199c811754313539a7149932cb07eb88a2419cb74ef2@92.111.179.34:9735"
    ],
    "best_header_timestamp": "1523352867"
}

Node B:

$ lncli getinfo
{
    "identity_pubkey": "03c992c210b08ebb7ccbb2ba26e09bb4a8d536daa6f8702e8b14627a338c35446a",
    "alias": "Amazing_Droopy [LND]",
    "num_pending_channels": 2,
    "num_active_channels": 4,
    "num_peers": 13,
    "block_height": 517515,
    "block_hash": "000000000000000000008952fc103538d7d4050f0245f2e64ae0260914fa7e2d",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "03c992c210b08ebb7ccbb2ba26e09bb4a8d536daa6f8702e8b14627a338c35446a@82.95.192.186:9735"
    ],
    "best_header_timestamp": "1523352867"
}

### Steps to reproduce
Check route from Node A to Node B:

$ lncli queryroutes "03c992c210b08ebb7ccbb2ba26e09bb4a8d536daa6f8702e8b14627a338c35446a" --amt 250

-> Multiple routes listed, all showing the channel IDs in open channel list of receiving node. 

  "total_time_lock": 517969,
            "total_fees": "2",
            "total_amt": "252",
            "hops": [
                {
                    "chan_id": "568925799164674049",
                    "chan_capacity": "22431",
                    "amt_to_forward": "251",
                    "fee": "1",
                    "expiry": 517825
                },
                {
                    "chan_id": "567168779613241345",
                    "chan_capacity": "250000",
                    "amt_to_forward": "251",
                    "fee": "0",
                    "expiry": 517681
                },
                {
                    "chan_id": "566334250287366144",
                    "chan_capacity": "175000",
                    "amt_to_forward": "251",
                    "fee": "0",
                    "expiry": 517667
                },
                {
                    "chan_id": "567669057419476993",
                    "chan_capacity": "55000",
                    "amt_to_forward": "250",
                    "fee": "1",
                    "expiry": 517523
                },
                {
                    "chan_id": "568075876720443393",
                    "chan_capacity": "40214",
                    "amt_to_forward": "250",
                    "fee": "0",
                    "expiry": 517523
                }

Requesting the payment from node B:

$ lncli addinvoice --memo "Pay me 250 via public nodes" --amt 250
{
	"r_hash": "abf85e602037a71803a8b320b28bf2c6cfdad91db7a758b64cb801d96eadfe4b",
	"pay_req": "lnbc2500n1pdvepxupp540u9ucpqx7n3sqagkvst9zljcm8a4kgak7n43djvhqqajm4dle9sdpv2pshjgrdv5srydfsypmxjcfqwp6kymrfvvsxummyv4escqzys43rs3h7ummyrx9yrgr5h4sel9xew0pttta5yjnjn9lxc8sf3fe2rvmtzv9xveu096gw88vn6z9cqx8f30gqpnd5tjgq9usanq69uvhgqnc2f4e"
}

Issuing the payment on node A:

$ lncli payinvoice "lnbc2500n1pdvepxupp540u9ucpqx7n3sqagkvst9zljcm8a4kgak7n43djvhqqajm4dle9sdpv2pshjgrdv5srydfsypmxjcfqwp6kymrfvvsxummyv4escqzys43rs3h7ummyrx9yrgr5h4sel9xew0pttta5yjnjn9lxc8sf3fe2rvmtzv9xveu096gw88vn6z9cqx8f30gqpnd5tjgq9usanq69uvhgqnc2f4e"
{
	"payment_error": "payment attempt not completed before timeout of 1m0s",
	"payment_preimage": "",
	"payment_route": null

**Comment by Roasbeef** [comment]
If you run master, the timeout issue should be resolved. 

Also it's important to note that `queryroutes` simply _looks_ at the graph for _reachability_. For example it may show a route, but if all the nodes are offline, or all their channels are worst-case unbalanced, then you won't actually be able to establish a payment.

**Comment by Roasbeef** [comment]
It's also important to understand that if you don't have any available inbound capacity, then you won't actually be able to receive payments.

**Comment by Roasbeef** [comment]
> is their an easy way to query inbound capacity?

`lncli channelbalance`.
