### ISSUE TITLE
initial connect sends same node info hundreds of times

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1072]
### Background

lnd sends a lot of msg 257 for the same node at initial connect
i've seen some nodes being sent 155 times within first few seconds. probably once per channel or something.
probably should be easy to limit to only once per node at first connect, and cut down the traffic a lot!

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
This is fixed by a new protocol extension. Please refer to: https://github.com/lightningnetwork/lightning-rfc/pull/392

Our implementation should be landing later this week.

**Comment by Roasbeef** [comment]
Actually re-read this issue, and it points out an optimization: to de-dup node announcements during the current "naive" initial table dump.

**Comment by robtex** [comment]
thank you.
and i was going to check this ticket to re-read your pointers about the new protocol features :)
the enhanced new protocols to bundle stuff together and resuming from a certain point is very interesting as well, but yes i agree de-duping is probably a good beginner task and quite quick fix.
