### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#1073]
### Background

Last night we had several powercuts, after lnd fails to start and run but panics and chrashes out.

### Your environment

lnd version 0.4.0-beta
 4.13.0-36-generic #40~16.04.1-Ubuntu
bitcoind 16.0

### Steps to reproduce

start lnd

### Expected behaviour

lnd starts and runs 

### Actual behaviour

lnd panics and chrashes

http://paste.ubuntu.com/p/GSbdcvHZwC/

**Comment by redstorm1** [comment]
updated lnd to latest
[INF] LTND: Version 0.4.1-beta commit=12cb35a6c9b4e9ee4f4ecb4b42a81602c7abbb37
appears to have solved the issue. 

Monitoring

**Comment by Roasbeef** [comment]
If updating resolved the issue, I'll close out unless there're further updates.
