### ISSUE TITLE
[tests] Expand chainntnfs tests to check mempool spends

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1074]
A recent addition to `btcd` was merged, making it notify about spends already in the mempool when a `NotifySpent` request comes in: https://github.com/Roasbeef/btcd/pull/20

This will now make it possible to expand the tests added in https://github.com/lightningnetwork/lnd/pull/969, resolving the following `TODO`: https://github.com/lightningnetwork/lnd/blob/6b6a616b1e6c6974226fcb2c8b09e089117ea77b/chainntnfs/interface_test.go#L545

### Steps:
- [x] Update the `btcd` dependency to point to latest `roasbeef/btcd`
- [ ] Expand test with clients that are registered first after we have seen the spending tx in the mempool.

**Comment by githubsands** [comment]
Hey halseth can you assign me this issue

**Comment by halseth** [comment]
@githubsands Feel free to pick it up! 😀
