### ISSUE TITLE
startup option for channel_reserve_satoshis (LND)

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1083]
### Background

Today,  when a channel is opened by A to B, A is requesting B to hold 1% of the capacity in reserve if and when B has a balance greater or equal of the reserve amount (channel_reserve_satoshis).  This can lead to strange situations like the case when A opens a 1,000,000 sat channel to B, A sends 10,000 sat to B but B can't do anything with these 10,000 sat as they should be kept as reserve. 

> Bolt 2: channel_reserve_satoshis:  1% of the channel total is suggested. Each side of a channel maintains this reserve so it always has something to lose if it were to try to broadcast an old, revoked commitment transaction.

Clearly, if B had in the past most of the capacity  (say, 50%-99%) and is now having only 1%, this 1% will not keep the "wrong" person from trying to broadcast an old, revoked commitment transaction.

**I would like to suggest a new startup Option --chanreserve which is the percentage of the capacity to be  used as channel_reserve_satoshis. Default will be 1%.** 

Please let me know if you are happy with this and I will try to add support.

Thanks

Offer

**Comment by Roasbeef** [comment]
> This can lead to strange situations like the case when A opens a 1,000,000 sat channel to B, A sends 10,000 sat to B but B can't do anything with these 10,000 sat as they should be kept as reserve.

This will _always_ be the case. B can't start to send outbound HTLC's until they're safely above the reserve. 

> this 1% will not keep the "wrong" person from trying to broadcast an old, revoked commitment transaction.

It's that that it will "keep" them from broadcasting. The goal is to avoid a _costless_ attack to ensure that the risk of failure to attempt a contract is tangible at all times.

**Comment by offerm** [comment]
Thanks.

I get your view point. Still I would claim:

1. For an attacker, Risking 1% of the channel capacity of a possible win of 30%-99% provides a good risk reward. If she knows that her peer is offline or not monitoring the chain, she may take the risk. So 1% (or even 5%) does really provides protection. Clearly, 1% is better then 0%.

2.  In situation where there is trust between the peers, setting the reserve to 0 may make sense. I have at least two usage scenarios  which are problematic to achieve without setting the fundee reserve to be zero.

**Taking your comments into account I suggest to implement this feature on the "openchannel" function and not as a startup/config option. Are you happy with this?**

**Comment by halseth** [comment]
Take a look at how the `remote_csv_delay` option is handled. It is both an option to `openchannel` and a default can be set at startup. A `chan_reserve` option can be added in a similar fashion.

**Comment by halseth** [comment]
This overlaps with #800 btw.

**Comment by offerm** [comment]
Sorry, I  have missed #800.

Thank you
