### ISSUE TITLE
Force close stuck, TX disappeared

### ISSUE THREAD

**Issue by BitBargain** [lightningnetwork/lnd#1091]
Some time ago a channel was closed. It's been sitting in pending_forced for very long so now I checked the TXID and it isn't in the blockchain, isn't in the mempool.

How can I get LND to give me the raw transaction so I can attempt to re-broadcast it? I'm worried about opening any more channels if I can lose the money because of failed closing transactions. I'd prefer to know what happened here and also be able to resolve it.

lnd version 0.4.1-beta commit=13945de8060ad42e077988c1cf69e205dc11e528 on a Debian with Bitcoind (0.16) as backend.

>    "pending_force_closing_channels": [
>        {
>             "channel": {
>                 "remote_node_pub": "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432",
>                 "channel_point": "7cbc012a8c8c1472d560b77a5dbe9759288647d671aa550925bc0d59c4ada2e9:1",
>                 "capacity": "5000000",
>                 "local_balance": "4999276",
>                 "remote_balance": "0"
>             },
>             "closing_txid": "14f0121bfc785806a224b60a3a8f009babfba06e1ede38a756816199810e886f",
>             "limbo_balance": "4999276",
>             "maturity_height": 0,
>             "blocks_til_maturity": 0,
>             "recovered_balance": "0",
>             "pending_htlcs": [
>             ]

**Comment by cyclopes2011** [comment]
I noticed your issue and wanted to point to my issue with appears similar.

[https://github.com/lightningnetwork/lnd/issues/1071](url)

**Comment by Roasbeef** [comment]
> How can I get LND to give me the raw transaction so I can attempt to re-broadcast it?

`lnd` will automatically rebroadcast transactions on start up. On restart, do you see your `bitcoind` reject the transaction?

**Comment by Roasbeef** [comment]
Looking at the chain, we see: https://www.smartbit.com.au/tx/7cbc012a8c8c1472d560b77a5dbe9759288647d671aa550925bc0d59c4ada2e9

Which has _both_ outputs spent, which means that all funds have been fully swept by `lnd`. So it would appear that this is related #1071, which will be fixed by #1017.

**Comment by Roasbeef** [comment]
> I'm worried about opening any more channels if I can lose the money because of failed closing transactions.

No money was lost, if you follow the link above, you'll see that all the funds were properly swept.

**Comment by BitBargain** [comment]
In response to your request for logs:

> 2018-04-13 12:36:12.584 [ERR] UTXN: Notification chan closed, can't advance output 14f0121bfc785806a224b60a3a8f009babfba06e1ede38a756816199810e886f:0
> 2018-04-13 12:36:14.702 [INF] UTXN: Commitment outpoint 14f0121bfc785806a224b60a3a8f009babfba06e1ede38a756816199810e886f:0 registered for confirmation notification.

Thanks for the clarification. That puts me at ease (hopefully it fixes not just the issue but will also remove this phantom / stuck tx). Feel free to close this ticket. Thanks again.

**Comment by 8KSS** [comment]
same as me;


Where is the 59K Satoshi?

Initial Balance;
lncli walletbalance
{
    "total_balance": "1006634",
    "confirmed_balance": "0",
    "unconfirmed_balance": "1006634"
}


Payments stuck for a few days now afer closeallchannels forced.

 lncli pendingchannels
{
    "total_limbo_balance": "467280",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "035f804103054d1d24aa4b1cbe29a90c06af2695c93adb6e7501dc143cffbc09bd",
                "channel_point": "870c55d150833a518e201765cae3d8827cca95b687094a76cc77551d8b3c0f06:1",
                "capacity": "81034",
                "local_balance": "80853",
                "remote_balance": "0"
            },
            "closing_txid": "96eb50eaec2d71c5ba4ea2b16a7b90751a47a9aa041d51037a5911834de988c6"
        },
        {
            "channel": {
                "remote_node_pub": "025e77156e4c5e1ed62f9ad113ac2115a981ee99fa05d95be9e43add7f785a9b4d",
                "channel_point": "b7bc21da6fb89c6ac3b61469bb5ee6e7103f93e5811caad0a5d250155329f008:1",
                "capacity": "153978",
                "local_balance": "153797",
                "remote_balance": "0"
            },
            "closing_txid": "b5b3e9f501a1f216e611062e63ecf30e58ee55f43f59a89fdb2f42a475d22ddd"
        },
        {
            "channel": {
                "remote_node_pub": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                "channel_point": "a061c52fef9a578f73204cfbf1f27310aa37543cf1018abc318a7754930f3ec6:1",
                "capacity": "110024",
                "local_balance": "109736",
                "remote_balance": "0"
            },
            "closing_txid": "1e80c3e1fdcf85c8df3da61d98192b25447d473c1b888906044bb04d76934836"
        },
        {
            "channel": {
                "remote_node_pub": "033c3a18d7ffe9e1eec718b45616b202cd98a8054b47e424fb56a0f2ea6877a13f",
                "channel_point": "69a03a186f7a6d1d3b3142ade35f8ce7d614f4a26c985b96c3e847d657546fd3:1",
                "capacity": "29577",
                "local_balance": "29396",
                "remote_balance": "0"
            },
            "closing_txid": "48d19746465c854084f90bef7674d2cad2c4ae89e5d6ab9e038be4224e4bf29a"
        },
        {
            "channel": {
                "remote_node_pub": "0350a241aca91b8f6a694f1643a93b2f5022c226ae7025868ddaf9c87e5d4e4e09",
                "channel_point": "315a6286fc8577aa0e29848222a5b91f549ca693487340ad8544669f646285ff:0",
                "capacity": "93679",
                "local_balance": "93498",
                "remote_balance": "0"
            },
            "closing_txid": "f7e8843655586b5a130ee085b25d3b42f30b6680ff20ba7c4de35781c272343a"
        }
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "0355157b4260b70c7f407a720c527a84e9522cd948e7a8ad92ae00773be52488e3",
                "channel_point": "e284f54f4cbc4cc6c8a95773650b9623bc0f0a68442b63b1705f3a1e3aa1ac8b:0",
                "capacity": "266885",
                "local_balance": "266704",
                "remote_balance": "0"
            },
            "closing_txid": "27e8bc7ac798e537be359e272936dae153a3e048ab3177c9750aefc28f60685e",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },
        {
            "channel": {
                "remote_node_pub": "0350a241aca91b8f6a694f1643a93b2f5022c226ae7025868ddaf9c87e5d4e4e09",
                "channel_point": "5e3a31d773e1e251a3eef87694e764cd8f0cb7aa185275568fc9c3e3c27d66ad:1",
                "capacity": "32113",
                "local_balance": "31932",
                "remote_balance": "0"
            },
            "closing_txid": "36e32efb0a7356b01664b389bcad57773740158ad075c37a1458ca27c13bb4fd",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ]
}

Current Balance;
{
    "total_balance": "947180",
    "confirmed_balance": "947180",
    "unconfirmed_balance": "0"
}





net in;1006634
Net out;947180


Loss;-59454



Never made a payment, paid additional fee's on-chain.

Where did it go?

**Comment by Roasbeef** [comment]
@8KSS for those last two channels, everything has been fully resolved on-chain, meaning all funds have been swept. It's possible that the sum of your fees across all those channels went up to 59k satoshis, as there were multiple instances a transaction fee is paid: when opening a channel, when closing a channel, when sweeping time-locked funds from a channel.

**Comment by Roasbeef** [comment]
Also if you do `listchaintxns`, which transactions are included?

**Comment by Roasbeef** [comment]
It's also the case that if you have any channels which at closing time had a "dusty" output, then those aren't able to be claimed, and will instead go to miner's fees.

**Comment by 8KSS** [comment]
{
    "transactions": [
        {
            "tx_hash": "9c974ced47bc0b75d5ea34ee0158a6906932d3c49977b5691130377fd91b6d2d",
            "amount": "1106810",
            "num_confirmations": 1095,
            "block_hash": "0000000000000000003d1c0fa13f9373f5471d4ab46722b4f8b37dddb06fbcce",
            "block_height": 517241,
            "time_stamp": "1523202090",
            "total_fees": "0",
            "dest_addresses": [
                "37KrUw2WE9wJcyP7nv9n1GEuhxW4CFdmGR",
                "13uXq2N3LpP3P1AtSbV1TWQ6TBbszomshe"
            ]
        },
        {
            "tx_hash": "74fe74027f10c59ba2c575571775d695ad7a67b7cad84cd5d78d41fb5b92a379",
            "amount": "-100176",
            "num_confirmations": 1091,
            "block_hash": "0000000000000000004b1ef0def18c0549541e090dcb9199721e6cad8f18ccdf",
            "block_height": 517245,
            "time_stamp": "1523204067",
            "total_fees": "176",
            "dest_addresses": [
                "bc1qlykhj7gkurptx4zdlsql4gv4fpnh5drk3yahcjlhwch3jz9hpfrquxmw27",
                "bc1qa45w3vh6zl9rh0v4k62yr7znx849sxxf58zywf"
            ]
        },
        {
            "tx_hash": "faac42fe33dfd3d457456fde310aff9e9c6b4f0a8d5fec84a7bc043679701aa8",
            "amount": "-100153",
            "num_confirmations": 1089,
            "block_hash": "0000000000000000004e4e712b8d6dd77f61681f061727922fc7267817bd7baf",
            "block_height": 517247,
            "time_stamp": "1523204788",
            "total_fees": "153",
            "dest_addresses": [
                "bc1quajc4wd0a8pzgcl8c9a4yj8p74eku34k2aq6y7rx30swfwclmw8scg6r8a",
                "bc1q2utu0dy0577vswz2k7gm23lzlxuxmj0j23ztsm"
            ]
        },
        {
            "tx_hash": "70bbbec912d53394434937b4c7f6d4a2ec4a0dbdf64daa943567e24c085d0da6",
            "amount": "-100153",
            "num_confirmations": 1086,
            "block_hash": "000000000000000000429f5fec52afdc16540ef5eda2d5a711a988db8041da46",
            "block_height": 517250,
            "time_stamp": "1523207188",
            "total_fees": "153",
            "dest_addresses": [
                "bc1qyfml8qcj6rqfj4he0ft60vqfw726zcwjz36exn94sn5z9vd2drsqprk02p",
                "bc1qnzmfzw5wag0446aap8u476ppuj5tuzcqd4g9tc"
            ]
        },
        {
            "tx_hash": "9cf94667f4932c7a5de3945fe1dcd38792ed668e3019f391f9221d4689c8f5b1",
            "amount": "-242584",
            "num_confirmations": 1081,
            "block_hash": "00000000000000000004b9e238f822a7bdf4104ffcc8ef44c22bef468a47facd",
            "block_height": 517255,
            "time_stamp": "1523209562",
            "total_fees": "306",
            "dest_addresses": [
                "bc1qttkh9e0gnllupvmye8j5khwc8gy9ku07588xrdpk7kn8v63yz9ysu09c7e",
                "bc1qfcyn75cqzmnw9l92mafgwtnuf2w6dzq86k63qw"
            ]
        },
        {
            "tx_hash": "e284f54f4cbc4cc6c8a95773650b9623bc0f0a68442b63b1705f3a1e3aa1ac8b",
            "amount": "-267191",
            "num_confirmations": 1079,
            "block_hash": "000000000000000000428a173468966d068f08f63f11c2d8db47d95ab861a32a",
            "block_height": 517257,
            "time_stamp": "1523210752",
            "total_fees": "306",
            "dest_addresses": [
                "bc1q6c8pha924qag9xwxqyxsk532h60wvggyxvy23j6qp9mpslwsgzasezqayu",
                "bc1q77tutdrdmpdqh7q7y6tprvdgsseql3j23dzap4"
            ]
        },
        {
            "tx_hash": "15c7ae08a0c2b361b0949a8ab8cf303014703d76c6c4ed83d0b96e43d048d60b",
            "amount": "49448",
            "num_confirmations": 1077,
            "block_hash": "0000000000000000001e00ceb49c819ce4b7d2ff4097345c83146bc81a5466c7",
            "block_height": 517259,
            "time_stamp": "1523212151",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qqs6ydfeeacj9x857ctwdde97uzg7a5p6ar9m2y"
            ]
        },
        {
            "tx_hash": "cc9bcf84953174c14473a510a1e7a32f6dc556677379c4f5a41549d4963b1a74",
            "amount": "49819",
            "num_confirmations": 1066,
            "block_hash": "000000000000000000173855d066a30d10598bb537df6e9f1c5c7260c3587ff6",
            "block_height": 517270,
            "time_stamp": "1523218909",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qmg97xsfzapplwqtj23weyptd6sh3e3zx08nwpr",
                "bc1qzm7rzvrt8gmlxp6hlrnazw3c8eammkdmmr7m92"
            ]
        },
        {
            "tx_hash": "a5cdf35837516aab6b2a29cfd82b391df820888a6f37c911ac3ef6be5b7acc4f",
            "amount": "-24951",
            "num_confirmations": 1063,
            "block_hash": "0000000000000000000765e613d057c8c8e2b9aa6f869cbc7bb9c60a4fbc1a1a",
            "block_height": 517273,
            "time_stamp": "1523221187",
            "total_fees": "612",
            "dest_addresses": [
                "bc1q098yc3prl42ly6xgtjdlllvzeuucht69y423d20rsaur7w49lh4s2m6tuk",
                "bc1q03dsr6r3xjkred35yp6qnjupz0l7s54jtjrxfz"
            ]
        },
        {
            "tx_hash": "308eba2e4e405b9ff3b6fcbaf0229253d3ce3f0c907eecc26eb50966fb6a1def",
            "amount": "-24868",
            "num_confirmations": 1062,
            "block_hash": "0000000000000000001d0572268c17bf1105f548730d3f595400621f0c1e33d5",
            "block_height": 517274,
            "time_stamp": "1523221313",
            "total_fees": "777",
            "dest_addresses": [
                "bc1qedegkw9zsxutmjnqtfxjcvupmcrj5yfl0ysvejwq655lzc2x9uwqluw4m9"
            ]
        },
        {
            "tx_hash": "07c539253aae202f9e2565b336090254725a8c1a99ca5f6bdf5a95f9eff7f97e",
            "amount": "23425",
            "num_confirmations": 1056,
            "block_hash": "000000000000000000171e0180e529175b64abdccf07fb5d8939c5df402770aa",
            "block_height": 517280,
            "time_stamp": "1523222852",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qcpeg4z27x3980mf36etuwdvk8n4zkkgc8vukht"
            ]
        },
        {
            "tx_hash": "f56105760ffecb543e7c258df90923d6ec8e6dc5061aa80c44ac706f005c8c86",
            "amount": "23539",
            "num_confirmations": 1055,
            "block_hash": "00000000000000000007a0598c0dfa22a62e695f8499c6e54fae5a6f13ceb3c2",
            "block_height": 517281,
            "time_stamp": "1523224213",
            "total_fees": "0",
            "dest_addresses": [
                "bc1q8m4caucwc5xf0g3ycvytacx0vejdvsn8udm65f"
            ]
      },
        {
            "tx_hash": "5e3a31d773e1e251a3eef87694e764cd8f0cb7aa185275568fc9c3e3c27d66ad",
            "amount": "-32334",
            "num_confirmations": 1029,
            "block_hash": "000000000000000000009d4941e841717bc0659dee2cf36a24e15766400fcd14",
            "block_height": 517307,
            "time_stamp": "1523235565",
            "total_fees": "221",
            "dest_addresses": [
                "bc1qep8nygcc04859rk9faegcca9pthdc6sd28t3up",
                "bc1qvxk0r76kj4uhggpmxclxesna6lpeh5nuyucqn9zwasz22kg392dsvk49lz"
            ]
        },
        {
            "tx_hash": "83933bc9f6ef890b4ad829b4daf3a9d40c7b984b695727e71db45062b61ee33e",
            "amount": "49515",
            "num_confirmations": 914,
            "block_hash": "0000000000000000001901ed133f6243d0e09996cc2cba0c02ac0995cb9ac5fa",
            "block_height": 517422,
            "time_stamp": "1523299592",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qxxqsjgsyu7jac30yv9wndv2zczw32ajjfan8gs"
            ]
        },
        {
            "tx_hash": "69a03a186f7a6d1d3b3142ade35f8ce7d614f4a26c985b96c3e847d657546fd3",
            "amount": "-31107",
            "num_confirmations": 913,
            "block_hash": "0000000000000000000fe118346644678212ec2258b450e78e6f4e97257d4f68",
            "block_height": 517423,
            "time_stamp": "1523300465",
            "total_fees": "1530",
            "dest_addresses": [
                "bc1qhza8qu93wu56jqu8h7fgmn9uezqznt4j76z6k5",
                "bc1qrccs7f597q6a2pewckfwmalzam7yulpy7elw3wvnjcvhkpfsxmesgsl0n2"
            ]
        },
        {
            "tx_hash": "cde8b0b50eac0371bf53fc5cb826104704d2c2c0f9cfd000ffac11f0a0357378",
            "amount": "242097",
            "num_confirmations": 698,
            "block_hash": "00000000000000000034fa3f2a40160414b8383b79fde2cad794c076f40107e0",
            "block_height": 517638,
            "time_stamp": "1523416750",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qzzrfwzk2j7pwt2uw8rxe4tpad76qmrz9yhxety"
            ]
        },
        {
            "tx_hash": "48d19746465c854084f90bef7674d2cad2c4ae89e5d6ab9e038be4224e4bf29a",
            "amount": "29396",
            "num_confirmations": 698,
            "block_hash": "00000000000000000034fa3f2a40160414b8383b79fde2cad794c076f40107e0",
            "block_height": 517638,
            "time_stamp": "1523416750",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qfaudg3c79qt6ka24j5vaakh2a692va24qn28uh"
            ]
        },
        {
            "tx_hash": "b7bc21da6fb89c6ac3b61469bb5ee6e7103f93e5811caad0a5d250155329f008",
            "amount": "-154131",
            "num_confirmations": 697,
            "block_hash": "00000000000000000024bb10868e4e0705f476def339971ea478cef6ede4d615",
            "block_height": 517639,
            "time_stamp": "1523417604",
            "total_fees": "153",
            "dest_addresses": [
                "bc1qwl9nkxw7npkgv48sxkstv23e9smfl9vywzekl8",
                "bc1q7q86lxgarst74qse6e664g2g3p35g94ganfl6vjqnn8cvh4xk4lqn8f7fq"
            ]
        },
        {
            "tx_hash": "a061c52fef9a578f73204cfbf1f27310aa37543cf1018abc318a7754930f3ec6",
            "amount": "-110245",
            "num_confirmations": 694,
            "block_hash": "0000000000000000001ede02615aa1d20085340fd575343606ad99145c4bbba3",
            "block_height": 517642,
            "time_stamp": "1523418467",
            "total_fees": "221",
            "dest_addresses": [
                "bc1q5auvgydauj8tkl5dx35dtc57p4ywx6tsj7szct",
                "bc1q2v5tzvuzqh006xtflpraf9gqqscqyhuukl3m3ewy6j2q6lh8n8ds7rqvmp"
            ]
        },
        {
            "tx_hash": "870c55d150833a518e201765cae3d8827cca95b687094a76cc77551d8b3c0f06",
            "amount": "-81392",
            "num_confirmations": 685,
            "block_hash": "0000000000000000002d20adf0060cf304355a851b2451564a52b682d7d51ed8",
            "block_height": 517651,
            "time_stamp": "1523422212",
            "total_fees": "358",
            "dest_addresses": [
                "bc1q3yscranux5jjasnr8gl73nt065r8d86dapzh8d",
                "bc1qge5xr7a555ymvweaut83hyfvc4hucap05n6py0gjrvusqevvyp3syav0jy"
            ]
        },
        {
            "tx_hash": "315a6286fc8577aa0e29848222a5b91f549ca693487340ad8544669f646285ff",
            "amount": "-93900",
            "num_confirmations": 682,
            "block_hash": "0000000000000000002f3d97213e775e21ec33fee04381fd8e193a4dd61c9d17",
            "block_height": 517654,
            "time_stamp": "1523423028",
            "total_fees": "221",
            "dest_addresses": [
                "bc1qj43uk8xhhyz50ve229xal0n73nqj3xfm0crfg2tmd894psnntfrqha29vd",
                "bc1qa2q47myrv0ykyhngmxfsqf6nlscv8q42k3yjm0"
            ]
        },
        {
            "tx_hash": "1e80c3e1fdcf85c8df3da61d98192b25447d473c1b888906044bb04d76934836",
            "amount": "109736",
            "num_confirmations": 623,
            "block_hash": "0000000000000000003376431f1927bec9cc690d44636f230ea22a6db5bbe6a5",
            "block_height": 517713,
            "time_stamp": "1523457794",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qaj0aeup5m9gj3tk86gvafcajqxnl2dygud5wg3"
            ]
        },
        {
            "tx_hash": "b5b3e9f501a1f216e611062e63ecf30e58ee55f43f59a89fdb2f42a475d22ddd",
            "amount": "153797",
            "num_confirmations": 622,
            "block_hash": "0000000000000000000e28622c0fd7d8bdd8f0029b99800b9790e5f15b5f5320",
            "block_height": 517714,
            "time_stamp": "1523457812",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qd0f8353jsmn8d7mjgap0geququzcw3w7ngv9td"
            ]
        },
        {
            "tx_hash": "f7e8843655586b5a130ee085b25d3b42f30b6680ff20ba7c4de35781c272343a",
            "amount": "93498",
            "num_confirmations": 622,
            "block_hash": "0000000000000000000e28622c0fd7d8bdd8f0029b99800b9790e5f15b5f5320",
            "block_height": 517714,
            "time_stamp": "1523457812",
            "total_fees": "0",
            "dest_addresses": [
                "bc1q3yrn9nmnedug70ehrzvlvknzk4jgsnfz4srnee"
            ]
        },
        {
            "tx_hash": "96eb50eaec2d71c5ba4ea2b16a7b90751a47a9aa041d51037a5911834de988c6",
        },
        {
            "tx_hash": "f7e8843655586b5a130ee085b25d3b42f30b6680ff20ba7c4de35781c272343a",
            "amount": "93498",
            "num_confirmations": 622,
            "block_hash": "0000000000000000000e28622c0fd7d8bdd8f0029b99800b9790e5f15b5f5320",
            "block_height": 517714,
            "time_stamp": "1523457812",
            "total_fees": "0",
            "dest_addresses": [
                "bc1q3yrn9nmnedug70ehrzvlvknzk4jgsnfz4srnee"
            ]
        },
        {
            "tx_hash": "96eb50eaec2d71c5ba4ea2b16a7b90751a47a9aa041d51037a5911834de988c6",
            "amount": "80853",
            "num_confirmations": 622,
            "block_hash": "0000000000000000000e28622c0fd7d8bdd8f0029b99800b9790e5f15b5f5320",
            "block_height": 517714,
            "time_stamp": "1523457812",
            "total_fees": "0",
            "dest_addresses": [
                "bc1q38hkhrdc8sp9n2ttvgyvq508vmk2zjfwm69vk2"
            ]
        },
        {
            "tx_hash": "6c19483e7c04d9ba1dd50e05fbb62b78f44701568721669aa53630d537eb6f0c",
            "amount": "298432",
            "num_confirmations": 537,
            "block_hash": "0000000000000000002e9d97ba959422043f3b9ec6301909f39946acd243b741",
            "block_height": 517799,
            "time_stamp": "1523503391",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qpsm0hn432wztf6m5nrmdjpzvwq6lajqnnnaaq3"
            ]
        },
        {
            "tx_hash": "b5316f61f5acbd8ca94d9cf0a6c60017cf972dc682ea6f454a43510b9efc1cf2",
            "amount": "-947180",
            "num_confirmations": 385,
            "block_hash": "00000000000000000036cfc2d0abdbf286603db9e8f53f9c76b12df9c8135760",
            "block_height": 517951,
            "time_stamp": "1523587508",
            "total_fees": "6000",
            "dest_addresses": [
                "16kKXtA9AN9LLgMS4pikTqUJuuJRPwFR5f"
            ]
        }
    ]
}

**Comment by 8KSS** [comment]
so total fees, 11187.  6000 was to get back to on-chain
Never spent a satoshi for anything, just opened/closed a few channels.

**Comment by Roasbeef** [comment]
@8KSS upon updating to the latest master, do the pending close transactions still persist? Also note that intermediate sweeping transaction won't show up in `listchaintxns`. By these I mean those transactions that are created when we spend HTLC transactions on our commitment, or when commitments are broadcast.

**Comment by 8KSS** [comment]
Nope didn’t spend anything.

**Comment by BitBargain** [comment]
> @8KSS upon updating to the latest master, do the pending close transactions still persist? 

For what it's worth, mine's still there.

>     "pending_force_closing_channels": [
>         {
>             "channel": {
>                 "remote_node_pub": "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432",
>                 "channel_point": "7cbc012a8c8c1472d560b77a5dbe9759288647d671aa550925bc0d59c4ada2e9:1",
>                 "capacity": "5000000",
>                 "local_balance": "4999276",
>                 "remote_balance": "0"
>             },
>             "closing_txid": "14f0121bfc785806a224b60a3a8f009babfba06e1ede38a756816199810e886f",
>             "limbo_balance": "4999276",
>             "maturity_height": 0,
>             "blocks_til_maturity": 0,
>             "recovered_balance": "0",
>             "pending_htlcs": [
>             ]
>         }
>     ]
> }

lncli version 0.4.1 commit=b0709b45f7af9314481d06e617b1cee088fd708e

**Comment by Roasbeef** [comment]
We recently fixed another bug related to sending out notification of spends that are _already_ confirmed in the chain. Note that this only affected the `btcd` chain backend.

**Comment by BitBargain** [comment]
Is this something that should be cleared up in the latest version?

lnd version 0.4.1-beta commit=86fd9e361e04716b6a0d2e7146d6c19c0b4f05b5

Still seeing this stuck TX :(

**Comment by Roasbeef** [comment]
Yes, as in we'll always only act on the ultimately confirmed commitment transaction. In your case, both outputs have been fully spent on the transaction, meaning that if you had any funds, they've been swept into the wallet.

**Comment by BitBargain** [comment]
That'll have to work, thanks.

In the long run it'd be preferable if channels couldn't get stuck this way in the first place to have to 'clean up' after them. I don't know how easily this is doable. I'm sure there are challenges. But still.

Many ghost channels piling up over time does not sound like a good thing to live with and it's suspcious that the solution could be automated. Anyway, I'm sure there are priorities, so for now a manual cleanup method is OK. Thanks in advance.

**Comment by Roasbeef** [comment]
> In the long run it'd be preferable if channels couldn't get stuck this way in the first place to have to 'clean up' after them.

Totally, that PR that just landed clears up all instances of weird situations like this we're aware of. 

> Many ghost channels piling up over time does not sound like a good thing to live with

Defiantly, they shouldn't pile up at all. What you're seeing is lingering behavior of the recently fixed bug. When we fixed the bug, we _could_ have remove the faulty channels in an automated fashion. But then with that, there's a risk that we'd accidentally remove a non-faulty channel. As a result, it's safer to give users tools to pin point these faulty channels and remove them manually.
