### ISSUE TITLE
lnd tries to reconnect to peers it doesn't have active channels with

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#1100]
### Background

My node is trying to reconnect to this two nodes over and over:
022c715b377856f5e176c52dfbe1f19b0283c4a85d563b1f09a9c7d9b6820ec375
034f8f64c087a8deebb47d03082ec5b27e521b32396f775d0e953b1c98530dc728

I tried to connect to them manualy but they refuse connection.
Im guesing they are behind firewall or just have bad externalip set.

### Your environment

* version of `lnd`: lncli version 0.4.1 commit=bc029b9cd4c15ff974c4e232fb4a606e9fea4f8c
* which operating system (`uname -a` on *Nix): Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoin core 15.1

### Steps to reproduce

I belive once my node was connected to this 2 peers. At at some point they stop accepting connections, while my node is trying to reconnect ignoring fact that they refuse.

### Expected behaviour

Node should stop trying to reconnect to nodes that refuse incoming connection after few attemnts?

### Actual behaviour

Node trying to reconnect over and over and there is no way to prevent that. This 2 nodes are not on peers list so i cant discconect.

**Comment by halfik** [comment]
@Roasbeef i dont belive i have any channels with this nodes. I think i had channels with them but it was long time ago.

My channels: http://wklej.org/id/3411819/

**Comment by offerm** [comment]
I managed to reproduce it. It is simple actually.

1. open a channel with a peer. let it become active (confirmations)
2. close the channel and let it confirm
3. restart LND

LND will try to reconnect to the peer.
In log you can find this:

2018-04-18 16:42:45.944 [DBG] SRVR: Attempting persistent connection to channel peer 026d2f05b3d01269def3941f79005d62c0ba124d93aa6b81fc200329188a59a49e@94.210.58.186:9735

At LND start there is a call to FetchAllLinkNodes. LND tries to establish connection to the list coming back from FetchAllLinkNodes.
I have checked nodes.go which maintains a database of LinkNodes and couldn't find a method to remove a LinkNode for the database.  As such, I believe that once you have a channel with a peer LND will always try to connect to it even if the channel is closed. Not really nice :-)

Hope this is not a big BS from me.
