### ISSUE TITLE
lnd crash, panic: page 1072 already freed

### ISSUE THREAD

**Issue by plasm0r** [lightningnetwork/lnd#1107]
### Background

lnd is crashing during startup:

Attempting automatic RPC configuration to bitcoind
Automatically obtained bitcoind's RPC credentials
2018-04-17 22:19:08.109 [INF] LTND: Version 0.4.1-beta commit=
2018-04-17 22:19:08.110 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-04-17 22:19:08.112 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2018-04-17 22:19:08.119 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-04-17 22:19:08.120 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-04-17 22:19:08.121 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
2018-04-17 22:19:20.759 [INF] LNWL: Opened wallet
2018-04-17 22:19:21.159 [INF] LTND: Primary chain is set to: bitcoin
2018-04-17 22:19:21.159 [INF] LTND: Initializing bitcoind backed fee estimator
2018-04-17 22:19:27.366 [INF] LNWL: Opened wallet
2018-04-17 22:19:27.371 [INF] LNWL: Started listening for blocks via ZMQ on tcp://127.0.0.1:29000
2018-04-17 22:19:33.627 [INF] LNWL: The wallet has been unlocked without a time limit
2018-04-17 22:19:33.628 [INF] LTND: LightningWallet opened
2018-04-17 22:19:33.657 [INF] HSWC: Restoring in-memory circuit state from disk
2018-04-17 22:19:33.658 [INF] HSWC: Payment circuits loaded: num_pending=6, num_open=6
2018-04-17 22:19:33.693 [INF] HSWC: Trimming open circuits for chan_id=1293038:78:0, start_htlc_id=0
2018-04-17 22:19:33.693 [INF] HSWC: Trimming open circuits for chan_id=1293043:62:1, start_htlc_id=0
2018-04-17 22:19:33.693 [INF] HSWC: Trimming open circuits for chan_id=1293054:445:0, start_htlc_id=0
panic: page 1072 already freed

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*freelist).free(0x122500a0, 0x85fb, 0x0, 0x7518b000)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/freelist.go:143 +0x4ac
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0x11e99040, 0x1224b710, 0xacfe28)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:363 +0x1e0
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0x11e99000, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:350 +0x90
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0x11e98fc0, 0x120e32e4, 0x5)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:350 +0x90
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0x1200aac0, 0x1200aa00, 0x120e3538)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:568 +0x37c
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0x11ebc50c, 0xbeadc529, 0x5b68e6d)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:535 +0x2d4
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0x11ebc500, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/tx.go:160 +0xb8
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).Update(0x11f78000, 0x120e3630, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:675 +0xd0
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).SetSourceNode(0x11e0c638, 0x120903f0, 0x46, 0x46)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:314 +0x5c
main.newServer(0x11f30978, 0x1, 0x1, 0x11f76050, 0x12084000, 0x122fd140, 0x0, 0x8, 0x12084000)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/server.go:320 +0xe10
main.lndMain(0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:303 +0x8b8
main.main()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:623 +0x24

### Your environment
* lnd 0.4.1-beta (lnd-linux-arm-v0.4.1-beta.tar.gz)
* Linux 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux (Rapbian Stretch Lite)
* Bitcoin Core Daemon version v0.16.0 (bitcoin-0.16.0-arm-linux-gnueabihf.tar.gz)
* I recently copied my existing .lnd folder to a new hardrive.

### Steps to reproduce
lnd is crashing during startup. It happens every time I try to start it.

### Expected behaviour
lnd should startup without error

### Actual behaviour
lnd crashes with a stack trace.

**Comment by plasm0r** [comment]
No, it was shutdown, along with bitcoind. I copied both the .bitcoin and .lnd folders over to the new drive. bitcoind started without problems. Lnd did a lot of initial syncing/catching up and then it crashed. Upon restart I keep getting  the same results. 

I

**Comment by Roasbeef** [comment]
If you re-compile `lnd` with the `-race` flag, does it report anything? 
```
go build -v -race
```

**Comment by plasm0r** [comment]
I tried that, but it's not supported on my platform:

go build: -race and -msan are only supported on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64

Anything else I can try for you? Should I try and build from latest source? I'm using the 0.4.1 binary release at the moment.

**Comment by plasm0r** [comment]
Somthing that i forgot to mention is that I was using an external USB drive that was powered by the raspberry PI. This wasn't working too well and I would occasionally get voltage drops. So I switched to a USB drive that was separately powered. I wonder if database corruption could have occurred during those voltage drops.

I was searching and came across this which made me think that https://github.com/boltdb/bolt/issues/348
It's an older issue but it made me think that those voltage drops I was getting could have corrupted the database.

**Comment by plasm0r** [comment]
Ok, i have a copy of the database that caused the problem. I will try and recompile on my x64 Linux VM with that race flag set as it's not available when compiling a Go app on an Arm platform like the Raspberry PI.

**Comment by halseth** [comment]
Similar: https://github.com/lightninglabs/neutrino/issues/48

**Comment by plasm0r** [comment]
Hi

I recompiled on my x64 Linux VM and ran LND with the bad database copied from my Raspberry PI and I'm getting the same error (see below) with no additional information that I can see. Is there something I could have missed? I did notice that with that race flag set, LND took much longer to start and used a lot more of the CPU. Anything else you want me to try?

2018-04-27 18:50:02.266 [INF] LTND: Version 0.4.1-beta commit=
2018-04-27 18:50:02.281 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-04-27 18:50:02.963 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2018-04-27 18:50:03.503 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-04-27 18:50:03.507 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-04-27 18:50:03.507 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
2018-04-27 18:50:50.521 [INF] LNWL: Opened wallet
2018-04-27 18:50:50.695 [INF] LTND: Primary chain is set to: bitcoin
2018-04-27 18:50:50.968 [INF] LTND: Initializing btcd backed fee estimator
2018-04-27 18:51:14.645 [INF] LNWL: Opened wallet
2018-04-27 18:51:40.597 [INF] LNWL: The wallet has been unlocked without a time limit
2018-04-27 18:51:40.598 [INF] LTND: LightningWallet opened
2018-04-27 18:51:41.357 [INF] LNWL: Started rescan from block 00000000eb8c3cd4de7697ad36294b4afa72e3e514935f326d67c94fa6d2d95f (height 1293900) for 36 addresses
2018-04-27 18:51:42.192 [INF] HSWC: Restoring in-memory circuit state from disk
2018-04-27 18:51:42.234 [INF] HSWC: Payment circuits loaded: num_pending=6, num_open=6
2018-04-27 18:51:42.511 [INF] HSWC: Trimming open circuits for chan_id=1293038:78:0, start_htlc_id=0
2018-04-27 18:51:42.512 [INF] HSWC: Trimming open circuits for chan_id=1293043:62:1, start_htlc_id=0
2018-04-27 18:51:42.512 [INF] HSWC: Trimming open circuits for chan_id=1293054:445:0, start_htlc_id=0
panic: page 1072 already freed

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*freelist).free(0xc42021fa70, 0x8605, 0x7fae22430000)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/freelist.go:143 +0x796
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0xc4205ac540, 0xc420592a60, 0x15b8fe0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:363 +0x962
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0xc4205ac4d0, 0x0, 0x0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:350 +0x190
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0xc4205ac460, 0xc4206ec4c0, 0x5)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:350 +0x190
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc4201960c0, 0xc4202b0300, 0xc4206ec940)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:568 +0x699
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc42025c0f8, 0x1875e8a14c, 0x1b25e00)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:535 +0x52a
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc42025c0e0, 0x0, 0x0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/tx.go:160 +0x191
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).Update(0xc42027c780, 0xc4206ecba0, 0x0, 0x0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:675 +0x125
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).SetSourceNode(0xc4202b4008, 0xc420330000, 0x46, 0x46)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:314 +0xe5
main.newServer(0xc420280300, 0x1, 0x1, 0xc420236740, 0xc42017a1b0, 0xc42021f1a0, 0x8, 0x8, 0x0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/server.go:320 +0x1f0e
main.lndMain(0x0, 0x0)
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/lnd.go:320 +0x11c5
main.main()
        /home/admin/gocode/src/github.com/lightningnetwork/lnd/lnd.go:636 +0x34

**Comment by Roasbeef** [comment]
This is running _with_ the race condition detector?

**Comment by Roasbeef** [comment]
Ah yes, it's expected that the race condition detector slows things down (150x or so).

**Comment by polkhovsky** [comment]
I started getting this error today after I had to shut down my iMac by holding the power button and restart it again.

**Comment by polkhovsky** [comment]
Any possible workaround for this? I'd like to close all channels and move the coins out to another wallet before they are lost. Thanks.

**Comment by Roasbeef** [comment]
What storage medium were you using for your node @polkhovsky?

**Comment by polkhovsky** [comment]
a regular 2Tb hard drive

**Comment by Roasbeef** [comment]
A spinning disk?

**Comment by Roasbeef** [comment]
If you follow the steps above to attempt to start w/ the race condition detector on, what are your results?

**Comment by polkhovsky** [comment]
Actually I'm lying. The lnd stuff is on my primary SSD drive. Bitcoin's data is on the spinning 2Tb drive.

**Comment by polkhovsky** [comment]
I'm not clear on the instructions. What do I do after I run `go build -v -race` ? Simply run or is there an install step?

**Comment by polkhovsky** [comment]
```
2018-05-23 18:24:34.361 [INF] CRTR: Prune tip for Channel Graph: height=522708, hash=00000000000000000001e027b822f6fb109cb770f862f312df3e4529324004f4
2018-05-23 18:24:34.386 [INF] CRTR: Syncing channel graph from height=522708 (hash=00000000000000000001e027b822f6fb109cb770f862f312df3e4529324004f4) to height=524065 (hash=0000000000000000001581362fd2a38ff9c4be3f15c0b484351d94d41ed36cdb)
panic: page 4140 already freed

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*freelist).free(0xc42022a3f0, 0xb960c4, 0x582c000)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/freelist.go:143 +0x449
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0xc4201c23f0, 0xc4202b3180, 0x1cba220)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:363 +0x1fa
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*node).spill(0xc4201c22a0, 0xc42094d0e8, 0xa)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/node.go:350 +0xbf
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc420237e80, 0xc42022bb00, 0xc42094d4c8)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:568 +0x4b8
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc42035e398, 0x371901ddb, 0x2197520)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:535 +0x3f9
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc42035e380, 0x0, 0x0)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/tx.go:160 +0x11c
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).Update(0xc42029a1e0, 0xc42094d6c0, 0x0, 0x0)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:675 +0xe8
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).PruneGraph(0xc4202ee198, 0xc4200cebf8, 0x1, 0x1, 0xc420b36080, 0xc40007f9d5, 0x0, 0x1, 0xc42094d848, 0x16aa728, ...)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/channeldb/graph.go:581 +0xc0
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).syncGraphWithChain(0xc420238340, 0xc42081a000, 0x19ec)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/routing/router.go:526 +0x850
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start(0xc420238340, 0x0, 0x0)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/routing/router.go:381 +0x3db
main.(*server).Start(0xc420364c80, 0x1ae0800, 0x2e)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/server.go:589 +0x16d
main.lndMain(0x0, 0x0)
	/Users/alex/go/src/github.com/lightningnetwork/lnd/lnd.go:597 +0x1adb
main.main()
	/Users/alex/go/src/github.com/lightningnetwork/lnd/lnd.go:642 +0x26

```

**Comment by polkhovsky** [comment]
Any other ideas?

**Comment by polkhovsky** [comment]
As an experiment, I moved the channel.db out of the folder and restarted lnd. It happily ran, but my channel balance showed 0. Have I lost those coins now anyway since my node has been down all this time?

**Comment by Roasbeef** [comment]
If you have your seed, then you can recover the funds @polkhovsky.

**Comment by badokun** [comment]
Had the same thing happened to me. Power cut and then this irrecoverable state. Also moved the channel.db to get going again. What would a good back up strategy be? backup the channel.db on a cron job after checking lnd's state, e.g. a rcp call to getinfo. if it's good, make the backup. This way you'll have the best chance of recovery. 

@Roasbeef am I missing something?

**Comment by Roasbeef** [comment]
#2313 implements that in a scheme that's impossible to mess up for the end user. It should be ready for final review by next week.

**Comment by badokun** [comment]
> If you have your seed, then you can recover the funds @polkhovsky.

If you modify the channel.db file doesnt that signal to your peers you may be attempting to steal funds and you'll be penalized. I've just done this now, so will see how it plays out

**Comment by badokun** [comment]
> #2313 implements that in a scheme that's impossible to mess up for the end user. It should be ready for final review by next week.

Thanks! That was a lightning quick response!

**Comment by badokun** [comment]
> Have I lost those coins now anyway since my node has been down all this tim

Did you ever get your coins returned? I was under the impression if a channel goes stale, it'll be closed by the other party at some point. On 1ml.com it still shows my channels as ACTIVE even though my end of the connection is dead
