### ISSUE TITLE
Can't close channel ("Unable to find channel")

### ISSUE THREAD

**Issue by BitBargain** [lightningnetwork/lnd#1112]
### Background

I am unable to close a channel. I get:
> [lncli] rpc error: code = Unknown desc = unable to find channel

### Your environment

lncli version 0.4.1 commit=b0709b45f7af9314481d06e617b1cee088fd708e
Linux Debian 9, 4.9.20 kernel
Bitcoin Core 0.16

### Steps to reproduce

> lncli closechannel --force c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13 0

### Expected behaviour

I would expect the channel to be forcefully closed or if the channel is already in a closing state then I would not expect the channel to be listed by `listchannels` but rather to show up only in response to `pendingchannels`.

### Actual behaviour

> [lncli] rpc error: code = Unknown desc = unable to find channel

### Additional remark

The channel was opened by Eclair on my phone. I tried to close it from the app side gracefully, but it didn't work - it just stayed there. Now it looks like it may have closed on-chain unilaterally. But LND still lists the channel instead of showing it as pending force-close or removing it completely.

### The channel

>        {
>             "active": false,
>             "remote_pubkey": "03796020b0eb28e2adb57ff7a56d9bdb9d421939c57522cdc7f4ebe78a4daadd4f",
>             "channel_point": "c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0",
>             "chan_id": "568505785711525888",
>             "capacity": "1157000",
>             "local_balance": "304",
>             "remote_balance": "1156359",
>             "commit_fee": "641",
>             "commit_weight": "552",
>             "fee_per_kw": "256",
>             "unsettled_balance": "0",
>             "total_satoshis_sent": "0",
>             "total_satoshis_received": "304",
>             "num_updates": "63",
>             "pending_htlcs": [
>                 {
>                     "incoming": true,
>                     "amount": "151",
>                     "hash_lock": "dgr6wkX2H2EbFPxZaTKsYBQSO/d9Pgh6p+RL4+CQApA=",
>                     "expiration_height": 518892
>                 }
>             ],
>             "csv_delay": 144,
>             "private": true
>         },

### Logs

> 2018-04-19 15:32:34.195 [INF] PEER: NodeKey(03796020b0eb28e2adb57ff7a56d9bdb9d421939c57522cdc7f4ebe78a4daadd4f) loading ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0)
> 2018-04-19 15:32:34.197 [INF] HSWC: ChannelLink(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) is starting
> 2018-04-19 15:32:34.197 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0)
> 2018-04-19 15:32:34.197 [INF] HSWC: HTLC manager for ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) started, bandwidth=0 mSAT
> 2018-04-19 15:32:34.198 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0)
> 2018-04-19 15:32:34.241 [INF] HSWC: Received re-establishment message from remote side for channel(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0)
> 2018-04-19 15:32:34.326 [INF] PEER: Ideal fee for closure of ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) is: 181 sat
> 2018-04-19 15:32:34.326 [INF] HSWC: ChannelLink(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) is stopping
> 2018-04-19 15:32:34.645 [INF] HSWC: ChannelLink(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) has exited
> 2018-04-19 15:32:34.645 [INF] PEER: ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): sending shutdown message
> 2018-04-19 15:32:34.645 [INF] PEER: ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): Responding to shutdown
> 2018-04-19 15:32:39.085 [INF] NTFN: Dispatching spend notification for outpoint=c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0
> 2018-04-19 15:32:39.085 [WRN] CNCT: Unprompted commitment broadcast for ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0)
> 2018-04-19 15:32:39.085 [INF] CNCT: Unilateral close of ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) detected
> 2018-04-19 15:32:39.100 [INF] CNCT: ChannelArbitrator(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): remote party has closed channel out on-chain
> 2018-04-19 15:32:39.100 [INF] CNCT: ChannelArbitrator(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): contract resolutions empty, exiting
> 2018-04-19 15:32:39.100 [INF] CNCT: Marking ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) fully resolved

**Comment by BitBargain** [comment]
Update: after restarting Eclair, the channel seems to have gone. But before I did that, it could not be closed gracefully nor forcefully by my LND node.

**Comment by Roasbeef** [comment]
Looks like you tried to do a fee negotiation, then eclair ended up force closing the channel.

**Comment by Roasbeef** [comment]
Based on the logs, the state was resolved on disk: 
```
2018-04-19 15:32:39.100 [INF] CNCT: ChannelArbitrator(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): remote party has closed channel out on-chain
2018-04-19 15:32:39.100 [INF] CNCT: ChannelArbitrator(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0): contract resolutions empty, exiting
2018-04-19 15:32:39.100 [INF] CNCT: Marking ChannelPoint(c0a1c42af0c94586b03d47934bf7a57daac4ca22e42458924fbb4493bbaeab13:0) fully resolved
```

**Comment by Roasbeef** [comment]
It looks like the eclair client _started_ to close, but then disconnected from lnd. Then while it was disconnected, it force closed.

**Comment by BitBargain** [comment]
That's a possibility, what bothers me is that there was a stage in all of this when on the LND side I was helpless to do anything about the channel. It listed it under `listchannels` but didn't allow me to close it.

I had to launch the app on the phone for this to be resolved. Before that, the channel was just sitting there but could not be closed.

Was this because of the pending HTLC? Or some other issue? I don't know. It could all be normal, it just may need to be sent to `pendingchannels` while it's being closed.

**Comment by Roasbeef** [comment]
> Was this because of the pending HTLC? 

If you had a pending HTLC, we don't allow cooperative channel closing, as otherwise the funds in the HTLC would basically be lost.

**Comment by BitBargain** [comment]
But that htlc must have been pending for a while now and it was up to Eclair which hasn't connected for a while at the time I tried to close the channel on LND's side. It's not good to not have control over the channel, no matter what.

Either way, the error message is misleading at the very least ("Unable to find channel")
