### ISSUE TITLE
lnd prematurely stops trying alternative payment routes and fails payment

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1114]
### Background

when trying to settle an invoice, lnd tries two paths and prunes the final destination node, resulting in no more alternative paths being tried althought there are plenty alternative routes that would have worked.

"destination": "02634b5d6b7db0cf26025bb59ddf1eafed2f1857de3550c129cfd7dbfb403c4e0f",

```
  00000480  24 8f a5 dc 03 20 04 a0  a2 67 c0 6b 57 e1 19 4e  |$.... ...g.kW..N|
  00000490  07 b4 a9 0d e2 99 cc 0b  91 65 6b 75 d7 aa c9 17  |.........eku....|
  000004a0  e6 8d 6c 2d a8 60 8e 3c  bf da 10 1c da 51 1e f2  |..l-.`.<.....Q..|
  000004b0  c0 c7 60 6c 5c 58 5a 18  b5 71 18 97 24 91 7b f3  |..`l\XZ..q..$.{.|
  000004c0  10 6c 66 15 39 86 01 1a  d0 62 5f b1 6d 96 ba 3a  |.lf.9....b_.m..:|
  000004d0  84 6e c6 0c 2c 1d ab 77  9d 1f ce 4f a5 b0 db c0  |.n..,..w...O....|
  000004e0  98 fd 33 40 fe e9 6e ff  a3 f0 7f f6 bf 10 7a bf  |..3@..n.......z.|
  000004f0  53 ba 9a 63 b6 26 c3 15  34 0d 2a 4f 8d 5a 5c f9  |S..c.&..4.*O.Z\.|
  00000500  60 0a 3d 8c 0c de e8 35  8d 48 0f 19 e0 cb 86 49  |`.=....5.H.....I|
  00000510  cb 43 63 45                                       |.CcE|
 },
 HeaderMAC: ([32]uint8) (len=32 cap=32) {
  00000000  8c bf fc 2f 8a 24 77 c6  8f ee b3 96 f1 33 34 61  |.../.$w......34a|
  00000010  00 78 97 17 28 62 57 f8  f1 ba 75 b7 ac 07 ef 95  |.x..(bW...u.....|
 }
})

2018-04-20 10:25:43.034 [ERR] HSWC: insufficient capacity in available outgoing links: need 119000 mSAT, max available is 0 mSAT
2018-04-20 10:25:43.034 [ERR] CRTR: Attempt to send payment e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b failed: TemporaryChannelFailure: insufficient capacity in available outgoing links: need 119000 mSAT, max available is 0 mSAT
2018-04-20 10:25:43.034 [TRC] CRTR: node=031b6ba6271514bd30202ba007a1d2ef2e2106aaa5774183c570137251687407dc reported failure when sending htlc=e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b
2018-04-20 10:25:43.034 [DBG] CRTR: Reporting edge 565273221551947777 failure to Mission Control
2018-04-20 10:25:43.034 [DBG] CRTR: Mission Control session using prune view of 1 edges, 0 vertexes
```

```
  00000470  77 23 1c b2 cc 45 24 2e  fb 46 a6 3f 5b 01 50 4f  |w#...E$..F.?[.PO|
  00000480  5b 4c ce b2 e3 4a 5c b0  fc fc 6e 9b 38 43 6c b0  |[L...J\...n.8Cl.|
  00000490  15 c9 d9 37 5c a4 a4 31  75 c4 04 e5 b0 99 d3 25  |...7\..1u......%|
  000004a0  4c a3 7f 90 22 ab dd dd  91 da ee 6c c4 a3 83 3e  |L..."......l...>|
  000004b0  e5 5b 7d e7 83 a6 30 46  b7 8f 73 ad 3c 26 23 54  |.[}...0F..s.<&#T|
  000004c0  5d c5 1a ff 4e 92 0c 7d  19 d0 c8 29 b2 97 b3 75  |]...N..}...)...u|
  000004d0  80 89 55 5b ec 3b fe fc  5c cc 41 dc 4d 98 e7 25  |..U[.;..\.A.M..%|
  000004e0  95 99 c7 b9 4e 84 a1 3b  c9 48 5b 12 64 b0 ad 43  |....N..;.H[.d..C|
  000004f0  22 6f 7d 30 9f 34 c2 ea  6a 70 5a eb 1f aa 6b 4e  |"o}0.4..jpZ...kN|
  00000500  f3 1f 86 e3 d4 9e b9 5b  56 e2 d4 65 79 b2 32 af  |.......[V..ey.2.|
  00000510  82 f2 2f 7f                                       |../.|
 },
 HeaderMAC: ([32]uint8) (len=32 cap=32) {
  00000000  16 e7 11 cb 0c 01 96 de  14 53 fa 09 f0 b7 97 c0  |.........S......|
  00000010  47 d2 74 10 a0 a4 c4 a9  92 0f 7c 91 93 9e c1 11  |G.t.......|.....|
 }
})

2018-04-20 10:25:44.026 [ERR] CRTR: Attempt to send payment e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b failed: UnknownNextPeer
2018-04-20 10:25:44.026 [TRC] CRTR: node=022bd091df93de9ccb69891bfe5a4cdf91541ba045aa73eb05f4f66478184bbe89 reported failure when sending htlc=e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b
2018-04-20 10:25:44.026 [DBG] CRTR: Reporting vertex 02634b5d6b7db0cf26025bb59ddf1eafed2f1857de3550c129cfd7dbfb403c4e0f failure to Mission Control
2018-04-20 10:25:44.026 [DBG] CRTR: Mission Control session using prune view of 1 edges, 1 vertexes
```

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
They key is this log fragment: 
```
2018-04-20 10:25:44.026 [ERR] CRTR: Attempt to send payment e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b failed: UnknownNextPeer
2018-04-20 10:25:44.026 [TRC] CRTR: node=022bd091df93de9ccb69891bfe5a4cdf91541ba045aa73eb05f4f66478184bbe89 reported failure when sending htlc=e1ef2b2255e223f5bddf3140fac18ab3c020342dbac1ad87a6a15e566315197b
```

If the peer _right_ before the destination reports an unknown next peer, then we'll prune the destination vertex. This allows us to fail quickly in the case that the destination isn't online at all. 

However, what seems be happening here (from reading scrollback on chat), is that there was a node connected to the destination, which maybe was flapping. As a result, it didn't have connectivity to the destination node. In this case, we'll prune the dest vertex, but likely instead we should prune the channel that we attempted to route over. This will allow us to continue attempts, but just prune away routes _through_ that node.

**Comment by robtex** [comment]
yes, otherwise it is too easy to just have a node report another node is down, and severely affect the recipients nodes connectivity via any route.
personally i don't think you should prune away all routes thru the previous node either, because it might have a working connectivity via another node, even if the direct connection is faulty for some reason.
if we do insist on punishing nodes and/or channels, it's better to put them lower in the list, rather than completely remove them. they do deserve a second chance, because they have good chances of being part of a working route.

**Comment by Roasbeef** [comment]
> personally i don't think you should prune away all routes thru the previous node either, because it might have a working connectivity via another node, even if the direct connection is faulty for some reason.

Yeah was I'm suggesting is to instead just prune that _channel_ we attempted. Eventually, all the channels leading from that previous node to the destination would themselves be exhausted. 

> if we do insist on punishing nodes and/or channels, it's better to put them lower in the list, rather than completely remove them. they do deserve a second chance, because they have good chances of being part of a working route.

Yep, atm right now our pruning is very naive, and short lived. The next version of mission control will move to a decaying score based system that's persistent. Making things persistent will also improve UX, as right now, the first payment may take a few seconds, but then the subsequent ones will go through a bit faster as the cache is warmed up.
