### ISSUE TITLE
LND Unable to start server, bad-txns-vout-empty

### ISSUE THREAD

**Issue by hikedev** [lightningnetwork/lnd#1118]
### Background

I did close all of my lnd (autopilot) channels, 1 channel is still not able to be closed down. lnd will not start anymore. Its is similar to this issue https://github.com/lightningnetwork/lnd/issues/1010 . I was able to start lnd once again by blocking the ip, but this doesnt work anymore. Im on the latest commit. Is there a way to flush or clear the broadcasting history?

### Your environment
lncli version 0.4.1 commit=8af80bfc5cdebcd323ed2a50ea0497df6e9bc6e4 , bitcoind

### Actual behaviour
2018-04-23 10:53:04.964 [INF] CNCT: Creating ChannelArbitrators for 1 active channels
2018-04-23 10:53:04.964 [INF] NTFN: New block epoch subscription
2018-04-23 10:53:04.965 [INF] CNCT: Creating ChannelArbitrators for 6 closing channels
2018-04-23 10:53:04.965 [INF] NTFN: New spend subscription: utxo=4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0
2018-04-23 10:53:05.058 [INF] NTFN: New spend subscription: utxo=3bad5aa89342175f0c94f2bdf0f3c0b7d18bb1ffab59c68b7fd9d0282f8b06af:0
2018-04-23 10:53:05.059 [INF] CNCT: ChannelArbitrator(4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0): starting state=StateBroadcastCommit
2018-04-23 10:53:05.059 [INF] CNCT: Close observer for ChannelPoint(4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0) active
2018-04-23 10:53:05.060 [INF] CNCT: ChannelArbitrator(4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0): force closing chan
2018-04-23 10:53:05.064 [INF] HSWC: Removing channel link with ChannelID(c44b3e41d6c36b08249f8892c3076f77b6095d7acd51103214a2ce25c668fb4b)
2018-04-23 10:53:05.064 [ERR] CNCT: unable to mark link inactive: channel link not found
2018-04-23 10:53:05.065 [INF] CNCT: Broadcasting force close transaction, ChannelPoint(4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0): (*wire.MsgTx)(0xc420669600)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc4206c1f80)({
   PreviousOutPoint: (wire.OutPoint) 4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) <nil>,
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 bf cd bb  e9 1d 57 eb 9b 35 18 43  |0E.!......W..5.C|
     00000010  92 57 bd 95 13 90 32 51  d9 ac b7 0e 41 6e e6 23  |.W....2Q....An.#|
     00000020  88 d3 2c 47 c6 02 20 4b  af 07 87 85 39 73 be 22  |..,G.. K....9s."|
     00000030  20 b3 e0 eb 74 53 28 4c  09 b8 8b fb 86 a9 33 9a  | ...tS(L......3.|
     00000040  c4 e1 5a 24 e9 02 52 01                           |..Z$..R.|
    },
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 ff c4 29  33 be 67 ba 5b df 9b 52  |0E.!...)3.g.[..R|
     00000010  76 58 a5 61 bd 30 91 83  e1 38 3f 70 78 a8 a7 87  |vX.a.0...8?px...|
     00000020  14 3d 27 8d d0 02 20 45  35 5a 9a 5a 48 2b 71 0d  |.='... E5Z.ZH+q.|
     00000030  ae 22 f5 ff 1d 53 df 6a  ab cc 45 13 08 84 0f ef  |."...S.j..E.....|
     00000040  61 e1 f5 2a a5 8d f9 01                           |a..*....|
    },
    ([]uint8) (len=71 cap=500) {
     00000000  52 21 02 44 a2 55 67 3e  3d 0c 5f 94 6a f2 5b 98  |R!.D.Ug>=._.j.[.|
     00000010  a3 eb 48 e8 ea 2b 11 78  0f c6 d4 fc 2c 50 c1 5e  |..H..+.x....,P.^|
     00000020  08 ba 7f 21 03 28 b4 b3  c7 8a 69 1c 52 2e 17 6f  |...!.(....i.R..o|
     00000030  80 60 a7 73 9f e1 bb 23  37 fb c6 34 72 3e 86 78  |.`.s...#7..4r>.x|
     00000040  3c b9 77 e9 5f 52 ae                              |<.w._R.|
    }
   },
   Sequence: (uint32) 2148557958
  })
 },
 TxOut: ([]*wire.TxOut) {
 },
 LockTime: (uint32) 547847813
})

 2018-04-23

 10:53:05.066 [ERR] CNCT: ChannelArbitrator(4bfb68c625cea214321051cd7a5d09b6776f07c392889f24086bc3d6413e4bc4:0): unable to broadcast close tx: -26: 16: bad-txns-vout-empty
2018-04-23 10:53:05.067 [ERR] CNCT: unable to advance state: -26: 16: bad-txns-vout-empty
2018-04-23 10:53:05.067 [ERR] SRVR: unable to start server: -26: 16: bad-txns-vout-empty

**Comment by Roasbeef** [comment]
You basically had a "dust" channel before we patched `lnd` to remove them all together. To start up again, you'll need to apply [this patch](https://github.com/lightningnetwork/lnd/issues/975#issuecomment-377613760). The channel was "useless" as all the funds in the channel went to fees (which will no longer happen in newly created channels). 

We'll be adding an RPC soon to let you "forget" faulty channels like this.

**Comment by vegardengen** [comment]
yay! Looking forward to that RPC. But please be a bit careful with docs! This sounds like a splendid way to "lose" funds...?

Will you forget it or shelve it? Would be nice if all the info was there so that you could unforget it in case you actually did a mistake, forgetting the wrong channel?

**Comment by Roasbeef** [comment]
FWIW, the funds here were likely not yours and also a small amount (less
than typical fees). New versions of lnd will no longer encounter this
issue.

On Apr 24, 2018 12:25 AM, "vegardengen" <notifications@github.com> wrote:

yay! Looking forward to that RPC. But please be a bit careful with docs!
This sounds like a splendid way to "lose" funds...?

Will you forget it or shelve it? Would be nice if all the info was there so
that you could unforget it in case you actually did a mistake, forgetting
the wrong channel?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1118#issuecomment-383830727>,
or mute the thread

**Comment by Roasbeef** [comment]
The RPC would probably only be enabled with a debug build.

**Comment by hikedev** [comment]
> You basically had a "dust" channel before we patched lnd to remove them all together. To start up again, you'll need to apply this patch. The channel was "useless" as all the funds in the channel went to fees (which will no longer happen in newly created channels).

Thanks Roasbeef, I will try that.

> We'll be adding an RPC soon to let you "forget" faulty channels like this.

+1
