### ISSUE TITLE
pendingchannels

### ISSUE THREAD

**Issue by tretaki** [lightningnetwork/lnd#1123]
### Background

When calling:
lncli pendingchannels -o
lncli pendingchannels -c
lncli pendingchannels -a
lncli pendingchannels

They all give the same output, namely they list all channels, opening and closing channels. If I understood the docs correctly they -o should list only opening channels, -c only closing channels?

### Your environment

* version of `lnd` version 0.4.1
* which operating system: raspbian Linux raspberrypi 4.9.59-v7+
* version `bitcoind` Bitcoin Core RPC client version v0.16.0

**Comment by Roasbeef** [comment]
The arguments on the `lncli` command actually don't correspond to arguments in the RPC atm. The options were added very early on, but never threaded through to the RPC system.

**Comment by tretaki** [comment]
Ok. That makes sense, thank you for clearing that up and big thanks for all the work you are putting in!
