### ISSUE TITLE
Potential malformed error packet returned

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#1126]
### Background

Opened a channel from eclair to yall, and got an error back

### Your environment

Using eclair to open a channel to lnd

### Steps to reproduce

Open a channel from eclair to y'all on testnet. Try to purchase an article

### Expected behaviour

The purchase suceeds

### Actual behaviour

Sometimes it works, sometimes not: intermittently, the lnd channel returns an unparsable error packet. More details on https://github.com/ACINQ/eclair/issues/572#issuecomment-383727381

**Comment by pm47** [comment]
We get failure message `000410070000`, which I believe is an invalid `temporary_channel_failure` (missing the required `channel_update`).

**Comment by pm47** [comment]
Note: errors are transient are are not easily reproductible

**Comment by sstone** [comment]
It seems that lnd considers that the `channel_update` field in `temporary_channel_failure` is optional, and we think it is mandatory. I'll open an issue on the specs repo for clarification.

**Comment by Roasbeef** [comment]
Why would a `channel_update` be required for a temp chan failure? The nature of the error is that it's opaque and doesn't deliver any new information.

**Comment by Roasbeef** [comment]
Your PR to the spec makes an assertion that isn't found anywhere else in the spec. In other words, it's a fundamental change: 
> we think it is mandatory

**Comment by sstone** [comment]
The way BOLT4 is written hints that a `channel_update` is always included when the update flag is set.  Since we made different implementation choices it clearly needs to be specified, and making it a mandatory field is what makes the most sense to me (even though it may not always help).

**Comment by gustavonalle** [comment]
FYI, c-lightning is also [sending it](https://github.com/ElementsProject/lightning/blob/master/channeld/channel.c#L2196)

OTOH, in other circumstances (BOLT 7), a ```channel_update``` has been associated with temp failures:

```...MAY create and send a channel_update with the disable bit set to 1, to signal a channel's temporary unavailability ```.

IMHO, what could make sense is to honor the ```len``` field: if zero this means no channel_update follows.
