### ISSUE TITLE
channeldb: prune LinkNodes w/o any active channels

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1128]
Currently, within the codebase, `lnd` [will attempt to reliably reconnect to _all_ peers that we have active channels with](https://github.com/lightningnetwork/lnd/blob/master/server.go#L861). We do this in order to ensure maximal availability of all our our channels. However, a flaw exists in the current logic: we will continue to automatically re-connect to peers we _no longer have channels_ with. This flaw can cause an excessive number of idle goroutines to be created, especially with nodes that have had hundreds of channels in the past. 

To remedy this, we should garbage collect any [`LinkNodes`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/nodes.go#L22) that we no longer have active channels with. 

# Steps To Completion

- [ ] The [`MarkChanFullyClosed`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/db.go#L524) method should also check the [`openChannelBucket`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L26) to see if the target node still has lingering entries in the sub-bucket after channel closure. If not, then the link node should be deleted. 

- [ ] In the case that a `LinkNode` _is_ eligible for garbage collection, it should be removed from the [`persistentPeers`](https://github.com/lightningnetwork/lnd/blob/master/server.go#L85) map. 

- [ ] The [`persistentRetryCancels`](https://github.com/lightningnetwork/lnd/blob/master/server.go#L88) entry for the target node should be closed, and the entry deleted. 

Will fix #1100

**Comment by merehap** [comment]
I'll take a look at this, starting today or tomorrow.

**Comment by Roasbeef** [comment]
Closed by #1371.
