### ISSUE TITLE
lnd doesn't work from 32-bit <-> 64-bit systems

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#113]
## Describe the Bug
As reported by `shinobimonkey` on IRC, it seems that `lnd` is unable to establish an encrypted p2p connection between 32-bit and 64-bit systems. 

## Steps to Reproduce 
Spin up an `lnd` node on a 32-bit system, and one on a 64-bit system and attempt to establish a connection using `lncli connect`. The two nodes will be unable to connect to each other. 

## Investigation so Far
I attempted some cursory debugging and discovered that the `brontide` handshake is failing with an authentication error. This indicates that a MAC check somewhere in the handshake is failing when they attempt to connect out to my node that's currently serving as our testnet faucet. 

## Next Steps
My current suspicion is that the issue lies in the [library we're currently using for the chachapoly AEAD](https://github.com/aead/chacha20). The library uses some SIMD assembly instructions that either function differently across 32/64-bit systems, or aren't supported on 32-bite systems leading to the code to fallback to operations that don't commute across 32/64-bit systems. 

I'm going to create a branch that traces the execution of the `brontide` handshake within the logs. With this we should be able to pin-point the exact point of divergence.

**Comment by Roasbeef** [comment]
As an update, we have a few users connecting out to the faucet from Raspberry Pi's, so the root cause of this issue is still unknown.

**Comment by AndrewSamokhvalov** [comment]
I believe [this](https://github.com/lightningnetwork/lnd/issues/146) might be related.

**Comment by Roasbeef** [comment]
Closing for now due to commit 9234956. If the issue re-appears I'll re-open this.
