### ISSUE TITLE
routing+chancloser+contractcourt: send out a `ChannelUpdate` w/ disable active on close events

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1132]
The [`ChannelUpdate` message has a set of flags](https://github.com/lightningnetwork/lnd/blob/master/lnwire/channel_update.go#L50), which are interpreted as a bitfield. Once of the possible bits is a [disabled bit](https://github.com/lightningnetwork/lnd/blob/master/lnwire/channel_update.go#L21). This bit signals that the channel isn't eligible to be used for any HTLC routing attempts. Nodes can send out an update with this bit set as a courtesy to other node if they're going offline, or the like. 

Atm, when we close a channel, or have broadcast a commitment/close-tx, the router isn't notified of this event. As a result, we can unnecessarily incur a routing failure until the closing transaction is ultimately confirmed. Additionally, all other nodes may attempt to route over this channel which will immediately trigger and error and a wasted attempt. 

# Steps To Completion

- [ ] When we accept a cooperative close transaction, we should send a message to the `AuthenticatedGossiper`, to send out an announcement (and apply it to the `ChannelRouter`) that the channel is now disabled. 

- [ ] Within the `contractcourt`, if we decide to force close the current transaction, we should send a similar message to the `AuthenticatedGossiper`.

**Comment by ironclownfish** [comment]
I'll start looking at this. It'll be for learning and practice for now since I'm still brand new. I'll update if I start to think I'm actually going to produce something useful.

**Comment by MiikeWilliams** [comment]
@ironclownfish Hey man, were you able to make any progress on this? Was going to have a look into later this week.
