### ISSUE TITLE
Integration test logs get lost on Termbin

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1133]
### Background
When the `lnd` integration tests run, they produce log files for each node (`output*.log`). On Travis, we attempt to upload these logs to Termbin, such that they can be inspected in case of failing tests. 

### Problem
We recently have been seeing some of the files (usually `output0.log` and `output1.log`) not being part of the files that gets uploaded to Termbin. Here is a recent example: https://travis-ci.org/lightningnetwork/lnd/jobs/370890809 (notice all files from `output2.log`-`output39.log` are uploaded).

This is annoying, as we then have no way of figuring out why the test cases are failing, since these two nodes (Allice and Bob) play a key role in almost all of the tests.

### Steps to completion
- [ ] Figure out why these files are not uploaded (theory is that they are getting too big).
- [ ] Make sure they always get uploaded regardless, either by configuring Termbin to accept them or changing to a different service than Termbin.

**Comment by guggero** [comment]
I'll have a look and try to fix it, together with #1134

**Comment by Roasbeef** [comment]
Fixed by #1139 and #1140.
