### ISSUE TITLE
[Test enhancement] Correlate integration test nodes with log output files

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1134]
### Background
If integration tests are run with the `-logoutput` flag (this happens automatically during `make itest`) then each node that is created during the tests is adding its log output to a file named `outputX.log`, where `X` is the node's node ID.

The number of nodes used during integration tests are starting to become very numerous, and it is hard to know for sure which file corresponds to which node.

### Steps to completion
- [ ] Make the `NewNode` method take a `name string` parameter. (E.g. we would pass "Carol" here: https://github.com/lightningnetwork/lnd/blob/c54a91f44dc4717d2be0c210ab0e4a1a2a1cfb79/lnd_test.go#L537:20)
- [ ] When the log file is created (https://github.com/lightningnetwork/lnd/blob/c54a91f44dc4717d2be0c210ab0e4a1a2a1cfb79/lntest/node.go#L257), print the name of the node, the public key and the filename to `stdout`.

**Comment by tyzbit** [comment]
Taking a crack at this for my first issue.

**Comment by Roasbeef** [comment]
@tyzbit see the linked PRs above.

**Comment by guggero** [comment]
Sorry, @tyzbit, I should have commented here that I was working on that...

**Comment by Roasbeef** [comment]
Fixed by #1139.
