### ISSUE TITLE
Dust Error when trying to open channel with c-lightning

### ISSUE THREAD

**Issue by ecurrencyhodler** [lightningnetwork/lnd#1142]
### Background

Trying to open a channel with 3,000,000 litoshis.  I have lnd, they have c-lightning. 

### Your environment

* version of `lnd`: Version 0.4.1-beta 
* which operating system OSx
* version of `btcd`, `bitcoind`, or other backend: `litecoin core RPC client version v0.15.1.0-07fe91da4`

### Steps to reproduce

lncli openchannel 03dda598d8c08cb02ae51e9dd6e2f236239610f2bd2e99230fa66acf69721983b4 3000000

### Expected behaviour

Channel should open.

### Actual behaviour

Was returned this error:
```
[lncli] rpc error: code = Code(189) desc = You gave bad parameters:Our channel reserve 30000 would be below their dust 54600
```

**Comment by Roasbeef** [comment]
I think `c-lightning` recently disabled support for litecoin, as it wasn't really maintained on their end. The issue you're getting indicates that the channel is too small taking into account the scaled dust limit for litecoin. On our end, what we can do is adjust the reserve accordingly to lie above dust.

**Comment by ecurrencyhodler** [comment]
Would I be able to manually adjust it from the terminal?  If so, what would be the command?

**Comment by Roasbeef** [comment]
Closing this for now as `c-lightning` has recently removed their litecoin support all together. 

Later this week, we'll be raising the amounts for litecoin so it's a bit more usable with `lnd`.

**Comment by flack** [comment]
@Roasbeef 

> c-lightning has recently removed their litecoin support all together.

where did you get this from? To me it looks like they discussed it, but decided to keep it, at least that was the resolution to this PR:

https://github.com/ElementsProject/lightning/pull/1433

**Comment by ecurrencyhodler** [comment]
@flack I think he meant that there won't be any more support for LTC.

**Comment by arowser** [comment]
I think the lnd should set different dust_limit for bitcoin and litecoin, the currrent dust_limit is 573,  so lnd->lightning open channel failed if amount <57201sats, LND show:
```
[lncli] rpc error: code = Code(189) desc = You gave bad parameters:Our channel reserve 30000 would 
be below their dust 54600
```
if fund amount <57201 sat , the lnd->lightningd openchannel will failed, but lightningd->lnd will success.
