### ISSUE TITLE
lnd refusing *lower* fees, claiming there is no capacity

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1145]
### Background

one channel has 13394 commit_fee, 18500 fee_per_kw

```
"capacity": "20000",
"local_balance": "6606",
"remote_balance": "0",
"commit_fee": "13394",
"commit_weight": "600",
"fee_per_kw": "18500",
```

### Steps to reproduce

node tries to lower the fee from current fee_per_kw 18500 to the lower 12750

2018-04-27 22:46:42.435 [INF] HSWC: ChannelPoint(cf8ba45e4e708abd5e113c3dfe57137d800788f07d4f0949058ae4b8d607b0dc:0): updating commit fee to 12750 sat/kw
2018-04-27 22:46:42.435 [ERR] HSWC: unable to update fee rate: cannot apply fee_update=12750 sat/kw, new fee of 9231000 mSAT is greater than balance of 6606000 mSAT

### Expected behaviour

Fee should be lowered
Since the previous higher fee is more than the new lower fee, it should fit
previously the commit_fee was 13394
9231 is significantly lower.
still lnd claims it can not apply the new *lower* fee

### Actual behaviour

lnd claims the *lower* fee does not fit because it doesn't take into account that the current commit_fee is already accounted for.
it only checks what balance is left after previous commit_fee has been subtracted.
so it tries to fit *both* the old higher fee *and* the new lower fee.

**Comment by vegardengen** [comment]
Like this?

https://github.com/vegardengen/lnd/commit/0788e22c0c67e7c353d8c5adf6bf6943fcea2eba

**Comment by vegardengen** [comment]
https://github.com/lightningnetwork/lnd/pull/1151
