### ISSUE TITLE
lncli - unknown service lnrpc.WalletUnlocker

### ISSUE THREAD

**Issue by ripper234** [lightningnetwork/lnd#1153]
### Background

I'm trying to get a basic lnd setup running on Windows using the [tutorial](https://dev.lightning.community/tutorial/01-lncli/).

I have btcd & lnd running, trying to connect to lnd using lncli.

> lncli --rpcserver=localhost:10001 --no-macaroons create

and getting

> [lncli] unable to generate seed: rpc error: code = Unimplemented desc = unknown service lnrpc.WalletUnlocker

The lnd server logs do not show anything 

> ..\lnd --rpclisten=localhost:10001 --listen=localhost:10011 --restlisten=localhost:8001
> 2018-04-29 18:17:55.089 [INF] LTND: Version 0.4.0-alpha
> 2018-04-29 18:17:55.111 [INF] LTND: Active chain: Bitcoin (network=simmnet)
> 2018-04-29 18:17:55.113 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
> 2018-04-29 18:17:55.115 [INF] LTND: Primary chain is set to: bitcoin
> 2018-04-29 18:17:56.339 [INF] LNWL: Opened wallet
> 2018-04-29 18:17:57.668 [INF] LNWL: The wallet has been unlocked without a time limit
> 2018-04-29 18:17:57.668 [INF] LTND: LightningWallet opened
> 2018-04-29 18:17:57.703 [INF] LNWL: Started rescan from block 16850df166dd81b36fb341f127776360d726701ede265f5d62edb2f17669fe66 (height 318) for 0 addresses
> 2018-04-29 18:17:57.705 [INF] LNWL: Catching up block hashes to height 318, this might take a while
> 2018-04-29 18:17:57.718 [INF] LNWL: Done catching up block hashes
> 2018-04-29 18:17:57.718 [INF] LNWL: Finished rescan for 0 addresses (synced to block 16850df166dd81b36fb341f127776360d726701ede265f5d62edb2f17669fe66, height 318)
> 2018-04-29 18:17:57.722 [INF] HSWC: Restoring in-memory circuit state from disk
> 2018-04-29 18:17:57.723 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
> 2018-04-29 18:17:57.736 [INF] RPCS: RPC server listening on 127.0.0.1:10001
> 2018-04-29 18:17:57.737 [INF] RPCS: gRPC proxy started at 127.0.0.1:8001
> 2018-04-29 18:17:57.816 [INF] HSWC: Starting HTLC Switch
> 2018-04-29 18:17:57.816 [INF] NTFN: New block epoch subscription
> 2018-04-29 18:17:57.818 [INF] NTFN: New block epoch subscription
> 2018-04-29 18:17:57.818 [INF] DISC: Authenticated Gossiper is starting
> 2018-04-29 18:17:57.818 [INF] BRAR: Starting contract observer with 0 active channels
> 2018-04-29 18:17:57.819 [INF] NTFN: New block epoch subscription
> 2018-04-29 18:17:57.819 [INF] CRTR: FilteredChainView starting
> 2018-04-29 18:17:57.884 [INF] CRTR: Filtering chain using 0 channels active
> 2018-04-29 18:17:57.885 [INF] CRTR: Prune tip for Channel Graph: height=318, hash=16850df166dd81b36fb341f127776360d726701ede265f5d62edb2f17669fe66
> 2018-04-29 18:17:57.886 [INF] SRVR: Auto peer bootstrapping is disabled
> 2018-04-29 18:17:57.886 [INF] CMGR: Server listening on 127.0.0.1:10011
> 

### Your environment

* I am using compiled binaries for lnd (version 0.4.0-alpha) and btcd (0.12.0-beta)
* Windows 10

**Comment by offerm** [comment]
Try to provide the  `--no-macaroons` when starting LND.

**Comment by Roasbeef** [comment]
Don't provide `--no-macaroons` as offerm suggested. That will start your RPC server without _any sort of authentication at all_. 

Your fault is that you're starting `lnd` without actually using proper wallet encryption `--noencryptwallet`. When you start in this mode, you don't get a wallet seed. It should only be used for experimentation on testnet, and nothing more.

**Comment by ripper234** [comment]
I am testing it in simnet mode, so I though `--noencryptwallet` would be ideal. But I removed it now and successfully got to the initialization phase. Thanks.

**Comment by Roasbeef** [comment]
Oh yah, in that case then you can skip that section of the tutorial :p
