### ISSUE TITLE
chainntnfs: implement a persistent height hint wrapper

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1168]
All methods in the chain notifier interface currently take a `heightHint` parameter. The role of this parameter is to give the stateless implementation of the `ChainNotifier` interface a lower bound on when to start looking for the earliest occurrence of the event. Usually this value isn't used as we remain online for the lifetime of the event (confirmation, spend or w/e). However, we currently have a concept of a "historical dispatch" of an event. This occurs when the stateless chain notifier instance is already live, and we receive a notification for an event with a `heightHint` value that is in the _past_. In this case, depending on various factors (txindex, pruned or w/e) we may have to fetch a set of blocks in the worst case to scan forward to determine if we need to dispatch an event (spend or confirm). 

The current logic can run into efficiency issues due to frequent restarts needing to re-fetch and download blocks in the neutrino case, and also in the future when we add full pruned node support. We can avoid this duplicated work by adding a simple caching layer on top of the `ChainNotifier` itself: 
```go

type HeightHintCache interface {
    CommitSpendHint(op wire.OutPoint, heightHint uint32) error   
    QuerySpendHint(op wire.OutPoint) (uint32, bool)
    PurgeSpendHint(op wire.OutPoint) error 

    CommitConfimHint(txid chainhash.Hash, heightHint uint32) error
    QueryConfirmHint(txid chainhash.Hash) (uint32, bool)
    PurgeConfimHint(txid chainhash.Hash) error
}

type PersistentChainNotifier struct {
    chainntnfs.ChainNotifier
    hintCache chainntnfs.HeightHintCache
}
```

# Steps To Completion 

- [ ] Implement an version of the `HeightHintCache` backed by the current `channeldb`. The interface itself is very simple, we're just adding a thin persistence layer on top of the notifier itself. The methods should be self-explanatory, but feel free to ask questions in the issue body to clear up any ambiguities before beginning.  

- [ ] The `chainntnfs.ChainNotifier` methods will also need to be modified to return the _latest_ known height for which the event hasn't yet been dispatched. This will be used by the `PersistentChainNotifier` struct to update the mapping after each call (see the next item).

- [ ] Implement the `PersistentChainNotifier` struct. Notice that this is more or less, a wrapper interface in a sense. The `PersistentChainNotifier` should implement _all_ methods that the `    chainntnfs.ChainNotifier` does. As a result, we'll be able to pass it in everywhere we currently accept the primary interface. 
     * Each method should itself perform a lookup using the relevant `HeightHintCache` method. This will be used to populate what the `heightHint` value should be to the inner interface implementation.
     * Upon successful method dispatch, the relevant height hint should be updated within the cache. 
     * Upon success _event_ dispatch, the relevant height hint should be deleted from the cache.

**Comment by vapopov** [comment]
I'll take this issue
