### ISSUE TITLE
Document how to build on Windows without using the Makefile

### ISSUE THREAD

**Issue by ripper234** [lightningnetwork/lnd#1171]
I am trying to compile latest lnd on Windows, I failed both using gnu Make for Windows and using WSL.
It is [my understanding](https://stackoverflow.com/questions/11321668/how-to-compile-a-package-of-golang-on-windows-platform)  that Go has an internal build system/standard (`go build`) that shouldn't rely on Make.

Using Makefiles limit lnd development to linux-based systems only and should be dropped in favor of a more cross-platform option.

**Comment by ripper234** [comment]
This works, thanks!

How about adding this to the build instructions?

**Comment by Roasbeef** [comment]
The make file is simply a connivence wrapper for certain commands. The commands are cross-platform. If you use the `go` tool on your platform, you'll be able to compile as normal. Using `go build` is very standard, and we use `dep` for dependency management.

**Comment by dabura667** [comment]
@ripper234 It's already in the Makefile, a Makefile is literally a build instruction.

I literally just copy pasted the commands directly from the Makefile with an English explanation added.

**Comment by ripper234** [comment]
Too bad, the Makefile is 241 lines long, for someone who's not fluent in make or in Go and just wants to build lnd, @dabura667's explanation above is a life saver.

Although on the other hand I understand the need to avoid repeating yourself.
