### ISSUE TITLE
[ERR] CMGR: Can't accept connection: Act One: invalid handshake version: 22, only 0 is valid

### ISSUE THREAD

**Issue by leblitzdick** [lightningnetwork/lnd#1173]
Hi,
im trying to integrate  lightning payment with the  woocommerce lightning plugin for wordpress from joaodealmeida and if i connect lnd i get the following error: 

....[ERR] CMGR: Can't accept connection: Act One: invalid handshake version: 22, only 0 is valid, msg=...

i have no idea, maybe related to my SSL configuration??

lnd  version 0.4.1 commit=09c997983127bb1e575d97c69aa364a82cfb1df7
Linux 3.2.0-5-amd64 #1 SMP Debian 3.2.96-3 x86_64 GNU/Linux
https://github.com/joaodealmeida/woocommerce-gateway-lightning
PLESK wordpress 4.9 with woocommerce

thanks!!

**Comment by Roasbeef** [comment]
Make sure you're using the correct port to connect.

**Comment by leblitzdick** [comment]
With this configuration:

https://localhost:9735

the above Error Massage appears 

with this http://localhost:9735 this error appears:

...[ERR] CMGR: Can't accept connection: Act One: invalid handshake version: 80, only 0 is valid, msg=...

$ nc -zv localhost 9735
> localhost [127.0.0.1] 9735 (?) open

Port 9735 is the only one i get an reaction

**Comment by cfromknecht** [comment]
9735 is the peer port, you can’t use HTTP to connect to it. You need to connect to the REST port, default is 8080

**Comment by leblitzdick** [comment]
Ahh, I almost thought it could not be 9735. The error is still there, but now i can look for the real problem!

The Server System is quite old (Debian 7), perhaps there is a problem with the old PHP Version (5.6.35) that the plugin in WordPress must use.  

 thanks!
