### ISSUE TITLE
Proposal for option disable TLS for REST RPC endpoint.

### ISSUE THREAD

**Issue by Horndev** [lightningnetwork/lnd#1182]
### Background

Requiring clients to use https vice allowing http introduces a barrier for new clients.  Furthermore, using self-signed certificates (default) or CA issued certificates adds an additional layer of complexity for clients.  There is already the option for originating IP-restricted access, and required macaroons sent in the headers already provide authentication.

### Your environment

Applies to multiple evironments.

### Expected behaviour

An option in the lnd.conf, and/or command line to disable https.

### Actual behaviour

No way to disable TLS.

lnd uses a proxy for HTTP to gRPC, and TLS can be disabled by a change:

https://github.com/lightningnetwork/lnd/blob/bdf3f4d7753ce950bd14ed56ad96c12097f1b4c9/lnd.go#L541

Change that line to:

`listener, err := net.Listen("tcp", restEndpoint)`

to disable tls.

**Comment by Roasbeef** [comment]
It's likely the case that services _shouldn't_ directly expose the REST endpoint to the public interface. Instead, it was meant to serve as components in a backend service to drive an application.

**Comment by Roasbeef** [comment]
>  Furthermore, using self-signed certificates (default) or CA issued certificates adds an additional layer of complexity for clients

Everything on the web should be using TLS. One can either use the default certs of `lnd` (which shouldn't be an issue if just hitting a backend service as you already need the macaroons), or they can go the existing CA route (Let's Encrypt, or the like).

**Comment by Roasbeef** [comment]
> I guess the macaroons could be susceptible to copying by man-in-the-middle without TLS. Is this a weakness in that authentication approach?

Yep, which is why it's important to use TLS when connecting to the endpoint. It's the nature of the approach as it's a bearer API credential. The macaroons we have right now are pretty basic, but applications will be able to precisely tune the capabilities of the macaroon in order to mitigate the damage possible due to a compromise of the credential. 

> Other REST APIs use a secret key to sign requests when working over HTTP.

A naive implementation of that would still be subject to replay attacks.

**Comment by Horndev** [comment]
> A naive implementation of that would still be subject to replay attacks.

Right, so it's up to the server to make sure the implementation is sound :)  I think even "got-robbed-blind" MtGox had a proper secure REST API.  Maybe they should have also thought about other aspects.

So, maybe this issue - the inclusion of HTTP endpoint - would require a re-working of the macaroon authentication, and a full rework of the REST API so that it's not just a gRPC proxy.

The level of effort vs reward may be a bit low compared to some other issues right now.

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/4648 by allowing to disable TLS on non-public interfaces (to work behind a reverse proxy that then encrypts with TLS).
