### ISSUE TITLE
server+brontide: implement persistent banning and decaying DoS scoring

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1183]
Currently within `lnd`, we don't have any sort of persistent peer banning or DoS scoring. As we being to achieve reliability, this will be increasingly important to ensure that faulty or malicious peers aren't able to cripple the daemon. Many of the pieces are in place to implement proper peer banning and DoS scoring, but they haven't yet been assembled into a final usable form. In order to complete this issue, the owner of the issue will need to implement the following.

# Steps To Completion 

- [ ] The first component is the currently unused [`connmgr.DynamicBanScore`](https://godoc.org/github.com/Roasbeef/btcd/connmgr#DynamicBanScore). We'll first need to embed one of these within the each `peer` struct created. The implementor will then need to decide: what actions constitute an increase in the ban score, which actions result in a transient/permanent increase, and finally the threshold at which we'll actually ban for an event. Possible offenses that would constitute an increase in the ban score include: sending an invalid announcement, sending an announcement for an unknown chain, force closing channels, etc. 
- [ ] Now that we have a "score" for nodes, and also a threshold of when to ban, we'll need a way to remember which nodes that have been banned. We may want to ban on the basis of: node pubkey, node IP, and also possibly even IP ranges. The "ban store" itself, should be exposed via an interface such as:
```go
type BanStore interface {
    BanNode(pubkey *btcec.PublicKey, timeout time.Duration, addrs ...net.Addr) error
    UnbanNode(pubkey *btcec.PublicKey) error
    IsNodeBanned(pubkey *btcec.PublicKey) error
    IsAddrBanned(addr net.Addr) error
}
```
Once the threshold is reached, a node should be banned accordingly within the server itself. 

- [ ] A default implementation of the `BanStore` interface should be implemented in `channeldb`. 

- [ ] The final component is [`brontide`](https://github.com/lightningnetwork/lnd/tree/master/brontide) awareness. The `brontide` dialer should be modified to take the `BanStore` interface. When accepting a new connection, if the IP is banned, the socket should be closed.  Additionally, when we [recv act three](https://github.com/lightningnetwork/lnd/blob/master/brontide/noise.go#L603), we should check that the node pub key isn't banned, if so, the connection should be closed. 

- [ ] Finally, the `brontide` listener should return a set of structured errors. In the case that the remote node doesn't know our public key, or sends us an invalid handshake, then an error should be returned. This error should then be interpreted by the goroutine in the server, and then banned accordingly. 

Additionall measures (suggested by @aakselrod) include: 

 ### New connection manager
A new connection manager should be added. This connection manager would keep track of only peers that have no channels open (gossip peers), limiting the number of incoming and outgoing connections. Once one of the peers in the new connection manager becomes a channel peer, it should be moved to the existing connection manager which will be reserved for channel peers only.

### Non-gossip peers
With the new sync extensions, it will be possible to request graph gossip from only selected peers. This would be a useful feature to enable for:
  * Incoming connections which have had the option manually set via RPC
  * Persistent peers, by default
  * Channel peers, by default
   * Outgoing connections, by default

This would require an RPC to enable the option on specific incoming peers and disable the option on specific channel and outgoing connections. It would also require saving the peer's gossip/non-gossip state for node restarts.

**Comment by Crypt-iQ** [comment]
Can I take a stab at this?

**Comment by wpaulino** [comment]
Would say this is a pretty large task that would require a lot of communication and thought on the design front first before jumping straight into implementing this.
