### ISSUE TITLE
contractcourt+utxonursery: create stray output pool to be incrementally emptied

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1184]
Currently, within the daemon, due to varying output sizes, and the dynamic fee climate on the main chain, it may be the case that we're unable to sweep an output at the desired fee rate. This can happen when sweeping various outputs in the `contractcourt` package, breached outputs by the `breachArbiter`, and also time-locked outputs handled by the `utxoNursery`. At this point, these will be left on the chain as sort of "dust" output. Ideally, we should attempt to either drop the fee rate, or pool these outputs into a set, to be later spent. 

# Steps To Complete 

- [ ] The [`CheckTransactionSanity`](https://godoc.org/github.com/btcsuite/btcd/blockchain#CheckTransactionSanity) function should be more widely used _whenever_ we create transactions to sweep outputs generated by transactions. Even further, we should extend the function itself to return more details w.r.t _why_ the transaction is invalid. If we can return info concerning which output(s) to remove to maintain a certain fee rate, then we can slowly prune inputs/outputs until we're able to sweep a transaction. This can be done in an iterative loop. 

- [ ] We should adopt a fee rate _floor_ based on the widely used consensus fee rate floors. If we obtain a fee rate quote _below_ this, then we should bump the rate to ensure we've above the floor. 

- [ ] Finally, in the case that the output is simply too small to sweep at a target fee rate, it should be added to a "stray output" pool which is stored persistently. The items in this pool (on disk, but it should be interacted with via an interface, should include complete details w.r.t to _how_ to sweep this output. In many cases, the [`SignDescriptor`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/signdescriptor.go#L20) for the output should be sufficient. 

- [ ] A new sub-system should be erected to manage the stray output pool, and periodically batch these outputs into single transaction to sweep back into the wallet. A later extension can allow other sub-systems to use this as an extension point to implement further batching when sweeping outputs from various contracts.

**Comment by vapopov** [comment]
I'll take this issue

**Comment by Roasbeef** [comment]
Superseded by the Sweeper more or less.
