### ISSUE TITLE
[Logging] Error "unable to close channel" although channel is actually successfully closed

### ISSUE THREAD

**Issue by ripper234** [lightningnetwork/lnd#1189]
### Background

Following the tutorial on simnet, I'm trying to close the Alice <-> Bob channel from Alice's side.
Alice manages to close the channel (A subsequent `listchannels` afterwards does not list the channel).
However Bob has an ERR log with

`unable to respond to remote close msg: unable to close channel, ChannelID(6bb6bb69537f1cbf75db75eec97facbef4ccc19729bd759ef782036000f38090) is unknown`

I believe this ERR log should perhaps be a WARN or INFO instead, because the channel is indeed successfully closed (ERR logs should indicate ERROR conditions, not normal flow).

### Your environment

* lnd version 0.4.1-beta commit=097fd50747356a39593e5ac7625bf0b0fb1305a1
* Windows 10
* btcd compiled from source today from roasbeef branch commit a03db407e40d3b66ea29984263bbc8bf4d2f04c4

**Comment by Roasbeef** [comment]
It's a benign log statement, just that both sides echo back the last message during the close negotiation process. Typically the other side has already ack'd and then accepted the last closing message and cleaned up the state. As a result, the state machine responsible for processing this message has already exited.

**Comment by ripper234** [comment]
So, if it's a benign message ... shouldn't it be something other than ERR?

**Comment by Roasbeef** [comment]
Yep, not disagreeing!
