### ISSUE TITLE
admin.macaroon is not created when running lnd

### ISSUE THREAD

**Issue by ripper234** [lightningnetwork/lnd#1190]
### Background

I successfully completed stage 1 of the tutorial using `--no-macaroons`.
Now I'm trying to learn how to use macaroons.

The tutorial does not explain how to create the `admin.macaroon` file.
When I run lnd, it waits for the either `lncli create` or `lncli unlock`. No `admin.macaroon` file can be found anywhere on disk at this point.

These commands (`lncli`) however seem to require the existence of an `admin.macaroon` file.

```
>lncli --rpcserver=localhost:10001 --macaroonpath=C:\work\lnd\alice\data\admin.macroon getinfo
[lncli] open C:\work\lnd\alice\data\admin.macroon: The system cannot find the file specified.
```

Tried to `touch` it and then I got

`[lncli] empty macaroon data`

So, how do I create an initial macaroon file?

### Your environment

* lnd version 0.4.1-beta commit=097fd50747356a39593e5ac7625bf0b0fb1305a1
* Windows 10
* btcd compiled from source today from roasbeef branch commit a03db407e40d3b66ea29984263bbc8bf4d2f04c4

**Comment by dabura667** [comment]
if lnd is running with -no-macaroons, you don’t need to specify the macaroon

**Comment by ripper234** [comment]
It is no longer running with -no-macaroons, I just said that everything worked for me before without macaroons, I'm trying to get it to work with them now.

**Comment by dabura667** [comment]
If you run lnd in macaroon mode it automatically generates the macaroon in the default location.

Move the macaroon file to your folder you are specifying

**Comment by ripper234** [comment]
Is that the `macaroons.db` file? Because the tutorial speaks of `admin.macaroon`, but the file I see on disk is `macaroons.db`.

**Comment by ripper234** [comment]
It seems that just running lnd with no parameters creates the macaroons.db file, but contrary to the documentation it does not create an admin.macaroon file.

**Comment by guggero** [comment]
The admin.macaroon is only created after you run `lncli unlock` or `lncli create`. So you should run either of these commands first.
The macaroons.db is where the root key for the macaroons is stored, so it's in a different format and cannot be used for the `--macaroonpath` parameter.

**Comment by ripper234** [comment]
But doesn't `lncli unlock` require `--macaroonpath`? From your answer I guess not.
Ok, I will try this flow again and reopen if I run into issues.

**Comment by autemox** [comment]
> The admin.macaroon is only created after you run `lncli unlock` or `lncli create`. So you should run either of these commands first.
> The macaroons.db is where the root key for the macaroons is stored, so it's in a different format and cannot be used for the `--macaroonpath` parameter.

When I do "lncli --rpcserver=localhost:10001 --macaroonpath=data/admin.macaroon create" no admin.macaroon file is created.  Like the OP I have been able to do the tutorial with --no-macaroons on but when I try to complete the tutorial with macaroons, I have serious problem with no admin.macaroon file existing.

**Comment by ereztdev** [comment]
echoing this issue, I followed the same path of creating the macaroon, my network is testnet stipulated in lnd.conf as:
```
[Bitcoin]
bitcoin.testnet=1
bitcoin.active=1
bitcoin.node=btcd
```
created the macaroon with:  `lncli --rpcserver=localhost:10001 --macaroonpath=data/admin.macaroon create` for user under `$GOPATH/dev/user/`
After entering + confirming pwd,
refusing passphrase + enter for surpassing cipher seed passphrase
fresh cipher seed generated.
checking under `$GOPATH/dev/user/data/` no macaroon created.

I have to say that on my first run going through simnet with the alice/bob/charlie demo it did not work until I passed the `network` param stating simnet, now i'm trying to do the same, changed the `lnd.conf` to testnet and now macaroons are not created.

**Comment by ereztdev** [comment]
Moreover, `gracefully shutting down` from time to time gracefully **never** shuts down, just hangs.

**Comment by ereztdev** [comment]
Ok 
Would be wise to return a path created since the call is:
`lncli --network=testnet --rpcserver=localhost:10001 --macaroonpath=data/admin.macaroon create`
Which stipulates saving to `data` folder.

**Comment by cfromknecht** [comment]
@ereztdev `macaroonpath` is always passed as an argument for where to _read_ a macaroon. It is never used as the location to save one. Again, no macaroon path argument is required for `create`

**Comment by BrianSipple** [comment]
I think the confusion here stems from two things:

1. The tutorial snippet for `lncli create` uses `--macaroonpath`, even though it’s not needed.
2. The path is incorrect — assuming we want it to match the file that’s automatically generated _after_ initially running `lncli create`.

`2.` causes errors when trying to proceed from the tutorial from `1`. I submitted a PR for the fix.

**Comment by A-qiu161203** [comment]
sir, I met the same problem as you. Have you solved this problem yet? Could you please help me? Thank you very much!

**Comment by frazras** [comment]
Found mine at  ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
