### ISSUE TITLE
Improve message if lncli unlock is called multiple times.

### ISSUE THREAD

**Issue by mojoaxel** [lightningnetwork/lnd#1191]
### Background

Not an real issue but i got a little confused by this.:
If you call `lncli unlock` multiple times it prompts message that "lncli unlock" or "lncli init" should be called. That's confusing!

### Your environment

* lnd version 0.4.1-beta commit=9017d18f14d9cb07256dfa9c2927cb6d6431dbeb
* Linux bitcoin-full-node-with-lightning 4.4.0-121-generic
* Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

### Steps to reproduce

Call `lncli unlock` multible times.

### Expected behaviour

After calling `lncli unlock` the second time I would expect something like:
`[lncli] The wallet is already unlocked.`

### Actual behaviour

After calling `lncli unlock` the second time:
`[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.`

_I hope you don't mind opening this minor feature request_

**Comment by guggero** [comment]
Thank you for your issue!
This is indeed not really nice as the error message is very misleading.
I added a new message for this specific case (see #1193).
