### ISSUE TITLE
pending channel waiting for non existent txid

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#1197]
### Background

I started a connection from eclair android wallet (testnet) to my local LND
 channel negotiation run until wait_for_funding_confirmed and pending channel is showing in lnd's db
but, tx doesn't exist in the blockchain

### Your environment

lnd 0.41beta
4.15.0-20-generic #21-Ubuntu SMP  x86_64 GNU/Linux
bitcoind 0.16

### Steps to reproduce

open a channel from eclair wallet on android

lncli pendingchannels https://pastebin.com/tRrEZzje
lnd.log https://pastebin.com/k3FNg1US

look for txid 085ddddce49e3a279fa914c703824d7a6936287ed8524302155633f7ada35f2c

### Expected behaviour

discard channel ?

### Actual behaviour

channel pending forever

**Comment by Roasbeef** [comment]
If the phone never broadcasted the funding transaction itself then we'll eventually forget the non-confirming channel after a few days. I'd look into the eclair wallet itself to determine what actions it took and why it didn't broadcast the funding transaction.

**Comment by Roasbeef** [comment]
Is the channel still lingering?

**Comment by enorrmann** [comment]
still pending on lnd's side
tried to force close from eclair, but since there is no funding tx. it's still closing

**Comment by Roasbeef** [comment]
Update on this? The channel should have been removed at this point (due to timeout).

**Comment by enorrmann** [comment]
channel was still showing as pending, so I force closed it

 lncli closechannel --force 085ddddce49e3a279fa914c703824d7a6936287ed8524302155633f7ada35f2c 0
{
	"closing_txid": "e6a4a5bdd91af62029b6384c0bbfe0f6d2f39fa997167f8cdd9909692d23a182"
}

the channel is gone from lnd's db now, but I had to --force close it
also, closing txid doesn't exist on the chain

closing log 
https://pastebin.com/raw/BLMh2BUb

**Comment by Roasbeef** [comment]
Closing this issue for now as the original input to the funding transaction was actually spent by the eclair node. Perhaps an issue with concurrent coin selection on their end.
