### ISSUE TITLE
[feature request] add RPC for getting on-chain fee estimates

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1212]
Currently `lnd` fetches fee estimates from its chain backend several places, for instance: https://github.com/lightningnetwork/lnd/blob/ddcbb4089801bd632772ec57fba24f66e0bb3c97/rpcserver.go#L1112

These estimates are currently only used within `lnd` itself, and is not exposed to the user in any way.

### Steps to completion:
- [ ] Make a new RPC endpoint (proto + rpcserver implementation) that calls the `estimator` with a passed confirmation target.
- [ ] Create a new `lncli` command `estimatefee` that takes a block number and uses the new RPC endpoint to return a fee estimate in `sat/vbyte`.

**Comment by jrmillerwork** [comment]
I'd like to try this.

**Comment by halseth** [comment]
@jrmillerwork There's already a PR up for this: #1228

**Comment by jrmillerwork** [comment]
Okay, thanks. How to determine that there is a PR for a given issue?

**Comment by halseth** [comment]
If you look above, there's a fee issues/PRs referencing this issue. If you click the PR you can see that it says "Fixes #1212" 😄
