### ISSUE TITLE
lost Channel Informations after Reinstallation

### ISSUE THREAD

**Issue by KallerTobias** [lightningnetwork/lnd#1214]
I have LND on my Raspberry Pi 3. I tried to install the GUI App and the Pi died. So i backuped the data dir, config , macroons and tsl files. Now my pi is running again, but when I start LND with the old channel.db the start fails. So I did start the Lncli withour the channel file and everything is fine. But now all my informations about the channel data is lost and I have 0 open channels. Any way to force close these channels or impot them? 

### Your environment

* version of `lnd`: 0.4.1
* Rapian
* version of `btcd`, `bitcoind`, or other backend: 0.16

**Comment by Roasbeef** [comment]
>  I tried to install the GUI App

What GUI app? 

So you moved over your channel state but didn't ensure that all the files were swept over?

**Comment by KallerTobias** [comment]
This one: https://github.com/mably/lncli-web
But I'm more interested in closing all the cannels or get them back, any solution?

**Comment by KallerTobias** [comment]
OK, my Pi Crashe, so I Copied everything to a save HDD and reinstalled the Pi. Than bevore i started the LND firt time I copied the saved dir back in place and startet the LND. I will post the Log Files etc. when I'm home again.

**Comment by Roasbeef** [comment]
> panic: invalid freelist page: 3350, page type is leaf

It appears your SD card has become corrupted.

**Comment by TobiasKaller** [comment]
The Blockchain is still syncing at my windows PC. So there is a chance that I'll be able to get the channles back at the windows system?

**Comment by Roasbeef** [comment]
If you have your seed you can recover your on chain funds using `lncli create` with the latest version of master. I think it's possible to instead open up the database in a read-only form, to attempt to see what data can be obtained to recover the funds in channels as well.

**Comment by TobiasKaller** [comment]
Ok, so how can I open the db in read-only? And what do you mean with using the latest version of master?

**Comment by Roasbeef** [comment]
Latest version of master meaning the latest commit. 

> When I delete the channel.db an restart lnd.service I can unlock the wallet and everything is finde, just the Channels are missing.

If you've deleted everything, then unless you have a seed, your funds are lost.

**Comment by halseth** [comment]
@TobiasKaller No, only on-chain funds can be restored with the seed unfortunately.
