### ISSUE TITLE
Question: Remove existing wallet and create new one

### ISSUE THREAD

**Issue by mojoaxel** [lightningnetwork/lnd#1216]
### Background

Let's say someone lost access to their lnd wallet (asking for a friend :wink:) and now he wants to create a new wallet?

Just calling `lncli create` returns an error, as expected:
`[lncli] unable to generate seed: rpc error: code = Unknown desc = wallet already exists`

**What would be the best way of removing the old wallet and creating a new one? Just delete all macraroon files?**

By the way. The error is thrown at the end of the create-wallet process. It would be nice if `lncli create` would return an error instantly and not ask for all the passwords and ciphers first!

### Your environment

* lnd version 0.4.1-beta commit=9017d18f14d9cb07256dfa9c2927cb6d6431dbeb
* Linux bitcoin-full-node-with-lightning 4.4.0-121-generic
* Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

_Thanks for the Help!_

**Comment by Roasbeef** [comment]
> What would be the best way of removing the old wallet and creating a new one? Just delete all macraroon files?

Just delete all your old state, then start over again.

**Comment by mojoaxel** [comment]
Thanks the quick answer!

> Just delete all your old state, then start over again.

My question is what is the "old state". Is it all macaroon files? Some configs? For me and also for documentation purposes it would be nice to know what information is stored where.

**Comment by Roasbeef** [comment]
> My question is what is the "old state". Is it all macaroon files? Some configs? For me and also for documentation purposes it would be nice to know what information is stored where.

Old state is everything in the `lnd` application directory. The location depends on you OS, for example will be in `~/.lnd` for linux.

**Comment by miketwenty1** [comment]
Is there a more surgical way to do this? Would I be able to delete just enough to prompt a new "Create or unlock wallet prompt" and not botch the lnd service.  I'm trying NOT to delete everything as that would cause a new rescan of the entire blockchain.

**Comment by Jeans5** [comment]
I removed everything in the ~/.lnd directory and still got this error:

> [lncli] unable to generate seed: rpc error: code = Unknown desc = wallet already exists

**Comment by tailnode** [comment]
I deleted `~/.lnd/data`, it works.

**Comment by vwas2** [comment]
i dont consider  "I deleted ~/.lnd/data, it works." a solution since it changes identity_pubkey (and all connected setups). 
Rbeef comment "Just delete all your old state, then start over again." is also insufficient. 

Do better, provide solution, please reopen.

**Comment by mrmcbitcoin** [comment]
I did

rm ~/.lnd/data/chain/bitcoin/mainnet/wallet.db

**Comment by realizecondition** [comment]
I will leave this here in case it helps someone else.

I was able to prompt creating a new wallet (resolve "[lncli] unable to generate seed: rpc error: code = Unknown desc = wallet already exists" without having to even shut down the lnd) by simply renaming "\Lnd\data\chain\litecoin\mainnet\wallet.dat" to a different filename.
