### ISSUE TITLE
confirmation_height is always zero

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#1217]
### Background

while a channel is in pending state lncli pendingchannels always shows "confirmation_height" : 0

### Your environment

lnd 0.41beta
 4.15.0-20-genericx86_64 GNU/Linux
bitcoind 0.16

### Steps to reproduce

open a channel to LND from other client
list channels with lncli pendingchannels
wait for some confirmations

### Expected behaviour

confirmation_height should show the number of confirmations

### Actual behaviour

confirmation_height always show 0

**Comment by Roasbeef** [comment]
The confirmation height simply isn't set anywhere atm.

**Comment by KevinKelbie** [comment]
Would it be more suitable to have it set at -1 to show that it isn't in a block yet? Block height 0 is a valid block height whereas -1 isn't.

**Comment by danielemiliogarcia** [comment]
it would be nice to have this one! to track pending-opening channels progress!  It'll be of great help. Great project!

**Comment by danielemiliogarcia** [comment]
@Roasbeef  how difficult or large you estimate this fix? thinking about contributing with a PR


2 replies

**Comment by wpaulino** [comment]
It should be a small change. All the information is already stored within the database to set the field in the [RPC response](https://github.com/lightningnetwork/lnd/blob/9f7d2f6cbcfbfa74abc0d170a3caccfd21791c00/rpcserver.go#L1952). The confirmation height should be [`FundingBroadcastHeight`](https://github.com/lightningnetwork/lnd/blob/9f7d2f6cbcfbfa74abc0d170a3caccfd21791c00/channeldb/channel.go#L373) + [`NumConfsRequired`](https://github.com/lightningnetwork/lnd/blob/9f7d2f6cbcfbfa74abc0d170a3caccfd21791c00/channeldb/channel.go#L379).

**Comment by nicolasburtey** [comment]
I'm also seeing this issue. wouldn't it make sense to just remove the confirmation_height key pair from the JSON until it's fixed?

**Comment by instagibbs** [comment]
at minimum just update docs to say it's deprecated?
