### ISSUE TITLE
high memory usage when connected to bitcoind undergoing initial block download

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#1218]
### Background

I just installed lnd with bitcoind on mainnet. After bitcoind finished reindexing (due to txindex) , the RAM usage of lnd increased steadily to more than 30 GByte (on a system with 128 GByte RAM). 

The last few log messages (trace):

```
2018-05-09 22:40:50.821 [INF] LNWL: Catching up block hashes to height 521895, this might take a while
2018-05-09 22:40:50.822 [INF] LNWL: Done catching up block hashes
2018-05-09 22:40:50.822 [INF] LNWL: Finished rescan for 0 addresses (synced to block 0000000000000000001d32cb2a1929ff90721e94626c3f44ced62af5b9a530d6, height 521895)
2018-05-09 22:41:54.484 [DBG] LNWL: Possible reorg at block 0000000000000000004134af5968669d654605ecb0836c4424baa45754dfbae7
```

### Your environment

* version of `lnd`: lnd version 0.4.1-beta
* which operating system (`uname -a` on *Nix): Linux ftp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core Daemon version v0.16.0

### Steps to reproduce

Start bitcoind with reindex and txindex=1, start lnd, wait

### Expected behaviour

Less memory consumption. I also notice other log messages now (gossip?) that did not appear before the forced restart.

### Actual behaviour

High memory consumption, steadily growing.

**Comment by Roasbeef** [comment]
So you're attempting to sync `lnd` and `bitcoind` concurrently? We recommend instead letting `bitcoind` fully sync, then start up `lnd`. If you follow this path, then certain optimizations that we put into place to detect the case where `bitcoind` is already synced will allow your node to boot up much faster.

**Comment by C-Otto** [comment]
I don't know what lnd did, but `bitcoind` certainly was doing some work (writing lots of data to disk, at least). A restart solved the issue. I still don't think that `lnd` should consume several GByte of RAM. Fpr this very specific case I'm fine with lack of optimizations, though.

**Comment by Roasbeef** [comment]
> I still don't think that lnd should consume several GByte of RAM. 

In the normal case it doesn't. I have an `lnd` node on testnet consuming 20MB as an example. 

> For this very specific case I'm fine with lack of optimizations, though.

To re-word my comment above: one should allow their `bitcoind` node to fully sync before starting up `lnd`. 

If you're able to reproduce this, [if you run with the `--profile` flag set, then you can easily extract a memory profile of all the goroutines in the entire daemon](https://blog.golang.org/profiling-go-programs). With this, we can then pinpoint why you're seeing high memory usage with `lnd` connected to a `bitcoind` that's undergoing the initial block download.

**Comment by Roasbeef** [comment]
Yes the issue is that during IDB, due to the _bounded_ queue of RPC requests, bitcoind  can't keep up with out requests. As a result, it drops them and we currently don't retry for those assuming that bitcoind is "trusted". A temp work around would be increasing the size of the RPC work queue.

**Comment by wpaulino** [comment]
No longer an issue as of https://github.com/lightningnetwork/lnd/pull/3141.
