### ISSUE TITLE
tests: extend integration tests to grab snapshot of active goroutines on failure 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1219]
Currently, if we encounter deadlocks when modifying or adding new integration tests, it's a bit difficult to pinpoint exactly what the flaw in the new test/code is. All `lnd` instances running in the test now also [expose the profile port which allows us to obtain valuable debug information](https://github.com/lightningnetwork/lnd/blob/master/lntest/node.go#L262). It would be really useful if upon test failure, the framework hit the profile page over HTTP (http://localhost:port/debug/pprof/goroutine?debug=1) for each active node in the harness, and then write that out on disk in an appropriately name filed. 

# Steps To Completion 

- [ ] Upon test failures, scan through all active nodes and hit their profile page (`/debug/profile/goroutine`) in order to obtain a snapshot of the set of active goroutines. 

- [ ] Once the goroutine snapshot has been obtained, a new file should be written to disk for each node using a similar naming scheme as to the one we use currently for the regular set of logs.

**Comment by taketa** [comment]
I'll take this issue
