### ISSUE TITLE
walletunlocker+lnd: eliminate extra scrypt invocation on wallet unlock 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1223]
Atm, when we unlock the daemon for the the first time, we incur 3 scrypt invocations: [checking if the wallet password is correct](https://github.com/lightningnetwork/lnd/blob/master/walletunlocker/service.go#L263), [attempting to decrypt the root macaroon store](https://github.com/lightningnetwork/lnd/blob/master/walletunlocker/service.go#L280), and [a third time when we go to create the `LightningWallet` itself](https://github.com/lightningnetwork/lnd/blob/master/chainregistry.go#L514). Only two are absolutely necessary. Getting rid of the extra invocation will speed up the start time, and also lessen the computational/memory load on constrained devices (mobile phones, pi's, etc)

# Steps To Completion 

- [ ] Eliminate the final scrypt invocation. This can be achieved by passing the instantiated `WalletController` implementation directly from the `WalletUnlocker`. This may require a bit of re-working in the way we handle config parsing.

**Comment by guggero** [comment]
I would like to work on this, if that's OK.

**Comment by guggero** [comment]
Can be closed IMO, since #1239 is committed.

**Comment by Roasbeef** [comment]
Closed by #1239.
