### ISSUE TITLE
rpc: add support for unix sockets 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1224]
Currently, we only support binding to TCP interfaces for both RPC servers. We can easily add support for `unix` sockets as well. This would entail being able to recognize, parse, and then bind to the specified unix socket. 

- [ ] A good starting point would this [this comment that more or less outlines the parsing and binding process](https://github.com/lightningnetwork/lnd/pull/495#issuecomment-355931289).

**Comment by guggero** [comment]
Cool, I'll try to implement that.

**Comment by maurycy** [comment]
@guggero Any success? I've started playing with this code.

**Comment by guggero** [comment]
Yes, I have a working solution ready. It just needs some tidying up then I'll create the Pull Request. Should probably have time to do so tomorrow.

**Comment by maurycy** [comment]
@guggero :+1:
