### ISSUE TITLE
rpc+contractcourt: merge the contractResolver state into the pendingchannels RPC response 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1227]
Currently, the `pendingchannels` RPC will only display information drawn from the `utxoNursery` for pending force close channels. However, for a channel that was forced closed with active HTLCs, the HTLC outputs won't be sent to the nursery until they're fully mature. As a result, atm, there's a gap where all information isn't displayed on the RPC layer. This should be reconciled by having the `pendingchannels` RPC query the `chainArbitrator` to obtain information regarding all active `contractResolvers` for a particular channel point.

There are currently four types of [`contractResolvers`](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/contract_resolvers.go#L23): timeout, success, timeout contest, and success contest. The first two are terminal states and will result in outputs being swept on chain by the [ `utxoNursery`](https://github.com/lightningnetwork/lnd/blob/master/utxonursery.go#L214) or the resolver directly. The latter two, are _indeterminate_ states. In this state we're either waiting for an HTLC to timeout, a pre-image to be discovered off-chain, or a pre-image to be discovered on-chain. During this period of time (before expiry or sweeping), there's no information available on the RPC layer concerning these HTLCs. In order to reconcile this, we'll need to extend the `pendingchannels` RPC call to also pull in information concerning these HTLCs. 

One possible path would be to extend the [`HTLC`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L757) with a new enum showing the current status of the HTLC itself.

**Comment by orbitalturtle** [comment]
I'll work on this.

**Comment by Roasbeef** [comment]
Forgot to comment, but this had been assigned, sorry!

On May 20, 2018 10:38 AM, "orbitalturtle" <notifications@github.com> wrote:

I'll work on this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1227#issuecomment-390498494>,
or mute the thread

**Comment by Roasbeef** [comment]
Resolved w/ #1875.
