### ISSUE TITLE
rpc+routing: cache DescribeGraph response, move calculation into ChannelRouter

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1232]
I run a few nodes on mainnet that are used to seed the DNS bootstrapping that `lnd` will use by default if it doesn't have an existing channel graph to use to seek out its set of initial peers. I've noticed that the `DescribeGraph` response itself can generate quite a bit of garbage, and this will only get worse as the size of the advertised graph grows. We can easily combat this by caching the result of `DescribeGraph`, the cache would be evicted each time a new channel is opened, or a channel is closed, similar to the `queryRoutes` cache that we have in the router.

**Comment by adilw3nomad** [comment]
I can pick this up. I've read the comments on 1377 and understand that we want to cache the gRPC response itself.

**Comment by Roasbeef** [comment]
@adilw3nomad correct!
