### ISSUE TITLE
lncli+macaroons+rpc: create encrypted macaroon jar for remote client-side macaroon storage

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1237]
Currently, all the default macaroons we generate are stored client-side unencrypted on-disk. With #1236, users will be able to instantiate `lnd` remotely without writing any macaroons to disk while obtaining the root macaroon which allows them to create distinct constrained macaroons. Once this is implemented, it would be nice if `lncli` detected this operating mode, and prompted the users (maybe) for a password to use to encrypted these macaroons in a database on disk. `lncli` would then gain more awareness w.r.t the mapping of certain commands to the particular macaroon needed and would decrypt them on demand. 

Related to #1236

**Comment by guggero** [comment]
The only thing that's missing here (with both #4310 and #1236 now merged) is that `lncli` automatically asks to create a profile if the `--stateless_init` flag of `lncli create` is used.

**Comment by Roasbeef** [comment]
Closing this since we have #4310 implemented now. I think the remainder could be handled in `lndinit`.
