### ISSUE TITLE
Using roasbeef/btcd breaks db compatibility with btcsuite/btcd

### ISSUE THREAD

**Issue by stevenroose** [lightningnetwork/lnd#124]
After running roasbeef/btcd on testnet, btcsuite/btcd was unable to use the database afterwards.

I reported the problem here first: https://github.com/btcsuite/btcd/issues/918

**Comment by Roasbeef** [comment]
[Responded](https://github.com/btcsuite/btcd/issues/918#issuecomment-276904543) in the original issue.

**Comment by stevenroose** [comment]
Well, I guess it's ok to close this issue. Or maybe wait until segwit lands in btcd#master. Up to you.
