### ISSUE TITLE
Funding transaction of active channel not in listchaintxns

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#1244]
### Background

I opened a channel which works as intended. However, the funds from the funding transaction are still shown in my wallet, and the funding transaction of that channel is not shown in `listchaintxns`. As a result I'm able to create new channels using those funds, resulting in:

> FNDG: Unable to complete reservation sign complete: Transaction rejected: output already spent

The funding transaction is 2e719e9407a128c76e15d190a133d929ff7d229f4ac639b3611251858118c049.

Channel information:
```
{
"active": true,
"remote_pubkey": "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432",
"channel_point": "2e719e9407a128c76e15d190a133d929ff7d229f4ac639b3611251858118c049:0",
"chan_id": "574506920233533440",
"capacity": "145955",
"local_balance": "74202",
"remote_balance": "69400",
"commit_fee": "2353",
"commit_weight": "724",
"fee_per_kw": "3250",
"unsettled_balance": "0",
"total_satoshis_sent": "0",
"total_satoshis_received": "600",
"num_updates": "11",
"pending_htlcs": [ ],
"csv_delay": 144,
"private": false
}
```

### Your environment

* lnd version 0.4.1-beta commit=28b12116e42c83149b6c6b93b70d669a0702bd2d
* Linux ftp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
* Bitcoin Core 0.16.0

### Steps to reproduce

Create channel, force-close another channel, try to create a new channel.

### Expected behaviour

The funds should not be marked as available, the funding transaction should appear in the list

**Comment by aakselrod** [comment]
@C-Otto Do you have any logs from when you opened the channel whose funding tx isn't seen?

**Comment by C-Otto** [comment]
@aakselrod I have plenty of logs, this seems to be the interesting part: https://ftp.halifax.rwth-aachen.de/~cotto/2e71.txt
Feel free to ask for more! Thanks :)

**Comment by aakselrod** [comment]
Did you save the seed from when this wallet was created?

**Comment by C-Otto** [comment]
@aakselrod of course :)

**Comment by C-Otto** [comment]
I managed to rescan my wallet using `dropwtxmgr` (https://github.com/roasbeef/btcwallet/tree/master/cmd/dropwtxmgr).
