### ISSUE TITLE
rpc+lnrpc: add new closechannels cli+rpc command

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1250]
Currently, there's no way of viewing the _past_ history of closed channels. Channels may have been closed due for many reasons (co-op, force, breach, etc), but none of this data is yet visible to the end user. Additionally, UI's will likely want to display the past history of closed channels, as it's possible that a channel was closed while the end user was offline. [We already keep the full history of all closed channels within the database](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L1623), so no new DB modifications should be necessary. 

# Steps To Completion 

- [ ] Create new `ClosedChannels` RPC within `lnrpc`. The field returned should be some subset of the existing `ChannelCloseSummary` struct. 

- [ ] Implement the new RPC within `rpcserver.go`

- [ ] Add a matching `closechannels` command to `lncli`. Desirable arguments may be filtering amongst the various close types (force, breach, etc).

**Comment by wpaulino** [comment]
Closed by #1274.
