### ISSUE TITLE
chains: move ltc support and all future alt-chains behind a build flag

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1251]
`lnd` currently supports both BTC and LTC, and there're plans to refactor the chain selection in the future in order to allow developers of other chains to add arbitrary chains in the future. However, in order to achieve this, we'll need to move to a more "plug in" oriented system where in the chain implementations are actually _external_ to `lnd` itself, and are instead constructed at "run time". 

With the current implementation, although only BTC is used primarily, we're still forced to always pull and and compile `ltcsuite` as well. This adds to the size of the binary, and also slows down compilation times a bit. We should move to instead guard all the LTC support behind a new _build_ flag (`-tags=ltc`). The major release of `lnd` will be compiled with this flag active, but the existence fo the flag means that developers creating specialized deployments can opt out.

# Steps To Completion 

- [ ] Split the current [`chainparams.go`](https://github.com/lightningnetwork/lnd/blob/master/chainparams.go) file into two distinct files. The LTC file [should be guarded with a build flag](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) such that it's only compiled with the tag active. 

- [ ] Elements of [`chainregistry.go`](https://github.com/lightningnetwork/lnd/blob/master/chainregistry.go) should also be extracted into individual files with build flags guarding their compilation as needed.

**Comment by maurycy** [comment]
I will start working on this.

**Comment by maurycy** [comment]
I will start working on this (accidentally deleted the previous comment.)

**Comment by Roasbeef** [comment]
I think we'll just continue removing it all together at this point.

**Comment by saubyk** [comment]
Closing this as LTC support will be removed from 0.18 onwards.
