### ISSUE TITLE
logging: unify logging of `lnwire.ShortChannelID`

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1252]
We use [`ShortChannelID`s](https://github.com/lightningnetwork/lnd/blob/master/lnwire/short_channel_id.go#L7) to uniquely locate channel within the chain. A `String` method was recently added to print out the short chan ID in a `block:tx_index:output_index` format. This method is now _implicitly_ used when passed into a formatting directive with out using the `ToUint64()`. However, much of the codebase is still split between these two formats. For example, during the discovery/funding process, we use `ToUint64()` [rather widely within the codebase](https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L1419). On the other hand, each time we log a wire message, it uses the `String` method directly. 

# Steps To Completion 

- [ ] Comb through the codebase and switch to using either the `String` method or the `ToUint64()` variant.

**Comment by maurycy** [comment]
I will start working on this.
