### ISSUE TITLE
Wrong description/name for openchannel local_amt

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#1259]
When I open a channel using `openchannel`, the amount given as `local_amt` is the whole channel capacity. In other words, the `push_amt` is included in this amount. Instead, I expect the parameter to be named `channel_capacity` or similar.

When the channel is opened successfuly, the original `local_amt` is shown as `capacity`, while `local_balance` is whatever remains after deducting `push_amt`/`remote_balance` and fees/reserve.

### Your environment

* lnd version 0.4.1-beta commit=28b12116e42c83149b6c6b93b70d669a0702bd2d
* Linux ftp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
* Bitcoin Core 0.16.0

**Comment by Roasbeef** [comment]
If you look at `lncli openchannel -h`, the `local_amt` is the total amount that you wish to commit to the channel. Optionally, you can push a portion of that amount immediately to the remote party. `capacity = local_amt + push_amt`. The fee is variable, and the reserve is a fixed amount that cannot be used.

**Comment by C-Otto** [comment]
Yes, that part of the help text is quite accurate (the name, however, is misleading). I also see this:

> The channel will be initialized with local-amt satoshis local and push-amt
>   satoshis for the remote node.

I'd say the part "local-amt satoshis local" is, at least, misleading.

**Comment by C-Otto** [comment]
Please re-open. The referenced commit does not clarify the confusion about `local_amt` (which actually is the channel capacity).
