### ISSUE TITLE
[ERR] SRVR: unable to start server bad-txns-in-belowout

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#1261]
### Background

lnd crashes at startup with error 

### Your environment
0.4.1-beta commit=6a2a049df13103918546a3fc83d65862b68d9708
Linux 4.13.0-1015-gcp  x86_64 GNU/Linux
bitcoind 0.16

out
https://pastebin.com/raw/K7KzHKix

and lnd.log
https://pastebin.com/raw/pBN1gqr1

**Comment by cfromknecht** [comment]
Appears similar to #1267

**Comment by enorrmann** [comment]
I'm trying to debug this but I can't find the error string "bad-txns-in-belowout" anywhere in the source

**Comment by enorrmann** [comment]
found it in bitcoin's  [source](https://github.com/bitcoin/bitcoin/blob/3c098a8aa0780009c11b66b1a5d488a928629ebf/src/consensus/tx_verify.cpp#L238)

```c
    if (nValueIn < value_out) {
        return state.DoS(100, false, REJECT_INVALID, "bad-txns-in-belowout", false,
            strprintf("value in (%s) < value out (%s)", FormatMoney(nValueIn), FormatMoney(value_out)));
    }
```

**Comment by enorrmann** [comment]
I have collected the logs since channel opening [here](https://www.dropbox.com/home/public/lnd/logs/lnd_issue_1261)
