### ISSUE TITLE
LND RPC API Issues with StopDaemon command

### ISSUE THREAD

**Issue by neogeno** [lightningnetwork/lnd#1265]
### Background

LND Refuses to respond to StopDaemon() API unless chain is fully synched. It also doesn't reply whether it was successful or not in either case when a stop is requested.

### Your environment

* version of `lnd` Version 0.4.1-beta commit=9f6af3a2c1b036fb224949753054afc684e30644
* which operating system (`uname -a` on *Nix)  Linux Ubuntu 16
* version of `btcd`, `bitcoind`, or other backend btcd Version 0.12.0-beta
* any other relevant environment details Using nodejs grpc-node to access LND API

### Steps to reproduce

1. Start a new LND node accessible remotely its IP and TLS Cert, Macaroon
2. Using Javascript API Setup a lightning connection to the node and issue:

call = lightning.stopDaemon({}, function(err, response) {
     console.log('StopDaemon: ' + JSON.stringify(response));
 })

### Expected behaviour

The callback function should output IDEALLY something like {status: 'stopped} or similar and shut down the node at the earliest in a graceful manner.

### Actual behaviour

If the node is fully synched, it will shutdown as expected but return empty response {}. If the node is not yet synched the callback function will timeout and do nothing.

**Comment by rawtxapp** [comment]
I believe lnd doesn't check for shutdown requests while it's syncing, I patched it myself by doing this: https://github.com/rawtxapp/lnd/blob/newmerge/lnd.go#L583, if the lnd devs thinks it's a good idea, I can create a patch and send it to lnd master.

**Comment by neogeno** [comment]
Thanks for addressing this so fast  - you guys are rockstars!
