### ISSUE TITLE
Unconfirmed balance in wallet appears to be a duplicate of a closed channel transaction and is now stuck

### ISSUE THREAD

**Issue by Cees2daBees** [lightningnetwork/lnd#1268]
### Background

wallet balance shows an unconfirmed balance which appears to be a duplicate of a closed channel

### Your environment

lnd version 0.4.1-beta commit=
Linux RaspiBolt 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l
Bitcoin Core Daemon version v0.16.0

### Steps to reproduce

$ lncli walletbalance
{
    "total_balance": "225266",
    "confirmed_balance": "195602",
    "unconfirmed_balance": "29664"
}

### Expected behaviour

After a reboot of my RaspiBolt, one of the channels that I was connected to was closed. The funds in the channel was returned to my wallet as expected. The funds from that channel was 29664 and showed up as an unconfirmed balance and then was added to the confirmed balance shortly thereafter.

### Actual behaviour

After some time (a day later maybe, I don't recall) and for some unknown reason, the amount of 29664 again showed up on my wallet balance query as an unconfirmed balance. This was in addition to the 29664 that was already confirmed and still included in my confirmed balance. And so, this additional 29664 shown as unconfirmed balance is surplus funds that should not be in my wallet or my channel balances. This amount has been shown as unconfirmed in my walletbalance for about 6 days now. There does not appear to be any on-chain txns that did not confirm as the last on-chain txn was confirmed as shown below:

"tx_hash": "2bb8c84969d872183bbb8ffefdd32f5e6a78d8ffddaeb49e8ad8f3fa83631098",
            "amount": "29664",
            "num_confirmations": 1053,
            "block_hash": "00000000000000000031db80b6e6c391b46417c5073d9400f1c1edcbd963abde",
            "block_height": 522723,
            "time_stamp": "1526350282",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qawl2f8nvt2h8uucruxzynmkpkh546ne2xndxns"

**Comment by Roasbeef** [comment]
Did you reboot the entire rasp pi? Or just `lnd` or just `bitcoind`? Which commit were you running? Do you have logs for `lnd` (with `LNWL=trace` logging) on start up?

**Comment by Roasbeef** [comment]
> Is there a way I can determine which commit I'm running?

Current builds compile in the commit hash into the binary, so looks like you're running an older build. 

> Not sure how to get those lnd logs, do I just include the LNWL=trace line in the lnd.conf file?

Yeah, then you'll find the logs in the `~/.lnd` directory, assuming you didn't modify the `lnddir`.

**Comment by cfromknecht** [comment]
@Cees2daBees your conf should contain:
```
debuglevel=LNWL=trace
```
to target one subsystem. You can also target multiple using commas
```
debuglevel=LNWL=trace,PEER=debug
```

**Comment by Cees2daBees** [comment]
hope i did this right... log file attached

[lnd.log](https://github.com/lightningnetwork/lnd/files/2024810/lnd.log)

**Comment by Cees2daBees** [comment]
I'm not too sure what I'm looking at in this log file, but I did notice something that I think seems unusual. There is a line in the log file that reads as per below. The transaction hash matches what I've pasted above from my last on-chain txn that confirmed. Perhaps this is why my wallet balance continues to show an unconfirmed balance? I've searched the entire log file for the word "inserting" and this line is the only place it shows up. Any ideas? I don't want to do anything else with my node, like open or close any other channels, for fear of it getting stuck behind this unconfirmed txn?

2018-05-16 01:22:02.225 [INF] LNWL: Inserting unconfirmed transaction 2bb8c84969d872183bbb8ffefdd32f5e6a78d8ffddaeb49e8ad8f3fa83631098

**Comment by Roasbeef** [comment]
@Cees2daBees ok so it seems that there's an error on transaction submission rejection that we're not currently detecting by default. When you restart `lnd`, and look at your `bitcoind` logs, do you see that transaction being rejected? 


>  I don't want to do anything else with my node, like open or close any other channels, for fear of it getting stuck behind this unconfirmed txn?

You should be able to do those other things. The issue here is that the transaction is being rejected, but we aren't removing the unconfirmed transaction from the transaction store, so the input used shows up as an unconfirmed balance.

**Comment by Cees2daBees** [comment]
Updated to 0.4.2-beta and walletbalance no longer shows that unconfirmed balance.
Thanks!
