### ISSUE TITLE
Make Check fails - TestLightningNetworkDaemon

### ISSUE THREAD

**Issue by sunnya97** [lightningnetwork/lnd#1284]
### Background

Did first time install of lnd and tried to run `make check` and it alternates between 2 different errors on TestLightningNetworkDaemon (which means Error 1 seems to be non-deterministic as it passes sometimes?)

Error 1:
```
FAIL: TestLightningNetworkDaemon/test_multi-hop_htlc_local_force_close_immediate_expiry (27.37s)
    	lnd_test.go:69: Failed: (test multi-hop htlc local force close immediate expiry): exited with error: 
    		*errors.errorString alice's channel still has active htlc's
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:6415 (0xb3c54d)
    			testMultiHopHtlcLocalTimeout: t.Fatalf("alice's channel still has active htlc's")
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:94 (0xb1479b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:9289 (0xb58079)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/usr/local/go/src/testing/testing.go:777 (0x4eee20)
    			tRunner: fn(t)
    		/usr/local/go/src/runtime/asm_amd64.s:2361 (0x45bee1)
    			goexit: BYTE	$0x90	// NOP
```
Full log here: https://pastebin.com/1aRxr8Mt

Error 2:
```
FAIL: TestLightningNetworkDaemon/test_multi-hop_htlc_local_force_close_immediate_expiry (27.37s)
    	lnd_test.go:69: Failed: (test multi-hop htlc local force close immediate expiry): exited with error: 
    		*errors.errorString alice's channel still has active htlc's
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:6415 (0xb3c54d)
    			testMultiHopHtlcLocalTimeout: t.Fatalf("alice's channel still has active htlc's")
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:94 (0xb1479b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/sunnya97/go/src/github.com/lightningnetwork/lnd/lnd_test.go:9289 (0xb58079)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/usr/local/go/src/testing/testing.go:777 (0x4eee20)
    			tRunner: fn(t)
    		/usr/local/go/src/runtime/asm_amd64.s:2361 (0x45bee1)
    			goexit: BYTE	$0x90	// NOP
```

Full logs here:  https://pastebin.com/kfAze9eY

### Your environment

* version of `lnd` 
`lnd version 0.4.1-beta commit=9eef31d21087ec93645974378af0e226e3bc7f49`
* which operating system (`uname -a` on *Nix)
`Linux sunnya97-Z370N 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
`btcd version 0.12.0-beta`
* any other relevant environment details
`go version go1.10.2 linux/amd64`

### Steps to reproduce

See background

### Expected behaviour

Pass

### Actual behaviour

Fails

**Comment by Roasbeef** [comment]
See #1279.

**Comment by sunnya97** [comment]
Oh cool, thanks.  Will keep an eye on that PR.

P.S. Holy shit.  That was the fastest response time I've ever seen to a Github issue. Can all project maintainers please be you?

**Comment by Roasbeef** [comment]
Closing for now as this _particular_ flake has been resolved. We're working on resolving the new flake you ran into on the link PR. Thanks for testing lnd!
