### ISSUE TITLE
pending channels lingering after failed broadcast

### ISSUE THREAD

**Issue by rubenkr** [lightningnetwork/lnd#1290]
### Background & Description
I am running a btc full node and lnd on top of it.
So far everything was running okay until today somewhere noon. I noticed that my channels broke down from 130 to 70 active channels. And I was having 8 pending channels since days open. I am not able to shutdown lncli stop. It hangs saying `[ERR] FNDG: waiting for fundingconfirmation failed`.

### Environment
I am running Ubuntu 14.06LTS and latest LND from Github.
lnd version 0.4.1-beta commit=
3.13.0-145-generic #194-Ubuntu SMP Thu Apr 5 15:20:44 UTC 2018 x86_64 x86_64 x86_64 
Bitcoin Core Daemon version v0.16.0.0-845838c

### Steps to reproduce

```
lncli getinfo
{
    "identity_pubkey": "032b2b3f4abda9677bb9563e226c068d3a2456fb8b036635a81c9bcaa1671d1ada",
    "alias": "KRYPTO.KOELN",
    "num_pending_channels": 8,
    "num_active_channels": 0,
    "num_peers": 0,
    "block_height": 524649,
    "block_hash": "0000000000000000000678ed5d5a4e7abbb0526c6ee0ee5ebf1b8fc5a8290b9e",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "032b2b3f4abda9677bb9563e226c068d3a2456fb8b036635a81c9bcaa1671d1ada@5.189.141.242:9735"
    ],
    "best_header_timestamp": "1527423277",
    "version": "0.4.1-beta commit="
}
```

### Expected behaviour

Pending channels will be closed automatically and not blocking other channels funding.

### Actual behaviour
Stop Funding does not behave normally and prevents LND from normal shutdown. Trying to kill process and restart manually does not solve the problem, but keeps hanging with pending channels, not establishing active channels again.
```
2018-05-27 14:33:23.433 [WRN] FNDG: fundingManager shutting down, stopping funding flow for ChannelPoint(e4d1e62e3743ae6aa67a6d7f550063187a8bb7985e7f011d92ee31082eb88483:1)
2018-05-27 14:33:23.433 [WRN] FNDG: fundingManager shutting down, stopping funding flow for ChannelPoint(341a99578bf711ca651bf84ad232b302b832ef8241aad809a4e064216658c027:1)
2018-05-27 14:33:23.433 [ERR] FNDG: waiting for fundingconfirmation failed
^C^C^C^C2018-05-27 14:38:48.897 [INF] NTFN: Cancelling epoch notification, epoch_id=5
2018-05-27 14:38:48.897 [INF] NTFN: Cancelling epoch notification, epoch_id=8
2018-05-27 14:38:48.897 [INF] NTFN: New confirmation subscription: txid=7aabf0af311b31169a4619417e9490a0507879c9c877907c0227f416889972b1, numconfs=3
2018-05-27 14:38:48.897 [INF] FNDG: Waiting for funding tx (7aabf0af311b31169a4619417e9490a0507879c9c877907c0227f416889972b1) to reach 3 confirmations
2018-05-27 14:38:48.897 [WRN] FNDG: fundingManager shutting down, stopping funding flow for ChannelPoint(7aabf0af311b31169a4619417e9490a0507879c9c877907c0227f416889972b1:1)
```
LND.log (last 300 lines) : https://pastebin.com/4HR8tFNe 

lncli pendingchannels: https://pastebin.com/Nat1vLUU

btc@vmd27150:~$ lncli channelbalance
{
    "balance": "1719996",
    "pending_open_balance": "128506"
}

```
btc@vmd27150:~/.bitcoin$ cat bitcoin.conf 
server=1
daemon=1
txindex=1
rpcuser=bitcoinrpc
rpcpassword=xxxxXXXxxxxxxxxx
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332
```

Update: Maybe this is related to issue happened here #720 , that my node didnt broadcast fundinx tx, but will wipe of the problem after 48hours.

**Comment by Roasbeef** [comment]
Which commit hash are you running? If you update to the latest master, does the issue still persist? 

> Trying to kill process and restart manually does not solve the problem, but keeps hanging with pending channels, not establishing active channels again.

What do you mean hanging with pending channels? Active channels are established simply when the other peer connects to you again. If you're not connected to the peer, then the channel won't ever be marked as active. 

It seems that none of those funding transactions were confirmed. It may be the case that the remote party just never broadcasted the transactions, or weren't able to get it into the mempool in time. 

One question: why are you trying to repeatedly open such small channels? Before something like AMP is deployed, they won't be of much use at all, and would better serve the network combined into fewer (but larger) channels.

**Comment by Roasbeef** [comment]
If you run w/ profiling on (`--profile=port`), then go to the web interface to fetch the latest goroutine dump as you're shutting down, what does it reveal?

**Comment by rubenkr** [comment]
Thanks for your answer. I am using the latest commit from this github repo. So the issue persist.

Hanging channels I mean the pending channels that are not being opened, nor closed since days now.

I am trying to connect smaller nodes to the overall network. If that does not make sense, I will do make larger channels to more popular nodes.

###Latest goroutine 
https://pastebin.com/wnzPvnCB

**Comment by Roasbeef** [comment]
> Hanging channels I mean the pending channels that are not being opened, nor closed since days now.

As you are the one that created the channels, we don't forget them atm, as they still have funds in the channels themselves. If you look at start up logs with `LNWL=trace` do you see `lnd` trying to retransmit them? 

> I am trying to connect smaller nodes to the overall network. If that does not make sense, I will do make larger channels to more popular nodes.

At this point in the network's deployment, those channels won't be of much use as they're so small.

**Comment by rubenkr** [comment]
Okay thanks. Now I added in the lnd.conf file following entry:

```
; Debug logging level.
; Valid levels are {trace, debug, info, warn, error, critical}
; You may also specify <subsystem>=<level>,<subsystem2>=<level>,... to set
; log level for individual subsystems.  Use btcd --debuglevel=show to list
; available subsystems.
; debuglevel=info
```

Problems persistent and I tried desperately to close the channels - with no luck. There is no funding_transction ID, because it did not happen.  

lncli closechannel $channelid 1, but it is expecting a funding_tx, which I dont know how to find which funding_tx was used.

I also cannot find the transcation with lncli list chanins

`lncli listchaintxns | grep $channelid`

displaying nothing whether I am using remote_node_pub nor channel_point.

Should I simply ignore this and just continue running the node? Not much users are anymore connected to my node (-80%).

**Comment by Roasbeef** [comment]
@rubenkr the issue here is that you're connected to a node that hasn't fully synced the chain: 
> has witness data, but segwit isn't active yet

You need to ensure that the node is fully synced before you connect `lnd`.

**Comment by Roasbeef** [comment]
You use the channel point, not the channel ID when you're closing channels on the command line.

**Comment by Roasbeef** [comment]
Seems like this was resolved?
