### ISSUE TITLE
restoreMemState in htlcswitch crashes lnd on start

### ISSUE THREAD

**Issue by rawtxapp** [lightningnetwork/lnd#1297]
### Background
lnd crashes on startup while trying to restore memory state in htlcswitch.
Before this, I rolled up to master, created a new channel, closed the wallet and attempted to reopen it.

### Your environment
* version of `lnd`
lnd master at commit 31aa8553e70629455bb0d1d1afac0e9167e11f9e
* OS:
Darwin MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
* backend:
neutrino

### Steps to reproduce

Just created a channel to a node, closed the wallet and restarted it again. The wallet was existing long before the update.

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x467a6c9]
goroutine 1 [running]:
github.com/lightningnetwork/lnd/htlcswitch.(*circuitMap).restoreMemState.func1.2(0x749e668, 0x10, 0x10, 0x749e678, 0x10, 0x10, 0x10, 0x0)
    /Users/user/go/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:284 +0x159
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).ForEach(0xc42024a340, 0xc43056ef00, 0x11, 0x11)
    /Users/user/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:388 +0x109
github.com/lightningnetwork/lnd/htlcswitch.(*circuitMap).restoreMemState.func1(0xc420282000, 0x4c239d0, 0xc420282000)
    /Users/user/go/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:267 +0x137
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).View(0xc4200c03c0, 0xc43056f018, 0x0, 0x0)
    /Users/user/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:699 +0x90
github.com/lightningnetwork/lnd/htlcswitch.(*circuitMap).restoreMemState(0xc42054c240, 0x0, 0x0)
    /Users/user/go/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:238 +0xdf
github.com/lightningnetwork/lnd/htlcswitch.NewCircuitMap(0xc4200b3f60, 0xc4200b3f60, 0x49a6a20, 0x0, 0xc42049e800)
    /Users/user/go/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:196 +0x7b
github.com/lightningnetwork/lnd/htlcswitch.New(0xc4306702a0, 0x4cb4c60, 0xc420244060, 0xc4200b3ec0, 0xc42000c0c0, 0x4cb8820, 0x51ba240, 0xc4200b3f00, 0xc420554600, 0x0, ...)
    /Users/user/go/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:236 +0xd9
main.newServer(0xc420328030, 0x1, 0x1, 0xc42000c0c0, 0xc4202f8630, 0xc4306702a0, 0x8, 0x8, 0x0)
    /Users/user/go/src/github.com/lightningnetwork/lnd/server.go:219 +0xa40
main.lndMain(0x0, 0x0)
    /Users/user/go/src/github.com/lightningnetwork/lnd/lnd.go:320 +0xb4d
main.main()
    /Users/user/go/src/github.com/lightningnetwork/lnd/lnd.go:652 +0x26

### Expected behaviour
No crash.

### Actual behaviour
Crashes.

**Comment by cfromknecht** [comment]
I have another patch that removes the offending keystone altogether, though first want to learn a little more about the state of your circuit map

**Comment by rawtxapp** [comment]
It prints
```
2018-05-31 16:32:18.598 [INF] HSWC: Lost keystone=(Chan ID=0:0:0, HTLC ID=4), unable to find circuit for incoming circuit key=(Chan ID=0:0:0, HTLC ID=6)
2018-05-31 16:32:18.598 [INF] HSWC: Lost keystone=(Chan ID=0:0:0, HTLC ID=6), unable to find circuit for incoming circuit key=(Chan ID=0:0:0, HTLC ID=6)
```

**Comment by cfromknecht** [comment]
Prefect, that is what I expected. Bugs surrounding `0:0:0` are possible pre-0.4.2. Here's the diff to remove those:

```
index 0e56d43e..2fc71e95 100644
--- a/htlcswitch/circuit_map.go
+++ b/htlcswitch/circuit_map.go
@@ -264,6 +264,7 @@ func (cm *circuitMap) restoreMemState() error {
                        return ErrCorruptedCircuitMap
                }   
 
+               var lostKeystones []CircuitKey
                if err := keystoneBkt.ForEach(func(k, v []byte) error {
                        var (
                                inKey  CircuitKey
@@ -280,7 +281,14 @@ func (cm *circuitMap) restoreMemState() error {
 
                        // Retrieve the pending circuit, set its keystone, then
                        // add it to the opened map.
-                       circuit := pending[inKey]
+                       circuit, ok := pending[inKey]
+                       if !ok {
+                               log.Debugf("Lost keystone=%v, unable to find circuit "+
+                                       "for incoming circuit key=%v", *outKey, inKey)
+                               lostKeystones = append(lostKeystones, *outKey)
+                               return nil
+                       }
+
                        circuit.Outgoing = outKey
                        opened[*outKey] = circuit
 
@@ -289,6 +297,16 @@ func (cm *circuitMap) restoreMemState() error {
                        return err 
                }   
 
+               // Remove any lost keystones, there is no way we can recover
+               // if we don't know the incoming key.
+               for _, outKey := range lostKeystones {
+                       log.Debugf("Removing lost keystone=%v", outKey)
+                       err := keystoneBkt.Delete(outKey.Bytes())
+                       if err != nil {
+                               return err
+                       }
+               }
+
                return nil 
 
        }); err != nil {
```

**Comment by cfromknecht** [comment]
After restarting with this patch, you should be able to revert to master and start as normal

**Comment by rawtxapp** [comment]
I tried it, but I get
```
2018-05-31 17:07:18.033 [INF] HSWC: Removing keystone (Chan ID=0:0:0, HTLC ID=4)
2018-05-31 17:07:18.033 [ERR] SRVR: unable to create server: tx not writable
```
And then it crashes again. But if it's fixed in the latest version, I'm not too worried about recovering that channel.db, I only had a single testnet channel on it, so it's fine. Thank you!

**Comment by cfromknecht** [comment]
ahh you're right, that is trying to delete inside a read-only txn. thanks for running, this was a helpful confirmation that there isn't a larger issue!
