### ISSUE TITLE
Update NodeAnnouncement address advertisement to match spec

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#131]
Currently, the `lnwire.NodeAnnouncement` uses a recently dated format for communicating the reachable address of a particular node. Atm we assume that they're always encoding an IPv4 or IPv6 address within an IPv6 address. However, this is rather restricts as it means we can't signal hidden service addresses (both the current and next-gen version), or i2p address etc. [A recent modification to the spec allows for a much more flexible format, which can be adapted to any new address types we'd like to advertise in the future](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-node_announcement-message). 

Additionally, the database (`channeldb.LightnignNode`) should be updated to also store a variable number of address for a particular ndoe. 

## Steps To Completion 

- [ ] Modify the `Address` field within the `lnwire.NodeAnnouncement` struct to instead be a more flexible `[]net.Addr`

- [ ] Modify the encoding/decoding routine for `lnwire.NodeAnnouncement` to use the format defined within the specification. Rather than packing in a single IPv6 address, it should now pack in an integer signaling the _number_ of addresses, then induvidual pack in each known address with a byte prefix denoting the proper type. 

- [ ] Modify the encoding/decoding routines for `channeldb.LightningNode` to also accept and update a variable amount of reachable addresses. 

# Follow Up Tasks

Once the above has been completed, then the logic around the `connmgr` should also be updated to attempt to connect out to all advertised addresses. In the event that we're able to connect out or revive a connection from one of the advertise addresses, then _all_ the gorourtines launched by the `connmgr` to connect out to the directed node should be cancelled. This will require a modification to the `connmgr` package within `btcd` to allow the cancellation of a connection attempt that didn't succeed. Currently one is only able to cancel a persistent connection attempt iff one was successful in the past.

**Comment by bryanvu** [comment]
Will take this one.

**Comment by Roasbeef** [comment]
Closed by #154.
