### ISSUE TITLE
lnd crashing consistently in ~12-24 hrs, with no error output

### ISSUE THREAD

**Issue by janoside** [lightningnetwork/lnd#1314]
### Background

I'm running `lnd` on an Ubuntu server and consistently seeing silent crashes. My installation was performed using the Linux instructions [here](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) and I opted for the `go` installation option (rather than `make`). I then run `lnd` with the command: `lnd > ~/.lnd/logs/startup.log &`. The last ~15 min of log output (level=`info`) before crashing can be seen [here](https://pastebin.com/rHPw56un).

### Your environment

* lnd commit `7cf5ebe2650`
* lnd is configured with [this lnd.conf](https://pastebin.com/PiHCALSZ), stored in the default location, "~/.lnd/lnd.conf"
* Ubuntu `16.04.4` (Linux `4.4.0-124`)
* bitcoind `0.16.0`
* Server: 16gb memory, plenty of free disk space
* lnd has no channels
* I'm querying lnd via gRPC regularly (pulling full network description every ~60 sec)

### Steps to reproduce

Configure with `lnd.conf` as shown above, then launch with command above. Wait ~12-24 hours and lnd silently crashes.

### Expected behaviour

lnd continues to run or crashes with error output indicating why.

### Actual behaviour

lnd crashes consistently in less than 24 hours with no obvious error output.

**Comment by Roasbeef** [comment]
You'll need to capture stderr if you aren't already, if you're hitting a panic, then it won't show within the logs or stdout.

**Comment by janoside** [comment]
Thanks. Configured to capture stderr now. Will update when I have more info.

**Comment by janoside** [comment]
Now running with `lnd > ~/.lnd/logs/lnd-out.log 2> ~/.lnd/logs/lnd-err.log &` - still seeing no output in `lnd-err.log` when lnd crashes.

**Comment by halseth** [comment]
also up your loglevel to `debug`

**Comment by kulpreet** [comment]
I get the same silent crash. Will run as suggested above and report.

Also, I don't know if this is related, but would be nice to have a -daemon option :) I don't know how desirable a feature that might be.

**Comment by maurycy** [comment]
Could you check the syslog? Maybe it is the OOM.

**Comment by maurycy** [comment]
Could you check the syslog? Maybe it is the OOM killer.

>

**Comment by janoside** [comment]
Don't see anything in syslog. Still not seeing any output to stderr (assuming my command above to capture it is correct...please let me know if it's not). I will increase log level to debug and start it up again.

**Comment by Roasbeef** [comment]
@kulpreet it's the job of the user to handle things like this. 

@janoside try running w/o any sort of init system or hypervisor. Just the plain `lnd` binary, if you just leave it, then the crash (as you report) will eventually happend, and we'll be able to extract the information from `stdout`.

**Comment by janoside** [comment]
@roasbeef I'm happy to run any way. I believe I'm running the lnd binary directly, but the limits of my knowledge on the matter are showing. I've included the actual commands I'm running. I'll include again below. Is the below command what you recommend (running lnd binary directly and capturing stderr)?

lnd > ~/.lnd/lnd-out.log 2> ~/.lnd/lnd-err.log &

**Comment by Roasbeef** [comment]
Just run lnd in the foreground, without any redirection

**Comment by Roasbeef** [comment]
It's been 24 hrs, it is still up? 😝
