### ISSUE TITLE
Autopilot doesn't start in docker container

### ISSUE THREAD

**Issue by neogeno** [lightningnetwork/lnd#1329]
I am running the latest version of lnd in a docker container with the --autopilot.active command line argument but even after funding the on-chain wallet the auto pilot never starts and there is no mention in the log file of any start of Autopilot sequence  

### Your environment

* version of `lnd`  lnd version 0.4.2-beta commit=d98d4523e10426c4ce097ecc7ec1ba199a331c60
* which operating system (`uname -a` on *Nix) alpine linux - from docker hub
* version of `btcd`, `bitcoind`, or other backend  btcd v0.12-beta
* any other relevant environment details

Base OS Image LND is running on : https://hub.docker.com/_/alpine/ latest version 3.7
Source binary: built from source using golang:1.10-alpine docker image

### Steps to reproduce

1. Launch docker container from golang:1.10-alpine 
2. Build LND from source
3. copy lnd to new container built from alpine:latest
4. Launch LND from alpine linux container with --autopilot.active argument

### Expected behaviour

1. LND should start opening channels to appropriate peers as soon as the wallet is funded.

2. Should find record in log file along the lines of:
[INF] ATPL: Instantiating autopilot with cfg: xxx

3. Autopilot should open channels automatically as soon as possible 

### Actual behaviour

The Node seems to function normally, and can open channels manually but no automatic opening is being performed even after running the node for days.

**Comment by halseth** [comment]
Can you provide some logs from startup with `debuglevel=debug`? :)

**Comment by neogeno** [comment]
I tried it with Debug flag set but there is no error message whatsoever. Simply missing any log entries for ATPL: ....
