### ISSUE TITLE
Set minimum fee to 253 sat/kw

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#1330]
As discussed in https://github.com/ElementsProject/lightning/issues/1443 and https://github.com/ElementsProject/lightning/issues/1529 and https://www.mail-archive.com/lightning-dev@lists.linuxfoundation.org/msg00560.html there are issues if lnd suggests a fee of 250 if other clients require a higher fee, for example 253 as this is the technical minimum as determined by clightning.

To avoid incompabilities and a separated network I suggest to hard-code the minimum fee to 253 sat/kw, compatible to clightning.

**Comment by Roasbeef** [comment]
What's a ksipa?

**Comment by C-Otto** [comment]
A kilo sipa, where sipa is Pieter Wuille. I guess it's related to the SegWit size computation, but sadly I don't know the details. I copied the unit and I'm perfectly fine to replace it with something well known :)

**Comment by Roasbeef** [comment]
There's no such thing as a ksipa, there're no implementations that reference such a unit. There's only weight and vsize.

**Comment by C-Otto** [comment]
Could you edit the title accordingly?

**Comment by Roasbeef** [comment]
Adding the fee floor for now, but just want it to be clear that it's only a temporary patch. Nodes can raise the min fee rate at any time based on the size of their mempool.

**Comment by n1bor** [comment]
Do not think that nodes raising min relay fee rate when mempool is full will be a real issue. As other than the 253 floor the 2/6 block fee estimates will always be well above the min relay rate.
Issue only happens at the lower extreme.
