### ISSUE TITLE
Cannot BootStrap new nodes with BOLT-0010 DNS Seed

### ISSUE THREAD

**Issue by neogeno** [lightningnetwork/lnd#1334]
### Background

After LND syncs with the btcd backend it tries to connect to nodes but fails repeatedly. The Log shows:
```
[INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]
```

over and over again.

### Your environment

* version of `lnd` lnd version 0.4.2-beta commit=d98d4523e10426c4ce097ecc7ec1ba199a331c60
* which operating system (`uname -a` on *Nix) Linux
* version of `btcd`, `bitcoind`, or other backend btc 0.12
* any other relevant environment details

- running in a docker container, the containers used to work fine until now. Starting from today, when I  tried to launch a new node I get this problem.
- switching DNS to 8.8.8.8 has no effect.

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Start a new lnd node in a docker container.

### Expected behaviour

Should connect to peers automatically

### Actual behaviour

LND repeatedly queries the bootstrap nodes to no avail. 

Log File Error:

```
[ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]: lookup soa.nodes.lightning.directory on 10.0.0.2:53: read udp 10.0.1.179:41329->10.0.0.2:53: i/o timeout

[ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]: lookup soa.nodes.lightning.directory on 10.0.0.2:53: server misbehaving
```

**Comment by Roasbeef** [comment]
Was doing development on the seed and forgot the restart the main instances, has now been fixed.

**Comment by tsmith123** [comment]
@Roasbeef Don't suppose you've forgotten to restart the instances again have you? I'm getting exactly the same issues.
