### ISSUE TITLE
same issue of #1289 after delete macaroons set to solve #987 / #921

### ISSUE THREAD

**Issue by Fr4nZ82** [lightningnetwork/lnd#1336]
i have same issue of #1289 after delete macaroons set to solve #987 / #921 
# Background
i'm on mainnet.
lnd crash if command lncli addinvoice sent after some time from start; if same command is sent before that time a payreq is created and lnd continue to work.

### Your environment
* version of `lnd`    0.4.2-beta commit=a1ad3a5011019ffbd746b882f1c72ce55f96a798
* which operating system  4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
* version of `btcd`     BTCD: Version 0.12.0-beta
* any other relevant environment details - i have 2 channels in pending force close since 2 month ago, one of them cause the #975 issue

### Steps to reproduce

If debuglevel is set to debug or info "Lncli addinvoice" crashes lnd but not always. It seems that it happens only after a certain amount of time (1 minute).
if debuglevel is set to trace "Lncli addinvoice" correctly generate payreq but getinfo wont work.
Note that i try this (to change debug level and do addinvoice test) only 2 time

### Actual behaviour
every time lnd crash, this is the last row in the log (with the same channel), other rows are normal work of DBG
2018-06-06 20:50:37.093 [ERR] RPCS: Unable to get link for channel 644fc6295f357451486b7ee7297330576eaf171f5987313106ba62cc28df2561: channel link not found

**Comment by Roasbeef** [comment]
This was fixed in commit `4d37508417153c1263ee22acbd5614c37e927c3c`.
