### ISSUE TITLE
The daemon should reject any channel state-transitions if not fully-synced to the chain

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#134]
Currently within the daemon, we disallow accepting or creation channels if the daemon is not fully synced. The rationale behind this is that, we're unable to properly fully verify the channel creation process if we aren't synced to the chain, as we won't be able to tell when the funding transaction has been confirmed. Also in the case of a dual-funder channel, if we don't have the latest UTXO state, then we won't be able properly validate if an input included by the remote peer is actually unspent or not. 

This constraint should also be extended to _reject_ any update requests by a remote peer to update a channel before we're fully synced to the chain. This is critical for safety, as a peer might've closed out a channel, but we haven't yet recognized it because we're still only aware of the historical portion of the chain. 

An alternative approach is to, within the `readHandler` of a peer, if the message is a channel update message (add, settle, cancel, revoke, sig) message, then check to see if we're still performing an initial sync after a reboot. This check should be implemented as a atomic boolean the `server` struct that indicates if we're still performing our initial sync on boot. This should be used rather than the `lnwallet.WalletController.IsSynced` method as it allows us to avoid a costly database hit on _each_ channel update message.

**Comment by johng** [comment]
Looks like this has been done? The server doesn't start till the chain is fully synced
