### ISSUE TITLE
Force closing channel looking for txid different than one actually mined. Funds in limbo.

### ISSUE THREAD

**Issue by duck1123** [lightningnetwork/lnd#1341]
### Background

I was using autopilot to open a new channel, but my node was shut down before the transaction was mined. When I was syncing up my node a few hours later, starting LND while bitcoind was scanning the 6 previous blocks, I received an error about the block height being less than previous and LND crashed.

I restarted LND, and everything synced back up and the channel was shown as opened. I tried to pay an invoice, but the payment never completed. That was when I noticed that the channel was being forced closed. I never saw an actual error message about that payment.

The closing_txid does not match the actual closing transaction on chain and as such, LND is unable to detect that the close has finished.

Opening transaction: https://www.smartbit.com.au/tx/0932213005e5023d5acc5a66ef40be7e4fbf08b52b88c55598643036288e3380

lncli pendingchannels | jq ".pending_force_closing_channels[0]"                                                                                  

```json
{
  "channel": {
    "remote_node_pub": "024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed",
    "channel_point": "0932213005e5023d5acc5a66ef40be7e4fbf08b52b88c55598643036288e3380:1",
    "capacity": "1600000",
    "local_balance": "1599819",
    "remote_balance": "0"
  },
  "closing_txid": "3428ff4021fb0e75233506442d1f19d416a7eb06c8e1d38bd6a47b00618c90c2",
  "limbo_balance": "1599819",
  "maturity_height": 0,
  "blocks_til_maturity": 0,
  "recovered_balance": "0",
  "pending_htlcs": []
}
```

Actual closing transaction: https://www.smartbit.com.au/tx/65e0596a71c671136a62b9530231ed84ec3bef4a02aac6349ec3448e237262e3

Additional details can be found in the slack thread: https://lightningcommunity.slack.com/archives/C6BKD3RKR/p1528316418000738

A copy of logs collected with an additional log line dumping resolver information can be found at: https://duck1123.keybase.pub/lnd-patched.log.gz

Unfortunately, all logs from the time this error occurred have already been rotated out. 

### Your environment

* LND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
  * Compiled from source: go version go1.10 linux/amd64
* Linux cybertronix 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

### Steps to reproduce

Begin to open channel but shut down node before funding transaction can confirm. After transaction confirms, have remote party force close the channel.

Start bitcoind, and while it is rewinding the last 6 blocks start lnd and after it crashes, start it again.

### Expected behaviour

Channel should be closed once closing transaction is complete. Locked funds should be returned to wallet.

### Actual behaviour

Channel still listed under "pending_force_closing_channels" despite closing transaction having 370+ confirmations. Funds in limbo.

**Comment by duck1123** [comment]
So my naive thought was, if the problem is that it has the wrong txid and the real txid is presumably good and ready to go, would it be possible to just write a small bit of code to just force an update to that field in LND's database?

As for what caused it, I've got nothing.

**Comment by duck1123** [comment]
I'm not sure if this is relevant or not. Before starting this wallet, I was testing going back and forth between creating wallets with and without encryption. While I generally deleted all the files in ~/.lnd (save for the conf file) between each wallet generation, there was at least one time where I only deleted the wallet.dat file. I'm pretty sure, but not 100%, that I started from a completely fresh slate when I finally created this wallet, but there is the chance that it may have partially tried to update with a different wallet.

In any case, none of the previous wallets had any transactions. Also, I have been able to successfully open and close channels as well as make payments aside from operations regarding this channel.

**Comment by Roasbeef** [comment]
> there was at least one time where I only deleted the wallet.dat file

`lnd` doesn't use a `wallet.dat` file. 

>  would it be possible to just write a small bit of code to just force an update to that field in LND's database?

Depending on if you were on `0.4.1` when this happend, that should be possible. If you look at your old logs, do you see any warnings about a re-org happening?

**Comment by duck1123** [comment]
> lnd doesn't use a wallet.dat file.

I meant to say `wallet.db`, sorry.

I have been on 0.4.2-beta for the entire life of this wallet.

The logs from when the problem originally occurred have since been rotated off, so I'm unable to search for re-org events.

**Comment by halseth** [comment]
This could previously happen when we were acting on mempool spends, but as of v0.4.2 we shouldn't. I am wondering if this could be the a result of your `bitcoind` actually notifying on mempool spends, which might cause this to happen. Our test instance doesn't, but maybe that's a configuration option. Will look into!

**Comment by duck1123** [comment]
My bitcoind is the standard one from the Ubuntu repository. There is nothing special in my bitcoin.conf

```
testnet=0
server=1
rpcuser=REDACTED
rpcpassword=REDACTED
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=p2sh-segwit
```

**Comment by halseth** [comment]
Yep, I was able to reproduce on our test instance. We weren't waiting long enough in the test for the mempool spend to arrive, I have a PR that fixes this issue up :)

**Comment by duck1123** [comment]
This PR wouldn't release my funds though, would it? Or will it just save anyone else from going through this?

**Comment by halseth** [comment]
Nah, it wouldn't unfortunately :/ 

Should be possible to create a small patch that just changes the db record maybe..
