### ISSUE TITLE
Remote uncooperative close when trying to send a first HTLC

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#1342]
### Background

When connected to remote https://1ml.com/node/03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258 peer using BLW the very first payment attempt directly to that node results in a remote uncooperative closing.

Messages sent from BLW:

> --> UpdateAddHtlc(0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470,0,100000,18ec2624601f2cf15b25a0600bb092e94e9b514954a151263a658c6dcbf08242,526571,000237d723d2bd755d0c63e8ee94d5dde32a280e08085653d5945a56f7f36a69c86dca9460c154f20428e60f41bb6b3d2c2173c62e216c333f47c5342345734d5b9e4f1de45f4f22901df86fe5e88191c70a44bc5f919651309d1b26e4b9b77b93d2e39e81a200c01afb60534a381d204275f4b0a3f1dae1c938d575b684449726acedc440c0227f01c0c38a09c1a269a28b6e4005b078893dfc96ca24e954da3ce582e5c8d5d6101b987cae620fe52be8e93ad0e84018a4f3e2df15eddea786302b5ac1de35eae97409061c43a8413ebe5f676d8c503d738847107c7c0370028d2368a5e4aeea0bef7e240752ba71eabe37d5dd132dd6ecdfe150b96d619f5a40bb886ef72d0864ce8ed0e32984b6f9023c44b089c7dc2b7fc5153043419ca45b7e27284a0795989e3a6ab9d882c92c9cdf62be9947417b703cec134e70caecdac5d51976b017d280959cbc8324209dad6067b1249bc145102d155e810308127530b7a7127e5962044ba69bfb505002c6d35cb5c36a36d48093bfc15d39a7c70de2bf1a8fde65fc8da2f6c5c574759dab1f26161d15c9cc0afa10d3a1dd4cbfc926add70084eb675c325b9725b4b5af838265ead80c6ab40e6b0dee95772f622bb9ca4ba2b17ae1c47d5d3f04d5a604e5caee01f0c5567c52955e4ccf4649452e5fa494931f0e5dfe8e7cd04496e2a8d18a37580d3d6d618f56b753b4ac7b4bf1d035bd913c0dd64dff8bb78e23397a11af8291a82c9d1aa225ba490f778968d12585e42978a4838ed456474ec8b5a8231b674ec4a4123a9cd758b41fb3128e158ea583fc2b3480c5dddff0cbe1e7c2669e056c8daab1ee62f8b9942e92504f0b8810d0dcefcd178af7d14d0652b199fcce5edb09c9fc1ef34d5dc768caa101d32ea0b30273c8c4c04710a2f4e67faca83925fe3d051a5c4610801eeab3e55f75d1167a9678aea3c1b5325a53570ef93d24674107c111e7a50e751a450aee6cad892536d6e09cc242971aaef3e15ec650ce426300b4cd84d08455799ceb876494977779a9895d82725129af30cf7aeb889220e0c66efa61d1fcfc720c47147c564241ee1bf00c54f6c1a89b024d17299024ef0b0d78bf5010c3ba5a51a3c8b81ea2f427e500332f293f5faafa968e5c3778a83b427d9632f634ccc7e768e9ed6daa9189f55972dac3136e4b3b9d4fe1ec9fde6e64a744d98ff3e771e7697efea96991795f81682c23f9411776b272f349344e7054edb61815f30615198d0fbdbf56687690c580758dfe3de27bd08900a0b83021519934cb710170d44138a69d4dd50150e7bc990acef8e3748202c2e62be038589170f422a3b9b00e2fc50edfec075c3aec79255fb048d7499ee2cfe1b816478c01c65a6f63093dc07963f465be1313e016d76d3391f888967e57df3b1ed373c90c92ad79fb8349724e546abaf18a79583e44a19421fc6ea07690485f3409b6e49a05eba64db7bbec0da9ac00587027b1fae5c75a753af7e78e44503f71be6e363c86e89c835c5b6b7dfbbcb77e3913f4ec00c6543ffa77812da163c69153d507f78362012c603eab6c3e513d5ff25137541cef00b8454078ebc24784d366986986337efde3218a46e998e183893ba09ae9ca90f4f2a8ae80bdcfb802bd97343bfceda9942b31cb11f818411e960da3888fdb867b252211a25c8f76b8aebf35ab9908e692a54093cf22406f392dd5515d27f44890dcec0d77070368e386a6ca9cd1f730b6dc27d177ceef5ad29a2610715ebab6910ddecc15bcb2cbe9a67ff5898bb509183d2ad464dd0c441d28b44d0a07c02e1f3e503a628187e64cdd57b0c29f00311f63f57a77acfe4ee870eca8eefab1e4a21d8e692ed52a5ecee1929fc9d629fe9bd6e1b9c669c3cc08a531e851ed1ecfbc056d3c24170eb55637b70702009e)
> 
> --> CommitSig(0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470,304402202259c4d0500d129c8efbb16daf9aba48a292365fd48d8672a7470d1140bbae8502205fdd2b4fff1e1311f61b491e4f8fb81f783e92f640481f9c791e5342e895710601,List())

Remote peer LND log: http://paste.ubuntu.com/p/BD3kFqvxqh/
Full local BLW channel state: https://paste.ubuntu.com/p/Gn9CMWxhhy/

### Your environment

lnd version 0.4.2-beta commit=4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae

### Steps to reproduce

Open a channel with https://1ml.com/node/03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258, try to send a payment.

### Expected behaviour

No remote uncooperative closing.

### Actual behaviour

Remote uncooperative closing.

**Comment by Roasbeef** [comment]
Do you know that this is actually an `lnd` node? Or this is you using `lnd` to connect to that other node? 

```
2018-06-07 13:41:53.020 [ERR] HSWC: ChannelLink(0:0:0) Failing link: ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0): unable to accept new commitment: rejected commitment: commit_height=1, invalid_commit_sig=304402202259c4d0500d129c8efbb16daf9aba48a292365fd48d8672a7470d1140bbae8502205fdd2b4fff1e1311f61b491e4f8fb81f783e92f640481f9c791e5342e8957106, commit_tx=02000000010155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b647000000000000bb94d80014be31200000000001600149c22f5e199819b6ea09e58dad8b66734823f68c2cddddc20, sig_hash=0989b651a9a6eba9c444fd31e79a3323afa072ed424aee144685b737c810efc4
2018-06-07 13:41:53.022 [ERR] HSWC: ChannelLink(0:0:0) link failed, exiting htlcManager
```

The zero's there where the chan ID _should_ be would indicate that for w/e reason, this channel wasn't yet fully locked in.

**Comment by Roasbeef** [comment]
It looks like we never even got that HTLC add, can you try this with `PEER=debug` for logging? 

The transaction _we_ reconstruct is: 
```
(*wire.MsgTx)(0xc42008c100)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc420094240)({
   PreviousOutPoint: (wire.OutPoint) 70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) <nil>,
   Sequence: (uint32) 2152577291
  })
 },
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0xc420080240)({
   Value: (int64) 1237835,
   PkScript: ([]uint8) (len=22 cap=22) {
    00000000  00 14 9c 22 f5 e1 99 81  9b 6e a0 9e 58 da d8 b6  |...".....n..X...|
    00000010  67 34 82 3f 68 c2                                 |g4.?h.|
   }
  })
 },
 LockTime: (uint32) 551345613
})
```

The tx that we broadcasted is
```
2018-06-07 13:41:53.238 [INF] CNCT: Broadcasting force close transaction, ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0): (*wire.MsgTx)(0xc4201aa2c0)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc42239e840)({
   PreviousOutPoint: (wire.OutPoint) 70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) <nil>,
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 70 79 5a 82  90 e0 d0 4f 83 05 20 2d  |0D. pyZ....O.. -|
     00000010  de ff de 71 d9 6a 9f 70  09 6d 20 e2 d0 24 e7 62  |...q.j.p.m ..$.b|
     00000020  9d 13 f2 4c 02 20 1f 7b  34 76 86 ac bc 91 7a 46  |...L. .{4v....zF|
     00000030  e3 b9 45 ba 3b 0e 17 71  97 e8 b8 9c d7 ee d3 35  |..E.;..q.......5|
     00000040  50 48 61 98 c4 92 01                              |PHa....|
    },
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 02 58 e9 37  25 8d 01 1f 63 19 8c 9b  |0D. .X.7%...c...|
     00000010  2e cf f9 ed 42 43 03 77  c4 f6 26 c8 75 61 c4 ab  |....BC.w..&.ua..|
     00000020  71 99 42 21 02 20 1f ad  5f a3 d4 42 c9 10 25 e0  |q.B!. .._..B..%.|
     00000030  b3 f9 30 58 9e 5f 1a 57  07 79 02 6b a6 92 65 c2  |..0X._.W.y.k..e.|
     00000040  8b c5 f9 71 c6 67 01                              |...q.g.|
    },
    ([]uint8) (len=71 cap=500) {
     00000000  52 21 03 45 11 e6 12 46  19 3a 7a 60 03 6a 18 cb  |R!.E...F.:z`.j..|
     00000010  cc 09 36 65 ef 87 5f 14  f0 05 d3 fb 22 6e 7f 21  |..6e.._....."n.!|
     00000020  5f 13 7a 21 03 bb 06 69  6d 64 90 e7 65 83 3e ac  |_.z!...imd..e.>.|
     00000030  22 46 9d 2d 21 6d 6d 1c  86 2e 10 86 9f dc 81 e3  |"F.-!mm.........|
     00000040  03 cf 14 a6 28 52 ae                              |....(R.|
    }
   },
   Sequence: (uint32) 2152577291
  })
 },
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0xc421f8abc0)({
   Value: (int64) 1237835,
   PkScript: ([]uint8) (len=22 cap=22) {
    00000000  00 14 53 51 7b 6a 94 6e  ba ee 18 05 5c c8 fd f4  |..SQ{j.n....\...|
    00000010  fc 44 1d 09 d7 ff                                 |.D....|
   }
  })
 },
 LockTime: (uint32) 551345612
})
```

**Comment by Roasbeef** [comment]
While y'all think our commitment is: 
```
(*wire.MsgTx)(0xc420058140)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc42005c2a0)({
   PreviousOutPoint: (wire.OutPoint) b970703501bb0dc2f9e8cd324310df1c3a30ca6efed0192882acc6569c92cf41:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=72) {
     00000000  30 45 02 21 00 83 b4 0c  70 dc 92 3d 77 fb 4a 94  |0E.!....p..=w.J.|
     00000010  97 08 bb 1b 2d 00 92 87  3f 61 e4 fd c0 c8 d1 b1  |....-...?a......|
     00000020  15 04 39 b6 6f 02 20 58  06 00 f7 a2 3d ca 66 bf  |..9.o. X....=.f.|
     00000030  14 29 2a 15 bc 23 af 30  11 2a 31 11 bd b5 ba fe  |.)*..#.0.*1.....|
     00000040  61 07 b5 8b 1b 46 31 01                           |a....F1.|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  03 4a a9 4e 34 14 a3 36  74 73 01 f8 52 84 d0 b6  |.J.N4..6ts..R...|
     00000010  c3 17 33 4f 56 55 f2 80  91 e2 a0 6c a2 76 c2 88  |..3OVU.....l.v..|
     00000020  a6                                                |.|
    }
   },
   Sequence: (uint32) 0
  })
 },
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0xc42000c2a0)({
   Value: (int64) 1237289,
   PkScript: ([]uint8) (len=22 cap=22) {
    00000000  00 14 47 b8 6c 14 a5 f2  24 02 a9 d7 23 f5 0b f8  |..G.l...$...#...|
    00000010  06 6f ca f9 f6 c8                                 |.o....|
   }
  })
 },
 LockTime: (uint32) 0
})
```

Which looks very wrong, as the outpoints are totally different...

**Comment by Roasbeef** [comment]
I think this might be an eclair issue after all? It has the wrong outpoint for the remote commitment, but the correct for the local commitment.

**Comment by btcontract** [comment]
> Do you know that this is actually an lnd node? Or this is you using lnd to connect to that other node?

03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258 belongs to @robtex, we were coordinating in slack while all this was happening.

> The zero's there where the chan ID should be would indicate that for w/e reason, this channel wasn't yet fully locked in.

Both of us have seen channel as locked in and being in `NORMAL` state. Here's a piece @robtex has provided right after a channel got opened and before I've sent a first HTLC, I was restarting an app locally to see if channel gets broken on reestablishment:

```
2018-06-07 13:38:38.044 [INF] SRVR: New inbound connection from 92.113.43.165:37022

2018-06-07 13:38:38.045 [ERR] SRVR: Unable to retrieve advertised address for node 030858ba60e8ac2a4a9e21a247153894b15171d6ec9e06592b73c1018f93c39abd: no advertised addresses found

2018-06-07 13:38:38.228 [INF] PEER: NodeKey(030858ba60e8ac2a4a9e21a247153894b15171d6ec9e06592b73c1018f93c39abd) loading ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0)

2018-06-07 13:38:38.232 [INF] NTFN: New block epoch subscription

2018-06-07 13:38:38.240 [INF] HSWC: ChannelLink(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0) is starting

2018-06-07 13:38:38.240 [INF] HSWC: Trimming open circuits for chan_id=526425:2021:0, start_htlc_id=0

2018-06-07 13:38:38.240 [INF] HSWC: Adding live link chan_id=0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470, short_chan_id=526425:2021:0

2018-06-07 13:38:38.240 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0)

2018-06-07 13:38:38.240 [INF] HSWC: HTLC manager for ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0) started, bandwidth=0 mSAT

2018-06-07 13:38:38.240 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0)

2018-06-07 13:38:38.394 [INF] HSWC: ChannelPoint(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0): resending FundingLocked message to peer

2018-06-07 13:38:38.395 [INF] HSWC: Received re-establishment message from remote side for channel(70649bc78643c6ea589e2832118904f22126feb5ce30aeb9b86241e975be5501:0)

2018-06-07 13:38:38.709 [INF] FNDG: Received duplicate fundingLocked for ChannelID(0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470), ignoring.

2018-06-07 13:38:42.908 [INF] DISC: Broadcasting batch of 10 new announcements

2018-06-07 13:39:12.908 [INF] DISC: Broadcasting batch of 8 new announcements
```

> It looks like we never even got that HTLC add, can you try this with PEER=debug for logging

Sure, will do.

> While y'all think our commitment is ...

That's not a commitment tx, that is a `claimMainTx` in Eclair/BLW terminology, the one which spends my main P2PKH output from a commit tx. Indeed it's called `remoteCommit` in provided Json file and that's a terrible naming choice of mine.

Info about remote commit from BLW point of view can be seen in this block:

```
"remoteNextCommitInfo":{
         "nextRemoteCommit":{
            "index":1,
            "spec":{
               "htlcs":[
                  {
                     "incoming":true,
                     "add":"0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470000000000000000000000000000186a018ec2624601f2cf15b25a0600bb092e94e9b514954a151263a658c6dcbf08242000808eb000237d723d2bd755d0c63e8ee94d5dde32a280e08085653d5945a56f7f36a69c86dca9460c154f20428e60f41bb6b3d2c2173c62e216c333f47c5342345734d5b9e4f1de45f4f22901df86fe5e88191c70a44bc5f919651309d1b26e4b9b77b93d2e39e81a200c01afb60534a381d204275f4b0a3f1dae1c938d575b684449726acedc440c0227f01c0c38a09c1a269a28b6e4005b078893dfc96ca24e954da3ce582e5c8d5d6101b987cae620fe52be8e93ad0e84018a4f3e2df15eddea786302b5ac1de35eae97409061c43a8413ebe5f676d8c503d738847107c7c0370028d2368a5e4aeea0bef7e240752ba71eabe37d5dd132dd6ecdfe150b96d619f5a40bb886ef72d0864ce8ed0e32984b6f9023c44b089c7dc2b7fc5153043419ca45b7e27284a0795989e3a6ab9d882c92c9cdf62be9947417b703cec134e70caecdac5d51976b017d280959cbc8324209dad6067b1249bc145102d155e810308127530b7a7127e5962044ba69bfb505002c6d35cb5c36a36d48093bfc15d39a7c70de2bf1a8fde65fc8da2f6c5c574759dab1f26161d15c9cc0afa10d3a1dd4cbfc926add70084eb675c325b9725b4b5af838265ead80c6ab40e6b0dee95772f622bb9ca4ba2b17ae1c47d5d3f04d5a604e5caee01f0c5567c52955e4ccf4649452e5fa494931f0e5dfe8e7cd04496e2a8d18a37580d3d6d618f56b753b4ac7b4bf1d035bd913c0dd64dff8bb78e23397a11af8291a82c9d1aa225ba490f778968d12585e42978a4838ed456474ec8b5a8231b674ec4a4123a9cd758b41fb3128e158ea583fc2b3480c5dddff0cbe1e7c2669e056c8daab1ee62f8b9942e92504f0b8810d0dcefcd178af7d14d0652b199fcce5edb09c9fc1ef34d5dc768caa101d32ea0b30273c8c4c04710a2f4e67faca83925fe3d051a5c4610801eeab3e55f75d1167a9678aea3c1b5325a53570ef93d24674107c111e7a50e751a450aee6cad892536d6e09cc242971aaef3e15ec650ce426300b4cd84d08455799ceb876494977779a9895d82725129af30cf7aeb889220e0c66efa61d1fcfc720c47147c564241ee1bf00c54f6c1a89b024d17299024ef0b0d78bf5010c3ba5a51a3c8b81ea2f427e500332f293f5faafa968e5c3778a83b427d9632f634ccc7e768e9ed6daa9189f55972dac3136e4b3b9d4fe1ec9fde6e64a744d98ff3e771e7697efea96991795f81682c23f9411776b272f349344e7054edb61815f30615198d0fbdbf56687690c580758dfe3de27bd08900a0b83021519934cb710170d44138a69d4dd50150e7bc990acef8e3748202c2e62be038589170f422a3b9b00e2fc50edfec075c3aec79255fb048d7499ee2cfe1b816478c01c65a6f63093dc07963f465be1313e016d76d3391f888967e57df3b1ed373c90c92ad79fb8349724e546abaf18a79583e44a19421fc6ea07690485f3409b6e49a05eba64db7bbec0da9ac00587027b1fae5c75a753af7e78e44503f71be6e363c86e89c835c5b6b7dfbbcb77e3913f4ec00c6543ffa77812da163c69153d507f78362012c603eab6c3e513d5ff25137541cef00b8454078ebc24784d366986986337efde3218a46e998e183893ba09ae9ca90f4f2a8ae80bdcfb802bd97343bfceda9942b31cb11f818411e960da3888fdb867b252211a25c8f76b8aebf35ab9908e692a54093cf22406f392dd5515d27f44890dcec0d77070368e386a6ca9cd1f730b6dc27d177ceef5ad29a2610715ebab6910ddecc15bcb2cbe9a67ff5898bb509183d2ad464dd0c441d28b44d0a07c02e1f3e503a628187e64cdd57b0c29f00311f63f57a77acfe4ee870eca8eefab1e4a21d8e692ed52a5ecee1929fc9d629fe9bd6e1b9c669c3cc08a531e851ed1ecfbc056d3c24170eb55637b70702009e"
                  }
               ],
               "toLocalMsat":0,
               "malformed":[

               ],
               "failed":[

               ],
               "feeratePerKw":1927,
               "toRemoteMsat":1239130000,
               "fulfilled":[

               ]
            },
            "txid":"a0b4387dea8ad28c6310a9376f9545a87e85d99e721311b114a6a5936c259f58",
            "remotePerCommitmentPoint":"03570e2b4bb9ded8bfc7958d6692aa9047062888895bc946dd088c5c334cb84383"
         },
         "sent":"0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b64702259c4d0500d129c8efbb16daf9aba48a292365fd48d8672a7470d1140bbae855fdd2b4fff1e1311f61b491e4f8fb81f783e92f640481f9c791e5342e89571060000",
         "localCommitIndexSnapshot":0
      }
```

Next remote commit txid is `a0b4387dea8ad28c6310a9376f9545a87e85d99e721311b114a6a5936c259f58`

**Comment by btcontract** [comment]
Another point to add, my implementation is not _exactly_ Eclair: low level crypto code is mostly copied but everything above is done quite differently, although inspired by how Eclair does stuff. So BLW bugs and behavior may not be present in Eclair.

**Comment by btcontract** [comment]
Meanwhile I've reconstructed a remote commit tx itself as seen by BLW: `02000000010155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b647000000000000bb94d8001e7e21200000000001600149c22f5e199819b6ea09e58dad8b66734823f68c2cddddc20`, it's txid is `a0b4387dea8ad28c6310a9376f9545a87e85d99e721311b114a6a5936c259f58`

**Comment by btcontract** [comment]
@robtex just had another BLW/LND channel closed on reestablishment, here's log: http://paste.ubuntu.com/p/nvdJyWqyNB/

There was a `UpdateFee` followed by `CommitSig` which LND thinks is not valid.

```
2018-06-08 08:45:35.352 [ERR] HSWC: ChannelLink(0:0:0) Failing link: ChannelPoint(d904d734b3f47b1acb1348263bf8fbd7faf3b6f3b8330f1f04ca9bcdcf56fc5b:1): unable to accept new commitment: rejected commitment: commit_height=1, invalid_commit_sig=304502210083066ec7196308545d0f25bf23108d33a3cd3c9d167eee6917735f11b62d2b4f022049cf41278d332cd2fc200c41659113b27891d692de3d3a79b50f1e9a9c94d1eb, commit_tx=02000000015bfc56cfcd9bca041f0f33b8f3b6f3fad7fbf83b264813cb1a7bf4b334d704d90100000000262cc48001878e0400000000001600145b9f750213ba5c426e44a0714b4d06212029a3c298cb9620, sig_hash=6a2b47ad05d7ba79dbd865f858167b1179fb3c08aedfc4977f67246a664f40c6
2018-06-08 08:45:35.375 [ERR] HSWC: ChannelLink(0:0:0) link failed, exiting htlcManager
```

`ChannelLink(0:0:0)` is present again.

**Comment by btcontract** [comment]
And got another channel of mine closed while trying to send a `200 sat` payment, LND log: http://paste.ubuntu.com/p/T37SJVQjBn/

Remote LND commit tx: `020000000142cb27899dfc4d9bbb55253bce2d7938bcb458df856f0a67bf1e47f25df2323e0000000000c2923d8001509d07000000000016001486224148c7adbacec6c2ec9f8e5815463886b7120fada120`

Local BLW commit tx: `020000000142cb27899dfc4d9bbb55253bce2d7938bcb458df856f0a67bf1e47f25df2323e0000000000c2923d8001889c07000000000016001486224148c7adbacec6c2ec9f8e5815463886b7120fada120`

Again a difference of `200 sat`, in BLW commit tx the value is `498824`, in LND commit tx it's `499024`.

**Comment by Roasbeef** [comment]
> It does seem like not sending a CommitSig before a funding tx reaches 7 (possibly 6) confirmations has something to do with this.

Hmm, that's odd, it shouldn't really matter if confs have passed or not. The only thing that _might_ affect is receiving payments via routing hints, as we may not have sent our hint to the remote peer at that time (would need to check though). The zero chan ID thing is the best lead atm, as is what we'll investigate, thanks for the report.

**Comment by Roasbeef** [comment]
> Meanwhile I've reconstructed a remote commit tx itself as seen by BLW: 

Ok, then we created an identical state. Where's the HTLC though? Did BLW try to create a commitment state without an HTLC?

**Comment by btcontract** [comment]
Do you mean https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#message-retransmission? It is fully supported.

**Comment by btcontract** [comment]
Got yet another channel remotely closed with another LND node (rompert.com, https://1ml.com/node/02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b) on trying to add a `79 sat` HTLC.

LND log: http://paste.ubuntu.com/p/q7czx23STH/

LNG remote generated commit tx: `02000000010c039e52771aa29584fc75ff02e11a56d24649d3607b64c875ab866812246b030000000000ef93988001693a0f0000000000160014533dee625bef36762cc8fed0e9256f83bbaf8b43a0a58520`

BLW local generated commit tx: `02000000010c039e52771aa29584fc75ff02e11a56d24649d3607b64c875ab866812246b030000000000ef939880011a3a0f0000000000160014533dee625bef36762cc8fed0e9256f83bbaf8b43a0a58520`

Again a difference of `79 sat`. What's interesting is this time `ChannelLink(526746:2341:0)` is present in logs, not `ChannelLink(0:0:0)` and payment attempt was made when funding tx had more than 7 confirmations.
