### ISSUE TITLE
Force Channel Failed - Balance Pending

### ISSUE THREAD

**Issue by RossClelland** [lightningnetwork/lnd#1343]
### Background

I opened a channel with another node and attempted to make a payment which failed with an error stating there was no route to the target. I tried again later but had the same issue and the other node appeared to be down. I used the force close method and waited 24h for the transaction to mature. However the channel is still in a Pending state.

My logs don't go back far enough but here's the current status:

lnd successfully unlocked!
bitcoin@bitseed3:~$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "02a94aadd09055ca615bd76aacb6bba748ed8a0d2e5924aea643e3dc3912085314",
                "channel_point": "1a310f6ad4daad7362782eb0423145782ffdc864d5158784ce8c943d1a3bf09e:1",
                "capacity": "506475",
                "local_balance": "73955",
                "remote_balance": "0"
            },
            "closing_txid": "e8660ca0d580cff4c0c7bc75c1df3b303ab98995cc0661d3c14192e106bb107a",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ],
    "waiting_close_channels": [
    ]
}

### Your environment

0.4.1 LND
UBUNTU
Bitcoind 

### Steps to reproduce

Force close channel after a failed attempt at making a payment.

### Expected behaviour

Channel should close and pending/limbo  balance should have been returned

### Actual behaviour

Closing transaction has matured but the channel is still in a Pending state

**Comment by Roasbeef** [comment]
At this point, it looks like your "to self" output has been spent. But there are still HTLC outputs that haven't been swept. Once these become mature, then these will be swept as well. Also I would recommend updating to `0.4.2` once these channels have been swept, as many bugs have been fixed in this new version.
