### ISSUE TITLE
lnd-lnd force-closing due to invalid_commit_sig

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1348]
two lnd trying to send 1 sat invoices to eachother. one froze in mutex-land. restarted both. channel got closed after restarts.

lnd version 0.4.2-beta commit=4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae

might be closely related to #1340 

```2018-06-08 14:44:22.767 [ERR] HSWC: ChannelLink(522968:666:1) Failing link: ChannelPoint(9d3f4868ec2d1c4c8c7da14d4e60adb08a57ee9f73743066d9f9e0a31ecf9acd:1): unable to accept new commitment: rejected commitment: commit_height=594, invalid_commit_sig=3044022026ed0d5ac10ca73cd7358aeb30abfdaadc8cbd8f173f8b84b20e61d55ccc6d04022045b7363a5e1295d20a39b008be240c39a4f0a232982b3a75beed28eb8037d235, commit_tx=0200000001cd9acf1ea3e0f9d9663074739fee578ab0ad604e4da17d8c4c1c2dec68483f9d0100000000a1b71280023d0a020000000000220020a4d327d89eee074a20bbe25f5d0c5955a7ab50d1566a45ea1621222b71696a3577340d000000000016001409a2344fd318ff0478b2f5663cdcbf4ff70b6028fc55d720, sig_hash=2389fc4abd70c5c97696513bfd73f0393ee9b70f515403ee117f387d65f903ed```

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
Don't think it's related to #1340, instead it's related to #1345. Also are you able to reproduce with two fresh instances?
