### ISSUE TITLE
failed to make payment, bitcoins dissapeard 

### ISSUE THREAD

**Issue by Cryptoknut** [lightningnetwork/lnd#1354]
### Background

Yesterday I tried to make a payment over the lighting network. I have made successful payments before. I will enter what I did below. 

lncli channelbalance
{
    "balance": "414323",
    "pending_open_balance": "0"
}

lncli decodepayreq lnbc2357510n1pd3kpdfpp54meuf89hwgqsxde2u37v77z4gp6ll7w20uw0hx4gmly233adhggqdzdxysv89eqgf5hgcm0d9hzqnrfva58gmnfdenjqnn9w3mk7untyp2z65mgd9e8ggpdyp8xzane9ssyccqzysk0d2ks4fxem0svyq03vah9syex7duhm8us4pfdhlrc8fghfef5yr968hpxf538pgve9c2tqrtpgm9dt6k326nur94wgullu9pg9ftuqqq4s5vs
{
    "destination": "039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3",
    "payment_hash": "aef3c49cb7720103372ae47ccf78554075fff9ca7f1cfb9aa8dfc8a8c7adba10",
    "num_satoshis": "235751",
    "timestamp": "1528497577",
    "expiry": "3600",
    "description": "1 × Bitcoin Lightning Network T-Shirt - Navy, L",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144",
    "route_hints": [
    ]
}

lncli payinvoice lnbc2357510n1pd3kpdfpp54meuf89hwgqsxde2u37v77z4gp6ll7w20uw0hx4gmly233adhggqdzdxysv89eqgf5hgcm0d9hzqnrfva58gmnfdenjqnn9w3mk7untyp2z65mgd9e8ggpdyp8xzane9ssyccqzysk0d2ks4fxem0svyq03vah9syex7duhm8us4pfdhlrc8fghfef5yr968hpxf538pgve9c2tqrtpgm9dt6k326nur94wgullu9pg9ftuqqq4s5vs

--at this point it seemed to hang no response was given. I went over to a new tab to check my channel balance 

lncli channelbalance
{
    "balance": "178354",
    "pending_open_balance": "0"
}

-- You can see my amount of satoshis came out of the channel but the payment did not clear from the recipient. I have tried restarting my node and lnd and everything seems to be working fine other than the btc from the failed payment never came back. I was given this error message below after restarting node & lnd

lncli channelbalance
{
	"payment_error": "htlc switch have been stopped while waiting for payment result",
	"payment_preimage": "",
	"payment_route": null
}

 

### Virtualbox running linuxmint 

* version of `lnd`
lncli version 0.4.1 commit=524291dadaf39bfbd99efb6654beb6030b3e285e
* which operating system (`uname -a` on *Nix) 
linux mint 18.3 cinnamon  running on virtualbox 5.2.6
* version of `btcd`, `bitcoind`, or other backend
0.16.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

--let me know if you need anything else, thanks in advance :)

**Comment by baryluk** [comment]
I believe I had similar issue few days ago. `lncli payinvoice` would stuck for hours, doing nothing. I needed to kill it eventually. I do not actually know if my coins dissapeard tho.

**Comment by Roasbeef** [comment]
Your coins aren't gone, there may be some nodes on the network that are running a newer version of `lnd` where some regressions have popped up that can introduce a deadlock at times. If you look at `listchannels`, the HTLC will be pending if it somehow targeted a node in this state. If you restarted and the node then cancelled back this payment, then the coins are still pending.

**Comment by baryluk** [comment]
Ok, but what about `lncli payinvoice` being stuck for hours? At least in my case.

@Cryptoknut Did your `lncli payinvoice` eventually finished, or you did cancel it by Ctrl-C or something?
