### ISSUE TITLE
lncli fwdinghistory doesn't return latest entries

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1357]
my guess is that 
lncli fwdinghistory has a default of 100 entries, and default starting 24 hours ago
but it doesn't give you the 100 *latest* entries, but rather the 100 *first* entries, starting 24 hours ago

```
lncli fwdinghistory --max_events 10 | grep timestamp | tail -n10
lncli fwdinghistory --max_events 100 | grep timestamp | tail -n10
lncli fwdinghistory --max_events 1000 | grep timestamp | tail -n10
```

these all give different results

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
I don't see anything inconsistent. The command will return the forwarded payments in that time range. The default time range is 24 hours. By default, we'll return the first 100 payments. You can tune the `--max_events` to return more payments.
