### ISSUE TITLE
lncli listpayments should show fee in msat

### ISSUE THREAD

**Issue by baryluk** [lightningnetwork/lnd#1359]
It shows fee in saotshi now, and apparently rounds it down. It should be in msat.

**Comment by Roasbeef** [comment]
Agreed it should list `msat` instead of `sat`. It's stored in the database (rightfully) as sat, so just the protos need to be modified to display msat.

**Comment by baryluk** [comment]
I can grab this. Do you want to retain 'fee' field for compatibility or is it fine to remove it? I guess it is fine to remove it (mark as reserved tag in proto), as lnd isn't release yet and shouldn't really used for anything? ;D

**Comment by Roasbeef** [comment]
I think we can first add the new field, and annotate the old one as deprecated just as we did recently in the `Hop` proto.

**Comment by baryluk** [comment]
Ok. I just was curious about your policy on compatibility at this moment. Will do.

**Comment by offerm** [comment]
I see no impact for marking the old field as deprecated.  It is not even indicated as such in the swagger.json.

**Comment by baryluk** [comment]
I know marking the field deprecated is fine. I was thinking to just remove it in the same commit completely, or even reuse the same tag name as "fee" field. Should be "fine" as `lnd` is not released yet. That is what I meant by "policy on compatibility at this moment".

**Comment by offerm** [comment]
My comment was about @Roasbeef suggestion to make these fields marked as deprecated in the rpc.proto file. I see no impact at all for such marking and fail to understand how new code can be aware that these fields are deprecated. Maybe we should switch to a newer protoc version  for that to have an impact? 


@baryluk see this: 

> The exported API's are not yet stable, so be warned: they may change drastically in the near future.

**Comment by Roasbeef** [comment]
Well `lnd` _has_ been "released". However we can do it in two phases perhaps: first deprecate it, then warn that it'll be removed, then just remove it all together.

**Comment by pinheadmz** [comment]
Wanted to add to this discussion that the `value` field in `listpayments` should also display in mSat, or at least include a separate `value_msat` field. I was able to pay a 1 mSat invoice using LND by manually editing `queryroute` data and passing that edited route to `sendtoroutes` (thanks to @alexbosworth in slack for help on this)

yet in both `listchannels` and `listpayments` the values are displayed as `0`
