### ISSUE TITLE
An endless logging about "Unable to retrieve advertised address for node"

### ISSUE THREAD

**Issue by Perlover** [lightningnetwork/lnd#1365]
### Background

I test Bitcoin Lightning Wallet (hereinafter **_BLW_**) (Android) with the LND.
I have endless logging in LND about "Unable to retrieve advertised address for node". The status of channel in BLW as OFFLINE but funding transaction (780459ab1713419bd1976f1e55eccacd0849b9a4b1570fc2c6baf47c0a0479ee) has 9 confirmations already. The LND node is online (0243e39ae262094048ecd96ede723e246821fbad7b73efb15ad2426cf78a3f68f1@46.229.165.145:9735).

Some logs here: https://github.com/btcontract/lnwallet/issues/53

### Your environment

* version of `lnd` - 0.4.2-beta commit=2e838abb3f552e...cbcefa5
* which operating system (`uname -a` on *Nix) - CentOS 6.*
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.16.0
* any other relevant environment details - Bitcoin Lightning Network v0.09-52

### Steps to reproduce

1. Install BLW from the "Google Play"
2. To make funding transaction
3. During waiting of 3 confirmations may be to need to change IPSs during process.

### Expected behaviour

The channel in BLW as OPEN after 3 confirmations

### Actual behaviour

The channel in BLW as OFFLINE (yellow), endless logging in LND when BLW is online.

**Comment by Perlover** [comment]
I checked my logs
I see same error (Unable to retrieve advertised address for node) only after today upgrade from 7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 to 2e838abb3f552e6d4d2186453b739da7cbcefa54. I upgraded from sources by `git pull && make clean && make && make install`

**Comment by Perlover** [comment]
I checkout to 4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae commit and i see again "Unable to retrieve advertised address for node" for Eclair wallet node for example.
If i checked out to 7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 (git tag v0.4.2-beta) - i don't see same errors. I think the problem is located somewhere between 7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 and 4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae commits...

**Comment by Perlover** [comment]
Hmmm

    commit 08f80b6cf35d427bf9e1a39079543cccfb63ae1c
    Author: Wilmer Paulino <wilmer.paulino@gmail.com>
    Date:   Wed May 2 02:30:56 2018 -0400
    
	server: use advertised address when reestablishing inbound connections
	
	In this commit, we update the way we reestablish inbound connections if
	we lose connectivity to a node we have an open channel with. Rather than
	fetching the node's advertised port, we'll fetch one of their advertised
	addresses instead. This ensure that if the remote node is running behind
	a proxy, we do not see the proxy's address.

**Comment by Perlover** [comment]
I checked out to 0.4.2-beta commit=7cf5ebe2650b67...1f1d6e19 (0.4.2-beta bump version) and i don't have a problem with connects from Android wallets (Eclair wallet & Bitcoin Lightning Wallet)
But i think somewhere from *7cf5ebe* commit there is bug "Unable to retrieve advertised address for node". I tried some commits before 08f80b6cf35d427bf9e1a39079543cccfb63ae1c (for example 08f80b6cf35d427bf9e1a39079543cccfb63ae1c) but i had problem - endless OFFLINE<->WAIT_FOR_FUNDING_CONFIRMED reconnects when channel had been creating (from Eclair wallet)

**Comment by Perlover** [comment]
And i think this issue is related with this bug too
https://github.com/lightningnetwork/lnd/issues/1361

**Comment by Perlover** [comment]
And related with this issue:
https://github.com/lightningnetwork/lnd/issues/1360

**Comment by Roasbeef** [comment]
Related to #1351.
