### ISSUE TITLE
Integration test fails - started by PR 1350 merge

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1366]
### Background

This happens locally and on travis.
started to be consistent from #1350 
please check:

--- FAIL: TestLightningNetworkDaemon (108.15s)
	lnd_test.go:10481: Running 43 integration tests
    --- PASS: TestLightningNetworkDaemon/onchain_fund_recovery (47.72s)
    --- PASS: TestLightningNetworkDaemon/basic_funding_flow (0.20s)
    --- PASS: TestLightningNetworkDaemon/update_channel_policy (6.21s)
    --- PASS: TestLightningNetworkDaemon/open_channel_reorg_test (3.40s)
    --- PASS: TestLightningNetworkDaemon/disconnecting_target_peer (2.61s)
    --- PASS: TestLightningNetworkDaemon/graph_topology_notifications (6.49s)
    --- FAIL: TestLightningNetworkDaemon/funding_flow_persistence (30.32s)
    	lnd_test.go:69: Failed: (funding flow persistence): exited with error: 
    		*errors.errorString peers unable to reconnect after restart: peers not connected within 15 seconds
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:1399 (0xb859eb)
    			testChannelFundingPersistence: t.Fatalf("peers unable to reconnect after restart: %v", err)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:94 (0xb7dd6b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:10494 (0xbd141a)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f66e0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
FAIL

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by halseth** [comment]
Thanks, we are currently looking into this.

**Comment by offerm** [comment]
@halseth be aware that PR #1373 is solving it.

Offer

**Comment by offerm** [comment]
@Roasbeef @halseth 

Looks like it is still failing on a different test. See PR #1363 

--- PASS: TestLightningNetworkDaemon/switch_offline_delivery (19.33s)
    --- PASS: TestLightningNetworkDaemon/switch_offline_delivery_persistence (22.18s)
    --- FAIL: TestLightningNetworkDaemon/switch_offline_delivery_outgoing_offline (26.63s)
    	lnd_test.go:69: Failed: (switch offline delivery outgoing offline): exited with error: 
    		*errors.errorString Bob(0): timeout waiting for channel(34551f3ecf2415978b5d686c74abea17f4ab38fbc0f210c0a0e3ff79739138db:0) open: channel not opened before timeout
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:9390 (0xbbdc7b)
    			testSwitchOfflineDeliveryOutgoingOffline: t.Fatalf("%s(%d): timeout waiting for "+
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:94 (0xb7e04b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:10021 (0xbcd25a)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f66e0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
FAIL
exit status 1

**Comment by Roasbeef** [comment]
Yep that's a distinct flake.
