### ISSUE TITLE
sendcoins erroring out

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#1368]
### Background

Describe your issue here.

Cannot send funds on chain.

### Your environment

* version of `lnd` commit hash ed2b5692a23821c43ce686fced4c25904355453a
* which operating system (`uname -a` on *Nix) x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend:tom btcd
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

I have an un-broadcasted pending open channel:
{
"channel": {
"remote_node_pub": "030a7edba83a52414807aaf46f1c6efc6ff87994b6328d503a785a56c753648c57",
"channel_point": "7043005938fc3cffe382aad2fb10d4f77330286c5ad3b06706e35cd58bd608da:0",
"capacity": "11555792",
"local_balance": "11554525",
"remote_balance": "0"
},
"confirmation_height": 0,
"commit_fee": "1267",
"commit_weight": "600",
"fee_per_kw": "1750"
}
],

lncli sendcoins --sat_per_byte 1 32rAsENdG4damhGoQ1gptuqAe3rDi2k5AG 16233000
[lncli] rpc error: code = Unknown desc = -22: TX rejected: orphan transaction 2fb6145958b993557ef103cad36adca30b9d6312861f6e766271da9256030608 references outputs of unknown or fully-spent transaction 61d4d996361583571dd10fcf635d695e7356c2595a24f9a838a918577ed383c1

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
What chain backend are you using? On start up, do you see that channel attempted to be re-broadcast?

**Comment by juscamarena** [comment]
btcd, still using your fork.

And yeah.

Here's some startup logs.

https://paste.ubuntu.com/p/NnGHFrFKN5/

I see it inserting unconfirmed every startup, but it may be referencing already spent inputs as well?

And as you can see lnd attempts to broadcast a load of other transactions long confirmed.

The negative ones being from the small channels that I need to forget once there's an forget channel rpc.

**Comment by Roasbeef** [comment]
```
2018-06-11 20:06:28.206 [DBG] LNWL: Could not resend transaction c5a9f8f27bb87212d8281e392e30baf41a174077acb015ffeeea6349b1147ec0: -22: TX rejected: transaction already exists
```

Ah ok, I see which error we're missing from `btcd` now, will be an easy fix, I can actually send you a patch for my fork to apply, as we want to switch over to `btcsuite/btcwallet` this week.

**Comment by Roasbeef** [comment]
Actually, "already exists" is fine. That just means that the transaction is already in the mempool of the node.

**Comment by juscamarena** [comment]
Ran:

cd $GOPATH/src/github.com/roasbeef/btcwallet/cmd/dropwtxmgr
dropwtxmgr --db ~/.lnd/data/chain/bitcoin/mainnet/wallet.db

Rescanned all wallet transactions and can send funds fine now. I just have the two lingering pending open channels referencing already spent outputs.

**Comment by Roasbeef** [comment]
Cool, so will close this for now, but make a new issue to ensure that we remove these pending channels if we fail to actually broadcast the final funding transaction.
