### ISSUE TITLE
Describe Graph gRPC

### ISSUE THREAD

**Issue by ekerstein** [lightningnetwork/lnd#1369]
I'm trying to get the describe graph data as a Python dictionary using gRPC. I feel like i'm missing something simple.

When I call describe graph I get a ChannelGraph object. When I call the object it prints out the data, and I've noticed I can do things like "describegraph.nodes" or "describegraph.edges". But I can't figure out how to simply get the data into a Python dict so I can iterate through it and do other operations. What am I missing?

```
from lndgrpc import LNDClient
lnd = LNDClient("127.0.0.1:10009")
data = lnd.describe_graph()
for d in data:
    print(d)
TypeError: 'ChannelGraph' object is not iterable

print(data['nodes'])
TypeError: 'ChannelGraph' object is not subscriptable

```

**Comment by Roasbeef** [comment]
I'd call `dir()` on the returned object to see how to manipulate it. This is more of an Python API level issue, rather than an `lnd` one. You may also want to check out the proto docs for Python gRPC in particular.
