### ISSUE TITLE
Accessing REST api outside local computer

### ISSUE THREAD

**Issue by phillyfan1138** [lightningnetwork/lnd#1376]
### Background

I'm trying to perform commands via the REST api on my local network.  I receive an immediate "connection refused" when I try to access the REST api from a different computer on the same network.

### Your environment

* version of `lnd`: 0.4.2
* which operating system (`uname -a` on *Nix): 4.14.34-v7+ (ARM debian)
* version of `btcd`, `bitcoind`, or other backend: 0.16.0
* any other relevant environment details: I'm on a Raspberry PI

### Steps to reproduce

The relevant line of lnd.conf: 
restlisten=0.0.0.0:8080

I then performed the following curl request from a computer on my network:
curl --insecure --header "Grpc-Metadata-macaroon: [mymacarroon]" https://[myip]:8080/v1/getinfo

### Expected behaviour
I was expected to get info about the node.  When I run the same command above on the Raspberry PI (with localhost substituted for [myip]) I get a response with the node info.  I can also successfully access the RPC endpoint from outside my local computer.

### Actual behaviour

I immediately receive the following error:

curl: (7) Failed to connect to [myip] port 8080: Connection refused

**Comment by Roasbeef** [comment]
Ensure that your NAT situation is figured out. You'll need to ensure that the ports are being forwarded properly. 

If you're trying to access via LAN, then you'll need to use the local IP, not your external IP.

**Comment by phillyfan1138** [comment]
I'm only on my local LAN and I'm using my local (192.168.x.xxx) IP address.  Again, this is working for gRPC, just not for REST.

**Comment by Roasbeef** [comment]
Check to ensure (using a tool like `netstat` or `lsof`) that `lnd` is actually listening on the proper port.

**Comment by phillyfan1138** [comment]
I had the restlisten line in the wrong location in lnd.conf...I now get a response from lnd.  However, I now get a certificate error.  The answer in [issue 684](https://github.com/lightningnetwork/lnd/issues/684) is to regenerate the certificates with additional IP addresses...however after some googling I couldn't figure out how to generate certificates in such a way as to include specific IP addresses.  Any guidance would be appreciated!

**Comment by harshitgupta** [comment]
> I had the restlisten line in the wrong location in lnd.conf...I now get a response from lnd. However, I now get a certificate error. The answer in [issue 684](https://github.com/lightningnetwork/lnd/issues/684) is to regenerate the certificates with additional IP addresses...however after some googling I couldn't figure out how to generate certificates in such a way as to include specific IP addresses. Any guidance would be appreciated!

Hi were you able to figure out how to regenerate the certificates?
