### ISSUE TITLE
Question: Makefile - Travis + coveralls

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1378]
Is there a reason why travis coveralls (COVER in Makefile) is not running also on integration test. Without this, there are no tests for the rpcserver.go which is a hugh and important file.

Would you like me to suggest a PR for that?

**Comment by Roasbeef** [comment]
It isn't running as the integration tests use active `lnd` binaries. The coverage stuff only works with tests within the package executed by the runtime.

**Comment by offerm** [comment]
@Roasbeef @halseth 

Still think it can be done. Let me explain:

Today, when the integration test runs it is using the lnd-debug binary to start a process for Alice, Bob, Carol, etc. If we would somehow cause lnd-debug to generate cover data we could collect the data for each execution of lnd-debug and append it to the cover data we collect for the unit tests. 

Actually, there is a nice way in which we can create lnd-debug with cover.

`go test  -c -o lnd-debug -covermode count `

The above creates a binary which is running the lnd tests. 

Now, what if we create a test which invokes the main() function? 

say main_test.go
```

// +build !rpctest

package main

import (
	"testing"
	"flag"
	"fmt"
	"os"
	"strings"
	"path"

)
func TestEmpty(t *testing.T) {

}

func TestMain(m *testing.M) {

		// Parse the command line using the stdlib flag package so the flags
		// defined in the testing package are populated. This include the
		// -coverprofile flag.
		flag.Parse()
		// Strip command line arguments that were for the testing package and
		// that are now handled. This will remove arguments that wouldn't be
		// recognised when using a 3rd party command line parser like
		// github.com/urfave/cli.
		var programArgs []string
		for _, arg := range os.Args {
			if strings.HasPrefix(arg, "-test.") ||
				strings.HasPrefix(arg, "-httptest.") {
				continue
			}
			programArgs = append(programArgs, strings.Join([]string{"--",arg},""))
		}
		os.Args = programArgs

		// If the test binary name is $program_name or $program_name.coverage,
		// we are being asked to run the coverage-instrumented program. So call
		// main() directly.
		if path.Base(os.Args[0]) == "lnd-debug" ||
			path.Base(os.Args[0]) == "lnd-debug" {
			main()
		}

		// Run unit-tests as usual.
		os.Exit(m.Run())


}


```

With this we can invoke lnd via the test file with:

`./lnd.coverage  -test.v -test.coverprofile=integration.cov bitcoin.active bitcoin.simnet debuglevel=trace no-macaroons externalip=84.111.139.147 alias=Offer noencryptwallet `

More information can be found here:

[Building and using coverage-instrumented programs with Go](http://damien.lespiau.name/2017/05/building-and-using-coverage.html)

Suggest to reopen this issue and create a PR for it.

**Comment by halseth** [comment]
Code coverage numbers are currently a bit off, and should probably be given some love to reflect the actual lines of gocode (excluding comments etc) that is covered by the unit tests, over adding coverage of integration tests.

When that is said, code coverage are usually ONLY measured for unit tests, and I don't think they make that much sense for integration tests tbh (they are not at all deterministic for starters).

**Comment by offerm** [comment]
@halseth Thanks for your response.

Don't know what you mean by "Code coverage numbers are currently a bit off". From playing with these tests in the last few weeks (see PR #1493 ) I haven't seen anything like that and the data presented by coveralls was precise. 

[from here:](https://medium.com/@jonatan_ivanov/code-coverage-not-only-for-unit-tests-419f3c73d00 )

> Basically, test coverage can be measured for all levels of tests, like unit-, integration-, acceptance tests, etc

In LND's case, the current coverage number is ~54%. This is relativly low. 

I see three main issues:

1. How do you know that LND's integration tests actually checking ALL RPC calls? without coverage you can't be sure about it.

2. Adding lines to rpcserver.go will, in most cases lead to failure with coveralls. These lines are added to the line count and are not covered by unit tests (so coverage % declines).

3. Community memebers are not aware that you don't give attantion to coveralls and spend time trying to make PRs flaged green.  If you consider coveralls as noise why don't you remove it from the project setup?

Suggest you reconsider this.

Offer
