### ISSUE TITLE
Loading config file error

### ISSUE THREAD

**Issue by skcheffy** [lightningnetwork/lnd#1386]
### Background

I have been working on setting up Litecoin LN and Bitcoin LN.  I have been running full nodes for a while and wanted to dive a little deeper.  I have my Litecoin LN working properly and i basically changed the ln.conf to represent Bitcoin.  When I went to run lnd i kept getting an error saying 

loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

After asking around i finally went on Github and found something similar.  Someone said to put:

lnd --debuglevel=trace --bitcoin.active --bitcoin.testnet

When I did that my response was:

Attempting automatic RPC configuration to btcd
unable to load RPC credentials for btcd: unable to extract RPC credentials: open /Users/skcheffy/Library/Application Support/Btcd/btcd.conf: no such file or directory, cannot start w/o RPC connection

I was confused at first but then i realized there was a folder in Application Support called BTCD.  There was nothing in it.  I tried duplicating the confirmation file in that folder and got:

Attempting automatic RPC configuration to btcd
unable to load RPC credentials for btcd: unable to extract RPC credentials: open /Users/skcheffy/Library/Application Support/Btcd/btcd.conf: no such file or directory, cannot start w/o RPC connection

So, my assumption is lnd is pulling from that folder for some reason and not the Bitcoin folder where all the files and info is.

Any thoughts on how I can reconfigure?

### Your environment

I did my LND setup from here:

https://gist.github.com/ecurrencyhodler/f6da7f26110c875e7fa41a91c66b72a1

* macOS Sierra 10.12.6
* BitcoinCore .16

* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by skcheffy** [comment]
The odd thing is that I found the btcd folder but there is absolutely nothing in it. Seems that Core downloaded to Bitcoin folder.  

I set up manually based on using the Bitcoin folder which has a bitcoin.conf.  It seems lnd is requesting a conf in the btcd folder so even though I have nothing else in that folder i would still need to create the conf in btcd?  I did attempt before i messaged but the credentials didn't work and i assume because i used the same name and PW i pulled from the Bitcoin folder.  I am adding a few screen shots to show you what i am dealing with.

I tried sample-lnd.conf in command line and got nothing.

![screen shot 2018-06-13 at 8 54 21 pm](https://user-images.githubusercontent.com/31999006/41385830-f989d430-6f4b-11e8-92f2-c07c23d4f664.png)
![screen shot 2018-06-13 at 8 54 47 pm](https://user-images.githubusercontent.com/31999006/41385837-07b1e386-6f4c-11e8-95b4-4fca4f4d904a.png)

**Comment by Roasbeef** [comment]
Look at `lnd -h`. You need to specify that you're using `bitcoind`. Atm, you aren't doing so.

**Comment by skcheffy** [comment]
This is my bitcoin.conf file without Password in there.

![screen shot 2018-06-13 at 8 55 46 pm](https://user-images.githubusercontent.com/31999006/41385878-4ba5d7fa-6f4c-11e8-876e-ac8563bd45c4.png)

**Comment by githorray** [comment]
Don't forget the `rpcallowip` settings. Without it, the rpc server won't allow connections.

**Comment by Roasbeef** [comment]
Have you looked at our installation instructions? It spells out the parameters you need to specify. I mean `lnd.conf`, not `bitcoind.conf`.

**Comment by skcheffy** [comment]
Going there now.  Sorry i am sure this was a stupid question but i think i may get there.

**Comment by NTierSoftware** [comment]
> `rpcallowip`

Has this been deprecated?  It's not found in the canonical:
[https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf](url)

**Comment by guggero** [comment]
`rpcallowip` is a `bitcoind` config param, it never was a param in `lnd`.
