### ISSUE TITLE
lncli hangs opening channel

### ISSUE THREAD

**Issue by tim222tim** [lightningnetwork/lnd#1388]
### Background

I have a repeatable issue opening channels with 0.4.2.

### Your environment

lnd 0.4.2-beta commit=2e838abb3f552e6d4d2186453b739da7cbcefa54
Ubuntu 16.04
bitcoind 0.16.0

### Steps to reproduce

confirmed wallet balance = 185290, pending open balance = 0

open channel 180000 
    lncli does not return to prompt (I have waited a long time, though not with this log capture)

all wallet balances  = 0, pending open balance = 176018
new channel shows as pending open, but channel point tx doesn't exist on block explorer

closechannel : "unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found"
closechannel -force :  "unable to find arbitrator"

shutdown and restart lnd

confirmed wallet balance = 185290, pending open balance = 176018

close channel : "no peer for channel with chan_id="
connect to channel peer : "already connected"
close channel : "no peer for channel with chan_id="
close channel -force : received closing_tx, but doesn't exist on block explorer

confirmed walletbalance = 185290, pending open balance = 0

### Expected behaviour

Channel should have opened or an error should have been reported.

### Actual behaviour

Channel was in limbo state until lnd was restarted and channel was force closed.

Here's a log of the above.

[lndlog.zip](https://github.com/lightningnetwork/lnd/files/2101756/lndlog.zip)

**Comment by Roasbeef** [comment]
Are you able to reproduce on master? A bug related to this was recently fixed.

**Comment by tim222tim** [comment]
I just repeated the same steps with 0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc and got the same results.

**Comment by Roasbeef** [comment]
What are your steps to reproduce even?

**Comment by tim222tim** [comment]
Here are the steps I used to reproduce the issue. I apologize that my original message was not clear.

_I start out with a confirmed wallet balance and no pending open balance:_

`lncli walletbalance`


```
{
    "total_balance": "185290",
    "confirmed_balance": "185290",
    "unconfirmed_balance": "0"
}
```

`lncli channelbalance`

```
{
    "balance": "1572426",
    "pending_open_balance": "0"
}
```

`lncli connect 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf@13.92.254.226:9735`

```
{

}
```

`lncli openchannel 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf 180000`

_There is no output and the command prompt does not come back._

_Now the confirmed balance is gone and there is a pending open balance:_

`lncli walletbalance`

```
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}
```

`lncli channelbalance`

```
{
    "balance": "1572426",
    "pending_open_balance": "176018"
}
```

`lncli pendingchannels`

```
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf",
                "channel_point": "269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89:1",
                "capacity": "180000",
                "local_balance": "176018",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "3982",
            "commit_weight": "600",
            "fee_per_kw": "5500"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}
```

_Transaction 269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89 never appears  on block explorer, not even as uncommitted._

_Attempts to close the channel are unsuccessful:_

`lncli closechannel 269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89 1`

```
[lncli] rpc error: code = Unknown desc = unable to gracefully close channel while 
peer is offline (try force closing it instead): channel link not found
```

`lncli closechannel 269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89 1 -force`

```
[lncli] rpc error: code = Unknown desc = unable to find arbitrator
```
_I stop and restart lnd. Now the confirmed wallet balance reappears, but the pending open balance is still there:_

`lncli stop`

`lncli unlock`

`lncli walletbalance`

```
{
    "total_balance": "185290",
    "confirmed_balance": "185290",
    "unconfirmed_balance": "0"
}
```

`lncli channelbalance`

```
{
    "balance": "1572426",
    "pending_open_balance": "176018"
}
```

_I still can't close the channel gracefully, but am able to force close it:_

`lncli connect 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf@13.92.254.226:9735`

```
[lncli] rpc error: code = Unknown desc = already connected to peer: 13.92.254.226:9735
```

`lncli closechannel 269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89 1`

```
[lncli] rpc error: code = Unknown desc = no peer for channel with 
chan_id=896cb10460ed0caaf3127ee1512f80cca4fdb9f0de923958ba4854ab56e59c27
```

`lncli closechannel 269ce556ab5448ba583992def0b9fda4cc802f51e17e12f3aa0ced6004b16c89 1 -force`

```
{
        "closing_txid": "a85d33d9ee1006506cf0d1082480cdd5f567460299183e6e39db24a9394f429f"
}
```

_Transaction a85d33d9ee1006506cf0d1082480cdd5f567460299183e6e39db24a9394f429 never appears on block explorer. This makes sense, I suppose, since the fudning transaction never appeared either._

_Now the wallet and channel balances are back where we started:_

`lncli walletbalance`

```
{
    "total_balance": "185290",
    "confirmed_balance": "185290",
    "unconfirmed_balance": "0"
}
```

`lncli channelbalance`

```
{
    "balance": "1572426",
    "pending_open_balance": "0"
}
```

The log file I posted in my original message follows these same steps. The only difference is that the I was attempting to open a channel to a different node.

**Comment by Roasbeef** [comment]
Perhaps try with a distinct node? If the node you're trying to connect to is faulty for some reason, then makes sense that we can't actually complete the funding process. I'd also look in the logs to see how far we get in the funding process.

**Comment by tim222tim** [comment]
I have reproduced this same exact behavior connecting with 6 to 8 different nodes, all since 0.4.2. This did not happen with earlier versions.

**Comment by Roasbeef** [comment]
I guess what I'm trying to say, is that it's an issue worth tackling if you can reproduce locally with distinct nodes. Otherwise, we don't know what commit the remote nodes are running which may have had bugs which are patched in the newer commits. 

The fact that your transactions are never broadcast, means that the remote node didn't even respond to the first message. But looking at the logs, we see: 
```
2018-06-14 05:20:41.679 [ERR] FNDG: Unable to complete reservation sign complete: Transaction rejected: output already spent
2018-06-14 05:20:41.679 [INF] FNDG: Cancelling funding reservation for node_key=03473ec133c70c05db8d1abaa272449b0cfd3d38e1978bfe1e7765d1913b7e7c51, chan_id=6859a4c7d8ec8b1df77a400a64b47b618169ea8e1908ff7fac0ee61ad34d2317
2018-06-14 05:20:41.679 [ERR] FNDG: unable to cancel reservation: unable to cancel reservation: attempted to cancel non-existent funding state
```

**Comment by tim222tim** [comment]
Ok. I'm not sure what you mean by distinct nodes. Can you give me specific instructions on how to proceed? I would be happy to run any procedures that you recommend.

**Comment by tim222tim** [comment]
Sorry. I just reread your message and understand now that you'd like me to run a second node and run this test between the two nodes locally. I could try that. Can I run a second node on the same machine? If so, can you point me to instructions on how do keep those configurations separate?

**Comment by Roasbeef** [comment]
Yes you can run a second node on the same machine. You'll need to set a new `lnddir`, and also set the various listening ports (see `lnd -h` or `sample-lnd.conf`) to distinct values so they don't conflict.

**Comment by petertodd** [comment]
I'm seeing this issue as well.

**Comment by Roasbeef** [comment]
See #1505 and #1495.

**Comment by petertodd** [comment]
Thanks.

Curiously the problem seems to have resolved itself after trying a few more times, though it took leaving my node on overnight with a pending "closechannels" command for the channels to actually close.
