### ISSUE TITLE
Add DisconnectPeer RPC

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#139]
An RPC should be added that removes a peer targeted either by its public key or it's relative `peer_id`. The RPC should remove the peer both from the sever and also remove the persistent connection attempt 

**NOTE:** It isn't possible to complete this issue until the `connmgr` package within `btcd` has been modified to allow removal of a connection which hasn't been successfully established.

**Comment by afederigo** [comment]
I will try to solve this.

**Comment by Roasbeef** [comment]
Fixed by #171.
