### ISSUE TITLE
I tried to restore wallet from seed but channels were not restored. Is it ok?

### ISSUE THREAD

**Issue by Perlover** [lightningnetwork/lnd#1394]
### Background

I tried (in testnet) to use restore wallet from seed but channels were not restored. Is it ok? I don't see any documentation about backups & restoring but i had read issue closed tickets and i think it should work from seed because keys of channels are deterministic from seed. And data loss feature is there already (without anouncing to nodes)

### Your environment

* version of `lnd` **0.4.2-beta commit=7cf5ebe2650b67...1f1d6e19**
* which operating system (`uname -a` on *Nix) CentOS 6.\*
* version of `bitcoind` - 0.16.0
* any other relevant environment details

### Steps to reproduce

1. I have node_1 at IP_1 with opened channels
2. Shutdown node_1
3. We should have node_2 with same version of lnd, not to be run and IP_2 (different IP)
4. To run bitcoind @ node_2 and wait of syncing with blockchain
5. To run first time the lnd. I do `lncli create`. It was asked: i have seed or nor. I enter seed of node_1 and password of seed
6. After i see in logs:

        Wallet recovery mode enabled with address lookahead of 250 addresses
        ...
        RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=250

### Expected behaviour

I wanted to see opened all channels. 

I think that this is a working situation, when node changes IP and/or port. The main ID of node is public key. When i shut down node_1 and ran node_2 other nodes in the lightning network should anounce new IP (and may be port) and third party nodes with opened channels should reconnect after this.

### Actual behaviour

I saw that public key of node is same. walletbalance has non-zero value. But after lnd running 24 hours already i didn't see any old opened channels. The channelbalance was zero too.

After i shut down node_2 and ran node_1 again. Now the node_1 has same opened channels which had before shutting  down.

I didn't do it with same IP because i didn't want to make and restore binnary files. I think that this is a working situation, when node changes IP and/or port. The main ID of node is public key. When i shut down node_1 and ran node_2 other nodes in the lightning network should anounce new IP (and may be port) and third party nodes with opened channels should reconnect after this. But it doesn't happen.

**Comment by Perlover** [comment]
Only binary (wallet.db & channel.db files?) method?

**Comment by halseth** [comment]
> Only binary (wallet.db & channel.db files?) method?

?

**Comment by Perlover** [comment]
My question was: if now the seed restore for channel not realised - have i only way to backup binary files?

    $datadir/chain/bitcoin/mainnet/wallet.db
    $datadir/graph/mainnet/channel.db

Right? Or it will not help to restore LN node?

**Comment by halseth** [comment]
Yeah, but if the binary files is not the latest state, you risk that using them might be considered a channel breach.

**Comment by Perlover** [comment]
> you risk that using them might be considered a channel breach.

Yes, i know it (_Breach Remedy_ transaction from other side of channel).
I hope that the seed restoring for channel will be realized soon.

**Comment by Roasbeef** [comment]
You must understand that channels are stateful. You need the seed _plus_ the state.

**Comment by brandoncurtis** [comment]
@Roasbeef if wallet.db and channel.db are _continuously_ backed up, should that be sufficient to restore channel balances in the event of a failure?  Would backing these up properly require stopping `lnd`?

**Comment by vindard** [comment]
@brandoncurtis my understanding is that it isn't since there could be data that's stored in memory and not written to those db files immediately once `lnd` is running. 

(It's why I always shut down `lnd` before doing any major moves/backups of my .lnd directory... not the most ideal state of things right now)
