### ISSUE TITLE
"lncli newaddress np2wkh" returns Z address not an M address for Litecoin

### ISSUE THREAD

**Issue by ecurrencyhodler** [lightningnetwork/lnd#1397]
### Background

When creating a new address with `lncli newaddress np2wkh`, it returns a Z address not an M address for Litecoin. 

### Your environment

* version of `lnd`- 0.4.2-beta
* which operating system (`uname -a` on *Nix) - MAC
* version of `btcd`, `bitcoind`, or other backend - Litecoind

**Comment by windsok** [comment]
I can confirm that I also have this issue when generating a np2wkh address on litecoin mainnet with litecoind

**Comment by ErikEk** [comment]
I'll give it a try.

**Comment by windsok** [comment]
I believe this PR is meant to fix it, though i've not yet tested myself - https://github.com/lightningnetwork/lnd/pull/1489

**Comment by ErikEk** [comment]
After what I've tested that seems to be the issue.

**Comment by ErikEk** [comment]
It seems the issue is not just the netID, from what I've seen. I've made this change but still can't send (from litcoind) any funds to freshly generated addresses (lncli newaddress np2wkh).
@windsok Can you?

**Comment by ErikEk** [comment]
I've changed the netID and it seems to fix it.

**Comment by windsok** [comment]
ping @wangxinxi

**Comment by windsok** [comment]
Is the netID change you describe in addition to https://github.com/ltcsuite/ltcd/pull/8/files ?

**Comment by ErikEk** [comment]
It's exactly the same fix.
