### ISSUE TITLE
low CLTV creates routing errors

### ISSUE THREAD

**Issue by leishman** [lightningnetwork/lnd#1398]
### Background

Here is a link to the slack convo for reference, but I will summarize below: https://lightningcommunity.slack.com/archives/C6BKD3RKR/p1529106498000126

I had set my `time_lock_delta` setting to 4 (from the 144 default) using `lncli updatechanpolicy`. I do not remember if I was able to successfully make payments with this setting, but I think I was. A few days later I tried to pay `satoshis.place` which I had previously done successfully many times. However, payments began to fail with the following error:
```
{
        "payment_error": "unable to route payment to destination: IncorrectCltvExpiry(expiry=527800, update=(lnwire.ChannelUpdate) {
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  c0 4e ad f5 99 78 70 de  62 47 eb e4 2b 54 03 51  |.N...xp.bG..+T.Q|
  00000010  c3 44 c6 9f 0c 96 c4 66  8d e8 fa c2 ac c3 07 a8  |.D.....f........|
  00000020  12 cc a0 1b 07 bc c5 67  b5 f2 48 5a 72 7d 3c 10  |.......g..HZr}\u003c.|
  00000030  54 35 99 a0 2c c5 68 14  b7 c2 0d 86 ce 2a 7c c7  |T5..,.h......*|.|
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
 ShortChannelID: (lnwire.ShortChannelID) 527196:849:1,
 Timestamp: (uint32) 1529018851,
 Flags: (lnwire.ChanUpdateFlag) 0,
 TimeLockDelta: (uint16) 4,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
 BaseFee: (uint32) 0,
 FeeRate: (uint32) 1
}
",
        "payment_preimage": "",
        "payment_route": null
}
```

Upon attempting to pay the same invoice a second time, the following error would occur:

```
{
        "payment_error": "unable to find a path to destination",
        "payment_preimage": "",
        "payment_route": null
}
```

After running `updatechanpolicy` again payments still failed with the "unable to find a path to destination" error for a few minutes and then began to succeed.

### Your environment
`lnd version 0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc`
`Linux 4.4.0-1052-aws #61-Ubuntu SM`
Bitcoind backend

### Steps to reproduce

See description

### Expected behaviour

Payment should occur or understandable error should be reported. 

### Actual behaviour

CLTV error described was given however it seems that this shouldn't have happened given other routes were available but seemingly not attempted.

Read the slack thread for some additional context

**Comment by halseth** [comment]
@leishman Any possibility you've got from when this happened, or that you can repro and capture logs? I'm wondering if you did the fee update, but then it wasn't properly updated for you own channels...

Do you know if  `ShortChannelID: (lnwire.ShortChannelID) 527196:849:1` is your channel?
