### ISSUE TITLE
Openchannel fails - rpc error: code = Code(189) desc = You gave bad parameters:Unknown chain-hash

### ISSUE THREAD

**Issue by BobleChinois** [lightningnetwork/lnd#1403]
### Background

I can't open a channel with node 02dd4cef0192611bc34cd1c3a0a7eb0f381e7229aa3309ae961a7fc0076b4d2bb6@35.198.136.5:9735. 
I tried other node and could open a channel.

### Your environment

* version of `lnd` : "0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc"
* which operating system : Linux Celeri 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `bitcoind` : "version": 160000,
  "subversion": "/Satoshi:0.16.0/",
  "protocolversion": 70015,

### Steps to reproduce

Bitcoind is synced and running. Lnd idem.
``Connect 02dd4cef0192611bc34cd1c3a0a7eb0f381e7229aa3309ae961a7fc0076b4d2bb6@35.198.136.5:9735`` ==> OK
``openchannel 02dd4cef0192611bc34cd1c3a0a7eb0f381e7229aa3309ae961a7fc0076b4d2bb6 50000`` ==> failure

### Expected behaviour

Opening a channel with the said node and local amount of 50000 sat.

### Actual behaviour

Got this message : ``[lncli] rpc error: code = Code(189) desc = You gave bad parameters:Unknown chain-hash 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f``

**Comment by Roasbeef** [comment]
That means you're on say testnet, but trying to connect to mainnet. Make sure you're on the same chain as the node you're trying to connect to.
