### ISSUE TITLE
lnd --lnddir=xxx not working properly with configuration file

### ISSUE THREAD

**Issue by zx9r** [lightningnetwork/lnd#1406]
### Background

When starting lnd with parameter --lnddir=somedir, the config file is read from ~/.lnd/lnd.conf instead of reading from somedir/lnd.conf

At the moment you have to specify also --configfile to read the config file from another directory or a config file with other filename

### Your environment

* version of `lnd`: "0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"
* which operating system (`uname -a` on *Nix): Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

### Steps to reproduce

lnd --lnddir=/home/bitcoin/.lnd_testnet

### Expected behaviour

Should take config file from /home/bitcoin/.lnd_testnet/lnd.conf

### Actual behaviour

It takes the config file from /home/bitcoin/.lnd/lnd.conf

**Comment by orbitalturtle** [comment]
I'll work on this.

**Comment by yaslama** [comment]
@orbitalturtle Sorry :) But I needed it..
