### ISSUE TITLE
node_announcements are sent in format violation of BOLT 7

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lnd#1407]
BOLT 7 states:
"The origin node:...MUST NOT include more than one address descriptor of the same type.", however, lnd happily relays along such node announcements (see, eg, the node with alias "BallLightning" which has two IPv4 entires).

**Comment by githorray** [comment]
```
$ lncli getnodeinfo 02b813dcf53442e2ba8ac0b7911dc31ab0b62fda5e55b30388efb6c39a8ee54d3c
{
    "node": {
        "last_update": 1523630651,
        "pub_key": "02b813dcf53442e2ba8ac0b7911dc31ab0b62fda5e55b30388efb6c39a8ee54d3c",
        "alias": "BallLightning",
        "addresses": [
            {
                "network": "tcp",
                "addr": "76.93.137.43:9735"
            },
            {
                "network": "tcp",
                "addr": "76.176.5.137:9735"
            }
        ],
        "color": "#ff0000"
    },
    "num_channels": 1,
    "total_capacity": "200000"
}
```

**Comment by Saibato** [comment]
@Roasbeef @TheBlueMatt 
I think about to change the following line in BOLT-7
MUST NOT include more than 21 `address descriptor`.
https://github.com/lightningnetwork/lightning-rfc/commit/2719d878d4c585e6684db48fd7a5dbccb5d0fba7

**Comment by Roasbeef** [comment]
Based on the above and my reading of the current spec, it seems this is allowed.
