### ISSUE TITLE
REST unlockwallet command seems to be unavailable

### ISSUE THREAD

**Issue by robclark56** [lightningnetwork/lnd#1408]
### Background

Calls to REST /v1/unlockwallet return  `Not Found`

### Your environment

* version of `lnd`
V0.4.2

* which operating system (`uname -a` on *Nix)
Linux RaspiBolt 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
Hardware = 64 bit
OS = 32 bit

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.16.0

* any other relevant environment details
Environment is 
https://github.com/Stadicus/guides/blob/master/raspibolt/README.md

## Using this as a reference: ##
https://app.swaggerhub.com/apis/lnd-rest/rpc-proto/master

### Steps to reproduce
Run the following from the bash cli on the LND localhost.

Note: Tried submitting POST params in both formats

* POST application/x-www-form-urlencoded   (= default) & 
* POST application/json

```
admin ~  ฿  sudo curl --insecure  -X POST --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000  /home/admin/.lnd/admin.macaroon)"   --data "wallet_password=$(echo MyTestPassword | base64)"  https://192.168.0.141:8081/v1/unlockwallet

Not Found

admin ~  ฿  sudo curl --insecure  -X POST --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000  /home/admin/.lnd/admin.macaroon)"   --data "{\"wallet_password\":\"$(echo MyTestPassword | base64)\"}"  --header "Content-Type: application/json" https://192.168.0.141:8081/v1/unlockwallet
Not Found

```

### Expected behaviour
If wallet Locked => Wallet is unlocked
If wallet Unlocked => 'Wallet is already unlocked'

### Actual behaviour
Get 'Not Found' .... implying REST does not recognize the unlockwallet command

### Useful curl cheatsheet
https://gist.github.com/subfuzion/08c5d85437d5d4f00e58

### Other REST calls work OK
eg `/v1/getinfo`

```
admin ~  ฿  sudo curl --insecure   --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000  /home/admin/.lnd/admin.macaroon)"     https://192.168.0.141:8081/v1/getinfo     

  {"identity_pubkey":"02487eee34c34792d234ef39c050555fa44835a33689ffc3013db4de9a0bac3a9f","alias":"SWIFT.connect","num_active_channels":8,"num_peers":14,"block_height":1325646,"block_hash":"0000000000018d0276b97860e399431e3ff287ddf9c3281436b24d5aeee94192","synced_to_chain":true,"testnet":true,"chains":["bitcoin"],"uris":["02487eee34c34792d234ef39c050555fa44835a33689ffc3013db4de9a0bac3a9f@58.6.87.18:19735"],"best_header_timestamp":"1529208415","version":"0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"}
```

**Comment by Roasbeef** [comment]
If you've already started the daemon, then you don't need to hit unlock wallet. If you started with `--noencryptwallet` (which you definitely _should not_ on mainnet), then the unlocker service won't start up at all. Once you've unlocked the wallet, then the service is no longer needed, as the wallet is already unlocked.

**Comment by robclark56** [comment]
Roasbeef: Understand what you are saying, but

1. Did not start with --noencryptwallet
1. Process followed was:
  * Stop lnd
  * start lnd
  * issue REST unlockwallet command while wallet was locked
  * get 'Not Found' 

Surely REST unlockwallet would be expected to respond in this case?

Rob

**Comment by robclark56** [comment]
Hangon ..... eat my words .... think I see my mistake

:-(

**Comment by phillyfan1138** [comment]
As a follow on to this...is there a reason that I can't make an HTTP request for several seconds after unlocking the wallet?
