### ISSUE TITLE
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus

### ISSUE THREAD

**Issue by Amiga500** [lightningnetwork/lnd#1409]
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus.

![raspibolt_memory](https://user-images.githubusercontent.com/16525337/41505743-66b2828a-720f-11e8-9492-a4853f4911d8.png)

**Comment by Roasbeef** [comment]
Thanks!
