### ISSUE TITLE
Ensure the connmgr doesn't attempt to establish connections based off of incoming connection info

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#141]
Currently, if we receive an incoming connection, then the port we store in the database for the IP address that made that incoming connection is the port the TCP connection was assigned to after the initial handshake completed. Upon boot (if we later establish a channel with that node), the daemon will then tell the `connmgr` to establish a persistent connection to that peer, however the connection will fail indefinitely as it's attempting to use the non-default TCP port. 

The logic around establishing persistent connections should be modified to instead store the _advertise_   IP+port information within the peer's `NodeAnnouncement` rather than the information we obtain upon connection.

**Comment by shravan-shandilya** [comment]
@Roasbeef Will try to solve this.

**Comment by Roasbeef** [comment]
Closed by #154.
