### ISSUE TITLE
Problem with Golang installation documentation for Linux

### ISSUE THREAD

**Issue by superquest** [lightningnetwork/lnd#1411]
### Background

[The instructions to install golang](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#preliminaries) fail for me

### Your environment

* version of `lnd`
NA

* which operating system (`uname -a` on *Nix)
Linux thundroid 4.14.47-132 #1 SMP PREEMPT Sun Jun 3 22:33:16 UTC 2018 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
NA

* any other relevant environment details
(following along with [this tutorial](https://medium.com/@stadicus/perfect-low-cost-%EF%B8%8Flightning%EF%B8%8F-node-4c2f42a4ff7b))

### Steps to reproduce
`apt` can't find the `golang-1.10-go` package:

```
admin@thundroid:~/download$ sudo apt-get install golang-1.10-go
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package golang-1.10-go
E: Couldn't find any package by glob 'golang-1.10-go'
E: Couldn't find any package by regex 'golang-1.10-go'
```

I fixed by adding the `ppa:gophers/archive` according to [golang wiki instructions](https://github.com/golang/go/wiki/Ubuntu):

```
$ sudo add-apt-repository ppa:gophers/archive
$ sudo apt-get update
$ sudo apt-get install golang-1.10-go
```

### Expected behaviour

Install golang

### Actual behaviour

Doesn't install golang

**Comment by Roasbeef** [comment]
Well it depends on your distro. We also link _directly_ to the official golang instructions as well, as a fall back, as some distros may not have that proper pacakge.

**Comment by Exision87** [comment]
I ran into the same problem:

Me:~$ sudo apt-get install golang-1.11-go
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package golang-1.11-go
E: Couldn't find any package by glob 'golang-1.11-go'
E: Couldn't find any package by regex 'golang-1.11-go'

And would suggest to replace the [guide](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) with

$ sudo apt-get install golang-go

as per [golang wiki](https://github.com/golang/go/wiki/Ubuntu)

**Comment by Roasbeef** [comment]
The reason we don't use that command is that is isn't guaranteed to install the _latest_ version of Go which we currently require.

**Comment by 335iguy** [comment]
It's still clearly in the install instructions to type in the command as-is. It should be changed to reflect that you have to do something more than just that. Makes it easy for newbies.

**Comment by karma-pete** [comment]
Thank you this helped me on my Ubuntu install
