### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by mecampbellsoup** [lightningnetwork/lnd#1414]
### Background

I can no longer `make && make install` because the `dep` build tool dependency is not found.

### Your environment

* short SHA `fc658dbf`
* Darwin MEC-MBP.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
* 0.16.0 bitcoind

### Expected behaviour

Should build the tip of my local git branch.

### Actual behaviour

```
λ MEC-MBP lnd → λ git master* → pwd
/Users/mec/go/src/github.com/lightningnetwork/lnd
λ MEC-MBP lnd → λ git master* → make && make install
 Compiling dependencies.
dep ensure -v
make: dep: No such file or directory
make: *** [dep] Error 1
```

**Comment by Roasbeef** [comment]
This isn't an issue with the build. This is an issue with your local environment. You don't have dep installed, or it isn't found in your path.

**Comment by mecampbellsoup** [comment]
Well according to the install instructions, `dep` is supposed to be installed via `make`... 

![image](https://user-images.githubusercontent.com/2043821/41540485-5daa17e6-72de-11e8-823f-aaa1e499c4ff.png)

**Comment by Roasbeef** [comment]
Yep, but if your $PATH isn't set up properly, this it won't be picked up.

**Comment by mecampbellsoup** [comment]
I thought the behavior is that `make` installs `dep`, which should Just Work ™️ as long as `go` and `$GOPATH` are properly set, correct?

**Comment by Roasbeef** [comment]
Yes, but if `make` execute (and you see in installing dep), then that would mean that your path is messed up somehow. Evidence that this is the case is the passing build: https://travis-ci.org/lightningnetwork/lnd/builds/393621878. Travis starts as a blank state, and we use the make file to install all the required dependancies.
