### ISSUE TITLE
Manual connect during chain sync prevents channel from becoming active

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#1420]
### Background

If a manual connection (`lncli connect`) to a peer with a channel is made after lnd has started but before it has caught up to the chain backend, the channel will remain inactive even after sync is complete. Other channels have connections established and become active automatically once chain sync is complete.

### Your environment

* 0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc
* Linux instance-1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
* bitcoind 0.16.1

### Steps to reproduce

1. Open a channel in lnd
2. Shutdown lnd and let it stay offline for at least a few hours.
3. Start lnd, as soon as the grpc server becomes available (before chain sync is complete), run `lncli connect` to the peer node with which you made the channel in step 1.
4. The channel will remain inactive and stay that way even after the chain sync is complete.

I started up an lnd instance that had been offline for some time When coming online, it needed to catch up to the latest blocks. During this time, lnd had no active channels and no connections. I was impatient and wanted to try to make a payment right away, so I manually connected to a peer I had a channel with and tried to pay that peer. The payment failed because the channel was still inactive. `listpeers` showed my connection to that peer.

I waited for the chain sync to complete, and when it did it connected to all peers with which I had channels, and all those channels became active. However, the channel with the peer with whom I had manually connected to earlier remained inactive and stayed that way. Payment to the peer would fail. Attempts to reconnect/disconnect to the peer failed as well:

```bash
lncli disconnect 026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115
[lncli] rpc error: code = Unknown desc = cannot disconnect from peer(026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115), all active channels with the peer need to be closed first

lncli connect 026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115@34.237.245.216:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 34.237.245.216:9735
```

Restarting lnd and waiting for the connections to happen automatically resolved this issue and the channel above became active.

From looking through the code and `peer.go` a bit, it looks like the cause might be that existing channels are only activated when a connection to a peer is established. If the channel can't become active during chain sync, then it remains inactive and since the connection is not reestablished after chain sync, it stays that way. 

### Expected behaviour

After chain sync on startup, channels to peers with which we already have connections should become active. Alternatively, connections should not be allowed during startup chain sync.

### Actual behaviour

Channels to peers with which we already have connections do not become active on completion of startup chain sync.

**Comment by Roasbeef** [comment]
> If a manual connection (lncli connect) to a peer with a channel is made after lnd has started but before it has caught up to the chain backend, the channel will remain inactive even after sync is complete. 

You shouldn't be able to to a manual connection, as the server isn't started up _before_ the initial chain is actually synced. Peer connections won't succeed as well as the listening server hasn't been started up as well. Channels are only added to switch once a peer is connected, as before that it doesn't actually matter. 

On being active: a channel is only active once the channel is "eligible to forward". This means connected, but also once they've sent the `FundingLocked` message. If they haven't sent this (for w/e reason), then the channel won't become active.

**Comment by Roasbeef** [comment]
What did the logs w/ this peer show at the time as well?

**Comment by sangaman** [comment]
Here's the logs from the rescan, you can see that the gRPC server started listening while the rescan was going on. I figure that's why I was able to do `lncli connect`. The logs don't show the manual connection happening, I figure my logging level isn't low enough.

```bash
2018-06-19 01:48:06.861 [INF] LNWL: Started rescan from block 00000000000000000038ee6ab784d62ae7654900960f2e26ef689fe4751ae144 (height 528059) for 141 addresses
2018-06-19 01:48:07.099 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2018-06-19 01:48:07.100 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2018-06-19 01:48:07.103 [INF] LNWL: Starting rescan from block 00000000000000000038ee6ab784d62ae7654900960f2e26ef689fe4751ae144
2018-06-19 01:48:07.801 [INF] LTND: Waiting for chain backend to finish sync, start_height=528149
2018-06-19 02:01:58.018 [INF] LNWL: Rescan finished at 528149 (00000000000000000009381e7024d7385c514dc1f1c662760b66df532b5a9867)
2018-06-19 02:01:58.036 [INF] LNWL: Catching up block hashes to height 528149, this might take a while
2018-06-19 02:01:58.038 [INF] LNWL: Done catching up block hashes
2018-06-19 02:01:58.039 [INF] LNWL: Finished rescan for 141 addresses (synced to block 00000000000000000009381e7024d7385c514dc1f1c662760b66df532b5a9867, height 528149)
2018-06-19 02:01:59.090 [INF] LTND: Chain backend is fully synced (end_height=528149)!
```

Regarding `FundingLocked`, I found this:

```bash
2018-06-19 02:02:05.349 [ERR] SRVR: unable to send message to 026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115, peer is not connected
2018-06-19 02:02:05.350 [WRN] FNDG: unable to send fundingLocked to peer 026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115: peer is not connected. Will retry when online
```

So it's saying I'm not connected to peer `026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115`, however I did have a connection according to `listpeers`. You can also see from my first post that if I tried to connect to that peer again manually, I got a message saying I was already connected:

```bash
lncli connect 026a9cb86ff60b1f2eb8cc44068451266b8ad54a935db72762ca3484f9d73c3115@34.237.245.216:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 34.237.245.216:9735
```

**Comment by Roasbeef** [comment]
Yes the peer wasn't connected, so we weren't able to send the funding locked message to the remote peer. 

If we connect, but then the peer disconnects before funding locked is exchanged, then there may have been a gap where we were connected, but the remote peer wasn't processing this message, so we couldn't continue w/ the process of the channel becoming active. 

Until both sides send/recv the funding locked message. The channel cannot become active.

**Comment by Roasbeef** [comment]
Your issue is that the remote peer isn't sending the channel sync message for some reason. Logs show that `lnd` is doing everything correctly. If the remote peer isn't responsive, then you'll have to close out the channel. When you try to close cooperatively, it disconnects.

**Comment by jpentland** [comment]
Executing the following command:
```
lncli closechannel f5e7d14cf065071d7502a07bc102446e9c180ec70847e3cc61ef27826cc4adac --output_index 1 --force --sat_per_byte 150
```

Results in lncli blocking indefinitely, and the following on the log:
```
2018-07-17 08:31:32.396 [INF] HSWC: Removing channel link with ChannelID(acadc46c8227ef61cce34708c70e189c6e4402c17ba002751d0765f04cd1e7f4)
2018-07-17 08:31:32.396 [INF] CNCT: Attempting to force close ChannelPoint(f5e7d14cf065071d7502a07bc102446e9c180ec70847e3cc61ef27826cc4adac:1)
```

But no more information regarding the progress. I don't see any evidence that a commitment TX was sent to the p2p network.
