### ISSUE TITLE
Cannot get list of unconfirmed transactions via RPC

### ISSUE THREAD

**Issue by neogeno** [lightningnetwork/lnd#1422]
### Background

Accessing the LND API via GRPC, you can use GetTransactions to list all on-chain transactions but if there are any pending unconfirmed transactions, that are related to my wallet, they will be invisible until they are confirmed.

I see that in the go source code here there is a function that can do this if we specify 0 confirmations, but it is not exposed to the RPC.  

https://github.com/lightningnetwork/lnd/blob/cd8a21c4b829def9bf317a1a9b42f07e36b5891c/lnwallet/btcwallet/btcwallet.go#L221

### Your environment

* version of `lnd` 0.42
* which operating system (`uname -a` on *Nix) Linux
* version of `btcd`, `bitcoind`, or other backend btcd 0.12

**Comment by Roasbeef** [comment]
It depends what backend you're using. Neutrino for example, doesn't see unconfirmed transactions. 

As you can see from this fragment: https://github.com/lightningnetwork/lnd/blob/cd8a21c4b829def9bf317a1a9b42f07e36b5891c/lnwallet/btcwallet/btcwallet.go#L573

We display both confirmed and unconfirmed transactions that the wallet knows of.

**Comment by neogeno** [comment]
I am not using Neutrino it’s a full LND node syncing with btcd but cannot see any unconfirmed transactions, although they do appear as incoming subscription events from subscribeTransactions. Often, however my node will be offline and thus I won’t know about the transaction until it’s confirmed.

**Comment by neogeno** [comment]
Confirmed This happens on lnd version 0.4.2-beta commit=d98d4523e10426c4ce097ecc7ec1ba199a331c60

**Comment by wpaulino** [comment]
What should probably be done here is to introduce a more robust streaming notification delivery for `SubscribeTransactions` and possible the other streaming RPCs like how #1125 does.

**Comment by neogeno** [comment]
The robust notifications are good idea for all subscriptions. But why does manually invoking the getTransactions RPC command not show the unconfirmed chain transactions, when according to the code, it should?

**Comment by Roasbeef** [comment]
Related to #1501.

**Comment by neogeno** [comment]
Just to clarify, I am reporting this issue in a configuration that DOES NOT use neutrino.
