### ISSUE TITLE
max message payload is too big

### ISSUE THREAD

**Issue by mntetai** [lightningnetwork/lnd#1423]
### Background
I have installed roastbeefs btcd fork on win 10 pro( 64) .
 

When running lnd I can not connect to btcd running local host. 
### Your environment
Windows 10 pro
* version of `lnd`
https://github.com/lightningnetwork/lnd/commit/e30f8694f02869d5f7d3cf49190d1d37d5b29000

* version of `btcd`, `bitcoind`, or other backend
https://github.com/Roasbeef/btcd/commit/a03db407e40d3b66ea29984263bbc8bf4d2f04c4

### Steps to reproduce
Install zap-desktop from github , install btcd from git hub

### Expected behaviour

zap-desktop should run and connect to local btcd

### Actual behaviour

zap-desktop can not connect to local btcd

### error seen in logs
`09:10:46 2018-06-20 [ERR] PEER: Can't read message from [::1]:52916 (inbound): ReadMessage: message payload is too large - header indicates 1936672778 bytes, but max message payload is 33554432 bytes.`

**Comment by Roasbeef** [comment]
This isn't lnd. You're trying to connect to the wrong port perhaps. The message you see is from a connect _peer_. `lnd` connects to the _RPC_ interface.
