### ISSUE TITLE
< "synced_to_chain": false > with bitcoin.regtest=1

### ISSUE THREAD

**Issue by gdassori** [lightningnetwork/lnd#1424]
### Background

LND+bitcoind goes out of sync until restarted (regtest).

### Your environment

* "version": "0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc"
* Linux lnd_node_1 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.0
* I'm using two docker containers, one for lnd, one for bitcoind

Config file:
```

[Bitcoin]
bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=bitcoinrpc
bitcoind.rpcpass=bitcoinrpcpassword
bitcoind.zmqpath=tcp://bitcoind_host:50001
bitcoind.rpchost=bitcoind_host
```

### Steps to reproduce
```
- start bitcoind in regtest
- start lnd

- $ lncli getinfo
- $ bitcoin-cli generate 1
- $ lncli newaddress np2wkh
- $ bitcoin-cli sendtoaddress <generated address> 1
- $ bitcoin-cli generate 6
- $ lncli getinfo
- $ lncli listchaintxns
```
### Expected behaviour

synced_to_chain should be true
block_hash should change
block_height should increase
best_header_timestamp should increase
transactions list should be up-to-date with the new incoming transaction

### Actual behaviour

synced_to_chain is *false*
block_hash changes according to bitcoind
block_height changes according to bitcoind
best_header_timestamp is the same as 6 blocks ago
transactions is empty

**Comment by Roasbeef** [comment]
Is this a local node or a remote node? Ensure that before your start to generate those blocks, that `lnd` is actually connected to and receiving notifications from `bitcoind`. Also ensure that you already have `bitcoind` compiled w/ `zmq`.

**Comment by gdassori** [comment]
Hi, my first issue here, I take the chance to congrat for your work.

Going back on the topic, I'm not 100% sure ZMQ worked properly for the entire test, and actually a docker cluster can make connections between containers rather unstable, so I may and expect to have an unstable zmq connection at any moment. 

Is it zmq, atm, the only way to keep lnd in sync with bitcoind? No fallback on the RPC API is available when zmq is not responsive? 

Can I expect lnd to recover at some point in the future, or once a block notification via zmq is lost, lnd will be out of sync forever until restarted?

Thanks for your support.

**Comment by gdassori** [comment]
Ok, I confirm there was a lack on zmq configuration, I published only hashed data, and not raw. 
Once set zmqpubrawblock & zmqpubrawtx, lnd started to sync.
