### ISSUE TITLE
Local_balance amount decreasing fast in open channels

### ISSUE THREAD

**Issue by BobleChinois** [lightningnetwork/lnd#1430]
### Background

Maybe this is silly I don't know, but I think there is something wrong with the commit_fee of 2 open channels of mine.
The amount of ``commit_fee`` feels huge, and it seems it is depleting my ``local_balance`` which is rapidly decreasing. 
It might not be a bug, maybe I did something wrong, but I can't figure it out. 

### Your environment

* ``lnd version 0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc``
* ``Linux Celeri 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux``
* ``"version": 160000,
  "subversion": "/Satoshi:0.16.0/",
  "protocolversion": 70015,``

### Steps to reproduce

I just happened to have 2 open channels with nodes : 
* ``02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637``
* ``02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b``

### Expected behaviour

As far as I know, the ``local_balance`` of a channel should be pretty stable if you don't use it, minus variation of ``commit_fee`` maybe ?

### Actual behaviour

The available amount to spend is falling very fast : 
* ``02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637`` : I funded 20000 sat (minus 153 sat fees) on the 16th of this month, made 1 payment of 264 fees, today local balance is only 3445
* ``02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b`` : I funded 79647 sat (minus 200 sat fees) on the 19th of this month, made no payment, today local balance is only 49963

Here are the ``listchannels`` output : 

> {

    "channels": [
        {
            "active": true,
            "remote_pubkey": "02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637",
            "channel_point": "f1d4726b33944bbcfbe0e9e3b18461675a1e40db21d3acce776ee364269a9bbf:0",
            "chan_id": "580769738400137216",
            "capacity": "79647",
            "local_balance": "49963",
            "remote_balance": "0",
            "commit_fee": "29684",
            "commit_weight": "600",
            "fee_per_kw": "41000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "16",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
            "channel_point": "ac8f2f0f77698a71e4ee35de89cedcf3fa64c6ae96685dd078ea084cc1eb1fd6:0",
            "chan_id": "580280455773945856",
            "capacity": "20000",
            "local_balance": "3445",
            "remote_balance": "264",
            "commit_fee": "16555",
            "commit_weight": "600",
            "fee_per_kw": "22500",
            "unsettled_balance": "0",
            "total_satoshis_sent": "264",
            "total_satoshis_received": "0",
            "num_updates": "23",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        }
    ]
}

**Comment by Roasbeef** [comment]
This is just the commitment fee being automatically adjusted. If you're on testnet, then fee estimation is a bit wonky, so you might have high-ish fees on your commitment transaction. For mainnet, the fee situation is a lot more realistic.

**Comment by BobleChinois** [comment]
Ok thanks, I just wanted to be sure I did nothing wrong. Was on mainnet btw.

**Comment by jrwagh333** [comment]
What exactly is the commitment fee? Can this be explained in more detail and can you adjust it manually?

**Comment by halseth** [comment]
@jrwagh333 It is just the fee used for the pre-signed commitment transactions. Cannot be set manually at this point.
