### ISSUE TITLE
Link rejects HTLCs that meet CLTV forwarding policy of outbound link but not inbound link

### ISSUE THREAD

**Issue by treygriffith** [lightningnetwork/lnd#1431]
### Background

When a single node's channels have diverse timelock delta forwarding policies (e.g. Channel A has a forwarding policy of 
```
{
  "timeLockDelta":130,
  "minHtlc":"1000",
  "feeBaseMsat":"0",
  "feeRateMilliMsat":"6"
}
```
and Channel B has a forwarding policy of
```
{
  "timeLockDelta":144,
  "minHtlc":"1000",
  "feeBaseMsat":"0",
  "feeRateMilliMsat":"6"
}
```
)

It rejects incoming HTLCs to forward that have enough timelock according to the outbound link's policies but not the inbound link's policies.

For example, if a route was forwarding through the node from Channel B to Channel A, and only had 130 of time lock delta, it would be rejected with the following error message:

```
2018-06-22 00:52:44.183 [ERR] HSWC: Incoming htlc(ec387ebcd20521ae17c81841020c488f7ec9ce10287856cd77cc24bed7633f53) has incorrect time-lock value: expected at least 144 block delta, got 130 block delta
```

### Your environment

* version of `lnd`: `0.4.2` commit `fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7`
* which operating system (`uname -a` on *Nix): Darwin Kernel Version 17.5.0
* version of `btcd`, `bitcoind`, or other backend: btcd commit `bc09449`
* any other relevant environment details

### Steps to reproduce
1. Create 3 Nodes, A, B, and C
2. Open a channel between A -> B, and B -> C
3. Set B's forwarding policy for A->B to a timelock delta of 100 (from the default of 144)
4. Send a payment from A to C.

### Expected behaviour

B should forward the HTLC on the basis of its forwarding policy for B->C, not it's forwarding policy for A->B.

I believe I've found the source of the issue in https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go :

Setting the `hopPolicy` from the inbound link
https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go#L2347

Using the `timeDelta` from the inbound link's `hopPolicy`
https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go#L2353

Using the inbound link's `timeDelta` to check against the outgoing cltv
https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go#L2354
https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go#L2386

This is similar to the fee issue that was fixed in #1019 wherein the fee was being measured against the incoming link's policy instead of the outgoing link. I suspect that since most nodes on the network use the same CLTV delta policy on all of their channels, this issue hasn't surfaced as broadly on mainnet.

This behavioral expectation also comes from the spec: https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message

Of course, if this is a misunderstanding of the spec, let me know.

### Actual behaviour

The forwarding node fails to forward with this error message:
```
2018-06-22 00:52:44.183 [ERR] HSWC: Incoming htlc(ec387ebcd20521ae17c81841020c488f7ec9ce10287856cd77cc24bed7633f53) has incorrect time-lock value: expected at least 144 block delta, got 130 block delta
```

The sending node receives a failed payment with:
`Attempt to send payment ec387ebcd20521ae17c81841020c488f7ec9ce10287856cd77cc24bed7633f53 failed: IncorrectCltvExpiry`

**Comment by treygriffith** [comment]
It also looks like there is a similar check on the exit hop:
https://github.com/lightningnetwork/lnd/blob/fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7/htlcswitch/link.go#L2212
which according to my read of the spec, forwarding policies shouldn't be referenced for non-forwarding scenarios.

This should mean (although I haven't tested it) that if you specify a `min_final_cltv_delta` of a smaller amount than the forwarding policy, this will reject it, although it should not.

**Comment by Roasbeef** [comment]
Related to #1398.

**Comment by Roasbeef** [comment]
Thanks for such a detailed issue! I'll have a PR up fixing the bulk of the issue (also a bug within the hop payload generation within the router, which propagated into the switch). With respect to that last comment, we'll need to also start to store the cltv delta used for the invoices in order to fully remedy it.
