### ISSUE TITLE
Unable to retrieve initial bootstrap peers (lnd 0.4.2-beta)

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#1434]
### Background

Just installed lnd (version 0.4.2-beta commit=18f17ad49b4cc58635a285e53441d82a0c54fd99) with a fresh data directory and I get this repeatedly:

Jun 23 14:23:46 x lnd[16819]: 2018-06-23 14:23:46.535 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]: lookup soa.nodes.lightning.directory on 213.186.33.99:53: server misbehaving
Jun 23 14:23:46 x lnd[16819]: 2018-06-23 14:23:46.535 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
Jun 23 14:23:46 x lnd[16819]: 2018-06-23 14:23:46.535 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph

### Your environment

lnd version 0.4.2-beta commit=18f17ad49b4cc58635a285e53441d82a0c54fd99
Debian Stretch
go version go1.9.4 linux/amd64

**Comment by jogc** [comment]
Seems it eventually found some peers. It took a long time though. Log was filled with these messages.

**Comment by Roasbeef** [comment]
Was doing some tweaks to the seed itself, and forgot to restart! It's back up now, will work on adding redundancy!
