### ISSUE TITLE
LND GRPC stream calls doesn't return some kind of confirmation

### ISSUE THREAD

**Issue by sezaru** [lightningnetwork/lnd#1445]
### Background

I'm creating an application using Elixir that needs to communicate with my local LND node, for the GRPC connection I'm using [GRPC-Elixir](https://github.com/tony612/grpc-elixir) library which works great except when I try to use the stream functions like the `subscribe_invoices` which will trigger a timeout.

I created an issue in the authors library github: [link](https://github.com/tony612/grpc-elixir/issues/56).

What the author found out is that, for example,  the `subscribe_invoices` call will not return anything from the LND server (until an invoice request happens obviously) and so the library thinks it didn't get the stream and timeout.

A proposed solution from him was to make the library simply wait forever with them stream opened, and that indeed fixed the issue, but it seemed to me like an workaround.

So my question is, is that the expected behavior? Every time I do a stream call to LND it will not return any message confirming the stream? Making the GRPC client wait forever (never timeout) is the correct way to handle that?

### Your environment

* LND 0.4.2
* Linux thunderpay1 4.15.0-22-generic Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind

**Comment by Roasbeef** [comment]
Sounds like an issue with the elixir lib. The streaming call only returns (atm) a response if a new invoice has been settled. There's a PR open to modify this to allow users to specify the last invoice ID they know of, and from there we'll send out a set of backlog notifications.
