### ISSUE TITLE
lncli: add extra confirmation dialogue to payinvoice+sendpayment

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1455]
Currently there's no easy way for a user to verify the integrity of a payment request they're about to pay, unless one first uses the `decodepayreq` method _each_ time before sending on the command line. It would be nice if this became the default, as since many users are new to the system, it's easy for a site to trick a user into paying a higher invoice. To avoid this, we should add a default mode where we _always_ display the invoice to the user for confirmation before attempting to pay the invoice. 

# Steps To Completion 

- [ ] Modify `payinvoice` and `sendpayment` to _always_ first call `DecodePayReq` with the payreq. The response of this should be displayed to the users w/ a confirmation dialogue w.r.t if we should proceed or not. 

- [ ] Add a `--force` (or `-f`) flag to both of these commands to skip the user verification

**Comment by rawtxapp** [comment]
Looks like a good first issue, can I take this ?

**Comment by githorray** [comment]
I always decode first. This will save a step. Great!

**Comment by tiero** [comment]
I can take it myself as well, since it can save on a my application half of the time (of course only if isn't going to take it `rawtxapp`, I'm ok with FIFO policy :D )
