### ISSUE TITLE
replace ChaCha20Poly1305 implementation

### ISSUE THREAD

**Issue by aead** [lightningnetwork/lnd#146]
I recommend to switch from my ChaCha20Poly1305 implementation to the "official" [golang](https://godoc.org/golang.org/x/crypto/chacha20poly1305) implementation.
I'm planning to restructure my repository (backward comp. breaking changes) in a few weeks and I don't want to break your build.
The golang implementation will also lead to a significant performance improvement on amd64 (caused by more specialized code), but will decrease the performance on 386 and probably on arm. But there's work in progress to solve this :smile:

**Comment by aead** [comment]
Sry, you use vendoring - so this has low priority

**Comment by Roasbeef** [comment]
Thanks for the heads up! We've moved over to the `crypto/x/chachapoly1305` library.
