### ISSUE TITLE
lncli addinvoice fails with "permission denied"

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#1465]
### Background
There are two issues here:
1. lncli addinvoice fails.
2. The error message given is not very helpful.

Here's the command that I ran:
./lncli addinvoice --amt 2000
[lncli] rpc error: code = Unknown desc = permission denied

I suspect that the failure might be related to me upgrading my version of lnd.

### Your environment

* version of `lnd`
lnd version 0.4.2-beta commit=7c2307984d38ed5a27f27798f30aacb619927454
* which operating system (`uname -a` on *Nix)
Raspbian
Linux 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.16.99.0-9b8b1079d
* any other relevant environment details

### Steps to reproduce
Unknown, but potentially something like the following:
1. Upgrade for lnd 0.4.1 to 0.4.2.
2. Run lncli addinvoice --amt 2000

### Expected behaviour

* A new invoice is generated.
* If a permissions error occurs, information about the resource in question is provided (e.g. the file path of the wrongly-permissioned file, so that the user can manually fix the permissions).

### Actual behaviour

* No invoice is generated.
* An error occurs.
* The error message is not helpful enough (does not include a file path, for example).

**Comment by Roasbeef** [comment]
You need to delete your old set of macaroons, as there's now a new `invoice.macaroon`.
