### ISSUE TITLE
Errors in REST API Reference

### ISSUE THREAD

**Issue by mschristiansen** [lightningnetwork/lnd#1466]
I'm busy writing a client library against the REST API. There is a few places where the reference is wrong e.g. `best_header_timestamp` in `/v1/getinfo` is supposed to be an `int64` but actually a `string`, some fields seem to be optional.

If the reference is generated from https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.swagger.json and this is a hand-written file then I'm happy to create a pull request to correct the issues that I find. Let me know.

**Comment by Roasbeef** [comment]
What reference are you referring to? That's just a set of swagger json docs. If you're actually getting json, many times it's the case that integers are encoded as strings, as JS doesn't have proper integers.

**Comment by Roasbeef** [comment]
Are you aware of https://api.lightning.community/rest/?

**Comment by mschristiansen** [comment]
That's the reference I am using and which is wrong. Was thinking it was generated from the swagger docs.

Assuming we want reference to match implementation and not the other way around. Want help fixing it?

**Comment by Roasbeef** [comment]
There's no need to fix it: it's JSON, integers are usually encoded as strings.

**Comment by Roasbeef** [comment]
Also the swagger file is automatically generated.

**Comment by mschristiansen** [comment]
`"1"` specified as type `<Int64>` instead of `<string>` is problematic for something that is supposed to be machine readable (even if in JSON). It should not take much effort to correct and I'm happy to do so, if I'm pointed in the right direction. I will close the issue, but feel free to leave a comment.

**Comment by wbobeirne** [comment]
I personally scratched my head at this as well, it seems that sometimes you get back numbers where you'd expect to remain small enough (e.g. `v1/getinfo`'s `numPeers`) but you get back strings for numbers you'd expect to get big (e.g. `v1/balance/blockchain`'s balance numbers).

It's great that this is done automatically as you'd expect, but it'd be even better if the documentation reflected that. Given that somewhere this conversion is happening explicitly, it'd be great to have this issue re-opened & the documentation corrected.

**Comment by mschristiansen** [comment]
I fully agree with you, but will leave it to one of the maintainers to reopen if acknowledged that it is an issue they care about.
