### ISSUE TITLE
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

### ISSUE THREAD

**Issue by andronoob** [lightningnetwork/lnd#1472]
### Background

LND cannot initialize with Litecoin Core

### Your environment

Windows 10 Pro 1803 x64
LND 0.4.1 AMD64
Litecoin Core 0.16.0 (litecoin-qt)

### Steps to reproduce

1.Edit `lnd.conf`, add `[Bitcoin]` and `[Litecoin]` section, set `bitcoin.active=0` and `litecoin.active=1`, save.
lnd.conf:
```
[Application Options]
debuglevel=info
debughtlc=true
maxpendingchannels=10
alias=LND
color=#ffffff

[Litecoin]
litecoin.active=1
litecoin.testnet=0
litecoin.mainnet=1
litecoin.node=litecoind
litecoind.dir="C:\\Users\\user\\AppData\\Roaming\\Litecoin"
litecoin.chaindir="C:\\Users\\user\\AppData\\Roaming\\Litecoin\\blocks"
litecoind.rpchost=127.0.0.1:59332
litecoind.rpcuser=user
litecoind.rpcpass=password
litecoind.zmqpath=tcp://127.0.0.1:19501
litecoin.basefee=0
autopilot.active=0

[Bitcoin]
bitcoin.active=0
bitcoin.testnet=0
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoind.dir="C:\\Users\\user\\AppData\\Roaming\\Bitcoin"
bitcoin.chaindir="C:\\Users\\user\\AppData\\Roaming\\Bitcoin\\blocks"
bitcoind.rpchost=127.0.0.1:8332
bitcoind.rpcuser=user
bitcoind.rpcpass=password
bitcoind.zmqpath=tcp://127.0.0.1:18501
bitcoin.basefee=0
autopilot.active=0
```
2.Start litecoin-qt, wait it to sync.
3.Try to start LND.

### Expected behaviour

LND should start without complaining.

### Actual behaviour

 *Sometimes* LND could start, *sometimes* it won't:
```
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)
```

**Comment by Roasbeef** [comment]
Are you setting the ` --litecoin.node` option?

**Comment by andronoob** [comment]
@Roasbeef 
Yes.
I've just updated the text, content of lnd.conf was added.

**Comment by Roasbeef** [comment]
Your config is invalid. You're mixing items within distinct namespaces. Ensure that they're properly partitioned. Another approach is to add items on by one, then you'll see which one is incorrect.

**Comment by andronoob** [comment]
@Roasbeef 
I expected that LND's behaviour should be *deterministic*. Actually, LND *probabilistically* fails to start.

**Comment by Roasbeef** [comment]
Follow my instructions and you'll find where you've created an invalid
config.

On Jun 29, 2018 6:48 PM, "andronoob" <notifications@github.com> wrote:

@Roasbeef <https://github.com/Roasbeef>
I expected that LND's behaviour should be *deterministic*. Actually, LND
*probabilistically* fails to start.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1472#issuecomment-401509378>,
or mute the thread

**Comment by andronoob** [comment]
@Roasbeef 
Thanks. I think I've fixed my config file.
But, I'm still confused. I expected that LND should always refuse to start with a invalid config file. Actually, sometimes LND starts, sometimes it won't.

lnd.conf:
```
[Application Options]
debuglevel=info
debughtlc=true
maxpendingchannels=10
alias=LND
color=#ffffff

[Litecoin]
litecoin.active=1
litecoin.testnet=0
litecoin.mainnet=1
litecoin.node=litecoind
litecoin.chaindir="C:\\Users\\user\\AppData\\Roaming\\Litecoin\\blocks"
litecoin.basefee=0

[Litecoind]
litecoind.dir="C:\\Users\\user\\AppData\\Roaming\\Litecoin"
litecoind.rpchost=127.0.0.1:59332
litecoind.rpcuser=username
litecoind.rpcpass=password
litecoind.zmqpath=tcp://127.0.0.1:19501

[Bitcoin]
bitcoin.active=0
bitcoin.testnet=0
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.chaindir="C:\\Users\\user\\AppData\\Roaming\\Bitcoin\\blocks"
bitcoin.basefee=0

[Bitcoind]
bitcoind.dir="C:\\Users\\user\\AppData\\Roaming\\Bitcoin"
bitcoind.rpchost=127.0.0.1:8332
bitcoind.rpcuser=username
bitcoind.rpcpass=password
bitcoind.zmqpath=tcp://127.0.0.1:18501

[autopilot]
autopilot.active=0
```

**Comment by offerm** [comment]
@andronoob  do you still face startup problems after fixing the config file?

**Comment by andronoob** [comment]
@offerm The problem was already resolved after fixing config file.

**Comment by mariogintili** [comment]
I'm having this issue to, off a fresh untar of this release https://github.com/lightningnetwork/lnd/releases/tag/v0.15.0-beta

**Comment by guggero** [comment]
It sounds like your `lnd.conf` isn't found by `lnd`.

**Comment by mariogintili** [comment]
thanks! @guggero I've opened #6817 - I'll explore that avenue and comment there
