### ISSUE TITLE
unable to fetch chan info: no chan info found

### ISSUE THREAD

**Issue by cryptagoras** [lightningnetwork/lnd#1476]
### Background

lnd crashes on startup (I use the latest commit 076fc712619ca4b6ee518c7ab4c263cbae51108e)
```
2018-06-29 21:16:43.939 [INF] LTND: LightningWallet opened
2018-06-29 21:16:44.070 [INF] HSWC: Restoring in-memory circuit state from disk
2018-06-29 21:16:44.745 [INF] HSWC: Payment circuits loaded: num_pending=2531, num_open=128
2018-06-29 21:16:44.789 [ERR] SRVR: unable to create server: unable to read channel for chain_hash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000, node_key=02e9fa6b495d07ce19796b0
6b5c0f51a401dbb48935c3aafe54067c89299add0ed: unable to read channel data for chan_point=50ed4f4099d9b197d12917bf9694e6417b526b919e9cb80454a414fff9d39395:0: unable to fetch chan info: no chan info found
2018-06-29 21:16:44.789 [INF] LTND: Shutdown complete
unable to read channel for chain_hash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000, node_key=02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed: unable to read channel data for chan_point=50ed4f4099d9b197d12917bf9694e6417b526b919e9cb80454a414fff9d39395:0: unable to fetch chan info: no chan info found
```

### Your environment

* version of `lnd`
076fc712619ca4b6ee518c7ab4c263cbae51108e currently
fc658dbf6043951f6ba8b8e86f4e67bc903cf6b7 previously
* which operating system (`uname -a` on *Nix)
Ubuntu 16.04 LTS 4.4.0-45-generic
* version of `btcd`, `bitcoind`, or other backend
Bitcoin core 0.16.0
* any other relevant environment details

### Notes
I found https://github.com/lightningnetwork/lnd/issues/567#issuecomment-355789128 and tried reverting to the previous commit that worked fine, but it now fails too at startup.
I also tried the v0.4.2-beta tagged 7cf5ebe with same result.

**Comment by Roasbeef** [comment]
See this commit for the prior fix: https://github.com/lightningnetwork/lnd/commit/3f2aa1c36837ecde53366e02e77db3575f05bd67#diff-760b3f162cb411feafa64b94f79df309

Was possible that your channel entered this state before that was merged though.

**Comment by cryptagoras** [comment]
Thx. I tried multiple things, same error, but I'll look at it again tomorrow. (slim chances I'll get anywhere :P)

**Comment by Roasbeef** [comment]
Use this patch to be able to boot up: 
```diff
diff --git a/channeldb/db.go b/channeldb/db.go
index 076b1c2c..6fd3f6bb 100644
--- a/channeldb/db.go
+++ b/channeldb/db.go
@@ -417,7 +417,7 @@ func fetchChannels(d *DB, pending, waitingClose bool) ([]*OpenChannel, error) {
 
 				nodeChans, err := d.fetchNodeChannels(chainBucket)
 				if err != nil {
-					return fmt.Errorf("unable to read "+
+					log.Errorf("unable to read "+
 						"channel for chain_hash=%x, "+
 						"node_key=%x: %v", chainHash[:], k, err)
 				}
```


Once the [forget channel](https://github.com/lightningnetwork/lnd/pull/1295) PR is merged, then you'll be able to remove this faulty channel.
