### ISSUE TITLE
Unknown Option - Autopilot

### ISSUE THREAD

**Issue by RossClelland** [lightningnetwork/lnd#1483]
### Background
lnd.conf contains the following which I've copied and pasted from the sample config file:
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.9

However, when I start lnd I get the following error:
2018-06-30 09:12:03.690 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:19: unknown option: autopilot.active

### Your environment

version of `lnd` 0.4.2-beta
o/s - ubuntu 16
bitcoind 0.16.1

### Steps to reproduce

Configure lnd.conf as follows:

> 2018-06-30 09:12:03.690 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:19: unknown option: autopilot.active
> 2018-06-30 09:12:03.691 [INF] LTND: Version 0.4.2-beta commit=18f17ad49b4cc58635a285e53441d82a0c54fd99
> 2018-06-30 09:12:03.691 [INF] LTND: Active chain: Bitcoin (network=mainnet)
> 2018-06-30 09:12:03.691 [INF] CHDB: Checking for schema update: latest_version=1, db_version=1

then run 'lnd' and 'lnd unlock'

### Expected behaviour

After syncing with bitcoind autopilot should engage

### Actual behaviour

Autopilot doesn't start with the following error:

**> 2018-06-30 09:12:03.690 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:19: unknown option: autopilot.active**
> 2018-06-30 09:12:03.691 [INF] LTND: Version 0.4.2-beta commit=18f17ad49b4cc58635a285e53441d82a0c54fd99
> 2018-06-30 09:12:03.691 [INF] LTND: Active chain: Bitcoin (network=mainnet)
> 2018-06-30 09:12:03.691 [INF] CHDB: Checking for schema update: latest_version=1, db_version=1

**Comment by wpaulino** [comment]
You should ensure all `autopilot` settings in the config file are directly below the `[autopilot]` header.

```
[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.9
```

**Comment by RossClelland** [comment]
Just made the change and it works, thanks
