### ISSUE TITLE
[Feature Request]: Parameter for disabling TLS

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#1490]
I would like a way to disable TLS.

With BTCPay, TLS is handled by a NGINX reverse proxy which then route HTTP requests to LND via url routing. Having TLS at LND level make no sense in our case.

We could probably share the private key of the certificate to LND, but it complicates everything, as the certificate is renewed automatically by nginx and we would need a logic to restart LND to pick up the new certificate. Also, a bug in LND could expose nginx's certificate. (ping @RockStarDev)

**Comment by Roasbeef** [comment]
Why would you need to share the cert? If nginx is just acting as a reverse proxy, then it has no need for the private key, and the cert (for lnd) doesn't need to be known to the wider internet.

**Comment by Roasbeef** [comment]
> Having TLS at LND level make no sense in our case.

An extra (well not even extra at this state, the default) step yes, wouldn't say it adds nothing though.

**Comment by NicolasDorier** [comment]
BTCPay wants to access LND from inside the network via HTTP, and but expose LND through HTTPS through the reverse proxy.

Without this, BTCPay can't really connect to LND from inside the network, as it does not trust HTTPS.
I prefer not adding a textbox to input the cert thumbprint, and I prefer not ignoring bad certificates.

My proposal is only for disabling TLS for REST interface, not for the gRPC interface.

**Comment by Roasbeef** [comment]
Yes we can add something like that, but I'd prefer that it can _only_ be enabled if all RPC listeners are only listening on local host.

**Comment by NicolasDorier** [comment]
@Roasbeef does not work for my case. LND is running in its own container and thus need to be accessed by the BTCPay container as well as the NGINX container which handle HTTPS/Let's encrypt and route HTTP request based on the HTTP path. (https://btcpay.example.com/lnd requests are directly forwarded to LND REST)

**Comment by Roasbeef** [comment]
Seems you could just easily proxy from 0.0.0.0 -> localhost then.

**Comment by NicolasDorier** [comment]
What do you mean? If we limit this to localhost, it means LND will only listen on 127.0.0.1, which mean that neither nginx nor btcpay would be able to access it as they are on different container.

**Comment by Roasbeef** [comment]
Yeah so on the same container that `lnd` runs on, a proxy to handle that mapping.

**Comment by NicolasDorier** [comment]
I am not comfortable with several process in one container, and it add a dependency and complexity in my dockerfile / entrypoint. Simpler for me just allowing http on 0.0.0.0 and maintaining my own fork. 

I understand your worry that somebody will end up shooting himself in the foot.

**Comment by Roasbeef** [comment]
OK, no problem. The patch set itself is pretty small, so hopefully it won't be too difficult to maintain.

**Comment by NicolasDorier** [comment]
Closing this for now. I might do a PR later still with allowing that only on 127.0.0.1, it would make it even easier to maintain for me.
