### ISSUE TITLE
lnd exits w/ error due to comment on config line for tlsextradomain

### ISSUE THREAD

**Issue by stp-ip** [lightningnetwork/lnd#1491]
### Background

lnd crashes due to tldextradomain, when trailing comment on same line.

### Your environment

* version of `lnd`
b8fecfca71507643e2ba3cc32b65c9de87790597
* which operating system (`uname -a` on *Nix)
4.15.0-1-ARCH (Archlinux)
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details

### Steps to reproduce

Add any address to tlsextradomain + trailing comment `; grpc` and let lnd regenerate the certs.

### Expected behaviour

Generate certs including subject alternative name for a domain + comment on the same line.
Start lnd with new certs. 

### Actual behaviour
Generate certs including subject alternative name. (works)
Lnd crashed due to `x509: cannot parse dnsName "somehiddenthing.onion ; grpc"`

**Comment by stp-ip** [comment]
Not the onion address, but the comment at the end of line.

**Comment by Roasbeef** [comment]
I wouldn't call this a crash, more like: exit with an error. 

Why are you adding a trailing comment? What do you mean by "trailing comment"?

What's the full error returned?

**Comment by Roasbeef** [comment]
If you properly specify a _domain_ (nothing else), does this command work as you expect?

**Comment by stp-ip** [comment]
The idea was to add more context to the configuration details.

Config line:
`example.com ; grpc`

The only error resulting in the exit:
`x509: cannot parse dnsName "example.com ; grpc"`

Without the comment it works without the exit.

**Comment by Roasbeef** [comment]
I see, I don't think this is actually an issue then. The format (of the config file) specifies that comments should only be the first thing on the line, not afterwards.
