### ISSUE TITLE
Add ability to get funding_fee and close_fee from RPC.

### ISSUE THREAD

**Issue by andrewshvv** [lightningnetwork/lnd#1503]
**Feature request:**
Add ability to get funding_fee and close_fee from RPC.

- [ ] Add `funding_fee` in `pendingchannels`
- [ ] Add `funding_fee` in `listchannels`
- [ ] Add `close_fee` in `pendingchannels`
- [ ] Add `close_fee` in `closedchannels`

**Rationale:**
Building an external subsystem which manages the lnd channels it is important to track what are the costs for open, close, and in future update the channel, as well as the cost for current commitment transaction.

For now there are several ways of tracking `close_fee`:
* get the closing fee from external explorer, or external subsystem which monitors the blockchain.
* by knowing `fee_per_kw` and  `commit_fee` and standard size of cooperative close_tx we always could calculate what is the `max` and `min` fee, but as far as I understand `fee_per_kw` might be changed by another side during close phase? Correct me if I am wrong please.

But for `funding_fee` situation is different? If I am correct, we need always track wallet balance to understand how much was taken from it for funding fee, which might be hard because of the fact that `lnwallet` not tracks change inputs right now.  Although, situation for tracking `funding_fee` might change with this [PR](https://github.com/lightningnetwork/lnd/pull/1461) being merge 🤔

**Comment by Roasbeef** [comment]
If you have the `txid`, you can already calculate all of this.

**Comment by carlaKC** [comment]
With the addition of close initiators in recent lnd versions + txid, it is always possible to calculate fees for channels. 
Our [faraday](https://github.com/lightninglabs/faraday/blob/master/docs/accounting.md) tool's audit output does the heavy lifting and creates a CSV containing a full accounting report if you don't want to manually calculate.

**Comment by andrewshvv** [comment]
@carlaKC Great! Thanks for the update.
