### ISSUE TITLE
lncli doesn't read rpcserver (rpclisten) from config file

### ISSUE THREAD

**Issue by zx9r** [lightningnetwork/lnd#1511]
### Background

When running lncli --lndir=somedir with somedir != defaultdir it doesnt read the parameter rpclisten to know where to connect to make the grpc calls to the lnd daemon.

While this is not solved you have to specify in the command line with the parameter --rpcserver

### Your environment

* lncli version 0.4.2 commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
* Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

### Steps to reproduce

Start lnd with a diferent from default configfile:

lnd --lnddir=/home/bitcoin/.lnd_testnet --configfile=/home/bitcoin/.lnd_testnet/lnd.conf

The config file should have rpclisten=host:port with port != default (10009)

Then try:

lncli --lnddir=/home/bitcoin/.lnd_testnet getinfo

### Expected behaviour

Should connect to lnd and print the response of getinfo grpc call

### Actual behaviour

Tries to connect to default port (10009) where can be listen another lnd instance. In such case the authentication handshake will fail.  If there isn't any lnd listening on default port it will show a connection error.

While this is not solved you have to specify in the command line with the parameter --rpcserver:

lncli --lnddir=/home/bitcoin/.lnd_testnet --rpcserver=localhost:20009 getinfo

**Comment by Roasbeef** [comment]
This is the expected behavior. We have that command line setting for a reason (`--rpcserver`). Otherwise, we'd also have to read the `lnd.conf` within `lncli`.
