### ISSUE TITLE
channeldb+rpc: add pagination of listinvoices

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#1514]
```
$ lncli listinvoices
[lncli] rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (4726702 vs. 4194304)
```

Currently, once we exceed a few thousand invoices, we can no longer return them over the RPC interface in a single go. As a result, we need to add _pagination_ in order to allow callers to iteratively request the entire range, or even seek within the current range. 

# Steps To Completion  

- [ ] Decide on a sane initial value for the chunk size, this can be determined by computing the current serialize size of the `channeldb` struct (as an upper bound), and extrapolating from there towards the max size of `4726702 bytes. 

- [ ] Modify the `ListInvoices` method to instead resemble the [`ForwardingLog.Query`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_log.go#L171) API. 

- [ ] Update the RPC response to use this new query interface, and also the RPC interface to accept the new max invoices, invoice seek param, and any other new relevant parameters. 

- [ ] Update `lncli` to set sane default values for these, and also expose the new values to the caller.

**Comment by taketa** [comment]
I'll take this issue

**Comment by Roasbeef** [comment]
👍
