### ISSUE TITLE
getInfo RPC doesn't return LND version

### ISSUE THREAD

**Issue by neogeno** [lightningnetwork/lnd#1520]
### Background

When using the command line lncli getinfo, the version of LND is displayed as the last field. However, when connecting via GRPC and calling the getinfo command, all fields EXCEPT version are returned.

### Your environment

* version of `lnd`0.42 latest
* which operating system (`uname -a` on *Nix) Linux
* version of `btcd`, `bitcoind`, or other backend 0.12
* any other relevant environment details

### Steps to reproduce

```$lncli getinfo``` 
Observe the version number

Use GRPC to connect and make a call
```
lightning.getInfo({}, function(err, response) {
    if (err) console.log(err)
    console.log('GetInfo!:', response);
});
```

### Expected behaviour

GRPC results should match lncli

### Actual behaviour

Missing "version" data

Tell us what happens instead

**Comment by Roasbeef** [comment]
Have you updated your set of protos? `lncli` uses gRPC directly, and properly displays the version: 
```
{
    "identity_pubkey": "030f375d8aecdddc852309c15c3b67c2934de0de4d31e1e04a03d656ca0a78d008",
    "alias": "030f375d8aecdddc8523",
    "num_pending_channels": 0,
    "num_active_channels": 19,
    "num_peers": 29,
    "block_height": 1351796,
    "block_hash": "000000000001debe269c64d5b06341f3ce03c9180b66d54efa8e2c0658291271",
    "synced_to_chain": true,
    "testnet": true,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "030f375d8aecdddc852309c15c3b67c2934de0de4d31e1e04a03d656ca0a78d008@104.131.26.124:9735"
    ],
    "best_header_timestamp": "1530991203",
    "version": "0.4.2-beta commit=c19c872cffe19dfd26cfbf041797acfc0800111f"
}
```

**Comment by neogeno** [comment]
My Bad, had an old proto file lurking around.
