### ISSUE TITLE
Can't compile on Windows 10 Pro, running into non-compilation errors it seems.

### ISSUE THREAD

**Issue by OluAgunloye** [lightningnetwork/lnd#1521]
### Background

I can't compile lnd.exe on Windows. The CLI compiles just fine, just not the daemon executable.

### Your environment

* version of `lnd`: master as of 7-7-2018: `lightningnetwork/lnd commit: 08de2becf8d77fae192205172c4fb17bb09bd0dbf49e64aa323b2fcbf9fe2a35`
* `Windows 10 Home`
* version of `btcd` is one that comes from running `make check`
*` go1.10.X`

### Steps to reproduce
open an cmd.exe prompt in Windows machine and install Go version 1.10.x, setting up proper go path structure
go to lnd and then (with proper GOPATH set) run: 
`go build -v -o lnd.exe -ldflags "-X main.Commit=26c36f183a6a8c86b7bc17f133922a2e13cbdd90" github.com/lightningnetwork/lnd`  as per instructions found here: [https://github.com/lightningnetwork/lnd/issues/1171#issuecomment-386019374](url)
### Expected behaviour

I expect lightning lnd.exe to compile in the same way as I compiled the lncli, which compiled just fine. 

### Actual behavior

```

github.com/lightningnetwork/lnd
# github.com/lightningnetwork/lnd
..\github.com\lightningnetwork\lnd\lnd.go:519:31: cannot use rpcServer (type *rpcServer) as type lnrpc.LightningServer in argument to lnrpc.RegisterLightningServer:
        *rpcServer does not implement lnrpc.LightningServer (missing ClosedChannels method)
..\github.com\lightningnetwork\lnd\peer.go:524:7: cannot use p (type *peer) as type lnpeer.Peer in field value:
        *peer does not implement lnpeer.Peer (missing IdentityKey method)
..\github.com\lightningnetwork\lnd\peer.go:532:11: cannot use p.server.invoices (type *invoiceRegistry) as type htlcswitch.InvoiceDatabase in field value:
        *invoiceRegistry does not implement htlcswitch.InvoiceDatabase (wrong type for LookupInvoice method)
                have LookupInvoice("github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".Hash) (channeldb.Invoice, error)
                want LookupInvoice("github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".Hash) (channeldb.Invoice, uint32, error)
..\github.com\lightningnetwork\lnd\peer.go:538:14: unknown field 'BlockEpochs' in struct literal of type htlcswitch.ChannelLinkConfig
..\github.com\lightningnetwork\lnd\peer.go:555:35: too many arguments in call to htlcswitch.NewChannelLink
        have (htlcswitch.ChannelLinkConfig, *lnwallet.LightningChannel, uint32)
        want (htlcswitch.ChannelLinkConfig, *lnwallet.LightningChannel)
..\github.com\lightningnetwork\lnd\peer.go:837:11: cannot use p.addr.IdentityKey (type *btcec.PublicKey) as type lnpeer.Peer in argument to p.server.authGossiper.ProcessRemoteAnnouncement:
        *btcec.PublicKey does not implement lnpeer.Peer (missing IdentityKey method)
..\github.com\lightningnetwork\lnd\rpcserver.go:332:5: cannot use (*rpcServer)(nil) (type *rpcServer) as type lnrpc.LightningServer in assignment:
        *rpcServer does not implement lnrpc.LightningServer (missing ClosedChannels method)
..\github.com\lightningnetwork\lnd\rpcserver.go:2899:47: not enough arguments in call to r.server.chanRouter.FindRoutes
        have (*btcec.PublicKey, lnwire.MilliSatoshi, uint32)
        want (*btcec.PublicKey, lnwire.MilliSatoshi, lnwire.MilliSatoshi, uint32, ...uint16)
..\github.com\lightningnetwork\lnd\server.go:268:36: not enough arguments in call to htlcswitch.New
        have (htlcswitch.Config)
        want (htlcswitch.Config, uint32)
..\github.com\lightningnetwork\lnd\xgo.go:91:6: main redeclared in this block
        previous declaration at ..\github.com\lightningnetwork\lnd\lnd.go:644:6
..\github.com\lightningnetwork\lnd\server.go:268:36: too many errors
```

**Comment by Roasbeef** [comment]
Did you use `dep ensure -v` beforehand? 

```
..\github.com\lightningnetwork\lnd\xgo.go:91:6: main redeclared in this block
```

There is `xgo.go` file...

**Comment by OluAgunloye** [comment]
Removed the xgo.go file just now and ran dep ensure -v beforehand.  I mus be doing something not useful somewhere, as out put has barely changed:
`github.com/lightningnetwork/lnd
# github.com/lightningnetwork/lnd
..\github.com\lightningnetwork\lnd\lnd.go:519:31: cannot use rpcServer (type *rpcServer) as type lnrpc.LightningServer in argument to lnrpc.RegisterLightningServer:
        *rpcServer does not implement lnrpc.LightningServer (missing ClosedChannels method)
..\github.com\lightningnetwork\lnd\peer.go:524:7: cannot use p (type *peer) as type lnpeer.Peer in field value:
        *peer does not implement lnpeer.Peer (missing IdentityKey method)
..\github.com\lightningnetwork\lnd\peer.go:532:11: cannot use p.server.invoices (type *invoiceRegistry) as type htlcswitch.InvoiceDatabase in field value:
        *invoiceRegistry does not implement htlcswitch.InvoiceDatabase (wrong type for LookupInvoice method)
                have LookupInvoice("github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".Hash) (channeldb.Invoice, error)
                want LookupInvoice("github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".Hash) (channeldb.Invoice, uint32, error)
..\github.com\lightningnetwork\lnd\peer.go:538:14: unknown field 'BlockEpochs' in struct literal of type htlcswitch.ChannelLinkConfig
..\github.com\lightningnetwork\lnd\peer.go:555:35: too many arguments in call to htlcswitch.NewChannelLink
        have (htlcswitch.ChannelLinkConfig, *lnwallet.LightningChannel, uint32)
        want (htlcswitch.ChannelLinkConfig, *lnwallet.LightningChannel)
..\github.com\lightningnetwork\lnd\peer.go:837:11: cannot use p.addr.IdentityKey (type *btcec.PublicKey) as type lnpeer.Peer in argument to p.server.authGossiper.ProcessRemoteAnnouncement:
        *btcec.PublicKey does not implement lnpeer.Peer (missing IdentityKey method)
..\github.com\lightningnetwork\lnd\rpcserver.go:332:5: cannot use (*rpcServer)(nil) (type *rpcServer) as type lnrpc.LightningServer in assignment:
        *rpcServer does not implement lnrpc.LightningServer (missing ClosedChannels method)
..\github.com\lightningnetwork\lnd\rpcserver.go:2899:47: not enough arguments in call to r.server.chanRouter.FindRoutes
        have (*btcec.PublicKey, lnwire.MilliSatoshi, uint32)
        want (*btcec.PublicKey, lnwire.MilliSatoshi, lnwire.MilliSatoshi, uint32, ...uint16)
..\github.com\lightningnetwork\lnd\server.go:268:36: not enough arguments in call to htlcswitch.New
        have (htlcswitch.Config)
        want (htlcswitch.Config, uint32)
..\github.com\lightningnetwork\lnd\xgo.go:91:6: main redeclared in this block
        previous declaration at ..\github.com\lightningnetwork\lnd\lnd.go:644:6
..\github.com\lightningnetwork\lnd\server.go:268:36: too many errors`

**Comment by OluAgunloye** [comment]
Just deleted everything and reinstalled from scratch, installation seems fine now.

**Comment by Roasbeef** [comment]
👍
