### ISSUE TITLE
local-amt push-amt description in openchannel

### ISSUE THREAD

**Issue by jakubtrnka** [lightningnetwork/lnd#1522]
### Background

When I open a new channel I'd like to have very clear description of what the command exactly does. People don't generally know details of lightning inner working. And what they see is "if all my channels have zero remote balance, I cannot receive payments, and If I want a channel with non-zero remote balance, I have to give the money to the counter party for free". 

### Your environment
* lnd version 0.4.2-beta commit=8ab464b4d191fd095ab46a4b3d36cb9fe54cf3f4

### Expected behaviour
The help command should tell to which purpose push-amt serves and how this should be set instead of `the number of satoshis to push to the remote side as part of the initial commitment state (default: 0)`, which sounds more like "opens a channel and makes payment right after that, which you don't get back"

**Comment by Roasbeef** [comment]
> which sounds more like "opens a channel and makes payment right after that, which you don't get back"

That's exactly what it does. You open a channel and pay the other party at the same time.

**Comment by jakubtrnka** [comment]
And what's the purpose of this option? Why would somebody want to do that? I thought this option tells the counterparty to push that amt to the initial state of channel. Is the shortcut open&pay really needed?

**Comment by guggero** [comment]
That option is absolutely needed. One simple example might be: My employer opens a channel with my node with the capacity of my salary and pushes the whole amount to my side. The effect is that I have a new channel that I can start spending from immediately (after funding tx is confirmed). Without this option, the process would be asynchronous since after opening the channel the employer's node would need to wait for the channel to open before paying the entire capacity to my side.

I'm sure there are many more use cases where this option might be very useful.

**Comment by Roasbeef** [comment]
Agree with everything @guggero just said. Updated the help to make this a bit more clear.

**Comment by jakubtrnka** [comment]
@Roasbeef @guggero Ok, thans for explenation.
So in that case, is there any other direct way, I can make my node accept payments? I have few Sats on lightning spin, and the payment never goes through? I have LND running for more than 2 weeks, port forwarding set correctly, URI=035a73512b9ddd75340fd31d7e68ecc73397a4b05a382e846251b3b478815f188d@185.21.223.231:9735

**Comment by halseth** [comment]
@jakubtrnka You need incoming capacity. Simplest way to get this is for someone to open a channel to you, or for you to spend some funds (everything you spend will go towards your incoming channel capacity!)

**Comment by jakubtrnka** [comment]
I know that. I must probably accept the fact that tuning LN node is bit more subtle than I was used to from Bitcoin Core which is totally fool-proof.
