### ISSUE TITLE
Can't connection server rpclisten port

### ISSUE THREAD

**Issue by dognie** [lightningnetwork/lnd#1525]
### Background
I'm going to connect to the btcd server,Because the data of the btcd test node is too large.
my localhost 192.168.124.6 
my server 192.168.124.13 (Syn testnet data completion)

### environment

* version of `lnd` 0.4.2-beta commit=a0b2fadea35fa4642daf4e9f56e6ecfe31d22ce1
* macos 10.13.5
* version of `btcd`,0.12.0-beta on ubuntu 16.04

### Steps to reproduce
- btcd config and rpclisten
```
root@eth:/etc/supervisor/conf.d# netstat -an |grep 183
tcp        0      0 0.0.0.0:18333           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:18334           0.0.0.0:*               LISTEN
tcp        0      0 192.168.124.13:54052    46.229.165.145:18333    ESTABLISHED
tcp        0      0 192.168.124.13:45960    200.122.181.58:18333    ESTABLISHED
tcp        0      0 192.168.124.13:18334    192.168.124.6:54960     TIME_WAIT
tcp        0      0 192.168.124.13:18334    192.168.124.6:54952     TIME_WAIT
tcp        0      0 192.168.124.13:18334    192.168.124.6:54953     TIME_WAIT
tcp        0      0 192.168.124.13:55920    94.23.239.47:18333      ESTABLISHED
tcp        0      0 192.168.124.13:43856    47.93.123.233:18333     ESTABLISHED
tcp        0      0 192.168.124.13:48912    188.40.66.212:18333     ESTABLISHED
tcp        0      1 192.168.124.13:51686    183.81.181.30:60303     SYN_SENT
tcp        0      0 192.168.124.13:33672    193.28.87.190:18333     ESTABLISHED
tcp        0      0 192.168.124.13:18334    192.168.124.6:54957     TIME_WAIT
tcp        0      0 192.168.124.13:18334    192.168.124.6:54959     TIME_WAIT
tcp        0      1 192.168.124.13:51788    183.81.181.30:60303     SYN_SENT
tcp        0      0 192.168.124.13:18334    192.168.124.6:54965     FIN_WAIT2
tcp        0      0 192.168.124.13:18334    192.168.124.6:54958     TIME_WAIT
tcp        0      0 192.168.124.13:45714    144.76.136.19:18333     ESTABLISHED
tcp        0      0 192.168.124.13:18334    192.168.124.6:54964     TIME_WAIT
tcp        0      0 192.168.124.13:18334    192.168.124.6:54951     TIME_WAIT
tcp        0      0 192.168.124.13:36500    208.82.23.199:18333     ESTABLISHED
tcp6       0      0 :::18333                :::*                    LISTEN
unix  3      [ ]         STREAM     CONNECTED     21839    /var/run/dbus/system_bus_socket
root@eth:/etc/supervisor/conf.d# ps ax |grep btcd
 3252 ?        Sl   706:32 btcd
24836 ?        Sl     5:34 /home/bai/goproj/bin/btcd --testnet --txindex --rpcuser=bai --rpcpass=bai --datadir=/home/bai/data1/btc_testnet --rpclisten 0.0.0.0:18334
25133 pts/1    S+     0:00 grep --color=auto btcd
```
- lnd log and config
```
 lnd
2018-07-09 10:51:23.639 [INF] LTND: Version 0.4.2-beta commit=a0b2fadea35fa4642daf4e9f56e6ecfe31d22ce1
2018-07-09 10:51:23.639 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-07-09 10:51:23.639 [INF] CHDB: Checking for schema update: latest_version=1, db_version=1
2018-07-09 10:51:23.655 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-07-09 10:51:23.655 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-07-09 10:51:23.655 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2018-07-09 10:51:37.188 [INF] LNWL: Opened wallet
2018-07-09 10:51:37.261 [INF] LTND: Primary chain is set to: bitcoin
2018-07-09 10:51:37.261 [INF] LTND: Initializing btcd backed fee estimator
```

Lnd cat lnd.conf
```
;externalip=x.x.x.x
bitcoin.active=1
bitcoin.testnet=1
bitcoin.node=btcd
btcd.rpchost=192.168.124.13:18334
btcd.rpcuser=bai
btcd.rpcpass=bai
```
➜  Lnd lncli unlock
Input wallet password:

lnd successfully unlocked!
➜  Lnd lncli getinfo
```
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable
```
`Is there a problem in my btcd.rpchost format? `
### Expected behaviour

I want to be able to connect my server btcd testnet 
`lncli getinfo` to normal output 

### Actual behaviour
I always get this :rpc error: code = Unavailable desc = grpc: the connection is unavailable

**Comment by offerm** [comment]
Looks like LND fails to create a connection with BTCD. 

Are you using the right rpc.cert for your btcd node?  you need to use the one from 192.168.124.13

check the BTCD log for connection related errors from 192.168.124.6 (you may need debuglevel=debug) for this

**Comment by ErikEk** [comment]
Try removing btcd.rpchost. It worked for me.

**Comment by ErikEk** [comment]
There seems to be an issue when trying to shut down the lnd instance (using Ctrl+C) after one tries to connect to a non working rpchost.
@dognie Do you experience the same issue?

**Comment by ErikEk** [comment]
I guess you don't need me to leave an issue.

**Comment by dognie** [comment]
@ErikEk  I've had the same problem.(Ctrl+C not work)So I had to kill the process and restart it.
Another problem is that I can't connection target server rpclisten port.(`btcd.rpchost`)
Your btcd is in your local or server side？
My solution now is to start btcd locally, but it wastes a lot of my disk. Besides, I have no better solution.

**Comment by ErikEk** [comment]
I guess that issue has been assigned to halseth for now. I'll look into your first issue as well.

**Comment by halseth** [comment]
@dognie Please post the complete logs from LND after you have unlocked the wallet. It should say why it shuts down :)

**Comment by ErikEk** [comment]
@dognie I'm experiencing the same issue when trying to connect to a remote btcd node with btcd.rpchost=192.168.0.199:18333.
@halseth: I don't get any debug messages with debuglevel=debug on.

**Comment by ErikEk** [comment]
@dognie I'm experiencing the same issue when trying to connect to my remote (on LAN) BITCOIND node (testnet 18333)  with btcd.rpchost=192.168.0.199:18333.
@halseth: I don't get any debug messages with debuglevel=debug on. It's just stuck on LTND: Initializing btcd backed fee estimator.

**Comment by Roasbeef** [comment]
I don't think this is an issue with `lnd` at all. Instead, it appears to be an issue with the home networking you're attempting to configure `lnd` with.

**Comment by dognie** [comment]
Yep I'll try other ways.Thanks
