### ISSUE TITLE
lnd crashes after a gRPC client made an InvoiceSubscription call.

### ISSUE THREAD

**Issue by cbfl** [lightningnetwork/lnd#1538]
### Background

I'm using LND with various thin/web wrappers. After updating to latest code in master it crashes every time a client is connected and tries to subscribe to invoices.

### Your environment

lnd version 0.4.2-beta commit=93207608b5a433ddfc15cfe56bb060e1c720166e
Linux 4.4.0-124-generic x86_64 x86_64 x86_64 GNU/Linux
Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

### Steps to reproduce

1) Update lnd to 93207608b5a433ddfc15cfe56bb060e1c720166e
2) make gRPC InvoiceSubscription request

### Expected behaviour

not crashing :)

### Actual behaviour

fatal error: runtime: out of memory

**Comment by Roasbeef** [comment]
What arguments are you passing to the streaming RPC call?

**Comment by Roasbeef** [comment]
Attempting to reproduce.

**Comment by Roasbeef** [comment]
Updated an existing node to the latest commit, and was able to receive new notifications no issue.

**Comment by Roasbeef** [comment]
Found the culprit, should have a PR up shortly!
