### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#1546]
### Background
after running for a few minutes, lnd crashes with panic
panic after updating to latest commt

`panic:` runtime error: makeslice: len out of range
goroutine 53983 [running]:
github.com/lightningnetwork/lnd/channeldb.deserializeOutgoingPayment(0xb90910, 0x13ca5bc0, 0x8, 0xa637a088, 0x9d)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:192 +0x1a8
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments.func1.1(0xa637a080, 0x8, 0x8, 0xa637a088, 0x9d, 0x9d, 0x9d, 0x115e8e0c)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:103 +0x84
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).ForEach(0x13ca5ba0, 0x1322fad8, 0x8, 0x8)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:388 +0xec
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments.func1(0x115e8e00, 0xae1668, 0x115e8e00)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:95 +0x74
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).View(0x1153a000, 0x1322fb18, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:699 +0x80
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments(0x1143c050, 0x97b709, 0xe, 0x0, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:89 +0x4c
main.(*rpcServer).ListPayments(0x114dff40, 0xb962c8, 0x13c24740, 0x10a4624, 0x114dff40, 0x124ecb10, 0x114aa000)
	/home/admin/go/src/github.com/lightningnetwork/lnd/rpcserver.go:3572 +0x74
github.com/lightningnetwork/lnd/lnrpc._Lightning_ListPayments_Handler.func1(0xb962c8, 0x13c24740, 0x8ec508, 0x10a4624, 0x1, 0x1, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6684 +0x68
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xb962c8, 0x13c24740, 0x8ec508, 0x10a4624, 0x124ecb00, 0x124ecb10, 0x13a39970, 0x5a7078, 0x13a39970, 0x13ca5960)
	/home/admin/go/src/github.com/lightningnetwork/lnd/macaroons/service.go:117 +0x108
github.com/lightningnetwork/lnd/lnrpc._Lightning_ListPayments_Handler(0x9676c8, 0x114dff40, 0xb962c8, 0x13c24740, 0x13a39950, 0x1162d810, 0x0, 0x0, 0xe1a92aa3, 0x65251098)
	/home/admin/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6686 +0x124
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0, 0x115be2e0, 0x10779dc, 0x13ca5960, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x7c0
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0, 0x13ca5960)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1054
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x11328f00, 0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x7c
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0x7c
`

### Your environment
MAINNET
Version 0.4.2-beta commit=93207608b5a433ddfc15cfe56bb060e1c720166e
4.15.0-20-genericx86_64 GNU/Linux
bitcoind 0.16

[LOGS](https://www.dropbox.com/s/xs78iz9laaczney/lnd.log?dl=0)

**Comment by wpaulino** [comment]
The logs linked don't show the panic stack trace.
