### ISSUE TITLE
gRPC and path routing

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#1552]
Feel free to close this if you think it is off-topic, as it may not be related to LND, but underlying limitation of gRPC.

In a deployement with BTCPay with BTC, LTC and says BTG all having their own instance of LND, my goal is:

1. To not have to open a new port for each instance
2. To make the traffic pass through my reverse proxy, such that my valid certificate get applied instead of auto-generated one

I plan to use gRPC support in [nginx](https://www.nginx.com/blog/nginx-1-13-10-grpc/). 
This would support routing to the right LND based on the path of the HTTP2 queries.

That said, it seems (I may be mistaken), that gRPC path is already defined as `{service_name}/{method}`.
Which mean that I can't use several LND, because all the service_name of all the LND instances running inside BTCPay are the same. (and probably hard coded by every LND client library)

So here I am with 2 choices:

1. Force all clients to connect to the internal LND via REST, on which I know routing will work properly, (it means that it put the burden on wallets to never connect using gRPC)
2. Expose only BTC gRPC, and not exposing any other altcoins gRPC,

Or have you another solution I did not thought of?

Note that in the future, I may also have several LND for the same crypto currency, on which I would like to apply routing as well.

**Comment by Roasbeef** [comment]
So according to this link: https://www.nginx.com/blog/nginx-1-13-10-grpc/

A new-ish version of `nginx` actually supports proxying to multiple services over a single end point. Are you using this version, or a later version?
