### ISSUE TITLE
ChannelCloseSummary.closing_tx_hash doesn't match Transaction.tx_hash

### ISSUE THREAD

**Issue by ottosuess** [lightningnetwork/lnd#1553]
### Background

I'm trying to find out which of my on chain transactions result from channel open and close actions by matching `ChannelCloseSummary.closing_tx_hash`es with `Transaction.tx_hash`es.

This only works for cooperative closes. Otherwise the `closing_tx_hash` points to the predecessor of the transaction that returns my funds.

`getTransactions` contains this `tx_hash`:
https://live.blockcypher.com/btc-testnet/tx/46345deeb0460fb561ae99e61df736a47158170a31f5f56934009f47d384d189/

`channelCloseSummary` points to this `closing_tx_hash`:
https://live.blockcypher.com/btc-testnet/tx/6b07c84dd2e53283d007d7a038e1c678b26186542877390746a5b60699c0ec12/#output-index-1

### Your environment

* version of `lnd`: 0.4.2-beta commit=18f17ad49b4cc58635a285e53441d82a0c54fd99

### Expected behaviour

If this is the intended behaviour maybe add an other field to the `channelCloseSummary` with the tx_hash that actually returns my funds?

Or is there any other way to find out which transactions result from closing a channel?

**Comment by Roasbeef** [comment]
I'm sorry, but I don't quite understand the question. The internal wallet doesn't actually know about channels, so the first one is the funding transaction that was initially created, while the second is the commitment transaction.

**Comment by ottosuess** [comment]
Ok, let me try to explain my problem again.

I think its very confusing for users to see the on chain transactions that result from opening and closing channels just like a regular transactions because you are not really receiving and sending money but rather moving it in and out of a channel. It still is your money, just in a channel. The only thing you are really spending in those transactions are the fees.
Thats why i want to find the on chain transactions that result from opening and closing channels.

I can find transactions with the `closing_tx_hash` of the `ChannelCloseSummary` in the list of transactions i get from the `GetTransactions` method ONLY if the `close_type` is `COOPERATIVE_CLOSE`.

For example this close summary belongs the the transaction below because of the matching `7dda7c11dfcbe9...` hash.

```
{
    "channel_point": "5650747c79086ea49c614896659f8ab7cebe8573f9d0756db09ac26a13079d3f:0",
    "chan_id": "1481779934917099520",
    "chain_hash": "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943",
    "closing_tx_hash": "7dda7c11dfcbe913f281e6fb734811c155601083ab701011e5bf7d8d3cb18f49",
    "remote_pubkey": "02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e",
    "capacity": "1000000",
    "close_height": 1349336,
    "settled_balance": "998918",
    "time_locked_balance": "0",
    "close_type": "COOPERATIVE_CLOSE"
}
```

```
{
    "tx_hash": "7dda7c11dfcbe913f281e6fb734811c155601083ab701011e5bf7d8d3cb18f49",
    "amount": "998918",
    "num_confirmations": 4191,
    "block_hash": "000000000000030feefc232c6983b15f254d69ba6da57bfb0b5aacff81bc3dc1",
    "block_height": 1349336,
    "time_stamp": "1530622968",
    "total_fees": "0",
    "dest_addresses": [
        "tb1qxly02fgnsyptkpkkuxaqgccqu0sr5ut8azmhxy"
    ]
}
```

But i can't find the transactions for ChannelCloseSummaries of type `REMOTE_FORCE_CLOSE` or `LOCAL_FORCE_CLOSE`.

```
{
    "channel_point": "8ba44a24263709e91c59c0d84dfae1bd7125af70f64237551a800d13e5718f13:0",
    "chan_id": "0",
    "chain_hash": "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943",
    "closing_tx_hash": "c7bcb0d48da1d1d37e23d84721a0b38de3f20aa2ee3838fdcac4e1e39920e916",
    "remote_pubkey": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
    "capacity": "373420",
    "close_height": 1352294,
    "settled_balance": "364370",
    "time_locked_balance": "0",
    "close_type": "REMOTE_FORCE_CLOSE"
},
```

This `closing_tx_hash` does not show up in my transactions list.

Sorry, i'm not that deep into the inner workings of lightning yet. Maybe i'm missing something here.

**Comment by Roasbeef** [comment]
It doesn't show up as it's a spend from a channel funding output. These aren't controlled by the wallet, but are controlled by `lnd`.

**Comment by Roasbeef** [comment]
If the remote party force closes, and you don't have any balance in the channel, then there's no output to the wallet. As a result, the wallet has nothing to track.

**Comment by ottosuess** [comment]
ah, thanks for clarifying. i guess this can be closed.
