### ISSUE TITLE
Unable to set externalip

### ISSUE THREAD

**Issue by aleksajovanovic** [lightningnetwork/lnd#1555]
### Background

Hi all,
Ive been trying to run a lightning node using lnd on the testnet but i'm unable to set the externalip necessary for public discovery. The command im using for btcd is:
`btcd --testnet --txindex`

### Your environment

* lnd version 0.4.2-beta
* Mac OS
* btcd version 0.12.0-beta

my lnd config file looks like:
debuglevel=info
debughtlc=true
listen=MY_IP_IS_HERE
externalip=MY_IP_IS_HERE
alias=mynode
color=#ff5050
maxpendingchannels=5
bitcoin.testnet=1
bitcoin.active=1
bitcoin.node=btcd

### Expected behaviour

Should have a publicly discoverable node

### Actual behaviour

I get an error:
![image](https://user-images.githubusercontent.com/10064402/42691747-4b7b90b6-8677-11e8-8f3a-18e490f18780.png)

**Comment by githorray** [comment]
listen=
should be your local IP, not your external IP.

```
$ host 108.168.39.196
196.39.168.108.in-addr.arpa domain name pointer dhcp-108-168-39-196.cable.user.start.ca.
```

**Comment by aleksajovanovic** [comment]
thanks so much!

**Comment by aleksajovanovic** [comment]
still cant see my node on https://explorer.acinq.co/ though

**Comment by githorray** [comment]
Many explorers do not update in real-time. Can you see your node in `lncli describegraph`?
