### ISSUE TITLE
[Feature Request] Cookie file authentication should not be cached

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#1557]
I noticed you are caching cookiefile at startup by considering it the same as RPCUser/Pass in `extractBitcoindParameters`. But the cookiefile change when BitcoinD get restarted, which mean LND stop working if bitcoind restart.

Second issue with it, if LND start just after BitcoinD but just before the cookiefile get regenerated, then we start having problem because LND is using the outdated file.

This make integration of LND to BTCPay randomly working.

**Comment by Roasbeef** [comment]
So what would you have then, `lnd` to continually poll the cookie file to see if it's re-created?

**Comment by NicolasDorier** [comment]
@Roasbeef just when the `rpcCLient` prepare the request to send to bitcoind, it read the cookieFile.

On NBitcoin I did a different system in the RPCClient: and I cache the `CookieFile`, if I get error 401, I read the cookiefile again and try one more time. That said this optimization should not really matter.
