### ISSUE TITLE
LND with Neutrino never finishes syncing after restart

### ISSUE THREAD

**Issue by PJUllrich** [lightningnetwork/lnd#1559]
### Background

I run `LND` with a `Neutrino` backend on the `Bitcoin testnet` chain. During the initial sync, the node has 3 peers and syncs the entire `testnet` chain. However, even after the latest block is synced, no incoming transactions are recognised, so `lncli walletbalance` returns only `0`s for all three sections although the address should be funded (as can be seen on e.g. [BlockCypher](https://live.blockcypher.com/btc-testnet/address/2NFbQxmu11AaKtzHHL7xYRFtj8LjoovSAEk/). I then stop and restart the `LND` node. When restarted, the node syncs the latest blocks, but never sets the `synced_to_chain` flag to `true` although the testnet block height is equal to the block height as e.g. on BlockCypher. Also, no funding transactions are recognised as during the initial sync. I deleted the `LND` folder and re-synced the entire chain twice now, but the problems persist.

### Your environment

* `lnd`: `0.4.2-beta`
* Darwin (macOS)
* Backend version not applicable, since `neutrino`-mode is used

### Steps to reproduce

1. Remove all previous `LND` files in e.g. `~/.lnd/`
1. Start `LND` in `neutrino` mode with 
```
lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=neutrino --neutrino.connect=faucet.lightning.community
```
1. Let the `LND` node sync fully.
1. Create a new address with `lncli newaddress np2wkh`
1. Send some Bitcoins to that address. Wait for confirmations.
1. Check `walletbalance` with `lncli walletbalance`
1. See `Expected behaviour 1.` and `Actual Behaviour 1.`
1. Stop and restart the `LND` node with the same commands as previously.
1. See `Expected behaviour 2.` and `Actual Behaviour 2.`

### Expected behaviour

1. `lncli walletbalance` shows the funds that were send to the address.
1. `LND` syncs and eventually sets the `synced_to_chain` flag to `true`. `lncli walletbalance` shows the funds that were sent to the address.

### Actual behaviour

1. `lncli walletbalance` shows only `0`s for all three sections.
1. `LND` never sets `synced_to_chain` to `true` and doesn't show funds in `walletbalance`.  Shows the following output: 
```
// Note: I removed the timestamps for brevity
[INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host

// The next output is printed over 1000 times
[DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)

// Eventually, this is printed
[DBG] BTCN: Sending getblocks (locator 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152, stop 0000000000000000000000000000000000000000000000000000000000000000) to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Sending getheaders (locator 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152, stop 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01) to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Received inv (block 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01) from 159.203.125.125:18333 (outbound)
[DBG] BTCN: Received headers (num 1) from 159.203.125.125:18333 (outbound)
[INF] BTCN: Processed 1 block in the last 12.26s (height 1353458, 2018-07-14 08:51:39 +0200 CEST)
[DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Received cfheaders from 159.203.125.125:18333 (outbound)
[DBG] BTCN: Rescan got out of order block 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01 with prevblock 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152

// From here on, the following lines are repeated every now and then
[DBG] BTCN: Received ping from 159.203.125.125:18333 (outbound)
[DBG] BTCN: Sending pong to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Sending ping to 159.203.125.125:18333 (outbound)
[DBG] BTCN: Received pong from 159.203.125.125:18333 (outbound)
``` 

### Related Issues
#511 
#1424 

### Additional Info
`lncli getinfo` shows:
```
{
    "identity_pubkey": "03ca1948523a57f8482db73e305a7be97ab2ea6151de13c60bbb4047d44105958d",
    "alias": "03ca1948523a57f8482d",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_peers": 0,
    "block_height": 1353475,
    "block_hash": "0000000000000047e5b0dc7229ee7c8d44197898a901f5059afdc8fbeed63f46",
    "synced_to_chain": false,
    "testnet": true,
    "chains": [
        "bitcoin"
    ],
    "uris": [
    ],
    "best_header_timestamp": "1531518389",
    "version": "0.4.2-beta commit=bc5bfeb479d5123ad3c9cfc8bf9636bb1535802e"
}
```
`lncli listpeers` shows:
```
{
    "peers": [
    ]
}
```

**Comment by PJUllrich** [comment]
Just tested the above using Docker instead and received the same problems.

**Comment by Roasbeef** [comment]
What `btcd` version are you using to sync? If you're using the faucet, then it uses a new version of the neutrino protocol that wasn't packaged with 0.4.2 beta .

**Comment by PJUllrich** [comment]
Hmm, I'm not actively using any `btcd` instance, but only run the packaged `lnd` release `0.4.2 beta`. Alright, so I need to update my local `lnd` instance. Where can I find out which version the faucet is running?

**Comment by vyomeshaudi6** [comment]
> ### Background
> 
> I run `LND` with a `Neutrino` backend on the `Bitcoin testnet` chain. During the initial sync, the node has 3 peers and syncs the entire `testnet` chain. However, even after the latest block is synced, no incoming transactions are recognised, so `lncli walletbalance` returns only `0`s for all three sections although the address should be funded (as can be seen on e.g. [BlockCypher](https://live.blockcypher.com/btc-testnet/address/2NFbQxmu11AaKtzHHL7xYRFtj8LjoovSAEk/). I then stop and restart the `LND` node. When restarted, the node syncs the latest blocks, but never sets the `synced_to_chain` flag to `true` although the testnet block height is equal to the block height as e.g. on BlockCypher. Also, no funding transactions are recognised as during the initial sync. I deleted the `LND` folder and re-synced the entire chain twice now, but the problems persist.
> ### Your environment
> 
>     * `lnd`: `0.4.2-beta`
> 
>     * Darwin (macOS)
> 
>     * Backend version not applicable, since `neutrino`-mode is used
> 
> 
> ### Steps to reproduce
> 
>     1. Remove all previous `LND` files in e.g. `~/.lnd/`
> 
>     2. Start `LND` in `neutrino` mode with
> 
> 
> ```
> lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=neutrino --neutrino.connect=faucet.lightning.community
> ```
> 
>     1. Let the `LND` node sync fully.
> 
>     2. Create a new address with `lncli newaddress np2wkh`
> 
>     3. Send some Bitcoins to that address. Wait for confirmations.
> 
>     4. Check `walletbalance` with `lncli walletbalance`
> 
>     5. See `Expected behaviour 1.` and `Actual Behaviour 1.`
> 
>     6. Stop and restart the `LND` node with the same commands as previously.
> 
>     7. See `Expected behaviour 2.` and `Actual Behaviour 2.`
> 
> 
> ### Expected behaviour
> 
>     1. `lncli walletbalance` shows the funds that were send to the address.
> 
>     2. `LND` syncs and eventually sets the `synced_to_chain` flag to `true`. `lncli walletbalance` shows the funds that were sent to the address.
> 
> 
> ### Actual behaviour
> 
>     1. `lncli walletbalance` shows only `0`s for all three sections.
> 
>     2. `LND` never sets `synced_to_chain` to `true` and doesn't show funds in `walletbalance`.  Shows the following output:
> 
> 
> ```
> // Note: I removed the timestamps for brevity
> [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host
> 
> // The next output is printed over 1000 times
> [DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)
> 
> // Eventually, this is printed
> [DBG] BTCN: Sending getblocks (locator 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152, stop 0000000000000000000000000000000000000000000000000000000000000000) to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Sending getheaders (locator 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152, stop 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01) to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Received inv (block 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01) from 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Received headers (num 1) from 159.203.125.125:18333 (outbound)
> [INF] BTCN: Processed 1 block in the last 12.26s (height 1353458, 2018-07-14 08:51:39 +0200 CEST)
> [DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Sending getcfheaders to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Received cfheaders from 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Rescan got out of order block 0000000000000011d5cce43f3941a11d44a42ccccde67f7773c23ef58ada7d01 with prevblock 000000000000001268a4b20345424065a93daafab687dd7a85db7324623c5152
> 
> // From here on, the following lines are repeated every now and then
> [DBG] BTCN: Received ping from 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Sending pong to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Sending ping to 159.203.125.125:18333 (outbound)
> [DBG] BTCN: Received pong from 159.203.125.125:18333 (outbound)
> ```
> 
> ### Related Issues
> 
> #511
> #1424
> ### Additional Info
> 
> `lncli getinfo` shows:
> 
> ```
> {
>     "identity_pubkey": "03ca1948523a57f8482db73e305a7be97ab2ea6151de13c60bbb4047d44105958d",
>     "alias": "03ca1948523a57f8482d",
>     "num_pending_channels": 0,
>     "num_active_channels": 0,
>     "num_peers": 0,
>     "block_height": 1353475,
>     "block_hash": "0000000000000047e5b0dc7229ee7c8d44197898a901f5059afdc8fbeed63f46",
>     "synced_to_chain": false,
>     "testnet": true,
>     "chains": [
>         "bitcoin"
>     ],
>     "uris": [
>     ],
>     "best_header_timestamp": "1531518389",
>     "version": "0.4.2-beta commit=bc5bfeb479d5123ad3c9cfc8bf9636bb1535802e"
> }
> ```
> 
> `lncli listpeers` shows:
> 
> ```
> {
>     "peers": [
>     ]
> }
> ``


 you get it why this was happening i am having the exact same issue

**Comment by halseth** [comment]
@vyomeshaudi6 This is quite an old issue. Could you please open a new one if you see this with the latest version?
