### ISSUE TITLE
Reconnecting to Peer. Connection Refused.

### ISSUE THREAD

**Issue by bruceleeroy18** [lightningnetwork/lnd#1561]
### Background

Had an active channel with TorGuard for a while. I rebooted computer and now lnd will not reconnect to this channel. I could force close it, but thought it was giving an odd response to my lncli connect attempts. 

### Your environment

* lnd v. 0.4.2
* ubuntu mate 18.04
* bitcoind

### Steps to reproduce

lncli connect 03557fd11b58cb93d2ad4fab4dd4cff7462a97e21e8f6b7a712cb8bd27a96b9eef@188.166.23.129:9735
[lncli] rpc error: code = Unknown desc = dial tcp 188.166.23.129:9735: connect: connection refused

Debug Log
2018-07-15 00:02:15.304 [WRN] SRVR: Already have 1 persistent connection requests for 03557fd11b58cb93d2ad4fab4dd4cff7462a97e21e8f6b7a712cb8bd27a96b9eef@188.166.23.129:9735, connecting anyway.
2018-07-15 00:02:15.305 [DBG] SRVR: Connecting to 03557fd11b58cb93d2ad4fab4dd4cff7462a97e21e8f6b7a712cb8bd27a96b9eef@188.166.23.129:9735
2018-07-15 00:02:15.409 [ERR] SRVR: Unable to connect to 03557fd11b58cb93d2ad4fab4dd4cff7462a97e21e8f6b7a712cb8bd27a96b9eef@188.166.23.129:9735: dial tcp 188.166.23.129:9735: connect: connection refused
2018-07-15 00:02:15.410 [ERR] RPCS: (connectpeer): error connecting to peer: dial tcp 188.166.23.129:9735: connect: connection refused

### Expected behaviour

lnd should reconnect to peer. Then channel should become present when calling listpeers, and active when calling listchannels. 

### Actual behaviour

no connection established.

**Comment by Xian001** [comment]
ACKing here. Experiencing the same issue.

**Comment by wpaulino** [comment]
> lnd should reconnect to peer. Then channel should become present when calling listpeers, and active when calling listchannels.

`lnd` already does this. We'll continually attempt to reconnect to a peer using a backoff. If the peer is down however, there's not much we can do but wait. I'm unable to connect to them at the moment, which most likely means they're offline and have been since you came across this.

**Comment by Roasbeef** [comment]
> 2018-07-15 00:02:15.409 [ERR] SRVR: Unable to connect to 03557fd11b58cb93d2ad4fab4dd4cff7462a97e21e8f6b7a712cb8bd27a96b9eef@188.166.23.129:9735: dial tcp 188.166.23.129:9735: connect: connection refused

As you can see, they've either changed their IP or are no longer listening on the proper port.

**Comment by Roasbeef** [comment]
I'm unable to connect as well. Closing this as it looks to be an issue with TorGuard, and not `lnd`.

**Comment by bruceleeroy18** [comment]
Thanks for your time. 


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Olaoluwa Osuntokun <notifications@github.com> Date: 7/16/18  15:58  (GMT-05:00) To: lightningnetwork/lnd <lnd@noreply.github.com> Cc: bruceleeroy18 <browningsmith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [lightningnetwork/lnd] Reconnecting to Peer. Connection Refused.
  (#1561) 
I'm unable to connect as well. Closing this as it looks to be an issue with TorGuard, and not lnd.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lightningnetwork/lnd","title":"lightningnetwork/lnd","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lightningnetwork/lnd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Roasbeef in #1561: I'm unable to connect as well. Closing this as it looks to be an issue with TorGuard, and not `lnd`. "}],"action":{"name":"View Issue","url":"https://github.com/lightningnetwork/lnd/issues/1561#issuecomment-405362622"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lightningnetwork/lnd/issues/1561#issuecomment-405362622",
"url": "https://github.com/lightningnetwork/lnd/issues/1561#issuecomment-405362622",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [lightningnetwork/lnd] Reconnecting to Peer. Connection Refused. (#1561)",
"sections": [
{
"text": "",
"activityTitle": "**Olaoluwa Osuntokun**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Roasbeef",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lightningnetwork/lnd\",\n\"issueId\": 1561,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lightningnetwork/lnd/issues/1561#issuecomment-405362622"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356543838\n}"
}
],
"themeColor": "26292E"
}
]
