### ISSUE TITLE
[Feature Request] lncli should not ask for server tlscert if it is trusted by the machine

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#1562]
BTCPay will expose gRPC over an HTTPS connection with a trusted certificate from Let's encrypt.

Requiring the certificate on the user's machine is inconvenient.

# Workaround

We can download the certificate using `openssl` before using lncli.

```bash
HOST="testlnd1.btcpayserver.com"
LND_DEFAULT_PATH="/root/.lnd"
[ ! -f "$LND_DEFAULT_PATH" ] && mkdir $LND_DEFAULT_PATH
openssl s_client -showcerts -servername "$HOST" -connect "$HOST:443" < /dev/null \
                         | openssl x509 -outform PEM > "$LND_DEFAULT_PATH/tls.cert"
lncli --no-macaroons --rpcserver "$HOST:443" getinfo
```

**Comment by Roasbeef** [comment]
> --no-macaroons

Please don't expose a service to the public internet without macaroon authentication!

**Comment by NicolasDorier** [comment]
Of course I don't, just using this to know if the underlying server is responding with the expected error message.

**Comment by Roasbeef** [comment]
Gotcha, currently investigation a way to do this automatically if the host set is an actual domain.

**Comment by NicolasDorier** [comment]
@Roasbeef to be clear, the certificate still need to be verified to be trusted by the machine to prevent man in the middle. I don't know if this is easy in Go.

**Comment by Roasbeef** [comment]
Why not just include that script you have above as a pre-build check in the docker container?

**Comment by NicolasDorier** [comment]
because I can't suppose users have openssl (imagine windows users who want to connect to their LND node via lncli)

BTCPay expose publicly LND's gRPC interface, I would like to make it as painless to people to connect to it safely.

**Comment by NicolasDorier** [comment]
It is not needed by me, but I can already see the quesiton coming of people asking me why the handshake get rejected by lncli.

**Comment by Roasbeef** [comment]
The docker container can install that for the user so they don't have to. Where does Windows come into play here? Is that how users are expected to initially provision BTCPay?

**Comment by NicolasDorier** [comment]
People provision BTCPay on a VM in an hosting provider (mainly Azure, but can be any)

With BTCPay comes a LND node bundled into the docker, and whose gRPC access is exposed.

Now the user, from his personal laptop, might want to use `lncli` to administer his LND node.
Of course, he can also SSH into the VM and use lncli directly. But it is less convenient than just being able to use lncli from his personal laptop.
