### ISSUE TITLE
"walletbalance" does not update in a timely fashion after openchannel funding / bitcoind

### ISSUE THREAD

**Issue by Xian001** [lightningnetwork/lnd#1564]
### Background

When opening a channel with a peer, "walletbalance" does not update in a timely fashion, disallowing funding of other channels.

### Your environment

* $ lncli getinfo
{
    "identity_pubkey": "026bce917a5854f3c5140cc69c977d19a6d656554120b6dedf045b246941b858c5",
    "alias": "TexasRouter",
    "num_pending_channels": 1,
    "num_active_channels": 31,
    "num_peers": 35,
    "block_height": 532160,
    "block_hash": "0000000000000000002a63d85c14c381304870dfe9a7be266b2b0e0e2b9b35eb",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "026bce917a5854f3c5140cc69c977d19a6d656554120b6dedf045b246941b858c5@47.184.129.94:9735"
    ],
    "best_header_timestamp": "1531751999",
    "version": "0.4.2-beta commit=bc5bfeb479d5123ad3c9cfc8bf9636bb1535802e"

* $ uname -a
Linux bitcorn 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* bitcoind --$ ./bitcoin-cli --datadir=/mnt/bitcoin_data getnetworkinfo
{
  "version": 160100,
  "subversion": "/Satoshi:0.16.1/",
  "protocolversion": 70015,
  "localservices": "000000000000040d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 34,

### Steps to reproduce

1) `lncli walletbalance`
2) Ensure that "total_balance" and "confirmed_balance" are equal, and "unconfirmed_balance" at 0
3) Open a connection to a peer
4) Open a channel to the peer
5) "`walletbalance`" hasn't become spendable since opening channel

eg: 
```
$ lncli openchannel 03d301eedc0949238bf919452ee7ef5c45bda4adbe17faba4037170b3573841446 1000000
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.01 BTC only have 0 BTC  available
```

- Notice that `walletbalance` has been in a funky state for the last few hours

```
$ lncli walletbalance
{
    "total_balance": "9480691",
    "confirmed_balance": "0",
    "unconfirmed_balance": "9480691"
}
```

### Expected behaviour

walletbalance updates in a more timely fashion before allowing further funding.

### Actual behaviour

walletbalance remains in an unusable state due to funding being unconfirmed.

EDIT: `listchaintxns` shows my last tx as having 40 confirmations.
EDIT2: Decided to stop and restart `lnd` for... reasons... and problems persists.
EDIT3: `walletbalance` seemed to resolve, but the issue that preceded this issue remains for some-odd reason - cannot `openchannel` with the following peer - https://www.robtex.com/lightning/node/03d301eedc0949238bf919452ee7ef5c45bda4adbe17faba4037170b3573841446 - would time-out trying to fund the channel, necessitating a CTRL-C to abort and get on with my life.

**Comment by Roasbeef** [comment]
When we start to fund a channel, we'll lock those inputs selected in order to avoid concurrency issues. The locked inputs aren't reflected in `walletbalance` until after the channel is confirmed. If you're using `bitcoind`, and the node is remote, then it's possible that it's missing notifications at times which can get our wallet state of of sync. This issue will be fixed soon on our end, and a more fundamental fix may be packaged with a later release of `bitciond`.

**Comment by Roasbeef** [comment]
If the peer is unresponsive, then you won't be able to complete the channel funding handshake to successfully open the channel. If you have a single UTXO, then you'll need to wait for that to confirm before we can use the change output to open additional channels.
