### ISSUE TITLE
ZMQ connection refused

### ISSUE THREAD

**Issue by nharmon9** [lightningnetwork/lnd#1586]
### Background

Dial tcp connection refused 

### Your environment

* 0.4.2
* Darwin 17.4.0
* bitcoind
* mainnet
zmq things set to 127.0.0.1:28332

### Steps to reproduce

$lnd
unlock wallet

### Expected behaviour

It should start up lnd

### Actual behaviour

dial tcp 127.0.0.1:28332: connect : connection refused

**Comment by peername** [comment]
Do you have these lines in bitcoin.conf? 
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

**Comment by nharmon9** [comment]
Yes

**Comment by wpaulino** [comment]
`bitcoind` must be compiled with ZMQ support as it is not included by default.

**Comment by nharmon9** [comment]
I tried:
brew install zeromq
git clone "bitcoin repo"
make
sudo make install
all with the bitcoin.conf in the same folder with the block data having the lines mentioned above.
I may be really stupid but the one thing I haven't tried is restarting the computer.

**Comment by Roasbeef** [comment]
You just need to ensure that `bitcoind` is actually listening on those ports. If it isn't then you don't actually have zmq active.

**Comment by mandelmonkey** [comment]
> `bitcoind` must be compiled with ZMQ support as it is not included by default

Is this a recent change? I thought ZMQ was enabled by default or is that not the case with the latest bitcoind?

**Comment by halseth** [comment]
@mandelmonkey It was not default before, maybe it is now.
