### ISSUE TITLE
Append newline to openchannel and closechannel's outputs

### ISSUE THREAD

**Issue by 21E14** [lightningnetwork/lnd#160]
Trivial: “lncli openchannel” output seems to need a new line suffixed lest it flows into the bash prompt. Apparently, this impacts "lncli closechannel" too.

**Comment by Roasbeef** [comment]
Not sure how it appears in your prompt, but a successful `openchannel` command appears like this on my prompt:
```
lnd/cmd/lncli  0e29395 ✗                                                                                                                                                                                          14d ◒
▶ lncli openchannel --node_key=03c48c35c34a0992fe221fd8ed3367c0da9311f0d7d7b7ca5c02c4630bff107d36 --local_amt=10000
{
	"funding_txid": "8766cc7ab3c57e76a14c3aec9bbd2c1f26272781be8635c8f8071faf6d2c3783"
}%
```

**Comment by 21E14** [comment]
I get the following in the docker container:

{
	"funding_txid": "bunchofnumbers"
}root@1234567890:

Apparently, moli is seeing the same with closechannel (see #ln).
