### ISSUE TITLE
channel_update disable usage

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1605]
according to https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message

```
MAY create and send a channel_update with the disable bit set to 1, to signal a channel's temporary unavailability (e.g. due to a loss of connectivity) OR permanent unavailability (e.g. prior to an on-chain settlement).
MAY sent a subsequent channel_update with the disable bit set to 0 to re-enable the channel.
```

Are there any plans to implement this in lnd to signal loss of connectivity to a peer? It would avoid *many* dead ends in routing discovery.

Other than signalling that the channel with the peer is actually down, my opinion is that it could be used to signal other reasons for a channels unavailability, such as local balance being 0, so there is no point trying to push anything thru it.

if gossip volume is a concern, flap-dampening as in bgp4 or simply rate limiting would be trivial to implement which would further deter from trying to route via unstable nodes. analysing percentage of unavailable channels to a node could also be done to deem the node itself is probably unavailable too.

**Comment by Roasbeef** [comment]
Re-opening for now, as we're gonna go ahead and merge that linked PR as is. Atm, it only sends on channel closes, but at least paves the way to doing more in the future.

**Comment by robtex** [comment]
regarding flapping, just [re]start a timer each time the status changes. when timer is up, it means the channel stopped flapping so it is safe to update the status.
timer could be like 10 minutes so it won't spam updates even if ppl upgrade their node.
