### ISSUE TITLE
describegraph fails when expected node is not found

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#1607]
### Background

Getting graph details using `describegraph` results in a `ErrGraphNodeNotFound` error.

### Your environment

* `"version": "0.4.2-beta commit=bca926d6af69b117eb6afa0e50ec2dc32d2899d4"`
* Ubuntu 16.04.4 LTS
* Bitcoin Core 0.16.0

### Steps to reproduce

    lncli describegraph
    [lncli] rpc error: code = Unknown desc = unable to find node

### Expected behaviour

`describegraph` should return full results

### Actual behaviour

Error prevents graph listing

**Comment by wpaulino** [comment]
This should be fixed by #1600.

**Comment by Roasbeef** [comment]
Yep, it'll be fixed by that issue. I can also tag on a fix to just keep going and compute the graph even if a node isn't actually found.
