### ISSUE TITLE
Incorrect `final_incorrect_cltv_expiry` logic

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#1615]
It seems like currently `FailFinalIncorrectCltvExpiry` is sent in wrong circumstances when `proposed_expiry - grace < chain_height`: https://github.com/lightningnetwork/lnd/blob/b0288d46773ac6d45e5dc4d5e6a80dd3034d0b9f/htlcswitch/link.go#L2150-L2164

While according to https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md it should be sent when `The CLTV expiry in the HTLC doesn't match the value in the onion`.

**Comment by btcontract** [comment]
Found out when investigating https://github.com/btcontract/lnwallet/issues/77, that one is also suspicious but for different reasons.

**Comment by Roasbeef** [comment]
Yeah looks like we should actually be sending `final_expiry_too_soon` here.

**Comment by cfromknecht** [comment]
I'm on it!
