### ISSUE TITLE
lnd does not finish starting all watchers in  ChainArbitrator 

### ISSUE THREAD

**Issue by vegardengen** [lightningnetwork/lnd#1616]
[lnd.log](https://github.com/lightningnetwork/lnd/files/2225725/lnd.log)
### Background

I decided to force close some old channels with peers I hadn't seen for a month or more. I force-closed 5 channels in total. About the same time, I noticed someone creating dust channel of 20k satoshi with me, so after having force-closed, but before anything was confirmed I guess, I restarted node to set a minchansize parameter.

Describe your issue here.

After starting up lnd and unlocking wallet, it gets to ChainArbitrator, and begins starting close observers. After a variable number of successful close observer goroutines is started, it seems to get stuck and LND does not continue its work. It still answers to lncli commands, though.
### Your environment

* version of `lnd`

LND version 0.4.2-beta commit=e0baa4969035fc555b185d21acaa0b09aecdef6f
* which operating system (`uname -a` on *Nix)

Linux thundroid 4.14.24-113 #1 SMP PREEMPT Mon Mar 5 12:21:35 UTC 2018 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

Bitcoin Core Daemon version v0.16.0
Copyright (C) 2009-2018 The Bitcoin Core developers

* any other relevant environment details

### Steps to reproduce

Not sure if the above steps will reproduce or not....

### Expected behaviour

All chain watchers should start, and LND should continue startup.

### Actual behaviour

Tell us what happens instead

LND hangs in ChainArbitrator startup.

**Comment by vegardengen** [comment]
bitcoin@thundroid:~/log/lnd/bitcoin/mainnet$ lncli pendingchannels
{   
    "total_limbo_balance": "921438",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {   
            "channel": {
                "remote_node_pub": "0241cff95a87da9ca9b581b84ce2c15fb58a0879c951e6125ad2be04b12af8ff4c",
                "channel_point": "afceff0e9a1a9875460e0cb819155e97bcd0f37337b539b35983b6a04774bf75:0",
                "capacity": "100000",
                "local_balance": "1453",
                "remote_balance": "0"
            },
            "limbo_balance": "1453"
        },
        {   
            "channel": {
                "remote_node_pub": "025a596f3023eb914d6041bbb75d9d274b8131596aa9c6eecff72fa45de9927fbc",
                "channel_point": "ad01a921838dafbbf674efa6952a2c6db6ce128d31d36b5734a7097a5f372c28:1",
                "capacity": "284324",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {   
            "channel": {
                "remote_node_pub": "025ce4e3a87a832a535aabc2b33ec06eadd55568824484ff03e2b2bd5302b733af",
                "channel_point": "002288803fe566290aa5551ee8bd2d8c0e737b5e3aeb6d476f5930c36567c0ca:1",
                "capacity": "200000",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {   
            "channel": {
                "remote_node_pub": "029e2a4faea100086a10c23d253ec4d5ae26d9015a8a7d756a17ecff4b923db923",
                "channel_point": "00ed181d67cacc3ebc8a9e0f3775ded4aa21c60727528d5d12a420b31dfab4d8:0",
                "capacity": "1000000",
                "local_balance": "919985",
                "remote_balance": "0"
            },
            "limbo_balance": "919985"
        },
        {   
            "channel": {
                "remote_node_pub": "03341b688f09301a8c0f7528b587bd59db9f8e3f9aec46da19061911d8debf11a2",
                "channel_point": "f8786cfba4eebb2e1f7e041e6e5260e15b8c1b1a921b45651e9163bc14fecbc8:0",
                "capacity": "10000",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        }
    ]
}
bitcoin@thundroid:~/log

**Comment by vegardengen** [comment]
``bitcoin@thundroid:~/log/lnd/bitcoin/mainnet$ lncli pendingchannels
{   
    "total_limbo_balance": "921438",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {   
            "channel": {
                "remote_node_pub": "0241cff95a87da9ca9b581b84ce2c15fb58a0879c951e6125ad2be04b12af8ff4c",
                "channel_point": "afceff0e9a1a9875460e0cb819155e97bcd0f37337b539b35983b6a04774bf75:0",
                "capacity": "100000",
                "local_balance": "1453",
                "remote_balance": "0"
            },
            "limbo_balance": "1453"
        },
        {   
            "channel": {
                "remote_node_pub": "025a596f3023eb914d6041bbb75d9d274b8131596aa9c6eecff72fa45de9927fbc",
                "channel_point": "ad01a921838dafbbf674efa6952a2c6db6ce128d31d36b5734a7097a5f372c28:1",
                "capacity": "284324",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {   
            "channel": {
                "remote_node_pub": "025ce4e3a87a832a535aabc2b33ec06eadd55568824484ff03e2b2bd5302b733af",
                "channel_point": "002288803fe566290aa5551ee8bd2d8c0e737b5e3aeb6d476f5930c36567c0ca:1",
                "capacity": "200000",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {   
            "channel": {
                "remote_node_pub": "029e2a4faea100086a10c23d253ec4d5ae26d9015a8a7d756a17ecff4b923db923",
                "channel_point": "00ed181d67cacc3ebc8a9e0f3775ded4aa21c60727528d5d12a420b31dfab4d8:0",
                "capacity": "1000000",
                "local_balance": "919985",
                "remote_balance": "0"
            },
            "limbo_balance": "919985"
        },
        {   
            "channel": {
                "remote_node_pub": "03341b688f09301a8c0f7528b587bd59db9f8e3f9aec46da19061911d8debf11a2",
                "channel_point": "f8786cfba4eebb2e1f7e041e6e5260e15b8c1b1a921b45651e9163bc14fecbc8:0",
                "capacity": "10000",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        }
    ]
}
bitcoin@thundroid:~/log

**Comment by wpaulino** [comment]
@vegardengen, follow the [debugging docs](https://github.com/lightningnetwork/lnd/blob/master/docs/debugging_lnd.md#capturing-pprof-data-with-lnd) and post a goroutine dump of whenever you think the node is stuck.

**Comment by vegardengen** [comment]
Well. After @Roasbeef said they would eventually finish, I decided to let it linger over the night.

It's now morning, 4 out of 5 pending channels has gone from waiting to pending.

**Comment by vegardengen** [comment]
To help catching this issue, I restarted with profiling. This is what is going on when it scans for the last channel close TXID (8 hours later)

[goprofile.log](https://github.com/lightningnetwork/lnd/files/2226513/goprofile.log)
