### ISSUE TITLE
Feature request: dynamic host resolution to continually update external IPs

### ISSUE THREAD

**Issue by jpentland** [lightningnetwork/lnd#1624]
### Background

Currently the advertised IP address can only be configured by either setting `externalip` at startup, or using the `nat` option to automatically retrieve the IP address. In cases where this fails there is currently no fallback option to allow the user to set the IP themselves at runtime.

### Solution

Add a command  `setaddr` to `lnrpc` that allows the user to modify the list of advertised IP addresses and
have the new list broadcast to the network.

There are multiple ways a user might want to use this:
* Set single or multiple IP addresses and remove existing ones.
* Add a new IP address to the list of current IP addresses.
* Add additional addresses while retaining only a subset of the existing ones.

A solution to this would be to allow the user to specify a list of addresses, with the option of either replacing or appending to the current list. The above cases could be achieved in the following ways:

* Set single or multiple IP addresses and remove existing ones.
  - Replace the current list with a new list.
* Add a new IP address to the list of current IP addresses.
  - Append to the current list.
* Add additional addresses while retaining only a subset of the existing ones.
  - Retrieve the current list with 'getInfo', modify it locally and use `setaddr` to replace the list with the locally created one.

The only case not covered by this would be to delete all advertised addresses (thus advertising no addresses).

Usage examples (with lncli):
```
lncli setaddr 87.133.148.162:9735
lncli setaddr 87.133.148.162:9735,2001:db8:a0b:12f0::1:9735
lncli setaddr --append 87.133.148.162:9735
```

### Status

I am currently preparing a pull request for this.

**Comment by rootzoll** [comment]
@Roasbeef is there any progress on this feature request? Or any other solution to update advertised IPs for nodes behind a router with a changing IPs and dynamic dns?

**Comment by Roasbeef** [comment]
For router behind dynamic ips, there's a PR open to update the NAT code to
detect ip changes, remap and the re announce the new ips.

On Nov 3, 2018 8:40 PM, "Christian Rotzoll" <notifications@github.com>
wrote:

@Roasbeef <https://github.com/Roasbeef> is there any progress on this
feature request? Or any other solution to update advertised IPs for nodes
behind a router with a changing IPs and dynamic dns?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1624#issuecomment-435639513>,
or mute the thread

**Comment by rootzoll** [comment]
As far as I understood the NAT code is that it will not work with every router a node is behind, correct? A manual way to update it, would provide a solid way to make the RaspiBlitz reachable in every setup.

**Comment by Roasbeef** [comment]
So this came up in another context, and we're going to look up allowing users to specify a new flag something like `--externalhosts`. Internally, `lnd` would then periodically resolve the domain name to see if the IP changed, sending out a new `NodeAnnouncement` if so.
