### ISSUE TITLE
lncli getinfo "too many open files"

### ISSUE THREAD

**Issue by lobsterpub** [lightningnetwork/lnd#1631]
### Background

I was having issues when running 'lncli getinfo' and getting 2 variations of the a message saying "too many files open" and was told in the slack to try raising my open file limit to 500000, previously the soft limit was 1024 and hard limit 4096.

### Your environment

* LND commit eobaa496
* ubuntu 16.04
* bitcoind 0.16
* LND and bitcoind running under user bitcoin
* 0 open channels

```
bitcoin ~ ฿ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31321
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 500000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31321
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

bitcoin ~ ฿ ulimit -n
500000

bitcoin ~ ฿ ulimit -u
31321
```

### Steps to reproduce

Restart LND, wait at least several hours (usually overnight) and run 'lncli getinfo'. When the issue first starts happening I will get the 'too many open files' message about 50% of the time, the longer I let my node run the more likely I get the message (~90%+)

### Expected behaviour

Get a readout of the current lnd node info.

### Actual behaviour

```
bitcoin ~ ฿ lncli getinfo
[lncli] rpc error: code = Unknown desc = unable to sync PoV of the wallet with current best block in the main chain: Post http://localhost:8332: dial tcp: lookup localhost: too many open files

bitcoin ~ ฿ lncli getinfo
[lncli] rpc error: code = Unknown desc = unable to get best block info: Post http://localhost:8332: dial tcp: lookup localhost: too many open files
```

**Comment by vegardengen** [comment]
Is there lots of connections if you check?

`netstat -an` will tell you that.

`lsof -p <pid>` where <pid> is the process id of lnd will show you what files lnd has open. Keep in mind that a network connection is a file.

you can find the process ID of lnd if you do `ps -fu bitcoin`

**Comment by Roasbeef** [comment]
I'd check to see if someone is attempting to drain your set of file descriptors. Is the bitcoind node remote?

**Comment by lobsterpub** [comment]
I manually updated bitcoind to 0.16.1, the Ubuntu PPA is still at 0.16, after reading about something similar regarding 'too many open files' on bitcoin's github.  It has been running about 24 hours and no errors.

@vegardengen after I updated I ran the commands you suggested and it didn't look like there were that many files open, maybe a couple hundred at most. 

@roasbeef I don't know how to check or verify if someone is draining my file descriptors.

Seems fixed now.

**Comment by vegardengen** [comment]
The file descriptors and connections will reset as you restart the programs. You should keep a watch on this - and keep these commands handy.

`netstat -an` and `netstat -an | wc  -l` - see if they are increasing.
`lsof -p <pid of LND>`

**Comment by lobsterpub** [comment]
Still no errors, *fingers crossed.

`netstat -an | wc -l` is showing between 700-900.

**Comment by lobsterpub** [comment]
The error is back again

`netstat -an | wc -l` showing 805

I don't see anything in the LND or bitcoind logs.

**Comment by lobsterpub** [comment]
This is all I see in the dubug.log related to the RPC server.

```
2018-07-29 04:03:08 Received a POST request for / from 127.0.0.1:59666
2018-07-29 04:03:08 ThreadRPCServer method=getblockhash
2018-07-29 04:03:08 Received a POST request for / from 127.0.0.1:59668
2018-07-29 04:03:08 ThreadRPCServer method=getblock
```

**Comment by Roasbeef** [comment]
Closing for now as the issue seems to have been resolved after upgrading `bitcoind`.
