### ISSUE TITLE
[Test flake] htlc mismatch: predicate not satisfied after time out

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1632]
The integration test suite currently fails sometimes with the error 
```
    --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_local_chain_claim (7.50s)
    --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_remote_chain_claim (7.45s)
    --- FAIL: TestLightningNetworkDaemon/switch_circuit_persistence (37.02s)
    	lnd_test.go:74: Failed: (switch circuit persistence): exited with error: 
    		*errors.errorString htlc mismatch: predicate not satisfied after time out
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:9428 (0xc089ce)
    			testSwitchCircuitPersistence: t.Fatalf("htlc mismatch: %v", err)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:99 (0xbcaccb)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:11258 (0xc236ba)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f6aa0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
```
See for instance: https://travis-ci.org/lightningnetwork/lnd/jobs/407553324

This is the line where it fails: https://github.com/lightningnetwork/lnd/blob/5299472fad9e67d2875892f304641f80fb7ce325/lnd_test.go#L9428

It most often happen on Travis, which indicates this is more likely to happen on slow boxes.

### Steps
- [ ] (easy) Correct the error logging for this error. `assertNumActiveHtlcs` should be changed to return an error indicating how many HTLCs were active when failure happened.
- [ ] Get rid of the test failure.

**Comment by jarole** [comment]
same issue here. How to fix it?

**Comment by halseth** [comment]
Might be fixed by https://github.com/lightningnetwork/lnd/pull/1608

**Comment by offerm** [comment]
@jarole can you please share the link to the travis build which failed?

**Comment by halseth** [comment]
@offerm Can you open a new issue for the failure, if you believe it is not covered by #1608? Thanks!

**Comment by offerm** [comment]
@halseth Yes. I'm now sure it is a different problem. Real problem not detected on time due to a problem  in this code:

```
func assertNumActiveHtlcs(nodes []*lntest.HarnessNode, numHtlcs int) error {
	req := &lnrpc.ListChannelsRequest{}
	ctxb := context.Background()
	for _, node := range nodes {
		nodeChans, err := node.ListChannels(ctxb, req)
		if err != nil {
			return err
		}

		for _, channel := range nodeChans.Channels {
			if len(channel.PendingHtlcs) != numHtlcs {
				return fmt.Errorf("expected %v HTLCs, got %v",
					numHtlcs, len(channel.PendingHtlcs))
			}
		}
	}

	return nil
}

```

The code aim to check that all nodes see `numHtlcs` HTLCs in their channels. 

The code is not ready for a case that a node reports zero channels. In such a case, the node is considered "good" while it is not. 

Do you want me to open a new issue to just modified #1608 where the problem was reported (was closed by @Roasbeef too early)?

I'm still trying to explain why the channel between Bob and Alice removed. Think it is related to #1588.

**Comment by halseth** [comment]
@offerm Good catch! yeah, looks like that method should return an error at the end.

Let's continue the discussion in the issue you opened :)
