### ISSUE TITLE
[Bug, REST]: no graph edges exist only on REST Proxy

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#1637]
It seems `getinfo` is sending back (via REST)

```
{"error":"no graph edges exist","code":2}
```

No error using gRPC.
Tried to restart... nothing fix it.

**Comment by Roasbeef** [comment]
Is this a fresh `lnd` node? We don't read from the graph database at all for `getinfo`. Also can you fill in the rest of the issue template for issues? It helps a bunch of repetitive back and forth on our end w.r.t asking questions about the commit, etc.

**Comment by NicolasDorier** [comment]
So here is the strange thing: This error was sent by the REST proxy but NOT by gRPC. (lncli was working fine)

I can't really reproduce, but I noticed it happened when I started LND while my node was not full synched. Somehow lnd got stuck.

I workaround this problem now by using a tool which delay lnd start until my node is fully synched and started. (https://github.com/btcpayserver/lnd/blob/dockerfile2/docker-entrypoint.sh#L52)

I could not reproduce since then.

I think there was several issue:
1. Why would REST Proxy send the error, but not gRPC?
2. Why the sync of LND was stuck?

They are probably related.

Anyway for now, I can't reproduce easily, and found a workaround which seems to work until now. 
Feel free to close this issue.

**Comment by Roasbeef** [comment]
>  Somehow lnd got stuck.

Stuck as in? At times `lnd` can stop getting new blocks from `bitcoind` if the zmq notification queue fills up and we miss a block notification as a result. A combo of #1579 and #1439 will resolve this.

**Comment by NicolasDorier** [comment]
I don't have the logs in hands, but when you first start LND, there is a period where it sync and show progress with block heights, something like "Synched up to block 380000".

It turns out that it was blocked to a certain height around 400000. Restart did not worked, we unstucked it by deleting the data folder of LND.
