### ISSUE TITLE
Suggestion for "channel reserve", "spendable amount", "available liquidity"

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#1639]
I know currently we have many issues that are priority... But if this is possible I would like to suggest for these items to be listed for each channel when we do `listchannels`: 

`channel_reserve_satoshis` = lists 1% of required channel reserve to help users aware of this fact.
`spendable_satoshis` = lists amount of money the user can spend.
`available_liquidity_satoshis` = lists available amount that can be used to route payments (which I think will be great to help users understand how routing works).

If someone can create code for these features, it would be great.  Thank you.

**Comment by orbitalturtle** [comment]
Taking this

**Comment by orbitalturtle** [comment]
Hi @molxyz! One question for you. Aren't spendable_satoshis and available_liquidity_satoshis the same value? Just want to make sure I'm not missing something...

**Comment by ZapUser77** [comment]
@orbitalturtle Well... depends.  If sum of remote_balance < sum of Local_balance, then Liquidity would be = sum of remote_balance and < spendable.
Not sure if that's what he meant or not, as "liquidity" wouldn't be on an individual channel, it'd be for the combination of channels... perhaps listed before any specific channel is listed? (Or after the entire list)
