### ISSUE TITLE
build fails with "undefined: sort.Slice"

### ISSUE THREAD

**Issue by AlexanderPavlenko** [lightningnetwork/lnd#164]
https://github.com/lightningnetwork/lnd/blob/5e11e56818efb60fd9d77522bb856eb0026199c8/routing/router.go#L1160

I guess, https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/Dockerfile#L1 needs to be updated to go 1.8

**Comment by Roasbeef** [comment]
Fixed as part of 761b0466ebb5a8e87e102024952ad873ed8ffc8f and 69b257154fea291ed5e9b02ffeff54a14a79754a.

Closing.
