### ISSUE TITLE
REQUEST: listchannels / listpeers to include peer "Alias" Info

### ISSUE THREAD

**Issue by Xian001** [lightningnetwork/lnd#1640]
### Background

When issuing a `listchannels` command, it is not immediately apparent which `remote_pubkey` name belongs to which alias.

This information would be useful to display.

### Your environment

`    "version": "0.4.2-beta commit=bca926d6af69b117eb6afa0e50ec2dc32d2899d4"
`
### Steps to reproduce

1) `lncli listchannels` 
2) Notice node `alias`es are not displayed

### Expected behaviour

Would be useful to display node `alias` in listchannels / listpeers

**Comment by Roasbeef** [comment]
You can easily loo up the alias of the node using `getnodeinfo`. As a result, there's no need for us to add this information in `listpeers` or `listchannels`. Aliases are also not to be relied upon. They're completely unreliable an non-unique.

**Comment by Xian001** [comment]
>Aliases are also not to be relied upon. They're completely unreliable an non-unique.

I know they are unreliable and non-unique, but you're effectively forcing two calls to get some, otherwise, interesting/human-readable information.

Instead of seeing the alias info in one call, we are forced to read in the entire list of channels, and then do a getnodeinfo for each pub_key.

I mean, it's something simple enough, that I'm thinking of just learning enough GoLang to patch things myself.

Would a simple patch like that be rejected ?

**Comment by Roasbeef** [comment]
Won't be out right rejected, but it won't have as high priority for review/testing compared to the other PR's.
