### ISSUE TITLE
Feature Request: Ability to route to Self as destination

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#1645]
Allowing payments to be sent back to one's self opens the door for channel balancing.

**Comment by ZapUser77** [comment]
If I understand the code right, this should allow self routing. 
Insert into Line 504 of Pathfind.go:
if r.selfNode.PubKeyBytes == target {
	ignoredVertexes[Vertex(target)] = struct{}{}
}

**Comment by ZapUser77** [comment]
I've successfully created a way to route to self, without creating infinite loops.
I just have to clean up the code changes, and I'll submit my first PR.  ^_^

**Comment by ZapUser77** [comment]
https://github.com/lightningnetwork/lnd/pull/1652

@Roasbeef The PR you said you were looking forward to.  ;)

**Comment by ZapUser77** [comment]
https://github.com/lightningnetwork/lnd/pull/1685

**Comment by philippgille** [comment]
Is this related to issue #482?

**Comment by ZapUser77** [comment]
@philippgille yes.  It's related, and would solve issue 482.  Code was submitted as PR1751, linked above, that would allow self routing.
