### ISSUE TITLE
Feature Request, Optimization: Add Global setting: MaxRoutingFee

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#1646]
Please add in a variable/setting "FastMaxRoutingFee".

As the network topology grows, it'll take longer and longer to find 'all paths within x hops'.
And
Most people aren't going to care about finding 'all paths'.  They just want to find ONE path that's not expensive.

By allowing the user to set a "FastMaxRoutingFee", once a route is found that is less than or equal to the number, it stops looking for additional paths.  This could cut path-finding time by more than 99.9+% as the topology grows to infinity.  
If no route is found below this number, the search continues then returns the cheapest one and asks permission if it is ok to send.
Default would be zero.  This number should be alterable with LNCLI commands.

**Comment by Roasbeef** [comment]
Do you now how Dijkstra'S works? It's very fast even with larger graphs. We don't try to find "all paths". There's already a way to set the fee limit for a payment, see `lncli sendpayment -h`. /

**Comment by ZapUser77** [comment]
"Do you now how Dijkstra'S works?"
I do now.  ^_^
Sorry to have wasted your time.
