### ISSUE TITLE
Use of iota

### ISSUE THREAD

**Issue by kulpreet** [lightningnetwork/lnd#1654]
### Background

I was messing with the thought about why `iota` was not used in loads of places. Then I came across a comment about `SingleFunder` and `DualFunder` in channel.go. https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L110

So I have two questions:

1. Can I create a PR to switch to iota in all places apart from the the explicit no go in channel.go?
2. Why is iota not considered stable. This kind of surprised me.

**Comment by Roasbeef** [comment]
We don't use iota for database code. Consider that someone adds a new value, but doesn't place it at the very end. All those keys will now differ from the existing mapping that was present on disk. It's safe to use it for values that only live in memory, and are never written to disk.
