### ISSUE TITLE
Channels 'disappearing'  unknown channels updates for channels active previously

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#1663]
### Background

Describe your issue here.

### Your environment

* version of `lnd` c48ecb85f69949dc25ce4cba730213d64c20297e
* which operating system (`uname -a` on *Nix) Ubuntu
* version of `btcd`, `bitcoind`, or other backend BTCD
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

I seem to be getting a lot of unknown channels updates, there are multiple.
This is a channel with ACINQ, Bitrefill has funds tied up there according to them.

They've also already closed it on their end.
https://paste.ubuntu.com/p/Ndxy4xP4sw/

https://www.robtex.com/btc/tx/aeb9b1c13fc99c45636dc94b3947a23f0077b9992c061f511deac894a75d88b1

Seems I have funds there bc1qzzg6as0hhdcvh7l7kzpdr7t9tdrq9v55nqt5qvjn4u0yw286rurqxd58qg, but seems my node is unaware of anything or the channel itself.
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by juscamarena** [comment]
It seems @robtex is also running into this as well, he's some logs from him: 
https://pastebin.com/8UG1TWQU

**Comment by Roasbeef** [comment]
If they're sending chan reest messages for channels they've already closed, then that would point to a bug in eclair? 

If the channel is still actually open, but we don't know of it ourselves, then it's possible that we forgot about the channel if it took too long to actually confirm. We'll forget a channel after 288 blocks. This is safe as since things are single funder, we don't lose any funds by doing so.

**Comment by juscamarena** [comment]
ACINQ were sending these when it was still open on their end, these messages stopped when they closed the channels from their end with ACINQ getting their funds at the point.

They were the funder of the channel and most of the funds were pushed my way after the fact (I can't verify, I don't have logs for that) so it probably was active and fully functioning at that point unless they burned funds. I didn't receive any of the funds on chain after the fact.

Here's how it shows up in closedchannels.
{
"channel_point": "0cf144448544b444d6f88dafb86370a474825f8d7d5bf016038beaaf119031fe:0",
           "chan_id": "0",
           "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
           "closing_tx_hash": "0000000000000000000000000000000000000000000000000000000000000000",
           "remote_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
           "capacity": "0",
           "close_height": 0,
           "settled_balance": "0",
           "time_locked_balance": "0",
           "close_type": "FUNDING_CANCELED"
       },

The channel didn't take long to confirm, 120 minutes, but no logs to see what lnd did.

https://btc.com/aeb9b1c13fc99c45636dc94b3947a23f0077b9992c061f511deac894a75d88b1#in_0

And the closing transaction above was closed two weeks later with two outputs them saying one of the was for bitrefill.

**Comment by juscamarena** [comment]
Actually seems the bigger output is theirs and was sweeped. Guess I should file and issue on their repo instead lol

**Comment by Roasbeef** [comment]
Closing for now as there've been no further updates, will re-open if the issue pops up again.
