### ISSUE TITLE
no disable bit on force-close

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1667]
lnd doesn't send lnd when making force-close

from the issue in #1664 

as i understand it, in 1664 it was the lnd side that force closed it.
regardless my lnd didn't send a disabled message, only saw one from the clighting side in gossip. checked two implementations listening to gossip, none of them recorded my side, only the opposite side.

on a properly disabled channel, both sides should signal disable, right? not just the one that first detected it?

`lnd version 0.4.2-beta commit=c48ecb85f69949dc25ce4cba730213d64c20297e`

(the lnd involved in the closure, the channel_update below is from an irrelevant version) 

```2018-07-31 22:29:03.916 [TRC] CRTR: New channel update applied: (*channeldb.ChannelEdgePolicy)(0xc428f2cd20)({
 SigBytes: ([]uint8) (len=70 cap=70) {
  00000000  30 44 02 20 55 98 74 3a  94 35 21 c8 b1 21 23 72  |0D. U.t:.5!..!#r|
  00000010  33 5f e5 60 f8 17 26 ca  e0 12 a2 47 d4 92 e3 0b  |3_.`..&....G....|
  00000020  84 a8 c0 85 02 20 1e 00  67 20 ae 9c 5b f1 a5 f6  |..... ..g ..[...|
  00000030  aa 80 51 1c 20 ce 7d 2b  7d 44 3e 7a a6 41 a4 62  |..Q. .}+}D>z.A.b|
  00000040  8c e3 26 d5 7b 15                                 |..&.{.|
 },
 sig: (*btcec.Signature)(<nil>),
 ChannelID: (uint64) 586950093339492353,
 LastUpdate: (time.Time) 2018-07-31 22:28:59 +0000 UTC,
 Flags: (lnwire.ChanUpdateFlag) 2,
 TimeLockDelta: (uint16) 14,
 MinHTLC: (lnwire.MilliSatoshi) 1000 mSAT,
 FeeBaseMSat: (lnwire.MilliSatoshi) 1000 mSAT,
 FeeProportionalMillionths: (lnwire.MilliSatoshi) 10 mSAT,
 Node: (*channeldb.LightningNode)(<nil>),
 db: (*channeldb.DB)(<nil>)
})```

**Comment by Roasbeef** [comment]
> as i understand it, in 1664 it was the lnd side that force closed it.

Nope, `c-lightning` force closed. 

> on a properly disabled channel, both sides should signal disable, right? not just the one that first detected it?

Nope, only one side will send it out. 

>  Flags: (lnwire.ChanUpdateFlag) 2,

Looks disabled to me...

**Comment by Roasbeef** [comment]
Closing as we disable when we force close, and would only _learn_ of the remote side force closing if it hit the chain, in which case, the entire network would also detect.
