### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cyclopes2011** [lightningnetwork/lnd#1672]
### Background

(Please adjust issue title to be more accurate once root cause is identified. I realize this may be a generic panic error message. Thank you.)

I have been running a node for several months and I have recently added more funds to the node. I manually added channels but have now also configured autopilot to help find the best connections. I shutdown the node several times with 'lncli stop' while making changes/updates to the lnd.conf file to configure autopilot. On a recent shutdown of LND, the restart resulted in a crash as documented below.

Not sure where to start on this one...researched similar issues here and found patches or code updates were required. I am not a developer so please let me know in detail what additional information, debugs, etc. you need.

Thank you for your assistance.

### Your environment

* lnd version 0.4.2-beta commit=f6ea91af713546174bf04a79302116aa455d89c8 (This started on the commit prior to the current commit. I updated to see if it would resolve the issue.)
* Linux steropes 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255
* Bitcoind is running on a dedicated node/separate from LND node (node name: steropes).

### Steps to reproduce

After a clean reboot, I started 'tmux' and split two terminal windows. The top terminal started LND and the bottom executed 'lncli unlock' to unlock the wallet.

From the LND terminal window, this panic error follows the output from the log file attached below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x678fae]

goroutine 87 [running]:
github.com/lightningnetwork/lnd/chainntnfs.(*TxConfNotifier).Register(0x0, 0xc420923080, 0x0, 0x0)
        /home/jfears/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/txconfnotifier.go:121 +0x2e
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterConfirmationsNtfn(0xc42026a070, 0xc4203276e0, 0xc420946200, 0x22, 0x1f4, 0x8296400000006, 0xc4201e27c4, 0x4eebe3, 0xc4201e27c0)
        /home/jfears/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:799 +0x192
main.(*fundingManager).annAfterSixConfs(0xc4200c0700, 0xc42055d800, 0xc420921070, 0x0, 0x0)
        /home/jfears/gocode/src/github.com/lightningnetwork/lnd/fundingmanager.go:2104 +0x37c
main.(*fundingManager).Start.func4(0xc4200c0700, 0xc420921070, 0xc420558740, 0xc42055d800)
        /home/jfears/gocode/src/github.com/lightningnetwork/lnd/fundingmanager.go:682 +0x76
created by main.(*fundingManager).Start
        /home/jfears/gocode/src/github.com/lightningnetwork/lnd/fundingmanager.go:679 +0x877
```

lnd.log (with debug level)
[lnd-2.log](https://github.com/lightningnetwork/lnd/files/2255055/lnd-2.log)

### Expected behaviour

LND should start without error or crash.

### Actual behaviour

LND crashes soon after startup.

**Comment by wpaulino** [comment]
Will be fixed by #1669.

**Comment by cyclopes2011** [comment]
Thank you!

**Comment by cyclopes2011** [comment]
Confirmed fixed.
