### ISSUE TITLE
Incorrect payment error message

### ISSUE THREAD

**Issue by grunch** [lightningnetwork/lnd#1680]
### Background

I have an open channel with "local_balance": "0", and I try to pay an Invoice to the node I'm direcly connected by the channel

### Your environment

* lnd version 0.4.2-beta commit=f0f5e11b826e020c11c37343bcbaf9725627378b
* Linux wepa 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* btcd version 0.12.0-beta

### Steps to reproduce
```
$ lncli payinvoice lnsb10u....cqde6eyq
```
### Expected behaviour

I'm a sender with not enough funds for this invoice, I should get an error message that indicates to me that I don't have enough funds

```
{
	"payment_error": "not enough funds",
	"payment_preimage": "",
	"payment_route": null
}
```

### Actual behaviour

I receive this error message

```
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
```

**Comment by ccdle12** [comment]
would be happy to work on this one

**Comment by ZapUser77** [comment]
Could change the message to "Unable to find a path with sufficient funds to destination".

This would be more accurate overall.  Because, even if there "is a path" to destination, it's ignored if the bandwidth/capacity is lower than amount being sent.

**Comment by ccdle12** [comment]
> Could change the message to "Unable to find a path with sufficient funds to destination".
> 
> This would be more accurate overall. Because, even if there "is a path" to destination, it's ignored if the bandwidth/capacity is lower than amount being sent.

Hi @ZapUser77,

That was a good point about the the accuracy of the message. I've created a PR that returns the error suggested and checks in pathFind whether the route has sufficient funds to the destinatino.

**Comment by tzarebczan** [comment]
I just ran into this, definitely should be clearer to the user! Whatever happened to ^ PR.

**Comment by joostjager** [comment]
Besides a failure when there is no local balance, it could also be informative to return another dedicated message if the final node has no channel that is large enough in capacity.
