### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by toxicacd** [lightningnetwork/lnd#1682]
As of late LND doesn't compile in my windows environment anymore.
Build fails when building dependancy neutrino.

* LND Commit=f0f5e11b826e020c11c37343bcbaf9725627378b
* Windows10

### Steps to reproduce
git pull
make && make install

### Error
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/headerfs
vendor\github.com\lightninglabs\neutrino\headerfs\truncate_windows.go:30:7: undefined: ExtendedFilter
make: *** [build] Error 2****

**Comment by Roasbeef** [comment]
[This has been fixed in neutrino](https://github.com/lightninglabs/neutrino/pull/79), and will soon be fixed in `lnd` itself. Will close this issue once the PR which updates the deps lands.

**Comment by Roasbeef** [comment]
Fixed by 61681a59ebba768c6618e289f28c3896439de3f8
