### ISSUE TITLE
Gopkg.lock is out of sync with Gopkg.toml and project imports

### ISSUE THREAD

**Issue by mrfelton** [lightningnetwork/lnd#1686]
### Background

Running the following commands to install lnd results in changes to `Gopkg.lock`.

```
cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull
make && make install
```

After running make, the following error is printed, before listing out all of the specific things that are out of sync.

> Gopkg.lock is out of sync with Gopkg.toml and project imports

After everything has been installed, the repo is left in a dirty state with a changed `Gopkg.lock` file.

This is basically the same issue as reported in https://github.com/lightningnetwork/lnd/issues/993.

### Your environment

* lnd master
* Darwin

### Steps to reproduce

Follow the installation steps as outlined in `INSTALL.md` and then run `git status`. 

### Expected behaviour

`Gopkg.lock` should not be changed and git should be in a clean state after installing.

### Actual behaviour

Repo is in a changed state and Gopkg.lock` is marked as dirty (it has lots of changes).

**Comment by halseth** [comment]
@mrfelton Try pulling the latest version of `dep` and see if that helps.

**Comment by bob-333** [comment]
I just had the same issue and was unable to resolve it without removing the whole `gocode` directory and reinstalling from scratch.

When I tried to `git pull`, I saw:

```Updating 098cd940..47788c3c
error: Your local changes to the following files would be overwritten by merge:
	Gopkg.lock
Please commit your changes or stash them before you merge.```

I hadn't modified the file at all, but it was indeed different:

```$ git diff
diff --git a/Gopkg.lock b/Gopkg.lock
index 844640b4..aeaa5651 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -3,22 +3,27 @@
 
 [[projects]]
   branch = "master"
+  digest = "1:3c2fd21de8c94d23641d11c374e56ec10a3833a1a412d639ef3b6d48d7798c81"
   name = "git.schwanenlied.me/yawning/bsaes.git"
   packages = [
     "ct32",
     "ct64",
     "ghash",
-    "internal/modes"
+    "internal/modes",
   ]
+  pruneopts = "UT"
   revision = "e06297f34865a50b8e473105e52cb64ad1b55da8"
 
 [[projects]]
   branch = "master"
+  digest = "1:9a112e9f617878a9a643fdfcb7c31afaf0cf8859b8c179bf6bf53f9f881be695"
   name = "github.com/NebulousLabs/fastrand"
   packages = ["."]
+  pruneopts = "UT"
   revision = "3cf7173006a0b7d2371fa1a220da7f9d48c7827c"
 
 [[projects]]
+  digest = "1:0e85dfcc0eab64bc0c24247bf91045e44295121181c3c3d822e427404320ba56"
   name = "github.com/NebulousLabs/go-upnp"
   packages = [
     ".",
@@ -27,42 +32,52 @@
     "goupnp/httpu",
     "goupnp/scpd",
     "goupnp/soap",
-    "goupnp/ssdp"
+    "goupnp/ssdp",
   ]
+  pruneopts = "UT"
   revision = "29b680b06c82d044ebea91bf3069038eb562df2a"
 
 [[projects]]
+  digest = "1:c9ef1fba766e914747fa05a9947a6312fb0ee0ddb89218b1d96dd28b5d17b67e"
   name = "github.com/Yawning/aez"
   packages = ["."]
+  pruneopts = "UT"
   revision = "4dad034d9db2caec23fb8f69b9160ae16f8d46a3"
 
[and lots more]
```

I tried moving the modified file out of the way and pulling again, and then the `git pull` ran without error. But then the `make` failed:

```$ make && make install
 Compiling dependencies.
dep ensure -v

# Bringing vendor into sync
grouped write of manifest, lock and vendor: failed to export github.com/btcsuite/btcd: fatal: failed to unpack tree object f899737d7f2764dc13e4d01ff00108ec58f766a9
: exit status 128
Makefile:113: recipe for target 'dep' failed
make: *** [dep] Error 1
```

I tried pulling a new version of `dep`:

```$ cd ../../golang/dep
$ git pull
```

That ran without error, so I went back and tried the `make` again:

```$ cd -
$ make
 Compiling dependencies.
dep ensure -v
grouped write of manifest, lock and vendor: scratch directory /home/light/gocode/src/github.com/lightningnetwork/lnd/.vendor-new already exists, please remove it
Makefile:113: recipe for target 'dep' failed
make: *** [dep] Error 1
```

It didn't like that a particular directory existed, so I moved it out of the way and tried again:

```$ mv .vendor-new .vendor-new.old1
$ make
 Compiling dependencies.
dep ensure -v

# Bringing vendor into sync
(1/20) Wrote github.com/btcsuite/golangcrypto@master: hash of vendored tree didn't match digest in Gopkg.lock
(2/20) Wrote github.com/miekg/dns@79bfde677fa81ff8d27c4330c35bda075d360641: hash of vendored tree didn't match digest in Gopkg.lock
(3/20) Wrote github.com/NebulousLabs/go-upnp@29b680b06c82d044ebea91bf3069038eb562df2a: hash of vendored tree didn't match digest in Gopkg.lock
grouped write of manifest, lock and vendor: failed to export git.schwanenlied.me/yawning/bsaes.git: fatal: failed to unpack tree object c0276d75487ef7aceab140c9eb31601dd7d18bd4
: exit status 128
Makefile:113: recipe for target 'dep' failed
make: *** [dep] Error 1
```

That gave me a new error about the Gopkg.lock being wrong. So I gave up and reinstalled from scratch:

```$ cd $GOPATH/..
$ mv gocode gocode.old1
$ go get -d github.com/lightningnetwork/lnd
$ cd $GOPATH/src/github.com/lightningnetwork/lnd
$ make && make install
```

and that seemed to get me back to a working lnd.

What did I do wrong, and how should I have recovered from it?

**Comment by halseth** [comment]
There seems to be a problem with using new version of `dep` if there is artifacts from an old version of `dep` lying around. So updating dep + re-cloning `lnd` looks like it resolves it.

**Comment by bob-333** [comment]
@Roasbeef replied on IRC, saying:

> 23:30 <@roasbeef> bob333: can just remove your old gopkg, or ratehr undo the changes, we updated the dep version, so the file is kinda out of whack

I don't know enough `go` to understand that I needed to do, but hopefully that helps people who have the same issue I had when updating their lnd installation.
