### ISSUE TITLE
Is it possible to display the wallet seed?

### ISSUE THREAD

**Issue by woodyjon** [lightningnetwork/lnd#1688]
I created a wallet. Everything is working fine. But I realized that I lost the 24-word seed that I had written when creating the wallet. I have the wallet password and the password that was asked for encrypting the seed. Is there some way to get that seed or do I need to send all the funds to myself, recreate a new wallet and fund that new wallet?
Thank you!

### Your environment

* version of `lnd`: lnd v0.4.2-beta
* which operating system (`uname -a` on *Nix): Linux raspberrypi 4.14.52-v7+
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core Daemon version v0.16.2

**Comment by Roasbeef** [comment]
Unfortunately, there isn't. However, you can create a new seed, then sweep your funds under that new seed and carry on. If it comes down to it, it's possible to modify `lnd` (atm) to dump out the HD seed (which is derived from the 24-word seed).

**Comment by woodyjon** [comment]
Thank you for your response. Could you please confirm the steps I should take to sweep and create a new wallet?:

1. Close all channels with `$ lncli closeallchannels` (will my funds be safe? will there be some delay to have access to my funds?)
2. Send my funds to another btc wallet with `$ lncli sendcoins [address]`
3. Stop lnd
4. Delete everything in .lnd except lnd.conf. Do I also delete the .macaroon files?
5. Restart lnd
6. Create a wallet with `$ lncli create`
7. Unlock it with `$ lncli unlock`
8. Send funds to it

**Comment by Roasbeef** [comment]
Yep that sounds correct. For the first step, it may be the case that some of your peers aren't online, so you'll need to wait up to a few days (depending on the channel size) in order to get your funds back.

**Comment by woodyjon** [comment]
OK thank you. And thank you for all you do!

**Comment by MasterNeuron** [comment]
> Is there a feature planned for displaying the mnemonic seed? Could use it right now and it shouldn't be that difficult to implement, right?

Yes, I need that too.

**Comment by mmotola** [comment]
srsly no one found a hack yet to the encrypted wallet? I mean, we have the password after all.. there must be some hack to get to the encrypted seed... every other wallet in bitcoin gives you the option to view the seed, why not have that option in LND? There's no security risk in showing it to the proven owner, it's just a lot of pain in resetting the whole wallet if we can't get to the seed... at the very least provide a way to backup the encrypted file in such a way that the wallet can be recovered with the password...

**Comment by guggero** [comment]
You can use [`chantools walletinfo --withrootkey`](https://github.com/guggero/chantools/blob/master/doc/chantools_walletinfo.md) to get the `xprv` of your `wallet.db`. You can't recover the seed itself because that's hashed before it's stored in the `wallet.db`. But with the extended master root key you can get all on-chain funds back (and also off-chain with some tricks).
