### ISSUE TITLE
Failed to process consensus server notification 

### ISSUE THREAD

**Issue by omkarsunku** [lightningnetwork/lnd#1695]
Hi,

Description
I am running a bitcoind(prune) background and lnd. I am getting error something like "Failed to process consensus server notification (name: blockconnected, detail: failed to store sync information 00000000000000000009062530da4a81da5cdd23999c15a16be443ec41b41b1e: failed to fetch block hash for height 535583: couldn't get hash from database)"
bitcoin-cli -getinfo
{
"version": 160000,
"protocolversion": 70015,
"walletversion": 159900,
"balance": 0.00000000,
"blocks": 535584,
"timeoffset": -1,
"connections": 8,
"proxy": "",
"difficulty": 5949437371609.53,
"testnet": false,
"keypoololdest": 1532664716,
"keypoolsize": 10000,
"paytxfee": 0.00000000,
"relayfee": 0.00001000,
"warnings": ""
}

lncli getinfo
{
"identity_pubkey": "0395f6d538b90efbad4c9d9e93a8d2a3fba48c29dff1c298069a521170dde1ba43",
"alias": "sts_lnd",
"num_pending_channels": 0,
"num_active_channels": 0,
"num_peers": 0,
"block_height": 535584,
"block_hash": "00000000000000000009062530da4a81da5cdd23999c15a16be443ec41b41b1e",
"synced_to_chain": false,
"testnet": false,
"chains": [
"bitcoin"
],
"uris": [
"0395f6d538b90efbad4c9d9e93a8d2a3fba48c29dff1c298069a521170dde1ba43@myip:9735"
],
"best_header_timestamp": "1532715932",
"version": "0.4.2-beta commit=a0b2fadea35fa4642daf4e9f56e6ecfe31d22ce1"
}
both lnd and bitcoind are at same height but I am not able to connect with any node. Here I am using bitcoind in prune is this the problem?
(Note:Bad english)

**Comment by Roasbeef** [comment]
> Here I am using bitcoind in prune is this the problem?

Yes that's the issue. We currently don't support `bitcoind` in pruned mode, as eventually (if lnd is down) it may prune out blocks that we actually need for various purposes. We have plans to eventually support this mode, but for now, you'll need to run a full archive node.

**Comment by omkarsunku** [comment]
@Roasbeef  Thanks
