### ISSUE TITLE
Make RPC fails with error code

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#1699]
I followed the instructions on  https://github.com/lightningnetwork/lnd/tree/master/lnrpc  and get this error:

home/lightningmaster/protoc/protoc/bin/protoc: 1: /home/lightningmaster/protoc/protoc/bin/protoc: Syntax error: "(" unexpected

This is using the rpc.proto that's at the current commit level.

**Comment by ZapUser77** [comment]
Same issue as: https://github.com/google/protobuf/issues/2071
If "Change the first line of gen_protos.sh to #!/usr/bin/env bash" happened, would that break it for other OS?
If so, can "Prompt user to use: bash gen_protos.sh" be added in?

**Comment by Roasbeef** [comment]
Closing this as seems to just be an environment issue.

**Comment by ZapUser77** [comment]
Oddly enough... ./ works fine now.  I think it has to do with the instructions.
I followed the ones in 1701 (which didn't work), except I added "checkout master" just after "Make install" of the protobuf.
After that, everything worked fine.
