### ISSUE TITLE
strange nLockTime on closing channels

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1710]
Sometimes the nLockTime looks fishy. Often it is 0 but in some cases, in this case i took a channel between two lnd:s, the value doesn't make sense to me

nLockTime: 543820130
which corresponds to
`Lock Time | 1987-03-27 05:08:50`

https://www.blockchain.com/btc/tx/2e60793fe0cbbab250ba65c1609fe72abbecfd250d8eee53357a6b0baeadc743

in this case it was no harm done, but if nLockTime is out of control, it might end up with unfortunate values.

is everything in order?

**Comment by Roasbeef** [comment]
Yep, we use the lock time and sequence to encode the state number using a mask known to both parties: https://github.com/lightningnetwork/lnd/blob/f6ea91af713546174bf04a79302116aa455d89c8/contractcourt/chain_watcher.go#L335

We can use the lock time below the current unix time safely, as it'll always be "valid". For the sequence num, we disable the relative lock time behavior, so we can use most of those bits.

**Comment by robtex** [comment]
ah. yeah. i guess as long as it is also >= 500000000 or it would be a block number.
thank you for clarifying the trick.
