### ISSUE TITLE
Restoring channel.db fails (corrupted database)

### ISSUE THREAD

**Issue by mariodian** [lightningnetwork/lnd#1715]
I've recently switched from HDD to SSD on my server and restored all the chain and graph files from the backup. 

But when I ran `lnd` it gave me the following error:

```
2018-08-10 11:09:28.040 [INF] LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
2018-08-10 11:09:28.040 [INF] LTND: Active chain: Bitcoin (network=mainnet)
panic: invalid freelist page: 61397, page type is branch

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*freelist).read(0xc4202a5260, 0x7f10f485e000)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/freelist.go:237 +0x2fd
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist.func1()
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:290 +0x12b
sync.(*Once).Do(0xc420240510, 0xc420449820)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist(0xc4202403c0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:283 +0x4e
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.Open(0xc420036a20, 0x30, 0x180, 0x15a4ae0, 0x30, 0xc4200369f0, 0x25)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:260 +0x38b
github.com/lightningnetwork/lnd/channeldb.Open(0xc4200369f0, 0x25, 0x3, 0xc4200369f0, 0x25)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:73 +0xe0
main.lndMain(0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:162 +0x3d8
main.main()
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:651 +0x26
```

I have no issues restoring the chain files (and access the chain funds) but `graph/mainnet/channel.db` seems corrupted.

Is there anything I could do about it or are my channels lost (I only had 0.03BTC in there so not a huge deal)? 

Thanks!

### Your environment

* lnd 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 (but I tried the latest commit too)
* version of `lnd`
* Linux hackisatongmachine 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Roasbeef** [comment]
Appears that the DB has been corrupted. The free list is no longer correct.

**Comment by Roasbeef** [comment]
You can try going back to your HDD (assuming the files are still there).

**Comment by mariodian** [comment]
Unfortunately, I've formatted it already :/

**Comment by Roasbeef** [comment]
Can you try copying it back over to the HDD and seeing if it makes a difference at all?

**Comment by Roasbeef** [comment]
Closing this for now as it isn't an direct issue with lnd, but will keep commenting to see if we can read the DB in a restricted state even just to be able to close out the channels.

**Comment by mariodian** [comment]
Moved it to the HDD. Got the same error. They way I was backing it up is I never shut down lnd and just copied the data folder to a local machine over rsync. 

I guess that's not the right way to do?

Is there any guideline how to safely keep the current state? Ideally without shutting down the daemon.

Thanks for help anyway!

**Comment by Roasbeef** [comment]
Hmm yeh if it was while lnd was operating, then it's possible you copied
over the data in an inconsistent state, which would've never actually been
written to disk

**Comment by mariodian** [comment]
Is there a way to automate the process without shutting down the daemon? I'm wondering how others keep their data safe.
