### ISSUE TITLE
failed to export golang.org/x/sys: fatal: failed to unpack tree object 

### ISSUE THREAD

**Issue by valuead** [lightningnetwork/lnd#1718]
~/go/src/github.com/lightningnetwork/lnd# git pull && dep ensure
Already up-to-date.
grouped write of manifest, lock and vendor: failed to export golang.org/x/sys: fatal: failed to unpack tree object 904bdc257025c7b3f43c19360ad3ab85783fad78
: exit status 128

**Comment by Xian001** [comment]
ACK. Experiencing this with latest master.

**Comment by cryptagoras** [comment]
Same, but I get it slightly different:
```
 Compiling dependencies.
dep ensure -v
# Bringing vendor into sync
grouped write of manifest, lock and vendor: failed to export github.com/btcsuite/btcd: fatal: failed to unpack tree object f899737d7f2764dc13e4d01ff00108ec58f766a9
: exit status 128
```

Env: Ubuntu 16.04 LTS
`go version go1.10 linux/amd64`

**Comment by cfromknecht** [comment]
Do any of you see a directory named `$GOPATH/src/github.com/lightningnetwork/lnd/.new-vendor`?

**Comment by cfromknecht** [comment]
Would first try removing `$GOPATH/src/github.com/lightningnetwork/lnd/vendor`. If you also see `$GOPATH/src/github.com/lightningnetwork/lnd/.vendor-new`, try removing that as well.

**Comment by Xian001** [comment]
Removed vendor as well as .vendor-new

```
~/gocode/src/github.com/lightningnetwork/lnd$ make
 Compiling dependencies.
dep ensure -v

# Bringing vendor into sync
(1/43) Wrote github.com/btcsuite/btclog@84c8d2346e9fc8c7b947e243b9c24e6df9fd206a: missing from vendor
(2/43) Wrote github.com/grpc-ecosystem/grpc-gateway@f2862b476edcef83412c7af8687c9cd8e4097c0f: missing from vendor
(3/43) Wrote github.com/juju/loggo@master: missing from vendor
(4/43) Wrote google.golang.org/genproto@df60624c1e9b9d2973e889c7a1cff73155da81c4: missing from vendor
(5/43) Wrote github.com/davecgh/go-spew@8991bc29aa16c548c550c7ff78260e27b9ab7c73: missing from vendor
grouped write of manifest, lock and vendor: failed to export git.schwanenlied.me/yawning/bsaes.git: fatal: failed to unpack tree object c0276d75487ef7aceab140c9eb31601dd7d18bd4
: exit status 128
Makefile:113: recipe for target 'dep' failed
make: *** [dep] Error 1
```

**Comment by Roasbeef** [comment]
Which version of dep are y'all using?

**Comment by Roasbeef** [comment]
The current files in the repo are generated using `v0.5.0`.

**Comment by Xian001** [comment]
> I think your best bet might be do re clone lnd all together.

I'm a total newbie gitard.

Suggestions on how to re-clone would be great. I followed the install directions on the main page, and, well, I has a sad still.

Have tried git reset --hard, git fetch --all... *shrugs*

I have no idea what's going on :(

**Comment by Roasbeef** [comment]
No problem! My re clone I mean _delete_ the `lnd` directory all together, and use `git clone` to fetch the repo again. 

> I have no idea what's going on :(

Sorry about this...I _think_ it's an issue on the `dep` side not properly managing it's caches

**Comment by Xian001** [comment]
Ok.

```
mv lnd lnd_old
go get -d github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
make && make install

sh startlnd.sh
unknown flag `bitcoind.zmqpath'
--bitcoind.zmqpath=tcp://127.0.0.1:28332
```

Getting closer... I guess...

**Comment by Roasbeef** [comment]
The args have changed a bit: https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#running-lnd-using-the-bitcoind-or-litecoind-backend

**Comment by Xian001** [comment]
*cries*

unknown flag `zmqpubrawblock

`--zmqpubrawblock=tcp://127.0.0.1:28332 --zmqpubrawtx=tcp://127.0.0.1:28333`

in startlnd.sh now

**Comment by Xian001** [comment]
LOL.

`unknown flag `zmqpubrawtx'
`
FML.

**Comment by Roasbeef** [comment]
Ensure that you're on `lnd` master. I don't know what is in `startlnd.sh`.

**Comment by Xian001** [comment]
`lnd --bitcoin.active --bitcoin.node=bitcoind --bitcoin.mainnet --debuglevel=info --bitcoind.rpcuser=xxx --bitcoind.rpcpass=yyy --zmqpubrawblock=tcp://127.0.0.1:28332 --zmqpubrawtx=tcp://127.0.0.1:28333 --bitcoind.dir=/mnt/md0/bitcoin_data`

I'm using the documentation @ https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

Have to think that's pulling master by default ?

**Comment by Roasbeef** [comment]
Yes, but ensure that you're doing `make install` so it's installed in your path.

**Comment by wpaulino** [comment]
Those are the options for `bitcoind`. For `lnd`, they are `--bitcoind.zmqpubrawblock` and `--bitcoind.zmqpubrawtx`. Please read the docs carefully.

**Comment by Xian001** [comment]
>Those are the options for bitcoind. For lnd, they are --bitcoind.zmqpubrawblock and --bitcoind.zmqpubrawtx. **Please read the docs carefully**.

I'm a moron.

Resolved issues in both bitcoin.conf and issues starting up lnd.

Appreciate the patience.

Up and running latest-and-greatest again.

**Comment by Roasbeef** [comment]
u

**Comment by valuead** [comment]
Why don't you put how you resolved here for the community?

**Comment by Xian001** [comment]
>Why don't you put how you resolved here for the community?

As wpaulino noted, I did not pay close enough attention to the command line parameters, and did not preface the following commands with "bitcoin."

`--bitcoind.zmqpubrawblock and --bitcoind.zmqpubrawtx`

I did verify I had the zmq settings properly defined in bitcoin.conf
