### ISSUE TITLE
lnd crashes after initiating rescan

### ISSUE THREAD

**Issue by MikeC-xx** [lightningnetwork/lnd#1721]
### Background

I have been running my lnd node for 4 months.
A problem started to appear recently: lnd crashes after "lncli unlock".

Can anyone help me out please?

Log debuglevel=debug:
Aug 11 09:43:50 RaspBolt systemd[1]: Started LND Lightning Daemon.
Aug 11 09:43:52 RaspBolt lnd[583]: Attempting automatic RPC configuration to bitcoind
Aug 11 09:43:52 RaspBolt lnd[583]: Automatically obtained bitcoind's RPC credentials
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.109 [INF] LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.109 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.274 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.336 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.337 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
Aug 11 09:43:52 RaspBolt lnd[583]: 2018-08-11 09:43:52.339 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
Aug 11 09:45:18 RaspBolt lnd[583]: 2018-08-11 09:45:18.292 [INF] LNWL: Opened wallet
Aug 11 09:45:18 RaspBolt lnd[583]: 2018-08-11 09:45:18.703 [INF] LTND: Primary chain is set to: bitcoin
Aug 11 09:45:18 RaspBolt lnd[583]: 2018-08-11 09:45:18.704 [INF] LTND: Initializing bitcoind backed fee estimator
Aug 11 09:45:27 RaspBolt lnd[583]: 2018-08-11 09:45:27.027 [INF] LNWL: Opened wallet
Aug 11 09:45:27 RaspBolt lnd[583]: 2018-08-11 09:45:27.032 [INF] LNWL: Started listening for blocks via ZMQ on tcp://127.0.0.1:29000
Aug 11 09:45:33 RaspBolt lnd[583]: 2018-08-11 09:45:33.207 [INF] LNWL: The wallet has been unlocked without a time limit
Aug 11 09:45:33 RaspBolt lnd[583]: 2018-08-11 09:45:33.207 [INF] LTND: LightningWallet opened
Aug 11 09:45:33 RaspBolt lnd[583]: 2018-08-11 09:45:33.263 [INF] HSWC: Restoring in-memory circuit state from disk
Aug 11 09:45:35 RaspBolt lnd[583]: 2018-08-11 09:45:35.313 [INF] HSWC: Payment circuits loaded: num_pending=482, num_open=50
Aug 11 09:45:36 RaspBolt lnd[583]: 2018-08-11 09:45:36.187 [INF] LNWL: Started rescan from block 00000000000000000011e1a89074fa3ecf2824b3baef8adc4a8f5f2c28d933e2 (height 536237) for 1315 addresses
Aug 11 09:45:36 RaspBolt lnd[583]: 2018-08-11 09:45:36.316 [INF] LNWL: Starting rescan from block 00000000000000000011e1a89074fa3ecf2824b3baef8adc4a8f5f2c28d933e2
Aug 11 09:45:38 RaspBolt systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 09:45:38 RaspBolt systemd[1]: lnd.service: Unit entered failed state.
Aug 11 09:45:38 RaspBolt systemd[1]: lnd.service: Failed with result 'exit-code'.

### Your environment

version 0.4.2 commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
running on Raspberry Pi
backend Bitcoin Core RPC client version v0.16.0

### Expected behaviour

Tell us what should happen

### Actual behaviour

lnd crashes after "lncli unlock"

**Comment by Roasbeef** [comment]
If you can somehow capture `stderr` what error shows?

**Comment by MikeC-xx** [comment]
I think this could be it:
`2018-08-14 08:04:51.409 [INF] LNWL: Started rescan from block 0000000000000000000a284a51525407a530a01d6e33ea1532625db372c300ef (height 536238) for 1315 addresses`
`2018-08-14 08:04:51.624 [INF] LNWL: Starting rescan from block 0000000000000000000a284a51525407a530a01d6e33ea1532625db372c300ef`
`2018-08-14 08:04:52.491 [ERR] SRVR: unable to create server: unable to read channel for chain_hash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000, node_key=038af0e15f3ef98e274f2d0e928ebe096214d12387ae9147a6681aa60e8edeefa2: unable to read channel data for chan_point=ed538ad9878a85c4ce7a3bc869fc206faca3563b574f4e862b44e408316b3311:1: unable to fetch chan info: no chan info found`

`unable to read channel for chain_hash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000, node_key=038af0e15f3ef98e274f2d0e928ebe096214d12387ae9147a6681aa60e8edeefa2: unable to read channel data for chan_point=ed538ad9878a85c4ce7a3bc869fc206faca3563b574f4e862b44e408316b3311:1: unable to fetch chan info: no chan info found`

**Comment by MikeC-xx** [comment]
I searched around for the same error and found issue #1476. I applied a patch described in the issue, compiled lnd and it works. Thanks for helping. Closing this issue.
