### ISSUE TITLE
channeldb+funding: implement streaming and regular RPCs for static backup format

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#175]
A request has come in to allow online backup of the databases used by `lnd` so that the process doesn't have to be stopped for backup.

The channel DB can be backed up using https://godoc.org/github.com/boltdb/bolt#Tx.WriteTo

The wallet DB can be backed up using https://github.com/btcsuite/btcwallet/blob/master/walletdb/interface.go#L203 (`DB.Copy()`).

**Comment by johynpapin** [comment]
Hello. Can I work on this issue?

**Comment by aakselrod** [comment]
Sure. This should be an easy one, since we're no longer planning on integrating a LevelDB back-end at this time.

**Comment by johynpapin** [comment]
In that case I will try to do that.
I want to make sure I understand the problem.
So I have to add an RPC to make a backup, and add the corresponding command in the cli?

**Comment by Roasbeef** [comment]
Note that this has evolved to the full static back up scheme. The goal here is to ensure there're no foot guns in the regular back up process for users.

**Comment by prusnak** [comment]
Is this being worked on? If yes, is there another tracking issue or pull request or even a branch name where the development takes place?
