### ISSUE TITLE
Try to start a docker but it goes wrong

### ISSUE THREAD

**Issue by zhouzhou84** [lightningnetwork/lnd#1753]
### Background

I force rm a container and try to start it again,but it return:
```
ubuntu@ip-172-31-15-69:~/gocode/src/github.com/lightningnetwork/lnd/docker$ docker-compose run -d --name alice lnd_btc
Starting btcd ... error

ERROR: for btcd  Cannot start service btcd: b'endpoint with name btcd already exists in network docker_default'

ERROR: for btcd  Cannot start service btcd: b'endpoint with name btcd already exists in network docker_default'
ERROR: Encountered errors while bringing up the project.
ubuntu@ip-172-31-15-69:~/gocode/src/github.com/lightningnetwork/lnd/docker$ 

```

### Your environment
```
ubuntu@ip-172-31-15-69:~$ uname -a 
Linux ip-172-31-15-69 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-15-69:~$ lnd -V
lnd version 0.4.2-beta commit=21841c9f6b065a625e5dcb68c18dfbf3ee25326b
ubuntu@ip-172-31-15-69:~$ lncli -v
lncli version 0.4.2 commit=21841c9f6b065a625e5dcb68c18dfbf3ee25326b
ubuntu@ip-172-31-15-69:~$ btcd -v
Error creating a default config file: open /home/ubuntu/sample-btcd.conf: no such file or directory
unknown flag `v'
Use btcd -h to show usage
ubuntu@ip-172-31-15-69:~$ btcd --version
btcd version 0.12.0-beta
ubuntu@ip-172-31-15-69:~$ 
```

### Steps to reproduce
1.start a alice docker  container
2.exit forcely and kill the procee
3.restart with "docker-composed"

how to go back ?

**Comment by xsb** [comment]
@zhouzhou84 I could not reproduce the issue but it looks like one of the containers that docker-compose launched is still attached to the default docker network. You can forcely remove it from there by doing this:

```
docker network disconnect -f docker_default btcd
```

If this succeeds, the dontainer is going to be detached from the network and your command will work as the first time. If you find any issue you can also run the following command and then try again:

```
docker rm -f alice btcd
```

I hope this helps!

**Comment by zhouzhou84** [comment]
Ok,thank you very much On 2018-08-21 04:53 , Xavi Soler Wrote: @zhouzhou84 I could not reproduce the issue but it looks like one of the containers that docker-compose launched is still attached to the default docker network. You can forcely remove it from there by doing this: docker network disconnect -f docker_default btcd
 If this succeeds, the dontainer is going to be detached from the network and your command will work as the first time. If you find any issue you can also run the following command and then try again: docker rm -f alice btcd
 I hope this helps! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Roasbeef** [comment]
Seems like this has been resolved? Will re-open if not.
