### ISSUE TITLE
htlc mismatch: predicate not satisfied after time out  - continue

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1761]
@halseth This issue is related to #1632.
IMHO, the conclusion that it is solved by #1608 is wrong.

> --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_local_chain_claim (7.50s)
>     --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_remote_chain_claim (7.45s)
>     --- FAIL: TestLightningNetworkDaemon/switch_circuit_persistence (37.02s)
>     	lnd_test.go:74: Failed: (switch circuit persistence): exited with error: 
>     		*errors.errorString htlc mismatch: predicate not satisfied after time out
>     		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:9428 (0xc089ce)
>     			testSwitchCircuitPersistence: t.Fatalf("htlc mismatch: %v", err)
>     		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:99 (0xbcaccb)
>     			(*harnessTest).RunTestCase: testCase.test(net, h)
>     		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:11258 (0xc236ba)
>     			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
>     		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f6aa0)
>     			tRunner: fn(t)
>     		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
>     			goexit: BYTE	$0x90	// NOP

The test which failed is `switch_circuit_persistence`. Logic is:  create channels C<->D<->A<->B,  Start C in a mode that cause it not to provide preimages, create 5 invoices by C, make 5 payments by B, check that all nodes has 5 pending HTLCS, restart, check again, Make C send the 5 preimages.

The problem is cause by A not sending the perimages to B.

This can be seen in A log file at time `2018-07-24 11:01:59.662`. A received 5 `UpdateFulfillHTLC` but never forwarded to B. The reason for that is that the channel between A and B was closed at `2018-07-24 11:01:57.437`. Relevant error message at 
`2018-07-24 11:01:57.361 [WRN] HSWC: ChannelPoint(cd518f4905100727cdbb4249b885aec4dba5435086122c3c5ead24127bd6b8b9:0): received unknown message of type *lnwire.ChannelReestablish`

All relevant log files are here. 
[output-39-Carol-02240054.log](https://github.com/lightningnetwork/lnd/files/2307998/output-39-Carol-02240054.log)
[output-38-Dave-028fdc5f.log](https://github.com/lightningnetwork/lnd/files/2307999/output-38-Dave-028fdc5f.log)
[output-1-Alice-038101c0.log](https://github.com/lightningnetwork/lnd/files/2308000/output-1-Alice-038101c0.log)
[output-0-Bob-02d3141f.log](https://github.com/lightningnetwork/lnd/files/2308001/output-0-Bob-02d3141f.log)

**Comment by Roasbeef** [comment]
Can this be melded into that prior issue rather than opening a new one?

**Comment by offerm** [comment]
@Roasbeef I opened a new issue for this one as requested by @halseth in #1632 after you decided to close it regardless my comment there that it is not related to #1608.

> @offerm Can you open a new issue for the failure, if you believe it is not covered by #1608? Thanks!

**Comment by cfromknecht** [comment]
Thank you for these logs @offerm! Something defintely seems off here, as we receive an additional channel reestablish after the link has (presumably) already received a prior one. I will start looking into probable causes

**Comment by cfromknecht** [comment]
Closing for now, since i think this was fixed in #1785
