### ISSUE TITLE
Estimated onchain funding/closing fee in rpc/rest api getinfo or getnetworkinfo

### ISSUE THREAD

**Issue by dmitryskorbovenko** [lightningnetwork/lnd#1762]
### Feature request

Good UX of channel opening demands to have ability to show to user the fee requiring for channel opening/closing.
Let's return current estimated onchain funding/closing fee in rpc/rest api calls like getinfo or getnetworkinfo, or create new one

**Comment by Roasbeef** [comment]
Demands? More like a nice to have I'd say, this is a job for GUI's not `lnd`. Duplicate of #1228.
