### ISSUE TITLE
[ERR] SRVR: unable to start server: unable to find node

### ISSUE THREAD

**Issue by bruceleeroy18** [lightningnetwork/lnd#1768]
### Background

Lightning node went down a couple days ago due to a power outage. Upon restarting my lncli debug says I cannot find a node and will automatically shut down. Can't run any grpc.

### Your environment

*  Version 0.4.2-beta commit=bca926d6af69b117eb6afa0e50ec2dc32d2899d4
* Linux. Ubuntu Mate 16.04
* bitcoind

lnd.conf: debuglevel=debug

maxpendingchannels=9
MinChanSize=20000
externalip=192.168.2.1

alias=browntown_BTC

bitcoin.mainnet=1
bitcoin.active=1
bitcoin.node=bitcoind

bitcoind.rpcuser=xxxx
bitcoind.rpcpass=xxxx
bitcoind.zmqpath=tcp://127.0.0.1:28332

autopilot.active=1
autopilot.maxchannels=6
autopilot.allocation=.75

bitcoin.conf: server=1
txindex=1
daemon=1
externalip=192.168.2.1
maxconnections=18
rpcuser=xxxx
rpcpassword=xxxx
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

Debug Log

lnd --bitcoin.active --bitcoin.mainnet 
2018-08-22 20:23:32.691 [INF] LTND: Version 0.4.2-beta commit=bca926d6af69b117eb6afa0e50ec2dc32d2899d4
2018-08-22 20:23:32.691 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-08-22 20:23:32.692 [INF] CHDB: Checking for schema update: latest_version=3, db_version=3
2018-08-22 20:23:32.751 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-08-22 20:23:32.751 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080

*Then I go to lncli unlock*

2018-08-22 20:09:20.599 [ERR] SRVR: unable to start server: unable to find node

2018-08-22 20:09:20.599 [INF] FNDG: Funding manager shutting down
2018-08-22 20:09:21.347 [INF] LTND: Shutdown complete
unable to find node

### Expected behaviour

lncli to open a connection to previously connected nodes.

**Comment by cfromknecht** [comment]
@Roasbeef @halseth maybe related to #1745?

**Comment by ZapUser77** [comment]
Did you start BitcoinD and let it sync before starting LND?

**Comment by Roasbeef** [comment]
Nah @cfromknecht, it's related to a bug that was fixed _right_ after that commit went in. We were pruning to early if a node had private channels. [This comment contains the workaround](https://github.com/lightningnetwork/lnd/issues/1684#issuecomment-411627092). New nodes (or those that skipped that commit) won't run into this issue.

**Comment by bruceleeroy18** [comment]
Yes sir, I have let bitcoind sync. Bitcoin-cli getblockchaininfo returns expected output. 


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- 原始訊息 --------自： ZapUser77 <notifications@github.com> 日期： 2018/8/22  21:25  (GMT-05:00) 至： lightningnetwork/lnd <lnd@noreply.github.com> 副本： bruceleeroy18 <browningsmith@gmail.com>, Author <author@noreply.github.com> 主旨： Re: [lightningnetwork/lnd] [ERR] SRVR: unable to start server: unable to find node (#1768) 
Did you start BitcoinD and let it sync before starting LND?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lightningnetwork/lnd","title":"lightningnetwork/lnd","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lightningnetwork/lnd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ZapUser77 in #1768: Did you start BitcoinD and let it sync before starting LND?"}],"action":{"name":"View Issue","url":"https://github.com/lightningnetwork/lnd/issues/1768#issuecomment-415244289"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lightningnetwork/lnd/issues/1768#issuecomment-415244289",
"url": "https://github.com/lightningnetwork/lnd/issues/1768#issuecomment-415244289",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [lightningnetwork/lnd] [ERR] SRVR: unable to start server: unable to find node (#1768)",
"sections": [
{
"text": "",
"activityTitle": "**ZapUser77**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ZapUser77",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lightningnetwork/lnd\",\n\"issueId\": 1768,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"lightningnetwork/lnd\",\n\"issueId\": 1768\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lightningnetwork/lnd/issues/1768#issuecomment-415244289"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371359632\n}"
}
],
"themeColor": "26292E"
}
]
