### ISSUE TITLE
debuglevel=show does not work

### ISSUE THREAD

**Issue by torkelrogstad** [lightningnetwork/lnd#1772]
### Background
It's not possible to show the available subsystems when specifying `debuglevel`. 

Also, there a typo in `sample-lnd.conf`. On line 109 it says `btcd`, I assume this is meant to be `lnd`.

### Your environment
* version of `lnd`
```
$ lnd --version
lnd version 0.4.2-beta commit=47788c3ceca098d4cf6559fc847a93e86bd89094
```
* which operating system (`uname -a` on *Nix)
```
$ uname -a 
Linux torkel-XPS13 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 GNU/Linux
```

* version of `btcd`, `bitcoind`, or other backend
Not really relevant as this error happens before `lnd` connects to any backend, but for completeness sake:
```
$ btcd --version
btcd version 0.12.0-beta
```

* any other relevant environment details

```
$ go version
go version go1.10.1 linux/amd64
```

### Steps to reproduce

With an empty `lnd.conf`, run:
```
$ lnd --bitcoin.active --bitcoin.mainnet --debuglevel=show
```

### Expected behaviour

A list of available subsystem logging options should be printed. From `lnd -h`:
```
Logging level for all subsystems {trace, debug, info, warn, error, critical} 
You may also specify <subsystem>=<level>,<subsystem2>=<level>,... 
to set the log level for individual subsystems 
Use show to list available subsystems (default: info)
```

### Actual behaviour
```
$ lnd --bitcoin.active --bitcoin.mainnet --debuglevel=show
Attempting automatic RPC configuration to btcd
Automatically obtained btcd's RPC credentials
loadConfig: The specified debug level [show] is invalid
Use lnd -h to show usage
2018-08-23 17:42:23.728 [INF] LTND: Shutdown complete
loadConfig: The specified debug level [show] is invalid
```

I'm no Go expert, but looking through the code in `config.go` (`validLogLevel` and `parseAndSetDebugLevels`), it seems like there's no check for the string "show" being passed as an option. I'm guessing this is happening because of accidentally copying some (but not all) code from `btcd`?

**Comment by Roasbeef** [comment]
Show is only meant to be used from `lncli`. Looks like we need to update the docs a bit.
