### ISSUE TITLE
failed to export github.com/lightninglabs/neutrino: fatal: failed to unpack tree object 

### ISSUE THREAD

**Issue by valuead** [lightningnetwork/lnd#1773]
git pull && dep ensure
Already up-to-date.
grouped write of manifest, lock and vendor: failed to export github.com/lightninglabs/neutrino: fatal: failed to unpack tree object 0d0ce901538af81e234c1b2376babf20fe976b09
: exit status 128

**Comment by Roasbeef** [comment]
This can be fixed by upgrading your `dep` instance, and also clearing your old vendor directory.

**Comment by bob-333** [comment]
Could you please provide instructions? I'm getting the same error after deleting the directory it tells me to delete:

    light@fairly:~/gocode/src/github.com/lightningnetwork/lnd$ make
     Compiling dependencies.
    dep ensure -v
    # Bringing vendor into sync
    grouped write of manifest, lock and vendor: failed to export github.com/lightninglabs/neutrino: fatal: failed to unpack tree object e7780d39ef5628b23615a6cbbb2f41cd583f4afd
    : exit status 128
    Makefile:113: recipe for target 'dep' failed
    make: *** [dep] Error 1
    light@fairly:~/gocode/src/github.com/lightningnetwork/lnd$ make dep
     Compiling dependencies.
    dep ensure -v
    grouped write of manifest, lock and vendor: scratch directory /home/light/gocode/src/github.com/lightningnetwork/lnd/.vendor-new already exists, please remove it
    Makefile:113: recipe for target 'dep' failed
    make: *** [dep] Error 1
    light@fairly:~/gocode/src/github.com/lightningnetwork/lnd$ /bin/rm -fr /home/light/gocode/src/github.com/lightningnetwork/lnd/.vendor-new
    light@fairly:~/gocode/src/github.com/lightningnetwork/lnd$ make dep
     Compiling dependencies.
    dep ensure -v
    # Bringing vendor into sync
    grouped write of manifest, lock and vendor: failed to export github.com/lightninglabs/neutrino: fatal: failed to unpack tree object e7780d39ef5628b23615a6cbbb2f41cd583f4afd
    : exit status 128
    Makefile:113: recipe for target 'dep' failed
    make: *** [dep] Error 1
    light@fairly:~/gocode/src/github.com/lightningnetwork/lnd$ 

Perhaps the "Updating" section of https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md needs improving. The steps it lists currently don't work for me.

**Comment by halseth** [comment]
@bob-333 Try  updating `dep`, delete `vendor` and `.vendor-new`, then running `make dep` again.
