### ISSUE TITLE
[Feature request] Show the number of inactive channels inf `GetInfo`

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1779]
Currently a call to `getInfo` will show the number of pending and active channels:

```bash
# lncli --network=testnet getinfo
{
    "identity_pubkey": "xxx",
    "alias": "xxx",
    "num_pending_channels": 0,
    "num_active_channels": 18,
    "num_peers": 24,
    "block_height": 1408630,
    "block_hash": "0000000000000217d7d8affbffb25e50ce097fb4367f487ac8114abea065c7da",
    "synced_to_chain": true,
    "testnet": true,
    "chains": [
        "bitcoin"
    ],
    "uris": [],
    "best_header_timestamp": "1535105615",
    "version": "0.4.2-beta commit=c9bb04efb921eaa7700a376058bce7b8bdbb3df3"
}
```

It would be useful to also show the number of `inactive` channels.

The active channels are fetched here: https://github.com/lightningnetwork/lnd/blob/625b210f441ece841c76b81377dd96e8d09aba8e/rpcserver.go#L1243

### Steps to completion:
- [ ] Add a new field to the `GetInfoResponse` proto called `num_inactive_channels`: https://github.com/lightningnetwork/lnd/blob/625b210f441ece841c76b81377dd96e8d09aba8e/lnrpc/rpc.proto#L1040
- [ ] After getting the active channels, do a database lookup to get all currently open channels.
- [ ] Subtract the active channels from the number of open channels and add to the rpc response.

**Comment by xsb** [comment]
I would like to pick this one as my first contribution, will get in contact if I get stuck.

**Comment by xsb** [comment]
@halseth could you review https://github.com/lightningnetwork/lnd/pull/1782?
