### ISSUE TITLE
unable to create wallet controller (missing address manager namespace)

### ISSUE THREAD

**Issue by omkarsunku** [lightningnetwork/lnd#1780]
Hi,
Even I am using --no-macaroons it is still asking me address manager missing.

lnd --no-macaroons --noencryptwallet --datadir=~ / . lnd-ltc --configfile= ~/ . lnd / lnd-ltc.conf --logdir=~/.lnd-ltc --rpclisten=10002 --listen=1002 --litecoin.active --litecoin.testnet --litecoin.node=ltcd --ltcd.rpcuser=xxxxxxxx --ltcd.rpcpass=xxxxxxxx
2018-08-24 16:52:46.770 [WRN] LTND: open ~/.lnd/lnd-ltc.conf: no such file or directory
2018-08-24 16:52:46.772 [INF] LTND: Version 0.4.2-beta commit=625b210f441ece841c76b81377dd96e8d09aba8e
2018-08-24 16:52:46.775 [INF] LTND: Active chain: Litecoin (network=testnet)
2018-08-24 16:52:46.813 [INF] CHDB: Checking for schema update: latest_version=5, db_version=5
2018-08-24 16:52:46.884 [INF] LTND: Primary chain is set to: litecoin
2018-08-24 16:52:47.059 [INF] LTND: Initializing btcd backed fee estimator
unable to create wallet controller: missing address manager namespace
unable to create chain control: missing address manager namespace
2018-08-24 16:52:47.245 [INF] LTND: Shutdown complete
missing address manager namespace

I am running ltcd node on my machine which is fully synced and but it is taking btcd backed fee estimator. 
**2018-08-24 16:52:47.059 [INF] LTND: Initializing btcd backed fee estimator**

And I have lnd-ltc configuration file in ~/.lnd but again it is showing no such file or directory.
2018-08-24 16:52:46.770 [WRN] LTND: open ~/.lnd/lnd-ltc.conf: no such file or directory
This is my lnd configuration file.
[Application Options]
debuglevel=trace
debughltc=true
alias=litecoin-lnd

[Litecoin]
litecoin.active=1
litecoin.testnet=true
litecoin.node=ltcd

[Ltcd]
ltcd.zmqpath=tcp://127.0.0.1:28332

Did i went wrong anywhere? How can solve this problem.

Thanks.

**Comment by Roasbeef** [comment]
Which commit are you upgrading from? Or even which commit are you running currently? This is a message which would indicate that you've dropped the waddrmgr state manually.

**Comment by omkarsunku** [comment]
@Roasbeef  I am using commit=625b210f441ece841c76b81377dd96e8d09aba8e.

**Comment by Roasbeef** [comment]
What commit did you update from?

**Comment by Roasbeef** [comment]
You can use `git reflog` to look at the commit you were on before you checked out master.

**Comment by Roasbeef** [comment]
Also I recommend using macaroons always, as otherwise, the PC has no authentication in front of it.

**Comment by omkarsunku** [comment]
Is this the commit you were asking?

~/go/src/github.com/lightningnetwork/lnd$ git reflog
515ba7a4 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/lightningnetwork/lnd

**Comment by omkarsunku** [comment]
Actually I am trying to perform a swap between BTC-LTC. Is that easy to perform swap using lightning bitcoin and lightning litecoin on testnet initially (future time possibly on mainnet).

I am using Bitcoin node(bitcoind) and Litecoin node(ltcd) already fully synced.

**Comment by Roasbeef** [comment]
Yes that's the commit, which is pretty old-ish. It looks like somehow the partial state there has been corrupted. I would [use this tool](https://github.com/btcsuite/btcwallet/blob/master/cmd/dropwtxmgr/main.go) on your `wallet.db` (in the data dir for lnd) to restore the state.

**Comment by omkarsunku** [comment]
So shall I need to use newer commit to run properly.
