### ISSUE TITLE
Macaroon signature mismatch after commiting to the latest version

### ISSUE THREAD

**Issue by peername** [lightningnetwork/lnd#1791]
After commiting to the latest version, my *.macaroon files became invalid. I am geting the following error:

verification failed: signature mismatch after caveat verification

I tried to recreate them be deleting *.macaroons & macaroons.db , but no new files are created.

How to force the lnd to recreate all macaroon files with a valid ones?

**Comment by kulpreet** [comment]
I think the macaroon files got moved to be under the chain directory.

Earlier all chains used the same macaroons, now each chain can have
separate macaroons.

I got that error too. Then saw some discussion on slack clarifying the
problem.

Hope this helps.

@roasbeef - maybe we can delete the old macaroons to avoid this confusion?

**Comment by erkarl** [comment]
@peername I think keeping up with merged PRs and Slack activity is the way to go if you need to stay on latest master. For those who stay on tagged releases these kinds of changes will be documented in the release notes.

**Comment by cfromknecht** [comment]
@peername slack is probably the best place for up to date info, but @erkarl is right that it would be documented in the release notes.

IIRC, the old ones were not deleted in case users wanted to revert or wanted to the keep them. You may delete them yourself if you don't need them.
