### ISSUE TITLE
Docker stuck on simnet

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#1792]
I think there's a problem with the docker implementation.  Following the instructions, `export NETWORK="testnet"` for example, followed by `sudo docker-compose up "btcd"` shows `Command: btcd --simnet --debuglevel=info --rpcuser=devuser --rpcpass=devpass --datadir=/data --logdir=/data --rpccert=/rpc/rpc.cert --rpckey=/rpc/rpc.key --rpclisten=0.0.0.0 --txindex`.  As you can see, it's starting simnet instead of testnest.

I can get it to run testnet by explicitly changing https://github.com/lightningnetwork/lnd/blob/master/docker/btcd/start-btcd.sh#L45

Another way to pass the environment would be to use a .env file

**Comment by yancyribbens** [comment]
@Roasbeef i'd be happy to pick this up also.

**Comment by Roasbeef** [comment]
Excellent! So issue seems that it no longer properly reads out the environment variables?

**Comment by yancyribbens** [comment]
yeah.  It doesn't scope up the env vars from the host OS.

Should be able to just use the `environment:` key in `docker-compose.yml`, although maybe being on `Version 2` is the issue.

```
    environment:
      RPCUSER: $RPCUSER
      RPCPASS: $RPCPASS
      DEBUG: $DEBUG
      NETWORK: $NETWORK
```

https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers
https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by yancyribbens** [comment]
this seems to work now.  Therefore closing issue.
`Command: btcd --testnet --debuglevel=info --rpcuser=devuser --rpcpass=devpass --datadir=/data --logdir=/data --rpccert=/rpc/rpc.cert --rpckey=/rpc/rpc.key --rpclisten=0.0.0.0 --txindex`

**Comment by yancyribbens** [comment]
PR to fix issue: https://github.com/lightningnetwork/lnd/pull/2220

**Comment by yancyribbens** [comment]
just an update to this issue.  it looks like the problem with not switching networks has to do with my environment and how I set the env vars.  For example, it works ok to use `sudo NETWORK=some_net ..` however, `export NETOWRK=some_net` will not work for me.  At any rate, the PR I submitted still is needed to fix the mainnet implementation from what I can tell.
