### ISSUE TITLE
how to get the address list?

### ISSUE THREAD

**Issue by zhouzhou84** [lightningnetwork/lnd#1793]
### Description
I use `lncli unlock` but it returns"it was unlocked already", but I don't know the address, So I generate a new address with `lncli newaddress np2wkh` and get some coin from the faucet using the new address,but the walletbalance is still 0, Do I need to change to this new address and how to do it?

**Comment by cfromknecht** [comment]
Have you verified that the transaction confirmed? What’s the txid?

**Comment by cfromknecht** [comment]
I’m not sure what’s meant by change to the new address, but you shouldn’t have to do anything extra to see the balance. The process you describe sounds correct.

**Comment by zhouzhou84** [comment]
Ok,my fault,I know something about it . Please close this issuse thank you so much On 2018-08-27 11:10 , Conner Fromknecht Wrote: I’m not sure what’s meant by change to the new address, but you shouldn’t have to do anything extra to see the balance. The process you describe sounds correct. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cfromknecht** [comment]
Good to hear, no problem
