### ISSUE TITLE
[lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification

### ISSUE THREAD

**Issue by PatrickLemke** [lightningnetwork/lnd#1796]
### Background

With the newest update, when trying to use lncli, I get this error:
[lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification

### Your environment

* lncli version 0.4.2 commit=26f68da5b2883885fcf6a8e79b3fc9bb12cc9eef
* Linux patrick-VirtualBox 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.99.0-f030410
* Running on Oracle VM Virtualbox image

### Steps to reproduce

Use any lncli command

**Comment by Roasbeef** [comment]
The macaroon location has changed recently, check out the `sample-lnd.conf` for the new location.

**Comment by basharov** [comment]
In order anyone else coming here in hope to fix the issue, @Roasbeef is right, but I will just share an excerpt from the `sample-lnd.conf` as a fix:

```
; Disable macaroon authentication. Macaroons are used are bearer credentials to
; authenticate all RPC access. If one wishes to opt out of macaroons, uncomment
; the line below.
no-macaroons=true
```

So, the idea is to uncomment `no-macaroons=true` or add this value if it's not there yet.

**Comment by guggero** [comment]
That's not a good idea, that disables authentication completely. Meaning anyone can use the RPC to do whatever they want with your lnd. If you get the above error message, it very likely means you're using a wrong macaroon. You should try to debug the issue instead of disabling authentication!
