### ISSUE TITLE
runtime: invalid pc-encoded table f=runtime.exitsyscallfast

### ISSUE THREAD

**Issue by mkke** [lightningnetwork/lnd#1797]
### Background

Wallet recovery doesn't complete

### Your environment

* version of `lnd`
Version 0.4.2-beta commit=f1256ba41b033e62de2980b89bc7e278f76a0880
* which operating system (`uname -a` on *Nix)
Linux bitcoin 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
bitcoin-0.16.2-x86_64-linux-gnu
* any other relevant environment details

### Steps to reproduce

Start lnd, lncli create with recovery mode.

### Expected behaviour

Wallet recovery completed

### Actual behaviour

Lnd exits with error:
[lnd.log](https://github.com/lightningnetwork/lnd/files/2325573/lnd.log)

**Comment by Roasbeef** [comment]
Can you describe your situation in more detail? Hard to investigate from a single sentence.

**Comment by mkke** [comment]
I've attached the complete log. The lnd process is not running afterwards.
I'm still trying the wallet recovery for the issue #1141.

**Comment by Roasbeef** [comment]
Which version of go are you using?

**Comment by mkke** [comment]
go version go1.10.3 linux/amd64

**Comment by Roasbeef** [comment]
Can you try updating to go1.11 and trying again? Looks like this was an issue for ARM, but has been fixed since then.

**Comment by mkke** [comment]
With go1.11 the error did not reappear.
