### ISSUE TITLE
Add graph diameter calculation to GetNetworkInfo

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#180]
The response of the `GetNetworkInfo` RPC contains the following fields:
```proto
message NetworkInfo {
    uint32 graph_diameter = 1;
    double avg_out_degree = 2;
    uint32 max_out_degree = 3;
    uint32 num_nodes = 4;
    uint32 num_channels = 5;
    int64 total_network_capacity = 6;
    double avg_channel_size = 7;
    int64 min_channel_size = 8;
    int64 max_channel_size = 9;
}
```

Currently, all fields _except_ the `graph_diameter` field are populated. The [graph diameter](http://mathworld.wolfram.com/GraphDiameter.html) is to represent the diameter, or the worst-case path length from one node to another within the channel graph.

**Comment by phlip9** [comment]
I'll take a look at this issue.

**Comment by Lldenaurois** [comment]
Hi phlip9, Im actually already working on this issue and have a PR open for it.

I need to fix a bug though, so maybe if you'd liketo takea look at the PR that would be cool

**Comment by phlip9** [comment]
Ahh I didn't see that. I'll check out your PR.

**Comment by afederigo** [comment]
If this task hasn't completed and nobody is working on it, I'd like try to finish it.

**Comment by Lldenaurois** [comment]
Hey man, feel free to work on it :)

**Comment by Lldenaurois** [comment]
Hey aferdigo, I actually just noticed that my PR is almost done. My bad... Been kinda swamped lately. I will upload the PR later today

**Comment by afederigo** [comment]
Ok, I will take another one :)

**Comment by nalinbhardwaj** [comment]
I’ll take this up :)

**Comment by mlerner** [comment]
@nalinbhardwaj: are you still working on this? if not, I can finish it.

**Comment by nalinbhardwaj** [comment]
@mlerner I have the work done already but I think I may have misunderstood the task(which is why I was holding off a PR), is the graph diameter to be found using the same `EdgeWeight()` as `routing/pathfinding.go` or should channel weights be taken as 1?

**Comment by C-Otto** [comment]
@nalinbhardwaj my gut feeling is: 1. @Roasbeef could you chime in on this, please?
