### ISSUE TITLE
lnd chain confusion thinks its on mainnet not testnet

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#1800]
### Background

Running bitcoind on testnet and running lnd on testnet with bitcoind, after updating to beta 0.5 several issues are occurring, Automatic RPC configuration fails, (have to specify the bitcoind rpc settings in the lnd.conf. Once started lnd thinks its on mainnet when creating a invoice.

### Your environment
lnd version 0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0
4.15.0-24-generic #26~16.04.1-Ubuntu
bitcoind "version": 160200

grep "^[^#;]" lnd.conf
[Application Options]

listen=0.0.0.0:9745
restlisten=127.0.0.1:8888
externalip=203.86.204.88:9745
alias=Geektech lnd
color=#6600cc
[Bitcoin]
bitcoin.active=1
bitcoin.testnet=1
bitcoin.node=bitcoind
[Btcd]

[Bitcoind]

bitcoind.rpcuser=thisisatestfool
bitcoind.rpcpass=thisisatestpasword
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28332
[neutrino]
[Litecoin]
[Ltcd]

[autopilot]
[tor]

 grep "^[^#;]" bitcoin.conf

testnet=1
server=1
rpcuser=thisisatestfool
rpcpassword=thisisatestpasword
rpcallowip=127.0.0.1/32
minrelaytxfee=0
txindex=1
daemon=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

### Steps to reproduce
start lnd either using lnd.conf or with cmdline
lnd --bitcoin.active --bitcoin.testnet --debuglevel=trace --bitcoind.rpcuser=thisisatestfool --bitcoind.rpcpass=thisisatestpasword --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28332 

Try and create a invoice.
lncli addinvoice --amt 50000 --memo testing

### Expected behaviour

Invoice should be created successfully

### Actual behaviour

[lncli] unable to read macaroon path (check the network setting!): open /home/ligntning/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory

lnd thinks its on mainnet but its on testnet the mainnet directory does not exist due to running on testnet.

**Comment by Roasbeef** [comment]
This was a change in `0.5`, but you can set the the `--network=testnet`flag, or do something like: 
```
alias tncli=lncli --network=testnet
```

Should have the release notes up by tomorrow to cover some of this stuff.

**Comment by redstorm1** [comment]
which section should this go in lnd.conf? [Application Options] or [bitcoin]

**Comment by redstorm1** [comment]
is their a change to selecting the bitcoin node also? not thinks im on btcd not bitcoind

Attempting automatic RPC configuration to btcd

**Comment by Roasbeef** [comment]
lnd.conf is fine, you only need to modify the args to lncli.

**Comment by redstorm1** [comment]
Got it thanks
