### ISSUE TITLE
not automatically connecting to peers

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1803]
Just a reminder that lnd still doesn't succeed to automatically connect to peers.
Have 40 peers i had to manually make `lncli connect` to activate channels after a lnd restart.
don't think i can provide any useful data

**Comment by cfromknecht** [comment]
Fwiw, I’ve restarted my node several times today, and haven’t experienced this. Logs would definitely help see what lnd is _trying_ to do

**Comment by halseth** [comment]
Old issue: #1087

**Comment by robtex** [comment]
ok lets close this and reopen #1087 then

**Comment by halseth** [comment]
Think we can just keep this one open, as not sure if it's the same issue :)

**Comment by Roasbeef** [comment]
Based on the comments in the other issue, it looks like we're possibly backing off too quickly, or are removing the connection reuest as we think we already have on eestablished, then the connection dies for w/e reason. 

@halseth we should be able to get to the bottom of this by starting a heavily-ish loaded node on testnet, and disabling all logging levels but `SRVR` and `CMGR` just to track the various errors it runs into during the reconnection process.
