### ISSUE TITLE
Macaroon path for gRPC tutorials not updated

### ISSUE THREAD

**Issue by PatrickLemke** [lightningnetwork/lnd#1804]
### Background

The tutorials for the gRPC API have not been updated yet to the new macaroon path

It's correct here:
https://github.com/lightningnetwork/lnd/blob/dadf13e2a32118cc7416e297142fdd0d0c94a6a5/docs/grpc/python.md

But not here:
https://dev.lightning.community/guides/python-grpc/

Same applies for java, ruby, etc.

**Comment by Roasbeef** [comment]
Will be fixed by https://github.com/lightninglabs/lightning-dev-site/pull/50 and https://github.com/lightninglabs/lightning-dev-site/pull/51. Closing this issue to track on the repo for the dev site instead. Thanks for reporting this!
