### ISSUE TITLE
Add a Stop command to gRPC and the RPC Server

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#181]
At the time of the writing of this issue, there currently isn't a way to gracefully stop `lnd`. The only way to terminate the process atm is to use `CTRL-C`to kill the process. While the usage of this stopping method is advantageous to gauging the degree of fault-tolerance of the daemon, it would be nice to be able to gracefully top the daemon with a single RPC command. 

# Steps To Completion 

- [ ] Add a new `Stop` command to the set of protos, along with request/response protos. 
- [ ] Implement the `Stop` command within the daemon. The `Stop` command should carry a signal from the RPC server, to the server, and finally to the termination goroutine in `lnd.go`. All sub-systems should be gracefully signaled to stop, waited on, and then finally the process should exist once all the sub-systems have been stopped.
- [ ] Add a new `lncli` command from the `stop` command.

**Comment by halseth** [comment]
I'll take this one :)
