### ISSUE TITLE
Force closed channels, question about final balance

### ISSUE THREAD

**Issue by Cees2daBees** [lightningnetwork/lnd#1829]
### Background

I recently force closed 4 channels to nodes that were offline/not responding. After closing and monitoring the blockchain, I found the transactions for channel closures, the transaction fee was the commit fee, and the amounts to each address(node) was as per the local and remote balances of the channel.

After the transaction reached the 144 confirmations, I was able to review on my node. I noticed that funds received from each closed channel did not match the local balance prior to channel closure (they also did not match the amount found on blockchain.info going to my address), but were short by exactly 246 satoshis each. Is there an additional fee to force close channels that I am not aware of?

### Your environment

lnd version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
Linux RaspiBolt 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
Bitcoin Core Daemon version v0.16.1

**Comment by Roasbeef** [comment]
Yes, when we sweep the time-locked output, we need to pay a feee on the transactions that we sweep.

**Comment by Cees2daBees** [comment]
Thanks for the response @Roasbeef , appreciate everything you guys are doing with LND! Keep up the great work!
