### ISSUE TITLE
[Feature request] LND support for Litecoin on Simnet

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#1830]
Tried to run LND  with litecoin on simnet:

```
loadConfig: simnet mode for litecoin not currently supported
```

Is there a good reason for this not to be supported?
May I suggest a PR?

**Comment by offerm** [comment]
@Roasbeef @halseth Will you welcome a PR for this?

It is a very simple one and I see no reason why not to support it. With all the issues that the testnet is currently having it would be better to support SimNet. 

Please let me know

**Comment by halseth** [comment]
Sure, it would be more of a question who could test/review the change, as I don't know of many using LTC simnet.

**Comment by offerm** [comment]
@halseth see #1865 

Let me know what you think. I think this is riskless. Added a message making this unsupported option.

**Comment by halseth** [comment]
Agree should be safe to add, as it doesn't affect most users.
