### ISSUE TITLE
Update to 0.5 - RC1 

### ISSUE THREAD

**Issue by waffi121** [lightningnetwork/lnd#1831]
I'm trying to update to 0.5 beta but when opening the wallet is:

[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable

and in the log:

`Sep 03 16:45:39 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Sep 03 16:45:39 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 16:45:39 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Sep 03 16:45:39 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Sep 03 16:46:39 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Sep 03 16:46:39 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Sep 03 16:46:39 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Sep 03 16:46:40 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 16:46:40 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Sep 03 16:46:40 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.`

I have again installed the 0.4 and now everything works again.

I installed the whole thing on a raspberry.

anyone have an idea what it can be?

Thank you

**Comment by irekzielinski** [comment]
There are number of things that needs some tweaking when upgrading to 0.5
You might find this discussion useful: 
https://github.com/Stadicus/guides/issues/190

**Comment by Roasbeef** [comment]
Yep the guide you're using needs to be updated itself.
