### ISSUE TITLE
Makefile:132: recipe for target 'build' failed  make: *** [build] Error 1

### ISSUE THREAD

**Issue by valuead** [lightningnetwork/lnd#1834]
Issue with the Latest commit 2b448be  
/go/src/github.com/lightningnetwork/lnd# git pull && dep ensure
Already up-to-date.
root@xxxx:~/go/src/github.com/lightningnetwork/lnd#

vendor/github.com/btcsuite/btcd/btcec/precompute.go:12:2: cannot find package "strings" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/strings (vendor tree)
        /root/lnd/src/strings (from $GOROOT)
        /root/go/src/strings (from $GOPATH)
vendor/github.com/btcsuite/btcd/btcec/btcec.go:25:2: cannot find package "sync" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/sync (vendor tree)
        /root/lnd/src/sync (from $GOROOT)
        /root/go/src/sync (from $GOPATH)
vendor/github.com/btcsuite/btclog/log.go:44:2: cannot find package "sync/atomic" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/sync/atomic (vendor tree)
        /root/lnd/src/sync/atomic (from $GOROOT)
        /root/go/src/sync/atomic (from $GOPATH)
vendor/github.com/btcsuite/golangcrypto/ssh/terminal/util.go:21:2: cannot find package "syscall" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/syscall (vendor tree)
        /root/lnd/src/syscall (from $GOROOT)
        /root/go/src/syscall (from $GOPATH)
vendor/github.com/btcsuite/btcd/integration/rpctest/rpc_harness.go:15:2: cannot find package "testing" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/testing (vendor tree)
        /root/lnd/src/testing (from $GOROOT)
        /root/go/src/testing (from $GOPATH)
vendor/github.com/miekg/dns/scanner.go:9:2: cannot find package "text/scanner" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/text/scanner (vendor tree)
        /root/lnd/src/text/scanner (from $GOROOT)
        /root/go/src/text/scanner (from $GOPATH)
vendor/github.com/btcsuite/btcd/btcjson/help.go:12:2: cannot find package "text/tabwriter" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/text/tabwriter (vendor tree)
        /root/lnd/src/text/tabwriter (from $GOROOT)
        /root/go/src/text/tabwriter (from $GOPATH)
vendor/github.com/btcsuite/btcd/wire/blockheader.go:10:2: cannot find package "time" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/time (vendor tree)
        /root/lnd/src/time (from $GOROOT)
        /root/go/src/time (from $GOPATH)
vendor/github.com/btcsuite/btcutil/appdata.go:13:2: cannot find package "unicode" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/unicode (vendor tree)
        /root/lnd/src/unicode (from $GOROOT)
        /root/go/src/unicode (from $GOPATH)
vendor/golang.org/x/text/encoding/unicode/unicode.go:10:2: cannot find package "unicode/utf16" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/unicode/utf16 (vendor tree)
        /root/lnd/src/unicode/utf16 (from $GOROOT)
        /root/go/src/unicode/utf16 (from $GOPATH)
vendor/github.com/btcsuite/btcd/wire/message.go:11:2: cannot find package "unicode/utf8" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/unicode/utf8 (vendor tree)
        /root/lnd/src/unicode/utf8 (from $GOROOT)
        /root/go/src/unicode/utf8 (from $GOPATH)
vendor/github.com/davecgh/go-spew/spew/bypass.go:27:2: cannot find package "unsafe" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/unsafe (vendor tree)
        /root/lnd/src/unsafe (from $GOROOT)
        /root/go/src/unsafe (from $GOPATH)
Makefile:132: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by cfromknecht** [comment]
Hi @valuead, your `$GOROOT` appears to be incorrect, make sure it’s pointing to the directory where the go source is located

**Comment by valuead** [comment]
I did the same thing every release/update and everything was fine 
I do use .profile 
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

now i see this 
/go/src/github.com/lightningnetwork/lnd# make
 Compiling dependencies.
dep ensure -v
 Building debug lnd and lncli.
go build -v -tags=debug -o lnd-debug -ldflags "-X main.Commit=2b448be048daf85cef4cbb37ceed4413fdb051e6" github.com/lightningnetwork/lnd
vendor/github.com/btcsuite/websocket/conn.go:8:2: cannot find package "bufio" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/bufio (vendor tree)
        /root/lnd/src/bufio (from $GOROOT)
        /root/go/src/bufio (from $GOPATH)
breacharbiter.go:4:2: cannot find package "bytes" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/bytes (vendor tree)
        /root/lnd/src/bytes (from $GOROOT)
        /root/go/src/bytes (from $GOPATH)
vendor/github.com/jrick/logrotate/rotator/rotator.go:33:2: cannot find package "compress/gzip" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/compress/gzip (vendor tree)
        /root/lnd/src/compress/gzip (from $GOROOT)
        /root/go/src/compress/gzip (from $GOPATH)
vendor/github.com/btcsuite/btcd/btcec/precompute.go:8:2: cannot find package "compress/zlib" in any of:
        /root/go/src/github.com/lightningnetwork/lnd/vendor/compress/zlib (vendor tree)
        /root/lnd/src/compress/zlib (from $GOROOT)
        /root/go/src/compress/zlib (from $GOPATH)

**Comment by Roasbeef** [comment]
Your $GOPATH and $GOORT still look to be incorrect. Check out this tutorial on how to set the properly: https://golang.org/doc/code.html#GOPATH

**Comment by valuead** [comment]
thanks for helping 
my go it in /root/go
my env vars looks like this 
export PATH=$PATH:$GOPATH/bin
export GOPATH=$HOME/go
export GOROOT=/root/go/src

**Comment by cfromknecht** [comment]
i'm assuming `/root` is the same `$HOME` in this case?

mine looks like this:
```
export GOROOT=$HOME/go-root
export GOPATH=$HOME/go
```
for me, `/$HOME/go-root` has the golang source cloned via git, and `$HOME/go` is where development happens and all third-party packages are installed

**Comment by cfromknecht** [comment]
@valuead this is definitely not a code issue, it 100% that your `$GOROOT` is incorrect. To remedy, you'll need to find _where_ the go source code is installed.

Do you see how in mine they are distinct top-level directories?

**Comment by cfromknecht** [comment]
You shouldn't need to add `/src` to the end of `$GOROOT`, it will automatically search in `/src` under the top level directory. For example:
```
/root/go/src/src/unicode/utf16 (from $GOROOT)
```
Note the double `/src/src`

**Comment by valuead** [comment]
thank you all issue closed as i have mismatch in my go tools. updated go and was able to compile
