### ISSUE TITLE
 error: runtime: out of memory

### ISSUE THREAD

**Issue by valuead** [lightningnetwork/lnd#1835]
lnd --bitcoin.mainnet --debuglevel=debug --bitcoin.node=bitcoind  --autopilot.active
Attempting automatic RPC configuration to bitcoind

Automatically obtained bitcoind's RPC credentials
2018-09-04 00:27:47.864 [INF] LTND: Version 0.5.0-beta commit=edf304ad8b98a38b21cc08ef3bb727b8f48b71af
2018-09-04 00:27:47.865 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-09-04 00:27:47.866 [INF] CHDB: Checking for schema update: latest_version=5, db_version=5
2018-09-04 00:27:47.960 [INF] LTND: Primary chain is set to: bitcoin
2018-09-04 00:27:52.800 [INF] LTND: Initializing bitcoind backed fee estimator
2018-09-04 00:27:52.798 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:28332
2018-09-04 00:27:52.801 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:28333
2018-09-04 00:28:00.633 [DBG] LNWL: Using minimum fee rate of 253 sat/kw
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xfaa02a, 0x16)
        /usr/lib/go-1.10/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc421500000, 0x10000000, 0x8cdc00, 0x17b57f8)
        /usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x179bc60, 0x10000000, 0xc420043770)
        /usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x179bc60, 0x8000, 0x0)
        /usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x179bc60, 0x8000, 0x17b5808, 0x7fbaf4de2dd8)
        /usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x179bc60, 0x8000, 0x1790101, 0x0)
        /usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x179bc60, 0x8000, 0x10101, 0x2)
        /usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x10000000, 0x7fbaf4de0101, 0x456e7d)
        /usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x7fbb00000000)
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/lib/go-1.10/src/runtime/proc.go:1170

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc42032c1b0 sp=0xc42032c1a8 pc=0x459930
runtime.mallocgc(0x10000000, 0xdca020, 0x1, 0xc420594000)
        /usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc42032c250 sp=0xc42032c1b0 pc=0x412792
runtime.makeslice(0xdca020, 0x4000000, 0x4000000, 0xc420594000, 0x200, 0x200)
        /usr/lib/go-1.10/src/runtime/slice.go:61 +0x77 fp=0xc42032c280 sp=0xc42032c250 pc=0x443757
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/golangcrypto/scrypt.Key(0x16a15a0, 0x6, 0x6, 0xc420461388, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/golangcrypto/scrypt/scrypt.go:235 +0x152 fp=0xc42032c340 sp=0xc42032c280 pc=0x744f92
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/snacl.(*SecretKey).deriveKey(0xc420461380, 0xc42032caa0, 0x20, 0xdd87a0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/snacl/snacl.go:114 +0x9e fp=0xc42032c3e0 sp=0xc42032c340 pc=0x74588e
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/snacl.(*SecretKey).DeriveKey(0xc420461380, 0xc42032caa0, 0x58, 0x58)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/snacl/snacl.go:201 +0x39 fp=0xc42032c448 sp=0xc42032c3e0 pc=0x745de9
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.loadManager(0x7fbb0869e500, 0xc420080f00, 0x16a15a0, 0x6, 0x6, 0x176f900, 0x6, 0x6, 0xc420080f40)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/manager.go:1404 +0x35c fp=0xc42032ca90 sp=0xc42032c448 pc=0x76037c
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.Open(0x7fbb0869e500, 0xc420080f00, 0x16a15a0, 0x6, 0x6, 0x176f900, 0x0, 0x0, 0x0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/manager.go:1491 +0xac fp=0xc42032cb60 sp=0xc42032ca90 pc=0x7613cc
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.Open.func2(0x11aa940, 0xc4204641e0, 0xc4204641e0, 0x0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:3375 +0x139 fp=0xc42032cbf8 sp=0xc42032cb60 pc=0x90bfd9
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb.View(0x11b3120, 0xc420240780, 0xc42032cd48, 0x8, 0x8)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb/interface.go:196 +0x72 fp=0xc42032cc50 sp=0xc42032cbf8 pc=0x740682
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.Open(0x11b3120, 0xc420240780, 0x16a15a0, 0x6, 0x6, 0xc42032ce30, 0x176f900, 0x0, 0x0, 0xc42032ce28, ...)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:3371 +0x1d2 fp=0xc42032cd90 sp=0xc42032cc50 pc=0x9001b2
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Loader).OpenExistingWallet(0xc4204611a0, 0x16a15a0, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/loader.go:189 +0x39d fp=0xc42032ce90 sp=0xc42032cd90 pc=0x8ecb9d
github.com/lightningnetwork/lnd/lnwallet/btcwallet.New(0xc42045baa0, 0x1d, 0x0, 0x0, 0x16a14c8, 0x5, 0x5, 0x16a15a0, 0x6, 0x6, ...)
        /root/go/src/github.com/lightningnetwork/lnd/lnwallet/btcwallet/btcwallet.go:117 +0x37a fp=0xc42032cf88 sp=0xc42032ce90 pc=0xb655ba
main.newChainControlFromConfig(0xc420237680, 0xc420468040, 0x16a14c8, 0x5, 0x5, 0x16a15a0, 0x6, 0x6, 0x0, 0x0, ...)
        /root/go/src/github.com/lightningnetwork/lnd/chainregistry.go:496 +0x9a9 fp=0xc42032db10 sp=0xc42032cf88 pc=0xc88499
main.lndMain(0x0, 0x0)
        /root/go/src/github.com/lightningnetwork/lnd/lnd.go:275 +0x8de fp=0xc42032df28 sp=0xc42032db10 pc=0xcacbde
main.main()
        /root/go/src/github.com/lightningnetwork/lnd/lnd.go:455 +0x26 fp=0xc42032df88 sp=0xc42032df28 pc=0xcaeb76
runtime.main()
        /usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc42032dfe0 sp=0xc42032df88 pc=0x42e5a2
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42032dfe8 sp=0xc42032dfe0 pc=0x45c4c1

goroutine 19 [select]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0xc42045e640)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:736 +0x105
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient.(*Client).start
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:1029 +0x116

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x41

goroutine 8 [select, locked to thread]:
runtime.gopark(0x110b928, 0x0, 0xf99664, 0x6, 0x18, 0x1)
        /usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4201be750, 0xc42008e300)
        /usr/lib/go-1.10/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 9 [select]:
github.com/lightningnetwork/lnd/signal.mainInterruptHandler()
        /root/go/src/github.com/lightningnetwork/lnd/signal/signal.go:62 +0x108
created by github.com/lightningnetwork/lnd/signal.init.1
        /root/go/src/github.com/lightningnetwork/lnd/signal/signal.go:30 +0x81

goroutine 12 [select]:
io.(*pipe).Read(0xc42045cd20, 0xc4201b4000, 0x1000, 0x1000, 0x1, 0x1, 0x1)
        /usr/lib/go-1.10/src/io/pipe.go:50 +0x115
io.(*PipeReader).Read(0xc420464120, 0xc4201b4000, 0x1000, 0x1000, 0xc4201fde00, 0x4cb84e, 0xc42045cc80)
        /usr/lib/go-1.10/src/io/pipe.go:127 +0x4c
bufio.(*Reader).fill(0xc4201fdf50)
        /usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).ReadSlice(0xc4201fdf50, 0xa, 0x1, 0x0, 0x0, 0x1, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:341 +0x2c
bufio.(*Reader).ReadLine(0xc4201fdf50, 0x16a12e0, 0x1, 0x1, 0x1, 0x0, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:370 +0x34
github.com/lightningnetwork/lnd/vendor/github.com/jrick/logrotate/rotator.(*Rotator).Run(0xc42045ccd0, 0x11a70a0, 0xc420464120, 0xc42045ccd0, 0x0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/jrick/logrotate/rotator/rotator.go:100 +0xb8
created by main.initLogRotator
        /root/go/src/github.com/lightningnetwork/lnd/log.go:135 +0x328

goroutine 34 [select]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0xc4200a65a0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:736 +0x105
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient.(*Client).start
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:1029 +0x116

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7fbb086eef00, 0x72, 0xc420067a18)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201a4298, 0x72, 0xffffffffffffff00, 0x11a89c0, 0x16a19e8)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201a4298, 0xc420450600, 0x1, 0x1)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201a4280, 0xc420450625, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201a4280, 0xc420450625, 0x1, 0x1, 0xc4201a4280, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4204641a0, 0xc420450625, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
io.ReadAtLeast(0x7fbb0869e4c0, 0xc4204641a0, 0xc420450625, 0x1, 0x1, 0x1, 0xf5a440, 0xc420067b00, 0x7fbb0869e4c0)
        /usr/lib/go-1.10/src/io/io.go:309 +0x86
io.ReadFull(0x7fbb0869e4c0, 0xc4204641a0, 0xc420450625, 0x1, 0x1, 0x0, 0x1794720, 0xc4202fc6e0)
        /usr/lib/go-1.10/src/io/io.go:327 +0x58
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).readFrame(0xc420298d20, 0x0, 0x0, 0x0, 0x0, 0x11a71c0, 0xc4202fc6e0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:263 +0xf8
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).readMessage(0xc420298d20, 0x0, 0x0, 0x40f2ad, 0xc42001e000, 0xe67f00)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:312 +0x56
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).Receive(0xc420298d20, 0xc420480120, 0xc4202fc600, 0x7fbb086f91d0, 0xc4202fc6e0, 0xc4202fc601)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:378 +0x40
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain.(*BitcoindConn).blockEventHandler(0xc420234070, 0xc420298d20)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain/bitcoind_conn.go:184 +0x187
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain.(*BitcoindConn).Start
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain/bitcoind_conn.go:139 +0x349

goroutine 27 [runnable]:
syscall.Syscall(0x0, 0x8, 0xc4205b0c57, 0x1, 0x1, 0x1, 0x0)
        /usr/lib/go-1.10/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc4205b0c57, 0x1, 0x1, 0xc420080900, 0x0, 0x0)
        /usr/lib/go-1.10/src/syscall/zsyscall_linux_amd64.go:749 +0x5f
syscall.Read(0x8, 0xc4205b0c57, 0x1, 0x1, 0x0, 0xc420060ad0, 0x6)
        /usr/lib/go-1.10/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc4201c0100, 0xc4205b0c57, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:153 +0x118
net.(*netFD).Read(0xc4201c0100, 0xc4205b0c57, 0x1, 0x1, 0xc4201c0100, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e070, 0xc4205b0c57, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
io.ReadAtLeast(0x7fbb0869e4c0, 0xc42000e070, 0xc4205b0c57, 0x1, 0x1, 0x1, 0xf5a440, 0xc420060c00, 0x7fbb0869e4c0)
        /usr/lib/go-1.10/src/io/io.go:309 +0x86
io.ReadFull(0x7fbb0869e4c0, 0xc42000e070, 0xc4205b0c57, 0x1, 0x1, 0x0, 0x1794720, 0x0)
        /usr/lib/go-1.10/src/io/io.go:327 +0x58
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).readFrame(0xc42019e6c0, 0xc4205af4c0, 0xc4205d0b40, 0xc4202bb200, 0xc42028d4d0, 0xc4201e1200, 0x2)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:288 +0x52c
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).readMessage(0xc42019e6c0, 0x5d2a00, 0xc4205ce7c0, 0x4, 0x0, 0x8)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:312 +0x56
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.(*Conn).Receive(0xc42019e6c0, 0xc420480120, 0xc420060e00, 0x0, 0x0, 0x5)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:378 +0x40
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain.(*BitcoindConn).txEventHandler(0xc420234070, 0xc42019e6c0)
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain/bitcoind_conn.go:259 +0x187
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain.(*BitcoindConn).Start
        /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/chain/bitcoind_conn.go:140 +0x378

**Comment by Roasbeef** [comment]
Can you fill out the entire issue template for this issue and all others in the future? Thanks! It saves us a lot of back and forth to get to the bottom of the issue.

**Comment by valuead** [comment]
next time will do. my issue with env was the mismatch in go tools
this is what i got after I compile make make install

**Comment by cfromknecht** [comment]
If you do `go version` what do you get.

**Comment by valuead** [comment]
go version go1.10 linux/amd64

**Comment by valuead** [comment]
The server had low memory 500 mg after creating a swap file 4 GB things start flying 
thank you to @Roasbeef  and other team members.
