### ISSUE TITLE
Full persistence within the BreachArbiter

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#184]
The `breachArbiter` is sub-system within `lnd` that is tasked with swiftly enacting justice in the case that we detect that a channel peer broadcasts a prior revoked state. With the current implementation, justice _must_ be enacting in a single execution context, meaning that if `lnd` restarts, then we'll never re-attempt to broadcast our transaction sweeping _all_ the funds within the channel. In order to make `lnd` more fault-tolerant and absolutely correct, we'll need to persistent the channel breach state to disk so we can reliably dispatch justice in all possible scenarios. 

# Steps To Completion 

- [ ] Once a channel breach is detected, we'll need to immediately write the breach state to disk. 
    * Persistence should be implemented via a series of `boltdb` buckets storing the necessary channel breach data required to construct and broadcast the justice transaction. 
- [ ] Upon restart, the `breachArbiter` should check it's persistent state for any channel breaches which were partially handled, or not dispatched at all. The necessary goroutine should then be launched (`b.exactRetribution`) to handle the channel breach.

**Comment by phlip9** [comment]
I'll take a look at this issue.

**Comment by Roasbeef** [comment]
@phlip9 cool! You may want to study [_this_ commit](https://github.com/lightningnetwork/lnd/pull/90/commits/1d2d3734e302d68032392d2ce54ada229d4b648c) which added full persistence to the `utxoNursery`. Take note of the way the integration tests have been modified to ensure that restarts at each stage of the pipeline doesn't affect the correctness of the final actions taken by `lnd`.

**Comment by Roasbeef** [comment]
Closed by #241.
