### ISSUE TITLE
LND is slow to filter blocks

### ISSUE THREAD

**Issue by marcw** [lightningnetwork/lnd#1845]
### Background

I recently acquired a [raspiblitz](https://github.com/rootzoll/raspiblitz) and I have been in the process of setting it up since a few days. The device has been restarted quite a few times during the block filtering process. 

The debug log shows:

```
2018-09-05 09:23:27.265 [DBG] LNWL: Filtering block 451347 (00000000000000000187d69052cb76201d13e5ac4666d8e957d8a28565ea470d) with 1740 transactions
2018-09-05 09:23:28.685 [DBG] LNWL: Filtering block 451348 (000000000000000001b5019852502dc3eacc00a0289e9b027bbb8a7785a3e560) with 2119 transactions
2018-09-05 09:23:30.123 [DBG] LNWL: Filtering block 451349 (000000000000000000c29dddf0de11e381972b2e625dc7ae2b00e3e32668797c) with 1994 transactions
2018-09-05 09:23:31.629 [DBG] LNWL: Filtering block 451350 (00000000000000000117064114ffe0aaf77c4e77f3f8f9958761fcc85f366b34) with 2571 transactions
2018-09-05 09:23:33.201 [DBG] LNWL: Filtering block 451351 (00000000000000000021dea11b5bb308b36f0c6cf5f99bdcf0656fd5c36d5aab) with 2280 transactions
2018-09-05 09:23:34.812 [DBG] LNWL: Filtering block 451352 (000000000000000000f4ce8da87d55aaf4bd5fe98987ee90b8eb51cb7bee2558) with 1401 transactions
```

Blocks are filtered every second or so. At current pace, it will take more than a day to finish filtering blocks. 

Here is the result of the `top` command:

```
top - 09:31:10 up 15:28,  2 users,  load average: 1.50, 1.54, 1.54
Tasks: 120 total,   1 running,  73 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.3 us,  1.5 sy,  0.0 ni, 69.6 id,  2.4 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :   949440 total,    44332 free,   369176 used,   535932 buff/cache
KiB Swap:  1048572 total,  1048564 free,        8 used.   473792 avail Mem
```

`dstat` shows that there is quite a bit of disk activity:

```
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw
 28   2  67   3   0   0| 781k  105k|   0     0 |   0     0 |3198  1456
 40  10  46   3   0   1|1024k   28k|5523B 3303B|   0     0 |3564  2215
 30   2  67   1   0   0| 248k    0 |3590B 3648B|   0     0 |2915  1149
 28   1  70   1   0   0|1116k   68k|2221B 1857B|   0     0 |3239  1343
 33   6  56   5   0   1| 916k   28k|5332B 1713B|   0     0 |3588  2188
 29   0  69   3   0   0|  68k 8192B|1147B 1738B|   0     0 |2636   756
 27   2  68   3   0   0|1032k   32k|3737B 2169B|   0     0 |3301  1546
 28   1  68   3   0   0| 760k   60k|3816B 2377B|   0     0 |3087  1240
 29   0  71   0   0   0|   0     0 | 264B  905B|   0     0 |2572   605
 29   1  65   5   0   0|1484k  100k|4322B 1973B|   0     0 |3412  1552
```

I don't know if it's of any help, but I recorded the syscalls by running `sudo strace -p `pidof lnd | tr ' ' ','` 2>&1 | grep -v clock_gettime` and the results are in this file: [strace.log](https://github.com/lightningnetwork/lnd/files/2351786/strace.log)

`netstat -a | grep 8332 | wc -l` gives a result of about 200 connections, all coming from localhost. They are nearly all in a `TIME_WAIT` status.

### Your environment

* version of `lnd` : lnd version 0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0
* which operating system (`uname -a` on *Nix) : Linux 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux. (Raspbian GNU/Linux 9.4 (stretch))
* version of `btcd`, `bitcoind`, or other backend : bitcoind v160200
* any other relevant environment details : The raspiblitz is a bitcoind+lnd full node running on a RaspberryPi 3. 

### Steps to reproduce

Set up a full node on a RaspberryPi, sync the blockchain and then wait for lnd to filter blocks

### Expected behaviour

I was expecting LND to filter blocks quicker. 

### Actual behaviour

LND takes a few days to filter blocks.

**Comment by Roasbeef** [comment]
There's nearly zero disk I/O done when filtering out blocks. I think most of those IOPs you're seeing are actually due to running bitcoind as well on the constrained system. When we're filtering blocks, we already have the block in memory so it's just a matter of CPU usage and allocations at that point. 

I'd check the settings you're using to run the bitcoind node, that you're not attempting to serve too many peers, wasting CPU on INVs, etc. 

> netstat -a | grep 8332 | wc -l gives a result of about 200 connections, all coming from localhost. They are nearly all in a TIME_WAIT status.

So with that information, I think bitcoind is responsible for most of the load. You should run with _conservative_ settings for bitcoind, since it's the process that consumes most of the resources.

**Comment by marcw** [comment]
@Roasbeef Thanks for the precision. Here is my bitcoin.conf

```
# bitcoind configuration

# mainnet/testnet - to switch just comment/uncomment
#testnet=1

# Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=1

# Connection settings
rpcuser=<rpcuser>
rpcpassword=<rpcpassword>
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

datadir=/home/bitcoin/.bitcoin
```

**Comment by Roasbeef** [comment]
Ah OK, re-reading that comment above, I see that those were all RPC connections. AFAIK, bitcoind doesn't support keep-alive on the RPC connections, so we're forced to create a new one for each request we have, which can start to stack up if it's catching up to the chain. 

I'm closing this as a duplicate so we can track it in this issue where the problem was initially raised: #1545
