### ISSUE TITLE
b\bdb\db.go:55:10: undefined: bolt

### ISSUE THREAD

**Issue by gccrpm** [lightningnetwork/lnd#1851]
go install    ./... 
# github.com/btcsuite/btcwallet/walletdb/bdb
..\..\btcsuite\btcwallet\walletdb\bdb\db.go:12:2: imported and not used: "github.com/coreos/bbolt"
..\..\btcsuite\btcwallet\walletdb\bdb\db.go:55:10: undefined: bolt
# github.com/lightningnetwork/lnd/macaroons
macaroons\service.go:18:2: imported and not used: "github.com/coreos/bbolt"
macaroons\store.go:10:2: imported and not used: "github.com/coreos/bbolt"
macaroons\store.go:49:2: bolt is not a package
macaroons\store.go:49:2: undefined: DB
# github.com/lightningnetwork/lnd/channeldb
channeldb\channel.go:15:2: imported and not used: "github.com/coreos/bbolt"
channeldb\db.go:13:2: imported and not used: "github.com/coreos/bbolt"
channeldb\db.go:92:2: bolt is not a package
channeldb\forwarding_log.go:9:2: imported and not used: "github.com/coreos/bbolt"
channeldb\forwarding_package.go:10:2: imported and not used: "github.com/coreos/bbolt"
channeldb\graph.go:19:2: imported and not used: "github.com/coreos/bbolt"
channeldb\invoices.go:12:2: imported and not used: "github.com/coreos/bbolt"
channeldb\meta.go:4:2: imported and not used: "github.com/coreos/bbolt"
channeldb\migrations.go:9:2: imported and not used: "github.com/coreos/bbolt"
channeldb\nodes.go:11:2: imported and not used: "github.com/coreos/bbolt"
channeldb\nodes.go:11:2: too many errors

**Comment by gccrpm** [comment]
how slove it

**Comment by cfromknecht** [comment]
`make && make install`
