### ISSUE TITLE
[Feature Request] Timeout for payinvoice (/v1/channels/transactions)

### ISSUE THREAD

**Issue by BitBargain** [lightningnetwork/lnd#1867]
We are using 'payinvoice' (or rather `/v1/channels/transactions` with a `payment_request` parameter).

It would be nice to have a 'timeout' parameter also, a specific time limit after which LND should give up trying to pay the invoice.

I'm guessing there is already one behind the scenes (1 minute, correct?), hopefully it's just a matter of making it available to be set through a parameter.

I understand that a workaround is possible through 'sendroute' but it involved multiple calls and plenty of extras. We've already implemented the invoice payments using `/v1/channels/transactions` and only need a timeout.

Thanks for your kind consideration.

**Comment by danielalexiuc** [comment]
I'd like to see this too.

@BitBargain what is the current workaround?

**Comment by BitBargain** [comment]
Daniel: Based on the responses, the situation is that even if you cancelled the payment there would still be a chance for it to be sent, since you just push it to nodes and the rest is up to them (at least until the expiry). The only real workaround (at least in my case) would be to make lightning non-instant and let users submit a withdrawal request and returning a result to them later, once the payment is successful or the timeout.

**Comment by PWKad** [comment]
@BitBargain you mentioned a workaround using sendtoroute but I don't see how that's possible?  Any links?

**Comment by halseth** [comment]
This can be done using the `routerrpc.SendPayment` API.

**Comment by wpaulino** [comment]
@PWKad https://github.com/lightningnetwork/lnd/blob/5485101f9f7640c1b4d6b10ac531a209e2e32715/lnrpc/routerrpc/router.proto#L40
