### ISSUE TITLE
privacy of transaction that gets broadcast when opening a channel

### ISSUE THREAD

**Issue by 3ntranced** [lightningnetwork/lnd#1868]
### Background

When I open a channel, the transaction that gets broadcast, is it broadcast through my node? How do I ensure my ip cannot be revealed with this transaction?

### Your environment

* lnd version 0.5.0-beta
* Linux 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
* Bitcoin Core Daemon version v0.16.1

**Comment by alexbosworth** [comment]
Your chain backend broadcasts the transaction

Tor is an option for improving your privacy, and the Dandelion WIP feature should also help

**Comment by Roasbeef** [comment]
Yep Tor is your best immediate option. If you're running with the neutrino mode, then all Bitcoin p2p traffic will be routed over Tor. If you're running with a full node backend, then you'll need to ensure that it's only making outbound connections over Tor, and either not listening, or also running as a Tor hidden service.
