### ISSUE TITLE
Add a SignMessage/VerifyMessage RPC command

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#187]
Within the network, _all_ announcements my other nodes are signed by the nodes that broadcast them. In addition all advertised channels are themselves transmitted with a set of channel authentication proofs that attest to the fact that two nodes consensually opened a channel with each other and are able to perform updates on that channel. 

The combination of channel authentication proofs and signed messages provide a very strong degree of attestation. It's possible that higher level applications may want to re-use these attestations to bind higher level identities to these sybil resistant attestations. For example, some new forum website may require an attestation from an active Lightning node with a least `N` channels with at least `K` BTC contained within them (think "fidelity bonds"). 

# Steps To Completion 

- [ ] Add two RPC methods to the current gRPC service: `SignMessage`, and `VerifyMessage`. 
- [ ] Propose a encoding scheme for the serialized signatures (possibly re-use a portion of `zpay32`?)
- [ ] Implement the two new methods within the RPC method.
- [ ] Add command-line support for the two methods.

**Comment by phlip9** [comment]
Hey, I'd like to take a stab at this issue.

I also have some questions/comments:

+ I'm assuming `SignMessage` would sign some arbitrary message with the node's `identityPriv` private key.
    + Is `nodeSigner.SignMessage` the canonical way to sign a message?
    + The signature could probably be encoded as `zbase32(s || crc32(s))` where `s := sig.Serialize()`.
    + We could probably pull out the `zbase32(msg || crc32(msg))` functionality that `zpay32` currently handles, since the signature would use the same scheme.
+ I'm guessing `VerifyMessage` would verify another node's signature on some message.
    + What is the canonical way to refer to another node?
        + It seems like a similar RPC call would be `OpenChannel`, which takes either a `peer_id` or a `node_pubkey`.

**Comment by Roasbeef** [comment]
Hi @phlip9, excited to hear you'd like to tackle this issue? 

> Is nodeSigner.SignMessage the canonical way to sign a message?

Yes, that'd be the ideal way to sign incoming messages. 

> The signature could probably be encoded as zbase32(s || crc32(s)) where s := sig.Serialize()

I don't think there's a need to include the checksum component as there isn't an _error correcting_ aspect. If the signature itself has been modified, then it'll fail to verify. 

Some thoughts on the serialization method: 
   * When signing a message, the only return value should be the encoded signature itself. In order to facilitrate quick pubkey recovery from the signature, the [`SignCompact`](https://godoc.org/github.com/btcsuite/btcd/btcec#SignCompact) function within `btcec` should be used. This'll append a header byte that tells the signature verifier _which_ of the possible recovered points are the target public key. 
   * We can then add a new publicly exported method to `zpay32` which simply encodes using `base32` and leaves off the check sum. As an alternative, we could use the `bech32` character set, but I don't think that's needed as I don't expect people to read off signatures over the telephone or attempt to copy them down by hand.

> I'm guessing VerifyMessage would verify another node's signature on some message.

Yes, `VerifyMessage` should take a signature, and a message and return a boolean indicating if the signature if value or not. The following steps should be performed when verifying a `(sig, msg)` pair: 

    * Perform [pubkey extraction](https://godoc.org/github.com/btcsuite/btcd/btcec#RecoverCompact) to recover the public key under which the message was signed. 
    * Using the extracted public key, query the graph database to see if the node is an active vertex within the graph or not. This current version can consider "active" to simply be properly announced, while future version may require some level of channel capitalization for the signature to be correct.

So with what's described above, the `VerifyMessage` RPC call only needs two parameters: the sig and the message.

**Comment by phlip9** [comment]
> > The signature could probably be encoded as zbase32(s || crc32(s)) where s := sig.Serialize()
>
> I don't think there's a need to include the checksum component as there isn't an error correcting aspect. If the signature itself has been modified, then it'll fail to verify.

Indeed, I was a bit confused about why the encoding would need a checksum. I thought it might've been to avoid conflating transmission and transcription errors with invalid signatures, but they shouldn't otherwise be needed.

> When signing a message, the only return value should be the encoded signature itself. In order to facilitrate quick pubkey recovery from the signature, the SignCompact function within btcec should be used. This'll append a header byte that tells the signature verifier which of the possible recovered points are the target public key.

Right, just returning a pubkey recoverable signature should be fine.

I'm also wondering what the protobuf type of the message should be. I suppose we could take either a UTF-8 string message or a byte array message. Haven't thought too much about the consequences of either.

**Comment by AndrewSamokhvalov** [comment]
@Roasbeef @phlip9 
>  For example, some new forum website may require an attestation from an active Lightning node with a least N channels with at least K BTC contained within them (think "fidelity bonds").

If I understood example correctly apart from the validation result it might be worth it also return `pubkey` of the node which generated this message, in order to be sure that message came from the particular node.

**Comment by Roasbeef** [comment]
Closed by #192.

**Comment by MaxFangX** [comment]
Without a way to recover the public key that signed a message (from the command line or RPC) given a signature and a message, apps cannot use the sign/verify mechanism for authentication, requiring instead another scheme like a username/password or other scheme, which is too high friction for a user who wants to simply pay a site and then be able to come back to that later. @phlip9 would it be possible to modify this implementation to include what @AndrewSamokhvalov suggested?

**Comment by phlip9** [comment]
The current implementation returns a pubkey recoverable signature, which
means you can derive the signing pubkey from the signature.

You could also explicitly return a pubkey for signing and require a pubkey
parameter for verification, which would be clearer imo.
