### ISSUE TITLE
Warning message about unknown option: bitcoind.rpchost

### ISSUE THREAD

**Issue by frennkie** [lightningnetwork/lnd#1870]
### Background

When I start LND I see a warning message in the log for the option bitcoind.rpchost:

```
2018-09-09 17:20:39.933 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:25: unknown option: bitcoind.rpchost
```

Line 25 simpy contains: `bitcoind.rpchost=127.0.0.1`

### Your environment

* version of `lnd`
`Version 0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0`
* which operating system (`uname -a` on *Nix)
`Linux hostname 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux` (RaspberryPi)
* version of `btcd`, `bitcoind`, or other backend
`bitcoind`

**Comment by halseth** [comment]
Can you post the whole config?

**Comment by saubyk** [comment]
I am getting a similar warning for 'bitcoind.rpcpass':

>lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=xxx --bitcoind.rpcpass=xxx --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333 --externalip=24.228.183.56

2018-09-09 11:51:06.699 [WRN] LTND: C:\Users\xxx\AppData\Local\Lnd\lnd.conf:15: unknown option: bitcoin.rpcpass

**Comment by saubyk** [comment]
lnd.conf

bitcoin.active=1
debuglevel=debug

#enable either testnet or mainnet
bitcoin.testnet=1

bitcoin.node=bitcoind
bitcoind.rpcuser=xxx
bitcoin.rpcpass=xxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28332

bitcoind.zmqpath=tcp://127.0.0.1:28332

externalip=x.x.x.x

#autopilot.active=1
#autopilot.maxchannels=7
#autopilot.allocation=0.2

**Comment by saubyk** [comment]
bitcoin.conf

testnet=1
txindex=1
server=1
dbcache=6000
daemon=1
rpcuser=xxx
rpcpassword=xxx
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

**Comment by frennkie** [comment]
```
[Application Options]
debuglevel=info
maxpendingchannels=5
alias=xxx
color=#68F442
rpclisten=0.0.0.0:10009
tlsextradomain=x.y.z
restlisten=127.0.0.1:8080
[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=xxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
```

**Comment by halseth** [comment]
Try setting the category [Bitcoind] above it

**Comment by frennkie** [comment]
Oh.. sorry.. I overlooked that there is a `[Bitcoin]`and a `[Bitcoind]` section. Solved.

**Comment by RhinoAK** [comment]
That resolved it for me... WOW the order of the Category solved for me as well.
