### ISSUE TITLE
No answer to `channel_reestablish` for unknown channels in case of channel db reset

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lnd#1882]
### Background

Investigating why I had no responses to `channel_reestablish` messages for any of my 4 channels to the same node (`02cf3cc45d8fee5055c4ba5a58fe22ae973685fa2cb43e2c5b6454eaa1d08066a8`, "lightningspin"), it turns out that the user "lost the channel database" some time ago and had restarted with a new database.

### Your environment

* version of `lnd`:  0.5.0-beta commit=2b448be048daf85cef4cbb37ceed4413fdb051e6

### Expected behaviour

I would expect `lnd` to reply to each `channel_reestablish` with an "unknown channel" `error` message referring to the corresponding `channel_id` so that my node knows that it needs to unilaterally close them.

To be clear, the spec isn't quite clear on that, it sounds like a reasonable thing to do.

### Actual behaviour

`lnd` doesn't reply to `channel_reestablish`, connection stays open.

**Comment by Roasbeef** [comment]
Fixed by #1937
