### ISSUE TITLE
lnd daemon not starting after a power failure on raspberrypi : rpc error / lnd.service:Failed / panic:invalid freelist page

### ISSUE THREAD

**Issue by brigittenico** [lightningnetwork/lnd#1889]
### Background

Despite bitcoind recovers fine, the Lightning network daemon won't restart properly after a random & inexpected power outage.

### Environment : Raspberry Pi 3B+ (sd card) raspibolt @stadicus
* version of `lnd` : lnd version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
* OS : Linux 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
* bitcoind : Core Daemon version v0.16.2

### Steps to reproduce

Power off your raspberry pi lightning node without entering the shutdown command

### Expected behaviour

The daemon should be able to restore a previously backed up channel db state upon restart

### Actual behaviour

channel.db seems corrupted : 
```
$ lncli getinfo
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable
...
...
cat /home/bitcoin/.lnd/lnd.conf
# lnd configuration
[Application Options]
debuglevel=debug
#info
debughtlc=true
maxpendingchannels=3
alias=myhost
color=#68F442
[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=*********
bitcoind.zmqpubrawblock=tcp://127.0.0.1:29000
bitcoind.zmqpubrawtx=tcp://127.0.0.1:29000
# node management
bitcoin.basefee=1000
bitcoin.feerate=1
[autopilot]
autopilot.active=1
autopilot.maxchannels=20
autopilot.allocation=0.6
autopilot.minchansize=200000
autopilot.maxchansize=16777215
...
...
$ sudo journalctl -f -u lnd                                                                                         
-- Logs begin at Wed 2018-09-12 14:06:09 CEST. --
sept. 12 15:04:35 myhost systemd[1]: Started LND Lightning Daemon.
sept. 12 15:04:35 myhost lnd[30854]: Attempting automatic RPC configuration to bitcoind
sept. 12 15:04:35 myhost lnd[30854]: Automatically obtained bitcoind's RPC credentials
sept. 12 15:04:35 myhost lnd[30854]: 2018-09-12 15:04:35.391 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:19: unknown option: bitcoind.rpcuser
sept. 12 15:04:35 myhost lnd[30854]: 2018-09-12 15:04:35.391 [INF] LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
sept. 12 15:04:35 myhost lnd[30854]: 2018-09-12 15:04:35.391 [INF] LTND: Active chain: Bitcoin (network=mainnet)
sept. 12 15:04:35 myhost lnd[30854]: panic: invalid freelist page: 4181, page type is branch
sept. 12 15:04:35 myhost systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sept. 12 15:04:35 myhost systemd[1]: lnd.service: Unit entered failed state.
sept. 12 15:04:35 myhost systemd[1]: lnd.service: Failed with result 'exit-code'.
...
...
$ strace -f -o strace.log lnd
Attempting automatic RPC configuration to bitcoind
Automatically obtained bitcoind's RPC credentials
2018-09-12 15:06:02.207 [WRN] LTND: /home/bitcoin/.lnd/lnd.conf:19: unknown option: bitcoind.rpcuser
2018-09-12 15:06:02.209 [INF] LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
2018-09-12 15:06:02.209 [INF] LTND: Active chain: Bitcoin (network=mainnet)
panic: invalid freelist page: 4181, page type is branch
goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*freelist).read(0x113073c0, 0x73e45000)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/freelist.go:237 +0x290
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist.func1()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:290 +0x114
sync.(*Once).Do(0x112a41f8, 0x1165db14)
        /usr/local/go/src/sync/once.go:44 +0xb8
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist(0x112a4140)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:283 +0x38
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.Open(0x1122d200, 0x30, 0x180, 0xf166f0, 0x30, 0x25, 0x1122d1d0)
      /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:260 +0x324
github.com/lightningnetwork/lnd/channeldb.Open(0x1122d1d0, 0x25, 0x3, 0x1122d1d0, 0x25)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:73 +0x90
main.lndMain(0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:162 +0x308
main.main()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:651 +0x14

...

**Comment by brigittenico** [comment]
To get out this issue I deleted the channel.db
I hope my little funds will be returned since I still wear the same public key ?
I didn't realize a channel db backup was necessary.
I have just a detailed channel list (from 1ml). Isn'it possible to re establish a channel with theses peers, according to previous channel ids, points, etc ? And to get back my btc fractions ?

**Comment by Roasbeef** [comment]
> To get out this issue I deleted the channel.db
With this action, you've lost _all_ of your channel date. You should _never_ delete any data within the lnd directory unless you're _sure_ you know what they hold. At this point, it isn't possibly to _easily_ get back your channel funds. However, it may be possible to write a specialized script to seek out your old channels and attempt to recover them on-chain.

**Comment by brigittenico** [comment]
What should I have done ? If I restart my node with the old corrupted channel.db the lnd crashes so I have no other choice but shutdown and move on.

And mostly, what can I do now ? 
I've already reconnected with my peers holding my ghost channels.
I can try to restart my node with the old channel db but only bitcoind gets working.

Please tell us how to recover funds that are still listed by `lncli listchaintxns` ;
How to restore a corrupted channel.db ?

**Comment by brigittenico** [comment]
@Roasbeef have you some clue about your foresaid script, or any plan to consider this as a issue to solve in future versions ?

**Comment by Roasbeef** [comment]
> What should I have done ? 

Possibly waited, many of us were busy with release preparations so this issue slipped by. 

> And mostly, what can I do now ?

Your channel state is likely gone. However, you'll be able to recover those on-chain funds.

**Comment by Roasbeef** [comment]
> or any plan to consider this as a issue to solve in future versions ?

Yes, on the recovery end, but if users delete data, then there isn't much we can do about that on our end.

**Comment by flack** [comment]
@brigittenico I know it's too late for that now, but in situations like these, it's almost always a good idea to not delete something, but simply rename it or move it to a different directory. For the program, the effect is the same as deletion, but you can still go back to the old state in case it turns out it was a bad idea

**Comment by brigittenico** [comment]
@flack @Roasbeef I've not deleted anything, just moved around the old corrupted db in order to restart the deamon.
So, please, how do i proceed to recover off-chain funds ?

**Comment by cfromknecht** [comment]
@brigittenico was your channeldb being stored on an SD card by chance? if so, i would ensure in the future that it is stored on the HDD, as boltdb seems to have crash consistency issues on such mediums

**Comment by brigittenico** [comment]
@cfromknecht unfortunately not, it was stored on a ssd powered by the raspberry and both were shutdown at time.
The sd card seems fine and the system is running well.

**Comment by brigittenico** [comment]
The updated version will not run with a corrupted database, in my case. Still wondering what to do.
```
$ bitcoind --version
Bitcoin Core Daemon version v0.16.3
$ lncli --version
lncli version 0.5 commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
bitcoin@myhost $ lncli unlock
Input wallet password:
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable
$ lncli getinfo
[lncli] unable to read macaroon path (check the network setting!): open /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory

$ sudo journalctl -u lnd -f
-- Logs begin at Sat 2018-09-22 06:50:17 CEST. --
sept. 22 09:03:02 myhost systemd[1]: Started LND Lightning Daemon.
sept. 22 09:03:02 myhost systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
sept. 22 09:03:02 myhost systemd[1]: lnd.service: Unit entered failed state.
sept. 22 09:03:02 myhost systemd[1]: lnd.service: Failed with result 'exit-code'.
sept. 22 09:04:02 myhost systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
sept. 22 09:04:02 myhost systemd[1]: Stopped LND Lightning Daemon.
sept. 22 09:04:02 myhost systemd[1]: Started LND Lightning Daemon.
sept. 22 09:04:02 myhost systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
sept. 22 09:04:02 myhost systemd[1]: lnd.service: Unit entered failed state.
sept. 22 09:04:02 myhost systemd[1]: lnd.service: Failed with result 'exit-code'.

$ strace -f -o strace.log lnd
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

$ sudo cat /home/bitcoin/.bitcoin/bitcoin.conf
    # bitcoind configuration
    # remove the following line to enable Bitcoin mainnet
    # testnet=1
    # Bitcoind options
    server=1
    daemon=1
    txindex=1
    disablewallet=1
    # Connection settings
    rpcuser=raspibolt
    rpcpassword=**********
    rpcallowip=192.168.1.1/24
    zmqpubrawblock=tcp://127.0.0.1:28332
    zmqpubrawtx=tcp://127.0.0.1:28333
    # Raspberry Pi optimizations
    dbcache=100
    maxorphantx=10
    maxmempool=50
    maxconnections=40
    maxuploadtarget=5000
    datadir=/home/bitcoin/.bitcoin

$ sudo cat /home/bitcoin/.lnd/lnd.conf
    # lnd configuration
    [Application Options]
    debuglevel=debug
    maxpendingchannels=3
    alias=myhost
    color=#68F442
    [Bitcoin]
    bitcoin.active=1
    bitcoin.mainnet=1
    bitcoin.node=bitcoind
    bitcoind.rpcuser=raspibolt
    bitcoind.rpcpass=**********
    bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
    bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
    bitcoin.basefee=1000
    bitcoin.feerate=1 
    [autopilot]
    autopilot.active=1
    autopilot.maxchannels=20
    autopilot.allocation=0.6
    autopilot.minchansize=200000
    autopilot.maxchansize=16777215



```

**Comment by cfromknecht** [comment]
@brigittenico do you have any logs from before the crash?

**Comment by brigittenico** [comment]
I will do as you, answer with a question, the one I ask above :
> how do i proceed to recover off-chain funds ?
Sorry I'm angry against lnd which make me lose money.

**Comment by Roasbeef** [comment]
> Sorry I'm angry against lnd which make me waste some money and plenty of time.

We recommend running with reliable hardware for the interim future. If you have your seed, you can recover the on-chain funds. As for the off-chain funds, only if static channel backups were in place would you be able to restore those funds. This is very high priority for us, and should land in our upcoming 0.5.1 release.
