### ISSUE TITLE
Fully synchronized and running LND consumes more and more CPU, until 100%

### ISSUE THREAD

**Issue by BobleChinois** [lightningnetwork/lnd#1899]
### Background

LND's CPU usage has been abnormally high for the last days.

### Your environment

* version of `lnd` : `"version": "0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"`
* which operating system : `Linux Celeri 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `bitcoind` : 
```
"version": 160200,
  "subversion": "/Satoshi:0.16.2/",
  "protocolversion": 70015,
```
* any other relevant environment details : `getinfo` output : 
```
{
    "identity_pubkey": "0306ea2f621073076c33f190eb8843e79653d5fc1375c2196f8c90875434d4aa74",
    "alias": "Sosthene ☇",
    "num_pending_channels": 0,
    "num_active_channels": 6,
    "num_peers": 11,
    "block_height": 541230,
    "block_hash": "00000000000000000016fa5755f2b93882199232ef042d46272a9af7c08711bc",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "0306ea2f621073076c33f190eb8843e79653d5fc1375c2196f8c90875434d4aa74@5.51.82.169:9735"
    ],
    "best_header_timestamp": "1536833477",
    "version": "0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"
}
```
* I recently experienced a lot of networking issues and reinstalled Network Manager just before the problem occured. I don't see any link, but as lnd seemed to start to freak out at the same time I'd rather mention it.

### Steps to reproduce

I have been running lnd for at least 3 months almost uninterrupted, and CPU usage has been consistently low (around 2 or 3%).
I noticed two days ago that lnd was consuming almost 100% of my CPU, it was fully synced and has been running for some time.
After restart, CPU usage is back to normal, but it progressively grows until it eats almost all my CPU.
I thought that maybe `nochanupdates` could help, but after maybe 12 hours or so I found out that CPU usage was very high again (more than 70% now).
Logs don't show abnormal activity, at least as far as I can tell.

### Expected behaviour

CPU usage should be consistent and low.

### Actual behaviour
CPU usage is growing with runtime and eventually becomes very high.

**Comment by wpaulino** [comment]
There have been a lot of performance improvements since the version that you're currently on (v0.4.2-beta). I would recommend upgrading to master or one of the 0.5 release candidates and see if you're still having high CPU usage.

**Comment by Roasbeef** [comment]
Closing this as performance has been dramatically improved in 0.5 which will be released shortly. I would also crank the debug level up to `PEER=debug`, so you can see what's going on w.r.t the p2p network.
