### ISSUE TITLE
Remote peer replies with an Error instead of force-closing a channel

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#1904]
### Background

BLW user had a channel open with a https://1ml.com/node/02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469 and decided to close it cooperatively. During closing negotiations user got a signature which was considered invalid by BLW (exception raised at https://github.com/btcontract/lnwallet/blob/f2d4576edc67e98873e294590860e016d8d464f4/app/src/main/java/fr/acinq/bitcoin/Script.scala#L627).

Due to a bug which was then present in BLW a channel was not locally force-closed automatically, the wallet just did nothing. After not finding a manual force-close option (another UX issue) user decided to completely remove wallet data and then restore it which was successful but since restored channel's state was gone it's only option left is `data-loss-protect` protocol but remote peer does not force-close a channel locally when requested and replies with a `Sync error` instead.

I've obtained wallet data to test it and here's a communication log:

```
incoming <-- Init(,82)
incoming <-- ChannelReestablish(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,9,8,Some(c8e139e2512b48387453d0fe357311a0ae01192deb055d2f88cce9cdef8becdd),Some(029f7b244beef657bd7d381c2bde70bfab55c380288f7ba0289523f54f80635a6e))
outgoing --> Error(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,706c65617365207075626c69736820796f7572206c6f63616c20636f6d6d69746d656e74)
incoming <-- Error(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,73796e63206572726f72)
```

Remote channel state as provided by @slush0:

```
{
            "active": false,
            "remote_pubkey": "03d8fd6f16702fbfde85aef3204d6500568e151db9adf05b4e3118180c72ae7c97",
            "channel_point": "c8fa856f0026ab1dbe895ce736008ed4316c718610a18ac88043fcf364c917a5:1",
            "chan_id": "591528459752767489",
            "capacity": "300000",
            "local_balance": "1000",
            "remote_balance": "296027",
            "commit_fee": "2973",
            "commit_weight": "724",
            "fee_per_kw": "4106",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "1000",
            "num_updates": "8",
            "pending_htlcs": [
            ],
            "csv_delay": 2000,
            "private": true
        }
```

Remote log excerpt as provided by @slush0:

```
Except of thousands lines of 

"2018-09-03 13:15:15.433 [INF] HSWC: Removing channel link with ChannelID(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9)
2018-09-03 13:15:21.232 [INF] HSWC: Adding live link chan_id=a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9, short_chan_id=537992:1561:1"

 I don't see anythong related this channel in my logs.
```

### Your environment

version of `lnd`: master
perhaps @slush0 can add more info here.

### Expected behaviour

Remote peer force-closes a channel on getting our `Error`.

### Actual behaviour

Remote peer replies with a `Sync error` and does nothing.

**Comment by Roasbeef** [comment]
We don't force close on errors as that would cause if (if we're the initiator) to eat fees at the remote peers whim and also suspend our funds. The bigger Q here is why we didn't force close after y'all sending ChannelReestablish message, or was that not send in this transcript?

**Comment by btcontract** [comment]
When in `data-loss-protect` state, BLW does not send a `ChannelReestablish` but only an `Error` in response to any remote message. Is there any way to make a remote peer force-close a channel in this situation, for instance, will dummy `ChannelReestablish` do that?

**Comment by btcontract** [comment]
The idea generally is there no need for you to know that but just react to a remote error as per BOLT02: 

> The error returned by the fallen-behind node (or simply the invalid numbers in the channel_reestablish it has sent) should make the other node drop its current commitment transaction to the chain.

But I totally get the decision to not automatically close on remote `Error`, in my wallet I show user a notification with an option to force-close a channel manually in this case. I'll update code to send an invalid `ChannelReestablish` and see how it goes.

**Comment by Roasbeef** [comment]
As we don't yet have error codes in place, it would possibly be irresponsible to force close on each `Error` message we get, and that would also become a DoS vector.

**Comment by Roasbeef** [comment]
Closing this for now since this is in line with our policy, and we expect a `ChannelReestablish` in order to trigger the data loss protection.

**Comment by btcontract** [comment]
Can confirm it works now, remote peer still sends a "sync error" but also force-closes a channel, a messaging log:

```
<-- Init(,82)
<-- ChannelReestablish(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,9,8,Some(c8e139e2512b48387453d0fe357311a0ae01192deb055d2f88cce9cdef8becdd),Some(029f7b244beef657bd7d381c2bde70bfab55c380288f7ba0289523f54f80635a6e))
--> ChannelReestablish(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,9223372036854775807,0,Some(0000000000000000000000000000000000000000000000000000000000000000),Some(030317c21a348db31ad8eaa35114c83714c51e210a33dd6492df378c0cd0515594))
<-- Error(a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9,73796e63206572726f72)
<got a refunding tx>
```
