### ISSUE TITLE
unable to start server: -26: 66: min relay fee not met

### ISSUE THREAD

**Issue by lra** [lightningnetwork/lnd#1912]
### Background

My testnet lnd does not want to start anymore, as soon as I unlock the wallet, it crashes with the error `unable to start server: -26: 66: min relay fee not met`.

### Your environment

* version of `lnd`: `version 0.5 commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d`
* which operating system (`uname -a` on *Nix): `Linux lightning 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend `bitcoind v0.16.2`
* any other relevant environment details

### Steps to reproduce

```
$ lncli unlock
```
Then in the logs I get:
```
Sep 15 00:12:50 lightning lnd[7058]: 2018-09-15 00:12:50.567 [ERR] UTXN: Failed to re-register first-stage HTLC output 7f0cee03f2b2bea0e3772da02b9a287c6ef54082824b8d2d538fce6244281646:0
Sep 15 00:12:50 lightning lnd[7058]: 2018-09-15 00:12:50.568 [ERR] UTXN: Failed to regraduate outputs at height=1403750: -26: 66: min relay fee not met
Sep 15 00:12:50 lightning lnd[7058]: 2018-09-15 00:12:50.568 [INF] NTFN: Cancelling epoch notification, epoch_id=3
Sep 15 00:12:50 lightning lnd[7058]: 2018-09-15 00:12:50.568 [ERR] SRVR: unable to start server: -26: 66: min relay fee not met
Sep 15 00:12:50 lightning lnd[7058]: 2018-09-15 00:12:50.571 [INF] LTND: Shutdown complete
Sep 15 00:12:50 lightning lnd[7058]: -26: 66: min relay fee not met
```

### Expected behaviour

`lnd` should not crash.

### Actual behaviour

`lnd` is crashing.

**Comment by Roasbeef** [comment]
Looks like you hit an issue that's been patched in the latest version of `lnd`, but if you still have a pre-signed transaction that you can hit it. The current solution is to lower the `minrelayfee` on your bitcoind node, then restart it. This show allow the transaction to enter the mempool.

**Comment by lra** [comment]
That fixed it, at least it's now graduating new blocks. Thanks!
