### ISSUE TITLE
macaroon not found for mainnet issue with testnet newaddress RPC

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#1914]
### Background

Bitcoind Testnet
LND testnet
run command `lncli newaddress p2wkh`
`lncli] unable to read macaroon path (check the network setting!): open /home/user/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory`

### Your environment
```
[Application Options]
color=#fff000
alias=testnetnode
;externalip=<public ip address> 

[Bitcoin]
bitcoin.active=1 
bitcoin.testnet=1
bitcoin.node=bitcoind
```
* version of `lnd` 
master
* which operating system (`uname -a` on *Nix) 
Linux testnode 4.15.0-1019-gcp #20~16.04.1-Ubuntu SMP Thu Aug 30 11:52:19 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend 
bitcoind 0.16.2
* any other relevant environment details
Even if I run LND with "--no-macaroons" it will still happen
### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by miketwenty1** [comment]
Also.. If I add
```
no-macaroons=true
adminmacaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon
readonlymacaroonpath=~/.lnd/data/chain/bitcoin/testnet/readonly.macaroon
invoicemacaroonpath=~/.lnd/data/chain/bitcoin/testnet/invoice.macaroon
```
to lnd.conf it makes no difference.

**Comment by miketwenty1** [comment]
TEMP FIX: 
```
mkdir -p ~/.lnd/data/chain/bitcoin/mainnet/
cp ~/.lnd/data/chain/bitcoin/testnet/* ~/.lnd/data/chain/bitcoin/mainnet/
```

**Comment by cfromknecht** [comment]
@miketwenty1 Try passing `--network=testnet` to `lncli`?

**Comment by miketwenty1** [comment]
in release notes

**Comment by cfromknecht** [comment]
Yes since the client is stateless. One suggestion is to use `alias tlncli=“lncli --network=testnet`, and similar for simnet

**Comment by A-qiu161203** [comment]
> Yes since the client is stateless. One suggestion is to use `alias tlncli=“lncli --network=testnet”`, and similar for simnet

hello,I try this method :lncli --rpcserver=localhost:xxxxxx --no-macaroons --network=simnet create. But it still doesn't work.

**Comment by A-qiu161203** [comment]
> TEMP FIX:
> 
> ```
> mkdir -p ~/.lnd/data/chain/bitcoin/mainnet/
> cp ~/.lnd/data/chain/bitcoin/testnet/* ~/.lnd/data/chain/bitcoin/mainnet/
> ```

hello~ Can this method work?
