### ISSUE TITLE
[Feature Request] Autopilot: add possibility to check running status and settings

### ISSUE THREAD

**Issue by frennkie** [lightningnetwork/lnd#1918]
Currently the only way to check whether the **autopilot** is enabled and which settings are active is by looking into the `lnd.conf` file (which even could have been modified since the last start).

It would be great to have a `lncli` command that lists the status and settings.

*Bonus Feature*: Being able to change settings (e.g. max channels/allocation)

**Comment by halseth** [comment]
Currently, no.

**Comment by frennkie** [comment]
Wouldn't it make sense to have it...?!

If it makes sense then it might be more more useful to flag this as a `feature request` / `help wanted` instead of closing, no?

**Comment by halseth** [comment]
Yeah, definitely :)  Can you edit the title and description?

**Comment by Roasbeef** [comment]
Now that the autopilot sub-server is in, it can be extended to allow users to modify parameters or targets while it's active.

**Comment by halseth** [comment]
Closing, as this is mostly addressed now. If there are specific features wanted in the RPC, they can get their own issue.

**Comment by frennkie** [comment]
@halseth nice to see this has been done! :-D Just one question.. currently the compiled releases do not include the `autopilotrpc` flag. Is there any timeline/policy when this will be enabled by default?

For now I will simply patch this in for my node.

**Comment by halseth** [comment]
@frennkie  No timeline but we are evaluating it :)
