### ISSUE TITLE
[Solved] Build fails: "scratch directory /home/bitcoin/gocode/src/github.com/lightningnetwork/lnd/.vendor-new already exists, please remove it"

### ISSUE THREAD

**Issue by gabridome** [lightningnetwork/lnd#1920]
### Background

Posted just in case someone else has the same problem.

**Resolved by making a `make clean` before**.

(It has never been necessary)

Upgraded with git pull. Trying to do
`make && make install"

### Your environment
* version of `lnd`
commit 3b2c807288b1b7f40d609533c1e96a510ac5fa6d
Fri Sep 14 12:35:00 2018 -0700

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.0rc2

* any other relevant environment details

### Steps to reproduce
updated to latest commit

### Expected behaviour

build and run.

### Actual behaviour

It is not possible to build the update.
```
$ make
 Compiling dependencies.
dep ensure -v
grouped write of manifest, lock and vendor: scratch directory /home/bitcoin/gocode/src/github.com/lightningnetwork/lnd/.vendor-new already exists, please remove it
Makefile:113: recipe for target 'dep' failed
make: *** [dep] Error 1
```

**Comment by gabridome** [comment]
As I wrote, by making a `make clean` before `make && make install` the problem is resolved.

**Comment by cfromknecht** [comment]
@gabridome yes there's been a recent issue with `dep` where it can't properly install the dependencies to the vendor directory. We [recently modified](https://github.com/lightningnetwork/lnd/pull/1901) `make clean` to properly remove the directories that caused the issue, glad it worked!
