### ISSUE TITLE
Unable to apply migration #4;  unable to open channeldb: unable to update edge policies: unable to fetch node: ****, unable to find node

### ISSUE THREAD

**Issue by JTopanov** [lightningnetwork/lnd#1929]
### Background

After upgrade to v. 0.5 I am unable to start LND node.
Error message:  unable to open channeldb: unable to update edge policies: unable to fetch node: 028925a789df879d8cde4149f099efd76f4bcab87a30c2e6f48e34a984300343f6, unable to find node
ln

### Your environment

lnd --version
lnd version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d

uname -a
Linux schhh-lightning 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

btcd --version
btcd version 0.12.0-beta

 -- Mainet
  -- No channels with the node that can't be fetched.
  -- The node in issue is not even in peer list.
  -- During my investigation I figured out that if I remove the channeldb from data folder, I am enable to start the node, but all channels and channel balances are lost.
  -- I revert back to version  0.4.2-beta and I am running a health node:
  ---- 18 open channels
  ------ 15 active=true, 
  ------ 3 active = false 

### Steps to reproduce

1, stop lnd daemon
-- lnd stop
2. Update the lnd version
-- cd $GOPATH/src/github.com/lightningnetwork/lnd
-- git pull
-- make && make install

3. start lnd deamon:
-- lnd

### Expected behaviour
lnd daemon v. 0.5 starts and waits for wallet password

### Actual behaviour

Log nohup.out: 

2018-09-17 19:46:30.180 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-09-17 19:46:30.181 [INF] CHDB: Checking for schema update: latest_version=6, db_version=3
2018-09-17 19:46:30.181 [INF] CHDB: Performing database schema migration
2018-09-17 19:46:30.181 [INF] CHDB: Applying migration #4
2018-09-17 19:46:30.206 [INF] CHDB: Unable to apply migration #4
2018-09-17 19:46:30.209 [ERR] LTND: unable to open channeldb: unable to update edge policies: unable to fetch node: 028925a789df879d8cde4149f099efd76f4bcab87a30c2e6f48e34a984300343f6, unable to find node
2018-09-17 19:46:30.209 [INF] LTND: Shutdown complete
unable to update edge policies: unable to fetch node: 028925a789df879d8cde4149f099efd76f4bcab87a30c2e6f48e34a984300343f6, unable to find node

**Comment by Roasbeef** [comment]
Which precise commit were you on before updating? You can use `git reflog` to find the precise commit.

**Comment by JTopanov** [comment]
I need to clarify the following:
1. I reverted back to previous "known good" version (v 0.4.2) ,so at the moment I am running the node using this version.
2. For test purposes, I created a new user in Linux and installed fresh lnd (v 0.5) from GitHub under this user.
 As a result I was able to create a new wallet and to start the node (v 0.5) using the new wallet.
Afterwards, I stopped the both nodes (v 0.4.2 and v 0.5), I copied the data folder (wallet that contains my funds and channels) from the old node (v 0.4.2) to the data folder of new node (v 0.5).
I was unable to start the new node (v 0.5) with old wallet - same issue as in my description.


3. Bellow is the information about precise commit of node that works fine at the moment (v 0.4.2)

$ git reflog
bca926d HEAD@{0}: checkout: moving from master to bca926d
baee07e HEAD@{1}: pull: Fast-forward
f0f5e11 HEAD@{2}: pull: Fast-forward
bca926d HEAD@{3}: pull: Fast-forward
d98d452 HEAD@{4}: clone: from https://github.com/lightningnetwork/lnd


Please, let me know if you need additional info.

**Comment by Roasbeef** [comment]
> As a result I was able to create a new wallet and to start the node (v 0.5) using the new wallet.
Afterwards, I stopped the both nodes (v 0.4.2 and v 0.5), I copied the data folder (wallet that contains my funds and channels) from the old node (v 0.4.2) to the data folder of new node (v 0.5).
I was unable to start the new node (v 0.5) with old wallet - same issue as in my description.

If you started the 0.5 node, and then copied from the 0.4.2 node, to the 0.5 node, then this report possibly makes sense. In 0.5 the on-disk structure for all announcements has an extra set of bytes appended to it, meaning we can't read the 0.4.2 state from 0.5. 

When you say "data directory" which files and folders do you mean specifically?

**Comment by Roasbeef** [comment]
On both my testnet and mainnet nodes, I can't find that node pubkey either in my view of the network. Did you update to any intermediate commits? There was a prior version (a dirty commit between 0.4.2 and 0.5) that had a bug where it would remove a node too early, causing the database state to be inconsistent. Checking your reflog dump, you were on this commit in the past. As a result, your primary course of action is to re-create your node by sweeping all funds to a node node. Alternatively, a more hacky fix is to just skip over that check and remove the channel from the on disk state.

**Comment by JTopanov** [comment]
As I mentioned, I tried both methods to upgrade to version 0.5:
1. Update the lnd version
-- cd $GOPATH/src/github.com/lightningnetwork/lnd
-- git pull
-- make && make install

2. Clean installation of lnd
-- go get -d github.com/lightningnetwork/lnd
-- cd $GOPATH/src/github.com/lightningnetwork/lnd
-- make && make install

Both methods lead me to the same result, when I attempt to use my original wallet.

> When you say "data directory" which files and folders do you mean specifically?

The files contained in my data folder are below:
`ls -l data/
total 52
-rw------- 1 lnd lnd   232 Jul  7 21:38 admin.macaroon
drwx------ 3 lnd lnd  4096 Jul  7 21:38 chain
drwx------ 3 lnd lnd  4096 Jul  7 21:39 graph
-rw-r--r-- 1 lnd lnd   115 Jul  7 21:38 invoice.macaroon
-rw------- 1 lnd lnd 32768 Sep 20 16:10 macaroons.db
-rw-r--r-- 1 lnd lnd   183 Jul  7 21:38 readonly.macaroon
`

Moreover, during my experiments, I figured out that if I delete file `data/graph/mainnet/channel.db`, I am able to run the node using lnd (v. 0.5), but all my channels are gone.

In addition, when I run the node using lnd (v. 0.4.2) I can see all my channels and funds, but I noticed the following issue:
When I attempt to `getnetworkinfo` or to `describegraph`, the following errors appear:
`getnetworkinfo
[lncli] rpc error: code = Unknown desc = unable to find node
` 

`describegraph
[lncli] rpc error: code = Unknown desc = unable to find node
`
I believe I am affected by issue #1607 which is resolved by #1600, but I am not sure how to perform the solution.
Any directions will be appreciated.

**Comment by Roasbeef** [comment]
Yeah the issue you're running into is due to you being on a "dirty" commit between the past two versions. It's been fixed in master as is, there're are two solutions: patch your node to not see missing a node as an error, or start a new code from 0.5. I'd generally recommend the latter approach, as the fist could cause greater issues down the line.

**Comment by JTopanov** [comment]
I checked the status of my running node (v 0.4.2) yesterday (29.09.2018) and I noticed that I was able to run "getnetworkinfo" and "describegraph".

I checked the logs and noticed that some of nodes and channels were pruned successfully.

Afterwards I managed to update my node using standard method (git pull; make && make install).

Now, the node has version (0.5.0-beta) and it is running with the original wallet. I am able too see all my funds and channels as expected.

I don't know how, but the issue has been resolved. Thank you for the assistance, I will proceed with closure of this thread.

**Comment by beedub** [comment]
I'm seeing this issue as well.

```
2018-12-01 19:42:10.397 [INF] LTND: Version: 0.5.1-beta commit=v0.5.1-beta-66-g7a39131a85958e238dfe830e2b5b496e80cb31e9, build=production, logging=default
2018-12-01 19:42:10.398 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-12-01 19:42:10.399 [INF] CHDB: Checking for schema update: latest_version=7, db_version=3
2018-12-01 19:42:10.399 [INF] CHDB: Performing database schema migration
2018-12-01 19:42:10.399 [INF] CHDB: Applying migration #4
2018-12-01 19:42:10.509 [INF] CHDB: Unable to apply migration #4
2018-12-01 19:42:10.513 [ERR] LTND: unable to open channeldb: unable to update edge policies: unable to fetch node: 031e8f3e16f06f78249497161f23fa50b3218c7a15c895149459942836ffc53f6c, unable to find node
2018-12-01 19:42:10.513 [INF] LTND: Shutdown complete
```

I was previously running 0.4.2. I had one channel that was stuck in force close pending, which is why I decided to upgrade. This channel may be that channel.

Any ideas on how I can resolve?

**Comment by halseth** [comment]
Hi @beedub! I have a PR up that should fix your problem now: #2279

You can try to run it and see if it fixes the issue you are seeing :)

**Comment by beedub** [comment]
@halseth just installed this version and `lnd` seems to be running properly again. thanks!

**Comment by halseth** [comment]
@beedub Glad to hear! To be clear: after you have run my patch once you can go back to running normal `lnd` releases, as the database should be fixed :)

**Comment by halseth** [comment]
Note that we still want #2279 to handle this scenario consistently.
