### ISSUE TITLE
Daemon Crash 

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#194]
Here's the output:
https://pastebin.com/XcwYJYXv

On commit: 4fd285236e07e04e10cf660b843a47ed26fd8035

I was in the middle of sending debug payments via the cli manually.

**Comment by AndrewSamokhvalov** [comment]
Hi @juscamaren! Thank for send crash output. Could you check please that you are running latest version of `lnd`?

**Comment by AndrewSamokhvalov** [comment]
Ooops, that was `Apr 22` sorry :)

**Comment by AndrewSamokhvalov** [comment]
As the historical note from @Roasbeef about that issue:

> It's due to a desync bug, old htlc is there, new htlc is forwarded, we examine list of cleared htlc's, but it's after a restart, so the blob is actually nil".

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/commit/249e5781304a7bd4ec00496db9cf43b0070c44cc.
