### ISSUE TITLE
When opening a channel I get an exceeded pending limit error, but have none pending

### ISSUE THREAD

**Issue by JWWeatherman** [lightningnetwork/lnd#1940]
### Background

When I attempt to open a channel either using lncli I get the error:

[lncli] rpc error: code = Code(101) desc = Number of pending channels exceed maximum

Even though I have no pending channels:

root@blarg:~/btcpayserver-docker# ./bitcoin-lncli.sh pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

### Your environment

* version of `lnd` 0.4.2
* Ubuntu
* bitcoind

### Steps to reproduce

I've been opening a closing channels with 6 or so other nodes for the last few days.

**Comment by JWWeatherman** [comment]
After restarting the service I no longer get the error and am unable to reproduce.

**Comment by Roasbeef** [comment]
If you open a channel _to_ another node that has too many channels, the you can get this error.
