### ISSUE TITLE
tests: integration tests fail attempting to establish connection to bitcoind

### ISSUE THREAD

**Issue by ccdle12** [lightningnetwork/lnd#1946]
### Background

When calling `make check` or specifically `cd lnwallet && go test interface_test.go`,

Passes the checks of starting bitcoind but fails with establishing connection, maybe it's do with ZMQ?

### Your environment

* lnd version 0.5.0-beta commit=6d759bd8d9f1595f32fba6f901db4dcb78b6613e
* OS: MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
* bitcoind: Bitcoin Core Daemon version v0.16.99.0-4754a0adf-dirty
* btcd: btcd version 0.12.0-beta
### Steps to reproduce

1. `make && make install`
2. `make check` or `cd lnwallet && go test interface_test.go`

Stack Trace: 
```interface_test.go:2350: unable to establish connection to bitcoind: Post http://127.0.0.1:33779: dial tcp 127.0.0.1:33779: connect: connection refused```

Line in Code:
* interface_test.go
* Line 2349
```if err := chainConn.Start(); err != nil { t.Fatalf("unable to establish connection to "+"bitcoind: %v", err)```

### Expected behaviour

The tests should pass.

### Actual behaviour

Tests fail due to unable to establish connection to bitcoind

**Comment by halseth** [comment]
Is your `bitcoind` compiled with ZMQ support? Does it work if you run `lnd` normally?

**Comment by ccdle12** [comment]
Hi @halseth ,

Turns out the version I was using wasn't compiled with ZMQ support.

I upgraded to `Bitcoin Core Daemon version v0.17.99.0-9a3a984bb`, and the tests are passing.

Thanks for the help and I'll close the issue.
