### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#1947]
`lnd` dependencies should be updated after the following changes are merged:

- [x] https://github.com/btcsuite/btcd/pull/1217
- [x] https://github.com/lightninglabs/neutrino/pull/98
- [x] https://github.com/lightninglabs/neutrino/pull/96
- [x] https://github.com/lightninglabs/neutrino/pull/108
- [x] https://github.com/btcsuite/btcwallet/pull/541

**Comment by mryellow** [comment]
Unfamiliar with dependency management in GoLang but it looks like Renovate supports it via `go.mod` files. It automatically posts PRs with updates as they become available.

* Renovate will search each repository for any `go.mod` files.
* Existing dependencies will be extracted from require statements
* Renovate will resolve the dependency's source repository and check for semver tags if found (GitHub-only currently)
* If the source repository has either a "changelog" file or uses GitHub releases, then Release Notes for each version will be embedded in the generated PR.

https://renovatebot.com/docs/golang/

**Comment by Roasbeef** [comment]
All deps updated!
