### ISSUE TITLE
Litecoin p2sh addresses not supported with sendcoins

### ISSUE THREAD

**Issue by PatrickLemke** [lightningnetwork/lnd#1949]
### Background

When trying to send funds on-chain to a p2sh address using the sendcoins method an error occurs, saying that the address format is invalid.

### Your environment

* lnd version 0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0
* Linux raspberrypi 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
* Litecoin Core Daemon version v0.16.3

**Comment by ErikEk** [comment]
I think it's because of a problem with the btcsuite package.

**Comment by Roasbeef** [comment]
Fixed by eb30870d8f5833183dc50acfe1b31e45841b96b2.
