### ISSUE TITLE
Invoice payment in limbo for several days, listed as pending_htlcs, what is going on?

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#1965]
Here is the senario, someone requested that I pay an invoice. Like this: 

`lnbc81400n1pd6fcckpp5m8vqd290m0xs84c42aukt98hrdv4tr55yzjq3hlpultswl78lrwqdpqd35kw6r5de5kuemnd3hhgmtpvd5xjmn9cqzyskytzntl3q3tzlg8jl9qqac0a437lmzxcpemmrve8t0wxsshrrefslmde95vjyujnk6h8gldhenl2n36wupzzzcnpwke6c72fyjwvfuqpvvht4u`

decoded: 

```
{
    "destination": "0294f37ee9e26f9107a16414b691978033efd4e0f0e3aa99d309c4be3f3003124f",
    "payment_hash": "d9d806a8afdbcd03d71557796594f71b59558e9420a408dfe1e7d7077fc7f8dc",
    "num_satoshis": "8140",
    "timestamp": "1537532694",
    "expiry": "3600",
    "description": "lightningslotmachine",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144",
    "route_hints": [
    ]
}
```

I attempt to pay the invoice, but nothing happens, no response from lnd. Since this payout is automated I have to return a 404 error to the user. Not great.

Then I get a complaint that the money never arrived, not so strange, so I take a look and I find the payment here: 

```
        {
            "active": true,
            "remote_pubkey": "0232e20e7b68b9b673fb25f48322b151a93186bffe4550045040673797ceca43cf",
            "channel_point": "5934bf3804b4cc4e42ac730ea285fb148e05d96ccb042532c1b2dace56dc61f7:1",
            "chan_id": "596172796792995841",
            "capacity": "809335",
            "local_balance": "121065",
            "remote_balance": "678989",
            "commit_fee": "1140",
            "commit_weight": "896",
            "fee_per_kw": "1272",
            "unsettled_balance": "0",
            "total_satoshis_sent": "678989",
            "total_satoshis_received": "0",
            "num_updates": "75",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "8141",
                    "hash_lock": "2dgGqK/bzQPXFVd5ZZT3G1lVjpQgpAjf4efXB3/H+Nw=",
                    "expiration_height": 542817
                }
            ],
            "csv_delay": 144,
            "private": false
        },
```

This is already two days ago, but still it's 261 blocks until the **expiration_height**. What does this mean? I can't cancel this can I? I just have to wait for another 43 hours and see? maybe the transaction goes through, maybe it fails? 

Can I prevent this in the future by adding a smaller time frame for the payment to be routed? I really don't want to risk having to wait for several days for transactions to go through. Can I pay an invoice and say, if it does not succeed within 60 seconds, cancel it? 

PS. I think lightning is great, I have already processed several hundred transactions and 90% of the time it's instant. So great to job!

### Your environment

* version of `lnd`

"version": "0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d"

* which operating system (`uname -a` on *Nix)

Linux RaspiBolt 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

 bitcoind version": 160300

**Comment by Roasbeef** [comment]
Your HTLC is in the time out process. This can happen if the receiving side holds onto the HTLC for w/e reason, or somewhere in the middle of the route a node is down/faulty/crashed, etc and they never cancel back the HTLC. Each additional hop adds a time lock, as the route gets longer the time lock gets longer. Atm, the default setting of `lnd` is on the high-ish side as an initial precautionary measure. In the future, we'll lower this value to somewhere in the 10-20s of blocks. '

> Can I prevent this in the future by adding a smaller time frame for the payment to be routed?

In the future, you can add a constraint of the _max_ delay that any payment will incur. 

> Can I pay an invoice and say, if it does not succeed within 60 seconds, cancel it?

This can be done in-between routing attempts. However, at this early stage of the network, not all nodes are yet up to the level of reliability that will be required in the future. So until we add a bit more intelligence  and passive routing probing, if an HTLC goes through a faulty node, then it may become suspended. In this case, the node should have already went to chain for the HTLC and cancelled it back. The fact that it hasn't done this yet, indicates that it's faulty.
