### ISSUE TITLE
Database update error after updating to lnd v0.5-beta

### ISSUE THREAD

**Issue by peername** [lightningnetwork/lnd#1968]
As a continue of #1874

I am still trying to update my database to v6.

1. Commit (lnd v0.5-beta) 14bc024 is starting the process but it takes too long. 48 hours passed and still nothing. Is it worth to wait?

2. Latest commit f430509 is giving me this error:

2018-09-23 20:20:34.321 [INF] LTND: Version 0.5.0-beta commit=f4305097e1638f6f8958dfa9eec941d8bf80246e
2018-09-23 20:20:34.321 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-09-23 20:20:34.321 [INF] CHDB: Checking for schema update: latest_version=6, db_version=5
2018-09-23 20:20:34.321 [INF] CHDB: Performing database schema migration
2018-09-23 20:20:34.321 [INF] CHDB: Applying migration #6
2018-09-23 20:20:34.321 [INF] CHDB: Migrating database to properly prune edge update index
2018-09-23 20:20:34.329 [INF] CHDB: Constructing set of edge update entries to purge.
2018-09-23 20:20:34.668 [INF] LTND: Shutdown complete
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*leafPageElement).key(...)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/page.go:120
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).keyValue(0xc42021f750, 0x7fee3927a7c0, 0x10, 0x10, 0x7fee3927a7d0, 0x0, 0x2a, 0xc42021f700)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:354 +0x1a3
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).next(0xc42021f750, 0xfa6a0a, 0x9, 0x0, 0x0, 0x0, 0x0, 0xc400000000)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:248 +0xdb
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).Next(0xc42021f750, 0x10, 0x10, 0x7fee3927a7d0, 0x0, 0x0, 0x0)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:75 +0x71
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).ForEach(0xc42007afc0, 0xc42021f828, 0x1, 0x1)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:387 +0xbf
github.com/lightningnetwork/lnd/channeldb.migratePruneEdgeUpdateIndex(0xc4202060e0, 0xfb2f6e, 0x16)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/channeldb/migrations.go:522 +0x35d
github.com/lightningnetwork/lnd/channeldb.(*DB).syncVersions.func1(0xc4202060e0, 0x1113f00, 0xc4202060e0)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:758 +0x14f
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).Update(0xc42045e960, 0xc420439a18, 0x0, 0x0)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:668 +0x90
github.com/lightningnetwork/lnd/channeldb.(*DB).syncVersions(0xc42015b7c0, 0x177dea0, 0x7, 0x7, 0xc42045e960, 0x0)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:750 +0x34f
github.com/lightningnetwork/lnd/channeldb.Open(0xc4200391d0, 0x23, 0x3, 0xc4200391d0, 0x23)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:124 +0x184
main.lndMain(0x0, 0x0)
/home/cloxy/go/src/github.com/lightningnetwork/lnd/lnd.go:168 +0x3fc
main.main()
/home/cloxy/go/src/github.com/lightningnetwork/lnd/lnd.go:455 +0x26

**Comment by peername** [comment]
Related to:
#1924
#1934
#1913
#1907

**Comment by halseth** [comment]
What hardware are you running with?

**Comment by halseth** [comment]
@peername There shouldn't be any migration related changes between the two commits you listed. Are you sure they are behaving differently? 

It does look like you have experienced a DB corruption, but with the hardware you are running that is not very common. Best would be to close out channels and start with a clean DB, but I'm curious why the two commits behave differently...

**Comment by peername** [comment]
Our database is over RAID 1 array. It is not possible our database to be corrupted on hardware level.

**Comment by Roasbeef** [comment]
By run I mean run to completion. The migration itself can be seen as being optional in a sense, as lnd will still operate without the migration applied, but it'll essentially spam peers with stale updates, and you won't allow you to reclaim the wasted disk space.

**Comment by Roasbeef** [comment]
Does this commit allow the migration to execute properly? https://github.com/lightningnetwork/lnd/commit/034198ffb70140390310dd4d21a1f6da1b4a0fab#diff-99f3013528876f55a0e46ff7014e8a19

**Comment by peername** [comment]
Can you please help me to downgrade my installation to that commit? I don't know how. I am updating and compiling to the latest version by the official instructions.

**Comment by halseth** [comment]
@peername Yes, `git checkout 034198f`!

**Comment by peername** [comment]
I tried commit 034198f , but the result is the same.

**Comment by peername** [comment]
Yes, it was exactly the same error. We closed all the channels and started over with a fresh installation. Can't show the logs.
