### ISSUE TITLE
Please sign current release key with previous release key

### ISSUE THREAD

**Issue by jonathancross** [lightningnetwork/lnd#1977]
### Background

I am trying to verify the key used to sign the current release. The key being used now is [0xCE58F7F8E20FD9A2](https://sks-keyservers.net/pks/lookup?op=vindex&search=0xCE58F7F8E20FD9A2) which has no connection to the PGP web of trust strong set (no signatures at all actually).  The old key used by @Roasbeef was [0x9CC5B105D03521A2](https://sks-keyservers.net/pks/lookup?op=vindex&search=0x9CC5B105D03521A2) which had signatures from myself and Peter Todd (both part of the PGP strong set).

### Expected behaviour

Users should be able to establish a PGP WOT path to the current release key.

### Actual behaviour

Users must try and establish some notion of the trustworthiness of this key through Keybase, it is not possible through PGP signatures.

### Suggested fixes

* One easy way to fix this would be to sign the new key with the old key and vice versa.
* Meeting PGP users in person and exchanging key signatures would also help.

**Comment by Roasbeef** [comment]
The prior release key expired before the release was cut. I was traveling at the time it expired, and unfortunately was unable to properly sign the old key with the new key. All my major online identities have attested to this key either transitively or explicitly. I'll be meeting up with a group of developers early next month, and can have them sign the key to attest to it themselves.

**Comment by jonathancross** [comment]
> The prior release key expired before the release was cut.

You probably know this, but you can always [renew keys](https://unix.stackexchange.com/questions/177291/how-to-renew-an-expired-keypair-with-gpg#177310) if needed.

> I'll be meeting up with a group of developers early next month, and can have them sign the key to attest to it themselves.

Good to hear, thanks.
