### ISSUE TITLE
tls.cert authentication handshake failed: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by vwoo** [lightningnetwork/lnd#1980]
### Background

I'm trying to create a new lnd mainnet node with the recent v0.5-beta stable release from https://github.com/lightningnetwork/lnd/releases. During the wallet creation process, I get an error:

```
$ /Users/vwoo/lnd/lncli --lnddir=/Users/vwoo/lnd create
Input wallet password: 
Confirm wallet password: 

Do you have an existing cipher seed mnemonic you want to use? (Enter y/n): n

Your cipher seed can optionally be encrypted.
Input your passphrase if you wish to encrypt it (or press enter to proceed without a cipher seed passphrase): 
Confirm cipher seed passphrase: 

Generating fresh cipher seed...

[lncli] unable to generate seed: rpc error: code = Internal desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"vincent.local\")"
```
It seems to not like the hostname vincent.local. I think that the .local tld is a default of macOS for their bonjour service (https://en.wikipedia.org/wiki/.local).

Can confirm it is in the newly generated tls.cert (with identifying ip addresses removed):

```
$ openssl x509 -noout -text -in tls.cert | grep DNS:
DNS:vincent.local, DNS:localhost, DNS:unix, DNS:unixpacket, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:FE80:0:0:0:0:0:0:1, IP Address:192.168.1.77, IP Address:192.168.1.78, IP Address:<ipv6 address>, IP Address:<ipv6 address>, IP Address:<ipv6 address>, IP Address:10.8.0.100, IP Address:<ipv4 address>
```

The funny thing is I have a testnet lnd node running on the same machine without this problem. It has been running for several months updating to the latest git commit every week or so.

### Your environment

* lnd version 0.5.0-beta commit=5747e8971ca6cd2bf432ce09d3c5fc7aad93a8e2 (from lnd-darwin-amd64-v0.5-beta.tar.gz)
* macOS Mojave 10.14

### Steps to reproduce

```
$ /Users/vwoo/lnd/lnd --lnddir=/Users/vwoo/lnd
$ /Users/vwoo/lnd/lncli --lnddir=/Users/vwoo/lnd create
```

### Expected behaviour

Wallet created and unlocked, seed words displayed etc.

### Actual behaviour

lncli exits with error message

**Comment by Roasbeef** [comment]
Make sure the key and cert (if you made a custom one) are in line. Also make sure it's grabbing the correct cert if you have multiple `lnd` instances running locally.

**Comment by vwoo** [comment]
Thanks Roasbeef. It looks like I needed to add a --rpcserver argument to lncli to tell it to use the correct port.
