### ISSUE TITLE
lnd got stuck in weird state and crashed

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#1989]
lnd got confused about my wallet balance and showed it as zero even though it should
be close to 200000000 (minus a small amount for a pair of opened channels):

lnd-linux-amd64-v0.5-beta/lncli --chain=litecoin --rpcserver=127.0.0.1:10010 walletbalance
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}

and when i tried doing listchaintxns it crashed:

lnd-linux-amd64-v0.5-beta/lncli --chain=litecoin --rpcserver=127.0.0.1:10010 listchaintxns
[lncli] rpc error: code = Unavailable desc = transport is closing

Sep 28 12:17:16 X lnd[27982]: 2018-09-28 12:17:16.710 [INF] CRTR: Pruning channel graph using block c792680c48d4d87ba8bc6381aa2b8b80539c6c937078fdbd6f372457a3b50943 (height=1499696)
Sep 28 12:17:16 X lnd[27982]: 2018-09-28 12:17:16.718 [INF] NTFN: New block: height=1499696, sha=c792680c48d4d87ba8bc6381aa2b8b80539c6c937078fdbd6f372457a3b50943
Sep 28 12:17:16 X lnd[27982]: 2018-09-28 12:17:16.718 [INF] UTXN: Attempting to graduate height=1499696: num_kids=0, num_babies=0
Sep 28 12:17:16 X lnd[27982]: 2018-09-28 12:17:16.788 [INF] CRTR: Block c792680c48d4d87ba8bc6381aa2b8b80539c6c937078fdbd6f372457a3b50943 (height=1499696) closed 0 channels
Sep 28 12:21:14 X lnd[27982]: 2018-09-28 12:21:14.863 [INF] CRTR: Pruning channel graph using block 6e46626753a09952ab0f80470ac4f255e44c514e79b712b989dc5018516d6182 (height=1499697)
Sep 28 12:21:14 X lnd[27982]: 2018-09-28 12:21:14.871 [INF] NTFN: New block: height=1499697, sha=6e46626753a09952ab0f80470ac4f255e44c514e79b712b989dc5018516d6182
Sep 28 12:21:14 X lnd[27982]: 2018-09-28 12:21:14.871 [INF] UTXN: Attempting to graduate height=1499697: num_kids=0, num_babies=0
Sep 28 12:21:14 X lnd[27982]: 2018-09-28 12:21:14.909 [INF] CRTR: Block 6e46626753a09952ab0f80470ac4f255e44c514e79b712b989dc5018516d6182 (height=1499697) closed 0 channels
Sep 28 12:22:05 X lnd[27982]: 2018-09-28 12:22:05.057 [INF] CRTR: Pruning channel graph using block 98cd10804c85f11ebb0a7873b065657dcdcc84294d8580a088988bd3f7bb32aa (height=1499698)
Sep 28 12:22:05 X lnd[27982]: 2018-09-28 12:22:05.060 [INF] NTFN: New block: height=1499698, sha=98cd10804c85f11ebb0a7873b065657dcdcc84294d8580a088988bd3f7bb32aa
Sep 28 12:22:05 X lnd[27982]: 2018-09-28 12:22:05.061 [INF] UTXN: Attempting to graduate height=1499698: num_kids=0, num_babies=0
Sep 28 12:22:05 X lnd[27982]: 2018-09-28 12:22:05.216 [INF] CRTR: Block 98cd10804c85f11ebb0a7873b065657dcdcc84294d8580a088988bd3f7bb32aa (height=1499698) closed 0 channels
Sep 28 12:22:42 X lnd[27982]: 2018-09-28 12:22:42.274 [INF] CRTR: Pruning channel graph using block 0a1992919620c32998611dcf4d36d052686bf58635d35875b20a245ceb1e38d4 (height=1499699)
Sep 28 12:22:42 X lnd[27982]: 2018-09-28 12:22:42.279 [INF] NTFN: New block: height=1499699, sha=0a1992919620c32998611dcf4d36d052686bf58635d35875b20a245ceb1e38d4
Sep 28 12:22:42 X lnd[27982]: 2018-09-28 12:22:42.279 [INF] UTXN: Attempting to graduate height=1499699: num_kids=0, num_babies=0
Sep 28 12:22:42 X lnd[27982]: 2018-09-28 12:22:42.343 [INF] CRTR: Block 0a1992919620c32998611dcf4d36d052686bf58635d35875b20a245ceb1e38d4 (height=1499699) closed 0 channels
Sep 28 12:24:26 X lnd[27982]: 2018-09-28 12:24:26.745 [INF] CRTR: Pruning channel graph using block 2ee34fa2fac012bc614136b21df40d743af93d4a7d5468e46071599bf487f1d0 (height=1499700)
Sep 28 12:24:26 X lnd[27982]: 2018-09-28 12:24:26.749 [INF] NTFN: New block: height=1499700, sha=2ee34fa2fac012bc614136b21df40d743af93d4a7d5468e46071599bf487f1d0
Sep 28 12:24:26 X lnd[27982]: 2018-09-28 12:24:26.749 [INF] UTXN: Attempting to graduate height=1499700: num_kids=0, num_babies=0
Sep 28 12:24:26 X lnd[27982]: 2018-09-28 12:24:26.801 [INF] CRTR: Block 2ee34fa2fac012bc614136b21df40d743af93d4a7d5468e46071599bf487f1d0 (height=1499700) closed 0 channels
Sep 28 12:28:23 X lnd[27982]: 2018-09-28 12:28:23.644 [INF] DISC: Broadcasting batch of 1 new announcements
Sep 28 12:28:50 X lnd[27982]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 28 12:28:50 X lnd[27982]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xceb18d]
Sep 28 12:28:50 X lnd[27982]: goroutine 12292203 [running]:
Sep 28 12:28:50 X lnd[27982]: main.(*rpcServer).GetTransactions(0xc00094bad0, 0x1204760, 0xc001154f00, 0x1a24318, 0xc00094bad0, 0xc0005cade0, 0xc0002798f0)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x20d
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0x1204760, 0xc001154f00, 0xe8f6a0, 0x1a24318, 0x1, 0x1, 0x0, 0x0)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x89
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1204760, 0xc001154f00, 0xe8f6a0, 0x1a24318, 0xc0005cadc0, 0xc0005cade0, 0xc0008feb50, 0x40c478, 0x50, 0xf32b80)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x153
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0xf8aa60, 0xc00094bad0, 0x1204760, 0xc001154f00, 0xc000cf73b0, 0xc0009c46c0, 0x0, 0x0, 0xc000f78860, 0x10)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x158
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000432000, 0x1209e40, 0xc00115a180, 0xc0002ee300, 0xc00094bbf0, 0x19e2130, 0xc001154f90, 0x0, 0x0)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x8ec
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000432000, 0x1209e40, 0xc00115a180, 0xc0002ee300, 0xc001154f90)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1308
Sep 28 12:28:50 X lnd[27982]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00045b1e0, 0xc000432000, 0x1209e40, 0xc00115a180, 0xc0002ee300)
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f
Sep 28 12:28:50 X lnd[27982]: created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Sep 28 12:28:50 X lnd[27982]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0xa1
Sep 28 12:28:50 X systemd[1]: lnd-litecoin.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

after restart of lnd, listchaintxns works as it should and walletbalance reports the correct amounts:

lnd-linux-amd64-v0.5-beta/lncli --chain=litecoin --rpcserver=127.0.0.1:10010 walletbalance
{
    "total_balance": "197469450",
    "confirmed_balance": "0",
    "unconfirmed_balance": "197469450"
}

**Comment by Roasbeef** [comment]
Fixed by #1916
