### ISSUE TITLE
lncli payinvoice: wrong amount in confirmation dialog

### ISSUE THREAD

**Issue by piezzo** [lightningnetwork/lnd#1994]
### Background

When using lncli payinvoice with a custom amount (i.e. --amt ), the amount shown in the confirmation dialog is not the amount that is passed using --amt, which is sent after confirmation. (see screenshot)

### Your environment

* version of `lnd` 
0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0
* which operating system (`uname -a` on *Nix) 
Linux lightning 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend 
bitcoind-0.16.3 (arm)

* any other relevant environment details

### Steps to reproduce

Use --amt <anynumber> to pay an invoice (in this case the amount in the invoice was zero)

### Expected behaviour

amount confirmed should be the amount being sent.

### Actual behaviour

Amount confirmed appears to be the amount encoded within the payment request (here: 0)
<img width="1172" alt="bildschirmfoto 2018-09-28 um 18 29 58" src="https://user-images.githubusercontent.com/7838487/46222035-70606b80-c34f-11e8-8e11-cddaa865c567.png">

**Comment by Roasbeef** [comment]
This was fixed by #1885.
