### ISSUE TITLE
Compact filters are downloaded on every restart for an opened channel

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#1997]
### Background
I am having an LND node with one channel opened and I saw that on every restart of the node the compact filters are downloaded from the block that contains the funding transaction.
After several dozens of blocks this become a pain, especially in environment with low resources like mobile.
In LND there is a component called ChainArbitrator that creates a ChainWatcher for every active channel in order to be notified with on chain events related to this channel.
As part of its duties, the ChainWatcher registers for a spend notification by using the notifier interface (notifier.RegisterSpendNtfn) to get a notification when the funding transaction output is spent.
When the notifier is configured to be neutrino, it just triggers a rescan starting from the block of the funding transaction, which is implemented by downloading all the compact filters. This seems a correct behavior for the first time but shouldn't be necessary for next times we create a ChainWatcher for this channel. I expect it will start the rescan from the point it stopped.
I have noticed that neutrino has the option to save the filters it downloads, I tried that and it solves this issue but I don't think this is the right solution as we only need to know the "last known scanned" filter for every channel.

### Your environment
* LND master
* macOS
* btcd version 0.12.0-beta

### Steps to reproduce
1. Run a simple node configured to work with neutrino and open a channel
2. Wait for some blocks to be mined or in simnet just generate 1000 blocks to see the issue clearly.
3. On every restart the filters are downloaded since the funding transaction block even though they were downloaded and the utxo was validated on a previous run.

### Expected behaviour
I expect that for every channel the rescan will start from the last point it stopped.

### Actual behaviour
The rescan starts from the block contains the funding transaction regardless of where it stopped on a previous run.

**Comment by Roasbeef** [comment]
See #1788 and the cache in general.

**Comment by Roasbeef** [comment]
Target is 0.5.1, check out the milestone we're currently using to track the release: https://github.com/lightningnetwork/lnd/milestone/8
