### ISSUE TITLE
REST API newaddress is not generating the correct address per address type

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#1999]
Background
REST API newaddress is not generating the correct address per address type while sending the address type as query parameter '?type={address_type}'

Your environment
lnd v0.5.0
Windows 10
bitcoind 0.16.2
WebUI: Angular 6, Node 8.12.0, TypeScript 2.7.2

Steps to reproduce
NA

Expected behaviour
REST API should generate the correct address as per address type passed in query param.

Actual behaviour
It is only generating the address with 'np2wkh' address type.
![addresstypequery](https://user-images.githubusercontent.com/23240721/46266727-4e0d5000-c4ff-11e8-884d-d11594bf3935.jpg)

**Comment by wpaulino** [comment]
You'll need to update `lnd` to the latest commit on the master branch in order for the fix to apply.

**Comment by ShahanaFarooqui** [comment]
When are you planning to update the binaries?

**Comment by wpaulino** [comment]
The next release can be tracked at https://github.com/lightningnetwork/lnd/milestone/8. There are still a couple of items left, so once everything's wrapped up you can expect a release shortly after.
