### ISSUE TITLE
Macaroon for transactional apps

### ISSUE THREAD

**Issue by cryptagoras** [lightningnetwork/lnd#2003]
It would be great if there was a constrained macaroon for (potentially non-trusted) apps that only transact (create/pay invoice/address), read basic info maybe but not deal with channel management or other advanced or dangerous stuff.

At the moment the only option is using the admin macaroon.

I could give it a go and send a PR if you want, the only(/first :P) thing I need help is naming the macaroon, maybe `transactional.macroon`.

**Comment by wpaulino** [comment]
Ideally `lnd` only creates macaroons that are considered useful for the majority of users. If there's demand for such a macaroon, I think we'd open to including something like so.

Keep in mind however that, in the future, you'll be able to create your own custom macaroons with the permissions you desire. #1160 is a nice starting point that achieves this. At the moment it hasn't received much review as it's not as big of a priority, but it will be later down the road.

**Comment by Roasbeef** [comment]
Closing as #1160 (and the follow ups) exist.
