### ISSUE TITLE
Send out updated announcements periodically

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#2005]
Some nodes will attempt to prune "zombie" nodes and channels from the channel graph. This can happen if a new ~~`ChannelUpdate` or~~ `NodeAnnouncement`  with an updated timestamp is sent after a time on the order of a few weeks.

To avoid getting pruned, we should periodically check the timestamp of our last sent `NodeAnnouncement` ~~and `ChannelUpdate`~~, and broadcast updated ones if the timestamp is a few weeks in the past.

**Comment by Roasbeef** [comment]
We already to this: https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L1308

**Comment by halseth** [comment]
Not for `NodeAnnouncements`.

**Comment by gustavonalle** [comment]
I am using lncli version 0.8.0-beta commit=v0.8.0-beta-163-gb222b6e6250be0adea1d880800fde60f6b8695d1. and my ```lnd``` IP address changed, I tried to open a channel, change alias, ip, and still the node announcement is not sent... What incantation should I perform to make it update?

**Comment by halseth** [comment]
@gustavonalle It will be updated after 24hrs.
