### ISSUE TITLE
unable to start server: Couldn't get cfheader

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2013]
### Background
LND is running on iOS. In one of the test device (an iPad), LND is unable to start up and crashes repeatedly because it is unable to get a "cfheader". This appears to be neutrino related. This error has occurred before, and after a few failed restarts, one will succeed eventually and there were no crashes after that. This time however i am unable to start up the LND node on that device. Two other devices are working fine peering with each other, sending payments etc. So, it seems to me btcd is ok and the chain is not corrupted (which has happened before and i'll create another issue explaining that ). 

### Your environment

* version of `lnd` - 0.5
* which operating system (`uname -a` on *Nix) --- iOS
* version of `btcd`, `bitcoind`, or other backend  -- btcd 0.12..0-beta 

### Steps to reproduce

Nothing special. Build ios app for device, and install it from xcode. Then make changes (bug fixes) and the number of stops and restarts causes the device to go out of sync with something /somewhere so that it loses some headers. The "stops" i am referring to are not necessarily controlled shutdown, rather abrupt termination by dismissing app. 

### Expected behaviour

Device with LND should go on working and behave like other devices , connected to the same btcd

### Actual behaviour

Crashes unable to find CFHeader as in log ---> https://0bin.net/paste/w1WZ8HU2djgtaqqC#aNFktvxjh9fWGG7kM+UZOAZBYL64JYVwzWATCovdtk-

**Comment by Roasbeef** [comment]
Closing this here as it's actually a neutrino issue (which has a distinct repo). This will be solved by https://github.com/lightninglabs/neutrino/pull/96

**Comment by offerm** [comment]
@Roasbeef what is the status of this?

I just switch my LND-BTCD to use neutrino and found the same problem.

Is there a way around it?

Why is this issue closed?

**Comment by Roasbeef** [comment]
You can't switch over like that atm. In that case the wallet thinks everything is synced, and goes to get a header that it should have. However, since you started with btcd, then you actually don't have those headers on disk.
