### ISSUE TITLE
send coins to invoice on same node (self)

### ISSUE THREAD

**Issue by aggroLINUS** [lightningnetwork/lnd#2020]
### Background

imagine running a custodial wallet service on 1 lnd.
one user wants to send a payment to another user on the same service.
essentially it is a LN payment within the node.

at the moment a payent to myself fails this way:

{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}

thanks for your hard work guys!!
i also try my best to bring your work to the people!!

**Comment by Roasbeef** [comment]
This isn't supported via the vanilla interface atm. You can use `sendtoroute` to achieve this however. It seems that in your use case, you can just store balances _outside_ of lnd, and simply update the external database for payments within the "same service".
