### ISSUE TITLE
queryroutes fee output is confusing

### ISSUE THREAD

**Issue by tobiasl1** [lightningnetwork/lnd#2025]
### Background

lncli queryroutes shows fee for the wrong channel.
For my test i set the basefee to the following values:
A->B is 0 sat, B->C 10 sat, C->D 20 sat, but queryroutes shows the 10 sat fee for A->B, 20 for B->C and 0 for C->D:

```
bash-4.4# lncli --network=simnet queryroutes 0295d50da9904a063b4f92251eb7f828cbc75a3410d210fd2853a47f8e318456ea 100
{
    "routes": [
        {
            "total_time_lock": 724,
            "total_fees": "30",
            "total_amt": "130",
            "hops": [
                {
                    "chan_id": "440904162803712",
                    "chan_capacity": "977800",
                    "amt_to_forward": "120",
                    "fee": "10",
                    "expiry": 580,
                    "amt_to_forward_msat": "120000",
                    "fee_msat": "10000"
                },
                {
                    "chan_id": "450799767453696",
                    "chan_capacity": "1000000",
                    "amt_to_forward": "100",
                    "fee": "20",
                    "expiry": 436,
                    "amt_to_forward_msat": "100000",
                    "fee_msat": "20000"
                },
                {
                    "chan_id": "460695372103680",
                    "chan_capacity": "1000000",
                    "amt_to_forward": "100",
                    "fee": "0",
                    "expiry": 436,
                    "amt_to_forward_msat": "100000",
                    "fee_msat": "0"
                }
            ],
            "total_fees_msat": "30000",
            "total_amt_msat": "130000"
        }
    ]
}
```

Is there a specific reason why it's displayed like that or is it a bug?
I think that output is very confusing, because it let's you think you're paying fees to yourself and that the last channel has no fees.
Also the "expiry" and "amt_to_forward" values seem to be shifted in the same way by 1 channel.

### Your environment

version: 0.5.0-beta commit=e9809c715ecba644ee86b4324822235f862dfccb
simnet with 4 nodes (docker)

### Steps to reproduce

Set up 4 nodes with channels A-B,B-C,C-D and set the fee for each channel to a different value with lncli updatechanpolicy.
Check the fees with lncli queryroutes from node A to D.

### Expected behaviour

The fee value should match witch the correct channel id.

### Actual behaviour

The values are shifted by 1 channel.

**Comment by wpaulino** [comment]
The `fee` field in its current interpretation shows the fee that will be paid for the next hop of the _current_ hop. So in this case, the first hop will pay a fee of 10 satoshis for the second hop, which matches with the policies that you've set on each channel. I do agree this is perhaps unintuitive and could use a better name to clarify its meaning.

**Comment by joostjager** [comment]
The first element in the `hops` list gives you:
- The channel id of the channel between the source node and the node that is the first hop. This is the incoming channel of the first hop node.
- The fee that will be withheld by that hop for forwarding the payment. This based on the outgoing channel policy of the first hop node.

The `queryroutes` output is as expected, but it is indeed confusing because properties of both incoming and outgoing connections of a node are mixed in the same (array) element.

**Comment by Roasbeef** [comment]
The fee there is the fee we pay to the node for _that_ hop. So the fees aren't really wrong, but may not be displayed how you'd initially expect them to be. As A you never pay a fee to the first hop, but you pay them for transit to the second hop. By hop here I mean node rather than edge.
