### ISSUE TITLE
Autopilot not working

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#2040]
### Background

Hi,
my autopilot is not working as expected
I used the default autopilot options in lnd.conf 
First autopilot has opened 3 channels, then I put new BTC onchain on my node in order to let autopilot  open more channels but this doesn't happen.

### Your environment

* lnd 0.5
* linux 4.17.14
* bitcoind 0.17.0

### Steps to reproduce

Once autopilot opens 3 channels, send more BTC onchain and wait for more channels to be opened.

### Expected behaviour

Channels should automatically open respecting lnd.conf parameters

### Actual behaviour

Channels do not open

**Comment by danbadjar** [comment]
Sorry. Stop/start lnd and the autopilot is now working correctly

**Comment by wpaulino** [comment]
Do you have any debug logs?

The default settings have a fund allocation of `0.6`. This means that autopilot will only use 60% of your total funds (on-chain and off-chain) to create channels. Once it reaches that threshold, no further channels will be opened. If you did indeed send more coins to the node's wallet, that should've been recognized by the autopilot agent.

**Comment by danbadjar** [comment]
Thank you for the response.
I had sufficient funds but maybe I didn't wait enought. I just stopped and started lnd and now everything is working as expected
