### ISSUE TITLE
Very High CPU usage for lnd and bitcoind

### ISSUE THREAD

**Issue by BobleChinois** [lightningnetwork/lnd#2041]
### Background

I just started a brand new LND node with tor routing (see #2034).

As adviced in #2035 , I upgraded lnd to last commit this morning.

It appears that as soon as I start lnd, it eats instantly anywhere from 20% up to 70% of my CPU, and that bitcoind CPU usage also goes through the roof (from 1 or 2% to 15-20%).

Before that I used to run LND 0.5.0-beta without tor and with low CPU usage.

Lnd is fully synced with bitcoind. As it is a new node, it hasn't any open or pending channel yet, and autopilot is off.

I had a look at the logs, didn't see anything unusual as far as I can tell, but I can provide logs filtered by subsystem if necessary, just tell me what to look at.

### Your environment

* lnd version 0.5.0-beta commit=25145acc46cc5d18e4e348eed097300b1391d2a7
* Linux Celeri 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.3

### Steps to reproduce

Start LND.

### Expected behaviour

CPU usage should be constant and low.

### Actual behaviour

CPU usage instantly becomes very intensive for lnd and bitcoind.

**Comment by wpaulino** [comment]
Was It syncing the channel graph? At the moment, that should be the only known thing within `lnd` that would cause high CPU usage. If it's not that, you can set up profiling on your node to get a CPU profile by doing the following:

1. Restart `lnd` with the `--profile=PORT` flag.
2. This step will require go to be installed. Once `lnd` has started, open another shell and run `go tool pprof http://localhost:PORT/debug/pprof/profile`.
3. After running the command from step 2, you'll need to wait for the following prompt:
```
Entering interactive mode (type "help" for commands, "o" for options)
(pprof)
```
At this point, you can run `web`, which will generate an SVG with a CPU profile graph and post it here.

**Comment by BobleChinois** [comment]
Hi, sorry I have been afk these days. I started lnd again and let it run for some time before taking the CPU profile, it appears that CPU usage becomes normal after a while. 

I guess you were right, it was synching the channel graph. Might be because I run it on old hardware too.

It seemed to me that start up was less CPU intensive with previous release though.  

Anyway I'm closing it for the moment, I'll come back with a CPU profile in case the problem shows up  again. 

Thanks !
