### ISSUE TITLE
Feature request - which hop is offline when paying 

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2043]
### Background

HTLC payment indicated it was successful. However it failed because the recipient was offline. In other words, 'A','B','C' are three LND nodes. 'A' pays 'C' via 'B' . 'A'  finds a route even if 'C' is offline, and payment is successful because the first hop succeeds. Obviously when 'B' forwards payment to 'C' it fails (log below). 

'A' never finds out about the failure.  

It would be great if a rest endpoint is available for 'A' to know of the failure. After all the error messages received by 'B' (below) provide the reason.

routes {
  total_time_lock: 11813
  total_fees: 1
  total_amt: 91801
  hops {
    chan_id: 12669672486928384
    chan_capacity: 14962301
    amt_to_forward: 91800
    fee: 1
    expiry: 11669
    amt_to_forward_msat: 91800000
    fee_msat: 1091
  }
  hops {
    chan_id: 12357411184640000
    chan_capacity: 15416693
    amt_to_forward: 91800
    expiry: 11669
    amt_to_forward_msat: 91800000
  }
  total_fees_msat: 1091
  total_amt_msat: 91801091
}

Found routes  [Lnrpc_Route:
total_time_lock: 11813
total_fees: 1
total_amt: 91801
hops {
  chan_id: 12669672486928384
  chan_capacity: 14962301
  amt_to_forward: 91800
  fee: 1
  expiry: 11669
  amt_to_forward_msat: 91800000
  fee_msat: 1091
}
hops {
  chan_id: 12357411184640000
  chan_capacity: 15416693
  amt_to_forward: 91800
  expiry: 11669
  amt_to_forward_msat: 91800000
}
total_fees_msat: 1091
total_amt_msat: 91801091
]
**2018-10-12 00:59:23.733 [ERR] CMGR: Can't accept connection: unable to accept connection from [2607:fb90:a42a:2ab7:xxxx:xxxx:xxxx:dee6]:60540: chacha20poly1305: message authentication failed
2018-10-12 00:59:25.106 [ERR] CRTR: Attempt to send payment fad5b53864296c74ac85415bc28f7ddd3e927edb1ccd178e66dc5cfeb1c57d35 failed: UnknownNextPeer
2018-10-12 00:59:27.306 [ERR] CMGR: Can't accept connection: unable to accept connection from [2607:fb90:a42a:2ab7:9dc4:e7e3:7a48:dee6]:60544: chacha20poly1305: message authentication failed
2018-10-12 00:59:28.602 [INF] HSWC: Sent 0 satoshis and received 0 satoshis in the last 10 seconds (0.200000 tx/sec)**

### Your environment

* version of `lnd` --- 0.5beta
* which operating system (`uname -a` on *Nix) - iOS
* version of `btcd`, `bitcoind`, or other backend - btcd

### Steps to reproduce

Set up three nodes. Send payment (payee) to payer. Let payer be offline. You will see above errors.

### Expected behaviour

Behavior is as expected (as programmed). Better behavior would be pass the error up the htlc chain so that 'A' learns of the error 

### Actual behaviour

Only 'B' learns of the error - 'A' is clueless and marks invoice as settled.

**Comment by weaklysubjective** [comment]
Correction : "Set up three nodes. Send payment (payee) to payer. Let payer be offline. You will see above errors."  Send payment (payer) to payee. Let payee be offline. You will see above errors.

**Comment by wpaulino** [comment]
This will fixed by #1662.

**Comment by weaklysubjective** [comment]
So #1662 refers to using "SendToRoute" supplying a pubkey. Will that work for SendPaymentSync ?

**Comment by wpaulino** [comment]
Yes, they all use the same code path.

**Comment by weaklysubjective** [comment]
Gotcha.. so both will now accept a pubkey of the payer ?

**Comment by wpaulino** [comment]
#1662 initially included those changes, but it was broken up to allow add the better payment failure reporting. The other feature is being tracked in https://github.com/lightningnetwork/lnd/pull/1944.

**Comment by weaklysubjective** [comment]
sorry to keep on this ....one last ..am i supposed to have had this feature (#1662 and #1944) in 0.5 beta ?

**Comment by wpaulino** [comment]
They have not been merged to the master branch yet, you'll need to wait until then. You'll then have to wait for the next release or just update yourself manually and build from source.

**Comment by weaklysubjective** [comment]
Ok thanks ..may be i'll give it a shot for the next test cycle of my app

**Comment by Roasbeef** [comment]
The latest responses in the router sub-server now return all failure information.
