### ISSUE TITLE
Return raw announcement signatures in SubscribeChannelGraph

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2046]
### Background

When receiving the channel graph announcements, I'd like to receive the original signatures from the announcing nodes

This helps with preserving a record that can be re-authenticated in the case of data corruption

### Actual behaviour

Currently signatures are not included in the graph feed, putting a requirement on trusting the node's original signature check

**Comment by Bluetegu** [comment]
I'd like to try and address this one

**Comment by Bluetegu** [comment]
Its more complex than I originally thought. Please see below my clarification questions.

SubscribeChannelGraph streams node updates, channel edge policy updates, and close channel updates.

Some of updates are generated by incoming gossip messages. Here it seems straight forward; add to rpc.proto the raw signatures, as well as all the other fields this signature covers that are not exported via the current SubscribeChannelGraph interface and its done. This would require adding color, timestamp and opaque data bytes, and signature, to NodeUpdate. Similarly adding several fields to ChannelEdgeUpdate, including flags, opaque data, chain_hash(?) and signature. This is possible, but somehow what is created looks like a hack; i.e. NodeUpdate and LIghtningNode (returned in ChannelGraph by the DescribeGraph service) looks very similar, but uses different addresses formats, etc. It raises the question whether DescribeGraph and SubscribeChannelGraph shouldn't be harmonized, i.e. that they deliver the same LightningNode with all the fields and the signature required for the consumer to re-verify. This would render it to not be backward compatible, but it may be the right way to go.

In general its not clear to me whether adding raw signatures to SubscribeChannelGraph without adding signatures to DescribeGraph is useful. If the intention is to have all the topology and reverify it, DescribeGraph should include the signatures too.

Channel close updates are sent when lnd figures out the channel was closed via a chain update, so there is no signature here. Is that ok?

Thanks!

**Comment by halseth** [comment]
Sounds like a good approach to reuse proto definitions for certain APIs! :)

**Comment by saubyk** [comment]
Closing this issue, as no appetite for this change. Can be reopened if there is a need in the future
