### ISSUE TITLE
Status of LND / RPC - whether running/fully syncd or not

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2047]
### Background

In the lifecycle of iOS apps they can be running in the foreground, running in the background, or dismissed and terminated.  When in foreground or backgrounded and still running (not suspended), it would be nice to know if LND and RPC are still in good health and running.
I have set up timers running every 30 seconds to getinfo and to connect peers to notify if RPC and LND respectively are working well. Obviously it is expensive to run timers and to run them at frequent intervals makes the app a resource hog etc. 

Ideally we would like to run one timer to learn of the LND status - whether syncd, running , not started yet etc.. Thus a rest endpoint would be a great add

### Your environment

* version of `lnd` - 0.5beta
* which operating system (`uname -a` on *Nix) - iOS
* version of `btcd`, `bitcoind`, or other backend - btcd

### Expected behaviour

A way to know if LND has fully syncd and started up 

### Actual behaviour

No such rest endpoint

**Comment by Roasbeef** [comment]
If you can hit the RPC server, then you know if `lnd` is active or not. The best call to hit is `getinfo`.

**Comment by weaklysubjective** [comment]
Hi @Roasbeef , even though getinfo works and returns results even indicating whether or not syncd with the blockchain, from my experience, it doesn't seem to be enough to know if LND is actually listening on 9735. When using neutrino there is a delay between when RPC is ready and when LND is listening on 9735. Many trials show the same result, that RPC is ahead of LND which appears to be catching up with neutrino filters and best block estimation. To know if LND is ready i do use Connect 2 peer. It would be nice if Start LND could push status available to end user apps via a rest endpoint.

**Comment by Roasbeef** [comment]
Typically the "main" RPC is the last to start up. Things like `ConnectToPeer` won't actually work before the server has started up. While syncing we start up RPCs that allow you to get things like getinfo and other status reports. You won't be able to do things like connect to peers or make channels during this phase however. Once the "synced_to_chain" bool flips to true, then you know that lnd is ready for action.
