### ISSUE TITLE
Listchaintxns

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#2050]
### Background

Describe your issue here.

Odd entry in listchaintxns

        {
            "tx_hash": "c006221d97cea983951be48c0992767c5bff575bcaa9a776def6cf6b95784aad",
            "amount": "0",
            "num_confirmations": 0,
            "block_hash": "",
            "block_height": 0,
            "time_stamp": "1536965928",
            "total_fees": "0",
            "dest_addresses": [
            ]
        }

### Your environment

* version of `lnd`      "version": "0.5.0-beta commit=7fe095c54128b502e20b3482ef73f1b6ba737850"

* which operating system (`uname -a` on *Nix) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend, btcd
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

No logs show that txid
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
Can happen due to second layer HTLCs and the like. We add them to the wallet so it can rebroadcast them, but the wallet doesn't know the inputs and can't spend the outputs itself.
