### ISSUE TITLE
Allow invoices hop hints to be used in queryroutes

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2056]
### Background

Currently queryroutes "Queries the channel router for a potential path to the destination that has sufficient flow for the amount including fees"

But in the case that the destination is one with a private channel hop, hop hints must be inserted into the evaluated graph.

This API currently does not allow insertion of hop hints into the graph, other than through a workaround of querying a path to the hint and then constructing a route from there.

### Expected behaviour

It would be helpful for paying to private channel destinations via sendtoroute or checking if invoices were payable if the API took an invoice or an array of hops to include in its query analysis.

**Comment by Bluetegu** [comment]
I'd like to give this a try.

**Comment by KarolStrzelec** [comment]
hi what do you think about this solution?
https://drive.google.com/file/d/1H0SLt2ntS2yqjJ7lkeisFhyHLIFH070D/view?usp=sharing
