### ISSUE TITLE
Wipe LND , reinstall with old pubkey 

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2057]
### Background

iOS apps can be deleted and reinstalled. LND works as designed when reinstalled , no problem there. However the node pub key changes - and this is expected as well. Is it possible to change LND to supply key pair as a command line argument ? 

A lot is riding on the old key pair(pub/private keys) , such as channels opened, payment made, unsettled invoices and so on. 

I realize this request may be antithetical to crypto and its functioning, but no harm asking :-)

### Your environment

* version of `lnd` - 0.5beta
* which operating system (`uname -a` on *Nix) - iOS
* version of `btcd`, `bitcoind`, or other backend - btcd

### Steps to reproduce

Delete lnd, reinstall. Pubkey changes

**Comment by Roasbeef** [comment]
> Delete lnd, reinstall. Pubkey changes

You need to recover with your existing seed.

**Comment by weaklysubjective** [comment]
Hi Roasbeef - a bit of searching led to this --> https://github.com/bitcoin-core/secp256k1/issues/519#issuecomment-426119574 ... says there "Closing this. People should not use recoverable signatures in basically any application -- their patent story is questionable and they cannot be batch-validated."   

Also saw your comment on slack "People should not use recoverable signatures in basically any application -- their patent story is questionable and they cannot be batch-validated.
not every application requires batch validation

our case certainly doesn’t
and re patents…it’s already in every version of bitcoind actively used"

Per apoelstra  --> "Yes, but only for historical reasons, in the signmessage API which will be replaced by BIP322 or something similar."

Your thoughts ?

**Comment by Roasbeef** [comment]
By seed I mean the mnemonic you receive when creating a wallet.

**Comment by weaklysubjective** [comment]
My fault i didn't communicate this correctly. 
After a bit more digging, it seems

1. Lnd.go generates a cert and key pair for TLS purposes. Seems to me the "seed and mnemonic" applies to the TLS key pair
2.  Whereas my original question/issue relates to the activeChainControl 'idPrivKey' (and the pubkey thereof) To the extent i read the code the pubkey of the idPrivKey becomes the node's pubkey. 
 
Sorry if i didn't communicate this correctly. Perhaps if you could shed some light on the two points above, and whether the node could retain the old pubkey (priv key), that would be great. thanks

**Comment by weaklysubjective** [comment]
Roasbeef i have deleted the latest comment...it didn't make sense to me , i am sure it didn't make sense to you either :-)  May be by reading code i'll hope to inform myself.

**Comment by weaklysubjective** [comment]
Roasbeef , i recall why i stopped using noseedbackup=0 (previously noecnryptwallet). It is because i couldn't find a way to input password in response to the following message 

"2018-10-18 23:38:52.988 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-10-18 23:38:52.988 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-10-18 23:38:52.988 [INF] LTND: **Waiting for wallet encryption password**. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it."

I get the part about seed, mnemonic and password etc...**but is there a way to access the WalletUnlockerService directly ?**. By that i mean access the 'genseed', 'initwallet' etc. without LND waiting on a password entry ? I could see  inputting the password beforehand and then supplying it to 'genseed' and subsequently to 'unlockWallet'.

I can see that LND starts up gRPC proxy on 8080 and RPC server on 10009 (as in log above) ...so i'd think i could run a walletservice client against it . But the result is that those calls are never invoked..wile LND waits on the password.

TIA

**Comment by weaklysubjective** [comment]
Quick update - just after my comment, i tried a couple of things and one was introducing a delay. And it appears to make progress in that i succeeded in generating mnemonic, Yay ! Still however lnd didn't appear to continue from where it was waiting. It may have something else to do with the way i am doing things. Sure to keep you posted.

**Comment by weaklysubjective** [comment]
I am able to confirm WalletUnlock service rocks ! Able to initialize and subsequently unlock wallet. The issue was a race condition LND not started and WalletUnlocking started :-) Not sure the delay would hold , but for now all good. Thanks
