### ISSUE TITLE
Autopilot not working as expected

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#2065]
### Background

Hello,
I am experiencing some issues with autopilot feature.
My settings in lnd.conf are defaults:

autopilot.maxchannels=5
autopilot.allocation=0.6 

My onchain balance is 2193803 satoshis
My LN balance is 1690481 satoshis

So I am expecting that Autopilot will allocate on LN 60% of the total amount of my funds: ~ 2330570 satoshis, but this doesn't happen

I have only 4 open channels

### My environment

lnd 0.5 beta
linux-4.17.14
bitcoind-0.17.0

### Expected behaviour

Autopilot should open at least 1 more channel allocating 60% of my funds on LN

### Actual behaviour
Autopilot doesn't open channels. In my logs I just found:
[INF] ATPL: Node updates received, assessing need for more channels
and nothing more

**Comment by Roasbeef** [comment]
`float(1690481) / 2193803  = 0.7705710129852134`

You've already allocated 77% of the balance.
