### ISSUE TITLE
tor integration missing HashedControlPassword

### ISSUE THREAD

**Issue by zundg** [lightningnetwork/lnd#2070]
When using tor it seems to be best to have tor running on a different machine. lnd seems to support this, as tor related configuration options allow specification of an IP address.

Yet " // Its [lnds] only supported method of authentication is the SAFECOOKIE method."

the safecookie is regenerated with each restart of tor [0].

So when trying to run lnd via tor in such an isolated environment, with each restart of tor one has to manually sync up the cookie or sacrifice isolation. 

[0] https://www.torproject.org/docs/tor-manual.html.en

**Comment by wereHamster** [comment]
There's a PR open to add this feature: #2548

**Comment by guggero** [comment]
Fixed by #4048.
