### ISSUE TITLE
Node HDD crash. Funds lost?

### ISSUE THREAD

**Issue by Smiggel** [lightningnetwork/lnd#2071]
### Background

I had a node running. The HDD, crashed and had to get it replaced. I setup a new node now, and used the seed to restore my wallet. However, the channels were not closed properly at the time of the crash.

How can I get my funds back? It's a small amount (0.003 BTC) but still wonder if it is possible. Money has not returned to the wallet, and the channel is not active for a week now.

### Your environment

* version of `lnd`
0.14.2
* which operating system (`uname -a` on *Nix)
Raspbian
* version of `btcd`, `bitcoind`, or other backend
17.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
> version of lnd
> 0.14.2

That doesn't appear to be a valid version of lnd. 

If you have your seed (from `lncli create`), then you'll be able to obtain your on-chain balance. See this issue for the progress on static channel backup, which will allow you to recover most of the off-chain balance from your existing channels: #175.

**Comment by Smiggel** [comment]
I mean version 0.4.2. Sorry about that. :-)

Will look into the issue. Thanks.
