### ISSUE TITLE
chan_id becomes zero after the channel is closed

### ISSUE THREAD

**Issue by dlaptev** [lightningnetwork/lnd#2072]
### Background

The list of my closed channels (`lncli closedchannels`) contains lots of channels with `chan_id = 0`. The issue is that most of these channels actually had a valid non-zero `chan_id` before they were closed.

For example, a channel with `channel_point = 0eae1043be01bacb5a13e9efb4308bbb3cfbb0ebc27365955d301b232d1a494f:1` previously had `chan_id = 594728038517637121`. It was open for weeks, so it is not related to an unconfirmed funding transaction. It also participated in lots of forwarding events. But after it was closed with `REMOTE_FORCE_CLOSE` (the remote node is c-lightning), its `chan_id` shows as zero.

It is not a huge problem by itself, but makes it harder to parse the output of `lncli fwdinghistory`.

### Your environment

* `lnd version 0.5.0-beta commit=6d759bd8d9f1595f32fba6f901db4dcb78b6613e`
* `Linux 4.4.0-134-generic #160-Ubuntu SMP x86_64 GNU/Linux`
* `Bitcoin Core Daemon version v0.16.3.0-g49e34e288`

### Steps to reproduce

Run `lncli closedchannels`, find a channel with `chan_id = 0`, look for the opening transaction in robtex or some other explorer, find that the channel has a recorded non-zero id.

### Expected behaviour

When a channel is closed, the `chan_id` should be preserved and correctly displayed in `lncli closedchannels`.

### Actual behaviour

`chan_id` becomes zero.

**Comment by Roasbeef** [comment]
If the chan ID is zero, then that means that your local node never actually announced the channel to the greater network. A channel can be closed _before_ it's announced to the network if either node force closes it before it's fully announced. It's likely that there also exists a race where the node force closes _right_ as we're trying to announce the channel. Depending on the order in which we discover these two events, we may end up with a zero channel ID in the database. 

For those channels that have zero chan ID, what is their close trigger?

**Comment by Roasbeef** [comment]
Found the culprit, fixed in #2074. Thanks for this issue report!

**Comment by dlaptev** [comment]
Thanks for a super quick fix!
