### ISSUE TITLE
LN channels do not re-open and wallet does not receive funds back after HDD crash

### ISSUE THREAD

**Issue by Smiggel** [lightningnetwork/lnd#2078]
### Background

Had a working setup using stadicus guide, 7 channels open with autopilot. After a week I had a harddisk crash. I had to replace my harddisk and did a new setup of the node. 
I imported my wallet seed to re-use my old wallet and hoping the channels would open again, or would receive my funds back, as the channels were not closed properly

Setup used the mainnet.

### Your environment

"version": "0.4.2-beta
"operating system": "Raspbian Stretch"
"bitcoind": 17.0
Raspibol setup

### Steps to reproduce

Setup a node on a pi using the Raspibolt guide. Fund the node and setup channels; Remove the harddisk. Format the harddisk and re-setup the node. Import your wallet with the previous received seed.

### Expected behaviour

1. I would expect the funds to return to my wallet, as the node did not close the channels properly, because the harddisk crashed with the information on it. I would expect the channels to close, as they can not used/active anymore.
or
2. I would expect LND to see based on my wallet seed, what channels were open, and restore them.

I would at least like to restore the channels or force close them, but that seems not possible.

### Actual behaviour

The wallet is empty. According to 1ML.com when I lookup my node, it has 10 channels open now. 3 of them are new and the other 7 channels that I had open previously are still open. The channels did not close and remain active, when my side of the channel is gone.

**Comment by Roasbeef** [comment]
> I imported my wallet seed to re-use my old wallet and hoping the channels would open again, or would receive my funds back, as the channels were not closed properly

The seed only contains on-chain keys, and info w.r.t the off-chain keys that we used. It doesn't yet include static channel information. Until that's in place, we recommend ensuring you're using a stable, reliable medium for a disk. This feature will be implemented soon, and can be tracked at #175.

**Comment by Roasbeef** [comment]
> "version": "0.4.2-beta


Also I recommend updating to 0.5, as a _ton_ of bugs (and also generally performance improvements) have landed since then.
