### ISSUE TITLE
sendcoins returns unknown address type for all adrresses on litecoin mainnet

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#2085]
### Background

sendcoins returns unknown address type for all adrresses on litecoin mainnet.

`./lncli --network=mainnet --no-macaroons --rpcserver=localhost:10001 sendcoins --addr=MQjGGyBTtgtha6T9FmCjATFV1AJYvBWkNe --amt=100
[lncli] rpc error: code = Unknown desc = unknown address type`

### Environment

* latest lnd-v0.5-beta for linux-amd64 ( I am using ubuntu 16.04)
* additionaly built latest master lnd (commit - 0e683d895b943e5837dbbdc3724dc0dbd3ef6b12 ) with latest btcd master ( commit - 67e573d211ace594f1366b4ce9d39726c4b19bd0 )

##### Open litecoind mainnet 
`
./litecoind --mainnet --rpcuser=xu --rpcpassword=xu --txindex --zmqpubrawblock=tcp://127.0.0.1:29442 -zmqpubrawtx=tcp://127.0.0.1:29444 --daemon
`
##### Open lnd 

`lnd --noseedbackup --rpclisten=localhost:10001 --listen=localhost:10011 --restlisten=8001 --datadir=data --logdir=logs --nobootstrap --no-macaroons --litecoin.active --litecoin.mainnet --litecoin.node=litecoind --litecoind.rpcuser=xu --litecoind.rpcpass=xu --litecoind.zmqpubrawblock=tcp://127.0.0.1:29442 --litecoind.zmqpubrawtx=tcp://127.0.0.1:29444 --debuglevel=debug`

##### Fund lnd after balance confirmed, try to sencoins back to litecoin address(any type)

`./lncli --network=mainnet --no-macaroons --rpcserver=localhost:10001 sendcoins --addr=MQjGGyBTtgtha6T9FmCjATFV1AJYvBWkNe --amt=100
[lncli] rpc error: code = Unknown desc = unknown address type`

**Comment by dannypaz** [comment]
@RostyslavAntonyshyn Im going to link to this address in another issue as `AddInvoice` is also affected by this bug for fallback addresses
