### ISSUE TITLE
Channel ID : 0 

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#2095]
### Background

Hello, I've opened a channel and I found it in state "active":false
this could be related to the remote channel offline at this moment.
I'm worried about the CHANNEL ID: 0 
Is this a bug? What does it mean?

lncli listchannels (for the channel of this topic):

            "active": false,
            "remote_pubkey": "032d4baebebfdeab7a2ecef2fbe109cbef10de95f05aa54090fdb687789547dbf5",
            "channel_point": "fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64:0",
            "chan_id": "0",
            "capacity": "100000",
            "local_balance": "98240",
            "remote_balance": "0",
            "commit_fee": "1760",
            "commit_weight": "600",
            "fee_per_kw": "2432",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },

Thanks in advice 

### Your environment

lnd-0.5
linux
bitcoind-0.17.0

### Expected behaviour

The channel should have a Channel ID

### Actual behaviour

Channel ID is 0

**Comment by danbadjar** [comment]
Searching the funding tx ( fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64 ) in a blockchain explorer it seems that it doesn't even exist

**Comment by wpaulino** [comment]
@danbadjar the transaction seems to have confirmed now. A `chan_id` of 0 would mean that the funding transaction has yet to confirm, but in that case it _shouldn't_ show under `listchannels`, so this is definitely undesired behavior. Do you have any logs for the opening/confirmation process?

**Comment by Roasbeef** [comment]
[The funding tx _does_ indeed exist](https://www.smartbit.com.au/tx/fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64). It would show as zero, if the funding manager never actually announced it to the network as a whole.

**Comment by danbadjar** [comment]
Hello to you all and thanks for the kindly responses.
Checked the tx id and yes, now it exists and it's confirmed.
Unfortunately the chan_id is still 0  as lncli listchannels shows:

            "active": false,
            "remote_pubkey": "032d4baebebfdeab7a2ecef2fbe109cbef10de95f05aa54090fdb687789547dbf5",
            "channel_point": "fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64:0",
            "chan_id": "0",
            "capacity": "100000",
            "local_balance": "98240",
            "remote_balance": "0",
            "commit_fee": "1760",
            "commit_weight": "600",
            "fee_per_kw": "2432",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false

I attach 2 logs.
1.log is obtained by grepping the tx id in lnd.log
2.log is obtained by grepping FNDG in lnd.log

[2.log](https://github.com/lightningnetwork/lnd/files/2518109/2.log)
[1.log](https://github.com/lightningnetwork/lnd/files/2518110/1.log)

If it can help my bitcoind backend debug.log shows a lot of this entries:

ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 0fd7ab36246daf61802e10a0316cc2b0f17a1d6404bfdd53878ba34e158b4680, high-hash, proof of work failed (code 16)

2018-10-26T07:03:13Z UpdateTip: new best=0000000000000000001f2a9c762ce493cfc6967d46a17d6fbcc412e6165dabe7 height=547373 version=0x20000000 log2_work=89.914329 tx=351506341 date='2018-10-26T07:02:28Z' progress=1.000000 cache=76.1MiB(564284txo) warning='16 of last 100 blocks have unexpected version'

Thanks in advice for your patience and disponibility

**Comment by wpaulino** [comment]
Seems like the relevant parts we need have moved to the gzipped log files. We'll want to check those as well. We can also just search for the txid `fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64` to gather more results.

**Comment by danbadjar** [comment]
Hello and thanks for your response.
I attach the log obtained by grepping the txid in the last gzipped log.
[fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64.log](https://github.com/lightningnetwork/lnd/files/2520000/fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64.log)

At the moment everything seems ok with this channel and suddenly if I check it with lncli listchannels I have the channel_id valorized. Here's the output:

        {
            "active": true,
            "remote_pubkey": "032d4baebebfdeab7a2ecef2fbe109cbef10de95f05aa54090fdb687789547dbf5",
            "channel_point": "fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64:0",
            "chan_id": "601648364714000384",
            "capacity": "100000",
            "local_balance": "98240",
            "remote_balance": "0",
            "commit_fee": "1760",
            "commit_weight": "600",
            "fee_per_kw": "2432",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },

I don't know if the errors on my backend bitcoind could be the source of this problem.
I've never seen a chan_id = 0 in the output of lncli listchannels.

Thanks

**Comment by Roasbeef** [comment]
Nice! Looks like we eventually sent out the full proof for this channel, so were able to re-discover the proper channel ID.
