### ISSUE TITLE
SignMessage & VerifyMessage missing from REST API

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2096]
### Background

The SignMessage and VerifyMessage commands available to gRPC are not available via the REST API. Not sure if there's a particular reason for this, but ideally the APIs should be at parity with each other.

### Your environment

* version of `lnd` - 0.5.0-beta
* which operating system (`uname -a` on *Nix) - macOS
* version of `btcd`, `bitcoind`, or other backend - btcd

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Actual behaviour

N/A

**Comment by wpaulino** [comment]
This is because they're missing a REST endpoint like the other RPCs do.
https://github.com/lightningnetwork/lnd/blob/5c6c9668916461536e15b5be11e06adee0cfa89d/lnrpc/rpc.proto#L263
