### ISSUE TITLE
Can't open channels. Funding txs doesn't exist

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#2099]
### Background

Hello,
suddenly I notice that I can't open channels. Funding tx doesn't exist and my channels remain in pending state forever.
Yesterday I've opened a channel with 02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469

    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469",
                "channel_point": "1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0",
                "capacity": "1000000",
                "local_balance": "998551",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "1449",
            "commit_weight": "600",
            "fee_per_kw": "2002"
        },
Here is my log obtained by grepping the channel_point in lnd.log 
[funding.log](https://github.com/lightningnetwork/lnd/files/2518461/funding.log)

In my backend bitcoin core (bitcoind) I have a lot of these errors:

ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 0fd7ab36246daf61802e10a0316cc2b0f17a1d6404bfdd53878ba34e158b4680, high-hash, proof of work failed (code 16)
ERROR: AcceptBlockHeader: prev block not found

I don't know if it's normal.
Thanks in advice to all those who want to help me

### Your environment

lnd-0.5
linux
bitcoind-0.17.0

**Comment by danbadjar** [comment]
It seems that the transaction is not in the mempool. The output of the command is:

error code: -5
error message:
No such mempool or blockchain transaction. Use gettransaction for wallet transactions.

The channel appears in lncli pendingchannels:

    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469",
                "channel_point": "1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0",
                "capacity": "1000000",
                "local_balance": "998551",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "1449",
            "commit_weight": "600",
            "fee_per_kw": "2002"
        },

The only errors I have on my bitcoind , in addition of the 2 mentioned before is:

socket recv error Connection reset by peer (104)

I don't have a RPC connection between bitcoind and lnd. I used .cookie file and everything seems ok by this side.

Thanks

**Comment by wpaulino** [comment]
In that case, we can see the transaction being broadcast in the logs. Just look for `Broadcasting funding tx for ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95` and the transaction should show below.

**Comment by danbadjar** [comment]
Found it in lnd.log:

2018-10-25 10:17:10.281 [INF] FNDG: Broadcasting funding tx for ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0): (*wire.MsgTx)(0xc0020c3540)({
 Version: (int32) 1,
 TxIn: ([]*wire.TxIn) (len=3 cap=15) {
  (*wire.TxIn)(0xc00079d2c0)({
   PreviousOutPoint: (wire.OutPoint) 0a0db5112f9b9e063ee145f67f333735f7de11c8336c606d2754617c7b3ae0eb:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 1c 04 af 66  15 54 2b fd c2 d4 05 b0  |0D. ...f.T+.....|
     00000010  bb 05 51 4b 15 09 e2 2c  4c 48 5d e2 13 22 e9 ce  |..QK...,LH].."..|
     00000020  92 a8 4c 71 02 20 06 26  9f 0d 20 b4 d8 ff 10 60  |..Lq. .&.. ....`|
     00000030  87 9b fc 22 ca 79 86 91  78 96 f9 30 18 b4 7f 21  |...".y..x..0...!|
     00000040  3b 62 59 44 75 a8 01                              |;bYDu..|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  02 0d 5b 27 20 d7 53 68  d0 85 03 0f 20 6c e9 6d  |..[' .Sh.... l.m|
     00000010  1f 63 92 1b 60 7f 53 7d  3d 3c 91 89 0c 9c d4 5b  |.c..`.S}=<.....[|
     00000020  72                                                |r|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00079d260)({
   PreviousOutPoint: (wire.OutPoint) 55c28b5397b1da9be891c023a15904f41b06591c1f59e05c3e8bedaff60a4a5e:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 3a 3c 14 ac  42 21 53 01 a1 13 9e d7  |0D. :<..B!S.....|
     00000010  91 c5 80 38 05 c7 a1 f9  68 72 84 b3 80 1f e5 15  |...8....hr......|
     00000020  4d cd 84 0e 02 20 45 a1  a6 22 5c 16 db 46 df eb  |M.... E.."\..F..|
     00000030  e5 e1 33 56 59 af c0 50  b3 5a 41 65 fb 73 fb c6  |..3VY..P.ZAe.s..|
     00000040  be a2 ab 94 f9 25 01                              |.....%.|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  03 e4 eb fe 5c b0 11 c8  bd 22 c6 cf a0 75 77 2b  |....\...."...uw+|
     00000010  41 14 12 5c d2 fb 11 cb  a3 7c ee 4c 6f f2 bb f9  |A..\.....|.Lo...|
     00000020  d0                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00079d200)({
   PreviousOutPoint: (wire.OutPoint) fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64:1,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 2f 99 bf 44  aa 3a d0 c4 8a 98 1f 37  |0D. /..D.:.....7|
     00000010  20 a7 26 03 7d 97 85 95  87 14 96 21 f1 fe 99 af  | .&.}......!....|
     00000020  06 bc 10 2a 02 20 13 3e  57 cf 38 cd 2b 62 cf 9f  |...*. .>W.8.+b..|
     00000030  da d5 b6 9f f3 40 fb 00  e3 4b 6d 42 ef e6 c1 17  |.....@...KmB....|
     00000040  70 3c 18 34 57 87 01                              |p<.4W..|
    },    ([]uint8) (len=33 cap=33) {
     00000000  02 29 85 52 a9 5a 01 e8  5a a9 24 ae 0b 0e 01 2d  |.).R.Z..Z.$....-|
     00000010  e2 04 6b 70 85 21 48 04  f2 51 fc 6d 37 c8 01 0f  |..kp.!H..Q.m7...|
     00000020  22                                                |"|
    }
   },
   Sequence: (uint32) 4294967295
  })
 },
 TxOut: ([]*wire.TxOut) (len=2 cap=15) {
  (*wire.TxOut)(0xc000672d40)({
   Value: (int64) 1000000,
   PkScript: ([]uint8) (len=34 cap=500) {
    00000000  00 20 ca 09 3f 4b 0d 39  c7 f2 bf 14 f5 6e 5f 71  |. ..?K.9.....n_q|
    00000010  36 a9 85 c5 1a ef 2e ac  94 3f 91 7c 48 8e 9c cf  |6........?.|H...|
    00000020  8f 99                                             |..|
   }
  }),
  (*wire.TxOut)(0xc0006ac6e0)({
   Value: (int64) 1054320,
   PkScript: ([]uint8) (len=22 cap=500) {
    00000000  00 14 5e 96 ba 9d 43 04  e6 de 31 56 bc a0 b7 68  |..^...C...1V...h|
    00000010  b0 95 8a cc c1 1d                                 |......|
   }
  })
 },
 LockTime: (uint32) 0
})

2018-10-25 10:17:10.285 [INF] LNWL: Inserting unconfirmed transaction 1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95
2018-10-25 10:17:10.594 [ERR] FNDG: unable to broadcast funding txn: Transaction rejected: output already spent
2018-10-25 10:17:10.594 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0)
2018-10-25 10:17:10.595 [INF] NTFN: New block epoch subscription
2018-10-25 10:17:10.607 [INF] CNCT: ChannelArbitrator(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0): starting state=StateDefault
2018-10-25 10:17:10.612 [INF] NTFN: New spend subscription: utxo=1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0
2018-10-25 10:17:10.970 [INF] FNDG: Finalizing pendingID(0ea319931b29b98fef3355754e10998db5e98003491485bf91941ae17b45ff80) over ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0), waiting for channel open on-chain
2018-10-25 10:17:10.970 [INF] CNCT: Close observer for ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0) active
2018-10-25 10:17:10.971 [INF] FNDG: Waiting for funding tx (1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95) to reach 3 confirmations
2018-10-25 10:17:10.972 [INF] NTFN: New confirmation subscription: txid=1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95, numconfs=3
2018-10-25 10:17:11.608 [ERR] NTFN: Rescan for spend notification txout(313337326266663964376164633465656562343432653933346430303731623731363536346431663666363236383466653464336266653861383631356339353a30) failed: transaction not found within range


Do you have any idea?

**Comment by wpaulino** [comment]
The funding transaction is using an output that's already been spent (`0a0db5112f9b9e063ee145f67f333735f7de11c8336c606d2754617c7b3ae0eb:0`).

Did you upgrade to 0.5 from a previous version or is this a new node?

**Comment by danbadjar** [comment]
This is a new node (lnd-0.5). I often upgrade it by downloading last commits from git.
I don't know if this is a good procedure or not but I've never used lnd < 0.5 version
Is a normal situation that I found the opening channel even if the tx doesn't exist?
Sorry but I'm a newbie and I'm trying to understanding what to do now or if this could be considered a bug.
Can I close a pending opening channel and reopening it later? Should this work ?

Thanks for your support

**Comment by danbadjar** [comment]
Tried to close the channel:
`lncli closechannel --force 1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95 0`

Output:

```
2018-10-26 21:03:35.691 [INF] LNWL: Inserting unconfirmed transaction b9f29d1702db579d9b67007ec65e23e9c3dfa8f68b9670a4b946d37338df993c
2018-10-26 21:03:35.994 [ERR] CNCT: ChannelArbitrator(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0): unable to broadcast close tx: Transaction rejected: output already spent
2018-10-26 21:03:36.153 [INF] CNCT: ChannelArbitrator(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0): noop trigger userTrigger
2018-10-26 21:03:36.154 [INF] PEER: Waiting for confirmation of cooperative close of ChannelPoint(1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0) with txid: b9f29d1702db579d9b67007ec65e23e9c3dfa8f68b9670a4b946d37338df993c
2018-10-26 21:03:36.155 [INF] NTFN: New confirmation subscription: txid=b9f29d1702db579d9b67007ec65e23e9c3dfa8f68b9670a4b946d37338df993c, numconfs=1
2018-10-26 21:03:36.184 [ERR] CNCT: Unable to disable channel 1372bff9d7adc4eeeb442e934d0071b716564d1f6f62684fe4d3bfe8a8615c95:0 on close: edge not found
```
Tried to reopen channel with less satoshis and the lncli command hangs.
The entry in my lnd.log is:

```
2018-10-26 21:08:05.434 [INF] LNWL: Performing funding tx coin selection using 1750 sat/kw as fee rate
2018-10-26 21:08:05.969 [INF] FNDG: Target commit tx sat/kw for pendingID(2fa56d7286239261bdd43c1675af7538ebe5011f31331ed027db946e8144e87d): 2689
2018-10-26 21:08:05.970 [INF] FNDG: Starting funding workflow with 109.239.79.181:56766 for pendingID(2fa56d7286239261bdd43c1675af7538ebe5011f31331ed027db946e8144e87d)

```

Searched the new tx in blockchain with `bitcoin-cli getrawtransaction 2fa56d7286239261bdd43c1675af7538ebe5011f31331ed027db946e8144e87d`
But the tx seems not to exist:
```
error code: -5
error message:
No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
```

Opening a channel with a different node has worked fine.

thanks

**Comment by danbadjar** [comment]
In addition:

`2018-10-26 21:18:55.337 [ERR] RPCS: unable to open channel to NodeKey(02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469): reservation timed out waiting for peer (peerID:&{0x1a42660 93162746650022752342188251569107910372578863127868846617692951791722036360297 37165765782557854869010865635498783213512286523587243610725885566527965360774}, chanID:2fa56d7286239261bdd43c1675af7538ebe5011f31331ed027db946e8144e87d)
`

**Comment by wpaulino** [comment]
> Tried to reopen channel with less satoshis and the lncli command hangs.

This is possible if the remote peer doesn't respond, which we can tell happened by looking at `2018-10-26 21:18:55.337 [ERR] RPCS: unable to open channel to NodeKey(02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469): reservation timed out waiting for peer (peerID:&{0x1a42660 93162746650022752342188251569107910372578863127868846617692951791722036360297 37165765782557854869010865635498783213512286523587243610725885566527965360774}, chanID:2fa56d7286239261bdd43c1675af7538ebe5011f31331ed027db946e8144e87d`.

> Can I close a pending opening channel and reopening it later? Should this work ?

A channel can't be closed if there's no funding transaction present to begin with.

> This is a new node (lnd-0.5). I often upgrade it by downloading last commits from git.
I don't know if this is a good procedure or not but I've never used lnd < 0.5 version
Is a normal situation that I found the opening channel even if the tx doesn't exist?
Sorry but I'm a newbie and I'm trying to understanding what to do now or if this could be considered a bug.

The reason why I ask is because in versions prior to 0.5, there was a bug in the wallet that would lead to duplicate UTXOs. This has been addressed to no longer happen going forward though. So I'm not quite sure what could be causing your problem yet. Perhaps it does have to do with the errors you are seeing on your backend node.

**Comment by Roasbeef** [comment]
It looks like something is up with your bitcoind node, are you able to find any of these transactions in your mempool?

**Comment by Roasbeef** [comment]
Before you attempted to open channels, did you do any calls with `sendcoins` with a custom fee rate?

**Comment by danbadjar** [comment]
Yes I used sendcoins with custom fees and everything went fine.
I can't find any of these transactions in the mempool

**Comment by danbadjar** [comment]
I've just tried `lncli sendcoins` but it seems my funds are locked and I can't withdraw:

lncli walletbalance
{
    "total_balance": "1756563",
    "confirmed_balance": "1756563",
    "unconfirmed_balance": "0"
}

lncli sendcoins --addr bc1qzhs5nnhkqzj2wlu9wegudg9p2quyucd8ymq54u --amt 1200000 --sat_per_byte 17
[lncli] rpc error: code = Unknown desc = -25: Missing inputs

**Comment by danbadjar** [comment]
Hello, I've tried to consolidate tx inputs closing channels and force closing which are not online.
At the moment I have 3 pending_force_closing_channels:
```
 {
  "channel": {
   "remote_node_pub": "0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4",
   "channel_point": "4ed4bc5dfe9abd07697334ccf505cfdff13e1336fff01dbdc4b33cc5ae3ea42a:1",
   "capacity": "400000",
   "local_balance": "398053",
   "remote_balance": "0"
  },
  "closing_txid": "8ce95896be9a33e8f133bb85bc3e493b7ff0ae9aad074713ce36f969a62a13c2",
  "limbo_balance": "398053",
  "maturity_height": 547680,
  "blocks_til_maturity": 138,
  "recovered_balance": "0",
  "pending_htlcs": []
 },
 {
  "channel": {
   "remote_node_pub": "032d4baebebfdeab7a2ecef2fbe109cbef10de95f05aa54090fdb687789547dbf5",
   "channel_point": "fbb4c1c5560b3b54608428a2355f7a06aedba5408b00b8bc68aade3b0b8d8e64:0",
   "capacity": "100000",
   "local_balance": "98055",
   "remote_balance": "0"
  },
  "closing_txid": "96d2eda43d4505770370129a5fafbffd667f67e22f24517c74483dd31114c987",
  "limbo_balance": "98055",
  "maturity_height": 547679,
  "blocks_til_maturity": 137,
  "recovered_balance": "0",
  "pending_htlcs": []
 },
 {
  "channel": {
   "remote_node_pub": "0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3",
   "channel_point": "974019dcd5acadc0e984b455aa976a21abe7a5f227f189e4ecfb6a2f125f3285:0",
   "capacity": "500000",
   "local_balance": "498055",
   "remote_balance": "0"
  },
  "closing_txid": "17dacab2f2f8171fdd6691a23b3f0ea3d2a2e2a0e89802315d0086d4a9425f5f",
  "limbo_balance": "498055",
  "maturity_height": 547679,
  "blocks_til_maturity": 137,
  "recovered_balance": "0",
  "pending_htlcs": []
 }
```

lncli walletbalance shows 0 unconfirmed balance
```
{
    "total_balance": "5867582",
    "confirmed_balance": "5867582",
    "unconfirmed_balance": "0"
}
```

I can't even withdraw using lncli sendcoins
lncli sendcoins --addr bc1qzhs5nnhkqzj2wlu9wegudg9p2quyucd8ymq54u --amt AMOUNT --sat_per_byte 11
[lncli] rpc error: code = Unknown desc = -25: Missing inputs

```
Closing txids have more than 6 confirmations.
Can anyone help me?
lnd-0.5

**Comment by danbadjar** [comment]
the only entries I have in my logs:

```
2018-10-27 13:18:09.653 [INF] RPCS: [sendcoins] addr=bc1qzhs5nnhkqzj2wlu9wegudg9p2quyucd8ymq54u, amt=0.05 BTC, sat/kw=2750
2018-10-27 13:18:09.811 [INF] LNWL: Inserting unconfirmed transaction 9e75a102c947ae6e6ae990e6800a56e5525f2701ed2c9c9c3d7d27ad1708067a
2018-10-27 13:18:09.812 [DBG] LNWL: Marked address bc1qru5vhwluph5echjcywcpu6dz8q9u0fgl9t5a6j used

```

**Comment by wpaulino** [comment]
The `Missing inputs` error would mean that your wallet's UTXO set is faulty. This could arise due to a bug when using `sendcoins` which has been addressed as of https://github.com/lightningnetwork/lnd/commit/7ad1f9f7d73b1a63268e11a6ed01aa3d1a61504f. I would suggest upgrading to that commit or later, and rescanning your wallet with the [`dropwtxmgr`](https://github.com/btcsuite/btcwallet/blob/master/cmd/dropwtxmgr/main.go) tool. This will force a chain rescan of your wallet upon startup and will pick up all of your relevant UTXOs.

As for your pending channels, your funds will return to your wallet after the CSV delay (`blocks_til_maturity`).

**Comment by halseth** [comment]
`dropwtxmgr` works for btcwallet, so it is independent of the chain backend.

Closing per https://github.com/lightningnetwork/lnd/issues/2099#issuecomment-433655909 and https://github.com/lightningnetwork/lnd/issues/2099#issuecomment-433714834.

**Comment by bidelakbari** [comment]
I encountered the same issue about 4 days ago.
I'm still trying ...

_This is what that happened so far:_
1- Opened a channel to a node
2- In <code>pendingchannels</code> i can see a pending_open_channel entry
3- The txid does not exist anywhere (also not in my bitcoind mempool)
4- Updated the lnd and lncli to the latest version <code>lnd version 0.5.1-beta commit=v0.5.1-beta-311-ga0c0e8edc9a58e8833fd32119964207205f9c764</code>
5- Ran <dropwtxmgr> on my wallet.db file
6- Restarted the lnd and unlocked the wallet successfully but the pending_open_channel_entry is still there. also the tx still not exists anywhere.
7- In lnd log file I could find this: 
<code>[ERR] NTFN: Rescan to determine the spend details of txid:1 failed: transaction not found within range</code>

any ideas?

**Comment by danbadjar** [comment]
Sorry to tell but as a newbie I started a fresh node with LND 0.5.1 and I have no more of this errors.
Some money on my old LND server were lost

**Comment by bidelakbari** [comment]
I could recover my onchain funds via <code>sendcoins</code> but I don't want to start fresh because of my existing inbound channels.

**Comment by danbadjar** [comment]
It was the same for me but luckily i had few channels

**Comment by wpaulino** [comment]
@bidelakbari you can run the `lncli abandonchannel` command to remove it from there. You'll need a debug build in order to use it, which you can obtain by running `make` and using the `lnd-debug` binary found within.

**Comment by Rui2guo** [comment]
> I encountered the same issue about 4 days ago.
> I'm still trying ...
> 
> _This is what that happened so far:_
> 1- Opened a channel to a node
> 2- In `pendingchannels` i can see a pending_open_channel entry
> 3- The txid does not exist anywhere (also not in my bitcoind mempool)
> 4- Updated the lnd and lncli to the latest version `lnd version 0.5.1-beta commit=v0.5.1-beta-311-ga0c0e8edc9a58e8833fd32119964207205f9c764`
> 5- Ran `dropwtxmgr` on my wallet.db file
> 6- Restarted the lnd and unlocked the wallet successfully but the pending_open_channel_entry is still there. also the tx still not exists anywhere.
> 7- In lnd log file I could find this:
> `[ERR] NTFN: Rescan to determine the spend details of txid:1 failed: transaction not found within range`
> 
> any ideas?
> 
> EDIT: @Roasbeef how I can remove the `pending_open_channel` entry now that I could recover my onchain funds?
> I tried `closechannel --force` but it throw this error `[lncli] rpc error: code = Unknown desc = unable to find channel`
> 
> any help would be appreciated.


Hello， I don't know if your problem has been solved. I've also met this problem.

**Comment by wpaulino** [comment]
@Rui2guo see https://github.com/lightningnetwork/lnd/issues/2099#issuecomment-452854844.
