### ISSUE TITLE
Create a WalletController implementation for Bitcoin Core

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#21]
Within the daemon there exists an base-wallet interface called the `WalletController` which the `LightningWallet` uses in a composite manner to create a fully-fledged Lightning enabled wallet. The interface itself is rather minimal and should be able to accommodate easily dropping in an alternative wallet into the daemon. 

The current, and only (at the time of writing this issue) concrete implementation of the `WalletController` is `BtcWallet` which is implemented by an embedded instance of [`btcwallet`](https://github.com/btcsuite/btcwallet). Due to the current architecture of `btcwallet` an active `btcd` instance is required for the wallet to function correctly. 

Due to popularity, a `WalletController` interface implementation for Bitcoin Core's wallet should be added. The implementation of the interface should be possible entirely over Bitcion Core's RPC interface. [`btcrpcclient`](https://godoc.org/github.com/btcsuite/btcrpcclient) is capable of connecting to Bitcoin Core instances and should be sufficient in helping to implement the interface. A simple layer of persistent storage within the `WalletController` implementation may be required in order to fully implement all the features of the interface. 

This issue is dependent on #17 as the PR implements the necessary refactoring within the daemon to allow dropping in multiple/alternative wallets.

**Comment by mmgen** [comment]
Please make lnd usable with bitcoind as a backend. This will greatly increase your user base.

**Comment by johynpapin** [comment]
Does anyone work on this issue? If not, I'll try.

**Comment by aakselrod** [comment]
Sorry the assignment isn't updated, but I'm working on this issue. Thanks!

**Comment by gituser** [comment]
any update on this @aakselrod ?

would like to test lnd with bitcoin-core.

**Comment by halseth** [comment]
@gituser Awesome, you can help test following these instructions: https://gist.github.com/aakselrod/5644b9319041a796ba6ffca28062376e

**Comment by Roasbeef** [comment]
Closed by #447.
