### ISSUE TITLE
Allow private channels to be used in sendtoroute

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2139]
### Background

Currently sendtoroute takes as an argument a set of hops that assume the channels specified reference channels known to the channel graph.

Completely specifying all the route details including public keys of node hops is not possible, which precludes the ability to use sendtoroute for things like sending to private recipients.

### Expected behaviour

Ideally sendtoroute would accept public keys in its arguments and follow crafted routes as specified without needing to consult the channel graph for edge and node lookups.

**Comment by AndrewSamokhvalov** [comment]
#1944
