### ISSUE TITLE
Payinvoice hangs (forever?) if initiated early after lnd restart

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#2141]
### Background

I've tried to perform small (~50ksat) payment to Bitrefill, but it timeouted after ~1 minute multiple times due to some "TemporaryChannelFailure".

Then I've (naively) restarted `lnd`, and after checking with `getinfo` that I have active channels, tried to perform payment with new invoice. 

But it `lncli payinvoice ...` didn't exit for quite some time, much longer than for 1 minute in the usual case. I've terminated it with `cltr+c`, tried again to pay the same invoice, and got "payment in transition".

I've restarted again, and tried to do payment for new invoice again, without terminating `lncli`. It's still there after ~20 minutes:
```
root@odroid-hc1:~# ps aux | fgrep lncli
root      3330  0.0  0.0   3764   528 pts/8    S+   13:07   0:00 grep -F lncli
lnd      32496  0.0  0.4 859280  9200 pts/7    Sl+  12:45   0:00 lnd.go/bin/lncli payinvoice lnbc568u1p...
root@odroid-hc1:~# date
Sat Nov  3 13:07:34 EET 2018
```

Looking at journal, I see error just before performing payment:
```
Nov 03 12:44:35 odroid-hc1 lnd[31982]: 2018-11-03 12:44:35.090 [ERR] HSWC: Cannot find pending payment with ID 6000
```
I guess it's about that previous "payment In transition"?

Anyway, currently collected `[ERR`] entries after latest payment:
```
Nov 03 12:44:35 odroid-hc1 lnd[31982]: 2018-11-03 12:44:35.090 [ERR] HSWC: Cannot find pending payment with ID 6000
Nov 03 12:44:59 odroid-hc1 lnd[31982]: 2018-11-03 12:44:59.989 [ERR] HSWC: ChannelLink(0:0:0) Failing link: unable to synchronize channel states: didn't receive ChannelReestablish before deadline
Nov 03 12:45:01 odroid-hc1 lnd[31982]: 2018-11-03 12:45:01.357 [ERR] HSWC: ChannelLink(0:0:0) Failing link: unable to synchronize channel states: didn't receive ChannelReestablish before deadline
Nov 03 12:45:01 odroid-hc1 lnd[31982]: 2018-11-03 12:45:01.362 [ERR] HSWC: ChannelLink(0:0:0) Failing link: unable to synchronize channel states: didn't receive ChannelReestablish before deadline
Nov 03 12:45:39 odroid-hc1 lnd[31982]: 2018-11-03 12:45:39.368 [ERR] PEER: unable to send msg to remote peer: peer exiting
Nov 03 12:47:28 odroid-hc1 lnd[31982]: 2018-11-03 12:47:28.310 [ERR] HSWC: ChannelLink(0:0:0) Failing link: unable to synchronize channel states: didn't receive ChannelReestablish before deadline
```

This is `strace` for `lncli`:
```
lnd@odroid-hc1:~$ strace -v -r -f -p 32496
strace: Process 32496 attached with 8 threads
[pid 32563]      0.000000 futex(0x11b685d0, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32502]      0.000077 futex(0x78295c, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32501]      0.000055 futex(0x11b68350, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32500]      0.000099 futex(0x11b680d0, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32499]      0.000055 epoll_wait(4,  <unfinished ...>
[pid 32498]      0.000153 futex(0x11b365d0, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32497]      0.000059 futex(0x772670, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 32496]      0.000166 futex(0x772a40, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 32497]     36.184377 <... futex resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 32497]      0.000107 clock_gettime(CLOCK_MONOTONIC, {tv_sec=1102005, tv_nsec=330650519}) = 0
[pid 32497]      0.000190 clock_gettime(CLOCK_MONOTONIC, {tv_sec=1102005, tv_nsec=330835644}) = 0
[pid 32497]      0.000293 pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
[pid 32497]      0.002709 clock_gettime(CLOCK_MONOTONIC, {tv_sec=1102005, tv_nsec=333841645}) = 0
[pid 32497]      0.000167 futex(0x772670, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0}
```

Also I've noticed that `lnd` CPU usage is high after restart and decreases slowly with time:
![cpubyproc-day](https://user-images.githubusercontent.com/292191/47951620-13159680-df5b-11e8-915e-622693c6c0a2.png).

Maybe `lnd` is not "ready" for the payments on my slow `odroid-hc1` machine, early after `lnd` restart? If so, I would expect `lncli` to timeout, or error early. If payment will go through, it will be "lost" because payment receiver would expire invoice after ~15 minutes...

### Your environment

* `0.5.0-beta commit=v0.5-beta-295-gb6009850635cf966eb3bd637de5da89cb9262589`
* `Linux odroid-hc1 4.9.0-8-armmp-lpae #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) armv7l GNU/Linux`
* `Satoshi:0.17.0`

### Steps to reproduce

Restart `lnd` and try to pay invoice as soon as possible (on slow machine?).

### Expected behaviour

`lncli` should timeout/error within a minute or so, much earlier than usual invoice expiration.

### Actual behaviour

`lncli payinvoice` hangs forever (so far).

**Comment by Talkless** [comment]
I'll try to perform another payment after `lnc` CPU usage settles down...

**Comment by wpaulino** [comment]
> I've tried to perform small (~50ksat) payment to Bitrefill, but it timeouted after ~1 minute multiple times due to some "TemporaryChannelFailure".

`TemporaryChannelFailure` in this case means that we tried all the possible routes to the destination, but there wasn't enough balance along the route to completely forward the payment.

> But it lncli payinvoice ... didn't exit for quite some time, much longer than for 1 minute in the usual case. I've terminated it with cltr+c, tried again to pay the same invoice, and got "payment in transition".

As we discussed on IRC, when a payment is sent, a payment session is started by `lnd` that attempts multiple routes (if any). If an intermediate node of a single route does not send a response back, then the payment session will hang rather than time out.

> I've restarted again, and tried to do payment for new invoice again, without terminating lncli. It's still there after ~20 minutes:

It's possible that this payment took the same route as the previous one that got stuck. This is something that we should improve in general, routes should not be tried with channels that have pending HTLCs. This is hard to do however, as we (as the sender) don't know the hop at which the HTLC is stuck at.

> Also I've noticed that lnd CPU usage is high after restart and decreases slowly with time:

See https://github.com/lightningnetwork/lnd/issues/2041#issuecomment-429442279 on how to retrieve a CPU profile of `lnd`.

**Comment by Talkless** [comment]
> It's possible that this payment took the same route as the previous one that got stuck

That's reasonable explanation. Will try to create additional channel to some other node and try payment again.

> See #2041 (comment) on how to retrieve a CPU profile of lnd.

Will try.

**Comment by Roasbeef** [comment]
So you're running bitcoind, tor, electrumx, and lnd on the same odroid? At a glance, seems like pretty high load for a SBC of that size. Those log messages show a channel that's unable to re-sync as the remote peer isn't sending the message needed to "ACK" that channel. 

> Nov 03 12:44:35 odroid-hc1 lnd[31982]: 2018-11-03 12:44:35.090 [ERR] HSWC: Cannot find pending payment with ID 6000

There's a bug in the system right now, where if you send a payment, then restart, the payment may actually be fulfilled, but won't be marked as such in the database.

**Comment by Talkless** [comment]
> So you're running bitcoind, tor, electrumx, and lnd on the same odroid?

Yep :) . Well, load / cpu usage is not that bad, the main issue is HDD which I will change to SSD in some time in the future. There's only issue after longer downtime, when bitcoind/electrum/lnd has to keep up:

![load-day](https://user-images.githubusercontent.com/292191/48016322-3428e380-e123-11e8-87fd-21c526c8f4ab.png)
![cpu-day](https://user-images.githubusercontent.com/292191/48016326-368b3d80-e123-11e8-9355-ffcbd93a528f.png)

At the moment of writing, `lnd` is getting much calmer after these restarts:
![cpubyproc-week](https://user-images.githubusercontent.com/292191/48016482-984ba780-e123-11e8-84e5-9db00268265d.png)

**Comment by Talkless** [comment]
> If an intermediate node of a single route does not send a response back, then the payment session will hang rather than time out.

I have tried again, and after seeing 3 `TemporaryChannelFailure` entries in log it hang again (for more than 10 minutes, so I've ctr-c'id it). So basically 3 routes failed in "responsible way", while next attempt was one of these unresponsive nodes?

Just after that I have tired to buy one pixel, and it worked with 4-node path from first try.

**Comment by wpaulino** [comment]
> I have tried again, and after seeing 3 TemporaryChannelFailure entries in log it hang again (for more than 10 minutes, so I've ctr-c'id it). So basically 3 routes failed in "responsible way", while next attempt was one of these unresponsive nodes?
Just after that I have tired to buy one pixel, and it worked with 4-node path from first try.

This is most likely because there was enough balance along the route for this payment but not the one you tried before (which is why you saw `TemporaryChannelFailure`).

**Comment by Talkless** [comment]
> See #2041 (comment) on how to retrieve a CPU profile of lnd.

I failed to get profile, it timeouts. 

Currently, my `lnd` running with `profile=10000` results in total CPU cap, all 8 cores ant 100%, load > 20..., and seems that `tool pprof` timeouts:
```
# /usr/lib/go-1.10/bin/go tool pprof http://127.0.0.1:10000/debug/pprof/profile
Fetching profile over HTTP from http://127.0.0.1:10000/debug/pprof/profile
http://127.0.0.1:10000/debug/pprof/profile: Get http://127.0.0.1:10000/debug/pprof/profile: net/http: timeout awaiting response headers
failed to fetch any source profiles
```

`tcpdump` confirms that `GET...` is sent (ACT received from `lnd`), but I get no response... I've increased `-timeout` but failed to get output after ~10 minutes... Or should I wait for more?

**Comment by wpaulino** [comment]
> all 8 cores ant 100%, load > 20...

I would say this is most likely the culprit for not receiving a response and timing out.

**Comment by Talkless** [comment]
> I would say this is most likely the culprit for not receiving a response and timing out.

No, I get all-100% when I launched profiler. It does not have such huge CPU load when running without profiling.

**Comment by Talkless** [comment]
What I wanted to say is that I cannot profile, as profiling itself seems to eat all resources...

**Comment by Talkless** [comment]
With 0.5.1, there are no more CPU usage spike & slow falloff (as seen in https://user-images.githubusercontent.com/292191/48016482-984ba780-e123-11e8-84e5-9db00268265d.png) after every restart! Great improvement :) .

**Comment by wpaulino** [comment]
Great! Will close this for now. We can reopen it if the issue comes back.
