### ISSUE TITLE
[feature request] Allow fee_limit_percent be specified as float

### ISSUE THREAD

**Issue by avemeva** [lightningnetwork/lnd#2154]
As far as I understand currently we could specify `fee_limit_percent` in `queryroutes` and `sendpayment` only as `int` which makes it impossible to specify `0.1%` percentage, and minimal `fee_limit_percent` becomes `1%` which is lot for payment.

**Comment by ccdle12** [comment]
hi, would be happy to work on this one

**Comment by halseth** [comment]
Can you calculate maximum absolute fee instead, and use `fee_limit`? IMO we shouldn't introduce more floats in the API 😛

**Comment by AndrewSamokhvalov** [comment]
@halseth Sure, it is not urgent, just gave small feedback on API 😄

**Comment by ccdle12** [comment]
@halseth I was updating the fee limit percent to double in the protobuf file :S, good to know!

**Comment by Roasbeef** [comment]
As @halseth notes, the caller can do this themselves, and then just map to a regular `fee_limit`. IIRC, we do this atm on the command line.

**Comment by armurbalda** [comment]
Definitely understand the reasoning (trying to avoid floats whenever possible too) but practically this makes the flag mostly useless.
