### ISSUE TITLE
Docker building "non-zero code:2" error when build dockerized lnd

### ISSUE THREAD

**Issue by babonet13** [lightningnetwork/lnd#2168]
I'm trying to build the lnd docker image locally on my machine using those resources : https://github.com/lightningnetwork/lnd/tree/master/docker/lnd

I got a error at Step 5/12 
make: *** No targets specified and no makefile found.  Stop.
The command '/bin/sh -c apk add --no-cache     git     make &&  cd /go/src/github.com/lightningnetwork/lnd &&  make &&  make install' returned a non-zero code: 2

PS : In fact I'm trying  to upgrade to LND 0.5. Is it planned for soon ?

**Comment by halseth** [comment]
I haven't tried the docker instructions in a while, feel free to send a PR to make it work with 0.5!

**Comment by babonet13** [comment]
How to send a Push Request ? Do I have to make a fork before and/or to create a new tag ? (Sorry I not very familiar with Github functionalities) ...

**Comment by halseth** [comment]
No worries! Originally you would need to create a fork, but I think GitHub now supports that you click the Edit button on the document, and create a Pull Request directly! 😀

**Comment by xsb** [comment]
@babonet13 looks like you are running docker build from within the `docker/lnd` directory so the build context (group of files) that are passed to the build environment inside the container does not include the root of the project, this would explain why the `make` command fails.

If you want to build the lnd container by yourself you can do it from the root of the repository and specifying the path of the Dockerfile.

```sh
docker build -f docker/lnd/Dockerfile .
```

You also have the option to use docker-compose as described [here](https://github.com/lightningnetwork/lnd/tree/master/docker).

**Comment by babonet13** [comment]
@xsb : I could succefully rebuild the lnd image using the command ```docker build -f docker/lnd/Dockerfile .``` Thanks

**Comment by wpaulino** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/2168#issuecomment-437850010.
