### ISSUE TITLE
Can't connect to onion nodes when using remote Tor

### ISSUE THREAD

**Issue by qubenix** [lightningnetwork/lnd#2176]
### Background

I'm using Whonix, which operates as a workstation and separate gateway where Tor is run. In order to use an onion service for my node I need to listen on `0.0.0.0`. In order to do that I have to disable Tor in my conf. This causes me to not be able to make connections to other onion nodes. I believe the problem is here: https://github.com/lightningnetwork/lnd/blob/d4b042dc1946ece8b60d538ade8e912f035612fe/server.go#L1659-L1663 but I don't know `go` enough to fix it.

**Comment by qubenix** [comment]
Upon further inspection it seems that altering `server.go` was not enough to fix this in my personal tests.

**Comment by svewa** [comment]
`You don't have to disable Tor completely. You can keep --tor.active set without setting --tor.v2 or --tor.v3. Then, all you need to do is point to the correct SOCKS proxy through --tor.socks.`

That works for outgoing connections but not for incoming connections

**Comment by qubenix** [comment]
>You don't have to disable Tor completely. You can keep --tor.active set without setting --tor.v2 or --tor.v3. Then, all you need to do is point to the correct SOCKS proxy through --tor.socks.

This statement is not correct, because once you set `tor.active=1` listening is disabled by `lnd`. `-listen` is completely ignored, even if set to localhost.

**Comment by aakselrod** [comment]
I'm running a similar setup as you and am running into the same issue. I'll get this fixed today.

**Comment by addressleakt** [comment]
>This statement is not correct, because once you set tor.active=1 listening is disabled by lnd. -listen is completely ignored, even if set to localhost.

>I'm running a similar setup as you and am running into the same issue. I'll get this fixed today.

Hello aakselrod, will you fix this that qubenix is talking about too? So we can have incoming connections over Tor running on a remote machine?
