### ISSUE TITLE
Dockerized lnd (re)-build : error at lauch 

### ISSUE THREAD

**Issue by babonet13** [lightningnetwork/lnd#2177]
In order to have a fresh version of LND in Dockerized mode, I have rebuild the image from this Dockerfile : https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/Dockerfile
Using this command : ```docker build -t lnd -f docker/lnd/Dockerfile .``` 

Build process was fine ...
... but when running the container, with this command :
docker run -d --name=lightning-node -v /home/satoshi/.bitcoin:/root/.bitcoin -v /home/sat
oshi/.lnd:/root/.lnd -p 9735:9735 -p 10009:10009 lnd --bitcoin.active --bitcoin.mainnet --bitcoin.node=bitcoind

I got this error :
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--bitcoin.active\": executable file not found in $PATH": unknown.

PS : I DO NOT have this error with the very same command using the lnd image pulled from the Docker registry

**Comment by babonet13** [comment]
@wpaulino : Thanks for pointing me thie new Dockerfile.

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/2185.
