### ISSUE TITLE
Fix gRPC documentation responseOpenChannel

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2180]
### Background

the response of openChannel and openChannelSync is not as described.

### Your environment

lnd version 0.5.0-beta commit=a3edcf9cd537ea37a502efc91d262e7017a99e6b
Linux 4.15.0-38-generic #41-Ubuntu 2018 x86_64 x86_64 x86_64 GNU/Linux
btcd version 0.12.0-beta

### Steps to reproduce

```
print "opening channel with bob:"
response = stub.OpenChannelSync(request, metadata=[('macaroon'), macaroon)])
print "response:",response
```

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

```
opening channel with bob:
response: { 
    "funding_txid_bytes": <bytes>,
    "funding_txid_str": <string>,
    "output_index": <uint32>,
}
```

### Actual behaviour

```
opening channel with bob:
response: funding_txid_bytes: "\366\312\323\014\245d\232\313\013\004\001P\245\341<\002\216\017I\203\214j>ub\364~\255\301e\2275"
```

**Comment by ranchalp** [comment]
Inspecting, found out that one cannot access them by the name of gRPC, but rather by the three following attribute names:
'OUTPUT_INDEX_FIELD_NUMBER', 
'FUNDING_TXID_BYTES_FIELD_NUMBER'
'FUNDING_TXID_STR_FIELD_NUMBER'

```
>>> ln.ChannelPoint.__dict__.keys()
['__module__', '__doc__', 'DESCRIPTOR', '__slots__', 'OUTPUT_INDEX_FIELD_NUMBER', 'FUNDING_TXID_BYTES_FIELD_NUMBER', 'FUNDING_TXID_STR_FIELD_NUMBER']
>>> responseOpenChannel.output_index
''
>>> responseOpenChannel.OUTPUT_INDEX_FIELD_NUMBER
3
```

**Comment by Roasbeef** [comment]
If the output index is zero, then depending on what language you use, it won't display the value as it thinks it's "nil". Re `funding_txid_str` vs `funding_txid_bytes`: there's a similar display artefact in that if it thinks one is "zero", then it won't actually display it. Most things that consume lnd use the raw bytes, but we added the string form for those that use the REST API.

**Comment by Roasbeef** [comment]
If you do `dir(response)`. or `print(dir(response))`, then you'll see all the fields.

**Comment by ranchalp** [comment]
I actually converted `funding_txid_bytes` and set `funding_txid_str` manually, and observed that both are somehow mutually exclusive. If I set myself `funding_txid_str` then `funding_txid_bytes` becomes 'None'.
Is this an expected behaviour? If so, I believe the gRPC documentation needs to update to show this behaviour.

**Comment by Roasbeef** [comment]
They're implemented as a `oneof`: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L747

So yeah, you should only set one or the other. The proper place to request changes to the display of the API is https://github.com/lightninglabs/lightning-api/issues, thanks!

**Comment by ranchalp** [comment]
Today I got a channel opened with an output index of 1, and yet the response to Open Channel had not set output index to one (that is, it was unset, so default to 0 for int):


code:
```
[...]
    print "local_node:", local_node
    print "creating channel, remote_node:", remote_node
    
    remote_node_bytes= remote_node.decode('hex')
    request = ln.OpenChannelRequest(
        node_pubkey=remote_node_bytes,
        node_pubkey_string=remote_node,
        local_funding_amount=amt,
        # push_sat=<int64>,
        # target_conf=<int32>,
        # sat_per_byte=<int64>,
        # private=<bool>,
        # min_htlc_msat=<int64>,
        # remote_csv_delay=<uint32>,
        # min_confs=<int32>,
        # spend_unconfirmed=<bool>,
    )
    try:
        responseOpenChannel = stub.OpenChannelSync(request, metadata=[('macaroon', macaroon)])
    except:
        print("Could not open channel. Unexpected error:", sys.exc_info())
        return None
    
    print "responseOpenChannel:" ,responseOpenChannel
    print "responseOpenChannel type:" ,type(responseOpenChannel)
    responseOpenChannel.funding_txid_str=responseOpenChannel.funding_txid_bytes[::-1].encode("hex")
    print "responseOpenChannel(after treated):" ,responseOpenChannel
    return responseOpenChannel
```

Output:
```[...]
local_node: 0358fa9016e5de00a2f2b0ad51ae4f6528a2dbbc2dae5d59a9cafa66f6d5e435ad
creating channel, remote_node: 0201aeb7f1b28c0b8244d4b214ca137f72870a0e52f9f53debe80eb403ffcd6a99
responseOpenChannel: funding_txid_bytes: "\263XsA\200\'\020\341\207\350\207Q3\364U\362$\235\367N^\007:\377pZ\025\003\215\267V\231"

responseOpenChannel type: <class 'rpc_pb2.ChannelPoint'>
responseOpenChannel(after treated): funding_txid_str: "9956b78d03155a70ff3a075e4ef79d24f255f4335187e887e1102780417358b3"

channel_point:  9956b78d03155a70ff3a075e4ef79d24f255f4335187e887e1102780417358b3:0
```

Actual channel:

```
$> lncli -n testnet getchaninfo 1588218158047559681
{
    "channel_id": "1588218158047559681",
    "chan_point": "9956b78d03155a70ff3a075e4ef79d24f255f4335187e887e1102780417358b3:1",
    "last_update": 1542822543,
    "node1_pub": "0201aeb7f1b28c0b8244d4b214ca137f72870a0e52f9f53debe80eb403ffcd6a99",
    "node2_pub": "0358fa9016e5de00a2f2b0ad51ae4f6528a2dbbc2dae5d59a9cafa66f6d5e435ad",
    "capacity": "16777215",
    "node1_policy": {
        "time_lock_delta": 144,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false
    },
    "node2_policy": {
        "time_lock_delta": 144,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false
    }
}
```

I do not think I should open a new issue, but let me know if I should.

```
$> python --version
Python 2.7.15rc1
$> pip list
grpcio (1.16.1)
grpcio-tools (1.16.1)
googleapis-common-protos (1.5.5)
```
