### ISSUE TITLE
lnwire+funding+routing: populate, implement and adhere to the new max_htlc ChannelUpdate value

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2182]
Recently, a new `max_htlc` value has been added to the ChannelUpdate message via a spec amendment: https://github.com/lightningnetwork/lightning-rfc/pull/465. This value in the short term, can allow nodes to signal the largest HTLC they're willing to carry, allow light clients who don' t verify channel existence to have some guidance when routing HTLCs, and finally may allow nodes to preserve a portion of their available bandwidth at all times by advertising a value lower than the actual channel capacity. In the long term, this can be used by implementations of AMP to guide payment splitting, as it becomes apparent to a node the _largest_ possible HTLC (in an idea world of full bandwidth available for each link direction one wishes to route) one can route over a particular channel. 

As a prep for our AMP implementation, and also to provide those existing naive light clients with additional path finding implementation, we should add and observe this new field. Now that PR #1825 has been merged, older nodes will properly retain and verify signatures including these new fields even though they haven't yet updated to recognize these fields. As a result, only now can we proceed with out implementation. 

# Steps To Completion 

- [ ] Update the `ChannelUpdate` struct in `lnwire` to partition the existing flags field into the new `channel_flags` and `message_flags` pairs. 

- [ ] Add a new `MaxHTLC` field to the `ChannelUpdate` message.

- [ ] When funding new channels, set a default for these values if one isn't specified. 

- [ ] Extend the `UpdateChanPolicy` RPC and cli commands to allow the caller to specify this value. This may require modifications to the peer and switch as well to ensure these fields properly propagate and are set properly. 

- [ ] Add new verification logic within the link [`HtlcSatifiesPolicy`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1874) method to ensure the HTLC isn't too large. 

- [ ] Update [the path finding logic](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L545) to ignore a channel if the HTLC value (including the fees at that point) exceed the max HTLC value (if set) of the link.

**Comment by valentinewallace** [comment]
i'll take this one! :)
