### ISSUE TITLE
The changing of the feerate in config doesn't affect to new channels

### ISSUE THREAD

**Issue by Perlover** [lightningnetwork/lnd#2184]
### Background

The `feerate` changed in config file doesn't affect to new channels (incoming channels, for example private channels from Bitcoin Lightning Wallet from Android - `BLW`)

### Your environment

* version of `lnd` 0.5.0-beta commit=v0.5-beta-321-gd4b042dc1946ece8b60d538ade8e912f035612fe
* which operating system (`uname -a` on *Nix) CentOS 6.*
* version of `bitcoind` - 0.17.0.1

### Steps to reproduce

1. Install `lnd` from sources
2. To setup first settings as:
    bitcoin.feerate=10000
    bitcoin.basefee=1000
3. To make channel from `BLW`. I made some payments - fee was 1%
4. After sometime (may be when some channels will be created through autopilot) to change `feerate` as 100
5. stop & start `lnd` daemon
6. close channel with `lnd` from `BLW`
7. To make channel again from `BLW` to `lnd`
8. After test payments i see again fee as 1%

### Expected behaviour

In point 8 i expect fee as 0.01%

### Actual behaviour

In point 8 i get fee as 1%

**Comment by CodingMuziekwijk** [comment]
I never used BLW but according the rpc api reference: 

" --fee_rate value         the fee rate that will be charged proportionally based on the value of each forwarded HTLC, the lowest possible rate is 0.000001"

So I think you should try fee_rate=0.00001

**Comment by Perlover** [comment]
@CodingMuziekwijk feerate in config is 1 / 1000000 so 100 is 0.0001 of API

**Comment by Perlover** [comment]
I made some tests (here and below: `BLW` - Bitcoin Lighting Wallet @ Android)
If BLW1 (and Eclair wallet @ Android too) connects to my node and other BLW2 connects to it too then when i send to from BLW1 to other BLW2 and versa - there is 1% comission.
If BLW2 connected to other node (for example to ACINQ) then there is comission is 0.01% (BLW1->BLW2) as expected. I checked it even debug info of channel.

The 1% fee is even if BLW1 connected to my node and Eclair wallet connected to my node too. When i send from Eclair to BLW - there 1% fee too (even though both channels are open after i changed feerate in config file and restarted `lnd`)

It feels like the old feerate in lnd to be cached for private channels even if these private channels are opened after reconfigured and restarting of lnd. Is it possible?

**Comment by Roasbeef** [comment]
Private channels don't pay fees, they aren't used for routing.

**Comment by Perlover** [comment]
I described here scheme as:

BLW1 <---> LND <---> BLW2

Yes, there are two private channels through one LND
Now there the LND has `bitcoin.feerate=100` in config file, many times i restarted it but if i send from BLW1 to BLW2 or from BLW2 to BLW1 through this LND the peyments has 1% of fee.

I described above that first time i had `bitcoin.feerate=10000` but after i changed to 100, restarted the LND, closed and opened again private channels but fee there for one forwardind is 1% now but should be 0.01% (a feerate as 100)

**Comment by Perlover** [comment]
`lncli fwdinghistory` now output:

    {
	"forwarding_events": [
	    {
		"timestamp": "1542198119",
		"chan_id_in": "604774276317839361",
		"chan_id_out": "604698409996058624",
		"amt_in": "208254",
		"amt_out": "208232",
		"fee": "22"
	    },
	    {
		"timestamp": "1542223729",
		"chan_id_in": "604698409995862016",
		"chan_id_out": "604819356264628224",
		"amt_in": "70077",
		"amt_out": "70069",
		"fee": "8"
	    },
	    {
		"timestamp": "1542228124",
		"chan_id_in": "604698409995862016",
		"chan_id_out": "604819356264628224",
		"amt_in": "142737",
		"amt_out": "142722",
		"fee": "15"
	    },
	    {
		"timestamp": "1542275262",
		"chan_id_in": "604774276317839361",
		"chan_id_out": "604698409996058624",
		"amt_in": "13",
		"amt_out": "12",
		"fee": "1"
	    },
	    {
		"timestamp": "1542277774",
		"chan_id_in": "604774276317839361",
		"chan_id_out": "604773176808570880",
		"amt_in": "101001",
		"amt_out": "100000",
		"fee": "1001"
	    },
	    {
		"timestamp": "1542277801",
		"chan_id_in": "604773176808570880",
		"chan_id_out": "604774276317839361",
		"amt_in": "101001",
		"amt_out": "100000",
		"fee": "1001"
	    }
	],
	"last_offset_index": 6
    }

Here two last payments from BLW1 to BLW2 and versa
As you can see other fee is about 0.01% for other forwardings.
But for last two - about 1%

**Comment by Perlover** [comment]
I think problem can be afftected by BLW too. For example it can use old `feerate` gotten from LND but not notified by LND because it's private channel. Other reason can be because the author of BLW waits this: https://github.com/lightningnetwork/lnd/pull/1595 and now BLW uses temporary workaround until this problem will fixed in LND. Now i see that the BLW uses normal fee (0.01%) for same same channel. I don't know - to close ticket ot not.

I think to wait the resolving of the https://github.com/lightningnetwork/lnd/pull/1595 then the author of BLW will remove temporary workaround from BLW and may be i will test it again.

**Comment by btcontract** [comment]
Here's what likely happens:

- BLW opens non-public channels which currently don't get `ChannelUpdate` reliably (https://github.com/lightningnetwork/lnd/issues/1347).
- Until a proper solution is deployed, BLW looks at public `ChannelUpdate`s an LND peer currently has and reconstructs the most probable private `ChannelUpdate`, this has proven to be a working solution.
- BLW only does this once and stores a `ChannelUpdate` for a non-public channel locally.
- After fees are updated on LND side, BLW still stores old values because LND likely does not send an update due to the same issue.

**Comment by Perlover** [comment]
@btcontract told me that this bug should be fixed already. I close this ticket
