### ISSUE TITLE
Crash: FetchChanUpdates

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#2187]
After runnign lnd for quite a long time (more than month I think):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xc8f959]

goroutine 577 [running]:
main.(*chanSeries).FetchChanUpdates(0xc42021c160, 0x72b3f1b60a8ce26f, 0x4ff763ae46a2a6c1, 0x9c085ae165831e93, 0x19d668, 0x44400086506, 0x1790001, 0x1, 0xc4322d1700, 0x405d2b, ...)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/chan_series.go:300 +0x459
github.com/lightningnetwork/lnd/discovery.(*gossipSyncer).FilterGossipMsgs(0xc42014c2d0, 0xc42049f680, 0x19, 0x19)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/discovery/syncer.go:865 +0x88a
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler(0xc420226300)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1185 +0x12c3
created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).Start
        /home/lightning/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:444 +0x19c
```

### Your environment

* version of `lnd`: 0.5.0-beta commit=fb95858afce6d7129758e7677bcb1552c5be2c51
* operating system: Debian stable `Linux <hostname censored> 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64 GNU/Linux`
* `bitcoind -version`: `v0.16.3`
* `lnd` runs under a different user than `bitcoind`

### Steps to reproduce

Unknown, just ran the node

### Expected behaviour

Not crashing

### Actual behaviour

Crash

Sorry if this was filed somewhere already, I didn't find anything similar.

**Comment by wpaulino** [comment]
This is fixed in the [latest release](https://github.com/lightningnetwork/lnd/releases/tag/v0.5.1-beta-rc1).
