### ISSUE TITLE
lnd does not accept bitcoind.rpc* variables in lnd.conf

### ISSUE THREAD

**Issue by oitdmser** [lightningnetwork/lnd#2193]
### Background

I run lnd and bitcoind under their own users on the same physical machine in preparation for having them run on separate physical machines. As part of my setup lnd does not have read privileges to the bitcoind .cookie, so I'm trying to configure lnd to use RPCauth.

### Your environment

* version of `lnd`: commit=v0.5-beta-285-gc3546c280d0e59157848a2e82440bc2ea98bc2a3
* which operating system (`uname -a` on *Nix): Debian Stretch
* version of `btcd`, `bitcoind`, or other backend: v0.17.0.1
* any other relevant environment details

### Steps to reproduce

When I use the following options in my lnd.conf as described in the lnd documentation:

```
bitcoind.rpchost=127.0.0.1:8332
bitcoind.rpcuser=joeblow
bitcoind.rpcpass=superSecretPasswordByRPAUTH.py
bitcoind.zmqpubrawblock=127.0.0.1:28332
bitcoind.zmqpubrawtx=127.0.0.1:28333
```

### Expected behaviour

lnd should run using the RPCauth credentials entered in lnd.conf

### Actual behaviour

lnd errors out:

```
lnd.conf:16: unknown option: bitcoind.rpchost
lnd.conf:17: unknown option: bitcoind.rpcuser
etc
```

lnd runs fine if I specify the above options using the command line like this:

`lnd -bitcoind.rpchost=127.0.0.1:8332 -bitcoind.rpcuser=joeblow ... etc`

This means typing in the RPC password in the command-line and command-line options can be seen by users running 'top' or task manager. This exposes RPC password to users other than 'lnd.' Having RPC password in lnd.conf is moderately more secure because the file can be locked down with chmod.

**Comment by Roasbeef** [comment]
> lnd.conf:16: unknown option: bitcoind.rpchost

Check the rest of your conf for any errors. The parser atm is very forgiving, and doesn't always call out errors as it finds them.

**Comment by oitdmser** [comment]
The '16' in the error corresponds to the line with `bitcoind.rpchost`, so it would seem that is the line that has the error.

If I comment out all lines with `bitcoind.rpc*` lnd loads without errors. Wouldn't that indicate the problem is with the bitcoind.rpc* variables?

**Comment by oitdmser** [comment]
my lnd.conf
```
[Application Options]
debuglevel=info
debughtlc=false
maxpendingchannels=5
alias=WittyAlias
color=#000300
maxlogfiles=3

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
bitcoin.mainnet=1

[autopilot]
autopilot.active=1
autopilot.maxchannels=16
autopilot.allocation=0.1

#RPC Stuff **doesn't seem to work as of 0.5beta**
#instead use at command line or to modify the exec command in the .service file
#rpccookiefile=/tmp/.cookie
#rpchost=127.0.0.1:8332
bitcoind.rpcuser=wittyusername
bitcoind.rpcpass=VerySecretSuperDuperRPCauthPassword
bitcoind.zmqpubrawblock=127.0.0.1:28332
bitcoind.zmqpubrawtx=127.0.0.1:28333


```

**Comment by wpaulino** [comment]
The `bitcoind` specific options need to be under a `[Bitcoind]` tag.

**Comment by oitdmser** [comment]
FIXED. Thank you!

Edited lnd.conf looks like this:
```
[Application Options]
debuglevel=info
debughtlc=false
maxpendingchannels=5
alias=WittyAlias
color=#000300
maxlogfiles=3

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
bitcoin.mainnet=1

[autopilot]
autopilot.active=1
autopilot.maxchannels=16
autopilot.allocation=0.1

[Bitcoind]
bitcoind.rpchost=127.0.0.1:8332
bitcoind.rpcuser=wittyusername
bitcoind.rpcpass=VerySecretSuperDuperRPCauthPassword
bitcoind.zmqpubrawblock=127.0.0.1:28332
bitcoind.zmqpubrawtx=127.0.0.1:28333
```
