### ISSUE TITLE
CloseChannel missing from REST API

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2197]
### Background

The [`CloseChannel` gRPC method](https://api.lightning.community/#closechannel) is not also available via the REST API. Unfortunately this means clients using the REST API can only ever open channels and never close them.

### Your environment

* version of `lnd` — 0.5.0-beta
* which operating system (`uname -a` on *Nix) — macOS 10.13.6
* version of `btcd`, `bitcoind`, or other backend — bitcoind

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Actual behaviour

N/A

**Comment by Roasbeef** [comment]
How are you trying to execute the call? It _is_ indeed exposed in the REST API: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L383 

See also the channels endpoint: https://api.lightning.community/rest/index.html#v1-channels

**Comment by wbobeirne** [comment]
The description on that endpoint:

> AbandonChannel removes all channel state from the database except for a close summary. This method can be used to get rid of permanently unusable channels due to bugs fixed in newer versions of lnd. Only available when in debug builds of lnd.

Led me to believe that that wasn't the same method as offered by the gRPC API, which has this description:

> CloseChannel attempts to close an active channel identified by its channel outpoint (ChannelPoint). The actions of this method can additionally be augmented to attempt a force close after a timeout period in the case of an inactive peer. If a non-force close (cooperative closure) is requested, then the user can specify either a target number of blocks until the closure transaction is confirmed, or a manual fee rate. If neither are specified, then a default lax, block confirmation target is used.

Perhaps it's just misdocumented though.

**Comment by cfromknecht** [comment]
@wbobeirne this issues should be fixed in master, see https://github.com/lightningnetwork/lnd/pull/2150

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/2197#issuecomment-440099187
