### ISSUE TITLE
[Feature request] Structured payment errors

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2201]
### Background

When sending a payment, a failed route can indicate where the failure happened and for what specific reason, with a signed message that can include data about how to address the failure.

This data is currently returned serialized to an unstructured `payment_error` string which makes it harder to work with.

(related PR: https://github.com/lightningnetwork/lnd/pull/1662)

### Your environment

* lnd 0.5.1 rc 2
* MacOS Mojave
* Bitcoin Core 0.17.0

### Steps to reproduce

Send to a route using `sendToRouteSync` and experience an error such as `TemporaryChannelFailure` or `FeeInsufficient`.

### Expected behaviour

The error should return all fields of the backing data structure in a structured form, with an "error type" field, and then individualized error data for each individual error, such as indicating which channel experienced a `TemporaryChannelFailure` or what is the actual expected fee in a `FeeInsufficient` error.

### Actual behaviour

The backing data structure for the error is serialized to an unstructured string which contains the error data context.

**Comment by Roasbeef** [comment]
Related to #1662

**Comment by alexbosworth** [comment]
This seems solved with routerrpc changes

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/2201#issuecomment-526314585
