### ISSUE TITLE
gRPC python ChannelPoint cannot be created (Instance of wrong class)

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2207]
### Background

When trying to close a channel defining a channel point manually, it results in an error since the class ln.ChannelPoint is not properly set. It does however work if taking the output of openChannel (but this is not always available).

### Your environment

* version of `lnd`
lnd version 0.5.1-beta commit=v0.5.1-beta-rc3
* which operating system (`uname -a` on *Nix)
Ubuntu 18.04 4.15.0-39-generic
* version of `btcd`, `bitcoind`, or other backend
btcd version 0.12.0-beta

### Steps to reproduce

 ```
 channel_point = "d6193919b42e2f7a4056d7102c3b781d097d30181249b525452999f6ed9a58bb:0"
   _channel_point = ln.ChannelPoint
   print "see here:", type(_channel_point)
   _channel_point.funding_txid_str=channel_point.split(":")[0]
   _channel_point.output_index=channel_point.split(":")[1]

    request = ln.CloseChannelRequest(
        channel_point=_channel_point,
        # force=<bool>,
        # target_conf=<int32>,
        # sat_per_byte=<int64>
    )
    response = stub.CloseChannel(request, metadata=[('macaroon', macaroon)])
    print response
```

### Expected behaviour

`{ 
    "close_pending": <PendingUpdate>,
    "confirmation": <ConfirmationUpdate>,
    "chan_close": <ChannelCloseUpdate>,
}`

### Actual behaviour

`TypeError: Parameter to MergeFrom() must be instance of same class: expected lnrpc.ChannelPoint got GeneratedProtocolMessageType.`

**Comment by ranchalp** [comment]
```
$> python --version
Python 2.7.15rc1
$> pip list 
googleapis-common-protos (1.5.3)
grpcio (1.16.0)
grpcio-tools (1.16.0)
```

**Comment by ranchalp** [comment]
```python --versionPython 2.7.15rc1pip list googleapis-common-protos (1.5.3)grpcio (1.16.0)grpcio-tools (1.16.0)```

**Comment by ranchalp** [comment]
```python --versionPython 2.7.15rc1pip list googleapis-common-protos (1.5.3)grpcio (1.16.0)grpcio-tools (1.16.0)```

**Comment by Roasbeef** [comment]
I'm unable to reproduce with my instance of Python 2.7. Does this resolve your issue: https://stackoverflow.com/a/50477383 ?

**Comment by ranchalp** [comment]
```
$> python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpc_pb2 as ln
import rpc_pb2 as ln
>>> ln.ChannelPoint
<class 'rpc_pb2.ChannelPoint'>
>>> channel_point = "d6193919b42e2f7a4056d7102c3b781d097d30181249b525452999f6ed9a58bb:0"
channel_point = "d6193919b42e2f7a4056d7102c3b781d097d30181249b525452999f6ed9a58bb:0"
>>> _channel_point = ln.ChannelPoint
>>> print "see here:", type(_channel_point)
see here: <class 'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType'>
```

It does not really. If you follow the same steps it shows the proper type?

**Comment by wpaulino** [comment]
> \>\>\> _channel_point = ln.ChannelPoint

The type needs to be defined as `ln.ChannelPoint()`, otherwise you're making a type alias.

```
Python 2.7.15 (default, Jul 23 2018, 21:27:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpc_pb2 as ln
>>> ln.ChannelPoint
<class 'rpc_pb2.ChannelPoint'>
>>> type(ln.ChannelPoint)
<class 'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType'>
>>> _channel_point = ln.ChannelPoint
>>> type(_channel_point)
<class 'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType'>
>>> __channel_point = ln.ChannelPoint()
>>> type(__channel_point)
<class 'rpc_pb2.ChannelPoint'>
```
