### ISSUE TITLE
lnd --version returns wrong info for release v0.5.1-beta-rc1 binaries

### ISSUE THREAD

**Issue by lispmeister** [lightningnetwork/lnd#2209]
### Background
Calling "lnd --version" on a v-0.5.1-beta-rc1 binary returns "lnd version 0.5.0-beta commit"
The release binary returns the wrong version string.

### Your environment
The lnd is running on an Odroid HC2

* version of `lnd`
lnd version 0.5.0-beta-rc1

* which operating system (`uname -a` on *Nix)
Linux XXXXXX 4.14.78-150 #1 SMP PREEMPT Tue Oct 23 10:43:36 -03 2018 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
bitcoind --version
Bitcoin Core Daemon version v0.17.0.1

* any other relevant environment details

### Steps to reproduce
Run "/usr/local/bin/lnd --version".

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
The correct version of the build should be returned: "lnd version 0.5.1-beta-rc1 commit"

### Actual behaviour
The version string "lnd version 0.5.0-beta commit" is returned.

**Comment by halseth** [comment]
Version information is not always updated before the final version is tagged. In this case the version was bumped in `rc2`.
