### ISSUE TITLE
GitBash: [lncli] The handle is invalid.

### ISSUE THREAD

**Issue by CarlosMassiah** [lightningnetwork/lnd#2213]
### Background
Error:
Input wallet password: [lncli] The handle is invalid.

Happens for any input using lncli in GitBash on Windows. This is a similar issue to https://github.com/lightningnetwork/lnd/issues/498

The work around is to open CMD and do the unlock/create command in there, then return to the bash terminal. 

### Your environment

* lnd 0.5 (also occurs in previous verions)
* Windows
* Git bash

### Steps to reproduce

1) Have a windows machine with Git bash installed.
2) Acquire lnd and lncli 
3) >lncli unlock
4) See error.

**Comment by molxyz** [comment]
@CarlosMassiah hi,

>The work around is to open CMD and do the unlock/create command in there, then return to the bash terminal.

If the CMD can create/unlock password, why do you return to the bash terminal?  You can use the cmd.exe to run LND and do queries on the node, that's what I've been doing.
