### ISSUE TITLE
Code Contribution Guidelines should reference Lightning RFC

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#2214]
In `docs/code_contribution_guidelines.md#ReqReading` the original LN whitepaper is listed. Furthermore, there is a link to https://medium.com/@lightningnetwork/lightning-network-meeting-on-interoperability-and-specifications-ea49e47696a4 (Version 1 specification). I think the RFC at https://github.com/lightningnetwork/lightning-rfc should be listed in addition (or as a replacement).

**Comment by Roasbeef** [comment]
Went this replacing the blog post all together since it's so dated.
