### ISSUE TITLE
Invalid handshake every 60 seconds

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#2216]
2018-11-25 20:14:50.338 [ERR] CMGR: Can't accept connection: unable to accept connection from 10.34.0.82:32940: Act One: invalid handshake version: 71, only 0 is valid, msg=474554202f20485454502f312e310d0a557365722d4167656e743a206375726c2f372e33352e300d0a486f73743a20313139

Which is odd... because the IP is a private IP... one that doesn't exist on my network.  It should be impossible for my system to even see any traffic 10.*.*.*.

This message appears every 60 seconds, except the port is different each time.  I've stopped LND and updated from 5.0 to the latest, and still getting the error.

**Comment by Roasbeef** [comment]
This isn't an lnd related error, and is usually someone trying to port scan your node. Say they try to probe for an HTTPS server at that port, we'll fail the handshake as we're expecting the `brontide` handshake. 

Which version were you running prior? (also it's helpful if you fill in the issue template as it avoids back and forth to obtain basic information) 

What other processes do you have running on the machine? Are you running behind a proxy?

**Comment by ZapUser77** [comment]
"Which version were you running prior?"
"updated from 5.0 to the latest," It was the released 5.0 version

It's running on Raspberry PI with absolutely nothing else running.
It's not on a 10.* network, and since 10.* is not a routable IP... it should be impossible for the node to encounter any device with 10.* IP address.

It is running through a VPN, but neither the local, nor remote IP is running on the 10.* network.

Thanks.

**Comment by ZapUser77** [comment]
Ok, it looks like the VPN does assign a 2nd local address in the 10. network.  The IP address listed is the "local" address of the server itself.

This only started happening (or being reported) since 5.0.

**Comment by ZapUser77** [comment]
I don't think this has anything to do with LND (or could be cured by it).  Thanks.

**Comment by ZapUser77** [comment]
Contacted the VPN service, it's a known issue on their end.

**Comment by ZapUser77** [comment]
Ok... the "known issue" was that the source was showing up as a 10.* IP.

The problem is coming from a Lightning Node... 
[ERR] CMGR: Can't accept connection: unable to accept connection from 5.189.141.242:54673: Act One: invalid handshake version: 71

**Comment by cfromknecht** [comment]
71 is "G", it's most likely an HTTP GET request that's hitting your LN port

**Comment by ZapUser77** [comment]
Thanks.  It was coming from another lightning node, that I did not have a channel with, nor was connected to... But it has since ceased.

Thanks.
