### ISSUE TITLE
LND report different channel point OutputIndex value between OpenChannel and ListChannels operations

### ISSUE THREAD

**Issue by federicobond** [lightningnetwork/lnd#2219]
### Background

When opening a channel that references a channel point with 1 as its output index, OpenChannel reports 0 instead. Performing a ListChannels request after opening it reports the output index correctly.

### Your environment

* `lnd 0.5.1-beta-rc3`
* macOS 10.14.1
* btcd version 0.12.0-beta

### Steps to reproduce

This is probably dependent on the UTXO set that the embedded wallet manages and the resulting funding TX, so I haven't found an easy way to reproduce it for others.

### Expected behaviour

OpenChannel should report the output index as 1, consistent with the response from ListChannels in both nodes.

### Actual behaviour

OpenChannel reports the OutputIndex for the channel point as 0.

**Comment by Roasbeef** [comment]
Are you using `OpenChannelSync`?

**Comment by Roasbeef** [comment]
Should be fixed #2221

**Comment by federicobond** [comment]
Yes, I was using OpenChannelSync. Thanks for the quick resolution!
