### ISSUE TITLE
lnd fills tmpfs->/tmp  

### ISSUE THREAD

**Issue by Wolf-Raider** [lightningnetwork/lnd#2226]
### Background

Hi,
I noticed something with lnd, where I think this could be an issure:
On my Raspberry, i noticed someting is filling up my /tmp tmpfs partition. 
I have 500MB of RAM for my tmpfs which get filled by 16 MB/h from the LND process. 
So after a few days tmpfs is full. LND is continuing running normal, but apt-get update etc. will fail then.

Can someone explain what is written frum the LND process? Is it needed? Can i disable this function?   

### Your environment

LND 5 Beta on Pi2 (minibian image) 
only lnd / bitcoind running

**Comment by wpaulino** [comment]
`lnd` _should_ only write data within its configured directories (see `--lnddir`, `--datadir`, `--logdir` in `lnd --h`), so if you have any of those set to point to `/tmp`, then that would explain it.

**Comment by Roasbeef** [comment]
We end up rotating the logs, which can cause some churn there. You can also turn that off. I'd check your dirs as hinted above.

**Comment by halseth** [comment]
Relevant options are 
```
      --lnddir=    The base directory that contains lnd's data, logs, configuration file, etc. (default: ~/Library/Application Support/Lnd)
      --configfile=    Path to configuration file (default: ~/Library/Application Support/Lnd/lnd.conf)
  -b, --datadir=    The directory to store lnd's data within (default: ~/Library/Application Support/Lnd/data)
      --logdir=    Directory to log output. (default: ~/Library/Application Support/Lnd/logs)
      --maxlogfiles=    Maximum logfiles to keep (0 for no rotation) (default: 3)
      --maxlogfilesize=     Maximum logfile size in MB (default: 10)
```

**Comment by Wolf-Raider** [comment]
Hi, thanks for your answers.
I checked all settings in lnd.conf. I didn't set anything so it should run with the default settings.
My LND dir is /mnt/PIHDD/LightningData/ there i find /data /logs etc. However, in /Logs there is only one file called bitcoin.  With -maxlogfiles=3 shouldn't there be 3 files?

I set now the logging level in LND.conf to 'Error' (from Debug), than my usage of /tmp folder isn't raising up in the former huge speed.  

Is there a command to check which paths lnd is using? With them above, I could only set them.

**Comment by wpaulino** [comment]
> However, in /Logs there is only one file called bitcoin

This is actually a directory, which contains the logs for the different networks (mainnet, testnet, etc).

> I checked all settings in lnd.conf. I didn't set anything so it should run with the default settings

In that case, there might be something else running on your system that's writing to it. Can you tell what exactly is being written to the partition?
