### ISSUE TITLE
Improper use of `FinalIncorrectCltvExpiry`

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lnd#2227]
### Background

I'm investigating https://github.com/ACINQ/eclair/issues/758, user keeps getting `FinalIncorrectCltvExpiry` from various `lnd` nodes. For example it happens with a direct channel to yalls. After looking into `eclair` source code, it seems we are correctly building the onion and I don't see why such an error should nereturned.

### Expected behaviour

This error should only be used when there is a mismatch between the cltv value in the htlc and the value for the next hop in the onion for the last node. By convention they should be equal.

### Actual behaviour

It seems that in the below code `lnd` returns a `FinalIncorrectCltvExpiry` when the last cltv value is less than an expected height. I think in that case it should return `FailFinalExpiryTooSoon` instead. I believe the onion is indeed properly formatted, but the user's bitcoind is out of sync.

https://github.com/lightningnetwork/lnd/blob/42c45979215e3242ef2e162ccd9de3cbb0ed28a1/htlcswitch/link.go#L2397-L2411

**Comment by Roasbeef** [comment]
That section you link to is checking the _onion payload_, not the HTLC.

**Comment by Roasbeef** [comment]
Here's where we send the too soon error: https://github.com/lightningnetwork/lnd/blob/42c45979215e3242ef2e162ccd9de3cbb0ed28a1/htlcswitch/link.go#L2286

**Comment by pm47** [comment]
> That section you link to is checking the onion payload, not the HTLC.

Sure, but it seems that you are checking the onion value against a `expectedHeight`, whereas my understanding of the spec is that you should only make sure that it is equal to the `cltvExpiry` of the last htlc in the route.

In other words:
- if `lastHtlc`.`cltvExpiry` < `expectedHeight`
  return `FinalExpiryTooSoon`
- if `lastHtlc`.`cltvExpiry` != `onion`.`outgoingCltv`
  return `FinalIncorrectCltvExpiry`
- if `lastHtlc`.`cltvExpiry` >= `expectedHeight` && `onion`.`outgoingCltv` == lastHtlc.cltvExpiry 
  OK

Currently the sender receives a `FinalIncorrectCltvExpiry` but I *think* that what you really meant is `FinalExpiryTooSoon`.

**Comment by Roasbeef** [comment]
Ah you're correct! Will fix that shortly, thanks!

**Comment by viaj3ro** [comment]
has there been any progress?
