### ISSUE TITLE
LND sends an incoming HTLC which would exceed local `maxHtlcValueInFlightMsat`

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2232]
### Background

BLW user attempted to send and receive a number of HTLCs through a channel with LND node and some of outgoing HTLCs got stuck, a bit later LND attempted to fulfill one of BLW's payment requests but doing so exceeded a local `maxHtlcValueInFlightMsat`.

BLW `maxHtlcValueInFlightMsat` is set to `4000000 SAT`, LND `maxHtlcValueInFlightMsat` is set to `14850000 SAT`, BLW has 7 stuck outgoing HTLCs with total sum of `5783057 SAT` which already exceeds local in-flight limit, which is fine since when sending we only take into account a remote limit (right?).

As far as I understand LND should not attempt to fullfill any of BLW's requests until total in-flight sum gets below `4000000 SAT` but it does.

### Your environment

0.5.1-beta commit=v0.5.1-beta-rc4

**Comment by btcontract** [comment]
On a slightly related node, I've just tried to remove local `maxHtlcValueInFlightMsat` check to let an incoming HTLC get fulfilled but LND sends a `commit_sig` which BLW thinks is invalid. I guess we can deal with that once this one is settled.

**Comment by cfromknecht** [comment]
@btcontract thanks for the report!

> which is fine since when sending we only take into account a remote limit (right?).

Yes it will only apply the remote limit.

> As far as I understand LND should not attempt to fullfill any of BLW's requests until total in-flight sum gets below 4000000 SAT but it does.

The limits are directional; BLW can only offer 14850000 sat in-flight, and LND can only offer 4000000 sat. If the final payment from LND to BLW was below 4000000 sat, I think this is expected?

**Comment by cfromknecht** [comment]
From [BOLT 02](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-9):

> if the sum of total _offered_ HTLCs would exceed the remote's max_htlc_value_in_flight_msat:
>   - MUST NOT add an HTLC.

**Comment by btcontract** [comment]
Indeed, thanks for explanations. BLW gets it wrong here by checking a total in-flight amount.
