### ISSUE TITLE
listchaintxns has invalid item (zero ammout, destinations...)

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#2238]
### Background

This is my latest entry in `lncli listchaintxns` output:
```
        {
            "tx_hash": "4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942",
            "amount": "0",
            "num_confirmations": 0,
            "block_hash": "",
            "block_height": 0,
            "time_stamp": "1543390517",
            "total_fees": "0",
            "dest_addresses": [
            ]
        }
```
Zero amount, confirmations, destination addresses...

Meanwhile, my local `bitcoin-cli -datadir=/home/bitcoin/.bitcoin/ getrawtransaction 4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942 1` states:
```
...
  "hex": "02000000000101c609c446e7b5652e08f87f652c1c78680fc7f259a3862a192973453e69d41ba80100000000ffffffff01c76203000000000016001490a8cfe2049807f74b2dfc3b16e6fd1dd91816b60400473044022009044a5990ba1301ec213e4d90d0e13967df9df771022714cd62990d8f401f0f022005518c9a698b9e737b75260336cfa32004f4580b7403d8416b059813fdc644c30147304402204a679c7b91df277377158cb33155656e0d7fbea70b1b9fa535e16d18f5105ddd02206fae1e31e9120971482a2bfb667c810d1e6f487492c8c9ded3d79384b19423590147522102217144a276369ea0767b690a73c755efcd97c132dadc512adaf3d488394ae4e82103e9df0c8bd28d59d9158d9d33065c38a0a9f5f5717deb36f0e742f1fb9418443752ae00000000",
  "blockhash": "000000000000000000167474485fa5509851c0fe423347463fce5fd9b199c747",
  "confirmations": 61,
  "time": 1543391341,
  "blocktime": 1543391341
```
LND logs:
```
# fgrep 4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942 /home/lnd/.lnd/logs/bitcoin/mainnet/lnd.log
2018-11-28 09:35:17.593 [INF] LNWL: Inserting unconfirmed transaction 4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942
2018-11-28 09:35:18.028 [INF] PEER: Waiting for confirmation of cooperative close of ChannelPoint(a81bd4693e457329192a86a359f2c70f68781c2c657ff8082e65b5e746c409c6:1) with txid: 4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942
2018-11-28 09:35:18.071 [INF] NTFN: New confirmation subscription: txid=4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942, numconfs=1
2018-11-28 09:49:23.698 [INF] NTFN: Dispatching 1 conf notification for 4a5daa5d86879904e9efe852937513df76362b133162ca1284d6e24d37ca6942
```
### Your environment

* version of `lnd` `0.5.0-beta commit=v0.5-beta-295-gb6009850635cf966eb3bd637de5da89cb9262589`
* Linux odroid-hc1 4.9.0-8-armmp-lpae #1 SMP Debian 4.9.130-2 (2018-10-27) armv7l GNU/Linux
* /Satoshi:0.17.0/ (mainnet)

### Steps to reproduce

Unknown

### Expected behaviour

Item in `listchaintxns` should contain non-zero amounts, confirmations, etc.

**Comment by Roasbeef** [comment]
It isn't invalid per say, it's just that we use the wallet to store transactions that don't actually belong to it. The wallet is meant to track transactions that send to it via a change address, or directly. In certain circumstances, we'll give it a transaction where no outputs at all belong to it. In this case it tries to parse out the fees it paid and where it sent funds to, but these are all script hash addresses. In your case, a co-op close happened, where we didn't have an output address.

**Comment by Talkless** [comment]
> in your case, a co-op close happened

Oh, so basically all funds was on remote side (from my point of view), so no coins had to go to my wallet? Thanks @Roasbeef .
