### ISSUE TITLE
describegraph output does not reflect own channel just created

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2241]
### Background

Just created a channel in a local simnet between two nodes. Not only did a third node not find such channel in `describegraph` after some minutes (how to force an update?), but also the node that created the channel itself does not reflect such channel in its `describegraph` (its own just created channel that does show up on `listchannels`).

### Your environment

lnd version 0.5.1-beta commit=v0.5.1-beta-rc4-13-gb07499f227bd78dbceaa8c6ee047f1c033716cdf
4.15.0-39-generic #42-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
btcd version 0.12.0-beta
### Steps to reproduce

1- Create channel with node (`openchannel`), 
2- Verify channel confirmed (not in `pendingchannels` and yes in `listchannels`)
3- Try to see after some time from a third node (either searching in the output of `describegraph` or directly through `getchaninfo <channel_id>`
4- Try to see from the creating nodes themselves (same procedure)

### Expected behaviour

At least the creating nodes should have its own confirmed channel in `describegraph` and as the output of `getchaninfo`. There should also be a way to force updating the graph with neighbors for a third node. After some small about of time, connected peers should also have it in their `describegraph` and through `getchaninfo`

### Actual behaviour

Creating nodes can see the channel through `listchannels` and `getchaninfo`, but it does not show up on `describegraph`. Directly connected peers can not see it by any method after some minutes.

```
$>lncli-simnet-charlie getinfo | grep pubkey
    "identity_pubkey": "02bf11de672ee987cd0ecb77329476615ca7d265eb680cd22ce54873cab6f1001b",

$>lncli-simnet-bob openchannel --node_key="02bf11de672ee987cd0ecb77329476615ca7d265eb680cd22ce54873cab6f1001b" --local_amt=50000 --push_amt=5000
{
	"funding_txid": "217708f9838d6a66b23d82b1dcc1981124c68c755c689fd83f69ed8ee90c2550"
}
[... wait till not in pendingchannels and yes in listchannels ...] 
$>lncli-simnet-bob describegraph | grep "217708f9838d6a66b23d82b1dcc1981124c68c755c689fd83f69ed8ee90c2550"
[Nothing]
$> lncli-simnet-bob listchannels
    "channels": [
        {
            "active": true,
            "remote_pubkey": "02bf11de672ee987cd0ecb77329476615ca7d265eb680cd22ce54873cab6f1001b",
            "channel_point": "217708f9838d6a66b23d82b1dcc1981124c68c755c689fd83f69ed8ee90c2550:0",
            "chan_id": "31345976996331520",
            "capacity": "50000",
            "local_balance": "35950",
            "remote_balance": "5000",
            "commit_fee": "9050",
            "commit_weight": "724",
            "fee_per_kw": "12500",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
$> lncli-simnet-alice getchaninfo 31345976996331520
[lncli] rpc error: code = Unknown desc = edge not found

[same with lncli-simnet-charlie, the other node in the channel]
[and from a third node such as lncli-simnet-alice]

**Comment by wpaulino** [comment]
How many blocks are you mining? Channels won't be added to the graph until they have reached 6 confirmations.

**Comment by ranchalp** [comment]
If the channel si in the output of `listchannels` and not in the output of `pendingchannels`, isn't this a sign that it already got 6 confirmations? I will repeat it now reporting blocks mined.

**Comment by ranchalp** [comment]
Correct. It was after **3 blocks** that it appeared in describegraph (including that of the neighbor).

```
$>lncli-simnet-bob openchannel --node_key="02bf11de672ee987cd0ecb77329476615ca7d265eb680cd22ce54873cab6f1001b" --local_amt=50000 --push_amt=5000
<265eb680cd22ce54873cab6f1001b" --local_amt=50000 --push_amt=5000
{
	"funding_txid": "abd513b9a40557fc37ceab623ae286699c15a4c9f1b570abdcc0cbf1d5e84e07"
}

$> btcctl --simnet generate 2
   [...]
$> lncli-simnet-bob pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02bf11de672ee987cd0ecb77329476615ca7d265eb680cd22ce54873cab6f1001b",
                "channel_point": "abd513b9a40557fc37ceab623ae286699c15a4c9f1b570abdcc0cbf1d5e84e07:0",
                "capacity": "50000",
                "local_balance": "35950",
                "remote_balance": "5000"
            },
            "confirmation_height": 0,
            "commit_fee": "9050",
            "commit_weight": "724",
            "fee_per_kw": "12500"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

$> btcctl --simnet generate 1
   [...]
$> lncli-simnet-bob pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

$> lncli-simnet-bob listchannels | grep 31427340856852480 #now in the blockchain
            "chan_id": "31427340856852480",
$> lncli-simnet-bob describegraph | grep 31427340856852480 

$> btcctl --simnet generate 1 #1block since in blockchain
   [...]
$> lncli-simnet-bob describegraph | grep 31427340856852480

$> $> btcctl --simnet generate 1 #2blocks since in blockchain
   [...]
$> lncli-simnet-bob describegraph | grep 31427340856852480

$> btcctl --simnet generate 1 #3blocks since in blockchain
   [...]
$> lncli-simnet-bob describegraph | grep 31427340856852480 #it appears on describegraph
            "channel_id": "31427340856852480",
$> lncli-simnet-charlie describegraph | grep 31427340856852480
            "channel_id": "31427340856852480",
$> lncli-simnet-alice describegraph | grep 31427340856852480 #even for neighbours
            "channel_id": "31427340856852480",
```

It was **not 6 but 3 blocks**,

**Comment by ccdle12** [comment]
repeated the above experiment, can confirm on my simnet environment that `describegraph` shows the node after only **3 blocks** and the channel as active when calling `listchannels`, maybe just a simnet issue?

**Comment by wpaulino** [comment]
This is not an issue and is working as intended. Channels must reach a significant number of confirmations (in this case 6) before announcing them due to chain reorgs. This announcement has nothing to do with how the channel itself works. After 3 confirmations (which is the default and cannot be modified at the moment) the channel will become active for both parties and they can begin transacting.

**Comment by halseth** [comment]
@wpaulino Shouldn't `describegraph` only include announced channels (in case `--include_unannouncend=false), which should be after 6 confs?

**Comment by halseth** [comment]
@ranchalp Looking at your logs it looks like you actually are mining 6 blocks before it appears in `decribegraph` (not 3 as you write). This is the expected behaviour.

**Comment by ranchalp** [comment]
@halseth it is not 6 but 3 blocks. The channel did not get in the blockchain until block 28606 (when it stopped being in `pendingchannels` and started being in `listchannels`). 3 Blocks later, at block 28609, both nodes' `describegraph`, and 3rd party's `describegraph` could see the channel (i.e. the channel is active).

**Comment by halseth** [comment]
@ranchalp It goes from `pendingchannels` to `listchannels` after 3 blocks.

**Comment by ranchalp** [comment]
@halseth What is the purpose of `confirmation_height` in `pendingchannels`? because, assuming what you said is correct, I still got a value of `confirmation_height: 0` in the first 3 blocks (while the channel was still in `pendingchannels`), and that is why I thought the channel was not included in the blockchain until the 4th block (when it was not in `pendingchannels` but yes in `listchannels`).

**Comment by halseth** [comment]
Yeah, it is not currently being set, there's a TODO: https://github.com/lightningnetwork/lnd/blob/640fe2558b9b812f812fe1591dfc564037abb470/rpcserver.go#L1796

**Comment by ranchalp** [comment]
My apologies then.

**Comment by halseth** [comment]
No worries, I get that that unused field is confusing! 😀
