### ISSUE TITLE
dockerfile deps

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#2256]
### Background

lnd docker build fails for: https://github.com/lightningnetwork/lnd/blob/master/Dockerfile

### Steps to reproduce

from the lnd root: `docker build .`

### Expected behaviour

should build without failure

### Actual behaviour
fails with the following error:

```make: *** [Makefile:107: build] Error 2
The command '/bin/sh -c apk add --no-cache     git     make &&  git clone https://github.com/lightningnetwork/lnd /go/src/github.com/lightningnetwork/lnd &&  cd /go/src/github.com/lightningnetwork/lnd &&  make &&  make install' returned a non-zero code: 2
```

**Comment by yancyribbens** [comment]
fix is here: https://github.com/lightningnetwork/lnd/pull/2257

**Comment by adler99** [comment]
Hi, I had a different issue with the current Dockerfile. Seems like no dependencies got downloaded:
> \033[0;32m Building debug lnd and lncli.\033[0m
> GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-106-g349551373d7fd571c2a917908e7155c6c6f9706a" github.com/lightningnetwork/lnd
> nat/upnp.go:9:2: cannot find package "github.com/NebulousLabs/go-upnp" in any of:
> 	/usr/local/go/src/github.com/NebulousLabs/go-upnp (from $GOROOT)
> 	/go/src/github.com/NebulousLabs/go-upnp (from $GOPATH)
> ...

fixed it locally by adding
`go get -d ./...` before the make command
I guess dependencies should be handled in the make file, so it's more a hack than a solution. Hope it helps someone!

**Comment by yancyribbens** [comment]
@adler99 did you run build from / or /docker?

**Comment by adler99** [comment]
I added the following to the Dockerfile:
`&& go get -d ./...`
`RUN cd  /go/src/github.com/lightningnetwork/lnd && make ...` 
I needed to add cd again, I guess go get changes the directory...

And then those commands run smoothly:
build the image:
`docker build -t lnd . --no-cache`
create the container:
`docker create --link bitcoin-server --name=lnd -v ${PWD}/data:/root/.lnd -p 9735:9735 -p 10009:10009 lnd:latest`

**Comment by halseth** [comment]
Fixe by https://github.com/lightningnetwork/lnd/pull/2257
