### ISSUE TITLE
Periodically resolve `externalip` if set to domain name

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#2262]
### Background

My lnd.conf is
```
[Application Options]
debuglevel=debug
minchansize=30000
maxpendingchannels=10
externalip=xxxxx.ddns.net:9735
alias=my-alias
restlisten=0.0.0.0:8081
listen=0.0.0.0:9735
maxlogfiles=0
maxlogfilesize=100
debuglevel=debug

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=localhost
bitcoind.rpcuser=xxxxx
bitcoind.rpcpass=xxxxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:29000
bitcoind.zmqpubrawtx=tcp://127.0.0.1:29001
```

### Your environment

* version of `lnd`
```
lnd version 0.5.1-beta commit=v0.5.1-beta-rc3-2-g712fc3ebed1c9e0df6bad2b240acce1a0804b1d2
```

* which operating system (`uname -a` on *Nix)
```
Fedora release 28 (Twenty Eight)
Linux  4.19.2-200.fc28.x86_64 #1 SMP Wed Nov 14 20:58:35 UTC 2018 x86_64 x86_64 x86_64
 GNU/Linux
```

* version of `btcd`, `bitcoind`, or other backend

```
Bitcoin Core RPC client version v0.17.99.0-d26278988
```

### Expected behaviour

```lnd``` should detect external DNS changes periodically and send channel announcements automatically, without forcing me to use NAT traversal. Every X minutes, it should resolve the external domain name and compare with the last IP used and send updates in case needed.

### Actual behaviour

External DNS changes, lnd does not send node announcement with the new IP unless I restart it manually.

**Comment by halseth** [comment]
Related: https://github.com/lightningnetwork/lnd/issues/274, https://github.com/lightningnetwork/lnd/issues/2005

**Comment by Roasbeef** [comment]
> Every X minutes, it should resolve the external domain name and compare with the last IP used and send updates in case needed.

It has no awareness of DNS at all, we only advertise IP addresses on the network.

**Comment by gustavonalle** [comment]
@Roasbeef Currently it resolves the DNS configured in  ```externalip``` to an ip, so we just to do it periodically rather than on startup only

**Comment by gustavonalle** [comment]
I'd like to take a stab at this, seems a good issue for first time contributors?

**Comment by wpaulino** [comment]
Sure! Changed the title to better reflect the issue.

**Comment by jnaulty** [comment]
any progress on this?

**Comment by seth586** [comment]
+1, would like to use a VPN for inbound clearnet connections, VPN server constantly changes but their dns service would fix this!

**Comment by cfromknecht** [comment]
@jnaulty @seth586 i think this PR should cover it? https://github.com/lightningnetwork/lnd/pull/4281
