### ISSUE TITLE
Return `color` from getInfo

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2268]
### Background

This is quite minor, but when bootstrapping an application that would want to know the auth'd node's color (e.g. for some kind of identification or UI customization,) you have to call `/v1/getinfo` or `lightning.getInfo()`, get the node's public key, and then call `/v1/graph/node/{pub_key}` or `lightning.getNodeInfo({ pub_key })` to get the color. It would be nice if `color` was one of the properties that came back from getinfo to spare the extra request.

As an aside, while I personally have not had a use for either yet, this also appears to be true for the `addresses` array and `last_update`.

### Your environment

* version of `lnd` — 0.5.1
* which operating system (`uname -a` on *Nix) —  macOS
* version of `btcd`, `bitcoind`, or other backend — bitcoind

**Comment by halseth** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/2312
