### ISSUE TITLE
Can't connect to gRPC with external IP 

### ISSUE THREAD

**Issue by kasadawa** [lightningnetwork/lnd#2269]
### Background

I want to access gRPC with external ip.

here is my lnd.conf

[Application Options]
externalip=87.227.XXX.XX
alias=XXXXXXXXX
color=#3399FF

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=XXXXXXXX
bitcoind.rpcpass=XXXXXXXXXX
bitcoind.zmqpubrawblock=XXXXXXXX
bitcoind.zmqpubrawtx=XXXXXXXX

I had tried with the localhost:10009 and it's working but I need to figure out how and on which port to make it work with the external IP 87.227.XXX.XX . 

I don't know if I need to explicitly to config this option, but I didn't find any doc. 

Testing on my LAN . 

Here are my LND LISTEN TCP connections. 

<img width="661" alt="screen shot 2018-12-04 at 10 44 25 am" src="https://user-images.githubusercontent.com/11670959/49429816-2746f080-f7b2-11e8-850f-3d804ba50e3f.png">

### Your environment
 OSX

* version of `lnd` : 0.5.0-beta 
* which operating system : OSX
* version of bitcoind : v0.17.0.1

### Actual behaviour

Can't use gRPC with external IP .

**Comment by neogeno** [comment]
Needs to have a rpclisten parameter for 0.0.0.0 and also tlsextraip for your external IP

**Comment by alexbosworth** [comment]
And you'll need to regenerate your by deleting them and restarting lnd if you set a tlsextraip

**Comment by Roasbeef** [comment]
Closing based on the responses above.
