### ISSUE TITLE
[listchannels] fix unsettled_balance

### ISSUE THREAD

**Issue by cfromknecht** [lightningnetwork/lnd#2274]
There is a currently-unused field on `listchannels`, named `UnsettledBalance`, which I believe is meant to display the sum of all outstanding pending htlcs. Turns out, the field is actually 2 years old and been hiding in plain sight, but I just noticed it today 🤣

Currently this field will always contain 0, as we don't modify the field in the response message. To make the field accurate, it should include the sum of the [HTLC amounts](https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L2154) contained in the `PendingHTLCs` field.

**Comment by ccdle12** [comment]
would be happy to take up this issue

**Comment by cfromknecht** [comment]
Thanks again @ccdle12!

**Comment by ccdle12** [comment]
No worries! @cfromknecht , happy to have picked it up
