### ISSUE TITLE
Feature request: source pegging in query routes

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2282]
### Background

Sometimes I want to pay to destination C but only if my payment goes through peer B. It would be great to have a way to add this constraint to the routing query.

Potential reasons for this:

1. I want to pay back to myself, through a channel where I have already spent down
2. Peer B is my friend and I want to include him in my payments
3. I want more information on a new peer to see how effectively they route for me

### Your environment

* lnd 0.5.1
* MacOS Mojave
* Bitcoin Core 0.17.0

### Steps to reproduce

1. Issue a queryroutes request
2. Routing results do not route through a desired node

### Expected behaviour

I want the set of route results to always include a route going through a desired edge.

### Actual behaviour

Routes returned don't include my desired hop.

**Comment by Bluetegu** [comment]
I'll try to address this.

**Comment by wamde** [comment]
When using `QueryRoutes` in [rebalance-lnd](https://github.com/C-Otto/rebalance-lnd), we run into  limitations which could be addressed by adding several parameters and constraints to the current path finding:
## Find routes from any to any, with multiple selections
Let's say I want to add fund to one of my channels, I can QueryRoute to the other node's pubkey, easy.
But when I want to empty a certain channel, I don't really care which of my channels may receive it (I may have several candidates for that), what matters is that the outgoing channel (or the pubkey of the remote node) is forced. We currently do that by filtering the results we get from QueryRoutes, which is less than optimal :)
This is also useful to do fee optimisation: I see that I am a lot more likely to be selected as a routing node by the current lnd source routing algorithm if:
1/ I have low fees
2/ I provide a short path (to not suffer from the other nodes' fees)
If I could, with my local knowledge of the network (omniscient for now, but how is it going to last I don't know), compute routes and fees from any node to any node in the network, I could position myself as a competitor by lowering my fees on certain channels on competitive routes, establish new channels to short circuit big nodes or increase my fees on monopoly routes.

## Specify the minimum capacity of channels along the route
Today, this value is implicitly taken as amt_forwarded + whatever fees. This implies that the channels are all nicely lined up and fully loaded in one direction, which is not likely, and even less likely when people actively rebalance their channels. It would be nice to specify which channel capacity we would like to go for at minimum, AND what is the amount (to have amt forwarded and fees automatically calculated too). Typically I would use minimum_capacity =~ 2x amount

## Include a certain node/channel in the route
As mentioned above by Alex.

## Exclude a certain node/channel
Either I don't want to imbalance my own channel for some reason, or I want to circumvent some node/channel for another reason. Again, this can be done by filtering out the results of QueryRoutes downstream, but it is terribly inefficient and fairly easy to do in the KSP algorithm I reckon.

**Comment by Bluetegu** [comment]
I updated the PR. It now allows pegging of nodes and channels leading to nodes, and CLI is working. Help verifying that it is a useful feature would be great.

**Comment by C-Otto** [comment]
How does this relate to https://github.com/lightningnetwork/lnd/pull/2572?

**Comment by wpaulino** [comment]
#2572 makes the first hop go through the given channel, while this seems to be at any hop.

**Comment by alexbosworth** [comment]
This is actually possible now with the source pub key argument in query routes

Just specify a source pub key and prepend the hop or hops you want to the start

**Comment by Roasbeef** [comment]
Implemented as part of
