### ISSUE TITLE
Failure Setting up LND using Docker 

### ISSUE THREAD

**Issue by NourGritli** [lightningnetwork/lnd#229]
Hello everyone , 
I was trying to create a lightening network cluster (using Docker as described in your Readme file ) but i keep getting these errors : 
![screenshot at 2017-07-04 18-09-29](https://user-images.githubusercontent.com/29896934/27837389-3709a690-60e4-11e7-87fd-2162b10c7096.png)
![screenshot at 2017-07-04 18-08-55](https://user-images.githubusercontent.com/29896934/27837393-41090fe6-60e4-11e7-8371-1eb45eb2778c.png)

Docker Version : 
![screenshot at 2017-07-04 18-10-05](https://user-images.githubusercontent.com/29896934/27837409-59c73422-60e4-11e7-8d95-b5257496cab1.png)
Docker-compose version 
![screenshot at 2017-07-04 18-10-34](https://user-images.githubusercontent.com/29896934/27837410-5c01516e-60e4-11e7-9918-07d6c5347dfc.png)
@Roasbeef

**Comment by AndrewSamokhvalov** [comment]
Hey @NourGritli , thanks for creating the issues 👍  Was able to reproduce it locally, create the fix in a minute.

**Comment by AndrewSamokhvalov** [comment]
PR: #230

**Comment by NourGritli** [comment]
Hey @AndrewSamokhvalov , Thank you for the rapid response 
unfortunatelly am still getting the same error 
![screenshot at 2017-07-04 18-57-54](https://user-images.githubusercontent.com/29896934/27838411-bdaf0e64-60ea-11e7-9ed0-eb434ae6eaba.png)

**Comment by AndrewSamokhvalov** [comment]
@NourGritli My PR has to be merged with master

**Comment by NourGritli** [comment]
@AndrewSamokhvalov  i add your modifications to my local repo and the problem is solved 
Thank you :+1: :smile:
