### ISSUE TITLE
etcd as channeldb storage?

### ISSUE THREAD

**Issue by leshik** [lightningnetwork/lnd#2298]
Hi,

How hard would be to implement e.g. `etcd` as the storage backend for channels data? It is distributed, consistent, has gRPC API, and uses `boltdb` internally for persistence. Also proven reliable by such projects as CoreOS and Kubernetes. It's not suitable for local node installs, but would be a great help for routing nodes where reliability is important.

**Comment by Roasbeef** [comment]
See #1172. The PR as is has been abandoned though, feel free to pick it up, as then it'll be much easier to add additional database backends for `lnd`.

**Comment by Roasbeef** [comment]
See #3934 for the evolution on this issue.
