### ISSUE TITLE
Neutrino GetUtxo super slow, lnd stuck and not shutting down

### ISSUE THREAD

**Issue by wereHamster** [lightningnetwork/lnd#2300]
### Background

Every time I start lnd (with -d debug) I see that it is fetching lots of filters, sometimes starting from 20k old blocks). The speed is around 10 blocks/s so it takes a long while until this scan completes. I also believe that this is the same code (goroutine) that's preventing ^C from cleanly shutting lnd down. I have to `kill` lnd to stop it.

### Your environment

* version of `lnd`: HEAD as of today
* which operating system (`uname -a` on *Nix): Darwin Kernel Version 17.7.0
* version of `btcd`, `bitcoind`, or other backend: btcd HEAD as of today
* any other relevant environment details

### Steps to reproduce

Start lnd with -d debug, and use the neutrino backend. It seems that this gets worse the older your channels are (the older they are the farther back neutrino starts the rescan).

### Expected behaviour

lnd shouldn't spend dozens of minutes rescanning the blockchain at each restart. While the actual CPU cost is negligible (I see <2% CPU usage during that time), it still means that the network interface and CPU are being constantly used which will decrease battery life, especially on mobile devices.

### Actual behaviour

I investigated who is interested in these filters and why, and this is what I found out:

routing/router.go processUpdate() receives a channeldb.ChannelEdgeInfo message, and calls lnwallet/btcwallet/blockchain.go GetUtxo(), which in turn calls into neutrino GetUtxo(), which then starts the rescan from the given block height. Due to how neutrino GetUtxo is implemented, it fetches one filter after another, starting from an initial height towards the tip. As mentioned before, the speed is around 10 blocks/s, and probably constrained mostly by latency (in my case ~80ms RTT).

There may be other callers of GetUtxo(), all of which will take a long time to complete and potentially block other parts of lnd.

### Notes

I found this router config option, which confirms that neutrino is the bottleneck here:

```
	// AssumeChannelValid toggles whether or not the router will check for
	// spentness of channel outpoints. For neutrino, this saves long rescans
	// from blocking initial usage of the wallet. This should only be
	// enabled on testnet.
	AssumeChannelValid bool
```

**Comment by Roasbeef** [comment]
See #1781
