### ISSUE TITLE
gRPC `sendToRouteSync` stucks if hop offline

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2303]
### Background

gRPC `sendToRouteSync` stucks if one of the hopes is offline.

### Your environment

* version of `lnd`
    lnd version 0.5.1-beta commit=v0.5.1-beta
* which operating system (`uname -a` on *Nix)
    Linux despatx 4.13.0-36-generic Ubuntu
* version of `btcd`, `bitcoind`, or other backend
    btcd version 0.12.0-beta
* any other relevant environment details
    protobuf (3.6.1)
    grpcio (1.16.1)
    grpcio-tools (1.16.1)

### Steps to reproduce

1- Set up three nodes Alice Bob and Charlie
2- Create channels Alice -> Bob and Bob -> Charlie (with enough funds in the pointed direction)
3- Make sure the three lnd nodes are online, and get the route Alice -> Bob -> Charlie through queryroutes
4- Make sure Alice and Charlie are online, and Bob is **offline**
5- Run sendToRouteSync 
6- it stucks (no response)

### Expected behaviour

 Some error arising after some time

### Actual behaviour

 it stucks

**Comment by Roasbeef** [comment]
FWIW, the sync variants typically aren't as maintained as the regular streaming variants, but nevertheless this should be fixed, we'll look into it. Thanks for the report!

**Comment by joostjager** [comment]
Tried to repro by modifying `lncli` to use `SendToRouteSync`, but got the expected error:
`"payment_error": "unable to route payment to destination: UnknownNextPeer"`

Used `bitcoind`, but seems unlikely that that is related.

Can you reproduce this on a completely clean env (all lnd data dirs cleared)?

**Comment by joostjager** [comment]
You could also try to apply this commit: https://github.com/joostjager/lnd/commit/082b8197ee0699f593948d2a521425abb6c3fe25

Then you can exercise sendtoroutesync using `lncli`, to isolate the python grpc aspect.

**Comment by ranchalp** [comment]
After further testing I am pretty sure the problem derives python's `gRPC`. Today it happened again. here is the code I run for further testing:

```
import codecs, grpc, os
import rpc_pb2 as ln, rpc_pb2_grpc as lnrpc
import string
import random

# Due to updated ECDSA generated tls.cert we need to let gprc know that
# we need to use that cipher suite otherwise there will be a handhsake
# error when we communicate with the lnd rpc server.
os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'

# Lnd cert is at ~/.lnd/tls.cert on Linux and
# ~/Library/Application Support/Lnd/tls.cert on Mac
cert = open(os.path.expanduser('[...]'), 'rb').read()
creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel([...], creds)
stub = lnrpc.LightningStub(channel)

with open(os.path.expanduser([...]), 'rb') as f:
    macaroon_bytes = f.read()
    macaroon = codecs.encode(macaroon_bytes, 'hex')
[...]
request = ln.SendRequest(
    dest_string=dest,
    amt=5000,
    payment_hash_string=payment_hash,
    fee_limit=fee_limit,
)

response = stub.SendPaymentSync(request, metadata=[('macaroon', macaroon)])

print 'response no streaming:', response
```

and here the output:

```
$ python
>>> v={}; execfile('testing-no-streaming.py',v);
 [had to cancel myself with Ctrl-C]
C-c^CKeyboardInterrupt
Exception KeyboardInterrupt in 'grpc._cython.cygrpc._next' ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testing-no-streaming.py", line 42, in <module>
    response = stub.SendPaymentSync(request, metadata=[('macaroon', macaroon)])
  File "[...]/.local/lib/python2.7/site-packages/grpc/_channel.py", line 532, in __call__
    state, call, = self._blocking(request, timeout, metadata, credentials)
  File "[...]/lib/python2.7/site-packages/grpc/_channel.py", line 527, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 305, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 151, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 152, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 303, in grpc._cython.cygrpc.SegregatedCall.next_event.on_success
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 277, in grpc._cython.cygrpc._process_segregated_call_tag
KeyError: None
>>>
```

Had to cancel myslef. But in this case, in the same python shell, even the streaming code would not return:

```
>>> v={}; execfile('testing-streaming.py',v);
C-c^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testing-streaming.py", line 51, in <module>
    response =next(stub.SendPayment(request_iterable, metadata=[('macaroon', macaroon)]),None)
  File "[...]/python2.7/site-packages/grpc/_channel.py", line 367, in next
    return self._next()
  File "[...]/python2.7/site-packages/grpc/_channel.py", line 349, in _next
    self._state.condition.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```
Again, had to cancel myself. I then tried directly from command line (normal version, so sendPayment is streaming):
```
$ lncli-simnet-bob sendpayment --dest=[...] -amt=[...] -r [...]
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
```

After closing and reopening the python shell, it woked as expected, so I have no idea what the problem might be... but this is no good for testing different routes... is it more advisable to use javascript's gRPC version? or directly the command line?

**Comment by ranchalp** [comment]
Update, just found out that this also happens when using the command line version directly. It just happened now (only path in the network is dave - charlie - bob - alice) :
```
$ lncli-simnet-dave sendpayment --dest=alice --amt=5550 -r hash
```

result: hang for a considerable amount of time. Tried again with a different hash after cancelling, and after verifying both `lnd` are running, and received the following error:
```
{
	"payment_error": "payment is in transition",
	"payment_preimage": "",
	"payment_route": null
}
```
even though it was a different hash.

This might have to do with the fact that I was testing right before #2328 with the `While True` option and creating a different hash each time a few minutes/hours before, so maybe that experiment clashed with this one (is there a buffer of hashes that gets filled or something?)
```

**Comment by weaklysubjective** [comment]
Can confirm this issue exists in the iOS environment , also with gRPC. Unable to pay any invoice once this bug manifests, and the error alternates between "unable to find a path to destination" and "payment in transition". There are at least two direct channels between the nodes. This is on testnet. One of the nodes is able to pay, its the other that's stuck.

**Comment by Roasbeef** [comment]
Closing as unable to repro.
