### ISSUE TITLE
lnwire+routing: deprecate FinalIncorrectHtlcAmount in favor of unified UnknownPaymentHash

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2321]
In order to fix a probing vector, [we've recently made a modification in the specification to phase out 
`FinalIncorrectHtlcAmount` in favor of adding an additional payload to `UnknownPaymentHash` of the final value the destination receives](https://github.com/lightningnetwork/lightning-rfc/commit/914ebab9080ccccb0ff176cb16b7a6ba21e23bbe). This change coalesces the two errors, making an unknown payment hash error indistinguishable from the case wherein an intermediate node modifies the value of the final HTLC. Otherwise, if this isn't patched, then a node can probe the final destination of an HTLC as the node that returns `FinalIncorrectHtlcAmount` reveals that the know the payment hash pre-image, but the value is incorrect. After this change, lack of knowledge of a payment hash extended, and an incorrect value for a known payment hash will be indistinguishable. 

# Steps To Completion 

- [ ] Extend [`UnknownPaymentHash`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L297) include a new `lnwire.MiliSatoshi` field of the payment amount. At the end, the error type should properly implement the [`Serializable`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/message.go#L139:6) interface. 

- [ ] Within the link, [whenever we send back an `UnknownPaymentHash` error, we should _always_ set the value of the incoming HTLC](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L2312). 

- [ ] Within the link, [stop returning `FailIncorrectPaymentAmount ` and instead return `UnknownPaymentHash` populated as we do above](https://github.com/lightningnetwork/lnd/blob/42c45979215e3242ef2e162ccd9de3cbb0ed28a1/htlcswitch/link.go#L2361).

**Comment by orbitalturtle** [comment]
Taking this
