### ISSUE TITLE
External IP advertised as 0.0.0.0 when UPnP support enabled

### ISSUE THREAD

**Issue by acurious** [lightningnetwork/lnd#2322]
### Background

I have enabled UPnP support on the daemon. LND starts up, but advertises external IP as 0.0.0.0 to the network. Port forwarding seems to work though. Service can been seen on actual external IP address. 

My lnd.conf is
```
[Application Options]
debuglevel=info
nat=true
maxpendingchannels=5
minchansize=50000
bitcoin.feerate=100
bitcoin.basefee=1000
alias=xxx
color=xxx

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=btcd

[Btcd]
btcd.rpchost=localhost
btcd.rpcuser=xxx
btcd.rpcpass=xxx
```

### Your environment
* version of `lnd`
`lnd version 0.5.1-beta commit=v0.5.1-beta-138-g5451211d1947de5b2376aff5eb39c6e9f969cbbb`

* which operating system (`uname -a` on *Nix)
`Linux 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* version of `btcd`, `bitcoind`, or other backend
`btcd version 0.12.0-beta`

* any other relevant environment details
Using 4g router ZyXEL LTE3311, UPnP enabled

### Steps to reproduce

Not sure

### Expected behaviour

Correct external IP should be advertised to the network when UPnP support is enabled. 

### Actual behaviour

External IP advertised as 0.0.0.0 when UPnP support is enabled

**Comment by Roasbeef** [comment]
How are you determining 0.0.0.0 is advertised?

**Comment by acurious** [comment]
1. I can see it from my Bitcoin Lightning Wallet from Android - BLW. It finds my node, but tells it can not connect to remote peer at IPv4(/0.0.0.0,9735) 
2. `lncli getinfo` returns 	

```
"uris": [
	"<pubkey>@0.0.0.0:9735"
]
``` 
3. Public Lightning Network search engines  also show my node's address as `"<pubkey>@0.0.0.0:9735"`

**Comment by wpaulino** [comment]
@acurious can you provide startup logs?

**Comment by Roasbeef** [comment]
I think this has been resolved?

**Comment by frennkie** [comment]
I was watching this issue and just tested it on `LND v0.9.2-beta`.

I do have an unrelated issue (I needed whitelist the IP of my node on my router for adding port forwardings) but after fixing that I currently can use `nat=true` and `getinfo` will show the correct IP and not `0.0.0.0`.

I still believe it would be *nice* to have this feature request implemented: #3157.

**Comment by acurious** [comment]
I simply forgot the issue. I was not able to fix it

**Comment by frennkie** [comment]
Can you still reproduce it?

**Comment by acurious** [comment]
No, I can't reproduce it atm. I stopped running a node a while ago.

**Comment by frennkie** [comment]
I had a reconnect over the night a it still looks fine (showing the new IP on `getinfo`). @Roasbeef I think it's safe to consider this fixed and close it.

**Comment by guggero** [comment]
Nice, thanks for the update @frennkie.
