### ISSUE TITLE
faucet.lightning.community fails

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2330]
### Background

Trying to fund my node but repeatedly get error message "site cannot be reached". 
Pinging the site works..wondering if LND is functioning ?

### Your environment

* version of `lnd` : Not Applicable , funding via website

### Steps to reproduce
Try funding from faucet.lightning.community

Additional info / question:

How can i connect to faucet.lightning.community and open a channel from a iPV6 node ?

**Comment by Roasbeef** [comment]
I may have banned your IP, PM me on email/twitter/irc/slack to check. The faucet is active atm and has been for a few days.
