### ISSUE TITLE
Can't update IP for persistent channel connection

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#2340]
### Background

I have a node (call it A) with opened channel to a remote node (call it B).
After the channel was opened B's IP address was changed and ever since LND doesn't connect automatically to this peer on startup, which seems OK to me since it doesn't have  way to know about the IP change.
The problem is that I can't find a way to update the IP for this peer so that on startup it will connect automatically to the channel.
Using the "lncli connect" command succeed but doesn't affect the next restart.

### Your environment
* lnd master
* mac os

### Steps to reproduce
1. open a channel with remote node.
2. change the remote node ip address.
3. connect to the remote node after the ip change.
4. restart LND.

### Expected behaviour

I do expect to have a way to change the saved ip address for this peer so that the next startup succeed to connect automatically.

### Actual behaviour

I need to do manual connect on every startup to be able to connect to this peer, even though I have a channel with it and the peer is online.

**Comment by roeierez** [comment]
My investigation raised that the connections to peers with channels happens at this function: https://github.com/lightningnetwork/lnd/blob/master/server.go#L1620
For each channel there is a "LinkNode" struct in the channel db. The problem is that this LinkNode is only created and saved once, when the channel is pending here: https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L870
I have in mind two ways of approaching this and would appreciate your opinion on this:
1. implicit -  when a peer that has channels starts, override the LinkNode with the new address, probably at this point: https://github.com/lightningnetwork/lnd/blob/master/peer.go#L306. I see that although the LinkNode has array of addresses it is created with one address for the pending channel here: https://github.com/lightningnetwork/lnd/blob/master/channeldb/nodes.go#L67 and I wonder if this address can be safely replaced when a new valid connected address is detected for this peer.
2. explicit - either add API to change peer address that will affect associated LinkNode address or add flag to connect command that explicitly overrides the current address for the associated LinkNode

**Comment by Roasbeef** [comment]
> The problem is that I can't find a way to update the IP for this peer so that on startup it will connect automatically to the channel.

When the node makes a new announcement, we'll re-connect back to it on start up. We combine the `LinkNode` view with the latest announcements in the graph.

**Comment by Roasbeef** [comment]
Ah, or you mean that we should modify our connection targets in real time as node announcements change in the network?

**Comment by roeierez** [comment]
> When the node makes a new announcement, we'll re-connect back to it on start up. We combine the `LinkNode` view with the latest announcements in the graph.

Thanks, I see now the code I missed in `establishPersistentConnection` function. It actually merges the addresses from the graph as you said. Maybe in my case there was a problem with the node announcement, I need to check again.



> Ah, or you mean that we should modify our connection targets in real time as node announcements change in the network?

I actually didn't mean that. In such case I guess a disconnect will occur and currently the code retries to connect with the first advertise address from the graph so it is pretty much up to date. It can maybe be optimized to try all addresses but it is not the case I reported.

Thanks for making this clear. This issue can be closed.

**Comment by roeierez** [comment]
@Roasbeef I checked and I believe on my case the channel graph was not updated.
So in the case that "A" has a channel with "B" and "B"  is stoped, changes IP address and then restarted again, is there a way to ensure that A will get the updated graph with the new advertise addresses on reconnecting to B?

**Comment by Roasbeef** [comment]
Should have been resolved by https://github.com/lightningnetwork/lnd/pull/4133, which ensures we also send our local announcement each time we connect to a peer.
