### ISSUE TITLE
REST API CORS headers

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2344]
### Background

If a web application wanted to use an LND node, requests would be blocked even if the REST API were exposed due to the lack of a `Access-Control-Allow-Origin` header. I don't know that there's much harm in setting it to `*` by default, since you'd need macaroons for the node to do pretty much anything anyway.

This is somewhat of a duplicate of #1405, however that issue went a little off-topic with a fork of LND.

### Your environment

* version of `lnd` - 0.5.1
* which operating system (`uname -a` on *Nix) - Ubuntu Server 16.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind

**Comment by tiero** [comment]
As far I know, shouldn't be needed a `grpc-web` proxy running to serve browsers?

**Comment by wbobeirne** [comment]
> As far I know, shouldn't be needed a `grpc-web` proxy running to serve browsers?

Not sure I understand what you're asking, but there's a REST API is provided by `grpc-gateway`, which is what browsers can use to communicate.

It looks like #1433 was an attempt at adding this. However, it looks like that's gone a bit stale. It also added a config option, rather than CORS headers by default, but I think that'd be satisfactory.
