### ISSUE TITLE
Restrict routing to select one of suggested routing hints

### ISSUE THREAD

**Issue by Bluetegu** [lightningnetwork/lnd#2346]
### Background

A private invoice may include multiple route-hints, indicating the forward route from a public node to the final destination.
For this issue lets name the two parts of the route the public-path and the private-path, connected together to form the entire path from source to destination. 

Current routing will select the shortest path** combined out of all edges and nodes contained in the hints and those public, such that the resulting private-path would not necessarily be one of the suggested route hints (Please see examples below).

As far as I read BOLT#11, this is not against the spec, but it does mean that the issuer of the private invoice has less control than they might expect.

** path with least total fees, with enough capacity, but assume here for the discussion that all edges are set with the same fee, and have enough capacity, so shortest == least total fees.

### Your environment

* version of 0.5.1-beta commit=v0.5-beta-rc2-674-gb60156f84a253ee48383ff03577a8d3816980cfe-dirty
* any other relevant environment details: 
came up in a review to PR#2151. 

### Steps to reproduce

Suppose we have the network below, consisting of 3 public nodes (A, B, C) and 3 private nodes (D, E, F). 
F provides the following to route hints:
r1: B -> D -> E -> F
r2: C -> E -> D -> F

With the current routing, routing will select:
 A -> B -> D -> F  (or A -> C -> E -> F)
That is, it will not select one of the route hints, but rather a shorter path, combined from the two (it will not transverse D -> E or E -> D as suggested in the hints).

```
  ........| F | .......
  .                   .
  .  23               . 24
  .                   .
  .         22        .
| D |...............| E | 
  .                   .
  .  20               . 21
  .                   .
| B |               | C | 
  |                   |
  |  10               | 11
  |                   |
  ------ | A | ------
```
Note this also applies to a bit simpler setup, in which the private channel is between two public nodes B and C. 
r1: C -> B -> D
r2: B->C -> D
while routing will select either A -> B -> D or A -> C -> D

 ```
  ........| D | .......
  .                   .
  .  23               . 24
  .                   .
  .         22        .
| B |...............| C | 
  |                   |
  |  10               | 11
  |                   |
  ------ | A | ------
```

### Expected behaviour

The private part of the route should follow one of the suggested route hints. 

Routing should calculate a route to one of the public nodes specified as the 'start' node in the suggested route hints, and follow the route hints to reach the final destination, then iterate over the possible route hints and compare the resulting path to select the best of those.
That is, in the first example above,  for r1, calculate the route to B, and use r1 for the private path, for r2 calculate the route to C and user r2, then compare A -> B -> D -> E -> F and A -> C -> E -> D -> F and select the best out of those.

### Actual behaviour

The shortest path composed of all known public nodes + edges and private nodes + private edges is calculated.

**Comment by Roasbeef** [comment]
>  such that the resulting private-path would not necessarily be one of the suggested route hints 

The routing hints are just meant to be an extension for the network view for the sender. It's possible atm to specify multiple "off network" hops in a routing hints, but there's currently no protocol-level extension to allow a sort of gossip of these routes with a TTL (so you can advertise a neighborhood for example). 

To summarize this issue, you're requesting a "strict routing hint" mode wherein we'll ensure that the final path has an exact suffix of the hops specified in the routing hint?

**Comment by Bluetegu** [comment]
> To summarize this issue, you're requesting a "strict routing hint" mode wherein we'll ensure that the final path has an exact suffix of the hops specified in the routing hint?

Yes.

I think BOLT#11 definition of the use of route-hints is ambiguous, and as a result it is not clear whether 'strict route hint' mode should be the default or not (e.g. that was my understanding when reading it the first time). I don't know what other implementations chose to implement with this regard. Ambiguity in definition is never a good thing,  so this should probably be raised as an issue in lightning-rfc.

**Comment by Roasbeef** [comment]
Blinded paths essentially allow you to force this behavior, so closing this as we're tracking the implementation elsewhere.
