### ISSUE TITLE
Concurrency issue with `update_fee`

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lnd#2348]
### Background

I don't know the version of `lnd` so this issue may have already been fixed, just thought it would be interesting to keep a reference just in case.

Right after having sent an `update_fee`, `lnd` rejects a `commit_sig` that I sent, and by looking at the attached error message, I can see that `lnd` was *incorrectly* expecting that I use the new unacknowledged feerate.

```
  eclair              lnd
    |                  |
    |-------sig------->|
    |<------fee--------|
    |<------err--------|
    |                  |

```

**Comment by halseth** [comment]
So is eclair or lnd sending the `fee` here? Should the fee come before the sig in the drawing?

**Comment by pm47** [comment]
`lnd` sends the fee, and `eclair` send the signature roughly at the same time. The exact order doesn't really matter, the point is that the fee hasn't been acknowledged by `eclair`, if that makes sense?
