### ISSUE TITLE
OpenChannel gRPC stream not yielding ConfirmationUpdates

### ISSUE THREAD

**Issue by fusion44** [lightningnetwork/lnd#2351]
### Background

[I'm using the OpenChannel gRPC call from Python](https://github.com/fusion44/fort-bitcoin-gql/blob/master/backend/lnd/implementations/subscriptions/open_channel_subscription.py#L171) to open channels and watch for the responses. Current implementation seems only to yield the chan_pending and chan_open responses, but omits confirmation updates. Confusingly the response is included in the [documentation](https://api.lightning.community/?python#openchannel).

### Your environment

lncli version 0.5.1-beta commit=v0.5.1-beta
Linux laptop-antergos 4.19.8-arch1-1-ARCH #1 SMP PREEMPT Sat Dec 8 13:49:11 UTC 2018 x86_64 GNU/Linux
btcd version 0.12.0-beta

### Expected behaviour
Either send the confirmation updates or remove it from the gRPC interface

Thanks!

**Comment by halseth** [comment]
Looks like it has never been implemented.

**Comment by Linuxurious** [comment]
I'll take this on

**Comment by Linuxurious** [comment]
Ok, I seem to have pin-pointed the issue:

Looks like [here](https://github.com/lightningnetwork/lnd/blob/e6623f98b38f279900aaedf6a6993f34c3a45337/cmd/lncli/commands.go#L681) and [here](https://github.com/lightningnetwork/lnd/blob/e6623f98b38f279900aaedf6a6993f34c3a45337/cmd/lncli/commands.go#L698) we check the cases for the two [OpenStatusUpdates](https://github.com/lightningnetwork/lnd/blob/e6623f98b38f279900aaedf6a6993f34c3a45337/lnrpc/rpc.proto#L1238) PendingUpdate and ChannelOpenUpdate, but we omit the case for ConfirmationUpdate. Looks like the stream and all that jazz was implemented on the rpc server though, so it should be as easy as just adding the case to the cli command.

**Comment by fusion44** [comment]
@Linuxurious Thanks for implementing this! 
Roasbeef pointed me to the [ConfirmationEvent struct](https://github.com/lightningnetwork/lnd/blob/master/chainntnfs/interface.go#L166) as a good starting point.

**Comment by halseth** [comment]
@Linuxurious Note that the confirmation event is not yet sent on the channel (should be don from the `fundingmanager`). I would recommend adding a check for this to `fundingmanager_test.go` :)

**Comment by willcl-ark** [comment]
Hello @fusion44, is this implementation still on going?

**Comment by fusion44** [comment]
@willcl-ark I don't know. Haven't heard of @Linuxurious since he wanted to tackle the issue. I'll take this on in the coming week.
