### ISSUE TITLE
DescribeGraph - Channel Graph - fails when expected IP not found

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2358]
### Background

Node A is connected to Node B for this example lets say from IP1 to IP2. Both IP's are v6 and they are different IP's. The nodes also have a public channel between them, the channel is fully functional, able to invoice and pay using the channel.
The channel graph view from Node B has nodes and links that can be displayed as a directed graph. Node B is connected to a couple of nodes in the acinq network and possibly to faucet.lightning.community. This is how Node B gets the graph.

Channel graph for A is also seen similar to B 

However the link between Node A and Node B is not shown in the channel graph

I would expect that channel graph from the point of view of Node A would show the link between itself and Node B, in addition to the full directed graph of Node B 

### Your environment

* version of `lnd` --- 0.5.0 beta
* which operating system (`uname -a` on *Nix)  --- iOS
* version of `btcd`, `bitcoind`, or other backend -- btcd

### Steps to reproduce

1) Connect any two nodes , and have a channel between them
2) Connect Node B to other nodes in the lightning ecosystem
3) Describe graph of Node B and you will see nodes and links
4) Describe graph of Node A will not show the link between Node A and Node B

### Expected behaviour

Expecting to see a full directed graph from the point of view of Node A (just like Node B but with one extra link between Node A and Node B)

### Actual behaviour

Node A graph does not show link between itself and Node B

**Comment by wpaulino** [comment]
> Node A graph does not show link between itself and Node B

Does B show the channel between it and A in its graph?

With `lnd`, channels are not announced to the network and added to the graph until they've reached 6 confirmations.

**Comment by weaklysubjective** [comment]
No, B does not show channel between it and A. Channel has been announced and nodes are able to invoice and pay between each other. Though both have channels to a common node and its possible the payments got routed through that node, not sure. Pretty sure that its past 6 confirmations

**Comment by weaklysubjective** [comment]
Hi Paulino / et al, I did some more digging and it appears the DescribeGraph issue relates to change of IP Address. When Node A connected and opened a channel to Node B , Node B's IP Address was different from what it is now when asked to describe channel graph. 
Channel Graph holds on to the old IP and thus the new IP doesn't show on the vertexes or edges.

The channel appears in the active channels, but describegraph is one step behind (or so i think)

Not sure if my assumptions are correct. Much appreciate any feedback.

**Comment by Roasbeef** [comment]
Does this persist if you upgrade to 0.5.1? What's the exact error you see when you try to call `describegraph`?

**Comment by weaklysubjective** [comment]
Have to try 0.5.1. As to what happens in 0.5.0 consider the following:

The links shown below are derived from the 'edges' i get from DescribeGraph 

- there is a link from source node 2 to target node 1 , both being nodes i run, with different IP's {"source":2,"target":1,"value":4,"group":2,"alias":"holdonfordearlifeDHTHLNbAQkKaMT"
- for some reason there is also a link from source node 1, to target node 0 (as below) "source":1,"target":0,"value":4,"group":3,"alias":"holdonfordearlifeDHTHLNbAQkKaMT"
I only have two nodes running atm.


While the links exist (one is a good link) , other i am not sure where it comes from, neither link is drawn in a directed graph. However, each node , does have a link drawn to elsewhere , not between themselves. That in my mind is the issue.  

Apart from the fact that describegraph shows more edges than there should be, it seems ok. It may be how the links are drawn that is the issue. 
I'll keep this open until i figure out what might be the problem.

Why does DescribeGraph produce more edges than are there ?

**Comment by weaklysubjective** [comment]
Hi Guys, Describegraph works correctly. It was an issue in the app in the way it drew the links. Nodes and edges from describegraph are as expected. Thank you for your comments..will close this one.
