### ISSUE TITLE
lnd crashes after onchain transaction

### ISSUE THREAD

**Issue by jguchte** [lightningnetwork/lnd#2362]
### Background

lnd crashes after onchain transaction.

panic: runtime error: invalid memory address or nil pointer dereference

### Your environment

* version of `lnd`
0.5.0-beta

* which operating system (`uname -a` on *Nix)
Linux RaspiBolt 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.0.1

* any other relevant environment details
go version go1.11.4 linux/arm

I followed the guide provided by Stadicus. 
https://github.com/Stadicus/guides/blob/master/raspibolt/README.md

I have a feeling this problem started occuring sometime after I completed the steps in the guide and is not (directly) related. I installed Golang and did some other tweaking.

### Steps to reproduce

After doing an onchain transaction, funding or opening a channel, lnd crashes.

### Expected behaviour

Lnd keeps running.

### Actual behaviour

Logs:
After onchain transaction (new funds)

....
Dec 21 21:00:29 RaspiBolt lnd[9831]: 2018-12-21 21:00:29.807 [INF] LNWL: Inserting unconfirmed transaction [...txid here...]
Dec 21 21:00:33 RaspiBolt lnd[9831]: 2018-12-21 21:00:33.682 [INF] DISC: Broadcasting batch of 31 new announcements
Dec 21 21:01:03 RaspiBolt lnd[9831]: 2018-12-21 21:01:03.683 [INF] DISC: Broadcasting batch of 107 new announcements
Dec 21 21:01:08 RaspiBolt lnd[9831]: 2018-12-21 21:01:08.897 [INF] LTND: New invoice subscription client: id=4
Dec 21 21:01:33 RaspiBolt lnd[9831]: 2018-12-21 21:01:33.682 [INF] DISC: Broadcasting batch of 161 new announcements
Dec 21 21:01:34 RaspiBolt lnd[9831]: 2018-12-21 21:01:34.522 [INF] CRTR: Updated vertex data for node=03434a39cd9a537c852fc8fb72454086d726f9111e9f730cef4985c39c11fae944
Dec 21 21:01:34 RaspiBolt lnd[9831]: 2018-12-21 21:01:34.523 [INF] ATPL: Node updates received, assessing need for more channels
Dec 21 21:01:38 RaspiBolt lnd[9831]: 2018-12-21 21:01:38.695 [INF] CRTR: Updated vertex data for node=02d8be648914ac46eec73489f333057fe559ef3799adf13b14842260be80a2f847
Dec 21 21:01:38 RaspiBolt lnd[9831]: 2018-12-21 21:01:38.696 [INF] ATPL: Node updates received, assessing need for more channels
Dec 21 21:01:38 RaspiBolt lnd[9831]: 2018-12-21 21:01:38.771 [INF] CRTR: Updated vertex data for node=024a549e096f4355073e3a2712a10c5a773e48bd21a7d2ddef71639481008ce811
Dec 21 21:01:38 RaspiBolt lnd[9831]: 2018-12-21 21:01:38.772 [INF] ATPL: Node updates received, assessing need for more channels
Dec 21 21:02:03 RaspiBolt lnd[9831]: 2018-12-21 21:02:03.682 [INF] DISC: Broadcasting batch of 11 new announcements
Dec 21 21:02:15 RaspiBolt lnd[9831]: 2018-12-21 21:02:15.492 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.89.123:51822: chacha20poly1305: message authentication failed
Dec 21 21:02:19 RaspiBolt lnd[9831]: 2018-12-21 21:02:19.256 [INF] LTND: New invoice subscription client: id=5
Dec 21 21:02:19 RaspiBolt lnd[9831]: 2018-12-21 21:02:19.565 [INF] RPCS: [listchannels] fetched 5 channels from DB
Dec 21 21:02:19 RaspiBolt lnd[9831]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 21 21:02:19 RaspiBolt lnd[9831]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78c4e8]
Dec 21 21:02:19 RaspiBolt lnd[9831]: goroutine 240853 [running]:
Dec 21 21:02:19 RaspiBolt lnd[9831]: main.(*rpcServer).GetTransactions(0x1cee920, 0xbf41a0, 0x21db200, 0x1314240, 0x1cee920, 0x0, 0x197a35c)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x1fc
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0xbf41a0, 0x21db200, 0x8fc3a0, 0x1314240, 0x1, 0x1, 0x0, 0x0)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x68
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xbf41a0, 0x21db200, 0x8fc3a0, 0x1314240, 0x2c23050, 0x2c23060, 0x1d8f314, 0x5c0be4, 0x30, 0x91ab50)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x108
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0x970730, 0x1cee920, 0xbf41a0, 0x21db200, 0x1c93680, 0x1abe670, 0x0, 0x0, 0x0, 0x4a73bc)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x118
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x1f86cc0, 0xbf6ec8, 0x36b4000, 0x222c000, 0x1ceea20, 0x12e7340, 0x21db980, 0x0, 0x0)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x74c
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0x1f86cc0, 0xbf6ec8, 0x36b4000, 0x222c000, 0x21db980)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0xf40
Dec 21 21:02:19 RaspiBolt lnd[9831]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x36d5ae0, 0x1f86cc0, 0xbf6ec8, 0x36b4000, 0x222c000)
Dec 21 21:02:19 RaspiBolt lnd[9831]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x7c
Dec 21 21:02:19 RaspiBolt lnd[9831]: created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Dec 21 21:02:19 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 21 21:02:19 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Dec 21 21:02:19 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 21 21:03:20 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Dec 21 21:03:20 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Dec 21 21:03:20 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Dec 21 21:03:20 RaspiBolt lnd[11740]: Attempting automatic RPC configuration to bitcoind
Dec 21 21:03:20 RaspiBolt lnd[11740]: Automatically obtained bitcoind's RPC credentials
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.716 [INF] LTND: Version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.720 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.766 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.791 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.790 [INF] RPCS: password RPC server listening on [::]:10009
Dec 21 21:03:20 RaspiBolt lnd[11740]: 2018-12-21 21:03:20.791 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

After opening a channel (I did this one with ZapIOS)

Dec 21 21:20:51 RaspiBolt lnd[11740]: 2018-12-21 21:20:51.599 [INF] DISC: Broadcasting batch of 21 new announcements
Dec 21 21:21:21 RaspiBolt lnd[11740]: 2018-12-21 21:21:21.599 [INF] DISC: Broadcasting batch of 13 new announcements
Dec 21 21:21:51 RaspiBolt lnd[11740]: 2018-12-21 21:21:51.599 [INF] DISC: Broadcasting batch of 18 new announcements
Dec 21 21:22:04 RaspiBolt lnd[11740]: 2018-12-21 21:22:04.539 [INF] RPCS: [listchannels] fetched 5 channels from DB
Dec 21 21:22:15 RaspiBolt lnd[11740]: 2018-12-21 21:22:15.873 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.89.123:52934: chacha20poly1305: message authentication failed
Dec 21 21:22:21 RaspiBolt lnd[11740]: 2018-12-21 21:22:21.599 [INF] DISC: Broadcasting batch of 8 new announcements
Dec 21 21:22:42 RaspiBolt lnd[11740]: 2018-12-21 21:22:42.068 [INF] CRTR: New channel discovered! 

[...channel info here...]

Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.801 [INF] LNWL: Inserting unconfirmed transaction [..txid here..]
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.842 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint([..txid here..]:0)
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.842 [INF] CNCT: ChannelArbitrator([..txid here..]:0): starting state=StateDefault
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.842 [INF] NTFN: New block epoch subscription
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.866 [INF] NTFN: New spend subscription: utxo=[..txid here..]:0
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.871 [INF] FNDG: Finalizing pendingID([...id here]) over ChannelPoint([..txid here..]:0), waiting for channel open on-chain
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.871 [INF] CNCT: Close observer for ChannelPoint([..txid here..]:0) active
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.878 [INF] FNDG: Waiting for funding tx ([..txid here..]) to reach 3 confirmations
Dec 21 21:24:27 RaspiBolt lnd[11740]: 2018-12-21 21:24:27.878 [INF] NTFN: New confirmation subscription: txid=[..txid here..], numconfs=3
Dec 21 21:24:28 RaspiBolt lnd[11740]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 21 21:24:28 RaspiBolt lnd[11740]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78c4e8]
Dec 21 21:24:28 RaspiBolt lnd[11740]: goroutine 41422 [running]:
Dec 21 21:24:28 RaspiBolt lnd[11740]: main.(*rpcServer).GetTransactions(0x3b17ae0, 0xbf41a0, 0x5c6a100, 0x1314240, 0x3b17ae0, 0x0, 0x359c158)
Dec 21 21:24:28 RaspiBolt lnd[11740]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x1fc
Dec 21 21:24:28 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 21 21:24:28 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Dec 21 21:24:28 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 21 21:25:28 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Dec 21 21:25:28 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Dec 21 21:25:28 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Dec 21 21:25:28 RaspiBolt lnd[11810]: Attempting automatic RPC configuration to bitcoind
Dec 21 21:25:28 RaspiBolt lnd[11810]: Automatically obtained bitcoind's RPC credentials
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.668 [INF] LTND: Version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.671 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.672 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.707 [INF] RPCS: password RPC server listening on [::]:10009
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.710 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
Dec 21 21:25:28 RaspiBolt lnd[11810]: 2018-12-21 21:25:28.710 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

I can provide the full log if necessary. (txid's and channel info)

**Comment by vegardengen** [comment]
This is probably the known error in 0.5.0, that doing a listchaintxns with an unconfirmed tx in the wallet would crash LND.

This issue is fixed in 0.5.1, so I would recommend upgrading to 0.5.1.

0.5.1 is more of a bugfix release, so a lot of other bugs was also fixed.

**Comment by jguchte** [comment]
> This is probably the known error in 0.5.0, that doing a listchaintxns with an unconfirmed tx in the wallet would crash LND.
> 
> This issue is fixed in 0.5.1, so I would recommend upgrading to 0.5.1.
> 
> 0.5.1 is more of a bugfix release, so a lot of other bugs was also fixed.

Thank you! Will update to 0.5.1 and report here if this is the cause.

**Comment by Roasbeef** [comment]
Fixed as part of 0.5.1.
