### ISSUE TITLE
Issue trying to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by KingZee** [lightningnetwork/lnd#2364]
### Background
Having trouble building lnd on Ubuntu 16.04 machine. It seems that there is a problem with fetching dependencies, I'm not familiar with golang. Here's the error message after running the first command : 

    $ go get -d github.com/lightningnetwork/lnd
    package context: unrecognized import path "context" (import path does not begin with hostname)
    package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
    package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)

It still finishes, but as I expected after trying to build I get errors of "cannot find package".

How do I install those dependencies? I'm using golang 1.6.

### Your environment
* default golang version parsed from apt-get, which was 1.6
* latest version of lnd
* Linux ubuntu 4.4.0-138-generic
* bitcoind : /Satoshi:0.17.0/

**Comment by ErikEk** [comment]
Try uising golang 1.11 to start with.

**Comment by ErikEk** [comment]
Apparently the context package has been added in Go 1.7. I'll look into it.

**Comment by Roasbeef** [comment]
The docs _are_ updated, which docs are you referring to?
