### ISSUE TITLE
Can't accept incoming connection: EOF

### ISSUE THREAD

**Issue by Nomadic951** [lightningnetwork/lnd#2375]
### Background

With Autopilot on, one outgoing channel opened successfully.  Since then, a single external node is repeatedly(Approaching a day every few minutes) been trying and failing to open a channel to my node.  I cannot see why it is failing.  Blocking the IP in UFW appears results in no apparent incoming connection attempts.

### Your environment

LND: 0.5 commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
OS: Linux RaspPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
BTC Client: Bitcoin Core RPC client version v0.17.0.1

### Steps to reproduce

Start LND and monitor with journalctl

### Expected behaviour

New inbound connection stops repeating either by no future attempts or channel successfully opens

### Actual behaviour

Same node repeatedly attempts and fails to open an inbound connection roughly every 2.5 minutes.  No other inbound channels appear to be trying to connect.
[Incoming_log.txt](https://github.com/lightningnetwork/lnd/files/2709195/Incoming_log.txt)

**Comment by smmalis37** [comment]
I have a script that runs periodically and that uses `nc -z ip_addr 9735` to test whether my node is reachable or not, and to notify me if it goes down. I noticed in the lnd logs that they produce exactly the same message every time my script pings it. Is it possible that this is something similar? Maybe an explorer that heard about you and is just making sure you're still alive?

**Comment by halseth** [comment]
You are using an old version of lnd. You should upgrade to v0.5.1.

**Comment by wpaulino** [comment]
Doesn't seem like an issue other than that node potentially being faulty/malicious. In the future, we'll detect peers that do this through a DoS engine and ban them.
