### ISSUE TITLE
Network graph became too large for grpc to handle

### ISSUE THREAD

**Issue by dlaptev** [lightningnetwork/lnd#2376]
### Background

```lncli describegraph```

results in

```[lncli] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4238144 vs. 4194304)```

Probably some kind of pagination is needed or (as a temporary solution) the grpc limit could be increased from the default one in 4MB.

### Your environment

 * ```lnd version 0.5.0-beta commit=6d759bd8d9f1595f32fba6f901db4dcb78b6613e```
 * ```Linux 4.4.0-134-generic #160-Ubuntu SMP x86_64 GNU/Linux```
 * ```Bitcoin Core Daemon version v0.16.3.0-g49e34e288```

### Steps to reproduce

Run ```lncli describegraph```.

### Expected behaviour

A json object describing the lightning network graph.

### Actual behaviour

```[lncli] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4238144 vs. 4194304)```

**Comment by cryptagoras** [comment]
There's an open PR (#2374) addressing this.

**Comment by dlaptev** [comment]
Oops, did not see it. Thanks for the reply!
