### ISSUE TITLE
Can't send full balance to other end of direct channel

### ISSUE THREAD

**Issue by KAMEHOB** [lightningnetwork/lnd#2383]
### Background

I have setup gateway style cluster of one gateway node(nodeG) and 3 private client nodes(nodeC1, nodeC2, nodeC3).. So all client transactions are routed through nodeG. All client nodes have channels to nodeG.

### Describe your issue here.

The issue I have is that I can fill the nodeG side of the channel with any amount of  satoshis. But when I want to send them back to let's say nodeC2, it allows me to transfer only some part of the amount.

Here is a real example of channel balances:

nodeG amt  | nodeC2 amt
-------------+---------------
| 1611          | 22757

I want to send those 1611 satoshis to nodeC2 end. But what only allows me to route is 1038 satoshis. I can't understand why, this is direct channel between the 2 nodes.

> lncli queryroutes 03bce096d13fc4e41a1aa74333a20dbb1d796ba74d7ab20e079490125fd938c2c2 1038
{
    "routes": [
        {
            "total_time_lock": 555894,
            "total_fees": "0",
            "total_amt": "1038",
            "hops": [
                {
                    "chan_id": "610926043866857473",
                    "chan_capacity": "25000",
                    "amt_to_forward": "1038",
                    "fee": "0",
                    "expiry": 555894,
                    "amt_to_forward_msat": "1038000",
                    "fee_msat": "0",
                    "pub_key": "03bce096d13fc4e41a1aa74333a20dbb1d796ba74d7ab20e079490125fd938c2c2"
                }
            ],
            "total_fees_msat": "0",
            "total_amt_msat": "1038000"
        }
    ]
}

***********

> lncli queryroutes 03bce096d13fc4e41a1aa74333a20dbb1d796ba74d7ab20e079490125fd938c2c2 1039
[lncli] rpc error: code = Unknown desc = unable to find a path to destination

### Your environment

* lnd version 0.5.1-beta 
* Linux blockchain 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind

### Expected behaviour

Should transfer all satoshis back to the other side of the channel.

### Actual behaviour

Allows partial transfer of funds

**Comment by vegardengen** [comment]
This is as per design. The reserve, currently 1% of channel, can never be sent back. This is a deterrent against submitting an old channel balance - upon doing so, the partner receives *all* funds, so you do want your channel partner to always have something to lose.

**Comment by KAMEHOB** [comment]
I am sorry I will turn this into a discussion but I need to clean things out of all limitations on LN, which are normally trivial use cases.

So here 1% of 25000(the commited amount in the channel) is 250 satoshi and here it doesn't allow you to send 1611 - 1038 = 573.

Can someone collaborate more on how exactly this is calculated, and can it be seen somewhere in the channel info or any other place.. so it can be for example shown on the user in specific cases. This kinda also limits the routing amount that can pass through you and it is somehow mistery how it works exactly, and why you can receive but not send the same amount.. Especially from user point of view is nerve testing game when you start with completely new channel(one sided).

I also noticed another sub-issue, you have to send the other party at least 1000 satoshis at least, so he can actually start sending you something like 2-3 satoshis.. I understand this now comes from above.. Really big problem for receiving funds until you don't spend some for while.

In the gateway usage(topology).. is it recommened final client nodes to open one channel to the gateway, and separately gateway to open a channel to the user to somehow counter the effect above? I imagine this issue will disappear when we have both parties commit funds in one channel in the future.

Also, how this applies/mix on routing when for example nodeC1 wants to pay nodeC3 through nodeG(gateway). Are there any other limitations, from experience I know the gateway should have some satoshis on their end on both channels so it can forward the amounts to nodeC3 and there is a minimum HTLC amount of 1000 by default..

**Comment by BobleChinois** [comment]
Hi, I'm pretty much in the same situation than OP with two of my nodes. I understand the point of having this 1% reserve, but I think it would be nice to have a more explicit message error then. Isn't it possible to deactivate the reserve requirement on channel opening?

**Comment by halseth** [comment]
You are right, @vegardengen, this is because of the channel reserve, which is set here: https://github.com/lightningnetwork/lnd/blob/089d461552ffc05d7b1c22d603af0fa82e788e85/server.go#L899

Atm, this will me `max(1% of channel capacity, dustlimit)`, which is why it might be higher than the 1%.

It could be made configurable, it just hasn't been a priority. Feel free to open a feature request, or even better: a PR to add the option! 😀
