### ISSUE TITLE
dep ensure requires a repo from http://github.com/BitfuryLightning/tools

### ISSUE THREAD

**Issue by tiero** [lightningnetwork/lnd#2386]
### Background

Adding `lnd` as a go package using `dep` it gives me a `Could not read from remote repository` error pointing from `https://github.com/BitfuryLightning/tools`

I do think is a private repository. 

### Your environment

* version of `lnd` **lnd version 0.5.1-beta commit=**
* which operating system (`uname -a` on *Nix) **Darwin**
* `bitcoind`, 
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

* Install Dep

* add `lnd` to a dep project 

`dep ensure -add github.com/lightningnetwork/lnd`

### Expected behaviour

Add to `vendor` folder the go code needed

### Actual behaviour

```➜  dep ensure -add github.com/lightningnetwork/lnd
Fetching sources...

Solving failure: 
	(1) failed to list versions for https://github.com/BitfuryLightning/tools: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by halseth** [comment]
It looks like when you add the dependency without any revision specified, it will fetch the first available "non-beta" release `v0.0.2`, which has this outdated `BitfuryLightning` dependency.

Instead, try doing `dep ensure -add github.com/lightningnetwork/lnd@0.5.1-beta` :)
