### ISSUE TITLE
[Documentation] sat_per_byte ignored when (force) closing a channel

### ISSUE THREAD

**Issue by wamde** [lightningnetwork/lnd#2392]
### Background

Describe your issue here.

### Your environment

lnd 0.5.1
bitcoind 0.17

### Steps to reproduce

`lncli closechannel --force --block --sat_per_byte 1 funding_txid output_index`

### Expected behaviour

I would expect block explorers to show that the closing tx would use 1 sat per byte. Instead it shows 24 in my case.

**Comment by wamde** [comment]
Note that `lncli closechannel --sat_per_byte 1 funding_txid output_index` seems to work fine.

**Comment by halseth** [comment]
Force closing a channel uses the pre-signed commitment transaction, and hence the fee cannot be manually set. Agree that this could be better documented.

**Comment by cfromknecht** [comment]
fwiw, `lncli closechannel -h` already says that it's for cooperative closures only:
```
  In the case of a cooperative closure, One can manually set the fee to
  be used for the closing transaction via either the --conf_target or
  --sat_per_byte arguments. This will be the starting value used during
  fee negotiation. This is optional.
```

**Comment by cfromknecht** [comment]
there's also an open issue to have `lncli closechannel` return an error when trying to force close with `--sat_per_byte` set https://github.com/lightningnetwork/lnd/issues/3074

**Comment by halseth** [comment]
Closing in favor of #3074
