### ISSUE TITLE
Feature Request: sendToRoute using only channel_ids and amt value

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2398]
It would be nice to have a feature that specifies a particular route by given `channel_ids` and `amt`. Now, when one wants to force a particular route, one needs to call `query_routes`, look for the route with the hops that one wants, and use it for the `sendToRoute` payment. It would be nice to have such feature to ease these in cases when somebody wants to pay through a particular route.

**Comment by ctrlbreak-** [comment]
I'm trying to chain queryroutes and sendtoroute via LNCLI, and cannot get any attempts to currently work:

https://pastebin.com/aH55fJ5F

Channel is directly between my older CL node and more recent LND node.  Payment hash is for 500000 msats.

I don't have an adequate understanding of why this is failing or how to correct it.

**Comment by ranchalp** [comment]
@crtlbreak- the error is probably the final expiry cltv. c-lightning uses way too small values for lnd. However this is not the llace for this. For things like thsj try the lnd slack or ethereum.stackexchange.

**Comment by ctrlbreak-** [comment]
FFS. I was instructed to come here and share that information from the slack.

**Comment by ranchalp** [comment]
If you have enough to suspect your issue may have to do with the actual implementation of `lnd`, then you should come here and open a new issue.
IMHO this is more of a particular problem I'd say. That's your call. 

In any case, you should not comment an open issue with a newly unrelated one, but rather open your own issue.

**Comment by halseth** [comment]
Using a list of pubkeys is actually supported already, I just think the documentation is not up-to-date.

**Comment by wpaulino** [comment]
> I argue for a new way of specifying the route: by giving a list of channel_ids.

Intermediate nodes along a route with non-strict forwarding (currently supported `Eclair` and `lnd`) will choose the best link for the next hop based on certain heuristics, e.g., highest bandwidth, etc., so passing in a list of `channel_id`s won't make a difference here.

**Comment by bockha** [comment]
The json data returned by queryroutes is very confusing and contains much redundant information for every hop. Which of this information is really mandatory for calling sendtoroute?

**Comment by ranchalp** [comment]
@halseth @wpaulino I have been going through the `pub_key` feature from #1944, it is really cool, and also I do agree that the difference is not vital when nodes are using non-strict forwarding. But it is not what I am suggesting. I did not make it clear enough though.

Basically, while the purpose of #1944  is to be able to route a payment without having to lookup in the graph, and thus a one-hop payment adding the `pub_key` would look like this:
```
{
    "routes": [
        {
            "total_time_lock": 1451790,
            "total_fees": "1",
            "total_amt": "51",
            "hops": [
                {
                    "chan_id": "1595091205233246209",
                    "chan_capacity": "16777215",
                    "amt_to_forward": "50",
                    "fee": "1",
                    "expiry": 1451646,
                    "amt_to_forward_msat": "50000",
                    "fee_msat": "1000",
                    "pub_key": "0389a4d10d30e6176ea7cd0a7060344108061fc9ca88b02fa52dacea4b0114b316"
                },
                {
                    "chan_id": "1595102200348803072",
                    "chan_capacity": "200000",
                    "amt_to_forward": "50",
                    "fee": "0",
                    "expiry": 1451646,
                    "amt_to_forward_msat": "50000",
                    "fee_msat": "0",
                    "pub_key": "034858c44d3710d5cffae3c2e3a62ff58b3755a495b681431d507d9b8705595e83"
                }
            ],
            "total_fees_msat": "1000",
            "total_amt_msat": "51000"
        }
    ]
}
```
I argue for a payment request of the following type:
```
{
    "routes": [
        {
            "hops": [
                {

                    "pub_key": "0389a4d10d30e6176ea7cd0a7060344108061fc9ca88b02fa52dacea4b0114b316"
                },
                {

                    "pub_key": "034858c44d3710d5cffae3c2e3a62ff58b3755a495b681431d507d9b8705595e83"
                }
            ],

        }
    ]
}
```

I realized now that this might be too open-ended for users since they do not choose the fees in this case and thus might end up paying more than desired, that's why perhaps this can be added as a feature to `queryroutes`. That is, now `queryroutes` only takes the `--dest` and `--amt` argument. 
I would argue to add a feature to call `queryroutes` exclusively with a list of `pubkeys` and `amt`. 

The reason is that while #1944 has its application, it does not solve the scenario I illustrated in the first comment when opening this issue: some users may only know the `pub_keys`/`channel_ids` of the route they want to take, and with current features (including #1944) they would have to call `queryroutes` with a big `num_max_routes`, search for the route they want, and then call `sendtoroute`. The output of `queryroutes` may not include the route the user wants, since it might not be among the best ones, and it might incur in much delay from retrieving a big amount of routes to search for one route that is already known.

This is the result of not having a feature/function to retrieve all the resulting values of the route automatically (`fee`, `total_fees_msat`, etc.).

**Comment by halseth** [comment]
`SendToRoute` can be used with pubkeys already, and there is fundamentally no way to enforce using particular `channel_ids`. The route can be constructed manually with a combination of `queryroutes` and `describegraph`.

One could always add more APIs and features to handle specific usecases, but IMO this should be done on the application level to avoid API bloat.
