### ISSUE TITLE
Faucet.lightning.community "unable to open channel" when trying to fund new node

### ISSUE THREAD

**Issue by becausetheypayme** [lightningnetwork/lnd#2401]
### Background

Faucet.lightning.community throws "unable to open channel" error when trying to fund new node

### Your environment

* "version": "0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"
* Linux LND 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
* Bitcoin Core RPC client version v0.17.0.1
* Running on Pi3+

### Steps to reproduce

1. > lncli connect 0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b@159.203.125.125

2. > lncli listpeers
 {
            "pub_key": "0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b",
            "address": "159.203.125.125:9735",
            "bytes_sent": "12084",
            "bytes_recv": "3258956",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": false,
            "ping_time": "59329"
        }

3. Browse to: https://faucet.lightning.community/
4. Input node info: "0276757d2192c55d2930f7843b586615173b37fa163ab4f1678a38a2300dd4fef8"
      From lncli getinfo: "identity_pubkey": "0276757d2192c55d2930f7843b586615173b37fa163ab4f1678a38a2300dd4fef8",

5. Input channel amount/initial balance defaults, as shown in fields

6. Click submit

7. Error displays

### Expected behaviour

Channel successfully created! message should display...

### Actual behaviour

Error "unable to open channel" displays unless channel/balance amounts increased. In this case I chose to add a zero to each default,1000000/500000, which worked.

Not a huge deal but for greenies like me, it was a PITA to figure out when the defaults didn't work. So may want to update. Or maybe it was just a fluke... Not sure. :-)

Thanks and Happy New Year!

**Comment by Roasbeef** [comment]
The proper spot for this issue is at https://github.com/lightninglabs/lightning-faucet thanks!
