### ISSUE TITLE
Error when opening channel to particular node Synchronizing Blockchain

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2406]
### Background

When connecting to the following node (the 9th node with the most amount of channels in testnet):
```
{
    "node": {
        "last_update": 1546472328,
        "pub_key": "0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b",
        "alias": "0270685ca81a8e4d4d01",
        "addresses": [
            {
                "network": "tcp",
                "addr": "159.203.125.125:9735"
            }
        ],
        "color": "#3399ff"
    },
    "num_channels": 142,
    "total_capacity": "1587488741"
}
```
The error I receive is: 
```
lncli-bob openchannel --node_key=0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b --local_amt=16777215
<684072ae52c507f8ebe9daf0caaab7b --local_amt=16777215
[lncli] rpc error: code = Code(102) desc = Synchronizing blockchain
```
However, this is a problem only with such node, none of the rest. Of course this is a problem of such node, not my node, or lnd, but the fact the error is `Synchronizing blockchain` is misleading. This is the output of `lnd`:
```
 [INF] FNDG: Starting funding workflow with 159.203.125.125:9735 for pendingID(...)
 [DBG] PEER: Sending MsgOpenChannel(temp_chan_id=10d5c92d0d4973157f3befb71368c9204200e515fe057b25001a860b6b32cf6e, chain=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, csv=2016, amt=0.16777215 BTC, push_amt=0 mSAT, reserve=0.00167772 BTC, flags=1) to 159.203.125.125:9735
 [DBG] PEER: Received Error(chan_id=10d5c92d0d4973157f3befb71368c9204200e515fe057b25001a860b6b32cf6e, err=) from 159.203.125.125:9735
 [INF] FNDG: Cancelling funding reservation for node_key=0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b, chan_id=10d5c92d0d4973157f3befb71368c9204200e515fe057b25001a860b6b32cf6e
 [ERR] FNDG: Received funding error from 0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b: 
 [ERR] RPCS: unable to open channel to NodeKey(0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b): rpc error: code = Code(102) desc = Synchronizing blockchain
```
### Your environment

btcd version 0.12.0-beta
lnd version 0.5.1-beta commit=v0.5.1-beta
Linux 4.13.0-36-generic #40~16.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

Just connect to the specified node and try to open a channel.

### Expected behaviour

A more descriptive error should come out

### Actual behaviour

Error Synchronizing Blockchain, while this is not the errors (as any other operation, even opening a channel with other nodes, works perfectly).

**Comment by Roasbeef** [comment]
It means the remote peer isn't synced.

**Comment by Dmitry1007** [comment]
My remote peer is synced and they have an open channel between them but I get the same exact error message "rpc error: code = Code(102) desc = Synchronizing blockchain"

Any idea of how to troubleshoot this?
