### ISSUE TITLE
gRPC in Python fails on StatusCode.RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by slush0** [lightningnetwork/lnd#2409]
### Background

Looks like increasing complexity of Lightning network triggers message size limits in gRPC Python implementation while calling DescribeGraph RPC:

```
Traceback (most recent call last):
  File "lndtools.py", line 89, in <module>
    main()
  File "lndtools.py", line 62, in main
    collect.collect(args, db, rpc)
  File "/home/bitcoin/lndstats/collect.py", line 288, in collect
    describegraph = rpc.DescribeGraph(ln.ChannelGraphRequest())
  File "/home/bitcoin/.local/lib/python3.5/site-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/bitcoin/.local/lib/python3.5/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (4746533 vs. 4194304)"
	debug_error_string = "{"created":"@1546533588.666415375","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"Received message larger than max (4746533 vs. 4194304)","grpc_status":8}"
```

### Your environment

* lncli version 0.5.1-beta commit=v0.5.1-beta-rc3-4-g8924d8fb20eb2abfd9cc93c6cc7eb6951184cb88-dirty
* Linux server01 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

### Steps to reproduce

```
describegraph = rpc.DescribeGraph(ln.ChannelGraphRequest())
```
### Expected behaviour

RPC call should return network graph of Lightning network.

### Actual behaviour

Exception about message limit raised.

I've actually found a workaround and the primary reason to open this issue is to tell others about the workaround. While default limit of gRPC message is 4MB, there's a way how to overload it:

```
channel = grpc.secure_channel(grpc_url, combined_creds, options=[
        ('grpc.max_send_message_length', 50 * 1024 * 1024),
        ('grpc.max_receive_message_length', 50 * 1024 * 1024)
        ])
```

However it is supposed as dirty hack as grpc developers mentions the message size should be rather in kilobytes than in megabytes: https://github.com/grpc/grpc/issues/7927#issuecomment-244845823

Considering the data structure in DescribeGraph will tend to expand in time, I propose to change DescribeGraph message to avoid such issue.

**Comment by Roasbeef** [comment]
See #2374. 

> Considering the data structure in DescribeGraph will tend to expand in time, I propose to change DescribeGraph message to avoid such issue.

Change it how?

**Comment by slush0** [comment]
Hm, I tried to search it before posting, but missed that issue. My bad and sorry for duplicate.

> Change it how?

Introduce paging / streaming.
