### ISSUE TITLE
Unable to broadcast funding tx: output already spent

### ISSUE THREAD

**Issue by bockha** [lightningnetwork/lnd#2410]
### Background

```
$ lncli openchannel --node_key 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365 --connect 95.211.207.81:9735 2000000
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.02 BTC only have 0.01570152 BTC  available
$ lncli walletbalance
{   
    "total_balance": "2562178",
    "confirmed_balance": "1570152",
    "unconfirmed_balance": "992026"
}
$ lncli openchannel --node_key 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365 --connect 95.211.207.81:9735 1000000
{
        "funding_txid": "ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274"
}
```
This looks ok, but the [created transaction](https://live.blockcypher.com/btc/tx/ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274/) is invalid and can not be broadcasted. The broken transaction is shown by pendingchannels and will stay there forever:
```
$ lncli pendingchannels
{
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365",
                "channel_point": "ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1",
                "capacity": "1000000",
                "local_balance": "999455",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "545",
            "commit_weight": "600",
            "fee_per_kw": "753"
        }
...
```
### Your environment

* lnd version 0.5.1-beta commit=v0.5.1-beta-252-ge6623f98b38f279900aaedf6a6993f34c3a45337
* Linux odroid 4.14.66-147 #1 SMP PREEMPT Wed Aug 22 13:24:49 -03 2018 armv7l armv7l armv7l GNU/Linux
* bitcoind 0.16.3

### Steps to reproduce

This seems to happen sporadically. 

### Expected behaviour

It should not use spent UTXOs to create funding transactions or at least it should remove the broken channel from the pending list.

### Actual behaviour
It creates a broken funding transaction that can never be broadcasted and keep the broken channel forerver in the pending open channels list.

### Log

```
2019-01-03 21:49:30.605 [INF] LNWL: Inserting unconfirmed transaction ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274
2019-01-03 21:49:30.635 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1): Transaction rejected: output already spent
2019-01-03 21:49:30.635 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1)
2019-01-03 21:49:30.635 [INF] CNCT: ChannelArbitrator(ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1): starting state=StateDefault
2019-01-03 21:49:30.635 [INF] NTFN: New block epoch subscription
2019-01-03 21:49:30.640 [INF] NTFN: New spend subscription: spend_id=144, outpoint=ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1, height_hint=556887
2019-01-03 21:49:30.705 [INF] FNDG: Finalizing pendingID(4736fb6125ca0fe4128f0c615fff390eb327f542faf4e04def99fef8d931b2a0) over ChannelPoint(ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1), waiting for channel open on-chain
2019-01-03 21:49:30.705 [INF] CNCT: Close observer for ChannelPoint(ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1) active
2019-01-03 21:49:30.705 [INF] NTFN: New confirmation subscription: txid=ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274, numconfs=3
2019-01-03 21:49:30.706 [INF] FNDG: Waiting for funding tx (ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274) to reach 3 confirmations
2019-01-03 21:49:31.086 [ERR] NTFN: Rescan to determine the spend details of ea17e0101b5154fd9e0ba335f7256b50dd76ff7eb89fa38ed1e0e2004132b274:1 failed: transaction not found within range
```

**Comment by Roasbeef** [comment]
Were you also sending coins concurrently over the RPC interface during this funding attempt or prior ones? Do you have any sort of automated system that either open channels or sends coins on chain?

**Comment by bockha** [comment]
I successfully opened about three channels before which were still waiting for their first confirmation. Then, as described above, I tried to open a channel and got the error about the insufficient witness outputs. The next try to open the channel with a lower capacity failed because of the spent utxo. I have no scripts doing automated on chain transactions. The autopilot is deactivated.

**Comment by hpbock** [comment]
It happened again this morning. In [this Logfile](https://privatebin.net/?bd100442a6885ba1#N/spAAIeqsP/3U98LD1HMLg2+z/A+Mp3x1DPHAfNKnQ=) you will see a first channel open, which took quite long, so I interrupted `lncli` with `STRG-C`. It though succeeded. The following try to open another channel failed with the spent UTXO.

**Comment by hpbock** [comment]
I meanwhile restarted `lnd` due to an update to `golang 1.11.4`. Right after the restart I tried to open another channel, which failed [according to the logfile](https://privatebin.net/?22643abe36e96c41#t4KsCYYT3vZS+LSu9E/Jay6zCmMco52ZKmZCTdpMcB0=) although `lncli` returned no error:
```
$ lncli openchannel --node_key 0276e09a267592e7451a939c932cf685f0754de382a3ca85d2fb3a864d4c365ad5 --connect 62.210.110.5:9735 xxxxxx
{
        "funding_txid": "a8304b941e2109c036411252c4136ddbe0c4fe9b1073359d1dca8fe9405c8697"
}
```

**Comment by wpaulino** [comment]
The 0.5.1 release included some migrations to restart the wallet with a clean transaction history in order to account for a lingering bug. By the time that these outputs were spent, the first release candidate (v0.5.1-beta-rc1) was already released. Do you recall if you had updated to this version prior to Nov 18th or before? This would help in reducing the possible number of code paths to see how exactly this bug could've happened.

**Comment by hpbock** [comment]
That time I updated my nodeabout weekly to the master branch on github. Unfortunately I can't recall when I upgraded to v0.5.1-beta-rc1.

**Comment by wpaulino** [comment]
Gotcha. Unfortunately, there isn't enough context to determine how this could've happened. I'd run the [`dropwtxmgr`](https://github.com/btcsuite/btcwallet/blob/master/cmd/dropwtxmgr/main.go) tool to force a rescan from your birthday to avoid the issue for now. If there is still an issue present that causes the wallet to have an inaccurate state, it'll probably happen again. You can also remove the invalid channels from `pendingchannels` by using the `abandonchannel` command available in a debug build of `lnd`. You can obtain one by just running `make` and using the `lnd-debug` binary found within the directory.

**Comment by bockha** [comment]
Thank you for your support! I will close this issue and keep an eye on it after rescanning.
