### ISSUE TITLE
Feature request: extend ListPayments response by original invoice memo

### ISSUE THREAD

**Issue by misovan** [lightningnetwork/lnd#2420]
### Background

I would like to propose to extend ListPayment response by memo information from the invoice the payment was based on. This information is necessary for easy identification of the payment by the user. Many standard payment formats implement such behavior.

### Proposed behaviour

```
        {
            "payment_hash": "14e42ffc411edea0e44ba00437b1e7a7e34995e1299d511506190f40341c30ae",
            "value": "2",
            "creation_date": "1546714044",
            "path": [
            ],
            "memo": "Payment for 2 pixels at satoshis.place.",
            "fee": "1",
            "payment_preimage": "ffaad08cf2a3983a46488bb2e44af3136832c8bf7705b6e868ed5e52f5ff638b"
        }
```

### Actual behaviour

ListPayments grpc api currently [returns](https://api.lightning.community/?shell#payment) an array of `Payment` objects. `Payment` does not contain `Memo` field from the invoice it was based on.

ListPayments returns list of payments stored in lnd database. Currently LND stores each payment into db (see AddPayment in [channeldb/payments.go](https://github.com/lightningnetwork/lnd/blob/master/channeldb/payments.go)) as `OutgoingPayment` type. This type definition already contains `Invoice`, but the actual memo data are not passed to it when saving payment to db (see savePayment in rpcserver.go).

### Proposal

1. Extend `rpcPaymentIntent` type by `memo` (in [rpcserver.go](https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go))
2. Extend extractPaymentIntent function so it sets `payIntent.memo` to `payReq.Description` value
3. Pass `memo` in dispatchPaymentIntent to savePayment function (function signature extended)
4. Extend listPayments response in rpcserver.go so it returns `Memo` set to stored `payment.Invoice.Memo` value (with Memo added as well to used `lnrpc.Payment` type)

Proposed change does not require any changes in db layer nor in channeldb/payments.go as relevant `OugoingPayment` type already implements `Invoice`.

Thanks for feedback.
Michal

**Comment by misovan** [comment]
I've [created a PR #2440](https://github.com/lightningnetwork/lnd/pull/2440) implementing the change

**Comment by alexbosworth** [comment]
This should be covered already, the full payment request is in the payment response

**Comment by misovan** [comment]
Yes it has been covered in a way, that full payReq data are available. While more flexible, that approach requires additional call / client impl of decoding it when invoice memo is needed.

**Comment by sako0938** [comment]
This is some code I've been working on to try and do some auditing of funds myself. 
`import lnd_grpc

c = lnd_grpc.Client()
payments = []

for i in c.list_payments().payments:
    payments.append(i)

#print(payments)
print(payments[0])

no_pr_count = 0

for pay in payments:
    pr = pay.payment_request
    if pr == "":
        print("This pr has no payment request attached")
        no_pr_count = no_pr_count + 1
    if pr != "":
        pr_info = c.decode_pay_req(pr)
        # if node doesnt exist this will error out
        try:
            print(c.get_node_info(pr_info.destination).node.alias )
        except Exception as e:
            print("This node is no longer online!")

        print(str(pay.value_sat) + "____" + str(pr_info.description) + "____" + str(pr_info.destination) + "\n\n" )

print("This many pr's don't have a pay req attached: %d" % no_pr_count )`

I have quite of bit of payments with no payment requests attached to them, which I am guessing are older payments. In addition, many don't have memos/description, so that makes it even more interesting. I'm also using the GetNodeInfo command to find the node alias. If the node has left the network (GetNodeInfo), and no memo was provided (DecodePayReq) then the payment from what I can tell becomes quite difficult to track down.

**Comment by wpaulino** [comment]
> I have quite of bit of payments with no payment requests attached to them, which I am guessing are older payments.

This is expected for some of the payments as they weren't handled correctly after restarts.

> In addition, many don't have memos/description, so that makes it even more interesting.

Nothing you can do as that's under control of the party issuing the payment request.

**Comment by wpaulino** [comment]
Closing as https://github.com/lightningnetwork/lnd/pull/2717 provides the payment request instead, which allows for more flexibility.
