### ISSUE TITLE
[Enquiry] HTLC timeout and channel concurrency

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2425]
I am a newbie and my target is to setup a payment router.

As far as i know, lightning channel uses HTLC for multi-hops payment. The default timelock value is normally 144 block (~ 1 day)

If timeout does occur, will my channel locked up for 24 hour and not able to route other payments?

**Comment by Roasbeef** [comment]
It depends on the size of the HTLC. If it's small, then we won't go to chain for it. If you're sending the payment, then another node upstream should cancel back that HTLC when the farthest one times out.
