### ISSUE TITLE
I have connected a testnet lnd node to a mainnet lnd node.

### ISSUE THREAD

**Issue by educob** [lightningnetwork/lnd#2441]
Hi.

Not sure if this is the place for this or if this is supposed to happen.

I am learning LN and I have my lnd node connected to testnet. I found a web with LN nodes and I thoght they'd be testnet nodes but they were mainnet.

I could connect to the mainnet node as a peer but then it failed when trying to create a payment channel.

`'Unknown chain=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943. Supported chain=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f'`

It seems weird to me that it's possible to connect nodes of different chains. Maybe it makes sense to have a payment that crosses chains (btc & ltc). Is that so?

Thanks.

ps: btw I cannot find a web with testnet lnd nodes. Is there any?

**Comment by wpaulino** [comment]
It's not possible to open channels between testnet and mainnet. It's possible to connect nodes between them because there is no way of identifying what network is node is running on just from their public key + IP address.

> ps: btw I cannot find a web with testnet lnd nodes. Is there any?

https://explorer.acinq.co/

**Comment by educob** [comment]
Thanks for the explorer.
