### ISSUE TITLE
LND will not open channel with c-lightning

### ISSUE THREAD

**Issue by fluidvoice** [lightningnetwork/lnd#2443]
### Background

Can connect to a c-lighting node but cannot open a channel. 
Works OK with other LND nodes.
Same problem as this issue:
https://github.com/lightningnetwork/lnd/issues/2250#issue-386391316
I've talked to another LND user who says he has the same problem.

### Your environment
lnd 0.5.1-beta
Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Bitcoin Core Daemon version v0.17.0.1
Raspberry Pi (Raspiblitz project)

### Steps to reproduce

Connect and try to openChannel to:
03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@199.96.236.9:9735

### Actual behaviour

Openchannel times out/fails.
Disconnecting 199.96.236.9:9735, reason: Peer 199.96.236.9:9735 no answer for 5m0s -- disconnecting
unable to open channel to NodeKey(): peer disconnected
[lncli] rpc error: code = Unknown desc = peer disconnected

performing same to this node succeeds:

> 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c@mainnet.node.lightningpowerusers.com:9735

[lnd.log.175.txt](https://github.com/lightningnetwork/lnd/files/2741907/lnd.log.175.txt)

**Comment by fluidvoice** [comment]
admin@thundahub:~ $ lncli listchannels
{
    "channels": [
        {
            "active": false,
            "remote_pubkey": "02e55281b6555dc72275a4a6809df347edc02c23e43826a916dfa1702d86005170",
            "channel_point": "c87357cfdbee9c6b7302809a278553d350d2b2a6c48b6bcba04383714f6eaba8:1",
            "chan_id": "612964538441269249",
            "capacity": "250000",
            "local_balance": "245386",
            "remote_balance": "0",
            "commit_fee": "4614",
            "commit_weight": "600",
            "fee_per_kw": "6374",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "20",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": false,
            "remote_pubkey": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c",
            "channel_point": "6c9f793113ab7cc32a60eaf3482a55f82d45df1f7b3ab19f68adef14fea3b327:0",
            "chan_id": "613132763720777728",
            "capacity": "30000",
            "local_balance": "25385",
            "remote_balance": "0",
            "commit_fee": "4615",
            "commit_weight": "600",
            "fee_per_kw": "6375",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "10",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        }
    ]
}

**Comment by wpaulino** [comment]
Hard to tell why this is happening without the logs of the c-lightning node. I do know that they have certain heuristics in place to prevent opening channels with peers whom a force close has recently happened with, etc.

**Comment by fluidvoice** [comment]
> Hard to tell why this is happening without the logs of the c-lightning node. I do know that they have certain heuristics in place to prevent opening channels with peers whom a force close has recently happened with, etc.

Are there any really easy means to startup a c-lightning node in the cloud?  If so I can run that, try to reproduce the problem, and get logs from the other side as well.

**Comment by Roasbeef** [comment]
I'd open this issue in the c-lightning repo instead. On our side, they simply never respond to anything. They've been having some issues with crashing nodes given certain HTLC parameters.

**Comment by fluidvoice** [comment]
for reference. The c-lightning/ElementsProject opened issue:
https://github.com/ElementsProject/lightning/issues/2241#issue-397775854
