### ISSUE TITLE
Feature request: SubscribeOpenChannel gRPC stream

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#2451]
### Background

Cant get OpenChannel gRPC stream when other node opens a channel against me. 

Suppose I'm  node A, and another node B opens the channel with me. i want the feedback, but (B) is going to be receiving the streaming.

### Expected behaviour

It would be nice to have a subscribeOpenChannel  in gRPC, that allows a 3rd party to receive the streaming that produces OpenChannel, just the same but consumed by other

GREAT PROJECT!

**Comment by Roasbeef** [comment]
See #1988

**Comment by danielemiliogarcia** [comment]
@Roasbeef that PR only informs  (active, inactive, closed) i mean to have the full openchannel streaming https://api.lightning.community/?javascript#openchannel 

Parameter | Type | Description
-- | -- | --
chan_pending | PendingUpdate |  
confirmation | ConfirmationUpdate |  
chan_open | ChannelOpenUpdate

**Comment by Roasbeef** [comment]
We can't know that information, as we don't know when they broadcast the channel. Once it's confirmed, then that'll give you an update for a new channel (opened).

**Comment by danielemiliogarcia** [comment]
could that be possible if it receives  "remote_node_pub" or "channel_point" as an in parameter? o could get those asking the node for pendingchannels

**Comment by wpaulino** [comment]
We already watch channels opened to us anyway, so we can assume it is pending as soon as we've exchanged `funding_signed` and send a `PendingUpdate`. Then, once we see it in a block, we can begin to send `ConfirmationUpdate`s and a final `ChannelOpenUpdate` once fully confirmed.
