### ISSUE TITLE
Strange channel transition from "opened" to "opening" state

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#2456]
### Background

We have internal channel state syncing mechanism, and sometimes we see that channel goes from opened to opening state.

[Example of such channel](https://btc.com/ad90e5234500351defee20a592ae827fcf92ada29cf3ba2b101658c30d997e3c), currently this channel is in pending state.

### Your environment
* version of `lnd`:
v0.5.1-beta-b07499f227bd78dbceaa8c6ee047f1c033716cdf

* which operating system (`uname -a` on *Nix):
Linux 8dd68dd62928 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend:
bitcoind-0.17.0

### Expected behaviour
If channel moves to opened state it shouldn't go back to opening state, until it is update of capacity, which is not implemented yet.

I have logs for ad90e5234500351defee20a592ae827fcf92ada29cf3ba2b101658c30d997e3c channel, which is in the opening state, but in explorer we could see ~240 confirmation on time of writing this issue. Logs are in CSV format, sorry for that  : )

[opened_opening_transition.csv.zip](https://github.com/lightningnetwork/lnd/files/2749363/opened_opening_transition.csv.zip)

**Comment by wpaulino** [comment]
Which state transition are you referring to? The second one is a known issue (see #1806).

1. openchannel -> broadcast -> pendingchannels -> confirms -> listchannels -> back to pendingchannels
2. openchannel -> broadcast -> pendingchannels -> confirms -> still in pendingchannels

Nothing looks out of the ordinary to me in the logs. If you restart the node, it _should_ show under listchannels again. Could you post the logs after the restart as well?

**Comment by Roasbeef** [comment]
By opening you mean it goes back to `pendingchannels`?

**Comment by Roasbeef** [comment]
Does it disappear from `listchannels`?

**Comment by AndrewSamokhvalov** [comment]
@Roasbeef yes, but let me try to catch another one, probably this is the issue with our logic. Or wait until someone else confirms the issue.

**Comment by AndrewSamokhvalov** [comment]
Update: channel moved to `listchannels`
