### ISSUE TITLE
Accept running tor hidden service even if clearnet listening is enabled

### ISSUE THREAD

**Issue by ketominer** [lightningnetwork/lnd#2458]
### Background

I would like to help liquidity between tor and clearnet nodes. For this, I want to run nodes listening both on the clearnet and on a hidden service.

While in usual cases it's probably a bad idea, I think the user should have the liberty to do it anyway, maybe with an extra option to be sure that the user knows what they're doing.

If I'm missing something here please let me know.

### Steps to reproduce

Configure a node with a hidden service and clearnet listening different from localhost

### Expected behaviour

lnd should allow the user to do it

### Actual behaviour

"lnd must *only* be listening on localhost when running with Tor inbound support enabled" message appears and lnd shuts down.

**Comment by Roasbeef** [comment]
Yep, as said above this is possible, but requires you to do a bit more manual work. We don't have any plans to make this automated atm, as we want to ensure we avoid easy footguns of people leaking their IP's. We assume that more advanced users that understand the potential pitfall, will also be able to make a manual `torrc` file to address this.
