### ISSUE TITLE
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

### ISSUE THREAD

**Issue by kaotic818** [lightningnetwork/lnd#2459]
### Background

Describe your issue here.

Ive looked at other issues and nobody describes a solution

### Your environment
Windows 10 1803 64 bit

* version of `lnd` 

latest version
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

https://github.com/ecurrencyhodler/Litecoin-Resources/blob/master/LTC%20Guides/LTC%20Lightning%20Network%20lnd%20Guide%20(Win).md 

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by kaotic818** [comment]
debuglevel=info
alias=xxxxx
maxpendingchannels=10
datadir=$LOCALAPPDATA/Lnd/data
rpclisten=127.0.0.1:10009
restlisten=127.0.0.1:10010
litecoin.mainnet=1
litecoin.active=1
litecoin.node=litecoind
litecoind.rpchost=localhost
litecoind.rpcuser=xxxxx
litecoind.rpcpass=xxxxx
litecoind.zmqpubrawblock=tcp://127.0.0.1:28332
litecoind.zmqpubrawtx=tcp://127.0.0.1:28333

**Comment by heatbreak21** [comment]
Did you fix this problem? If so can you let me know what you did

**Comment by kaotic818** [comment]
Yes. It was the RPC listener which Ecurrency holder on twitter gave me a new conf file that had the update to it. Also my conf files i needed to name .conf they had .txt still.

________________________________
