### ISSUE TITLE
Channels suddenly closed and most funds gone

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#2476]
### Background

I am not sure exactly what happened, hopefully someone can help me figure it out. Five channels or so closed and my channelbalance went from 4491462 to 563801 overnight. 

First I though my server had been hacked, but another lighting node that I run have suddenly received about 2000000 sat from that node. So at least half of the channel balance was sent there, and the channel was closed and settled on the blockchain. 

Leading me to believe that my node somehow sent old state(s) and was "punished", then my other node and some other lightning nodes received all the funds on those channels?

I don't want to publish my node identification here, but I can send that info if someone think they can help me at least figure out what happened exactly, and perhaps how to prevent it in the future.. 

### Your environment

* version of `lnd`

 "version": "0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d"

* which operating system (`uname -a` on *Nix)

Linux RaspiBolt 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

 "version": 160300,
  "protocolversion": 70015,

**Comment by Roasbeef** [comment]
Look at `lncli closedchannels`. If you're online, then any peer can close a channel at will.

**Comment by hakonamatata** [comment]
> 
> 
> Hi @hakonamatata, that is certainly a plausible sequence of events, though it's hard to know without more info. Are you on our slack or IRC? Happy to assist you there if you don't want to publish information publicly.

Yeah, if there is a slack channel for example. I can post all details there. 

> 
> 
> Look at `lncli closedchannels`. If you're online, then any peer can close a channel at will.

Is there a way to see if a channel has been closed because the lightning node was "punished" ? 

I see a lot of ""LOCAL_FORCE_CLOSE", ""REMOTE_FORCE_CLOSE", ""COOPERATIVE_CLOSE", but these are all normal behavior. Not causing my funds to be taken. I am guessing.

**Comment by hakonamatata** [comment]
After discussing on slack it turns out it's all good. There is a few pending channels with all the satoshi that will be released in 115 blocks. 

I was confused because "pending_open_balance" said 0. I assumed that if there was satoshis in limbo waiting to be paid out, it would show up there.
