### ISSUE TITLE
[Question] How to generate macaroon files manually

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2480]
I am trying to automate docker app setup. lnd and btcd are in different containers.

My goal is to be as user friendly as possible. When docker build is completed, the rpc certificates and macaroon files are expected to be ready in folder specified by user.  The files are for external lncli or web interface application.

During docker build phase, rpc certs can be generated by openssl, but how can the macaroon files be generated?

**Comment by halseth** [comment]
You must run `lnd` for the macaroon files to be generated.

**Comment by Roasbeef** [comment]
You can modify the cert generation with additional arguments for lnd. Check out `lnd -h`.

**Comment by lsching17** [comment]
> You can modify the cert generation with additional arguments for lnd. Check out `lnd -h`.

I tried to generate a wildcard cert by parameter '  --tlsextradomain="*"  

But lncli shows the following error message

`$lncli --rpcserver=a.b.com:10001 --macaroonpath=data/chain/bitcoin/testnet/readonly.macaroon getinfo
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for lubuntu, localhost, *, unix, unixpacket, not a.b.com"`

Is it a bug or expected behaviour?
