### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by ac-com-au** [lightningnetwork/lnd#2488]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
You didn't fill out the template. We can't address your issue if you give no information.

**Comment by ac-com-au** [comment]
upgrade LND  
make & make install fails 
lncli version 0.5.1-beta commit=v0.5.1-beta-rc3-2-g712fc3ebed1c9e0df6bad2b240acce1a0804b1d2-dirty

Linux s3 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Bitcoin Core RPC client version v0.17.0rc4

cd $GOPATH/src/github.com/lightningnetwork/
git pull
make && make install

-------------------------------

samh@s3:~/gocode/src/github.com/lightningnetwork/lnd$  make && make install
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-411-g099d2603187395585b1d6cc9d53c9e96bc1534dd" github.com/lightningnetwork/lnd
github.com/lightningnetwork/lnd/channeldb
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb/bdb
github.com/lightningnetwork/lnd/macaroons
# github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb/bdb
vendor/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:12:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
vendor/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:55:10: undefined: bbolt
github.com/lightningnetwork/lnd/nat
# github.com/lightningnetwork/lnd/nat
nat/pmp.go:35:19: undefined: natpmp.NewClientWithTimeout
# github.com/lightningnetwork/lnd/macaroons
macaroons/service.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
macaroons/store.go:10:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
macaroons/store.go:49:2: bbolt is not a package
macaroons/store.go:49:2: undefined: DB
# github.com/lightningnetwork/lnd/channeldb
channeldb/channel.go:16:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/db.go:13:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/db.go:106:2: bbolt is not a package
channeldb/forwarding_log.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/forwarding_package.go:10:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/graph.go:20:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/invoices.go:12:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/meta.go:3:8: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/migrations.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/nodes.go:11:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/nodes.go:11:2: too many errors
Makefile:100: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by Roasbeef** [comment]
You need to install Go 1.11, and remove your vendor directory in the `lnd` folder.

**Comment by ac-com-au** [comment]
thank you  👍

**Comment by ac-com-au** [comment]
installed Go 1.11 and removed vendor directory  make && make install FAILS.
samh@s3:~/gocode/src/github.com/lightningnetwork/lnd$  make && make install
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-411-g099d2603187395585b1d6cc9d53c9e96bc1534dd" github.com/lightningnetwork/lnd
github.com/lightningnetwork/lnd/channeldb
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb/bdb
# github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/walletdb/bdb
vendor/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:12:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
vendor/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:55:10: undefined: bbolt
github.com/lightningnetwork/lnd/macaroons
github.com/lightningnetwork/lnd/nat
# github.com/lightningnetwork/lnd/nat
nat/pmp.go:35:19: undefined: natpmp.NewClientWithTimeout
# github.com/lightningnetwork/lnd/macaroons
macaroons/service.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
macaroons/store.go:10:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
macaroons/store.go:49:2: bbolt is not a package
macaroons/store.go:49:2: undefined: DB
# github.com/lightningnetwork/lnd/channeldb
channeldb/channel.go:16:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/db.go:13:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/db.go:106:2: bbolt is not a package
channeldb/forwarding_log.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/forwarding_package.go:10:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/graph.go:20:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/invoices.go:12:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/meta.go:3:8: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/migrations.go:9:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/nodes.go:11:2: imported and not used: "github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt" as bolt
channeldb/nodes.go:11:2: too many errors
Makefile:100: recipe for target 'build' failed
make: *** [build] Error 2
samh@s3:~/gocode/src/github.com/lightningnetwork/lnd$

**Comment by ac-com-au** [comment]
problem solved  I just reinstalled fresh LND installation
