### ISSUE TITLE
Docker LND doesn't persist state across reboots

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#2508]
I noticed the docker `lnd` service doesn't persist state across container restarts.  If we added a container this would allow more permanent storage for the container.

**Comment by jrosco** [comment]
wouldn't this be up to the user to handle themselves?

**Comment by yancyribbens** [comment]
@jrosco what do you mean exactly?  The volume can always be deleted if the user wants to remove the stored state.

**Comment by jrosco** [comment]
It sounds to me like you need to add a persistent volume to your build configure. If so, this can easily be added using docker-cli, docker-compose, k8s etc. Although I could be incorrectly understanding you, in which case I can safely be ignored :)

**Comment by yancyribbens** [comment]
@jrosco thanks for the feedback and actually I think you're right.  This should be not on the Dockerfile but instead in docker-compose to be run during run-time :/.   Testing that out now.

**Comment by yancyribbens** [comment]
https://github.com/lightningnetwork/lnd/pull/2533

**Comment by guggero** [comment]
Fixed by #2533.
