### ISSUE TITLE
it should be simple to start setup with `docker-compose up`

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#2509]
It should be simple to start lnd using `docker-compose up` and have everything "just work" however some services fail.  we could also split out a seperate `yml` file for use with `litecoin` in case someone wants to choose which type of node they run.  So for example, if someone did `docker-compose up` this would just run the `btc` setup, but if instead they did `docker-compose -f docker-compose.ltc.yml up` then it would run just litecoin or both perhaps.  splitting out a seperate `yml` file would also make testing and development simpler imo.

**Comment by yancyribbens** [comment]
i'd be happy to be assigned this if it seems like a good idea.

**Comment by darwin** [comment]
I put quite some effort into a project which can generate a simnet cluster which works out-of-the-box:
https://github.com/darwin/simverse

When you generate default one via `./sv create` you can look at generated `docker-compose.yml` and related docker files and scripts under `_workspace/default`. This could be some inspiration for implementing refresh of docker support here.

**Comment by guggero** [comment]
Fixed by #2699.
