### ISSUE TITLE
Update verifymessage to return more specific signature validation response

### ISSUE THREAD

**Issue by jamaljsr** [lightningnetwork/lnd#2510]
### Background

I am implementing Sign & Verify features into the Lightning Joule browser plugin. We would like to allow websites to authenticate users by having them sign a message using their lightning node private key. The website will then take the signed message and verify it on their backend using their own lightning node. There's a more detailed explanation on the Joule Extension [issue 146](https://github.com/wbobeirne/joule-extension/issues/146).

Currently, the LND `verifymessage` command will return `valid: false` when the signature is not valid and also if the signing node is not in the verifying node's graph. It would be a better UX to distinguish between these two failures because in the second case, the website can inform the user to connect to our node to allow the verification to succeed.

### Your environment

* LND: Version: 0.5.1-beta commit=v0.5.1-beta-250-gbd0177ddc5a6e296f9f67a6f857527a1bc82fef0
* BTCD: Version 0.12.0-beta

### Steps to reproduce

The existing behavior can be reproduced by running the `testNodeSignVerify` test in the [lnd_test.go](https://github.com/lightningnetwork/lnd/blob/master/lnd_test.go#L8428)

To repro using the CLI, you would need to setup 3 nodes, `alice`, `bob` and `carol`.
1. Open a channel from `alice` to `bob`. Leave `carol` disconnected from the other two
2. Sign a message on `alice` using `lncli signmessage hello`. The command will return a `signature`
3. Verify the message on `bob` using `lncli verifymessage hello <signature>`
4. You should receive the response `{ "valid": true, "pubkey": <alicepubkey> }`
5. Verify the message again on `bob` with an invalid message using `lncli verifymessage goodbye <signature>`
6. You should receive the response `{ "valid": false, "pubkey": <alicepubkey> }`
7. Verify the message using `carol` using `lncli verifymessage hello <signature>`
8. You should receive the response `{ "valid": false, "pubkey": <alicepubkey> }`

After additional testing, I also observed that if `carol` was once a peer of `alice` or `bob` then `verifymessage` will return `valid: true` even if she disconnects from all peers in the network. 

9. Add `bob` as a peer of `carol` using `lncli connect <bobpubkey>@<bobhost>`
10. Verify the message using `carol` using `lncli verifymessage hello <signature>`
11. You should receive the response `{ "valid": true, "pubkey": <alicepubkey> }`
12. Remove `bob` as a peer of `carol` using `lncli disconnect <bobpubkey>`
13. Verify the message using `carol` using `lncli verifymessage hello <signature>`
14. You should receive the response `{ "valid": true, "pubkey": <alicepubkey> }`

### Expected behavior

It would be good if `verifymessage` distinguished between "invalid because the message/signature pair doesn't match" versus "invalid because the signing node was never in my graph".

### Actual behavior

The `verifymessage` command returns `valid: false` when the signature is not valid and also if the signing node is not in the verifying node's graph.

### Proposed solution
Return two validation results in the `verifymessage` response:
- `sig_valid`: the message/signature pair is valid 
- `graph_valid` indicates that the signing node is in the graph

Example: `{ "graph_valid": true, "sig_valid": true, "pubkey": <pubkey> }`. 

If backwards compatibility is a concern, then `graph_valid` can remain named `valid` with the same behavior, but the `sig_valid` can be added. The documentation should also be updated to explain exactly what `valid` means.

I would be happy to submit a PR once a final solution is decided.

**Comment by ccdle12** [comment]
I'd be happy to pick this one up, I've already updated on my branch according to the above request, in the process if looking for/writing tests.

**Comment by alexbosworth** [comment]
Should note that signing and verifying messages using your pubkey is also possible with the standard payment request API. All payment requests lnd makes are signed with your key and validating even in-browser is pretty easy

**Comment by jamaljsr** [comment]
@alexbosworth are you referring to the AddInvoice GRPC endpoint, using the memo field?

**Comment by alexbosworth** [comment]
Yes the memo field is also signed by the node key

**Comment by dmidnight** [comment]
@alexbosworth can you point me towards an example of verifying a message in javascript/browser, or a hint on how to go about it?

**Comment by alexbosworth** [comment]
this website https://lndecode.com/ does js client side decoding of a payment request so I guess they are doing it

**Comment by dmidnight** [comment]
Looks marked as TODO there... For anyone else interested, I found an example here: https://github.com/nerddan/ln-crypto

**Comment by halseth** [comment]
@jamaljsr @dmidnight Were you able to find a workaround, and we can close this one?

**Comment by jamaljsr** [comment]
all good here. thanks!

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/2510#issuecomment-535050893
