### ISSUE TITLE
[Feature Request] Redeemable gift cards or 'reverse invoices'  

### ISSUE THREAD

**Issue by baebb** [lightningnetwork/lnd#2518]
Hi there! First off big thanks for all the work on LND and congrats on Sphinx Send @Roasbeef ! 

I've been looking over the developer guide to facilitate a UX flow I had in mind, but found no clear solution. I'd like to create redeemable gift cards of BTC. 

My 'dream' flow would be something as simple as the LND invoicing system. The recipient of the gift card would scan/input the lnbc invoice code and then receive a pre-nominated amount of msats from the payer.

Alternatives I've looked at but don't exactly fit my desired UX flow:

- Opening a new channel and specifying a push amount. _This requires knowing the payee's public address already._ 

- Creating a new wallet with the redeemable btc funds on it, then giving the private key to the payee. _This puts too much trust in the payer._

I think this feature would be a great way to onboard new users to Lightning. They would see how easy it is receive funds instantaneously and would have installed a lightning-capable wallet. 

Thank you for reading

**Comment by Roasbeef** [comment]
Seems there'd need to be some sort of payment server in order for this to work correctly. So after scanning the gift card, the receiver pings the service telling it to send (passing in w/e card ID or the like), the the server sends the payment to the receiver.

**Comment by justrossthings** [comment]
@Roasbeef https://github.com/donnerlab1/lightning-voucher has something like that [and they intend to implement sphinx send]. 

I'd like to avoid intermediaries ideally. How crazy is an LN invoice with a negative value?
