### ISSUE TITLE
Invoice payment stuck

### ISSUE THREAD

**Issue by corbelantoine** [lightningnetwork/lnd#2524]
### Background

I have a direct channel opened to BlueWallet's node (03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268).
The channel is sufficiently funded and the connexion is not broken:
`lncli connect 03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268@207.180.244.165:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 127.0.0.1:33862`
--> I'm using reverse port forwarding as a proxy

### Your environment

* version of `lnd`
`lnd --version
lnd version 0.5.1-beta commit=v0.5.1-beta-343-g55b580f2b80d2e62af4067d3ddf8688614bf0914`

* which operating system (`uname -a` on *Nix)
Linux HOST_NAME 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.1

* any other relevant environment details
Tor is setup. There is two ways to connect to me: Tor onion v2 or using an ipv4 public IP on an AWS server that forwards everything on port 9735 to my localhost.

### Steps to reproduce
Create an invoice on bluewallet app:
`lnbc1u1pwyvyhypp5mzretv6qjjg3c2s50sws6nnepua473n4lf6ruqsm0aruh7flspasdq823jhxaqcqzysfsmkfs7qgw3v557fs20h4xrj5kma9wfmd57snx2kxxkutysdx3ws8ez0qjl7crla93vsnr4sgtp9u537cwh3pqtv0t3srm3qcnwzaecpgvenqc`

`lncli payinvoice XXX...`

### Expected behaviour

Payment should be paid instantly.

### Actual behaviour

`lncli payinvoice lnbc1u1pwyvyhypp5mzretv6qjjg3c2s50sws6nnepua473n4lf6ruqsm0aruh7flspasdq823jhxaqcqzysfsmkfs7qgw3v557fs20h4xrj5kma9wfmd57snx2kxxkutysdx3ws8ez0qjl7crla93vsnr4sgtp9u537cwh3pqtv0t3srm3qcnwzaecpgvenqc
Description: Test
Amount (in satoshis): 100
Destination: 03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268
Confirm payment (yes/no): yes`

Payment stuck here. No log being displayed (as INFO).
While this is stuck I could send some sats to the app "Wallet of Satoshi" and pay the same invoice from there.
This also happened yesterday, I wanted to wait in case it was a network issue.

State of the channel:
"capacity": "450000",
"local_balance": "45950",
"remote_balance": "403604",
"commit_fee": "446",
"commit_weight": "724",
"fee_per_kw": "616",
"unsettled_balance": "0",
"total_satoshis_sent": "403604",
"total_satoshis_received": "0",
"num_updates": "2",
"pending_htlcs": [
],
"csv_delay": 144,
"private": false

**Comment by Roasbeef** [comment]
I'd file an issue with blue wallet.

**Comment by corbelantoine** [comment]
https://github.com/BlueWallet/LndHub/issues/9

It is probably an issue with LND. Everything is explained there. Happy to provide more info if you want to reopen the issue... I'm keeping the log just in case.

**Comment by Roasbeef** [comment]
It's a small enough of a payment that we won't go to chain to claim it, their node just held onto the payment. I don't know what their node is running as far as extra patches to allow it to be a custodial multi-user wallet. Also likely the case that the node can be DoS'd etc, since it's so widely publicized.

**Comment by Lavande** [comment]
Experiencing the same issue here(cli got stuck after having typed 'yes' for payment with nothing useful from logs).
I tried several times with different repients (tippin.me, Y'alls, etc). It seems that it's a network connection problem. Some went through while some didn't, and sometimes some went through. *_*
Observing.

**Comment by halseth** [comment]
Using debug logs should show what's happening.
