### ISSUE TITLE
[lncli] rpc failure for wildcard certificate

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2525]
I would like to generate a wildcard certificate that support any domain. I think domain validation is meaningless for self-signed certificate.

i pass parameter ' --tlsextradomain="*" to lnd

But lncli shows the following error message ("a.b.com" is a dummy domain defined in /etc/hosts)

`$lncli --rpcserver=a.b.com:10001 --macaroonpath=data/chain/bitcoin/testnet/readonly.macaroon getinfo 

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for lubuntu, localhost, *, unix, unixpacket, not a.b.com"`

Is it a bug or expected behaviour?

**Comment by lsching17** [comment]
This is the details of the certificate

`$ openssl x509 -in tls.cert -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7c:59:62:ef:92:dd:d0:d6:36:4d:15:a2:61:5e:9d:f5
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: O = lnd autogenerated cert, CN = lubuntu
        Validity
            Not Before: Jan 17 07:06:59 2019 GMT
            Not After : Mar 13 07:06:59 2020 GMT
        Subject: O = lnd autogenerated cert, CN = lubuntu
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:88:fd:ea:4b:cd:b7:67:64:6b:d0:0a:4a:e3:fc:
                    94:26:ab:93:55:cc:20:71:aa:ad:48:65:d3:8d:88:
                    83:d1:73:1e:81:40:ee:16:e9:86:93:be:1a:14:77:
                    1d:7d:0b:f1:1d:dc:6b:ae:4e:55:44:23:29:e0:70:
                    4c:a7:ec:f9:31
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Alternative Name: 
                DNS:lubuntu, DNS:localhost, DNS:*, DNS:unix, DNS:unixpacket, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:192.168.42.213, IP Address:FE80:0:0:0:1892:70EF:174B:E1FC
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:93:4c:71:36:b7:4a:74:d8:c4:c7:c3:be:b5:
         fe:bc:91:9b:38:c7:e0:97:bc:3d:d4:6f:0b:3a:f0:51:b8:c3:
         d3:02:21:00:a1:2b:b4:23:fb:2d:9a:bf:ba:41:f5:af:a1:8e:
         18:f1:d1:f1:cf:e3:b5:b4:8c:00:50:f7:86:60:f4:d3:9d:3c
-----BEGIN CERTIFICATE-----
MIIB7jCCAZOgAwIBAgIQfFli75Ld0NY2TRWiYV6d9TAKBggqhkjOPQQDAjAzMR8w
HQYDVQQKExZsbmQgYXV0b2dlbmVyYXRlZCBjZXJ0MRAwDgYDVQQDEwdsdWJ1bnR1
MB4XDTE5MDExNzA3MDY1OVoXDTIwMDMxMzA3MDY1OVowMzEfMB0GA1UEChMWbG5k
IGF1dG9nZW5lcmF0ZWQgY2VydDEQMA4GA1UEAxMHbHVidW50dTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABIj96kvNt2dka9AKSuP8lCark1XMIHGqrUhl042Ig9Fz
HoFA7hbphpO+GhR3HX0L8R3ca65OVUQjKeBwTKfs+TGjgYgwgYUwDgYDVR0PAQH/
BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wYgYDVR0RBFswWYIHbHVidW50dYIJbG9j
YWxob3N0ggEqggR1bml4ggp1bml4cGFja2V0hwR/AAABhxAAAAAAAAAAAAAAAAAA
AAABhwTAqCrVhxD+gAAAAAAAABiScO8XS+H8MAoGCCqGSM49BAMCA0kAMEYCIQCT
THE2t0p02MTHw761/ryRmzjH4Je8PdRvCzrwUbjD0wIhAKErtCP7LZq/ukH1r6GO
GPHR8c/jtbSMAFD3hmD00508
-----END CERTIFICATE-----`

**Comment by guggero** [comment]
Only saw this issue now. This is not how wildcard certificates work. You cannot just add a single `*` and expect it to be valid for all domains. Wildcards only apply to subdomains. So for your case you can try adding `*.b.com` and see if that works (not sure though). But anyway, the recommended/supported way for your use case is to add all your possible domains with multiple `--tlsextradomain` flags and not use any wildcard.
