### ISSUE TITLE
Switching from bitcoind to neutrino results in broken behavior

### ISSUE THREAD

**Issue by tdickman** [lightningnetwork/lnd#2526]
### Background

Switching an lnd node from `bitcoin.node=bitcoind` to `bitcoin.node=neutrino` results in [weird behavior](https://lightningcommunity.slack.com/messages/C6BDA6DGE/convo/C6BDA6DGE-1548173508.155300/). Namely, nodes with existing connections are unable to connect anymore, and new nodes are unable to establish new connections.

### Your environment

* version of `lnd`: `lncli version 0.5.1-beta commit=v0.5.1-beta-dirty`
* which operating system (`uname -a` on *Nix): `Linux nodes-lnd-6665fd9d6d-2d7g9 4.15.0 #1 SMP Mon Jul 16 20:23:29 UTC 2018 x86_64 Linux` (running inside docker container in Kubernetes cluster)
* version of `btcd`, `bitcoind`, or other backend: `arilot/docker-bitcoind:0.15.1`
* any other relevant environment details

### Steps to reproduce

Create a new lnd node and sync it using a bitcoind node. Establish a channel with the node. Update the config to use neutrino, and restart.

### Expected behaviour

Node continues operating normally, or node returns an error message upon startup.

### Actual behaviour

Node start normally, and syncs blocks on startup. Other nodes that have open channels with us are unable to reconnect to us (channel remains inactive). Other nodes are also unable to establish new channels with us.

**Comment by Roasbeef** [comment]
This isn't supported. You can't switch to neutrino as no headers are on disk. As is you can only switch between full node operating nodes, and not also neutrino.

**Comment by tdickman** [comment]
Totally understand, and that's what I gathered from from conversation with folks on Slack. Someone suggested that I post this since it might make sense to at least have an error message at startup rather than what appeared to be a valid startup, and then broken behavior.

**Comment by philippgille** [comment]
I also think an error message during startup makes sense in this case. Maybe this issue can be reopened (and renamed to something like `Add error message during startup when switching from bitcoind/btcd to Neutrino`)?

Or is there a plan to support the switch in the future, making the implementation of an error message at this point a useless effort?
