### ISSUE TITLE
Can't open a channel - maxValueInFlight too large: 4000000000 mSAT, max is 301000000 mSAT

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#2539]
### Background

I'm trying to open a channel from Bitcoin Lightning Wallet using master and getting an error message that seems backwards so figured I would report and roll back to last release.

### Your environment

* version of `lnd` lnd version 0.5.1-beta commit=v0.5.1-beta-509-gecd5541d55fbf1218662d0d95b220411f25415ed
* which operating system (`uname -a` on *Nix) Ubuntu 18
* version of `btcd`, `bitcoind`, or other backend - bitcoind .17
* any other relevant environment details

### Steps to reproduce

1. Spin up a lnd node
2. Open "Bitcoin Lightning Wallet" on Android and open a channel to the lnd node
  - min is 300000 sats 
3. check LND logs

### Expected behaviour

Channel should open or an error message that makes sense should be displayed

### Actual behaviour

Note the error indicates the `maxValueInFlight too large: 4000000000 mSAT, max is 300000000 mSAT` but 300000000 was the amount I tried to open it for, not the max.  It's actually 1 decimal place less sats as well so it is well under the limit from my understanding.

```
lnd_1       | 2019-01-26 00:11:55.664 [INF] FNDG: Recv'd fundingRequest(amt=0.003 BTC, push=0 mSAT, delay=1440, pendingId=265578e855267e6a2e5f7fd08521f15c049d4edbb3eecb59d0f2457c8c64697f) from peer(037187c8e60dc05faa764736656ac6385672b187ea874f85ac0c460488901aa425)
lnd_1       | 2019-01-26 00:11:55.672 [ERR] FNDG: Unacceptable channel constraints: maxValueInFlight too large: 4000000000 mSAT, max is 300000000 mSAT
lnd_1       | 2019-01-26 00:11:55.672 [DBG] FNDG: Failing funding flow for pendingID=265578e855267e6a2e5f7fd08521f15c049d4edbb3eecb59d0f2457c8c64697f: maxValueInFlight too large: 4000000000 mSAT, max is 300000000 mSAT
lnd_1       | 2019-01-26 00:11:55.672 [INF] FNDG: Cancelling funding reservation for node_key=037187c8e60dc05faa764736656ac6385672b187ea874f85ac0c460488901aa425, chan_id=265578e855267e6a2e5f7fd08521f15c049d4edbb3eecb59d0f2457c8c64697f
lnd_1       | 2019-01-26 00:11:55.673 [ERR] FNDG: unable to cancel reservation: no active reservations for peer(037187c8e60dc05faa764736656ac6385672b187ea874f85ac0c460488901aa425)
lnd_1       | 2019-01-26 00:11:55.673 [DBG] FNDG: Sending funding error to peer (037187c8e60dc05faa764736656ac6385672b187ea874f85ac0c460488901aa425): (*lnwire.Error)(0xc010bffa40)({
lnd_1       |  ChanID: (lnwire.ChannelID) (len=32 cap=32) 265578e855267e6a2e5f7fd08521f15c049d4edbb3eecb59d0f2457c8c64697f,
lnd_1       |  Data: (lnwire.ErrorData) (len=66 cap=80) {
lnd_1       |   00000000  6d 61 78 56 61 6c 75 65  49 6e 46 6c 69 67 68 74  |maxValueInFlight|
lnd_1       |   00000010  20 74 6f 6f 20 6c 61 72  67 65 3a 20 34 30 30 30  | too large: 4000|
lnd_1       |   00000020  30 30 30 30 30 30 20 6d  53 41 54 2c 20 6d 61 78  |000000 mSAT, max|
lnd_1       |   00000030  20 69 73 20 33 30 30 30  30 30 30 30 30 20 6d 53  | is 300000000 mS|
lnd_1       |   00000040  41 54                                             |AT|
lnd_1       |  }
lnd_1       | })
lnd_1       |
lnd_1       | 2019-01-26 00:11:55.675 [DBG] PEER: Sending Error(chan_id=265578e855267e6a2e5f7fd08521f15c049d4edbb3eecb59d0f2457c8c64697f, err=maxValueInFlight too large: 4000000000 mSAT, max is 300000000 mSAT) to {{peerid}}
lnd_1       | 2019-01-26 00:11:55.753 [INF] PEER: unable to read message from {{peerid}}: EOF
lnd_1       | 2019-01-26 00:11:55.753 [INF] PEER: Disconnecting {{peerid}}, reason: read handler closed
lnd_1       | 2019-01-26 00:11:55.854 [DBG] SRVR: Peer {{peerid}} has been disconnected
```

**Comment by PWKad** [comment]
I just switched back to 5.1, let me get it building again first to make sure it's going to work and I'll try to switch back to master tomorrow to re-test.

**Comment by halseth** [comment]
This is probably BLW that attempts to open a channel with `max_value_in_flight` greater than the channel capacity, so the error message is correct.

**Comment by PWKad** [comment]
That's possible however I downgraded to 5.1 and the channel open went through fine.  So perhaps it is a new error that is being thrown that wasn't previously identifying a bug in BLW
