### ISSUE TITLE
Panic when exchanging gossip with c-lightning

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lnd#254]
While integration testing I noticed a fun `panic`:

```
panic: runtime error: index out of range

goroutine 229 [running]:
github.com/lightningnetwork/lnd/lnwire.newAlias(0xc4201d40c0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/lnwire/node_announcement.go:48 +0xdf
github.com/lightningnetwork/lnd/lnwire.readElement(0x1276820, 0xc4205259e0, 0xc27460, 0xc420125f30, 0x0, 0x0)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/lnwire/lnwire.go:565 +0xb93
github.com/lightningnetwork/lnd/lnwire.readElements(0x1276820, 0xc4205259e0, 0xc42072f9c0, 0x7, 0x7, 0x70, 0xcc8ea0)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/lnwire/lnwire.go:590 +0x65
github.com/lightningnetwork/lnd/lnwire.(*NodeAnnouncement).Decode(0xc420125f10, 0x1276820, 0xc4205259e0, 0x0, 0x0, 0x2)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/lnwire/node_announcement.go:125 +0x130
github.com/lightningnetwork/lnd/lnwire.ReadMessage(0x1276820, 0xc4205259e0, 0x0, 0x8e, 0x0, 0x0, 0x0)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/lnwire/message.go:256 +0xe4
main.(*peer).readNextMessage(0xc4202f4f20, 0x1281da0, 0xc420525980, 0xc4204ebee0, 0xc4202630e0)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/peer.go:391 +0x100
main.(*peer).readHandler(0xc4202f4f20)
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/peer.go:543 +0x105
created by main.(*peer).Start
        /home/cdecker/dev/lightning-integration/src/lnd/src/github.com/lightningnetwork/lnd/peer.go:271 +0x83f
```

It appears to crash `lnd` completely, instead of dropping the announcement and continuing. No idea yet what causes this, just wanted to give a heads up :wink:

**Comment by Roasbeef** [comment]
Thanks for the report! 

Dug into it a bit, and found the culprit: we never updated our `NodeAnnouncement` encoding/decoding order after we moved around the features (`a257554456cda98afd1532c302c0e5e84de0455e`). Will get this fixed very soon!

**Comment by Roasbeef** [comment]
This should be fixed in the latest version of master. Leaving open for now as to wait for verification before closing.

**Comment by cdecker** [comment]
No longer panics :+1:, though parsing fails and kills the connection. The following gossip messages are created by c-lightning and parse correctly in Eclair, but fail in lnd:

```01000e3a2a9376c229a1431e87d8afba0be2d151ffe46ec5aba846efd61159925dde47f277e7bf124807ef2dda4632912de3c9c6bd9f367be588b7be541e4e2ae82cce438995e84341bcc99674bec1540a857c20f1efbc218bf732e5e5cbfb4d1f0a547a2b1688cb111cfdfd5bebb95dbb6d97759e5924223bb61f95f56ced626a0fe600d1cff35e5b16a078e0973679139798652e5dc2ae64c3fbb925022c429b6e5d92bf3f2db75990e5ca4979232d228a6fbab9af9ac84f46f2cdb7425e139605db2db75804b7f0d7f35859a174a22abfd0fdb4baa603da0ed6c02a19a282db8d28e975b208f86081c17910f8a6ed9f4d893eaa6c95333dccd0e8349d732ff85900000008b60000040001021ef55b7ecbe25de36dbf30ccefaa57af66d527055b571a27ab182486ab46a87502f199e30895012b3d47ec578b526b8d22801682f5f52416b568bfb92f897b1cc003555e9121423a340cb4e272fa937d675463dd0efe252680bc315c4e5678223c110279bc983ebf50c6475275acdf8763e375a756ab21e84363dd86fec0a292b2d603```

**Comment by Roasbeef** [comment]
Closing as we located the issue: c-lightning wasn't populating the `chain_hash` field in the `ChannelAnnouncement` message.
