### ISSUE TITLE
Installation problems on Raspberry Pi

### ISSUE THREAD

**Issue by MoritzC** [lightningnetwork/lnd#255]
when running `sudo apt-get install golang-go` i only got
go1.3.3 linux/arm
which threw all kinds of errors during `go install`

to get the recommended version - Go 1.8 - get the archive [here](https://golang.org/dl/)

example with newest version
`wget https://storage.googleapis.com/golang/go1.8.3.linux-armv6l.tar.gz`
`tar -C /usr/local -xzf go1.8.3.linux-armv6l.tar.gz`

**Comment by Roasbeef** [comment]
I've recently updated the documentation to indicate that the min golang version if go 1.7. 

Closing.
