### ISSUE TITLE
lncli getinfo showing 4294967295 num_inactive_channels

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#2552]
### Background

Closing some channels, opening some. Force close 15+. Was doing maintenance! Then I ran getinfo and saw something weird.

### Your environment

* version of `lnd`: `0.5.1-beta commit=v0.5.1-beta-256-089d461552ffc05d7b1c22d603af0fa82e788e85`
* which operating system (`uname -a` on *Nix): `3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64`
* version of `btcd`, `bitcoind`, or other backend - `bitcoind 0.17.1`
* any other relevant environment details

### Steps to reproduce

Run lncli getinfo...

### Expected behaviour

0 inactive channels, as I closed all inactive (which was not what I wanted to do but happened any way). **In listchannels there were 0 inactive channels**.

### Actual behaviour
```{
       "version": "0.5.1-beta commit=v0.5.1-beta-256-g089d461552ffc05d7b1c22d603af0fa82e788e85",
       "identity_pubkey": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
       "alias": "MiltonPusser.lightningnode.eu",
       "num_pending_channels": 2,
       "num_active_channels": 109,
       "num_inactive_channels": 4294967295,
       "num_peers": 132,
       "block_height": 560488,
       "block_hash": "00000000000000000016bd943367e0941bf42605145c89ca031bb32e6ae10dae",
       "best_header_timestamp": 1548685935,
       "synced_to_chain": true,
       "testnet": false,
       "chains": [
               "bitcoin"
       ],
       "uris": [
               "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b@82.197.218.97:9735"
       ]
```

**Comment by karloluiten** [comment]
@Roasbeef : "just a display thing"

Less prio I guess.

**Comment by Roasbeef** [comment]
Looked into it and it's a cosmetic bug, should certainly be fixed though!

**Comment by AbelLykens** [comment]
I see a mismatch between datatypes in 
https://github.com/lightningnetwork/lnd/blob/8bde0e736f5044f456d8121c9462f235a9423d4c/lnrpc/rpc.proto#L1165

and 

https://github.com/lightningnetwork/lnd/blob/8bde0e736f5044f456d8121c9462f235a9423d4c/lnrpc/rpc.swagger.json#L1900

Not a clue if this is the problem exactly or how to fix though.

**Comment by yashbhutwala** [comment]
@AbelLykens it looks like that mismatch is the same for `num_active_channels` and `num_pending_channels`, so not sure if type is the issue.  I could potentially see an overflow issue with the implementation here: [lnd/rpcserver.go: Line 1813](https://github.com/lightningnetwork/lnd/blob/e2285732e47bacd74206f0bbf2c42c6ad8825548/rpcserver.go#L1813).  But I don't have much go programming experience to confirm.

**Comment by cfromknecht** [comment]
Fix for this would something along these lines:
```golang
channels, err := r.server.chanDB.FetchAllOpenChannels()
if err != nil {
        return nil, err
}

var numActiveChannels uint32
for _, channel := range channels {
        chanID := lnwire.NewChanIDFromOutPoint(&channel.FundingOutPoint)
        if r.server.htlcSwitch.HasActiveLink(chanID) {
                numActiveChannels++
        }
}

numInactiveChannels := uint32(len(channels)) - numActiveChannels
```
