### ISSUE TITLE
Hash of payment_preimage doesn't match payment_hash

### ISSUE THREAD

**Issue by tphyahoo** [lightningnetwork/lnd#2553]
### Background

Payment objects, returned by the listpayments command in lnd, are described at https://api.lightning.community/#payment

My understanding is that in all cases the payment_primate should be the sha256 preimage of the payment_hash value. However, this is not the case. 

### Your environment

* version of `lnd` -- 0.5.1-beta commit=basedon-v0.5.1-beta-dirty"
* which operating system (`uname -a` on *Nix) -- ubuntu
* version of `btcd`, `bitcoind`, or other backend -- Bitcoin Core RPC client version v0.17.0
* any other relevant environment details -- btcpayserver one quick deploy on lunanode as desacribed at https://medium.com/@BtcpayServer/launch-btcpay-server-via-web-interface-and-deploy-full-bitcoin-node-lnd-in-less-than-a-minute-dc8bc6f06a3

### Steps to reproduce

make a small payment from my node to my reddit lntipbot. This is routed through a couple intermediary nodes as shown below. 

    root@btcpay391320:~/btcpayserver-docker# cat bitcoin-lncli.sh 
    #!/bin/bash
    
    docker exec -ti btcpayserver_lnd_bitcoin lncli --macaroonpath /root/.lnd/admin.macaroon "$@"
    
    
    # ./bitcoin-lncli.sh listpayments
    {   
        "payments": [
            {   
                "payment_hash": "fb0153ce72e7a902318648f74408b8cf758cd0d42941b46ea93ff18c3f09acf3",
                "value": "5000",
                "creation_date": "1547572623",
                "path": [
                    "026b105ac13212c48714c6be9b11577a9ce10f10e1c88a45ce217e6331209faf8b",
                    "038df0bd2fad1bfe42d177f18ea5e33543e2b855ef369d06bd94b81d2c87187c82",
                    "03345d99a94e2fc8a69698f8bbec6bea5a4e8dbaf8b313085bb9710f6014765e45",
                    "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                    "0219c2f8818bd2124dcc41827b726fd486c13cdfb6edf4e1458194663fb07891c7"
                ],
                "fee": "2",
                "payment_preimage": "0925c03778c4282a53481bc1a9ecd35d268a3e87a7318c1c56ad3e8e1b22e894",
                "value_sat": "5000",
                "value_msat": "5000000"
            }
        ]
    }
    
    # echo -n '0925c03778c4282a53481bc1a9ecd35d268a3e87a7318c1c56ad3e8e1b22e894' | sha256sum
    801937ceaf5588e72732b234656594be4288c608cb9161212cc4e6b97577e236
    
    but should be fb0153ce72e7a902318648f74408b8cf758cd0d42941b46ea93ff18c3f09acf3

### Expected behaviour

The last two strings should match

### Actual behaviour

see above

**Comment by Roasbeef** [comment]
Your command looks like it's hashing the hex encoding of the pre image rather than the raw bytes, we directly hash the raw bytes: https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L4393
