### ISSUE TITLE
Bug in breach arbiter

### ISSUE THREAD

**Issue by BitfuryLightning** [lightningnetwork/lnd#256]
It seems like when the balance of one party in breached commitment is 0, breach arbiter is unable to create justice tx, because it assumes that there are always two outputs to parties.
Example test
https://github.com/BitfuryLightning/lnd/commit/b7f8e5bf9058c5f780894e44092fa455b76ae565

Should I:
1. Create are distinct test for it?
2. Fix it?

**Comment by cfromknecht** [comment]
@BitfuryLightning thanks for documenting this! I am currently working on improvements to the breach arbiter in these PR's #241 and #264. I have talked with @Roasbeef about a potential solution and will see that it is resolved in the latter update.
