### ISSUE TITLE
Can not open a channels with last ~100000 sats onchain balance.

### ISSUE THREAD

**Issue by peername** [lightningnetwork/lnd#2567]
### Background

We can not use the last remaining onchain funds to open a channel.

When new fresh fund are added, everything is working. But if walletbalance < 100000 the channel opening operation is working but the transaction is not broadcasted to the network.

I tried many times during last 2-3 months to lock these funds in a channel. Every time it is the same. I receive the transaction ID but this transaction is not broadcasted. But the funds are missing from the walletbalance command.

To recover the funds, I am using closechannel --force + restarting the LND daemon. Only after the restart the money are back in my onchain wallet. They just sits there. I can not use them.

How can I export the individual onchain outputs to investigate which of them is causing the problem?

### Your environment

version of `lnd`: v0.5.1-beta Static Release
operating system: Ubuntu 18.04
bitcoind: 0.17.1

**Comment by Roasbeef** [comment]
Channels that small may be rejected by remote peers, or if it's on testnet, then the fees may be too high for us to open a channel like that? Do you have any further details?

**Comment by peername** [comment]
Mainnet. I am leaving enough satoshis for fees. Tried many times with different peer.

I think the problem is in some "broken" TX output. Is is possible to rescan the blockchain (UTXO set)?

**Comment by wpaulino** [comment]
Looks like you've run into #2410. You can follow the discussion there to see what needs to be done. Do you still have the logs for the invalid transaction? If you do, do you also have logs for the transaction containing the output the funding transaction is trying to double spend?

**Comment by peername** [comment]
Now I have 404000 sats balance in my wallet:

`./lncli walletbalance
{
    "total_balance": "404028",
    "confirmed_balance": "404028",
    "unconfirmed_balance": "0"
}
`
Trying to open a channel with 400,000 sats:

`./lncli openchannel 03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda 400000 --sat_per_byte 1
{
	"funding_txid": "4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22"
}
`

The transaction is not broadcasted:

`./bitcoin-cli gettransaction 4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22
error code: -5
error message:
Invalid or non-wallet transaction id
`

These are the logs:

`2019-02-02 11:48:42.230 [INF] RPCS: Manual fee rate input of 250 sat/kw is too low, using 253 sat/kw instead
2019-02-02 11:48:42.230 [INF] FNDG: Initiating fundingRequest(localAmt=0.004 BTC, remoteAmt=0 mSAT, capacity=0.004 BTC, chainhash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, peer=03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda, dustLimit=0.00000573 BTC, min_confs=1)
2019-02-02 11:48:42.237 [INF] LNWL: Performing funding tx coin selection using 253 sat/kw as fee rate
2019-02-02 11:48:42.321 [INF] FNDG: Target commit tx sat/kw for pendingID(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee): 2676
2019-02-02 11:48:42.321 [INF] FNDG: Starting funding workflow with 88.4.193.210:9735 for pendingID(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee)
2019-02-02 11:48:42.519 [INF] FNDG: Recv'd fundingResponse for pendingID(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee)
2019-02-02 11:48:42.531 [INF] FNDG: pendingChan(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee): remote party proposes num_confs=3, csv_delay=144
2019-02-02 11:48:42.531 [INF] FNDG: Generated ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1) for pendingID(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee)
2019-02-02 11:48:42.677 [INF] FNDG: Broadcasting funding tx for ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1): (*wire.MsgTx)(0xc02ee01ec0)({
 Version: (int32) 1,
 TxIn: ([]*wire.TxIn) (len=7 cap=15) {
  (*wire.TxIn)(0xc00cb08b40)({
   PreviousOutPoint: (wire.OutPoint) 34039f317dc8e5c58fb743091767c8fe047fdadc75c32edf1646dc07f21fc823:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 ee 1a af  0b e8 a9 6a ca 15 d6 a8  |0E.!.......j....|
     00000010  d6 8e f2 30 01 ce c3 19  10 f0 26 f7 78 69 fa 95  |...0......&.xi..|
     00000020  ea 33 86 66 a3 02 20 0f  3f a1 fb 86 46 c2 38 a2  |.3.f.. .?...F.8.|
     00000030  5d 0c 81 67 b1 8a c9 95  7f b3 f2 3e 14 73 2e 14  |]..g.......>.s..|
     00000040  f6 8f 51 c6 dd df 33 01                           |..Q...3.|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  02 c7 48 38 ea 97 6a 55  d6 d0 d3 41 27 23 92 6a  |..H8..jU...A'#.j|
     00000010  2e 14 b1 90 7f dd 84 a5  e0 78 f4 5c d9 0e 08 65  |.........x.\...e|
     00000020  34                                                |4|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb08a20)({
   PreviousOutPoint: (wire.OutPoint) 4a77a56485ae593d3f2ac510512ed005dbf9922e77068e80076433d6b50cfcfa:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 8e 96 1e  ba 75 02 d9 3f 08 92 7b  |0E.!.....u..?..{|
     00000010  4c 16 7e ff 76 66 46 17  94 2a 6c da 73 3a c5 8d  |L.~.vfF..*l.s:..|
     00000020  c7 05 ed 65 67 02 20 6f  5a 98 55 1b d5 5e 63 76  |...eg. oZ.U..^cv|
     00000030  1b f2 32 18 4e a5 cc eb  cc c4 22 80 72 d9 a5 15  |..2.N.....".r...|
     00000040  f4 87 48 a6 7a 16 db 01                           |..H.z...|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  03 57 ce 8f 5a e9 e2 42  67 bd f7 33 d4 92 c3 6e  |.W..Z..Bg..3...n|
     00000010  38 63 a4 b0 df 77 9d f6  a8 61 02 d1 bd 39 b5 52  |8c...w...a...9.R|
     00000020  1c                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb087e0)({
   PreviousOutPoint: (wire.OutPoint) 4e754c34386e8df6b476e160e6dbcfae5351cbade3b224588ba6cf62f427dbe3:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 35 c0 ae 5c  74 32 b2 74 fd b4 79 a1  |0D. 5..\t2.t..y.|
     00000010  d7 67 7f 7a b3 60 0b ce  32 81 b1 58 8a 70 84 63  |.g.z.`..2..X.p.c|
     00000020  13 c8 15 e5 02 20 62 67  32 bc 8a 12 38 00 80 11  |..... bg2...8...|
     00000030  e7 09 99 17 7a 82 f2 b8  f2 d5 c3 be db 36 c8 aa  |....z........6..|
     00000040  10 6c a1 80 c4 78 01                              |.l...x.|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  03 31 c8 1c a8 c6 62 88  05 fd 0e bd 92 de 10 4a  |.1....b........J|
     00000010  72 6c 34 1a 71 af fe ca  23 a6 a7 19 27 6a fb 06  |rl4.q...#...'j..|
     00000020  45                                                |E|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb08780)({
   PreviousOutPoint: (wire.OutPoint) 87d4c7d474e17ab4862388cdb475c4240690ae248dd3a47d96bbe513b9c54205:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 59 2f 15 ca  0c 5a 35 c1 56 27 fa 12  |0D. Y/...Z5.V'..|
     00000010  cd f3 77 3b 24 40 cf 68  e3 bc 7f 58 ed 02 e4 f8  |..w;$@.h...X....|
     00000020  68 6c f4 a2 02 20 3b 07  ab fc 7a cf 33 37 af af  |hl... ;...z.37..|
     00000030  d5 4f 67 c4 66 b1 9c cc  cc 49 23 a2 ed 13 ba 96  |.Og.f....I#.....|
     00000040  4c 1d 94 0a f2 d4 01                              |L......|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  02 a0 df 2e 8a 9d fd 1a  2a 08 1d 2d fd fb 4c 46  |........*..-..LF|
     00000010  e9 e3 a3 07 83 ab ea b8  51 cf 7d fc ce 5e f9 6d  |........Q.}..^.m|
     00000020  8e                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb088a0)({
   PreviousOutPoint: (wire.OutPoint) 925c5e20ed1741659f33a80c3737a9ff0d0fd9018d9e369e5f1188c683a58133:1,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 eb 81 81  e8 c5 13 54 38 58 f2 0c  |0E.!.......T8X..|
     00000010  25 23 e0 1d d4 55 25 7d  29 43 94 1c 85 af 52 03  |%#...U%})C....R.|
     00000020  ba 5d 26 a8 8b 02 20 76  29 fb 71 a5 6d 4a 98 3e  |.]&... v).q.mJ.>|
     00000030  a0 08 62 52 e6 bf 36 0d  79 1b a0 75 0c 49 45 49  |..bR..6.y..u.IEI|
     00000040  5e 8d 57 de 05 3a 43 01                           |^.W..:C.|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  02 92 9b f0 fb 60 e7 17  f9 a0 4f a6 93 66 75 55  |.....`....O..fuU|
     00000010  05 23 f1 f2 79 50 ec 99  48 62 f7 ed da d1 b0 5b  |.#..yP..Hb.....[|
     00000020  88                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb08ba0)({
   PreviousOutPoint: (wire.OutPoint) 93c6c2ce92acc3687cbd3ad32ba995c3788132851cf1cd6f7e6a0053d0021840:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 f1 f1 c4  5b e2 a8 d8 f8 7f 7d dc  |0E.!....[.....}.|
     00000010  4c 8d b7 6c 1e 4c d8 6e  cb 8f bf c7 f5 da cb 44  |L..l.L.n.......D|
     00000020  a8 97 b2 af 09 02 20 5a  33 bf b9 30 39 19 2b 35  |...... Z3..09.+5|
     00000030  a7 5b ee b5 bd 19 2e 41  d5 21 3d 89 87 7e 7a ff  |.[.....A.!=..~z.|
     00000040  c8 6a a4 38 d2 ef c1 01                           |.j.8....|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  02 55 f6 44 73 ac 2d d7  e0 cc 7b 09 ca 76 0f 34  |.U.Ds.-...{..v.4|
     00000010  dc 9b d4 07 11 47 37 2d  ee f7 55 11 84 12 75 e9  |.....G7-..U...u.|
     00000020  8e                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  }),
  (*wire.TxIn)(0xc00cb08ae0)({
   PreviousOutPoint: (wire.OutPoint) 943b2071a2a67fc35952e21875d7422f42cdc9bf30aa30c2d7a2852404c9b49f:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 0a e1 e1 61  f9 20 61 71 d3 35 54 70  |0D. ...a. aq.5Tp|
     00000010  6a 2d 3b ac fe b1 a0 34  c8 76 db 22 f9 8e 3f c2  |j-;....4.v."..?.|
     00000020  85 5d 13 57 02 20 29 bf  88 4c 53 8d 4b a8 1a 1b  |.].W. )..LS.K...|
     00000030  ae 58 a1 15 5e 24 5d b8  c8 9c 1a bb d9 15 c0 09  |.X..^$].........|
     00000040  08 82 1a 30 c1 87 01                              |...0...|
    },
    ([]uint8) (len=33 cap=33) {
     00000000  03 50 4c 41 f6 35 17 3a  ea 23 a3 4e f0 5e 56 53  |.PLA.5.:.#.N.^VS|
     00000010  00 df 63 db 88 73 59 90  bf 7d fb 54 5b 16 44 3b  |..c..sY..}.T[.D;|
     00000020  1a                                                |.|
    }
   },
   Sequence: (uint32) 4294967295
  })
 },
 TxOut: ([]*wire.TxOut) (len=2 cap=15) {
  (*wire.TxOut)(0xc02607cd80)({
   Value: (int64) 3460,
   PkScript: ([]uint8) (len=22 cap=500) {
    00000000  00 14 7a b2 57 84 8a dd  33 53 d8 32 fc 71 cf cf  |..z.W...3S.2.q..|
    00000010  a9 a9 ca da 7b d4                                 |....{.|
   }
  }),
  (*wire.TxOut)(0xc000bba1c0)({
   Value: (int64) 400000,
   PkScript: ([]uint8) (len=34 cap=500) {
    00000000  00 20 26 b1 63 5c a5 07  d4 d4 7b 84 7f f9 0d 3c  |. &.c\....{....<|
    00000010  1b 21 ad f7 9b b3 c6 5d  20 84 55 48 df 6b cf 57  |.!.....] .UH.k.W|
    00000020  ff 67                                             |.g|
   }
  })
 },
 LockTime: (uint32) 0
})

2019-02-02 11:48:42.680 [INF] LNWL: Inserting unconfirmed transaction 4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22
2019-02-02 11:48:42.790 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1): Transaction rejected: output already spent
2019-02-02 11:48:42.790 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1)
2019-02-02 11:48:42.791 [INF] CNCT: ChannelArbitrator(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1): starting state=StateDefault
2019-02-02 11:48:42.791 [INF] NTFN: New block epoch subscription
2019-02-02 11:48:42.794 [INF] NTFN: New spend subscription: spend_id=89, outpoint=4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1, height_hint=561198
2019-02-02 11:48:42.910 [INF] FNDG: Finalizing pendingID(e17a9da3e0e66e3070106cbe4f57e0c7d06b84d7b946d9ef7cd9573695b4d9ee) over ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1), waiting for channel open on-chain
2019-02-02 11:48:42.910 [INF] NTFN: New confirmation subscription: txid=4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22, numconfs=3
2019-02-02 11:48:42.910 [INF] FNDG: Waiting for funding tx (4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22) to reach 3 confirmations
2019-02-02 11:48:42.911 [INF] CNCT: Close observer for ChannelPoint(4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1) active
2019-02-02 11:48:43.025 [ERR] NTFN: Rescan to determine the spend details of 4e54d9d3a9217d8ddb5cb3ac7c1ff29c3e0ae9d94549f6e9301367978b10fd22:1 failed: transaction not found within range`

**Comment by wpaulino** [comment]
The transaction is double spending an output for a transaction that already exists in the chain 34039f317dc8e5c58fb743091767c8fe047fdadc75c32edf1646dc07f21fc823. We've had bugs like this before where the wallet has duplicate entries for an output. Do you have any logs for this one as well?

**Comment by wpaulino** [comment]
See https://github.com/lightningnetwork/lnd/issues/2410#issuecomment-453577863 for more context on what you can do. Will close this for now, feel free to re-open if you run into the issue again.
