### ISSUE TITLE
macaroon path and ubuntu go path TOTAL frustration

### ISSUE THREAD

**Issue by mmvphil** [lightningnetwork/lnd#2576]
Running unbutu latest server..
running lnd.. trying to use path to /home instead of root for obvious disk space issues.
 
our lnd stopped working :(

reason being macaroon path which we use is in /home directory .. along with .. /home/lndata/chain/bitcoin/mainnet/admin.macaroon path setup in auth.js file..for grpc.
Everything was working fine for a while then ERRORS
 lnd conf file pointed to datadir of home ..
 **program KEPT ON looking into ./root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon** for it..
It used to work fine.. is it a GO path resetting on us? how could it SUDDENLY STOP WORKING and looking in the wrong path? ??  

SO FKN FRUSTRATING this go path issue not sticking on ubuntu latest. Or is it another issue?
Anyway our **work around was to copy the macaroon so it is in both paths..** 

Can anyone help us regarding **DEFINITIVE DOCUMENTATION ON HOW TO SET UP** 
A. go path to datadir of /home and why in the heck it keeps trying to look into root for macaroon ??
B. macaroon path to /home

See https://bitx.press/comments.php?p=81 our LN powered site.   cheers.

**Comment by wpaulino** [comment]
> A. go path to datadir of /home and why in the heck it keeps trying to look into root for macaroon ??

`lncli` will look for the macaroon in the current user's default lnd directory (this would be ~/.lnd on Linux).

> B. macaroon path to /home

If you need to specify a different path, use the `--macaroonpath` flag to specify the absolute path, or just `--lnddir` (in your case, `/home/lndata`) to point to the correct base directory..
