### ISSUE TITLE
Not enough witness outputs

### ISSUE THREAD

**Issue by mmvphil** [lightningnetwork/lnd#2577]
re lncli openchannel node_key=03da1c27ca77872ac5b3e568af30673e599a47a5e4497f85c7b5da42048807b3ed  --local_amt=450000 --push_amt=0 --connect=46.229.165.142:9735
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.0045 BTC only have 0.000639 BTC  available
bitcoin-cli getbalance
0.01041585

... All transactions have min 30 confirms at this point? Tried a reboot of lnd .. no joy :(

**Comment by wpaulino** [comment]
`lnd` can only use funds from its own wallet. You'll need to transfer them there and then open the channel.

**Comment by mmvphil** [comment]
HOLY SHIT i forgot to addfunds OMG wat a brain fart.. lol
