### ISSUE TITLE
Allow spending unconfirmed push_amount

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#2579]
LND should allow spending from unconfirmed `push_amount`, since in the worst case it won't confirm at all and so is "transferred" to the node opening the channel.

I've opened related issues at BOLT repo: https://github.com/lightningnetwork/lightning-rfc/issues/565
and BLW repo: https://github.com/btcontract/lnwallet/issues/125

The issue in BLW repo also describes real-world use case for this.

**Comment by halseth** [comment]
Not sure I get what you are saying. The `push_amt` is a channel balance, so it cannot be used before the channel is active, and that requires confirmation.

**Comment by Kixunil** [comment]
What you describe is the current state, however, it makes no sense to disable spending `push_amt` because if it gets confirmed later, everything works as if it was confirmed beforehand and if it doesn't get confirmed at all (gets double spent) the receiver of `push_amt` loses whole unspent `push_amt`.

The use case is to allow people to buy pre-funded channels from a reputable service (e.g. for fiat) and use the funds within Lightning Network immediately, without waiting for confirmation.

I suppose that the fact the balance is `push_amt` is forgotten by lnd after the channel is created, so it requires a change to remember it.

**Comment by Roasbeef** [comment]
Closing this as it's a spec level issue, not an implementation level issue. As the responder of the channel funding as is atm, we can't even be sure that we actually _have_ a push amount until the commitment is confirmed. Even then, the push amount may not actually put you above your channel reserve.

**Comment by Kixunil** [comment]
Is now a good time to re-open this, since it's implemented in other wallets?

**Comment by cfromknecht** [comment]
I don’t think there’s been any progress on the spec front?
