### ISSUE TITLE
Significantly less Nodes/Channels in graph after upgrade

### ISSUE THREAD

**Issue by Bluetegu** [lightningnetwork/lnd#2588]
### Background

getnetworkinfo showing significantly less channels and nodes, compared to release 0.51 version (mainnet):

    "num_nodes": 1912,
    "num_channels": 9284,

While 0.51 version (not mine) is reporting:

    "num_nodes": 2961,
    "num_channels": 23197,

This is after a few days in which the numbers are stable.

On slack moli suggested that this is related to DLP. My expectation is that DLP will have local implications (refusing connection to peer), but the global graph picture should be the same regardless of whether the node upgraded version or not. 

### Your environment

* version of `lnd`
"version": "0.5.1-beta commit=v0.4.1-beta-2533-gbcc9e303968552d5638feb005c2d6d35bb996a64"

* which operating system (`uname -a` on *Nix)
Linux ln.bluetegu.cc 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details

### Expected behaviour

The overall number of channels and nodes in the graph should be similar to the number of channels and nodes of a 0.51 version node that wasn't upgraded.

### Actual behaviour

New upgraded node has much lower numbers.

**Comment by Roasbeef** [comment]
This is just what you've heard from you peers. There's no global view of the network. You'll eventually hear about the rest of the graph.
