### ISSUE TITLE
The closed channels list should return the initiator of channels

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2594]
In PR #2473 an attribute was added to the channels list which represents the initiator of the channel. 

This is an important field for record keeping and to identify the party responsible for commitment transaction fees in the 1.0 protocol.

So consistent with the reasoning for #2473, a record of the initiating party should be persisted and be returned in the closed channel API

**Comment by carlaKC** [comment]
Resolved by #3961. 

All channels that were closed after we started storing open channels in historical channel bucket will have initiator displayed in rpc close summary. For older channels this value will be recorded as `UNKNOWN`, since we did not store it.
