### ISSUE TITLE
On-chain payments and addresses should have labels

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2597]
In the API, it would be useful to have labeling on on-chain transactions and addresses.

For invoices there is a memo field that can be used to keep track of the purpose of payments

For on-chain sends and receives there is no labeling to help describe transactions

- [x] Add payment labels

- [ ] Add address labels

**Comment by carlaKC** [comment]
Will be picking this up as part of reliable accounting.

**Comment by carlaKC** [comment]
I've started working on the transactions portion of this. Got me thinking whether we should take advantage of the ability to label transactions when lnd publishes transactions (so, the non user-initiated case). 

This would look like a set list of labels (`open channel`, `sweep`, `close channel`) which inform the user what 'type' of transaction this was. Right now, you can figure out what a transaction is by looking at the tx structure (higher skill level) or searching `ListChannels`/`ClosedChannels`/`ListSweeps` (endpoint WIP) for the transaction (higher effort). With these labels, all the lnd published transactions listed in `GetTransactions` will provide an indication of what they are, which makes it easy for users to then go look up additional information about the tx in the correct place. I think this is a big win, at the minimal cost of a few bytes in walletdb.

**Comment by saubyk** [comment]
There are transaction labels now in LND for channel opens and sweeps. Closing this issue. Can reopen if there are more labeling needs.
