### ISSUE TITLE
Use semaphores to limit goroutine concurrency within the daemon

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#26]
There a several areas within the daemon where a goroutine is launched to asynchronously complete a task. Currently the deployment of such goroutines is _unbounded_. Semaphores should be added to various areas in order to control the level of concurrency dedicated to these outstanding async requests. 

Grepping for "semaphore" wtihin the repo yeids: 

```
./fundingmanager.go:538:        // TODO(roasbeef): semaphore to limit active chan open goroutines
./rpcserver.go:461:         // TODO(roasbeef): semaphore to limit num outstanding
./server.go:327:    // TODO(roasbeef): semaphore to limit the number of goroutines for
./server.go:402:        // TODO(roasbeef): server semaphore to restrict num goroutines
```

In golang a simple semaphore can be created by creating a typedef around a `chan struct{}`. The new type would also provide `acquire` and `release` methods along with a constructor to initialize a semaphore taking a parameter which dictates the level of buffering in the underlying channel.

**Comment by afederigo** [comment]
Hello!
I would like to try to solve this issue

**Comment by afederigo** [comment]
I have stopped the work under Roasbeef's recommendation.
