### ISSUE TITLE
Autopilot miscalculates the total funds

### ISSUE THREAD

**Issue by mcduck76** [lightningnetwork/lnd#2608]
The autopilot agent calculates the total funds available by adding the on chain wallet funds to the total channel allocation.

However, the channel allocation is erroneously calculated by adding the channel capacities instead of the local balance:
https://github.com/lightningnetwork/lnd/blob/a0c0e8edc9a58e8833fd32119964207205f9c764/autopilot/agent_constraints.go#L103

As the threshold is checked against this value, it can lead to unexpected results, especially as remote funding grows larger (which should be excluded from the calculation of the total funds).

Apparently there was a provision for this amount to be calculated properly, but the corresponding field (FundedAmt) is not populated accordingly:
https://github.com/lightningnetwork/lnd/blob/e2285732e47bacd74206f0bbf2c42c6ad8825548/autopilot/graph.go#L103

**Comment by halseth** [comment]
Good catch :)

**Comment by yashbhutwala** [comment]
@halseth should `FundedAmt` field be added in other places as well?

**Comment by halseth** [comment]
Up for grabs.

**Comment by halseth** [comment]
Still up for graps.
