### ISSUE TITLE
Autopilot uses the wrong amount for open channel

### ISSUE THREAD

**Issue by mcduck76** [lightningnetwork/lnd#2609]
The autopilot agent receives the total amount available for automatic channel opening, as well as the number of channels to open by a call to ChannelBudget:
https://github.com/lightningnetwork/lnd/blob/6c78fc574098d05be36e1423c0edd182aa13656c/autopilot/agent.go#L490

It then proceeds to open each channel with this amount. It is never divided by the number of channels. This immediately causes the threshold set (allocation) for the autopilot to be exceeded.

Example:
8 BTC wallet funds.
1 BTC allocated to 3 channels.
option Threshold set to 0.3.
option MaxChannels set to 5.

The ChannelBudget call will return (8+1) * 0.3 - 1 =1.7 available for funding 2 channels, as the current allocation is 1/(8+1) (0.11, less than 0.3)

The agent then opens two new channels with 1.7 BTC funding each. This leads to the current allocation being 4.4/(4.6+4.4)=0.49, which is way more than the 0.3 requested threshold.

The correct behavior would be if the 1.7 available funds were equally divided to the channels to be opened, in this case 1.7/2=0.85.

If that was the case, the new threshold would be 2.7/(6.3 + 2.7)=0.3, which would be correct according to the option allocation set in the configuration.

Note: The amount per channel does not have to be just funds/numofchannels, it could be splitted according to the channel score to be opened (as an extra feature), as long as the total amount opened does not exceed the total funds available.

**Comment by halseth** [comment]
Are you saying you are seeing this overallocation with the current autopilot? 

The maximum network channel size is about 0.16 BTC, so it cannot open channels up to the size you mention.

The current implementation will open channels, one at the time of size maxchansize set in the config. Is this consistent with what you are seeing?

**Comment by mcduck76** [comment]
My example was with crude numbers for easier back-of-the-envelope calculations.

The maxchansize (undocumented in the sample-lnd.conf file) is indeed going to cap the limit to whatever value it is set. This however has nothing to do with the reported issue.

Real example (how I discovered the problem in the first place):

0.48 BTC wallet funds.
0.0022 BTC allocated to 3 channels.
option Threshold set to 0.3.
option MaxChannels set to 5.
maxchansize not set, default 0.16777216.

Calculated budget: (0.48+0.0022)*0.3-0.0022=0.14246
Autopilot opens two new channels of its choice, with 0.14246 amount each (less than the 0.16777216 maximum).
New allocation 0.28712/(0.19508+0.28712)=0.595, almost double the 0.3 requested.

This way if the MaxChannels setting was initially set to 6 instead of 5, the whole wallet would be allocated to the three extra channels (0.14246 * 3).

Correct behavior would be to divide the amount somehow among the channels to be opened.

**Comment by Roasbeef** [comment]
Which commit/version of lnd are you using?

**Comment by mcduck76** [comment]
v0.5.1-beta-656-g9cd88a04b728cce31683e61dab29882672ed710f

(latest as of the time of opening the issue)

**Comment by getuser1122342** [comment]
Is the autopilot/agent.go new? How do I had this to my Linux node?

I started my Bitcoin LND node Aug last year.

It was working OK until I restarted it two weeks ago now I can’t get LND to connect to other peers 

What is the command to update the LND version? I am running the Odroid HC2 mini-computer  

LND is running but I can’t connect to other peers. I keep getting is error after running the lncli connect command after 5 mins 

`Feb 07 22:17:36 thundroid lnd[26269]: 2019-02-07 22:17:36.197 [ERR] SRVR: unable to get channel links: unable to locate channel link by destination hop id 03
Feb 07 22:19:33 thundroid lnd[26269]: 2019-02-07 22:19:33.921 [ERR] RPCS: (connectpeer): error connecting to peer: dial tcp 78.46.77.22:9735: connect: connec
Feb 07 22:19:40 thundroid lnd[26269]: 2019-02-07 22:19:40.541 [INF] SRVR: Established connection to: 167.99.212.230:9735
Feb 07 22:21:40 thundroid lnd[26269]: 2019-02-07 22:21:40.562 [ERR] SRVR: unable to get channel links: unable to locate channel link by destination hop id 03
Feb 07 23:57:07 thundroid lnd[26269]: 2019-02-07 23:57:07.939 [INF] LNWL: Rescan finished at 562054 (000000000000000000023b426814d5b37d00ea11dab0a7df222778f2
Feb 07 23:57:07 thundroid lnd[26269]: 2019-02-07 23:57:07.945 [INF] LNWL: Starting rescan from block 0000000000000000002b432a0a922f0632b1a6a3c9cfa9468e1c1e25
Feb 08 01:21:34 thundroid lnd[26269]: 2019-02-08 01:21:34.136 [INF] LNWL: Rescan finished at 562066 (000000000000000000147dc5df41f4d22b5006b2b8c89f435893bf2b
Feb 08 01:21:34 thundroid lnd[26269]: 2019-02-08 01:21:34.143 [INF] LNWL: Starting rescan from block 0000000000000000001815ca64b581c7b665e374722d0c7ac4c88317
Feb 08 02:01:36 thundroid lnd[26269]: 2019-02-08 02:01:36.626 [INF] LNWL: Rescan finished at 562072 (00000000000000000027b74f720d234845408c064a348220a0b58c24
Feb 08 04:53:05 thundroid lnd[26269]: 2019-02-08 04:53:05.871 [ERR] SRVR: unable to get channel links: unable to locate channel link by destination hop id 03`

**Comment by wpaulino** [comment]
@getuser1122342 your issue is unrelated to the original issue here. It looks like you're running an outdated version, so I would suggest upgrading to the [latest release](https://github.com/lightningnetwork/lnd/releases/tag/v0.5.2-beta).

**Comment by getuser1122342** [comment]
> @getuser1122342 your issue is unrelated to the original issue here. It looks like you're running an outdated version, so I would suggest upgrading to the [latest release](https://github.com/lightningnetwork/lnd/releases/tag/v0.5.2-beta).

@wpaulino 
Thanks 
What is the command to update the LND version? I am running the Odroid HC2 mini-computer

**Comment by getuser1122342** [comment]
@halseth 
Can someone explain to me how to install gpg or gpg2 via the command line only because the Linux version I am running is cli only because this is required now to update LND version.

Also what is the command line to update my LND version?

I am running the Odroid HC2 mini-computer and have cli only.

**Comment by halseth** [comment]
@getuser1122342 You don't need gpg to install lnd. Just download the release for you target platform and unzip the binary.

**Comment by getuser1122342** [comment]
@halseth 
Thanks, I am running the Odroid HC2 mini-computer and have cli only Ubuntu 16.04.03 LTE.

What is the command to update LND to the lasted version?

**Comment by wpaulino** [comment]
@getuser1122342 I'd suggest joining our Slack or IRC if you need help.

**Comment by getuser1122342** [comment]
@wpaulino 

Is there no simple command to update the LND version?

**Comment by halseth** [comment]
There's a link in the readme. There you also find install instructions

**Comment by getuser1122342** [comment]
@halseth  Thanks
