### ISSUE TITLE
Neutrino Error

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#261]
https://pastebin.com/PZ065arN

Restarting it made it fetch everything fine after.

commit 48712526d61c1512dff26211082a97b0605f270e

**Comment by Roasbeef** [comment]
This commit https://github.com/lightninglabs/neutrino/pull/16/commits/0e4155a66399dcba3b4886425c41f986da68dd8b which recently landed in `neutrino` fixed this issue. 

Closing.
