### ISSUE TITLE
unable to install V0.5.2 -mod=vendor only valid when using modules

### ISSUE THREAD

**Issue by bruceleeroy18** [lightningnetwork/lnd#2612]
### Background

Attempting to install latest version. Get an error with the flag -mod=vendor. (When used without the -mod=vendor I get another result)

### Your environment
linux-amd64.
go1.11.5 

Both vendor and lnd are unzipped, and in the current directory. 
### Steps to reproduce

go build -v -mod=vendor -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.2-beta-rc3"
build flag -mod=vendor only valid when using modules

go build -v -mod=vendor -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.2-beta"
build flag -mod=vendor only valid when using modules

go build -v -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.2-beta-rc3"
can't load package: package .: no Go files in /home/

Do I have go installed incorrectly? I just go from source and was able to install lnd-v0.5.1 from lnd/master install.

**Comment by wpaulino** [comment]
You'll need to to prepend the build command with `GO111MODULE=on`. The release notes have been updated to reflect this.

**Comment by bruceleeroy18** [comment]
Thanks!Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Wilmer Paulino <notifications@github.com> Date: 2/7/19  15:11  (GMT-05:00) To: lightningnetwork/lnd <lnd@noreply.github.com> Cc: bruceleeroy18 <browningsmith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [lightningnetwork/lnd] unable to install V0.5.2 -mod=vendor only valid when using modules (#2612) You'll need to to prepend the build command with GO111MODULE=on. The release notes have been updated to reflect this.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lightningnetwork/lnd","title":"lightningnetwork/lnd","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lightningnetwork/lnd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wpaulino in #2612: You'll need to to prepend the build command with `GO111MODULE=on`. The release notes have been updated to reflect this."}],"action":{"name":"View Issue","url":"https://github.com/lightningnetwork/lnd/issues/2612#issuecomment-461578312"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lightningnetwork/lnd/issues/2612#issuecomment-461578312",
"url": "https://github.com/lightningnetwork/lnd/issues/2612#issuecomment-461578312",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bruceleeroy18** [comment]
Now I am getting this error. 

$ GO111MODULE=on go build -v -mod=vendor -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.2-beta"
go: cannot find main module; see 'go help modules'

**Comment by wpaulino** [comment]
Make sure that the you are within the lnd source directory before running this command.

**Comment by bruceleeroy18** [comment]
Thanks. That did the trick to initiate build.

Once it builds it, it says lnd command not found. Any more suggestions?

**Comment by wpaulino** [comment]
Run the same command but replace `build` with `install`.

**Comment by bruceleeroy18** [comment]
Oh, I see. Thanks for helping me learn this details of the process.

**Comment by wpaulino** [comment]
No worries, thanks for pointing out these issues. I've updated the release notes to account for this.

**Comment by bruceleeroy18** [comment]
Now my command line says LND is installed and wants lncli to open it, but it says lncli is not installed. let me try a reboot and get back to you.

**Comment by wpaulino** [comment]
Ah, you'll need to install `lncli` as well with: `GO111MODULE=on go install -v -mod=vendor -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.2-beta" ./cmd/lncli`

**Comment by bruceleeroy18** [comment]
will do! thanks again.

**Comment by bruceleeroy18** [comment]
Got it all update thanks to you! Can I send you a couple millibitcoin via lightning?

**Comment by wpaulino** [comment]
I'd suggest joining our [Slack](https://join.slack.com/t/lightningcommunity/shared_invite/enQtMzQ0OTQyNjE5NjU1LWRiMGNmOTZiNzU0MTVmYzc1ZGFkZTUyNzUwOGJjMjYwNWRkNWQzZWE3MTkwZjdjZGE5ZGNiNGVkMzI2MDU4ZTE) or #lnd on IRC and asking there :)
