### ISSUE TITLE
How to be sure that my node is protected when its offline

### ISSUE THREAD

**Issue by kasadawa** [lightningnetwork/lnd#2613]
As far as I read, there is no way backup the node.
So if something happens with the server the node will be offline . 

If your node is offline for a long time , and there were some opened channels, can the other party steal  all of the funds in the channels by giving old state/signature  ? (because the connection is p2p , who is responsible for watching for this kind of fraud. )

**Comment by wpaulino** [comment]
> As far as I read, there is no way backup the node.
So if something happens with the server the node will be offline .

Static channel backups are currently in progress and will be able to help you recover funds in the event that your node loses critical state for channel operation. See https://github.com/lightningnetwork/lnd/pull/2313 for details.

> If your node is offline for a long time , and there were some opened channels, can the other party steal all of the funds in the channels by giving old state/signature ?

Yes, this will be solved by watchtowers. I suggest you do some research on them. Our implementation is also currently WIP and will hopefully make it into the next release.
