### ISSUE TITLE
lncli rpc error: tls handshake failed

### ISSUE THREAD

**Issue by aggieben** [lightningnetwork/lnd#2614]
### Background

lncli fails to connect to lnd out of the box

### Your environment

* version of `lnd`: 0.5.2-beta
* which operating system (`uname -a` on *Nix) Windows 10 1809, build 17763.253
* version of `btcd`, `bitcoind`, or other backend bitcoind, v0.17.1
* any other relevant environment details

### Steps to reproduce

Downloaded 0.5.2-beta binaries as zip.  Extracted lnd.exe and lncli.exe to local folder.  Ran lnd.exe with options to connect it to bitcoind, which appears to succeed.  Then, tried running `lncli getinfo`, but it fails with 
```
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"
```

Tried again, specifying `lnddir` as suggested in #883.  Still met with same error.

### Expected behaviour

lncli connects to lnd and prints results of `getinfo`.

### Actual behaviour

Error message as shown above.

I have also tried connecting Zap to this node and experienced the same error.

**Comment by Roasbeef** [comment]
Is it a local or remote node? Make sure that if you're using a distinct `lndir`, then you also update `lncli` to point to the new cert. There appears to be a configuration issue on your end.

**Comment by aggieben** [comment]
@Roasbeef the node is local (both lnd and bitcoind), and the lndir is just the default (`%LOCALAPPDATA%\Lnd`)

**Comment by Roasbeef** [comment]
What command are you trying to do? If you remove the existing tls.cert and tls.key, do things start working again?

**Comment by aggieben** [comment]
I was trying to just do anything.  `getinfo` seemed like a safe one to try.  

Moving the TLS cert and key and restarting Lnd seemed to get me past this particular problem.  Now I'm able to do
`lncli --macaroonpath <path> create`
Which allowed me to set a password, and it generate a cipher seed.  Maybe I'm good to go?  I'll look more tomorrow.

**Comment by aggieben** [comment]
Looks like now the error is: `verification failed: signature mismatch after caveat verification`

**Comment by Roasbeef** [comment]
That means you have the wrong macaroon.

**Comment by sergioabril** [comment]
I got the same error on startup, when I fired up lnd after upgrading, but it worked just fine after a while. 

````
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"
```

**Comment by wpaulino** [comment]
@aggieben macaroons are not needed when using the `create/unlock/changepassword` commands. The `--macaroonpath` flag for `lncli` is to use the macaroon found at that path, not create it at that path. If you'd like to provide a different path for `lnd` to create its macaroons, then you should use the `--adminmacaroonpath/--readonlymacaroonpath/--invoicemacaroonpath` flags for `lnd`.

**Comment by Roasbeef** [comment]
> I got something similar on startup, when I fired up lnd after upgrading, but it worked just fine after a while.

Upgrading from master (today) to 0.5.2 is actually a downgrade (just pointing this out), since master has some things that 0.5.2 doesn't. Closing this out now as it's just a config issue.

**Comment by aggieben** [comment]
Thanks for your help, @Roasbeef
