### ISSUE TITLE
either bitcoin.active or litecoin.active must be set to 1 (true) ?? [no litecoin at all]

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#2616]
### Background
```
admin@raspberrypi:~ $ cat /home/bitcoin/.lnd/lnd.conf
# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=info
maxpendingchannels=5
alias=XXXX
color=#68F442
rpclisten=0.0.0.0:10009
tlsextraip=192.168.1.0/24


[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

bitcoin.node=bitcoind

[autopilot]
autopilot.active=1
autopilot.maxchannels=10
autopilot.allocation=0.9


admin@raspberrypi:~ $ lnd
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)
```
### Your environment

rasbpy

**Comment by Roasbeef** [comment]
Something in your config is wrong. Progressively remove (or comment) out items until it parses.

**Comment by wpaulino** [comment]
The issue is most likely to do with your alias including [].

**Comment by MrManPew** [comment]
I do not understand, you can see the config. What's wrong with it?

**Comment by MrManPew** [comment]
```
admin@raspberrypi:~ $ cat /home/bitcoin/.lnd/lnd.conf
# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
#debuglevel=info
#maxpendingchannels=5
#alias=Mr_Man[LND]
#color=#68F442
#rpclisten=0.0.0.0:10009
#tlsextraip=192.168.1.0/24


[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

bitcoin.node=bitcoind

[autopilot]
#autopilot.active=1
#autopilot.maxchannels=10
#autopilot.allocation=0.9
admin@raspberrypi:~ $ lnd
loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)
```
I've commented everything and I still get it...

**Comment by MrManPew** [comment]
@wpaulino @Roasbeef  and whoever read this ticket. The problem was that the lnd.conf was not in the right folder.. I followed the instructions here: https://github.com/Stadicus/guides/tree/master/raspibolt and something with the users configuration is wrong

**Comment by Jeans5** [comment]
In which folder should it be?

**Comment by eyal352** [comment]
I believe the issue was with lnd looking in the wrong directory for the lnd.conf file, and once i configured that, it could not locate the bitcoin.conf file. I was able to make it work by explicitly passing the location of both files:
`lnd --lnddir=/home/eyal/.lnd --bitcoind.dir=/home/eyal/.bitcoin`

**Comment by pfergi42** [comment]
I was able to comment out the [Bitcoin] header line in the lnd.conf and was able to get this error to go away.  Ref issue #97 from Lit repo (https://github.com/lightninglabs/lightning-terminal/issues/97)
