### ISSUE TITLE
chan size of 0.00115 BTC is below min chan size of 0.003 BTC

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#2617]
### Background
```
admin@raspberrypi:~ $ lncli openchannel --sat_per_byte=2  03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e 115000
[lncli] rpc error: code = Code(199) desc = chan size of 0.00115 BTC is below min chan size of 0.003 BTC
```

Is that a response from lnd, or a response from the server? If it is a reponse from the server it is a bit better if it will say the server state that:... (I have channels that are smaller)

### Your environment

* version of `lnd`
Can't run lnd, see https://github.com/lightningnetwork/lnd/issues/2616
* which operating system (`uname -a` on *Nix)
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.1
* any other relevant environment details

**Comment by Roasbeef** [comment]
Response from the node you're trying to connect to.

**Comment by Roasbeef** [comment]
It is a response from the node you're trying to open the channel with. It references the size of the channel you attempted to create.

**Comment by MrManPew** [comment]
@Roasbeef 
Thank you for the response. I understand that this is the response from the server. 
**I am suggesting** to change lncli error message.

Currently the error message is:
```
[lncli] rpc error: code = Code(199) desc = chan size of 0.00115 BTC is below min chan size of 0.003 BTC
```

I suggest to change it to something like:
```
Can not connect, the node that you are trying to connect replied the following message: "chan size of 0.00115 BTC is below min chan size of 0.003 BTC" ([lncli] rpc error: code = Code(199))
```

I think that would make it more clear, what do you think?

**Comment by MrManPew** [comment]
```[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.002 BTC only have 0.00058359 BTC  available```
This is what I get when I do not have enough BTC...
