### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by maxbry** [lightningnetwork/lnd#2627]
### Background

    $ make
     Building debug lnd and lncli.
    GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-686-gc44d4046c15f4d51301a9cf94a4b98cc906ac84c" github.com/lightningnetwork/lnd
    runtime
    # runtime
    /usr/local/go/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
    /usr/local/go/src/runtime/map.go:65:2: bucketCnt redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
    /usr/local/go/src/runtime/map.go:69:2: loadFactorNum redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:69:18
    /usr/local/go/src/runtime/map.go:70:2: loadFactorDen redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:70:18
    /usr/local/go/src/runtime/map.go:76:2: maxKeySize redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:76:17
    /usr/local/go/src/runtime/map.go:77:2: maxValueSize redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:77:17
    /usr/local/go/src/runtime/map.go:82:2: dataOffset redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:85:4
    /usr/local/go/src/runtime/map.go:91:2: empty redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
    /usr/local/go/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
    /usr/local/go/src/runtime/map.go:93:2: evacuatedX redeclared in this block
            previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
    /usr/local/go/src/runtime/map.go:93:2: too many errors
    Makefile:92: recipe for target 'build' failed
    make: *** [build] Error 2

### Your environment

    /lnd$ git rev-parse HEAD
    c44d4046c15f4d51301a9cf94a4b98cc906ac84c
    $ uname -a
    Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
    /bitcoin$ git rev-parse HEAD
    392d1382c1b1459aaea86250cecaa54b84508f2d

**Comment by wpaulino** [comment]
It seems like your go install is borked. I'd suggest fixing that as this is not an issue with `lnd`. Maybe check out https://github.com/golang/go/issues/27269.
