### ISSUE TITLE
2 questions/ No active channels on autopilot and random transaction too half my balance.

### ISSUE THREAD

**Issue by CryptoAstroNut** [lightningnetwork/lnd#2628]
### Background

I just got my node up and running on mainnet and put in a small amount of bitcoin to play around with. I have yet to have a channel open up.(it's on autopilot) I had one channel in pending for awhile but that was it. Also I noticed that half my balance disappeared so I checked the transactions and there are two. My orignal deposit and then one withdraw..... Can someon explain this to me please? I tried sending 150sats on Yall's but that came up as "unable to find path or destination. Below is a pic of the transaction. Top is my deposit and bottom is the withdraw. Sorry if this is a noob questions but I am one.
![transaction](https://user-images.githubusercontent.com/44443315/52539546-1b3c5980-2d34-11e9-855f-4bf6ec4933a9.png)

### Your environment

* version of `lnd`: 0.5
* which operating system: Rasbian stretch

**Comment by molxyz** [comment]
@CryptoAstroNut  Try `lncli listchannels`, the fund must be in a channel.  If the channel doesn't show up there, it must be in pending so try  `lncli pendingchannels` to find out.

Also version 0.5 is quite old, you should update and get v0.5.2.

**Comment by CryptoAstroNut** [comment]
It does look like it's in a channel thank you. its show it as "Active:false" Do i just close this channel?
 I'll go ahead and update this version also thank you.

**Comment by molxyz** [comment]
@CryptoAstroNut  I wouldn't close the channel yet. After doing the update, restart your LND node and try `lncli listchannels` again, the channel might show `active`, if not, it just means your counterparty is offline at the moment.

**Comment by CryptoAstroNut** [comment]
Ok, thank you for answering this for me I appreciate it.

**Comment by wpaulino** [comment]
Closing as there doesn't seem to be an issue here. I'd suggest checking out our Slack or IRC channel for questions like these instead.
