### ISSUE TITLE
state go version dependency

### ISSUE THREAD

**Issue by dooglus** [lightningnetwork/lnd#263]
I tried following the installation instructions in docs/INSTALL.md and failed.

is it worth mentioning the minimum supported version of go? I used the apt-get command from the instructions and ended up with version 1.3.3 on debian stable, which failed when I tried to install glide.

I don't really understand why it installed v1.3.3 when v1.7.5 is available in backports, but that's what happened.

Here's a log:

    $ sudo apt-get install golang-go
    [sudo] password for chris: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libgconf2-4 libgnome2-0
    Use 'apt-get autoremove' to remove them.
    The following extra packages will be installed:
      golang-go-linux-amd64 golang-go.tools golang-src
    The following NEW packages will be installed:
      golang-go golang-go-linux-amd64 golang-go.tools golang-src
    0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
    Need to get 31.0 MB of archives.
    After this operation, 227 MB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://debian.osuosl.org/debian/ jessie/main golang-src amd64 2:1.3.3-1 [5,149 kB]
    Get:2 http://debian.osuosl.org/debian/ jessie/main golang-go-linux-amd64 amd64 2:1.3.3-1 [7,918 kB]
    Get:3 http://debian.osuosl.org/debian/ jessie/main golang-go amd64 2:1.3.3-1 [9,030 kB]
    Get:4 http://debian.osuosl.org/debian/ jessie/main golang-go.tools amd64 0.0~hg20140703-4 [8,864 kB]
    Fetched 31.0 MB in 14s (2,133 kB/s)
    debconf: unable to initialize frontend: Dialog
    debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
    debconf: falling back to frontend: Readline
    Selecting previously unselected package golang-src.
    (Reading database ... 196403 files and directories currently installed.)
    Preparing to unpack .../golang-src_2%3a1.3.3-1_amd64.deb ...
    Unpacking golang-src (2:1.3.3-1) ...
    Selecting previously unselected package golang-go-linux-amd64.
    Preparing to unpack .../golang-go-linux-amd64_2%3a1.3.3-1_amd64.deb ...
    Unpacking golang-go-linux-amd64 (2:1.3.3-1) ...
    Selecting previously unselected package golang-go.
    Preparing to unpack .../golang-go_2%3a1.3.3-1_amd64.deb ...
    Unpacking golang-go (2:1.3.3-1) ...
    Selecting previously unselected package golang-go.tools.
    Preparing to unpack .../golang-go.tools_0.0~hg20140703-4_amd64.deb ...
    Unpacking golang-go.tools (0.0~hg20140703-4) ...
    Processing triggers for man-db (2.7.0.2-5) ...
    Setting up golang-src (2:1.3.3-1) ...
    Setting up golang-go-linux-amd64 (2:1.3.3-1) ...
    Setting up golang-go (2:1.3.3-1) ...
    debconf: unable to initialize frontend: Dialog
    debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
    debconf: falling back to frontend: Readline
    Setting up golang-go.tools (0.0~hg20140703-4) ...

    $ go version
    go version go1.3.3 linux/amd64

    $ apt-cache policy golang-go
    golang-go:
      Installed: (none)
      Candidate: 2:1.3.3-1
      Version table:
         2:1.7~5~bpo8+1 0
            100 http://debian.osuosl.org/debian/ jessie-backports/main amd64 Packages
         2:1.3.3-1 0
            500 http://debian.osuosl.org/debian/ jessie/main amd64 Packages
            100 /var/lib/dpkg/status

    $ go get -u github.com/Masterminds/glide
    package github.com/Masterminds/glide
    	imports bufio: unrecognized import path "bufio"
    package github.com/Masterminds/glide
    	imports bytes: unrecognized import path "bytes"
    package github.com/Masterminds/glide
    	imports container/list: unrecognized import path "container/list"
    package github.com/Masterminds/glide
    	imports crypto/sha256: unrecognized import path "crypto/sha256"
    package github.com/Masterminds/glide
    	imports encoding/json: unrecognized import path "encoding/json"
    package github.com/Masterminds/glide
    	imports encoding/xml: unrecognized import path "encoding/xml"
    package github.com/Masterminds/glide
    	imports errors: unrecognized import path "errors"
    package github.com/Masterminds/glide
    	imports fmt: unrecognized import path "fmt"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports io: unrecognized import path "io"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports io/ioutil: unrecognized import path "io/ioutil"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports log: unrecognized import path "log"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports net/http: unrecognized import path "net/http"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports net/url: unrecognized import path "net/url"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports os: unrecognized import path "os"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports os/exec: unrecognized import path "os/exec"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports path/filepath: unrecognized import path "path/filepath"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports regexp: unrecognized import path "regexp"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports runtime: unrecognized import path "runtime"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports strings: unrecognized import path "strings"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports time: unrecognized import path "time"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports sync: unrecognized import path "sync"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports go/ast: unrecognized import path "go/ast"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports go/parser: unrecognized import path "go/parser"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports go/printer: unrecognized import path "go/printer"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports go/token: unrecognized import path "go/token"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports strconv: unrecognized import path "strconv"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports os/signal: unrecognized import path "os/signal"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports encoding: unrecognized import path "encoding"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports encoding/base64: unrecognized import path "encoding/base64"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports math: unrecognized import path "math"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports reflect: unrecognized import path "reflect"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports sort: unrecognized import path "sort"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports unicode: unrecognized import path "unicode"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports unicode/utf8: unrecognized import path "unicode/utf8"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports go/build: unrecognized import path "go/build"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports text/scanner: unrecognized import path "text/scanner"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports github.com/Masterminds/glide/gb
    	imports github.com/Masterminds/glide/godep
    	imports github.com/Masterminds/glide/gom
    	imports github.com/Masterminds/glide/gpm
    	imports github.com/Masterminds/glide/importer
    	imports github.com/Masterminds/glide/repo
    	imports github.com/codegangsta/cli
    	imports flag: unrecognized import path "flag"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports github.com/Masterminds/glide/gb
    	imports github.com/Masterminds/glide/godep
    	imports github.com/Masterminds/glide/gom
    	imports github.com/Masterminds/glide/gpm
    	imports github.com/Masterminds/glide/importer
    	imports github.com/Masterminds/glide/repo
    	imports github.com/codegangsta/cli
    	imports syscall: unrecognized import path "syscall"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports github.com/Masterminds/glide/gb
    	imports github.com/Masterminds/glide/godep
    	imports github.com/Masterminds/glide/gom
    	imports github.com/Masterminds/glide/gpm
    	imports github.com/Masterminds/glide/importer
    	imports github.com/Masterminds/glide/repo
    	imports github.com/codegangsta/cli
    	imports text/tabwriter: unrecognized import path "text/tabwriter"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports github.com/Masterminds/glide/gb
    	imports github.com/Masterminds/glide/godep
    	imports github.com/Masterminds/glide/gom
    	imports github.com/Masterminds/glide/gpm
    	imports github.com/Masterminds/glide/importer
    	imports github.com/Masterminds/glide/repo
    	imports github.com/codegangsta/cli
    	imports text/template: unrecognized import path "text/template"
    package github.com/Masterminds/glide
    	imports github.com/Masterminds/glide/action
    	imports github.com/Masterminds/glide/cache
    	imports github.com/Masterminds/glide/godep/strip
    	imports github.com/Masterminds/glide/msg
    	imports github.com/Masterminds/vcs
    	imports github.com/Masterminds/glide/path
    	imports github.com/mitchellh/go-homedir
    	imports github.com/Masterminds/semver
    	imports github.com/Masterminds/glide/cfg
    	imports github.com/Masterminds/glide/mirrors
    	imports gopkg.in/yaml.v2
    	imports github.com/Masterminds/glide/util
    	imports github.com/Masterminds/glide/dependency
    	imports github.com/Masterminds/glide/gb
    	imports github.com/Masterminds/glide/godep
    	imports github.com/Masterminds/glide/gom
    	imports github.com/Masterminds/glide/gpm
    	imports github.com/Masterminds/glide/importer
    	imports github.com/Masterminds/glide/repo
    	imports github.com/codegangsta/cli
    	imports github.com/Masterminds/glide/tree
    	imports path: unrecognized import path "path"
    $

**Comment by Roasbeef** [comment]
Hi @dooglus, thanks for pointing this out! A prior version of our documentation specified the minimum golang version, but looks like it was lost in a recent re-org. I'll be pushing a commit shortly that updates the installation notes and also specifies the min golang version.
