### ISSUE TITLE
[Enquiry] how lnd handles missing blocks for pruned mode

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2638]
In the documentation:

> NOTE: WE DO NOT FULLY SUPPORT PRUNED OPERATING MODES FOR FULL NODES. It's possible to run a node in a pruned mode and have it serve lnd, however one must take care to ensure that lnd has all blocks on disk since the birth of the wallet, and the age of the earliest channels (which were created around March 2018).

If evil gossiper claims that a channel was opened at blockheight 100000 and the related block is pruned. Will lnd ignore the message? Will there be any negative impact? e.g. Denial of service or DB corruption

**Comment by wpaulino** [comment]
Any channels that are advertised to you with a block height that has been pruned will not be added to the graph since it's not possible for us to verify the channel's existence. This effectively limits your path finding options if you prune too aggressively.
