### ISSUE TITLE
Make && Make Install Throwing Error

### ISSUE THREAD

**Issue by futjrn** [lightningnetwork/lnd#2641]
Following the instructions to build on linux 18.04 
 
futjrn@blocksat:~/gocode/src/github.com/lightningnetwork/lnd$ make clean && make && make install
 Cleaning source.
rm -f ./lnd-debug ./lncli-debug
rm -f ./lnd-itest ./lncli-itest
rm -f -r ./vendor .vendor-new
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-708-g4fce641d6ac9da4b82d08f0c54540066c9f6e41e" github.com/lightningnetwork/lnd
GO111MODULE=on go build -v -tags="dev" -o lncli-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-708-g4fce641d6ac9da4b82d08f0c54540066c9f6e41e" github.com/lightningnetwork/lnd/cmd/lncli
cmd/lncli/autopilotrpc_default.go:5:8: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go-1.10/src/github.com/urfave/cli (from $GOROOT)
	/home/futjrn/gocode/src/github.com/urfave/cli (from $GOPATH)
Makefile:92: recipe for target 'build' failed
make: *** [build] Error 1

----------------------------------------------------------------------------------------------------
So i tried a make check : 
futjrn@blocksat:~/gocode/src/github.com/lightningnetwork/lnd$ make check
 Installing btcd.
GO111MODULE=on go get -v github.com/btcsuite/btcd/@v0.0.0-20190115013929-ed77733ec07d
package github.com/btcsuite/btcd/@v0.0.0-20190115013929-ed77733ec07d: invalid github.com/ import path "github.com/btcsuite/btcd/@v0.0.0-20190115013929-ed77733ec07d"
Makefile:84: recipe for target 'btcd' failed
make: *** [btcd] Error 1

Not sure whats happening. 
thanks

**Comment by futjrn** [comment]
so I reset my VM cuz I thought maybe turning off bitcoind would be the fix. 

sudo make && make install builds until : 

github.com/lightningnetwork/lnd
GO111MODULE=on go build -v -tags="dev" -o lncli-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-708-g4fce641d6ac9da4b82d08f0c54540066c9f6e41e" github.com/lightningnetwork/lnd/cmd/lncli
/home/futjrn/go/src/github.com/lightningnetwork/lnd/cmd/lncli/autopilotrpc_default.go:5:8: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go-1.10/src/github.com/urfave/cli (from $GOROOT)
	/home/futjrn/go/src/github.com/urfave/cli (from $GOPATH)
Makefile:92: recipe for target 'build' failed
make: *** [build] Error 1


a sudo make check with bitcoind stopped still says the same thing

**Comment by Roasbeef** [comment]
I'd double check the location of both your $GOPATH and $GOROOT. Looks a configuration issue on your end, unable to reproduce.

**Comment by cfromknecht** [comment]
@futjrn you shouldn’t need sudo to run the make commands. If you do, something is definitely wrong with your go installation
