### ISSUE TITLE
Recover after out of mem error

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#2642]
### Background

Looks like we ran out of memory on this device and it caused lnd to crash. Do you think there is a way to recover from this?

### Your environment

* version of `lnd`
  0.5.1-beta commit=v0.5.1-beta
* which operating system (`uname -a` on *Nix)
  Linux lnd 4.14.70-v7+ #2 SMP Wed Sep 19 07:49:26 UTC 2018 armv7l Linux
* version of `btcd`, `bitcoind`, or other backend
  bitcoind: 0.17.0
* any other relevant environment details
  bitcoind and lnd are running in docker containers
  raspberry pi 3b+
* 2 GB swap file

### Steps to reproduce

New errors appear in the logs every time we unlock lnd. 

See specific logs here
[logs.txt](https://github.com/lightningnetwork/lnd/files/2865739/logs.txt)

### Expected behaviour

Lnd should boot up fine.

### Actual behaviour

Lnd crashes.

**Comment by vegardengen** [comment]
Can you show the output of the command "free" ? that should show your memory status,

It does look like there's no memory to run lnd, so it just crashes.

How much have you set your bitcoind to consume? Might consider to lower that if you now are finished syncing.

**Comment by wpaulino** [comment]
I believe the Go runtime does not allow recovering from an OOM if an allocation happens and there isn't enough memory. Instead, I'd determine what the culprit is for the high memory usage. If it's lnd, there are some nice memory optimizations for when a node has flappy peers in the current master branch.
