### ISSUE TITLE
Continuous lnd crash - panic: runtime error: index out of range - channel.db

### ISSUE THREAD

**Issue by larry-beck** [lightningnetwork/lnd#2643]
### Background
Looks like channel.db is corrupted on this device and it caused lnd to crash. Can you help me recover this DB file? The results of running bbolt on the channel.db file via compact and check options are noted below in the pastebin links as well as the entire lnd log from 15 minutes before the crash until the point after many restarts and reboots of the system that I manually stopped the lnd service. External HD is working fine, ran diagnostics on it and no errors or issues noted, so nothing wrong with drive the db file is located. All lnd and bitcoin node files are stored and run on the external HD as well, BTC node is running fine and in sync with bitcoin network and working as it should. All other files in lnd directories are readable and work just fine if I delete the channel.db file and restart lnd service. Raspi has as always 600MB RAM free of 1GB total, is it plugged along with external HD into UPS by itself and would run for days if a power outage and the UPS does not show any outages or brownouts, connected to 1GB hardwire network connection no wireless being used, internal system temp is only 60C/140F, so running cool for electronics. Thoughts/ideas to recover this db file and get my channels and funds back?

### Your environment
* version of `lnd`
  lnd version 0.5.2-beta commit=v0.5.2-beta
* which operating system
  Linux RaspiBolt 4.14.79-v7+ # 1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
* version of `bitcoind`
  Bitcoin Core Daemon version v0.17.1
* any other relevant environment details
  bitcoind and lnd are running
  Raspberry Pi 3 Model B Plus Rev 1.3
  4TB external USB WD hard drive
  128GB SD card for OS only
  swap file on external HD not SD card

### Steps to reproduce
New errors appear in the logs every time we unlock lnd.

### See specific logs here
bbolt check log: https://pastebin.com/e29qJJJr
bbolt compact log: https://pastebin.com/csiNWdcE
lnd log showing db file being accessed and error thrown in log: https://pastebin.com/KADCyuQJ

### Expected behavior
lnd should boot up fine.

### Actual behavior
lnd crashes.

**Comment by Roasbeef** [comment]
Resolved on slack that it was due to disk corruption.
