### ISSUE TITLE
Receiving node - Unable to query invoice registry when processing payments 

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2650]
### Background

I have two nodes A and B. They have a channel from payer to payee i.e. Node B to Node A
Node B bought from Node A, Node A invoiced Node B, Node B pays Node A.

Node A has only one channel to Node B
Node B has several channels, including channel to Node B. 

B->A channel was opened by Node B to make the payment, and it has enough capacity and local balance to pay Node A. 
The remote balance of A in the B->A channel is 0

Using sendroutesync to pay. As in the log, there is exactly 1 route, and 1 hope to make the payment, and the route is correctly picked (from a large selection of routes and hops).

Yet, when Node B tries to pay Node A, Node A is unable to find the invoice it prepared, in its own registry. This results in "UnknownpaymentHash" error - please see trace (debuglevel=SRVR=trace,PEER=trace,HSWC=trace)

### Your environment

* version of `lnd`  - 0.5.1-beta commit
* which operating system (`uname -a` on *Nix) -- iOS
* version of `btcd`, `bitcoind`, or other backend -- neutrino /btcd

### Steps to reproduce
1) Set up two nodes running on 0.5.1-beta, neutrino and btcd
2) Connect and open a channel
3) Have one invoice the other , and the other pay the invoice
4) Results in unknownpaymenthash due to not finding invoice in registry

### Expected behaviour

With routes and hops correctly selected, the expected behavior would be that the payment succeeds.

### Actual behaviour

"Unable to query invoice in registry" ---> "UnknownPaymentHash"

Log from both receiver (Node A) and sender of payment(Node B) viewpoints.
========================================================

[payment-trace.txt](https://github.com/lightningnetwork/lnd/files/2873302/payment-trace.txt)

**Comment by weaklysubjective** [comment]
For the same payment hash , SendPaymentSync works !

**Comment by Roasbeef** [comment]
I'd check your arguments to `SendToRouteSync`. Also generally, it's better to use the regular `SendPayment` methods if you're not doing anything custom as far as path finding.

**Comment by Roasbeef** [comment]
You likely hit this bug: https://github.com/lightningnetwork/lnd/commit/9c940746a748ab759e2f17957d825695c4f3ff42#diff-01ada5680aaa18fc79cbf78b2d55a37b

Fixed in master, so closing.

**Comment by weaklysubjective** [comment]
I'm setting only the hash as string is optional. I read the link, just to make sure i understand, is the issue because the optional payment string is not set ?
