### ISSUE TITLE
Can more than one person use a lnd node? or Everyone must have their own lnd node?

### ISSUE THREAD

**Issue by ocoderr** [lightningnetwork/lnd#2652]
I have a  bitcoin full node .I want to build a LND node for others to use. 
Can more than one person use a lnd node? or Everyone must have their own lnd node?

**Comment by brandoncurtis** [comment]
LND is designed to be used by a single user.  Whoever runs LND has full access to all funds stored in the LND node's on-chain wallet and off-chain channels.

If you create a service that runs LND and provides access to other users, you have created a custodial wallet where you control user funds.  Examples of custodial wallets include web wallets like https://htlc.me and https://tippin.me and mobile wallets like BlueWallet and Wallet of Satoshi.

Packages like LndHub allow you to create such a custodial service: https://github.com/BlueWallet/LndHub

Note that if your service is misconfigured or there are any bugs in the software or anyone else is able to gain access to your system in any way, they can steal everyone's funds.  LndHub has already had what appear to be potentially money-losing bugs:
- https://github.com/BlueWallet/LndHub/commit/dec313aa4cd05a0becee723ba84ec81ceb84b26a
- https://github.com/BlueWallet/LndHub/commit/d04b155e118403eaf3d8cb6cf61a25af709a4f90

Stay safe out there.  **Not your LND node, not your bitcoin.**

**Comment by ocoderr** [comment]
thanks
