### ISSUE TITLE
Check password size after seed generation

### ISSUE THREAD

**Issue by grunch** [lightningnetwork/lnd#2654]
### Background

The first step when you create your wallet is enter wallet password and confirm it, this password input has a size validation but it is checked at the end of the process, after the user answered two questions and the seed is generated, this check must be right after the user enter the confirmation wallet password.

### Your environment

* lncli version 0.5.1-beta commit=v0.5.1-beta-728-g44b8cd6699db84d9d163a31efc038571afe6d2be
* Linux wepa 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* I'm using neutrino on testnet

### Steps to reproduce
```
lncli -n testnet create
Input wallet password: 
Confirm wallet password: 

Do you have an existing cipher seed mnemonic you want to use? (Enter y/n): n

Your cipher seed can optionally be encrypted.
Input your passphrase if you wish to encrypt it (or press enter to proceed without a cipher seed passphrase): 

Generating fresh cipher seed...

!!!YOU MUST WRITE DOWN THIS SEED TO BE ABLE TO RESTORE THE WALLET!!!

---------------BEGIN LND CIPHER SEED---------------
 1. abstract   2. keep     3. save      4. anchor
 5. before     6. arena    7. divorce   8. basket
 9. joy       10. wealth  11. there    12. system
13. sister    14. leader  15. cluster  16. mail  
17. invest    18. iron    19. remove   20. diesel
21. junior    22. bonus   23. sweet    24. clock 
---------------END LND CIPHER SEED-----------------

!!!YOU MUST WRITE DOWN THIS SEED TO BE ABLE TO RESTORE THE WALLET!!!
[lncli] rpc error: code = Unknown desc = password must have at least 8 characters
```

**Comment by peername** [comment]
Same problem here.

**Comment by yancyribbens** [comment]
@valentinewallace @Roasbeef i'll take this one.

**Comment by wpaulino** [comment]
@yancyribbens #2680 has already been proposed as a solution.
