### ISSUE TITLE
Multiple lnd instances sharing bitcoind: update docs

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#2655]
https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md currently has a note discouraging this

> Don't connect more than two or three instances of lnd to bitcoind. With the default bitcoind settings, having more than one instance of lnd, or lnd plus any application that consumes the RPC could cause lnd to miss crucial updates from the backend

But this issue was fixed in 
https://github.com/lightningnetwork/lnd/pull/1566

**Comment by Roasbeef** [comment]
It wasn't. There're still issues if the user doesn't properly tune the number of RPC threads or their ZMQ high water limit.
