### ISSUE TITLE
channeldb: store the shachain key locator in instead of raw producer 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2659]
Atm, [we store the shachain root directly in `channeldb`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L481). Fortunately, [we derive this using the proper `keychain` key family, and use the serialize private key directly as the root](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L551). However, since we don' also store the `keychain.KeyLocator` information, during the implementation of the new SCB format, I was forced to brute force query the wallet in order to obtain the private key that's need in order to carry out the DLP protocol. In the current implementation, we consciously limit the search space to 10k or so, to avoid a very long lived search or an inadvertent infinite loop. Instead, we should store _only_ the `KeyLocator` information so we don' t need to perform this search. As a side effect, we'll also get away from storing this private key on disk in plaintext. 

**NOTE:** fixing this issue will involve a database migration. At this point, we've decided to hold off on all database migrations until we have a TLV system in place as it will make the migrations much more streamlined when we need to modify _values_ already stored in the system. 

# Steps To Completion 

- [ ] Using the yet-to-be-written TLV system, add a new field to the `channeldb.OpenChannel` struct that stores the `keychain.KeyLocator` for out `shachain` root. 

- [ ] Deprecate the old value for all new channels going forward 

- [ ] Update the yet-to-be-merged SCB feature to stop using the brute-force method, in favor of directly deriving the key based off of the key locator.

**Comment by Crypt-iQ** [comment]
Can I take this

**Comment by Crypt-iQ** [comment]
Taking this one!

**Comment by halseth** [comment]
The TLV migration strategy is not yet decided, so it might be a bit early to pick up :)

**Comment by Roasbeef** [comment]
Still planning to tackle this @Crypt-iQ?

**Comment by Crypt-iQ** [comment]
@roasbeef Yeah
