### ISSUE TITLE
Shouldn't the autopilot with several heuristics use the Harmonic mean instead of the Arithmetic one?

### ISSUE THREAD

**Issue by renepickhardt** [lightningnetwork/lnd#2665]
I found this line in your autopilot which combines several heuristics for the autopilot: 

https://github.com/lightningnetwork/lnd/blob/2bf22617d4edf571b2f0b4b46f1a2d721bef74c8/autopilot/combinedattach.go#L110

As far as I understand the scores are always supposed to be normalized which should mean that we are talking about rates. According to the  [Wikipedia article about the Harmonic mean](https://en.wikipedia.org/wiki/Harmonic_mean) this seems to be a better candidate than the arithmetic mean that is currently being used: 

> In mathematics, the harmonic mean [...] is appropriate for situations when the average of rates is desired.

The formula for a weighted harmonic mean can also be found in the wikipedia article: 

![codecogseqn](https://user-images.githubusercontent.com/1926816/53077362-188af280-34f2-11e9-8c41-10f1cba97c52.gif)

If you agree I would implement the weighted harmonic mean and exchange the current average and issue a pull request.

fyi: @alexbosworth @halseth

**Comment by halseth** [comment]
@renepickhardt The scores are in the range `[0,1]`, not sure if that qualifies as a rate?
