### ISSUE TITLE
LND doesn't broadcast URI when port 9735 tunneled from a different external IP

### ISSUE THREAD

**Issue by Chrozayis** [lightningnetwork/lnd#2667]
### Background
I was having a bunch of issue with NAT and port forwarding from my small-brand router. Looking around here I found some answers buried in the issues. I'll try those when I have router access again.

In the mean time I've tunneled port 9735 from my AWS machine to my local lnd server using `ssh -R`.
I set the externalip field to the AWS VM's public ip. I can confirm using Eclair Mobile that I can connect using `pubkey@awsip:9735`, however `getinfo` and `getnodeinfo mypubkey` don't return any URIs whatsoever.

### Your environment

* version of `lnd`
0.5.1-beta
* which operating system (`uname -a` on *Nix)
4.14.94-1-MANJARO
* version of `btcd`, `bitcoind`, or other backend
Bitcoind v0.16.3.0-g49e34e288005
* any other relevant environment details
Person in charge of setting this up (me) doesn't understand networking.

### Steps to reproduce

1. Tunnel port 9735 from a virtual server to a local lnd instance.
2. Set externalip to the VM's ip (the IP I want lnd to be broadcasting)

### Expected behaviour

Externalip setting is used to create the broadcasted URI even if it doesn't match the lnd server's public ip.

### Actual behaviour

No URIs are broadcast. `getnodeinfo` says my URIs are null.

**Comment by Roasbeef** [comment]
Does the node have any active channels?

**Comment by Chrozayis** [comment]
Yes. There are 35 outbound channels (~2 might be duplicates). Incoming and outgoing payments work fine.
There is also one private inbound channel that I made with Eclair

**Comment by Chrozayis** [comment]
Found the problem. Had to do with how bash handles comments in a launcher file.
You can show you have the same issue as me if `lncli stop` ends your log with `... unknown command...`
lnd is not at fault.
