### ISSUE TITLE
Bump to go1.11.5

### ISSUE THREAD

**Issue by Gfloresechaiz** [lightningnetwork/lnd#2670]
I've noticed that some users run into trouble with their installation whenever they don't have the right version of Go. Currently, the installation instructions from the official repo at INSTALL.md for Linux indicate to download and install go1.11.4.linux-amd64.tar.gz but 1.11.5 is the latest stable version available. 

I would simply like to recommend to modify the package name from 1.11.4 to 1.11.5 and the hashes associated with them. Let me know what you think. I have quickly modified this part of the INSTALL.md document if it can help : 

(x86-64)

wget https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
sha256sum go1.11.5.linux-amd64.tar.gz | awk -F " " '{ print $1 }'

The final output of the command above should be 
ff54aafedff961eb94792487e827515da683d61a5f9482f668008832631e5d25. If it isn't, then the target REPO HAS BEEN MODIFIED, and you shouldn't install this version of Go. If it matches, then proceed to install Go:

tar -C /usr/local -xzf go1.11.5.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

(ARMv6)

wget https://dl.google.com/go/go1.11.5.linux-armv6l.tar.gz
sha256sum go1.11.5.linux-armv6l.tar.gz | awk -F " " '{ print $1 }'

The final output of the command above should be b26b53c94923f78955236386fee0725ef4e76b6cb47e0df0ed0c0c4724e7b198. If it isn't, then the target REPO HAS BEEN MODIFIED, and you shouldn't install this version of Go. If it matches, then proceed to install Go:

tar -C /usr/local -xzf go1.11.5.linux-armv6l.tar.gz
export PATH=$PATH:/usr/local/go/bin

**Comment by Roasbeef** [comment]
Want to go ahead and turn this into a PR?

**Comment by Gfloresechaiz** [comment]
Done. 

https://github.com/lightningnetwork/lnd/pull/2672
