### ISSUE TITLE
Incorrect versioning

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#2673]
"build.Commit=v0.5.1-beta-762-ge1382bd4fc118ba2e93b1e987f94bc1a1b1fec3d"
Shouldn't this commit be v0.5.2?

**Comment by wpaulino** [comment]
0.5.2 was branched off of master to prevent introducing new features as it's meant to be a minor release. That release has the proper version. The master branch however is still building on top of the latest major release 0.5.1.
