### ISSUE TITLE
SendCoins does not check for mainnet or testnet

### ISSUE THREAD

**Issue by michaelWuensch** [lightningnetwork/lnd#2677]
### Background

The gRPC SendCoin command does not check if the destination address belongs to testnet or mainnet.
It is not a big deal, as any developer can check this before calling the command, but still I think it would be nice to have that extra security.
Note: I only tested sending testcoins to mainnet addresses, not the other way arround.

### Your environment

LND: 0.5.1-beta commit=v0.5.1-beta-263-g552a9b7190e14269f612f7fda401172d6e81f147
operating system: Linux Manjaro

### Steps to reproduce

1. Configure your LND to use testnet
2. Use SendCoin gRPC command to send testnet coins to a mainnet address

### Expected behaviour

It should throw an error: Wrong network

### Actual behaviour

It works and the coins are gone

**Comment by ccdle12** [comment]
Wow, that does seem a little bit dangerous. I'd be happy to pick this one up.

**Comment by halseth** [comment]
Hm, I'm wondering whether we would enforce this in `btcutil.DecodeAddress` instead? To ensure the address only validates for the expected network.
