### ISSUE TITLE
[Enquiry] advice for tuning "fee_per_kw"

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2683]
I am a newbie and my target is to setup a payment router.

The api documentation of "fee_per_kw"

> The required number of satoshis per kilo-weight that the requester will pay at all times, for both the funding transaction and commitment transaction. This value can later be updated once the channel is open.

I do not quite understand this, if i want to charge 0.1% when forward payment, then i should set fee_per_kw=1 ?

**Comment by Roasbeef** [comment]
No look at `updatechanpolicy`.
