### ISSUE TITLE
[Enquiry] concept of channel fee

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2684]
AFAIK, each channel has its own fee rate, which is "fee_per_kw"

For the following setup:

             A   ----(HIGH Fee rate) ----  B  ----------------  C

B want to charge A for more fee, he raises the fee of their channel

1. A pays to C
2. A pays to B
3. C pays to A

The high fee rate only affects case 1, am i correct?

Thanks in advance.

**Comment by Roasbeef** [comment]
Questions are better asked on IRC or Slack. He'll raise the fee from channel B -> C.
