### ISSUE TITLE
listchannels REST endpoint fails with HTTP 500

### ISSUE THREAD

**Issue by Heebron** [lightningnetwork/lnd#2694]
I am writing an application to interact with lnd using its REST API.  After updating to v0.5.2-beta I noticed that the 'listchannels' endpoint responds with an http 500 error:

The response code is: 500 and the response message is the default for that code, 'Internal Server Error'

The error comes in batches.  I call the endpoint once every 10 seconds and it will run for quite some time without a problem - returning the expected JSON. Then it will return the 500 error for an hour or more, then go back to working. 

lnd only logs 
```
lnd.log:2019-02-23 08:16:11.228 [INF] RPCS: [listchannels] fetched 16 channels from DB
```
It does not log any kind of error when the 500 is being returned. Setting config item debug to debug does not show any errors.

I suspect that the serialization process from your internal data structure to JSON is where the problem lies and that the root of the problem is channel specific - perhaps the particular metadata of a channel is not complete or contains something about it that the serialization process stumbles upon.

I'm not a 'go' programmer - but am learning. eventually, I'd like to contribute more than a possible bug report.

I use Ubuntu 18.10 running a full bitcoind node at version:
```
Bitcoin Core Daemon version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8
```
lnd version is 0.5.2-beta
My node name on 1ml.com is Babylon-4

**Comment by Roasbeef** [comment]
Unable to reproduce w/ 0.8. We log _all_ RPC errors now, so if you're able to reproduce, then we'll examine it, and ideally re-open this issue.
