### ISSUE TITLE
Make the ChannelRouter and ChannelGraph re-org aware

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#270]
# Issue

Currently, the channel router attempts [prunes edges from the `ChannelGraph`](https://godoc.org/github.com/lightningnetwork/lnd/channeldb#ChannelGraph.PruneGraph) with each new block that's connected to the end of the main chain. The set of outpoints (channels) that the `ChannelRouter` watches is the [`ChannelView`](https://godoc.org/github.com/lightningnetwork/lnd/channeldb#ChannelGraph.ChannelView) which contains the set of all unspent channel outputs. Whenever any of these outputs is spent within a block, the `ChannelRouter` will use the `ChannelGraph` to remove that edge, thereby pruning the closed channel from the known channel graph. 

The behavior described above is insufficient due the the possibility of a re-org invalidating prior confirmed funding transactions, thereby temporarily closing the channel as it now has a "negative" confirmation. Therefore, the `ChannelRouter` and `ChannelGraph `need to be modified in order be aware of reorganizations, and to act upon them by pruning any channels that were affected by the re-org. 

# Steps to Completion 

The [`FilteredChainView`](https://godoc.org/github.com/lightningnetwork/lnd/routing/chainview#FilteredChainView) interface is used by the `ChannelRouter` to receive notification whenever a the current `ChainView` watched by the router has been modified by a connected block. Currently, the `ChannelRouter` only acts upon [_connected_](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L421) blocks that may affect the chain view. The `ChannelRouter` should be modified to also act upon _disconnected_ blocks that may affect the chain view. In addition, the `ChannelGraph` struct will need to be modified (possibly along with some of the database indexes) to allow one to prune all channels within a certain `chan_id` range. 

- [ ] Within the `btcd` implementation of `FilteredChainView` [add the necessary code to actually notify the client upon disconnected blocks](https://github.com/lightningnetwork/lnd/blob/master/routing/chainview/btcd.go#L176). 

- [ ] [Add](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L170) a `staleBlocks` attribute to the `ChannelRouter` and initialize it within the `Start()` method. 

- [ ] Upon each stale block found a new `PruneByHeight(height uint32)` method added to the `ChannelGraph` should be called. This method takes a height to prune, and turns that height into a range of channel ID's that should be scanned for, and removed from all indexes. 

- [ ] Implement the `PruneByHeight` method that should be added to the `ChannelGraph`. This method should take the passed height, and map it into two `lnwire.ShortChannelID` instances. The first will consist of `lnwire.ShortChannelID{BlockHeight: blockHeight}`, and the second `lnwire.ShortChannelID{BlockHeight: blockHeight, TxIndex: math.MaxUint32, TxPosition: math.MaxUint16`. These will be used to scan the database a [`Cursor`](https://github.com/boltdb/bolt#iterating-over-keys). 
    
    Within `channeldb/graph.go`, the [`edgeIndexBucket`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/graph.go#L62) stores a mapping of `chanID -> ... `. This is the primary index that's used to look up channels by their short chan ID. The other buckets that should be considered are the `channelPointBucket`, and the `edgeBucket`. When scanning the `edgeIndexBucket` with this range scan, the other two will need to be modified as well in order to ensure that the graph database remains in a sane state. At the end of the scan, the `pruneTipKey` should be updated as well to mark the current prune tip. 

- [ ] Upon startup, the `ChannelRouter` calls [`syncGraphWithChain`](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L283) with the assumption that it can only ever be behind the main chain, on the most work branch. With this in mind it then walks _forwards_ in the chain to catch up on blocks that may have pruned items within the `ChannelGraph`. This routing should also be modified to be aware of the case where `lnd` has been offline for some time, and wakes up on a _stale_ branch. In this case, it should walk backwards pruning each block until it matches up with the common block hash that's found in both the main chain and this side chain. From there, it should then resume the normal "walk forwards and prune" procedure.

**Comment by halseth** [comment]
I'll take this one :)
