### ISSUE TITLE
Feature Request: grpc restrictions

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#2709]
### Background

Currently when running a node it is under the assumption that once unlocked any function should be able to be performed by the bearer of the macaroon.

Assuming that a webserver is improperly set up and serving the macaroon or someone accessed it from source control or something (I know, edge cases, but just for ex.) it would be nice if there was a way to restrict or whitelist features.

### Example lnd.conf

Ex. only allow sending from this wallet to whitelisted addresses via gRpc or REST -
```
chain.whitelist='1HL2GgCjCxZsUwvHD5wWd8SUNm14zDojUb, 3HgSqhtPb1MWwjvrDaVhjqJ3bD7WfdfEB3'
```
ex. only allow paying invoice from whitelisted nodes
```
node.whitelist='032bf50d657c83e911b3f40ed26a8280f48ad75aca58cd6f8e82f04adf943bbf50'
```

### Purpose

When setting up a node for others for example who are less technical there should be a way to help them protect themselves from poor opsec.

By allowing whitelisted addresses only you can try to help secure from loss of funds situations.

**Comment by MDrollette** [comment]
The macaroons themselves should contain those restrictions (caveats). There is work in progress to allow for more types of caveats on top of the limited set that exists today, like the whitelisting you mention. Currently, we only generate pre-defined admin, read-only, and invoicing macaroons. But in the situation you describe you might only want to give the user a macaroon that is limited in what it can do (send to a specific address or have a balance limit, etc.) and never expose the admin macaroon to them at all.

There is a project that is collecting some of this macaroon work https://github.com/lightningnetwork/lnd/projects/3

**Comment by PWKad** [comment]
I mostly agree but in this case I'm talking more about the fact that a "normal" user won't know what a macaroon is so won't really be able to configure it that way, it's really a fallback but since everyone and their brother is encouraging different ways to spin up fresh full LND nodes I was thinking how to aid that specific workflow by providing a few params to help keep them safe.

In hindsight though that still requires configuration by the end user so not sure that's a better approach, but would love to hear if anyone else has feedback.

**Comment by MDrollette** [comment]
That makes sense. I think the mechanism is definitely the macaroon, though I agree a better UI/UX is needed to create and use them - ideally without the user even knowing that they are creating/using them. From a user perspective it's just a set of capabilities (I can do this and can't do that), the implementation shouldn't be their concern.

**Comment by Roasbeef** [comment]
Closing as we'd rather stick with our current credentials based system rather than using ACLs.
