### ISSUE TITLE
Fuzz the wire parser in the lnwire package

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#271]
# Issue

Currently, within the `lnwire` package, we have a set that uses the [`testing/quick`](https://golang.org/pkg/testing/quick/) package to create a set of block-block tests that use the quickcheck testing paradigm to exercise our wire parser. This set of tests uses property based testing to ensure that the parser is able to adhere to the [`mainScenario`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/lnwire_test.go#L95), amongst other things, this ensures that we'll always be able to consume a message that we produced, ensuring correctness of our wire parsing implementation. 

This set of tests are nice, but insufficient. What we _really_ want to ensure (for safety/security properties) is that: no sequence or random bytes, partially correct wire encodings, or mutated wire encodings case `lnd` to _crash_. We
ll need to ensure that under the presence of arbitrary malicious input, `lnd` partially parses, them ignores them if invalid, and keeps on trucking. This can be achieved by what's known as [fuzz testing](https://en.wikipedia.org/wiki/Fuzzing). 

There exists a popular fuzz-testing library written in golang, called [`go-fuzz`](https://github.com/dvyukov/go-fuzz), we can use this to being the process of first fuzzing encoding/decoding code within the `lnwire` package. In the future, we can expand our usage to cover other relevant areas of the codebase. 

# Steps To Completion 

- [x] Get familiar with how the `go-fuzz` package is used by [reading the documentation](https://github.com/dvyukov/go-fuzz). 

- [x] Create an applicable fuzz function within the `lnwire` package. This may closely resemble the `mainScenario` used within the tests, but should call `panic` rather than failing the test. 

- [x] Next, gather an initial testing corpus. This should consist of known valid serialized wire messages. At the very least, there should be an entry for _each_ of the known wire messages defined within the current [specification](https://github.com/lightningnetwork/lnd/blob/master/lnwire/message.go#L23). A diversity of input is desirable, so these can be obtained by either adding some code to `lnd` to dump valid messages into a file, or by generating them manually. 

- [x] Execute the fuzzer with the defined fuzz function, and corpus. 

- [x] Monitor the execution of the fuzzer, noting which inputs cause the fuzz function to panic. Examine the inputs, and the current parsing code, creating PR's fixing the panic for each input found. 

- [x] ????

- [x] Profit 🎉

**Comment by Crypt-iQ** [comment]
I can do this - I've used American Fuzzy Lop before so this is familiar territory.

**Comment by Crypt-iQ** [comment]
I made a PR for one error that `go-fuzz` found: https://github.com/lightningnetwork/lnd/pull/310

**Comment by halseth** [comment]
Good finds! 😃  How hard would it be to add the fuzz test that found these errors together with the fix?

**Comment by Crypt-iQ** [comment]
@halseth do you mean the malicious input?  I'm not sure where I'd put it and whether it belongs in a PR.  I could make a gist though...

**Comment by halseth** [comment]
I'm not familiar enough with `go-fuzz` to know what this input looks like 😛  It would be nice if the fuzz tests ran continuously together with the rest of the tests, to make sure the bugs are not introduced again, and maybe catch more?

**Comment by Crypt-iQ** [comment]
@halseth I would agree, but the corpus that `go-fuzz` generates might get too large to include in a repo.  This is a specific test I made to follow the stacktrace that the fuzzer gave me upon crash: https://gist.github.com/Crypt-iQ/96ef579fb6229b6f47ec8c0d41aecd10

**Comment by halseth** [comment]
Aha, cool :) Let's hear what @Roasbeef was thinking. Thanks!

**Comment by Crypt-iQ** [comment]
No problem !

**Comment by Crypt-iQ** [comment]
One thing that `go-fuzz` found was that when deserializing `MsgFundingSigned` messages and then asserting equality after serialization, the two `[]byte` (pre-deserialization and post-serialization) are not deeply equal.  This is because of [line #54](https://github.com/Roasbeef/btcd/blob/master/btcec/signature.go#L54) here which is called only on serialization of `MsgFundingSigned` and alters `*Signature.S`.  Is it intended that the `S` value be different upon deserialization & serialization?  I ask since this seems a bit involved and I'd have to brush up on my cryptography to assess this.

**Comment by Crypt-iQ** [comment]
I believe that `go-fuzz` has found all of the bugs it can find with the given corpus.  I simply started with a serialized message for each message type and let `go-fuzz` generate the rest of the corpus.  After several hours of running, it has found no more crashes.

**Comment by Roasbeef** [comment]
Thanks for all the work on this @Crypt-iQ! Do you think you could add some documentation under the `docs` folder which details how you set up your harness for fuzzing? This would include the initial corpus (possible committed as a compressed file), and the fuzzing function you used. 

I envision this to be useful as we'll likely want to re-run the fuzzer in the future as we make modifications to the wire parsing, and also simply for educational purposes 📚.

**Comment by Crypt-iQ** [comment]
Of course! @Roasbeef

**Comment by Roasbeef** [comment]
Current running fuzzing graveyard: 
  * #310  
  * #312

**Comment by Roasbeef** [comment]
I have a machine with the fuzzing set up recently added running now. I'll continue to monitor this over the next few days/weeks and report here with any new issues found, re-opening as necessary. 

Closing.
