### ISSUE TITLE
peer disconnected when create channel with tor onion node

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#2710]
version: v0.5.2-beta

I try to create channel between 2 lnd nodes, they are using tor (inbound+outbound).

First, "lncli connect", success and no error.
Then, verify by "lncli listpeers", they list each other as peers and no error.

Finally, then i try to create channel between the nodes. lncli always timeout and "peer disconnected" messages are found in the backend log.

>  [INF] PEER: Disconnecting xxx.onion:9735, reason: unable to start peer: unable to read init msg: EOF

I tried to reset tor by deleting their data directory, but problem still exists.

Any help is appreciated

**Comment by Roasbeef** [comment]
Check the logs to see why the peers are disconnecting.
