### ISSUE TITLE
Support for distributed key value store for HA deployments?

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#2712]
Currently lnd uses persistence based on an embedded key value store http://github.com/etcd-io/bbolt
If any disk issue happen, such as corruption or malfunction, the application state is lost causing loss of funds or loss of availability (until a backup is restored).

To prevent the problems above, and to have both high availability and failure tolerance, one way is to use a distributed database underneath so that state is transparently replicated by the database engine  to other nodes so that even with catastrophic failures the state is available elsewhere.

When it comes to Golang, one option of such distributed databases is [cockroachDB](https://github.com/cockroachdb/cockroach), but I reckon this is not the only option.

What does the lnd team think about this feature? It'd require a pluggable persistence layer that would allow the operator/user to optionally use a distributed database for high avaialbility and failure tolerance scenarios

**Comment by Roasbeef** [comment]
See #413
