### ISSUE TITLE
Slow Startup: RPC commands delayed and stalling

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#2719]
### Background

Describe your issue here.
Have around 460 channels, running lnd  on go 1.11.5, seeing increased memory usage as well, when booting up for quite some time RPC commands are delayed and stall.

### Your environment

* version of `lnd` 0.5.2-99-beta commit=v0.5.1-beta-805-ga6cf6f4237ef53b1f0c51c2fcfb9c1ce73cf9e06

* which operating system (`uname -a` on *Nix) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.17
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question

go profile dump:  http://paste.ubuntu.com/p/SsyVbRYrWt/

### Expected behaviour

Tell us what should happen
RPC commands responding not so slowly
### Actual behaviour
Tell us what happens instead

RPC commands take almost a minute to respond. Although after some time running, RPC commands do respond swiftly like normal

**Comment by halseth** [comment]
Hunch is that the `rpcserver` is querying the backend for best blocks, timestamps etc, while it is in process of registering block/spends subscriptions.

**Comment by wpaulino** [comment]
Also all the recent gossip growth can lead to performing many database operations which hold the lock.

**Comment by Roasbeef** [comment]
@juscamarena addressed by 0.6 and also the new `--stagger-initial-reconnect`?

**Comment by juscamarena** [comment]
Yes, addressed by that and earlier fixes.

Can be closed, thanks for the improvements. :)
