### ISSUE TITLE
Convert all onion errors to adhere to the error interface, interpret in ChannelRouter

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#272]
# Issue 

Within the protocol, we use onion routed payment paths to add a degree of censorship resistance and privacy to the process of sending and forwarding payments within the network. We also re-use the generated onion circuits to send HTLC related forwarding errors on the _backwards) path. Details of the format and types of these errors can be found in [`BOLT-0004`](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#returning-errors). 

Our current implementation uses a [`FailureMessage`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L14) interface to distinguish the different types of errors. Some errors carry a payload, while others are simply empty. When an error occurs in the current codebase, the [`HltcSwitch`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L100) is the [sub-system that currently handles them](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L383). If the error carries a [`ChannelUpdate`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/channel_update.go#L11) message, then it is applied to the channel graph using the `UpdateTopology` closure. 

Rather than the switch handling the errors, the `ChannelRouter` should handle them. The current behavior can cause the router to continue attempting to send payments using the other `k-i`(where `i` is the number of routes tried to far) routes it obtained. This is the wrong behavior for certain classes of errors like [`FailUnknownPaymentHash`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L235) which should cause termination of the send attempt rather than retrying. 

# Steps to Completion

- [ ] Convert all errors within [`onion_error.go`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go) to adhere to the [error interface](https://golang.org/pkg/builtin/#error). 

- [x] Remove the [`UpdateTopology`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L93) field from the htlcswitch's config struct. This is no longer needed as we'll be pushing up interpretation of the errors to one layer above: the `ChanneRouter`.

- [x] [After decrypting the error within the switch](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L388), simply return the error back to the `ChannelRouter`, removing the other logic. 

- [x] Within the main [`SendPayment` loop](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L1019), rather than unconditionally continuing, [a type switch](https://tour.golang.org/methods/16) should be used to identify the type of error. Depending on the error return, the following actions should be carried out:
    * If the error is permanent, like "unknown payment hash", then the loop should be terminated, with the error being returned to the user. This goes for types `PERM|NODE`, `PERM`    
    * For error types of `UPDATE`, then new channel update should be validated and committed to the channel graph if valid. Case-by-case, we should either continue, or break out to re-run the path finding algorithm, with either the new information, or removing an edge from consideration. We may need to add a set of temporarily black listed edges to the path finding logic for this case.

**Comment by johng** [comment]
For errors of type NODE and FlagBadOnion, what is the expected behaviour?

**Comment by Roasbeef** [comment]
Fixed as part of: https://git.io/vdCym
