### ISSUE TITLE
Expose a command to verify addresses to the api

### ISSUE THREAD

**Issue by michaelWuensch** [lightningnetwork/lnd#2721]
### Background

I am using LND to create a nice looking, easy to use Wallet. To create a great user experience, I want to have a good error handling, showing usable and easy to understand errors.

When sending coins (on-chain), I want to be able to actually check the validity of the address **before** I use the gRPC SendCoins command. Right when scanning a QR-Code the user should already receive messages like: This is not a vaild bitcoin address.

I know, I can program it myself, but it would be great if that "low level" stuff could be handled by LND to make LND easily integratable into any environment.
The validity checks already exist in LND, an exposure to a separate API command would be great.

This only applies for on-chain addresses.
For lightning payments it is already possible using the "decodePayReq" command

As an example the command could look like this:
Name: verifyAddress
Input: Bitcoin Address
Output:  bool isValid, int error  (error = 0 -> wrong checksum, error = 1 -> different network, ...)

### Environment

LND: 0.5.1-beta commit=v0.5.1-beta-263-g552a9b7190e14269f612f7fda401172d6e81f147
Operating system: Linux Manjaro

**Comment by Roasbeef** [comment]
I don't think we'll be adding something like this. If you're scripting a Bitcoin related service, it should be also able to properly verify the address.
