### ISSUE TITLE
error:transaction output is dust when trying to sweep funds

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#2725]
On mainnet v0.5.2 when trying to sweep the coins from my on-chain wallet.
Dust should be added to fee.

(Posted on https://github.com/ShahanaFarooqui/RTL/issues/75 but I don't think this is RTL related issue)

I guess that there is a bug in the sweep all that somehow create a very small change ?

**Comment by capacitynetwork** [comment]
See https://github.com/lightningnetwork/lnd/issues/2527

But master has bugs, do not advise upgrading to master, I have just made this mistake.

**Comment by NicolasDorier** [comment]
I can pick a single commit if the fix to this problem is simple.

**Comment by molxyz** [comment]
@NicolasDorier I'm not sure if you're looking for this PR:  https://github.com/lightningnetwork/lnd/pull/2198 ?

This PR will sweep all dust amounts, it's not in v0.5.2, only in master. It works great for me.

**Comment by NicolasDorier** [comment]
@molxyz I am very confused. Ride the Lightning use the sweepall feature of LND, so this should be on 0.5.2. And this is precisely using this feature in Ride the Lightning which give me this error.

**Comment by NicolasDorier** [comment]
Ok so they are using `SendAll` on `/transactions` (https://github.com/ShahanaFarooqui/RTL/commit/5b8f48d989510ad0a8f038a56daa4f8805e544fa) not sweepall. How are they different?

**Comment by NicolasDorier** [comment]
Ah I think this is ignored on RTL because not supported on 0.5.2!
