### ISSUE TITLE
Data loss protection disabled by default on master?

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2727]
I'm getting reports from users having issues connecting to LND master (such as https://github.com/btcontract/lnwallet/issues/133). BLW disallows creating channels with nodes without data loss protection and seems like it's turned off now. Is this intentional? If yes, what are the reasons for this change?

**Comment by cfromknecht** [comment]
@btcontract lnd advertises required dlp by default and there is no way to change that otherwise via the cli. If you inspect the init we send, is the correct bit set? We fixed a bug in lnd that would not properly detect required feature bits, im curious if maybe the same thing is happening in blw?

**Comment by btcontract** [comment]
Thanks for the suggestion, turned out it was exactly a bug in BLW which was causing an incorrect mandatory feature support detection. LND master sends `81` in init which contains a `OPTION_DATA_LOSS_PROTECT_MANDATORY` bit instead of optional as it was earlier.

**Comment by cfromknecht** [comment]
Awesome, feature bit implementation has indeed been more nuisanced than they appear at the surface level :)
