### ISSUE TITLE
Expose payment hash to the API for forwarded payments

### ISSUE THREAD

**Issue by sergioabril** [lightningnetwork/lnd#2731]
### Background

When listing routed payments by using `lncli fwdinghistory`, it shows the history of transactions that were routed by that node. However, with the information provided right now by the API, it's hard to match each one of them with a real payment/invoice. It would be useful to have more information about these, like the **payment hash**. That could ease the process of tracking payments, by comparing the hash of an invoice with its respective hash on a routing node. Really useful when using a setup that includes having a specific node in place as a gateway for payments (For instance, you could check if an invoice was really paid from your node, by checking your gateway node, and looking for matches by payment hash. Right now, without a **payment hash** field exposed, it's really hard)

### Your environment

* Lnd 0.5.2
* (Any environment or bitcoin node setup)

### Steps to reproduce

Type `lncli fwdinghistory`

### Expected behaviour

**Payment hash** for every forwarded transaction should be shown, to be able to look up and track payments by its hash (i.e. when using a routing node on purpose)

### Actual behaviour

Only **timestamp**, **chan_id's**, **amnt**, and **fee** are exposed at the moment.

**Comment by yyforyongyu** [comment]
I'm looking into this one. Currently, there seems no better way but to add a new field `PaymentHash` to `channeldb.ForwardingEvent`, which involves db migration, painful.

**Comment by guggero** [comment]
I think this can now be implemented externally to `lnd` by using the [HTLC interceptor](https://github.com/lightningnetwork/lnd/pull/4018). I don't think we should by default add this information to the DB as most users aren't necessarily interested in that information. Routing nodes that really are interested in knowing the forwarded payment hashes can use the interceptor to write them to an external database.

**Comment by carlaKC** [comment]
The problem with using HTLC interceptor for something like this is that you can't guarantee that you will get the payment hash for every forwarded htlc - say your interceptor goes down and you miss a forward, there's no (easy) way to recover it. Depending on use case, it could be fine to miss the occasional payment hash. 

A long-term solution for the strict use case (and a lot of other auditing issues) would be to expose each commitment that we have saved for a channel, and keep them around once the channel has been closed (probably opt-in, it's a lot of data). It would be a bit of leg work, but one could then link forwards to payment hashes in the commitments themselves. This is something I started looking into in #4088, but it's a complex task and there didn't seem to be too much demand at the time.

**Comment by LNBIG-COM** [comment]
+1

I need this feature too because I want to calculate a real balance of all nodes and I want to know which pending HTLCs have preimage inside my LND and which are not. The only way that comes to my mind so far is to match `forwarding_events` with `pending_htlcs`. The `pending_htlcs` have `hash_lock` but `forwarding_events` have not.

**Comment by carlaKC** [comment]
> I want to know which pending HTLCs have preimage inside my LND and which are not. 

If you want to know whether the forwarding event is a payment to/from your node, you can look at the `event_type` field for to check whether it is a send, receive or forward. Would that help?

> The only way that comes to my mind so far is to match `forwarding_events` with `pending_htlcs`. The `pending_htlcs` have `hash_lock` but `forwarding_events` have not.

In the latest release, pending htlcs expose their forwarding channel and htlc index so you should be able to match them against forwarding events as is. But agreed that adding hash would be much simpler.

**Comment by Roasbeef** [comment]
Available as part of https://github.com/lightningnetwork/lnd/pull/4018
