### ISSUE TITLE
Unable to sweep coins from lnd wallet

### ISSUE THREAD

**Issue by hex17or** [lightningnetwork/lnd#2733]
### Background

I want to sweep my balance of 185 877 031 sats from the lnd wallet to another wallet. However, when I issue the `sendcoins` command with the flag `--sweepall`, Ind throws an 'incorrect usage' error with the message `flag provided but not defined: -sweepall`

### Your environment

* version of `lnd` : lncli version 0.5.2-beta commit=v0.5.2-beta
* which operating system : Linux 4.15.0-43-generic #46-Ubuntu SMP
* version of `bitcoind`: Bitcoin Core Daemon version v0.17.1
* running on a scaleway x86-64 VPS

### Steps to reproduce

    $ lncli --network=testnet sendcoins --sweepall --addr tb1qv9rvjrxl69yztu0t4xmyxzakszj44883ug687h
    Incorrect Usage.

    NAME:
       lncli sendcoins - Send bitcoin on-chain to an address.

    USAGE:
       lncli sendcoins [command options] addr amt

    CATEGORY:
       On-chain

    DESCRIPTION:

      Send amt coins in satoshis to the BASE58 encoded bitcoin address addr.

      Fees used when sending the transaction can be specified via the --conf_target, or
      --sat_per_byte optional flags.

      Positional arguments and flags can be used interchangeably but not at the same time!

    OPTIONS:
       --addr value          the BASE58 encoded bitcoin address to send coins to on-chain
       --amt value           the number of bitcoin denominated in satoshis to send (default: 0)
       --conf_target value   (optional) the number of blocks that the transaction *should* confirm in, will     be used for fee estimation (default: 0)
       --sat_per_byte value  (optional) a manual fee expressed in sat/byte that should be used when crafting the transaction (default: 0)

    [lncli] flag provided but not defined: -sweepall

### Expected behaviour

lnd should sweep my wallet balance to the destination address

### Actual behaviour

lnd throws up an 'incorrect usage' error

**Comment by cfromknecht** [comment]
@hex17or as the error message indicates, `--sweepall` is not available in 0.5.2. this capability is in master and will be available in the coming 0.6 release
