### ISSUE TITLE
24 word mnemonic generated is not BIP39 compliant 

### ISSUE THREAD

**Issue by pandeykumar** [lightningnetwork/lnd#2735]
### Background

The 24 word seed mnemonic gereated by lncli create doesn not seem to be BIP39 compliant.
I tried validating it via https://iancoleman.io/bip39/#english ( the local copy of it ) and trying to import it as bip39 seed in electrum and get  checksum failed. 
Is this expected?  I haven't moved any fund in the wallet so if needed I can put the seed here 

passphrase was not used to protect the seed.

lnd seems to like it just fine as I can create new addresses...
### Your environment

* version of `lnd`: 0.5.2-beta
* which operating system (`uname -a` on *Nix) : pi B+ (Linux kcryptlnd 4.14.79-v7+ #1159 SMP)
* version of `btcd`, `bitcoind`, or other backend : bitcoin v0.17.0.1 mainnet
* any other relevant environment details : RaspiBlitz v1.0

### Steps to reproduce

When first setting up lnd as part of setting up wallet

### Expected behaviour

24 word mnemonic should be importable in Electrum o
### Actual behaviour

getting checksum failed

**Comment by cfromknecht** [comment]
@pandeykumar yes this is expected, electrum and lnd use different seed formats. electrum uses BIP 38 while lnd uses a cipherseed. see https://github.com/lightningnetwork/lnd/tree/master/aezeed for more info on lnd's seed format

**Comment by penguin4238** [comment]
hey why we dnt support BIP 39? i suppose we should add this feature
