### ISSUE TITLE
RTL web interface and cli main menu show different wallet balances

### ISSUE THREAD

**Issue by jaramburu** [lightningnetwork/lnd#2738]
I sent some BTC to my on-chain wallet via 'Funding' on the the cli menu. The tx was confirmed several times and the correct balance appears when I open the RTL web interface. However, the cli and zap mobile wallet still display the old balance (ie before I sent funds on chain). Why would this be? For reference, I have channel autopilot disabled.
<img width="752" alt="screenshot 2019-03-06 17 02 53" src="https://user-images.githubusercontent.com/5151478/53924665-cdb0c500-4031-11e9-83fd-a6bdb6e9907a.png">
<img width="491" alt="screenshot 2019-03-06 17 03 07" src="https://user-images.githubusercontent.com/5151478/53924666-ce495b80-4031-11e9-8407-a0f980036a31.png">

**Comment by molxyz** [comment]
@jaramburu These apps weren't created by the LND devs, you should ask the people who created them.
