### ISSUE TITLE
Don't unconditionally create a new NodeAnnouncement upon startup

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#274]
# Issue

[Atm, upon start up we'll unconditnioally create a new node announcement, write it to the database, sign the announcement ~~and broadcast it to the network~~](https://github.com/lightningnetwork/lnd/blob/master/server.go#L212). This is unnecessary, as we should only do this if configuration options between this running instance and the last have modified what our `NodeAnnouncement` _should_ be within the network. 

# Steps to Completion 

- [ ] Rather than doing the above unconditionally, we should instead craft a new node announcement based on the relevant configuration options, and compare that with the one on disk. If they differ, then we should update the node announcement in the database.

**Comment by blico** [comment]
I would like to give this one a shot! (seems easy enough)

**Comment by halseth** [comment]
As noted in https://github.com/lightningnetwork/lnd/pull/2084#discussion_r321007023, we still unconditionally update our node announcement on startup (but we don't broadcast it). I updated the issue description to reflect this.

**Comment by halseth** [comment]
Discussion is whether updating and sending on startup is actually okay. Currently we don't send the update one it seems like.

**Comment by Roasbeef** [comment]
These days we have node announcement propagation issues, so this would be a stop backwards.
