### ISSUE TITLE
Can't build properly

### ISSUE THREAD

**Issue by Razer0123** [lightningnetwork/lnd#2747]
### Background

I've been trying to build LND following the installation process on GitHub, but I get this error

### Your environment

* version of `lnd`- latest
* which operating system (`uname -a` on *Nix) - 4.15.0-20-generic #21-Ubuntu
* version of `btcd`, `bitcoind`, or other backend - v0.17.1.0
* any other relevant environment details

### Steps to reproduce

Just building

### Expected behaviour

Successful build

### Actual behaviour

`Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.5.1-beta-835-ge0886ff1f56f4c5f92c7feaf941420d7a5751858" github.com/lightningnetwork/lnd
github.com/btcsuite/btcwallet/chain
# github.com/btcsuite/btcwallet/chain
../../btcsuite/btcwallet/chain/neutrino.go:384:19: s.CS.NewRescan undefined (type *neutrino.ChainService has no field or method NewRescan)
../../btcsuite/btcwallet/chain/neutrino.go:434:19: s.CS.NewRescan undefined (type *neutrino.ChainService has no field or method NewRescan)
Makefile:92: recipe for target 'build' failed
make: *** [build] Error 2`

**Comment by molxyz** [comment]
@Razer0123  Which Go version are you running?  You need at least go v1.11 or later (but don't use go 1.12).
And which lnd version are you trying to compile? To compile lnd v0.5.2-beta, try this: 
```
cd $GOPATH/src/github.com/lightningnetwork/lnd
git fetch --tags
git checkout v0.5.2-beta
make clean && make && make install
```

**Comment by Razer0123** [comment]
Yeah seems like I had already installed go from the ubuntu repo, so it was cousing issues

Thanks
