### ISSUE TITLE
Synchronization not progressing

### ISSUE THREAD

**Issue by Jonbros01** [lightningnetwork/lnd#2748]
On iOS my phone syncing doesn't progress stuck at block 1483968 ...

This issue occur with last few alpha releases including last one 0.0.18

![IMG_0217](https://user-images.githubusercontent.com/31890680/54055723-e816aa00-41bb-11e9-9626-8e4813a86441.PNG)

![UNADJUSTEDNONRAW_thumb_7de](https://user-images.githubusercontent.com/31890680/54055771-08466900-41bc-11e9-87b8-65d6b7727f05.jpg)

**Comment by Roasbeef** [comment]
Wrong repo.
