### ISSUE TITLE
De-duplicate announcements in the AuthenticatedGossiper

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#275]
# Issues 

Atm, when we receive valid announcements either from the network, or a local subsystem within the [`AuthenticatedGossiper`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L99) we immediately add them to the next announcement batch. This can cause excessive spamming as if user triggers a command that triggers a new `ChannelUpdate` to be sent, then each instance of execution of said command will result in an additional message being added to the channel batch. 

To address this issue, the [`announcementBatch`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L321) slice within the main `networkHandler` goroutine should be properly de-duplicated. Additionally, while were at it, we should also make the [`trickleDelay`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L333) configurable and exposed as a command line option.  

# Steps to Completion 

- [ ] Create a new isolated struct private struct called something along the lines of `deDupedAnnouncements`. This struct will encapsulate the logic needed to properly de-duplicate any announcements which have been added to this batch. This struct should take the place of the `[]lnwire.Message` used to track the current announcement batch. 

- [ ] The `deDupedAnnouncements` struct should have the following methods:
    * `Reset()` which resets all storage and indexes used internally 
    * `AddMsg(lnwire.Message)` which adds a new `lnwire.Message` to the current batch
    * `Batch()` which returns the set of de-duplicated announcements to be sent out during the next announcement epoch. 

- [ ] We have three main messages types which need to be de-duplicated, each with a unique attribute that can be used to de-duplicate them:
    * `ChannelAnnouncement`: uniquely identified by `ShortChannelID` field. 
    * `ChannelUpdate`: uniquely identified by the (`ShortChannelID`, `Flags`) tuple. 
    * `NodeAnnouncement`: uniquely identified by the `NodeID` field. 

    Based on each of the unique fields for a received announcement, de-duplication should be performed within the `AddMsg` method, with newer announcements replacing older announcements in the pending batch. 

- [ ] As a bonus, the  [`trickleDelay`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L333) used within the `AuthenticatedGossiper` should be mode configurable. Currently it's set to `300ms` in order to allows us to ensure our tests are speedy. A `time.Duration` representing the length of an announcement epoch should be added to [`routing.Config`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L49) struct.

    This value should be exposed in the config for lnd itself, and used to initialize the struct accordingly. **NOTE**: when [creating nodes within the integration tests](https://github.com/lightningnetwork/lnd/blob/master/networktest.go#L119) this value should be set to something on the order of 300ms such that the tests continue to operate as normal.

**Comment by flaurida** [comment]
I'm going to take a stab at this :)

**Comment by halseth** [comment]
Here's a bit of background to batch announcements: https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#rebroadcasting

**Comment by flaurida** [comment]
thanks!

**Comment by Roasbeef** [comment]
Closed by #322
