### ISSUE TITLE
newaddress hangs when using simnet and docker

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#2751]
### Background

running: `lncli --network=simnet newaddress np2wkh` doesn't return a new address when following the current docker instructions https://github.com/lightningnetwork/lnd/tree/master/docker.  However, other networks such as `testnet` work fine.

### Your environment

docker

### Steps to reproduce

Follow the current docker instructions here: https://github.com/lightningnetwork/lnd/tree/master/docker

### Expected behavior

a new simnet address should be returned

### Actual behavior

`lncli` hangs and doesn't return any output.

**Comment by ccdle12** [comment]
should be fixed by: https://github.com/btcsuite/btcwallet/pull/602

This bug means that an address cannot be generated by a wallet since the wallet is not synced to the network. In order for the wallet to be synced to the network a block must be mined... in order to generate a block on simnet we need an address.

**Comment by yancyribbens** [comment]
@ccdle12 thanks!  does lnd fully integrate btc wallet?  I'm not sure where the btcwallet `wallet.go` is in lnd.

**Comment by ccdle12** [comment]
@yancyribbens No worries!, yes LND uses btcwallet implicitly.

In `lnwallet/btcwallet/btcwallet.go` on `line 19 (at time of writing)` btcwallet is imported as `base`.

In the `BTCWallet struct` on `line 47`, the field `wallet` uses `*base.Wallet` which is the `Wallet` in `btcwallet/wallet/wallet.go`.

**Comment by yancyribbens** [comment]
confirmed btcsuite/btcwallet#602 fixes the docker issue therefore closing
