### ISSUE TITLE
Getting this error { error: 'json: cannot unmarshal number into Go value of type map[string]json.RawMessage',   code: 3 }

### ISSUE THREAD

**Issue by infiniteannant** [lightningnetwork/lnd#2753]
### Background
I am using bitcoind regetest network. When I am setting up lightning network. I created two nodes in the network. when I am connecting two nodes(peers) using following code-
var fs = require('fs');
var request = require('request');
var macaroon = fs.readFileSync('/home/annant/lnd_A/data/chain/bitcoin/regtest/admin.macaroon').toString('hex');
var requestBody = { 
    addr: "03abd76b87c7638352c8b6d84ee765ffab6a9f275409624c365e36e92fe8d059e8@localhost:9734",
    perm: true,
  };
 var options = {
    url: 'https://localhost:8080/v1/peers',
    // Work-around for self-signed certificates.
    rejectUnauthorized: false,
    json: true, 
    headers: {
      'Grpc-Metadata-macaroon': macaroon,
    },
    form: JSON.stringify(requestBody),
  };
 request.post(options, function(error, response, body) {
    console.log(body);
  });

I am getting error=>
{ error: 'json: cannot unmarshal number into Go value of type map[string]json.RawMessage',
  code: 3 }

**Comment by wpaulino** [comment]
The address cannot be provided as a string, but rather as an object that contains a `pubkey` and a `host`. This is indicated in our [documentation](https://api.lightning.community/rest/index.html?javascript#v1-peers). Give this a try:

```
var requestBody = {
    addr: { 
        pubkey: "03abd76b87c7638352c8b6d84ee765ffab6a9f275409624c365e36e92fe8d059e8",
        host: "localhost:9734"
    },
    perm: true,
};
```

**Comment by infiniteannant** [comment]
Thanks..Its working..I will join slack group.
