### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#2756]
After building and then using `sudo make install` lnd and lncli are not avaiable as commands and I need to do `./lnd-directory/.lnd-debug` to run lnd.  I am on Unbuntu 18.04, trying to build the latest version of lnd.

**Comment by Roasbeef** [comment]
Check your $PATH.

**Comment by cfromknecht** [comment]
@benthecarman be sure to add `$GOPATH/bin` to your path. fwiw, you shouldn't need `sudo` to run make
