### ISSUE TITLE
Auto regeneration of SSL Cert

### ISSUE THREAD

**Issue by robclark56** [lightningnetwork/lnd#2758]
### Background
When lnd is first started, and no tls.cert is found, the necessary tls.key & tls.cert file are generated.
It is easy to regenerate them: stop lnd. Delete the files. Start lnd.

My Current Cert shows:
```Validity
            Not Before: Apr 24 04:53:56 2018 GMT
            Not After : Jun 19 04:53:56 2019 GMT
        Subject: O = lnd autogenerated cert, CN = RaspiBolt
```

### The Issue
After the SSL cert expires, various remote queries will fail.
### Your environment
* version of `lnd`: 0.5.2

### Steps to reproduce
None.

### Requested Behaviour
1) Would help if the certs were created with a much longer validity period from the start. 
2) And auto-regeneration needs to be implemented

### Question
Do macaroons also have expiry dates? If so ... same issue applies.

**Comment by akshit-modi** [comment]
With the PR https://github.com/lightningnetwork/lnd/pull/3011/files we have resolved the issue of TLS auto generation but what about certs with longer validity, is there a way we can increase the default tls cert expire timing of 14 months ? It would be really helpful if we can have a option to create a certificate for longer duration such like 3 years.

**Comment by guggero** [comment]
Check `lnd --help`:
```
--tlscertduration=                                                     The duration for which the auto-generated TLS certificate will be valid for (default: 10080h0m0s)
```
