### ISSUE TITLE
During lightning  network setup I got error{ error:   'json: cannot unmarshal object into Go value of type []uint8',  code: 3 }

### ISSUE THREAD

**Issue by infiniteannant** [lightningnetwork/lnd#2760]
### Background
I am using bitcoind network setup. and when I am sending payment from one peer to other peer. I am getting following error.
{ error:   'json: cannot unmarshal object into Go value of type []uint8',  code: 3 }

Describe your issue here.

the code is given below

var fs = require('fs');
var bytes = require('utf8-bytes');
var request = require('request');
var macaroon = fs.readFileSync('/home/sahana/lndNodes/nodeA/data/chain/bitcoin/regtest/admin.macaroon').toString('hex');
var requestBody = {
   dest: Buffer.from('033089343084efd952cf05043fccd1eeb6bab0e6fcf84a44a32e7e682f5ae7e18e','base64'),
   amt: "400",
   dest_string: Buffer.from('033089343084efd952cf05043fccd1eeb6bab0e6fcf84a44a32e7e682f5ae7e18e','hex'),
   final_cltv_delta: 3
 };
var options = {
   url: 'https://localhost:8080/v1/channels/transactions',
   // Work-around for self-signed certificates.
   rejectUnauthorized: false,
   json: true,
   headers: {
     'Grpc-Metadata-macaroon': macaroon,
   },
   form: JSON.stringify(requestBody),
 };
request.post(options, function(error, response, body) {
   console.log(body);
 });

**Comment by wpaulino** [comment]
You're missing the `payment_hash` field of the invoice in the `requestBody`. Also, if you provide the string versions, you don't need to provide the other one, e.g., if you set `dest_string`, `dest` isn't required (same applies for `payment_hash` and `payment_hash_string`.

Alternatively, you can just set the `payment_request`, which will populate the remaining items for you on the server side.
