### ISSUE TITLE
Expand PublishTransaction into a reliable transaction [re]broadcast sub-system

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#277]
# Issue 

Currently, we use the `PublishTransaction` method of the [`WalletController`](https://godoc.org/github.com/lightningnetwork/lnd/lnwallet#WalletController) interface to broadcast transactions. Relevant transactions that are to be broadcast include: funding transaction, commitment transactions during a force close, transactions sweeping time locked outputs within the `utxoNursery`, and justice transactions created by the `breachArbiter`. 

The current default implementation of the `WalletController`, `BtcWallet`, will attempt to re-broadcast any transactions which haven't been confirmed since the last restart. However, this only applies to transactions that directly spend inputs under its control. This means that any transactions that are channel related (other than the funding transaction) _won't_ be re-broadcast. This is an issue as there are many occasions where we depend on a reliable transaction confirmation in order to dispatch critical services such as sweeping an HTLC that has had its time lock expire. 

In order to address these issues, a new sub-system for reliable transaction broadcast should be created. 

# Steps to Completion 

- [x] Within the daemon, create a new sub-system for reliable transaction broadcast. Extra points for creativity for the name of this new sub-system. This sub-system would only be used within the daemon, meaning that the reservation workflow within `lnwallet` would still use the `PublishTransaction` method as normal. All other instances within the `lnd` package currently use `PublishTransaction` should be modified to instead interact with this sub-system . 

- [x] The sub-system itself should be exposed to the rest of `lnd` has a simple interface with a single method. It should accept identical arguments to that of `PublishTransaction`. The implementation of the sub-system should be split into two components: 
    1. A `TransactionBroadaster` an abstract interface that's able to submit transactions to the network somehow. 
    2. The concrete implementation of this new interface should take the `TransactionBroadcaster` as its parameter. This will allow us to have a single instance of the core logic, but be able to plug in different back end instances (neutrino, btcd, bitcoind, etc). 

    The core logic of this sub-system would be to implement reliable transaction broadcast. Before returning to the sender, it should write to disk, the transaction itself before broadcasting the transaction to the network using the `TransactionBroadcast`. This sub-system should also take an instance of the [`ChainNotifier`](https://godoc.org/github.com/lightningnetwork/lnd/chainntnfs#ChainNotifier) and use it to register for confirmation notifications. Once it has received a confirmation notification, it can delete the transaction entry from the database. 

- [x] The transaction broadcast method of this new sub-system should also have a concrete set of errors that are returned along with it. This set of errors will allow the other sub-systems within `lnd` to detect instances of duplicate transaction broadcast, double spends, etc. Atm we attempt to do this on a case-by-case basis by examining the string of the error returned. However, this currently only applied to errors returned by the `btcd` backend, and not `neutrino`, etc. Once these errors are in place, a sweep should be performed to find instances of such [error checks like this one](https://github.com/lightningnetwork/lnd/blob/master/peer.go#L1438), moving them over to checking the new concrete errors.

**Comment by halseth** [comment]
I'll take this one 👍

**Comment by Roasbeef** [comment]
In the current default context, this has been fixed by: https://github.com/Roasbeef/btcwallet/pull/16 and https://github.com/lightningnetwork/lnd/pull/594. We may revisit this later once additional pure wallet backends are added.
