### ISSUE TITLE
Channel still pending force closed

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#2778]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
lnd master now, few commits behind
Recent logs         "version": "0.5.2-99-beta commit=queue/v1.0.1-12-ga24eeb913534272e8fd934875058d662ebd72551",

* which operating system (`uname -a` on *Nix) 
x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend 
bitcoind
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
Channel closed completely sweeping everything! \o/

Tell us what should happen

### Actual behaviour

Tell us what happens instead

> {
>            "channel": {
>                "remote_node_pub": "02b30264b0e600b1e417bdc8c87622ba5004c55bea824bcb9f981680dd1a3987e7",
>                "channel_point": "8d5813a28e1088d669bcdebd49f324d0ee16a9d5b03c2c54506b51a7b63ea41b:1",
>                "capacity": "16000000",
>                "local_balance": "4097798",
>                "remote_balance": "0"
>            },
>            "closing_txid": "6ae410962fe621a8ca686419ab502bf2d709de49afe7f5d3d7ddff4d6694c067",
>            "limbo_balance": "11688180",
>            "maturity_height": 566307,
>            "blocks_til_maturity": -628,
>            "recovered_balance": "4097798",
>            "pending_htlcs": [
>                {
>                    "incoming": false,
>                    "amount": "3896060",
>                    "outpoint": "3bab49bce98d0c116a146c953fa4010d691373eeb42103539aa34d1b71cb1d30:0",
>                    "maturity_height": 564298,
>                    "blocks_til_maturity": -2637,
>                    "stage": 1
>                },
>                {
>                    "incoming": false,
>                    "amount": "3897060",
>                    "outpoint": "3e7c1a452770300d50ca8f8c4c7607d4418c0a8550a876890caaa51473e51254:0",
>                    "maturity_height": 564298,
>                    "blocks_til_maturity": -2637,
>                    "stage": 1
>                },
>                {
>                    "incoming": false,
>                    "amount": "3895060",
>                    "outpoint": "b4993e54e741c06c3f1cabf431dafefb1940c519beb16c143b27eb6a89d1bed4:0",
>                    "maturity_height": 564298,
>                    "blocks_til_maturity": -2637,
>                    "stage": 1
>                }
>            ]
>        },
> 

Logs for the channel: http://paste.ubuntu.com/p/D3ByM8VFHb/

Sweeping logs for the channel: http://paste.ubuntu.com/p/Qqsg4fMd8j/

All the force close outputs were swept, but lnd didn’t recognize that for whatever reason

**Comment by joostjager** [comment]
If looking up any of those htlcs on chain, it seems that they are spent with a preimage while your node is still trying to resolve with the second level timeout tx.

https://www.smartbit.com.au/tx/1cd145bd8503b891f8e651e521d14303c3ad9eb93eef0fd862455efb243566bb

Could it be that you force closed the channel and the other end of the channel pulled the htlc there after?

There is currently a gap in `lnd` where we don't properly detect this spend. And unfortunately also do not recover the preimage.

**Comment by juscamarena** [comment]
I didn't initiate a force close here, at least not intentionally.

**Comment by juscamarena** [comment]
"channel": {
                "remote_node_pub": "02b30264b0e600b1e417bdc8c87622ba5004c55bea824bcb9f981680dd1a3987e7",
                "channel_point": "2d5d16f1f79d46cbe9c8e1f82246b328c24e5500583adde462f31d63010fbec8:1",
                "capacity": "8000000",
                "local_balance": "7343325",
                "remote_balance": "0"
            },
            "closing_txid": "60d7aadcc4289d3458d8cb23349a4d41356af66944b3954c641f8b68fede357f",
            "limbo_balance": "494811",
            "maturity_height": 566341,
            "blocks_til_maturity": -1200,
            "recovered_balance": "7343325",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "494811",
                    "outpoint": "2927bd8ca283ca4c8722b1015e674cc23176c9abdf889b415302132ec8842913:0",
                    "maturity_height": 564332,
                    "blocks_til_maturity": -3209,
                    "stage": 1
                }
            ]
        }

Here's another one.

**Comment by Roasbeef** [comment]
Resolved by #2795 (and it successor).

**Comment by LNBIG-COM** [comment]
Hi!

I have same problem
LND is `0.6.0-beta commit=v0.6.0-beta-116-g985902be2779a5dcc7ac1d5b3d7eb7929608816d`

For example

LND-34:

    {
	"channel": {
	    "remote_node_pub": "03bc9337c7a28bb784d67742ebedd30a93bacdf7e4ca16436ef3798000242b2251",
	    "channel_point": "6cd7a9364d87dd145c2688d5f1997af0aafef151a05a959ec37491964c4f0e29:0",
	    "capacity": "16777215",
	    "local_balance": "16751786",
	    "remote_balance": "0"
	},
	"closing_txid": "e762434a9f9d123e459a6e35c05dcf3e68cc893895fb63193a807e8d02fcb13d",
	"limbo_balance": "817",
	"maturity_height": 570310,
	"blocks_til_maturity": -3762,
	"recovered_balance": "16751786",
	"pending_htlcs": [
	    {
		"incoming": false,
		"amount": "817",
		"outpoint": "63dd2e62ff9432cecc71cdb642aaa48ba1e8d64e1db9179ec741a63ca285027e:0",
		"maturity_height": 570311,
		"blocks_til_maturity": -3761,
		"stage": 2
	    }
	]
    },

LND-32:

    {
	"channel": {
	    "remote_node_pub": "03bc9337c7a28bb784d67742ebedd30a93bacdf7e4ca16436ef3798000242b2251",
	    "channel_point": "0fadc94bf3845cc723f3ec049c6f052787105fa3bceeafecab80b405197c0d3d:1",
	    "capacity": "16777215",
	    "local_balance": "16761926",
	    "remote_balance": "0"
	},
	"closing_txid": "8eeaddd2ba3f19f6c088c7a902dac71c64e5af8d2e64802f2639cf9989b3fd1d",
	"limbo_balance": "3268",
	"maturity_height": 570310,
	"blocks_til_maturity": -3762,
	"recovered_balance": "16761926",
	"pending_htlcs": [
	    {
		"incoming": false,
		"amount": "817",
		"outpoint": "d8f1b521a0be0ab85f9130019d477a60145a087f7d5d4bbe1217d0f4b1e73709:0",
		"maturity_height": 570311,
		"blocks_til_maturity": -3761,
		"stage": 2
	    },
	    {
		"incoming": false,
		"amount": "817",
		"outpoint": "2208bad382348c33d5b81d7bb26c6c86e1099f86e41664473a9f46ebd8474931:0",
		"maturity_height": 570311,
		"blocks_til_maturity": -3761,
		"stage": 2
	    },
	    {
		"incoming": false,
		"amount": "817",
		"outpoint": "e16350621e9a5490a78ca61ce385e57579c5bf39fb082525dba1b3b5268a6977:0",
		"maturity_height": 570311,
		"blocks_til_maturity": -3761,
		"stage": 2
	    },
	    {
		"incoming": false,
		"amount": "817",
		"outpoint": "a7b9339afa4409d418dc2bdb5ade2896fc666a368c17375d7f82c4dfd3a91cca:0",
		"maturity_height": 570311,
		"blocks_til_maturity": -3761,
		"stage": 2
	    }
	]
    },

Is it this bug again?

**Comment by LNBIG-COM** [comment]
Strange. I checked some closing transactions from above listed ones
Amounts (~16M) were swept successfully by my LNDs and even used.
So funds are not locked as i understand correctly. Right?

**Comment by Roasbeef** [comment]
Same response as your other issue: the internal sweeper doesn't handle those outputs atm, as we'd need to pay more in fees than we'd gain by actually sweeping the output.
