### ISSUE TITLE
Peer connections flapping

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#2784]
### Background

Updated to 0.5.2-99-beta commit=queue/v1.0.1-23-g36cc1da8ea0eec6be4559c673bc07bd0ae9be66a

And started back up.  It can't seem to sync, and keeps disconnecting 10-20 peers every few minutes while 'applying gossip update'

### Your environment

* version of `lnd` : 0.5.2-99-beta commit=queue/v1.0.1-23-g36cc1da8ea0eec6be4559c673bc07bd0ae9be66a

* which operating system (`uname -a` on *Nix) Rasbian
* version of `btcd`, `bitcoind`, or other backend

### Steps to reproduce

Start node

### Expected behaviour
Runs normally

### Actual behaviour
"Applying update" stalls for 10+ seconds... then spam of peer connections failing.  
All of these peers were working find before the upgrade.  There seems to be an endless loop of trying to get the gossip... causes peers to disconnect... when reconnect tries to get gossip... which causes peers to disconnect.
It's like the gossiper is causing peers to time out... which is causing the gossiper to start over when the channel comes up and rinse/repeat.

2019-03-15 23:27:41.020 [INF] DISC: gossipSyncer(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e): applying new update horizon: start=2019-03-15 22:26:59 +0700 +07, end=2155-04-22 04:55:14 +0700 +07, backlog_size=21999
2019-03-15 23:27:55.228 [INF] DISC: Broadcasting batch of 905 new announcements
2019-03-15 23:27:55.336 [INF] PEER: Disconnecting 213.174.156.76:9735, reason: unable to write message: write tcp 10.34.0.85:43314->213.174.156.76:9735: write: connection reset by peer
2019-03-15 23:27:55.348 [INF] PEER: Disconnecting 46.229.165.138:9735, reason: unable to write message: write tcp 10.34.0.85:55744->46.229.165.138:9735: write: connection reset by peer
2019-03-15 23:27:55.360 [INF] PEER: Disconnecting 46.229.165.133:9735, reason: unable to write message: write tcp 10.34.0.85:39280->46.229.165.133:9735: write: connection reset by peer
2019-03-15 23:27:55.430 [INF] PEER: Disconnecting 46.229.165.154:9735, reason: unable to write message: write tcp 10.34.0.85:49280->46.229.165.154:9735: write: connection reset by peer

**Comment by ZapUser77** [comment]
I closed the 5 channels that were flapping the most, and the problems disappeared.

**Comment by hpbock** [comment]
The IP addresses you posted seem to belong to LNBig.com.

Do you observe this problem constantly? Or is it intermittent for some hours during the day?
Can you observe high load on your harddisk like in #2809?

**Comment by ZapUser77** [comment]
It started just after upgrading, and persisted for 3 days straight, non-stop.  (I wanted to see if the "deprioritize gossip" helped with the out of memory problem.)
It wasn't the same channels each time, nor was it just the 5 posted.  But there were 5 channels that were flapping more than the others, and once I closed them, the rest stopped.

Wild guess: while applying new update horizon, my node stopped sending keep-alives, which caused the distant end to disconnect, and when they reconnected it flooded my node with updates which started the cycle all over again.

I wasn't checking HD I/O, but CPU was in the 75-100% range the entire time.

**Comment by Roasbeef** [comment]
@ZapUser77 you can give this branch a spin https://github.com/lightningnetwork/lnd/compare/master...Roasbeef:net-stability?expand=1

**Comment by Roasbeef** [comment]
Needs one more change, but these combined should address most of the current issues.

**Comment by ZapUser77** [comment]
@Roasbeef I received an email that you posted here, but don't see the replies for some reason.
The link you posted is "to open a new pull request".  
I don't know the syntax to pull your specific commit to my device.  If you can provide the exact pull command syntax, I can do that right away.

**Comment by wpaulino** [comment]
He wanted you to try out an experimental branch that greatly improves the current gossip issues, but there are some database changes that will change and we'd rather wait until they're done to have people actively test them.

**Comment by ZapUser77** [comment]
Ok thanks.  Ya, my node is running on mainnet with real funds... so gotta say safe.  :)

**Comment by johnmarc** [comment]
I'm having a similar problem, with many of my peers unable to maintain open connections some reconnect some don't. The problem does seem to be worse at different times of day too, with overnight edt being much more stable (not really sure if that's coincidence or not.). 

I see the same disconnect messages that @ZapUser77  was seeing and I'll see the number of peers I have open drop below the number of channels and many of my channels become inactive.

Restarting lnd generally reconnects to all channels for a short time but then they begin to fall off again.

**Comment by hpbock** [comment]
@Roasbeef @cfromknecht my node is running e3c65e1a4935dbf9ba91cb326ea78b5161748dad which includes #2819 since 28th of march and the problem has not yet vanished.
![image](https://user-images.githubusercontent.com/15837933/55280830-579b3780-532b-11e9-9830-e92b81cb6ee5.png)
I observe that at the same time the number of connected peers are reduced dramaticaly, my harddisk i/o is used by 100% writing data onto lnds partition, see graphs beneath. The CPU itself is mostly idle - only one is in state iowait during the times the disk io is maxed.  
![image](https://user-images.githubusercontent.com/15837933/55280844-7ac5e700-532b-11e9-8c0a-0b446dab6054.png)
http://192.168.10.67/munin/localdomain/localhost.localdomain/diskstats_utilization-week.png
![image](https://user-images.githubusercontent.com/15837933/55280852-8dd8b700-532b-11e9-83ea-9e03807b0767.png)
![image](https://user-images.githubusercontent.com/15837933/55280856-9b8e3c80-532b-11e9-949b-72c65000c4b3.png)
What does LND write during that times onto the harddisk that is never read again?
