### ISSUE TITLE
Payment stuck in "payment is in transition"

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#2786]
### Background

Some payment was stuck a while ago. Some of my stuck payments date back to March 3rd, which is a lot

### Your environment

* `lnd version 0.5.1-beta commit=v0.5.1-beta`
* `Linux 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* `bitcoin-0.17.0`

### Steps to reproduce

* Send payment. Payment is reported as in transition
* After a while I am checking old invoices doing this:
`time lncli queryroutes --dest=03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e --num_max_routes=1 --amt=200000 | lncli sendtoroute  --payment_hash=648477ef67df06db42c398f3a756c1b88916e91d0d2444a4658f1ea1f3b27b97  -`
where destination and payment hash are real values from decoded stuck invoice
* Still reports `"payment_error": "payment is in transition"`

### Expected behaviour

* Payment to be timeouted (or some kind of other permanent error) so I can safely assume funds from the payment are back

### Actual behaviour

Indefinitely `"payment_error": "payment is in transition"`

**Comment by wpaulino** [comment]
This is expected if you never receive a settle/cancel back for that preimage. What's the timeout on the HTLC? Depending on how many hops it took, it can take quite a while as the default is still 144 blocks per hop. #2759 will address that portion of it.

**Comment by Roasbeef** [comment]
We don't allow re-using a payment hash that has an in-flight HTLC. You'll need to wait for it to timeout, but also payment hash re-use isn't recommenced.

**Comment by Overtorment** [comment]
@Roasbeef how do I tell whats the status of the payment I sent, given I have bolt11 invoice string?

**Comment by Overtorment** [comment]
@wpaulino  @Roasbeef what if Im trying this trick with `queryroutes | sendtoroute` on a timeouted payment, and it replies `payment is in transition` ? is it safe to assume it will never be paid, and no funds are spent?

**Comment by halseth** [comment]
`payment is in transition` means that the HTLC is active on the network, and can be settled anytime.
