### ISSUE TITLE
LND tries to connect to itself?

### ISSUE THREAD

**Issue by drunkenclam** [lightningnetwork/lnd#2787]
My LND seems to try to connect to itself as a peer:

```
Mar 16 14:00:24 NeonBlack lnd[10137]: 2019-03-16 14:00:24.675 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38482: EOF
Mar 16 14:00:42 NeonBlack lnd[10137]: 2019-03-16 14:00:42.698 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38542: EOF
Mar 16 14:01:00 NeonBlack lnd[10137]: 2019-03-16 14:01:00.685 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38602: EOF
Mar 16 14:01:17 NeonBlack lnd[10137]: 2019-03-16 14:01:17.138 [INF] DISC: Broadcasting batch of 100 new announcements
Mar 16 14:01:18 NeonBlack lnd[10137]: 2019-03-16 14:01:18.646 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38664: EOF
Mar 16 14:01:36 NeonBlack lnd[10137]: 2019-03-16 14:01:36.663 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38724: EOF
Mar 16 14:01:54 NeonBlack lnd[10137]: 2019-03-16 14:01:54.735 [ERR] CMGR: Can't accept connection: unable to accept connection from x:38784: EOF
```

The IP in the log is my current public IP.

I played around with tor a few days ago, but it's now deactivated again (maybe that could be a source for the connection issues?)

I'm on current LND master on a raspi with bitcoind backend

**Comment by molxyz** [comment]
@drunkenclam  LND doesn't connect to itself though? We had this error before which I reported it here: 
https://github.com/lightningnetwork/lnd/issues/193
which was fixed in https://github.com/lightningnetwork/lnd/commit/d188d97fce5a4241ae2b0631be2c9397dd3ecfd9
Do you have another node on the same IP?

**Comment by drunkenclam** [comment]
I didn't try to connect it to itself, and it isn't listed in listpeers.

It's just the log that is full of those entries.

I don't have another node in my local network.

**Comment by Roasbeef** [comment]
Realized this may have actually been an issue in the addresses the DNS seed was serving. This should now be fixed on its end.
