### ISSUE TITLE
package git.schwanenlied.me/yawning/bsaes.git/ct32: cannot download

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#2788]
Can't compile a clean installation
uname -a
Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux

go version
go version go1.11.5 linux/arm

go get -d github.com/lightningnetwork/lnd

package git.schwanenlied.me/yawning/bsaes.git/ct32: cannot download, git://git.schwanenlied.me/yawning/bsaes uses insecure protocol

**Comment by enorrmann** [comment]
seems it was a temporary conectivity issue (from schwanenlied.me's side) .. tried again in the morning and it compiles fine

**Comment by jmlon** [comment]
Trying a new installation in WSL2:

```
go version go1.13 linux/amd64
go get -d github.com/lightningnetwork/lnd
package git.schwanenlied.me/yawning/bsaes.git/ct32: cannot download, git://git.schwanenlied.me/yawning/bsaes uses insecure protocol
package git.schwanenlied.me/yawning/bsaes.git/ct64: cannot download, git://git.schwanenlied.me/yawning/bsaes uses insecure protocol
```

**Comment by guggero** [comment]
> `go get -d github.com/lightningnetwork/lnd`

That command doesn't respect the `replace` directives in `go.mod` and therefore tries to download the package from the wrong source. Please install `lnd` from source as described here: https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-lnd-from-source

**Comment by RajGoodF** [comment]
@guggero Hi while following your above suggestion I am getting the following error:
make: *** [Makefile:145: install] Error 2

**Comment by guggero** [comment]
What's the actual error? This is just the summary message at the end. You're probably missing a tool.

**Comment by RajGoodF** [comment]
@guggero sry, got the error resolved, my mistake haven't updated go version.
