### ISSUE TITLE
Does the unlock wallet password encrypt both on-chain and channel data?

### ISSUE THREAD

**Issue by Perlover** [lightningnetwork/lnd#2789]
Hello,

Sorry may be for strange question but does the LND encrypt only on-chain wallet or both wallet & channel data too? Other words will a hacker have access to channel keys (and funds of channels) and data if he will have access to channel db files? You used on-chain wallet from separately repository and i could think that you encrypt only on-chain wallet keys.

Thanks!

**Comment by wpaulino** [comment]
All secrets within the wallet are encrypted with your wallet password, but your channel data is not. Once #2313 is in, we'll have channel backups that will be encrypted with a key derived from your seed, but the channel data itself will remain unencrypted.

**Comment by Perlover** [comment]
:(

So if node works 99% of time with 90% funds to be locked in channels for example then all 90% of funds not safe. Other words if hacker will have access to backups or to only unencrypted HDD with channel data even if use wallet lock password he will take all 90% of funds? I had being understanding the meaning of wallet blocking completely differently.

I think you have to explicitly indicate somewhere in the documentation that unlocking by password of LND before launching almost does not give protection - the channel keys are unencrypted, which means the hacker can send the channel’s funds to your addresses when closing!

**Comment by wpaulino** [comment]
The channel keys are stored and encrypted within the wallet. The channel data just includes hints on how to derive those keys from the master key.

**Comment by Perlover** [comment]
Ohh. It's fine news. Thanks!
