### ISSUE TITLE
Unable to use gRPC from external and REST from same machine at the same time

### ISSUE THREAD

**Issue by JediWed** [lightningnetwork/lnd#2801]
### Background

When trying to use gRPC from outside and REST from the same machine at the same time REST calls does not work.

### Your environment

* lnd version 0.5.2-beta commit=v0.5.2-beta
* Linux rv1025 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Ubuntu 16.04.6 LTS
* Bitcoin Core Daemon version v0.17.1 (bitcoind)

### Steps to reproduce

1. Configure lnd.conf
```
restlisten=localhost:19925
rpclisten=0.0.0.0:10009
tlsextraip=a.b.c.d
externalip=a.b.c.d
```
2. Delete certificate
3. Restart lnd to create new certificate
4. Use external application/wallet to connect to lnd via gRPC with admin.macaroon and tls.cert
5. Use internal (running on the same machine like lnd) application/wallet to connect to lnd via REST

* external client can be a wallet like zap, pebble, shango, etc.
* for internal client RTL was used (Ride The Lightning)

### Expected behaviour

Step 4 and 5 should work.

### Actual behaviour

Step 5 does not work.

> All Subconns Are In Transientfailure, Latest Connection Error: Connection Error: Desc = "Transport: Authentication Handshake Failed: X509: Certificate Is Valid For 127.0.0.1, ::1, a.b.c.d, 172.17.0.1, xxx::xxxx:xxxx:xxxx:xxxx, Not 0.0.0.0"

RTL is running on the same machine like lnd and it's configured to access it via https://localhost:19925/v1

**Comment by wpaulino** [comment]
This has been fixed in master (#2247) and will be included in the next release. See https://github.com/lightningnetwork/lnd/issues/1567#issuecomment-471178535 for a temporary workaround.
