### ISSUE TITLE
Invoice not paid, but local balance deducted, remote balance stayed the same

### ISSUE THREAD

**Issue by Cees2daBees** [lightningnetwork/lnd#2807]
### Background

I tried to pay a tippin.me invoice for 6000 sats. The first time I attempted to pay it, nothing seemed to be happening and I hit ctrl-c to cancel. I tried paying again, and got the error "unable to find a path to destination". But it looks like the local balance of one of my channels was deducted the amount I was trying to pay. The remote balance of that channel didn't change, and the commit fee did not account for the change in local balance.

This is the invoice I attempted to pay:
lnbc1pwfrya6pp5tm7km2zfy0ukg9pfau4udughna2c2p96yz8334765f4rcd338x7qdph235hqurfdcs8xet9vfjk2uejyq58g6tswp5kutndv55jsaf3xqmrv2gcqzysxqyz5vqw0hu7qtx0xvt5uzxvkdzrfj5w3p7zxyds64fcfg5c64q6mhfc5p8wks00jdhkvl80znzfe72q84vtmpjyrsve4xan7s077l9jet4p4gpjm7fe0

### Your environment

lnd version 0.5.2-beta commit=v0.5.2-beta
Linux RaspiBolt 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Bitcoin Core Daemon version v0.17.1

**Comment by Roasbeef** [comment]
The local balance will be deducted due to the HTLC. There's likely still a pending HTLC on the commitment.
