### ISSUE TITLE
Add new TLS cipher suites

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#281]
After issue #276 is completed, there's an additional bit of improvement allowed by Go 1.8 that can be done. The new standard library has additional cipher suites that can be added to the `CipherSuites` slice in the TLS configuration in `lnd.go`. Only those suites that follow the guidelines listed in the comments should be added. Specifically, this means that they shouldn't use outdated primitives like SHA-1, 3DES, or AES in ECB mode. The new suites to be added specifically include some new cipher suites that use AES in CBC mode.

**Comment by Roasbeef** [comment]
This was closed by #314.
