### ISSUE TITLE
Can't open channels: 'peer is not online'

### ISSUE THREAD

**Issue by erickuhn19** [lightningnetwork/lnd#2817]
I can't open up a channel with anyone. I've tried from the Zap Desktop GUI and also from the command line. I'm mainly getting that the peer is offline even though I know they are indeed online bc I'm talking to them and making sure their node is connected. 

I asked the same node to open a channel with me and that was successful. 

I'm using:

$ lncli openchannel 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f 500000

Getting the response: 
2019-03-21 16:12:28.548 [ERR] RPCS: unable to open channel to NodeKey(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): peer 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f is not online

### Your environment

"version": "0.5.2-beta commit=v0.5.2-beta-rc7",
macOS
bitcoind: v0.17.1

**Comment by Roasbeef** [comment]
The remote party isn't connected. You need to connect to them before you can open a channel. Ensure they're connected before you open the channel.

**Comment by erickuhn19** [comment]
Makes sense, used $lncli connect

**Comment by priyanshu-techal** [comment]
So, I ran $lncli connect public_node_uri
Now, shall I wait for the node to accept my request?

**Comment by mlvl36667** [comment]
> So, I ran $lncli connect public_node_uri Now, shall I wait for the node to accept my request?

lncli connect [address]@[ip]:[port]
