### ISSUE TITLE
make check error: unable to create pay reqs

### ISSUE THREAD

**Issue by DariusParvin** [lightningnetwork/lnd#2818]
### Background

I'm getting an error when running make check. Full output is here:
https://pastebin.com/BaLHHC2C

--- FAIL: TestLightningNetworkDaemon (402.57s)
    lnd_test.go:13497: Running 51 integration tests
    --- PASS: TestLightningNetworkDaemon/sweep_coins (6.21s)
    --- PASS: TestLightningNetworkDaemon/onchain_fund_recovery (31.86s)
    --- PASS: TestLightningNetworkDaemon/basic_funding_flow (1.77s)
    --- PASS: TestLightningNetworkDaemon/unconfirmed_channel_funding (7.36s)
    --- PASS: TestLightningNetworkDaemon/update_channel_policy (13.02s)
    --- PASS: TestLightningNetworkDaemon/open_channel_reorg_test (4.61s)
    --- PASS: TestLightningNetworkDaemon/disconnecting_target_peer (5.79s)
    --- PASS: TestLightningNetworkDaemon/graph_topology_notifications (9.48s)
    --- PASS: TestLightningNetworkDaemon/funding_flow_persistence (20.16s)
    --- PASS: TestLightningNetworkDaemon/channel_force_closure (45.75s)
    --- PASS: TestLightningNetworkDaemon/channel_balance (1.66s)
    --- PASS: TestLightningNetworkDaemon/channel_unsettled_balance (10.94s)
    --- PASS: TestLightningNetworkDaemon/single_hop_invoice (3.59s)
    --- PASS: TestLightningNetworkDaemon/sphinx_replay_persistence (17.31s)
    --- PASS: TestLightningNetworkDaemon/list_outgoing_payments (2.53s)
    --- PASS: TestLightningNetworkDaemon/max_pending_channel (9.58s)
    --- PASS: TestLightningNetworkDaemon/multi-hop_payments (20.77s)
    --- PASS: TestLightningNetworkDaemon/single-hop_send_to_route (2.67s)
    --- PASS: TestLightningNetworkDaemon/multi-hop_send_to_route (9.77s)
    --- PASS: TestLightningNetworkDaemon/send_to_route_error_propagation (16.33s)
    --- PASS: TestLightningNetworkDaemon/unannounced_channels (1.83s)
    --- PASS: TestLightningNetworkDaemon/private_channels (23.71s)
    --- PASS: TestLightningNetworkDaemon/invoice_routing_hints (29.04s)
    --- PASS: TestLightningNetworkDaemon/multi-hop_payments_over_private_channels (20.42s)
    --- PASS: TestLightningNetworkDaemon/multiple_channel_creation_and_update_subscription (5.95s)
    --- PASS: TestLightningNetworkDaemon/invoice_update_subscription (3.19s)
    --- PASS: TestLightningNetworkDaemon/multi-hop_htlc_error_propagation (21.81s)
    --- PASS: TestLightningNetworkDaemon/node_announcement (7.08s)
    --- PASS: TestLightningNetworkDaemon/node_sign_verify (7.43s)
    --- FAIL: TestLightningNetworkDaemon/async_payments_benchmark (31.40s)
        lnd_test.go:76: Failed: (async payments benchmark): exited with error: 
            *errors.errorString unable to create pay reqs: unable to add invoice: rpc error: code = DeadlineExceeded desc = context deadline exceeded
            /Users/dariuscognac/go/src/github.com/lightningnetwork/lnd/lnd_test.go:8812 (0x18be647)
            	testAsyncPayments: t.Fatalf("unable to create pay reqs: %v", err)
            /Users/dariuscognac/go/src/github.com/lightningnetwork/lnd/lnd_test.go:101 (0x188c466)
            	(*harnessTest).RunTestCase: testCase.test(net, h)
            /Users/dariuscognac/go/src/github.com/lightningnetwork/lnd/lnd_test.go:13518 (0x18ef645)
            	TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase, lndHarness)
            /usr/local/Cellar/go/1.12.1/libexec/src/testing/testing.go:865 (0x10f9a00)
            	tRunner: fn(t)
            /usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337 (0x105e7b1)
            	goexit: BYTE	$0x90	// NOP
FAIL
exit status 1
FAIL	github.com/lightningnetwork/lnd	402.606s
make: *** [itest-only] Error 1

### Your environment

* version of `lnd`
lnd version 0.5.2-99-beta commit=

* which operating system (`uname -a` on *Nix)
Darwin Dariuss-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.1
btcd version 0.12.0-beta

* any other relevant environment details
Not sure if this is relevant but I had previously installed bitcoin qt and had downloaded the blockchain. Then after attempting to install lnd I installed bitcoind

### Steps to reproduce

See background

### Expected behaviour

Pass

### Actual behaviour

Fail

**Comment by Roasbeef** [comment]
If you're running on mac, with go 1.12, then unfortunately,  [write I/O is now 10-30x slower :(](https://github.com/golang/go/issues/30497)

As a result, the integration tests no longer pass reliably, as we focus on Linux for the Travis runs.

**Comment by DariusParvin** [comment]
ah damn okay. Thanks a lot for your quick reply :)
