### ISSUE TITLE
Macaroons: encrypt DB entries with key protected by same PW as wallet

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#282]
Currently, macaroon database entries (particularly root keys) are written in plaintext. This is OK for alpha, but unacceptable for mainnet operation with real money. The following steps need to be taken:

- [ ] Add code (similar to waddrmgr) to lock/unlock macaroon database, storing a key encrypted with a password, and allowing to change the password
- [ ] Add code to upgrade the database by encrypting the existing root keys with the key
- [ ] Ensure that the macaroon service is instantiated with the same password as the wallet database
- [ ] When wallet password support is added to RPC (issue #226), ensure that's also wired to the macaroon service

**Comment by rajeshnair2k** [comment]
Is anybody working on this? Otherwise I would like to take a stab at this.

**Comment by halseth** [comment]
I think #367 should be merged first :)

**Comment by rajeshnair2k** [comment]
@halseth I will work on this one since you have merged #367

**Comment by Roasbeef** [comment]
Fixed by #718
