### ISSUE TITLE
Minimum HTLC from API works strange. Is it bug?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#2822]
When i create channels through API i use `min_htlc_msat` in `openChannelSync`
But when the channel was created i see this parameter at other side of channel

For example this channel was created from LND-41 with min_htlc_msat as 1:

https://1ml.com/channel/624841463022616576

But i see Min HTLC as 1 at other side _BITCOIN-KIT [lnd/mainnet]_
But the _BITCOIN-KIT [lnd/mainnet]_ has default min htlc as 1000 and there is lnd too. And vice versa

And same info i see in lnd-41 side:

    l getchaninfo 624841463022616576
    {
        "channel_id": "624841463022616576",
        "chan_point": "8a6c0bf3afa6f710ad2f6635774c9416cda5ff29c2530c8f288cf4eacc1f0edb:0",
        "last_update": 1553263266,
        "node1_pub": "0283ca0b7eca022bcf8f32aa418e5ff2bd375806faba40409cdc8e48c2b32ef725",
        "node2_pub": "03dab87ff8635982815c4567eb58af48f9944d11c56beb12b91e1049aaea06e187",
        "capacity": "4000000",
        "node1_policy": {
            "time_lock_delta": 144,
            "min_htlc": "1",
            "fee_base_msat": "1000",
            "fee_rate_milli_msat": "1",
            "disabled": false,
            "max_htlc_msat": "3960000000"
        },
        "node2_policy": {
            "time_lock_delta": 144,
            "min_htlc": "1000",
            "fee_base_msat": "500",
            "fee_rate_milli_msat": "500",
            "disabled": false,
            "max_htlc_msat": "3960000000"
        }
    }

Is it bug?

**Comment by Roasbeef** [comment]
No, it's how the protocol works. You convey the min amount that you'll accept. In order for you to accept a routed HTLC it comes across the other link.
