### ISSUE TITLE
Bitcoind docker image

### ISSUE THREAD

**Issue by yancyribbens** [lightningnetwork/lnd#2827]
It would be nice to have a docker image and compose setup for running `bitcoind` instead of `btcd` as the backend locally.

**Comment by yancyribbens** [comment]
related to: https://github.com/lightningnetwork/lnd/issues/2266

**Comment by mohamedawnallah** [comment]
Hey, @guggero @yancyribbens @awb99, I've just submitted PR #8354 for this issue. I'd love to receive any feedback from you. Thanks!
