### ISSUE TITLE
Add command-line tool to delegate macaroons

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#283]
Macaroons are useful because it's possible to delegate them without contacting the target service. `lncli` shows an example of how to do it with an expiration time. Either a new command can be added to `lncli` or a new command-line tool altogether can be written to delegate macaroons. Currently supported caveats include allowed/denied RPC permissions and expiration time but the tool will need to be maintained as support for new caveats is added.

**Comment by guggero** [comment]
This sounds like a fun task. I'll give it a go if that's ok.

**Comment by Kixunil** [comment]
I'm interested in this too. This could improve security of Btcpayserver + lnd setup, since btcpayserver needs invoice+readonly. Currently I have to use admin for it.
