### ISSUE TITLE
UNIMPLEMENTED: unknown service lnrpc.Lightning error when called listUnspent gRPC method

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#2834]
### Background

After call gRPC listUnspent method (https://api.lightning.community/#listunspent) I got error "UNIMPLEMENTED: unknown service lnrpc.Lightning"

### Your environment

* version of `lnd`: 0.5.2-beta commit=v0.5.2-beta
* which operating system: Linux lnd-tst-02 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `bitcoind`: Bitcoin Core RPC client version v0.16.0.0-g4b4d7eb255
* proto built for Java

### Steps to reproduce

Call blockingStub.listUnspent gRPC method generated for Java env.

### Expected behaviour

List unspent outputs

### Actual behaviour

UNIMPLEMENTED: unknown service lnrpc.Lightning error

**Comment by wpaulino** [comment]
The documentation is only tracking the master branch at the moment, not the v0.5.2 release.
