### ISSUE TITLE
[Feature request] Include amounts in subscribeTransactions for each dest address

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#2835]
### Background

When call subscribeTransaction gRPC command (https://api.lightning.community/#subscribetransactions) and receive any transaction there is list of dest addresses, but there is no amount for each address. Such amount would be very helpfull, as for now it is hard to detect if wallet received on-chain payment on expected address with expected amount.

### Your environment

* version of `lnd`: 0.5.2-beta commit=v0.5.2-beta
* which operating system: Linux lnd-tst-02 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `bitcoind`: Bitcoin Core RPC client version v0.16.0.0-g4b4d7eb255
* proto built for Java

### Steps to reproduce

Call subscribeTransaction gRPC command and receive some transaction.
 
### Expected behaviour

Transaction do not contain amount for each dest address.

### Actual behaviour

Transaction should contain amount for each dest address.

**Comment by wpaulino** [comment]
The documentation is only tracking the master branch at the moment, not the v0.5.2 release.

**Comment by asocjal** [comment]
But documentation also do not contain amounts for each dest address

**Comment by Roasbeef** [comment]
You can easily map the address to each output script in the response. All the necessary data is already returned.

**Comment by asocjal** [comment]
What response and output script do you mean? Do I need to call some additional method after receive new Transaction?

**Comment by asocjal** [comment]
According to gRPC specification, this is all the data returned (Transaction) after SubscribeTransaction:

`tx_hash | string | The transaction hash
amount | int64 | The transaction amount, denominated in satoshis
num_confirmations | int32 | The number of confirmations
block_hash | string | The hash of the block this transaction was included in
block_height | int32 | The height of the block this transaction was included in
time_stamp | int64 | Timestamp of this transaction
total_fees | int64 | Fees paid for this transaction
dest_addresses | array string | Addresses that received funds for this transaction
`
Where is output script that I could mach with address?

**Comment by halseth** [comment]
I think you need to query your full node for the amounts. Agreed that this would be useful, and it would be quite simple to add.

Reopening as feature request.
