### ISSUE TITLE
Channel balance should be in millisatoshis

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#2836]
### Background

Channel in gRpc (https://api.lightning.community/#channel) contains balance but in satoshis instead of millisatoshis. 

### Your environment

* version of `lnd`: 0.5.2-beta commit=v0.5.2-beta
* which operating system: Linux lnd-tst-02 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `bitcoind`: Bitcoin Core RPC client version v0.16.0.0-g4b4d7eb255
* proto built for Java

### Steps to reproduce

Call ListChannels gRpc method.  

### Expected behaviour

Local and remote balance should be msat values

### Actual behaviour

Local and remote balance are in satoshis

**Comment by wpaulino** [comment]
The documentation is only tracking the master branch at the moment, not the v0.5.2 release.

**Comment by asocjal** [comment]
But documentation also do not contains millisatoshis for channel amounts

**Comment by wpaulino** [comment]
That's how it currently is at the RPC level, so not an issue with the documentation.
