### ISSUE TITLE
Add macaroon-specific tests

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#284]
The macaroon code needs some tests! Some ideas for things to test include:

- [ ] Authenticating to one macaroon service with the macaroon of another service, with no macaroon, or with an invalid macaroon
- [ ] Authenticating using permissions that are denied or allowed in various ways
- [ ] Authenticating with macaroons containing expired and non-expired `TimeBeforeCaveat`
- [ ] Doing all of the above in both `lnd` integration tests (with and without `lncli`, thanks @mrwhythat) and package-level unit tests

**Comment by yashbhutwala** [comment]
Is anyone else working on this issue? If not, I can take a stab at it.

**Comment by merehap** [comment]
I'll take up the unit testing portion of this under the assumption that @yashbhutwala and @mrwhythat are no longer looking at this.
