### ISSUE TITLE
Macaroons: add better request replay protection

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#285]
The `lncli` command-line utility currently adds a 60-second expiration by default to help mitigate potential replay attacks. We may be able to do better, at least for native protobuf-based gRPC. My current best idea is to add a caveat type for a `RequestHash` and add that caveat, along with the existing expiration, with every call from `lncli`. This should work as long as the `RequestHash` doesn't include metadata, but won't work for the REST gateway as it constructs its own protobuf-formatted request from the JSON-formatted request.

**Comment by guggero** [comment]
I'll give this one a try.
