### ISSUE TITLE
How to get amounts for addresses in Transaction?

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#2853]
Some time ago, I opened such issue:

https://github.com/lightningnetwork/lnd/issues/2835

Roasbeef closed it with comment:

"You can easily map the address to each output script in the response. All the necessary data is already returned."

Maybe I'm an idiot, but I don't see output script in Transaction, that is returned as a result of SubscribeTransactions gRPC command. How can I get output script to map with addresses? Should I call some additional command?

**Comment by Roasbeef** [comment]
You can look at the outputs of the transaction. From there, you can map the addresses. The issue tracker isn't the place for questions like this, they're better suited for IRC or our Slack channel.
