### ISSUE TITLE
Can you restrict inbound channel to a minumum amount of sats?

### ISSUE THREAD

**Issue by merclyn** [lightningnetwork/lnd#2854]
### Background

I am looking in the sample config file for a parameter that will restrict inbound channels to be minimum amount of satoshis. I see this feature out in the wild on other nodes, but not sure if its in lnd yet.  I would like to stop people from opening up smaller channels to a node.

### Your environment
lnd 0.5.2 on linux (centos) - x86_64 GNU/Linux  with bitcoin-core 17.0.1 (bitcoind)

If this is a supported feature, I cannot find it documented anywhere.

**Comment by wpaulino** [comment]
Yes, with the `--minchansize` flag. See `lnd -h`.

**Comment by merclyn** [comment]
OK, thanks.  sorry for the false report.
