### ISSUE TITLE
cannot create wallet

### ISSUE THREAD

**Issue by awb99** [lightningnetwork/lnd#2856]
I started with LND docker-compose images, and modified them to use bitcoind. Now the chain has
synched and I want to create a wallet. I use bitcoin on mainnet.

```
lncli --rpcserver localhost:10001  \
      --macaroonpath /root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon \
      --network mainnet --chain bitcoin \
      create
```

This command fails when I want to create a new seed:
```
Generating fresh cipher seed...
[lncli] unable to generate seed: rpc error: code = Unimplemented desc = unknown service lnrpc.WalletUnlocker
```
However, I used the following site to generate the mnemonic seed https://iancoleman.io/bip39/
and then entered them, and then it worked!

However, when I check the Bitcoin adresses generated and compare them with 
the ones in https://iancoleman.io/bip39/  then they are completely different.

This is the lnd startup I used:
```
exec lnd \
    --debuglevel=trace \
    --noseedbackup \
    --logdir="/data" \
    "--bitcoin.active" \
    "--bitcoin.mainnet" \
    "--bitcoin.node=bitcoind" \
    "--bitcoind.rpchost=bitcoind:8332" \
    "--bitcoind.rpcuser=$RPCUSER" \
    "--bitcoind.rpcpass=$RPCPASS" \
    "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332" \
    "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333" \
    "--rpclisten=localhost:10001" \
    "--rpclisten=lnd:10001" \
    "--restlisten=0.0.0.0:8089" \
    "--listen=0.0.0.0:10011" \
    "$@"
```

**Comment by molxyz** [comment]
@awb99 Not sure if docker is up-to-date. It would be better if you install everything on a laptop and try them out on testnet by following this guide:  https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md .

Also, one important thing to remember: `LND does NOT use BIP39` ! After lnd is installed, at startup it will ask you if you want to `create` or `unlock`. Once you answer with `create` , enter your password, it will create a seed for your wallet.  

Please join LND slack for these support beginner questions.

**Comment by halseth** [comment]
Correct, `lnd` doesn't use BIP-39. 

The first mentioned error means that `lncli` cannot find `lnd`.
