### ISSUE TITLE
Add support for root key and possibly macaroon rotation

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#286]
When new macaroons are generated, it would be good to rotate the root keys used to generate them. This would include the following change:

- [ ] Update the `RootKeyStorage` implementation to generate a new root key and ID every time `RootKey()` is called.

It might also be a good feature to force macaroon rotation by causing generated macaroons to expire as follows:

- [ ] Update `genMacaroons()` in `lnd.go` to add a `TimeBeforeCaveat` with a sane default timeout and possibly a command-line option in `config.go` to modify that timeout if desired.
- [ ] Update the code in `lndMain()` in `lnd.go` that checks for macaroon file existence to also check for macaroon validity/expiration.

**Comment by mrwhythat** [comment]
@aakselrod I'd like to take this as well as other macaroon-related issues such as #285 , but I'd like to base it on #313 when/if it is reviewed/approved

**Comment by aakselrod** [comment]
@mrwhythat I'm hoping to review it this week. I'm in France for Breaking Bitcoin.

**Comment by guggero** [comment]
Replaced by #3715.
