### ISSUE TITLE
lnd is writing to disk almost all the time

### ISSUE THREAD

**Issue by Rav3nPL** [lightningnetwork/lnd#2860]
### Background

I`m running lnd on machine that run few other things (including lightning-c) and I observed system-wide slowdown when lnd is running (not only when fresh start).
htop shows that lnd process is almost constantly writing to disk in rate 1-3MB/s consuming around 20% of cpu.

### Your environment

* version of `lnd`
 version 0.5.2-99-beta commit=queue/v1.0.1-190-gabfbdf6aec3bbf63a1f13e5706ee983efbfb4674

* which operating system (`uname -a` on *Nix)
Ubuntu 18.04
 4.15.18-11-pve #1 SMP PVE 4.15.18-33 (Tue, 05 Feb 2019 07:36:16 +0100) x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core  version v0.18.99.0-e14cd04ab

**Comment by halseth** [comment]
This happens during initial graph sync, and progress to reduce this is tracked in #2847 #2740 etc.
