### ISSUE TITLE
LND does not propagate payment result to sender

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2865]
There is a BLW - LNBIG.com [lnd-12] (https://1ml.com/node/034ea80f8b148c750463546bd999bf7321a0e6dfc60aaf84bd0400a2e8d376c0d5) - OpenChannelN1 (https://1ml.com/node/033fd3e16bc450ea25cad365c8422f5534429c084a2f5e200caaf5fee6811418e5) route which was used to send a `3001 SAT` payment from BLW:

```
Your wallet
-->
Node ID: 034ea80f8b148c750463546bd999bf7321a0e6dfc60aaf84bd0400a2e8d376c0d5, Channel ID: 623703468500189184, Expiry: 60 blocks, Routing fees: 0,003500% of payment sum + baseline 0 msat
-->
Node ID: 033fd3e16bc450ea25cad365c8422f5534429c084a2f5e200caaf5fee6811418e5, Channel ID: 624099292704997376, Expiry: 144 blocks, Routing fees: 0,000100% of payment sum + baseline 1000 msat
-->
Payee node: 03902356d26efdc0812726c31a1a2e0d721f26063dd252ac89ded8280037e9ece8, Expiry: 20 blocks
```

This payment is expired by now (but `BLW - LNBIG` channel is intact since BLW does not close it in such cases).

When looking at `LNBIG - OpenChannelN1` state it's seen that payment is not there anymore:

```
{
            "active": true,
            "remote_pubkey": "033fd3e16bc450ea25cad365c8422f5534429c084a2f5e200caaf5fee6811418e5",
            "channel_point": "9370b594f26b765cfccce9f3fbe266efb11eb136734c70fc3f4613ddafab937d:0",
            "chan_id": "623703468500189184",
            "capacity": "3510000",
            "local_balance": "3497823",
            "remote_balance": "3001",
            "commit_fee": "9176",
            "commit_weight": "724",
            "fee_per_kw": "12674",
            "unsettled_balance": "0",
            "total_satoshis_sent": "3001",
            "total_satoshis_received": "0",
            "num_updates": "56",
            "pending_htlcs": [
            ],
            "csv_delay": 421,
            "private": false,
            "initiator": true
        },
```

Additionally, node operator claims that `fwdinghistory 1548922781 1554106781 0 1000` for above channel does not show anything yet `"remote_balance": "3001"` suggests a payment has been successfully routed.

When looking at `BLW - LNBIG` channel a payment is still there:

```
{
            "active": true,
            "remote_pubkey": "0340e6be7259217d821658db7d14f00ada2529836c48423fc322660efbec20bb96",
            "channel_point": "1d7107c9f4291cbc5cabfc5c6ea56dc069701e48a42e30c0eac89c9ae3c07dd0:1",
            "chan_id": "624874448403431425",
            "capacity": "2680000",
            "local_balance": "1754772",
            "remote_balance": "912613",
            "commit_fee": "12615",
            "commit_weight": "724",
            "fee_per_kw": "13278",
            "unsettled_balance": "3001",
            "total_satoshis_sent": "915614",
            "total_satoshis_received": "0",
            "num_updates": "16",
            "pending_htlcs": [
                {
                    "incoming": true,
                    "amount": "3001",
                    "hash_lock": "C1yRtexsxeTz0fdzYzGaNrJkQA/1BVuhCjiqPozxfK4=",
                    "expiration_height": 569419
                }
            ],
            "csv_delay": 2016,
            "private": true,
            "initiator": true
        }
```

Debug level is set to `TRACE` at LNBIG12, 

`grep -i UpdateFailHtlc ~/.lnd/mainnet-lnd-run.log |wc -l` 
result: 1, seems unrelated to BLW channel:

```
2019-03-27 22:40:03.682 [INF] HSWC: Received outside contract resolution, mapping to: (*htlcswitch.htlcPacket)(0xc012a37440)({
 incomingChanID: (lnwire.ShortChannelID) 0:0:0,
 outgoingChanID: (lnwire.ShortChannelID) 567255:1391:0,
 incomingHTLCID: (uint64) 0,
 incomingHtlcAmt: (lnwire.MilliSatoshi) 0 mSAT,
 outgoingHTLCID: (uint64) 30,
 sourceRef: (*channeldb.AddRef)(<nil>),
 destRef: (*channeldb.SettleFailRef)(<nil>),
 incomingAmount: (lnwire.MilliSatoshi) 0 mSAT,
 amount: (lnwire.MilliSatoshi) 0 mSAT,
 htlc: (*lnwire.UpdateFailHTLC)(0xc06c164c40)({
  ChanID: (lnwire.ChannelID) (len=32 cap=32) 0000000000000000000000000000000000000000000000000000000000000000,
  ID: (uint64) 0,
  Reason: (lnwire.OpaqueReason) <nil>
 }),
 obfuscator: (htlcswitch.ErrorEncrypter) <nil>,
 localFailure: (bool) false,
 hasSource: (bool) false,
 isResolution: (bool) true,
 circuit: (*htlcswitch.PaymentCircuit)(<nil>),
 incomingTimeout: (uint32) 0,
 outgoingTimeout: (uint32) 0
})
```

`grep -i UpdateFulfillHtlc ~/.lnd/mainnet-lnd-run.log |wc -l`
result: 0

So LNBIG sends neither `UpdateFulfillHtlc` nor `UpdateFailHtlc` to BLW once it connects.

LND version: LND: 0.5.2-99-beta commit=queue/v1.0.1-106-g9143067014bcde14f1e8f7eb515bae1ccccb97c5

**Comment by LNBIG-COM** [comment]
Hello!

And my addition:

When i do:

    l fwdinghistory 1548922781 1554106781 0 1000|less
    
I see 203 items (for all time at this node)

But there even no mentions of the channel `623703468500189184`! But i see that payment was succesfully send there (to see channel data above)

**Comment by btcontract** [comment]
"Might get fixed, nice to have"? 
This seems like a serious bug to me. 

As things stand if channel gets broken now then either `LNBIG12` loses `3001 SAT` (if payment was fulfilled in `LNBIG12 -  OpenChannelN1`) or BLW does (if payment was failed in `LNBIG12 -  OpenChannelN1`). Even if payment sum was large enough for on-chain resolution this is still a major inconvenience to everyone involved.

**Comment by LNBIG-COM** [comment]
@Roasbeef , I would like to know what you think about the last comment of @btcontract ?

Simply put and looking at the perfect explanation of https://medium.com/@peter_r/visualizing-htlcs-and-the-lightning-networks-dirty-little-secret-cb9b5773a0 here is exactly case of Fig. 5 (Bob - LND-12, Alice - BLW and Carol - OpenChannelN1) but normal case should be as Fig. 6

**Comment by LNBIG-COM** [comment]
Now i restarted the LND but nothing changed... Today i will update all servers up to current master branch and will check up this again after...

**Comment by LNBIG-COM** [comment]
After update:

    {
        "active": true,
        "remote_pubkey": "033fd3e16bc450ea25cad365c8422f5534429c084a2f5e200caaf5fee6811418e5",
        "channel_point": "9370b594f26b765cfccce9f3fbe266efb11eb136734c70fc3f4613ddafab937d:0",
        "chan_id": "623703468500189184",
        "capacity": "3510000",
        "local_balance": "3491221",
        "remote_balance": "3001",
        "commit_fee": "15778",
        "commit_weight": "724",
        "fee_per_kw": "21792",
        "unsettled_balance": "0",
        "total_satoshis_sent": "3001",
        "total_satoshis_received": "0",
        "num_updates": "69",
        "pending_htlcs": [
        ],
        "csv_delay": 421,
        "private": false,
        "initiator": true,
        "chan_status_flags": "ChanStatusDefault"
    },

    
    {
        "active": false,
        "remote_pubkey": "0340e6be7259217d821658db7d14f00ada2529836c48423fc322660efbec20bb96",
        "channel_point": "1d7107c9f4291cbc5cabfc5c6ea56dc069701e48a42e30c0eac89c9ae3c07dd0:1",
        "chan_id": "624874448403431425",
        "capacity": "2680000",
        "local_balance": "966283",
        "remote_balance": "1694167",
        "commit_fee": "19550",
        "commit_weight": "724",
        "fee_per_kw": "22857",
        "unsettled_balance": "3001",
        "total_satoshis_sent": "1697168",
        "total_satoshis_received": "0",
        "num_updates": "24",
        "pending_htlcs": [
            {
                "incoming": true,
                "amount": "3001",
                "hash_lock": "C1yRtexsxeTz0fdzYzGaNrJkQA/1BVuhCjiqPozxfK4=",
                "expiration_height": 569419
            }
        ],
        "csv_delay": 2016,
        "private": true,
        "initiator": true,
        "chan_status_flags": "ChanStatusDefault"
    },

    
    $ l fwdinghistory 1548922781 1554106781 0 1000|grep 623703468500189184|wc -l
    0

So no changes...

**Comment by Roasbeef** [comment]
Should be fixed now in the latest release of `lnd`. Will re-open if this pops up in the wild again.
