### ISSUE TITLE
Add support for additional macaroon restrictions such as requester's IP

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#287]
There's some low-hanging fruit for locking down macaroons to specific IP addresses using `ClientIPAddrCaveat` provided by the `go-macaroon-bakery`. It would be good to implement this in `macaroons/auth.go` and then in the delegation utility alluded to in #283.

**Comment by flaurida** [comment]
I can take this while waiting for feedback on other PRs :)

**Comment by aakselrod** [comment]
Thanks @flaurida, this is already being implemented in #313 by @mrwhythat.

**Comment by flaurida** [comment]
Ah ok thanks for the clarification, how about this one instead then?
https://github.com/lightningnetwork/lnd/issues/60

**Comment by Roasbeef** [comment]
Fixed by #313, 

Closing.
