### ISSUE TITLE
BTCD after ----dropcfindex error: Checksum does not match

### ISSUE THREAD

**Issue by frico21** [lightningnetwork/lnd#2872]
### Background

After updating btcd to the latest commit (aa6e0f35703c1438cc45860ddc0c3f6e6c633c93) and launching it with --dropcfindex. 

When relaunching it normally with:
`btcd --txindex --rpcuser=1234 --rpcpass=1234 --debuglevel=debug --datadir=/opt/btcdaemon --logdir=/opt/btcdaemon --minrelaytxfee=0`

it starts reindexing the blocks until I got the following error:
`2019-04-02 10:00:37.823 [INF] INDX: Indexed 917 blocks in the last 10.01s (329371 transactions, height 220456, 2013-02-10 06:08:48 +0000 UTC)`

`2019-04-02 10:00:42.366 [ERR] BTCD: Unable to start server on [:8333]: block data for block 00000000000000c32ac05e662ee9bd4d222b549abe10178fb544d6e6f26e93c9 checksum does not match - got 42cfb630, want ac157a84`

`2019-04-02 10:00:42.366 [INF] BTCD: Gracefully shutting down the database...`

`2019-04-02 10:00:43.043 [INF] BTCD: Shutdown complete`

### Your environment

* version of `lnd` 0.5.2-beta commit=v0.5.2-beta
* version of `btcd` 0.12.0-beta

**Comment by Roasbeef** [comment]
Not related to lnd, looks like you have disk corruption.

**Comment by frico21** [comment]
but how can I restore the database? I have to delete it and download it all again?
