### ISSUE TITLE
Restore (on testnet) only fully restored 4 out of 6, 2 in waiting_close.

### ISSUE THREAD

**Issue by vegardengen** [lightningnetwork/lnd#2873]
### Background

I tried the new static channel backups from PR #2313 

I had 6 newly opened channel, with autopilot, 3 fully opened and 3 in pending open state. All fully funded by my side.

### Your environment

* LND .5.2-99-beta commit=queue/v1.0.1-236-gf2160273b7477c9f0202250dd803afb5da261813
* Ubuntu 18.04
* bitcoind 0.16.3
* 

### Steps to reproduce

Create a few channels, do a backup. Stop node, do seed restore, then attempt to restore channel backup 
### Expected behaviour

All funds swept by my node back into wallet balance.
### Actual behaviour

Two channels are stuck in waiting_close. I can not see any force close transaction being submitted by remote end.

Example of one that closed properly:

        {
            "channel": {
                "remote_node_pub": "0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d",
                "channel_point": "3c5921f38a80c0750201fde6837c3dd485adc5c42d6062b7a173418f2a9bd47d:0",
                "capacity": "7279998",
                "local_balance": "7279815",
                "remote_balance": "0"
            },
            "closing_txid": "7f0e0c2b9b5fde7e8f8668b9ede04032646083f19d6ad2801b5dcb106cb3a023",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },

These are still stuck:

waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "023f76b9c7f0aeaef5302b39126f028b75fda2ac6afa960c18c060d3677b2240b4",
                "channel_point": "8660ebcadf3d3295ba74b0b17db2effc6054065faab2018feba55b5bd99ec7dd:0",
                "capacity": "16777215",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {
            "channel": {
                "remote_node_pub": "0254198c09eda5681742e5e81ee3d23d758fd52388db26da066b68363b96c003b7",
                "channel_point": "91da66c9ce3054803d1bc392459a5f912f7465aceb2753920d4f8de909cd95bb:1",
                "capacity": "16777215",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        }
    ]

Attacking a log from my test.

[restore_log.gz](https://github.com/lightningnetwork/lnd/files/3033886/restore_log.gz)

**Comment by vegardengen** [comment]
Realize it's entirely possible that the error is in the remote end, it does look like it just is waiting for a force close TX from the remote end.

**Comment by vegardengen** [comment]
Going into "silly mode" (after having waited half a day for it to resolve), I tried restarting. Then I tried restoring again based on what the auto-generated backups had, and got the two waiting_closed channels back into the same state.

As a last attempt - since this is testnet, and I might as well go full on "stupid user to try to break things", I restored the full backup that included the four fully resolved channels.

State is now that I have 

1) the four already restored/resolved channels in pending_force_closed, I suspect they'll never advance. It might be good to try avoid restoring channels that the blockchain says are closed/swept?

2) The two originally problematic channels in waiting_close, as on the first restore attempt.

**Comment by Roasbeef** [comment]
I only see channel update messages in the log. Since this is testnet, it is likely the case that these are un-upgraded nodes, since testnet is much less active than mainnet these days. Also if these are other implementations, then they may not yet properly reliably send the required data. Looking at `91da66c9ce3054803d1bc392459a5f912f7465aceb2753920d4f8de909cd95bb` I see that it's been fully swept on chain now. While it looks like the other channel hasn't fully closed yet (logs also show it didn't trigger anything).
