### ISSUE TITLE
error during payment

### ISSUE THREAD

**Issue by sahanakk** [lightningnetwork/lnd#2877]
`HP-ProBook-440-G4:~/lndNodes/nodeA$` lncli --network=regtest  --lnddir=./ --rpcserver=localhost:10009 sendpayment --dest=032c6076cc088982b8c72a5190c1540fedac606e8910771ba9fce890beffe16ffe --amt=1 --final_cltv_delta=500 --sphinx
{
	"payment_error": "FinalExpiryTooSoon",
	"payment_preimage": "",
	"payment_route": null
}
`
And the other node if i try the same thing i am getting the following result

` HP-ProBook-440-G4:~/lndNodes/nodeB$ lncli --network=regtest  --lnddir=./ --rpcserver=localhost:11009 sendpayment --dest=03b952d074d45d0bf12634cba1d8a08a73affe3f2dd7d3531bc62c9b900a2ed585 --amt=100 --sphinx
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
`

_Originally posted by @sahanakk in https://github.com/lightningnetwork/lnd/pull/2455#issuecomment-478542618_

**Comment by Roasbeef** [comment]
Make sure your nodes aren't synced, and double check your environment.

**Comment by sahanakk** [comment]
@Roasbeef  Sorry i didn't get
