### ISSUE TITLE
Wallet balance 0 after btcpay-update.sh!

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#2881]
I ran  `btcpay-update.sh` command and now my wallet balance is 0! 

Channels and channelbalance seems unaffected. 

* version of `lnd`

"version": "0.5.2-beta commit=basedon-v0.5.2-beta-3-dirty",

* which operating system (`uname -a` on *Nix)

Linux BTCPayServerVM 4.15.0-1019-azure #19-Ubuntu SMP Thu Jul 26 19:54:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

I use https://github.com/btcpayserver/btcpayserver-docker

And just ran the update command,  `btcpay-update.sh`

**Comment by Roasbeef** [comment]
BTCPay did some dangerous things in their past deployments (no user seed, running pruned mode, etc). I would make an issue in their tracker, as it has to do with their update mechanism.
