### ISSUE TITLE
Inaccurate fee report sum

### ISSUE THREAD

**Issue by mcduck76** [lightningnetwork/lnd#2886]
The feereport rpc call is producing apparently inaccurate day, week, and month fee sum fields.

The current calculation is based in AmtIn-AmtOut:
https://github.com/lightningnetwork/lnd/blob/3a19afe46d8c1ffed84d416c74ee6e966f3c1c62/rpcserver.go#L4457

Apparently, by the time the subtraction is performed, the AmtIn and AmtOut fields have already lost their millisatoshi resolution. The resulting totalfees are not including any fees less than 1 satoshi.

I could verify the above fact by adding up the forwards one by one for the same period.

**Comment by wpaulino** [comment]
The fees are being calculated correctly there (in terms on millisatoshis), but they're being exposed at the RPC level rounded to the nearest satoshi. We could possibly extend the response with the values in millisatoshis as well.

**Comment by mcduck76** [comment]
Yes, it seems that you are correct.
Thank you for the response.
