### ISSUE TITLE
Add caveat for limiting a user's ability to send payments only to/via specific nodes

### ISSUE THREAD

**Issue by aakselrod** [lightningnetwork/lnd#289]
It is possible to limit users/processes to send money only via specific routes or to specific nodes. A new type of caveat would have to be implemented that would allow constructions similar to the following:

* `path[0] in {node1, node2}` to specify that the user can only send through channels open with `node1` or `node2`
* `path[-1] in {node3, node4}` to specify that the user can only send to final destination nodes `node3` or `node4`
* `path[-1] not in {node5}` to specify that the user can't send to final destination `node5`
* `path[0] not in {node6, node7}` to specify that the user isn't allowed to route payments through channels connecting to `node6` or `node7`

If additional filtering is desired, it may be worthwhile to implement support for additional indices or wildcards in the path's node index, such that `path[2]` would mean the third hop. This would be more involved, as it would need to force the router to select specific paths rather than simply restrict the user to only specific channels or destinations.

**Comment by mrwhythat** [comment]
If I understand it correctly, these predicates are supposed to be the actual payload of the macaroon (i.e. part of its condition) with the corresponding macaroon checker being able to parse/validate it and apply it to the actual information about the payment route in order to make a decision.

**Comment by aakselrod** [comment]
That's correct.

**Comment by mrwhythat** [comment]
Started working on this. I'm assuming node identifiers (`node1`, `node2` etc) are `LightningNode`'s `PubKey` field values. Otherwise, syntax may be extended to allow IP/onion address restrictions.

**Comment by Roasbeef** [comment]
Will be obviated by https://github.com/lightningnetwork/lnd/pull/5101
