### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by cameloid124** [lightningnetwork/lnd#2894]
### Background

lnd daemon is eating a lot of memory. The usage gradually increases up to approximately 2.0g during the day, and then the process gets killed due to OOM. Logs show nothing abnormal.

I've found lots of reports on similar behaviour, but no specific recommendations how to mitigate.

### Your environment

* lnd version 0.6.0-beta commit=v0.6-beta-rc2, connected to mainnet, 5 channels, ~8-10 peers
* Linux 4.18.0-16 x86_64
* Bitcoin Core Daemon version v0.18.99.0-ba54342c9, "pruned" node
* Xeon Gold 6140, 2 cores, 4 GB VM
* Node name is 'cameloid'

lnd config is next to the default:

[Application Options]
  
maxlogfiles=3
maxlogfilesize=10
maxpendingchannels=10
alias=cameloid
restlisten=localhost:8080

[Bitcoin]

bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]

bitcoind.rpchost=localhost
bitcoind.rpcuser=cameloid
bitcoind.rpcpass=xxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:29000
bitcoind.zmqpubrawtx=tcp://127.0.0.1:29001

[autopilot]

autopilot.active=1
autopilot.maxchannels=10
autopilot.allocation=0.8

### Steps to reproduce

Just keep it running long enough (from 12-15 hrs to a couple of days).

What can I do to help investigating this?

**Comment by wpaulino** [comment]
Do you have any flappy peers? Most of the optimizations that have been included in v0.6 also require your peers to have upgraded to see better results.

Getting a memory/heap profile of whenever you're experiencing high memory usage would also be really helpful. [This blog post should help guide you](https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/) (don't worry about the code parts, that's already handled by `lnd`).

**Comment by cameloid124** [comment]
I'm not familiar with go profiling tools, but hopefully this is what you're looking for:

<pre>
$ go tool pprof -top http://localhost:9736/debug/pprof/heap
Fetching profile over HTTP from http://localhost:9736/debug/pprof/heap
Saved profile in /home/bitcoin/pprof/pprof.lnd.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz
File: lnd
Type: inuse_space
Time: Apr 7, 2019 at 7:41pm (+08)
Showing nodes accounting for 428.87MB, 97.79% of 438.54MB total
Dropped 38 nodes (cum <= 2.19MB)
      flat  flat%   sum%        cum   cum%
  210.54MB 48.01% 48.01%   210.54MB 48.01%  github.com/lightningnetwork/lnd/lnwire.makeEmptyMessage
  202.51MB 46.18% 94.19%   204.02MB 46.52%  github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).ProcessRemoteAnnouncement
   11.27MB  2.57% 96.76%    11.27MB  2.57%  github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement
    4.55MB  1.04% 97.79%     4.55MB  1.04%  github.com/lightningnetwork/lnd/routing.(*ValidationBarrier).InitJobDependencies
         0     0% 97.79%    11.27MB  2.57%  github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1
         0     0% 97.79%   210.54MB 48.01%  github.com/lightningnetwork/lnd/lnwire.ReadMessage
         0     0% 97.79%     3.95MB   0.9%  github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler
         0     0% 97.79%   204.02MB 46.52%  main.(*msgStream).msgConsumer
         0     0% 97.79%   210.54MB 48.01%  main.(*peer).readHandler
         0     0% 97.79%   210.54MB 48.01%  main.(*peer).readNextMessage
         0     0% 97.79%   204.02MB 46.52%  main.newDiscMsgStream.func1
</pre>

**Comment by cameloid124** [comment]
And this is very typical:

<pre>
bitcoin@cameloid-sg:/home/camel$ top -b -n 1
top - 21:25:21 up 27 days,  9:48,  2 users,  load average: 4.49, 3.08, 2.65
Tasks: 142 total,   3 running, 139 sleeping,   0 stopped,   0 zombie
%Cpu(s): 22.6 us,  3.2 sy, 74.2 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3944.7 total,    114.1 free,   3517.3 used,    313.3 buff/cache
MiB Swap:   1024.0 total,      0.0 free,   1024.0 used.    423.5 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
12762 bitcoin   20   0 2396924   1.2g  33676 S  43.8  30.5  26:49.63 lnd
</pre>

**Comment by Roasbeef** [comment]
The issue looks to be one of your peers, I'd check the logs and ban the ones that seems to be flappy (rapidly disconnecting/reconnecting).

**Comment by cameloid124** [comment]
I don't exactly know what to look for, but I only see routine activity in the logs, no rapid updates or massive loads of error messages.

**Comment by Roasbeef** [comment]
Unable to reproduce this on any of my nodes. If there's nothing out of the ordinary, then perhaps it's an OS level issue? 

If you have any thing else to report back with possibly the `trace` or `debug` logging level, then we can re-open this to investigate.
