### ISSUE TITLE
Channel in FUNDING_CANCELED state with confimred remote funding

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2897]
Details are here: https://github.com/btcontract/lnwallet/issues/134

Funding sent from BLW was pending since April 1st and got confirmed today, but remote LND has channel in FUNDING_CANCELED state by now.

**Comment by wpaulino** [comment]
We'll need @PierreRochard's logs for this channel.

**Comment by Roasbeef** [comment]
This seems normal, as the responder to a channel funding, we'll forget about it if it isn't confirmed within a reasonable timeframe. Otherwise, someone could just initiate a ton of channel fundings with fake channels that are never broadcast to fill up our disk. What is considered as reasonable now, may be more blocks than reasonable back then.

**Comment by PierreRochard** [comment]
Beginning
```
lnd.log:2019-04-01 14:11:48.522 [INF] FNDG: completing pendingID(5a69c180658d61709555cf17634d65202e3894566f1bcbb5a2a6650b5788dec0) with ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-01 14:11:48.531 [INF] FNDG: sending FundingSigned for pendingID(5a69c180658d61709555cf17634d65202e3894566f1bcbb5a2a6650b5788dec0) over ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-01 14:11:48.531 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-01 14:11:48.531 [INF] CNCT: ChannelArbitrator(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0): starting state=StateDefault
lnd.log:2019-04-01 14:11:48.536 [INF] NTFN: New spend subscription: spend_id=1221, outpoint=6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0, height_hint=569766
lnd.log:2019-04-01 14:11:48.633 [INF] CNCT: Close observer for ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) active
lnd.log:2019-04-01 14:11:48.633 [INF] NTFN: New confirmation subscription: txid=6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab, num_confs=3
lnd.log:2019-04-01 14:11:48.634 [INF] FNDG: Waiting for funding tx (6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab) to reach 3 confirmations
lnd.log:2019-04-01 14:11:48.782 [ERR] NTFN: Rescan to determine the spend details of outpoint=6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0 within range 569766-569766 failed: transaction not found within range
```

Part that may be of interest (2 days later)

```
lnd.log:2019-04-03 08:46:18.617 [WRN] PEER: Unable to find our forwarding policy for channel 6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0, using default values
lnd.log:2019-04-03 08:46:18.617 [INF] HSWC: ChannelLink(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) is stopping
lnd.log:2019-04-03 08:46:18.721 [INF] HSWC: ChannelLink(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) has exited
lnd.log:2019-04-03 08:46:18.721 [INF] HSWC: ChannelLink(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) is starting
lnd.log:2019-04-03 08:46:18.722 [INF] HSWC: HTLC manager for ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) started, bandwidth=0 mSAT
lnd.log:2019-04-03 08:46:18.722 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-03 08:46:19.072 [INF] HSWC: Received re-establishment message from remote side for channel(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-03 13:38:48.395 [WRN] FNDG: canceled waiting for funding confirmation, stopping funding flow for ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0)
lnd.log:2019-04-03 13:38:48.395 [WRN] FNDG: timeout waiting for funding tx (6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0) to confirm
lnd.log:2019-04-03 13:49:37.012 [WRN] HSWC: ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0): received unknown message of type *lnwire.ChannelReestablish
lnd.log:2019-04-04 07:27:15.325 [WRN] HSWC: ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0): received unknown message of type *lnwire.ChannelReestablish
lnd.log:2019-04-04 08:11:23.461 [WRN] HSWC: ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0): received unknown message of type *lnwire.ChannelReestablish
lnd.log:2019-04-04 08:11:35.883 [WRN] HSWC: ChannelPoint(6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0): received unknown message of type *lnwire.ChannelReestablish
```

**Comment by wpaulino** [comment]
What happened is exactly what @Roasbeef described. We should've sent an error back when canceling, but it's possible BLW didn't receive it if the app wasn't open at the time.

**Comment by Roasbeef** [comment]
Yeah this is normal, it took too long to confirm so we forgot about it. We should eventually make that a parameter though given the current fee levels.

**Comment by btcontract** [comment]
FWIW c-lightning waits for two weeks (2016 blocks) in such cases and Eclair has no special termination rule at all I think which is IMO way more reasonable than ~4 days. I've seen txs confirming in 2-3 weeks during 2017 fee spike.

> Otherwise, someone could just initiate a ton of channel fundings with fake channels that are never broadcast to fill up our disk

Never broadcast is one thing but seeing a valid tx in a mempool is different. Perhaps LND can wait longer if funding is in a mempool?

**Comment by halseth** [comment]
> Perhaps LND can wait longer if funding is in a mempool?

That is possible, but `lnd` does not always have access to the mempool (using neutrino), so that would complicate things.

I agree that the timeout should be made configurable, but missing the 4 day confirmation window also indicates the initiator's fee estimation being off.

**Comment by engenegr** [comment]
Experienced this situation. 

My counternode (LND) has FUNDING_CANCELED while mine shows channel as inactive but established.

I'm not sure it is normal from UX point of view. I'm not sure how much the channel had been in pending status because I opened it long time ago and since then it was just 'inactive'.

I _could_ set up low fee. But I look onto opening transaction now, see 11 sat/vbyte and understand that it was created fast enough and it wasn't exceptional situation.

**Comment by engenegr** [comment]
When I try to close this inactive channel, lnd throws:
```
[lncli] rpc error: code = Unknown desc = unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found
```
I definitely connected to peer since it is opening new channel while I'm trying to close this invalid channel.

**Comment by engenegr** [comment]
@halseth of course I tried then force close and it worked.

I have bad news.

Brand new channel, opened after update of my counternode to 0.6 is inactive!

My peer opened this channel yesterday right after we resolved a situation with FUNDING_CANCELED and now it is just do not work.

I will restart my node, but I hardly believe this action will help.

**Comment by engenegr** [comment]
UDP: I restarted my node and the channel is active now. Everything seems ok now. Sorry.
