### ISSUE TITLE
Add RPC to show current total available channel capacity

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#29]
An RPC should be added, similar to `walletbalance` which shows the total available payment bandwidth across all open channels. 

Steps to complete this issue: 

- Add a new proto defintion to `lnrpc/rpc.proto`. 

- Use the `gen-protos.sh` tool to re-compile the latest definitions. 

- Implement the `channelbalance` RPC within the rpcServer. This will involve obtaining channel snapshots from all the peers and tallying the total available channel capacity within each channel. 

- Add the `channelbalance` RPC call to `cmd/lncli`.

**Comment by AndrewSamokhvalov** [comment]
I will try to do this one.

**Comment by AndrewSamokhvalov** [comment]
Hi @Roasbeef, @T909!

I have a questions:
1. Do we have tests for RPC functions?
2. Do we have the way test RPC functions like "WalletBalance" without running BTC node?

**Comment by Roasbeef** [comment]
Hey @AndrewSamokhvalov, 

Great questions! I've just finished some work I prioritized to streamline the process of both automatic, and manual testing within the daemon. 

1. With [this commit](https://github.com/lightningnetwork/lnd/commit/2032723efcc3f11c2028556141e2df75008e5c6a), I added a small framework which is useful for the creation of integration tests. There's a basic example here which just open and closes a channel between two nodes. Hopefully the example is sufficient to get you up an running w.r.t using the harness. 

2. The framework (which uses [`networkHarness`](https://github.com/lightningnetwork/lnd/blob/master/networkharness.go#L212)) spins up a `btcd` node as part of the test network which all the other nodes are connected to. So you won't need to manually as one is managed automatically by the harness.

Slightly related: I also added some final touches to the [docker based network test environment](https://github.com/lightningnetwork/lnd/tree/master/docker). It makes it easy to get up a `btcd` node along with an arbitrary number of `lnd` nodes within managed containers that have persistent storage. I'm still writing the docs, but assuming you have `docker` and `docker-compose` installed, the testbed can be built with: 
```
docker-compose build --force-rm
``` 
and the containers started with:
```
docker-compose up -d
```
additionally `lnd` nodes can be added with: 
```
docker-compose scale lnd=N
```
(where N is the new number of `lnd` nodes that should exist)

**Comment by AndrewSamokhvalov** [comment]
I don't know how, but sometimes test `TestLightningNetworkDaemon` isn't working.
```
FAIL: TestLightningNetworkDaemon (11.31s)
       	lnd_test.go:190: Running 1 integration tests
       	lnd_test.go:192: Executing test basic funding flow
panic: runtime error: index out of range [recovered]
       	panic: runtime error: index out of range
```

Looks like channels not initialized properly, or maybe more time is needed, so:

```bash
➜  lnd git:(master) ✗ go test -run TestLightningNetworkDaemon

Alice peer info:
&lnrpc.ListPeersResponse{
    Peers: {
        &lnrpc.Peer{
            LightningId: ....
            PeerId:      1,
            Address:     "127.0.0.1:19557",
            Channels:    {
                &lnrpc.ActiveChannel{
                    RemoteId: ....
                    ChannelPoint: ....
                    Capacity:         50000000,
                    LocalBalance:     50000000,
                    RemoteBalance:    0,
                    UnsettledBelance: 0,
                    PendingHtlcs:     nil,
                    NumUpdates:       0x0,
                },
            },
        },
    },
}

Bob peer info:
&lnrpc.ListPeersResponse{
    Peers: {
        &lnrpc.Peer{
            LightningId: ....
            PeerId:      1,
            Address:     "127.0.0.1:64249",
            BytesSent:   0x135,
            BytesRecv:   0x1da,
            SatSent:     0,
            SatRecv:     0,
            Inbound:     true,
            Channels:    nil,
        },
    },
}
```

**Comment by Roasbeef** [comment]
Hmm yes it seem the test occasionally run into timing issues. Currently, once Alice learns of the channel, she then asynchronously notifies Bob that it's now open. IF the timing of the execution within the tests is off, then it may be possible that Alice has learned of the channel, but Bob is still waiting on Alice's signal. 

I'm currently working on adding some additional asynchronous events consumable by RPC clients in order to tighten up the execution of the tests. The run time should also be reduced significantly, as all sleeps within he tests should be able to be removed.

**Comment by Roasbeef** [comment]
Heya, 

I've pushed a few commits which make the current `networkHarness` and the current example test much more robust. All the `time.Sleep`'s have been removed so execution is much quicker, and the tests are "tighter" since they consume async requests from the daemon rather than just executing and hoping the timing works out correctly. 

As a result of the new async "status update" functionality, some of the calling sites within the tests are a bit more verbose, but that can easily be abstracted to some helper functions which will be re-used rather frequently across tests.

**Comment by AndrewSamokhvalov** [comment]
Hi @Roasbeef , sorry for delay, are tests in `master` branch working for you? If no, any chance that tests will be repaired in near future? Just need a way to understand that I didn't break anything :)

**Comment by Roasbeef** [comment]
The tests work fine for me on the master branch locally (other than a failing test in `lnwire` which is fixed by an outstanding PR). 

I still need to investigate that re-occurring failure in Travis. My current hunch is that the underlying `rpctest` package from `btcd` that's being used doesn't currently account for parallel multi-process execution. I need to add something along the lines of a file-system level lock which each `rpctest.Harness` process attempts to grab before spinning up any processes. I suspect many instances attempt to come up in parallel which results in all but one process being able to grab the listening port causing connection attempts to fail for the rest. 

A few questions: 

1. Which tests are failing for you?
2. Do you have my btcd fork installed within your `$GOPATH` before you run the test? 
3. Make sure to do a `go install` in the root directory of the project locally to ensure the harness uses the latest built version of `lnd`. 
  * This can be remedied by modifying the `networkHarness` to programmatically build the latest version of `lnd` for use within the running test context.

**Comment by Roasbeef** [comment]
OK, Travis is now green 💚.

There was a lingering race condition which I've fixed in the latest series of commits to master.

**Comment by AndrewSamokhvalov** [comment]
@Roasbeef Yep, thanks

**Comment by AndrewSamokhvalov** [comment]
@Roasbeef Could we read the logs from test node? When I test `channelbalance` over RPC I am getting this `lnd_test.go:158: unable to get channel balance: rpc error: code = 13 desc = transport is closing`, looks like I have runtime error on btc node side, but can't find a way to read logs or insert `log.Print()` properly to understand what is going wrong.

**Comment by AndrewSamokhvalov** [comment]
@Roasbeef I found temporary [solution](http://stackoverflow.com/questions/8875038/redirect-stdout-pipe-of-child-process-in-golang), but maybe there is better way.
go```
cmd := exec.Command("ls", "-l")
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
```

**Comment by Roasbeef** [comment]
Yeh, locally I would do something along those lines when debugging the integration tests. 

I think that ability should be made accessible to test authors, so just pushed a commit (https://github.com/lightningnetwork/lnd/commit/d2acb4336ce35b6961b1ae5bb023d7cd29510971) which adds the ability to dump the logs of a particular node at any point in the tests.
