### ISSUE TITLE
tor.socks specified but outbound tor connections fail

### ISSUE THREAD

**Issue by seth586** [lightningnetwork/lnd#2903]
### Background

My lnd node can not make outbound tor connections with tor.socks=9050 specified.

### Your environment

* lnd 0.5.2
* FreeBSD 11.2
* bitcoind 0.17.1
* any other relevant environment details

### Steps to reproduce

lnd.conf:
```
[Application Options]
nat=true
alias=blahblah
listen=192.168.0.123:9735
listen=localhost:9735
externalip=qwertyuiopasdfghjklzxcvbbm.onion
restlisten=0.0.0.0:8082
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0
minchansize=900000

maxlogfiles=1
maxlogfilesize=10

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.basefee=1000
bitcoin.feerate=10

[Bitcoind]
bitcoind.dir=/home/bitcoin/.bitcoin

[tor]
tor.socks=127.0.0.1:9050
```
torrc:
```
SOCKSport 9050
DataDirectory /var/db/tor
ControlPort 9051
CookieAuthentication 1
CookieAuthFileGroupReadable 1
CacheDirectoryGroupReadable 1

HiddenServiceDir /var/db/tor/lnd_service
HiddenServiceVersion 3
HiddenServicePort 9735 127.0.0.1:9735
```
### Expected behaviour

I should be able to make outbound tor connections.

### Actual behaviour

Result of `lncli connect 03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7@gwdllz5g7vky2q4gr45zguvoajzf33czreca3a3exosftx72ekppkuqd.onion:9735`:
```
[lncli] rpc error: code = Unknown desc = dial tcp: address gwdllz5g7vky2q4gr45zguvoajzf33czreca3a3exosftx72ekppkuqd.onion: no suitable address found
```

**Comment by wpaulino** [comment]
Have you confirmed whether this happens with every peer you attempt connecting to? Is this peer actually online?

**Comment by seth586** [comment]
Yes, this happens to every peer I attempt to connect to. I have even checked to see if the peers are reachable on https://graph.lndexplorer.com/

**Comment by wpaulino** [comment]
Do you have `tor.active=1` set? I don't see it in the `lnd.conf` you pasted above.

**Comment by seth586** [comment]
If I set `tor.active=1` I get:
```
NAT traversal cannot be used when listening is disabled
```
I understand this is a safety feature for tor only listening nodes, but there is no safety concern for clearnet nodes to connect to tor only nodes. Socks proxy should work either way, imo.

**Comment by wpaulino** [comment]
I believe that error has been addressed in the current master branch. You can also try one of the v0.6 release candidates, or wait until the official release.

**Comment by Roasbeef** [comment]
Yep master now lets you connect outbound and also set a distinct listening interface.
