### ISSUE TITLE
Routing payment walletofsatoshi, BlueWallet to raspiblitz node

### ISSUE THREAD

**Issue by walletofsatoshi** [lightningnetwork/lnd#2906]
So to keep it short I am trying to route payment from my BlueWallet / walletof satoshi to my raspiblitz node wallet but consistently getting error that there was a routing problem. I can send payment other way round and that’s why have remote balance and the payment I am trying to send is less than remote balance but still getting the routing problem error. Please suggest further. Thanks

**Comment by molxyz** [comment]
@walletofsatoshi There's a 1% reserve of the channel total capacity that needs to be taken into account when trying to figure out this activity. Have you put that into the equation?  Also, this type of beginner questions should be better helped on LND slack. GH issues space isn't for basic tech support.

**Comment by walletofsatoshi** [comment]
Ok will post at LND slack but I did consider 1% reserve still not working

**Comment by halseth** [comment]
Hopefully you can solve this by asking on the slack, the issue here doesn't contain enough information to be able to help 😄
