### ISSUE TITLE
No handling for sending on-chain funds to node's pubkey

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2920]
### Background

A user reported to me that they accidentally sent bitcoin to their node's public key as an address, rather than to a deposit address generated by their node (That issue is here: https://github.com/wbobeirne/joule-extension/issues/202). I can imagine this is an easy mistake to make, so it might be nice to account for it. I can think of a few ways to handle this:

1. Provide an easy way for users to access / rescue funds sent to their node's pubkey.
1. Don't allow sends to your pubkey (or other node's pubkeys, if this is easy to distinguish) without some kind of flag set.
1. (Unlikely, but I'll just throw it out there) Differentiate node pubkeys so that they're not valid to send to.

### Your environment

* version of `lnd` - 0.6.0-rc3
* which operating system (`uname -a` on *Nix) - Ubuntu 16.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind

**Comment by Roasbeef** [comment]
FWIW, sending to a plain pubkey _is_ an accepted Bitcoin transaction type. It's actually the very first Bitcoin transaction type.

**Comment by ccdle12** [comment]
Happy to pick this one up, I've made a WIP PR that at the moment checks against the users own Pubkey, ideally it would be better to prevent any Pubkeys?

**Comment by Roasbeef** [comment]
Yeah I think we should instead prevent any direct pubkey sends as the
wallet doesn't watch for this type of output.

**Comment by ccdle12** [comment]
@Roasbeef awesome, I'll update the PR to prevent any pubkeys as dest
