### ISSUE TITLE
Fail to import lnd/macaroons pkg in my own app

### ISSUE THREAD

**Issue by xsb** [lightningnetwork/lnd#2934]
### Background

I am trying to use `lnd/macaroons` in my Go program but I fail at it.

### Your environment

* version: master
* operating system: macos

### Steps to reproduce

Here I provide a simple example in which I can reproduce the issue but notice that the application is actually bigger and uses many more packages.

```go
package main

import (
	"io/ioutil"
	"log"

	"github.com/lightningnetwork/lnd/macaroons"
	"google.golang.org/grpc/credentials"
	macaroon "gopkg.in/macaroon.v2"
)

func main() {
	grpcCredential, err := credentials.NewClientTLSFromFile("/path/to/tls.cert", "")
	if err != nil {
		log.Fatal(err)
	}

	providedMacaroon, err := ioutil.ReadFile("/path/to/admin.macaroon")
	if err != nil {
		log.Fatal(err)
	}
	mac := &macaroon.Macaroon{}
	if err = mac.UnmarshalBinary(providedMacaroon); err != nil {
		log.Fatal(err)
	}
	// not doing anything because this is just an example
	_ = macaroons.NewMacaroonCredential(mac)
}
```

When getting the dependencies I see this error.

- Using Go modules (and outside of $GOPATH):

```sh
$ go get ./...
(...)
go: finding github.com/lightningnetwork/lnd/macaroons latest
build playg: cannot load github.com/lightningnetwork/lnd/macaroons: cannot find module providing package github.com/lightningnetwork/lnd/macaroons
```

I tried clearing modules cache with `go clean -modcache` but it did not help.

- Not using Go modules (inside of $GOPATH):

```sh
$ go get ./...
# github.com/lightningnetwork/lnd/macaroons
../github.com/lightningnetwork/lnd/macaroons/service.go:9:2: imported and not used: "github.com/coreos/bbolt" as bolt
../github.com/lightningnetwork/lnd/macaroons/store.go:10:2: imported and not used: "github.com/coreos/bbolt" as bolt
../github.com/lightningnetwork/lnd/macaroons/store.go:49:2: undefined: bbolt
```

The error says that the import was aliased to `bolt` so I checked and that's not the case in my filesystem:

```sh
$ head $GOPATH/src/github.com/lightningnetwork/lnd/macaroons/store.go | tail -n 1
	"github.com/coreos/bbolt"
```

### Expected behaviour

I can import lnd packages in my project.

### Actual behaviour

I fail to import lnd packages in my project.

**Comment by wpaulino** [comment]
When using Go modules, you should be able to just run

```go mod -require=github.com/lightningnetwork/lnd@version```

 within your project's directory and run `go build` after.

**Comment by xsb** [comment]
That fixed it, thanks @wpaulino

**Comment by soqt** [comment]
Any solutions for this problem? I tried above but not work for me. Here is my error message:

build command-line-arguments: cannot load github.com/lightningnetwork/lnd/macaroons: module github.com/lightningnetwork/lnd@latest found (v0.0.2), but does not contain package github.com/lightningnetwork/lnd/macaroons
