### ISSUE TITLE
Issues with findPaths algorithm

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#2938]
Found some issues with the Yen's implementation in the `findPaths` function, thought I'd post here and see if I could help fix anything.  If we have a graph like so (source A, target E):
```
//   ┌──────────┐        20         ┌──────────┐
//   │    E     │───────────────────│    D     │
//   └──────────┘                   └──────────┘
//     |   |                           |      
//     |   |                           |      
// 1000|   | 10                        | 50   
//     |   |                           |     
//     |   |                           |      
//   ┌──────────┐        60         ┌──────────┐
//   │    B     │───────────────────│    C     │
//   └──────────┘                   └──────────┘
//        |
//        |
//        | 30
//        | 
//  ┌──────────┐
//  │     A    │
//  └──────────┘
```
then the first path via Djikstra's will be `A -> B -> E` with total fees of 10.  When finding the next shortest path, Yen's will blacklist the `10` fee edge and our root path will be `A -> B` w/ spur node `B`.  However, since this will call `findPath` with source `B` and target `E`, the fees will not be taken into account because of [this line](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L584).  Therefore, the 2nd shortest path will be `A -> B -> E` with total fees of 1000 instead of `A -> B -> C -> D -> E` with fees of 130.  The next iteration will then find the 3rd shortest path (deviating from the 2nd shortest path) and find it to be `A -> B -> C -> D -> E`.  The `queryroutes` call will sort these fees before returning to the user, but if `k=2`, then the wrong 2nd path is returned.

The next issue is due to the use of a `pathHeap` which sorts by number of hops in a path rather than a metric like distance as used in `findPath`.  If we have a graph like so (source A, target E):
```
//   ┌──────────┐        50         ┌──────────┐
//   │    E     │───────────────────│    D     │
//   └──────────┘                   └──────────┘
//     |   |                           |      
//     |   |                           |      
// 1000|   | 10                        | 50   
//     |   |                           |     
//     |   |                           |      
//   ┌──────────┐  40 ┌───────┐  50 ┌──────────┐
//   │    F     │─────│   B   │─────│    C     │
//   └──────────┘     └───────┘     └──────────┘
//                       |
//                       |
//                       | 30
//                       | 
//                 ┌──────────┐
//                 │     A    │
//                 └──────────┘
```

then the shortest path will be `A -> B -> F -> E` with total fees of 50.  When our root path is `A -> B` and spur node is `B`, edge `B -> F` will be ignored and the candidate path `A -> B -> C -> D -> E` will be added to the `pathHeap`.  When our root path advances and is `A -> B -> F` with spur `F`, the `10` fee edge will be ignored and the candidate path `A -> B -> F -> E` with total fees of 1040.  When we have finished iterating over the previous shortest path and [finally pop off the best path from the pathHeap](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L940), we will pop off `A -> B -> F -> E` because it has less hops.

**Comment by joostjager** [comment]
@Crypt-iQ the plan is to remove `findPaths` completely for the 0.7 release.

**Comment by joostjager** [comment]
The number of routes parameter has already been deprecated: https://github.com/lightningnetwork/lnd/blob/dd48a36226521f6e6e2dddc456c4c0cf3c5d48ea/lnrpc/rpc.proto#L1613

**Comment by Crypt-iQ** [comment]
Ok closing this then @joostjager
