### ISSUE TITLE
Release Readme show "v0.6-rc4-beta" instead of v0.6-beta-rc4

### ISSUE THREAD

**Issue by jrosco** [lightningnetwork/lnd#2942]
The release v0.6-beta-rc4 [README](https://github.com/lightningnetwork/lnd/releases/tag/v0.6-beta-rc4 ) is showing release name "v0.6-rc4-beta" in some spots were it should be "0.6-beta-rc4"

Example typo the **manifest-v0.6-rc4-beta.txt** filename

**Comment by Roasbeef** [comment]
Fixed! Thanks for verifying :)
