### ISSUE TITLE
Insufficient capacity and HTLC cancellation?

### ISSUE THREAD

**Issue by yehen** [lightningnetwork/lnd#2943]
If there is a topology, say, A-B-C, and A want to send a transaction to C via this route.
However, the channel from B to C does not have sufficient capacity, from the wiki, we know that there will be a temporary_channel_failure error msg responsed.

Then the question is: Will the HTLC contract between A and B be cancelled before the timeout of this HTLC?

**Comment by Roasbeef** [comment]
Yep, it'll be cancelled _off chain_ by `lnd` instantly when it realizes it can't forward the HTLC.
