### ISSUE TITLE
docker tutorial .lnd/admin.macaroon: no such file or directory

### ISSUE THREAD

**Issue by y-zono** [lightningnetwork/lnd#295]
I'm trying to start the docker tutorial https://github.com/lightningnetwork/lnd/tree/master/docker.

However, I got `.lnd/admin.macaroon: no such file or directory` error. How can I fix this problem?

1.server info

```
$ uname -a
Linux lnd 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

2.install docker-compose

```
$ sudo -i
# curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose -v
docker-compose version 1.9.0, build 2585387
```

https://docs.docker.com/compose/install/

3.install docker

```
$ sudo apt-get update
$ sudo apt-get install --no-install-recommends apt-transport-https curl software-properties-common
$ curl -fsSL 'https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | sudo apt-key add -
$ sudo add-apt-repository "deb https://packages.docker.com/1.13/apt/repo/ ubuntu-$(lsb_release -cs) main"
$ sudo apt-get update
$ sudo apt-get -y install docker-engine
$ docker -v
Docker version 1.13.1-cs6, build 495b235
$ sudo usermod -a -G docker $USER // (*1)
```

https://docs.docker.com/cs-engine/1.13/

4.install lnd

```
$ git clone https://github.com/lightningnetwork/lnd.git
$ cd lnd/docker/
$ export NETWORK="simnet"
$ docker-compose run -d --name alice lnd_btc
Successfully built 4b9f55cbf6c7
WARNING: Image for service lnd_btc was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
alice
$ docker exec -i -t alice bash
root@e96a9a8cf281:/go/src/github.com/lightningnetwork/lnd# lncli newaddress np2wkh // (*2)
[lncli] open /root/.lnd/admin.macaroon: no such file or directory
```

(*1)

I got the following error. It was fixed after re-login.

```
$ docker-compose run -d --name alice lnd_btc
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

(*2)

The tutorial shows alice not root user.

```
alice$ lncli newaddress np2wkh 
```

**Comment by patwhite** [comment]
So, I see that there's a workaround to specify the macaroon directory list in #279 - @halseth is the right way to handle this through the work around and just update the documentation, or could we tweak the startup scripts to use the other location? Happy to do the work if you give some guidance

**Comment by halseth** [comment]
Probably tweaking the startup script would be preferred, then the user wouldn't have to worry about specifying the macaroonpath every call to `lncli` 😄 

You probably would want to change this line to `~/.lnd`, or maybe remove it completely (such that `lnd` will use the default path): https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/start-lnd.sh#L49

**Comment by y-zono** [comment]
Thanks @patwhite @halseth My issue was solved.
