### ISSUE TITLE
How do I get hex from the macaroon file?

### ISSUE THREAD

**Issue by Relaxo143** [lightningnetwork/lnd#2951]
I'm trying to connect Shango wallet to my lnd node (0.6 rc4) and I need the hex of the macaroon file. How do I get it? If I just click on edit with notepad++ I get text, not hex. Sorry for the dumb question.

**Comment by seth586** [comment]
```
xxd -p -c2000 ~/admin.macaroon
```

**Comment by molxyz** [comment]
@Relaxo143 It seems you're running your LND on Windows? To convert the macaroon into hex you need a tool called `xxd.exe` which afaik Windows does not have it.

So for windows users, it'll be best if you install https://gitforwindows.org/ which will give you many cool, useful Linux command tools that can run on Windows, including `xxd.exe`, which will convert the macaroon into hex in just a second. 

After install "git for windows", make sure you set paths for these commands in Windows System Variables so you can use them in any directories. 

Then open your Command Prompt (cmd.exe) and run this line:  `
xxd -p C:\Users\yourname\AppData\Local\Lnd\data\chain\bitcoin\mainnet\admin.macaroon` 

If you have more questions, the best place to ask is on LND slack as Github is not for tech support.

**Comment by Relaxo143** [comment]
> @Relaxo143 It seems you're running your LND on Windows? To convert the macaroon into hex you need a tool called `xxd.exe` which afaik Windows does not have it.
> 
> So for windows users, it'll be best if you install https://gitforwindows.org/ which will give you many cool, useful Linux command tools that can run on Windows, including `xxd.exe`, which will convert the macaroon into hex in just a second.
> 
> After install "git for windows", make sure you set paths for these commands in Windows System Variables so you can use them in any directories.
> 
> Then open your Command Prompt (cmd.exe) and run this line:
> `xxd -p C:\Users\yourname\AppData\Local\Lnd\data\chain\bitcoin\mainnet\admin.macaroon`
> 
> If you have more questions, the best place to ask is on LND slack as Github is not for tech support.
Thanks a lot. I managed to get the hex data, now I only need to figure out why the port shows as closed even though I forwarded it. I'll check out slack

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/2951#issuecomment-483164415
