### ISSUE TITLE
Verify mnemonic

### ISSUE THREAD

**Issue by xColliNx** [lightningnetwork/lnd#2952]
### Background

Unable to verify if backup mnemonic is the correct mnemonic

### Recommendation

1. User to enter "displayseed", output "<seed 1~24>" OR
2. User to enter "verifyseed <seed 1~24>", output "Seed correct!" or "Seed wrong!"

**Comment by wpaulino** [comment]
The seed is currently not stored within the wallet, so this is not possible to do. This is we suggest taking care when noting your seed down at the time of creation.
