### ISSUE TITLE
default working directory

### ISSUE THREAD

**Issue by seth586** [lightningnetwork/lnd#2954]
### Background

lnd creates `~/.lnd` directory on start even if empty. 

### Your environment

* lnd v0.6-beta-rc4
* FreeBSD 11.2
* bitcoind 0.17.1

### Steps to reproduce

Start lnd with the following lnd.conf:
```
[Application Options]
datadir=/var/db/lnd/data
logdir=/var/db/lnd/logs
tlscertpath=/var/db/lnd/tls.cert
tlskeypath=/var/db/lnd/tls.key

alias=insert_something_catchy_here
listen=localhost
restlisten=0.0.0.0:8080
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.basefee=1000
bitcoin.feerate=100

[Bitcoind]
bitcoind.dir=/var/db/bitcoin

[tor]
tor.active=1
tor.socks=localhost:9050
tor.dns=soa.nodes.lightning.directory:53
tor.control=localhost:9051
tor.v3=1
tor.privatekeypath=/var/db/lnd/v3_onion_private_key
```

### Expected behaviour

Working directory should be `/var/db/lnd`

### Actual behaviour

lnd creates empty `~/.lnd` folder on start.

### Suggested fix:

Add lnd `--workdir=` flag to specify the default working directory instead of assuming `~/.lnd` & having to specify manual paths for all features.

**Comment by halseth** [comment]
@seth586 did you try `--lnddir`?

**Comment by wpaulino** [comment]
See the `--lnddir` flag in `lnd -h`.

**Comment by lamafab** [comment]
> `--lnddir`

Would have been nice if it were documented here: https://docs.lightning.engineering/lightning-network-tools/lnd/lnd.conf :)

**Comment by Liongrass** [comment]
Thank you for pointing this out @lamafab !

**Comment by Liongrass** [comment]
Hi @lamafab! The option `--lnddir` is only available as a runtime flag, not as a configuration option, which is why it's not included (or available) in the `lnd.conf` file. You wouldn't be able to specify the directory in the configuration flag, because LND wouldn't know where to find the configuration file if the directory is non-standard.

**Comment by lamafab** [comment]
Hi @Liongrass, yes this makes sense. But what I meant is that it would have helped if `--lnddir` flag was mentioned at the start of the doc.
