### ISSUE TITLE
Channel Not Opened & Cannot Remove Pending Channel

### ISSUE THREAD

**Issue by pardus79** [lightningnetwork/lnd#2964]
### Background

A few weeks ago, I tried opening a channel to a peer. The channel failed to open but remained as a pending channel. The opening transaction was never broadcast and the channel point on the pending channel does not correspond to a transaction on the blockchain or a pending one.

I tried to forceclose it and it moved to waiting_close_channels, where it has been for about a week. Trying to close it again give response `[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed`

Any way to remove this pending channel? 

### Your environment

0.6.0-beta commit=v0.6-beta-rc3-10-ga2aeb646e7b6fe3f1c2af5ccafd13d785431bb86
Linux 4.14.35-128
bitcoind v0.17.1

### Expected behaviour

This pending channel should be cleared-out automatically at some point.

### Actual behaviour

Pending channel remaining indefinitely.

**Comment by wpaulino** [comment]
Seems related to #2948. Can you paste the logs for the funding and force close transactions?

**Comment by pardus79** [comment]
Could not find opening log, but here is when I try to close:

```
Apr 16 14:51:28 thundroid lnd[2816]: 2019-04-16 14:51:28.822 [INF] HSWC: Removing channel link with ChannelID(5d90da315c748d34cc08b370d67e7ac856b41185aad9cf7fd7b414872e96b38f)
Apr 16 14:51:28 thundroid lnd[2816]: 2019-04-16 14:51:28.822 [INF] CNCT: Attempting to force close ChannelPoint(8eb3962e8714b4d77fcfd9aa8511b456c87a7ed670b308cc348d745c31da905d:1)
Apr 16 14:51:28 thundroid lnd[2816]: 2019-04-16 14:51:28.822 [WRN] CNCT: Unable to disable channel 8eb3962e8714b4d77fcfd9aa8511b456c87a7ed670b308cc348d745c31da905d:1 on close: edge not found
Apr 16 14:51:28 thundroid lnd[2816]: 2019-04-16 14:51:28.823 [ERR] RPCS: unable to force close transaction: channel is already in the process of being force closed
```

**Comment by wpaulino** [comment]
Do you recall why the channel failed to open? Was it due to a double spend or low fees during the fee spike? Can you find the channel's funding transaction in your bitcoind's mempool?

**Comment by pardus79** [comment]
`bitcoin-cli getrawtransaction` does not find it `No such mempool or blockchain transaction.`. I don't think it made it to my node to be broadcast. The channel opening just stayed in `pending_open_channels` for most of a day before I checked the txid and it didn't exist on-chain or in the mempool. It stayed there until I tried to force close it and it has stayed in `waiting_close_channels` since.

**Comment by pardus79** [comment]
Here's the channel info:
```
 "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                "channel_point": "8eb3962e8714b4d77fcfd9aa8511b456c87a7ed670b308cc348d745c31da905d:1",
                "capacity": "1000000",
                "local_balance": "989324",
                "remote_balance": "0"
            },
            "limbo_balance": "989324"

```

**Comment by wpaulino** [comment]
If the transaction failed to broadcast due to being invalid, then the funds should not be locked up. If you believe they still are, you can force a rescan from your wallet's birthday. See [here](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan) for more details on how to do so. I would only do this if you're absolutely sure the transaction cannot confirm in the chain.

You can attempt to use the `abandonchannel` command with a debug build of `lnd` to remove the pending channel record. To obtain a debug build, just run `make` in `lnd`'s source directory and use the binary created there: `./lnd`.

**Comment by pardus79** [comment]
I'm certain no funds were moved in regards to this so I'll go ahead and remove it.

Thank you for your help!

**Comment by wpaulino** [comment]
Sweet. Will close for now then, feel free to comment or ask on our [Slack](https://join.slack.com/t/lightningcommunity/shared_invite/enQtMzQ0OTQyNjE5NjU1LWRiMGNmOTZiNzU0MTVmYzc1ZGFkZTUyNzUwOGJjMjYwNWRkNWQzZWE3MTkwZjdjZGE5ZGNiNGVkMzI2MDU4ZTE) if you have trouble doing the above.
