### ISSUE TITLE
Inconsistent date format used in logged

### ISSUE THREAD

**Issue by erikbos** [lightningnetwork/lnd#2965]
### Background

Just upgraded to lnd 0.6 

### Your environment

* version of `lnd`

0.6

### Steps to reproduce

Connect lnd's restlisten port 

### Expected behaviour

Date format should be the same for all log entries generated by lnd.

### Actual behaviour

Log entries:

Apr 16 22:39:01 x lnd[27852]: **2019-04-16** 22:39:01.560 [INF] CRTR: Updated vertex data for node=x
Apr 16 22:39:08 x lnd[27852]: **2019/04/16** 22:39:08 http: TLS handshake error from x:51511: remote error: tls: unknown certificate

**Comment by cfromknecht** [comment]
pretty sure this log is not generated by lnd, but by grpc. all of lnd's logs will have the format: `[LVL] SYST: ...` where `LVL` is the logging level and `SYST` is the subsystem that wrote the log
