### ISSUE TITLE
Money occasionally vanishes into thin air when doing self-payments

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#2966]
I'm rebalancing channels by doing self-payments and occasionally, even though the payment was successful (both according to what sendtoroute gives back and the output of listpayments), the balance of the incoming channel never gets updated. The balance of the outgoing channels gets updated though. So I'm kind of losing money. Seen this a few times now, but I just recently added detection for it so could have happened earlier without me realizing.

Example:
Channel state of the incoming channel before and after two payments of 50000 sat each (info comes from listchannels, fields are node alias, channel point, channel id, local balance, remote balance, capacity):

LNBIG.com [lnd-26] dfcb5371017d0ff0f5f86ed17d03cf571311f703af5c6da1ce5ac73472f4a3c7:0 622280700522135552      20966    1927444    1957576
LNBIG.com [lnd-26]                       dfcb5371017d0ff0f5f86ed17d03cf571311f703af5c6da1ce5ac73472f4a3c7:0 622280700522135552      20966    1927444    1957576 

And the same for the outgoing channel:

lncm-ad-1                                6601d9e0145c1ac710234b1878a4b7be295687e5a0df0c49fd11c4ff665a998a:0 626423660300075008     114276          0     125000
lncm-ad-1                                6601d9e0145c1ac710234b1878a4b7be295687e5a0df0c49fd11c4ff665a998a:0 626423660300075008      15376     100002     125000

I'm only giving details for the first of the two payments. For that one, sendtoroute was called with payment_hash set to bd8556cab367205d5acc099d0eadf174a7576057d7fa10e23b747cd8e716b71e and given this list of routes: https://pastebin.com/DMqFESpE
and gave this back:

```json
{
    "payment_error": "",
    "payment_preimage": "5760982e99f294d4f99605cfdda49613856773ce18152edc9a075b454e82b378",
    "payment_route": {
        "total_time_lock": 572306,
        "total_fees": 1,
        "total_amt": 50001,
        "hops": [
            {
                "chan_id": 626423660300075008,
                "chan_capacity": 125000,
                "amt_to_forward": 50000,
                "fee": 1,
                "expiry": 572162,
                "amt_to_forward_msat": 50000150,
                "fee_msat": 1050,
                "pub_key": "03f443605e76840a654b19247240d98ac56d1b80ec069dc608bf98e3bb172b68ee"
            },
            {
                "chan_id": 605605507184394240,
                "chan_capacity": 16777215,
                "amt_to_forward": 50000,
                "expiry": 572158,
                "amt_to_forward_msat": 50000100,
                "fee_msat": 50,
                "pub_key": "03da1c27ca77872ac5b3e568af30673e599a47a5e4497f85c7b5da42048807b3ed"
            },
            {
                "chan_id": 623680378716028928,
                "chan_capacity": 16777215,
                "amt_to_forward": 50000,
                "expiry": 572128,
                "amt_to_forward_msat": 50000000,
                "fee_msat": 100,
                "pub_key": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b"
            },
            {
                "chan_id": 622280700522135552,
                "chan_capacity": 1957576,
                "amt_to_forward": 50000,
                "expiry": 572128,
                "amt_to_forward_msat": 50000000,
                "pub_key": "03a503d8e30f2ff407096d235b5db63b4fcf3f89a653acb6f43d3fc492a7674019"
            }
        ],
        "total_fees_msat": 1200,
        "total_amt_msat": 50001200
    }
}
```

lookupinvoice for the payment request that was being used gives this:

```json
{
    "memo": "",
    "receipt": null,
    "r_preimage": "V2CYLpnylNT5lgXP3aSWE4Vnc84YFS7cmgdbRU6Cs3g=",
    "r_hash": "vYVWyrNnIF1azAmdDq3xdKdXYFfX+hDiO3R82OcWtx4=",
    "value": "50000",
    "settled": true,
    "creation_date": "1555479334",
    "settle_date": "1555479343",
    "payment_request": "lnbc500u1pwtdwexpp5hkz4dj4nvus96kkvpxwsat03wjn4wczh6lappc3mw37d3eckku0qdqqcqzpgrzjq20dhvcyc7sql05ujyhwhw9gvkh7j6seq90q2j8ghctfr7t9789fwz9juvqqt3gqqyqqqqlgqqqqqqgqjqhwd7zx7gpx26s2ugaxy0280fz8vdxmcdejlh94nd4hvfhzkjxj79nkku4wmtlvy082rkl66zkdql9xelnt07elz70luf5gf8fzqe59gpc6z83c",
    "description_hash": null,
    "expiry": "3600",
    "fallback_addr": "",
    "cltv_expiry": "40",
    "route_hints": [
        {
            "hop_hints": [
                {
                    "node_id": "029edbb304c7a00fbe9c912eebb8a865afe96a19015e0548e8be1691f965f1ca97",
                    "chan_id": "626812887394222081",
                    "fee_base_msat": 1000,
                    "fee_proportional_millionths": 1,
                    "cltv_expiry_delta": 144
                }
            ]
        }
    ],
    "private": true,
    "add_index": "19801",
    "settle_index": "1320",
    "amt_paid": "50000000",
    "amt_paid_sat": "50000",
    "amt_paid_msat": "50000000"
}
```

lnd 0.6 (also seen with lnd 0.5.2)

**Comment by jogc** [comment]
I forgot to add that the only thing I can find in the log related to the payment is this line:

2019-04-17 13:35:43.335 [INF] HSWC: ChannelLink(552271:2822:1) settling htlc bd8556cab367205d5acc099d0eadf174a7576057d7fa10e23b747cd8e716b71e as exit hop

(I was running with debuglevel info)

**Comment by Roasbeef** [comment]
Seems like there's a problem with whatever code you're using to rebalance.

**Comment by Roasbeef** [comment]
> , the balance of the incoming channel never gets updated. The balance of the outgoing channels gets updated though. 

If the balance of the incoming channel never goes down, but the outgoing increase, then you'd be _gaining_ money not losing money.

**Comment by halseth** [comment]
@jogc Can you provide some logs (debuglevel) from when you are doing such a payment?

**Comment by jogc** [comment]
Yep, sure. Since it only happens occasionally it could take a little while.

Den ons 24 apr. 2019 kl 18:18 skrev Johan T. Halseth <
notifications@github.com>:

**Comment by jogc** [comment]
I'm trying to log as much as possible. Do I need PEER=debug or is it enough
with PEER=info? (all the others are set to trace)

Den ons 24 apr. 2019 kl 18:18 skrev Johan T. Halseth <
notifications@github.com>:

**Comment by Roasbeef** [comment]
Closing this for now as it seems to be an issue with your rebalancing script, rather than anything in `lnd`. You may want to compare your script with the others in the wild that are widely used.

**Comment by jogc** [comment]
Ok, fine. Just to be clear: If I am being stupid and hand weird routes to sendtoroute, lnd will not protect me from myself and the end result could be something like this, correct?

**Comment by jogc** [comment]
Ok, I have reproduced this, and it seems no funds are actually getting lost (sorry for the noise about that)! Rather, it seems lnd takes the liberty to ignore the last channel hop I have specified in the route and choose another channel instead (this second channel does go between exactly the same pair of nodes as the one I specified). So the balance is updated (increased) on that channel instead. But the reported route that sendtoroute gives back does not reflect this modification, so I think there is still a bug in the sendtoroute command. Should I open a new issue for this?

**Comment by Roasbeef** [comment]
>  it seems lnd takes the liberty to ignore the last channel hop I have specified in the route and choose another channel instead (this second channel does go between exactly the same pair of nodes as the one I specified

This is expected: https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#non-strict-forwarding

We can't control _which_ route a node uses when it has multiple possible options that lead to the same target.

**Comment by jogc** [comment]
Got ya!


Den tis 30 apr. 2019 kl 07:15 skrev Olaoluwa Osuntokun <
notifications@github.com>:
