### ISSUE TITLE
findPath fails to find path when cltvlimit is specified

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#2969]
### Background

Pathfinding with findPath can fail to return a valid route when the cltv limit restriction is specified.
### Your environment

* version of `lnd`
lnd version 0.6.0-beta commit=v0.6-beta-rc3-19-g6cfb02813b0a1b470cf2fd738043f8cb20ac1569
* which operating system (`uname -a` on *Nix)
Darwin

### Actual Behavior
If we have a graph like so:
```
//               30, 144         30, 144
//   ┌──────────┐    ┌──────────┐     ┌──────────┐
//   │    D     │────│     E    │─────│    T     │
//   └──────────┘    └──────────┘     └──────────┘
//         |                           |      
//         |                           |      
//         | 30, 144                   | 500, 144   
//         |                           |     
//         |                           |      
//   ┌──────────┐     30, 144       ┌──────────┐
//   │    B     │───────────────────│    C     │
//   └──────────┘                   └──────────┘
//        |
//        |
//        | 30, 144
//        | 
//  ┌──────────┐
//  │     A    │
//  └──────────┘
//	  |
//	  |
//        | 30, 144
//        |
//  ┌──────────┐
//  │     S    │
//  └──────────┘
```
where the first value is the base fee and the second value is the time lock delta of each edge (let's say it's the same in both directions).  Let's say our cltv limit is `500`.  Then `findPath` will start with T, adding both `E` and `C` to the heap.  Then `E` is popped off the heap (fee of 30 vs fee of 500), and `D` is added to the heap.  Then `D` is popped off the heap (fee of 60 vs fee of 500) and `B` is added to the heap.  Then `B` is popped off the heap (fee of 90 vs fee of 500), but `A` is not added to the heap because the cltv limit of `500` is exceeded (`144 * 4 = 576`).  Then `C` is popped off the heap, but since `B` already has a distance in the distance map of 90, `B` cannot be taken again with a greater distance.  So `findPath` will fail to return the correct route of `S -> A -> B -> C -> T` with total time lock of `432`.

**Comment by Crypt-iQ** [comment]
Update: similar pathfinding failures can occur with the fee limit restriction, max or min htlc's of an edge, or the bandwidth of an edge.  A valid path exists but it won't be taken.

**Comment by Crypt-iQ** [comment]
The cases where fee-based limits (all of the constraints BESIDES cltv limit are fee-based) fail are a little bit different but still follow the same idea.  Let's take the following graph where the LHS is the base fee (fee rate 0) and the RHS is the time lock delta.

```
//                      400, 144         
//   ┌──────────┐                     ┌──────────┐
//   │    D     │─────────────────────│    T     │
//   └──────────┘                     └──────────┘
//         |                           |      
//         |                           |      
//         | 400, 144                  | 400, 144   
//         |                           |     
//         |                           |      
//   ┌──────────┐     300, 200      ┌──────────┐
//   │    B     │───────────────────│    C     │
//   └──────────┘                   └──────────┘
//        |
//        |
//        | 400, 144
//        | 
//  ┌──────────┐
//  │     A    │
//  └──────────┘
//	  |
//	  |
//        | 400, 144
//        |
//  ┌──────────┐
//  │     S    │
//  └──────────┘
```

Let's have a payment amount of 1 million satoshis from S to T and a fee limit of `1150` msats.  A real-life example would likely have higher fees for higher payments, but bear with me.  So `findPath` will start with `T`, adding `C`, `D` to the heap. The edge weight function is:
https://github.com/lightningnetwork/lnd/blob/1c22474ad31b5f7fe18f9cc8df7c08cd445eaacb/routing/pathfind.go#L347-L357

So `C`, `D` have a distance of:
`(1000000400 * 15 * 144/1000000000) + 400 ≈ 2560`.

If `D` is popped off the heap, the distance to `B` will be:
`2560 + 400 + (1000000800 * 15 * 144 / 1000000000) ≈ 5120`.

If `C` is popped off the heap, the distance to `B` will be:
`2560 + 300 + (1000000700 * 15 * 200 / 1000000000) ≈ 5860`.

So the path to `B` will be through `D` with a distance of `5120`.  However, then `B` won't be able to reach `A` because of the fee limit of `1150` msats (`400 * 3 = 1200`) so path finding will fail.  But the path through C would have been able to support the fee limit (`400 + 300 + 400 = 1100`).

**Comment by joostjager** [comment]
@Crypt-iQ These are excellent examples showing Dijkstra not returning the optimum route. This is a very valid issue.

**Comment by Crypt-iQ** [comment]
@joostjager One more thing I forgot to note but it might already be clear to you.

This case applies to all of the failures, but let's take the fee limit case above.  If we have another path from `T` to `S` that doesn't go through `B` and still satisfies the fee limit, it would be preferred.  This path could have huge cltv values and thus a much larger distance to source.  So it might not be the case that `findPath` returns no paths, but instead just a non-optimal path.  I bring this up because the graphs on testnet / mainnet are quite large and connected so failures where no paths are returned might not be common.  Instead, there might just be subtle failures where non-optimum paths are returned.

**Comment by joostjager** [comment]
Yes, I know it can be quite subtle, difficult to detect. A similar problem exists for the hop limit.

**Comment by joostjager** [comment]
Unassigning myself as this is not something that I will be working on in the short term. It isn't an easy problem to solve.

**Comment by saubyk** [comment]
Closing this issue, can reopen if we feel there is a need to address this
