### ISSUE TITLE
[Feature request] Arbitrary messages grpc API

### ISSUE THREAD

**Issue by jooray** [lightningnetwork/lnd#2971]
LND grpc API has signmessage and verifymessage call. It would be useful if we could pass arbitrary messages (with some topic id) to a remote node (or alternatively just connected peer), encrypted with the node's public key. It is about exposing this functionality to the public.

This functionality is useful when building applications on top of the Lightning network, for example for negotiating contracts and prices. There are many possible use-cases that go beyond just invoicing and paying the invoice.

**Comment by wpaulino** [comment]
You can already provide an arbitrary message to the API, see https://api.lightning.community/#signmessage.

**Comment by jooray** [comment]
Yes, I know, but only for signing.

What I am saying is that since there is a way for the LN nodes to communicate anyway, it would be great if we could use the API to send a particular custom message to another LN node, while using the same communication channels, encryption and security.

**Comment by Roasbeef** [comment]
LN isn't a messaging protocol. You can build something _on top_ of `lnd` using these API's if you'd like.
