### ISSUE TITLE
[Feature request] Accepting or rejecting payments

### ISSUE THREAD

**Issue by jooray** [lightningnetwork/lnd#2972]
When issuing an invoice, there should be a way for the recipient to finalize or reject the payment before finalising it automatically.

This is useful for example for a use-case of physical vending machine. The invoice is issued, the payment goes through up until the last step. The machine tries to dispose the product, but it detects a mechanical problem and wants to refuse the payment at the last moment, so the final decision is with the receiver of the payment to accept or reject the payment (but without affecting finality).

**Comment by vegardengen** [comment]
This is already possible through #2022  which needs special building, with invoicesrpc tag.

I haven't followed that one closely, but I see from other in progress PR's that there is ongoing work on redesigning it.

**Comment by jooray** [comment]
Thanks
