### ISSUE TITLE
Paying hold invoice using CLI blocks until receiver settles invoice

### ISSUE THREAD

**Issue by willcl-ark** [lightningnetwork/lnd#2975]
### Background

As far as I can tell, when Alice creates a hold invoice for Bob, when Bob goes to pay the invoice, the call is blocking until Alice settles the invoice from her side.

This is not so much of a problem for the gRPC API (which is how I discovered the issue) as there are many techniques to circumvent this, but in the CLI I feel that this needs to be reworked so that Bob can use his CLI while waiting for Alice to settle the invoice.

### Your environment

* lnd v0.6-beta
* darwin
* bitcoind 0.18.0rc3

### Steps to reproduce

`alice addholdinvoice PreimageHashHex Amount`

`bob payinvoice PaymentRequest`

... bob's CLI wait's indefinitely until:

`alice settleinvoice PreimageHex` is called by alice

### Expected behaviour

CLI call to payinvoice should be non-blocking

**Comment by wpaulino** [comment]
There's no way for `lnd` to tell whether it is paying a hold invoice or not. The best we can do is provide a flag for users to prevent blocking when paying a hold invoice, but they'd have to know they are indeed paying one.

**Comment by willcl-ark** [comment]
I see, and with this flag the payer would not know if the payment was accepted or not without frequent manual checking...

Perhaps then it is something best left to wallet layer software which seems to be the case currently

**Comment by Roasbeef** [comment]
> So that Bob can use his CLI while waiting for Alice to settle the invoice

Bob can run it in the background, user another terminal, etc, etc. The API for paying invoice will also be revamped by 0.7.
