### ISSUE TITLE
[Feature] Add the ability to craft on-chain transactions using specified UTXOs

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2976]
Coin control is a feature that can help deliver improved privacy and assist with regular wallet-related tasks like UTXO-consolidation and fan-out.

Discrete control of UTXOs can also aid in fee-strategic coin selection schemes

Ideally this could be added to every on-chain transaction generating method

**Comment by kaloudis** [comment]
@alexbosworth any progress here? I think this is a really important one and would like to help

**Comment by alexbosworth** [comment]
> @alexbosworth any progress here? I think this is a really important one and would like to help

There is now a coin lease API, have you looked at that?

**Comment by wpaulino** [comment]
This isn't possible yet, keep an eye on https://github.com/lightningnetwork/lnd/pull/4389 for being able to do so through PSBTs.

**Comment by kaloudis** [comment]
@alexbosworth will do

@wpaulino good to know, will check it out.

thank you both

**Comment by rockstardev** [comment]
Now tell me you'll also be able to do this with unconfirmed UTXOs and we're in business...

**Comment by guggero** [comment]
The PSBT funding PR is merged now. But I just looked at the code and saw that we require at least one confirmation on the selected UTXOs. I guess we'll need to add a `allow_unspent` flag on the `FundPsbt` RPC.

**Comment by rockstardev** [comment]
@guggero worthy to note that @mrfelton already implemented on-chain sending with selection of unconfirmed UTXOs, this PR: https://github.com/lightningnetwork/lnd/pull/4653

**Comment by guggero** [comment]
Ah yes, I remember that PR. But none of those RPCs allow you to do coin selection, so having the same `min_confs` and `spend_unconfirmed` params on the `FundPsbt` RPCs would give you even more control.

**Comment by Roasbeef** [comment]
The set of PSBT calls can now be used to accomplish this.
