### ISSUE TITLE
Feature Request: Allow Spending Unconfirmed Funding Transaction Change Output to CPFP it with sendcoins

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#2977]
### Background

Describe your issue here.

Currently have a channel open where I cannot spend the change output with sendcoins to increase fees for channel to confirm quicker. 

Would be nice to have a flag where all coins even unconfirmed can be spent.

Have not checked any of the build flags if I can do this manually.

**Comment by wpaulino** [comment]
See https://github.com/lightningnetwork/lnd/pull/1746.

**Comment by juscamarena** [comment]
Nice, didn't search for PRs, but issues.
