### ISSUE TITLE
Fully validate all channel commitment flow constraints 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#298]
# Issue 

Within the specification [there are a series of flow control and reserve related parmaters](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements) which are used in order to allow nodes to limit their total exposure at any given time (flow control), and also to ensure that both sides always have skin-in-the-game (reserves). The reserves are required, as otherwise, if a party ever has a balance of _zero_ within the channel (other than the first state), it then becomes _costless_ for them to attempt to broadcast a prior state and cheat the honest party within the channel. 

At the comment the [only dimension of commitment sanity](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L2406) that we verify are that we're not going over the limit on the max number of HTLC's. This is insufficient, as we should be verifying all dimensions of commitment sanity which include flow cntorl limits, fee viability, and finally reserve adherence. 

# Steps to Completion 

The areas that'll need to be touched for the completion of this issue are two fold: 
  

- [ ] We'll need to modify the initial funding workflow to properly set sane default values for the channel reservation, and flow control values within the [`ChannelConstraints`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L122) proposed during the funding workflow. We currently [use functions to set proposed number of confirmations, and remote delay which are configurable](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L210). Similar closures should be used to set sane values based on the value of the channel.

- [ ] Currently, [we simply _echo_ back the flow control parameters](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L759) during the funding workflow, instead we should advertise our requirements for the _remote_ party. One will need to study the manner in which the parameters apply to either side. For example, the reserve value I send is what I require _your_ reserve to be. As a result, some of the initialization within the `fundingManager`, and also within the [reservation workflow itself](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L146) will need to be modified to be aware of this. 

- [ ] The [`validateCommitmentSanity`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L2406) method should be updated to ensure all reserve and flow control parameters are upheld at all times. Additionally, it should also reject an HTLC add attempt if the initiator of the channel is unable to pay for the require fees. 

- [ ] The [`getBandwidth`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L862) method should be modified to subtract the require reserve value. This simple change will ensure that [when making forwarding decisions](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L350), the switch doesn't need to make any additional calculations, and the reserve is subtracted from what the available bandwidth should be.

**Comment by Crypt-iQ** [comment]
I'll take this one

**Comment by halseth** [comment]
I'll finish this one up :)

**Comment by Roasbeef** [comment]
Fixed by #443
