### ISSUE TITLE
Funding TXID never broadcasted to network, forced closed channel but it remains stuck

### ISSUE THREAD

**Issue by Z-and** [lightningnetwork/lnd#2988]
I'm having the same exact problem described in issue #2964. However, the node I'm using was built with Raspiblitz which I believe only installs the binaries, so I'm not able to run a debug build of lnd to `abandonchannel `. Is there any other way to remove this channel from `waiting_close_channel`?

**Comment by wpaulino** [comment]
No, that'll be the only way. You can follow the [install docs](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installation) on the Raspberry Pi to compile the debug binary.
