### ISSUE TITLE
Observe the routing table dump feature bit

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#299]
# Issue 

Within the protocol, we use [feature bits](https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md) to allow nodes to signal their awareness and possibly implementation of new features. Features are either optional or mandatory. An optional feature means we can still interact if you don't know of it, while a mandatory feature means I'll kill the connection and go seek a peer which has the features as it's necessary for us to actually do normal operation. 

At the time of the writing of this issue, there exists a single feature bit specified: [`initial_routing_sync`](https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md#assigned-localfeatures-flags). It's rather simply and indicates if a peer wants to receive a full routing dump upon initial connection or not. We don't yet properly observe this, so we should. 

The feature bits that `lnd` is aware of are housed in [`features.go`](https://github.com/lightningnetwork/lnd/blob/master/features.go). 

# Steps to Completion 

- [ ] Re-examine our [`FeatureVector`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go) implementation along with it's verification of if [we're compatible with a peer or not](https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go#L204) compared with the specification. A few components have been modified over the drafting period, so we should re-examine it to ensure we implement the proper behavior. 

- [ ] When a peer connects, atm [we unconditionally synchronize routing state](https://github.com/lightningnetwork/lnd/blob/master/server.go#L1047). Instead, the feature bit should be examined, only triggering the routing table sync if they _don't_ have the bit set. 

The accomplish the above tasks, the API of the `FeatureVector` struct may need to be modified a bit in order to allow callers to preferentially set certain bits. Atm, the API assumes that bits will always be assigned in order (if uses array based initialization).

**Comment by jamesob** [comment]
Going to be tackling this in the next few days. If anyone has a burning desire to take this over, just say so!

**Comment by Roasbeef** [comment]
Fixed by #373.
