### ISSUE TITLE
lnwallet: extend BitcoindFeeEstimator to allow economic fee estimates

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2990]
Atm for our `bitcoind` fee estimator, by not setting an `estimate_mode`, we default to always using the `CONSERVATIVE` setting. This setting can at times return a higher fee rate than the `ECONOMICAL` setting would. [We should update our custom JSON request (as this call isn't in `btcd`)](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/fee_estimator.go#L441) to either allow this new setting, or default to one of the other depending on what is actually being done (close new channel, sweep out, etc).

**Comment by yyforyongyu** [comment]
I'm working on this issue.

**Comment by guggero** [comment]
Fixed by #4078.
