### ISSUE TITLE
Odd go/git tags behavior

### ISSUE THREAD

**Issue by meeDamian** [lightningnetwork/lnd#2994]
### Background

Attempt to import `lnd` to a project yields one of two peculiar scenarios:
- if version is not specified, [the very first ever `v0.0.2` tag is used][ancient],
- if latest tag `v0.6-beta` is specified, it [gets force-replaced with a quite confusing `v0.5.1-beta.0.20190416133022-58ec9efed2a6`][insistent], where `v0.5.1-beta` is a name of a seemingly random old tag, and `20190416133022-58ec9efed2a6` part actually correcponds to the tag specified originally.

[ancient]: https://travis-ci.com/meeDamian/sadlnd/jobs/194904266
[insistent]: https://travis-ci.com/meeDamian/sadlnd/jobs/194904267

### Your environment

* version of `lnd`: **`v0.6-beta`** and **`v0.5-beta`** (`v0.5.2-beta`, `v0.5.1-beta` seem to behave as expected)
* which operating system: **[Travis] and MacOS 10.14.5**
* version of `btcd`, `bitcoind`, or other backend: **N/A**

[Travis]: https://travis-ci.com/meeDamian/sadlnd/builds/109272806

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Clone: `https://github.com/meeDamian/sadlnd`, and run:

```
docker build insistent/
```

### Expected behaviour

Tag `v0.6-beta` should be used.

### Actual behaviour

Tag `v0.5.1-beta.0.20190416133022-58ec9efed2a6` is used instead.

---

Even if(?) this bug is just a _`go mod` growing pain_. The issue here might spare someone confusion I went through.

**Comment by cfromknecht** [comment]
@meeDamian thanks for the report, after looking into it it seems the issue is caused by not having the format `vX.X.X` and instead only using a major and minor version. there should be a new `v0.6.0-beta` tag. can you confirm that this now works for you?

**Comment by meeDamian** [comment]
Specifying either `v0.6-beta`, or `v0.6.0-beta` works as expected now.  Former gets automatically replaced with `v0.6.0-beta`, but that's good.

Not specifying a tag still pulls `v0.0.2` by default. That's probably because it's the highest version available without the `-beta` suffix.

Also, thank you :).
