### ISSUE TITLE
contractcourt+htlcswitch: reliable handoff of contract resolutions 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2998]
Today in `lnd`, if we need to timeout or settle and HTLC on-chain, then in order to cancel/settle the _incoming_ HTLC, [we send a message to the switch to clean up the incoming link](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/htlc_timeout_resolver.go#L141). This message then gets [passed to the switch via a `resolutionMessage`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L1557). However, due to a lack of _reliable_ handoff between the switch and the resolver, if `lnd` goes down _during_ the handoff, then the outgoing HTLC will be settled/expired, but the incoming HTLC will be left lingering. There's a `done` channel that's closed in an attempt to synchronize, but it's only closed once the HTLC settle/fail is inserted into the mailbox of the link, and not when it's been fully committed like the normal forwarding packages. 

There're a few ways we can go about fixing this: 
  1. Modify the resolvers themselves to continually try to send the resolution message to the switch. As the circuit map will be cleaned up once the resolution is fully committed, once the attempt fails, the resolver knows that the HTLCs have been fully cleaned up. 
  2. Add persistent state to the switch, which is _synchronously_ written before returning to the resolver. This state is then checked on start up, similar to the forwarding packages to re-insert any relevant messages into the mail box of the target link.

**Comment by joostjager** [comment]
@Roasbeef Isn't it most straight-forward to use the channel SettleFail filter? Wait in the resolver for the filter bit to be set, similar to how the outgoing link would be notified if the link was still there.

**Comment by joostjager** [comment]
Started looking into this again. If we want the resolver to check the settle/fail filter of its channel, we need to have the commit height for which we are resolving. It is not yet clear to me whether this value is available for all close types in the channel arbitrator. It is not persisted as part of a commit set in `briefcase`.

**Comment by joostjager** [comment]
There are also the `HtlcFailNowAction` resolutions that currently don't have a resolver, but probably should have. Otherwise an incoming htlc may not get cancelled if `lnd` goes down after [hand off](https://github.com/lightningnetwork/lnd/blob/daa08be62ae8dda0b81f975d0af9b53a3cab2dc4/contractcourt/channel_arbitrator.go#L902) in `channel_arbitrator`.
