### ISSUE TITLE
Port over all specification test vectors into table-driven tests

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#300]
# Issue 

The set of specifications includes a number of tests vectors across the various documents in order to provide implementations with valid inputs to automated tests to ensure that their implementations at least partially compatible with other implementations. In several areas of the codebase, we've ported over these tests to be executed using the [table-driven test paradigm](https://github.com/golang/go/wiki/TableDrivenTests) commonly used within the golang ecosystem.

In order to keep in sync with the latest specification changes, and to provide an additional level of assurance of our compatibility we, should port over the remaining un-imported test vectors into the project.  

# Steps to Completion 

- [x] Port [Appendix C: Funding Transaction Test Vectors](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#appendix-c-funding-transaction-test-vectors) from `BOLT-0003`. 

- [x] Port [Appendix C: Commitment and HTLC Transaction Test Vectors](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#appendix-c-commitment-and-htlc-transaction-test-vectors) from `BOLT-0003`.

- [x] Port  [Appendix E: Key Derivation Test Vectors](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#appendix-e-key-derivation-test-vectors) from `BOLT-0003`.

**Comment by jimpo** [comment]
I'm working on this one.

**Comment by Roasbeef** [comment]
Fixed by #365, #350, and #593
