### ISSUE TITLE
invoices+rpc: disallow creating an invoice if the node lacks insufficient incoming bandwidth

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3001]
Today it's possible to create an invoice that can't actually ever be fulfilled. For example, if the maximum inbound bandwidth for all my channels is 100k satoshi, then I can't receive a 300k satoshi payment. An optional mode should be added to `AddInvoice` to _reject_ invoice creation like this, notifying the caller that they can't receive a payment of that size. Eventually, we may also want to make this mode the default in order to slowly educate users w.r.t the flow constraints of channels. Even after AMP, this will still be relevant, but instead we'd sum inbound bandwidth across all channels.

**Comment by xsb** [comment]
I can pick this one
