### ISSUE TITLE
fundingmanager+routing: sanity check all open channels for advertisements on startup 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3002]
There's a lingering issue in `lnd` today that can cause a channel to not be fully announced as a result of a flubbed handoff between the funding manager and gossiper/router. In this scenario, the funding manger marks a channel as complete, causing it to not attempt to re-announce the channel on start up. A symptom of this in the past (though it's been [partially patched and should be reverted as part of this](https://github.com/lightningnetwork/lnd/commit/c0977c95dfd7c1b4ff4e25363f8f4b1ef72569ea#diff-01ada5680aaa18fc79cbf78b2d55a37b)) is that a channel shown in `listchannels` has a channel ID of zero.

A more fundamental overhaul in the funding manager as prep for splicing and dual funding is planned. However, in the short term, we can properly patch this by adding a simple sanity check at startup within the funding manager.

- [ ] On startup, the funding manager should obtain all known channels, filter out those that are private, and check for existence of a fully advertised channel within the router. If one isn't found, then the channel announcements should be re-created and re-sent.

**Comment by mlerner** [comment]
I can take this on.

**Comment by wpaulino** [comment]
@mlerner might want to wait until https://github.com/lightningnetwork/lnd/pull/1910 lands.

**Comment by halseth** [comment]
#1910 is merged, there is a TODO in the fundingmanager to do this consistently check. We could also unconditionally send new announcement every restart, as long as the gossiper handle the duplicated messages.

**Comment by Roasbeef** [comment]
Seems it isn't clear if this is still an issue or not.
