### ISSUE TITLE
lnwire+channeldb+pool: extend the reader/write buffer pools to cover channeldb+lnwire

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3004]
Today we use a set of read/write buffer pools to reduce the amount of allocation that occurs doing routine operation. This tends us to a steady state of allocations, and reduce heap pressure as well. These buffer pool are used in the `brontide` package and the peer when reading/writing messages of the wire. We can also use these pools within `channeldb` when serializing and decoding message, and also within `lnwire` when decoding message. Once these two areas are covered, most allocations due to encoding/decoding will no go through these buffer pools. During the development process, we may want to re-examine the default number of workers for these buffer pools.

**Comment by Crypt-iQ** [comment]
I can look at this one, seems cool

**Comment by yyforyongyu** [comment]
I am looking into this one.

**Comment by Crypt-iQ** [comment]
`pprof` may help you here @yyforyongyu

**Comment by yyforyongyu** [comment]
> `pprof` may help you here @yyforyongyu

Cool thanks for the tip.
