### ISSUE TITLE
rpc+autopilot: allow for arbitrary predicate based channel acceptance criteria

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3005]
Today in the network, the only value a node has that can let it reject a channel is the min channel size parameter. However, there're many other constraints routing nodes may want to apply for accepting/rejecting inbound channels. Accepting an inbound channel in a single funder world is _mostly_ "free", in that you don't need to put any funds up. However, as the network matures, nodes may start to be more discerning w.r.t _which_ channels they accept. For example, a node that may want to position itself as a reliable backbone node, may only want to accept channels from other nodes with a certain channel age, or based on their connections to other node in the network. 

# Steps To Completion 

- [ ] Rather than hard code each of this individual scenarios, we should create a generic system to allow routing node operators to express any sort of criteria they want. At the `fundingManager` level, we can extend it with an interface that resembles something like:
```go
type ChannelAcceptor interface {
    Accept(node *btcec.PublicKey, req *lnwire.OpenChannel) boo
}
```

- [ ] The initial implementation would just always return `true`. As a follow up, we would then refactor the min channel size validation logic to stand behind the `Accept` method. 

- [ ] Next, a new bi-directional streaming RPC should be created. Within the default `Accept` method, if a client is active (there can only be one at a time?), then the default method should be ignored and a client query issued instead. The query should proxy the arguments to `Accept` to the client, who will then return a `bool` indicating if the channel should be accepted or not.

**Comment by Crypt-iQ** [comment]
I can take this if nobody's working on it

**Comment by Crypt-iQ** [comment]
What exactly does this have to do with autopilot (looking at the title)? I thought that autopilot just opened outgoing channels, and all incoming open channel messages were processed by the fundingmanager.  Is that correct?

**Comment by Crypt-iQ** [comment]
Can close this #3039 was merged
