### ISSUE TITLE
htlcswitch+chanCloser: enforce fee high water mark for channels

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3006]
For each channel, we should start to define a point in which we'll no longer accept or trigger fee updates for as they being to eat into the balance of the channel. In the future, we won't have any fees on the commitment transaction, as a CPFP (and later no_input) mechanism will be used to anchor down the commitment transaction. As a prep for commitment v2, we should extend the logic in the link to enforce a fee ceiling if they're the initiator, and possibly accept then coop close on the responder side if the fees exceed this limit.

**Comment by Crypt-iQ** [comment]
I can look at this
