### ISSUE TITLE
gRPC VerifyChanBackup not compatible with output of ExportAllChannelBackups

### ISSUE THREAD

**Issue by willcl-ark** [lightningnetwork/lnd#3009]
### Background

gRPC API:

`VerifyChanBackup` takes an argument `single_chan_backups` which needs to be of type `ChannelBackups` (note the ‘s’ on the end).

When I directly pass it a `ChannelBackups` object i get RPC error: `"only one Single is accepted at a time"`. The node does have two channels total...
If I dig into the ChannelBackups object and slice the first item, I see the (single) `ChannelBackup` object (note the lack of ‘s’), but this is invalid according to `VerifyChanBackup`…

`lnrpc.ChanBackupSnapshot` is expecting `lnrpc.ChannelBackups` got `lnrpc.ChannelBackup`

### Your environment

* lnd v0.6.0-beta
* OSX 
* bitcoind v0.18.0 RC4
* python gRPC

### Steps to reproduce

https://gist.github.com/willcl-ark/16bc89a0a3302ffbae5148bd030deb0d

### Expected behaviour

VerifyChanBackup should either accept iterable `ChannelBackups` objects, or otherwise accept single `ChannelBackup` objects. 

### Actual behaviour

It specifies `ChannelBackups` but does not accept them. And also will not accept `ChannelBackup` objects

**Comment by wpaulino** [comment]
Things were done this way to allow reusing some of the proto messages, although in this case it doesn't work out nicely. You need to provide a `ChannelBackups`, which is an array of `ChannelBackup`, that only contains one `ChannelBackup`.

**Comment by wpaulino** [comment]
If you want to verify multiple channels, you can use the `MultiChanBackup` field only instead.

**Comment by willcl-ark** [comment]
Thanks for your reply Wilmer @wpaulino.

While it’s possible to create these single arrays quite easily on my side, don’t you think the behaviour should be changed to be as I described above?

Multi is working great using RPC. And using the cli both single and multi-backup, verify and restore work fine; this single-as-an-array seems to be the only weak link in my opinion...

**Comment by Roasbeef** [comment]
It only accept a single backup as the response it meant to tell if you a single backup is correct or not. The response would need to be modified to return information describing _which_ backup was incorrect.

**Comment by willcl-ark** [comment]
I guess my point is that `ExportChannelBackup` returns a `ChannelBackup`, which is not accepted by `VerifyChanBackup` without repacking inside a `ChannelBackups`, and then `ExportAllChannelBackups.single_chan_backups` returns a `ChannelBackups` which is also not accepted by `VerifyChanBackup` without splitting and repacking each channel back into single `ChannelBackups` structures.

It just feels inconsistent, but if its going to stay like this I can easily write something to split ChannelBackups and to repack ChannelBackup appropriately for my RPC interface.

**Comment by guggero** [comment]
Doing some housekeeping and found this old issue. I'm not sure we can just change the RPC interface, as that would break existing clients.

> It just feels inconsistent, but if its going to stay like this I can easily write something 

Yeah, unfortunately we just have to add this to the large list of small inconsistencies in our gRPC/REST interfaces that result from organic growth of the API. But I personally feel it's way more important to not break the API on update rather than get rid of all little inconsistencies.

With that said, I'm going to close the issue. Feel free to re-open if you strongly disagree.
