### ISSUE TITLE
Implement 2-week network view pruning

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#301]
# Issue

Within the [`AuthenticatedGossiper`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L99) we currently have a period goroutine, driven by a [`time.Ticker`](https://golang.org/pkg/time/#Ticker) which re-announces the latest channel update for our set of active outgoing channels. This is done to ensure that the latest version of the current routing policy attached with each `ChannelUpdate` message. 

An amendment was recently made in the set of specifications to [recommend that nodes prune stale entries from their channel graph](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#recommendation-on-pruning-stale-entries) as it's possible for channel to become completely inactive for a variety of reasons. 

At this point, we don't yet prune these entries, so as a result, we may end of with lingering "zombie" channels. 

# Steps to Completion 

- [ ] The main `ChannelUpdate` re-broadcast loop should be modified still tick every 30 minutes, but only rebroadcast a `ChannelUpdate` iff, we "close" to the recommended 2-week interval. 

- [ ] Instead, of just reading from disk and converting to a `ChannelUpdate`, we should update the `Timestamp` field, re-sign, write the new edge policy to disk, _then_ re-broadcast to the rest of the network. Portions of the [`processFeeChanUpdate`](https://github.com/lightningnetwork/lnd/blob/master/discovery/service.go#L507) method can likely be refactored slightly as much of the code within that method can be re-used for this case.

**Comment by blico** [comment]
The description of the first step is not clear to me. Based off of the spec, I am assuming that functionality should be added to the re-broadcast loop that checks for stale channels, and prunes if necessary.

**Comment by Roasbeef** [comment]
@blico as in, it should tick every 30 minutes, but filter out the edges it re-broadcasts. It should only re-broadcast a `ChannelUpdate` message, if now minus the `Timestamp` (expressed in unix time), is "close" to 2-weeks.

Re-reading, you're partially correct as I forgot to add the third item: within that same tick, it should examine the edges of the graph, and only prune iff they haven't been updated in 2 weeks.

**Comment by blico** [comment]
Ok gotcha, thanks for the clarification. I will start working on this issue now.

**Comment by Roasbeef** [comment]
Adopted this issue after @blico did the initial work. 

Closing.
