### ISSUE TITLE
updating errors from version 0.5.2-99-beta to the latest one

### ISSUE THREAD

**Issue by okae** [lightningnetwork/lnd#3014]
### Background

while trying the normal update procedure on the last command im getting lot of errors.

on this command "make clean && make && make install"

### Your environment

* lncli version 0.5.2-99-beta commit=v0.5.1-beta-805-ga6cf6f4237ef53b1f0c51c2fcfb9c1ce73cf9e06
* Linux UB 4.15.0-47-generic 
* Bitcoin Core Daemon version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8

### Steps to reproduce

while trying the normal update procedure on the last command im getting lot of errors.

cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull
make clean && make && make install   //on this command in getting all those errors

### Expected behaviour

LND  should update without any problem like always, i did it so many times without any errors, but now im getting this issue.

### Actual behaviour

make clean && make && make install
 Cleaning source.
rm -f ./lnd-debug ./lncli-debug
rm -f ./lnd-itest ./lncli-itest
rm -f -r ./vendor .vendor-new
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.6.0-beta-47-gb63584980a5bb73583f70d58be35b072ed2bda35" github.com/lightningnetwork/lnd
github.com/btcsuite/btcwallet/internal/legacy/keystore
github.com/btcsuite/btcwallet/walletdb/bdb
github.com/lightninglabs/neutrino
github.com/lightningnetwork/lnd/lncfg
github.com/lightningnetwork/lnd/nat
# github.com/btcsuite/btcwallet/walletdb/bdb
../../btcsuite/btcwallet/walletdb/bdb/db.go:12:2: imported and not used: "github.com/coreos/bbolt"
../../btcsuite/btcwallet/walletdb/bdb/db.go:55:10: undefined: bolt
# github.com/btcsuite/btcwallet/internal/legacy/keystore
../../btcsuite/btcwallet/internal/legacy/keystore/keystore.go:2801:12: cannot use addresses (type []"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Address) as type []"github.com/btcsuite/btcutil".Address in field value
../../btcsuite/btcwallet/internal/legacy/keystore/keystore.go:2883:15: cannot use addresses (type []"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Address) as type []"github.com/btcsuite/btcutil".Address in assignment
# github.com/lightninglabs/neutrino
../../lightninglabs/neutrino/blockmanager.go:2241:35: cannot use stubBlock (type *"github.com/btcsuite/btcutil".Block) as type *"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Block in argument to blockchain.CheckProofOfWork
../../lightninglabs/neutrino/log.go:32:22: cannot use logger (type "github.com/btcsuite/btclog".Logger) as type "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger in argument to blockchain.UseLogger:
	"github.com/btcsuite/btclog".Logger does not implement "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger (wrong type for Level method)
		have Level() "github.com/btcsuite/btclog".Level
		want Level() "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Level
../../lightninglabs/neutrino/log.go:33:20: cannot use logger (type "github.com/btcsuite/btclog".Logger) as type "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger in argument to txscript.UseLogger:
	"github.com/btcsuite/btclog".Logger does not implement "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger (wrong type for Level method)
		have Level() "github.com/btcsuite/btclog".Level
		want Level() "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Level
../../lightninglabs/neutrino/log.go:34:16: cannot use logger (type "github.com/btcsuite/btclog".Logger) as type "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger in argument to peer.UseLogger:
	"github.com/btcsuite/btclog".Logger does not implement "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger (wrong type for Level method)
		have Level() "github.com/btcsuite/btclog".Level
		want Level() "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Level
../../lightninglabs/neutrino/log.go:35:19: cannot use logger (type "github.com/btcsuite/btclog".Logger) as type "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger in argument to addrmgr.UseLogger:
	"github.com/btcsuite/btclog".Logger does not implement "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Logger (wrong type for Level method)
		have Level() "github.com/btcsuite/btclog".Level
		want Level() "github.com/btcsuite/btcd/vendor/github.com/btcsuite/btclog".Level
../../lightninglabs/neutrino/query.go:960:42: cannot use block (type *"github.com/btcsuite/btcutil".Block) as type *"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Block in argument to blockchain.CheckBlockSanity
../../lightninglabs/neutrino/rescan.go:709:44: cannot use relevantTxs (type []*"github.com/btcsuite/btcutil".Tx) as type []*"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Tx in argument to ro.ntfn.OnFilteredBlockConnected
../../lightninglabs/neutrino/rescan.go:754:26: cannot use tx (type *"github.com/btcsuite/btcutil".Tx) as type *"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Tx in argument to ro.ntfn.OnRedeemingTx
../../lightninglabs/neutrino/rescan.go:770:21: cannot use tx (type *"github.com/btcsuite/btcutil".Tx) as type *"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Tx in argument to ro.ntfn.OnRecvTx
../../lightninglabs/neutrino/rescan.go:812:44: cannot use relevantTxs (type []*"github.com/btcsuite/btcutil".Tx) as type []*"github.com/btcsuite/btcd/vendor/github.com/btcsuite/btcutil".Tx in argument to ro.ntfn.OnFilteredBlockConnected
../../lightninglabs/neutrino/rescan.go:812:44: too many errors
Makefile:94: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by wpaulino** [comment]
You need to upgrade your version of Go to at least 1.11.
