### ISSUE TITLE
LND swept funds from remote force-close twice.

### ISSUE THREAD

**Issue by vegardengen** [lightningnetwork/lnd#3021]
### Background

This is not my issue, I just helped troubleshoot, and got his permission to submit it as an issue because I haven't heard of such an issue before.

lightning-app 0.5.0-beta funded a transaction that was force-closed by remote node. Local node swept it first, then tried a second time to sweep same funds, which was rejected by the network. This resulted in a bad UTXO causing most subsequent autopilot actions to fail.

### Your environment

* version of `lnd`
lightning-app 0.5.0 (LND 0.6.0-beta), release version.
* which operating system (`uname -a` on *Nix)

Windows.

* version of `btcd`, `bitcoind`, or other backend

Neutrino

* any other relevant environment detail
### Expected behaviour

Funds are swept only once.

### Actual behaviour

Funds were swept twice.

Relevant action is starting approximately 2019-04-26 21:28:04.433

[lnd.log](https://github.com/lightningnetwork/lnd/files/3124064/lnd.log)
[list.txt](https://github.com/lightningnetwork/lnd/files/3124065/list.txt)

**Comment by Roasbeef** [comment]
If it was a sweep transaction, then it's normal for us to possibly try to construct and rebroadcast a similar transaction. How have you determined that this created an invalid UTXO?

**Comment by vegardengen** [comment]
Ok, the listchaintxns that is added was the full and complete one - so that's probably the piece you are missing.

The later attempted channel with 1.9M satoshi has to be using this transaction for his wallet to believe there is this much funds in it, because no more than 1.6M satoshi was ever sent to it.

**Comment by wpaulino** [comment]
This is a combination of the sweeper aggressively rescheduling inputs and Neutrino not receiving a proper error back for an invalid transaction. There'll be some ongoing work in these areas to make them more robust. Will close this for now, you should be able to use `dropwtxmgr` to access the funds if they are locked within the invalid channel.
