### ISSUE TITLE
'describegraph' chan_point & capacity values are 0 for all channels

### ISSUE THREAD

**Issue by rstmsn** [lightningnetwork/lnd#3024]
### Background

describegraph successfully returns the json encoded representation of lnd's view of the network. 
However, the 'capacity' and 'chan_point' values for *all* channels are 0.

Example:
            "channel_id": "597094187538317312",
            "chan_point": "0000000000000000000000000000000000000000000000000000000000000000:0",
            "last_update": 1556369109,
            "node1_pub": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
            "node2_pub": "02c921ef88d90e8760b31227ccc82dd8d4bb8082d636935abcde0cde4827f1ebb9",
            "capacity": "0", 

### Your environment

* version of `lnd`
"version": "0.6.0-beta commit=v0.6-beta-31-ge8257b35ff575066a10ee658421c35897e19269e",

* which operating system (`uname -a` on *Nix)
 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Neutrino:

./lnd--bitcoin.active--debuglevel=info--lnddir=/home/info/lnd--routing.assumechanvalid--historicalsyncinterval=20m--autopilot.active--autopilot.minconfs=0--autopilot.allocation=0.95--autopilot.heuristic=externalscore:0.95--autopilot.heuristic=preferential:0.05--rpclisten=localhost:10006--listen=localhost:10016--restlisten=192.168.0.1:443--profile=9096--bitcoin.mainnet--bitcoin.node=neutrino--neutrino.connect=165.227.7.29--neutrino.connect=dev.conner.money--neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json

**Comment by wpaulino** [comment]
This is expected as a result of running with `--routing.assumechanvalid`.

**Comment by rstmsn** [comment]
> This is expected as a result of running with `--routing.assumechanvalid`.

Much obliged. Thankyou

**Comment by rstmsn** [comment]
Is relaunching with the flag removed sufficient to cause the graph database to repopulate the missing channel properties?

**Comment by wpaulino** [comment]
Unfortunately no, the graph would need to be removed and there's no user-friendly way of doing that at the moment.

**Comment by rstmsn** [comment]
would it be sufficient to delete 'channel.db' and relaunch?

**Comment by wpaulino** [comment]
`channel.db` also includes your channel state.

**Comment by rstmsn** [comment]
would this be an appropriate time to test 'exportchanbackup' ?

**Comment by wpaulino** [comment]
Your channels would be closed as result of restoring them in order to recover your off-chain balance. If you're OK with that, then feel free to do so.

**Comment by rstmsn** [comment]
is there any other way to rebuild the local channel index without having to close the channels? thanks for the help here.
