### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mraksoll4** [lightningnetwork/lnd#3028]
### Background
when i try compile with

GOOS=windows GOARCH=amd64 go build -v -o lnd.exe -ldflags "-X main.Commit=v0.6-beta" github.com/lightningnetwork/lnd

for windows

i hv this erroe

```
GOOS=windows GOARCH=amd64 go build -v -o lnd.exe -ldflags "-X main.Commit=v0.6-beta" github.com/lightningnetwork/lnd
github.com/lightningnetwork/lnd/routing/route
# github.com/lightningnetwork/lnd/routing/route
routing/route/route.go:119:4: cannot use 0 (type int) as type [1]byte in field value
```

### Steps to reproduce

at ubuntu 18.04

first i do
sudo apt install go-dep
then
wget https://dl.google.com/go/go1.12.3.linux-amd64.tar.gz
then
sudo tar -C /usr/local -xzf go1.12.3.linux-amd64.tar.gz
then
export PATH=$PATH:/usr/local/go/bin
then
go get -d  github.com/lightningnetwork/lnd
then
cd /home/ubuntu/go/src/github.com/lightningnetwork/lnd
then
dep init
then 
dep ensure -v
then 
GOOS=windows GOARCH=amd64 go build -v -o lnd.exe -ldflags "-X main.Commit=v0.6-beta" github.com/lightningnetwork/lnd

and give error

```
GOOS=windows GOARCH=amd64 go build -v -o lnd.exe -ldflags "-X main.Commit=v0.6-beta" github.com/lightningnetwork/lnd
github.com/lightningnetwork/lnd/routing/route
# github.com/lightningnetwork/lnd/routing/route
routing/route/route.go:119:4: cannot use 0 (type int) as type [1]byte in field value

```

**Comment by cfromknecht** [comment]
@mraksoll4 do you get the same error with `make`?

**Comment by cfromknecht** [comment]
The commit indicates you are trying to compile 0.6-beta, but the file referenced in the error did not exist in 0.6.

**Comment by Roasbeef** [comment]
We also don't use `dep` anymore. You'll need to build with go modules: https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-lnd

**Comment by mraksoll4** [comment]
problem was at download latest lightning-onion from master, not version from comint what was need.
