### ISSUE TITLE
Re-send FundingLocked in ChannelLink upon re-connect if at state zero

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#303]
# Issue

The current specification draft describes the process of re-synchronizing channel state upon reconnection. As transports can be unreliable, we don't have a guarantee that the remote party actually received the last update we sent before the connection was closed. As a result, upon reconnection we'll attempt to retransmit the state necessary to reconcile any possible deviations in our state. 

PR #231 implements the bulk of the retransmission logic but leaves one component un-implemented:

> If next_local_commitment_number is 1 in both the channel_reestablish it sent and received, then the node MUST retransmit funding_locked, otherwise it MUST NOT. On reconnection, a node MUST ignore a redundant funding_locked if it receives one.

# Steps to Completion 

- [ ] Upon reconnection (as an intermediate step before #231 is merge) if the current state number o is zero [within the ChannelLink's main goroutine](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L277) then the `FundingLocked` message should be reconstructed, and re-sent to the remote peer. 

    The `FundingLocked` message can be reconstructed by [obtaining the the next `commitmentPoint` from the core channel state machine](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L2967). 

- [ ] Within the [`fundingManager`](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go) when [handling the `FundingLocked` message](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1466) if this is a retransmitted message, then it should be ignored, rather than continuing normal processing. We can determine if this is a retransmission by examining the [RemoteNextRevocation](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L311) field for `nil-ness`

- [ ] Currently, within the `fundingManager`when we try to send the `FundingLocked` message to the remote party, [but they're not currently online, we simply exit early and fail to properly announce the channel](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1389).  Instead, we should send a request to the server to be notified of when the target peer comes online again. In the case the peer re-connects, then we should wait up and resume duties as normal. This is also related to #305 as we'll need to decouple channel graph insertion from channel announcement as well.

**Comment by halseth** [comment]
Taking a look at this one :)

**Comment by halseth** [comment]
Can be closed re #328 :)

**Comment by Roasbeef** [comment]
Closing.
