### ISSUE TITLE
lnd.conf optimization for raspberry pi

### ISSUE THREAD

**Issue by bereska** [lightningnetwork/lnd#3030]
### Background

Not an issue currently but rather an info-request on optimizing lnd performace on arm devices like raspberry pi, etc.
Arm devices offer a very low-cost entry level for all to bitcoin and lightning.
However pairing with bitcoind and great add-ons like BTCPay Server sucks almost all juice from these recourse-limited devices.
Is there a way to optimize lnd to use less RAM & CPU on raspberry pi without breaking anything or reducing functionality, etc?
Similar to what what can be done to bitcoind for example: -blocksonly -dbcache=20 -maxsigcachesize=4 -maxconnections=4 -rpcthreads=1

### Your environment
Linux bereskaLND 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Raspiblitz 1.1 on rpi 3b+ with:
lnd version 0.5.2-beta commit=v0.5.2-beta
Bitcoin Core Daemon version v0.17.0.1
Manually installed:
DOTNet 2.2
NBXplorer latest
BTCPay server v.1.0.3.94

**Comment by Roasbeef** [comment]
There's nothing atm, however if you upgrade to lnd 0.6-beta, then you'll find that there've been a number of _significant_ performance improvements (both memory+CPU). 0.6.1 includes even more optimizations as well.

**Comment by bereska** [comment]
thank you
