### ISSUE TITLE
Documentation: How current is the channel state written to disk?

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#3033]
This is not a technical issue, but a lack of documentation (or me being unable to find it). Aside from the code, I mean.

I'd like to find out what kind of channel state information is written to disk, and what is left out. Can it happen that a HTLC is settled without having that information on disk? What's the worst case scenario of a sudden power loss? How would RAID 1 or replication techniques like DRBD help? Would lnd use an old state after a sudden reboot? Is using SCB recovery the only safe way to go, or would the file on disk still be helpful?

**Key question:** Is there is a guarantee that the disk version of the channel state is updated first to destroy the obsolete state?

This is related to consistency, disk barriers, flushes, caches, buffers, ...

**Comment by Roasbeef** [comment]
Updates are always made locally before flushing them out to the network. Worst case in the scenario of sudden power loss is corruption (depending on the storage medium). Replicating the file system on the block storage level may be safe depending on if all writes are synchronous amongst the replicas. `lnd` won't use an old state after a reboot if the state on disk is consistent. Robust distributed replication at the block storage level for a file system will be secure if writes are synchronous and durable. The details of this depend on the file system, operating system, replication protocol, and storage devices along with their peripherals. `lnd` uses `boltdb` which is based on `lmdb` and implements concurrency control via MVCC on top of a b+tree.
