### ISSUE TITLE
LTC seeks BTC macaroon

### ISSUE THREAD

**Issue by P0u1us** [lightningnetwork/lnd#3036]
Hi, just wondering if it was ever noticed or reported ;-)

I have successfully setup 2 servers: 1 for BTC-LN and 1 for LTC-LND
it all works with 1 curious thing:
whenever you want to perform lncli stop on the LTC-LND server:
it throws an error (sorry I didnt record it :(
but what it seeks at that moment is the admin.macaroon in the data/chain/mainnet/bitcoin/ folder !
when I make a copy of admin.macaroon from data/chain/mainnet/litecoin/ to mainnet/bitcoin
all works properly ;-)

### Your environment
Ubuntu 18.04

**Comment by wpaulino** [comment]
This is the expected behavior for now, `lncli` defaults to bitcoin mainnet. If you'd like to use a different chain and/or network, you'll need to use the `--chain` and/or `--network` flags respectively.
