### ISSUE TITLE
How  up own dns seed ?

### ISSUE THREAD

**Issue by mraksoll4** [lightningnetwork/lnd#3037]
### Background

i try this 
https://github.com/Roasbeef/lseed
 but hv this error
```
DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]]: dial tcp 127.0.0.1:53: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2019-05-03 20:02:09.045 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]] 
```

### Steps to reproduce

i was redirect to 127.0.0.1 this dns for test and run 
```
127.0.0.1                   soa.nodes.lightning.directory
127.0.0.1                   ltfn.nodes.lightning.directory
```

```
C:\lnd>lseed -ltc-lnd-node 127.0.0.1:10009 -root-domain ltfn.nodes.lightning.directory -ltc-tls-path C:\Users\V\AppData\Local\Lnd\tls.cert  -ltc-mac-path C:\Users\V\AppData\Local\Lnd\data\chain\litecoin\mainnet\admin.macaroon -listen 127.0.0.1:53
[36mINFO[0m[0000] Creating LTC chain view
[36mINFO[0m[0000] Checking Node(03ceda0c98f9cb5c1089e8b63f90dafa1a4ae52333db4f3ebc64e63839a6b3f975) (litecoin) for reachability @ 127.0.0.1:9735
[36mINFO[0m[0000] Node(03ceda0c98f9cb5c1089e8b63f90dafa1a4ae52333db4f3ebc64e63839a6b3f975) (litecoin) is reachable number of reachable nodes: 1
```

bul when it tre connect i hv this error

```
DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]]: dial tcp 127.0.0.1:53: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2019-05-03 20:02:09.045 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]]
```

**Comment by wpaulino** [comment]
There's currently no way to specify an alternate DNS seed for bootstrapping. Do you have a custom DNS server set on your computer/network, e.g. Cloudflare's `1.1.1.1`? I know some people have had issues when doing so.

**Comment by mraksoll4** [comment]
I was recompile it with other server , and try by using http://freedns.afraid.org connet to seed for test

but not give anyting than 

```
ubuntu@ubuntu:~$ dig a2.node.mooo.com SRV

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> a2.node.mooo.com SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56857
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;a2.node.mooo.com.		IN	SRV

;; ANSWER SECTION:
a2.node.mooo.com.	1	IN	SRV	10 10 9735 a2.node.mooo.com.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri May 03 21:35:05 EEST 2019
;; MSG SIZE  rcvd: 70

```
```


		litecoinMainnetGenesis: {
			{
				"ltc.nodes.lightning.directory",
				"soa.nodes.lightning.directory",
changet to
				"a2.node.mooo.com",
				"a2.node.mooo.com",
			},
		},
	}
```

**Comment by wpaulino** [comment]
If you recompiled, then perhaps you're still using the old binary as I still see it querying for the original DNS seeds:

> bul when it tre connect i hv this error
>
> DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]]: dial tcp 127.0.0.1:53: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2019-05-03 20:02:09.045 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 20:02:09.045 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.lightning.directory soa.nodes.lightning.directory]]

**Comment by mraksoll4** [comment]
```
2019-05-03 21:35:09.983 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 21:35:09.983 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[a2.node.mooo.com a2.node.mooo.com]]
2019-05-03 21:35:09.986 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[a2.node.mooo.com a2.node.mooo.com]]: dial tcp xxx.xxx.xxx.xxx:53: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2019-05-03 21:35:09.986 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 21:35:09.986 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 21:35:09.986 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 21:35:09.986 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[a2.node.mooo.com a2.node.mooo.com]]
```

**Comment by mraksoll4** [comment]
i try different way
![1111ssss](https://user-images.githubusercontent.com/32709596/57161841-34195000-6df5-11e9-9c80-9ec89be79c9a.jpg)


```
2019-05-03 22:39:28.955 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 22:39:28.955 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-05-03 22:39:28.955 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-05-03 22:39:28.955 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[node.testxxxx.cf soa.testxxxx.cf]]
2019-05-03 22:39:28.958 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[node.testxxxx.cf soa.testxxxx.cf]]: dial tcp xxx.xxx.xxx.xxx:53: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
```
C:\lnd>lseed -ltc-lnd-node 127.0.0.1:10009 -ltc-tls-path C:\Users\V\AppData\Local\Lnd\tls.cert -ltc-mac-path  C:\Users\V\AppData\Local\Lnd\data\chain\litecoin\mainnet\admin.macaroon -root-domain node.testxxxx.cf
[36mINFO[0m[0000] Creating LTC chain view
[36mINFO[0m[0000] Checking Node(03ceda0c98f9cb5c1089e8b63f90dafa1a4ae52333db4f3ebc64e63839a6b3f975) (litecoin) for reachability @ 127.0.0.1:9735
[36mINFO[0m[0000] Node(03ceda0c98f9cb5c1089e8b63f90dafa1a4ae52333db4f3ebc64e63839a6b3f975) (litecoin) is reachable number of reachable nodes: 1

```

**Comment by Roasbeef** [comment]
Looks like you need to increase the number of open file descriptors allowed on your system. You need to set the "soa" domain to the IP address of the DNS server itself.

**Comment by mraksoll4** [comment]
soa. is at A record  to ip where runing lseed
node. is madet as NS to domiadn redirected by A to ip.

**Comment by mraksoll4** [comment]
```
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.     
ERRO[0075] srv no chain view found for _nodes._tcp.
```

**Comment by mraksoll4** [comment]
now no errors but stil not work , how i undestand lseed is broken. its no give any data to nodes about peers.

**Comment by mraksoll4** [comment]
the promlem notiing not even accept doing , node.domian.coin ns  and make at it sub domian and put A record. How its comfigurated at nodes.lightning.directory ? 

```
DEBU[0713] Dispatching request for sub-domain _nodes._tcp.nodes.
DEBU[0713] Incoming request                              subdomain=_nodes._tcp.nodes. type=SRV
ERRO[0713] srv no chain view found for _nodes._tcp.nodes.
DEBU[0713] Replying with 0 answers and 0 extras (len=43)  replies=0
DEBU[0713] Dispatching request for sub-domain _nodes._tcp.nodes.
DEBU[0713] Incoming request                              subdomain=_nodes._tcp.nodes. type=SRV
ERRO[0713] srv no chain view found for _nodes._tcp.nodes.
DEBU[0713] Replying with 0 answers and 0 extras (len=43)  replies=0
DEBU[0713] Dispatching request for sub-domain _nodes._tcp.nodes.
DEBU[0713] Incoming request                              subdomain=_nodes._tcp.nodes. type=SRV
ERRO[0713] srv no chain view found for _nodes._tcp.nodes.

```

**Comment by mraksoll4** [comment]
Sorry go i reopen it , but please answer and close. Its realy no where find answer :/

**Comment by mraksoll4** [comment]
What you was use , and what protocols configueated.

**Comment by mraksoll4** [comment]
its always givin me error.

> 
> RRO[0310] srv no chain view found for _nodes._tcp.
> DEBU[0310] Replying with 0 answers and 0 extras (len=43)  replies=0
> DEBU[0310] Dispatching request for sub-domain _nodes._tcp.
> DEBU[0310] Incoming request                              subdomain=_nodes._tcp. type=SRV
> ERRO[0310] srv no chain view found for _nodes._tcp.
> DEBU[0310] Replying with 0 answers and 0 extras (len=43)  replies=0
> DEBU[0310] Dispatching request for sub-domain _nodes._tcp.
> DEBU[0310] Incoming request                              subdomain=_nodes._tcp. type=SRV
> ERRO[0310] srv no chain view found for _nodes._tcp.
> DEBU[0310] Replying with 0 answers and 0 extras (len=43)  replies=0
> DEBU[0310] Dispatching request for sub-domain soa.
> DEBU[0310] Incoming request                              subdomain=soa. type=None
> DEBU[0310] Replying with 1 answers and 0 extras (len=68)  replies=1
>

**Comment by mraksoll4** [comment]
> 019-05-05 22:11:34.921 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.ltfn.cf soa.nodes.ltfn.cf]]
> 2019-05-05 22:11:34.927 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[ltc.nodes.ltfn.cf soa.nodes.ltfn.cf]]: lookup ln1q0zzemevv273q6txv3dy84kzaug9tjq5g5nak9v5w0uxs48tyql0v9me5q4.ltc.nodes.ltfn.cf. on 8.8.8.8:53: no such host
> 2019-05-05 22:11:34.927 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
> 2019-05-05 22:11:34.927 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
> 2019-05-05 22:11:34.927 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.ltfn.cf soa.nodes.ltfn.cf]]
> 2019-05-05 22:11:34.932 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[ltc.nodes.ltfn.cf soa.nodes.ltfn.cf]]: lookup ln1q0zzemevv273q6txv3dy84kzaug9tjq5g5nak9v5w0uxs48tyql0v9me5q4.ltc.nodes.ltfn.cf. on 8.8.8.8:53: no such host
> 2019-05-05 22:11:34.932 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
> 2019-05-05 22:11:34.933 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
> 2019-05-05 22:11:34.933 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[ltc.nodes.ltfn.cf soa.nodes.ltfn.cf]]
>
