### ISSUE TITLE
Implement persistent HTLC expiry decayed Sphinx packet replay protection

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#304]
# Issues 

[Our implementation](https://github.com/lightningnetwork/lightning-onion) of [Lighting's onion routing protocol](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md) critically depends on proper replay protection in order to deliver on its privacy guarantees. Otherwise, an attacker can inject a prior HTLC into the network to attempt to re-trace its path in the case it has compromised one or more nodes within a potential path. 

Currently, we implement a basic version of replay protection backed by [non-persistent storage](https://github.com/lightningnetwork/lightning-onion/blob/master/sphinx.go#L677) within the `sphinx.Router` struct. This insufficient as if the daemon restart, then it will be susceptible to propagated replays as it's forgotten all the prior shared secrets. Additionally, as is now this storage is never reclaimed. We can reclaim this storage as HTLC's have a set _expiration_ date, past that expiration date we no longer need to remember the shared secret once an HTLC as expired as [we'll reject it within the state machine if it's already expired](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1186). 

We'll need to implement a persistent, decaying shared-secret log in order to properly implement replay protection. 

# Steps to Completion 

- [ ] Reject HTLC's which expire a period deemed too far in the future. We already ensure that they exactly meet our time lock delta parameters, but this measure will ensure that we don't even accept such HTLC's. This is critical as otherwise this presents a DoS vector against the persistent shared secret log. 

- [ ] Create a new on-disk data-structure implementing a persistent, decayed shared secret log. This should likely stand behind a new interface created that will replace the current [`sharedSecret map`](https://github.com/lightningnetwork/lightning-onion/blob/master/sphinx.go#L610) in the `sphinx.Router`. 

    We have two options here:

    1. Re-use `boltdb` for the persistent log. A struct wrapping `channeldb` would implement to to-be-created interface in the `lightning-onion` repo. This is the easiest path forward likely but would increase write contention as we'd need an additional write for each HTLC processed, though they could be batched. 
    2. Implement an on-disk replay protection log for _each_ channel implemented as a flat file. This would involved linearly scanning the file, but periodic checkpoints which contain skip pointers to later sections would allow searches to be short circuited. 

    In either case, the format of the on-disk structure would be: `(sharedHash, expiryHeight)`. Within the `sphinx.Router` we'd consult this rather than the current on-disk map. Where `sharedSecretHash = sha256(sharedSecret)[:20])`. Rather than writing the raw shared secret to disk, we instead write a truncated sha256 hash of it. By doing this, we avoid writing sensitive data (the shared secret) to disk, and also save a bit of space by truncating to 20 bytes instead of 32 bytes. 

- [ ] Create a persistent goroutine that garbage collects entries within the log. When `currentHeight > expiryHeight`, the entry can safely be removed from the on-disk storage.

**Comment by Crypt-iQ** [comment]
I would like to take this if that's ok
