### ISSUE TITLE
ver0.6 LND  service not running

### ISSUE THREAD

**Issue by vamp111** [lightningnetwork/lnd#3042]
LND service not running

on a Raspiblitz 1.2
lnd 0.6
Win10 x64

happened after upgrading to lnd 0.6 before this node was inactive for 29 days

256 RESTARTS DETECTED - LND might be in a error loop
1556943302 ERROR: LND RPC is not responding. LND may have problems starting up. Check logs, config files and systemd service. **Org-Error: [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

LND logs:
https://termbin.com/hvsf
https://termbin.com/oy81q

DeBug log:
https://termbin.com/siy8

Add:
https://termbin.com/8sqb

https://termbin.com/e0x0

**Comment by fluidvoice** [comment]
already logged as Raspiblitz issue where I said it looks like a disk I/O error: https://github.com/rootzoll/raspiblitz/issues/565#issuecomment-489339538

**Comment by Roasbeef** [comment]
This just means that the RPC server isn't yet running.

**Comment by Roasbeef** [comment]
> critical target error

That means you have a bad sector on your file system.

**Comment by vamp111** [comment]
> > critical target error
> 
> That means you have a bad sector on your file system.

any idea, what can i do to resolve it, I cant access my funds i have somewhat 25 chanels open with 0.18 BTC locked.

**Comment by fluidvoice** [comment]
> > > critical target error
> > 
> > 
> > That means you have a bad sector on your file system.
> 
> any idea, what can i do to resolve it, I cant access my funds i have somewhat 25 chanels open with 0.18 BTC locked.

Reinstall Raspiblitz and restore your wallet as per the documentation: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-can-i-recover-my-coins-from-a-failing-raspiblitz

**Comment by vamp111** [comment]
ok, but my LND was inactive for the past 29 days (or even maybe more) Im not sure the last data will be correct, couldn't that result in loss of funds?

**Comment by vamp111** [comment]
after running e: lncli unlock && lncli exportchanbackup --all --output_file /mnt/hdd/lnd/data/chain/bitcoin/mainnet/channel.backup
and confirming by password i get the following error:

 [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by vamp111** [comment]
after running e: lncli unlock && lncli exportchanbackup --all --output_file /mnt/hdd/lnd/data/chain/bitcoin/mainnet/channel.backup
and confirming by password i get the following error:

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by fluidvoice** [comment]
> after running e: lncli unlock && lncli exportchanbackup --all --output_file /mnt/hdd/lnd/data/chain/bitcoin/mainnet/channel.backup
> and confirming by password i get the following error:
> 
> [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

ah yeah, sorry. I didn't realize it won't run if `lnd` is not running. So that won't help you.

**Comment by vamp111** [comment]
> > after running e: lncli unlock && lncli exportchanbackup --all --output_file /mnt/hdd/lnd/data/chain/bitcoin/mainnet/channel.backup
> > and confirming by password i get the following error:
> > [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
> 
> ah yeah, sorry. I didn't realize it won't run if `lnd` is not running. So that won't help you.
> Follow the directions in the FAQ?

thats my latest debug log: https://termbin.com/z9ug

I dont have undervoltage or high temp. warning like I did before, yet again I ran out of options to start the LND service

from FAQ tried different methods, for example migrating from Raspi to LND Desktop app, it didn't worked..

also since i lack a channel.backup file, reinstalling a fresh copy of the Raspi will result in loss of funds I guess.

currently looking for a way to force close all chanels, wait 48hrs and try to recover with the mnemonic, but really dont know how this would happen

**Comment by wpaulino** [comment]
The channel backups don't exist because the server needs to be able to properly start, which seems to not be the case with both of you. @vamp111 since you had database corruption before upgrading to v0.6, I don't see an easy way of recovering your off-chain funds.

**Comment by vamp111** [comment]
Thanks @wpaulino i'm aware now, im discussing this with @rootzoll

just a theoretical question. If all my channel parties, force close the channels with me, will after 48hrs the funds be available on-chain and recovarable with the 24 word seed?

**Comment by wpaulino** [comment]
No because you'd still need to sweep the output yourself and you lost data -- it doesn't pay directly to a wallet address you control. You'd be able to do so if you had static channel backups though.

**Comment by vamp111** [comment]
but I don't have... so basicly I should say farewell to my funds

**Comment by vamp111** [comment]
maybe working with the wallet.db file?
