### ISSUE TITLE
Implement block-based grace period for channel announcements 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#305]
# Issue 

Atm, as soon as a channel has reached the specified number of confirmations, then [we _immediately_ announce it to the network](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1355). Instead of the immediate announcement, we should be following the specification's prescription to wait until [the funding transaction has reached _at least_ 6 confirmations](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#requirements). 

# Steps to Completion 

- [ ] Fixing this will require decoupling the [`waitForFundingConfrimation` method](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1259) from the announcement of the channels themselves. However, by announcement we only mean broadcasting the series of channel announcement messages to the greater network. 

- [ ] [As soon as the `FundingLocked` message is sent](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1378), we should _still_ be immediately adding the new channel to our internal channel graph so it can become visible to the `ChannelRouter` during path finding.

**Comment by Crypt-iQ** [comment]
I can do this one.

**Comment by Roasbeef** [comment]
@Crypt-iQ it doesn't require them, but makes sense to work on the others in tandem as they touch the same part of the codebase, and slight refactors in one will likely make it easier to do the rest.

**Comment by Roasbeef** [comment]
Closed by #411.
