### ISSUE TITLE
--help does not show how to use debuglevel

### ISSUE THREAD

**Issue by dscotese** [lightningnetwork/lnd#3051]
### Background

This is similar to #1772, which was about lnd.  lncli also suffers from the defect of lncli debuglevel=show not working:
` lncli debuglevel=show
No help topic for 'debuglevel=show'

### Your environment
Version: 0.6.0-beta commit=v0.6-beta-rc3-32-g7a0c9f33bc49c123024e0993e32154cae616ae8c
Linux version 4.15.0-47-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
bitcoind that provides bitcoin-cli version Bitcoin Core RPC client version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8

### Steps to reproduce

Try `lncli debuglevel=show`
This should return a list of valid values to be placed after `lncli debuglevel=` in order to alter the debug log level while lnd is running.  Instead of the list, we get `No help topic for 'debuglevel=show'`

**Comment by wpaulino** [comment]
`debuglevel` is the subcommand, `--show` is the flag. The command is `lncli debuglevel --show`.
