### ISSUE TITLE
htlcswitch: clean up forwarding state from closed channels

### ISSUE THREAD

**Issue by cfromknecht** [lightningnetwork/lnd#3052]
## Background

In the process of forwarding HTLCs, LND maintains two persistent data structures in order to offer high throughput and crash tolerance.

The first is the [`CircuitMap`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/circuit_map.go), which maintains a record of incoming (ChannelID, HtlcID) to outgoing (ChannelID, HtlcID). This allows it to determine where a Settle/Fail message should return, and also ensure at most one HTLC is ever sent out for a particular incoming HTLC. The circuit map provides insight at the core of the forwarding process, when LND internally moves an HTLC from the incoming to outgoing channel.

The second is a series of _forwarding packages_ ([FwdPkg](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_package.go#L195)), which records all HTLCs that are added or removed by a particular commitment transaction. One such record is maintained by each channel for every commitment height. These records are updated atomically when updating channel states, and provide persistent insight into the ingress and egress of HTLCs at the perimeter of the daemon wrt the view of the channel's commitments.

## Issue

Under normal operation, records from both the `CircuitMap` and `FwdPkgs` are removed when they 
become unnecessary. However, this can only be done if the channel is active in the `htlcswitch`. When a channel is closed, LND prevents those channels from ever being loaded back into the switch, to prevent any accidental state updates from occurring and risking any sort of channel breach.

Therefore, the current design leaves some of the forwarding state behind when channels are closed. The total amount of data is small relative to the other data maintained by LND, but it is ideal that we clean up after ourselves and free up the disk space.

## Steps to Completion (`FwdPkg` Cleanup)

- [ ] Create a `Wipe` method on the [`ChannelPackager`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_package.go#L411) which deletes the top level bucket for the given channel's forwarding logs
- [ ] When a channel is closed via [`CloseChannel`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L2038), the channel's forwarding packages should be cleaned up by invoking the `Wipe` method on its `ChannelPackager`
 - [ ] Add a migration to clean up any forwarding packages for channels that have been closed prior, yet still have a top-level forwarding package bucket

## Steps to Completion (`CircuitMap` Cleanup)

On startup, when restoring the circuit map state from disk in [NewCircuitMap](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/circuit_map.go#L185):
 - [ ] Determine the set of channels that have been closed
 - [ ] Remove all _circuits_ from the circuit bucket whose _key_ prefix matches a short channel id in the set of the closed channels
 - [ ] Remove any _keystones_ from the keystone bucket whose _key_ prefix matches a short channel id in the set of closed channels
 - [ ] Ensure _never_ to remove keys whose prefix is the zero-value short channel id, this deletes state for locally initiated payments. We should be defensive by including this check in the `CircuitMap`. It is too risky to assume that the short channel id field is always correct, e.g. some channels may have never confirmed (and never assigned a proper short chan id) but are now closed.

Note: In theory, we can do better than only cleaning the circuit map on restarts, however channel closures aren't very frequent and the amount code required to do so live probably doesn't warrant the complexity unless it becomes an issue in the future.

## WARNING

Please DO NOT test this on a mainnet node until it has undergone sufficient review. This cleanup requires modifying extremely critical code, and minor bugs can lead to completely irrecoverable loss of forwarding state. 

## Notes

This issue could technically be broken up into two, though given the amount of interplay between the the circuit map and forwarding packages I think it'd be best to review the changes as a whole to make sure nothing is missed.

**Comment by Crypt-iQ** [comment]
I thought that `bbolt` didn't actually free up disk space when deleting? Just made all of the nodes in the B+ tree "free" but no compaction of any sort was done.

**Comment by yyforyongyu** [comment]
i'm working on this one
