### ISSUE TITLE
routing: payment fails if block mined while htlc is in flight

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#3055]
### Background

Currently the sender of a payment builds a route that delivers a final htlc to the receiver at exactly the invoice final cltv delta. This assumes that while the htlc is on its way towards the receiver, no block is mined. If a new block does arrive, the payment fails with a `FinalExpiryTooSoon` error.

Assuming it takes on average 5 seconds for an htlc to arrive at the receiver and blocks come in every 600 secs, about 1% of the payments are expected to fail because of this.

### Your environment

* lnd 0.6.1-rc2
* linux
* bitcoind v0.17

### Steps to reproduce

* Setup a three node network Alice -> Bob -> Charlie
* Modify Bob so that it delays forwarding the htlc for 30 seconds
* Send a payment Alice -> Charlie via Bob
* When Bob enters the delay, mine a block

### Expected behaviour

Payment succeeded.

### Actual behaviour

Payment fails with `FinalExpiryTooSoon`.

### Fix suggestions
1. Pad the route that Alice constructs with one block.
2. Alternatively, retry the payment.

**Comment by Crypt-iQ** [comment]
Taking this one

**Comment by joostjager** [comment]
For this issue, it would be good to discuss the fix approach early. Suggestion one, two or something else?

**Comment by Crypt-iQ** [comment]
I think the fix should use suggestion one.  I think it's as simple as adding one to both of these lines
https://github.com/lightningnetwork/lnd/blob/f8c824fb1d6c5ef8524148f59ea5650af65af98b/routing/pathfind.go#L140-L142 in the form of some const called `BlockPadding` or something.  Then all of the failing unit / integration tests would need to be updated.

Alternatively, if [this](https://github.com/lightningnetwork/lnd/issues/1222) were implemented, a side effect would be that no `BlockPadding` const would be needed.

**Comment by joostjager** [comment]
I also prefer suggestion one. Maybe we should add the padding already outside of `newRoute` to `finalCLTVDelta`, to keep the functionality of `newRoute` clear.

Selection of the value of `BlockPadding` may be good to finalize before fixing tests, to prevent double work.

**Comment by Crypt-iQ** [comment]
Do you think the value of `BlockPadding` should be something higher just in case?  In case of reorgs or blocks found in quick succession?  I think `6` would be acceptable.

**Comment by joostjager** [comment]
Normally the process of getting the htlc at the receiver should be quick. Like seconds. From that perspective, one or two blocks should be enough. We can just start with that and increase if needed after this is in.
