### ISSUE TITLE
NodeAnnouncement not being sent

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#3058]
If we open a channel between two nodes `A` and `B`, the node that receives the `AnnounceSignatures` message second will likely not send out its `NodeAnnouncement` message to the opposite peer.  This can be seen by running lnd with `-d PEER=debug` and examining that one of the peers does not have the log message starting with `Sending NodeAnnouncement`

Let's say `B` sends out `AnnounceSignatures` first.  This issue then arises because when `B` [sends out their `AnnounceSignatures` message followed by their `NodeAnnouncement` message](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L2679), their node is not public according to this check here since it hasn't yet received the other half of the channel proof:
https://github.com/lightningnetwork/lnd/blob/c4415f04008c70be20b42f85e1ceff3ef99614c2/discovery/gossiper.go#L1526

Node `A` on the other hand, will most likely (barring the same race condition happening) send out their `NodeAnnouncement` given that it has the full channel proof before sending it out.

A side effect of this is that peers connected to `A` may not see the `NodeAnnouncement` from `B`.  I.e. if we have a graph that looks like
```
Z ---- A ---- B
```
then Z will not receive B's node announcement.

**Comment by wpaulino** [comment]
This would only happen in the case of a node opening it's first public channel, so it's not too crucial of an issue. https://github.com/lightningnetwork/lnd/pull/2084 would also allow us to rebroadcast it if the node decides not to open any other channels.

**Comment by Crypt-iQ** [comment]
Yeah good point on the first public channel.  Although it's possible they open another channel and the announcement isn't broadcast b/c it's a coin flip but it gets less and less likely with more open channels.

**Comment by Crypt-iQ** [comment]
Update: My original comment wasn't entirely accurate. If ANY lnd node receives the remote `AnnounceSignatures` message after already sending it out, no `NodeAnnouncement` message will be sent.  This is because of the previously mentioned check `IsPublicNode` and also because https://github.com/lightningnetwork/lnd/blob/c4415f04008c70be20b42f85e1ceff3ef99614c2/discovery/gossiper.go#L2326-L2330 where source is set to the `AnnounceSignatures` sender.  So when a node attempts to broadcast these messages, it won't send to the channel peer since they were set as the sender of these messages:
https://github.com/lightningnetwork/lnd/blob/c4415f04008c70be20b42f85e1ceff3ef99614c2/discovery/syncer.go#L1055-L1057 

I also noticed that the `ChannelAnnouncement` here isn't actually sent out to the channel peer:
https://github.com/lightningnetwork/lnd/blob/c4415f04008c70be20b42f85e1ceff3ef99614c2/fundingmanager.go#L2147-L2150 
In the case that a node receives the `AnnounceSignatures` method after sending it out, a `ChannelAnnouncement` message will not be sent to the channel peer.  I don't think this is a big deal, but thought I'd point it out.  Basically, it's possible for channel peers to not exchange `ChannelAnnouncement` / `NodeAnnouncement` messages.

**Comment by wpaulino** [comment]
> where source is set to the AnnounceSignatures sender

In order to get around this, we could determine which node announcement belongs to us and set the source to ourselves to ensure we at least send it out to our channel peer due to the existing race condition with `IsPublicNode`, which seems a bit more involved to tackle. Thoughts @halseth?

**Comment by halseth** [comment]
Not sending the `ChannelAnnouncement` to your channel peer is by design, since they can already craft it themselves.

> where source is set to the AnnounceSignatures sender
This seems to be the main issue here, and I think it is as easy as just setting the source to the owner of the `NodeAnnouncement`?

**Comment by Crypt-iQ** [comment]
Yeah I think that's all that needs to be done.  Is it the case that we want to ensure that no `ChannelAnnouncement` is sent to the channel peer? Because it's sent in the same broadcast with the `NodeAnnouncement` + `ChannelUpdates` when receiving your local `AnnounceSignatures` second.  There's no side effect to sending it, but since it's not necessary why bother?

**Comment by halseth** [comment]
I don't think it hurts sending it (not changing the current behavior) :)
