### ISSUE TITLE
Observe channel announcement preference during channel funding workflow 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#306]
# Issue 

During the funding workflow process, the initiator of the workflow [signals a bit to indicate if this channel should be announced to the network or not](c627c21cc1e6a58987ad6995172ce1ec3a32fdb361dcda7e6cbfec836e547c97). At this point, we don't currently observe this bit, and will instead [_unconditionally_](https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L1355) announce the channel to the network. Instead, we should observer the LSB of the [`ChannelFlags`](https://github.com/lightningnetwork/lnd/blob/master/lnwire/open_channel.go#L100) field within the `OpenChannel` message to determine if the channel should be announced or not. 

Related to #305 as we'll also still need to insert the new channel into the channel graph so the `ChannelRouter` can still use the channel for path finding.

**Comment by Crypt-iQ** [comment]
I can also take this since it's related to #305

**Comment by Roasbeef** [comment]
Closed by #411.
