### ISSUE TITLE
Can't unlock wallet - certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by tim222tim** [lightningnetwork/lnd#3078]
### Background

I stopped lnd and then upgraded bitcoind to v18. When finished, after restarting bitcoind, I restarted lnd and got the following error unlocking the wallet:

`
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"
`

No changes were made to my configuration.

### Your environment

*  lnd version: 0.6.0-beta commit=v0.6.0-beta-72-g1387af8c9461ae23f735c240284e0d90a2b2cc47, build=production, logging=default
* Ubuntu 16
* bitcoind 18

### Steps to reproduce

lncli unlock

**Comment by molxyz** [comment]
@tim222tim  delete tls.cert and tls.key, restart lnd. It will recreate a new tls pair for you.

**Comment by tim222tim** [comment]
That did it. Thanks!

**Comment by Roasbeef** [comment]
Yeah it's been a year or so since we launched on mainnet, and the default expiration for the original certs created was around that time. There's a PR with a proposed fix (auto regen on restart) that we're considering: https://github.com/lightningnetwork/lnd/pull/3011

**Comment by tim222tim** [comment]
Thanks @Roasbeef !

**Comment by waffi121** [comment]
i don't want to open a new thread because i have the same problem.

I updated from lnd 0.8 to 0.8.1 and if I want to get info with "lncli getinfo" I get the same error message. 

can i also delete the tls.cert and tls.key to solve the problem?

thank you!

**Comment by guggero** [comment]
@waffi121 yes, you can try the same.

**Comment by sangaman** [comment]
I ran into this again and resolved the issue by deleting tls.cert and tls.key, then restarting lnd.

**Comment by pseudozach** [comment]
sorry to comment on a closed issue but the problem with this is that a running LND instance fails to respond to any command if certificate expires "while it's running" so I had to force kill the lnd process. Not sure if that could cause any problems. it didn't so far...

**Comment by guggero** [comment]
As long as you just send the normal kill (SIGINT and not `-9` to forcefully kill with SIGKILL) it should shut down normally, as if you pressed `Ctrl+C` in the console.

**Comment by pseudozach** [comment]
@guggero that's what I did. thanks! it's great to know.
