### ISSUE TITLE
lnd error 

### ISSUE THREAD

**Issue by btc21cluib** [lightningnetwork/lnd#3079]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by btc21cluib** [comment]
Background
raspiblitz 1.2
Describe your issue here.
LND service error
Your environment
rasberry 
version of lnd
6.0
Steps to reproduce
when I start my RaspiBlitz 1.2 
The LND service is running with error.
lnd unlock permanently   

debug log
https://termbin.com/dl10

**Comment by wpaulino** [comment]
It fails with start with the following error:

`2019-05-15 08:13:49.883 [ERR] SRVR: unable to create server: unable to read bucket for chain=f0b74181eeff906b6c254d475c7d5ff85793e29bd757f4eee96eb41148fa338c00000001`

That hash is meant to be the bitcoin genesis block hash, but that doesn't seem to be the case, which would likely indicate some type of database corruption.

**Comment by btc21cluib** [comment]
Ok - Thank you for your response, but how can I repair this database corruption? When I create a new wallet is all working, but after i recover my old Walter with the same blockchain-data,  I got this error again.

**Comment by fluidvoice** [comment]
> Ok - Thank you for your response, but how can I repair this database corruption? When I create a new wallet is all working, but after i recover my old Walter with the same blockchain-data, I got this error again.

I think this corruption is with the bitcoin blockchain DB not LND.  So follow the Raspiblitz doc and FAQ for recovery and/or re-install.

**Comment by wpaulino** [comment]
> i recover my old Walter with the same blockchain-data, I got this error again.

Can you clarify what you mean by this? Are you using the same `channel.db`?

**Comment by btc21cluib** [comment]
@wpaulino  no I start with a fresh wallet like declares  here: 1) Recover LND datahttps://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#1-recover-lnd-data

**Comment by wpaulino** [comment]
Taking a glance at the backup script, it seems to just be backing up the current data. So if that's already corrupted, then yes you will still be seeing the same issue. You might want to try this https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#2-recover-from-wallet-seed instead.

Closing as it's just another database corruption issue.
