### ISSUE TITLE
Allow no authentication when binding to private non-routable addresses

### ISSUE THREAD

**Issue by dieeasy** [lightningnetwork/lnd#3080]
### background

I'm running lnd in docker.
It was running on 0.6, upgraded to 0.6.1 and it won't start anymore.

### environment

* `debian` stretch (with backported kernel)
* `docker` / docker-compose
* `bitcoind` 0.17.1
* `lnd` v0.6.1-beta
* `testnet`

### steps to reproduce

The issue should appear anytime lnd is ran with `--no-macaroons` and `--rpclisten=0.0.0.0:10009`.

For clarity, this is the final lnd cmdline:
```
lnd --lnddir=/lnd/path --bitcoin.active --bitcoin.testnet --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=******** --bitcoind.rpcpass=******** --externalip=lnd.example.com:9735 --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --debuglevel=info --alias=node_alias --color=#RRGGBB --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --tlsextraip=127.0.0.1 --tlsextradomain=lnd --no-macaroons
```

Tried setting the rpclisten address to a domain name, so it could be resolved at runtime to the private IP address of the docker container. The obtained IP address was in the 172.16.0.0/12 range as expected but lnd would still refuse to start.

### expected behaviour

I expected lnd to just run when upgrading from 0.6 to 0.6.1.

Also I think it should run when binding to non-routable IP addresses in the RFC1918 private ranges.

Alternatively, I would expect an option to silence this check when the user knows the instance is not publicly accessible.

As an example, in my case the 10009 port is not exposed to the host nor the Internet and is only accessible by other docker containers in the same docker network (a Lighter instance in my scenario).

### actual behaviour
lnd refuses to start and logs:
```
Detected RPC server listening on publicly reachable interface a.b.c.d:10009 with authentication disabled! Refusing to start with --no-macaroons specified.
```

**Comment by wpaulino** [comment]
> Also I think it should run when binding to non-routable IP addresses in the RFC1918 private ranges.

Yeah this is the problem here. It currently only checks [these](https://github.com/lightningnetwork/lnd/blob/master/lncfg/address.go#L18).

**Comment by yyforyongyu** [comment]
was working on it, then found this
https://github.com/golang/go/issues/29146
looks like they will add IPv4 and IPv6 private addresses to the `net` package.

maybe we could add `0.0.0.0` to `loopBackAddrs` as a quick fix(and wait for the `net` package to be updated)?

**Comment by zoedberg** [comment]
I've read this [comment](https://github.com/lightningnetwork/lnd/pull/4258#issuecomment-625245673) and I understand your concerns. Maybe an intermediate solution that could satisfy developers for the moment could be denying dangerous IPs only when on mainnet, what do you think?
