### ISSUE TITLE
Reestablish channels without backup

### ISSUE THREAD

**Issue by gijswijs** [lightningnetwork/lnd#3083]
My node crashed before I was able to get channel.backup off site. So I have a few channels for which I know the `chan_point`, and there has been no transaction activity on those channels. It seems to me I could insert the "channel shell" into the database, so that the DLP protocol can be initiated. But I'm not sure how to go about this without a backup to restore.

Would anybody care to share any pointers? (Or explain to me why this can't be done?)

Thank you.

**Comment by molxyz** [comment]
@gijswijs  What's a "channel shell" ?

**Comment by gijswijs** [comment]
@molyx It's a term coined by @Roasbeef in the PR for the static channel backup #2313 

The exact quote is this:

> Given the set of channels to recover, the server will then (using the new chanbackup) package, will insert a series of "channel shells" into the database. These contains only the information required to initiate the DLP (data loss protection) protocol and nothing more. As a result, they're makred as "recovered" channels in the database, and we'll disallow trying to use then for any other process.

But the flow explained in that PR presumes a `channel.backup` file. My question is if we can initiate this proces without such a file.

**Comment by molxyz** [comment]
@gijswijs  Which version/commit of LND were you running before the node  crashed? 
Do you have any log for the crash? I think it would help your case better if you post your log on a pastebin and show it here.

**Comment by gijswijs** [comment]
I was running v0.6-beta. No logs or anything survived. The hardware is a complete loss, and this happened shortly after I set up this node, so no (channel) backups that I had stored off site (yet). the crash wasn't caused by LND anyway, so I don't think the logs would be of any help anyway.

But I still would like to see if I could get the DLP protocol going without a backup. I might be overlooking something, but I can't see why it shouldn't be possible.

**Comment by wpaulino** [comment]
It is not possible, even if the channel is force closed, you won't be able to sweep the funds as the outputs don't pay directly to an address your wallet controls. The `channel.backup` contains the information required to sweep it.

**Comment by Roasbeef** [comment]
Other than the channel point, you'll need to know which set of keys were used for that channel. If the node didn't have many channels, then you could quickly-ish brute force them to see what matches on chain. You'd also need to know the pubkey of the node. It's possible reconstruct all this, but it requires low level knowledge of how SCB and DLP work.

**Comment by gijswijs** [comment]
@Roasbeef That sounds like a challenge. :)
I maintain this node for research purposes anyway, so I might have a go at it.
Who knows, I might get a decent blog post out of it.
