### ISSUE TITLE
Bug? All hold invoices are private

### ISSUE THREAD

**Issue by MaxHillebrand** [lightningnetwork/lnd#3084]
### Background

When adding a hold invoice, it automatically adds private channel routing hints, regardless if the flag `--private` is active, or not. 

### Your environment

`lnd v0.6.1`

### Steps to reproduce

`lncli addholdinvoice [command options] hash [amt]`

An invoice with routing hints of all private channels is produced.

`lncli addholdinvoice --private [command options] hash [amt]`

Again, an invoice with routing hints of all private channels is produced.

### Expected behaviour

When the `--private` flag is not set, there should not be any routing hints included in the invoice. I'm not sure if this is on purpose, or if this is undesired behavior.

**Comment by wpaulino** [comment]
`lncli` creates invoices with routing hints by default. If you'd like to omit them, you need to explicitly set `--private=false`.

**Comment by MaxHillebrand** [comment]
Oh, I did not notice that it's private by default. 
As you mention `--private=false` works.
Sorry for the FUD then :)
Closing the issue...
