### ISSUE TITLE
Feature Request: PSBT integration, especially signing

### ISSUE THREAD

**Issue by MaxHillebrand** [lightningnetwork/lnd#3085]
### Background

[Partially Signed Bitcoin Transactions (BIP 174)](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) (by [@achow101](https://github.com/achow101)) allows for a standardized transfer of unsigned, partially signed, fully signed and finalized transactions. It would be nice to integrate this standard into lnd.

### Usage

I need this specifically to manage on chain funds of the lnd wallet in another software user interface. The capabilities of [bitcoin-qt](https://github.com/bitcoin/bitcoin),  [Wasabi Wallet](https://wasabiwallet.io) or [Electrum Wallet](https://electrum.org) are far greater than the implemented lnd wallet.

I would export the master public key from lnd into a watch only software wallet, build a PSBT there, export this over ssh, SD or any other way onto the lnd wallet for signing and broadcasting. 

### Considerations

PSBT integration would be a rather big change and improvement, I guess. There might be other more interesting ways to approach this, of course. 

I've [copied this feature request](https://github.com/btcsuite/btcwallet/issues/619) to the repository of btcsuite/btcwallet.

**Comment by AdamISZ** [comment]
Hi @MaxHillebrand  :)

Just to let you know I've had this PR open for a while: https://github.com/btcsuite/btcutil/pull/126

`lnwallet` currently encapsulates a `btcwallet` instance but it's built with an interface with the intention of being able to abstract that out (see [here](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/interface.go#L123-L132)), also I shouldn't comment too much on the arch. as I know it's changed a bit recently.

I was mostly thinking about coinjoin directly with lnd coins; I glean (speculate) that your intended use case is something more like; take lnd utxos via an xpub, import watch only, then do coin control stuff to build a tx, then import that back into lnd to sign and broadcast. I guess that makes sense.

 Anyway, I think there'll be a bit more to it than dropping in PSBT.

**Comment by MaxHillebrand** [comment]
Fantastic work Adam, thank you for this!!

Seems like your PR is very advanced already, hope we get this integrated son.
I'm really looking forward to what you tinker up with this coin join integration, I'll definitely stay tuned!

**Comment by Roasbeef** [comment]
This is on my radar now, with the end goal of being able to fund channels from a PSBT aware hardware wallet. Along the way, `btcwallet` will get full blown PSBT generation/signing/combining support as well.

**Comment by Roasbeef** [comment]
I'll be chopping this one up into some follow up issues to track things like the necessary RPC changes we'll need.

**Comment by Roasbeef** [comment]
Also waxwing's PR to `btcutil` which adds `psbt` support has been merged!
