### ISSUE TITLE
unable to pay invoice or move on-chain funds

### ISSUE THREAD

**Issue by vamp111** [lightningnetwork/lnd#3086]
Hi, im having trouble with the LND desktop app.

tried to pay an invoice and even send on-chain funds, but i get an error.
Logs keep updating with this info

*its a wallet I restored with the 24 words from my full LN node, who crashed and still has open channels with somewhat 18-20 nodes

logs attached
[logs.txt](https://github.com/lightningnetwork/lnd/files/3187275/logs.txt)

**Comment by wpaulino** [comment]
There are no errors in the logs attached.

> tried to pay an invoice and even send on-chain funds, but i get an error.

What error specifically?

**Comment by vamp111** [comment]
@wpaulino  will make another log, sorry

**Comment by halseth** [comment]
@vamp111 Please open an issue at https://github.com/lightninglabs/lightning-app/ with the proper logs/screenshots attached.
