### ISSUE TITLE
Is a length of node alias 31 or 32?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3091]
https://github.com/lightningnetwork/lnd/blob/27ae22fa6c2a69c0bda197d77dac99a8e756b7d6/sample-lnd.conf#L136

Hello!

In https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#requirements-2 i see that the field of Alias is 32 bytes and:

> MUST set alias to a valid UTF-8 string, with any alias trailing-bytes equal to 0.

So i think the zero trailing byte should be anyway. If it's right that we should say:

> ; The alias your node will use, which can be up to 31 UTF-8 characters in
> ; length.

What do you think?

P.S. More correctly say up to 31 bytes of utf-8 encoding?

**Comment by wpaulino** [comment]
You're allowed up to 32 bytes (inclusive), but if you happen to use any less than that, then the remaining bytes should be 0. This isn't something users need to worry about, `lnd` will handle the trailing bytes for you.
