### ISSUE TITLE
Allow use of unconfirmed UTXOs as input to funding transaction

### ISSUE THREAD

**Issue by grantwest** [lightningnetwork/lnd#3092]
If you fund your node with a single large transaction then the wallet will only have 1 UTXO to work with. If you want to open several channels, this means opening the channels serially and waiting for each to confirm before opening the next. It would be nice if the LND could use the unconfirmed change UTXO from the first channel funding transaction as the input to the next channel funding transaction.

I typically open my channels with a very low fee because I am not in a hurry. The problem is that doing it serially makes this process take weeks just to open a few channels. I would prefer to get all the txns published all at once.

**Comment by wpaulino** [comment]
You can already do so through the RPC interface. There is a bug with `lncli` however that will be resolved by https://github.com/lightningnetwork/lnd/pull/3093.
