### ISSUE TITLE
[feature request] Verify Compiled Protos on Travis

### ISSUE THREAD

**Issue by cfromknecht** [lightningnetwork/lnd#3094]
As pointed out by @xsb in #2312, different authors may have different proto versions installed when doing development. To ensure all PRs use the correct of protoc and plugins, we should move to have Travis verify that the output is correct, and fail the build otherwise.

## Steps to Completion
1. Have travis build and install the protobuf dependencies specified [here](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/README.md#generate-protobuf-definitions).
2. Cache the protobuf and plugin source directories in the travis build cache, so that it doesn't need to be recompiled from scratch on every build.
3. Add a new make target to `Makefile`, e.g. `rpc-check`, that first runs the `rpc` target, and then asserts that the source tree is clean. This can be done by using `$(shell git describe --dirty)` and asserting that the output doesn't contain the string `"dirty"`
4. Add the `rpc-check` target as a dependency to `travis-race`, `travis-itest`, and `travis-cover`, preferably after `lint` so that the more expensive operations are done only if the protos are sound.

**Comment by johng** [comment]
Would it not be better to just not checkout the generated protobuf files in source control, and make the generation part of the build step?

**Comment by cfromknecht** [comment]
@johng the protos should still be checked into source. The intent is that by recompiling them in Travis, we should be able to tell if they’re correct if it leaves the source tree in a dirty state

I started working on this in #3011 and #3010

**Comment by johng** [comment]
> @johng the protos should still be checked into source 
Why?

**Comment by cfromknecht** [comment]
@johng so that installing/building grpc and the related plugins isn’t required to compile lncli
