### ISSUE TITLE
[lncli] unable to parse chan backups: unable to decode multi packed backup: encoding/hex

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#3099]
### Background

Hello,
I'm trying to import my channels backup obtained with exportchanbackup
but I'm stuck on this error
`[lncli] unable to parse chan backups: unable to decode multi packed backup: encoding/hex: invalid byte: U+002F '/'`

Am I missing something?
Thanks in advice for your help
### Your environment

* lnd 0.6.1 beta
* linux
* bitcoin-core 0.18.0

**Comment by wpaulino** [comment]
How are you passing in the `channel.backup` file? When using `--single_backup` or `--multi_backup`, the backup needs to be hex encoded. When using `--multi_file`, you can just provide the path of the file.

**Comment by danbadjar** [comment]
Hello,
I've used a wrong parameter. Since I have a simple file I should use --multi_file.
I was using --multi_backup 
Now it works.
Thanks for the help
