### ISSUE TITLE
cannot recover wallet through channels.backup

### ISSUE THREAD

**Issue by nsollazzo** [lightningnetwork/lnd#3102]
### Background

I was not able to recover the funds from seed + channels.backup

### Your environment

* version of `lnd` Version: **0.6.1-beta commit=basedon-v0.6.1-beta-dirty**
* which operating system (`uname -a` on *Nix): **Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**
* version of `btcd`, `bitcoind`, or other backend: **Bitcoin Core 0.18.0**
* any other relevant environment details: **running btcpay server with docker containers**

### Steps to reproduce

I followed the [recovering-using-scbs](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#recovering-using-scbs) guide

### Expected behaviour

recover the wallet with the channels and the funds

### Actual behaviour
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaa508d]

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc000141838)
	/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:472 +0x278
panic(0xb99ca0, 0x141dc80)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
main.create(0xc000098c80, 0x0, 0x0)
	/go/src/github.com/lightningnetwork/lnd/cmd/lncli/commands.go:1604 +0x127d
main.actionDecorator.func1(0xc000098c80, 0x0, 0x0)
	/go/src/github.com/lightningnetwork/lnd/cmd/lncli/commands.go:70 +0x33
reflect.Value.call(0xb55c00, 0xc00003e0a0, 0x13, 0xc9261b, 0x4, 0xc0001497d8, 0x1, 0x1, 0xc0000a8040, 0xc0000a6690, ...)
	/usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0xb55c00, 0xc00003e0a0, 0x13, 0xc0001497d8, 0x1, 0x1, 0x5, 0x4, 0xc00001d010)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0xb55c00, 0xc00003e0a0, 0xc000098c80, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:481 +0x1fb
github.com/urfave/cli.Command.Run(0xc94118, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcbd468, 0x39, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.18.0/command.go:186 +0x908
github.com/urfave/cli.(*App).Run(0xc00008a780, 0xc00009a060, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:235 +0x52e
main.main()
	/go/src/github.com/lightningnetwork/lnd/cmd/lncli/main.go:307 +0x1044
```

**Comment by wpaulino** [comment]
Will be fixed by #3104. You can alternatively restore the backup with `lncli restorchanbackup` after you create the wallet.

**Comment by nsollazzo** [comment]
> Will be fixed by #3104. You can alternatively restore the backup with `lncli restorchanbackup` after you create the wallet.

I tried and this is the result `[lncli] unable to restore chan backups: rpc error: code = Unknown desc = unable to unpack chan backup: chacha20poly1305: message authentication failed`

**Comment by wpaulino** [comment]
That error is shown when passing in an invalid backup. What was the exact command you ran?

**Comment by nsollazzo** [comment]
because I'm using btcpay server and docker i ran:
`./bitcoin-lncli.sh restorechanbackup --multi_file /channels.backup `

and [here](https://github.com/btcpayserver/btcpayserver-docker/blob/master/bitcoin-lncli.sh) you can find the script : it just invoke the lncli inside the docker container.
I've copied the channels.backup file from my machine to the remote server and then inside the docker container in the root folder

**Comment by wpaulino** [comment]
I'm assuming this new node where you're running this command on was restored using your seed? This is crucial as the encryption key of the backup is derived from the seed.

**Comment by nsollazzo** [comment]
well, the first thing I did after the download of the full blockchain was `lncli create` and then I gave the seed

**Comment by wpaulino** [comment]
Perhaps there was a typo? Did it recover any on-chain funds for you?

**Comment by nsollazzo** [comment]
I checked and i found no funds.
`walletbalance` gave me
```
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}
```
and when i try to do `create` again with the same seed I see:
```
[lncli] Wallet is already unlocked
```

**Comment by wpaulino** [comment]
You'll need to wipe your current `lnd` state in order to restore again.

**Comment by nsollazzo** [comment]
how can I do that?

**Comment by Roasbeef** [comment]
You'd start from scratch with a new `lnd` directory. We're all your funds in channels, or did you also have on-chain funds? If you haven't already, you [should check out these recovery docs](https://github.com/lightningnetwork/lnd/blob/68da2058636a4f702946010c98dd50408182740d/docs/recovery.md).

**Comment by nsollazzo** [comment]
I had both on and off chain.
I'm already following the recovery docs as I mention when I opened the issuee.
Following @wpaulino suggestion of "wiping the current lnd state in order to restore again" my question is: how can i do that?

**Comment by wpaulino** [comment]
You need to locate where BTCPay server stores `lnd`'s data and remove it/move it elsewhere. I'd reach out to the developers if you're unsure of where that is.

**Comment by nsollazzo** [comment]
I found that the volume is here `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data` and I move it from local and from the docker container but when I try to `lncli create` to restore from the seed it says `[lncli] Wallet is already unlocked`

**Comment by wpaulino** [comment]
You need to shut down `lnd`, move the data elsewhere, and restart it before trying `lncli create` again.

**Comment by nsollazzo** [comment]
so, I used the [btcpay-down.sh](https://github.com/btcpayserver/btcpayserver-docker/blob/master/btcpay-down.sh) which stops and removed all containers (so it stopped lnd and removed everything for me), then I removed the data from the volume on the host and finally I used [btcpay-up.sh](https://github.com/btcpayserver/btcpayserver-docker/blob/master/btcpay-up.sh) to put everything up again.
I waited a couple of minutes, then I tried to `lncli create` but the results where the same: `[lncli] Wallet is already unlocked`

**Comment by nsollazzo** [comment]
solved [here](https://github.com/btcpayserver/btcpayserver-docker/issues/138)
