### ISSUE TITLE
[Bug] Make LND resilient to bitcoind crashes: Dropping ZMQ connection

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#3109]
### Background

Very often, when BitcoinD restarts for anything, LND stop working.

I tracked that previously to LND not handling cookiefile authentication the right way.
LND not reading the cookiefile everytimes it is calling RPC. **BUT this is not the only problem.**

On BTCPay, I switched to fixed rpcuser/password only for LND, but keep having problems.

The last time I noticed that my LND was seemingly working, but the chain was not synched anymore for some reason.
I checked the logs, could not find any specific issue, but it seemed clear LND was not getting blocks from BitcoinD, and it was also clear that LND was able to use RPC against bitcoind  (no RPC error in the logs).

Restarting LND did the trick.

### Your environment

* version of `lnd 0.6.1`

### Steps to reproduce

* Run Bitcoin Core
* Run LND
* Wait LND is operational
* Restart Bitcoin Core

### Expected behaviour

LND should reconnect to ZMQ automatically OR crash.

### Actual behaviour

LND does not reconnect to ZMQ, the chain is not synched anymore, the blocks are not received, putting the user's fund at risk.

**Comment by wpaulino** [comment]
Have tried this myself on regtest and testnet and I'm unable to reproduce. `lnd` already has logic to reconnect to the ZMQ sockets.

**Comment by wpaulino** [comment]
How long does `bitcoind` usually stay down for before restarting it?

**Comment by Roasbeef** [comment]
Are you running both of them inside containers? Or the raw binaries?

**Comment by NicolasDorier** [comment]
Both of them inside container. A possible issue might be DNS caching? When in my case the bitcoind process restarted and may have been attributed a different IP.

Does lnd is caching DNS resolution internally?

**Comment by NicolasDorier** [comment]
> How long does bitcoind usually stay down for before restarting it?

Normally 1 or 2 min, as docker restart bitcoind automatically.

**Comment by NicolasDorier** [comment]
If you tell me that LND is not caching internally the ZMQ host DNS's IP, then we can close this issue until I can better reproduce the issue.

**Comment by halseth** [comment]
The `gozmq` lib is perhaps caching the IP.

**Comment by wpaulino** [comment]
It indeed is, it caches the host:port.

**Comment by NicolasDorier** [comment]
@wpaulino then this should be fixed, as any temporary crash of bitcoind will render LND in a zombie state which can lead to the other party broadcast an old state without risk.

Either LND should crash, or it should not cache host:port

**Comment by Roasbeef** [comment]
>  as any temporary crash of bitcoind will render LND in a zombie state which can lead to the other party broadcast an old state without risk.

In either case, `lnd` is at risk. If we crash we can't respond, if we don't crash we'll never get the on-chain notification.

**Comment by NicolasDorier** [comment]
If you crash, process managers (docker, supvervisord or systemd) would restart it.
