### ISSUE TITLE
Trouble creating macaroon file (lncli create+rpc error)

### ISSUE THREAD

**Issue by zhongtan** [lightningnetwork/lnd#3115]
### Background

I am working through the tutorial to build from source but got stuck at running LND using the btcd backend. I ran this command and got the prompt to create or unlock a wallet:

`lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=<username> --bitcoind.rpcpass=<password> --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333 --externalip=<my computer's ip>`

I tried running `lncli create` but I keep getting this RPC error:

`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

I include a new seed mnemonic every time I try to create a new wallet. I think I must have missed out on some configurations but I'm not entirely sure where they are. 

I looked at this similar [issue](https://github.com/grpc/grpc-go/issues/2636) and tried downgrading RPC to version 1.17.0 but still ran into the same error. 

### Your environment

* version of `lnd`
lnd v0.6.1-beta

* which operating system 
MacOS Mojave 10.14.5

* version of `btcd`, `bitcoind`, or other backend
btcd version 0.12.0-beta

* version of `go`
go1.12.4 darwin/amd64

* bitcoin.conf
`testnet=1`
`server=1`
`daemon=1`
`zmqpubrawblock=tcp://127.0.0.1:28332`
`zmqpubrawtx=tcp://127.0.0.1:28333`

### Expected behaviour

Macaroon file should be created

### Actual behaviour

All subConns in TransientFailure

**Comment by molxyz** [comment]
@zhongtan  You have `--bitcoind.rpcuser=<username> --bitcoind.rpcpass=<password>` in your lnd.conf but not in bitcoin.conf.  You need to set the same credentials in both.  For bitcoin.conf it should be 
```
rpcuser=<username>
rpcpassword=<password>
```

**Comment by zhongtan** [comment]
My bad, I was supposed to run lnd in another session while creating the wallet. I included the credentials in my bitcoin.conf and ran the lnd command again with all the flags. I got a different error instead:

`
[lncli] rpc error: code = Unknown desc = wrong seed version
`

I tried deleting the entire LND folder and started over but still got the same error above. Any ideas on what might be wrong?

**Comment by zhongtan** [comment]
I ended up not using an existing cipher seed and let lnd generate a new seed for me. Not getting the error anymore, thanks!

**Comment by cfromknecht** [comment]
> `wrong seed version`

This sounds like you're not using a proper cipher seed?

**Comment by gnipping** [comment]
I meet the samiliar question. I can use lncli create and lncli unlock, but when I use other commands. It feeds back the error.
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

**Comment by cfromknecht** [comment]
@gnipping when lnd first starts up, only the [`WalletUnlocker`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.pb.go#L11204) rpcserver is active. Once authentication is successful, it gets replaced by the full [`Lightning`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.pb.go#L11423) rpcserver. That error looks more like you were trying to connect to the rpcserver while lnd was done (or crashed), though it is possible you issued the command while the switchover between rpcservers happens.

**Comment by OpenSystemCode** [comment]
@gnipping @cfromknecht  I have the same problem on my rasperberry pi.

` sudo journalctl -u lnd -f -n20`

```
Jan 31 16:28:09 "" systemd[1]: Started LND Lightning Daemon.
Jan 31 16:28:10 "" lnd[1380]: Attempting automatic RPC configuration to bitcoind
Jan 31 16:28:10 "" lnd[1380]: Automatically obtained bitcoind's RPC credentials
Jan 31 16:28:10 "" lnd[1380]: 2020-01-31 16:28:10.250 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
Jan 31 16:28:10 "" lnd[1380]: 2020-01-31 16:28:10.251 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jan 31 16:40:30 "" systemd[1]: Stopping LND Lightning Daemon...
Jan 31 16:40:30 "" lnd[1380]: 2020-01-31 16:40:30.760 [INF] LTND: Received terminated
Jan 31 16:40:30 "" lnd[1380]: 2020-01-31 16:40:30.874 [INF] LTND: Shutting down...
Jan 31 16:40:30 "" lnd[1380]: 2020-01-31 16:40:30.966 [INF] LTND: Gracefully shutting down.
Jan 31 16:43:30 "" systemd[1]: lnd.service: State 'stop-sigterm' timed out. Killing.
Jan 31 16:43:30 "" systemd[1]: lnd.service: Killing process 1380 (lnd) with signal SIGKILL.
Jan 31 16:43:30 "" systemd[1]: lnd.service: Main process exited, code=killed, status=9/KILL
Jan 31 16:43:30 "" systemd[1]: Stopped LND Lightning Daemon.
Jan 31 16:43:30 "" systemd[1]: lnd.service: Unit entered failed state.
Jan 31 16:43:30 "" systemd[1]: lnd.service: Failed with result 'timeout'.
Jan 31 16:43:49 "" systemd[1]: Started LND Lightning Daemon.
Jan 31 16:43:50 "" lnd[1749]: Attempting automatic RPC configuration to bitcoind
Jan 31 16:43:50 "" lnd[1749]: Automatically obtained bitcoind's RPC credentials
Jan 31 16:43:50 "" lnd[1749]: 2020-01-31 16:43:50.349 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
Jan 31 16:43:50 "" lnd[1749]: 2020-01-31 16:43:50.350 [INF] LTND: Active chain: Bitcoin (network=mainnet)

```

can you help to resolve this?

**Comment by guggero** [comment]
@OpenSystemCode from your log it looks like `lnd` doesn't have enough time to start.
We added change to the way the databases are handled in `v0.9.0` that uses less memory but takes longer to start. You can disable that behavior: Try setting the `sync-freelist=1` option in the `lnd.conf` file or the `--sync-freelist` command line flag.

The other option is to give lnd more time to start. Perhaps your `systemd` script needs a longer wait timeout or something. Is this the RaspiBlitz software?

**Comment by OpenSystemCode** [comment]
Hey @guggero thanks for you reply. It's RaspiBolt Software. I waited a few minutes until the message  `Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.`

After this message the cmd `lncli unlock` went through.

**Comment by A-qiu161203** [comment]
> I meet the samiliar question. I can use lncli create and lncli unlock, but when I use other commands. It feeds back the error.
> `[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

so am I. Have you resoved it?

**Comment by Smiggel** [comment]
> I meet the samiliar question. I can use lncli create and lncli unlock, but when I use other commands. It feeds back the error.
> `[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

Did you find the solution for this? I have the same issue now after upgrading RaspiBlitz from 1.6.1 to 1.6.2.

**Comment by Smiggel** [comment]
> > I meet the samiliar question. I can use lncli create and lncli unlock, but when I use other commands. It feeds back the error.
> > `[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`
> 
> so am I. Have you resoved it?

Were you able to resolve this?

**Comment by bvrulez** [comment]
I have a similar problem after beeing unable to remove macaroon files and upgrading on a RaspiBolt: https://github.com/Stadicus/RaspiBolt/issues/734

But I have to say that I used their recommendations of how to [upgrade ](https://stadicus.github.io/RaspiBolt/raspibolt_faq.html#how-to-upgrade-lnd) and I am unsure if this is up-to-date because LND seems to just do it with a docker now.

**Comment by getacat** [comment]
> I ended up not using an existing cipher seed and let lnd generate a new seed for me. Not getting the error anymore, thanks!

how to let lnd generate a new seed? I meet the same error as you.

`[lncli] rpc error: code = Unknown desc = wrong seed version`
