### ISSUE TITLE
Command Line Options for Docker

### ISSUE THREAD

**Issue by Tzadiko** [lightningnetwork/lnd#3116]
### Background

Hi, I'm new to Docker. I would like to use the Dockerfile provided but am having difficulties understanding the "Commandline Options". Here:

`docker create --name=lnd lightninglabs/lnd [command-line options]`

I am running `docker create --name=lnd lightninglabs/lnd --bitcoin.active --bitcoin.mainnet1 --debuglevel=debug --bitcoin.node=bitcoind-lightning --bitcoind.rpcuser=REDACTED --bitcoind.rpcpass=REDACTED --externalip=X.X.X.X --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333`

**Given the information below, please advise as to how I can create a LND node, and then enter it and create a wallet, using Docker. Thank you!**

### Your environment

I have the most recent version of bitcoind (0.17.1). I have a bitcoind node called bitcoind-lightning. It is in a Kubernetes cluster alongside some other pods. GIven that the bitcoind node is inside a cluster, I can connect to it through a service: http://bitcoind-lightning.XXX.XXX.XXX:8332/

My bitcoind.conf file for bitcoind-lightning.

`# Network
listen=1

# Docker
daemon=0
printtoconsole=1

# Mempool
minrelaytxfee=0.00005

# RPC
server=1
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0.0.0.0
rpcuser=REDACTED
rpcpassword=REDACTED

# Additional lines to enable ZeroMQ
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

# Indices
txindex=1
addressindex=1
timestampindex=1
spentindex=1`

### Steps to reproduce

I would like to learn how to set up a lightning node using this bitcoind node.

### Expected behaviour

I would like to launch and run lnd, exec into the container, and create a wallet using ` docker exec -it lnd-testnet lncli create`

### Actual behaviour

`Total reclaimed space: 1.133GB
SYSTEM:~ homefolder$ docker create --name=lnd lightninglabs/lnd --bitcoin.active --bitcoin.mainnet --debuglevel=debug --bitcoin.node=bitcoind-lightning --bitcoind.rpcuser=REDACTED --bitcoind.rpcpass=REDACTED --externalip=X.X.X.X --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
934da9265ce57463260492cc759d3b65f8ce6f284d5d9374fd4e55ca3606b8e8
SYSTEM:~ homefolder$ docker start lnd
lnd
SYSTEM:~ homefolder$ docker run lnd
Unable to find image 'lnd:latest' locally
docker: Error response from daemon: pull access denied for lnd, repository does not exist or may require 'docker login'.
See 'docker run --help'.
SYSTEM:~ homefolder$ `

**Comment by Roasbeef** [comment]
I'm unable to reproduce this.

**Comment by peername** [comment]
Same problem here. The following commend:

`sudo docker create --name lnd lightninglabs/lnd`

returns:

`Error response from daemon: pull access denied for lightninglabs/lnd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by guggero** [comment]
There currently aren't any official images provided by Lightning Labs. You can create the image by issuing the following command in the root directory: `docker build -t lightninglabs/lnd .` (don't forget the dot at the end).
