### ISSUE TITLE
[Documentation] install dropwtxmgr instructions appear incorrect

### ISSUE THREAD

**Issue by IvanThinking** [lightningnetwork/lnd#3121]
### Background
This page: https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
describes how to get funds back. One option if funds are still missing is to do the "Forced In-Place rescan" in which the instruction is given:

 It can be installed with the following command:

⛰  go get -v -u github.com/btcsuite/btcwallet/cmd/dropwtxmgr

However, doing this apparently fails to install the package. Being a linux n00b, I am trying to figure out how to actually install it, but this aint it.

### Your environment
SSH to my raspiblitz version of lightning network node

### Steps to reproduce
1. Follow your instructions on https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md to do "Forced In-Place rescan"
2. Fail when trying to use verbatim install instructions.

### Expected behaviour
dropwtxmgr gets installed so I can follow the rest of the instructions

### Actual behaviour
it appears the install does not happen as trying to continue with the instructions yields:

Command: dropwtxmgr --db=$HOME/.lnd/data/chain/bitcoin/mainnet/wallet.db
Response: -bash: dropwtxmgr: command not found

Here are the -v logs generated:
 go get -v -u github.com/btcsuite/btcwallet/cmd/dropwtxmgr
github.com/btcsuite/btcwallet (download)
github.com/btcsuite/btcutil (download)
github.com/btcsuite/btcd (download)
Fetching https://golang.org/x/crypto/ripemd160?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ripemd160?go-get=1 (status code 200)
get "golang.org/x/crypto/ripemd160": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ripemd160?go-get=1
get "golang.org/x/crypto/ripemd160": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/btcsuite/btclog (download)
github.com/btcsuite/golangcrypto (download)
github.com/coreos/bbolt (download)
github.com/jessevdk/go-flags (download)

After this I get a command prompt... as if the "go get" function is failing to install after downloading?

**Comment by molxyz** [comment]
@IvanThinking  The recovery doc is a general guide for most lnd users who have have their datadir in  `$HOME/.lnd` . But since you are you're using 'raspiblitz version' do you have a different set up for your lnd datadir?  If you do, you need to find out where it is.  

You might also try to find out if `dropwtxmgr` is already installed in your system.  Do `which dropwtxmgr` to see if it shows where it might be installed.

**Comment by IvanThinking** [comment]
I  did: cd $HOME/.lnd then an ls

it showed: data  lnd.conf  logs  tls.cert in the ./lnd directory so I'm guessing it's as expected?

I tried: which dropwtxmgr
It showed nothing (just shows prompt again)

**Comment by IvanThinking** [comment]
I got it to work by using "**~/go/bin/**dropwtxmgr --db=$HOME/.lnd/data/chain/bitcoin/mainnet/wallet.db"

Maybe change the docs to reflect this addition to the path?

**Comment by molxyz** [comment]
@IvanThinking  Yea i had problem with the doc how to install dropwtxmgr in the past. But i got it figured out.  Here's my little guide I just put in a pastebin, try this:   https://paste.ee/p/5KlMB#lLNJ1ngz3Lq88yyNPpvW6P7C5Pwgk7Nc

**Comment by IvanThinking** [comment]
I got it to work. Unfortunately, my satoshis are still lost in some weird limbo.

**Comment by Roasbeef** [comment]
You need to have `$GOPAATH/bin` in your `$PATH`.

**Comment by RobinTick** [comment]
For the next person with this issue, make sure you run the latest GO version.
Installing golang trough APT will give you an old version, remove that, and get it from here https://golang.org/doc/install
