### ISSUE TITLE
lncli returns `admin.macaroon: no such file or directory` when `no-macaroons=true` in `lnd.conf`

### ISSUE THREAD

**Issue by kilrau** [lightningnetwork/lnd#3123]
### Background

LND setup with `no-macaroons=true` causes `lncli` to return `admin.macaroon: no such file or directory`. Details below.

### Your environment

* version of `lnd`: `0.6.1-beta commit=v0.6.1-beta-60-g339080394d10b59f2542edcf6b1dfd13e876e728`
* which operating system (`uname -a` on *Nix): `4.15.0-1039-aws #41-Ubuntu SMP Wed May 8 10:43:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `btcd`, `1.3.0`
* any other relevant environment details: user `ubuntu`

### Steps to reproduce

1. Set up `0.6.1-beta` (btcd backend, mainnet) from scratch with `no-macaroons=true` in `lnd.conf` (before initial `lncli create`). Doesn't create macaroon files when lnd is started for the first time (expected).
2. `lncli create`: setup wallet
3. `lncli getinfo` & co are failing with `[lncli] unable to read macaroon path (check the network setting!): open /home/ubuntu/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory`.

Notes:
* Restarting `lnd` with  `no-macaroons=false` in `lnd.conf` creates macaroon files and fixes it.
* After macaroons files are created, `no-macaroons=true` in `lnd.conf` can be enabled, not sure if it's read tho.
* Moving (or deleting) macaroons files, cause `lncli` to return `admin.macaroon: no such file or directory` again, unless `--macaroonpath=` to the macaroon files.
* Related issues: https://github.com/lightningnetwork/lnd/issues/1236, https://github.com/lightningnetwork/lnd/issues/533. If PR's for these will fix it, please close. Not a prio anyways.

### Expected behaviour

lncli works out-of-the-box without macaroons

### Actual behaviour

lncli in above scenario needs macaroons to work. I read through https://github.com/lightningnetwork/lnd/blob/master/docs/macaroons.md and I believe it describes that `lncli` should work without macarooons at all when `no-macaroons=true` is set in `lnd.conf`.

**Comment by Roasbeef** [comment]
You need to set `--no-macaroons` for `lncli`.
