### ISSUE TITLE
Can't initialize wallet from script via lnd_grpc: mnemonic phrase checksum doesn't match

### ISSUE THREAD

**Issue by s-tikhomirov** [lightningnetwork/lnd#3127]
### Background

I'm trying to create a Python script to launch multiple independent LND instances in separate directories. As a minimal example, I've written a script which is supposed to launch BTCD, then launch LND, then initialize a wallet, then kill everything.

Doing it manually works:
```
btcd --txindex --simnet --rpcuser=kek --rpcpass=kek
lnd --bitcoin.active --bitcoin.simnet --btcd.rpcuser=kek --btcd.rpcpass=kek --no-macaroons --rpclisten=localhost:10001 --listen=localhost:10011 --datadir=data --logdir=log --tlscertpath=tls.cert --tlskeypath=tls.key
lncli --lnddir . --network simnet --no-macaroons --rpcserver localhost:10001 create
```

### Your environment

*  lnd version 0.6.1-beta commit=v0.6.1-beta-84-gaf3b04e53f7cc2198ac41a7b6590018a2b21a599
* Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* btcd version 0.12.0-beta
* Python 3.6.5, [lnd_grpc](https://github.com/willcl-ark/lnd_grpc) f5df6d920eb700c22d89c40e58c1ecd6571e4de0

### Steps to reproduce

`python3 script.py` the following:

```
from lnd_grpc import lnd_grpc
from time import sleep
import sys
import os
import subprocess
import signal

# start BTCD
cmd = "btcd --txindex --simnet --rpcuser=kek --rpcpass=kek"
btcProcess = subprocess.Popen([cmd],shell=True, stdout=sys.stdout, stderr=sys.stderr, preexec_fn=os.setsid)
sleep(10)

# create a test directory
test_dir = os.path.join(os.getcwd(), 'test', '') # require trailing slash
os.mkdir(test_dir)
os.chdir(test_dir)

# start LND 
lnd_command = "lnd --bitcoin.active --bitcoin.simnet --btcd.rpcuser=kek --btcd.rpcpass=kek --no-macaroons " + \
    "--rpclisten=localhost:10001 --listen=localhost:10011" + \
    " --datadir=data --logdir=log --tlscertpath=tls.cert --tlskeypath=tls.key"
lndProcess = subprocess.Popen([lnd_command], shell=True, stdout=sys.stdout, stderr=sys.stderr, preexec_fn=os.setsid)
sleep(10)

# initialize Lightning wallet
try:
    lnd_rpc = lnd_grpc.Client(
        lnd_dir=test_dir,
        network='simnet',
        grpc_host='localhost',
        grpc_port='10001'
        )
    lnd_rpc.gen_seed()
    lnd_rpc.init_wallet(wallet_password="123456789")
except Exception as e:
    print(e)
finally:
    # kill BTC and LND processes
    print("killing...")
    os.killpg(os.getpgid(btcProcess.pid), signal.SIGTERM)
    os.killpg(os.getpgid(lndProcess.pid), signal.SIGTERM)
    print("killed")
```

### Expected behaviour

A new wallet initialized, then both daemons killed.

### Actual behaviour

The script exits with error:

```
<_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "mnemonic phrase checksum doesn't match"
	debug_error_string = "{"created":"@1558974002.624020765","description":"Error received from peer ipv4:127.0.0.1:10001","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"mnemonic phrase checksum doesn't match","grpc_status":2}"
>
```

Looks like it expects me to  enter a mnemonic phrase, but why? No wallet has been initialized yet.

**Comment by Roasbeef** [comment]
You need to pass the seed mac into `InitWallet`, check out the documentation here: https://api.lightning.community/

**Comment by s-tikhomirov** [comment]
Just to clarify: in the examples on the website, the RPC libraries are imported as `import rpc_pb2 as ln, rpc_pb2_grpc as lnrpc`, but I've been trying to use [lnd_grpc](https://github.com/willcl-ark/lnd_grpc) (`from lnd_grpc import lnd_grpc`). Are those different things? (Well, the function names are different: `InitWallet` vs `init_wallet`, etc.) Should I switch?

**Comment by halseth** [comment]
@s-tikhomirov Yeah they are different. You can file the issue on the `lnd_grpc` repo.
