### ISSUE TITLE
initwallet REST API is failing with passphrase

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#3128]
initwallet REST API is working without passphrase but it fails with passphrase with 'invalid passphrase' error message.

### Your environment
* version of `lnd`: 0.6.0-beta
* which operating system: Windows
* version `bitcoind`: v0.17.1

### Steps to reproduce
Initialize wallet with below details:
Method: POST, 
url: https://192.168.1.8:8080/v1/initwallet, 
payload: {
    "wallet_password":"c3VoZWIxMjM=",
    "cipher_seed_mnemonic":["absent","stuff","layer","holiday","slam","pelican","drift","heart","prepare","casual","treat","liar","small","venue","fragile","wise","frown","safe","brief","cherry","pigeon","pole","sound","rocket"],
    "aezeed_passphrase":"dGhpc2lzbXlwYXNzcGhyYXNl"
}

### Expected behaviour
It should successfully initialize the wallet.

### Actual behaviour
Failed response with { "error": "invalid passphrase", "code": 2 }

**Comment by Roasbeef** [comment]
You're passing in the values as base58, they should be raw bytes.
