### ISSUE TITLE
infinitely pending force close channel  

### ISSUE THREAD

**Issue by ac-com-au** [lightningnetwork/lnd#3132]
### Background

infinitely pending force close channel  

### Your environment

 lncli getinfo
{
        "version": "0.6.1-beta commit=v0.6.1-beta-165-g28fdf9712d88c104ca039dc56d5242d3822c00d0",
        "identity_pubkey": "024a853d9cdedafc164e49c2cef301966e5a78091322a84175b52d059d71b4d672",
        "alias": "ac.com.au",
        "color": "#3399ff",
        "num_pending_channels": 0,
        "num_active_channels": 7,
        "num_inactive_channels": 0,
        "num_peers": 9,
        "block_height": 578196,
        "block_hash": "00000000000000000001a60d8e921297504021ed4cbbb51b956bbfd6de1088c6",
        "best_header_timestamp": 1559049512,
        "synced_to_chain": true,
        "testnet": false,
        "chains": [
                {
                        "chain": "bitcoin",
                        "network": "mainnet"
                }
        ],
        "uris": [
                "024a853d9cdedafc164e49c2cef301966e5a78091322a84175b52d059d71b4d672@175.33.130.235:9735"
        ]
}

Linux s3 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 bitcoin-cli --getinfo
{
  "version": 189900,
  "protocolversion": 70015,
  "blocks": 578196,
  "timeoffset": 0,
  "connections": 92,
  "proxy": "",
  "difficulty": 6704632680587.417,
  "chain": "main",
  "walletversion": 169900,
  "balance": 0.00000000,
  "keypoololdest": 1527382208,
  "keypoolsize": 1000,
  "unlocked_until": 0,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

"pendong force close "
Funding transaction:
https://blockstream.info/tx/ccf052db98a2acfda354f0d0fc2cafe31944ce418c768c5bcad1aed5896786b5

Channel opening date: Feb 09, 2019 1:03 PM
Closing Transaction: https://blockstream.info/tx/cf63b67be2f10b7c34bc6f9cab24dedc343a4064a2e87907412962b3975448e9

**Comment by ac-com-au** [comment]
lncli listchannels
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "020c92d71dfe47d49d322eed910064787973dff96c05a39d75a75d7e8f33aead4c",
            "channel_point": "a504af0a992bdea4061db3dec874381d96451fa6058480d7b7fd869b8577ec9b:0",
            "chan_id": "619498935981047808",
            "capacity": "100000",
            "local_balance": "1000",
            "remote_balance": "76764",
            "commit_fee": "22236",
            "commit_weight": "724",
            "fee_per_kw": "30713",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "1000",
            "num_updates": "316",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "027e70d8859e090ed975b11cfa02109221482954a254dff185e4142188eb66518b",
            "channel_point": "80e4910d7cf37d118d7f56b6abc8854358224809ba51dcc476bd9f9319d7d1bc:0",
            "chan_id": "624481922696019968",
            "capacity": "300000",
            "local_balance": "274225",
            "remote_balance": "0",
            "commit_fee": "25775",
            "commit_weight": "600",
            "fee_per_kw": "35602",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "194",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "02809e936f0e82dfce13bcc47c77112db068f569e1db29e7bf98bcdd68b838ee84",
            "channel_point": "4de257931bd38ed007f7430db979e33e5cddc55fa6ccba5f1b94cb8d795b8f11:0",
            "chan_id": "622497304214175744",
            "capacity": "20000",
            "local_balance": "0",
            "remote_balance": "1798",
            "commit_fee": "18202",
            "commit_weight": "552",
            "fee_per_kw": "25142",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "209",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c",
            "channel_point": "3d18bcd9b4d2fa2aba4c5cd1fe6c24956b39032c843f1baec10a61a4da5eff61:0",
            "chan_id": "626067418604830720",
            "capacity": "400000",
            "local_balance": "0",
            "remote_balance": "374225",
            "commit_fee": "25775",
            "commit_weight": "552",
            "fee_per_kw": "35601",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "168",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c",
            "channel_point": "090571c90e88fad698ddd40bdfcacfd807a9c67f935e3084aad378ba0643eafb:1",
            "chan_id": "617837573898829825",
            "capacity": "400000",
            "local_balance": "351264",
            "remote_balance": "26500",
            "commit_fee": "22236",
            "commit_weight": "724",
            "fee_per_kw": "30713",
            "unsettled_balance": "0",
            "total_satoshis_sent": "26500",
            "total_satoshis_received": "0",
            "num_updates": "369",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0",
            "channel_point": "afdb7e5521987f6bbddeda8fc0a64eea19774987a5c5f7d4272507615e9b5f28:1",
            "chan_id": "617833175946428417",
            "capacity": "300000",
            "local_balance": "277766",
            "remote_balance": "0",
            "commit_fee": "22234",
            "commit_weight": "600",
            "fee_per_kw": "30711",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "348",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault"
        },
        {
            "active": true,
            "remote_pubkey": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
            "channel_point": "ea595546688eefc64cfcdbed4e107c8204cea9571a12e56ed63653a61acf3c28:1",
            "chan_id": "621964041164357633",
            "capacity": "400000",
            "local_balance": "0",
            "remote_balance": "377764",
            "commit_fee": "22236",
            "commit_weight": "552",
            "fee_per_kw": "30714",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "303",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault"
        }
    ]
}
samh@s3:~$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
                "channel_point": "ccf052db98a2acfda354f0d0fc2cafe31944ce418c768c5bcad1aed5896786b5:1",
                "capacity": "289000",
                "local_balance": "164544",
                "remote_balance": "0"
            },
            "closing_txid": "cf63b67be2f10b7c34bc6f9cab24dedc343a4064a2e87907412962b3975448e9",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ],
    "waiting_close_channels": [
    ]
}

**Comment by molxyz** [comment]
@ac-com-au  I noticed you're running `bitcoin "version": 189900,` . Not sure if it has anything to do with your issue but we've been advised not to run bitcoin master or version 0.18.0 currently. The recommended version is either 0.17.0  or 0.17.1.

**Comment by danbadjar** [comment]
Same problem here. 
Channels stuck on force close. Can we solve the problem just rollback the bitcoind version?

**Comment by danbadjar** [comment]
Suggestion @Roasbeef 
Can you add in the release page a warning for bitcoind-0.18 ?
https://github.com/lightningnetwork/lnd/releases/
Thanks

**Comment by danbadjar** [comment]
the only thing I found about bitcoind issues is a tweet of Alex Bosworth:
https://twitter.com/alexbosworth/status/1129402043360108545

**Comment by wpaulino** [comment]
What are the debug `CNCT` logs for the channel upon restart?

**Comment by danbadjar** [comment]
Maybe this can help you.
Channel is still stuck in force close and funds don't come onchain.
ATM I'm on Bitcoind 0.18 and LND 0.6.1-beta commit=v0.6.1-beta-174
On the other side the peer told me the tx is ok and his funds are correctly come back onchain.

2019-05-29 22:48:39.593 [INF] CNCT: Close observer for ChannelPoint(c2ff3e968c5168540ca10fc9e3e9b26410b00b600fcde6daa91797136baa4691:0) active
2019-05-29 22:48:39.682 [INF] CNCT: Close observer for ChannelPoint(3f023738d931ffd31353aab9e3ccb3e402dff536144c7073a49ee39dd54f1da2:0) active
2019-05-29 22:48:39.682 [INF] CNCT: ChannelArbitrator(c2ff3e968c5168540ca10fc9e3e9b26410b00b600fcde6daa91797136baa4691:0): starting state=StateDefault
2019-05-29 22:48:39.690 [INF] CNCT: ChannelArbitrator(3f023738d931ffd31353aab9e3ccb3e402dff536144c7073a49ee39dd54f1da2:0): starting state=StateDefault
2019-05-29 22:48:39.751 [INF] CNCT: ChannelArbitrator(a2f3f8d97b815daea481ad9fe536ef2a3860c7e4104ccee56ff3d998162cc426:1): starting state=StateWaitingFullResolution
2019-05-29 22:48:39.759 [INF] CNCT: ChannelArbitrator(a2f3f8d97b815daea481ad9fe536ef2a3860c7e4104ccee56ff3d998162cc426:1): still awaiting contract resolution
2019-05-29 22:48:39.762 [INF] CNCT: ChannelArbitrator(a2f3f8d97b815daea481ad9fe536ef2a3860c7e4104ccee56ff3d998162cc426:1): **relaunching 1 contract resolvers**
2019-05-29 22:48:39.763 [INF] NTFN: New confirmation subscription: txid=b2a759675e0a33a6702a9f50fdbdc5b5a74c2146997496bad5fd7f7422ec90b7, num_confs=1
2019-05-29 22:48:39.764 [INF] NTFN: New confirmation subscription: conf_id=1, txid=**b2a759675e0a33a6702a9f50fdbdc5b5a74c2146997496bad5fd7f7422ec90b7**, height_hint=577007
2019-05-29 22:48:39.823 [INF] DISC: Authenticated Gossiper is starting
2019-05-29 22:48:39.823 [INF] BRAR: Starting contract observer, watching for breaches.
2019-05-29 22:48:39.824 [INF] NTFN: New block epoch subscription
2019-05-29 22:48:40.613 [INF] CRTR: FilteredChainView starting
2019-05-29 22:48:40.758 [INF] NTFN: Dispatching 1 confirmation notification for txid=b2a759675e0a33a6702a9f50fdbdc5b5a74c2146997496bad5fd7f7422ec90b7
2019-05-29 22:48:40.758 [INF] CNCT: *contractcourt.commitSweepResolver(a2f3f8d97b815daea481ad9fe536ef2a3860c7e4104ccee56ff3d998162cc426:1): sweeping commit output
**2019-05-29 22:48:40.777 [INF] SWPR: Sweep request received: out_point=b2a759675e0a33a6702a9f50fdbdc5b5a74c2146997496bad5fd7f7422ec90b7:0, witness_type=CommitmentNoDelay, time_lock=0, amount=0.00001209 BTC, fee_preference=6 blocks**
2019-05-29 22:48:40.778 [INF] NTFN: New spend subscription: spend_id=3, outpoint=b2a759675e0a33a6702a9f50fdbdc5b5a74c2146997496bad5fd7f7422ec90b7:0, height_hint=578413

**Comment by Roasbeef** [comment]
@danbadjar the channel only has 1k satoshis remaining, atm we won't sweep outputs that small since we'd pay more in fees than we'd actually obtain ultimately.

**Comment by danbadjar** [comment]
Hello @Roasbeef and thanks for your response.
So, just to be clear, I should expect that the force close channel will be there "forever" or in case of lower fees the sweep could be executed?
Thanks in advice

**Comment by wpaulino** [comment]
Correct, so until fees are low enough that it can be swept, the pending channel record will persist until the sweep transaction has confirmed.

**Comment by danbadjar** [comment]
Thank you very much for the help

**Comment by ac-com-au** [comment]
![zap](https://user-images.githubusercontent.com/3029233/58760193-e91b6580-8577-11e9-8f3a-4a253981968a.JPG)

**Comment by ac-com-au** [comment]
problem solved
reinstalled bitcoind to  v 0.18.0 
Thank you all for help
