### ISSUE TITLE
Fee zero - is it possible to change in LND?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3138]
Now the LND has minimum fee rate as 1/1,000,000
If i try to use zero i get error "fee rate of 0 is too small, min fee rate is 1e-06" (v0.6.1-beta)

But other nodes already has fee as 0 / 0: [ACINQ channel example](https://1ml.com/channel/635796996973068288) (and capacity 1 BTC too! ;-)

It turns out that all nodes based on LND software will be noncompetitive with Eclair software... Is it possible to allow fee rate & base fee as **0**?

**Comment by Roasbeef** [comment]
A fee rate of 1 msat is essentially zero. But yes you're correct that we currently don't permit that value to be set to zero atm. I wouldn't say 0 vs 1 msat for fees will make an implementation competitive or non-competitive as that's not the only thing that path finding takes into account. What will make a _node_ competitive is proper management of their established channels, not over saturating the network with their own channels, and high availability.
