### ISSUE TITLE
Channels stuck on Pending_Force_closing but final txs have been confirmed.

### ISSUE THREAD

**Issue by ElCapitano11** [lightningnetwork/lnd#3144]
### Background
Long story short: Ran a raspiblitz, lnd stopped working. I'm trying all the recovery methods on their github. In the mean time I asked peers to close channels with me. 
In an attempt to recover funds I installed this LND Desktop App on mac. Follow this: https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-move-funds--channels-from-raspiblitz-to-lnd-lightning-desktop-app
It has worked a little, since I am now able to see the state of my channels. 
![Screenshot 2019-05-31 at 02 12 41](https://user-images.githubusercontent.com/46606158/58654126-cefc4000-8349-11e9-80ed-6b5b32576f7e.png)

Describe your issue here.
The 3 channels that I asked my peers to close are still showing Pending Force Closing. Since 10May19, but the final txs have been confirmed. example:
![Screenshot 2019-05-31 at 02 03 12](https://user-images.githubusercontent.com/46606158/58653490-682a5700-8348-11e9-811f-a97dc3913943.png)

Closing transaction ID: https://blockstream.info/tx/2d60e50201b2c9102b3d50e1c33f9223bb53c5b90ac9ee7a1134f5f4daf9b8e2

The inactive channels I am unable to close.

The log is showing this:

 Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Getting channel balance failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Getting new wallet address failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Listing peers failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Listing channels failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Listing pending channels failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

ERROR: Listing closed channels failed
{
    "code": 14,
    "details": "Connect Failed",
    "metadata": {
        "_internal_repr": {}
    }
}

### Your environment

* version 0.5.1-alpha.3565)
* which operating system (Mac OS 10.14.5)
* transfered files came from raspiblitz v1.2

Any help fixing this issue is kindly appreciated.

**Comment by Roasbeef** [comment]
The app isn't able to connect to your node at all from those error logs. I'm not sure if those instructions work properly, I've never tried them out myself.

**Comment by wpaulino** [comment]
Closing due to no updates.
