### ISSUE TITLE
Payments made with sendtoroute do not reflect the paid amounts in listpayments

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#3146]
In `19fafd7a9a5fe4ba05a6250aae748f2b7465ea05` the behavior of listpayments changes to no longer return the sent value of payments made with sendtoroute

Prior to this commit, sendtoroute payments values could be accessed via listpayments

After this commit, the values are returned as 0 instead of their actual amount

The expected value for these payments is the route total amount - total fees

**Comment by ksedgwic** [comment]
I think I'm seeing this:

```
        {
            "payment_hash": "352a2df60a19175f06cb5fa9993436e3a0f16cee5b32cfba8dd8b1fcf82ccef5",
            "value": "0",
            "creation_date": "1559353582",
            "path": [
                "0234d70cf65a4e8974d3d49e23ec7b9792877f783f2f5dfd3882422aada18a916c",
                "02a5fa844d310f582d209fe649352b225440b8a54e77361f229bb92ee263c87e6f",
                "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
                "02a5fa844d310f582d209fe649352b225440b8a54e77361f229bb92ee263c87e6f"
            ],
            "fee": "3",
            "payment_preimage": "16bd366b68d34960f16436fd5ca93cf67745c40d7c143204534a5e6f5a8599da",
            "value_sat": "0",
            "value_msat": "0"
        },
￼```

Sending with:
```
		sendRsp, err := router.SendToRoute(ctxt, &routerrpc.SendToRouteRequest{
			PaymentHash: invoiceRsp.RHash,
			Route: route,
		})
```
Version:
```
lnd version 0.6.1-beta commit=v0.6.1-beta-181-g1b5655f7fab463558b0e6a4120339581e810c096
```

**Comment by ksedgwic** [comment]
### Background

While rebalancing channels using loops created with QueryRoutes and
routerrpc SendToRoute sends are not credited to the
destination channel.

### Your environment

* mainnet
* lnd version 0.6.1-beta commit=v0.6.1-beta-181-g1b5655f7fab463558b0e6a4120339581e810c096
* Linux home2 4.15.0-48-generic #51~16.04.1-Ubuntu SMP Fri Apr 5 12:01:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8

### Steps to reproduce

The code is available here:

https://github.com/ksedgwic/lndtool/blob/a142ad8d29152e54b2ea78c278c14139e5102d69/rebalance.go

After running `lndtool recommend` a target source and destination
channel is automatically selected and QueryRoutes is run to find a
loop.  Each possible loop route is tried using SendToRoute until a
payment succeeds.

### Expected behaviour

I expected `lncli listpayments` to display a paid invoice like this:

```
{
    "payment_hash": "e378c21f6fd82dd95d4218c7a6f7f0277941cc87aac0004d6c23343c07f7ae28",
    "value": "10000",
    "creation_date": "1559319374",
    "path": [
        "02a04446caa81636d60d63b066f2814cbd3a6b5c258e3172cbdded7a16e2cfff4c",
        "038d43a1ef03a7882dc74729db276b575fcda8205e66b6a1b544c09ac86d0e2794",
        "0395033b252c6f40e3756984162d68174e2bd8060a129c0d3462a9370471c6d28f",
        "02a5fa844d310f582d209fe649352b225440b8a54e77361f229bb92ee263c87e6f"
    ],
    "fee": "0",
    "payment_preimage": "9baaed8d638bd429408802be2f74e3adf37030cf475ba5704c3cf5188757ee93",
    "value_sat": "10000",
    "value_msat": "10000000"
},
```

### Actual behaviour

Instead a payment with 0 value is displayed:

```
{
    "payment_hash": "5d198c5afb2604c0e1546604ec4ed260c15fc30ec1c629a5fbd9c9c5467bb204",
    "value": "0",
    "creation_date": "1559351866",
    "path": [
        "0234d70cf65a4e8974d3d49e23ec7b9792877f783f2f5dfd3882422aada18a916c",
        "0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3",
        "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
        "02a5fa844d310f582d209fe649352b225440b8a54e77361f229bb92ee263c87e6f"
    ],
    "fee": "2",
    "payment_preimage": "29ec07cc44f47e54d6032a03c6f5fb569f72d5976a97dc737193842c588f3b6b",
    "value_sat": "0",
    "value_msat": "0"
},
```

**Comment by ksedgwic** [comment]
@aliexbosworth I'm confused about the state of my channels which encountered this problem; is the channel state ok?  Or is my node confused about the local balance?

**Comment by alexbosworth** [comment]
I don't think there's a state issue since when I repro'ed it I could just modify the code to recalculate the amount paid from the route and it showed the correct amount

It seems to just be an RPC issue

**Comment by ksedgwic** [comment]
Is there a possibility I could retreat my version to before the suspected mods but still after the DB change?  Is this worth a try?

**Comment by alexbosworth** [comment]
No I wouldn't try it

**Comment by alexbosworth** [comment]
There may be a state issue here so if these amounts are important to you I would avoid making more sendtoroute payments for the time being, even though I confirmed that the data is retained in one place there may be missing duplication of the data for record keeping purposes

**Comment by ksedgwic** [comment]
Ok, sounds good.  I'll work on improving some other parts of my program for now.

**Comment by alexbosworth** [comment]
@ksedgwic you might want to confirm this fixes the issue for you, it should be solved conclusively though
