### ISSUE TITLE
Docker: Cannot change entrypoint to change lnd parameters

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#3148]
### Background

I am playing around with the dockerfiles for LND found inside `docker/`. I have followed the example from the Readme, which works. Now what I would like to do is to use the `admin.macaroon` and `tls.cert` to connect to the LND docker instance from the host. It looks as if by default LND will not allow me to connect to it via gRPC from the host machine, as it only allows localhost connections? I have successfully copied the `tls.cert` and exported the `admin.macaroon` as hex and converted it back to binary on the host machine but cannot connect to the LND docker instance and also the port shows as closed using `nmap -p 10009 172.31.0.3` from the host machine.

I was therefore thinking about changing the entrypoint of the Dockerfile to allow me to add parameters to the `lnd` execution. The entrypoint is the bash script `start-lnd.sh`, which at the end contains the following execution:
```
exec lnd \
    --noseedbackup \
    --logdir="/data" \
    "--$CHAIN.active" \
    "--$CHAIN.$NETWORK" \
    "--$CHAIN.node"="btcd" \
    "--$BACKEND.rpccert"="/rpc/rpc.cert" \
    "--$BACKEND.rpchost"="blockchain" \
    "--$BACKEND.rpcuser"="$RPCUSER" \
    "--$BACKEND.rpcpass"="$RPCPASS" \
    --debuglevel="$DEBUG" \
    "$@"
```

So that I can connect from the host to the LND instance (e.g. with IP `172.31.0.3`) via gRPC, I am simply trying to change the execution of `lnd` to: 
```
exec lnd \
    --noseedbackup \
    --logdir="/data" \
    --rpclisten=0.0.0.0:10009 \
    --tlsextraip=172.31.0.3 \
    --externalip=172.31.0.3 \
    "--$CHAIN.active" \
    "--$CHAIN.$NETWORK" \
    "--$CHAIN.node"="btcd" \
    "--$BACKEND.rpccert"="/rpc/rpc.cert" \
    "--$BACKEND.rpchost"="blockchain" \
    "--$BACKEND.rpcuser"="$RPCUSER" \
    "--$BACKEND.rpcpass"="$RPCPASS" \
    --debuglevel="$DEBUG" \
    "$@"
```

But simply changing those lines inside `start-lnd.sh` does not change the actual execution when running `docker-compose run -d -p 10009:10009 --name alice lnd_btc`, as can be seen when doing
`docker exec -i -t alice bash`:
```
bash-4.4# ps -lA
PID   USER     TIME  COMMAND
    1 root      0:03 lnd --noseedbackup --logdir=/data --bitcoin.active --bitcoin.simnet --bitcoin.node=btcd --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=blockchain --btcd.rpcuser=devuser --btcd.rpcpass=devpass --debuglevel=debug
   33 root      0:00 bash
   38 root      0:00 ps -lA
```

I am probably doing something wrong when changing the `Dockerfile` for lnd, or there is an easy solution that I cannot see. Any help would be very much appreciated!

Thanks!

**// Edit**: When overriding the Entrypoint directly as in `docker-compose run -d -p 10009:10009 --entrypoint="lnd --noseedbackup --logdir=/data --rpclisten=0.0.0.0:10009 --tlsextraip=172.31.0.3 --externalip=172.31.0.3 --bitcoin.active --bitcoin.simnet --bitcoin.node=btcd --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=blockchain --btcd.rpcuser=devuser --btcd.rpcpass=devpass --debuglevel=debug" --name alice lnd_btc` then I am able to connect to it. So it seems this is unrelated to LND and a misconfiguration/unknowledge on my behalf regarding Docker and therefore feel free to close this issue. But if anyone knows a solution I am still looking for one :)

### Your environment

* version of `lnd`: 0.6.1-beta commit=v0.6.1-beta-186-g4068e78af690f9b4a598de1f3f0b21b5560dd146
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

**Comment by wpaulino** [comment]
> So it seems this is unrelated to LND and a misconfiguration/unknowledge on my behalf regarding Docker and therefore feel free to close this issue.

Closing per this comment.
