### ISSUE TITLE
Add update external IP RPC

### ISSUE THREAD

**Issue by frennkie** [lightningnetwork/lnd#3157]
It would be create to have an RPC for setting/updating the external IP.
I know that there is the option `nat=true` which sets up an external IP watcher (for NAT-PMP and UPnP) - but this is not a universal solution.

Therefore it would be good if users could use the technology of theirs choice outside of LND to detect changes and the set them over RPC (without needing to stop and start the whole LND process).

**Comment by frennkie** [comment]
@halseth It mentioned this to you in Munich.. sadly I currently have no time to work on an PR.. maybe later in June... :-D

**Comment by frennkie** [comment]
This issue is also resolved by #1624, correct?

**Comment by wpaulino** [comment]
If you were interested in having a hostname be resolved automatically to an IP and handle changes, then yes.

**Comment by frennkie** [comment]
Yes, I think #4281 will cover my use case - thanks!
