### ISSUE TITLE
Add a 'outgoing_chan_id' parameter to queryroutes

### ISSUE THREAD

**Issue by ashleyholman** [lightningnetwork/lnd#3158]
Similar to how the `sendpayment` API has a `outgoing_chan_id` parameter to define the channel to use for the first hop, it would be useful to also be able to specify this with `queryroutes`.

My use case is that I'm rebalancing channels, and started with the script from https://github.com/C-Otto/rebalance-lnd/.  I wanted to modify the script to use my preferred first hop, then realized it isn't supported on the API side.

**Comment by alexbosworth** [comment]
You could ignore-edge all the edges except one

**Comment by ashleyholman** [comment]
@alexbosworth sounds promising, but I can't see any such option in `queryroutes --help` or in sample-lnd.conf or `lnd --help`.  Where can I find this feature?  I'm running 0.6.1-beta.

**Comment by wpaulino** [comment]
You can upgrade to the master branch, but beware that there is a migration that'll prevent you from going back to v0.6.1. If you're not comfortable doing so then I'd suggest waiting for the next v0.7 release.

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3158#issuecomment-498803386
