### ISSUE TITLE
Docker - Digital Ocean - marketplace image - get started with a single click... 

### ISSUE THREAD

**Issue by marsrobertson** [lightningnetwork/lnd#3159]
## Installation

* https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md
* Alternative: https://gist.github.com/bretton/0b22a0503a9eba09df86a23f3d625c13
* Yet another alternative: https://medium.com/coinmonks/the-lightning-network-how-to-install-and-hopefully-make-money-6e3058e3fa7c

In all instances it takes many steps, multiple hops, multiple dependencies, multiple days wait time.

I actually spent some time thinking about what are the minimum requirements in terms of storage, CPU, RAM: https://lightningcommunity.slack.com/archives/C6BDA6DGE/p1559654394006200?thread_ts=1559382765.103900&cid=C6BDA6DGE

<img src="https://user-images.githubusercontent.com/44369284/58885777-b047d180-86da-11e9-9ece-4cb79c544295.png" width="380">

_(mental fatigue, each decision reduces my remaining brainpower)_

## Digital Ocean

![image](https://user-images.githubusercontent.com/44369284/58885321-e3d62c00-86d9-11e9-9316-18a1ffa70a97.png)

Here are the instructions on how to add your image to Digital Ocean  marketplace: https://marketplace.digitalocean.com/vendors/getting-started-as-a-digitalocean-marketplace-vendor

> By making your app available in the DigitalOcean Marketplace, it will be searchable and visible to our global community of 3.5 million developers.

**Lightning Network on your private server can be as simple as a single click ⚡️⚡️⚡️**

Just like here, unfairly easy: https://medium.com/lightning-power-users/windows-macos-lightning-network-284bd5034340

----

Issues related to Docker: #2827 #2266

**Comment by Roasbeef** [comment]
We don't have plans atm to create a version of `lnd` for the Digital Ocean Marketplace. I think our current docker solutions get us pretty far, but we may re-examine this in the future.

**Comment by marsrobertson** [comment]
Docker gets you pretty far... I'm still in "analysis paralysis" mode, not sure what are the minimal hardware requirements for that.

![image](https://user-images.githubusercontent.com/44369284/59157338-629be200-8aa9-11e9-9fc3-fe7aa151b8a4.png)

_(pretty sure running LND without docker is more performance efficient)_

In the meanwhile using [OpenNode](https://www.opennode.co/) to accept payments.
