### ISSUE TITLE
SIGINT does not shut down lnd when backend node is unreachable

### ISSUE THREAD

**Issue by OttoAllmendinger** [lightningnetwork/lnd#3166]
### Background

Lnd doesn't shut down on `SIGINT` when neutrino backend is unavailable (maybe other backends are affected as well)

### Your environment

* `lnd version 0.6.1-beta`
* `Linux 1f63d48b9f57 5.1.6-arch1-1-ARCH #1 SMP PREEMPT Fri May 31 15:17:53 UTC 2019 x86_64 Linux`

### Steps to reproduce

Start a fresh lnd and specify an address for the neutrino backend where no service is running (`127.0.0.1:11111` in this case)
 
```bash
    lnd \
      --configfile=/dev/null \
      --debuglevel=debug \
      --datadir=/tmp/lnd \
      --logdir=/tmp/lnd/logs \
      --tlscertpath=/tmp/lnd/tls.cert \
      --tlskeypath=/tmp/lnd/tls.key \
      --rpclisten=127.0.0.1:10009 \
      --nobootstrap \
      --bitcoin.active \
      --nolisten \
      --bitcoin.simnet \
      --noseedbackup \
      --bitcoin.node=neutrino \
      --neutrino.connect=127.0.0.1:11111 &
  sleep 1
  kill -SIGINT $! # lnd will hang at `CHBU: Stopping chanbackup.SubSwapper`
```

### Expected behaviour

The SIGINT signal should trigger a clean lnd shutdown.

### Actual behaviour

LND hangs and tries to connect to the backend. It can be stopped via `kill -9`

Via `printf` debugging I pinpointed the location where it hangs for me:

* https://github.com/lightningnetwork/lnd/blob/880279/chanbackup/pubsub.go#L208
* https://github.com/lightningnetwork/lnd/blob/880279/chanbackup/pubsub.go#L179
* https://github.com/lightningnetwork/lnd/blob/880279/chanbackup/multi.go#L92
* https://github.com/lightningnetwork/lnd/blob/880279/chanbackup/crypto.go#L67
* https://github.com/lightningnetwork/lnd/blob/880279/chanbackup/crypto.go#L37
* https://github.com/lightningnetwork/lnd/blob/880279/keychain/btcwallet.go#L208 -- the callback to `Update()` never gets called

Because `lnd` doesn't advance past `s.updateBackupFile()`, it doesn't enter the `select` call for the quit channel.

**Comment by wpaulino** [comment]
Tried to reproduce locally and it gets stuck here:

```
1 @ 0x1030e1f 0x104ddd9 0x104ddaf 0x158bb41 0x158bfae 0x158b9f0 0x1597769 0x105e331
#	0x104ddae	time.Sleep+0x12e									/usr/local/go/src/runtime/time.go:105
#	0x158bb40	github.com/btcsuite/btcwallet/wallet.(*Wallet).scanChain+0x100				/Users/user/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190524003533-2c05240dff28/wallet/wallet.go:527
#	0x158bfad	github.com/btcsuite/btcwallet/wallet.(*Wallet).syncToBirthday+0x2ad			/Users/user/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190524003533-2c05240dff28/wallet/wallet.go:561
#	0x158b9ef	github.com/btcsuite/btcwallet/wallet.(*Wallet).syncWithChain+0x4df			/Users/user/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190524003533-2c05240dff28/wallet/wallet.go:328
#	0x1597768	github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications.func1+0x38	/Users/user/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190524003533-2c05240dff28/wallet/chainntfns.go:43
```

Will be fixed by #3141.
