### ISSUE TITLE
Feature request: `decodepayreq` grpc should have an option to not include route hints

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#3171]
### Background

When calling the `decodepayreq` grpc method it seems to take extra time and returns route hints.  Presumably this is to give the `sendpayment` a route hint when you subsequently call that rpc but if I understand the workflow correctly `sendpayment` will still need to calculate the route.

### Your environment

* version of `lnd` lncli version 0.6.1-beta commit=v0.6.1-beta-228-gaa5156a1a985ef3e0b1e6ad48a081125a465870d
* which operating system - OSX / docker / ubuntu
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.17
* any other relevant environment details

### Steps to reproduce

```
$ lncli decodepayreq LNBC1U1PW0J5PNRZJQWRYAUP9LH50KKRANZGCDNN2FGVX390WGJ5JD07RWR3VXEJE0GLC7Z93ASQQDNQQQQQQQQLGQQQQQEQQJQFPPQC9YXPVZVQUH32TQLR2ZHLSUX730GY2S0DQQCQZZGPP5PF4U6QGJQYNXKK6UN8YKSJCN0VCXSW3JMKPH0Z0J0VSHQEP2CL9SXQYZ5VPTD6F7HJ7A6RPUM7RRVFH95J99NM3LVHCKN3PGWFF7KMKMVKCJS0XXC6Q6EV59KJL3C864C33XVZ77HL9L7TJ3JMDMQLRDHE53UH068GPER4WHT
```

### Expected behaviour

There should be an option to disable route hints and just return the decoded payment request (I think!)

### Actual behaviour

Route hints are found each time.

**Comment by wpaulino** [comment]
How much more extra time is it taking?

**Comment by PWKad** [comment]
About ~5 seconds maybe?  I don't know if there is an easy way to profile why it is taking so long I guess I could try it from the command line and see if there is latency there as well, was just observing through grpc thus far.

**Comment by Roasbeef** [comment]
FWIW that isn't a valid payreq (though it may have been on purposes?). 

The call itself is purely CPU bound, so there's no additional I/O done in order to decode a payreq. It could even be moved to exist entirely in `lncli`. Are you able to obtain a CPU profile when you issue the call? Also do you have any other scripts that are regularly hitting the RPC interface?

**Comment by PWKad** [comment]
Checking from the command line your both right there is near zero time spent, going to keep checking it from grpc and see if I can find any other reason it's taking longer sorry for the false report, will close for now unless I find anything concrete.
