### ISSUE TITLE
same as 3078: lncli does not find tls.cert and tls.key after deleting them

### ISSUE THREAD

**Issue by emplexity** [lightningnetwork/lnd#3175]
### Background

faced the issue #3078, addressed it as advised by deleting the tls.key and .cert, kill -9 lnd by pid, restarted lnd with nohup lnd &, launched lncli unlock and get the message 
[lncli] open /home/beersel/.lnd/tls.cert: no such file or directory

retried the above 2 times with the same behaviour

### Your environment

* version of `lnd` lnd version 0.5.1-beta commit=v0.5.1-beta-rc3-2-g712fc3ebed1c9e0df6bad2b240acce1a0804b1d2-dirty
* which operating system (`Ubuntu 16.4)
* version of `btcd`, `bitcoind`, or other backend: v0.16.3.0-g49e34e288

* any other relevant environment details

### Steps to reproduce

launch lnd followed by lncli unlock
Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
lncli unlock must unlock lnd once the right pw is entered
Tell us what should happen

### Actual behaviour
message
[lncli] open /home/beersel/.lnd/tls.cert: no such file or directory

**Comment by wpaulino** [comment]
Is lnd properly starting up after the restart? Are you using any configuration options that would result in the certificate being created in a different directory?

**Comment by emplexity** [comment]
Thanks for the quick feedback.
Everything turned out fine after the nightly reboot and orderly restart of bitcoind and lnd. The tls.key and tls.cert were created as advertised in #3078, where they have to. I can now use lncli again without error message.
So I guess the problem was an issue on my side when trying to address the first issue when I encountered it.
Apologize for the noise.

**Comment by cfromknecht** [comment]
@emplexity that’s also an ancient version of lnd (9 months old), updating is highly recommended
