### ISSUE TITLE
Lnd panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by omkarsunku** [lightningnetwork/lnd#3185]
### Background

When I restart the lnd I am get the below error

**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x58c50e]**
### Your environment

* version of `lnd`
**lnd version 0.6.1-beta**
* which operating system (`uname -a` on *Nix)
**Linux ubuntu-18 4.15.0-50-generic**
* version of `btcd`, `bitcoind`, or other backend
**bitcoind version  v0.18.0.0**

### Expected behaviour
lnd should restart properly or indicate if something has been corrupted.

### Actual behaviour

lnd start crashes with the below logs.
2019-06-11 05:54:27.460 [TRC] CRTR: node=303331363331346462346562353432643137623961376163366636363531666362333139666433646132373931393764346630396138393066633330336563663264 reported failure when sending htlc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x58c50e]

goroutine 569 [running]:
crypto/ecdsa.Verify(0xc000285b00, 0xc0001d40a0, 0x20, 0x20, 0xc0107969e0, 0xc010796a00, 0xc000134990)
        /usr/local/go/src/crypto/ecdsa/ecdsa.go:237 +0x4e
github.com/btcsuite/btcd/btcec.(*Signature).Verify(...)
        /root/gocode/pkg/mod/github.com/btcsuite/btcd@v0.0.0-20190605094302-a0d1e3e36d50/btcec/signature.go:77
github.com/lightningnetwork/lnd/routing.VerifyChannelUpdateSignature(0xc0000ce630, 0xc000285b00, 0x0, 0x0)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/ann_validation.go:155 +0x1dd
github.com/lightningnetwork/lnd/routing.ValidateChannelUpdateAnn(0xc000285b00, 0xf42400, 0xc0000ce630, 0xc0000342c0, 0xc000134630)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/ann_validation.go:136 +0x70
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).applyChannelUpdate(0xc0000ce420, 0xc0000ce630, 0xc000285b00, 0x7d1979a23dfd19b3)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:2077 +0x176
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).processSendError(0xc0000ce420, 0x1457520, 0xc01097f840, 0xc0107c1a50, 0xc010a7e1e0, 0xc0001d26c0)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:1949 +0x491
github.com/lightningnetwork/lnd/routing.(*paymentLifecycle).handleSendError(0xc000252230, 0x1438420, 0xc010a7e1e0, 0xc0107967e0, 0x2)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/payment_lifecycle.go:348 +0x25f
github.com/lightningnetwork/lnd/routing.(*paymentLifecycle).resumePayment(0xc000252230, 0x0, 0x0, 0x0, 0x0, 0x1, 0x10a6480, 0x110f101)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/payment_lifecycle.go:150 +0x56f
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).sendPayment(0xc0000ce420, 0xc0107c1a40, 0xc0004bf130, 0x1457520, 0xc01097f840, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:1794 +0x1f6
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start.func1(0xc0000ce420, 0xc010a5a730, 0xc0000a10a0)
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:538 +0xfb
created by github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start
        /root/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:526 +0x33c

**Comment by omkarsunku** [comment]
I am using the latest version on lnd.
lnd version 0.6.1-beta commit=v0.6.1-beta-242-ge45d4d703aec0645cacdbd3f286ade860c0b3d45

**Comment by halseth** [comment]
@omkarsunku Can you try running with #3195 and see if it resolves your issue?

If not, can you post full logs from startup until crash? :)

**Comment by omkarsunku** [comment]
I tried #3195 but still the same error. Below are the logs


[lnd.log](https://github.com/lightningnetwork/lnd/files/3281235/lnd.log)

**Comment by halseth** [comment]
Thanks! 🙏 

Very interesting... I don't see immediately where the pubkeys are getting nilled tbh. 

@omkarsunku  If you can run with the following patch on top of #3195 then maybe we can check if they are nilled all along (might be spammy, but that is a good sign):

```diff
diff --git a/routing/router.go b/routing/router.go
index dfa47582c..cf58cce2f 100644
--- a/routing/router.go
+++ b/routing/router.go
@@ -1463,6 +1463,13 @@ func generateSphinxPacket(rt *route.Route, paymentHash []byte,
                return nil, nil, err
        }

+       log.Tracef("original Constructed per-hop payloads for payment_hash=%x: %v",
+               paymentHash[:], newLogClosure(func() string {
+                       path := sphinxPath[:sphinxPath.TrueRouteLength()]
+                       return spew.Sdump(path)
+               }),
+       )
+
        log.Tracef("Constructed per-hop payloads for payment_hash=%x: %v",
                paymentHash[:], newLogClosure(func() string {
                        path := make([]sphinx.OnionHop, sphinxPath.TrueRouteLength())
@@ -1475,6 +1482,13 @@ func generateSphinxPacket(rt *route.Route, paymentHash []byte,
                }),
        )

+       log.Tracef("original2 Constructed per-hop payloads for payment_hash=%x: %v",
+               paymentHash[:], newLogClosure(func() string {
+                       path := sphinxPath[:sphinxPath.TrueRouteLength()]
+                       return spew.Sdump(path)
+               }),
+       )
+
        // Next generate the onion routing packet which allows us to perform
        // privacy preserving source routing across the network.
        sphinxPacket, err := sphinx.NewOnionPacket(
@@ -1491,6 +1505,12 @@ func generateSphinxPacket(rt *route.Route, paymentHash []byte,
                return nil, nil, err
        }

+       log.Tracef("original Generated sphinx packet: %v",
+               newLogClosure(func() string {
+                       return spew.Sdump(sphinxPacket)
+               }),
+       )
+
        log.Tracef("Generated sphinx packet: %v",
                newLogClosure(func() string {
                        // We make a copy of the ephemeral key and unset the
@@ -1504,6 +1524,12 @@ func generateSphinxPacket(rt *route.Route, paymentHash []byte,
                }),
        )

+       log.Tracef("original2 Generated sphinx packet: %v",
+               newLogClosure(func() string {
+                       return spew.Sdump(sphinxPacket)
+               }),
+       )
+
        return onionBlob.Bytes(), &sphinx.Circuit{
                SessionKey:  sessionKey,
                PaymentPath: sphinxPath.NodeKeys(),
```

**Comment by omkarsunku** [comment]
@halseth @Roasbeef  I am really sorry guys I am running two nodes one pruned and one full node. I got this error since the lnd connected to pruned node. Really Sorry guys thanks for support @halseth .

**Comment by halseth** [comment]
@omkarsunku I don't think this is related to whether the node is pruned or not. Are you saying this only happens with the pruned backend?

**Comment by omkarsunku** [comment]
Yes @halseth since this time I got the below error:
Failed getting conf details from index (unable to query for txid f533b36569b5762118db328d7216223f6c8dfc64cc50f4bec96c1940c55a7fe2: -5: No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.), scanning manually

I guess this is completely because of pruned node. Correct?

**Comment by halseth** [comment]
@omkarsunku Yes, but the crash you are seeing seems unrelated to that error. I would like to get to the bottom of why it is happening.
