### ISSUE TITLE
My node doesn't know about its own channels. Help?

### ISSUE THREAD

**Issue by Relaxo143** [lightningnetwork/lnd#3192]
I'm running LND v6.1 beta.

I made a backup of the Lnd dir a while ago and today I needed to restore from it. I thought it would be enough to recover my channels but I was wrong. These 2 channels are open but my node doesn't know about them. Listchannels doesn't show either of them. Is there a way to continue using them or do I just have to hope that my counterparties eventually close them? If they do would I see my btc on chain? (I think I should, the seed and the public key are the same). 

https://1ml.com/channel/637505638024937473
https://1ml.com/channel/631061400401477632

**Comment by Roasbeef** [comment]
> I made a backup of the Lnd dir a while ago and today I needed to restore from it.

This isn't how you should recover an `lnd` node. We have some [new-ish documentation on this topic that you can find here](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md). Put simply, it isn't safe to restore with an existing version, instead you should use your see along with an SCB file or hex.

**Comment by Relaxo143** [comment]
Would running dropwtxmgr be helpful in my case?

**Comment by wpaulino** [comment]
No, as that only recovers funds that pay directly to your wallet, which channel closes don't do at the moment unless closed cooperatively.

**Comment by Relaxo143** [comment]
> No, as that only recovers funds that pay directly to your wallet, which channel closes don't do at the moment unless closed cooperatively.

Where do the funds go if it's a force closure then?

**Comment by wpaulino** [comment]
If you force close, a time-locked output you need to sweep to your wallet after the delay. If the remote party force closes, an output that's tweaked with a random nonce that you also need to sweep to your wallet, but without a delay.

**Comment by wpaulino** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3192#issuecomment-501110895.
