### ISSUE TITLE
router.macaroon not begin generated

### ISSUE THREAD

**Issue by 05nelsonm** [lightningnetwork/lnd#3193]
### Background

Trying to get loopd to work, but when I run lnd it's not generating the necessary router.macaroon

To update lnd I executed:

`$ cd $GOPATH/src/github.com/lightningnetwork/lnd`
`$ git pull`
`$ make clean && make && make install tags="signrpc walletrpc chainrpc invoicesrpc"`

When executing `make check`, I received an error:

> ok  	github.com/lightningnetwork/lnd/zpay32	(cached)
> Makefile:124: recipe for target 'unit' failed
> make: *** [unit] Error 123

Proceeded to install loopd in accordance with their directions:
`& git clone https://github.com/lightninglabs/loop.git`
`$ cd loop/cmd`
`$ go install ./...`

`$ mv ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon ~/Desktop/`
`$ mv ~/.lnd/data/chain/bitcoin/mainnet/invoice.macaroon ~/Desktop/`
`$ mv ~/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon ~/Desktop/`

`$ lnd`

lnd ran and generated:

1. admin.macaroon
2. chainnotifier.macaroon
3. invoice.macaroon
4. invoices.macaroon
5. readonly.macaroon
6. signer.macaroon
7. walletkit.macaroon

but no router.macaroon and I received an error while trying to run loopd:

> 2019-06-12 03:13:00.860 [INF] LOOPD: Version: 0.1.3-alpha commit=
unable to obtain macaroons: open /home/matthew/.lnd/data/chain/bitcoin/mainnet/router.macaroon: no such file or directory

### Your environment

* version of `lnd`
     lnd version 0.6.1-beta commit=v0.6.1-beta-254-g89f6db11e69d8b64d666f8e844528d24dde98efb
* which operating system (`uname -a` on *Nix)
    Linux ubuntu-desktop-vm 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
   bitcoind v0.18.0
* any other relevant environment details
Just installed on this VM go1.12.3.linux-amd64.tar.gz, so that's up-to-date

Not sure if it has anything to do with tor only, but my lnd.conf contains:
> tor.active=1
> tor.socks=127.0.0.1:9055
> tor.control=127.0.0.1:9056
> tor.streamisolation=1
> tor.v3=1

### Expected behaviour

A router.macaroon file should be generated

### Actual behaviour

A router.macaroon file was not generated

**Comment by joostjager** [comment]
Thanks for the detailed report. This problem goes away if you add the `routerrpc` tag to `make`. https://github.com/lightninglabs/loop/pull/61 created that updates `README.md`.

**Comment by Roasbeef** [comment]
Closed by lightninglabs/loop#61
