### ISSUE TITLE
Only allow a single pending channel per-peer

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#32]
Currently the `fundingManager`, and the `rpcServer` will happily allow either a caller or remote peer to create multiple pending channels at a time. This behavior should instead be restricted to only allow a single pending channel at a time per-peer. Such a constraint acts as a defense against a slow-loris like DoS attack wherein a peer creates hundreds of thousands of pending channels, never intending to complete the funding workflow for them.

Steps to completion: 

- the `fundingMgr` should reject all requests to either process or initialize a new channel funding workflow if one already exists for the targeted peer. 

- the `lnwire.ErrorGeneric` messagesshould be sent to the offending peer if the constraint is violated

**Comment by AndrewSamokhvalov** [comment]
I will try to do this one.

**Comment by Roasbeef** [comment]
Fixed by #36. 

Closing.
