### ISSUE TITLE
Makefile build Issue

### ISSUE THREAD

**Issue by rahulasnani** [lightningnetwork/lnd#3200]
Error in installing lnd

can't load package: package github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-266-gc8ef9a4f63b235dd389a8edb09c955ea060ad971: unknown import path "github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-266-gc8ef9a4f63b235dd389a8edb09c955ea060ad971": cannot find module providing package github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-266-gc8ef9a4f63b235dd389a8edb09c955ea060ad971

I am on ubuntu 16.04

I am getting this error when I'm running the command
make && make install

Can someone tell me why I'm getting this?

**Comment by Roasbeef** [comment]
What version of Go are you running?

**Comment by rahulasnani** [comment]
I am using go1.11.5 linux/amd64
@Roasbeef

**Comment by wpaulino** [comment]
I'd suggest upgrading to the latest version of Go and running `go clean -modcache`.

**Comment by rahulasnani** [comment]
Thanks @wpaulino. It worked!
