### ISSUE TITLE
lnd not getting new blocks from bitcoind

### ISSUE THREAD

**Issue by 05nelsonm** [lightningnetwork/lnd#3205]
### Background
lnd not receiving new blocks from bitcoind and falling out of sync

### Your environment

* version of `lnd`: lnd version 0.7.0-beta commit=v0.7.0-beta-rc1
* which operating system (`uname -a` on *Nix): Linux 4.18.0-21-generic #22~18.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v0.18.0
* any other relevant environment details
Running Samourai Dojo Docker as backend with docker ports opened for communication between bitcoind (running in docker container) and lnd (running on host machine).

### Steps to reproduce

1. Install Samourai Dojo v1.0 in accordance with https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_setup.md
2. Copy bitcoind data to Dojo bitcoind container --> https://gist.github.com/05nelsonm/96ad8da7724de3a66f44d6c2d70b361c)
2. Configure Dojo to work with lnd --> https://gist.github.com/05nelsonm/ef55dcc1fb3aa588c8135cd107ee5d8c
3. Install lnd in accordance with https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md
4. Run it

### Expected behaviour
When new blocks are found lnd should be able to fetch them from bitcoind and not fall out of sync

### Actual behaviour
lnd does not receive new blocks and then gets out of sync

**Comment by 05nelsonm** [comment]
So trying to reproduce the exact moment which it hangs up I think I've narrowed it down to some specific conditions. I'm still trying to get a repeatable method, but it has something to do with:

-while bitcoind and lnd are running, lock the screen on Ubuntu Desktop 18.04.
-login to the Zap Android App and access the node remotely.
-in the Zap app, switch back and forth between TX history and wallet (which will proc calls to the node for the wallet balance)
-on the phone, minimize the app (do not close out)
-after about a minute or so, go back into the app and unlock it and switch back and forth between TX history and wallet
-close the app
-wait for a while before unlocking Ubuntu (for blocks to come in)
-lnd has hung up

+I've gotten it to happen 3 or 4 times, but it's not every time... and only when Ubuntu Desktop is locked.
+Also noticed that if I was switching back and forth between TX history and the wallet in the app around the same time a new block came in, that's when it would happen
+not sure if it has something to do with the tls handshake interrupting bitcoind rpc communicating with lnd rpc, but there's something going on there.

**Comment by wpaulino** [comment]
Unable to reproduce - seems related to #3109 since both involve the use of containers.

**Comment by 05nelsonm** [comment]
Been running bitcoind on the host machine as opposed to inside of a Docker container, and everything has been working properly. Closing this issue and chalking it up to that.
