### ISSUE TITLE
Can't update to v0.7.0-beta-rc1

### ISSUE THREAD

**Issue by Razer0123** [lightningnetwork/lnd#3208]
### Background

Can't update to v0.7.0-beta-rc1

### Your environment

v0.6
* which operating system (`uname -a` on *Nix)
0.18
4.15.0-20-generic #21-Ubuntu SMP
### Steps to reproduce

Followed the old update commands

### Expected behaviour

Update

### Actual behaviour

Makefile:94: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by molxyz** [comment]
@Razer0123  What version of Go are you running?

**Comment by Razer0123** [comment]
1.11

**Comment by Razer0123** [comment]
Fixed after updating go
