### ISSUE TITLE
disable auto-pilot by default !!

### ISSUE THREAD

**Issue by vamp111** [lightningnetwork/lnd#3216]
I used the app to restore with seed from another wallet

the app has auto-pilot enabled by default, in the very second it synced it opened up a random channel.....

I try to close it, but its status is on 'Waiting Close"since a month now.........

**Comment by wpaulino** [comment]
The app enables is by default as the point is to onboard users onto lightning as quickly as possible.

Can you include details of the waiting close channel?

**Comment by Roasbeef** [comment]
Wrong repo, you should open this at: https://github.com/lightninglabs/lightning-app/

Alternatively, you can use a raw `lnd` instance to restore your funds

**Comment by vamp111** [comment]
@Roasbeef its the 2nd time I open an issue in the wrong repository, sorry about that!
