### ISSUE TITLE
panic: Unable to synchronize wallet to chain (during restore)

### ISSUE THREAD

**Issue by JimmyMow** [lightningnetwork/lnd#3223]
### Background

When restoring an LND wallet with a seed, LND panics on sync with the following error:

```
panic: Unable to synchronize wallet to chain: unable to perform wallet recovery: failed to store sync information
```

Here is the full error message:

```
2019-06-19 15:11:46.502 [INF] LNWL: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=2500
2019-06-19 15:11:46.505 [INF] LNWL: Seed birthday surpassed, starting recovery of wallet from height=1544150 hash=00000000000d71fb89ae8a84ad174ce9fa62b63ca1a040ddeaffa901ddfaf07b with recovery-window=2500
panic: Unable to synchronize wallet to chain: unable to perform wallet recovery: failed to store sync information 00000000000d71fb89ae8a84ad174ce9fa62b63ca1a040ddeaffa901ddfaf07b: failed to fetch block hash for height 1544149: block not found

goroutine 133705 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc0001e8a00)
	/Users/conner/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190614043544-a335c566148c/wallet/chainntfns.go:117 +0x149d
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	/Users/conner/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190614043544-a335c566148c/wallet/wallet.go:191 +0x153
```

After doing a quick GH investigation, my hunch would be this `btcwallet` PR:

https://github.com/btcsuite/btcwallet/pull/618
https://github.com/btcsuite/btcwallet/blob/a335c566148cfbe4a90e191564f2146525fe5861/wallet/chainntfns.go#L117

I've been able to reproduce by simply restoring with seed, but only have tested while using `neutrino` as the backend. 

### Your environment

* version of `lnd`
0.7.0-rc-1

* version of `btcd`, `bitcoind`, or other backend
Neutrino

### Steps to reproduce

- Create a new LND wallet with seed
- Attempt to restore with seed

**Comment by wpaulino** [comment]
Thanks for the report @JimmyMow! This should be fixed by https://github.com/btcsuite/btcwallet/pull/627.

**Comment by JimmyMow** [comment]
Nice one @wpaulino

**Comment by jacohend** [comment]
I just encountered this same issue in 12.1 beta, similar stack trace:
```
goroutine 259 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc00003e140)
/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20201207233335-415f37ff11a1/wallet/chainntfns.go:117 +0x13fb
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20201207233335-415f37ff11a1/wallet/wallet.go:201 +0x1cb
```

**Comment by wpaulino** [comment]
@jacohend could you open a new issue including some more details? What backend version you're running and the panic message would be helpful.

**Comment by jacohend** [comment]
@wpaulino I found a newer version of this issue here: lightningnetwork/lnd#729

**Comment by Bitcoinnoobie** [comment]
I am getting the same issue
Os : lubuntu
I am getting this error when i try to unlock the wallet
