### ISSUE TITLE
Unable to change a private channel to make it public

### ISSUE THREAD

**Issue by sohomang** [lightningnetwork/lnd#3230]
### Background

No API command permits to change a private channel to make it public (and _vice versa_). Some wallets like Zap iOS open channels as private by default and this characteristic seems unalterable for now.

### Your environment

* lnd version 0.6.1-beta
* bitcoind version v0.18.0
* Raspbian GNU/Linux 9 (Stretch)

### Steps to reproduce

* Open a channel from GUI/CLI and make it private (somehow)
* ???
* Profit

### Expected behaviour

A command should exist to let users toggle their channels' privacy settings while they're open/active.

### Actual behaviour

Users have to `closechannel` then `openchannel` again to reset their `private` setting, which pollutes the blockchain with 2 transactions.

**Comment by Roasbeef** [comment]
It isn't possible to do so atm at the protocol level. This would require protocol changes. A better place to open this issue is at: https://github.com/lightningnetwork/lightning-rfc

Thanks!
