### ISSUE TITLE
Add closing_txid to WaitingCloseChannel rpc

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#3234]
### Background

I am trying to parse through my transactions using listchaintxns. I am unable to determine the difference between a waiting close channel and an incoming on chain transaction with zero confirmations. 

Both ForceClosedChannel and ClosedChannel contain closing_txid already. It makes sense to add closing_txid to WaitingCloseChannel as well. 

### Your environment

* version of `lnd`
0.6.1-beta commit=v0.6.1-beta
* which operating system (`uname -a` on *Nix)
Linux lnd 4.14.70-v7+ #2 SMP Wed Sep 19 07:49:26 UTC 2018 armv7l Linux
* version of `btcd`, `bitcoind`, or other backend
bitcoind: 0.17.0
* any other relevant environment details
bitcoind and lnd are running in docker containers
raspberry pi 3b+

### Steps to reproduce

1. Open a channel with anyone
2. Wait for channel to be fully confimed 
3. Generate new address
4. Send a transaction to newly created address
5. Close channel before the transaction from step 4 is confirmed
6. run `lncli listchaintxns` and try to determine which of the two unconfirmed transactions is a channel close

### Expected behaviour

Should be able to determine which transactions are for closing channels.

### Actual behaviour
Unable to determine which transactions are for closing channels.

**Comment by Roasbeef** [comment]
We don't really know what the closing TXID is when a channel is in the waiting close state. This is due to the fact that the remote side may be closing out on chain, or our attempted close is actually a double spend (non replacement) which we'll discover once the funding outpoint hits the chain.

**Comment by wpaulino** [comment]
An alternative solution would be with https://github.com/lightningnetwork/lnd/issues/2597.

**Comment by stridentbean** [comment]
> We don't really know what the closing TXID is when a channel is in the waiting close state. This is due to the fact that the remote side may be closing out on chain, or our attempted close is actually a double spend (non replacement) which we'll discover once the funding outpoint hits the chain.

It looks like lnd _does_ know the tx_hash immediately when a channel is closed. Here is an example of a testnet transaction. I closed the channel cooperatively and ran listchaintxns. The result below shows the txn and the fact that it has 0 confirmations.
```
{
  "tx_hash": "3a1f080b82704a60a2959cd1be32f4a7e019c55897e1bf45d2de830e06601728",
  "amount": "99817",
  "num_confirmations": 0,
  "block_hash": "",
  "block_height": 0,
  "time_stamp": "1561413309",
  "total_fees": "0",
  "dest_addresses": [
  ],
  "raw_tx_hex": "02000000000101758d01614a0738e71e8d9af3d5be1b8d279acbe4cf87912ae0978c718581f3e20000000000ffffffff01e98501000000000016001417428478304e2802169f10b1a8385e030dea94fc0400483045022100ff57599227ab4182e50d811ff768763545b0154ed53efb8960b260d801f4d1540220775cb2465f28d93d79d2c8805e1eda02d833dcb3d4380962d3e800373bf7a912014830450221008458908b17a282a52f24c94cc98c2bac275ba255cc360376481460fd89c5638902205e9866a6827ff632081d581318c7c171c9ee4bab2d41654a90f18b77a05f42af014752210278064edd73a27741b933d40f9dc89c0ccaf8a168a71b1067f28c631d235877a92103310a1f9933ec4394c32a0a5e5619c3e07cdc705e634e1f614b30e42d3bb1ce4d52ae00000000"
}
```

Then after it is confirmed 
```
{
  "tx_hash": "3a1f080b82704a60a2959cd1be32f4a7e019c55897e1bf45d2de830e06601728",
  "amount": "99817",
  "num_confirmations": 2,
  "block_hash": "0000000057421fd317571504aa821b8ac317ae86db38637349523e1bc81951d6",
  "block_height": 1564910,
  "time_stamp": "1561414382",
  "total_fees": "0",
  "dest_addresses": [
    "tb1qzapgg7psfc5qy95lzzc6swz7qvx7498ujk4xhj"
  ],
  "raw_tx_hex": "02000000000101758d01614a0738e71e8d9af3d5be1b8d279acbe4cf87912ae0978c718581f3e20000000000ffffffff01e98501000000000016001417428478304e2802169f10b1a8385e030dea94fc0400483045022100ff57599227ab4182e50d811ff768763545b0154ed53efb8960b260d801f4d1540220775cb2465f28d93d79d2c8805e1eda02d833dcb3d4380962d3e800373bf7a912014830450221008458908b17a282a52f24c94cc98c2bac275ba255cc360376481460fd89c5638902205e9866a6827ff632081d581318c7c171c9ee4bab2d41654a90f18b77a05f42af014752210278064edd73a27741b933d40f9dc89c0ccaf8a168a71b1067f28c631d235877a92103310a1f9933ec4394c32a0a5e5619c3e07cdc705e634e1f614b30e42d3bb1ce4d52ae00000000"
}
```

After it is confirmed I also see it under `closedchannels`
```
{
            "channel_point": "e2f38185718c97e02a9187cfe4cb9a278d1bbed5f39a8d1ee738074a61018d75:0",
            "chan_id": "1719126012446638080",
            "chain_hash": "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943",
            "closing_tx_hash": "3a1f080b82704a60a2959cd1be32f4a7e019c55897e1bf45d2de830e06601728",
            "remote_pubkey": "0347dd556485e1adbcf46a8efaeac9ab5beb3efd0ba89eb7832c6e5a1391c68aec",
            "capacity": "100000",
            "close_height": 1564910,
            "settled_balance": "99817",
            "time_locked_balance": "0",
            "close_type": "COOPERATIVE_CLOSE"
        }
```

It seems like there should be a way in the database to connect a `waiting_close_channels` to the transaction that has 0 confirmations. Maybe what I am missing is the fact that this pending transaction _could_ change?

**Comment by wpaulino** [comment]
We only know of the closing transaction during cooperative closes and uncooperative closes done by us, otherwise we'll have to wait until we detect it on-chain when done by the remote party.

**Comment by stridentbean** [comment]
It sounds like the best we can do is say the transaction is a pending close channel, but we cannot correlate to which channel until it confirms once. I can live with that.

**Comment by halseth** [comment]
This is relevant to this issue: https://github.com/lightningnetwork/lnd/pull/3016

**Comment by Roasbeef** [comment]
Waiting close now shows all possible commitments, and the remaining information can be obtained with `PendingSweeps`.
