### ISSUE TITLE
Suggestion for improving wallet security

### ISSUE THREAD

**Issue by lcpo** [lightningnetwork/lnd#3239]
Hi, I have a suggestion for increasing security of the working node.
It would be great to set a password for transactions to other bitcoin addresses, something like a payment password using the following methods: SendMany, SendCoins, etc, also, the ability to enable and disable the request for this password through the configuration file.
Also, this password can be set when creating a wallet, and then can be changed.
What do you think?

**Comment by molxyz** [comment]
@lcpo  You already can set a password when you create a LND node.

**Comment by wpaulino** [comment]
Is the idea behind this request to have some sort of permission system where only users with the password can access specific RPCs? This can already be achieved with macaroons, which you can read about how they're used within `lnd` [here](https://github.com/lightningnetwork/lnd/blob/master/docs/macaroons.md).
