### ISSUE TITLE
Short command for invoice payment

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#324]
Per roasbeef's suggestion, I would like to ask for a change in the command to make invoice payment when using lnd with btcd on commandline.  So, instead of 
`lncli sendpayment --pay_req=yx9zqprrqp9f16s9ymcmikjkwxm7a9gbeqm373dehytc96yjd1bjn8ym18sw3mp5rg1rcfitqcj3u6up1acnw9195urj9j5uwjnnpezyyyyyyyyyyyycoxjj3ydy`

Could we make it shorter, something like: 
`lncli payinvoice yx9zqprrqp9f16s9ymcmikjkwxm7a9gbeqm373dehytc96yjd1bjn8ym18sw3mp5rg1rcfitqcj3u6up1acnw9195urj9j5uwjnnpezyyyyyyyyyyyycoxjj3ydy `  ?  

Thank you.

**Comment by rajeshnair2k** [comment]
I would like to take a stab at this. Is the intention here to create a new command with just payment request as the argument?

**Comment by halseth** [comment]
Yep, that's my understanding at least :)

**Comment by rajeshnair2k** [comment]
I have a pr(https://github.com/lightningnetwork/lnd/pull/359) open for this. Would appreciate feedback.
