### ISSUE TITLE
ForwardingHistory: intelligently handle vague requests

### ISSUE THREAD

**Issue by tyzbit** [lightningnetwork/lnd#3240]
### Background

If no parameters are given, the `ForwardingHistory` RPC queries the `ChannelDB` for the last 24 hours of forwarding events.  This behaviour may not be expected considering the name of the RPC; one might expect that a full history, or the most recent chunk of forwarding events be returned rather than a time slice of 24 hours.

I suggest the default behavior of `ForwardingHistory` be changed to look for the 100 most recent forwarding events.  Also, if a user provides only one of StartTime or EndTime, `ForwardingHistory` should assume a default StartTime of the seed birthday, or a default EndTime of `time.Now()`.  This might also help in cases such as #2585.

Alternatively (and more simply), we can default end_time to time.Now() so users can omit it in favor of just providing a start_time.

This is separate from #1233.

### Steps to reproduce

1. Record a specific forwarding event
2. Wait 24 hours
3. Run `$ lncli fwdinghistory`

### Expected behaviour

All forwarding events are shown, or the most recent X forwarding events are shown.

### Actual behaviour

The specific forwarding event is not shown.  It must be found by specifying StartTime and EndTime together.

**Comment by tyzbit** [comment]
If the idea sticks, I'd like to take this on.

**Comment by Roasbeef** [comment]
Fixed by #3246.
