### ISSUE TITLE
[Feature Request] Add sweep flag to estimateFee rpc

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#3242]
**Issue**
Currently, estimating sending all funds from a wallet using lnd's interface requires a lot of guessing and checking. 

**Feature**
Add a flag `sweep` or `send_all` to EstimateFeeRequest. EstimateFeeResponse should remain the same. Then, send coins call should succeed with the returned fee rate and send_all being true.

**Comment by wpaulino** [comment]
You can use the existing `SendCoins` RPC with a custom fee (fixed sat/vbyte or confirmation target) and the `SendAll` flag. Would that be adequate for your use or are you mainly interested in this being added to the `EstimateFee` RPC?

**Comment by stridentbean** [comment]
I understand how to use `SendCoins` with the `SendAll` flag. But, I want to be able to tell the user how much it will cost them before they send it. Mainly, I would like it to be added to `EstimateFee`.

**Comment by Roasbeef** [comment]
If you use the wallet's entire balance as the value for the address mapping, then it should work.

**Comment by stridentbean** [comment]
> If you use the wallet's entire balance as the value for the address mapping, then it should work.

I'm not sure if this is related to https://github.com/lightningnetwork/lnd/issues/3217, but using the entire wallet balance is not working. 

I'm on a testnet node running lncli version 0.7.0-beta commit=v0.7.0-beta-rc2

```
bash-4.4# lncli --macaroonpath /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon walletbalance
{
    "total_balance": "98851306",
    "confirmed_balance": "98851306",
    "unconfirmed_balance": "0"
}
```

Still fails. 
```
bash-4.4# lncli --macaroonpath /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon estimatefee '{"2N5Q9hSUiFVtQXz61SarbiQNoRWBS6gS3V6":98851306}'
[lncli] rpc error: code = Unknown desc = insufficient funds available to construct transaction
```

**Comment by Roasbeef** [comment]
It's possible to now do `lncli sendcoins --sweepall`.
