### ISSUE TITLE
[feature request] add rpc endpoint estimateChannelFee

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#3243]
**Issue**
There is no mechanism to estimate opening a channel. The estimateFee endpoint is close, but not exactly correct. 

**Feature**
Create another rpc endpoint called estimateChannelFee. EstimateChannelFeeRequest should contain target_conf and send_all. EstimateChannelFeeResponse should contain fee_sat and feerate_sat_per_byte.

**Comment by Roasbeef** [comment]
Why can't the current `EstimateFee` work for this? It can never be _100_ % correct, since it depends on the UTXO distribution and coin selection. If between your fee estimate call the user makes a transaction, then things may not match up fully.
