### ISSUE TITLE
Error lookup X.X.X.X: no such host

### ISSUE THREAD

**Issue by grangonzo** [lightningnetwork/lnd#3244]
### Background
Hello, trying to install LND on latest ubuntu following the installation guide here. 
but when i get to:

Once all of the above is complete, and you've confirmed bitcoind is fully updated with the latest blocks on testnet, run the command below to launch lnd with bitcoind as your backend (as with bitcoind, you can create an lnd.conf to save these options, more info on that is described further below): lnd --bitcoin.active --bitcoin.mainnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=REPLACEME --bitcoind.rpcpass=REPLACEME --externalip=X.X.X.X --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

**Comment by cfromknecht** [comment]
@grangonzo just to rule this out, does the error say "X.X.X.X" or your IP?

**Comment by grangonzo** [comment]
> @grangonzo just to rule this out, does the error say "X.X.X.X" or your IP?

Yes. i just typed exactly what the instructions say. It says --externalip=X.X.X.X in the guide, so that's what i entered. 
Ubuntu returns this: lookup X.X.X.X: no such host

**Comment by cfromknecht** [comment]
gotcha, the X.X.X.X is meant to be replaced with your external IP address. it isn't strictly critical to the setup if you want to omit it and set it up at a later time

**Comment by grangonzo** [comment]
> gotcha, the X.X.X.X is meant to be replaced with your external IP address. it isn't strictly critical to the setup if you want to omit it and set it up at a later time

Ok thanks. I'll google to learn how to find out my external IP address and change it.

Appreciate your help. 

Still need to figure out why i ended up with lnd at /go/src/github.com/lightningnetwork/lnd by following the guide step by step lol. I realize it's not a guide for normal people but i'll try to succeed!

**Comment by wpaulino** [comment]
> Still need to figure out why i ended up with lnd at /go/src/github.com/lightningnetwork/lnd by following the guide step by step lol.

Perhaps you forgot to set your `GOPATH`, which you can do with:

```
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
```

Closing per https://github.com/lightningnetwork/lnd/issues/3244#issuecomment-505604213.
