### ISSUE TITLE
lncli tower info crashes LND if watchtower not enabled

### ISSUE THREAD

**Issue by pardus79** [lightningnetwork/lnd#3261]
### Background

Watchtowers are not enabled. `lncli tower info` crashes LND.

### Your environment

* lnd version 0.7.0-beta commit=v0.7.0-beta
* Linux thundroid 4.14.35-128 #1 SMP PREEMPT Fri Apr 20 13:49:49 UTC 2018 armv7l armv7l armv7l GNU/Linux
* Bitcoin Core Daemon version v0.17.1

### Steps to reproduce

Start LND
Unlock wallet
`lncli getinfo` shows LND running as normal
`lncli tower info` gives error `[lncli] rpc error: code = Unavailable desc = transport is closing`

Log when this occurs:

> Jul 02 12:04:09 thundroid lnd[3225]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 02 12:04:09 thundroid lnd[3225]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x692f80]
Jul 02 12:04:09 thundroid systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 02 12:04:09 thundroid systemd[1]: lnd.service: Unit entered failed state.
Jul 02 12:04:09 thundroid systemd[1]: lnd.service: Failed with result 'exit-code'.

This was after setting-up, but then disabling, watchtowers. Disabled both by commenting-out watchtower settings in lnd.conf and by totally deleting them. Restoring watchtower settings made `lncli tower info` behave normally.

**Comment by lukeroberts** [comment]
Also seeing this on Windows 2019, but I did not set up watchtower config options at all in my conf yet

**Comment by cfromknecht** [comment]
was able to reproduce, fix is here #3262
