### ISSUE TITLE
Possible path finding performance degradation

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#3266]
There have been some reports of path finding being slower after the merge of probability based pathfinding #2802. This issue exists to log investigations that have been done on this potential issue.

**Comment by joostjager** [comment]
So far I haven't been able to see any performance degradation. Setup of the test that I ran:
- Modify `lncli` to pass through a `source` parameter for `queryroutes`
- Modify `lnd` to log extra path finding statistics.
- Build a list of testnet nodes: 
   `lncli --network=testnet describegraph | jq ".nodes[].pub_key" -r > testnet_nodes.txt`
- Run `v0.6.1-beta` on testnet and sync the graph.
- Run `cat testnet_nodes.txt | head -n50  | xargs -I % lncli --network=testnet queryroutes % 300000  --num_max_routes=1 --source=038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9`. This executes queryroutes requests to the first 50 nodes in the graph.
- Run `queryroutes --source=138863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a64001 --num_max_routes=1 --amt=500000 038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9`. The source pubkey does not exist. This will trigger an exploration of the full graph in order to find a path that doesn't exist. This is the worst case path finding performance.
- Upgrade to `v0.7-beta`
- Run the same tests again

Results:
[pathfindingperf.txt](https://github.com/lightningnetwork/lnd/files/3355007/pathfindingperf.txt)

There seem to be no significant difference between the releases.

**Comment by Crypt-iQ** [comment]
I usually get longer `findPath` calls than this.  Two notes:

- Doesn't queryroutes not include probability based path finding (#3221) ?
- I noticed when I did this for my path finding efficiency branch, it helped to ignore the disabled edge check here.  A lot of the path finding attempts in your log have edges = nodes explored = 1 which probably means a path isn't being found and thus the very small time measurement.
https://github.com/lightningnetwork/lnd/blob/a6e77811b1578f5d48191d0b9a5d4cbf895626f5/routing/pathfind.go#L386-L388

**Comment by joostjager** [comment]
QueryRoutes indeed does not use mission control yet, but probabilities are taken into account (although it is just the default probability of 1). There could have been a regression in those changes.

One thing that is different when using `SendPayment` is that the default probability is 0.95. I changed that manually, but it didn't make a difference.

I'll park this issue until more specific information comes up.

**Comment by Crypt-iQ** [comment]
I do see *slightly* higher time for 0.7, but it's probably not enough to warrant anybody sending you a report - perhaps it's an edge case.  Ignoring the disabled check + choosing a different, less connected source `038d142dd1fe429daa2ca975f651a6559fb90ddc254d242f7f1fd33c1264958fc4`, and finding paths to the first 300 nodes yields the below graph (purple = 0.7)

<img width="905" alt="Screen Shot 2019-07-03 at 9 42 25 PM" src="https://user-images.githubusercontent.com/15145615/60634065-7eaa4f00-9ddb-11e9-87fe-a2ba5056370e.png">

**Comment by sako0938** [comment]
Recently did a $20 payment to a node I dont have a channel with on my 0.8.0beta-rc2 node running with neutrino on Odroid XU4.:
It took:
real	3m11.608s
user	0m0.242s
sys	0m0.072s

I don't know if the timeout got increased, but I'm happy I dont have to retry payments over and over, and I can just wait for it. 
1.5 sat payments fees and 3 minute confirmation still >> the blockchain.
