### ISSUE TITLE
best_header_timestamp is from year 2042

### ISSUE THREAD

**Issue by ottosuess** [lightningnetwork/lnd#3270]
### Background

when I setup a new testnet neutrino lnd and run `lncli --network testnet getinfo` i get something like this:

```
{
	"version": "0.7.0-beta commit=v0.7.0-beta-rc2",
	"identity_pubkey": "038df0ade1bbfb1f082818cc6e387b2634e1717d38d51d829ca8f85b6ec99e3ba1",
	"alias": "038df0ade1bbfb1f0828",
	"color": "#3399ff",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_inactive_channels": 0,
	"num_peers": 0,
	"block_height": 95000,
	"block_hash": "00000000004f8dd4fa96de576defb7a6a53333994cccde06a6bc4750a5747e49",
	"best_header_timestamp": 2288912640,
	"synced_to_chain": false,
	"testnet": true,
	"chains": [
		{
			"chain": "bitcoin",
			"network": "testnet"
		}
	],
	"uris": null
}
```

`best_header_timestamp` is 2288912640 which according to unixtimestamp.com is 07/14/2042 @ 1:04am (UTC).

once `synced_to_chain` is `true`, `best_header_timestamp` changes to a more reasonable value (1562254258, which is now)

### Your environment

* version of `lnd`: **lnd version 0.7.0-beta commit=v0.7.0-beta-rc2**
* which operating system (`uname -a` on *Nix): **Darwin Kernel Version 18.5.0 (mac os)**
* version of `btcd`, `bitcoind`, or other backend: **neutrino**
* any other relevant environment details

### Expected behaviour

`best_header_timestamp` should not be in the future.

### Actual behaviour

`best_header_timestamp` is in the year 2042.

**Comment by valentinewallace** [comment]
This affects the lightning app initial network loading spinner as well: https://github.com/lightninglabs/lightning-app/issues/1243

**Comment by mandelmonkey** [comment]
@ottosuess did you find a work around for this in the mean time?

**Comment by wpaulino** [comment]
@mandelmonkey I've put up https://github.com/btcsuite/btcwallet/pull/703 to address this.

**Comment by mandelmonkey** [comment]
@wpaulino thanks for the update

**Comment by mandelmonkey** [comment]
Seems that the best header timestamp is always 1231006505 now?

```
block_height":550000

{"version":"0.11.0-beta commit=v0.11.0-beta-59-ge4764a67cc415627e9196265f5c5bfe8ea5d388a-dirty","commit_hash":"e4764a67cc415627e9196265f5c5bfe8ea5d388a","identity_pubkey":"03d240740d9e876dfcc998f1b3f173310d481a667e366e7fb1c9b15fcd426debe6","alias":"03d240740d9e876dfcc9","color":"#3399ff","num_pending_channels":0,"num_active_channels":0,"num_inactive_channels":0,"num_peers":0,"block_height":550000,"block_hash":"000000000000000000223b7a2298fb1c6c75fb0efc28a4c56853ff4112ec6bc9","best_header_timestamp":"1231006505

"block_height":602000

{"version":"0.11.0-beta commit=v0.11.0-beta-59-ge4764a67cc415627e9196265f5c5bfe8ea5d388a-dirty","commit_hash":"e4764a67cc415627e9196265f5c5bfe8ea5d388a","identity_pubkey":"03d240740d9e876dfcc998f1b3f173310d481a667e366e7fb1c9b15fcd426debe6","alias":"03d240740d9e876dfcc9","color":"#3399ff","num_pending_channels":0,"num_active_channels":0,"num_inactive_channels":0,"num_peers":0,"block_height":602000,"block_hash":"0000000000000000000bcf39e01dcc3fa4f6b9aceb7e6d7e945113338b48ca53","best_header_timestamp":"1231006505```

**Comment by wpaulino** [comment]
That's the genesis block timestamp. `block_height` corresponds to the best height known to the backend, while `best_header_timestamp` corresponds to the best header known to the wallet. The wallet is not synced until the backend is synced, which is why you see the same timestamp while the height is increasing.

**Comment by mandelmonkey** [comment]
I thought one would expect to see the best_header_timestamp increase as the block height increased? This would allow you to calculate the sync progress

**Comment by mandelmonkey** [comment]
@wpaulino any thoughts on this? at the moment im not sure how to show the sync progress in the app if I dont know what the current timestamp of the current synced header/block is

**Comment by wpaulino** [comment]
Sorry I missed this @mandelmonkey, you are correct in that it's not possible to determine the sync progress without the timestamp. Could you open a separate issue to track this?

**Comment by mandelmonkey** [comment]
> Sorry I missed this @mandelmonkey, you are correct in that it's not possible to determine the sync progress without the timestamp. Could you open a separate issue to track this?

done thanks
