### ISSUE TITLE
[ERR] SRVR: unable to force close: unable to find key for addr

### ISSUE THREAD

**Issue by justinmoon** [lightningnetwork/lnd#3277]
### Background

I'm trying to sweep funds from a node that has lied dormant for a few months.

Everything was working but then I ran `lncli closeallchannels`. This problem appeared afterwards.

### Your environment

* version of `lnd`

> lnd version 0.5.2-beta commit=v0.5.2-beta

* which operating system (`uname -a` on *Nix)

> Linux odroid 4.14.55-133 #1 SMP PREEMPT Sat Jul 14 18:18:06 UTC 2018 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

> Bitcoin Core Daemon version v0.17.1

* any other relevant environment details

### Steps to reproduce

-  `lncli unlock`
-  Running any `lncli` command gives error:

```
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, 
latest connection error: connection error: desc = "transport: Error while dialing 
dial tcp 127.0.0.1:10009: connect: connection refused"
```

3. Node crashes. [Here are the logs](https://gist.github.com/justinmoon/e8253b80c623fe8c625c4f524b31c58a).

### Expected behaviour

`lncli` commands wouldn't crash node

### Actual behaviour

`lncli` commands crash node

**Comment by Roasbeef** [comment]
Did you modify the on-disk state of the node at all? Also can you think of any instance of unclean shutdowns?

**Comment by Roasbeef** [comment]
Fixed by #3280.

**Comment by justinmoon** [comment]
Thanks @Roasbeef.

I made a backup of my lnddir, installed lnd master branch at `616750184ef9316b849f1ec092176e6814cb2661` and ran it. I got a different error: [here are the logs](https://gist.github.com/justinmoon/3d2a8eccd8b458d478937e33d47062ef).

Let me know if you'd like a new issue. Leaving it here in case context helps debugging.

**Comment by halseth** [comment]
@justinmoon Please open a new issue :)
