### ISSUE TITLE
routing+channeldb: implement batched channel announcement+update writing

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3288]
As implemented today, [only a single channel can be written (synchronization wise) within the daemon at any given time](https://github.com/lightningnetwork/lnd/blob/master/channeldb/graph.go#L498). As a result, one of the current bottle necks to spinning up a new `lnd` node is actually just _ingesting_ the graph. Due to the recently added edge/node caching within `channeldb`, using [the `Batch` call from `bbolt`](https://godoc.org/github.com/etcd-io/bbolt#DB.Batch) won't result in any increased concurrency due to the required mutex synchronization. Instead, we can _coalesce_ several channels at the router level, which are then periodically written to disk in a _single_ database transaction. This change should _significantly_ reduce the amount of time it takes to ingest the graph given that atm, we need a _new_ database transaction for each channel, which can take some time (in the realm of computers). 

# Steps To Completion 

- [ ] Add a new `AddBatchedChannelEdge` (or diff name) method that's able to take a _variadic_ `*channeldb.ChannelEdgeInfo` to be written in a single database transaction. Alternatively, we can simply extend the prior version (`AddChannelEdge`) with a variadic parameters which will allow us to keep all existing callers in place. 

- [ ] A similar method should be created the permits the caller to write several `*channeldb.ChannelEdgeInfo` instances in a single database transaction. 

- [ ] Rather than write channels [one at a time](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L1226), the router should return immediately to the caller, but _cache_ that channel in memory until the next batch flush criteria is met. This can either be time based, or based on a maximum/minimum batch size. 

- [ ] Add a new coalescer component to the router that will "periodically" write the latest batch of channels to disk. 

- [ ] Determine how to maintain external consistency w.r.t channels in the next scheduled batch that haven't yet been written to disk.

**Comment by cfromknecht** [comment]
tackling this
