### ISSUE TITLE
Misspelling found on LN Community Blog 

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#329]
"bitcoin.rpcpass" is misspelled in one place, screenshot to show here: https://i.imgur.com/Iqc1d07.png .
This error is found on this blog (the line before "Docker Build"):
http://lightning.community/lnd/faucet/2017/01/19/lightning-network-faucet/

Thank you.

**Comment by Roasbeef** [comment]
I believe this was fixed, thanks for reporting!
