### ISSUE TITLE
describegraph missing addresses for nodes on simnet

### ISSUE THREAD

**Issue by ajcrowe** [lightningnetwork/lnd#3304]
### Background

When running an integration suite utilising `simnet` expected output for `describegraph` is missing the node `addresses`

example: 

```
lncli --network=simnet describegraph
{
    "nodes": [
        {
            "last_update": 1562858165,
            "pub_key": "0237e082e486ed1b59ac4c02253f1ec942a247ff7c577a2de636aff57e2e60a32d",
            "alias": "0237e082e486ed1b59ac",
            "addresses": [
            ],
            "color": "#3399ff"
        },
...
```

### Your environment

* `v0.6.1-beta` and `v0.7.0-beta`
* `alpine` based Docker image
* `btcd` `master` `c26ffa87`

### Steps to reproduce

* Using modified version of https://github.com/lightningnetwork/lnd/tree/master/docker
* Run the containers (`btcd`, `lnd`)
* Establish peering and open channels between nodes
* Execute `lncli --network=simnet describegraph`

### Expected behaviour

items in `nodes` should contain a populated `addresses` array

### Actual behaviour

items in `nodes` are missing values from `addresses` array

**Comment by wpaulino** [comment]
Nodes need to set the `--externalip` flag in order to advertise their reachable addresses to the network. Check out `lnd -h`.
