### ISSUE TITLE
Error: Too many private routes

### ISSUE THREAD

**Issue by ottosuess** [lightningnetwork/lnd#3305]
lnd seems to check that invoices have less than 20 route hints, but creates invoices with more than 20 route hints itself.
i believe this happened when creating an invoice on a recent lnd build with 250+ private channels.

for more information you can take a look at this issue:
https://github.com/LN-Zap/zap-iOS/issues/182

sorry about the little amount of information. 🙏

**Comment by wpaulino** [comment]
`lnd` _shouldn't_ create invoices with more than 20 route hints.
https://github.com/lightningnetwork/lnd/blob/aa1cd04dbf07a9195d5ada752f383988d8d01fa7/lnrpc/invoicesrpc/addinvoice.go#L271

**Comment by ottosuess** [comment]
just woke up so I might be wrong:
shouldn't this break `if numHints >= 20` otherwise it will add 21 hints 🤔

right now the check passes when it's 20 and adds another hint.

**Comment by wpaulino** [comment]
You're right, nice catch.
