### ISSUE TITLE
signal SIGSEGV: segmentation violation when specifying tor.active=1

### ISSUE THREAD

**Issue by ts95** [lightningnetwork/lnd#3308]
### Background

I've configured `lnd.conf` like so:
```
[application options]
debuglevel=debug
maxpendingchannels=10

[bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=neutrino

[neutrino]
neutrino.connect=mainnet1-btcd.zaphq.io

[tor]
tor.active=1
tor.dns=nodes.lightning.directory

[routing]
routing.assumechanvalid=1
```

For some reason, when I run lnd the following happens:
```
→ lnd --bitcoin.active --bitcoin.mainnet
2019-07-13 17:03:43.440 [INF] LTND: Version: 0.7.0-beta commit=v0.7.0-beta-4-ga6e77811b1578f5d48191d0b9a5d4cbf895626f5-dirty, build=production, logging=default
2019-07-13 17:03:43.440 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-07-13 17:03:43.447 [INF] CHDB: Checking for schema update: latest_version=9, db_version=9
2019-07-13 17:03:43.461 [INF] LTND: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x105da38]

goroutine 1 [running]:
github.com/lightningnetwork/lnd.Main(0x2083e40, 0xc0004f6db0)
	/Users/tonisucic/go/src/github.com/lightningnetwork/lnd/lnd.go:208 +0x2bfa
main.main()
	/Users/tonisucic/go/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:14 +0x26
```

For the record everything works perfectly when I omit `tor.active`.

### My environment

* lnd 0.7.0-beta
* macOS 10.14.5 Mojave (Darwin 29mbp.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64)
* node backend: neutrino

### Steps to reproduce

Assuming a wallet has already been created:
1. Set `tor.active=1` in `lnd.conf` or specify the `--tor.active` flag when running `lnd`.
2. Run lnd with neutrino as the node backend: `lnd --bitcoin.active  --bitcoin.mainnet --tor.active --debuglevel=debug --bitcoin.node=neutrino --neutrino.connect=mainnet1-btcd.zaphq.io`

### Expected behaviour

The daemon works as intended with tor being activated.

### Actual behaviour

When tor is activated, a runtime error occurs causing the daemon to shut down immediately.

**Comment by Roasbeef** [comment]
Do you have the `tor` daemon running locally? Also your line numbers don't match up, which changes do you have staged locally? (see the `dirty`) tag in lnd's version.

**Comment by ts95** [comment]
For whatever reason I thought the tor daemon would be bundled with lnd but in retrospect I realize that that doesn't make much sense. Now that I'm running the tor daemon locally it works as expected.

Perhaps it would be a good idea to display an error message that informs that user that the tor daemon isn't running / isn't reachable.
