### ISSUE TITLE
[Autopilot] feature request: boost priority for peers which provide inbound capacity

### ISSUE THREAD

**Issue by lsching17** [lightningnetwork/lnd#3310]
I am testing lnd tor node for months, and i never have inbound capacity. I can spend money, but cannot receive.

There are possible ugly workarounds
1. buy capacity  -  defeat the purpose of cheap fee
2. advertise for capacity - defeat the purpose of anonymous tor node

Can lnd improves the liquidity of lightning network by tuning autopilot algorithm? something like this:

`if a peer provides inbound capacity, boost its priority for channel creation. 
This behaviour is on by default and can be turned off by user.`

The idea is: You provide liquidity, and the network rewards you with liquidity

This should be an incentive for merchant to buy/hold btc and offer liquidity

**Comment by lsching17** [comment]
I think this offers incentive to merchant to buy/hold btc and offer liquidity to the network

**Comment by th3geek** [comment]
I have no comment on the request, but if you need inbound liquidity just use an exchange like zigzag or loop out to send your current lightning funds on-chain.

**Comment by lsching17** [comment]
> 
> 
> I have no comment on the request, but if you need inbound liquidity just use an exchange like zigzag or loop out to send your current lightning funds on-chain.

Imagine i am a crypto newbie and would like to setup a lightning shop with 1 btc

1. Why do my customers fail to pay by lightning? i already deposit 1 btc in the node.

    After hour and hours of googling, i finally realize i need to buy incoming capacity

2. zigzag limits per deposit to around 0.04 btc, so i need to pay 25 times to zigzag
3. zigzag is not free lunch. Who will pay the bill? My dear customers.
 
It is very hard to image mass adoption if lnd is not "plug and play", "user-friendly" is very important,.

**Comment by Roasbeef** [comment]
> I am testing lnd tor node for months, and i never have inbound capacity. I can spend money, but cannot receive.

You can use a [Loop Out](https://blog.lightning.engineering/posts/2019/03/20/loop.html) to receive inbound capacity. 

The rest of the issues you bring forth are IMO, on boarding issues, and we're working on additional solutions to package tools such as `loop` in a more user friendly manner.
