### ISSUE TITLE
[Feature request] Configurable subsystem that goes to chain if off-chain balance differs from on-chain balance significantly against our favor

### ISSUE THREAD

**Issue by tyzbit** [lightningnetwork/lnd#3312]
### Background

As it stands today, if a user has a channel with a high incentive for the other party to cheat, LND does not take any action, and I'm not aware of any way to find channels like these through existing RPCs (though my knowledge of existing RPCs is limited).

`example: A(0BTC)<->B(1BTC) on channel opening but now channel balance is A(1BTC)<->B(0BTC).  B has a 1BTC incentive to try to cheat`

I think it would provide additional deterrent against attempted breaches if LND optionally tracked channels divergence from on-chain and updated the balances on-chain* when, for example, a large percentage of remote funds (lets say 70%) gets sent over the channel to us after channel open.  This could be configured to happen only for channels only when our funds are a certain multiple of the channel's commit_fee (lets say 20x).  This prevents us needlessly going on-chain for a small amount of satoshis.  Furthermore, we could configure these actions only to take place after a certain amount of time, to allow for the channel to rebalance itself via a manual rebalance or routing/sending a payment of sufficient size.

\* I'm not sure what this would look like, worst case it would be a channel close and then re-open but I think considering splicing this could be done as a splice where the on-chain funds simply go to our own wallet and the channel size stays the same.

**Comment by wpaulino** [comment]
As for the general idea of detecting such cases, perhaps this seems better to delegate to an application built on top of `lnd`? This can already be achieved by checking balances and whether you're the initiator of the channel with the `ListChannels` RPC.

**Comment by cfromknecht** [comment]
@tyzbit once there exists a previous state where most of the funds have been sent over, the incentive to cheat would remain until the channel closes. Splicing does solve this to some extent, since it basically allows you make previously valid states unusable after the splice is confirmed. The only way to prevent entering such an undesirable state atm is to set high enough reserve values that you would be comfortable with, but that also has the side effect of limiting the usability of the channel.

It seems in practice that this would amount to you setting a soft-reserve higher than your actual, which will cause the channel to be force closed if the remote party oversteps. At that point though why not tell the remote party what you're actually comfortable with up front, to prevent them from accidentally getting the channel closed?

**Comment by tyzbit** [comment]
@wpaulino I would say that would be fine if we all agree that this functionality would not improve `lnd`'s safety.  Adding something like channel rebalancing directly into `lnd` could be seen as an optional feature that doesn't increase or decrease the safety of the application so there's no reason why it *needs* to be directly built into the application.  Tracking risk according to divergence from the base chain *does* increase safety in my view, so unless it's not a project goal for `lnd` to have the highest safety it can, I think it makes sense to either add it directly to the application or make the decision that this feature would either not add sufficient value or it would introduce unnecessary complexity.

@cfromknecht I hope the base functionality would either close (which can try cooperative first) the channel and reopen it with the same funds, or go to chain with the current distribution of funds and keep the channel open (if that action is possible according to RFC).  I agree, this would limit the usability of channels, but usability is sacrificed for safety, which is a tradeoff some users may make.

I think this feature would be best implemented where the conditions for going to chain are known only to the local node operator so the remote node operator isn't informed as to what we consider to be acceptable risk and has to assume we are as conservative as possible.

**Comment by Roasbeef** [comment]
Can be done externally using the existing RPC calls.
