### ISSUE TITLE
Channels recovery from a corrupted channel.db

### ISSUE THREAD

**Issue by Feyynt** [lightningnetwork/lnd#3319]
### Background

Hi everyone!

Basing on the answers on my past issue #2826 I think I have the channel.db file corrupted, and this make my LND shutdown after decryption and after autonomously starting Channel Arbitrator.

I tried to run the bbolt check /path/to/channel.db command and the result is:
104085 errors found
invalid value

Some of them are "multiple references" and the others are "unreachable unfreed".

What does this mean? What can I do to restore my channels information?
If other nodes close channels with me the funds are recoverable with my seed?

Thanks 

### Your environment

version of lnd: 0.5.2-99-beta
which operating system: Windows
version of btcd: 0.12.0-beta

**Comment by wpaulino** [comment]
You'll need to follow our [recovery guide](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md). It seems like you don't have a `channel.backup` file due to running `v0.5.2`, so you won't be able to recover funds within channels.

**Comment by Feyynt** [comment]
Why you didn't use addresses derived from the seed in the commitment transactions outputs?

Anyway, it was probably a file system issue, so I think only few bytes has been corrupted. For the rest I need to exctract information from my channel.db file.

What does "multiple references" mean? And what does "unreachable unfreed" mean?

**Comment by halseth** [comment]
> Why you didn't use addresses derived from the seed in the commitment transactions outputs?

This is how the LN spec currently is. It will be changed in the future.

You can recover on-chain funds from you seed.
