### ISSUE TITLE
Channel stuck pending after forced close by counter party

### ISSUE THREAD

**Issue by blacktemplar** [lightningnetwork/lnd#3320]
### Background

Two months ago the counter party of one of my channels force closed it since I was offline at this time due to hardware problems. After recovering my LND node (with a backup) everything works fine except this force closed channel which is still stuck in pending channels. The closing transaction has already over 10000 confirmations. Its not a big amount (in the cents) for me but I am still curios if this is a bug and what one can do in this case to access the onchain tx output which is not seen by my lnd node (is not added to the onchain walletbalance).

This is the output of `lncli pendingchannels`:
```
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "xxxxxxxxxxxxxxxxxxxxxx",
                "channel_point": "xxxxxxxxxxxxxxxxxxxxxx:1",
                "capacity": "20000",
                "local_balance": "1843",
                "remote_balance": "0"
            },
            "closing_txid": "xxxxxxxxxxxxxxxxxxxxxx",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ],
    "waiting_close_channels": [
    ]
}
```

and this is the output of `lncli getinfo` which shows the current block height and therefore the closing transaction should have been processed:

```
{
        "version": "0.7.0-beta commit=v0.7.0-beta-rc1",
        "identity_pubkey": "xxxxxxxxxxxxxxxxxxxxxx",
        "alias": "xxxxxxxxxxxx",
        "color": "xxxxxxx",
        "num_pending_channels": 0,
        "num_active_channels": 3,
        "num_inactive_channels": 4,
        "num_peers": 4,
        "block_height": 585808,
        "block_hash": "00000000000000000015887786402897996894289952ac8b9857a29c7a27a58f",
        "best_header_timestamp": 1563362508,
        "synced_to_chain": true,
        "testnet": false,
        "chains": [
                {
                        "chain": "bitcoin",
                        "network": "mainnet"
                }
        ],
        "uris": [
                "xxxxxxxxxxxxxxxxxxxxxx@xx.xxx.xxx.xxx:xxxx"
        ]
}
```

### Your environment

* version of `lnd`: 0.7.0-beta commit=v0.7.0-beta-rc1
* which operating system (`uname -a` on *Nix): Fedora 29
* version of `btcd`, `bitcoind`, or other backend: bitcoind v0.18.0

### Steps to reproduce

Not sure, channel was force closed by counter party during lnd node being offline.

### Expected behaviour

The local_balance should get added to my walletbalance and the channel should appear in closedchannels and not pendingchannels

### Actual behaviour

The channel is listed in pendingchannels, the local_balance is not added to the walletbalance.

Similar issues but not quite the same: #3029 #2948

**Comment by blacktemplar** [comment]
Maybe this is a duplicate of #3132 so the problem could be that the local_balance (1843 Satoshi) is too small to be swept.

As a follow up question: Why do we have to sweep it and cannot just add the funds to the walletbalance and as soon as there is a suitable outgoing on chain transaction propose to use the funds as every "normal" wallet does it (collect multiple tx outputs and use if needed multiple outputs to create new outgoing transaction).

**Comment by wpaulino** [comment]
Sweeping these outputs currently uses a fee estimate of 6 blocks, so that would have to provide a low enough fee rate. Assuming that it has at some point since the channel was force closed, there might be something else. Could you provide CNCT logs for the channel?

> Why do we have to sweep it and cannot just add the funds to the walletbalance 

The outputs don't pay out directly to an address the wallet controls, so we have to sweep it. This will change as part of the 1.1 Lightning spec.

**Comment by Roasbeef** [comment]
>                 "local_balance": "1843",

The balance is too small.

**Comment by blacktemplar** [comment]
Searching through the recent logs I could find the following interesting mentions of the channel:

```
2019-07-17 07:53:08.736 [ERR] NTFN: Rescan to determine the conf details of txid={closing_tx_id} within range 574xxx-585784 failed: chain notifier shutting down
2019-07-17 07:53:08.736 [ERR] CNCT: ChannelArbitrator({channel_point}): unable to progress resolver: quitting
2019-07-17 07:54:33.697 [INF] CNCT: Creating ChannelArbitrators for 1 closing channels
2019-07-17 07:54:33.857 [INF] CNCT: ChannelArbitrator({channel_point}): starting state=StateWaitingFullResolution
2019-07-17 07:54:33.861 [INF] CNCT: ChannelArbitrator({channel_point}): still awaiting contract resolution
2019-07-17 07:54:33.862 [INF] CNCT: ChannelArbitrator({channel_point}): relaunching 1 contract resolvers
2019-07-17 07:54:33.863 [INF] NTFN: New confirmation subscription: txid={closing_tx_id}, num_confs=1
2019-07-17 07:54:33.863 [INF] NTFN: New confirmation subscription: conf_id=1, txid={closing_tx_id}, height_hint=574xxx
2019-07-17 08:07:37.683 [INF] UTXN: NurseryReport: building nursery report for channel {channel_point}
2019-07-17 08:15:11.790 [INF] NTFN: Dispatching 1 confirmation notification for txid={closing_tx_id}                                                            
2019-07-17 08:15:11.791 [INF] CNCT: *contractcourt.commitSweepResolver({channel_point}): sweeping commit output
2019-07-17 08:15:11.794 [INF] SWPR: Sweep request received: out_point={closing_tx_id}:0, witness_type=CommitmentNoDelay, time_lock=0, amount=0.00001843 BTC, fee_preference=6 blocks
2019-07-17 08:15:11.796 [INF] NTFN: New spend subscription: spend_id=8, outpoint={closing_tx_id}:0, height_hint=585721                                          
2019-07-17 08:15:11.829 [INF] SWPR: Sweep candidates at height=585784 with fee_rate=9489 sat/kw, yield 0 distinct txns
2019-07-17 11:44:53.834 [INF] UTXN: NurseryReport: building nursery report for channel {channel_point}
```

(I filtered the logs shown above to only contain interesting lines from the log corresponding to the channel in question. Furthermore I replaced the channel_point, the closing tx id, and the last digits of the closing tx block 574xxx to preserve my anonymity.)

So it seems that he tries to sweep the channel but the fees are to high (at the moment). I will post more logs when the fees are low again.

@Roasbeef how is it explained then that I had the same situation with another channel which got force closed by the counter party and where my local balance was even smaller (around 1000 sat) but that one got swept with no problems?

**Comment by wpaulino** [comment]
> how is it explained then that I had the same situation with another channel which got force closed by the counter party and where my local balance was even smaller (around 1000 sat) but that one got swept with no problems in January?

From your report it seems like the channels were just closed two months ago, so the output couldn't have been swept in January?

Logs look fine to me, just seems like a matter of waiting for fees to be low enough. Will close for now as I don't think there's an issue here, feel free to re-open/comment if things aren't resolved after a while.
