### ISSUE TITLE
Usability: log that backend (bitcoind) is not available before exiting

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#3323]
I started lnd and unlocked my wallet while bitcoind was off. This caused lnd to exit. It took me a while to figure out that bitcoind was the issue. The log files of lnd did not point me to the issue.

> 2019-07-17 20:08:15.611 [INF] LTND: Version: 0.7.0-beta commit=v0.7.0-beta, build=production, logging=default
> 2019-07-17 20:08:15.611 [INF] LTND: Active chain: Bitcoin (network=mainnet)
> 2019-07-17 20:08:15.643 [INF] CHDB: Checking for schema update: latest_version=9, db_version=9
> 2019-07-17 20:08:15.655 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8081
> 2019-07-17 20:08:15.655 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
> 2019-07-17 20:08:15.656 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
> 2019-07-17 20:08:22.397 [INF] LNWL: Opened wallet
> 2019-07-17 20:08:22.583 [INF] LTND: Primary chain is set to: bitcoin
> 2019-07-17 20:08:22.597 [INF] LTND: Shutdown complete

**Comment by wpaulino** [comment]
This is the current output of reproducing your scenario:

```
2019-07-17 12:53:08.091 [INF] LNWL: Opened wallet
2019-07-17 12:53:08.200 [INF] LTND: Primary chain is set to: bitcoin
unable to create chain control: unable to subscribe for zmq block events: dial tcp 0.0.0.0:28332: connect: connection refused
2019-07-17 12:53:08.217 [INF] LTND: Shutdown complete
unable to subscribe for zmq block events: dial tcp 0.0.0.0:28332: connect: connection refused
```

The errors don't seem to be logged, but are rather sent to `stdout`/`stderr`.

**Comment by C-Otto** [comment]
Yes, those messages would help. I don't see those with `lncli unlock`, and my server's output is hidden due to systemd magic.
