### ISSUE TITLE
[Feature Request] "--nograph" mode

### ISSUE THREAD

**Issue by willcl-ark** [lightningnetwork/lnd#3324]
I think it might be useful for some use-cases to have a mode where the node does not attempt to connect to any peers, does not make unspecified outbound connections and does not gossip or download the network graph off any connected peers.

The use-case would be for creating manual, ad-hoc networks which might not want or need to interlink to the main network, it would also enable low-bandwidth nodes to only connect to selected individual nodes via single channels, and not have them automatically download unnecessary graph updates.

I also believe such a mode might complement new routing features in the pipeline ("Trampoline Payments" IIRC) where routing can be sub-contracted out to other nodes or done in a "meet-in-the-middle" fashion.

Thoughts?

edited only to include "Trampoline Payments" as routing technology name

**Comment by shivankgarg98** [comment]
I'm a beginner and I wish to take this issue. Can you help me regarding how to start?

**Comment by halseth** [comment]
I don't think this is a beginner issue really, not having graph data available would need some work.

**Comment by Overtorment** [comment]
FYI, I tried running lnd with ` --numgraphsyncpeers=0 ` and it didn't help, lnd was still syncing graph

**Comment by wpaulino** [comment]
The flag name is somewhat vague, but as the description notes, the setting is only for new graph updates. The initial graph sync upon peer connections is still done regardless of this flag.

**Comment by cfromknecht** [comment]
Closed by #4945

**Comment by cfromknecht** [comment]
@Overtorment setting `--numgraphsyncpeers=0` in 0.12.1 will disable all syncing
