### ISSUE TITLE
Feature Request: Support a "routeless" payment

### ISSUE THREAD

**Issue by riperk** [lightningnetwork/lnd#3327]
When a business/exchange/service/custodian uses lightning, they will generally run into the situation where one user generates an invoice, and another user tries to pay that invoice. Currently this will fail with lnd giving an error `unable to find a path to destination`. 

Now while it's certainly not unsolvable (e.g. business could use a cluster of lnd nodes, and then never make a payment to an invoice made by the same node; or perhaps a bit more annoying and develop a special hidden internal transfer and mask it as a lightning payment), it seems like an annoying problem that will need to be resolved by every business.

For this reason, I think it would make sense to support (an optional?) ability to make a routeless payment in which the payment just immediately succeeds, and involves no going over the network at all.

**Comment by Roasbeef** [comment]
> For this reason, I think it would make sense to support (an optional?) ability to make a routeless payment in which the payment just immediately succeeds,

If this is the behavior what would it achieve? If someone is making a custodial solution on top of `lnd`, there's a _number_ of things they'd need to implement along the way in order to make it secure, such as segmented accounts. `lnd` can't, and won't grow to do all of this, somethings are just better done outside the codebase. 

>  it seems like an annoying problem that will need to be resolved by every business.

Businesses that solve this problem will ideally open source it, such as the BlueWallet hub.

**Comment by riperk** [comment]
> If this is the behavior what would it achieve?

Ideally the wallet would show that you made a payment for X, and received a payment for X. So there would be no effect (other than some items in the history), just that it creates a unified API for paying/receiving from self. Now any service/business using lnd doesn't need to distinguish between self-created invoices and not.

> lnd can't, and won't grow to do all of this, somethings are just better done outside the codebase

Absolutely. Like an account system as you mentioned I think is a great example of something that should not be done in lnd. I am not familiar with the lnd codebase, or deeply familiar with lightning -- however this seems like a case that would be better solved by lnd than externally.

To draw a rough parallel, when you are implementing an (onchain) bitcoin deposit/withdraw system, there's in general absolutely no to distinguish or care if the sending address is one you own or not. I think it'd be nice if the same behaviour applied to lnd.

**Comment by Roasbeef** [comment]
Closing this for now since we have no immediate plans to do something like this, since it can be better served outside of `lnd`. Also there're a number of existing projects which are starting to implement this functionality.
