### ISSUE TITLE
unable to route. Disabled?

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#3328]
Using 0.6.1-beta commit=v0.6.1-beta

I have a simnet setup with about 10 nodes and 20 channels. 

A has a channel to B which has a channel to C

The channel between B and C shows this:

{
    "channel_id": "1858174651006977",
    "chan_point": "a04db9a8b2c294fe933e5ce203b9c36790ad87256f3ab3055ed334440dd0d405:1",
    "last_update": 1563446448,
    "node1_pub": "027dbb21be00a4cace0ce73761449f4d329cd400c08d556e2df4c65cf530c4e689",
    "node2_pub": "03d2d4cb2e72e1aef1ace7e98f8c6c04e3c5195fbacc6e986db71228ae8d48c89d",
    "capacity": "225000000000",
    "node1_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "1",
        "fee_rate_milli_msat": "10",
        "disabled": true,
        "max_htlc_msat": "222750000000000"
    },
    "node2_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "222750000000000"
    }
}

Questions:

1. does "disabled": true prevents routing from A to C?
2. What can be a reason for such disabled:true and how can I reset it?

**Comment by wpaulino** [comment]
> does "disabled": true prevents routing from A to C?

Yes, it is taken into account during path finding.

> What can be a reason for such disabled:true and how can I reset it?

There's a mechanism in `lnd` that auto disables channels for peers that have been disconnected for more than 20 mins. If peers reconnect, it will take 19 mins until a new graph update is sent enabling the channel. These are just defaults and can be configured through the `--chan-enable-timeout`, `--chan-disable-timeout`, and `--chan-status-sample-internal` flags.

**Comment by offerm** [comment]
Thank you @wpaulino This worked for me.
