### ISSUE TITLE
[BUG] 512 Missing argument to ADD_ONION

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#3329]
### Background

We have a small number of instances where users are unable to connect just LND to tor. Bitcoind works with Tor just fine. 

Turning Tor off for LND does allow it to boot up properly. 

Deleting Tor data and restarting doesn't seem to help. 

### Your environment

* Has affected both nodes running 0.6.1 and 0.7.0. 
* Linux casa-node-apollo 4.14.70-v7+ #2 SMP Wed Sep 19 07:49:26 UTC 2018 armv7l GNU/Linux)
* Has affected both Bitcoind 0.17.1 and 0.18.0. 
* Running on a raspberry pi 3 b+ in docker containers. 
* Tor version 0.3.5.8.

### Steps to reproduce
I can't reproduce this on any of my nodes. However, a customer out of South Africa experiences this error whenever he turns Tor on for lnd. 

### Expected behaviour

1. Unlock Lnd
2. LND syncs chain
3. LND creates an onion address
4. LND is active

### Actual behaviour

1. Unlock Lnd
2. LND syncs chain
3. LND fails to create an onion address
4. LND is still locked (because it crashes)

Below are LND docker logs. Docker logs are set to `warn` to there are not very many of them.
```
512 Missing argument to ADD_ONION
2019-07-19 17:16:04.671 [ERR] SRVR: unable to start server: 512 Missing argument to ADD_ONION
```

**Comment by wpaulino** [comment]
Are they specifying a custom path for the private key through `--tor.privatekeypath`? If not, do they have a file named either `v2_onion_private_key` or `v3_onion_private_key` within `~/.lnd` _with contents in it_?

**Comment by Roasbeef** [comment]
What version of `tor` are they running also?

**Comment by stridentbean** [comment]
I'm asking for 

> Are they specifying a custom path for the private key through `--tor.privatekeypath`? If not, do they have a file named either `v2_onion_private_key` or `v3_onion_private_key` within `~/.lnd` _with contents in it_?

We use `v3_onion_private_key`, but I'm asking the user to tell me if there are any contents in it. 

> What version of `tor` are they running also?
Tor version 0.3.5.8.

**Comment by stridentbean** [comment]
> Are they specifying a custom path for the private key through `--tor.privatekeypath`? If not, do they have a file named either `v2_onion_private_key` or `v3_onion_private_key` within `~/.lnd` _with contents in it_?

I was able to get the user back on the horn and confirmed the `v3_onion_private_key` is empty. 

![Screen Shot 2019-08-22 at 11 38 32 AM](https://user-images.githubusercontent.com/2092944/63541045-28e84e00-c4d2-11e9-87a8-caa07207ef15.png)

**Comment by wpaulino** [comment]
Removing that file should allow things to work again, though I don't see how this file could've been created with nothing in it.
