### ISSUE TITLE
lnd error after pruning chain to 2GB

### ISSUE THREAD

**Issue by ipty** [lightningnetwork/lnd#3335]
### Background

after pruning my btc from a full chain to 2GB lnd says
LNWL: Unable to complete chain rescan: -1: Block not available (pruned data)
because the block is not longer on the disk

### Your environment

lnd: 7.0-beta
Linux pc 4.15.0-55-generic #60-Ubuntu 

### Steps to reproduce
install a fullchain btc node && lnd
after all doing well after a full btc chainsync set bitcoind to prune to 2GB 

### Expected behaviour
a resyncing on lnd with whats available
or an option to reset the lnd chain without losing the wallet data
(may there is one but i did not find it)

### Actual behaviour
ERR: LNWL: Unable to complete chain rescan: -1: Block not available (pruned data)
"synced_to_chain": stays false

**Comment by cfromknecht** [comment]
From the install docs:

> NOTE: WE DO NOT FULLY SUPPORT PRUNED OPERATING MODES FOR FULL NODES. It's possible to run a node in a pruned mode and have it serve lnd, however one must take care to ensure that lnd has all blocks on disk since the birth of the wallet, and the age of the earliest channels (which were created around March 2018).

You're going to need more than 2GB of storage, and probably need to resync the chain

> or an option to reset the lnd chain without losing the wallet data
> (may there is one but i did not find it)

The on-chain wallet likely needs to be restored, but the exact steps will be dependent on whether the wallet has off-chain funds. Does the wallet have channels?

**Comment by wpaulino** [comment]
If you fully sync the bitcoind node, all you need to do is start `lnd` again and it'll be able to proceed. As stated above, pruned backends are not supported at the moment, though this is something we'll address in the near future.
