### ISSUE TITLE
Regtest hangs on startup when blocks are old

### ISSUE THREAD

**Issue by carlaKC** [lightningnetwork/lnd#3336]
### Background

I run LND with a bitcoind regtest backend and have noticed that it hangs on `Waiting for chain backend to finish sync` on start up. Now that LND is considering a node unsynced if block timestamp > 2 hours old, it hangs quite often. 

It's a really minor issue but I found this exception for simnet in `lnd.go` and was wondering if there's any reason not to include `cfg.bitcoin.RegTest` as well? I would like to add it if there are no objections. 
```
	// If we're not in simnet mode, We'll wait until we're fully synced to
	// continue the start up of the remainder of the daemon. This ensures
	// that we don't accept any possibly invalid state transitions, or
	// accept channels with spent funds.
	if !(cfg.Bitcoin.SimNet || cfg.Litecoin.SimNet) {
```
### Your environment
* LND 0.7.0-beta
* Mojave 10.14.5
* Bitcoind

### Steps to reproduce
1. Run LND with Bitcoind backend
2. Stop LND and do not mine any blocks on regtest for two hours
3. Restart LND and it should hang on waiting to sync because 

### Expected behaviour

Regtest should also proceed with startup despite not being synced to the blockchain, as is the case with Bitcoin/Litecoin.

### Actual behaviour
The regtest LND node waits for you to mine more blocks before it proceeds with startup.

**Comment by wpaulino** [comment]
> It's a really minor issue but I found this exception for simnet in lnd.go and was wondering if there's any reason not to include cfg.bitcoin.RegTest as well? I would like to add it if there are no objections.

There isn't, feel free to open a PR addressing it!
