### ISSUE TITLE
ZAP: Funding tx cannot be found; hanging in pending open

### ISSUE THREAD

**Issue by wdey** [lightningnetwork/lnd#3340]
ZAP case: https://github.com/LN-Zap/zap-desktop/issues/2531
Autopilot enabled !
Problem:
Open a channel to ln1.satoshilabs.com which hangs in pending open since weeks !
0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4
The Funding tx cannot be found
https://blockstream.info/tx/db94d2ffd17c166686d291f56f64d665ff4d0f1a13462200483d3f0ae17de821

lncli --lnddir=C:\Users\wdey\AppData\Roaming\Zap\lnd\bitcoin\mainnet\wallet-3 --rpcserver=127.0.0.1:11009 pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4",
                "channel_point": "db94d2ffd17c166686d291f56f64d665ff4d0f1a13462200483d3f0ae17de821:1",
                "capacity": "250052",
                "local_balance": "241002",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "9050",
            "commit_weight": "600",
            "fee_per_kw": "12500"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

**Comment by LiekosDev** [comment]
I appear to be having the same problem..

https://github.com/lightningnetwork/lnd/issues/3341

**Comment by wpaulino** [comment]
See resolution in #3341.
