### ISSUE TITLE
Stuck pending_open channel for days

### ISSUE THREAD

**Issue by LiekosDev** [lightningnetwork/lnd#3341]
### Background

New to running a LND node, so inexperience may [likely] be a factor.  I've used autopilot to open some channels, and I've since closed them all (or tried to).  For the most part this worked OK, but I still have a zombie pending_open channel for multiple days with no limbo balance.  How do I kill this thing?  NOTE: my channel pending_open balance has also been stuck at **this value**, even though my wallet is/was empty.  (I've since added more funds to try having an active node again, but I'd like to clear out this zombie channel...)

I see no log details pertaining to the channel, and trying to do a closechannel states:
lncli closechannel 60ebbc8ed216604f74e8bc71f768060aa25d23d6d38aa758a2c121afd4b155f0
[lncli] rpc error: code = Unknown desc = channel not found

My node:
https://1ml.com/node/03f28b34c82c8f437d2c23f4dbcb0e2b9377475e3f154f12e5f249fc9e4df229f0

Current State:

lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "021779d56f6992431e959991a664d678a2f41054073adb48c5a351d791c9cb0781",
                "channel_point": "60ebbc8ed216604f74e8bc71f768060aa25d23d6d38aa758a2c121afd4b155f0:1",
                "capacity": "570935",
                **"local_balance": "570741",**
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "194",
            "commit_weight": "600",
            "fee_per_kw": "269"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

### Your environment
mainnet

* version of `lnd`: .7 beta
* which operating system (`uname -a` on *Nix): raspian buster lite 7/10/2019
* version of `btcd`, `bitcoind`, or other backend .18
* any other relevant environment details

### Steps to reproduce

1. Fired up an LND with default autopilot values.
2. Stopped LND, changed default values to increase maxchannels and allocation
3. Started LND
4. Left it running overnight
5. Closed all channels, swept full wallet balance to other address
RESULT: still a zombie pending_open channel days later

### Expected behaviour

No stuck pending_open channels?

### Actual behaviour

Stuck pending_open channel, and stuck pending_open channel balance even though wallet empty.

Thanks!

**Comment by wpaulino** [comment]
Looks like this is just an invalid channel as a result of likely double spending an input. In the future we'll be able to detect this and remove it. For now, you should be able to remove it with the `lncli abandonchannel` command available in a debug build of lnd. You can obtain one by running `make` in lnd's source directory, which will create a `lnd-debug` binary. If the you believe the funds have actually been committed, you'll have to [force a wallet rescan](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan).

**Comment by LiekosDev** [comment]
> Looks like this is just an invalid channel as a result of likely double spending an input. In the future we'll be able to detect this and remove it. For now, you should be able to remove it with the `lncli abandonchannel` command available in a debug build of lnd. You can obtain one by running `make` in lnd's source directory, which will create a `lnd-debug` binary. If the you believe the funds have actually been committed, you'll have to [force a wallet rescan](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan).

This doesn't work.  After compiling the debug binary and swapping it in, I get:

lncli abandonchannel 60ebbc8ed216604f74e8bc71f768060aa25d23d6d38aa758a2c121afd4b155f0
**[lncli] rpc error: code = Unknown desc = channel not found**

So abandonchannel can't even find/see it.  Still in the pending_open list though.  I believe I've gotten the funds back, I'd just like to get rid of this thing so it's not throwing off my channel balance and cluttering up my pending list.

Still:

    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "021779d56f6992431e959991a664d678a2f41054073adb48c5a351d791c9cb0781",
                "channel_point": "60ebbc8ed216604f74e8bc71f768060aa25d23d6d38aa758a2c121afd4b155f0:1",
                "capacity": "570935",
                "local_balance": "570741",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "194",
            "commit_weight": "600",
            "fee_per_kw": "269"
        },

**Comment by wpaulino** [comment]
> I'd just like to get rid of this thing so it's not throwing off my channel balance and cluttering up my pending list.

Given that you've already closed all of your channels, you should start a new node and go through the recovery process then.
