### ISSUE TITLE
"listunspent" is showing already spent output

### ISSUE THREAD

**Issue by peername** [lightningnetwork/lnd#3350]
### Background

"listunspent" command is showing already spent output:

> $ lncli listunspent
> {
>                 ... ,
>                 {
>                         "address_type": 0,
>                         "address": "bc1qqdfaj7c6ccwmm8v4vtch828wn2vmf0p9c99ps0",
>                         "amount_sat": 57783,
>                         "pk_script": "00140353d97b1ac61dbd9d9562f173a8ee9a99b4bc25",
>                         "outpoint": "93c6c2ce92acc3687cbd3ad32ba995c3788132851cf1cd6f7e6a0053d0021840:0",
>                         "confirmations": 57182
>                 }
>         ]
> }

Sometimes the LND is relying on this output and transactions can't be broadcasted. How to force rescan of UTXO set or remove this output?

### Your environment

LND 0.7.0
Ubuntu Server 18.04
bitcoind 0.18.0

### Steps to reproduce

I suppose that the trouble arose a year ago when LND crashed while opening a new channel.

### Expected behaviour

UTXO set must include only unspent transaction.

### Actual behaviour

UTXO set incluses already spent transactions

**Comment by wpaulino** [comment]
> Sometimes the LND is relying on this output and transactions can't be broadcasted. How to force rescan of UTXO set or remove this output?

https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan
