### ISSUE TITLE
Make check failed after updating

### ISSUE THREAD

**Issue by 05nelsonm** [lightningnetwork/lnd#3364]
### Background

- Updated client to most recent version in accordance with prescribed directions
- When finalizing the update via execution of `$ make check`, there was a failure reported

### Your environment

* **version of `lnd`**
lnd version 0.7.1-beta commit=v0.7.1-beta-20-g8c9c4b52e869f1d083f4ba7b1302a0bb964bc6be

* **which operating system (`uname -a` on Nix)**
Linux ubuntu-desktop-vm 4.18.0-25-generic #26~18.04.1-Ubuntu SMP x86_64 GNU/Linux

* **version of `btcd`, `bitcoind`, or other backend**
Bitcoin Core Daemon version v0.18.0

* **any other relevant environment details**
N/A

### Steps to reproduce

`$ cd $GOPATH/src/github.com/lightningnetwork/lnd`
`$ cd git pull`
`$ make clean && make && make install`
`$ make check`
Observe error as reported below under 'Actual behavior' 

### Expected behavior

Execution of `$ make check` should output 'PASS' for all categories

### Actual behavior

Execution of `$ make check` outputs the following:

```
    --- FAIL: TestLightningNetworkDaemon/revoked_uncooperative_close_retribution (18.99s)
        lnd_test.go:99: Failed: (revoked uncooperative close retribution): exited with error: 
            *errors.errorString unable to get bob chan info: node should only have a single channel, instead it has 0
            /home/matthew/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:6877 (0xd29146)
            	testRevokedCloseRetribution: t.Fatalf("unable to get bob chan info: %v", err)
            /home/matthew/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:123 (0xd029b5)
            	(*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
            /home/matthew/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:14312 (0xd6ca64)
            	TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
            /usr/local/go/src/testing/testing.go:865 (0x4fbf00)
            	tRunner: fn(t)
            /usr/local/go/src/runtime/asm_amd64.s:1337 (0x45e751)
            	goexit: BYTE	$0x90	// NOP
FAIL
FAIL	github.com/lightningnetwork/lnd/lntest/itest	969.258s
Makefile:118: recipe for target 'itest-only' failed
make: *** [itest-only] Error 1
```

**Comment by goodc0re** [comment]
Just a note that I am getting the same error. 

       lnd_test.go:99: Failed: (revoked uncooperative close retribution remote hodl): exited with error: 
            *errors.errorString unable to get carol's channel info: node should only have a single channel, instead it has 0
            /home/alone/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:7451 (0xd6fdfa)
                testRevokedCloseRetributionRemoteHodl.func1: t.Fatalf("unable to get carol's channel info: %v", err)
            /home/alone/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:7586 (0xd3af18)
                testRevokedCloseRetributionRemoteHodl: checkCarolBalance(pushAmt - 3*paymentAmt)
            /home/alone/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:123 (0xd10cda)
                (*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
            /home/alone/gocode/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:14675 (0xd7a50c)
                TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
            /usr/local/go/src/testing/testing.go:909 (0x509aa9)
                tRunner: fn(t)
            /usr/local/go/src/runtime/asm_amd64.s:1357 (0x460e81)
                goexit: BYTE    $0x90   // NOP
FAIL
FAIL    github.com/lightningnetwork/lnd/lntest/itest    1033.190s
FAIL
Makefile:115: recipe for target 'itest-only' failed
make: *** [itest-only] Error 1

**Comment by Roasbeef** [comment]
The tests are tuned mostly to run on Travis (timeouts are the main factor), so at times there can be unexpected flakes locally. To my knowledge, I haven't seen this flake in particular flare up recently.
