### ISSUE TITLE
[Question] RTL backup functionality

### ISSUE THREAD

**Issue by maltokyo** [lightningnetwork/lnd#3371]
This is not an issue, rather a question.  I didn't know how to post a question here.

I noticed the "channels" section of RTL now contains a "backups" section for channel backups, that's cool.  What file should I periodically backup (on another server) to ensure the future safety of my channels?  And where can I find the restore process?

Thanks!

**Comment by molxyz** [comment]
@maltokyo Normally info for these things is in the `docs` section of this repo. Here are the guides for backup and recovery:  https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md

Also, if you want faster help, the better places are lnd slack and channel #lnd on IRC.

**Comment by maltokyo** [comment]
Thank you so much. I did see that... however I don’t think that’s applicable for BTCPay server. As we don’t have “out of the box” access (they are not even created) to the 24 word recovery phrases right? So does it mean our LND backups that we see as successful are quite useless?

**Comment by molxyz** [comment]
@maltokyo  You will need to ask them on their GH repo. If you don't have the 24 seed words you can't do onchain funds and channel funds recovery, that is correct.

**Comment by halseth** [comment]
@maltokyo You should take this to the RTL issue tracker.
