### ISSUE TITLE
Update documentation for wtclient

### ISSUE THREAD

**Issue by nolim1t** [lightningnetwork/lnd#3375]
The sample lnd.conf file no longer works for using a watchtower. LND also quits out and doesn't run.

If its gonna be deprecated, it should just warn not just die.

```
wtclient.private-tower-uris` is deprecated and will be removed in the v0.8.0 release, to specify watchtowers remove `wtclient.private-tower-uris`, set `wtclient.active`, and check out `lncli wtclient -h` for more information on how to manage towers
```

Furthermore wtclient actually does not work (seems that it needs the build flag) but can't find it anywhere in the documentation.

**Comment by wpaulino** [comment]
That documentation is outdated as of the master branch and only applies up to the v0.7.1 release. There have been new changes in this area that will be released and documented as part of the v0.8.0 release.

**Comment by cfromknecht** [comment]
> Furthermore wtclient actually does not work (seems that it needs the build flag) but can't find it anywhere in the documentation.

that's a good point, you'll need to compile with `wtclientrpc` to be able to interact with the client via rpc. we should consider compiling that by default since no special compilation was required of users in 0.7.x to use the wtclient

**Comment by cfromknecht** [comment]
Reopening as docs still need to be updated, tho `wtclientrpc` is enabled by default as of #3515
