### ISSUE TITLE
[Docs] [Protobuf] Need steps for regenerating rpc.pb.go

### ISSUE THREAD

**Issue by jacohend** [lightningnetwork/lnd#3376]
There are no steps for regenerating `rpc.pb.go`. All the current instructions do is regenerate the `.proto` files. Could these steps be added?

**Comment by wpaulino** [comment]
The `.proto` files are not generated, these are modified manually. The [current documentation](https://github.com/lightningnetwork/lnd/tree/master/lnrpc#generate-protobuf-definitions) already provides instructions on how to generate new changes made to the `.proto` files.

**Comment by jacohend** [comment]
@wpaulino Following those directions does not generate the root rpc.pb.go files.

**Comment by wpaulino** [comment]
They're already generated and committed to the repository. You'd only need to regenerate them if there are new changes made to the `.proto` files. If no changes were made, regenerating should not produce a diff.

**Comment by jacohend** [comment]
Yes, I'm changing some rpc methods on my own build and need to regenerate. Turns out that my IDE was not picking up the file changes to that directory for some reason. The go files rebuilt fine, but weren't visible.

Thanks for your help.
