### ISSUE TITLE
LND shuts down with rescan error after unlocking wallet

### ISSUE THREAD

**Issue by jacohend** [lightningnetwork/lnd#3386]
### Background

LND using Neutrino consistently shuts down whenever the only wallet is unlocked, with the following errors: 

```
[ERR] NTFN: Error during rescan: rescan exited
[INF] CRTR: FilteredChainView stopping
```

Not much more detail about this error is shown with `--debugLevel=trace`, unfortunately. Logs are attached. 

### Your environment

* version of `lnd`: Latest master, build tag says `github.com/lightningnetwork/lnd/build.Commit=v0.7.1-beta-rc2-6-ga09ecf91d8dcf82ef5dbc22cc9da428d0f62792b`

* which operating system (`uname -a` on *Nix): `4.15.0-1026-gcp #27-Ubuntu SMP Thu Dec 6 18:27:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` 
2 core 8 GB RAM

* version of `btcd`, `bitcoind`, or other backend: **Neutrino**

* any other relevant environment details: Run in docker with .lnd mounted as a volume

### Steps to reproduce

Unlocking my wallet **even after a full data deletion and wallet recovery** will cause lnd to shutdown. Logs after one such recovery event are attached:
 
[lnd_unlock.log](https://github.com/lightningnetwork/lnd/files/3481221/lnd_unlock.log)

**Comment by wpaulino** [comment]
That rescan error is due to `lnd` shutting down, not `lnd` shutting down due to the error. It seems like `lnd` is being shut down manually to me, possibly something to do with docker or your setup?

**Comment by jacohend** [comment]
@wpaulino We're running with docker-compose, using the standard image. LND only shuts down after wallet unlocking. No OOM errors are reported, and there's nothing of note in the systemd logs. We're pretty confused.

**Comment by jacohend** [comment]
I've found we're getting a sigint but no logs from the signal handler. Looking into this more as an errant sigint-related issue. Thanks for your help.
