### ISSUE TITLE
Unable to restore channel backup

### ISSUE THREAD

**Issue by reivanen** [lightningnetwork/lnd#3394]
### Background

Trying to restore from a backup file results in no channels, but wallet balance is ok

### Your environment

* version of `lnd` 0.7.1-beta
* which operating system (`uname -a` on *Nix) ubuntu 18.04
* version of `btcd`, `bitcoind`, or other backend bitcoind Bitcoin Core version v0.18.0.0
* any other relevant environment details

### Steps to reproduce

Try to restore channel backup with a clean .lnd folder

lncli create -multi_file=/home/ubuntu/RTL/backup/channel-all.bak

### Expected behaviour

channels and wallet balance should appear

### Actual behaviour

restore process stops lnd on error message "Unable to start server: unable to unpack chan backup: chacha20poly1305: message authentication failed". Only wallet balance appears.

> 2019-08-06 16:53:15.984 [WRN] LNWL: Could not parse output script in 42d17c7028e27ab775e640122aa78a7d278bdbf6cb6d72c838f6e91a6bb0eb6f:2: opcode OP_DATA_75 requires 76 bytes, but script only has 39 remaining
> 2019-08-06 16:53:15.988 [INF] LNWL: Recovered 1 external addrs at height=545995 hash=0000000000000000001332f21b29c5b5679de255366830017572e17a26f6aac6
> 2019-08-06 16:53:15.988 [INF] LNWL: Found 1 spends from watched outpoints at height=545995 hash=0000000000000000001332f21b29c5b5679de255366830017572e17a26f6aac6
> 2019-08-06 16:53:16.249 [INF] LNWL: Recovered 1 internal addrs at height=545996 hash=0000000000000000001d71b4cda649763d7c1bad81ed4161a610f044744230d5
> 2019-08-06 16:53:16.249 [INF] LNWL: Found 1 spends from watched outpoints at height=545996 hash=0000000000000000001d71b4cda649763d7c1bad81ed4161a610f044744230d5
> 2019-08-06 16:53:16.443 [WRN] LNWL: Could not parse output script in a1813d783a0f84fa53e9377f3853058d4605650d52d3c1f5c7970d36615edcdf:2: opcode OP_DATA_75 requires 76 bytes, but script only has 39 remaining
> ...

similar messages repeat throughout restore process thousands of times. And then in the end:

> ...
> 2019-08-06 19:29:33.500 [INF] LNWL: Recovered addresses from blocks 587409-588891
> 2019-08-06 19:29:33.843 [INF] LNWL: Started rescan from block 0000000000000000000aeb89a1066c9055d710eff9e3e021a1e3740e6d0b873c (height 588891) for 27 addresses
> 2019-08-06 19:29:41.695 [INF] LNWL: Catching up block hashes to height 588911, this might take a while
> 2019-08-06 19:29:41.745 [INF] LNWL: Done catching up block hashes
> 2019-08-06 19:29:41.745 [INF] LNWL: Finished rescan for 27 addresses (synced to block 000000000000000000047728af7b53179cadb76b72d0838d29cf2cfaa520530e, height 588911)
> 2019-08-06 19:29:42.145 [INF] LTND: Chain backend is fully synced (end_height=588911)!
> 2019-08-06 19:29:43.940 [INF] NTFN: New block epoch subscription
> 2019-08-06 19:29:43.940 [INF] HSWC: Starting HTLC Switch
> 2019-08-06 19:29:43.997 [INF] NTFN: New block epoch subscription
> 2019-08-06 19:29:44.170 [INF] NTFN: New block epoch subscription
> 2019-08-06 19:29:44.259 [INF] NTFN: New block epoch subscription
> 2019-08-06 19:29:44.385 [INF] BRAR: Starting contract observer, watching for breaches.
> 2019-08-06 19:29:44.427 [INF] DISC: Authenticated Gossiper is starting
> 2019-08-06 19:29:44.427 [INF] NTFN: New block epoch subscription
> 2019-08-06 19:29:44.707 [INF] CRTR: FilteredChainView starting
> 2019-08-06 19:29:44.714 [INF] CRTR: Filtering chain using 0 channels active
> 2019-08-06 19:29:44.716 [INF] CRTR: Prune tip for Channel Graph: height=588911, hash=000000000000000000047728af7b53179cadb76b72d0838d29cf2cfaa520530e
> 2019-08-06 19:29:45.009 [ERR] LTND: Unable to start server: unable to unpack chan backup: chacha20poly1305: message authentication failed
> 2019-08-06 19:29:45.009 [INF] RPCS: Stopping RPC Server
> 2019-08-06 19:29:45.183 [INF] LTND: Shutdown complete
> Unable to start server: unable to unpack chan backup: chacha20poly1305: message authentication failed
>

**Comment by molxyz** [comment]
@reivanen Did you follow the official guides here:  https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md ? 

>lncli create -multi_file=/home/ubuntu/RTL/backup/channel-all.bak
This looks like you follow RTL's guide and not the LND guide? If so it's not LND issue, you need to ask the RTL folks to help you out.

**Comment by wpaulino** [comment]
> Unable to start server: unable to unpack chan backup: chacha20poly1305: message authentication failed

This error would mean that you were unable to decrypt the channel backup, most likely because it was created with a different seed.

**Comment by reivanen** [comment]
Yes i followed the recovery guide, only changed the path to backup. Also tried lncli restorechanbackup with same result. The seed should not be different because the wallet balance shows up.

**Comment by wpaulino** [comment]
Possibly an error with how the `channel.backup` file is encoded? The file should contain raw bytes -- is this what you're seeing?

**Comment by Roasbeef** [comment]
The script related errors are benign. Our best guess here is that there's an encoding issue, as you seem to be giving it a custom backup file.

**Comment by molxyz** [comment]
@reivanen  I'm curious.. did the channels get closed? What did you see in `pendingchannels` ?

**Comment by reivanen** [comment]
The backup is done using RTL GUI, and it does not have a restore option so i assumed the format is same as LND has.

The process restores correctly the small amount that was reserved in wallet and can be seen with lncli walletbalance, but channelbalance, listchannels, pendingchannels etc. show nothing. So it just rejects the channels even when to me it looks like they are correctly found during the scan.

**Comment by wpaulino** [comment]
> The backup is done using RTL GUI, and it does not have a restore option so i assumed the format is same as LND has.

It seems like RTL is just taking the output of the RPC as the whole backup. I don't know whether they intend this to be parsed by the user or whether this should be what's provided to `lnd`. In either case, the relevant portion here would be the `chan_backup` field in the response above, which is encoded as base64. The response indicates that this is a backup for a single channel, so in order to use this with `lnd`, you'd need to decode base64, encode to hex, and specify it with `lncli restorechanbackup --single_backup HEX`.

> The process restores correctly the small amount that was reserved in wallet and can be seen with lncli walletbalance, but channelbalance, listchannels, pendingchannels etc. show nothing. So it just rejects the channels even when to me it looks like they are correctly found during the scan.

The channel backup won't allow those channels to be used once restored. They'll be closed and the funds will be swept to your wallet.

**Comment by saubyk** [comment]
Hi,
`RTL` makes use of REST APIs to work with `lnd`.

The backup files generated by REST APIs are not inter-operable between the REST and `lncli` interfaces.

We will provide a channel fund restoration feature via the UI, which will use the REST API for channel restoration, so that `RTL` generated backup files can work (https://github.com/ShahanaFarooqui/RTL/issues/177).

In the mean time, you can use the instruction provided in the following comment, to manually restore the channels from your current backup files.

At the risk of stating the obvious, please note that the channel fund restoration will only work if the node has been recovered with the same original seed, which were used for the backup file.

**Comment by saubyk** [comment]
Step 1: Get hex value of macaroon for header:
`~\AppData\Local\Lnd\data\chain\bitcoin\testnet\admin.macaroon` => Encode to Base64 => Convert Base64 value to Hex = `<YourHexMacaroon>`

Step 2: Get `lnd` server url from `RTL`:
Go to your `~RTL/<multinode/singlenode>config` and get the value of `lndServerUrl` to replace `<lndServerUrlFromRTLConfig>` in the command.

Step 3: Copy EITHER `multi_chan_backup` OR `chan_backups` from `channel-all.bak` file in below signature:
```
multi_chan_backup JSON:
{
    "multi_chan_backup": "7mI7ax1+dVDI...."    
}
```
OR
```
chan_backups JSON:
{
    "chan_backups": {
        "chan_backups": [
            {
                "chan_point": {
                    "funding_txid_bytes": "SmkqsLT..."
                },
                "chan_backup": "09CXNGkJfa8..."
            },
            {
                "chan_point": {
                    "funding_txid_bytes": "PgQOdl..."
                },
                "chan_backup": "coeUutg2d07wk24FA...."
            }
        ]
    }
}
```

Step 4: Use CURL or Postman to execute POST API:
`curl -d '<multi_chan_backup JSON OR chan_backups JSON>' -H "Grpc-Metadata-macaroon:<YourHexMacaroon>" -H "Content-Type: application/json" -X POST <lndServerUrlFromRTLConfig>/channels/backup/restore`

**Comment by wpaulino** [comment]
Thanks for clarifying @saubyk! Will close as there isn't actually an issue here, just a matter of providing the format `lncli restorechanbackup` expects.

**Comment by reivanen** [comment]
Thanks, i was able to use a base64 to hex converter and get the channels closed and coins in wallet.

Is the failure to import a LND bug or is the correct place to continue this on RTL's bug tracker?

**Comment by MykelSIlver** [comment]
> @reivanen I'm curious.. did the channels get closed? What did you see in `pendingchannels` ?
> 
> > Trying to restore from a backup file results in no channels, but wallet balance is ok
> 
> The SCB recovery doesn't bring back your channels but it asks your remote peers to close those channels. So if they closed your channels, the funds go back to your wallet.

What if you did a force close because of the other party took off his lightning node? Are those funds lost because the backup file results in no channels?
I am currently in the middle of this situation now. Or do I simply have to wait until the wait till maturity time lock is expired (over 1400 blocks) and see the funds automatically back in my wallet? Thanks in advance
