### ISSUE TITLE
Error in making process

### ISSUE THREAD

**Issue by Liaojinghui** [lightningnetwork/lnd#3395]
routing/route/route.go:159:11: unknown field 'HopData' in struct literal of type sphinx.OnionHop
routing/route/route.go:179:11: path[i].HopData undefined (type sphinx.OnionHop has no field or method HopData)
Makefile:85: recipe for target 'build' failed

**Comment by molxyz** [comment]
@Liaojinghui  Could you give more info such as what go version you have, what type of computer OS, etc.

**Comment by Liaojinghui** [comment]
> @Liaojinghui Could you give more info such as what go version you have, what type of computer OS, etc.

go version is 1.10.4 on 64-bit ubuntu linux 18.04LTS

**Comment by Liaojinghui** [comment]
> @Liaojinghui Could you give more info such as what go version you have, what type of computer OS, etc.

Problem solved after updating to go1.12. Thanks.

**Comment by pinheadmz** [comment]
Getting this error now on a fresh install at `v0.7.1-beta` using go version 1.13 linux/arm

**Comment by pinheadmz** [comment]
Seems to be fixed in master branch 20a5ee2f1ee5b233bd301e263f296e7611e0ea07
