### ISSUE TITLE
ERROR: No such service: alice

### ISSUE THREAD

**Issue by Liaojinghui** [lightningnetwork/lnd#3408]
### Background
Ttying to establish a lightning network cluster running on the testnet.

Describe your issue here.
I was following the instructions in this file https://github.com/lightningnetwork/lnd/tree/master/docker

But when i try to run Alice with command: `docker-compose up -d "alice";`

I got this error: ERROR: No such service: alice

### Your environment

* version of `lnd`
0.7.1-beta

* which operating system (`uname -a` on *Nix)
Ubuntu 18.04 64bit

* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce
Run `docker-compose run -d --name alice lnd_btc` to create a new container.
Colse it first, then run `docker-compose up -d "alice"` to bring it back.

### Expected behaviour
Container Alice should back online.

### Actual behaviour
Error, could not find Alice

**Comment by valentinewallace** [comment]
Are you referring to [this line](https://github.com/lightningnetwork/lnd/blame/master/docker/README.md#L310)? Yeah, I don't think that works. Would you like to submit a PR changing that line to: 
```
docker-compose run -d --name alice lnd_btc; docker exec -it "alice" bash
```
? :)

**Comment by Liaojinghui** [comment]
#3411

**Comment by Liaojinghui** [comment]
> Are you referring to [this line](https://github.com/lightningnetwork/lnd/blame/master/docker/README.md#L310)? Yeah, I don't think that works. Would you like to submit a PR changing that line to:
> 
> ```
> docker-compose run -d --name alice lnd_btc; docker exec -it "alice" bash
> ```
> 
> ? :)

I think simply fixing this problem won't help much. This version of instruction is out of data and can not be used directly to switch the network from `simnet` to `testnet`.
