### ISSUE TITLE
Multi-hop transaction fail because of unable to find a path in my test environment

### ISSUE THREAD

**Issue by Liaojinghui** [lightningnetwork/lnd#3416]
### Background
I set up ten lnd instances in my Ubuntu 18.04 and connected them in a linear topology (node_i ->node_i+1). All of my test accounts are funded enough test bitcoin and 9 channels are created with the same topology as the network connection. After 3 confirmation, direct channels could successfully process transactions, but it still could not find a valid path to do the multi-hop transaction. 

### Your environment

* version of `lnd` = the newest version from the git master branch.
* which operating system  = Ubuntu 18.04 
* version of `btcd`, `bitcoind`, or other backend = Which is also the newest from the master branch.

### Steps to reproduce
Create at least three new lnd instances and create at least 2 channels to connect them together in a linear way.

### Expected behaviour

Assume we have node `A`, `B`, and `C` connected with channel `c_1` and `c_2` in a way like `A-> c_1 ->B-> c_2 ->C ` 
I was expecting that as long as `c_1` could handle transaction between `A` and `B`; `c_2` could handle `B` and `C`, it should be able to send coin from A to C through HTLC. 

### Actual behaviour

What I got it could not find a valid path. every channel has 50000 satoshis in both sides, and I only send 10 satoshis for each transaction, the fee for each node is 1 satoshi.

**Comment by Liaojinghui** [comment]
It works now after 6 confirmation. So weird, is that direct channel needs 3 confirmations while  HTLC needs 6 confirmations?

**Comment by cfromknecht** [comment]
@Liaojinghui yes that's correct, the channel is usable after 3 confs but it isn't announced to the wider network until 6. until that happens the channel can't forward HTLCs

**Comment by Liaojinghui** [comment]
> @Liaojinghui yes that's correct, the channel is usable after 3 confs but it isn't announced to the wider network until 6. until that happens the channel can't forward HTLCs

Thank you for answering.
