### ISSUE TITLE
Payment to hold invoices hangs

### ISSUE THREAD

**Issue by bucko13** [lightningnetwork/lnd#3417]
### Background

I'm trying to pay and settle hold invoices but any attempt to pay just hangs (both running as a script w/ grpc or via cli or via lightning joule) and when I try and settle it says the invoice is still open. Issue #2975 seems similar except that even the payment fails so settling in a separate terminal session also doesn't work (since the invoice is still open and not held).

### Your environment

* lnd 0.7.1-beta commit=v0.7.1-beta-rc2-20-g55b481c4194d64ed049be598e44bd8d441ded0ca
* Ubuntu 18.04.2 LTS
*  neutrino backend
* running a docker container on a VPS

### Steps to reproduce

`alice addholdinvoice PreimageHashHex Amount`

`bob payinvoice PaymentRequest`

... bob's CLI wait's indefinitely

... in a separate terminal session
`alice settleinvoice PreimageHex `

... returns error:
`[lncli] rpc error: code = Unknown desc = invoice still open`

The above happens when running w/ grpc as well. Running the test from `ln-service` (see [here](https://github.com/alexbosworth/ln-service/blob/1e063252348c0adc78006ae3f90edebc7cfcdcd6/test/invoicesrpc-integration/test_subscribe_settle_invoice.js) with the timeouts for paying and settling, payment also doesn't seem to go through and I get the same `invoice still open` error.

### Expected behavior

I would expect the `payinvoice` command to return something, though I understand that is not currently the way it works. Absent that, I would expect the invoice to change state when the `payinvoice` command goes out and that alice would be able to settle the hold invoice.

### Actual behaviour

payment command hangs and settlement fails because invoice is still open.

**Comment by wpaulino** [comment]
> [lncli] rpc error: code = Unknown desc = invoice still open

This means you're attempting to settle the invoice before a HTLC that satisfies it has been received by the payee. This is likely just a timing issue. To determine when you're able to settle it, you can use the `SubscribeSingleInvoice` RPC to notify you when the invoice has transitioned to an accepted state.

**Comment by wpaulino** [comment]
The payment command hangs from the payer's side because the payment is not being settled/canceled by the receiver.

**Comment by bucko13** [comment]
Thanks @wpaulino. I was continuing to play around with it and found that to be the case. Unfortunately had to make the timers a lot longer than they were in the ln-service tests presumably because they are live channels that could take longer to receive the payment. I was going to try with the subscription next, but it does feel like it would be nice to have some kind of response when a payment is received and the state changes, even if it doesn't change to `settled`. This makes for easier synchronous script constructions, simplifies the CLI interaction, and can add some clarity in the payment flow of a script in allowing for synchronous-like flows. e.g. wait for this payment to confirm as sent, then move on to step 2. And if we don't get that `200` response to confirm then deal with it accordingly. 

I saw it mentioned in that other issue that this interface was something that could be updated, but thought I'd throw in another two cents.

**Comment by wpaulino** [comment]
> I was going to try with the subscription next, but it does feel like it would be nice to have some kind of response when a payment is received and the state changes, even if it doesn't change to settled.

This should already be the case with the `SubscribeSingleInvoice` RPC, unless you're referring to something else. It'll notify you of state changes to `accepted`, `canceled`, and `settled`.

**Comment by bucko13** [comment]
Yes, I was able to get this working with `SubscribeSingleInvoice` so it's not a major blocker. More just that from a UX standpoint when using the CLI the hang is very confusing when you expect some response when the payment has been accepted even if not settled (I wasn't even aware of what could be the issue until searching GitHub issues). 

Even when using the gRPC it can be kind of awkward in certain situations to code around it, which was the case in the ln-service tests. There is one where it tests the subscriptions and is structured as you describe, but [another](https://github.com/alexbosworth/ln-service/blob/master/test/invoicesrpc-integration/test_settle_invoice.js#L77) that has to use a weird, non-deterministic timeout in the hopes that a payment state has changed in time. When making network calls, the expectation would be some kind of response that the request was heard and responded to.

**Comment by wpaulino** [comment]
> More just that from a UX standpoint when using the CLI the hang is very confusing when you expect some response when the payment has been accepted even if not settled

Ah I see, from the payer side you're not able to tell what the status of the HTLC is once you've sent it. This is just how things work at the protocol level. All you can do is wait to hear back.

**Comment by bucko13** [comment]
Ok, I could see how that would be complicated from the protocol level. I’m not familiar enough with the routing mechanisms, but I have seen errors come back from failed payment attempts due to a route failing for some reason, and I guess there’s no way to differentiate between payment failure and payment held? Would it make sense to maybe have a shorter timeout for the CLI call?

**Comment by wpaulino** [comment]
> but I have seen errors come back from failed payment attempts due to a route failing for some reason, and I guess there’s no way to differentiate between payment failure and payment held?

If a payment is held then there is no response at all. You have to wait for a settle/fail back.

> Would it make sense to maybe have a shorter timeout for the CLI call?

The CLI currently only provides access to the synchronous payment API. If you look at the [router sub-server](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/routerrpc/router.proto), you'll see a series of new asynchronous APIs where nothing blocks and you rely on subscriptions to deliver results as soon as they're ready. I believe there isn't a timeline at the moment to migrate the CLI towards this new API though.

**Comment by wpaulino** [comment]
Closing as there isn't an actual issue here. I'd suggest joining our [slack](https://join.slack.com/t/lightningcommunity/shared_invite/enQtMzQ0OTQyNjE5NjU1LWRiMGNmOTZiNzU0MTVmYzc1ZGFkZTUyNzUwOGJjMjYwNWRkNWQzZWE3MTkwZjdjZGE5ZGNiNGVkMzI2MDU4ZTE) where there's a greater active audience if you have any other questions.

**Comment by bucko13** [comment]
Appreciate the help and feedback!
