### ISSUE TITLE
Can not open channel - "Peer not online"

### ISSUE THREAD

**Issue by Kineticmb** [lightningnetwork/lnd#3422]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment]
Opening a channel requires communication with the peer, so if they are not online then it is not possible.
