### ISSUE TITLE
GetNodeInfo returns inaccurate policies for channels

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#3426]
### Background

When using getNodeInfo to look up node channels, the set of channels with policies is returned, however some of the policies are reversed.

This error seems to be due to a confusion between returned values, `FetchChannelEdgesByID` returns edges as in their public key lexicographical order whereas `ForEachChannel` returns edges as in order of their relationship between outgoing and incoming vs the node queried.

A workaround is to use getchaninfo on the channel ids returned by getNodeInfo, getchaninfo will use `FetchChannelEdgesByID` which returns the lexicographical order 

### Your environment

* lnd 0.7.1-beta on Ubuntu  - through LND 0.11.1-beta
* Bitcoin Core 0.18.0

### Steps to reproduce

Call getNodeInfo on a large set of channels, where there will be a conflict between the outgoing vs ingoing and node1 vs node2.

Some of the policies will be reversed

### Expected behaviour

Policies should reflect their author's set policies

### Actual behaviour

Semi-random policies are returned due to potential conflicts

**Comment by alexbosworth** [comment]
I still see this as an issue in 0.11.0

Calling `GetNodeInfo` on my own node: `03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7`

I get this response:

```
{
  channels: [
    {
      channel_id: '623236176062709761',
      chan_point: 'b1376838b3635d67373ca611c2ce7c94d16ad9af514ec007fb546aa256818b7b:1',
      last_update: 1599503036,
      node1_pub: '031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0',
      node2_pub: '03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7',
      capacity: '5000000',
      node1_policy: {
        time_lock_delta: 144,
        min_htlc: '1000',
        fee_base_msat: '1000',
        fee_rate_milli_msat: '2500',
        disabled: false,
        max_htlc_msat: '4950000000',
        last_update: 1599502373
      },
      node2_policy: {
        time_lock_delta: 144,
        min_htlc: '1000',
        fee_base_msat: '1000',
        fee_rate_milli_msat: '1',
        disabled: false,
        max_htlc_msat: '4950000000',
        last_update: 1599503036
      }
    },
```

So node 2 in this case is my node, and it lists my fee rate as being 1, but my fee rate is 2500. It switches the policies around

You can repro this with lncli as well:

`lncli getnodeinfo 03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7 --include_channels`

```
    "channels": [
        {
            "channel_id": "623236176062709761",
            "chan_point": "b1376838b3635d67373ca611c2ce7c94d16ad9af514ec007fb546aa256818b7b:1",
            "last_update": 1599503036,
            "node1_pub": "031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0",
            "node2_pub": "03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7",
            "capacity": "5000000",
            "node1_policy": {
                "time_lock_delta": 144,
                "min_htlc": "1000",
                "fee_base_msat": "1000",
                "fee_rate_milli_msat": "2500",
                "disabled": false,
                "max_htlc_msat": "4950000000",
                "last_update": 1599502373
            },
            "node2_policy": {
                "time_lock_delta": 144,
                "min_htlc": "1000",
                "fee_base_msat": "1000",
                "fee_rate_milli_msat": "1",
                "disabled": false,
                "max_htlc_msat": "4950000000",
                "last_update": 1599503036
            }
        },
```

**Comment by halseth** [comment]
Re-opening per https://github.com/lightningnetwork/lnd/issues/3426#issuecomment-688542887

**Comment by Roasbeef** [comment]
Resolved now?

**Comment by alexbosworth** [comment]
This is still the case in LND 0.12.0

**Comment by apotdevin** [comment]
And on LND 0.12.1
