### ISSUE TITLE
LND Rest API Estimate Fee Endpoint incorrect?

### ISSUE THREAD

**Issue by mandelmonkey** [lightningnetwork/lnd#3430]
### Background

When using the estimate fee endpoint in the REST API aka
https://api.lightning.community/rest/#get-v1-transactions-fee

it does not require the AddrToAmount parameter like this GRPC version requires, furthermore when making a request it returns the error "no outputs"

### Your environment

* version of `lnd`
0.7
* which operating system (`uname -a` on *Nix)
Mac OS 10.14.6
* version of `btcd`, `bitcoind`, or other backend
bitcoind 18.1
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
I made a request to the REST api over TOR like so
http://vmsgj6t6t2l542rt3hqacpyqtt5upimhxfefiejkkrjiylblwzmys4id.onion/lnd-rest/btc/v1/transactions/fee?target_conf=2

### Expected behaviour

The API should require the AddrToAmount parameter but this is not stated in the documentation

Tell us what should happen

### Actual behaviour

AddrToAmount is not required according to the documentation and a "no outputs" error is returned

**Comment by mandelmonkey** [comment]
ok thanks good to know will close

**Comment by mandelmonkey** [comment]
Actually im not sure it even works by adding the field, I tried both
 
`http://vmsgj6t6t2l542rt3hqacpyqtt5upimhxfefiejkkrjiylblwzmys4id.onion/lnd-rest/btc/v1/transactions/fee?target_conf=2&AddrToAmount=%7B%22tb1qha3jslcuc5dp4fneyf82373m7yq45a3x7k8ncq%22%3A10000%7D`
 
and
 
`http://vmsgj6t6t2l542rt3hqacpyqtt5upimhxfefiejkkrjiylblwzmys4id.onion/lnd-rest/btc/v1/transactions/fee?target_conf=2&AddrToAmount={"tb1qha3jslcuc5dp4fneyf82373m7yq45a3x7k8ncq":10000}`
 
and get a 

`unexpected type map[string]int64 in *lnrpc.EstimateFeeRequest`

feels like it should be a POST request not GET for transactions/fee

**Comment by mandelmonkey** [comment]
like this?
```btc/v1/transactions/fee?target_conf=2&AddrToAmount[tb1q2wjf5tnsuccqk63pfnpcjkq9zdejess2urm3uz]=10000
```

**Comment by mandelmonkey** [comment]
like this?
```
btc/v1/transactions/fee?target_conf=2&AddrToAmount[tb1q2wjf5tnsuccqk63pfnpcjkq9zdejess2urm3uz]=10000
```

**Comment by mandelmonkey** [comment]
not yet with this ```https://btcpay.mandelduck.io/lnd-rest/btc/v1/transactions/fee?target_conf=2&AddrToAmount[1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE]=10000```

I get a ```no outputs``` error

**Comment by wpaulino** [comment]
Gotcha, seems like this is something out of our control until the underlying issue is fixed unless we were to modify the API to be `POST` instead, which would be a breaking change.

**Comment by mandelmonkey** [comment]
ok thanks so should I keep this issue open?

**Comment by wpaulino** [comment]
Yeah. Once that's been resolved and is included in a release, we can update the dependency on our side.

**Comment by wbobeirne** [comment]
Hey @mandelmonkey, this request seems to work fine for me

```
v1/transactions/fee?target_conf=2&AddrToAmount[tb1qha3jslcuc5dp4fneyf82373m7yq45a3x7k8ncq]=10000
```
returns
```
{
    "fee_sat": "2496",
    "feerate_sat_per_byte": "17"
}
```
Not sure if this is something different between 0.7.0 and 0.9.1, but thought you should know!

**Comment by wpaulino** [comment]
We've upgraded the dependency responsible for this multiple times now since the last activity in this issue, so it could very well be resolved.

**Comment by guggero** [comment]
Yes, it probably works now. But the documentation still doesn't show the parameter at all. Not sure if we'll ever fix that as it's in the swagger generator which we cannot update further because of a bug.

**Comment by mandelmonkey** [comment]
@wbobeirne cheers for letting me know will take a look
