### ISSUE TITLE
Recovering a wallet from seed with -multi_file=channel.backup balance not reflected

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#3451]
### Background

While upgrading I ran in to a database migration issue (possibly unrelated, see bottom of issue).

I was worried that since the upgrade seemed to fail that the database was unrecoverable so I attempted a wallet recovery from seed and using the SCB option.  When I `lncli closedchannels` I added up all of the `settled_balance`s and noted how many sats it should be assuming that is the balances that I should be recovering from those channels (it is pretty close to what I expected so I'm assuming it's close)

### Your environment

* version of `lnd` - lncli version 0.7.1-beta commit=v0.7.1-beta-155-g06206f09b5c0c29654110b5cb95a85a9c0e75e14
* which operating system (`uname -a` on *Nix) - ubuntu
* version of `btcd`, `bitcoind`, or other backend - bitcoind
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

I expected `lncli walletbalance` to reflect the closed channel balances.

### Actual behaviour

I checked all transactions from `lncli listunspent` and compared to `lncli walletbalance` and those two balances match but I don't see the balances from the channels anywhere.  `lncli listchaintxns` does not seem to have anything recent from closed channels either.

#### Migration output

```
[INF] CHDB: Checking for schema update: latest_version=10, db_version=8
[INF] CHDB: Performing database schema migration
[INF] CHDB: Applying migration #9
[INF] CHDB: Migrating outgoing payments to new bucket structure
[INF] CHDB: Migration of outgoing payment bucket structure completed!
[INF] CHDB: Applying migration #10
[INF] CHDB: Unable to apply migration #10
[ERR] LTND: Unable to open channeldb: unexpected EOF
```

**Comment by Roasbeef** [comment]
You can return to 0.7.1, and you'll be able to boot up.

**Comment by Roasbeef** [comment]
Also note that the `settled_balance` field in the output there may not always be 100% accurate as it can represent the _max_ amount we may be able to retrieve.

**Comment by wpaulino** [comment]
> When I lncli closedchannels I added up all of the settled_balances and noted how many sats it should be assuming that is the balances that I should be recovering from those channels (it is pretty close to what I expected so I'm assuming it's close)

It's also possible that you spent some of the balance from those closed channels in new channels or other on-chain transactions.
