### ISSUE TITLE
Go modules likes the rc tags better than the proper release tag

### ISSUE THREAD

**Issue by snowzach** [lightningnetwork/lnd#3454]
### Background

If I do a `go get -u` on my project that depends on the this repo, go likes the rc tags better than the plain beta tag.

### Your environment

0.7.1-beta
linux
go1.12.9

### Steps to reproduce

Write a simple project that depends on lnd such as a simple grpc client

### Expected behaviour

`go get -u` would update to the latest version of lnd

### Actual behaviour

`go get -u` will update to the latest rc... 

So if I use v0.7.1-beta in my go.mod and I issue a `go get -u` it will update to `v0.7.1-beta-rc2`

I am not really sure what the best way to fix this is. I think the `-beta` in the name confuses go modules. I fear this could cause some major issues for folks as it could possibly revert important security fixes or something. (unlikely but possible)

The only other thing I could suggest is at least for safety's sake, make one last RC before cutting a release such that if someone does happen to do this at least they would still be using the right version.

**Comment by molxyz** [comment]
> So if I use v0.7.1-beta in my go.mod and I issue a `go get -u` it will update to `v0.7.1-beta-rc2`

@snowzach  Not sure what you meant. Can you paste the whole line of your command ? Thx.

**Comment by wpaulino** [comment]
Confirmed I was able to reproduce. This is likely due to all of our release tags including `beta`.

**Comment by cfromknecht** [comment]
how do we plan to address this? drop the `-beta` from tags?

**Comment by wpaulino** [comment]
> The only other thing I could suggest is at least for safety's sake, make one last RC before cutting a release such that if someone does happen to do this at least they would still be using the right version.

We'll be proceeding with this approach going forward, so this can be closed.

The fact that Go picks a pre-release tag when there's a proper release tag available does seem weird to me, and could possibly point to a bug there.

**Comment by snowzach** [comment]
@wpaulino I think the issue here is that lnd is using dashes to separate the pre-release tags and the build version. According to the semver rule here: https://semver.org/#spec-item-11 I think it would work properly if you used a `.` to separate the pre-release tag with the build tag. 

For example: `v0.8.2-rc1.beta < v0.8.2-rc2.beta < v0.8.2.beta` if I read it correctly.

That's the rules anyhow, I have not validated if go implements them correctly yet.
