### ISSUE TITLE
Cancel/Delete pending open channels when stuck

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#3457]
### Background

I have five pending open channels where the output is already spent. These five channels are stuck forever in this state because the funding output has already been used. This becomes confusing because it appears I have my existing wallet balance and these stuck duplicate pending open channels.

Currently, the only remedy is to erase this wallet and create a new wallet. 

LND should automatically delete these from pending channels list. 

Logs
```
2019-09-03 21:55:13.227 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(SCRUBBED:1): Transaction rejected: output already spent
2019-09-03 21:55:18.291 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(SCRUBBED:1): Transaction rejected: output already spent
2019-09-03 21:55:18.889 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(SCRUBBED:0): Transaction rejected: output already spent
2019-09-03 21:55:19.512 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(SCRUBBED:1): Transaction rejected: output already spent
2019-09-03 21:55:20.136 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(SCRUBBED:1): Transaction rejected: output already spent
```

### Your environment

- lnd 0.7.0.
- Linux casa-node 4.14.70-v7+ #2 SMP Wed Sep 19 07:49:26 UTC 2018 armv7l GNU/Linux)
- Has affected both Bitcoind 0.18.0.
- Running on a raspberry pi 3 b+ in docker containers.
- Tor version 0.3.5.8.

### Steps to reproduce

I'm unsure how this happened or how to reproduce it. But, I suspect it has to do with attempting and failing to broadcast a low fee open channel transaction. Then removing all funds from the wallet. 

### Expected behaviour

A pending channel should be canceled/deleted if it can never be completed. 

### Actual behaviour

Pending channels become stuck forever if the funding output has already been spent.

**Comment by wpaulino** [comment]
You can use the `lncli abandonchannel` command with a debug version of lnd. You can obtain one by running `make` in lnd's source directory -- the resulting binary will be named `lnd-debug`.

**Comment by stridentbean** [comment]
@wpaulino I've confirmed I can abandon channels. This should solve the immediate issue. Are there any plans on fixing the root of the issue? 

I've had a few other users experience this issue in the wild. Making abandon channel available in the non debug version, could help. I don't really want to ship a debug version of LND to our users. Auto abandoning the channel if the transaction is rejected should be the correct solution.

**Comment by wpaulino** [comment]
We're aware of the issue but it's not as high of a priority as other things going on at the moment.

> I've had a few other users experience this issue in the wild.

Since I know Casa uses autopilot, this might've been due to https://github.com/lightningnetwork/lnd/pull/3342.

**Comment by chpio** [comment]
> uses autopilot

im having the same problem, it was caused by the autopilot (i think it was lnd v0.11)
