### ISSUE TITLE
LND crashes on startup can't access funds

### ISSUE THREAD

**Issue by Rabbit7744** [lightningnetwork/lnd#3459]
I was setting up my LND node and installed RTL (ride the lightning)
As I was using it to create new channels I noticed an option to use unconfirmed transactions, since my stuff was currently still unconfirmed I thought, sure!

However, my balance stopped showing up, so I restart.
Now, LND won't start anymore and I don't know how to access the channels in order to close them and get them back.

This is the error it gives me when I try to unlock my wallet. It seems to work okay before that.

2019-09-04 04:16:26.513 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2019-09-04 04:16:26.513 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2019-09-04 04:16:26.514 [INF] LTND: Waiting for chain backend to finish sync, start_height=593152
2019-09-04 04:16:27.123 [DBG] LNWL: Chain backend synced to tip!
panic: Unable to synchronize wallet to chain: t: short read (expected 8 bytes, read 0)

goroutine 114 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000254500)
        /home/opti/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190712034938-7a3a3e82cbb6/wallet/chainntfns.go:117 +0x149d
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
        /home/opti/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190712034938-7a3a3e82cbb6/wallet/wallet.go:191 +0x153
opti@ubuntu:~/lnd$

Using Ubuntu 18.08
LND Version: 0.7.1-beta commit=v0.7.1-beta-155-g06206f09b5c0c29654110b5cb95a85a9c0e75e14
bitcoind
Latest version of RTL

**Comment by molxyz** [comment]
@Rabbit7744  You need to report to RTL folks on their Github repo. The LND dev team has nothing to do with RTL.

**Comment by Rabbit7744** [comment]
@molxyz I understand that the LND has nothing to do with RTL, I don't really want to use RTL anymore though. Just looking for a way at the moment to start LND back up so I can get to my stuff.

**Comment by molxyz** [comment]
@Rabbit7744  
If you have the seed words and channel.backup file, you should be able to recover your funds by starting a new lnd instance and follow the SCB guides. Your `channel.backup` should be in the default location `~/.lnd/data/chain/bitcoin/mainnet/channel.backup` 

And here are the guides:  https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md

You can also ask on the LND slack for help if needed.

**Comment by wpaulino** [comment]
Are you seeing this error reliably upon unlocking the wallet? Any other logs available?

**Comment by Rabbit7744** [comment]
@wpaulino It does happen upon unlocking the wallet, I don't think I have any other logs.
I doesn't even save the error to the .log file, it's just throwing it in my console.

**Comment by wpaulino** [comment]
Yeah recovering is probably your best bet here, though I'm still interested in how you arrived at this state. Do you have the logs before running into the issue?

> I doesn't even save the error to the .log file, it's just throwing it in my console.

That's because the program crashed and it can't write the output to the log file.

**Comment by Rabbit7744** [comment]
Recovery went okay. I tried digging through the logs but can't discover anything out of order.
My guess is that it had to do with the RTL option of spending unconfirmed transactions, however I'm not willing to try and recreate the issue.
Thank you for your assistance!
