### ISSUE TITLE
Question how to setup lnd.conf file correctly

### ISSUE THREAD

**Issue by PimPum** [lightningnetwork/lnd#3460]
### Background

Hi, I am not a developer or anything but I am using Bitcoins since 2011 and now I finally managed to set up the LN deamon with bitcoind on a Raspberry 4.
But I have trouble configuring the lnd.conf file correctly and dont know where to ask those questions other than here. I think for you those questions are easily answered.
My node is supposed to be reachable from outsinde 24/7 and I have a changing IPv4 and IPv6 address.

1. Do I have to set it like in the lnd sample if the node is supposed to be reached via IPv4 and IPv6? Why listen to Port 9736 with an IPv6 address? Or is it default anyways and I dont have to write it in lnd.conf?
listen=0.0.0.0:9735
listen=[::1]:9736  (why is there a "1" within the address?)

2. On my Firewall I have to open Port 9735 for IPv4 and 9736 for IPv6?

3. I have a changing IP every few days. What do I have to enter to broadcast the actual IPv4 and IPv6 automaticcally without manually setting the external IP evertime it changes?
externalip=87.173.00.87
externalip=2003:EB:671E::DEA6:32FF:FE03:E7EC

Thank you in advance :)

### Your environment

* version 0.7.1
* Raspbian Debian Buster
* bitcoind

**Comment by molxyz** [comment]
@PimPum 
Hi, This GH repo is mainly for reporting issues, bugs, problems... But the best place to ask for help with tech support is LND Slack. Here's the link to join the slack:  https://join.slack.com/t/lightningcommunity/shared_invite/enQtMzQ0OTQyNjE5NjU1LWRiMGNmOTZiNzU0MTVmYzc1ZGFkZTUyNzUwOGJjMjYwNWRkNWQzZWE3MTkwZjdjZGE5ZGNiNGVkMzI2MDU4ZTE

**Comment by PimPum** [comment]
thank you :)
