### ISSUE TITLE
Connecting multiple LNDs on internal network

### ISSUE THREAD

**Issue by dmidnight** [lightningnetwork/lnd#3464]
### Background

I have 2 LND nodes that can connect to external peers correctly. 

Setup:
LND1 at 10.0.0.100:9735
LND2 at 10.0.0.101:9736

Both nodes are setup with externalip=myexternalip:port and I can see that looks correct when using getinfo.

When I connect from LND1 to LND2:
- it connects, and shows LND2 port in listpeers correctly.

When I call listpeers on LND2:
- it shows LND1 with the port it connected from, not LND1's correct port. example: 43107 instead of 9735.

### Your environment

* version of `lnd` - 0.7.1-beta
* which operating system (`uname -a` on *Nix) - ubuntu 18.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.17.1
* any other relevant environment details - 2 separate machines on LAN, no firewalls, using externalip

### Steps to reproduce

See background above

### Expected behaviour

listpeers on both machines should show the other peer with the correct port.

### Actual behaviour

listpeers on the target machine shows the source machine with incorrect port. Tools like the Joule browser plugin show the other node as offline from both sides. Cannot create channel between nodes.

**Comment by wpaulino** [comment]
> it shows LND1 with the port it connected from, not LND1's correct port. example: 43107 instead of 9735.

This is expected and wouldn't say it's incorrect. We show the address of the connection we've established with the peer.

If you're interested in seeing the advertised addresses of a node, you can use the `getnodeinfo` command/RPC.

**Comment by dmidnight** [comment]
`getnodeinfo` results in [lncli] rpc error: code = Unknown desc = unable to find node from either side

**Comment by wpaulino** [comment]
Nodes are only advertised after opening a public channel.

**Comment by dmidnight** [comment]
Ah, right... I had pending channels from lnbig but nothing actually open yet. 

Thanks
