### ISSUE TITLE
lnd.conf:4: strconv.ParseBool: parsing "1\r\rbitcoin.mainnet=1": invalid syntax

### ISSUE THREAD

**Issue by Kineticmb** [lightningnetwork/lnd#3472]
Just trying to set up lnd on windows 10

get the above error when trying to run lnd.exe in powershell

windows 10 laptop

* version of `lnd` 0.7.1
* which operating system : Windows 10
* bitcoind - Bitcoin core version 18.1
* any other relevant environment details

### Steps to reproduce

Simply trying to run lnd.exe on powershell

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment]
What does your config file look like?

**Comment by Kineticmb** [comment]
# Auto-Generated Configuration File

# Node Launcher version 6.0.5

debuglevel=info

bitcoin.active=1

bitcoin.mainnet=1

bitcoin.node=bitcoind

restlisten=0.0.0.0:8080

rpclisten=localhost:10009

tlsextraip=127.0.0.1

color=#000000

listen=0.0.0.0:9735

bitcoind.rpchost=127.0.0.1

bitcoind.rpcuser=my user

bitcoind.rpcpass= mypassword

bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500

bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501

alias=myalias

**Comment by wpaulino** [comment]
It looks like node launcher is not formatting these options correctly. The config file should look something like:

```
[Application Options]
debuglevel=info
restlisten=0.0.0.0:8080
rpclisten=localhost:10009
tlsextraip=127.0.0.1
color=#000000
listen=0.0.0.0:9735
alias=myalias

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=my user
bitcoind.rpcpass= mypassword
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18500
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18501
```

**Comment by Kineticmb** [comment]
Thank you for your help, this is much appreciated.

Its now saying either bitcoin.active or litecoin.active must be set to 1 (True) but ive definitely got:
bitcoin.active=1 as per your previous message

**Comment by wpaulino** [comment]
Did you save the changes in the same config file or did you create a new one? You can specify the path of the config file to lnd through the `--configfile` flag, make sure to include the path within quotes.

**Comment by Kineticmb** [comment]
Thank you so much! It worked! I deleted the old and created a new file.

Really appreciate it.
