### ISSUE TITLE
High inbound bandwidth usage with neutrino enabled

### ISSUE THREAD

**Issue by AnotherDroog** [lightningnetwork/lnd#3482]
### Background

Unexpectedly high inbound bandwidth usage when neutrino is enabled. Depending on network conditions lnd is receiving more than 3GB in 30 minutes. High bandwidth links can easily consume more than 50MBit/s on the receive side.

### Your environment

* version of `lnd`

latest master `0.7.1-beta commit=v0.7.1-beta-213-gfb565bcd5d3c4f91622e96e91d2955338bbaa69b` with patch to enable neutrino on bitcoin mainnet

* which operating system (`uname -a` on *Nix)

reproducible on Debian 9 & 10, Alpine 3.10, MacOS 10.14.6

* version of `btcd`, `bitcoind`, or other backend

neutrino backend configuration:
```
[Neutrino]
neutrino.connect=mainnet1-btcd.zaphq.io
neutrino.connect=mainnet2-btcd.zaphq.io
neutrino.connect=btcd-mainnet.lightning.computer

[Bitcoin]
bitcoin.active=1
bitcoin.testnet=0
bitcoin.mainnet=1
bitcoin.node=neutrino
```
* any other relevant environment details

Occurs within Docker and outside as a bare binary

### Steps to reproduce

Enable neutrino in `config.go` ~L812 make all relevant tags and apply config as above

### Expected behaviour

Neutrino should not be using more bandwidth than a full archival node

### Actual behaviour

Neutrino consistently consumes a large amount of inbound bandwidth from a single btcd node over port 8333.

**Comment by Roasbeef** [comment]
When it downloads the channel graph, it needs to fetch all blocks that channels were included in, along with filters to fully verify the channels. If you wish to save bandwidth, then you can use `--routing.assumechanvalid`.

**Comment by AnotherDroog** [comment]
Thank you for the swift reply! @Roasbeef

Excuse the nitpick,
isn’t it a bit misleading, that `synced_to_chain = true` while it’s getting filters?

**Comment by Roasbeef** [comment]
It has all the filters it needs at that point. The filters it's fetching
are to verify legacy channels.
