### ISSUE TITLE
Unable to import lnd on Go 1.13

### ISSUE THREAD

**Issue by meeDamian** [lightningnetwork/lnd#3506]
### Background

Attempt to `go get` lnd using Go 1.13 fails with:

```
go get: github.com/lightningnetwork/lnd@v0.7.1-beta requires
	github.com/btcsuite/btcwallet@v0.0.0-20190712034938-7a3a3e82cbb6 requires
	github.com/lightninglabs/neutrino@v0.0.0-20190313035638-e1ad4c33fb18 requires
	github.com/btcsuite/btcwallet@v0.0.0-20190313032608-acf3b04b0273 requires
	github.com/lightninglabs/neutrino@v0.0.0-20190213031021-ae4583a89cfb requires
	github.com/btcsuite/btcwallet@v0.0.0-20180904010540-284e2e0e696e33d5be388f7f3d9a26db703e0c06: invalid pseudo-version: revision is longer than canonical (284e2e0e696e)
```

### Your environment

* version of `lnd`: same behaviour for the last 4 releases.
* which operating system (`uname -a` on *Nix): tested on MacOS, debian buster, and Alpine 3.8 through 3.10

A result of a minimal automated test case for multiple go/lnd combinations can be found here: https://github.com/meeDamian/go-get-lnd/commit/f931fd0425db481b0db4c1fc5917900b3c351000/checks

### Steps to reproduce

1. Have go 1.13
1. Run
	1. `go get github.com/lightningnetwork/lnd@v0.7.1-beta`, or
	1. Add `require github.com/lightningnetwork/lnd v0.7.1-beta` to `go.mod`, and try to build
	

### Expected behaviour

`go get` and `go build` complete successfully.

### Actual behaviour

This: https://github.com/meeDamian/go-get-lnd/runs/222083871#step:3:71

### Workaround

A temporary workaround I've found that works for me is adding the following to `go.mod`:

```
replace github.com/btcsuite/btcwallet => github.com/btcsuite/btcwallet v0.0.0-20190814023431-505acf51507f
```

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/3458.
