### ISSUE TITLE
GPG key used to sign releases & tags have expired

### ISSUE THREAD

**Issue by meeDamian** [lightningnetwork/lnd#3507]
### Background

The key hosted at https://keybase.io/roasbeef/pgp_keys.asc, and used to sign tags, and releases has expired on 2019-09-13.

### Steps to reproduce

```shell
$ curl https://keybase.io/roasbeef/pgp_keys.asc | gpg --import

$ cd lnd

$ git verify-tag v0.7.1-beta
OpenTimestamps: No timestamp found
gpg: Signature made Wed Jul 31 00:36:43 2019 +07
gpg:                using RSA key F8037E70C12C7A263C032508CE58F7F8E20FD9A2
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: BD59 9672 C804 AF27 7086  9A04 8B80 CD2B B8BD 8132
     Subkey fingerprint: F803 7E70 C12C 7A26 3C03  2508 CE58 F7F8 E20F D9A2

$ echo $?
1
```

### Expected behaviour

Git tag, and manifest signature verification succeeds. 

### Actual behaviour

Git tag, and manifest signature verification fails.

**Comment by Roasbeef** [comment]
Hey, yeah the key is expired. However, that doesn't mean that any of those past signatures are now invalid (even though it may show a warning of an expire key. I typically like to create signing keys with a 1 year expiry, and let them expire unless conditions insist that key be active for longer. If there's no dire reason, I'll likely just create a new key, again with a 1 yr expiry, and have the other developers sign off on it before our next release.

**Comment by meeDamian** [comment]
Why?  I'm not a gpg expert, but are there any downsides of just extending it, or having it not expire and using revoke key if needed later?

The problem is that the signature verification fails on automated systems, and AFAIK there's no easy way of preventing that w/o some insane hacks of changing system clock, or somehow parsing the output of gpg command.

**Comment by Roasbeef** [comment]
It's just my form of key hygiene. This is also something that's bound to happen unless a key has an unlimited life time, which IMO is undesirable.

**Comment by meeDamian** [comment]
A key can be extended at any point, even after expiration.

My question is: **What is the point of generating a new key, as opposed to extending the validity of the existing one?**

It causes needless verification fails of all previous signatures (non trivial to handle), forces everyone to download, and verify new key periodically (error prone - any key update error might leave people vulnerable).

**Comment by Roasbeef** [comment]
You can view it as a soft deadman's switch. It also allow me progressively upgrade the parameters of the key (bit length, rsa/ecdsa, etc) over time as more modern cryptography becomes available to yubikeys. If you check a historic key server, you'll see that all my other keys also expired after one year. The verification there isn't failing persay, it just warns that the key has expired. I'll have a new signing key up within the week signed by the other developers of `lnd`, I'll also start to timestamp each of the tags I sign as well as my commits using OTS.

**Comment by Roasbeef** [comment]
My new key:
  * https://keys.openpgp.org/vks/v1/by-fingerprint/BD599672C804AF2770869A048B80CD2BB8BD8132
  * https://keybase.io/roasbeef/pgp_keys.asc?fingerprint=9769140d255c759b1eb77b46a96387a57caae94d

**Comment by jonathancross** [comment]
> My new key:
> https://keys.openpgp.org/vks/v1/by-fingerprint/BD599672C804AF2770869A048B80CD2BB8BD8132

That is your old key ;-)
Here is the new one it seems: [9769 140D 255C 759B 1EB7  7B46 A963 87A5 7CAA E94D](https://keys.openpgp.org/vks/v1/by-fingerprint/9769140D255C759B1EB77B46A96387A57CAAE94D)

> It's just my form of key hygiene.

Unfortunately, letting a key expire means that all the sigs also expire and anyone who by luck managed to verify the key in person with you (like I did a couple years ago) is back to zero.  This makes it difficult to determine if a key is yours or that of an imposter (however unlikely that may be).

Please consider cross-signing new and old keys to establish some link we can rely on.

Thanks.

**Comment by setpill** [comment]
Please reopen; current release's manifest signature cannot be verified without ugly libfaketime hacks, which is not viable for packaging.

**Comment by setpill** [comment]
Nor the tag signature.

**Comment by dmp1ce** [comment]
@Roasbeef, Whether or not you extend the expiration, setting a one year expiration still acts as a soft dead mans switch. In both cases you need to take action.

If you only want to take advantage of the latest algorithms, perhaps you could rotate your `Sign` subkey instead of creating an entirely new keyring (primary secret).

**Comment by Roasbeef** [comment]
They can all still be verified (there're even other older releases with prior expired keys as well). What happens is that you receive a warning that the key is expired, just as you would if the key has no trust level from your PoV. 

> If you only want to take advantage of the latest algorithms, perhaps you could rotate your Sign subkey instead of creating an entirely new primary secret.

Too late. I'm also not in the positions geographically to do anything otherwise.

**Comment by meeDamian** [comment]
> They can all still be verified (there're even other older releases with prior expired keys as well). What happens is that you receive a warning that the key is expired, just as you would if the key has no trust level from your PoV.

@Roasbeef the issue it with automated checks, which treat this warning as an error, and fail.

**Comment by AnotherDroog** [comment]
I've also run into this. Faking system time is not a viable solution.

**Comment by setpill** [comment]
FWIW `gpg2` at least does not *error* on signatures from expired keys, simply outputs a warning. I was running into some packaging trouble earlier and misattributed it to the key expiration; what actually happened was that I whitelisted `F8037E70C12C7A263C032508CE58F7F8E20FD9A2` when I should have whitelisted `BD599672C804AF2770869A048B80CD2BB8BD8132`.

However, this is just about the AUR packaging of the prebuilt binaries; the AUR package that builds from source can only verify using `git verify-tag [tagname]` (the Makefile assumes a git environment, so building from the source tarball is not trivial; or if it is, I didn't find it in the documentation), which *does* error because of key expiration.

I cannot comment on any other packaging systems, but it is not strange to assume they might also run into trouble.

**Comment by meeDamian** [comment]
A _temporary_ hack around `verify-tag` that I've found is:

```shell
git verify-tag "${TAG}" || \
    { git verify-tag --raw "${TAG}" 2>&1 | grep EXPKEYSIG && echo "Accepting expired key!"; }
```

Although, I have no idea how safe the above is…

**Comment by jonathancross** [comment]
**FWIW:** I was able to meet @Roasbeef at LNConf and verify his key as:
```
9769 140D 255C 759B 1EB7  7B46 A963 87A5 7CAA E94D
```
I have signed this key and uploaded to keyservers:
http://keys2.kfwebs.net/pks/lookup?op=vindex&search=0xA96387A57CAAE94D&fingerprint=on

Unfortunately he is not interested in signing other keys, so this key will remain outside of the PGP Web Of Trust.

**Comment by Roasbeef** [comment]
> Given that, it seems like circumventing the official signature, and relying on multiple people building a release, and signing its hash might be the most sustainable way forward. Not quite clear on details yet.


Yep, we have plans to go in this direction, but baby steps first.
