### ISSUE TITLE
Support creation of custom macaroons

### ISSUE THREAD

**Issue by dannypaz** [lightningnetwork/lnd#3516]
### Background

`connectPeer` requires access to the admin macaroon, however if a user needs to make payments and is using neutrino, the best way to establish connections through peers is to use `connectPeer` and then they can open a channel to your node.

I want to be able to use the `connectPeer` API without requiring the admin macaroon and invoice macaroon seems like a good interim place to put this before custom macaroons is released.

**Comment by wpaulino** [comment]
> connectPeer requires access to the admin macaroon, however if a user needs to make payments and is using neutrino, the best way to establish connections through peers is to use connectPeer and then they can open a channel to your node.

I'd say that establishing a direct connection to your payment destination is not ideal and doesn't scale. Why does this only apply to Neutrino?

> I want to be able to use the connectPeer API without requiring the admin macaroon and invoice macaroon seems like a good interim place to put this before custom macaroons is released.

Mixing peer permissions with invoices for an invoice macaroon doesn't seem like a nice separation of concerns to me, which is what the macaroons attempt to achieve at the moment. Either a peer macaroon should exist, or you can create your own custom macaroon once that's supported.

**Comment by dannypaz** [comment]
> I'd say that establishing a direct connection to your payment destination is not ideal and doesn't scale. Why does this only apply to Neutrino?

Doesn't only apply to neutrino (we can think corporate firewall issues as an example), but neutrino is a good example. `ConnectPeer` is a way to guarantee that Node A is connected to Node B.

Peer macaroon would be perfect. Saying that `connectPeer` should be in an invoice macaroon would be a stretch.

Is there any timeline for support for custom macaroons? Would LL be up for reviewing a PR for a `peer` macaroon?

**Comment by Roasbeef** [comment]
I think we'd rather opt for a more generalized bakery vs adding new macaroons for specific use cases.

**Comment by dannypaz** [comment]
https://github.com/lightningnetwork/lnd/pull/1147

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/1160
