### ISSUE TITLE
Python gRPC: AttributeError: 'LightningStub' object has no attribute 'UnlockWallet'

### ISSUE THREAD

**Issue by s-tikhomirov** [lightningnetwork/lnd#3526]
### Background

I'm trying to connect to my LND from a Python script. As a first step, I'm following [these instructions](https://dev.lightning.community/guides/python-grpc/) to set everything up and then execute [this script](https://api.lightning.community/#simple-rpc-3) line by line.

### Your environment

* version of `lnd`: lnd version 0.6.1-beta commit=v0.6.1-beta-84-gaf3b04e53f7cc2198ac41a7b6590018a2b21a599
* which operating system (`uname -a` on *Nix): Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v0.18.0 (regtest)
* any other relevant environment details

### Steps to reproduce

Install the environment as described [here](https://dev.lightning.community/guides/python-grpc/), then:
```
$ python
Python 2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpc_pb2 as ln
>>> import rpc_pb2_grpc as lnrpc
>>> import grpc
>>> import os
>>> os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'
>>> cert = open(os.path.expanduser('~/.lnd/tls.cert'), 'rb').read()
>>> creds = grpc.ssl_channel_credentials(cert)
>>> channel = grpc.secure_channel('localhost:10009', creds)
>>> stub = lnrpc.LightningStub(channel)
>>> password = "12345678"
>>> b_password = password.encode()
>>> request = ln.UnlockWalletRequest(wallet_password=b_password)
>>> response = stub.UnlockWallet(request)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'LightningStub' object has no attribute 'UnlockWallet'
```

### Expected behaviour

Get some kind of "wallet unlocked" message.

### Actual behaviour

```
AttributeError: 'LightningStub' object has no attribute 'UnlockWallet'
```

**Comment by wpaulino** [comment]
`UnlockWallet` is part of the `WalletUnlocker` service, not `Lightning`. You should be creating a stub for that instead. The service is only available until the wallet is created/unlocked. It is not available if you're running lnd with `--noseedbackup`.

**Comment by s-tikhomirov** [comment]
Sorry, not sure I understand. Is the python-grpc documentation just out of date?

**Comment by wpaulino** [comment]
The guide might not be out of date, but it's assuming that the lnd node has been unlocked. You can unlock it through the CLI with `lncli unlock`.

**Comment by instagibbs** [comment]
I had the same exact issue and only found out I could `InitWallet` on `WalletUnlocker` based on @wpaulino comment above.

fwiw I think it's a bit much for users to figure this out on existing documentation alone.

There are 0 instances of `LightningStub` string outside of the documentation in `docs/grpc/python.md` and a mention of the `WalletUnlocker` service in `lnrpc/README.md` but it's up the the user to guess what the name of it is(f.e. not `WalletUnlockerStub`)

**Comment by instagibbs** [comment]
oh dear, I must have skimmed over the line a bunch of times, it indeed exists in the gRPC docs: https://api.lightning.community/?python#initwallet
