### ISSUE TITLE
closechannel not using --conf_target and --sat_per_byte as expected

### ISSUE THREAD

**Issue by maltokyo** [lightningnetwork/lnd#3528]
### Background

I am trying to close channels for as cheap as possible, just to see how to do it on my test server.

Closing channels in my case takes approx 5sat / vbyte even when setting `--sat_per_byte 1` or `--conf_target 60`

I know the difference between bytes and vbytes, I just want to find out how to get it to 1sat / vbyte.

Worst of all (see last example below) `--sat_per_byte 0` resulted in the largest fee out of all the tests!!  I was ready for it to be not confirmed, and realise I should pay fees, it was just a test...

### Your environment

* Latest version of BTCPay Server  with LND on Ubuntu 18.04 server

### Steps to reproduce

`lncli closechannel --sat_per_byte 1 --funding_txid ebfbdbb27449f456f3c86d745d0cca1950bedc4f05201556aa3da4d54dcfab17`

Result:
```
{
	"closing_txid": "957e42958f8783fe0a2e9ea6f8b14fc5b9890f5957d84f32e7b48260209d12ad"
}
```
**Fee = 5sats/vbyte**

And

`lncli closechannel --funding_txid a9b3f2c6a889b5a1bc45fe689d6e48e9bffd2b57e047adbe6f3b6e8fd726e9dd --conf_target 60`

Result:
```
{
	"closing_txid": "1c638b59170fe286dfd1267c1f94fe98b9b4e9e5ed3499ff27dc18f5fb4e4a4c"
}
```
**Fee = 5sats/vbyte**

And, just for another test, I tried **--sat_per_byte 0** - this resulted in the LARGEST fee, overpaying by nearly 500% of the current market rate to get into the next block(!!!!):

`lncli closechannel --funding_txid 63c8ae15d6f4d3f28157974a2b8fb925eb7034140317244495ad1b919f0d07ae --sat_per_byte 0`
```
{
	"closing_txid": "172dc9c911a020d3204c8e869bfc0f733ee3bab2c2f3687d27da0e2ba2bf37fa"
}
```

**Fee = 0.00002128 BTC (15.5 sat/vB)** 

### Expected behaviour

I wanted to wait longer and subsequently pay 1sat / vbyte

### Actual behaviour

These both took 5sat per byte and confirmed in the very next block.. 
How can I do the channel closures with 1sat/vbyte, or cheapest possible?

**Comment by wpaulino** [comment]
Closing channels cooperatively goes through a fee negotiation between both parties. The fee you provide is used as the starting point, but it may be raised by the remote party if it thinks it's too low.

> And, just for another test, I tried --sat_per_byte 0 - this resulted in the LARGEST fee, overpaying by nearly 500% of the current market rate to get into the next block(!!!!):

This is interpreted as no custom fee being provided, so it uses a default confirmation target of 6 blocks, which at that time corresponded to 15 sat/vbyte.

**Comment by Roasbeef** [comment]
>  So in this case
what’s the point of setting sats per byte if I have no say in it anyway?

You _do_ have a say in it, as both sides will progressively inch towards each other in order to satisfice on the final fee used for the closing transaction. However, if both sides disagree on what the the final fee should be (very diff fee estimation for example), then it's possible that you may end up paying a bit more. However, also note that the _initiator_ is the one that pays fees in channels atm.

**Comment by maltokyo** [comment]
Understood. Thank you. Where can I read about this in detail?
