### ISSUE TITLE
lncli restorechanbackup segfault on binary backup

### ISSUE THREAD

**Issue by yope** [lightningnetwork/lnd#3529]
### Background

This happened after dealing with a corrupted channel.db forced me to start over. Initially LND  had suddenly crashed with "Unable to start server: edge not found". After a trying to debug the issue I ended up just ignoring the DB error and was able to start and obtain a channel.backup file. After that I stopped LND, wiped the data directories and started from scratch recovering the wallet from the seed mnemonic, and trying to recover the channels from the channel.backup file.

### My environment

* version of `lnd`: 0.7.1-beta
* OS: `Linux imp 4.19.66-v7l+ #1253 SMP Thu Aug 15 12:02:08 BST 2019 armv7l GNU/Linux`
* bitcoind v0.18.1
* Running on a raspberry-pi 4 with 4GiB, initially installed via raspiblitz 1.3

### Steps to reproduce

1. Have a channel.backup file generated with `lncli  exportchanbackup --all --output_file channel.backup`
2. Initialize new lnd and start recovery of wallet from seed.
3. Before copying the new macaroons to the admin account (no idea if this is relevant, probably not, but bear with me): `lncli restorechanbackup channel.backup`

### Expected behaviour

I'd expect an error telling me the something in the lines of `[lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification`.
Or some other error message that the channel.backup is in the incorrect format (I forgot to specify the `--multi_file` option). Although ideally lncli should be smart enough to detect wich of the backup file formats I am feeding it.

### Actual behaviour
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e6268]

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0x37d1690)
        /Users/roasbeef/gocode/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:472 +0x224
panic(0x7c0d80, 0x10c9b80)
        /usr/local/go/src/runtime/panic.go:522 +0x1a0
main.restoreChanBackup(0x34c03c0, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/cmd/lncli/commands.go:4006 +0xe8
main.actionDecorator.func1(0x34c03c0, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/cmd/lncli/commands.go:70 +0x24
reflect.Value.call(0x772920, 0x340f6d8, 0x13, 0x882859, 0x4, 0x344d664, 0x1, 0x1, 0x340a600, 0xa0, ...)
        /usr/local/go/src/reflect/value.go:447 +0x3a4
reflect.Value.Call(0x772920, 0x340f6d8, 0x13, 0x344d664, 0x1, 0x1, 0x3427b3c, 0x8835f8, 0x88)
        /usr/local/go/src/reflect/value.go:308 +0x74
github.com/urfave/cli.HandleAction(0x772920, 0x340f6d8, 0x34c03c0, 0x0, 0x0)
        /Users/roasbeef/gocode/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:481 +0x1bc
github.com/urfave/cli.Command.Run(0x88ec02, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8b8cee, 0x41, 0x0, ...)
        /Users/roasbeef/gocode/pkg/mod/github.com/urfave/cli@v1.18.0/command.go:186 +0x6f8
github.com/urfave/cli.(*App).Run(0x34be750, 0x340a140, 0x3, 0x4, 0x0, 0x0)
        /Users/roasbeef/gocode/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:235 +0x474
main.main()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/cmd/lncli/main.go:310 +0xd98
```
After copying the relevant macaroons and specifying `--multi_file`, it seemed to work, although it took a few hours, presumably waiting for lnd to sync and complete wallet recovery.
I am aware that I committed two mistakes, but IMHO lncli shouldn't just crash in this case.
I am creating this issue anyway after advice from @alexbosworth, who assisted me via slack with ideas as to how to recover from the channel-db corruption.

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/3455. The fix will be included in the next release.
