### ISSUE TITLE
About a month after a power outage lnd crashes with "edge not found"

### ISSUE THREAD

**Issue by yope** [lightningnetwork/lnd#3530]
### Background

LND 0.7.1-beta running for almost a  year without problems (multiple updates in between of course). Recently upgraded hardware from rpi 3 to rpi4. Currently 4 channels, 3 almost permanently active. About a month ago it suffered a power outage. After restarting everything seemed fine.

### My environment

* version of `lnd`: 0.7.1-beta
* OS: `Linux imp 4.19.66-v7l+ #1253 SMP Thu Aug 15 12:02:08 BST 2019 armv7l GNU/Linux`
* bitcoind v0.18.1
* Initially installed from raspiblitz 1.3

### Steps to reproduce

Hard to know. The only thing that could play a role here is the power outage that happened about a month ago. Since then the node had been running seemingly fine though.

### Expected behavior

IMHO lnd is either too buggy/unstable still, or still has insufficient robustness to deal with db corruption caused by sudden power loss. Sudden power loss can always happen, and before lnd goes out of beta, IMHO these problems must be addressed.

### Actual behavior

Out of the blue, lnd just crashed, and wouldn't start again.
In the logs, I could find this message:

`2019-09-20 16:20:03.588 [ERR] LTND: Unable to start server: edge not found`

After some digging in the code, I found that the place where the crash happened was here:

```
channeldb/graph.go:
...
func fetchChanEdgeInfo(edgeIndex *bbolt.Bucket,
	chanID []byte) (ChannelEdgeInfo, error) {

	edgeInfoBytes := edgeIndex.Get(chanID)
	if edgeInfoBytes == nil {
>>		return ChannelEdgeInfo{}, ErrEdgeNotFound
	}

	edgeInfoReader := bytes.NewReader(edgeInfoBytes)
	return deserializeChanEdgeInfo(edgeInfoReader)
}
...
```

### How I recovered

I had a rather old channel.backup file. At least one new channel had been opened since, so I needed to create a newer version somehow.

At first I tried bbolt:

```
$ go run github.com/etcd-io/bbolt/cmd/bbolt check /mnt/hdd/lnd/data/graph/mainnet/channel.db
page 2562: multiple references
page 6584: multiple references
page 6145: multiple references
page 4907: multiple references
[...]
page 3629: unreachable unfreed
page 3630: unreachable unfreed
page 3670: unreachable unfreed
778 errors found
invalid value
exit status 1
```

```
$ go run github.com/etcd-io/bbolt/cmd/bbolt compact -o channel-compacted.db /mnt/hdd/lnd/data/graph/mainnet/channel.db
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x1c8822c, 0x500)
        /usr/local/go/src/runtime/sema.go:71 +0x2c
sync.(*Mutex).Lock(0x1c88228)
        /usr/local/go/src/sync/mutex.go:134 +0x224
go.etcd.io/bbolt.(*DB).Close(0x1c88140, 0x0, 0x0)
        /home/bitcoin/go/src/go.etcd.io/bbolt/db.go:473 +0x38
panic(0x11b1c0, 0x20e208)
        /usr/local/go/src/runtime/panic.go:522 +0x1a0
go.etcd.io/bbolt.(*Bucket).Sequence(...)
        /home/bitcoin/go/src/go.etcd.io/bbolt/bucket.go:338
main.(*CompactCommand).walkBucket.func1(0x9ed84050, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2114 +0xdc
go.etcd.io/bbolt.(*Bucket).ForEach(0x1e848a0, 0x1c37b68, 0x1, 0x1)
        /home/bitcoin/go/src/go.etcd.io/bbolt/bucket.go:388 +0xf8
main.(*CompactCommand).walkBucket(0x1c100c0, 0x1e848a0, 0x1c0c500, 0x1, 0x1, 0xa2b845a5, 0xa, 0xa, 0x0, 0x0, ...)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2111 +0x124
main.(*CompactCommand).walkBucket.func1(0xa2b845a5, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2114 +0x158
go.etcd.io/bbolt.(*Bucket).ForEach(0x1c0ab60, 0x1c37c40, 0x0, 0x0)
        /home/bitcoin/go/src/go.etcd.io/bbolt/bucket.go:388 +0xf8
main.(*CompactCommand).walkBucket(0x1c100c0, 0x1c0ab60, 0x0, 0x0, 0x0, 0x9f77239e, 0xa, 0xa, 0x0, 0x0, ...)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2111 +0x124
main.(*CompactCommand).walk.func1.1(0x9f77239e, 0xa, 0xa, 0x1c0ab60, 0x1c0ab60, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2093 +0x84
go.etcd.io/bbolt.(*Tx).ForEach.func1(0x9f77239e, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bitcoin/go/src/go.etcd.io/bbolt/tx.go:129 +0x70
go.etcd.io/bbolt.(*Bucket).ForEach(0x1c1238c, 0x1c37d08, 0x1c0e348, 0x0)
        /home/bitcoin/go/src/go.etcd.io/bbolt/bucket.go:388 +0xf8
go.etcd.io/bbolt.(*Tx).ForEach(0x1c12380, 0x1c7cd28, 0xd57a8, 0x4)
        /home/bitcoin/go/src/go.etcd.io/bbolt/tx.go:128 +0x58
main.(*CompactCommand).walk.func1(0x1c12380, 0x13de58, 0x1c12380)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2092 +0x54
go.etcd.io/bbolt.(*DB).View(0x1c88000, 0x1c7cd6c, 0x0, 0x0)
        /home/bitcoin/go/src/go.etcd.io/bbolt/db.go:725 +0x84
main.(*CompactCommand).walk(0x1c100c0, 0x1c88000, 0x1c0a420, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2091 +0x54
main.(*CompactCommand).compact(0x1c100c0, 0x1c88140, 0x1c88000, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:2021 +0x140
main.(*CompactCommand).Run(0x1c100c0, 0x1c10040, 0x3, 0x4, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:1996 +0x360
main.(*Main).Run(0x1c7cfac, 0x1c10038, 0x4, 0x5, 0x0, 0x14f01)
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:114 +0xc0c
main.main()
        /home/bitcoin/go/src/github.com/etcd-io/bbolt/cmd/bbolt/main.go:70 +0xa8
exit status 2
```

So this wasn't going to work.

Fortunately, after some excellent support and advice from @alexbosworth via slack, I patched the code to ignore the error, so lnd could start and I could make a newer channel.backup file.
Having that I started from a clean setup, recovered from the wallet seed and the channel.backup file.

**Comment by wpaulino** [comment]
We've addressed some issues that prevented `lnd` from cleanly shutting down in the past. Given that you have a somewhat old database, it's possible that it was corrupted before the fixes were in place. There's not much we can do on our side given that corruption already happened, so I'll close this assuming that you were able to recover your funds through your seed and channel backup. Feel free to re-open or open a new issue if you experience this with the new database.
