### ISSUE TITLE
Wallet balance available for funding channels non apparently witness specific

### ISSUE THREAD

**Issue by braydonf** [lightningnetwork/lnd#354]
A wallet without any witness outputs, but with a balance, will give `ErrInsufficientFunds`, when trying to open a channel. Looks like some faucets don't yet handle `p2wkh` addresses.

This may not be apparent without reading through the [coin selection code](https://github.com/lightningnetwork/lnd/blob/8a208ae3cd1556f9342e2795c137ccc834d127b9/lnwallet/wallet.go#L1286) and noticing use of `ListUnspentWitness`, otherwise it seems a bit odd that the balance would be displayed as zero when opening a channel.

Sending to a `p2wkh` internally provided a balance for funding channels, and ability to have a `channelbalance`.

**Comment by Roasbeef** [comment]
> A wallet without any witness outputs, but with a balance, will give ErrInsufficientFunds, when trying to open a channel.

Yep, we require that segwitty outputs be used as inputs to funding transactions, otherwise malleability is re-introduced. 


> Looks like some faucets don't yet handle p2wkh addresses.

For faucets, you can use the `np2wkh` address type which wraps a `p2wkh` script within a `p2sh` script.

**Comment by Roasbeef** [comment]
I agree that this could be better documented!
