### ISSUE TITLE
getchaninfo returns invalid last_update

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#3548]
### Background

When attempting to filter inactive channels, I used CLI with a small python script:

```python
import json
import sys
import time

limit_seconds = 2 * 30 * 24 * 60 * 60

now = time.time()

channel = json.load(sys.stdin)
if channel["last_update"] < (now - limit_seconds):
  print(channel["chan_point"].replace(":", " "))
```

The output of `lncli getchaninfo $CHANNEL` is passed to it. To my surprise the output contained a channel that was used pretty much daily.

### Your environment

* version of `lnd`: 0.7.1
* which operating system (`uname -a` on *Nix): `Linux REDACTED 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind 0.17.0.1`
* any other relevant environment details: Centos

### Steps to reproduce

* A channel opened from BLW directly to LND, used nearly daily
* BLW offline
* Run `lncli getchaninfo $CHANNEL | check_node.py`, check_node.py is the script above

### Expected behaviour

The output should be empty because the channel was used less than two months ago

### Actual behaviour

The output contains the channel

**Comment by wpaulino** [comment]
`last_update` does not report on the activity of a channel. It is the timestamp of the latest gossip update for that channel. Gossip updates can happen due to policy changes, or to ensure channels are not considered "zombies" if no updates have happened.

For your use case, it'd be better to take a look at the `ForwardingHistory` RPC.

**Comment by Kixunil** [comment]
OK, fair enough. It's missing documentation. Could it be documented better, please?

**Comment by halseth** [comment]
`last_update` is deprecated, so I wouldn't rely on it.

**Comment by Kixunil** [comment]
Even better, only needs "Deprecated, do not use" documentation :)
