### ISSUE TITLE
Channel acceptor should allow for custom rejection message

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#3552]
### Background

When dynamically rejecting an inbound channel, the connecting peer should receive an indication of why their request was rejected.

Examples of existing messages:

1. Minimum channel size not reached
2. Multiple channels not supported

### Steps to reproduce

1. Open a channel that will get dynamically rejected
2. Get generic rejection message

### Expected behaviour

Rejection message should carry a hint at the problem for debugging purposes

### Actual behaviour

Message cannot be customized so the receiver doesn't know why the channel was rejected

**Comment by Meshugah** [comment]
I'd like to work on this. What steps do I take to open a channel that will get dynamically rejected?

**Comment by Roasbeef** [comment]
@Meshugah you can use the current `ChannelAcceptor` call to programmatically reject channels.

**Comment by Jeiwan** [comment]
Looks like there were no progress on this issue, so I'll start working on it.
