### ISSUE TITLE
[Feature Request] enable contact book payment experience

### ISSUE THREAD

**Issue by ossel** [lightningnetwork/lnd#3555]
As a user I would like to manage a contact list in my wallet to have the following payment experience:

1) select contact
2) enter payment amount
3) click send

To add a new contact the user would scan the node pubkey of a friend and enter the name of the friend. The wallet would call LND to persist the new entry in his contact book.

Implementing the contact book inside LND would have the benefit that the data is available for all the connected devices of the user. 
I personally use a phone, desktop and browser wallet and managing my contacts for 3 or more different devices would not be a nice user experience.

If the contact book functionality would be implemented without LND for persistence, all 3 wallet providers would need to implement a common way of syncing the contact data using a service like Google Drive or Dropbox and the user would need to configure and grant 3 times a permission.

LND would need an additional endpoint like /contacts that supports GET, POST and DELETE requests:
```
{
    "contact_name": "My best friend",
    "contact_pub_key": "02788242941915ed5a101511b8dfeb6db81e0fcd7546f6a55ef4dedf590a7d7ff4",
    "contact_category": "Friends"
}
```

As far as I'm aware making invoiceless payments should be possible soon because of the "key send" proposal (https://github.com/lightningnetwork/lnd/pull/2455)

The ZAP wallet would be interested to experiment with such a contact list feature.

**Comment by bitcoinuser** [comment]
Great suggestion. In the past I suggested something like this to Breez lightning wallet, see my suggestion: https://github.com/breez/breezmobile/issues/104
