### ISSUE TITLE
`"synced_to_chain": false,` after upgrade to 0.7.1

### ISSUE THREAD

**Issue by Sosthene00** [lightningnetwork/lnd#3559]
### Background

`getinfo` returns `"synced_to_chain": false,`, even as block_heigth is exactly the same than bitcoind. 
I just realized something was wrong because LND seems to work ok otherwise. I upgraded to 0.7.1 about 3 weeks ago, and I suspect that's when things went wrong.
Besides LND eats up all CPU power (might be related to https://github.com/lightningnetwork/lnd/issues/3370 ?), but other than that it seems to work fine. 

### Your environment

* version of `lnd` 0.7.1-beta commit=basedon-v0.7.1-beta-dirty
* which operating system (`uname -a` on *Nix) 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend "/Satoshi:0.18.0/"
* any other relevant environment details Running inside the dockerized BTCPay Server ; pruned. 

### Steps to reproduce

Just run BTCPay server with LND activated (while I suspect things went wrong when I upgraded to 0.7.1 and a new installation won't actually have the same issue).

### Expected behaviour

LND should indicate `"synced_to_chain": true,`, and CPU usage is usually far lower than that.

### Actual behaviour

 LND seems to never catch up on the chain (but it actually did when you look at block_height) and LND will eventually start to consume up to 100% of CPU or even more.

**Comment by wpaulino** [comment]
Are you able to reproduce this reliably on restarts? Could you provide a CPU profile?

**Comment by Roasbeef** [comment]
I think you might have some old dormant channel that recently closed perhaps? If it's old enough, and beyond the prune horizon of your node, then `lnd` may not be able to automatically recover, as we don't support `bitcoind` in pruned mode.

**Comment by Sosthene00** [comment]
I restarted once again today and this time `"synced_to_chain": ` is `true` again, and CPU usage is back to normal.
I'll keep an eye on it to see if it stays this way, and close the issue for the moment.
Thanks!
