### ISSUE TITLE
Docker: Cannot bind to ipv4

### ISSUE THREAD

**Issue by varnav** [lightningnetwork/lnd#3570]
### Background

As ldn image in Docker hub was not updated for a long time, I took Dockerfile from repo and made some minor changes to make it work. Here it is:

https://github.com/varnav/lnd-node-docker

I run it with the command: `docker run -d --name lnd-testnet -v lnd-data:/root/.lnd -p 9735:9735 -p 10009:10009 --restart on-failure --security-opt no-new-privileges varnav/lnd-node --bitcoin.active --bitcoin.testnet --bitcoin.node=neutrino --neutrino.connect=faucet.lightning.community --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --tlsextraip=0.0.0.0`

Log shows this:

`2019-10-02 16:56:55.960 [INF] RPCS: RPC server listening on 0.0.0.0:10009`

But output of `lsof -i :9735 -i :10009 -i :8080` is:

> COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
> docker-pr 23543 root    4u  IPv6 1184846      0t0  TCP *:10009 (LISTEN)
> docker-pr 23556 root    4u  IPv6 1178219      0t0  TCP *:9735 (LISTEN)
> 

### Your environment

* 0.8.0-beta
* Ubuntu 18.04.3 LTS
* Docker 19.03.1

### Steps to reproduce

Run Docker and lsof commands above.

### Expected behaviour

Should bind to ipv4, not ipv6

### Actual behaviour

Binds to ipv6 only

**Comment by dannypaz** [comment]
This looks related to you @varnav https://stackoverflow.com/a/30006034

**Comment by Roasbeef** [comment]
Doesn't look like an `lnd` issue per that last comment.
