### ISSUE TITLE
Node not reachable

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#3581]
An LND node runs at `0268485a83e66c1bc2557053cc37c6d308d5430c7bf73e436af12a0feed98d2f46@51.159.21.209:9735` on Casa box, it has an incoming deeply buried public channel with Bitrefill yet no other LN node can find a route to it, more info here: https://explore.casa/nodes/0268485a83e66c1bc2557053cc37c6d308d5430c7bf73e436af12a0feed98d2f46

Moreover, all attempts to connect to that node fail despite `51.159.21.209` pinging well and node being online, @sinitcin (an owner) has even restarted it but to no effect.

A start command looks like this:

> lnd --rpclisten=localhost:10009 --listen=localhost:10011 --restlisten=localhost:8001 --datadir=data --logdir=log --bitcoin.active --bitcoin.mainnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=xxxxxxx --bitcoind.rpcpass=xxx --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333 --externalip=51.159.21.209 --alias=LUNU

lnd version 0.7.1-beta commit=v0.7.1-beta-294-gcd3c2b508ec45373602e3cdb9cd19ab7b224f94d

**Comment by molxyz** [comment]
> Moreover, all attempts to connect to that node fail despite `51.159.21.209` pinging well and node being online, @sinitcin (an owner) has even restarted it but to no effect.

Port 9735 is closed:  https://www.yougetsignal.com/tools/open-ports/
