### ISSUE TITLE
Documentation: How to use build tags, and what they do

### ISSUE THREAD

**Issue by kornpow** [lightningnetwork/lnd#3598]
### Background

The binaries are built with most of the build flags already set, but when building from source you must specify which tags are desired. This is an important step to building a usable binary from source.

These flags should be listed in the docs, with what their use is for the entire system, and whether or not excluding it would break the normal function of the system.

A section on what the experimental tag does, which is required for ``` --routing.assumechanvalid ``` would be useful too, since it seems that tag includes everything plus some.

Maybe for another Issue? Make a build tag, which is build everything?

**Comment by sako0938** [comment]
I may try and tackle this if I can, for reference, here is the tags I know about:
```make && make install tags="experimental autopilotrpc signrpc walletrpc chainrpc invoicesrpc routerrpc watchtowerrpc```

**Comment by sako0938** [comment]
Here is how to build the "go way" and also use the build tags.
GO111MODULE=on go install -v -tags experimental,autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,routerrpc,watchtowerrpc ./...

v0.8.1beta not being labelled properly has me paying a lot more attention to what I'm building!

**Comment by sako0938** [comment]
Notation for how go uses build tags, at top of file: `// +build {tag}`
`
find . -type f -print0 | xargs -0 grep "// +build routerrpc"
`
Getting close to providing a PR, not sure if I will have expertise enough to show whether a node would be functional with or without a given tag, but having the tags right in the docs will help.

**Comment by sako0938** [comment]
How to checkout a tagged commit: ```git checkout tags/v0.9.0-beta```

**Comment by sako0938** [comment]
Additional Tags: watchtowerrpc wtclientrpc
