### ISSUE TITLE
Force close = funds doomed in limbo

### ISSUE THREAD

**Issue by justin7942163** [lightningnetwork/lnd#3602]
### Background

I have around 500,000 sats stuck in limbo on a forever closing node + around 40,000 on another with the same issue due to a force close (by the other party I assume) after my hardware went down for 24 hours.

The channel has been "closing" for over a week now and the original funding tx was on the 28th of September.

Is there anything I can do or are my funds gone forever?

### Your environment

* LND 0.7.1
* Ubuntu Server
* Bitcoin Core RPC v0.18.0
* Running within docker environment of BTCPayServer and using ZapDesktop

### Steps to reproduce

I'm not sure how to 'reproduce' this issue, it's pretty straightforward, my channels were closed and my funds were thrown into limbo.

### Expected behaviour

Node should have closed and returned my committed sats to me.

### Actual behaviour

Sats have not been returned, stuck in limbo, all lightning wallet clients I've tried say that it is just "closing" nothing else I can do.

![Screenshot_1](https://user-images.githubusercontent.com/31229612/66796168-9a80cd80-ef52-11e9-81ad-4317836b476f.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/31229612/66796215-b8e6c900-ef52-11e9-851b-f67dd30dff2b.jpg)

**Comment by wpaulino** [comment]
Can you provide logs for both channels?

Looking at the chain, the channel [5e1d9292acfc7230fbe948ca732c7e66ccaad73ad4bd5406a181c8367f5461c4](https://blockstream.info/tx/5e1d9292acfc7230fbe948ca732c7e66ccaad73ad4bd5406a181c8367f5461c4?expand) has not been closed yet. The channel [fff0304be98a9f605b6e57fa9984b02d6c24e9aeedd0dfe1fa36d26813fd96cf](https://blockstream.info/tx/fff0304be98a9f605b6e57fa9984b02d6c24e9aeedd0dfe1fa36d26813fd96cf?expand) was closed successfully and the money was swept by both parties.

**Comment by justin7942163** [comment]
How do I provide the logs?

**Comment by wpaulino** [comment]
They should be in your docker instance at the path `~/.lnd/logs/bitcoin/mainnet/lnd.log`.

**Comment by justin7942163** [comment]
Thank you, I'll do it tomorrow afterwork. I have to sleep now. 

Please check back here in 18 hours when I should have the logs for you.

**Comment by wpaulino** [comment]
From the logs:

`2019-10-16 05:57:18.330 [INF] DISC: Update announcement for short_chan_id(659217694184833024), is premature: advertises height 599555, only height 599322 is known`

It looks like your bitcoind node may not be fully caught up with the chain.

**Comment by justin7942163** [comment]
My node is caught up? BTCPayServer says it's synched.

Should I download a different node like Windows Node Launcher, set that up and then connect my LND to that and hopefully should all be synced back up?

**Comment by molxyz** [comment]
> If this is my problem, will linking my lightning node to a full normal node work to helping recover my limbo funds?

In the past I've seen it worked for some people, doesn't hurt to try, and you will need to let lnd do the  rescan which will take a while if you have many txs.  If it doesn't work, you really need the BTCPay people to help you out.

**Comment by justin7942163** [comment]
Hey @molxyz  I got my funds back by contacting the owner of the node and asking them to force close the channel. Cheers.
