### ISSUE TITLE
HTLC stuck for no reason

### ISSUE THREAD

**Issue by fiatjaf** [lightningnetwork/lnd#3604]
I've sent payment from an Electrum private channel through a c-lightning node I control through `LNBIG-10`. I had sent many similar HTLCs to the same destination without an issue, but then this one got stuck.

The c-lightning node that routed the payment has the following to say about it:

```
  {                                                                                                                   
    "payment_hash": "40b6e979e4063f561662cd2a86ea6106856f1a4aadf533d1164de9e27981f4f4",                               
    "in_channel": "599419x1969x0",                                                                                    
    "out_channel": "567204x2215x0",                                                                                   
    "in_msatoshi": 432345,                                                                                            
    "in_msat": "432345msat",                                                                                          
    "out_msatoshi": 432345,                                                                                           
    "out_msat": "432345msat",                                                                                         
    "fee": 0,                                                                                                         
    "fee_msat": "0msat",                                                                                              
    "status": "offered",                                                                                              
    "received_time": 1571139281.492                                                                                   
  }       
```

I don't actually have access to the calculated route from Electrum, but LNBIG says the next hop would be `LNBIG-28` then `BOLTENING.club`.

The payment never reached the recipient (which is also under my control).

`LNBIG-10` has the pending HTLC at the incoming channel, but not at the outgoing channel:

```
{
            "active": true,
            "remote_pubkey": "02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d",
            "channel_point": "8f7f3ca9e3c8cc6a5fb4702648383dd36419a6e2dfdb192aeb3fa4620d0d92f4:0",
            "chan_id": "623647393466220544",
            "capacity": "10000000",
            "local_balance": "9258804",
            "remote_balance": "738293",
            "commit_fee": "2903",
            "commit_weight": "724",
            "fee_per_kw": "3412",
            "unsettled_balance": "432",
            "total_satoshis_sent": "4461020",
            "total_satoshis_received": "3722295",
            "num_updates": "1582",
            "pending_htlcs": [
                {
                    "incoming": true,
                    "amount": "432",
                    "hash_lock": "QLbpeeQGP1YWYs0qhuphBoVvGkqt9TPRFk3p4nmB9PQ=",
                    "expiration_height": 599670
                }
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "100000",
            "remote_chan_reserve_sat": "100000",
            "static_remote_key": false
        }
```

**Comment by fiatjaf** [comment]
Also, restarting my c-lightning node and inspecting the logs for `channel_update` messages gives me messages from a lot of channels, but not from the channel involved in this.

**Comment by Roasbeef** [comment]
Given that these are all remote nodes which aren't under your control. We don't have much to go off of here. If you can reproduce this in a constrained environment, then we'll be able to dig in more.

**Comment by LNBIG-COM** [comment]
What i see there:

Payment from @fiatjaf -> lnd-10 -> lnd-28 -> BOLTENING.club
If BOLTENING.club under control @fiatjaf we have chances to catch bug if he is there

lnd-10 about channel `fiatjaf -> lnd-10`:

```

{
            "active": true,
            "remote_pubkey": "02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d",
            "channel_point": "8f7f3ca9e3c8cc6a5fb4702648383dd36419a6e2dfdb192aeb3fa4620d0d92f4:0",
            "chan_id": "623647393466220544",
            "capacity": "10000000",
            "local_balance": "9258804",
            "remote_balance": "738293",
            "commit_fee": "2903",
            "commit_weight": "724",
            "fee_per_kw": "3412",
            "unsettled_balance": "432",
            "total_satoshis_sent": "4461020",
            "total_satoshis_received": "3722295",
            "num_updates": "1582",
            "pending_htlcs": [
                {
                    "incoming": true,
                    "amount": "432",
                    "hash_lock": "QLbpeeQGP1YWYs0qhuphBoVvGkqt9TPRFk3p4nmB9PQ=",
                    "expiration_height": 599670
                }
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "100000",
            "remote_chan_reserve_sat": "100000",
            "static_remote_key": false
        },
```

The lnd-10 has in forwarding payments:

```
        {
            "timestamp": "1571139264",
            "chan_id_in": "623647393466220544",
            "chan_id_out": "623649592406507520",
            "amt_in": "433",
            "amt_out": "433",
            "fee": "0",
            "fee_msat": "0"
        }
```

The channel between `lnd-10` and `lnd-28` at `lnd-10` side:

```
{
            "active": true,
            "remote_pubkey": "030995c0c0217d763c2274aa6ed69a0bb85fa2f7d118f93631550f3b6219a577f5",
            "channel_point": "85eaa841fb9f2f6a21dc3ce40b80cb59ae9874bccff28c539b101d50ba2a8a79:0",
            "chan_id": "623649592406507520",
            "capacity": "5000000",
            "local_balance": "1584288",
            "remote_balance": "3413241",
            "commit_fee": "2471",
            "commit_weight": "724",
            "fee_per_kw": "3412",
            "unsettled_balance": "0",
            "total_satoshis_sent": "574713",
            "total_satoshis_received": "2159002",
            "num_updates": "1080",
            "pending_htlcs": [
            ],
            "csv_delay": 600,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "50000",
            "remote_chan_reserve_sat": "50000",
            "static_remote_key": false
        },
```

The forwarded payment at `lnd-28`:

```
{
            "timestamp": "1571139264",
            "chan_id_in": "623649592406507520",
            "chan_id_out": "623792528936075264",
            "amt_in": "433",
            "amt_out": "432",
            "fee": "0",
            "fee_msat": "346"
        }
```


Then the channel between `lnd-28` and `BOLTENING.club`:

```
"active": true,
            "remote_pubkey": "02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8",
            "channel_point": "9949519a3c344ac7ca544563300597a4d1abe0254784500b4cff4c4ff885e31c:0",
            "chan_id": "623792528936075264",
            "capacity": "5000000",
            "local_balance": "4946801",
            "remote_balance": "50728",
            "commit_fee": "2471",
            "commit_weight": "724",
            "fee_per_kw": "3412",
            "unsettled_balance": "0",
            "total_satoshis_sent": "511942",
            "total_satoshis_received": "461214",
            "num_updates": "949",
            "pending_htlcs": [
            ],
            "csv_delay": 600,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "50000",
            "remote_chan_reserve_sat": "50000",
            "static_remote_key": false
        },
```

@Roasbeef , i have question because i don't know lightning protocol details but if the payment left `lnd-10` and was forwarded to `lnd-28` and then to `BOLTENING.club` - does this mean that both (lnd-10 & lnd-28) received a preimage from the recipient?

And tomorrow if to need i can setup loglevel for submodules of LND and to log events about this payment. But i don't know what a submodule should i use and loglevel to catch bug.

**Comment by fiatjaf** [comment]
My c-lightning node also has also has this output from the channel involved:

```
        "htlcs": [
          {
            "direction": "in",
            "id": 11,
            "msatoshi": 432345,
            "amount_msat": "432345msat",
            "expiry": 599684,
            "payment_hash": "40b6e979e4063f561662cd2a86ea6106856f1a4aadf533d1164de9e27981f4f4",
            "state": "RCVD_ADD_ACK_REVOCATION",
            "local_trimmed": true
          }
        ]
```

**Comment by fiatjaf** [comment]
`BOLTENING.club` is not under my control.

**Comment by fiatjaf** [comment]
I know this is probably impossible to debug, but it's our duty to report it anyway.

**Comment by KarolStrzelec** [comment]
hi what do you think about this solution?
https://drive.google.com/file/d/1H0SLt2ntS2yqjJ7lkeisFhyHLIFH070D/view?usp=sharing

**Comment by fiatjaf** [comment]
> hi what do you think about this solution?
> https://drive.google.com/file/d/1H0SLt2ntS2yqjJ7lkeisFhyHLIFH070D/view?usp=sharing

It's not relevant to this issue. I don't understand the ratings thing, but it can't work because normally phones can't open channels with other phones. Also Bisq isn't supposed to be doing anything really related to LN. Very confusing.

**Comment by cfromknecht** [comment]
@fiatjaf that user spammed a bunch of issues with an irrelevant link, please ignore.

As far as the issue, I'm still digging into these logs to figure out what's going on. @LNBIG-COM is that HTLC still pending? Block 599670 passed a while ago, it should have been canceled. Have you restated since that block?

**Comment by KarolStrzelec** [comment]
> It's not relevant to this issue. I don't understand the ratings thing, but it can't work because normally phones can't open channels with other phones. Also Bisq isn't supposed to be doing anything really related to LN. Very confusing.

I'm sorry guys, I thought it was quite simple:
Acinq has made a new standard for wallets that can accept funds in LN without open channels in the non-custodial version. At the last LN conference there was very little talk about this topic, but instead of delegating the opening of channels they want to create a "bank" to entrust them with funds for this purpose.

Hey, I really want to help. We are currently able to use Bisq technology to coordinate autopilots in neutrino wallets. In this technology, each mobile protfel can be a private hub. We don't need millions of lines of code, just use the very simple mechanism described in the picture, assuming that thanks to neutrinos, every wallet mobile is a private hub.

I do not want to disturb, I am working on commercial use of LN in business, do what you want.

**Comment by fiatjaf** [comment]
The HTLCs are not pending anymore, the channel between my node and LNBIG was closed.

**Comment by cfromknecht** [comment]
@KarolStrzelec please make a new issue at the very least, this has nothing to do the issue at hand, or any of the other issues that were spammed for that matter.

> The HTLCs are not pending anymore, the channel between my node and LNBIG was closed.

Okay that's what I would have expected. Gonna be tough to debug now that we can't inspect further, unless we are able to dig up some logs from the incident. I'll keep this in mind and see if I can come up with a rationale explanation

**Comment by fiatjaf** [comment]
Yes, I think we can even close this issue. Maybe a future event can shed light into this and vice-versa and the failure can be spotted, but for now this issue has accomplished its job.

**Comment by cfromknecht** [comment]
I think so, if it resurfaces we can reopen. Thank you @fiatjaf and @LNBIG-COM for the detailed reports, very much appreciated :)

**Comment by BOLTENINGclub** [comment]
I'm running `BOLTENING.club`
Unfortunately I just saw this issue and my logs have been rotated since, so I don't think I can help.
