### ISSUE TITLE
Unable to settle invoice created via addholdinvoice

### ISSUE THREAD

**Issue by chill117** [lightningnetwork/lnd#3605]
### Background

Unable to settle an invoice created via `addholdinvoice`.

### Your environment

* `lnd version 0.7.1-beta commit=v0.7.1-beta`
* `4.15.0-50-generic Ubuntu x86_64 Linux`
* bitcoind - `Bitcoin Core Daemon version v0.17.1`
* bitcoin testnet

### Steps to reproduce

Generate secret and hash using the following node.js script:
```js
const crypto = require('crypto');
const secret = crypto.randomBytes(32).toString('hex');
const hash = crypto.createHash('sha256').update(secret).digest('hex');
console.log({secret, hash});
```

Sample output:
```json
{
  "secret": "2d2cd0ca5c4c49e12f972ff090be63b989f1b605d9d6c1efc73488511f172383",
  "hash": "c8e0a9c20bcbab325ccae5ae23a73d4c44687e00f4e44f6662d5a1fa63b017b0"
}
```

Create a hold invoice via bash command (providing the hash):
```bash
lncli --network=testnet addholdinvoice --memo="test hodl invoice" c8e0a9c20bcbab325ccae5ae23a73d4c44687e00f4e44f6662d5a1fa63b017b0
```

Initiate payment from the payer's node.

The invoice can be found via `lookupinvoice`:
```bash
lncli --network=testnet lookupinvoice c8e0a9c20bcbab325ccae5ae23a73d4c44687e00f4e44f6662d5a1fa63b017b0
```
The state is "accepted".

Finally try to settle the invoice from the payee's node:
```bash
lncli --network=testnet settleinvoice 2d2cd0ca5c4c49e12f972ff090be63b989f1b605d9d6c1efc73488511f172383
```

The following error occurs:
```
[lncli] rpc error: code = Unknown desc = unable to locate invoice
```

### Expected behaviour

The invoice should be settled.

### Actual behaviour

An error occurs and the invoice remains in the "accepted" state.

Canceling the invoice works:
```bash
lncli --network=testnet cancelinvoice c8e0a9c20bcbab325ccae5ae23a73d4c44687e00f4e44f6662d5a1fa63b017b0
```

**Comment by joostjager** [comment]
This error is expected if the secret doesn't hash to the payment hash.

**Comment by chill117** [comment]
I have discovered the problem: I was hashing the hex-encoded string value of the secret instead of the byte array. For example:
```js
const crypto = require('crypto');
const secret = crypto.randomBytes(32);
const hash = crypto.createHash('sha256').update(secret).digest('hex');
const wrongHash = crypto.createHash('sha256').update(secret.toString('hex')).digest('hex');
console.log({
	secret: secret.toString('hex'),
	hash,
	wrongHash,
});
```
In the above code, the values of `hash` and `wrongHash` are different. I tried the whole flow again but with the correct `hash` and now I am able to settle the invoice as expected.

**Comment by joostjager** [comment]
Cool. Closing then.
