### ISSUE TITLE
v0.8.0-rc3 build error: Checksum mismatch for btcd

### ISSUE THREAD

**Issue by ohenrik** [lightningnetwork/lnd#3607]
### Background

I'm trying to build v0.8.0-rc3 with this command:

`make && make install tags="signrpc walletrpc chainrpc invoicesrpc routerrpc watchtowerrpc"`

however i get this error message:

```
go: downloading github.com/btcsuite/btcd v0.20.0-beta
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
	downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
	go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.8.0-beta-rc3" github.com/lightningnetwork/lnd/cmd/lnd
go: downloading github.com/btcsuite/btcd v0.20.0-beta
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
	downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
	go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
make: *** [Makefile:92: build] Error 1
```
I am able to build the v0.8.0-rc2 version successfully. Are any one else experiencing this?

### Your environment

* version of `lnd`: v0.8.0-rc3
* which operating system: `Linux raspibolt 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: btcd v0.20.0-beta

**Comment by ohenrik** [comment]
go version go1.12.4 linux/amd64

Maybe this is related to the new modules in 1.13?

**Comment by cfromknecht** [comment]
can you try with either 1.12.9 or go1.13.1?

**Comment by ohenrik** [comment]
I can try this on Friday. Currently i got it working with rc2 and do not have time to mess up my node now before a demonstration tomorrow :p I'll get back to this on friday.

**Comment by nolim1t** [comment]
I get this issue build 0.18.1 as well

```
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
	downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
	go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
```g

**Comment by gustavonalle** [comment]
I have ```go version go1.12.9 linux/amd64``` and having the same issue

**Comment by gustavonalle** [comment]
Also tried building the tag ```commit 73ceb9a06eb19e727a9e6cf140bda8924df977eb (HEAD, tag: v0.8.0-beta)```, same error.
How did you guys release if it can't build?  🤔

**Comment by sergioabril** [comment]
I'm having the same error: checksum mismatch for btcd. Also, can confirm I didn't have it with rc2 (I have double checked).

I'm building a Docker container for testing with golang:1.12-alpine as builder

**Comment by molxyz** [comment]
@gustavonalle  Try `go clean -modcache`. Also, make sure all older Go versions have been purged from your system.

@sergioabril  You need go1.13.1.  Make sure to delete all older go versions in your system or the problem won't be solved.  There're important changes in RC3 which is the final version, so forget RC2. and you should get the final version which has been released and named `v0.8.0-beta`

**Comment by sergioabril** [comment]
@molxyz yep, can confirm that building Docker image with `golang:1.13.1-alpine` did the trick.

Running `v.0.8.0-beta `

**Comment by Roasbeef** [comment]
You need go 1.13.1 as mentioned in the release notes.

**Comment by anilCSE** [comment]
Same issue on go 1.13.3

**Comment by halseth** [comment]
@anilCSE Try using `lnd v0.8.1-beta`
