### ISSUE TITLE
Enable domain to my REST API URL

### ISSUE THREAD

**Issue by harizzubir** [lightningnetwork/lnd#3617]
this is my php curl option:
my url is https://123.123.123.123:5598 (ssl using self signed)
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

after enable domain to my API url, i keep getting null result when curl to the url.

Assist me

**Comment by guggero** [comment]
Can you please set
```
curl_setupt($ch, CURLOPT_VERBOSE, true);
```
And post the output of the PHP error log?
My guess is that you are missing the macaroon and you are getting an error because of that.

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3617#issuecomment-544853590

Please reopen if problem persists.
