### ISSUE TITLE
provide feedback about wallet restoring progress

### ISSUE THREAD

**Issue by ottosuess** [lightningnetwork/lnd#3619]
### Background

Restoring an older wallet takes a long time right now.

@mandelmonkey posted this on lnd slack:
> I just tried mainnet with a passphrase made about 4 months ago and one made just now, the one made 4 months ago is taking around 30mins the one made now in a just a couple of mins to recover

Right now there is no way to know if restoring is completed or how long it might still take.

This is pretty bad for UX on mobile devices where lnd is only running when the app is in foreground. Users will init their wallet with their `cipher_seed_mnemonic`, wait until the wallet is `synced_to_chain` and wonder why their old on chain funds don't show up. Would be great to have some sort of feedback I could show to users.

Is it possible to add something similar to `synced_to_chain` & `best_header_timestamp` for wallet restoring to the getInfo response?

**Comment by mandelmonkey** [comment]
Indeed many users feel the app has stalled and just close it, seems recovery progress is shown in the logs so would be great to have this also shown in getinfo or a separate endpoint

**Comment by yyforyongyu** [comment]
i'm working on this one
