### ISSUE TITLE
Sweep tx is not reflected in wallet balance.

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#3620]
### Background
A channel was forced closed and the other side have managed to broadcast the sweep transaction, which is also confirmed on chain. The issue is that the wallet balance is zero and the 'listchaintxns' shows empty list.

**Funding tx:** https://blockstream.info/tx/bf973531b59ef39a517d1e86c941e3e5b2b3ab22821a332848e9ff2013c3e9e1?output:1

**Closing tx**
https://blockstream.info/tx/b508ca1e227de1970a25e2bf13c585991c86c3d48b06bc47acbef440496eb8e2

**Other side sweep tx**
https://blockstream.info/tx/389df9de60d04e3f9452bf292abc4fb60e530d76583ea58692d3776ad3b83283

I see these lines in the log:

_--- Creating sweep transaction for 1 inputs (0 CSV, 0 CLTV) using 12500 sat/kw
--- Inserting unconfirmed transaction 389df9de60d04e3f9452bf292abc4fb60e530d76583ea58692d3776ad3b83283
--- No peers replied to inv message for transaction 389df9de60d04e3f9452bf292abc4fb60e530d76583ea58692d3776ad3b83283_

So the transaction is clearly broadcasted ( and should have been added to the wallet relevant txs and also the address should be watched).
After this the wallet was restarted and I see attempts to rebroadcast the same transaction (probably because no reply was received from previous broadcast) with conflict failure:

_--- Received reject (cmd tx, code REJECT_INSUFFICIENTFEE, reason replacement transaction f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73 has an insufficient fee rate: needs more than 49881, has 49881, hash f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73) from [2607:7700:0:1d:0:1:5e17:9aab]:8333 (outbound)
--- All peers rejected transaction f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73 checking errors
--- Broadcast attempt failed: rejected by [2607:7700:0:1d:0:1:5e17:9aab]:8333: replacement transaction f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73 has an insufficient fee rate: needs more than 49881, has 49881
--- Sending inv (witness tx f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73) to [2607:7700:0:1d:0:1:5e17:9aab]:8333 (outbound)
--- Removed invalid transaction_

It seems that the re-broadcast failed because the original transaction already existed in the mempool  and this one couldn't replace it without raising the fee (https://github.com/btcsuite/btcd/blob/e3d3088b80acb3d7943d38c495525d013a564892/mempool/mempool.go#L899). I also think this has caused removal of the transaction from the wallet which explains why it doesn't exist in the output of 'listchaintxns'.
What I don't yet understand is why the confirmation wasn't detected by the wallet as the address was generated by the wallet and therefore should have been added to the watch list.

To eliminate the case where a spent notification was missed (there were some issues at this area in the past) I have run manual rescan using this tool https://github.com/btcsuite/btcwallet/tree/master/cmd/dropwtxmgr but still the same results and the sweep utxo wasn't detected. No change to the wallet balance.

### Your environment

lnd version 0.7.1 using neutrino and btcd backend.
running on iOS mobile.

### Expected behaviour

The wallet balance and the listchaintxns output should be correct to include the sweep transaction.

### Actual behaviour

wallet balance is zero and no transaction in listchaintxns output.

**Comment by wpaulino** [comment]
Removing the transaction `f752aae46aca5a42c0950f9e956e3b221f929c7048a33a8b6592b40bdcffaa73` should not have caused the proper one `389df9de60d04e3f9452bf292abc4fb60e530d76583ea58692d3776ad3b83283` to be removed, but it looks like that was the case here. Are there any other instances in the logs of removing invalid transactions?

The recovery should've definitely picked it up, could you try again and increase the LNWL log level to trace?

**Comment by roeierez** [comment]
@wpaulino there is another one entry for removal of a transaction which seems to be the same case of retrying while the original is still in the mempool:

> _---Received reject (cmd tx, code REJECT_INSUFFICIENTFEE, reason replacement transaction 07a253b078b9844a109b86c491cf3062fbe264ca1fe6a9615727cb1b9815843a has an insufficient fee rate: needs more than 49881, has 49881, hash 07a253b078b9844a109b86c491cf3062fbe264ca1fe6a9615727cb1b9815843a) from 94.23.154.171:8333 (outbound)
> ---All peers rejected transaction 07a253b078b9844a109b86c491cf3062fbe264ca1fe6a9615727cb1b9815843a checking errors
> ---Broadcast attempt failed: rejected by 94.23.154.171:8333: replacement transaction 07a253b078b9844a109b86c491cf3062fbe264ca1fe6a9615727cb1b9815843a has an insufficient fee rate: needs more than 49881, has 49881
> 2019-10-18 23:39:40.614 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0x4000b703c0)({_
> 

This case happened on one of the mobile users. I will work with him to run the recovery on his mobile in trace mode and get back with the logs.

**Comment by roeierez** [comment]
@wpaulino attached is the log file for the last run after running the recovery tool. I also set the BTCN log level to DEBUG so we can see that the filter for the sweep tx confirmation block was fetched.
[lnd.log](https://github.com/lightningnetwork/lnd/files/3757096/recovery-info.log)

**Comment by roeierez** [comment]
@wpaulino I am working with the user to get the walletdb and channeldb files, will inspect them first to observe the current state and try to understand what happened.
Will come back when I have results to share.

**Comment by roeierez** [comment]
@wpaulino it turns out I used and old wallet.db, recovery with seed solved it. Thanks and closing this issue.
