### ISSUE TITLE
"Channel from self node has no policy" while updating channel policy

### ISSUE THREAD

**Issue by joaodealmeida** [lightningnetwork/lnd#3629]
### Background

Error when trying to update channel policies

### Your environment

* version of `lnd`- `0.7.1-beta commit=v0.7.1-beta`
* which operating system (`uname -a` on *Nix) - `Linux ip-172-31-4-119 4.4.0-1090-aws #101-Ubuntu SMP Fri Aug 2 15:21:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend - `Bitcoin Core 0.17.1`
* any other relevant environment details

### Steps to reproduce

lncli updatechanpolicy --base_fee_msat=x --fee_rate=x --time_lock_delta=x --chan_point=x

### Expected behaviour

Update channel policy accordingly

### Actual behaviour

I get an rpc error.

`[lncli] rpc error: code = Unknown desc = Channel from self node has no policy`

**Comment by wpaulino** [comment]
Have you restored any channels on this node? Could be related to https://github.com/lightningnetwork/lnd/issues/2911 in that case.

Otherwise, could you pinpoint the affected channels by calling `describegraph`, filtering for your own channels, and seeing which ones don't have a policy for your side?

**Comment by joaodealmeida** [comment]
I have not restored any channels.

That error appears when trying to update my channel policy individually as well (for all channels)

`alias lnupdatechan='lncli listchannels | jq -r '''.channels[].channel_point' | while read p; do lncli updatechanpolicy --base_fee_msat=x --fee_rate=x --time_lock_delta=x --chan_point="$p"; done'''`

**Comment by joostjager** [comment]
@joaodealmeida have you sorted this out in the mean time?

**Comment by joaodealmeida** [comment]
I believe I found the issue, just had not time to look at it more close...

Basically I pending close channel that was affected by the CVE, that's why it is stuck (fortunately no sats moved over the channel).

I basically need to compile LND with the dev tag and abandon the channel. I'll report back if the problem still persists.

**Comment by joostjager** [comment]
Ok, closing for now

**Comment by tdickman** [comment]
We are running into this same issue on v0.8.0. We have a pending close channel that was affected by the CVE (same as @joaodealmeida -> no sats moved over the channel).

I compiled LND with the dev tag, and abandoned the channel, but I'm still running into issues when running the following 2 commands:

```
$ lncli updatechanpolicy 0 0.0015 144
[lncli] rpc error: code = Unknown desc = Channel from self node has no policy
```

```
$ lncli feereport
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel XXXXXXXXXXXXXXXX
```

**Comment by wpaulino** [comment]
@tdickman see https://github.com/lightningnetwork/lnd/issues/3716, we'll track things there.
