### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by thisconnect** [lightningnetwork/lnd#363]
hi
simialar to lnd, ipfs is written in go and they distribute a binary, for various platforms

https://www.npmjs.com/package/go-ipfs-dep
https://www.npmjs.com/package/go-ipfs

this could help zap-desktop electron client https://github.com/LN-Zap/zap-desktop/pull/51

**Comment by joaodealmeida** [comment]
Thanks for bring this issue @thisconnect .
This would be really nice! Is it on your roadmap ?

**Comment by Roasbeef** [comment]
We don't currently have any plans to publish to npm. Instead, we recommend manually packaging the binary, or modifying your application to bundle the latest version. Once we start doing stable releases, it'll be less of a hassle to stay up to date with the latest version of `lnd`.
