### ISSUE TITLE
assumechanvalid not properly documented, not the default 

### ISSUE THREAD

**Issue by Sjors** [lightningnetwork/lnd#3630]
While testing the Bitcoin Core BIP157 PR https://github.com/bitcoin/bitcoin/pull/16442?ref=tokendaily#issuecomment-545402053 against a locally running Lnd instance, connected via p2p, I noticed that Lnd is fetching gigabytes of `cfilter` messages every minute. I added more details about my setup in the above issue.

bitcoind log is full of:
```
2019-10-23T11:44:07Z sending cfilter (16019 bytes) peer=2
```

After just a few minutes:

```
bitcoin-cli getpeerinfo

    "bytessent_per_msg": {
      "addr": 30082,
      "block": 91411051,
      "cfcheckpt": 19260,
      "cfilter": 9556773757,
      "feefilter": 32,
      "headers": 25,
      "ping": 128,
      "pong": 96,
      "sendheaders": 24,
      "verack": 24,
      "version": 127
    },
```

Meanwhile Lnd says:
```
2019-10-23 13:42:56.133 [INF] CRTR: Processed channels=18 updates=31 nodes=12 in last 1m0.003837556s
2019-10-23 13:43:56.134 [INF] CRTR: Processed channels=1 updates=1 nodes=0 in last 59.999969136s
2019-10-23 13:44:56.132 [INF] CRTR: Processed channels=19 updates=35 nodes=8 in last 59.996564919s
2019-10-23 13:45:56.135 [INF] CRTR: Processed channels=1 updates=1 nodes=0 in last 1m0.002229493s
2019-10-23 13:46:56.133 [INF] CRTR: Processed channels=19 updates=31 nodes=11 in last 59.996528948s
````

**Comment by wpaulino** [comment]
That's because it's attempting to verify channels are still valid, i.e. unspent, so it scans the chain from their confirmation heights to the latest height in the chain.

**Comment by Sjors** [comment]
It should probably cache the filters; that kind of bandwidth use is not healthy in general, and really problematic on mobile.

**Comment by wpaulino** [comment]
The filters are cached, but performing long linear scans doesn't go well with that unless we aggregate rescans over multiple channels, which I believe is not the case at the moment.

The real fix here is to have SPV channel proofs, which we plan to propose to the spec soon.

**Comment by Sjors** [comment]
If the filters are cached, why does it fetch more than 15 GB of them from my node in a few minutes?

**Comment by wpaulino** [comment]
They get evicted as other filters get cached instead.

**Comment by Sjors** [comment]
Maybe it's better to, for a given cache size, evict the oldest filters. You can then only verify gossip down to that age.

**Comment by Roasbeef** [comment]
You're meant to run with `--assumechanvalid` until SPV proofs have landed. Caching doesn't help otherwise, as it never needs to backtrack other than when re-scanning.

**Comment by Sjors** [comment]
I see Zap mobile added that [a few months ago](https://github.com/LN-Zap/zap-iOS/commit/9eccb474b6cd376d4962ca63e5fe2578271c66c5) and the Lightning Labs app [uses it too](https://github.com/lightninglabs/lightning-app/search?q=assumechanvalid&unscoped_q=assumechanvalid).

The option could use a bit more documentation than just: https://github.com/lightningnetwork/lnd/blob/master/mobile/sample_lnd.conf#L9
Maybe it should also be a default when `bitcoin.node=neutrino`.

**Comment by Roasbeef** [comment]
We don't default it for desktop, as it means that much of the information in `DescribeGraph` won't be populated. However, I agree we could document it better (fwiw, it was only just enabled in the past release which is a week or two old).

**Comment by Roasbeef** [comment]
Will keep open till we update the docs.

**Comment by Roasbeef** [comment]
This no longer requires a build tag now as of #4701
