### ISSUE TITLE
gRPC decodePayReq don't work 

### ISSUE THREAD

**Issue by Victorlerner** [lightningnetwork/lnd#3637]
### Background

Describe your issue here.
Hi, why this code doesn't work? it's node js
```
const grpc = require('grpc');
const fs = require('fs');
const protoLoader = require('@grpc/proto-loader');
const packageDefinition = protoLoader.loadSync(`${__dirname}/rpc.proto`, {
    enums: String,
    longs: String,
    arrays: true,
});
const proto = grpc.loadPackageDefinition(packageDefinition).lnrpc;
var lndCert = fs.readFileSync('tls.cert');
var sslCreds = grpc.credentials.createSsl(lndCert);
var macaroonCreds = grpc.credentials.createFromMetadataGenerator(function (args, callback) {
    var macaroon = fs.readFileSync("admin.macaroon").toString('hex');
    var metadata = new grpc.Metadata()
    metadata.add('macaroon', macaroon);
    callback(null, metadata);
});
var creds = grpc.credentials.combineChannelCredentials(sslCreds, macaroonCreds);
const lightning = new proto.Lightning(
    'localhost:1008', creds
);
 var request = {
        pay_req: "HERE PAY INVOICE",
    }
    lightning.decodePayReq(request, function (err, response) {
        console.log(response);
        console.error(err);
    })

```

it returns me **Error: 2 UNKNOWN: invalid bech32 string length 0**
which means it does not see my request

why is that? https://api.lightning.community/?python#decodepayreq 

listChannels works fine. but this **decodePayReq** and **lookupinvoice** **donsen't work**

in lncli decodePayReq and lookupinvoice  works to!
### Your environment 

* version of `lnd`  0.8.0
* which operating system (`uname -a` on *Nix) Ubuntu
* version of `btcd`, `bitcoind`, or other backend node
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment]
> Error: 2 UNKNOWN: invalid bech32 string length 0

This error means the request doesn't include a payment request.

Does using the field name `payReq` instead of `pay_req` work?

**Comment by Victorlerner** [comment]
**payReq**  and **pay_req**  don't work to

**Comment by Roasbeef** [comment]
Double check that you're passing in a real payment request. The API works as advertised, the error here is on the code side (your code).

**Comment by Victorlerner** [comment]
and where is the error in my code? I tried many options like camelcase etc...
 and spend many hours on this so I don't think that is an error in my code.
in addition, this code is from your own documentation https://api.lightning.community/?javascript#simple-rpc-29.

and I already wrote that yes **this is a real payment request in the console it works and in api no**

**Comment by wpaulino** [comment]
This worked for me using your code:
```
var request = {
    payReq: "lnsb1...",
}
```

The documentation suggests using the `grpc` package, rather than `@grpc/proto-loader`, which seems to prefer using camelCase.
