### ISSUE TITLE
Build fails: btcd@v0.20.0-beta: checksum mismatch

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#3638]
### Background

Can't build.

Getting:
```
go: verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
        downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
        go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
```

### Your environment

* version of `lnd` 
**1a0ab538d53c5be57cbbf80b0e48e5a207de9749**
* version of `go`
**go version go1.11.6 linux/arm**
* which operating system (`uname -a` on *Nix): 
**Linux 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux**
* version of `btcd`, `bitcoind`, or other backend
**I'm using bitcoind**

### Steps to reproduce

```
cd ~/gocode/src/github.com/lightningnetwork/lnd
git pull
make clean && make && make install
```

### Actual behaviour

Can't build. 

Tried `go clean -modcache` as suggested in #3607 - same problem.

Complete log:
```
 Cleaning source.
rm -f ./lnd-debug ./lncli-debug
rm -f ./lnd-itest ./lncli-itest
rm -f -r ./vendor .vendor-new
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.8.0-beta-67-g1a0ab538d53c5be57cbbf80b0e48e5a207de9749-dirty" github.com/lightningnetwork/lnd/cmd/lnd
go: downloading github.com/btcsuite/btcd v0.20.0-beta
go: downloading google.golang.org/genproto v0.0.0-20190201180003-4b09977fb922
Fetching https://google.golang.org/genproto?go-get=1
go: downloading github.com/kkdai/bstream v0.0.0-20181106074824-b3251f7901ec
go: finding github.com/ltcsuite/ltcd/chaincfg latest
Parsing meta tags from https://google.golang.org/genproto?go-get=1 (status code 200)
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at https://google.golang.org/genproto?go-get=1
go: finding github.com/ltcsuite/ltcd latest
go: downloading github.com/ltcsuite/ltcd v0.0.0-20190519120615-e27ee083f08f
go: verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
        downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
        go.sum:     h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
make: *** [Makefile:92: build] Error 1
```

**Comment by molxyz** [comment]
@alevchuk  Your Go version is ancient, you need to upgrade to go1.13.3 which is the latest, and that should solve this checkum mismatch issue.

**Comment by alevchuk** [comment]
Confirming: this gets solved by upgrading go to 1.13.3

**Comment by nordicdyno** [comment]
have got the same error with Go `1.13.4`

**Comment by guiguan** [comment]
still got this error in 1.13.3

**Comment by stridentbean** [comment]
I'm seeing this issue as well. It wasn't happening a week or so ago. It looks to be coming from https://github.com/lightningnetwork/lnd/blob/v0.8.0-beta/go.sum#L24. I'm running go 1.13.3 during docker build.

**Comment by reynico** [comment]
It is ok to re open this issue? Since v0.8.0-beta build fails as go.sum file is not matching the btcd signature

**Comment by Roasbeef** [comment]
Seems the best way to remedy this is to push a new tag. You'll find that `v0.8.1-beta` has been pushed as a new tag. It was branched off of `v0.8.0-beta`, but includes fixes to make `lnd` compatible with `bitcoind v0.19` and should resolve this mess in the process as well. Apologies for any trouble that it has caused.

**Comment by reynico** [comment]
`v0.8.1-beta` build did it perfect!

**Comment by wpaulino** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3638#issuecomment-554153370.
