### ISSUE TITLE
cannot get my php lnd to work

### ISSUE THREAD

**Issue by areaboy** [lightningnetwork/lnd#3641]
Hello everyone, Am new to LND. Am trying to test out amazing and awesome projects on Lighting Network. 
source[ https://github.com/rstmsn/php-lnd]( https://github.com/rstmsn/php-lnd)
I have downloaded the project and When I run index.php from my xampp server on windows, am facing this error below

```
Fatal error: Uncaught Exception: Macaroon not found. in C:\xampp\htdocs\proj3\classes\lnd.class.php:112 
Stack trace: #0 C:\xampp\htdocs\proj3\index.php(7): lnd->loadMacaroon('../../admin.mac...') #1 {main}
 thrown in C:\xampp\htdocs\proj3\classes\lnd.class.php on line 112

```
Please where do I get or generate this missing Macaroon. Again is there some instance that I need to set. Am running xampp
on windows for php

Thanks

**Comment by molxyz** [comment]
@areaboy  You need to ask for help on that repo, it doesn't belong to this Github LND site. But if you are running a LND node on windows, the macaroon files should be in directory `C:\Users\username\AppData\Local\Lnd\data\chain\bitcoin\testnet`  for testnet. For mainnet just replace `testnet` with `mainnet`.

**Comment by areaboy** [comment]
@molxyz Thanks for responding. please where do I download and install this LND node. Any docs helps on that. hoping to hear from you.

**Comment by molxyz** [comment]
@areaboy  You are on LND official repo, and here's the guide how to install lnd:  https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

There's also LND slack where you can get help faster if you want to join:
https://join.slack.com/t/lightningcommunity/shared_invite/enQtMzQ0OTQyNjE5NjU1LWRiMGNmOTZiNzU0MTVmYzc1ZGFkZTUyNzUwOGJjMjYwNWRkNWQzZWE3MTkwZjdjZGE5ZGNiNGVkMzI2MDU4ZTE

**Comment by areaboy** [comment]
Thanks
