### ISSUE TITLE
What are system requirements for installing and running LND

### ISSUE THREAD

**Issue by areaboy** [lightningnetwork/lnd#3643]
I heard that system requirements for running and installing this LND is as follows. 

    **Any Windows, macOS, or Linux computer.
    10 GB of disk space available.
    Bandwidth to download 250 GB of data from Internet**

Is it true. Thanks

**Comment by wpaulino** [comment]
If you're running with a `bitcoind` or `btcd` backend, you'll also need enough disk space to store those 250 GB.
