### ISSUE TITLE
Add trace logging during graph sync with chain on startup

### ISSUE THREAD

**Issue by kornpow** [lightningnetwork/lnd#3658]
### Background

Describe your issue here.

After seeing that you shouldn't run a routing node with neutrino, and seeing that people are connecting to my cloud neutrino node, I must switch over to btcd or risk coins.

After stopping Neutrino Node, adding my btcd configuration to lnd.conf, and restarting lnd, with the "--routing.assumechanvalid" flag, my node gets hung up on "Syncing channel graph from height="
At this point it seems as LND has completely hung. ```lncli stop``` doesn't work, ```sudo kill -15 {pid}``` doesn't work, only ```sudo kill -9 {pid}``` will fully stop lnd.

### Your environment

* version of `lnd`
lnd version 0.8.0-beta commit=v0.8.0-beta-34-g8ed75834480e7be3f42d77f5d96e2880c94156fb
* which operating system (`uname -a` on *Nix)
Linux vultr.guest 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
btcd version 0.20.0-beta
* any other relevant environment details
Remote btcd node

### Steps to reproduce
Working Neutrino Start:
```nohup lnd --routing.assumechanvalid > /dev/null 2> /dev/null &```
Stop LND
Edit Config for BTCD backend
Start BTCD backend lnd
nohup lnd > /dev/null 2> /dev/null &

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Trace Logs of the issue:
https://pastebin.com/TqNR3dzM

### Expected behaviour

Tell us what should happen

Hopefully it should go back an validate my old channels, and begin working normally.

### Actual behaviour
Hung lnd when trying to sync graph

**Comment by Roasbeef** [comment]
This isn't supported. Also can you move the logs that you pasted into some sort of pastebin? Thanks, otherwise it makes this issue hard to navigate.

**Comment by sako0938** [comment]
Ok I updated the logs to a pastebin. Good to know it isnt supported right now, there wasnt a good consensus about Neutrino to btcd support.

**Comment by wpaulino** [comment]
How long was it stuck for? It's scanning ~2200 blocks for spent channels, which can take a while, especially with a remote node.

**Comment by sako0938** [comment]
I could have waited longer, I only waited 5-10 minutes at most. The fact that things were completely hung, logs completely stopped made me think we had an issue.

**Comment by wpaulino** [comment]
That's because this is being done during startup, and there's currently no way to stop `lnd` during this process. See https://github.com/lightningnetwork/lnd/issues/3399.

**Comment by sako0938** [comment]
It’s seems to start after unlock of the wallet. I’ll leave it going overnight and report back.

**Comment by sako0938** [comment]
It did end up working after leaving it for a long while. Would it be possible to add at least trace logs of activity for this action? In the past if I ever noticed it hanging, switching into trace logging, and seeing activity at least gave me confidence things were still working.

Still Roasbeef says switching backends isnt supported, so I'll probably just keep this as btcd backend node.

**Comment by wpaulino** [comment]
> Would it be possible to add at least trace logs of activity for this action?

Sure, renamed the issue to reflect this.

**Comment by sako0938** [comment]
I still think this is an important issue, even when not using Neutrino. This extra logging is something people can use to help themselves.

This step takes a pretty decent amount of time, and if there are other issues at play, like an unresponsive remote node, you're really in the dark the entire time waiting for something to happen.

```
2020-03-14 20:52:30.966 [INF] CRTR: FilteredChainView starting
2020-03-14 20:52:32.421 [INF] CRTR: Filtering chain using 37076 channels active
2020-03-14 20:52:32.549 [INF] CRTR: Prune tip for Channel Graph: height=620944, hash=00000000000000000001e11d2a7cd9f41c1620a711673303098825a723fd2e53
2020-03-14 20:52:32.674 [INF] CRTR: Syncing channel graph from height=620944 (hash=00000000000000000001e11d2a7cd9f41c1620a711673303098825a723fd2e53) to height=621653 (hash=000000000000000000057850f7082d69fd637be4f14eb627ca29e5b61ef72f68)
2020-03-14 21:01:34.642 [INF] RPCS: [debuglevel] changing debug level to: trace
2020-03-14 21:06:00.196 [DBG] NTFN: Filtering 2526 txns for 30 spend requests at height 621654
```
I simply turned off my node, scp'ed my data directory to a new server, and started again, and this step still takes ~15 minutes, all the while I am wondering if some firewall issue or btcd issue is occuring.

**Comment by tlindi** [comment]
I'd love to se also some additional log entries too. This is with Bitcoin Core as a backend.

`2024-01-19 05:39:32.113 [INF] CRTR: Prune tip for Channel Graph: height=795306, hash=00000000000000000001ca0ec46c01bfeb1a978c84a77af0ff0bb07455b144f02024-01-19 05:39:32.113 [INF] CRTR: Prune tip for Channel Graph: height=795306, hash=00000000000000000001ca0ec46c01bfeb1a978c84a77af0ff0bb07455b144f0

2024-01-19 05:39:32.253 [INF] CRTR: Syncing channel graph from height=795306 (hash=00000000000000000001ca0ec46c01bfeb1a978c84a77af0ff0bb07455b144f0) to height=826365 (hash=000000000000000000012ea3b73236c75114556050b6d212cdc7a754d210fa6a)`

Would be lovely to see some progress, please?

**Comment by tlindi** [comment]
@roasbeef any chance someone could look into this. This is anoyning many many mobile node builders too. Please?

**Comment by guggero** [comment]
@tlindi it doesn't look like you've even set your log to debug or trace. Do you see more when you set `loglevel=debug` in your config?

**Comment by tlindi** [comment]
I added
`debuglevel=CRTR=trace`

Now there was one **huge** line 
![image](https://github.com/lightningnetwork/lnd/assets/7249767/89811f9a-0327-4e6e-86ca-4613094881ca)

But but even after some 30minutes there was no more `[TRC] [CRTR]` lines.  As one would expect, cause this issue above says logging should be improved. Unfortunately my bundle node rolled logs over after sync catched up. And I have no more details :-/ But anyone can see the same after node is offline for some time. (I'll try to catch better log.)

Just for reference / sample how it could look (from electrs) as [INF] level too.
![image](https://github.com/lightningnetwork/lnd/assets/7249767/74a895f1-8f2f-43ad-9e1d-aa12360d8199)
^Nice and clean isn't it?


Has logging been improved been since open of this issue?

**Comment by kornpow** [comment]
@guggero I think I hit this again... I am interested in fixing it.

Made a simple fix, which is already giving me far more confidence about this loooong running procedure:
```
--- a/routing/router.go
+++ b/routing/router.go
@@ -824,7 +824,7 @@ func (r *ChannelRouter) syncGraphWithChain() error {
                if err != nil {
                        return err
                }
-
+               log.Debugf("Checking Next Height: %v ", int64(nextHeight))
                // We're only interested in all prior outputs that have been
                // spent in the block, so collate all the referenced previous
                // outpoints within each tx and input.
```


Example output:
```
2024-03-12 22:31:44.473 [DBG] CRTR: Checking Next Height: 701593 
2024-03-12 22:31:44.906 [DBG] CRTR: Checking Next Height: 701594 
2024-03-12 22:31:45.342 [DBG] CRTR: Checking Next Height: 701595 
2024-03-12 22:31:45.591 [DBG] LNWL: Processing GetRawTransaction for batch 60...
2024-03-12 22:31:45.699 [DBG] CRTR: Checking Next Height: 701596 
2024-03-12 22:31:46.273 [DBG] CRTR: Checking Next Height: 701597 
2024-03-12 22:31:46.925 [DBG] CRTR: Checking Next Height: 701598 
2024-03-12 22:31:47.287 [DBG] CRTR: Checking Next Height: 701599 
2024-03-12 22:31:47.584 [DBG] LNWL: Processing GetRawTransaction for batch 61...
2024-03-12 22:31:47.702 [DBG] CRTR: Checking Next Height: 701600 
2024-03-12 22:31:48.282 [DBG] CRTR: Checking Next Height: 701601 
2024-03-12 22:31:48.715 [DBG] CRTR: Checking Next Height: 701602 
```

**Comment by guggero** [comment]
Happy to review a PR if you want to put one up. Or should I take the diff and create the PR?

**Comment by tlindi** [comment]
Would it be too much of output if logging level could be [INFO]?

**Comment by kornpow** [comment]
I think that #8550 should close this issue
