### ISSUE TITLE
Add support for namespacing logs from bitcoin backend

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#3662]
Currently all logs coming from the bitcoind backend, such as when importing Neutrino, gets the tag `[BTCN]`. Internally in Neutrino, each sub system has its own logger with a namespace, but this won't be shown in the lnd logs.

We should add support for showing the internal tags in the lnd logs, either by using the backend tags directly, or adding them to the existing lnd log tag.

- [ ] Show backend tags in lnd logs
- [ ] Allow setting loglevel on individual backend tags.

**Comment by saubyk** [comment]
Closing this as may not be relevant now
