### ISSUE TITLE
Question for Offline Invoice Generation: How to catch onions failures and custom settlement HTLC with preimage?

### ISSUE THREAD

**Issue by tiero** [lightningnetwork/lnd#3666]
Background: I'm trying to implement the idea explained here https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-June/002009.html 

TL;DR  an offline vending machine generates an BOLT11 invoice with ephemeral node pub key  generated on the fly and put in the _routing hints_ the actual route needed in order to reach our *online* node 

If I would implement this in LND, how I can detect the Onion Failure and notify this to other clients? A stream would be perfect!

**Comment by carlaKC** [comment]
Hi @tiero, if I'm understanding your goals and the mailing list post correctly (specifically `When our online node is asked to route a payment to an unknown node `K` it tries to generate the preimage.`) you're looking to add some custom logic to your node to account for the case where a HTLC arrives at your node and has an invalid onion structure which you then try to parse for some alternate information which will provide you with a preimage?

Could you please clarify some points for me?
1. You're expecting to be the last node in the route, yes? 
2. Your need to extract this custom preimage then settle the incoming HTLC? Not just observe that this invalid HTLC has arrived

I am working on #3420 which will provide a stream of HTLC events (including failures), but if you need custom HTLC settle logic (which I think you do, unless I'm misunderstanding) then I don't think that an events stream on its own is going to suffice?

**Comment by tiero** [comment]
Hi @carlaKC 

thank you for your sweet response, yes you got right. 

> You're expecting to be the last node in the route, yes?
Yes exactly I will put in the routing hints my online node, the actual recipient of the payment.

> Your need to extract this custom preimage then settle the incoming HTLC? Not just observe that this invalid HTLC has arrived

Yes, the first part would be to detect incoming HTLC failure and try to parse/decrypt the preimage encoded. 

The second part would be to implement some custom settlement logic as you say, yes. If you have any hints on where to put my hands on to start working on this custom logic, super appreciated!

It seems that you are exactly working on the feature I need for the first part, I would subscribe for Failure Events and try to get the payload of the HTLC somehow.

**Comment by Roasbeef** [comment]
Rather than implement the adhoc protocol outlined in that mailing list post, you can instead leverage the upcoming AMP support to implement this. Check out these slides from a talk I recently gave: https://docs.google.com/presentation/d/1nCqBVPF63xi0apzDEfWNrj_IA0iNt1XYSINjHtmmqaI/edit?usp=sharing (slides 6-8). 

The scheme in the ML post you linked requires exposing internal Sphinx packet processing state to an application, which is a major layering violation. The scheme described in the slides I linked above supports payment splitting, and also create a re-useable invoice along the way as well, which is independently useful.

**Comment by tiero** [comment]
Thanks, so you are suggesting in particular to `Can also delegate invoice signing to distinct pubkey` feature, that's would be great. 

Where I can follow/contribute to this upcoming AMP support?
