### ISSUE TITLE
[Feature Request]  mutually funded channels implementation

### ISSUE THREAD

**Issue by brain-zhang** [lightningnetwork/lnd#3673]
### Background

It seems now the Lightning implementations do not allow for mutually funded channels;  its not bidirectional by default.

I created a channel and i don't have any inbound capacity on that very channel. Then I send some bitcoin to the other side, Can i receive the money back by the same channel without gererating an invoice?

After reading through this whole issues management, but i found nothing about this thread; Of sure, I'll check the docs too; If I missed something, thanks for pointing me that.

**Comment by molxyz** [comment]
@brain-zhang 

> I created a channel and i don't have any inbound capacity on that very channel. Then I send some bitcoin to the other side, Can i receive the money back by the same channel without gererating an invoice?

No. There's WIP for `key send` txs, look at PR #2455 but this is not in the current implementation.

**Comment by carlaKC** [comment]
The title and body on this feature request seem unrealated to me? There are two issues here:
1. Title - Mutually funded channels: assuming this means the ability for both parties to contribute funds to a channel on creation. This is generally referred to as dual funded channels, and there is a PR open to the BOLTS [here](https://github.com/lightningnetwork/lightning-rfc/pull/524).
2. Body - invoiceless sends: The ability to send to a node without an invoice, which currently has a WIP PR out as @molxyz points out

Which one of these are you after?

**Comment by brain-zhang** [comment]
Dear @molxyz and @carlaKC , Thank you for your guidance; I think [WIP](https://github.com/lightningnetwork/lightning-rfc/pull/524) is the extremeccly  feature what i want;

Sorry for I'd never noticed it before; and then i'll identified as Duplicate of #524

**Comment by brain-zhang** [comment]
Duplicate of #524

**Comment by Roasbeef** [comment]
> I created a channel and i don't have any inbound capacity on that very channel. 

@brain-zhang, you can [use Loop to resolve this](https://blog.lightning.engineering/posts/2019/03/20/loop.html).
