### ISSUE TITLE
lnd Dockerfile is not building image on Docker Hub

### ISSUE THREAD

**Issue by kordless** [lightningnetwork/lnd#368]
Step 10/11 : COPY "docker/lnd/start-lnd.sh" .

COPY failed: stat /var/lib/docker/tmp/docker-builder532973727/docker/lnd/start-lnd.sh: no such file or directory

**Comment by Roasbeef** [comment]
That's a surprise: I wasn't aware that we have an image on Docker Hub! 

Can you like to the image you're trying to build? If you're not able to build from pulling (whichever non-official) image you're pulling from Docker Hub, can you [build locally using the `docker-compose` set up](https://github.com/lightningnetwork/lnd/tree/master/docker)? 

(also reminds me that the configuration should be updated to add an option for spinning up `lnd` nodes backed by [`neutrino`](https://github.com/lightninglabs/neutrino))

**Comment by bryanvu** [comment]
This error goes away for me on Google Container engine if I remove the directory as in PR #378. @kordless can you send us the info for the image on Docker Hub so I can check to see that this fixes it?

**Comment by Roasbeef** [comment]
Closing due inactivity.
