### ISSUE TITLE
Getting Error while running $make check Makefile:121: recipe for target 'unit' failed

### ISSUE THREAD

**Issue by Susilmohanty11** [lightningnetwork/lnd#3680]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by guggero** [comment]
See #3681
