### ISSUE TITLE
Getting Error while running $make check Makefile:121: recipe for target 'unit' failed

### ISSUE THREAD

**Issue by Susilmohanty11** [lightningnetwork/lnd#3681]
Dear All,
Warm greetings,

I am getting error while running $make check command after LND installation.

OS: Ubuntu 18.04 LTS
Go Version: go version go1.13.4 linux/amd64

Installed LND using the bellow commands

go get -d github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
make && make install
It works well.

While running Tests command, I am getting error
$make check

--- PASS: TestFundingManagerRestartBehavior (5.13s)
PASS
ok  	github.com/lightningnetwork/lnd	(cached)
?   	github.com/lightningnetwork/lnd/cmd/lncli	[no test files]
?   	github.com/lightningnetwork/lnd/cmd/lnd	[no test files]
?   	github.com/lightningnetwork/lnd/docs/go-fuzz	[no test files]
?   	github.com/lightningnetwork/lnd/lntest	[no test files]
?   	github.com/lightningnetwork/lnd/watchtower/wtmock	[no test files]
Makefile:121: recipe for target 'unit' failed
make: *** [unit] Error 123

How to resolve this issue? 

Thanking You
Warm regards 
Susil

**Comment by guggero** [comment]
You need the binary called `bitcoind` to be in your path, otherwise some tests will fail. If you scroll up, you should see the exact tests that fail if you search for `FAIL:`.
I'm going to add this to the documentation.
