### ISSUE TITLE
Can't start lnd after shutdown: ChannelDB migration problem

### ISSUE THREAD

**Issue by theBergmann** [lightningnetwork/lnd#3683]
### Background

I had to delete my cert files, so I shut down lnd and rebooted it. Than I stumpled into a large array of erros.

1. restarting lnd caused this sequence:

2019-11-06 18:34:44.503 [INF] LTND: Version: 0.6.1-beta commit=v0.6.1-beta, build=production, logging=default
2019-11-06 18:34:44.503 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-11-06 18:34:44.547 [INF] CHDB: Checking for schema update: latest_version=8, db_version=9
2019-11-06 18:34:44.547 [ERR] CHDB: Refusing to revert from db_version=9 to lower version=8
2019-11-06 18:34:44.548 [ERR] LTND: unable to open channeldb: channel db cannot revert to prior version
2019-11-06 18:34:44.548 [INF] LTND: Shutdown complete
channel db cannot revert to prior version

2. Tried to upgrade lnd. Used the guide here:
https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

but after typing "make clear && make && make install" I get this:

/usr/local/go/src/runtime/map.go:97:2: too many errors
make: *** [build] Fehler 2

3. Now I can't start lightning.

### Your environment

* version of `lnd`
0.6.2
* which operating system (`uname -a` on *Nix)
Linux node 2.6.32-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
core 0.16.2
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment]
> 2019-11-06 18:34:44.548 [ERR] LTND: unable to open channeldb: channel db cannot revert to prior version

Database migrations are not backwards-compatible, so you can't downgrade after you've already upgraded.

> but after typing "make clear && make && make install" I get this:
> /usr/local/go/src/runtime/map.go:97:2: too many errors

This suggests that the prior version of `go` wasn't properly uninstalled before installing the never version. Once that's done, you should be able to compile and install the latest version of `lnd`. Alternatively, you can use the existing release binaries.

**Comment by theBergmann** [comment]
Thank you for the answer.
How can I solve the database issue?

I also don't know how to uninstall go. Installed it with the code specified in the lnd installation guide.

**Comment by halseth** [comment]
You can use the binaries found here if you can't compile lnd: https://github.com/lightningnetwork/lnd/releases

Newest version is recommended.

**Comment by molxyz** [comment]
@theBergmann You also need to update your bitcoind, v0.16.2 is ancient, and due to the inflation bug that was discovered, safe versions for bitcoin start with 0.16.3 and up, the current version is 0.18.1.
