### ISSUE TITLE
OpenChannel struct database inconsistencies

### ISSUE THREAD

**Issue by wpaulino** [lightningnetwork/lnd#3696]
The `channeldb.OpenChannel` struct has a few inconsistencies in its method and uses. There should ever be one active instance per channel, i.e., the singleton pattern, but this is not the case. Many of its methods also read/write information not strictly necessary for their operation. These inconsistencies together have led to bugs like https://github.com/lightningnetwork/lnd/issues/3675.

**Comment by Roasbeef** [comment]
I think these have been resolved at this point?

**Comment by wpaulino** [comment]
The issues caused by the inconsistencies have been resolved, but the singleton pattern hasn't been done yet if we still want to do that.
