### ISSUE TITLE
Show balance committed to fees in ChannelBalance RPC

### ISSUE THREAD

**Issue by JavierRSobrino** [lightningnetwork/lnd#3707]
### Background

The balance is being reduced over time for no apparent reason:

```
lncli channelbalance
{
    "balance": "36236429",
    "pending_open_balance": "0"
}
# several minutes after:
lnd lncli channelbalance
{
    "balance": "36230377",
    "pending_open_balance": "0"
}
# several minutes after:
lncli channelbalance
{
    "balance": "36220371",
    "pending_open_balance": "0"
}
#several minutes after:
lncli channelbalance
{
    "balance": "36218966",
    "pending_open_balance": "0"
}

```

Trying to understand if it is related to routing:

```
lncli fwdinghistory
{
    "forwarding_events": [
    ],
    "last_offset_index": 0
}
```
All channels appear as connected except one, and this has not been changed for several hours.

### Your environment

* version of `lnd`: v0.8.0-beta-20-g21a40daf5840a856240866fff49e8c07dac7283c
* base fee put to 50000, in case it is relevant.
* 37 channels open at this time.
* Debian inside docker.
* Bitcoind 0.18

### Steps to reproduce

Just watch the balance over time.

**Comment by guggero** [comment]
This is due to fee re-negotiation. When on-chain fees rise, the peers of a channel negotiate a new fee that would be used to close a channel. This fee is deducted from the balance of the channel funder.
Can you tell us the approximate time frame over which you observed the balances?
And can you try to correlate rising fees, for example with https://jochen-hoenicke.de/queue/#0,24h ?

**Comment by JavierRSobrino** [comment]
Thank you @guggero, it seems to be that, now the balance is increasing.
Speaking of this, I think the way the balance is presented is then confusing. Perhaps should have 3 properties and a total, like:

```
{
    "balance": "36258699",
    "retained": "134532",
    "pending_open_balance": "0"
    "total": "36393231",
}
```

Meaning `retained` the amount that is retained for on-chain fees.
