### ISSUE TITLE
The closed channels list, should return who initiated the channel-close operation close_initiator

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#3709]
### Background

The closed channels list, should return who initiated the channel-close operation close_initiator

### Expected behaviour

show "close_initiator": true/false, like "initiator": true for channels

### Actual behaviour

attribute not present

**Comment by wpaulino** [comment]
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/2594.

**Comment by brandoncurtis** [comment]
@wpaulino I don't think this is a duplicate.  #2594 asks `closedchannels` to include the *channel initiator*; this issue is asking `closedchannels` to include information about *which party initiated the close*.

**Comment by wpaulino** [comment]
This would only be useful in the co-op close case as you can already determine which party force closed through the close type field.
