### ISSUE TITLE
LND crashes at startup CHDB: Unable to apply migration #9

### ISSUE THREAD

**Issue by jguchte** [lightningnetwork/lnd#3714]
### Background
After updating from 0.5.1 to 0.7.1 LND crashes at startup with the following error log:

Attempting automatic RPC configuration to bitcoind
Automatically obtained bitcoind's RPC credentials
2019-11-11 20:52:56.377 [INF] LTND: Version: 0.8.0-beta commit=v0.8.0-beta, build=production, logging=default
2019-11-11 20:52:56.377 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-11-11 20:52:56.398 [INF] CHDB: Checking for schema update: latest_version=11, db_version=8
2019-11-11 20:52:56.398 [INF] CHDB: Performing database schema migration
2019-11-11 20:52:56.398 [INF] CHDB: Applying migration #9
2019-11-11 20:52:56.398 [INF] CHDB: Migrating outgoing payments to new bucket structure
2019-11-11 20:52:56.399 [INF] CHDB: Unable to apply migration #9
2019-11-11 20:52:56.400 [ERR] LTND: Unable to open channeldb: graph bucket not initialized
2019-11-11 20:52:56.400 [INF] LTND: Shutdown complete
Unable to open channeldb: graph bucket not initialized

In the mean time I have updated to 0.8.0 to see if the problem was solved.
Not sure what to do next.

### Your environment

* version of `lnd`
0.8.0-beta
* which operating system (`uname -a` on *Nix)
Linux RaspiBolt 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.0.1
* any other relevant environment details

### Steps to reproduce

Just starting LND produces this error.

### Expected behaviour

LND should perform the database migration and start.

### Actual behaviour

LND crashes.

**Comment by halseth** [comment]
@jguchte Did you have channels open before doing the upgrade? And done any payments?

The error indicates that the self node pubkey isn't set, which usually mean that the node was never started properly.

**Comment by jguchte** [comment]
> 
> 
> @jguchte Did you have channels open before doing the upgrade? And done any payments?


Thanks for your reply!

I believe I indeed  had some channels open during the upgrade. After the upgrade I was able to open/close some channels. 
I do not think I made any payments.

**Comment by halseth** [comment]
So you are saying you were able to start the node after you updated? Or did you revert back to the old version?

**Comment by jguchte** [comment]
I think so... Unfortunately I do not have a complete timeline by memory. After the crashes I haven't looked at my node for a couple of months. 

At the moment my node has two active channels which are created 8 and 9 months ago and one active channel which is created 3 months ago.
When I look at the release date of lnd v0.7.1-beta (Jul 30) it gives me the impression I opened the last channel after I upgraded.

Is there a way for me to lookup some LND (upgrade) logging which can confirm of invalidate the above? Maybe I can compare the upgrade date with the channel creation date.

Thanks in advance and sorry I can not give a conclusive answer to your questions.

**Comment by halseth** [comment]
@jguchte So you are running v0.8 now, and it works?

**Comment by jguchte** [comment]
The node stopped working while on v0.7.1. At that point I didn't know what to do, keeping in mind that I didn't want to lose any funds. I did not yet make a backup (full image of the SD card in my rpi3) after upgrading to v0.7.1, so I would lose the new channels after a "restore" back to an old image running v.0.5.1.

I couldn't find an answer to this problem so I let it be for a while. The next time I looked on Github there was a new version (0.8.0) and I thought maybe upgrading could solve it.

Is it possible to downgrade back to v0.5.1, or would this affect the channels created in v0.7.1?

**Comment by Roasbeef** [comment]
> Is it possible to downgrade back to v0.5.1, or would this affect the channels created in v0.7.1?

No, it isn't possible to downgrade.

**Comment by jguchte** [comment]
> 
> 
> > Is it possible to downgrade back to v0.5.1, or would this affect the channels created in v0.7.1?
> 
> No, it isn't possible to downgrade.

Thanks for the reply!

Is there anything else I can try to solve this?

**Comment by halseth** [comment]
@jguchte Can you try running 0.7.1, and post the logs when starting up?

**Comment by jguchte** [comment]
> 
> 
> @jguchte Can you try running 0.7.1, and post the logs when starting up?

I'll try that, but I think I will get the same error. It was the reason to update to v.0.8.0.

I will report the logs here! 
Thanks.
