### ISSUE TITLE
Proposal: disable the channel from our side if local_balance == 0

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3717]
Why not set the LND the disable property on its side for a channels with `local_balance == 0`?

The protocol has a specially `disable` property for each side of the channel (which translated with `channelUpdate`). Since the world does not know balances of channel, the operational management of this property would reduce unnecessary attempts to iterate routes in those directions where the payment still fails.

For example:

lnd-09 has channel:

```
{
    "active": true,
    "remote_pubkey": "0208fbcafddef7e746ff727c2244b854a7f18a52f9ce9a03724a190cc5b999313a",
    "channel_point": "330fb0fe195737c21fa33d8ddf351c00669d301e8de044a4a58406781d31a4ec:1",
    "chan_id": "652324855729225729",
    "capacity": "292855",
    "local_balance": "0",
    "remote_balance": "288189",
    "commit_fee": "4666",
    "commit_weight": "552",
    "fee_per_kw": "6446",
    "unsettled_balance": "0",
    "total_satoshis_sent": "0",
    "total_satoshis_received": "0",
    "num_updates": "2610",
    "pending_htlcs": [
    ],
    "csv_delay": 6,
    "private": false,
    "initiator": false,
    "chan_status_flags": "ChanStatusDefault",
    "local_chan_reserve_sat": "2928",
    "remote_chan_reserve_sat": "2928",
    "static_remote_key": false
},
```

The probability that the payment will go out through this channel is 0%. However, the LND has in the policy `disabled` as `false` for this direction:

```
$ l getchaninfo 652324855729225729
{
    "channel_id": "652324855729225729",
    "chan_point": "330fb0fe195737c21fa33d8ddf351c00669d301e8de044a4a58406781d31a4ec:1",
    "last_update": 1573617449,
    "node1_pub": "0208fbcafddef7e746ff727c2244b854a7f18a52f9ce9a03724a190cc5b999313a",
    "node2_pub": "02de11c748f5b25cfd2ce801176d3926bfde4de23b1ff43e692a5b76cf06805e4a",
    "capacity": "292855",
    "node1_policy": {
        "time_lock_delta": 14,
        "min_htlc": "1",
        "fee_base_msat": "1",
        "fee_rate_milli_msat": "10",
        "disabled": false,
        "max_htlc_msat": "289927000",
        "last_update": 1573097284
    },
    "node2_policy": {
        "time_lock_delta": 30,
        "min_htlc": "0",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "6400",
        "disabled": false,
        "max_htlc_msat": "292855000",
        "last_update": 1573617449
    }
}
```

And this means that many wallets will try this direction for sending. And it could be like this:

```
if (local_balance == 0) {
    disabled = true
    channelUpdate()
}
else {
    disabled = false
    channelUpdate()
}
```

What do you think about this?

**Comment by Roasbeef** [comment]
Totally makes sense. We already have [a sub-system that manages enabling/disabling channels to the network](https://godoc.org/github.com/lightningnetwork/lnd/netann). So from here, the next step would be to add a new component in the switch (?) that would request enables/disables based on sampled channel bandwidth.

**Comment by halseth** [comment]
Leaks who is the initiator? I guess it can be probed relatively easy anyway...

**Comment by C-Otto** [comment]
Related to #5033

**Comment by alexbosworth** [comment]
LND 0.13.0 allows you to control the disable flag so you can implement this heuristic if you want

**Comment by LNBIG-COM** [comment]
> LND 0.13.0 allows you to control the disable flag so you can implement this heuristic if you want

Is it possible for the LND itself to perform this function, even if only some option is globally enabled for this? As I understand it, the developers implemented flag control through the API, but I don't see any problems for the server itself to manage this (after all, it sees balances on its side).

**Comment by LNBIG-COM** [comment]
It seems that there was already a discussion about this in the specified thread. While reading and trying to understand.

**Comment by LNBIG-COM** [comment]
> LND 0.13.0 allows you to control the disable flag so you can implement this heuristic if you want

Can you send a link to the method of gRPC API where I can change this flag? I haven't found it yet.

**Comment by guggero** [comment]
The API is in the `routerrpc` subserver: https://api.lightning.community/#updatechanstatus

**Comment by Roasbeef** [comment]
> if the sender uses the old low prices, will also cause a cancellation of the payment (although it will attach new tariffs to the onion packet).

In practice, if the sender is using `lnd`, they'll retry once more (with no penalty) using that new fee.
