### ISSUE TITLE
QueryRoutes doesn't see in disabled field of graph edge policy?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3718]
### Background

Sometimes i call `QueryRoutes` after i call `SendToRouteSync` with these routes and got messages `ChannelDisabled`. I checked same errors - they are valid and `getchaninfo` has `disabled` as `true`. I may suspect that inside the `QueryRoutes` function does not pay attention to the `disabled` property in a policy for the channel in the certain direction.

### Your environment

* version of `lnd` 0.8.0-beat

### Expected behaviour

I think `QueryRoutes` should return only routes with enabled channels.

**Comment by wpaulino** [comment]
> I think QueryRoutes should return only routes with enabled channels.

I believe it already does this, the path finding code is shared between our routing-related RPCs.

What's happening here is that your node wasn't aware of these channels being disabled, so once it receives the error back, it's applied to the database to reflect that they're now disabled.
