### ISSUE TITLE
Unclear encoding of r_hash_str in documentation

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#3720]
### Background

The encoding of `r_hash_str` is unclear from the [documentation](https://api.lightning.community/rest/index.html#v1-invoice). It's not possible to determine if it should be hex, URL encoding, bas64 or something else.

### Your environment

N/A

### Steps to reproduce

1. Go to https://api.lightning.community/rest/index.html#v1-invoice
2. Read the documentation.
3. See that's imposible to determine the encoding

### Expected behaviour

The documentation clearly states what encoding should be used.

### Actual behaviour

Encoding is missing.

**Comment by wpaulino** [comment]
The documentation needs to be updated. You can look at the [source](https://github.com/lightningnetwork/lnd/blob/e2e94c3b6e2ff7d02361b99255cd262c2de8f9a7/lnrpc/rpc.proto#L2351) for now instead.

**Comment by guggero** [comment]
Documentation was updated, it now states that base64 encoding needs to be used.
