### ISSUE TITLE
SendToRoute & SendToRouteSync - how to get onion packet of error message?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3731]
I have 0.8.0-beta and use rebalancing

Often i get some error: `TemporaryChannelFailure` or `UnknownNextPeer`. But if i get `UnknownNextPeer` error for example i have only code of error and payment_hash. Example:

```
{ payment_error: 'UnknownNextPeer', payment_preimage: <Buffer >, payment_route: null, payment_hash: <Buffer ec 2a c1 08 bc 4b 35 fa 15 3d fd 7d 0a 33 fc e4 78 96 59 99 4c a8 56 e2 84 87 1a f
5 27 93 d0 d6> }
```

I cannot define what a node sent to me this error (an onion packet should consists a public key of node who sent error) and where in problem if route has 6-8 hops for example. And i cannot repay by other route because i should recall QueryRoutes with new ignore_edges but i don't know what should i add to `ignore_edges`

I asked @btcontract and he answered me that i should get onion packet for this. It does the Eclair for example.

How can i get onion error packet from `SendToRoute*` gRPC method?

P.S. For example `TemporaryChannelFailure` error is as:

```
{ payment_error: 'TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc00727fd90)({\n' + ' Signature: (lnwire.Sig) (len=64 cap=64) {\n' + '  00000000  4f 59 65 d9 d5 13 bb ab  73 91 6f 73 98 94 92 eb  |OYe.....s.os....|\n' + '  00000010  3b 62 3b e2 22 21 78 70  00 d5 17 f4 53 bf 94 dc  |;b;."!xp....S...|\n' + '  00000020  62 bd 19 ae 67 47 95 bb  f8 ba 5e 04 d1 3f bf 01  |b...gG....^..?..|\n' + '  00000030  d4 b9 42 76 31 75 8e c6  0c 95 f2 20 f5 e0 8c a1  |..Bv1u..... ....|\n' + ' },\n' + ' ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,\n' + ' ShortChannelID: (lnwire.ShortChannelID) 580327:947:0,\n' + ' Timestamp: (uint32) 1573770868,\n' + ' MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,\n' + ' ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,\n' + ' TimeLockDelta: (uint16) 40,\n' + ' HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,\n' + ' BaseFee: (uint32) 1,\n' + ' FeeRate: (uint32) 1,\n' + ' HtlcMaximumMsat: (lnwire.MilliSatoshi) 1980000000 mSAT,\n' + ' ExtraOpaqueData: ([]uint8) <nil>\n' + '})\n' + ')', payment_preimage: <Buffer >, payment_route: null, payment_hash: <Buffer da 90 e7 6b 94 82 95 b3 f1 92 43 5d 5b b1 43 bb 2b 06 be ff 82 7b d8 60 ea 0a 59 a2 bd 92 de 51> }
```

There is few more info and i parse it (`ShortChannelID`) but @btcontract answered to me that it's not completed info too. There is no onion packet too (i need public key of node who sent this error)

**Comment by wpaulino** [comment]
If you use the [`routerrpc` `SendToRoute`](https://github.com/lightningnetwork/lnd/blob/cea24294892bcc3b2bcfb02306fc3f86c6eb842b/lnrpc/routerrpc/router.proto#L191) version, there's a `Failure` in the response which includes the  `failure_source_index` of the route.

**Comment by LNBIG-COM** [comment]
I use `SendToRouteSync` and i use gRPC

I see now in docs: https://api.lightning.community/#sendtoroutesync

There is only `SendResponse` response. What is `routerrpc` term?

**Comment by wpaulino** [comment]
It's a router-related subserver. You can read more about them in the (`v0.6.0-beta` release notes](https://github.com/lightningnetwork/lnd/releases/tag/v0.6-beta).

**Comment by LNBIG-COM** [comment]
Thanks! It's new world for me ;-) I thought that there is only one gRPC methods. I will look there

**Comment by LNBIG-COM** [comment]
Please one question only
The default `SendToRoute` is in `Lightning` service. But if i will include `routerrpc` - what method will work as `SendToRoute`?

**Comment by wpaulino** [comment]
You'll need to instantiate the `Router` service found in [`router.proto`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/routerrpc/router.proto) similar to how you do with `Lightning` service. You can then invoke `SendToRoute` on the `Router` service.

**Comment by wpaulino** [comment]
Also it requires compiling `lnd` with the `routerrpc` flag. If you're using the binaries, it should be included. If you built from source, rebuild with `make install tags=routerrpc`.

**Comment by wpaulino** [comment]
Feel free to comment/re-open if you have any other questions.
