### ISSUE TITLE
lnd 0.8.1 gives wrong version at command line

### ISSUE THREAD

**Issue by ryantm** [lightningnetwork/lnd#3735]
### Background

--version flag for lnd 0.8.1-beta shows an older version

### Your environment

* version of `lnd` 0.8.1-beta
* which operating system (`uname -a` on *Nix) NixOS
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce
```
$ lnd --version
```

### Expected behaviour

```
lnd version 0.8.1-beta commit=
```

### Actual behaviour

```
lnd version 0.8.0-beta commit=
```

**Comment by Roasbeef** [comment]
If you compile using our makefile (as intended), you should see: 
```
lncli version 0.8.0-beta commit=v0.8.1-beta
```

**Comment by ryantm** [comment]
Okay, sorry to bug you, we'll look into it on our end more.
