### ISSUE TITLE
lncli listchaintxns shows not owned txs

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#3746]
I don't know if its an issue, or its on purpose, just wanted to know what is happening

### Background
i have been trying loop in testnet, for this loop in HTLC 2MuuE7evoExqtVmFX2K1WsJA6jpzY2aosac
which have 2 tx
this b7a46dceffca8b738344011fc74ad88cd5eb0c158ceee50b84d5ece3699672ae which i think is the on-chain payment funding the HTLC
and this 4dc4c183d937747db543a2f08753e16aa06ba688670ae9a1d24937f7544d4619 which i think its the loop server sweeping the payment, after the off-chain invoice was paid, and secret revealed..
but if i prompt my node with lncli listchaintxns i can see both txs tracked by my node wallet
the second with "total_fees": "0",
we can explore that tx and see that in fact it has fees, (wont be mined if not)
why is my node tracking that tx? isn't that tx supposed to be from the server side?
is loopd using LND to watch for the final resolution of the swap and maybe LND's transaction subscriptions just do weird accounting when it's not your TX?
also in LND logs is see
[INF] LNWL: Inserting unconfirmed transaction 4dc4c183d937747db543a2f08753e16aa06ba688670ae9a1d24937f7544d4619
that tx is not supposed to be inserted by my node wallet, or am i wrong?e.

### Your environment

* `lnd` 0.8.0-beta
* Linux 4.4.0-166-generic 
* Bitcoin Core version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65 (64-bit)

### Steps to reproduce

Loop in and inspect logs

### Expected behaviour

LND wallet module not to track that zero fee on-chain tx

### Actual behaviour

LND wallet module tracking that that zero fee on-chain tx

**Comment by Roasbeef** [comment]
This is intended, we show all transactions sent by the wallet. `loopd` uses `lnd` to create its transactions.

**Comment by wpaulino** [comment]
The fees being 0 is another bug, see https://github.com/lightningnetwork/lnd/issues/2936.

Closing per https://github.com/lightningnetwork/lnd/issues/3746#issuecomment-556388330.

**Comment by danielemiliogarcia** [comment]
@Roasbeef , question...
the 2nd tx: 4dc4c183d937747db543a2f08753e16aa06ba688670ae9a1d24937f7544d4619 
i think its the loop server sweeping the payment, after the off-chain invoice was paid, and secret revealed.. or i am wrong?
if its the loop server, why is my wallet tracking that? is that because its destination is the HTLC address that i broadcasted? so its attached to an address of my ownership?

**Comment by wpaulino** [comment]
This seems like a bug actually, that transaction shouldn't show up for you.

**Comment by Roasbeef** [comment]
Anything actionable here?

**Comment by wpaulino** [comment]
@Roasbeef from what I remember, we may be calling `NotifyReceived` on outputs that aren't ours, causing its spend to show up as relevant.

**Comment by Roasbeef** [comment]
Fixed by the recent update to `btcwallet` master.
