### ISSUE TITLE
Close type mismatch, remote force close, reports a breach close

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#3747]
### Background

Doing a force close from node B, is reported as Breach close in node B instead of remote force close

https://github.com/lightningnetwork/lnd/blob/0b2ef8bb4e21479f408860fcf6dfdd8ae6814cc0/server.go#L805

### Steps to reproduce

Open a channel A->B , force close the channel from B

### Expected behaviour

in node A, report a Remote Force Close

### Actual behaviour

in node A, reports a Breach Close

**Comment by Roasbeef** [comment]
You may have accidentally breached yourself. Do you have any steps to reproduce this?

**Comment by danielemiliogarcia** [comment]
https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L2057-L2086 it missmatches docs https://api.lightning.community/#closuretype which is right?? or thats not the correct piece of code?

**Comment by wpaulino** [comment]
They're at different levels, one enum is used within the database, the other is used for the RPC. The database one is mapped to the RPC as shown in:
https://github.com/lightningnetwork/lnd/blob/b1e6d9c5cf26d7026c829e11ec95f2289a74201c/rpcserver.go#L2857

**Comment by danielemiliogarcia** [comment]
thanks, close
