### ISSUE TITLE
LND FreeBSD release

### ISSUE THREAD

**Issue by nvk** [lightningnetwork/lnd#376]
Would be very much appreciated if there was an official FreeBSD release.

**Comment by Roasbeef** [comment]
`golang` has built in support for cross-compiling to FreeBSD and also natively compiling on FreeBSD, so you should be able to build everything locally (if inclined). The last release `v0.3-alpha` is now out of sync with the mainline in master, so it won't be able to establish channels with most of the current testnet network (although that _does_ have a FreeBSD binary, mostly untested though).

**Comment by Roasbeef** [comment]
Closing as it's possible to build for FreeBSD manually. Future release will include a FreeBSD binary.

**Comment by Facey-McFace** [comment]
Where are the FreeBSD build instructions?
