### ISSUE TITLE
[Feature Request] show on hold balance of channels when there are hodl/hold invoices in flight

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#3764]
### Background

calling listchannels when there is a hold invoice in flight, the amount is not in local_balance nor in remote_balance so the channel capacity seems to be changed, would be nice to show a hold_balance with the sum of all hold invoices in flight for that channel, so remote+local+hold is always the channel capacity

**Comment by wpaulino** [comment]
You can already do so this today by adding all the pending HTLC amounts.
