### ISSUE TITLE
[Feature Request] ChannelBalance displays total_local_balance and total_remote_balance

### ISSUE THREAD

**Issue by danielemiliogarcia** [lightningnetwork/lnd#3765]
### Steps to reproduce

call ChannelBalance

### Expected behaviour

returns:

balance | int64 | Sum of channels balances denominated in satoshis
pending_open_balance | int64 | Sum of channels pending balances denominated in satoshis
total_local_balance  | int64 | Sum of channels local balances
total_remote_balance  | int64 | Sum of channels remote balances
total_on_hold_balance | int64 | Sum of channels on_hold balances see https://github.com/lightningnetwork/lnd/issues/3764

### Actual behaviour

returns:

balance | int64 | Sum of channels balances denominated in satoshis
pending_open_balance | int64 | Sum of channels pending balances denominated in satoshis

**Comment by wpaulino** [comment]
This remains unaddressed.

**Comment by kilrau** [comment]
Highly interested in this feature too. Workarounds (like iterating through `listchannels`) are very inefficient.

**Comment by yyforyongyu** [comment]
working on this one
