### ISSUE TITLE
Git pull doesn't update to latest beta version

### ISSUE THREAD

**Issue by 01CGAT** [lightningnetwork/lnd#3766]
The following update commands currently don't update lnd to the latest beta version:

cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull

**Comment by wpaulino** [comment]
By latest beta version are you referring to `v0.8.1-beta`? That release was based off of `v0.8.0-beta` and a few bug fixes rather than being based off of the master branch.

**Comment by 01CGAT** [comment]
I'm sorry, yes, I was referring to v0.8.1-beta.
Thanks for the clarification!
