### ISSUE TITLE
can't genSeed and initWallet

### ISSUE THREAD

**Issue by vinhyenvodoi98** [lightningnetwork/lnd#3779]
i try to create new wallet using js, grpc
this it my code 
```js
var fs = require('fs');
var grpc = require('grpc');
var protoLoader = require('@grpc/proto-loader');

const packageDefinition = protoLoader.loadSync('./rpc.proto');
const lnrpc = grpc.loadPackageDefinition(packageDefinition).lnrpc;

process.env.GRPC_SSL_CIPHER_SUITES = 'HIGH+ECDSA';
var lndCert = fs.readFileSync('/home/ubuntu/.lnd/tls.cert');
var sslCreds = grpc.credentials.createSsl(lndCert);

var walletUnlocker = new lnrpc.WalletUnlocker('localhost:10001', sslCreds);

var request = {
  // aezeed_passphrase: <bytes>,
  // seed_entropy: <bytes>,
};
walletUnlocker.genSeed(request, function(err, response) {
  console.log(response);
});
```
response is `undefined` and i try to use initWallet and get the same result
Is it possible to import a wallet by private key to use lightningnet work ?
please give me an example 
Thanks !!!

**Comment by guggero** [comment]
The code looks OK to me. For this to work, lnd has to be in the correct state though.
It should say the following line and wait there, otherwise the `WalletUnlocker` is not initiated:
`LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.`

You cannot import any wallet that was not generated by lnd. The `aezeed` mnemonic is a special format that is not (yet) adopted by any other tool. There is software out there that can turn your BIP32 root key (`xprv`) into an aezeed but I wouldn't recommend that unless you know exactly what you are doing. And lnd probably uses a different derivation path than the wallet you are importing from, so your coins might not even show up.

**Comment by vinhyenvodoi98** [comment]
@guggero 
Thank for your explanation .

- I trying to build game like tic tac toe where people can bet and play with each to other to other . But without smart contract ( like Ethereum ) and the channel is **single-funded channel** . what is solution, flow or architecture for me ?

> You cannot import any wallet that was not generated by lnd ...
you mean player must be create wallet in **lnd** even they have wallet already ,isn't it ? what is the easiest way for player to quick start a game ?

**Comment by guggero** [comment]
I think LN is a good choice for a game like that.
lnd needs to have full control over the on-chain funds it is given, so it is not advisable to use an existing seed (even though it is technically possible with some tricks).
Which leads to the following flow usually:
1. Setup lnd and create a new wallet (using the `GenSeed` and `InitWallet` methods).
1. Start/unlock lnd and let it sync the chain and graph.
1. Generate an on-chain address in the lnd wallet (with the `NewAddress` method).
1. Send some coins from an existing wallet to that address.
1. Open a channel.

**Comment by vinhyenvodoi98** [comment]
@guggero 
Thanks for the suggestion

**Comment by vinhyenvodoi98** [comment]
@guggero
If lnd node already has wallet, it will impossible to genSeed anymore, isn't it ?
```
require('dotenv').config();
var grpc = require('grpc');
var protoLoader = require('@grpc/proto-loader');

const packageDefinition = protoLoader.loadSync('./rpc.proto', {
  keepCase: true
});
const lnrpc = grpc.loadPackageDefinition(packageDefinition).lnrpc;

process.env.GRPC_SSL_CIPHER_SUITES = 'HIGH+ECDSA';
var lndCert = Buffer.from(process.env.LND_CERT, 'utf8');
var sslCreds = grpc.credentials.createSsl(lndCert);

var macaroonCreds = grpc.credentials.createFromMetadataGenerator(function(args, callback) {
  var macaroon = process.env.LND_MACAROON;
  var metadata = new grpc.Metadata();
  metadata.add('macaroon', macaroon);
  callback(null, metadata);
});

var creds = grpc.credentials.combineChannelCredentials(sslCreds, macaroonCreds);
var lightning = new lnrpc.Lightning('localhost:10009', creds);

var getInfo = () => {
  return new Promise((resolve, reject) => {
    var request = {};
    lightning.getInfo(request, (err, response) => {
      console.log(response);
      resolve(response);
    });
  });
};

var genSeed = async () => {
  var walletUnlocker = await new lnrpc.WalletUnlocker('localhost:10009', sslCreds);

  var request = {};

  await walletUnlocker.genSeed(request, function(err, response) {
    console.log(response);
  });
};

genSeed();
getInfo();
```
i was thought the problem is `walletUnlocker.genSeed(request, function(err, response) {...` run before `var walletUnlocker = await new lnrpc.WalletUnlocker('localhost:10009', sslCreds);` 
but genSeed() still response undefined

**Comment by guggero** [comment]
Correct, `genSeed()` can only be called while the wallet is locked (which only happens on startup, when a wallet password is set).
