### ISSUE TITLE
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#3780]
Ref issue posted first here: https://github.com/btcpayserver/btcpayserver/issues/1191

### Background

Using BTCPay server to run lightning. 

All commands to lnd gives this error: 

`bitcoin-lncli.sh walletbalance`
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"`

Despite this, sending and receiving payments with BTCPay server works fine.  

### Your environment

* version of `lnd`

lnd:v0.7.1-beta      

* which operating system (`uname -a` on *Nix)

Linux BTCPayServerVM 4.15.0-1019-azure #19-Ubuntu SMP Thu Jul 26 19:54:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

bitcoin:0.18.0

**Comment by Roasbeef** [comment]
You may be running the server on another port, or your cert is expired. Double check your port/host for the main server. If it's expired, then you need to restart your lnd node, and the cert will be re-generated.
