### ISSUE TITLE
Expired Keybase proofs for A96387A57CAAE94D

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#3784]
### Background

When attempting to verify GPG signatures of latest release (0.8.1) I found out that the keybase proofs for A96387A57CAAE94D key are absent.

### Your environment

Irrelevant

### Steps to reproduce

1. Open the keybase account of @Roasbeef 
2. Click github gist proof
3. See the proof for an old key (964EA263DD637C21)
4. Click reddit proof
5. See the proof for an old key (964EA263DD637C21)
6. Observe that Twitter account is not linked at all

### Expected behaviour

All proofs should be up to date. It'd be nice to have Twitter account linked too for greater confidence

### Actual behaviour

The proofs are expired, Twitter link missing.

**Comment by Roasbeef** [comment]
Tweet verification: https://twitter.com/roasbeef/status/1201703509470527488?s=20

Thanks for keeping me accountable!
