### ISSUE TITLE
Addinvoice lacks hop hint if last public channel is pendingclose

### ISSUE THREAD

**Issue by corbelantoine** [lightningnetwork/lnd#3792]
I tried closing my last public channel while I still had one private. I created a new invoice and no hint was included. That makes it impossible to receive payments while the channel is closing since the sender won't be able to find a path to my node.
Once the closing channel got confirmed on-chain, addinvoice started including hop_hints again.

lnd version 0.8.0-beta commit=v0.8.1-beta

**Comment by Roasbeef** [comment]
Are you sure the channel had enough inbound bandwidth for the payment?

**Comment by corbelantoine** [comment]
Add invoice without any parameter doesn’t assume a min payment size, right?
I simply called lncli addinvoice in both cases.

**Comment by wpaulino** [comment]
You can see why the channel is being skipped if you run `lncli debuglevel --level=IRPC=debug` and try creating the invoices again.

Was the private channel peer offline when you tried the first invoice?

**Comment by corbelantoine** [comment]
Seems like I can't reproduce...

No I don't think it was offline

**Comment by wpaulino** [comment]
> No I don't think it was offline

You can cross-check your logs to see timestamps of when the corresponding peer connected/disconnected and when the invoice was created.
