### ISSUE TITLE
Change 'sendcoins' error message

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#38]
When I tried to move bitcoins from `p2pkh` address to `p2wkh`, I found that our decode method can't recognise `p2wkh` address format.

```
$ lncli walletbalance
{
    "balance": 1000
}
$ lncli newaddress p2wkh
{
    "address": "4NyXCayeJqEvbNXeNTfjGMzDC55r3q8sA1xPa"
}

$ lncli sendcoins 4NyXCayeJqEvbNXeNTfjGMzDC55r3q8sA1xPa 1000
[lncli] rpc error: code = 2 desc = decoded address is of unknown format
```

**Comment by AndrewSamokhvalov** [comment]
Sorry, my fault,all works fine. But maybe we should change error message?
```
lncli sendcoins --addr=4NyXCayeJqEvbNXeNTfjGMzDC55r3q8sA1xPa --amt=1000
```

**Comment by Roasbeef** [comment]
Nice, happy you figrued it out in the end. 

Yeah, the error message there isn't very accurate. It's attempting to decode an address of `""`(empty string), which causes the command to fail. 

This is closely linked to #31 which proposes adding support for _positional_ arguments in addition to the currently supported key word arguments. As a stop gap, some preliminary sanity checks can be added to all (most?) of the commands which ensures that the require values have been specified.
