### ISSUE TITLE
Cosmetics: missing space in log message

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#3807]
There should be a space after "finished":

`2019-12-07 19:46:12.605 [INF] NTFN: Historical spend dispatch finishedfor request outpoint=xxx:1, script=0 xxx (start=607101 end=607101) with details: <nil>`

**Comment by ellemouton** [comment]
I am keen to pick this one up in order to learn how to do a PR

**Comment by C-Otto** [comment]
Fixed in #3813
