### ISSUE TITLE
crash report: BRAR: unable to load channel from disk: json: cannot unmarshal array into Go struct field Vin.txinwitness of type string

### ISSUE THREAD

**Issue by stevenroose** [lightningnetwork/lnd#381]
lnd crashes right after connecting to a new peer.

This are the logs I get for the crash:
```
2017-10-17 11:39:19.143 [ERR] BRAR: unable to load channel from disk: json: cannot unmarshal
array into Go struct field Vin.txinwitness of type string
2017-10-17 11:39:19.143 [ERR] SRVR: unable to create to start server: json: cannot unmarshal 
array into Go struct field Vin.txinwitness of type string
```

And the stderr output is just this `json: cannot unmarshal array into Go struct field Vin.txinwitness of type string`.

I was on commit f20cb89982e0d9a66cf797383693241bf6c4acb5 when it happened and I suspect that the node that made the connection to me was on that one as well.

**Comment by stevenroose** [comment]
As mentioned on IRC, this happens when pointing lnd at a btcsuite/btcd node instead of one running roasbeef/btcd.

**Comment by Roasbeef** [comment]
Closing.
