### ISSUE TITLE
go.mod in inconsistent state

### ISSUE THREAD

**Issue by setpill** [lightningnetwork/lnd#3830]
`go.mod` contains a dependency on `google.golang.org/grpc v1.18.0` and a dependency on `github.com/grpc-ecosystem/grpc-gateway v1.8.6`; but `github.com/grpc-ecosystem/grpc-gateway v1.8.6` has a dependency on `google.golang.org/grpc v1.19.0`.

**Comment by wpaulino** [comment]
The [current master branch](https://github.com/lightningnetwork/lnd/blob/master/go.mod#L51) has the correct dependency, that being `google.golang.org/grpc v1.19.0`

**Comment by setpill** [comment]
PEBCAK
