### ISSUE TITLE
Master branch requires falafel 0.6 for mobile build

### ISSUE THREAD

**Issue by mandelmonkey** [lightningnetwork/lnd#3856]
### Background

Master branch requires falafel 0.6 for mobile build but it seems that falafel 0.6 does not exist

### Your environment

* version of 
master branch

* which operating system (`uname -a` on *Nix)
Mac OS

* version of `btcd`, `bitcoind`, or other backend
NA
 
### Steps to reproduce
pull master and run make ios

### Expected behaviour

should build 

### Actual behaviour

```falafel version 0.6 required``` is shown

**Comment by wpaulino** [comment]
Have you followed the instructions in https://github.com/lightningnetwork/lnd/tree/master/mobile?

**Comment by mandelmonkey** [comment]
its seems falafel is at 0.6 now so will close
