### ISSUE TITLE
make check error #1

### ISSUE THREAD

**Issue by DaiKen1956** [lightningnetwork/lnd#3869]
### Background

During make check I get this error:

    --- FAIL: TestLightningNetworkDaemon/basic_funding_flow (37.04s)
        lnd_test.go:99: Failed: (basic funding flow): exited with error:
            *errors.errorString unable to create new node: timeout waiting for TLS cert file to be created after 30 seconds
            /root/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:1056 (0xd72a59)
                testBasicChannelFunding: t.Fatalf("unable to create new node: %v", err)
            /root/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:122 (0xd6e43a)
                (*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
            /root/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:14896 (0xdd9c4c)
                TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
            /usr/local/go/src/testing/testing.go:909 (0x50ac89)
                tRunner: fn(t)
            /usr/local/go/src/runtime/asm_amd64.s:1357 (0x460e81)
                goexit: BYTE    $0x90   // NOP
FAIL
FAIL    github.com/lightningnetwork/lnd/lntest/itest    118.844s
FAIL
Makefile:115: recipe for target 'itest-only' failed
make: *** [itest-only] Error 1

### Your environment

* version of `lnd`
lnd version 0.8.0-beta commit=v0.8.0-beta-163-gb222b6e6250be0adea1d880800fde60f6b8695d1

* which operating system (`uname -a` on *Nix)
Linux h2824232.stratoserver.net 4.15.0 #1 SMP Thu Jun 27 15:10:55 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
btcd version 0.20.0-beta

* any other relevant environment details

### Steps to reproduce
make check

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
make check

### Expected behaviour

make check succes

### Actual behaviour

Tell us what happens instead
 make check fail

**Comment by Roasbeef** [comment]
Unable to reproduce this, it might be the case that one of the spawned `lnd` nodes attempted to bind to a port that was already in use.

**Comment by DaiKen1956** [comment]
Issue closed with an answer I don't know what to do with ;-( 
What now? Can somebody please point me in some direction how to solve this?
