### ISSUE TITLE
Channel "Pending" after 100+ confs

### ISSUE THREAD

**Issue by manakill** [lightningnetwork/lnd#3874]
### Background
Opened a channel yesterday. I assumed it opened and sent some sats with no problem. Hours later I noticed the channel was pending still, even though it had been confirmed. I also notice that the original balance of 6.1m has changed - as if the sats I sent went through the channel still Pending.

### Pending Channel Details:
Commit Weight:724
Fee Per Kw:1,568
Commit Fee:1,135
Channel Point:41b7c809d0c115a2578e39c963260d1be3cd96fcd071eb1ab8e6edae8b51fb59:1 
Remote Balance:2,292,568
Local Balance:3,806,296
Remote Node Pub:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f 
Capacity:6,100,000

### Your environment
LND Version: 0.8.0-beta commit=v0.8.1-beta
OS: Linux nodl 4.4.180-rockchip64 #1 SMP Thu Jun 6 08:08:17 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux
Bitcoind: Version: 180100

### Expected behavior

Channel shows Open

### Actual behavior

Channel stuck in Pending, even after many confs
Channel points show in 1ml (node alias: nodl [BVC])

**Comment by molxyz** [comment]
@manakill  Have you restarted the node?  Try that and see if the channel will be active.

**Comment by manakill** [comment]
@molxyz That fixed it! I didn't want to mess anything up trying that ahead of being told to lol. Thanks!!!
