### ISSUE TITLE
How to get xpub

### ISSUE THREAD

**Issue by bota87** [lightningnetwork/lnd#3877]
I'm looking for a way to get the xpub key

**Comment by Roasbeef** [comment]
Not possible with any of the current external RPCs atm. If you have your seed, then you can use the `aezeed` package to decrypt it, and extract the entropy which is used to generate the xpub.

**Comment by zerofeerouting** [comment]
Just a follow up on this old and closed tickets for anybody else that finds this searching (as I did):

As of #4678 it is now possible to retreive both the **ypub** (addresses that start with `3xxx`) as well as the **zpub** (addresses that start with `bc1xxx`) from LND with the command

```
lncli wallet accounts list
```

Hope this helps.
