### ISSUE TITLE
Is there a way to get remote per_commitment_point of an open channel?

### ISSUE THREAD

**Issue by artlav** [lightningnetwork/lnd#3878]
Problem: I got c-lightning, peer got LND, there is a channel open. I lost my node's database and only got the master key.

The private key i would have to use when the peer would unilaterally close a channel is derived (BOLT 3) as `my_payment_basepoint_secret + SHA256(remote_per_commitment_point || my_payment_basepoint)`

payment_basepoint is derivable from my master key, but i need the last per_commitment_point of the peer to recover funds.

So, the question is - how can an LND node operator determine the per_commitment_point of an open channel?

( Related issue on c-lightning side: https://github.com/ElementsProject/lightning/issues/2459#issuecomment-566793415 )

**Comment by guggero** [comment]
There currently is no way to do this with lnd itself.
I added the `dumpchannels` command to my lnd channel tools: https://github.com/guggero/chantools
This will print information about all currently open or pending channels of an lnd `channel.db` file to the console, including the `PerCommitPoint`.

Example from my testnet node:
```
 (chantools.dumpInfo) {
  ChanType: (channeldb.ChannelType) 2,
  ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943,
  FundingOutpoint: (string) (len=66) "ea5a6364947893d1a5ea1a05e2648caca16653a0b81d38e2f2db94cf75e2dbab:0",
  ShortChannelID: (lnwire.ShortChannelID) 1610283:92:0,
  IsPending: (bool) false,
  IsInitiator: (bool) true,
  ChanStatus: (channeldb.ChannelStatus) ChanStatusDefault,
  FundingBroadcastHeight: (uint32) 1610282,
  NumConfsRequired: (uint16) 3,
  ChannelFlags: (lnwire.FundingFlag) 1,
  IdentityPub: (string) (len=66) "03d5e17a3c213fe490e1b0c389f8cfcfcea08a29717d50a9f453735e0ab2a7c003",
  Capacity: (btcutil.Amount) 0.05 BTC,
  TotalMSatSent: (lnwire.MilliSatoshi) 1001175001 mSAT,
  TotalMSatReceived: (lnwire.MilliSatoshi) 0 mSAT,
  PerCommitPoint: (string) (len=66) "0303a7a2c20a91575148c8aab7e7cdc590807a9f9f6d8c11782f542a857502eb40",
  LocalChanCfg: (chantools.dumpChanCfg) {
   ChannelConstraints: (channeldb.ChannelConstraints) {
    DustLimit: (btcutil.Amount) 0.00000573 BTC,
    ChanReserve: (btcutil.Amount) 0.0005 BTC,
    MaxPendingAmount: (lnwire.MilliSatoshi) 4950000000 mSAT,
    MinHTLC: (lnwire.MilliSatoshi) 1000 mSAT,
    MaxAcceptedHtlcs: (uint16) 483,
    CsvDelay: (uint16) 600
   },
   MultiSigKey: (chantools.dumpDescriptor) {
    Path: (string) (len=17) "m/1017'/0'/0'/0/6",
    Pubkey: (string) (len=66) "02801e3f7ab31ff3ddba91f3c09816ebb4511e58c63d7f23204194babce5565490"
   },
   RevocationBasePoint: (chantools.dumpDescriptor) {
    Path: (string) (len=17) "m/1017'/0'/1'/0/6",
    Pubkey: (string) (len=66) "0269e350263b24c1cd125f5a49df9d3e4be659dff12318374d10dc9d1ebd670323"
   },
   PaymentBasePoint: (chantools.dumpDescriptor) {
    Path: (string) (len=17) "m/1017'/0'/3'/0/6",
    Pubkey: (string) (len=66) "03bc0dc1cf7e84a78d75fc102504cfd1a4b42df798f7acfa21edc2237d490de2f8"
   },
   DelayBasePoint: (chantools.dumpDescriptor) {
    Path: (string) (len=17) "m/1017'/0'/4'/0/6",
    Pubkey: (string) (len=66) "03a3d284670ca274158b1b1f15f603d5e81a037d4f86800012d73730fb5d348523"
   },
...
```

**Comment by artlav** [comment]
Should chantools be run with LND stopped? 

They seem to be getting a `panic: freepages: failed to get all reachable pages (page 57170: multiple references)` error.

**Comment by guggero** [comment]
Yes, I forgot to write that lnd must be stopped before running that command.

**Comment by Roasbeef** [comment]
Closing this as a tool is available to obtain this data. Ultimately, this is an issue with c-lightning, as they should continue to send their per commitment point until the channel has been fully resolved on-chain.
