### ISSUE TITLE
Missing port number in doc

### ISSUE THREAD

**Issue by infertux** [lightningnetwork/lnd#388]
The command under https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#running-lnd-in-light-client-mode is missing the port number and fails with the following message:

```
unable to create chain control: unable to create neutrino: address faucet.lightning.community: missing port in address
unable to create neutrino: address faucet.lightning.community: missing port in address
```

**Comment by aakselrod** [comment]
This is fixed in https://github.com/lightninglabs/neutrino/pull/19 allowing a peer address to be specified without a port.

**Comment by infertux** [comment]
Great. Closing it then.
