### ISSUE TITLE
lncli sendcoin help incomplete/outdated/wrong?!

### ISSUE THREAD

**Issue by frennkie** [lightningnetwork/lnd#3883]
### Background

Running `lncli sendcoins --help` lists that the  option `--addr` takes "the **BASE58** encoded bitcoin address to send coins to on-chain".

I assume BASE58 refers to the address formats for P2PKH and P2SH address (https://en.bitcoin.it/wiki/Address) - starting with 1 or 3 on mainnet.

This would exclude the usage of Bech32 (https://en.bitcoin.it/wiki/List_of_address_prefixes) - starting in bc1. But `lncli` is perfectly fine with using a Bech32 address. So I think the DESCRIPTION and the OPTIONS text should be revised.

### Your environment

* version of `lnd`: lncli version 0.8.2-beta commit=v0.8.2-beta

### Steps to reproduce

Run `lncli sendcoins --help`

**Comment by Roasbeef** [comment]
Yep, just an oversight in the documentation.

**Comment by cfromknecht** [comment]
we should be able to address this by 0.9
