### ISSUE TITLE
Project page is not updated correctly

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#3895]
Hi,
It seems that the project page is not updated correctly, there is not v10 projects, and some issues that are in v10:
(for example - https://github.com/lightningnetwork/lnd/pull/3601)
are shown in the v9 project page:
https://github.com/lightningnetwork/lnd/projects

**Comment by guggero** [comment]
There are two different kind of elements we use for development: milestones and projects.
Milestones are for more general, long-term planning/scheduling of issues and PRs. The project board is used for tracking the next upcoming version while it's in development.
Therefore it is correct that the milestone `0.10.0` already exists while the project `0.10.0` does not as long as `0.9.0` is not yet final (or at least in RC).

**Comment by Roasbeef** [comment]
there's a v10 board now ;)
