### ISSUE TITLE
unable to find a path to destination after stopping and restarting lnd's one by one.

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#3901]
### Background

I have 3 nodes running on different vm's with next configuration(Nodes A, B, C):

```noseedbackup=1
no-macaroons=1
rpclisten=localhost:10002
listen=localhost:10012
restlisten=8002
datadir=data_btc_regtest
logdir=logs_btc_regtest
nobootstrap=1
bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind
bitcoind.rpcuser=user
bitcoind.rpcpass=pass
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
maxpendingchannels=20
chan-enable-timeout=1m
debuglevel=debug
```

Both A and C have direct channels with node-B.
Both are sending payments to each other via node-B.

After executing steps described below, node-A has no route to node-C as channel between B-C is recognized as disabled from node-A point.

### Your environment

* version of lnd: 0.9.0-beta commit (can be reproduced on older versions too)
* version `bitcoind`: latest master 

### Steps to reproduce

1. Stop node-C, wait 20 minutes(chan-disable-timeout), then node-C channels become disabled for nodes A, B.
2. Stop node-A.
3. Reopen node-C, waiting 1 minute(my custom chan-enable-timeout) to receive an announcement that node-C channels are active again.
4. Reopen node-A, expecting that it will receive notifications about the current network state.
5. From node-A: run queryroutes to <node-C_pubkey>. 
6. From node-A: run getchaninfo <node-C_channel_id> to check whether the channel becomes enabled.

### Expected behavior

5. Route from A to C with hop on node-B.
6. getchaninfo shows channel is enabled.

### Actual behaviour

After waiting for hour on both mainnet and regtest:
5. queryroutes result: [lncli] rpc error: code = Unknown desc = unable to find a path to destination
6. getchaninfo: node-B policy: "disabled": true,

**Comment by wpaulino** [comment]
> Stop node-A.
Reopen node-C, waiting 1 minute(my custom chan-enable-timeout) to receive an announcement that node-C channels are active again.
Reopen node-A, expecting that it will receive notifications about the current network state.

Node A doesn't receive the update because it was sent while it was offline, so it'll need to wait for the next update to go out. `lnd` currently doesn't attempt to sync historical updates anymore as it proved to cause an influx of incoming gossip from the network. There's a protocol extension that we've yet to implement however that allows us to sync historical updates for select channels, so that's a possible route.

**Comment by RostyslavAntonyshyn** [comment]
> so it'll need to wait for the next update to go out.

I understand this, but another question is, when should lnd receive this next update? As I can see update is sent in 'reenableActiveChannels' once per each peer. As well as ChannelUpdate msg is received once.

So if peer was offline at that moment, it won't receive the update. (In case when I leave the nodes active and do nothing with them).

**Comment by wpaulino** [comment]
> I understand this, but another question is, when should lnd receive this next update?

A new update with an updated timestamp is sent every 24H, so the node would have to wait until then.
