### ISSUE TITLE
[mobile] grpc: no transport security set

### ISSUE THREAD

**Issue by ealymbaev** [lightningnetwork/lnd#3905]
### Background

I have launched LND on iOS via `gomobile` and all your instructions (using falafel). I am able to start LND node and see all logs. But I cannot make any gRPC requests because of the following error:

`Error Domain=go Code=1 "grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)" UserInfo={NSLocalizedDescription=grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)}`

### Your environment

Also please note that I am using new `nio` branch of `grpc-swift` as they recommend.

* version of `lnd`:  lnd v0.9.0-beta-rc1
* which operating system (`uname -a` on *Nix): OSX
* version of `btcd`, `bitcoind`, or other backend: Neutrino
* any other relevant environment details

### Steps to reproduce

`LndmobileStart` succeeds and I see all the logs. But any gRPC request (`LndmobileInitWallet` or `LndmobileGenSeed`) does fail with the error above.

**Comment by ealymbaev** [comment]
I have also created related issue on `grpc-swift` repo:

https://github.com/grpc/grpc-swift/issues/694

**Comment by wpaulino** [comment]
Should be fixed by https://github.com/lightningnetwork/lnd/pull/3907.
