### ISSUE TITLE
Sending payment with 2+ hops fails

### ISSUE THREAD

**Issue by mrwhythat** [lightningnetwork/lnd#391]
After merging latest changes  to my branch for #372 , `testPaymentPathConstraint` test, which tries to use 2 hops, started failing, so I modified `testMultiHopPayments` to add David, forming the topology **Carol -> David -> Alice -> Bob** with the following:

```go
	david, err := net.NewNode(nil)
	if err != nil {
		t.Fatalf("unable to create new nodes: %v", err)
	}
	if err := net.ConnectNodes(ctxb, david, net.Alice); err != nil {
		t.Fatalf("unable to connect david to alice: %v", err)
	}
	err = net.SendCoins(ctxb, btcutil.SatoshiPerBitcoin, david)
	if err != nil {
		t.Fatalf("unable to send coins to david: %v", err)
	}
	ctxt, _ = context.WithTimeout(ctxb, timeout)
	_ = openChannelAndAssert(ctxt, t, net, david,
		net.Alice, chanAmt, 0)

	carol, err := net.NewNode(nil)
	if err != nil {
		t.Fatalf("unable to create new nodes: %v", err)
	}
	if err := net.ConnectNodes(ctxb, carol, david); err != nil {
		t.Fatalf("unable to connect carol to david: %v", err)
	}
	err = net.SendCoins(ctxb, btcutil.SatoshiPerBitcoin, carol)
	if err != nil {
		t.Fatalf("unable to send coins to carol: %v", err)
	}
	ctxt, _ = context.WithTimeout(ctxb, timeout)
	chanPointCarol := openChannelAndAssert(ctxt, t, net, carol,
		david, chanAmt, 0)
```

This causes the test failure with the following error message:
```json
{
    	"payment_error": "Unable to apply channel update: Ignoring announcement (flags=1) for known chan_id=444202697687040",
    	"payment_preimage": "",
    	"payment_route": null
}
```

Some digging showed that the problem is with `FailFeeInsufficient` wire error, which is silently turned into this channel update error.

**Comment by mrwhythat** [comment]
Also, there seems to be no tests for multi-hop payments with more than one intermediary.

**Comment by Roasbeef** [comment]
There're unit tests that cover that case, more or less, it's identical to any other multi-hop test as the intermediate nodes follow the exact same logic. 

Have you seen this commit (https://github.com/lightningnetwork/lnd/commit/3e64ba0394d6dc709e31cf81eca554617eb110d1)? I think you might need to modify your test (or perhaps made a mistake during the merging) to ensure that it uses the returned payment request from the invoice, rather than manually specifying the payment hash.

**Comment by mrwhythat** [comment]
I'll take a look tomorrow, but examples I listed here reproduce on `master`. Also, as my test uses `lncli` directly, I do use payment request from the invoice with `--pay_req`.

**Comment by Roasbeef** [comment]
Thanks for the details! I'm looking into this now. I recently modified the sphinx payload generation to accommodate a recent change within the specification and fixed an existing bug with our fee calculation along the way. It's possible I introduced a regression in the process. I'll reproduce this using your posted code fragment, and will likely be able to get a fix up in short order.

**Comment by mrwhythat** [comment]
@Roasbeef thanks for the fix, now I can fix my payment path constraints.
