### ISSUE TITLE
can't create wallet in fresh lnddir

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lnd#3912]
Ubuntu 18.04, go 1.13.4 linux/amd64, daa08be62ae8dda0b81f975d0af9b53a3cab2dc4

The recent TLS commits seem to have broken creation of new wallets:

```
% ./lncli-debug -n regtest --lnddir=/tmp/lnd1 create
[lncli] open /tmp/lnd1/tls.cert: no such file or directory
% ls /tmp/lnd1
ls: cannot access '/tmp/lnd1': No such file or directory
```

Of course the certificate doesn't exist, this is a completely fresh installation. Am I supposed to do this differently now?

**Comment by wpaulino** [comment]
Those commits don't affect the creation of the TLS files. The TLS files are created by invoking `lnd`, so you'll want to run `lnd --lnddir=/tmp/lnd1`.

**Comment by ysangkok** [comment]
These commits have to change something about this behaviour, because if I use commit a0639c234f072a1d77e64648becc941f7c9c38ae, I can omit lnddir for lnd-debug and use it only for lncli. But it sounds my previous usage was wrong, and it is therefore ok that this now errors, so I will close.
