### ISSUE TITLE
How to add hold invoice through REST proxy?

### ISSUE THREAD

**Issue by thomaseizinger** [lightningnetwork/lnd#3913]
### Background

I am trying to integrate with LND via the REST proxy for the purpose of atomic swaps.

I would like to add a hold invoice to lnd via the REST API, yet I can't seem to find any documentation on how to actually do that. The most I could find was this wiki page which only refers to the CLI: https://lightningwiki.net/index.php/HODL_Invoice

How can I add add a new hold invoice to LND via the REST proxy? I would like to avoid the gRPC API if possible.

### Your environment

* version of `lnd`: lnd version 0.9.0-beta commit=v0.9.0-beta-rc1 (compiled with `tags="invoicesrpc"`)
* which operating system (`uname -a` on *Nix): Linux thomas-ThinkPad-T480 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: btcd version 0.20.1-beta
* any other relevant environment details

### Steps to reproduce

- Go to https://api.lightning.community/rest/index.html#lnd-rest-api-reference
- Search for 'hold' yields no results that point to ways how to do this

### Expected behaviour

A HTTP endpoint that allows me to register a hold invoice.

### Actual behaviour

Can't find an endpoint in the documentation to do this.

**Comment by guggero** [comment]
The RPC you are looking for is implemented in one of the experimental sub-servers (hence the required tag `invoicesrpc`). For these sub-servers we don't currently use the REST proxy and they are only available through gRPC.

**Comment by thomaseizinger** [comment]
> The RPC you are looking for is implemented in one of the experimental sub-servers (hence the required tag `invoicesrpc`). For these sub-servers we don't currently use the REST proxy and they are only available through gRPC.

Thanks for your answer!

Where can I find the documentation for the experimental gRPC services?
What is the plan in regards of stabilization of this experimental feature?

**Comment by guggero** [comment]
I don't think there is any documentation other than the proto files themselves. They are located in sub folders of the `lnrpc` directory. For example, what you are looking for is in https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/invoices.proto
I can't speak to the stabilization plans as I don't know. Experimental mostly means we don't respect backward compatibility as much as we try to in the main RPC. Using the sub-servers might mean you need to change your code every once in a while.
If you're writing something in go you could also use the `lndclient` library of loop, it's the native client library for our RPCs that we try to keep up to date (at least with what we use it for in our other projects).

**Comment by thomaseizinger** [comment]
Thank you! The proto file should be enough to get going! :)

> If you're writing something in go you could also use the lndclient library of loop, it's the native client library for our RPCs that we try to keep up to date (at least with what we use it for in our other projects).

We are using Rust but thanks for the hint!
