### ISSUE TITLE
Pending channels stuck even after restart - Unable to rebroadcast funding tx

### ISSUE THREAD

**Issue by danielalexiuc** [lightningnetwork/lnd#3919]
### Background

I have 6 channels stuck in PENDING_OPEN state, they all seem to have similar messages in the logs.

These have been pending open for several weeks, and were opened in a previous version of LND: 0.7.1

### Your environment

LND 0.8.2-beta
Bitcoin core 0.19.0.1

### Log messages

Here are the relevant logs for one of the channels, all the others have similar log messages.

`2020-01-16 00:54:44.153 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b:1): Transaction rejected: output already spent`

`2020-01-16 00:54:44.153 [INF] LNWL: Inserting unconfirmed transaction b4867af801936bdb197a77986c00e3d8fb6514964b45d281910776b3604e8801`

`2020-01-16 00:54:44.156 [INF] NTFN: New confirmation subscription: conf_id=1, txid=293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b, num_confs=1 height_hint=613028`

`2020-01-16 00:54:44.156 [INF] FNDG: Waiting for funding tx (293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b) to reach 1 confirmations
`

`2020-01-16 02:56:08.193 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b:1)`

`2020-01-16 02:56:08.194 [ERR] FNDG: Unable to advance pending state of ChannelPoint(293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b:1): error waiting for funding confirmation for ChannelPoint(293478046cb0541fec119b01ff9cfc0c2fec587a9a30347eec5904a6bf3fa70b:1): waiting for fundingconfirmation failed`

**Comment by wpaulino** [comment]
Do you have any instances of `Unable to broadcast funding tx` in your logs? It's likely that the transaction is double spending an output.

**Comment by ysangkok** [comment]
The first log line Daniel posted says "output already spent". Does that answer your question Wilmer?

**Comment by wpaulino** [comment]
@danielalexiuc you'll need to force a wallet rescan following the instructions in https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan. You'll also want to obtain a debug build of `lnd` with `make install tags=dev` and use the `lncli abandonchannel` on these pending channels. You should only abandon them if the transaction is indeed double spending an output.

**Comment by danielalexiuc** [comment]
Thanks - but I'm less interested in fixing my specific problem than I am in fixing the issue properly in LND for everybody else though (including my future self).

Can I help out with any more diagnostic logging?

**Comment by wpaulino** [comment]
There are two issues at hand:

1. The wallet is not tracking outputs correctly.
2. `lnd` doesn't check whether the inputs provided for the channel are unspent.

For 1, there are no known unresolved instances at the moment. For 2, we haven't implemented it yet. What I outlined above is the best solution for now.

**Comment by Overtorment** [comment]
@wpaulino how can I make sure that tx is doublespending?  I did a rescan for land with `dropwtxmgr`, and the pending open channel is still there, however the funding tx cannot be observed in mempool:


```
    "pending_open_channels": [
        {   
            "channel": {
                "remote_node_pub": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
                "channel_point": "ea4490bef2350bbc89913f4b19a64bf1c938be9a0a96ce1d1fc5a56f7a85a9c8:0",
                "capacity": "16777215",
                "local_balance": "16768165",
                "remote_balance": "0",
                "local_chan_reserve_sat": "167772",
                "remote_chan_reserve_sat": "167772",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "9050",
            "commit_weight": "600",
            "fee_per_kw": "12500"
        },
```

**Comment by wpaulino** [comment]
If it's not in the mempool or chain, then it's likely an invalid channel. You can confirm if you see any failed broadcast attempts for the funding transaction.

**Comment by Overtorment** [comment]
@wpaulino thanks! should I first abandon the channel and then do the rescan or vice versa?

**Comment by wpaulino** [comment]
Another rescan is not necessary if you've already done one, just abandoning the channel should be enough.

**Comment by wpaulino** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3919#issuecomment-575765780. There's already an existing issue tracking this: https://github.com/lightningnetwork/lnd/issues/386.
