### ISSUE TITLE
Channels I closed with 'closechannel' are stuck in 'pending_force_closing_channels'

### ISSUE THREAD

**Issue by Haaroon** [lightningnetwork/lnd#3923]
### Background

I opened two channels a few days ago then I closed them normally via the cli using `closechannel`. Both of them are stuck in `pending_force_closing_channels` but I did not force close them. Unfortunately now all my btc is stuck. This is for mainnet. 

```
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
                "channel_point": "3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1",
                "capacity": "16777215",
                "local_balance": "16773742",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "closing_txid": "d14b171932754fbd8644a85d3f0da77a62dfccb25cb86a7357b6429cd60dd426",
            "limbo_balance": "16773742",
            "maturity_height": 615234,
            "blocks_til_maturity": 1976,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },
        {
            "channel": {
                "remote_node_pub": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                "channel_point": "769d2d197126d2e16cab80850490e97611c2dcc68b2791c9e72cfcf915fe6a82:1",
                "capacity": "13068664",
                "local_balance": "13052263",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "closing_txid": "e4de8e3022eb07f00a865d89f5be7b24aae4ecbc48424bcb973c3e3825635688",
            "limbo_balance": "13060036",
            "maturity_height": 614629,
            "blocks_til_maturity": 1371,
            "recovered_balance": "0",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "7773",
                    "outpoint": "965366e67f9ce459b9575056af6772d79e9be74ace36347c99b823e17ab1d788:0",
                    "maturity_height": 614630,
                    "blocks_til_maturity": 1372,
                    "stage": 2
                }
            ]
        }
    ],
```

### Your environment

* lnd version `Version: 0.9.0-beta commit=v0.9.0-beta-rc2, build=production, logging=default`
* OS:`Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` (CentOS)
* `bitcoind` `190001`

### Steps to reproduce

* Open a channel
* Run closechannel

### Expected behaviour

* Channel should close normally?

### Actual behaviour

* Channels got stuck in this `pending_force_closing_channels` state

### Log files

Here is the log file when I start the lnd node with `--debuglevel=LNWL=trace,CNCT=trace,FNDG=trace,UTXN=trace` 
[lnd.log](https://github.com/lightningnetwork/lnd/files/4076573/lnd.log)

**Comment by peername** [comment]
> "blocks_til_maturity": 1976
> "blocks_til_maturity": 1371

You have to wait for this time to expire. Next time, check the opposite node for the period **time_lock_delta**.

**Comment by Haaroon** [comment]
Why? I did not force close the channels.

**Comment by guggero** [comment]
The unexpected behavior here is that the channels didn't cooperatively close. Do you still have the logs from when you did the `closechannel` command?

As @peername explained, now that the channels have been force closed, you need to wait for the time lock to expire.

**Comment by Haaroon** [comment]
And  how come the one of the closing got spent but mine isnt?

**Comment by guggero** [comment]
> And how come the one of the closing got spent but mine isnt?

Because the remote output of a commitment transaction is not time locked, only the local one. See https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#to_local-output

**Comment by Haaroon** [comment]
Ok thanks for clarifying, here is the full log from the night for both of the transactions. 

I belive I initated this closure after 04:00:00
[lnd_tx1.log.gz](https://github.com/lightningnetwork/lnd/files/4077225/lnd_tx1.log.gz)

This I believe initated after 23:00:00
[lnd_tx2.log.gz](https://github.com/lightningnetwork/lnd/files/4077228/lnd_tx2.log.gz)

**Comment by guggero** [comment]
Thanks! I found the relevant parts for the first channel (`3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1`):

```
2020-01-17 00:16:43.163 [INF] PEER: Ideal fee for closure of ChannelPoint(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1) is: 2557 sat
2020-01-17 00:16:43.164 [INF] PEER: ChannelPoint(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1): initiating shutdown of
2020-01-17 00:16:43.164 [INF] NANN: Announcing channel(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1) disabled [requested]
2020-01-17 00:16:43.347 [INF] HSWC: Removing channel link with ChannelID(35cf3892640642d2411c4d098b5879ba2c0ed71700861269e6fe215b5317d33c)
2020-01-17 00:16:43.347 [INF] HSWC: ChannelLink(613107:2689:1): stopping
2020-01-17 00:16:43.447 [INF] HSWC: ChannelLink(613107:2689:1): exited
2020-01-17 00:16:43.447 [INF] PEER: ChannelPoint(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1): sending shutdown message
2020-01-17 00:16:43.447 [DBG] PEER: Sending Shutdown(chan_id=35cf3892640642d2411c4d098b5879ba2c0ed71700861269e6fe215b5317d33c, script=0014d5d8d528e42b8225d73917504981e04c296735c4) to 020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b@82.197.218.97:9735
2020-01-17 00:16:43.645 [DBG] PEER: Received Shutdown(chan_id=35cf3892640642d2411c4d098b5879ba2c0ed71700861269e6fe215b5317d33c, script=0014debe08fdcf6689f6e6ebddd897e96c707e1a23fe) from 020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b@82.197.218.97:9735
2020-01-17 00:16:43.645 [INF] PEER: ChannelPoint(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1): shutdown response received, entering fee negotiation
2020-01-17 00:16:43.668 [INF] PEER: ChannelPoint(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1): proposing fee of 2557 sat to close chan

...

2020-01-17 04:48:41.025 [INF] CNCT: ChannelArbitrator(3dd317535b21fee66912860017d70e2cba79588b094d1c41d24206649238cf35:1): force closing chan
```

It looks like the remote peer never answered to the shutdown message.

**Comment by Haaroon** [comment]
Thank you very much for finding this,  this issue seems to very common, most nodes seem to be offline or  go offline very soon,its a shame to have the funds locked.

**Comment by guggero** [comment]
We'll look into this further. It could be a version interoperability problem as you updated to `v0.9.0-beta-rc2`. Could also be the other node misbehaving.
You are sure you never manually issued any force close command, right?

**Comment by Haaroon** [comment]
Thank you. I doubt its a version problem as I had this issue for the entire time, so I decided to update in the hope that it would fix the issue but it seems to have no effect.

I am  sure that I did not manually issue the `-force` command however, when I ran the `closechannel`  command  the terminal window never returned a response. It just hung. After 4 hours my machine disconnected from the terminal  instance. So  there is a possiblity that after those 4 hours, the lnd client replied with the `do you want to foce close message` and since my terminal window had been long closed, it likely default is to say yes?

**Comment by Haaroon** [comment]
The funds have been released, so I do not have an issue anymore, though I still havent been able to figure out an alternative reason to the one above.
