### ISSUE TITLE
lnwallet+keychain: tighten up signing abstractions by removing all raw private key handling

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3929]
Long term, we'd like to support use cases such as #3585 that allow more secure signing within `lnd` itself. As is today, we have the interfaces in the `keychain` package, as well as the `Signer` which already abstract away things like key derivation and signing. However, in several areas we use [this method to obtain a _raw_ private key for direct manipulation](https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go#L179). This is clearly incompatible with something like a hardware wallet, which aims to protect against all types of key exfiltration. Therefore, to support more secure signing, we need to _remove_ all usages of that method, reducing the number of total method in the `SecretKeyRing` interface to one. 

For more details w.r.t our long-term plan to support more secure signing, [please see this post on the lnd-dev mailing list](https://groups.google.com/a/lightning.engineering/d/msg/lnd/3rF65UxvDtM/ktDLAGtlAQAJ). 

We'll need to remove raw private key handling from the following areas:

# Steps To Completion 

- [x] The brontide handshake. Currently we pass the entire private key into the brontide state machine. However, it can get by with simply being able to perform an ECDH against our long-tern static identity key. From there on, it can carry out the remainder of the handshake using this resulting state, as well as the ephemeral key it generates for the handshake. The current [SecretKeyChain](https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go#L170) interface already has a [ScalarMult](https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go#L186) method which is meant to be used for ECDH, so we have that base covered already.

- [x] The watch tower's brontide handshake. Same thing as the above, just uses a distinct key for any created watch towers.

- [x] ~SCB blob encryption/decryption. When creating the SCB format, we didn't want to require that some future external singing abstraction had to be aware of the encryption scheme we used. As a result, we ended up obtaining the raw private key, and using that directly for encryption/decryption. Instead, we can start to use the ECDH method from the SecretKeyRing interface to obtain a new shared secret which is then used directly. We can bump the SCB version (the Multi specifically) to handle the transition from the old to the new format.~
Not needed, the SCB decryption key is derived from the _public_ key.

- [ ] [The channel's revocation root key](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L808). The private key is used directly as the input of `shachain.NewRevocationProducer`. This could be replaced by deriving a "shared" key against one of our other public keys and use that shared key (ECDH) hash instead. But that would only work for new channels. Needs to be considered when implementing https://github.com/lightningnetwork/lnd/issues/2659.

**Comment by Roasbeef** [comment]
Fixed by #4517. 

Where we're going, we won't need hot keys!

**Comment by GlenCooper** [comment]
![giphy](https://user-images.githubusercontent.com/967793/110194246-7ff11200-7e2f-11eb-93d1-884b88792d8d.gif)

**Comment by devrandom** [comment]
Yay!!
