### ISSUE TITLE
support to bitcoind and mainnet

### ISSUE THREAD

**Issue by kiahmed** [lightningnetwork/lnd#393]
Hi, new to LN , wonder if it'd support the mainnet to try out a real working example also can I configure with bitcoind running on a separate server over RPC? Or is it only hard coded to btcd? I have bitcoind full node that wanted to use but setting up a complete new btcd node and syncing everything would be nightmare now

**Comment by rodasmith** [comment]
For now, it is a specific build of btcd on testnet. It's pretty easy to set it up on testnet if you follow https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

**Comment by Roasbeef** [comment]
`bitcoind` support will be added once the in-progress PR for #21 is up. 

Closing.
