### ISSUE TITLE
Rename last_hop_pubkey to last_hop_pub_key

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#3930]
The QueryRoutesRequest parameter `last_hop_pubkey` introduced in https://github.com/lightningnetwork/lnd/pull/3911/files#diff-f6ec8c0f52caccfaec5656028d316c7fR2059 does not match the name pattern used for other parameters (`pub_key` and `source_pub_key`). If possible, rename to `last_hop_pub_key`.

**Comment by C-Otto** [comment]
@joostjager maybe this one is for you?

**Comment by C-Otto** [comment]
It's also confusing to have `byte` here and `string` for the other public keys. Is that intentional?

**Comment by sako0938** [comment]
About last_hop_pubkey vs last_hop_pub_key, I personally like last_hop_pubkey, but I have noticed many other places in the api where pub_key by itself is used:
14 occurrences of pub_key
52 occurrences of pubkey

I also think the byte vs string thing is kind of confusing.

I understand converting to base64, but also converting to bytes is a step that isnt super obvious what it means, even though the docs do say "bytes" type.
First Example: I convert string to a python "byte string"
```
>>> bdata['last_hop_pubkey'] = base64.b64encode('02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c'.encode('UTF-8') ).decode()
>>> bdata['last_hop_pubkey']
'MDIwMDRjNjI1ZDYyMjI0NTYwNmExZWEyYzFjNjljZmI0NTE2YjcwM2I0Nzk0NWEzNjQ3NzEzYzA1ZmU0YWFlYjFj'
>>> lnreq = requests.post(url, headers=headers, verify=cert_path, data=json.dumps(bdata))
>>> lnreq.text
'{"error":"invalid vertex length of 66, want 33","message":"invalid vertex length of 66, want 33","code":2,"details":[]}'
```
That doesnt work, but converting hex to bytearray object does work.
```
bdata['last_hop_pubkey'] = base64.b64encode(bytes.fromhex('02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c')).decode()
```

**Comment by halseth** [comment]
I agree that we should strive to have consistent naming on the RPC, but as an open source project having hundreds of different contributors, this is sometimes hard.

For this exact case, now that a name has been chosen, changing it would break users of the RPC, so easiest to just stick with it.
