### ISSUE TITLE
Escrow service possible? (Multi Signature LND Wallet)

### ISSUE THREAD

**Issue by snapo** [lightningnetwork/lnd#3933]
It is more of a technical question or maybe a hint from the community to put me in the right direction. There are 3 partys (A,B,Escrow)

A and B do not trust Escrow
A does not trust B
B does not trust A

If A wants to send funds to B is it somehow possible to create a multisig lighnting wallet? with (2-N) signatures?

Thanks for a hint in the right direction....

**Comment by Roasbeef** [comment]
Multi-sig: no, multi-payhash: yes. However, this isn't implemented in any existing LN implementation, and also isn't a part of the current spec.

**Comment by tlindi** [comment]
@Roasbeef is the situation still the same? Would like to create LND with 2-of-3 multisign.
