### ISSUE TITLE
channeldb/kvdb: implement etcd backend for new `kvdb` abstraction 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3934]
This PR depends on #3833. The goal of this PR is to implement the first backend for `lnd` that supports replicated storage of (initially) all user data. We may first only opt to replicate the critical portions (channel state, invoices, etc), and leave information like the graph (which can be re-synced from the p2p network as will local). Similarly, if the node is running with the neutrino backend, then all the chain state data can also remain locally on disk, as there's no system wide synchronization required. 

# Steps to Completion 

- [x] Select amongst the possible options outlined in [this comment](https://github.com/lightningnetwork/lnd/pull/3833#issuecomment-575776196) w.r.t the concrete implementation of the `kvdb` abstraction interface. 
- [x] As `etcd` is already a KV-store, we don't need to do anything like map an table structure into this more freestyle schema. Instead, we'll need to implement the existing "bucket" abstraction, which is essentially just a series of nested maps or namespaces. See [this bucket implementation within `btcd` for level db as inspiration](https://github.com/btcsuite/btcd/blob/master/database/ffldb/db.go#L562). 
- [x] Once the backend has been implemented, [we should ensure that the backend passes the existing set of tests within the `walletdb` package](https://github.com/btcsuite/btcwallet/tree/master/walletdb/walletdbtest). 
- [x] After the above step is complete, we'll then need to start integrating the new backend directly into `lnd`. This will likely require a new configuration namespace to configure all the relevant parameters required to connect to an `etcd` instance. The database should work for both a local instance as well as a set of instances behind a proxy in a clustered configuration.

**Comment by cfromknecht** [comment]
closed as of #4015
