### ISSUE TITLE
funding: PSBT based external channel funding capabilities 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3936]
Related to #3085. Now that we have our set of funding abstractions implemented within `lnd`, we can expose a much higher level (and safer!) RPC interface for our users. The end goal here is to be able to _initiate_ channel funding within lnd (negotiation of parameters, keys, etc), the mid-way through carry out an interactive protocol with an _external_ wallet to obtain signed inputs to _fund_ the new channels. 

Some ground work has already been laid here as [`btcutil` now has a feature complete (and `bitcoind` compatible) PSBT package](https://godoc.org/github.com/btcsuite/btcutil/psbt). The work in this issue will be to leverage some yet to be created `btcwallet` APIs (useful for testing) to create a new funding flow for PSBT based funding within `lnd`. 

# Steps to Completion 

- [ ] Create a _new_ [`chanfunding.Assembler`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/chanfunding/assembler.go#L112), and [`chanfunding.Intent`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/chanfunding/assembler.go#L83) which will house the new logic for this new type of funding shim within the codebase. 

- [ ] A likely location for the new more interactive funding protocol is likely the new `chanfunding.Intent` to be created. As we don't need to perform coin selection ourselves, the `chanfunding.Assembler` will mostly just be constructing the funding transaction once we have the relevant inputs. 

- [ ] From there a new multi-step protocol will need to be constructed within the wallet and the RPC interface. A possible outline may look something like this:
    1. User initiates funding with a new `FundingShim` which specifies that they wish to have the funding input selection and signing take place _outside_ of `lnd`. 
    2. We carry out the normal funding flow right up to the point [that we need to obtain the funding transaction](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L843). Using the new abstractions, we'll now carry out an interactive protocol to create a PSBT w/ no inputs (only funding output present), present that to the user for funding and signing, then finally verify the validity of the created funding transaction before proceeding. 
    3. Extend the current [`FundingStateStep`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L447) method to expose a new state machine to implement the protocol outlined above. A set of sample transition messages may resemble something along the lines of:
        * `FundingPsbtCreate` -> takes the `pendingChanID` used earlier and returns our PSBT template for the funding transaction. 
        * `FundingPsbtComplete` -> takes the `pendingChanID`, and the completed serialized PSBT packet, then progresses the funding flow. 
    4. Put it all together and we'll be able to use `lnd` to fund channel directly from any wallet (even hardware wallet) that supports PSBT!

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/4079.
