### ISSUE TITLE
rpc+docs: update set of external auto-generated documentation to also support sub-servers

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3937]
[This really belongs in this repo](https://github.com/lightninglabs/lightning-api), but `lnd` is more active so we'll be tracking it here instead. 

We have our current dev docs which can be found at api.lightning.community that we all know and love. However, these docs haven't yet been updated to also cover the set of RPC sub-severs. As these sub-servers are starting to become more and more fully featured, we make available the same level of documentation we have for the rest of the RPC interface.

**Comment by wpaulino** [comment]
This is now addressed. See https://api.lightning.community/#lnd-grpc-api-reference.
