### ISSUE TITLE
routing+invoices: implement AMP secret sharing and combination 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3939]
This issue is related to https://github.com/lightningnetwork/lightning-rfc/pull/658. Completion of this issue entails creating a new `secretshare` package (naming suggestion) within `lnd` that's able to:
  * Statically create a set of N shares for apriori splitting use cases. 
  * Dynamically create a set of N shares (incrementally or adaptively) fo more adhoc splitting use case. 
  * Combine the relevant shares and perform key derivation to produce preimages and payment hashes related to an ultimate payment 

Once the above is done (the libraries at the edges), we'll also need to then integrate this new _combination_ logic into the invoice registry. Along the way we'll likely opt to create some sort of new HTLC combination+settling (deciding _when_ it's possible to combine and also how to derive the pre-images) within the invoice registry. 

I've left out most of the details w.r.t the additive secret sharing scheme as those are elaborated upon in detail within the linked issue. One other thing I've left out of this is the implication on the RPC interface, for calls such as `ListPayments` and `ListInvoices`.

**Comment by cfromknecht** [comment]
Closed by #4162
