### ISSUE TITLE
BTCD Deprecation

### ISSUE THREAD

**Issue by jakesyl** [lightningnetwork/lnd#3956]
### Background

I saw an issue raised on btcd that's pretty relevant here considering [btcd(https://github.com/btcsuite/btcd/) was the first implementation supported and continues to be used in the lnd library (for serialization/deserialization which shouldn't cause any issues directly).

@matt24smith raised btcsuite/btcd#1520 which raises concerns over btcd's ability to keep up with new blocks. I'm not advocating for deprecating it, but I do think a discussion is warranted for the reasons enumerated above. Is this something we should act on?

**Comment by Roasbeef** [comment]
Not the proper location for this issue. That linked issue is also hyperbolic, between this year and the last, even with chain size expansion `btcd` synced the chain in _less_ time.
