### ISSUE TITLE
Is it possible to recover LNWL: Unable to complete chain rescan: -1: Block not available (pruned data)?

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#3968]
### Background

I left lnd down for too long accidentally because I forgot to enter the password (#899 is really pain). Now I hit missing block. Is this failure recoverable somehow without syncing full node again?

### Your environment

* version of `lnd` 0.8.1-beta
* which operating system (`uname -a` on *Nix) Linux <censored> 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend bitcoind 0.17.0.1

**Comment by cfromknecht** [comment]
@Kixunil we don't officially support pruned nodes (but we plan to!), so unfortunately i think you will need to resync the backend. another possibility is to temporarily connect to a friend's non-pruned node and lnd should heal itself.

if you do resync, you could consider only pruning below a certain height, e.g. segwit activation. this would prevent this from happening again, though it depends on how much free space you have available.

**Comment by Kixunil** [comment]
Thank you for information! Interestingly, LND worked well until this point. I will do the latter option ("friends node" - actually my own, LND is the one that isn't mine :))

For security, I need to use [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy). Do you happen to know if lnd needs any other command enabled that isn't in the [example config file](https://github.com/Kixunil/btc-rpc-proxy/blob/master/btc_rpc_proxy.toml)?

**Comment by cfromknecht** [comment]
> Thank you for information! Interestingly, LND worked well until this point.

Glad to hear!!

>  Do you happen to know if lnd needs any other command enabled that isn't in the example config file?

Off the top of my head that list is looks sufficient, as long as the block fetching is available it should get back into a good state :)

**Comment by Kixunil** [comment]
Turned out it was missing `getinfo`, it seems to work now. Thanks a lot!

**Comment by cfromknecht** [comment]
@Kixunil no problem!
