### ISSUE TITLE
Make ERROR

### ISSUE THREAD

**Issue by gnipping** [lightningnetwork/lnd#3974]
### Background
I successfully build the lnd and lncli.
But, when I use the command  `make btcd` to build btcd

### Your environment

* which operating system  ubuntu 18.04

### Actual behaviour
It feeds back the error 
`flag provided but not defined: -deps
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.
 Installing btcd.
cd /tmp && GO111MODULE=on go get -v github.com/btcsuite/btcd@v0.20.1-beta
package github.com/btcsuite/btcd@v0.20.1-beta: invalid github.com/ import path "github.com/btcsuite/btcd@v0.20.1-beta"
Makefile:83: recipe for target 'btcd' failed
make: *** [btcd] Error 1
`
The target URL is 404 NOT FOUND

**Comment by guggero** [comment]
Did you change anything in your `go.mod` file?

**Comment by gnipping** [comment]
> 
> 
> Did you change anything in your `go.mod` file?

No I don't

**Comment by guggero** [comment]
The command runs fine on my machine and on the build server. So it must be something in your setup. Did you change any other file? What commit/branch are you on? What go version are you using?

**Comment by gnipping** [comment]
> 
> 
> The command runs fine on my machine and on the build server. So it must be something in your setup. Did you change any other file? What commit/branch are you on? What go version are you using?

I use an AWS sever the os version is ubuntu 18.04, I use wget `https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz ` to build go, and use `go get -d github.com/lightningnetwork/lnd` to download the lnd, the I input the command `make && make install` `make check`

**Comment by guggero** [comment]
Ok, that seems to be the problem. You need to use `go 1.13.x` as described in the [installation instructions](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md).

**Comment by gnipping** [comment]
> 
> 
> Ok, that seems to be the problem. You need to use `go 1.13.x` as described in the [installation instructions](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md).

It does work, Thank you! But I have another problem after I build the btcd successfully, I input the command `btcd --testnet --rpcuser=myusername --rpcpass=mypassword`. It feeds back to me the error `Command 'btcd' not found, did you mean:

  command 'bcd' from deb bsdgames
  command 'etcd' from deb etcd-server
  command 'btpd' from deb btpd

Try: sudo apt install <deb name>
`

**Comment by guggero** [comment]
That's because the `make btcd` command in `lnd` only downloads and compiles `btcd` for the integration test, it's not installed in your `$PATH`. You should probably follow the [installation instructions for btcd](https://github.com/btcsuite/btcd) if you want to install it to your system.

**Comment by gnipping** [comment]
> 
> 
> That's because the `make btcd` command in `lnd` only downloads and compiles `btcd` for the integration test, it's not installed in your `$PATH`. You should probably follow the [installation instructions for btcd](https://github.com/btcsuite/btcd) if you want to install it to your system.



> 
> 
> That's because the `make btcd` command in `lnd` only downloads and compiles `btcd` for the integration test, it's not installed in your `$PATH`. You should probably follow the [installation instructions for btcd](https://github.com/btcsuite/btcd) if you want to install it to your system.

OK! Thank you!
