### ISSUE TITLE
Still problems with Neutrino

### ISSUE THREAD

**Issue by Roalkege** [lightningnetwork/lnd#3976]
Okay I have to reopen it. 
My wallet still says 0% blockchain sync.
![4C839EB6-8F6C-418F-A817-C404DE3D9422](https://user-images.githubusercontent.com/44238399/73572712-c6787e00-4471-11ea-834a-391b586b5e44.png)

What I have to do?

_Originally posted by @Roalkege in https://github.com/lightningnetwork/lnd/issues/3975#issuecomment-580901886_

EDIT: I used the Command `lncli listpeers` and the Output is an empty Array.

**Comment by molxyz** [comment]
@Roalkege  What app is this?  Probably better if you ask for help on the lnd slack.

**Comment by Roalkege** [comment]
@molxyz can you send me a invite? 
All invites I can find are invalid.

**Comment by molxyz** [comment]
@Roalkege Try this link:   https://lightning.engineering/slack.html

**Comment by Roasbeef** [comment]
I'd open an issue in the Zap repo.
