### ISSUE TITLE
listinvoices: reversed flag has no effect

### ISSUE THREAD

**Issue by bitromortac** [lightningnetwork/lnd#3986]
Currently the `lncli listinvoices --reversed` flag has no effect, as it
is of type `cli.BoolTFlag` https://github.com/lightningnetwork/lnd/blob/ad0a89b844ec9f55b3ca4ddbb4d368dd8e3c0ea9/cmd/lncli/commands.go#L2848
which is true by default.

Correct behavior can be triggered by `lncli listinvoices --reversed=True`
 or `lncli listinvoices --reversed=False`.

Is this behavior intended? I get that it is more comfortable for lncli users to
see the latest invoices by default. An easy fix would be to change 
`cli.BoolTFlag` to `cli.BoolFlag`, however, an lncli user would have to really use
then `lncli listinvoices --reversed` for the latest invoices. Could take over and fix it.

**Comment by carlaKC** [comment]
I don't think that `--reversed=True` is a nice UX. Renaming the flag would probably be the path of least resistance, perhaps to `--latest`? Then `lastest` invoices are shown by default, and `--latest=false` display in order of invoice add?

**Comment by bitromortac** [comment]
Yes, it's not a good UX and I wouldn't have expected that passing an explicit argument to a bool flag would have any effect. In order to preserve the functionality, one could also rename the flag to something like `--normal-order` and make it a boolean flag, off by default. Then one could pass it to the reversed flag in the request https://github.com/lightningnetwork/lnd/blob/2cd26d75564345c0c37fa83785ebe8e4f1fb8f28/cmd/lncli/commands.go#L2866 but negated. In this way one preserves the behavior of showing the latest invoices without any flag, but one is also able to access the first created invoices by using the `--normal-order` or `--from-beginning` flag.

**Comment by carlaKC** [comment]
>  make it a boolean flag, off by default. Then one could pass it to the reversed flag in the request

Sounds good to me! Not sure if `normal-order` is a good name because that requires some knowledge of what's 'normal'. `--paginate-forward` comes to mind but up to you :)

**Comment by halseth** [comment]
There's some history here, iirc it was done this way to keep it backwards compatible. Don't remember exactly, but could be wort checking: https://github.com/lightningnetwork/lnd/pull/1863

**Comment by bitromortac** [comment]
> There's some history here, iirc it was done this way to keep it backwards compatible. Don't remember exactly, but could be wort checking: #1863

Yes, would prepare the change and keep these points in mind. It wouldn't really change anything other than being able to start receiving invoices from the very beginning, as this is now only available to do so with `--reversed=False`, which is not very intuitive.
