### ISSUE TITLE
Allow for error-free build via `go github.com/lightningnetwork/lnd/...`

### ISSUE THREAD

**Issue by PaulCapestany** [LightningNetwork/lnd#4]
Not a big deal, but figured I might as well post this issue.

Currently the `uspv` package has these build errors:

```
uspv/eight333.go:21: undefined: wire.TestNetL
uspv/eight333.go:26: undefined: chaincfg.TestNetLParams
```

Other than that, only other package build issues I think others would run into when trying to do a `go get` of the `.../...` variety is the `too many errors` flavor of error in `lnstate`

**Comment by Roasbeef** [comment]
Thanks! I've fixed the build errors with [these](https://github.com/LightningNetwork/lnd/commit/8e54e0c3393971583c1b7a745dd4be897a29a954) [three](https://github.com/LightningNetwork/lnd/commit/872db633dfce6247a4f9f9d82a500a9ede495527) [commits](https://github.com/LightningNetwork/lnd/commit/8e54e0c3393971583c1b7a745dd4be897a29a954).

We'll have an automated [travis-ci](https://travis-ci.org/) build-bot linked to the repo up shortly.
