### ISSUE TITLE
LND fails to start

### ISSUE THREAD

**Issue by ArbenKarb** [lightningnetwork/lnd#4008]
### Background

LND fails to start (Note: has stopped working before upgrading to 0.9.0 on 0.7.1)

lnd[10151]: Automatically obtained bitcoind's RPC credentials
lnd[10151]: 2020-02-16 19:58:25.975 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
lnd[10151]: 2020-02-16 19:58:25.975 [INF] LTND: Active chain: Bitcoin (network=mainnet)
lnd[10151]: panic: freepages: failed to get all reachable pages (page 4085: multiple references)
lnd[10151]: goroutine 40 [running]:
lnd[10151]: github.com/coreos/bbolt.(*DB).freepages.func2(0xa856580)
lnd[10151]: github.com/coreos/bbolt@v1.3.3/db.go:1003 +0xdb
lnd[10151]: created by github.com/coreos/bbolt.(*DB).freepages
lnd[10151]: github.com/coreos/bbolt@v1.3.3/db.go:1001 +0x157
systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### Your environment

LND 0.9.0
linux-386
bitcoind v0.18.0

**Comment by halseth** [comment]
What hardware? Looks like a DB corruption.

**Comment by ArbenKarb** [comment]
channel backups have failed recently, what can I do?

**Comment by ArbenKarb** [comment]
cpu:
                       Intel(R) Atom(TM) x5-Z8500  CPU @ 1.44GHz, 792 MHz
                       Intel(R) Atom(TM) x5-Z8500  CPU @ 1.44GHz, 800 MHz
                       Intel(R) Atom(TM) x5-Z8500  CPU @ 1.44GHz, 1541 MHz
                       Intel(R) Atom(TM) x5-Z8500  CPU @ 1.44GHz, 1311 MHz
graphics card:
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers
network:
  enp2s0               Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
  wlp1s0               Intel Dual Band Wireless AC 3165
network interface:
  enp2s0               Ethernet network interface
  lo                   Loopback network interface
  wlp1s0               Ethernet network interface
  docker0              Ethernet network interface
disk:
  /dev/mmcblk0         Disk
  /dev/mmcblk0boot0    Disk
  /dev/mmcblk0boot1    Disk
  /dev/sda             Seagate Expansion
                       Seagate RSS LLC SRD0NF1 Expansion Portable (STEA)
partition:
  /dev/mmcblk0p1       Partition
  /dev/mmcblk0p2       Partition
  /dev/sda1            Partition
usb controller:
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller
bios:
                       BIOS
bridge:
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #2
hub:
                       Terminus Hub
                       Linux Foundation 2.0 root hub
                       Linux Foundation 3.0 root hub
memory:
                       Main Memory
bluetooth:
                       Intel Bluetooth Device
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
                       Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Trusted Execution Engine
                       Serial controller

**Comment by ArbenKarb** [comment]
I think I fucked up big time. Tried to use the recovery guide at https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
but since LND wouldn't start naturally always got an error. Then I deleted the channel.db upon which LND would start again, however the channel.backup file does not seem to contain a valid backup as I am always getting "missing channel backup" when using lncli restorechanbackup (no matter if I use single, multi backup or file. What happens to the funds locked in the channels when the counterparty force closes it?

**Comment by wpaulino** [comment]
> however the channel.backup file does not seem to contain a valid backup as I am always getting "missing channel backup" when using lncli restorechanbackup (no matter if I use single, multi backup or file.

This was an issue that has now been fixed, so you should attempt a restore with v0.9.0.

> What happens to the funds locked in the channels when the counterparty force closes it?

Sweeping funds from a remote force close requires a key that is stored within your `channel.db` and `channel.backup`. Without either of those, you won't be able to access those funds. This is no longer required with any _new_ channels going forward if both channel participants are running lnd v0.8.0 or later.

**Comment by ArbenKarb** [comment]
> This was an issue that has now been fixed, so you should attempt a restore with v0.9.0.

I am already running v0.9.0. However, the backups have been created on a prior version, may that be the issue?

**Comment by wpaulino** [comment]
No. Are you including the `--multi_file` flag?

**Comment by ArbenKarb** [comment]
> No. Are you including the --multi_file flag?

I have not included the --, seems to be working now (sorry)
