### ISSUE TITLE
Pending channels fails to return

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4011]
### Background

After unclean shutdown, pending channels fails to return channels

```
lncli pendingchannels
[lncli] rpc error: code = Unknown desc = unable to find arbitrator
```

Due to a randomly encountered out-of-memory termination LND was uncleanly terminated. After termination normal commands work but pendingchannels fails to return on lncli and via RPC

A forced in-place rescan with `dropwtxmgr` did not resolve the issue

### Your environment

* lnd 0.9.0
* Ubuntu
* Neutrino

**Comment by alexbosworth** [comment]
After a while, dropwtxmgr did seem to solve the issue but I am guessing it had to do some rescanning in the background

**Comment by raelschiffler** [comment]
> A forced in-place rescan with dropwtxmgr did not resolve the issue

@alexbosworth could you please elaborate on how to proceed with this? I'm facing the same problem after a power shortage.

**Comment by alexbosworth** [comment]
try doing a db compact with guggero chantools

**Comment by raelschiffler** [comment]
@alexbosworth thanks for answering so quickly.

> A forced in-place rescan with dropwtxmgr did not resolve the issue

Could you please indicate the exact command you used to do that?

My node doesn't seem to be broken, logs end like that:

> 2023-09-28 11:18:01.049 [INF] LTND: Waiting for chain backend to finish sync, start_height=809638
> 2023-09-28 11:18:17.623 [INF] LNWL: Started polling mempool to cache new transactions
> 2023-09-28 11:26:47.207 [ERR] RPCS: unable to populate arbitrator force close 
> resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 11:26:47.210 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator
> 2023-09-28 11:26:47.830 [ERR] RPCS: unable to populate arbitrator force close resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 11:26:47.831 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator
> 2023-09-28 11:26:48.945 [ERR] RPCS: unable to populate arbitrator force close resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 11:26:48.945 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator
> 2023-09-28 12:06:42.872 [ERR] RPCS: unable to populate arbitrator force close resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 12:06:42.881 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator
> 2023-09-28 12:06:43.129 [ERR] RPCS: unable to populate arbitrator force close resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 12:06:43.130 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator
> 2023-09-28 12:06:43.420 [ERR] RPCS: unable to populate arbitrator force close resp:2900fa53f63f907fe03af1d672321492bde556d68a756375dabea1a2ee6862ba:1, unable to find arbitrator
> 2023-09-28 12:06:43.421 [ERR] RPCS: [/lnrpc.Lightning/PendingChannels]: unable to find arbitrator

**Comment by alexbosworth** [comment]
try --reset-wallet-transactions

**Comment by raelschiffler** [comment]
Thank you.
