### ISSUE TITLE
crash on startup when no connection is available (mobile)

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4016]
### Background

In plane mode, lnd is giving the following error when starting (using neutrino): 
```Unable to initialize neutrino backend: unable to create neutrino light client: lookup btcd-testnet.lightning.computer: no such host```

I can reproduce with the mobile lightning labs app: just start in plane mode and the app will crash after loading up for ~1 sec. 

I'm not sure how to recover from this error. 

### Your environment

* version of `lnd` : 0.9.0
* which operating system (`uname -a` on *Nix): iOS. build from react native
* version of `btcd`, `bitcoind`, or other backend: neutrino

**Comment by halseth** [comment]
Probably makes the most sense to fix neutrino side? By having it retry until peers are available.

**Comment by halseth** [comment]
@nicolasburtey Created https://github.com/lightninglabs/neutrino/pull/208 to fix this. Please report back if it fixes the problem for you!
