### ISSUE TITLE
An error about gomod.

### ISSUE THREAD

**Issue by minchenzz** [lightningnetwork/lnd#4021]
```package main

import (
	"github.com/lightningnetwork/lnd"
)

func main()  {
	
}
```

When I use ```go mod tidy```, it failed. 
```
go: github.com/lightningnetwork/lnd imports
        github.com/roasbeef/btcwallet/waddrmgr: github.com/roasbeef/btcwallet@v0.11.0: parsing go.mod:
        module declares its path as: github.com/btcsuite/btcwallet
                but was required as: github.com/roasbeef/btcwallet
```
I used ```replace github.com/btcsuite/btcwallet v0.11.0 => github.com/roasbeef/btcwallet v0.11.0```, but it still does not work.

How can I fix it? 
Thank you so much.

**Comment by guggero** [comment]
What version of lnd did you specify in your `go.mod`? If you don't specify one explicitly it might pick a very old one. So try something like `github.com/lightningnetwork/lnd v0.9.0-beta-rc3.0.20200121213302-a2977c4438b5`
Not sure what else could be the problem.

**Comment by minchenzz** [comment]
@guggero I did not specify a version, ```go.mod``` is a  empty file. But ```github.com/lightningnetwork/lnd v0.9.0-beta-rc3.0.20200121213302-a2977c4438b5``` solved the problem. 👍 thank you!!!!
