### ISSUE TITLE
Hardware Secure Module on RaspberryPi for Raspiblitz, Raspibolt and more...

### ISSUE THREAD

**Issue by cedricwalter** [lightningnetwork/lnd#4022]
### Background

More and more people are using Raspberry PI to host their LND hot wallet. Using Raspiblitz, Raspibold or even maybe CASA. It would be great if LND start supporting optionally HSM like:

https://www.zymbit.com/blog-security-module-raspberry-pi/    (42. euro)
or
https://www.riddleandcode.com/secure-element

### Your environment
LND 0.9.0
### Steps to reproduce
Nothing 
### Expected behaviour
Nothing 
### Actual behaviour
Nothing

**Comment by Roasbeef** [comment]
Integration with hardware is up to the vendors of said lnd-in-a-box hardware variants. See these issues w.r.t additional abstraction of keying material which will make things like that possible: https://github.com/lightningnetwork/lnd/issues/3943, https://github.com/lightningnetwork/lnd/issues/3929. 

In any case, if you're "serious" about running a Lightning Node, a hardware upgrade from a rasp pi is strongly recommended.
