### ISSUE TITLE
Refactor the lnwallet package

### ISSUE THREAD

**Issue by mlerner** [lightningnetwork/lnd#403]
Test coverage for the `lnwallet` could be increased (see https://coveralls.io/builds/14090803/source?filename=lnwallet%2Fwallet.go#L45). Refactoring the `lnwallet` package would make the packages more easily testable and understandable.

Several things could be done to refactor (in order of when they should be done):
1) Rename `lnwallet` to `wallet`.
2) Separate `btcwallet` and existing lightning-aware wallet code into separate packages that each contain implementations satisfying the `interface.go` file. 
3) Remove code from the current `wallet.go` file - it contains code that is not directly related to the [`LightningWallet`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L237). A good example of this is the [message definitions](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L200) contained in `wallet.go`. Separating these definitions (and their handlers) into a separate file would allow for easier testing.

After these steps we would have:
- `wallet/btcwallet/*`
- `wallet/lnwallet/*`
- `wallet/interface.go` and other files not strictly related to a certain wallet implementation

**Comment by Roasbeef** [comment]
This has been happening progressively over the past few `lnd` releases, as a result I no longer think we need to track this independently.
