### ISSUE TITLE
Watchtower server: how can I get pubkey of watchtower server?

### ISSUE THREAD

**Issue by takaya-imai** [lightningnetwork/lnd#4037]
### Background

I want to set up watchtower server and its client.
I configured `watchtower.active=1` in  lnd.conf and restarted lnd as document https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md#configuring-a-watchtower. 
But no way to get pubkey of watchtower server because lncli did not return the pubkey .

### Your environment

* version of `lnd`: 0.9.0-beta
* which operating system (`uname -a` on *Nix): Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-139-generic x86_64)
* version of `btcd`, `bitcoind`, or other backend : bitcoind v0.18.0.0, testnet3

### Steps to reproduce

1. add `watchtower.active=1` into  lnd.conf
2. restart lnd
3. `$ lncli --network testnet tower info`

### Expected behaviour

`lncli` returns as follows.

```
{
        "pubkey": "03281d603b2c5e19b8893a484eb938d7377179a9ef1a6bca4c0bcbbfc291657b63",
        "listeners": [
                "[::]:9911"
        ],
        "uris": null,
}
```

### Actual behaviour

```
$ lncli --network testnet tower info
No help topic for 'tower'
```

**Comment by cfromknecht** [comment]
@takaya-imai the `watchtowerrpc` isn’t accessible by default in `lnd` or `lncli`. To do so, recompile with `make install tags=“watchtowerrpc` and restart `lnd`. The commands above look correct and should then work correctly

**Comment by takaya-imai** [comment]
@cfromknecht solved. thanks!
