### ISSUE TITLE
OpenChannelSync with node_pubkey fails with 'pubkey string is empty'

### ISSUE THREAD

**Issue by zoedberg** [lightningnetwork/lnd#4041]
### Background

Hi,

I'm calling lnd v0.9.0-beta via a Python gRPC client.

From this release, the parameter `node_pubkey_string` of the message `OpenChannelRequest` (required by both `OpenChannel` and `OpenChannelSync`) has been deprecated.

But, as stated by Roasbeef in this [issue](https://github.com/lightningnetwork/lnd/issues/3404):
> If you want to use OpenChannelSync, instead of OpenChannel (the streaming variant), then you'll need to pass in the hex encoded string.

I'm using `OpenChannelSync` and I can confirm that passing `node_pubkey` instead of `node_pubkey_string` causes the gRPC error `pubkey string is empty`.

Hence, when the parameter `node_pubkey_string` will be removed, `OpenChannelSync` will break.

### Environment

* version of `lnd`: `v0.9.0-beta`
* operating system: `Linux host 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux`
* version of `bitcoind`: `0.18.1`

### Steps to reproduce

Call `OpenChannelSync` setting `node_pubkey` in the `OpenChannelRequest`.

### Expected behaviour

Successful channel opening and a `ChannelPoint` return message.

### Actual behaviour

Channel opening fails with error: `pubkey string is empty`.

**Comment by wpaulino** [comment]
You can continue using the `node_pubkey_string` field for now, but ideally we need a change to use `node_pubkey` in https://github.com/lightningnetwork/lnd/blob/1467cd4dd382f9de7dc7ee89d779324ee9d2b4da/rpcserver.go#L1766

**Comment by Roasbeef** [comment]
This has been resolved as part of #4130.
