### ISSUE TITLE
DB Corruption (healthy hardware)

### ISSUE THREAD

**Issue by kilrau** [lightningnetwork/lnd#4043]
### Background

I experienced what looks like a db corruption. `lnd` is now unable to start with the corrupted db. The hardware/drive is healthy, other services running on it (e.g. bitcoind) are running just fine without any suspicious log entries or restarts at time of crash. I'd like to find out which db is corrupted (guessing `channel.db` though) and find the entry that caused it. Since I am not very experienced with `bbolt` and the bucket structure I'd appreciate some guidance.

I did a backup of the lnd data folder for that purpose and already went ahead and restored my node & channels using my mnemonic and channel backup.

Systemd showing the failed restart:
```
-- Logs begin at Fri 2020-02-28 22:05:28 GMT, end at Sat 2020-02-29 09:55:36 GMT. --
Feb 29 09:54:39 ABC systemd[1]: lnd.service: Scheduled restart job, restart counter is at 590.
Feb 29 09:54:39 ABC systemd[1]: Stopped LND Lightning Daemon.
Feb 29 09:54:39 ABC systemd[1]: Starting LND Lightning Daemon...
Feb 29 09:54:39 ABC systemd[1]: Started LND Lightning Daemon.
Feb 29 09:54:39 ABC lnd[9947]: panic: freepages: failed to get all reachable pages (page 18875: multiple references)
Feb 29 09:54:39 ABC lnd[9947]: goroutine 13 [running]:
Feb 29 09:54:39 ABC lnd[9947]: github.com/coreos/bbolt.(*DB).freepages.func2(0x1862c40)
Feb 29 09:54:39 ABC lnd[9947]:         github.com/coreos/bbolt@v1.3.3/db.go:1003 +0xcc
Feb 29 09:54:39 ABC lnd[9947]: created by github.com/coreos/bbolt.(*DB).freepages
Feb 29 09:54:39 ABC lnd[9947]:         github.com/coreos/bbolt@v1.3.3/db.go:1001 +0x108
Feb 29 09:54:39 ABC systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 29 09:54:39 ABC systemd[1]: lnd.service: Failed with result 'exit-code'.
```
Related issue: https://github.com/lightningnetwork/lnd/issues/3867, even though this one was caused by an actual hardware failure.

### Your environment

* version of `lnd`: `0.9.0-beta` (also tried to launch environment with `0.9.1-beta` today -> same)
* which operating system (`uname -a` on *Nix): `Linux ABC 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.19.0.1
* any other relevant environment details: env was running fine as is for several months (upgrade path 0.7.1 -> 0.8.1 -> 0.8.2 -> 0.9.0)

### Steps to reproduce

🤷

### Expected behaviour

No db corruption unless hardware/drive misbehaves.

### Actual behaviour

db corruption with well behaving hardware/drive.

**Comment by Roasbeef** [comment]
Are you running with `--sync-freelist`?

**Comment by kilrau** [comment]
No

**Comment by wpaulino** [comment]
Does running with the flag change anything?

**Comment by kilrau** [comment]
> Does running with the flag change anything?
It didn't. Anyhow, I'm on a new setup. Closing here.
