### ISSUE TITLE
Channel has been "pending open" for a week, Funding Transaction confirmed 

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#4046]
### Your environment

* version of `lnd`

"version": "0.8.2-beta commit=basedon-v0.8.2-beta-fresh-btcpay",

* which operating system (`uname -a` on *Nix)

Linux BTCPayServerVM 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

  "version": 190001,
  "protocolversion": 70015,

* any other relevant environment details

```
"pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "031678745383bd273b4c3dbefc8ffbf4847d85c2f62d3407c0c980430b3257c403",
                "channel_point": "49a5ef8258556cf651b84baa4ef2fca6db0f4d2d03ea6204c410fa3d28889080:1",
                "capacity": "505000",
                "local_balance": "485480",
                "remote_balance": "16789",
                "local_chan_reserve_sat": "5050",
                "remote_chan_reserve_sat": "5050"
            },
            "confirmation_height": 0,
            "commit_fee": "2730",
            "commit_weight": "724",
            "fee_per_kw": "3772"
        }
    ],
```

funding transaction: 

https://blockstream.info/tx/49a5ef8258556cf651b84baa4ef2fca6db0f4d2d03ea6204c410fa3d28889080

How can fix this or close the channel?

**Comment by wpaulino** [comment]
Did you open the channel or the remote party? Could you provide logs of the channel from startup?

**Comment by wpaulino** [comment]
You may be experiencing https://github.com/lightningnetwork/lnd/issues/3675. I'd try a restart before digging into the logs.

**Comment by hakonamatata** [comment]
> 
> 
> Did you open the channel or the remote party? Could you provide logs of the channel from startup?

I opened / attempted to open the channel. I have access to the logs, but it is a lot of text to dig through.

**Comment by wpaulino** [comment]
Did a restart help @hakonamatata?

**Comment by hakonamatata** [comment]
> 
> 
> Did a restart help @hakonamatata?

Yeah, restarting fixed the problem :)

**Comment by wpaulino** [comment]
You should also upgrade to v0.9.0 which is no longer affected by this issue.
