### ISSUE TITLE
suboptimal routes?

### ISSUE THREAD

**Issue by anonproject** [lightningnetwork/lnd#4054]
As far as I understood the payments in LN are routed in such a way that the destination node doesn't know the public key of the source node provided there is sufficient distance between these 'Alice' and 'Bob' nodes.  Correct?

For example as written [here](https://www.nasdaq.com/articles/lightning-network-traffic-analysis-raises-questions-over-fees-and-privacy-2019-12-27) :

> The paper also finds that despite randomized onion routing, “**strong statistical evidence can be gathered** about the sender and receiver of payments, since a substantial portion of payments involve only a single routing intermediary.” 
> As a potential solution to this privacy drawback, the authors suggest using “deliberately suboptimal, longer routing paths [that] can restore privacy while only marginally increasing the cost of an average transaction.”

I mean if the attacker own a substantial number of intermediate nodes, he can gather some statistical evidence.  Correct?
If so, how can I find not the shortest and the most efficient route but the most convoluted one?

**Comment by anonproject** [comment]
Also another question.  Kinda related to the issue discussed.

The matter concerns the problem of change in Wasabi Wallet.

They recommend ( https://docs.wasabiwallet.io/using-wasabi/ChangeCoins.html#why-change-is-an-issue ) to do the following:

> The Lightning Network can be a very private way of sending bitcoin, and you can choose the channel size to be exactly the size of your change coin. However, it is very important that you do not link this non-private coin to your main Lightning node public key.

> So, a good strategy is to **create a new Lightning node and public key**, send the whole change coin into this fresh wallet, and open a channel of this amount to a **random peer** on the network. Then route a payment either to a merchant for goods and services, or to your own main Lightning node for further use.

> After the balance of the channel is entirely on the other side, cooperatively close the channel with your peer, so that he gets the only output in the closing transaction.


Is it really necessary to create a new LN node?  Or it can be sufficient just to chose some convoluted route to transfer the funds to the main LN node?

Anyways, will it be secure to transfer the funds as described - just by creating a new LN node, opening a channel with random peer and transferring the funds to the main LN node and closing the channel afterwards?

**Comment by anonproject** [comment]
Oh.  So I can use the output of **describegraph** command to get the nodes and open channels.  Is there any tools available to build the routes with a minimum number of hops via that data?

**Comment by Roasbeef** [comment]
This isn't a forum, this is an issue tracker. I recommend [you join our slack](https://lightning.engineering/slack.html) where we'll be happy to field questions like this.
