### ISSUE TITLE
lncli estimatefee gets unexpected end of JSON input

### ISSUE THREAD

**Issue by tomosaigon** [lightningnetwork/lnd#4057]
### Background

When running the lncli command with argument estimatefee the command fails and prints:

`[lncli] unexpected end of JSON input`

### Your environment

* lnd 0.9.0-beta commit=v0.9.0-beta-155-g1467cd4dd382f9de7dc7ee89d779324ee9d2b4da
* Ubuntu 18.04
* Bitcoin Core version v0.18.1 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

`lncli estimatefee
[lncli] unexpected end of JSON input
`

### Expected behaviour

An estimated fee value is printed.

### Actual behaviour

Fees are not shown and an error is printed.

**Comment by Roasbeef** [comment]
Do you have error logs available?

**Comment by ErikEk** [comment]
Did you provide an address?
Like this...
lncli estimatefee '{"tb1qedtttrpl99w2rdkppdfrafnyhk0vcprg7ce96q":1000}'

**Comment by tomosaigon** [comment]
Command does work when passed a json string with address and amount. Perhaps the command simply tries to use a missing argument as an empty json string and then errors.
