### ISSUE TITLE
BTCN: Can't accept connection: unable to accept connection from 92.53.65.101:36220: EOF

### ISSUE THREAD

**Issue by toptim** [lightningnetwork/lnd#4058]
### Background

How fix this error?
And not found peer=0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8 in lightning network

### Your environment

* version of `lnd` LTND: Version: 0.9.1-beta commit=v0.9.1-beta, build=production, logging=default
* which operating system (`uname -a` on *Nix) Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core version v0.19.0.1
* any other relevant environment details

### Steps to reproduce

`[INF] SRVR: New inbound connection from 92.53.65.101:60216
[INF] SRVR: Finalizing connection to 0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8@92.53.65.101:60216, inbound=true
[INF] SRVR: Negotiated chan series queries with 0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8
[INF] DISC: Creating new GossipSyncer for peer=0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8
[INF] DISC: GossipSyncer(0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8): filtering chan range: start_height=620627, num_blocks=4294346668
[INF] DISC: GossipSyncer(0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8): sending final chan range chunk, size=91
[INF] DISC: GossipSyncer(0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8): fetching chan anns for 41 chans
[INF] PEER: unable to read message from 0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8@92.53.65.101:60216: EOF
[INF] PEER: Disconnecting 0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8@92.53.65.101:60216, reason: read handler closed
[INF] DISC: Removing GossipSyncer for peer=0218599c7f8c0b7b4d97f8f2cb09cb0666e9c28aa063aac883db967265092ae3b8
[INF] CRTR: Processed channels=0 updates=47 nodes=0 in last 59.999899112s
[INF] DISC: Broadcasting 73 new announcements in 8 sub batches
[INF] CRTR: Processed channels=0 updates=35 nodes=1 in last 59.999927724s
[INF] CRTR: Pruning channel graph using block 0000000000000000000ae6f51856442d134c1997be524f7b3e553f6ae9bee87c (height=620777)
[INF] CRTR: Block 0000000000000000000ae6f51856442d134c1997be524f7b3e553f6ae9bee87c (height=620777) closed 1 channels
[INF] NTFN: New block: height=620777, sha=0000000000000000000ae6f51856442d134c1997be524f7b3e553f6ae9bee87c
[INF] UTXN: Attempting to graduate height=620777: num_kids=0, num_babies=0
[INF] DISC: Broadcasting 40 new announcements in 4 sub batches
[INF] CRTR: Processed channels=0 updates=34 nodes=0 in last 59.999875866s
[ERR] BTCN: Can't accept connection: unable to accept connection from 92.53.65.101:36220: EOF

`
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
This doesn't appear to be an actual issue. A peer attempts to connect inbound but then disconnects at the last moment for w/e reason.

**Comment by toptim** [comment]
How I can block peer?
Connect problem only with this peer
