### ISSUE TITLE
very old force closed channels for neutrino can take a while to sweep

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#4060]
### Background

A forced closed channel stays in pending mode and unable to sweep funds.

### Your environment

lnd master with neutrino backend running on mobile.

### Steps to reproduce

1. Ensure active channel between Alice & Bob
2. Bob forces closing the channel while Alice is not running her app.
3. Alice opens her app after  ~1 month (or more).

I think this issue may be reproduced also if Alice restores from seed but didn't run this flow so I am not sure of that.

### Expected behavior

LND finishes syncing to chain, detects in a reasonable time the confirmation for the closed channel and executes the sweep transaction.

### Actual behavior

Takes hours for LND to get the confirmation and execute the sweep transaction.
In addition during these hours Alice's mobile app must be in the foreground. If the app exists from some reason, the whole process of scanning starts again.

### Notes
I believe the problem resides in the way the historical confirmations flow uses the filters query (https://github.com/lightningnetwork/lnd/blob/master/chainntnfs/neutrinonotify/neutrino.go#L528)
It looks like that by adding `OptimisticReverseBatch` query option this issue can be mitigated in a reasonable way.
Without batching I have seen in a user logs that it takes ~10 filters per second.
At the same user device a batch of 100 filters took ~9 seconds which is more than 10x performance gain.
If there aren't any objections to the proposed solution I will open a PR.

**Comment by wpaulino** [comment]
Sounds like a reasonable change to me with huge impact 👍
