### ISSUE TITLE
Return remote CSV constraint in API

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4063]
Currently the `csv_delay` returned in `Channel` messages relates to the local wait time, not the remote wait time:

```
    The CSV delay expressed in relative blocks. If the channel is force closed,
    we will need to wait for this many blocks before we can regain our funds.
```

There is a mirror CSV value that relates to the number of blocks where the local node is protected from the remote attempting to sweep an out-of-date version of the commitment transaction

This mirror CSV value is not returned in the `Channel` message and cannot be retrieved through the API

Since this CSV value indicates important security information for the channel, it should be returned in the API

**Comment by carlaKC** [comment]
Fixed by #4371
