### ISSUE TITLE
autopilot.active=false does not disable autopilot

### ISSUE THREAD

**Issue by oitdmser** [lightningnetwork/lnd#4065]
### Your environment

* version of `lnd`  0.9.1
* which operating system (`uname -a` on *Nix) Debian 10
* version of `btcd`, `bitcoind`, or other backend bitcoind v.19.1
* any other relevant environment details

### Steps to reproduce

my lnd.conf specifies autopilot.active=false or autopilot.active=0

### Expected behaviour

autopilot should be disabled

### Actual behaviour

I see "Instantizing autopilot ....." in the log on startup. neither of the above options stop autopilot from starting. I have to disable it by setting maxchannels=0

**Comment by halseth** [comment]
The autopilot module will always be running, but it won't open channels when non-active. Are you seeing actual channels being opened?

**Comment by oitdmser** [comment]
no, although I don't have enough unallocated funds to open a channel. Perhaps the verbage could be clarified in the log?

**Comment by halseth** [comment]
Added to log in https://github.com/lightningnetwork/lnd/pull/4071
