### ISSUE TITLE
Docker image not exists

### ISSUE THREAD

**Issue by David-Lor** [lightningnetwork/lnd#4074]
The [DOCKER Readme](https://github.com/lightningnetwork/lnd/blob/master/docs/DOCKER.md) specifies to use the [lightninglabs/lnd](https://hub.docker.com/r/lightninglabs/lnd/) image, but it currently does not exist on dockerhub.

**Comment by guggero** [comment]
Yes, we removed the image because it was really old. We should probably update the README with instructions on building your own image.
