### ISSUE TITLE
Unable to start node via docker

### ISSUE THREAD

**Issue by duybach** [lightningnetwork/lnd#4076]
### Background

I am following the guide from the README inside the docker folder. When I deploy "alice" and setup the BTCD node (by mining 400 blocks to activate segwit) I get this error when I check the logs from alice:

`[ERR] NTFN: unable to get block: -32602: parameter #2 'verbosity' must be type int (got bool) `

### Your environment

The docker README tutorial was working for me a few days ago. Today I had to redo the docker containers and after removing the containers & volumes, I've encountered this problem. Tried it also on my other device (Ubuntu & Windows).

### Steps to reproduce

```
$ export NETWORK="simnet" 

$ docker-compose run -d --name alice lnd_btc
$ docker exec -i -t alice bash

alice$ lncli --network=simnet newaddress np2wkh 

$ MINING_ADDRESS=<alice_address> docker-compose up -d btcd

$ docker-compose run btcctl generate 400

$ docker logs alice
[ERR] NTFN: unable to get block: -32602: parameter #2 'verbosity' must be type int (got bool) 
```

### Expected behaviour

My LND node should be able to get the blocks.

### Actual behaviour

LND Node can't read block because:
`[ERR] NTFN: unable to get block: -32602: parameter #2 'verbosity' must be type int (got bool) `

**Comment by guggero** [comment]
This error is coming from `btcd`. It looks like [a PR was recently merged](https://github.com/btcsuite/btcd/pull/1529) that changed the behavior there and lnd isn't compatible with the newest version yet. Can you try changing your `docker/btcd/Dockerfile` from

```
RUN git clone https://github.com/btcsuite/btcd.git . \
    &&  GO111MODULE=on go install -v . ./cmd/...
```

to

```
RUN git clone https://github.com/btcsuite/btcd.git . \
    &&  git checkout v0.20.1-beta && GO111MODULE=on go install -v . ./cmd/...
```

and then building the image again?

**Comment by duybach** [comment]
Thanks for the solution. Node is working now :+1:
