### ISSUE TITLE
InvalidOnionHMAC error on payment

### ISSUE THREAD

**Issue by Horndev** [lightningnetwork/lnd#4077]
### Background

When making a payment from LND, error message:
`{"payment_error":"InvalidOnionHMAC(onion_sha=9726356d9fb9088f3abe90029b529f99e92974d6351ff313ac6a3c4a7b52c66a)","payment_preimage":null,"payment_route":null,"payment_hash":"3A1j8TY24jLvppQkHthLJtBXnbf5hFPD/jA+zax00rQ="}`

- invoice generated by Bitcoin Lightning Wallet (Android)
- Submitted via LND REST API

### Your environment
* version of `lnd` = 0.9.0-beta commit=v0.9.0-beta-266-g15be39b8dbd75bb21ee452fef35f3955a09063bd
* ubuntu
* bitcoind

### Steps to reproduce

Produce invoice on BLW, pay with lnd REST api.

**Comment by joostjager** [comment]
@Horndev is this reproducible? Does it happen for every payment?

**Comment by Horndev** [comment]
I was able to reproduce for a while - but it stopped happening now.  It may have been related to the network path being used at the time.

**Comment by joostjager** [comment]
Closing issue for now until more info is available
