### ISSUE TITLE
LND 0.9.2 crash on Raspberry Pi 4

### ISSUE THREAD

**Issue by Amiga500** [lightningnetwork/lnd#4083]
### Background

LND 0.9.2 crash on Raspberry Pi 4 4GB

### Your environment

* LND 0.9.2
* Linux myNode 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
* Bitcoin Core version v0.19.1
* Mynode (full node) latest commits build

### Steps to reproduce

Started and after some minutes it reboots

### Expected behaviour

No reboots!

### Actual behaviour

Started and after some minutes it reboots

**Comment by Amiga500** [comment]
-- Logs begin at Sat 2020-03-14 16:02:56 CDT, end at Sat 2020-03-14 16:15:04 CDT. --
Mar 14 16:15:02 myNode lnd[7739]: 2020-03-14 16:15:02.146 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Mar 14 16:15:02 myNode lnd[7739]: 2020-03-14 16:15:02.145 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Mar 14 16:15:02 myNode lnd[7739]: 2020-03-14 16:15:02.145 [INF] LTND: Initializing bitcoind backed fee estimator
Mar 14 16:15:02 myNode lnd[7739]: 2020-03-14 16:15:02.118 [INF] LTND: Primary chain is set to: bitcoin
Mar 14 16:15:01 myNode lnd[7739]: 2020-03-14 16:15:01.873 [INF] LNWL: Opened wallet
Mar 14 16:12:37 myNode lnd[7739]: 2020-03-14 16:12:37.823 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Mar 14 16:12:37 myNode lnd[7739]: 2020-03-14 16:12:37.822 [INF] RPCS: password gRPC proxy started at 0.0.0.0:10080
Mar 14 16:12:37 myNode lnd[7739]: 2020-03-14 16:12:37.818 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
Mar 14 16:12:37 myNode lnd[7739]: 2020-03-14 16:12:37.794 [INF] CHDB: Checking for schema update: latest_version=12, db_version=12
Mar 14 16:12:28 myNode lnd[7739]: 2020-03-14 16:12:28.605 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Mar 14 16:12:28 myNode lnd[7739]: 2020-03-14 16:12:28.603 [INF] LTND: Version: 0.9.2-beta commit=v0.9.2-beta, build=production, logging=default
Mar 14 16:12:28 myNode lnd[7739]: Automatically obtained bitcoind's RPC credentials
Mar 14 16:12:28 myNode lnd[7739]: Attempting automatic RPC configuration to bitcoind
Mar 14 16:12:28 myNode systemd[1]: Started LND Lightning Daemon.
Mar 14 16:12:28 myNode lnd[7740]: abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
Mar 14 16:12:28 myNode lnd[7737]: + exit 0
Mar 14 16:12:28 myNode lnd[7737]: }
Mar 14 16:12:28 myNode lnd[7737]:   "warnings": ""
Mar 14 16:12:28 myNode lnd[7737]:   },
Mar 14 16:12:28 myNode lnd[7737]:     }
Mar 14 16:12:28 myNode lnd[7737]:       "height": 481824
Mar 14 16:12:28 myNode lnd[7737]:       "active": true,
Mar 14 16:12:28 myNode lnd[7737]:       "type": "buried",
Mar 14 16:12:28 myNode lnd[7737]:     "segwit": {
Mar 14 16:12:28 myNode lnd[7737]:     },
Mar 14 16:12:28 myNode lnd[7737]:       "height": 419328
Mar 14 16:12:28 myNode lnd[7737]:       "active": true,
Mar 14 16:12:28 myNode lnd[7737]:       "type": "buried",
Mar 14 16:12:28 myNode lnd[7737]:     "csv": {
Mar 14 16:12:28 myNode lnd[7737]:     },
Mar 14 16:12:28 myNode lnd[7737]:       "height": 388381
Mar 14 16:12:28 myNode lnd[7737]:       "active": true,
Mar 14 16:12:28 myNode lnd[7737]:       "type": "buried",
Mar 14 16:12:28 myNode lnd[7737]:     "bip65": {
Mar 14 16:12:28 myNode lnd[7737]:     },
Mar 14 16:12:28 myNode lnd[7737]:       "height": 363725
Mar 14 16:12:28 myNode lnd[7737]:       "active": true,
Mar 14 16:12:28 myNode lnd[7737]:       "type": "buried",
Mar 14 16:12:28 myNode lnd[7737]:     "bip66": {
Mar 14 16:12:28 myNode lnd[7737]:     },
Mar 14 16:12:28 myNode lnd[7737]:       "height": 227931
Mar 14 16:12:28 myNode lnd[7737]:       "active": true,
Mar 14 16:12:28 myNode lnd[7737]:       "type": "buried",
Mar 14 16:12:28 myNode lnd[7737]:     "bip34": {
Mar 14 16:12:28 myNode lnd[7737]:   "softforks": {
Mar 14 16:12:28 myNode lnd[7737]:   "pruned": false,
Mar 14 16:12:28 myNode lnd[7737]:   "size_on_disk": 303765997783,
Mar 14 16:12:28 myNode lnd[7737]:   "chainwork": "00000000000000000000000000000000000000000d9d3ff864170666cd30d687",
Mar 14 16:12:28 myNode lnd[7737]:   "initialblockdownload": false,
Mar 14 16:12:28 myNode lnd[7737]:   "verificationprogress": 0.9999996388003405,
Mar 14 16:12:28 myNode lnd[7737]:   "mediantime": 1584216623,
Mar 14 16:12:28 myNode lnd[7737]:   "difficulty": 16552923967337.23,
Mar 14 16:12:28 myNode lnd[7737]:   "bestblockhash": "0000000000000000000abdddc74247992a10646ac2ead8fb4c626af5b503fed3",
Mar 14 16:12:28 myNode lnd[7737]:   "headers": 621656,
Mar 14 16:12:28 myNode lnd[7737]:   "blocks": 621656,
Mar 14 16:12:28 myNode lnd[7737]:   "chain": "main",
Mar 14 16:12:28 myNode lnd[7737]: {
Mar 14 16:12:28 myNode lnd[7737]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Mar 14 16:12:28 myNode lnd[7737]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Mar 14 16:12:28 myNode lnd[7737]: Checking if Bitcoin is synced...
Mar 14 16:12:28 myNode lnd[7737]: + echo 'Checking if Bitcoin is synced...'
Mar 14 16:12:28 myNode lnd[7737]: + set -e
Mar 14 16:12:28 myNode systemd[1]: Starting LND Lightning Daemon...
Mar 14 16:12:28 myNode systemd[1]: Stopped LND Lightning Daemon.
Mar 14 16:12:28 myNode systemd[1]: lnd.service: Succeeded.
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.340 [INF] LTND: Shutdown complete
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.332 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping SignRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.331 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.330 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.329 [INF] RPCS: Stopping RPC Server
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.226 [INF] PEER: unable to read message from 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080: read tcp 127.0.0.1:33322->127.0.0.1:9050: use of closed network connection
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.225 [INF] PEER: Disconnecting 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080, reason: server: disconnecting peer 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.224 [INF] SRVR: Disconnecting from 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.224 [INF] PEER: unable to read message from 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735: read tcp 127.0.0.1:33318->127.0.0.1:9050: use of closed network connection
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.222 [INF] PEER: Disconnecting 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735, reason: server: disconnecting peer 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.221 [INF] SRVR: Disconnecting from 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.221 [INF] PEER: unable to read message from 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735: read tcp 127.0.0.1:33320->127.0.0.1:9050: use of closed network connection
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.220 [INF] PEER: Disconnecting 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735, reason: server: disconnecting peer 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.219 [INF] SRVR: Disconnecting from 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.218 [INF] CHFT: Stopping event store
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.217 [INF] CHBU: Stopping chanbackup.SubSwapper
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.217 [INF] FNDG: Funding manager shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.215 [INF] PRNF: Stopping PeerNotifier
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.215 [INF] CNCT: Stopping ChainArbitrator
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.214 [INF] DISC: Authenticated Gossiper is stopping
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.214 [INF] BRAR: Breach arbiter shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.214 [INF] UTXN: UTXO nursery shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.213 [INF] HSWC: HTLC Switch shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.212 [INF] CRTR: Block 0000000000000000000abdddc74247992a10646ac2ead8fb4c626af5b503fed3 (height=621656) closed 2 channels
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.187 [INF] CHDB: Pruned 1 unconnected nodes from the channel graph
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.185 [INF] CHDB: Pruned unconnected node 02c2fe44214097ddc746abd1ed49070267b9eb388e446f06769952fa3ee4f4e876 from channel graph
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.162 [INF] CRTR: FilteredChainView stopping
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.156 [INF] HSWC: Block epoch canceled, decaying hash log shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.155 [ERR] RPCS: [/chainrpc.ChainNotifier/RegisterBlockEpochNtfn]: chain notifier shutting down
Mar 14 16:12:28 myNode lnd[3278]: 2020-03-14 16:12:28.042 [INF] CRTR: Pruning channel graph using block 0000000000000000000abdddc74247992a10646ac2ead8fb4c626af5b503fed3 (height=621656)
Mar 14 16:12:26 myNode lnd[3278]: 2020-03-14 16:12:26.945 [INF] UTXN: Attempting to graduate height=621656: num_kids=0, num_babies=0
Mar 14 16:12:26 myNode lnd[3278]: 2020-03-14 16:12:26.944 [INF] NTFN: New block: height=621656, sha=0000000000000000000abdddc74247992a10646ac2ead8fb4c626af5b503fed3
Mar 14 16:12:26 myNode lnd[3278]: 2020-03-14 16:12:26.529 [INF] LTND: Gracefully shutting down.
Mar 14 16:12:26 myNode lnd[3278]: 2020-03-14 16:12:26.528 [INF] LTND: Shutting down...
Mar 14 16:12:26 myNode lnd[3278]: 2020-03-14 16:12:26.527 [INF] LTND: Received terminated
Mar 14 16:12:26 myNode systemd[1]: Stopping LND Lightning Daemon...
Mar 14 16:12:16 myNode lnd[3278]: 2020-03-14 16:12:16.545 [INF] CRTR: Processed channels=0 updates=25 nodes=0 in last 59.999831271s
Mar 14 16:11:19 myNode lnd[3278]: 2020-03-14 16:11:19.749 [INF] DISC: Broadcasting 33 new announcements in 4 sub batches
Mar 14 16:11:16 myNode lnd[3278]: 2020-03-14 16:11:16.545 [INF] CRTR: Processed channels=0 updates=31 nodes=0 in last 2m52.429756953s
Mar 14 16:10:33 myNode lnd[3278]: 2020-03-14 16:10:33.748 [ERR] SRVR: Unable to connect to 028b1831c55d5707804ed784392968b8b26446393ffa22edaf189e6cb863117d0d@paaqwyblecr4bag7.onion:9735: socks connect tcp 127.0.0.1:9050->paaqwyblecr4bag7.onion:9735: unknown error TTL expired
Mar 14 16:09:10 myNode lnd[3278]: 2020-03-14 16:09:10.112 [INF] CRTR: Block 00000000000000000002118f009a9142e42acdcd4222ebc2b7ddbee23b9a0e65 (height=621655) closed 4 channels
Mar 14 16:09:09 myNode lnd[3278]: 2020-03-14 16:09:09.971 [INF] CRTR: Pruning channel graph using block 00000000000000000002118f009a9142e42acdcd4222ebc2b7ddbee23b9a0e65 (height=621655)
Mar 14 16:09:07 myNode lnd[3278]: 2020-03-14 16:09:07.748 [INF] NTFN: New block epoch subscription
Mar 14 16:09:07 myNode lnd[3278]: 2020-03-14 16:09:07.748 [INF] UTXN: Attempting to graduate height=621655: num_kids=0, num_babies=0
Mar 14 16:09:07 myNode lnd[3278]: 2020-03-14 16:09:07.746 [INF] NTFN: New block: height=621655, sha=00000000000000000002118f009a9142e42acdcd4222ebc2b7ddbee23b9a0e65
Mar 14 16:08:33 myNode lnd[3278]: 2020-03-14 16:08:33.474 [INF] DISC: Obtained 1 addrs to bootstrap network with
Mar 14 16:08:33 myNode lnd[3278]: 2020-03-14 16:08:33.459 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
Mar 14 16:08:32 myNode lnd[3278]: 2020-03-14 16:08:32.864 [INF] DISC: GossipSyncer(02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b): applying gossipFilter(start=2020-03-14 16:08:32.864037185 -0500 CDT m=+171.536033156, end=2156-04-20 21:36:47.864037185 -0600 CST m=+4294967466.536033156)
Mar 14 16:08:32 myNode lnd[3278]: 2020-03-14 16:08:32.863 [INF] DISC: Creating new GossipSyncer for peer=02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b
Mar 14 16:08:32 myNode lnd[3278]: 2020-03-14 16:08:32.863 [INF] SRVR: Negotiated chan series queries with 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b
Mar 14 16:08:32 myNode lnd[3278]: 2020-03-14 16:08:32.008 [INF] SRVR: Finalizing connection to 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735, inbound=false
Mar 14 16:08:32 myNode lnd[3278]: 2020-03-14 16:08:32.008 [INF] SRVR: Established connection to: 02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b@213.174.156.70:9735
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.814 [INF] DISC: GossipSyncer(02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec): applying gossipFilter(start=2020-03-14 16:08:31.814463462 -0500 CDT m=+170.486459359, end=2156-04-20 21:36:46.814463462 -0600 CST m=+4294967465.486459359)
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.813 [INF] DISC: Creating new GossipSyncer for peer=02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.813 [INF] SRVR: Negotiated chan series queries with 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.747 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): applying gossipFilter(start=2020-03-14 16:08:31.747584475 -0500 CDT m=+170.419580390, end=2156-04-20 21:36:46.747584475 -0600 CST m=+4294967465.419580390)
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.746 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): remote peer has no new chans
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.623 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): filtering through 31710 chans
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.623 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): buffering chan range reply of size=7710
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.523 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): buffering chan range reply of size=8000
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.464 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): buffering chan range reply of size=8000
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.276 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): buffering chan range reply of size=8000
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.159 [INF] SRVR: Finalizing connection to 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080, inbound=false
Mar 14 16:08:31 myNode lnd[3278]: 2020-03-14 16:08:31.159 [INF] SRVR: Established connection to: 02f665f48119bcb606bf6f9519fa2a56ac078cfa31d7d9e34e784b1b326d9ff0ec@89.238.166.235:42080
Mar 14 16:08:30 myNode lnd[3278]: 2020-03-14 16:08:30.306 [INF] DISC: GossipSyncer(03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad): requesting new chans from height=0 and 4294967295 blocks after
Mar 14 16:08:30 myNode lnd[3278]: 2020-03-14 16:08:30.305 [INF] DISC: Creating new GossipSyncer for peer=03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad
Mar 14 16:08:30 myNode lnd[3278]: 2020-03-14 16:08:30.305 [INF] SRVR: Negotiated chan series queries with 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad
Mar 14 16:08:29 myNode lnd[3278]: 2020-03-14 16:08:29.625 [INF] SRVR: Finalizing connection to 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735, inbound=false
Mar 14 16:08:29 myNode lnd[3278]: 2020-03-14 16:08:29.625 [INF] SRVR: Established connection to: 03f86cc457090011282d8572a985f32d16ac698f0a1eb428faee02a46ad07c8cad@178.85.255.85:9735
Mar 14 16:08:28 myNode lnd[3278]: 2020-03-14 16:08:28.458 [INF] DISC: Obtained 3 addrs to bootstrap network with
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.142 [INF] CHBU: Swapping old multi backup file from /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.backup to /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/channel.backup
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.136 [INF] CHBU: Updating backup file at /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/channel.backup
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.129 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory] [lseed.bitcoinstats.com ]]
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.125 [INF] SRVR: Creating DNS peer bootstrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory] [lseed.bitcoinstats.com ]]
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.124 [INF] SRVR: Initializing peer network bootstrappers!
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.122 [INF] BTCN: Server listening on 127.0.0.1:9735
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.122 [INF] CHBU: Starting chanbackup.SubSwapper
Mar 14 16:08:24 myNode lnd[3278]: 2020-03-14 16:08:24.115 [INF] CHFT: Adding 0 channels to event store
Mar 14 16:08:23 myNode lnd[3278]: 2020-03-14 16:08:23.840 [INF] CRTR: Prune tip for Channel Graph: height=621654, hash=0000000000000000000789949a874c7a92f6983fd4aedb8e85cddeb79917cc21
Mar 14 16:08:23 myNode lnd[3278]: 2020-03-14 16:08:23.825 [INF] CRTR: Filtering chain using 36760 channels active
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.756 [INF] CRTR: FilteredChainView starting
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.736 [INF] NTFN: New block epoch subscription
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.724 [INF] BRAR: Starting contract observer, watching for breaches.
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.724 [INF] DISC: Authenticated Gossiper is starting
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.722 [INF] NTFN: New block epoch subscription
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.714 [INF] NTFN: New block epoch subscription
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.714 [INF] HSWC: Starting HTLC Switch
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.708 [INF] NTFN: New block epoch subscription
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.685 [INF] PRNF: PeerNotifier starting
Mar 14 16:08:19 myNode lnd[3278]: 2020-03-14 16:08:19.638 [INF] LTND: Chain backend is fully synced (end_height=621654)!
Mar 14 16:08:18 myNode lnd[3278]: 2020-03-14 16:08:18.660 [INF] LNWL: Finished rescan for 7 addresses (synced to block 0000000000000000000789949a874c7a92f6983fd4aedb8e85cddeb79917cc21, height 621654)
Mar 14 16:08:18 myNode lnd[3278]: 2020-03-14 16:08:18.660 [INF] LNWL: Done catching up block hashes
Mar 14 16:08:18 myNode lnd[3278]: 2020-03-14 16:08:18.657 [INF] LNWL: Catching up block hashes to height 621654, this might take a while
Mar 14 16:08:18 myNode lnd[3278]: 2020-03-14 16:08:18.648 [INF] LNWL: Started rescan from block 0000000000000000000789949a874c7a92f6983fd4aedb8e85cddeb79917cc21 (height 621654) for 7 addresses
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.545 [INF] LTND: Waiting for chain backend to finish sync, start_height=621654
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.536 [INF] RPCS: gRPC proxy started at 0.0.0.0:10080
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.534 [INF] RPCS: RPC server listening on 0.0.0.0:10009
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.530 [INF] ATPL: Instantiating autopilot with max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.527 [INF] LTND: Channel backup proxy channel notifier starting
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.491 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.489 [INF] HSWC: Restoring in-memory circuit state from disk
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.473 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.460 [INF] LTND: LightningWallet opened
Mar 14 16:08:17 myNode lnd[3278]: 2020-03-14 16:08:17.442 [INF] LNWL: The wallet has been unlocked without a time limit
Mar 14 16:08:14 myNode lnd[3278]: 2020-03-14 16:08:14.490 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Mar 14 16:08:14 myNode lnd[3278]: 2020-03-14 16:08:14.490 [INF] LTND: Initializing bitcoind backed fee estimator
Mar 14 16:08:14 myNode lnd[3278]: 2020-03-14 16:08:14.490 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Mar 14 16:08:14 myNode lnd[3278]: 2020-03-14 16:08:14.457 [INF] LTND: Primary chain is set to: bitcoin
Mar 14 16:08:14 myNode lnd[3278]: 2020-03-14 16:08:14.259 [INF] LNWL: Opened wallet
Mar 14 16:06:18 myNode lnd[3278]: 2020-03-14 16:06:18.265 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Mar 14 16:06:18 myNode lnd[3278]: 2020-03-14 16:06:18.265 [INF] RPCS: password gRPC proxy started at 0.0.0.0:10080
Mar 14 16:06:18 myNode lnd[3278]: 2020-03-14 16:06:18.259 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
Mar 14 16:06:18 myNode lnd[3278]: 2020-03-14 16:06:18.225 [INF] CHDB: Checking for schema update: latest_version=12, db_version=12
Mar 14 16:05:42 myNode lnd[3278]: 2020-03-14 16:05:42.386 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Mar 14 16:05:42 myNode lnd[3278]: 2020-03-14 16:05:42.384 [INF] LTND: Version: 0.9.2-beta commit=v0.9.2-beta, build=production, logging=default
Mar 14 16:05:42 myNode lnd[3278]: Automatically obtained bitcoind's RPC credentials
Mar 14 16:05:42 myNode lnd[3278]: Attempting automatic RPC configuration to bitcoind
Mar 14 16:05:40 myNode systemd[1]: Started LND Lightning Daemon.
Mar 14 16:05:40 myNode lnd[3279]: abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
Mar 14 16:05:40 myNode lnd[2758]: + exit 0
Mar 14 16:05:40 myNode lnd[2758]: }
Mar 14 16:05:40 myNode lnd[2758]:   "warnings": ""
Mar 14 16:05:40 myNode lnd[2758]:   },
Mar 14 16:05:40 myNode lnd[2758]:     }
Mar 14 16:05:40 myNode lnd[2758]:       "height": 481824
Mar 14 16:05:40 myNode lnd[2758]:       "active": true,
Mar 14 16:05:40 myNode lnd[2758]:       "type": "buried",
Mar 14 16:05:40 myNode lnd[2758]:     "segwit": {
Mar 14 16:05:40 myNode lnd[2758]:     },

**Comment by Roasbeef** [comment]
Do you have the `stderr` output?

**Comment by Roasbeef** [comment]
Also which version of Go did you build the binary with?

**Comment by Amiga500** [comment]
sorry but i'm not so expert with these things, if you tell me which commands use i made it now! :)

**Comment by Roasbeef** [comment]
From the logs, it also looks like the first few instances of the reboot `lnd` was _instructed_ to do so.

**Comment by Amiga500** [comment]
oh good then, on LND 0.9.1 i had multiple reboots.. so now i was thinked that the behaviour was the same. For now happened only one time

**Comment by Roasbeef** [comment]
So is it stuck in a reboot loop, or is it running as normal now?

**Comment by Amiga500** [comment]
Now it's running as normal, i check it for next hours.. if there will be issues i let you know. 
Thanks for all your work! ;)

**Comment by Amiga500** [comment]
No more happened! I close it
