### ISSUE TITLE
Inconsistent interface for node `addresses`

### ISSUE THREAD

**Issue by litch** [lightningnetwork/lnd#4084]
### Background

I'm consuming the rpc server (through a couple of other libraries) and am having to write some kind of janky code to deal with this inconsistent interface for a node.  Usually a `Node` has a collection of `addresses` that are `[]net.Addr`.  In one case, though, the occupier of that field is a `[]string`.

### Your environment

* version of `lnd`: 0.9.1
* which operating system (`uname -a` on *Nix): all of them
* version of `btcd`, `bitcoind`, or other backend: bitcoind (but it's irrelevant)

### Steps to reproduce

I *THINK* it is here:

https://github.com/lightningnetwork/lnd/blob/7f7805494cda829b71cee279602ba104ea5ea2ba/rpcserver.go#L4409-L4426

[]*lnrpc.NodeAddress

vs 

https://github.com/lightningnetwork/lnd/blob/7f7805494cda829b71cee279602ba104ea5ea2ba/rpcserver.go#L4838-L4852

[]string

I'm pretty sure that the update object that is being handled there *has* the network info - I think it is a `NetworkNodeUpdate`

https://github.com/lightningnetwork/lnd/blob/08ebefa8a33debe43d6b468341f4f152c882007c/routing/notifications.go#L232

### Expected behaviour

I would prefer the `nodeUpdates` returned a `[]net.Addr`, rather than a `[]string`. 

So I think that it makes sense for the interface to be unified, and I think that the []string instance is a mistake/oversight.  However, I'm reluctant to change this interface, since it gets consumed by a few other libraries and would have some cascading changes (that would all be good, I think).  For example, @alexbosworth 's `lightning` library consumes this alternate interface: https://github.com/alexbosworth/lightning/blob/master/grpc/protos/rpc.proto#L2374

Which then gets propagated to https://github.com/alexbosworth/ln-service where it then runs into my application code. 😄

Let me know if you think a fix to this would have a chance of getting accepted, and in that case I'll take a shot at it.

### Actual behaviour

The node object in `nodeUpdates` has a `[]string`.

**Comment by wpaulino** [comment]
One approach is to add a new field of type `[]*lnrpc.NodeAddress` and mark the existing one as deprecated.

**Comment by alexbosworth** [comment]
I'd prefer the deprecated approach because due to lack of versioning signaling it is difficult to match up a proto with an arbitrary LND
