### ISSUE TITLE
Persist and export HTLC settles per commitment height

### ISSUE THREAD

**Issue by carlaKC** [lightningnetwork/lnd#4088]
To reliably account for movement of funds within a channel, nodes require a reliable record of the htlcs that were settled as we update our commitment. This information _could_ be reconstructed from the forwarding log, invoices db and payments db, but to do so would not be robust enough for our purposes. Part of accounting project, tracked in #3942. 

### Steps to Completion
- Allow nodes to run in `accounting` mode which indicates that they wish to persist additional information for the sake of reliable accounting. Off by default, enabled by a command line flag
- Persist htlc settles by commitment height in a new accounting bucket, with the top level structure similar to the existing `openChannelBucket`:
```
[accounting-bucket]
    [channel-point-bucket]
      [commitments-bucket]
        [height-bucket]
          [timestamp]
          [commitment tx hash]
          [htlc-settles-bucket]
```
- Expose this information over a paginated rpc endpoint:
```
Rpc ChannelCommits (ChannelCommitsRequest) ChannelCommitsResponse
 
Message ChannelCommitsRequest{
  Oupoint chan_point = 1;
  uint64 start_height = 2;
  uint64 end_height = 3;
  index_offset = 4;
  num_max_events = 5;
}
 
Message Commit{
  // The height of the commit. 
  uint64 height = 1;
 
  // The commitment transaction hash.
  bytes commitment = 2;
 
  // The htlcs that were settled by this commit.
  repeated htlc settled_htlcs = 3;
}
 
message ChannelCommitsResponse{
  repeated Commit commits =1;
}

```

**Comment by Roasbeef** [comment]
> This information could be reconstructed from the forwarding log, invoices db and payments db, but to do so would not be robust enough for our purposes.

Why isn't the current on-disk information sufficient? If we need to add information that can't be obtained retroactively for existing nodes, then the usefulness of something like this is significantly reduced. 

In the past the rationale for this new bucket was that we don't have enough information to correctly identify HTLC level changes on the commitment transaction (we have two HTLCs, they're both gone in the next state, what happened?). Based on my current mental model of the system, we _do_ indeed have all the information we need:
  * We can identify any outgoing payments by looking in the payment database. The router initiates any state transitions for outgoing payments in the link. Upon restart, any inconsistencies will be reconciled as we need to do so for normal operation.
  * Any incoming settles can be identified with a combination of the revocation log and the invoices database. If an HTLC exists in one state, but not the other, the invoice DB should be checked to see if we've settled the HTLc. The latest invoice database now also maintains _per HTLC_ level information for each invoice as well. 

With that said, is there something I'm missing here?

**Comment by carlaKC** [comment]
> If we need to add information that can't be obtained retroactively for existing nodes, then the usefulness of something like this is significantly reduced.

I'm don't think it **significantly** decreases the usefulness. Going forward people will be opening new channels when wumbo arrives, and it will be very worthwhile for them to have a reliable account of how funds move in those channels. 

I'm still building up a complete mental model of this part of the codebase, so I'm probably off on this one, but I think the missing information would be for incoming forwarded htlcs (assuming that the forwarding log is not consistent), since they are not in the invoices database. 

Had another look at possible solutions, and I think everything we need is in `revocationLog` + `fwdPkg`:
- Keep revocation log around after channel close, add `ChanStatus=Archived`
- If running in accounting mode, do not delete forwarding package
- To get per commit settles, diff commits as expected then look at forwarding log for appropriate height to determine whether the htlcs were settled/failed

I think it's a really important part of accounting to include forwarding information, because that's currently one of the least visible aspects of a channel to people building on lnd; your own invoices/payments are accounted for well enough, but sometimes sats shift back and forth without your noticing (htlc notifier helps, but has the same issue as forwarding log).

**Comment by joostjager** [comment]
>With that said, is there something I'm missing here?

@Roasbeef, I think the htlc interceptor settles are missing here.Especially in the case of external invoice handling through the interceptor,

**Comment by carlaKC** [comment]
Replaced by #7840, which should achieve this with a much lighter disk footprint.
