### ISSUE TITLE
Structure of the data directory

### ISSUE THREAD

**Issue by stevenroose** [lightningnetwork/lnd#409]
Right now, this structure is created:
```
├── admin.macaroon
├── bitcoin
│   └── testnet
│       └── wallet.db
├── macaroons.db
├── readonly.macaroon
└── testnet3
    └── bitcoin
        └── channel.db
```

It's kinda confusing that there is a `bitcoin/testnet` and `testnet3/bitcoin`. I think both `channel.db` and `wallet.db` could live in `<protocol>/<network>/`..

**Comment by Roasbeef** [comment]
The current structure is a hold-over as it's mid way between being able to support multiple chains. In a future of multiple chains, the `channel.db` file would be in a distinct folder as it would be shared across all other instances. In this case, it would look something like: 
```
├── chain
│   └── bitcoin
│        └── testnet
│           ├── block_headers.bin
│           ├── ext_filter_headers.bin
│           ├── neutrino.db
│           ├── peers.json
│           ├── reg_filter_headers.bin
│           └── wallet.db
└── graph
    └── testnet 
        └── channel.db
```

Agreed that the current structure is confusing and sub-optimal. Before `0.4-beta` is released, we want to have a set directory structure which factors in future extensions.

**Comment by stevenroose** [comment]
Perfectly understandable, just keeping this for the record.

Quick thing: does `./graph/testnet/` mean that both litecoin-testnet and bitcoin-testnet will be considered equivalent and share a db, while bitcoin-mainnet and litecoin-mainnet also share one? That's neat.

**Comment by Roasbeef** [comment]
> while bitcoin-mainnet and litecoin-mainnet also share one

Yep, that's the plan! Stay tuned for some news soon on the implications of this 😉
