### ISSUE TITLE
Add buildroute functionality to REST API

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#4100]
### Background

I am looking to create a custom route in the REST API. Especially when creating routes that dont originate at your own node, the queryroute API does not help.

### Your environment

* version of `lnd`
LND master
* which operating system (`uname -a` on *Nix)
ubuntu
* version of `btcd`, `bitcoind`, or other backend
btcd
* any other relevant environment details

Unrelated, but what is the format LND is expecting for arrays in query parameters? queryroute uses an array for 'ignored_nodes', and I cannot get it to work.

**Comment by wpaulino** [comment]
> Unrelated, but what is the format LND is expecting for arrays in query parameters? queryroute uses an array for 'ignored_nodes', and I cannot get it to work.

Maybe have a look at https://swagger.io/docs/specification/serialization/?

**Comment by sako0938** [comment]
Thanks @wpaulino that doc should really be stickied somewhere!
The problem for that issue, happened to be I needed to percent-encode my base64 query parameter or else I get the error:
```{'error': 'illegal base64 data at input byte 22', 'message': 'illegal base64 data at input byte 22', 'code': 3, 'details': []}```

**Comment by sako0938** [comment]
In addition, last_hop_pubkey of queryroute needs to be percent-encoded base64 also. I'm starting to see the pattern, but it isn't called out explicitly like most everywhere else.

**Comment by wpaulino** [comment]
> I'm starting to see the pattern, but it isn't called out explicitly like most everywhere else.

@sako0938 correct, when using the REST API, all `byte` fields are interpreted as them being base64 encoded. It's noted in our [current main documentation](https://api.lightning.community/), but it hasn't been extended to document functionality found in sub-servers yet.
