### ISSUE TITLE
Authentication failure when connecting to btcd

### ISSUE THREAD

**Issue by AllanLindJensen** [lightningnetwork/lnd#4115]
### Background

LND log - after wallet is unlocked:
2020-03-25 13:03:38.336 [INF] LTND: Initializing btcd backed fee estimator

BTCD log
2020-03-25 13:03:38.374 [WRN] RPCS: RPC authentication failure from 127.0.0.1:48144
2020-03-25 13:03:43.421 [WRN] RPCS: RPC authentication failure from 127.0.0.1:48146
etcetera

### Your environment

* lnd version 0.9.0-beta commit=v0.9.0-beta-378-gf5e364071bfe35a6d943928d8a051216cb61ace4

* which operating system : Ubuntu 18.04.4
* version of `btcd`: btcd version 0.20.1-beta
* any other relevant environment details
  go version go1.14.1 linux/amd64
  btcd has data no in $HOME: btcd --datadir=/media/allan/btcd/.btcd --txindex > /dev/null

### Steps to reproduce

It happened after updating btcd and lnd Friday March 20th and rebuild.

### Expected behaviour

Tell us what should happen

### Actual behaviour

LND connot logon to btcd.
btcctl works.

**Comment by Roasbeef** [comment]
Looks like an auth issue on your end. Don't think there's anything `lnd` specific here. Double check your config for `btcd` and `lnd` to make sure things line up properly.

**Comment by AllanLindJensen** [comment]
I agree it must be an error my end. When user and pass are identical in btcd.conf and lnd.conf, then

lnd output: "Unable to start server: -32602: parameter #2 'verbosity' must be type int (got bool)"
btcd.log: "[ERR] RPCS: Websocket receive error from 127.0.0.1:50152: websocket: close 1006 unexpected EOF"

**Comment by AllanLindJensen** [comment]
Should I close this issue, and create a new one?

**Comment by guggero** [comment]
This looks like the same problem as in https://github.com/lightningnetwork/lnd/issues/4076.
Make sure you really are using `btcd v0.20.1-beta` and not `master`. Any version newer than `v0.20.1-beta` is **not** compatible with btcd.
