### ISSUE TITLE
Text error in docker readme?

### ISSUE THREAD

**Issue by cilphex** [lightningnetwork/lnd#4116]
### Background

I think there is a text error in this file:

https://github.com/lightningnetwork/lnd/blob/master/docker/README.md

It contains the text "All state is saved between instances using a shared _value_." I think that _value_ should read "_volume_".

I may be wrong, would be helpful to know if others agree.

**Comment by guggero** [comment]
Yes, you are correct. It's supposed to say `volume`. You're welcome to add a PR to fix it, I'll review.

**Comment by cilphex** [comment]
@guggero https://github.com/lightningnetwork/lnd/pull/4117
