### ISSUE TITLE
CLTV tie-breaking doesn't seem to be working

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lnd#4118]
I've been doing compatibility tests on https://github.com/lightningnetwork/lightning-rfc/pull/491 (since we're very late to the party and never merged support for that in eclair :fearful:)

C-lightning correctly orders duplicates by cltv, but lnd-0.9.2-beta doesn't (I think it should, since https://github.com/lightningnetwork/lnd/pull/3142 appears to add that feature).

It's easy to repro. In an Alice -> Bob setting, have Alice send the following two HTLCs:

- HTLC 1: amount1, paymentHash1, cltv1
- HTLC 2: amount1, paymentHash1, cltv1 - 1

Bob will send the htlc signatures in the wrong order: (sig for HTLC 1, sig for HTLC 2).
It should send (sig for HTLC 2, sig for HTLC 1).

**Comment by cfromknecht** [comment]
@t-bast that's interesting, we have a [test case for commitment sorting](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/commit_sort_test.go#L163) that is exactly what you describe. perhaps there's a more subtle issue in how it is applied to the commitment. i will try to repro and get back to you.

**Comment by t-bast** [comment]
Maybe there's no issue producing the commitment, but it only appears when providing the signatures for that commitment for some reason?

Don't hesitate to let me know if you're unable to repro and want logs or something.

**Comment by cfromknecht** [comment]
@t-bast indeed the issue was that the commitment was properly sorted, but the order of the HTLCs on the wire was not applying the tie-breaker. Should be fixed by #4121 and included in 0.10, thanks for the report!

**Comment by t-bast** [comment]
Cool, thanks for the quick fix!
