### ISSUE TITLE
LND becomes unresponsive and fills RAM/swap after a few 'listpayments' calls

### ISSUE THREAD

**Issue by Horndev** [lightningnetwork/lnd#4119]
### Background

LND freezes and can't be stopped - consumes all available RAM. 

When the process starts, unable to attempt graceful shutdown.  Only way to reset is to kill process.

The listpayments call is used to check if a payment was successful or failed.  The payments DB has become quite large (10K+ payments).  

I am hoping that PR #3960 will fix this, but even so - LND should not crash like this so I am wondering if there is a larger issue at play.

### Your environment

* version of `lnd`: 0.9.0-beta commit=v0.9.0-beta-287-gb6a0bfcabe382e828eba6b95b6f9f1dcb9d8e6b6
* Ubuntu
* bitcoind

### Steps to reproduce

Start LND, run for a while.  Make calls to listpayments RPC (either via lncli or REST interface).

The first few calls will work, but eventually LND will go into an unresponsive mode and start consuming RAM.

### Expected behaviour

LND should return an error if necessary - should not crash entire node.

### Actual behaviour

Runaway RAM usage.

**Comment by Horndev** [comment]
I dumped the listpayments result to a file and it was 211 MB in ASCII!!  This is likely the reason for the fail, since it appears in code that the DB result is loaded into memory and then formatted into the response.  Multiple calls to this method (while waiting for previous calls to complete) could overwhelm LND.

I think what is happening is that the call is timing out - causing my scheduler to retry later, while also queuing up new calls, until the number of calls is becoming very large.  This then causes LND to crash. 

I deleted the payments history from the channel DB using delete on /v1/payments and I will monitor if this fixes it.

If this is the cause of the problem, I am even more confident the PR mentioned will fix the issue.  I will monitor this to confirm.

**Comment by bitromortac** [comment]
PR #3960 will unfortunately not solve this problem, as all payments are still loaded into memory afterwards. It will just lessen the burden on data transfer from the node to the API consumer. To be more efficient, one would need to do some changes in the database, but that's the next step then.

**Comment by Horndev** [comment]
Looks like #4164 will be a step closer to solving this.

**Comment by Roasbeef** [comment]
Closing as #4261 has been merged.
