### ISSUE TITLE
Channel Acceptor Available on REST API

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#4120]
### Background

It would be great to be able to use the channel acceptor RPC from the REST API.

### Expected behaviour

I would like to have an application which uses thread to monitor the channel acceptor streaming API.

### Actual behaviour

You are only able to configure this through the gRPC interface, not through command line or REST.

**Comment by Roasbeef** [comment]
Not possible as is, since this is a bi-di streaming RPC, and the new websockets support only supports server streaming (only server sending messages).

**Comment by sako0938** [comment]
It is possible to do however if client message became supported?

This is a pretty powerful feature, so I’d love to use it.
