### ISSUE TITLE
Add timeout parameter/option for ConnectPeer(Request)

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#4123]
### Background

I could use a timeout=  setting in the `ln.ConnectPeerRequest` request, and in `lncli connect`. Now it seems to timeout after 2 minutes [?]. Being able to set this for a certain amount of seconds will make my application a bit smoother.

### Your environment

* LND 0.9.1-beta commit=v0.9.1-beta
* CentOS 8 (4.18.0-147.5.1.el8_1.x86_64)
* bitcoind bitcoin-0.18.1

### Steps to reproduce

Try to connect to an inactive node:
```lncli connect 02596a686579585d52bf1e9f560b470378c64450b4411a86577a200387432cf8cd@82.64.147.203:9735```
Wait around 2 minutes.
See a failure message.

### Expected behaviour

If I am able to set a 10 second timeout I do not have to wait long :).

### Actual behaviour

It times out after about 2 minutes.

**Comment by yyforyongyu** [comment]
i'm working on this one.

**Comment by BhaagBoseDK** [comment]
I noticed that for many peers the timeout does not work. I have a 5 second timeout but sometimes I see delays of 3+ minutes

Call
`response = stub.ConnectPeer(request = ln.ConnectPeerRequest(addr=address, perm=False, timeout=5))
`
result

```
Mon Sep  5 11:07:46 2022 : ... Attempting connection to peer.alias='MidasMulligan' inactive_peer='03fd21fdee8e9adc070b53a0bca8685cbc0b97f27b72f364723dcc54b4164ab21b' host='322e5mbonli3h4r4la6ox2gt2cm534k7uk3cbl6yr34rtxyfnj6mdiid.onion:9735'
Mon Sep  5 11:11:39 2022 : .... Error reconnecting MidasMulligan inactive_peer='03fd21fdee8e9adc070b53a0bca8685cbc0b97f27b72f364723dcc54b4164ab21b' str(e)='<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = "dial proxy failed: socks connect tcp 10.21.21.11:9050->322e5mbonli3h4r4la6ox2gt2cm534k7uk3cbl6yr34rtxyfnj6mdiid.onion:9735: unknown error general SOCKS server failure"\n\tdebug_error_string = "{"created":"@1662376299.194364800","description":"Error received from peer ipv4:10.21.21.9:10009","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"dial proxy failed: socks connect tcp 10.21.21.11:9050->322e5mbonli3h4r4la6ox2gt2cm534k7uk3cbl6yr34rtxyfnj6mdiid.onion:9735: unknown error general SOCKS server failure","grpc_status":2}"\n>'

```
