### ISSUE TITLE
Change address in channel opening used derivation path `m/1017'/0'/0'/1/0`, which the on-chain recovery misses

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#4127]
*Disclaimer: I am sorry for the following un-reproducable issue. But I am posting it to see if anyone has some inputs as to how this could have happened as it is bothering me.*

I had a corrupt `channel.db` file and therefore had to recover my on-chain funds using the AEZEED mnemonic.

Prior to having the corrupt database I was using the autopilot, which had opened exactly one channel to some other node (nearly one month ago).

When I recovered my on-chain funds I realized that only a small fraction of my on-chain balance had been recovered. After numerous tries I realized the following:

Recovering my wallet using my mnemonic with the `create` command looks for funds on the derivation path `m/84'/0'/0'/0/i` and `m/84'/0'/0'/1/i`, which I think is the standard thing to do in `lnd`. However, the change address from the old channel opening appears to be on the exact derivation path `m/1017'/0'/0'/1/0` and was therefore not caught when recreating the wallet. I searched through this derivation path manually because I found it as a comment in the source file:
https://github.com/lightningnetwork/lnd/blob/a2336005e650b33a708081cee18eff8739d0b245/keychain/derivation.go#L24

As far as I understand it this exact derivation path should have been used for a revocation key? But can it also be chosen for a change address when opening channels?

I have tried all kind of things also using regtest trying to reproduce this issue without success.

One more thing: I did have the same problem with a corrupt db a month ago where I successfully recovered the wallet using the SCB (from another previous channel) in `channel.backup` via `create --multi_file`. But even trying to reproduce this does not result in this issue...

Any ideas as to how this could have happened? I still have the corrupted `channel.db` and old `channel.backup` file and the mnemonic. Unfortunately I did delete the `lnd` directory with logs. But I can also directly provide information on the transaction id for the channel opening the weird change output and provide the mnemonic and show the different addresses with their derivation paths.

### Your environment

* version of `lnd`: v0.9.0 (or v0.9.1, I am not completely sure at this point)
* which operating system (`uname -a` on *Nix): Linux (Raspberry Pi)
* version of `btcd`, `bitcoind`, or other backend: `bitcoind v0.19.0.1`

### Steps to reproduce

Unfortunately not possible, see description above.

**Comment by alexbosworth** [comment]
May want to look at this: https://github.com/btcsuite/btcwallet/pull/682

**Comment by Roasbeef** [comment]
Yep see the commit above. Note that this issue only applies to master or `v0.9.1`.

**Comment by Roasbeef** [comment]
Also it isn't unusual that it's hard to repro this bug, given that the bug itself is caused by pseudo-random behavior (map iteration order).

**Comment by bjarnemagnussen** [comment]
Ah thanks for the info! Good to know that this behaviour is known. And I won't have to lose my sanity over not being able to reproduce this, as it seemed so strange to me :)
