### ISSUE TITLE
Abstract graph functionality to interface

### ISSUE THREAD

**Issue by mlerner** [lightningnetwork/lnd#413]
As noted in a [TODO in routing/graph.go](https://github.com/lightningnetwork/lnd/blob/215d57acb9c145fb98eef7463e736a88ae7ebd2d/routing/graph.go#L3), it would be ideal to refactor some routing code to use an interface, rather than a concrete instance of `channeldb.ChannelGraph`. These changes would allow for graph operations to be abstracted.

An example of possibly affected code is the `findPaths` method, which accepts a `channeldb.ChannelGraph`, source LightningNode, and target PublicKey and returns a list of possible paths - in the future, this could accept a `Graph`, source `Vertex` and a target `Vertex` and perform the same path finding algorithm.

**Comment by KarolStrzelec** [comment]
hi what do you think about this solution?
https://drive.google.com/file/d/1H0SLt2ntS2yqjJ7lkeisFhyHLIFH070D/view?usp=sharing

**Comment by Roasbeef** [comment]
Graph interfaces are used in specific locations as needed in the current codebase.
