### ISSUE TITLE
0-conf channel opening

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4136]
### Background

Be able to operate a channel before it's funding transaction gets mined.

### Your environment

* version of `btcd`, `bitcoind`, or other backend

I would assume this would only work with btcd or bitcoind, as lnd don't received data from mempool AFAIK. and 0-conf channel required mempool data 

### Expected behavior

Currently, the min-channel size is 1. I'd like to understand how to have 0 instead. 

I know it's not for every use cases, but for some use case this makes sense (ie: Phoenix wallet does this, and it shifts the trust assumption from "trustless" to trust-minimized)

This would assume both nodes want to operate with this particular flag/mode, and as I guess this would not be compliant to bolt.

**Comment by nicolasburtey** [comment]
I started looking at the code and I guess the action lies in fundingmanager.go.

One of my first interrogations is regarding `pendingChanID`. I guess we need to abstract this?

I’ll continue digging in in the upcoming days, but I’d love to have some feedback around this.

**Comment by halseth** [comment]
Related: #4424

**Comment by tvolk131** [comment]
Related: #5955

**Comment by morehouse** [comment]
Another zeroconf issue I think we can close.
