### ISSUE TITLE
Store and display when multiple payments sent using the same invoice

### ISSUE THREAD

**Issue by bryanvu** [lightningnetwork/lnd#414]
When a user sends multiple payments using the same payment request, the sender of the payment will only see one payment in response to the listpayments RPC. This is due to the payments being keyed by payment hash in the database. This will result in the payments shown being inconsistent with the channel balance. (Originally reported by fei via Slack)

**Comment by nalinbhardwaj** [comment]
I’d like to try this.

**Comment by mlerner** [comment]
I can work on this.

**Comment by mlerner** [comment]
After investigating more, and talking with Fei, it seems like the `listpayments` method is operating as desired. The code indicates that `listpayments` ["returns all outgoing payments in DB"](https://github.com/lightningnetwork/lnd/blob/2b2a3714c16791aaf7626fdfcda50331657e319d/channeldb/payments.go#L87). 

The `listpayments` code currently shows multiple _outgoing_ payments for a single payment hash: 
![listpayments](https://user-images.githubusercontent.com/181935/33521407-0767b22e-d786-11e7-920a-c38860601f10.png)

A method could be added to list all incoming payments if desired, to account for someone reusing a payment hash. Whether an invoice has been settled can also be checked with existing functionality (using the output of the `listinvoices` method).

**Comment by Roasbeef** [comment]
Closing due to @mlerner's report.
