### ISSUE TITLE
Windows refuses LND's connection

### ISSUE THREAD

**Issue by Relaxo143** [lightningnetwork/lnd#4146]
Hello! I haven't encountered this before - shortly after upgrading to 0.9.2-beta I get this error when starting LND: `dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.` I run Bitcoin Core 0.19.1 and Windows 10. I tried running lnd with the firewall disabled with no success. Any help would be appreciated!

**Comment by guggero** [comment]
The port 9050 is usually used for Tor. Did you activate anything Tor related in lnd? Could you perhaps post your configuration and/or command line parameters?

**Comment by Relaxo143** [comment]
You just gave me a huge clue, thanks. I've configured LND to run over Tor. However my tor client is not running properly (I think) so I stopped it. I get this warning message (sorry if it's off topic): 
`Guard  is failing a very large amount of circuits. Most likely this means the Tor network is overloaded, but it could also mean an attack against you or potentially the guard itself. Success counts are 123/258. Use counts are 84/84. 215 circuits completed, 0 were unusable, 93 collapsed, and 6 timed out. For reference, your timeout cutoff is 60 seconds.`
Is it safe to run Tor with this warning? Not running it is probably the reason why lnd is not starting up. Thanks again!

**Comment by guggero** [comment]
I'm not sure how `lnd` uses Tor exactly or what the error means in detail. But I know that `lnd` tends to open many circuits and that this can be challenging for the Tor client. So my _guess_ is, it's a load issue. But as I said, I'm not too familiar with the internals.

**Comment by Roasbeef** [comment]
Closing as this is resolved. Opening a new issue to possibly tune the amount of circuits we use.
