### ISSUE TITLE
Add unconfirmed wallet balance to walletbalance RPC

### ISSUE THREAD

**Issue by bryanvu** [lightningnetwork/lnd#415]
Currently, the walletbalance RPC returns the fully confirmed wallet balance. This can be confusing when a channel is opened with a particular amount, but a larger amount appears to be subtracted from the wallet balance until the change transaction is confirmed. This also creates confusion in the App UI. One solution would be to have the RPC return both the balance and the unconfirmed amount, and have the App display both. (Originally reported by several users via Slack, including moli and fei.)

**Comment by nalinbhardwaj** [comment]
Taking this :)
