### ISSUE TITLE
Increasing unconfirmed wallet balance when using SendOutputs 

### ISSUE THREAD

**Issue by jacohend** [lightningnetwork/lnd#4150]
### Background

Use of SendOutputs results in ever-larger "unconfirmed balance" in the wallet. 

### Your environment

* Version: 0.9.2-beta
* Linux 4.4.0 x86_64
* Neutrino

### Steps to reproduce

Send several OP_RETURN outputs via 
```
	b := txscript.NewScriptBuilder()
	b.AddOp(txscript.OP_RETURN)
	b.AddData(hash)
	outputScript, err := b.Script()
	outputs := []*signrpc.TxOut{
		&signrpc.TxOut{
			Value:    0,
			PkScript: outputScript,
		},
        }
	outputRequest := walletrpc.SendOutputsRequest{SatPerKw: estimatedFee.SatPerKw, Outputs: outputs}
	resp, err := wallet.SendOutputs(context.Background(), &outputRequest)
```

### Expected behaviour

After waiting a while, we should see the change outputs accumulating in confirmed_balance.

### Actual behaviour

Eventually all change accumulates in unconfirmed_balance and stays there forever. 

I'm not sure if I'm reading this right, but I think the issue might be [here](https://github.com/btcsuite/btcwallet/blob/60299130c647f27394e818079e2a0705e6aa8e60/wallet/createtx.go#L137) in the wallet file "txcreate.go".

**Comment by wpaulino** [comment]
Do you still see this issue after applying https://github.com/lightningnetwork/lnd/pull/4091?

**Comment by jacohend** [comment]
I'll test that fix for a few days and let you know.

**Comment by jacohend** [comment]
@wpaulino The patch does seem to be working for us. I'm not seeing any unconfirmed return outputs. I'll update if anything changes.

**Comment by jacohend** [comment]
@wpaulino We're still seeing this issue, unfortunately. 

These [funds](https://www.blockchain.com/btc/address/bc1qxmpru5jey99ta442u6slkzqr69af8y9y9d6ntf) still haven't returned to our wallet. Our recovery window is 10000, and we've tried clearing the chainstate and reloaded. Our current balance on that node is `{"total_balance":"1855318","confirmed_balance":"668","unconfirmed_balance":"1854650"}`

**Comment by jacohend** [comment]
It looks like the rescan is starting from a greater start height (627570) than that last transaction (627457) could this have something to do with it?

**Comment by wpaulino** [comment]
Could you attempt another sync with `debuglevel=BTCN=debug,LNWL=debug` in your configuration file to see if it provides any relevant logs?

**Comment by Roasbeef** [comment]
>  and we've tried clearing the chainstate and reloaded

What does that mean exactly?

**Comment by jacohend** [comment]
@wpaulino I'll try that and get back to you. 

@Roasbeef We cleared block_headers.bin, reg_filter_headers.bin, neutrino.db, and ran dropwtxmgr on the wallet.db. After full reload the node temporarily registers our balance as confirmed again, but subsequent chain transactions lead to (apparently) the same failure to register the unspent output, leading to all balance being "unconfirmed" again.

**Comment by Roasbeef** [comment]
> I'm not sure if I'm reading this right, but I think the issue might be here in the wallet file "txcreate.go".

What makes you believe this is the case? Other weird thing here is creating a zero-valued output.

**Comment by jacohend** [comment]
> What makes you believe this is the case? 

 It would explain why, prior to @wpaulino's patch, the address the unspent output is returned to is not registered as part of the wallet balance. The patch does seem to have fixed this issue on our other nodes, but as mentioned we still have a node where transactions don't get properly broadcast and where the balance is unconfirmed except right after a full reload of state. 

> Other weird thing here is creating a zero-valued output.

Is an OP_RETURN weird? Or mean you just in the context of SendOutputs?

**Comment by Roasbeef** [comment]
> Is an OP_RETURN weird? Or mean you just in the context of SendOutputs?

Just in the context of `SendOutputs`.

**Comment by Roasbeef** [comment]
> I should mention that the chain transaction in question never seems to be included in a block after broadcast.

Do you see any logs where the backing full node, or nodes it's connected to (on the P2P network), _reject_ the transaction?

**Comment by jacohend** [comment]
>Do you see any logs where the backing full node, or nodes it's connected to (on the P2P network), reject the transaction?

We don't see any rejection messages. Just no response to the inv message.

**Comment by wpaulino** [comment]
Depending on your peers (certain bitcoind versions), they may not send back reject messages. They also won't send them again if they've already ack'd receiving the transaction, whether it was valid or invalid.

**Comment by wpaulino** [comment]
@jacohend I assume you haven't experienced this issue in a while then?
