### ISSUE TITLE
Can not unlock wallet (authentication handshake failed: x509)

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#4153]
### Background

Hi,
I've logged to my node and show that lnd is not working, I've restarted the node, but now when I am trying to unlock the wallet I get:
```bash
admin@rock64:~$ lncli unlock
Input wallet password: 
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```
I've tried restarting the node a couple of times, but it did not help.

Any help?

### Your environment
```bash
admin@rock64:~$ lnd --version
lnd version 0.9.1-beta commit=v0.9.1-beta

admin@rock64:~$ uname -a
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux

admin@rock64:~$ bitcoind --version
Bitcoin Core Daemon version v0.18.0

```

**Comment by MrManPew** [comment]
Ok, I've solved it. I installed lnd using raspibolt manual, and for some reason, it was searching for the cert file in  admin/.lnd but lnd create the file in bitcoin/.lnd so I had to manually move it from bitcoin/.lnd to admin/.lnd

**Comment by carlaKC** [comment]
Glad you figured it out!
