### ISSUE TITLE
lnd hangs without logs when tor socks port is set to tor control port

### ISSUE THREAD

**Issue by gkrizek** [lightningnetwork/lnd#4154]
### Background

This tripped me up longer than I want to admit. I accidentally set my `tor.socks` port to the same port as `tor.control`. When this happens, `lnd` simply hangs with no log messages at all, even with `--debuglevel=trace`. When trying to kill the process with `Control+C` you get a shutdown message but the process doesn't actually exit. You must do `kill -9` to get exit the process.

### Your environment

- lnd version 0.9.1-beta commit=v0.9.1-beta
- Ubuntu Xenial Docker Image (Linux a6deda9059c1 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
- btcd backend (btcd version 0.20.1-beta)

### Steps to reproduce

Create a `lnd.conf` file with the follow Tor config:

```
[tor]
tor.active=true
tor.socks=9051
tor.control=9051
```

Try to run lnd with `lnd --configfile=/path/to/conf`.

Alternatively, you can exclusively use cli flags:

`lnd --tor.active --tor.socks=9051 --tor.control=9051 ...`

### Expected behaviour

I think it would be good at the very least to log something and handle a SIGTERM. Any indication or pointer to the problem would be very helpful instead of nothing. Not sure if there's a network level check you can do for this error. Perhaps just seeing if `tor.socks` and `tor.control` are the same port is sufficient to error out. However, this still happens if you only specify `tor.socks` and not set `tor.control` at all.

### Actual behaviour

lnd hangs with no output and doesn't respect SIGTERM.

**Comment by ErikEk** [comment]
I have identified the issue. I'm working on it.
