### ISSUE TITLE
How to set default `fee_rate` and `base_fee_msat` values for new channels?

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#4156]
How to set default `fee_rate` and `base_fee_msat` values for new channels? `OpenChannel` seems to not give this option. The documentation for `UpdateChannelPolicy` leads me to believe that only existing channels' policies are updated, not new ones. Is there a way to permanently change the defaults in lnd.conf?

**Comment by AndySchroder** [comment]
Okay, so I found out that `lnd -h` shows a lot of options. I guess `sample-lnd.conf` is not exhaustive and  `lnd -h` shows everything that could go in the command line or `lnd.conf`?

**Comment by peername** [comment]
lnd.conf:
bitcoin.basefee=1000 
bitcoin.feerate=1

**Comment by guggero** [comment]
The `sample-lnd.conf` is not generated automatically so it happens a lot that contributors forget to update it. But every option that is listed in `lnd -h` can be used in the `lnd.conf` file (without the `--` obviously).

**Comment by AndySchroder** [comment]
`OpenChannel` seems to now allow setting `fee_rate` and `base_fee`. Not sure when this was added.
