### ISSUE TITLE
Add "to" address to listchaintxns RPC

### ISSUE THREAD

**Issue by bryanvu** [lightningnetwork/lnd#416]
Currently, the on-chain transactions list doesn't include addresses. In order to make transactions easier to identify, we should display the destination address for each transaction. This would also be useful for the Transactions page in the App, as Bitcoin users are accustomed to seeing addresses in transaction lists. Note that "from" addresses would require significantly more infrastructure to provide, as that would require a full transaction index. (Originally requested by fei via Slack)

**Comment by mlerner** [comment]
I am going to work on this.

**Comment by Roasbeef** [comment]
Fixed by #426.
