### ISSUE TITLE
Unable to send payment through POST /v1/channels/transactions

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#4171]
Two users tried to send payment with lnd v0.8.0, 0.8.2 and 0.9.0 but they are unable to send the payment through RTL/ZAP. They can still pay the invoice from lncli. The LND console and API response sends the error as:

* [ERR] RPCS: [/lnrpc.Lightning/SendPaymentSync]: checksum failed. Expected atuqrp, got wzz8es.
* {"error":"checksum failed. Expected ksa3s9, got aaa5gn.","code":2}

* version of 0.8.0/0.8.2/0.9.0
* OS Unix
* bitcoind v0.19.01

Related Issue:
https://github.com/Ride-The-Lightning/RTL/issues/283

**Comment by guggero** [comment]
Discussed this in Slack. Not sure this really is an lnd issue. I can reproduce if I delete a few characters from an invoice. Please make sure the full, complete invoice is sent to lnd and no browser/UI issue is truncating anything. If possible to reproduce, a full REST request (or at least the JSON request payload) would be helpful.
