### ISSUE TITLE
Closed channel - funds appear to be in limbo

### ISSUE THREAD

**Issue by padgamer** [lightningnetwork/lnd#4197]
### Background

I have 4 channels that i closed Sunday - 4 days ago and they still show closing. How long should it take to receive the funds when closing a channel?

Windows 10
Version of lnd 0.9.2-beta

{
    "total_limbo_balance": "1448573",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266",
                "channel_point": "eb96d24ea2fd944de5fa4d9ba03d0454e228e5a033a8589acf53fcf8bc07f30d:1",
                "capacity": "70294",
                "local_balance": "69804",
                "remote_balance": "0",
                "local_chan_reserve_sat": "702",
                "remote_chan_reserve_sat": "702"
            },
            "limbo_balance": "69804"
        },
        {
            "channel": {
                "remote_node_pub": "03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf",
                "channel_point": "757476f8f817d3ed5156ae4716cea22e819a5b35baa2cf978c12ec693a158149:1",
                "capacity": "219596",
                "local_balance": "219106",
                "remote_balance": "0",
                "local_chan_reserve_sat": "2195",
                "remote_chan_reserve_sat": "2195"
            },
            "limbo_balance": "219106"
        },
        {
            "channel": {
                "remote_node_pub": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
                "channel_point": "331307cc2128d76ed913e36dea52370f535ba5f7262e978e4cd4b54640a6f211:1",
                "capacity": "880000",
                "local_balance": "879454",
                "remote_balance": "0",
                "local_chan_reserve_sat": "8800",
                "remote_chan_reserve_sat": "8800"
            },
            "limbo_balance": "879454"
        },
        {
            "channel": {
                "remote_node_pub": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
                "channel_point": "e683cb8995cbeb3d27d3066a37558d466fdd9f028489c88560787e7f2ffbd39a:1",
                "capacity": "280699",
                "local_balance": "280209",
                "remote_balance": "0",
                "local_chan_reserve_sat": "2806",
                "remote_chan_reserve_sat": "2806"
            },
            "limbo_balance": "280209"
        }

**Comment by padgamer** [comment]
it tells me no open channels to close when I try to close them. I tried to force lose them as well with no luck. any other options?

**Comment by guggero** [comment]
Did you try them one by one?
For example: `lncli closechannel --funding_txid eb96d24ea2fd944de5fa4d9ba03d0454e228e5a033a8589acf53fcf8bc07f30d --output_index 1 --force
`?
The `closeallchannels` might not work in that case.
Also, have you tried a restart of the node? How many other (open) channels do you have?

**Comment by padgamer** [comment]
Finally got them to close. Thank you for the help.
