### ISSUE TITLE
Missing backslash causing docker containers to fail to launch

### ISSUE THREAD

**Issue by Technifocal** [lightningnetwork/lnd#420]
https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/start-lnd.sh#L49

On the arguments for `lnd`, you have forgotten to add a backslash to the new argument implemented in 5ced45af01b0fe4d20f08a32b3cef91d18b35a89. This causes `lnd` to return back complaining about no coin (I.E. `--$CHAIN.active`) selected.

**Comment by mlerner** [comment]
This should be fixed by https://github.com/lightningnetwork/lnd/pull/427.
