### ISSUE TITLE
Unable to create a channel while another is pending

### ISSUE THREAD

**Issue by dudexk** [lightningnetwork/lnd#4200]
### Background

When trying to create multiple channels back-to-back, after the first channel opens, lnd seems to assume that the lnd wallet balance is zero. I have read that this is intentional, while the channel is pending. This is extremely inconvenient and seems to be unnecessary. I would like a solution that allows a work-around to this issue.

### Your environment

lnd version 0.8.0-beta commit=v0.8.0-beta-2-gb95a0a0f
Windows 10
backend=neutrino.0.6.2-beta
params=--debuglevel=debug --bitcoin.active --lnddir=C:\Users\Administrator\AppData\Roaming\Zap\lnd\bitcoin\mainnet\wallet-1 --rpclisten=localhost:11009 --listen=0 --routing.assumechanvalid "" --bitcoin.node=neutrino --neutrino.useragentname=zap-desktop --neutrino.useragentversion=0.6.2-beta --bitcoin.mainnet --neutrino.addpeer=mainnet3-btcd.zaphq.io --neutrino.addpeer=mainnet4-btcd.zaphq.io

### Steps to reproduce

Deposit X sat into your lnd wallet.
Let Y = X / 4
lncli openchannel --node_key node_key --connect node_ip:port Y
Channel starts successfully
lncli openchannel --node_key node_key --connect node_ip:port Y
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need Y BTC only have 0 BTC  available

### Expected behaviour

I would like to see the ability to create as many channels as the current confirmed wallet balance allows.

### Actual behaviour

After the first channel opens, you cannot create new channels until the first confirms.

**Comment by Crypt-iQ** [comment]
Does your wallet only have one UTXO under its control?

**Comment by dudexk** [comment]
> Does your wallet only have one UTXO under its control?

Yes it does. I deposit X and then try to create 2 channels of X / 4

So when a channel is pending, it will lock the UTXO associated with the spending txn? I don't understand why that's necessary. Why isn't it possible to open another channel with the same UTXO assuming that it's less than current confirmed balance?

**Comment by dudexk** [comment]
Ah I'm realizing now that the rest of the BTC in the UTXO would then be unconfirmed as a change txn right? That's the reason?

**Comment by wpaulino** [comment]
> Ah I'm realizing now that the rest of the BTC in the UTXO would then be unconfirmed as a change txn right? That's the reason?

Yes, if you'd like to spend the unconfirmed change, then you should use the flag `--min_confs=0`.

**Comment by Crypt-iQ** [comment]
> > Does your wallet only have one UTXO under its control?
> 
> Yes it does. I deposit X and then try to create 2 channels of X / 4
> 
> So when a channel is pending, it will lock the UTXO associated with the spending txn? I don't understand why that's necessary. Why isn't it possible to open another channel with the same UTXO assuming that it's less than current confirmed balance?

FWIW, it should be possible to eventually multiple channels in a single tx

**Comment by guggero** [comment]
With `v0.10.0-beta` it will be possible to open multiple channels by using a PSBT.
