### ISSUE TITLE
unable to decode payment request: amount 18446744073709541616 pBTC not expressible in msat

### ISSUE THREAD

**Issue by stefan-mihaila** [lightningnetwork/lnd#4210]
### Background

```
lncli listinvoices
[lncli] rpc error: code = Unknown desc = unable to decode payment request: amount 18446744073709541616 pBTC not expressible in msat
```

I recently upgraded to 0.10. I also recently played with https://sphinx.chat connected to this lnd. I am not sure when the error started to appear, as I usually use the node with Zap and it seems to work.

### Your environment

* version of `lnd`: 0.10.0-beta.rc2
* which operating system (`uname -a` on *Nix): 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v0.19.0.1
* any other relevant environment details

### Steps to reproduce

https://github.com/lightningnetwork/lnd/issues/4210#issuecomment-616981327

### Expected behaviour

command outputs invoice list

### Actual behaviour

```
lncli listinvoices
[lncli] rpc error: code = Unknown desc = unable to decode payment request: amount 18446744073709541616 pBTC not expressible in msat
```

**Comment by joostjager** [comment]
Reproduced

```
joost@joost-desktop $ lncli-alice addinvoice --amt -1
{
    "r_hash": "2c9ba6b687cc8d02d4dd4b3ac6daab66b882ea0180037b1ff33ada9007c9b424",
    "payment_request": "lnbcrt18446744073709541616p1p0fayc0pp59jd6dd58ejxs94xafvavdk4tv6ug96spsqphk8ln8tdfqp7fksjqdqqcqzpgsp54aupmwq5ady3stshwjjpg0zjct9g7nne7g6m0clf20magc9stkjs9qy9qsqcszc0q8cxe678h4zzzja86q8ukjnst5mnfr6xpuh8mwtcuuzjfkpnuea6ceadq6a0nd63qmwdxkjv8t3c9eh083tlk80a9n6z4enhssqpqn3ar",
    "add_index": "2"
}
[~/lightninglabs/loop] (master $=)
joost@joost-desktop $ lncli-alice decodepayreq lnbcrt18446744073709541616p1p0fayc0pp59jd6dd58ejxs94xafvavdk4tv6ug96spsqphk8ln8tdfqp7fksjqdqqcqzpgsp54aupmwq5ady3stshwjjpg0zjct9g7nne7g6m0clf20magc9stkjs9qy9qsqcszc0q8cxe678h4zzzja86q8ukjnst5mnfr6xpuh8mwtcuuzjfkpnuea6ceadq6a0nd63qmwdxkjv8t3c9eh083tlk80a9n6z4enhssqpqn3ar
[lncli] rpc error: code = Unknown desc = amount 18446744073709541616 pBTC not expressible in msat
```

Probably need to add constraints to `AddInvoice` for >=0 and <= 21 million

**Comment by stefan-mihaila** [comment]
Until `addinvoice` gets fixed, is there a way to fix `listinvoices` on my lnd instance? Other apps rely on it. Can I somehow manually remove the invalid invoice from the db?

**Comment by joostjager** [comment]
One workaround that doesn't fully cover everything is to cancel the invoice. Build `lnd` with the `invoicesrpc` tag and run `lncli cancelinvoice <hash>`. 

`listinvoices` will then work, but only if `--pending-only` is specified.

**Comment by Roasbeef** [comment]
Thanks for testing out the release candiate! We've fixed the core underflow issue here, but you'll need something else to be able to properly list your invoices again. A quick patch follows below, but we'll need to make another more generalized change so users can still read their invoices even if this happens again somehow: 
```diff
diff --git a/rpcserver.go b/rpcserver.go
index 29f40d7a7..5def61f87 100644
--- a/rpcserver.go
+++ b/rpcserver.go
@@ -4429,17 +4429,19 @@ func (r *rpcServer) ListInvoices(ctx context.Context,
 	// Before returning the response, we'll need to convert each invoice
 	// into it's proto representation.
 	resp := &lnrpc.ListInvoiceResponse{
-		Invoices:         make([]*lnrpc.Invoice, len(invoiceSlice.Invoices)),
+		Invoices:         make([]*lnrpc.Invoice, 0, len(invoiceSlice.Invoices)),
 		FirstIndexOffset: invoiceSlice.FirstIndexOffset,
 		LastIndexOffset:  invoiceSlice.LastIndexOffset,
 	}
-	for i, invoice := range invoiceSlice.Invoices {
-		resp.Invoices[i], err = invoicesrpc.CreateRPCInvoice(
+	for _, invoice := range invoiceSlice.Invoices {
+		rpcInvoice, err := invoicesrpc.CreateRPCInvoice(
 			&invoice, activeNetParams.Params,
 		)
 		if err != nil {
-			return nil, err
+			continue
 		}
+
+		resp.Invoices = append(resp.Invoices, rpcInvoice)
 	}
 
 	return resp, nil
```
