### ISSUE TITLE
COOPERATIVE_CLOSE is not honest

### ISSUE THREAD

**Issue by gnucccoin** [lightningnetwork/lnd#4217]
### Background

Today my channel is cooperative closed for remote host when the mempool is too big.

My satoshi are : 1468770 ( local_balance + commit_fee )
My channel is cooperative close from the remote host, and the transaction trx: https://www.blockchain.com/it/btc/tx/98374749ddc3505dfb0d1b534b74eb90acf06e19567bf21c50a9c48e5932e944

I receive: 1465294 sats .
I paid all the fee 3476 sats for a closure I didn't want.

Even node can close a channel, and if it does when the mempool is at its maximum, it's a problem for me that I opened the channel.

This means that I have to trust the remote node which does not close the node because otherwise I lose money.
So: Open a channel needs trust.

I know that for security reasons, those who open the channel always pay fees, but if I have to **sacrifice honesty for safety**, that's not good ( is my opinion ) .

It's called "COOPERATIVE_CLOSE" but it doesn't exist as a cooperative.

My fault is not been well informed about the protocol. 
I decide to close all channels when the mempool is low, because I'm afraid to open new channels now.

I hope you solve the problem for the next releases and I will be happy to return to LN.
Thanks for everything you do. I love Bitcoin.

**Comment by Roasbeef** [comment]
As is, it's the initiator that pays fees for the co-op close. The fee paid for the cooperative close can't be higher than the based fee on the commitment transaction for force closes. In the future we plan to make updates to our fee negotiation algorithm to make it more robust. It is possible to just _deny_ someone the ability to co-op close, but that isn't implemented, and seems to be undesirable.

**Comment by gnucccoin** [comment]
Dear Roasbeef.

My opinion, the problem is very serious. 
I created my node to help LN network to grow, but so I only lose money.

It also goes against Bitcoin's philosophy.

I have to have trust about the node which  I'm going to connect, because I open a channel paying 1 sat / byte (156 sats in total) and then I am forced to pay 3476 because the counterparty decides to close? It's no honest, you thing ? 

This problem is underestimated. Write in bold in the first lines of the documentation that **opening a channel requires trust** and that you risk losing money because you have no control over the closure of the channel.

Why not paid the node who decide to close the channel? Where is the problem?

Regards

**Comment by cfromknecht** [comment]
> Why not paid the node who decide to close the channel? Where is the problemT

The other party might not have any funds on their side and so they can't pay the fees. The issue is that doing this requires a protocol change, it's not something that can be fixed immediately in lnd.
