### ISSUE TITLE
lnrpc: expose all local and remote channel constraints

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#4218]
Channel parties each have their own constraints on the channel that are negotiated when the channel is opened. At the moment, `ListChannels` exposes only:

* Local csv delay
* Local channel reserve
* Remote channel reserve

What is missing:

* Remote csv delay
* Local and remote dust limit
* Local and remote max pending amount
* Local and remote min htlc
* Local and remote max accepted htlcs

The point of this issue is to extend the response so that it is complete.

Implementation suggestion: create a new proto message that describes all of the constraints for one party and add local and remote instances of this message to the `Channel` message. Deprecate the existing fields.

**Comment by alexbosworth** [comment]
Related issue: https://github.com/lightningnetwork/lnd/issues/4063

**Comment by yyforyongyu** [comment]
I'm working on it
