### ISSUE TITLE
Add lncli version capability to REST API

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#4222]
### Background
I am looking to be able to use the new ```lncli version``` command in the REST environment.

**Comment by Roasbeef** [comment]
I think this'll be done in #4141, once the PR is out of the draft stage, we'd appreciate your feedback to make sure things work properly.

**Comment by sako0938** [comment]
Awesome I will keep an eye on it. I found some resources about how the proxy works, so hopefully I will be able to help read through the PR code. https://grpc.io/blog/coreos/
