### ISSUE TITLE
No REST endpoint for checking the status of a single outgoing payment

### ISSUE THREAD

**Issue by arcbtc** [lightningnetwork/lnd#4229]
Why isn't there an equivalent of /v1/invoice for outgoing payments?
I have to retrieve a massive blob of payments and parse to find whether a transaction has cleared :(

**Comment by guggero** [comment]
With #4141 you'll be able to user `routerrpc`'s `TrackPayment` method. Better REST support is on its way!

**Comment by arcbtc** [comment]
Looking forward to it :)
