### ISSUE TITLE
Missing btcsuite/decred copyright in LICENSE file

### ISSUE THREAD

**Issue by marcopeereboom** [lightningnetwork/lnd#423]
Hey guys, I went through the code a bit and I noticed that Decred was dropped from the license file:
https://github.com/lightningnetwork/lnd/blob/master/LICENSE

Per: https://github.com/btcsuite/btcd/blob/master/LICENSE the following 2 lines are missing:
Copyright (c) 2013-2017 The btcsuite developers
Copyright (c) 2015-2016 The Decred developers

**Comment by aakselrod** [comment]
We need to add these to neutrino as well, since some of the code is taken from `btcd`.

**Comment by Roasbeef** [comment]
This isn't a fork for btcd nor decred?

**Comment by marcopeereboom** [comment]
Doesn't matter if it is a fork.  You have to retain the copyright either on a per-file basis or you shuffle the copyright owners into the main LICENSE file.

Just by having a quick look I found several files that are straight copies from btcd and that means you have to maintain the copyright.

**Comment by Roasbeef** [comment]
Sure, we'll add the copyright to each of the copied files. 

Here's a breakdown of the files we copied initially, let me know if I'm missing any: 
  * https://github.com/lightningnetwork/lnd/blob/master/lnwire/message.go 
  * https://github.com/lightningnetwork/lnd/blob/master/version.go 
  * https://github.com/lightningnetwork/lnd/blob/master/signal.go
  * https://github.com/lightningnetwork/lnd/blob/master/config.go

**Comment by marcopeereboom** [comment]
Looks about right.

**Comment by marcopeereboom** [comment]
Works for me.
