### ISSUE TITLE
Rendezvous of RPC that terminate in new SubscribeHtlcEvents

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#4233]
### Background
Hi, I've used this new https://api.lightning.community/?python#subscribehtlcevents call, (after fixing a bug in the documentation... ) 
This is the code that I used
```python
import codecs, grpc, os
import router_pb2 as lnd, router_pb2_grpc as routerrpc
import time
import pickle


macaroon = codecs.encode(open('/home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon', 'rb').read(), 'hex')
os.environ['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'
cert = open('/home/admin/.lnd/tls.cert', 'rb').read()
ssl_creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel('localhost:10009', ssl_creds)
stub = routerrpc.RouterStub(channel)
request = lnd.SubscribeHtlcEventsRequest()
print("Running")                                                                                                                                                                                               
responses = []                                                                                                                                                                                                 
response_id = 0                                                                                                                                                                                                
for response in stub.SubscribeHtlcEvents(request, metadata=[('macaroon', macaroon)]):                                                                                                                          
    print('res_id = ' + str(response_id))                                                                                                                                                                      
    print(response)

```

But after a while (at res_id 19) I got this error:
```
_Rendezvous: <_Rendezvous of RPC that terminated with:                                                                                                                                      
        status = StatusCode.UNKNOWN           
        details = "unknown failure detail type: <nil>"                                                                                                                                       
        debug_error_string = "{"created":"@1588220504.572403636","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_m
essage":"unknown failure detail type: <nil>","grpc_status":2}"
```

### Your environment

lnd version 0.10.0-beta commit=v0.10.0-beta
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux

Thanks

**Comment by carlaKC** [comment]
> after fixing a bug in the documentation

By bug in documentation, do you mean replacing `LND_DIR` with `/home/admin`?


As the docs mention at the top, this var is just a placeholder for the base dir that your OS uses. We can't hardcode a value in there that works for everybody unfortunately. 
```
LND_DIR will be used as a placeholder to denote the base directory of the lnd instance. 
By default, this is ~/.lnd on Linux and ~/Library/ApplicationSupport/Lnd on macOS.
```

Thanks for the bug report! Fix is up.

**Comment by MrManPew** [comment]
Hi @carlaKC 
this is the code on the documentation - https://api.lightning.community/?python#subscribehtlcevents, I'll add comments where I had to change it
```python
import rpc_pb2 as lnd, rpc_pb2_grpc as routerrpc #< -- here import rpc_pb2 instead of router_pb2 
# you also import rpc_pb2_grpc instead of router_pb2_grpc

macaroon = codecs.encode(open('LND_DIR/data/chain/bitcoin/simnet/admin.macaroon', 'rb').read(), 'hex')
os.environ['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'
cert = open('LND_DIR/tls.cert', 'rb').read()
ssl_creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel('localhost:10009', ssl_creds)
stub = routerrpc.RouterStub(channel)
request = lnd.routerrpc.SubscribeHtlcEventsRequest() 
# here ^^  you should do lnd.SubscribeHtlcEventsRequest and not lnd.routerrpc.SubscribeHtlcEventsRequest
```


By the way @carlaKC, we could have found the bug already in RC stage if you have replied to my question here 😢:
https://github.com/lightningnetwork/lnd/issues/3420#issuecomment-619424064
I had to go to the slack and ask @Roasbeef specifically on how to use it to find these instructions.
😢( now we need a new release...)

Thank you very much for the fast fix 🤗!

**Comment by carlaKC** [comment]
> this is the code on the documentation

Will have to check back in on this, I think the api.lightning.community docs have been updated recently as we cut release candidates so you might have just had a stale version but will confirm.

> Thank you very much for the fast fix 🤗! 

np, thanks again for testing!

**Comment by guggero** [comment]
@MrManPew the API doc for the subservers (everything that is not in the main `rpc.proto`) is brand new. You are correct, there need to be some changes for them to be correct. I'll update the docs soon. Thank you for testing!

**Comment by guggero** [comment]
The docs are updated now. And I'll add a PR that explains how to compile the subserver RPCs to Python soon.
