### ISSUE TITLE
tor: examine config params to tune max circuits

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4244]
Users that use stream isolation for Tor may run issues once the tor daemon starts to bump up against settings that govern the max amount of circuit used. Stream isolation attempts to create a new circuit for each outbound connection. A large lightning node may have 1k+ persistent connections, meaning we may be running into the default settings.

**Comment by ErikEk** [comment]
I might be wrong but I can't find any viable limitation from any of the available parameters for the tor daemon on linux. Would be nice to do a benchmark on the lightning network or some other network to see what happens...

**Comment by wpaulino** [comment]
@ErikEk from https://2019.www.torproject.org/docs/tor-manual.html.en:

> MaxClientCircuitsPending NUM
> Do not allow more than NUM circuits to be pending at a time for handling client streams. A circuit is pending if we have begun constructing it, but it has not yet been completely constructed. (Default: 32)

**Comment by ErikEk** [comment]
@wpaulino Thanks. I will look into it.

**Comment by ErikEk** [comment]
According to the people over at the tor project there is no config param governing the maximum number of circuits used by the tor daemon.
Something that could become a problem, when using 1k+ isolated streams e.g, is the limit of how many circuits that can be created in one burst without it getting ugly.
I was talking with arma (from tor project), and his recommendation was to add a small time interval between each circuit creation (1-2 sec) + look at the feedback from the tor daemon in extreme cases like this.

**Comment by Crypt-iQ** [comment]
If we knew exactly what the problems were , maybe I could help diagnose this.

**Comment by Crypt-iQ** [comment]
There doesn't seem to be anything governing the max amount of circuits that can be created with Tor.

**Comment by Roasbeef** [comment]
Thx for investigating! I think our existing staggered initial connection, and connection logic with backoff retry should be sufficient for this case.
