### ISSUE TITLE
NAT problems on node without public channels

### ISSUE THREAD

**Issue by PatrickLemke** [lightningnetwork/lnd#4266]
### Background

I have a private channel with a node that does not have public channels. Opening a channel with the other node worked without problems because I knew the IP address. Because the other node often changed its IP address we constantly loose connection. Enabling nat=1 in lnd.conf doesn't work either. 

I think the reason for this is that because the other node does not have public channels, the updated IP is never announced to the network and therefore never reaches my node. Therefore I lose connection as soon as the IP address of the other node changes.

### Your environment

* 0.10.0-beta
* Linux raspberrypi 4.19.75-v7l+ SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
* bitcoind 0.19.1

### Steps to reproduce

Open channel to node without public channels behind nat.
Wait.

### Expected behaviour

Connection is not lost after the other node changes its IP address

### Actual behaviour

Connection is lost after the other node changes its IP address

**Comment by wpaulino** [comment]
There's no way to communicate IP addresses within the protocol without being a public node. In this case, the private node should have persistent connections to you. If both nodes are private, then they'd need to learn of each other's new IP addresses through other means.

**Comment by PatrickLemke** [comment]
Does that mean the only viable solution would be to either use TOR or have stable IP addresses?

**Comment by wpaulino** [comment]
Yes, but only if both nodes are private. Otherwise the private should have a persistent connection to the public, which `lnd` already handles.

**Comment by PatrickLemke** [comment]
It seems that this is not the case for me. But maybe the reason for this is that the public node is behind tor while the private node does not have tor enabled.

**Comment by wpaulino** [comment]
Ah yeah, that's another constraint. The private node would need to be able to dial over Tor in that case.

Closing this as it doesn't seem like there's an issue.
