### ISSUE TITLE
SendPaymentV2 - timeout_seconds parameter doesnt really work

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#4269]
### Background

Not a single time I was able to make `SendPaymentV2` timeout after seconds I specified (typically try 5 seconds).

### Your environment

* version of `lnd` 0.10
* which operating system (`uname -a` on *Nix) ubuntu 18
* version of `btcd`, `bitcoind`, or other backend neutrino
* any other relevant environment details

using javascript wrapper

### Steps to reproduce

two ways to reproduce it, one with failure on the channel, other with hold invoices.

in case of regular invoice that just fails with timeout as described here https://github.com/lightningnetwork/lnd/issues/4267 number of seconds provided for timeout doesn't work, but call timeouts in about 1 minute.

in case of hold invoice it hangs indefinitely (if htlc was delivered to payee) until payee cancels or settles invoice.

example argument provided to sendPaymentv2:

```
{ payment_request:
      'lnbc10n1p0tv5tkpp5sf7mdrqpalnax4k0800gg3q9y5zjtrpjzpm4ckvhtw3k9m06p70sdqqcqzpgxqrrsssp52vg93r59g7c2annckehjs5n2pqtv974953kq5a79kt7d6feud3uq9qy9qsqfg25u62n24qrmlnm4dde9c8svv8ssxmmtwem6v42x4xwz9raesfyj4sdktgn3yss5yg8xlhrylscr3axuuay6g2ke4a7jxm5u08n6msphev28a',
     timeout_seconds: 6,
     fee_limit_sat: 1,
     no_inflight_updates: false }
```

### Expected behaviour

I expect the call to return always no later than after provided timeout.

### Actual behaviour

hangs for longer than should

**Comment by joostjager** [comment]
>I expect the call to return always no later than after provided timeout.

This is not how the `timeout_seconds` arguments works. What `timeout_seconds` defines is the time after which no new payment attempt is made anymore. In any case, the call blocks until the current attempt (or multiple attempts in case of MPP) either failed or settled.

If you want to hard timeout on the call level, you can just close the stream client side.

Note that in Lightning, it is fundamentally impossible to cancel a payment whenever you want. Once the HTLC is handed out, the payment can remain pending up to the HTLC expiry block height.

**Comment by Roasbeef** [comment]
Closing for now as it was a misinterpretation of the argument. A follow up here would be to modify the docs to make the behavior more explicit.
