### ISSUE TITLE
Add support for preset close address on inbound channels too

### ISSUE THREAD

**Issue by federicobond** [lightningnetwork/lnd#4279]
It's now possible to set a close address when opening or cooperatively closing a channel from the current node. It's not possible to define a close address for remotely initiated channels though.

The particular use case I have in mind is running LND nodes backed by a Bitcoin Core wallet, where all on-chain funds should come from and go to the Bitcoin node wallet.

**Comment by federicobond** [comment]
Sounds reasonable. Are there any issues or pull requests I should be following to learn more about what has been previously discussed about channel acceptance hooks?

**Comment by Roasbeef** [comment]
So these are already checked in as is, here's where the current implementation lives: https://github.com/lightningnetwork/lnd/blob/master/chanacceptor/interface.go. The only other on going work in this area is to return custom reject messages.

**Comment by Roasbeef** [comment]
Implemented as part of the current version of the channel acceptor.
