### ISSUE TITLE
Pending channel cannot rebroadcast transactions

### ISSUE THREAD

**Issue by Swissnode** [lightningnetwork/lnd#4284]
### Background

I have a waiting_close channel that remains in that state forever. The `lncli pendingchannels `command gives the following:

```
$ lncli pendingchannels
{
    "total_limbo_balance": "11868856",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "030196f24a59674ee494b97e2905968585f86a1fc5d238734ca44eed83d9b50fe6",
                "channel_point": "b72eff181ee1da568c12325706686992db5a49187d67274210902865d50bfe77:0",
                "capacity": "12000000",
                "local_balance": "11868856",
                "remote_balance": "123562",
                "local_chan_reserve_sat": "120000",
                "remote_chan_reserve_sat": "120000",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "11868856",
            "commitments": {
                "local_txid": "91e6d398eca0739138f454600b7aa47c0fc704fc85ef1426267004d85ceb736d",
                "remote_txid": "23e4490c24a23f5d9b84b98f6a95e74d21d5befcb72d8d90f1d1517b19746531",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "7581",
                "remote_commit_fee_sat": "7581",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}
```
These transactions are not in the mempool. Any attempt at having them rebroadcast fail (e.g. restarting lnd). They are also not present when i do `listchaintxns`.

### Your environment

* LND 0.10.0
* Linux RaspiBolt4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
* Bitcoin Core version v0.19.0.1

### Steps to reproduce

Impossible to know if it can be reproduced. The peer in question lost connectivity a lot so this is a suspected cause

### Expected behaviour

The channel should have closed

### Actual behaviour

Pending indefinitely

### Desired outcome

I would love to know what I can do to force these transactions to be rebroadcast. Failing that, is it safe for the peer i am connected to to do a close or force close on the channel? Thanks!

**Comment by carlaKC** [comment]
Have you tried to force close the channel yourself? Unfortunately you can't broadcast the remote peer's tx because we don't have the tx/witness to do so, so trying our own commit may do the tick.

If not, do you have logs available? If possible, grepping for the channel point/ close tx so we can see whether anything is out of the ordinary. 

The ` --protocol.anchors` option allows opts in to channels with anchor commitments, which allow you to manually bump the fees on close txns to speed it up. It's currently an experimental feature, and requires that your peer opt in as well, but will hopefully solve a lot of problems like this.

**Comment by Swissnode** [comment]
hmmm - to close the channel I need to provide the txid of the channel's funding transaction is that correct? If so, how do I get it? It isn't given in the pending channel command (see above)

**Comment by wpaulino** [comment]
The closing transaction is in the mempool now with a fee rate of 42 sat/vbyte. Fees are higher at the moment, so it's just a matter of waiting.

> Any attempt at having them rebroadcast fail (e.g. restarting lnd).

Do you see any errors in your logs regarding this?

**Comment by Swissnode** [comment]
so what happened was that the peer closed the channel, hence a tx appeared. Why my node got into this state is a mystery and almost certainly a bug, but hard to reproduce. Glad to *try* and help if there is something I can dig into... not sure how far back logfiles typically go... (?)

**Comment by carlaKC** [comment]
Looks like the remote close tx has [confirmed](https://blockstream.info/tx/23e4490c24a23f5d9b84b98f6a95e74d21d5befcb72d8d90f1d1517b19746531) on chain, is the channel still stuck in waiting close?

**Comment by Swissnode** [comment]
No everything is fine now because the remote peer closed the channel just a couple of days ago.. The issue is more "why did my node, when attempting to close a channel, go into status waiting_close and then never escape that state? I was lucky in that I knew the node owner and could request him to close it, however had that not been the case, I might have been stuck in that state forever...

**Comment by wpaulino** [comment]
We can't know why without you providing us more information available in your logs.

**Comment by Swissnode** [comment]
Yeah, i waited quite a while in this state so finding the logs will be painful / not possible as I don't know the exact time period anything might have happened. I will keep an eye on this issue in future, though, and provide timely logs if it happens again. Luckily I was able to recover without closing funds due to the cooperative nature of my peer :)
