### ISSUE TITLE
lnrpc/signrpc: SharedKeyRequest should also accept a base pubkey

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4290]
As is, the `signrpc. DeriveSharedKey` only accept a key locator to pass in, meaning the caller needs to obtain this ahead of time. For certain use cases, the caller may only actually have the raw pubkey itself. We should extend the method to accept either of them to make the lives of our callers a bit easier.

**Comment by yyforyongyu** [comment]
i'm working on it
