### ISSUE TITLE
Unable to complete chain rescan: MsgTx.BtcDecode

### ISSUE THREAD

**Issue by freehodl** [lightningnetwork/lnd#4296]
### Background
2020-05-18 20:12:46.639 [INF] LTND: Waiting for chain backend to finish sync, start_height=630894
2020-05-18 20:12:47.590 [DBG] LNWL: Chain backend synced to tip!
2020-05-18 20:12:47.622 [INF] LNWL: Started rescan from block 000000000000000000091dba4418995d092305179439b5b340b409791e43224d (height 626971) for 44 addresses
2020-05-18 20:12:47.672 [ERR] LNWL: Unable to complete chain rescan: MsgTx.BtcDecode: witness tx but flag byte is 00

When I initially got this error I updated from version: 0.8.0-beta commit=v0.8.0-beta-211-g4d7a151b4763f5893c91c4f6b49316391db17f73 to 0.10.0-beta but updating didn't fix it.

I then tried a rescan using dropwtxmgr and after several hours the rescan failed with the same error at the same height.

### Your environment

* 0.10.0-beta commit=v0.10.0-beta-137-g4d3bd6f178e541b1c99ea05b4e16607e129fc499
* Linux ATC 4.15.0-72-generic Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind

### Steps to reproduce

$ lnd

### Expected behaviour
lnd starts and syncs to chain and graph, connects to peers, channels open

### Actual behaviour

Lnd fails to rescan and sync with backend. No channels open. No peers available.

**Comment by Roasbeef** [comment]
What version of `bitcoind` are you using?

**Comment by Roasbeef** [comment]
From the error, it looks like we're expecting a witness transaction, but then there ends up being no witness data.

**Comment by freehodl** [comment]
v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65

**Comment by freehodl** [comment]
> What version of `bitcoind` are you using?
@Roasbeef  Thanks for the response! I was using v0.18.0.0 and just updated to v0.19.1 and now I get this:

[ERR] LNWL: Unable to complete chain rescan: -1: Block not found on disk

**Comment by cfromknecht** [comment]
not sure yet about the witness decoding, but

> [ERR] LNWL: Unable to complete chain rescan: -1: Block not found on disk

is your node pruned?

**Comment by freehodl** [comment]
> not sure yet about the witness decoding, but
> 
> > [ERR] LNWL: Unable to complete chain rescan: -1: Block not found on disk
> 
> is your node pruned?

No

**Comment by freehodl** [comment]
It looks to be a corrupted/missing block.  

$ bitcoin-cli getblock "00000000000000000002ea23db68d5a523bcf9cd293d9f1e6cfc60d372d58f09"
error code: -1
error message:
Block not found on disk

Doing a -reindex on my bitcoind instance now and closing this as it's not an LND issue.

Thanks! @Roasbeef @cfromknecht
