### ISSUE TITLE
Make invoice decoding (zpay32) compatible with Litecoin addresses.

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#430]
Currently, there's a bug in the `zpay32` package, making decoding BOLT-11 invoices for Litecoin (starting with `lnltc..`) fail. The reason is that decoding currently assumes the prefix is only 4 characters long, causing amount decoding include the last letter(s) of the prefix: https://github.com/lightningnetwork/lnd/blob/master/zpay32/invoice.go#L299

Steps to completion:

- [ ]  Add a test to `zpay32_test` that attempts to decode a Litecoin invoice, reproducing the failure. This should check both mainnet and testnet invoices.
- [ ] Make `Decode` not longer assume the prefix is exactly 4 characters, but examine the provided `Bech32HRPPrefix` (https://github.com/lightningnetwork/lnd/blob/master/zpay32/invoice.go#L285) to figure out the actual length, and extract the amount starting from the correct index.
- [ ] Write a test that also encodes a Litecoin invoice, making sure this works as expected.

**Comment by nalinbhardwaj** [comment]
Doesn't [cfromknecht/swapz](https://github.com/cfromknecht/lnd/tree/swapz/zpay32) already implement this? I think it just misses tests(which I can add once that's merged?)

**Comment by halseth** [comment]
That one kinda works around this bug by trimming the prefix down to 2 characters for litecoin. This issue aims to solve it in a more generic way. The creation of "ltcParams" will come at a later point :)

**Comment by nalinbhardwaj** [comment]
@halseth Ah, got it. I didn't look very closely, I'll take this up.

**Comment by nalinbhardwaj** [comment]
> The creation of "ltcParams" will come at a later point :)

But for tests etc. to work, it's easier to just make it right now. Or is there some other pending change before that can be done? I'll hold off my PR if so.

**Comment by halseth** [comment]
Hm, you might need to create a common interface that the `btcd/chaincfg.Params` and `ltcd/chaincfg.Params` implements if that does not exist already. What I mean is that you shouldn't "convert" ltc params to btc params, but assume they are provided correctly from the caller creating and decoding invoices.

This issue might be a bit harder than I anticipated... 😛

**Comment by nalinbhardwaj** [comment]
@halseth but currently we have [chainparams.go](https://github.com/lightningnetwork/lnd/blob/master/chainparams.go#L60) which just applies the lite coin chain parameters to the btcCfg parameters. Is it not desirable to use that? Or is that code being deprecated?

**Comment by halseth** [comment]
@nalinbhardwaj If you can make it work with the existing chainparams code, that is probably fine 👍

**Comment by nalinbhardwaj** [comment]
I’m a bit busy with other stuff, so i won’t be able to do this anymore. Anyone else should feel free to pick it up.
Sorry about unavailability.

**Comment by wilmerpaulino** [comment]
I’ll pick this up.

**Comment by Roasbeef** [comment]
Fixed by #767.
