### ISSUE TITLE
lncli wallet bumpfee with wrong output index

### ISSUE THREAD

**Issue by BjXXQWNQ** [lightningnetwork/lnd#4301]
### Background
When using lncli to bump the fee of an onchain transaction, the use of a wrong output index crashes lnd.

### Your environment

* lnd 0.10.0-beta
* Linux raspberrypi 4.19.97-v7l+ #1294 SMP armv7l GNU/Linux
* bitcoind 0.19.0

### Steps to reproduce

1. Open a channel to produce a new onchain funding transaction. The result was in my case a transaction with two outputs.
2. lncli wallet bumpfee [transactionhash]:2 

### Expected behaviour

Some error message.

### Actual behaviour

lnd deamon crashes.

**Comment by wpaulino** [comment]
Can you include the stack trace?

**Comment by BjXXQWNQ** [comment]
> Can you include the stack trace?
I found, the part in the logs.  
May 18 12:47:46 lnd[700]: panic: runtime error: index out of range [2] with length 2
May 18 12:47:46 lnd[700]: goroutine 3912344 [running]:

Do the hex coded values after this line include personal data? E.g. Hashes or TXids?
