### ISSUE TITLE
lnd: use critical logging level to trigger clean shutdown of `lnd`

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4306]
We've made some recent changes intended to promote reservation fo the `error` logging level for actual issues and not ephemeral states like a peer needing to reconnect. One logging level which isn't used at all in the codebase today is `critical`. Related to this, there're a number of [lingering](https://github.com/lightningnetwork/lnd/issues/1557) [issues](https://github.com/lightningnetwork/lnd/issues/3109) related incorrect or undefined behavior of `lnd` when the backend backend disconnects, or w're unable to connect or write to the backing database. At times, during states like this, the best thing to do is simply to *shtutdown* and rely on auto restart by a hypervisor or the like. 

# Steps to Completion 

- [ ] Identify relevant areas in the codebase where a hard shutdown is warranted. An example include being unable to execute a database write, or running out of disk space itself. 

- [ ] Create a light interface wrapper around the current logging interface, that enables a clean shutdown for the `Critifalf` logging level. 

- [ ] Hook up this new logging wrapper to the `signals` package, to send a shutdown message to the main handler, so we start to wrap things up then shutdown.

**Comment by carlaKC** [comment]
> Identify relevant areas in the codebase where a hard shutdown is warranted

The two most critical areas are probably db (something has gone very wrong) and chain connection (risk of losing funds). It's a short list to start, but I think that this will cover a lot of the known issues in this area (specifically thinking of bitcoind issues, we consume block epoch in multiple subsystems so we will pick up issues quickly).
- `channeldb/kvdb/interface`: [update](https://github.com/lightningnetwork/lnd/blob/master/channeldb/kvdb/interface.go#L14) or [view](https://github.com/lightningnetwork/lnd/blob/master/channeldb/kvdb/interface.go#L25) errors for bbolt db transactions
- `channeldb/kvdb/etcd`: [update](https://github.com/lightningnetwork/lnd/blob/master/channeldb/kvdb/etcd/db.go#L232) and [view](https://github.com/lightningnetwork/lnd/blob/master/channeldb/kvdb/etcd/db.go#L218) errors, if they are [`DatabaseError`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/kvdb/etcd/stm.go#L96) type
- `lnwallet/interface`: [`GetBestBlock`](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/interface.go#L317), if we can't get blocks, we're in trouble. We could also do some of the other calls in `BlockChainIO`, but they're also subject to input which could be invalid so we'd have to error match. 
- `chainntnfs/interface`: [`RegisterBlockEpochNtfn`](https://github.com/lightningnetwork/lnd/blob/master/chainntnfs/interface.go#L136), if we can't get new blocks, we can't see force closes etc. 

For Bitcoin backend errors, I'd have to do some further investigation into the kind of errors we're returning, if they aren't critical we don't want to needlessly shutdown (specifically neutrino). 

> running out of disk space itself

I imagine this is something we would want to perpetually monitor, so just spin up a goroutine which checks every [insert period here]. Question here would be how full is too full? Could just start simple and shutdown if we only have 10% (configurable) disk left and go from there?

**Comment by Roasbeef** [comment]
Implemented by #4479
