### ISSUE TITLE
build: create ARM build run on Github Actions 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4307]
As Github Actions is now available to us, and seems to allow us to have access to a new set of builds we can trigger for `itests`, we should use it to start to fill some of the gaps in our current CI system. Right now we build for Linux, Solaris, and Mac OS, but only run integration test for x86 Linux. A popular platform to run `lnd` on are 64 and 32-bit ARM machines, so we should make that our next target to _run_ the `itests` on. This should also save us time for our future release candidates, as in the past we've caught some ARM specific issues after the fact.

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/4408.
