### ISSUE TITLE
lncli openchannel --sat_per_byte 

### ISSUE THREAD

**Issue by BjXXQWNQ** [lightningnetwork/lnd#4308]
### Background

Openening a channel using --sat_per_byte leads to a approx. half the fee value in the transaction.
Setting it to 20 sat/byte creates a transaction with ~10.8 sat/byte or 5 sat/WU. The only way I get 20 is by using vbytes. Assuming 1 WU is 4 vbytes.
Am I missing something obvious?

### Your environment

* lnd 0.10.0-beta
* Linux raspberrypi 4.19.97-v7l+ #1294 SMP armv7l GNU/Linux
* bitcoind 0.19.0

### Steps to reproduce

lncli openchannel .... -sat_per_byte [sats]

**Comment by wpaulino** [comment]
The parameter should really be sat/vbytes as that and weight units are what we use internally.

**Comment by BjXXQWNQ** [comment]
I was not familliar with vbytes before opening the issue. Usually you fire up one of the pages used for fee estimation and decide what you want. Therefore I would suggest to change the configuration switch to really set sats/byte or at least sats/WU. I guess, up to now nobody expected it to be vbytes. 

Thanks for your good work and commitment.

**Comment by wpaulino** [comment]
`vbytes` is what we want here as we're dealing with segwit transactions, or we could just go straight to weight units. Given that, we have three options:

1. Rename the flag to `sat_per_vbyte` (breaking change).
2. Add a new flag with the correct name (`sat_per_vbyte`) and deprecate the existing one.
3. Move to weight units and deprecate the existing one.

**Comment by mattLLVW** [comment]
there's the same issue with `lncli sendcoins --sat_per_byte`

**Comment by yyforyongyu** [comment]
I'm working on this one, taking the second approach as it requires minimal effort from the user-end.

> Add a new flag with the correct name (sat_per_vbyte) and deprecate the existing one.
