### ISSUE TITLE
 lncli connect does not understand ipv6 with port

### ISSUE THREAD

**Issue by shtirlic** [lightningnetwork/lnd#431]
```
 lncli connect 024ad958ec9accc5c81facd2d0144759a1e113bae1d33094d260c16ff65ca8dac1:2a02:ed0:4367:7000:781f:faf4:4eaa:f1cd:9735
[lncli] target address expected in format: pubkey@host:port
```

**Comment by cfromknecht** [comment]
Hey @shtirlic! I believe this error is raised when the address provided is missing the `@` sign https://github.com/lightningnetwork/lnd/blob/master/cmd/lncli/commands.go#L259. The command pasted seems to also be missing it, is this an exact copy of the command you used?

**Comment by shtirlic** [comment]
Hi, yes it was missing the @, after I added it errors with this:
```
lncli connect 024ad958ec9accc5c81facd2d0944759a1e113bae1d33094d260c16ff65ca8dac1@2a02:ed0:42fd:c700:cc27:dc8f:ce9b:3082:9735
[lncli] rpc error: code = Unknown desc = lookup 2a02:ed0:42fd:c700:cc27:dc8f:ce9b:3082:9735: no such host
```

**Comment by MDrollette** [comment]
ipv6 addresses need to be wrapped in square brackets. Does this work for you?
```
lncli connect 024ad958ec9accc5c81facd2d0944759a1e113bae1d33094d260c16ff65ca8dac1@[2a02:ed0:42fd:c700:cc27:dc8f:ce9b:3082]:9735
```

**Comment by Roasbeef** [comment]
Correct that brackets are required. Closing.
