### ISSUE TITLE
Canceled invoices are not shown in SubscribeInvoice stream

### ISSUE THREAD

**Issue by lessless** [lightningnetwork/lnd#4311]
### Background
Canceled invoices are not shown in SubscribeInvoice stream. 

Additionally node closes  socket and  `[ERR] INVC: unknown invoice state: Canceled` error appears in longs.

### Your environment

* version of `lnd`: v0.10.0-beta
* which operating system (`uname -a` on *Nix): Debian GNU/Linux 10 (buster)
* version of `btcd`, `bitcoind`, or other backend:  `"version": 190100,  "subversion": "/Satoshi:0.19.1/"`
* any other relevant environment details

### Steps to reproduce

0. Optionally use [Lightning Polar](https://lightningpolar.com/) - create a `Simnet` network with at least one LND node
1. Install Elixir. On macOS: `brew install elixir`, for Linux check distribution-specific step at https://elixir-lang.org/install.html#unix-and-unix-like
2. Clone and navigate into project folder `git@github.com:lessless/unistream.git && cd unistream`
3. Fetch dependencies mix deps.get
4. Edit TLS and Macaroon file locations if necessary in [lib/unistream.ex](https://github.com/lessless/unistream/blob/master/lib/unistream.ex)
5. Start app in a REPL shell `iex -S mix`
6. Run `Unistream.crashing_subscription` and observe error tuple `{:error, %GRPC.RPCError{message: ":stream_error: :closed", status: 13}}` 

**Or**

here is a JS scripts that will reproduce half of the problem - without dropping connection https://gist.github.com/lessless/f31eff5c07ef45f5d45c18a44c95af9c 

Be sure to edit path to cert and macaroon files.

### Expected behaviour

Canceled invoices should appear in stream and  server shouldn't close the socket.

### Actual behaviour

You will not see Canceled invoice in output stream and there will be ` [ERR] INVC: unknown invoice state: Canceled` error in node logs.
Also node closes socket.

**Comment by Roasbeef** [comment]
Fixed by #4298.

**Comment by Roasbeef** [comment]
So as is, only new invoices and settled invoices show up over that stream. The `SubscribeSingleInvoice` call in the invoice sub-server will deliver cancelled invoices for a _specific_ invoice. 

That error message is interesting as this case appears to be handled here: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/utils.go#L83

**Comment by wpaulino** [comment]
Error message origin could also be from: https://github.com/lightningnetwork/lnd/blob/d32c7a481409e8cf353175083cd51cdc44298eae/invoices/invoiceregistry.go#L1229

**Comment by joostjager** [comment]
Reproduced and confirmed that this is the error origin. Scenario:
- add invoice 1
- add invoice 2
- cancel invoice 2
- subscribeinvoices with add_index = 1

We don't map the invoice states `accepted` and `canceled` to `open` (which should happen to remain consistent with the limitations of this call).

**Comment by lessless** [comment]
Connection was closed because client sent too many pings.
