### ISSUE TITLE
Node closes connection when there are no invoices to show in `SubscribeInvoices` stream

### ISSUE THREAD

**Issue by lessless** [lightningnetwork/lnd#4312]
### Background

Node closes connection when there are no invoices to show in `SubscribeInvoices` stream

### Your environment

- version of lnd: v0.10.0-beta
- which operating system (uname -a on *Nix): Debian GNU/Linux 10 (buster)
- version of btcd, bitcoind, or other backend: "version": 190100, "subversion": "/Satoshi:0.19.1/"
- any other relevant environment details

### Steps to reproduce

0. Install Elixir. On macOS: `brew install elixir`, for Linux check distribution-specific step at https://elixir-lang.org/install.html#unix-and-unix-like
1. Start [Lightning Polar](https://lightningpolar.com/) 
2. Create new network called `Simnet` with at least one LND node  
3. Start `Simnet` network 

--- or get hold on a blank-slate node out any created invoices --- 

4. Clone and navigate into project folder  `git@github.com:lessless/unistream.git && cd unistream`
5. Fetch dependencies `mix deps.get`
5. Edit TLS  and Macaroon file locations if necessary in [lib/unistream.ex](https://github.com/lessless/unistream/blob/master/lib/unistream.ex)
6. Start app in a REPL shell `iex -S mix`
7. Run `Unistream.subscribe_without_invoices` and observe error
9. Check node logs and there will be an `[ERR] INVC: unable to deliver backlog invoice notifications: there are no existing invoices` error

### Expected behaviour

Node will not close socket 
### Actual behaviour

Node closes socket

**Comment by wpaulino** [comment]
The error is logged (it shouldn't), but the connection shouldn't be closed as things proceed as normal.

https://github.com/lightningnetwork/lnd/blob/35d40efd5204d3ff47962028f2b3ead818aa5b03/invoices/invoiceregistry.go#L233

**Comment by lessless** [comment]
@wpaulino  I tried to dig on a client side but got stuck there as well. At this point my best shot would probably inspecting traffic with Wireshark but I need to get over TLS encryption for that.

Do you know how to get `tls.key` password?

**Comment by wpaulino** [comment]
> Do you know how to get tls.key password?

You can find it in lnd's data directory. If you haven't modified it, then it should be `~/.lnd/tls.key` on Linux or `~/Library/ApplicationSupport/Lnd` on macOS.

**Comment by lessless** [comment]
Connection was closed because client sent too many pings.

**Comment by wpaulino** [comment]
> Connection was closed because client sent too many pings.

That would point to an issue with the client library perhaps? We don't enforce any type of keep alive parameters on the server side. AFAIK, other gRPC client implementations (Python, JS) don't seem to have issues.
