### ISSUE TITLE
TrackPayments endpoint feature request

### ISSUE THREAD

**Issue by MrHash** [lightningnetwork/lnd#4313]
I have been using the `SubscribeInvoices` and `SubscribeSingleInvoice` endpoints. It would be useful to have a similar `TrackPayments` endpoint. Ideally these endpoints should behave in a similar way. I have seen some discussion about this on PRs so would to add my support to @joostjager ideas for how this should be implemented and standardised.

**Comment by guggero** [comment]
Added in #6335.
