### ISSUE TITLE
Not able to import  github.com/lightningnetwork/lnd/macaroons

### ISSUE THREAD

**Issue by begetan** [lightningnetwork/lnd#4323]
### Background

I am trying to create custom cli tool based on the code of the cmd/lncli/main.go  and this example:
https://bitcoin.stackexchange.com/questions/73869/rpc-call-to-lnd

It is not possible to build project due to dependency error of the package `github.com/lightningnetwork/lnd/macaroons`

### Your environment

* version of `lnd`  `0.10.0 latest`
* which operating system `Linux 4.15.0-99-generic #100-Ubuntu`
* version of `btcd`, `bitcoind`, or other backend  - `not specified`
* This system can build the whole lnd project without any issue

### Steps to reproduce
Create a go project with modules
Copy code from the  github.com/lightningnetwork/lnd/cmd/lncli/main.go
with `import "github.com/lightningnetwork/lnd/macaroons"`
go build 

### Expected behaviour
Normal compilation is expected

### Actual behaviour
```
go build
go: finding module for package github.com/lightningnetwork/lnd/macaroons
client.go:15:2: module github.com/lightningnetwork/lnd@latest found (v0.0.2), but does not contain package github.com/lightningnetwork/lnd/macaroons
```

### Extra questions
Should this package be available for import in general?
Is there any good manual how to make custom client for lnd?

**Comment by guggero** [comment]
You need to specify a specific version. For example `v0.10.0-beta`. The problem is that the `v0.0.2` tag of lnd didn't have the `-beta` suffix and therefore the semver library of go modules thinks that's the most recent/best to pick even though it's ancient.
