### ISSUE TITLE
Maximum payment limits are not consistent in QueryRoutes

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4325]
In theory a payment shard can now be larger than the "bootstrapping" limitation that prevented invoice creation larger than 0.04294967295 on the Bitcoin network

Practically, this limitation is still surfaced in some areas

In [rpcserver.go](https://github.com/lightningnetwork/lnd/blob/64b8aa8f114142b4b1d1e8e1e751c846d1a7f422/rpcserver.go#L76):

> maxBtcPaymentMSat = lnwire.MilliSatoshi(math.MaxUint32)

And enforced in [QueryRoutes](https://github.com/lightningnetwork/lnd/blob/1bd211a7228d2f13ecaf514f611738837c057d94/lnrpc/routerrpc/router_backend.go#L139):

> 	// Currently, within the bootstrap phase of the network, we limit the
>	// largest payment size allotted to (2^32) - 1 mSAT or 4.29 million
>	// satoshis.

This check is also enforced when [un-marshaling a route](https://github.com/lightningnetwork/lnd/blob/1bd211a7228d2f13ecaf514f611738837c057d94/lnrpc/routerrpc/router_backend.go#L492):

>		if routeHop.AmtToForward > r.MaxPaymentMSat {
>			return nil, fmt.Errorf("payment of %v is too large, "+
>				"max payment allowed is %v",
>				routeHop.AmtToForward,
>				r.MaxPaymentMSat.ToSatoshis())

To make a payment or check for a payment route using QueryRoutes for a larger payment, the limitation enforced there would need to be relaxed to a larger amount

**Comment by joostjager** [comment]
@Roasbeef rc3?
