### ISSUE TITLE
rpc+walletunlocker: only permit a single outstanding init/unlock operation 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4340]
As is today, we don't have any sort of synchronization between calls to the wallet init/unlock calls. As a result, it's possible that a call to init, followed by a concurrent call to unlock can deadlock the daemon. The end result is that `lnd` is in a deadlock state, stuck on the `flock` to open up bolt DB, while another goroutine is stuck (?) trying to close out the modified database. This issue was found when trying to create a container running on k8s that would be auto unlocked or initialized depending on the wallet state.

The fix here seems straight forward: use a semaphore-like construct to limit the number of outstanding concurrent calls in the wallet unlocker sub-server.

**Comment by wpaulino** [comment]
Related to https://github.com/lightningnetwork/lnd/issues/3631.
