### ISSUE TITLE
Proper LND restoration feature

### ISSUE THREAD

**Issue by ZsZolee** [lightningnetwork/lnd#4350]
### Background

I'm running an LND routing node. I know that the current restoration procedure with SCB file makes all channels force-close, but couldn't just be modified to be a "routing-node friendly" solution? I mean any kind of restoration procedure which is not destroying the already opened channels, just resuming the business? I think in the future the availability and the age score of a node will be really important. I as a future node user, don't want to spend money (on-chain transaction fees) on nodes which come and go. That's why it's really important to have a proper restoration function. 

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by peername** [comment]
Just use а reliable hardware with ECC memory and ZFS mirrorred array for storage.

You can also use database replication.

**Comment by ZsZolee** [comment]
That's not a pocket friendly solution. It will make huge costs, so in the future this will centralize the routing nodes and it's against the basic Bitcoin principles. I can't believe that it can't be resolved through software features. You guys are really smart people, it must be a solution for that.

**Comment by peername** [comment]
When it comes to money, there is no room for compromise. One node must store all states of each channel. This is a lot of information. It is not easy to back up in real time. Especially with routing nodes, where transactions are even more.

**Comment by ZsZolee** [comment]
Yeah, but what if, I have a special watchtower which has every detail from my node "on the fly"? I can "reconnect and reclaim" my old position from that watchtower. Or if for any reason I can't claim my position back, then I can still force-close all the channels and claim back my money. If I don't want to disclose these kind of details and rules to a foreign special watchtower, I could build one or more for myself. As a backup solution, which is hosted on a different hardware, different location. In this case I don't need to backup everything, just the seeds+SCB files to claim back my position from the special watchtowers.

**Comment by Roasbeef** [comment]
In addition to the ZFS set up mentioned above, we now recommend usage of `etcd` to replicate the backend storage of `lnd`.
