### ISSUE TITLE
Lncli closeallchannels does not update my wallet balance

### ISSUE THREAD

**Issue by Davincij15** [lightningnetwork/lnd#4354]
### Background
So I am doing testing on lightning and trying different things to see if they work.  I was testing the closing of channels and found that my balance did not update but I can see the transactions on-chain and mine are unspent.  

`./lncli closeallchannels --sat_per_byte 4`

and here is the list of my closed channels

    "channels": [
        {
            "channel_point": "0ad331c1708cbe85827cc11b7caa0c6cdf73f4c7a3eb0eb78343db884fb0c44c:1",
            "chan_id": "695713783583145985",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "0f43732ad15ad84bea92b2b2b6290140ad8ed3cbd057878c2d0bfdb36cf90458",
            "remote_pubkey": "02237cf638160525ba849c7092271f6e11c41c659389bb55b1cb677255e065dc90",
            "capacity": "220070",
            "close_height": 633060,
            "settled_balance": "91180",
            "time_locked_balance": "0",
            "close_type": "COOPERATIVE_CLOSE",
            "open_initiator": "INITIATOR_LOCAL",
            "close_initiator": "INITIATOR_LOCAL"
        },
        {
            "channel_point": "a23a05a05273674b7af40998ff73f0f0dc3a655c6fa2e3dc2b9d624a4bba4bd8:0",
            "chan_id": "695703887921676288",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "e18447232300e53a26d75a17c1c1d42e904d5ae5c01c6e0d8d1cfdc7c9b80b07",
            "remote_pubkey": "029a6c374e25af038d22a0bdfd8b064d66e7795205d2471c66012053aa1577959e",
            "capacity": "36871",
            "close_height": 633062,
            "settled_balance": "7646",
            "time_locked_balance": "0",
            "close_type": "COOPERATIVE_CLOSE",
            "open_initiator": "INITIATOR_LOCAL",
            "close_initiator": "INITIATOR_LOCAL"
        }
    ]

So I decided to restore my LND node from scratch (kept a backup) and see if it could find the transactions and as I was reading the log low and behold it did find the transactions BUT my balance did not change.

2020-06-04 23:24:51.735 [DBG] LNWL: Marking transaction 0f43732ad15ad84bea92b2b2b6290140ad8ed3cbd057878c2d0bfdb36cf90458 output 0 (0.0009118 BTC) spendable
2020-06-04 23:24:51.735 [DBG] LNWL: Marked address bc1qvlrqrg6k3c3rmjjc5x4f2gefnr5l7prnpr5250 used

2020-06-04 23:24:52.106 [DBG] LNWL: Marking transaction e18447232300e53a26d75a17c1c1d42e904d5ae5c01c6e0d8d1cfdc7c9b80b07 output 0 (0.00007646 BTC) spendable
2020-06-04 23:24:52.106 [DBG] LNWL: Marked address bc1qcwpqzkf0tsf9q4eultk5hljqnr5e6esjucay2z used

So clearly the money exists and I have the keys to them BUT!!  I have no access to the bitcoin the system says I have.

Also before I did this I turned off autopilot before doing the close all channels. 

I bet I am just not looking in the right spot for the money 
I check the bitcoin node as well but that has always been empty.

### Your environment

* version of `lnd`
Version: 0.10.99-beta
* which operating system (`uname -a` on *Nix)
Linux cs00 5.4.0-33-generic #37-Ubuntu
* version of `btcd`, `bitcoind`, or other backend
"version": 190001,
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
After closing the channel I expected Lncli to show me the pending balance that is not confirmed and the correct balance once confirmed.
./lncli walletbalance

Thanks
Davinci Jeremie
Davincij15

**Comment by wpaulino** [comment]
The funds from the closed channel `0ad331c1708cbe85827cc11b7caa0c6cdf73f4c7a3eb0eb78343db884fb0c44c:1` were used in https://blockstream.info/tx/b30683d2a11952d003b6b4c10f6c294c34e7f6160d26795383c3fea06c6bea83. The funds from the other channel still remain unspent so you should see those.

**Comment by Davincij15** [comment]
Hey, Thanks for the prompt reply!

I know that I should see the funds, but I do not see them. The log shows I got the funds, so does the blockchain, but no logs indicate the spending of the coins by me or some other product.  However, both transactions got spent away one hour after.  I was planning to send all of my balance back to me when this happened, and I am kind of shocked as I may have been compromised somehow.  

This was a fresh install of ubuntu server on a VM with updates and tools to compile in go, and I was running LndHub in the background.   My VM is running on my mac, but I remoted in from a windows box that has MobaXterm that I love because it easy to edit files and move them around.

I have 3 LND nodes in my home lab for testing.  
"DJ152TestNode2" - Node with the missing bitcoins with LndHub
"DJNode105" - Casa node for testing
"DavinciJ15Node1" - Node on ESXi home lab server testing with tor (no other products)

I repeated the same thing on DavinciJ15Node1 with the same installation version and files but with tor running.  I did not use autopilot instead I opened a channel from DJNode105 then sent some funds back and forth then did a close all.  So far so good on the DavinciJ15Node1 but casa node does not show the balance in my account (maybe a visual bug).  

I will keep an eye on it.

Finally, I will retest the circumstances but without LndHub and with LndHub running after issuing a closeall command.

Cheers

**Comment by Davincij15** [comment]
Hey, I found that I have the channel and the money!

 I don't know why I did not see it before but this time I downloaded a web-based software called lncli-web to see everything at a glance. 

But I was sure I did not see it before but my terminal logs say I didn't look at channels.

My bad.
