### ISSUE TITLE
Rescan or Extract Seed

### ISSUE THREAD

**Issue by Davincij15** [lightningnetwork/lnd#4360]
I was running LND on a server with no seed backup and it crashed months ago but I could only recover the wallet.db file disk platers.

Is there a way to have lnd rescan or extract the seed so I can recover and force a rescan?

**Comment by guggero** [comment]
`lnd` doesn't offer any tools for this. Also the `--noseedbackup` really really shouldn't be used for mainnet!

But you can extract the xprv with [chantools](https://github.com/guggero/chantools). Use the `walletinfo` subcommand. Then once you have the root key, you can use the `genimportscript` to generate all private keys and import them into `bitcoind` for example.

**Comment by Davincij15** [comment]
Wow!
Good work!
Thanks if that doesn't work nothing will!  
I will donate 10% of what I recover if it works.
