### ISSUE TITLE
The InitWallet grpc/protobuf C++ call does not works.

### ISSUE THREAD

**Issue by infografx** [lightningnetwork/lnd#4373]
### Background

I try to call grpc Initwallet in C++.

The WalletBalance call works correctly (on an initialilzed wallet)
The GenSeed call works correctly.

But the Initwallet does not.

Also libcurl calls to bitcoind works correctly.

### Your environment

* version of `lnd`: master branch
* which operating system: Windows 10.
* version of `bitcoind`: 0.20
* any other relevant environment details: Visual Studio C++ 2017.

### Steps to reproduce

stub->GenSeed(&context, genseedRequest, &genseedResponse);
Works correctly:

for (int i = 0; i<24; i++) {
   printf("cipher_seed_mnemonic: %s\n", genseedResponse.cipher_seed_mnemonic().Get(i).c_str()))
}
the output is:
cipher_seed_mnemonic: "about"
cipher_seed_mnemonic: "disagree"
cipher_seed_mnemonic: "genuine"
cipher_seed_mnemonic: "finger"
cipher_seed_mnemonic: "sense"
cipher_seed_mnemonic: "city"
cipher_seed_mnemonic: "entry"
cipher_seed_mnemonic: "crime"
cipher_seed_mnemonic: "enjoy"
cipher_seed_mnemonic: "father"
cipher_seed_mnemonic: "hammer"
cipher_seed_mnemonic: "shadow"
cipher_seed_mnemonic: "like"
cipher_seed_mnemonic: "slender"
cipher_seed_mnemonic: "liberty"
cipher_seed_mnemonic: "evidence"
cipher_seed_mnemonic: "stage"
cipher_seed_mnemonic: "popular"
cipher_seed_mnemonic: "speak"
cipher_seed_mnemonic: "settle"
cipher_seed_mnemonic: "funny"
cipher_seed_mnemonic: "save"
cipher_seed_mnemonic: "tornado"
cipher_seed_mnemonic: "whisper"

Then I try to do:

lnrpc::InitWalletRequest initwalletreq;
const char wpass[]{ "okokokokz1Q" };
std::size_t wsz = 11;
initwalletreq.set_wallet_password(wpass, wsz);

for (int i = 0; i<24; i++) {
   initwalletreq.add_cipher_seed_mnemonic(genseedResponse.cipher_seed_mnemonic().Get(i).c_str());
}

lnrpc::InitWalletResponse initwalletresp;
stub->InitWallet(&context, initwalletreq, &initwalletresp);

the output from:
initwalletreq.SerializeAsString().c_str()

is:
okokokokz1Qaboutdisagreegenuinefingersensecityentrycrimeenjoyfatherhammershadowlikeslenderlibertyevidencestagepopularspeaksettlefunnysavetornadowhisper

### Expected behaviour

The line:
 stub->InitWallet(&context, initwalletreq, &initwalletresp);
should not generate an error.

### Actual behaviour

In the file
...\grpc2017_bin\include\grpcpp\impl\codegen\client_unary_call.h
on line:
56: ::grpc::internal::Call call(channel->CreateCall(method, context, &cq));
the line stub->InitWallet(&context, initwalletreq, &initwalletresp);
generates an error:
Unhandled exception at 0x00007FFF4BA3DB8E (ucrtbase.dll) Fatal program exit requested.

**Comment by guggero** [comment]
This doesn't look like an error from `lnd`. It looks like your program crashed for some reason.
Maybe you can't use the same context twice? I'm not familiar with C++ at all... Try using a debugger to find out exactly where and why the program crashes.

**Comment by infografx** [comment]
Reusing a context was the problem. Thank you very much.
