### ISSUE TITLE
ourBalance while sending htlc is limited to htlc amount 

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#4374]
### Background

Got next situation when remote balance was lower then htlcCommitFee, this caused payment error:

// If they cannot pay the fee if we add another non-dust HTLC, we'll
  // report our available balance just below the non-dust amount, to
  // avoid attempting HTLCs larger than this size.
  if theirBalance < htlcCommitFee && ourBalance >= nonDustHtlcAmt {
    ourBalance = nonDustHtlcAmt - 1
  }

Have a question: why do we need to cut ourBalance to nonDustHtlcAmt in this case? Why cannot make it like: ourBalance -= htlcCommitFee

### Your environment

* version of `lnd` - 0.10.0 rc5
* which operating system (`uname -a` on *Nix) - linux

### Steps to reproduce

Happened only once, can't reproduce.

**Comment by Roasbeef** [comment]
We do this to report back a balance that nudges the caller in the correct direction.
