### ISSUE TITLE
Payment stuck in inflight mode

### ISSUE THREAD

**Issue by tdickman** [lightningnetwork/lnd#4381]
### Background

I have a payment that is stuck in the `IN_FLIGHT` state despite having initiated in > 12 days ago. I originally created this as [a bug in the loop repo](https://github.com/lightninglabs/loop/issues/233), but was redirected here since this is specifically an issue with lnd.

Full logs can be found [here](https://github.com/lightninglabs/loop/issues/233#issuecomment-644751759).

### Your environment

* version of `lnd`: Payment initiated under `0.9.1`, have since upgraded to `0.10.1` (12 days after payment initiated)
* which operating system (`uname -a` on *Nix):  `Linux nodes-lnd-cc59667-bwgb7 4.14.138+ #1 SMP Tue Sep 3 02:58:08 PDT 2019 x86_64 Linux`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind 0.17.1`
* any other relevant environment details

### Steps to reproduce

Initiate a loop operation, and have the payment fail. Somewhat unclear how to 100% reproduce.

### Expected behaviour

Payment should transition to failed state.

### Actual behaviour

Payment gets stuck in `INITIATED` state.

**Comment by joostjager** [comment]
Can you provide (relevant parts) of the lnd logs too?

**Comment by joostjager** [comment]
Closing issue, but can be re-opened when more information (lnd log) is available.

**Comment by tdickman** [comment]
@joostjager Reopening this as it continues to be an issue. Most recently, we have a 0.5 btc loop out attempt that is stuck in the initiated state. Loop out operation was initiated on `2020-11-17T20:11:06Z`. The payment is listed as `IN_FLIGHT` with one htlc with an `IN_FLIGHT` status. When I check channel (`lncli listchannels`) from the `IN_FLIGHT` payment, it lists no pending_htlcs.

Please let me know what log content would be useful / what to search for. We have a number of other payments in similar states, but this is the most recent, so we would still have logs for it.

**Comment by apolosan** [comment]
[lnd.conf.txt](https://github.com/lightningnetwork/lnd/files/9575237/lnd.conf.txt)
I am facing the same issue. I am stuck with 28 IN_FLIGHT and don't have any clue of how this was going to happen.
[lnd.log.zip](https://github.com/lightningnetwork/lnd/files/9575233/lnd.log.zip)

**Comment by bitromortac** [comment]
Could you describe what payments you made? Did your node restart during that time?

**Comment by apolosan** [comment]
[payments.txt](https://github.com/lightningnetwork/lnd/files/9575415/payments.txt)

**Comment by bitromortac** [comment]
Thank you for providing the logs :). There are some payments that timed out in the past. Could you also share `lncli listchannels`, would be great to see if there are active HTLCs. Did you do anything special?

**Comment by apolosan** [comment]
I have changed some lnd.conf parameters, updated lnd, recently closed a channel with 02d06be7fd0073e8edd3575f42f85cea552d7b38ff68dd1cddce56a25b74b06cbe node and opened a new one.

**Comment by bitromortac** [comment]
Ok, there are no pending HTLCs reported by `listchannels`. I saw you set many config parameters, will need to look at them more closely.

**Comment by apolosan** [comment]
Thank you! I appreciate!
