### ISSUE TITLE
Funds not showing in wallet after channel close

### ISSUE THREAD

**Issue by rgoodse** [lightningnetwork/lnd#4387]
### Background

After closing a channel, funds will not appear in the wallet balance, even after the closing transaction has many confirmations.

This happens on an inconsistent basis and is not predictable 

Example:

Channel open txid:
https://blockstream.info/tx/e90725d0a36f1ac54c19860a0503e84228ecb0097e9439395f3c66c49746f12b

Channel closing txid: https://blockstream.info/tx/10d2de0b3ac2627fe4372193cbc4ad4e8e20629766d2598f7a72da8b9647420d

>>Shows bc1qfnnxpm7qyv5y2weczsx4p6yufw6rsany4kad97 receiving ~0.04 BTC and bc1qt7wh5h32ghfnhxjlvgu4n8553qrkenpznhe9hr receiving ~0.0005 BTC. The wallet ONLY shows the 0.0005 BTC being received.

From "listchaintxns"
`"tx_hash": "10d2de0b3ac2627fe4372193cbc4ad4e8e20629766d2598f7a72da8b9647420d",
            "amount": "55345",
            "num_confirmations": 13,
            "block_hash": "0000000000000000000915714a2bbce990454eed94772610993c24fce05c10a9",
            "block_height": 635237,
            "time_stamp": "1592452373",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qt7wh5h32ghfnhxjlvgu4n8553qrkenpznhe9hr",
                "bc1qfnnxpm7qyv5y2weczsx4p6yufw6rsany4kad97"
            ],`

It should re-deposit the 0.04 BTC back to the wallet, but the wallet only shows the deposit of 0.0005 BTC.

It shows bc1qfnnxpm7qyv5y2weczsx4p6yufw6rsany4kad97 (the address that received the 0.04 BTC) as a destination address - so why doesn't it show in the wallet? At the time of writing this, it has 13 confirmations.

### Your environment

 lnd version 0.8.0-beta commit=v0.8.0-beta-2-gb95a0a0f
Windows 10 x64
neutrino backend

### Steps to reproduce

I cannot reliably reproduce the issue. It seems to occur randomly. The underlying reasons are not clear to me

### Expected behaviour

I should see the full amount in the channel (0.04 + 0.0005) being deposited back into the wallet.

### Actual behaviour

I only see 0.0005 BTC being deposited back into the wallet

**The 0.04 BTC input was involved in a loop out, which failed. Could that have something to do with it?**

**Comment by Roasbeef** [comment]
You've confirmed that your the _initiator_ of that channel? Also as you're running lnd 0.8 which is two releases behind, I _strongly_ recommend that you update to the latest version of `lnd`. 

If you only see the deposit of 0.0005 BTC, then that means that was your remaining balance in the channel.
