### ISSUE TITLE
Fail to openchannel on testnet

### ISSUE THREAD

**Issue by ZhXZhao** [lightningnetwork/lnd#4388]
### Background

After I connect to a peer node, I try to open a channel with the node.
But I failed.

### Error info

[lncli] rpc error: code = Unknown desc = received funding error from 02913d84886059292845f870c5229f103dd8d7d71d7e9fc6fd52f75a40486d2187: chan_id=f9ecc46d337b9f394a1211afe01e75482e97be68b5e7035a5583d7cc04cf60c3, err=Unknown chain=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943. Supported chain=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

### Your environment

* version of `lnd` Version: 0.10.99-beta
* which operating system (`uname -a` on *Nix) ubuntu18.04
* version of `btcd`, `bitcoind`, or other backend bitcoin core v0.20.99

### Expected behaviour

Successfully open a channel

### Actual behaviour

Fail to open a channel

**Comment by guggero** [comment]
From the error message it looks like you are trying to open a channel to a mainnet node. You can find testnet nodes here: https://1ml.com/testnet/

Feel free to join our Slack for help setting up a node: https://join.slack.com/t/lightningcommunity/shared_invite/enQtOTE3Mjc0MDQ0MTY3LWQ1NGNjNzg2YjFiNWU0NWIzZjBjYzQ0OGQ2Mzg1YmE2NjU4ODBhM2I2YTU5MTAzYzVmYzVlMTQzNGNjNGJkNGU
