### ISSUE TITLE
Can't route payment. Multiple TEMPORARY CHANNEL FAILURE @ 1.

### ISSUE THREAD

**Issue by downystreet** [lightningnetwork/lnd#4392]
OS: CentOS 8
lnd version:  version 0.10.99-beta

I'm having trouble paying invoices with amounts of $10 or $20. I was able to successfully complete the transactions when I had an open channel to a certain node that had a route to my destination with a local balance greater than the satoshi amount needed to complete the transaction. However, after several transactions and the local balance was moved to the remote balance, the node that was routing my payment was no longer usable and the lightning network was choosing a different route. I had multiple channels going out with a local balance  high enough to cover the transactions but now the transactions fail every time from what appears to be the transaction not being able to find a route over the network. All of the attempts start with the Alpha node and I see the route to the node I'm trying to reach but all of the routes from Alpha node that it is trying to complete say TEMPORARY CHANNEL FAILURE @ 1 and the transaction fails from timeout. Multiple attempts produces the same result. I tried to use the C-Otto/rebalance-lnd script to rebalance my own channels but every attempt was met with "Could not find any suitable route", unless I was using a very low amount of satoshis, around 5000, which is not very good when I need to rebalance around 200000 or more satoshi. When using this low amount of satoshi (5000) to try and rebalance the channel it would say trying route 1, TEMPORARY CHANNEL FAILURE and then move on to trying route 2 where it would then just sit there and not complete the rebalance.

Update: I was using the wrong variable when using the load balancer, so I was able to get it working, however even the load balancer is saying "not able to find a suitable route", using anything more than 30000 sats and is having multiple temporary channel failures when finding a route. Using the default of the load balancer to get the channels at a 50/50 ratio is unusable due to it not being able to find a suitable route. Because I'm having to send small amounts of satoshi, anywhere from 5000-20000, multiple times, it gets harder and harder for it to find a route and the load balancer just goes on and on saying temporary channel failure until, same as the regular lightning network, times out from failure to find a suitable route. It eventually gets to the point where I cant send anything to rebalance just like the lightning network. It would seem that sending multiple payments in succession is balancing the channel routes in a way that is antithetical to sending payments at all. In other words, after so many payments are sent through the channels and the remote and local balances have been shifted one way or another to favor either the remote or local balance you are not able to send payments at all unless somehow the channels get rebalanced.

**Comment by Roasbeef** [comment]
If you're seeing @1, then that means the very first hop beyond you doesn't have sufficient balance for the route, so it's an issue of peer selection if that node isn't maintaining their channel balances effectively. We can probably help you debug things a bit more on slack given the number of channels you have, the peers, etc. 

If you need to replenish your ability to send (top off your channel), then you can use [Lightning Loop](https://lightning.engineering/loop/) (specifically Loop In) to "top off" your channel.

**Comment by downystreet** [comment]
So the 1ml.com node alpha  isn't maintaining its channel balances effectively? Because that is the node that it is using for the 1st hop. You might want to make them aware of this. The lightning loop doesn't make sense to me. I have money in my lnd wallet right now and you are saying that in order to increase my local balance I need to put more funds into it?
