### ISSUE TITLE
discovery: replyChannelRange overflow causes zero result reply

### ISSUE THREAD

**Issue by bmancini55** [lightningnetwork/lnd#4393]
### Background

When processing query_channel_range, the incoming query includes a first_blocknum and num_block, both are uint32 values. According to BOLT7 there is no limitation on num_blocks in relation to the first_blocknum. This creates a situation where first_blocknum + num_blocks can overflow uint32 if not correctly handled by the receiving node.

In `syncer.replyChanRangeQuery`, when the end block is calculated, it does not account for the overflow. Go's implementation of integer overflows treats the addition as a modular addition resulting in an end block that is below the start block.
 
The final result is that zero records are returned.

### Your environment

* lnd version 0.10.99-beta commit=clock/v1.0.0-49-g9b8d51231c9cc5505380e911a45378f78d306190
* macOS: 10.15.5 

### Steps to reproduce

This was found testing a project that was sending custom gossip messages to various nodes.  The short of it is to construct a message with first_blocknum > 0 and num_blocks = uint32_max.

### Expected behaviour

It should returns results matching the range supplied, treating an overflow as wanting the maximum number of blocks. 

Below is a query that is constructed so that it does not trigger an overflow on an LND Node:  first_block + num_blocks = uint32_max.  The reply includes SCID results.

Query:
```
010743497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000001b0210ffe4fdef

0107 - type 263 (query_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum (1770000)
ffe4fdef - num_blocks (4293197295)
```

Reply:
```
0108 - type 264 (reply_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum (1770000)
ffe4fdef - num_blocks (4293197295)
01 - full_information (true)
00a9 - len (169)
00 - encoding type (uncompressed)
1b02480000140000 - scid
1b024c0000160001 - scid
1b024f00000d0000 - scid
1b024f00000d0001 - scid
1b02ae0000100000 - scid
1b02ae0000110000 - scid
1b02cb0000150000 - scid
1b02df0000090000 - scid
1b03340000120001 - scid
1b03ce0000050001 - scid
1b03ce0000060000 - scid
1b03ce0000070001 - scid
1b03ce0000080000 - scid
1b03cf00000e0000 - scid
1b03d000000d0000 - scid
1b03d000000e0001 - scid
1b04000000230000 - scid
1b04000000240001 - scid
1b04010000050001 - scid
1b04010000060000 - scid
1b04730000020000 - scid
```

### Actual behaviour

No results are returned when a message is constructed that triggers an overflow.  For example:  first_blocknum > 0, num_blocks= uint32_max. 

Query:
```
0107 - type 263 (query_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum( 1770000)
ffffffff - num_blocks(4294967295)
```

Reply
```
0108 - type 264 (reply_channel_range) 
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
001b0210 - first_blocknum (1770000)
ffffffff - num_blocks (4294967295)
01 - full_information (true)
0001 - len (1)
00 - encoding type (uncompressed)
```

**Comment by bmancini55** [comment]
I'm happy to submit a PR to address this issue.  

I have working code that prevents the overflow by calculating `maxNumBlocks` as  `math.MaxUint32 - startBlock` and if `numBlocks` is greater than this value it defaults the end block to the max value.

For testing, I plan to capture multiple query calls with 0 to max, non-overflow range, and overflowing range and ensure the correctly calculated `startBlock` and `endBlock` are passed for each query.

**Comment by wpaulino** [comment]
We actually already have a method that handles the overflow, it's just not being used in this case.

https://github.com/lightningnetwork/lnd/blob/87880c0d56937f2380acee37910492b2fc7b910f/lnwire/query_channel_range.go#L80

**Comment by bmancini55** [comment]
Ah good stuff, I will use that instead.
