### ISSUE TITLE
Multiple payments result in TEMPORARY CHANNEL FAILURE with no route.

### ISSUE THREAD

**Issue by downystreet** [lightningnetwork/lnd#4394]
After multiple payments are completed and the local balance gets shifted to the remote balance through a particular node, a route is unable to be found through the other connected nodes with local balance that meets requirements. TEMPORARY CHANNEL FAILURE @ 1 means that the first hop in the chain in my case 1ML.com node ALPHA does not have properly balanced channels and cannot route a payment of $10 or $20 to another node on the network. Using C-Otto/rebalance-lnd can help rebalance but it also has problems finding a suitable route with more than 30000 sat.

**Comment by Roasbeef** [comment]
See my comment on your other issue. As you start to send more payments your balance is depleted to the point that you may no longer be able to send payments. Rebalancing can't always help with this depending on your channel distribution. Another solution to this is using something like Loop In to "top off your channel". This actually inserts _new_ coins into your channel to allow you to send more coins.

**Comment by downystreet** [comment]
I put all my money into my node I have 11 or so channels most with around $10 capacity, 1 with $23 capacity and 2 with $50 capacity. I also have 1 inbound at >$100. The rebalancer allows me to use the node again but as I was saying there is a flaw in it. I am not able to just do a 50/50 rebalance, I have to send 1000 sats at a time to reblance because it has trouble finding a route after so many attempts and you have to keep lowering the amount of sats you are using. As far as using Loop to top up my balance, that just seems redundant when I already have all these channels open and around $20 in my lnd wallet right now. I don't have any more bitcoin to send through loop because I put it all into this lnd node.

**Comment by downystreet** [comment]
Do you want the logs?
