### ISSUE TITLE
closeallchannels results in 77% loss of initial funds.

### ISSUE THREAD

**Issue by downystreet** [lightningnetwork/lnd#4399]
Using ./lncli closeallchannels proceeded to close all channels. I had used 3137200 sat of my own money which comes out to around $290 to open about 18 or so channels about 2 days ago. After the channels were no longer able to route my payments I closed them out. This resulted in a 77% loss of my original funds. Walletbalance now shows only 701,733 after the closeallchannels command.

**Comment by Roasbeef** [comment]
Chatted with the user on IRC and explained that they didn't lose money, instead they had sent out that amount to a destination on the network. Any additional amount missing was paid out to fees.
