### ISSUE TITLE
Q: What is the maximum invoice length?

### ISSUE THREAD

**Issue by chokoboko** [lightningnetwork/lnd#4415]
I'm not sure it's a real issue, but I noticed that `maxInvoiceLength` in [zpay32/invoice.go](https://github.com/lightningnetwork/lnd/blob/c1ef5bb908606343d2636c8cd345169e064bdc91/zpay32/invoice.go#L81-L84)
is set to `7089` bytes, so an invoice "can fit into a single QR code". Since invoices are bech32 encoded (alphanumeric) and according to [ISO/IEC 18004:2015](https://www.sis.se/api/document/preview/918566/) the maximum storage capacity of QR code (version 40-L) for alphanumeric datatype is `4296` bytes.

**Comment by Crypt-iQ** [comment]
You are right, I took the 7089 from wikipedia. A pull request would be greatly appreciated :)

**Comment by halseth** [comment]
Actually, since it not a strict requirement that an invoice needs to fit in a QR code, I think we can be conservative and close this issue and PR.
