### ISSUE TITLE
Incorrect error check in channeldb tests

### ISSUE THREAD

**Issue by davecgh** [lightningnetwork/lnd#442]
As can be seen by looking at the following, the error being checked is not the error returned from `AddNextEntry`, rather the one returned from `AtIndex`.

https://github.com/lightningnetwork/lnd/blob/b98e993d764f545f0dac9b4e9df9bc7ad0ae734e/channeldb/channel_test.go#L124

**Comment by Roasbeef** [comment]
Nice catch! That's a nasty little scoping quirk.

**Comment by Roasbeef** [comment]
Closed by #446.
