### ISSUE TITLE
Unable to create chain control: unable to subscribe for zmq block events: dial tcp 127.0.01:18500: connectex:

### ISSUE THREAD

**Issue by milahajek** [lightningnetwork/lnd#4422]
### Background

I am ultranoob trying to set up lightning node. Already running bitcoin core full node. 

### Your environment

* version of `lnd` lnd-windows-amd64-v0.10.1-beta
* which operating system (windows)
* bitcoin core 2.0
* any other relevant environment details

![ln](https://user-images.githubusercontent.com/33515343/85904763-db332500-b809-11ea-8dfe-ff3dad59d0e3.jpg)

**Comment by Roasbeef** [comment]
Make sure you compiled `bitcoind` with `zmq` included. Also you need to set the argument to specify the `zmq` ports when you start up bitcoind.

**Comment by milahajek** [comment]
As I said - ultranoob, but I am trying to get maximum from the bitcoin ecosystem. I have no coding or technical background. If you think it is possible to write me an easy to follow step by step list of how to solve this issue and attach your lightning invoice for some sats, I will be grateful. If it is too complex, I will just find somebody who helps me in person with this. I am surprised I even got to this point. :)

**Comment by Roasbeef** [comment]
I'd check out the [install docs for running w/ a bitcoind node](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#using-bitcoind-or-litecoind), and [also our operational safety guidelines doc](https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md).
