### ISSUE TITLE
Allow separate configuration of bitcoind cookie usage

### ISSUE THREAD

**Issue by Jorijn** [lightningnetwork/lnd#4439]
Feature request:

### Background

I'd like to have an option under [bitcoind] where I am able to make LND use a `.cookie` file at a given location to authenticate to bitcoind. 

### Your environment

The backend I'm using is bitcoind. LND and components are run in a containerized environment. This allows me to control aspects of networking and authentication on a different scale than regular systems. LND is making me choose between cookie authentication on localhost, or RPC user/pass authentication on a remote host. I would like to have both at the same time.

I would like for LND to consume and use at least these values:
- hostname of bitcoind rpc server (container);
- port of bitcoind rpc server (container);
- path of bitcoind .cookie; (where it's mounted)

**Comment by wpaulino** [comment]
Relevant PR: https://github.com/lightningnetwork/lnd/pull/2280.
