### ISSUE TITLE
crypto.go:171:46: too few values in &btcec.PublicKey literal

### ISSUE THREAD

**Issue by martinbehrens** [lightningnetwork/lnd#4441]
### Background

Current master branch code base doesn't compile properly.

### Your environment

* version of `lnd`

Current master branch.

* which operating system (`uname -a` on *Nix)

 go version go1.13.4 linux/amd64
 CentOS Linux release 8.2.2004 (Core)
 Linux 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend

Not relevant.

* any other relevant environment details

### Steps to reproduce

1. Follow https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#preliminaries
2. Execute make

### Expected behaviour

Lnd should compile.

### Actual behaviour

Lnd doesn't compile properly: 

```
go: finding github.com/rogpeppe/fastuuid v1.2.0
go: finding github.com/NebulousLabs/fastrand v0.0.0-20181203155948-6fb6489aac4e
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding github.com/tv42/zbase32 v0.0.0-20160707012821-501572607d02
\033[0;32m Building debug lnd and lncli.\033[0m
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=clock/v1.0.0-130-gf9c6a1b73f21824a3b7acce9aa29d9907e38fb5d -X github.com/lightningnetwork/lnd/build.CommitHash=f9c6a1b73f21824a3b7acce9aa29d9907e38fb5d -X github.com/lightningnetwork/lnd/build.GoVersion=go1.13.4 -X github.com/lightningnetwork/lnd/build.RawTags=dev" github.com/lightningnetwork/lnd/cmd/lnd
github.com/lightningnetwork/lightning-onion
# github.com/lightningnetwork/lightning-onion
../../../../pkg/mod/github.com/lightningnetwork/lightning-onion@v1.0.2-0.20200501022730-3c8c8d0b89ea/crypto.go:171:46: too few values in &btcec.PublicKey literal
../../../../pkg/mod/github.com/lightningnetwork/lightning-onion@v1.0.2-0.20200501022730-3c8c8d0b89ea/crypto.go:178:46: too few values in &btcec.PublicKey literal
make: *** [Makefile:116: build] Error 2
```

**Comment by Roasbeef** [comment]
Unable to reproduce. Also our automated builds are passing now as well, so this points to an issue with your local environment.

**Comment by martinbehrens** [comment]
> Unable to reproduce. Also our automated builds are passing now as well, so this points to an issue with your local environment.

Confirmed with manually d/l'ing and installing the go tarball. Interestingly the default Centos 8 go v1.13.4 package (installable with 'yum module -y install go-toolset') doesn't work, although the version does meet lnd's minimum requirement.

Closing issue.

**Comment by Roasbeef** [comment]
> github.com/lightningnetwork/lnd/build.GoVersion=go1.13.4

Weird, this tag shows that it was being built with Go 1.13.4...
