### ISSUE TITLE
Install fails "package gitlab.com/NebulousLabs/fastrand: unrecognized import path" 

### ISSUE THREAD

**Issue by johnblanc** [lightningnetwork/lnd#4444]
### Background

I follow the install instructions to the point and all is fine until I do "go get -d github.com/lightningnetwork/lnd" to which I get:

> package gitlab.com/NebulousLabs/fastrand: unrecognized import path "gitlab.com/NebulousLabs/fastrand" (parse https://gitlab.com/NebulousLabs/fastrand?go-get=1: no go-import meta tags ())
package gitlab.com/NebulousLabs/go-upnp/goupnp: unrecognized import path "gitlab.com/NebulousLabs/go-upnp/goupnp" (parse https://gitlab.com/NebulousLabs/go-upnp/goupnp?go-get=1: no go-import meta tags ())
package gitlab.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1: unrecognized import path "gitlab.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1" (parse https://gitlab.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1?go-get=1: no go-import meta tags ())

### Your environment

* which operating system - Debian 10 behind TOR

### Steps to reproduce
Just following the install instructions

**Comment by wpaulino** [comment]
Are you able to build with the following:

```
$ git clone https://github.com/lightningnetwork/lnd
$ cd lnd
$ make install
```

**Comment by johnblanc** [comment]
no, it gives

> make install
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
 Installing lnd and lncli.
GO111MODULE=on go install -v -tags="" -ldflags " -s -w -X github.com/lightningnetwork/lnd/build.Commit=clock/v1.0.0-167-g60446494e9ea90e50a4753453ba6bb3615dcdd1a -X github.com/lightningnetwork/lnd/build.CommitHash=60446494e9ea90e50a4753453ba6bb3615dcdd1a -X github.com/lightningnetwork/lnd/build.GoVersion= -X github.com/lightningnetwork/lnd/build.RawTags=" github.com/lightningnetwork/lnd/cmd/lnd
/bin/sh: 1: go: not found
make: *** [Makefile:126: install] Error 127



and go is installed as per the instructions

**Comment by wpaulino** [comment]
`go` needs to be part of your path (https://golang.org/doc/install#tarball).

**Comment by johnblanc** [comment]
The path in which command?
The one from the official install instructions or the one provided here?
Please be more clear and newbie friendly, im very new to this.

**Comment by guggero** [comment]
The error message `/bin/sh: 1: go: not found` tells you that the `make` command doesn't find the `go` command.
You can fix this by adding the `go` binary to your `$PATH` environment variable. This should be part of the golang installation instructions, so maybe you skipped a step. Or you need to open a new terminal window for the changes to take effect.

**Comment by johnblanc** [comment]
I managed to make install the git cloned lnd repo
however now I get 
/lnd$ lnd
bash: lnd: command not found

I've set $PATH as per the instructions, see
/lnd$ echo $PATH
/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

is that what it should look like?

**Comment by wpaulino** [comment]
You'll need to add `$GOPATH/bin` to your `$PATH` as well.

**Comment by johnblanc** [comment]
Please let me know how, im quite new to this and need more precise instructionsfor which I'm sorry :(

**Comment by johnblanc** [comment]
anyone please?

**Comment by guggero** [comment]
See https://opensource.com/article/17/6/set-path-linux for how to set the path variable correctly.
You need to add the folder where you installed `go` to (usually something like `/usr/lib/go-1.xx/bin`) and also `$GOPATH/bin`.
What `$GOPATH` is and how you configure is described here.
Once this is all set up correctly, your `echo $PATH` should look something like this:
`/var/lib/go-1.xx:$GOPATH/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`.

**Comment by johnblanc** [comment]
What confuses me is that I followed the install instructions to the letter, my path looks like this now
echo $PATH
/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

and it still doeesn't work

I'll try again of course, but just so confusing :(

**Comment by johnblanc** [comment]
> See https://opensource.com/article/17/6/set-path-linux for how to set the path variable correctly.
> You need to add the folder where you installed `go` to (usually something like `/usr/lib/go-1.xx/bin`) and also `$GOPATH/bin`.
> What `$GOPATH` is and how you configure is described here.
> Once this is all set up correctly, your `echo $PATH` should look something like this:
> `/var/lib/go-1.xx:$GOPATH/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`.
> 
> Only then you run `make install` in the `lnd` directory which will install the `lnd` binary to `$GOPATH/bin/lnd`.

Seems like the command "export PATH=$PATH:/usr/local/go/bin" did't add it to the $PATH the first few times but now it did and it looks like that "/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:**/usr/local/go/bin**"

However,  lnd still doesn't start "lnd
bash: lnd: command not found"

I tried adding this $GOPATH (which by the way isn't in the install instructions) with this command "export PATH=$PATH:$GOPATH/bin" but probably that isn't right because lnd still doesn't run and now $PATH looks like this "/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/bin:/bin"

and echo $GOPATH returns nothing.

Also the only referrence about $GOPATH in the install instructions is "NOTE: Our instructions still use the $GOPATH directory from prior versions of Go, but with Go 1.12, it's now possible for lnd to live anywhere on your file system." and nothing about setting it to anything.
So, following the instructions to the letter makes it impossible ot isntall, at least for me.

Would appreciate if someone can give me the exact commands I need to add so it works,

Go is installed at "/usr/local/go/" as per the instructions at https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

**Comment by guggero** [comment]
From https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md:

> At this point, you should set your $GOPATH environment variable, which represents the path to your workspace. By default, $GOPATH is set to ~/go. You will also need to add $GOPATH/bin to your PATH. This ensures that your shell will be able to detect the binaries you install.

So set:
```
GOPATH=~/go
PATH=$PATH:$GOPATH/bin
```

Then change into the directory where you downloaded `lnd` and run `make install`.
That should create a file located in `~/go/bin/lnd`.
If that does not work, then you can run `make build` which will create a file `lnd-debug` in the current directory (where you downloaded the `lnd` source). You can start that by running `./lnd-debug` (note the dot slash at the beginning, that means, run the thing in the current directory).

**Comment by johnblanc** [comment]
Ok here is what happened, i've overall missed the 
export GOPATH=~/gocode
export PATH=$PATH:$GOPATH/bin
instructions because they are under FreeBSD instructions, at least look so, and I thought this is FreeBSD specific instructions.

works now, thank you all!
