### ISSUE TITLE
Cannot specify RPC host on Bitcoind testnet

### ISSUE THREAD

**Issue by k26dr** [lightningnetwork/lnd#4445]
### Background

Setting `--bitcoind.rpchost` does not work when `--bitcoind.testnet` is also set. 

### Your environment

* version of `lnd`: 0.10.0-beta.rc4
* which operating system (`uname -a` on *Nix): Ubuntu 18.04
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.19
* any other relevant environment details

### Steps to reproduce

Run lnd with both `--bitcoind.rpchost` and `--bitcoind.testnet` set. 

### Expected behaviour

Attempt to connect to the RPC host at the provided host and port.  

### Actual behaviour

Attempts to connect to localhost:18832

**Comment by carlaKC** [comment]
What value are you setting for `--bitcoind.rpchost`? 

What's probably happening is we're ignoring the value you provide because it's not specified with the format `host:port`, looking at where we [read](https://github.com/lightningnetwork/lnd/blob/master/chainregistry.go#L280) our config values:
```
If the specified host for the btcd/ltcd RPC server already has a port specified, 
then we use that directly. Otherwise, we assume the default port according to
the selected chain parameters.
```

**Comment by k26dr** [comment]
I'm passing in `--bitcoind.rpchost=100.70.202.113:8332` as the argument

**Comment by vwoo** [comment]
Can you try --bitcoin.testnet

No 'd' after bitcoin.

**Comment by k26dr** [comment]
it's working now so it looks like that was the issue..sorry for disturbing you about that. thanks for the help.
