### ISSUE TITLE
lncli bakemacaroon - permission denied

### ISSUE THREAD

**Issue by fiksn** [lightningnetwork/lnd#4462]
### Background

`lncli bakemacaroon peers:read peers:write`

fails with

`[lncli] rpc error: code = Unknown desc = permission denied`

### Your environment

* version of `lnd`

lnd version 0.10.3-beta commit=

* which operating system (`uname -a` on *Nix)

`Linux ln 4.19.118 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 aarch64 GNU/Linux`

* version of `btcd`, `bitcoind`, or other backend

Bitcoin Core version v0.19.1.0-g58ba7c314d552cea8cb024960a8504577aee586f

* any other relevant environment details

Running on Rapsberry Pi 4

### Steps to reproduce

`lncli --macaroonpath .../data/chain/bitcoin/mainnet/admin.macaroon --tlscertpath .../lnd.cert --rpcserver 127.0.0.1:10009`

### Expected behaviour

A macaroon should be baked, potentially serialized to a file when using --save_to

### Actual behaviour

I get `[lncli] rpc error: code = Unknown desc = permission denied` despite the fact I am using admin.macaroon.

**Comment by guggero** [comment]
See https://github.com/lightningnetwork/lnd/blob/master/macaroons/README.md#upgrading-from-v080-beta-or-earlier and https://github.com/lightningnetwork/lnd/releases/tag/v0.9.0-beta. You need to re-generate your macaroons.

**Comment by fiksn** [comment]
My bad, sorry. Thought the macaroons have already been recreated in the meanwhile. Works perfectly now.
