### ISSUE TITLE
Feature request: Integration with systemd

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#4470]
### Background

I need to do some post-start automation on LND (unlocking, generating a special macaroon with special permissions., maybe more in the future...) As far as I know (by absence of documentation), LND doesn't notify `systemd`, nor uses socket activation, so this must be achieved either by waiting some long time period or waiting in a loop for RPC to be available.

It'd be much easier if LND supported socket activation (not that I would ever rely on it - just as a coordination mechanism!) for GRPC and REST or used `systemd` notification after it binds the sockets.

**Comment by Roasbeef** [comment]
What does "socket activation" mean in this content? Unix sockets?

**Comment by Kixunil** [comment]
Both Unix and IP sockets. The way it works is `systemd` first binds all sockets of all services and then passes their file descriptors to the services it manages. The services then have to use those descriptors instead of binding their own. This is best done using a library.

This way, they can be launched at the same time as a request from any of them will be just waiting for `accept()` instead of failing with connection refused.

**Comment by Kixunil** [comment]
I assume #3982 is prerequisite for this (will have to check the code more deeply to know for sure).

**Comment by guggero** [comment]
Resolved by #5536.

**Comment by Kixunil** [comment]
Ah, in #5536 I said "part of" because I misremembered what this issue proposed - I thought I proposed to do both. You're correct that this was resolved.

Socket activation could still be useful even if not urgent. Is it OK to open a wishlist (non-priority) issue or should I rather avoid the clutter? (The main reason to open an issue for me would be getting notified if someone else wants to do it too.)

**Comment by guggero** [comment]
Ah, I overlooked the socket activation part. Though I don't think we'll want to integrate with `systemd` on such a deep level. The whole RPC/REST socket handling is already complex enough (with the mobile support) that I don't see an advantage large enough to justify such a refactor.
If you feel otherwise, I'd suggest opening a new issue just for the socket activation.

**Comment by Kixunil** [comment]
I think that *after RPCs were unified* it should be as simple as binding the listening socket slightly differently unless I'm missing something.

Opened #5666
