### ISSUE TITLE
channeldb: open bbolt database with a timeout 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4485]
As is, when we open the database, we'll block indefinitely waiting to obtain the file lock on the database file. Instead, we should [open the database with the timeout field specified](https://godoc.org/github.com/coreos/bbolt#Options). With a timeout value set, an error will be returned (which will shutdown `lnd`) if we're unable to open the database after a set duration.

**Comment by yyforyongyu** [comment]
I'm looking into this issue.

One question, to make this happen, we need to change [this line](https://github.com/btcsuite/btcwallet/blob/master/walletdb/bdb/db.go#L377) in `btcsuite/btcwallet/walletdb` first?

**Comment by ErikEk** [comment]
I looked into the issue and I can't see any way around it.

**Comment by Roasbeef** [comment]
Should be able to proceed with this after https://github.com/btcsuite/btcwallet/pull/714 is merged.
