### ISSUE TITLE
Pending forced closed channel with >2600 confirms 

### ISSUE THREAD

**Issue by QueenGit** [lightningnetwork/lnd#4489]
### Background

I have a forced closed channel wich has now over 2600 confirmations , TLD is 144
It is this channel : https://1ml.com/channel/621871682158264320

### Your environment

* 0.10.3-beta
* Debian

### Steps to reproduce

Don't know

### Expected behaviour

The channel should be closed and not be pending

### Actual behaviour

It keeps pending

**Comment by Roasbeef** [comment]
Is your node synced to the chain (can be checked in `lncli getinfo`). Also if you look at `pendingchannels`, is the `blocks_till_maturity` negative?

**Comment by Roasbeef** [comment]
Also if you have a very small amount on your side, then it may not be able to be swept immediately, unless you manually lower the target fees on your lnd node.

**Comment by QueenGit** [comment]
> Is your node synced to the chain (can be checked in `lncli getinfo`). Also if you look at `pendingchannels`, is the `blocks_till_maturity` negative?

Yes, its synced and `blocks_til_maturity: -2593`

**Comment by QueenGit** [comment]
> Also if you have a very small amount on your side, then it may not be able to be swept immediately, unless you manually lower the target fees on your lnd node.

Yes, its a small amount, but how wo lower the target fees ?

**Comment by Roasbeef** [comment]
As is, you'll need to either use the `bumpfee` command manually, or just wait until the chain fees have lowered. Eventually it'll confirm.
