### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#4491]
2020-07-28 08:12:47.305 [INF] LTND: Version: 0.10.1-beta commit=v0.10.1-beta, build=production, logging=default
2020-07-28 08:12:47.306 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2020-07-28 08:12:47.306 [INF] LTND: Opening the main database, this might take a few minutes...
panic: freepages: failed to get all reachable pages (page -1835263452: out of bounds: 28694)

tried to recover using chantools with not success.
```
./chantools compactdb --sourcedb ~/.lnd/data/graph/mainnet/channel.db --destdb /tmp/compacted.db
2020-07-28 08:33:20.717 [INF] CHAN: chantools version v0.2.0 commit v0.2.0-6-gaf2094b
panic: runtime error: index out of range [3253368639] with length 268435455

goroutine 1 [running]:
github.com/coreos/bbolt.(*leafPageElement).key(...)
	/home/bitcoin/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/page.go:120
github.com/coreos/bbolt.(*Cursor).keyValue(0x253bc68, 0x5c72137b, 0x29, 0x2c8a10, 0x24c4340, 0x2580ce0, 0x2586710, 0x1)
	/home/bitcoin/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/cursor.go:350 +0x1ac
```

What should I do ?

**Comment by guggero** [comment]
It sounds like the data part of your channel DB was corrupted, not just the freepages (which can happen on improper shutdown).

I'm not sure you can recover to a normal state from this if `compactdb` fails. Do you have a `channel.backup` file? You might want to [recover your funds from the SCB](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md). Unfortunately this will close all channels and incur a lot of on-chain fees, depending on when the last fee update happened (when was the node operational last?).

**Comment by halseth** [comment]
@offerm can be closed?

**Comment by offerm** [comment]
I guess so. I was not able to recover from this and had to recreate the node and close all channels using the backup.

A few days back I has a similar error after node crash but second restrat of lnd was ok.

**Comment by guggero** [comment]
What storage medium are you using for the `lnd` data directory? This sounds like you might have a faulty drive if you continue to get these errors.

**Comment by offerm** [comment]
I was using external hard drive for bitcoin and lnd directories.
Afrer last event I move the lnd directory to the local drive.

Both incidents happened after the machine halted for some reason.

Offer

**Comment by guggero** [comment]
> Both incidents happened after the machine halted for some reason.

Thanks for the information. Judging from that, I suspect this is a hardware issue. Not cleanly shutting down will often result in DB corruption. I'd suggest investigating the unexpected halts of the machine to avoid future problems.

Closing this for now.
