### ISSUE TITLE
Confusing behavior regarding macaroons and wallet initialization

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#4498]
### Background

My understanding is that the macaroons should not be present right after start of LND, only after creating the wallet. I've read the code and the docs and it should be this way. However @ShahanaFarooqui [claims](https://github.com/Ride-The-Lightning/RTL/issues/314#issuecomment-665955059) that her LND generates `admin.macaroon` before the wallet is initialized. `noseedbackup` option was not used.

Could you please explain what could cause LND to generate macaroons before initialization?

### Your environment

* my version of `lnd` 10.2
* @ShahanaFarooqui version of `lnd`: 10.4 - yes, I checked the code and changelog, they should act the same. Also same problem was apparently present few versions ago (see the linked issue)
* my operating system (`uname -a` on *Nix) Linux <irrelevant> 4.19.128-1.pvops.qubes.x86_64 #1 SMP Sun Jun 28 06:19:18 UTC 2020 x86_64 GNU/Linux
* @ShahanaFarooqui operating system: I don't know.
* my version of `bitcoind`: 0.20.0
* @ShahanaFarooqui version of `bitcoind`: I don't know
* any other relevant environment details: you can see our configurations at the linked issue

### Steps to reproduce

0. Become myself
1. Run a new instance of LND
2. `admin.macaroon` is not generated
3. Become @ShahanaFarooqui
4. Run a new instance of LND
5. `admin.macaroon` is generated

### Expected behaviour

`admin.macaroon` is not generated without wallet initialization

### Actual behaviour

`admin.macaroon` is not generated if without wallet initialization if you are myself and is generated without wallet initialization if you are @ShahanaFarooqui

**Comment by guggero** [comment]
The macaroons are generated [here](https://github.com/lightningnetwork/lnd/blob/master/lnd.go#L443). If you look a few lines above, the unlock happens [here](https://github.com/lightningnetwork/lnd/blob/master/lnd.go#L395) which blocks until a password is received (or a new wallet is created on first startup). This blocking step can only be skipped by using `--noseedbackup`.
Therefore if an `admin.macaroon` is available on disk _before_ the wallet is unlocked, it was either created by a previous node start or by using `--noseedbackup`.

Also it might be helpful to note that **none** of the `WalletUnlocker` calls require a macaroon. The security RPC interceptor is not yet started at that point.
