### ISSUE TITLE
A good alternative to noseedbackup?

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#4499]
### Background

I used `noseedbackup` for testing purposes (regtest) recently and it was very helpful. I created [a simple script to launch a new instance of `lnd`](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/tests/lib/spawn_secondary_lnd.sh) so that I can test opening channels and sending transactions.

Removing `noseedbackup` would force me to write complicated unlocking logic into my tests. Is there any good alternative to avoid such complication?

What is the rationale for removing `noseedbackup`? If it's just a concern that people would lose money or doing stupid things (like the old BTCPayServer config), why not just panic if `noseedbackup` is used on mainnet and allow it in other cases?

**Comment by Roasbeef** [comment]
> What is the rationale for removing noseedbackup? 

It hasn't been removed? I also use it on simnet as well. For actual coins I use scripts to unlock lnd automatically on restart. Depending on how you're scripting things, it shouldn't be _too_ complicated.

**Comment by Kixunil** [comment]
`lnd --help` says:

```
     --noseedbackup                                          If true, NO SEED WILL BE EXPOSED AND THE WALLET WILL BE ENCRYPTED USING THE DEFAULT PASSPHRASE -- EVER. THIS FLAG IS ONLY FOR TESTING AND IS BEING  DEPRECATED.
```

My understanding is that "deprecated" == "will be removed"

I use unlock scripts too, but it'd be really cool to not have to introduce higher probability of breaking into tests.

**Comment by Roasbeef** [comment]
Ah, I think that was put there just to discourage people from relying on it heavily. At the moment, we don't have any concrete plans for deprecation, and would likely accept a PR that modified that message and/or only allowed it to be used on non-mainnet.

**Comment by Kixunil** [comment]
OK, made a PR to change the message.
