### ISSUE TITLE
Feature request: add payinvoice option to increace payment timeout (to avoid FAILURE_REASON_TIMEOUT)

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#4518]
### Background

Currently the most annoying thing in my case is `FAILURE_REASON_TIMEOUT`. Some times I have to run `lncly payinvoice ...` multiple times (maybe 3 or 4) to make it succeed. Else, I get `FAILURE_REASON_TIMEOUT`. Maybe my node is slow, maybe the channels are not the best, but it DOES succeed after few retries. So why not allow to specify `--timeout` to allow it to search for valid route for some time longer? Or maybe `lnd.conf` option to change the default?

### Your environment

* `0.10.3-beta commit=v0.10.3-beta`
* Debain 10 Buster, 4.19.0-10-armmp-lpae
* Bitcoind 0.20.1

### Steps to reproduce

Have slow node and try to pay some invoices?

### Expected behaviour

Actions that has timeout should have timeout overridable.

### Actual behaviour

No `--timeout` (or similar) option for `payinvoice`. Have to re-execute `payinvoice` again multiple times in some cases to achieve `Payment status: SUCCEEDED`.

**Comment by Talkless** [comment]
Does https://github.com/lightningnetwork/lnd/pull/4688 fixes this?

**Comment by wpaulino** [comment]
Added in https://github.com/lightningnetwork/lnd/pull/4688.
