### ISSUE TITLE
Return node feature bits in subscribe channel graph graph topology updates

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4522]
### Background

When subscribing to the channel graph, the node update message does include a proto field dedicated to features but this is currently returned as empty bytes

If the caller does desire to read the feature bits of a node, a workaround is to request node info for the node whose identity key is in the announcement

### Your environment

* LND 0.11.0-beta.rc2

### Steps to reproduce

1. Subscribe to channel graph `SubscribeChannelGraph` / `GraphTopologyUpdate`
2. Receive a node update `NodeUpdate`
3. Inspect fields of node update for features

### Expected behavior

Node update should include the node feature bits, such as support for larger channels

### Actual behavior

Advertised features are blank

**Comment by bhandras** [comment]
Fixed in https://github.com/lightningnetwork/lnd/pull/4822
The fix adds a new `Features` field to the proto, containing the feature matrix, while the old `GlobalFeatures` field is deprecated.
