### ISSUE TITLE
Update GitHub About section

### ISSUE THREAD

**Issue by elvece** [lightningnetwork/lnd#4523]
### Background

Website meta tags should conform to the [open graph](https://ogp.me/) standard for sharing data on social media sites.
To have more descriptive information in the `og:description` meta tag for a project website hosted solely on GitHub, update the About section (presently displayed in the right column on the main page). 

### Expected behaviour

For instance, something like:

`<meta property="og:description" content="A complete implementation of a lightning network node with pluggable backend chain services.">`

### Actual behaviour

`<meta property="og:description" content="Lightning Network Daemon ⚡️. Contribute to lightningnetwork/lnd development by creating an account on GitHub.">`

**Comment by saubyk** [comment]
Unclear on the benefit or the need for this. Closing now.
