### ISSUE TITLE
[Docs] It looks like everything is "experimental"

### ISSUE THREAD

**Issue by losnappas** [lightningnetwork/lnd#4524]
If you look at this:

![Screenshot from 2020-08-12 10-03-30](https://user-images.githubusercontent.com/25119292/89985722-0adba680-dc6b-11ea-9087-ae9819ce60e4.png)

It looks like everything is "experimental". Also, when you scroll to Watchtower, for example, it doesn't say that it's experimental there, and the "experimental" section is hidden.

**Comment by Roasbeef** [comment]
It's mainly a
