### ISSUE TITLE
LND funding transaction stuck in mempool due to low fees and Bumpfee giving error

### ISSUE THREAD

**Issue by imacfan** [lightningnetwork/lnd#4530]
### Background

I opened a channel. Which is in pending state for long time. So i tried to find the issue. 
It seems LND funding transaction stuck in mempool due to low fees.

**I checked the logs of LND:**

_2020-08-07 22:24:17.996 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(#############:0): 
unmatched backend error: -26: mempool min fee not met, 223 < 242
2020-08-07 22:24:17.999 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(#############:0)
2020-08-07 22:24:18.000 [INF] NTFN: New block epoch subscription
2020-08-07 22:24:18.006 [INF] CNCT: ChannelArbitrator(#############:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=642722_

### Your environment

* version of `lnd` :**0.10.3**
* which operating system (`uname -a` on *Nix): **debian**
* version of `btcd`, `bitcoind`, or other backend: **bitcoind**
* any other relevant environment details

### Steps to reproduce

Opened a channel. In pending state.

### Expected behaviour

Transaction is stuck.Now I am trying to use **Bumpfee** in following way:

lncli wallet bumpfee [**passign_Channel_Point here**] --sat_per_byte 200

### Actual behaviour

**Error**: -- [lncli] outpoint should be of the form txid:index

**Comment by guggero** [comment]
From the error message it looks like you didn't provide the full outpoint (transaction ID plus the output index, separated with a colon).
Also you cannot bump the fee of the funding transaction itself because that would need a new pair of signatures on the commitment transactions. Try bumping the fee of the change output instead (if there is one).
See https://lightningwiki.net/index.php/Bumping_fee_for_lightning_channel_open

**Comment by imacfan** [comment]
> From the error message it looks like you didn't provide the full outpoint (transaction ID plus the output index, separated with a colon).
> Also you cannot bump the fee of the funding transaction itself because that would need a new pair of signatures on the commitment transactions. Try bumping the fee of the change output instead (if there is one).
> See https://lightningwiki.net/index.php/Bumping_fee_for_lightning_channel_open

Yup, it did work! I was missing NUMBER after colon. Explained in the URL that you shared. Thanks a lot!!

**Comment by jackgopack4** [comment]
Quick Q: if I have a transaction spending an entire UTXO (not a funding or closing just on-chain send), is there any way to bumpfee to do RBF even though there's no change output? lncli wallet bumpfee gives no output when selecting index 0

**Comment by guggero** [comment]
No output (=no error message shown) usually means success in lncli. Are you sure it didn't work?

I think the bumpfee command is the only place where RBF is implemented, currently.
