### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#4532]
### Background

The LND after a long time running crashed with `fatal error: concurrent map read and map write` error.

### Your environment

* version of `lnd` - 0.9.1-beta commit=v0.9.1-beta, build=production
* go - v1.14

### Steps to reproduce

I don't know

### Actual behaviour

Crash with lines:

```
2020-08-13 04:33:18.391 [INF] CHFD: Performing funding tx coin selection using 13327 sat/kw as fee rate
fatal error: concurrent map read and map write

goroutine 250410745 [running]:
runtime.throw(0x12ab8d3, 0x21)
        /home/bitcoin/go1.14/src/runtime/panic.go:1112 +0x72 fp=0xc0ac7591f0 sp=0xc0ac7591c0 pc=0x4360b2
runtime.mapaccess2(0x10b1fe0, 0xc00051c8d0, 0xc0ac759304, 0x2c, 0xc02266a4b0)
        /home/bitcoin/go1.14/src/runtime/map.go:469 +0x258 fp=0xc0ac759230 sp=0xc0ac7591f0 pc=0x40fe48
....
```

and so on...

The full log with this crash (many lines) is here (encrypted for your `release key`):

https://drive.google.com/file/d/1VW4o5-TI9BUwZeZb8-3FhGTG1IH3IrY8/view?usp=sharing

**Comment by guggero** [comment]
Would be useful to get at least all lines of the stack trace. There should be no confidential information in those.
I'm not the owner of the release key so I can't look into the shared file.

**Comment by LNBIG-COM** [comment]
Here txt log file of full stack:

https://drive.google.com/file/d/18zGe7urINgVPOca1fU3RHRMTpWPpiyaQ/view?usp=sharing

**Comment by guggero** [comment]
Thanks! Was able to create a fix https://github.com/btcsuite/btcwallet/pull/715.

**Comment by LNBIG-COM** [comment]
Thanks! ;-)
