### ISSUE TITLE
Incorrect amounts in wallet transactions when a channel is opened (rare)

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#4536]
### Background

Incorrect amounts in wallet transactions when a channel is opened (rare). I believe that this is reflected in the balance of the wallet and leads to an incorrect display of the balance. This is most likely a bug.

### Your environment

* version of `lnd` - `0.9.1-beta commit=v0.9.1-beta, build=production`
### Steps to reproduce

I don't know. May be a long time using of the LND.

### Expected behaviour

The amount of transaction for channel point should show minus (-) amount with on-chain fee.

### Actual behaviour

Sometimes there are zero (`0`)

For example: lnd-28. I see:

```
l listchaintxns
...
        {
            "tx_hash": "2abd07f52646a3655cd2323626e08c3af97b972b63946d78e2a980a33a636136",
            "amount": "0",
            "num_confirmations": 70877,
            "block_hash": "00000000000000000023ccd837eae948765766dba0a178e3b2b13e412c76c9d2",
            "block_height": 572833,
            "time_stamp": "1555986343",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qdgaxqp4hz8ans0nejydzw754ank6nlf9v7unhdpdyevz7plxq3ns202snw",
                "bc1quxsrvq9mr5e33yyw60zf97wldz082ugh7f8pg9"
            ],
            "raw_tx_hex": "0100000000010326401e6890b0993758b0b9c5a671177b608874620457081bb5bfa02ca26575880000000000ffffffffbef866de23c9ebd8b95e89017df93d057384c77c907632970ca88aae3d3e95e70100000000ffffffffdc261d40679e8210f747819859a7f11d2c9d37a14ead5c8d721b8b2c6c0a6de80000000000ffffffff0240420f00000000002200206a3a600
        },
```

But this transaction was used for channel opening because i see closed channel with channel point with same TxID:

```
l closedchannels

        {
            "channel_point": "2abd07f52646a3655cd2323626e08c3af97b972b63946d78e2a980a33a636136:0",
            "chan_id": "629836544430374912",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "7d2c38bc431995359e4bb1dcaf05055a456283933b7a8b21fc1aff5badb9d3bd",
            "remote_pubkey": "03d9a5341083d9ae16fd4f6fc117ed8a7f25689c02d0e3f4a955d45105e5ba9c63",
            "capacity": "1000000",
            "close_height": 638091,
            "settled_balance": "398541",
            "time_locked_balance": "0",
            "close_type": "REMOTE_FORCE_CLOSE"
        },
```

I think and i see for other transactions of opening channels that they has -NNNN amounts where NNNN is channel capacity + fees
I expect that the transaction `2abd07f52646a3655cd2323626e08c3af97b972b63946d78e2a980a33a636136` should have in `listchaintxns` list an amount as "-1012727" sats because 1000000 is capacity (zero output) and fee of this transaction is 12727 sats.

P.S. I found such a transaction with my scripts looking for such inconsistencies. I have another similar example that I can write about if you are interested in it. In another example, the sum is positive (although a channel was also opened, which means the sum must be less than zero).

**Comment by Roasbeef** [comment]
The amount shows zero as it's paying to an address that isn't solely controlled by the wallet (the multi-sig script). This can also happen if we do a sweep, and there's no change, or if we receive an incoming channel funding.

**Comment by LNBIG-COM** [comment]
> The amount shows zero as it's paying to an address that isn't solely controlled by the wallet (the multi-sig script).

I think in this case amount should be negative amount. In my opinion, you inattentively read what I write.

**Comment by wpaulino** [comment]
> version of lnd - 0.9.1-beta commit=v0.9.1-beta, build=production

Do you still see this in the latest version?

**Comment by LNBIG-COM** [comment]
> > version of lnd - 0.9.1-beta commit=v0.9.1-beta, build=production
> 
> Do you still see this in the latest version?

Yes

But I figured it out. I think @Roasbeef is right. 

The TX `2abd07f52646a3655cd2323626e08c3af97b972b63946d78e2a980a33a636136` has zero balance in wallet transactions but the `2abd07f52646a3655cd2323626e08c3af97b972b63946d78e2a980a33a636136:0` points to `7d2c38bc431995359e4bb1dcaf05055a456283933b7a8b21fc1aff5badb9d3bd` and then the output `7d2c38bc431995359e4bb1dcaf05055a456283933b7a8b21fc1aff5badb9d3bd:0` points to `862c9193e5ab231fee83b58c68ab8047ce29de6906387094dd0cacffe9e1320b` transaction. And the `862c9193e5ab231fee83b58c68ab8047ce29de6906387094dd0cacffe9e1320b` is in my wallet again with positive value. I think it's resolved HTLC.

**Comment by LNBIG-COM** [comment]
Why did the opening of the channel entail a transaction in my wallet with a zero value? Was it initiated by the other side?

**Comment by wpaulino** [comment]
Channels that you are not the initiator for should never show in your wallet. Are you having this 0 amount issue in the same node experiencing #4535?

**Comment by LNBIG-COM** [comment]
No. In this ticket i am about `lnd-28`. And there i see many "0" amount transactions in `listchaintxns`

The ticket _4535_ about `lnd-01` and oddly enough, I don't see any zero-sum transaction there.

**Comment by wpaulino** [comment]
Have you tried resetting the UTXO state of this node as well? This may also be related to the bug affecting your other issue given that they're on the same version.

**Comment by LNBIG-COM** [comment]
I checked other servers. All servers has hundreds zero amount transactions. After update up to LND v0.11.0-beta-rc4 (for example lnd-01 or lnd-28) and reindexing of wallet i don't see any zero transaction. But this process takes a long time.
The total balance of ballances of wallets and channels before and after does not change, except for the situation with the server lnd-01 (https://github.com/lightningnetwork/lnd/issues/4535)

I check same transactions by command:

```
lncli listchaintxns|grep amount|grep '"0"'
```

**Comment by LNBIG-COM** [comment]
> Channels that you are not the initiator for should never show in your wallet. Are you having this 0 amount issue in the same node experiencing #4535?

I have a news about this.

The lnd-28 was updated to last release (0.11.0-beta-rc4) and the wallet was reindexed. I didn't see after zero amount transactions in `listchaintxns`. But today i checked and found them again. I understood it seems what was happening. To begin with, I want to say that despite your answer that the list should not show transactions where we are not the initiator, such transactions are still shown.

```
l listchaintxns:

    "transactions": [
        {
            "tx_hash": "d53ada59348872f1fb7c715870a2ab43be671651c30c8afa70710f065ccbaf63",
            "amount": "0",
            "num_confirmations": 47,
            "block_hash": "00000000000000000007523bad5165bdcf4b4a29174f8a523a63a27e7d4ecfd4",
            "block_height": 644227,
            "time_stamp": "1597726518",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qdpq38mfe7gjfzrq5vz8w5py0jh7k9rl3fpsfnqky4n6vaaqrlavsas0elj"
            ],
            "raw_tx_hex": "0100000000010288e4b07f4ef23908661bf7758628fe79993cb427be2dbeb74acf11fc84bb339c0000000000fffffffff269a15d9a8ebba1d2e32bcd4c6921b3894521c1876d2b626da1961032a4b5660000000000ffffffff01ec51a20000000000220020684113ed39f224910c14608eea048f95fd628ff148609982c4acf4cef403ff59024730440220722873799f970
            "label": ""
        },
```

The `d53ada59348872f1fb7c715870a2ab43be671651c30c8afa70710f065ccbaf63` was not found in `pendingchannels/closedchannels/listchannels` but parent one was.

```
l closedchannels channels:

        {
            "channel_point": "a5b39e9056b7dbf130357c285d1d39c41ef2994594a18bab9bfedd528987b3cb:0",
            "chan_id": "706686909577297920",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "66b5a4321096a16d622b6d87c1214589b321694ccd2be3d2a1bb8e9a5da169f2",
            "remote_pubkey": "03aa486f90c3796936b18fd4273b425023ae21d7bf1aa9026133d4b1a9a6f7f564",
            "capacity": "6747435",
            "close_height": 644225,
            "settled_balance": "6087071",
            "time_locked_balance": "0",
            "close_type": "COOPERATIVE_CLOSE",
            "open_initiator": "INITIATOR_REMOTE",
            "close_initiator": "INITIATOR_REMOTE",
            "resolutions": [
            ]
        }
```

The `66b5a4321096a16d622b6d87c1214589b321694ccd2be3d2a1bb8e9a5da169f2` tx is parent of `d53ada59348872f1fb7c715870a2ab43be671651c30c8afa70710f065ccbaf63` and has output #1 (not to be spent) as `0.06087071 BTC`. It's ` "settled_balance": "6087071"` as i understand and it's my funds. But other output (#0) of `66b5a4321096a16d622b6d87c1214589b321694ccd2be3d2a1bb8e9a5da169f2` is spent as 0.00649021 BTC. It's remote funds as i understand and spent transaction is `d53ada59348872f1fb7c715870a2ab43be671651c30c8afa70710f065ccbaf63`. So the LND shows to me remote-side spent transaction with amount "0". I think that it i reindexed my wallet now then this transaction would disappear. I have 5-6 same transactions in `lnd-01` now despite the fact that I also installed a new version there and reindexed the wallet too. Is it bug of the LND?

**Comment by wpaulino** [comment]
Thanks for the detailed response! It looks like you're running into https://github.com/lightningnetwork/lnd/issues/3746. I'll close this and you can track that issue for updates.

**Comment by wpaulino** [comment]
To get rid of the transactions, you'll need to re-index, but keep in mind that they can continue to show until https://github.com/lightningnetwork/lnd/issues/3746 is resolved.
