### ISSUE TITLE
Pending payments

### ISSUE THREAD

**Issue by ChuckNorrison** [lightningnetwork/lnd#4541]
### Background

After some time i can not make further transactions within my lnbits instance

### Your environment

* version of `lnd`
LND 0.10.4-beta
* which operating system (`uname -a` on *Nix)
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
see logs attached
* any other relevant environment details
DynDNS and LetsEncrypt Setup without Tor

Logs:
https://termbin.com/nejz

### Steps to reproduce

not sure:
- common lnbits installation
- enable self funding for invoice
  -  tweak lndrest.py of lnbits: json={"payment_request": bolt11, "allow_self_payment": True}
- create invoice and send from same wallet

### Expected behaviour

The invoice should be paid or it should be blocked to pay your own invoice

### Actual behaviour

no payments possible anymore

manual call lncli payinvoice <invoice string> from console hangs

> $ lndmanage lncli payinvoice lnbc11110n1p0n4edypp5w4syrwr45cd9njpd6fzmrvejafurzdua2nsddq5ptknf2y0rz26qdpqwe5kzgrvde3kc6fqwpshj6twwehkjcm9cqzpgsp5qyz3punehxnr6ct96as9l83cfu9xqzrzg60t6fmsnlm97cl8tjvq9qy9qsqjvhdttu8g0xpnlwqq8wwnljuv5nl5l293syf6gv5lx24upcvj7ehyjnl5yv2n5xd527xvaazwxrxeqmecmde8jcvyp66jtm2cw46pkqqejkaca
^CTraceback (most recent call last):
  File "/home/admin/lndmanage/venv/bin/lndmanage", line 10, in <module>
    sys.exit(main())
  File "/home/admin/lndmanage/venv/lib/python3.7/site-packages/lndmanage/lndmanage.py", line 521, in main
    lncli.lncli(args_list[1:])
  File "/home/admin/lndmanage/venv/lib/python3.7/site-packages/lndmanage/lib/lncli.py", line 49, in lncli
    stderr=subprocess.PIPE,
  File "/usr/lib/python3.7/subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1681, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by ChuckNorrison** [comment]
ok seems the self funding attempts are blocked:
`[lncli] rpc error: code = Unknown desc = self-payments not allowed
`

**Comment by Roasbeef** [comment]
Closing as it seems to be resolved?
