### ISSUE TITLE
rpc: add new external API for manual channel enable/disable

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4543]
As is, we have an internal sub-system that automatically enables/disables channels based on the uptime of the peers we have channels opened with. This works well to ensure that we only advertise a channel as "enabled", if we have a stable connection with the channel peer. However, we've received a number of requests for routing node operators and businesses to be able to _manually_ enable/disable channel, independent of the current peer uptime signal. In lieu of such a feature, some users have started to use `UpdateChanPolicy` to advertise very high fees to discourage routing through a channel. 

This new could should ideally (?) live in the routing sub-server, or may trigger splitting some calls of that sub-server (like the htlc interception API) into a _new_ sub-server? 

One important implementation detail here is that if a user manually enables/disables a channel, then the current enable/disable sub-system should ignore the channel from there on out. We may also want to add the ability to return the channel to an "auto" mode, which relinquishes control of the channel availability back to the designated sub-system.

**Comment by Roasbeef** [comment]
Taking this one on.

**Comment by robot-dreams** [comment]
^ PR is a collaboration with @Roasbeef , I didn't just randomly start working on an already-claimed issue :)
