### ISSUE TITLE
config+funding: add new argument for max channel size that compiles to a channel acceptor 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4557]
With our latest release, users can use the `--protocol.wumbo-channels` to signal that they're willing to accept and create larger channels. However as is, users don't have a way to cap the largest channel they're willing to accept without writing a custom channel acceptor. To make regulating one's exposure easier, we should add a new `--max-chan-size` parameter to complement the existing `--min-chan-size` param.

**Comment by calvinrzachman** [comment]
I can give this one a try, if it's up for grabs. I have a start here https://github.com/lightningnetwork/lnd/pull/4567

**Comment by Roasbeef** [comment]
Fixed by #4567.
