### ISSUE TITLE
make: add CI sanity check for sample-lnd.conf

### ISSUE THREAD

**Issue by cfromknecht** [lightningnetwork/lnd#4569]
As this [recent PR shows](https://github.com/lightningnetwork/lnd/pull/4556) we haven't been very diligent about adding new config options
 to our `sample-lnd.conf`. A better approach would be to have a script run on travis that checks for new
config options and fails if there is not a corresponding entry in `sample-lnd.conf` to ensure they are
always modified in lock-step.

Given that lnd has various build configurations with customizable tags, I think for the now the
best place to start would be to check that the default production options (those available via
`make/make install`) are checked. Later we can look into more configurations.

Steps to completion:
 - [ ] Write a script that compares the `lnd` help output and `sample-lnd.conf` and looks for missing options.
   Preferably the script is as cross platform as possible, but it must minimally run on a linux travis box.
 - [ ] Modify the travis configuration to run the script in the `Sanity Check` phase similar to `rpc-check`
 - [ ] Optional: add a (phony) make target that builds and executes the script a la `rpc-check` for devs

**Comment by Roasbeef** [comment]
Now part of our CI.
