### ISSUE TITLE
lncli does not give a helpful error when the bitcoin backend cannot be reached

### ISSUE THREAD

**Issue by cilphex** [lightningnetwork/lnd#4578]
### Background

I am developing a project that uses lnd. If I use lncli to do, for example, `getinfo`, everything works fine while btcd and lnd are up and running.

If I kill the btcd process and then do `lncli getinfo`, it should produce a helpful error. Instead, it simply hangs.

### Your environment

* version of `lnd`

v0.11.0-beta

* which operating system (`uname -a` on *Nix)

golang:1.13-alpine

* version of `btcd`, `bitcoind`, or other backend

btcd v0.20.1-beta

* any other relevant environment details

Processes are running in Docker containers with golang:1.13-alpine base image.

### Steps to reproduce

- Start btcd
- Start lnd
- Run `lncli getinfo` - see that it returns proper information
- Stop btcd
- Run `lncli getinfo` - see that it hangs

### Expected behaviour

lncli should return some kind of helpful error if btcd is down and cannot be reached.

### Actual behaviour

lncli simply hangs on calls like `getinfo` when the btcd node is down.

**Comment by Roasbeef** [comment]
Related to this are the health checks we recently added that'll be part of 0.12: https://github.com/lightningnetwork/lnd/pull/4479 cc @carlaKC

**Comment by Roasbeef** [comment]
`lnd` will now shutdown itself if the `bitcoind/btcd` node goes down.
