### ISSUE TITLE
No `channel_reestablish` before funding tx is confirmed

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lnd#458]
Exact scenario:

1) eclair opens a channel to lnd
2) eclair publishes the funding tx
3) shutdown and restart eclair
4) eclair reconnects to lnd, handshake successful, but no `channel_reestablish` is received

If we remove step 3), channel establishment goes fine, and subsequent disconnections/reconnections work without any problem.

@cdecker was able to reproduce with `c-lightning` funding the channel.

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/pull/457

In this case, were enough confirmations reached to send the `FundingLocked`?

**Comment by pm47** [comment]
No, we disconnect as soon as the channel is funded (frequent use case on the mobile app)

**Comment by Roasbeef** [comment]
I see. Atm we don't consider a channel "active" until the channel has received a sufficient number of confirmations. So from the PoV of the current code, it doesn't send `channel_reestablish` as the channel isn't yet active (no confs, no `FundingLocked`). This can be added to that PR I linked by loading a channel even if it's pending. 

Looking at the spec, why would a node send the `FundingLocked` message if the channel hasn't yet reached a sufficient number of confirmations? That's contradictory...

**Comment by pm47** [comment]
> Looking at the spec, why would a node send the FundingLocked message if the channel hasn't yet reached a sufficient number of confirmations? That's contradictory...

I don't see where the specs says that?

To be clear expected behavior in my scenario is that if I reconnect immediately I just receive a `channel_reestablish`, no `funding_locked`.

**Comment by Roasbeef** [comment]
See the fragment above I pasted. IMO it should be amended to say _only_ send funding locked iff it's reach the num confs. 

I'll amend that PR I sent above to also address this case (_always_ send `channel_reestablish` even if the channel isn't open yet). Though IMO sending it does no purpose as neither sides can actually operate the channel yet.

**Comment by pm47** [comment]
> IMO it should be amended to say only send funding locked iff the channel has reached the num confs.

Gotcha, agree!

> Though IMO sending it does no purpose as neither sides can actually operate the channel yet.

I think `channel_reestablish` is related to the presence of commitments, not to the state of the channel. From that PoV it *kind* of makes sense to send `channel_reestablish` as soon as the first commitment has been exchanged.

**Comment by Roasbeef** [comment]
Test myself with that PR, can we'll now properly always send the chan sync message. Should also fix some issues users have reported when using the eclair app with `lnd`.
