### ISSUE TITLE
Remove requirement for experimental flag for --routing.assumechanvalid

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#4581]
### Background
lncli sendpayment fails with error even lncli channelbalance responds with 

lncli channelbalance
{
    "balance": "1990950",
    "pending_open_balance": "0"
}

channel has 3 confirmations

### Your environment

v0.11.0-beta
4.15.0-112-generic #113-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
neutrino backend

**Comment by Roasbeef** [comment]
Not much information to go off of, also if you're running w/ the neutrino backend, then make sure that you're using `--routing.assumechanvalid`. The slack may be a better place to debug any connectivity issues you may be having.

**Comment by enorrmann** [comment]
I'm confused about that flag ...
if I add it to lnd.conf I get

lnd.conf:17: unknown option: routing.assumechanvalid

and if I start lnd with --routing.assumechanvalid
I get
unknown flag `routing.assumechanvalid'

**Comment by guggero** [comment]
That flag is only available in experimental builds, which you currently need to run with Neutrino.
Try building with `make install tags=experimental`.

**Comment by enorrmann** [comment]
Actually I'm running neutrino from latest binary release. It is not required to build from source to enable neutrino

**Comment by guggero** [comment]
What I meant is that running `lnd` with Neutrino is _impractical_ without the `--routing.assumechanvalid` flag because that would make Neutrino download all blocks which takes forever.
But it is a discrepancy that we allow turning on Neutrino backends on a release build but not include the `--routing.assumechanvalid` flag. We'll fix that for `v0.12.0`.

**Comment by enorrmann** [comment]
great ! now I understand it ! thanks a lot

**Comment by pietroski-codefiction** [comment]
Hello everyone. I am having the same problem as @enorrmann had. I tried the flag --routing.assumechanvalid on the lnd v0.12.0 version although it seemed not to be necessary anymore; but the problem still persists on the first attemp only. It works after it fails at the first time. Does anyone else knows or suggests anything? Regards!!

**Comment by guggero** [comment]
Is your graph synced? Are you running with Neutrino? The `--routing.assumechanvalid` is still necessary for 0.12.1 and earlier if you're running on Neutrino. As long as `synced_to_graph` isn't true in `lncli getinfo` you won't be able to reliably pay invoices.
