### ISSUE TITLE
itest: btcd backend logs not complete

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lnd#4584]
Because `btcd` uses logrotate, when the log file size exceeds 10MB, it's compressed and saved as a `.gz` file, as shown in this [line](https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/log.go#L118).

On the other hand, in the `itest`, only the uncompressed logs are saved, as shown in this [line](https://github.com/lightningnetwork/lnd/blob/master/lntest/btcd.go#L107).
Debugging `itest` will sometimes need all the logs.

The logrorate settings should be configured for lnd nodes too, using `--maxlogfiles=0` to disable log rotation when running integration tests.

**Comment by ErikEk** [comment]
I'll take this one.

**Comment by ErikEk** [comment]
I'll wait for #4617 to be merged.

**Comment by ErikEk** [comment]
For the second part of the problem we need to access this function in btcsuite/btcd...
https://github.com/btcsuite/btcd/blob/2d7825cf709fc6ac15921cecfd4d62ec78ccbba2/log.go#L118
I'll leave it for now.
