### ISSUE TITLE
Autopilot goroutines stuck on connect

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#459]
As seen by @juscamarena, if the max number of autopilot channels is set too high (`autopilot.MaxChannels`), more goroutines than there are peers on the network might get created, and get stuck trying to connect/open channels.

We should limit the number of simultaneously spawned goroutines in this case to avoid this.

**Comment by juscamarena** [comment]
In my case I had set 100.

**Comment by juscamarena** [comment]
I haven't hit this since the last time, also updated to master.

**Comment by Roasbeef** [comment]
I think this was partially related to the panic fixed in: https://github.com/lightningnetwork/lnd/commit/2e2b262999da6288abb46f106c0fd90e5588e208

Before access to the map wasn't thread safe, so golang would at times panic as it detected concurrent read/writes to the map.
