### ISSUE TITLE
router.estimateRouteFee : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#4594]
running a test nodejs app calling ldn via GRPC

    let dest = Buffer.from('node_pubkey', 'hex');
    let queryRoutesReqRouter = { dest: dest, amt_sat: decoded.num_satoshis};
    router.estimateRouteFee(queryRoutesReqRouter, function (err, response) {
        // ... code
    });

lnd crashes with error 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbf75c8]

std terminal error
https://www.dropbox.com/s/54uhwkp4d4aphm9/std_out.log?dl=1

Log with debug = trace
https://www.dropbox.com/s/992cjmmuntlgsd2/lnd.zip?dl=1

### Your environment

v0.11.0-beta
neutrino
Linux  4.15.0-112-generic #113-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

**Comment by guggero** [comment]
Thanks for reporting this! Seems we forgot to pass a parameter when using the router from that RPC. Fix is incoming: #4596.
