### ISSUE TITLE
channel failure due to unknown error

### ISSUE THREAD

**Issue by viaj3ro** [lightningnetwork/lnd#4598]
I got quite a few of those with LND nodes in the last 2 years (I'm running the latest eclair version). It has gotten a bit better lately but still happening. This one was a channel to the yalls tor node, so maybe Alex can provide further useful info and logs.

```
2020-09-05 20:20:49,065 ERROR f.a.e.channel.Channel n:03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7 c:5ff017556b6864756d017799eb5d31067ea7c0ca7d18435290c6f889132f1eb5 - peer sent error: ascii='internal error' bin=696e7465726e616c206572726f72
```

**Comment by Roasbeef** [comment]
That's our blanket error for something happening with the channel. I think it's related to #4575, so closing this issue to consolidate.

**Comment by cfromknecht** [comment]
@Roasbeef AFAIK we return this error mostly when there is a database error wrt. to committing channel states, i suspect this is different from #4575. Perhaps we should reopen until we know more?

**Comment by viaj3ro** [comment]
This is what the LND peer had in his logs. He only keeps logs for a very short time, so there might be stuff missing.

``` "error": "disconnecting 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.17.70.80:9735, reason: read handler closed"
```

**Comment by cfromknecht** [comment]
@viaj3ro that error means that remote closed the connection, most likely triggered by the error sent above. that should be the expected behavior in this scenario iirc
