### ISSUE TITLE
Error when launching LND v0.11.0 on bitcoind: waiting for wallet encryption password, then lncli rpc error

### ISSUE THREAD

**Issue by VinceKunz** [lightningnetwork/lnd#4605]
### Background

I used to run a LND node on my PC on top of Bitcoin Core a few months ago. I was using LND v. 0.8.2, and it was working fine.

Since then, I halted running my LN node, and I just came back to it. I would like to run it again and develop my knowledge in Lightning.

I am beginning at Lightning, so your patience is appreciated :)

### Your environment

lnd v0.11.0-beta
Windows 10 64-bit OS, x-64 based processor (AMD Ryzen 5 1400 Quad-Core)
Bitcoin Core v. 0.20.0 (up and running)

### Steps to reproduce

First step on my terminal (Windows PowerShell (x86)), where the process was suspended and was waiting for wallet encryption password:

```
PS C:\Users\xxx\workspace\lightning\lnd-windows-amd64-v0.11.0-beta> .\lnd
2020-09-11 10:06:20.924 [INF] LTND: Version: 0.11.0-beta commit=v0.11.0-beta, build=production, logging=default
2020-09-11 10:06:20.988 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2020-09-11 10:06:20.989 [INF] LTND: Opening the main database, this might take a few minutes...
2020-09-11 10:06:20.989 [INF] LTND: Opening bbolt database, sync_freelist=false
2020-09-11 10:06:21.231 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
2020-09-11 10:06:21.231 [INF] LTND: Database now open (time_to_open=242.055ms)!
2020-09-11 10:06:21.243 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2020-09-11 10:06:21.243 [INF] RPCS: password gRPC proxy started at 0.0.0.0:8080
2020-09-11 10:06:21.243 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
```

Second step, where I shut the process down and used `lncli unlock` and inserted my wallet password:

```
2020-09-11 10:22:02.216 [INF] LTND: Received interrupt
2020-09-11 10:22:02.216 [INF] LTND: Shutting down...
2020-09-11 10:22:02.216 [INF] LTND: Gracefully shutting down.
2020-09-11 10:22:02.217 [ERR] LTND: unable to set up wallet password listeners: shutting down
2020-09-11 10:22:02.225 [INF] LTND: Shutdown complete
unable to set up wallet password listeners: shutting down
PS C:\Users\xxx\workspace\lightning\lnd-windows-amd64-v0.11.0-beta> .\lncli unlock
Input wallet password:
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connectex: No connection could be made because the target machine actively refused it."
```

### Expected behaviour

After having dowloaded LND updated version (the latest release, i.e. v. 0.11.0), I expected my Lightning node to run as it used to run a few months a go with the 0.8.2 version.

### Actual behaviour

I downloaded the latest release of LND, i.e. v. 0.11.0, but at some point it waited for wallet encryption password, with the following line: `Waiting for wallet encryption password. Use "lncli create" to create a wallet, "lncli unlock" to unlock an existing wallet, or "lncli changepassword" to change the password of an existing wallet and unlock it.`

As I couldn't input my password, I had to shut down the process with `Ctrl-C`and I tried to input my wallet's password by typing `lncli unlock`, but I got the following error message:

```
Input wallet password:
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connectex: No connection could be made because the target machine actively refused it."
```

Thank you for your support!

**Comment by guggero** [comment]
> Second step, where I shut the process down and used...

Why did you shut down `lnd`? It has to be running in order for you to unlock it. Currently `lnd` doesn't create a background service for itself automatically. So you have to run the process in the background the whole time.

**Comment by VinceKunz** [comment]
@guggero Sure you are right, but I shut `lnd` down because in my command line, there was only a blinking horizontal cursor on the left, with no input prompt where I could insert my password (see screenshot attached). This is why I tried to unlock the wallet beforehand, but I am probably missing something in the process.
<img width="973" alt="LND v0 11 0 pwd" src="https://user-images.githubusercontent.com/47115058/92906498-cb98a500-f424-11ea-884f-30ea3909d901.png">

**Comment by guggero** [comment]
Yes, that is just the log output of the daemon telling you what it's doing. You cannot interact with it there. You have to open a second terminal and issue the unlock command there. Think of `lnd` as being the server and `lncli` being the client tool to interact with the server. If the server isn't running, you cannot interact with it.

**Comment by VinceKunz** [comment]
@guggero This is what I was missing! Thanks a lot for your explanation, it makes fully sense. I understand now that it functions in the same way as Bitcoin Core with `bitcoind`and `bitcoin-cli`.

My wallet is successfully unlocked now and `lnd`is up and running!

**Comment by guggero** [comment]
Yes exactly, the `bitcoind` vs `bitcoin-cli` is probably an even better analogy.
You're welcome, happy to hear everything's working as expected now.
