### ISSUE TITLE
Channels pending_open and waiting_close forever

### ISSUE THREAD

**Issue by svewa** [lightningnetwork/lnd#4608]
### Background

I opened a few channels, possibly with way too low fee, around June 6th. They are in `pending_open_channels` since then. One of those channels I tried to force close, this one is in `waiting_close_channels` ever since (I guess a month at least now).
The one channel I tried to force_close has balance in limbo now, but I can't imagine it's in any more limbo than it was before.

### Your environment

Started with recent LND early June, now on 0.11.0 
Linux lnd 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
backend bitcoind 0.17.1

### Expected behaviour

After some time I'd expect the opening to be considered as failed. I don't know how to get rid of those channels.

$ lncli pendingchannels
{
    "total_limbo_balance": "4998239",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02740c62f38896511eb98479036b06907fcac283f62d08b756a1e25fb55e3f6772",
                "channel_point": "d1058537ee0c3306c5d59f507b65fa0b36f3287d130d741ba6f8427e251d78ce:1",
                "capacity": "5000000",
                "local_balance": "4997278",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "LEGACY"
            },
            "confirmation_height": 0,
            "commit_fee": "2722",
            "commit_weight": "600",
            "fee_per_kw": "3761"
        },
        {
            "channel": {
                "remote_node_pub": "02779c5e4fb6a87d8d18e8b9fa2846d847af6da0501cb39993478203248e922642",
                "channel_point": "42d4c42ff3d8d2483f242131bbb02aecdbf23ae6f81231aae8bcbb6b588d1efe:0",
                "capacity": "5000000",
                "local_balance": "4998486",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1514",
            "commit_weight": "600",
            "fee_per_kw": "2092"
        },
        {
            "channel": {
                "remote_node_pub": "02abbaa2bce7a353ec0624cfb91d19a3a6024d9bebdd96e79e6f289ea6915790e4",
                "channel_point": "acc00cc1c5c8c4b44caa37974ce61402f347fab6490fd9a8beeeb805f5334b72:0",
                "capacity": "5000000",
                "local_balance": "4998486",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1514",
            "commit_weight": "600",
            "fee_per_kw": "2092"
        },
        {
            "channel": {
                "remote_node_pub": "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
                "channel_point": "836dbe528f8ff02ccd87d949f9916d24a8eb7e3c2a40cc00e429654bad67e055:0",
                "capacity": "796293",
                "local_balance": "792475",
                "remote_balance": "0",
                "local_chan_reserve_sat": "7962",
                "remote_chan_reserve_sat": "7962",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "LEGACY"
            },
            "confirmation_height": 0,
            "commit_fee": "3818",
            "commit_weight": "600",
            "fee_per_kw": "5274"
        },
        {
            "channel": {
                "remote_node_pub": "02efe789fcf1d791e9dfc9494b81a9aea7aa0c2a8744c66165d16dc47ce6b88b91",
                "channel_point": "5f71bd3ba3d91fa8f67a0128e8b3f2dee81a45b4bb1c19d7781ed05e9b3d2fd8:0",
                "capacity": "5000000",
                "local_balance": "4998239",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1761",
            "commit_weight": "600",
            "fee_per_kw": "2433"
        },
        {
            "channel": {
                "remote_node_pub": "03902356d26efdc0812726c31a1a2e0d721f26063dd252ac89ded8280037e9ece8",
                "channel_point": "dbac2c25a7ce162cb96cf56b4ccb2c74eff849983303135d3d6d56674767356a:1",
                "capacity": "5000000",
                "local_balance": "4998239",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1761",
            "commit_weight": "600",
            "fee_per_kw": "2433"
        },
        {
            "channel": {
                "remote_node_pub": "03952f8756c036669440e06c782c7f21732886ccf04052e0e6e792f8f5a490f6aa",
                "channel_point": "19117302076f4f21bf38307409a83234ef2af2d9ccaf75bd9faf3ca692616351:1",
                "capacity": "5000000",
                "local_balance": "4998486",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1514",
            "commit_weight": "600",
            "fee_per_kw": "2092"
        },
        {
            "channel": {
                "remote_node_pub": "03c492f46d8e0a6256bb9c5c42f2aed24717f70a3f39e0961419dee511688e3110",
                "channel_point": "7b484d0c55b57053b5caec62df2384144fb3b1a1c34dfbddd972202ffee80b02:0",
                "capacity": "5000000",
                "local_balance": "4998486",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "1514",
            "commit_weight": "600",
            "fee_per_kw": "2092"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605",
                "channel_point": "31f55cdd3fd48809dd5c29f24a8976932ef11324b92da021a29646da090f9e0c:0",
                "capacity": "5000000",
                "local_balance": "4998239",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "4998239",
            "commitments": {
                "local_txid": "32de93cc464e2e3d6df9cc5d0b76d6b9bb171244d26b8478003b9a5b28262c28",
                "remote_txid": "081480122c3dcbc451d77cd003811a1f93d576620167a7a27200be2a9509ce97",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "1761",
                "remote_commit_fee_sat": "1761",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}

**Comment by enorrmann** [comment]
> ### Expected behaviour
> After some time I'd expect the opening to be considered as failed. I don't know how to get rid of those channels.

you can try increasing the funding tx fees via
lncli wallet bumpfee --sat_per_byte 10 funding_tx:output_num
see
https://api.lightning.community/?shell#bumpfee

**Comment by wpaulino** [comment]
None of these transactions exist in the chain/mempool, likely due to a low fee at the time of broadcast. If the inputs used in the transactions have already been spent elsewhere, you can use the `lncli abandonchannel` command available in a debug build of `lnd`, which you can obtain by simply running `make`.

**Comment by svewa** [comment]
@enorrmann The bumpfee fails due to "rpc error: code = Unknown desc = the passed output doesn't belong to the wallet"

@wpaulino How would the inputs be spend elsewhere? The wallet is managed by lnd. If lnd used the same inputs for another tx it should know about that and remove the channel by itself. I would have expected that lnd still assumes the tx is valid and thus would not use the same input for another purpose.

Grepping in "listunspent" and "listchaintxns" for the TXIDs (left of the colon in "channel_point") gives no result, so I assume it's save to abandon those channels?

**Comment by wpaulino** [comment]
> If lnd used the same inputs for another tx it should know about that and remove the channel by itself.

This isn't done yet and is being tracked as its own issue (https://github.com/lightningnetwork/lnd/issues/386).

> Grepping in "listunspent" and "listchaintxns" for the TXIDs (left of the colon in "channel_point") gives no result, so I assume it's save to abandon those channels?

Not necessarily. To be 100% sure, you'll want to obtain the raw transaction and check at least one of the inputs is spent. Unfortunately, since the transaction isn't found in `lncli listchaintxns`, you might have to find the raw transaction within your logs at the time of broadcast.

**Comment by svewa** [comment]
My logs don't contain any raw transactions. I just set logging to debug and tried to force-close an inactive channel - no plain TX in logs. 
The risk of abandoning channels which use unspent inputs is, that the TX could be rebroadcasted and I'd not have required info on the channel to reclaim my funds?

**Comment by guggero** [comment]
The risk of abandoning channels is that if the funding TX ever gets confirmed, your node doesn't have the signed commitment transactions anymore to force close the channel. And it doesn't have the information to do a cooperative close either. So basically the funds would be locked in a 2-of-2 multisig.

**Comment by svewa** [comment]
To be able to abandon I just build latest git version. And it seems all issues are resolved (or at least not that bad anymore). Log told me that lnd is "unable to rebroadcast" due to "transaction rejected: output already spent". I issued an abandon, but have a feeling that it was already auto-abandoned. Also all old opening TX which don't conflict seem to have been reissued, can find them in the mempool now. Too little fee, but at least it's clear to me now what's going on. Thanks.

**Comment by wpaulino** [comment]
Can this issue be closed then @svewa?
