### ISSUE TITLE
Frequent lnd crash

### ISSUE THREAD

**Issue by krtk6160** [lightningnetwork/lnd#4609]
### Background

I am running lnd on kubernetes. I have noticed that frequently, lnd restarts with the following log
```
2020-09-12 03:59:04.121 [INF] LTND: Primary chain is set to: bitcoin
2020-09-12 03:59:04.140 [ERR] LTND: Unable to create chain control: unable to connect to bitcoind: -28: Verifying blocks...
2020-09-12 03:59:04.144 [INF] LTND: Shutdown complete
Unable to create chain control: unable to connect to bitcoind: -28: Verifying blocks...
```

Not sure what is wrong here.
### Your environment

* version of `lnd` - 0.11.0 beta
* which operating system (`uname -a` on *Nix) - Linux
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.19.1
* any other relevant environment details - Kubernetes on Google Kubernetes Engine

**Comment by guggero** [comment]
> bitcoind: -28: Verifying blocks...

It looks like your bitcoind node is not ready yet. Maybe it is restarting often as well?

**Comment by krtk6160** [comment]
> It looks like your bitcoind node is not ready yet. Maybe it is restarting often as well?

You're right. I was looking at the number of restarts listed by `kubectl get pods` when trying to find the root cause. Bitcoind seemed to be running fine according to that.

But looking at the logs I can see that right before lnd shuts down, bitcoind has a restart (which is not picked up by kubernetes for some reason).
