### ISSUE TITLE
Panic Crash

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#461]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc31bf5]

goroutine 6184 [running]:
main.(*peer).logWireMessage(0xc420271080, 0x14a3a00, 0xc42090e300, 0x14a3a01)
        /home/ubuntu/projects/lightning/src/github.com/lightningnetwork/lnd/peer.go:930 +0x965
main.(*peer).readNextMessage(0xc420271080, 0x0, 0xc4205ecce8, 0xc4205ece78, 0xc4205ecce8)
        /home/ubuntu/projects/lightning/src/github.com/lightningnetwork/lnd/peer.go:457 +0x172
main.(*peer).readHandler(0xc420271080)
        /home/ubuntu/projects/lightning/src/github.com/lightningnetwork/lnd/peer.go:656 +0x18f
created by main.(*peer).Start
        /home/ubuntu/projects/lightning/src/github.com/lightningnetwork/lnd/peer.go:286 +0x83f

Running 7a3116f8a97223bb8403aedb058bb4a6f0417eca

**Comment by Roasbeef** [comment]
Ah, guessing you were connected to either `eclair` or `c-lightning` as I'm not sure if both of them have properly implemented the data loss protection option. Will fix!
