### ISSUE TITLE
wrong utxo showing in lncli listunspent

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#4612]
If I run lncli listunspent 
I see

```

{
	"utxos": [
		{
			"address_type": 0,
			"address": "bc1qd7qggj0c567hf7ttzpvuhysnujyh3wjgwche35",
			"amount_sat": 1939699,
			"pk_script": "00146f808449f8a6bd74f96b1059cb9213e48978ba48",
			"outpoint": "b058b833ec52be4b9e02e6052be4fbc5c7c4c56363b5bf3e1c83dcb841d99f3a:0",
			"confirmations": 0
		}
	]
}

```

But that outpoint correspont to a tx that has never been broadcast, so it is stuck there forever
I can't spend that because it is showing as "pending" balance
My total balance has not been affected, it seems that I got the same value from another tx.

I tried doing a dropwtxmgr, and rescan the chain, but the issue persists after.

### Your environment

v0.11.0-beta
4.15.0-112-generic #113-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
NEUTRINO

### Steps to reproduce

unknown

**Comment by wpaulino** [comment]
Do you see the transaction responsible for this UTXO in `lncli listchaintxns`?

**Comment by enorrmann** [comment]
> Do you see the transaction responsible for this UTXO in `lncli listchaintxns`?

nope. 
also, after a couple of dropwtxmgrs and restarts, tx is gone from utxos as well

**Comment by wpaulino** [comment]
> tx is gone from utxos as well

So the issue is resolved now?

Do you still have any logs that could indicate where this transaction originated from? A wallet output cannot be shown in `lncli listunspent` without the corresponding transaction being shown in `lncli listchaintxns`.

**Comment by enorrmann** [comment]
> So the issue is resolved now?

yes, will close for now and reopen if it happens again. I have weeks of logs to search, but only in INFO mode
