### ISSUE TITLE
wallet: handle mempool min fee not met error

### ISSUE THREAD

**Issue by svewa** [lightningnetwork/lnd#4616]
I have channels which are inactive for some time, so I tried to clean up:

Trying to force-close:

> [ERR] CNCT: ChannelArbitrator(fb34ceae72982ea7f0d485ad2b52b84b8e5b959d8ee83690aad99b3aae4422e4:0): unable to broadcast close tx: unmatched backend error: -26: mempool min fee not met, 545 < 9728 (code 66)

Okay, I think this i a known problem, closing fees have been negotiated some time ago and are not sufficient. But I wonder how I would retry if the fees would drop. Trying to force-close again results in:

> 2020-09-15 13:44:02.825 [INF] CNCT: Attempting to force close ChannelPoint(fb34ceae72982ea7f0d485ad2b52b84b8e5b959d8ee83690aad99b3aae4422e4:0)
> 2020-09-15 13:44:02.825 [ERR] RPCS: unable to force close transaction: channel is already in the process of being force closed
> 2020-09-15 13:44:02.825 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: channel is already in the process of being force closed
> 

So how would I convince lnd to try to rebroadcast the closing TX?

**Comment by wpaulino** [comment]
The closing transaction will be broadcast on restarts. Also, if any of the channels were using the new anchors protocol, then you could use the `bumpclosefee` command.

**Comment by svewa** [comment]
Also the node won't start again, if the fee is still too low :(

> [ERR] LTND: unable to start server: unmatched backend error: -26: mempool min fee not met, 3818 < 5592 (code 66)
 And in a new run:
> unable to start server: unmatched backend error: -26: min relay fee not met, 545 < 15000000 (code 66)

A full log of starting up lnd is nopasted here:

https://nopaste.xyz/?8d3da7c52797ba55#BH92BkihURmSSGWs8hEitrpYpu44HY8sjUPmq6g8DkTe

So no chance of using "bumpclosefee" I guess.

**Comment by Roasbeef** [comment]
> Also the node won't start again, if the fee is still too low :(

Looks like you're setting a high value manually in your bitcoind's config?

**Comment by Roasbeef** [comment]
> a) not repeatedly trying to broadcast the TX, only and restarts which are not to be expected on normal operation

The wallet assumes the backend source will rebroadcast, and in this case bitcoind does rebroadcast it over time.

**Comment by Roasbeef** [comment]
What network is this on? It's surprising that your wallet tried to use such a low fee.

**Comment by svewa** [comment]
@Roasbeef It's on bitcoin mainnet. No parameters for minrelaytxfee or blockmintxfee were specified before, but mempool was limited to 3MB.
I see how bitcoind is the right place to look for rebroadcasts, but only if bitcoind accepted the TX in the first place.

**Comment by wpaulino** [comment]
> but mempool was limited to 3MB.

This causes the issue to happen more often, as the limit will push lower fee transactions out of your mempool. Could you try removing this limit temporarily and restarting lnd?

**Comment by svewa** [comment]
@wpaulino I changed that as mentioned in https://github.com/lightningnetwork/lnd/issues/4616#issuecomment-693253459 - but still think this is a bug. As my issue is resolved, I'd be fine with closing this issue. Yet I'd still consider it a bug as mentioned above.

**Comment by Roasbeef** [comment]
Agreed, we should ensure that we're able to start up and log (on the appropriate level) if this happens.

**Comment by henhito** [comment]
I have a similar issue

lncli closechannel --force c9ad0b642043dc6ebba79bb5512e8f4357797880dc882feb6d87c961ef655eaf 1
[lncli] rpc error: code = Unknown desc = channel not found


2020-10-17 23:49:32.528 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: channel not found

my public key is 02e8882bc38ab89963cea0718335e7f33baf79a947590f6b9d80b6ffb4da82795d

https://1ml.com/node/02e8882bc38ab89963cea0718335e7f33baf79a947590f6b9d80b6ffb4da82795d/channels

you can see the txid on the channels.

I have restored my node, but did not back up my channel.back file.

**Comment by wpaulino** [comment]
@henhito if you restored your node and haven't restored a channel backup, then there won't be any channels present. If you don't have a channel backup at all and still have funds within the channel, you might be able to use [`chantools`](https://github.com/guggero/chantools#channel-recovery-scenario) by @guggero to recover them.

**Comment by henhito** [comment]
thanks @wpaulino I will give that a go.

**Comment by kingonly** [comment]
@Roasbeef @wpaulino we (Breez) had this issue (unmatched backend error) in production today causing our node to be down for a while.

Consider reopening this issue. IMHO, lnd should not stop not startup should be prevented in case a closing TX can't be broadcasted.  Cc: @yaslama

**Comment by wpaulino** [comment]
@kingonly could you open a new issue and include some more details (logs especially)? What bitcoind version were you running with? What was the bitcoind error?

**Comment by yaslama** [comment]
@wpaulino It seems that restarting bitcoind helped because the mempool memory was almost empty when lnd retried to broadcast the transaction. This helped lnd to start. But this issue still need to be solved and it's not a new one. Perhaps https://github.com/btcsuite/btcwallet/blob/50978fcf79f8100eb62c185606c66367cc03b03e/wallet/wallet.go#L3463 needs also to be modified to handle the "mempool min fee not met" error received from bitcoind.
In any case, please consider reopening this issue, at least in order to increase the visibility of the workaround: increase the bitcoind mempool max memory using the `-maxmempool` parameter and/or restart bitcoind.

**Comment by wpaulino** [comment]
We're aware of the issue and have plans to address it soon due to the current state of the fee market. Another related issue case is https://github.com/lightningnetwork/lnd/issues/4912.

**Comment by Roasbeef** [comment]
Gonna close this in favor of https://github.com/lightningnetwork/lnd/issues/7156
