### ISSUE TITLE
manifest-v0.11.1-beta.rc2.txt.sig is missing

### ISSUE THREAD

**Issue by MykelSIlver** [lightningnetwork/lnd#4619]
### Background

The manifest-v0.11.1-beta.rc2.txt.sig is missing. Therefore I cannot verify the release

### Your environment

* version of `lnd`
v0.11.1-beta.rc2
* which operating system (`uname -a` on *Nix)
Linux 4.19.118-v8+ #1311 SMP PREEMPT Mon Apr 27 14:32:38 BST 2020 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.20.1
* any other relevant environment details

### Steps to reproduce
wget https://github.com/lightningnetwork/lnd/releases/download/v0.11.1-beta.rc2/manifest-v0.11.1-beta.rc2.txt.sig

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
manifest-v0.11.1-beta.rc2.txt.sig should be downloaded

### Actual behaviour
404 Not Found

**Comment by Roasbeef** [comment]
Ooops, should be there now! Will add the OTS files only for the final release though. Thanks for this issue!
