### ISSUE TITLE
On master branch, lnd ran with --no-macaroons,  and ran lncli with --no-macaroons occur error.

### ISSUE THREAD

**Issue by iamgamelover** [lightningnetwork/lnd#4629]
I ran lnd with --no-macaroons ,  and ran lncli --no-macaroons --network=testnet getinfo. 

There is a error:

[lncli] could not load global options: unable to read macaroon path (check the network setting!): open /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon: no such file or directory

My environment

* lnd: master branch, v0.11.99 beta
* OS: CentOS
* chain backend: neutrino

**Comment by ghostufield** [comment]
I get this same error when trying to create a wallet. Lnd doesn't seem to make the macaroons as well as other files and folders when ran for the first time. It only creates
tls.cert
tls.key
logs/bitcoin/mainnet/lnd.log
data/graph/mainnet/channel.db

And that's it. Im running the same version of lnd but in Ubuntu and bitcoind as the backend.

**Comment by guggero** [comment]
For the command to create a wallet you don't need macaroons yet. They are created after a wallet is initialized (or unlocked the next time).

**Comment by ghostufield** [comment]
Hmmm when I run "lncli create" I get the same exact error as you posted...would that be an entirely separate issue?

**Comment by guggero** [comment]
Ah, yes, I see it now. It's the same problem, the macaroon is always attempted to be read even if it's not needed currently.

**Comment by ghostufield** [comment]
Ok. I talked to someone else who had the same problem and suggested I post it as an issue and then I saw your issue and thought it might be the same or similar. But he said his got resolved by updating to the 0.11 beta ?? So I don't know I'm lost

**Comment by ghostufield** [comment]
Just for reference I installed 0.11.0-beta and it fixed the problem

**Comment by iamgamelover** [comment]
Yes, this maybe a bug of master branch. I have checked out to v0.11 branch and everything is OK.
