### ISSUE TITLE
[lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@'

### ISSUE THREAD

**Issue by gades** [lightningnetwork/lnd#4630]
### Background

I can't create channel with 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266@23.237.77.11:9735

### Your environment

* LTND: Version: 0.11.0-beta commit=v0.11.0-beta, build=production, logging=default
* Linux tester 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core version v0.20.0

### Steps to reproduce

`$ lncli connect 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266@23.237.77.11:9735
{

}
$ lncli openchannel 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266@23.237.77.11:9735 500000
[lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@'
`

### Expected behaviour

It should create channel with 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266@23.237.77.11:9735

### Actual behaviour

[lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@'

**Comment by guggero** [comment]
For the `openchannel` command, you only need to specify the public key (`0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266`), not the full connection string.

**Comment by cfromknecht** [comment]
@gades you can also have `openchannel` connect to the target node using the `--connect` flag:
```
  --connect value                          (optional) the host:port of the target node
```

**Comment by gades** [comment]
> @gades you can also have `openchannel` connect to the target node using the `--connect` flag:
> 
> ```
>   --connect value                          (optional) the host:port of the target node
> ```

Thanks, it's working now, but the last version from master doesn't create macaroons  and I did use version form releases
