### ISSUE TITLE
misleading error message for keysend-hold-time

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4633]
### Background

Experimenting with the `keysend-hold-time` feature. The error return when not accepting a hodl keysend is: `FAILURE_REASON_INCORRECT_PAYMENT_DETAILS`

This error doesn't describe the issue accurately. The payment detail was correct, but the payment has not been settled by the receiving node before the timout.

### Your environment

* version of `lnd`: .11
* `bitcoind` backend

**Comment by Roasbeef** [comment]
That's the blanket error returned on the _protocol_. The current logic will just cancel back the HTLC as if it wasn't able to complete the route.

**Comment by nicolasburtey** [comment]
ok. I feel it could be made clearer that the error message is a blanker error/catch all. 
but closing for now.
