### ISSUE TITLE
Health check does not pick up misconfigured bitcoind ZMQ arguments

### ISSUE THREAD

**Issue by bjornoj** [lightningnetwork/lnd#4636]
### Background

I started LND with switched `bitcoind.zmqpubrawtx` and `bitcoind.zmqpubrawblock` ports. I didn't notice for several weeks because I could both send and receive lightning payments. One day I couldn't send payments anymore because `ExpiryTooFar`.
I also had a bunch of these logs in lnd:
```
2020-09-20 20:04:25.475 [INF] DISC: Update announcement for short_chan_id(713051982387740673), is premature: advertises height 648517, only height 647146 is known
```

I ended up in a potentially dangerous situation because LND wasn't notified of new transactions or blocks. Therefore my LND has not been able to sweep force closes between block 647146 and 648517.

### Your environment

* version of `lnd`
v0.9.2
* which operating system (`uname -a` on *Nix)
`Linux #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
`bitcoind v0.19.1`
* any other relevant environment details

### Steps to reproduce

1. Start bitcoind with these flags:
```
 $ bitcoind
-zmqpubrawtx=tcp://0.0.0.0:12397
-zmqpubrawblock=tcp://0.0.0.0:12398
```
2. Start lnd with these flags:
```
 $ lnd
--bitcoind.zmqpubrawtx=tcp://bitcoind:12398
--bitcoind.zmqpubrawblock=tcp://bitcoind:12397
```
Notice that the rawtx and rawblock ports are not equal. So lnd can't actually receive any events from the ZM Queue.

My node was running for a while with this config, leading to lots of logs like:
```
2020-09-20 20:04:25.475 [INF] DISC: Update announcement for short_chan_id(713051982387740673), is premature: advertises height 648517, only height 647146 is known
```

### Expected behaviour
The new health checks in v0.11.1 should not pass, because lnd is misconfigured.

### Actual behaviour
LND starts and chugs along happily (for a while).

**Comment by bjornoj** [comment]
I will happily fix this issue, but it would be nice with some ACKs that the expected behaviour is what you want to happen.

**Comment by Crypt-iQ** [comment]
I agree that the healthchecks shouldn't pass so Concept ACK from me. Expected behavior should be to attempt reconnect and eventually shut down I think?

**Comment by aghamir** [comment]
I faced the same error log in `0.13.1-beta`. My lnd config is:
```
[Application Options]

tlsextraip=xx.xx.xx.xx
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:10010

[Bitcoin]

bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=bitcoind
bitcoin.defaultchanconfs=3

[Bitcoind]
bitcoind.dir=~/data/bitcoin
bitcoind.rpchost=localhost:8030
bitcoind.rpcuser=xxxxxxxx
bitcoind.rpcpass=xxxxxxxxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:38331
bitcoind.zmqpubrawtx=tcp://127.0.0.1:38330

[tor]
tor.active=true
tor.socks=9050
tor.v3=true
tor.streamisolation=true

[wtclient]
wtclient.active=true 
```
and my `bitcoin.conf` is:
```
daemon=1
server=1
mainnet=1
txindex=1
disablewallet=1

zmqpubhashtx=tcp://127.0.0.1:38330
zmqpubhashblock=tcp://127.0.0.1:38331

rpcworkqueue=1100
maxmempool=2000
dbcache=1000
# generated from additional_params
deprecatedrpc=estimatefee

## Tor Settings
debug=tor
onlynet=onion
proxy=127.0.0.1:9050
bind=127.0.0.1
dnsseed=0
dns=0

## Tor v3 Seeds
addnode=kpgvmscirrdqpekbqjsvw5teanhatztpp2gl6eee4zkowvwfxwenqaid.onion
addnode=bnx4povtqynvwnui5oqm5xcxqvat3j7yzgn6mqciuyszqawhuayvyaid.onion
addnode=nqb5q6d4nhp54ziahhm2oxopqwyyulg7nrqwrcmfvwhj7y7xasaeg7ad.onion
addnode=qxkgr5u4rmwme5jticjuuqrecw5vfc5thcqdxvbffwbqgqkdin7s7vid.onion
addnode=wn3ffvfxdnhsgpw4oxhv4bhwhyylzqx72ndtdy4sucueoa7awdmw3nid.onion


[main]
rpcallowip=127.0.0.1
rpcauth=xxxxx
rpcport=8030
```
After one or two hours after running `lnd`, it shows this log:
```
DISC: Update announcement for short_chan_id(760993987868229633), is premature: advertises height 692120, only height 692089 is known
```
And it needs to be restarted.
