### ISSUE TITLE
Ability to spend unconfirmed utxos with sendcoins RPC

### ISSUE THREAD

**Issue by mrfelton** [lightningnetwork/lnd#4644]
### Background

Add ability to spend unconfirmed outputs when making onchain transactions.

When opening channels it is possible to spend unconfirmed outputs by passing `spend_unconfirmed` as part of the openChannel call.

Suggest adding the same `spend_unconfirmed` flag for `sendcoins` RPC.

### Your environment

* version of `lnd`: 0.11
* which operating system (`uname -a` on *Nix) : mac
* version of `btcd`, `bitcoind`, or other backend: bitcoind

### Steps to reproduce

Deposit coins onto a fresh node, then try to make a couple of onchain payments. They can fail when change outputs are unconfirmed.

### Expected behaviour

I should be able to spend the coins from my wallet.

### Actual behaviour

I can't spend them because some are unconfirmed.

**Comment by Roasbeef** [comment]
In this case, would output fanning or batching be a replacement to spending unconfirmed change? Or perhaps RBF of a base transaction to update the set of outputs?

**Comment by mrfelton** [comment]
I don't think that would work for our current use case - we need to be able to do instant one-time sends using unconfirmed outputs.
