### ISSUE TITLE
DNS seed bootstrapper doesn't seem to support IPV6

### ISSUE THREAD

**Issue by simonhorlick** [lightningnetwork/lnd#465]
I see the following error message repeated in the logs:

`DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]: address 2404:160:0:f:0:1:2d3f:5783:9735: too many colons in address`

**Comment by Roasbeef** [comment]
Related to #431
