### ISSUE TITLE
lncli unlock does not unlock wallet

### ISSUE THREAD

**Issue by xwvvvvwx** [lightningnetwork/lnd#4654]
### Background

Whenever I try to unlock my wallet, it appears to succeed, but afterwards `getinfo` shows that the wallet is still locked:

```
$ lncli --lnddir /bitcoin/lnd/ --rpcserver 10.250.0.2:9999 unlock

Input wallet password:

lnd successfully unlocked!

$ lncli --lnddir /bitcoin/lnd/ --rpcserver 10.250.0.2:9999 getinfo

[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
```

I'm not sure what I'm doing wrong here, I have previously run `lncli --lnddir /bitcoin/lnd/ --rpcserver 10.250.0.2:9999 create` and the procedure appeard to finish succesfully.... :thinking: 

My `bitcoind` conf looks like this (rpc auth section ommited)

```
rpcauth=lnd:<HASH>
dns=0
bind=10.250.0.2
rpcbind=127.0.0.1:8888
proxy=127.0.0.1:9050
listen=1
server=1
rest=1
txindex=1
onlynet=onion
zmqpubrawblock=127.0.0.1:42069
zmqpubrawtx=127.0.0.1:42096
```
and I'm running `lnd` like this:

```
lnd \
  --tor.active \
  --tor.socks=127.0.0.1:9050 \
  --tor.streamisolation \
  --autopilot.active \
  --bitcoind.dir="/bitcoin/bitcoind" \
  --bitcoind.rpcuser=lnd \
  --bitcoind.rpcpass=<PASSWORD> \
  --bitcoind.zmqpubrawblock=127.0.0.1:42069 \
  --bitcoind.zmqpubrawtx=127.0.0.1:42096 \
  --bitcoin.active \
  --bitcoin.node=bitcoind \
  --bitcoin.mainnet \
  --lnddir="/bitcoin/lnd" \
  --tlsextraip=10.250.0.2 \
  --tlsextraip=10.0.0.8 \
  --rpclisten=10.250.0.2:9999
```

### Your environment

* version of `lnd`: 0.11.0
* which operating system (`uname -a` on *Nix): `Linux bitcoin 5.4.66 #1-NixOS SMP Thu Sep 17 11:47:56 UTC 2020 x86_64 GNU/Li
nux`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v0.20.1.0-g7ff64311bee570874c4f0dfa18f518552188df08`
* any other relevant environment details: running inside a systemd-nspawn container

**Comment by guggero** [comment]
Can you please take a look at the logs? Maybe `lnd` stops for some reason and is then restarted by `systemd` in the unlocked state.

**Comment by xwvvvvwx** [comment]
Oups, I hadn't looked back far enough in the logs. This was exactly the issue. For future reference there were two issues with the above config:

1. `bitcoind` requires that the `zmq` address config is prefixed with `tcp://`
2. `lnd` expects the `bitcoind` rpc port to be `8332`

Thanks for the help!!!! :pray: :sparkles:
