### ISSUE TITLE
File manifest-v0.11.1-beta.txt.sig.ots is missing in the release

### ISSUE THREAD

**Issue by MykelSIlver** [lightningnetwork/lnd#4663]
### Background
File manifest-v0.11.1-beta.txt.sig.ots is missing in the release

### Your environment

* version of `lnd`
lnd v0.11.1-beta
* which operating system (`uname -a` on *Nix)
Linux 4.19.118-v8+ #1311 SMP PREEMPT Mon Apr 27 14:32:38 BST 2020 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core version v0.20.1

### Steps to reproduce
```
wget https://github.com/lightningnetwork/lnd/releases/download/v0.11.1-beta/roasbeef-manifest-v0.11.1-beta.txt.sig
wget https://github.com/lightningnetwork/lnd/releases/download/v0.11.1-beta/manifest-v0.11.1-beta.txt.sig.ots
ERROR 404: Not Found.
ots verify manifest-v0.11.1-beta.txt.sig.ots -f roasbeef-manifest-v0.11.1-beta.txt.sig
ots verify: error: argument TIMESTAMP: can't open 'manifest-v0.11.1-beta.txt.sig.ots': [Errno 2] No such file or directory: 'manifest-v0.11.1-beta.txt.sig.ots'
```

### Expected behaviour
That the file `manifest-v0.11.1-beta.txt.sig.ots` can be downloaded and used to verify the release with the `ots verify` command

### Actual behaviour
```
ERROR 404: Not Found.
ots verify: error: argument TIMESTAMP: can't open 'manifest-v0.11.1-beta.txt.sig.ots': [Errno 2] No such file or directory: 'manifest-v0.11.1-beta.txt.sig.ots'

```

**Comment by Roasbeef** [comment]
Should be there now! Was stuck there in the draft state.
