### ISSUE TITLE
FundPsbt includes a non-empty scriptSig in the unsigned transaction value

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4670]
### Background

A PSBT produced by the `WalletRpc` method `FundRpc` erroneously includes a scriptSig value

According to [BIP 174's specification](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#specification) of the unsigned transaction:

> The scriptSigs and witnesses for each input must be empty. The transaction must be in the old serialization format (without witnesses).

### Your environment

* LND commit `f8e3b41d1004aadc3dc506b2b13aaac4baec3b5a`

### Steps to reproduce

1. Create a single nested SegWit UTXO on an LND node
2. Call `FundPsbt` with no inputs to allow LND to select the funding inputs itself
3. Attempt to decode the resulting PSBT `funded_psbt`

### Expected Behavior

1. The funding step should not include any signature data
2. The PSBT should be a valid BIP 174 PSBT

### Actual Behavior

A scriptSig in the transaction encoded in the `PSBT_GLOBAL_UNSIGNED_TX` field is present. This causes decoding of the PSBT to fail, for example a call to `decodepsbt` in Bitcoin Core will fail.

**Comment by guggero** [comment]
Thanks for testing! Fix is on its way.
