### ISSUE TITLE
Fatal error: out of memory

### ISSUE THREAD

**Issue by Relaxo143** [lightningnetwork/lnd#4677]
So when I try to unlock the wallet I get `runtime: out of memory: cannot allocate 268435456-byte block (280723456 in use)
fatal error: out of memory`
Which is strange since I've been using LND since 2018 and this is the first time I'm seeing it. I have 16 gigs of RAM with half of it available so I don't think it's a memory problem. The OS is Win10 and LND is v0.11.0-beta.

**Comment by Roasbeef** [comment]
Do you have any settings to restrict the memory usage of `lnd`? Also guessing that this _isn't_ a 32-bit system right? Does the issue persist? And also what else do you have running on this machine other than lnd? Have you ever compacted the database?

**Comment by Relaxo143** [comment]
No to the first question. It's a 64bit system. I have Bitcoin Core, cgminer, VirtualBox, Steam, stuff like that. I haven't compacted the db (dont know how even) and yes so far the issue persists.

**Comment by guggero** [comment]
Do you have a stack trace or log from just before it crashes?

**Comment by Relaxo143** [comment]
> Do you have a stack trace or log from just before it crashes?

`runtime: out of memory: cannot allocate 268435456-byte block (284884992 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x10ac804, 0xd)
        runtime/panic.go:1116 +0x64
runtime.largeAlloc(0x10000000, 0x12950101, 0x1)
        runtime/malloc.go:1154 +0x103
runtime.mallocgc.func1()
        runtime/malloc.go:1047 +0x39
runtime.systemstack(0x0)
        runtime/asm_386.s:395 +0x53
runtime.mstart()
        runtime/proc.go:1041

goroutine 52 [running]:
runtime.systemstack_switch()
        runtime/asm_386.s:356 fp=0x128d9880 sp=0x128d987c pc=0x45dda0
runtime.mallocgc(0x10000000, 0xf018c0, 0x12934e01, 0x128fe000)
        runtime/malloc.go:1046 +0x686 fp=0x128d98d4 sp=0x128d9880 pc=0x40b206
runtime.makeslice(0xf018c0, 0x4000000, 0x4000000, 0x128fe000)
        runtime/slice.go:49 +0x4f fp=0x128d98e8 sp=0x128d98d4 pc=0x44763f
golang.org/x/crypto/scrypt.Key(0x128a6080, 0x17, 0x20, 0x12d7e054, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
        golang.org/x/crypto@v0.0.0-20200709230013-948cd5f35899/scrypt/scrypt.go:205 +0x111 fp=0x128d9948 sp=0x128d98e8 pc=0x7290f1
github.com/btcsuite/btcwallet/snacl.(*SecretKey).deriveKey(0x12d7e050, 0x128d9cc4, 0x12934fe0, 0x12934fe8)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/snacl/snacl.go:114 +0x6d fp=0x128d9994 sp=0x128d9948 pc=0x7297bd
github.com/btcsuite/btcwallet/snacl.(*SecretKey).DeriveKey(0x12d7e050, 0x128d9cc4, 0x12935080, 0x12935088)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/snacl/snacl.go:201 +0x2d fp=0x128d99e4 sp=0x128d9994 pc=0x729c0d
github.com/btcsuite/btcwallet/waddrmgr.(*Manager).Unlock(0x12ea62c0, 0x33289718, 0x1297a480, 0x128a6080, 0x17, 0x20, 0x0, 0x0)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/waddrmgr/manager.go:1134 +0x2a6 fp=0x128d9cb8 sp=0x128d99e4 pc=0x73a886
github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker.func1(0x13e1b80, 0x1293eff0, 0x1293eff0, 0x0)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:1241 +0x8a fp=0x128d9ce4 sp=0x128d9cb8 pc=0x8c4fca
github.com/btcsuite/btcwallet/walletdb.View(0x13e9fa0, 0x12e06000, 0x128d9dfc, 0x0, 0x0)
        github.com/btcsuite/btcwallet/walletdb@v1.3.3/interface.go:236 +0x97 fp=0x128d9d1c sp=0x128d9ce4 pc=0x706e27
github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker(0x1297e270)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:1239 +0x64d fp=0x128d9fe8 sp=0x128d9d1c pc=0x8bc72d
runtime.goexit()
        runtime/asm_386.s:1337 +0x1 fp=0x128d9fec sp=0x128d9fe8 pc=0x45f6b1
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:158 +0xd0

goroutine 1 [chan receive]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).Unlock(...)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:1342
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).Start(0x12cc4060, 0x1, 0x1)
        github.com/lightningnetwork/lnd/lnwallet/btcwallet/btcwallet.go:164 +0xbf
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup(0x1282fa40, 0x1282fa40, 0x129d25c0)
        github.com/lightningnetwork/lnd/lnwallet/wallet.go:352 +0x4e
github.com/lightningnetwork/lnd.newChainControlFromConfig(0x1295e900, 0x128a4640, 0x128a4640, 0x128a6080, 0x17, 0x20, 0x128a6080, 0x17, 0x20, 0x0, ...)
        github.com/lightningnetwork/lnd/chainregistry.go:542 +0xc79
github.com/lightningnetwork/lnd.Main(0x1295e900, 0x0, 0x0, 0x12902140, 0x0, 0x0)
        github.com/lightningnetwork/lnd/lnd.go:438 +0x92c
main.main()
        github.com/lightningnetwork/lnd/cmd/lnd/main.go:26 +0xb6

goroutine 7 [select]:
io.(*pipe).Read(0x12867940, 0x12a09000, 0x1000, 0x1000, 0x4c2458, 0x128689a0, 0xffffff00)
        io/pipe.go:57 +0xb4
io.(*PipeReader).Read(0x12e154b0, 0x12a09000, 0x1000, 0x1000, 0x1, 0x1, 0x0)
        io/pipe.go:134 +0x3b
bufio.(*Reader).fill(0x12899f84)
        bufio/bufio.go:100 +0xeb
bufio.(*Reader).ReadSlice(0x12899f84, 0x1b6e00a, 0x1, 0x1, 0x1, 0x0, 0x0)
        bufio/bufio.go:359 +0x32
bufio.(*Reader).ReadLine(0x12899f84, 0x1b6e0dd, 0x1, 0x1, 0x1, 0x0, 0x0)
        bufio/bufio.go:388 +0x2a
github.com/jrick/logrotate/rotator.(*Rotator).Run(0x1283e990, 0x13dd7a0, 0x12e154b0, 0x12833570, 0x0)
        github.com/jrick/logrotate@v1.0.0/rotator/rotator.go:100 +0x8d
github.com/lightningnetwork/lnd/build.(*RotatingLogWriter).InitLogRotator.func1(0x12cbb040, 0x12e154b0)
        github.com/lightningnetwork/lnd/build/logrotator.go:80 +0x3a
created by github.com/lightningnetwork/lnd/build.(*RotatingLogWriter).InitLogRotator
        github.com/lightningnetwork/lnd/build/logrotator.go:79 +0x27b

goroutine 14 [syscall]:
os/signal.signal_recv(0x45f6b6)
        runtime/sigqueue.go:147 +0x12f
os/signal.loop()
        os/signal/signal_unix.go:23 +0x1a
created by os/signal.Notify.func1
        os/signal/signal.go:127 +0x33

goroutine 15 [select]:
github.com/lightningnetwork/lnd/signal.mainInterruptHandler()
        github.com/lightningnetwork/lnd/signal/signal.go:71 +0xd1
created by github.com/lightningnetwork/lnd/signal.Intercept
        github.com/lightningnetwork/lnd/signal/signal.go:39 +0xb8

goroutine 51 [select]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).txCreator(0x1297e270)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:1159 +0xc2
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/wallet/wallet.go:157 +0xb2

goroutine 132 [select]:
github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0x12948200)
        github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:768 +0x96
created by github.com/btcsuite/btcd/rpcclient.(*Client).start
        github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:1066 +0xe5

goroutine 54 [runnable, locked to thread]:
syscall.Syscall9(0x747cddb0, 0x7, 0x358, 0x12938b40, 0x1, 0x12938b34, 0x12938b78, 0x12938b14, 0x0, 0x0, ...)
        runtime/syscall_windows.go:214 +0xbb
syscall.WSARecv(0x358, 0x12938b40, 0x1, 0x12938b34, 0x12938b78, 0x12938b14, 0x0, 0x0, 0x0)
        syscall/zsyscall_windows.go:1565 +0xab
internal/poll.(*FD).Read.func1(0x12938b14, 0x72, 0x12938b00)
        internal/poll/fd_windows.go:528 +0x50
internal/poll.(*ioSrv).ExecIO(0x1c67dc8, 0x12938b14, 0x1231b94, 0x0, 0x0, 0x0)
        internal/poll/fd_windows.go:206 +0x98
internal/poll.(*FD).Read(0x12938b00, 0x12b20028, 0x5, 0x5, 0x0, 0x0, 0x0)
        internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x12938b00, 0x12b20028, 0x5, 0x5, 0x43d80038, 0xfff, 0x1)
        net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x129ee0e0, 0x12b20028, 0x5, 0x5, 0x0, 0x0, 0x0)
        net/net.go:184 +0x67
io.ReadAtLeast(0x43d80038, 0x129ee0e0, 0x12b20028, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
        io/io.go:310 +0x74
io.ReadFull(...)
        io/io.go:329
github.com/lightninglabs/gozmq.(*Conn).readFrame(0x12cc4270, 0x12b20028, 0x5, 0x5, 0x1, 0x2, 0x0, 0x0, 0x17, 0x1, ...)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:330 +0x30a
github.com/lightninglabs/gozmq.(*Conn).readMessage(0x12cc4270, 0x1285df40, 0x3, 0x3, 0x12b22008, 0x127ade70, 0x0, 0x12b22000, 0x12866140)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:371 +0x8d
github.com/lightninglabs/gozmq.(*Conn).Receive(0x12cc4270, 0x1285df40, 0x3, 0x3, 0x2, 0x0, 0x0, 0x0, 0x0)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:458 +0x3d
github.com/btcsuite/btcwallet/chain.(*BitcoindConn).txEventHandler(0x1281ae40)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/chain/bitcoind_conn.go:319 +0x211
created by github.com/btcsuite/btcwallet/chain.(*BitcoindConn).Start
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/chain/bitcoind_conn.go:154 +0x165

goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0x33280cf8, 0x72, 0x13df0e0)
        runtime/netpoll.go:203 +0x4b
internal/poll.(*pollDesc).wait(0x12938a9c, 0x72, 0x1b6e300, 0x0, 0x0)
        internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*ioSrv).ExecIO(0x1c67dc8, 0x129389b4, 0x1231b94, 0x0, 0x435b73, 0x85fcb8)
        internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x129389a0, 0x12830a6c, 0x1, 0x1, 0x0, 0x0, 0x0)
        internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x129389a0, 0x12830a6c, 0x1, 0x1, 0x43d80038, 0xfff, 0x1)
        net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x129ee090, 0x12830a6c, 0x1, 0x1, 0x0, 0x0, 0x0)
        net/net.go:184 +0x67
io.ReadAtLeast(0x43d80038, 0x129ee090, 0x12830a6c, 0x1, 0x1, 0x1, 0x1, 0x12c92a80, 0x47e90038)
        io/io.go:310 +0x74
io.ReadFull(...)
        io/io.go:329
github.com/lightninglabs/gozmq.(*Conn).readFrame(0x12cc40f0, 0x12830a60, 0x8, 0x8, 0x1, 0x0, 0x0, 0x0, 0x0, 0x47e90038, ...)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:284 +0xac
github.com/lightninglabs/gozmq.(*Conn).readMessage(0x12cc40f0, 0x1292df40, 0x3, 0x3, 0x13450000, 0x12cbb028, 0x127adf60, 0x12d001e0, 0x12d001e0)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:371 +0x8d
github.com/lightninglabs/gozmq.(*Conn).Receive(0x12cc40f0, 0x1292df40, 0x3, 0x3, 0x45e8d000, 0x0, 0x0, 0x2, 0x1)
        github.com/lightninglabs/gozmq@v0.0.0-20191113021534-d20a764486bf/zmq.go:458 +0x3d
github.com/btcsuite/btcwallet/chain.(*BitcoindConn).blockEventHandler(0x1281ae40)
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/chain/bitcoind_conn.go:217 +0x211
created by github.com/btcsuite/btcwallet/chain.(*BitcoindConn).Start
        github.com/btcsuite/btcwallet@v0.11.1-0.20200814001439-1d31f4ea6fc5/chain/bitcoind_conn.go:153 +0x147

goroutine 162 [select]:
github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0x12948180)
        github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:768 +0x96
created by github.com/btcsuite/btcd/rpcclient.(*Client).start
        github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:1066 +0xe5`

**Comment by guggero** [comment]
Thank you, that should be helpful.
A few more questions to narrow this down: It looks like you're using the `386` (32bit) build. But judging from the amount of RAM you have, you are running on a 64bit system. Does the same happen with the `amd64` build?
And am I correct in the assumption that you are running one of the official release binaries of 0.11.0 and not a manually compiled one?

**Comment by Relaxo143** [comment]
> Thank you, that should be helpful.
> A few more questions to narrow this down: It looks like you're using the `386` (32bit) build. But you said you are running on a 64bit system. Does the same happen with the `amd64` build?
> And am I correct in the assumption that you are running one of the official release binaries of 0.11.0 and not a manually compiled one?

Huh, I could have sworn I was running the amd64 build. I just switched to that one and it's working. Still I don't see why it would throw that error on the 32-bit one though. And yes, those are the binaires from github. I haaven't compiled anything.

**Comment by guggero** [comment]
I'm not too familiar with how Windows handles RAM. But it could be that because 32bit processes only have access to the 4 GB of RAM (or even less on Windows) that golang just couldn't allocate more. But that's just speculation at this point. Not sure if you feel more investigation is justified at this point?

**Comment by Relaxo143** [comment]
Well 64bit works on my end so I don't need any help, but if you feel like it's important to understand why that happens for the project itself I'd be happy to cooperate. 32bit used to work for months before one day it showed this and now only 64 does the trick.

**Comment by guggero** [comment]
It's certainly strange that it just happened one day. Are you sure that you cannot correlate it with an update of the `lnd` version or the installation of another software that might now consume the "lower 4GB" portion of your RAM?

**Comment by guggero** [comment]
Just for more detail, the line causing the error is https://github.com/golang/crypto/blob/master/scrypt/scrypt.go#L205.
We allocate `32*16384*8*4=16777216` bytes (16MiB) here (see values for N and r here: https://github.com/btcsuite/btcwallet/blob/master/snacl/snacl.go#L38, `uint32` is 32 bits = 4 bytes per array entry). Not sure why exactly this leads to `32*16384*8*64=268435456` bytes (256MiB) to be allocated as shown in the error message.

According to [this comment](https://github.com/golang/go/issues/13992#issuecomment-175369397), go does have difficulties allocating that much memory on 32bit systems.
Still would be interesting to know why this only appears now. Could be a regression in the latest go versions we use to build the release binaries?

**Comment by Relaxo143** [comment]
> It's certainly strange that it just happened one day. Are you sure that you cannot correlate it with an update of the `lnd` version or the installation of another software that might now consume the "lower 4GB" portion of your RAM?

Until recently LND had been starting automatically with windows. A few days ago I disabled that and now I start it manually, sometimes long after the system has booted. Maybe that's the reason why it can't allocate memory? I will test it out tonight. But then again I've restarted LND before and if that was the problem it would have spit the same error.

**Comment by Crypt-iQ** [comment]
> Just for more detail, the line causing the error is https://github.com/golang/crypto/blob/master/scrypt/scrypt.go#L205.
> We allocate `32*16384*8*4=16777216` bytes (16MiB) here (see values for N and r here: https://github.com/btcsuite/btcwallet/blob/master/snacl/snacl.go#L38, `uint32` is 32 bits = 4 bytes per array entry). Not sure why exactly this leads to `32*16384*8*64=268435456` bytes (256MiB) to be allocated as shown in the error message.
> 
> According to [this comment](https://github.com/golang/go/issues/13992#issuecomment-175369397), go does have difficulties allocating that much memory on 32bit systems.
> Still would be interesting to know why this only appears now. Could be a regression in the latest go versions we use to build the release binaries?

When running pprof the scrypt calls regularly allocate about 256MB+ on startup.
