### ISSUE TITLE
Feature Request: Can the xPub of the on-chain wallet be retrieved with an API?

### ISSUE THREAD

**Issue by saubyk** [lightningnetwork/lnd#4678]
Is it possible to retrieve the xPub of the on-chain wallet?

- This can help simplify fund management on implementations like BTCPayserver, where currently the Lightning implementations run as a separate hot wallet from the main one.
- Enable other privacy improvements which BTCPayserver is interested in experimenting with (cc: @Kukks)

**Comment by gradientskier** [comment]
This would be a very useful feature.

In the meantime, I built this tool to extract the xpub from an internal lnd node in a btcpayserver-docker deployment.

https://github.com/gradientskier/btcpayserver-docker/blob/f-lnd-derivation-scheme/Tools/python/get_internal_lnd_derivation_scheme.py

You can call the python script using this bash script that also installs the necessary tools.

https://github.com/gradientskier/btcpayserver-docker/blob/f-lnd-derivation-scheme/Tools/get_internal_lnd_derivation_scheme.sh

**Comment by Roasbeef** [comment]
Implemented as of https://github.com/lightningnetwork/lnd/pull/5047
