### ISSUE TITLE
no auth on private addresses is not working

### ISSUE THREAD

**Issue by zoedberg** [lightningnetwork/lnd#4684]
### Background

It seems that the solution of #4473 is not working. 

### My environment

* version of `lnd`: `v0.11.1-beta`
* operating system: docker image from `golang:1.13-buster`
* backend: `bitcoind` `0.20.0`

### Steps to reproduce

Launch lnd `v0.11.1-beta` with the `--no-macaroons` flag and `--rpclisten=192.168.144.4:10009`.

### Expected behaviour

I expect to be able to launch lnd exposing the RPC interface on a private IP.

### Actual behaviour

I receive this error log:
`Detected RPC server listening on publicly reachable interface 192.168.144.4:10009 with authentication disabled! Refusing to start with --no-macaroons specified.`

**Comment by guggero** [comment]
That PR wasn't included in `v0.11.1-beta` (see [release notes](https://github.com/lightningnetwork/lnd/releases/tag/v0.11.1-beta)).
It will only be available in the upcoming `v0.12.0-beta`.

**Comment by zoedberg** [comment]
Oh sorry, missed that
