### ISSUE TITLE
Feature Request: Show forwarding info in ListChannels

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#4687]
This is a feature request related to the prevention of channel jamming. If a user is victim of a channel jamming attack, a call to `ListChannels` will show 483 pending outgoing htlcs on the jammed channel. What isn't shown is through which peers these malicious htlcs came in, making it harder to decide on an appropriate action.

The required information can be reconstructed by matching payment hashes to pending incoming htlcs on other channels, but with hashes there isn't a 1:1 relation. 

The forwarding log only stores settled htlcs, so nothing will be visible there for jammed channels.

The proposal is to extend the `ListChannels` output with information about the incoming part of forwarding circuits:

```
"pending_htlcs": [
        {
                "htlc_id": 9837,      // NEW
                "incoming": false,
                "amount": "5000",
                "hash_lock": "b5ff9903cea8e4d8f4d9f03d2542922fde04d244b7c6dcea18dd11002648c80b",
                "expiration_height": 36184,
                "incoming_chan_id": 45873894935894,   // NEW
                "incoming_htlc_id": 4483,             // NEW
        }
],
```

Implementation should be straight-forward by adding circuit map lookup calls.

I can provide a PR, but wanted to propose the idea first as an issue. This should allow for interesting [flow visualizations](https://twitter.com/joostjgr/status/1315567781497237505).

**Comment by Roasbeef** [comment]
That flow stuff looks really cool! Yeh I think this is an easy win to surface more information that higher level tools can utilize.

**Comment by joostjager** [comment]
Great, the PR is linked. I opted to always expose the other half to the circuit, not just for outgoing htlcs.
