### ISSUE TITLE
lnd crashing soon after start up

### ISSUE THREAD

**Issue by anaoum** [lightningnetwork/lnd#469]
After unlocking the wallet, I receive the following segmentation fault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc02ec6]

goroutine 411 [running]:
main.(*peer).logWireMessage(0xc420730000, 0x14dc920, 0xc4208826c0, 0x14dc901)
        /home/anaoum/gocode/src/github.com/lightningnetwork/lnd/peer.go:930 +0x8d6
main.(*peer).readNextMessage(0xc420730000, 0x0, 0xc4205a0ce8, 0xc4205a0e78, 0xc4205a0ce8)
        /home/anaoum/gocode/src/github.com/lightningnetwork/lnd/peer.go:457 +0x167
main.(*peer).readHandler(0xc420730000)
        /home/anaoum/gocode/src/github.com/lightningnetwork/lnd/peer.go:656 +0x1b9
created by main.(*peer).Start
        /home/anaoum/gocode/src/github.com/lightningnetwork/lnd/peer.go:286 +0x847
```

I have uploaded the trace logging if this helps anyone identify the problem: https://gist.github.com/anaoum/c1f9594024d4d52745b8e9f28e17d3eb

This is a serious problem as it is completely preventing access to funds in my wallet.

**Comment by Roasbeef** [comment]
Which commit are you running on? Does your local branch include: https://github.com/lightningnetwork/lnd/commit/ce6dee6ee4c3d4b161db65058c8afa4f541bae1f?

**Comment by anaoum** [comment]
Sorry, I should have mentioned I am on 7a3116f8a97223bb8403aedb058bb4a6f0417eca, which does not include ce6dee6ee4c3d4b161db65058c8afa4f541bae1f.
