### ISSUE TITLE
lncli feereport fails with error "no policy for outgoing channel" from a previously cooperatively closed channel, and open channels

### ISSUE THREAD

**Issue by bretton** [lightningnetwork/lnd#4690]
### Background

I'm having trouble with channels being closed, and then I get an error with `lncli feereport` as follows:
```
@lnd:~$ lncli feereport
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel REDACTED
```

and the log has
```
[ERR] RPCS: [/lnrpc.Lightning/FeeReport]: no policy for outgoing channel REDACTED
```

if I examine the channel:
```
$ lncli getchaninfo REDACTED
{
    "channel_id": "REDACTED",
    "chan_point": "0000000000000000000000000000000000000000000000000000000000000000:0",
    "last_update": 0,
    "node1_pub": "REDACTED",
    "node2_pub": "REDACTED",
    "capacity": "0",
    "node1_policy": null,
    "node2_policy": null
}
```

This happened over 2 nodes, one testnet, one mainnet. In both instances the chan_point is all zeros

However, one instance has a single nodeX_policy as null, while the other instance above, both are null.

If I examine the output of `lncli closechannels` and find the node pubkey it's a cooperative close in both instances, e.g.
```
{
    "channel_point": "REDACTED:0",
    "chan_id": "REDACTED",
    "chain_hash": "REDACTED",
    "closing_tx_hash": "REDACTED",
    "remote_pubkey": "REDACTED",
    "capacity": "20000",
    "close_height": 1637586,
    "settled_balance": "0",
    "time_locked_balance": "0",
    "close_type": "COOPERATIVE_CLOSE",
    "open_initiator": "INITIATOR_REMOTE",
    "close_initiator": "INITIATOR_UNKNOWN",
    "resolutions": [
    ]
},
```

I'm fully synced:
```
"synced_to_chain": true,
"synced_to_graph": true,
```

### Your environment

* lnd version 0.11.0-beta commit=v0.11.0-beta
* Ubuntu 16.04, Linux lnd 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* testnet instance is backed with `btcd version 0.20.1-beta`
* mainnet instance is backed with `Bitcoin Core RPC client version v0.18.0.0-2472733a24a9364e4c6233ccd04166a26a68cc65`
* these are long-running nodes, which have gone through upgrades from the earliest public LND releases

### Steps to reproduce

An unknown something happens with a closed channel. 

Run `lncli feereport` and get an error

### Expected behaviour

I should see output with a list of fees.

### Actual behaviour

I get an error
```
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel REDACTED
```

**Comment by bretton** [comment]
The issue is happening on another node now, only this time it's an active channel. 
```
[ERR] RPCS: [/lnrpc.Lightning/FeeReport]: no policy for outgoing channel REDACTED
```

`lncli getchaninfo` gives a null result for node1_policy, which is my node in this instance.

Is there any way I can manually set the missing value so the error goes away? 
How can I check it's not something I'm doing wrong. I run with default fee options, and never adjust those settings on the fly.

**Comment by bretton** [comment]
Found earlier issues, going back a year. It's strange it's popped up on 3 different nodes of mine in a short time period.

The suggestion seems to be to wipe the node and start over, lose of network reputation scoring. Else patch code on every update. Neither option is attractive. Will try abandonchannel options. Also the open channel with the error got closed now, but the error remains my side. 

https://github.com/lightningnetwork/lnd/issues/2911

https://github.com/lightningnetwork/lnd/issues/3477

https://github.com/rootzoll/raspiblitz/issues/1107

**Comment by githorray** [comment]
This has just started happening on my node as well. A channel closed from mid 2019 is suddenly back in the graph. "no policy for outgoing channel" errors now.

**Comment by githorray** [comment]
> Things that helped finding the fundingtx for `lncli abandonchannel` purposes was logs going back that many years. I'm not sure if there's another way?

1ml shows the funding transaction (channel point) from a channel id.

**Comment by githorray** [comment]
I tried using `lncli abandonchannel` as well on the previously closed channel. No error returned, but no change in behavior. Still an error running `lncli feereport` with the same channel id.

**Comment by bretton** [comment]
if I try update the channel policy for the problem channel, I get the error
```
[lncli] rpc error: code = Unknown desc = channel from self node has no policy
```
however it's a closed channel so retroactively adjusting policy probably not possible?

**Comment by githorray** [comment]
Maybe a strategic `continue` is in order. ☺️

**Comment by githorray** [comment]
This is the patch I am using to get back up and running in the meantime if anyone is stuck with this.

```
diff --git a/routing/router.go b/routing/router.go
index af1e8d75..396fbdd2 100644
--- a/routing/router.go
+++ b/routing/router.go
@@ -2255,7 +2255,7 @@ func (r *ChannelRouter) ForAllOutgoingChannels(cb func(*channeldb.ChannelEdgeInf
                e, _ *channeldb.ChannelEdgePolicy) error {

                if e == nil {
-                       return fmt.Errorf("channel from self node has no policy")
+                       return nil
                }

                return cb(c, e)
diff --git a/rpcserver.go b/rpcserver.go
index 8d39547f..4d74ca11 100644
--- a/rpcserver.go
+++ b/rpcserver.go
@@ -5756,8 +5756,7 @@ func (r *rpcServer) FeeReport(ctx context.Context,

                // Self node should always have policies for its channels.
                if edgePolicy == nil {
-                       return fmt.Errorf("no policy for outgoing channel %v ",
-                               chanInfo.ChannelID)
+                       return nil
                }

                // We'll compute the effective fee rate by converting from a
```

**Comment by halseth** [comment]
So you are saying this channel is closed? Or is this an old channel that was working fine before, and this suddenly started happening?

**Comment by bretton** [comment]
> So you are saying this channel is closed? 

the channel was in closed channels. I'm not sure why it closed. the error started appearing for some reason. happened on multiple nodes.

**Comment by halseth** [comment]
Interesting. Are you able to see it either in `listchannels` or `closedchannels`? Can you post the info shown there?

**Comment by bretton** [comment]
The output of `lncli closedchannels` is included in the original issue report. (it has a typo). I was asked to redact identifying info.

The channel doesn't appear in `lncli listchannels`.

on my other node it gives similar results to original above:

```
{
    "channel_point": "REDACTED",
    "chan_id": "REDACTED",
    "chain_hash": "REDACTED",
    "closing_tx_hash": "REDACTED",
    "remote_pubkey": "REDACTED",
    "capacity": "3000000",
    "close_height": 580311,
    "settled_balance": "141045",
    "time_locked_balance": "0",
    "close_type": "COOPERATIVE_CLOSE",
    "open_initiator": "INITIATOR_UNKNOWN",
    "close_initiator": "INITIATOR_UNKNOWN",
    "resolutions": [
    ]
}
```

except that `INITIATOR_UNKNOWN` appears twice, instead of only once like the original issue note.

examining the channel:
```
{
    "channel_id": "REDACTED",
    "chan_point": "0000000000000000000000000000000000000000000000000000000000000000:0",
    "last_update": 1560165966,
    "node1_pub": "REDACTED",
    "node2_pub": "REDACTED",
    "capacity": "0",
    "node1_policy": {
        "time_lock_delta": 14,
        "min_htlc": "1000",
        "fee_base_msat": "200",
        "fee_rate_milli_msat": "200",
        "disabled": false,
        "max_htlc_msat": "2940000000",
        "last_update": 1560165966
    },
    "node2_policy": null
}
```

**Comment by halseth** [comment]
I think what could happen is that the channel is being pruned after close, but then you later receive your own announcment from the remote peer. I can see if I can reproduce and put up a fix.

**Comment by bretton** [comment]
thanks @halseth

**Comment by bretton** [comment]
Thanks again, I updated from master, and it's still happening

```
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel REDACTED
```

I have version:
```
"version": "0.12.0-beta commit=v0.12.0-beta-106-gb52e8728",
```

is it active in master for a different version of lnd?

**Comment by halseth** [comment]
@bretton Technically, the change that was merged is supposed to make your node not end up in this state in the first place. 

You can try `abandonchannel` on the channel in question, if that doesn't work we can make a custom patch to fix your DB state :)

**Comment by bretton** [comment]
no luck with abandonchannel:
```
[lncli] rpc error: code = Unknown desc = unable to find closed channel summary
```
This has happened to my 3 remaining nodes now. Will they all need to be setup from scratch with new channels? (not good)

**Comment by halseth** [comment]
Hm, that is very strange. If the channel is listed in `closedchannels` it should have a close summary. Can you try again (making sure you are looking at the correct channel) to call `listchannels` and paste the output, then call `AbandonChannel` with the same channel as is listed there?

**Comment by githorray** [comment]
I tried abandoning the channels as well after the merge. No luck. The command completes without error, but still no go.

**Comment by halseth** [comment]
> I tried abandoning the channels as well after the merge. No luck. The command completes without error, but still no go.

Can you message me on the LND slack (@johanth) or on keybase (@halseth) and I can help you debug it

**Comment by delbonis** [comment]
Also having this issue with a now-closed channel that I'm pretty sure was initially opened with autopilot.  `node1_policy` is null, but `node2_policy` is set.  I have not yet tried using a dev build to abandon it, but given the post that @githorray has I'm not sure if it will work or not.
