### ISSUE TITLE
NodeKey with zeros (like \x00) is not processed correctly.

### ISSUE THREAD

**Issue by infografx** [lightningnetwork/lnd#4695]
### Background

I have got a NodeKey with stub.ListPeers:
031f04c86df5ac2b2c10b75fe54c9d007c119e1fbe4e8e3d244d91f76dd044a458

as you cann see there is a 00 after 9d.

When I try to open a channel to such node, in the log file I see:
[DBG] RPCS: [openchannel] request to NodeKey(031f04c86df5ac2b2c10b75fe54c9d) allocation(us=10000000, them=0)
[ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: invalid pub key length 15

But when I cnage 00 to any other number the server is parsed it correctly. Of course it cannot to complere request but it parses the NodeKey correctly:

[DBG] RPCS: [openchannel] request to NodeKey(031f04c86df5ac2b2c10b75fe54c9d017c119e1fbe4e8e3d244d91f76dd044a458) allocation(us=10000000, them=0)

### Your environment

* version of `lnd`: v0.10.3-beta.rc1
* which operating system Windows 10
* version of `btcd`, `bitcoind`: bitcoind: 0.20
* any other relevant environment details

### Steps to reproduce

You can take any other address, for example:
02d1a817e4ef53b55c27f2314d034b03fb5914f0b6874fab3e5d6799bde477210b
then replace 03 to 00. The error is happens. Only half of the address is recognized.
And you will get:
[ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: invalid pub key length 15

### Expected behaviour

Such bad key:
031f04c86df5ac2b2c10b75fe54c9d007c119e1fbe4e8e3d244d91f76dd044a458
was generated for me by the node.
And it should work, I think :)

### Actual behaviour

[ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: invalid pub key length 15

**Comment by infografx** [comment]
And also, It you put that \x00 somewhere in the NodeKey, the node will recognize only the part before \x00.

**Comment by Roasbeef** [comment]
How are you passing in this value? Via the RPC interface, or on the command line?

**Comment by guggero** [comment]
Judging from your mention of `stub.ListPeers` I assume this is done through RPC with either Python or a similar language. It sounds like the encoding of the pubkey in the language of your choice is probably the problem. 

Are you using `node_pubkey_string` or `node_pubkey` to send the pubkey?

**Comment by infografx** [comment]
Due to the project rquirements I have to use C++ with Visual Studio 15 2017 Win64.
Also I have built a grpc-1.28.0 with:
cmake ..\.. -G "Visual Studio 15 2017 Win64"

And then I call:
lnrpc::OpenChannelRequest openchannel_request;
openchannel_request.set_node_pubkey("\x02\xd1\xa8\x17\xe4\xef\x00\xb5\x5c\x27\xf2\x31\x4d\x03\x4b\x01\xfb\x59\x14\xf0\xb6\x87\x4f\xab\x3e\x5d\x67\x99\xbd\xe4\x77\x21\x0b");

I put literal here for an example.
You can see those \x00 there.

**Comment by infografx** [comment]
I'm going to run some more tests in various languages.

**Comment by infografx** [comment]
Yes, this behavior is confirmed in the simplest client server with Visual Studio 15 2017 Win64

**Comment by infografx** [comment]
Thank you guys. \x00  means end of line.
So I just need to use set_node_pubkey with lenth specified explicitly:
openchannel_request.set_node_pubkey("\x02\xd1\xa8\x17\xe4\xef\x00\xb5\x5c\x27\xf2\x31\x4d\x03\x4b\x01\xfb\x59\x14\xf0\xb6\x87\x4f\xab\x3e\x5d\x67\x99\xbd\xe4\x77\x21\x0b", 33);
