### ISSUE TITLE
Unclear error message from lncli updatechanpolicy

### ISSUE THREAD

**Issue by emplexity** [lightningnetwork/lnd#4702]
### Background
updating the fee channel policy of the 85+ channels of my node
command executed but with an error message

### Your environment
    85 + channels some initially with base_fee_msat 0 and 1000 and after the cmd all 1000
    0.11.99-beta 
    bitcoind v 0.20.0, 
    bitcoin and lnd on the same machine,
    lnd launched with nohup
    Running on a Ubuntu 16.04 virtual machine, with 1 TB disk, 14 GB RAM

### Steps to reproduce

Launch the following command:
~$ lncli updatechanpolicy --base_fee_msat 1000 --fee_rate 0.000001 --time_lock_delta 144

### Expected behaviour

It would be expected that the fee policy of all channels are updated according the command, that no error message is returned and if it does, that the error message reports whether the command was executed fully, partially or not at all and in case it is specific to the channels in error, it list them and gives their status after the command is executed

### Actual behaviour

got the following error message:
[lncli] rpc error: code = Unknown desc = generated invalid channel update sig: max_htlc(5000000000 mSAT) for channel update greater than capacity(2500000000 mSAT)

lncli feereport shows all channels have updated policies as per the lncli updatechanpolicy.

**Comment by Roasbeef** [comment]
Error is as stated: you can't set the max_htlc value for a channel to be a value greater than the channel itself.

**Comment by Roasbeef** [comment]
You're correct in that it's possible for partial application, as we commit each channel individually.

**Comment by emplexity** [comment]
Noted that the command processes all channels per increasing chan_id until it hits the ill channel, then the command reports the error and quit, leaving all channels with chan_id higher than the ill channel untouched.
I would expect the command skips the ill channel (after having reported the chan_id and the error message) and continues to process the following channels.

**Comment by Roasbeef** [comment]
Adding some commentary here: a way forward here is to either ensure that updates are all or nothing, or modify the return value to indicate which updates were successful vs not.
