### ISSUE TITLE
Can't pay any invoice

### ISSUE THREAD

**Issue by patrikmojzis** [lightningnetwork/lnd#4706]
**### Background**

I already tried paying several invoices from different nodes but none seems to go through. I even have opened direct channel to the node I got invoice from, but it still shows the same error that no route was found.

$ lncli payinvoice lnbc1500n1p0caagvpp53wgq4hpzqn2y6vsms4jzsvuv6xyf467gwn4cahv72njuls9755rqdpa2fjkzep6ypkxjmntypcxzunpypjkcgrxv96kxet5yqcjuvpsxqs8xct5wvsxxcqzpgxqr23ssp574pz8n8mtrrdjf66e3ttkehu0pjxvasrjw4z8tuntgeex08vkkhs9qy9qsq700am04xg6he3wysjmx263yremh75p26c2wm39n877ewf6vued5qt2y2gdp62lujvzwskmgdepfckmc7yxtx7a3ctefcxderv00jr5gqzaqmsu

Payment hash: 8b900adc2204d44d321b856428338cd1889aebc874eb8edd9e54e5cfc0bea506
Description: Read: link para el faucet 1.000 sats c
Amount (in satoshis): 150
Fee limit (in satoshis): 150
Destination: 03d06758583bb5154774a6eb221b1276c9e82d65bbaceca806d90e20c108f4b1c7
Confirm payment (yes/no): yes
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
| HTLC_STATE | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE | TIMELOCK | CHAN_OUT | ROUTE |
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
Amount + fee:   0 + 0 sat
Payment hash:   8b900adc2204d44d321b856428338cd1889aebc874eb8edd9e54e5cfc0bea506
Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE
[lncli] FAILED

**### Your environment**

- "version": "0.11.99-beta commit=v0.11.0-beta-312-gd12f76fd6d48f5d4df8d830b5ec49e9277ffa5c0"
- MacOS
- BTC neutrino
- Node runs behind Tor

**### Steps to reproduce**

Not clear.

**### Expected behaviour**

Payment should go through.

**### Actual behaviour**

Error: Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE

**Comment by Crypt-iQ** [comment]
Do you have any logs for this?

**Comment by patrikmojzis** [comment]
Never mind. Just found out that my node is only badly connected in the network. And regarding the direct channel, I checked the destination from invoice and it's actually a different pubkey than the recipient has on its website. So I thought I have different channel to him but in fact I did not. My bad. Closing issue.
