### ISSUE TITLE
[Feature] Ability to set expiration on LeaseOutput

### ISSUE THREAD

**Issue by AnthonyRonning** [lightningnetwork/lnd#4709]
### Background

I dug into it and it looks like the `LeaseOutput` API falls back to using `btcwallet`'s default leasing time of [10 minutes](https://github.com/btcsuite/btcwallet/blob/a7f551a6301c6368084a522ca67009981b3dc0b6/wtxmgr/tx.go#L29). 

I realize I can keep calling it to reset the timer but the ability to programmatically set it to a certain long running time without repeated calls over and over again would be useful. Happy to take a stab at it, but wanted to open the ticket first for discussion. 

Looks like it'll have to be passed all the way through to: 

https://github.com/btcsuite/btcwallet/blob/a7f551a6301c6368084a522ca67009981b3dc0b6/wtxmgr/tx.go#L1156-L1176

**Comment by halseth** [comment]
Def useful! In order to avoid losing track of outputs locked indefinitely, we should also possible expose `ListLocked` or `UnlockAll` methods.

**Comment by joostjager** [comment]
Added `ListLeases` to the PR, but skipped `UnlockAll`. Seems potentially dangerous to just release all locks indiscriminately. And this functionality can also be implemented client-side now.
