### ISSUE TITLE
Receiving 'out of order block' error when using HA bitcoin nodes

### ISSUE THREAD

**Issue by gkrizek** [lightningnetwork/lnd#4710]
### Background

I run multiple btcd nodes for a backend to an LND node. When LND starts up it picks one to connect to and establishes a websocket connection. If that btcd nodes goes away for whatever reason then LND connects to a new btcd node from the pool. It's possible (especially on testnet) that the server that got killed was behind on blocks. So when it connects to the new node it's actually seeing the chain head, but we receive this error over and over:

```
2020-10-22 05:08:49.762 [ERR] CRTR: out of order block: expecting height=1863909, got height=1863976
```

Looking at the code it seems like I'm hitting this case statement:
https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L1037-L1064

The comment about its utility makes sense, but I'm wondering if there's a better way to handle this? What if we checked if the received block is greater than our last known block. If it's greater we inspect every block in the delta and apply the necessary changes? I may be missing something with that suggestion, but if the new node is synced to the chain I don't see why we could retroactively get those on-chain events.

Thoughts?

### Your environment

* lnd-v0.11.1-beta
* Linux
* btcd version 0.20.1-beta

### Steps to reproduce

Create 1 LND node and 2 BTCD nodes. Configure automatic failover. Let the btcd that LND is connected to fall behind on blocks. Kill the bad btcd server so LND talks to the new btcd instance.

### Expected behaviour

Instead of just refusing to do anything try to retroactively apply updates.

### Actual behaviour

Just logs an error and doesn't continue

**Comment by gkrizek** [comment]
@wpaulino  I was going to take a whack at this, seems fairly easy except I'm not sure the best way to retrieve previous blocks in the `routing` package. Is there an example of the best way to accomplish that?

**Comment by wpaulino** [comment]
The chain notifier, which is what delivers the block notifications to the router, should already handle that. You may want to take a look at how notifications are delivered and maybe some of the related unit tests before tackling this. In the case you outlined above, once the notifier detects it missed blocks, it'll deliver the missed ones first and proceed to deliver any new ones at tip. Feel free to reach out on Slack if you have any questions.
