### ISSUE TITLE
Channels to online peers becoming inactive. Disconnect/reconnect brings them back online

### ISSUE THREAD

**Issue by mrfelton** [lightningnetwork/lnd#4714]
### Background

We have a number of channels that keep flipping to an offline status even though I know for a fact that the peer is online.

For example, I could have 2 channels open to some node with one of them showing as online and the other showing as offline at the same time. The peer clearly can't be both online and offline at the same time. Also, I have channels to the same peer from another node and those channels are also showing as online.

If I issue `lncli disconnect` and then `lncli connect` the offline channel will start showing as online again (sometimes just `lncli disconnect` is enough without the subsequent `connect` call)

### Your environment

* version of `lnd`: 0.11.1-beta
* which operating system (`uname -a` on *Nix): alpine
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details

### Steps to reproduce

Not sure. Seems to happen randomly but relatively frequently (most days)

### Expected behaviour

Channel should remain active continuously unless the peer is actually offline.

### Actual behaviour

Channel randomly gos into offline state even though the channel peer is online.

**Comment by hpbock** [comment]
The vertical spikes mark the restarts of LND. This Issue seems to have startet on week 42.
![grafik](https://user-images.githubusercontent.com/15837933/97146377-0867f380-1768-11eb-9535-ead8c8e95737.png)

**Comment by Roasbeef** [comment]
Closing as IIUC this was resolved as part of the https://github.com/lightningnetwork/lnd/issues/4724 saga
