### ISSUE TITLE
discovery: investigate node/channel level channel update throttling

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4724]
As is, we de-duplicate channel updates (if a channel is updated 10 times during our interval, we'll only send out a single update) and also only flush out channel updates periodically. In additino to possibly increasing the default value of the flush interval, we should also look into throttling updates on the _node/channels_ level. This may be beneficial as it's still possible for a single node to have some faulty script that updates channel updates too frequently, which ends up creating load on the network similar to the past zombie channel churn saga. This may also be causing unstable connections in the network, as too many messages in the queue may lead to failed write timeouts on the sending end, which ends up causing connections to fail unnecessarily. 

At a high level, we should go with something simpler first, then iterate from there. A possible route would be something like:
  * First, telemetry: each time we commit+broadcast a channel update, note the node that it emanated from (as we have directional edges). Increment a counter that keeps track of the number of updates generated from the node, which maybe also stores extra info w.r.t which channel and the diff itself. 
  * Next suppression: if we receive a channel update from a node, that doesn't appear to be a heart beat (to keep the channel alive), then we should check against the allotted quota. Something sane might be: only propagate the updates of a node N times a day. Where we permit a node to update all its set of channels (consider a `updatechanpolicy` that updates all the fees of a channel). Stuff like fee changes won't significantly be affected, as nodes will send back the latest chan upd if a routing failure happens.

**Comment by Roasbeef** [comment]
Thinking about this a bit more, we could do some combination of: 
  * Allowing the user to specify the total amount of bandwidth they want to contribute to gossip, either including or discounting IGD. If this threshold is reached, all gossip timestamps are set to nil, and we'll no longer receive active gossip messages from peers. This mode would still relay new channel announcements however. 
  * Allow the user to specify a per-node bandwidth allotment. Similar to the above, but lets the user be bit a bit more granular. This can either be node in terms of the number of peers we'll maintain or nodes in the network.

**Comment by alevchuk** [comment]
I wrote a design proposal for this: https://github.com/alevchuk/minibank/blob/first/incidents/i3/README.md

Please take it for what it's worth. I could be getting some assumptions wrong.

**Comment by Roasbeef** [comment]
Implemented in #4786
