### ISSUE TITLE
Proposal: set transaction confirmation timeout for 7 days

### ISSUE THREAD

**Issue by begetan** [lightningnetwork/lnd#4726]
With the new Bitcoin Mempool reality, it is quite easy to stack in with the low-cost transaction for up to 7 days.  It may cause an issue like this: https://github.com/lightningnetwork/lnd/issues/4575

I would like just to prioritize the already discussed decision about the new timeout.

![image](https://user-images.githubusercontent.com/17225934/97372249-7a008880-18b3-11eb-91b5-baba429540a8.png)

**Comment by Roasbeef** [comment]
We'll wait for 2016 blocks as is: https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L54

Do you think we need to increase it beyond 2 weeks?

**Comment by MrManPew** [comment]
The question is what happen if it takes more than two weeks, lets say it take 2 months.

**Comment by begetan** [comment]
> We'll wait for 2016 blocks as is: https://github.com/lightningnetwork/lnd/blob/master/fundingmanager.go#L54
> 
> Do you think we need to increase it beyond 2 weeks?

@Roasbeef This setting  is good!
 Actually this question inspired by your comment: https://github.com/lightningnetwork/lnd/issues/4575#issuecomment-686844886

>lnd will forget such channels after about 2 days or so, not sure how long eclair will hold on to them

Could you elaborate please what kind of timeout is?

**Comment by Roasbeef** [comment]
> The question is what happen if it takes more than two weeks, lets say it takes 2 months (or X> timeout value)

You only forget the channel is you're the responder. At that point, you don't even have any coins so it's safe to forget. If we don't forget after sometime, then it's possible for someone to fill up disk by just making channels that'll never even exist (since it's single funder). 

> Could you elaborate please what kind of timeout is?

I was wrong there, operating of an older model of the code. We changed to 2 weeks last year.
