### ISSUE TITLE
Add an option to automatically create a SCB file each time a new channel is added

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#4729]
### Background
It would be useful to have an option (which I think should be true as default) to create a new SCB file each time the channel status of the node changes. 
I assume one can also set the path in the config file so that the SCB can be written on an external usb(s) so that one can have more copies.

Some points I get form this crush:
https://github.com/lightningnetwork/lnd/issues/4720

**Comment by guggero** [comment]
This feature is already implemented. A `channel.backup` file is created in the same folder as the `wallet.db` file. Every time a channel is opened or closed the file is updated. The command line flag `--backupfilepath=` (or configuration option `backupfilepath=`) can change this default location.
