### ISSUE TITLE
Add noencryptwallet option to tutorial lnd.conf

### ISSUE THREAD

**Issue by jcyktor** [lightningnetwork/lnd#473]
While going through the beginning part of the tutorial, I ran into this message on trying to launch the `lnd` for alice:

> Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.

I was getting a similar message trying to run `lncli` and pointing to alice's `lnd`. I found PR #367 and tried the --noencryptwallet flag, which makes everything work as expected.

I looked through this repo and couldn't find the tutorial pages. If they're in another repo, let me know and I can open this issue there.

**Comment by Roasbeef** [comment]
The tutorials are housed in https://github.com/lightninglabs/lightning-dev-site

**Comment by Roasbeef** [comment]
Closing this as the issue should be opened on the dev site's repo.

**Comment by EddieOne** [comment]
The docs say to use this only for testing. What's the long term solution? It's not clear how to run `lncli create`

**Comment by halseth** [comment]
@EddieOne Not sure what you are trying here? That does not look like logs from `lncli create`-

**Comment by EddieOne** [comment]
Oh sorry, posted in the wrong tab.
