### ISSUE TITLE
routing: expose custom split size over RPC interface, prefer smaller splits on path finding 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4730]
As is, we'll only split when absolutely necessary. This has some nice traits, however, it means that at times we'll end up splitting way too late, and possibly run into the timeout a user has set for the entire payment. One way to start to experiment with this value a bit more would be to expose a new knob for path finding `max_shard_size` that lets a user control the largest possible payment shard to attempt. This will be useful for our upcoming system's testing framework for MPP/AMP itself. 

In addition to this we may want to look into a further proportional discount for payment attempts. As an example, if a payment attempt tries to consume more the say 25% (random number) of channel's capacity, then we'd penalize the attempt further to skew towards smaller splits.

**Comment by thorie7912** [comment]
It would be interesting to see some built-in heuristics around shard size vs routing speed vs routing price. Sometimes larger payments will go through but in higher fee channels, but there would be significant cost savings by going through a high number of shards instead. I personally would like to see `--force_parts` to directly begin with many shards, in addition to the current `--max_parts`, for routes that I know tend to be pricey for large payments.

**Comment by MaxHillebrand** [comment]
consider this a concept ACK for the feature request. I think it would solve a issue that I have constantly!

---

When attempting to route [relatively] large values, I always set `max_parts` to something like `10`. However, it seems that lnd always only queries routes with `1` part.  This results in countless route discovery failures and unsuccessful payments. [very very very many... :cry:]

That's super frustrating, as I do have plenty of liquidity to make the payment **across all channels**, but not enough in any one channel.

Having some flag like `force_parts` or `min_parts` would [hopefully] help.

Looking forward to testing this in [maybe] v0.13.0 already!! :rocket: :black_heart:

**Comment by MaxHillebrand** [comment]
to be clear, I'm requesting `min_parts` in lncli.

**Comment by Roasbeef** [comment]
> However, it seems that lnd always only queries routes with 1 part

Can you elaborate on this? The default behavior right now is to essentially split only when absolutely necessary. As a result, it may split "late in the game", when an earlier split may have had more success.

**Comment by Roasbeef** [comment]
> to be clear, I'm requesting min_parts in lncli.

Isn't this the same as setting the value manually? Or you want to ensure that if the payment is made, then it should use _at least_ `min_parts` payment shards?

**Comment by MaxHillebrand** [comment]
> However, it seems that lnd always only queries routes with 1 part

I run `lncli payinvoice --min_part 10 --pay_req <invoice> --amt 1000000`, then it queries routes, I don't see that it routes through multiple paths.

After 60 seconds, the route fails due to timeout, again, no sight of multiple paths. 

Unrelated to this issue, but how can increase that timeout to larger than 60 sec?

> Or you want to ensure that if the payment is made, then it should use at least min_parts payment shards? @Roasbeef 

Yes, if `min_parts 3` `max_parts 10`, the route MUST use at least 3, at most 10 parts.
