### ISSUE TITLE
rpc: allow users to set a persistent preference w.r.t the co-op fee rate

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4732]
As is, we always use the same target to attempt to negotiate co-op close fees. Negotiation itself is difficult to really allow a users to express their true preference, but that's outside the scope of this issue. To make things a bit more predictable for users, they should be able to _override_ the default fee rate that lnd uses when attempting a co-op close.

**Comment by murtyjones** [comment]
> the default fee rate that lnd uses when attempting a co-op close

looking into this one, where can i find the default fee rate in the codebase?

**Comment by Roasbeef** [comment]
@murtyjones the default rate is here: https://github.com/lightningnetwork/lnd/blob/f6f3ab5b0bd086ba3c4965bbdda0b6276893404b/peer/brontide.go#L2337. Right now it hard codes a 6 block conf estimate, which can be pretty high at times since it's what many default to.

**Comment by ellemouton** [comment]
@murtyjones, are you still looking into this one? If not, i'm keen to have a go. 

Quick question: Would the best thing to do be to:
a) add this to the main lnd Config struct (something like `--CoopCloseTargetConfs` with default = 6) and then pass that config down to each peer Brontide Config and use it from there. (in this option, all channels will get the same value) .Or
b) Only have the config in the Brontide Config and then have an rpc method to change the value on a per-channel basis?

**Comment by murtyjones** [comment]
> @murtyjones, are you still looking into this one? If not, i'm keen to have a go.
> 
> Quick question: Would the best thing to do be to:
> a) add this to the main lnd Config struct (something like `--CoopCloseTargetConfs` with default = 6) and then pass that config down to each peer Brontide Config and use it from there. (in this option, all channels will get the same value) .Or
> b) Only have the config in the Brontide Config and then have an rpc method to change the value on a per-channel basis?

Didn't end up getting to it, feel free!
