### ISSUE TITLE
wrong error message when recovering a wallet with a word that is not in word list

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#4733]
### Background
I used my mnemonic recovery words, and used accidentally used the word `hear` which is not in the word list:
https://github.com/lightningnetwork/lnd/blob/c1c4b84757dd5b1e1fcb285b4a1fa6a56b35432c/aezeed/wordlist.go

I should have got 
`word hear isn't a part of default word list`
https://github.com/lightningnetwork/lnd/blob/98274f63dcfa907d26135420f96b8fb1b99da31b/aezeed/errors.go#L34

but instead I got:
`Unknown desc = mnemonic phrase checksum doesn't match`

**Comment by Roasbeef** [comment]
Fixed by #4738
