### ISSUE TITLE
Set CLI timeout or status messages for permanent channel failure

### ISSUE THREAD

**Issue by thorie7912** [lightningnetwork/lnd#4734]
### Background

When attempting to send a payment through the CLI, without providing any particular timeout values, a payment can take hours or days to complete. Perhaps there can be a hard limit timeout by default? This is particularly annoying if the purchase is a very tiny amount, and everyone waits in limbo for something to happen. Maybe certain miniscule transactions can be specified as lossy money, where we don't really care if it succeeds or fails from a timeout perspective. In this case, since it was just a self-payment attempt at rebalancing, it didn't matter whether it worked or not, and not worth blocking for 17 hours IMO. A vendor or merchant or buyer might prefer to re-do the transaction and ask for another payment then manually settle the stuck transaction later (by issuing a vendor refund, etc) if it does go through.

```
------------+-------+----------+--------------------+-----------------------------------------------------------------------------------------------+
| HTLC_STATE                    | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE   | TIMELOCK | CHAN_OUT           | ROUTE                                                                                         |
+-------------------------------+--------------+--------------+--------------+-------+----------+--------------------+-----------------------------------------------------------------------------------------------+
| TEMPORARY_CHANNEL_FAILURE @ 1 |        1.263 |        2.928 | 1000         | 2.069 |   654714 | 712573694816944129 | dmbw.Latvia->LightningTo.Me->MOLA La Lightning->microlancer.io                                |
| PERMANENT_CHANNEL_FAILURE @ 1 |        4.170 |    62135.136 | 1000         | 3.039 |   654858 | 712573694816944129 | dmbw.Latvia->mainnet.lightningconductor.net->lnmarkets.com->MOLA La Lightning->microlancer.io |
+-------------------------------+--------------+--------------+--------------+-------+----------+--------------------+-----------------------------------------------------------------------------------------------+
Amount + fee:   0 + 0 sat
Payment hash:   6e0c297669b4500e05f7d5f6c1430a43a5b391398f81060dce3291ae113b2bda
Payment status: FAILED, reason: FAILURE_REASON_TIMEOUT
[lncli] FAILED
```

In this instance, sending 1000 sats took 62,135 seconds to complete (with failure). This is about 17.2 hours. In the meantime, the CLI was basically frozen/stuck, not really sure what was happening.

### Your environment

* LND: 0.11.0-beta commit=v0.11.0-beta
* OS: debian

### Steps to reproduce

Not sure how to reproduce this "permanent channel failure".

### Expected behaviour

Some reasonable CLI timeout or option to mark the transaction as orphaned/abandoned instead of waiting 17 hours. Or maybe an update message saying, "This transaction is taking unusually long time, but we'll keep trying for 62,135 more seconds before giving up. If you CTRL-C the payment will still continue to be attempted in the background."

### Actual behaviour

The CLI prompt was basically frozen in the terminal making me wonder if the system had crashed or something.

**Comment by Roasbeef** [comment]
When using the actual RPC interface, it's possible to use the async variant of sendpayment, and then use `TrackPaymentStatus` to receive updates. I don't think any major merchant/vendor is doing things purely based on the command line. The CLI has a default timer of 1 minute or so which can be extended. In your case, it appears that possibly the HTLC was held for a period of time.
