### ISSUE TITLE
Watchtower problem

### ISSUE THREAD

**Issue by ZsZolee** [lightningnetwork/lnd#4739]
### Background

I have two LND nodes. One is MynodeBTC and the other was Raspiblitz. I used the Raspiblitz to be a Watchtower node only. I had major TOR connection problems, so I wanted to switch to from Raspiblitz to MynodeBTC with my Watchtower node. First before I deleted the Raspiblitz, I wanted to remove from MynodeBTC (my main node) the connection to the Watchtower with the following command:

"lncli wtclient remove 039ce85b142b92f1d6051e57bcc66790fd03686685a6cd4a3f65cf2aa27e56c063@ovrhgl47prkmftvsdxuehak577t4oj5jydnsudhszjnifr2vau3gg2id.onion:9911"

Everything went fine, until I restarted the main node (MynodeBTC). Than LND never started again. I attached the LND [logs.](https://gofile.io/d/NDH4cR)

I needed to delete from the Mynode LND config the following line: "wtclient.active=1", to be able to run LND again.

### Your environment

version of `lnd 0.11`
operating system (MynodeBTC on an RPI4)
version of `bitcoind'

### Steps to reproduce

If I add again the following line:  "wtclient.active=1" to the LND config, the error happens again.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment]
You'll need to omit the address to fully remove the watchtower, e.g., `lncli wtclient remove tower_pubkey`.

**Comment by ZsZolee** [comment]
If I reactivate "wtclient.active=1", then LND can't start as I mentioned above. When I run the following command, I got an error:

"admin@myNode:~ $ lncli wtclient remove 039ce85b142b92f1d6051e57bcc66790fd03686685a6cd4a3f65cf2aa27e56c063
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd."

What should I do now?

**Comment by wpaulino** [comment]
Are you able to apply the following patch locally? This should allow you to start up after recompiling and restarting with these changes. After that, you'll want to add an address to the tower with `lncli wtclient add tower_pubkey addr`. You can then revert back to `v0.11.0-beta` (get rid of the patch) and remove the tower again with `lncli wtclient remove tower_pubkey`. I'll be opening a PR to prevent this issue going forward.

```
diff --git a/watchtower/wtclient/client.go b/watchtower/wtclient/client.go
index e85ea9cd..899b23fb 100644
--- a/watchtower/wtclient/client.go
+++ b/watchtower/wtclient/client.go
@@ -273,24 +273,6 @@ func New(config *Config) (*TowerClient, error) {
 		cfg.WriteTimeout = DefaultWriteTimeout
 	}
 
-	// Next, load all candidate sessions and towers from the database into
-	// the client. We will use any of these session if their policies match
-	// the current policy of the client, otherwise they will be ignored and
-	// new sessions will be requested.
-	candidateSessions, err := getClientSessions(
-		cfg.DB, cfg.SecretKeyRing, nil, activeSessionFilter,
-	)
-	if err != nil {
-		return nil, err
-	}
-
-	var candidateTowers []*wtdb.Tower
-	for _, s := range candidateSessions {
-		log.Infof("Using private watchtower %s, offering policy %s",
-			s.Tower, cfg.Policy)
-		candidateTowers = append(candidateTowers, s.Tower)
-	}
-
 	// Load the sweep pkscripts that have been generated for all previously
 	// registered channels.
 	chanSummaries, err := cfg.DB.FetchChanSummaries()
@@ -301,8 +283,8 @@ func New(config *Config) (*TowerClient, error) {
 	c := &TowerClient{
 		cfg:               cfg,
 		pipeline:          newTaskPipeline(),
-		candidateTowers:   newTowerListIterator(candidateTowers...),
-		candidateSessions: candidateSessions,
+		candidateTowers:   newTowerListIterator(),
+		candidateSessions: make(map[wtdb.SessionID]*wtdb.ClientSession),
 		activeSessions:    make(sessionQueueSet),
 		summaries:         chanSummaries,
 		statTicker:        time.NewTicker(DefaultStatInterval),

```

**Comment by ZsZolee** [comment]
Sadly I don't know how to do it because I'm just a user, not a developer. Can you write me the steps what to do? Or if I wait for the new version will that solve my problem?

**Comment by wpaulino** [comment]
Are you in our Slack? I can guide you through there, I'm `@wilmer` with the same photo.
