### ISSUE TITLE
Incoming Channel Opening Constraints

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#476]
Would be a nice feature to have a minimum set of parameters for anyone opening channels to a node and advertise that especially for merchants.

Some nodes may want to avoid having tens if not hundreds of small value channels which would could be expensive to close especially in times of high fee congestion.

Would be useful for me as I could peg the incoming channel btc rate to be the 100 USD equivalent or something on my end.

**Comment by Roasbeef** [comment]
@halseth is working on a task related to this

**Comment by Roasbeef** [comment]
Has been resolved with this PR: #3039
