### ISSUE TITLE
Ali

### ISSUE THREAD

**Issue by alizeyni** [lightningnetwork/lnd#4766]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by carlaKC** [comment]
Seems like an accidentally opened issue?
