### ISSUE TITLE
LND erroring out when restoring wallet with funds and open channels with funds

### ISSUE THREAD

**Issue by resdat** [lightningnetwork/lnd#4771]
### Background

I had a running copy of lnd on a Raspberry Pi 3, and ran out of diskspace due to the growth of the blockchain so it crashed and I could not restore it.  I built a new machine, sync'ed bitcoind and installed lnd. I created a wallet based on my old password and seed words. Initially it came up to sync, but is now crashing immediately. I had funds in both the wallet and channels. I understand the issue with channel funds, and am primarily after the wallet funds that are on-chain, but the restore of funds using create does not seem to be working. 

I think I can restore the funds by using my 24 seed words on a standard wallet and transferring them from there, but I thought it was good to report this since it seems to be a bug.

### Your environment

* lnd version 0.11.1-beta commit=v0.11.1-beta
* Ubuntu 20.04.1 LTS
* Bitcoin Core version v0.20.99.0-b99a1633b

### Steps to reproduce

Generally a common setup. One difference this has is that it is using REST due to a web service on this machine:

restlisten =localhost:8888

lnd& causes this error for me.

### Expected behavior

I would expect to see the wallet funds, but none of the channels that were previously set up.

### Actual behavior

[INF] CHBU: Starting chanbackup.SubSwapper
2020-11-08 19:11:30.282 [ERR] LTND: unable to start server: unable to refresh backup file: unable to extract on disk encrypted SCB: chacha20poly1305: message authentication failed

**Comment by guggero** [comment]
It sounds like you perhaps started `lnd` on this machine previously with another seed. It's trying to update the existing channel backup but that is encrypted with another wallet seed.
Try removing (perhaps make a backup of the file somewhere, just in case) the file in `~/.lnd/data/chain/bitcoin/mainnet/channel.backup`.

Or if you did run a node on this machine before (maybe just while trying something out?), maybe you're better off renaming the whole `.lnd` folder to something else and starting over cleanly.

**Comment by resdat** [comment]
moving the channel.backup to a new filename and restarting lnd solved the problem. Thanks!
