### ISSUE TITLE
[ERR] NANN: Unable to retrieve chan status for Channel(): edge not found

### ISSUE THREAD

**Issue by dsche-cyber** [lightningnetwork/lnd#4791]
### Background

bitcoind node and lnd node were offline for like 1 month.
Before I shut those down I made a channelbackup (SCB).
I run lncli restorechanbackup.

### Your environment

lnd-0.11.1-beta
Linux 5.9.8-gentoo
bitcoind (bicoin core) v0.20.1.0-gentoo

### Expected behaviour

Sats from Remote Forced channel closes return to wallet.

### Actual behaviour
Not all funds come back (some did).

I censor all hashes here with XXX and number them so you can refer to them, if you need them for debugging (just ask).

lnd gives repeatedly (but else functioning well, but my sats are still not all back):
[ERR] NANN: Unable to retrieve chan status for Channel(XXX:1): edge not found

I get three different categories of closed channels (existing resolution: CLAIMED, UNCLAIMED) and no resolution existing. Actually some funds got back and are now CLAIMED, but not all. So the problem is the UNCLAIMED and those without resolution.

How do I claimed those sats? What do I need to do?
The command lncli closedchannels for those two problematic categories, gives:
        {
            "channel_point": "XXX1",
            "chan_id": "XXX2",
            "chain_hash": "XXX3",
            "closing_tx_hash": "XXX4",
            "remote_pubkey": "XXX5",
            "capacity": "XXX6",
            "close_height": XXX7,
            "settled_balance": "XXX8",
            "time_locked_balance": "0",
            "close_type": "REMOTE_FORCE_CLOSE",
            "open_initiator": "INITIATOR_REMOTE",
            "close_initiator": "INITIATOR_REMOTE",
            "resolutions": [
                {
                    "resolution_type": "COMMIT",
                    "outcome": "UNCLAIMED",
                    "outpoint": {
                        "txid_bytes": "XXX9",
                        "txid_str": "XXX10",
                        "output_index": 0
                    },
                    "amount_sat": "XXX11",
                    "sweep_txid": "XXX12"
                }
            ]
        },
        {
            "channel_point": "XXX13",
            "chan_id": "XXX14",
            "chain_hash": "XXX15",
            "closing_tx_hash": "XXX16",
            "remote_pubkey": "XXX17",
            "capacity": "XXX18",
            "close_height": XXX19,
            "settled_balance": "0",
            "time_locked_balance": "0",
            "close_type": "COOPERATIVE_CLOSE",
            "open_initiator": "INITIATOR_LOCAL",
            "close_initiator": "INITIATOR_UNKNOWN",
            "resolutions": [
            ]
        },

**Comment by guggero** [comment]
Need additional information, @dsche-cyber contacted me on Slack and we're going to try to resolve it there.
My first suspicions are:
1. Offline peer
2. Outputs small enough to sweep at time

Will comment here what the final outcome was.

**Comment by Roasbeef** [comment]
That error is also a sign that possibly they were running an earlier (possibly master version?) of thee latest logic used to enable/disable channels.

**Comment by guggero** [comment]
@dsche-cyber what's the status on this issue? Were you able to do a full wallet rescan to fix your UTXO set?

**Comment by dsche-cyber** [comment]
@guggero By your recommendation rescanning is better done with closed channels. As one channel was still open, but one peer not responding, I force closed, so it will take some time until it is settled. Then I will try to rescan...

**Comment by dsche-cyber** [comment]
After waiting some time, funds return, but my lnd node didn't saw it. As @guggero recommended, I rescanned by following the guide:
https://github.com/lightningnetwork/lnd/blob/987edc9d810f000d97bc9ac3ba1668e3bec77018/docs/recovery.md

Now everything is fine, the funds from forced channel are back AND the funds that I was missing, when I openend this issue.
Thanks to @guggero, funds are SAFU!
