### ISSUE TITLE
Maintain connection to nodes with existing legacy channels

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#4800]
After we flipped the `static_remote_key` feature to required (https://github.com/lightningnetwork/lnd/pull/4751) lnd will fail to connect to _existing channel peers_ without this feature. See https://github.com/ACINQ/eclair-mobile/issues/256

We should probably don't require this feature for nodes we have existing legacy channels with.

**Comment by Roasbeef** [comment]
Will need to shift things around a bit for this, as it'll mean we need to read out the channels before we connect to a peer and enter the normal post connection state initialization.

**Comment by halseth** [comment]
Taking this one.

**Comment by halseth** [comment]
@C-Otto Can you checked whether master resolves your issue?

**Comment by C-Otto** [comment]
I force-closed my channel, sorry.
