### ISSUE TITLE
[anchor] Reserve UTXO for  anchor channel close

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#4808]
With anchor channels one might need an extra utxo to add fees to both the force close and the HTLC transactions. We should add a check/reserve that makes sure this is available at all times.

**Comment by Roasbeef** [comment]
What's the plan for this in the context of 0.13? Improve the estimation on our current 10k sat reserve?

**Comment by Roasbeef** [comment]
Consolidate a single UTXO for bumping purposes each time we do a transaction and/or sweep? The sweeper could grow (or something right above it) to manage this fee bumping UTXO to make sure it's available and is of "sufficient" size.

**Comment by Roasbeef** [comment]
Closing this as it has already been done?
