### ISSUE TITLE
Cannot obtain payment preimage after payinvoice command

### ISSUE THREAD

**Issue by anaoum** [lightningnetwork/lnd#481]
Currently the user is only ever presented with the payment_preimage after the payinvoice command.

Using the listpayments command at a later time does not show the preimage for paid invoices, only their hashes.

The preimage serves as proof of payment of a specific invoice and should be obtainable by the user if needed.

**Comment by Roasbeef** [comment]
Definitely! We currently don't store the preimage, only the payment hash. It's relatively straight forward to just store the _preimage_ instead. Also we should be storing the _entire_ payment request as that itself acts as a signed receipt and proof-of-payment along with the pre-image. 

Relevant code fragments that would need to be modified to fix this: 
  * https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L1534
  * https://github.com/lightningnetwork/lnd/blob/master/channeldb/payments.go#L40
