### ISSUE TITLE
channeldb: can't coop close channel after first try fails or times out

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#4819]
Opening this issue on behalf of a user that wishes to remain anonymous. The full log is available to me.

Relevant entries:

```
day 1 00:31:42.925 [INF] SRVR: Local close channel request delivered to peer: 02adxxx
day 1 00:52:29.557 [INF] SRVR: Disconnecting from 02adxxx@<remote-IP>:45566
day 1 00:52:29.558 [INF] PEER: disconnecting 02adxxx@<remote-IP>:45566, reason: server: disconnecting peer 02adxxx@<remote-IP>:45566
day 1 00:52:29.558 [INF] PEER: unable to read message from 02adxxx@<remote-IP>:45566: read tcp 172.21.0.4:9735-><remote-IP>:45566: use of closed network connection
day 1 00:56:18.535 [INF] SRVR: Finalizing connection to 02adxxx@<remote-IP>:33750, inbound=true
day 1 00:56:18.583 [INF] PEER: NodeKey(02adxxx) loading ChannelPoint(<redacted>:0)
day 1 00:56:18.585 [INF] DISC: Creating new GossipSyncer for peer=02adxxx
day 1 00:56:18.585 [INF] PEER: Negotiated chan series queries with 02adxxx
day 1 00:56:18.588 [ERR] PEER: resend failed: unable to fetch channel sync messages for peer 02adxxx@<remote-IP>:33750: unable to find closed channel summary
...
day 3 06:48:41.764 [INF] PEER: disconnecting 02adxxx@<remote-IP>:33750, reason: read handler closed
```

User must now force-close because reconnecting to the peer and trying to coop close again results in the error `nable to gracefully close channel while peer is offline (try force closing it instead): channel link not found`.

Can we fix this by not updating the local channel state until we hear back from the peer?

**Comment by cfromknecht** [comment]
We plan on fixing this but it requires a protocol change. Specifically to not send out signatures for each negotiated fee. If that's the case, then it is safe to load the channel back into an active state (where it can again be coop closed) if the original coop close failed.

**Comment by Roasbeef** [comment]
Removing this from the current milestone/project for now given it requires some protocol changes.
