### ISSUE TITLE
Return payment address when adding hold invoices

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4820]
### Background

In pull request [4752](https://github.com/lightningnetwork/lnd/pull/4752) the payment address secret was added to the response of invoices added

However there is another way to add invoices, which is the add hold invoice API, and to be consistent this should return the payment address as well

Currently this method in the invoices sub-server only returns the payment request in its result.

A workaround would be to lookup the invoice and retrieve the payment address that way.

**Comment by ErikEk** [comment]
I'll take a look.
