### ISSUE TITLE
LND doesn't recover from too many opened files

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#4821]
### Background

I found out that [ThunderHub opens too many connections to LND](https://github.com/apotdevin/thunderhub/issues/178). After stopping ThunderHub the number of file descriptors went down however to my surprise, LND was still unusable. (By ThunderHub or other means like `lncli`.)

### Your environment

* version of `lnd` 0.11.1
* which operating system (`uname -a` on *Nix) `Linux <censored> 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend `bitcoind` v0.20.0
* any other relevant environment details FD limit seems to be 1024

### Steps to reproduce

1. Start LND
2. Open too many connections to LND RPC
3. Waiting a while might be needed, not sure
4. Close the RPC connections
5. Attempt to connect to LND again

### Expected behaviour

LND should recover from this problem and continue accepting connections once it was solved

### Actual behaviour

LND doesn't accept connections anymore even after closing the "bad" connections.

### Additional notes

Apart from this, it'd be really nice if LND managed FDs a bit more carefully. Hitting the limit may prevent it from doing other essential operations such as connecting to peers or bitcoind. LND could get the FD limit at the start and then reserve some portion for outgoing connections and perhaps also split the limit between RPC and P2P connections. Finally, maybe instead of logging each failed accept, log the first failed accept and then log success once it succeeds. Logging every failure every second fills the log with useless messages and causes rotation.

**Comment by guggero** [comment]
What's the actual error message that `lnd` logs _after_ the connections were closed again?

**Comment by Kixunil** [comment]
```
lnd[30978]: 2020/12/03 08:39:07 http: Accept error: accept tcp4 0.0.0.0:9090: accept4: too many open files; retrying in 1s
lnd[30978]: 2020/12/03 08:39:08 http: Accept error: accept tcp4 0.0.0.0:9090: accept4: too many open files; retrying in 1s
lnd[30978]: 2020/12/03 08:39:09 http: Accept error: accept tcp4 0.0.0.0:9090: accept4: too many open files; retrying in 1s
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 194.26.29.126:10467: tls: first record does not look like a TLS handshake
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 194.26.29.126:9321: read tcp4 192.168.2.129:9090->194.26.29.126:9321: read: connection reset by peer
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 162.142.125.38:46338: read tcp4 192.168.2.129:9090->162.142.125.38:46338: read: connection reset by peer
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 162.142.125.38:39010: EOF
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 162.142.125.38:45862: read tcp4 192.168.2.129:9090->162.142.125.38:45862: read: connection reset by peer
lnd[30978]: 2020/12/03 08:39:10 http: TLS handshake error from 162.142.125.38:44416: write tcp4 192.168.2.129:9090->162.142.125.38:44416: write: connection reset by peer
```

ThunderHub was stopped at 08:39:09

**Comment by Roasbeef** [comment]
I think this is a ThunderHub issue, it doesn't appears there's anything we can do at the Go runtime level other than wait for new FDs to become available. Under the hood, if we try to make an outbound connection and there're no remaining FDs, then the runtime will retry in the background. IMO this is more of a kernel thing, as your setting of 1024 FDs is rather low, just imagine 1000 connections across your lnd+bitcoind nodes, at that point, there're no longer any remaining FDs. Also since `bitcoind` uses leveldb that ends up opening a lot of small files, even just the database workload can start to quickly consume file descriptors.

**Comment by Kixunil** [comment]
Please read the description again, it's not about *hitting* the limit, it's about recovering *afterwards*. Yes, ThunderHub caused exhaustion (fixed already), what's problematic is that LND didn't recover from it *after closing* those connections (even after a few minutes).

1024 is the default I don't see how it's low. It's per-process limit, not system-wide limit.

> Under the hood, if we try to make an outbound connection and there're no remaining FDs, then the runtime will retry in the background.

That's also the impression I got from log outputs (retrying in one second...). The thing is this seems to be actually broken. LND is stuck even after cleaning up those FDs.
