### ISSUE TITLE
Maximum outbound liquidity changes automatically over time

### ISSUE THREAD

**Issue by MyNameIsOka** [lightningnetwork/lnd#4824]
### Background

Maybe this is a stupid question but I noticed that my maximum outgoing amount changes even though I don't do anything with the wallet.
I just would like to know why that is.

### Your environment

* `lnd` v0.11.1
* OSX 10.15.7
* `bitcoind` v0.20.1
* using myNodeBTC

### Steps to reproduce

Just created multiple channels and monitored the sats in the wallet over a few days, not sending/receiving anything.

### Expected behaviour

I thought that the funds would stay the same.

### Actual behaviour

Well, the amount changes 😄

**Comment by guggero** [comment]
That's the channel closing fees (a.k.a. commit fees) of your channels adjusting to the rising/falling fee estimation based on the current mempool size/fee environment. That's totally expected for now and should go away with a new channel format that's soon being introduced (anchor output channels).

**Comment by MyNameIsOka** [comment]
I see, thank you for the explanation.
