### ISSUE TITLE
[Feature Request] Add WalletRPC implementation of underlying wallet IsOurAddress function

### ISSUE THREAD

**Issue by jalavosus** [lightningnetwork/lnd#4826]
### Background

Context: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/btcwallet/btcwallet.go#L288

Use case: checking which underyling wallet address was sent to when dealing with the output of GetTransactions.

**Comment by jalavosus** [comment]
Eh, better idea: just get all available wallet addresses (#4836)

**Comment by guggero** [comment]
Fixed by #5476.
