### ISSUE TITLE
Channel opening through PSBT from bitcoin 0.20.1

### ISSUE THREAD

**Issue by tomichec** [lightningnetwork/lnd#4831]
### Background

Bitcoin 0.20.1 has introduced [changes in the format of PSBT](https://bitcoin.org/en/release/v0.20.1#psbt-changes). Those changes made it incompatible with `lncli openchannel --psbt` resulting in the following error when funding the channel.

```
Canceling PSBT funding flow for pending channel ID xxxx...xxxx.
[lncli] verifying PSBT by lnd failed: rpc error: code = Unknown desc = error parsing psbt: Invalid PSBT serialization format
```

### Your environment

Two environments with the same problem.

* version of `lnd`
lncli version 0.11.99-beta commit=v0.11.0-beta-570-gc58589db3badb97451818f88f04471f5ec2e60b0
lncli version 0.11.99-beta commit=v0.11.0-beta-312-gd12f76fd6d48f5d4df8d830b5ec49e9277ffa5c0

* which operating system (`uname -a` on *Nix)

Linux alarm 4.14.180-1-ARCH #1 SMP PREEMPT Tue May 26 02:05:58 UTC 2020 armv7l GNU/Linux
Linux 8ee3768a0b0c 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
bitcoind 0.20.1

* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

I have proceed according to the [PSBT manual](https://github.com/guggero/lnd/blob/84dfed3fe2d28ceda343944874ab47fb57b73515/docs/psbt.md). In summary this involves:

1. initiate the channel opening with a connected node 
```
lncli openchannel --node_key ${node_id} --local_amt xxx --psbt
```
2. switch to another terminal window and create psbt in bitcoin-cli
```
bitcoin-cli walletcreatefundedpsbt [] '[{"bc1q...df":0.0xxx}]'
```
copy the encoded PSBT (long string).

3. switch back to the terminal with channel opening initiation and paste the PSBT.

The error will appear as shown above due to the wrong serialization format.

### Expected behaviour

The lncli should accept the new format of PSBT and show prompt for a finalized and signed PSBT. using `bitcoin-cli walletprocesspsbt  <encodedPSBT>`. Finally this signed PSBT is copied back to the `lncli`

### Actual behaviour

The channel opening is canceled.

**Comment by Roasbeef** [comment]
This was fixed by https://github.com/lightningnetwork/lnd/pull/4673
