### ISSUE TITLE
Allow to sweep private key for the channel opening.

### ISSUE THREAD

**Issue by tomichec** [lightningnetwork/lnd#4832]
### Background

In a usual operation, the user is required to send his funds to the lnd wallet before opening a channel. This means that the user needs to make two transactions to open the channel which increases the cost of channel opening.

### Expected behaviour

Assuming that the user is actually in control of the funds he would like to use for the channel creation, he could also import the private keys from another wallet and fund the channel with a single transaction.

### Actual behaviour

User has to make two transactions or go through complicated proceeding of PSBT channel opening.

**Comment by Roasbeef** [comment]
This is already possible via `PSBT` channel opening. IMO, it's a bad idea to allow users to pass `lnd` a _raw private_ key. Even beyond that we'd need to do a chain scan just to get all the proper UTXO information, and even then it wouldn't be clear what inputs/outputs to use.
