### ISSUE TITLE
routerrpc+routing: add ability to import mission control weights/data

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4833]
As is, it's possible for users to export their mission control state which can be useful for debugging, or just trying to reverse engineer how mission control itself works. The format that's exported is more or less an exact snapshot of the memory/desk state that `lnd` will use to guide its path finding endeavors. Mission control is known to be most effective once it has a "hot cache" as it's able to prune down the search space and avoid routes/channels it knows are already bad or ineffective. However, users that attempt to use path finding with a cold cache may waste time attempting to re-build the prior memory (since the channel weights decay) and potentially will run into some timeout by the time that they have "enough" memory built up. 

Consider that most users use a 60 second timeout, if it takes 61 seconds (making an assumption here for simplicity of the example), then users will timeout before they have a chance to actually start using the memory they've built up. Ofc, passive probing can also help to build up this memory/snapshot as well, but that isn't something that most end users or services do unless they have very high outbound volume, in which case they'll already be passively training their mission control instance over time. 

If we give users an option to _import_ mission control state, then they can start with a _hot cache_ for path finding. Going beyond this, state could be passed around between users of a given service to train their mission control state in a manner similar to distributed active learning in ML land. 

# Steps to Completion 

- [ ] Extend the `missionControlState` struct to be able to _batch import_ a series of pair results. 

- [ ] Add a new call to the `routerrpc`, something like `ImportMissionControl` to allow users to take the _direct_ output of the `QueryMissionControl` call. This data format would effectively become a new standardized way of sharing path finding history/memory between `lnd` nodes. 

- [ ] With the above step, we'll need to make a decision if we encounter a new pair result that already exists within the mission control state.
   * There're a few scenarios we need to account for:
       * A success exists, a newer failure exists (according to timestamp) 
       * A failure exists, a newer success exists 
   * To simplify to start with, we could consider just override anything with a newer timestamp compared to the existing state. In the future, we may attempt to combine in more clever ways, but we should likely just make an incremental step first since this change has rather high leverage for the network and many users as a whole.

**Comment by carlaKC** [comment]
Picking this up.

**Comment by carlaKC** [comment]
Do we want to store the imported information on disk, or just import and update our in-memory state?

Asking because we store full route information in mission control from the perspective of our node always being the sender, so would need to create fake routes for imported data or extend how we store this information on disk. Downside of not storing on disk would ofc be that we don't keep this information across restarts.

**Comment by halseth** [comment]
> Do we want to store the imported information on disk, or just import and update our in-memory state?

What does https://github.com/lightningnetwork/lnd/pull/4909 do?

**Comment by carlaKC** [comment]
> What does #4909 do?

Just in memory, since we don't save config options on disk.

**Comment by halseth** [comment]
I would say that is enough for now. The client updating the state could save it externally if needed.
