### ISSUE TITLE
Add more detailed info from updatechanpolicy

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#4846]
### Background
When trying to update the fee rate of a channel using updatechanpolicy, there are often cases where you send an api/cli call, and when you then check the fee rates, for some nodes the policy changed, and other nodes it didnt.

All calls to updatechanpolicy return:
`{}`

### Your environment

* version of `lnd`
'version': '0.11.99-beta commit=v0.11.0-beta-534-g7e298f143425337448f95019234b22849d64aca3', 'commit_hash': '7e298f143425337448f95019234b22849d64aca3'
* which operating system (`uname -a` on *Nix)
linux
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details
using 

### Steps to reproduce

Gotchas that I have found:

- min_htlc=1, where remote node only allows min_htlc=1000

- When passing in a bad txid using the rest API

- When the channel is unconfirmed

- When the channel is currently in-active.

### Expected behaviour

It should at least return an error message in cases where it cannot update the channel, and if not show why.

It seems that it might require streaming for something like this to actually return a response though.

### Actual behaviour

Most api calls to updatechanpolicy only return:
`{}`

**Comment by guggero** [comment]
I agree this isn't optimal behavior. Another gotcha that silently fails is if the channel isn't active at the moment of the policy update command.

**Comment by sako0938** [comment]
@guggero Oh definitely, that one has tripped me up in the past too!

For example with the LOOP server, my default fee rate is reasonably inexpensive, so my liquidity gets sucked up immediately when connected to the LOOP server. I would like to be able to update the channel's fee rate, before the channel has actually confirmed. Else I have to monitor when it confirms and quickly bump its fees before its liquidity gets used.

**Comment by ErikEk** [comment]
I'm on it.
