### ISSUE TITLE
unknown config option: no-rest-tls on 0.10.4-beta

### ISSUE THREAD

**Issue by 0xfff** [lightningnetwork/lnd#4853]
### Background

Trying to disable tls on rest via config option `no-rest-tls=true`.
According to [here](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L129) the option exists.
However i get `lnd.conf:15: unknown option: no-rest-tls`
Could not find a mention of the option in release notes

### Your environment

*  lnd version 0.10.4-beta commit=v0.10.4-beta
* Linux 4.15.0-112-generic 

### Steps to reproduce

Add the option to lnd.conf and restart lnd

### Expected behaviour

LND should accept the option

### Actual behaviour

LND rejects the option `lnd.conf:15: unknown option: no-rest-tls`

**Comment by halseth** [comment]
This is only available from the next release v0.12, which hasn't bee released yet.

**Comment by cfromknecht** [comment]
@0xfff I also wouldn’t expect this to be backported to 0.10.x considering the minimum recommended version is 0.11.0 as a result of the recently disclosed CVE’s. If you are still running 0.10.4 we strongly encourage updating to 0.11.0 or higher immediately.
