### ISSUE TITLE
confusion about retry-mechanism in LND

### ISSUE THREAD

**Issue by ZhichunLu-11** [lightningnetwork/lnd#4864]
### Background

Well, actually this is not a bug report. I am a fan of the Lightning Network and I am now very interested in LND's payment retry mechanism. Specifically, let's say A goes through B and C to pay D, and then C runs low on balance between CDs. Then C will return **InsufficientBalance**, and this message is put wrapped in **opaque reason**. A can then unlock the reason with its private key, but I'm curious how A would "punish" C in this case. I read the source code and the story seems to be that A will use [setLastPairResult](https://github.com/lightningnetwork/lnd/blob/a2336005e650b33a708081cee18eff8739d0b245/routing/missioncontrol_state.go#L55) to record this behavior and then reduce the probability of routing through C later on. I would like to know if this is the correct understanding, and I would appreciate if you could answer my question! Thanks!

**Comment by carlaKC** [comment]
Hi @ZhichunLu-11, your understanding is correct.

LND's mission control subsystem makes payment attempts, and then tries to attribute failure to one or both nodes along the route, depending on the error we get. In the case of `InsufficientBalance`, that means that C doesn't have outgoing capacity, so we attribute failure to C alone. 

This is a great explainer video: https://www.youtube.com/watch?v=p8toOF-imk4
