### ISSUE TITLE
[neutrino] confirmation notification might be missed if registered at tip

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#4866]
In the neutrino chainnotifier there is a slight chance that a confirmation notification gets missed if the block that confirms it arrive at the exact same time. It gets gets even worse by the fact that the height gets committed to the height hint cache, resulting in any subsequent rescan starting from a block after the one where it actually got confirmed.

I suspect this is the cause of some of the integration test flakes we are seeing for the Neutrino Backend.

### Scenario

1. The client registers for confirmation of a given txid: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L827
2. The request is registered with the `TxNotifier`: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L835
3. While this is happening, the block at which the transaction is confirmed gets mined, and notified by Neutrino: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L246. Since we hadn't yet registered the transaction with the filtered chain view, this block doesn't have the transaction included.
4. The block is connected at tip: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L607
5. Since the tx is not found in the filtered block, the height hint for the conf notification is updated: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/txnotifier.go#L1381
6. Now the filter is updated with the new tx: https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L861
7. Since the backend was told to rewind back to the height (https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/neutrinonotify/neutrino.go#L864) where the tx was registered with the `TxNotifier`, the block where it confirmed will be notified again, but will this time be ignored since it is not at the expected "next height": https://github.com/lightningnetwork/lnd/blob/f8dda6f0eeb99a2a53c4b49ddfd196689d3fbabd/chainntnfs/txnotifier.go#L1359

This causes the confirmation to go undetected.

### Other backends
AFAIK this seems to not be a problem on other backends, since we don't filter the blocks there, so the transaction will be found the first time we receive the block. However, we've seen similar symptoms with the `bitcoind` backend in the past that we never got to the bottom of (https://github.com/lightningnetwork/lnd/issues/3692), so there might be similar events that could trigger something like this on the other backends.

### Fix
Fix doesn't seem to be straight forward, as there is a de-sync between updating the filter and handling the received block. One thing that comes to mind is to accept blocks in the past being notified again, but looks like that would violate some assumptions. A better solution could be to improve on the Neutrino API such that one could atomically update the filter.

**Comment by Crypt-iQ** [comment]
> It gets gets even worse by the fact that the height gets committed to the height hint cache, resulting in any subsequent rescan starting from a block after the one where it actually got confirmed.

@wpaulino Can you confirm this? From my reading of the code, if a height is committed to the height hint cache, the txnotifier will resume at the committed height, and not committed height + 1.

**Comment by Crypt-iQ** [comment]
> It gets gets even worse by the fact that the height gets committed to the height hint cache, resulting in any subsequent rescan starting from a block after the one where it actually got confirmed.

`updateHints` won't update hints for requests not in `rescanComplete` state so this won't happen.
