### ISSUE TITLE
[documentation] sweepall support for unconfirmed_balance

### ISSUE THREAD

**Issue by LightningHelper** [lightningnetwork/lnd#4868]
I am not sure if `lncli sendcoins --sweepall` support also unconfirmed_balance (by CPFP?), if it does, can you please add it to the documentation; if it does not, can you please add this option?

Thanks

**Comment by guggero** [comment]
Setting `--min_confs` will allow you to sweep unconfirmed outputs. We should indeed mention this explicitly in the help for the command since not all `--min_confs` flags of other commands actually support this yet.
