### ISSUE TITLE
Pending HTLCs after attempting to route self-payment to balance channels

### ISSUE THREAD

**Issue by jackgopack4** [lightningnetwork/lnd#4874]
### Background

Hi all. I was attempting to route a payment through multiple nodes from one of my channels to another one of my channels. However the operation timed out, and I attempted again. 
Now I have two pending_HTLCs on my channel, details for the channel and HTLCs below.
`"channels": [
        {
            "active": true,
            "remote_pubkey": "02f3069a342ae2883a6f29e275f06f28a56a6ea2e2d96f5888a3266444dcf542b6",
            "channel_point": "1bfad0e27923e3eaaa931ac98b59281ca1a0aa731b7e94a11893c8b880412b09:0",
            "chan_id": "726015224475615232",
            "capacity": "7000105",
            "local_balance": "2933648",
            "remote_balance": "1448477",
            "commit_fee": "35918",
            "commit_weight": "1068",
            "fee_per_kw": "33630",
            "unsettled_balance": "2582062",
            "total_satoshis_sent": "10811146",
            "total_satoshis_received": "9362668",
            "num_updates": "3009",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "1291051",
                    "hash_lock": "7d1e974290affc61ffcf6f14f7f66db2ec82e50abfc9b0b51f3ca255a89bb58f",
                    "expiration_height": 662654
                },
                {
                    "incoming": false,
                    "amount": "1291011",
                    "hash_lock": "cf5847a8669a9599a434605940a3891226047fd212a7fa724c243d46bf788df9",
                    "expiration_height": 662718
                }
            ],`

Am I SOL? Should I wait until the expiration heights pass and then attempt to close the channel? These funds should be on local side of my channel. If I broadcast the closing transaction after the expiration height with the funds on my side of the channel am I at risk of losing the entire balance to the remote node?

I apologize for my lack of experience with lnd and lncli.
### Your environment

* version of `lnd` 0.11.1-beta
* which operating system  - linux
* Bitcoin Core v0.20.1.0 bitcoind
* Umbrel lightning node
* 
### Steps to reproduce

ran rebalance_lnd script from C-otto, hit "ctrl-C" when pending route appeared to be hanging for several minutes without timing out.

I understand this is not a bug with lnd or with the above script, necessarily, but I am hoping to find out more about my paths going forward. Thank you all.

**Comment by alexbosworth** [comment]
It's normal for HTLCs to remain pending since you cannot influence them after you commit to locking the HTLC: you can't cancel them once they are in in-flight.

If there is an interruption in cooperative flows along the route it is possible that the HTLC will be forced on to the chain, however you may not see this happen on your channel but rather a simple delay in cooperate resolution of the HTLC with your peer. You don't need to do anything for this to play out except keep your node online.

**Comment by jackgopack4** [comment]
Thank you for the information.

I was able to locate the "IN_FLIGHT" transaction; since the intended recipient is myself via another of my channels, is there a way to manually locate and provide the preimage?

**Comment by alexbosworth** [comment]
You wouldn't be able to provide the preimage for an outgoing payment no. You wouldn't want to do that before you had the incoming HTLC locked to yourself because giving the preimage to your peer would mean giving them the money with no guarantee of it returning to you. A circular rebalance has two HTLCs on two channels, one pays out and one pays in. If you only have one that means that you sent one out but you don't have one coming in yet, ie you have money committed outwards but no money committed inwards. If there were two, I don't know how this specific rebalance script works but if it uses normal invoices then LND would automatically settle it and you wouldn't have to do anything.

**Comment by jackgopack4** [comment]
So if I don't see any pending HTLCs on the channel that is supposed to be "receiving" the funds or "paying in," LND will create that HTLC and settle it?

**Comment by alexbosworth** [comment]
On the inbound side of the rebalance your inbound peer would extend the HTLC to you through a channel with them and then LND would recognize that it has the preimage for that HTLC and settle it

**Comment by jackgopack4** [comment]
if there was as you said "an interruption in cooperative flows along the route" there is no way to manually correct this? 

Just trying to see if there's a way to determine at which hop the payment has stalled. Is it likely that the peer which is supposed to provide the inbound liquidity to my node at the last hop has not received/forwarded the hash? And to determine which this is?

**Comment by alexbosworth** [comment]
I think if the invoice is expired then yes your node will reject the payment even if it shows up

Determining which hop stalled the payment is not supported no. It's impossible to say what happened after the outgoing payment was committed to your peer

**Comment by jackgopack4** [comment]
Alright. So if my node has rejected the payment, what will happen to the HTLC at the timelock expiration? Forced on-chain and channel closure?

**Comment by alexbosworth** [comment]
Rejecting the payment will cancel the HTLC and then that cancellation will hopefully cascade back to you with no on-chain impact

If there is an uncooperative state between any of the peers on the route then potentially they cannot resolve it as a cancel off chain and then the HTLC will go to the chain with the force-closing of the channel it is attached to

**Comment by jackgopack4** [comment]
So if the HTLC is still pending, obviously the payment has not yet been rejected. I'll just let this ride and see what happens. I'll report back here in the next few days. Thanks, Alex.

**Comment by alexbosworth** [comment]
I would check back every 40 blocks or so, the delta between each hop. If a hop is uncooperative and it resolves on chain with a force close, it can then cancel it backwards off-chain

**Comment by jackgopack4** [comment]
so from my lnd.log it appears that they should have failed due to Temporary Channel Failure:
`[WRN] CRTR: Attempt 7203 for payment cf5847a8669a9599a434605940a3891226047fd212a7fa724c243d46bf788df9 failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0x40068a31e0)({`
would this change anything or confirm any suspicions?

**Comment by alexbosworth** [comment]
A payment hash can be canceled back to you and then re-sent out to find a new route, and if that happened due to a temporary failure like no liquidity on the route then you would see this error in the log

**Comment by jackgopack4** [comment]
That makes sense; just strange to me that it still would show as "in flight" even though the log says it was cancelled.

**Comment by alexbosworth** [comment]
There is no visible identifier for attempts, but if there were then you would probably see that one attempt was canceled and another one is in flight

**Comment by jackgopack4** [comment]
Shouldn't `lncli trackpayment` produce some sort of output or error for either transaction?

**Comment by alexbosworth** [comment]
The track payment API is designed as a streaming API which means that it will not resolve while the payment resolution is still indeterminate

**Comment by jackgopack4** [comment]
Alex, thanks again for all your help.

The HTLCs were released back to the original channel after the time lock on hop 3 of 7 expired at height 662412.

Was able to pull the info about the two transactions using `lncli listpayments --include_incomplete` to see when each step of the way expired.
