### ISSUE TITLE
lnd node not starting anymore

### ISSUE THREAD

**Issue by svpi11** [lightningnetwork/lnd#4875]
Good morning,

I have an issue since today. I've been using a lnd node very well since last summer and last october, and I just connected today again. But with the command "lnd" as usually on my terminal, I have this error:

"Attempting automatic RPC configuration to bitcoind
unable to load RPC credentials for bitcoind: unable to extract RPC credentials: unable to find rpcuser in config, cannot start w/o RPC connection"

I am using Kubuntu 20.10 latest version, Bitcoin core 0.20.1 latest version, and lnd latest stable version too.

Thanks for your help trying to understand what happen, cause I've been not using it and modifying anything since month, and it always worked perfectly.

Thank you !

**Comment by guggero** [comment]
What does your `bitcoin.conf` look like? According to the error message, you didn't configure the RPC user/password correctly for `bitcoind`.

**Comment by svpi11** [comment]
Thank you very much for the answer :) !!

I didn't modify my bitcoin.conf since months, while it was working fine before... I am traveling right now but will send the content of the file when I can. 
I didn't use PRC user/password before but a cookie based authentication by torrc file for for it, so maybe this is it.

I will check it !

Thanks ! :)

**Comment by guggero** [comment]
Going to close this for now. Feel free to re-open if you think it is a problem in `lnd`.

**Comment by svpi11** [comment]
Thank you very much for your answer !!
I was about to close it too now, I've found the solution by myself and I'm confused... Another program just simply wrote into my bitcoin.conf file without I realized it... So I removed the line of this program.

Thank you all for your answers, and sorry for the disturbing ;) 
Thanks for your work by the way !
