### ISSUE TITLE
neutrino on mainnet

### ISSUE THREAD

**Issue by nakinthorn** [lightningnetwork/lnd#4877]
i try to using neutrino for mainnet with this command
`lnd --bitcoin.active --bitcoin.mainnet --debuglevel=debug --bitcoin.node=neutrino --neutrino.connect=btcd-mainnet.lightning.computer`

and when i checked log is so good
<img width="1350" alt="Screen Shot 2563-12-21 at 18 36 50" src="https://user-images.githubusercontent.com/19216345/102773274-8db00300-43bb-11eb-90c9-36f805c64037.png">

but!!! when i try to getinfo i got this error
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

Btw,
if am using testnet it working fine...

pls help

**Comment by halseth** [comment]
make sure your `lncli` is pointing to the `mainnet` config.

**Comment by nakinthorn** [comment]
> make sure your `lncli` is pointing to the `mainnet` config.
> 
> `lncli --network=mainnet` if everyhing is default (mainnet should be the default for `lncli` though)

mainnet 100%

**Comment by nakinthorn** [comment]
Ok, i found solution
it just add --feeurl
