### ISSUE TITLE
some transaction from `listchaintxns` are not part of lnd wallet

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4880]
### Background

so there has been a transaction with 1 input (keys belong to lnd) and 2 outputs (A with keys belonging to lnd, B is an outside wallet)

when B (a "third party" input) is being spent to a third party wallet (neither input/output are part of the lnd instance), it appears in the list of `listchaintxns`.  amount is 0.

### Your environment

* version of `lnd`: 0.11.1-beta
* `bitcoind` 0.20

### Steps to reproduce

I have not try to reproduce it. I just had an issue and have dig into the logs to understand more about this unexpected behavior

### Expected behaviour

Only transactions involving one input/output of the wallet should be listed in `listchaintxns`

### Actual behaviour

Transactions that spend an output that doesn't belong to lnd should not be listed in `listchaintxns` (and not trigger onchain event related to it) even if there could be other outputs for this same transaction that belong to lnd

**Comment by halseth** [comment]
Related? https://github.com/lightningnetwork/lnd/issues/3746

**Comment by nicolasburtey** [comment]
it seems it is duplicated indeed.
