### ISSUE TITLE
local Docker volume permissions issues

### ISSUE THREAD

**Issue by sbres** [lightningnetwork/lnd#4891]
### Background

I was trying to set up an lnd demon in a docker container last month but I kept having weird issues where lnd was unable to open database files.
After checking inside the container I found out that none of the files or directories had owners.
This made me think of some issues I had before with sharing a local volume with docker on OSX.

I found a clean way of avoiding this issue and I think it would be useful to add a little paragraph to the read me for docker install instructions.
The solution is from this documentation:
https://hub.docker.com/r/linuxserver/resilio-sync

```
When using volumes (-v flags) permissions issues can arise between the host OS and the container, we avoid this issue by allowing you to specify the user PUID and group PGID.

Ensure any volume directories on the host are owned by the same user you specify and any permissions issues will vanish like magic.

In this instance PUID=1000 and PGID=1000, to find yours use id user as below:

  $ id username
    uid=1000(dockeruser) gid=1000(dockergroup) groups=1000(dockergroup)
```

Let me know if you would accept a PR for this, I'm happy to help.

**Comment by guggero** [comment]
By default the `lnd` process inside the docker images runs as root. If you change that (for example by specifying the `--user` flag with the `docker run` command) then obviously the volumes/mounts must have the correct permissions for that user.
I don't think this is `lnd` specific at all but if you think adding a sentence or two to the instructions will help future users then of course feel free to create a PR.

**Comment by Roasbeef** [comment]
Closing as this can be resolved by specifying a user manually.
