### ISSUE TITLE
Python gRPC packages import order causes segfault macOS Big Sur 

### ISSUE THREAD

**Issue by TheRebelOfBabylon** [lightningnetwork/lnd#4897]
### Background

When following the [tutorial in the repo](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md), import order of the following packages can cause a segfault:
```
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
import grpc
````
As per an [issue in the grpc repo](https://github.com/grpc/grpc/issues/24897), the fix until the next release of grpc, is to ensure the `import grpc` statement comes before any `_pb2` imports.

### Your environment

* version of `lnd`: 0.12.0-beta.rc3
* which operating system: macOS Big Sur 11.1
* version of `btcd`: 0.21.0-beta
* version of Python: 3.7.3

### Steps to reproduce

When using any version of macOS Big Sur and using any version of python > 3.6, import the gRPC packages in the order described by the tutorial [here](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md) yields a segmentation fault

**Comment by gnossen** [comment]
Just wanted to ping this issue to say that [`1.34.1`](https://pypi.org/project/grpcio/1.34.1/) has been released, which should resolve this issue. See https://github.com/grpc/grpc/issues/24897 for more details.

**Comment by guggero** [comment]
Sounds like this cannot be fixed in the `lnd` repo but by using the new [version of `grpcio`](https://pypi.org/project/grpcio/1.34.1/). Feel free to reopen if any change in `lnd` is needed after all.
