### ISSUE TITLE
Mainnet

### ISSUE THREAD

**Issue by Sjors** [lightningnetwork/lnd#490]
Just creating a placeholder ticket so I get a notification once I can try it out. I don't mind losing a small amount of bitcoin for the early adopter credit :-)

Right now if you launch `lnd --bitcoin.active --neutrino.active --neutrino.connect=faucet.lightning.community` without specifying testnet, it uses testnet anyway. I assume that's by design.

**Comment by Roasbeef** [comment]
Yes it's testnet by design. No need for a placeholder, you'll likely see the tag on this repo (if you're watching it) once we tag our beta release (along with an announcement post, etc).
