### ISSUE TITLE
Security: Verification of the Docker Image

### ISSUE THREAD

**Issue by Zetanova** [lightningnetwork/lnd#4904]
### Background

LND makes a great effort to verify the source code and build images
with `gpg` and `timestamps`  

But the new docker images hosted on docker hub  is not easily verifiable.
because of the multi-strage build, of the container site, the binaries are just copied inside.
https://hub.docker.com/layers/lightninglabs/lnd/v0.12.0-beta.rc5/images/sha256-cf51e6989e832a928cfd82e7d77341b8bb9ef29578bb6d54a3e58bcac186aaf8?context=explore

How secure is an Docker-Hub account?

### Expected behaviour

Some mechanism to verify the container image itself or at least the binaries inside the container. 

I made view month ago a docker repo found here: https://github.com/Zetanova/docker-lnd
The dockerfile is downloading the binaries and verifying them. 
Instead of compiling them without verification. 
The final stage of the current dockerfile could make the same.

Maybe there a better way to sign a container-image-hash

**Comment by guggero** [comment]
This is correct, the docker images are not yet easily verifiable.
It should be possible to produce the same binary as is produced by the release build though. I did think about this a bit already but didn't get to implementing it.

**Comment by Zetanova** [comment]
I don't really understand the purpose of verifying something with an unverified script. 

I think the sha256  of the docker-image need to be signed by roasbeef and bitconner.
Like the .tar.gz archive is signed and verified externally.

**Comment by GlenCooper** [comment]
Hmmm

**Comment by guggero** [comment]
I'm open to investigate other ways of verifying the docker images. The current approach is just the "low hanging fruit" way of getting some verification going.

I looked into "Content Trust" for docker but that seemed very cumbersome both on our end as well as the user's end.

> I think the sha256 of the docker-image need to be signed by roasbeef and bitconner.

That could be done, yes. But how would you verify this in an automated fashion? Wouldn't that also involve a script? And where would the hash/signature files reside? In the GitHub release alongside the non-docker binaries?

**Comment by Zetanova** [comment]
I think that the verifier needs to investigate the image after build time and sign the image sha256 hash. 
The signature can be distributed like the .tar.gz one over the manifest
![image](https://user-images.githubusercontent.com/1385312/106123315-11e36c00-615a-11eb-810c-7aab6150cdaf.png)

What need to be verified is the identity of the image.

It can be handled like it in an ISO distribution, 
where u can download it from an untrusted source and verify the file-hash.

**Comment by guggero** [comment]
Okay, I'll think about this a bit more. Thanks for your input!
