### ISSUE TITLE
unable to create chain control: --feeurl parameter required when running neutrino on mainnet

### ISSUE THREAD

**Issue by JavierRSobrino** [lightningnetwork/lnd#4906]
### Background

In the latest versions, Neutrino mode stopped to work. It requires --feeurl which I have no idea what it is or how to use at all, and it seems it is not documented.

### Your environment

*  lnd version 0.12.0-beta.rc5 commit=v0.12.0-beta.rc5
* Linux

### Steps to reproduce

Run lnd with neutrino.

### Expected behaviour

Run without requiring feeurl, or at least documment what is this.

### Actual behaviour

Exit with error.

**Comment by guggero** [comment]
You are correct, the description was never updated. I added a PR to fix it (and also add a valid mainnet URL to the `sample-lnd.conf` file).

**Comment by Roasbeef** [comment]
If you weren't running with that parameter before, then your node didn't do any fee estimation at all, and always defaulted to 1 sat/byte.
