### ISSUE TITLE
Can't close channels or reconnect to peers.

### ISSUE THREAD

**Issue by joaojoyce** [lightningnetwork/lnd#493]
I have some channels showing as opened but can't do any payments, can't remove/close the channels and can't reconnect to the peers. Also can't see them in the https://explorer.acinq.co.

listchannels
````
{
    "channels": [
        {
            "active": false,
            "remote_pubkey": "025eeb02baf7555a3601b9eb894319bb7db594c9be11e5b5c289938274e1752894",
            "channel_point": "2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0",
            "chan_id": "0",
            "capacity": "160000",
            "local_balance": "156380",
            "remote_balance": "0",
            "commit_fee": "3620",
            "commit_weight": "600",
            "fee_per_kw": "5000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 4
        },
        {
            "active": false,
            "remote_pubkey": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
            "channel_point": "70854d189697d5f4c6313da783c2c5d404a48c8900163e366a94d3f1676665a7:0",
            "chan_id": "0",
            "capacity": "16000000",
            "local_balance": "15996380",
            "remote_balance": "0",
            "commit_fee": "3620",
            "commit_weight": "600",
            "fee_per_kw": "5000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144
        },
        {
            "active": false,
            "remote_pubkey": "03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2",
            "channel_point": "0780274b78fe27e1574701c957469ef2ec21f9a13aab550a6faa706279ee3462:0",
            "chan_id": "0",
            "capacity": "10000",
            "local_balance": "1380",
            "remote_balance": "5000",
            "commit_fee": "3620",
            "commit_weight": "724",
            "fee_per_kw": "5000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 4
        }
    ]
}
````
Noticed that "active" is false. 

listpeers
````
{
    "peers": [
    ]
}
````

Closing a channel:
`````
channel with chan_id=782df054356abe5b2c1151676a210b0370fbbff86ea9344e957cbd3774d8bf2c not found
`````

Trying to connect to a peer:
``````
2017-12-15 10:37:37.130 [INF] SRVR: Established connection to: 77.249.29.104:9735
2017-12-15 10:37:37.226 [INF] NTFN: New spend subscription: utxo=2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0
2017-12-15 10:37:37.227 [INF] PEER: peerID(71) loading ChannelPoint(2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0)
2017-12-15 10:37:37.227 [INF] LNWL: Close observer for ChannelPoint(2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0) active
2017-12-15 10:37:37.227 [INF] BRAR: ChannelPoint(2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0) is now live, abandoning state contract for live version
2017-12-15 10:37:37.227 [INF] NTFN: New block epoch subscription
2017-12-15 10:37:37.227 [INF] NTFN: Cancelling spend notification for out_point=2cbfd87437bd7c954e34a96ef8bffb70030b216a6751112c5bbe6a3554f02d78:0, spend_id=131
``````

PS: Is there documentation where I can find some more information (message and error specification) so I can do a better job of diagnosing these myself? Where should I start in order to build knowledge so I can eventually be able to contribute to the project?

**Comment by Roasbeef** [comment]
Those channels are inactive: 
```
"active": false,
```

This means the remote peer isn't online. Additionally, those channels haven't finished the final funding state (chan_id: 0), so they're unusable as is. If you want to close them out, you need to force close (`--force`). 

There's a PR that should be merged soon (https://github.com/lightningnetwork/lnd/pull/432) which will increase the reliability of the final phase of a channel funding flow.

> Is there documentation where I can find some more information (message and error specification) so I can do a better job of diagnosing these myself? 

There's some documentation on the API calls themselves at http://api.lightning.community/. Portions of the docs are out of date currently, so they could use some updating. We're also lacking a general document on channel lifetime: funding, waiting for confirmation, sending funding locked, announcing the channel, etc. A document going over the channel lifetime would be super helpful, as I've seen it's something that users get confused with (they don't realize the channels need to confirm, etc). 

> Where should I start in order to build knowledge so I can eventually be able to contribute to the project?

I'd say you can start by reading bits of the code itself, reading our [code contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md), then starting to tackle some [of the issues tagged beginner](https://github.com/lightningnetwork/lnd/issues?q=is%3Aissue+is%3Aopen+label%3Abeginner).

**Comment by Roasbeef** [comment]
The logs on connecting to the peers look fine, does that repeat over and over again? Which commit are you running?

**Comment by Roasbeef** [comment]
Closing to clear up some clutter in the issues. If you want to discuss this further you can jump on `#lnd` on freenode, or our developer/test slack.
