### ISSUE TITLE
lncli closeallchannels        Close the failure

### ISSUE THREAD

**Issue by Fab-Kean** [lightningnetwork/lnd#4948]
"closing_txid": "",
"error": "unable to close channel: rpc error: code = Unknown desc = caveat \"time-before 2021-01-23T16:21:45.811806151Z\" not satisfied: macaroon has expired"

**Comment by Fab-Kean** [comment]
How do I update Macaroon？

**Comment by Fab-Kean** [comment]
closing_txid": "",
	"error": "unable to close channel: rpc error: code = Unknown desc = server is still in the process of starting"

**Comment by guggero** [comment]
Macaroon expired: Do you use `lncli` on another host than `lnd` is running? There might be a difference in the system clock on those two machines.
Server still in the process of starting: Check the log to see what's happening, wait until `lnd` is fully started an error goes away.

**Comment by Fab-Kean** [comment]
> Macaroon expired: Do you use `lncli` on another host than `lnd` is running? There might be a difference in the system clock on those two machines.
> Server still in the process of starting: Check the log to see what's happening, wait until `lnd` is fully started and error goes away.

I tried restarting lnd and all the synchronization was completed, but there are still problems

**Comment by Fab-Kean** [comment]
-- Logs begin at Thu 2021-01-28 13:17:01 CST. --
Jan 29 08:27:55 kldn lnd[2048]: 2021-01-29 08:27:55.155 [INF] UTXN: Attempting to graduate height=668120: num_kids=0, num_babies=0
Jan 29 08:31:49 kldn lnd[2048]: 2021-01-29 08:31:49.167 [INF] NTFN: New block: height=668121, sha=0000000000000000000cb6839f14fba1859e5276b730d85a5d00ea98a88172b9
Jan 29 08:31:49 kldn lnd[2048]: 2021-01-29 08:31:49.168 [INF] UTXN: Attempting to graduate height=668121: num_kids=0, num_babies=0
Jan 29 08:32:43 kldn lnd[2048]: 2021-01-29 08:32:43.042 [INF] NTFN: New block: height=668122, sha=00000000000000000002cadef711c4a90974619b0e6fa7b7df5a989a34247d95
Jan 29 08:32:43 kldn lnd[2048]: 2021-01-29 08:32:43.045 [INF] UTXN: Attempting to graduate height=668122: num_kids=0, num_babies=0
Jan 29 08:34:46 kldn lnd[2048]: 2021-01-29 08:34:46.957 [INF] NTFN: New block: height=668123, sha=00000000000000000008c00cc1f47988a93746d6d9580101505c5a88b079d9f8
Jan 29 08:34:46 kldn lnd[2048]: 2021-01-29 08:34:46.957 [INF] UTXN: Attempting to graduate height=668123: num_kids=0, num_babies=0
Jan 29 08:38:34 kldn lnd[2048]: 2021-01-29 08:38:34.514 [INF] NTFN: New block: height=668124, sha=00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22
Jan 29 08:38:34 kldn lnd[2048]: 2021-01-29 08:38:34.515 [INF] UTXN: Attempting to graduate height=668124: num_kids=0, num_babies=0
Jan 29 09:25:12 kldn lnd[2048]: 2021-01-29 09:25:12.168 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: server is still in the process of starting

**Comment by Fab-Kean** [comment]
-- Logs begin at Thu 2021-01-28 13:17:01 CST. --
Jan 29 09:35:23 kldn lnd[2793]: 2021-01-29 09:35:23.999 [INF] CHDB: Checking for schema update: latest_version=20, db_version=20
Jan 29 09:35:24 kldn lnd[2793]: 2021-01-29 09:35:23.999 [INF] LTND: Database now open (time_to_open=23.787841699s)!
Jan 29 09:35:24 kldn lnd[2793]: 2021-01-29 09:35:24.363 [INF] RPCS: Password RPC server listening on 127.0.0.1:10009
Jan 29 09:35:24 kldn lnd[2793]: 2021-01-29 09:35:24.364 [INF] RPCS: Password gRPC proxy started at 127.0.0.1:8080
Jan 29 09:35:24 kldn lnd[2793]: 2021-01-29 09:35:24.364 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Jan 29 09:42:30 kldn lnd[2793]: 2021-01-29 09:42:30.339 [INF] LNWL: Opened wallet
Jan 29 09:42:30 kldn lnd[2793]: 2021-01-29 09:42:30.891 [INF] CHRE: Primary chain is set to: bitcoin
Jan 29 09:42:30 kldn lnd[2793]: 2021-01-29 09:42:30.966 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
Jan 29 09:42:30 kldn lnd[2793]: 2021-01-29 09:42:30.967 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Jan 29 09:42:30 kldn lnd[2793]: 2021-01-29 09:42:30.968 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.138 [INF] LNWL: The wallet has been unlocked without a time limit
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.196 [INF] CHRE: LightningWallet opened
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.262 [INF] HSWC: Restoring in-memory circuit state from disk
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.279 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.298 [INF] HSWC: Trimming open circuits for chan_id=571843:1064:1, start_htlc_id=0
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.441 [INF] LTND: Channel backup proxy channel notifier starting
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.442 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.447 [INF] RPCS: RPC server listening on 127.0.0.1:10009
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.455 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
Jan 29 09:42:37 kldn lnd[2793]: 2021-01-29 09:42:37.542 [INF] LTND: Waiting for chain backend to finish sync, start_height=668124
Jan 29 09:42:38 kldn lnd[2793]: 2021-01-29 09:42:38.390 [INF] LNWL: Started rescan from block 00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22 (height 668124) for 3 addresses
Jan 29 09:42:38 kldn lnd[2793]: 2021-01-29 09:42:38.401 [INF] LNWL: Catching up block hashes to height 668124, this might take a while
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.451 [INF] LNWL: Done catching up block hashes
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.452 [INF] LNWL: Finished rescan for 3 addresses (synced to block 00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22, height 668124)
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.586 [INF] LTND: Chain backend is fully synced (end_height=668124)!
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.586 [WRN] HLCK: check: disk space configured with 0 attempts, skipping it
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.586 [WRN] HLCK: check: tls configured with 0 attempts, skipping it
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.618 [INF] PRNF: PeerNotifier starting
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.711 [INF] HSWC: Starting HTLC Switch
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.711 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.716 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.772 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.780 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.795 [INF] CNCT: Creating ChannelArbitrators for 1 active channels
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.802 [INF] NTFN: New spend subscription: spend_id=1, outpoint=2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1, script=0 2de4bbaee06349877f8c835d4db9de0e3a69b911d53f800d0bf260d5b0cfc62b, height_hint=668124
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.803 [INF] NTFN: Dispatching historical spend rescan for outpoint=2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1, script=0 2de4bbaee06349877f8c835d4db9de0e3a69b911d53f800d0bf260d5b0cfc62b, start=668124, end=668124
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.927 [INF] CNCT: Close observer for ChannelPoint(2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1) active
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.934 [INF] CNCT: ChannelArbitrator(2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=668124
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] BRAR: Starting contract observer, watching for breaches.
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] DISC: Authenticated Gossiper is starting
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.958 [INF] CRTR: FilteredChainView starting
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.028 [INF] CRTR: Filtering chain using 33998 channels active
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.039 [INF] CRTR: Prune tip for Channel Graph: height=573417, hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.042 [INF] CRTR: Syncing channel graph from height=573417 (hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235) to height=668124 (hash=00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22)

**Comment by Fab-Kean** [comment]
-- Logs begin at Thu 2021-01-28 13:17:01 CST. --
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.927 [INF] CNCT: Close observer for ChannelPoint(2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1) active
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.934 [INF] CNCT: ChannelArbitrator(2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=668124
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] BRAR: Starting contract observer, watching for breaches.
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] DISC: Authenticated Gossiper is starting
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.935 [INF] NTFN: New block epoch subscription
Jan 29 09:42:39 kldn lnd[2793]: 2021-01-29 09:42:39.958 [INF] CRTR: FilteredChainView starting
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.028 [INF] CRTR: Filtering chain using 33998 channels active
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.039 [INF] CRTR: Prune tip for Channel Graph: height=573417, hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.042 [INF] CRTR: Syncing channel graph from height=573417 (hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235) to height=668124 (hash=00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22)
Jan 29 10:08:38 kldn lnd[2793]: 2021-01-29 10:08:38.365 [INF] NTFN: New block: height=668125, sha=000000000000000000097df216a0d884d745d44dfdabee0cec6991f14a84b222
Jan 29 10:08:38 kldn lnd[2793]: 2021-01-29 10:08:38.502 [INF] UTXN: Attempting to graduate height=668125: num_kids=0, num_babies=0

**Comment by Fab-Kean** [comment]
lncli getinfo

"num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 1,
    "num_peers": 0,

**Comment by Fab-Kean** [comment]
best_header_timestamp": "1611886052",
    "synced_to_chain": true,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
