### ISSUE TITLE
[lncli] could not load global options: unable to decode macaroon: cannot determine data format of binary-encoded macaroon

### ISSUE THREAD

**Issue by fenngineering** [lightningnetwork/lnd#4949]
I'm experiencing the below issue when running `lncli getinfo`, as you can see in log output after the `lncli` command:

What might be the cause of this? Any help with this is much appreciated.
Thanks

**Installation of lnd**
`wget https://github.com/lightningnetwork/lnd/releases/download/v0.12.0-beta.rc6/lnd-freebsd-amd64-v0.12.0-beta.rc6.tar.gz`
`tar -xvf lnd-freebsd-amd64*`
`install -m 0755 -o root -g wheel ~/lnd-freebsd-amd64*/* /usr/local/bin`

I used a pre build binary.

**Commands**

`root@bitcoin-node:~ # lncli -lnddir "/var/db/lnd"` 
`unlock Input wallet password: lnd successfully unlocked!`

`root@bitcoin-node:~ # lncli --network=mainnet getinfo`
`[lncli] could not load global options: unable to decode macaroon: cannot determine data format of binary-encoded macaroon`

**OS**
`FreeBSD 11.3-RELEASE-p14 amd64`

**Versions**

`root@bitcoin-node:~ # bitcoind --version`
`Bitcoin Core version v0.20.1.0-g7ff64311bee570874c4f0dfa18f518552188df08`

`root@bitcoin-node:~ # lnd --version `
`lnd version 0.12.0-beta.rc6 commit=v0.12.0-beta.rc6`

**Configs**

**lnd.conf**
`[Application Options]`
`lnddir=/var/db/lnd`
`externalip=x.x.x.x`
`alias=blah`
`listen=localhost`
`restlisten=127.0.0.1:8080`
`rpclisten=127.0.0.1:10009`
`tlsextraip=0.0.0.0`

**Bitcoin.conf**
`[Bitcoin]`
`bitcoin.active=1`
`bitcoin.mainnet=1`
`bitcoin.node=bitcoind`
`bitcoin.basefee=1000`
`bitcoin.feerate=100`
`bitcoin.timelockdelta=40`

`[Bitcoind]`
`bitcoind.dir=/var/db/bitcoin`
`bitcoind.rpcuser=xxxxx`
`bitcoind.rpcpass=xxxxx`
`bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332`
`bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333`

`[tor]`
`tor.active=1`
`tor.socks=localhost:9050`
`tor.dns=soa.nodes.lightning.directory:53`
`tor.control=localhost:9051`
`tor.v3=1`

**bitcoind.conf**
`externalip=x.x.x.x`
`server=1`
`txindex=1.`
`zmqpubrawblock=tcp://127.0.0.1:28332`
`zmqpubrawtx=tcp://127.0.0.1:28333`
`rpcallowip=127.0.0.1`
`rpcbind=127.0.0.1`
`server=1`
`txindex=1`
`zmqpubrawblock=tcp://127.0.0.1:28332`
`zmqpubrawtx=tcp://127.0.0.1:28333`
`rpcallowip=127.0.0.1`
`rpcbind=127.0.0.1`
`rpcuser=xxxxx`
`rpcpassword=xxxxx.`

**Comment by guggero** [comment]
If you run the `unlock` command with `-lnddir "/var/db/lnd"`, you also need to run `getinfo` with that command. The `lnddir` isn't persisted unless you place the `lnd.conf` file in the correct default location.
