### ISSUE TITLE
Proposal:  Set default feerate to 100 ppm

### ISSUE THREAD

**Issue by begetan** [lightningnetwork/lnd#4954]
My proposal is to set the default **bitcoin.feerate=100** ppm ( which is 0.01% also) instead of the current **bitcoin.feerate=1** ppm.

Recently we have celebrated a five anniversary of the Lightning Network whitepaper. It became from an idea to a mature and robust payment network, which is attracting now serious business.

Anyway, each time when someone asks me "If I would to invest Bitcoins into the Lightning Network, how much I could earn on it?"   usually reply "You'll just lose a small amount, but if you will do anything right, you loses will be minimal." But this situation has been change dramatically last months. In the new reality Bitcoin Mempool is much expensive even at the most inactive hours. During the hot mempool hours even a cooperative (which is controlled) close of the channel may hurt you by spending all incomes earned for the month. These losses multiplied by the growing fiat exchange rate and become a real pain, especially for the newcomers.
 
While it still very important to continue development of the balanced network and circular economy of LN, the idea is very simple. We should try at least to cover a onchgain tx costs.  

Here is the analysis of the costs from the bottom and top views.

1. The minimal channel open transaction costs **154** sat. For the small routing channel size **1-2M** it means that the fee rate at 100 ppm will cover the minimal (ideal) opening cost in the scenario of the unidirection payment flow  ( which is most common case in the network now) 

2. For the big channel of 16,7M (which was the max chan size for a long time) it will be possible to collect **1600 - 2000** seats, which could be the regular cost of a channel opening.

3. From the top line we could say quite safely that having 0.1% of total fees still keeps LN very attractive to the customers, comparing to all other existing methods. Assuming the everage payment path is 5 hops, it is possible to collect **100 - 500** sats for each node in the path (depending of their role). 

4. Any kind of network optimisation for establishing a bidirection flow in channels, also investment capital to wumboo channels should provide to node operators extra profit, above the on-chain costs and force-close risks.

I had several discussion with several routing node owners. Everyone was agreed about setting proper routing fees. If we check popular and really working nodes, most of them have much higher fees than 100 ppm. In the same time a lot of big nodes with the default fees stuck in deep assymetry and have a minimal forwards. The owners of these nodes just lost incentive to enforce optimisation because it wasting of satoshis without return.

So the changing defaults will not hurt the network, but only give a chance to a newcomers to be break even while professional node operators have a chance to be profitable. I believe it will increase the growth of Lightning Network.

**Comment by xraid** [comment]
Globally there are several economies where 100 grains of rice might cost 1 satoshis and at other geolocation´s You can not get any rice for 1 satoshis, then by having a enforced minimum forward rate would work against the networks global usability. 

So there is the prospect of being able do volumes of forwards at whatever ppm You like when You the node op also create a market to serve, just lobbying for higher enforced default forwarding settings will not grow the market where You as a node op is paramount in its functioning and are also then responsible for creating the market i.e USERS to forward.

The network is not and will not be a single market but several markets with different use and so enforce minimum defaults for all would hinder the dynamics that the network are visioned to be.

A p2p micropayments network can not enable a "fee market" without a market of USERS that do use micropayments p2p.

**Comment by openoms** [comment]
I do agree that fees should generally be higher to make liquidity work more efficiently, but this is probably not the best to be dictated by the protocol and base implementation developers.
There has been a similar proposal more than a year ago: https://www.mail-archive.com/lightning-dev@lists.linuxfoundation.org/msg01484.html
to which would worth to read the answer of @Roasbeef which I presume would still apply: https://www.mail-archive.com/lightning-dev@lists.linuxfoundation.org/msg01490.html

This would not stop more specific higher layer implementations and node projects to use some higher eg. 100 ppm defaults, but that should be discussed in their individual repositories.

**Comment by Roasbeef** [comment]
> We should try at least to cover a onchgain tx costs.

Totally, routing operators should modify their fees to do this themselves. Those that don't will end up losing money, but maybe that's OK if they mainly care about helping out the network. Many routing nodes just see it as a minor hobby and don't really care about min/maxing their potential revenue earnings.

**Comment by Roasbeef** [comment]
Even if we raised default fees (which I don't think makes sense see that mailing list reply of mine) people can still run negative if they mismanage their nodes. It then follows that we won't magically make new routing nodes profitable by increasing their default fees, in order to make money you need to be committed to your node and continually examine several factors. Running a profitable routing node will never be as simple as a "set and forget".

**Comment by Roasbeef** [comment]
> I had several discussion with several routing node owners. Everyone was agreed about setting proper routing fees.

That's great, they can do so _right now_ and observe if either they make more routing fee revenue, or their volume drops off causing them to make less than if they used w/e their prior fee setting was.

**Comment by begetan** [comment]
I have an experience with aggressive rebalancing strategy. There are some of good performing channels which drain liquidity quite fast, so i set fee rate between 100 to 250 ppm for them. In the same time I have a donor channels providing me inbound capacity. Without rebelance it stuck in some position pretty fast.

I used to run rebelancing script which is acctually trying to rebalance circulary profiable channels with the X/10 fees using keysend. The success rate was around 1%, but it was enought to increase profit 5-10x times hire.

According to my understanding of network state it is a game called "catch another fool". If someone occasually opens a channel in the right direction and  set by mistake low fee, It coudbe drained in hours or even in minutes. That is my exeprience.

My current view to the  Network is a follwing Pyramid:

1. Some exchanges and big shops on the top, which have huge benefits for their main business from fast and cheap LN payments. They drain liquidity continuously from the whole network.

2. Some good operating nodes whic care about overal balance, channel rebalancing.
The nodes with a lot of funds are here also. Thouse node drains capacity form amateurs 
and have a chance to cover their on-chain cost.

3. Amateur and enthusiasts' nodes. All of them have no expertise for fee management 
and just supply liquidity up to the pyramid. They have no chance to cover opening and closing tx costs.

So the whole pyramid based on the idea of misunderstanding of the technology  and mismanaging of the enthusiasts' node.

I believe LN is mature enough to utilize a market forces and signal for it's growing. So it could be a transition from bootstrap to **reasonable defaults**

**Comment by begetan** [comment]
> Even if we raised default fees (which I don't think makes sense see that mailing list reply of mine) people can still run negative if they mismanage their nodes.

I completely agree about node mismanaging effect. Anyway we are still talking about different kind of losses, which are higher for mismanaged nodes and lower for good managed.  The only thing I want to enforce - to provide reasonable defaults which may help to cover very basic costs like channel opening TX. It may help us to move from highly negative zone to closer to zero negative.

It is normal if the developers still consider the network as hobbyist, but not for profit project. We will just continue repeating it to potential investors and new participants ;)

**Comment by Roasbeef** [comment]
> I believe LN is mature enough to utilize a market forces and signal for it's growing

Indeed, that can already be done by having users update their routing fees based on the view of the market and also the various expenses that make up their cost basis. 

> The only thing I want to enforce - to provide reasonable defaults which may help to cover very basic costs like channel opening TX. It may help us to move from highly negative zone to closer to zero negative.

There's no magic number for this. Let's say I own my hardware and have had it sitting around for years unused, in essence, I don't need to factor this into my expenses for each month for my node. On the other hand someone that's using a VPS needs to pay for CPU, disk, bandwidth, etc. There's simply no magic number that works for all cases, therefore, users need to compute their own costs and set them accordingly.

**Comment by Roasbeef** [comment]
> It is normal if the developers still consider the network as hobbyist, but not for profit project.

This depends on the _individual_. If you want to take a node seriously and earn a profit, then you need to be actively adjusting your fees and watching your chain fees to ensure that you actually make a profit. Setting the default fees to a new magic number doesn't change the current chain conditions, nor the tendency of users to not take their chain fee costs into account when attempting to bring up and maintain a new node.

**Comment by begetan** [comment]
@Roasbeef  Thank you for the clarification! I close this issue.
