### ISSUE TITLE
Makefile :58 : Recipe for target gotool.ginkgo failed

### ISSUE THREAD

**Issue by pthoti52593** [lightningnetwork/lnd#4965]
### Background
Trying to setup the block chain development using Vagrant
Describe your issue here.
As part of blockchain development Setup, trying to run make docker, it is completing with error as shown in the screenshot
### Your environment
Ubuntu 16.04-xenial
* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce
Run make docker
Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
The make docker should completed successfully
Tell us what should happen

### Actual behaviour
The make docker command completing with error
![error](https://user-images.githubusercontent.com/77593336/106097811-322d0f80-60f5-11eb-9f5b-1fc77be97399.PNG)

Tell us what happens instead

**Comment by guggero** [comment]
There is no `make docker` target...
What commit of `lnd` did you check out? What directory are you running the command in?

**Comment by pthoti52593** [comment]
Hey, Thanks for the quick response.

Below is the path where I am running make docker 

cd $GOPATH/src/github.com/hyperledger/fabric

Regards,
Pavan.

**Comment by guggero** [comment]
This isn't the hyperledger repository...
