### ISSUE TITLE
Provide detached binary signatures

### ISSUE THREAD

**Issue by setpill** [lightningnetwork/lnd#4966]
### Background

I'm trying to package the latest release for Arch (AUR package lnd-bin). ~~Unfortunately, makepkg assumes that any `somefile.txt.asc` file is a signature for `somefile.txt`, whereas the different signed manifests are now self-contained. I intend to file a bug with makepkg about this, but in the meantime, would it be possible to provide separate manifests and signatures?~~ Discussion on Arch bug tracker indicates that lnd's binary signing scheme is unsupported.

### Your environment

* version of `lnd`
    * v0.12.0-beta
* which operating system (`uname -a` on *Nix)
    * Arch 5.10.10
* version of `btcd`, `bitcoind`, or other backend
    * Not relevant

### Steps to reproduce

If needed I can share the PKGBUILD file, but it's a bit overkill to understand the problem at hand.

**Comment by guggero** [comment]
I think you can solve this by running `gpg --output manifest-<username>-<version>.txt --verify manifest-<username>-<version>.txt.asc` first. That will extract the signed manifest file and should allow you run the `makepkg` command.

If that doesn't work, I'd be interested in seeing the PKGBUILD file.

**Comment by setpill** [comment]
Unfortunately there is not much room in the PKGBUILD to execute arbitrary steps *before* the source files are automatically verified. I am currently working on a hack to trick the script into thinking it is unsigned, only to do the signature checking manually later. If that doesn't work, I'll recreate the initial "naive" PKGBUILD for v0.12.0 that breaks. In the meantime, you can see the current PKGBUILD at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lnd-bin

**Comment by setpill** [comment]
Alright, I was able to make it work. Minor security regression because now I can no longer pin the pgp pubkey fingerprints in the PKGBUILD, but that's something that needs to be fixed in makepkg.

**Comment by setpill** [comment]
Reopening because on further investigation, cleartext signatures seem to have some pitfalls.

From discussion on the makepkg [bug report](https://bugs.archlinux.org/task/69459):

> No, it's actually avoiding a pitfall of gnupg where `gpg --verify manifest-roasbeef-v0.12.0-beta.txt.asc` is ambiguous if it's validating a clear signed file or it's a detached signature of `manifest-roasbeef-v0.12.0-beta.txt`.
> 
> For detached signatures you *need* `gpg --verify manifest-roasbeef-v0.12.0-beta.txt.asc manifest-roasbeef-v0.12.0-beta.txt`, else you can encounter scenarios where it's not clear what is being authenticated.

From the gpg manpages:

> Note:  When verifying a cleartext signature, gpg verifies only what makes up the cleartext signed data and not any extra data outside of the cleartext signature or the header lines directly following the dash marker line.  The option --output may be used to write out the actual signed data, but there are other pitfalls with this format as well.  It is suggested to avoid cleartext signatures in favor of detached signatures.

I've tested and it's possible to insert lines into `manifest-roasbeef-v0.12.0-beta.txt.asc` (outside of the signed message block) without invalidating the signature. This is not possible with detached signatures. It's possible to only process the signed part with the gpg command above, but if simply verifying the clear-signed file and then `cat` ing the entire file into some command, unverified input may unexpectedly be processed.

**Comment by Roasbeef** [comment]
> (outside of the signed message block

Is this surprising behavior though? As long as the contents/hashes being changed invalidates the signature, then I'm not sure that there's an issue with it.

**Comment by setpill** [comment]
It's one of those "not surprising if you think about it but it's easy to overlook" kind of things.

**Comment by setpill** [comment]
Further discussion on the Arch bug tracker indicates that manifests are suboptimal for automated checks, as they involve either upstream-specific filtering of the manifest lines, or using insecure `--ignore-missing`, as well as needing checking that the file pointed at is not outside of the expected directory. I have now implemented the checking and filtering in the PKGBUILD for my AUR package, though this doesn't exactly make the PKGBUILD more transparent/easy to read, which is a desirable trait.

**Comment by cfromknecht** [comment]
@setpill after looking into this,  moving away from a manifest would be a much bigger change, but we've modified the signature/verification flow to use detached signatures. we're planning to tag an 0.12.1-beta.rc4 so that we can test out the new setup, would be great to get your feedback and see if this helps out your use case!

**Comment by setpill** [comment]
Can confirm this works. I noticed that @Crypt-iQ has not linked their keybase and github accounts, so I've left checking of their signature out for now.
