### ISSUE TITLE
[/lnrpc.Lightning/CloseChannel]: server is still in the process of starting

### ISSUE THREAD

**Issue by Fab-Kean** [lightningnetwork/lnd#4967]
-- Logs begin at Thu 2021-01-28 13:17:01 CST. --
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.039 [INF] CRTR: Prune tip for Channel Graph: height=573417, hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235
Jan 29 09:42:47 kldn lnd[2793]: 2021-01-29 09:42:47.042 [INF] CRTR: Syncing channel graph from height=573417 (hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235) to height=668124 (hash=00000000000000000008a748eeeb51f25ffdc3a213634fac8156c3317dd77a22)
Jan 29 10:08:38 kldn lnd[2793]: 2021-01-29 10:08:38.365 [INF] NTFN: New block: height=668125, sha=000000000000000000097df216a0d884d745d44dfdabee0cec6991f14a84b222
Jan 29 10:08:38 kldn lnd[2793]: 2021-01-29 10:08:38.502 [INF] UTXN: Attempting to graduate height=668125: num_kids=0, num_babies=0
Jan 29 10:14:05 kldn lnd[2793]: 2021-01-29 10:14:05.851 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: server is still in the process of starting
Jan 29 10:26:04 kldn lnd[2793]: 2021-01-29 10:26:04.154 [INF] NTFN: New block: height=668126, sha=000000000000000000013842cddbf62f4918c751a2fd2534e982c094c2217224
Jan 29 10:26:04 kldn lnd[2793]: 2021-01-29 10:26:04.214 [INF] UTXN: Attempting to graduate height=668126: num_kids=0, num_babies=0
Jan 29 10:30:48 kldn lnd[2793]: 2021-01-29 10:30:48.701 [INF] NTFN: New block: height=668127, sha=000000000000000000010bcaa987b59a02f085db15ff5d7a77515012d86331af
Jan 29 10:30:48 kldn lnd[2793]: 2021-01-29 10:30:48.712 [INF] UTXN: Attempting to graduate height=668127: num_kids=0, num_babies=0
Jan 29 10:33:55 kldn lnd[2793]: 2021-01-29 10:33:55.051 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: server is still in the process of starting

**Comment by Fab-Kean** [comment]
$ lncli getinfo

"num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 1,
    "num_peers": 0,
    "block_height": 668127,
    "block_hash": "000000000000000000010bcaa987b59a02f085db15ff5d7a77515012d86331af",
    "best_header_timestamp": "1611887391",
    "synced_to_chain": true,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
        {
 ],
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "12": {
            "name": "static-remote-key",
            "is_required": true,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        }

**Comment by Fab-Kean** [comment]
server is still in the process of starting
"num_inactive_channels": 1,

How to solve these problems？

**Comment by Fab-Kean** [comment]
Jan 29 16:33:22 kldn lnd[1616]: 2021-01-29 16:33:22.884 [INF] CNCT: ChannelArbitrator(2e533cdaa28fb065f502948c891699010ff6450a394a3c70b4938f7a7e563e44:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=668162
Jan 29 16:33:22 kldn lnd[1616]: 2021-01-29 16:33:22.884 [INF] DISC: Authenticated Gossiper is starting
Jan 29 16:33:22 kldn lnd[1616]: 2021-01-29 16:33:22.885 [INF] NTFN: New block epoch subscription
Jan 29 16:33:22 kldn lnd[1616]: 2021-01-29 16:33:22.885 [INF] BRAR: Starting contract observer, watching for breaches.
Jan 29 16:33:22 kldn lnd[1616]: 2021-01-29 16:33:22.969 [INF] CRTR: FilteredChainView starting
Jan 29 16:33:40 kldn lnd[1616]: 2021-01-29 16:33:40.801 [INF] CRTR: Filtering chain using 33998 channels active
Jan 29 16:33:40 kldn lnd[1616]: 2021-01-29 16:33:40.820 [INF] CRTR: Prune tip for Channel Graph: height=573417, hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235
Jan 29 16:33:40 kldn lnd[1616]: 2021-01-29 16:33:40.825 [INF] CRTR: Syncing channel graph from height=573417 (hash=0000000000000000002a0532200a4cebe918ee0987eeafe3454f519b4a4d5235) to height=668162 (hash=0000000000000000000c1e9e9b601972146aa48803500c2521a6f813df55d434)

**Comment by guggero** [comment]
Was the node down for a long time?
I see ` "synced_to_graph": false,`, that means it's still catching up. Probably will resolve itself given some time. What kind of hardware is this running on?

**Comment by Fab-Kean** [comment]
> Was the node down for a long time?
> I see ` "synced_to_graph": false,`, that means it's still catching up. Probably will resolve itself given some time. What kind of hardware is this running on?

I have been offline for two years due to some problems，Raspberry Pi 3，bitcoin core has been online, lnd offline for about two years, because there is no lncli unlock。
It’s been online for about a week now, and lnd has also synced to the latest block, but "synced_to_graph": false  。I want to know what data is still being synchronized?

**Comment by guggero** [comment]
Two years is a long time to be offline.
Your node is catching up with changes to the Channel Graph (all nodes and channels in the whole public network). Each channel opening transaction is verified against the blockchain which, on slower hardware like a Raspberry Pi, can take a long time (bitcoind needs to rescan each transaction).
If you are on `lnd v0.12.0` you can add the `routing.assumechanvalid=true` configuration option to your `lnd.conf` to speed up the process (skipping the validation).

**Comment by Fab-Kean** [comment]
> Two years is a long time to be offline.
> Your node is catching up with changes to the Channel Graph (all nodes and channels in the whole public network). Each channel opening transaction is verified against the blockchain which, on slower hardware like a Raspberry Pi, can take a long time (bitcoind needs to rescan each transaction).
> If you are on `lnd v0.12.0` you can add the `routing.assumechanvalid=true` configuration option to your `lnd.conf` to speed up the process (skipping the validation).

In theory, my lnd just hasn't synchronized the data, there are no other problems, right?

**Comment by guggero** [comment]
Correct. It just takes very long because 2 years is a lot of data to catch up with.
You can check the progress with `lncli getnetworkinfo`.
It should look something like this:
```
{
    "graph_diameter": 0,
    "avg_out_degree": 9.268611111111111,
    "max_out_degree": 1235,
    "num_nodes": 7200,
    "num_channels": 33367,
    "total_network_capacity": "104933316815",
    "avg_channel_size": 3144823.2329846853,
    "min_channel_size": "1100",
    "max_channel_size": "500000000",
    "median_channel_size_sat": "544743",
    "num_zombie_chans": "7170"
}
```
The closer your numbers of `num_nodes` and `num_zombie_chans` get to those, the closer you are to having the graph fully synced.

**Comment by Fab-Kean** [comment]
> Correct. It just takes very long because 2 years is a lot of data to catch up with.
> You can check the progress with `lncli getnetworkinfo`.
> It should look something like this:
> 
> ```
> {
>     "graph_diameter": 0,
>     "avg_out_degree": 9.268611111111111,
>     "max_out_degree": 1235,
>     "num_nodes": 7200,
>     "num_channels": 33367,
>     "total_network_capacity": "104933316815",
>     "avg_channel_size": 3144823.2329846853,
>     "min_channel_size": "1100",
>     "max_channel_size": "500000000",
>     "median_channel_size_sat": "544743",
>     "num_zombie_chans": "7170"
> }
> ```
> 
> The closer your numbers of `num_nodes` and `num_zombie_chans` get to those, the closer you are to having the graph fully synced.

**Comment by Fab-Kean** [comment]
> > Correct. It just takes very long because 2 years is a lot of data to catch up with.
> > You can check the progress with `lncli getnetworkinfo`.
> > It should look something like this:
> > ```
> > {
> >     "graph_diameter": 0,
> >     "avg_out_degree": 9.268611111111111,
> >     "max_out_degree": 1235,
> >     "num_nodes": 7200,
> >     "num_channels": 33367,
> >     "total_network_capacity": "104933316815",
> >     "avg_channel_size": 3144823.2329846853,
> >     "min_channel_size": "1100",
> >     "max_channel_size": "500000000",
> >     "median_channel_size_sat": "544743",
> >     "num_zombie_chans": "7170"
> > }
> > ```
> > 
> > 
> > The closer your numbers of `num_nodes` and `num_zombie_chans` get to those, the closer you are to having the graph fully synced.

 $ lncli getnetworkinfo
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by guggero** [comment]
Is your node restarting/crashing? It seems you were able to run `lncli` commands earlier? Also make sure you update your version to at least `v0.11.1-beta` or `v0.12.0-beta` (preferred).

**Comment by Fab-Kean** [comment]
> Is your node restarting/crashing? It seems you were able to run `lncli` commands earlier? Also make sure you update your version to at least `v0.11.1-beta` or `v0.12.0-beta` (preferred).

lnd --version
lnd version 0.12.0-beta.rc6 commit=v0.12.0-beta.rc6

Then I will try to execute again later     lncli getnetworkinfo

**Comment by guggero** [comment]
Please refer to our Slack for further questions/debugging: https://lightning.engineering/slack.html

Noting I've seen so far sounds like a bug in `lnd`, going to close the issue now.
