### ISSUE TITLE
CMGR: Can't accept connection: chacha20poly1305: message authentication failed

### ISSUE THREAD

**Issue by whizz** [lightningnetwork/lnd#497]
I don't know if this is actually a problem, but every now and then the log contains this message.

```
2017-12-18 10:39:58.600 [ERR] CMGR: Can't accept connection: chacha20poly1305: message authentication failed
```

As there is no other detail in the log, I cannot determine what authentication failed and why. Maybe at least the error message should be clearer as what to do about it. 

I am able to connect to peers.

**Comment by Roasbeef** [comment]
There's no issue there. That's just the way that [`brontide`](https://github.com/lightningnetwork/lightning-rfc/blob/master/08-transport.md) works: if the connecting party doesn't know your pubkey, then you won't connect to them. 

On the network as is, this can happen if you've wiped your state in the past and have a new public key, yet older nodes are still trying to connect using your prior public key.

**Comment by MasterNeuron** [comment]
> There's no issue there. That's just the way that [`brontide`](https://github.com/lightningnetwork/lightning-rfc/blob/master/08-transport.md) works: if the connecting party doesn't know your pubkey, then you won't connect to them.
> 
> On the network as is, this can happen if you've wiped your state in the past and have a new public key, yet older nodes are still trying to connect using your prior public key.

And this error will still forever for older nodes? Then this will be an issue...

**Comment by Roasbeef** [comment]
> And this error will still forever for older nodes? Then this will be an issue...

Error for ever? If I open up a socket to your node, and try to send let's say TLS traffic, you'll get this issue. This can also arise if someone is port scanning you in an attempt to see what network facing services you're running.

**Comment by MegalithicBTC** [comment]
Sorry to resurrect, but we are clearly being port scanned and see a zillion of these messages in our console. It's tricky, because I don't want to block `[ERR] CMGR` messages in the logs, right? Maybe someone has found a workaround? Currently it's making using the logs challenging.

**Comment by guggero** [comment]
The `CMGR` is the [`btcd` connection manager](https://github.com/btcsuite/btcd/blob/master/connmgr/connmanager.go) and as far as I can see it only logs messages related to connection establishment events.
So if you're not experiencing issues with other peers in general and don't need that log turned on, you can append `,CMGR=critical` or `,CMGR=off` to your log level to get rid of the spam.

Another option would be to downgrade [this log line](https://github.com/btcsuite/btcd/blob/master/connmgr/connmanager.go#L503) to `log.Warnf()` with a PR, then you could still run with `CMGR=error`.

**Comment by MegalithicBTC** [comment]
Thanks, confirmed that this clears up the log spamming.
