### ISSUE TITLE
[doc v0.12.0-beta release notes] Actual GPG Key for roasbeef mismatches the release notes

### ISSUE THREAD

**Issue by nolim1t** [lightningnetwork/lnd#4970]
I'm trying to build and furthermore also trying to verify the keys against the keys pulled from keybase and the key for @Roasbeef in keybase doesn't seem to match whats in the release notes.

With the `lncm/docker-lnd` project we try to verify before we build.

The key fetched from roasbeef's keybase profile is `E4D85299674B2D31FAA1892E372CBD7633C61696` but in the release notes this key is `4AB7F8DA6FAEBB3B70B1F903BC13F65E2DC84465`

As not to trust but to verify, would like to know if there is something being compromised here or not.

**Comment by Roasbeef** [comment]
The release notes are outed, the section for the verification of the tag was also outed. Notice the dates now also reflect when the signatures were generated. 

Thanks for catching this!

**Comment by nolim1t** [comment]
Is keybase out of date?

**Comment by Roasbeef** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

No, the release notes were incorrect. Keybase has the correct key. 

The release is signed with: 60A1FA7DA5BFF08BDCBBE7903BBD59E99B280306

Which is a subkey of: E4D85299674B2D31FAA1892E372CBD7633C61696
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEYKH6faW/8Ivcu+eQO71Z6ZsoAwYFAmAVw1UACgkQO71Z6Zso
AwaTQxAAoxt/RWVMtmcQ1g8AXwhxHQJbtIelbNO/BFw0DMYnv7ufBcQzWdL04ty5
5CSOqfgwX+Zjs9aZBu5/oPX5X5lTa9ZxcOC+Rj4OhJsZhFTNQtUGedi2FC9cptEt
OkpvRozrNZgefZUUh115Jd7jt++FiYPvlLDIjqn7Kv7mMpd1JL2ZuUW/pWqkYmVl
4+xbCNSrZhzN+8q4UrSVJs4xLdvY/6RVONDoEWcDvY1oPrs5JPpTIFXBH1penbdd
S4tmR9xeKk9MNyzh/b8vd6I41VG9fB8FNbd8Tz/OVV6qq6iCfTYPpKbNLIHrTvoB
Q3tzpXvLs+315jxdiwGHXAT/1KaLPejvwlEeCCl6Th0+eb8AfR2mJ4PCxFV2H5u/
ey1CO8eeIQz1ZVP9fdAgiM5Xo6d3YoMDqOgAcILRa8WOVIMOgJd554afRdQKqvtM
CWJnAoR5vcY4dZx7mme2LDaZyI8XYgpwuutERerQHc6TXDZ1tc7obkiU6F009Tbx
M0jqfDohCIiJIFwwLZWDAtpbcFB3uhO/L5RHlpzaMzUvOjDdMpAGPXEPV7vARyyR
jlJfZQy1yKRO6sEVHKg1Ow9CTMr0hlhQMsUC2oKW4G8xyPsIBc0D3BooXh9u2EkQ
XnEd13hgq+w2OXTomxCuYs2sqK3lgUr6EV0zEaRdbtJDea12Cpo=
=TiP6
-----END PGP SIGNATURE-----

**Comment by Roasbeef** [comment]
The latest entry in my keybase sigchain adding the key used to generate the signature above: https://keybase.io/roasbeef/sigchain#274adb8168811ad54bfefaabc314ba0f7f99d34cb269d41b42848464d7854e530f
