### ISSUE TITLE
Create Wallet : lncli create - transport: authentication handshake failed: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by GraemeConradie** [lightningnetwork/lnd#4971]
### Background

In creating a new wallet, I get "x509: certificate signed by unknown authority"

### Your environment

* lnd version 0.12.0-beta commit=v0.12.0-beta-22-g10a81e01
* Linux earth 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* "version": 210000,
  "subversion": "/Satoshi:0.21.0/",
  "protocolversion": 70016,
* go version go1.15.6 linux/amd64

### Steps to reproduce

* Install go
* Build LND from source
* Configure lnd with BTC
* Create Wallet

### Expected behaviour

Wallet created successfully

### Actual behaviour

Wallet creation fails

**Comment by GraemeConradie** [comment]
As described here : https://github.com/lightningnetwork/lnd/issues/1980, local RCP and macaroon paths.

**Comment by mikkoc** [comment]
@GraemeConradie what was your solution? I'm running into the same issue but can't figure out what's wrong. I'm not generating any custom certs, and rpc server is running, as far as I can tell.
```
 netstat -tlpn | grep lnd
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      25025/lnd
tcp        0      0 127.0.0.1:10009         0.0.0.0:*               LISTEN      25025/lnd
```

**Comment by guggero** [comment]
Make sure you provide the correct `--tlscertpath` parameter when using `lncli`.
