### ISSUE TITLE
Enable Tor v3 address support for Neutrino client mode

### ISSUE THREAD

**Issue by bitcoinlizard** [lightningnetwork/lnd#4973]
### Background

Tor v3 address are not supported in Neutrino client mode.  This is discussed in the first comment here:

https://github.com/lightningnetwork/lnd/pull/4806

This is more relevant as bitcoind recently released version 0.21.0 which adds support for serving compact filters to peers.  Bitcoind also switched to Tor v3 addresses as a default in version 0.21.0 (older versions only supported v2).  Enabling Tor v3 address support could increase the number of Neutrino mode LND nodes deployed as there would be many more backends available.

**Comment by Roasbeef** [comment]
Note that in order to implement this, we'll need to implement the new `addrv2` scheme within the `btcsuite` set of libraries. After we do that, `neutrino` will get this feature "for free".

**Comment by openoms** [comment]
Would like note that there is a time limit here:

https://blog.torproject.org/v2-deprecation-timeline
```
3. October 15th, 2021
We will release new Tor client stable versions for all supported series that will disable v2.
 ```

**Comment by Roasbeef** [comment]
We're aware of the time limit, but unfortunately this won't make it into 0.14 as slated. See the newly created milestone that tracks this inclusion. 

As usual: contributions are accepted here. BIP 155 isn't too involved, but this fell through the cracks somewhat w/ all the other PR/issues and priorities.

**Comment by Roasbeef** [comment]
Note that I _have_ started a BIP 155 implementation, pretty confident I can finish it before the end of October (see the milestone this issue is attached to).

**Comment by nochiel** [comment]
> Note that I _have_ started a BIP 155 implementation, pretty confident I can finish it before the end of October (see the milestone this issue is attached to).

So, does this mean you don't need any help. That is, how can I help?

**Comment by Roasbeef** [comment]
Update on this: we're in active testing, a PR should be up in the next few days!

**Comment by Roasbeef** [comment]
The `btcd` PR (where most of this code lives), is here: https://github.com/btcsuite/btcd/pull/1812

**Comment by Roasbeef** [comment]
PR has been merged, so this is only blocked on the updates to the `neutrino` package.
