### ISSUE TITLE
Unable to start lnd unable to load RPC Credentials (bitcoind)

### ISSUE THREAD

**Issue by DakksNessik** [lightningnetwork/lnd#4975]
### Background

When attempting to start lnd I get the following message "unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpcpass,...". After several attempt to get the bitcoind.rpcuser bitcoind.rpcpass configs to work, however have not been successful.

Attempted:
 - Changing the password to not include Special Characters
 - Encapsulating the password in single and double quotes(bitcoind.rpcpass='kek' or bitcoind.rpcpass="kek")
 - Having lnd read the bitcoin.conf file both with "rpcauth=user:hash" and "rpcuser=kek rpcpassword=kek"

### Your environment

* lnd version: v0.12.0-beta
* os: Debian 10
* bitcoind version: v0.21.0
* environment details:
* lnd.conf:
```ini
[Application Options]
tlsextraip=1.2.3.4
tlsextradomain=example.net
tlsautorefresh=true
letsencryptlisten=0.0.0.0:8081
letsencryptdomain=example.com
listen=0.0.0.0:9735
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
externalip=example.onion
externalip=1.2.3.4
externalip=example.com
[Bitcoin]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpcuser=kek
bitcoind.rpcpass=kek
[tor]
tor.active=true
tor.socks=9050
tor.streamisolation=true
tor.control=localhost:9051
[watchtower]
watchtower.active=true
watchtower.listen=0.0.0.0:9911
watchtower.externalip=example.onion
watchtower.externalip=1.2.3.4
watchtower.externalip=example.com
[wtclient]
wtclient.active=true
```

* bitcoind.conf:
```ini
daemon=1  
txindex=1  
bind=0.0.0.0  
bind=127.0.0.1:8334=onion  
discover=0  
externalip=example.onion  
externalip=1.2.3.4  
externalip=example.com  
listenonion=0  
onion=localhost:9050  
proxy=localhost:9050  
server=1  
rest=1  
rpcbind=0.0.0.0  
rpcauth=kek:kekhash  
disablewallet=1
```

### Steps to reproduce

Start bitcoind using = `/usr/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/etc/bitcoin/bitcoin.conf -datadir=/var/lib/bitcoind`

Start lnd useing = `/usr/bin/lnd -daemon --configfile=/etc/lnd/lnd.conf --lnddir=/var/lib/lnd`

Let me know if I can provide additional information.
I will continue to keep searching for answers, however any assistance or insight you can provide would be appriciated.

**Comment by wpaulino** [comment]
Looks like your configs are missing the ZMQ options `zmqpubrawblock=tcp://127.0.0.1:28332` and `zmqpubrawtx=tcp://127.0.0.1:28333`.

**Comment by DakksNessik** [comment]
Thank you for the information that worked. This was on me, my brain read one or the other and not all or none.
