### ISSUE TITLE
rpc: Inconsistent behavior between 'openchannel' and 'closechannel' CLI options format

### ISSUE THREAD

**Issue by wankerstar** [lightningnetwork/lnd#4977]
### Background

If I run:
lncli openchannel ADDR --local_amt AMT --sat_per_byte=25
Things work as expected.

However, if I run:
lncli closechannel ADDR --sat_per_byte=25
"sat_per_byte" gets ignored completely unless placed before the ADDR.

I can understand if the spec is for the options to precede the address, but either way the behavior should be consistent between commands.

Thanks!

### Your environment

lncli version: "0.12.0-beta"
OS: Raspbian

### Steps to reproduce

Run a closechannel command with sat_per_byte specified after the address, observe that the argument is ignored. Meanwhile openchannel respects arg in same format.

### Expected behaviour

Commands should behave the same.

### Actual behaviour

They do not.

**Comment by ErikEk** [comment]
Something strange is going on here. You're right, it ignores sat_per_vbyte if it is placed after ADDR. I'll look into it.

**Comment by ErikEk** [comment]
sat_per_byte is deprecated. I had no issues with sat_per_vbyte.

**Comment by yyforyongyu** [comment]
As mentioned by @ErikEk , `sat_per_byte` is deprecated, please use `sat_per_vbyte` instead.

**Comment by Roasbeef** [comment]
Closing based on the above contributor responses.
