### ISSUE TITLE
lncli can't set the wallet password at lnd startup. unlock ,too

### ISSUE THREAD

**Issue by ghanavati27** [lightningnetwork/lnd#498]
Error message is "Input wallet password: [lncli] The handle is invalid."
Lines: 748,755,788 in https://github.com/lightningnetwork/lnd/blob/master/cmd/lncli/commands.go
need to change from
pw, err := terminal.ReadPassword(0)
to
pw, err := terminal.ReadPassword(int(syscall.Stdin))
also, import "syscall" at top of file.

**Comment by halseth** [comment]
Thanks! I Googled this and it seems this is an issue on Windows?

I think the fix you suggested should work :)

**Comment by ghanavati27** [comment]
Yes, i tested it on windows.
I fixed it by changing 0 to int(syscall.Stdin)
see https://golang.org/pkg/syscall/#pkg-variables
also , zero is true value. but i don't know why in windows in not true.

**Comment by ghanavati27** [comment]
However , int(syscall.Stdin) will work in all systems.

**Comment by coonce** [comment]
@ghanavati27 - Thanks for the fix! It seems that Windows always needs a little extra attention. :)

**Comment by halseth** [comment]
Closed by #499
