### ISSUE TITLE
lnd 0.12 exits prematurely with fatal error 

### ISSUE THREAD

**Issue by Stronzo-sky** [lightningnetwork/lnd#4984]
### Background

LND got panic (probably due to attempt of circular rebalance) and i can not restart it. It continuously has fatal error.

### Your environment

* version of `lnd`: 0.12 beta
* which operating system (`uname -a` on *Nix): Ubuntu 18.04.2 LTS
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v0.19.1
* any other relevant environment details

### Steps to reproduce

start lnd, unlock lnd, here LND stdout stops and throws an error
...
2021-02-05 12:53:25.933 [INF] CRTR: Syncing channel graph from height=669208 (hash=0000000000000000000101c5a32880f1a872bcab6eacaed3d241fbb21c51937d) to height=669217 (hash=0000000000000000000a528c3a4c68d2fbf02ab75c614e2748bbf1a47c364161)
2021-02-05 12:53:29.080 [INF] CHDB: Pruned unconnected node 0275ce589c2f41adbaf6112389f6007dd2ba704c4dfe1b166c5c8e9a3164f824a5 from channel graph
2021-02-05 12:53:29.080 [INF] CHDB: Pruned 1 unconnected nodes from the channel graph

unexpected fault address 0xa7b75044
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa7b75044 pc=0x8359df3]
...

### Expected behaviour
Normal start of LND wo

### Actual behaviour

I`m getting an error:
[debug.log](https://github.com/lightningnetwork/lnd/files/5932622/debug.log)

**Comment by guggero** [comment]
What system architecture are you running `lnd` on? Is it possible it's an ARM machine and your `channel.db` file is close to or over 1 GB in size?

If not, a SIGSEGV usually is an indication of data corruption. Can you start again with `--db.bolt.auto-compact` to see if the compaction fixes the problem?

**Comment by Stronzo-sky** [comment]
File sizes:
-rw-rw-r-- 1  1073733632 Feb  5 13:32 channel.db
-rw------- 1           8 Jan 29 17:13 channel.db.last-compacted

LND is running on a kvm virtual machine with 2gb ram

db.bolt.auto-compact=true is already set in lnd.conf

**Comment by guggero** [comment]
Try removing the `channel.db.last-compacted` file and restart `lnd` to trigger the compaction again.
If the problem persists, try giving the VM more RAM.

**Comment by Stronzo-sky** [comment]
Actually i`ve managed to proceed furher without errors after restarting bitcoind service (which is running on a remote server) - i was just restarting everuthing i could. For now lnd is still syncing with graph, hope it will finish it successfully.

**Comment by Stronzo-sky** [comment]
> Try removing the `channel.db.last-compacted` file and restart `lnd` to trigger the compaction again.
> If the problem persists, try giving the VM more RAM.

Looks like just removing `channel.db.last-compacted` file worked for me (without adding memory, but still will add later as i saw that its close to the limit and using swap during compaction procedure). Node is slowly coming up, i already have some channels in the active state. Many thanks guggero!
