### ISSUE TITLE
Tune aggressiveness of graph sync throttling to avoid too-long disables after node restarts

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4986]
### Background

When restarting LND, peers will begin to mark the node as disabled as it is offline. After 0.12.0 I've noticed that disable flag flipping sometimes requires a much more extended wait time, leading to unusable channels for long periods of time in spite of being actively connected.

### Your environment

* LND 0.12.0-beta

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/5006.
