### ISSUE TITLE
Invoice HTLC shards should not remain in ACCEPTED state after cancelation

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4987]
### Background

As currently designed in the invoices RPC: invoices enter an ACCEPTED state when HTLCs are held but not yet settled with the preimage. This is designed to allow a caller to know when HTLCs are safely held and that they can settle with a preimage.

However if the preimage is never provided, the HTLCs will never leave this ACCEPTED state even though after a timeout they will no longer be able to be claimed

Ideally the surfaced state of the HTLC would indicate a different state to the RPC caller to disambiguate between "able to be settled" and "no longer able to be settled"

### Your environment

* LND 0.12.0-beta

**Comment by joostjager** [comment]
Related: https://github.com/lightningnetwork/lnd/issues/4587

The original idea was to create a watcher that cancels back these htlcs right before the time out. That will also prevent the channel from force-closing. In that case, probably no new rpc state is needed.

**Comment by Roasbeef** [comment]
> The original idea was to create a watcher that cancels back these htlcs right before the time out. That will also prevent the channel from force-closing. 

Seems we can just extend the _existing_ invoice expiry watcher to add hodl invoices, but with a slightly different expiration value? 

Actually why isn't that sub-system already handling this case?

**Comment by joostjager** [comment]
So there are indeed three things to watch for:
- invoice expiry
- mpp release
- hodl invoice release

>Actually why isn't that sub-system already handling this case?

I don't remember exactly why we didn't use the invoice expiry watcher for mpp releases. Maybe it had to do with certain data not being available easily.

**Comment by carlaKC** [comment]
Right now we're trying to cancel the invoice, but in the case where we've accepted the htlc we hit a [specific case](https://github.com/lightningnetwork/lnd/blob/56b61078c5b2be007d318673a5f3b40c6346883a/invoices/invoiceregistry.go#L1116) that doesn't cancel accepted invoices (with the exception of [keysend](https://github.com/lightningnetwork/lnd/blame/56b61078c5b2be007d318673a5f3b40c6346883a/invoices/invoice_expiry_watcher.go#L172)). 

The logic to not cancel was introduced in #3694. I'd imagine that the intention was to leave cancelling hodl invoices up to the caller, but now we can't cancel them on expiry. I think that it's a reasonable change to allow cancelling of hodl invoices once they're expired, but could be missing some of the original reasoning there. @bhandras or @joostjager do you remember why we didn't want to auto-cancel hodl invoices?

**Comment by joostjager** [comment]
The reason not to auto-cancel is that a hodl invoice may be held long after the invoice expiry. For example in an off-chain to on-chain swap, the off-chain invoice may have a standard 3600 sec expiry, but once it is accepted, it may take many blocks to finally learn the preimage that allows it to be settled.

**Comment by carlaKC** [comment]
Had deeper look at this, and I think that the only case we're not covering is when the htlc goes to chain and then the timeout expires (which would be the case for hodl invoices that we fail to cancel, or a regular invoice when we hit chain between accept and settle). @alexbosworth do you remember if you've specifically seen this for invoices that are resolved on chain?

When we timeout an incoming htlc on-chain ([1](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/htlc_incoming_contest_resolver.go#L120)/[2](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/htlc_incoming_contest_resolver.go#L333)), we just mark the resolver as complete without signalling back to the invoice that we can no longer settle the invoice, so the htlcs stay open. We deliver updates to invoices (manual settle/fail) uni-directionally from invoices -> contractcourt through the [`hodlSubscriptions`](https://github.com/lightningnetwork/lnd/blob/fd76b879a2dabba185c9249ee2f711a3604e3c37/invoices/invoiceregistry.go#L1134) notification system. Options to address this could be: 
1. Introduce a block based invoice expiry watcher which cancels these htlcs when their expiry height is reached (could also prevent force-close for hold invoices, perhaps on an opt-in basis)
2. Establish contractcourt -> invoice registry communication which cancels the invoices once they're expired on chain

**Comment by alexbosworth** [comment]
I believe they resolved on-chain and the timeout expired

**Comment by joostjager** [comment]
Linking related issue https://github.com/lightningnetwork/lnd/issues/4587

**Comment by alexbosworth** [comment]
Should note not only did they expire the funds also were pulled back via the timeout path
