### ISSUE TITLE
Cannot build image due to domain resolving issue

### ISSUE THREAD

**Issue by MrLouzao** [lightningnetwork/lnd#4990]
### Background

When trying to build the image on Docker build, the domain `github.com` is not resolved and I obtain an error. As a result, I cannot build the image.

### Environment

* lnd v0.11.1-beta
* MacOS Catalina 10.15.7. Darwin BTSWSTRMD6R.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
* Docker version 19.03.13, build 4484c46d9d

### Steps to reproduce

1/ Download the repository
2/ Execute `docker build --tag=mrlouzao/lnd --build-arg checkout=v0.11.1-beta .`

### Actual behaviour

The build process starts and fails when reaching the clone from github statement.

```
...
#6 3.497 (37/37) Installing alpine-sdk (1.0-r0)
#6 3.503 Executing busybox-1.32.1-r2.trigger
#6 3.511 OK: 210 MiB in 52 packages
#6 3.572 Cloning into '/go/src/github.com/lightningnetwork/lnd'...
#6 3.631 fatal: unable to access 'https://github.com/lightningnetwork/lnd/': Could not resolve host: github.com
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apk add --no-cache --update alpine-sdk     git     make     gcc &&  git clone https://github.com/lightningnetwork/lnd /go/src/github.com/lightningnetwork/lnd &&  cd /go/src/github.com/lightningnetwork/lnd &&  git checkout $checkout &&  make release-install]: runc did not terminate sucessfully
```

### Another Notes

It seems like there is a problem with the base docker image. I've created my own image of Docker with base image `openjdk:8-jdk-alpine` and when invoking `RUN ping google.com` and `RUN ping github.com` it works perfectly.

However when I do the same with `golang:1.15.7-alpine`, for `RUN ping google.com` works, but for `RUN ping github.com` it doesn't.

So I conclude that there is a problem with the domain resolution of `github.com` for this image, but not for other domains.

**Comment by guggero** [comment]
This seems to be a common problem on MacOS for some reason. I'm not sure if the `alpine` base image could be the problem: https://github.com/gliderlabs/docker-alpine/issues/539

We've found that adding some DNS servers to your `daemon.json` (either `/etc/docker/daemon.json` or `~/.docker/daemon.json` depending on your system) fixes the issue:
```
{
    "dns": ["1.1.1.1", "8.8.8.8"]
}
```

**Comment by guggero** [comment]
The `release-install` method didn't exist in `v0.11.1-beta` yet. Try `docker build --tag=mrlouzao/lnd --build-arg checkout=v0.12.0-beta .`

I'm closing the issue since the DNS resolution problem isn't anything that should be fixed in our repo. Feel free to comment again if you run into further problems though.
