### ISSUE TITLE
SIGTERM is not passed through lnd when using Docker/Kubernetes

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4994]
### Background

using lnd in a kubernetes container. lnd doens't shutdown itself when doing `kubectl delete pod lnd`

### Your environment

* version of `lnd`: 0.12
* which operating system (`uname -a` on *Nix): kubernetes on gcloud. 
* version of `btcd`, `bitcoind`, or other backend. bitcoind.
* docker Image: lightninglabs/lnd/v0.12.0-beta

### Steps to reproduce

Run lnd in a dockerized environment in kubernetes.
run `kubectl delete pod lnd`

see the container as 'terminating' yet lnd continue as normal when looking at the log.

### Expected behaviour

when receiving SIGTERM, lnd should shut down itself, so that a SIGKILL is not needed.

### Actual behaviour

lnd doesn't shutdown after SIGTERM
need to force pod shutfown with `kubectl delete pod lnd --force`

**Comment by guggero** [comment]
I've been running `lnd` in a dockerized setup for many years now and never had problems like that.
We've also had no problems with running that exact image on a k8s cluster.

Can you please check your logs if you see the following message?
```
LTND: Received terminated
```

If you see that then `lnd` did receive the SIGTERM signal but something else is blocking the shutdown. More logs would then be helpful.

**Comment by nicolasburtey** [comment]
I had looked at the log and don't see any `LTND: Received terminated`. Looking at the logs it felt lnd was continuing as if it didn't know the pod was in a terminating stage.

The repo with the charts and associated yaml will be open sourced in the next week or so. I'll paste a link here when it's available. It could be the best way to debug this, but if you have other ideas on how to debug this in the meantime, happy to provide more info

**Comment by guggero** [comment]
The only thing I can think of that would prevent the SIGTERM to be handed to `lnd` is if you overwrite the `--entrypoint`. It might be called differently on k8s.
If you have a script there or other commands then you need to invoke `lnd` by using `call lnd ...` which will then forward the signals.

**Comment by nicolasburtey** [comment]
ahh right. it's probably this then:

```
...
      containers:
        - name: lnd-container
          command: ["/bin/sh","-c"]
          args: ["lnd & /root/unlock.sh"]
...
```

how do you handle the unlock? manually? for a side container?

**Comment by nicolasburtey** [comment]
unlock.sh:

```
    #!/bin/sh
    status=1
    while [ $status -ne 0 ]
    do  
      sleep 5
      output=$( (echo $LND_PASS | lncli unlock --stdin;) 2>&1 )
      status=$?
    done
    echo "[UnlockScript] wallet unlocked, script exiting"
    sleep infinity
```

**Comment by guggero** [comment]
Yes, that looks like it might be the problem. Perhaps move the call to `lnd` inside the script as well?
E.g:
```
...
      containers:
        - name: lnd-container
          command: ["/root/unlock.sh"]
...

...
    #!/bin/sh
    call lnd &

    status=1
    while [ $status -ne 0 ]
    do  
      sleep 5
      output=$( (echo $LND_PASS | lncli unlock --stdin;) 2>&1 )
      status=$?
    done
    echo "[UnlockScript] wallet unlocked, script exiting"
    sleep infinity

```

We are running a sidecar container that unlocks `lnd` whenever needed. We're planning on publishing that soon along with our cluster helm charts. But it'll probably take a bit more time.

**Comment by nicolasburtey** [comment]
ok for now, I'll be using this hack script:

```
    #!/bin/sh
    echo "launching lnd + unlock script"

    exit_script() {
      echo "Exit script"
      trap - SIGINT SIGTERM # clear the trap
      kill -- -$$ # Sends SIGTERM to child/sub processes
    }

    trap exit_script SIGINT SIGTERM

    lnd &
    status=1
    while [ $status -ne 0 ]
    do
      echo "entering loop"
      sleep 5
      output=$( (echo $LND_PASS | lncli unlock --stdin;) 2>&1 )
      status=$?
    done
    echo "[UnlockScript] wallet unlocked, exiting loop"
    sleep infinity &
    wait
```

using trap I can send the SIGTERM signal to lnd. 

using a sidecar didn't seem that straightforward because sidecar needs to rely on the macaroon and the tls, and those are unknown if it's lnd first start until the container is running, so it can't be injected in a sidecar. I'd be curious how you are managing this but for now this resolves my issue. thanks!
