### ISSUE TITLE
Retry rescan if RPC fails for getblock

### ISSUE THREAD

**Issue by dr-bonez** [lightningnetwork/lnd#4995]
### Background

I use [btc-rpc-proxy](https://github.com/kixunil/btc-rpc-proxy) as a backend for LND in order to enable pruning. Sometimes it fails to fetch a block that is already pruned due to spurious network errors. In this situation LND will stop the rescan, after logging `Unable to complete chain rescan: -1: Block not available (pruned data)`.

### Your environment
LND 0.11.1
`Linux 007a88073044 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l Linux` (Alpine 3.12 arm32v7)
[btc-rpc-proxy v0.2.4](https://github.com/Start9Labs/btc-rpc-proxy/tree/feature/bip155)

### Expected behaviour

After getting an error from getblock, should try again after a cooldown

### Actual behaviour

Rescan fails, entire lnd node needs to be restarted to get it to retry.

**Comment by Roasbeef** [comment]
> Sometimes it fails to fetch a block that is already pruned due to spurious network errors.

Seems like it should instead _mask_ this error? 

If you run lnd 0.12, then you can enable the chainbackend health check, with this on, `lnd` will shutdown (ideally to be restarted) if it's unable to reach the backend.

**Comment by dr-bonez** [comment]
What do you mean by mask the error? Is there a different error message it should return that will cause LND to retry? Or are you suggesting that it retry synchronously under the hood if it failed to fetch the block?

**Comment by Roasbeef** [comment]
> Or are you suggesting that it retry synchronously under the hood if it failed to fetch the block?

Yeah I mean this. `lnd` will shutdown if the backend itself fails to respond w/ 0.12.0+.

**Comment by dr-bonez** [comment]
Ok, will do. But just a note, this will only work well if `lnd` does not have a timeout on rpc calls to bitcoin core.

**Comment by 3nprob** [comment]
@dr-bonez I guess this is kind of a duplicate of #5661

As noted there, this should be fixed in next release. If you want to try my fix, you can build this branch based on `v0.14.2-beta`: https://github.com/3nprob/lnd/tree/dev-0.14.2
