### ISSUE TITLE
Add database versioning 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#50]
Currently, there isn't an upgrade mechanism in place within the database which makes the current schema rigid and upgradeable. To remedy this, a new bucket should be added to the database (`metaBucket`) which stores key that house meta-data related to the current/version state of the database. 

The `createChannelDB` method should be modified to create this new bucket+key during initializing. In a similar vein, when opening the database, the `dbVersionKey` should be read from the `metaBucket` and compared against some compile-time constant which stores the _latest_ known database version. If the two versions differ (after some future database update/migration), logic should be inserted to convert the old format to the newly defined format. Additionally, it may be advisable to fist make a complete copy of the current database using [bolt db's `WriteToMethod`](https://godoc.org/github.com/boltdb/bolt#Tx.WriteTo) as a fail-safe in case of bugs or failures during the database migration.

**Comment by AndrewSamokhvalov** [comment]
I will grab this one

**Comment by Roasbeef** [comment]
Closed by #64.
