### ISSUE TITLE
 Feature request: Consul support

### ISSUE THREAD

**Issue by 3nprob** [lightningnetwork/lnd#5001]
Consul has been gaining in adoption and mindshare over etcd recently, and has a lot of nice security properties as well.

What is tge stance on adopting consul as an alternative to etcd?

**Comment by Roasbeef** [comment]
We have no plans atm to integrate Consul.

**Comment by 3nprob** [comment]
would you be open for a PR for adding it?

**Comment by Roasbeef** [comment]
Perhaps, but fair warning, it would be non-trivial to add.

**Comment by 3nprob** [comment]
Good to know - I was not planning on juimping on it right now anyway, just good to know if it's a matter of "we don't want it" vs "no one's planning on dedicating timne for it " - maybe we can keep this issue open for potential future explorations of it :)

**Comment by saubyk** [comment]
closing this issue as no plans to add and no forthcoming pr on this for a while
