### ISSUE TITLE
Signet

### ISSUE THREAD

**Issue by AaronDewes** [lightningnetwork/lnd#5018]
BIP-325 introduced the signet for bitcoin.

Will this also be implemented in LND?

**Comment by guggero** [comment]
Yes, I think we'll want to add signed to `lnd`.
I've started some work on this though it needs some cleanup first.

See
https://github.com/guggero/lnd/tree/signet
https://github.com/guggero/btcd/commits/schnorr-sig

**Comment by joostjager** [comment]
This would definitely be nice. Testnet coins are starting to become scarce with a 0.1 btc block reward.

**Comment by Roasbeef** [comment]
@joostjager if you need coins, you can just get them from the faucet: https://faucet.lightning.community/ -- it has 5 BTC available, and another few hundred sitting in reserve.

**Comment by joostjager** [comment]
Can I use that faucet to open multiple 0.16 BTC (0.15 BTC push amt) channels to the same node?

**Comment by Roasbeef** [comment]
Yeah you can just close, then re-open again. Also make sure you're already connected to the faucet before you use the form, it doesn't attempt to connect out to the node.

**Comment by michaelfolkson** [comment]
I'm sure you already know this but Signet also has block discovery time following a Poisson process like on mainnet which is nice for timelocks. Testnet has long periods without block discovery and then periods with flurries of blocks discovered. 

A Signet faucet if needed is [here](https://signetfaucet.com/).

**Comment by nicolasburtey** [comment]
> Testnet coins are starting to become scarce with a 0.1 btc block reward.

what is scare becomes valuable :)
hodl your testnet coin for dear life!

**Comment by joostjager** [comment]
@Roasbeef I keep getting `unable to open channel` on the faucet. Could it have to do with max pending?
