### ISSUE TITLE
generate a docker build with --monitoring

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#5028]
### Background

Looking to add lndmon, but a build with --monitoring is required.

Currency using Docker image with:

* repository: lightninglabs/lnd
*  tag: v0.12.0-beta 

It is straightforward to build my own image, but it seems that using `--monitoring` is a use case frequent enough that it could make sense that lightning labs generated one, so that it's compatible out of the box with https://github.com/lightninglabs/lndmon

**Comment by guggero** [comment]
I assume the idea to hide this behind a build flag was to pull in fewer dependencies and only add the RPC interceptor (which might have a small impact on performance) if needed.
But with our reproducible build system and binary verification I think we'll want to move away from build tags for actual features. Should we just hide this behind a runtime flag, @cfromknecht, @Roasbeef?

**Comment by 3nprob** [comment]
My suggestion: add docker image build arg `tags`, so at build time one can do e.g. `docker build --build-arg tags='monitoring signrpc walletrpc'`

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/5399.
