### ISSUE TITLE
lnd crashes with invalid magic in compressed pubkey string: 26

### ISSUE THREAD

**Issue by Raulo** [lightningnetwork/lnd#503]
I updated lnd to the current HEAD and lnd is unable to start. It crashes with

2017-12-19 21:12:38.847 [DBG] LTND: Adding debug invoice (*channeldb.Invoice)(0xc4200af1e0)({
 Memo: ([]uint8) <nil>,
 Receipt: ([]uint8) <nil>,
 PaymentRequest: ([]uint8) <nil>,
 CreationDate: (time.Time) 2017-12-19 21:12:38.847298526 +0100 CET m=+7.381764617,
 SettleDate: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
 Terms: (channeldb.ContractTerm) {
  PaymentPreimage: ([32]uint8) (len=32 cap=32) {
   00000000  01 01 01 01 01 01 01 01  01 01 01 01 01 01 01 01  |................|
   00000010  01 01 01 01 01 01 01 01  01 01 01 01 01 01 01 01  |................|
  },
  Value: (lnwire.MilliSatoshi) 100000000000000 mSAT,
  Settled: (bool) false
 }
})

2017-12-19 21:12:38.847 [DBG] SRVR: Debug HTLC invoice inserted, preimage=0101010101010101010101010101010101010101010101010101010101010101, hash=72cd6e8422c407fb6d098690f1130b7ded7ec2f7f5e1d30bd9d521f015363793
unable to read channel for chain_hash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000, node_key=021a6f8b85c6da2bb7f22e36f4a9d618b9d811f4a1e00da35540b1a907ed3fc854: unable to read channel data for chan_point=d293df7ab9329a1fb64b71658297a6e2dda3436d8b43799a86eb9d2f93ab13be:0: unable to fetch chan info: invalid magic in compressed pubkey string: 26

Linux Ubuntu 16.04, go version go1.9.2

**Comment by Roasbeef** [comment]
There was a breaking database change recently. If you were on a prior commit, then you'll need to go back to that commit, close out your channels, then update to the new version.

**Comment by stevenroose** [comment]
I think I got the same thing:
```
unable to read channel for chain_hash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000, node_key=02011549da333502f4c7ff2395ee5d110ab865d55f580fb360799f4f95e1be9066: unable to read channel data for chan_point=3bbf1628e7b96e77cfedd8cc2fdb6bfa1b8677e9da25e38bcbf9af9bbb76fa75:0: unable to fetch chan info: invalid magic in compressed pubkey string: 1
```

What is the commit that had the breaking change? Ugh, I have a lot of channels to close out :D

**Comment by stevenroose** [comment]
Hmm, I guess it should be either 48e22219c0926d8f75613ca08b0edbc4e79aa059 or cf6f313cff967164dbb1685529b6819b9794cb17.

**Comment by Raulo** [comment]
@Roasbeef 

I managed to close all the channels except one and now I'm stuck

 lncli  closechannel --force 4a09ec8029146c979e98ed1fea1e06de59393a601b4d70994f268d1156e251c2 0 3
[lncli] rpc error: code = Unknown desc = -22: TX rejected: output 4a09ec8029146c979e98ed1fea1e06de59393a601b4d70994f268d1156e251c2:0 referenced from transaction 015b93824319b1d00f7741f96cb9a334b7f54b7f7459d88b2a5c003b0b625cea:0 either does not exist or has already been spent

Was it because the channel was closed uncooperatively by my partner while my lnd was offline?

@stevenroose 

My pre update commit was 4555682 and it worked (for all the channels except one).

**Comment by stevenroose** [comment]
For me, this one worked: 8411a5b8ce2a8c953876375160cd8399cf16147a

I'm having trouble closing all my channels (120). I made this little program, but I'm getting errors from the RPC. 

`Error receiving channel update for channel 1378804073908928512: 
rpc error: code = Unknown desc = invalid hash length of 0, want 32`

I have both my lnd node and the lnrpc dependency on the same commit, but the response parsing issue might be fixed in master, I didn't check.

```go
package main

import (
	"io/ioutil"
	"log"
	"strconv"
	"strings"
	"sync"

	"github.com/lightningnetwork/lnd/lnrpc"
	"github.com/lightningnetwork/lnd/macaroons"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	macaroon "gopkg.in/macaroon.v1"
)

const (
	rpcServerUrl = "localhost:10009"
	tlsCertPath  = "/home/steven/gocode/src/lndtools/tls.cert"
	macPath      = "/home/steven/gocode/src/lndtools/admin.macaroon"
)

var (
	wg  sync.WaitGroup
	rpc lnrpc.LightningClient
)

func main() {
	conn := getConn()
	defer conn.Close()
	rpc = lnrpc.NewLightningClient(conn)

	chanResp, err := rpc.ListChannels(context.TODO(), &lnrpc.ListChannelsRequest{})
	if err != nil {
		log.Fatal(err)
	}
	channels := chanResp.Channels

	log.Printf("Closing %d channels...", len(channels))
	for _, channel := range channels {
		wg.Add(1)
		go closeAndWait(channel)
	}

	wg.Wait()
}

func closeAndWait(channel *lnrpc.ActiveChannel) {
	defer wg.Done()

	id := channel.ChanId
	pointStr := channel.ChannelPoint

	split := strings.Split(pointStr, ":")
	if len(split) != 2 {
		log.Fatalf("Error closing channel %d: Channel point has %d parts",
			id, len(split))
	}
	pointTxStr, pointIdxStr := split[0], split[1]
	pointIdx, err := strconv.ParseUint(pointIdxStr, 10, 32)
	if err != nil {
		log.Printf("Error closing channel %d: %s", id, err)
	}

	log.Printf("Closing channel %d", id)
	req := &lnrpc.CloseChannelRequest{
		ChannelPoint: &lnrpc.ChannelPoint{
			FundingTxidStr: pointTxStr,
			OutputIndex:    uint32(pointIdx),
		},
		Force: true,
	}
	resp, err := rpc.CloseChannel(context.TODO(), req)
	if err != nil {
		log.Printf("Eror closing channel %d: %s", id, err)
	}

	for {
		update, err := resp.Recv()
		if err != nil {
			log.Printf("Error receiving channel update for channel %d: %s",
				id, err)
			log.Printf("Failed to close channel %d", id)
			return
		}

		switch update.Update.(type) {
		case *lnrpc.CloseStatusUpdate_ClosePending:
			u := update.Update.(*lnrpc.CloseStatusUpdate_ClosePending)
			txid := u.ClosePending.GetTxid
			log.Printf("Closure of channel %d pending with txid %x", id, txid)

		case *lnrpc.CloseStatusUpdate_Confirmation:
			u := update.Update.(*lnrpc.CloseStatusUpdate_Confirmation)
			confsLeft := u.Confirmation.GetNumConfsLeft()
			log.Printf("Confirmation for channel %d, need only %d left",
				id, confsLeft)

		case *lnrpc.CloseStatusUpdate_ChanClose:
			u := update.Update.(*lnrpc.CloseStatusUpdate_ChanClose)
			if u.ChanClose.GetSuccess() {
				txid := u.ChanClose.GetClosingTxid()
				log.Printf("Channel %d succesfully closed in txid %x", id, txid)
			}
			return
		}
	}
}

func getConn() *grpc.ClientConn {
	creds, err := credentials.NewClientTLSFromFile(tlsCertPath, "")
	if err != nil {
		log.Fatal(err)
	}

	macBytes, err := ioutil.ReadFile(macPath)
	if err != nil {
		log.Fatal(err)
	}
	mac := &macaroon.Macaroon{}
	if err = mac.UnmarshalBinary(macBytes); err != nil {
		log.Fatal(err)
	}

	opts := []grpc.DialOption{
		grpc.WithTransportCredentials(creds),
		grpc.WithPerRPCCredentials(macaroons.NewMacaroonCredential(mac)),
	}

	conn, err := grpc.Dial(rpcServerUrl, opts...)
	if err != nil {
		log.Fatal(err)
	}

	return conn
}
```

**Comment by Roasbeef** [comment]
@Raulo if the peer isn't online, then you can tack on `--force` to force close the channel. 

@stevenroose that's an odd error it isn't related to closing out channels at all. I'd check to see if you have the latest set of proto files. As I pointed out above, you may have some dormant peers that haven't come online for some time. In that case you can just force close the channel. 

Closing this issue now as it isn't really a bug.
