### ISSUE TITLE
Can not abandon failed channel open

### ISSUE THREAD

**Issue by 3nprob** [lightningnetwork/lnd#5030]
### Background

An lnd node was getting an incoming channel open from a peer that unfortunately set the fee way too low - eventually it fell out of the mempool and is now long gone.

The original input has since been spent elksewhere, so there is no way this tx ever somehow miraculously comes back.

The nodes insiting on trying to negotiate the channel, though. As there is nothing on chain, there is nothing to close.
Even abanding the channel doesn't work:

```
$ lncli abandonchannel --funding_txid $TXID
[lncli] rpc error: code = Unknown desc = unable to find closed channel summary
```

We do want to establish this channel, which currently we are prohibited from as clightning does not allow redundant channels.

The opening party (running clightning) is cooperative and will cooperate if anything needs to be done on  their end, but in either case it seems like this scenario should have a path to reolution even from the perspective of a single node?

**Comment by guggero** [comment]
Just to clarify, are you sure you're not missing the `--output_index` flag? Is the number after the colon in the `channel_point` notation really 0?

**Comment by 3nprob** [comment]
Yeah, there's only one output (otherwise we would have bumped the fee when it was still in the mempool)

**Comment by wpaulino** [comment]
What state is the channel in? Could you provide more details from the `listchannels`/`pendingchannels` output?

**Comment by 3nprob** [comment]
The initiating clightning shows it as `CHANNELD_AWAITING_LOCKIN.

`listchannels` doesn't include it.

```
$ lncli pendingchannels
        {
            "channel": {
                "remote_node_pub": "...",
                "channel_point": "...:0",
                "capacity": "...",
                "local_balance": "0",
                "remote_balance": "...",
                "local_chan_reserve_sat": "...",
                "remote_chan_reserve_sat": "...",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "confirmation_height": 0,
            "commit_fee": "...",
            "commit_weight": "...",
            "fee_per_kw": "..."
        }
```

**Comment by wpaulino** [comment]
I don't see how your error above is possible if the channel shows up under `pending_open_channels`. Was the funding txid reversed by any chance?

**Comment by 3nprob** [comment]
> I don't see how your error above is possible if the channel shows up under `pending_open_channels`. Was the funding txid reversed by any chance?

As I mentioned in the issue, the tx has low enough fee that it won't be confirmed, and there is no change output to do a CPFP or RBF. It won't ever go though.

**Comment by guggero** [comment]
Yes, but what @wpaulino is saying is: if you see the channel under `pending_open_channels`, the `unable to find closed channel summary` error shouldn't be possible. Are you 100% sure the `--funding_txid` flag is correct, without a colon or anything but otherwise looks the same as in `channel_point` of `pending_open_channels`?

**Comment by 3nprob** [comment]
So, it did work when I tried again - don't save my shell history so can't tell if I misissued it after all - I tried about a dozen separate times but was also pretty tired so it's not impossible I messed it up... But I have also issued a couple of rebuilds and restrats since.

What can I say, it's working now. Sorry for the confusion!
