### ISSUE TITLE
25 waiting close channels: channel link not found / channel is already in the process of being force closed

### ISSUE THREAD

**Issue by reynico** [lightningnetwork/lnd#5031]
### Background

Hi,
I'm trying to close 25 pending close channels on one of our nodes. Tried closing them cooperatively and I got the same error for the 25 channels.

```
[lncli] rpc error: code = Unknown desc = unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found
```

which is weird because most (if not all) nodes are up and running

So I forced it for the first time but the channels didn't close. Then I retried: (same for the 25 channels)

```
[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed
```

pendingchannel list is a bit lengthly: https://pastebin.com/raw/sEWmwuhE

### Your environment

* version of `lnd`: `v0.12.0-beta` / `d176d2d65fc06e6631c4dc9478592be8545a21de`
* which operating system (`uname -a` on *Nix): `Linux ip-10-2-2-227 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux `
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v0.20.1`
* any other relevant environment details

### Steps to reproduce
1. Pick a channel from pendingchannels: `06061304a0922ef12e739a58486949cbd83773ddeda049d2ae690c39755b8b0b`
```
        {
            "channel": {
                "remote_node_pub": "024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca",
                "channel_point": "06061304a0922ef12e739a58486949cbd83773ddeda049d2ae690c39755b8b0b:1",
                "capacity": "1000000",
                "local_balance": "989069",
                "remote_balance": "291",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "LEGACY"
            },
            "limbo_balance": "989069",
            "commitments": {
                "local_txid": "ae80983d53bc943031dc2e172e3bd002b604893ed84942bb5f414882dd3441ec",
                "remote_txid": "f917d36976c423da46dc23c45c0c9f0dbf6951b53d5868e865bca401ae1289dc",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "10640",
                "remote_commit_fee_sat": "10640",
                "remote_pending_commit_fee_sat": "0"
            }
        },
```

2. Cooperatively close it: `lncli closechannel 06061304a0922ef12e739a58486949cbd83773ddeda049d2ae690c39755b8b0b 1`

3. Got:

```
2021-02-16 18:45:40.867 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found
```

The channel looks closed in 1ml: https://1ml.com/channel/633529803994365953

---

lnd logs when trying to force close a channel:

```
2021-02-16 18:38:40.480 [INF] HSWC: Removing channel link with ChannelID(0b8b5b75390c69aed249a0eddd7337d8cb496948589a732ef12e92a004130607)
2021-02-16 18:38:40.480 [INF] CNCT: Attempting to force close ChannelPoint(06061304a0922ef12e739a58486949cbd83773ddeda049d2ae690c39755b8b0b:1)
2021-02-16 18:38:40.480 [WRN] CNCT: Unable to disable channel 06061304a0922ef12e739a58486949cbd83773ddeda049d2ae690c39755b8b0b:1 on close: edge not found
2021-02-16 18:38:40.480 [ERR] RPCS: unable to force close transaction: channel is already in the process of being force closed
2021-02-16 18:38:40.480 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: channel is already in the process of being force closed
```

### Expected behaviour

Channels closed either cooperatively or forced.

### Actual behaviour

Channels stuck in pending close, balance in limbo.

**Comment by wpaulino** [comment]
I went through your list, some of these channels have actually been fully closed on-chain, but most haven't. It looks like your node hasn't swept your time-locked outputs as a result of the local force closes, so we'll need some logs to investigate. Can you restart your node with the `CNCT=debug` log option set and provide logs since the restart? Feel free to DM me on Slack if you don't want to share your logs publicly, though you've already shared your channels publicly (we plan to have a private log submission form soon to prevent this from happening).

**Comment by reynico** [comment]
good, let's talk on Slack. Close the issue?
