### ISSUE TITLE
gRPC Request SendPaymentV2 unreliable when not handling update stream.

### ISSUE THREAD

**Issue by emieldesmidt** [lightningnetwork/lnd#5035]
### Background
I'm trying to send a large volume of (invoiceless) transactions that carry data as fast as possible, however I seem to have arrived at some tradeoff. Depending on whether or not I wait for the stream of payment updates provided by the gRPC request `routerrpc.SendPaymentRequest`, the transactions arrive all in order but slowly after each other, or almost instantaneous all together but with a lot of transactions failing or being out of order. Please note, this could very well be just me using the wrong call for my purposes, my apologies in that case.

### Your environment

* version of `lnd`: v0.12.0-beta (Docker)
* OS: Linux Ubuntu 20.04.1
* version of `bitcoind`: v0.21.0
* Testbed is a network of docker images managed by Polar, where the sending and receiving node can deal with keysend transactions

### Steps to reproduce

If we were to split up a file into appropriately sized chunks of data, and iteratively send it to the destination node using a for loop calling the following function, a clear difference in success and speed can be observed. Adding an artificial delay between calls when not waiting for the updates shows no clear difference in success rate. At the receiving node, the incoming payments are logged using the `SubscribeInvoices` call.

```
   def send_routed(self, target_pk, data, print_update = False):
       preimage, phash = next(self.crypt_gen)

       custom_records = {
            # Keysend record for invoice-free transaction
            5482373484: preimage,

            # Custom data encapsulating record
            9780141036144: str.encode(data)
        }

        # The request with the embedded custom records
        request = routerrpc.SendPaymentRequest(
            payment_hash = phash,
            amt = 2,
            final_cltv_delta = 40,
            dest = bytes.fromhex(target_pk),
            timeout_seconds = 2,
            dest_custom_records = custom_records,
            fee_limit_sat = 300,
            no_inflight_updates = True,
            dest_features = [9],
        )

        # All arrive, and in order, but very slow.
        if print_update:
            for r in self.rstub.SendPaymentV2(request, metadata = [('macaroon', self.macaroon)]):
                print(r) # or pass

        # Roughly 2/3 arrives, slightly disordered, very fast
        else:
            self.rstub.SendPaymentV2(request, metadata = [('macaroon', self.macaroon)])
```

### Expected behaviour

Transactions coming through with equal success rate, in order, even when not waiting for the payment updates.

### Actual behaviour

The following call is slow but reliable:
```
    for r in self.rstub.SendPaymentV2(request, metadata = [('macaroon', self.macaroon)]):
                print(r) 
```
The following call is very fast if used consequentially, but arrive unreliably or out of order (even with artificial delay between calls):
```
    self.rstub.SendPaymentV2(request, metadata = [('macaroon', self.macaroon)])
```

Help or clarification would be greatly appreciated!

**Comment by guggero** [comment]
The response of `SendPaymentV2` is a stream of updates. I'm pretty sure that you have to consume those updates (even if you don't print them) to unblock `lnd` and let it do its job.
The reason why this is slower is because the script is actually waiting for the payments to go through instead of just firing and forgetting the request.

**Comment by Roasbeef** [comment]
If you're using Python, you can use the `asyncio` package or coroutines to asynchronously wait for payment completion in the background, yet still be able to pipeline the payments.
