### ISSUE TITLE
tor: add new hybrid connectivity mode for those wishing to increase their connection diversity 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#5042]
As is today in `lnd`, users can activate _outbound_ support for Tor by setting the `tor.active` flag. If they wish to also create an onion service, they can do so with either `tor.v2` or `tor.v3`. However as defined, these modes are all or nothing, they'll either tunnel all connections over tor, or only accept connections over Tor, but not in-between. As more Tor nodes join the network, it's describe for a sort of hybrid node to appear which can bridge connectivity between the Tor-only and clearnet-only portions of the network. 

A _hybrid_ mode as I define it would:
  * Only use the SOCKS proxy to connect out to Tor nodes, and use clearnet for IPv4+IPv6. This allows them to establish better connectivity, but favor low latency links when possible, assuming they don't care about explicitly hiding the location of their node. 
  *  Allow `lnd` to listen on a non-private network interface (`0.0.0.0`), yet also listen on `localhost` to set up a normal onion service leveraging the existing library functionality to do so. This allows nodes to accept both hidden service and clearnet connections. Again the goal here is to improve connectivity, so we don't care that we'll also have a set of clearnet connections. 

Such an operating mode would be very useful for those nodes that are a part of Lightning Pool, as much of the order book is backed by Tor-only nodes. An existing Lightning routing node would also find this functionality attractive, as they would be able to connect out to and accept a more diverse set of connections.

**Comment by gkrizek** [comment]
+1 This would be great.

I'm unclear if this is part of your idea here but I'd love to be able to define which services use Tor and which don't. For example, if I had a node that had `--tor.active --tor.v3` and was also using Neutrino. It'd be great to tell Neutrino to not use Tor but still have LND use Tor for peers. If my objective is strictly easy NAT capabilities and not privacy this would help Neutrino run efficiently (or even connect to nodes in a private network) but also let me use Tor for the Lightning Network.

**Comment by Kixunil** [comment]
Repeating recommendation from #3100 for visibility: to avoid risk of harming privacy it should be opt-in with an additional switch (such as `tor.mixed`). It should not change existing behavior after update because people could miss it and it'd leak their address.

**Comment by yuvadm** [comment]
This would be a great feature to have for nodes that do not have a privacy requirement, but do want to connect to .onion nodes.

My current workaround is to ask other .onion node operators to add me as a peer, and then proceed to open a channel to them. Is there a better way to do this?

**Comment by Kixunil** [comment]
@yuvadm that's the best way I know of

**Comment by Roasbeef** [comment]
@yuvadm there's an active PR attempting to address this issue (#5410), if you're able to compile custom branches locally, it would be great if you could help test it out and give feedback.

**Comment by Roasbeef** [comment]
> To avoid risk of harming privacy it should be opt-in with an additional switch (such as tor.mixed). It should not change existing behavior after update because people could miss it and it'd leak their address.

Definitely, if added it would strictly be an opt-in feature and wouldn't change the behavior of any Tor configs in the wild.

**Comment by yuvadm** [comment]
@Roasbeef Haven't done so until now, but looks like a good time to start! Will build, test, and report back.
