### ISSUE TITLE
Keysend feature bit announcement

### ISSUE THREAD

**Issue by Ale1ster** [lightningnetwork/lnd#5044]
### Background

c-lightning and eclair have implemented keysend, assigning the feature bit 54/55 for it.

Since it is finally adopted and implemented by the other daemons under the above feature bit pair, I think it would be better, for compatibility reasons at least, to announce it as a node feature as well.

Currently, when sending keysend payments from c-lightning `v0.9.3` to lnd `v0.11.1-beta`, it fails due to the missing feature bit.
That is due to a strict requirement for the feature bit from c-lightning, but since it became adopted, wouldn't it be better if the corresponding feature was announced by the lnd nodes for compatibility?

As far as I have seen, the keysend feature bit has not been implemented yet, at least up until lnd `v0.12.0-beta`.

[Keysend feature assignment proposal](https://github.com/lightningnetwork/lightning-rfc/issues/605#issuecomment-606679798)
[c-lightning keysend to lnd error](https://github.com/ElementsProject/lightning/issues/4299)

[c-lightning keysend MR](https://github.com/ElementsProject/lightning/pull/3611)
[eclair keysend MR](https://github.com/ACINQ/eclair/pull/1485/)

**Comment by Roasbeef** [comment]
Our main focus right now is deploying AMP, which is a better version of keysend as it supports payment splitting, recurring push payments, a static invoice, and more. We wouldn't be opposed to a PR that adds in their experimental feature bit (though it's odd it's a lower feature bit).

**Comment by cfromknecht** [comment]
@Ale1ster see my response on the main issue: https://github.com/ElementsProject/lightning/issues/4299#issuecomment-781606865

The feature bit has _not_ been standardized yet, and as @Roasbeef mentions keysend will be made obsolete in the near term by work on AMP.

**Comment by tvolk131** [comment]
@ellemouton hey I should have posted something here, but I started on the implementation for this yesterday... If you're already working on it then I'll abandon what I've done, but otherwise I can take this instead. Let me know!

**Comment by ellemouton** [comment]
hey @tvolk131 ! i'm about to push up a pr :) review welcome!

**Comment by tvolk131** [comment]
Sounds good! I just looked it over. I'm a new contributor, and it was reassuring to see that your code was basically identical to mine.
