### ISSUE TITLE
Stucked force closed channel due to low fee.

### ISSUE THREAD

**Issue by blanquefort** [lightningnetwork/lnd#5055]
### Background

I tried to force-close channel to permanently offline peer by Zap wallet connected to my own node. Unfortunately Zap chooses too low fee (1 sat per byte) what results to stucked channel in "waiting close" state. 

I thought that its possible to do RBF this way due to this issue https://github.com/lightningnetwork/lnd/issues/557 .
What am I supposed to do to free funds in limbo? 

### Your environment

- lncli version 0.12.1-beta commit=v0.12.1-beta
- Linux raspberrypi 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
- bitcoind / Bitcoin Core RPC client version v0.21.0

### Steps to reproduce

`"lncli closechannel --force --sat_per_byte 80 4f00fad9cfb22fbe058c43216f1de7390657660fde04bc47f365e1c4cca49385 1"` or
`"lncli closechannel --force --conf_target 3 4f00fad9cfb22fbe058c43216f1de7390657660fde04bc47f365e1c4cca49385 1"` 

it ends up with error message
`"[lncli] rpc error: code = Unknown desc = force closing a channel uses a pre-defined fee"`.

### Expected behaviour

Bump up fee for transaction to speed up frozen/stucked channel closing due to mempool saturation and get back funds in limbo.

### Actual behaviour

Command ends with error about pre-defined fees for transaction force closing.

**Comment by halseth** [comment]
Unfortunately this with the old channel types bumping a force closed channel is not possible. This is what the new `anchor` channel type is meant to address.

**Comment by blanquefort** [comment]
Thanx for reply, but how could I solve this situation? Waiting for unsaturated mempool seems not meaningful.

**Comment by halseth** [comment]
Sorry, that's how bitcoin works, hard to do anything about it but wait.

**Comment by davqu** [comment]
Same problem here. Any solution?

**Comment by guggero** [comment]
> Same problem here. Any solution?

What problem exactly? The mempool seems to be emptying multiple times a day, so any transaction with any fee should eventually be mined.

**Comment by davqu** [comment]
I wanted to open a channel with BOS but the transaction never enters the mempool.
After some time I opened a new channel with the peer. That went well. But the first try went wrong.
The channel is only local. And when I try to close it I get: [lncli] rpc error: code = Unknown desc = force closing a channel uses a pre-defined fee. reboot and force close has been done. The channel is now already a month in pending.

**Comment by guggero** [comment]
Sounds like the channel never opened in the first place. Check if the funding TX was ever confirmed. If not, check if the UTXO used for the funding TX has been spent in the meantime. If it was, then it's safe to use `lncli abandonchannel` (see `lncli abandonchannel --help`) to get rid of the channel that never made it to chain.
