### ISSUE TITLE
performance issue with lnd 0.12.1

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#5056]
### Background

lnd has become slow/unresponsive since 0.12. upgrade to 0.12.1 didn't seem to have solved the issue

### Your environment

* version of `lnd`: 0.12.1
* which operating system (`uname -a` on *Nix). GKE n2-standard-2. using docker image provided by LL.
* `bitcoind`: 0.21.1

### Steps to reproduce

I would need guidance to provide useful logs. I have logs=debug activated. I can share it

I can also add CPU profiling if that is useful?

Using graphql so one call from the mobile app to the backend can lead to many 10+ RPC call over lnd, which makes it hard to narrow down the issue. I'm installing Istio / Jaeger to be able to trace the call that has issues.

### Actual behaviour

This is a [blackbox probe](https://github.com/prometheus/blackbox_exporter) of our backend. I have installed blackbox only recently since we start having issues with lnd 0.12. Prior, our users didn't complain about uptime, so I'm assuming there was no such issue. 

The graph shows that the app gets unresponsive for 1-3 minutes and then gets back online. 

![image](https://user-images.githubusercontent.com/11156370/109171938-de3f3600-7747-11eb-8e22-4c8a9f3d6d3a.png)

Our CPU usage is very low. on average .05 vCPU.

![image](https://user-images.githubusercontent.com/11156370/109172610-953bb180-7748-11eb-8399-e3752796e831.png)

**Comment by gkrizek** [comment]
What is your blackbox probe doing? Is it just a TCP connection check or checking a specific API endpoint? If API, gRPC or REST?

There was some problems like this in 0.12 (can be found in #4892 ) but appeared to be fixed in 0.12.1 for everyone

**Comment by nicolasburtey** [comment]
the blackbox is doing what our mobile wallet is doing when the app is opening. it's fetching all the data it needs in one call to be presented to the mobile wallet. 

Here is the graphql call in case this is helpful:

```
query gql_query_logged {
  prices {
    __typename
    id
    o
  }
  earnList {
    __typename
    id
    value
    completed
  }
  wallet {
    __typename
    id
    balance
    currency
    transactions {
      __typename
      id
      amount
      description
      created_at
      hash
      type
      usd
      fee
      feeUsd
      pending
    }
  }
  getLastOnChainAddress {
    __typename
    id
  }
  me {
    __typename
    id
    level
    username
    phone
  }
  maps {
    __typename
    id
    title
    coordinate {
        __typename
        latitude
        longitude
    }
  }
  nodeStats {
    __typename
    id
  }
}
```

many outpurs, like `wallet { balance }` or `wallet { transactions {...}  }` require RPC call from our backend to lnd.

We have another blackbox call that is fetching less data, and where data doesn't need interaction with lnd, and this one is not failing.

I saw that the HDD lnd is using is not a SSD. I'm switching to an SDD and see if this will have any effect and report back here.

**Comment by gkrizek** [comment]
Ah ok, so you're doing GraphQL in between. I would test response times on the specific APIs (without anything in between). Then you can know exactly which API/Method is taking a while and that's much more helpful to debug.

**Comment by Roasbeef** [comment]
> Using graphql so one call from the mobile app to the backend can lead to many 10+ RPC call over lnd, which makes it hard to narrow down the issue

Likely doing a single call and tracking that over time would give you better insight into what's slow. Also if you can do a proper profile (with the go runtime), then you can get a better breakdown of what's slow.

**Comment by nicolasburtey** [comment]
this makes sense, but this is assuming there is no interdependency/deadlock as the result of a heavier load of RPC calls. 

the issues https://github.com/lightningnetwork/lnd/issues/4892 showed that the issue was arising under a more heavy load and bitcoind stop responding. 

I'm wondering if this is not what we have here as well. If we have 50 users fetching their balance through graphql simultaneously, and each graphql call result in 10 rpc calls to lnd (which itself leads to an order of magniture more call to bitcoind?), this may result in a 100+ rpc call/s to lnd. (A lot of things could be cached/rearchitected on our end to reduce the load if we understand as this being the issue)

This is also why I'm trying to instrument Jaeger as it would make it clearer if the assumption above is relevant or not. I'll report back once I have made some progress.

**Comment by nicolasburtey** [comment]
I did some sanity check:
- move the cluster to a new set of nodes
- set the pod affinity to the lnd Pod such that lnd will run on the same pod as bitcoind.
- move lnd storage to ssd drive instead of the default magnetic harddrive

and for now, the issue seems to be gone. I'll close this ticket for now, and reopen it if the issue arises again.
