### ISSUE TITLE
Channel that will never close?

### ISSUE THREAD

**Issue by hakonamatata** [lightningnetwork/lnd#5065]
### Background

Hi. I closed down a few channels weeks ago, but some have been stuck at "closing" and some at "pending force close" for weeks now, maybe over a month. 

here is the funding transaction for one of them [https://blockstream.info/tx/aafb436d391dbf5f6eadfcbb062bc571c70b92bc3184478e2c84e13e75497073](https://blockstream.info/tx/aafb436d391dbf5f6eadfcbb062bc571c70b92bc3184478e2c84e13e75497073)

And I guess I know why it does not close, the fee is 0.00000578 BTC or 0.29 USD. This is not getting picked up in the mempool, since it is never cleared out. 

What can I do here, I have three channels, and they look to be potentially stuck in this state forever. There should be a way to somehow pump the fee so it can be closed. 

### Your environment

* version of `lnd`

lncli version 0.11.0-beta commit=basedon-v0.11.0-beta-fresh-btcpay

* which operating system (`uname -a` on *Nix)

Linux BTCPayServerVM 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

Bitcoin Core RPC client version v0.20.1

**Comment by Roasbeef** [comment]
Can you fill in the rest of the issue template including what backend, version, you're running, etc? 

You can use the `BumpFee` command to use CPFP to increase the fee rate of the closing transaction.

**Comment by hakonamatata** [comment]
> 
> 
> Can you fill in the rest of the issue template including what backend, version, you're running, etc?
> 
> You can use the `BumpFee` command to use CPFP to increase the fee rate of the closing transaction.

Thanks for the quick response, updated the issue with environment details. 

Still unsure how I can fix this with bump fee, for example this one

![image](https://user-images.githubusercontent.com/4003969/109932366-5f5b7780-7cca-11eb-81af-9ce198f58b42.png)

It has been "closing" for weeks now, the only transaction I know about is the funding transaction here: 
[https://blockstream.info/tx/aafb436d391dbf5f6eadfcbb062bc571c70b92bc3184478e2c84e13e75497073](https://blockstream.info/tx/aafb436d391dbf5f6eadfcbb062bc571c70b92bc3184478e2c84e13e75497073)

That one is already confirmed, so can't bump the fee on that one. 

Can I change it to a "force close"? then get a "closing transaction" txid, then bump the fee of the closing transaction?

**Comment by guggero** [comment]
The channel was force closed with a 6 sat/vByte TX: 7f87cc718a9a3d012d6288519a941d03f55bef5f17502173d73995bf861cc1de
Since that TX is time locked (you were the closing party), you can't CPFP it. There unfortunately is nothing you can do on your end other than wait for the mempool to clear below 6 sat/vByte. If you know who the remote peer is you can ask them to CPFP the TX.

**Comment by hakonamatata** [comment]
> 
> 
> The channel was force closed with a 6 sat/vByte TX: 7f87cc718a9a3d012d6288519a941d03f55bef5f17502173d73995bf861cc1de
> Since that TX is time locked (you were the closing party), you can't CPFP it. There unfortunately is nothing you can do on your end other than wait for the mempool to clear below 6 sat/vByte. If you know who the remote peer is you can ask them to CPFP the TX.

That is what I was afraid of, in this case it is not that many sats and it might be cleared at some point. But, what if it was a larger amount of BTC and the mempool never got cleared and reached the transaction fee. There is a potential risk of getting BTC stuck forever. Practically losing your Bitcoin on lightning.

**Comment by guggero** [comment]
Yes, that is a potential problem in LN. The upcoming anchor commitment channel format (see https://lightning.engineering/posts/2020-04-30-lnd-v0.10/ for more information) is addressing exactly that problem.

Closing this as there's nothing more that can be done at this point other than waiting.
