### ISSUE TITLE
discovery: actually actually get rid of the prematureChannelUpdates map

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#5076]
Not too long ago in the past, [we made a move to remove the `prematureChannelUpdates` map](https://github.com/lightningnetwork/lnd/commit/00d4e92362e30f262c640bf2c48193060c32f158) as it was added mainly to handle some jitter in the itests that would lead to spurious failures due to mismatched delay expectations. This change was then [_reverted_ as it made the itests more unstable](https://github.com/lightningnetwork/lnd/commit/555de44d9fe96cb9762b509b1329594a4bdb6b52#diff-1eda595bbebe495bd74a6a0431c46b66cb4e8b53beb311067c010feac2665dcb). 

In the wild (le lightning network) a seemingly common occurence:
  * We go to rotate a sync peer. 
  * Sync peer sends us a ton of channels that may actually be zombies but we don't know it yet. 
  * We end up fetching said channels. 
  * For some reason (seems to be an underlying bug somewhere*), the sync peer will send us a series of channel updates for zombies, _but not also the corresponding channel announcements_.  
   * We'll then fetch all these updates, realize that we don't have an edge info (chan ann) for them an insert them into the `prematureChannelUpdates` map. 

This process seems to repeat for certain nodes (seems partially dependent on zombie chan view consistency between them) causing a memory spike at the initial download, and also unnecessary resource utilization. Each time we'll waste bandwidth by asking us to send us the channel updates, only to re-add them to the `prematureChannelUpdates` map. 

We should investigate why exactly (*) is happening, but also move to incrementally remove the map (once again) as in practice it doesn't do much for most nodes outside of some private channel edge cases. 

## Steps To Completion 

- [ ] When we go to add a channel to the `prematureChannelUpdates` map, check to see if this edge in isolation can be considered a "zombie". If so, then add it to the zombie edge index, and drop it right there and there. If we eventually actually get the channel announcement for this edge, then we'll "resurrect" it so it can become active again. 

- [ ] Investigate why (*) is happening, and attempt to reproduce it in a simnet test environment.

**Comment by KenCox94** [comment]
Is this truly beginner friendly? I would like to try to resolve this.
