### ISSUE TITLE
ConnectPeer returning incorrect peer_id

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#508]
I've been seeing this behavior several times where the `peer_id` returned from `lncli connect` doesn't match the `peer_id` that's returned when I do `lncli listpeers`. My node isn't fully behaving as I'd expect yet with autopilot so it could be caused by some other issue, but it still seems like a faulty response. I suppose it could also be that `listpeers` is returning an incorrect `peer_id`?

This is on debian using neutrino mode, built off the latest code.

This might be an issue I could actually fix myself but it'd be helpful to confirm that other people are seeing it as well first.

```bash
$ lncli connect 02f1da524a70afd8de6019e2367b47d8d41a623aa3594f55d0785fe1b047c853bc@159.203.125.125
{
    "peer_id": 0
}
$ lncli listpeers
{
    "peers": [
        {
            "pub_key": "02f1da524a70afd8de6019e2367b47d8d41a623aa3594f55d0785fe1b047c853bc",
            "peer_id": 3,
            "address": "159.203.125.125:9735",
            "bytes_sent": "33",
            "bytes_recv": "761601",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "1454840"
        }
    ]
}```

**Comment by Roasbeef** [comment]
Yeh peer ID isn't really used at all currently. We're planning on deprecating it all together.
