### ISSUE TITLE
PSBT channel funding fails with very long PSBT strings

### ISSUE THREAD

**Issue by ajpwahqgbi** [lightningnetwork/lnd#5080]
### Background

Please see [this reddit post](https://old.reddit.com/r/lightningnetwork/comments/lyd7dk/psbt_channel_funding_issues/). It appears that this user can use the PSBT channel funding support just fine except when using very big PSBTs, where they get this message: `[lncli] base64 decode failed: illegal base64 data at input byte 4092` 

### Your environment
Unknown

### Steps to reproduce

Try to open a channel using the `--psbt` functionality. It allegedly succeeds with small PSBT strings but fails with long PSBT strings.

### Expected behaviour

Channel funding should work fine with any length PSBT string.

### Actual behaviour

Allegedly channel funding does not work with very long PSBT strings.

### Preliminary investigation:

The error message is from `cmd/lncli/cmd_open_channel.go`, line 521 or line 721.  I suspect the root cause is in `readLine`, where `fmt.Scan` is called only once in the goroutine.  I am not a golang programmer so take this hunch with a grain of salt :).

**Comment by guggero** [comment]
This seems to be a problem of the terminal itself. See https://stackoverflow.com/questions/39111541/golang-reading-long-text-from-stdin.
I tried a bunch of different things and it looks like the reader in golang never gets more than 4096 characters from the OS, no matter how I try to read it.

I created a PR to fix it in a different way though: https://github.com/lightningnetwork/lnd/pull/5083
