### ISSUE TITLE
abort/remove pendingchannel opening

### ISSUE THREAD

**Issue by tomichec** [lightningnetwork/lnd#5081]
### Background

I have tried to fund three channels via `lncli openchannel --psbt`, the first two with `--no_publish`. During the procedure I have created the funding transaction with `lncli wallet psbt fund` and pasting the output to all three channels and also the non-published channels with the `lncli wallet psbt finalize`. But then I realised that the publishing channel has failed and could not paste the finalize transaction in the protocol.

Now I have two pending channels (with the nodes that were not supposed to be published). I would like to restart the process, but trying to run the `lncli openchannel --psbt` with the same nodes results in error: `err=Number of pending channels exceed maximum`.

I assume that if the pending channels were removed I could restart it without the problem. Unfortunately I was not able to find a way to remove pending channels.

### Your environment

* version of `lnd`:  `lnd version 0.12.1-beta commit=v0.12.1-beta`
* which operating system (`uname -a` on *Nix) 
```
Linux alarm 4.14.180-1-ARCH #1 SMP PREEMPT Tue May 26 02:05:58 UTC 2020 armv7l GNU/Linux
```
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin core version v0.21.0`
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
1. open a few channels with `lncli openchannel --psbt` all but the last also with  the `--no_publish` option (the last channel is the publishing channel)
2. create the funding PSBT transaction with `lncli wallet psbt fund ...`
3. paste the resulting string to the opening channel as setup in step 1. and press enter to proceed to the finalization step
4. finalize the funding transaction with `lncli wallet psbt finalize` + string from step 2.
5. paste the resulting string to opening channel as setup in step 1. and after step 3. to all but the publishing channel channel (the one that would be supposed to publish it, i.e. without `--no_publish` option)
6. abort the channel opening of the publishing channel without pasting the finalizing PSBT string

### Expected behaviour

The pending channel opening could remain there, but the user should have an option to abort it and remove it from the `lncli pendingchannel` list

### Actual behaviour

The user is not able to abort `pendingchannel` and the error prevents initiation of another channel opening.

**Comment by guggero** [comment]
I agree this isn't optimal behavior. The problem is that the channel 1 and two are independent operations that are completed by running the finalize step. Therefore you can't abort the whole batch in step 6.

You can use the `lncli abandonchannel` (available in dev builds) to get rid of the channels. The remote peer will "forget" the channels after 2 weeks if the funding transaction is never published.

Perhaps we should offer an interface where opening multiple channels can be done atomically. What was the reason to abort in the middle in the first place?

**Comment by tomichec** [comment]
> What was the reason to abort in the middle in the first place?

The third peer (the publishing one) had a minimal funding limit that I didn't reach, so the channel opening failed. I have not noticed the failure and proceed to the finalization step in the first two channels.

**Comment by wpaulino** [comment]
@tomichec was the error only shown in the logs, or was it also returned as the response of the `openchannel` command?

**Comment by tomichec** [comment]
@wpaulino I think it was also returned as the response. I have just not seen it, as I switched to another tab right after I pressed enter (in order to fit in the 10 minutes time constrain).

**Comment by tomichec** [comment]
I have just tried to to compile the dev build as suggested by @guggero. I've done it using `make clean && make tags=dev && make install`. 

Then I've restarted the `lnd` service and tried to `abandonchannel`, but the `lncli` complains as
```
AbandonChannel RPC call only available in dev builds
```

What have I done wrong? How to get the dev build? 

Thanks in advance for any advice.

**Comment by wpaulino** [comment]
Can this be closed @tomichec?

**Comment by tomichec** [comment]
yes @wpaulino , I had finally recompiled the lncli `make clean && make tags=dev && make install tags=dev` to be able to `lncli abandonchannel` and then abandoned pending channels manually.

I have described psbt channel opening with `lncli`  in a blog post:

https://blog.lightningconductors.net/post/2021/03/31/opening-psbt-lncli.html
