### ISSUE TITLE
[Request] Open channel with specific utxo

### ISSUE THREAD

**Issue by delbonis** [lightningnetwork/lnd#5082]
If I have a utxo in my node's on-chain wallet that's an appropriate size to create a channel of, there doesn't seem to be a way to tell lnd to just spend the entire utxo into the channel without risking leaving some dust.  There's no way to do it explicitly and estimating fees in my head is difficult.  I'm imagining a flag to pick the utxo and a flag like `subtractfeefromamount` in bitcoind to be able to spend the entire utxo without having to leave any dust.  Or at least a flag to round up any dust into the capacity of the channel in the event that opening it would leave some.

Looking at some of the other issues here it seems like there's some effort being made to revamp the options for the `openchannel`-related RPCs to make it support more sophisticated use-cases, not sure if this fits with those.

**Comment by wpaulino** [comment]
FWIW, opening a channel with a specific UTXO is already supported if you use PSBTs, but as you pointed out you'll need to account for fees yourself.

**Comment by Roasbeef** [comment]
Closing as this functionality is already supported as is, though it'll be enhanced by this PR: https://github.com/lightningnetwork/lnd/pull/4029
