### ISSUE TITLE
subscribeInvoices({}) fails to report expiry

### ISSUE THREAD

**Issue by AllanLindJensen** [lightningnetwork/lnd#5089]
### Background

Describe your issue here.

### Your environment

* version of `lnd` lncli version 0.12.99-beta commit=v0.12.0-beta-208-g65b0bbcd
* which operating system: linux - Ubuntu
* version of bitcoin-core.daemon Bitcoin Core RPC client version v0.21.0
* any other relevant environment details

### Steps to reproduce

Set up a listener on change of invoice status, logging the data received. AddInvoice with short life-span

### Expected behaviour

An EXPIRY message, when the bill expires

### Actual behaviour

only the OPEN message is received, not a message upon expiry. An attempt to pay the bill fails due to expiry, though.

**Comment by Roasbeef** [comment]
You can use `invoicerpc.SubscribeSingleInvoice` for this.

**Comment by AllanLindJensen** [comment]
Thank you, Roasbeef. I read into the frase "newly added/settled invoices" in lnd_rpc, that it should also report expiry. Only now, I see that it doesn't say. The service, invoicerpc, will make the code of my server much better.
We are a lot of people, who benefit from your great work!

**Comment by sangaman** [comment]
This behavior did strike me as unexpected/unintuitive. I'd expect `SubscribeInvoices` and `SubscribeSingleInvoice` to behave the same, aside from the single/many nature of the calls.

@Roasbeef Is there a particular reason they behave differently? Is it worth adding expiry notifications to `SubscribeInvoices`? I could probably open a PR if it would be desirable.
