### ISSUE TITLE
LND error: Block not available (pruned data)

### ISSUE THREAD

**Issue by nsav** [lightningnetwork/lnd#5092]
### Background

Hi, I’m trying to get my LND up and running for the first time on my EmbassyOS. My node is 100% synched .

### Your environment

EmbassyOS
LND 0.11.1~1
BitcoinCore 0.21.0~2

### Steps to reproduce

I have transferred a small amount of funds to the wallet because I was following these instructions:

After setting up your Lightning node, make sure it is funded by sending bitcoin to your node wallet address and establishing channels with other nodes. Then you can begin participating in the network.

(from here: https://bitcoinmagazine.com/learning-bitcoin/how-to-operate-a-profitable-lightning-mode)

once I transferred, note, the transfer was successful when I look it up by the transaction ID, I thought I would see something in the RTL console, but my sats have remained at 0.

I then looked at the logs of the LND, and saw this error:

2021-03-10 22:16:43.029 [ERR] LNWL: Unable to complete chain rescan: -1: Block not available (pruned data)

Could I get some helping in getting my LND up and running? Thank you 🙏

**Comment by guggero** [comment]
From the error message it looks like you're running a pruned `bitcoind` node. That is not supported by `lnd` in the current version: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#pruned-bitcoind-node

**Comment by nsav** [comment]
Ok thank you. I’ll talk to start9labs and see if I can change this setting from the embassy console. 

Would you know how to do this on the EmbassyOS?

**Comment by guggero** [comment]
No idea, sorry. I'm not familiar with EmbassyOS at all.

Closing this since it's a known unsupported use case.

**Comment by wpaulino** [comment]
@nsav if you're open to testing and don't mind waiting a couple more days, I'm working on a PR to enable pruned bitcoind support.

**Comment by nsav** [comment]
Hi,
I have it up and running now, not sure what happened. Once I restarted it all started working.

But I should test as I dont want to lose sats testing and playing around.

I think I’ll go on a testnet

Thanks,
Nick
