### ISSUE TITLE
Update grpc java.md

### ISSUE THREAD

**Issue by henta** [lightningnetwork/lnd#5093]
### Background

The links to http. proto and annotations. proto no longer exist
Lower versions of GRPC may no longer work with existing code
I cannot access the public IP according to the documentation 
Then I upgraded the GRPC to 1.36.0, the os-maven-plugin to 1.6.2, and the protobuf-maven-plugin to 0.6.1, everything was fine

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/6080.
