### ISSUE TITLE
Problem with changing RPC port connection

### ISSUE THREAD

**Issue by MarcSky** [lightningnetwork/lnd#5096]
### Background

I want to change rpc port from 10009 -> 10010 and p2p listen from 9735->9736, because I want to using 2 and more LND on one machine.
```
rpclisten=0.0.0.0:10010
norest=true
maxpendingchannels=10
listen=0.0.0.0:9736
externalip=<EXTIP>
tlsextraip=<EXTIP>
```

docker ports
```
    ports:
      - 8090:8090
      - 9736:9736
      - 10010:10010
```

Also I regenerated tls.key and tls.cert.

After restarting lnd I get message - "Password RPC server listening on 0.0.0.0:10010" and after inserting command - `lncli getinfo` I get error **[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"**

Why my node listen 10009 rpc port? Maybe its normal practice make something like this, forwarding request from external network to internal, but I thought I can just change rpc port in config file and changed my rpc listener:
```
    ports:
      - "10010:10009"
      - "9010:9735"
```
### Your environment

* version of `lnd` **0.12.0-beta**
* which operating system (`uname -a` on *Nix) **ubuntu**
* version of `btcd`, `bitcoind`, or other backend - **bitcoind - latest**
* any other relevant environment details - docker-compose

### Expected behaviour

I expected that I can using my lnd with rpc port 10010 and p2p 9736

### Actual behaviour

I get error - **[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"**

**Comment by guggero** [comment]
Your node doesn't listen on 10009 anymore. But `lncli` by default tries to connect to `localhost:10009`. Use `lncli --rpcserver=localhost:10010` instead.

Or leave the `rpclisten=0.0.0.0:10009` inside the docker container and just expose the ports to the host in a different way:
```
    ports:
      - 8090:8080
      - 9736:9735
      - 10010:10009
```

**Comment by MarcSky** [comment]
@guggero thanks a lot for your answer but I have yet one question. My node in getinfo wrote me that his uri
```
    "uris": [
        "<pubkey>@<ip>:9735"
    ],
```
Its look like my node listen port 9735 for p2p communication, but I set 9736. It's normal?

**Comment by guggero** [comment]
If you set `listen=` to something other than the default (or if you use the docker port re-mapping) then you also need to specify `externalip=<IP_as_seen_on_the_external_network>:<external_port>`.

This is on purpose since the value of `externalip` (what you see in the `uris`) is what's also broadcast on the p2p network and changing `listen` shouldn't automatically change that value since it could leak internal network information.
