### ISSUE TITLE
on-chain transaction to external wallet stuck

### ISSUE THREAD

**Issue by adiadore** [lightningnetwork/lnd#5100]
### Background

Sent transaction with low fee to external wallet 
https://www.blockchain.com/btc/tx/575bb7b9d2e0eaeef4e75c0c912a2e19b65db3072f7fabd4e9087a2bdd855d74

now wallet balance is
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}

### Your environment

0.11.0-beta commit=basedon-v0.11.0-beta-fresh-btcpay

using up2date btcpay docker deployment with my first lnd config where providing private keys was not possible

### Steps to reproduce

tried with command wallet bumpfee tx:id --sat_per_byte xx

but of course the output does not belong to this wallet, works only for channel transaction bumps for me

whats my line? thanks for your time & help

**Comment by guggero** [comment]
It looks like the transaction never made it to the network because it's trying to spend an output that's already spent. Sounds to me like your wallet is out of sync with the chain.
Can you try to update to lnd v0.12.1 and use the `reset-wallet-transactions=true` configuration to do a full rescan?

**Comment by adiadore** [comment]
thank you, will try as soon as lnd is updated to v0.12.x, afaik reset-wallet-transactions=true is only available with v0.12.x right?

https://github.com/btcpayserver/btcpayserver-docker - will probably be updated soon

**Comment by guggero** [comment]
> is only available with v0.12.x right?

Correct.
