### ISSUE TITLE
Channel force-closed: invalid commitment

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5103]
I've been running some performance tests with lnd master (commit fa4155c12605be616a35d18c62a9a8087d5b4b32) and ran into a channel force-closure. Are there still scenarios that aren't properly handled?

Test setup:
* Two nodes Bob and Charlie, one 10M channel, Charlie initiated
* 100 parallel instances of a test script that continuously creates a 1 sat invoice on Bob's node and lets Charlie pay it
* I did some ctrl-C, but not completely sure when and how

In Charlie's log:
`2021-03-15 10:47:29.016 [ERR] HSWC: ChannelLink(37556:1:0): failing link: ChannelPoint(0dd9c23ce32346281459403064c499b5cddcf7241dab70655a3b24c56e57695f:0): unable to accept new commitment: rejected commitment: commit_height=8037, invalid_commit_sig=3045022100dda358c4d3b9fde9f5ea782f181dc027c1e32c6ed8eecb21d667613a2cb2afb50220168ce455bbbaf2eb08e773f726f15ecd73cd1ccf4519f41c403e197f9a5e3a37, commit_tx=02000000015f69576ec5243b5a6570ab1d24f7dccdb599c46430405914284623e33cc2d90d0000000000a9ffdd80022d99000000000000160014f0c1a869a65802d0ffe4a24be405bfe1348144aaa5d9970000000000220020a977bb99d0336cf20c1fb39fa5175a60fc19350495e1e36cc5a43f30c885fa785ddac520, sig_hash=f6b3a385fc50c01d0df13c8edc24f10c62add010b3ad99e49ff7ed90e7a3c6f5 with error: invalid commitment`

Full logs: 
[force-close-logs.zip](https://github.com/lightningnetwork/lnd/files/6140437/force-close-logs.zip)

**Comment by Crypt-iQ** [comment]
Did you restart one of the nodes

**Comment by joostjager** [comment]
Yes, I think this happened after a restart

**Comment by Roasbeef** [comment]
> Are there still scenarios that aren't properly handled?

We have one more scenario that we have a fix for and are actively testing, perhaps @Crypt-iQ could point you towards the new branch to see if it's still triggered with your tests?

**Comment by Crypt-iQ** [comment]
Aim to post a patch this week

**Comment by joostjager** [comment]
@Crypt-iQ couldn't repro anymore with your branch :raised_hands:

**Comment by Crypt-iQ** [comment]
@joostjager how many commitment & htlc updates did your test run through?

**Comment by roeierez** [comment]
It seems that the PR that aimed to fix this didn't make it: https://github.com/lightningnetwork/lnd/pull/5123
This issue causes closed channels in Breez every week and a fix is very important for us.
Any updates or anything we can do to help?

**Comment by Crypt-iQ** [comment]
> It seems that the PR that aimed to fix this didn't make it: #5123
> This issue causes closed channels in Breez every week and a fix is very important for us.
> Any updates or anything we can do to help?

There's a new PR under review https://github.com/lightningnetwork/lnd/pull/5231

**Comment by Crypt-iQ** [comment]
Closed by https://github.com/lightningnetwork/lnd/pull/5231 -- should be fixed between two 0.13 nodes.  Any more issues, feel free to make a new issue
