### ISSUE TITLE
Lnd unresponsive because of db deadlock

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5104]
During the same test that I described in #5103, the sending node got into an unresponsive state. 

Calls like `lncli getinfo` got stuck and returned nothing. `lncli debuglevel` however did return the current debug levels. So it doesn't seem anything on the grpc level.

I've created a goroutine profile and it seems there is a database deadlock, possibly in the payment handling.

![profile001](https://user-images.githubusercontent.com/4638168/111150273-2e165d80-858e-11eb-8212-c3e0cc1f5fe6.png)

**Comment by nicolasburtey** [comment]
I ran today into an issue where `lncli getinfo` didn't work. but `lncli listtransactions` worked. 

maybe it was related. lnd was repeatedly [showing this log](https://github.com/lightningnetwork/lnd/issues/4873) 

with lnd 0.12.1

**Comment by joostjager** [comment]
Can be reproduced via the scenario described in #5103:

* Two nodes Bob and Charlie, one 10M channel, Charlie initiated
* 100 parallel instances of a test script that continuously creates a 1 sat invoice on Bob's node and lets Charlie pay it

**Comment by Roasbeef** [comment]
Do you have a goroutine dump of the instance as well? That'll likely be more useful that the call graph SVG as we'll be able to see where things are stacking up.

**Comment by joostjager** [comment]
Yes: [goroutine.txt](https://github.com/lightningnetwork/lnd/files/6143829/goroutine.txt)

**Comment by joostjager** [comment]
I've added a call to `runtime.SetMutexProfileFraction` in `lnd`, which allowed me to get the following mutex profile:

![profile001](https://user-images.githubusercontent.com/4638168/111308320-d134a900-865a-11eb-8f48-59568168e687.png)

**Comment by joostjager** [comment]
This may be caused by interaction between:
* findPath running in its db tx and calling `MissionControl.GetProbability` which gets the mission control lock
* `MissionControl.ReportPaymentSuccess` getting the mission control lock and then opening a db tx

**Comment by Roasbeef** [comment]
> I've added a call to runtime.SetMutexProfileFraction in lnd

Oh wow, this is super dope! I forgot this even existed, gotta love how Go tooling just keeps getting better and better over time
