### ISSUE TITLE
check for existence of file for tls

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#5109]
### Background

running 
`lncli --tlscertpath filedoesnotexist --macaroonpath ./admin.macaroon --rpcserver localhost:10009 getinfo`

will show this output:

```
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

rather, it should show an error saying the file doesn't exist.

### Your environment

* version of `lnd`: 0.12

**Comment by JohnVonNeumann** [comment]
I'd be happy to have a crack at this issue.

**Comment by ErikEk** [comment]
@JohnVonNeumann Are you working on it? I don't mind fixing it.

**Comment by JohnVonNeumann** [comment]
@ErikEk hey mate, nah I jumped the gun, go ahead mate

**Comment by ErikEk** [comment]
@JohnVonNeumann thx for the quick reply. I'll look into it.
