### ISSUE TITLE
Improve coin selection

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5110]
Currently `lnd` coin selection always prefers the largest available utxo:

https://github.com/bottlepay/btcwallet/blob/664f77ded195410cdb1868b45c0f189b84b693be/wallet/createtx.go#L33

```golang
// Pick largest outputs first.  This is only done for compatibility with
// previous tx creation code, not because it's a good idea.
sort.Sort(sort.Reverse(byAmount(eligible)))
```

Similar logic is implemented in the sweeper and perhaps elsewhere too.

Short term, this selection logic leads to low tx fees, but over time the wallet will contain ever smaller utxos. This pushes back spending the fees to consolidate these utxos to a time where the mempool might be even fuller and bitcoin even more expensive.

One simple option is to just randomize coin selection.

Interesting background information:

https://iohk.io/en/blog/posts/2018/07/03/self-organisation-in-coin-selection/
https://murch.one/wp-content/uploads/2016/11/erhardt2016coinselection.pdf

**Comment by Roasbeef** [comment]
Technically this issue should be in the `btcwallet` repo since that's where the coin selection actually is for sending routine transactions. When funding we use the same coin selection [we call `ListUnspent` which sorts as well](https://github.com/btcsuite/btcwallet/blob/4ec908df938672a2a7fe2f99d124497b6a6ff72b/wallet/wallet.go#L2541). For those that need alternative algorithms, the existence of the PSBT API and the generic coin selection calls can allow them to do so today w/o any further modifications.

**Comment by joostjager** [comment]
I was in doubt where to put the issue. Indeed, routine transactions are handled in `btcwallet`, but for funding it is decided by `lnd` to  use the `ListUnspent` output order as is.

This is not a blocker for anything because, as you say, the PSBT API can be used for external coin selection. It is not that easy though because the caller would need to take into account weights and effective values of the utxos.

It seems that random coin selection is a simple but effective improvement over always taking the largest, so it may be worth using this by default.

**Comment by Roasbeef** [comment]
> It seems that random coin selection is a simple but effective improvement over always taking the largest, so it may be worth using this by default.

Indeed, we could also pretty easily make it configurable as well.

Would be contributors using this can use this stdlib method to easily shuffle the set of returned UTXOs when we do default coin selection: https://golang.org/pkg/math/rand/#Shuffle

**Comment by joostjager** [comment]
I can add randomization plus a filter on negatively yielding inputs to `btcwallet`. How would you like to see this configurable in `lnd`? I was thinking of adding a command line flag for the coin selection strategy. Doesn't seem to me that you'd want to specify this with every individual coin operation.

**Comment by joostjager** [comment]
@Roasbeef, friendly reminder for question above. I am happy to make the changes.

**Comment by Roasbeef** [comment]
> I was thinking of adding a command line flag for the coin selection strategy. Doesn't seem to me that you'd want to specify this with every individual coin operation.

Yeah I think a command-line flag makes sense as we wouldn't want to change the behavior by default over night.
