### ISSUE TITLE
--gc-canceled-invoices-on-startup has no effect

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#5113]
### Background

Have enabled --gc-canceled-invoices-on-startup and restarted lnd and all canceled invoices are still there

### Your environment

* lnd v0.12.1-beta
* Linux 4.15 x86_64 GNU/Linux

### Steps to reproduce

- Make sure --gc-canceled-invoices-on-startup is included in the lnd command line
- Restart lnd and wait until its fully up and running
- Check if there are any canceled invoices present:

```
$ ( i=72151; while test $i -ge 0; do lncli listinvoices --max_invoices=10000 --index_offset=$i; i=$(($i - 10000)); done ) > inv
$ grep CANCEL inv|wc -l
   65356

```

### Expected behaviour

Right after startup, no CANCELED invoices should be present

### Actual behaviour

There are 65356 CANCELED invoices present. Nothing obvious in the logfile.

**Comment by bhandras** [comment]
Hi @jogc 
I tried to reproduce this issue with no luck on my end. With that many invoices deleting them can take a relatively long time. Indeed we do not log anything unless the delete fails. How long did you wait after startup? Note that you will be able to do `listinvoices` while LND is attempting to delete them as it's done in one transaction.

**Comment by jogc** [comment]
Hi! lnd has been running for 3 days now, I just checked again and there are 65363 CANCELED invoices present, so they are definitely not being deleted.

**Comment by bhandras** [comment]
Could you please check if the following log is present: `Deleting old invoices failed` (it's in warning level)

**Comment by joostjager** [comment]
Small side comment:

>With that many invoices deleting them can take a relatively long time

I think it is questionable whether doing any special/lengthy processing on startup is a good idea in general. In particular if it is also technically possible to do it while running. I can understand that something like a db compaction needs to be done offline, but why garbage collecting invoices?

Nodes can be have long uptimes, often you want restart to happen quickly and in a future where micro-payments or streaming payments become common, the payment volume may grow dramatically.

**Comment by jogc** [comment]
I can add that a lot of these invoices are from early experimentation with circular payments, if that makes any difference

**Comment by juscamarena** [comment]
I get the same here: 'INVC: Deleting old invoices failed: unknown invoice'

**Comment by bhandras** [comment]
> Small side comment:
> 
> > With that many invoices deleting them can take a relatively long time
> 
> I think it is questionable whether doing any special/lengthy processing on startup is a good idea in general. In particular if it is also technically possible to do it while running. I can understand that something like a db compaction needs to be done offline, but why garbage collecting invoices?
> 
> Nodes can be have long uptimes, often you want restart to happen quickly and in a future where micro-payments or streaming payments become common, the payment volume may grow dramatically.

Very true. The option `--gc-canceled-invoices-on-startup` is really meant to be run once to get rid of old invoices for users that have many piled up. Normally we'll GC on the fly (see  `--gc-canceled-invoices-on-the-fly`).

**Comment by Roasbeef** [comment]
> I get the same here: 'INVC: Deleting old invoices failed: unknown invoice'

Interesting, so one out of place invoice is causing the entire thing to fail in some contexts. 

Here's where we can an initial scan to collect the set of invoices to delete: https://github.com/lightningnetwork/lnd/blob/master/invoices/invoiceregistry.go#L177

**Comment by Roasbeef** [comment]
It looks like we're failing to remove certain invoices from either:
  * The payment addr index: https://github.com/lightningnetwork/lnd/blob/e2690918a0de29e4581cc9264a3e934bdcf3a32b/channeldb/invoices.go#L2184
    * The invoice add index: https://github.com/lightningnetwork/lnd/blob/e2690918a0de29e4581cc9264a3e934bdcf3a32b/channeldb/invoices.go#L2202
    * The settle index: https://github.com/lightningnetwork/lnd/blob/e2690918a0de29e4581cc9264a3e934bdcf3a32b/channeldb/invoices.go#L2224

**Comment by Roasbeef** [comment]
@juscamarena @jogc 

Can y'all try this patch so we can pinpoint things a bit to double check the assumptions of the initial scan loop: 

```diff
diff --git a/channeldb/invoices.go b/channeldb/invoices.go
index 1675f15c9..7598575aa 100644
--- a/channeldb/invoices.go
+++ b/channeldb/invoices.go
@@ -2181,7 +2181,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
 				// payment address index.
 				key := payAddrIndex.Get(ref.PayAddr[:])
 				if !bytes.Equal(key, invoiceKey) {
-					return fmt.Errorf("unknown invoice")
+					return fmt.Errorf("unknown invoice " +
+						"in pay addr index")
 				}
 
 				// Delete from the payment address index.
@@ -2199,7 +2200,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
 			// invoice key.
 			key := invoiceAddIndex.Get(addIndexKey[:])
 			if !bytes.Equal(key, invoiceKey) {
-				return fmt.Errorf("unknown invoice")
+				return fmt.Errorf("unknown invoice in " +
+					"add index")
 			}
 
 			// Remove from the add index.
@@ -2221,7 +2223,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
 				// settle index
 				key := settleIndex.Get(settleIndexKey[:])
 				if !bytes.Equal(key, invoiceKey) {
-					return fmt.Errorf("unknown invoice")
+					return fmt.Errorf("unknown invoice " +
+						"in settle index")
 				}
 
 				err = settleIndex.Delete(settleIndexKey[:])
```

**Comment by Roasbeef** [comment]
> I can understand that something like a db compaction needs to be done offline, but why garbage collecting invoices?

IIUC, right now if a node had invoices that expired _before_ we added the invoice expiry watcher, they'll fall through here and never be auto cancelled: https://github.com/lightningnetwork/lnd/blob/master/invoices/invoiceregistry.go#L204

**Comment by jogc** [comment]
> @juscamarena @jogc
> 
> Can y'all try this patch so we can pinpoint things a bit to double check the assumptions of the initial scan loop:
> 
> ```diff
> diff --git a/channeldb/invoices.go b/channeldb/invoices.go
> index 1675f15c9..7598575aa 100644
> --- a/channeldb/invoices.go
> +++ b/channeldb/invoices.go
> @@ -2181,7 +2181,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
>  				// payment address index.
>  				key := payAddrIndex.Get(ref.PayAddr[:])
>  				if !bytes.Equal(key, invoiceKey) {
> -					return fmt.Errorf("unknown invoice")
> +					return fmt.Errorf("unknown invoice " +
> +						"in pay addr index")
>  				}
>  
>  				// Delete from the payment address index.
> @@ -2199,7 +2200,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
>  			// invoice key.
>  			key := invoiceAddIndex.Get(addIndexKey[:])
>  			if !bytes.Equal(key, invoiceKey) {
> -				return fmt.Errorf("unknown invoice")
> +				return fmt.Errorf("unknown invoice in " +
> +					"add index")
>  			}
>  
>  			// Remove from the add index.
> @@ -2221,7 +2223,8 @@ func (d *DB) DeleteInvoice(invoicesToDelete []InvoiceDeleteRef) error {
>  				// settle index
>  				key := settleIndex.Get(settleIndexKey[:])
>  				if !bytes.Equal(key, invoiceKey) {
> -					return fmt.Errorf("unknown invoice")
> +					return fmt.Errorf("unknown invoice " +
> +						"in settle index")
>  				}
>  
>  				err = settleIndex.Delete(settleIndexKey[:])
> ```

Applied. Will report back next time I restart the node.

**Comment by jogc** [comment]
This is what I got

`2021-03-22 11:39:53.875 [WRN] INVC: Deleting old invoices failed: unknown invoice in pay addr index`

**Comment by jogc** [comment]
Please met me know if there's anything else I can do to help diagnose this! (I don't want to restart my node too often since it takes so long to get up and running again but sooner or later...)

**Comment by Roasbeef** [comment]
We have a candidate PR now here: https://github.com/lightningnetwork/lnd/pull/5224 

Are any of y'all able to give it a spin? Ideally done first on a testnet instance that may have the same issue re not being able to garbage collect those old invoices.

**Comment by jogc** [comment]
Only seeing this on my main mainnet node unfortunately. Anyone?

**Comment by jogc** [comment]
Actually, is the garbage collection done before any (peer) network activity takes place? In that case I could start lnd with networking disabled and just restore the data directory from a full backup in case this PR would mess something up.

**Comment by bhandras** [comment]
> Actually, is the garbage collection done before any (peer) network activity takes place? In that case I could start lnd with networking disabled and just restore the data directory from a full backup in case this PR would mess something up.

We're collecting old invoices that need to be canceled on startup and then cancel them later lazily but those invoices that have  already been canceled before are deleted right away (so before any peer activity). It's unlikely that the PR messes up anything but sine it's a mainnet node, perhaps best to test with a backup in place.

Thank you so much for you help @jogc!

**Comment by jogc** [comment]
I spun up lnd with this PR applied and all networking disabled (except for communicating with bitcoind), unlocked it, waited until no significant activity could be seen with top or iotop and then did the `lncli listinvoices` thing (see above). They were all still there. Nothing related in the log.

Would it be of any help to get the full JSON output from `lncli listinvoices`? Or do you want me to dig into the db with some bbolt tool to get more low level data on these invoices..?

**Comment by bhandras** [comment]
> I spun up lnd with this PR applied and all networking disabled (except for communicating with bitcoind), unlocked it, waited until no significant activity could be seen with top or iotop and then did the `lncli listinvoices` thing (see above). They were all still there. Nothing related in the log.
> 
> Would it be of any help to get the full JSON output from `lncli listinvoices`? Or do you want me to dig into the db with some bbolt tool to get more low level data on these invoices..?

Could you please double check that `lnd` was started with `--gc-canceled-invoices-on-startup`, and were the invoices listed in `CANCELED` state?

Also were there logs such as:
`Adding %d pending invoices to the expiry watcher`
and
`Deleting old invoices failed:"`

**Comment by jogc** [comment]
> > I spun up lnd with this PR applied and all networking disabled (except for communicating with bitcoind), unlocked it, waited until no significant activity could be seen with top or iotop and then did the `lncli listinvoices` thing (see above). They were all still there. Nothing related in the log.
> > Would it be of any help to get the full JSON output from `lncli listinvoices`? Or do you want me to dig into the db with some bbolt tool to get more low level data on these invoices..?
> 
> Could you please double check that `lnd` was started with `--gc-canceled-invoices-on-startup`, and were the invoices listed in `CANCELED` state?

I started with exactly the same command line as a normally do, so yep. According to lncli they have `"state": "CANCELED"`, yes.

> 
> Also were there logs such as:
> `Adding %d pending invoices to the expiry watcher`
> and
> `Deleting old invoices failed:`

There is nothing related to invoices at all:

```
$ grep -i inv ~/.lnd.invoice-gc-testing/logs/bitcoin/mainnet/lnd.log
$

```

This is the debuglevel I use:

`--debuglevel=ARPC=warn,ATPL=warn,BRAR=warn,BTCN=warn,CHBU=warn,CHDB=warn,CHNF=warn,CMGR=warn,CNCT=warn,CRTR=warn,DISC=warn,FNDG=warn,HSWC=warn,INVC=warn,IRPC=warn,LNWL=warn,LTND=warn,NANN=warn,NTFN=info,NTFR=warn,PEER=warn,RPCS=warn,RRPC=warn,SGNR=warn,SPHX=warn,SRVR=warn,SWPR=warn,UTXN=warn,WLKT=warn,WTCL=debug,WTWR=debug`

**Comment by bhandras** [comment]
Hmm I tested a similar setup (no networking apart from localhost) with the same binary (built from `invoice-gc-errors` branch) and I get these logs from `INVC`:
```
2021-04-22 15:19:35.773 [DBG] INVC: Adding 0 pending invoices to the expiry watcher
2021-04-22 15:19:35.774 [WRN] INVC: Deleting old invoices failed: there are no existing invoices
```

Added one more commit to the PR for more verbose logging, such that we'll get something like this:
```
2021-04-22 15:30:27.650 [DBG] INVC: Adding 1 pending invoices to the expiry watcher
2021-04-22 15:30:27.650 [DBG] INVC: Added 1 invoices to the expiry watcher
2021-04-22 15:30:27.650 [INF] INVC: Attemting to delete 5 canceled invoices
2021-04-22 15:30:27.651 [INF] INVC: Deleted 5 canceled invoices
```
Could you please run the test with the new commit added @jogc? Also maybe enable debug level such that we see more more.

**Comment by jogc** [comment]
Sure. Won't be able to do it today though. One thing: I'm not running master, I'm running v0.12.1-beta with your patch applied on top (and a few of my own unrelated patches). I can send a tar.gz of the exact tree I built from just so we eliminate anything related to other differences. Slack maybe?

**Comment by bhandras** [comment]
Sure, hit me up on slack I'm `bhandras` there too.

**Comment by bhandras** [comment]
For reference here's how I tested:

Used @jogc 's fork, fired up a `regtest` instance, added a few invoices that expire right away. Stopped my `lnd` instance, opened the `channel.db` file with `boltbrowser` and removed everything from `pay-addr-index` and then restarted with `--gc-canceled-invoices-on-startup`. Confirmed that logs have:

```
2021-04-22 16:14:47.050 [INF] INVC: Attempting to delete 6 canceled invoices
2021-04-22 16:14:47.052 [INF] INVC: Deleted 6 canceled invoices
```
