### ISSUE TITLE
HtlcInterceptor event gets replayed after channel counterparty reconnects

### ISSUE THREAD

**Issue by hsjoberg** [lightningnetwork/lnd#5115]
### Background

Greetings, I have stumbled upon an issue that is a little bit difficult to explain, but nonetheless is causing some significant issues.

I am using the [`HtlcInterceptor`](https://api.lightning.community/#htlcinterceptor) API to intercept and _settle_ incoming forward HTLCs.  
This works as intended and it settles the incoming HTLC as it should.

However, when the counterparty node for the channel that the incoming HTLC was received from goes offline and then online again (reestablishing contact), the `HtlcInterceptor` event gets replayed again. This happens every time the connection with the channel counterparty gets reestablished.     
This happens after the HTLC was already settled. 

### Your environment

* Some of the nodes on lnd latest master (b4aa661d165601b8fb3df32d2cd5e0b28696e41c). Will try with all on master soon

### Steps to reproduce

I have created a simple NodeJS application that demonstrates this issue: https://github.com/hsjoberg/htlcintercept-bug

Either create three nodes manually somehow or use [Polar](https://github.com/jamaljsr/polar) to manage it through docker containers.

Here's a video of it happening: 

[![HtlcInterceptor bug video](https://img.youtube.com/vi/UWoUhr5_Yig/0.jpg)](https://www.youtube.com/watch?v=UWoUhr5_Yig)

### Expected behaviour

No old HTLC event should ever be replayed.

### Actual behaviour

Old `HtlcInterceptor` HTLC events gets replayed when connection to the channel counterparty node is reestablished.

A n.b here is that attempting to settle the HTLC again by writing back to the `HtlcInterceptor` stream does nothing as no HTLC was actually really sent (AFAICT).

I'm a bit unsure exactly what information would be helpful here so just ask if there's anything in particular. In the video I tail the logfile, but I can provide it in text format as well if wanted. 

Cheers

**Comment by Roasbeef** [comment]
IIUC, this is to be expected as upon reconnection at times the set of HTLCs are essentially _re forwarded_ internally if they don't get locked into an outgoing channel.

**Comment by champo** [comment]
@Roasbeef is the HTLC commited in the incoming channel? In other words, can the incoming HTLC disppear if it's not locked into an outgoing channel?

**Comment by Roasbeef** [comment]
> is the HTLC commited in the incoming channel? In other words, can the incoming HTLC disppear if it's not locked into an outgoing channel?

Not 100% sure what you're asking but in the "happy case" after things are fully locked in, internally things we be retransmitted again, but ignored by the switch since the circuit is already active. Looks like what we need here is a similar check: the interceptor just ignores that replay if it already has an active client and it's developed the message to them. 

The incoming HTLC can only be removed if things get cancelled back, or we need to go off-chain for some reason. I upon initial forwarding, no outgoing link exists (unknown next peer), then things will be cancelled back immediately.
