### ISSUE TITLE
New incoming channel from faucet stalls and blocks_till_open shows negative w/ neutrino

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#512]
When I sync an lnd instance using neutrino and try to get my first channel by connecting to the node at faucet.lightning.community and then using its website to open a channel with my node, a pending channel is created and the funding transaction is broadcast. However, the channel never becomes active even after hours and over a dozen confirmations for the funding transaction. If I shut down lnd, graceful shutdown takes a very long time (~20 minutes on an f1-micro google cloud instance) and upon restarting lnd the channel is listed under `pending_force_closing_channels`.

Here's what `pendingchannels` shows after many confirmations for the funding transaction:

```
$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02f1da524a70afd8de6019e2367b47d8d41a623aa3594f55d0785fe1b047c853bc",
                "channel_point": "87061e42c47cecd1f8adba38d53b6279b81070a1324f6f72dfaa1dda1d00b995:0",
                "capacity": "100000",
                "local_balance": "75000",
                "remote_balance": "6900"
            },
            "confirmation_height": 0,
            "blocks_till_open": -11,
            "commit_fee": "18100",
            "commit_weight": "724",
            "fee_per_kw": "25000"
        }
    ],
    "pending_closing_channels": [
    ],n
    "pending_force_closing_channels": [
    ]
}
```

And here's what the lnd output looks like when I call `lncli stop`.

```
2017-12-23 03:17:36.784 [INF] LTND: Received shutdown request.
2017-12-23 03:17:36.784 [INF] LTND: Shutting down...
2017-12-23 03:17:36.784 [INF] LTND: Gracefully shutting down the server...
2017-12-23 03:17:36.784 [INF] FNDG: Funding manager shutting down
2017-12-23 03:17:36.994 [WRN] FNDG: fundingManager shutting down, stopping funding flow for ChannelPoint(87061e42c47cecd1f8adba38d53b6279b81070a1324f6f72dfaa1dda1d00b995:0)
```

After the channel finally moves out of `pending_force_closing_channels`, I can see that my walletbalance goes up confirming that the channel did in fact exist and that I was able to close it and claim the portion of the channel allocated to my node.

I've been able to reproduce this issue twice on two separate instances, but it doesn't happen every time as sometimes the channel from the faucet becomes active as I'd expect. All these attempts were on debian stretch running the latest roasbeef/btcd and lnd, using go 1.8 and running with neutrino.

**Comment by johng** [comment]
Is txindex enabled in your backend?

**Comment by sangaman** [comment]
@johng I'm using neutrino, as I understand txindex does not apply in that case so I don't believe I'm using it but correct me if I'm wrong.

**Comment by johng** [comment]
I ran into a similar issue running with the `neutrino` chain.
 
The channel initially opened fine however, shortly afterwards (when a new black as mined) it went back into a pending state, with a negative `blocks_till_open` index. 

I then ran into the following issue when I restarted the `lnd`. 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1789623]

goroutine 90 [running]:
github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc42054c0a0, 0x0, 0xc4203015c0, 0x0, 0xc4203015c0, 0x0)
    /Users/johng/go/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x93
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc420304080, 0xc420304700, 0x0, 0x2, 0x2, 0x1, 0x7c699571de2d7401, 0x9180bb6bb5efe0b0)
    /Users/johng/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1125 +0xc0
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc420304080, 0xc4201e4de0, 0xc420304700, 0x0, 0xc43053a480)
    /Users/johng/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x53f5
github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc420231500, 0xc4201e4de0, 0xc420304080, 0xc42013f040)
    /Users/johng/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:839 +0x91
created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler
    /Users/johng/go/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:827 +0x508```

**Comment by halseth** [comment]
Thanks! The crash is caused by a missing nil check, I put up a small fix #548.

The original issue is interesting, it would help to get a dump of the (debug) logs from `lnd` from the point where the channel funding process is initiated until it has a few confirmations.

@sangaman When `lnd` finally exits (after hanging for 20 min), what do the logs say?

**Comment by sangaman** [comment]
Looks like I don't have those logs anymore, but I can try to recreate it. Is there a particular debug setting I should use?

**Comment by halseth** [comment]
Just set `debuglevel=debug` :)

**Comment by Roasbeef** [comment]
Note that there's no more `blocks_till_open ` as of: fa6354b2239f1e947a069b679f4c235ad3d9bc94.
