### ISSUE TITLE
Mass Force Closed Channels when Hard Drive Fills

### ISSUE THREAD

**Issue by manakill** [lightningnetwork/lnd#5121]
### Background

Possibly Related: node's hard drive filled up

### Your environment

* version of `lnd`
* Version: 0.11.1-beta
 
* version of `btcd`, `bitcoind`, or other backend
* Bitcoind Version: 200100

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
Let the hard drive fill up with new blocks

### Expected behaviour

Fail gracefully? Maybe broadcast a "please stand by" message to connected nodes so they know not to close channels

### Actual behaviour

13 Channels Forced Closed in the ~1.5 day time-frame my node was down. Says Remote Force Closed. Have spoken to several people who say they did not trigger these closures either.

**Comment by Roasbeef** [comment]
> Possibly Related: node's hard drive filled up

 lnd 0.12 has a health check that will gracefully shutdown if it detects the disk is full. I recommend you update to that version or later: https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L853
