### ISSUE TITLE
FundPsbt rpc template does not support multiple identical outputs

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5124]
The outputs to produce are specified in `TxTemplate` as a map:

https://github.com/lightningnetwork/lnd/blob/b1309277b969ce8c1b5726ac17b7a6cc6bba60da/lnrpc/walletrpc/walletkit.proto#L569

This prevents the creation of multiple identical outputs. The use cases for this are probably weak, but still the interface seems to be unnecessarily restrictive.

An example use case is an exchange servicing on-chain withdraws in batches. Users specify the destination address and it could happen that two identical outputs end up in the same batch. Perhaps users making a donation?

Workaround is probably to specify a psbt template.

**Comment by Roasbeef** [comment]
> The use cases for this are probably weak, but still the interface seems to be unnecessarily restrictive.

This is on purpose. You'll find the same behavior with bitcoind's `sendmany` command. 

> Users specify the destination address and it could happen that two identical outputs end up in the same batch. Perhaps users making a donation?

So then why not combine both those donations into a single output? It'll make the transaction smaller, reduce the number of UTXOs produced, and result in cheaper fees. 

As you mentioned, you can either pass in a raw PSBT, or use the coin selection+locking RPCs to craft a custom transaction.

**Comment by joostjager** [comment]
>So then why not combine both those donations into a single output? It'll make the transaction smaller, reduce the number of UTXOs produced, and result in cheaper fees.

Typically users will receive the txid of their on-chain payment. If in that tx, their donation is combined with the donation of a random other user it gets confusing.
