### ISSUE TITLE
lnd fails with apparent segfault! - Emergency

### ISSUE THREAD

**Issue by wankerstar** [lightningnetwork/lnd#5126]
### Background

LND runs to the point of syncing the channel graph, then fails with:

2021-03-19 10:45:25.365 [INF] CHDB: Pruned 7 unconnected nodes from the channel graph
unexpected fault address 0x66b1b044
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x66b1b044 pc=0x331acc]

### Your environment

lnd version 0.12.1-beta commit=v0.12.1-beta
Bitcoin Core version v0.21.0
Raspbian, RPi4

### Steps to reproduce

Appeared spontaneously overnight. Have tried reinstalling lnd and tor, restarting all services and device.

More detailed failure log attached as file.

[lndsegfault.txt](https://github.com/lightningnetwork/lnd/files/6172925/lndsegfault.txt)

**Comment by Crypt-iQ** [comment]
Seems like bbolt is corrupted? Could you try flipping the config option `sync-freelist` off?

**Comment by wankerstar** [comment]
Thanks for the suggestion!  Same output, I'm afraid  : (

**Comment by wankerstar** [comment]
Best guess is my rebalancing script failed in some strange way and corrupted some data. Can anyone confirm that this is a bbolt problem? Can I force a database rebuild or something?

**Comment by wankerstar** [comment]
Or, is there any way to recover my channels? I'm willing to do a total rebuild if necessary, losing this node would break my heart.

**Comment by guggero** [comment]
Is the database size larger than about 950 MB? If you are on a 32bit system (which most Raspberry Pis are), that limits the DB size. You might need to run database compaction. Try running [`chantools compactdb`](https://github.com/guggero/chantools/blob/master/doc/chantools_compactdb.md). If that results in the same error, you need to copy the DB to another host (64bit machine) and run the command there, then copy the DB back. This is a bit risky though so feel free to contact me on Slack if you're not sure what to do exactly.

**Comment by wankerstar** [comment]
Thanks guggero! It did fail with the same error on the pi, attempting compaction on 64 bit system now.

**Comment by ajpwahqgbi** [comment]
> If you are on a 32bit system (which most Raspberry Pis are), that limits the DB size.

So what is the procedure, then? @wankerstar should just get a new 64-bit device? Otherwise this compaction will have to be regularly repeated?

Should there be a warning not to use LND on 32-bit machines?

**Comment by guggero** [comment]
The procedure for 32bit systems is: Run compaction regularly (see the new `--db.bolt.auto-compact` added in `v0.12.0-beta`) and garbage collect unused data (`--gc-canceled-invoices-on-startup`, also new in `v0.12.0-beta`).
Long term a migration to a 64bit OS is recommended. I know RaspiBlitz is working on that.

**Comment by ajpwahqgbi** [comment]
Got it. Thanks for the instructions. I didn't read it; are these instructions in the README? If not they should probably be in there, as Raspberry Pis are pretty popular. Also someone should probably ping the RaspiBlitz people to get them to add these config options if they aren't doing it already.

**Comment by wankerstar** [comment]
Holy hell I'm back up!! Thank you so much for your prompt assistance.

Moving forward though, I'm worried! The compacted db is still 802mb, dangerously close to the limit. Attempting to launch with auto-compact enabled seems to cause the error to occur again. Should I consider moving architectures immediately? If so, the documentation claims switching architectures with open channels is unsupported - is that still true?

**Comment by Roasbeef** [comment]
Closing as this has been resolved. If you can migrate to a 64-bit architecture, recommend doing so. Simply copying over the database files likely won't work, so you may need a more manual transplant method.

**Comment by wankerstar** [comment]
Thanks. @Roasbeef, can you direct me to any information on how a "more manual" transplant might be accomplished?

**Comment by guggero** [comment]
You can follow this guide: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#migrating-a-node-to-a-new-device
There is still the lingering question whether moving between 32bit and 64bit is actually supported by the underlying `bbolt` database library. Given the fact that you just successfully compacted on a 64bit system and were able to start it again on the 32bit machine is a good indication that it probably works.
But please bear in mind that migrating between architectures is not officially supported by us and that things could still go wrong. If you are willing to take that risk, then simply moving the whole `.lnd` folder to a new machine is what you can do. If not, then closing all channels, starting a new node with the same seed on the new machine and then opening the channels again is the alternative option.
