### ISSUE TITLE
Lnd with Neutrino is not broadcasting on-chain transaction to the bitcoin network

### ISSUE THREAD

**Issue by hsjoberg** [lightningnetwork/lnd#5130]
### Background

Hi, I'm not sure if this issue should be opened in the neutrino project or here.

I am having some trouble sending on-chain transactions, seemingly they're never published/relayed.  
This is with lnd 0.12.1 using Neutrino and connecting to a bitcoind 0.21.0 node serving compact filters.

Both `SendCoins` and `OpenChannel` seems to be affected by this.

On the bitcoind side I tried putting mempool debug logging on, but no transaction is ever received.

On the lnd side I see nothing unusual:
```
2021-03-20 19:13:08.043 [INF] RPCS: [sendcoins] addr=tb1qyvugphjf6wfuzuqvwf2sl20gtxpa46k9af0zcx, amt=0.0005 BTC, sat/kw=12500, min_confs=1, send_all=false
2021-03-20 19:13:08.086 [INF] LNWL: Inserting unconfirmed transaction 516e19659f516dc830ab45da3c8e31fe2c056509a56039906d2ef115c907733d
2021-03-20 19:13:08.632 [INF] RPCS: [sendcoins] spend generated txid: 516e19659f516dc830ab45da3c8e31fe2c056509a56039906d2ef115c907733d
```

The configuration is nothing unusual AFAICT, on the bitcoind side (omitted comments etc to keep it small):

```
txindex=1

zmqpubrawblock=tcp://127.0.0.1:28334
zmqpubrawtx=tcp://127.0.0.1:29335

blockfilterindex=1
peerblockfilters=1

loglevel=debug
category=mempool
debug=mempool

testnet=1

listen=1

rpcuser=[redacted]
rpcpassword=[redacted]

rpcport=8332

[test]
port=18333
rpcport=18332
rpcbind=[redacted]
```

On the lnd side, [see here](https://github.com/hsjoberg/blixt-wallet/blob/master/src/state/index.ts#L263).

### Your environment

* lnd 0.12.1 with Neutrino
* bitcoind 0.21.0 as the Compact Filter server
* Mostly tested on my mobile wallet (Gomobile Android/iOS), but I confirmed it's happening on normal desktop MacOS as well, which is why I am choosing to open the issue

### Steps to reproduce

* Set up a bitcoind 0.21.0 node serving compact filters.
* Hook up lnd+neutrino with `neutrino.connect=<bitcoind node>`
* Send coins to lnd's internal wallet
* Spend these coins
* The transaction generated from lnd/btcwallet is seemingly never published (doesn't appear on block explorers etc). This applies to both mainnet and testnet. On mainnet I double-checked `bitcoin-cli testmempoolaccept ...` on the bitcoind peer to make sure the transaction valid and has enough fees.

### Expected behaviour

On-chain transactions created by lnd/btcwallet should relayed to the Neutrino peer. 

### Actual behaviour

Lnd/btcwallet seemingly never relays on-chain transactions to the Neutrino peer.

---

EDIT: Fixed lnd 0.20.1 -> 0.12.1...

**Comment by delbonis** [comment]
Is the transaction actually valid?  I keep having issues where my node tries to spend coins that have already been spent (into a Pool account) and it keeps an invalid pending utxo in the wallet that you have to rescan the chain to clear out.

**Comment by halseth** [comment]
Did you try the exact same setup just using btcd instead? Would be interesting to see if in that case it gets published.

**Comment by Roasbeef** [comment]
Also if you re-run it with full `debug/trace` logs for `BTCN` on the neutrino node, do you see it actually publish the transaction? Neutrino will also re-publish in the background until either it's restarted (then it'll continue to do so if still unconfirmed), or it gets confirmed.

**Comment by hsjoberg** [comment]
@delbonis I think the transaction is valid. I tested it with `bitcoin-cli testmempoolaccept`, which I assume will check if the script is actually valid.

@halseth Yes, my initial thought was some kind of incompatibility with bitcoind. I'll try what happens with btcd.

@Roasbeef Thanks, I'll try that and report back.

**Comment by hsjoberg** [comment]
@halseth Using `btcd 0.21.0-beta` instead of `bitcoind 0.21.0` works fine. Same setup.

**Comment by Roasbeef** [comment]
Was the transaction perhaps one of a relatively low fee? `btcd` doesn't implement a dynamic mempool fee requirement quite in the same way that `bitcoind` does.

**Comment by hsjoberg** [comment]
@Roasbeef I don't believe that's the case. This is happening on both mainnet and testnet. On mainnet I made sure to have sufficient tx fee (by checking on https://mempool.space), I also double-checked the tx hex with `bitcoin-cli testmempoolaccept ...` on the bitcoind neutrino peer to make sure it would accept the transaction.

Note that this isn't a one time incident, I can easily reproduce it on testnet and I believe @torkelrogstad has encountered into the same problem at least once.

**Comment by wpaulino** [comment]
@hsjoberg upon a glance, it seems we enforce a [500ms timeout on the transaction broadcast process](https://github.com/lightninglabs/neutrino/blob/5e09bd9b5d65e90c6ff07aa11b3b9d80d42afb86/query.go#L1139) and you received the `getdata` message after 2 seconds instead. Could try extending that timeout and see if it helps?

**Comment by hsjoberg** [comment]
@wpaulino Initial testing suggests that yes, increasing the timeout solves the problem!
I have opened a [pull request](https://github.com/lightninglabs/neutrino/pull/219) over at the Neutrino repository addressing this. 500ms seems unnecessarily short.

**Comment by delbonis** [comment]
@hsjoberg In my case the transaction actually is invalid, trying to manually give it to a node it rejects it because the input was already spent.

**Comment by hsjoberg** [comment]
Fix was merged over at the Neutrino repo https://github.com/lightninglabs/neutrino/commit/62e95cdcbf33d67a2c420f5015040dd3761e567a.

I'm opening a pull request to update the Neutrino version to use in lnd: #5170
