### ISSUE TITLE
DeleteAllPayments() RPC Ignores 'failed_payments_only' Parameter

### ISSUE THREAD

**Issue by wankerstar** [lightningnetwork/lnd#5131]
### Background

The following Python grpc code deletes both successful and unsuccessful payments from the database, rather than only unsuccessful payments. In particular there were known successful circular payments that were deleted.

req = ln.DeleteAllPaymentsRequest(failed_payments_only=True)
req.failed_payments_only = True              # maybe it doesn't like keyword assignment?
lnstub.DeleteAllPayments(req)

Output of ListPayments before deletion attached (2 instances).
[ListPayments_before.txt](https://github.com/lightningnetwork/lnd/files/6178212/ListPayments_before.txt)
[ListPayments_before2.txt](https://github.com/lightningnetwork/lnd/files/6178218/ListPayment_before2.txt)
Output afterwards is blank in both cases.

Thanks in advance for any help!

### Your environment

Python 3.7.3
lnd version 0.12.1-beta commit=v0.12.1-beta
Bitcoin Core version v0.21.0
Raspbian, RPi4

### Steps to reproduce

Execute Python code above with successful payments in the database. Mine were circular, if that's relevant.

### Expected behaviour

Successful payments should remain in the database.

### Actual behaviour

All payments appear to get deleted.

**Comment by halseth** [comment]
I'm not familiar with gRPC in a Python environment, could you past the serialized request proto (as hex)?

**Comment by halseth** [comment]
Also, can you look for the log `DeleteAllPayments` in your lnd logs and paste it here?

**Comment by halseth** [comment]
Btw, I noticed you are saying you are running v0.12.1. The `failed_payments_only` option is not available in that version, you should wait for v0.13 or update to master if you need it.

(and it's a good idea to stick with the gRPC definitions for the lnd versiont you are running to avoid these problems in the future)

**Comment by wankerstar** [comment]
Thank you! I had been assuming that the [grpc api reference](https://api.lightning.community/#lnd-grpc-api-reference) was for the currently released version. This explains much. Could you please point me to the version-dependent gRPC definitions so that I can avoid this mistake in the future?

**Comment by wankerstar** [comment]
Apologies if I'm being thick, @halseth, but I just can't seem to find a gRPC definition listing for a specific version, either in the docs or the code.
Could you please link me to whatever document informed you that the option is not available in v0.12.1?
This will prevent future stupid questions. Thanks in advance.

**Comment by wpaulino** [comment]
At the moment we only maintain rendered documentation for the master branch. It is sourced from the `.proto` files in `lnrpc`, so everything you need for your specific version should be there.
