### ISSUE TITLE
RegTest `SyncToChain` always false

### ISSUE THREAD

**Issue by jakesyl** [lightningnetwork/lnd#5144]
### Background

As discussed I've been working on improving the [`lntest`](https://github.com/lightningnetwork/lnd/tree/master/lntest) harnesses and working on an external, dockerized mocking library as a first step. But no matter what, the chain is never synced which precludes me from opening channels. This can be seen in xplorfin/lndmock#20

### Your environment

* version of `lnd`: `master`, dockerized at b4b7f2972442703fff59a881116bc9855f9ce305 using the [start-lnd.sh](https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/start-lnd.sh) script in the [`docker` folder ](https://github.com/lightningnetwork/lnd/tree/master/docker) and the [lnd docker file](https://github.com/lightningnetwork/lnd/blob/b4b7f2972442703fff59a881116bc9855f9ce305/Dockerfile)
* which operating system (`uname -a` on *Nix): alpine (as per the [lnd docker file](https://github.com/lightningnetwork/lnd/blob/b4b7f2972442703fff59a881116bc9855f9ce305/Dockerfile))
* version of `btcd`, `bitcoind`, or other backend: `v0.20.1-beta` from [this docker file](https://github.com/xplorfin/lnd-docker-images/blob/master/btcd/Dockerfile) (also a carbon copy of the [btcd docker file](https://github.com/lightningnetwork/lnd/blob/master/docker/btcd/Dockerfile) from lnd

### Steps to reproduce

The full code is in [`lnd_test`](https://github.com/xplorfin/lndmock/pull/20/files#diff-59f8cd202d4c7c9568f0d5eea7baf8ef8f20be72ecb6b86cb49ffdc0c3d9cbf3) in xplorfin/lndmock#20

### Expected behaviour

At some point in the `lnrpc.GetInfoRequest` (which is [sent on a loop](https://github.com/xplorfin/lndmock/pull/20/files#diff-1b42e349d40179b7f81d8278fbecbea68c4f1a9b8bd85e691b362c0b3338801eR134) [SyncedToChain](https://github.com/xplorfin/lndmock/pull/20/files#diff-1b42e349d40179b7f81d8278fbecbea68c4f1a9b8bd85e691b362c0b3338801eR140) will be true)

### Actual behaviour

SyncedToChain is never true

**Comment by jakesyl** [comment]
(temporarily?) closing, as it looks like I'm able to successfully get this working on docker intermittently (w/ the readme)

**Comment by guggero** [comment]
If there wasn't a block in more than 2 hours, bitcoind itself will start to think it's out of sync. Usually you can resolve this problem by just mining a new block.

**Comment by IAD** [comment]
@guggero maybe you know how to ignore this `bitcoind` 2 hours rule(for tests)? my lnd nodes cannot sync with the network on cold network start(inside the compose)

**Comment by guggero** [comment]
I don't think there is a way to ignore that. But can't you define a post startup script that mines a fresh block?
