### ISSUE TITLE
Local commitment output was swept by remote party

### ISSUE THREAD

**Issue by MykelSIlver** [lightningnetwork/lnd#5147]
### Background

Funds are swept by remote party during solving issue [#5140](https://github.com/lightningnetwork/lnd/issues/5140)

### Your environment

* version of `lnd`
0.12.1-beta commit=v0.12.1-beta

* which operating system (`uname -a` on *Nix)
Linux umbrel 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.21.0.0-g95ea54ba089610019a74c1176a2c7c0dba144b1c

* any other relevant environment details
n/a
### Steps to reproduce
issue [#5140](https://github.com/lightningnetwork/lnd/issues/5140)

### Expected behaviour

Local funds in `pending_force_closing_channels` should be swept into the **local** party wallet

### Actual behaviour
Local funds in `pending_force_closing_channels` are be swept into the **remote** party wallet!

Does this means the remote party has my funds?
If true, what can I do in this case and why has this happened?

The [containing node](https://1ml.com/node/0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f) who has probably my funds is high ranked in [BOS list](https://lightningwiki.net/bos/)
Seems not a bad thing, not a cheater likely, which improves my change to get the funds back somehow. Problem is I cannot reach this entity/person of this node.

**Comment by guggero** [comment]
I'm pretty sure this is just a log message that's wrong. Try looking at the chain to see what happened: https://blockstream.info/tx/7a3634171e8cb3da2c245608b92709eb5a7c12c08e830377d4c8e61f0b1e0420
You see that the funds that were swept were later used to open the channel https://1ml.com/channel/743142317133922305 to LNBig. So I assume you are node 0204a91bb5802ad0a799a.
It's quite hard to figure out who took the funds just from looking at the chain. That's probably why the error message is not accurate.

Again, my question: Are you missing any funds? If you don't know what your final balance is supposed to be, it's not going to be easy to judge when the process of channel recovery is finished.

**Comment by MykelSIlver** [comment]
Yes I am node 0204a91bb5802ad0a799a.
Yes I see what you mean.
No I am not sure what the final belance supposed to be.
Looking at https://blockstream.info/tx/7a3634171e8cb3da2c245608b92709eb5a7c12c08e830377d4c8e61f0b1e0420
I see too that the funds that were swept were later used to open the channel https://1ml.com/channel/743142317133922305 to LNBig

So because I am not sure what the final belance should be I am closing this ticket. My apologies for occupying your previous time.

**Comment by MykelSIlver** [comment]
Just want to add the following statement to clear the air:
No funds are lost.
Finished my calculation of all the funds which went in from the deposit o the lightning node and the funds which were available after closing all the channels and do some rescan. No loss at all (only fees reduced the amount microscopic, but this how it works.
I am gonna now building up my lightning node again from scratch with a good feeling. Trust is all that matters.
