### ISSUE TITLE
Stuck resumed payment

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5152]
### Background

I have a resumed payment that is stuck with an in-flight HTLC (according to `listpayments`), but there is no HTLC on the channel. The channel is active, but the payment doesn't resolve. Restarting the sending node doesn't change that.

### Your environment

`v0.12.1-beta` / linux / bitcoind

### Steps to reproduce

* Two nodes Alice and Bob, connected with a single channel
* Alice is patched to crash right after this log statement if `state.numShardsInFlight == 1`
https://github.com/lightningnetwork/lnd/blob/d85d82824ca5ce7da6434c589e32aa41130a6074/routing/payment_lifecycle.go#L143
* Send 1 sat payment from Alice to Bob
* Alice crashes on the patched line above
* Rebuild Alice without the patch
* Start Alice again
* Payment is now stuck and doesn't seem to resolve

### Expected behaviour

Payment resolves after channel is re-established.

### Actual behaviour

Payment is stuck and doesn't seem to resolve. Restarting doesn't help.

Log file attached that results from repro scenario. Payment hash is `522cf981d2aac7c284b460f42f65d4c82e52652cb0a0426c34b6967be943208d`

[lnd.log](https://github.com/lightningnetwork/lnd/files/6221155/lnd.log)

**Comment by halseth** [comment]
Related? https://github.com/lightningnetwork/lnd/issues/4788#issuecomment-804093718

**Comment by Roasbeef** [comment]
Also possibly related: https://github.com/lightningnetwork/lnd/issues/4501

**Comment by Roasbeef** [comment]
I believe this was resolved by: https://github.com/lightningnetwork/lnd/pull/5214
