### ISSUE TITLE
unable to start server: unmatched backend error: -26: mempool min fee not met, 183 < 551

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#5160]
### Background

When I attempt to start `lnd`, it stops with the error message in title.

### Your environment

* version of `lnd` 0.12.1
* which operating system (`uname -a` on *Nix) `Linux <censored> 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend bitcoind 0.20.0
* any other relevant environment details

### Steps to reproduce

1. Upgrade LND to 0.12.0
2. Let it run for a while
3. shut it down
4. delete macaroons
5. restart LND
6. Wait a bit

### Expected behaviour

LND starts and keeps running

### Actual behaviour

LND exits after a while with the message `unable to start server: unmatched backend error: -26: mempool min fee not met, 183 < 551`

**Comment by guggero** [comment]
This error comes from `bitcoind`. It doesn't accept a transaction that lnd tries to broadcast. Try lowering the min relay fee of `bitcoind`.

**Comment by Kixunil** [comment]
Ah, in the past I attempted to decrease the relay fee to be lower than the default but actually increased it. Oops. Fixing it helped.

Anyway, shouldn't LND know about the relay fee and adjust appropriately? `getmempoolinfo` can return the current fee.

**Comment by guggero** [comment]
True in theory. Though RBF is tricky in itself. And some transactions aren't single signed by `lnd` (force-close transactions, external funding TXns), so there isn't anything to be done anyway.

Closing the issue since increasing the fee rate fixed the error.

**Comment by Kixunil** [comment]
OK, that makes sense. A slight improvement would be if the message didn't mention "unmatched" error as my understanding was that LND doesn't understand it (is incompatible). Not sure how hard it is/if it's worth the effort.
