### ISSUE TITLE
gRPC port does not get exposed

### ISSUE THREAD

**Issue by madhms** [lightningnetwork/lnd#5161]
### Background

On mobile `--rpclisten` has no effect. The port does not get exposed whereas `--restlisten` works but can't handle requests because there is no gRPC server listening.

It would be great to have that working on mobile.

### Your environment

* v0.12.1-beta
* Android
* btcd v0.21.0-beta (Neutrino)

**Comment by hsjoberg** [comment]
I'm not sure why you want to host the gRPC server on mobile. The current solution in doing it "in-memory" is far superior. https://github.com/lightningnetwork/lnd/tree/master/mobile

Anyway unless something critically has changed, it is possible to host a gRPC server, at least on Android:

https://github.com/hsjoberg/blixt-wallet/tree/4c3247410dca08f7ba7623992a10e08b9587f250/android/app/src/main/java/com/blixtwallet

**Comment by madhms** [comment]
Okay I understand. I just thought it would be nice to be able to connect to the node directly even on mobile but yes ofc you could create a seperate gRPC/http server to communicate with the in-memory gRPC.
