### ISSUE TITLE
gRPC Python KeyError Raised During UpdateChannelPolicy When global=True Is Set

### ISSUE THREAD

**Issue by cryptosharks131** [lightningnetwork/lnd#5163]
### Background
When trying to set the `global` variable for the PolicyUpdateRequest gRPC endpoint in python, a KeyError is raised.

Example:
`stub.UpdateChannelPolicy(ln.PolicyUpdateRequest(global=True, base_fee_msat=1000, fee_rate=0.000001, time_lock_delta=40))`

Will result in the following python error:
`KeyError: 'global'`

### Your environment
Lnd: lncli version 0.12.1-beta commit=v0.12.1-beta
OS: Windows
Backend: bitcoind
Python 3.8.5
### Steps to reproduce

Try to execute the UpdateChannelPolicy via gRPC and python while also setting the `global` variable to `True`.  As per the below documentation:
https://api.lightning.community/?python#updatechannelpolicy

### Expected behaviour

The expected behavior is to update all channel policies without specifying a channel point.

### Actual behaviour

Conflict causing a key error while trying to set `global` variable.

### Work-around

I was able to solve this issue by manually editing my `rpb_pb2.py` file and changing the name of the variable from `global` to `target_all`.  I am then able to set the variable properly and the expected result is observed.

Example:
`stub.UpdateChannelPolicy(ln.PolicyUpdateRequest(target_all=True, base_fee_msat=1000, fee_rate=0.000001, time_lock_delta=40))`

Result:
All channel policies are updated.

### Proposed Solution
Update the variable name for this gRPC endpoint to something other than `global` to avoid any clashes in python.

Potential remediation:
https://github.com/cryptosharks131/lnd/commit/973ced1529d21bf3b53206e60b80ee3daa2ad9e0

**Comment by cryptosharks131** [comment]
I was able to validate the above mentioned fix after rebuilding `rpc_pb2.py` with the updated `rpc.proto` file.  I have opened a pull request to rename the gRPC variable to `update_all` and to remediate the issue under pull request #5164.

**Comment by guggero** [comment]
Sorry for only getting back to you on this so late. I don't think renaming a field in the RPC is the correct solution. This would potentially break other people that rely on the field name.

Can you try this instead?

```
args = {'global': True, 'base_fee_msat': 1000, 'fee_rate': 0.000001, 'time_lock_delta': 40}
stub.UpdateChannelPolicy(ln.PolicyUpdateRequest(**args))
```

See https://stackoverflow.com/questions/4179175/python-named-argument-is-keyword.

**Comment by cryptosharks131** [comment]
> Sorry for only getting back to you on this so late. I don't think renaming a field in the RPC is the correct solution. This would potentially break other people that rely on the field name.
> 
> Can you try this instead?
> 
> ```
> args = {'global': True, 'base_fee_msat': 1000, 'fee_rate': 0.000001, 'time_lock_delta': 40}
> stub.UpdateChannelPolicy(ln.PolicyUpdateRequest(**args))
> ```
> 
> See https://stackoverflow.com/questions/4179175/python-named-argument-is-keyword.

I can confirm this does allow you to use the existing variable name to update all channels as well.

**Comment by guggero** [comment]
> I am not sure how regenerating the other proto files affects the lnd binary's gRPC interface but with just the single change to rpc.proto, existing gRPC users are not affected as they would have to rebuild their rpc_pb2.py from the new rpc.proto in order to observe the effect of the variable change.

The native golang gRPC interface (and all interfaces for other languages) are generated from `rpc.proto`. So renaming the field will affect all API users. Therefore I'm in favor of documenting this special case in the Python documentation for the RPC instead of renaming the field itself.

**Comment by cryptosharks131** [comment]
I agree, that seems like the easiest thing to do in this case.

To help facilitate this, I have reverted the variable change on the attached pull request and pushed an update for the documentation to reflect this special scenario.
