### ISSUE TITLE
Add support for sending partial payment to invoices

### ISSUE THREAD

**Issue by derekbeau** [lightningnetwork/lnd#517]
## Reproduce
Testing using the [Stage 1 Tutorial](http://dev.lightning.community/tutorial/01-lncli/index.html)

- Alice creates a payment request for 4000 SAT
- Bob sends 1000 SAT `lncli-bob sendpayment --amt=1000 --pay_req=<ALICE_REQUEST>`
- Result: Bob sends 4000 SAT to Alice and payment request is settled

Not sure if I am doing the command wrong or if `--amt` is not supported with a specific `--pay_req`

## Suggestion
I believe invoices should accept partial amounts for the following benefits:

- User can make "installment" payments over time
- Reduces reliance on channel capacity
  - Partial payments can be sent from multiple channels the user controls (allowing total LN balance to function as a single wallet, rather than fragmented across channels)
  - Partial payments can be sent across multiple routes connecting to the recipient
  - Partial payments can be streamed over a single route to fulfill the invoice

One of the biggest criticisms I have seen of LN is that of channel capacity. There is a decreasing probability of finding a sufficient route as both the payment amount and number of hops increases.

Allowing partial payments enables LN micro-payments to be used for larger invoices.

**Comment by Roasbeef** [comment]
`--amt` is not meant to be used with `--pay_req`. The payreq contains all information required to complete the payment. 

Partial payments can already be executed: the receiver just gives out multiple payment requests.

**Comment by derekbeau** [comment]
But then wouldn’t the requesting party need to know route capacities in order to issue payment requests in proper denominations?

What I’m thinking is a way to give more tools to sending wallets for successfully filling payment requests.

**Comment by MrHash** [comment]
I don't think it is up to the payer to decide how much to pay of the invoice. If the payer wants to pay instalments, the seller has the prerogative to generate multiple invoices.

**Comment by cfromknecht** [comment]
Doing installments for the same payment request is also unsafe because you would be reusing the same payment hash/preimage. Intermediaries could take your money without actually ensuring delivery to the intended recipient.

**Comment by halseth** [comment]
Partially paying a given invoice is not currently supported. AMPs will make it possible to pay parts using multiple routes, but still the full amount must be paid.
