### ISSUE TITLE
Can not "make install" - "Error 2"

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [lightningnetwork/lnd#5174]
### Background
I am trying to install lnd on my Raspberry PI4. When running "make install" I get thrown out with

`pi@raspberrypi:~/code/lnd $ make install
 Installing lnd and lncli.
GO111MODULE=on go install -v -tags="" -ldflags " -s -w -X github.com/lightningnetwork/lnd/build.Commit=v0.12.1-beta-dirty -X github.com/lightningnetwork/lnd/build.CommitHash=d233f61383f2f950aa06f5b09da5b0e78e784fae -X github.com/lightningnetwork/lnd/build.GoVersion=go1.11.6 -X github.com/lightningnetwork/lnd/build.RawTags=" github.com/lightningnetwork/lnd/cmd/lnd
github.com/lightningnetwork/lnd/build
github.com/lightningnetwork/lnd/lntest/channels
github.com/lightningnetwork/lnd/healthcheck
github.com/lightningnetwork/lnd/lnwallet/chainfee
github.com/lightningnetwork/lnd/peernotifier
github.com/lightningnetwork/lnd/lnrpc/autopilotrpc
github.com/lightningnetwork/lnd/lnrpc/chainrpc
github.com/lightningnetwork/lnd/batch
github.com/lightningnetwork/lnd/lnwallet/chanfunding
github.com/lightningnetwork/lnd/channeldb
github.com/lightningnetwork/lnd/lnrpc/signrpc
github.com/lightningnetwork/lnd/lnrpc/watchtowerrpc
github.com/lightningnetwork/lnd/lnpeer
github.com/lightningnetwork/lnd/routing/chainview
github.com/lightningnetwork/lnd/invoices
github.com/lightningnetwork/lnd/chainntnfs
github.com/lightningnetwork/lnd/chanbackup
github.com/lightningnetwork/lnd/channelnotifier
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify
github.com/lightningnetwork/lnd/chainntnfs/btcdnotify
github.com/lightningnetwork/lnd/lnwallet
github.com/lightningnetwork/lnd/chainntnfs/neutrinonotify
# github.com/lightningnetwork/lnd/lnwallet
lnwallet/wallet.go:41:45: syntax error: unexpected _000, expecting comma or )
note: module requires Go 1.13github.com/lightningnetwork/lnd/chanfitness
make: *** [Makefile:145: install] Fehler 2
pi@raspberrypi:~/code/lnd $ 
`

### Your environment

* version of `lnd`
v0.12.1-beta
* which operating system (`uname -a` on *Nix)
Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

### Steps to reproduce

I just `make install`

### Expected behaviour

Installation

### Actual behaviour

Error message as named above

**Comment by Roasbeef** [comment]
You need to upgrade your Go version.

**Comment by AkumaNoTsubasa** [comment]
I installed go version go1.11.6 linux/arm from official distro. On which do I need to upgrade?

**Comment by Roasbeef** [comment]
I'd recommend updating to 1.15.9, we usually track the last two major go release (so the past year or so of releases).
