### ISSUE TITLE
Fee Limit: percentage and hard value cannot be both be set

### ISSUE THREAD

**Issue by kaloudis** [lightningnetwork/lnd#5176]
It would be nice if when setting a fee limit on `SendPaymentSync` you could set both a fixed value and a percentage of the amount you're sending. You can enforce both and set the limit to the smaller of the two values.

If I get enough ACKs on this I'll take a stab at implementing this myself

https://github.com/lightningnetwork/lnd/blob/b4b7f2972442703fff59a881116bc9855f9ce305/cmd/lncli/cmd_pay.go#L197

**Comment by Roasbeef** [comment]
> You can enforce both and set the limit to the smaller of the two values.

So this can just be done at the caller, no?

**Comment by kaloudis** [comment]
Yes this can all be done client side
