### ISSUE TITLE
Monitoring WT client - insufficient runtime info and/or insufficient documentation

### ISSUE THREAD

**Issue by svewa** [lightningnetwork/lnd#5183]
I run 0.12.1-beta, and have a WT configured. I need to figure out if the WT is actually doing it's job, at least as far as the client can determine this.
> wtclient tower/towers
and
> wtclient stats 
> {
>     "num_backups": 6,
>     "num_pending_backups": 6,
>     "num_failed_backups": 0,
>     "num_sessions_acquired": 4,
>     "num_sessions_exhausted": 1
> }

it seems nothing can reliably tell me if the WT accepted my channel states. Like the output above tells me that all the 6 backups are also "pending" - sounds to me like they were **not** successfully committed to the WT. Yet the WT debug log tells me:

> [DBG] WTWR: State update 6 accepted for XX
> [DBG] WTWR: Sending MsgStateUpdateReply(code=0 last_applied=6) to XX

and similarly on the client:
> [INF] WTCL: (legacy) SessionQueue(XX) uploaded backup(XX, NNNN) seqnum=6

So is the "num_pending_backups" broken and should actually be zero, as all backups have successfully been commited? If not, what is the meaning of num_pending_backups?

What can I figure out from the output of `lncli wtclient towers`? adding/removing a WT does not actually add/remove the WT from there, but just changes the `active_session_candidate`. I always have a positive number of sessions, and an empty session array - which confuses me.

Before I dug into this today, I noticed my WT crashed 2 weeks ago. The `lncli wtclient stats` was basically the same as above, with num_backups=num_pending_backups=210 - but with the WT being down and the output looking just like with a running WT... no help from the command.

**Comment by wpaulino** [comment]
> So is the "num_pending_backups" broken and should actually be zero, as all backups have successfully been commited? If not, what is the meaning of num_pending_backups?

I've confirmed this is a bug, the `num_pending_backups` field isn't decremented at the moment when a backup is accepted. I'll open a PR to fix this.

> What can I figure out from the output of lncli wtclient towers? adding/removing a WT does not actually add/remove the WT from there, but just changes the active_session_candidate. I always have a positive number of sessions, and an empty session array - which confuses me.

`lncli wtclient towers -h` is your friend, you can also use `-h` on any of its subcommands. Adding/removing a tower depends on the parameters used, e.g. if you provide an address, then that address will be added/removed. If you provide just the tower pubkey, the tower as a whole is added/removed. As for the sessions being empty, you need to use the flag `--include_sessions`. We added this flag to make the command output easier to glance.
