### ISSUE TITLE
Speed up TLS generation step on slow/32-bit platforms

### ISSUE THREAD

**Issue by camalolo** [lightningnetwork/lnd#519]
Here is what I see in the logs : 

2017-12-25 06:51:43.003 [INF] LTND: Version 0.3.0-alpha
2017-12-25 06:51:43.047 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2017-12-25 06:51:43.075 [INF] RPCS: Generating TLS certificates...

Nothing happens after that. As far as I can tell there was no error showing up anywhere (including when running lnd with -d trace). It just waits forever.

I found there's a "gencerts" utility in my gocode/bin directory, tried to generate a TLS certificate pair and move it to .lnd/tls.cert and .lnd/tls.key and it works :

2017-12-25 06:54:33.228 [INF] LTND: Version 0.3.0-alpha
2017-12-25 06:54:33.230 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2017-12-25 06:54:33.500 [INF] RPCS: password gRPC proxy started at localhost:8080
2017-12-25 06:54:33.501 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2017-12-25 06:54:33.501 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.

Built following the installations instructions on this architecture :

Linux DiskStation 3.2.40 #5967 Fri Nov 3 17:20:31 CST 2017 armv7l GNU/Linux

**Comment by Roasbeef** [comment]
If you're running on a constrained platform, then cert generation may take a bit of time. 

Can you give a bit more details w.r.t your hardware specs?

**Comment by camalolo** [comment]
The machine is a Diskstation DS213j, the specs are as follow : 

![image](https://user-images.githubusercontent.com/331741/34338137-aab6f72e-e9a0-11e7-9f16-ef2d94dc6406.png)

But the thing is, when I use the gencerts command line utility, it generates the certificates in 2-3 seconds. And it seems those certs are usable by lnd, if I generate them myself lnd seems to load normally past the point where certs are  initially created.

**Comment by halseth** [comment]
I suspect that gencerts is generating simpler certs than `lnd`.  I think`lnd` currently generates 4096 bit RSA certificates. 

How long did you wait for the certificates to finish being created before you gave up?

Could you try
1) Generate a RSA-4096 certificate with gencerts? `lnd` configuration is found here: https://github.com/lightningnetwork/lnd/blob/63517a1eef477cee84a8c9cab036af5a3bd3ee60/lnd.go#L538
2) Let `lnd` run for a while to check if it eventually finishes? I have seen certificate creation taking about 1 minute on iPhone 6, and I believe your platform is significantly slower.

**Comment by camalolo** [comment]
Hello halseth, you were right, I was just being impatient.

It works but just takes more than a minute :

![image](https://user-images.githubusercontent.com/331741/34546431-bbf23a40-f12e-11e7-87ab-259eb3ae07dd.png)

Regarding gencerts : it came with btcd, and via the command line it does not allow to specify the configuration for the keys generation as far as I can tell. I checked the code, it uses a different private key generator from the one in lnd. This very likely explains the difference in generation time ?

In lnd :
priv, err := rsa.GenerateKey(rand.Reader, 4096)

In btcd's gencerts :
priv, err := ecdsa.GenerateKey(elliptic.P521(), rand.Reader)

Closing this issue, thank you !

**Comment by halseth** [comment]
Cool, it just confirms that ECDSA is much faster than RSA on these platforms.

Keeping issue open for tracking enhancing this!

**Comment by halseth** [comment]
Cool, it just confirms that ECDSA is much faster than RSA on these platforms.

Keeping issue open for tracking enhancing this!

**Comment by Roasbeef** [comment]
We've switched to ecc certs by default (in #776) , so the start up time of a fresh installation has been drastically reduced.
