### ISSUE TITLE
High CPU spikes with v0.12.1-beta

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#5191]
### Background

<img src="https://github.com/miketwenty1/images/blob/master/highcpu.png?raw=true" width="800" height="200" />

We have high CPU spikes on the exact 30 minute mark of most hours throughout the day. Seems like some cron/batch process?

### Your environment

* version of `lnd`

v0.12.1-beta

* which operating system (`uname -a` on *Nix)

ubuntu 20.04

* version of `btcd`, `bitcoind`, or other backend

bitcoind (zmq) 0.21.0

* any other relevant environment details

LND is the cause of the CPU spikes verified by running `htop` during one of the spikes.
Logs don't show anything that constitutes a pattern with the spikes. 
Running an EC2 ubuntu instance t3.medium. (2 CPU, 4 GB RAM)

### Steps to reproduce
run 0.12.1-beta - using docker image

### Expected behaviour

Maybe CPU spikes every week? for auto db compaction, but not every hour.

________________
Any chance you know why this is happening?, or would you be able to instruct on how to get more information to help debug this?

**Comment by Roasbeef** [comment]
We landed a PR in master recently that'll ensure if we fail validating a chan ann, then all the other updates are ignored as well. I looked at the reject cache and realized it doesn't always add failed channel announcements to the cache, which is fixed here: https://github.com/lightningnetwork/lnd/pull/5192 

I see this at times myself, AFAICT, there're nodes that for some reason have never removed closed channels, so then they'll continually re-send them, nodes validate them, realized they're closed, the the cycle repeats. That PR I linked _should_ finally fix this, once and for all.

**Comment by miketwenty1** [comment]
We are running 213b264e4c0f92a23c7dd8a42e0b68e4958a7e3a 
After about a week we see spikes coming in again, however not quite as frequently.. at least not yet. We also noticed it took about 1 week for the spikes to happen on 0.12.1-beta for us as well. 
I think this would warrant a re-opening of this issue?
<img src="https://github.com/miketwenty1/images/blob/master/less_frequent_spikes.png?raw=true" width="800" height="200" />

**Comment by wpaulino** [comment]
We'll need CPU profiles to tell what's going on. Enable the profile flag on your node (flag takes a port to listen on) and whenever you experience high CPU usage, you can ran `curl http://localhost:PROFILE_PORT/debug/pprof/profile` and provide the resulting file here.

**Comment by Roasbeef** [comment]
@miketwenty1 I think you might've referenced the wrong commit hash?

**Comment by wpaulino** [comment]
Ah yeah, the commit should be https://github.com/lightningnetwork/lnd/commit/d5aedbcbd9db510c974c9f7be5ab177ad6546994 or later.

**Comment by miketwenty1** [comment]
referring to https://github.com/lightningnetwork/lnd/issues/5191#issuecomment-816989400
> We landed a PR in master recently ...

The impression was master at the time was a good choice. (213b264). So are you sure this is the wrong commit hash?

Would you recommend getting a CPU profile first on the current version or bumping to d5aedbc ?

**Comment by wpaulino** [comment]
There's two PRs which should both help, #5133 and #5192. @Roasbeef was referring to #5133 at the time, so if you pulled master then, you only have that one. You should bump to https://github.com/lightningnetwork/lnd/commit/d5aedbcbd9db510c974c9f7be5ab177ad6546994 and enable profiling.

**Comment by miketwenty1** [comment]
will look into this and report back when i have some data.
