### ISSUE TITLE
only run a watchtower server

### ISSUE THREAD

**Issue by kingwkb** [lightningnetwork/lnd#5195]
I try to run a watchtower server from https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md
and run `lnd --tor.active --tor.v3 --watchtower.active`
get error: loadConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

**Comment by Roasbeef** [comment]
You need to pick one of those chains. Set either of the arguments to have the tower boot up on your target chain.
