### ISSUE TITLE
Memory gradually increasing for 0.12.1-beta

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#5197]
### Background

<img src="https://github.com/miketwenty1/images/blob/master/increasingmem.png?raw=true" width="800" height="200" />

We have high memory on our node increasing steadily

### Your environment

* version of `lnd`

v0.12.1-beta

* which operating system (`uname -a` on *Nix)

ubuntu 20.04

* version of `btcd`, `bitcoind`, or other backend

bitcoind (zmq) 0.21.0

* any other relevant environment details

Referring to:
#5191 
@Roasbeef Would the #5192 fix, be related/fix this memory issue as well?

### Steps to reproduce
run 0.12.1-beta - using docker image

### Expected behaviour

Memory hold steady, fluctuates, but returns to "normal" levels.
________________
Any chance you know why this is happening?, or would you be able to instruct on how to get more information to help debug this?

**Comment by Roasbeef** [comment]
If you do a memory profile using `go tool pprof` you can get a precise break down w.r.t where memory is being alloacted. Also if you run Go 1.16, then memory is released more readily back to the operating system from the Go runtime.

**Comment by Roasbeef** [comment]
Also are you able to run master on this node? It has a fix to an issue that didn't make its way in to 0.12.1. Fair warning though, it has a migration, so you won't be able to go backwards.

**Comment by miketwenty1** [comment]
noted on the migration.

Question for running `go tool pprof`
I'm using the official docker image you guys released for 0.12.1-beta.
Seems that you are moving the binaries over from a builder image.
Would you have a recommended approach for running `go tool pprof` ?

**Comment by wpaulino** [comment]
> Would you have a recommended approach for running go tool pprof ?

You could expose the port from the container such that only the host running the container can access it.

> instead of running #5192 The current plan is to run master. Do you envision a 0.12.2 release for resource usage issues?

There are no plans for 0.12.2 as of yet, the next release will be the major version 0.13.0.

**Comment by miketwenty1** [comment]
good idea, thanks. 
Already upgrade to master commit, so I won't be able to profile this issue.. But good to know for next time.

**Comment by miketwenty1** [comment]
memory issue from 0.12.1-beta (to any relative severity from the original issue) is gone with recent commits.. will reopen if needed with future version. 
much improved! gj fellas

**Comment by miketwenty1** [comment]
memory issue from 0.12.1-beta (to any relative severity from the original issue) is gone with recent commits.. will reopen if needed with future version.
much improved! gj fellas
