### ISSUE TITLE
Allow a chain backends to connect to multiple sources

### ISSUE THREAD

**Issue by Alonzo-Coeus** [lightningnetwork/lnd#520]
Most large businesses have two or more bitcoin nodes just in case one goes offline. So it would be useful for a lightning node to be able to use backup nodes to make nodes more stable. How
How would you prefer this to be implemented. I was thinking of having and array of host addresses in the config file.

ps: i would like to work on this, if you think it is something we need

**Comment by sangaman** [comment]
+1 I think this would be a very handy feature.

**Comment by saubyk** [comment]
Closing this issue, as the requirement has not been expressed by users at all in the past 6 years or so.
