### ISSUE TITLE
Can't open a channel using Eclair Mobile (Static Remote Key issue?)

### ISSUE THREAD

**Issue by eduardof84** [lightningnetwork/lnd#5211]
Hi LND team,
I am running LND v0.12.1-beta on my Umbrel node.  Now I am trying to open a channel from my Eclair Mobile wallet and the response is: "Failed to open channel: incompatible features"   according to other Eclair users this is due to the Static Remote Key feature required on LND 0.12.0 - anyway I can change this setting to progress with the channel opening using Eclair? 
Thanks in advance

**Comment by Roasbeef** [comment]
Static remote key makes channels safer as you don't need a random value from the other side to recover your funds if they force close. You'll have to ask the eclair devs if/when they'll be adding the feature. I think maybe the Phoenix wallet supports it, but Eclair mobile itself doesn't.

**Comment by eduardof84** [comment]
Thanks, the benefits of the setting make sense, however would it be possible to change this if the user wanted to?

**Comment by eduardof84** [comment]
> Static remote key makes channels safer as you don't need a random value from the other side to recover your funds if they force close. You'll have to ask the eclair devs if/when they'll be adding the feature. I think maybe the Phoenix wallet supports it, but Eclair mobile itself doesn't.

Thanks, the benefits of the setting make sense, however would it be possible to change this if the user wanted to?
