### ISSUE TITLE
REST API /v1/channels results in error when adding peer query parameter

### ISSUE THREAD

**Issue by Czino** [lightningnetwork/lnd#5216]
### Background

I am trying to pull channel information based on the public key of my peers via the REST API.
The same call without the query parameter `peer` works fine, albeit giving me the whole list of channels. But as soon as I add it, I get an error message.

Describe your issue here.
```
curl -i -X GET --cacert "$tlscert" --header "$MACAROON_HEADER" "https://127.0.0.1:8080/v1/channels?peer=${node_id}"
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Thu, 15 Apr 2021 18:24:52 GMT
Content-Length: 119

{"error":"illegal base64 data at input byte 64","code":3,"message":"illegal base64 data at input byte 64","details":[]}
```

LND seems to be expecting base64 here. But even if I naively try to base64-encode the node_id, it won't work and results in a malformed URL error.

I am not entirely sure I am missing something crucial with curl but I also cannot find an example how to add the `peer`query parameter.

### Your environment

* version of `lnd`: 0.12.1-beta
* which operating system (`uname -a` on *Nix): Linux raspberrypi 5.4.51-v7l+ #1333
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details

### Steps to reproduce

```
macaroon="PATH/TO/macaroon"
MACAROON_HEADER="Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 $macaroon)"
tlscert="PATH/TO/tsl.cert"
node_id="A_PEERS_NODE_ID"

curl -i -X GET --cacert "$tlscert" --header "$MACAROON_HEADER" "https://127.0.0.1:8080/v1/channels?peer=${node_id}"
```

### Expected behaviour

LND REST API returns the channel data for given peer

### Actual behaviour

400 Bad Request

**Comment by wpaulino** [comment]
Are you decoding the node ID from hex into raw bytes (should result in 33 bytes) and then converting those bytes into base64? There was an intance similar to this issue in the past (https://github.com/lightningnetwork/lnd/issues/3168) which pointed out a bug in our gRPC-REST dependency, but that's been resolved now.

**Comment by Czino** [comment]
Thanks for the quick response.

I haven't decoded the node_id from hex into raw bytes and then to base64 as this is not pointed out in the [docs](https://api.lightning.community/#v1-channels)

The raw bytes are indeed 33bytes. I tried to plug that in as base64 but the results are similar. Should the conversion to rawbytes be wrong, please let me know.

```
curl -i -X GET --cacert "$tlscert" --header "$MACAROON_HEADER" "https://127.0.0.1:8080/v1/channels?peer=$(echo "$node_id" | xxd -r -p | base64)"
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Fri, 16 Apr 2021 07:46:25 GMT
Content-Length: 119

{"error":"illegal base64 data at input byte 22","code":3,"message":"illegal base64 data at input byte 22","details":[]}
```

**Comment by wpaulino** [comment]
Ah, you need to make sure you're using [URL encoding when converting to base64](https://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url), which the `base64` util does not provide. I tried it and confirmed it works.

**Comment by Czino** [comment]
Thanks a lot that makes sense. For future reference this is how I sucessfully make the request now

`curl -G --cacert "$tlscert" --header "$MACAROON_HEADER" --data-urlencode "peer=$(echo "$node_id" | xxd -r -p | base64)" "https://127.0.0.1:8080/v1/channels"`
