### ISSUE TITLE
unknown option: coop-close-target-confs

### ISSUE THREAD

**Issue by jlopp** [lightningnetwork/lnd#5219]
### Background

Trying to run lnd with this option in lnd.conf

### Your environment

lnd v0.12.1-beta
Ubuntu 20.04
Bitcoin Core 0.21.0

### Steps to reproduce

Create lnd.conf with the following:

[Application Options]
coop-close-target-confs=20

and run lnd

### Expected behaviour

lnd should start up successfully

### Actual behaviour

Error output: "unknown option: coop-close-target-confs"

**Comment by jlopp** [comment]
It looks like perhaps this is no longer a real option, but it has vestigal code in config.go and still exists in the sample lnd.conf

**Comment by alexbosworth** [comment]
Isn't this a future LND option and so it wouldn't work on older versions like 0.12.1?

**Comment by jlopp** [comment]
Whoops, I shouldn't have been looking at the sample conf in master
