### ISSUE TITLE
[Feature Request] Ability to prevent any offchain payments toward us

### ISSUE THREAD

**Issue by junderw** [lightningnetwork/lnd#5223]
In the event that we want to prevent people from sending money to us:

1. Never create any invoices (done, all we need to do is not expose any invoice API)
2. Disable keysend receives
3. Reject open channel requests that attempt to push sats to us

2 and 3 would probably be config file boolean values to toggle.

**Comment by junderw** [comment]
Clarification: 1 is not asking for ability to disable addinvoice etc. I am just saying that we can choose to not create any invoices and it will prevent deposits... so 1 needs no intervention.

**Comment by carlaKC** [comment]
This should all be covered by lnd's existing feature set: 
1. Don't add any invoices, as you say
2. Keysend is disabled by default, so no changes needed 
3. There is a `--rejectpush` option which will prevent any push amount channels

Another option that could be useful to you, depending on use case is `--rejecthtlc` which will prevent your node from forwarding any htlcs on its public channels. 

Hope this helps! Feel free to reopen if anything is unaddressed.
