### ISSUE TITLE
Payment Route Chan ID Recorded Does Not Match Actual Chan ID Observed Being Used

### ISSUE THREAD

**Issue by cryptosharks131** [lightningnetwork/lnd#5240]
### Background

I have found that when doing circular payments in an effort to rebalance channels, the channel lnd has recorded as being used for the last hop in the payment `htlcs` does not match what I am visually observing while monitoring my inbound/outbound liquidity values via `listchannels`.

Specifically this occurs when I have two open channels with my last hop peer and both channels have sufficient liquidity to complete the transaction.  It appears lnd will find a valid path and record it but it will not necessarily use that path in the end if there are duplicate valid channel paths between peers.

Further, I am using a custom monitoring tool similar to loop that visualizes your channel balances.  It also uses custom rebalancing scripts to keep channels within a desired liquidity target.  At the same time, I record the successful payment details from `listpaymets` once the payment completes, specifically the `htlcs` to analyze the successful route later and this is where I can see the discrepancy.

I target a channel id, the payment is requested, it is successful and the route is recorded. However, the payment route recorded the channel id I did not target in my calculations.  Now this should mean I still need to target the same channel id again since it did not get used (you only control last hops via pubkey) but I find that it did indeed get used and the rebalancing is completed.

This does not seem to have any negative affect outside of recording the wrong channel id in the payment htlcs of `listpayments` and the payment route still makes sense since the list of peer pubkeys used in each hop is valid.

### Your environment

* version of `lnd`: `lnd version 0.12.1-beta commit=v0.12.1-beta`
* which operating system (`uname -a` on *Nix): `Ubuntu`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind`
* any other relevant environment details: `N/A`

### Steps to reproduce

1. Create two channels with the same peer, make sure they both have inbound liquidity
2. Use that peer's pubkey as the last hop in the payment request (must have sufficient liquidity on both channels for the payment)
3. Observe change in channel inbound/outbound liquidity
4. Confirm if the visual change you saw via `listchannels` inbound/outbound liquidity matches the recorded value in `listpayents` for your last hop peer

### Expected behavior

Expected behavior is to record the correct channel id used when there were two potential paths available for the return payment.

### Actual behavior

It seems that a valid path of pubkeys is recorded in `listpayments` however it is not necessarily the correct path of channel ids used for the payment.  Actual behavior appears to be recording the calculated route instead of the post-payment actual route of channel ids used.

**Comment by Roasbeef** [comment]
> Specifically this occurs when I have two open channels with my last hop peer and both channels have sufficient liquidity to complete the transaction

This is due to the fact that we randomize which link is used when we receive a forwarding request that can travel over multiple channels. In practice, when a node has multiple channels with another node, they are free to choose which channel they used when forwarding, and the sender has no way to properly restrict in practice.

**Comment by Roasbeef** [comment]
Relevant location in the code: https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L1091 

Closing as this behavior is expected.
