### ISSUE TITLE
Documentation indicates lnd will run with bitcoind using cookie authentication for RPC, but it throws an error

### ISSUE THREAD

**Issue by de6df1re** [lightningnetwork/lnd#5241]
### Background
This is either an issue with the documentation or the implementation: 

* The lnd documentation states lnd can be run with bitcoind using cookie authentication here: [https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#using-bitcoind-or-litecoind](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#using-bitcoind-or-litecoind) "The auth parameters rpcuser and rpcpass parameters can typically be determined by lnd for a bitcoind instance running under the same user, including when using cookie auth. In this case, you can exclude them from the lnd options entirely."

* When running lnd with bitcoind as a backend, if rpcuser and rpcpassword are not set in bitcoind environment, bitcoind uses cookie authentication for rpc as documented here: [https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/doc/init.md](https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/doc/init.md)

* When bitcoind is running with cookie authentication for RPC, lnd checks explicity for rpcuser and rpcpassword and if they do not exist an error is generated.  This is implemented on lines 1496-1503 in config.go ... here: [https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/doc/init.md](https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/doc/init.md)

### Your environment

* version of `lnd`: lnd version 0.12.1-beta commit=v0.12.1-beta
* which operating system (`uname -a` on *Nix): Linux 5.8.0-1021-raspi #24-Ubuntu SMP PREEMPT Tue Apr 13 11:00:57 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind Bitcoin Core version v0.21.0
* any other relevant environment details

### Steps to reproduce

- install run, and sync bitcoind Bitcoin Core version v0.21.0 with no rpcuser or rpcpassword set (forcing bitcoind to use cookie authentication)
- install lnd, do not include rpcuser or rpcpassword in .lnd/lnd.conf

### Expected behavior

* config.go should not throw an error, unless it is not possible (or recommended) for lnd to use bitcoind with cookie authentication

### Actual behaviour

* Receive this error message:  "unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpcpass, bitcoind.zmqpubrawblock, bitcoind.zmqpubrawtx"

**Comment by guggero** [comment]
Can you post your full `lnd` config here please? It sounds to me like you need to remove the ZMQ parameters from it as well as they are also read from the `bitcoin.conf` (and the example in the `INSTALL.md` file is wrong).

**Comment by de6df1re** [comment]
Your solution is correct and resolved the issue.  Removing both ZMQ parameters from lnd.conf resulted in this response when running lnd: 

> Attempting automatic RPC configuration to bitcoind
> Automatically obtained bitcoind's RPC credentials

**Comment by guggero** [comment]
I read the documentation again and it isn't wrong per se, just not very clear. The section could definitely be improved.
Though the error message is pretty clear in what needs to be done IMO. Closing for now, but feel free to add a PR to improve the documentation.

**Comment by de6df1re** [comment]
Thank you
