### ISSUE TITLE
Feature request: add "wallet psbt process" API to partially sign UTXOs managed by the LND wallet

### ISSUE THREAD

**Issue by regata** [lightningnetwork/lnd#5243]
### Background

Currently LND supports creating and finalizing a PSBT:

```sh
lncli wallet psbt fund --outputs=<psbt inputs>
lncli wallet psbt finalize <psbt>
```

But it does not support partially signing (i.e. processing) psbt inputs without finalizing the transaction. This would be similar to `walletprocesspsbt` from bitcoin core: https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/walletprocesspsbt/

### Proposal

The lncli api could resemble bitcoin core:

```sh
lncli wallet psbt process --sign=true --sighash=ALL <psbt>
```

~~The GRPC API may have a new message type for `rpc FundingStateStep(FundingTransitionMsg)`~~:

```protobuf
message FundingTransitionMsg {
    oneof trigger {
        ...
        /*
        Used to update a PSBT with input information from our wallet and then sign inputs
        */
        FundingPsbtProcess psbt_process = 5;
    }
}
```

**Edit**

We can add a GRPC API to the wallet. Something along the lines:

```protobuf
# in walletkit.proto
rpc SignPsbt (SignPsbtRequest) returns (SignPsbtResponse);
```

If there are no objections, I can try to put a PR for this feature. Please let me know

**Comment by alexbosworth** [comment]
I'm not sure if this works for your intended use case but what if the `SignPsbt` method were simply changed to optionally only fill the BIP 174 signer role and allow for external finalization?

**Comment by regata** [comment]
Agree, it's better to add `SignPsbt` rather than couple it with `FundingStateStep`

**Comment by guggero** [comment]
Sounds good to me, PR is very welcome!

**Comment by bjarnemagnussen** [comment]
I will try to take a look at it and open PR.
