### ISSUE TITLE
`lncli stop` does not work forcing operator to kill Docker instance

### ISSUE THREAD

**Issue by andrerfneves** [lightningnetwork/lnd#5251]
### Background

For some odd reason on the `d51f61af252e30eb39e3c85dd366b525f89f9267` commit LND sometimes behaves weird, payments / routing fails and `lncli stop` stops working. I'm then forced to kill the docker instance forceably and 

### Your environment

* version of `lnd`
`d51f61af252e30eb39e3c85dd366b525f89f9267`

* which operating system (`uname -a` on *Nix)
Ubuntu 18.04

* version of `btcd`, `bitcoind`, or other backend
`0.21.0`

### Steps to reproduce

Haven't been able to point out what the issue is in order to reproduce the issue. It happens enough that we need to kill the instance once a week at this stage.

### Expected behaviour

`lncli stop` stops the machine.

### Actual behaviour

`lncli stop` does no change to the `lnd` instance

### Screen Recording

https://user-images.githubusercontent.com/2574011/116299997-5b008780-a76c-11eb-8b4a-baf9d983f1b4.mov

**Comment by guggero** [comment]
Weird. Could you please post the logs from the moment you issue the "stop" command onward?

**Comment by wpaulino** [comment]
Could be helpful to get a goroutine profile as well, see https://github.com/lightningnetwork/lnd/blob/master/docs/debugging_lnd.md#capturing-pprof-data-with-lnd.

**Comment by andrerfneves** [comment]
@guggero lncli logs from when `lncli stop` is ran here: https://paste.ubuntu.com/p/zccwFBfWjN/

@wpaulino gorouting logs here: https://paste.ubuntu.com/p/WvZ49pjr7j/

**Comment by wpaulino** [comment]
@andrerfneves can you confirm this node is indeed on commit `d51f61af252e30eb39e3c85dd366b525f89f9267`? The goroutine profile doesn't match the source code at that commit.

**Comment by andrerfneves** [comment]
@wpaulino seems like we're running `d5aedbcbd9db510c974c9f7be5ab177ad6546994` instead of `d51f61af252e30eb39e3c85dd366b525f89f9267`. Both `d5`s. Wonder if that's the issue, most likely?

Here are two other nodes, running the same commit and having the same problem. The nodes become unresponsive and `lncli stop` doesn't work. Channels and HTLCs also fail, and yet `lncli getinfo` and `lncli version` still work so we don't get alerted that the node is unreacheable/has problems.

https://paste.ubuntu.com/p/m5HDJQFJ5h/
https://paste.ubuntu.com/p/MXbYPvZC6H/

https://paste.ubuntu.com/p/xCmR6q4CBT/
https://paste.ubuntu.com/p/Nr82nSqDpd/

**Comment by wpaulino** [comment]
@andrerfneves I've opened https://github.com/lightningnetwork/lnd/pull/5258 to address the issue if you'd like to give it a try.

**Comment by andrerfneves** [comment]
@wpaulino I'll update to that PR on our dev lnd's tomorrow and will watch them accordingly. Thanks

**Comment by miketwenty1** [comment]
@wpaulino I see this is still open.  
Will be interested to run this after it's merged to master.
