### ISSUE TITLE
partial payment state after invoice timeout 

### ISSUE THREAD

**Issue by definitivequestion** [lightningnetwork/lnd#5261]
### Background
I tried transferring from the OKCoin exchange to my node, but apparently I didn't set the timeout long enough to pass through all the authentication steps for a withdrawal. The invoice must have been valid at the moment I submitted it to OKCoin, but it expired sometime before my node acknowledged it as received.
### Your environment

* lnd version 0.12.1-beta commit=v0.12.1-beta
* Linux myNode 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
* Bitcoin Core version v0.21.0
* Raspberry Pi 4 B 8 GB
* myNode 0.2.30
* ThunderHub 0.12.12

### Steps to reproduce

Since this is on mainnet, I do not know which implementations the intermediary nodes are using. I also don't know if this is reproducible since I don't have a machine to configure with regtest. However, I would try creating an invoice that will expire sometime after the sender checks the invoice expiration date, but before the network can find all routes and actually transmit the payment.

### Expected behaviour

Either the payment fails with the invoice expiration error, or the payment continues to route to the destination despite being expired.

### Actual behaviour

OKcoin has debited my account (but is saying withdrawal in progress), but my node has not acknowledged receipt of the funds.

This may be related to the following issues: #4788 #4501

**Comment by Roasbeef** [comment]
I recommend you open a support ticket with OKCoin. If your node has not received the funds, and they haven't fully sent the funds, then this will reflect on their node if they do `TrackPayment` with the payment hash. The payment will indeed fail if the payment is attempted _before_ the expiry, however it may continue if its attemped and then the invoice expires _during_ path finding.

**Comment by definitivequestion** [comment]
I have contacted OKCoin and they said they have escalated this to their technical department (the CS representative could only see that the payment is not marked as complete) so I will keep you posted.

**Comment by definitivequestion** [comment]
Things eventually resolved.
