### ISSUE TITLE
Channel balance reporting is inconsistent (lncli)

### ISSUE THREAD

**Issue by dipunm** [lightningnetwork/lnd#5263]
### Background

I've been trying to work out the exact balance in my LND node, and I am seeing discrepencies of upto 20sats. I have also used `faraday` which mostly matches my manual calculations. I need to understand the cause of discrepancies.

`lncli channelbalance`: Gives 28103202383msats
`lncli listchannels | jq '.channels[] | select(.active == true) | .local_balance'`: sums to 28103193000msats (28103193sats)

This is a discrepency of 9383msats (9 sats). Neither of these values match my calculations based on summing up all LND activity:

I manually summed the local channel opens and subtracted the close settlements and subtracted the fees from the close transactions where the channel open was initiated by my node. I ran `lncli closedchannels` and traversed the blockchain manually to find all the open and close transactions and found the following:
```
opened channels: 41619095000msats
closed channel settlements: 1250826000msats
closed channel fees (locally opened): 30421000msats
```

This gives me a balance of 40337848000msats. After then accounting for the routing fees, invoices and payments, I get a balance of 28494154790msats. I used the following commands:
```
lncli fwdinghistory --start_time -3y --max_events 900 | jq '.forwarding_events[].fee_msat'
lncli listinvoices --max_invoices 10000 | jq '.invoices[].amt_paid_msat'
lncli listpayments --max_payments 10000000 | jq '.payments[].fee_msat'
lncli listpayments --max_payments 10000000 | jq '.payments[].value_msat'
```

I realised I then had to subtract the channel commit fee reserves:
`lncli listchannels | jq '.channels[] | select(.initiator==true) | .commit_fee'`: sums to 390967000msats (390967sats)

A final balance of: 28103187790msats

This is a discrepency of 14593msats (15sats) from `lncli channelbalance`
And a discrepency of 5210 (5sats) from summing the output of `lncli listchannels`

I suspect that the discrepencies may come from the rounding of msats on closed channels, but I'm not sure how to confirm this, eg. what commands I can run to find the rounding errors introduced for each closed channel?

It may help just to output things like `local_balance` from `lncli openedchannels` in msats instead of rounding them.

### Your environment

* version of `lnd`: `lnd version 0.12.1-beta commit=v0.12.1-beta`
* which operating system (`uname -a` on *Nix): `Linux raspibolt 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v0.21.0`
* any other relevant environment details

### Steps to reproduce

See above

### Expected behaviour

I expected the `lncli channelbalance` command to match my manual calculations as described.

### Actual behaviour

I can't figure out where the discrepancies are coming from.

**Comment by dipunm** [comment]
I decided to sum up the routing fees for all the channels that were closed and calculated what the rounding errors might have been when they closed.

I performed the following calculations:
For each channel:
  Sum msats in and subtract msats out.
  round to the nearest 1000th
  find the difference (find the rounding errors)
  round up (ceil) to the nearest 1000th
  find the difference (find the rounding errors)
  round down (floor) to the nearest 1000th
  find the difference (find the rounding errors)

I then calculated the following sums:
sum of rounding errors: -93msats
sum of rounding errors after removing sign (ABS): 1235msats
sum of ceil errors: 1907msats
sum of floor errors: 2093msats.

Ultimately, I don't think the rounding errors from the closed channels explains the discrepancies I found above.

**Comment by Roasbeef** [comment]
The `ChannelBalance` call just sums up the same output that's returned over `ListChannels`: https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L2883 

Which field in particular are you looking at? It also includes information related to HTLCs (in the main balance) as well a pending balances (funding attempt not yet confirmed).

**Comment by dipunm** [comment]
> The ChannelBalance call just sums up the same output that's returned over ListChannels:

At least from the CLI's perspective, `listchannels` gives values rounded to the nearest `sats` and `channelbalance` gives the value in `msats`, but the sum of all the values are different by exactly `9383msats`.

> The commitment fee isn't included in this output as it's effectively already "suspended" to miners.

That's what I expected, and I am accounting for it as shown in my calculation formula below.

> Which field in particular are you looking at? 

I am looking to balance my books for reporting purposes. I assume that the msats value from `lncli channelbalance` is the most accurate. All values except the `local_balance` and `remote_balance` fields are 0 so there are no pending HTLC's AFAIK.



I am collecting all of the routing income, the payments, invoices etc. and after doing all that and accounting for the commit fees, I have a difference of `14593msats` from the `channelbalance` output (assuming that's the most accurate). I did all of my calculations in `msats` where possible so there should be no rounding errors.

My formula for manual calculations has been:
`ChannelOpenAmts - ChannelCloseSettledAmts - LocalChannelCloseFees - Payments - PaymentFees + Invoices + RoutingFees - CommitmentFees`

from the blockchain, I took:
- ChannelOpenAmounts
- ChannelCloseAmounts
- Locally opened ChannelCloseFees
I took the channel points from `listchannels` and `closedchannels` to get the open channel txs and manually combed the `closedchannels` output or close txs that were opened locally. I also included the settlements and fees from 3 timed out HTLC's, 2 of which came from locally opened channels.

Then from the cli I took:
- Payments,
- Payment fees,
- Invoices,
- Routing fees,
- Commitment fees.
And the commands I used are:
```
lncli listpayments --max_payments 10000000 | jq '.payments[].value_msat'
lncli listpayments --max_payments 10000000 | jq '.payments[].fee_msat'
lncli listinvoices --max_invoices 10000 | jq '.invoices[].amt_paid_msat'
lncli fwdinghistory --start_time -3y --max_events 900 | jq '.forwarding_events[].fee_msat'
lncli listchannels | jq '.channels[] | select(.initiator==true) | .commit_fee'
```

I started my node last November and have had less than 350 events in total including payments, invoices and routing. I just used huge numbers to be sure.

I hope this is a little better and clearer explanation.

As per my last comment, I thought the errors might have come from closed channels rounding the channel balances to commit to the blockchain, but I don't know exactly how they are rounded, so I calculated what the rounding errors would be if using nearest unit rounding (eg 0.4 = 0 and 0.5 = 1) as well as if using `ceil` and `floor` and no matter how I spin it, it doesn't account for the difference of `14593msats`. The maximum error I could force was `2093msats`.

I'd like to note that I have redone the calculations multiple times, and ensured that things like the commit fees and the channel balance were taken within seconds of each other.

**Comment by carlaKC** [comment]
> As per my last comment, I thought the errors might have come from closed channels rounding the channel balances to commit to the blockchain 

This sounds like a possible explanation for the difference. 

> I don't know exactly how they are rounded, so I calculated what the rounding errors would be if using nearest unit rounding (eg 0.4 = 0 and 0.5 = 1) as well as if using `ceil` and `floor` and no matter how I spin it, it doesn't account for the difference of `14593msats`. The maximum error I could force was `2093msats`.

As per the bolts, we always round commitment outputs [down](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#commitment-transaction-outputs).

**Comment by dipunm** [comment]
Thanks. This was interesting. I would like to understand dust limits a bit more. 

> If this amount, minus the fees for the HTLC transaction, is less than the `dust_limit_satoshis` set by the owner of the commitment transaction, the output MUST NOT be produced (thus the funds add to fees).

Does this mean that if a channel partially closes and leaves an open htlc, the second close transaction will forfeit the payout if the amount to receive is less than this configured dust limit and make an empty transaction with only a fee?

**Comment by carlaKC** [comment]
> Does this mean that if a channel partially closes and leaves an open htlc, the second close transaction will forfeit the payout if the amount to receive is less than this configured dust limit and make an empty transaction with only a fee?

Yes, in the case of a force close htlcs below the dust limit are included in miner fees, and all sub-satoshi amounts are rounded down. This is why nodes can configure the minimum htlc amount that they can route, to prevent routing dust amounts. If you want to learn the details about this, I'd encourage you to read through the spec: https://github.com/lightningnetwork/lightning-rfc.

This rounding happens for htlcs, but the LN protocol enforces a minimum reserve amount paying out to each peer that is above the dust limit, so each party will have an output in the close.

**Comment by Roasbeef** [comment]
Closing as it seems everything has been cleared up, will re-open if we find an issue that points otherwise.
