### ISSUE TITLE
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

### ISSUE THREAD

**Issue by pretyflaco** [lightningnetwork/lnd#5264]
### Background

Using BTCPay server to run lightning.

Most commands to lnd gives this error:

`bitcoin-lncli.sh getinfo`
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

Despite this, sending and receiving payments with BTCPay server works fine. 
Creating invoices with Joule, RTL all work

### Your environment

* version of `lnd`
lncli version 0.12.1-beta commit=basedon-v0.12.1-beta-15s-fresh-btcpay

* which operating system (`uname -a` on *Nix)
Linux btcpay283894 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.21.0

* any other relevant environment details

### Expected behaviour

output node information

### Actual behaviour

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by Roasbeef** [comment]
They may have changed the default RPC listening port for `lnd`. I'd check to see if that's been modified in the config and what the other tools you're using use for the port + cert.
