### ISSUE TITLE
Making sure peers can connect

### ISSUE THREAD

**Issue by emretezel** [lightningnetwork/lnd#5278]
Hi Everyone,

Just setup a full bitcoin node and lightning node on AWS, running 24/7. I can connect to my node with Zap, also managed to open a channel to ACINQ. Ports 10009 and 9735 are being forwarded.

So far no other channels have joined me inbound, I understand this doesn't happen overnight, but I just want to make sure that my node is discoverable and people can connect to it.

Below is my Conf file, does everything looks fine?

```
## LND Settings# Lets LND know to run on top of Bitcoin (as opposed to Litecoin)
bitcoin.active=true
bitcoin.mainnet=true

# Lets LND know you are running Bitcoin Core (not btcd or Neutrino)
bitcoin.node=bitcoind

## Bitcoind Settings# Tells LND what User/Pass to use to RPC to the Bitcoin node
bitcoind.rpcuser=<my username>
bitcoind.rpcpass=<my password>

# Allows LND & Bitcoin Core to communicate via ZeroMQ
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

## Zap Settings
# Tells LND to listen on all of your computer's interfaces
# This could alternatively be set to your router's subnet IP
tlsextraip=0.0.0.0
tlsextraip=18.168.149.67

# Tells LND where to listen for RPC messages
# This could also be set to your router's subnet IP
rpclisten=0.0.0.0:10009

externalip=18.168.149.67
```

**Comment by guggero** [comment]
I just checked and it looks like your P2P port is reachable. But nobody will just open channels to you without you doing something proactive.
There are community groups (for example the telegram group ["Lightning Liquidity & Pool"](https://t.me/LNBalancedChannels)) that coordinate between people to open channels to each other.
Or you could buy an inbound channel using [Lightning Pool](https://pool.lightning.engineering/).

Closing as everything looks correct.
