### ISSUE TITLE
lncli bumpfee completes but doesnt create a new transaction. Instead it waits in “pending sweeps”

### ISSUE THREAD

**Issue by 7hacker** [lightningnetwork/lnd#5282]
I had a Lightning channel open transaction pending for 24 hours due to a low fee.

So I issued a bumpfee for the output index like so (following instructions at https://lightningwiki.net/index.php/Bumping_fee_for_lightning_channel_open)

`lncli wallet bumpfee --sat_per_byte <new_fee> <txid>:<output index>
`

This completed with a return value of 0.

However a new transaction was never created.

Instead there is an output in the command:

`lncli wallet pendingsweeps
`

where I see the <new_fee> specified and the "outpoint" being the txid:output_index value

So what do I need to do to complete this CPFP operation?

**Comment by 7hacker** [comment]
Closing this since I resolved it.

My bitcoind didn't have the parent txn so the bumpfee never completed.

I restarted my bitcoind, lnd, rebroadcasted a raw txn that I got from another node's mempool and issued a bumpfee again.

A new txn was confirmed shortly after

**Comment by ktpx** [comment]
I have this same issue, could you clarify ", rebroadcasted a raw txn that I got from another node's mempool".
