### ISSUE TITLE
pending_force_closing_channels stuck for a long time now

### ISSUE THREAD

**Issue by af7567** [lightningnetwork/lnd#5283]
Hi, on `lncli pendingchannels` I have one stuck in pending_force_closing_channels for a long time now. I was using a pruned bitcoind backend so I thought maybe that was causing the problem but after reinitializing bitcoind and letting it download the whole blockchain this channel still won't close. Is it just because the amount is so small that the fee would cost too much?
I also tried height-hint-cache-query-disable=true

```
{
    "total_limbo_balance": "879",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "03fa3be3b4528c1d588e60060d7f10e37c38f5aa02f867632a5c7b816cf5afa775",
                "channel_point": "f5e918ac786cd1be22ed13b9e1484ed58faf06bfe2459b7be5c0361c02088380:0",
                "capacity": "20000",
                "local_balance": "879",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "closing_txid": "4062fb3e346ce87ccc22052c9ef41e483b8caeb61870d5e456cf9cc1c6e833a3",
            "limbo_balance": "879",
            "maturity_height": 666345,
            "blocks_til_maturity": -16309,
            "recovered_balance": "0",
            "pending_htlcs": [
            ],
            "anchor": "LIMBO"
        }
    ],
    "waiting_close_channels": [
    ]
}

````

**Comment by vegardengen** [comment]
Likely.

Currently, 4-5 sat/b is confirming, and the 879 satoshi would pretty much completely be eaten by fees.

LND will not do that. However, it will possibly sweep it if fees goes lower, or it will sweep it together with other force-closed channels, if it is economic to do so.

While I understand it can feel like it is malfunctioning, it really is not. It is just behaving rationally (if software can ever do that)

**Comment by af7567** [comment]
Thanks. I thought it probably is because of it being such a small amount, I just wanted to get a second opinion :)

**Comment by af7567** [comment]
It finally sorted itself out, so it definitely was just because of it being a very small amount. It took about 3 months but those sats are back in the wallet now.
