### ISSUE TITLE
lncli/rpc: sendcoins command ignores "min_confs" option when "sweepall" is used

### ISSUE THREAD

**Issue by cryptagoras** [lightningnetwork/lnd#5286]
### Background

`sendcoins` with `sweepall` seems to ignore the `min_confs` option.
https://github.com/lightningnetwork/lnd/blob/ea4ef204a0836724b8564ae9d74cfe8e0d7261ad/rpcserver.go#L1132-L1134

Probably either filter outputs used to respect `min_confs` or make lncli's help text clearer and print error if `lnci --sweepall --min_confs` combo is used.

### Your environment

* version of `lnd` => 0.12.1
* which operating system (`uname -a` on *Nix) => Ubuntu 16.04 LTS
* version of `btcd`, `bitcoind`, or other backend => bitcoind 0.21.1

### Steps to reproduce

`lncli sendcoins --min_confs 21 --sweepall bc1afsfqwfq...`

### Expected behaviour

Sweep all outputs that have at least 21 confirmations.

### Actual behaviour

Sweeps all outputs available, ignoring the 21 confs constraint.

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/pull/5200

**Comment by cryptagoras** [comment]
My bad, missed it.
