### ISSUE TITLE
Exception when opening channel from external wallet: error verifying PSBT: not all inputs are segwit spends 

### ISSUE THREAD

**Issue by Gridflare** [lightningnetwork/lnd#5287]
### Background

Potentially irrelevant background: I reinstalled lnd from the AUR lnd-git while trying to get the debug build working to use abandonchannel (#5265). I ended up having to hack the PKGBUILD to get it to build.
I also attempted to open a channel from a non-segwit wallet to see if it would work, that's when I saw the error for the first time.

After transferring the funds to the Electrum wallet I previously used for channel opens I still got the error. After restarting LND the error continues to persist.

### Your environment

* version of `lnd`
Updated via AUR package lnd-git on May 10, 2021
```
$ lnd --version
lnd version 0.12.99-beta commit=
```

* which operating system (`uname -a` on *Nix)
`Linux 4.19.187-1-MANJARO`
* version of `btcd`, `bitcoind`, or other backend
```
$ bitcoind --version
Bitcoin Core version v0.21.0.0-g95ea54ba089610019a74c1176a2c7c0dba144b1c
```
* any other relevant environment details
Electrum 4.1.2

### Reproduction
I'm not sure if I gave myself a weird version of LND or if the PSBT is broken. I can't go back to 12.1, and I can't open channels from LND's wallet either right now (#5265).

The base64 PSBT I created
```
cHNidP8BAH0CAAAAAQeYr3I5MHphjxj1bPQunMDzEkgelnMO5GCMmbDlxG5SAQAAAAD9////AsDGLQAAAAAAIgAg9fp4qrX9SaD2yimizd/iXaQGzn6L/Zw76gOwOptuxI5EBj0AAAAAABYAFONc59ZQL6q0zFUM0/q42rcQJfZiZmwKAAABAN4CAAAAAAEBMPm+cpKW6ErZunBiEagbxsTbqIjPk4IafKXcF22KaU8BAAAAAP3///8CzFoVAAAAAAAWABRWhifnP2EA8DBR7o/XvZ973jM/K8DPagAAAAAAFgAUkaSLivW2msAxEEs6XzgyHpWQ+rkCRzBEAiB+6VK+lMY+rlZ9QoHZRFWWFP5Pi/zMP/RparPY75mmlgIgLtLvsw/ZMaTow22vB46ERCVlk2WMIXZZQI4P5lgtENYBIQP2/DeH61A5AdKmyPH/3E4x+yAwEfe0v3TK+YTGVbpGIhRsCgAiBgImroxoUMLdqZNKgnBilRbwCjAWGhV+aPU0UHS5Xyj5AxC5tKcTAAAAgAAAAAAJAAAAAAAiAgLAoq4c393kznYb0SZHM2G0HSgOEHI8cDsLvhyRTfpKFxC5tKcTAAAAgAEAAAAIAAAAAA==
```

### Expected behaviour
The channel open proceeds to the next step

### Actual behaviour

An error is produced
```sh
$ lncli openchannel 026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2 3000000 --psbt
...
[lncli] verifying PSBT by lnd failed: rpc error: code = Unknown desc = error verifying PSBT: not all inputs are segwit spends
```

**Comment by Crypt-iQ** [comment]
This is intended because we need segwitty inputs as a precaution. See: https://github.com/lightningnetwork/lnd/pull/5165

**Comment by guggero** [comment]
@Crypt-iQ if you decode the PSBT you see that the input is SegWit. The PSBT just only sets the `non_witness_utxo` field but not the `witness_utxo`. Which I guess is technically allowed? Maybe need to add a special case for this.

**Comment by guggero** [comment]
@Gridflare did I understand you correctly that the PSBT was created in Electrum?

**Comment by Gridflare** [comment]
Yes, and I don't believe I updated Electrum recently, it worked just fine last week.
This might be the first time I've tried opening a channel with a single UTXO as input.

**Comment by Crypt-iQ** [comment]
> @Crypt-iQ if you decode the PSBT you see that the input is SegWit. The PSBT just only sets the `non_witness_utxo` field but not the `witness_utxo`. Which I guess is technically allowed? Maybe need to add a special case for this.

Maybe I read @wpaulino comment wrong, but the PSBT generated by bitcoind would always have witness_utxo set if it was a segwit input.  So this is an electrum PSBT and their formats differ slightly?

**Comment by alexbosworth** [comment]
Why not just look at the witness itself to see if it's set rather than look at the witness utxo?

**Comment by guggero** [comment]
That's the input of the previous transaction. The one being spent by the UTXO. That's just in there for completeness' sake I think.

**Comment by alexbosworth** [comment]
Crazy, ok - i'm curious how the signer even knows what sighash to make then

When I last looked at it the spec wasn't terribly prescriptive of how to put things together though

**Comment by guggero** [comment]
There's a special flag for the sighash type.

Correct, the spec is not enforcing it, this is what it mentions about `PSBT_IN_WITNESS_UTXO`:

> This should only be present for inputs which spend segwit outputs, including P2SH embedded ones. An input can have both PSBT_IN_NON_WITNESS_UTXO and PSBT_IN_WITNESS_UTXO

**Comment by Gridflare** [comment]
I'm still a bit confused about what went wrong. Is this a regression I encountered updating to the bleeding edge?
The Electrum PSBT funding flow worked for me just fine until recently.
If it is a regression, is there a known commit I can go back to? So I can open channels again. Or should I hunt for that commit myself?

**Comment by guggero** [comment]
Yes, we recently merged https://github.com/lightningnetwork/lnd/pull/5165 which added a new restriction that didn't catch all edge cases.

**Comment by alexbosworth** [comment]
I know there is a flag for the sighash signing type but I mean the sighash preimage overall is different for segwit vs legacy, so how does the signer take in that above PSBT and know that it needs to create the segwit preimage and not the legacy preimage? Is that just not encapsulated in this PSBT and it requires some external assumption or is there a specific signal that the segwit sighash preimage should be used?
