### ISSUE TITLE
Need help building walletkit for Python

### ISSUE THREAD

**Issue by Gridflare** [lightningnetwork/lnd#5289]
### Background

I'm trying to use the walletkit RPC in Python, I encountered a few issues along the way.
The first two issues are minor, and could maybe be helped with improved documentation. I am stumped by the third.

First, I made an assumption about the naming scheme and downloaded an empty file, this led to strange errors, I don't know much about curl, but maybe this can be improved.

Second when building walletkit it assumes that signer.proto is in a signrpc/ subfolder, and when importing it assumes the .py files for signer are also in the subfolder. This is fairly easy to work around and fix, but it caught me by surprise while following the tutorial. I feel that there may be a way to improve the situation.

Third, I cannot import the files generated, I get a stack trace as follows.

### Your environment
Linux, Python 3.9.4

### Steps to reproduce

Try to build walletkit following the directions at https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md

### Expected behaviour

It builds and imports without raising an exception

### Actual behaviour

Python stack trace when importing the generated module.
```Traceback (most recent call last):
  File "   /nodeinterface.py", line 18, in <module>
    import walletkit_pb2 as walletrpc, walletkit_pb2_grpc as walletkitstub
  File "   /walletkit_pb2.py", line 19, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/usr/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 965, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "walletkit.proto":
  signrpc/signer.proto: Import "signrpc/signer.proto" has not been loaded.
  walletrpc.SendOutputsRequest.outputs: "signrpc.TxOut" seems to be defined in "signer.proto", which is not imported by "walletkit.proto".  To use it here, please add the necessary import.
  walletrpc.WalletKit.DeriveNextKey: "signrpc.KeyDescriptor" seems to be defined in "signer.proto", which is not imported by "walletkit.proto".  To use it here, please add the necessary import.
  walletrpc.WalletKit.DeriveKey: "signrpc.KeyLocator" seems to be defined in "signer.proto", which is not imported by "walletkit.proto".  To use it here, please add the necessary import.
  walletrpc.WalletKit.DeriveKey: "signrpc.KeyDescriptor" seems to be defined in "signer.proto", which is not imported by "walletkit.proto".  To use it here, please add the necessary import.
```

**Comment by guggero** [comment]
This is probably because the `walletkit.proto` imports the `signrpc/signer.proto` file.
It's probably as simple as running the compilation command from the `lnrpc/` directory and using `walletrpc/walletkit.proto` as the last argument instead of just `walletkit.proto`.

The alternative (if you need to run this from within the `walletrpc/` directory) is to add the parent directory to the proto path: `--proto_path=googleapis:.:..`

**Comment by Gridflare** [comment]
That works! It was just a matter of cloning the whole lnrpc directory, and keeping the folder structure. Contrary to the tutorial's suggestion of grabbing the files individually.
