### ISSUE TITLE
One Channel From Active Peer Goes Inactive With Peer Message "Internal Error"

### ISSUE THREAD

**Issue by cryptosharks131** [lightningnetwork/lnd#5292]
### Background

I have a good peer with multiple channels open but for some reason I have one channel with that peer that has gone from active to inactive and I cannot get it back into a good state.

From reviewing the logs, it appears the peer is returning an ``internal error`` message and then my node is at that point marking the channel as inactive with the message ``internal error with error: remote error``.

Restarting the node or disconnecting and reconnecting to the peer does not seem to solve the issue.

Here are the only log messages I can see related to this error.  I have removed any identifiable information for now with ``<>``.
```
2021-05-12 15:33:30.235 [DBG] PEER: Received Error(chan_id=<>, err=internal error) from PEER@IP:PORT
2021-05-12 15:33:30.235 [ERR] HSWC: ChannelLink(<>): failing link: ChannelPoint(<>): received error from peer: chan_id=<>, err=internal error with error: remote error
2021-05-12 15:33:30.236 [ERR] HSWC: ChannelLink(<>): link failed, exiting htlcManager
2021-05-12 15:33:30.236 [INF] HSWC: ChannelLink(<>): exited
```

### Your environment

* version: ``lnd version 0.12.1-beta commit=v0.12.1-beta``
* which operating system: ``Ubuntu``
* version of backend: ``Bitcoin Core version v0.21.1``
* any other relevant environment details: ``N/A``

### Steps to reproduce

I am not sure how to reproduce this specific issue as it is the first occurrence I have seen.

In the past I have seen something very similar but I got an ``invalid_sig_commitment`` in that case and a force closure from my node following it.  The odd thing being that this other occurrence was also with this same peer but I wrote this off as a one time or rare occurrence where something may have got messed up in the htlc.

### Expected behaviour

It is not expected to have one channel inactive from a peer who has other channels that are active and routing with your node.

### Actual behaviour

Channel goes to inactive state due to unknown ``internal error``.

**Comment by wpaulino** [comment]
There's not much we can do with `internal error` without knowing what happened on the remote peer's side. Maybe you're able to get in contact with them?

**Comment by cryptosharks131** [comment]
After notifying the operator, the issue was resolved from their side.  However, they did not provide detail as to the root cause.

Closing this issue as it is no longer occurring and details of the peer's error are not available.
