### ISSUE TITLE
2month+ tx channel open => unable to parse message of unknown type: <unknown>

### ISSUE THREAD

**Issue by itmanagerro** [lightningnetwork/lnd#5294]
### Background

I've opened the channel before the mempool bump (1 month+) and now it confirmed, but the peer sync is getting error:

`[INF] PEER: unable to read message from [key]@[ipv4]:9735: unable to parse message of unknown type: <unknown>`

This is when the transaction confirmed:
```
[INF] LNWL: Marking unconfirmed transaction xxxxxxxxx mined in block 68xxxx
[DBG] LNWL: Marked address bc1xxxx used
[DBG] LNWL: Marked address bc1xxxx used
```

and no communication after wards until manually connected to peer,  which got to <unknown> error above

### Your environment

* 0.12.1-beta
* FreeBSD 12
* bitcoind
* ipv4+tor
* peer version c-lightning 0.10.0

### Steps to reproduce

Channel is inactie

### Expected behaviour

Channel should be active

### Actual behaviour

^^ description

**Comment by Roasbeef** [comment]
The remote peer is sending you a message that we don't understand. Not much we can do here, but sounds like a bug related to them sending you messages that we don't advertise the feature bits to?

**Comment by itmanagerro** [comment]
I've traced it to mesage.go of lnwire, so I understand that peer is sending some unknown code

can the long period of opening a channel due to low fee and mempool congestion affect the opening somehow?

**Comment by itmanagerro** [comment]
@Roasbeef thank you for the support, reddit helped me figure out that only forceclose can help in such situation as it passed more than 2 weeks for the channel to open, the peer is now aware of the

**Comment by Crypt-iQ** [comment]
@itmanagerro Would you mind sharing the peer you had the channel with? I think it would be beneficial to chase down *why* a peer is sending invalid messages.

**Comment by Crypt-iQ** [comment]
Not sure why the channel would be inactive, but the peer is allowed to send messages we don't understand and we'll ignore them.
