### ISSUE TITLE
What are "commit_weight" and "fee_per_kw"

### ISSUE THREAD

**Issue by emretezel** [lightningnetwork/lnd#5300]
Hi Everyone,

A newbie question, in layman terms what are "commit_weight" and "fee_per_kw" for? 

Best,

**Comment by guggero** [comment]
Commit weight is how large the commitment transaction is in weight units. And the fee that was chosen when crafting the commitment transaction is expressed in `per_kw = sats/kWU = sats/1000 weight units`.
