### ISSUE TITLE
Not Binding to Correct P2P Port

### ISSUE THREAD

**Issue by t-kiziah** [lightningnetwork/lnd#5302]
### Background

lnd does not properly bind to and advertise ipv4 interfaces

### Your environment

* 0.12.1-beta
* Linux
* bitcoind

### Steps to reproduce

Set listen and externalip options in configuration file

[Application Options]
listen=0.0.0.0:19735
externalip=X.X.X.X

### Expected behaviour

lnd should bind, listen, and advertise p2p connections on specified ipv4 interface and port

### Actual behaviour

lnd does not bind to ipv4 interface and advertises default port instead of the one specified to the network

netstat -punta | grep 19735
tcp6       0      0 :::19735                :::*                    LISTEN      549/lnd

lncli getinfo

"uris": [
        "03a9995d25d0767ef38ce2eff01ee574e41360c16b7bdf16a8edd87d82d06163c7@X.X.X.X:9735"
    ],

**Comment by githorray** [comment]
Try setting a port number on your external ip setting, if you don't it probably sets it to the default. It isn't automatically configured.

**Comment by t-kiziah** [comment]
Adding the port to the external ip setting seems to have fixed the p2p advertisement

"uris": [
        "03a9995d25d0767ef38ce2eff01ee574e41360c16b7bdf16a8edd87d82d06163c7@174.80.197.141:19735"
    ],

With that said, lnd seems to only be binding to ipv6 according to netstat:

netstat -punta | grep 9735
tcp6       0      0 :::9735                 :::*                    LISTEN      1184/lnd
