### ISSUE TITLE
REST API /v1/switch returns 100 earliest forwarding events instead of the past 24 hours as per documentation

### ISSUE THREAD

**Issue by hazrulnizam** [lightningnetwork/lnd#5306]
### Background

As per the the [documentation](https://api.lightning.community/#v1-switch), the `/v1/switch` API call should mimic the output of `lncli fwdinghistory` when called with no arguments, which is to return the 'first chunk' of forwarding events since 24 hours ago. Instead, the API call returns the first 100 forwarding events ever recorded by the node.

### Your environment

* `lnd` version `0.12.1-beta commit=v0.12.1-beta`
* `Linux 4.18.0-240.22.1.el8_3.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux`
* `bitcoind` version `0.21.0`
* `bitcoind` and `lnd` run in different servers

### Steps to reproduce

Call the `/v1/switch` API with no body, and compare the output with output from `lncli fwdinghistory` on the command line.

### Expected behaviour

Should return the 'first chunk' of forwarding events with the earliest timestamp of 24 hours ago, as per the output of `lncli fwdinghistory`:
```
{
    "forwarding_events": [
        {
            "timestamp": "<timestamp less than 24 hours ago>",
            "chan_id_in": "<channel id 1>",
            "chan_id_out": "<channel id 2>",
            "amt_in": "<amount>",
            "amt_out": "<amount>",
            "fee": "<fee>",
            "fee_msat": "<fee x 1000>",
            "amt_in_msat": "<amount>",
            "amt_out_msat": "<amount>"
        },
	{
	    other transactions.....
	},
        {
            "timestamp": "<timestamp less than 24 hours ago>",
            "chan_id_in": "<channel id 1>",
            "chan_id_out": "<channel id 2>",
            "amt_in": "<amount>",
            "amt_out": "<amount>",
            "fee": "<fee>",
            "fee_msat": "<fee x 1000>",
            "amt_in_msat": "<amount>",
            "amt_out_msat": "<amount>"
        }
    ],
    "last_offset_index": <n>
}
```

### Actual behaviour

API call returns the first 100 transactions ever recorded by the node:
```
POST /v1/switch
{
    "forwarding_events": [
        {
            "timestamp": "<timestamp of 1st ever transaction>",
            "chan_id_in": "<channel id 1>",
            "chan_id_out": "<channel id 2>",
            "amt_in": "<amount>",
            "amt_out": "<amount>",
            "fee": "<fee>",
            "fee_msat": "<fee x 1000>",
            "amt_in_msat": "<amount>",
            "amt_out_msat": "<amount>"
        },
	{
	    other 98 transactions.....
	},
        {
            "timestamp": "<timestamp of 100th ever transaction>",
            "chan_id_in": "<channel id 1>",
            "chan_id_out": "<channel id 2>",
            "amt_in": "<amount>",
            "amt_out": "<amount>",
            "fee": "<fee>",
            "fee_msat": "<fee x 1000>",
            "amt_in_msat": "<amount>",
            "amt_out_msat": "<amount>"
        }
    ],
    "last_offset_index": 100
}
```

**Comment by guggero** [comment]
I can confirm that the default value of 24 hours is only set when using the CLI. I assume the comment from which the API documentation is generated was initially targeted towards users of the CLI and is therefore not accurate for API users.

**Comment by RandallWert** [comment]
Having established that the behavior does not match the documentation, is the goal here to correct the documentation or to obtain the desired behavior in spite of this discrepancy? If the latter, then could a simple workaround consist of providing the start_time and end_time fields to capture the previous 24 hours (even though the documentation says this shouldn't be necessary)?

If that works, then hopefully the documentation can be changed accordingly.

(First-time contributor to GItHub here, hopefully not making a total fool of myself.)

**Comment by guggero** [comment]
Changing the default behavior of an API is a tricky thing to not mess up other user's code/logic. Therefore I suggest to fix this in the documentation to mention the actual behavior of the API.

**Comment by de6df1re** [comment]
I am new here, but would be glad to fork the repo and make the documentation updates and create a pull request.  Analysis below:

I have verified this behavior (0.12.1-beta commit=v0.12.1-beta), and note the following code: 

lnd/rpcserver.go ForwardingHistory is coded as follows:

```
        // startTime defaults to the Unix epoch (0 unixtime, or midnight 01-01-1970).
        startTime = time.Unix(int64(req.StartTime), 0)

        // If the end time wasn't specified, assume a default end time of now.
        if req.EndTime == 0 {
                now := time.Now()
                endTime = now
        } else {
                endTime = time.Unix(int64(req.EndTime), 0)
        }

        // If the number of events wasn't specified, then we'll default to
        // returning the last 100 events.
        numEvents = req.NumMaxEvents
        if numEvents == 0 {
                numEvents = 100
        }
```
lncli: fwdinghistory (lnd/cmd/lncli/commands.go forwardingHistory) is coded as follows:
 
```
        default:
                now := time.Now()
                startTime = uint64(now.Add(-time.Hour * 24).Unix())
        default:
                endTime = uint64(now.Unix())

```
I believe the documentation for the REST API needs to be updated in lnd\lnrpc\rpc.swagger here: 
```

    "/v1/switch": {    
      "post": {
        "summary": "lncli: `fwdinghistory`\nForwardingHistory allows the caller to query the htlcswitch for a record of\nall HTLCs forwarded within the target time range, and integer offset\nwithin that time range. If no time-range is specified, then the first chunk\nof the past 24 hrs of forwarding history are returned.",

```
I suggest the text be changed from (existing text): 

> ForwardingHistory allows the caller to query the htlcswitch for a record of all HTLCs forwarded within the target time range, and integer offset within that time range. **If no time-range is specified, then the first chunk of the past 24 hrs of forwarding history are returned.**

To (suggested text): 
> ForwardingHistory allows the caller to query the htlcswitch for a record of all HTLCs forwarded within the target time range, and integer offset within that time range, **for a maximum number of events. If no maximum number of events is specified, a maximum of 100 events will be returned. If no time-range is specified, then the earliest forwarding history events are returned.**

I'm new here but would be glad to fork the repo and make this update and pull request.

**Comment by de6df1re** [comment]
In progress, documentation PR to be submitted shortly.

**Comment by Roasbeef** [comment]
Was resolved by https://github.com/lightningnetwork/lnd/pull/5376
