### ISSUE TITLE
rest-annotations.yaml has incorrect routerrpc selectors

### ISSUE THREAD

**Issue by SamCymbaluk** [lightningnetwork/lnd#5307]
### Background

The rest-annotations.yaml file has incorrect selectors for certain routerrpc endpoints. This prevents gRPC gateway from generating files correctly.

### Your environment

* version of `lnd`: lnd v0.12.1-beta

### Steps to reproduce

Run `gen_protos.sh`

### Expected behaviour

The generated files include all intended endpoints.

### Actual behaviour

Some endpoints are silently missing. On new versions of gRPC gateway, the generation fails entirely with error:
```
HTTP rules without a matching selector: .routerroc.Router.SetMissionControlConfig .routerrpc.HtlcInterceptor, .routerrpc.UpdateChanStatus
```

**Comment by guggero** [comment]
You have the wrong version of `grpc-gateway` installed. Please use `make rpc` that uses the dockerized build process with the correct versions of all involved libraries.

**Comment by SamCymbaluk** [comment]
I understand that, but are the above not typos? Shouldn't `.routerroc.Router.SetMissionControlConfig` be `.routerrpc.Router.SetMissionControlConfig`, `.routerrpc.HtlcInterceptor` be `.routerrpc.Router.HtlcInterceptor`, and `.routerrpc.UpdateChanStatus` be `.routerrpc.Router.UpdateChanStatus`? 

If so, I'm happy to create the PR to fix them.

**Comment by guggero** [comment]
Ah, you're right... sorry this looks very much like the error you get if you use the wrong grpc-gateway version.

**Comment by guggero** [comment]
Thanks for reporting this @SamCymbaluk! I went ahead and created a fix for it.
We'll try to update to v2 of the `grpc-gateway` library soon that will catch these kinds of mistakes.
