### ISSUE TITLE
unable to read channel… invalid magic in compressed pubkey string

### ISSUE THREAD

**Issue by wereHamster** [lightningnetwork/lnd#531]
> unable to read channel for chain_hash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000, node_key=02a35187c5a71676da4930d93faaf30f6d5e19e3bbe8f3ead400b898967e1dc475: unable to read channel data for chan_point=b215b9a0c2a8fbb7c3ace8ea3fc874776b55e8dc05d02388790bfef4a0d04514:0: unable to fetch chan info: invalid magic in compressed pubkey string: 163

I tried to bisect this but was unable because some commits don't compile. The best I could find out is the good one is dab7f31e44390c6d92f19916946bc34d56738d55 and bad one is 9af7cc9b995e338fc043cd1ec5093a73b84b94fe. Somewhere in between the bug is introduced.

**Comment by Roasbeef** [comment]
A bug wasn't introduced. A breaking database change happened.

**Comment by wereHamster** [comment]
Ok. So how do I upgrade the database? Or do I have to wipe it and start fresh? Can I retain my wallet and channels or do I lose that during the upgrade?

**Comment by Roasbeef** [comment]
> So how do I upgrade the database? Or

As we haven't released a stable version yet, we didn't add any database migrations/updates to the commit. However, the infrastructure necessary to do so is already in place. 

To upgrade, you can close out all your old channels, then send any funds to a faucet, or another wallet you have. Once you've done this, you can then wipe your old state, and upgrade.
