### ISSUE TITLE
New channel is disabled 21 minutes after having enough confirmations

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5313]
### Background

I opened a channel which, after a while, had 6 confirmations. About 21 minutes later lnd disabled it. This is the second channel to that peer. More background in #5312.

See logs below.

### Your environment

* lnd version 0.12.1-beta commit=v0.12.1-beta-dirty
* Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
* Bitcoin Core (bitcoind) 0.12.0

### Steps to reproduce

Create a new channel.

### Expected behaviour

Channel is enabled and stays enabled.

### Actual behaviour

Channel is disabled after a few minutes, and is not enabled again. This didn't change for more than 2 days. I think I was able to enable the channel only by reconnecting to the peer or updating the channel policy manually.

```
2021-05-16 01:03:26.464 [INF] NTFN: New confirmation subscription: conf_id=63, txid=__FUNDING_TX__, num_confs=6 height_hint=683775
2021-05-16 01:03:26.465 [ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: rpc error: code = Unavailable desc = transport is closing
2021-05-16 01:04:01.853 [INF] CRTR: Processed channels=4 updates=38 nodes=4 in last 59.982753114s
2021-05-16 01:04:08.008 [INF] PEER: New channel active ChannelPoint(__FUNDING_TX__:0) with NodeKey(__PEER_PUBKEY__)
2021-05-16 01:04:08.009 [INF] HSWC: Removing channel link with ChannelID(__CHAN_ID__)
2021-05-16 01:04:08.009 [INF] HSWC: ChannelLink(__SHORT_CHAN_ID__): starting
2021-05-16 01:04:08.009 [INF] HSWC: Trimming open circuits for chan_id=__SHORT_CHAN_ID__, start_htlc_id=0
2021-05-16 01:04:08.009 [INF] HSWC: Adding live link chan_id=__CHAN_ID__, short_chan_id=__SHORT_CHAN_ID__
2021-05-16 01:04:08.009 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(__FUNDING_TX__:0)
2021-05-16 01:04:08.009 [INF] HSWC: ChannelLink(__SHORT_CHAN_ID__): HTLC manager started, bandwidth=__BANDWIDTH__ mSAT
2021-05-16 01:04:08.009 [INF] HSWC: ChannelLink(__SHORT_CHAN_ID__): attempting to re-resynchronize
2021-05-16 01:04:08.049 [INF] HSWC: ChannelLink(__SHORT_CHAN_ID__): resending FundingLocked message to peer
2021-05-16 01:04:08.049 [INF] HSWC: ChannelLink(__SHORT_CHAN_ID__): received re-establishment message from remote side
2021-05-16 01:04:08.072 [DBG] HSWC: ChannelLink(__SHORT_CHAN_ID__): loaded 0 fwd pks
2021-05-16 01:04:08.232 [INF] FNDG: Received duplicate fundingLocked for ChannelID(__CHAN_ID__), ignoring.
--
2021-05-16 01:24:48.637 [INF] NANN: Announcing channel(__FUNDING_TX__:0) disabled [detected]
```

**Comment by Roasbeef** [comment]
`lnd` will only automatically disable a channel if the other peer is offline, did you maintain connectivity this entire time?

**Comment by C-Otto** [comment]
I am sure that we were connected in the time frame shown in the logs, though.

**Comment by Roasbeef** [comment]
Do you know what _implementation_ the other node was?

**Comment by wpaulino** [comment]
@alexbosworth mentioned on Slack that he commonly sees newly opened channels being disabled, but they'll flip back to enabled shortly after, so it seems like an issue with our auto disable logic.

**Comment by alexbosworth** [comment]
I don't see it so often that I couldn't be sure it's just something correlated to channel opening, like maybe a channel open might confirm at a different time than when you are online so it gets disabled

**Comment by Roasbeef** [comment]
> No, it's a TOR only node and I can't find any public information. Is there a technical way to figure this out?

It may be a possible connectivity issue with the node, at times we notice that Tor-only nodes end up dropping connections of having them be idle after a certain amount of time, possibly related to some issue re circuit staleness.

**Comment by Roasbeef** [comment]
Given that the channel was disabled, and then never enabled again, the node was never able to maintain a stable connection.

**Comment by C-Otto** [comment]
Indeed, the other channel to that peer was disabled, too. It's weird that our nodes were connected, though (we exchanged gossip messages). Maybe lnd should make use of this connection to re-enable the channels?

**Comment by C-Otto** [comment]
I just had the same error, with a different peer. This time lnbig lnd-31, clearnet. I already had two channels with that peer, and the issue appeared with the third. Again, 21 minutes after the channel reached the confirmation target, it was disabled. Our peers are online and connected.

**Comment by C-Otto** [comment]
I just disconnected and got this:
`21:13:16.388 [INF] FNDG: Received duplicate fundingLocked for ChannelID(eaafba1a6007703b8c09e303ec7093e92c39985401bd170145df6443323f5443), ignoring.`

**Comment by Crypt-iQ** [comment]
> I just disconnected and got this:
> `21:13:16.388 [INF] FNDG: Received duplicate fundingLocked for ChannelID(eaafba1a6007703b8c09e303ec7093e92c39985401bd170145df6443323f5443), ignoring.`

Normal to receive this message, though we do plan to fix some things regarding funding locked so we align with the spec

**Comment by C-Otto** [comment]
Happened again with 0.13.0-beta-rc5. Peer is tor-only, channel is listed as active, I don't see any disconnection in the logs.

**Comment by Crypt-iQ** [comment]
Do you know what the peer is running? Logs may help

**Comment by C-Otto** [comment]
I don't know the other node's implementation. I do provided logs above. Is there anything specific you're looking for?

**Comment by Crypt-iQ** [comment]
If the counter-party force closed, there's really not anything we can do here without their logs

**Comment by C-Otto** [comment]
I just realized the issue title mentioned "closed", but in reality it's just a disabled channel. Sorry for the confusion!

So, with that in mind, I hope my own node's logs suffice?

**Comment by wpaulino** [comment]
@C-Otto could you start running with `debuglevel=NANN=debug`? This will give us more insight as to when it's getting disabled.

**Comment by C-Otto** [comment]
Done. Please open a channel to my node and I'll dell you what's going on (2M sat minimum) :)

**Comment by C-Otto** [comment]
```
13:16:14.693 [INF] NTFN: Dispatching 3 confirmation notification for txid=ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec
13:16:14.694 [INF] FNDG: ChannelPoint(ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec:1) is now active: ChannelID(ec9b3a04f67fa422a827b41f6f1b94466991d1adda32d1e9a3d3c06e98dd
13:16:14.854 [ERR] FNDG: unable to report short chan id: link ec9b3a04f67fa422a827b41f6f1b94466991d1adda32d1e9a3d3c06e98dd2bed not found
13:16:14.858 [INF] FNDG: Peer(02e1f391c9f3420fcaf65d45b615ab53034bd4a090036ddfb5703f6825b3b2bb4c) is online, sending FundingLocked for ChannelID(ec9b3a04f67fa422a827b41f6f1b94466991d1adda32d1
13:16:14.863 [INF] RPCS: channel: ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec:1 not found by channel event store
13:16:15.714 [INF] NTFN: New confirmation subscription: conf_id=78, txid=ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec, num_confs=6 height_hint=688890
13:16:16.964 [INF] PEER: New channel active ChannelPoint(ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec:1) with NodeKey(02e1f391c9f3420fcaf65d45b615ab53034bd4a090036ddfb5703
13:16:17.901 [INF] HSWC: ChannelLink(688890:1197:1): resending FundingLocked message to peer
13:16:18.251 [INF] FNDG: Received duplicate fundingLocked for ChannelID(ec9b3a04f67fa422a827b41f6f1b94466991d1adda32d1e9a3d3c06e98dd2bed), ignoring.
---
13:22:06.934 [INF] NANN: Announcing channel(ec2bdd986ec0d3a3e9d132daadd1916946941b6f1fb427a822a47ff6043a9bec:1) disabled [requested]
```

That's just 6 minutes after the channel has been confirmed. The NANN logs don't show anything more than that, even with debug logging.

**Comment by C-Otto** [comment]
Haven't seen this for a while (lots of new channels, though).
