### ISSUE TITLE
Unable to change channel  routing fees

### ISSUE THREAD

**Issue by CoderBoogs** [lightningnetwork/lnd#5320]
Background

I ran a casa node #1 with LND. Due to power failures the node corrupted. I was not able to back up my channels. But I had my seed. I transferred that node to an Umbrel and noticed the wallet had a balance. Shortly after opening up new channels I noticed my node had old channels that are open on 1ml.com but not visible on thunderhub. I proceeded to open channels with the goal of becoming a routing node and noticed I am unable to change my fees. thunder hub and RTL give me an error. On RTL thee error code is 500 and the error message is channel from self node has no policy  and then an API URL 

Your environment

raspberry pi 4
umbrel  (latest version)
LND 0.12.1
Bitcoind 0.21.1

Relevant configuration:

tor.active=true

Steps to reproduce:

Click on thunderhub channels. click on update fee. change the fee from 1 sat to 2 stats and the unexpected error pops up. 

Expected behavior:
Changing of the fees on my channels 

Several options:

I saw a fix to this potential issue 

https://github.com/lightningnetwork/lnd/issues/2911#issuecomment-490754329

but when I reached out to the Umbrel team they suggested:

You would have to fork our LND container with that patch applied and then modify a configuration file to point to your container. It will get removed after each Umbrel update so you'd have to re-apply the change and they recommended setting up a node and recovering my funds there. 

But I have opened many channels already and this will be too expensive to start over with a fresh node.

**Comment by Roasbeef** [comment]
0.13.0 lets you call abandon channel to remove the channels that may have closed w/o your node knowing. At this point, since your node had a power failure leading to corrupted state, manual intervention is required.

**Comment by CoderBoogs** [comment]
Thanks for looking into this and following up. I will just keep this node static. I put too much time and sats to manually start over. With default fees very low this node can still function as a routing node.
