### ISSUE TITLE
Documentation: Prometheus flags aren't documented in sample-lnd.conf

### ISSUE THREAD

**Issue by krtk6160** [lightningnetwork/lnd#5323]
### Background

Two prometheus flags for lnd are specified in the lndmon install [instructions](https://github.com/lightninglabs/lndmon/blob/master/INSTALL.md#lnd): `--prometheus.enable` and `--prometheus.listen`.
 They are not documented in the `sample-lnd.conf` file.

**Comment by Roasbeef** [comment]
Was fixed by https://github.com/lightningnetwork/lnd/pull/5331
