### ISSUE TITLE
"synced_to_chain": false , but at the same time the node is synchronized. 

### ISSUE THREAD

**Issue by peername** [lightningnetwork/lnd#5325]
### Background

My LND node says "synced_to_chain": false a few minutes after it is started. But the node is actually synchronized. The block height equals the current state of the Bitcoin blockchain.

### Your environment

* version of `lnd` : 0.13.0-beta.rc3 commit=v0.13.0-beta.rc3
* which operating system (`uname -a` on *Nix): Ubuntu Server 20.04
* version of `btcd`, `bitcoind`, or other backend: Neutrino Backend (Bitcoin Core 0.21.1 + NODE_COMPACT_FILTERS)

### Steps to reproduce

Run the latest RC version of LND and initialize it. After a few minutes it gets synched. After few more minutes it says  "synced_to_chain": false but it is actually synched. New blocks are added. Graph sync is working. Everything is OK.

### Expected behaviour

The node should report "synced_to_chain": true when "block_height" equals the total numbers of Bitcoin blocks.

### Actual behaviour

The node always reports "synced_to_chain": false

**Comment by joostjager** [comment]
Possible duplicated/related: https://github.com/lightningnetwork/lnd/issues/5132

**Comment by peername** [comment]
I switched back to LND 0.12.1-beta and the problem disappeared. It seems that the problem comes from the new version 0.13.0.

I am using Bitcoin Core 0.21.1 backend with compact filters enabled (BIP 157 and BIP 158).

**Comment by Roasbeef** [comment]
How were you able to go backwards given a DB migration is in place between those two versions? Do you mean you instead started a new node? Also how reproducible is this? May it have been the case that there's actually no difference in this context between those two versions and the restart is simply what resolved things for you?

**Comment by Roasbeef** [comment]
Is your node _only_ connected to that one bitcoind node?

**Comment by peername** [comment]
I tried with a fresh LND installation. Same problem.

I have 3 Bitcoin Core full nodes. I tried to connect to every one of them, even to the three nodes at a same time. Version _0.12.1-beta_ is working. Version _0.13.0-beta.rc3_ is not working.

Tired on different machine and environments - same problem. My Bitcoin Core 0.21.1 config:

_txindex=1
blockfilterindex=1
peerblockfilters=1_

You can try it yourself. The new version of LND is not working with Bitcoin Core backend in Neutrino mode. The old version is working.

My LND config:

_./lnd --bitcoin.active --bitcoin.mainnet --bitcoin.node=neutrino --neutrino.connect=87.121.37.156 --routing.assumechanvalid --feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json_

Now I am testing with BTCD as Neutrino backend - same problem. It shows /"synced_to_chain": false / when a new block arrives.

**Comment by wpaulino** [comment]
Thanks for the report @peername. This seems to be a side-effect of https://github.com/lightningnetwork/lnd/pull/5281.

@guggero since neutrino runs with the assume channel valid logic, the block subscription does not happen and the router height is never updated.

**Comment by guggero** [comment]
Oh, I see. Going to create a fix asap. I wonder why our neutrino itests didn't discover this?

**Comment by wpaulino** [comment]
> I wonder why our neutrino itests didn't discover this?

@guggero we run the itests with `validatechannels` for some testing assumptions.

**Comment by guggero** [comment]
Ah right, I forgot (again) that we don't do that (yet) :joy:
