### ISSUE TITLE
Hitting open file limit once at startup hangs lnd

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#5330]
### Background

If I start lnd, enter password, sometimes it hangs. My logs then look like:

![image](https://user-images.githubusercontent.com/47113175/119509878-8d4bd780-bd60-11eb-9ed1-e7f6a0f7e22c.png)

While looking at `watch "ls /proc/$( pgrep lnd )/fd | wc -l"` at startup, it seems it hangs IF it hits 1024 open files (the default for systemd services). 

### Your environment

* version of `lnd` commit=v0.12.1-beta
* which operating system: 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.21.1
* any other relevant environment details: many channels

### Steps to reproduce

1) Start LND, unlock
2) Wait for the 500+ channels to reopen
3) **POSSIBLY** my cronjob manually reconnecting fired!! Seems if you try to connect too many nodes, during startup, lnd crashes (blocking logwrite call I think)

### Expected behaviour
1) Start LND, unlock
2) Manual reconnects should fail until node is all good / tried to reconnect itself

### Actual behaviour
1) LND starts
2) Crashes

**Comment by Roasbeef** [comment]
You system doesn't have enough available file descriptors, you should look into increasing these values with the `ulimit` command (or the like).

**Comment by AbelLykens** [comment]
Yes I did that:
1) Increased `/etc/security/limits*` to `999999`
2) Increased `fs.file-max=999999`
3) Enabled `session required pam_limits.so` in PAM
That all did not work, until I added `LimitNOFILE=10000` under the `[Service]` stanza in the systemd startup file.

Now it sometimes slightly goes over 1024.

Main point is that lnd crashed when it hit the limit. Detecting the limits could help, or not accepting `connect` commands during startup.

I am fairly sure if my bot does the reconnects at startup again, lnd will crash (possibly because of the log action not being available / blocking).

Bit hard to reproduce exactly, because I don't want to risk my lnd funds (prod).

**Comment by SeverinAlexB** [comment]
Thanks for prioritizing

**Comment by Roasbeef** [comment]
Note that this is likely best implemented as a new `healthcheck`: https://github.com/lightningnetwork/lnd/tree/master/healthcheck

**Comment by rbndg** [comment]
Is this going to get fixed? 
I've been getting it quite often recently

**Comment by AbelLykens** [comment]
Well the fix is to increase limits. Only thing LND will help with is alert people if their limits are too low. That has not been implemented yet.

If I am correct :D

**Comment by rbndg** [comment]
Yeah, I did that.
The alert would be good feature to have

**Comment by Roasbeef** [comment]
FWIW, this is now essentially fixed with [Go 1.19](https://tip.golang.org/doc/go1.19): 
> On Unix operating systems, Go programs that import package [os](https://tip.golang.org/pkg/os/) now automatically increase the open file limit (RLIMIT_NOFILE) to the maximum allowed value; that is, they change the soft limit to match the hard limit. This corrects artificially low limits set on some systems for compatibility with very old C programs using the [select](https://en.wikipedia.org/wiki/Select_(Unix)) system call. Go programs are not helped by that limit, and instead even simple programs like gofmt often ran out of file descriptors on such systems when processing many files in parallel. One impact of this change is that Go programs that in turn execute very old C programs in child processes may run those programs with too high a limit. This can be corrected by setting the hard limit before invoking the Go program.
