### ISSUE TITLE
SendPayments fails with FinalIncorrectCltvExpiry

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#535]
Steps to reproduce:

`lncli addinvoice 5000`
`lncli decodepayreq pay_req`
`lncli sendpayment destination amount payment_request_hash`

Results:
```
{
        "payment_error": "FinalIncorrectCltvExpiry(expiry=1256748)",
        "payment_preimage": "",
        "payment_route": null
}
```

But if we just send `lncli sendpayment --pay_req=lntb50u1pdydw5gppxxx...`  it works nicely:
```
{
        "payment_error": "",
        "payment_preimage": "958c6375cb4c8f6617425345a39c847ad65062392634896862acb652bd548e23",
        "payment_route": {
                "total_time_lock": 1256883,
                "total_amt": 5000,
                "hops": [
                        {
                                "chan_id": 1381771655794065408,
                                "chan_capacity": 200000,
                                "amt_to_forward": 5000,
                                "expiry": 1256883
                        }
                ]
        }
}
```

Version:
```
~/Projects/pos on  master ➜ docker-compose exec lnd lnd --version
lnd version 0.3.0-alpha

~/Projects/pos on  master ➜ docker-compose exec lnd lncli -v     
lncli version 0.3
```

**Comment by Roasbeef** [comment]
This is more or less due to a block-based race condition. We're sending a payment, and a block is mined mid-flight. As we don't use any sort of "shadow" routes, our timeouts are very tight, and this unexpected block will result in an error.

**Comment by Richard87** [comment]
I'm not sure if I follow, are you saaying that it happens only if a block is mined at the exact time we try to pay a invoice?

Is there anything I can do, like increasing the timeout?

**Comment by Roasbeef** [comment]
On your end, just try again until we implement more slack on our timeouts.

**Comment by Richard87** [comment]
Hi,

I just put it in a loop to run every 10sec for 30minutes, but it have not gone through?

```
while true; do lncli sendpayment 02c1c089874c994d2ae99bd0520ba70a154ce0aa80dfe7a857eaf9ca6251a971c4 5000 72ba3fd6cd19f53f0c50f447b92128a3192083a3041435cd201b3244ec0c00d8; sleep 10; done
```

**Comment by Roasbeef** [comment]
You're calling `sendpayment` incorrectly. You need to be using a payment request, as it partially specifies what the final CLTV value should be.

**Comment by halseth** [comment]
@Roasbeef Does this mean that `lncli sendpayment` does not currently work without the `--pay_req` flag? In that case we should probably either remove it, or add the necessary `cltv` parameter.
