### ISSUE TITLE
Watchtower does not connect: chacha20poly1305: message authentication failed

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5360]
### Background

I use SSH port forwarding to connect to a remote lnd instance that should serve as a watchtower server. After adding the watchtower in the client, I get:

Server: `2021-06-05 20:02:24.258 [ERR] BTCN: Can't accept connection: unable to accept connection from 127.0.0.1:49876: chacha20poly1305: message authentication failed`
Client: `2021-06-05 19:02:24.317 [DBG] WTCL: (legacy) Session negotiation with tower=XXX failed, trying again -- reason: session negotiation unsuccessful`

This message is repeated everytime the client tries to connect.

The watchtower server is running on a fresh lnd installation with a fresh wallet and a pubkey I haven't seen before.

### Your environment

lnd 0.13.0-rc5
Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
bitcoind 0.21.0 (bitcoin core)

**Comment by guggero** [comment]
Could you post the watchtower server's and the client's configuration please? It sounds like you're possibly connecting to the wrong port? The watchtower server spins up a new listener on a new port.

**Comment by C-Otto** [comment]
Server:
```
[Application Options]
maxpendingchannels=10
listen=127.0.0.1
alias=ftp.halifax.rwth-aachen.de
accept-keysend=0
accept-amp=0
db.bolt.auto-compact=true
maxlogfiles=365
maxlogfilesize=1
protocol.wumbo-channels=0
debuglevel=info,WTWR=debug
maxpendingchannels=0
restlisten=127.0.0.1:8081
ignore-historical-gossip-filters=true
nolisten=true
norest=true
nobootstrap=true
rejecthtlc=true
numgraphsyncpeers=1
wallet-unlock-password-file=/home/bitcoin/.lnd/wallet.password

[watchtower]
watchtower.active=true
watchtower.listen=127.0.0.1:9911

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=bitcoin
bitcoind.rpcpass=xxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
bitcoind.estimatemode=ECONOMICAL

[autopilot]
autopilot.active=0
```

**Comment by C-Otto** [comment]
Client:
```
[Application Options]
maxpendingchannels=10
externalip=157.90.112.145
externalip=2a01:4f8:c2c:e8a0::1
listen=157.90.112.145
listen=2a01:4f8:c2c:e8a0::1
alias=c-otto.de
accept-keysend=1
accept-amp=1
minchansize=2000000
db.bolt.auto-compact=true
maxlogfiles=365
maxlogfilesize=1
protocol.wumbo-channels=1
debuglevel=info,DISC=warn,HSWC=debug

[wtclient]
wtclient.active=true
wtclient.sweep-fee-rate=50

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.basefee=100
bitcoin.node=bitcoind
bitcoin.timelockdelta=40
bitcoin.feerate=2500

[Bitcoind]
bitcoind.rpcuser=bitcoin
bitcoind.rpcpass=xxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
bitcoind.estimatemode=ECONOMICAL
```

**Comment by C-Otto** [comment]
I use `autossh` to forward port 9911 of the host listed as "server" above: `-L 9911:127.0.0.1:9911`

**Comment by guggero** [comment]
Thanks, looks good so far. Then on the server you run `lncli tower info` and use that pubkey to connect from the client with `lncli wtclient add`? The pubkey is different from `lnd`'s normal node identity pubkey.

**Comment by C-Otto** [comment]
Yeah, I used the regular pubkey. Stupid. Thanks, I wasn't aware of this. Maybe the error message could make this (stupid) mistake any clearer? Maybe the client is able to reject these attempts? Let's wait for the connection (don't see any failure nor success, yet).

**Comment by C-Otto** [comment]
OK, I see a ton of messages I haven't seen before. Looks good to me!
