### ISSUE TITLE
HSWC: Log amount for failed routing attempts

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5367]
### Background
Related to #5250.

For failed forwarding attempts I'd like to see the amount that my node tried to send. At the moment the log message does not show this information:

```
HSWC: ChannelLink(xxx:yyy:0): queueing removal of FAIL closed circuit: (Chan ID=xxx:yyy:0, HTLC ID=123)->(Chan ID=aaa:bbb:0, HTLC ID=456)
```

With the additional amount information I could get a better understanding of how my node is used, and what kind of failures happen further downstream.

I'm fully aware that routing attempts may fail for various reasons, including but not limited to probe transactions.

I'd be very happy to provide a PR, and I already gave it a try. However, I'd need some help finding the amount information in the objects that are available to me at the time of the failure.

### Your environment

lnd 0.13.0-rc5
Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
bitcoind 0.21.0 (bitcoin core)

**Comment by C-Otto** [comment]
https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1499

Sadly, `pkt` does not contain the necessary information. The "Forwarded HTLC" message in https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L1171 uses a `circuit` object instance which contains the forwarded amount.

How can I get access to this information for failed circuits?

**Comment by wpaulino** [comment]
cc @Crypt-iQ, any suggestions?

**Comment by calvinrzachman** [comment]
Hi Carsten,

so I think you're interested in the "failure" case of the function [`processRemoteSettleFails()`](https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta-branch/htlcswitch/link.go#L2457) which handles propagating `UpdateFailHTLC` back through your node towards the original payment sender. My best guess is the `amount` field would need to be set in `htlcPacket` struct at the following location:
```
https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta-branch/htlcswitch/link.go#L2523
```
The HTLC Switch is somewhat of a beast 😄so I'm not exactly sure.

Other candidate locations include:
```
# After your node restarts
https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta-branch/htlcswitch/switch.go#L1907
# I think this is for channel breaches
https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta-branch/htlcswitch/switch.go#L1598
# Probably not this
https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta-branch/htlcswitch/mailbox.go#L670
```

**Comment by C-Otto** [comment]
```
diff --git a/htlcswitch/link.go b/htlcswitch/link.go
index c133c46e..14aa3b6f 100644
--- a/htlcswitch/link.go
+++ b/htlcswitch/link.go
@@ -2538,6 +2538,7 @@ func (l *channelLink) processRemoteSettleFails(fwdPkg *channeldb.FwdPkg,
                                        ),
                                },
                        }
+                       l.log.Debugf("Failed forward to %s with amount %s", l.ShortChanID(), pd.Amount)
 
                        // If the failure message lacks an HMAC (but includes
                        // the 4 bytes for encoding the message and padding
```

This works fine for me, but I don't know if that's something worth merging. Comments?

From my node's logs:

```
22:43:27.589 [DBG] HSWC: ChannelLink(663466:1028:0): Failed forward to 663466:1028:0 with amount 102004 mSAT
22:43:27.590 [DBG] HSWC: ChannelLink(685592:1401:0): queueing removal of FAIL closed circuit: (Chan ID=685592:1401:0, HTLC ID=63)->(Chan ID=663466:1028:0, HTLC ID=1337)
22:43:40.833 [DBG] HSWC: ChannelLink(663466:1028:0): Failed forward to 663466:1028:0 with amount 100004901 mSAT
22:43:40.834 [DBG] HSWC: ChannelLink(685592:1401:0): queueing removal of FAIL closed circuit: (Chan ID=685592:1401:0, HTLC ID=64)->(Chan ID=663466:1028:0, HTLC ID=1338)
```

**Comment by Crypt-iQ** [comment]
If you find it useful I'm sure others will too, feel free to open a PR

**Comment by C-Otto** [comment]
Note to self: the chan ID is already added by the logger, no need to duplicate this
