### ISSUE TITLE
Peers are unable to reconnect and stuck in a deadlock after IP address change 

### ISSUE THREAD

**Issue by viaj3ro** [lightningnetwork/lnd#5377]
As described by @t-bast in https://gitter.im/ACINQ/eclair LND and eclair (possibly c-lightning) peers are unable to reconnect after a IP address change due to not trusting `node_announcement`:

> if you change your IP address, your peers won't reconnect to you. They'll wait for you to connect to them and then will store your new IP address for future reconnections (ie they don't trust the new IP address from `node_announcement` alone)

This leads to a situation where even some clearnet peers have to be manually reconnected which can be quite time consuming and TOR peers are stuck in a deadlock that can only manually be resolved by the node operator of each and every TOR peer. They would have to look up the new IP address of their offline peer on one of the lightning explorer websites and manually feed it to their node. This is unlikely to happen quickly, if at all.

I changed the IP of my node more than 2 days ago and still have 65 disconnected TOR peers. Most, if not all of them seem to be running LND.

I'd suggest to use the IP from `node_announcement` if a connection to the last known IP fails. Can still be alternated with last known IP until success.

Also reported to eclair: https://github.com/ACINQ/eclair/issues/1842

**Comment by Roasbeef** [comment]
Seems all we need to do here, is refresh the target peer IP/addr from the node announcement: https://github.com/lightningnetwork/lnd/blob/master/server.go#L3564

**Comment by ellemouton** [comment]
Cool, i had a go at this today along with adding an itest. I have 2 questions:
1. Is it necessary to only refresh peer advertised addresses [here if the peer is an inbound peer](https://github.com/lightningnetwork/lnd/blob/e62f0e1f3aa9fcc41c68088a842204c484234125/server.go#L3500)? Why not for all peers?
2. is an itest needed for something like this?

**Comment by Roasbeef** [comment]
> Is it necessary to only refresh peer advertised addresses here if the peer is an inbound peer? Why not for all peers?

We do it for inbound peers there as since it's an inbound connection, we may not have the proper port they're actually listening on to connect to (we see the random port assigned by the kernel). 

> Also, is an itest a good idea for something like this?

I think so, to ensure that things are working as expected end to end.

A sample test would look something like:
  * connect to a peer inbound 
  * disconnect 
  * restart inbound node and change the listening port 
  * initial peer should eventually reconnect

**Comment by viaj3ro** [comment]
Any chance for this issue to be resolved any time soon? I still have a handful of TOR peers that refuse to connect back to me even after almost 4 months. Since many nodes have IP address changes once in a while, I assume they have the same issue without ever noticing it.

**Comment by t-bast** [comment]
We didn't have time to work on this yet. @pm47 I'd be curious to have your take on this, as this impacts the connection logic.

Notice that there are related discussione at the spec level: https://github.com/lightningnetwork/lightning-rfc/pull/911
But unrelated of the spec, there is likely something that can be improved in every implementation's reconnection logic.

**Comment by t-bast** [comment]
Note that there are related discussions at the spec level: https://github.com/lightningnetwork/lightning-rfc/pull/911
Independently of that, I believe there are improvements that can be made to implementations (we didn't have time to fix this on the eclair side either yet).
