### ISSUE TITLE
Double spend on forced channel closing race

### ISSUE THREAD

**Issue by MrHash** [lightningnetwork/lnd#538]
If two parties both force close a channel at roughly the same time the later transaction can appear as a double spend and hence the local channel reference is not updated via its `closing_txid`. It seems to me lnd needs to clear the outstanding channel closing reference and update balances based on the prior event.

**Comment by whereyouatwimm** [comment]
@MrHash Is there anyway you can you provide logs from both parties for this scenario?

**Comment by MrHash** [comment]
I don't have logs and i'm on the road at the moment so can't set up a test, but the scenario is quite simple to replicate. Both sides of a channel need to force close at roughly the same time (possibly with no connectivity between the two nodes). The latter tx will be rejected as a double spend so it looks like the pending channels on one side won't be cleaned up.
