### ISSUE TITLE
Accept incoming channels if wallet is empty ("Unable to initialize reservation: reserved wallet balance invalidated")

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5381]
### Background

My node's wallet was empty for quite some time, and only by accident I learned that my node did NOT accept any new incoming channels. For channels using anchor outputs, some minimal on-chain balance needs to be reserved, which in general makes a lot of sense. However, I believe it's not in a node operator's best interest to NOT accept channels because of an empty wallet.

I'd like lnd to "downgrade" the request to some pre-anchor method, so that the channel can be opened.

In my case 7 different peers, including some who are VERY attractive to me, were rejected because of this, before I learned about this behaviour.

### Your environment

lnd 0.13.0-rc5
Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
bitcoind 0.21.0 (bitcoin core)

### Steps to reproduce

Have empty wallet on node A. Open channel to node A.

### Expected behaviour

Channel opens. Alternatively, the error message (both in the logs, and communicated to the peer) should clearly tell what went wrong (and the issue can be fixed).

### Actual behaviour

```
2021-06-12 13:43:04.059 [INF] FNDG: Recv'd fundingRequest(amt=0.02 BTC, push=0 mSAT, delay=240, pendingId=x) from peer(x)
2021-06-12 13:43:04.060 [INF] CHFD: Performing funding tx coin selection using 0 sat/kw as fee rate
2021-06-12 13:43:04.256 [WRN] CHFD: Unable to find funding output for shim intent: unable to create witness script, no funding keys
2021-06-12 13:43:04.257 [ERR] FNDG: Unable to initialize reservation: reserved wallet balance invalidated
2021-06-12 13:43:04.257 [INF] FNDG: Cancelling funding reservation for node_key=x, chan_id=x
2021-06-12 13:43:04.257 [ERR] FNDG: unable to cancel reservation: no active reservations for peer(x)
```

**Comment by halseth** [comment]
Could it be that your wallet had balance but it was unconfirmed at the point this happened? How come the wallet was completely empty?

Unfortunately downgrading a channel is not easy, and accepting incoming channels with an empty wallet can be unsafe.

**Comment by C-Otto** [comment]
No, it was completely empty. There's an easy way to do that: spend all your sats :)

If downgrading a channel-to-be (it's not opened, yet!) is too tricky, I suggest to improve the way this is communicated to the user. Although I see the privacy implications of this, I'd also like to see this in the message sent to the remote peer.

**Comment by halseth** [comment]
Ah, I see. However, lnd won't let you spend all your sats if you already have at least one anchor channel open (if you did have anchor channels, it must be a bug).

So it is kind of a temporary edge case: you spent all your sats and someone opened an anchor channel towards you. The issue should go away once a single anchor channel is up.

I do agree that communicating the failure better would be useful though.

**Comment by C-Otto** [comment]
One of the peers that failed previously due to my empty wallet now opened a channel to my node. However, this channel uses the "STATIC_REMOTE_KEY" type. Could you please double-check that this "legacy" type of channel can be created even if the target node doens't have any funds?

**Comment by Roasbeef** [comment]
> Could you please double-check that this "legacy" type of channel can be created even if the target node doens't have any funds?

If you have no anchor channels, and the other party doesn't support anchors, and wants to open a "legacy" channel that should be permitted. However if you have a _single_ anchor channel, and you attempt to open a "legacy" channel with another peer and your wallet is empty, then that'l fail.

**Comment by Roasbeef** [comment]
If you bump `LNWL` to debug, then you'll see the precise balance failure that happened.

**Comment by wpaulino** [comment]
> However if you have a single anchor channel, and you attempt to open a "legacy" channel with another peer and your wallet is empty, then that'l fail.

Is there a reason behind this other than this was how it was implemented? It seems it should only apply if another anchor channel is being opened, since that's the only commitment type to require an on-chain fund allocation.

**Comment by halseth** [comment]
The reserve check is only done for anchor channels (incoming our outgoing), so it shouldn't affect legacy channels. The only case I can think about is if you are emptying your wallet by opening a new channel, while having anchor channels.

**Comment by wpaulino** [comment]
> The reserve check is only done for anchor channels (incoming or outgoing), so it shouldn't affect legacy channels.

Right, but the reserve is still enforced even when a legacy channel is opened. It seems the check should only happen when an anchor channel is being opened instead?

**Comment by halseth** [comment]
If opening a legacy channel will empty your wallet, and you have existing anchor channels, it shouldn't be allowed.

**Comment by wpaulino** [comment]
Sorry, I should've made clear that I was referring to incoming channels, as described in https://github.com/lightningnetwork/lnd/issues/5381#issuecomment-861413548. So no funds are being contributed to a "legacy" channel in that case, but the reserve was still enforced and the channel was rejected.

**Comment by halseth** [comment]
Ah, right. If that's the case then that's a bug indeed.

**Comment by MrHash** [comment]
i was testing on regtest with 0.13.0 and was able to create a single active channel from node A to B, where node B had no wallet/channel balance, whereas attempting to create a second channel between node A and B failed with `funding failed due to internal error`. I set `--protocol.no-anchors` on the nodes and channel creation was unimpeded.
