### ISSUE TITLE
0 sat transactions. Not approved by me.

### ISSUE THREAD

**Issue by inpharmaticist** [lightningnetwork/lnd#5384]
### Background

0 sat on-chain transactions are listed in my transaction history. I did not make these and the addresses don't seem to be for the wallet of my LND node. I'm told the other apps I'm running (electrs, joinmarket, btc-rpc-explorer, RTL) wouldn't have caused this either.

### Your environment

* RaspiBlitz v1.6.3
* mainnet v0.20.0
* LND 0.11.1-beta

### Steps to reproduce

Not sure, just noticed a few transactions in my history

### Expected behaviour

Only list transactions I've accepted

### Actual behaviour

Seeing seemingly nonrelated transactions.

![image](https://user-images.githubusercontent.com/49789899/121973597-80ece600-cd32-11eb-90c8-445e96851fa8.png)

Truncated a lot here. Looking in BTC explorer on my node, the destination address says is mine = false. It's also noteworthy that there are 44 inputs, and all are legacy addresses (destination is native segwit). Inputs belong to cashapp according to kycp.org. 

{
"tx_hash": "9f5edc......",
"amount": "0",
"num_confirmations": 776,
"block_hash": "00000000.......",
"block_height": 686288,
"time_stamp": "1622842936",
"total_fees": "0",
"dest_addresses": [
"bc1q......"
],
"raw_tx_hex": "020000002d6e421......",
"label": ""
}

**Comment by wpaulino** [comment]
Do you see the `tx_hash` anywhere within your logs that could explain when/where it came from?

**Comment by inpharmaticist** [comment]
Oh, haven't looked. Where do I find the log?

**Comment by wpaulino** [comment]
It depends on your setup, you may want to refer to raspiblitz's documentation. The default path on Linux is usually `$HOME/.lnd/logs`.

**Comment by inpharmaticist** [comment]
Thanks. I found one in `/home/bitcoin/.lnd/logs/bitcoin/mainnet` but it doesn't go back more than 24 hours

**Comment by wpaulino** [comment]
There's also the gzipped ones that go beyond that time which you can search directly with `zgrep` or by decompressing them.

**Comment by inpharmaticist** [comment]
None of them go back before today unfortunately.

**Comment by wpaulino** [comment]
It seems you might've run into https://github.com/lightningnetwork/lnd/issues/3746. This isn't an issue anymore so it shouldn't happen if you update to the latest version. The only way to get rid of the transaction would be to reset the wallet state by restarting lnd with `lnd --reset-wallet-transactions`, which will force a rescan from the wallet's birthday.

**Comment by inpharmaticist** [comment]
I'm on 0.11.1, by latest version you mean 0.13?

**Comment by inpharmaticist** [comment]
Also does `lnd --reset-wallet-transactions` go into the .conf file?

**Comment by wpaulino** [comment]
> I'm on 0.11.1, by latest version you mean 0.13?

`v0.12.1-beta` should work as well.

> Also does lnd --reset-wallet-transactions go into the .conf file?

Yeah if you place `reset-wallet-transactions=true` under the `[Application Options]` header. It's meant to be a temporary config option so you should remove it once the rescan is done.

**Comment by inpharmaticist** [comment]
Thank you!
