### ISSUE TITLE
hltcswitch: when updating fee rates for all channels, respect the advertised min fee rate of active backend

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#5390]
As fees rise in the mempool, so does the fee that most nodes require in order to accept a new transaction to the mempool. If fees rise too much, then anchor channels that use a static-ish fee rate may not be able to get into the mempool as is. To ensure these transactions can always enter the mempool, [when checking to see if we need to update the fee rate](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1093), we should also check that the new fee rate isn't below the current min fee rate. If so, then it should be bumped up to that fee rate to ensure that in a force close scenario, if we're a routing node, we can get the transaction into the chain in time.

**Comment by ellemouton** [comment]
Having a look at this 👍 

I see that all the implementations of `chainfee.Estimator` have a `minFeePerKW` variable which is fetched from bitcoind/btcd at start up but is not changed after that. So it seems that this variable needs to be updated after startup too. I see 2 options for doing this:
1. Instead of just getting the relay fee at startup and then storing it in BitcoindEstimater/BtcdEstimater for the lifetime of the binary, could rather just call out to the node each time the relay fee is needed. Therefore always having the latest correct value.
2. Keep the in-memory relayfee variable (along with a lock) and then have a routine that updates that variable (maybe once per block?).

**Comment by wpaulino** [comment]
> 1. Instead of just getting the relay fee at startup and then storing it in BitcoindEstimater/BtcdEstimater for the lifetime of the binary, could rather just call out to the node each time the relay fee is needed. Therefore always having the latest correct value.
> 2. Keep the in-memory relayfee variable (along with a lock) and then have a routine that updates that variable (maybe once per block?).
>
> 1 is probs the cleanest option depending on how bitcoind/btcd is affected by these calls

Option 1 would be nice, though we should make sure fee estimation doesn't happen within any "hot-paths", as that would lead to another request being made to the backend. This can affect performance with bitcoind-backed nodes since there's no support for long-lived connections (IIRC).

**Comment by ellemouton** [comment]
Cool thanks @wpaulino 👍 

Was checking out exactly where it is used and found that it is also used to set `relayFeeRate` member of `UtxoSweeper`:
```
	// Retrieve relay fee for dust limit calculation. Assume that this will
	// not change from here on.
	s.relayFeeRate = s.cfg.FeeEstimator.RelayFeePerKW()
```
Surely this should also be changed and there should no longer be the assumption that relayFeeRate is static for Utxo sweeping?

If this is also updated to call bitcoind everytime then it starts getting a bit much.  How about adding a 'relayFeeLastUpdatedBlock' variable and then keeping the 'minFeePerKW' variable (and then would need a lock) and then only fetch new relay fee if last updated block is X blocks old?

**Comment by ellemouton** [comment]
How about replacing the `minFeePerKW` member of the FeeEstimators with a `minRelayFeeManager` that looks something like this:?

```
// minRelayFeeManager is used to store and update the minimum relay fee that is
// required by a transaction to be accepted to the mempool.
// The minRelayFeeManager ensures that the backend used to fetch the fee is not
// queried to regularly.
type minRelayFeeManager struct {
	mu                sync.Mutex
	minFeePerKW       SatPerKWeight
	lastUpdatedTime   time.Time
	minUpdateInterval time.Duration
	fetchNewFee       func() (SatPerKWeight, error)
}

// initMinRelayFee is used to set the minFeePerKW of the minRelayFeeManager
// and it requires that the call the the backend succeeds. This is just
// required when the minRelayFeeManager is being initialized.
func (m *minRelayFeeManager) initMinRelayFee() error {
	newMinFee, err := m.fetchNewFee()
	if err != nil {
		return err
	}

	m.minFeePerKW = newMinFee
	return nil
}

// getFee returns the stored minFeePerKW if it has been updated recently or
// if the call the the chain backend fails. Otherwise, it sets the stored
// minFeePerKW to the fee returned from the backend and floors it based on
// our fee floor.
func (m *minRelayFeeManager) getFee() SatPerKWeight {
	m.mu.Lock()
	defer m.mu.Unlock()

	if time.Since(m.lastUpdatedTime) < m.minUpdateInterval {
		return m.minFeePerKW
	}

	newMinFee, err := m.fetchNewFee()
	if err != nil {
		log.Errorf("unable to fetch updated relay fee " +
			"from bitcoind. Using last known relay fee instead")

		return m.minFeePerKW
	}

	// By default, we'll use the backend node's minimum relay fee as the
	// minimum fee rate we'll propose for transactions. However, if this
	// happens to be lower than our fee floor, we'll enforce that instead.
	m.minFeePerKW = newMinFee
	if m.minFeePerKW < FeePerKwFloor {
		m.minFeePerKW = FeePerKwFloor
	}

	log.Debugf("Using minimum fee rate of %v sat/kw",
		int64(m.minFeePerKW))

	return m.minFeePerKW
}

**Comment by Roasbeef** [comment]
@ellemouton I think that works as a generalized clamp for all chain activity, but doesn't seem to address the core issue describe in this issue. 

The issue here is that right now we clamp the fee rate used for anchor commitments: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L6907

What we want to do instead, is factor in the min relay fee as well (within bounds) to do an update of the commitment fee if that value rises above the current max anchor fee. If/when the min relay fee goes back down, then the code will also regulate it to be below the current max value.

**Comment by Roasbeef** [comment]
The other relevant area is here: https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1093 

We only want to update the fee if we "need to". Right now "need to" doesn't factor in the existence of the min relay fee at all.

**Comment by ellemouton** [comment]
@Roasbeef, let me know if the pr i opened is still not addressing the core issue. I think the first commit does. The other commits with the `minRelayFeeManager` are just there so that the minRelayFee being considered is not stale. but i can remove those if they are not needed. Lemme know 👍
