### ISSUE TITLE
Error when installing LND using tutorial

### ISSUE THREAD

**Issue by axelclark** [lightningnetwork/lnd#5398]
### Background

I'm following the installation guide at https://dev.lightning.community/guides/installation/.  I'm receiving an error when installing LND.  I'm not familiar with Go, so I haven't been able to track down the exact issue in the source code.

Also, I noticed the installation instructions in the tutorial don't match the installation instructions in the README.

Tutorial
```terminal
go get -d github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
make && make install
```
README
```terminal
⛰  git clone https://github.com/lightningnetwork/lnd
⛰  cd lnd
⛰  make install
```

I didn't receive the errors following the instruction in the README.

### Your environment

* MacOS
* go version go1.16.5 darwin/arm64

### Steps to reproduce

```terminal
$ go get -d github.com/lightningnetwork/lnd

go get: github.com/roasbeef/btcwallet@none updating to
	github.com/roasbeef/btcwallet@v0.11.0: parsing go.mod:
	module declares its path as: github.com/btcsuite/btcwallet
	        but was required as: github.com/roasbeef/btcwallet

```
### Expected behaviour

I expected to download LND from github.

### Actual behaviour

Received an error.

**Comment by wpaulino** [comment]
> go get -d github.com/lightningnetwork/lnd

Doing this defaults to a tag (v0.0.2) that was published years ago and does not adhere to our current versioning scheme. Once we adopt `go1.16` in our modules, we'll be able to [retract](https://blog.golang.org/go116-module-changes#TOC_5.) it and this method of installing _should_ work.

**Comment by Roasbeef** [comment]
Do this instead:
```
go get -d github.com/lightningnetwork/lnd@v0.13.0-beta
```
