### ISSUE TITLE
Proto file conflict - WARNING: proto: file "rpc.proto" is already registered

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5400]
When linking against `lnd v0.12.1-beta` in another application, the following warning is triggered when using `google.golang.org/protobuf v1.25.0`:

```
2021/06/18 12:09:43 WARNING: proto: file "rpc.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

When using `lnd v0.13.0-beta`, dependencies force `google.golang.org/protobuf v1.26.0` and this warning turns into a panic.

It seems that the root cause of the warning is that multiple lnd proto files use the same package name. In `v0.13.0-beta` those are:

* `rpc.proto`
* `walletunlocker.proto`
* `stateservice.proto`

What I think happens in the `init()` of the generated files is that they all register themselves under the same name and newer versions of protobuf don't accept that.

I suppose the fix is to give each proto a distinct package name.

**Comment by Roasbeef** [comment]
IIRC @guggero has a fix in mind for this, AFAWCT the log message itself is benign and was only added in a _new_ proto version.

**Comment by joostjager** [comment]
Yes, it was added in a new proto version. And in a newer version, it needs to be suppressed actively with a build or env flag to prevent a panic.

The thing is that if your app dependents on lnd for the protos, but needs to 'replace' the protobuf version for other reasons, you'll run into this.

**Comment by guggero** [comment]
Again, it's `etcd` that makes our lives hard. They also have a file called `rpc.proto` which collides with ours. Perhaps we should just rename ours to `lightning.proto` to get rid of the error.

**Comment by joostjager** [comment]
Interesting, so it isn't a conflict between the three files that I listed in the description?

**Comment by guggero** [comment]
No, using multiple files for the same package is fine. But having multiple proto files with the exact same name (even though they're declaring different packages and are being pulled in from dependencies) apparently is not supported (which is really stupid IMO)...

We have two options, really:
1. Suppress the warning at compile time: This needs to be done by each project pulling in `lnd` as a dependency, so not really a nice solution
2. Rename our `rpc.proto` to `lightning.proto`, likely breaking a lot of tutorials/docs/HOWTOs in the process.
