### ISSUE TITLE
Failed to upgrade from 0.12.1 to 0.13.0

### ISSUE THREAD

**Issue by psouthx** [lightningnetwork/lnd#5401]
### Background

Lnd failed to upgrade from 0.12.1 to 0.13.0.

### Your environment

* Lnd: 0.13.0-beta
* OS: Ubuntu 20.04.2 LTS aarch64
* Backend: Bitcoin Core 0.21.0

### Steps to reproduce

1. Upgraded lnd binaries from 0.12.1 to 0.13.0
2. Started lnd

### Expected behaviour

Lnd should start

### Actual behaviour

Lnd failed to start:
```
2021-06-18 07:20:39.527 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
2021-06-18 07:20:39.528 [INF] LTND: Shutdown complete

unable to open databases: unable to obtain database backends: file size too small

**Comment by wpaulino** [comment]
Are you still able to start the node if you downgrade back to `v0.12.1`?

**Comment by Roasbeef** [comment]
Do you have sufficient disk space in the instance?

**Comment by psouthx** [comment]
Yes, the node starts fine in `v0.12.1`. Regarding disk space, not sure how much is needed but the free space is about the same as the total amount consumed by the `data` dir (i.e. the `data` dir would have to double in size to fill the disk).

**Comment by Roasbeef** [comment]
What config params are you running lnd with? The fact that you're able to downgrade in general shows the upgrade (and migrations) were never actually completed.

**Comment by psouthx** [comment]
This is `lnd.conf`:
```
[Application Options]
maxpendingchannels=.........
externalip=.........
externalhosts=.........
alias=.........
color=.........
MinChanSize=.........
listen=.........
rpclisten=.........
restlisten=.........
tlsextradomain=.........
protocol.wumbo-channels=1

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.feerate=.........

[Bitcoind]
bitcoind.rpchost=.........
bitcoind.rpcuser=.........
bitcoind.rpcpass=.........
bitcoind.zmqpubrawblock=.........
bitcoind.zmqpubrawtx=.........

[Tor]
tor.active=1
tor.socks=.........
```

It seems like the database was not upgraded because it could not be opened as per the error message:
`unable to open databases: unable to obtain database backends: file size too small`

**Comment by guggero** [comment]
> Regarding disk space, not sure how much is needed

Since you don't have auto compaction turned on, there shouldn't be any more space needed than before.

This is very weird, the error definitely comes from `bbolt`: https://github.com/etcd-io/bbolt/blob/v1.3.5/db.go#L336

Might be a stupid question, but what binary are you running for `v0.13.0`, since you're mentioning `aarch64`. Are you sure you're running the `linux-arm64` binary and not the `linux-armv7` by accident?

**Comment by psouthx** [comment]
After building from source it seems like it's working fine.

I believe the binary was the right one. As a matter of fact, there are two nodes running on that server and only one had problems. The other node upgraded without issues.

Since it's not possible to reproduce the problem anymore I'll be closing it. Thanks.
