### ISSUE TITLE
Payments across nodes sometimes fail due to CLTV rejection

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#5406]
### Background

When making a payment using SendPaymentV2, the CLTV delta seems to get set incorrectly and the payment is rejected.

### Your environment

* LND 0.13.0

### Steps to reproduce

On nodes that have been running for a while:

1. Create invoice on node A (lncli addinvoice)
2. Pay 1 sat to the request with node B: (lncli payinvoice <req> --amt 1)

I haven't been able to reproduce it in regtest, but seen independently on multiple nodes

### Expected behavior

Payment should succeed

### Actual behavior

Recipient sees invalid CLTV delta and rejects the payment

**Comment by Crypt-iQ** [comment]
Could this be due to a block being mined while the payment is in flight?

**Comment by alexbosworth** [comment]
After running https://github.com/lightningnetwork/lnd/pull/5404 for a while it seems that solves the problem on my nodes
