### ISSUE TITLE
queryroutes failed 

### ISSUE THREAD

**Issue by rick-li** [lightningnetwork/lnd#541]
I have three nodes
A: 03c34557081c4aed7573f10473666cfc11154dc3ef0551fedddf8d406092b3fe0b
B: 020a940e1b4f34a594220421a46e3729bada8cc11ae48ac284cfe711617d292957
C: 034dab37e662fabb34814c6bf742b1906e24f676159377b46a7efef402ac30f5d8

A has a channel with B who has a channel with C

from Node A queryroutes to Node C failed.
lncli queryroutes  --dest 034dab37e662fabb34814c6bf742b1906e24f676159377b46a7efef402ac30f5d8 --amt 100

[lncli] rpc error: code = Unknown desc = target not found

**Comment by halseth** [comment]
Can you paste the result of `describegraph` before doing `queryroutes`? Thanks!

**Comment by halseth** [comment]
Also, make sure all funding transactions have at least 6 confirmations :)

**Comment by rick-li** [comment]
@halseth  Thanks for the info, now it works., I guess it was due to less than 6 confirmation.
