### ISSUE TITLE
Channel stuck in Waiting Close

### ISSUE THREAD

**Issue by Loksley** [lightningnetwork/lnd#5414]
### Background

I have a 300k sats channel with OpenNode.com that I tried to close 2.5 weeks ago.
I triggered the close in RTL and got an error message (I did not write this down unfortunately!) Since then the channel is shown under "Waiting Close".

The fee was set at 5 sat/vbyte which should be enough given the mempool cleared several times since then.
Both nodes are online and OpenNode.com (03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e) is connected as peer.

### Your environment

* version of `lnd`: v0.12.1-beta
* Umbrel 0.3.12 on Raspberry Pi 4 Model B Rev 1.4

### Steps to reproduce

- c. 2.5 weeks ago, closed channel using RTL (5sat/vbyte), received error message (not recorded unfortunately)
- Since then the channel is shown under "Pending / Waiting Close"
- lncli pendingchannels show:
`{
    "total_limbo_balance": "292781",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
                "channel_point": "60ffc05a5d310f39acaaca158ab26f91f7901cf02076cb4455d9fe1d08b985f5:0",
                "capacity": "300000",
                "local_balance": "292781",
                "remote_balance": "0",
                "local_chan_reserve_sat": "3000",
                "remote_chan_reserve_sat": "3000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "292781",
            "commitments": {
                "local_txid": "9dbc92f24091fe8563fe82619969b809990c998e5be6ba01c6326eefc9ec578d",
                "remote_txid": "8670c8fa13f86f2bc637e375f72c88cd8c6d55dda8542883f077005e2b842c2a",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "7219",
                "remote_commit_fee_sat": "7219",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}`

- When entering `lncli closechannel 60ffc05a5d310f39acaaca158ab26f91f7901cf02076cb4455d9fe1d08b985f5 0` to re-trigger the channel close, there is no command line output and nothing changes
- When searching log file for the channel point I found:
`2021-06-21 14:36:00.226 [INF] PEER: NodeKey(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e) loading ChannelPoint(60ffc05a5d310f39acaaca158ab26f91f7901cf02076cb4455d9fe1d08b985f5:0)`
`2021-06-21 14:36:00.226 [WRN] PEER: ChannelPoint(60ffc05a5d310f39acaaca158ab26f91f7901cf02076cb4455d9fe1d08b985f5:0) has status ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator, won't start.`

### Expected behaviour

Channel close to be re-triggered by closechannel command and channel closes cooperatively.

### Actual behaviour

Channel remains stuck in Waiting Close.

**Comment by Roasbeef** [comment]
If you attempted to do a cooperative closure, and the connection broke down for some reason, then you'll unfortunately need to _force close_ the channel instead. AFAICT, the co-op close transaction was never broadcasted (neither side ever received an echo signature back). 

Closing this as is, see #4819 for more details.

**Comment by Loksley** [comment]
Thank you for your response.
It's a shame but will do a force close then.
