### ISSUE TITLE
IncorrectOrUnknownPaymentDetails for all payments after lnd runs for a while

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#5415]
### Background

Updated to 13.0 beta rc 5.
After several hours of uptime, all payments start failing with `IncorrectOrUnknownPaymentDetails`
As usual, restarting LND remedies the situation.

### Your environment

* v0.13.0-beta.rc5
* `Linux lnd2 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* neutrino

**Comment by Overtorment** [comment]
ps. usually testing from cli using `lncli sendpayment     --force --pay_req  xxx  --amt 2`

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/pull/5404

**Comment by alexbosworth** [comment]
does this scenario repro on your failing nodes? https://github.com/lightningnetwork/lnd/issues/5406

**Comment by Overtorment** [comment]
looks like patch from #5404  helped. so far so good
