### ISSUE TITLE
ERR_INFORMATION_LEAK

### ISSUE THREAD

**Issue by ackoco** [lightningnetwork/lnd#542]
The client used was eclair for Android with testnet. Funds are locked. TXID as below :

{
  "block_hash": "000000008f424a8d50b075fa0e376415efb90c8a8dc7bb6a799e1e000b6f009d",
  "block_height": 1256804,
  "block_index": 43,
  "hash": "b14cef07fa84ec37d6d79ba712b6ba3321cd0dee93edcb75413be60cc117ada1",
  "addresses": [
    "2N1hEJUtskeo4ty6EoVNVhcHS3QWZLGysrm",
    "2NBSajsb9hXuqkkB9j8kVH7zrowqgGG69uN"
  ],
  "total": 198945856,
  "fees": 27072,
  "size": 149,
  "preference": "low",
  "confirmed": "2017-12-30T15:49:54Z",
  "received": "2017-12-30T15:49:54Z",
  "ver": 2,
  "double_spend": false,
  "vin_sz": 1,
  "vout_sz": 2,
  "confirmations": 174,
  "confidence": 1,
  "inputs": [
    {
      "prev_hash": "d882df52c9db3d3a8e47e355e6b38a3e58d69506128cf928dfc725d9c70468a6",
      "output_index": 1,
      "script": "16001457da70ec96eef0c44458f4c3b6bc548276b8d42f",
      "output_value": 198972928,
      "sequence": 4294967295,
      "addresses": [
        "2NBSajsb9hXuqkkB9j8kVH7zrowqgGG69uN"
      ],
      "script_type": "pay-to-script-hash",
      "age": 1256739,
      "witness": [
        "3045022100a9053638a0416abc0843ab22b2638dc42a82e7f052cd459710e5ec4d2195fb1302201f13725c13ece7e69d3ab6884c5babbbe59a6db8afaf91a6d550eacedc9a072601",
        "03438a3ddb313bc94b20d7f43187ae5b42d99b33efc3f7a5da9296bd6c54d05586"
      ]
    }
  ],
  "outputs": [
    {
      "value": 200000,
      "script": "00207eaa0286dcae2b08de30c2b033584aff911b6c30a4aca456c3141ca85bafae12",
      "spent_by": "65837945e3aca1368f6827673111250aa134587de107b392bf06188addd2cbb9",
      "addresses": null,
      "script_type": "pay-to-witness-script-hash"
    },
    {
      "value": 198745856,
      "script": "a9145cac154bb43e2bc26ca0448c56a86a1edea66bee87",
      "addresses": [
        "2N1hEJUtskeo4ty6EoVNVhcHS3QWZLGysrm"
      ],
      "script_type": "pay-to-script-hash"
    }
  ]
}

**Comment by ackoco** [comment]
![screenshot_20180101-071503](https://user-images.githubusercontent.com/7787640/34465939-dd195ed2-eec3-11e7-9c63-d5ce53d4296b.png)
Screenshot of the channel state

**Comment by Roasbeef** [comment]
This isn't an issue tracker for `eclair`. Please re-open this issue on their repo. Thanks!
