### ISSUE TITLE
Pruned node, invoice payments fail with ExpiryTooSoon error

### ISSUE THREAD

**Issue by 1443** [lightningnetwork/lnd#5421]
### Background

Trying to pay an invoice on testnet with a pruned node and bitcoind backend fails with ExpiryTooSoon error. Channel is active, node is synced to chain and graph. Using the exact same wallet, channel and invoice succeeds with Neutrino backend.

### Your environment

* version of `lnd`: 0.13.0
* which operating system: Raspberry Pi OS
* version of `bitcoind`: 0.21.0

### Steps to reproduce

Make new channel with aranguren.org node, try to pay htlc.me invoice with pruned node bitcoind backend.

### Expected behaviour

Payment should succeed.

### Actual behaviour

Payment fails with ExpiryTooSoon error.
[lnd_pruned.log](https://github.com/lightningnetwork/lnd/files/6694621/lnd_pruned.log)

**Comment by yyforyongyu** [comment]
The `outgoing_expiry` is already behind the current height, weird.
```go
2021-06-21 19:29:58.209 [ERR] HSWC: ChannelLink(2005763:11:0): 
htlc(2d783f63b3a23996983949bd68249038fd959df9137b2635bf52246f6e1dae62) has an expiry that's too soon: 
outgoing_expiry=2005718, best_height=2005766
```

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/pull/5404

**Comment by wpaulino** [comment]
> Using the exact same wallet, channel and invoice succeeds with Neutrino backend.

If you're switching between backends on the same node, then it's possible you were also running with the `routing.assumechanvalid` config option with the bitcoind backend as well? That config option is not necessary with the bitcoind backend. If so, then you've also run into #5404.
