### ISSUE TITLE
Recovery window failing to detect transaction to same address as one it has detected

### ISSUE THREAD

**Issue by ProofOfKeags** [lightningnetwork/lnd#5422]
### Background

I have a situation where LND has detected a transaction to a particular address it is aware of but not another.

Showing: https://blockstream.info/tx/4f43fbffc33d8bf298e410aafed3ac1d2fb162d6da59bd9e2a5b7b05b9d2ea7a
Missing: https://blockstream.info/tx/a039e4cb3825607d65157d3444580c469aff3b6d4899f3812b80016615dab71c

What's strange is that the one that is showing happens at a later block height than the one that is missing. Several instances of in-place rescans have taken place with recovery windows of 5, 10, 550 and 20000. In each case the recovery process was unable to detect the missing transaction.

If I were to speculate on the cause of this situation, I might guess that for optimization purposes if LND is aware of a transaction that occurs at a certain height, it may assume that that is the first time that address was used and only scan subsequent blocks for transactions that are encumbered to the same address.

### Your environment

EmbassyOS 0.2.13

* LND 0.12.1
* Linux 5.4.51-v7l+ 1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
* bitcoind 0.21.1

### Steps to reproduce

The customer in question did this

 1. Fund on chain wallet via Ride The Lightning
 2. Open channel 1
 3. Open channel 2
 4. Close channel 1
 5. Close channel 2
 6. Take lnd service backup (backs up all of lnddir)
 7. Remove all funds from onchain wallet
 8. Send small tx back to onchain wallet address in Ride The Lightning
 9. Opened Ride The Lightning and confirmed that I saw that incoming tx (the one that ultimately went missing)
 10. Logged out of Ride The Lightning
 11. Restored lnd from backup (restores all lnddir data, overwriting previous contents of lnddir, except the channel database which is deleted)
 12. Logged into Ride The Lightning
 13. Sent a second transaction to the address where the tx went missing (this one showed up)
 14. Performed recovery processes at 5, 10, 550, and 20000 window sizes
 
The channel activity here appears to be irrelevant but is included for thoroughness.

### Expected behaviour

All transactions to the addresses the wallet is aware of would show up in the on-chain transaction history

### Actual behaviour

Only the latter transaction to one of the addresses was detected. Recovery windows did not seem to fix this.

### Speculation

Given that it is detecting one of the transactions that went into this address, the backup restore process clearly left the keys intact. Since the missing transaction was initially detected but never confirmed before the lnddir was replaced, it makes sense why the transaction could be missing initially. The subsequent transaction may have also tricked LND into thinking that there were no earlier transactions to that address. It is possible also that the wallet.db file is carrying some piece of state that is causing it to not want to rescan the transaction occurring 10 blocks earlier.

**Comment by Roasbeef** [comment]
> LND 0.12.1

Are you able to repro w/ 0.13?

**Comment by Roasbeef** [comment]
> it may assume that that is the first time that address was used and only scan subsequent blocks for transactions that are encumbered to the same address.

We always watch for all known addresses on start up: https://github.com/btcsuite/btcwallet/blob/6ab9b615576f4a86c31bcaef9eddee060b36da00/wallet/wallet.go#L322

> Several instances of in-place rescans have taken place with recovery windows of 5, 10, 550 and 20000. In each case the recovery process was unable to detect the missing transaction.

Do you know what the "birthday height" of the wallet is?

**Comment by ProofOfKeags** [comment]
How would I ascertain the wallet birthday, either from files in the datadir or lncli?

**Comment by guggero** [comment]
There's no easy way to look it up from any of the files AFAIK. You can extract the birthday from the seed using my web tool: https://guggero.github.io/cryptography-toolkit/#!/aezeed

Might be something I should add to `chantools` to not be reliant on a web tool for things seed related...

**Comment by wpaulino** [comment]
@ProofOfKeags if you run with `LNWL=debug` and restart, you should see a log message showing the birthday block hash and height.

**Comment by Crypt-iQ** [comment]
Do you have any logs for this

**Comment by guggero** [comment]
Any update on this? If you restore the wallet from seed (not from a file based backup) with the latest version, is one transaction still not being picked up? Can you check if the destination address is in the list if you run [`chantools genimportscript --lndpaths`](https://github.com/guggero/chantools/blob/master/doc/chantools_genimportscript.md)?
