### ISSUE TITLE
Channel update propagation speed

### ISSUE THREAD

**Issue by rkfg** [lightningnetwork/lnd#5426]
### Background

I can't find reliable information about this anywhere so decided to ask here as the developers surely know better! How fast do the node/channel updates propagate? I use [charge-lnd](https://github.com/accumulator/charge-lnd) to provide hints to the users about my channel balances, those that have too much outbound liquidity get lower fees so they're more likely to be used in routing. However, these changes seem to take a lot of time to propagate to other nodes. I check my channels at 1ml.com and amboss.space, the latter shows outdated fees and it's been almost 3 hours since they were changed. I don't think it takes less than 1 hour at least to reach these public browsers.

What's even more interesting is that even those nodes that connect to my node directly don't get these updates quick enough. For example, my Breez wallet connects to my node via a private channel and when I run `getchaninfo 7540...` in the developer console I get old fees. `getinfo` says `"syncedToGraph": true` and `"syncedToChain": true`. Breez uses `lnd 0.12.1-beta` currently. My friend also connects to my node via a public channel and he also reported old fees for that channel.

I wouldn't care about this but it sometimes causes routing to fail due to insufficient fees because the sender used outdated information. How can this be sped up if at all? Is it a bug or a fundamental limitation (or a DoS prevention measure)? I don't know if there's any other way to signal channel balances to the world so that users don't blindly pick channels without enough liquidity and fail too often. I understand why channel balances have to be private but changing fees is a really good mechanic that preserves privacy and lets balance channels naturally.

### Your environment

* `lnd v0.13.0-beta-27-gf9a51882`
* `Linux 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux` (RPi 4B)
* `Bitcoin Core v0.21.1`

### Steps to reproduce

- update channel fees via RPC or external tools

### Expected behaviour

- the new values are propagated to other nodes relatively quickly (10-15 minutes to remote nodes and withing minutes to the directly connected nodes)

### Actual behaviour

- the new values are propagated to other nodes for hours, even to those that have channels opened to my node

**Comment by Roasbeef** [comment]
> How fast do the node/channel updates propagate?

The short answer is "eventually". Each node may have different parameters w.r.t how quickly it sends out updates, how many batches it sends out at a time, etc. You shouldn't count on them being transmitted "instantly" across the network, things are batched and staggered to reduce bandwidth usage and duplicate updates being transmitted.
