### ISSUE TITLE
Add lncli command for `PublishTransaction`

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#5438]
This is already an API for `PublishTransaction` but it not reachable through using `lncli`.
It would be nice to have so if we need to use it we don't need to use something like `curl` or manually coding it.

**Comment by ErikEk** [comment]
I can look into it.

**Comment by guggero** [comment]
I think this would come in handy. Since the RPC is only available in the `walletrpc` subserver the command should be conditionally compiled into the `lncli wallet` command which is only available if the `walletrpc` subserver is. So the command would be something like `lncli wallet publishtx`.

**Comment by ErikEk** [comment]
> I think this would come in handy. Since the RPC is only available in the `walletrpc` subserver the command should be conditionally compiled into the `lncli wallet` command which is only available if the `walletrpc` subserver is. So the command would be something like `lncli wallet publishtx`.

Thanks for the guidance. I'll take a shot at this.

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/5460
