### ISSUE TITLE
Documentation on macaroons is wrong

### ISSUE THREAD

**Issue by jblachly** [lightningnetwork/lnd#5444]
### Background

Macaroons are created after wallet creation. However, the documentation in the main installation (https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) states the following:

> Running lnd for the first time will by default generate the admin.macaroon, read_only.macaroon, and macaroons.db files that are used to authenticate into lnd.

As a first-time LND user, I was bitten by this today because I first wanted to run `lncli getinfo`; it took some searching to realize I had to first run `lncli create` in order to create the macaroon files.

As you can see, this has confused users for a long time: this old closed issue https://github.com/lightningnetwork/lnd/issues/1190 which is reflective of the same wrong documentation, had a user post as recently as late 2020.

### Your environment

* version of `lnd`: v0.13.0-beta
* `Linux hostname 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* `bitcoin-0.18.0`

### Steps to reproduce

1. Run `lnd` for the first time, connecting via RPC to bitcoind
2. Run `lncli getinfo`

### Expected behaviour

Should not fail with macaroon error

### Actual behaviour

Macaroons do not yet exist, which is in direct conflict with the documentation

**Comment by guggero** [comment]
Yes, the doc could be improved here. PRs are welcome.

**Comment by gabbyprecious** [comment]
Hi @guggero can I send a quick pr for this?

**Comment by tvolk131** [comment]
@guggero this is fixed with #6348, right?

**Comment by guggero** [comment]
Yes, thanks for the reminder, @tvolk131!

Fixed by https://github.com/lightningnetwork/lnd/pull/6348.
