### ISSUE TITLE
Channel pruning causes lnd to crash

### ISSUE THREAD

**Issue by patrikmojzis** [lightningnetwork/lnd#5445]
### Background

LND crashes after it attempts to prune channels.

```
2021-06-28 18:32:38.654 [INF] CRTR: Pruning 34102 zombie channels
unexpected fault address 0x5ead7040
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x5ead7040 pc=0x4fc4b4]
```

Full output:
[https://justpaste.it/25el0](https://justpaste.it/25el0)

### Your environment

- lnd 0.13 (but the issue persists from version 0.12)
- neutrino
- tor

### Steps to reproduce
Not clear. It worked normally until it did not. No changes were made.

**Comment by Crypt-iQ** [comment]
This seems like database corruption, so perhaps channel pruning is not the cause.  What hardware are you running on?

**Comment by patrikmojzis** [comment]
I'm using Raspberry Pi 4.

**Comment by patrikmojzis** [comment]
Seems like you were right. I started it on my mac and it works. Thanks.
