### ISSUE TITLE
btcpayserver LND Unavailable

### ISSUE THREAD

**Issue by Ruinous101** [lightningnetwork/lnd#5454]
Hi I opened this issue with btcpayserver but not getting support like I did back in 2019 when testing manual deployment and VPS deployments.

currently I have a btcpayserver on VPS with the following error (documented here: https://github.com/btcpayserver/btcpayserver-docker/issues/494#issue-933037976).

`[ERR] LTND: unable to create chain control: unable to subscribe for zmq block events: dial tcp: lookup bitcoind: no such host`

I'm a non technical user but can follow direction well to troubleshoot. I was able to get view of the LND config but as of yet waiting in reply to view bitcoind config instruction for btcpayserver. Everything should be default settings using the internal LND node and is "legacy" in their terms without seed backup. So help to get this node online and closing channels to migrate to version with seed would be optimal. I suppose I would have done it sooner but have had no issues, and simple restarts typically solve errors in the past.

I don't know how to reproduce, as mentioned no errors till a couple days ago, with LND "unavailable".

**Comment by Roasbeef** [comment]
Looks like it's trying to connect to `bitcoind` within the container, but the DNS alias used isn't up to date? Not sure exactly, you'll likely have better success with the btcpay issue tracker, as we focus on lnd specific issues here. 

I'd double check that the `bitcoind` instance is actually active, and reachable under the `bitcoind` DNS alias (a local docker-compose thing).

**Comment by Ruinous101** [comment]
Thanks the eyes on potentially being DNS, had me look more at the server since bitcoind is active/online. A few package installs and LND node is online again (after server shutdown/startup). Still would love reply for file locations on bitcoind config from btcpay side to change some defaults.
