### ISSUE TITLE
[Feature Request]: Allow updating node announcement data without restarting the node

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#5466]
Updating data for graph node announcements currently requires restarting the node, which reduce the quality of service of the node. Additionally custom feature bits cannot be set for use in experimental or 3rd party solutions and features like larger channel signaling can also not be dynamically updated.

Ideally the node announcement elements could be adjusted at run-time using an API:

- node network addresses
- node alias string
- node color
- node feature bits (high range for custom bits)

This could help in scenarios such as:

- Updating the graph to a new dynamically assigned IP address
- Updating graph exploration displays
- Dynamically turning on and off large channel signaling based on channel acceptance policy updates

**Comment by Roasbeef** [comment]
Picking this up.
