### ISSUE TITLE
Locked outputs stay in listleases after their lease is expired

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#5467]
### Background

In the `ListLeases` API in walletkit, the call is described as "ListLeases lists all currently locked utxos."

When locking a UTXO using the LeaseOutput, after expiration the leased UTXO continues to appear in the response even
though it also shows up in the `ListUnspent` output after expiration, indicating it is not leased.

### Your environment

* lnd 0.13.0

### Steps to reproduce

- Lease a UTXO
- Wait for the lease to expire
- Call ListLeases

### Expected behavior

I expect to see only leased UTXOs returned

### Actual behavior

Non-leased UTXOs are returned

**Comment by joostjager** [comment]
Looked into this and it seems that leases are only really removed on startup. The workaround is to filter the list client-side. Maybe we can add server-side filtering to 0.13.1?
