### ISSUE TITLE
`protocol.anchors=[t/f]` is not a valid option in lnd.conf in LND 0.13.0

### ISSUE THREAD

**Issue by ProofOfKeags** [lightningnetwork/lnd#5474]
According to the below option in the config sample it appears that I should be able to specify `protocol.anchors`

https://github.com/lightningnetwork/lnd/blob/v0.13.0-beta/sample-lnd.conf#L391-L394

However, it appears that upon doing this it does not work. Is this a leftover option from 0.12.x when anchors were not the default?

https://github.com/lightningnetwork/lnd/releases/tag/v0.13.0-beta

**Comment by yyforyongyu** [comment]
> However, it appears that upon doing this it does not work. Is this a leftover option from 0.12.x when anchors were not the default?

Yeah it wasn't updated and was fixed in #5439. The coming `v0.13.1-beta.rc1` should have it included.
