### ISSUE TITLE
EMERGENCY! Node suddenly cannot open BBOLT db. "file size too small"

### ISSUE THREAD

**Issue by wankerstar** [lightningnetwork/lnd#5490]
### Background

PLEASE HELP!  Here's what I get:

Jul 10 00:48:35 dietnode systemd[1]: Stopped LND Lightning Network Daemon.
Jul 10 00:48:35 dietnode systemd[1]: Started LND Lightning Network Daemon.
Jul 10 00:48:35 dietnode lnd[1406]: Attempting automatic RPC configuration to bitcoind
Jul 10 00:48:35 dietnode lnd[1406]: Automatically obtained bitcoind's RPC credentials
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.560 [INF] LTND: Version: 0.13.0-beta commit=v0.13.0-beta, build=production, logging=default, debuglevel=info
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.561 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.564 [INF] RPCS: RPC server listening on 127.0.0.1:10009
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.578 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.579 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.579 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
Jul 10 00:48:35 dietnode lnd[1406]: 2021-07-10 00:48:35.583 [INF] LTND: Shutdown complete
Jul 10 00:48:35 dietnode lnd[1406]: unable to open databases: unable to obtain database backends: file size too small
Jul 10 00:48:35 dietnode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 00:48:35 dietnode systemd[1]: lnd.service: Failed with result 'exit-code'.

### Your environment

lnd 0.12, 0.13 - happens with both. dietpi 64-bit on an RPi4

### Steps to reproduce

Happened suddenly while a rebalance script was running.

**Comment by Roasbeef** [comment]
How large is `channel.db` on disk? That error is returned by bolt, the underlying database when it goes to set up the initial memory map.  The error is triggered when it fails to perform the memory map, as the underlying file size is less than 2x the page size. Sounds like maybe the file has been replaced, or truncated or for some reason.

**Comment by wankerstar** [comment]
I'm not seeing a channels database file, actually.

How is that possible? Could the database have been corrupted in such a way that the filesytem won't list it?

Excuse me if I'm missing something obvious, I'm rather in a panic.

bitcoin@dietnode:~ $ ls /mnt/ext/lnd/data/chain/bitcoin/mainnet/ -lAF
total 2024
-rw-r----- 1 bitcoin bitcoin     293 May  3 18:11 admin.macaroon
-rw-r--r-- 1 bitcoin bitcoin      83 May  3 18:11 chainnotifier.macaroon
-rw-r--r-- 1 bitcoin bitcoin   58279 Jul  9 07:39 channel.backup
-rw-r--r-- 1 bitcoin bitcoin     132 May  3 18:11 invoice.macaroon
-rw-r--r-- 1 bitcoin bitcoin      91 May  3 18:11 invoices.macaroon
-rw-r----- 1 bitcoin bitcoin   20480 Jul  9 07:38 macaroons.db
-rw-r--r-- 1 bitcoin bitcoin     217 May  3 18:11 readonly.macaroon
-rw-r--r-- 1 bitcoin bitcoin      91 May  3 18:11 router.macaroon
-rw-r--r-- 1 bitcoin bitcoin      92 May  3 18:11 signer.macaroon
-rw-r----- 1 bitcoin bitcoin 1957888 Jul 10 00:37 wallet.db
-rw-r--r-- 1 bitcoin bitcoin     114 May  3 18:11 walletkit.macaroon

**Comment by wankerstar** [comment]
Thanks, @Roasbeef ! Did I hit another file size limit somehow?

-rw-r--r-- 1 bitcoin bitcoin 2147491840 Jul 10 00:37 channel.db

**Comment by wankerstar** [comment]
Attempting compacting with chantools on a more memory-rich machine. Hopeful this will work.

**Comment by wankerstar** [comment]
Worked. I apparently need to be more careful with my database size regardless of architecture.

Sorry to bother you, @Roasbeef , and thanks again for the help!
