### ISSUE TITLE
itest-flake: AMP send payment chan open timeout

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#5500]
Doesn't appear related at all to AMP, instead that some announcements don't arrive before the current test timeout is hit: 
```
=== RUN   TestLightningNetworkDaemon/29-of-82/neutrino/multi-hop_payments_over_private_channels
    test_harness.go:88: Failed: (sendpayment amp): exited with error: 
        *errors.errorString (36): timeout waiting for channel(4b569e427eac3528125336988864964b48d48e32dd65136af6555e1dbad28087:0) open: channel not opened before timeout
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_mpp_test.go:349 (0xf01789)
        	(*mppTestContext).waitForChannels: c.t.Fatalf("(%d): timeout waiting for "+
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_amp_test.go:234 (0xee9dd2)
        	testSendPaymentAMP: ctx.waitForChannels()
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/test_harness.go:112 (0xee7aee)
        	(*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:11702 (0xf9902f)
        	TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
        /home/travis/.gimme/versions/go1.16.3.linux.amd64/src/testing/testing.go:1193 (0x51c72f)
        	tRunner: fn(t)
        /home/travis/.gimme/versions/go1.16.3.linux.amd64/src/runtime/asm_amd64.s:1371 (0x471c01)
        	goexit: BYTE	$0x90	// NOP
=== RUN   TestLightningNetworkDaemon/49-of-82/neutrino/revoked_uncooperative_close_retribution_altruist_watchtower/legacy
```

**Comment by guggero** [comment]
Here are the logs from my most recent local run that provoked the flake:
[amp-chan-open-timeout.zip](https://github.com/lightningnetwork/lnd/files/6810996/amp-chan-open-timeout.zip)

**Comment by Roasbeef** [comment]
Adding some additional context, the above failed run was using the neutrino backend ^

**Comment by Roasbeef** [comment]
Potentially useful log fragment: 
```
  65 2021-07-13 19:52:35.104 [INF] NTFN: Missed blocks, attempting to catch up
  64 2021-07-13 19:52:35.104 [ERR] NTFN: unable to get missed blocks: starting height 742 is greater than ending height 741
```

**Comment by Roasbeef** [comment]
Don't think that's relevant as it seems to heal properly later on. 

Here's what I think is happening: 
  * The `mppTestContext` [is used to create 6 channels back to back](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_amp_test.go#L43)
  * The method used to create the channel ends up calling [`openChannelAndAssert`](https://github.com/lightningnetwork/lnd/blob/edd4152682dc8f70e11da541cd3be4692db4b011/lntest/itest/lnd_mpp_test.go#L300) which'll open the channel, mine 6 blocks, [then ensure that the channel gets advertised](https://github.com/lightningnetwork/lnd/blob/edd4152682dc8f70e11da541cd3be4692db4b011/lntest/itest/assertions.go#L78)
   * Later on, [we wait for all nodes to hear about all channels on the network level](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_amp_test.go#L62)


I think the issue here is that we'll potentailly alreayd have mined 30 or so blocks before getting to the final nodes, and those nodes may have already heard about the channel already. This may then cause their [`lightningNetworkWatcher`](https://github.com/lightningnetwork/lnd/blob/edd4152682dc8f70e11da541cd3be4692db4b011/lntest/node.go#L1213) goroutine to not properly dispatch this, since it's assumed that the channel hasn't been announced (or notified) when the method is called. 

One solution here is to just check if the channel is already in the node's graph or not, when we go to register the notification. If we do this in the same state machine as the watcher, then we ensure if the channel is already known, the client is immediately notified. One thing that can help us debug this more in the future is adding additional logging in some of these helper goroutines so we can more easily track the control flow.
