### ISSUE TITLE
Startup endless loop 

### ISSUE THREAD

**Issue by zanderisrael** [lightningnetwork/lnd#5502]
### Background

LND unable to startup after password manual input, simply reboots

### Your environment

lnd 0.12.1
Raspiblitz

Starting LND Lightning Daemon...
Jul 10 22:33:49  systemd[1]: Started LND Lightning Daemon.
Jul 10 22:35:32  lnd[11017]: panic: runtime error: slice bounds out of range [::5770623284] with length 2147
Jul 10 22:35:32  lnd[11017]: goroutine 1 [running]:
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.unsafeByteSlice(...)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/unsafe.go:27
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*leafPageElement).key(...)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/page.go:126
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x6926, 0x0)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:328 +0x
Jul 10 22:35:32  lnd[11017]: sort.Search(0xd24c, 0x4000705a00, 0x60)
Jul 10 22:35:32  lnd[11017]:         sort/search.go:66 +0x4c
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).nsearch(0x4000705e68, 0x7f80034850, 0x8, 0x8)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:327 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).search(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0xbd59)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:257 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).searchPage(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0x7
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:308 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).search(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0x373e)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:265 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).searchPage(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0x7
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:308 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).search(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0xcca5)
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:265 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Cursor).seek(0x4000705e68, 0x7f80034850, 0x8, 0x8, 0x0, 0x8,
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/cursor.go:159 +0x
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Bucket).Get(0x400204a340, 0x7f80034850, 0x8, 0x8, 0x28, 0xe1
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/bucket.go:262 +0x
Jul 10 22:35:32  lnd[11017]: github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).Get(0x400204a340, 0x7f8003
Jul 10 22:35:32  lnd[11017]:         github.com/btcsuite/btcwallet/walletdb@v1.3.5/bdb/db.go:211 +0x40
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/channeldb.fetchChanEdgeInfo(0x7f8791aca8, 0x400
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/channeldb/graph.go:3864 +0x6c
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView.func1.1(0
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/channeldb/graph.go:3364 +0x118
Jul 10 22:35:32  lnd[11017]: go.etcd.io/bbolt.(*Bucket).ForEach(0x400204a300, 0x40020444e0, 0x40007068a8, 0x
Jul 10 22:35:32  lnd[11017]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/bucket.go:390 +0x
Jul 10 22:35:32  lnd[11017]: github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).ForEach(0x400204a300, 0x40
Jul 10 22:35:32  lnd[11017]:         github.com/btcsuite/btcwallet/walletdb@v1.3.5/bdb/db.go:190 +0x30
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView.func1(0x1
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/channeldb/graph.go:3355 +0x188
Jul 10 22:35:32  lnd[11017]: github.com/btcsuite/btcwallet/walletdb.View(0x126a568, 0x4000164480, 0x4001bb33
Jul 10 22:35:32  lnd[11017]:         github.com/btcsuite/btcwallet/walletdb@v1.3.5/interface.go:239 +0x98
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/channeldb.(*DB).View(0x4000164480, 0x4001bb3370
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/channeldb/db.go:244 +0xb4
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/kvdb.View(0x126a568, 0x4000164480, 0x4001bb3370
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/kvdb@v1.0.0/interface.go:34 +0x68
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView(0x400002a
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/channeldb/graph.go:3335 +0xd0
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start(0x4000114aa0, 0x
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/routing/router.go:548 +0x5e0
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd.(*server).Start.func1()
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/server.go:1633 +0xd04
Jul 10 22:35:32  lnd[11017]: sync.(*Once).doSlow(0x40004b8288, 0x4000706f88)
Jul 10 22:35:32  lnd[11017]:         sync/once.go:68 +0x11c
Jul 10 22:35:32  lnd[11017]: sync.(*Once).Do(...)
Jul 10 22:35:32  lnd[11017]:         sync/once.go:59
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd.(*server).Start(0x40004b8280, 0xfa2015, 0x2e)
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/server.go:1498 +0xc0
Jul 10 22:35:32  lnd[11017]: github.com/lightningnetwork/lnd.Main(0x400040e500, 0x0, 0x0, 0x0, 0x0, 0x400008
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/lnd.go:992 +0x1d08
Jul 10 22:35:32  lnd[11017]: main.main()
Jul 10 22:35:32  lnd[11017]:         github.com/lightningnetwork/lnd/cmd/lnd/main.go:36 +0x198
Jul 10 22:35:32  systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 10 22:35:32  systemd[1]: lnd.service: Failed with result 'exit-code'.

**Comment by guggero** [comment]
Sounds like either an issue with the `channel.db` file becoming too large for a 32bit Raspberry Pi or data corruption.
Try upgrading to the latest RaspiBlitz release which upgrades to 64bit software. And also add `db.bolt.auto-compact=true` to your config file.
If that doesn't fix it, you probably suffered data corruption and might need to recover your funds using SCB: https://docs.lightning.engineering/lightning-network-tools/lnd/recovery

**Comment by zanderisrael** [comment]
> Sounds like either an issue with the `channel.db` file becoming too large for a 32bit Raspberry Pi or data corruption.
> Try upgrading to the latest RaspiBlitz release which upgrades to 64bit software. And also add `db.bolt.auto-compact=true` to your config file.
> If that doesn't fix it, you probably suffered data corruption and might need to recover your funds using SCB: https://docs.lightning.engineering/lightning-network-tools/lnd/recovery

thanks! it actually was the channel.db file that got corrupt,  I removed graph-* keys using the boltweb db viewer, and im back online :)
