### ISSUE TITLE
RPC feereport returns "no policy for outgoing channel" for closed channel

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#5505]
### Background

I am calling `    feereport = self.stub.FeeReport(ln.FeeReportRequest())`, which returns with `"{"created":"@1626024343.812097728","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"no policy for outgoing channel 726607861215526913 ","grpc_status":2}"`.

This channel has been closed for 20k+ blocks (it's not in `listchannels`, it's [only] in `closedchannels`). I _have_ run neutrino for a bit, when my bitcoind backend failed, which might be the root cause for this. @wpaulino 's remarks on #2911 sound relevant:

> Ah I see what happened then. After you restored from your seed, your channel was likely still open so it was gossiped to you, and since the new node still has the same node public key, we interpreted it as ours. There's no easy way of removing those however, so the best thing to do is modify the source code to ignore those errors with a continue rather than returning the error.

It was not a restore, but a switch back and forth from Neutrino backend, but it feels similar.

### Your environment

* version of `lnd`: 0.12.1-beta
* which operating system (`uname -a` on *Nix) 4.18.0-240.22.1.el8_3.x86_64
* version of `btcd`, `bitcoind`, or other backend: bitcoind bitcoin-0.21.1
* any other relevant environment details: nothing much I think. My RTL did break too.

### Steps to reproduce

Call feereport, get error

### Expected behaviour

Get feereport back :wink: 

### Actual behaviour

Error returned:

```
[ Lightning root@srv44 charge-lnd]# ./charge-lnd.py 
Traceback (most recent call last):
  File "./charge-lnd.py", line 112, in <module>
    success = main()
  File "./charge-lnd.py", line 25, in main
    lnd = Lnd(arguments.lnddir, arguments.grpc)
  File "/opt/dev/charge-lnd/lnd.py", line 33, in __init__
    self.feereport = self.get_feereport()
  File "/opt/dev/charge-lnd/lnd.py", line 53, in get_feereport
    feereport = self.stub.FeeReport(ln.FeeReportRequest())
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "no policy for outgoing channel 726607861215526913 "
        debug_error_string = "{"created":"@1626024343.812097728","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"no policy for outgoing channel 726607861215526913 ","grpc_status":2}"
>
```

**Comment by AbelLykens** [comment]
#5320 handled by @halseth sounds relevant too.

Can I abandonchannel for this one? Will that help? @wpaulino I think said this would not work (in that other case). (and I get `AbandonChannel RPC call only available in dev builds` but I might need to run a different LND binary if I get a confirmation that's secure :wink: ).

**Comment by wpaulino** [comment]
With v0.13.0 you should be able to override the dev binary constraint but providing the confirmation flag to `AbandonChannel` at both the RPC and lncli level.

**Comment by Roasbeef** [comment]
> It was not a restore, but a switch back and forth from Neutrino backend, but it feels similar.

This isn't safe to do.

**Comment by AbelLykens** [comment]
> With v0.13.0 you should be able to override the dev binary constraint but providing the confirmation flag to AbandonChannel at both the RPC and lncli level.

Thanks @wpaulino . Will update after rc's have been out for a bit.

Main question: Will abandonchannel help here? ;)

> This isn't safe to do.

Yeah I noticed @Roasbeef ... Cleaning up the mess now. Did not know this was unsafe :wink: .

**Comment by AbelLykens** [comment]
Related: https://github.com/guggero/chantools/issues/22

**Comment by AbelLykens** [comment]
@guggero's chantools update, allowing me to drop a single channel, fixed this for me.

For those reading this later: 
* I guess there is a problem in your channel DB
* This can be fixed. In my case the cause was changing backends.
* There is a bad channel in your graph, and lnd still thinks it belongs to you
* Download chantools, and use a command like this: `cp channel.dp{,.bak} && chantools dropchannelgraph --channeldb ./channel.db --single_channel 726607861215526913`

Thanks for help all.
