### ISSUE TITLE
LND peer stopped sending commitments, won't send *any* messages after sending revoke_and_ack

### ISSUE THREAD

**Issue by whitslack** [lightningnetwork/lnd#5506]
### Background

An LND peer got itself into a condition in which it would always stop communicating with my node after sending a `revoke_and_ack` message, right at the point when it should have sent a new signed commitment.

### Your environment

* version of C-Lightning: **0.10.0**
* which operating system: **Gentoo Linux x86_64**
* version of `bitcoind`: 0.21.0

### Peer's environment

* version of `lnd`: **0.12.1-beta**
* which operating system: **Umbrel 0.3.14**
* version of `btcd`, `bitcoind`, or other backend: **unknown**

### Steps to reproduce

I'm running C-Lightning 0.10.0. The peer is running LND 0.12.1-beta. Unfortunately, the peer's operator rebooted his Umbrel instance without exporting the LND log, so the logs from his side were lost. I have the logs from my side, which I will now use to paint a picture of what happened.

The following is all from the perspective of my node (the C-Lightning node), so where it says `peer_in`, those are messages received *from* the LND peer, and where it says `peer_out`, those are messages sent *to* the LND peer.

The connection was humming along just fine. Several HTLCs in succession had been added and removed; some were fulfilled, and some had failed. The connection was lost and reestablished cleanly, at which time there were no outstanding HTLCs in the channel. About a minute after reconnection, there was an incoming routed payment that wanted to be forwarded over the channel.

```
NEW:: HTLC LOCAL 1540 = SENT_ADD_HTLC/RCVD_ADD_HTLC
Adding HTLC 1540 amount=738655msat cltv=690679 gave CHANNEL_ERR_ADD_OK
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
peer_in WIRE_REVOKE_AND_ACK
```

At this point, the next step in the protocol should have been for the LND peer to send a new commitment, but it never did.

About 18 minutes later, another incoming routed payment requested to be forwarded over the channel.

```
NEW:: HTLC LOCAL 1541 = SENT_ADD_HTLC/RCVD_ADD_HTLC
Adding HTLC 1541 amount=315667351msat cltv=690971 gave CHANNEL_ERR_ADD_OK
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
```

This time, no `revoke_and_ack` message was received from the LND peer. Indeed, *no* further messages were received from the peer in that connection, which my node eventually killed.

Three seconds after my node killed the connection, the LND peer reconnected and completed the `channel_reestablish` handshake. Since my node had sent an `update_add_htlc` message (for HTLC 1541) that was never acknowledged, it dutifully restarted that exchange.

```
Connect IN
peer_out WIRE_INIT
peer_in WIRE_INIT
peer_out WIRE_CHANNEL_REESTABLISH
peer_in WIRE_CHANNEL_REESTABLISH
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
peer_out WIRE_ANNOUNCEMENT_SIGNATURES
peer_in WIRE_REVOKE_AND_ACK
```

So now the LND peer did acknowledge my node's new commitment at least, but it still didn't send a new commitment of its own.

About 19 minutes later, another incoming payment requested to be forwarded over the channel with this LND peer.

```
NEW:: HTLC LOCAL 1542 = SENT_ADD_HTLC/RCVD_ADD_HTLC
Adding HTLC 1542 amount=50002152msat cltv=690638 gave CHANNEL_ERR_ADD_OK
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
```

So now, again, the LND peer is not acknowledging my new commitment or sending any messages at all.

After another 6 minutes, another incoming routed payment.

```
NEW:: HTLC LOCAL 1543 = SENT_ADD_HTLC/RCVD_ADD_HTLC
Adding HTLC 1543 amount=175000msat cltv=690584 gave CHANNEL_ERR_ADD_OK
peer_out WIRE_UPDATE_ADD_HTLC
```

This time, my node did not send a new commitment since its last commitment (for HTLC 1542) was still unacknowledged by the LND peer.

After 30 seconds, my node gave up and killed the connection.

```
Adding HTLC too slow: killing connection
Failing HTLC 1543 due to peer death
```

Yet again, within seconds of killing the connection, the LND peer reconnected inbound and completed the channel reestablishment handshake. And again, my node had sent an unacknowledged `add_htlc`, so it sent it again.

```
Connect IN
peer_out WIRE_INIT
peer_in WIRE_INIT
peer_out WIRE_CHANNEL_REESTABLISH
peer_in WIRE_CHANNEL_REESTABLISH
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
peer_out WIRE_ANNOUNCEMENT_SIGNATURES
peer_in WIRE_REVOKE_AND_ACK
```

Same as before: the LND peer acknowledged my node's new commitment but did not send one of its own and in fact went silent for the rest of this connection.

About a minute later, another incoming payment tried to route over this channel.

```
NEW:: HTLC LOCAL 1543 = SENT_ADD_HTLC/RCVD_ADD_HTLC
Adding HTLC 1543 amount=175000msat cltv=690584 gave CHANNEL_ERR_ADD_OK
peer_out WIRE_UPDATE_ADD_HTLC
peer_out WIRE_COMMITMENT_SIGNED
```

No response from the LND peer. Are you seeing the pattern?

This all happened once more, but I'll spare the log excerpts, as they're the same as before. Now the channel had reached five outstanding, acknowledged HTLCs, but the LND peer had not sent commitments for any of them.

Some time later, we get a clue that the LND peer has a corrupted notion of the channel state: it attempts to add its own HTLC to the channel (in a fresh connection) despite that the channel already has reached its maximum number of outstanding HTLCs.

```
Connect IN
peer_out WIRE_INIT
peer_in WIRE_INIT
peer_out WIRE_CHANNEL_REESTABLISH
peer_in WIRE_CHANNEL_REESTABLISH
peer_out WIRE_ANNOUNCEMENT_SIGNATURES
[after about 2 hours with no messages in either direction]
peer_in WIRE_UPDATE_ADD_HTLC
peer_out WIRE_WARNING
Peer transient failure in CHANNELD_NORMAL: channeld WARNING: Bad peer_add_htlc: CHANNEL_ERR_TOO_MANY_HTLCS
```

My node killed the connection after sending the warning, but the LND peer reconnected seconds later and attempted to add an HTLC again, which was again rejected due to exceeding the maximum number of outstanding HTLCs on the channel. The LND peer repeated this behavior several more times over the course of the next few hours, but it never sent any new commitment.

Eventually, the deadline for one of the outstanding HTLCs arrived, and my node was forced to unilaterally close the channel.

### Expected behaviour

LND should not abruptly stop sending any new commitments.

LND should not attempt to add new HTLCs to a channel after it has already acknowledged a number of outstanding HTLCs that reaches the channel peer's maximum limit.

### Actual behaviour

LND acknowledges one new HTLC per connection but never sends any new commitment nor any other message after the `revoke_and_ack`.

LND attempts to add a new HTLC to a channel even though it has already acknowledged a number of outstanding HTLCs equal to the channel peer's maximum limit on outstanding HTLCs.

**Comment by Crypt-iQ** [comment]
lnd 0.13.0 fixes some state machine bugs present in earlier versions, especially when restarting which would give it some bad state.  Additionally, 0.13.1 will include a fix for sending an HTLC when the max outstanding limit is reached.

**Comment by Crypt-iQ** [comment]
Given that 0.12.1 contained buggy state transitions on restart, I think this issue can be closed.  But if you experience this when connected to a (modern) 0.13.0 or greater node, please file another issue as that would be a bug.

**Comment by whitslack** [comment]
@Crypt-iQ: Thanks for the insights. I wish there were a way to fingerprint the software versions of the nodes that connect to mine so I could refuse to open channels with outdated, buggy versions. Maybe add that to the feature enhancements wishlist?
