### ISSUE TITLE
Windows 10 compilation error

### ISSUE THREAD

**Issue by ZekeLares** [lightningnetwork/lnd#551]
https://github.com/lightningnetwork/lnd/blob/2ddd13908447381412d376db5fd8372d6a2806bd/cmd/lncli/commands.go#L1449

I get the following error on this line:
\commands.go:1449:22: cannot use attrs (type gographviz.Attrs) as type map[string]string in argument to graphCanvas.AddNode

**Comment by halseth** [comment]
Similar issue+fix found by doing quick google search: https://github.com/nickng/dingo-hunter/issues/15

**Comment by Roasbeef** [comment]
You need to ensure that you've done `glide install` before attempting to install `lncli`.
