### ISSUE TITLE
RSA Key in release notes are out of date.

### ISSUE THREAD

**Issue by dipunm** [lightningnetwork/lnd#5511]
### Background

Release notes using an old RSA Key in verification instructions.

### Your environment

Not relevant.

### Steps to reproduce

```
gpg --verify manifest-roasbeef-v0.13.0-beta.sig manifest-v0.13.0-beta.txt`
```
### Expected behaviour

Output (based on release notes)
```
gpg: Signature made Wed Sep 30 17:35:20 2020 PDT
gpg:                using RSA key 4AB7F8DA6FAEBB3B70B1F903BC13F65E2DC84465
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [ultimate]
```

### Actual behaviour

Output:
```
gpg: Signature made Thu 17 Jun 2021 17:48:09 BST
gpg:                using RSA key 60A1FA7DA5BFF08BDCBBE7903BBD59E99B280306
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [unknown]
```

The key is different, but the signature is newer. Also, older releases have this newer key.

**Comment by Roasbeef** [comment]
Fixed! Looks like it was left over from the initial template our automated system puts up, thanks for pointing this out!

**Comment by dipunm** [comment]
@Roasbeef it happened again with 1.13.1-beta
Also, is bitconner's sig supposed to be there? raspiblitz's build_sdcard script seems to prefer his.
