### ISSUE TITLE
[bbolt] sync-freelist=false setting ignored

### ISSUE THREAD

**Issue by xanoni** [lightningnetwork/lnd#5519]
### Background

[bbolt] sync-freelist=false setting ignored

### Your environment

* lnd version 0.13.0-beta commit=v0.13.0-beta
* Linux 5.10.x, armhf
* bitcoind

### Steps to reproduce

```lnd.conf
[Application Options]
sync-freelist=false

[bolt]
db.bolt.nofreelistsync=true
```

### Expected behaviour

```
[INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
```

### Actual behaviour

```
[INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
```

**Comment by ErikEk** [comment]
I'll look into this.
