### ISSUE TITLE
[lncli] rpc error: code = Unknown desc = reserved wallet balance invalidated

### ISSUE THREAD

**Issue by xanoni** [lightningnetwork/lnd#5523]
### Background

Recurring issue ... I try to open a channel but get the feedback `[lncli] rpc error: code = Unknown desc = reserved wallet balance invalidated`. Restarting LND doesn't help. Moving the UTXO to Electrum and back doesn't help. Sweeping & consolidating the UTXOs in one new UTXO doesn't help. The UTXOs have enough confirmations. 

I've had this issue before with another UTXO and it resolved itself after a few days. Not sure why/how.

### Your environment

* lnd version 0.13.0-beta commit=v0.13.0-beta
* Linux armhf
* Bitcoin Core version v21.99.0

### Steps to reproduce

```
lncli openchannel --node_key <pubkey> --sat_per_vbyte 1 --local_amt <amount_lower_than_the_utxo> --connect <onion_address>
```

### Expected behaviour

Funding transaction sent to blockchain.

### Actual behaviour

```
[lncli] rpc error: code = Unknown desc = reserved wallet balance invalidated
```

**Comment by guggero** [comment]
Both nodes seem to be on version 0.13.x and will therefore try to open anchor output channels. For those channels you are required to have at least one sufficiently large UTXO in your wallet (on both sides, the funder and the channel receiver). You can either turn off anchor channels or open a channel to a node that has an UTXO.

**Comment by xanoni** [comment]
> one sufficiently large UTXO

How is "sufficiently large" defined? Just the desired size of the channel, or more?

Also, is this the expected/desired behavior? If yes, the error message could be tweaked.

**Comment by guggero** [comment]
Not sure exactly, I think 10k sats per channel, capped at 100k max if there are more than 10 channels.
Yes, I agree the error message could be better. But that is the expected behavior indeed. You need to be able to CPFP an anchor channel in case you need to force close it.

**Comment by xanoni** [comment]
Some empirical research:

I tried a few other nodes, but got the same error for all of them. Then I gradually reduced the channel size until it was 100154 sats below the UTXO size (using `--sat_per_vbyte=1`). Then it went through.

Thus, the number seems to be 100k.

**Comment by xanoni** [comment]
Just saw the tags, seems contributions are accepted. I will come up with a message that would have made sense to me and send a PR.

**Comment by xanoni** [comment]
https://github.com/lightningnetwork/lnd/pull/5577

@guggero does this work?

**Comment by Roasbeef** [comment]
Closing as https://github.com/lightningnetwork/lnd/pull/5577 was merged.
