### ISSUE TITLE
Validate invoice field lengths before parsing

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#553]
Currently, not all the lengths of the `BOLT-11` invoice fields are properly sanity checked before attempting to parse them: 

* Fallback address: https://github.com/lightningnetwork/lnd/blob/63517a1eef477cee84a8c9cab036af5a3bd3ee60/zpay32/invoice.go#L712 Could crash if the address field is empty.
* Routing info: https://github.com/lightningnetwork/lnd/blob/63517a1eef477cee84a8c9cab036af5a3bd3ee60/zpay32/invoice.go#L777 Crashes if length is not exactly what we anticipate (multiple of 51 bytes).

### Steps to completion:

- [ ] Create test cases triggering the crashes/failures.
- [ ] Properly validate the lengths, and return error if it does not match what we expect.

**Comment by valentinewallace** [comment]
New to LN, interested in taking this on! (can start Tuesday)
