### ISSUE TITLE
Silent error when creating a PSBT on lncli

### ISSUE THREAD

**Issue by LAMike310** [lightningnetwork/lnd#5531]
### Background

When trying to create a PSBT with a new node without any funds, the output is blank. I was a little confused until a friend in Slack told me to check the logs, which told me I didn't have sufficient funds. 

`wallet couldn't fund PSBT: error creating funding TX: insufficient funds available to construct transaction`

### Your environment

* version of `lnd`: 

_lncli version 0.12.1-beta commit=v0.12.1-beta_

* which operating system (`uname -a` on *Nix) : 

_Linux umbrel 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux_

* version of `btcd`, `bitcoind`, or other backend:

_Bitcoin Core RPC client version v0.21.1.0-g194b9b8792d9b0798fdb570b79fa51f1d1f5ebaf_

* any other relevant environment details

### Steps to reproduce

On a new node w/o any funds, run this command:

./lncli wallet psbt fund --outputs='{"bcrt1qjrdns4f5zwkv29ln86plqzs092yd5fg6nsz8re":50000000}' 

### Expected behaviour

An error explaining why there I can't create a PSTB on lncli w/o going to the logs

**Comment by ErikEk** [comment]
I'll take a look.

**Comment by ErikEk** [comment]
It works for me on mainnet with bitcoind. I get `[lncli] rpc error: code = Unknown desc = wallet couldn't fund PSBT: error creating funding TX: insufficient funds available to construct transaction`.

**Comment by LAMike310** [comment]
Yeah I think it might be a problem with Umbrel, a few other commands weren't working for me either.

https://github.com/getumbrel/umbrel/issues/876
