### ISSUE TITLE
Feature: RPC method to compute required wallet reserve

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#5540]
### Background

I'd like to report wallet reserve in the UI of my app so that the user is notified if he attempts to deposit less than the required amount. I can of course compute it myself but then I have to worry about the constants changing and updating the app with a new LND release. Having the algorithm exposed in form of RPC method would improve reliability.

### Proposed RPC method

Method name: `GetRequiredWalletReserve`
Input argument: `additionalPublicChannels: u32` - how many *additional* channels the caller would like to open
Output fields:
* `requiredReserve: BitcoinAmount` - the result, currently `min((currentPublicChannels + additionalPublicChannels) * 10000, 100000)`
* `walletBalance: BitcoinAmount` - a small optimization so that the caller doesn't have to make two RPC calls

### Alternatives

Stabilize the current algorithm (promise not to change it).

**Comment by mauricepoirrier** [comment]
Hi @guggero 👋🏼  I'll be working on this one. Would you mind any guidance?

**Comment by guggero** [comment]
Sure. The value we're interested in is this one: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L1049
And the calculation for the number of current anchor channels is in the method just above.

I think a good place for this would be the [`walletrpc`](https://github.com/lightningnetwork/lnd/tree/master/lnrpc/walletrpc) RPC. Take a look at https://github.com/lightningnetwork/lnd/tree/master/lnrpc#generate-protobuf-definitions to get started with protobufs.

**Comment by mauricepoirrier** [comment]
@guggero sorry the delay.
I was wondering if there is a way to expose the method for the current anchor channels to the wallet kit package? Or should I just re-implement the logic for the currentNumAnchorChans?

Thanks! first issue 😓

**Comment by guggero** [comment]
Hmm, good question. I think we probably need to change the [`Wallet` here](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/walletrpc/config_active.go#L47) from the generic `lnwallet.WalletController` interface to the specific `lnwallet.LightningWallet` struct and then export the `currentNumAnchorChans()` method.
It should already be set as the specific type [here](https://github.com/lightningnetwork/lnd/blob/master/subrpcserver_config.go#L165) anyway.
