### ISSUE TITLE
Unable to add tor v3 address as neutrino peer

### ISSUE THREAD

**Issue by lukaszsamson** [lightningnetwork/lnd#5548]
### Background

Unable to add tor v3 address as neutrino peer

### Your environment

* version of `lnd` 0.13.1
* which operating system (`uname -a` on *Nix) macos
* version of `btcd`, `bitcoind`, or other backend: neutrino

### Steps to reproduce

```
neutrino.addpeer=n35aod4iraixvkzd5pwvkkyld4zwkog7cyaxs6cqwovstg6a26idkgid.onion:8333
```

### Expected behaviour

It should accept v3 address as v2 is now deprecated

### Actual behaviour

It treats v3 address as v2 address
```
2021-07-21 00:07:41.056 [WRN] BTCN: unable to lookup IP for n35aod4iraixvkzd5pwvkkyld4zwkog7cyaxs6cqwovstg6a26idkgid.onion:8333: invalid onion v2 host: n35aod4iraixvkzd5pwvkkyld4zwkog7cyaxs6cqwovstg6a26idkgid.onion
```

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/issues/4973
