### ISSUE TITLE
Feature Request: Pending Peers

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#555]
Hi,

I have a problem trying to connect to a peer, but it's in pending state... Unfortunatly there are no endpoints to view status of pending peers, and posibly cancelling connection attempts etc

Richard

**Comment by halseth** [comment]
What do you mean by "pending state"?

**Comment by Richard87** [comment]
I get this error message:

```

~/Projects/pos on  master ➜ docker-compose exec lnd lncli connect 038b869a90060ca856ac80ec54c20acebca93df1869fbee9550efeb238b964558c@172.104.59.47:9735
[lncli] rpc error: code = Unknown desc = connection attempt to 038b869a90060ca856ac80ec54c20acebca93df1869fbee9550efeb238b964558c@172.104.59.47:9735 is pending
```

**Comment by Richard87** [comment]
It would be nice to be able to specify a timeout when connecting, f.eks 15 / 60 / 3600 seconds...

Btw, if I try to delete the connection, this happens:
```
~/Projects/pos on  master ➜ docker-compose exec lnd lncli disconnect 038b869a90060ca856ac80ec54c20acebca93df1869fbee9550efeb238b964558c                   
[lncli] rpc error: code = Unknown desc = unable to disconnect peer: unable to find peer 038b869a90060ca856ac80ec54c20acebca93df1869fbee9550efeb238b964558c
```

**Comment by tomichec** [comment]
I have experienced it too.

**Comment by Lldenaurois** [comment]
Bonjour gents. May I take this one? I'll try to reproduce this error and see what's going on

**Comment by danielemiliogarcia** [comment]
i would like this one too! grpc listPendingPeers
