### ISSUE TITLE
[ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: insufficient local balance log line does not provide useful information.

### ISSUE THREAD

**Issue by BhaagBoseDK** [lightningnetwork/lnd#5556]
### Background

lnd.log prints this log line when queryrote fails
[ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: insufficient local balance

However there is no other information related to "what was the route" "what was the balance requested" "which channel failed" etc.

### Your environment

* version of `lnd` 
> 0.12.1-beta commit=v0.12.1-beta

* which operating system (`uname -a` on *Nix) 
> Linux umbrel 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux

### Steps to reproduce

Whenever query route fails this line is printed in lnd.log

### Expected behaviour

The log line should provide channel, balance, and other useful information to investigate further.

### Actual behaviour

The log line only prints a message without any related information for further investigation.

**Comment by Roasbeef** [comment]
> insufficient local balance

This means w/e route _you_ attempted to execute, doesn't have enough outbound balance. So it would be the very first channel the user selected in the route.

**Comment by BhaagBoseDK** [comment]
but if you are looking at the logs for the routes passing via your node, you would have no idea which channel the sending node selected. A log message should have some meaningful information.
