### ISSUE TITLE
difference between cancelled invoice and deleted invoice?

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#5558]
### Background

An invoice can be cancelled, either using the [cancelHodlInvoice](https://github.com/alexbosworth/ln-service#cancelhodlinvoice) or because an invoice has expired

After trying to fetch the invoice with getInvoice, sometimes it will return an object with `{ is_cancelled: true }`, sometime it will trigger an error with `(err[2].err.details === "unable to locate invoice")`

I'm trying to make sense of why that is and in what case the invoice is no longer present in the database, and in which case the invoice is present but cancelled?

### Your environment

* version of `lnd`: 0.12.1
* version of `btcd`, `bitcoind`, or other backend: bitcoind

@alexbosworth @dolcalmi

**Comment by alexbosworth** [comment]
Probably if you are using the new prune canceled invoices flag then you will have invoices removed from the database on startup or on the fly depending on your configuration, and in that case it will appear as never existing when the prune job happens?

**Comment by nicolasburtey** [comment]
> Probably if you are using the new prune canceled invoices flag then you will have invoices removed from the database on startup or on the fly depending on your configuration, and in that case it will appear as never existing when the prune job happens?

yes this seems to be the case, but I have not been able to clearly understand the pattern here. it seems sometime the invoice is still being returned as `{ is_cancelled: true }` even with invoice pruned on the fly. I guess I may need to do more systematic testing to try to understand this

**Comment by nicolasburtey** [comment]
ok did some tests, and actually there is no more `{ is_cancelled: true }` if `gc-canceled-invoices-on-the-fly=true` is being used. I guess the mix may have being the the `gc-canceled-invoices-on-startup=true` only being activated.
