### ISSUE TITLE
"synced_to_chain": false when bitcoind and lnd are both at the most recent block

### ISSUE THREAD

**Issue by raymondclowe** [lightningnetwork/lnd#5566]
### Background

lnd says it is not synced after bitcoind gets the next block, even though lnd reports it has reached the same block height as bitcoind.

### Your environment

* version of `lnd`: lnd version 0.13.1-beta commit=v0.13.1-beta
* which operating system (`uname -a` on *Nix): Linux [redacted] 5.10.17-v7l+ [hash]1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v0.21.1
* any other relevant environment details

### Steps to reproduce

Start bitcoind
Start lnd

Wait a few moments for lnd to finish starting

At this point `    "synced_to_chain": true `

Wait for several minutes for a new block then check again

```
lncli getinfo
{
    "version": "0.13.1-beta commit=v0.13.1-beta",
    "commit_hash": "596fd90ef310cd7abbf2251edaae9ba4d5f8a689",
    "identity_pubkey": "02b6008aa463ab2eb16e533a74f8d29ef22429f458fff292b8bea50e6be5e5c4dc",
    "alias": "bluebean",
    "color": "#76f9ec",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 0,
    "num_peers": 6,
    "block_height": 692360,
    "block_hash": "00000000000000000012d3e4d31541b4eee3b5923ae68a2d046681d81640a075",
    "best_header_timestamp": "1627084819",
    "synced_to_chain": false,
    "synced_to_graph": false,
    "testnet": false,
```

```
bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 692360,
  "headers": 692360,
  "bestblockhash": "00000000000000000012d3e4d31541b4eee3b5923ae68a2d046681d81640a075",
  "difficulty": 13672594272814.14,
  "mediantime": 1627079409,
  "verificationprogress": 0.9999966648352485,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000001fc3894994ecde1939725cf8",
  "size_on_disk": 1921945361,
  "pruned": true,
  "pruneheight": 690692,
  "automatic_pruning": true,
  "prune_target_size": 2000683008,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },

```

### Expected behaviour

I would have thought it would say true as it seems lnd has caught up with the new block.  

### Actual behaviour

If I restart lnd then it says true, but then after a few minutes it switches to false and stays that way until I restart lnd.

**Comment by Roasbeef** [comment]
See this issue where we're aggregating reports: https://github.com/lightningnetwork/lnd/issues/5132 

Would be useful if you have logs of where things flip to "false", and if you see reports of "out of order" blocks in the logs or not. Also check that your `bitcoind` is configured properly: https://github.com/lightningnetwork/lnd/issues/5132
