### ISSUE TITLE
Cannot send through new channel because FAILURE_REASON_INSUFFICIENT_BALANCE

### ISSUE THREAD

**Issue by raymondclowe** [lightningnetwork/lnd#5568]
### Background

This looks similar to https://github.com/lightningnetwork/lnd/issues/5468 . Not sure if it is same or different but my case doesn't have ""min_htlc_msat": "0"," which was identified as the cause there.

I have opened a new channel to a new peer I have not done connection with before.  Soon after the channel is established the owner of the remote channel sends me an invoice for a sample amount, 10sats, and I try to pay it but get FAILURE_REASON_INSUFFICIENT_BALANCE.

Everything looks as though there is a local balance on that channel and it is active.

I have channel to other node that works fine and doesn't show this behavior.

The same problem has appeared in other channels from my node in the past and I've just given up on them, closed them, and tried again with a different node.

This time I was very meticulous and worked with the owner of the remote node in an attempt to be sure I wasn't just confused.

### Your environment

* version of `lnd`: lnd version 0.13.1-beta commit=v0.13.1-beta
* which operating system (`uname -a` on *Nix): Linux [redacted] 5.10.17-v7l+ [hash]1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v0.21.1

### Steps to reproduce

Channel has been opened and shows in list of channels:

```
lncli listchannels
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "033b4b17a264d3a476632224929ec5c7a037b0d2e7daf33a3709aed2177a89976a",
            "channel_point": "432ce4b0659806c382e10ea7f177a2f6e1c066fb4159bd42fe86ebdf33790d65:0",
            "chan_id": "761499763243089920",
            "capacity": "20000",
            "local_balance": "19618",
            "remote_balance": "0",
            "commit_fee": "382",
            "commit_weight": "600",
            "fee_per_kw": "529",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "573",
            "remote_chan_reserve_sat": "573",
            "static_remote_key": true,
            "commitment_type": "STATIC_REMOTE_KEY",
            "lifetime": "7806",
            "uptime": "7769",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "573",
                "dust_limit_sat": "573",
                "max_pending_amt_msat": "19800000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "remote_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "573",
                "dust_limit_sat": "573",
                "max_pending_amt_msat": "19800000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            }
        },

......
```

I have a balance:

```
lncli channelbalance
{
    "balance": "47969",
    "pending_open_balance": "0",
    "local_balance": {
        "sat": "47969",
        "msat": "47969704"
    },
    "remote_balance": {
        "sat": "10010",
        "msat": "10010296"
    },
    "unsettled_local_balance": {
        "sat": "0",
        "msat": "0"
    },
    "unsettled_remote_balance": {
        "sat": "0",
        "msat": "0"
    },
    "pending_open_local_balance": {
        "sat": "0",
        "msat": "0"
    },
    "pending_open_remote_balance": {
        "sat": "0",
        "msat": "0"
    }
}

```

I try to pay a test invoice of 10 sats sent from the node I'm connected to:

`lncli sendpayment --pay_req lnbc100n1ps06s84pp5fqm3yfuv2a5y99yjdg0pqnf3x2y97ddndmrtm8w3lnpyte58xpwsdqqcqzpgxqr23ssp5nk86mefrletc9ae2rpflyg7ldrtwgjt0nlu3ve0rnzpxxu03sqaq9qyyssqmlg2nxslw5tt9knuc3v9nmha2gjpw6rmlppfjwxsn33ugcju7cgypf6dnpeqcfjy7md2usj4gftzx6jfxc363rsw3nf3lmp7ksxv4sqqfufwzl --outgoing_chan_id 761499763243089920
`

### Expected behaviour

It should pay

### Actual behaviour

```
Payment hash: 483712278c57684294926a1e104d3132885f35b36ec6bd9dd1fcc245e687305d
Description:
Amount (in satoshis): 10
Fee limit (in satoshis): 10
Destination: 033b4b17a264d3a476632224929ec5c7a037b0d2e7daf33a3709aed2177a89976a
Confirm payment (yes/no): yes
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
| HTLC_STATE | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE | TIMELOCK | CHAN_OUT | ROUTE |
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
Amount + fee:   0 + 0 sat
Payment hash:   483712278c57684294926a1e104d3132885f35b36ec6bd9dd1fcc245e687305d
Payment status: FAILED, reason: FAILURE_REASON_INSUFFICIENT_BALANCE
[lncli] FAILED
```

The lnd log at the time I try the payment looks like this:

```

Jul 25 21:00:18 fridge lnd[21486]: 2021-07-25 21:00:18.897 [ERR] NANN: Unable to retrieve chan status for Channel(432ce4b0659806c382e10ea7f177a2f6e1c066fb4159bd42fe86ebdf33790d65:0): edge not found
Jul 25 21:00:19 fridge lnd[21486]: 2021-07-25 21:00:19.844 [WRN] CRTR: Failed to find route for payment 483712278c57684294926a1e104d3132885f35b36ec6bd9dd1fcc245e687305d: insufficient local balance
Jul 25 21:00:19 fridge lnd[21486]: 2021-07-25 21:00:19.988 [ERR] CRTR: Payment 483712278c57684294926a1e104d3132885f35b36ec6bd9dd1fcc245e687305d failed: insufficient_balance
```

Trying to get info on the channel also doesn't work:

```
lncli getchaninfo 761499763243089920
[lncli] rpc error: code = Unknown desc = edge not found
```

If I look for it in the list of peers `lncli listpeers` then I can see:

```
...

        {
            "pub_key": "033b4b17a264d3a476632224929ec5c7a037b0d2e7daf33a3709aed2177a89976a",
            "address": "18.141.118.207:46678",
            "bytes_sent": "4457",
            "bytes_recv": "487894",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "41468",
            "sync_type": "PASSIVE_SYNC",
            "features": {
                "0": {
                    "name": "data-loss-protect",
                    "is_required": true,
                    "is_known": true
                },
                "5": {
                    "name": "upfront-shutdown-script",
                    "is_required": false,
                    "is_known": true
                },
                "7": {
                    "name": "gossip-queries",
                    "is_required": false,
                    "is_known": true
                },
                "9": {
                    "name": "tlv-onion",
                    "is_required": false,
                    "is_known": true
                },
                "12": {
                    "name": "static-remote-key",
                    "is_required": true,
                    "is_known": true
                },
                "14": {
                    "name": "payment-addr",
                    "is_required": true,
                    "is_known": true
                },
                "17": {
                    "name": "multi-path-payments",
                    "is_required": false,
                    "is_known": true
                }
            },
            "errors": [
                {
                    "timestamp": "1627209134",
                    "error": "disconnecting 033b4b17a264d3a476632224929ec5c7a037b0d2e7daf33a3709aed2177a89976a@18.141.118.207:9735, reason: read handler closed"
                }
            ],
            "flap_count": 5,
            "last_flap_ns": "1627209170636766064"
        },

...
```

The remote end of this channel is using lnd version 0.12.1-beta

**Comment by Roasbeef** [comment]
Similar to the other issue you've opened, it appears you're having connectivity issues, baed on how frequenrtly your connect peer is flapping (connecting, then disconnecting). If you don't know of that edge at all (which is very odd), then it makes sense that path finding isn't able to route outbound, if it doesn't actually know of that edge. 

If you restart and/or try to reconnect to that peer, do you eventually get the channel announcement? Also assuming that the rest of the network knows about the channel, then your node should _eventually_ query again for that channel as we essentially spot check our view of teh graph with the peers we're connected with periodically.

**Comment by raymondclowe** [comment]
What fixed this was removing tor / proxy.

I understand this is a network issue and don't expect lnd to magically fix that.

My only thought is that an error message indicating that the problem was a connectivity issue would save a lot of troubleshooting effort. The "insufficient balance" was quite a red herring.

**Comment by Roasbeef** [comment]
> What fixed this was removing tor / proxy.

Nice! 

> My only thought is that an error message indicating that the problem was a connectivity issue would save a lot of troubleshooting effort. The "insufficient balance" was quite a red herring.

Yeah that would be ideal, but from lnd's PoV, it just knows that it can't reach the node, that may be due to a networking issue, or it just being offline all together.
