### ISSUE TITLE
Recovery of funds from force closed channel

### ISSUE THREAD

**Issue by michaelg-au** [lightningnetwork/lnd#5571]
Background

My previous lightning node was established in around Feb 2020. In May 2020, I managed to delete the hard drive and SD card concurrently (don’t ask… 😊). I had been manually downloading the SCB backup on an ad hoc basis.

It was a 2BTC node with 101 channels. 99 channels were SCB backed-up. I successfully utilized the SCB backup to trigger the data loss protection/force closes on 98 channels in the week or two following the deletion – so was quite happy at the time.
A year later, about a week ago, I thought I’d have a go at restoring the last (SCB backed-up) channel which I couldn’t close previously. Fired up the node, ran the recovery commands and surprise – the final channel force closed and I recovered those funds.

Feeling confident, I started thinking about the two channels that weren’t covered by the SCB backup. One of them already closed previously. With a very small balance, not sure exactly what happened and not overly worried. The final channel is more significant – 5m Sats.

It was with a relatively significant player (CoinPayments). Reached out to them and asked if they could force close. They did that immediately, which was nice. I was hoping that the funds would appear in my restored on-chain wallet… but no luck. I looked at the Guggero chantools github instructions and given step 11, I felt hopeful that the funds would appear given I was using at least v0.8. I also looked at the article: "Did you lose funds on the Lightning Network because of a disk crash? Here’s a way you might get them back. | by Oliver Gugger | Medium."

Based on this article, I felt that perhaps I should have followed the steps here with the ‘fakechanbackup’ to try to retrieve the commit point (prior to requesting the force close with the other party).

Now that I’m here, I’m thinking that I need that commit point to be able to somehow access the funds on-chain. Just wondering if anyone could help me with that? Or – perhaps I’m looking at the problem from the wrong angle and there is some other way to approach.

**Comment by guggero** [comment]
It sounds like the channel in question was opened with an `lnd` version later than 0.6.x which would mean the channels were already of the newer type `STATIC_REMOTE_KEY`.
If that really is the case then you should be able to use the `chantools genimportscript --lndpaths` to get the private key for the force closed channel. Just store the output of that command into a text file, then search it for the address on which your force-closed funds currently reside on. If you find the address in the file, you also have the private key there.

If it was an older channel, then you indeed need to get the `per_commit_point` from the other node. That is a bit more involved but should be possible if the other node is still around.

**Comment by michaelg-au** [comment]
Thanks Guggero! I now have a private key for the relevant channel close transaction. I've never imported a private key to a wallet before - so that is my next step. I'm setting up a new Bitcoin instance on my desktop and will then _importprivkey_. Quietly confident at this stage.
