### ISSUE TITLE
gRPC - should be PendingChannelsRequest but there is PendingChannelRequest 

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#558]
Incorrect request (PendingChannelRequest) and response (PendingChannelResponse) names.

**Comment by Roasbeef** [comment]
Thanks for the report! You're totally right, the naming scheme should be consistent across all RPC's.

**Comment by Roasbeef** [comment]
Closed by https://github.com/lightningnetwork/lnd/commit/742158434171ccea1ac05398c2b69d2d4dc4453b
