### ISSUE TITLE
Channel stuck in "waiting close"

### ISSUE THREAD

**Issue by Bitcarnicoin** [lightningnetwork/lnd#5583]
### Background

I initiated a channel close on Umbrel 2 weeks ago but it remains stuck in "waiting close." If I select "view info" on the channel in RTL (Ride The Lightning), I can see a closing Transaction ID but it is not in the mempool. 

I have tried restarting my node to re-broadcast the transaction but without success. I see no way to force close the channel in RTL or Umbrel dashboard.

Not sure what info would be helpful to debug, happy to provide.

### Your environment

Latest Umbrel 0.3.14, Raspberry Pi

### Steps to reproduce

Select channel in Umbrel, hit "close channel"

### Expected behaviour

Expected channel to close.

### Actual behaviour

Stuck in "pending" "waiting close"

**Comment by guggero** [comment]
You need to force close the channel, probably through the command line. Though I think RTL should also offer that as an action in the UI, but I can be mistaken.

**Comment by Bitcarnicoin** [comment]
> You need to force close the channel, probably through the command line. Though I think RTL should also offer that as an action in the UI, but I can be mistaken.

Can't see it anywhere in RTL as an action. How do I run commands on Umbrel? There's no operating system installed besides that.

**Comment by guggero** [comment]
I'm sure the Umbrel support can help you with that. This is what I found with google: https://community.getumbrel.com/t/help-recovering-lightning-channel-linux/993

**Comment by Bitcarnicoin** [comment]
> I'm sure the Umbrel support can help you with that. This is what I found with google: https://community.getumbrel.com/t/help-recovering-lightning-channel-linux/993

So I have been able to connect via command line through my PC using: C:\WINDOWS\system32>ssh umbrel@umbrel.local

Tried running a channel close command ~/umbrel/bin/lncli close id=${CHANNEL_ID_HERE} force=true timeout=0 but can't get it to execute . Any ideas?

**Comment by guggero** [comment]
That command doesn't seem to be correct. It should look something like `~/umbrel/bin/lncli closechannel --force ${CHANNEL_FUNDING_TXID} ${CHANNEL_FUNDING_OUTPUT_INDEX}`

**Comment by Bitcarnicoin** [comment]
Sorry can't get that to execute. This is what I see when I output pending channels. Can figure out what's wrong?

umbrel@umbrel:~ $ ~/umbrel/bin/lncli pendingchannels
{
    "total_limbo_balance": "998398",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03d607f3e69fd032524a867b288216bfab263b6eaee4e07783799a6fe69bb84fac",
                "channel_point": "b637a085cd919d61d4108cc3b527c9d7417537d65094a9ad18cdb41926643c72:0",
                "capacity": "1000000",
                "local_balance": "998398",
                "remote_balance": "0",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "998398",
            "commitments": {
                "local_txid": "c7f4fcade56defc4d8e5b912fc904e0b623963e99dd3c3f9ede7b7fa18d7764e",
                "remote_txid": "c2f0bfe1860d73ceef55e3dcc8a94905ff2def88bddeec9ea9fc090a82deb0d3",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "1602",
                "remote_commit_fee_sat": "1602",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}
umbrel@umbrel:~ $

**Comment by Bitcarnicoin** [comment]
Finally figured out the syntax:

umbrel@umbrel:~ $ ~/umbrel/bin/lncli closechannel --force **.........................**  //(channel point with a space instead of ":" )

Transaction was re-broadcast and confirmed. "blocks_til_maturity": 143 so presumably have to wait for these to clear before funds are returned.

Thanks for your help.
