### ISSUE TITLE
I could pay the same invoice twice

### ISSUE THREAD

**Issue by camalolo** [lightningnetwork/lnd#560]
Hello,

I tried to pay the same invoice twice and it worked.

I would have expected an error the second time ?

```
> lncli payinvoice lntb30u1pdymftapp5s2yc267p3f38vh54q49qtc2nal4lxt4neywh8w5p84803m5qqceqdz80v3xjg36yfjkgefjv4jrzvpdxvmnye3dx33kvcfdvymnqefdvgenvetpx5ursvmpxvujylgcqzysqvl5y9shyzm2hq8gwuvtvlkhgzsyvwakpmjk89w5zkqh4j6hsvspu0w87qh42tpc4hkv636dnewrhra5nq66gxarrg6t0kjr446x9lqplmsx47
{
	"payment_error": "",
	"payment_preimage": "a2d89014688e038eeab9a1951a9d3f9627af244530e81a1cce3997600930260f",
	"payment_route": {
		"total_time_lock": 1257514,
		"total_amt": 3000,
		"hops": [
			{
				"chan_id": 1382342302329339905,
				"chan_capacity": 16677216,
				"amt_to_forward": 3000,
				"expiry": 1257514
			}
		]
	}
}

> lncli payinvoice lntb30u1pdymftapp5s2yc267p3f38vh54q49qtc2nal4lxt4neywh8w5p84803m5qqceqdz80v3xjg36yfjkgefjv4jrzvpdxvmnye3dx33kvcfdvymnqefdvgenvetpx5ursvmpxvujylgcqzysqvl5y9shyzm2hq8gwuvtvlkhgzsyvwakpmjk89w5zkqh4j6hsvspu0w87qh42tpc4hkv636dnewrhra5nq66gxarrg6t0kjr446x9lqplmsx47
{
	"payment_error": "",
	"payment_preimage": "a2d89014688e038eeab9a1951a9d3f9627af244530e81a1cce3997600930260f",
	"payment_route": {
		"total_time_lock": 1257514,
		"total_amt": 3000,
		"hops": [
			{
				"chan_id": 1382342302329339905,
				"chan_capacity": 16677216,
				"amt_to_forward": 3000,
				"expiry": 1257514
			}
		]
	}
}

> lncli listpayments
{
    "payments": [
        {
            "payment_hash": "8289856bc18a62765e95054a05e153efebf32eb3c91d73ba813d4ef8ee800632",
            "value": "3000",
            "creation_date": "1515038088",
            "path": [
                "03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2"
            ],
            "fee": "0"
        },
        {
            "payment_hash": "8289856bc18a62765e95054a05e153efebf32eb3c91d73ba813d4ef8ee800632",
            "value": "3000",
            "creation_date": "1515038133",
            "path": [
                "03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2"
            ],
            "fee": "0"
        }
    ]
}
```

Cheers

**Comment by camalolo** [comment]
Additional remark : the channel between my node and the payee indeed shows the payment was sent twice (I made a first one of 1500 sat then paid the same 3000 sat invoice twice). Here is the entry of HTLC.me lnd node in my lncli listpeers :

        {
            "pub_key": "03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2",
            "peer_id": 8,
            "address": "45.63.87.131:9735",
            "bytes_sent": "1004429",
            "bytes_recv": "1518834",
            "sat_sent": "7500",
            "sat_recv": "7933",
            "inbound": true,
            "ping_time": "2502"
        }

So for all I know I really send the same payment twice. In my humble opinion this should never be allowed ? Or is my application responsible for not sending a payment that was already sent before ?

**Comment by Roasbeef** [comment]
`sat_sent` and `sat_recv` show _all_ payments that have gone through your node. Not only those that have _originated_ from your node.

**Comment by camalolo** [comment]
My apologies Roasbeef, I think my second remark might have made my original question unclear.

My problem was that I could pay the same invoice twice. I ran the lncli payinvoice <payment_id> command twice with the same payment id, and it worked twice, and the payment shows up twice in lncli listpayments. Is that by design ? Shouldn't the payment request be rejected the second time ?

Thanks for your time !

**Comment by halseth** [comment]
@camalolo You are right that it should be rejected, it was fixed in https://github.com/lightningnetwork/lnd/commit/e2fe4c295530634cfb2ba0a5c48c7d21ae60bfea

**Comment by camalolo** [comment]
@halseth Great ! Thanks !
