### ISSUE TITLE
AddHoldInvoice is not working

### ISSUE THREAD

**Issue by RobinBlaesing** [lightningnetwork/lnd#5600]
### Background

I would like to create a hold invoice with `AddHoldInvoice` but it neither works with lncli nor javascript grpc. Other interactions with lncli and grpc work, like creating normal invoices by `addInvoice` and sending payments to other nodes using `sendPaymentV2`.

### My environment

LND version: v0.12.1-beta
Operating system: Ubuntu
Bitcoind: v0.21.0

I am on regtest using this lnd.conf:
```
[Application Options]
listen=0.0.0.0:10011
rpclisten=localhost:10001
restlisten=0.0.0.0:8001
debuglevel=ATPL=debug,CRTR=warn,LNWL=critical
[autopilot]
autopilot.active=1
[Bitcoin]
bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpchost=localhost
bitcoind.rpcuser=Y
bitcoind.rpcpass=XXX
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
```

#### lncli
`lncli addholdinvoice 05189e0a237e2177859d6bbed49dcce729aa7dcce83f2f10e8972717a077cfb8` 

#### grpc
I downloaded 'invoices.proto' and other proto files from [https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/invoices.proto](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/invoices.proto) into my working directory and included it by 

```javascript
const loaderOptions = {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
};
const packageDefinition = protoLoader.loadSync(['router.proto', 'lightning.proto', 'invoices.proto', 'signer.proto', 'lncli.proto', 'autopilot.proto', 'verrpc.proto'], loaderOptions);
const invoicesrpc = grpc.loadPackageDefinition(packageDefinition).invoicesrpc;

let invoicesrpc = new invoicesrpc.Invoices('localhost:10001', creds);
invoicesrpc.AddHoldInvoice(request, function(err, response) {
  console.log(response);
  console.log(err);
});
```

#### lncli
Should return something.

#### grpc
According to [https://api.lightning.community/?javascript#addholdinvoice](https://api.lightning.community/?javascript#addholdinvoice) `invoicesrpc.AddHoldInvoice` should return 
```
// Console output:
//  { 
//      "payment_request": <string>,
//      "add_index": <uint64>,
//      "payment_addr": <bytes>,
//  }
```

#### lncli 
Returns `No help topic for 'addholdinvoice'`. Then also `lncli1 lookupinvoice 05189e0a237e2177859d6bbed49dcce729aa7dcce83f2f10e8972717a077cfb8`returns `[lncli] rpc error: code = Unknown desc = unable to locate invoice` (although I am not certain to use lookupinvoice correctly here).

#### grpc
Returns
```
Error: 12 UNIMPLEMENTED: unknown service invoicesrpc.Invoices
    at Object.exports.createStatusError (/home/rob/app-container/js/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'unknown service invoicesrpc.Invoices'
}
```

**Comment by carlaKC** [comment]
> Error: 12 UNIMPLEMENTED: unknown service invoicesrpc.Invoices

The `AddHoldInvoice` call is part of the invoices rpc server, which you need to build with the `invoicerpc` tag. Looks like you built lnd without it?

I'd suggest using `make release-install`, which will include all of the rpc servers that we include in our release binaries.

**Comment by RobinBlaesing** [comment]
**Thanks! That has solved it!**

lncli returns `pay_req` now.

Only remaining issue is with grpc: There is no hash function utility in LND for creating the `hash` for a request. Hence, I am using `crypto` but there seems to be a problem with the length of the hash.

My code for building the request

```javascript
const crypto = require('crypto');
const secret = crypto.randomBytes(32);
console.log('secrect: ' + secret.toString('hex'));
const hash = crypto.createHash('sha256').update(secret).digest('hex');
console.log('hash: ' + hash);

let request = {
  memo: "test",
  hash: hash,
  value: 500000,
  expiry: 3600
};
invoicesrpc1.AddHoldInvoice(request, function(err, response) {
  console.log(response);
  console.log(err);
});
```
returns
```
secrect: daf06a908ff4b6696c840f36191d137b46c4913a55e2fbbf78e839aeb6d70b30
hash: 67646d5c0a0b387cc2ee0f8423ca30968ec46a2b17d41de87b5c993700854f9d
undefined
Error: 2 UNKNOWN: invalid hash length of 48, want 32
    at Object.exports.createStatusError (/home/rob/app-container/js/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/rob/app-container/js/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'invalid hash length of 48, want 32'
}
```
Any idea?

**Comment by guggero** [comment]
I think the `hash` field in the request needs to be the raw bytes (so a `Buffer`), not the hex string. Try using `.digest()` without any params. You can still use `hash.toString('hex')` for the log statement.

Closing for now as this was a build tag issue. Feel free to comment further if you have more questions about how to use the API.

**Comment by RobinBlaesing** [comment]
> 
> 
> I think the `hash` field in the request needs to be the raw bytes (so a `Buffer`), not the hex string. Try using `.digest()` without any params. You can still use `hash.toString('hex')` for the log statement.
> 
Thanks! It works with `crypto.createHash('sha256').update(secret).digest();`. However, I think a Utility class would be helpful for these kind fo things.
