### ISSUE TITLE
Implement BOLT1 warning messages

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#5602]
Related: https://github.com/lightningnetwork/lnd/issues/5593#issuecomment-891787008, Acinq sent a new `warning` message type in response to a `ChannelReestablish`.

See https://github.com/lightningnetwork/lightning-rfc/pull/834, which currently isn't merged yet but apparently already implemented by Eclair.

**Comment by Roasbeef** [comment]
We have a very WIP here: https://github.com/lightningnetwork/lnd/pull/5560

But as you mention the spec PR isn't really finalized yet, and we also don't advertise any few feature bits, so I wouldn't expect them to send a new message to us.

**Comment by Crypt-iQ** [comment]
New coop close proposal PR mentions warnings should be sent, not a hard requirement from my reading though: https://github.com/lightningnetwork/lightning-rfc/pull/847

**Comment by Roasbeef** [comment]
Fixed by #6546, we also start to send them now.
