### ISSUE TITLE
Getting policy info for a channel that is closed

### ISSUE THREAD

**Issue by noderunner11** [lightningnetwork/lnd#5608]
### Background

I had an inbound channel opened from LNBIG:
I was able to get policy info for a channel that was closed.
If I looked up the channel it was not showing as disabled as well and it was coming up in path findings but routing is failing.
Also, attached a screenshot of the result of doing a `getChannel`
It was like I had an inbound channel open that was already closed...

```
   peer_public_key:      033e9ce4e8f0e68f7db49ffb6b9eecc10605f3f3fcb3c630545887749ab515b9c7
    peer_alias:           LNBIG.com [[lnd-11]](url)
    channel_id:           693454x1235x0
    channel_open:         500e117e2833909b07ff757fc0d261bdb8c22f987cbc2c138965880bf01e0d16:0
    channel_close:        ef2cfa23cae1baab682dddc00bfbb41e9dd8e3b4c64e82bf452f3f29a7f41489
```
### Your environment
* version of `lnd`: v-0.13.1-beta
* which operating system (`uname -a` on *Nix): Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-1041-aws x86_64)
* version of `btcd`, `bitcoind`, or other backend: bitcoind **(pruned mode)**

### Expected behaviour

Channel should not show up as active when its already closed.

### Actual behaviour

Channel showing up as active and closed at the same time.

**Screenshot of doing a getChannel and from list of closedChannels:**

<img width="691" alt="Screen Shot 2021-08-06 at 11 32 46 AM" src="https://user-images.githubusercontent.com/84944042/128535221-b09a0acd-aad8-4ab5-ba39-535f8af9fb1d.png">

<img width="685" alt="Screen Shot 2021-08-06 at 11 32 31 AM" src="https://user-images.githubusercontent.com/84944042/128535224-e017b2c7-e5f4-47eb-9478-5d05122a5114.png">

**This is when routing is attempted:**

```
evaluating: 
  - 690203x1572x1 
  - Bitrefill 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f. Fee rate: 0.11% (1096)
  - 679023x828x0
  - Supercon--tor-1 03f11710057e2d087c2610ef9fd13886c8497af95f5be9d96e4ae7b2d4b2035e4b. Fee rate: 0.00% (0)
  - 673112x1536x0
  - LNBIG.com [lnd-11] 033e9ce4e8f0e68f7db49ffb6b9eecc10605f3f3fcb3c630545887749ab515b9c7. Fee rate: 0.33% (3290)
  - 693454x1235x0

failure: UnknownNextPeer at 693454x1235x0 from LNBIG.com [lnd-11]
```

**Comment by Roasbeef** [comment]
Yeah that channel is indeed closed....if you do `lncli getinfo`, do you see the current block height, and that your node is fully synced?

**Comment by noderunner11** [comment]
> Yeah that channel is indeed closed....if you do `lncli getinfo`, do you see the current block height, and that your node is fully synced?

Yeah, it is synced, just checked again now.

**Comment by noderunner11** [comment]
Happening again with another channel, here are the screenshots and I just checked again, I am synced.

<img width="630" alt="Screen Shot 2021-08-07 at 10 19 54 AM" src="https://user-images.githubusercontent.com/84944042/128603999-7ac517df-2fcc-4b19-8ba3-fd5a09ef7ef1.png">
<img width="625" alt="Screen Shot 2021-08-07 at 10 19 21 AM" src="https://user-images.githubusercontent.com/84944042/128604000-ff97d192-f375-4f78-9d67-626b3b07ce46.png">

**Comment by noderunner11** [comment]
Update on issue: I had `routing.assumechanvalid=1` turned on in lnd.conf file. Adding this to make sure you're aware of this and maybe potentially causing the issue.

**Comment by noderunner11** [comment]
Another update: removing `routing.assumechanvalid=1` and restarting the node seems to have solved the issue. The channels are now not found.

**Comment by Roasbeef** [comment]
Yeah that's the issue, since that moves to not fully verify the channel graph. Instead the channel will _eventually_ be pruned as a zombie.
