### ISSUE TITLE
New option to allow LND to listen to 127.0.0.1 for gRPC server

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#561]
Hi,

Can we add a option to allow LND to listen to 127.0.0.1 for gRPC commands, *or* specify a unix socket for communication?

I would like to be able to connect to docker containers with gRPC instead of over REST.

Is there a reason not to allow this?

(If you agree that this feature should be in LND, I could give it a try to implement it!)

**Comment by MDrollette** [comment]
#495 is meant to address this. Open to feedback on it.

**Comment by thijstriemstra** [comment]
#495 was merged. Can this be closed?

**Comment by Richard87** [comment]
Yup, just tested and works great :D
