### ISSUE TITLE
LND repeatedly fetching channels and getting hung

### ISSUE THREAD

**Issue by iliaster94** [lightningnetwork/lnd#5610]
### Background

The last time I played with it was three weeks ago and regularly checking my balance with Zap wallet in the meantime to make sure it was still there. Turns out, Zap includes the balance of offline channels in you total balance so I had no idea when it broke. It seems I can't connect to any peers because the "server has not yet finished starting up" according to RTL. On Chain seems functional. Noticed the Watchtower Client repeatedly searching for candidates and failing so I disabled that and rebooted the app to no avail. Turned Watchtower back on for the sake of maintaining defaults. I'm not sure where to go from here. 

** I should mention that EmbassyOS has root blocked off and I have yet to figure out how to make SSH keys that it will accept so that I can access it via terminal. I have been unable to verify that the channel.bak file is in the correct folder or exists at all. I do however, have a copy of the channel.bak on my PC that I downloaded via RTL for safe keeping.

### Your environment

* LND Version: 0.13.0~4
* EmbassyOS by Start9Labs
* Bitcoin Core 0.21.1~1 (the Embassy listing doesn't say bitcoind or btcd so not sure)
* Bitcoin Proxy 0.3.2
* All services have "internal" and "system defined" selected for RPC stuff.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/84783719/128612043-a449d642-1275-4bbc-8631-7e5c662d3fb8.png)

### Expected behaviour

LND usually boots and after a moment the channels appear in RTL.

### Actual behaviour

Upon boot, LND shows that I am synced to chain but not graph. After a while, it attempts to fetch channels and then repeats endlessly as shown in picture.

**Comment by guggero** [comment]
Is the bitcoind node pruned? Do you have `routing.assumechanvalid=true` in your config?

The RPC calls you see for fetching the channels is one of your tools (RTL or Zap) that's querying lnd. That's probably not the main issue. What does `lncli getinfo` say? We'll need some more infos (including logs) to say more.

**Comment by iliaster94** [comment]
The node is pruned and compensating with Bitcoin Proxy. I can't even type those into the terminal for reasons stated above. But, the issue seems to have resolved. I left it for several hours upon the last reboot I did and it caught up. I guess I was expecting to see more in the debug log showing me what block height lnd had caught up to so far. Guess that's a function of not using terminal to run it. Anyways, sorry for bothering yall

**Comment by guggero** [comment]
Okay, thanks for the update. Closing as the issue seems to be fixed.
