### ISSUE TITLE
Reliability: staying connected despite changing IP address / connection changes

### ISSUE THREAD

**Issue by xanoni** [lightningnetwork/lnd#5628]
I'm running `lnd v0.13.1-beta` on a RaspberryPi 4B (32-bit) with `bitcoind` (master). The installation itself works fine, but unfortunately the Internet connection sometimes gets reset and a new IP is assigned. The node is Tor only, so no connections over clearnet (but Tor connections to clearnet-only nodes).

I've noticed that this can lead to a subset of channels—let's between 1 and 3—staying "Inactive" for several hours, despite the actual "outage" (no Internet) only lasting for a second or two. This can typically be fixed by manually connecting to the respective nodes via the CLI.

I have not spotted a clear pattern, yet, but a hypothesis is that clearnet channels are more likely to stay inactive (to be confirmed). This would somewhat make sense given the Tor node needs to initiate the connection, and maybe it doesn't.

1) Do you have any hypotheses where to start looking for the culprit(s)? E.g., is this more likely to be an `lnd` or a `tor` problem? Something else?

2) Is there a painless way to reliably trigger reconnects if an inactive channel is detected? The "brute force" solution would be to just `lncli connect` to all nodes in a `while true; do lncli connect [...]; sleep 600; done` loop, but that probably has unintended side effects.

Let me know if I skipped any key info.

**Comment by Roasbeef** [comment]
> let's between 1 and 3—staying "Inactive" for several hours, despite the actual "outage" (no Internet) only lasting for a second or two. 

We'll back off for up to an hour (exponential back off) if we get a bunch of failures when trying to reconnect to peers. It's actually a config argument (`--maxbackoff`) so you can tweak things if things are taking too long to connect out manually.

**Comment by xanoni** [comment]
Ahh. Nice one. I kept the default value and forgot this setting even existed. I've now set it to 10 minutes instead of 1 hour.

Will report back, but feel free to close this if you want to keep things tidy.

**Comment by Dikay900** [comment]
Seems like you have the same problems as I experience as well.
I also tried manually reconnect with lncli connect but it was just a matter of time until everything went wrong there resulting into other connections also failing.

Do you have these problems as well when restarting lnd? I am currently a bit frustrated since there are some channels which just won't come back online from time to time because i cannot connet to their peer. Looking them up on 1ml and the lightning terminal they appear all up and running. I do not know if this is related to lnd or the peer lightning software...

**Comment by xanoni** [comment]
I don't really know if there's been an improvement... I noticed it last time because someone complained. Whenever I check `lntop`, there are some inactive channels ... earlier today I saw two inactive channels, and when I try to connect manually, both show me `unknown error unknown code: 240`.

```bash
$ lncli connect $KEY_A@$ONION_A:9735
[lncli] rpc error: code = Unknown desc = socks connect tcp 127.0.0.1:9050->$ONION_A:9735: unknown error unknown code: 240

$ lncli connect $KEY_AB$ONION_B:9735
[lncli] rpc error: code = Unknown desc = socks connect tcp 127.0.0.1:9050->$ONION_B:9735: unknown error unknown code: 240

lncli disconnect $KEY_A
[lncli] rpc error: code = Unknown desc = unable to disconnect peer: peer $KEY_A is not connected

lncli disconnect $KEY_B
[lncli] rpc error: code = Unknown desc = unable to disconnect peer: peer $KEY_B is not connected
```

What's this error? Are they maybe just down? Is there a way to get more verbose output? @Roasbeef

**Comment by xanoni** [comment]
It's kinda sad, but I execute this after every detected Internet connection reset now ... will try to debug properly when I find enough time.

```bash
#! /usr/bin/env -S bash -x

DELAY_PRELOOP=20
DELAY_LOOP=90
DELAY_INTRAPEER=0.5

NICE=19

PEER_LIST="\
key1@onion1.onion:9375
[...]
keyN-1@onionN-1.onion:9375
keyN@onionN.onion:9375
"

## restart tor
sudo systemctl restart tor && sleep "${DELAY_PRELOOP}"

## reconnect to lnd peers
for i in {1..3}; do
    for peer in ${PEER_LIST}; do
        echo -en "\nConnect: ${peer}\n"
        nice -n${NICE} lncli connect --perm "${peer}"
        sleep "${DELAY_INTRAPEER}"
    done
    sleep "${DELAY_LOOP}"
done
```

**Comment by Roasbeef** [comment]
Closing this for now, as it appears that the peers are just down themselves. 

That script you have won't help if you already have the peer established as a persistent connection ("already have 1 persistent connection attempt..."). 

You may want to also try restarting the Tor daemon, _then_ also restarting `lnd` as well if you're just generally running into issues w/ Tor as it can be more unstable at times. 

[This PR](https://github.com/lightningnetwork/lnd/pull/5538) should also help in the case where the remote peer changes it's tor address or IP address between reconnection attempts.

**Comment by xanoni** [comment]
In the example the peers were down and there was a persistent connection attempt, thus the message and the script would not have helped.

However, since I posted the examples I've observed other inactive channels, and some of the counterparty nodes were again not down. However, I haven't done enough testing to know if the script truly fixes channels that would have stayed inactive otherwise, or if it just gives `lnd` a nudge and accelerates the connection process a little bit.

Besides, I'm no longer sure if the problem is really the connection reset, or if the connectivity problems with certain nodes are independent of that. I've now observed inactive channels to major nodes (which shouldn't be down) even after the IP has been stable for several days.

Need to do more pattern recognition.
