### ISSUE TITLE
node went down when channels are pending force closure

### ISSUE THREAD

**Issue by noderunner11** [lightningnetwork/lnd#5630]
### Background

Unfortunately my node went down a couple of days ago, I was able to sweep most funds using an SCB, however before my node went down I had to two force closures in flight that were initiated by me, what would happen to these funds? The closure transactions hit a few confirmations before the node went down but they haven’t hit the maturity block yet. What would happen to the stuck as of now in those closures? 
### Your environment

* version of `lnd` v0.13.1-beta
* which operating system (`uname -a` on *Nix): Ubuntu
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details: bitcoind pruned

### Expected behaviour

Funds returning back to onchain wallet. 

### Actual behaviour

Unknown yet, funds still locked in the force closure.

**Comment by guggero** [comment]
Do you have an SCB from _before_ you force closed the channels? Then you should be able to normally recover the funds by using that SCB.
Unfortunately `lnd` used to remove the channels too early from the SCB file (this was fixed with #5528 which will be in 0.14) when a local force close was issued. So if you don't have an older SCB you might need a more manual approach. I was planning on adding a new functionality for this to `chantools`, so please let me know if you are affected.

**Comment by noderunner11** [comment]
> Do you have an SCB from _before_ you force closed the channels? Then you should be able to normally recover the funds by using that SCB.
> Unfortunately `lnd` used to remove the channels too early from the SCB file (this was fixed with #5528 which will be in 0.14) when a local force close was issued. So if you don't have an older SCB you might need a more manual approach. I was planning on adding a new functionality for this to `chantools`, so please let me know if you are affected.


I have an older SCB before the force closures, I ran that one and the channels show up in pending force closure, do I have to wait till the maturity block for the funds to return because I initiated the closure or will I be able to sweep the funds? 

Also, adding that feature to chantools would be great.

**Comment by guggero** [comment]
Ah okay, that is good! Then lnd will sweep the funds as soon as the time lock expires. There is no way around the time lock, no.

I'm closing the issue as the initial problem was solved in #5528 and you'll get the funds back soon.
Feel free to comment again if something doesn't work as expected.
