### ISSUE TITLE
Restorechanbackup: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 9414286** [lightningnetwork/lnd#5634]
Unfortunately, I overwritten the working .lnd/data folder with my old 2019 backup (.lnd/data) and lost all information about channels.

When I start my LND node and try to recover channel from actual channel.backup
`lncli restorechanbackup --multi_file=channel.backup`

 lnd crashes with error:

 `2021-08-17 01:37:20.910 [INF] LTND: SCB Recovery: created channel shell for ChannelPoint(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0), chan_type=2
2021-08-17 01:37:20.910 [INF] LTND: Inserting 1 SCB channel shells into DB
2021-08-17 01:37:20.913 [INF] LTND: Informing chain watchers of new restored channels
2021-08-17 01:37:20.914 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0)
2021-08-17 01:37:20.916 [INF] CNCT: ChannelArbitrator(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=696129
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xaff441]`

[recover.txt](https://github.com/lightningnetwork/lnd/files/6995935/recover.txt)

Environment
version": "0.13.99-beta commit=v0.13.0-beta-150-gedd41526
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-34-generic x86_64)

**Comment by Roasbeef** [comment]
Relevant stack trace: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xaff441]

goroutine 2371 [running]:
github.com/lightningnetwork/lnd/chainntnfs.(*TxNotifier).RegisterSpend(0x0, 0xc000abc024, 0xc000d6a200, 0x22, 0x1f4, 0x95ebe, 0x0, 0x0, 0x0)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/chainntnfs/txnotifier.go:991 +0x61
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterSpendNtfn(0xc000400500, 0xc000abc024, 0xc000d6a200, 0x22, 0x1f4, 0x95ebe, 0x0, 0x0, 0x1f4)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:636 +0x86
github.com/lightningnetwork/lnd/contractcourt.(*chainWatcher).Start(0xc001af9280, 0xc0004fa2b0, 0x0)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/contractcourt/chain_watcher.go:267 +0x264
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).WatchNewChannel(0xc000502c60, 0xc000abc000, 0x0, 0x0)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:1121 +0x48f
github.com/lightningnetwork/lnd.(*chanDBRestorer).RestoreChansFromSingles(0xc0005ca4e0, 0xc0023f8780, 0x1, 0x1, 0x1, 0x1)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/chanrestore.go:272 +0x2fd
github.com/lightningnetwork/lnd/chanbackup.Recover(0xc001936000, 0x55, 0x80, 0x17b5aa0, 0xc0005ca4e0, 0x17b5b00, 0xc0000e2280, 0xc0001f4400, 0x7fc430ccf718)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/chanbackup/recover.go:50 +0x20c
github.com/lightningnetwork/lnd/chanbackup.UnpackAndRecoverMulti(0xc000e46000, 0x835a, 0xa000, 0x7fc430ccf718, 0xc00000e120, 0x17b5aa0, 0xc0005ca4e0, 0x17b5b00, 0xc0000e2280, 0x17d50c0, ...)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/chanbackup/recover.go:122 +0xc9
github.com/lightningnetwork/lnd.(*rpcServer).RestoreChannelBackups(0xc0005a6a90, 0x17d50c0, 0xc002c86120, 0xc002dfc080, 0xc0005a6a90, 0xc00004cb00, 0x1)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/rpcserver.go:6464 +0x4d0
github.com/lightningnetwork/lnd/lnrpc._Lightning_RestoreChannelBackups_Handler.func1(0x17d50c0, 0xc002c86120, 0x13f75c0, 0xc002dfc080, 0x1, 0x1, 0xc00004cb00, 0xc00002a2f8)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:22551 +0x8b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x17d50c0, 0xc002c86120, 0x13f75c0, 0xc002dfc080, 0x26, 0x0, 0x0, 0xc001d54001)
        /home/vnc/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x114
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).MacaroonUnaryServerInterceptor.func1(0x17d50c0, 0xc002c86120, 0x13f75c0, 0xc002dfc080, 0xc0005ca280, 0xc0002be280, 0x8300, 0x835e, 0x0, 0x0)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/rpcperms/interceptor.go:485 +0xc2
```

**Comment by Roasbeef** [comment]
AFAICT, the node may not actually be fully initialized yet. When you enter this command, has the node already been unlocked and is ready to accept RPC requests?

**Comment by 9414286** [comment]
The node was already been unlocked and was ready to accept RPC requests. But I can't garantie that it was fully initialized (synced_to_chain and synced_to_graph), but I have seen actual wallet balance before start restorechanbackup. 
Now I waiting synced_to_chain and synced_to_graph to try again.

**Comment by guggero** [comment]
I would recommend to use a tagged version of `lnd` (e.g. 0.13.1-beta) and not the `master` branch. You should be able to "downgrade" now as there hasn't been a DB migration just yet.

**Comment by 9414286** [comment]
I saw database migration messages in log, when start LND firstly (after my fault)

> 
> 
> I would recommend to use a tagged version of `lnd` (e.g. 0.13.1-beta) and not the `master` branch. You should be able to "downgrade" now as there hasn't been a DB migration just yet.

**Comment by guggero** [comment]
Yes, those messages are always logged. If you're on version 22 of the DB (which both 0.13.1-beta and current master use), you are fine.

**Comment by Crypt-iQ** [comment]
If we're looking at the same code (current master):

https://github.com/lightningnetwork/lnd/blob/52767a7567afe1a96e275a8659f77467ac0fe72f/chainntnfs/txnotifier.go#L987-L994

seems like the txnotifier isn't initialized and panics upon calling the member `n.quit`?

**Comment by Roasbeef** [comment]
> seems like the txnotifier isn't initialized and panics upon calling the member n.quit?

Yeah so I'm thinking they just need to wait for it to spin up? Though IIRC, we had logic here to reject requests that came in too early.

**Comment by 9414286** [comment]
Now I have some strange things:
1) `
2021-08-18 01:58:55.974 [INF] LNWL: Finished rescan for 6 addresses (synced to block 0000000000000000000059e97dea0b0b9ebf4ac1fd66726b339fe1c9683de656, height 696302)
2021-08-18 01:58:56.827 [INF] LTND: Chain backend is fully synced (end_height=696302)!
` -here I can see some clannels, that was added with first restorechanbackup (before fall)
2) but, `    "synced_to_chain": false,
    "synced_to_graph": false,`
3) zero walletbalance

**Comment by guggero** [comment]
When you recovered your node, did you start with a clean/empty `.lnd` directory? Or did you restore the `channel.backup` file over the 2019 backup?

**Comment by 9414286** [comment]
> 
> 
> When you recovered your node, did you start with a clean/empty `.lnd` directory? Or did you restore the `channel.backup` file over the 2019 backup?

I have main ubuntu LND server and mounted remote discs storage (quite good secured).
1) Ubuntu server LND installed, .LND folder, with lnd.config (datadir = / mnt / storage / .lnd / data).
2) Remote discs storage with old version .LND folder with actual data folder only.

My fault was: I copy data folder from server to storage.

So, after fault, I started my actual LND node with /data folder from 2019. Afrer sussesfuly start (with upgrade db log messages), 
I did restore the channel.backup file over the actual /.lnd folder except 2019 /data folder.

Now I see something wrong: still "synced_to_chain": false, "synced_to_graph": false, and zero walletballance.

So I have plan do it from first step:
1) make present / data folder backup,
2) rewrite present / data with old version copy (2019) / data folder agein
3) start LND, wait for "synced_to_chain": true, "synced_to_graph": true,
4) make restore the `channel.backup`

**Comment by guggero** [comment]
You should never start `lnd` from an old backup! That puts your channel balance at risk.
When you use the `channel.backup`, make sure you start from scratch (empty `.lnd` folder!). Otherwise you'll end up with a borked state.

**Comment by 9414286** [comment]
Yes, I know about such risk, but I have only 3 small channel from 2019.  Ok, I get it. 
So, I will install new /.lnd and copy it. 

Is it enaught to copy new /.lnd/**data** folder only?  (or I need full new /.lnd folder with old wallet.db)

**Comment by guggero** [comment]
You can delete all files except the `wallet.db` and then use `reset-wallet-transactions=true` in your `lnd.conf` to make it rescan the chain from the beginning and detect funds. Make sure to remove that option again after a successful run, otherwise it will happen on every startup.

**Comment by 9414286** [comment]
I've done a new instance of the .lnd node with the old wallet.db. To see my balance I made 'lncli unlock --recovery_window=2500'. With full synced node 'lncli restorechanbackup --multi_file=channel.backup' was without any error.
