### ISSUE TITLE
Delete specific payments

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#5639]
### Background

Currently there is a RPC that can delete all (failed) payments/htcls via `Lightning.DeleteAllPayments`. 

But there does not seem to be a way to delete a specific payment by referencing e.g. its hash or index number. Is there a reason for it, or would there be a general interest in having this ability?

**Comment by guggero** [comment]
I can't think of a reason why such an RPC shouldn't exist. So if anyone wants to go for it, I'll add my review :+1:

**Comment by bjarnemagnussen** [comment]
Thanks @guggero! I will look into this!

**Comment by ErikEk** [comment]
@bjarnemagnussen Might wanna take a look at https://github.com/lightningnetwork/lnd/issues/5641 while you're working with the same endpoint.

**Comment by bjarnemagnussen** [comment]
Closed by https://github.com/lightningnetwork/lnd/pull/5660
