### ISSUE TITLE
Support invoices without amount specified.

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#564]
According to this:

https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md

amout is optional for payment invoice. Unfortunatelly lncli doesn't give option to create invoice without amout:

> lncli addinvoice
[lncli] value argument missing

In lncli there is sendpayment method that gives possibility for sender to specify amount, but I don't see command that creates payment_hash without invoice.

How can I query for payment without amout, and send payment  with amout specified by sender?

Also when trying to create invoice by RPC I got error message:

> Caused by: io.grpc.StatusRuntimeException: UNKNOWN: zero value invoices are disallowed

**Comment by halseth** [comment]
Zero value invoices are currently not supported by the LN spec. The invoice format makes in optional to allow for this in the future :)

**Comment by halseth** [comment]
Correction: it is supported by the LN spec, but `lnd` does not currently support it.

**Comment by halseth** [comment]
Sorry, I misunderstood your initial description. Per the discussion on the mailing list, I believe this is a feature request? :)

**Comment by halseth** [comment]
Summary:

It is possible by the LN specification to pay invoices that has no specified amount, allowing "donation type" payments. `lnd` currently requires an invoice to specify the amount.

### Steps to completion:
- [ ] Allow the creation of invoices with no amount.
- [ ] Handle incoming HTLCs paying an invoice without any amount.
- [ ] Allow payment using invoices with no amount, where the amount is specified at time of payment.

**Comment by wilmerpaulino** [comment]
Since I'm working on #636, which covers some of the same code, I'll pick this up as well :)
