### ISSUE TITLE
Suggestion: REST API - Deleting payment arguments should not be optional.

### ISSUE THREAD

**Issue by jackeveritt** [lightningnetwork/lnd#5641]
### Background

Since the Delete Payments operation is so destructive, the arguments should not be optional. If not defined, I think it would be better to return an error.

REST API - [DELETE] https://api.lightning.community/#v1-payments

### Your environment

LND version 0.13.1-beta

### More Info

The documentation does not define these arguments as optional, nor document the defaults either

**Comment by redek-zelton** [comment]
The better way for you is to store all your outgoing payments with "listpayments" in your own datastore. It's true that DeletePayment is destructive. May be you should check macaroon if it s possible to delete directly there.
