### ISSUE TITLE
Documentation on pruned mode support is outdated

### ISSUE THREAD

**Issue by krtk6160** [lightningnetwork/lnd#5656]
### Background

The safety [docs](https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#pruned-bitcoind-node) around prune mode support are outdated and do not specify that prune mode is now supported with v0.13.0

**Comment by Roasbeef** [comment]
Looks like we missed updating that section in this commit: https://github.com/lightningnetwork/lnd/commit/410b30b9caaf59a78a29d8b924e14395b7daa59d

**Comment by gusandrioli** [comment]
This was fixed here: https://github.com/lightningnetwork/lnd/commit/a39e6105e46e34a7c573c157bae2ce11df0541fc

**Comment by guggero** [comment]
Fixed in #5765.
