### ISSUE TITLE
Websocket not working on Node.JS

### ISSUE THREAD

**Issue by LAMike310** [lightningnetwork/lnd#5680]
### Background

I created a script to watch for events called `socket.js`

```

const WebSocket = require('ws');

const macaroon = "xxxx"

ws.on('message', function incoming(event) {
    const result = JSON.parse(event).result;
    console.log(result)
    ws.send('{}')
});

```
And a `invoice.js` script

```
const request = require('request');
const macaroon = "xxx"

let requestBody = {
    memo: "Hello World",
    value: "1",
}
let options = {
  url: 'https://localhost:8080/v1/invoices',
  rejectUnauthorized: false,
  json: true,
  headers: {
    'Grpc-Metadata-macaroon': macaroon,
  },
  form: JSON.stringify(requestBody),
}
request.post(options, function(error, response, body) {
  console.log(body);
});

```

As you can see in the video below, everything works fine for the first 2-3 payments, then the script closes out:

https://streamable.com/4mh6rj

### Your environment

* version of `lnd`: **0.13.1 beta**
* which operating system: **Linux** 
* version of `btcd`, `bitcoind`, or other backend: **Neutrino**
* any other relevant environment details: Running this CDK https://github.com/a5an0/ThunderCloud

### Steps to reproduce

Run the `socket.js` script, and the `invoice.js` script to create a couple of invoices, pay them, and see if the script closes.

### Expected behaviour

Socket connection should give an error message or stay open indefinitely 

### Actual behaviour

Socket closes out after 2-3 payments, can create many invoices without a problem

**Comment by guggero** [comment]
Thank you for the report. I was able to reproduce this locally and am investigating what causes it.
For now, you should be able to work around the problem by setting `--ws-ping-interval=0` and `--ws-pong-wait=0` until this is properly fixed.

**Comment by LAMike310** [comment]
Thanks for looking into it, I ended up using the gRPC for now, but I will keep those ws flags handy for next time.
