### ISSUE TITLE
lnwire: mild regression in BenchmarkWriteMessage between 449f207 and  031d7b1

### ISSUE THREAD

**Issue by odeke-em** [lightningnetwork/lnd#5687]
Here is an exhibit of the performance of this repo after the ~latest code at 449f207217bb9d04229c71be5ef7665549f96cd3, changed from https://github.com/lightningnetwork/lnd/commit/031d7b1d556a65d7efc993f194f624216d9f59b3

https://dashboard.github.orijtech.com/benchmark/f599c2cf80b945ef9c2444e0c866c954
<img width="1526" alt="Screen Shot 2021-09-02 at 7 14 45 PM" src="https://user-images.githubusercontent.com/4898263/131940312-f87ddbc2-aebb-42ef-b70a-94dc2b772880.png">

and the hints of changes can be seen per

<img width="638" alt="Commits on Aug 30, 2021" src="https://user-images.githubusercontent.com/4898263/131941084-1774ef8d-ba23-49bf-b161-07c76cc7e3b1.png">

I was exhibiting to @arshbot in PR https://github.com/lightningnetwork/lnd/pull/5565 how using gobencher with a base commit to the master branch will ensure that all other benchmarks will have something to be compared against. Next week or so we plan on releasing a view that'll show the progression of magnitudes of benchmarks to help with visually pinpointing when changes occurred.

**Comment by saubyk** [comment]
Not clear about the action here. Closing the issue, feel free reopen if this is still a concern.
