### ISSUE TITLE
Migrate LND from 32 bit to 64 bit Raspberry pi 4 (myNode BTC)

### ISSUE THREAD

**Issue by imacfan** [lightningnetwork/lnd#5691]
I want to upgrade my node to 64 bit for LND.

What's the suggested steps to do it without losing existing channels. I have those available on my 32 bit node. 

Thanks

**Comment by guggero** [comment]
You can follow the "Option 1" of this step: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#migrating-a-node-to-a-new-device
There is a warning about migrating between architectures in that document, but it looks like ARM32 -> ARM64 is safe to do (many RaspiBlitz and myNode machines were migrated recently, so far no problems were discovered).

I'm going to create a PR to remove the warning in the linked document (or reduce it to the migration path that is known to be buggy, which is Linux<->Windows).
