### ISSUE TITLE
Un expected `[ERR]` log output when calling `lncli state`

### ISSUE THREAD

**Issue by bodymindarts** [lightningnetwork/lnd#5694]
### Background

`lmcli state` is causing unexpected log output.

### Your environment

* version of `lnd`
  v0.13.1
* which operating system (`uname -a` on *Nix)
  COS
* version of `btcd`, `bitcoind`, or other backend
  v0.21.1
* any other relevant environment details
  Kubernetes version: 1.19.12

### Steps to reproduce

```
lncli state
```

The logs will show:
```
2021-09-06 13:47:09.838 [ERR] RPCS: [/lnrpc.State/SubscribeState]: context canceled
```

We are using `lncli state` as our readiness + liveness probe and so are getting a continuous stream of ^^ output.

### Expected behaviour

No unexpected log output

**Comment by ErikEk** [comment]
Will look into it.
