### ISSUE TITLE
Recovered channel leads to force close which is stuck in waiting and cannot be reinitiated

### ISSUE THREAD

**Issue by JustAGuy12345** [lightningnetwork/lnd#5696]
### Background
(THIS IS A REPOST BECAUSE ORIGINAL WAS CLOSED BEFORE MY PROBLEM WAS SOLVED OR BEFORE I WAS ADEQUATELY HELPED TO FIND A WORKAROUND)
Channel close is stuck in waiting and cannot be forced through LND commands.

### Your environment

latest stable version LND on Umbrel OS lightning node
raspberry pi 8gb

### Steps to reproduce
This channel originally would not loop out or complete a cooperative close. There was an OS level error following this and I had to recover my channels through backup. The channel backup initiated a force close on this channel and it has remained in waiting ever since.

### Expected behaviour

I am expecting a force close and deposit of the 600,000 satoshi balance into my bitcoin wallet from the channel close.
### Actual behaviour

lnd --forceclose emits an error and pending force close is not fulfilled.

**Comment by guggero** [comment]
Going to re-open the original issue that was closed prematurely.
