### ISSUE TITLE
Local force-closing on remote `Error` is not happening

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#5698]
### Background

When SBW has a locally missing channel user may connect to remote peer and send an `Error` extracting a `channelId` from remote `ChannelReestablish` message. Remote LND is expected to force-close a channel but instead it replies with an `Error` and nothing happens.

Message log from SBW side:

```
SBW <-- ChannelUpdate(b2670a0473ae4f71e3487891f41e064aa3c66f8c52ed08a96a7fc1ad61c5879c54e6f481557b1e8562d39deeedd877e4d54919453fa9da3e035e06c1c5be0f07, ...

SBW <-- ChannelReestablish(93273fd57c8714ae0ddaff5a730d3adb82a7afc98700345ecffbd52938cbee03,168,167, ...

... user sees a missing channel warning and decides to ask a force-close.

SBW --> Error(93273fd57c8714ae0ddaff5a730d3adb82a7afc98700345ecffbd52938cbee03,ByteVector(36 bytes, 0x706c65617365207075626c69736820796f7572206c6f63616c20636f6d6d69746d656e74))

SBW <-- Error(93273fd57c8714ae0ddaff5a730d3adb82a7afc98700345ecffbd52938cbee03,ByteVector(43 bytes, 0x756e61626c6520746f20726573756d65206368616e6e656c2c207265636f76657279207265717569726564))

... channel stays open
```

### Your environment

* version of `lnd`: 0.13.1-beta commit=v0.13.1-beta

### Steps to reproduce

Send an `Error` to remote LND peer.

### Expected behaviour

Remote peer should force-close a channel.

### Actual behaviour

Remote peer replies with an `Error` containing an `unable to resume channel, recovery required` message and does nothing.

If peer is sent an "all zeros" `Error` it still does nothing and does not reply with `Error`.

**Comment by Crypt-iQ** [comment]
We don't force close in response to an `Error` message, or do anything with the all-zeros `Error` message

**Comment by btcontract** [comment]
Why? Does not seem to be compliant with spec.

**Comment by Crypt-iQ** [comment]
Not sure why as I didn't implement the initial logic there, but also all-zeros `Error` message is going to be removed I believe?

**Comment by Crypt-iQ** [comment]
If you want to trigger a remote force close for an lnd channel, you can send an "old" `ChannelReestablish` message to trigger DLP, or send an invalid `commit_sig`

**Comment by Roasbeef** [comment]
We never implemented it since we felt it was somewhat abusive (you send an error and _we're_ forced to incur the CSV delay), I think most of the other implementations stopped doing it as well.
