### ISSUE TITLE
Bad onion check fails on sending a second HTLC while the first one is stuck

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#570]
My wallet is connected to 025685ded18090d2d60120f8c2a0069c8972ce3672f9ee37684895a798038bf1c4.
The first HTLC is sent to 03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2 and gets stuck (stays neither fulfilled nor failed).
The second HTLC is sent to starblocks coffeshop, lnd responds with a failure which fails to pass this check: https://github.com/btcontract/lnwallet/blob/master/app/src/main/java/com/lightning/wallet/ln/ChannelData.scala#L317

UPD this is reproducible on both my wallet and Eclair for android, error does not happen in similar scenario when connected to an Eclair-based node.

**Comment by btcontract** [comment]
The same error just happened amid channel reestablishment process after disconnect with a single in-flight HTLC

**Comment by Roasbeef** [comment]
Related to #528

**Comment by Roasbeef** [comment]
Fixed by 9a76b3ee58fc581f8c4d0bef6f4d0979da3e6ca1
