### ISSUE TITLE
Recovery scan warnings: opcode OP_DATA_75 requires 76 bytes, but script only has 39 remaining

### ISSUE THREAD

**Issue by nipponese** [lightningnetwork/lnd#5703]
### Your environment

* version of `lnd`: `lnd version 0.13.1-beta commit=v0.13.1-beta`
* which operating system (`uname -a` on *Nix): `Linux raspberrypi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend" `Bitcoin Core version v0.21.1`
* any other relevant environment details

### Steps to reproduce

Followed directions at: https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
1. Used `lncli create`
2. Entered seed
3. Correctly entered cipher seed password
4. Opened the wallet

### Expected behaviour

No warnings

### Actual behaviour
After running lnd for about three hours, this warning has shown up in the logs >2,500 times (with different hash)
`2021-09-08 10:49:08.181 [WRN] LNWL: Could not parse output script in b341bb39955c5cf50af37244c1ae65d9fd4e9dc7363009508c54138a9c45ff23:2: opcode OP_DATA_75 requires 76 bytes, but script only has 39 remaining`

When running `lncli getrecoveryinfo`, it does seem the "progress" value is increasing.

**Comment by guggero** [comment]
These errors are actually harmless and you can ignore them for now. It's some weird data in some of the early blocks.
We should mute the message though, that just needs a set of changes in one of the chain libraries we use.

**Comment by Roasbeef** [comment]
See this issue: https://github.com/lightningnetwork/lnd/issues/5222 

It's a benign error
