### ISSUE TITLE
[PSBT channel open] illegal base64 data at input byte 4092

### ISSUE THREAD

**Issue by MaxHillebrand** [lightningnetwork/lnd#5717]
### Background

Trying to open a channel with the psbt workflow, signing wallet is Wasabi, funding utxo is a CoinJoin output.

### Your environment

* lnd version 0.13.1-beta
* Debian 10

### Steps to reproduce

RTFM: :smile: https://github.com/lightningnetwork/lnd/blob/master/docs/psbt.md
But use Wasabi hot wallet `Advanced > Build Transaction`. Then click the copy button for the Base 64 encoded PSBT.

### Expected behaviour

Successful channel opening.

### Actual behaviour

```
Error received: got error from server: rpc error: code = Unknown desc = user canceled funding
[lncli] base64 decode failed: illegal base64 data at input byte 4092
```

### Speculation

Maybe this is because the funding input is a CoinJoin output? The signed PSBT from Wasabi is substantially larger in my case compared to the docs.

**Comment by guggero** [comment]
See https://github.com/lightningnetwork/lnd/issues/5080, you need to save the PSBT as a file and enter the filename in the prompt.

> Paste the funded PSBT here to continue the funding flow.
> If your PSBT is very long (specifically, more than 4096 characters), please save
> it to a file and paste the full file path here instead as some terminals will
> truncate the pasted text if it's too long.

Read The F** Help Text? ;-)

**Comment by MaxHillebrand** [comment]
I see, thank you.
My lncli was out of date, that's why I didn't get the prompt mention.
