### ISSUE TITLE
0-fee channel probing attack & mitigation

### ISSUE THREAD

**Issue by mb300sd** [lightningnetwork/lnd#5721]
I've been using watchhtlcstream.py from lndpytools to monitor my node in the background, and noticed some strange activity.

I've been getting a lot of lines resembling
FORWARD 7 0 Tue Sep 14 00:26:11 2021 100000.0 for 0.0

I can't be sure weather this is an actual channel probing attack or someone's buggy software sending 0-fee routing attempts, but it seems that LND is leaking balance information regardless.

If the channel balance is sufficient for forwarding, it returns FEE_INSUFFICIENT, while if the balance is not sufficient for forwarding, it returns TEMPORARY_CHANNEL_FAILURE.

I propose checking the fee and returning the FEE_INSUFFICIENT error prior to checking the balance, in order to avoid leaking information.

**Comment by tvolk131** [comment]
@Roasbeef is this something that we still want done? If so, I can pick it up.

**Comment by saubyk** [comment]
Closing as should be addressed with pr #7490
