### ISSUE TITLE
itest-flake: ARM test timeout

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#5723]
Test times out after 1 hour.

Attached is the goroutine dump.
[arm-test-timeout.txt](https://github.com/lightningnetwork/lnd/files/7159917/arm-test-timeout.txt)

**Comment by yyforyongyu** [comment]
Do we have the build logs?

**Comment by guggero** [comment]
No, unfortunately I didn't think of saving the build logs as well. I thought the goroutine dump might be enough to see where things are hanging. But I looked through them now and didn't find anything obvious. I'm starting to think that Go on ARM has a general problem since golang 1.16 and later...

**Comment by yyforyongyu** [comment]
fixed by #6825
