### ISSUE TITLE
Disable auto-generated onion address advertisement

### ISSUE THREAD

**Issue by the-honeybadger** [lightningnetwork/lnd#5729]
### Background

When TOR is enabled a v3 onion address is generated based on the TLS cert and added to the available URIs for the node. If an onion keypair is already configured in the TOR service and added to LND via an externalip flag then the additional auto-generated onion address is not desired; I want the only URI for the node to be the vanity onion. Could we create a no-onion-advertise flag?

Alternatively, LND could add support for flat ed25519 keypairs, but this can already be handled by the TOR service without any extra work.

### Your environment

lnd 13.1
debian 10
bitcoind 0.21.1
tor 0.4.5.10

### Steps to reproduce

Use mkp224o to generate a vanity onion, add that keypair to TOR for port 9735, enable tor in lnd so outbound connections are proxied, add the vanity hostname as an externalip, restart lnd and note the multiple URIs in "lncli getinfo"

### Expected behavior

I need LND to use TOR but only advertise the one custom URI.

### Actual behavior

The node advertises both onion addresses.

### Side notes

I'm obviously not a developer and I really appreciate you taking the time to help me with a slightly odd request.

**Comment by Roasbeef** [comment]
Yeah `lnd` expects the key to be in a particular format, you'll likely just need to massage the output of `mkp224o` to write it in that format.
