### ISSUE TITLE
How to use SendToRouteV2 for MPP with failing shards?

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5733]
### Background

I'd like to construct routes manually and send a large amount as an MPP to my destination by splitting the payment into several shards I send out via SendToRouteV2. Naturally, some of those shards may fail, and (eventually) some of them will reach the destination.

My intuition is to re-send the amounts for failed shards via a different route, so that (eventually) all shards reach their destination and the whole MPP amount can be settled.

However, this does not work, as lnd complains about "payment has reached terminal condition" when I send another shard. I think this only happens after the first shard failed, but I'm not too sure.

In a chat with @alexbosworth he helped me with a few points:

> LND has a safety method that does not allow new shards to start until the entire mpp failed

> the route has to fail completely first

> you have to wait until you get a full resolution on all shards

> shards that succeed will be failed with mpp failure code

Even with those hints, I fail to understand how to proceed in my situation. How does `lncli payinvoice` work internally, i.e. how does it react to failing shards? I don't see a response for successful (i.e., blocking and waiting) shards. How is this supposed to look like? My intuition is that these shards just hang (without communicating any error).

### Your environment

* lnd 0.13.1-beta
* gRPC via Java

### Steps to reproduce

* Send some shards with same MPP data via SendToRouteV2
* Wait for failing shard ("temporary channel failure" somewhere along the route)
* Send failing shard's amount again via a different route

### Expected behaviour

New shard is sent and, potentially, arrives at destination (or fails).

### Actual behaviour

SendToRouteV2 throws exception: "payment has reached terminal condition"

**Comment by yyforyongyu** [comment]
> How does lncli payinvoice work internally, i.e. how does it react to failing shards? 

`lncli payinvoice` uses `SendPaymentV2`, which will construct the routes, hence the shards, for you. If the shard fails with terminal errors, such as payment timeout, no routes, incorrect payment details, or insufficient funds, the payment will be terminated.

`SendToRouteV2`, however, treats each shard differently. Atm, if a shard fails, we always fail the payment.
https://github.com/lightningnetwork/lnd/blob/03bce2129b2c738ed9e2a55acd30ad1eb76b0e26/routing/router.go#L2259-L2284

**Comment by C-Otto** [comment]
Thank you. To clarify, does that mean that `lncli payinvoice` fails if just one of the (many) shards reaches a channel that experiences a "temporary channel failure"?

**Comment by yyforyongyu** [comment]
> Thank you. To clarify, does that mean that `lncli payinvoice` fails if just one of the (many) shards reaches a channel that experiences a "temporary channel failure"?

Nope. In that case, it will retry by constructing a new route and attempt to send the payment again.

**Comment by C-Otto** [comment]
Oh, OK. To clarify again, `lncli payinvoice` replaces failed shards by new shards, completing the whole MPP over time (or running into, say, a timeout). Is that correct? If so, I'd love to do the same with my own routes. How can I do that?

**Comment by Roasbeef** [comment]
> Is that correct? If so, I'd love to do the same with my own routes. How can I do that?

You'd need to modify `SendToRoute` to add a mode that doesn't assume it's being used for a single shot payment.

**Comment by C-Otto** [comment]
Thanks. I hope you agree that the current SendToRoute is rather useless for MPP. I opened a feature request so that this can be tackled.
