### ISSUE TITLE
unable to initialize neutrino backend: unable to create neutrino database: timeout

### ISSUE THREAD

**Issue by ashjkl159** [lightningnetwork/lnd#5736]
### Background
Did setup of EC2 Instance according to "https://github.com/alexbosworth/run-lnd" with neutrino as backend, no tor. In lnd.conf among other configuration (based on above manual) I did add neutrino.connect=faucet.lightning.community and bitcoin.node=neutrino

### Your environment

0.13.1-beta
OS - ubuntu server 20
neutrino backend

### Steps to reproduce

Run lnd command with neutrino.connect=faucet.lightning.community and bitcoin.node=neutrino

### Expected behaviour

LND starts

### Actual behaviour

2021-09-15 21:04:49.337 [INF] LTND: Version: 0.13.1-beta commit=v0.13.1-beta, build=production, logging=default, debuglevel=CNCT=debug,CRTR=debug,HSWC=debug,NTFN=debug,RPCS=debug
2021-09-15 21:04:49.337 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2021-09-15 21:05:49.310 [ERR] LTND: unable to initialize neutrino backend: unable to create neutrino database: timeout
2021-09-15 21:05:49.310 [INF] LTND: Shutdown complete

**Comment by guggero** [comment]
Is another instance of `lnd` still running? All the databases have a unique lock, so if you get a timeout it means another process still locks them.

**Comment by ashjkl159** [comment]
I tried to connect to my EC2 Instance from 2 different computers before. However, I only run lnd from 1 computer. I even exited from both computers and connect from only one computer and still same result

**Comment by guggero** [comment]
Check on the EC2 instance with `ps -ef | grep lnd` to make sure no other lnd instance is running.

**Comment by ashjkl159** [comment]
ubuntu     11782       1  0 Sep14 ?        00:17:37 /home/ubuntu/go/bin/lnd
ubuntu     35255   35027  0 13:58 pts/0    00:00:00 grep --color=auto lnd

do i need to kill 35255 ?

**Comment by Roasbeef** [comment]
Try a different EC2 instance perhaps? Perhaps something si wrong with the instance itself?

**Comment by ashjkl159** [comment]
ok i will terminate this instance and make new one ... bit of practice is always good :-) thanks anyway for trying
