### ISSUE TITLE
Recover funds from wallet

### ISSUE THREAD

**Issue by whizz** [lightningnetwork/lnd#574]
I was affected by #528. This was fixed. However, now when I upgrade, the database format has changed and I cannot start lnd. The solution to this mentioned in  #567 is to downgrade. But when I do, lnd crashes, because #528. 

You see my problem, right?

Is there any way to recover the funds from the wallet before wiping it? I know it's testnet, but I don't want to waste tBTC, if possible.

**Comment by MDrollette** [comment]
This is not a good solution, and I have no idea what the implications are. But this is what I did on testnet to at least be able to start lnd and close my 60+ channels gracefully and transfer the funds out. Note that it did make one channel in a weird state and unable to be closed.

I downgraded to the previous version then added this `return` here https://github.com/lightningnetwork/lnd/blob/f4a649b30a35e3f98d7f6a106e771222bb19b305/lnwallet/channel.go#L1483

```golang
if ogHTLC == nil {
		return &PaymentDescriptor{
			LogIndex:                 logUpdate.LogIndex,
			EntryType:                MalformedFail,
			FailCode:                 wireMsg.FailureCode,
			ShaOnionBlob:             wireMsg.ShaOnionBlob,
			removeCommitHeightRemote: commitHeight,
		}, nil
}
```

**Comment by Roasbeef** [comment]
Applying the patch above to that prior commit version will allow you to restart to reclaim those tBTC.  We do currently have db migration infrastructure, but it isn't yet being heavily used as we haven't shipped a stable release. Once we do, you can expect upgrades to work smoothly. In this time of active development, we've decided we can move forward more quickly by not needing to focus as much attention on maintain backward compatibility after changes.
