### ISSUE TITLE
iOS Lndmobile crash after receive sats from payment request

### ISSUE THREAD

**Issue by damiandizeo** [lightningnetwork/lnd#5742]
### Background

On iOS (14.7.1) Lndmobile.framework crash with an EXC_BAD_ACCESS when receive sats through a channel after a payment request. Crash persist when node restart.

### Your environment

* version of `lnd` --- 0.13.99-beta commit=healthcheck/v1.0.2-113-g9e8b9ccd-dirty
* which operating system (`uname -a` on *Nix) --- iOS (14.7.1)
* version of `btcd`, `bitcoind`, or other backend --- neutrino
* any other relevant environment details --- testnet

### Steps to reproduce

- User A (me) add an invoice
- User B connects to my peer, open a new channel, once is active, pay the invoice
- Once payment is done iOS App crash over github.com/lightningnetwork/lnd/record.(*AMP).String ()

![Screen Shot 2021-09-16 at 14 17 01](https://user-images.githubusercontent.com/10283906/133656405-630fa716-b2a1-4685-91d5-7f7c395fa805.png)

Last logs before crash:

[INF] DISC: Received new remote channel announcement for 2094591:3:0
[DBG] DISC: Got AnnounceSignatures for channel with full proof.
[DBG] DISC: Already have proof for channel with chanID=ff2bb0dcc326014f774c24f305950e9dfa6f6826bb975402e8dc08c9f2468e46
[DBG] DISC: Received half proof for channel ff2bb0dcc326014f774c24f305950e9dfa6f6826bb975402e8dc08c9f2468e46 with existing full proof. Sending full proof to peer=03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776
[DBG] DISC: Full proof sent to peer=03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776 for chanID=ff2bb0dcc326014f774c24f305950e9dfa6f6826bb975402e8dc08c9f2468e46
[DBG] PEER: Sending ChannelAnnouncement(chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, short_chan_id=2303027159935156224) to 03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776@91.170.177.132:9735
[INF] DISC: GossipSyncer(03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776): sending final chan range chunk, size=5580
[DBG] PEER: Sending ReplyChannelRange(start_height=0, end_height=2094606, num_chans=5580, encoding=0) to 03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776@91.170.177.132:9735
[DBG] DISC: Removed stale AnnounceSignatures message for channel=2094591:3:0 with peer=03df170f96334cf47ce8689e5f6a8f3ce8e85eda603e5a1136f8b999c2128b1776
[DBG] HSWC: ChannelLink(468e46f2c908dce8025497bb26686ffa9d0e9505f3244c774f0126c3dcb02bff:0): loaded 1 fwd pks

### Expected behaviour

Channel local amount should update with the amount from the invoice 

### Actual behaviour

App crash after node syncs.

PD: that same steps works perfectly on Android with same framework version.
PD2: if channel is closed, stop crashing.

Thanks in advance.

**Comment by guggero** [comment]
I think I found the problem, see #5743. Would be great if you could confirm the fix works.
Though I expect this to crash on Android as well... But maybe another code path is taken there?

**Comment by damiandizeo** [comment]
> I think I found the problem, see #5743. Would be great if you could confirm the fix works.
> Though I expect this to crash on Android as well... But maybe another code path is taken there?

Worked!! created a new Lndmobile.framework with your file changes on amp.go and mpp.go and no more crash!! Thanks a lot!!
