### ISSUE TITLE
Move dependencies from makefile into go 

### ISSUE THREAD

**Issue by naveensrinivasan** [lightningnetwork/lnd#5749]
### Background
The `go` tool dependencies are pinned within the `Makefile`
https://github.com/lightningnetwork/lnd/blob/44d73d7e3eef92d2526db8173818015ed94c7945/Makefile#L38-L40

This makes it harder to upgrade with tools like dependabot https://github.com/lightningnetwork/lnd/issues/5740

The golanglint is `1.42` and the version currently being used is `1.18` which makes it harder to fix issues like #5741 

### Recommendation

Move all the tool dependencies into a `go` file like `tools.go` and have a separate `go mod` which can be used for upgrades and version pinning.  

This will help clean up Makefile, Upgrade (automatically), and still have pinned versions.

#### Example 

- https://github.com/ossf/scorecard/tree/main/tools 
- https://github.com/ossf/scorecard/blob/main/tools/tools.go

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/6244.
