### ISSUE TITLE
tor.skip-proxy-for-clearnet-targets in sample-and.conf

### ISSUE THREAD

**Issue by jrydval** [lightningnetwork/lnd#5752]
### Background

The sample-and.conf file contains tor.skip-proxy-for-clearnet-targets key which is not valid option.

### Your environment

* 0.13.1

### Steps to reproduce

Set:
tor.skip-proxy-for-clearnet-targets=true 
in 
lnd.conf
and restart lnd. It will complain about this key.

### Expected behaviour

Clearnet channels for non-tor nodes.

### Actual behaviour

Config file error

**Comment by guggero** [comment]
That option was added after 0.13.1. It will be available in 0.14.0. You should always look at the `sample-lnd.conf` file for the version you're running as the one in `master` might contain new, unreleased flags.

**Comment by jrydval** [comment]
Hm, you are right. Looking forward for the next version!

Best Regards,
Jan
