### ISSUE TITLE
lnd loses connection to tor controlport

### ISSUE THREAD

**Issue by lnd-routing** [lightningnetwork/lnd#5757]
### Background

We noticed that incoming connections were failing to resolve our onion address. Checking on tor using nyx, we noticed that lnd was not connected to the controlport, only bitcoind. We have found that some other nodes are unreachable on their onion addresses, while they are online and making outgoing connections.

We have moved to manual configuration of the onion address in torrc to prevent this from reoccurring.

### Your environment

* version of `lnd`
0.13.1
* which operating system (`uname -a` on *Nix)
linux x64
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details

### Steps to reproduce

Restart tor while lnd is running

### Expected behaviour

lnd reconnects to tor controlport to advertise onion address

### Actual behaviour

lnd is not connected to tor controlport

**Comment by ErikEk** [comment]
Related: https://github.com/lightningnetwork/lnd/issues/5166

**Comment by Roasbeef** [comment]
Gonna close in favor of #5166 as that precisely describes what needs to be fixed here.
