### ISSUE TITLE
Buildroute fails on healthy route

### ISSUE THREAD

**Issue by yuvadm** [lightningnetwork/lnd#5760]
### Background

Buildroute is refusing to resolve what otherwise seems like a healthy route.

### Your environment

* v0.13.0-beta-131-gc4221c3c

### Steps to reproduce

My node (`789`) has two active and healthy channels with peers `123` and `456`. And yet, `buildroute` refuses to resolve the ring between all the nodes. 

### Expected behaviour

I would expect `buildroute` to show a healthy route. 

### Actual behaviour

```bash
$ lncli buildroute --hops 123,456,789
[lncli] rpc error: code = Unknown desc = no matching outgoing channel available for node 2 (456)
```

This behavior persists even after `resetmc`, as well as after lnd restart.

The failure occurs on the link with my node, so this doesn't seem like a gossip propagation issue.

**Comment by Roasbeef** [comment]
Seems like your node doesn't have the _outgoing_ channel for the second hop there? 

If you try to look up the channel using `lncli getchaninfo` do you see _both_ edges there?

**Comment by yuvadm** [comment]
A few hours ago the issue has resolved itself, but right now I get:

```bash
$ lncli getchaninfo 456789
{
    "channel_id": "456789",
    "chan_point": "abcdef1234:1",
    "last_update": 1632086787,
    "node1_pub": "0202",
    "node2_pub": "0303",
    "capacity": "1000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1000",
        "disabled": false,
        "max_htlc_msat": "995000000",
        "last_update": 1632086787
    },
    "node2_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1000",
        "disabled": false,
        "max_htlc_msat": "990000000",
        "last_update": 1632080740
    }
}
```

@Roasbeef What would you expect to see in the pathological case, when the issue was still occurring?

**Comment by Roasbeef** [comment]
Sounds like just an issue of update propagation (which can be slow at times in the network today with all the throttling most nodes do). 

> What would you expect to see in the pathological case, when the issue was still occurring?

If the issue was still occurring, then one of the node policies listed there would be blank. This matches up w/ that error that it doesn't know how to traverse the edge between those two nodes since it didn't have a node policy. 

Gonna close this now since the issue resolved itself.
