### ISSUE TITLE
InactiveRpcError: StatusCode.UNAVAILABLE "failed to connect to all addresses"

### ISSUE THREAD

**Issue by count-null** [lightningnetwork/lnd#5764]
### Background

I'm trying to use the gRPC interface remotely using python. I was getting this error when using someone else's script. Then I figured I'd try a minimal gRPC example to try and debug. I've found this guide which produces the same result: https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md

I am able to connect to RPC when the script runs locally. But over LAN it gives error.

### Your environment

raspiblitz 1.7 accessible at  192.168.1.21 (over LAN on same network)

`rpclisten=0.0.0.0:10009`

lncli version 0.12.1-beta commit=lightning-terminal-v0.4.1-alpha

Bitcoin Core version v0.21.0

`$ ufw allow 10009`

```
$ nmap -p 10009 192.168.1.21
Starting Nmap 7.80 ( https://nmap.org ) at 2021-09-19 13:43 EDT
Nmap scan report for raspberrypi.lan (192.168.1.121)
Host is up (0.0029s latency).

PORT      STATE SERVICE
10009/tcp open  swdtp-sv

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds
```

### Steps to reproduce

After following the steps in the link above, execute this script:
```
import lightning_pb2 as ln
import lightning_pb2_grpc as lnrpc
import grpc
import os

os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'

cert = open(os.path.expanduser('/home/user/Documents/grpctest/tls.cert'), 'rb').read()
creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel('192.168.1.21:10009', creds)
stub = lnrpc.LightningStub(channel)

# Retrieve and display the wallet balance
response = stub.WalletBalance(ln.WalletBalanceRequest())
print(response.total_balance)

```

### Actual behaviour

```
Traceback (most recent call last):
  File "/home/user/Documents/grpctest/main.py", line 19, in <module>
    response = stub.WalletBalance(ln.WalletBalanceRequest())
  File "/home/r/Documents/grpctest/venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/Documents/grpctest/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1632072392.622579918","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3186,"referenced_errors":[{"created":"@1632072392.622579207","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":146,"grpc_status":14}]}"
```

**Comment by Roasbeef** [comment]
Is your node listening on all interfaces? So not just `localhost`? If it's just listening on `localhost`, then it won't be reachable over LAN.

**Comment by guggero** [comment]
Also, if you're using `192.168.1.21` to connect to the node, then you need to add `--tlsextraip=192.168.1.21` to your `lnd` configuration and re-generate the certificate (delete tls.cert and tls.key and restart lnd).

We should probably add that information to the documentation.

**Comment by count-null** [comment]
Regenerating the tls for the node IP worked!
