### ISSUE TITLE
On-chain recovery wtih absolute index rather than recovery window

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5767]
I'd like to restore the on-chain state of a node that potentially has large gaps between keys. In this case it isn't clear what should be specified as the size of the recovery window.

The `ListAccounts` rpc returns internal and external key counts. By recording these after each invocation of `NewAddress` (or even better - `NewAddress` returns the new count), I'd know how many keys would need to be looked for.

If this absolute key index could be passed in to the recovery logic, I could be sure that all funds will be found.

**Comment by Roasbeef** [comment]
Do you realize it's essentially the same thing? The window there is the _initial_ index that we'll start at, then extend _by that window_ each time a new address is found. 

In practice, I've found that the window of most nodes isn't actually very high in practice. If you use the `lncli wallet accounts list` command on a node, you can see the internal+external key index of the two main key families we use.

**Comment by joostjager** [comment]
Nice, didn't think about that. When passing in the key index as the recovery window, I think the only downside is that `index*2` keys are scanned where just `index` would be sufficient? Doesn't sound like a big problem.
