### ISSUE TITLE
Feature request: disclose version to peers, disallow connections based on version

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5775]
### Background

This is a follow-up to the discussion in #5506. In short, lnd may have bugs that might cause a risk to peers. In the example of #5506 there is a higher risk of unilateral channel closes due to a bug in the state machine of a peer running lnd 0.12.1.

In @whitslack's words:
> I wish there were a way to fingerprint the software versions of the nodes that connect to mine so I could refuse to open channels with outdated, buggy versions. Maybe add that to the feature enhancements wishlist?

In order to avoid this risk for my own node, I'd like my peers to disclose their version (and, thus, their known bugs) to me. As a reaction to this information, I could deny new channels, deny connections altogether, or only accept connections if all channels to that peer were initiated by that peer.

Obviously, this information can be faked, and any rules imposed by my node can be circumvented. However, I believe there's a big benefit to the network as a whole, if nodes upgrade faster because of this.

**Comment by Crypt-iQ** [comment]
Concept NACK due to easy fingerprinting

**Comment by C-Otto** [comment]
@Crypt-iQ Could you elaborate, please? Which risk do you want to avoid by not disclosing the version?

**Comment by Crypt-iQ** [comment]
In case of a 0day or disclosed vulnerability that allows somebody to easily target a node.  If you want to, you can change your alias to include your version?  If anything, my opinion is that something like this should be opt-in instead of opt-out

**Comment by Roasbeef** [comment]
This isn't really possible, other than setting required feature bits on new things that're only in newer versions. 

So you'd need to implement your own finger printing, and say use that in some channel acceptor hook.
