### ISSUE TITLE
gRPC FundPsbt ignores `MinConfs` field and defaults to 1

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#5779]
### Background

The gRPC `FundPsbt` request allows to define a `MinConfs` field to set the minimum number of confirmations required for the UTXOs selection. However, this field is actually ignored and it will always default to a minimum of 1 confirmation.

### Your environment

* version of `lnd`: master

### Steps to reproduce

To scenarios:

1) Have a single unconfirmed UTXO and call `FundPsbt` with `MinConfs` set to zero and `SpendUnconfirmed` true.

2) Have a single UTXO with 1 confirmation and call `FundPsbt` with `MinConfs` set to 2.

### Expected behaviour

1) An error is returned that the wallet does not have sufficient funds.

2) A PSBT is created using this single UTXO.

### Actual behaviour

1) It should have used the single unconfirmed UTXO as we requested it to also use unconfirmed UTXOs.

2) It should have ignored the single UTXO with one confirmation as we requested to only use UTXOs with at least 2 confirmations.

### Solution

The issue seems to arise from the call of `FundPsbt` in the `btcwallet` dependency, where it is called to create inputs with a fixed minimum of 1 confirmation: https://github.com/btcsuite/btcwallet/blob/d0868cb9dd94a61788167a3a3d20f56db24a963a/wallet/psbt.go#L140-L143

I think the `FundPsbt` method in the `btcwallet` dependency should have a parameter to set the minimum confirmations for UTXOs to select.

**Comment by bjarnemagnussen** [comment]
BTW I am taking a look at it

**Comment by guggero** [comment]
Oh, so this was overlooked in https://github.com/lightningnetwork/lnd/pull/4905... The parameter needs to be threaded through correctly, yes.

**Comment by bjarnemagnussen** [comment]
Should be closed by #5689 ?

**Comment by guggero** [comment]
Yes, thanks for the reminder. Fixed in #5689.
