### ISSUE TITLE
[REST] Unlockwallet / createwallet returns 500

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#579]
I have a few problems with unlock and create wallet over rest...

All requests return Internal server error:
 - When unlocking non existant wallet: `{"error":"wallet not found","code":2}`
 - Creating a wallet while one exist: `{"error":"password must have at least 8 characters","code":2}` (note that the password I tested with was `testtest`
 - Creating wallet with password `testtest`: `{"error":"password must have at least 8 characters","code":2}`
 - Unlocking wallet with invalid password: `{"error":"invalid passphrase for master public key","code":2}`*WORKS*
 - Unlocking wallet with correct password: `{"error":"invalid passphrase for master public key","code":2}`

**Comment by halseth** [comment]
I suspect this has to do with how the password is encoded (such that `lnd` is actually not receiving "testtest").

Can you paste the exact command/script used to issue the REST call? thanks!

**Comment by Richard87** [comment]
Hi, I used these calls:

https://github.com/lightningsale/lnd-rest-php/blob/master/src/Resource/LndClient.php#L43-L48

**Comment by halseth** [comment]
I was able to make it work using 
```shell
curl -X POST -k https://localhost:8080/v1/createwallet -d '{"password": "dGVzdHRlc3Q="}'
```
Note that the password is expected to be `byte` format https://github.com/lightningnetwork/lnd/blob/beeb75cb5fdd0f21d747fad64abdfd7ffbd08cb4/lnrpc/rpc.swagger.json#L2055 and therefore is `base64` encoded. 

Let me know if that works for you!

**Comment by Richard87** [comment]
Ahh, thank you! I'm sure this solves alot of problems (I'll double check the swagger documentation next time ;) )
