### ISSUE TITLE
Feature request: Tor onion support à la `lncli --rpcserver=xxx.onion`

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#5799]
It would be great if nodes with TOR proxy support could submit lncli commands to an .onion address.

Example:
```
lncli --rpcserver=xxx.onion --macaroonpath=data/chain/bitcoin/simnet/admin.macaroon getinfo
```

**Comment by Roasbeef** [comment]
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/4939#issuecomment-905262693
