### ISSUE TITLE
outdated signature in the release page

### ISSUE THREAD

**Issue by 3cola** [lightningnetwork/lnd#5800]
### Background

When checking the signature of the manifest for the v0.13.1, I am getting a different RSA key than the one provided in the release page instructions. This is misleading. Unless I am doing something wrong.

### Your environment

* version of `lnd` : v0.13.1
* which operating system (`uname -a` on *Nix): freebsd
* version of `btcd`, `bitcoind`, or other backend: irrelevant
* any other relevant environment details

### Steps to reproduce

curl https://keybase.io/roasbeef/pgp_keys.asc | gpg --import
wget https://github.com/lightningnetwork/lnd/releases/download/v0.13.1-beta/manifest-roasbeef-v0.13.1-beta.sig
wget https://github.com/lightningnetwork/lnd/releases/download/v0.13.1-beta/manifest-v0.13.1-beta.txt
gpg --verify manifest-roasbeef-v0.13.1-beta.sig manifest-v0.13.1-beta.txt

### Expected behaviour

gpg: Signature made Wed Sep 30 17:35:20 2020 PDT
gpg:                using RSA key 4AB7F8DA6FAEBB3B70B1F903BC13F65E2DC84465
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [ultimate]

### Actual behaviour

gpg: Signature made Mon Jul 19 23:41:37 2021 CEST
gpg:                using RSA key 60A1FA7DA5BFF08BDCBBE7903BBD59E99B280306
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [unknown]

**Comment by naveensrinivasan** [comment]
have you seen this https://security.stackexchange.com/a/45534?

**Comment by Roasbeef** [comment]
Hey yeah looks like a fragment from our release template was left over, updated the docs, thanks for catching this!
