### ISSUE TITLE
unable to re-create old wallet - rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

### ISSUE THREAD

**Issue by ashjkl159** [lightningnetwork/lnd#5809]
### Background

trying to re-create wallet with onchain funds in there

### Your environment

lnd 0.13.1-beta
OS ubuntu 20 lts
bitcoind over TOR

### Steps to reproduce
after new install, lncli create new wallet, write down password, 24 word seed, no passphrase, bos chain-deposit - deposit onchain funds into wallet, then again make new install, lncli create wallet, input written down password, input written down 24 word seed, no pasphrase

### Expected behaviour

expected to see my old wallet recreated with onchain funds present

### Actual behaviour

[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by guggero** [comment]
You need to start `lnd` first before you can do `lncli create`.

**Comment by ashjkl159** [comment]
that helped thanks
tried again - lncli create wallet, input written down password, input written down 24 word seed, no pasphrase
[lncli] rpc error: code = Unknown desc = wallet already exists

P.S. This wallet was originally build in AWS EC Instance. Instance is deleted now and I am trying to re-create this wallet on my local comp.

**Comment by guggero** [comment]
Did you copy any files from the EC instance? Are you trying to just re-run the original wallet or did that wallet crash and you actually need to run the disaster recovery?
Re-installing lnd doesn't solve the problem, it's that you already have files in `~/.lnd`. If you still have funds in that old local node then you should try a different machine or temporarily move that folder away.

**Comment by ashjkl159** [comment]
no, i did not copy any files from EC2 instance ... there were no channels open at all, just onchain funds deposit ... that I am trying to recover somehow ... so I guess no need for disaster recovery

in my old local comp node I had no onchain funds, no channels at all, I can just delete it.

I am trying to re-create EC2 node on my local comp to get hold of onchain funds there and start opening channels if everything works fine

**Comment by guggero** [comment]
okay, then this should get you covered:
1. make sure `lnd` isn't running on the local machine
2. remove the `.lnd` directory (or rename it to something else just to be safe)
3. start `lnd`
4. run `lncli create`, use the seed you had from the EC2 instance
5. wait for `lncli getinfo` to report `synced_to_chain: true`
6. check your wallet balance

I'm going to close the issue since there doesn't seem to be a problem with lnd itself.
I suggest to join our community Slack (https://lightning.engineering/slack.html) if you need more assistance.
