### ISSUE TITLE
Cannot generate proto definitions for iOS

### ISSUE THREAD

**Issue by schjonhaug** [lightningnetwork/lnd#5812]
### Background

I’m following the instructions at https://github.com/lightningnetwork/lnd/blob/master/mobile/README.md for generating an lnd mobile framework for iOS. I am able to generate the framework files, but I cannot generate the proto definitions.

### Steps to reproduce

Per the README.md:

> In order to generate protobuf definitions for your language of choice, add the proto plugin to the protoc invocations found in gen_protos.sh. For instance to generate protos for Swift, add --swift_out=. and run make rpc.

So, in gen_protos.sh (located in $GOPATH/src/github.com/lightningnetwork/lnd/lnrpc/gen_protos.sh) I have added `--swift_out` directly after `protoc` in 3 places, like so:

```
# Generate the protos.
    protoc --swift_out=. -I/usr/local/include -I. \
      --go_out . --go_opt paths=source_relative \
      --go-grpc_out . --go-grpc_opt paths=source_relative \
      "${file}"

    # Generate the REST reverse proxy.
    annotationsFile=${file//proto/yaml}
    protoc --swift_out=. -I/usr/local/include -I. \
      --grpc-gateway_out . \
      --grpc-gateway_opt logtostderr=true \
      --grpc-gateway_opt paths=source_relative \
      --grpc-gateway_opt grpc_api_configuration=${annotationsFile} \
      "${file}"

    # Finally, generate the swagger file which describes the REST API in detail.
    protoc --swift_out=. -I/usr/local/include -I. \
      --openapiv2_out . \
      --openapiv2_opt logtostderr=true \
      --openapiv2_opt grpc_api_configuration=${annotationsFile} \
      --openapiv2_opt json_names_for_fields=false \
      "${file}"
```

Now, when I run `make rpc` I get the following output:

```
❯ make rpc
 Compiling protos.
cd ./lnrpc; ./gen_protos_docker.sh
Building protobuf compiler docker image...
[+] Building 1.3s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/golang:1.16.3-buster                                                                      1.1s
 => [1/4] FROM docker.io/library/golang:1.16.3-buster@sha256:9d64369fd3c633df71d7465d67d43f63bb31192193e671742fa1c26ebc3a6210                0.0s
 => CACHED [2/4] RUN apt-get update && apt-get install -y   git   protobuf-compiler='3.6.1*'   clang-format='1:7.0*'                         0.0s
 => CACHED [3/4] RUN cd /tmp   && mkdir -p /tmp/build/.cache   && mkdir -p /tmp/build/.modcache   && export GO111MODULE=on   && go get goog  0.0s
 => CACHED [4/4] WORKDIR /build                                                                                                              0.0s
 => exporting to image                                                                                                                       0.0s
 => => exporting layers                                                                                                                      0.0s
 => => writing image sha256:504a3b11c42526bd4338cc5b75b39982d277bfab76b61a29f523f537a227115f                                                 0.0s
 => => naming to docker.io/library/lnd-protobuf-builder                                                                                      0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Compiling and formatting *.proto files...
/build/lnrpc /build
Generating root gRPC server protos
Generating protos from lightning.proto, into .
protoc-gen-swift: program not found or is not executable
--swift_out: protoc-gen-swift: Plugin failed with status code 1.
make: *** [rpc] Error 1
```

So, it’s complaining that `protoc-gen-swift` is missing. I do have it installed locally via Homebrew, but this is run inside a container in Docker, right? So it’s missing from the container?

**Comment by Roasbeef** [comment]
Are you running this on master?

**Comment by Roasbeef** [comment]
I think the docs might be slightly out of date, if you just run `make ios` do things work?

**Comment by Roasbeef** [comment]
Alternatively, `make mobile-rpc`, that other call should do both the libraries and the protos however

**Comment by guggero** [comment]
Yeah, we need to update the documentation on this.
There are two ways to compile the protos for swift IMO:
1. Inside the docker image, install swift and the `protoc-gen-swift` plugin, then add the `--swift_out` to the `gen_protos.sh` file --> This is probably the more involved but ultimately optimal way since it makes sure that `protoc` has the same version for all created files.
2. Install `protoc` and `protoc-gen-swift` on your local system and run the command manually as you did. This should work fine as well but might produce some problems if the `protoc` version of your system is too far ahead or behind the one used in the docker image.

@schjonhaug would you be willing to add a PR that updates the docs to describe either of the two ways?

**Comment by schjonhaug** [comment]
Sure, I’ll take a look at it. I think the first approach is the way to go.

Just a question though: Should `--swift_out` be added to [gen_protos.sh](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/gen_protos.sh) or (gen_bindings.sh)[https://github.com/lightningnetwork/lnd/blob/master/mobile/gen_bindings.sh]? They both include the `protoc` command.

**Comment by guggero** [comment]
I think `gen_protos.sh` is more appropriate since that generates the protobuf stubs where `gen_bindings.sh` generates other mobile specific code.

**Comment by schjonhaug** [comment]
OK. And should `--swift_out` be added to all 3 `protoc` commands, or just the first one?

**Comment by guggero** [comment]
Just to the first one.
To avoid misunderstandings: You're updating the documentation to instruct users how to manually update the `gen_protos.sh` in their local source, right? You're not actually adding the `--swift_out` to the `gen_protos.sh` in your changes? Because swift is just one of a few options and we wouldn't want that to be hard coded in our `gen_protos.sh` (since it doesn't work without also installing the swift framework).

**Comment by schjonhaug** [comment]
Agreed – I’ll create a PR with updated instructions for iOS in the mobile folders’s [README.md](https://github.com/lightningnetwork/lnd/blob/master/mobile/README.md)
