### ISSUE TITLE
Direct channel between two wallets

### ISSUE THREAD

**Issue by Giiizmooooo** [lightningnetwork/lnd#5819]
Is there a wallet out there which allows me to create a channel with another wallet? Or is always a node needed in between? 

Probably a super stupid question. I started reading about the way lightning works some weeks ago and will start playing around with my own node next week. As I slowly start understanding the function of nodes and channels etc. I feel I miss the bit for the wallet part.

**Comment by Roasbeef** [comment]
Something more for the Discussions section, but: yes it's possible to make a direct channel between nodes. All nodes have a wallet.
