### ISSUE TITLE
lncli failing to return error message when not setting updatechanpolicy if max_htlc is set > channel capacity

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#5820]
### Background

lncli updatechanpolicy won't actually update channel policy, without returning any errors, if you try and set max_htlc to an amount higher than the channel capacity. This happened because of a script of mine to manage  fees on multiple channels with same peer, bashed my head since fees weren't being updated until it dawned on me.

### Your environment

* version of `lnd` 0.13.1 
* which operating system (`uname -a` on *Nix) Linux 5.10.63-v7l+ armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend 22.0
* any other relevant environment details none

### Steps to reproduce

lncli updatechanpolicy --base_fee_msat XXX --fee_rate YYY --max_htlc_msat ZZZ--time_lock_delta 40 --chan_point nnnnnnnnnnn
...where ZZZ is greater than the channel capacity

### Expected behaviour

Clear error by lncli explaining what happened

### Actual behaviour

empty response as if everything went fine

**Comment by guggero** [comment]
I think this was probably fixed in https://github.com/lightningnetwork/lnd/pull/5405.

**Comment by Roasbeef** [comment]
Yep, fixed in master and the soon to be cut 0.14.
