### ISSUE TITLE
No sync peer candidates available

### ISSUE THREAD

**Issue by f-L0x** [lightningnetwork/lnd#5822]
### Background

I'm not a pro user.
I started testing lnd on a windows machine ~ 2 years ago
Since some month it seems as it can not sync with the bitcoin network.
The lnd log creates the following error

'''
lnd: 2021-10-04 19:58:33.931 [INF] BTCN: New valid peer 165.227.7.29:8333 (outbound) (/btcwire:0.5.0/btcd:0.21.0/)
lnd: 2021-10-04 19:58:33.932 [INF] BTCN: Syncing to block height 703544 from peer 165.227.7.29:8333
2021-10-04 19:58:33.932 [INF] BTCN: Fetching set of headers from tip (height=669559) from peer 165.227.7.29:8333
lnd: 2021-10-04 19:58:34.097 [INF] BTCN: Lost peer 165.227.7.29:8333 (outbound)
lnd: 2021-10-04 19:58:34.097 [WRN] BTCN: No sync peer candidates available
'''

### My environment

* Unfornutely a very old Version:
* LTND: Version: 0.7.0-beta commit=, build=production, logging=default
* Windows

### Actual behaviour

LND applications starts. But can't sync.
Same behaviour since ~ 2 month
Tested ~ once per week

**Comment by Roasbeef** [comment]
Sounds like you're running w/ just `neutrino.connect`, you need to remove that so it can find available peers. Also you're on an _extremely_ old version and I strongly advise you to update.
