### ISSUE TITLE
Security update is ruining lots of Umbrel devices, please attempt to reach out to them

### ISSUE THREAD

**Issue by JustAGuy12345** [lightningnetwork/lnd#5825]
NOTE: I understand LND and Umbrel are different however I am getting 0 communication for umbrel developers so I want to urge some of you to bring up this concern to them and potentially help me. I will try to help other umbrel users if I can. This type of negligence can lead to catastrophic failures within the lightning network as a whole. The more people running umbrels at this point the more vulnerable the network is.

### Background

1 month old umbrel user, I was banned from Umbrel's telegram for suggesting that the update they released was incompetent due to the fact that several users had all of their channels offline post update. No one in the telegram was assisting these people, the developers there could only focus on trying to ban me for calling out their mistake.

### Your environment

N/A

### Steps to reproduce
Update umbrel to 0.4.3

### Expected behaviour

The update should not completely ruin ones lightning node.

### Actual behaviour

Several lightning nodes have been corrupted with 100% offline channels and/or other issues. Since this update is for security purposes, it is absolutely unthinkable that they released an update that would further damage the lightning nodes they are attempting to secure. I want my node to be updated to latest version of LND, but I would rather not be a guinea pig for the umbrel developers that feel the need to ban anyone suggesting they unit test their releases.

**Comment by Roasbeef** [comment]
Hi, we're in contact w/ them, it isn't an `lnd` software issue, so will close it out for now, thanks. AFAICT, those users may just need to wait for all their connections to reset, particullary if they're running pure Tor. 

See this issue: https://github.com/lightningnetwork/lnd/issues/5824#issuecomment-933891729

**Comment by JustAGuy12345** [comment]
Tor is not able to be disconnected on umbrel, you are forced to route through tor the GUI wont allow it to be disabled. If youre actually in contact with them then you need to press them to do several tests before releasing updates. Countless people were left helpless in their telegram page their nodes are probably still down.
