### ISSUE TITLE
Developer from umbrel has banned be apparently for using bad words but really its to protect their horrible software practices

### ISSUE THREAD

**Issue by JustAGuy12345** [lightningnetwork/lnd#5829]
https://github.com/getumbrel/umbrel/issues/1017

I am banned from their telegram, I am banned from submitting issues. It is almost as if they do not respect me whatsoever as a user of their software. They treated me as a criminal from the beginning, gave me no opportunity to justify anything I was talking about in their chat. And to protect the fact that I literally communicated with a handful of people who's devices went down before they banned me for "using bad language" even though I was being harassed for suggesting a re-release of the potentially broken update so I dont risk losing all of my funds due to one incompetent developer.

**Comment by Roasbeef** [comment]
Please stop using our issue tracker for your grievances against other developers.

**Comment by JustAGuy12345** [comment]
I am being BANNED from a well known distributor of your software for suggesting a fix! How do you not see how catastrophic of a fucking failure this is? Your whole network will be run by self-righteous "cant-do-wrong" cancel culture pumping censorship happy clowns.
