### ISSUE TITLE
LND on auto pilot is not becoming a relay node in Testnet3

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#583]
In Testnet3, I'm running a lightning network LND node with latest from https://github.com/lightningnetwork/lnd with Automatic channel management ( auto pilot mode).

Auto pilot established 10 outgoing channels with 0.16 BTC committed to each channels. All 10 channels are active.

I'd expect that there is enough activity on testnet for some payments to get routed thought the node, yet for several days now there are still 0 payments flowing through the LND node.

I want to take auto pilot out for a spin and see it work. A successful test would be to payments getting routed though the node automatically.

I already eliminated a few hypothesis of why this is not becoming a relay node:
1. It's not because I'm running outdated version. I upgraded to latest https://github.com/lightningnetwork/lnd/commit/9a76b3ee58fc (from Jan 8)
2. It's not because my peer port is not open (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L47). I tested that network connections from outside work and show up in LND logs.

What are likely hypothesis of why this is not becoming a relay node?

**Comment by Roasbeef** [comment]
If you check our `listpeers` output, you'll be able to see if you've routed any satoshis through a peer. An example output is: 
```
            "pub_key": "X",
            "peer_id": 21,
            "address": "X:9735",
            "bytes_sent": "12058069",
            "bytes_recv": "11062762",
            "sat_sent": "96000",
            "sat_recv": "12346",
            "inbound": true,
            "ping_time": "82744"
```

**Comment by alevchuk** [comment]
Re-check. I have 14 peers. All of them have sat_recv 0 and sat_sent 0.

**Comment by Roasbeef** [comment]
> I'd expect that there is enough activity on testnet for some payments to get routed thought the node

FWIW, the payment flow on testnet is relegated to a particular part of the subgraph close to: starblocks, htlc.me,  y'alls, etc (and other demos). All these services are also singly homed. Even the the testnet faucet which is pretty well connected, only a handful of transfers go through the node. At this point in the lifetime of the testnet network, there aren't any deployed passive metering services (which would see sustained high throughput) or the like. As a result, most make their first channel to the [faucet](https://faucet.lightning.community/), then pay yalls.org and call it a day.

**Comment by Roasbeef** [comment]
Closing this one out as this isn't really an issue with current software. It's more indicative of the current traffic patterns on testnet being concentrated to the popular demos.
