### ISSUE TITLE
what is the default autopilot.active value?

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#5843]
I take a look at sample-lnd.conf. It gives the example

```
[autopilot]

; If the autopilot agent should be active or not. The autopilot agent will
; attempt to automatically open up channels to put your node in an advantageous
; position within the network graph.
; autopilot.active=true

```

which leads me to believe that autopilot is active by default. However, it does not seem to be when I run lnd. Is it?

I take a look at config.go, and I can't figure out what the default setting is. Where is it defined?

I would prefer autopilot needs to be explicitly enabled and not automatically, but sample-lnd.conf suggests it is. I would recommend you adjust sample-lnd.conf to show all the default values. Otherwise, where are we supposed to learn the default values?

Another example is 

```
[tor]
; Allow outbound and inbound connections to be routed through Tor
; tor.active=true
```

but I also don't think tor is enabled by default.

**Comment by guggero** [comment]
The values in the sample conf are just that: example values. The default value for all `boolean` values is `false`.
See https://github.com/lightningnetwork/lnd/issues/5344 and https://github.com/lightningnetwork/lnd/pull/5596.

**Comment by AndySchroder** [comment]
Thanks for the tip.

Would it be better to make a blanket statement at the top of `sample-lnd.conf` saying all `boolean` values default to `false`, and/or somewhere in https://docs.lightning.engineering/lightning-network-tools/lnd/ ?

Or, would it be better to explicitly state the default for each variable in `sample-lnd.conf`so that if you later decide to make some `boolean` options not default to `false` everything will be clear?

**Comment by guggero** [comment]
I've clarified the request to update the sample config file here: https://github.com/lightningnetwork/lnd/issues/7612
And a first PR is apparently being worked on. Closing this issue as the other one has slightly more context.
