### ISSUE TITLE
buildroute fails on first hop

### ISSUE THREAD

**Issue by nullcount** [lightningnetwork/lnd#5846]
### Background

Similar to #5760

`buildroute` fails on the first hop but I can clearly see that the outgoing channel exists

`lncli buildroute --amt 500000 --hops 123,456,789 --outgoing_chan_id 777`
`[lncli] rpc error: code = Unknown desc = no matching outgoing channel available for node 1 (123)`

It may be worth noting that the channel 777 is only a few hours old. 

```
$ lncli getchaninfo 777

{
    "channel_id": "777",
    "chan_point": "asdf37483:1",
    "last_update": 1633706462,
    "node1_pub": "123",
    "node2_pub": "myPubKey",
    "capacity": "1000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "0",
        "disabled": false,
        "max_htlc_msat": "990000000",
        "last_update": 1633682958
    },
    "node2_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "0",
        "disabled": true,
        "max_htlc_msat": "990000000",
        "last_update": 1633706462
    }
}
```

### Your environment

`lncli version 0.13.3-beta commit=v0.13.3-beta`

**Comment by 3nprob** [comment]
@count-null Did this resolve itself automatically..?

Getting the same thing (also a few hours old channel).
