### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#5868]
### Background

Docker build fails.

### Your environment

* lnd master e6c65f1cbd5a7f3f1aed7b5ef7720a7112156d78
* linux

### Steps to reproduce

`docker build .`

### Actual behaviour

```
Cloning into '/go/src/github.com/lightningnetwork/lnd'...
Already on 'master'
Your branch is up to date with 'origin/master'.
make: git: Operation not permitted
make: git: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: *** [Makefile:160: release-install] Error 127
The command '/bin/sh -c apk add --no-cache --update alpine-sdk     git     make     gcc &&  git clone https://github.com/lightningnetwork/lnd /go/src/github.com/lightningnetwork/lnd &&  cd /go/src/github.com/lightningnetwork/lnd &&  git checkout $checkout &&  make release-install' returned a non-zero code: 2
```

**Comment by bhandras** [comment]
Can confirm it works on my end. Just guessing but do you have enough disk space?

**Comment by Roasbeef** [comment]
Confirmed I was able to build np as well.

**Comment by 10gic** [comment]
This is an issue in Alpine. A workaround:
```
FROM golang:1.17.3-alpine as builder
-------- change to ------->
FROM golang:1.17.3-alpine3.13 as builder
```

Ref:
https://discuss.circleci.com/t/unable-to-use-make/40552
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396

**Comment by thorie7912** [comment]
@guggero I had the same issue with building `v0.14.2-beta` on docker just now, and updating the alpine tag fixed it. I'm wondering, any reason not to update the Dockerfile on `master` to reflect the working alpine tag?

**Comment by guggero** [comment]
Updating the base image sounds good to me :+1:
