### ISSUE TITLE
[lncli] rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by sebastianortizp** [lightningnetwork/lnd#5872]
### Background

Downloaded Node Launcher 6.0.9 Fix clipboard
Downloaded lnd v0.13.3-beta
Already had Core installed and running normally. Couple of wallets active.
Trying to run 

"C:\Users\<xyz>\AppData\Local\Lnd\lnd.exe" --lnddir="C:\Users\<xyz>\AppData\Local\Lnd"

but when it asks for unlock

C:\Users\<xyz>>"C:\Users\<xyz>\AppData\Local\Lnd\lncli.exe" unlock
Input wallet password:
[lncli] rpc error: code = Unavailable desc = transport is closing

### Your environment

lnd v0.13.3-beta
Windows 10
core 0.21.1.0

### Steps to reproduce

Trying to run 

"C:\Users\<xyz>\AppData\Local\Lnd\lnd.exe" --lnddir="C:\Users\<xyz>\AppData\Local\Lnd"

but when it asks for unlock

C:\Users\<xyz>>"C:\Users\<xyz>\AppData\Local\Lnd\lncli.exe" unlock
Input wallet password:
[lncli] rpc error: code = Unavailable desc = transport is closing

### Expected behaviour

no idea, it's my first lnd node and I would expect for it to complete set up and allow creation of channels etc.
### Actual behaviour

Tell us what happens instead

Instead I'm not able to bypass this issue of unlocking the wallet with lncli

**Comment by Roasbeef** [comment]
Double check your ports, and also take a look at the `lnd` logs as well to se why it's failing.
