### ISSUE TITLE
Temporary loss of wallet balance 

### ISSUE THREAD

**Issue by botrunner** [lightningnetwork/lnd#588]
My wallet balance sometimes suddenly goes to 0 for no reason. I had previously some funds and suddenly (without any action)

`walletbalance` returns :
```
{    "total_balance": "0",    "confirmed_balance": "0",    "unconfirmed_balance": "0"}
```
If I wait a bit, it resumes back to the balance it had before.
`{ "total_balance": "169163672", "confirmed_balance": "169163672", "unconfirmed_balance": "0" }`

I have seen this behaviour a few time.

I'm using version 0.3 (beeb75c) with neutrino.

**Comment by Roasbeef** [comment]
If you're creating channels, then the balance of your channels isn't shown in the `walletbalance` command. Are you running with autopilot enabled? Or creating channels manually yourself?

**Comment by botrunner** [comment]
I did not mean the balance of the channels but the wallet. 
`walletbalance` suddenly returns 0, and then is back to normal after a while.
The the balance is 0, I cannot create a channel (expected error `message [lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.001 BTC only have 0 BTC  available`)
I'm using neutrino and autopilot.

**Comment by Roasbeef** [comment]
Yes, if you don't have any funds in your wallet. You can't make any channels. You need to have witness outputs in your wallet in order to be able to create channels.

**Comment by botrunner** [comment]
Yes, I understand that, but the balance went to 0 and then back to normal after few seconds.
`{
    "total_balance": "169163672",
    "confirmed_balance": "169163672",
    "unconfirmed_balance": "0"
}`

**Comment by Roasbeef** [comment]
Yes, if you're running on autopilot, then when it attempts to create a channel, it needs to ensure those inputs are only used exclusively. As a result, when a channel open req is pending, those outputs will appear to be consumed. If that pending funding workflow fails, then those outputs will then be restored to the free pool.

**Comment by botrunner** [comment]
is it going to consume the entire balance?

**Comment by Roasbeef** [comment]
If several active channels are being created, or you only have a _single output_ in your wallet. Then this may be the case. 

Perhaps hop on IRC so we can continue to discuss this? It appears that nothing is abnormal here.
