### ISSUE TITLE
unable to create chain control

### ISSUE THREAD

**Issue by thephizzz** [lightningnetwork/lnd#5885]
### Background
After starting lnd and after unlocking wallet, lnd exits with following error:

2021-10-23 15:17:28.242 [INF] LNWL: Opened wallet
2021-10-23 15:17:28.285 [INF] CHRE: Primary chain is set to: bitcoin
2021-10-23 15:17:28.287 [ERR] LTND: unable to create chain control: Post "http://127.0.0.1:8333": EOF
2021-10-23 15:17:28.299 [INF] LTND: Shutdown complete

unable to create chain control: Post "http://127.0.0.1:8333": EOF

### Your environment
lnd v0.13.3-beta 
(btw I get this when querying version: [lncli] unable fetch version from lnd: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connectex: No connection could be made because the target machine actively refused it.")

Windows 10
bitcoind v0.21.1

I am running a full bitcoin node and lnd on the same machine.
The two ran error-free for ~ 2 years and just last week all this happened.
I think my ISP changed my external IP

### Steps to reproduce
Start bitcoind and wait for full sync.
start lnd
Unlock wallet
Error occurs

### Expected behaviour
lnd should run after opening wallet and connect to bitcoind

### Actual behaviour
After starting lnd and after unlocking wallet, lnd exits with following error:

2021-10-23 15:17:28.242 [INF] LNWL: Opened wallet
2021-10-23 15:17:28.285 [INF] CHRE: Primary chain is set to: bitcoin
2021-10-23 15:17:28.287 [ERR] LTND: unable to create chain control: Post "http://127.0.0.1:8333": EOF
2021-10-23 15:17:28.299 [INF] LTND: Shutdown complete

unable to create chain control: Post "http://127.0.0.1:8333": EOF

### I am attaching lnd.conf and bitcoin.conf

Thank you for any help.

[bitcoin.conf.TXT](https://github.com/lightningnetwork/lnd/files/7403539/bitcoin.conf.TXT)
[lnd.conf.TXT](https://github.com/lightningnetwork/lnd/files/7403540/lnd.conf.TXT)

**Comment by thephizzz** [comment]
As a follow-up to this issue for those who encounter it, the solution was in m bitcoin.conf file.

I had put all of the lnd relevant entries into the [regtest] section of the bitcoin.conf file and they were ignored since I was on mainnet. After moving them to the start of the file lnd was able to connect.
These were the entries:

testnet=0
server=1
daemon=1
rpcuser= xxxxxxx
rpcpassword=xxxxxxxx
txindex=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

**Comment by Srikarrao1** [comment]
@thephizzz  After moving them to the start of the file lnd was able to connect. how to do this

**Comment by thephizzz** [comment]
I'm not sure if this is the same issue that I had, but I simply edited my bitcoin.conf file to move the lnd lines (see above) out of the [regtest] section, and placed them into the [main] section.
Hope this helps.
