### ISSUE TITLE
Documentation: leader_election.md replication of critical data section might need update

### ISSUE THREAD

**Issue by SteliosRammos** [lightningnetwork/lnd#5908]
### Background

Since the first release candidate 0.14.0 allows full remote database support, the [leader election guide](https://github.com/lightningnetwork/lnd/blob/master/docs/leader_election.md) might need to be updated, more particularly the section on the replication of non-critical data: 

>All critical data is written to the replicated database, including LND's wallet data which contains the key material and node identity. Some less critical data however is currently not written to that same database for performance reasons and is instead still kept in local bbolt files.
>
>For example the graph data is kept locally to improve path finding. Other examples are the macaroon database or watchtower client database. To make sure a node can become active and take over quickly if the leader fails, it is therefore still recommended to have the LND data directory on a shared volume that all active and passive nodes can access. Otherwise the node that is taking over might first need to sync its graph.
>
>As we evolve our cluster support we'll provide more solutions to make replication and clustering even more seamless.

**Comment by azhodl** [comment]
Vh.

**Comment by Roasbeef** [comment]
Fixed by #5917
