### ISSUE TITLE
Litecoin wallet fails

### ISSUE THREAD

**Issue by oroblu** [lightningnetwork/lnd#5909]
### Background

I can run LND on LITECOIN mainnet, i can create wallet, but after that i cannot access to the wallet.

### Your environment

* version of `lnd`: v0.13.3-beta
* which operating system: docker,linux
* version of `litecoind`: v0.18.1
******** litecoin.conf**********
server=1
txindex=1
rpcbind=192.168.0.201
rpcallowip=0.0.0.0/0
rpcport=9332
rpcuser=******
rpcpassword=******
zmqpubrawblock=tcp://192.168.0.201:39000
zmqpubrawtx=tcp://192.168.0.201:39001
***********************************************

### Steps to reproduce

Run LND on litecoin mainnet try to check wallet balance:
lncli --chain litecoin --network mainnet walletbalance

### Expected behaviour
get wallet balance

### Actual behaviour
i get en error:
[lncli] rpc error: code = Unknown desc = failed to retrieve account public key: unsupported net Unknown BitcoinNet (3686187259)

**Comment by oroblu** [comment]
Just discovered that this happen since v13.0 in version v12.0 it works. Do you plan to remove LTC support?

**Comment by Roasbeef** [comment]
The culprit for this error message: https://github.com/btcsuite/btcwallet/blob/master/waddrmgr/scoped_manager.go#L2307

**Comment by iandennismiller** [comment]
I still see this error after updating to 0.14.0

**Comment by iandennismiller** [comment]
The value `3686187259` is the magic number/identifier corresponding to the litecoin network.  That number appears in the error message:

```
[lncli] rpc error: code = Unknown desc = failed to retrieve account public key: unsupported net Unknown BitcoinNet (3686187259)
```

The error message indicates that the litecoin magic number is not recognized as such.  Instead, it appears to default to `Unknown BitcoinNet`.

**Comment by oroblu** [comment]
:pray::pray::flushed::flushed: please fix it

**Comment by iandennismiller** [comment]
I'm not sure btcwallet includes support for litecoin wallets.  I found a fork with litecoin support:

https://github.com/ltcsuite/ltcwallet

I am concerned this is non-trivial to integrate to support litecoin.  I am not familiar with the lnd internals, either.  But am I correct that this will require integrating a new wallet?

**Comment by iandennismiller** [comment]
I do not think Litecoin wallet derivation is currently supported because Litecoin's HD wallet version numbers appear to not be present in scoped_manager.  In particular, I notice litecoin is not specified at all where these constants are defined:

https://github.com/btcsuite/btcwallet/blob/559f6eff0e52f7a617382eec0d0a41c835c0709f/waddrmgr/scoped_manager.go#L24

I found a reference for litecoin wallet derivation according to BIP32:

https://github.com/satoshilabs/slips/blob/master/slip-0132.md

In general, litecoin's parameters are defined here:

https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L137

I think HD wallet derivation, including the version number, can be inferred from these parameters.

**Comment by iandennismiller** [comment]
Hi @Roasbeef - I wanted to ask an organizational question.  I saw you added this issue to milestone 0.14.0 but that tag was already released - and so was 0.14.1.  Would it make any difference, organizationally, if this issue were reassigned to one of the upcoming milestones like 0.15.0?

**Comment by iandennismiller** [comment]
Although I believe the "right" solution would be to link a wallet provider library - and the btcsuite wallet provider is a good one - would it be possible to support litecoin with a simple shim or wrapper on top of btcwallet?  As far as I can tell, the litecoin implementation would be mostly compatible, as it is.  The primary challenge, then, is for a shim to recognize the litecoin magic numbers for mainnet, testnet, etc.

Can anybody comment on this strategy?  I do foresee one issue with supporting M- addresses - but this is all beyond my current knowledge about the internals.  I'm just trying to facilitate.

**Comment by oroblu** [comment]
Hi, happy new year. Any possibility to get LTC in next release?

**Comment by oroblu** [comment]
Just see that ltcsuite create a forked version, it's RC2 but it works! https://github.com/ltcsuite/lnd

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Litecoin  support [LIVE CHAT ](litte-coin.com)

**Comment by saubyk** [comment]
Closing this issue, as LND will not be supporting LTC from 0.18 onwards.
