### ISSUE TITLE
invoice expiry watcher cancels cancelled invoices, causing lots of errors in the logs

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5911]
### Background

There seems to be some logic in invoice_expiry_watcher.go which automatically cancels invoices as soon as they expire. In general, I think this is a great idea. However, I think this code also calls CancelInvoice for invoices that have already been cancelled. As a result of this, my log file shows countless errors like the following:

```
21:01:31.738 [ERR] INVC: Unable to cancel invoice: 3183323db058dbf197f25e0ba0a86b370b4e2934e0e291ce7bb58fe27bf0a99f: unable to locate invoice
```

### Your environment

* version of `lnd`: some recent master (0.14ish)

### Steps to reproduce

1. Create invoice
2. Cancel invoice
3. Wait for invoice to expire
4. Look at logs

### Expected behaviour

The invoice is cancelled in step 2 and nothing noteworthy happens at 3./4.

### Actual behaviour

An error is logged.

**Comment by bhandras** [comment]
Thanks for reporting, indeed this error is very annoying, but fortunately it's easy to fix.
