### ISSUE TITLE
lnd reconnect (existing channel) to eclair: failure

### ISSUE THREAD

**Issue by akovalenko** [lightningnetwork/lnd#5912]
### Background

I'm running lnd on lnurl-pay.me, maintaining a channel to lntxbot.com.
Recently the channel fails to be brought up on reconnect. From my (lnd) side it looks like the peer closes the channel after I send RevokeAndAck and CommitSig, while from eclair side it looks like I'm not sending expected RevokeAndAck promptly:

```
    Forwarded From: (B){Bastien Teinturier} at 00:50
    It means your node sent a 'commit_sig', to which the counterparty
    should promptly reply with a 'revoke_and_ack' to finalize the
    update, but they have gone silent for more than 30 seconds, so
    eclair disconnects and reconnects to (hopefully) trigger the logic
    on their side (it helped a lot with buggy lnd nodes)                   00:54
    is this connection over tor?                                           00:56
``` 
The connection is over clearnet.

### Your environment

* lnd @ 217019aa8a2bdf44f9660b1df7466e3f34630c05
* Linux  5.1.0
* bitcoind 22.0

### Steps to reproduce

Probably can't be reproduced at will.

### Expected behaviour

The channel is working

### Actual behaviour

The channel doesn't work

**Comment by akovalenko** [comment]
[lnd.log.gz](https://github.com/lightningnetwork/lnd/files/7449877/lnd.log.gz)
My lnd log with debug loglevel, the relevant fragment starts with "we owe them a revocation"

[channel.json.txt](https://github.com/lightningnetwork/lnd/files/7449881/channel.json.txt)
Eclair channel states from the remote side

**Comment by Roasbeef** [comment]
Answer to this? 
> is this connection over tor?

**Comment by Roasbeef** [comment]
Also if the channel has _already_ been force closed, then nothing can be done till the force close transaction actually confirms.

**Comment by akovalenko** [comment]
> Answer to this?
> 
> > is this connection over tor?

No, it's over clearnet, as written above.
Actually the channel came back alive and well after several hours, the problem just disappeared.

**Comment by akovalenko** [comment]
It started happening again (same peer, same channel).

**Comment by Roasbeef** [comment]
Does this repro w/ rc3? A connection related bug/regresssion was fixed.

**Comment by akovalenko** [comment]
@Roasbeef the channel works fine for several days. I haven't noticed exact timing w.r.t. rc3, unfortunately.

Would you please let me know which commit could have fixed this? It'll help my understanding of lnd and where to look for future bug causes.

**Comment by saubyk** [comment]
Closing this issue. Feel free to re-open if you are encountering it again with the latest LND. Thanks.
