### ISSUE TITLE
Pending channels output incorrectly reports remote balance as zero

### ISSUE THREAD

**Issue by tanuck** [lightningnetwork/lnd#5924]
### Background

While investigating a forced closure from Breez, the outputs of the closing on-chain transaction didn't align with what we expected. `lncli pendingchannels` shows `remote_balance: 0` and a single pending htlc, however, the closing transaction has a third output for a remote balance. When looking at the logs for the construction of the closing transaction, it does include a remote balance:
```
 ourBalance: (lnwire.MilliSatoshi) 15781743297 mSAT,
 theirBalance: (lnwire.MilliSatoshi) 163085529 mSAT,
```

### Your environment

LND: v0.13.1-beta
OS: Ubuntu 18.04
Backend: btcd 0.21

### Expected behaviour

Pending channels output should have `remote_balance: 163085` for the closing channel in question.

**Comment by Roasbeef** [comment]
Was this call before or after things fully confirmed on chain? Was this a pending close or already closing channel? 

The value reported is based of _our_ final commitment transaction before the transaction went to chain. There're multiple commitment transactions in flight at any given time, and it's possible something else lands in the chain, but we'll still observe it.

**Comment by tanuck** [comment]
It's still a pending close. Awaiting the limbo balance to mature.

**Comment by tanuck** [comment]
@joostjager thought the full pending channels output may be helpful.

```
{
    "total_limbo_balance": "15835263",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0",
                "channel_point": "243bb5b4c6ac624ce80e4986f3134efa2c92f343f3f55043cf8fe30a9eb60a00:0",
                "capacity": "16000000",
                "local_balance": "15781743",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "closing_txid": "b59c9bc72df244c1581553ea54f5cf955c9101ad00b0ee00c3a95b2fee431b3b",
            "limbo_balance": "15835263",
            "maturity_height": 709345,
            "blocks_til_maturity": 1154,
            "recovered_balance": "0",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "53520",
                    "outpoint": "ca6914bcda65921055b00764191730d5827fc2529ddf6e55889c72d431d194c6:0",
                    "maturity_height": 709346,
                    "blocks_til_maturity": 1155,
                    "stage": 2
                }
            ],
            "anchor": "LIMBO"
        }
    ],
    "waiting_close_channels": [
    ]
}
```

**Comment by yyforyongyu** [comment]
I think we don't set the field of `remote_balance` in the `pending_force_closing_channels`, may look confusing.
