### ISSUE TITLE
Compaction error message due to low disk space is wrong

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5937]
### Background

When compaction failed as described in #5936 I got the following message:

> could not start compaction, destination folder /home/bitcoin/.lnd/data/graph/mainnet only has 10823012352 bytes of free disk space available while we need at least 10196967424 for worst-case compaction

This is confusing, as 10823012352 > 10196967424.

### Your environment

* 0.14.0-beta.rc2
* Linux server 5.10.0-8-amd64 #&#8203;1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Have large channel.db and attempt compaction. In my case: 9.5 GByte channel.db (plus around 600 MB sphinxreplay/wtclient) on a partition with 20 GByte total space.

### Expected behaviour

The error message shows correct numbers.

### Actual behaviour

The numbers in the error message are wrong (see above).

**Comment by Roasbeef** [comment]
We use a multiplier of 1.1 as a fudge factor to make sure we actually have enough disk space. The printed message doesn't take this multiplier into account, so it's mainly a logging issue.

**Comment by jyturley** [comment]
This sounds like an easy enough change to get my feet wet with this project. I'll make a PR that produces the following message instead:
> could not start compaction, destination folder /home/bitcoin/.lnd/data/graph/mainnet only has 10823012352 bytes of free disk space available while we need at least 11216664166 for worst-case compaction

https://play.golang.org/p/v452qzfvvQw
