### ISSUE TITLE
"updatechanstatus" and "updatechanpolicy" hangs

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5943]
### Background

This might be related to #5914.

During normal operation of my node (it forwards transactions) the invocation of "lncli updatechanstatus" hangs when I try to enable a channel that, most likely, already is enabled.

### Your environment

* 5d7e814ea8e7e4fdf48eddc40333353aa07bbf05
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

Stacktrace:
[goroutine.txt](https://github.com/lightningnetwork/lnd/files/7491981/goroutine.txt)

**Comment by C-Otto** [comment]
This happened with master+#5941 for a channel to LOOP while I had a pending forward (HODL transaction).

**Comment by C-Otto** [comment]
Same thing for a closechannel --force.

Another observation: the log shows several messages related to previous stuck requests when I stop lnd. In the case of the force-close transaction I see that the transaction was broadcast only after the shutdown request.

**Comment by C-Otto** [comment]
A couple of days I observed this for coop close attempts. I think what I thought were tor issues might be related to this deadlock issue.

> I closed a channel with a peer where I have two other channels remaining. The close command didn't terminate because of connection issues (tor. yay.) and I cancelled the lncli invocation (using CTRL+C). Now the channel shows up in waiting_close_channels, but sadly I don't see the close transaction in the mempool. When I try to close the channel again, I get "channel link not found". Is there a good way out of this, without force-closing the channel?
> 
> "Local close channel request delivered to peer: x"

**Comment by bhandras** [comment]
It looks like this is a different type of deadlock than what we fixed before in the graph cache. IUUC it seems like in this case it's hitting a limit in the validation barrier: https://github.com/lightningnetwork/lnd/blob/54584aabb6758aa40c714bd454e5e10013e8f02a/routing/router.go#L1027

since there's one goroutine that's waiting here:

```
1 @ 0x43c985 0x44db97 0xca5765 0xc9c2ea 0x473d81
#	0xca5764	github.com/lightningnetwork/lnd/routing.(*ValidationBarrier).InitJobDependencies+0xa4	/home/cotto/IdeaProjects/lnd/routing/validation_barrier.go:98
#	0xc9c2e9	github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler+0xda9		/home/cotto/IdeaProjects/lnd/routing/router.go:1051
```
I'm not super familiar with the the way this part of the code works, but it seems like your bitcoind connection may be slow for some reason? (another goroutine is waiting to get block data)

**Comment by bhandras** [comment]
There's a number of goroutines waiting to read/write from `r.networkUpdates` but it seems like this one is at least blocking:

```
13 @ 0x43c985 0x44db97 0x980b49 0x975fb9 0xc2bdae 0xc7a58b 0xc9facc 0xc9df25 0xcab713 0x473d81
#	0x980b48	github.com/btcsuite/btcwallet/chain.(*BitcoindConn).GetBlock+0x248			/home/cotto/go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/chain/bitcoind_conn.go:575
#	0x975fb8	github.com/btcsuite/btcwallet/chain.(*BitcoindClient).GetBlock+0x38			/home/cotto/go/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/chain/bitcoind_client.go:143
#	0xc2bdad	github.com/lightningnetwork/lnd/blockcache.(*BlockCache).GetBlock+0x26d			/home/cotto/IdeaProjects/lnd/blockcache/blockcache.go:52
#	0xc7a58a	github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).GetBlock+0x1ea		/home/cotto/IdeaProjects/lnd/lnwallet/btcwallet/blockchain.go:139
#	0xc9facb	github.com/lightningnetwork/lnd/routing.(*ChannelRouter).fetchFundingTx+0x8b		/home/cotto/IdeaProjects/lnd/routing/router.go:1705
#	0xc9df24	github.com/lightningnetwork/lnd/routing.(*ChannelRouter).processUpdate+0x7c4		/home/cotto/IdeaProjects/lnd/routing/router.go:1476
#	0xcab712	github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler.func1+0x3f2	/home/cotto/IdeaProjects/lnd/routing/router.go:1086```

I assume this is your desktop with many cores?

**Comment by C-Otto** [comment]
It's a cloud server with 4 vCPUs. bitcoind seems to run fine, I don't see any issue with it. It's a pruned node which runs on the same machine.

**Comment by C-Otto** [comment]
I bisected a few commits, which all experienced the same issue during/after startup:

1. "the RPC server is in the process of starting up, but not yet ready to accept calls"
2. updatechanpolicy works (two or three times)
3. it hangs

```
git bisect start
# bad: [3cef5ea61da4ebb05c1b6a618e41928bb1536228] docs: update release notes
git bisect bad 3cef5ea61da4ebb05c1b6a618e41928bb1536228
# bad: [5d7e814ea8e7e4fdf48eddc40333353aa07bbf05] Merge pull request #5674 from torkelrogstad/2021-08-26-http-mux
git bisect bad 5d7e814ea8e7e4fdf48eddc40333353aa07bbf05
# bad: [af9b62085412404f192222c5d2d0defa015135cb] Merge pull request #5538 from ellemouton/refreshPeerIP
git bisect bad af9b62085412404f192222c5d2d0defa015135cb
# bad: [fa8e8e6f999faf65efa7838459869de11f85d370] Merge pull request #5761 from naveensrinivasan/naveen/feat/fix-mongo-CVE
git bisect bad fa8e8e6f999faf65efa7838459869de11f85d370
# bad: [3385d3841436a840c2695ba064c10af9e275c032] Merge pull request #5766 from JssDWt/update-csharp-grpc-docs-grpc.net.client
git bisect bad 3385d3841436a840c2695ba064c10af9e275c032
```

This is very strange, as I've been running 5d7e814ea8e7e4fdf48eddc40333353aa07bbf05 for a while without any issues. This makes me believe that it's a configuration/environment/weird issue, that isn't caused by an (unconditional) bug in the code.

**Comment by C-Otto** [comment]
@bhandras spent some time with me to dig into this. The fact that I run a pruned bitcoind seems to be related to this, and we think lnd spends a lot of time waiting for old blocks that aren't directly available. A "hanging" command was able to recover over night, and now my node is running without any issues. I'm closing this, but it might be a good idea to add some helpful debug logs to help other users/devs identify this issue when it happens.

**Comment by bhandras** [comment]
Thanks for the investigation @C-Otto!
