### ISSUE TITLE
Need help with windows 10 batch file I made to automate a LND command at startup

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#5946]
I made the following batch file that gets launched at Windows startup:

cd C:\Users\User\AppData\Local\Lnd\bin
lncli
lncli unlock
myPassword

The first line goes to the directory of lncli.exe in cmd, the second line starts lncli.exe in the command prompt, the third line is the command to unlock a feature of the program, and the last line is supposed to input my password, but unfortunately, after the program prompts me to enter my password, my password doesn't get inputted. How can I modify this batch script so that after I am prompted for my password, my password is automatically typed in and the enter key pressed?

**Comment by Roasbeef** [comment]
Closing this as it's more of a trouble shooting request (you'll need to figure out how to feed `stdin` into the command). Would recommend reaching out to other developers on slack, or using the Discussion (Q&A) feature here.

**Comment by guggero** [comment]
I suggest you look at `lncli unlock --help` and read the description for the `--stdin` flag. Or look at `lnd --help` and make use of the `--wallet-unlock-password-file` flag.
