### ISSUE TITLE
Running lnd in neutrino mode without btcd installed will not be able to generate addresses. Inform the user for that

### ISSUE THREAD

**Issue by dannybabbev** [lightningnetwork/lnd#595]
When starting a lnd node for the first time (with ~/.lnd wiped) in **neutrino mode** without having installed `btcd` the daemon will run fine without showing the user any errors. However, when trying to generate a new address with `lncli newaddress np2wkh` the command will hang indefinitely without apparent reason.

Only upon installation of btcd, **removal of ~/.lnd** and syncing the light client the `newaddress` command works fine.

This is obviously because lnd does not manage the addresses for you but btcd does. But a user might not suspect that.

The problem is that many users who want to run lnd in neutrino mode only (on a raspberry, for example) will think that installing btcd is unnecessary, as the **daemon runs just fine without showing any signs of errors**. But the commands which require `btcd` to execute properly (such as `lncli newaddress`) will hang without result.

I think that when the `btcd` installation is not found the users must be informed via an error.

**Comment by Roasbeef** [comment]
> When starting a lnd node for the first time (with ~/.lnd wiped) in neutrino mode without having installed btcd the daemon will run fine without showing the user any errors. However, when trying to generate a new address with lncli newaddress np2wkh the command will hang indefinitely without apparent reason.

Yes, if you try to run in `neutrino` mode w/o pointing it to any `btcd` instance, then it won't operate properly. The tutorial is clear that you need to be running `btcd` locally, or point to a remote `btcd` instance. 

> This is obviously because lnd does not manage the addresses for you but btcd does. But a user might not suspect that.

Nope, `lnd` manages all addresses itself. `btcd` doesn't have a wallet at all. 

> But the commands which require btcd to execute properly (such as lncli newaddress) will hang without result.

When running in `neutrino` mode, no commands require `btcd`.

**Comment by dannybabbev** [comment]
> Yes, if you try to run in neutrino mode w/o pointing it to any btcd instance, then it won't operate properly. The tutorial is clear that you need to be running btcd locally, or point to a remote btcd instance.

Sure, it would be good if lnd shows an error about that in the output console.

**Comment by Roasbeef** [comment]
> Sure, it would be good if lnd shows an error about that in the output console.

It simply won't be able to connect outbound if there are no peers specified.
