### ISSUE TITLE
Question regarding my lightning node activity

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#5957]
I recently set up a LND node to help support the network and have been wondering how I could determine whether or not my node is successfully helping route payments.

Would the "total_satoshis_sent" and "total_satoshis_received" values tell me this?

Since I opened my channel the values have been at 0, if they were to increase to a higher number, would that mean I routed some payments?

**Comment by Roasbeef** [comment]
Check out `lncli feereport` and `lncli fwdinghistory`. 

Closing as this is just a question and not a software issue, feel free to open something in the discussions section.
