### ISSUE TITLE
Abandoned channel (later force closed by peer) settled balance not showing up in LND wallet

### ISSUE THREAD

**Issue by miceliomad** [lightningnetwork/lnd#5958]
### Background

Hi, 
 - Oct 21: I opened a channel with WoS, edge here: https://amboss.space/edge/705994x2429x1
 - Oct 23: After aprox 1-2 days, my node was not able to set a policy for the channel. So decided to abandon the channel with `lnd lncli abandonchannel --funding_txid 9a75c78fb9d1925555bfb6ba8f4b678091111df6baf1f0b6c999a140adc85ad1 --output_index 1 --i_know_what_i_am_doing`
 - Contacted WoS to make them aware and ask for a Force Close on their side. 
 - Oct 24: WoS force closed channel on their side succesfully. Closing Tx id [confirmed](https://mempool.space/tx/dbf0c928b63c5944155edb73641269efdf3b7c38585fd7011b0329021ea85c20) Note: As I abandoned the channel my node didn't know about the closing Tx but got it from peer. 

I waited 3 weeks expecting the settled amount to reach my LND wallet, but no Tx related to this closed channel can be seen in my node wallet. So the whole funding amount is lost. 

 - Nov 9: I have restarted the node with reset-wallet-transactions=true" on lnd.conf. No luck.  

Peer (WoS) has been very cooperative and we have been assessing the issue together, we conveyed it was the time to rise the issue to LND team as we don't have a clue on what's going on. Apparently my LND wallet cannot recognize the receiving address of the closing Tx or it cannot scan properly past events. 

Side note: it could be that my node was offline shortly when the closing Tx got confirmed, but if it was it was for less than 5 minutes. 

### Your environment

* version of `lnd`: v0.13.3-beta
* which operating system: umbrel on pi, 0.4.6
* version of `btcd`, `bitcoind`, or other backend: 22
* any other relevant environment details: probably not related but on same period this happened I have been experiencing strange force closes from active channels, either triggered by my node or the other side with no apparent reason for forcing it. 

### Steps to reproduce

I really don't want to reproduce it again :=) but I can extract logs or provide configuration details by request if needed. 
Links to opening and closing Tx provided above. 

### Expected behaviour

My node LND wallet should have received the settled amount already as per [confirmed Tx](https://mempool.space/tx/dbf0c928b63c5944155edb73641269efdf3b7c38585fd7011b0329021ea85c20) but is not there or my LND wallet cannot "see it". 

### Actual behaviour

Missing ~4Msats from settled onchain tx, closing Tx not showing in Tx list. Funds missing. 

Thanks in advance,

**Comment by guggero** [comment]
Abandoning a channel means giving up on it. It really should only be used if the funding transaction never made it to the chain. Did you read the help text? I assume yes, since you provided the `--i_know_what_i_am_doing` flag.

`lnd` will never pick up those funds automatically since it removed all information about the channel. You'll need to use [`chantools genimportscript --lndpaths`](https://github.com/guggero/chantools/blob/master/doc/chantools_genimportscript.md) to derive the private keys for the funds.

**Comment by miceliomad** [comment]
Thanks for the prompt reply @guggero , please don't blame me for using the `--i_know_what_i_am_doing` flag...., clearly I was not enterly sure about the full effects of doing it, but doc mentioned something about it keeping track of closures still, so I went ahead. won't do again. Lesson learnt. 

Thanks for the tip, I'll go through it carefully. 

Just a couple of questions, 
- what's the difference between `reset-wallet-transactions=true` I did recently and what chantools will do? 
- Considering my environment (umbrel), do I need to take any precaution before running `chantools genimportscript --lndpaths` (currently going through chantool docs). 

Thx again!

**Comment by guggero** [comment]
The command keeps a summary of the closed channel (what the funding TX and the remote peer was) but `lnd` won't look at the chain anymore for an abandoned channel. Maybe we should make the doc even clearer.

Currently `lnd` doesn't track the derivation path where those remote force closed funds go to automatically. Only when you use an SCB. That's why `reset-wallet-transactions` will not pick them up either. This is a bug and should eventually be fixed.
`chantools` just generates a list of all private keys, including the derivation path that `lnd` doesn't look at automatically. You'll need to import the private key into electrum or something similar to get the funds out.

You can install `chantools` on your local desktop computer, it doesn't need to be in umbrel. But it will ask you for your seed, so make sure you have that ready.

**Comment by miceliomad** [comment]
Okay, thanks for the clarity. I think I got it now, let's try step by step. I'll return with the results (or more questions..). 
thx a million

**Comment by miceliomad** [comment]
Ok, unfortunatelly it didn't work..., what I did: 

- Generated the private keys with `chantools genimportscript --lndpaths --format electrum`. Went OK. 
- Imported keys into Electrum. Electrum desktop connected to my node via Tor. Sync went OK, I can see all Tx for the wallet. 

But...
- The missing Tx or receiving address did not appear, and the balance is the same I can see in the node's LND wallet. 

Should I consider this funds lost forever?  would it be useful if I send some sats to that address? would that make the node recognize the address and maybe scan back for more Tx's¿¿ 

You mentioned there was a bug causing `reset-wallet-transactions` to not pick up these tx. Should I wait till this is solved? Do you have link to that bug report? 

Totally lost at this point. Any further tips or actions I can take are really appreciated. Would you please reopen the case if possible as this is not solved.  

Thx

**Comment by miceliomad** [comment]
![txid_wos_close](https://user-images.githubusercontent.com/94038195/141102864-b82a5ed9-c73b-4410-a0ee-033f77e460ae.png)

Attached what electrum can tell about the Tx in question after importing the keys from chantools output.  

- "Transaction unrelated to your wallet"
- LockTime: 545278228 (1987-04-13 04:10:28) ?¿

**Comment by guggero** [comment]
Ah, it was an anchor channel. There the funds are in a script output, not a simple pubkey hash output.
You'll need to run `chantools sweepremoteclosed --recoverywindow 100 --feerate 5 --sweepaddr <some_address_of_your_wallet_to_send_to> --publish` to get the funds out.

**Comment by miceliomad** [comment]
This is what I get after running `chantools sweepremoteclosed --recoverywindow 100 --feerate 5 --sweepaddr <some_address_of_your_wallet_to_send_to> --publish` and entering the seed words: 

> Error: found 0 sweep targets with total value of 0 satoshis which is below the dust limit of 600

**Comment by miceliomad** [comment]
found it! previous commend ran well but with a `--recoverywindow 500`  since I hade some more than 100 onchain Txs. Was published succesfully and it inmediately appeared on the node wallet. 
You are a Hero! how can I send you some sats for the help provided? Thanks!

**Comment by guggero** [comment]
Cool! Wasn't sure how many channels your node had in its lifetime, so apparently 100 was too small.
No tip necessary. But I'm always happy about a GitHub star on the chantools repo ;-)
