### ISSUE TITLE
Errors connecting to neutrino nodes

### ISSUE THREAD

**Issue by trigger67** [lightningnetwork/lnd#5960]
### Background

Hi, while investigating some issues with my node, I saw the same warnings coming again and again in the logs.

Everytime I restart LND, after 2 or 3 hours, I start to have a lot of warnings.
I do not know if a process starts after that time, or if simply the process is quiet until it starts to fail.

Logs seems to indicate that my node cannot query data to a neutrino node.
When I restart LND, the errors come again, but the IP of the neutrino node is different.
So it seems not to be linked to a specific node, but more of a general issue, or an issue on my side.

The logs :

```
{"log":"2021-11-09 18:29:56.010 [WRN] BTCN: Query(300) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:29:56.010796177Z"}
{"log":"2021-11-09 18:29:56.010 [WRN] BTCN: Query(300) failed with error: did not get response before timeout. Timing out.\n","stream":"stdout","time":"2021-11-09T18:29:56.010948501Z"}
{"log":"2021-11-09 18:29:59.453 [WRN] BTCN: Query(301) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:29:59.453588019Z"}
{"log":"2021-11-09 18:29:59.453 [WRN] BTCN: Query(301) failed with error: did not get response before timeout. Timing out.\n","stream":"stdout","time":"2021-11-09T18:29:59.45361016Z"}
{"log":"2021-11-09 18:30:03.454 [WRN] BTCN: Query(301) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:30:03.454437118Z"}
{"log":"2021-11-09 18:30:08.722 [WRN] BTCN: Query(302) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:30:08.722325581Z"}
{"log":"2021-11-09 18:30:13.142 [WRN] BTCN: Query(303) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:30:13.142247866Z"}
{"log":"2021-11-09 18:30:17.796 [WRN] BTCN: Query(304) from peer 176.9.123.70:8333 failed, rescheduling: did not get response before timeout\n","stream":"stdout","time":"2021-11-09T18:30:17.796609015Z"}
```

It seems to me that LND is trying again and again to query the same node. Shouldn't it stop after like X tries ? Maybe it should stop and query another node ?

### Your environment

- A new server (LND is still in the process of "downloading" the graph of channels and nodes)
- LND 0.13.3, **pruned** bitcoin core 22.0, with BTCPayServer hosted at Lunanode.

**Comment by Roasbeef** [comment]
If you only have a single peer then that's all it can try. Make sure you're not running with `--connect` as that means it won't try to connect to any other peers.

**Comment by Roasbeef** [comment]
If you have a pruned bitcoind node, then why are you also running `lnd` in neutrino mode? Given it can just connect to that `bitcoind` node? Or you mean `lnd` itself is pruned?

**Comment by trigger67** [comment]
Sorry, I have the default BTCPayServer configuration (from Lunanode), I did not set any neutrino mode anywhere.
My bitcoin node is pruned, LND node seems normal.

One remark I received on Slack + this log (with "BTCN") made me think that my node is trying to reach neutrino nodes. It's not the case ?
I am probably wrong, I thought that as my node is pruned, LND had to reach neutrino nodes to retreive some data.

In any case, this warning keeps comming. From today:
`[WRN] BTCN: Query(4773) from peer 13.229.133.26:8333`
The peer is different, and the query number is now 4773!

I have no specific issue with my node at the moment, but I want to help solve a bug if there is.

**Comment by Roasbeef** [comment]
Can you do this: https://github.com/lightningnetwork/lnd/issues/5962#issuecomment-965950271

and this: https://github.com/lightningnetwork/lnd/issues/5962#issuecomment-966724337

**Comment by Roasbeef** [comment]
What seems to be happening is this node is pruned, so it needs to try and fetch blocks that the node doesn't have from teh p2p network. Since the node was just updated to the latest version, it may need to potentially fetch a lot of blocks, and the machine it's running on my node be able to keep up with that, or the peers it's connected to can't actually serve its queries.

**Comment by trigger67** [comment]
Hey,
I think that my node finished syncing the graph, i'll need to wait a bit to have more logs.
Here are my peers: 
[GetPeerInfo.txt](https://github.com/lightningnetwork/lnd/files/7531351/GetPeerInfo.txt)

Also I do not know if it is linked, but I have an issue that my peers deactivate the channels they have with me. (that's why I started to dig into the logs and find the issue above)
And It started again... => https://yalls.org/network/0365890fd861996e6949cc6797e352278bd71fa6165219fad1d7c6e3290e2ae5ac 

Should I open another issue to investigate that ?

**Comment by trigger67** [comment]
Some BTCN debug logs : 
[lndLogs.txt](https://github.com/lightningnetwork/lnd/files/7531360/lndLogs.txt)
