### ISSUE TITLE
batchopenchannel fails with "unmatched backend error: -26: mempool min fee not met" (lnd 0.14-rc3)

### ISSUE THREAD

**Issue by xmrk-btc** [lightningnetwork/lnd#5969]
### Background

For example, trying to open a channel with 2 sat/vB, I got

`2021-11-12 19:58:49.046 [ERR] RPCS: [/lnrpc.Lightning/BatchOpenChannel]: batch funding failed: error publishing final batch transaction: unmatched backend error: -26: mempool min fee not met, 924 < 2783
`
while the mempool looked like this:
![image](https://user-images.githubusercontent.com/62961693/141537422-6c83fdf4-067f-4b60-aeb5-a2de35e36763.png)

(The time on my machine is in UTC, I am pretty sure it corresponds to 20:58 CET shown on the screenshot.)

So 2 sat/vB seems reasonable, maybe the tx would wait a few blocks, but no reason to refuse it altogether.

Similar behaviour observed with lndmanage (https://github.com/bitromortac/lndmanage), AFAIK it uses the equivalent of `lncli wallet psbt` to create multiple channels in one tx . (I am sure it does not rely on lnd's batchopenchannels, because it works with lnd 0.13.)

Possibly related: when using lncli openchannel using even lower fee (1 sat/vB), the transaction is created, but not broadcasted . Restarting lnd does force the broadcast.

### Your environment

* version of `lnd`: 0.14.rc3
* which operating system (`uname -a` on *Nix): `Linux ubuntu 5.11.0-1021-raspi #22-Ubuntu SMP PREEMPT Wed Oct 6 17:30:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: bitcoin-0.21.1

### Steps to reproduce

Run `lncli batchopenchannel --sat_per_vbyte=1 "$CHAN_JSON"` when the mempool has less than 1M of transactions with fee 1 sat/vB.

### Expected behaviour

The transaction which opens the channels should be broadcasted.

### Actual behaviour

Returns error message (see above), no transaction is broadcasted, the channels are cleaned up.

**Comment by Roasbeef** [comment]
Your node rejected the transaction. You need to raise its min mempool fee

**Comment by xmrk-btc** [comment]
But please note that `openchannel` works with even lower fee, the transaction is not rejected in that case. The only difference I see is in tx size, does it matter?

**Comment by xmrk-btc** [comment]
I tried openchannel at 22:15 CET, with 1 sat/vB , so even worse conditions, and that tx was not rejected. (But is seems it was not broadcasted either, cannot find it on blockstream explorer.)

**Comment by Roasbeef** [comment]
Yeah this is about the _absolute_ fee paid. Are you limiting the mempool of your `bitcoind` node?

**Comment by xmrk-btc** [comment]
I guess I am, those are some values of my bitcoin.conf:

```
dbcache=20M 
maxmempool=20M 
minrelaytxfee=0.000001

```

**Comment by Roasbeef** [comment]
Yeah so the effect of that is that as your mempool gets larger, then the floor of the transaction fee rate will rise.

**Comment by xmrk-btc** [comment]
ok, raised maxmempool to 100M, and successfully initiated batch of 3 channels, so it seems resolved. Thanks, and sorry for opening a non-issue.
