### ISSUE TITLE
Failure to restore lnd wallet/channels when out of sync

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#597]
I've been trying to figure out how to properly back up lnd and discovered this bug. I am unable to close channels when they become out of sync after a standard copy and paste backup/restore process. 

Scenario,
Start simnet
Fund Alice
Create channel from Alice to Bob
Send 100 satoshi from Alice to Bob
Create backup of Alice's lnd (wallet and channels)
Send 1 satoshi from Alice to Bob
Kill Alice's lnd node
Restore Alice from backup
Observe Alice and Bob are out of sync
Attempt to close channel from Alice's side (FAIL)
Attempt to close channel from Bob's side (FAIL)

**Comment by Roasbeef** [comment]
If they're out of sync, you won't be able to do cooperative channel closures as the states are incompatible.

**Comment by stridentbean** [comment]
Is there a way to do noncooperative channel closures at this time? If there is, that would be the obvious workaround. It seems to me like a total loss of the wallet and channel files will be an edge case, but not nonexistent.

**Comment by Roasbeef** [comment]
> Is there a way to do noncooperative channel closures at this time?

Yes, force close the channel.

**Comment by stridentbean** [comment]
Ah, I see, just add the `--force` to the close channel command. 

`lncli-bob closechannel 5b90f6b255d1b9298846b6ff8f3ff625b20c86bd73abcd6c73e76b238286c13d --force`
