### ISSUE TITLE
"unknown option: db.backend" when trying to create a node running on postgres

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#5975]
### Background

lnd won't start if I use the directions from https://github.com/lightningnetwork/lnd/blob/master/docs/postgres.md

### Your environment

* version of `lnd` 0.14rc3
* which operating system (`uname -a` on *Nix) Linux **** 5.10.63-v8+ # 1459 SMP PREEMPT ************** aarch64 GNU/Linux
* version of `bitcoind`,
* any other relevant environment details: testing on plebnet playground signet network

### Steps to reproduce

Follow raspibolt guide up to lightning section, I used lnd.conf from my previous test node, I removed the [bolt] section and added the configuration options found in the docs for postgres

### Expected behaviour

lnd populates postgres database

### Actual behaviour
This is returned in cycles in journalctl -f -u lnd.service:

systemd[1]: Started LND Lightning Network Daemon.
lnd[21132]: failed to load config: /home/bitcoin/.lnd/lnd.conf:61: unknown option: db.backend
systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: lnd.service: Failed with result 'exit-code'.
systemd[1]: lnd.service: Service RestartSec=30s expired, scheduling restart.
systemd[1]: lnd.service: Scheduled restart job, restart counter is at 11.
systemd[1]: Stopped LND Lightning Network Daemon.

It is maybe useful to expand on the postgres doc to include a more comprehensive example of lnd.conf file

**Comment by bhandras** [comment]
My guess is that you may need to add a section to your `lnd.conf` too:

```
[db]
db.backend=postgres
```

**Comment by asvdf** [comment]
Thank you, that partially fixed it.
After a minor hiccup with the timeout line, where I thought default duration was in seconds and I used a politically correct value of "20", to get an error about missing units, I corrected it to "20s".

Now though, I get:

lnd[4017]: 2021-11-14 18:14:56.172 [INF] LTND: Opening the main database, this might take a few minutes...
lnd[4017]: 2021-11-14 18:14:56.173 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to obtain database backends: error opening postgres graph DB: unknown database type
lnd[4017]: 2021-11-14 18:14:56.177 [INF] LTND: Shutdown complete
lnd[4017]: unable to open databases: unable to obtain database backends: error opening postgres graph DB: unknown database type


This is my relevant section of lnd.conf

[db]
db.backend=postgres
db.postgres.dsn=postgresql://bitcoin:bitcoin@locahost/bitcoin
db.postgres.timeout=20s

**Comment by bhandras** [comment]
What version of Postgres are you using?
Can you `psql` to that db? Maybe the DB doesn't exist yet? Do you have the `bitcoin` user with granted privileges to the `bitcoin` databse?

**Comment by asvdf** [comment]
I did create that database with psql with the postgres user and also added bitcoin user with bitcoin password + superuser privileges.
Just to check, I also just ran psql with bitcoin user, dropped bitcoin database, recreated it, created a dummy table inside it, removed that table, no problem.

**Comment by asvdf** [comment]
To counter-check, I even made sure the password for user bitcoin was bitcoin, by switching again to postgres user, and from inside psql running `ALTER ROLE bitcoin WITH PASSWORD 'bitcoin';`, still getting same error.

**Comment by bhandras** [comment]
Just a guess but is there any other database running on your machine? Postgres should by default listen on port `5432`.
I tested locally and for me it started up with my local Postgres instance with no issues.

**Comment by ephestione** [comment]
I did try with `sudo netstat -tulpn | grep 5432 `and indeed postgres shows up as
`Tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      4277/postgres                                                                         tcp6       0      0 ::1:5432                :::*                    LISTEN      4277/postgres`

I also remember that when I installed postgres I did have to get the packages because it wasn't installed already.

**Comment by asvdf** [comment]
Using netstat I can confirm postgres is listening on 5432, and while I have other databases running on this machine, I installed postgres just for lnd.

**Comment by bhandras** [comment]
Perhaps try specifying the port too: `postgresql://bitcoin:bitcoin@localhost:5432/bitcoin`

**Comment by asvdf** [comment]
Was going to be exactly my next move... Alas, no change

**Comment by bhandras** [comment]
Oh, I see what your problem is. You need to build `lnd` with the `postgres` backend (also in the doc https://github.com/lightningnetwork/lnd/blob/master/docs/postgres.md#building-lnd-with-postgres-support)

`make tags=kvdb_postgres`

**Comment by bhandras** [comment]
Just a quick note: if you're building a release version with postgres, make sure to add `kvdb_postgres` to the release tags: https://github.com/lightningnetwork/lnd/blob/1abe1da5b3a0e914b8c0f0d837fc0c17bed74a88/make/release_flags.mk#L41

This is because if you specify `tags` for `make` it'll overwrite the predefined build tags.

**Comment by asvdf** [comment]
> Oh, I see what your problem is. You need to build `lnd` with the `postgres` backend (also in the doc https://github.com/lightningnetwork/lnd/blob/master/docs/postgres.md#building-lnd-with-postgres-support). It is not enabled by default.
> 
> ```
> make tags=kvdb_postgres
> ```

Oh shucks, I briefly considered that I actually had to build from source, but I immediately decided that the arm64 binaries from the assets had to have been compiled with postgres enabled...

**Comment by asvdf** [comment]
After installing go, editing the release tags, downloading hundreds of MBs to my raspi, and seeing how the make command fills my tmpfs /tmp folder and stops with a not enough space on disk error, I decided I don't want to do this :-(
I'll hope for a near future when postgres support willl be just builtin :)

**Comment by bhandras** [comment]
You can also make a release build on your main machine, don't need to do that in your raspi.

```
git checkout v0.14.0-beta.rc3
make release tag=v0.14.0-beta.rc3
```
