### ISSUE TITLE
LND crashing - panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by aantonop** [lightningnetwork/lnd#5977]
### Background

Upgraded to 0.14-beta-rc3 (mistakenly thought it was 0.13.4-beta)

LND crashes after restart

### Your environment

* version of `lnd`
0.14-beta-rc3

* which operating system (`uname -a` on *Nix)
Linux ln 5.4.0-1059-aws #62~18.04.1-Ubuntu SMP Fri Oct 22 21:51:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
bitcoind: v0.21.1

### Steps to reproduce

Nov 14 23:38:41 ln lnd[18905]: 2021-11-14 23:38:41.140 [INF] NTFN: Dispatching confirmed spend notification for outpoint=9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0, script=0 418f94a68090431b1d138993a6d9afebd3edd5708f8c1463c19f3a15340accc3 at current height=709748: 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f[0] spending 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0 at height=709447
Nov 14 23:38:41 ln lnd[18905]: panic: runtime error: index out of range [1] with length 0
Nov 14 23:38:41 ln lnd[18905]: goroutine 2798 [running]:
Nov 14 23:38:41 ln lnd[18905]: github.com/lightningnetwork/lnd/contractcourt.isSuccessSpend(...)
Nov 14 23:38:41 ln lnd[18905]:         /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:270
Nov 14 23:38:41 ln lnd[18905]: github.com/lightningnetwork/lnd/contractcourt.(*htlcTimeoutResolver).Resolve(0xc007b89c00, 0xc005d83da0, 0x0, 0xc00865b0a0, 0x2)
Nov 14 23:38:41 ln lnd[18905]:         /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:296 +0x3c9
Nov 14 23:38:41 ln lnd[18905]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc0061f0000, 0x18c2ed0, 0xc007b89c00)
Nov 14 23:38:41 ln lnd[18905]:         /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2180 +0x2a2
Nov 14 23:38:41 ln lnd[18905]: created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
Nov 14 23:38:41 ln lnd[18905]:         /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1298 +0x12c
Nov 14 23:38:41 ln systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by yyforyongyu** [comment]
Looks like somehow we bypassed the `isPreimageAvailable` check. Do we have more logs for debugging purposes?

**Comment by aantonop** [comment]
I have logs preceding this but they only show the expected startup process
of a node with more than a hundred channels.

Can you recommend any other action? Or can I turn on other log settings?

**Comment by aantonop** [comment]
Additional information: I regressed to v0.14-beta-rc1 and got the same error. I can't regress to v0.13.4 because of a db schema update (from 22 to 24). 

The error always occurs right after the attempted notification of a confirmed spend at height 709447:
```
NTFN: Dispatching confirmed spend notification for outpoint=9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0
```

**Comment by Crypt-iQ** [comment]
@aantonop Can you add the following logline:
```diff
+++ log.Debugf("logging outpoint %v", spend.SpentOutPoint)
```
To the top of the `isSuccessSpend` function below:
https://github.com/lightningnetwork/lnd/blob/1abe1da5b3a0e914b8c0f0d837fc0c17bed74a88/contractcourt/htlc_timeout_resolver.go#L238-L243

**Comment by Crypt-iQ** [comment]
> Looks like somehow we bypassed the `isPreimageAvailable` check. Do we have more logs for debugging purposes?

Since we may be learning the preimage here, I think this is intentional.

**Comment by Crypt-iQ** [comment]
Additionally, can you give us more information about your bitcoind setup? Are you running with `-txindex`, are you running a pruned node, etc?

**Comment by aantonop** [comment]
> Additionally, can you give us more information about your bitcoind setup? Are you running with `-txindex`, are you running a pruned node, etc?

Bitcoin Core version v0.21.2

txindex=1 and no pruning

**Comment by aantonop** [comment]
> @aantonop Can you add the following logline:
> 
> ```diff
> +++ log.Debugf("logging outpoint %v", spend.SpentOutPoint)
> ```
> 
> To the top of the `isSuccessSpend` function below and trigger the crash again?:
> 
> https://github.com/lightningnetwork/lnd/blob/1abe1da5b3a0e914b8c0f0d837fc0c17bed74a88/contractcourt/htlc_timeout_resolver.go#L238-L243

Logs with new logging entry:

```
2021-11-15 17:43:50.946 [DBG] NTFN: Updated spend hint to height=709447 for confirmed spend request outpoint=9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0, script=0 418f94a68090431b1d138993a6d9afebd3edd5708f8c1463c19f3a15340accc3
2021-11-15 17:43:50.946 [INF] NTFN: Dispatching confirmed spend notification for outpoint=9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0, script=0 418f94a68090431b1d138993a6d9afebd3edd5708f8c1463c19f3a15340accc3 at current height=709866: 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f[0] spending 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0 at height=709447
2021-11-15 17:43:50.946 [DBG] CNCT: logging outpoint 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0
panic: runtime error: index out of range [1] with length 0

goroutine 4097 [running]:
github.com/lightningnetwork/lnd/contractcourt.isSuccessSpend(0xc009e240c0, 0xc009e24001, 0x0)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:271 +0x11d
github.com/lightningnetwork/lnd/contractcourt.(*htlcTimeoutResolver).Resolve(0xc001e20a80, 0xc005819d40, 0x0, 0xc0048fefe0, 0x2)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:297 +0x74
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc006512280, 0x18bfeb0, 0xc001e20a80)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2180 +0x2a2
created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1298 +0x12c
```

**Comment by Crypt-iQ** [comment]
Commenting for others:
It appears that the transaction passed from `chainntnfs` is not getting its witness populated, leading to an OOB panic. On a transaction explorer, it has the witness properly populated.

**Comment by Roasbeef** [comment]
> It appears that the transaction passed from chainntnfs is not getting its witness populated, leading to an OOB panic

Meaning it's possible that his node doesn't have the witness data for that block? Seems unlikely....

I think the next step would be attempting to log the full transaction as we see it (either hex or w/ `spew.Sdump`).

**Comment by aantonop** [comment]
I will continue to help with troubleshooting.

Let me know where you need to get more debug info

**Comment by Roasbeef** [comment]
Thanks, here's another diff to apply: 

This'll print out the transaction as the node sees it: 
```diff
diff --git a/contractcourt/htlc_timeout_resolver.go b/contractcourt/htlc_timeout_resolver.go
index b20f10ca9..e7b0e5eba 100644
--- a/contractcourt/htlc_timeout_resolver.go
+++ b/contractcourt/htlc_timeout_resolver.go
@@ -1,7 +1,9 @@
 package contractcourt
 
 import (
+	"bytes"
 	"encoding/binary"
+	"encoding/hex"
 	"fmt"
 	"io"
 	"math"
@@ -242,6 +244,11 @@ func isSuccessSpend(spend *chainntnfs.SpendDetail, localCommit bool) bool {
 	spendingInput := spend.SpendingTx.TxIn[spenderIndex]
 	spendingWitness := spendingInput.Witness
 
+	var b bytes.Buffer
+	spend.SpendingTx.Serialize(&b)
+	log.Infof("spending transaction hex: %v", hex.EncodeToString(b.Bytes()))
+	log.Infof("spending transaction full: %v", spew.Sdump(spend.SpendingTx))
+
 	// If this is the remote commitment then the only possible spends for
 	// outgoing HTLCs are:
 	//
```

**Comment by Roasbeef** [comment]
Updated the above comment slightly to log all the context about the spending transaction.

**Comment by aantonop** [comment]
Here's the new log with the Tx dump:

```
2021-11-15 20:53:05.146 [DBG] CNCT: logging outpoint 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0  
2021-11-15 20:53:05.147 [INF] CNCT: spending transaction hex: 020000000163ea2ad30f480abab85f761e750d980f737d3a489cf23574c814a81fce7d9c9c
00000000000000000001e4f2030000000000220020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d3990ebc50a00
2021-11-15 20:53:05.147 [INF] CNCT: spending transaction full: (*wire.MsgTx)(0xc002e4f700)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc00c032c00)({
   PreviousOutPoint: (wire.OutPoint) 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) <nil>,
   Sequence: (uint32) 0
  })
 },
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0xc002e483a0)({
   Value: (int64) 258788,
   PkScript: ([]uint8) (len=34 cap=34) {
    00000000  00 20 aa fa 6f 44 24 a3  0d 4f 7d b8 46 bd ee cc  |. ..oD$..O}.F...|
    00000010  8f 6c c0 8d c4 88 94 e1  06 9b 6d 0f e3 51 b2 4d  |.l........m..Q.M|
    00000020  39 90                                             |9.|
   }
  })
 },
 LockTime: (uint32) 706027
})

panic: runtime error: index out of range [1] with length 0

goroutine 3695 [running]:
github.com/lightningnetwork/lnd/contractcourt.isSuccessSpend(0xc00227f9c0, 0xc00227f901, 0x0)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:278 +0x485
github.com/lightningnetwork/lnd/contractcourt.(*htlcTimeoutResolver).Resolve(0xc005251880, 0xc00217f920, 0x0, 0xc003586040, 0x2)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:304 +0x74
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc002948780, 0x18bff90, 0xc005251880)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2180 +0x2a2
created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1298 +0x12c

```

**Comment by aantonop** [comment]
I'm guessing the problem is here: ```   Witness: (wire.TxWitness) <nil>,```, right?

**Comment by Crypt-iQ** [comment]
Could you log with the entire spend detail (Laolu edited his diff comment after you ran it)?

**Comment by Roasbeef** [comment]
> I'm guessing the problem is here: Witness: (wire.TxWitness) <nil>,, right?

Yeah precisely, this is what we're getting hung up on right now...

It might be reading some stale state from disk? Next step here would be a patch that allows it to get the proper transaction, which should let you restart, then we can continue finding the root cause in the background.

**Comment by aantonop** [comment]
Got it, re-applied patch and running now for full spend detail

**Comment by Roasbeef** [comment]
Does your full node know of all the info for that transaction? 

Should be really unlikely, but might as well check this off the list: 
```
bitcoin-cli getrawtransaction 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f
```

**Comment by aantonop** [comment]
```
2021-11-15 21:42:08.263 [INF] NTFN: Dispatching confirmed spend notification for outpoint=9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0, script=0 418f94a68090431b1d138993a6d9afebd3edd5708f8c1463c19f3a15340accc3 at current height=709887: 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f[0] spending 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0 at height=709447
2021-11-15 21:42:08.263 [INF] CNCT: spending transaction hex: 020000000163ea2ad30f480abab85f761e750d980f737d3a489cf23574c814a81fce7d9c9c00000000000000000001e4f2030000000000220020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d3990ebc50a00
2021-11-15 21:42:08.263 [INF] CNCT: spending detail full: (*chainntnfs.SpendDetail)(0xc0062b7fc0)(20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f[0] spending 9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63:0 at height=709447)

panic: runtime error: index out of range [1] with length 0

goroutine 3487 [running]:
github.com/lightningnetwork/lnd/contractcourt.isSuccessSpend(0xc0062b7fc0, 0xc0062b7f01, 0x0)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:277 +0x3e5
github.com/lightningnetwork/lnd/contractcourt.(*htlcTimeoutResolver).Resolve(0xc000df5880, 0xc002e42ea0, 0x0, 0xc00547ad00, 0x2)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:303 +0x74
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc003912000, 0x18c3f90, 0xc000df5880)
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2180 +0x2a2
created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
        /usr/local/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1298 +0x12c
```

**Comment by aantonop** [comment]
> `bitcoin-cli getrawtransaction 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f`

It seems to know:
```
bitcoin-cli getrawtransaction 20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f
020000000163ea2ad30f480abab85f761e750d980f737d3a489cf23574c814a81fce7d9c9c00000000000000000001e4f2030000000000220020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d3990ebc50a00
```

**Comment by aantonop** [comment]
Hm, I see no Scriptsig in the bitcoin-cli output, decoded:

```
{
  "txid": "20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f",
  "hash": "20f71bd0c14f171995a4616b0c6f2f675d4bf207c502838bb2dc081f90f3506f",
  "version": 2,
  "size": 94,
  "vsize": 94,
  "weight": 376,
  "locktime": 706027,
  "vin": [
    {
      "txid": "9c9c7dce1fa814c87435f29c483a7d730f980d751e765fb8ba0a480fd32aea63",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 0
    }
  ],
  "vout": [
    {
      "value": 0.00258788,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d3990",
        "hex": "0020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d3990",
        "reqSigs": 1,
        "type": "witness_v0_scripthash",
        "addresses": [
          "bc1q4tax73py5vx57ldcg677any0dnqgm3ygjnssdxmdpl34rvjd8xgqrrzqlg"
        ]
      }
    }
  ]
}

```

**Comment by Roasbeef** [comment]
Ah hah! Ok this is what's weird: the node isn't returning the witness information...

IIRC, it should by default, unless there's some flag we need to be setting? 

I know in the past, bitcoind had a thing where if the node upgraded _after_ segwit, it would rewind/re-download things, but I think they removed that, and maybe this node is in that situation? 

From where we can insert the proper hex:
```
0200000000010163ea2ad30f480abab85f761e750d980f737d3a489cf23574c814a81fce7d9c9c00000000000000000001e4f2030000000000220020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d39900500483045022100c0876e755415614992e83847bc2f7b9f63b7c7f94d77d1b29249763f2f2c23b5022003ad3755985af0105d0e1f870f894eecc175448a14912013e6d479b744613ec20147304402203dabf9f3242878af2b763216b60948fdc5344b9fb8a33454d14d2be47fe6e5640220157cb362ea8a011ace2e2b378020f642f72990ce0d90ec55852af76cb381226c01008576a914d6118db3a2000cf3387384791cbe2706e272636b8763ac6721025eea1b995eddc860a8d8fb1c2a807cfa85115c167e2eae1319db1fa65b7e4b2f7c820120876475527c2102762be64d0dac9857b5f39bb2c67ece29cd25fd1d8b1088c420e0377f50f9348652ae67a91449ca43ee12b19a64a53ea27add7b08996d8cc7df88ac6868ebc50a00
```

So the node can at least start up, as we continue to fall deeper into this rabbit whole...

**Comment by aantonop** [comment]
This bitcoind node has been running for years. It's strange that it doesn't have the full transaction.
I'm going to run a reindex on the bitcoin node.

**Comment by aantonop** [comment]
Can I restart lnd with neutrino backend for now, until my bitcoin node reindexes?

**Comment by Crypt-iQ** [comment]
I don't know off-hand if restarting lnd with a different backend is supported. I don't see why it wouldn't be, but I can't recommend it because I don't know.  I can work on a patch with the correct witness version if you decide not to use neutrino.

**Comment by aantonop** [comment]
I'll wait for the re-index to complete and see if that fixes the bitcoind issue

I would appreciate a patch to insert the correct Tx hex for this transaction and hopefully that's enough to get the node up again

**Comment by Crypt-iQ** [comment]
Somebody just told me that bitcoind -> neutrino won't work, but the other way does.  Will work on that patch

**Comment by Crypt-iQ** [comment]
If reindexing doesn't work, you can try this. I am pretty sure this will work as long as I didn't mess up when typing out the hex:

```diff --git a/chainntnfs/bitcoindnotify/bitcoind.go b/chainntnfs/bitcoindnotify/bitcoind.go
index d4206d310..89923b58d 100644
--- a/chainntnfs/bitcoindnotify/bitcoind.go
+++ b/chainntnfs/bitcoindnotify/bitcoind.go
@@ -1,6 +1,8 @@
 package bitcoindnotify
 
 import (
+	"bytes"
+	"encoding/hex"
 	"errors"
 	"fmt"
 	"sync"
@@ -816,6 +818,43 @@ func (b *BitcoindNotifier) historicalSpendDetails(
 			}
 
 			txHash := tx.TxHash()
+
+			spendTx := chainhash.Hash{
+				0x20, 0xf7, 0x1b, 0xd0, 0xc1, 0x4f, 0x17, 0x19,
+				0x95, 0xa4, 0x61, 0x6b, 0x0c, 0x6f, 0x2f, 0x67,
+				0x5d, 0x4b, 0xf2, 0x07, 0xc5, 0x02, 0x83, 0x8b,
+				0xb2, 0xdc, 0x08, 0x1f, 0x90, 0xf3, 0x50, 0x6f,
+			}
+
+			// Short-circuit for this particular spending txid.
+			if txHash == spendTx {
+				chainntnfs.Log.Infof("short-ciruiting for txid: %v", spendTx)
+				txString := []byte("0200000000010163ea2ad30f480abab85f761e750d980f737d3a489cf23574c814a81fce7d9c9c00000000000000000001e4f2030000000000220020aafa6f4424a30d4f7db846bdeecc8f6cc08dc48894e1069b6d0fe351b24d39900500483045022100c0876e755415614992e83847bc2f7b9f63b7c7f94d77d1b29249763f2f2c23b5022003ad3755985af0105d0e1f870f894eecc175448a14912013e6d479b744613ec20147304402203dabf9f3242878af2b763216b60948fdc5344b9fb8a33454d14d2be47fe6e5640220157cb362ea8a011ace2e2b378020f642f72990ce0d90ec55852af76cb381226c01008576a914d6118db3a2000cf3387384791cbe2706e272636b8763ac6721025eea1b995eddc860a8d8fb1c2a807cfa85115c167e2eae1319db1fa65b7e4b2f7c820120876475527c2102762be64d0dac9857b5f39bb2c67ece29cd25fd1d8b1088c420e0377f50f9348652ae67a91449ca43ee12b19a64a53ea27add7b08996d8cc7df88ac6868ebc50a00")
+				txBuf := make([]byte, hex.DecodedLen(len(txString)))
+				_, err = hex.Decode(txBuf, txString)
+				if err != nil {
+					chainntnfs.Log.Infof("failed to decode tx hex string: %v", err)
+					return nil, fmt.Errorf("couldn't decode tx hex: %v", err)
+				}
+
+				reader := bytes.NewReader(txBuf)
+				var msgTx wire.MsgTx
+				err = msgTx.BtcDecode(reader, 70013, wire.WitnessEncoding)
+				if err != nil {
+					chainntnfs.Log.Info("failed to decode wire msg tx: %v", err)
+					return nil, fmt.Errorf("couldn't decode wire msg tx: %v", err)
+				}
+
+				inputIndex := uint32(0)
+				return &chainntnfs.SpendDetail{
+					SpentOutPoint:     &msgTx.TxIn[inputIndex].PreviousOutPoint,
+					SpenderTxHash:     &txHash,
+					SpendingTx:        &msgTx,
+					SpenderInputIndex: inputIndex,
+					SpendingHeight:    int32(709447),
+				}, nil
+			}
+
 			return &chainntnfs.SpendDetail{
 				SpentOutPoint:     &tx.TxIn[inputIdx].PreviousOutPoint,
 				SpenderTxHash:     &txHash,
```

**Comment by aantonop** [comment]
Thank you @Crypt-iQ

**Comment by aantonop** [comment]
All fixed after re-index. Thanks for your help. 

Perhaps some error-checking code is needed in that function so that if the bitcoind backend does not return a Tx correctly it doesn't crash the node?

**Comment by Roasbeef** [comment]
> All fixed after re-index. Thanks for your help.

Interesting, maybe something we want to surface to the `bitcoind` devs? Very curious w.r.t how that happened in the first place 🤔

> Perhaps some error-checking code is needed in that function so that if the bitcoind backend does not return a Tx correctly it doesn't crash the node?

Perhaps, but on the other hand the crash helped us find this issue, that maybe otherwise would've gone unnoticed (the HTLC just sitting on the chain when it can be timed out).
