### ISSUE TITLE
High memory consumption (memory leak?)

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5979]
### Background

My node consumes 6.4G of RAM ("RES" according to top), and according to my data this figure is slowly increasing. Even if it were constant, I think it's a bit too much. A heap "pprof" shows a total consumption of around 3G, which is far below the 6.4G.

![lnd_heap_nov_15_10_01](https://user-images.githubusercontent.com/344948/141753039-39c2e19d-9b66-4490-9858-154db9e0aa45.png)

The node has been started on November 12th, and the data shown above has been obtained on November 15th (today).

Some memory-related settings:
* blockcachesize=419430400
* routerrpc.maxmchistory=10000

### Your environment

* lnd 0.14.0-beta-rc3
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Start lnd. Wait. 

### Expected behaviour

Memory usage stays below, say, 5G.

### Actual behaviour

Memory usage increases to 6.4G and more.

**Comment by Crypt-iQ** [comment]
How many channels does this node have? You could lower the blockcachesize and put the watchtower on a different machine

**Comment by C-Otto** [comment]
242 active channels, a few more in total
The watchtower server is on a different machine, but the watchtower client is on the same shown above. Or did I enable a server on this machine, too?

The block cache size is 419430400, which is 400 MByte. I don't think that would make a huge dent.

**Comment by Crypt-iQ** [comment]
Ah, so it's a client, yikes. Can you get the heap profile that shows the individual source-code lines?

**Comment by C-Otto** [comment]
https://c-otto.de/heap-1637001043.txt.gz

**Comment by C-Otto** [comment]
My node is rather busy, closing in on 50k fwds/month :)

**Comment by Roasbeef** [comment]
It looks like your node is busy serving _breaches_ constantly?

**Comment by Roasbeef** [comment]
Does the node also serve as a tower for other nodes?

**Comment by Crypt-iQ** [comment]
> It looks like your node is busy serving _breaches_ constantly?

https://github.com/lightningnetwork/lnd/blob/c4e55bbe6b19d53d5c7af946ab7d31237de08179/htlcswitch/link.go#L1893-L1904

**Comment by C-Otto** [comment]
> Does the node also serve as a tower for other nodes?

No.

> It looks like your node is busy serving breaches constantly?

`lncli closedchannels` doesn't show any breach, and I don't think a breach happened recently. The code looks like watchtower client stuff, though, maybe it's just updating a lot (with each transaction)? I have lots of failed HTLCs (routing failing further down the line, rebalancing).

**Comment by C-Otto** [comment]
I just noticed that my watchtower server stopped on Nov 8th. That might contribute? I just restarted it, let's see.

**Comment by C-Otto** [comment]
Something is happening. I see lots of CPU/disk activity on both sides, the bbolt database gets lots of small writes (I think), and memory is going down (after going up a bit when it started). I'd say we can close this issue? Do you want me to create a new issue (don't hold this stuff in RAM)?

![memory_1h](https://user-images.githubusercontent.com/344948/141851675-1b2ef747-be9e-448a-a362-23e933c34e67.png)

**Comment by Crypt-iQ** [comment]
I think queuing watchtower updates is an issue

**Comment by Roasbeef** [comment]
Thanks for looking into this, seems the memory queueing is indeed the issue. We should likely commit the queue to disk or just halt and regenerate the updates once the tower is back online.
