### ISSUE TITLE
Watchtower updates are queued in memory when tower is offline (memory leak)

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5983]
### Background

See #5979. My node was active, with lots of forwardings, failed HTLCs, ... During this time the configured watchtower was offline and, as such, didn't receive any updates. It seems that lnd queues those updates in memory, and only releases them once the watchtower re-appears.

See #5979 for more details (including a heap pprof file).

### Your environment

* lnd 0.14.0-beta-rc3
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Configure lnd as watchtower client. Stop watchtower server. Start lnd. Have lots of activity.

### Expected behaviour

Memory (RAM) usage is sane.

### Actual behaviour

Memory usage increases over time.

**Comment by Whiskey992** [comment]
Ty GM
