### ISSUE TITLE
Recovering funds when open channel transaction doesn't hit the mempool

### ISSUE THREAD

**Issue by WSBPrince** [lightningnetwork/lnd#5986]
### Background

lncli openchannel outputs a funding transaction but that transaction does not make it to the mempool. This is rare but has happened 2 times in about 150 opens. 

After which LND thinks those coins are spent and no longer recognizes them in wallet. I used flag -reset-wallet-transactions and can now see the funds in LND and are spendable however the failed open channels are still "pending."

Two questions:
1) Is there anyway to see the raw transaction so I can rebroadcast to the mempool (I won't do it in this case).
2) Since I_dont_know_what_im_doing, is using abandonchannel for the 2 pending / lost channels appropriate here (I think yes)?

### Your environment

* 0.13.3-beta
* Ubuntu 20.4
* bitcoind 22.0
* any other relevant environment details

### Steps to reproduce

Uncertain why it sometimes fails opening a transaction

### Expected behaviour

Raw transaction hits mempool

### Actual behaviour

Transactions gets lost

**Comment by Roasbeef** [comment]
If you've safely updated lnd's UTXO set state, then you can safely use the abandon channel call here to remove the pending channel (ONLY IF YOU KNOW IT DIDN't BROADCAST). 

If you _do_ want to see the raw transaction, then it would've been available in `lncli listchaintxns`. We attach a special label (https://github.com/lightningnetwork/lnd/blob/a329c8061266418bccd797aa5d7d277c736ee930/labels/labels.go#L61) for all channel opens. 

If the channel isn't hitting the mempool, then it may be the case that yuo're runing into mempool limits such as the ancestor limit.

**Comment by WSBPrince** [comment]
Thanks. The 2 failed transactions don't appear in lncli listchaintxns but they are there in pendingchannels. Any idea why this may occur? I tested with a new opening channel and while it was pending (and verified in mempool) I did see the openchannel label so know I am looking in the correct place.
