### ISSUE TITLE
Sending to invoice AND attaching data throws error

### ISSUE THREAD

**Issue by gcomte** [lightningnetwork/lnd#5989]
### Background

With `lncli sendpayment` you can pay an invoice (by using `pay_req=lnbc...`) or you can send some money without using an invoice by using the flag `--keysend`. When you use `--keysend` you may furthermore attach some data to the payment by using the `--data` flag.

However, when you send to an invoice and try to attach data there, you get a golang error:
`panic: assignment to entry in nil map`

Maybe there is no need to send data along with the payment when there you use invoices anyway and could just put your data into the invoice's `memo` field. But still, this could throw a cleaner error message than just the golang error.

### Your environment

* LND 0.13.4
* x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. Create an invoice on node A
2. On node B, run the following command: `lncli sendpayment --pay_req={INVOICE FROM NODE A} --data 3438382=0a21ff`

### Expected behaviour

Either it just works, or gives back an error message saying that the `--data` flag may only be used for keysend payments, but not when using invoices.

### Actual behaviour

Throws a Go error with stacktrace (`panic: assignment to entry in nil map`)

**Comment by guggero** [comment]
Thanks for the report! Fix is up.
