### ISSUE TITLE
"We're not running within systemd" when running within systemd

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#5996]
### Background

I'm running lnd with systemd. I noticed on a recent restart via `systemctl` that `We're not running within systemd` was printed in the logs. Also, the wallet did not automatically unlock in spite of `wallet-unlock-password-file` being set - I'm not sure if this is related.

### Your environment

* 0.14.0-beta.rc4
* 5.10.17-v8+ aarch64 GNU/Linux
* bitcoind 0.21

### Steps to reproduce

Restart lnd managed by systemd with `systemctl`.

### Expected behaviour

No "We're not running within systemd" message in the logs. Wallet unlocks automatically with `wallet-unlock-password-file`

### Actual behaviour

"We're not running within systemd" message appears in the logs. Walled required manual unlock.

**Comment by sangaman** [comment]
Just a note after investigating some more, it looks like my `lnd.conf` file within the lnd data directory was not loaded at all, which explains why the wallet was not unlocked (most noticeably the lack of alias). I restarted lnd again via systemctl and this time it *did* pick up the config and automatically unlock the wallet, however I still see the "We're not running within systemd" message in the logs.

**Comment by guggero** [comment]
Can you somehow verify that the `NOTIFY_SOCKET` is set for `lnd` when it's started with `systemd`? That's the env variable that is used to detect whether or not `lnd` was started by `systemd`.

**Comment by rkfg** [comment]
I had the same issue but then I googled this `NOTIFY_SOCKET` and found out the `Type` of the service should be `notify` and mine was `simple`. After changing it to `notify` lnd indeed reports that it sees systemd: `[INF] LTND: Systemd was notified about our readiness`

If OP's unit is setup with `notify` type and lnd still doesn't see systemd it's easy to check the env var with
```
cat /proc/`pidof lnd`/environ | tr '\0' '\n' | grep NOTIFY
```
for me it returns `NOTIFY_SOCKET=/run/systemd/notify`

**Comment by guggero** [comment]
Thank you @rkfg for looking into this.

Closing this since the fix seems to be adding `Type=notify` to the `[Service]` section of the `systemd` service description file.

**Comment by sangaman** [comment]
I will try the `Type=notify` line and report back next time I restart my node, thank you.

**Comment by sangaman** [comment]
I changed `Type=simple` to `Type=notify` and got `Systemd was notified about our readiness` in the lnd logs, so I can confirm that the fix works.

@guggero - would it make sense to have an example systemd service setup within the lnd repo or an associated "official" lnd documentation repo? Right now the only two such examples I can find online are in gists, and both of them use `Type=simple`. I would bet that a lot of lnd/systemd users out there aren't notifying systemd properly due to this.

**Comment by Kixunil** [comment]
Damn, looks like I wrote an unclear log message. Any ideas how to change it? Maybe "We're not running within systemd or service type isn't notify"?
