### ISSUE TITLE
Implement reservation zombie sweeper

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#60]
Currently within the wallet's `ChannelReservation` workflow any reservation which are partially started but not ultimately completed are never cleaned up, meaning the allocated resources will be active until a daemon restart. 

A "zombie sweeper" goroutine should be added which manually cancels reservations which haven't progressed for a certain "idle" period of time.

**Comment by AndrewSamokhvalov** [comment]
will take this one

**Comment by flaurida** [comment]
Can I take this? It seems like it would be a good issue to get my feet wet :)

**Comment by paddyquinn** [comment]
Looks like the last PR for this (#337) has been closed since Sep. 19th and the [master branch](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go) still has this as a TODO. Going to pick this one up as a first issue unless someone else is actively working on it.

**Comment by halseth** [comment]
I was planning to pick this up, but feel free to, as I haven't started yet! 😀

**Comment by stevenroose** [comment]
Seems like this one is solved.

**Comment by halseth** [comment]
Yep, solved by #782 👍

**Comment by paddyquinn** [comment]
Yup. This can be closed.
