### ISSUE TITLE
"missing feature dependency: 23" after upgrade to 0.14.0-beta

### ISSUE THREAD

**Issue by lightningbrie** [lightningnetwork/lnd#6002]
### Background

lnd would not start after upgrading to 0.14.0-beta.
The last part of the output of `journalctl -u lnd`:
```
lnd[21138]: 2021-11-18 21:05:12.001 [INF] CHRE: LightningWallet opened                                          
lnd[21138]: 2021-11-18 21:05:12.006 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
lnd[21138]: 2021-11-18 21:05:12.007 [INF] TORC: Starting tor controller                                         
lnd[21138]: 2021-11-18 21:05:12.009 [ERR] LTND: Shutting down because error in main method: unable to create server: invalid feature set SetInit: missing feature dependency: 23
lnd[21138]: 2021-11-18 21:05:12.009 [INF] TORC: Stopping tor controller                                         
lnd[21138]: 2021-11-18 21:05:12.010 [ERR] TORC: DEL_ONION got error: invalid arguments: unexpected code         
lnd[21138]: 2021-11-18 21:05:12.010 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
lnd[21138]: 2021-11-18 21:05:12.027 [INF] LTND: Shutdown complete                                               
lnd[21138]: unable to create server: invalid feature set SetInit: missing feature dependency: 23                
```

### Your environment

* version of `lnd`: 0.14.0-beta
* Linux 5.10.63-v7l+ armv7l GNU/Linux
* bitcoind v22.0
* go1.16.7
* Tor version 0.3.5.15

### Steps to reproduce
* checkout v0.14.0-beta
* make install tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc routerrpc watchtowerrpc monitoring"
* **have `protocol.no-anchors=true` in lnd.conf**

(note: after disabling the `protocol.no-anchors=true`-line in my lnd.conf, lnd did start-up)

### Expected behaviour
lnd should start

### Actual behaviour
lnd not starting up with log lines as pasted above

**Comment by Roasbeef** [comment]
Any particular reason you want to disable anchors? They make channels much safer as it ensures you can increase the fee in a force close scenario. Otherwise it's possible you end up in a state where you _can't_ even broadcast the transaction.

**Comment by Roasbeef** [comment]
If you do want to disable it, then you also want to set: `--no-script-enfroced-lease`.

**Comment by lightningbrie** [comment]
There wasn't a good reason for me to disable it: it was disabled in my lnd.conf, because I was experimenting with it. However, I think lnd still should not quit with an error if people do use the option.

**Comment by xpsx** [comment]
Does this problem related?

*** LAST 20 LNbits LOGS ***
sudo journalctl -u lnbits -b --no-pager -n20
-- Logs begin at Sat 2021-11-20 19:11:04 GMT, end at Sat 2021-11-20 19:26:42 GMT. --
Nov 20 19:14:33 raspberrypi systemd[1]: Started lnbits.
Nov 20 19:14:41 raspberrypi sh[12410]: /home/lnbits/lnbits/lnbits/app.py:63: RuntimeWarning:   × The backend for LndRestWallet isn't working properly: '{"code":2, "message":"waiting to start, RPC services not available", "details":[]}'
Nov 20 19:14:41 raspberrypi sh[12410]:   RuntimeWarning,
Nov 20 19:14:41 raspberrypi sh[12410]: [2021-11-20 19:14:41 +0000] [12413] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Nov 20 19:14:41 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=4/NOPERMISSION
Nov 20 19:14:41 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Nov 20 19:15:11 raspberrypi systemd[1]: lnbits.service: Service RestartSec=30s expired, scheduling restart.
Nov 20 19:15:11 raspberrypi systemd[1]: lnbits.service: Scheduled restart job, restart counter is at 4.
Nov 20 19:15:11 raspberrypi systemd[1]: Stopped lnbits.
Nov 20 19:15:11 raspberrypi systemd[1]: Started lnbits.
Nov 20 19:15:19 raspberrypi sh[15025]: /home/lnbits/lnbits/lnbits/app.py:63: RuntimeWarning:   × The backend for LndRestWallet isn't working properly: '{"code":2, "message":"the RPC server is in the process of starting up, but not yet ready to accept calls", "details":[]}'
Nov 20 19:15:19 raspberrypi sh[15025]:   RuntimeWarning,
Nov 20 19:15:19 raspberrypi sh[15025]: [2021-11-20 19:15:19 +0000] [15042] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Nov 20 19:15:19 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=4/NOPERMISSION
Nov 20 19:15:19 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Nov 20 19:15:49 raspberrypi systemd[1]: lnbits.service: Service RestartSec=30s expired, scheduling restart.
Nov 20 19:15:49 raspberrypi systemd[1]: lnbits.service: Scheduled restart job, restart counter is at 5.
Nov 20 19:15:49 raspberrypi systemd[1]: Stopped lnbits.
Nov 20 19:15:49 raspberrypi systemd[1]: Started lnbits.
Nov 20 19:15:57 raspberrypi sh[16418]: [2021-11-20 19:15:57 +0000] [16419] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)

**Comment by lightningbrie** [comment]
I applied https://github.com/Roasbeef/lnd/commit/979b67fc1d999dba124d657d21399faf130514a5 as a patch and found it fixes the issue.
