### ISSUE TITLE
LookupInvoiceV2 grpc response inconsistency

### ISSUE THREAD

**Issue by xraid** [lightningnetwork/lnd#6008]
Using https://api.lightning.community/#lookupinvoicev2

`invoices.lookupInvoiceV2({payment_hash: xxx}, function (err, response) {`

A AMP Invoice (created with a 0.14.0-beta) paying a with a 0.13.4-beta, i get a response inconsistency in 
amp_invoice_state: {} returns set_id:  with and without ampersands in list for diff records

while `lncli lookupinvoice r_hash: xxx` returns ampersands correctly

my understanding is lncli use grpc to LND so somewhere the impl of JS grpc seems use different functions typecasting differently ?

**Comment by guggero** [comment]
> returns set_id: with and without ampersands

I don't know what you mean with that. _Sounds_ like an encoding problem. But can you give an example please? What ampersand are you referring to?

**Comment by xraid** [comment]
here is a `lookupInvoiceV2(payment_hash)` where out of 5 only 2 have single ampersands.

JS still reports key as string regardless . probably a grpc lib thing ?

amp_invoice_state: {
    '4352cbd3cffe5707c8ba2a45c1e60583a6c906da785459966b05485f92b80726': {
      state: 'SETTLED',
      settle_index: '242',
      settle_time: '1637432584',
      amt_paid_msat: '1001000'
    },
    dbbeeee98f3c6053ad75152e5dbb7f50b43e9893ce1e9a0ac035cf3befb78de0: {
      state: 'SETTLED',
      settle_index: '238',
      settle_time: '1637413586',
      amt_paid_msat: '1001000'
    },
    e393ad6d6b7a9dc874a88602e6590aa5bf0490bf4d6e7f33d16b015f8b66fcd8: {
      state: 'SETTLED',
      settle_index: '239',
      settle_time: '1637413645',
      amt_paid_msat: '1001000'
    },
    '4e8f28cacf72ca6a677de15ea780c151aabaacf1ec13788a672fa66ec6e9b074': {
      state: 'SETTLED',
      settle_index: '240',
      settle_time: '1637414642',
      amt_paid_msat: '1001000'
    },
    a232ad0869facadf5f8074f72336287e7ec7fac4cf0b9c5c34366769b700a9ef: {
      state: 'SETTLED',
      settle_index: '241',
      settle_time: '1637414684',
      amt_paid_msat: '1001000'
    }
  },

**Comment by guggero** [comment]
For JS everything that isn't a number is handled as a string. So yes, things will be formatted differently between `lncli` and JS. Also make sure you use the correct proto files (most recent ones) when using JS. If you use an old version, then new fields such as the `amp_invoice_state` might not be filled.
Or are you saying the actual _content_ is different between `lncli` and JS?

BTW, AMP stands for Atomic Multipath Payments and has nothing to do with ampersands (the character).

**Comment by xraid** [comment]
hehe ampersand the (the character)

so my Atomic Multipath Payment Invoice get payed to a 14 node that has a node.js with latest proto reporting a responce with inconsistent formatting ... why ... 

now it seem be harmless when parsing, but the inconsistency is not explained ...

thanks

**Comment by guggero** [comment]
I still don't understand the inconsistency, I think. Can you post exactly what looks different? And what you expect? What is the output of `lncli`?

**Comment by xraid** [comment]
'4352cbd3cffe5707c8ba2a45c1e60583a6c906da785459966b05485f92b80726': 
dbbeeee98f3c6053ad75152e5dbb7f50b43e9893ce1e9a0ac035cf3befb78de0: 

with without above !

lncli reports correctly with (") for all
node.js grpc reports with random skips for (')

**Comment by guggero** [comment]
Ah, now I see it. It looks like if the hex starts with a digit, it's printed with single quotes, if it starts with a letter the single quotes are skipped. That's probably not even the grpc library but the print method you use. Are you using `console.log()` or `console.dir()`?
Try `JSON.stringify(xyz, null, 2)`, that should make it uniform.

Closing this as it's a node.js issue.

**Comment by xraid** [comment]
console  log or dir no diff

JSON.stringify(xyz, null, 2) really comfumbles it

ok so i was hesitant before the parse test, and as it is still strings, no unexpected hidden bug will be needed taken care of.
thanx for explaining the letter or num start of line that would in grpc probably format differently.
