### ISSUE TITLE
Don't send the Locked CSV Output to a new address after Locktime expires

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6010]
### Background

Most channel force closes happen because of some connectivity issues between both peers. Therefore I would call it a proper Force Close where nobody whats to cheat the other party but instead wants to recover his funds, which are stuck in a limbo state which cannot be recovered. The funds which belong to the closing party are timelocked with a CSV. When the CSV expires the output is sent "forward looking" to a P2WKH address. This is an additional Transaction which in my view is not necessary, because funds are also safu in the P2WSH address of the closing Transaction. In a high fee environment this can be very expensive without really a reason to do so. In addition sending the funds from this CSV output when a false channel state is broadcasted and not detected by the counterparty would mean the funds are stolen which should not be supported by default by the software. 

I suggest the option to run lnd in a conservative mode, where only those transaction are made which are absolutely necessary  and at the lowest fee possible. So a lnd.conf entry could be imaginable. 
### Your environment

* version of `lnd`: 0.14.0-beta
* which operating system (`uname -a` on *Nix): Linux (raspiblitz)
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details: anchor channel

### Steps to reproduce

A force close of a anchor channel. After the CSV of the output expires an additional TX is created which sends this output to the lnd wallet

### Expected behaviour

The force close should happen and let the CSV output reside where it is becaue safety is not an issue here.

### Actual behaviour

The Transaction is send from the P2WSH output to a P2WPKH output without needing it concerning the safety of funds

**Comment by guggero** [comment]
> because funds are also safu in the P2WSH address of the closing Transaction

That is not really true. The time lock is there to give the other party time to enforce the justice mechanism. Meaning the same output also has a revocation script path that is not time locked and can be taken by the other party if they learn the [`per_commit_secret`](https://github.com/lightning/bolts/blob/master/03-transactions.md#remotepubkey-derivation). In a normal force close (e.g. with no intention of cheating) the other party doesn't have that secret, true. But leaving funds in an UTXO where theoretically another party does have keys to isn't really safe.

The other argument for sweeping is: To sweep the time locked output, you need to know the exact script used for the UTXO. That script contains [three variables](https://github.com/lightning/bolts/blob/master/03-transactions.md#commitment-transaction-outputs) of which one is computed with a key from the other party. So how would you go about recovering that transaction in case of a node crash? Not sweeping that UTXO would mean you'd need to keep another file around that backs up all scripts ever used. That could be integrated into the channel backup, but it doesn't really sound like a good idea to me.

**Comment by ziggie1984** [comment]
Thanks for this detailed description. 

You are right, one has to consider the scenario one is in and how the mempool is filled up. 

I have two follow up questions:

1. Does the LND wallet try to aggregate sweeping UTXOs, meaning that for example I have a _to_local output and several HTLCs outputs with different cltv_expiry dates, does LND wait and make one final sweeping TX or will it sweep every output as soon as the CLTV expires ? Would be cool to have a kind of "Expired UTXO Collector"

2. Is this sweeping part of the BOLTS, because I could not find it. Or is it not really a hard requirement and does LND consider all 3 Transactions (Commitment Output, HTLC (Succes/Timeout) and Sweeping TX when Trimming an Output ?

**Comment by guggero** [comment]
We do have a general purpose sweeper (see `sweep` package) that is fee aware and tries to batch sweeps together. It can also fee bump sweeps through RBF.
I don't think sweeping is part of the BOLTS, it's more of a general good practice tip when dealing with script outputs in bitcoin.

**Comment by ziggie1984** [comment]
OK so I guess there is no real interest in giving the user the possibility to keep their P2WSH output instead of sweeping it. Would increase the complexity of the codebase. (As a routing node running I would prefer to immediately use those P2WSH Output to open another channel immediately). I would then close this issue if you are ok with that @guggero ?

**Comment by ziggie1984** [comment]
Closed the issue, because an UTXO sweeped of a P2WSH address is more safe and can be restored form a single seed in case your node chrashes!
