### ISSUE TITLE
link test mentions incorrect build tags to fix certain tests failing

### ISSUE THREAD

**Issue by greywolve** [lightningnetwork/lnd#6020]
Hi :)

I'm new to the project and was trying to run some tests.

Attempting to run `go test ./htlcswitch` returns:

```         
--- FAIL: TestChannelLinkBandwidthConsistency (0.00s)
    link_test.go:2173: htlcswitch tests must be run with '-tags debug
--- FAIL: TestChannelLinkTrimCircuitsNoCommit (0.00s)
    link_test.go:2907: htlcswitch tests must be run with '-tags debug
--- FAIL: TestChannelLinkCleanupSpuriousResponses (1.24s)
    link_test.go:5162: alice fwdpkg index 0 should not have ack
--- FAIL: TestSwitchDustForwarding (17.43s)
    switch_test.go:3388: 
        	Error Trace:	switch_test.go:3388
        	Error:      	Target error should be in err chain:
        	            	expected: "dust threshold exceeded"
        	            	in chain: 
        	Test:       	TestSwitchDustForwarding
FAIL
FAIL	github.com/lightningnetwork/lnd/htlcswitch	108.933s
FAIL
```
Following the recommended resolution:

```
go test ./htlcswitch -tags debug
# github.com/lightningnetwork/lnd/build
build/log.go:88:39: undefined: LogLevel
FAIL	github.com/lightningnetwork/lnd/htlcswitch [build failed]
```

I dug through the Makefile and realised I needed to add the 'dev' tag. `go test ./htlcswitch -tags dev` works.

I'm guessing this is just an outdated hint that needs updating. :)

**Comment by guggero** [comment]
The recommended way to run the tests is through `make unit`. So for example `make unit pkg=htlcswitch` in your case. Where did you see the outdated documentation?

**Comment by greywolve** [comment]
@guggero thanks for the tip. :) It was just an outdated hint in the test code. Sent a PR to fix, though maybe that hint should just be removed entirely if make is the way to run tests?

**Comment by guggero** [comment]
I think the PR is okay for now.
