### ISSUE TITLE
walletrpc.ListUnspent RPC needs sane default values for max_confs and min_confs

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#6028]
REST API /v2/wallet/utxos is returning empty array after upgrading the LND to 0.14.1

It was returning the list of utxos before this upgrade and lncli still returns the correct utxo list.

**Comment by guggero** [comment]
The parameters `min_confs` and `max_confs` have been added. Unfortunately they don't have any internal default values, so they fall back to 0. You should get the UTXOs if you specify `max_confs: 9999999`. If you don't want to see unconfirmed UTXOs, also add `min_confs: 1`.

Keeping the issue open to add some sane default values.

**Comment by ShahanaFarooqui** [comment]
@guggero I was using max_confs param till 0.13.1 release and it was working fine. I tried all these values but it is always returning the empty array.

**Comment by guggero** [comment]
I just tested this locally with `v0.14.1-beta` and I do get UTXOs when I send `{max_confs: 9999999}`.
What does `lncli listunspent` show? Can you somehow log the full request you're sending?

**Comment by ShahanaFarooqui** [comment]
Till v0.13.1, `min_confs` and `max_confs` were passed as query parameters and now they have been moved to body. So I kept trying with the same without realizing this tiny change. After moving the parameters from query to body, I am able to receive the data. Please let me know if I can close the issue or you want to keep it open for default values addition.

**Comment by guggero** [comment]
Aaaah, that explains it. There was an annotation missing in the REST configuration. That's why previously the parameters weren't read from the POST body correctly.
Thanks for figuring this out!

Just out of curiosity: Do the POST body parameters also work with lnd v0.13.x?

I'm leaving the issue open so someone can add default values.

**Comment by ShahanaFarooqui** [comment]
@guggero, body params were not working till 13 only query params.

**Comment by ErikEk** [comment]
I can take a look at it.
