### ISSUE TITLE
Enable URI encoding for /v2/invoices/subscribe API

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#6029]
The api `/v2/invoices/subscribe` accepts `r_hash` in base64 and returns `Not found` error whenever the request is sent with either special character `/` or `%2F`.

Or

The request should accept r_hash in `hex`.

**Comment by guggero** [comment]
Unfortunately, we can't change that since it's a limitation of the REST proxy library we use.
Fortunately it's an easy fix on the encoding side.
From the [API docs](https://api.lightning.community/#lnd-rest-api-reference):

> NOTE: The byte field type must be set as the base64 encoded string representation of a raw byte array. Also, any time this must be used in a URL path (ie. `/v1/abc/xyz/{payment_hash}`) the base64 string must be encoded using a URL and Filename Safe Alphabet. This means you must replace `+` with `-`, `/` with `_`, and keep the trailing `=` as is. Url encoding (ie. `%2F`) will not work.
