### ISSUE TITLE
upgraded to zap wallet but unable to open a channel

### ISSUE THREAD

**Issue by shedy360** [lightningnetwork/lnd#6038]
### Background
I am unable to open/create a new channel on my newly installed zap desktop app, please i  would really appreciate a way to get my on chain btc off the wallet as the money was meant for a payment that i am unable to do because of the channel problem.
Describe your issue here.

### Your environment
windows 10

* version of `lnd`
* which operating system (`uname -a` on *Nix) windows
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

keep getting error messages
![WhatsApp Image 2021-11-30 at 07 36 54](https://user-images.githubusercontent.com/57156817/143959639-14bac7cd-443f-4298-92af-41e241bef72b.jpeg)
![WhatsApp Image 2021-11-30 at 07 36 55](https://user-images.githubusercontent.com/57156817/143959651-a5254de5-9179-4347-8fdf-e6feba04ca82.jpeg)
d

**Comment by Roasbeef** [comment]
The attempt failed as the other party wasn't reachable. 

This isn't the Zap tracker though, and this doesn't appear to be an lnd specific issue, so closing this for now.
