### ISSUE TITLE
`synced_to_chain` is always `false`

### ISSUE THREAD

**Issue by fiatjaf** [lightningnetwork/lnd#6046]
### Background

`getinfo` says `synced_to_chain: false` always, and most of commands don't work because of that.

For example, `restorechanbackup` returns `[lncli] unable to restore chan backups: rpc error: code = Unknown desc = server is still in the process of starting`.

### Your environment

* version of `lnd`: 0.14.1 (but also tried on 0.14.0 and some 0.13.x version)
* which operating system (`uname -a` on *Nix): 5.14.3-arch1-1 
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Knots version v0.21.1.knots20210629
* any other relevant environment details: using mainnet now, but also tried a regtest node some days ago and was unable to fund a channel because `channels cannot be created before the wallet is fully synced`. On regtest I tried to mine many blocks etc., was able to get funds on my lnd wallet and it showed logs saying it was processing each new block/transaction being created:

![image](https://user-images.githubusercontent.com/1653275/144327090-f0461262-d9e4-485a-96b4-24255a6c9206.png)

### `getinfo` output

```json
{
    "version": "0.14.1-beta commit=v0.14.1-beta",
    "commit_hash": "6042004edaaa5b3cad0a0808ff23dba4716f7178",
    "identity_pubkey": "027e5b8114a0f05fcfcbf6f765def839005e54be7bd1a3cccca921df19237d0462",
    "alias": "027e5b8114a0f05fcfcb",
    "color": "#3399ff",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 0,
    "num_peers": 0,
    "block_height": 712142,
    "block_hash": "0000000000000000000ac796edf4aa14a37fc8dedcd5d2384e6081369acd635d",
    "best_header_timestamp": "1638398554",
    "synced_to_chain": false,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "mainnet"
        }
    ],
    "uris": [
    ],
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "12": {
            "name": "static-remote-key",
            "is_required": true,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        },
        "23": {
            "name": "anchors-zero-fee-htlc-tx",
            "is_required": false,
            "is_known": true
        },
        "30": {
            "name": "amp",
            "is_required": true,
            "is_known": true
        },
        "31": {
            "name": "amp",
            "is_required": false,
            "is_known": true
        },
        "45": {
            "name": "explicit-commitment-type",
            "is_required": false,
            "is_known": true
        },
        "2023": {
            "name": "script-enforced-lease",
            "is_required": false,
            "is_known": true
        }
    }
}
```

### `lnd.conf` contents

```
[Application Options]
listen=0.0.0.0:9732
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8088
maxpendingchannels=3
minchansize=10000
accept-keysend=true
allow-circular-route=1

[Bitcoind]
bitcoind.rpchost=10.147.17.69
bitcoind.rpcuser=fiatjaf
bitcoind.rpcpass=fiatjaf
bitcoind.zmqpubrawblock=tcp://10.147.17.69:28332
bitcoind.zmqpubrawtx=tcp://10.147.17.69:28333

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.defaultchanconfs=1
```

**Comment by Roasbeef** [comment]
> For example, restorechanbackup returns [lncli] unable to restore chan backups: rpc error: code = Unknown desc = server is still in the process of starting.

Is this an older node, or one that was offline for some time and is just now being restarted? 

You'll get that message if the wallet is still catching up to the current tip of the main chain. If the node has been offline for several days/weeks, this could take a bit of time.

**Comment by fiatjaf** [comment]
The node is fully synced, yes.

I'm trying to restore an old node for which I found a backup, so maybe it is that? In this case would be nice to have some indication of that status on `getinfo`, because currently my `getinfo` shows the current block there: `"block_height": 712142,`.
