### ISSUE TITLE
Unconfirmed Sweep gets rebroadcasted with the same fee and bumpfee function is not broadcasting the transaction with higher fees

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6047]
### Background

When a force close happens, Outputs are sweeped. The remote party closed the channel with me, my ("to_remote", from the perspective of the remote node) value was immediately accessible to the wallet. It was swept with 1 sats/vbyte. Now I had two problems which I don't understand especially what lnd does under the hood:

1. The sweep kept rebroadcasting (up to 7 times) with 7 different TXids but the same fee, so this rebroadcasting was not a RBF but something I don't understand.` lncli wallet pendingsweeps` was only showing the output of the commitment TX.
2. When I tried bump the fee manually with lncli wallet bumpfee --sats_per_vbyte XX output:index the output was and empty array when retrying the command `lncli wallet pendingsweeps ` it showed the following:

```
admin@raspberrypi:~ $ lncli wallet pendingsweeps
{
        "pending_sweeps": [
                {
                        "outpoint": "????",
                        "witness_type": "UNKNOWN_WITNESS",
                        "amount_sat": ????,
                        "sat_per_vbyte": 3,
                        "broadcast_attempts": 9,
                        "next_broadcast_height": 712212,
                        "requested_sat_per_vbyte": 3,
                        "requested_conf_target": 0,
                        "force": false
                }
        ]
}
```

Why is the witness_type unknown ? It showed a new sat_per_vbyte value (3), but after the rebroadcast height of 712212 passed this TX was not broadcasted. 

How I fixed my issue: I got the raw TX from the command `lncli listchaintxns` and broadcasted it with `bitcoin-cli sendrawtransaction "hex"`

Seems like something is not really working on LND wallet side.

### Your environment

* version of `lnd`: 0.14.0
* which operating system  raspiblitz
* version of  `bitcoind` : 22.0

### Steps to reproduce
Problem 1. Create a sweep TX which is not confirmed for severaal blocks and see whether LND is creating a lot of new sweep TX for the same output and the same TX fee.
Problem 2. Force Close a channel and let the funds which are available immediately be sweeped and then try to bump the fee, bumped TX will not be broadcasted

### Expected behaviour
Problem1: Either the TX is created with higher Fees as an RBF TX or the original sweep is kept. So that my local balance is not flooded with unconfirmed Sweeping TX which all use the same fee.
Problem2: If all checks are good and RBF rules are met, broadcast the transaction or raise an error that the TX is not broadcasted

**Comment by Roasbeef** [comment]
> The sweep kept rebroadcasting (up to 7 times) with 7 different TXids but the same fee, so this rebroadcasting was not a RBF but something I don't understand.

This is part of the design of the sweeper: it assumes it might receive conflicting or invalid input sets, and will back off and attempt to retry diff combinations of them as needed. it also re-queries for the current fee estimate for the target confirmation interval, which may results in more than one transaction being _attempted_ to be broadcast. 

> Why is the witness_type unknown ? It showed a new sat_per_vbyte value (3), but after the rebroadcast height of 712212 passed this TX was not broadcasted.

Unknown simply because it isn't filled in right now, and the proto is re-used elsewhere. 

The sweeper operates with a default 8 minute timer, so maybe it just hadn't retried before you broadcasted things?

**Comment by ziggie1984** [comment]
Closing this because this is how the sweeper works normally. To check why a sweep is not getting confirmed there might be a problem with the bundling of different sweeps which are already in the local mempool and might therefore get rejected by the mempool. This relates to #7933
