### ISSUE TITLE
Allow to stop announcing a channel without closing channel.

### ISSUE THREAD

**Issue by mh-ash** [lightningnetwork/lnd#6055]
Allow to stop announcing a channel without closing channel. (Aka the ability to make an existing public channel private).

**Comment by BhaagBoseDK** [comment]
would be a great change.
also it should be possible to change local_max_htlcs and other static properties of a channel without closing.

**Comment by Roasbeef** [comment]
Not possible without a spec change, but even then you can't guarantee people delete the information of the previously public channel. The [`UpdateChanStatus`](https://api.lightning.community/#updatechanstatus) call can be used to _disable_ the channel on your side.
