### ISSUE TITLE
unable to start server: unable to query fee estimator: web API does not include a fee estimation for block target of 1

### ISSUE THREAD

**Issue by SeverinAlexB** [lightningnetwork/lnd#6056]
### Background

One of my client node was unable to start because it requested a fee estimation for block target 1. See the [incident report](https://severinalexb.github.io/personal-blog/2021/12/05/Indicent-Report.html) for more background information.

Logs:
```
[ERR] CNCT: ChannelArbitrator(*****): unable to advance state: unable to query fee estimator
: web API does not include a fee estimation for block target of 1
unable to start server: unable to query fee estimator: web API does not include a fee estimation for block target of 1
```

### Your environment

* version of `lnd`: 0.13.4
* which operating system (`uname -a` on *Nix): Linux Nuc9 5.11.0-41-generic~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend : Neutrino

### Steps to reproduce

The node was down for some time and needed to react quickly to channel force-closes. See related incident report.

### Expected behaviour

Only request estimations for block >= 2 or provide estimations for block 1.

### Actual behaviour

Node didnt start anymore.

**Comment by Roasbeef** [comment]
The problematic area in the code: https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L1285

Which API were you using as an estimator?

**Comment by yyforyongyu** [comment]
> See the incident report for more background information.

Report read. So you end up writing a customized web API? I think we may add default values plus warnings when the fee estimator cannot give result for a given conf target.

**Comment by SeverinAlexB** [comment]
> Which API were you using as an estimator?

https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json


> Report read. So you end up writing a customized web API? I think we may add default values plus warnings when the fee estimator cannot give result for a given conf target.

Default values please! Customized web API sounds a bit too fancy for what I did. Copy/past `btc-fee-estimates.json`, add value for block 1, upload it to my personal web server and change feeurl config to this new url. Start lnd, wait until everything is resolved, change back to default fee estimation url.
