### ISSUE TITLE
Linux open file limit

### ISSUE THREAD

**Issue by SeverinAlexB** [lightningnetwork/lnd#6057]
### Background

One of my clients node ran into extended downtime and experienced the loss of half of its channels due to an Linux open file limit issue and a resulting wallet.db corruption.

I will describe the relevant informations for the issue here. See the [incident report](https://severinalexb.github.io/personal-blog/2021/12/05/Indicent-Report.html) for more background information.

These errors showed up

```
[ERR] BTCN: Can't accept connection: accept tcp [::]:9733: accept4: too many files open
[ERR] LTND: Unable to lookup witness: no witnesses
[ERR] NTFN: Failed getting UTXO: get utxo request cancelled
[ERR] NTFN: Failed to update rescan progress: database not open
[WRN] LNWL: Unable to remove invalid transaction **transactionId**: database not open
[ERR] NTFN: Failed to update rescan progress: database not open
```

Specifically `BTCN: Can't accept connection: accept tcp [::]:9733: accept4: too many files open` hints to an open file limit problem.

After increasing the limit from 1024 to 16384 the `too many files open` error didn't show up anymore. I was able to fix the `database not open` error with `--reset-wallet-transactions`. I strongly assume the wallet.db corruption was a result of the open file limit.

Related issues:
 - #1631
 - #4821
 

### How to increase the limit

Increase systemd limit: Set `LimitNOFILE=16834` in your service unit file.
Increase user terminal limit: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

### Your environment

* version of `lnd`: 0.13.4
* which operating system (`uname -a` on *Nix): Linux Nuc9 5.11.0-41-generic~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Neutrino
* any other relevant environment details

### Steps to reproduce

Run LND (possibly with Neutrino) with enough channels/peers.

### Expected behaviour

I request some measurements to prevent this as this issue can have nasty consequences.
Proposals:

- Check open file limit on lnd start. Bitcoin Core already does this for example.
- Graceful shutdown in case the open file limit is hit.
- Adding an open file limit section in the documentation.

Implementing one of these proposals is probably enough.

### Actual behaviour

LND runs into the open file limit and starts to behave unexpectedly with database corruption risk.
This issue might also be a security risk. Attackers can open many new TCP connections (open files) to a node, corrupt the database, and therefore bring the node down.

**Comment by Roasbeef** [comment]
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/5330
