### ISSUE TITLE
bbolt: improve startup time by tweaking disk access when loading channel.db

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6059]
### Background

When I restart my node (without compaction) lnd is able to read the `channel.db` file with about 15 MByte/sec. As my DB has a size of around 10 GByte, this part of the boot process takes around 10 minutes.

I noticed that I can massively improve startup time by, for example, issuing `pv channel.db > /dev/null` (or `cat channel.db > /dev/null`), which reads the file with several 100 MByte/sec. My system has 16 GByte of RAM, i.e. (most of) the channel db fits into memory.

Please consider tweaking the disk access for the initial DB load accordingly. 

### Your environment

* lnd-0.14.1-beta
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Start lnd with a channel db of ~10 GByte (after compaction).

### Expected behaviour

Initial steps (up to unlocking the wallet) take a minute or so.

### Actual behaviour

Initial steps (up to unlocking the wallet) take more than 10 minutes.

**Comment by Roasbeef** [comment]
> Please consider tweaking the disk access for the initial DB load accordingly.

This is a hardware level matter (disk I/O). If you want to increase start up time, you can opt to sync the free list, which trades off for slower writes once the database becomes larger. Reading the free list within the database involves operations other than just disk I/O. Any optimization there would need to come from `bbolt` itself. 

As the replicated DB backends we support start to mature, they'll allow users to by pass the current long start up time for larger nodes. 

> My system has 16 GByte of RAM, i.e. (most of) the channel db fits into memory.

bolt doesn't load the entire db into resident memory, instead it uses memory-mapping to address the entire DB in virtual memory space.

**Comment by Roasbeef** [comment]
Also once we carry this out, a ton of the unnecessary data on disk will be eliminated: https://github.com/lightningnetwork/lnd/issues/5388

**Comment by C-Otto** [comment]
I disagree, this isn't (just) a hardware matter, as made obvious by my improvement which only involved software. It seems lnd/bbolt issues lots of smaller read requests, which aren't served as fast as larger requests. Please reopen this issue and consider reading the DB file in larger chunks (readahead?).

Related topic for nginx (webserver): https://serverfault.com/questions/935482/how-to-reduce-io-wait-when-serving-large-static-files-on-nginx

**Comment by Roasbeef** [comment]
> Please reopen this issue and consider reading the DB file in larger chunks (readahead?).

"reading the free list within the database involves operations other than just disk I/O. " 

I think the `bbolt` issue tracker is the proper place for this, we don't do anything in `lnd` other than call `db.Open`, any changes to `bbolt` itself would need to be tracked there and made to the DB project itself.
