### ISSUE TITLE
Logging (pathfind): Don't log [WRN] CRTR: Channel x has zero cltv delta

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6069]
### Background

Inspired by https://github.com/C-Otto/rebalance-lnd/issues/241.

As part of pathfinding, lnd might encounter edges that have a policy specifying a zero CLTV delta (possibly because of no/outdated gossip?). Every time an edge like this is used in the pathfinding code, a warning is logged: https://github.com/lightningnetwork/lnd/blob/290b78e700021e238f7e6bdce6acc80de8d0a64f/routing/pathfind.go#L705

For nodes that query a lot of routes (for example when running `rebalance-lnd`), countless warnings are logged. These warnings don't seem to serve a proper purpose, as the user cannot do anything about it, and in my experience this also didn't cause any issues.

### Your environment

* lnd-0.14.1-beta
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Run QueryRoutes a few times.

### Expected behaviour

Warning from issue title is not logged.

### Actual behaviour

Warning from issue title is logged quite often.

**Comment by ErikEk** [comment]
I can fix it if we want this change.

**Comment by sloorush** [comment]
Hey!
I am interested in working on this issue, but could someone please explain what exactly needs to be done as PR #6242 was not accepted, which removes the check and the log.

**Comment by ziggie1984** [comment]
Closing with https://github.com/lightningnetwork/lnd/pull/7267
