### ISSUE TITLE
ACINQ channel switches to inactive, can't re-activate

### ISSUE THREAD

**Issue by vindard** [lightningnetwork/lnd#6079]
### Background

Shortly after channel with ACINQ opens it switches to inactive. If I disconnect the peer and reconnect I get the following. Is there any obvious issue you all can see here?
```
Dec 12 00:14:20 raspibolt lnd[29545]: 2021-12-12 00:14:20.582 [INF] DISC: Broadcasting 148 new announcements in 15 sub batches
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.150 [INF] SRVR: Established connection to: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.150 [INF] SRVR: Finalizing connection to 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735, inbound=false
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.650 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(<redacted-chan-point>)
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.651 [INF] HSWC: Removing channel link with ChannelID(<redacted>)
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] HSWC: ChannelLink(<redacted-chan-point>): starting
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] HSWC: Trimming open circuits for chan_id=<redacted>, start_htlc_id=1
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] HSWC: Adding live link chan_id=<redacted>, short_chan_id=<redacted>
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] NTFN: New block epoch subscription
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(<redacted-chan-point>)
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] PEER: Negotiated chan series queries with 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] DISC: Creating new GossipSyncer for peer=03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.652 [INF] HSWC: ChannelLink(<redacted-chan-point>): HTLC manager started, bandwidth=1543922015 mSAT
Dec 12 00:14:21 raspibolt lnd[29545]: 2021-12-12 00:14:21.653 [INF] HSWC: ChannelLink(<redacted-chan-point>): attempting to re-synchronize
Dec 12 00:14:25 raspibolt lnd[29545]: 2021-12-12 00:14:25.264 [INF] PEER: unable to read message from 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735: unable to parse message of unknown type: <unknown>
```

### Your environment

- Raspbian Buster 10 with `lnd v0.14.1-beta`

**Comment by Roasbeef** [comment]
> Dec 12 00:14:25 raspibolt lnd[29545]: 2021-12-12 00:14:25.264 [INF] PEER: unable to read message from 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735: unable to parse message of unknown type: <unknown>

So this looks fine: we ignore unknown messages and continue reading anything after that. 

If you go to `PEER=debug` logging, does it print out the message type we don't know about?

Do you see this behavior with each new channel?

Do you have logs during/after the eventual disconnect? Active/inactive here is based on if both sides send and receive the channel re-establish message.

**Comment by vindard** [comment]
It's only with ACINQ so far, and that channel was opened and then had a stuck htlc just before I upgraded to v14.1 from v11.1. 

I've since force-closed the channel and need to re-open it again once the force-close txn clears. I can try again and let you all know here if I still am seeing the issue.

**Comment by Roasbeef** [comment]
Great, thanks, will re-open this issue if we get any other additional informatio. 

This PR recently merged fixes an issue that would cause "competing" connection requests to sort of wipe each other out: https://github.com/lightningnetwork/lnd/pull/6082
