### ISSUE TITLE
LND v0.14.1-beta running high CPU

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#6090]
### Background

Running several nodes on version v0.14.1-beta, one of the nodes is running "hot"

### Your environment

running in docker on ubuntu 20.04/ec2/aws
Verified the disk i/o is not at high utilization.

### Steps to reproduce
- run lnd
- `curl http://localhost:<PORT>/debug/pprof/profile` to get cpu profile
### Expected behaviour

I'm unsure if LND needs more CPU, or if something is wrong. I've attached a picture of the cpu profile. I also have the cpu trace if that I can share privately if needed.

### Actual behaviour

High CPU, hopefully this profile graph pic helps

[png of profile graph](https://github.com/miketwenty1/images/blob/master/outhighcpu.png?raw=true)

**Comment by guggero** [comment]
Is this running with freelist sync on? From the profile it looks that way. A compaction should help (or turning off freelist sync).

**Comment by miketwenty1** [comment]
You're correct was using freelist sync. I'll set this to false and rerun LND, will open a new issue if I see this issue again.
