### ISSUE TITLE
Add private status or channel flags to opening pending channels

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#6100]
In the output of list channels the private/public status of the channel is returned, but in the output of pending channels the status is not revealed. To allow for recognizing a pending open channel as a private requires waiting for the channel to confirm.

Ideally the `PendingChannelsResponse` would include the channel flags or the private/public status of the channel to know which type of channel is opening.

### Your environment

* lnd 0.14.1

### Workaround

A way to find the status of an incoming pending channel is to intercept open channel requests with the `ChannelAcceptor` API. This API reveals the bit flag features of the channel and through this the private or public status can be ascertained.

**Comment by tvolk131** [comment]
@madskrogh this was fixed with #6167, right? Or is there still more work to be done?

**Comment by guggero** [comment]
Yes, fixed by #6167.
