### ISSUE TITLE
Unhandled error while reforwarding htlc settle/fail over htlcswitch: UnknownNextPeer

### ISSUE THREAD

**Issue by xjmzx** [lightningnetwork/lnd#6115]
### Background

I force closed a channel several days ago, still shows pending. Checked logs after restarting lnd and found the error in the title: Unhandled error while reforwarding htlc settle/fail over htlcswitch: UnknownNextPeer

I'm not 100% this relates to the error, but there seems no other issues during start up

When looking at the pending channel in  Thunderhub, the details seems pretty strange

Force Closed             Yes
Total locked time       4972d 23h 10m (716107 blocks)
Pending locked time 1d 11h 20m (212 blocks)
State:                          Inactive
Status:                        Closing
Local Balance:            446236
Node Public Key:       033a83...
Transaction Id:           7de7f0...
Transaction Vout:      1
Close Transaction Id: ecd4c6...
Partner Node Info     Node Capacity: 17500000
Channels:                  20
Last Update:             3 days ag ...

### Your environment

lnd: 0.14.1-beta commit=v0.14.1-beta
macos: 12.1
bitcoind: 229900

This is the first time I have noticed the error and monitoring.

### Expected behaviour

Pending force close should have been completed. No error in logs

### Actual behaviour

Channel seems to be hanging with limbo balance indefinitely

**Comment by xjmzx** [comment]
Searching peer info, seems the implementation is ACINQ/Eclair v0.6.2

**Comment by guggero** [comment]
If you're running `lnd` with the default log level of `info` then the actual reason for the force-close isn't logged currently. This will be corrected with https://github.com/lightningnetwork/lnd/pull/6124.
So it's not clear why the channel was force closed. It could just be that the remote peer asked you to, as part of the data loss protocol (DLP).

The error you see is probably unrelated, it sounds to me like a failed payment attempt of an ongoing payment.

**Comment by Roasbeef** [comment]
You get that error if the other peer isn't connected at forwarding time. What seems to have happened is upon restart we tried to re-forward that HTLC, but the channel didn't exist. 

Closing as everything looks to be in order here, the channel will be available for sweeping after those 205 blocks (which should be the case by now) have passed.

**Comment by xjmzx** [comment]
The issue did resolve itself, I suspect the cause was probably unrelated, my mistake.
Thanks for getting back to me with your input, Roasbeef, guggero.
Good to know that logs may become more descriptive.
