### ISSUE TITLE
Add Root Key ID to RPC Middleware Messages

### ISSUE THREAD

**Issue by gkrizek** [lightningnetwork/lnd#6119]
### Background

When interacting with messages from the RPC Middleware, there's a field of [`raw_macaroon`](https://github.com/lightningnetwork/lnd/blob/5d9b59ac5ade96467ddce4469c832fa3d8c481fe/lnrpc/lightning.proto#L4188-L4193) that is in the messages. This is obviously the actual macaroon contents. It would be really helpful to also include the Root Key ID that the macaroon belongs to in this message. This could be used in several ways:

- Assign policies on an entire root key which could cover many macaroons instead of 1 by 1
- Macaroons are sensitive so maybe the interceptor isn't aware of the raw content to evaluate. If you used an identified you could still perform policies without knowing the contents.

### Your environment

* lnd 0.14.1
* any os
* any backend

### Steps to reproduce

Intercept messages with the RPC Middleware

### Expected behaviour

Add a better identifier to the payloads outside of the raw_macaroon.

**Comment by guggero** [comment]
The root key ID is encoded in the macaroon, it's called the `StorageId`. Take a look at this commit (`IsSuperMacaroon`) on how to parse it: https://github.com/lightninglabs/lightning-terminal/pull/292/commits/fa756a51a8fdc57940f76375b4670015066f71fd

**Comment by Roasbeef** [comment]
Closing based on the above comment.
