### ISSUE TITLE
I need help claiming my node

### ISSUE THREAD

**Issue by jmburch921** [lightningnetwork/lnd#6120]
### Background

About two years ago I did a great job following directions, and I was able set up a lnd node.   Several months later, I suffered some brain trama in an accident.   A year ago I began to remember some details like the name and color I selected.  Ironically enough the name was enlightened https://1ml.com/node/02e7cda15016259bdd4cb50dd49a55d6766f30443e2ed9ed909f47e2f666303e65 
For the past year I have been trying to retrace my Steps on a laptop that has been reset.   I have found some lnd files... htlc.me files...  I found that I have a project creation on Google console called lightning...  I also have aws console with LND in the dir.  Also an Enlightened web page?  You can hopefully understand the frustration and now urgency as I am need of more costly surgery.   I am willing to pay a % of what is recovered.   

### Your environment

* version of `lnd`
*  my Acer laptop 
* I used bitcoin core with a connection to blockdaemon shared node
* for sure used onion services

**Comment by AugustoResende** [comment]
Apparently this node is running and active. Probably you left in some instance of ec2 or google cloud.

Because Bitcoin is a p2p network with no central coordinating entity, to obtain the funds you must have access to your private key, and in the case of lightning, access to the node or at least some scb backup

**Comment by jmburch921** [comment]
i have aws ec2 and in the console I see lnd, but I cannot access through any commands.

I also have a project in google console called lightning which i cant access due to billing??

thank you for your reply.

**Comment by jmburch921** [comment]
reparing your terminal...
[cloudshell-user@ip-10-0-126-247 ~]$ Try these commands to get started:
aws help  or  aws <command> help  or  aws <command> --cli-auto-prompt
[cloudshell-user@ip-10-0-126-247 ~]$ dir
lnd
[cloudshell-user@ip-10-0-126-247 ~]$

**Comment by AugustoResende** [comment]
Probably your node is still in aws. To log-in in your node machine you'll need to get the aws keypair, that i think you don't have, then you can follow this tutorial:

https://medium.com/the-10x-dev/how-to-recover-access-login-to-your-aws-instance-after-losing-your-pem-keypair-file-e0d31bae2da4

It certainly shouldn't be on the google cloud because your node is still online, and billing issues commonly shutdown the machine.

**Comment by jmburch921** [comment]
i do have the key pair.

**Comment by jmburch921** [comment]
is this not it?  why cant it just be simple like...   open cipherseed.go????   I am losing my patcience and what mind is left.  1 year and I am 1 command away..... or at least i hope I am.... am i not????

[cloudshell-user@ip-10-0-147-162 aezeed]$ dir
bench_test.go  cipherseed.go  cipherseed_rpctest.go  cipherseed_test.go  errors.go  README.md  wordlist.go
[cloudshell-user@ip-10-0-147-162 aezeed]$

**Comment by guggero** [comment]
It looks like you're looking at the source directory of lnd, where you compiled the binary from. Search for a `.lnd` directory in your $HOME dir, that contains the data. And try if `lncli getinfo` returns anything (would mean the node is still running).

If the node is running, close all channels and withdraw the funds. If not, try if you can start and unlock it (requires a password that you set). If that doesn't work, download the `.lnd` directory and continue with [chantools](https://github.com/guggero/chantools), specifically `chantools walletinfo` where you can try to find out your password as many times as you need.

**Comment by jmburch921** [comment]
Thank you very much for your reply.  I will try to get to that directory.  

Is it $cd home
Or
$cd gopath
?

**Comment by jmburch921** [comment]
update:  I was using the wrong account.  I found an account that had a past due amount on lightsail payments.  I paid it, only to find out that they deleted my account.

**Comment by guggero** [comment]
Going to answer your email and will close this issue in the meantime (since it's not a problem with lnd itself).

**Comment by jmburch921** [comment]
I have an ec private key file.  Is this the private key?

**Comment by jmburch921** [comment]
Very well.  Thank you.
