### ISSUE TITLE
How do I import rpc_pb2 and rpc_pb2_grpc in python?

### ISSUE THREAD

**Issue by suhailsaqan** [lightningnetwork/lnd#6127]
I am using Python and I am trying to import `rpc_pb2` and `rpc_pb2_grpc` in Python. How do I do that?

**Comment by suhailsaqan** [comment]
Nevermind, I imported `lightning_pb2` and `lightning_pb2_grpc`.

**Comment by Roasbeef** [comment]
Glad you figured it out! Anything you can add to make [our documentation more explicit](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md) would be much appreciated.
