### ISSUE TITLE
Peers are still unable to reconnect and stuck in a deadlock after IP address change

### ISSUE THREAD

**Issue by viaj3ro** [lightningnetwork/lnd#6128]
Unfortunately https://github.com/lightningnetwork/lnd/issues/5377 still persists. 

I had another IP address change on my node and around 25 of my tor peers are still disconnected after 40 hours. The new IP was announced right after the change and 1ml picked it up around 15-30 minutes later.

I was able to verify that a handful of those peers are running LND versions that already implemented https://github.com/lightningnetwork/lnd/pull/5538 which should've solved the issue but apparently it didn't.

**Comment by ellemouton** [comment]
Some questions:
- Do you perhaps have some logs from the peers showing that it is in fact a deadlock?
- Also would be useful to just confirm that the peers are definitely getting the node_announcement update (just to definitely rule that out). ie, if they do a `getnodeinfo` on your node id, does the new ip addr show up?
- is it _only_ Tor peers that you are having this issue with? and if so, is it _all_ your tor peers?

**Comment by viaj3ro** [comment]
No logs unfortunately. One of the nodes was yalls-tor, but Alex keeps no logs. He said he didn't receive the new IP, either due to gossip not getting through ore rate limiting. He had to manually reconnect after more than 40 hours of being stuck.

I had to manually reconnect some clearnet nodes as well and some tor nodes did reconnect rather quickly.

So the issue might be that the new IP just doesn't get to every node. But why is that the case?

**Comment by ellemouton** [comment]
> So the issue might be that the new IP just doesn't get to every node

yeah sounds like this might be the issue. Could you perhaps check with a few more of the peers that are not connecting back to you if they also did not get the IP addr update? then we can be sure that this is more of a reliable-gossip-propagation issue rather than a reconnection issue.

**Comment by viaj3ro** [comment]
the ones I have contact information are already connected and the others I have no way of contacting them unfortunately.

But there seems to be very widespread issues with LNDs ability to receive gossip.  https://amboss.space/ isn't able to show recently or even long time ago closed channels, since the gossip doesn't get through.

Channels are often marked as disabled for days, even though they are perfectly healthy due to LND apparently rate limiting so extreme that the enabled message can't get through : https://github.com/lightningnetwork/lnd/issues/6000#issuecomment-991270252

And now even new IP announcement doesn't propagate properly.

Why all these issues with gossip?

**Comment by Roasbeef** [comment]
> Why all these issues with gossip?

Some implementations throttle gossip pretty aggressively (something like 3 updates per node for 24 hrs or something like that), we also throttle as well on a burst level, but only dedicate a few connections at a time to be "active" syncners.

You may want to try increasing the number of active syncers (`--numgraphsyncpeers`).  

> I was able to verify that a handful of those peers are running LND versions that already implemented #5538 which should've solved the issue but apparently it didn't.


This in theory addresses things assuming they're actually getting the new node announcements.

**Comment by Roasbeef** [comment]
> I had another IP address change on my node and around 25 of my tor peers are still disconnected after 40 hours.

Did you observe this for _only_ the tor peers?

**Comment by Roasbeef** [comment]
> I had another IP address change on my node and around 25 of my tor peers are still disconnected after 40 hours. 

Are you running with hosts specified in `--externalhosts`? That's the only way we'll detect that your IP changed. Otherwise, we don't have a way to detect such changes, particularly if you're behind a NAT, without additional protocol extensions, like: https://github.com/lightning/bolts/pull/917

**Comment by viaj3ro** [comment]
> Did you observe this for _only_ the tor peers?

there were a handful of clearnet peers, that were offline as well, but I manually connected them right away.

> Are you running with hosts specified in `--externalhosts`? That's the only way we'll detect that your IP changed. Otherwise, we don't have a way to detect such changes, particularly if you're behind a NAT, without additional protocol extensions, like: [lightning/bolts#917](https://github.com/lightning/bolts/pull/917)

not exactly sure what you mean but I'm announcing my new IP via `eclair.server.public-ips = [31.17.64.33]` and 1ml and most of my tor peers are picking up on it. Around 15 tor peers do not, though and are still disconnected.

**Comment by viaj3ro** [comment]
I found a workaround for the issue: changing the alias seems to trigger a gossip message and all disconnected peers (TOR or otherwise) were finally able to reconnect.

This also means something is not going right with the IP announcement itself, though.

**Comment by whitslack** [comment]
I'll contribute another data point to this story. My node's IP address changed two days ago. Of my 1166 peers with whom I have active channels, only 361 have reconnected, with 805 still remaining unconnected. 1ML shows my new IP address, but Amboss still shows my old address. And, strangely, Amboss says it observed a change in my address yesterday, yet it still shows the old address.

Do node announcements carry timestamps? Is it possible that stale announcements are overwriting fresher announcements?

**Comment by viaj3ro** [comment]
@whitslack did you try the alias change trick?

**Comment by whitslack** [comment]
> I assume you updated your IP in the config already?

My node is C-Lightning, and I specified my host's dynamic DNS name in the config. Yes, I did restart the node to pick up the change in address, and `lightning-cli getinfo` does show the new IP address.

> did you also try the alias change trick?

I did not. I don't want to change my node's alias, and besides, the problem is not that my node didn't generate a new node announcement, as some nodes like 1ML have seen the new announcement. There does seem to be a problem in propagating the new announcement to all nodes in the network, however.

**Comment by whitslack** [comment]
@viaj3ro: I'll change the color instead. Should have the same effect, I'd imagine.

**Comment by viaj3ro** [comment]
@whitslack  did it work?

**Comment by whitslack** [comment]
> did it work?

@viaj3ro: Mixed results. I'm now up to 432 connected channel peers, with 729 disconnected channel peers still to go. Amboss now shows my new IP address, citing today's date as the date of the change, yet that change actually still shows my old color, so it would actually represent the change from two days ago. Amboss still doesn't see my new color.

**Comment by viaj3ro** [comment]
@whitslack have a look https://lightningnetwork.plus/ 
If they don't have your new IP, I'd say the color changing scheme didn't work. But it's also possible, that you have to wait 24h, since some notes have very restrictive anti spam measures. 

If you have telegram, we can takes this conversation there and not clutter this thread even more: https://t.me/viaj3ro

**Comment by whitslack** [comment]
FWIW, I opened a similar [issue](https://github.com/ElementsProject/lightning/issues/5037) in the C-Lightning issue tracker. However, this may turn out to be caused by a fundamental design problem that affects all Lightning implementations.

**Comment by LNBIG-COM** [comment]
I have a similar problem (LND `v0.15.4-beta`). I decided to unify the LND instances with `lnd.conf`  by taking the external IP address outside to the /etc/hosts file. I decided to use `externalhosts` instead of the `externalip` option in lnd.conf. Now I am observing the following problem:

/etc/hosts file:

```
XX.XX.XX.XX ip-external
```

lnd.conf (there is no `externalip` option):

```
externalhosts=ip-external:9735
listen=ip-external:9735
```

The problem is that when I transfer the LND instance to another server and run it with these settings, the server instance itself sees its own IP (`l getinfo` shows the `uris` field as `nodeid@ip:port`), but it does not announce it to other nodes, and even my other nodes (`v0.15.4-beta`) have the old IP address in their graph even after a few days.

I come to the conclusion that the `externalhosts` option does not work at all as intended. It's not that my IP address  changes periodically - it's static, but still LND doesn't announce its IP address via gossip to lightning network. Otherwise I can't explain it in any way.

**Comment by LNBIG-COM** [comment]
And may be other bug? I put in a config a following lines:

gossip.pinned-syncers=0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0,03bc9337c7a28bb784d67742ebedd30a93bacdf7e4ca16436ef3798000242b2251,03da1c27ca77872ac5b3e568af30673e599a47a5e4497f85c7b5da42048807b3ed,02de11c748f5b25cfd2ce801176d3926bfde4de23b1ff43e692a5b76cf06805e4a,02bb24da3d0fb0793f4918c7599f973cc402f0912ec3fb530470f1fc08bdd6ecb5,032679fec1213e5b0a23e066c019d7b991b95c6e4d28806b9ebd1362f9e32775cf,033e9ce4e8f0e68f7db49ffb6b9eecc10605f3f3fcb3c630545887749ab515b9c7,03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12,031ce29116eab7edd66148f5169f1fb658fad62bdc5091221ab895fe5d36db00b2,034ea80f8b148c750463546bd999bf7321a0e6dfc60aaf84bd0400a2e8d376c0d5,03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618,03fce165537aea120bffe8505876b44d5119354f825b3eac329b761fc5636bf334,030995c0c0217d763c2274aa6ed69a0bb85fa2f7d118f93631550f3b6219a577f5,03e5ea100e6b1ef3959f79627cb575606b19071235c48b3e7f9808ebcd6d12e87d,039edc94987c8f3adc28dab455efc00dea876089a120f573bd0b03c40d9d3fb1e1,028a8e53d70bc0eb7b5660943582f10b7fd6c727a78ad819ba8d45d6a638432c49,022755c3ff4e5a1d71f573cda4b315887fc00a9e5c9ea9a847d939f3e517e69a70,022c260f9ad58196af280c80a96ec9eabf6404df59ff1a7553b0f381c875a29ba0,024d2387409269f3b79e2708bb39b895c9f4b6a8322153af54eba487d4993bf60f,02c91d6aa51aa940608b497b6beebcb1aec05be3c47704b682b3889424679ca490,0303a518845db99994783f606e6629e705cfaf072e5ce9a4d8bf9e249de4fbd019,03dab87ff8635982815c4567eb58af48f9944d11c56beb12b91e1049aaea06e187,0311cad0edf4ac67298805cf4407d94358ca60cd44f2e360856f3b1c088bcd4782,02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b,035f5236d7e6c6d16107c1f86e4514e6ccdd6b2c13c2abc1d7a83cd26ecb4c1d0e


Its are my nodes. But I cannot start LND now (v0.15.4). I see the error:

WRN] LTND: Error validating config: ValidateConfig: error parsing gossip syncer: invalid vertex string length of 1674, want 66
failed to load config: ValidateConfig: error parsing gossip syncer: invalid vertex string length of 1674, **want 66**

But `lnd --help` shows:

gossip.pinned-syncers= A set of peers that should always remain in an active sync state, which can be used to closely synchronize the routing tables of two nodes. **The value should be comma separated list of hex-encoded pubkeys.**
