### ISSUE TITLE
Graph remains out of synch for a very long time for a direct peer.

### ISSUE THREAD

**Issue by BhaagBoseDK** [lightningnetwork/lnd#6132]
### Background

I have a channel with LOOP -> 693862x1024x1

Today it shows disabled from LOOP -> me (see is_disabled = true from LOOP end)
The update is nearly 4 hours old (see updated_at:). I checked with some of my peers and their graph does not show the same state for this channel. Their update is 3 minutes later (18:30:59.000Z). 

I tried to enable/disable channel from my end, lncli disconnect/connect, as well as sending a test payment of 1 sat but the channel graph is still old.

Because of this issue, I am unable to circular rebalance this channel.

umbrel@umbrel:~/.lnd $ bos call getchannel --param id=693862x1024x1

id:               693862x1024x1
capacity:         20000000
policies: 
  - 
    base_fee_mtokens: 1000
    cltv_delta:       40
    fee_rate:         500
    is_disabled:      true
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 1000
    public_key:       021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d
    updated_at:       2022-01-03T18:27:11.000Z
  - 
    base_fee_mtokens: 269420
    cltv_delta:       20
    fee_rate:         5120
    is_disabled:      false
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 2169420
    public_key:       03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1
    updated_at:       2022-01-03T22:53:36.000Z
transaction_id:   7ca1004931dad578e11fc6979a30e17b659f782f3a94eba3e165d26639992b49
transaction_vout: 1
updated_at:       2022-01-03T22:53:36.000Z

### Your environment

* version of `lnd`

"version": "0.14.1-beta commit=v0.14.1-beta",

* which operating system (`uname -a` on *Nix)
Linux umbrel 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux

### Steps to reproduce

This looks like a freak issue so not sure how to reproduce.

### Expected behaviour

Channel Graph should be latest for direct connected peers.

### Actual behaviour

Graph is out of synch for nearly 4 hours.

**Comment by Roasbeef** [comment]
The channel graph propagates changes to all peers _eventually_. If you want to ensure your node gets changes more quickly, you can increase `numgraphsyncpeers`. 

> Channel Graph should be latest for direct connected peers.

Only true if the peer is currently a sync peer. We only have a subset of the peers sending us gossip data (why get the same message from 1k peers each time?). If you set that flag to a higher value (default is 9), then you'll get more gossip data, and tradeoff CPU/bandwidth for a more up to date view of the graph. 

You can also have peers that you'll _always_ get new data from by using `gossip.pinned-syncers`.

**Comment by Roasbeef** [comment]
> Today it shows disabled from LOOP -> me (see is_disabled = true from LOOP end)

This means _loop_ disabled _with you_. You enabling in another direction doesn't fix that. If you don't have the channel at all, then that means it isn't in your local graph, so it wasn't fully announced.

**Comment by BhaagBoseDK** [comment]
> > Today it shows disabled from LOOP -> me (see is_disabled = true from LOOP end)
> 
> This means _loop_ disabled _with you_. You enabling in another direction doesn't fix that. If you don't have the channel at all, then that means it isn't in your local graph, so it wasn't fully announced.

No loop has not disabled with me. When you check the same channel on your node (693862x1024x1) you will find that channel enabled from both side. Just on my node, I am missing the gossip update and even after nearly 12 hours my gossip is still behind.

I will try the other suggestions (num synch peers and pinned syners)

**Comment by BhaagBoseDK** [comment]
> You can also have peers that you'll _always_ get new data from by using `gossip.pinned-syncers`.

This did not help. I added 3 pinned peers who I know have correct update on this channel.

> The channel graph propagates changes to all peers eventually. If you want to ensure your node gets changes more quickly, you can increase numgraphsyncpeers.

How long can be "eventual"? Also the way I am describing the issue, the update I have  "updated_at:       2022-01-03T18:27:11.000Z" is behind by nearly 4 minutes of next update from loop. Will this catch up?

**Comment by BhaagBoseDK** [comment]
could this have an impact?
`[routing]
routing.strictgraphpruning=true`

**Comment by BhaagBoseDK** [comment]
As example, my node shows the following now (see updated_at changed for my node but not LOOP)
`
umbrel@umbrel:~/lndlog $ bos call getchannel --param id=693862x1024x1

id:               693862x1024x1
capacity:         20000000
policies: 
  - 
    base_fee_mtokens: 1000
    cltv_delta:       40
    fee_rate:         500
    is_disabled:      true
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 1000
    public_key:       021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d
    updated_at:       2022-01-03T18:27:11.000Z
  - 
    base_fee_mtokens: 269420
    cltv_delta:       20
    fee_rate:         5120
    is_disabled:      false
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 2169420
    public_key:       03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1
    updated_at:       2022-01-04T09:06:22.000Z
transaction_id:   7ca1004931dad578e11fc6979a30e17b659f782f3a94eba3e165d26639992b49
transaction_vout: 1
updated_at:       2022-01-04T09:06:22.000Z
`

but the same command gives the following output for a third party peer (or your own node would show similar)

`
$ bos call getchannel --param id=693862x1024x1

id:               693862x1024x1
capacity:         20000000
policies: 
  - 
    base_fee_mtokens: 1000
    cltv_delta:       40
    fee_rate:         500
    is_disabled:      false
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 1000
    public_key:       021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d
    updated_at:       2022-01-04T08:10:33.000Z
  - 
    base_fee_mtokens: 269420
    cltv_delta:       20
    fee_rate:         5120
    is_disabled:      true
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 2169420
    public_key:       03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1
    updated_at:       2022-01-03T22:53:06.000Z
transaction_id:   7ca1004931dad578e11fc6979a30e17b659f782f3a94eba3e165d26639992b49
transaction_vout: 1
updated_at:       2022-01-04T08:10:33.000Z
`

**Comment by BhaagBoseDK** [comment]
is there anyway graph can be refreshed (delete and request a fresh view)

**Comment by alexbosworth** [comment]
I can confirm `693862x1024x1` on LOOP is not disabled in either direction on the local graph view

**Comment by BhaagBoseDK** [comment]
yes that is the problem - only for my node I still get this "disabled": true,

umbrel@umbrel:~ $ lncli getchaninfo --chan_id 762909337139019777
{
    "channel_id": "762909337139019777",
    "chan_point": "7ca1004931dad578e11fc6979a30e17b659f782f3a94eba3e165d26639992b49:1",
    "last_update": 1641298863,
    "node1_pub": "021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d",
    "node2_pub": "03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1",
    "capacity": "20000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "500",
        "disabled": true,
        "max_htlc_msat": "19800000000",
        "last_update": 1641234431
    },
    "node2_policy": {
        "time_lock_delta": 20,
        "min_htlc": "2169420",
        "fee_base_msat": "269420",
        "fee_rate_milli_msat": "4699",
        "disabled": false,
        "max_htlc_msat": "19800000000",
        "last_update": 1641298863
    }
}

**Comment by alexbosworth** [comment]
Potentially you missed an update from Loop which re-enabled the channel

I see that Loop disabled this edge 9 hours ago, then re-enabled it. I would check back in 15 hours and I think it will probably resolve itself.

**Comment by BhaagBoseDK** [comment]
Finally happy to see the correct update reflected in the graph took almost 36 hours.

    base_fee_mtokens: 1000
    cltv_delta:       40
    fee_rate:         500
    is_disabled:      false
    max_htlc_mtokens: 19800000000
    min_htlc_mtokens: 1000
    public_key:       021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d
    updated_at:       2022-01-05T08:28:55.000Z

**Comment by Roasbeef** [comment]
Closing for now as the updates were all _eventually_ propagated. See my comments above w.r.t how to increase the aggressiveness w.r.t how your peer sends updates to other peers. 

We have a few other open issue tracking some possilbe networking bugs in our stack, which may indirectly address issues of slower gossip data propagation.
