### ISSUE TITLE
lnd running on 32-bit system OOMs on start up 

### ISSUE THREAD

**Issue by martinatime** [lightningnetwork/lnd#6135]
### Background

Everything has been fine up until just now

### Your environment

* version of `lnd` - 0.14.1-beta
* which operating system (`uname -a` on *Nix) - Linux raspibolt2 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend - Bitcoin Core version v22.0.0
* any other relevant environment details
Raspberry Pi 4GB

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
Jan 05 15:28:54 raspibolt2 lnd[1938]: 2022-01-05 15:28:54.181 [INF] LNWL: Opened wallet
Jan 05 15:28:54 raspibolt2 lnd[1938]: 2022-01-05 15:28:54.505 [INF] CHRE: Primary chain is set to: bitcoin
Jan 05 15:28:54 raspibolt2 lnd[1938]: 2022-01-05 15:28:54.586 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
Jan 05 15:28:54 raspibolt2 lnd[1938]: 2022-01-05 15:28:54.586 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Jan 05 15:28:54 raspibolt2 lnd[1938]: 2022-01-05 15:28:54.586 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime: out of memory: cannot allocate 268435456-byte block (359727104 in use)
Jan 05 15:28:54 raspibolt2 lnd[1938]: fatal error: out of memory
Jan 05 15:28:54 raspibolt2 lnd[1938]: goroutine 227 [running]:
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime.throw({0x14d936e, 0xd})
Jan 05 15:28:54 raspibolt2 lnd[1938]:         runtime/panic.go:1198 +0x5c fp=0x8bf9a04 sp=0x8bf99f0 pc=0x49e18
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime.(*mcache).allocLarge(0xb6fbf538, 0x10000000, 0x0, 0x1)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         runtime/mcache.go:229 +0x26c fp=0x8bf9a38 sp=0x8bf9a04 pc=0x26a50
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime.mallocgc(0x10000000, 0x12930b8, 0x1)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         runtime/malloc.go:1082 +0x6b4 fp=0x8bf9a7c sp=0x8bf9a38 pc=0x1c630
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime.makeslice(0x12930b8, 0x4000000, 0x4000000)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         runtime/slice.go:98 +0xac fp=0x8bf9a90 sp=0x8bf9a7c pc=0x646ec
Jan 05 15:28:54 raspibolt2 lnd[1938]: golang.org/x/crypto/scrypt.Key({0x3de9400, 0xd, 0x200}, {0x3c12644, 0x20, 0x20}, 0x40000, 0x8, 0x1, 0x20)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/scrypt/scrypt.go:204 +0x13c fp=0x8bf9ae4 sp=0x8bf9a90 pc=0x320164
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/snacl.(*SecretKey).deriveKey(0x3c12640, 0x8bf9e04)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet@v0.13.0/snacl/snacl.go:114 +0x64 fp=0x8bf9b30 sp=0x8bf9ae4 pc=0x320820
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/snacl.(*SecretKey).DeriveKey(0x3c12640, 0x8bf9e04)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet@v0.13.0/snacl/snacl.go:201 +0x24 fp=0x8bf9b80 sp=0x8bf9b30 pc=0x320d0c
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/waddrmgr.(*Manager).Unlock(0x3d5cf20, {0xa6b9bd48, 0x8370840}, {0x3de9400, 0xd, 0x200})
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet@v0.13.0/waddrmgr/manager.go:1199 +0x228 fp=0x8bf9df4 sp=0x8bf9b80 pc=0x33a004
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker.func1({0x1894468, 0x50872f8})
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet@v0.13.0/wallet/wallet.go:1276 +0x94 fp=0x8bf9e20 sp=0x8bf9df4 pc=0x4ff640
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/walletdb/bdb.(*db).View(0x3d628c0, 0x7e0ec90, 0x1690dd0)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:392 +0xa8 fp=0x8bf9e58 sp=0x8bf9e20 pc=0x535484
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/walletdb.View(...)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/interface.go:260
Jan 05 15:28:54 raspibolt2 lnd[1938]: github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker(0x3dc01e0)
Jan 05 15:28:54 raspibolt2 lnd[1938]:         github.com/btcsuite/btcwallet@v0.13.0/wallet/wallet.go:1274 +0x288 fp=0x8bf9fe4 sp=0x8bf9e58 pc=0x4fefb0
Jan 05 15:28:54 raspibolt2 lnd[1938]: runtime.goexit()

### Expected behaviour

Tell us what should happen

**Comment by bhandras** [comment]
Seems like LND is trying to allocate 256 MiB but it fails as all the memory is taken? Do you have anything else running that's using a lot of RAM? Do you have swap?

**Comment by guggero** [comment]
Also, try upgrading to a 64bit operating system and then try running the `arm64` binary of `lnd`.

**Comment by martinatime** [comment]
> Seems like LND is trying to allocate 256 MiB but it fails as all the memory is taken? Do you have anything else running that's using a lot of RAM? Do you have swap?

It had been running fine until now with everything else that was running. I've been stopping everything else and it doesn't seem to impact the memory allocation issue.

**Comment by martinatime** [comment]
> Also, try upgrading to a 64bit operating system and then try running the `arm64` binary of `lnd`.



> Also, try upgrading to a 64bit operating system and then try running the `arm64` binary of `lnd`.

I've been very hesitant to make the switch with a running node. I guess I'll have to look into it.

**Comment by martinatime** [comment]
I attempted to set up a swapfile (I swore I already had one) but that didn't resolve the issue

@guggero is there a guide on how to go from 32 to 64? I don't want to kill my node but I'm at a loss as to what to do next.

**Comment by martinatime** [comment]
https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#migrating-a-node-to-a-new-device

I'll be trying this tonight when I have more time to dedicate to it.

**Comment by martinatime** [comment]
I migrated to 64bit and I'm up and running again. I swear I was keeping watch of the size of my channels.db but apparently over the holidays I lost track and it ballooned. Thanks again for the help. I'll close this now.
