### ISSUE TITLE
Failing to payinvoice: IncorrectCltvExpiry

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#614]
I'm running db06a8a7eea310f6eda12025a80e5fe5f788aaf5 from Jan 12, 2018 on Bitcoin Testnet on Autopilot.

I was able to get a few other payments through a few days earlier.

Now, the payments keep failing:

Invoice
=========
```
$ lncli addinvoice 5867
{
        "r_hash": "3c6349bdf274bb3e1ae69303837faab31f2335a01f6066f49014e515dfe0a1d6",
        "pay_req": "lntb58670n1pd9asx9pp58335n00jwjanuxhxjvpcxla2kv0jxddqrasxdaysznj3thlq58tqdqqcqzyszard582h2vj3agn2wyyd2wrhjh9sn6zehqtsmm8g34j0xaz76zgqhv9shmuwm6a5awddqctmmh4a844n5r9wk95mt4ucmj3a5zw32jqptx0tk2"
}


$ lncli decodepayreq lntb58670n1pd9asx9pp58335n00jwjanuxhxjvpcxla2kv0jxddqrasxdaysznj3thlq58tqdqqcqzyszard582h2vj3agn2wyyd2wrhjh9sn6zehqtsmm8g34j0xaz76zgqhv9shmuwm6a5awddqctmmh4a844n5r9wk95mt4ucmj3a5zw32jqptx0tk2
{
    "destination": "034725c18651ace5f07ee7e958473726f38b2af123eefbd127124134c2c0e11263",
    "payment_hash": "3c6349bdf274bb3e1ae69303837faab31f2335a01f6066f49014e515dfe0a1d6",
    "num_satoshis": "5867",
    "timestamp": "1516159173",
    "expiry": "3600",
    "description": "",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144"
}
```

Pay Invoice Failure 1: TemporaryChannelFailure
==================================
```
{
        "payment_error": "unable to route payment to destination: TemporaryChannelFailure",
        "payment_preimage": "",
        "payment_route": null
}

real    1m3.587s
user    0m0.004s
sys     0m0.000s
```

Pay Invoice Failure 2: FeeInsufficient
===========================
```
$ lncli payinvoice lntb58670n1pd9asx9pp58335n00jwjanuxhxjvpcxla2kv0jxddqrasxdaysznj3thlq58tqdqqcqzyszard582h2vj3agn2wyyd2wrhjh9sn6zehqtsmm8g34j0xaz76zgqhv9shmuwm6a5awddqctmmh4a844n5r9wk95mt4ucmj3a5zw32jqptx0tk2

{
        "payment_error": "FeeInsufficient(fee=6435235 mSAT, update=(lnwire.ChannelUpdate) {\n Signature: (*btcec.Signature)(0xc424f99600)({\n  R: (*big.Int)(0xc421666080)(9742021230676497245360959906780211633425178691083885930242016454386522403519),\n  S: (*big.Int)(0xc4216660a0)(10684544472076612949939263463537384537328465992097424989967893533589242567616)\n }),\n ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943,\n ShortChannelID: (lnwire.ShortChannelID) 1258823:27:0,\n Timestamp: (uint32) 1516153912,\n Flags: (lnwire.ChanUpdateFlag) 1,\n TimeLockDelta: (uint16) 144,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 0 mSAT,\n BaseFee: (uint32) 1000,\n FeeRate: (uint32) 1\n}\n",
        "payment_preimage": "",
        "payment_route": null
}

real    3m28.558s
user    0m0.008s
sys     0m0.000s
```

Pay Invoice Failure 3: IncorrectCltvExpiry
==============================
```
$ lncli payinvoice lntb58670n1pd9asx9pp58335n00jwjanuxhxjvpcxla2kv0jxddqrasxdaysznj3thlq58tqdqqcqzyszard582h2vj3agn2wyyd2wrhjh9sn6zehqtsmm8g34j0xaz76zgqhv9shmuwm6a5awddqctmmh4a844n5r9wk95mt4ucmj3a5zw32jqptx0tk2

{
        "payment_error": "IncorrectCltvExpiry(expiry=1259824, update=(lnwire.ChannelUpdate) {\n Signature: (*btcec.Signature)(0xc424305a80)({\n  R: (*big.Int)(0xc4237f35a0)(81059145196036646713481071676514017115163930873331302993276634617269884409902),\n  S: (*big.Int)(0xc4237f35c0)(27185760502567886351570496160630551252297493061642143492013530703980555209607)\n }),\n ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943,\n ShortChannelID: (lnwire.ShortChannelID) 1258860:160:1,\n Timestamp: (uint32) 1516011533,\n Flags: (lnwire.ChanUpdateFlag) 1,\n TimeLockDelta: (uint16) 14,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 10000 mSAT,\n BaseFee: (uint32) 10000,\n FeeRate: (uint32) 100\n}\n",
        "payment_preimage": "",
        "payment_route": null
}

real    3m28.558s
user    0m0.008s
sys     0m0.000s
```

**Comment by alevchuk** [comment]
It looks like only the direct channels are working and all the relay paths are broken.
I have 7 active channels to other peers with enough capacity.

Why would I get IncorrectCltvExpiry in this case?

**Comment by Roasbeef** [comment]
You'll get `IncorrectCltvExpiry` if the node you're trying to send to isn't synced to the network, or you aren't. If nodes disagree about the current block height, that can happen, but only typically in a narrow window where as you send a payment, a block is mined. 

Those other errors you get are also "standard". `TemporaryChannelFailure` typically indicates that the channel doesn't have enough capacity to carry the payment.

**Comment by alevchuk** [comment]
So possibly one or more active channels are connected to nodes where the chain is outdated (e.g. btcd is no longer running)?

If IncorrectCltvExpiry is encountered, should PayInvoice try a different channel?

I’m running loop that keep re-trying PayInvoice on the same pay_req (with a 24 hour expiry), yet always getting one of the 3 failures. I have many active channels open on payee and payer, 50 channels each. The only one that works is the direct (1 hop) route. Once I deplete that channel, and longer routes are chosen then PayInvoice starts failing.  Does that mean that none of my channels are able to route this payment? Or is it always tripping on one bad channel?

**Comment by alevchuk** [comment]
I don't see the error anymore and it's likely that one of my nodes had issues. If I see it again and get a better understanding of what's happening, I'll post the details here and re-open.
