### ISSUE TITLE
[Request] Wallet Status

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#615]
Hi!

I would like to know the wallet status so I can show an apropriate screen on login.

walletStatus should return "Locked", "Unlocked", "Not Created" or similar.

Or even better, make the information available in "getInfo", and make that command available before the wallet have been opened/created.

Alternative, a call to GetInfo could return an error if the wallet doesn't exist/is locked instead of 404...

**Comment by githubsands** [comment]
@Roasbeef can you assign me this issue?

**Comment by Roasbeef** [comment]
Hmm, well the wallet is not unlocked, if the main gRPC server _isn't_ up. As is, the `WalletUnlocker` service is _only_ up if the wallet isn't yet unlocked. We can't actually start up the regular RPC server as is atm, if the wallet isn't unlocked.

**Comment by Richard87** [comment]
I would love if WalletUnlocker had *copied* the `getInfo` command, and returned the information it could, as well as a wallet status (and it would say locked/unavailable/unknown or something) :)

Richard

**Comment by halseth** [comment]
Tracking this in #3982
