### ISSUE TITLE
EstimateFee Error - Invalid length destination key

### ISSUE THREAD

**Issue by srmcatee1110** [lightningnetwork/lnd#6150]
### Background
I have setup a regnet test network with two LND nodes.   One to send money and the second (lnd2) to generate invoices on.  I am writing code to simulate a mobile app.  I'm currently trying to calculate the fee to pay an invoice and attempting to call /v2/router/route/estimatefee

I'm getting this error when I execute the code below:
{'code': 2, 'message': 'invalid length destination key', 'details': []}

`import base64
import codecs
import json
import requests
payment_alias = b'02183a81bfb5ce3a221d'
payment_destination = b'02183a81bfb5ce3a221d15ffa67c2a1d796746ac89f1c81850577b52ec1633e339'

payment_hash = "P2KF2DfNWvXfi2mIsHDggiCNiAMgIdY7YQLNumyWE7o="
payment_addr = "0CvjBbZYw5piSHEqn74Nb0ccWvzvbpibrQOLBNu4A3A="

qrinvoice = "lnbcrt7u1psakj8hpp58a3gtkphe4d0thutdxytqu8qsgsgmzqryqsavwmpqtxm5mykzwaqdqlw3jhxapqw35xjueqda6hggr5wfujqvccqzpgxqyz5vqsp56q47xpdktrpe5cjgwy4fl0sddar3ckhuaahf3xadqw9sfkacqdcq9qyyssq327t48uyceydjj2rxk7kl5gxq2q3yjxqjraxsqq02uttm6kvwcwsd8yzqvj5pdkxgfequjs32tefd9mhl06hu3tt4l36eyqats0rr7qpyhjd54"

lnd1 = "10.142.0.21:8080"

url = 'https://{}/v2/router/route/estimatefee'.format(lnd1)
data = {
             'dest': base64.b64encode(payment_destination).decode(),
             'amt_sat': 200
         }

cert_path = './tls.cert'

macaroonhex = <macaroonvalue>
headers = {'Grpc-Metadata-macaroon': macaroonhex}

r = requests.post(url, data=json.dumps(
    data), headers=headers, verify=cert_path)

print(r.json())
`

### Your environment
Two LND nodes on Debian 10.
Linux  #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
LND "version": "0.14.0-beta commit=v0.14.0-beta",
bitcoind version:   220000

### Steps to reproduce
1. Create an invoice.
2. Run above code

### Expected behaviour
I should get a fee back but just get error.

**Comment by guggero** [comment]
You need to hex decode the `payment_destination` first to get the raw bytes, then encode the raw bytes with base64.

Going to close the issue as this is not a problem with `lnd` itself.
