### ISSUE TITLE
"Unable to read message from" c-lightning nodes

### ISSUE THREAD

**Issue by dlaptev** [lightningnetwork/lnd#6153]
### Background

I was trying to open channels to two separate c-lightning nodes (don't know the versions unfortunately), and instead of the usual "Multiple channels unsupported" that I expected, I got "rpc error: code = Unknown desc = peer disconnected". In the logs I see the usual funding workflow interrupted with

```
2022-01-12 21:05:15.900 [INF] PEER: unable to read message from 03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5@212.96.34.202:9735: unable to parse message of unknown type: <unknown>
2022-01-12 21:05:15.903 [INF] PEER: unable to read message from 03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5@212.96.34.202:9735: EOF
2022-01-12 21:05:15.904 [INF] PEER: disconnecting 03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5@212.96.34.202:9735, reason: read handler closed
```

Could be that message parsing somehow broke between CL and LND.

### Your environment

* version of `lnd`: 0.14.1-beta commit=v0.14.1-beta

### Steps to reproduce

Have a channel with a CL node, try to open another channel.

### Expected behaviour

We should receive a meaningful error message that multiple channels are not supported by CL.

### Actual behaviour

Get "peer disconnected" error.

**Comment by alexbosworth** [comment]
this might be a spec issue since the spec doesn't have a way to signal multiple channels not supported

sometimes I notice that clightning will wait until later in the funding flow to return an error which is very difficult to deal with so i mostly avoid clightning nodes when doing channel opening

**Comment by Roasbeef** [comment]
> We should receive a meaningful error message that multiple channels are not supported by CL.

Not sure if they send one, but there's a new `warning` message being added, that ideally eventually will have _error_ codes so it becomes easier to programmatically handle stuff like this. 

> 2022-01-12 21:05:15.900 [INF] PEER: unable to read message from 03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5@212.96.34.202:9735: unable to parse message of unknown type: <unknown>

This line is benign, we just ignore messages we don't understand, I think they ended up hanging up the connection after that. 

We actually store (in memory) the last few errors we receive from a peer that can be seen in `ListPeers`, but only while we're connected to them. If you try again with the debug/trace logging, you'll likely be able to see the type of error they sent. 

Closing this as it's a sort of spec issue, and `lnd` worked as expected here.
