### ISSUE TITLE
How to fix it [lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification

### ISSUE THREAD

**Issue by ChayanonSaelee** [lightningnetwork/lnd#6154]
### Background
I have tried to use lnd for mainnet it is no problem. when I use for lnd testnet I can use ' lncli unlock ' but found this error 
" [lncli] rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification "

### environment

* lnd version 0.12.0-beta commit=v0.12.0-beta
* ubuntu 
* Bitcoin Core version v0.21.1

## LDN settings
    # Lets LND know to run on top of Bitcoin (as opposed to Litecoin)
    alias=pp025
    color=#34ebc3
    bitcoin.active=1
    #bitcoin.mainnet=1
    bitcoin.testnet=1
    # Lets LND know you are running Bitcoin Core (not btcd or Neutrino)
    bitcoin.node=bitcoind
    ## Bitcoind Settings
    # Tells LND what User/Pass to use to RPC to the Bitcoin node
    bitcoind.rpcuser=test
    bitcoind.rpcpass=ptest
    bitcoind.rpchost=127.0.0.1
    # Allows LND & Bitcoin Core to communicate via ZeroMQ
    bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
    bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
    ## Zap Settings
    # Tells LND to listen on all of your computer's interfaces
    # This could alternatively be set to your router's subnet IP
    tlsextraip=0.0.0.0
    # Tells LND where to listen for RPC messages
    # This could also be set to your router's subnet IP
    rpclisten=0.0.0.0:10009

### this is bitcoin.conf
    txindex=1
    server=1
    testnet=1
    #daemon=1
    maxconnections=10
    minrelaytxfee=0.00000000
    incrementalrelayfee=0.00000010
    # Allows LND to connect to the Bitcoin node via an RPC user & pass
    rpcuser=test
    rpcpassword=ptest
    # Allows LND & Bitcoin Core to communicate via ZeroMQ
    zmqpubrawblock=tcp://127.0.0.1:28332
    zmqpubrawtx=tcp://127.0.0.1:28333

How should I fix it and do I need to edit another file?

**Comment by guggero** [comment]
You need to point `lncli` to the correct port of the testnet node and use the correct macaroon/TLS files. Look at `lncli --help`:

```
GLOBAL OPTIONS:
   --rpcserver value          The host:port of LN daemon. (default: "localhost:10009")
   --lnddir value             The path to lnd's base directory. (default: "/home/guggero/.lnd")
   --tlscertpath value        The path to lnd's TLS certificate. (default: "/home/guggero/.lnd/tls.cert")
   --chain value, -c value    The chain lnd is running on, e.g. bitcoin. (default: "bitcoin")
   --network value, -n value  The network lnd is running on, e.g. mainnet, testnet, etc. (default: "mainnet")
   --no-macaroons             Disable macaroon authentication.
   --macaroonpath value       The path to macaroon file.
```

Or just use `lncli --network testnet <yourcommand>` if you're using the default directories.
