### ISSUE TITLE
Htlc interceptor race condition on startup

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6161]
When lnd starts, the htlc interceptor may not be quick enough to register itself. 

If a link comes up and a new htlc comes in (and/or previously accepted htlcs are replayed) and the interceptor isn't there, lnd could fail back the htlc. On an earlier run though, the interceptor could have settled it already (but that settle never made it to the database for some reason).

One solution suggested [here](https://github.com/lightningnetwork/lnd/issues/6040#issuecomment-1011477671) by @champo is to keep the htlcs in a queue until the interceptor is registered.

@carlaKC added to this that lnd also [releases htlcs](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/routerrpc/forward_interceptor.go#L221) when the connection to the interceptor is lost. This can possible be solved through the queue as well?

Perhaps there are other cases too where lnd falls back to default behavior when this is undesired or just unsafe.

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/6232
