### ISSUE TITLE
Logging timestamps should be optional

### ISSUE THREAD

**Issue by erikarvstedt** [lightningnetwork/lnd#6163]
lnd always prints timestamps in log messages.
This is redundant in systemd services (where log messages are automatically timestamped) and should be made optional.
This [SO post](https://stackoverflow.com/a/48630122/3806468) shows how this can be achieved

**Comment by redek-zelton** [comment]
Check this: https://newreleases.io/project/github/lightningnetwork/lnd/release/v0.13.0-beta.rc3.

Your Logging timestamps is useful for your peer. He should know when was your last log.

**Comment by erikarvstedt** [comment]
@zedek-zelton, how is the link relevant to this issue?

**Comment by redek-zelton** [comment]
ah sorry my bad, it's a suggestion.

**Comment by imskr** [comment]
Can I work on this? @Roasbeef

**Comment by imskr** [comment]
Can I work on this? @Roasbeef

**Comment by erikarvstedt** [comment]
Note to implementers:
- `bitcoind` has option `logtimestamps` (default: true)
- `clightning` has option `log-timestamps`(default: true)

`lnd` should use one of these names.

**Comment by guggero** [comment]
Unfortunately the command line flag parsing library we use cannot have boolean values with default value `true` (because you cannot specify `--myflag=false`). So it would need to be inverted. I'm voting for `disable-log-timestamps`.

**Comment by qustavo** [comment]
@guggero looks like the convention is to use the `--no` prefix flag (i.e `--no-macaroons` or `--no-listen'`)

**Comment by ellemouton** [comment]
Note that when https://github.com/lightningnetwork/lnd/pull/9083 is in, then this should be quite easy to do by passing options to the Handlers we define there :) (ie, no need to pass options to the btclog package anymore)
