### ISSUE TITLE
RPCMiddlewareRequest always has empty custom_caveat_condition

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#6164]
### Background

If I bake a macaroon with `lncli bakemacaroon` and add the `--custom_caveat_name mine --custom_caveat_condition mycaveat` options, when I intercept RPC calls using the baked macaroon for the named custom caveat, the `custom_caveat_condition` field is blank.

Interestingly, if I get the `raw_macaroon` bytes and deserialize them, I see the `mycaveat` identifier there. So it's not being totally ignored, it's just not where I expect it to be on the `RPCMiddlewareRequest`

### Your environment

* lnd 0.14.1

### Expected behaviour

`custom_caveat_condition` should be the value I set with the `--custom_caveat_condition` option.

### Actual behaviour

`custom_caveat_condition` is empty.

**Comment by guggero** [comment]
Are you registering your interceptor as read-only? I think the `custom_caveat_condition` is only set if you are using an interceptor that expects a custom caveat.

**Comment by sangaman** [comment]
Sorry for not responding sooner. I am not registering as read only, and I'm in fact able to deny requests with the interceptor in this setup. When I register I set  `custom_macaroon_caveat_name` to match the value of the `--custom_caveat_name` option when using `bakemacaroon`.

**Comment by guggero** [comment]
Ah I see now that we forgot to add that in `NewMessageInterceptionRequest` and `NewStreamAuthInterceptionRequest`. I'll try to fix that once time allows me to.
Or, if you want to take a stab, we should probably pass an argument in https://github.com/lightningnetwork/lnd/blob/master/rpcperms/interceptor.go#L930, but only if a custom caveat is set.

**Comment by sangaman** [comment]
I'll take a stab at it.
