### ISSUE TITLE
lnd stuck on get info - rpc services not available

### ISSUE THREAD

**Issue by CryptoCloaks** [lightningnetwork/lnd#6179]
### Background

My LND started having an error after a restart where it can't find the rpc.
![image](https://user-images.githubusercontent.com/40768388/150059679-fd0624ae-a714-426b-81ff-f630a840b037.png)

### Your environment

* version of `0.14.1-beta-fresh-btcpay`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

No idea how to replicate to be honest.

### Expected behaviour

lnd should start without RPC errors.

### Actual behaviour

lnd stuck from starting

**Comment by Roasbeef** [comment]
Looks like the DB is still waiting to be open. You can't hit RPCs until it fully starts up. [You can use the `State` sub-server to get notified when the RPC server is fully healthy](https://api.lightning.community/#service-state).

**Comment by CryptoCloaks** [comment]
Okay, I'll look into why my DB is screwing up. Thanks for the insight.

**Comment by guggero** [comment]
If opening the database takes a long time, you either need to turn off freelist sync (`sync-freelist=false`) and/or run DB compaction (`db.bolt.auto-compact=true`).

Closing the issue as this is likely a configuration and/or DB growth issue that can be addressed by auto-compaction.

**Comment by CryptoCloaks** [comment]
Thank you Guggero. Keep up the great work!
