### ISSUE TITLE
itests+config: created lnd nodes are reading the lnd config on the host machien, rather than ignoring it 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6199]
Tried to run some itests locally earlier today and got this error: 
```
=== CONT  TestLightningNetworkDaemon
    test_harness.go:118: lnd finished with error (stderr):
        exit status 1
        failed to load config: ValidateConfig: The mainnet, testnet, regtest, and simnet params can't be used together -- choose one of the four
```

After I commented out everything in the config on my local machine, the tests are able to run properly. It appears that a recent change attempted to fix some related issue here, and ended up breaking existing behavior inadvertently.

**Comment by Roasbeef** [comment]
I think this commit might be the culprit: https://github.com/lightningnetwork/lnd/commit/0f167fd03e2542ae230544f8ab36063f2ee61089#diff-0e426a43248661127a0c0ee115aef7a1093b635f8993b3f7ebb1dd9f05b8f249

**Comment by guggero** [comment]
Oops, yes, that's the problem, sorry. Going to take a look.
