### ISSUE TITLE
Return error to the client when calling walletrpc `SignPsbt` when signing fails

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#6204]
### Background

In the new `walletrpc` method `SignPsbt` it allows you to sign a PSBT, but if you pass a PSBT that has nothing for the node to sign it will fail to add signatures since it has nothing to sign, but this failure will be silent. If you are using this API and you think you have passed something to sign, the successful response could make you think that signing completed successfully when in fact nothing was signed.

### Your environment

* lnd `0dae2d47f20b924c72a798d551537c5d9de8f86a`

### Steps to reproduce

1. Pass a PSBT to the SignPsbt method that has no inputs that the node can sign and get a resulting `signed_psbt`

### Expected behavior

The API should complain that it didn't receive anything to sign

### Actual behavior

It returns a `signed_psbt` result that may in fact not actually be signed

### Workaround

If you compare the resulting PSBT with the original PSBT and they are byte for byte equal, this indicates nothing was signed

**Comment by hieblmi** [comment]
@alexbosworth your issue was addressed in #6771. 
Release notes info:
https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.16.0.md#rpc

Please close this issue if it has been resolved.

**Comment by guggero** [comment]
Fixed by #6771. Not returning an error was always on purpose as that can be useful for some flows.
With #6771 the caller now has a better option to find out if anything was signed at all.
