### ISSUE TITLE
Reliable HTLC outcome lookup

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6208]
Add a new rpc call to retrieve low-level information about an HTLC. The interface could be something like:

`LookupHTLC(chanId, HtlcId)` and/or `LookupHTLCs(paymentHash)`

One way to look up this information for incoming exit hop htlcs is through the invoices rpc. With the ongoing decomposition of `lnd` though, the invoices subsystem may no longer be used (https://github.com/lightningnetwork/lnd/issues/6036).

An external component connected via the interceptor api can keep track of the incoming htlcs, but the most reliable record of what happened on a channel still lies within lnd. If there is a problem, the best option would be to inspect that ground truth.

Also in the case where the invoices subsystem is used, it can happen that an invoice is marked as settled, but that lnd eventually did lose the htlc because of down time. The invoice state will incorrectly remain `settled`.

Related to this is https://github.com/lightningnetwork/lnd/issues/4910, but the `fwdinghistory` call doesn't seem to have the query options to make it scalable to millions of htlcs. In that same issue, `SubscribeHtlcEvents` is mentioned as an alternative. The problem with that call is that it isn't meant to be fully reliable either and still relies on external record keeping.

**Comment by joostjager** [comment]
>the most reliable record of what happened on a channel still lies within lnd

Actually, maybe I am wrong here? I was thinking of the revocation log as the source of truth. That contains all past commitment transactions with the htlcs on them, but I think it doesn't tell you what happened to the htlc. At some point, the htlc disappears again, but it is then unknown whether that's due to a fail or a settle. 

An indication is in the balance change, but doesn't seem solid either. If two htlcs of amount X (total 2X) are removed in the same commitment transaction and the balance shifts only by X, I don't think you can be certain which of the two htlcs settled and which one failed.

Are there any alternatives here or is this data just not available currently?

**Comment by carlaKC** [comment]
> but I think it doesn't tell you what happened to the htlc. At some point, the htlc disappears again, but it is then unknown whether that's due to a fail or a settle.

Yeah indeed, afaik you end up with a weird subset-sum issue trying to reconstruct from revocation logs. Not aware of alternatives. 

I believe the desired direction would be to store the information in the revocation log differently, so that it has more of a "diff" systems. Sensitive piece of code to touch though.

**Comment by joostjager** [comment]
PR https://github.com/lightningnetwork/lnd/pull/6517 is a first attempt at adding an htlc lookup rpc.

**Comment by joostjager** [comment]
Related/partially overlapping: https://github.com/lightningnetwork/lnd/issues/4088
