### ISSUE TITLE
Out of date documentation on lightning.community

### ISSUE THREAD

**Issue by mohamedmansour** [lightningnetwork/lnd#622]
Hello the installation documentation is out of date:

https://dev.lightning.community/guides/installation/

There are no `--bitcoin.rpcuser` or `--bitcoin.rpcpass`, it should be renamed to `--btcd.rpcuser`

Any plans to update them :) I would have done so but can't find the web source. All new users to lightning network on that site will be lost.

**Comment by aakselrod** [comment]
There is already a PR for these changes: https://github.com/lightninglabs/lightning-dev-site/pull/22

**Comment by MeshCollider** [comment]
Because this is an issue on the wrong repo I think it can be closed
