### ISSUE TITLE
Unsafe hand-off from contractcourt to switch

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6223]
### Background

Raising this issue to bring attention to the following line:

https://github.com/lightningnetwork/lnd/blob/60625b6c1a0b8beff30f80e3b245f6518770c588/contractcourt/htlc_timeout_resolver.go#L182

This call ends up in `Switch.ProcessContractResolution` where the resolution is posted to a channel. After that, the onchain resolver will be marked as completed. But if lnd crashes right after that, I don't think switch will ever hear back about this outcome? If a local payment is pending, it may remain pending forever?

### Your environment

* lnd 0.14.2-beta

**Comment by Crypt-iQ** [comment]
This is a dupe of https://github.com/lightningnetwork/lnd/issues/2998 the callsite is mentioned in the issue

**Comment by joostjager** [comment]
I knew there had been an issue for this at one point, but wasn't able to find it. But yes, #2998 was what I remembered. Will close this one.
