### ISSUE TITLE
Try to handle lost channels

### ISSUE THREAD

**Issue by stevenroose** [lightningnetwork/lnd#624]
With an upgrade, I had to delete the channel database (yeah I should have renamed it to be able to close the channels afterwards) and the `DescribeGraph` rpc still shows the channels, but lnd is not aware of them.

There is probably not much it can do, since it doesn't have the closing txs etc. Perhaps the best thing would be to contact the peers (when it finds them) and kindly ask to close the channel (even though this would make them pay for the closing, which will make them reluctant to do it).

**Comment by Roasbeef** [comment]
This isn't an issue. This is testnet, people don't care about their channels lol. When real money is involved, you can be sure people will go through any measures necessary to regain their coins. 

If you know there's a breaking change, and you're about to update, we recommend closing out all the channels beforehand. There're measures in the protocol for recovery of channels after partial data loss. 

Additionally, if a channel hasn't sent out a "heart beat" in a long time, then we'll prune it from our graph.

**Comment by stevenroose** [comment]
It's true that with real money, people will be a lot more cautious before upgrading. However, if there is something lnd can do, there is no harm in doing so.

I do realize however, that when lnd takes specific action, it might somehow reveal to the counterpart that it lost access, allowing him to close the channels in his favor.

**Comment by leblitzdick** [comment]
After a crazy update to version 0.4.1 i lost about 8 channels. i did not refund them with closechannels before upgrading to the new version, so i see them in 1ml.com but i have no access to them with my lnd:

[lncli] rpc error: code = Unknown desc = unable to find channel

I am on the mainnet, so there is real money in it, not much, but it will be nice to get it back and have a "realistic" channel count in 1ml.com

**Comment by halseth** [comment]
@leblitzdick Upgrading from `0.4` to `0.4.1` shouldn't affect your channels. Do you see any in `listchannels`?

**Comment by stevenroose** [comment]
(I guess he updated from `0.3.*` instead. Otherwise wouldn't be as _crazy_ ;)

**Comment by Roasbeef** [comment]
You simply need to force close those channels. Look at `lncli closechannel
-h`.

**Comment by leblitzdick** [comment]
Not that simple i think. The channel example is not the output from the current lncli listchannels. I only have the output of lncli listchannels (0.4.0 version) as an textfile. it is only a copy of the output! 

Then i type lncli listchannels (0.4.1 version) at the moment no "old" channels (textfile) are listed.

So lncli closechannel with or without --force are not working, because the channel ids are not known by the current LND (0.4.1 version)

sorry a little bit tricky to describe...

**Comment by Roasbeef** [comment]
It's possible that the remote party closed out those channels while you were offline. Note that the channel itself was _very_ small, as a result, we got those funds immediately (since it was the remote peer that force closed). No channels were lost as there were not breaking changes. 

> In 1ml.com all the channel ids are visible, but since the update i lost control about them.
Explorers aren't authoritative, these are your channels, not theirs.

**Comment by leblitzdick** [comment]
No i don't think so, the 10 remaining channels that i cant't close are still there and the funding isn't withdraw to my wallet. if I compare the accounts there is a difference.

So i try to contact these nodes to close the channel and release the funding.
But it is hard to contacting the owners of the nodes, some have websites with emails but some do not. Is there a way to identify them via the network or to send them messages?

**Comment by Roasbeef** [comment]
> I only see channels established since the upgrade.

There we're no breaking changes between those two versions. I'd check to ensure you didn't modify the data directories during update. 

A bigger question is: how exactly did you update? 

> Is there a way to identify them via the network or to send them messages?

Generally, no...

**Comment by leblitzdick** [comment]
I simply stop the Node with lncli stop, install the new Software version and start it again. I don't modify anything in the .lnd Directory! 
Maybe i don't remember every step i do, passing 2 week since i do this, but modifications in .lnd i will remember.

**Comment by Roasbeef** [comment]
You must have done something in-between. There were _no_ breaking changes between those versions.

**Comment by leblitzdick** [comment]
back to my problem, if I turn off my node, the inactive channels should eventually be closed because of inactivity. Would that be a way to force empty the channels?
And if yes, wow long would that take? Days, weeks, months or maybe "TimeLockDelta" ?

**Comment by stevenroose** [comment]
@leblitzdick If you have old channels where you don't have control over, they might never closes. You're relying on the counterparties of that channels to close them. If they don't, I guess they can never be closed.

**Comment by leblitzdick** [comment]
So i take my Node offline for a couple off and see what happens. I hope they will be closed off inactivity, but you right, it's in the hands off the counterparties.

**Comment by stevenroose** [comment]
I'm gonna close this.
