### ISSUE TITLE
Sendcoins returns unknown address type

### ISSUE THREAD

**Issue by atseth** [lightningnetwork/lnd#6247]
### Background

Litecoin Lnd wallet shows on chain coins available.  Using sendcoins command returns unknown address type error.  Is there any way to transfer my coins from lnd to another Litecoin wallet?

### Your environment

* Version 0.14.2
* Windows
* Litecoind v 0.18
* any other relevant environment details

### Steps to reproduce

Transfer liteccoins to lnd wallet.  Verify coins available using walletbalance command.  Use sendcoins command to transfer back out again.  Lnd returns unknown address type error.

**Comment by alexbosworth** [comment]
try the old style ltc addresses not the bech32 type

**Comment by hieblmi** [comment]
Given the activity here and the removal of litecoin support in lnd I think we can close this issue.
