### ISSUE TITLE
Payment status: IN_FLIGHT (stuck)

### ISSUE THREAD

**Issue by dolcalmi** [lightningnetwork/lnd#6249]
### Background

We have this problem since last year, but recently the number of cases has been increasing (~2 per day).  Basically is the same behavior exposed here https://github.com/lightningnetwork/lnd/issues/5396.

Related issues: https://github.com/lightningnetwork/lnd/issues/5396 - https://github.com/lightningnetwork/lnd/issues/4788 - https://github.com/lightningnetwork/lnd/issues/5461

Details:

- trackpayment: returns IN_FLIGHT
- invoice: expired
- timelock: expired
- output channel: without pending HTLCs
- in some cases we could confirm with the destination node that payment was not fulfilled

please check below some logs (it is a summary but in general are the same 4 records per attempt)

```
2022-02-10 19:27:46.205 [DBG] CRTR: Payment 0217d96c0104366b8d75cb8057d4ea1838e3620fe29569d8ab94cc1c0ac84111 in state terminate=false, active_shards=1, rem_value=0 mSAT, fee_limit=0 mSAT
2022-02-10 19:27:46.205 [INF] CRTR: Resuming payment shard 1043689 for payment 0217d96c0104366b8d75cb8057d4ea1838e3620fe29569d8ab94cc1c0ac84111
2022-02-10 19:27:45.850 [INF] CRTR: Resuming payment 0217d96c0104366b8d75cb8057d4ea1838e3620fe29569d8ab94cc1c0ac84111
2022-02-10 19:26:11.927 [ERR] CRTR: Resuming payment 0217d96c0104366b8d75cb8057d4ea1838e3620fe29569d8ab94cc1c0ac84111 failed: htlcswitch shutting down.
```

in this specific case time lock was 721995 and payment was created 2/4/2022, 14:32:03

### Your environment

* version of `lnd`:v0.14.2-beta

### Steps to reproduce

not sure

### Expected behaviour

Track payment should return failed if it was not completed before expiration

### Actual behaviour

trackpayment shows IN_FLIGHT even after expiration

**Comment by dolcalmi** [comment]
cc @nicolasburtey

**Comment by alexbosworth** [comment]
Another related PR now: https://github.com/lightningnetwork/lnd/pull/6352

**Comment by ClayShoaf** [comment]
When you say "resolve that on chain", let's say it's a payment that I tried to send. Would it go back to my wallet, or would it have to wait for the channels that I tried to hop across to close?

**Comment by alexbosworth** [comment]
HTLCs resolve in two different ways:

1. You get a refund of the funds going out, after a timeout
2. The funds are successfully sent towards their destination

**Comment by ClayShoaf** [comment]
Thank you for the replies!
