### ISSUE TITLE
Ignoring Base Fee

### ISSUE THREAD

**Issue by pud-micha** [lightningnetwork/lnd#6256]
### Background

As described here
https://lnrouter.app/graph/zero-base-fee
and here
https://arxiv.org/abs/2107.05322
the base fee is a real problem in pathfinding. There are many open channels in the field. But if you can only open a new channel without a base fee then over time every channel will have none and the network is as efficient as possible.

### Expected behaviour

Every new channel should have a fee_base_msat = 0 and ignore any given value. So even if fee_base_msat != 0 then it must be set to 0 by the program.
I think I found the right spot in /lnd/routing/localchans/manager.go but I'm not really sure.

Thank you.

**Comment by yyforyongyu** [comment]
The market decides the base fee, not the code. That being said, algorithms should reflect reality, not bend it. Closed.

**Comment by pud-micha** [comment]
Code is not the "market". A percentage rate is enough for a "market". A fixed base fee is bad for the network efficency. Better code is always better than bad code. You say that you like to have a slow inefficient and unreliable network. Okay. Than say it. "market" pfff. I hope some day the firefighters have a market too and burn cities down to make their shareholders happy ...

**Comment by mineralf** [comment]
As there are good arguments for #zeroBaseFee in path finding I would not prevent it at all but at least honestly think about a default 0 value in the future.
As a lot of plebs don't change the default fees ever the defaults will have a big impact.
But it seems like the defaults are as difficult to change as the bitcoin consensus rules ;) see also https://github.com/lightningnetwork/lnd/issues/4954

**Comment by pud-micha** [comment]
Maybe a way out of this can be an official fork with a nice name like "LNDzero". So the users can choose and promote the right thing without long explainations how to config this "new" lnd.
