### ISSUE TITLE
Very low Commitment Fee with CLightning Channels (STATIC_REMOTE_KEY)

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6257]
### Background

A lot of node runners were complaining about commitment transaction which were not confirming because of a low feerate of 1.02 sats/vbyte. The Commitment Tx with such a low fee which were force-closed had no stuck HTLCs so I am not sure how the commitment TX Fee will change. Anchor Channels are not critical with such low feerate, however STATIC_REMOTE_KEY channels should in General aim for higher fees because there is now way to feebump them for the party which is closing the channel. Which could be a potential security issue when HTLCs are part of the Commitment TX.

### Your environment

* version of `lnd`: v0.14.1-beta"
* which operating system: aarch64 GNU/Linux
* version of  `bitcoind` backend
* any other relevant environment details

### Steps to reproduce

Let a CLightning Node open a Channel to an LND node.

### Expected behaviour

LND aims for higher fees (overestimating), only for STATIC_REMOTE_KEYs

### Actual behaviour
Feerate for Commitment TX with CLI nodes (when mempool fees were high)

```
025407ac7bd16419f4ae9e7827665c031323184514618c390278ec4a2708d3558f ChannelType:: STATIC_REMOTE_KEY Feerate:  2.12
0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f ChannelType:: STATIC_REMOTE_KEY Feerate:  1.012
0337694505123a12a8fadd95523dcc235898ad3b80a06e4a63ca26fed68dd0d17c ChannelType:: STATIC_REMOTE_KEY Feerate:  2.12
```

From anther Node:
```
035eb7d2253d934b51dd 035eb7d2253d934b51dd1cc145b6f36a9c2d953c4379f5fff9c39bb437ece525ae ChannelType:: STATIC_REMOTE_KEY Feerate:  2.272
Hyper-capitalist 03e3fc2b4f0aeb2e17866b4134e3fb0800ab11ca54f30ccc8b6d927209d2f57602 ChannelType:: STATIC_REMOTE_KEY Feerate:  2.12
```

Feerate for LND <=> LND Nodes where around 10 sat/vbyte when recording this issue which is reasonable for STATIC_REMOTE_KEYS

**Comment by ziggie1984** [comment]
In addition to the Commitment TX fee, the local constraints with CLI Nodes show weird values:

```
 "local_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "58607",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "18446744073709551615",
                "min_htlc_msat": "0",
                "max_accepted_htlcs": 30
            },
```

Especially the High Max_Pending_AMT_MSAT

**Comment by ziggie1984** [comment]
Some other stats form another node:

```
020d1617e27ac022395352f2b3774969593d3d6ddff6fb117d820a9dda8da45217 (Probably CLI Node) ChannelType:: STATIC_REMOTE_KEY Feerate:  2.012
023ffea7f9a3c3ae9c36963618c07fc3f8e0e794e685c53e63b4430a4fe2a305cb (Probably CLI Node) ChannelType:: STATIC_REMOTE_KEY Feerate:  2.012
0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f(100%CLI Node) ChannelType:: STATIC_REMOTE_KEY Feerate:  1.012
0337694505123a12a8fadd95523dcc235898ad3b80a06e4a63ca26fed68dd0d17c (100%CLI Node) ChannelType:: STATIC_REMOTE_KEY Feerate:  2.012

```

**Comment by guggero** [comment]
> Especially the High Max_Pending_AMT_MSAT

Those are the values that c-lightning is sending over as the constraints on the local channel. lnd just takes them as they are received in the channel open message.

I could be wrong on this, but from a quick look into the code it seems to me that lnd just accepts any fee update from the remote as long as it's not _too large_. So maybe this also is just a different behavior in c-lightning that would need to be adjusted there?

In any case, anchor channels aim to solve this exact problem. And with all major implementations now implementing or rolling out anchor channels, this should happen less often.

**Comment by Roasbeef** [comment]
To add to the above, the _initiator_ is the one that controls the fee rate being used. If we accept a channel and they have a low fee rate, we can't do much about it. If it's an anchor channel, then we know we can bump the fee via CPFP post broadcast. We don't change the fee rate _we_ propose based on the implementation of the node (lnd has no visibility into that rn).

**Comment by Roasbeef** [comment]
>  lnd just accepts any fee update from the remote as long as it's not too large

To add to this, without anchors, if the initiator\ sends you a super low fee rate, your only course of action is to force close with the prior fee rate (assuming it's high, but maybe that was low as well).

**Comment by Roasbeef** [comment]
Closing as anchors resolves issues with `update_fee` and if we're the initiator, then we can't select the fees at all.
