### ISSUE TITLE
Cannot open channel: [lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@'

### ISSUE THREAD

**Issue by zynos** [lightningnetwork/lnd#6264]
### Background

I want to open a channel with the command:
```
lncli openchannel --sat_per_vbyte 2 0270a90e7dc244dc372d244b59bbcaa4fbce86c1d5a592e95d7eeecfb2136c309e@mtgxbwu72mrv4r4dduziu7xgesynnu55szobg4vic2qjoopelearujqd.onion:9735 100000 0
```
But i receive this error
`[lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@'`

I could connect succesfully with this command:
```
lncli connect 0270a90e7dc244dc372d244b59bbcaa4fbce86c1d5a592e95d7eeecfb2136c309e@mtgxbwu72mrv4r4dduziu7xgesynnu55szobg4vic2qjoopelearujqd.onion:9735
```

and received this response
```
{

}
```

### Your environment

* lnd version 0.14.2-beta commit=v0.14.2-beta
* Debian GNU/Linux 11 (bullseye)
* Bitcoin Core RPC client version v22.0.0
* on Raspberry PI 8 GB RAM

**Comment by Roasbeef** [comment]
See `lncli openchannel -h`. You're specifying the wrong arguments.
