### ISSUE TITLE
Baking macaroon with `macaroon:generate` indirectly grants all permissions

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#6265]
### Background

If I create a macaroon using `lncli bakemacaroon` with the `macaroon:generate` permission, I can then use that macaroon to create another macaroon with any permissions. For example, if the first macaroon only has `info:read` and `macaroon:generate`, it can be used to create a second macaroon with whichever permissions I'd like such as `onchain:write`, `offchain:write`, etc... In effect, the `macaroon:generate` permission de facto grants every other permission indirectly.

Perhaps this is intentional, but it seemed unintuitive to me and a potential security concern. I would have expected a macaroon with the `macaroon:generate` permission to only create macaroons with a subset of the permissions it has been granted.

### Your environment

* lnd 0.14.2

### Steps to reproduce

Create a macaroon with `lncli bakemacaroon macaroon:generate` and use that macaroon to create additional macaroons with whichever permissions you would like.

### Expected behaviour

A macaroon with `macaroon:generate` can only create macaroons with a subset of its own permissions. This could perhaps be done by passing in the raw macaroon on the grpc request and inspecting which permissions it has within lnd.

### Actual behaviour

A macaroon with `macaroon:generate` can create macaroons with any permissions regardless of its own permissions.

**Comment by Roasbeef** [comment]
> A macaroon with macaroon:generate can only create macaroons with a subset of its own permissions. This could perhaps be done by passing in the raw macaroon on the grpc request and inspecting which permissions it has within lnd.

This would need to be another set of caveats. The bake call checks that the request has the macaroon required to bake them generally. What you want here is another layer of verification, [_within_ the bake call itself](https://github.com/lightningnetwork/lnd/blob/28ea2736a04566b06c38533e5e48e1b8d185a49b/rpcserver.go#L7090), to introspect into the macaroon that was used to call _it_.

**Comment by sangaman** [comment]
Thanks for the explanations. The rough use case I had in mind was generating a macaroon with some subset of permissions including the `macaroon:generate` permission, and then using that macaroon to be able to create other macaroons with narrower subsets of permissions. This would allow us to leave `admin.macaroon` under tight controls, and not have to go back and access it whenever we want to create another macaroon with narrow permissions.

Inspecting the the macaroon in the bake call is what I had in mind for how such functionality could be implemented.

This isn't a critical piece of functionality by any means, I understand the current behavior but perhaps it could be made a little clearer that any macaroon with `macaroon:generate` is equivalent to the full admin macaroon. It makes me wonder a bit why this would even be its own permission - in other words baking a macaroon with `macaroon:generate` seems functionally equivalent to cloning `admin.macaroon`?

**Comment by guggero** [comment]
> It makes me wonder a bit why this would even be its own permission

The main reason is that the `admin.macaroon` cannot be revoked (because it is derived from the non-deletable default root key ID `0`). So you might never want to use that. Instead you'd create a new admin-like macaroon from a different root key that you could use to bake new macaroons but you could also revoke (by removing the non-default root key from the macaroons DB).

I guess what you'd need for your use case is a new _caveat_ instead. A caveat that would allow you to **narrow** the current set of permissions. And since anyone can add caveats, you wouldn't need the bake permission.

For example, the macaroon could be issued with `chain:read offchain:read peers:read macaroons:read` and the user could then add a caveat saying `revoke-permissions macaroons:read` which would downgrade the macaroon to just `chain:read offchain:read peers:read`.

**Comment by sangaman** [comment]
Thanks for the explanation. I think that's fine for our use cases, we'll just need to add these caveats without the help of lnd (if I understand correctly).

I'm closing this issue since I don't believe there's any further action or explanation necessary. Thank you.
