### ISSUE TITLE
multi: permit sending to and receiving from P2TR addresses

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6266]
On the road to extending our RPC APIs to fully encompass all the new taporot related components, we'll need to add support for sending + receiving. For sending, we just need to update to the latest `btcutil` version. For receiving, we're blocked on some underlying `btcwallet` changes, that'll eventually bubble up into new RPCs on the `lnd` level. 

# Steps To Completion
- [ ] Update `lnd` to [`btcutil v1.1.0` ](https://github.com/btcsuite/btcd/releases/tag/btcutil%2Fv1.1.0). After this, anyone can send to a `bech32m` address. 
   * We _might_ want to get this on a check to the backend to make sure it'll actually allow these transaction types to be propagated. 
- [ ] Add a new [address type enum](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/walletrpc/walletkit.proto#L322) for the `NewAddress` call.

**Comment by alexbosworth** [comment]
Will the existing Neutrino recognize receiving on p2tr?

**Comment by Roasbeef** [comment]
> Will the existing Neutrino recognize receiving on p2tr?

As in will they recognize receiving coins if the transaction _inputs_ spend from p2tr? Yes. 

When we update neutrino to use the new version of `btcwallet`, then it'll automatically be able to detects spends/credits related to the addresses. We don't need to modify the BIP 158/157 filters to support basic taproot items. If we want to allow things like matching based on the reveal of a particular internal key or leaf revealed, then we need a new filter type that inserts special items from the witness.

**Comment by Roasbeef** [comment]
Related PR: https://github.com/btcsuite/btcwallet/pull/792
