### ISSUE TITLE
Halseth key in repo is expired

### ISSUE THREAD

**Issue by setpill** [lightningnetwork/lnd#6272]
### Background

I thought I could switch away from Zoom-owned keybase for importing keys to verify lnd releases, but it seems not.

### Steps to reproduce

```bash
$ curl https://raw.githubusercontent.com/lightningnetwork/lnd/master/scripts/keys/halseth.asc | gpg --import
$ gpg --list-keys | grep -C 1 -e 15BAADA29DA20D26
```

NB: This assumes a more up to date version of the pubkey is not already in the keyring. If it is, you can delete it by first running

```bash
$ gpg --delete-key 15BAADA29DA20D26
```

### Expected behaviour

```
pub   rsa2048 2017-08-10 [SC] [expires: 2023-08-25]
      7AB3D7F5911708842796513415BAADA29DA20D26
uid           [ unknown] Johan T Halseth <johanth@gmail.com>
```

### Actual behaviour

```
pub   rsa2048 2017-08-10 [SC] [expired: 2021-08-25]
      7AB3D7F5911708842796513415BAADA29DA20D26
uid           [ expired] Johan T Halseth <johanth@gmail.com>
```

### Additional notes

The key expired before it was committed to this repo. Please consider investing in some automated checks against this kind of thing.

**Comment by guggero** [comment]
Yeah, this slipped through. The initial PR was created way before the key expired (https://github.com/lightningnetwork/lnd/pull/5053) but then we didn't check again. We'll need some automation to detect this.
In the meantime we're just going to remove that key since they're not an active contributor anymore.
Thanks for auditing the keys in the first place!

**Comment by setpill** [comment]
```bash
cat halseth.asc | gpg --with-colons --import-options show-only --import | awk -F':' -vtwoweeks=$(date -d "2 weeks" +%s) '{ if (($1 == "pub" || $1 == "sub") && $7 < twoweeks) {print $1 "key expires in less than two weeks"} }'
```

Might serve as some inspiration.

**Comment by guggero** [comment]
Created a PR (#6280) to remove two expired or about to expire keys. Will look at automating the warning in the future (going to create a separate issue for that).
