### ISSUE TITLE
During initial sync via neutrino, if no peers are available/reachable, lnd crashes

### ISSUE THREAD

**Issue by losh11** [lightningnetwork/lnd#6292]
If the wallet is in its initial sync using neutrino, whilst being recovered, and midway through the sync looses connection to other nodes, whilst still having access to networking, lnd will panic crash with error message `unable to synchronize wallet to chain: unable to perform wallet recovery`. 

I don't think this is really a concern with regular laptop/pc, but in our usecase we are building a mobile. From our previous experience building non-custodial mobile wallets, we've had users find that certain ISPs and mobile operators 'ban' access to the bitcoin ports. We've also seen issues when users devices are switching between wifi/mobile data, one of which bans access to the bitcoin ports; these situations will lead lnd to panic crash.

### Your environment

* lnd: 0.14.2
* Ubuntu 20.04 WSL2
* neutrino

**Comment by guggero** [comment]
This was fixed by https://github.com/btcsuite/btcwallet/pull/870 which was included in the `btcwallet` version bump PR https://github.com/lightningnetwork/lnd/pull/7767.
