### ISSUE TITLE
update mobile build to expose all relevant sub-severs 

### ISSUE THREAD

**Issue by martinlachev** [lightningnetwork/lnd#6296]
### Background

Hi guys, I have an issue that when the user stays in the wallet, and new blocks are being mined, my pending on-chain transactions(the one that has 6 or fewer confirmations)  are not updating, unless I get a new transaction from SubscribeTransaction method, or call GetTransactions once more. I saw that there is a method for that RegisterConfirmationsNtfn and I want to ask how to use it?

### Your environment

* version of `lnd` - latest
* which operating system (`uname -a` on *Nix) - Neutrino iOS
* version of `btcd`, `bitcoind`, or other backend  - the default from Neutrino

### Steps to reproduce

Try to subscribe for RegisterConfirmationsNtfn method from LndMobile 

### Expected behavior

Be able to use it 

### Actual behavior

Not being able to use it

**Comment by HannahMR** [comment]
Okay so you’re using LND mobile on a iOS device to query Neutrino for the status of a transaction, specifically the number of confirmations a transaction has? 

I’m a bit unclear on if you are you already trying to use RegisterConfirmationsNtfn or you are considering using it. Can you clarify?

When are you expecting to be notified, and when/how do you know that it has failed?

What do the LND logs say during this time?

**Comment by Roasbeef** [comment]
If you add this extra option, then the notifier RPC sub-server will be available: 
 https://github.com/lightningnetwork/lnd/tree/master/mobile#options

**Comment by martinlachev** [comment]
Hi, guys, thanks for the response,  I have tried building the framework with make ios prefix=1 but I did not get the methods available in my LndMobile.obj binary. :(
![Screenshot 2022-02-27 at 21 43 03](https://user-images.githubusercontent.com/17933549/155901630-6b0f030b-26d3-4248-be76-dd252bd09769.png)
![Screenshot 2022-02-27 at 22 26 28](https://user-images.githubusercontent.com/17933549/155901632-7b850809-6978-4c68-83af-83c4b8c7b75a.png)
![Screenshot 2022-02-27 at 16 26 11](https://user-images.githubusercontent.com/17933549/155901636-166e8275-c645-4f4c-be01-312d7ffdce44.png)

**Comment by Roasbeef** [comment]
Can you try this patch? 
```diff
diff --git a/mobile/gen_bindings.sh b/mobile/gen_bindings.sh
index 36b478b2b..80aa8c2f5 100755
--- a/mobile/gen_bindings.sh
+++ b/mobile/gen_bindings.sh
@@ -33,13 +33,13 @@ target_pkg="github.com/lightningnetwork/lnd/lnrpc"
 
 # A mapping from grpc service to name of the custom listeners. The grpc server
 # must be configured to listen on these.
-listeners="lightning=lightningLis walletunlocker=lightningLis state=lightningLis"
+listeners="lightning=lightningLis walletunlocker=lightningLis state=lightningLis chainnotifier=lightningLis"
 
 # Set to 1 to create boiler plate grpc client code and listeners. If more than
 # one proto file is being parsed, it should only be done once.
 mem_rpc=1
 
-PROTOS="lightning.proto walletunlocker.proto stateservice.proto"
+PROTOS="lightning.proto walletunlocker.proto stateservice.proto chainrpc/chainnotifier.proto"
 
 opts="package_name=$pkg,target_package=$target_pkg,listeners=$listeners,mem_rpc=$mem_rpc"
 ```

**Comment by martinlachev** [comment]
Hi, I was able to build the framework by adding a "chainrpc"  to [this](https://github.com/lightningnetwork/lnd/blob/28389fe38c319d3d45efa27aeb93b88b6def3a64/Makefile#L304) line in Makefile, should I make a PR and add it as default or maybe enhance the docs for the mobile build, what do you guys think is the better approach, thanks? :)

**Comment by Roasbeef** [comment]
> Hi, I was able to build the framework by adding a "chainrpc" to [this](https://github.com/lightningnetwork/lnd/blob/28389fe38c319d3d45efa27aeb93b88b6def3a64/Makefile#L304) line in Makefile,

Ahh of course, nice find! 

> should I make a PR and add it as default or maybe enhance the docs for the mobile build, what do you guys think is the better approach, thanks?

Sure! I think we may even take the leap and just add the other sub-server RPCs by default, since many of them actually have the newer set of more modern calls.

**Comment by martinlachev** [comment]
Sorry for not responding for so long but I have been trying to use RegisterConfirmationsNtfn and I need some help with figuring out how to provide script parameters for this RPC request. It should be an output script and from my research, it is connected to a UTXO, can you guys help me figure out this?

**Comment by Roasbeef** [comment]
@martinlachev do you still plan on making that PR to expose the rest of the sub-servers? 

That's the output script of one of the outputs of the transaction you're waiting for confirmation of.

**Comment by kaloudis** [comment]
Tackling this here: https://github.com/lightningnetwork/lnd/pull/6464

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/6464
