### ISSUE TITLE
Trying to close channels and withdraw funds back to layer 1 from my LND wallet/node

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#6297]
LND Version: 0.13.3-beta

I booted up my LND node for the first time in a long time and it gets stuck on this syncing stage:

>  `2022-02-25 11:00:15.787 [INF] LNWL: Started rescan from block 00000000000000000006915cd8f7fe110fb309371e902fe326f8b105d545a073 (height 712809) for 21 addresses`

I left it on overnight and nothing changed so I decided to reboot the node and see if it made any difference but it still gets stuck on this step.

I need to get my node synced and my channels closed because I am trying to get my BTC back on layer 1.

**Comment by alexbosworth** [comment]
If you are running bitcoind you can add this to your bitcoin.conf

`debug=rpc`

It will let you see RPC calls in the bitcoin core logs

Then you can see if requests are being made to do the scanning, or if it's not doing anything

**Comment by Roasbeef** [comment]
Closing as the rescan just needs to finish, though it is several thousand blocks behind. Will re-open if the rescan finishes and you can't access the funds.

**Comment by jaxkeiser** [comment]
If you close the rescan while it is in progress, will it continue where it left off when you start it again?
