### ISSUE TITLE
Switch to 2-layer HTLC's 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#63]
Switch HTLC structure back to the format which was originally in the paper. 

See: https://lists.linuxfoundation.org/pipermail/lightning-dev/2015-November/000339.html

**Comment by cjamthagen** [comment]
Will start working on this.

**Comment by AndrewSamokhvalov** [comment]
Hi @cjamthagen! I think the @Roasbeef will take this one, but lets wait for him.

**Comment by cjamthagen** [comment]
Ah, thanks for letting me know.

**Comment by cjamthagen** [comment]
Just so I know, are `advanced` issues off the table, so to speak? Are other issues that no one claimed yet up for grabs? Let me know. @AndrewSamokhvalov @Roasbeef

**Comment by AndrewSamokhvalov** [comment]
@cjamthagen I think there are plenty of [them](https://github.com/lightningnetwork/lnd/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.2-alpha) 😄

**Comment by cjamthagen** [comment]
Not questioning the amount of issues available. Just wondering if some of them, like this one, are being worked on already.

**Comment by Roasbeef** [comment]
Heya, yeah @AndrewSamokhvalov is right, I'll be implementing this in the near future. Generally, the issues tagged `advanced` are up for grabs other than this one and #59.

**Comment by cjamthagen** [comment]
Ok, thanks for letting me know. I'll stop working on #59 then. Man.. you're hogging all the fun ones for yourself :)

**Comment by Roasbeef** [comment]
Fixed.
