### ISSUE TITLE
Are there supported upgrade paths? Can I 0.13.3 to 0.14.2 ?

### ISSUE THREAD

**Issue by feikede** [lightningnetwork/lnd#6302]
### Background

Is there a recommended upgrade path? I am still on 0.13.3. Can I upgrade to 0.14.2? 
In 0.14.0 are some database migrations. Will they also apply if I skip 0.14.0?

### Your environment

0.13.3

**Comment by lucasdcf** [comment]
Yes, you can upgrade directly to 0.14.2.
