### ISSUE TITLE
Insufficient Bandwidth to route HTLC

### ISSUE THREAD

**Issue by Deekee62** [lightningnetwork/lnd#6303]
### Background

Failed forwards due to "insufficient bandwidth to route htlc" but there is enough outbound liquidity. Some knowledgeable noderunners have already cross checked and confirmed that this indeed is a strange behavior indeed.

### Your environment

* LND Version: 0.14.2-beta
* Linux umbrel 5.10.17-v8+ 1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
* Bitcoin Version: 220000,
Subversion: Satoshi:22.0.0
Protocol Version: 70016

**Hardware Details**
Hardware: BCM2835
Revision: d03114
Serial: 100000000b2d1319
Model: Raspberry Pi 4 Model B Rev 1.4

### Steps to reproduce

Hard to say how this can be reproduced, at least one peer has reported that about 10% of his forwards show the same behavior.

Below some more details I’ve checked:

- Incomig and out going balance is more than sufficient
- There are no HTLC limits on both sides
- There are no HTLC’s in-flight
- There is no disabled flag on either end of the channel

Below please find a 2 screenshot which document the behaviour:

![telegram-cloud-photo-size-4-5819205817772128712-y](https://user-images.githubusercontent.com/33904339/156243872-f8ebdf8d-e9b4-40ae-aa2a-89ea2e07b17e.jpg)

![telegram-cloud-photo-size-4-5819205817772128713-y](https://user-images.githubusercontent.com/33904339/156243903-9ca3ffae-0942-4537-be3a-9fd410b7666d.jpg)

### Expected behaviour

Forwards should not fail if the is enough liquidity, see example above.

4'651K incoming remote 
3'982K outgoing local
2'547K forwarding amount

### Actual behaviour

Some forwards fail although sufficient liquidity is available.

Any assistance or guidance would be very much appreciated!

Many thanks in advance and have a nice day!

**Comment by Roasbeef** [comment]
There's a log line there about "violated target outgoing link", so that HTLC violated the policy for that link, but we send back the generic "insufficient bandwidth" error internally.

**Comment by positiveblue** [comment]
@Deekee62 also, just on top of the line @Roasbeef is talking about, could you put the full line? I think the format is

`insufficient bandwidth to route htlc: {ammount to forward} is larger than {channel outgoing bandwidth}` Are those numbers approx  2.5M and 3.9M?

**Comment by Deekee62** [comment]
Here another complete example:

<img width="402" alt="HTLC_24638" src="https://user-images.githubusercontent.com/33904339/156562485-7188f801-8b8f-453c-ac40-61ea866ff35d.png">

<img width="2435" alt="image" src="https://user-images.githubusercontent.com/33904339/156562635-a9402007-5280-4d82-b4b0-52621a8bd01c.png">

1'176'859K outgoing local
899'820K forwarding amount

I hope the data provided is sufficient and have a nice day :-)

**Comment by Roasbeef** [comment]
In that screen shot, you can see that after accounting for the channel reserve, the channel doesn't have enough bandwidth to forward the HTLC.

**Comment by Deekee62** [comment]
But the channel reserve is only 40'000 sats, so the is still enough liquidity!!

**Comment by Roasbeef** [comment]
I'd check the other parameters of the channel, including the "max value in flight" field. What you've shown is what lnd used to make the forwarding decision. I recommend monitoring the logs more so you can see how things are accounted for. Also in the future screen shots of logs are harder for us to parse at times [than using a paste bin](https://0bin.net/).

**Comment by Ripley81** [comment]
Hey Deekee62 - what command do you use to find that view with the HTLC? I suspect I have similar issues, or at least I'm not understanding the calculations involved when assessing routing ability.

<img width="2072" alt="chargelnd@raspibolt: ~ — ssh admin@raspibolt local — 251×22 2023-03-14 07-25-08" src="https://user-images.githubusercontent.com/28821403/224914172-dcf474ca-2a11-4340-8bb4-47143de6824a.png">
