### ISSUE TITLE
 1.72 Patch causing start up loop due to possible permission error?

### ISSUE THREAD

**Issue by Superhans79** [lightningnetwork/lnd#6304]
### Background
I have a LND On raspberry PI and I tried to patch it to 1.72 using the menu supplied by LND - It updated but when I tried to rebbot the startup process goes into an endless loop.

### Your environment

1.72

Built on Rasperry PI

### Steps to reproduce

i JUST REBOOT

### Expected behaviour

Boot up to LND

### Actual behaviour

i GET A MESSAGE STATING :+1:
/home/admin/00infoLCD.sh line 100: /home/admin/setup.scripts/eventInforwait.sh permission denied
/home/admin/_cashe.sh line 198: redis-sli command not found

Do i just need to amend permission

**Comment by Superhans79** [comment]
Okay so I am running this on a raspberry pi and I am logging on via ssh on my Ubuntu machine..

When I try log on via ssh I can't..

So can I try log on to my pi during the boot up stage and fix somthing?

Sorry I'm a newbie and using this as a learning project

**Comment by Superhans79** [comment]
> 1. What is ls -a of the file return? (Asking what the perms are)
> 
> 
> 
> 2. How is LND being run?(which user is running it)
> 
> 
> 
> Looks like a permission issue indeed. The easy solution would be to allow anyone to execute the file (more insecure). The proper solution is to figure out what user LND is running as and set the file to be executable by that user.

Thanks for the reply.. makes sense just not sure how to do it 😀😀😀

**Comment by lucasdcf** [comment]
@Superhans79 Considering you have this 00infoLCD.sh file, I understand you're using Raspiblitz, right? I recommend you to ask for guidance in their telegram group: https://t.me/raspiblitz 

This is not an issue with lnd.
