### ISSUE TITLE
LND crashes on channel.db compact attempt

### ISSUE THREAD

**Issue by iWarpBTC** [lightningnetwork/lnd#6305]
### Background

I wanted to try compacting my channel.db for the very first time. My channel.db is now about 1.24 GB. 

### Your environment

* lnd 0.14.2-beta
* Linux umbrel 5.10.11-v8+ # 1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux
* Bitcoin Core version v22.0.0
* Umbrel v0.4.15

### Steps to reproduce

I add these lines to my lnd.conf and restart lnd:
```
[bolt]
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=0
```

Dunno if it's relevant, but I've got one pending force close.

### Expected behaviour

Lnd starts and channel.db is compacted.

### Actual behaviour

Lnd crashes until the mentioned lines is removed from the lnd.conf. Removing the lines, lnd starts as usual. 

```
2022-03-03 22:24:11.225 [INF] LTND: Version: 0.14.2-beta commit=v0.14.2-beta, build=production, logging=default, debuglevel=HSWC=debug
2022-03-03 22:24:11.225 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-03-03 22:24:11.227 [INF] RPCS: RPC server listening on 0.0.0.0:10009
2022-03-03 22:24:11.235 [INF] RPCS: gRPC proxy started at 0.0.0.0:8080
2022-03-03 22:24:11.236 [INF] LTND: Opening the main database, this might take a few minutes...
2022-03-03 22:24:11.236 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
panic: runtime error: invalid memory address or nil pointer dereference
2022-03-03 22:24:11.236 [INF] CHDB: Compacting database file at /data/.lnd/data/graph/mainnet/channel.db
2022-03-03 22:24:11.255 [INF] LTND: Shutdown complete

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd18324]

goroutine 1 [running]:
go.etcd.io/bbolt.(*Bucket).Sequence(...)
        go.etcd.io/bbolt@v1.3.6/bucket.go:340
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1.1({0x7ee1657400, 0x10, 0x10}, 0x0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:227 +0x104
go.etcd.io/bbolt.(*Tx).ForEach.func1({0x7ee1657400, 0x10, 0x10}, {0x7ee1657010, 0x0, 0x0})
        go.etcd.io/bbolt@v1.3.6/tx.go:129 +0x7c
go.etcd.io/bbolt.(*Bucket).ForEach(0x400044a0f8, 0x400079c930)
        go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0x10c
go.etcd.io/bbolt.(*Tx).ForEach(0x400044a0e0, 0x400079c980)
        go.etcd.io/bbolt@v1.3.6/tx.go:128 +0x58
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1(0x400044a0e0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:220 +0x54
go.etcd.io/bbolt.(*DB).View(0x400073c000, 0x400079ca40)
        go.etcd.io/bbolt@v1.3.6/db.go:772 +0x84
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk(0x400079ceb0, 0x400073c000, 0x400079cab8)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:219 +0x54
github.com/lightningnetwork/lnd/kvdb.(*compacter).compact(0x400079ceb0, 0x400073c240, 0x400073c000)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:147 +0xd4
github.com/lightningnetwork/lnd/kvdb.(*compacter).execute(0x400079ceb0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:117 +0x500
github.com/lightningnetwork/lnd/kvdb.compactAndSwap(0x400079d2d0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:179 +0x71c
github.com/lightningnetwork/lnd/kvdb.GetBoltBackend(0x400079d2d0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:101 +0x98
github.com/lightningnetwork/lnd/lncfg.(*DB).GetBackends(0x4000442000, {0x1a54510, 0x4000443100}, {0x40003fc200, 0x1d}, {0x40005c8cf0, 0x25}, {0x4000882210, 0x2a}, 0x0, ...)
        github.com/lightningnetwork/lnd/lncfg/db.go:392 +0x20b8
github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x400000d968, {0x1a54510, 0x4000443100})
        github.com/lightningnetwork/lnd/config_builder.go:810 +0x324
github.com/lightningnetwork/lnd.Main(0x40002c2500, {{0x0, 0x0, 0x0}}, 0x40001290e0, {0x400007c9c0, 0x400039c240, 0x400039c2a0, 0x400039c300, {0x0}})
        github.com/lightningnetwork/lnd/lnd.go:353 +0x15d0
main.main()
        github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x258
umbrel@umbrel:~ $ ./watcher.sh 
        github.com/lightningnetwork/lnd/lnd.go:353 +0x15d0
main.main()
        github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x258
```

**Comment by Roasbeef** [comment]
Is the node able to restart _without_ compaction? Was the node moved at all (new machine or cross architecture)?

**Comment by iWarpBTC** [comment]
Yes, _without_ the compaction configured the node can be (re)started and is running at the moment without any obvious issue. The node is running from the very beginning on the same RB Pi 4 computer.

**Comment by MWDJ** [comment]
I had similar issues with not being able to compact channel.db late last year at 1.7GB size (constant restarts).  After I used chantools to compact the database offline as described here:  https://www.lightningnode.info/technicals/lnddatabasecompaction; this enabled the built-in LND auto compaction to work successfully.  

Ultimately, I upgraded to a 64bit LND and have channel.db of over 3.3GB working stable. 
Hope this works for you as well.
-DJ

**Comment by MWDJ** [comment]
Also I've adjusted compact as follows:
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=36h

**Comment by iWarpBTC** [comment]
Today I apparently successfully ran `chantools compactdb` compacting the channel.db from 2GB under 700MB. Althrough there were a bunch of these error in the process: 

`[ERR] CHAN: Bucket [...] was nil! Probable data corruption suspected.`

The node seems to be running normaly now. On the next restart, I'll try auto-compact again and let you know.

**Comment by guggero** [comment]
The `[ERR] CHAN: Bucket [...] was nil! Probable data corruption suspected.` errors don't sound good though!
If you want to be absolutely sure that you don't run into problems down the line, you should close all channels, delete the `channel.db` file, re-sync the graph and then re-open the channels again.

**Comment by iWarpBTC** [comment]
That would probably be the most sensible thing to do. But who would want to reopen about 70 channels? 😄 
Maybe the problem is caused just by one or two of them. It is possible for me to use these "bucket ids" to track them down?

**Comment by guggero** [comment]
Can you post the full log of the compaction? E.g. what bucket names were logged just before those error messages? If the damage was confined to the graph or other non-channel related data, then it's probably okay to continue.

**Comment by iWarpBTC** [comment]
It all have been written out in the first moments of the compaction process: [chantools.log](https://github.com/lightningnetwork/lnd/files/8314845/chantools.log)

**Comment by guggero** [comment]
Okay, all those buckets look like they are from the `edge-update-index` bucket, which stores graph update information. So unless you see weird behavior with the graph (e.g. nodes not being found when doing pathfinding or trying to pay someone), you should be okay.

Going to close the issue for now since compaction seems to have rescued the most critical part of your DB.
