### ISSUE TITLE
deadlock between contractcourt, htlcswitch

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#6312]
I introduced this in https://github.com/lightningnetwork/lnd/pull/6221
The `channel_arbitrator` calls `ForceCloseChan` when broadcasting a commitment, which eventually calls `MarkLinkInactive` which then later calls `link.Stop`, which waits for the link to stop. The link may be sending a ContractUpdate to the channel_arbitrator at the same time via `NotifyContractUpdate`. These subsystems seem to be tightly coupled, so maybe @yyforyongyu idea of writing them to disk and polling is a better way to go.

**Comment by Crypt-iQ** [comment]
I think this could be achieved by adding a persistence layer following the model of the resolution message store pull https://github.com/lightningnetwork/lnd/pull/6250

**Comment by yyforyongyu** [comment]
If we are already at the step `ForceCloseChan`, I think further updates to the channel should be forbidden and `NotifyContractUpdate` needs to return an error. It seems simpler to add a check inside `NotifyContractUpdate`, if the `ChannelArbitrator.state == StateCommitmentBroadcasted` then we return an error.

**Comment by Crypt-iQ** [comment]
I think that's a nice simple solution and should fix the deadlock. One behavior that approach would have vs the current PR is (master also has this problem in a pretty similar timing scenario):

goroutine 1:
```
t1 - checkLocalChainActions (StateDefault -> StateBroadcastCommit), no more link updates
t2 - ForceCloseChan (StateBroadcastCommit -> StateCommitmentBroadcasted)
t3 - sweepAnchors (uses c.activeHtlcs to find the commitment deadline)
```

goroutine 2:
```
t1 - NotifyContractUpdate (link notifies of new htlc's, don't get added due to not StateDefault) 
t2 - link shut down due to ForceCloseChan
```

Since sweepAnchors uses `c.activeHtlcs` to find the commitment deadline, it could be out-of-date. The PR fixes this issue silently since the link will buffer the HTLCs from `goroutine2:t1`, then `goroutine:t3` will use the cached result.

**Comment by yyforyongyu** [comment]
Hmm, maybe my understanding is a bit off here. But do we allow any updates to `c.activeHtlcs` once we've reached the state `StateBroadcastCommit`?

**Comment by Crypt-iQ** [comment]
In the pre-deadlock logic, the link would send to `htlcUpdates`. This can occur until `MarkLinkInactive` returns. If the link has sent along `htlcUpdates` it will be blocking while `stateStep` is occurring. `MarkLinkInactive` is then called which eventually closes `link.quit` and `c.activeHtlcs` won't get updated.

**Comment by yyforyongyu** [comment]
I think if our systems have a well-defined set of internal states, they can provide a good abstraction when they interact with each other.
