### ISSUE TITLE
Holdinvoice can be canceled even if after the payee accepted

### ISSUE THREAD

**Issue by yuyaogawa** [lightningnetwork/lnd#6313]
### Background

When a payer sends payment to holdinvoice, the payee can hold the payment. But when the payer cancels the RPC command, it sends out failure resolution message (I am not sure if it acutally sends out) to the payee, and payee cancels the holding payment even if they still want to hold it. Is it expected behavior? If so, how can the payee hold the payment despite payer's cancellation.

### Your environment

* version of `lnd` 0.14.2-beta commit=v0.14.2-beta

**Comment by Roasbeef** [comment]
>  But when the payer cancels the RPC command, it sends out failure resolution message (I am not sure if it acutally sends out) to the payee, and payee cancels the holding payment even if they still want to hold it

If the payment/HTLC is held by the payee (the receiver), then then payer (the sender) cannot cancel. Only the payee can as the fact that the HTLC exists on the payer's commitment transaction can only be undone by the payee. Once the payment/HTLC is held by the payer (the receiver), then the only way to fully "cancel" the payment is either for the CLTV timeout to be reached, or the payee cancelling back early.

**Comment by yuyaogawa** [comment]
That is what I am expecting. However what I have done is that
1. Payee creates an holdinvoice with `addholdinvoice` and subscribes the invoice with `subscribeSingleInvoice`
2. Payer sends a payment to the holdinvoice
3. Payee accepts the payment (never settle/cancel)
4. Payer cancels the in-flight payment with [Ctrl+c] command.
5. Payee's server closes the stream

When I as payee check the invoice status with `lookupinvoice` the state is `CANCELED` even if I never cancel the held payment.

**Comment by yuyaogawa** [comment]
@alexbosworth Thanks for a reply. How long can an accepted invoice be held? Is there a way to prevent from auto canceling? Let's say I want to hold an accepted invoice for 3 hours, should I create an holdinvoice with setting `cltv_expiry` to more than 18?

**Comment by alexbosworth** [comment]
You are right, the CLTV delta on the invoice is governing the hold time

Extending the CLTV delta indiscriminately may cause the sender to be unable to pay since there is a default governing the max CLTV and there are also maximum hold times on every hop, but a standard hold time is 40 which should allow for a few hours, or you could go to 144 which is the prior default

**Comment by yuyaogawa** [comment]
An held invoice is auto canceled in a few minutes when I set `cltv_expiry` to 18, but it seems another invoice is still being held when I set `cltv_expiry` to 144. My issue is resolved, but can you tell me when exactly is auto cancel happen?

**Comment by alexbosworth** [comment]
It should be governed by `--invoices.holdexpirydelta=` which is defaulting to 12

**Comment by yuyaogawa** [comment]
Thanks!
