### ISSUE TITLE
Disk Space Reduction: Remove Failed Payments

### ISSUE THREAD

**Issue by levmi** [lightningnetwork/lnd#6318]
Breaking down the [master issue](https://github.com/lightningnetwork/lnd/issues/5388) into independent issues for tracking

Only keep around failed payment attempts if specified by a new flag. This is a major culprit of ballooning database state as due to things like payment splitting a successful attempt may generate several failures.

**Comment by tvolk131** [comment]
I can take a whack at this!

**Comment by yyforyongyu** [comment]
Was planning to work on this issue this week. Have you started yet @tvolk131 ?

**Comment by tvolk131** [comment]
@yyforyongyu yes I have. Hope to have a PR out in the next day or two

**Comment by tvolk131** [comment]
Quick update! The work is coming along nicely, but a little slower than I anticipated. PR should be out by tomorrow evening.
