### ISSUE TITLE
Disk Space Reduction: Blank out any on disk onion blobs if specified 

### ISSUE THREAD

**Issue by levmi** [lightningnetwork/lnd#6319]
Breaking down the [master issue](https://github.com/lightningnetwork/lnd/issues/5388) into independent issues for tracking

Blank out any on-disk onion blobs if specified with a new flag. Each blob is 1.3 KB and we store them several times over in places like payment attempts as well as invoices.

**Comment by Roasbeef** [comment]
Has been resolved by https://github.com/lightningnetwork/lnd/pull/6347
