### ISSUE TITLE
[Bug] [Interoperability] Openchannel creates channel with 1000 sat capacity

### ISSUE THREAD

**Issue by junderw** [lightningnetwork/lnd#633]
Problem: Openchannel creates 1000 capacity channel. This means that the only way to create a standard closing transaction is 0 <> 1000 or 1000 <> 0.

Suggestion: Perhaps making a minimum capacity requirement for channels >= dust_limit x 2 (1092 satoshis currently) is necessary...

Currently the balance is 999 <> 1... but if I tried to unilaterally close or even amicably close, the transaction won't propagate because 1 satoshi output is non-standard.

**Comment by Roasbeef** [comment]
The 1 satoshi output won't be created. It's below dust, so it will be trimmed.

**Comment by Roasbeef** [comment]
We have a sanity check for fee: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/reservation.go#L186

But seems that TODO should be addressed and it should be addressed, so some multiple of our dust limit as you suggest.
