### ISSUE TITLE
ZMQ: Can't connect to transaction host if it's mapped to a different port.

### ISSUE THREAD

**Issue by JssDWt** [lightningnetwork/lnd#6333]
### Background

I'm trying to connect a debug version of LND to a bitcoind instance running in a Polar docker container. The Polar bitcoind docker container maps the ZMQ transaction host port (28335) to another local port (29335). LND is unable to connect to the ZMQ transaction host.

### Your environment

* lnd debug build of the current master branch (41b91bd5beb2dcff3b5d7cddb74a319bba18b8e5)
* OS: `21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`
* bitcoind 0.21.1 regtest running in Polar 1.3.0 in default configuration
* Polar connection details:
  - RPC Host | http://127.0.0.1:18443
  - P2P Host | tcp://127.0.0.1:19444
  - ZMQ Block Host | tcp://127.0.0.1:28334
  - ZMQ Transaction Host | tcp://127.0.0.1:29335
* Docker port mapping details
  - 18443/tcp | 0.0.0.0:18443
  - 18444/tcp | 0.0.0.0:19444
  - 28334/tcp | 0.0.0.0:28334
  - 28335/tcp | 0.0.0.0:29335

### Steps to reproduce

- Run bitcoind in Polar, docker ports mapped like above config
- Start LND with `./lnd-debug --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=127.0.0.1:18443 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28334 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:29335`
- `lncli-debug unlock`

### Expected behaviour

LND should connect to the ZMQ transaction host over a mapped port in a docker container.

### Actual behaviour

After unlocking the wallet I get this error:
```
2022-03-11 12:47:31.573 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28334
2022-03-11 12:47:31.573 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:29335
2022-03-11 12:47:31.585 [ERR] LTND: unable to create partial chain control: unable to subscribe to zmq tx events on 127.0.0.1:29335 (bitcoind is running on 0.0.0.0:28335)
2022-03-11 12:47:31.586 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to subscribe to zmq tx events on 127.0.0.1:29335 (bitcoind is running on 0.0.0.0:28335)
```

### Remarks
- The same error occurs when connecting to `bitcoind.zmqpubrawtx=tcp://0.0.0.0:29335`, so it must be the port mapping that is the problem.
- Apparently in this case LND _is_ able to connect to the ZMQ block host. Note that the port mapping for the block host in above configuration is 28334:28334. So same port apparently does work.

**Comment by JssDWt** [comment]
The relevant check in the code is here:
`https://github.com/lightningnetwork/lnd/blob/41b91bd5beb2dcff3b5d7cddb74a319bba18b8e5/chainreg/chainregistry.go#L547`

I suppose bitcoind doesn't know which port it is exposed under. It 'thinks' it's exposed under port 28335, but it cannot know that we're in fact mapping the port. 

Removing the check fixes the problem for me.

**Comment by ErikEk** [comment]
I added this constrain because of a security concern we had. I can add a pr which will exclude localhost, think it should be enough.

**Comment by JssDWt** [comment]
> I added this constrain because of a security concern we had. I can add a pr which will exclude 0.0.0.0.

I don't think that will help. It's the port number in this case. If I'm hosting the bitcoind ZMQ events under 1.2.3.4:5555, but it's proxied over 5.4.3.2:1111, I should be able to subscribe to the proxy I think.

**Comment by ErikEk** [comment]
I think we just have to add a check for ZMQ events in the continuous health check. At this moment, I think it would be best to remove this check. This would be a less discrete way to solve the issue than adding yet another config parameter.
Will post a pr this weekend. Thanks for your feedback.

**Comment by ErikEk** [comment]
> I guess the problem is that you cannot know you're actually subscribed to ZMQ events at all, right?
That's right. It's obvious how we best solve this.

**Comment by joostjager** [comment]
Ran into this as well and would welcome `enableZMQSanityCheck`. Or perhaps allow users to omit the port in configuration and in that case use the port retrieved from bitcoind?

**Comment by ErikEk** [comment]
@joostjager @JssDWt I added a pr which removes the zmq tx/block port check. I am not a fan of adding yet another config parameter to address this minor check. Remember, this only occurs when the port numbers are mixed up. I rather see I or someone add an health check that gives a warning to the user in runtime.
If you rather like me to fix this with an config parameter I'll gladly do that.
Thanks for your feedback.
