### ISSUE TITLE
Privacy Feature Request - we should be able to do a sweep all with coin control (Pick specific UTXOs to sweep))

### ISSUE THREAD

**Issue by merclyn** [lightningnetwork/lnd#6334]
### Background

Privacy Feature - we should be able to do a sweep all with coin control (Pick specific UTXOs to sweep).  Would be even better if we can do sweep all while opening channels. lastly, opening channels with coin control/sweep all from those utxos)

Basically, we need coin control features in lnd.

### Your environment

lncli version 0.14.2-beta commit=v0.14.2-beta

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by alexbosworth** [comment]
You can select coins with the fund psbt API

**Comment by merclyn** [comment]
That would work, I didnt think of that. We probably should work to get it into cli, and to get consoles like RTL to add better support.

**Comment by Roasbeef** [comment]
Yep, this is already possible with the set of existing RPC calls (fund psbt, locking coins, compute input script to sign, etc).
