### ISSUE TITLE
Missing channel after successful channel open to C-Lightning node with pending force close

### ISSUE THREAD

**Issue by netmojo** [lightningnetwork/lnd#6343]
### Background

For some reason my node force-closed a couple of productive channels, and instead of waiting days for them to finish closing, I was impatient and opened new channels with those nodes. I used the RTL interface to open the new channels. The first one opened normally and I was able to use the channel right away. The second one, however, was a C-Lightning node, (which I have since learned) does not support multiple channels to the same peer. From my side, the channel appeared to open normally -- funds spent -- but then it does not appear in my list of open channels. The force close to that channel is still in pending state. How do I retrieve my funds?

### Your environment

* version of `lnd`: 0.14.2-beta
* which operating system (`uname -a` on *Nix): Debian GNU/Linux 10 (Umbrel) on armv6
* version of `btcd`, `bitcoind`, or other backend: bitcoin core v22.0
* any other relevant environment details - Umbrel v0.4.15

### Steps to reproduce

1. Force close a channel with a C-Lightning node. 
2. While the channel is still pending close, initiate a new channel open with that node. 

### Expected behaviour

If the other side of the channel does not confirm channel open, I would expect an error message, and my funds returned on-chain.

### Actual behaviour

(will update pending more investigation).

**Comment by Roasbeef** [comment]
If you look at `listchannels` and `pendingchannels`, do you see the channel? If so what state is it in, are there funds in limbo? 

Given that CL doesn't support opening > 1 channel  to a node(I think they also won't accept another one until the existing one is fully closed/resolved), and AFAICT it never reached broadcast time, then all the funds should still be there, but you make have a "ghost" channel in the `pendingchannel`s output.

**Comment by netmojo** [comment]
No, the channel does not appear in `listchannels` or `pendingchannels`. I think I screwed up saving the logs too :/. This is for a different channel, that is open.

`2022-03-15 05:50:49.401 [INF] FNDG: Generated ChannelPoint(a4d31ec08e9d19f204c979b1d4e0db2b89f4496a7a10bd07c13633e9fb2eb2a0:1) `

The pending force close finally reached block height so is closed. My funds are in some weird half-signed contract.

**Comment by netmojo** [comment]
OK, as per my updated logs, it appears that there is a channel with the "short_chan_id" of `727400:690:1` that is associated to the on-chain channel-open transaction. How can I get info on this channel, and maybe close it?

**Comment by netmojo** [comment]
Nevermind. I think I confused myself and didn't actually open the channel I thought I did. 🙄
