### ISSUE TITLE
payments that no longer exists are being reported by TrackPayments

### ISSUE THREAD

**Issue by dolcalmi** [lightningnetwork/lnd#6344]
### Background

We implemented a [workaround](https://github.com/GaloyMoney/galoy/blob/main/src/services/lnd/index.ts#L664) for this issue https://github.com/lightningnetwork/lnd/issues/6249. This "fix" let us resolve most of the pending transactions, however, we still have 9 pending payments (IN_FLIGHT and expired) in 6 different channels and they were not solved because the channels were not closed by our node or by the output channel node and they are still active.

### Your environment

* `lnd`: v0.14.2-beta
* `bitcoind`: v22.0

### Steps to reproduce

Maybe related to inconsistent data caused by issue https://github.com/lightningnetwork/lnd/issues/6249

### Expected behaviour

Close channel with pending payments after timeout

### Actual behaviour

Channels active even after months of having timed out payments (IN_FLIGHT)

**Comment by Roasbeef** [comment]
Have you verified using `listchannels` that these channels had/have present HTLCs on them?

**Comment by dolcalmi** [comment]
> Have you verified using `listchannels` that these channels had/have present HTLCs on them?

yes, like in https://github.com/lightningnetwork/lnd/issues/6249 there are no pending HTLCs

**Comment by Roasbeef** [comment]
If there are no pending HTLCs, then the HTLCs don't actually exist, which means the payments don't. Instead, it seems like the issue described in https://github.com/lightningnetwork/lnd/issues/5461. The router and the system that handles going on chain are pretty independent of each other, so if there're present "live" HTLCs on a commitment transaction, they should always be cleaned up  on chain irrespective of what else is going on when sending payments.

**Comment by dolcalmi** [comment]
> If there are no pending HTLCs, then the HTLCs don't actually exist, which means the payments don't. Instead, it seems like the issue described in #5461.

just to confirm.. is it safe to handle that payments as failed payments?

**Comment by nicolasburtey** [comment]
am I correct to understand that the payment would disappear after a node restart @Roasbeef ?

**Comment by Roasbeef** [comment]
> just to confirm.. is it safe to handle that payments as failed payments?

Yes, it's safe as long as you confirm that there's no related HTLC present on any of your outgoing channels. We're doing some work to be able to reproduce this scenario reliably so we can be confident in a fix. I can definitely see how it makes ensuring there're no accounting holes as far as attempted payments more difficult. 

> am I correct to understand that the payment would disappear after a node restart @Roasbeef ?

AFAIU, the current issue is that it _doesn't_ disspear and becomes stuck in an "in flight" state with no further attempts, even though the timeout has passed.

**Comment by nicolasburtey** [comment]
> I can definitely see how it makes ensuring there're no accounting holes as far as attempted payments more difficult.

yup the main issue is that there is a payment in flight, so the associated user that started the payment has the associated amount reduced from his account.

if the payment fails, he's supposed to have a refund. 

the main issue is that we have to see the payment status changed from in flight to failed.  we can't easily time based the refund because otherwise some attackers could use a hold invoice, and wait until the refund happens, to then settle the hold invoice, which would effectively be a form of double spend

**Comment by Roasbeef** [comment]
This PR addresses _at least_ one known issue in this area, and potentially more (pending additional testing + scenario reproduction): https://github.com/lightningnetwork/lnd/pull/6352

**Comment by Roasbeef** [comment]
Note that the "main" issue re not doing an absolute timeout is still open: https://github.com/lightningnetwork/lnd/issues/5461
