### ISSUE TITLE
Unable to close channel, channel not found.  [Please close, wrong project]

### ISSUE THREAD

**Issue by evilmrburns** [lightningnetwork/lnd#635]
A little background, I downloaded LND Windows binaries for the GUI to test lightning out. Opened 12 various channels, sent payments. A few minor hiccups along the way but nothing a restart of the program or what not that couldn't fix the problem. 

So, instead of just on my desktop for testing, I thought I would start a linux node. I closed the channels, sent the balance over to linux after building from source, everything is running fine over there.

However, I noticed when I came back, that three channels had not closed. 

`lnd: 2018-01-19 11:18:41.398 [ERR] RPCS: [closechannel] unable to close ChannelPoint(581a2281a7c286718ac353c46404738f58c1c95abaf133e8cc9c72f5db40a20a:0): channel with chan_id=0aa240dbf5729ccce833f1ba5ac9c1588f730464c453c38a7186c2a781221a58 not found
lnd: 2018-01-19 11:18:42.425 [ERR] RPCS: [closechannel] unable to close ChannelPoint(4c15e545f2227581963b47036fbae0d9618c8600dba9077afabf7db0ffafd822:0): channel with chan_id=22d8afffb07dbffa7a07a9db00868c61d9e0ba6f03473b96817522f245e5154c not found
lnd: 2018-01-19 11:18:43.598 [ERR] RPCS: [closechannel] unable to close ChannelPoint(3da615b63cafaeb646dc92bbbb8b2b7d60f3597ac3701e6a34602c168a7530be:0): channel with chan_id=be30758a162c60346a1e70c37a59f3607d2b8bbbbb92dc46b6aeaf3cb615a63d not found`

These three channels refuse to close. The balance is tied up. Nothing of which on testnet I'm worried about, but I cannot find more information about it. I cannot force a close in the GUI. 

If I try to spend coins on any site, it cannot route. 

`lnd: 2018-01-19 11:20:46.765 [ERR] HSWC: unable to find links by destination unable to locate channel link bydestination hop id 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 2018-01-19 11:20:46.765 [ERR] CRTR: Attempt to send payment df3de4eb78e528c8d530d7bc955a831400c21f957a4953b89abf7430436d9878 failed: UnknownNextPeer
lnd: 2018-01-19 11:20:47.205 [ERR] HSWC: unable to find links by destination unable to locate channel link bydestination hop id 026210049063949182ec8292c9c86814e2202fcd96477ba800ae753ae7f1f02e11 2018-01-19 11:20:47.205 [ERR] CRTR: Attempt to send payment df3de4eb78e528c8d530d7bc955a831400c21f957a4953b89abf7430436d9878 failed: UnknownNextPeer
lnd: 2018-01-19 11:20:47.616 [ERR] HSWC: unable to find links by destination unable to locate channel link bydestination hop id 029e114e189504c625d1df762425b992317a7d56866470bc8558fbc197800d7d2b 2018-01-19 11:20:47.616 [ERR] CRTR: Attempt to send payment df3de4eb78e528c8d530d7bc955a831400c21f957a4953b89abf7430436d9878 failed: UnknownNextPeer`

I am assuming that these three nodes have gone offline. I've tried to close at various times over the last two days with no success. Is there something in LNCLI that allows me to force these? But not in the GUI?

**Comment by stridentbean** [comment]
Using LNCLI you can add a `--force` when trying to `closechannel`. This will allow you to close noncooperative channels when there are disagreements or the other node is offline. I haven't tried the UI in awhile, but the last time I checked there was no force option.

**Comment by evilmrburns** [comment]
@stridentbean Thanks for the response. I did find the --force on LNCLI while playing on my node in linux. But, I also think you are correct, the UI just has no way for me to push that through, and I also didn't realize the lightning-app was a different git project.

I would say this can be closed, it's on the wrong git.

**Comment by MeshCollider** [comment]
@evilmrburns you should be able to close the issue yourself since you created it

**Comment by evilmrburns** [comment]
@MeshCollider You're right. In edit, I can't find it. But, when I add a new comment, it shows close and comment. Thank you :) I just needed to look harder.
