### ISSUE TITLE
btcd not found (installation documentation)

### ISSUE THREAD

**Issue by kgelinas** [lightningnetwork/lnd#637]
I've followed the instruction everything seem fine
except at this line

> btcd --testnet --txindex --rpcuser=kek --rpcpass=kek
> -su: btcd: command not found

there's no binary in $GOPATH/bin of btcd

> ls $GOPATH/bin/
> addblock  btcctl  findcheckpoint  gencerts  glide  lncli

is this supposed to be installed from somewhere else?

**Comment by kgelinas** [comment]
never mind seem that debian golang default is to 1.7
you really need 1.8 :)

**Comment by evilmrburns** [comment]
Ubuntu 16.04 is 1.6 :/ I submitted a PR to update the instructions to include adding the gophers repo to the installation instructions.
