### ISSUE TITLE
walletbalance => scope m/86'/0' not found 

### ISSUE THREAD

**Issue by akovalenko** [lightningnetwork/lnd#6377]
### Background

I'm requesting walletbalance from my lnd and get error "scope m/86'/0' not found"
### Your environment

* version of `lnd`: 6e2214fd0fc04adff705141b17482550bee58cde with a small workaround to make tor initialization possible
* operating system: `Linux murphy 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* bitcoind 22.0

### Steps to reproduce

The node has a long history and the bug might depend on it. Not tried to reproduce with a fresh node.
### Expected behaviour

Wallet balance is shown

### Actual behaviour

error message appears

**Comment by guggero** [comment]
Ah, this is the new pay-to-taproot keyspend only derivation path. I guess we need to make sure the scopes/derivation paths are also created for existing wallets. Going to look into it.

**Comment by guggero** [comment]
Created a fix in https://github.com/lightningnetwork/lnd/pull/6379. That should allow you to see your wallet balance again.

**Comment by akovalenko** [comment]
@guggero works, confirmed (also fixes balance query for lnzap-android)
