### ISSUE TITLE
Sample bitcoin.conf is missing from installation guide

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#638]
Please add sample bitcoin.conf to the guide under https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-btcd

The following is a sample bitcoin.conf:

testnet=1
txindex=1
server=1
daemon=1
zmqpubrawblock=tcp://127.0.0.1:18501
zmqpubrawtx=tcp://127.0.0.1:18501

Thank you.

**Comment by MeshCollider** [comment]
PRs welcome if you want to update this yourself :)

**Comment by yancyribbens** [comment]
I'll pick this one up as a first issue.

**Comment by yancyribbens** [comment]
I'm a little confused by this request.  Wouldn't we provide a btcd.conf instead of bitcoin.conf?

**Comment by molxyz** [comment]
@MeshCollider @yancyribbens   Ooopsss!  I posted the wrong link. I meant this bitcoin.conf to be under this link for bitcoind:    https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#running-lnd-using-the-bitcoind-backend

Sorry about the confusion. Should have rechecked my typing before posting.

**Comment by yancyribbens** [comment]
@molxyz I see.  Thanks!

**Comment by Roasbeef** [comment]
Fixed as part of #702.
