### ISSUE TITLE
Cannot call `FundPSBT` with a psbt with only a zero value OP_RETURN output

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#6386]
When creating trying to fund a psbt that creates an `OP_RETURN` with 0 value it gives the error `wallet couldn't fund PSBT: PSBT packet must contain at least one input or output`. If I change the output to be 1 satoshi, it will work.

**Comment by guggero** [comment]
The error is coming from here: https://github.com/btcsuite/btcwallet/blob/master/wallet/psbt.go#L54
This checks if there is at least one output in the PSBT. Are you sure that your first attempt with 0 sats actually included the TxOut? If yes, could you please paste a sample PSBT?

**Comment by benthecarman** [comment]
Here is the psbt `cHNidP8BACABAAAAAAEAAAAAAAAAAA1qC2hlbGxvIHdvcmxkAAAAAAAA`

decoded:
```
$ bitcoin-cli decodepsbt cHNidP8BACABAAAAAAEAAAAAAAAAAA1qC2hlbGxvIHdvcmxkAAAAAAAA
{
  "tx": {
    "txid": "b42fab8da654e748e6d0817f1eba248110bb3fa6da1c7e56b10f71bd1a9f2acf",
    "hash": "b42fab8da654e748e6d0817f1eba248110bb3fa6da1c7e56b10f71bd1a9f2acf",
    "version": 1,
    "size": 32,
    "vsize": 32,
    "weight": 128,
    "locktime": 0,
    "vin": [
    ],
    "vout": [
      {
        "value": 0.00000000,
        "n": 0,
        "scriptPubKey": {
          "asm": "OP_RETURN 68656c6c6f20776f726c64",
          "hex": "6a0b68656c6c6f20776f726c64",
          "type": "nulldata"
        }
      }
    ]
  },
  "unknown": {
  },
  "inputs": [
  ],
  "outputs": [
    {
    }
  ],
  "fee": 0.00000000
}
```

**Comment by guggero** [comment]
Okay, this is probably a bug in the golang PSBT library... It always expects a TX to be in the witness format, but this one doesn't seem to be. Weird that `bitcoind` doesn't have the same issue. What tool did you create the PSBT with? Bitcoind or another tool?

**Comment by benthecarman** [comment]
> Okay, this is probably a bug in the golang PSBT library... It always expects a TX to be in the witness format, but this one doesn't seem to be. Weird that `bitcoind` doesn't have the same issue. What tool did you create the PSBT with? Bitcoind or another tool?

I made it in bitcoin-s. 

BIP 174 states it shouldn't be in the witness seralization

> | Unsigned Transaction
| <tt>PSBT_GLOBAL_UNSIGNED_TX = 0x00</tt>
| None
| No key data
| <tt><transaction></tt>
| The transaction in network serialization. The scriptSigs and witnesses for each input must be empty. The transaction must be in the old serialization format (without witnesses).



<br class="Apple-interchange-newline">

**Comment by guggero** [comment]
Oh, thanks for finding that reference, I wasn't aware of that. Then the code in https://github.com/btcsuite/btcd/blob/master/btcutil/psbt/psbt.go#L217 is incorrect. Could you open an issue in `btcd` with the example PSBT please?

**Comment by Roasbeef** [comment]
(btcd PR was merged, but lnd needs to be updated)
