### ISSUE TITLE
lnd logs: [ERR] RPCS: [/lnrpc.Lightning/DeletePayment]: non bucket element in payments bucket

### ISSUE THREAD

**Issue by GaryBanderas** [lightningnetwork/lnd#6388]
**Background**

In the lnd logs, I have this error message that appears every 3 or 4 minutes since a couple of days.

[ERR] RPCS: [/lnrpc.Lightning/DeletePayment]: non bucket element in payments bucket

 I don't know what caused it or it's meaning. It doesn't seem to cause any issue. The error is still appearing after all failed payments are cleaned and after restarting lnd. I use lndg to rebalance some channels.

Environment:
lnd 0.14.2-beta
Umbrel 0.4.15
Bitcoin Core v22.0.0

**Comment by Roasbeef** [comment]
Seems like you're trying to delete a payment that has already been deleted. We definitely improve the error message here though.

**Comment by GaryBanderas** [comment]
Thanks for the answer!
