### ISSUE TITLE
Postgres replication discrepancy after filesystem failure, choose correct dump to restore

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#6395]
### Background

btrfs raid1 filesystem (with db replication on third ssd) is failing, node has been shutdown after disabling forwards and  making sure of no pending htlcs; waiting for SSD replacements to arrive; dump of main postgres instance and of replica are slightly different, which one to restore on new node?

This is the output of diff:
```
diff -u /replica/sqldump/replica.dump /replica/sqldump/main.dump
--- /replica/sqldump/replica.dump 
+++ /replica/sqldump/main.dump
@@ -982092,7 +982092,7 @@
 -- Name: channeldb_kv_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bitcoin
 --

-SELECT pg_catalog.setval('public.channeldb_kv_id_seq', 15758297, true);
+SELECT pg_catalog.setval('public.channeldb_kv_id_seq', 15758280, true);


 --
@@ -982106,7 +982106,7 @@
 -- Name: macaroondb_kv_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bitcoin
 --

-SELECT pg_catalog.setval('public.macaroondb_kv_id_seq', 33, true);
+SELECT pg_catalog.setval('public.macaroondb_kv_id_seq', 3, true);


 --
@@ -982127,7 +982127,7 @@
 -- Name: walletdb_kv_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bitcoin
 --

-SELECT pg_catalog.setval('public.walletdb_kv_id_seq', 20948, true);
+SELECT pg_catalog.setval('public.walletdb_kv_id_seq', 20919, true);
```

In the above, the DB replica seems to be ahead of main instance in regards of counters; to be noted, the main instance resided on the failing btrfs raid1 filesystem, while replicating instance mounted on `/replica` resides on a third ext4 ssd which shows no filesystem failures.

When restoring node on new btrfs raid, should I import dump from main instance, or replica instance (whith higher counters, hence apparently "more updated")?

### Your environment

* version of `lnd` 14.2
* which operating system (`uname -a` on *Nix) raspios 64bit
* version of `btcd`, `bitcoind`, or other backend - 22
* any other relevant environment details //

### Steps to reproduce

I wish you not to reproduce this, will give you bad headaches.

### Expected behaviour

Both dumps are identical

### Actual behaviour

Slight differences in dump.

**Comment by guggero** [comment]
Disabling forwards and making sure there aren't any HTLCs isn't enough to make sure there are no channel updates. Simple fee negotiations can cause a channel to be updated and the channel being breached on restore. You should always shut down lnd completely (or disable all channels manually) before taking a snapshot.

If the only diff between the two dumps is indeed only sequences, you might be okay in this specific case. Though extreme caution is advised here.

**Comment by jjager-nydig** [comment]
Out of curiosity, did you use synchronous replication with Postgres? If not, it still wouldn't explain why the replica is ahead though.

Needless to say, sync replication is critical for Lightning data.

**Comment by asvdf** [comment]
> Disabling forwards and making sure there aren't any HTLCs isn't enough to make sure there are no channel updates. Simple fee negotiations can cause a channel to be updated and the channel being breached on restore. You should always shut down lnd completely (or disable all channels manually) before taking a snapshot.
> 
> If the only diff between the two dumps is indeed only sequences, you might be okay in this specific case. Though extreme caution is advised here.

Does this mean that, even if no forwards happened, in case of a "fee mismatch" I would still trigger a force close on coming back online with an "old fee state"? In any case, yes, not especially knowledgeable about lnd DB logical structure, but I also would say that with only sequences being different, I shouldn't be at risk whatever version I restore, and especially not if I restore the newest



> Out of curiosity, did you use synchronous replication with Postgres? If not, it still wouldn't explain why the replica is ahead though.
> 
> Needless to say, sync replication is critical for Lightning data.

it was streaming replication actually, so I should instead look into synchronous you suggest?

**Comment by guggero** [comment]
> Does this mean that, even if no forwards happened, in case of a "fee mismatch" I would still trigger a force close on coming back online with an "old fee state"?

Yes and potential loss of funds because your node would publish an old state.

> so I should instead look into synchronous you suggest?

Yes!

**Comment by asvdf** [comment]
Also, pardon my flooding: no matter what is stored in the replica, I should prefer restoring the master in case streaming replication was used... now that I think about it though, the failure happened on the raid1 btrfs system where master resided, while the ext4 ssd where replica was stored didn't go corrupted.

**Comment by guggero** [comment]
> My understanding is that, worst case scenario, in case old state is published while I go back online on LN, but not closing the channel, I would lose funds because of the swiping fees, not 100% of funds because of a justice transaction... am I wrong?

No, if your node force-closes with an old state, your counterparty has the revocation key for the time locked funds and can take your balance as well. `lnd` will do its best to not force close if it detects (is informed by the remove node) that there is a mismatch of the channel state. But you shouldn't rely on that alone, things can still go wrong.

**Comment by joostjager** [comment]
>it was streaming replication actually, so I should instead look into synchronous you suggest?

We definitely need to add this to the postgres doc in lnd. It is super important.

>What's curious, is that in streaming mode, the replica should NOT be "newer" than the master, rather the opposite. Unless there is something about how sequences are stored that is not apparent to the eye, making them not really sequential.

I would indeed also expect that if things are out of sync, that the replica is behind. But if hardware is failing, I guess anything can happen?

**Comment by asvdf** [comment]
ok, I just decided that I'll go with going online with the replica state after blockchain is synced, unless someone of you wants to convince me of the opposite

**Comment by joostjager** [comment]
I just wonder if there is a more direct indicator of the version of the data available in postgres.

**Comment by asvdf** [comment]
> I just wonder if there is a more direct indicator of the version of the data available in postgres.

wouldn't think so, since the dumps only differ for those sequences... old disks are gone, so not able to verify with file timestamps

**Comment by joostjager** [comment]
A colleague of mine came up with an explanation why the replica is ahead. Apparently sequence numbers are allocated ahead of time on the replica.

https://github.com/postgres/postgres/blob/00cb86e75d6dd13a8bc07f79c2cdbe20d96c2d92/src/backend/commands/sequence.c#L57

**Comment by asvdf** [comment]
> You should always shut down lnd completely (or disable all channels manually) before taking a snapshot.

Forgot to mention this: the very last "session" of the node, before I shut it down for good to restore the hardware, was:
1. boot node, have lnd start completely
2. run `bos limit-forwarding --disable-forwards`
3. wait for a while (at least 10 minutes) while checking with `lncli listchannels | jq '.[][] | .pending_htlcs[] '` to confirm no pending htlc's were running
4. `sudo poweroff` while watching the connected monitor to verify nothing was up and everything could terminate gracefully

Considering this, would you say I am in the clear?



> A colleague of mine came up with an explanation why the replica is ahead. Apparently sequence numbers are allocated ahead of time on the replica.
> 
> https://github.com/postgres/postgres/blob/00cb86e75d6dd13a8bc07f79c2cdbe20d96c2d92/src/backend/commands/sequence.c#L57

this means I should actually restore the dump of the main database, instead of the replica, you reckon?

**Comment by joostjager** [comment]
>this means I should actually restore the dump of the main database, instead of the replica, you reckon?

I saw that the difference in your sequence numbers is indeed < 32. If that is because of pre-allocation, the difference should be inconsequential and it shouldn't matter which copy your restore. But I am no expert on postgres internals.

**Comment by asvdf** [comment]
To complete this thread, which I will be closing at the same time: my node was restored today from the main postgresql instance's dump, and no force closures happened; I have now synchronous replication in place.
