### ISSUE TITLE
LND

### ISSUE THREAD

**Issue by malzate10** [lightningnetwork/lnd#6399]
https://github.com/lightningnetwork/lnd/blob/6d661334599ffa2a409ad6b0942328f9fd213d09/lntest/itest/lnd_single_hop_invoice_test.go#L24-L33
`make itest icase=single_hop_invoice log=stdout` runs that specific test, otherwise you’ll be running the full test suite for bitcoind/neutrino/btcd

**Comment by yyforyongyu** [comment]
Please read [this doc](https://github.com/lightningnetwork/lnd/blob/master/docs/MAKEFILE.md#itest) for more info.
Closed as this is not an issue.
