### ISSUE TITLE
Pending force close channel stuck with negative blocks_til_maturity

### ISSUE THREAD

**Issue by akovalenko** [lightningnetwork/lnd#6406]
### Background

After force closing a channel, I've noticed that a sweep transaction fails to broadcast. Not sure on the cause and whether I'd better just wait, and having an appetite for on-chain funds, I decided to accelerate the sweep using `lncli wallet bumpfee --force --conf_target=1 ef54b51cdf659af7323eec86652c1c71b4daf57cff5899c7a5b07e0ab02c359a:3`, and it succeeded (on-chain funds became available, pendingsweeps became empty).

The channel, however, is stuck in pendingchannels for 1070 blocks by now:
```
        {
            "channel": {
                "remote_node_pub": "03cd0448616e81ba9aeef8f6f6d34ffdd9f9a23250545fe6f3e015c8a80e34c5fa",
                "channel_point": "6a89626df86ca424e7e2d90a29113d18ed800884568eab1dc9adb2fa0393d80b:1",
                "capacity": "5000000",
                "local_balance": "4985588",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "closing_txid": "ef54b51cdf659af7323eec86652c1c71b4daf57cff5899c7a5b07e0ab02c359a",
            "limbo_balance": "4985588",
            "maturity_height": 730431,
            "blocks_til_maturity": -1070,
            "recovered_balance": "12333",
            "pending_htlcs": [
            ],
            "anchor": "RECOVERED"
        },
```

### Your environment

* version of `lnd` : approx. current git master 8109c9ccf1e41b32234b2372d09aa83b20d65d63
* which operating system (`uname -a` on *Nix): `Linux murphy 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: bitcoind 22.0

### Steps to reproduce

Unsure whether the issue is reproducible reliably or at all

### Expected behaviour

After the funds are swept (and confirmed), the channel disappears from pendingchannels

### Actual behaviour

The channel is staying force-closing with negative blocks_til_maturity

**Comment by akovalenko** [comment]
@guggero abandonchannel indeed fixes this (I always forget there's an "I'm know what I'm doing" trick), previous restart didn't.

**Comment by guggero** [comment]
Did you let `lnd` run for a while after restart? I guess we should have a monitor RPC for ongoing chain rescans to check for such things.
Closing as fixed by abandoning the channel.
