### ISSUE TITLE
[Request] command to close all opened channels

### ISSUE THREAD

**Issue by johnnyhonda** [lightningnetwork/lnd#641]
Currently there is no way to close all channels that are opened without some hacking. It would be nice to have something like:

`lncli closechannel -all`

If you want to close all channels: @djseeds:

## to close all channels...  

```lncli listchannels | jq '.[][]' | jq -r '.channel_point' | tr : ' ' | xargs -n2 lncli closechannel```

## to close only inactive channels...

```lncli listchannels | jq '.[][]' | jq -c -r 'select(.active == false) | .channel_point' | tr : ' ' | xargs -n2 lncli closechannel --force```

**Comment by kasadawa** [comment]
there is no documentation about the command, please provide one [here](https://api.lightning.community/?shell)
