### ISSUE TITLE
Payment channel in LND

### ISSUE THREAD

**Issue by Neoblock8** [lightningnetwork/lnd#6410]
Hi,

I have created a new channel and send some LND to another channel. The payment transaction was successful.
It will not reflect in another channel, But amount will be detected in first channel.

Can anyone provide me a payment channel document for LND?

### Your environment

* version of `lnd`
lnd version 0.12.1-beta commit=v0.12.1-beta

* which operating system (`uname -a` on *Nix)/

* version of `btcd`, `bitcoind`, or other backend
bitcoind: Bitcoin Core version v22.99.0-08bcfa27675d 

* any other relevant environment details

**Comment by yyforyongyu** [comment]
You can check this link,
https://docs.lightning.engineering/lightning-network-tools/lnd

> It will not reflect in another channel

What do you mean here? What command did you use to check the balance?

**Comment by Neoblock8** [comment]
> You can check this link, https://docs.lightning.engineering/lightning-network-tools/lnd
> 
> > It will not reflect in another channel
> 
> What do you mean here? What command did you use to check the balance?

Hi,

Using below commands to send LND to another channel.
Command for checking balance: ./lncli --network=testnet walletbalance


**connect 1st with 2nd server**
open a channel with local amount in server 1
./lncli --network=testnet openchannel --push_amt=10 --local_amt 20000
It will added in list channels
**Add invoice in server2**
./lncli --network=testnet addinvoice --amt=10 --memo="test"
**send payment in server1**
./lncli --network=testnet sendpayment --pay_req=lnt........
**check lookupinvoice**
./lncli --network=testnet lookupinvoice ""
**close channel**

**Comment by guggero** [comment]
If you pay from one node to another, then on one node you have an invoice (the node getting paid) and on the other node you have a payment (the node paying). So I'm not sure if that is your question, but you should see the same payment with `lncli listinvoices` on the payee node and with `lncli listpayments` on the payer node.

Be aware that `--push_amt` is equal to sending a payment. So you're basically giving free money to the other node!

**Comment by Neoblock8** [comment]
> If you pay from one node to another, then on one node you have an invoice (the node getting paid) and on the other node you have a payment (the node paying). So I'm not sure if that is your question, but you should see the same payment with `lncli listinvoices` on the payee node and with `lncli listpayments` on the payer node.
> 
> Be aware that `--push_amt` is equal to sending a payment. So you're basically giving free money to the other node!

Hi @guggero 

Sending lnd to another channel. The same payment can be visible in **lncli listinvoices** on the payee node and with **lncli listpayments** on the payer node. Then, I have to check my walletbalance [**./lncli --netowrk=testnet walletbalance**] but it is not credited. 

If i check with **./lncli --netowrk=testnet channelbalance**, It shows both local and remote balance.

Where we can check the updated channel balance in lnd?

**Comment by guggero** [comment]
The `lncli walletbalance` shows you the (L1) on-chain balance. The `lncli channelbalance` shows you the (L2) off-chain balance. If you send a payment, that only affects the off-chain balance. You can use `lncli listchannels` to see the available balances of each individual channel.

You can familiarize yourself with how the Lightning Network works with resources like [`lnbook`](https://github.com/lnbook/lnbook). That should help you understand the difference between local and remote balance.
You can also sign up to [our community Slack server](https://lightning.engineering/slack.html) for help with basic questions.
The issue tracker should be used for bugs and production issues.
