### ISSUE TITLE
lnwallet: sendcoins --sweepall uses reserved anchor sweep output

### ISSUE THREAD

**Issue by cryptagoras** [lightningnetwork/lnd#6416]
### Background

`lncli sendcoins --sweepall ...`
uses all unspent outputs, including anchor sweep reserved output(s?) and recreates a new output.

### Your environment

* version of `lnd` 
  * 0.14.2
* which operating system (`uname -a` on *Nix)
  * Ubuntu 20.04 LTS
* version of `btcd`, `bitcoind`, or other backend
  * Bitcoin core 22.0
* any other relevant environment details

### Steps to reproduce

While having at least one active anchor channel.
`lncli sendcoins --sweepall ...`

### Expected behaviour

Create a single-output on-chain TX and not include any reserved outputs.

### Actual behaviour

Creates an on-chain TX with two outputs.

**Comment by Roasbeef** [comment]
How are you gaging that it's using the reserved outputs? 

> Creates an on-chain TX with two outputs.

This is expected, it'll ensure that it sends back enough to reach its anchor reserve on chain. 

AFAICT, this is working as expected.

**Comment by cryptagoras** [comment]
> How are you gaging that it's using the reserved outputs?
> 
tbf I'm speculating. I think I read somewhere that anchor sweeps were reserving an output. I may use the wrong terminology. Also it was 100k sats and happened at least once more in the past again with an extra output of 100k sats.

Also I just noticed that I had a pending force close of a channel that has `"anchor": "LIMBO"` but the commitment type of the channel was `STATIC_REMOTE_KEY`, so not sure if it's related.

> > Creates an on-chain TX with two outputs.
> 
> This is expected, it'll ensure that it sends back enough to reach its anchor reserve on chain.
> 
> AFAICT, this is working as expected.

Wouldn't be ideal to not touch the anchor reserve? It's a waste of sats, blockspace (and maybe a soft privacy leak?).

**Comment by Roasbeef** [comment]
> Wouldn't be ideal to not touch the anchor reserve? It's a waste of sats, blockspace (and maybe a soft privacy leak?).

The issue is that we don't actually carve out additional UTXOs (would cost more over time). Instead we just tally how much needs to be left over. As a result, there isn't a good way to ensure that balance is kept other than the "send back" trick. 

We could alternatively try to craft the UTXO sizes perfectly, but that itself would generate extra change outputs each time we need to do transaction, and also bring in more inputs as well. 

> Also I just noticed that I had a pending force close of a channel that has "anchor": "LIMBO" but the commitment type of the channel was STATIC_REMOTE_KEY, so not sure if it's related.

Is the `lncli` client up to date? Some of the proto types changed in a prior release as with the channel type feature in the protocol, there isn't always necessarily a "default" implicit type.

**Comment by cryptagoras** [comment]
> The issue is that we don't actually carve out additional UTXOs (would cost more over time). Instead we just tally how much needs to be left over. As a result, there isn't a good way to ensure that balance is kept other than the "send back" trick.
> 
> We could alternatively try to craft the UTXO sizes perfectly, but that itself would generate extra change outputs each time we need to do transaction, and also bring in more inputs as well.

I see, yeap, just thought I'll report it in case it was a bug. I kinda see it as an enchantment, and would be helpful to me since I tend to use sweepall when fees are low, but feel free to close the issue. 

> Is the `lncli` client up to date? Some of the proto types changed in a prior release as with the channel type feature in the protocol, there isn't always necessarily a "default" implicit type.

It is up to date, but the channel was couple years old so maybe that's the reason.
