### ISSUE TITLE
Clarification: neutrino on mainnet?

### ISSUE THREAD

**Issue by ckcollab** [lightningnetwork/lnd#642]
I believe you can only use neutrino on testnet, is that true? Just wanted to clear this up and help anyone looking for information in the future!

**Comment by dabura667** [comment]
You can use neutrino on mainnet. But it’s not production ready, so you shouldn’t.

**Comment by ckcollab** [comment]
Which neutrino server can you point to?

**Comment by dabura667** [comment]
Make your own.

**Comment by dabura667** [comment]
Compile roasbeef/btcd master and sync the blockchain. Now you have a full node serving neutrino.

**Comment by ckcollab** [comment]
Ok.... that defeats the purpose for me.

So there is no public neutrino server available? If I'm already running a full node there's no point right...?

**Comment by dabura667** [comment]
Don’t use LND on mainnet.

**Comment by ckcollab** [comment]
Err... why not? I'm confused, what does this have to do with my questions? I'm well aware of the risks I'm taking...

**Comment by Roasbeef** [comment]
Don't use lnd on mainnet...yet ;)

**Comment by dabura667** [comment]
Aware of the risks YOU’RE taking.

If we put up a public mainnet neutrino server, that would be ENCOURAGING people to take a risk that they might be underestimating.

And no one wants to encourage that right now.

Sync a full node, it’s not that big of a deal.

Or find someone who already synced btcd to compile a neutrino capable fork and tell you their IP address.

**Comment by ckcollab** [comment]
> If we put up a public mainnet neutrino server, that would be ENCOURAGING people to take a risk that they might be underestimating.

I really don't think anyone capable of running a LN node (let alone Docker...) is unaware of the risks. 

> Sync a full node, it’s not that big of a deal.

Eh... it's annoying for sure. I'd like to play around on mainnet quickly and easily, it's certainly my *opinion*. I mean, why do you even have neutrino if it's not a big deal? I want to test apps on Heroku, so it's hugely annoying to have to sync. Neutrino is a great solution and I'm excited to use it.

> Or find someone who already synced btcd to compile a neutrino capable fork and tell you their IP address.

Right, that's what this thread is about ;)

Am currently syncing on roasbeef's BTCD, hopefully everything is setup properly.

**Comment by gaillard** [comment]
Since the majority of people will probably want to run in a light mode, connecting to a public neutrino serving btcd, is any attention being given to items in neutrino/btcd? I don't see a lot of activity and the recent beta turned off neutrino support :(

**Comment by halseth** [comment]
@gaillard The spec (BIP157/158) changed slightly, and `neutrino` needs to be updated to follow this before it can be used on mainnet. It is definitely being given attention :)
