### ISSUE TITLE
Allow sending whole utxos to external address

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#6426]
### Background

Was sending out a FC output to cold wallet, checked out `lncli sendcoins` and was surprised to notice there it no way to just "send out whole utxo minus miner fees" (110sats at 1sat/vB with 1 input and 1 output).
Used `bos fund` in the end, which made me pay a fee that included the bandwidth of a change output which wasn't there, overpaid 31sats! Thirtyone satoshis!!!!1one

### Your environment

* version of `lnd` 0.14.2
* which operating system (`uname -a` on *Nix) latest raspiod
* version of `btcd`, `bitcoind`, or other backend 22
* any other relevant environment details //

### Steps to reproduce

Have a utxo other than the anchor sitting in hot wallet, wisely decide to move out to cold wallet, notice there is no option to easily have the whole utxo sent out with coin selection and auto fee deduction.

### Expected behaviour

Having something like `lncli sendcoins --utxos outpoint0[,outpoint1,...] ...` that will send out whole utxo(s) amount deducting correct fee depending on selected fee-rate

### Actual behaviour

No such option is present

**Comment by alexbosworth** [comment]
Related issue https://github.com/lightningnetwork/lnd/issues/5863

**Comment by Roasbeef** [comment]
You can use `lncli sendcoins --sweepall`. 

Or you can use a custom PSBT spend, or a manual one using the UTXO locking APIs.
