### ISSUE TITLE
 "payment_error": "IncorrectCltvExpiry(... While trying to paying invoice

### ISSUE THREAD

**Issue by evilmrburns** [lightningnetwork/lnd#643]
Steps to reproduce, I am trying to place a bet on thunderdice.ws

1. I create an invoice for winnings and send it.
2. Then I decode their invoice. 
`lnd# lncli decodepayreq lntb10m1pdxxwh5pp50wurp8qrkl8ndf0g77c9p2cg7nr686dq0et03rkp4qap5nel5kksdzgu2d2ruyl36ezq5n0d3kzqgesx9pngw2n2a9y55jdgveny3zjgd9nskzyfpy9zk3nyrcflfy7cqzysxqzfvwmjqm25mdmr7gzk3fv5uajulla3s40xm4qe22j2t8z65k70hxj7nffyq3mea0fd5dn7xexchp4v65zw4dlym3acx30zqnmckjed2x5qpz4w7qy
{
    "destination": "024c873f489141f6581c78a8af32a6209eb23847ca55c18b4032e6789af1abfcd0",
    "payment_hash": "7bb8309c03b7cf36a5e8f7b050ab08f4c7a3e9a07e56f88ec1a83a1a4f3fa5ad",
    "num_satoshis": "1000000",
    "timestamp": "1516452596",
    "expiry": "300",
    "description": "⚡🎲 Roll #01C49SWJJRMC32DRCK8XDHHQZ3 🤞",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144"`

No problems so far.

3. Things go whack when I payinvoice.

`lnd# lncli payinvoice lntb10m1pdxxwh5pp50wurp8qrkl8ndf0g77c9p2cg7nr686dq0et03rkp4qap5nel5kksdzgu2d2ruyl36ezq5n0d3kzqgesx9pngw2n2a9y55jdgveny3zjgd9nskzyfpy9zk3nyrcflfy7cqzysxqzfvwmjqm25mdmr7gzk3fv5uajulla3s40xm4qe22j2t8z65k70hxj7nffyq3mea0fd5dn7xexchp4v65zw4dlym3acx30zqnmckjed2x5qpz4w7qy
{
        "payment_error": "IncorrectCltvExpiry(expiry=1259848, update=(lnwire.ChannelUpdate) {\n Signature: (*btcec.Signature)(0xc426d7e570)({\n  R: (*big.Int)(0xc4216866a0)(89340177582389881986852179839059456963387107954788646610842139216532726933491),\n  S: (*big.Int)(0xc4216866c0)(55895161682399835640186733659274932337009916987062616889610202285333267835250)\n }),\n ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943,\n ShortChannelID: (lnwire.ShortChannelID) 1259567:58:0,\n Timestamp: (uint32) 1516379297,\n Flags: (lnwire.ChanUpdateFlag) 0,\n TimeLockDelta: (uint16) 4,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,\n BaseFee: (uint32) 0,\n FeeRate: (uint32) 1\n}\n",
        "payment_preimage": "",
        "payment_route": null
}`
I've tried multiple times, quickly doing it, waiting until the invoice should almost expire with the same result. They are getting bets placed on their site. I cannot find owner information to find out their implementation or anything.

**Comment by Roasbeef** [comment]
This may happen if their node isn't fully synchronized, or if when you made a payment, a block was mined. It's a race condition that we're aware of. The solution is to add a bit more padding in terms of blocks for our timelocks. Closing this (I think the authors are on our slack so you can contact them there) as it's being tracked in a distinct issue.

**Comment by kristapsk** [comment]
Should this still be an issue or fixed? Tried to do lightning payment with mainnet BTC and got similar error. I'm using local `lnd` with `bitcoind` as a backend, have open channel with yalls.org and tried to pay invoice from Blockstream Store.

**Comment by Roasbeef** [comment]
AFAIK, the blockstream store is currently being updated, so they may have stopped synchronization in order update their node, close out channels, etc. You can get this issue if your node, or their node isn't fully synchronized. This can also happen in the case of a race condition where you try to send a payment right as a block has been mined. This race condition can be fixed by adding a bit of padding w.r.t the timelocks we use when sending payments.

**Comment by kristapsk** [comment]
My node is fully synchronized. Also just tested with paying directly to yalls, that worked. So, if I would do some lightning payment to some other receiver, which is neither yalls nor blockstream, that should indicate it's a problem at blockstream side?

**Comment by Roasbeef** [comment]
>  that should indicate it's a problem at blockstream side?

That's my hunch.

**Comment by kristapsk** [comment]
Seems that was the case. Tried again just now, now got "unable to route payment to destination: TemporaryChannelFailure: insufficient capacity in available outgoing links: need 326352390 mSAT, max available is 67156600 mSAT" error, but that's different thing, got it.

Althrough first time at `lncli payinvoice ...` it kinda hanged up for a long time (minute or more, didn't count seconds), didn't have patience, pressed ^C. Did the same command little bit later, had the above error without any big delays, which is, obviously, either routing issue or yalls.org not having enough balance at their channels to next hops. Unfortunatelly, I cannot provide more debug info what happened first time I ran the command, so it's useless. (isn't here something like verbose output mode for `lncli`?)

**Comment by Roasbeef** [comment]
> TemporaryChannelFailure: insufficient capacity 

Yeah that just means the terminal channel it attempted to route through didn't have enough capacity. 

> isn't here something like verbose output mode for lncli?

For now, the source of information is the logs, in the future if we make the `payinvoice` command more streaming to pass back debug information.
