### ISSUE TITLE
Websockets draft address in node_announcement rejected?

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#6432]
### Background

The following node_announcement doesn't seem to be accepted by LND:

```
01012674c2e7ef68c73a086b7de2603f4ef1567358df84bb4edaa06cf2132965b14e2434faab04170f0089216accbd79188fa3d40dbb0438bd89782cae27cc656bf60007800088082a69a2625e7a2a024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605024b9a424c554549524f4e2d76302e31312e307263332d362d67663963613934650000001d0180c7caa826070224006180000000d0000000005cd2a001260706204c
```

This is with the draft websocket address type (6) (experimental reckless core-lightning mode enabled!):

In particular, the addrlen here is 001d (29), and the addr is `0180c7caa826070224006180000000d0000000005cd2a001260706204c` which breaks down to:

* `01`: IPv4. `80c7caa8` = ip address. `2607` = port.
* `02`: IPv6. `24006180000000d0000000005cd2a001` = ipv6 address. `2607` = port
* `06`: Websocket. `204c` = port

I think we'll remove the code which advertizes this for the coming Core Lightning release, since it prevents broad propagation (see https://github.com/ElementsProject/lightning/issues/5196 ).

**Comment by Roasbeef** [comment]
So looks like reject unknown address types: https://github.com/lightningnetwork/lnd/blob/master/lnwire/lnwire.go#L805-L808 

We _should_ just be ignoring it though: 
> SHOULD ignore the first address descriptor that does NOT match the types defined above.
