### ISSUE TITLE
Non-taproot signing requires superfluous prev outputs

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#6437]
### Background

When signing a non taproot transaction, the API now will require the previous output information, even for non-Taproot signatures where those previous output values are not signed over. Providing even dummy values for the previous outputs will produce valid signatures so long as the number of inputs is consistent, because the prev inputs data in the non-Taproot case is not used and not needed.

### Your environment

* lnd docker build daily-testing-20220420

### Steps to reproduce

- Create a tx that has 2 inputs, spending p2wpkh outpoints
- Sign the tx but only sign with one of the outpoints, using `SignOutputRaw`

### Expected behavior

- A signature would be produced

### Actual behavior

- Error: `provided previous outputs doesn't match number of transaction inputs`

### Workaround

Pass dummy values to match the number of inputs in the transaction, this will produce a valid signature and no error

**Comment by alexbosworth** [comment]
I guess another workaround here is look at the output scripts in the prev outs, if none are v1, omit the prev outs entirely?

**Comment by guggero** [comment]
Discussed this offline to clarify. A caller should either completely omit the `PrevOutputs` field (for example when signing v0 inputs) or provide a complete set (one entry for each of the inputs of the transaction, required when signing a v1 input).
But an incomplete set is never allowed, independent of what type of input is being signed.
