### ISSUE TITLE
Question regarding channel annoucements numConfs

### ISSUE THREAD

**Issue by hydranetdev** [lightningnetwork/lnd#6439]
Hi,

![image](https://user-images.githubusercontent.com/22526009/164405210-1b814e08-0da8-4f66-8114-e10f4c457e08.png)

if i understand this correctly, a LND will never broadcast a channel unless it has 6 confirmations, even if the number of required confirmations for channel is lower.
Why was it not made configurable and what implications would it have to lower this so say 3 confs?
Thanks and kind regards

**Comment by guggero** [comment]
It's a spec thing:
https://github.com/lightning/bolts/blob/master/07-routing-gossip.md#the-announcement_signatures-message

> MUST NOT send announcement_signatures messages until funding_locked has been sent and received AND the funding transaction has at least six confirmations.
