### ISSUE TITLE
Unclear how to subscribe for TX confirmation without public key script

### ISSUE THREAD

**Issue by torkelrogstad** [lightningnetwork/lnd#6443]
### Background

I'm trying to use the chain notifier RPC interface to subscribe for confirmation updates to a transaction I've broadcast. I only care about this specific TXID to receive a confirmation. 

Looking at the Proto sources, it looks like it should be possible to achieve this. 

https://github.com/lightningnetwork/lnd/blob/9572b49922d77e2605cda27f3ddcbe9b21567828/lnrpc/chainrpc/chainnotifier.proto#L10-L19

### Your environment

* version of `lnd`: 0.14.2 (running on Voltage)
* which operating system (`uname -a` on *Nix): don't know, Voltage
* version of `btcd`, `bitcoind`, or other backend: neutrino, don't know version because of Voltage

### Steps to reproduce

1. Call the `RegisterConfirmationsNtfn` RPC method with _just_ the `txid` parameter set. 

### Expected behaviour

I'd expect to get a successfull subscription to updates about my TXID. 

### Actual behaviour

I get an error: `an output script must be provided`

**Comment by alexbosworth** [comment]
Did you try the `SubscribeTransactions` API?

**Comment by torkelrogstad** [comment]
I've briefly looked at it, maybe it could solve my use case. 

However, for the sake of curiosity I'd really like to get the `RegisterConfirmationsNtfn` to work. I'm having a hard time figuring out what to stick into the output script parameter. Would be great with some pointers here. For example for [this historical TX](https://mempool.space/tx/026cb0cdf1da2c315e51e7d29181c663eabf435e9370dac280916e7d840a56bf) (just a random one I grabbed from mempool.space), what should I use as the output script value?

**Comment by alexbosworth** [comment]
the output script is like the resolved chain address that is being sent to, like `0014fc6ab29af77f67b2e0c6a986a965eb106f52c9e2`

**Comment by torkelrogstad** [comment]
Thanks. After doing this on a new TX (TXID `b8a2a7cd18785e8679ac2b4e560821735459ffde687311c645a4e2692c008ebf"`, script `a91498e34d0267714760e3e826b54b6ee3bbb5edb41187`), I see a bunch of logs similar to this after it got confirmed:

```
2022-04-23 03:48:30.286 [ERR] BTCN: filter for block 00000000000000000000508dec60f4d8df39a03d73fd5a523e11704600d7e368 might be invalid, input 0 of tx 491f312efcc830205ac0028d24204f69d6ea14c817893b2844d56868b2315e83 spends pk script 00200259ef57aa3567399cf328b0b298bd4efbb00ecc3fb72b07ca7182292468fcee which wasn't matched by filter. The input likely spends a taproot output which is not yetsupported 
```

Don't see any log lines relating to neither my TXID nor my script. 

Am I doing something wrong here, or maybe misunderstanding how this is supposed to work?

**Comment by guggero** [comment]
I think that's just some blocks that contain Taproot outputs which the Neutrino filters don't understand/validate yet.

**Comment by torkelrogstad** [comment]
So the messages I'm seeing about the filters are completely unrelated to my problem?

**Comment by alexbosworth** [comment]
I'm not sure what your code is doing exactly but an event should be raised when a tx with the given output script confirms, maybe check how you are calling the API

**Comment by torkelrogstad** [comment]
I've created a reproduction of the setup I'm using [here](https://github.com/torkelrogstad/lnd-notify-test). 

It fetches recent transaction from the mempool, and tries to subscribe to it. 

This is the output I get, before it hangs waiting for an update: 

```
❯ go build . && ./lnd-notify-test -cert=$tls -macaroon=$macaroon -lnd=my-lnd-host:10009
2022/04/23 13:39:42 dialing to LND at=my-lnd-host:10009
2022/04/23 13:39:42 connected to LND    chain=mainnet   version=0.14.3-beta commit=v0.14.3-beta.f1-1-g9dab14665         height=733209
2022/04/23 13:39:42 best block height: 733209
2022/04/23 13:39:43 subscribing to TXID=b8b001b02f89a5b8c82acfe853de650ad0ab06834d867dfae100d76a38254ec8 and scriptPubKey=a914a12021889182f5cfcf783582c744eed332dcb99787
```

Meanwhile, the transaction was confirmed in [this block](https://mempool.space/tx/b8b001b02f89a5b8c82acfe853de650ad0ab06834d867dfae100d76a38254ec8). 

In my LND logs, I see these relevant lines: 

```
2022-04-23 18:07:37.501 [INF] NTFN: New block: height=733211, sha=00000000000000000009a92dd83a06bbb8d86b6e1f9d28d4a9feebe402beaf64
2022-04-23 18:07:21.418 [ERR] BTCN: filter for block 00000000000000000009a92dd83a06bbb8d86b6e1f9d28d4a9feebe402beaf64 might be invalid, input 0 of tx 3f3cedcf0ff7fba659c23bfc7ca7de2109682785ccc49a22543b87bf7a1b0b6f spends pk script 0020ffb513d8d583681bb342dbb32b14a4389950ca67c42e2e97d57c55903bb1a31c which wasn't matched by filter. The input likely spends a taproot output which is not yetsupported
2022-04-23 18:07:21.294 [ERR] BTCN: filter for block 00000000000000000009a92dd83a06bbb8d86b6e1f9d28d4a9feebe402beaf64 might be invalid, input 0 of tx 6ae203348d1aec85464a4091bdac900556c37c5ae03b85c825e2adc07c1d28e4 spends pk script 002021a0dfa939c2a3ed50004b7313c1aa208638a876f9e91073c1a325ca19605292 which wasn't matched by filter. The input likely spends a taproot output which is not yetsupported
2022-04-23 18:07:09.161 [INF] BTCN: Verified 1 filter header in the last 26m40.53s (height 733211, 2022-04-23 18:06:54 +0000 UTC)
2022-04-23 18:07:09.115 [INF] CRTR: Processed channels=0 updates=129 nodes=3 in last 59.999931837s
2022-04-23 18:06:59.159 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=733211, hash=00000000000000000009a92dd83a06bbb8d86b6e1f9d28d4a9feebe402beaf64 
```

**Comment by alexbosworth** [comment]
Interesting, I'm not sure exactly what is wrong - does it work if you specify all zeros for the txid?

**Comment by torkelrogstad** [comment]
Omiting the TXID parameter worked!

**Comment by torkelrogstad** [comment]
If it's any interest, I digged up the relevant log lines from when I got a hit: 

```
│2022-04-24 03:55:02.185 [WRN] NTFN: Ignoring address reuse for script=0 5e8019fb7d6395712aebba89ffe1f3dc1113819a at height 733270.                                                                        
│2022-04-24 03:55:02.294 [INF] NTFN: New block: height=733270, sha=000000000000000000055735e9795afc85e59f9fe409e69e77b7cf597ecaad67                                                                        
│2022-04-24 03:55:02.294 [INF] NTFN: Dispatching 1 confirmation notification for script=0 5e8019fb7d6395712aebba89ffe1f3dc1113819a

**Comment by guggero** [comment]
This sounds to me like the classic "TXID must be in reverse byte order if serialized as bytes vs. when shown as hex" problem... So in the lnd RPC if a TXID is a string field, it's expected in the "human readable" form (which is the hex serialization of the reverse of the actual hash).

**Comment by torkelrogstad** [comment]
You're completely right @guggero... Can't really recall how many times I've been bitten by that over the years, and it still keeps popping up every now and then. I used `hex.DecodeString`, fixed by instead doing `chainhash.NewHashFromStr`. 

With that being said - the documentation seems to be incorrect here. The docs imply I should be able to omit the `script` parameter, but without it I get an error.

**Comment by guggero** [comment]
I agree, the working isn't super clear in the docs. It's not clear that you can either specify both the TXID _and_ script (then both need to match) or _only_ the script (then you get notified if the script confirms in a different TX).
But the API definitely isn't built for only matching on the TXID alone, it is explicitly built to detect specific scripts being confirmed.
