### ISSUE TITLE
Channel balance in LND

### ISSUE THREAD

**Issue by Neoblock8** [lightningnetwork/lnd#6449]
Hi,
  Open a channel and send some amount to another channel.
  **In server1 channel balance is:**
      "balance": "19717",                                                                                                     
      "pending_open_balance": "0",                                                                                           
      "local_balance": {                                                                                                          
      "sat": "19717",                                                                                                        
      "msat": "19717000"                                                                                                 
     },                                                                                                                      
   "remote_balance": {                                                                                                         
    "sat": "100",                                                                                                           
    "msat": "100000"                                                                                                    
    }

 **In server2 channel balance is:**
      "balance": "100",                                                                                                     
      "pending_open_balance": "0",                                                                                           
      "local_balance": {                                                                                                          
      "sat": "100",                                                                                                        
      "msat": "100000"                                                                                                 
     },                                                                                                                      
   "remote_balance": {                                                                                                         
    "sat": "19717",                                                                                                           
    "msat": "19717000"                                                                                                    
    }
    
    
   After closing the channel, Server1 channel local balance is credited in lnd walletbalance but In server2 channel local balance is not credited. And then, Checking channel balance in both servers, it becomes zero. Where the server2 channel local balance is credited?

**Comment by ziggie1984** [comment]
Yes thats normal because in lightning if your local_balance is under the bitcoin dustlimit the output of your peer (100 sats) gets trimmed away, dust-limit for normal segwit v0 is 294 sats.

**Comment by ziggie1984** [comment]
By trimmed away, it is added to the fees of the transaction

**Comment by alexbosworth** [comment]
you can also look at the commitment fee portion of your channels, some funds are reserved for chain fees and that is represented in the balance
