### ISSUE TITLE
'lncli queryroutes' almost always hangs for most pubkeys

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#645]
I just set up a testnet lnd node and received funds from a faucet using the following tutorial: http://lightning.community/lnd/faucet/2017/01/19/lightning-network-faucet/ .

Everything was successful until I tried to queryroutes. Querying the route to the faucet succeeds (it is still my active peer):
`lncli queryroutes --dest=02c39955c1579afe4824dc0ef4493fdf7f3660b158cf6d367d8570b9f19683afb5 --amt=1000`

But querying the route to my other active peer hangs (including if amt=1000000):
`lncli queryroutes --dest=02f6d66509f7ef98d9470ab5dc3998f8785112c545f86e50b9811772a9166f99dc --amt=1000`

Also, querying a random pubkey found in the 'lnd describegraph' output hangs.
`lncli queryroutes --dest=038e1c0dee8a07504e9870e16e22162a8c3c51698ba051e5d1ca14b0f3cc2afee8 --amt=1000000`

Notably the third case succeeded once, taking only a few seconds, but I haven't been able to reproduce that success.

The pubkey listed in the tutorial also hangs:
`lncli queryroutes --dest=03c3cbc887448ff950c32a3561441249f1983322519fcea18cbb7769cbd2f4b995 --amt=1000000`

Purchasing on Starblocks has been a success each time I've tried, so this appears to be a problem with queryroutes in particular rather than the LN testnet or my machine.

'lncli --version' returns "lncli version 0.3"

Is there any other information I can provide or testing that I can do to help debug this issue?

**Comment by halseth** [comment]
This is a known issue, coming from the fact that a lot of disk IO is done during path finding. A PR to address this is up: https://github.com/lightningnetwork/lnd/pull/379

Also a `max_num_routes` parameter should be added the the `queryroutes` command.

**Comment by Raulo** [comment]
I have the same problem (although eventually the query usually gets resolved) but probably for the same reason, paying invoice hangs. I have 3 channels open and I can pay instantly to yalls and thunderdice but payments to starblocks and htlc.me hang during payinvoice. Interestingly, htlc.me can pay me instantly.

**Comment by Roasbeef** [comment]
Fixed by these series of commits: 33ba60ce661da053dac03a6b28a24433f5648929, 8a29c01354e8867fc8548eaffd25c0b6d250f3f6, ad0f5b31f6129de8edfa4fbeb000bc7460c9ddcf.
