### ISSUE TITLE
Raspberry PI 3B+ runtime/panic.go

### ISSUE THREAD

**Issue by dawiepoolman** [lightningnetwork/lnd#6452]
### Background

After upgrading I get Go errors.

### Your environment

* version of `lnd`: lnd v0.14.3-beta 
* which operating system (`uname -a` on *Nix): Linux raspberrypi 4.19.66-v7+ # 1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: 
Bitcoin Core version v22.0.0
* any other relevant environment details
Go version:  go1.17.3 linux/arm

### Steps to reproduce

The lnd deamon log:

sudo journalctl -f -u lnd
-- Logs begin at Thu 2016-11-03 19:16:43 SAST. --
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.033 [INF] LTND: Version: 0.14.3-beta commit=v0.14.3-beta, build=production, logging=default, debuglevel=info
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.034 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.109 [INF] RPCS: RPC server listening on 127.0.0.1:10009
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.140 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.145 [INF] LTND: Opening the main database, this might take a few minutes...
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.145 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.173 [INF] CHDB: Compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db
Apr 24 00:33:23 raspberrypi lnd[2246]: 2022-04-24 00:33:23.173 [INF] CHDB: Found old temp DB @ /home/bitcoin/.lnd/data/graph/mainnet/temp-dont-use.db, removing before swap
Apr 24 00:33:53 raspberrypi lnd[2246]: 2022-04-24 00:33:53.033 [ERR] RPCS: [/lnrpc.WalletUnlocker/UnlockWallet]: waiting to start, RPC services not available
Apr 24 00:33:53 raspberrypi systemd[1]: Started LND Lightning Daemon.
Apr 24 00:37:41 raspberrypi lnd[2246]: unexpected fault address 0x76f19040
Apr 24 00:37:41 raspberrypi lnd[2246]: fatal error: fault
Apr 24 00:37:41 raspberrypi lnd[2246]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x76f19040 pc=0x522d40]
Apr 24 00:37:41 raspberrypi lnd[2246]: goroutine 1 [running]:
Apr 24 00:37:41 raspberrypi lnd[2246]: runtime.throw({0x14ce704, 0x5})
Apr 24 00:37:41 raspberrypi lnd[2246]:         runtime/panic.go:1198 +0x5c fp=0x4a90fe0 sp=0x4a90fcc pc=0x49e18
Apr 24 00:37:41 raspberrypi lnd[2246]: runtime.sigpanic()
Apr 24 00:37:41 raspberrypi lnd[2246]:         runtime/signal_unix.go:742 +0x1d0 fp=0x4a90ff8 sp=0x4a90fe0 pc=0x63590
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*DB).meta(0x45ac3c0)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/db.go:948 +0x1c fp=0x4a91014 sp=0x4a90ffc pc=0x522d40
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*DB).hasSyncedFreelist(...)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/db.go:330
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Tx).rollback(0x44cdf80)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/tx.go:278 +0x5c fp=0x4a91028 sp=0x4a91014 pc=0x52c6cc
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Tx).Commit(0x44cdf80)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/tx.go:161 +0x2a0 fp=0x4a910bc sp=0x4a91028 pc=0x52bf54
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).compact.func2({0x4c035f0, 0x2, 0x2}, {0x2adf7a89, 0x8, 0x8}, {0x2adf7a91, 0x1f8, 0x1f8}, 0x0)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:152 +0xc0 fp=0x4a91100 sp=0x4a910bc pc=0xcd16c4
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0x4a916dc, 0x4640760, {0x4c035f0, 0x2, 0x2}, {0x2adf7a89, 0x8, 0x8}, {0x2adf7a91, 0x1f8, ...}, ...)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:262 +0x74 fp=0x4a91154 sp=0x4a91100 pc=0xcd1f04
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket.func1({0x2adf7a89, 0x8, 0x8}, {0x2adf7a91, 0x1f8, 0x1f8})
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:280 +0x90 fp=0x4a911ac sp=0x4a91154 pc=0xcd20e0
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Bucket).ForEach(0x4640760, 0x4a91218)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0x114 fp=0x4a911e0 sp=0x4a911ac pc=0x51c014
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0x4a916dc, 0x4640760, {0x440df50, 0x1, 0x1}, {0x39bcfab0, 0xa, 0xa}, {0x0, 0x0, ...}, ...)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:273 +0x170 fp=0x4a91234 sp=0x4a911e0 pc=0xcd2000
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket.func1({0x39bcfab0, 0xa, 0xa}, {0x0, 0x0, 0x0})
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:276 +0x150 fp=0x4a9128c sp=0x4a91234 pc=0xcd21a0
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Bucket).ForEach(0x4641f80, 0x4a912f8)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0x114 fp=0x4a912c0 sp=0x4a9128c pc=0x51c014
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0x4a916dc, 0x4641f80, {0x0, 0x0, 0x0}, {0x46424317, 0xa, 0xa}, {0x0, 0x0, ...}, ...)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:273 +0x170 fp=0x4a91314 sp=0x4a912c0 pc=0xcd2000
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1.1({0x46424317, 0xa, 0xa}, 0x4641f80)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:226 +0x150 fp=0x4a9136c sp=0x4a91314 pc=0xcd1ca0
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Tx).ForEach.func1({0x46424317, 0xa, 0xa}, {0x0, 0x0, 0x0})
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/tx.go:129 +0x70 fp=0x4a9138c sp=0x4a9136c pc=0x52bbb4
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Bucket).ForEach(0x457e70c, 0x4a913d4)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0x114 fp=0x4a913c0 sp=0x4a9138c pc=0x51c014
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*Tx).ForEach(0x457e700, 0x4a513f4)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/tx.go:128 +0x58 fp=0x4a913e0 sp=0x4a913c0 pc=0x52bb1c
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1(0x457e700)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:220 +0x54 fp=0x4a91400 sp=0x4a913e0 pc=0xcd1b28
Apr 24 00:37:41 raspberrypi lnd[2246]: go.etcd.io/bbolt.(*DB).View(0x45ac280, 0x4a51444)
Apr 24 00:37:41 raspberrypi lnd[2246]:         go.etcd.io/bbolt@v1.3.6/db.go:772 +0x90 fp=0x4a91430 sp=0x4a91400 pc=0x522248
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walk(0x4a516dc, 0x45ac280, 0x4a51480)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:219 +0x54 fp=0x4a91450 sp=0x4a91430 pc=0xcd1aac
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).compact(0x4a516dc, 0x45ac3c0, 0x45ac280)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:147 +0xe4 fp=0x4a914a0 sp=0x4a91450 pc=0xcd1568
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.(*compacter).execute(0x4a916dc)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:117 +0x5ac fp=0x4a915ec sp=0x4a914a0 pc=0xcd0f38
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.compactAndSwap(0x4a51910)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:179 +0x76c fp=0x4a91708 sp=0x4a915ec pc=0xccfeec
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/kvdb.GetBoltBackend(0x4a91910)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:101 +0x98 fp=0x4a91750 sp=0x4a91708 pc=0xccf460
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd/lncfg.(*DB).GetBackends(0x45fc100, {0x189d1ec, 0x4918900}, {0x49001e0, 0x25}, {0x443f230, 0x2d}, {0x46368c0, 0x32}, 0x0, ...)
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/lncfg/db.go:392 +0x11cc fp=0x4a91934 sp=0x4a91750 pc=0xf1f8b4
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x44ae730, {0x189d1ec, 0x4918900})
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/config_builder.go:810 +0x318 fp=0x4a91a38 sp=0x4a91934 pc=0x1138f48
Apr 24 00:37:41 raspberrypi lnd[2246]: github.com/lightningnetwork/lnd.Main(0x4588c00, {{0x0, 0x0, 0x0}}, 0x4494510, {0x4695380, 0x446b580, 0x446b5c0, 0x446b600, {0x0}})
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/lnd.go:353 +0x14f4 fp=0x4a91f50 sp=0x4a91a38 pc=0x113d1a4
Apr 24 00:37:41 raspberrypi lnd[2246]: main.main()
Apr 24 00:37:41 raspberrypi lnd[2246]:         github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x20c fp=0x4a91fbc sp=0x4a91f50 pc=0x118e344
Apr 24 00:37:41 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 00:37:41 raspberrypi systemd[1]: lnd.service: Unit entered failed state.
Apr 24 00:37:41 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
Apr 24 00:38:41 raspberrypi systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Apr 24 00:38:41 raspberrypi systemd[1]: Stopped LND Lightning Daemon.
Apr 24 00:38:41 raspberrypi systemd[1]: Starting LND Lightning Daemon...
Apr 24 00:38:41 raspberrypi lnd[2305]: Attempting automatic RPC configuration to bitcoind
Apr 24 00:38:41 raspberrypi lnd[2305]: Automatically obtained bitcoind's RPC credentials
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.886 [INF] LTND: Version: 0.14.3-beta commit=v0.14.3-beta, build=production, logging=default, debuglevel=info
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.886 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.892 [INF] RPCS: RPC server listening on 127.0.0.1:10009
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.911 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.912 [INF] LTND: Opening the main database, this might take a few minutes...
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.912 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.912 [INF] CHDB: Compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db
Apr 24 00:38:41 raspberrypi lnd[2305]: 2022-04-24 00:38:41.912 [INF] CHDB: Found old temp DB @ /home/bitcoin/.lnd/data/graph/mainnet/temp-dont-use.db, removing before swap
Apr 24 00:38:53 raspberrypi lnd[2305]: unexpected fault address 0x76f89040
Apr 24 00:38:53 raspberrypi lnd[2305]: fatal error: fault
Apr 24 00:38:53 raspberrypi lnd[2305]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x76f89040 pc=0x522d40]
Apr 24 00:38:53 raspberrypi lnd[2305]: goroutine 1 [running]:
Apr 24 00:38:53 raspberrypi lnd[2305]: runtime.throw({0x14ce704, 0x5})
Apr 24 00:38:53 raspberrypi lnd[2305]:         runtime/panic.go:1198 +0x5c fp=0x4a06fe0 sp=0x4a06fcc pc=0x49e18
Apr 24 00:38:53 raspberrypi lnd[2305]: runtime.sigpanic()
Apr 24 00:38:53 raspberrypi lnd[2305]:         runtime/signal_unix.go:742 +0x1d0 fp=0x4a06ff8 sp=0x4a06fe0 pc=0x63590
Apr 24 00:38:53 raspberrypi lnd[2305]: go.etcd.io/bbolt.(*DB).meta(0x4162500)
Apr 24 00:38:53 raspberrypi lnd[2305]:         go.etcd.io/bbolt@v1.3.6/db.go:948 +0x1c fp=0x4a07014 sp=0x4a06ffc pc=0x522d40
Apr 24 00:38:53 raspberrypi lnd[2305]: go.etcd.io/bbolt.(*DB).hasSyncedFreelist(...)
Apr 24 00:38:53 raspberrypi lnd[2305]:         go.etcd.io/bbolt@v1.3.6/db.go:330
Apr 24 00:38:53 raspberrypi lnd[2305]: go.etcd.io/bbolt.(*Tx).rollback(0x4b78e80)
Apr 24 00:38:53 raspberrypi lnd[2305]:         go.etcd.io/bbolt@v1.3.6/tx.go:278 +0x5c fp=0x4a07028 sp=0x4a07014 pc=0x52c6cc
Apr 24 00:38:53 raspberrypi lnd[2305]: go.etcd.io/bbolt.(*Tx).Commit(0x4b78e80)
Apr 24 00:38:53 raspberrypi lnd[2305]:         go.etcd.io/bbolt@v1.3.6/tx.go:161 +0x2a0 fp=0x4a070bc sp=0x4a07028 pc=0x52bf54
Apr 24 00:38:53 raspberrypi lnd[2305]: github.com/lightningnetwork/lnd/kvdb.(*compacter).compact.func2({0x42f2180, 0x2, 0x2}, {0x2ae27a89, 0x8, 0x8}, {0x2ae27a91, 0x1f8, 0x1f8}, 0x0)
Apr 24 00:38:53 raspberrypi lnd[2305]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:152 +0xc0 fp=0x4a07100 sp=0x4a070bc pc=0xcd16c4
Apr 24 00:38:53 raspberrypi lnd[2305]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0x4a076dc, 0x4414980, {0x42f2180, 0x2, 0x2}, {0x2ae27a89, 0x8, 0x8}, {0x2ae27a91, 0x1f8, ...}, ...)
Apr 24 00:38:53 raspberrypi lnd[2305]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:262 +0x74 fp=0x4a07154 sp=0x4a07100 pc=0xcd1f04
Apr 24 00:38:53 raspberrypi lnd[2305]: github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket.func1({0x2ae27a89, 0x8, 0x8}, {0x2ae27a91, 0x1f8, 0x1f8})
Apr 24 00:38:53 raspberrypi lnd[2305]:         github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:280 +0x90 fp=0x4a071ac sp=0x4a07154 pc=0xcd20e0
Apr 24 00:38:53 raspberrypi lnd[2305]: go.etcd.io/bbolt.(*Bucket).ForEach(0x4414980, 0x4a07218)
Apr 24 00:38:53 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 00:39:11 raspberrypi systemd[1]: Failed to start LND Lightning Daemon.
Apr 24 00:39:11 raspberrypi systemd[1]: lnd.service: Unit entered failed state.
Apr 24 00:39:11 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.

**Comment by dawiepoolman** [comment]
I tried downgrading to LND v0.14.2-beta but getting similar errors

**Comment by guggero** [comment]
https://github.com/lightningnetwork/lnd/issues?q=is%3Aissue+is%3Aclosed+unexpected+fault+address+

https://github.com/lightningnetwork/lnd/issues/5877

Likely cause: Channel DB got too big for 32bit OS. You need to upgrade your Raspberry Pi OS to a 64bit version.

**Comment by dawiepoolman** [comment]
This solved the issue thanks you.  I have upgraded to a RPi4 64bit
