### ISSUE TITLE
Anchor channel stuck in waiting close

### ISSUE THREAD

**Issue by LNOrville** [lightningnetwork/lnd#6453]
**Background**

Requested a channel close via RTL setting a 1 sat/vb fee. Channel closing is now stuck in limbo.

**Your environment**

* Lnd v0.14.2-beta
* Umbrel on a RasPi
* Used RTL for the closing request.

**Steps to reproduce**
Cooperatively close anchor channel with a (too?) low fee (1 sat/vb) - preferably via RTL.
Check that the output of lncli pendingchannels looks something like this (*variables* removed for privacy reasons):
total_limbo_balance": "*number*",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "*Pub ID*",
                "channel_point": "*CP:1*",
                "capacity": "*number*",
                "local_balance": "*number*",
                "remote_balance": "*number*",
                "local_chan_reserve_sat": "10010",
                "remote_chan_reserve_sat": "10010",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "2",
                "chan_status_flags": "ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator"
            },
            "limbo_balance": "*number*",
            "commitments": {
                "local_txid": "eda0b18eb4b92542042f51d897711aff50353d7b72dafc2e2fe85c3f0f4d4c48",
                "remote_txid": "c071940dd10dab21ba747ef8be4d9b68228c24c608d58c05fe5754242713ceaa",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2013",
                "remote_commit_fee_sat": "2013",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }

**Expected behaviour**

Cooperative close of channel after a while when mempool empties out and is available to process 1 sat/vb tx

**Actual behaviour**

Channel stuck in waiting close, funds stuck in limbo.
Closing node is more than willing to bump the fee, but does not know if that is the correct solution or how to do it.

See also 
https://community.getumbrel.com/t/channel-stuck-in-waiting-close/7340
https://community.getumbrel.com/t/channel-closed-for-several-weeks-waiting-close/7054/12

**Comment by guggero** [comment]
It sounds like the negotiation between the two peers timed out. At least the closing transaction couldn't be found in the mempool anymore. So because of [this](https://github.com/lightningnetwork/lnd/issues/4819) you can't try again.
You'll need to force close the channel in this case, unfortunately.

**Comment by LNOrville** [comment]
No, it looks like none of the tx ids in the pendingchannels output was ever in the mempool. I was a bit hesitant to try a force close, since another person in the Umbrel forum had the same issue, and they reported that a force close did not help, but if you think a force close is the way to go I will try that.

**Comment by guggero** [comment]
Force closing should work fine in such cases. The force close command on the CLI is a bit hard to use, maybe that other user just got it wrong and they got an error message? The command is `lncli closechannel --force <txid> <idx>`, so in your case `lncli closechannel --force 2d106... 1` (notice the space and the `1` after the txid, this is the part a lot of users get wrong).

**Comment by LNOrville** [comment]
Thanks for your help. Force closing worked well, I now have a tx ID showing in mempool and lncli pendingchannels shows a maturity height.
