### ISSUE TITLE
Coop close fee unnecessarily high, even with target confs =1000

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#6458]
### Background

`lnd` will not follow setting in `lnd.conf` regarding fee for channel closure.
Closing two channels with same peer, I started by initiating the closure of the one I opened myself, and had `coop-close-target-confs=100`, mempool was empty, but the fee I paid was 285sats, at 1.69s/vB. Mind you, mempool was really empty, with a streak of preceding blocks mostly empty as well.
My soon-to-be-ex-peer advised me to set `coop-close-target-confs=1000` as they had, so I did just that and restarted: this way we both had 1000 as confirmation target.
They then proceeded to coop-close the other channel they did open (as karma would have it) and...
```
[INF] CHCL: ChannelPoint(xxx): proposing fee of 284 sat to close chan
[INF] CHCL: ChannelPoint(xxx) fee of 0.00000284 BTC accepted, ending negotiation
```
no negotiation, no nothing, they as well paid some 100sats more than what was needed.

### Your environment

* version of `lnd` 14.2
* which operating system (`uname -a` on *Nix) latest raspios
* version of `btcd`, `bitcoind`, or other backend 22
* any other relevant environment details //

### Steps to reproduce

Wait for empty mempool, have very high target confs in lnd.conf on both sides, coop-close channel and observe applied tx fee.

### Expected behaviour

Using saner fee rates for closures.

### Actual behaviour

Spending 70% more on closure fees

**Comment by guggero** [comment]
See https://github.com/lightningnetwork/lnd/issues/5345

**Comment by asvdf** [comment]
I see, I did search for open issues but neglected to check in closed ones as well, as IMO this is an ongoing situation :)
Happy to know that someone else pointed it out already, and @Kixunil at that, still unexpected that this is not something that more users feel should be addressed.

**Comment by Kixunil** [comment]
Perhaps LND could force close the channel if the cooperative fee is significantly higher (more than force_close_fee + balance * interest_rate * timelock). However in your case it seems your peer was not abusive and the fee was still higher.

**Comment by BhaagBoseDK** [comment]
Yes LND should never accept a fee higher than what would have been the fee for force close. COOP close is done for a reason otherwise an abusive peer can inflict huge cost on the other side for malicious reasons.

**Comment by hazrulnizam** [comment]
I did two cooperative closes today and the results were interesting. One of them closed almost at exactly the same as issue opener @GordianLN encountered - 284 sats at 1.69 sat/vB:

```
[INF] SWPR: Manual fee rate input of 250 sat/kw is too low, using 253 sat/kw instead
[INF] PEER: Local close channel request delivered to peer: xxxx
[INF] PEER: Delivery addr for channel close: xxxx
[INF] HSWC: ChannelLink(xxxx:x): exited
[INF] HSWC: Removing channel link with ChannelID(xxxx)
[INF] HSWC: ChannelLink(xxxx:x): stopping
[INF] CHCL: Ideal fee for closure of ChannelPoint(xxxx:x) is: 284 sat
[INF] CHCL: ChannelPoint(xxxx:x): initiating shutdown
[INF] NANN: Announcing channel(xxxx:x) disabled [requested]
[INF] CHCL: ChannelPoint(xxxx:x): sending shutdown message
[INF] CHCL: ChannelPoint(xxxx:x): shutdown response received, entering fee negotiation
[INF] CHCL: ChannelPoint(xxxx:x): computing fee compromise, ideal=284, last_sent=0, remote_offer=284
[INF] CHCL: ChannelPoint(xxxx:x): proposing fee of 284 sat to close chan
[INF] CHCL: ChannelPoint(xxxx:x) fee of 0.00000284 BTC accepted, ending negotiation
```

The other closed at closer to 1sat/vB:

```
[INF] SWPR: Manual fee rate input of 250 sat/kw is too low, using 253 sat/kw instead
[INF] PEER: Local close channel request delivered to peer: yyyy
[INF] PEER: Delivery addr for channel close: yyyy
[INF] HSWC: ChannelLink(yyyy:y): exited
[INF] HSWC: Removing channel link with ChannelID(yyyy)
[INF] HSWC: ChannelLink(yyyy:y): stopping
[INF] CHCL: Ideal fee for closure of ChannelPoint(yyyy:y) is: 183 sat
[INF] CHCL: ChannelPoint(yyyy:y): initiating shutdown
[INF] NANN: Announcing channel(yyyy:y) disabled [requested]
[INF] CHCL: ChannelPoint(yyyy:y): sending shutdown message
[INF] CHCL: ChannelPoint(yyyy:y): shutdown response received, entering fee negotiation
[INF] CHCL: ChannelPoint(yyyy:y): proposing fee of 183 sat to close chan
[INF] CHCL: ChannelPoint(yyyy:y): computing fee compromise, ideal=183, last_sent=183, remote_offer=170
[INF] CHCL: ChannelPoint(yyyy:y): proposed remote fee is close enough, capitulating
[INF] CHCL: ChannelPoint(yyyy:y): proposing fee of 170 sat to close chan
[INF] CHCL: ChannelPoint(yyyy:y) fee of 0.0000017 BTC accepted, ending negotiation
```

Note that I initiated both closes with `--sat_per_vbyte 1`, evidenced by the same line in the logs:
```
[INF] SWPR: Manual fee rate input of 250 sat/kw is too low, using 253 sat/kw instead
```

but one of them ended up with:
```
[INF] CHCL: Ideal fee for closure of ChannelPoint(xxxx:x) is: 284 sat
```
while the other with:
```
[INF] CHCL: Ideal fee for closure of ChannelPoint(yyyy:y) is: 183 sat
```

Why do the ideal fees differ? The only thing I can think of is one of them might be a legacy channel while the other is an anchor channel. Perhaps lnd goes through different code logic when calculating closing fees for different channel types?
