### ISSUE TITLE
Unable to calculate total number of payments from /v1/payments REST response

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#6459]
### Background
/v1/payments response returns first and last index offsets, but the total number of payments cannot be calculated through them.

### Your environment
* version of `lnd`: 0.14.1-beta
* which operating system (`uname -a` on *Nix): Windows 10
* version of `btcd`, `bitcoind`, or other backend: 0.21.1

### Expected behaviour
I want to get the total number of payments without fetching the entire list.

### Actual behavior
Current solution is to fetch the complete list of payments, which takes too much time.

**Comment by guggero** [comment]
I agree that it would be nice to just have a `total_num_payments` variable.
But as a workaround, you should be able to get the highest index (which should be `total_num_payments - 1`) by using `include_incomplete=true&may_payments=1&reversed=true` as the query/POST params.

**Comment by guggero** [comment]
Added the feature as requested since it was simple enough to implement. I'm curious, how long does this query take on your test machine with several hundred payments?

**Comment by ShahanaFarooqui** [comment]
Thank you for the quick action. My nodes have a maximum of a few thousand transactions and do not take more than 1-2 seconds.

However, some of our users with a huge number of transactions complain about their UI taking almost 3-5 minutes to fetch all of their payments and invoices.
