### ISSUE TITLE
REST API request for Payment Lookup

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#6460]
### Background
With an ever-increasing number of payments, we want to add a payment lookup feature in the UI, like existing invoice lookup: https://api.lightning.community/#v2-invoices-lookup

### Your environment
* version of `lnd`: 0.14.1
* which operating system (`uname -a` on *Nix): Windows 10
* version of `btcd`, `bitcoind`, or other backend: 0.21.1

### Expected behaviour
To lookup a payment directly through hash, like current invoice lookup API.

### Actual behaviour
No REST API exists for payments lookup yet.

**Comment by guggero** [comment]
There is `TrackPaymentV2` (https://api.lightning.community/#v2-router-track). It's a streaming endpoint, so it'll block and stream updates if the payment isn't final yet. But I think that should return exactly what you're looking for.

**Comment by ShahanaFarooqui** [comment]
We need this endpoint to give an option to search a payment from the list of all payments, not unfinished only. A simple search from the list like invoice lookup, not the subscription.

**Comment by guggero** [comment]
The `TrackPaymentV2` RPC will return the current state of the payment (with all information available at that time) immediately and then keep the stream open for updates if the payment isn't final yet. So for finished payments you can just close the stream after the first message and then you have exactly what you're asking for. It's just not a synchronous API, but I'm pretty sure you have streaming requests with WebSockets working in other places?

**Comment by ShahanaFarooqui** [comment]
Got it, I will check the solution by today EoD and let you know if it works. Thanks.

**Comment by ShahanaFarooqui** [comment]
Track payment worked as per the requirement. Closing the issue now. Thank you for the prompt response.
