### ISSUE TITLE
Loss my funds $lncli sendcoins --sweepall, transaction not broadcasted

### ISSUE THREAD

**Issue by breakeven618** [lightningnetwork/lnd#6466]
### Background

Hi, I have used the command: "lncli sendcoins --sweepall --sat_per_vbyte 1 --addr bc1tergtuzpg5rhu3xd8jxxxx" to withdraw my funds from my LN node and it seems that the transaction has not been broadcast but it has left my balance at zero.

### Your environment

* version of `lnd` : 0.14.3-beta commit=v0.14.3-beta
* which operating system (`uname -a` on *Nix): Debian 5.16.12-2parrot1 (2022-03-11) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v22.0.0 

### Steps to reproduce

I have recently installed LN node but never opened channels. Send some balance and then try to withdraw them.

1)-
$lncli walletbalance
{
    "total_balance": "50000",
    "confirmed_balance": "50000",
    "unconfirmed_balance": "0",
    "locked_balance": "0",
    "account_balance": {
        "default": {
            "confirmed_balance": "50000",
            "unconfirmed_balance": "0"
        }
    }
}

2)-
$lncli sendcoins --sweepall --sat_per_vbyte 1 --addr bc1tergtuzpg5rhu3xd8jxxxx

out: "tx_hash": "783542724d243d5a51dae6c694e91deaxxxxxx"

Then
I have searched in  the mempool the TXHASH and it does not exist.

Then
$lncli walletbalance
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0",
    "locked_balance": "0",
    "account_balance": {
        "default": {
            "confirmed_balance": "0",
            "unconfirmed_balance": "0"
        }
    }
}

Then

$lncli listchaintxns
{
    "transactions": [
        {
            "tx_hash": "783542724d243d5a51dae6c694e91deaxxxxxx",
            "amount": "-50000",
            "num_confirmations": 0,
            "block_hash": "",
            "block_height": 0,
            "time_stamp": "1650920789",
            "total_fees": "318",
            "dest_addresses": [
                "bc1tergtuzpg5rhu3xd8jxxxx"
            ],
            "raw_tx_hex": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "label": "external"
        },

### Expected behaviour

The transaction should have been broadcast.

### Actual behaviour

num_confirmations remain 0
not block_hash
TXHASH not in mempool

I really appreciate any help you can give me. More than to recover the funds, my desire is to learn and collaborate when I can. Thank you very much.

**Comment by guggero** [comment]
As mentioned in the other issue, try the "forced in-place rescan" described here: https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan

**Comment by breakeven618** [comment]
I did this and it has worked perfectly, I have recovered my funds. Thank you very much @guggero.

Solved: 
https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan
⛰  lnd --reset-wallet-transactions
