### ISSUE TITLE
restPort listening on * by default

### ISSUE THREAD

**Issue by Deelight-fr** [lightningnetwork/lnd#647]
Is there a reason for restEndpoint to be mapped to *, while grpcEndpoint is only mapped to localhost. I assume it is probably safer to also map restEndpoint to localhost, to avoid security issues with nodes not protected by a firewall.

lnd.go:
```
 	grpcEndpoint := fmt.Sprintf("localhost:%d", loadedConfig.RPCPort)
	restEndpoint := fmt.Sprintf(":%d", loadedConfig.RESTPort)
```

Maybe it should be a parameter, but localhost by default seems safer.

**Comment by Roasbeef** [comment]
Thanks for reporting this! This can definitely be an issue if a users is running with all authentication _disabled_ via the (`--nomacaroons` option). I'll patch this shortly along with some additional parsing to reject dangerous configuration options.
