### ISSUE TITLE
Curl command for LND

### ISSUE THREAD

**Issue by Neoblock8** [lightningnetwork/lnd#6470]
Hi,
 Is there any curl command for LND network?

**Comment by Roasbeef** [comment]
No, but you can use `curl` along with the REST interface.

**Comment by Neoblock8** [comment]
> No, but you can use `curl` along with the REST interface.

Hi @Roasbeef 
 Then how to access REST Interface

**Comment by guggero** [comment]
https://api.lightning.community/#lnd-rest-api-reference
