### ISSUE TITLE
How to remove sweeps which are never going to succeed!

### ISSUE THREAD

**Issue by BhaagBoseDK** [lightningnetwork/lnd#6471]
### Background
I see a sweep in lncli wallet pending sweep which I am sure will never succeed since the outpoint is invalid.

How do I get rid of this sweep which keep executing (and failing).

Details:

around block 733926 I was fee bumping a sweep transaction for a pending receive from LOOP. 

```
2022-04-28 07:49:03.284 [INF] SWPR: Creating sweep transaction 644b5103c79d8ce7a4b1f3a2c64bf1491037ace75cecbfa069ff03329880fc17 for 1 inputs (d1fc6a954a9c213544746f7d5194e13e0f7cec3761c5b74f4a1d7d48d1fca38f:0 (WitnessKeyHash)) using 750 sat/kw, tx_weight=439, tx_fee=0.00000329 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2022-04-28 07:49:03.294 [INF] LNWL: Inserting unconfirmed transaction 644b5103c79d8ce7a4b1f3a2c64bf1491037ace75cecbfa069ff03329880fc17
2022-04-28 07:49:03.297 [ERR] LNWL: Notifying unmined tx notification (644b5103c79d8ce7a4b1f3a2c64bf1491037ace75cecbfa069ff03329880fc17) while creating notification for blocks
```

Meanwhile the previous transaction was confirmed before the fee bump. (weird). 

`2022-04-28 07:55:05.713 [INF] LNWL: Marking unconfirmed transaction 6f6d0597b743c678b7c47e9b930daa1034a071bb1c1199379e34419ab551ea7e mined in block 733926
`

However now the fee bump transaction is stuck in pendingsweeps.

```
umbrel@umbrel:~/lndlog $ lncli wallet pendingsweeps
{
	"pending_sweeps": [
		{
			"outpoint": "d1fc6a954a9c213544746f7d5194e13e0f7cec3761c5b74f4a1d7d48d1fca38f:0",
			"witness_type": "WITNESS_KEY_HASH",
			"amount_sat": 5169273,
			"sat_per_vbyte": 3,
			"broadcast_attempts": 8,
			"next_broadcast_height": 734002,
			"requested_sat_per_vbyte": 3,
			"requested_conf_target": 0,
			"force": false
		}
	]
}
```

This sweeps keeps getting executed (and fails each time). The outpoint `"outpoint": "d1fc6a954a9c213544746f7d5194e13e0f7cec3761c5b74f4a1d7d48d1fca38f:0",` is invalid.

My UTXOs and Balance is correct. I am 100% sure this sweep is invalid and will never succeed. 

How do I get rid of this sweep from my lnd.

### Your environment

```
umbrel@umbrel:~/lndlog $ lncli getinfo
{
    "version": "0.14.2-beta commit=v0.14.2-beta",
    "commit_hash": "1e511be523eb8e97c4e2d9c89a7a263963a3929f",
    "identity_pubkey": "03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1",
    "alias": "⚡G-Spot-21_69_420⚡",
    "color": "#216942",
    "num_pending_channels": 0,
    "num_active_channels": 226,
    "num_inactive_channels": 4,
    "num_peers": 221,
    "block_height": 733961,
    "block_hash": "00000000000000000000881faf41c4aed5a506c42b0d6d78a806375f8630cc0f",
    "best_header_timestamp": "1651156766",
    "synced_to_chain": true,
    "synced_to_graph": true,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "mainnet"
        }
    ],
    "uris": [
        "03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1@82.16.240.248:9735",
        "03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1@zacadqiqgi43tdv4ztjet2fh22f72ol2tokotp5cqdbszgx6tpyqdxad.onion:9735"
    ],

```

### Expected behaviour

Ability to remove a pending sweep. May be on the line of abandon_channel with --I_AM_SURE flag.

### Actual behaviour

Not able to remove a pending sweep which will never succeed.

**Comment by Roasbeef** [comment]
The set of pending sweeps aren't committed to disk. Instead what's returned there is an in-memory map maintained by the sweeper. Therefore a subsequent restart will remove that pending sweep, if a sub-system isn't still trying to sweep the HTLC. In 0.14.3 we fixed an issue related to sweeps sticking around due to 3rd party anchor spends. If I understand your scenario correctly, then [the fix also applies here](https://github.com/lightningnetwork/lnd/pull/6274) as: we'll detect that sweep and remove any other conflicting transactions (including that pending sweep) we may have.

**Comment by BhaagBoseDK** [comment]
thank you - this explains it.
