### ISSUE TITLE
unable to load TLS credentials: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by miguelkmldev** [lightningnetwork/lnd#6476]
### Background

I'm trying to run LND node on Android but i'm having issues to start up the node.

### Your environment

* version of `lnd` - 0.14.1-beta
* which operating system (`uname -a` on *Nix) - Android API 32
* version of `btcd`, `bitcoind`, or other backend - Neutrino

### Steps to reproduce

I'm using the next command to try to startup the node.

`--bitcoin.active --bitcoin.testnet --bitcoin.node=neutrino --tlsdisableautofill --lnddir=${LND_DIR} --neutrino.connect=faucet.lightning.community --debuglevel=debug`

### Expected behaviour

The node should be start up without problems.

### Actual behaviour

`shutting down because error in main method: unable to load TLS credentials: tls: failed to find any PEM data in certificate input`

**Comment by guggero** [comment]
Did you edit your `tls.cert` file or copy it from somewhere? Sounds like that file is corrupt or empty. You can let `lnd` create a new one by deleting **both** `tls.key` and `tls.cert` and restarting.

**Comment by miguelkmldev** [comment]
@guggero thanks, delete the app from simulator and reinstall.
Done!
