### ISSUE TITLE
[lncli] addinvoice reveales private channels by default

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6484]
### Background

the command lncli addinvoice reveals route hints in case you have private channels by default. Only setting the private flag to false prevents that.

### Your environment

* version of `lncli` : v0.14.3-beta.rc1

### Steps to reproduce

Just create an invoice with `lncli addinvoice 100` and decode paymentrequest with `lncli decodepayreq "your_payment_request"` you should see the routing hints filled with your private channels

### Expected behaviour

Only if I select the flag --private, routing hints should be revealed

### Actual behaviour

Private Routing hints get revealed by default

**Comment by ziggie1984** [comment]
In case this was not decided intentional the bug is in the file:

lnd/cmd/lncli/cmd_invoice.go where the flag private is specified by default to true:

```
cli.BoolTFlag{
			Name: "private",
			Usage: "encode routing hints in the invoice with " +
				"private channels in order to assist the " +
				"payer in reaching you",
		}
```

should be:

`cli.BoolFlag{` (without the T)

**Comment by BhaagBoseDK** [comment]
nice one!

**Comment by ziggie1984** [comment]
In addition to this issue, I was wondering whether its smart to include all private channels into the payment request. I have 3 channels (private) to the same node, and the routing hints include all of them in the routing hints, though its not really necessary bc, lnd can use whatever channel it wants to forward the payment to a peer, hence I would make revealing routing hints more selectable, what are your thoughts ?

**Comment by ziggie1984** [comment]
```
 "route_hints": [
        {
            "hop_hints": [
                {
                    "node_id": "03ceddba52e1dbbc2927defa9c695166a9890937915453aec00c8d89d33ddeea66",
                    "chan_id": "3128110581088256",
                    "fee_base_msat": 1000,
                    "fee_proportional_millionths": 1,
                    "cltv_expiry_delta": 40
                }
            ]
        },
        {
            "hop_hints": [
                {
                    "node_id": "03ceddba52e1dbbc2927defa9c695166a9890937915453aec00c8d89d33ddeea66",
                    "chan_id": "3124812046204928",
                    "fee_base_msat": 1000,
                    "fee_proportional_millionths": 1,
                    "cltv_expiry_delta": 40
                }
            ]
        },
        {
            "hop_hints": [
                {
                    "node_id": "03ceddba52e1dbbc2927defa9c695166a9890937915453aec00c8d89d33ddeea66",
                    "chan_id": "3108319371788288",
                    "fee_base_msat": 1000,
                    "fee_proportional_millionths": 1,
                    "cltv_expiry_delta": 40
                }
            ]
        }
```

All to the same node, which could be improved imo

**Comment by guggero** [comment]
Nice catch! Going to create a fix soon. About the second issue, see https://github.com/lightningnetwork/lnd/pull/4679.
