### ISSUE TITLE
Online API docs are not updated

### ISSUE THREAD

**Issue by thijstriemstra** [lightningnetwork/lnd#649]
#537 fixes a typo in the api docs but the typo is still visible on http://api.lightning.community/#subscribeinvoices. It seems the docs are manually updated or stopped updating? How does the update process work?

**Comment by thijstriemstra** [comment]
ping @Roasbeef

**Comment by MeshCollider** [comment]
@thijstriemstra no I don't think there's anywhere else to file this, I believe @MaxFangX just needs to update it, but it's not an actual issue with lnd so I gave it the upstream tag to make that more clear :)

**Comment by MeshCollider** [comment]
Actually, opening an issue on https://github.com/lightninglabs/lightning-api would probably be more suitable

**Comment by Roasbeef** [comment]
We updated the docs today!

**Comment by Roasbeef** [comment]
@thijstriemstra you fixed a type in `rpcserver.go`. The docs are generated from `lnrpc/rpc.proto`.

**Comment by thijstriemstra** [comment]
Ok, so it's a different file but exact the same typo.
