### ISSUE TITLE
Unconfirmed Wallet Balance 10+ days

### ISSUE THREAD

**Issue by azhodl** [lightningnetwork/lnd#6498]
### Background
I have 11 pending tx's that show zero confirmations for well over a week now. These are associated with Cooperatively closed channels. 

I have completed --reset-wallet-transactions with no change.
I then updated from lnd 0.13.4 to 0.14.2 with no change.
During this time I have restarted LND 3x with no change.

### Your environment

* 0.14.2-beta commit=v0.14.2-beta
* Linux Nuc9 5.11.0-41-generic #45~20.04.1-Ubuntu x86_64
* Neutrino
* any other relevant environment details

### Steps to reproduce

listunspent
`"utxos": [
		{
			"address_type": 0,
			"address": "bc1q602lpk0az5ml7mqyumsl57ye4cvgjrrpak0arn",
			"amount_sat": 971089,
			"pk_script": "0014d3d5f0d9fd1537ff6c04e6e1fa7899ae18890c61",
			"outpoint": "1a2c44d2d564cea668e81c4eed4809e4a2995dd6b687c9cf79e50f1b54d55072:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1q05ursfwmpgmx5esmp2l8sdgx0g98mu4gqq76su",
			"amount_sat": 110048,
			"pk_script": "00147d383825db0a366a661b0abe7835067a0a7df2a8",
			"outpoint": "4c6992a2cde9ea92ff69b5a3c21a7e0619a364a345fd6144258c17647ee4d152:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1qmxfhr4kzda66ssfrrdud7998xqf66u0qrlct4h",
			"amount_sat": 1909829,
			"pk_script": "0014d99371d6c26f75a841231b78df14a73013ad71e0",
			"outpoint": "73f53b5350751033f7db0ee69e99856b30c464ea5842f69098c56f02a67e4e47:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1q0p8j8sp3hxkdd9m7zxlcrccjn6cpgj5ywtypwt",
			"amount_sat": 19999709,
			"pk_script": "0014784f23c031b9acd6977e11bf81e3129eb0144a84",
			"outpoint": "8948630f2ad12575b8f13580dd4650804e724b7109d421d01d294e47dcc141a2:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1qgu5v7ulmwr9q6dqqlf3xe0ycu35ksq4mcxx7fs",
			"amount_sat": 18866838,
			"pk_script": "00144728cf73fb70ca0d3400fa626cbc98e4696802bb",
			"outpoint": "e626c6c018ae831f7513f4957bfb5a8320423f77f288ba54c52c5b9ddd0eb6d4:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1q46uc5vu579r4quuqyp6jscuk47422rca238um8",
			"amount_sat": 4444144,
			"pk_script": "0014aeb98a3394f1475073802075286396afaaa50f1d",
			"outpoint": "0b0c3c73a6987f972cb6c50a0e71be54f3c84f6120c64400dfd05d9a955d005d:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1qpw8hmtmm97stvtuccwym59l2pthsw0z546vxv3",
			"amount_sat": 4056617,
			"pk_script": "00140b8f7daf7b2fa0b62f98c389ba17ea0aef073c54",
			"outpoint": "614e4dfbc9f627bb8d79bf36120bc06fa1366b675b37f71a756e89c1605ec0b1:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1qw2a723sguzaclswr2f9x53yztpfv0fz3awsjpc",
			"amount_sat": 2280215,
			"pk_script": "001472bbe54608e0bb8fc1c3524a6a44825852c7a451",
			"outpoint": "9aa63708d7826d5c3d6b1d7a1de8c6877081c5bd843b45d6749b7bb44d4b90bc:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1q6azqw5s8g2pcqyq0tzsavxvefcl7v2ppqralq5",
			"amount_sat": 11747023,
			"pk_script": "0014d744075207428380100f58a1d619994e3fe62821",
			"outpoint": "7cdea7daa6d86df90cd48bff844daece58087ce62e259f46c4af20eac1c99fe7:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1q9sg02qcejpp0g7hst7njcw52zpluy4yw4262c7",
			"amount_sat": 477,
			"pk_script": "00142c10f503199042f47af05fa72c3a8a107fc2548e",
			"outpoint": "8cea4a806bed339454ec233634991630ffef3db0057d1edd30e265f1d9d8053f:0",
			"confirmations": 0
		},
		{
			"address_type": 0,
			"address": "bc1qpc365ygd72kp3kfxvj4l460ek3zytmgen63k32",
			"amount_sat": 1589255,
			"pk_script": "00140e23aa110df2ac18d92664abfae9f9b44445ed19",
			"outpoint": "d78e9c5b96525125015a7e5724208b6b9fbbdd3557cdc21532dd2359bcf36038:0",
			"confirmations": 0
`
walletbalance
`"total_balance": "86788666",
    "confirmed_balance": "20813422",
    "unconfirmed_balance": "65975244",
    "account_balance": {
        "default": {
            "confirmed_balance": "20813422",
            "unconfirmed_balance": "65975244"
        }
`
One channel closure that I am positive is included in these missing tx's is one with LOOP. I am pretty sure its the 5th tx on the list for 333 sats less than this settled amount.

closedchannels
` "tx_hash": "ad99fed800f02ef8bee0cf41a393b05bca8bd6edf5bd9e0b9c2ffee82d8a72af",
            "amount": "18867171",
            "num_confirmations": 1408,
            "block_hash": "00000000000000000007c9efd42441fcd9d1ca74274a93104e54772949525a71",
            "block_height": 733208,
            "time_stamp": "1650734591",
            "total_fees": "0",
            "dest_addresses": [
                "bc1qgz8lrc0gt8v827f757rfydhyxsl3mnc5dlpw4t",
                "bc1qa5jnh964rlmszexs4mz0jq9lyfqxa3lcjsdrpn"`

Please let me know what I am missing and how to resolve. Thank you!

**Comment by peername** [comment]
Make sure your backend is synched.

You can try to rescan onchain LND transactions with:

`lnd --reset-wallet-transactions`

I had the same problem and all transactions got confirmed after the rescan.

**Comment by Roasbeef** [comment]
AFAICT, none of these are actually in the chain. It could've been a case of starting a co-op close, then one side bails out and either side needs to force close instead. That issue will be fixed in 0.15 (you can restart and resume operations).

**Comment by azhodl** [comment]
Today I performed dropwtxmgr from BTCSUITE based on recommendations by BOS. All the original UTXO's that were unconfirmed are now showing confirmed at the appropriate block height, some 3000 blocks ago and the Sweep transaction appears to have been canceled.

I am closing this issue. Thank you.
