### ISSUE TITLE
Payments attempts on closed channels

### ISSUE THREAD

**Issue by GaryBanderas** [lightningnetwork/lnd#6501]
### Background

I noticed recently that payments are being attempted by some peers on a couple of closed channels, sometimes closed many weeks ago. They seem to have one thing in common: they were doubles. Situations where I had 2 channels with a single peer and I coop closed one (the older). It looks like it also happened on a new channel that I re-opened to a peer very shortly after cooperatively closing an older.

### Your environment

lnd v0.14.2-beta
Umbrel 0.14.15

### Steps to reproduce

1. Have a channel with a peer and route payments on it for some time. 
2. Open a second channel with the same peer.
3. Cooperatively close the first, older channel.

### Expected behaviour

Only the second channel should now be announced to the network and payments should be attempted only on the sole channel left.

### Actual behaviour

The closed channel still cause payment failures indefinitely for some peers as if still seen active.

**Comment by yyforyongyu** [comment]
Could you share some relevant logs?

**Comment by GaryBanderas** [comment]
Im trying to find something to give you. For now, I'm able to monitor this issue only with the software I use (LNDg). In my failed HTLC's, I've isolated 3 problematics closed channels in the same situation. I can see there these defuncts channels id in the "Channel Out id" column and being source of an "Unknown Next Peer" failure.  For one of these peer, I've tried to close the newer channel to see if the failures on the older channel would stop, meaning I have now no channel to this peer. The older channel closed 7 days ago is still source of failed HTLC's, and also today for a new peer that opened a channel to me in the last 24 hours, this defunct channel has been attemped for payment.

**Comment by Roasbeef** [comment]
AFAICT, this just might be sender either not keeping up w/ the graph or not removing channels themselves that are closed. From the report, `lnd` seems to be doing the right thing, but it's some unknown sender (due to the sender privacy the current onion routing give us). The sender crafts the entire route, so if you see forwarding requests going to a closed channel, then it's the sender's fault, and not the forwarding node's.

**Comment by GaryBanderas** [comment]
Yes, this seems to be the case indeed. Thanks for your thoughts @Roasbeef . Closing the issue.
