### ISSUE TITLE
Cryptic error when bitcoind is not running

### ISSUE THREAD

**Issue by Sjors** [lightningnetwork/lnd#6516]
I forgot to restart bitcoind after fixing the config. When trying to start Lnd I see:

```
failed to load config: ValidateConfig: unable to load RPC credentials for bitcoind: unable to extract RPC credentials: unable to find rpcpassword in config, cannot start w/o RPC connection
```

This is very confusing, because I already set `bitcoind.rpccookie` and you can't actually set an RPC user in that case.

Starting bitcoind makes the error go away.

**Comment by ErikEk** [comment]
I guess this happens because lnd can not find the .cookie file. I'll try to improve the error message.
