### ISSUE TITLE
wallet: taproot address creation fails on signet 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6519]
When I create a new (signet) wallet and fund a taproot address, my attempt to open a channel fails with: 

```
[lncli] rpc error: code = Unknown desc = unsupported address type: 51200f5a550....8b
```

If that's intentional, maybe `newaddress` should have a warning not to use the `p2tr` just yet.

Fortunately coin selection seems to prefer non-taproot addresses, so I was able to just create a p2wpkh address, fund that and then open a channel with a sufficiently low balance.

Using master @ 10f7213998936019911c486703b154ca3db85f95

_Originally posted by @Sjors in https://github.com/lightningnetwork/lnd/issues/6263#issuecomment-1121081359_

**Comment by guggero** [comment]
This isn't signet specific, turns out we forgot some small p2tr compatibility fixes in the channel funding process. Added an itest to the PR above.
Thanks for testing, @Sjors!
