### ISSUE TITLE
Add filtering options on REST /v1/payments

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#6532]
### Background
Currently, we do not have any option to filter payments based on time while sending the GET request. To show time based reports in the UI, we have to fetch the entire list of payments and filter them locally. It becomes more expensive for nodes with a large number of payments. The reporting will be faster if we can send the request with `from` and `to` parameters to filter the records through API itself.

### Your environment
version of lnd: 0.14.1-beta
which operating system (uname -a on *Nix): Windows 10
version of btcd, bitcoind, or other backend: 0.21.1

### Expected behaviour
Get a filtered list of payments.

### Actual behaviour
Can either fetch the entire list or paginated list.

**Comment by tvolk131** [comment]
I can take this one!
