### ISSUE TITLE
Channel stuck in pending with funding tx booted from mempool

### ISSUE THREAD

**Issue by dannydeezy** [lightningnetwork/lnd#6550]
I initiated a channel open at 1 sat/byte, then there was a big mempool spike. I believe the transaction was booted from the mempool due to low fees. I tried restarting Lnd but it did not rebroadcast the transaction. I'm hoping there is a way to manually rebroadcast the channel open so I don't have to do the `abandonchannel` command. Any suggestions?

* lnd version 0.14.2-beta commit=v0.14.2-beta
* Bitcoin Core v22.0.0

**Comment by guggero** [comment]
Restarting lnd should re-broadcast the transaction. Can you try that again?
The other thing you can try is to get the TXID (from `lncli pendingchannels`) and check if your `bitcoind` has it (`bitcoin-cli getrawtransaction <txid>`). If it does, you can also manually re-broadcast it.

**Comment by dannydeezy** [comment]
thanks, trying a restart again.
also `bitcoin-cli getrawtransaction <txid>` does not find the tx.

also worth noting, its likely i opened the channel originally with `--min_confs 0`, is it possible I have double spent one of the inputs after the original tx was booted from mempool?

**Comment by guggero** [comment]
It's possible you double spent it. But then you should see something like `removing invalid transaction` in the startup log. If that TXID matches your channel funding transaction and the input that's being spent is actually spent (and confirmed) by another transaction, then you can use the `abandonchannel` command. If there is no confirmed spend of that UTXO then `lnd` should publish it again (or something else went wrong that made the TX invalid).
Anyway, you'll need to take a closer look at the log after startup.
