### ISSUE TITLE
Channel cannot be closed -- lncli restorechanbackup did not return complete data

### ISSUE THREAD

**Issue by ckapilla** [lightningnetwork/lnd#6555]
### Background
While temporarily winding down my RaspPi node, I suffered a complete data loss on my SSD. After restarting my node on a desktop, I am happy to report that I was able to recover funds from my on-chain balance and from 3 of 4 channels using SCB files, but the fourth channel has remained in **pending** / **waiting_close_channels** state for almost two weeks, with **chan_status_flags** of  **ChanStatusRestored**, which I see means that the restored channel "doesn't have all the fields a typical channel will have". This is true, as **lncli pendingchannels** reports **local_balance** of zero and **remote_balance** of zero, which was not the case.

### Your environment
* `lnd`:   v 0.14.3-beta commit=v0.14.3-beta
* OS: ubuntu-desktop 5.13.0-41-generic
* bitcoind:  v 22.0.0

### Steps to reproduce
data dependent, not really reproducible -- 

### Expected behaviour
after running lncli restorechanbackup channel should go into pending close state and eventually be successfully force closed by other end.

### Actual behaviour
The force close by the other end has not been successful, and  running **lncli pendingchannels** returns this incomplete data:

{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "02f765f7dc76002a49990ae9cea7d493c13685b071d5743445f79ec8b5dc52329e",
                "channel_point": "b27f791ad646de132c0c46273540dcba288ab22d252e4c8306a5b32745403a01:0",
                "capacity": "250000",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusRestored"
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "",
                "remote_txid": "",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "0",
                "remote_commit_fee_sat": "0",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}

Here is filtered output from lnd startup that references this channel:

2022-05-13 09:42:06.285 [INF] CHBU: Starting chanbackup.SubSwapper
2022-05-13 09:42:06.308 [WRN] CHBU: Replacing disk backup for ChannelPoint(b59e6298704f1f4277e4b2ef2ce984089f4819feedb8965fa1c7903cb9c21265:0) w/ newer version
2022-05-13 09:42:06.308 [WRN] CHBU: Replacing disk backup for ChannelPoint(b27f791ad646de132c0c46273540dcba288ab22d252e4c8306a5b32745403a01:0) w/ newer version
2022-05-13 09:42:06.310 [INF] CHBU: Updating backup file at /home/chris/.lnd/data/chain/bitcoin/mainnet/channel.backup

**Comment by alexbosworth** [comment]
did you try connecting to `02f765f7dc76002a49990ae9cea7d493c13685b071d5743445f79ec8b5dc52329e`

**Comment by ckapilla** [comment]
> did you try connecting to `02f765f7dc76002a49990ae9cea7d493c13685b071d5743445f79ec8b5dc52329e`

I've been in contact with the owner -- there were actually two channels between our two nodes, one opened by me, and one opened by him. He did a force close on both, and one went through successfully, but this one did not. Are there known reasons that would cause a result like this with incomplete data?

**Comment by alexbosworth** [comment]
The peer had a failure force closing but they did not lose data? What was the failure?

**Comment by ckapilla** [comment]
Sorry, "failure" was a poor choice of words, I just meant that the result of the close was the restored channel did not have complete data, as shown above. So one channel closed as expected with complete data and is visible via "lnci closedchannels", and this one did not., it is stuck in pending / waiting_close as shown above

**Comment by alexbosworth** [comment]
based on the on-chain data it does not appear that the stuck channel was force closed by the other side

**Comment by ckapilla** [comment]
thanks I appreciate your looking into this!  I guess my basic question is, since "lncli pendingchannels" shows incomplete data, is there hope that this will eventually find its way out of "waiting_close_channels", and is there anything I can do to help that along other than wait some more?

**Comment by alexbosworth** [comment]
since you have communication with the peer i would ask what they see on their side of things

**Comment by ckapilla** [comment]
alas he has not been terribly communicative about that, but I will try again...

**Comment by alexbosworth** [comment]
you could also get all your funds out and try the recovery from scratch again, looking in the logs for what happens when you initiate recovery with this peer

**Comment by ckapilla** [comment]
if I do this command:
lncli restorechanbackup --single_backup  "8ce2c26de..." 
I get this in the log

> CHBU: Restoring ChannelPoint(b27f791ad646de132c0c46273540dcba288ab22d252e4c8306a5b32745403a01:0) to disk: 
> 2022-05-20 12:02:24.809 [INF] LTND: SCB Recovery: created channel shell for ChannelPoint(b27f791ad646de132c0c46273540dcba288ab22d252e4c8306a5b32745403a01:0), chan_type=2
> 2022-05-20 12:02:24.809 [INF] LTND: Inserting 1 SCB channel shells into DB

but the outuput of lncli pending channels is unchanged.

**Comment by ckapilla** [comment]
I have more information from the other end. He is being very helpful, but doesn't have time for much right this moment. His LND is showing a WAIT_CLOSING state with a limbo balance and local and remote balances as expected. He then verified that the closing transaction LND reports somehow did not make it onto his bitcoin node, as shown here:
![LND](https://user-images.githubusercontent.com/451875/169650322-81f5b2e2-85c0-40aa-9f0d-85254b67473d.jpg)
 Would the best thing be for him to just try the force close again?

**Comment by alexbosworth** [comment]
He could try restarting

**Comment by ckapilla** [comment]
good point -- that has certainly worked for me a number of times during this process.
