### ISSUE TITLE
Install guide refers to upgrade process but following it breaks lnd

### ISSUE THREAD

**Issue by bretton** [lightningnetwork/lnd#657]
The install guide at https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md includes a paragraph on updating lnd.

However the changes between commits are so significant in recent days that attempting to upgrade introduces errors when running lnd. Reverting doesn't work either. Have to start from scratch.

Suggestion: add a note to the updating section that updates are not working 100% yet, and it's not suggested to follow the process at this stage. Better to close channels, wipe and start from scratch.

**Comment by dabura667** [comment]
NACK. During the alpha phase of software, "upgrade" does not need to guarantee nothing breaks.

I think it's fine the way it is.

**Comment by bretton** [comment]
I don't think people care what stage of the development process a project is in, nearly as much as they do about having documentation which is useful and accurate. If upgrades are not reliable, it shouldn't be part of the install guide, or more clearly specified that things may break.

**Comment by dabura667** [comment]
> it shouldn't be part of the install guide

It definitely should.

Not every dev is familiar with golang and so explaining how to switch from one commit to another and compile that commit is necessary.

Every developer is, however, familiar with git.

Use git reflog to checkout previously built commits and rebuild.

**Comment by Roasbeef** [comment]
We haven't yet done a stable release, so users that are closely following the current development can be on either IRC or our slack in order to determine if a change may be breaking. Good news is that we're nearly done with breaking changes!

As @dabura667 said, you can use `git reflog` to find your prior commit, close out your channels, then roll forward and start from there.
