### ISSUE TITLE
Sweep transaction stuck after switching backends

### ISSUE THREAD

**Issue by WesVleuten** [lightningnetwork/lnd#6572]
### Background

There is a unspendable transaction stuck as unconfirmed labeled as `0:sweep`, the transaction hash does not appear on the blockchain. Decoding the transaction reveals it's trying to spend a previously spent utxo.

The issue first appeared while I was running v0.14.2, I found #6471 as a similar issue with PR #6274 resolving it, so I upgraded LND in hopes that would resolve my issue too. It did not.

Restarting LND didn't resolve the issue.

A restart using `--reset-wallet-transactions` didn't resolve the issue.

Even though it's pending, and labeled as a sweep, it's not listed in `lncli wallet pendingsweeps`

The transaction id is listed in `lncli wallet listsweeps`

The utxo it's trying to spend was spent over 10k blocks ago.

### Your environment

LND version: `0.14.3-beta commit=v0.14.3-beta`
OS: `Linux 5.15.0-1006-raspi #6-Ubuntu SMP PREEMPT Mon Apr 25 12:50:48 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
Neutrino backend

### Steps to reproduce

I am not sure how to reproduce the issue, but it seems to have appeared after I switched from bitcoind backend to neutrino.

### Expected behaviour

Unspendable transaction to be discarded.

### Actual behaviour

Transaction stuck as unconfirmed, with no way I can tell for it to either delete it or forget about it.

**Comment by alexbosworth** [comment]
Switching from bitcoind to neutrino is not supported, did you try switching back?

**Comment by WesVleuten** [comment]
Switching back resolved this issue, thank you!
