### ISSUE TITLE
Always "out of memory" while Initializing btcd backed fee estimator

### ISSUE THREAD

**Issue by leo-ho** [lightningnetwork/lnd#658]
My lightning node was created and synced for a few days and suddenly crashed. From then on every time I launch lnd it exits with "out of memory" while Initializing btcd backed fee estimator. I tried to reboot the machine but the same error persisted. 

I then tried to remove wallet.db and recreated the wallet. It passed previous failure point and started to sync blocks. However, after 632104 blocks the same exact error happened again.  

I'm running lnd + btcd(testnet) on Raspberry Pi model 3B. The memory itself looks fine as it did once synced up and running for a few days. Further information please find the attached files.

[systeminfo.txt](https://github.com/lightningnetwork/lnd/files/1656118/systeminfo.txt)

[lnd.log](https://github.com/lightningnetwork/lnd/files/1656119/lnd.log)

[runtime_err.txt](https://github.com/lightningnetwork/lnd/files/1656122/runtime_err.txt)

[lnd.conf.txt](https://github.com/lightningnetwork/lnd/files/1656123/lnd.conf.txt)

**Comment by Roasbeef** [comment]
Running _both_ on a single rasp-pi may be a bit constrained memory wise. `btcd` itself loads the entire chain into memory (the headers) and also may see high-ish (may exceed 1GB) memory usage in isolation itself. On a device like a rasp-pi, I'd recommend running in neutrino mode.

**Comment by leo-ho** [comment]
Thanks for the suggestion. Considering the fact that this issue always happens no matter how much memory was used while lnd is launched (I tried many different scenarios, including kill other processes  to keep memory usage as low as possible), it looks something worth looked into instead of simply a memory constrain issue -- although might not be an urgent one.

**Comment by Roasbeef** [comment]
Hmm yeah, in my experience lnd's memory usage is very low. If you're doing an IBD, then `btcd` itself can start to consume upwards of 1GB of memory. You may see success in adding some swap to the device (or just running with neutrino).

**Comment by leo-ho** [comment]
Actually the swap file was enabled and still mostly available. This is what I provided in the attachment "systeminfo.txt" : 
free:
              total        used        free      shared  buff/cache   available
Mem:         994240      654268      156848        3940      183124      286392
Swap:       1023996      313864      **710132**

Yet it still  crashed...

**Comment by Roasbeef** [comment]
This is still running _both_ `btcd` and `lnd` on the pi? 1GB may not be enough for both of them. 

The runtime error there showed that it was unable to allocate all the memory needed to actually compute scrypt to decrypt the wallet.

**Comment by aakselrod** [comment]
Any chance you could run it with `--debuglevel=trace` and send back the log? That might help us track down where exactly it's crashing.

**Comment by aakselrod** [comment]
Ahh, yeah, decrypting the wallet could do it.

**Comment by leo-ho** [comment]
As you said, lnd itself doesn't seem to consume much memory (3% or so). I dug into the code a bit and realized the error was in btcsuite/golangcrypto/scrypt/scrypt.go:235, where 
`v := make([]uint32, 32*N*r)`
Although I don't understand why swap file is not utilized for facilitating required memory...

**Comment by Roasbeef** [comment]
What version of Go are you running?

**Comment by leo-ho** [comment]
Just for your information. I recompiled lnd with go1.9.3 and this issue was gone.
