### ISSUE TITLE
Local inactive channel does not show up as disabled in "getchaninfo"/graph

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6582]
### Background

One of my channels is inactive, as shown in `lncli listchannels`. However, using `lncli getchaninfo` both directions of the channel are shown as enabled (disabled is false). As my code currently only relies on `getchaninfo` (or, rather, the information obtained with "describe graph"), the lack of information causes unnecessary failures.

I'd like to see as much information as possible in the graph (describe graph, getchaninfo) so that tools can make use of this information without jumping through hoops to find the information elsewhere.

### Your environment

* version of `lnd`: 0.15.0-beta.rc3
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Make active channel inactive (drop connection to peer?). Query lncli getchaninfo for this channel.

### Expected behaviour

Channel is shown as disabled (from our side).

### Actual behaviour

It is shown as enabled (not disabled).

**Comment by Roasbeef** [comment]
Channels aren't disabled as soon as a peer goes offline: https://github.com/lightningnetwork/lnd/blob/master/netann/chan_status_manager.go#L80-L83. This is to prevent spammy updates from a peer connecting and disconnecting rapidly. It may take up to 20 minutes for a channel to be disabled.

**Comment by saubyk** [comment]
Hi @C-Otto closing this issue as there's no objection to @Roasbeef 's comment. Feel free to reopen if not satisfied or if you have more to add. Thanks

**Comment by C-Otto** [comment]
I understand that active/inactive and enabled/disabled are not the same. I don't need to spam the network, but I need a way to see information about an individual channel. As this is related to the similar question of retrieving a single channel's balance, I added a comment to the corresponding (open) issue. I'm OK with closing this issue.
