### ISSUE TITLE
channel remains in closing state for a month already

### ISSUE THREAD

**Issue by raimiuxxx** [lightningnetwork/lnd#6587]
### Background

I accidentally opened a second channel with node "magnetron". It was opened successfully. But then when I realized I do not need it I closed it (not using force close). Then it got into closing state and remains there forever. Now a month has passed and it is still closing. I contacted the owner of "magnetron" node, which is Muun wallet, but they said there is nothing they can do.

P.S. I never tried closign my first channel with magnetron and it continues running properly.

### Your environment

* version of `lnd` v0.14.2-beta
* which operating system: Umbrel Version 0.4.18
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core v22.0.0
* any other relevant environment details

### Steps to reproduce

[Channel Id: 806304862080532481]
Short Channel Id 733330x1275x1
Channel Point 474ea6b61803a59ce655039b28f8a57fc8ddd4f34edb87b8d75e69c43b547ecc:1
Capacity 0.04000000
First Seen Sunday, April 24, 2022
Transaction ID: 474ea6b61803a59ce655039b28f8a57fc8ddd4f34edb87b8d75e69c43b547ecc
My node: 0325b2bcfb148df2175061319f6d3041356859b948efa0bcae35d2e2245974e730@kcxibzf5qskgvbz53r6w4gxqsfdp646s3wi75r2ght5n7ueeuxh4xdad.onion:9735
Peer node: 038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6@evbw26fxcjyclkqjjbjovtfy7i36ojrs6c2vws3f5og7aokn2pok4kyd.onion:9735

### Expected behaviour

Can somebody help me to close this channel?

### Actual behaviour

Channel is in closing state forever keeping my funds frozen.

**Comment by ziggie1984** [comment]
Just check with `lncli pendingchannels` if the channel is in the waiting close just force close it with:

`lncli closechannel --force --output_index 474ea6b61803a59ce655039b28f8a57fc8ddd4f34edb87b8d75e69c43b547ecc --chan_point 1`

and see whether this resolves your issue

**Comment by raimiuxxx** [comment]
This worked, problem solved. Thank you very much!
