### ISSUE TITLE
Closing channel but stuck with commitment type ANCHOR

### ISSUE THREAD

**Issue by zey-2** [lightningnetwork/lnd#6591]
### Background

Requested a channel close via LNDg with 1 sat/vb fee. Channel closing is now stuck in limbo.

{
    "total_limbo_balance": "943894",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "029fe040ab2f303ebb74af21304da35b826bb47305b42dbfbd477fa14d2f88784e",
                "channel_point": "6a5be655dd238832df2e4d3d95c1b0be16a6870c59988f5dc13da3718103cfe3:0",
                "capacity": "1000000",
                "local_balance": "943894",
                "remote_balance": "52635",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator"
            },
            "limbo_balance": "943894",
            "commitments": {
                "local_txid": "fb4844101f36f32878869e934ca0b81d41fdc238766e84b4b7070350e2e7c113",
                "remote_txid": "8bc2d4ac7d59cbc634b299bc6e0a7e51b80911cdb1ad5e9573be49bb8b2bc038",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2810",
                "remote_commit_fee_sat": "2810",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}
### Your environment

Umbrel v0.4.18

### Action taken

I guess force close may be the only way out, hence I tried the following command. However, I didn't see any response. May I know if this is correct?
 ~/umbrel/bin/lncli closechannel --force fb4844101f36f32878869e934ca0b81d41fdc238766e84b4b7070350e2e7c113 0

### Also see
https://github.com/lightningnetwork/lnd/issues/6453

**Comment by zey-2** [comment]
Tried this and the channel is closed. Expensive move. 😭
~/umbrel/bin/lncli closechannel --force 6a5be655dd238832df2e4d3d95c1b0be16a6870c59988f5dc13da3718103cfe3

**Comment by Swissnode** [comment]
Does it matter which peer requests the force close? Should it be the same peer that attempted to close the channel?

**Comment by zey-2** [comment]
Thanks for commenting. As it happened quite a while back, I can't remember what happened at that time. 😅
