### ISSUE TITLE
[Feature] Proxy support

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#6595]
I would like to run LND behind a socks proxy, but there seems no option for that in lnd.conf.

When running in Tor-mode it already connects to such a proxy, so it seems adding support for a normal one shouldn't be difficult.

**Comment by guggero** [comment]
I know this issue was first, but since https://github.com/lightningnetwork/lnd/issues/6845 has slightly more context, I'm going to close this one in favor of the other one.
