### ISSUE TITLE
Peers prefer Tor?

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#6606]
Since recently my node advertises a clearnet IP in addition to the Tor address. 

But I noticed that none of my inbound peers (100+) connect to this IP, they all use Tor even though they are not Tor-only nodes. I'm trying to understand why this is.

  - Do they always re-use the same address they used during the initial channel creation, as that would be Tor?
  - Do they notice that my outgoing connections to them are still via Tor, and is that why they prefer the same protocol when making an inbound connection to me?
  - Is there any other reason why they would prefer Tor over clearnet?

The strange thing is, that my own outbound connections don't seem to have this behaviour. All my outgoing connections are to clearnet IP's (over Tor) where possible. Even to nodes I initially connected to their Tor address when creating the channel. So it seems LND indeed has a preference for IP over Tor, so that makes it even stranger that my peers behave differently.

**Comment by guggero** [comment]
Are you running with `--tor.skip-proxy-for-clearnet-targets`? Most likely you are and all your peers are not.
