### ISSUE TITLE
rpccookie does not work when .bitcoin directory is not accessable

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#6613]
### Background

[bitcoind.rpccookie](https://github.com/lightningnetwork/lnd/blob/7106ea59db9ade78d65bb46605f94637900c0e3f/lncfg/bitcoind.go#L10) parameter is used to point to a file that bitcoind generates for letting clients have a [more secure](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md) way to authenticate with it.

bitcoind is configurable such file can be written to a custom location. This is useful for limiting access to only one or two accounts on the system that need the cookie and don't need to read the rest of `.bitcoin` directory.

Yet, looks like LND cannot be configured to access a particular `bitcoind.zmqpubrawblock`, `bitcoind.zmqpubrawtx` with a cookie. It only works with the cookie file if LND is configured to access the whole `.bitcoin` directory, from where it will read bitcoin's config for `zmqpubrawblock` and `zmqpubrawtx`: 
```
failed to load config: ValidateConfig: unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpc
pass, bitcoind.zmqpubrawblock, bitcoind.zmqpubrawtx
```
Why can't I just configure  `bitcoind.zmqpubrawblock` and `bitcoind.zmqpubrawtx` like I did with user+password auth?

### Your environment

* `lnd version 0.15.0-beta.rc3 commit=tor/v1.0.1-6-g199f9d113`
* `Linux bl5 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux`
* `Bitcoin Core version v23.0`

### Steps to reproduce

1. Run lnd and bitcoind on separate OS accounts.
2. Try to configure bitcoind to write it's cookie file to a particular directory and LND to read just that cookie file (e.g. by setting up group permissions)
3. Deny LND account from read access to `.bitcoin` directory.

### Expected behaviour

LND  should let me configure `bitcoind.zmqpubrawblock` and `bitcoind.zmqpubrawtx` 

without the need for LND to access `bitcoind.dir`

**Comment by bitromortac** [comment]
reproduced, working on a fix

**Comment by guggero** [comment]
If you say "from the same bitcoin.conf", you mean a conf that has both the mainnet and signet sections set and you start both daemons with different flags?
If that's the case, where are the two different `.cookie` files stored? Are they in distinct directories? Sounds like a specific signet (or maybe any non-mainnet network) problem, perhaps we don't took in the correct folder. Might be worth opening a new issue.
