### ISSUE TITLE
[Feature] Add reason to force closes

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#6615]
Every few weeks I encounter a local force close on one of my channels, and I really wonder why.

When running `lncli closedchannels` I get something like:

```
         "close_type": "LOCAL_FORCE_CLOSE",
         "close_initiator": "INITIATOR_LOCAL",
```

Which isn't helpful at all. The only other option would be to browse through the logfiles for a message somewhere, but that is hard to do, especially if it happened long ago.

Why would we not add a third field, something like:

         "close_reason": "<description>",

so that it is always possible to track down what triggered it?

**Comment by Roasbeef** [comment]
^ yep
