### ISSUE TITLE
[Feature] Implement persistent height hints

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#6618]
When the requirement for `txindex` was dropped, it said in the release notes:

`However, for performance reasons until the persistent height hints are re-activated, we recommend running with an active transaction index for your full node which backs lnd. `

So basically LND runs slower without `txindex` because the height hints are missing. My request is to implement this mechanism so that there is less of a performance hit when running without index.

**Comment by Roasbeef** [comment]
This is [already implemented](https://github.com/lightningnetwork/lnd/blob/28ea2736a04566b06c38533e5e48e1b8d185a49b/chainntnfs/height_hint_cache.go#L96). A `txindex` is still faster though, as if we're offline, we need to walk forward in the chain to re-build those height hints.
