### ISSUE TITLE
Missing documentation for postgresql database structure

### ISSUE THREAD

**Issue by GordianLN** [lightningnetwork/lnd#6619]
### Background

Postgresql backend would allow for very fast data access, by directly querying the database with your coding language of choice and a DB driver, instead of using lnd as intermediary with gRPC. This will need previous knowledge of things to look for in the database.
I did open the DB with an explorer, and the contents are... overwhelming to say the least.
I personally have no advanced knowledge but I know my way around MySQL/MariaDB and SQLite, yet the (binary?) data stored in postgresql makes no sense at all to me.
I was expecting to find cleartext and tidy information about the state of life, the universe and everything, but 42 wasn't even in there among the scary amount of numbers I saw.
I honestly thought I'd find searchable output like the one `lncli getchaninfo` gives, for example, just waiting to be fetched with a query like `SELECT * FROM channeldb WHERE chanid=nnnnnnnnnn`.

### Your environment

* version of `lnd` 0.14.3
* which operating system (`uname -a` on *Nix) latest raspios
* version of `btcd`, `bitcoind`, or other backend 22
* any other relevant environment details /

### Steps to reproduce

Open postgresql with something like adminer

### Expected behaviour

Find human-readable data

### Actual behaviour

Be violently hit with all the cold indifference of binary data

**Comment by guggero** [comment]
See https://github.com/lightningnetwork/lnd/issues/6288 for more context.

**Comment by GordianLN** [comment]
Actually, I'd now like to see SQLite support with clearly readable structure, just like CLN, and postgres>sqlite migration, but I guess I'm OT in my own issue 😅

**Comment by ziggie1984** [comment]
Closing with https://github.com/lightningnetwork/lnd/pull/7442
