### ISSUE TITLE
Connecting to faucet fails with non-descript error message

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#662]
Using this tutorial (http://lightning.community/lnd/faucet/2017/01/19/lightning-network-faucet/), the connect command command:

`lncli connect 02f1da524a70afd8de6019e2367b47d8d41a623aa3594f55d0785fe1b047c853bc@faucet.lightning.community:9735`

fails with the following, unhelpful error message:

`[lncli] rpc error: code = OutOfRange desc = EOF`

Note that my node is already connected to two other peers:
02c39955c1579afe4824dc0ef4493fdf7f3660b158cf6d367d8570b9f19683afb5
02f6d66509f7ef98d9470ab5dc3998f8785112c545f86e50b9811772a9166f99dc

The first of these is the pubkey that is returned by the faucet (https://faucet.lightning.community/), as opposed to the one listed above that is hard-coded in the tutorial.

I'm running version 0.3. As far as I can tell everything else about my node is working correctly.

Can this error message be improved? Because it isn't useful I'm unsure if there is some actual functionality bug here.

**Comment by Roasbeef** [comment]
The faucet's public key rotates from time to time. The current key is: 
```
02c39955c1579afe4824dc0ef4493fdf7f3660b158cf6d367d8570b9f19683afb5
```

The error message itself can't _directly_ be improved as dude to our p2p crypto layer, if someone connects and doesn't actually know our _real_ identity, then we immediately disconnect.

**Comment by thijstriemstra** [comment]
Where does one obtain this 'current key'?

**Comment by merehap** [comment]
Roasbeef: The error message couldn't have text like "Expired/unused/unknown public key" appended to it in some way or something similar? I'd imagine that people will run into the rotating pubkey issue from time to time and would like some guidance when it happens.

thijstriemstra: If you go directly to the faucet (https://faucet.lightning.community/) it will give you an up-to-date pubkey/address. It is just the one that is hard-coded in the tutorial that will be forever out of date.

**Comment by merehap** [comment]
Note that I can make a PR for the change, if you can point me in the right direction. If there is a larger project needed for making error messaging better in general I'd be happy to look into it, too.

**Comment by merehap** [comment]
Note that I get the exact same error message for some pubkeys that I know are active. There should be some way to distinguish the error cases for the user (as far as I understand).

`sean@dmt:~$ lncli connect 03b4db738647df61fac756a0713d238e892e4ae4a5de651c7c0acad2a76b1447e1@197.155.6.37:9735`

`[lncli] rpc error: code = OutOfRange desc = EOF`

**Comment by Roasbeef** [comment]
There's no way to distinguish the two. It's the result of the remote peer either no listening, or simply killing the TCP connection immediately. 

> Note that I get the exact same error message for some pubkeys that I know are active.
You'll only get that error if they're actually not listening, or have changed public keys.

**Comment by merehap** [comment]
Sorry for re-opening.

My claim is that there should be a better error message than just "EOF". "EOF" tells the user nothing, and is an code-internal detail that shouldn't be exposed to the user. At the very least, it would be possible to modify openChannel in commands.go to have something like

```
stream, err := client.OpenChannel(ctxb, req)
if err == io.EOF {
    return fmt.Errorf("failed to establish channel due to remote host rejecting it")
}

if err != nil {
    return err
}
```



I understand that the different error cases are indistinguishable. My objective is to improve the user experience through better messaging, even if that means we have to introduce a generic error message. I'm happy to prepare a PR for this if you'd like. Tell me if it is too low priority though.

**Comment by merehap** [comment]
@Roasbeef ^ I couldn't reopen, but if you could still look at my latest comment, that would be great.

**Comment by Roasbeef** [comment]
Thanks for that example, I totally agree on that front. How about we make a new issue more directly targeting more descriptive errors on the command line for `openchannel`, `connect` and any other cli messages?
