### ISSUE TITLE
Commandline parameters override config

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#6637]
It is normal that the commandline parameters override the values in the config file. Bitcoin also has this behaviour.

But for parameters were you can have multiple, like `tlsextraip` and `tlsextradomain` it would make sense to accept them from both places, and it does not happen now.

This makes it impossible to add an extra IP on Umbrel in the config file, because Umbrel already specifies one IP through the commandline parameters, so the ones in the config file get ignored.

**Comment by guggero** [comment]
While I see why it would be useful in your case, I think it would be confusing in general if the override/precedence behavior is different for some of the values. And that new behavior wouldn't allow you to overwrite multi-value config file parameters anymore from the CLI.

Maybe this is something that should be solved in Umbrel instead? Add the ability to customize the values in the config file? Or, can't you just re-create the existing config file value in the custom CLI flags you set? I assume there's a custom value in there, but maybe you have access to that environment value in the CLI as well?
