### ISSUE TITLE
`ChanStatusBorked`, closure with ZFR, "ghost" balance sent to unknown addresses

### ISSUE THREAD

**Issue by GordianLN** [lightningnetwork/lnd#6639]
### Background

Channel with ZFR that out of the blue closes, bos bot just reports  "closing channel", not a force closure.
I saw no unconfirmed txns in my cold wallet, out of which I took an address to attach to the channel open I initiated.
Onchain, I see this tx corresponding to the closure:
cda9474e4cabc591b5a79503784b039d800729a19b07cd0ea982acde22c182ce
The output addresses are not known to me.
This is the relevant output from `lncli pendingchannels`
```
   "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5",
                "channel_point": "58839114c2a2d8011126547f03f2ea6395242bef8498353c21c1bd36ec53f69b:0",
                "capacity": "2100000",
                "local_balance": "585085",
                "remote_balance": "1362691",
                "local_chan_reserve_sat": "21000",
                "remote_chan_reserve_sat": "21000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "1",
                "chan_status_flags": "ChanStatusBorked"
            },
            "limbo_balance": "585085",
            "commitments": {
                "local_txid": "4ecefe0f6ba5214198793dedd12fcef71481bf7c1fd243dbf0daf444eebc0633",
                "remote_txid": "cda9474e4cabc591b5a79503784b039d800729a19b07cd0ea982acde22c182ce",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2145",
                "remote_commit_fee_sat": "2145",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
```

From the records saved by lndg about the channel, local I had 585497 + 1734 commit, which summed to the 1512769 lndg had saved as remove balance is exactly 2100000.

Grepping ERR from logs I see
```
[ERR] LNWL: ChannelPoint(58839114c2a2d8011126547f03f2ea6395242bef8498353c21c1bd36ec53f69b:0): sync failed: remote's next commit height is 37795, while we believe it is 37793!
[ERR] HSWC: ChannelLink(58839114c2a2d8011126547f03f2ea6395242bef8498353c21c1bd36ec53f69b:0): failing link: unable to synchronize channel states: unable to sync commit chains with error: unable to resume channel, recovery required
```

I know at this point this must have been a FC which my lnd didn't detect as such, will I recover the funds automatically via sweep or do I need to do anything special?

### Your environment

* version of `lnd` 0.14.3
* which operating system (`uname -a` on *Nix) raspberry bullseye
* version of `btcd`, `bitcoind`, or other backend 0.22
* any other relevant environment details

### Steps to reproduce

Nothing special

### Expected behaviour

Don't even know what to expect

### Actual behaviour

Closure, funds disappeared

**Comment by alexbosworth** [comment]
looks like the remote side is force closing

**Comment by GordianLN** [comment]
Yup, it indeed was a force closure in the end, telegram bot notified about it when tx had confs, and upon further examination of logs I noticed
```
[ERR] LNWL: ChannelPoint(58839114c2a2d8011126547f03f2ea6395242bef8498353c21c1bd36ec53f69b:0): sync failed: remote's next commit height is 37795, while we believe it is 37793!
```
and there were several disconnections and reconnections going on from before until after the FC.
It's like a pending HTLC got stuck there while I was offline for ZFR, and ZFR's commit height was increased while mine wasn't, and as soon as I came back online, surprise!

**Comment by Crypt-iQ** [comment]
Did you have a power loss or unclean shutdown ?

**Comment by Crypt-iQ** [comment]
Can you provide logs for that channel leading up to (several minutes before) the bad channelreestablish/sync messages? And any error logs if you have them. What type of storage device are you using?

**Comment by GordianLN** [comment]
On second examination, this could be related to:
https://github.com/lightningnetwork/lnd/issues/6593

Thinking about the issue, it looks like remote node somehow advanced in channel state progression while my node was disconnected, and stayed on the previous channel state; upon reconnection, the mismatch was evident, and ZFR FC'ed the channel.

**Comment by Crypt-iQ** [comment]
Did you have `unable to resolve fwd pkgs: bucket not found` in your logs?

**Comment by GordianLN** [comment]
grepping log for `bucket` returns nothing, actually.
Let me redact the logs and will attach them here

To help you grep, remote node pubkey is `038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5` and channel point is `58839114c2a2d8011126547f03f2ea6395242bef8498353c21c1bd36ec53f69b:0`

[lnd.log](https://github.com/lightningnetwork/lnd/files/8922029/lnd.log)

**Comment by GordianLN** [comment]
Btw, lnd is using postgresql backend on a raid1 over 2 kingstone A400 ssd's

**Comment by Crypt-iQ** [comment]
Thank you I will look into this

**Comment by Crypt-iQ** [comment]
It seems like you've claimed the `to_remote` output on the remote's commitment tx. The unclaimed output is either an offered HTLC or received HTLC. I don't have enough information here to help recover it, maybe you could contact ZFR to get the relevant script details to claim it.

**Comment by GordianLN** [comment]
> It seems like you've claimed the `to_remote` output on the remote's commitment tx. The unclaimed output is either an offered HTLC or received HTLC. I don't have enough information here to help recover it, maybe you could contact ZFR to get the relevant script details to claim it.

I'm afraid I don't know what this is about though, like, at all... does it mean there should be some funds that are expected to be mine, but they got lost somehow?

**Comment by dstadulis** [comment]
@GordianLN Lightning Labs is almost finished assessing the issue.  Wanted to update you

**Comment by zerofeerouting** [comment]
This is what my node knew about the channel

```
{
    "timestamp": "2022-06-13T09:28:32.992Z",
    "old_state": "CHANNELD_NORMAL",
    "new_state": "AWAITING_UNILATERAL",
    "cause": "protocol",
    "message": "channeld: received ERROR error channel 9bf653ec36bdc1213c359884ef2b249563eaf2037f54261101d8a2c214918358: unable to resume channel, recovery required"
}
```

It looks like my peer (@GordianLN) signed off on two channel states but "forgot" about them, resulting in them asking me to force-close the channel by sending an `error` message.

**Comment by Crypt-iQ** [comment]
@GordianLN you havent lost any funds

**Comment by GordianLN** [comment]
> @GordianLN you havent lost any funds

Sorry for late reply... anyway you could say I lost a few thousands of sat in force close expenses, that at my node's current level eat up a serious amount of the positive balance of my node's life

**Comment by Roasbeef** [comment]
This issue has been resolved! Thanks for such a great bug report 🙏🏾
