### ISSUE TITLE
/v1/peers POST not working (syntax error)

### ISSUE THREAD

**Issue by bc31164b-cfd5-4a63-8144-875100622b2d** [lightningnetwork/lnd#6643]
### Background

When i try making a POST to /v1/peers to connect, it returns a syntax error.

### Your environment

* version of `lnd`: 0.14.3-beta
* which operating system: not sure / voltage v0.3.12
* version of `btcd`, `bitcoind`, or other backend: not sure

### Steps to reproduce

```python
import base64, codecs, json, requests

url = "https://<NODE_IP>:8080/v1/peers"
cert_path = "tls.cert"
macaroon = codecs.encode(open("admin.macaroon", "rb").read(), "hex")
headers = {"Grpc-Metadata-macaroon": macaroon}
data = {
    "addr": "0342a8a3ede9568778ea80a369901b680103e7ce06c0773696bf6fcbb805476aa1@217.173.236.78:17735",
    "perm": False,
    "timeout": "30",
}
# don't use cert for voltage node
r = requests.post(url, headers=headers, data=json.dumps(data))  # verify=cert_path
print(r.json())
```

### Expected behaviour

Connects to the node.

### Actual behaviour

```
{'code': 3, 'message': 'proto: syntax error (line 1:10): unexpected token "0342a8a3ede9568778ea80a369901b680103e7ce06c0773696bf6fcbb805476aa1"', 'details': []}
```

**Comment by guggero** [comment]
That's because `addr` needs to be an object too, not a string: https://api.lightning.community/#lnrpclightningaddress

**Comment by guggero** [comment]
Didn't see that comment, fixed in https://github.com/lightningnetwork/lnd/pull/6644.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
Super thanks.
