### ISSUE TITLE
Using REST /v2/router/send endpoint results in unexpected EOF'

### ISSUE THREAD

**Issue by razorman8669** [lightningnetwork/lnd#6645]
### Background

we've noticed a failure rate of about 60% of our sends (using REST api endpoint `/v2/router/send`)  from our testnet LND node.  it's an obscure error with a response of 
```{ code: 3, message: 'unexpected EOF', details: [] }```

We originally thought it was due to running the latest `v0.15.0-beta.rc6` but have since setup 2 more clean nodes running `v0.14.3` on different machines and are still getting this error regularly.  it results in the send to fail completely most of the time.

### Your environment

* version of `lnd`
`v0.15.0-beta.rc6` and `v0.14.3-beta`
* which operating system (`uname -a` on *Nix)
`Linux lnd-testnet 5.4.0-1078-gcp #84~18.04.1-Ubuntu SMP Fri Jun 3 13:37:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

* version of `btcd`, `bitcoind`, or other backend
btcd - v0.22.0-beta

* any other relevant environment details
Running LND in docker alpine using Dockerfile from LND
executing the REST call via Nodejs v16 using vanilla `https` library.

### Steps to reproduce
setup a testnet LND node.
call `/v2/router/send` REST endpoint. we use NodeJS to talk to LND.  here's an attempt to give you a really stripped down version of how we query:

```
    options =  {
      ca: "<Buffer 2d 2d ... 768 more bytes>",
      host: '211.211.211.211',
      port: 8082,
      headers: {
        'Grpc-Metadata-macaroon': '02011...3334432'
      },
      path: '/v2/router/send',
      method: 'POST',
      body: {
        payment_request: 'lntb1p32j7dzpp5rsu...myeh9lagqu382yy',
        fee_limit_sat: 2,
        timeout_seconds: 45,
        amt: 334
      }
    }

    const req = https.request(options, (res) => {
      const body = [];
      res.on('data', (chunk) => {
        body.push(chunk);
      });
      res.on('end', () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          throw new Error(`Request Error: ${res.statusCode}: ${res.statusMessage}`));
        }

        return Buffer.concat(body).toString(); // will contain '{ code: 3, message: 'unexpected EOF', details: [] }'
      });
    });

    req.on('error', reject);
    if (options.body) {
      req.write(options.body);
    }
    req.end();
```

### Expected behaviour

the send should actually work

### Actual behaviour

about 60% of the time, the send fails with ```{ code: 3, message: 'unexpected EOF', details: [] }```  the other 40% it works just fine.

**Comment by razorman8669** [comment]
Hi guggero, thanks for pointing me to those docs.  After reimplementing using websockets, i'm seeing 100% success rate...so far.

Something to point out though, is that the docs do not make mention of needing to use the websockets library if you want things to go smoothly.  in other words, the docs here https://api.lightning.community/#v2-router-send use the `request` (which is deprecated in favor of `http.request`) library to make a simple POST request, and we ended up writing our own stream-decoding-parser for handling the stream of payment updates.  which seemed to work... 40% of the time.  It was the other 60% with intermittent failures that made us very confused.

even moreso, was we used the same approach for subscribing to the invoices endpoint, but had no failures on that one... it was only the send endpoint that was giving us EOF errors.

After spending much time on this, it seems that the API docs could use some mentioning of using websockets and link to [websocket docs](https://github.com/lightningnetwork/lnd/blob/master/docs/rest/websockets.md).  or better, use `websockets` (`ws` library) in the examples instead of `request`

**Comment by guggero** [comment]
You're right, the API docs doesn't mention WebSockets in the Python examples.

So both the file https://github.com/lightninglabs/lightning-api/blob/master/templates/rest/lnd_python.md and https://github.com/lightninglabs/lightning-api/blob/master/templates/grpc/lnd_python.md should be updated accordingly.
I'm no Python programmer, so perhaps you could create a PR to that repo?
I'll review and test the changes.
