### ISSUE TITLE
Expensive but pointless anchor sweep transaction

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6652]
### Background

As part of a force-close of an anchor channel (due to an HTLC timeout), my node published the force-close TX with a fee rate of 13.7 sat/vByte. As my peer was the channel initiator, my peer paid those fees.

My node then also published a sweep transaction to retrieve the anchor output (330sat). This transaction was created with a fee rate of 13.7 sat/vByte (3,748sat). This transaction was pointless, as a) the fees paid exceed the 330sat reward b) the fee rate is not higher than the fee rate of the close transaction.

I expect lnd to be resourceful with my funds. Wasting 3,748sat without any benefit does not match this expectation.

Close Transaction: https://mempool.space/tx/9e5196388d61b20ee13138420de4ac786c3ff104066578a7bcb9075f1e51a906

Note that lnd later replaced the 13.7 sat/vByte sweep transaction by one paying 22.1 sat/vByte. I believe the first sweep transaction should not have been broadcast, though.

Logs:
2022-06-20 19:57:17.644 [INF] SWPR: Creating sweep transaction 50346cb6df2ed640faa9e8fc296b6c34e6721c62101d267a58f098c5e2c128c6 for 2 inputs (... (CommitmentAnchor), b2fd843d33cc1054f0eed5a0db68300604acd0138a67ad5709826a36adaca2be:0 (WitnessKeyHash)) using 3415 sat/kw, tx_weight=719, tx_fee=0.00003748 BTC, parents_count=1, parents_fee=0.00003105 BTC, parents_weight=1288

2022-06-20 20:28:39.966 [INF] SWPR: Creating sweep transaction b8db5fca53a1b0d2e88cc82ec1103d775e8edb992c2e27341415ff36f567d6a6 for 2 inputs (... (CommitmentAnchor), 15d7d610f2bec8671ddcb96fd7d1838625f22afe7bef5b5b6360a05de94f3eb3:0 (WitnessKeyHash)) using 3517 sat/kw, tx_weight=719, tx_fee=0.00003953 BTC, parents_count=1, parents_fee=0.00003105 BTC, parents_weight=1288

### Your environment

* version of `lnd`: lnd 0.15.0-beta.rc6
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Force-close anchor channel.

### Expected behaviour

Anchor sweep transaction is created with a very low fee rate (so that it is worth it to recover 330sat) OR with a fee rate higher than the close-tx (so that the close-tx is confirmed faster, assuming this is necessary).

### Actual behaviour

A sweep transaction is created that is too expensive and does not help confirming the close-tx (CPFP).

**Comment by hazrulnizam** [comment]
It looks like your initial force close transaction actually has a fee rate of 9.66 sat/vB, which was not enough to get into [block 741609](https://mempool.space/block/0000000000000000000665d5f08deed598ecf97e992dfc9c3843538e588e3600).

Block 741609 was confirmed at 19:56, and your node responded to the force-close transaction not getting confirmed by using the anchor output to perform CPFP, as evidenced by your log:

`2022-06-20 19:57:17.644 [INF] SWPR: Creating sweep transaction 50346cb6df2ed640faa9e8fc296b6c34e6721c62101d267a58f098c5e2c128c6 for 2 inputs (... (CommitmentAnchor), b2fd843d33cc1054f0eed5a0db68300604acd0138a67ad5709826a36adaca2be:0 (WitnessKeyHash)) using 3415 sat/kw, tx_weight=719, tx_fee=0.00003748 BTC, parents_count=1, parents_fee=0.00003105 BTC, parents_weight=1288`

At 20:27, [block 741610](00000000000000000003bb428f50e2d825f2ff6bdde64b34f1d7b0af5219728c) was confirmed, and your transaction still had not make it into the blockchain. Your node then increases the CPFP fee:

`2022-06-20 20:28:39.966 [INF] SWPR: Creating sweep transaction b8db5fca53a1b0d2e88cc82ec1103d775e8edb992c2e27341415ff36f567d6a6 for 2 inputs (... (CommitmentAnchor), 15d7d610f2bec8671ddcb96fd7d1838625f22afe7bef5b5b6360a05de94f3eb3:0 (WitnessKeyHash)) using 3517 sat/kw, tx_weight=719, tx_fee=0.00003953 BTC, parents_count=1, parents_fee=0.00003105 BTC, parents_weight=1288`

which raises the 'effective' fee rate of your combined force close transcation + anchor sweep to 13.7 sat/vB, which then made it into [block 731611](https://mempool.space/block/0000000000000000000208c1bd86a976d81620821f6d56a8a5c3b83366ebd128) a couple of minutes later.

I would say this is an excellent example of the anchor outputs working as intended.

**Comment by C-Otto** [comment]
> It looks like your initial force close transaction actually has a fee rate of 9.66 sat/vB, which was not enough to get into [block 741609](https://mempool.space/block/0000000000000000000665d5f08deed598ecf97e992dfc9c3843538e588e3600).

Yes, and I think this makes this whole issue invalid. Sorry for the confusion, I think mempool.space showed the aggregated fee rate which I confused with the individual fee rate.

**Comment by C-Otto** [comment]
> lnd won't create sweeps for something as small as 330 sats in isolation, but will bundle it along w/ other sweeps.

That's incorrect. Force-Close TX: https://mempool.space/tx/0872418971226cd4ad9445f1c80fa5f8a9b7d7c1e41fe50c813d6b48e5317b88

Anchor Sweep TX: https://mempool.space/tx/9010dca5bf99896884fbcbea7b83e17bbe3e48853dcec725a8157b06e2a91d9d

This time the sweep cost 181, which is less than 330. I'm fine with that.
