### ISSUE TITLE
Regression: fwdinghistory only accepts --start_time as last argument

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6674]
### Background

Previously, this worked:
`lncli fwdinghistory --start_time -10y --index_offset 0 --max_events 1`

With lnd 0.15.0-beta-rc6 I get `[lncli] unable to decode start_time: strconv.ParseUint: parsing "--index_offset": invalid syntax`

The command works as expected if I move `--start_time` to the end:

`lncli fwdinghistory --index_offset 0 --max_events 1 --start_time -10y`

### Your environment

* version of `lnd`: lnd 0.15.0-beta-rc6
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

`lncli fwdinghistory --start_time -10y --index_offset 0 --max_events 1`

### Expected behaviour

JSON output

### Actual behaviour

`[lncli] unable to decode start_time: strconv.ParseUint: parsing "--index_offset": invalid syntax`

**Comment by ErikEk** [comment]
I can take a look.

**Comment by ErikEk** [comment]
`lncli fwdinghistory --start_time=-10y --index_offset=0 --max_events=1` works but I'll take a closer look at what is going on here.

**Comment by ErikEk** [comment]
v1.22.9 works for me too.
