### ISSUE TITLE
Replaced transaction's amount is shown twice in "unconfirmed_balance"

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6677]
### Background

My node recovered the commitment amount a couple of days after a force-close. The first transaction showed up in `unconfirmed_balance` (`lncli walletbalance`), as expected. However, lnd decided to replace this transaction by a transaction paying a higher fee rate. Now, `unconfirmed_balance` shows the double of the amount.

### Your environment

* version of `lnd`: lnd 0.15.0-beta.rc6
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Let lnd recover commitment amount after force-close. Let lnd replace (cheap) transaction by (more expensive) transaction. Run `lncli walletbalance`.

### Expected behaviour

Amount is shown in `unconfirmed_balance`.

### Actual behaviour

Double of the amount is shown.

**Comment by guggero** [comment]
Probably related and/or duplicate of https://github.com/lightningnetwork/lnd/issues/5244.

**Comment by C-Otto** [comment]
Yes, or rather #5225.

PS: Now I have 3x the amount :)
