### ISSUE TITLE
fuzz: upgrade to testing.F

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#6679]
The fuzz tests we have don't run on my machine anymore with go1.18. dvyukov/go-fuzz is basically deprecated at this point. We should upgrade to language-native `testing.F` even if it's not that great yet. 

Basically the fuzz tests should stay the same, but the build step is changed:

- remove `make`-level fuzz references
- fuzz tests that don't need to import from other packages can live in the same package they test (`lnwire`)
- fuzz tests that require testing more complex state will likely need to live in a top-level `fuzz` package
- these should probably be behind build flags since we still support 1.17

It might be better to move a package at a time to ease review

**Comment by babinchak** [comment]
Hello, new here. Thought this would be a good first issue for me. Just made a commit migrating lnwire: https://github.com/babinchak/lnd/commit/1c7cd98f40a6bda99adb2b00c58ba66a1ec8c4ff

Working on migrating brontide, wtwire, and zpay32 to make my first pull request.
For now, I put all the tests from fuzz/lnwire/*.go to a single lnwire/fuzz_test.go file, preserving order.

Let me know if you think I should organize/write the tests different.

**Comment by babinchak** [comment]
Migrated wtwire, similar to lnwire: https://github.com/babinchak/lnd/commit/520afde240b8ec77f131698cad52aaacb39065a0

**Comment by babinchak** [comment]
Migrated zpay32
Fuzzed encode and decode for 30s each successfully. Want to know good seed corpus values.

**Comment by babinchak** [comment]
Migrated brontide: https://github.com/babinchak/lnd/commit/27591d07a9d15659837d35dda5ce4b3ea6874440

**Comment by babinchak** [comment]
diff that might help visualize brontide migration: https://github.com/babinchak/lnd/compare/f3a67bd..33dc5e5
Just using github as a diff tool, the commits in diff_demo branch aren't actual changes

**Comment by babinchak** [comment]
Might need help writing function comments for fuzz tests in lnwire, wtwire, and zpay32. Brontide's fuzz test comments were detailed so I copied them but the other packages were not.
