### ISSUE TITLE
Router always picks the direct channel between A and B, even though there is no more balance and many alternative routes are available

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#668]
I'm running 2 nodes (A and B) on db06a8a7eea310f6eda12025a80e5fe5f788aaf5 (Jan 12)

Router always picks the direct channel between A and B, even though there is no more balance in the channel and I have plenty of other channels with local_balance and remote_balance. There are many indirect routes available, as can be shown with `lncli queryroutes` for the same invoces (with the help of `lncli decodepayreq`). Here is my queryroutes output https://pastebin.com/6xjG3g77

RequestRoute seems to always return the one direct route, even after the balance there is depleted.

The problem can be narrowed down in missioncontrol.go, this log line gets executed when picking routes to pay an invoice:
https://github.com/lightningnetwork/lnd/blob/6f408004e29f1b464502d30342211bf393e5c548/routing/missioncontrol.go#L227

I always get an empty pruneView: "DBG] CRTR: Mission Control session using prune view of 0 edges, 0 vertexes"

The evidence of that is:
```
lncli debuglevel --level CRTR=trace
grep 'Mission Control session using' .lnd/logs/testnet3/bitcoin/lnd.log | awk '{print $12, $13, $14, $15}' | sort | uniq -c
    498 0 edges, 0 vertexes
```

Sometimes I see 1 edge and 0 vertexes in the pruneView:
```
2018-01-24 09:32:18.796 [DBG] CRTR: Reporting edge 1384490748044509184 failure t
o Mission Control
2018-01-24 09:32:18.796 [DBG] CRTR: Mission Control session using prune view of
1 edges, 0 vertexes
```

Is it normal for pruneView to be empty while many routes are available?

**Comment by Roasbeef** [comment]
It doesn't matter if the router selects that route as it'll receive a failure from the switch, then prune out that edge and retry. The prune view gets _larger_ as less routes are actually available. `queryroutes` doesn't factor in any immediate balances (doesn't take into account flow).
