### ISSUE TITLE
Feature Request: Neutrino Get block by height

### ISSUE THREAD

**Issue by kornpow** [lightningnetwork/lnd#6688]
### Background

In the neutrino subsystem, it would be useful to be able to get a block by its height, instead of just by the block hash.

If I wanted to convert a short_chan_id: `{block_height}x{tx index}x{output index}` to a channel point `{transaction id}:{output index}`, I would need this ability.

**Comment by ErikEk** [comment]
I'll do it.

**Comment by kornpow** [comment]
it seems like the linked PR will cover this use case, thanks!
