### ISSUE TITLE
Peer is dropped after failed fee negotiation

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#669]
After connecting to a peer and then attempting to establish a channel with it, I got the error message " local/remote feerates are too different". After this occurred, my connection with the peer was dropped. I would not expect that failing to establish a channel with a peer would lead to that peer getting dropped.

Here's the full session:

`**sean@dmt:~$ lncli connect 03ae988eafce66559ce91d99f3ef29450333934d54d1c7de9fd0579e0bd5ef8973@109.99.154.45:9735**

{
    "peer_id": 0
}

**sean@dmt:~$ lncli openchannel 03ae988eafce66559ce91d99f3ef29450333934d54d1c7de9fd0579e0bd5ef8973 100000 50000**

[lncli] rpc error: code = Code(208) desc = local/remote feerates are too different: remoteFeeratePerKw=5000 localFeeratePerKw=53760

**sean@dmt:~$ lncli openchannel 03ae988eafce66559ce91d99f3ef29450333934d54d1c7de9fd0579e0bd5ef8973 100000 5000**

[lncli] rpc error: code = Unknown desc = unable to find peer nodeID(03ae988eafce66559ce91d99f3ef29450333934d54d1c7de9fd0579e0bd5ef8973), peerID(0)
`

Note that I don't know if it was my local node that dropped the connection or the remote node, nor do I know which LN implementation the remote node was running. Also, the remote node is no longer up, so I can no longer reproduce the issue (though I reproduced it multiple times while it was still up).

Is dropping a peer the expected behavior when a channel fails to be established? If not, is it more plausible that this behavior is a bug, or is a policy decision by either the local or remote node? Apologies if this behavior is documented somewhere, I wasn't able to find it.

**Comment by Roasbeef** [comment]
This is an issue with `c-lightning`, not `lnd`. If it sees divergent fee rate, then it'll immediately disconnect. This can happen at times on testnet, as fees don't matter at all, so estimators are all out of wack.

**Comment by merehap** [comment]
For reference, here's the issue on the c-lightning bug tracker: https://github.com/ElementsProject/lightning/issues/443
