### ISSUE TITLE
lncli: fix batchopenchannel help text

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#6697]
The `lncli batchopenchannl --help` command contains outdated help text, e.g. `local-amt` instead of `local_funding_amount` etc.

The list of valid options is here: https://github.com/lightningnetwork/lnd/blob/262591c3331c2170697fe89b8c49ab857db0adf7/cmd/lncli/cmd_open_channel.go#L702

**Comment by positiveblue** [comment]
Solved in #6698 thx @hieblmi
