### ISSUE TITLE
lncli: --chan_point option for updatechanstatus

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#6699]
### Background

`lncli updatechanpolicy` provides a `--chan_point` option which could also ease the use of `lncli updatechanstatus`
Maybe the --chan_point option makes also sense for more channel operations.

### Your environment
```
lncli version 0.15.0-beta commit=v0.15.0-beta
```

### Expected behaviour

```
lncli updatechanstatus --chan_point funding_txid:idx
``` 
can be used instead of 
```
lncli updatechanstatus --funding_txid tx --output_index idx
```

**Comment by ErikEk** [comment]
I'll look into it.

**Comment by SachinMeier** [comment]
This issue was resolved.

**Comment by hieblmi** [comment]
Thanks, wanted to keep it open, I think there might be other commands that benefit from a chan_point flag. Will have a look in a bit.

**Comment by SachinMeier** [comment]
Funny enough I tried to open an mr to do exactly this a few days ago. Every cli cmd that takes funding_txid & outpoint_index now also takes chan_point.

**Comment by hieblmi** [comment]
Nice, could you link the PR here and I'll close the issue.

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/6705.
