### ISSUE TITLE
Improving error messaging for lncli commands

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#671]
Many lncli commands give unhelpful error messages in various failure cases. For example, when a host can't be reached or rejects a connection, `lncli connect` and `lncli openchannel` give the following error message:

`[lncli] rpc error: code = OutOfRange desc = EOF`

This message does not tell the user what is wrong, resulting in user confusion and low value bug reports, like https://github.com/lightningnetwork/lnd/issues/662 . Instead the error description could be something like "remote host is unavailable or rejected connection".

Another example is the error message "unable to find peer" when a command requires a peer but the user specifies a pubkey that does not correspond to a current peer. A better message might be "specified host is not currently connected". Both the `openchannel` and `disconnect` commands are affected by this. Note that this change might be a little more controversial because it would modify an error message within server.go, rather than strictly within commands.go.

Scope for this issue:
1. Create a PR improving the error messages listed above (I can start this immediately).
2. Investigate and document here similar error messages that can improved within commands.go.
3. Create a PR/PRs for improving the cases found in point 2.

Does this all sound reasonable?

Previous issue discussing this topic with @Roasbeef : https://github.com/lightningnetwork/lnd/issues/662

**Comment by merehap** [comment]
I've created a branch in my repo that will carry these changes: https://github.com/merehap/lnd/tree/cli_errors . Creating a PR for the changes is blocked upon the following PR being merged: https://github.com/lightningnetwork/lnd/pull/728

**Comment by erkarl** [comment]
One confusing error message that I encountered was:
```
admin@icoin:~ $ lncli decodepayreq lntbXYZ
[lncli] rpc error: code = Unknown desc = unknown network
```
only to find out later that I was trying to pay a testnet invoice on mainnet :).

**Comment by Roasbeef** [comment]
Closing this as we're tracking the over arching error code improvement here: https://github.com/lightningnetwork/lnd/issues/5586
