### ISSUE TITLE
[lncli] error parsing JSON: unknown value "\"TAPROOT_PUBKEY\"" for enum walletrpc.AddressType

### ISSUE THREAD

**Issue by alfzk** [lightningnetwork/lnd#6715]
### Background

I'm trying to create a view-only node but when I try to import `lncli createwatchonly /root/.lnd/accounts-signer.json` it returns the following error `[lncli] error parsing JSON: unknown value "\"TAPROOT_PUBKEY\"" for enum walletrpc.AddressType` both software are in the same version.

### Environment

* version of `0.14.1-beta`
* version of `bitcoind`, or other backend

### Steps to reproduce
```bash
Signer:~/$ lncli wallet accounts list > accounts-signer.json
WatchOnly:~/$ lncli createwatchonly accounts-signer.json
```

**Comment by positiveblue** [comment]
Is the signer using  `v0.15.0` or higher? I guess `createwatchonly` expects to understand all the addresses in the file but you are trying to import from a newer version (with more address types) to an old one (where that address type did not exist yet).

You should be able to use `createwatchonly` in a version that is _at least_ as new as the one you are listing the accounts.

Note: we could change the default behavior of `createwatchonly` and simply ignore the types that are not know for us but that is something that needs some discussion.
