### ISSUE TITLE
Heavy bloating of channel.db

### ISSUE THREAD

**Issue by Bitcoinite** [lightningnetwork/lnd#6737]
### Background

The channel.db is increasing in size very rapidly. It was about 7.2 GB when I upgraded from lnd v0.14.3-beta to v0.15.0-beta. The first thing I noticed after upgrading was, that the channel.db initially grew slower than pre-upgrade. After some days I had a force close with some channel the size of my channel.db exploded by over 1 GB in growth per day. Restarting lnd and compacting the channel.db fixed this issue for a little while. Now I experience this heavy bloating of the channel.db once again, this time there were no channel closes implied.

Currently each time i restart lnd and compact the channel.db I start at around 7.4 GB in db size. This will grow at a rate of up to 100 MB/hour. The growth rate seems to accelerate the bigger the channel.db gets. The only thing I can do right now is to restart lnd compact the channel.db every 48 hours (when it hits around 11 GB).

My node has 55 channels and I'm currently forwarding around 3000 transactions per week. Rebalancing channels with LNDg. Typically 10-30 pending HTLCs.

### Your environment

* Version of lnd v0.15.0-beta
* which operating system (`uname -a` on *Nix): `Linux umbrel 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: 0.23
* any other relevant environment details -

### Steps to reproduce

Running lnd 0.15-beta and watching the size of the channel.db

### Expected behaviour

The channel.db size should stay the same or at least grow very slowly in size

### Actual behaviour

The channel.db size is bloating by a growth rate of up to 100 MB per hour.

**Comment by BhaagBoseDK** [comment]
does it impact if lndG creates an invoice for each rebalance? How much space does the invoice take usually? I am assuming expired invoices (unsuccessful rebalances) would be garbace collected on the fly based on lnd settings.

**Comment by hazrulnizam** [comment]
It's not the invoice, I think. The continuous rebalance attempt keeps sending out channel state updates, of course the db bloats. It would have been worse pre-0.15.0.

Try stopping the LNDg for a period of time and watch the db size when it's not spamming HTLCs all the time.

**Comment by C-Otto** [comment]
My node is processing lots of HTLC updates and I barely see any DB size increase. I doubt that this is the reason.

**Comment by 2Fast2BCn** [comment]
> My node is processing lots of HTLC updates and I barely see any DB size increase. I doubt that this is the reason.

Aren't you also aggressively running some kind of rebalacer (but rebalance-lnd instead of LNDg)

**Comment by Roasbeef** [comment]
If you're doing a lot of rebalancing, you end up accumulating a lot of failed payments (most scripts just sort of try to brute force things). You can delete them manually with `lncli deletepayment --all`. 

In 0.15.1 we'll start to _always_ delete failed payments after the payment has terminated. A new option will let you keep them around if you want.

**Comment by C-Otto** [comment]
> Aren't you also aggressively running some kind of rebalacer (but rebalance-lnd instead of LNDg)

Yes, I do lots of rebalance (at least attempts), and I also have some very active channels (at least when it comes to failed attempts).

**Comment by Bitcoinite** [comment]
After my last restart and compaction, the channel.db has grown 100 MB over night. I will wait until the real bloating (100 MB per hour) kicks in again before making a copy of the file. I started documenting the current size of the db at several times per day. I also added CHDB=debug, maxlogfiles=10 and maxlogfilesize=100 to the lnd.conf

Agreeing with C-Otto that the rebalancing from LNDg shouldn't cause this. I'ts only trying to rebalance one channel at a time, that's all. Others are rebalancing much more aggressively and don't see their channel.db bloating. Also I doubt that my little 55 channel node sees as many probes and HTLCs as some bigger nodes that don't have this issue.

One more thing that I noticed: When the real bloating kicks in, lnd constantly uses 70-135% CPU (according to htop).usually it's more like 5-15% with some rare spikes to 40-80% CPU load.

**Comment by Bitcoinite** [comment]
My documentation of the channel.db size so far:

15.07.2022 16:46 DB Size: 7.473 GB
15.07.2022 18:20 DB Size: 7.473 GB
15.07.2022 18:49 DB Size: 7.49 GB
16.07.2022 00:44 DB Size: 7.506 GB
16.07.2022 09:14 DB Size: 7.574 GB
16.07.2022 11:29 DB Size: 7.585 GB
16.07.2022 13:09 DB Size: 7.602 GB
16.07.2022 16:12 DB Size: 7.669 GB
16.07.2022 23:13 DB Size: 7.805 GB
17.07.2022 01:11 DB Size: 7.891 GB
17.07.2022 09:54 DB Size: 8.34 GB
17.07.2022 13:35 DB Size: 8.534 GB
17.07.2022 19:37 DB Size: 9.106 GB
17.07.2022 23:12 DB Size: 9.62 GB

**Comment by BhaagBoseDK** [comment]
In my observation, the bloating stops after `sync-freelist=false` is set. Since the default is false, most node operators reported bloating stopped after 0.15 however those who had set it to true (for whatever reasons) experienced bloating.

Here is data from my observations.

```
Date                           #Update   Size
---------------------------------------------------------------------------------------------------
Fri 15 Jul 22:51:53 UTC 2022   3120625   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 16 Jul 06:49:49 UTC 2022   3134824   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 16 Jul 06:52:26 UTC 2022   3134880   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 16 Jul 06:57:37 UTC 2022   3134932   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 16 Jul 19:59:42 UTC 2022   3168681   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sun 17 Jul 07:36:48 UTC 2022   3202378   4.8G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sun 17 Jul 20:01:00 UTC 2022   3221174   4.8G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Mon 18 Jul 06:23:22 UTC 2022   3233913   4.8G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Mon 18 Jul 16:41:07 UTC 2022   3250284   4.9G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Tue 19 Jul 06:19:48 UTC 2022   3275720   4.9G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db <-- Compact Here
Wed 20 Jul 06:50:27 UTC 2022   3207812   4.7G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Wed 20 Jul 21:26:58 UTC 2022   3234685   5.3G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Thu 21 Jul 06:33:46 UTC 2022   3249400   5.8G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Thu 21 Jul 17:42:11 UTC 2022   3266275   6.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db <-- Compact Here. Sync freelist=false
Thu 21 Jul 18:03:50 UTC 2022   3266427   4.5G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Fri 22 Jul 07:06:09 UTC 2022   3223813   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 23 Jul 07:14:15 UTC 2022   3231219   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sat 23 Jul 17:12:17 UTC 2022   3250485   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sun 24 Jul 06:08:53 UTC 2022   3273608   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Sun 24 Jul 12:23:44 UTC 2022   3286024   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
Mon 25 Jul 06:47:23 UTC 2022   3304949   4.6G /home/umbrel/umbrel/lnd/data/graph/mainnet/channel.db
```

**Comment by lucasdcf** [comment]
@Bitcoinite Have you tried setting sync-freelist=false?

**Comment by Roasbeef** [comment]
@BhaagBoseDK we recommend that users run _with_ `sync-freelist=false` (the default). Without that argument, you'll see very high CPU usage with large database, since it needs to sort+write the freelist to disk each time. The default setting trades that off for longer start times, since the freelist needs to be reconstructed at start up each time.
