### ISSUE TITLE
`i_know_what_i_am_doing` option for `closeallchannels`

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#6743]
### Background

Unintentional closure of all channels can have various negative implications for routing node operators.
A `i_know_what_i_am_doing` flag would mitigate unintentional closure of all channels.

### Your environment

lncli version 0.15.0-beta

**Comment by yyforyongyu** [comment]
I think for `closeallchannels`, as the name itself suggests clearly, that you will close all your channels when using this command. And I'm not sure of the utility of adding that flag?

**Comment by hieblmi** [comment]
From other tools I am used to have at least another check before performing critical operations. Maybe a "Do you really want to close all channels?" would be better than a flag?

**Comment by ohenrik** [comment]
Yes the `closeallchannels` says what it does pretty clearly, but... I was a bit quick, a bit tired and looked for the `closedchannels` command to see *all* closed channels... yeah you can guess what happened. It's a monumental fail on my part and entirely my own. But.

The `payinvoice` command has a confirmation dialogue. I would say `closeallchannels` is a much more dangerous command and absolutely deserves to have such a confirmation dialogue. I'm not sure how much work it is to add one though. Maybe this is a good candidate for "good first issue"?

**Comment by guggero** [comment]
Created a PR to fix this.
