### ISSUE TITLE
signmessage ignores message text after space

### ISSUE THREAD

**Issue by MykelSIlver** [lightningnetwork/lnd#6745]
### Background

`lncli signmessage` seems to ignore all the message text after a space character (see steps to reproduce). 
As a result signmessage returns the same signatures after the first space of the messagetext.

### Your environment

* version of `lnd`
```
 0.14.2-beta
 commit_hash: 1e511be523eb8e97c4e2d9c89a7a263963a3929f

```        
* which operating system (`uname -a` on *Nix)
`Linux 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux`

* version `bitcoind`
Bitcoin Core 22.0.0

* any other relevant environment details
Umbrel Version 0.5.1

### Steps to reproduce

```
lncli signmessage "hello"
{
    "signature": "d9dtkf119rjx8sk9g6zqpmomrh6kq6spfn3nzqp88g8rrr8eghxykqht8zsrmio1mhi6czk3qhoqiqgwhh99kuyt4zt9erxrzosbswse"
}

lncli signmessage "hello abcde"
{
    "signature": "d9dtkf119rjx8sk9g6zqpmomrh6kq6spfn3nzqp88g8rrr8eghxykqht8zsrmio1mhi6czk3qhoqiqgwhh99kuyt4zt9erxrzosbswse"
}
```

`"hello"` and `"hello abcde"` gives both the same signature  `d9dtkf119rjx8sk9g6zqpmomrh6kq6spfn3nzqp88g8rrr8eghxykqht8zsrmio1mhi6czk3qhoqiqgwhh99kuyt4zt9erxrzosbswse` 

### Expected behaviour
`lncli signmessage "hello" `should give another signature than `lncli signmessage "hello abcde"`

### Actual behaviour
Same signature is returned after space in messagetext of signmessage. All the text in the message text seems to be ignored after the first space character in the messagetext

**Comment by ErikEk** [comment]
@MykelSIlver Have you tried lnd 0.15?

**Comment by MykelSIlver** [comment]
> @MykelSIlver Have you tried lnd 0.15?

No. Since I use Umbrel, I am stuck with the version of lnd they run. Could you please check if this happens on the 0.15 version of lnd? Love to hear your response!
Thank you.

**Comment by ErikEk** [comment]
@MykelSIlver Running om master and it seems to be working.

**Comment by ErikEk** [comment]
@MykelSIlver Maybe you can encode your message to avoid spaces until you can upgrade to 0.15.

**Comment by MykelSIlver** [comment]
> @MykelSIlver Running on master (0.15+) and it seems to be working.
```
lnshell@6f74e28c3fbe:~$ less /lnd/logs/bitcoin/mainnet/lnd.log                                                                                                                                                [74/128]
lnshell@6f74e28c3fbe:~$ lncli getinfo                                                                                                                                                                                 
{                                                                                                                                                                                                                     
    "version": "0.15.0-beta commit=v0.15.0-beta",                                                                                                                                                                     
    "commit_hash": "5c36d96c9cbe8b27c29f9682dcbdab7928ae870f",                
```                     

```
lnshell@6f74e28c3fbe:~$ lncli signmessage "hello"
{
    "signature": "d9dtkf119rjx8sk9g6zqpmomrh6kq6spfn3nzqp88g8rrr8eghxykqht8zsrmio1mhi6czk3qhoqiqgwhh99kuyt4zt9erxrzosbswse"
}
lnshell@6f74e28c3fbe:~$ lncli signmessage "hello abcde"
{
    "signature": "d9dtkf119rjx8sk9g6zqpmomrh6kq6spfn3nzqp88g8rrr8eghxykqht8zsrmio1mhi6czk3qhoqiqgwhh99kuyt4zt9erxrzosbswse"
}
lnshell@6f74e28c3fbe:~$     
```          

Strange I surprisingly checked with getinfo and use 0.15!. I still have two the same signatures...

**Comment by ErikEk** [comment]
I'm running:
"version": "0.15.0-beta commit=kvdb/v1.1.0-1141-g5c36d96c9",
"commit_hash": "5c36d96c9cbe8b27c29f9682dcbdab7928ae870f"
and it is working.
Could be. No problem man.

**Comment by ErikEk** [comment]
@MykelSIlver If you call it with REST just remember to send the message byte64 encoded instead of as a string.

**Comment by MykelSIlver** [comment]
Should I close this ticket?

**Comment by ErikEk** [comment]
Yes, if you solved it.

**Comment by MykelSIlver** [comment]
Status to solved because I think it has to do with Umbrel .
When using RTL (Ride The Lightning) under umbrel gives you the option signmessage Gui based which works fine!

**Comment by guggero** [comment]
I just tested this with `lnd v0.15.0-beta` and `lnd v0.14.3-beta` and got the expected result in both cases. My suspicion is that Umbrel has an alias for `lncli` and does something incorrectly with the command line arguments passed to it.
