### ISSUE TITLE
[lncli] rpc error: code = Unknown desc = edge not found

### ISSUE THREAD

**Issue by LStratos** [lightningnetwork/lnd#6764]
### Background

On a daily bases i check my node on amboss and spotted nicehash channel have the status  stated that my node have disable the channel. 
![image](https://user-images.githubusercontent.com/16865519/180631274-183bae30-954d-4ce3-8214-8d368e0e98d3.png)

but on my end( in my node ) the status was online
![image](https://user-images.githubusercontent.com/16865519/180631291-6bcaabb5-0bc6-47bb-9ed6-c293b7d77141.png)

### Your environment

* Lightning node : 0.15.0-beta 
* OS : Umbrel
* BTC node : 22.0-build-2

### Steps to reproduce

i try running the below command
lncli updatechanstatus d5cde60872614da1062643c1b9de5339f2e9855e6071c7bce58ec1bffa0b53bb --action enable

and got the error : [lncli] rpc error: code = Unknown desc = edge not found

so i am wondering is it my node issue or something?

**Comment by ellemouton** [comment]
if you use `lncli listchannels` does it show the channel as active? 

worth noting that enabling/disabling is directional. So perhaps they just disabled the direction from them to you. But that would not explain why you get the `edge not found` error

**Comment by SachinMeier** [comment]
in the command you have above, you aren't passing the vout (output_index).

**Comment by guggero** [comment]
Closing as per the comment above, thanks for noticing, @SachinMeier.

You can also use the `--chan_point` flag which takes the format `txid:output_index`.
