### ISSUE TITLE
How to find compromise in restarted fee negotiation (coop close)?

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6781]
### Background

If both nodes run lnd 0.15+, it is possible to retry a failed fee negotiation (as part of a cooperative channel close). If one node is running an older version of lnd, the channel has to be force-closed. 

However, in my observation this doesn't help as long as both peers stick to the same values: my node still suggests numbers far below my peer's suggestions, and after a few attempts the negotiation fails.

How can I tell my lnd (without restart!) to accept/suggest higher fee rates for a specific peer/channel?

See https://github.com/lightninglabs/loop/issues/516 for an example of this.

### Your environment

* version of `lnd`: lnd v0.15.0-beta with a few patches from master (and some of my own)
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Configure very low fee rates (bitcoind.estimatemode=ECONOMICAL, coop-close-target-confs=1000). Open channel to LOOP. Let LOOP coop-close channel.

### Expected behaviour

Nodes agree on fee rate, especially after manual intervention on my side.

### Actual behaviour

Fee rate negotiation fails repeatedly.

**Comment by Roasbeef** [comment]
This'll be fixed by https://github.com/lightningnetwork/lnd/pull/6770 

Long story short: we went to catch up w/ co-op close semantics in the spec, rolled that out, realized that caused issues with co-op close in the wild (we went to no longer accept fees above the commitment fee, but w/ anchors that can be very low), realized that requirement was removed from the spec, now have a fix to roll back our prior change and make things more flexible.

**Comment by Roasbeef** [comment]
Fee negotiation [isn't _super_ well defined in the spec](https://github.com/lightning/bolts/issues/1013) (basically just says agree on a fee). By 0.16 we'll have the fee range feature implemented, and for taproot we might actually just try to re-do things all together (round based, only send a sig at the very end, etc).
