### ISSUE TITLE
Small issue on INSTALL.md

### ISSUE THREAD

**Issue by starrymoonlight** [lightningnetwork/lnd#679]
I found that these lines:

export GOPATH=~/gocode
export PATH=$PATH:$GOPATH/bin

Only worked if I used this:

export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin

**Comment by Roasbeef** [comment]
You're meant to create the `gocode` directory. Depending on how you installed Go, then it may actually _live_ in `~/go`. I recommend checking out the official docs on this matter: https://github.com/golang/go/wiki/SettingGOPATH
