### ISSUE TITLE
Automatic RPC configuration for btcd

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#68]
Currently, when setting up `lnd` users are required to manually enter the RPC credentials for `btcd`. This can be a bit cumbersome and makes setting up `lnd` initially a bit clunky. 

As an enhancement alternative, `lnd` can attempt to lookup the app data directory for `btcd` and parse out the current RPC credentials. The daemon would then default to this route for automatically configuring the `btcd` web-sockets RPC clients currently within `lnd`.

**Comment by jackzampolin** [comment]
Looks like this is already implemented? https://github.com/lightningnetwork/lnd/blob/master/config.go#L38

**Comment by Roasbeef** [comment]
Nice eye! However, that section only _partially_ implements what I briefly lined out in this issue. 

What you pointed out is the section where we automatically read btcd's RPC certs which are required for the JSON-RPC's established TLS connection. The missing compontent is to also parse out the _user authentication_ information from the `btcd.conf` which is found in the `btcdHomeDir` folder. 

Once the file is located+read into memory either a regex or some manual parsing can be used to grab the values for `rpcuser` and `rpcpass`.
