### ISSUE TITLE
channel.db massive (22GB)

### ISSUE THREAD

**Issue by SatCollector** [lightningnetwork/lnd#6800]
### Background

My channels.db is massive at 22gb and growing quickly. I ran compact on it and it barely shrinks. 
I rebalance a lot but have read other people that rebalance a lot don't have massive dbs like I do.
I ran DeleteAllPayments using rest and grpc and it doesn't seem to really do anything. 
Not sure how I can get my database to shrink, any ideas?

These are some of my settings:

[Application Options]

payments-expiration-grace-period=30m
ignore-historical-gossip-filters=1
sync-freelist=false
stagger-initial-reconnect=1
maxlogfiles=3
gc-canceled-invoices-on-startup=true
gc-canceled-invoices-on-the-fly=true
accept-amp=true

[bolt]

db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=100h

### Your environment
lnd:v0.14.3-beta

**Comment by alexbosworth** [comment]
try updating to lnd 0.15

**Comment by positiveblue** [comment]
Hello @SatCollector, as @alexbosworth said, updating to `v0.15.x` will help you with this. From the [release notes](https://github.com/lightningnetwork/lnd/releases) `This migration enables a 95% reduction in the disk space consumed by new channel updates`

That will help to stop the db from growing that much but it's not a silver bullet to reduce the current size of the db yet. [More changes](https://github.com/lightningnetwork/lnd/pull/6469) have already been merged to master, but they are not included in any release yet.

**Comment by Roasbeef** [comment]
Yep, you should upgrade to 0.15 which cuts down state growth by ~90%. 0.15.1 will also contain an optional migration to reclaim all the used up state. 0.15.1 will also keep around less information on disk for failed payments as well.
