### ISSUE TITLE
lnd force-closes in response to warning messages

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lnd#6801]
A while back we added warning messages to the spec with the purpose of having a way to signal to nodes that something has gone wrong but that we do not want to force close any channels.

We started using warning messages to tell peers when we ignored a gossip message because it was bogus, with the message "Unreadable/bogus gossip message".

However, it looks like lnd interprets warning messages as critical errors and responds by force-closing channels - ignoring the entire purpose of warning messages?

A peer of mine pulled this from their log:

2022-08-06 12:14:48.864 [ERR] HSWC: ChannelLink(0db90ff58728d7698dbf9e478eca33109b9777898acf28b08bd9352a75a7a74c:0): failing link: ChannelPoint(0db90ff58728d7698dbf9e478eca33109b9777898acf28b08bd9352a75a7a74c:0): received error from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Unreadable/bogus gossip message with error: remote error

On my end I just received an error message that said "remote error".

**Comment by C-Otto** [comment]
I'm said peer. Let me know if you need further information.

**Comment by positiveblue** [comment]
@TheBlueMatt just checking: the [type](https://github.com/lightning/bolts/blob/master/01-messaging.md#the-error-and-warning-messages) for those messages is set to `1`?

**Comment by positiveblue** [comment]
I will try to replicate it locally but for the logs it looks like the message was really parsed as [error](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L2074) and not a [warning](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L2070)
@C-Otto do you do a quick search to see if you have any logs matching `received warning message from peer` for this or any other peer?

**Comment by C-Otto** [comment]
I can't find a single entry in the recent logs (~1 month).

**Comment by positiveblue** [comment]
I tried to replicate it, unsuccessfully, in the main branch + added a test for it #6805 

I noticed that it is tagged for v0.16.0 BUT if @C-Otto is running master it should include those changes. I am not sure what is the process for tagging a version (v0.15.1 for example) that not includes the latest changes in master though (maybe we manually cherry pick the commits that need to be included?).

@Roasbeef https://github.com/lightningnetwork/lnd/commit/115b0418747ba941875bd9f2be1bb18754f6f636 should include those changes right?

**Comment by C-Otto** [comment]
I guess you mean 99828b8ebb72e18be69a7870d5342d20a748412c? That's included in 115b0418747ba941875bd9f2be1bb18754f6f636.

**Comment by C-Otto** [comment]
> I can't find a single entry in the recent logs (~1 month).

I just realized that I've only started using the new code yesterday, which also means that older logs cannot contain this new log entry.

**Comment by positiveblue** [comment]
Did you started using the new code yesterday AFTER the force close? If so this solves the case. Next warning message should not trigger any force close/channel failure.

**Comment by C-Otto** [comment]
> Did you started using the new code yesterday AFTER the force close? If so this solves the case. Next warning message should not trigger any force close/channel failure.

That thought also crossed my mind :) But no, I triple checked. I first started with the new code, then the quoted log message appeared.

**Comment by Roasbeef** [comment]
We started to understand warning messages in [this PR](https://github.com/lightningnetwork/lnd/pull/6546) which is unreleased (only exists in master). There should be a [different log for nodes in master](https://github.com/lightningnetwork/lnd/pull/6546/files#diff-9926ec0b86d09ad93deb44807ccee9a52ed42535007f96ae497478c07b76843aR1999-R2005), and nodes on 0.15 and before should just be ignoring the message all together. So I think we need to set up a repro case here. 

This PR seems to indicate [we properly won't do anything when we get the message](https://github.com/lightningnetwork/lnd/pull/6805), so perhaps something else is going on here.

@positiveblue 
> I am not sure what is the process for tagging a version (v0.15.1 for example) that not includes the latest changes in master though 

We always branch minor release off that base branch. So 0.15.1 will only take in changes in that milestone, so it won't include us reading the warning message as an example.

**Comment by Crypt-iQ** [comment]
The problem is that `handleError` converts the `Warning` to an `Error` message and passes it to every link since it's the all-zero connection id:

`handleError`:
https://github.com/lightningnetwork/lnd/blob/6060e05d7cbba138b91051529d8ffbfc1672ed54/peer/brontide.go#L1535

all-zero:
https://github.com/lightningnetwork/lnd/blob/6060e05d7cbba138b91051529d8ffbfc1672ed54/peer/brontide.go#L1684-L1688

**Comment by Roasbeef** [comment]
@TheBlueMatt The reason y'all send the warning is also pretty interesting ("Unreadable/bogus gossip message"), might deserve another issue in the tracker. Is is that the gossip message is invalid from y'alls PoV, or it has like unknown types or something?
