### ISSUE TITLE
CLN interoperability: "unable to start peer: invalid remote features: missing feature dependency: 45"

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6802]
### Background

I'm running 115b0418747ba941875bd9f2be1bb18754f6f636 which is a very recent commit in `master` (somewhere between 0.15.0 and 0.15.1). Somewhere after 0.15.0 the issue surfaced, which seems to be limited to CLN peers. As I'm still able to connect to "zero fee routing | CLN" (`038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5`, @zerofeerouting), I guess that this issue is limited to some CLN versions.

### Your environment

* version of `lnd`: 115b0418747ba941875bd9f2be1bb18754f6f636
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23
* any other relevant environment details: `db.prune-revocation=true`

### Steps to reproduce

Connect to any of the following peers:
* `024271a1be2d7a3e2a276b241257be734d843885d252f50575e4c7db2691aedd3a` - "running v.0.12"
* `027b0575bc6a9a6a371f306e01916b34522a3bc2e9ce7490ebfea6815465734e98`
* `02fe6a27ddcb2dd9fa8479fe1d52549b5932079a493b51f1409fa2c5878f1bc07c` - running "the development tip of cln"
* `03a465772d45616bf6c8450a69191db8f3cf8cca19ff92138735fd5f1d436fe4dc`

### Expected behaviour

Connection

### Actual behaviour

`[INF] PEER: Peer(PUBKEY): disconnecting PUBKEY@IP:PORT, reason: unable to start peer: invalid remote features: missing feature dependency: 45`

**Comment by C-Otto** [comment]
With `git bisect` I get this commit introducing the issue:
a6c62eb71e6380c3b96d673a60c1712355342bb8

**Comment by C-Otto** [comment]
Looks like a CLN bug to me, see linked issue.

**Comment by positiveblue** [comment]
@C-Otto I think you are right, `ScidAliasOptional` (47) depends on `ExplicitChannelTypeOptional` (45) and `ZeroConfOptional` (51) on `ScidAliasOptional` (47).

**Comment by C-Otto** [comment]
According to https://github.com/lightning/bolts/blob/master/09-features.md 46/47 does not have any dependency.

**Comment by positiveblue** [comment]
It's true that it is not in the bolt. I may be missing something here but I fail to see how the nodes will [negotiate](https://github.com/ElementsProject/lightning/blob/669bca4a02b724f9326c1afaf00732c205501979/common/features.c#L100) if the channel that they are opening is zero conf or not if they cannot set the `channel_type` :eyes:

**Comment by C-Otto** [comment]
See comments for deps.go in https://github.com/lightningnetwork/lnd/pull/5955 (I can't link to them)

**Comment by C-Otto** [comment]
So lnd shouldn't include the 47->45 dependency for connections, just for new channels?

**Comment by Crypt-iQ** [comment]
I think the dependency can be removed and everything should just work

**Comment by C-Otto** [comment]
Without the dependency I'm now able to connect to 024271a1be2d7a3e2a276b241257be734d843885d252f50575e4c7db2691aedd3a (and others).

**Comment by Roasbeef** [comment]
The above PR should resolve things for now. However, we always want to use the explicit channel type stuff for zero conf negotiation. As a result, if the other peer doesn't support it, we'll fail out on the RPC level. Looks like CLN will start to set the feature bit now (given they actually understand/implement it): https://github.com/ElementsProject/lightning/pull/5455. With that in, everything "should just work" now.
