### ISSUE TITLE
Channel stuck on waiting close, cannot force close

### ISSUE THREAD

**Issue by LunarMooner** [lightningnetwork/lnd#6804]
### Background

My channel has been stuck for a long time on the waiting close state. I tried many solutions to force close it but nothing worked.

### Your environment

* version of `lnd`
 0.14.2-beta
* which operating system (`uname -a` on *Nix)
 Linux 52c60ea144c5 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux
* any other relevant environment details
 Umbrel 0.4.18

### Steps to reproduce

I closed the channel using Ride The Lightning app in Umbrel it worked for all my channels except one

### Expected behaviour

Channel should have closed and returned my sats

### Actual behaviour

It is stuck on waiting_close.

**Comment by positiveblue** [comment]
Hello @LunarMooner, couple of questions:

Could you provide some of the `many solutions to force close it but did worked`?

Are the funds stuck? or the channel was closed successfully on chain but LND does not reflect that properly?

Did you linked https://github.com/lightningnetwork/lnd/pull/1449 for some reason?

**Comment by LunarMooner** [comment]
@positiveblue

The main method I've tried was running `lncli closechannel --force` which always returns: `pc error: code = Unknown desc = server is still in the process of starting`
There was something else I tried a while ago but apologies I cannot remember the exact process.

The funds are stuck, the channel never closed successfully on chain from what I can tell.

Also I linked the item by accident due to formatting. I copy+pasted the output of uname -a amd there was a *hashtag*1449 there.

**Comment by positiveblue** [comment]
It looks like the rpc server is not up yet, do you mind restarting LND, unlocking the wallet and checking that the subserver starts properly? If `lncli closechannel --force` you should see in the startup logs some hints about what is going wrong in the subserver.

**Comment by positiveblue** [comment]
@LunarMooner any updates here?

**Comment by LunarMooner** [comment]
rpc server eventually started, I haven't had my node on in a while so it needed to resync with the chain as well which im assuming is potentially the reason it might not have been able to start. After starting I ran the closechannel command and the channel went from being in waiting_close_channels to pending_force_closing_channels and has been like that for a few hours.

**Comment by positiveblue** [comment]
Perfect, it looks like this was the problem. I will close this issue but do not hesitate to open a new one in case the force close does not go through (it should :+1:)
