### ISSUE TITLE
simnet: ListAccounts fails with unsupported key scope

### ISSUE THREAD

**Issue by bitromortac** [lightningnetwork/lnd#6807]
### Background
An issue came up in lndmon (https://github.com/lightninglabs/lndmon/issues/84), where a user could not start lndmon in `simnet` and the reason is an erroneous call to `ListAccounts` which errors with
```
WalletCollector ListAccountsfailed with: rpc error: code = Unknown desc = account default has unsupported key scope m/1017'/1'
```

### Steps to reproduce
I could reproduce it with a freshly initialized simnet (no blocks mined, make sure `walletrpc` is active). 

### Expected behaviour
`ListAccounts` should give back all accounts.

### Actual behaviour
`ListAccounts` fails because
https://github.com/lightningnetwork/lnd/blob/6060e05d7cbba138b91051529d8ffbfc1672ed54/lnrpc/walletrpc/walletkit_server.go#L1355
 falls through with internal scope of `m/1017'/115'` but `account.KeyScope` is `m/1017'/1'`, i.e., the `HDCoinType` is different.

**Comment by startimeahmet** [comment]
Is any workaround available for this yet?
