### ISSUE TITLE
queryroutes is running very slowly

### ISSUE THREAD

**Issue by joepalermo** [lightningnetwork/lnd#6808]
### Background

Running queryroutes is very slow on my node. It typically takes about ~10 seconds to query a route. In my lnd.conf I have ensured that db.no-graph-cache=false to ensure that graph caching is used. Not sure what else to try.

I have another LND node which takes < 1 second to run queryroutes so I know this can be a lot faster.

### Your environment

LND version: lnd version 0.15.0-beta commit=v0.15.0-beta
OS version: Linux *** 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:05:39 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
bitcoind version: Bitcoin Core RPC client version v23.0.0

**Comment by bitromortac** [comment]
Do you have a specific usage pattern, are you using the lncli or some other way to query routes? What hardware are you running on? Is the process (lnd) consuming lots of CPU cycles? What happens after a restart, is it faster generally? You could also see what effect `db.no-graph-cache=true` has.

**Comment by joepalermo** [comment]
Thanks @bitromortac 

**Do you have a specific usage pattern, are you using the lncli or some other way to query routes?**

I recently ran a large number of probes (i.e. failed payments). However, I made a modification to the lnd.conf to mitigate the influence of prior payment attempts (routerrpc.aprioriweight=1, see https://docs.lightning.engineering/lightning-network-tools/lnd/payments) and that didn't have an effect.

**What hardware are you running on?**

I think hardware should be sufficient to run queryroutes efficiently:

- ARM Cortex-A53 24-core CPU
- 32GB of RAM
- RAID 1 array of Samsung SSDs

**Is the process (lnd) consuming lots of CPU cycles?**

In a steady-state condition (i.e. not running an expensive command like queryroutes), LND doesn't consume much CPU, but when I run `lncli queryroutes` it uses a lot more.

**What happens after a restart, is it faster generally?**

No, it's the same.

**You could also see what effect db.no-graph-cache=true**

What would this tell us? I'm hesitant to restart LND unless I need to since sometimes my channels are force-closed upon restart.

**Comment by bitromortac** [comment]
We could record a profile/trace and see why the command takes so long to run. You would need to restart your node and set the profile port `profile=27362`. Adapt `lncli`, `seconds`, and `command` to your needs in the following script:

```bash
#!/bin/bash
# seconds should be larger than how long the command typically runs
seconds=15
lncli="/path/to/lncli"
# profport needs to be set in lnd.conf, e.g., profile=27362
profport=27362
command="queryroutes PUBKEY AMOUNT"

 # record a trace
$lncli $command > /dev/null &
curl http://localhost:$profport/debug/pprof/trace?seconds=$seconds --output test.trace
 
# record a profile
$lncli $command > /dev/null &
curl http://localhost:$profport/debug/pprof/profile --output test.prof
```

Would be great if you could share `test.prof` and `test.trace`, the files can be analyzed with `go tool trace test.trace` and `go tool pprof test.prof`.

Other stats that would be interesting and if you like to share them:

number of history pairs in mission control: 
`lncli querymc | grep history | wc -l`
Total number of payments:
`lncli listpayments --count_total_payments | grep total_num_payments`
Number of invoices:
`lncli listinvoices | grep r_hash | wc -l`

**Comment by joepalermo** [comment]
Thank you, but I am closing because I have moved on to using another pathfinding solution.
