### ISSUE TITLE
autopilot.allocation comment in sample-lnd.conf needs fixing

### ISSUE THREAD

**Issue by dooglus** [lightningnetwork/lnd#681]
lnd/sample-lnd.conf says:

    ; The percentage of total funds that should be committed to automatic channel
    ; establishment
    ; autopilot.allocation=0.6

I tried using that setting, and it allocated 60% of my funds, not 0.6%. Maybe the comment needs fixing?

**Comment by Roasbeef** [comment]
Ah yeh, `allocation` is the _fraction_ of coins that'll be committed.
