### ISSUE TITLE
Channel still stuck in force close, not releasing funds

### ISSUE THREAD

**Issue by LunarMooner** [lightningnetwork/lnd#6819]
Referring to Issue #6804

Channel has been stuck in pending_force_closing_channels for a few days and still has not released the funds. No longer sure what the solution is here.

**Comment by Roasbeef** [comment]
If you do `lncli pendingchannels` do you see a value there for the amount of blocks remaining? If that isn't zero, then teh funds are still time locked.

**Comment by LunarMooner** [comment]
"blocks_til_maturity": 264

is this what you mean?

**Comment by positiveblue** [comment]
It means that it was force closed by you and you can not make use of the funds until that number of blocks. The other party can challenge the force close if you did not use the latest state (tried to steal).

**Comment by LunarMooner** [comment]
Ahh I see, that's good to know. In that case I'll close the issue.

Thanks for the help, I'm still new to all this so still trying to figure it out :)
