### ISSUE TITLE
add a command line option to disable stdout and stderr

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#6828]
lnd has a log file that is written to that contains mostly the same (duplicate) information that is written to standard output and standard error. When running lnd as a systemd service, the systemd journal gets all of this information too from stdout and stderr. It would be nice to have a command line option that does not have the outputs written to standard output/error, only the lnd log file, this would avoid polluting the systemd journal with duplicate information. I'm aware that the log level can be changed, but I'd still like to capture more detailed information, I just don't necessarily want it going to the systemd journal too. When running on the command line, we can already redirect to /dev/null, but that's not as clean of an approach, especially when using systemd.

In bitcoind we have the -daemon option that does this silencing of standard output and standard error (since bitcoind also has its own dedicate log file) and also forks the process and puts it in the background. I'm not totally sure why bitcoind forks the process and sends it to the background, so I'm not sure if lnd wants to do this too. I don't see a particular advantage of it because then when running as a systemd service, lnd would need to communicate the pid to systemd so that it can keep track of whether it's actually running.

**Comment by guggero** [comment]
> would avoid polluting the systemd journal with duplicate information

See https://github.com/lightningnetwork/lnd/issues/5993

**Comment by AndySchroder** [comment]
Thanks for pointing me to some workarounds. Would still like to see this option available, but the workarounds can be used for now.

**Comment by Zetanova** [comment]
container users would need it reverse, to disable the internal local file log and only publish in the stdout / stderr 
Of course an option to publish to a proper external logging service would be nice to have too.

**Comment by ellemouton** [comment]
This is fixed by #9083 which introduces a new --logging.daemon-mode option to disable logs being written
to stdout and a new --logging.no-file option to disable writing logs to the standard log file.
