### ISSUE TITLE
"uris" in GetInfo returns wrong port

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#683]
I'm running "master" on Commit `dd08662c879bcee47a77acc2021702dec262999a`

GetInfo:
```
{
    "identity_pubkey": "020d58cde87fe71b5375b157b891116da9a01952fbaae14f863edfc28ab47da5ba",
    "alias": "",
    "num_pending_channels": 1,
    "num_active_channels": 4,
    "num_peers": 7,
    "block_height": 1260901,
    "block_hash": "0000000000000150c5b2dbf402b5c5acacc9f8ba72c2d19bbbb5fe6ab148074e",
    "synced_to_chain": true,
    "testnet": true,
    "chains": [
        "bitcoin"
    ],
    "uris": [
       
"020d58cde87fe71b5375b157b891116da9a01952fbaae14f863edfc28ab47da5ba@92.221.98.237:9735"
    ]
}

```
The startup ommand:
```
lnd \
    --noencryptwallet \
     --logdir=/data \
     --bitcoin.active --bitcoin.testnet --bitcoin.node=btcd --bitcoin.node=neutrino \
     --btcd.rpccert=/rpc/rpc.cert --btcd.rpchost=blockchain --btcd.rpcuser=lightningsale --btcd.rpcpass=lightningsale \
     --externalip=92.221.98.237 \
     --listen=0.0.0.0:9736 \
     --rpclisten=0.0.0.0:10009 \
     --restlisten=0.0.0.0:8080 \
     --debuglevel=debug \
     --neutrino.connect=faucet.lightning.community \
     --autopilot.active \
     --no-macaroons
```

`netstats`:
```
tcp6       0      0 :::8080                 :::*                    LISTEN      19671/lnd           
tcp6       0      0 :::10009                :::*                    LISTEN      19671/lnd           
tcp6       0      0 :::9736                 :::*                    LISTEN      19671/lnd 
```

**Comment by Roasbeef** [comment]
Worth noting that `9735` is the default port for the network, as many implementations assume this never changes, you may have connectivity issues for inbound peers. This is just a cosmetic defect.

**Comment by Roasbeef** [comment]
>      --no-macaroons      --restlisten=0.0.0.0:8080 \

This is a _very_ dangerous set up. You're listening on an external interface, yet have all authentication disabled. I'll be pushing out a commit soon that causes `lnd` to fail to start up if such a config combination is detected.

**Comment by Roasbeef** [comment]
>  --externalip=92.221.98.237

This is actually the issue. The URI parsing uses what was specified as an external IP address. 

Here's an example of a correct configuration: 
  * Starting `lnd` as: `./lnd --externalip=192.0.0.5:9090`

  * Then the response of `getinfo`: 
```
    "uris": [
        "036facb0f47608fe343aba4aeaab3e819ed7482b41f19c462294887e488f25d958@192.0.0.5:9090"
    ]

```

**Comment by Richard87** [comment]
Hi, thanks for looking into this!

Since I'm running LND in a closed (docker) network, how will that affect me?

My external ip is 92.221.98.237, and my peer port is 9736 (My ISP is blocking 9735 for some maintenance port :/ )

When I start LND in Docker, I only expose port 9736 to the outside, but I have to listen on the internal interface IP (172.18.0.0.4 or similar).

What is the relationship between "externalip" and "listen"?


Thanks for the heads up :) I am planning to start using Macaroons, just haven't gotten to it yet 👍
