### ISSUE TITLE
Slack invite is expired on the website

### ISSUE THREAD

**Issue by shellandbull** [lightningnetwork/lnd#6830]
### Background

Here's a video demonstrating the issue

![broken-slack-link](https://user-images.githubusercontent.com/3522106/184593038-b60ba995-061d-4391-8462-a6e8339c3b9f.gif)

**Comment by guggero** [comment]
Thanks for the report. Unfortunately those links expire after a while and after a certain number of people joined. Will make sure this is updated asap.

**Comment by guggero** [comment]
Should be fixed now. Please make sure to refresh the lightning.engineering website and try again.
