### ISSUE TITLE
Problem starting lnd: invalid magic in compressed pubkey

### ISSUE THREAD

**Issue by medisoft** [lightningnetwork/lnd#685]
`2018-01-28 11:30:54.847 [INF] LNWL: Started rescan from block 000000001bf6edc5014f07cf6de5bc52d20ade8617f192ab609362789571f622 (height 1260873) for 631 addresses
unable to read channel for chain_hash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000, node_key=0201d0feddc169f695493d4e8e27ddff537a43eaa7577984319f0f5e8615e689e6: unable to read channel data for chan_point=adba529feaceecdf33349c61bab28991d7945ffbb1cd6c301e934380dc20bd6b:0: unable to fetch chan info: invalid magic in compressed pubkey string: 1`

**Comment by halseth** [comment]
There has been a change in the database format. Please delete `channel.db` and try again.

**Comment by Roasbeef** [comment]
Alternatively, use `git reflog` to go back to the commit you were at before updating to master, close out all your channels, then roll forward to update.
