### ISSUE TITLE
Node shutting down because error in main method

### ISSUE THREAD

**Issue by 9414286** [lightningnetwork/lnd#6852]
### Background

I had power outage of my network storage with LND data folder (.lnd/data), so LND node lost connection to it, but continue to run. I restored power supply and restarted LND. After restart, node shutting down with error.

### Your environment

* version of `lnd`
0.15.0-beta commit=v0.15.0-beta
* which operating system (`uname -a` on *Nix)
Ubuntu
* version of `btcd`, `bitcoind`, or other backend
bitcoind 230000

`Version: 0.15.0-beta commit=v0.15.0-beta-146-g87f4f03fc, build=production, logging=default, debuglevel=info

2022-08-23 07:40:39.230 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-08-23 07:40:39.231 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2022-08-23 07:40:39.235 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2022-08-23 07:40:39.236 [INF] LTND: Opening the main database, this might take a few minutes...
2022-08-23 07:40:39.237 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=false
2022-08-23 07:40:39.593 [INF] LTND: Creating local graph and channel state DB instances
2022-08-23 07:40:39.868 [INF] CHDB: Checking for schema update: latest_version=29, db_version=29
2022-08-23 07:40:39.906 [INF] LTND: Database(s) now open (time_to_open=669.553511ms)!
2022-08-23 07:40:39.907 [INF] LTND: We're not running within systemd or the service type is not 'notify'
2022-08-23 07:40:39.907 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2022-08-23 07:40:58.325 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
2022-08-23 07:41:25.714 [INF] LNWL: Opened wallet
2022-08-23 07:41:25.763 [INF] CHRE: Primary chain is set to: bitcoin
2022-08-23 07:41:25.903 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
2022-08-23 07:41:25.903 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
2022-08-23 07:41:25.903 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
2022-08-23 07:41:26.498 [INF] LNWL: The wallet has been unlocked without a time limit
2022-08-23 07:41:26.518 [INF] CHRE: LightningWallet opened
2022-08-23 07:41:26.540 [INF] SRVR: Onion services are accessible via Tor! NOTE: Traffic to clearnet services is not routed via Tor.
2022-08-23 07:41:26.540 [INF] TORC: Starting tor controller
2022-08-23 07:41:26.823 [INF] HSWC: Cleaning circuits from disk for closed channels
2022-08-23 07:41:26.988 [INF] HSWC: Finished cleaning: num_closed_channel=36, num_circuits=0, num_keystone=0
2022-08-23 07:41:26.988 [INF] HSWC: Restoring in-memory circuit state from disk
2022-08-23 07:41:27.119 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
**2022-08-23 07:41:27.257 [ERR] LTND: Shutting down because error in main method: unable to create server: unable to read bucket for chain=616c6961732d6275636b6574**
2022-08-23 07:41:27.258 [INF] TORC: Stopping tor controller
2022-08-23 07:41:27.258 [ERR] TORC: DEL_ONION got error: invalid arguments: unexpected code
2022-08-23 07:41:27.258 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
2022-08-23 07:41:27.263 [INF] LTND: Shutdown complete`

**Comment by ellemouton** [comment]
Do you perhaps have the logs for the time at which the power outage happened? Would be useful to see how LND responded to that.

**Comment by 9414286** [comment]
> 

Sorry, I don't know, how logging work, so I can find only lnd.log contained logs after restart. And another file named lnd,log.1, that contain only one minute repeating message (while connection was lost):
`2022-08-22 13:13:16.442 [ERR] BTCN: Can't accept connection: accept tcp [::]:9735: accept4: too many open files`

**Comment by bhandras** [comment]
> > Do you perhaps have the logs for the time at which the power outage happened? Would be useful to see how LND responded to that.
> 
> Sorry, I don't know, how logging works, so I can find only lnd.log contained logs after restart. And another file named lnd.log.1, that contain only one minute repeating message (while connection was lost): `2022-08-22 13:13:16.442 [ERR] BTCN: Can't accept connection: accept tcp [::]:9735: accept4: too many open files`

Out of curiosity, what does `cat /proc/sys/fs/file-max` display to you? (Shows the number of allowed open files).

**Comment by 9414286** [comment]
> Out of curiosity, what does `cat /proc/sys/fs/file-max` display to you? (Shows the allowed max number of open files).
9223372036854775807

**Comment by guggero** [comment]
Also see https://github.com/lightningnetwork/lnd/issues/6231#issuecomment-1072213156

**Comment by ellemouton** [comment]
ok @9414286 , so next step would be to try a db compaction. You can do this either by turning on auto-compaction in LND by setting the `db.bolt-auto-compact=true` option. Or you can manually do it by using a tool like [`chantools compactdb`](https://github.com/guggero/chantools/blob/master/doc/chantools_compactdb.md). 

If after doing this you still get this error, then you will need to do an SCB recovery.

**Comment by 9414286** [comment]
> Also see [#6231 (comment)](https://github.com/lightningnetwork/lnd/issues/6231#issuecomment-1072213156)

I set `DefaultLimitNOFILE=1024000:5120000`, rebooted ubuntu, but result is the same: 
`2022-08-23 21:46:52.572 [ERR] LTND: Shutting down because error in main method: unable to create server: unable to read bucket for chain=616c6961732d6275636b6574`

**Comment by 9414286** [comment]
> > Also see [#6231 (comment)](https://github.com/lightningnetwork/lnd/issues/6231#issuecomment-1072213156)
> 
> I set `DefaultLimitNOFILE=1024000:5120000`, rebooted ubuntu, but result is the same: `2022-08-23 21:46:52.572 [ERR] LTND: Shutting down because error in main method: unable to create server: unable to read bucket for chain=616c6961732d6275636b6574`

`2022-08-23 22:40:11.016 [INF] LTND: Version: 0.15.0-beta commit=v0.15.0-beta-146-g87f4f03fc, build=production, logging=default, debuglevel=info
2022-08-23 22:40:11.016 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-08-23 22:40:11.016 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2022-08-23 22:40:11.018 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2022-08-23 22:40:11.018 [INF] LTND: Opening the main database, this might take a few minutes...
2022-08-23 22:40:11.018 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
2022-08-23 22:40:11.037 [INF] CHDB: Compacting database file at /mnt/synology/.lnd/data/graph/mainnet/channel.db
2022-08-23 22:40:59.654 [INF] LTND: Shutdown complete

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1614e]

goroutine 1 [running]:
go.etcd.io/bbolt.(*Bucket).Sequence(...)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:340
github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket.func1({0x7ff04d75b180, 0xc, 0xc}, {0x0?, 0x9e?, 0x9e?})
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:277 +0xee
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0008a16c0, 0xc0005e05e8)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0xa4
github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0xc0005e0eb0, 0xc0008a16c0, {0xc00075d1e8?, 0x1, 0x1}, {0x7ff0278fc2d4, 0x21, 0x21}, {0x0, 0x0, ...}, ...)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:273 +0x1cb
github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket.func1({0x7ff0278fc2d4, 0x21, 0x21}, {0x0?, 0x0?, 0x0?})
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:276 +0x148
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0008a0c80, 0xc0005e0788)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0xa4
github.com/lightningnetwork/lnd/kvdb.(*compacter).walkBucket(0xc0005e0eb0, 0xc0008a0c80, {0x0?, 0x0, 0x0}, {0x7ff00bc1f186, 0x10, 0x10}, {0x0, 0x0, ...}, ...)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:273 +0x1cb
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1.1({0x7ff00bc1f186, 0x10, 0x10}, 0xc0008a0c80)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:226 +0x145
go.etcd.io/bbolt.(*Tx).ForEach.func1({0x7ff00bc1f186, 0x10, 0x10}, {0x0?, 0x0?, 0x100e8?})
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:129 +0x63
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0004ae2b8, 0xc0005e0918)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0xa4
go.etcd.io/bbolt.(*Tx).ForEach(0xc0000fc880?, 0xc0000fc8a0?)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:128 +0x49
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1(0x0?)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:220 +0x4b
go.etcd.io/bbolt.(*DB).View(0xc0000fcac0?, 0xc0005e09f0)
        /home/vnc/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:772 +0x82
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk(0x0?, 0x0?, 0x0?)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:219 +0x46
github.com/lightningnetwork/lnd/kvdb.(*compacter).compact(0xc0005e0eb0, 0xc0000fc900, 0xc0005e0bb0?)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:147 +0x125
github.com/lightningnetwork/lnd/kvdb.(*compacter).execute(0xc0005e0eb0)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/bolt_compact.go:117 +0x6ea
github.com/lightningnetwork/lnd/kvdb.compactAndSwap(0xc0005e1298)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/backend.go:179 +0x74f
github.com/lightningnetwork/lnd/kvdb.GetBoltBackend(0xc0005e1298)
        /home/vnc/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.3.1/backend.go:101 +0x87
github.com/lightningnetwork/lnd/lncfg.(*DB).GetBackends(0xc000122000, {0x18775f8?, 0xc0004b0f00}, {0xc0006a6270, 0x25}, {0xc000519d70, 0x2d}, {0xc0006a62a0, 0x2e}, 0x1, ...)
        /home/vnc/go/src/github.com/lightningnetwork/lnd/lncfg/db.go:392 +0x1fd1
github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0xc0004d8dc8, {0x18775f8, 0xc0004b0f00})
        /home/vnc/go/src/github.com/lightningnetwork/lnd/config_builder.go:813 +0x325
github.com/lightningnetwork/lnd.Main(0xc00011aa00, {{0x0?, 0xc0000021a0?, 0x300000002?}}, 0xc000480cc0, {0xc00009b320, 0xc0000a6840, 0xc0000a68a0, 0xc0000a6900, {0x0}})
        /home/vnc/go/src/github.com/lightningnetwork/lnd/lnd.go:355 +0x1810
main.main()
        /home/vnc/go/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x205
`

**Comment by 9414286** [comment]
> ... then you will need to do an SCB recovery.

In my opinion, it is totally wrong way because it means, that you can't operate node at home because power outage is very common. I can't remember any case when any application or database was corrupted to zero by power outage (if HD wasn't damage). It have to be way to close one or couple LN "bad" channels, from SCB, but not all of them.
Another way is to tell the truth to the people: LN nodes are only for Industrial dataсenter, not for kitchens. So lightning will become a centralized service.

**Comment by ellemouton** [comment]
@9414286 , what hardware are you running on? both LND & data folder

**Comment by 9414286** [comment]
> @9414286 , what hardware are you running on? both LND & data folder
Thanks for truing to help. Main proccesor with LND daemon is I7+16gb memory+500gb HD, data folder in Synology RAID1 5TB+5TB (WD Red) (I added it after previous SCB with HD hardware problem). Synology shows me, that file system is ok.

**Comment by ellemouton** [comment]
unfortunately it does seem like SCB is your best option here. From the error you have posted, there is clearly some db corruption that occurred. Perhaps in future, consider using a Postgres backend as well as investing in a UPS.

**Comment by 9414286** [comment]
> unfortunately it does seem like SCB is your best option here. From the error you have posted, there is clearly some db corruption that occurred. Perhaps in future, consider using a Postgres backend as well as investing in a UPS.

I already have two UPS (LND node have way more lifetime than Synology ). It sounds very sad, because I thought I invested enough to prevent SCB. Maybe it is a good reason to give up with Lightning after 3,5 years of operating. Thank you for your help.
