### ISSUE TITLE
Conflicting last hop information for self-payment

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6865]
I have a historic (June 9th 2022) self-payment, i.e. created an invoice and paid it myself (both from the same node). At the time of this self-payment, I had (at least) two open channels to peer from which I received the payment, i.e. I increased the outbound liquidity to that peer and reduced it somewhere else.

The invoice information contains a single HTLC entry and `lncli lookupinvoice xxx | jq -r ".htlcs[].chan_id"` gives me channel ID `A`.

The payment information contains a single route with three hops, where `lncli trackpayment --json xxx | jq -r ".htlcs[].route.hops[-1].chan_id"` gives me the channel ID used for the last hop (channel `B`).

The bug is that the IDs `A` and `B` are different (but both correspond to the channels I, at that time, had to the expected peer). 
As I'd like to use this information to differentiate self-payments from regular payments, this messes up my accounting. I believe that the information should correspond to reality, i.e. indicate which channel actually served the final HTLC.

**Comment by C-Otto** [comment]
Closing, thanks to https://twitter.com/positiveblue2/status/1563579042250788865.

The paying party doesn't know which channels are used, the route just contains suggestions. Each peer along the route is free to pick any channel, even private ones. There's no feedback to the payer, and as such the actual route taken (which includes the last hop) may be different from the route specified in the payment.

**Comment by guggero** [comment]
The term for this is "non-strict forwarding", see the BOLTs for more information: https://github.com/lightning/bolts/blob/master/04-onion-routing.md#non-strict-forwarding
