### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by varg-finance** [lightningnetwork/lnd#6869]
### Background

LND-Process is shutting down

### Your environment

0.15.0-beta, now 0.15.1-beta.rc2 (pre-compiled binary from the release)
ubuntu amd64 (fully updated)
bitcoind v23.0.0
dedicated Intel Core-i7, 32Gb RAM, 1Tb SSD
node's age: 2+ months
RTL 0.12.3-beta
BOS 12.16.3

### Steps to reproduce

During operation, LND went offline and did not restart again.

### Expected behaviour

Start LND

### Actual behaviour

LND did not start

● lnd.service - LND Lightning Network Daemon
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-08-29 22:53:47 MSK; 29s ago
    Process: 20086 ExecStart=/usr/local/bin/lnd (code=exited, status=2)
   Main PID: 20086 (code=exited, status=2)
        CPU: 4.207s

Update LND (0.15.0-beta --> 0.15.1-beta.rc2) and upgrade entire Ubuntu to the latest versions has no effect.
The problem appeared suddenly, no changes were made (settings, restarts or something else) - process just crashed without any apparent reason and did not restart again.

Log file in attachment.
[log.txt](https://github.com/lightningnetwork/lnd/files/9447653/log.txt)

I will be grateful for any advice.

UPD: interesting in log file, "[INF] LNWL: Removed invalid transaction" repeats every restart with the same transaction...

**Comment by Crypt-iQ** [comment]
@yyforyongyu

**Comment by yyforyongyu** [comment]
Could you turn on debug or trace log and share the logs again?

**Comment by Roasbeef** [comment]
Related to https://github.com/lightningnetwork/lnd/pull/6624?

**Comment by varg-finance** [comment]
@yyforyongyu , of course. Debug log in attachment.
[log_debug.txt](https://github.com/lightningnetwork/lnd/files/9450335/log_debug.txt)

**Comment by Crypt-iQ** [comment]
are you running any node management software like RTL/lndg/etc?

**Comment by Crypt-iQ** [comment]
Have you recently changed your BOS version?

**Comment by varg-finance** [comment]
No. My configuration hasn't changed in two+ weeks.

**Comment by Crypt-iQ** [comment]
- When did lnd go offline, did it panic or did you simply just shut it down normally?
- Have you previously used a different BOS version?
- What was your configuration like when lnd went down the first time?

**Comment by varg-finance** [comment]
1) panic. like after every restart now.
2) yes. last update of BOS I made around... 3-4 weeks ago.
3) after first time I updated LND (0.15.0-beta --> 0.15.1-beta.rc2) and all Ubuntu packages via apt. BOS, RTL, bitcoind stay untouched for now.
4) no.
5) mostly basic functionality:
RTL) open/close channels, adjust fees, acquire statistics (reports), circular payments (rebalance), generating onchain-addresses, reconnect peers
BOS) telegram integration, opening balanced channels, rebalance, reconnect peers, tags management (for rebalance nodes avoiding)... ...perhaps that's all.

**Comment by Crypt-iQ** [comment]
> 1. panic. like after every restart now.

The very first time it went down, it was a panic?

> 2. yes. last update of BOS I made around... 3-4 weeks ago.

do you know the version you were on before that?

**Comment by varg-finance** [comment]
`The very first time it went down, it was a panic or did you stop it and then couldn't start again?`
Panic. I did not anything absolutely at this moment and many hours before.

`do you know the version you were on before the update?`
It's hard to say exactly, but not less 12.13.x. I guess... 12.13.4.

**Comment by Crypt-iQ** [comment]
Gotcha, and you were on BOS 12.16.3 at the time of the initial crash?

**Comment by varg-finance** [comment]
Yes, exactly.

**Comment by Crypt-iQ** [comment]
For RTL, how are you reconnecting to your peers? Is there a button or some API call that you are using?

**Comment by varg-finance** [comment]
I choose peer (with disabled channel usually), click on "disconnect" (message "peer disconnected successfully"), thereafter press "connect to peer" and enter publicKey or publicKey@address.port . If peer connected ok, the channel often becomes active.

If peer is not connected (not in the list), i try to connect it.

I think, this GUI uses lincli disconnect/connect.

**Comment by Crypt-iQ** [comment]
- How quickly after "disconnect" does it take you to press "connect to peer" and enter in the info?
- Did you tend to route a lot of HTLC's?

**Comment by varg-finance** [comment]
1) Well... I don't wait anything... Seconds, obviously. 
2) My maximum is 80-90 HTLC's, but it happened very rarely (not every day at least), average value is 30-40. Sometimes 10, sometimes 50, average - 30-40. High values usually don't last long, minutes, thereafter it goes down pretty fast.

**Comment by Crypt-iQ** [comment]
> 1. Well... I don't wait anything... Seconds, obviously. How much time between two mouse clicks : )

Yeah just double-checking, the timing matters here

> 2. My maximum is 80-90 HTLC's, but it happened very rarely (not every day at least), average value is 30-40. Sometimes 10, sometimes 50, average - 30-40. High values usually don't last long, minutes, thereafter it goes down pretty fast.

Is that 30-40 avg / day?

**Comment by varg-finance** [comment]
30-40 avg simultaneously. At one moment. I open RTL ("active HTLCs") and see there count, which is usually 30-40.
How many per day... I don't know.

**Comment by varg-finance** [comment]
Сan I try something maybe? Save backups and change something? Second day of node offline is so painful... Expired HTLCs, automatic force-closes of many good channels...

However, if it is not safe, there is no choice. Anyway, I am very grateful for the help and assistance in this situation...

**Comment by Crypt-iQ** [comment]
@yyforyongyu do you mind rebasing your PR on top of 0.15.1?

That way @varg-finance can apply https://github.com/lightningnetwork/lnd/pull/6624 and use other channels. The patch isn't tested on a live node afaik. You may be able to close the channel point in question without error, not sure.

**Comment by Crypt-iQ** [comment]
Actually, if you end up using that patch when it's ready, I don't think you should try to close the buggy channel point - it might lead to a similar situation. If you have issues with that patch (lnd not starting up, but the panic is gone), we can give you a temporary one on top of that one.

**Comment by varg-finance** [comment]
Ok. I am ready to provide you all the logs or other information and won't do anything without your approval.

**Comment by Roasbeef** [comment]
Here's the branch rebased: https://github.com/lightningnetwork/lnd/compare/v0.15.1-branch...Roasbeef:lnd:remote-log-rebase?expand=1

Can clone from: https://github.com/Roasbeef/lnd/tree/remote-log-rebase

**Comment by varg-finance** [comment]
Unfortunately, it seems like I need some help with installation. I always used ready binary file in releases before, sorry for wasting your time : (

1) I try to clone https://github.com/Roasbeef/lnd/tree/remote-log-rebase via HTTPS (`git clone https://github.com/Roasbeef/lnd.git`). Installation failed:

![1](https://user-images.githubusercontent.com/98950624/187634980-c2e74225-5e24-4d9a-ba2c-fd871bd68f78.png)

2) I try to download zip-file, unzip it and install. Also unsuccessful:

![2](https://user-images.githubusercontent.com/98950624/187635585-690f346d-dd61-400d-afb9-68856e94d926.png)

I understand that I make the simplest mistakes, but I need assistance...

I have go version go1.18 linux/amd64.

**Comment by varg-finance** [comment]
@yyforyongyu , something goes wrong again...

![3](https://user-images.githubusercontent.com/98950624/187648846-43ca0752-c986-413f-b65c-3296cb508757.png)

...nothing changed... behavior of LND remains the same.

Fresh debug log:
[new 1.txt](https://github.com/lightningnetwork/lnd/files/9460453/new.1.txt)

**Comment by guggero** [comment]
`make install` will put the binary in your `$GOPATH/bin` directory. So look for an `lnd` binary there, and put your `$GOPATH/bin` to your `$PATH`.

**Comment by varg-finance** [comment]
Finally, lnd version 0.15.1-beta commit=v0.3-alpha-11443-g5cbdcde5e !

LND started, works as normal for 1-2 minutes, thereafter shutdown (NOT panic) from this line:

2022-08-31 13:11:21.152 [ERR] CNCT: ChannelArbitrator(67d1c841ad1ff92666ec3829f8c18d57b3fda89b8ba37bc71c2eca2731ce8675:0): unable to force close: No HTLC with ID 670 in channel 750573:1517:0
2022-08-31 13:11:21.152 [ERR] CNCT: ChannelArbitrator(67d1c841ad1ff92666ec3829f8c18d57b3fda89b8ba37bc71c2eca2731ce8675:0): unable to advance state: No HTLC with ID 670 in channel 750573:1517:0
2022-08-31 13:11:21.152 [INF] CNCT: ChainArbitrator shutting down

full log:
[log 3.txt](https://github.com/lightningnetwork/lnd/files/9460619/log.3.txt)

**Comment by varg-finance** [comment]
After another reboot Node works much longer than usual, and do some work before fail again.

As far as I can tell, this time it's for some other reason.

full log:
[log 4.txt](https://github.com/lightningnetwork/lnd/files/9461341/log.4.txt)

I will try to restart Node from time to time.

**Comment by yyforyongyu** [comment]
@varg-finance could you add this debug config to your node `--debuglevel=debug,LNWL=trace` and start it again?

**Comment by varg-finance** [comment]
@yyforyongyu, yes, of course. Just few minutes.

**Comment by varg-finance** [comment]
LNWL trace log:
[log 5.txt](https://github.com/lightningnetwork/lnd/files/9461464/log.5.txt)

**Comment by Crypt-iQ** [comment]
This is what I mentioned in chat and briefly glossed over above, the contractcourt is not able to advance state here and will be stuck unless we give another patch @yyforyongyu - `ForceCloseChan` is calling `NewLightningChannel` on startup. Startup is the only place that the `advanceState` error is used and will prevent lnd from starting up

**Comment by yyforyongyu** [comment]
@varg-finance  Could you apply this PR and restart again? It adds more trace logs.

https://github.com/lightningnetwork/lnd/pull/6624

**Comment by varg-finance** [comment]
@yyforyongyu , done.

lnd 0.15.1-beta commit=v0.3-alpha-11443-g5cbdcde5e-dirty with #6624 
debuglevel=debug,LNWL=trace

[log 6.txt](https://github.com/lightningnetwork/lnd/files/9462316/log.6.txt)

**Comment by varg-finance** [comment]
Sorry for disturbing again, but I have a question. Does it make sense to ask a counterparty of problem channel to force-close it? Сould it be beneficial or undesirable?

I really want to shorten the offline period : )

**Comment by Crypt-iQ** [comment]
It wouldn't help here unless we give you yet another patch

**Comment by yyforyongyu** [comment]
@varg-finance are you on slack or keybase or anything?

**Comment by varg-finance** [comment]
@yyforyongyu , twitter, telegram ( both - @SunnySarahNode ). but I'm ready to create account in any other service.

**Comment by legalizemath** [comment]
fyi very similar situation and errors on v0.14.2-beta as I commented here w/ log, don't mind updating but I haven't seen that work for anyone in either thread yet

https://github.com/lightningnetwork/lnd/issues/6617#issuecomment-1266050501

interestingly similar "Removed invalid transaction" shortly before error too where all the inputs are already spent according to mempool

sidenote: if can figure out what channel id it is causing issue out of ~200, is there something like chantools forceclose for a single channel (that one seems to do all of them) so can just get rid of it with chantools removechannel and be able to actually start lnd again for rest of them? i can't exactly run single channel scb from lncli since it's unavailable bc of this issue

**Comment by legalizemath** [comment]
successfully recovered my node using above method

I was using docker images for lnd which didn't have the "dirty" commit print outs to tell me which channel state wasn't able to advance in but based on provided logs I noticed it's likely the last one with remaining (non-zero) "local updates that the peer should sign" and setting logging to `debug` level I purged the channel that had the following output

```
2022-10-06 17:26:04.413 [DBG] LNWL: ChannelPoint(f66299a97128bd4f27f8c1bb36f7e9d0edb732a765ec53033df44b2f4dc0e4b9:1): Restoring 7 local updates that the peer should sign
```

then I used chantools to purge that channel from db (after peer force closed it) and it booted and works perfectly again

hope this helps anyone else stuck until problem is fixed

**Comment by yyforyongyu** [comment]
Fyi, wrote a [report](https://gist.github.com/yyforyongyu/d345ac4a9bca0740c1c23947214e5768) on this.

**Comment by varg-finance** [comment]
Update. I don't have this problem anymore. 

I applied suggested patch, wait for the channel with "broken" HTLC to force-close, updated LND to the latest version and after that, the problem didn't reoccur.

Thanks to the whole development team, especially to @yyforyongyu !
