### ISSUE TITLE
node backend does not support taproot

### ISSUE THREAD

**Issue by hihouhou** [lightningnetwork/lnd#6872]
### Background

with v0.15.1-beta update

### Your environment

* `lnd` v0.15.1-beta
* `btcd` 0.22.0-beta
* debian 11.2

### Steps to reproduce

just start lnd

### Expected behaviour

lnd up

### Actual behaviour

lnd                   | 2022-08-30 22:35:21.841 [ERR] LTND: unable to create partial chain control: node backend does not support taproot
lnd                   | 2022-08-30 22:35:21.841 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: node backend does not support taproot
lnd                   | 2022-08-30 22:35:21.864 [INF] LTND: Shutdown complete
lnd                   |
lnd                   | error creating wallet config: unable to create partial chain control: node backend does not support taproot

### on your doc :
https://github.com/lightningnetwork/lnd/pull/6798. https://github.com/lightningnetwork/lnd/pull/6826, the officially supported versions of bitcoind are: 21, 22, and 23.
nothing about btcd ?

**Comment by Roasbeef** [comment]
You want this version for btcd: https://github.com/btcsuite/btcd/releases/tag/v0.23.1

Which docs are you referring to?

**Comment by positiveblue** [comment]
For what I see there have been more version tagged in `btcd` but there is no official releases of them? `0.22.0-beta` is from last year so for sure does not have the taproot changes included. Latest one is `v0.23.1` which is taproot compatible. I do not remember when it was included `v0.22.1` or `v0.23.0` @Roasbeef

**Comment by hihouhou** [comment]
the release was updated 1 mn ago :-) I 'm testing

**Comment by hihouhou** [comment]
btcd@btcd:/opt/btcd$ ./bin/btcd --version
btcd version 0.23.1-beta

but same error, I don't see any option about taproot, am I blind ?

**Comment by hihouhou** [comment]
> You want this version for btcd: https://github.com/btcsuite/btcd/releases/tag/v0.23.1
> 
> Which docs are you referring to?

https://github.com/lightningnetwork/lnd/blob/v0.15.1-beta.rc1/docs/release-notes/release-notes-0.15.1.md

**Comment by hihouhou** [comment]
reminder for me, never update a server before sleeping 🤣

**Comment by positiveblue** [comment]
What is the output for `client.GetBlockChainInfo()` when you hit your btcd (v0.23.1) server? Doesn't it include `taproot` under `resp.SoftForks.Bip9SoftForks` ?

**Comment by hihouhou** [comment]
weird with getblockchaininfo method ->` {"jsonrpc":"1.0","result":null,"error":{"code":-32603,"message":"limited user not authorized for this method"},"id":"1"}`
I don't find anything on https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md#JSONAuth
but curl works because getinfo : 
```
{
  "jsonrpc": "1.0",
  "result": {
    "version": 230100,
    "protocolversion": 70002,
    "blocks": 751931,
    "timeoffset": -1,
    "connections": 8,
    "proxy": "",
    "difficulty": 28351606743493.773,
    "testnet": false,
    "relayfee": 1e-05,
    "errors": ""
  },
  "error": null,
  "id": "1"
}

```

**Comment by hihouhou** [comment]
found!!! I used rpclimited creds....with rpcuser  creds it's up ! is it ok about my solution ?

**Comment by positiveblue** [comment]
It looks ok, taproot key is there so lnd `v0.15.1-beta` should not complain about it :eyes: 

Does it still complain after restarting it pointing to the btcd version `0.23.1-beta`?

**Comment by hihouhou** [comment]
only ok with not rpclimiteduser but rpcuser, you saved my sleep and my server, thank you for the support
