### ISSUE TITLE
failed to load config: bool flag `--db.prune-revocation' cannot have an argument

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#6884]
### Background

0.15.1-beta release notes (https://github.com/lightningnetwork/lnd/releases/tag/v0.15.1-beta) states:

> The migration can be activated with a new CLI command: --db.prune-revocation=true

Though in reality it produces error:

```
Sep 04 19:10:50 odroid-hc1 lnd[9864]: bool flag `--db.prune-revocation' cannot have an argument
Sep 04 19:10:50 odroid-hc1 lnd[9864]: failed to load config: bool flag `--db.prune-revocation' cannot have an argument
Sep 04 19:10:50 odroid-hc1 systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
```

Removing `=true` makes it work.

### Your environment

* `0.15.1-beta`
* `Linux odroid-hc1 5.18.0-0.deb11.4-armmp-lpae #1 SMP Debian 5.18.16-1~bpo11+1 (2022-08-12) armv7l GNU/Linux`
* `bitcoind v23.0`

### Steps to reproduce

Launch `lnd` with `--db.prune-revocation=true` as specified in release notes.

### Expected behaviour

Documentation should be correct :)

### Actual behaviour

Documentation is not correct.

**Comment by refazi** [comment]
Got the same issue, @Talkless are you running the umbrel compiled docker?

**Comment by positiveblue** [comment]
Fixed, thank you for bringing it up. The config files needs the `prune-revocation=true` or `prune-revocation=1` so we put it wrong in the cli param :+1:

**Comment by Talkless** [comment]
@refazi no, I am running on manually-setupped Debian ARM SBC.

**Comment by Talkless** [comment]
@positiveblue wait, so we "must" set this parameter permamently in config file? I thought this was a single-use run to clean things up?

**Comment by Talkless** [comment]
OK got it, thanks @saubyk ! Migration was done on my node, and I just removed that flag from system unit file.
