### ISSUE TITLE
/v2/invoices/lookup?payment_hash={payment_hash}  returns error when payment_hash contains certain characters

### ISSUE THREAD

**Issue by Takayuki-Suzuki** [lightningnetwork/lnd#6909]
### Background

I'm trying to create invoice and check its status through the REST API.

### Your environment

* version of `lnd`: v0.15.1-beta
* which operating system (`uname -a` on *Nix): Linux umbrel 5.10.103-v8+ 1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core RPC client version v23.0.0
* any other relevant environment details

### Steps to reproduce
Call lookup API with payment_hash parameter that includes "/" or "+".
The result doesn't change even though url-encoding the parameter.

```
curl -X GET https://umbrel.local:8080/v2/invoices/lookup?payment_hash=gcsVYT4KkXhc\+alSonnlsx/oOP8ZXHmDJOwcADSu4fA= -H "Grpc-Metadata-macaroon: $(cat macaroon.txt)" --cacert tls.cert
```

```
curl -X GET https://umbrel.local:8080/v2/invoices/lookup?payment_hash=gcsVYT4KkXhc%2BalSonnlsx/oOP8ZXHmDJOwcADSu4fA%3D -H "Grpc-Metadata-macaroon: $(cat macaroon.txt)" --cacert tls.cert
```

### Expected behaviour
Returns invoice data.
https://api.lightning.community/?python#v2-invoices-lookup

### Actual behaviour
Returns error.
`{"code":3, "message":"parsing field \"payment_hash\": illegal base64 data at input byte 12", "details":[]}`

**Comment by positiveblue** [comment]
I think you need to scape the characters in the terminal or use  quotes  `"`

**Comment by guggero** [comment]
Actually, you'll need to use base64 URL safe encoding (different alphabet than normal base64).

**Comment by Takayuki-Suzuki** [comment]
Ah ok, I did something like this and it works now. Thanks!

```python
payment_hash = base64.urlsafe_b64encode(base64.b64decode(payment_hash)).decode()
```
