### ISSUE TITLE
Allow to reserve coop-close for currently offline peers and/or with pending htlcs, up to `timeout` period

### ISSUE THREAD

**Issue by GordianLN** [lightningnetwork/lnd#6911]
### Background

I just learnt that cln allows to request a coop close for an offline peer, that will be actioned as soon as the peer comes back online, depending on a set timeout (if 0, wait indefinitely) ending which, the coop-close request will turn into a force close. Same goes with pending htlcs, the coop-close feature will disable all routing and wait for pendings to resolve, then issue the coop close.
This is something missing from lnd, and that is not present as feature request in the issues, at least as far as my search went (closest I found, is "coop close pending open channel").

### Your environment

not relevant 

### Steps to reproduce

not relevant

### Expected behaviour

Add a configurable timeout (lnd.conf or as cli paramenter) to set a user-configured timeout, and have the above behaviour available

### Actual behaviour

Currently this feature is not available

**Comment by MangoTreeNode** [comment]
Thumbs up for this.

**Comment by Bitcoinite** [comment]
Yes, please!

**Comment by Roasbeef** [comment]
Fixed by #8167
