### ISSUE TITLE
FundPsbt: allow P2TR change outputs and decorate them correctly

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#6918]
### Background

Currently the key scope used for creating change outputs in `FundPsbt` is dependent on the account name/number passed in. Since the `default` account is the only one that allows us to fund with any available input (NP2WKH, P2WKH, P2TR), we only use that one.
But the fall back key scope for the `default` account is defined as [BIP-84 here](https://github.com/btcsuite/btcwallet/blob/master/wallet/createtx.go#L357) we only get P2WKH change addresses.

In addition to allowing P2TR change outputs to be created, we also need to query the internal public key for the generated change output and add it to the `PSBT_OUT_TAP_INTERNAL_KEY` field of the output in the funded PSBT.

**Comment by antonilol** [comment]
`lncli sendcoins` also creates p2wpkh change addresses, even when sending to and from a taproot address

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/7528
