### ISSUE TITLE
--value=10000 should be --amt 10000

### ISSUE THREAD

**Issue by starrymoonlight** [lightningnetwork/lnd#694]
On page https://github.com/lightninglabs/lightning-dev-site/blob/master/tutorial/01-lncli.md

This: bob$ lncli-bob addinvoice --value=10000
should read: bob$ lncli-bob addinvoice --amt 10000

**Comment by ckcollab** [comment]
What about the other occurrences of `--value`? I created a PR for the 2 I saw, if you find any others let me know and I'll add them to my PR :)

**Comment by starrymoonlight** [comment]
Will keep an eye out.

**Comment by MeshCollider** [comment]
Closing this as its an issue for the lightning-dev-site repo not this one, please open issues in the correct repo :)
