### ISSUE TITLE
doc: improve log message of `openchannel --local_amt 0 --psbt`

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#6943]
A psbt funding flow with local amount of `0` is giving unexpected error message(although it makes sense).
```
lnclit openchannel --node_key xxx --local_amt 0 --psbt

Error received: got error from server: rpc error: code = Unknown desc = amount pushed to remote peer for initial state must be below the local funding amount
```

Maybe its better to explicitly state that the local amount needs to be >0.

**Comment by Schiocco** [comment]
I agree. For newbies like me it creates confusion
