### ISSUE TITLE
"Invalid address or key" when attempting to openchannel

### ISSUE THREAD

**Issue by capitalistdog** [lightningnetwork/lnd#6951]
### Background

This is an upgraded 15.1 node with existing channels and chain balances, including pending force closes

Using a `btcd` direct backend that was upgraded to 22 as required

When attempting to open a channel, it fails with:

`[lncli] rpc error: code = Unknown desc = -5: Invalid address or key: bc1p...`

Same result with defaults or specifying anchors as chan type.

Addresses in error do not appear to be UTXO's in the chain wallet

### Your environment

* version of `lnd`: 15.1
* which operating system (`uname -a` on *Nix) Ubuntu / 5.4.41-1
* btcd22

### Steps to reproduce

Production node balances on 15.1

### Expected behaviour

Channel should open and show a txid

### Actual behaviour

Complains about UTXO key

**Comment by capitalistdog** [comment]
Noticed that the "pending" force closes show a blocks till maturity as a negative number. Should be able to access those funds but can't... relevant?

**Comment by positiveblue** [comment]
`lnd v0.15.1-beta` needs to use a bitcoin node that supports taproot. In btcd that is [v0.23.1-beta](https://github.com/btcsuite/btcd/releases/tag/v0.23.1)

**Comment by positiveblue** [comment]
Yes, it [should have not started](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.15.1.md#taproot) :eyes:

Did you build master or it really was [v0.22.0-beta](https://github.com/btcsuite/btcd/releases/tag/v0.22.0-beta)

**Comment by guggero** [comment]
I think because Neutrino only connects on the P2P layer and not through RPC the same check cannot be used. I guess we could parse the announced version in P2P but I don't think we currently do that.

**Comment by capitalistdog** [comment]
I had been running v20, but it nagged so I updated to v22 (tagged binary) and it satisfied it

Getting an updated Go to work is always an adventure, will report back if I ever manage to generate a btcd binary from master.

**Comment by capitalistdog** [comment]
Just realized I confused this node with another, it is *NOT* a neutrino back end... It uses btcd directly

**Comment by positiveblue** [comment]
Just to clarify, `v22` means `[btcd v0.22.0-beta](https://github.com/btcsuite/btcd/releases/tag/v0.22.0-beta)`

To make sure that we are not talking about bitcoind, which went from `[bitcoind v0.21.1-beta](https://github.com/bitcoin/bitcoin/releases/tag/v0.21.1)` to [bitcoind v22.0-beta](https://github.com/bitcoin/bitcoin/releases/tag/v22.0)

**Comment by Roasbeef** [comment]
You need to be using btcd v23.1.

**Comment by capitalistdog** [comment]
> Just to clarify, `v22` means [btcd v0.22.0-beta](https://github.com/btcsuite/btcd/releases/tag/v0.22.0-beta), right?
> 
> Just to be sure that we are not talking about bitcoind, which went from [bitcoind v0.21.1-beta](https://github.com/bitcoin/bitcoin/releases/tag/v0.21.1) to [bitcoind v22.0-beta](https://github.com/bitcoin/bitcoin/releases/tag/v22.0)

confirm btcd...

Getting to 23 is proving a challenge because it requires a newer glibc which means an OS upgrade... might be a bit to confirm. 

This is the same neutrino instance powering the node with this issue, so likely related: https://github.com/lightningnetwork/lnd/issues/6938#issuecomment-1259756947

Would be nice to have a workaround: https://github.com/lightningnetwork/lnd/issues/6922

**Comment by guggero** [comment]
> Getting to 23 is proving a challenge because it requires a newer glibc which means an OS upgrade... might be a bit to confirm.

What do you mean by "requires a newer glibc"? If you're talking about `btcd`, I don't think you need anything other than Golang to compile. Or are you compiling Golang from source as well?

**Comment by capitalistdog** [comment]
> > Getting to 23 is proving a challenge because it requires a newer glibc which means an OS upgrade... might be a bit to confirm.
> 
> What do you mean by "requires a newer glibc"? If you're talking about `btcd`, I don't think you need anything other than Golang to compile. Or are you compiling Golang from source as well?

I got it compiled but it won't start. citing:

```
Sep 27 19:10:12 neutrino btcd[19214]: /root/btcd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/btcd)
Sep 27 19:10:12 neutrino btcd[19214]: /root/btcd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/btcd)
```

**Comment by guggero** [comment]
Ah, that sounds like a `cgo` problem. Try disabling that with `CGO_ENABLED=0 make install`. See https://community.tmpdir.org/t/problem-with-go-binary-portability-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-32-not-found/123

**Comment by guggero** [comment]
If the DNS issue mentioned in the link above becomes an issue, try adding `GODEBUG="netdns=cgo"` to your env as well.

**Comment by guggero** [comment]
I created a PR to make this easier, see https://github.com/btcsuite/btcd/pull/1890.
You basically want to run what's in `release-install`: `env CGO_ENABLED=0 go install -v  -trimpath -ldflags="-s -w -buildid=" github.com/btcsuite/btcd`

**Comment by capitalistdog** [comment]
Awesome, got it built with CGO disabled... 

Peer I was opening to is offline now of course... grabbing another...

**Comment by capitalistdog** [comment]
Was able to create a channel with 15.1 client, thank you very much @guggero for the extended support.
