### ISSUE TITLE
Expose the new interface as part of the set of defined `DatabaseInstances`. This'll allow projects that "wrap" lnd to pass in their own custom implementations, which may use a different DB backend all together.

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6954]

**Comment by Roasbeef** [comment]
A sub step would be to first eliminate the main channeldb pointer in the invoice registry, original comment:
https://github.com/lightningnetwork/lnd/issues/6842

**Comment by saubyk** [comment]
addressed by:
https://github.com/lightningnetwork/lnd/pull/7215
