### ISSUE TITLE
docker lnd service does not have a data volume

### ISSUE THREAD

**Issue by Osso** [lightningnetwork/lnd#696]
Currently the docker-compose.yml for the lnd service:
    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

There's no volume defined for the data dir. That means all the keys are lost when recreating the container.

 I am adding a --data-dir=/data and making /data a volume in the proposed merge request. That /data also contains the logs.

**Comment by Richard87** [comment]
Hi!

Re: lncli and config-file, could we make *all* configuration options available via environement variables?

So the config would be loaded in this order (top first):

 1. Default config
 2. config file (if found in default location, OR in LND_CONFIG_FILE env variable)
 3. environment
 5. command line options 

The last line overrides the first item (command-line options are never overwritten)

**Comment by tyzbit** [comment]
@Osso I would suggest manually "shimming" in a volume from local storage if you need to preserve it ( `-v /local/path:/root`, I think.)

@Richard87 I think #1164 satisfies your need of having all configuration options available via ENV variable.

**Comment by Roasbeef** [comment]
Closed due to #1164.
