### ISSUE TITLE
listpayments returns error "payment isn't initiated"

### ISSUE THREAD

**Issue by xmrk-btc** [lightningnetwork/lnd#6964]
### Background

```
$ ~/go/bin/lncli listpayments
[lncli] rpc error: code = Unknown desc = payment isn't initiated
```

This issue prevents me from getting statistics about my rebalancing. For example, Ride the Lightning just displays:
![image](https://user-images.githubusercontent.com/62961693/193449749-34433168-a3f0-4b61-9768-c1acd518255c.png)

When I add --max_payments, it seems to work, but I tried to process it in a script and  remember some problems with order, probably the payments were not ordered at all - this was around a year ago. But I do not see that problem now, the indexes are ordered:
```
$ ~/go/bin/lncli listpayments --max_payments 10|grep payment_index
            "payment_index": "728130",
            "payment_index": "728226",
            "payment_index": "728263",
            "payment_index": "728264",
            "payment_index": "728267",
            "payment_index": "728586",
            "payment_index": "728884",
            "payment_index": "728978",
            "payment_index": "729510",
            "payment_index": "729607",

$ ~/go/bin/lncli listpayments --max_payments 10|grep offset
    "first_index_offset": "728130",
    "last_index_offset": "729607",
```

### Your environment

* lnd 0.15.1
* raspberry pi 4, arm64
* bbolt db
* --db.prune-revocation applied

### Steps to reproduce
I got into this state (where listpayments does not work as explained above) by doing lncli deletepayments, probably with --include_non_failed . But this was around a year ago, so not sure. I tried to reproduce it with lnd 0.15.1 on my another testing node, which had 3 or 4 payments in its db, but not successful. 

### Triage?
I do not care that much about data about my past payments, I would be happy to do an equivalent of `drop table payments; create table payments;`. Just don't know how to do it and whether it would be safe. I mean it would be nice to solve the underlying issue, but with bbolt being replaced by postgres, it doesn't make sense to spend much effort on a bbolt issue.

**Comment by GeorgeTsagk** [comment]
Hi @xmrk-btc!

Yes this is a db related issue, specifically the above error "Payment Isn't Initiated" is returned from the call `db.FetchPayment(paymentHash)` in [lnd/control_tower.go](https://github.com/lightningnetwork/lnd/blob/bd69e79f84f84be996070d095271f896b4735646/routing/control_tower.go#L269-L272).

> I got into this state (where listpayments does not work as explained above) by doing lncli deletepayments, probably with --include_non_failed

Perhaps RTL had cached some payment hashes and later tried to fetch their info, which did not exist as you had deleted the payments. I would assume this is normal behavior.

>  I would be happy to do an equivalent of drop table payments; create table payments;. Just don't know how to do it and whether it would be safe.

I agree with you that this wouldn't be necessary. You could try doing a [DeleteAllPayments](https://api.lightning.community/#deleteallpayments) on a newer version of lnd, but doing so would definitely cause important information to be lost.

**Comment by xmrk-btc** [comment]
Tried to delete, and it did not help, with the latest (0.15.1) lnd:

```
ubuntu@ubuntu:~$ ~/go/bin/lncli deletepayments --all --include_non_failed
Removing all payments, this might take a while...
{
        "ok": true
}
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments
[lncli] rpc error: code = Unknown desc = payment isn't initiated

```

Should I compact the db? I have compacted the db several times since this problem appeared, but not sure if I did deletepayments followed by immediate compact_db.

**Comment by GeorgeTsagk** [comment]
So do you get the above error only when there are no payments in db?

What happens if you make a successful payment and then do `lncli listpayments` again (without `--max_payments`)

**Comment by xmrk-btc** [comment]
> So do you get the above error only when there are no payments in db?
> 
> What happens if you make a successful payment and then do `lncli listpayments` again (without `--max_payments`)

No, listpayment never works without maxpayments, neither before deletepayments nor after. Right now, after delete and doing some payments, I get:
```
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 4|grep index
            "payment_index": "741554",
            "payment_index": "741555",
            "payment_index": "741749",
            "payment_index": "741761",
    "first_index_offset": "741554",
    "last_index_offset": "741761",
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 5
[lncli] rpc error: code = Unknown desc = payment isn't initiated
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments 
[lncli] rpc error: code = Unknown desc = payment isn't initiated

```

**Comment by GeorgeTsagk** [comment]
> > So do you get the above error only when there are no payments in db?
> > What happens if you make a successful payment and then do `lncli listpayments` again (without `--max_payments`)
> 
> No, listpayment never works without maxpayments, neither before deletepayments nor after. Right now, after delete and doing some payments, I get:
> 
> ```
> ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 4|grep index
>             "payment_index": "741554",
>             "payment_index": "741555",
>             "payment_index": "741749",
>             "payment_index": "741761",
>     "first_index_offset": "741554",
>     "last_index_offset": "741761",
> ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 5
> [lncli] rpc error: code = Unknown desc = payment isn't initiated
> ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments 
> [lncli] rpc error: code = Unknown desc = payment isn't initiated
> ```

In this referenced example the total number of payments you made was 4?

It really strikes to me as if `listpayments` is trying to fetch info of a payment hash that does not exist anymore, perhaps there's some caching there.

**Comment by xmrk-btc** [comment]
I am not sure how many payments were made, so I repeated the test, `deletepayments --all --include_non_failed`, no compacting this time, and doing just 1 payment:
```
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 1 | grep index
            "payment_index": "747896",
    "first_index_offset": "747896",
    "last_index_offset": "747896",
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments --max_payments 2 | grep index
[lncli] rpc error: code = Unknown desc = payment isn't initiated
ubuntu@ubuntu:~$ ~/go/bin/lncli listpayments  | grep index
[lncli] rpc error: code = Unknown desc = payment isn't initiated

```
