### ISSUE TITLE
"panic: page 25248 already freed" / lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by coldacid** [lightningnetwork/lnd#6971]
### Background

lnd fails to start as of 2022-10-02. lnd.service is stuck in a restart loop which began when I was not present to diagnose, but appears to be due to an already-freed page.

### Your environment

* version of `lnd`: `lnd version 0.15.0-beta commit=v0.15.0-beta`
* which operating system (`uname -a` on *Nix): `Linux nodepi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v23.0.0`
* any other relevant environment details: Raspiblitz v1.8.0

### Steps to reproduce

Unknown how to reproduce; lnd was working fine until the weekend, after which it failed and systemd automatically trying to restart it ended up with the following log repeated ad nauseum:

```
Oct 03 23:11:40 nodepi systemd[1]: Starting Lightning Network Daemon...
Oct 03 23:11:40 nodepi lnd[916985]: panic: page 25248 already freed
Oct 03 23:11:40 nodepi lnd[916985]: goroutine 1 [running]:
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*freelist).free(0x4000342080, 0x17ce70, 0x7f54eb3000)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c4
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*node).spill(0x40007a6230)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/node.go:359 +0x1d0
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*node).spill(0x40007a61c0)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/node.go:346 +0xa0
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*node).spill(0x40007a6150)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/node.go:346 +0xa0
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*node).spill(0x40007a60e0)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/node.go:346 +0xa0
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*Bucket).spill(0x40005d4b40)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x250
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*Bucket).spill(0x400043a478)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/bucket.go:537 +0xcc
Oct 03 23:11:40 nodepi lnd[916985]: go.etcd.io/bbolt.(*Tx).Commit(0x400043a460)
Oct 03 23:11:40 nodepi lnd[916985]:         go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xac
Oct 03 23:11:40 nodepi lnd[916985]: github.com/btcsuite/btcwallet/walletdb/bdb.(*transaction).Commit(0x19ddeb0?)
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:101 +0x24
Oct 03 23:11:40 nodepi lnd[916985]: github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x400084b108?, 0x179c008, 0x0?)
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:437 +0x104
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd/kvdb.Update(...)
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/kvdb@v1.3.1/interface.go:16
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd/channeldb.initChannelGraph({0x19dbf48?, 0x4000277200?})
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/channeldb/graph.go:347 +0x40
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd/channeldb.NewChannelGraph({0x19dbf48?, 0x4000277200}, 0xc350, 0x4e20, 0x1dcd6500, 0x3a98, 0x1, 0x0?)
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/channeldb/graph.go:196 +0x44
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd/channeldb.CreateWithBackend({0x19dbf48, 0x4000277200}, {0x4000ab41e0, 0x6, 0x25?})
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/channeldb/db.go:314 +0x2b0
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x40000109d8, {0x19d4118, 0x4000574140})
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/config_builder.go:869 +0x6e8
Oct 03 23:11:40 nodepi lnd[916985]: github.com/lightningnetwork/lnd.Main(0x400056c000, {{0x0?, 0x40000b6600?, 0x40000b6660?}}, 0x40005dc7e0, {0x40000aac00, 0x40000b6600, 0x40000b6660, 0x40000b66c0, {0x0}})
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/lnd.go:355 +0x1454
Oct 03 23:11:40 nodepi lnd[916985]: main.main()
Oct 03 23:11:40 nodepi lnd[916985]:         github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x1ac
Oct 03 23:11:40 nodepi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 03 23:11:40 nodepi systemd[1]: lnd.service: Failed with result 'exit-code'.
Oct 03 23:11:40 nodepi systemd[1]: Failed to start Lightning Network Daemon.
```

### Expected behaviour

lnd should start up and run properly.

### Actual behaviour

lnd terminates with 2/INVALIDARGUMENT status.

**Comment by GeorgeTsagk** [comment]
Hello @coldacid !!

This certainly looks like a bbolt issue. After reading some older similar issues like #1107 it looks like this can be caused by external factors like voltage drops / forced shutdowns. Another reason could be running the 32-bit lnd and your channel DB approaching 1GB.

One thing you can try is using [guggero/chantools](https://github.com/guggero/chantools/blob/master/doc/chantools_compactdb.md) to create a compacted copy of your DB.

Also you might want to consider disabling the [sync-freelist](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L89-L93) option from your lnd config.

**Comment by coldacid** [comment]
It's 64-bit (lnd: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped) and I've never had undervoltage issues with the node. There have been some power failures in recent history, but the last one of those was at least a week and a half before this problem started.

It does look, based on what I see in my syslog collector, that there could be a problem with the USB-SATA adapter or with the SSD itself, but the auto fsck on power-up doesn't ever seem to report any problems with the file system. At this point I'm going to treat this as a hardware issue, but I might be back if there's further evidence suggesting that the hardware's okay.

**Comment by guggero** [comment]
Haven't heard anything here, so going to close the issue with the assumption of hardware failure as mentioned above.
Please re-open if there's evidence against that.
