### ISSUE TITLE
channel.backup is not updated

### ISSUE THREAD

**Issue by milhousevanhouten11** [lightningnetwork/lnd#6973]
### Background

I've just noticed that channel.backup file has not been updated for 2 days, even if there were 30+ transactions in the meantime.
There are no errors in the log, and the time of the last update was the time when lnd was restarted (gracefully). 

### Your environment

* lnd v0.15.1-beta
* Ubuntu 22.04
* bitcoind 23.0.0

### Expected behaviour

channel.backup should update after each lightning transaction. This is a problem because I'm watching this file for updates, before copying it to the backup location.

**Comment by alexbosworth** [comment]
scb is only updated on channel open and close

**Comment by guggero** [comment]
Please read this: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#file-based-backups
SCB files only contain the static channel information (with SCB standing for Static Channel Backup), not state updates.

**Comment by milhousevanhouten11** [comment]
Thanks, for the quick replay.
