### ISSUE TITLE
zero-conf channels should remain for responder after 2016 blocks

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#6990]
It's possible that the transaction just hasn't been broadcast yet and will be. Or it's possible that the mempool is full but the channel has already been used. Since this isn't a malicious case like a double-spend and can happen between two parties that trust each other, we should handle this explicitly by having no block ceiling. We could also have no block ceiling unless the user specifies an argument.

**Comment by GeorgeTsagk** [comment]
> I think this is already covered under the constant here?
> 
> https://github.com/lightningnetwork/lnd/blob/4b2edc4777f5c6fdc1c0dfd12fe4d8c7048a0825/funding/manager.go#L99-L102
> 
> EDIT: Chatted offline and we actually want it to retain the channel after this point.

Perhaps make that const configurable? Another work-around would be exposing another bool arg on lnd about timing out 0-conf channel funding txs

**Comment by Crypt-iQ** [comment]
I don't know if users will be able to choose a safe constant, so leaning towards no ceiling

**Comment by alexbosworth** [comment]
A motivation for a cleanup timeout is for randomly received open channel requests, but in the case of zero-conf there is already an explicit acceptance of the channel so that motivation wouldn't apply, which implies no need for a ceiling

**Comment by Roasbeef** [comment]
>  but in the case of zero-conf there is already an explicit acceptance of the channel so that motivation wouldn't apply, which implies no need for a ceiling

Yeah this matches my current thinking as well. They're already fully opt in, so you as the acceptor have full control on acceptance.
