### ISSUE TITLE
[feature]: listchannels output should include node alias 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6994]
**Is your feature request related to a problem? Please describe.**

Many applications want to display a node's alias along side the set of displayed channels. Today that information isn't returned, so then an application needs to hit `GetNodeInfo` for each of the channels, which can really slow down loading 1000s of channels for a large node. 

**Describe the solution you'd like**

Add a new `alias` field to the `ListChannels` RPC call. 

**Describe alternatives you've considered**

Applications could use `GetNodeInfo` with `--include_channels`, but that'll only show the graph level information and not also the link level information. As an alternatively, we could add more link level channel info here (capacity, balance, etc, etc).

**Comment by hieblmi** [comment]
Additionally it would be great to have alias information on the `lncli fwdinghistory` events, maybe through new fields `alias_in` and `alias_out`.

**Comment by hieblmi** [comment]
Hi, I have taken up this issue since the related PR is closed since a while. The changes required here resemble changes in https://github.com/lightningnetwork/lnd/pull/7001. I have working code for a peer alias in `ListChannels` and will submit it with tests soon.

**Comment by Chinwendu20** [comment]
Hello @hieblmi . Are you still working on this? Or can I take this on

**Comment by hieblmi** [comment]
Hi @Chinwendu20, I am still working on it here: https://github.com/lightningnetwork/lnd/pull/7322. Please feel free to review the code if you want to.

**Comment by hieblmi** [comment]
@saubyk this ticket can be closed as https://github.com/lightningnetwork/lnd/pull/7322 was merged.

**Comment by guggero** [comment]
Fixed by #7322.
