### ISSUE TITLE
[bug]: btcd causes make release-install to fail with go:build error

### ISSUE THREAD

**Issue by abrkn** [lightningnetwork/lnd#7008]
### Background

Describe your issue here.

### Your environment

* version of `lnd` 0.15.1-beta and 0.15.2-beta
* which operating system (`uname -a` on *Nix) Docker golang:1.16.3-alpine
* version of `btcd`, `bitcoind`, or other backend bitcoind: bitcoind v23.0.0

### Steps to reproduce

Unable to `make release-install`:

```
/go/pkg/mod/github.com/btcsuite/btcd@v0.23.1/blockchain/compress.go:8:2: //go:build comment without // +build comment
make: *** [Makefile:142: release-install] Error 1
```

### Expected behaviour

Build install, exit with no error

### Actual behaviour

Command exits with error

This error is introduced in v0.15.1-beta and persist in v0.15.2-beta. The build executes fine from the v0.15.0-beta tag

**Comment by Roasbeef** [comment]
Which Go version are you using? You'll need to be using at least Go 1.18.

**Comment by abrkn** [comment]
Okay, I'll give that a shot.

**Comment by abrkn** [comment]
That works, @Roasbeef.

If anyone runs into [Operation not permitted](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396) after upgrading your Docker image, you also need to upgrade Docker itself to v20.10.
