### ISSUE TITLE
[lncli] rpc error: code = Unknown desc = channel not found

### ISSUE THREAD

**Issue by lampshadeshoe** [lightningnetwork/lnd#7010]
I am attempting to force close a channel.
I issue: lncli listchannels
I choose the channel_point I want to close
It is inactive 
I attempt lncli closechannel --force {channel_point}
I recieve: [lncli] rpc error: code = Unknown desc = channel not found
Any ideas what is going on?

**Comment by sputn1ck** [comment]
The correct syntax for close channel is:
`lncli closechannel --force funding_txid [output_index]`

So if my `channel_point` is `f9895a116215e8e550426e3c58c0053408d967eef751b674ad9fca5115b49442:1` I would call
`lncli closechannel --force f9895a116215e8e550426e3c58c0053408d967eef751b674ad9fca5115b49442 1`

Could you try that again?

**Comment by lampshadeshoe** [comment]
That was it, thank you very much!
I had left the colon in the expression :1
On this field the default value is 0 correct?
For my edification where could I find the documentation for the difference between a 0 and 1?
Once again thank you for the timely assistance.

**Comment by sputn1ck** [comment]
Hm, I don't know of any documentation other than https://api.lightning.community/#closechannel

The `output_index` is the position of the output in the funding transaction of a channel. E.g. in this [channel ](https://1ml.com/channel/782807199131631617)[this channel opening] the [funding transaction](https://blockstream.info/tx/78d5bd477b0dcddde83bc7c5c624c1fef2436a48072403b17636305e212e1c8a) of the channel is at `output_index` 1.
