### ISSUE TITLE
[watchtower] [feature]: mark exhausted sessions as inactive

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7045]
**Is your feature request related to a problem? Please describe.**
By default, each watchtower session has at most 1024 updates. Once it is exhausted, it is not used for further updates and a new session is created on demand. During startup of lnd, all active sessions (including those that are exhausted) are loaded as candidates, and once a new update needs to be added to a session, lnd loops over these candidates to find an eligable one.

As, over time, most sessions are exhausted, this is a rather long trial-and-error loop (I have over 60,000 exhausted sessions on my node) which runs (only) once after each startup (when the first update is handled).

**Describe the solution you'd like**
I'd like lnd to mark exhausted sessions as inactive once all updates are acked by the watchtower server (as it is already done when removing/disabling a tower), so that the exhausted sessions do not need to be consired for new updates (possibly improving lnd startup performance).

Furthermore, this would help with #6886 #6259 #7035 as exactly these sessions (exhausted, inactive, all updates are acked) are candidates for removal from both the server's and the client's databases.

**Comment by C-Otto** [comment]
Note that it does not suffice to mark a session as inactive once the last (acked) update is added, as there may be older exhausted sessions where no new update will ever be added.

**Comment by ellemouton** [comment]
Took another approach with #7405. I think it solves the same issue though :)

**Comment by ellemouton** [comment]
Fixed in https://github.com/lightningnetwork/lnd/pull/7405
