### ISSUE TITLE
Remove symbols from commands

### ISSUE THREAD

**Issue by 1440000bytes** [lightningnetwork/lnd#7054]
It will be easier to copy from block if there were no extra symbols with commands. 

Example:

![image](https://user-images.githubusercontent.com/94559964/196409576-ac3252ec-58a2-43a6-a51f-65823882d7e0.png)

![image](https://user-images.githubusercontent.com/94559964/196409796-9807fa50-d927-4090-8797-1835348d568d.png)

**Comment by hazrulnizam** [comment]
Those symbols seemed to be added and standardised across all docs in https://github.com/lightningnetwork/lnd/commit/2c634bfaf39838f7717d828884b3f0bb5a54f691.

There might be a reason for it.

**Comment by habibitcoin** [comment]
Sounds reasonable to me; similar request was opened in https://github.com/lightninglabs/taro/pull/162

The discussion was pretty cursory in https://github.com/lightningnetwork/lnd/pull/4926

**Comment by habibitcoin** [comment]
Opened a pull request https://github.com/lightningnetwork/lnd/pull/7070
