### ISSUE TITLE
[bug]: uri with wrong public ip

### ISSUE THREAD

**Issue by ChuckNorrison** [lightningnetwork/lnd#7061]
### Background

i was able to track my issue down to the lnd service on my raspiblitz setup. My node uri is set to @127.0.0.1:9735 frequently. After a while it fixes itself. While this issue persist iam able to ping some public websites, so my internet is just fine. Iam using a tun0 OpenVPN connection on this node.

### Your environment

* version of `lnd`
0.15.3
* which operating system (`uname -a` on *Nix)
Linux raspberrypi 5.15.32-v8+ #\1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
23.0.0
* any other relevant environment details
OpenVPN Client

### Steps to reproduce

restart lnd.service and `lncli getinfo`

### Expected behaviour

dont use 127.0.0.1, this is always wrong!

### Actual behaviour

public ip detection fails

**Comment by positiveblue** [comment]
Does this only happen when you restart LND or the node address changes to localhost even when the process has been running for a while?

I guess not but, Is 127.0.0.1 added to your lnd.conf as `externalip`?

**Comment by ChuckNorrison** [comment]
only observed on restart lnd, which happens automatically several times a day cause of another issue iam facing.

The 127.0.0.1 IP is set in the lnd.conf as externalip. if i stop lnd and set the correct externalip, the wrong ip is set after start of lnd.

**Comment by ChuckNorrison** [comment]
@positiveblue i use a static ip via my VPS. 

In case of failure, i stop lnd service, fix externalip manually and start lnd. Then it gets replaced with 127.0.0.1 automatically. Anyway, the raspiblitz configuration use duckdns in the background. But my IP will never change, cause its static. Iam connected to my VPS with OpenVPN Client from my raspberry PI which runs lnd.service

**Comment by positiveblue** [comment]
If you have a static IP that is the one that should go in the `lnd.conf`. i think an external program is recreating your config adding `127.0.0.1` and deleting your changes.

**Comment by ChuckNorrison** [comment]
Ok thanks for your help, then lnd is not updating this config automatically and i need to get back into the raspiblitz code to find it. I will close this issue here.

**Comment by guggero** [comment]
Did you (or RaspiBlitz) set [`externalhost`](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L67) perhaps? That will try to resolve the given host periodically and announce the resolved IP address to the network. Not sure if that works correctly in combination with `externalip`.
