### ISSUE TITLE
How to get mainnet?

### ISSUE THREAD

**Issue by angry-elf** [lightningnetwork/lnd#707]
Is it Lightning Network in use now? I can see numerous news about "Wow, it's really working", but can't find any working node solution for LN.

I searched through the issues here, and there was several references "mainnet is not supported in LND yet". 

So, the questions are:
1. When lnd will support LN?
2. What daemons are supported LN for now in production (eclair and c-lightning claims "do not use us in mainnet")?

**Comment by zaptrem** [comment]
Mainnet use is not currently encouraged. You may be able to find help somewhere else.

**Comment by MeshCollider** [comment]
Using Lightning on mainnet at this relatively early stage in development and testing is reckless and may result in fund loss. This applies to all implementations including c-lightning and eclair. LND support will be released for mainnet when it's ready, but no-one can give a definite timeframe for when that will be.
