### ISSUE TITLE
[bug]: very old payments with status in_flight

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7072]
### Background

Some of the payments reported by `lncli listpayments` have the status "in_flight". However, these were created more than a year ago. In the example below, the first hop channel is closed already (and I currently do not have another channel to said peer), and all "expiry" are far smaller than the current block height.

[payment.txt](https://github.com/lightningnetwork/lnd/files/9844691/payment.txt)

I expect lnd to either not return these payments, or provide final status.

The payment was a rebalance attempt. I cannot find an invoice with a matching hash, so I guess the payment failed.

### Your environment

* lnd v0.15.3-beta (with a few unrelated patches)
* Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* bitcoind v23

**Comment by C-Otto** [comment]
I'm also unable to delete this payment:
```
lncli deletepayments --payment_hash c279ba7df2554393f60a81ab0f4e201422928de7ecafe4fb2d82cf35d1d37de7
[lncli] error deleting single payment: rpc error: code = Unknown desc = payment 'c279ba7df2554393f60a81ab0f4e201422928de7ecafe4fb2d82cf35d1d37de7' has status InFlight and therefore cannot be deleted
```

**Comment by hazrulnizam** [comment]
Similar to https://github.com/lightningnetwork/lnd/issues/6834?

**Comment by C-Otto** [comment]
Yes, a duplicate even. Thanks!
