### ISSUE TITLE
[feature]: expose tlv data for gossip messages in `DescribeGraph`

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#7080]
TLV extensions for gossip messages are received by `lnd` and stored on disk, but there is no way to retrieve that data through the api. This issue is about extending `DescribeGraph` and other relevant graph calls with a `tlv_records` field.

Example application: https://github.com/mempool/mempool/issues/2658

**Comment by alexbosworth** [comment]
would also be cool to broadcast arbitrary tlv values here
