### ISSUE TITLE
htlcswitch: make final settle signal opt-in, add delete functionality

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#7089]
>And making this opt-in can complicate things. So I guess I'm not sure, tho leaning towards making it opt-in, at lease give users an option.

Given the advanced state of this PR, would you be okay with discussing and implementing the opt-in in another PR, possibly combined with delete functionality?

_Originally posted by @joostjager in https://github.com/lightningnetwork/lnd/issues/6517#issuecomment-1291997033_

**Comment by yyforyongyu** [comment]
Coming back from itest fix, I got two questions with PR #6517,
- what's the difference between `HtlcEventSettle` and `HtlcEventFinal` with `settled=true`? Do they overlap? Or can an `HtlcEventSettle` be followed by an `HtlcEventFinal` with `settled=false`?
- the htlc event used here is `UNKNOWN`, which doesn't feel right - how can an intentionally crafted event be unknown?

Found this previous discussion,
> I didn't want to add a dedicated subscriber api for final htlc notification and decided that the existing htlc notifier api is close enough to add it there. The use case, at least mine, is quite different though. The htlc notifier is intended to keep a (lossy) eye on traffic, whereas the final htlc notification is needed to get a definite answer to what happened to an htlc without relying on polling LookupHtlc. The additional context of whether the htlc was a forward or exit hop receive isn't relevant.

**Comment by joostjager** [comment]
>what's the difference between HtlcEventSettle and HtlcEventFinal with settled=true? Do they overlap? Or can an HtlcEventSettle be followed by an HtlcEventFinal with settled=false?

They are different. `HtlcEventSettle` is the initiation of the settle action, and `HtlcEventFinal, settled=true` is when it actually happened.

`HtlcEventSettle` can indeed by followed by `HtlcEventFinal with settled=false`. This is what is unsafe about lnd and the primary reason for #6517.

**Comment by Roasbeef** [comment]
Hey @joostjager are you still planning on resolving this for 0.16?

**Comment by joostjager** [comment]
I can definitely do that. What would be the most suitable way to opt-in to it, command line flag?

**Comment by yyforyongyu** [comment]
I think a config option would be nice.

**Comment by yyforyongyu** [comment]
actually just realized the delete part is not added yet

**Comment by joostjager** [comment]
What would be the best way to implement delete for this? Delete everything for a particular channel? There is no way to query for which channels final resolution data is stored though.
