### ISSUE TITLE
[bug]: CRITICAL! Unable to process chain reorg / too many witness items to fit into max message size

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7096]
### Background

lnd does not process new blocks.

lnd:
```
2022-11-01 12:02:54.658 [ERR] LNWL: Unable to process chain reorg: unable to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea: MsgTx.BtcDecode: too many witness items to fit into max message size [count 500003, max 500000]
```

bitcoind:
```
2022-11-01T10:44:23Z UpdateTip: new best=000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea height=761249 version=0x20a00000 log2_work=93.818550 tx=776743287 date='2022-11-01T10:44:19Z' progress=1.000000 cache=21.2MiB(82459txo)
```

My bitcoind knows about block height 761255, but lnd and mempool.space are stuck at 761248.

* lnd v0.15.3-beta
* bitcoind v23

https://twitter.com/c_otto83/status/1587400648366202880

**Comment by C-Otto** [comment]
Possibly related?
https://twitter.com/wasabiwallet/status/1586648312811294723

tx d465033214fd2309dcce5a90c45fcaa788aa4394ee36debe07aad8d8a37907d2

**Comment by guggero** [comment]
On it.

**Comment by indomitorum** [comment]
Same here.


2022-11-01 11:10:13.912 [ERR] LNWL: Unable to process chain reorg: unable to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea: MsgTx.BtcDecode: too many witness items to fit into max message size [count 500003, max 500000]

lnd@indomitusbtc:~$ lncli getinfo | grep synced
    "synced_to_chain": false,
    "synced_to_graph": true,

**Comment by C-Otto** [comment]
I'm pretty sure all (recent) lnd installations are affected by this.

**Comment by mutatrum** [comment]
btcd issue: https://github.com/btcsuite/btcd/issues/1906

**Comment by RandyMcMillan** [comment]
😬

**Comment by Sep21-2009** [comment]
https://twitter.com/brqgoo/status/1587397646125260802?t=4Dn-tAdekbGilSd7TCXeKA&s=19

?

**Comment by b3h3rkz** [comment]
I'm guessing this is a btcd issue? Everything seems to be fine on bitcoin

**Comment by C-Otto** [comment]
Yes, the btcd issue is linked above.

**Comment by Stronzo-sky** [comment]
also got hte same bug, running lnd-15.3 and bitcoin-22.0:

**Comment by LNBIG-COM** [comment]
Hi,

My all nodes are in a state:

```
l getinfo|grep synced
    "synced_to_chain": false,
    "synced_to_graph": true,
```

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/7098, release binaries and docker images for `v0.15.4-beta` are going to be available soon (building right now).

**Comment by Stronzo-sky** [comment]
> I'm guessing this is a btcd issue? Everything seems to be fine on bitcoin

no, i`m running bitcoin core v22.0 and having the same issue.

**Comment by WalterSmuts** [comment]
I'm running neutrino, and not seeing the issue:
```
walter@fluffy:~$ lncli  getinfo | grep synced
    "synced_to_chain": true,
    "synced_to_graph": true,
walter@fluffy:~$ lncli  getinfo | grep block
    "block_height": 761264,
    "block_hash": "000000000000000000072cabab0aac7c6b00db0664b82edc77d3252634fcba8a",
```

**Comment by C-Otto** [comment]
Fixed version is available here: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta

**Comment by NicolasDorier** [comment]
I bumped to 0.15.4, it fixed the issue. (our own build)

**Comment by joostjager** [comment]
Would it be possible to modify lnd so that it skips validation on blocks received from the chain backend? Just reading about Eclair's exposure to this class of bugs: https://github.com/ACINQ/eclair/pull/2473#discussion_r1011530186
