### ISSUE TITLE
[bug]: MsgTx.BtcDecode: too many witness items to fit into max message size [count 500003, max 500000]

### ISSUE THREAD

**Issue by HotCrypt** [lightningnetwork/lnd#7102]
### Background

Hello, 
I’m a beginner and I’m trying to explore and understand the LN network (I was very surprised:0,1sat of fees for an instant transaction with —keysend, it’s clear that it’s the best secure crypto network👏💪). 

I am so happy to have managed to install an lnd node and create a first channel to test (100ksat) and an Uris with active announcement. 

I run bitcoinqt v.22 and lnd 15.2 beta on a raspberry 4 8go with 2to hdd.

Everything has been working very well for several days but I have this error that appeared today, my node lnd is blocked at block height 761248 (0000000000000000000640e114b9e6272b9688178273e193ef957e02fad1069f).  

Thanks for your help.

**Comment by alexbosworth** [comment]
try updating to lnd 0.15.4

**Comment by saubyk** [comment]
Hi @HotCrypt please update to 0.15.4 to get this issue addressed

**Comment by HotCrypt** [comment]
Merci a tous. Ca fonctionne 😀🎉👌
