### ISSUE TITLE
Minimize validation on received blocks

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#7124]
Would it be possible to modify lnd so that it skips/relaxes validation on blocks received from the chain backend?

Just reading about Eclair's exposure to this class of bugs: https://github.com/ACINQ/eclair/pull/2473#discussion_r1011530186

**Comment by GeorgeTsagk** [comment]
AFAIU this could eliminate any future issues with chain sync caused by `lnd` codebase? They would then only be related to the chain backend of choice.

cc @Roasbeef any reason to **not** relax lnd block validation?

**Comment by Roasbeef** [comment]
This would be more of a `btcsuite/btcd` thing. We use the library to parse the blocks, so any relaxation would need to happen there. We don't do any special application level checks (eg: we don't verify pow when the block comes from a chain backend). 

We don't do any custom policy stuff, and want to eventually switch to doing `testmempoolaccept` on everything (if available) before we broadcast.

**Comment by joostjager** [comment]
Even if it is something that can be implemented in `btcsuite/btcd`, I still think it is worth tracking in this repository. Maybe there are other implementation options too. Unless of course the suggestion to loosen validation is not going to help.
