### ISSUE TITLE
Trying to understand calculations local_amt

### ISSUE THREAD

**Issue by RvMp** [lightningnetwork/lnd#713]
Trying to understand why `10000` satoshis equals `0.32274783` btc

My balance was `'t: 713,213,549, c: 713,213,549, u: 0'` (total, confirmed, unconfirmed)
When I opened a channel and funded it the balance changes unexpectedly 

```
lncli openchannel 0299ee6e1b4568628309236247bdcbc371aa54e48c85a5a82ca8d6359f514608de --local_amt=10000
```

Now my witness_balance=`'t: 680,935,100, c: 680,935,100, u: 0'` ????

I would expect: `713,213,549 - 10,000 = 713,203,549`
Is the local_amt amount multiplied by X or?

corresponding tx: https://live.blockcypher.com/btc-testnet/tx/dc7f99589cb8d7200a85f4fd7cb58e0823a4237328aafcf44a99089220fabddd/

Tested with this node:

```
lncli connect 0299ee6e1b4568628309236247bdcbc371aa54e48c85a5a82ca8d6359f514608de@92.53.89.122:9736
```

Channel still pending right now (opened 40 minutes ago)
```
  {
            "channel": {
                "remote_node_pub": "0299ee6e1b4568628309236247bdcbc371aa54e48c85a5a82ca8d6359f514608de",
                "channel_point": "dc7f99589cb8d7200a85f4fd7cb58e0823a4237328aafcf44a99089220fabddd:0",
                "capacity": "10000",
                "local_balance": "5656",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "4344",
            "commit_weight": "600",
            "fee_per_kw": "6000"
        }
```

**Comment by Roasbeef** [comment]
Did you have autopilot on? Possible it could have opened additional channels while you weren't polling the commands.

**Comment by RvMp** [comment]
On slack someone explained to me this is normal behavior and when the channel changes from pending to active the amount will be returned. System to prevent double spending?

**Comment by halseth** [comment]
Yeah, you are basically spending that whole output (of size `0.32274783`), so it is not available for use again before your channel is confirmed, making your balance drop.

**Comment by RvMp** [comment]
That explains. Why 0.32?

**Comment by halseth** [comment]
That's how Bitcoin works: you always have to consume an output completely.

**Comment by RvMp** [comment]
And thats the amount of bitcoin in one witness address?

**Comment by RvMp** [comment]
Thank you @halseth for explaining

**Comment by RvMp** [comment]
I think this one can be closed. The restart / pending problem can be found here:
https://github.com/lightningnetwork/lnd/issues/720
