### ISSUE TITLE
Change Addresses do not default to taproot

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#7144]
### Background

I am creating transactions and my changes addresses seems to always be native segwit v0.

Expierenced when calling `sendoutputs` and `lncli sendcoins`using lnd 0.15.4

**Comment by positiveblue** [comment]
Thank you for creating an issue so it easier to track @benthecarman 

We need to add [here](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/btcwallet/btcwallet.go#L985) the correct KeyScope. We are using `nil` so [btcwallet uses the default one](https://github.com/btcsuite/btcwallet/blob/58c26808d1b4e7341fc03701fc7dcacb5a78b6b0/wallet/createtx.go#L101) (P2WKH)

A possible fix is simply using `waddrmgr.KeyScopeBIP0086` as the key scope param but I will need someone with more context before creating the PR.

I know some people were talking about not using P2TR addresses as default and  having it configurable. If we follow that path, then we need to send here whatever the user configures. If not, `KeyScopeBIP0086` is the way to go :rocket:
