### ISSUE TITLE
upgrading to latest commit (with changed directories) makes alias stop working

### ISSUE THREAD

**Issue by bretton** [lightningnetwork/lnd#716]
After closing out channels, backing up wallet.db, I upgraded to the latest commit.

restart of lnd created new directory structure. 

stopped, copied backup of wallet.db to new location, overwriting new file. 

started again, got up to date, ran 'lncli getinfo' and found my alias was no longer being set.

"alias": "",

if I run 'lncli getnodeinfo <pubkey>' then I see the alias again but this is probably from network history from peers. 

The current changes appear to break the earlier alias commits.

```
db7d902 HEAD@{0}: pull: Fast-forward
b4e280e HEAD@{1}: pull: Fast-forward
4559438 HEAD@{2}: pull: Fast-forward
dd08662 HEAD@{3}: clone: from https://github.com/lightningnetwork/lnd
```

**Comment by dabura667** [comment]
Did you check your lnd.conf?

**Comment by bretton** [comment]
Yes it's the same lnd.conf as it was before.

Even starting lnd with --alias=xxx results in lncli getinfo giving
```
"alias": "",
```

**Comment by bretton** [comment]
1. node with a week old commit:
```
$ git reflog
b4e280e HEAD@{0}: pull: Fast-forward
e30f869 HEAD@{1}: pull: Fast-forward
dd08662 HEAD@{2}: pull: Fast-forward
86133e5 HEAD@{3}: clone: from https://github.com/lightningnetwork/lnd
```

output of getinfo:
```
$ lncli getinfo
{
    "identity_pubkey": "033d45b692e1f3617dd77ab9bad6d070c6a3438467a5beed34c9b5a218b03fc15b",
    "alias": "nanoparticle.space",
<snip>
```

2. node upgraded to current commit:
```
$ git reflog
db7d902 HEAD@{0}: pull: Fast-forward
b4e280e HEAD@{1}: pull: Fast-forward
4559438 HEAD@{2}: pull: Fast-forward
dd08662 HEAD@{3}: clone: from https://github.com/lightningnetwork/lnd
```

output of getinfo
```
$ lncli getinfo
{
    "identity_pubkey": "02faf31d72590671bdcbd65cef587e1eb35656e65aa27c24250ee2056c23c82a26",
    "alias": "",
<snip>
```

**Comment by bretton** [comment]
this appears fixed with the following commit. tested & working

https://github.com/lightningnetwork/lnd/commit/7144707734171023392d514ccc61941f7e30adb6
