### ISSUE TITLE
[bug]: Incomplete channel graph

### ISSUE THREAD

**Issue by Heisenberg-CZE** [lightningnetwork/lnd#7166]
### Background

I recently discovered that my channel graph contains only a little over 50k channels.

`lncli describegraph | grep channel_id | wc -l`

I found out that I had `routing.strictgraphpruning=true` in lnd.conf, so I deleted it (default should be false). It's been more than 24 hours, my node is very well connected, online, but the number of channels is still the same (except few).

For example, my node reports, that this node **02ff30e83896d453cfc89ff4dd06d23d793b7246f154c210324adc1d42c849ce74** has only 7 channels. The reality is 108.

`lncli describegraph | grep 02ff30e83896d453cfc89ff4dd06d23d793b7246f154c210324adc1d42c849ce74 | grep node | wc -l`
`7`

I am directly connected with this node, I have a channel with him. So the gossip path should be quite short.

If I randomly select a channel, it shows me that it is in a zombie state, even if the last_update was, for example, a few hours ago and other nodes can see it fine. 

`lncli getchaninfo 828585365650407425`
`[lncli] rpc error: code = Unknown desc = edge marked as zombie`

https://amboss.space/edge/828585365650407425

This is just one example. My node does not see almost half of the channels that my peers have open and therefore does not use them at all in routing. 

I know that `strictgraphpruning` sets that all it takes is for one party to not send an update within the limit and the channel will be considered as zombie. At the same time, the **same node** has to send an update later to make it active again. However, I find it very unlikely that in almost 30k cases one party would not send updates and at the same time I would expect the number of channels to grow once I deleted this from the lnd.conf. 

### Your environment

* LND v0.15.4-beta
* Bitcoin Core v23.0.0

### Steps to reproduce

Run a node with `routing.strictgraphpruning=true` for few days/weeks/months. Set it to false afterwards.

### Expected behaviour

My node should see all channels that reach it with the gossip protocol (+- 80k), update from one side should be enough to make it active.

### Actual behaviour

My node only knows about 50k channels and this number is not increasing at all.

**Comment by sputn1ck** [comment]
This bug is being actively looked into, some references:
https://github.com/lightningnetwork/lnd/issues/6531
https://github.com/lightningnetwork/lnd/issues/6870
https://github.com/lightningnetwork/lnd/issues/7073

**Comment by Roasbeef** [comment]
See this discussion: https://github.com/lightningnetwork/lnd/discussions/7042
