### ISSUE TITLE
Installing lnd ERROR

### ISSUE THREAD

**Issue by liderako** [lightningnetwork/lnd#717]
> git clone https://github.com/lightningnetwork/lnd $GOPATH/src/github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
glide install
go install . ./cmd/...

When I running last command. I have some error. 
```
unexpected directory layout:
	import path: github.com/boltdb/bolt
	root: /home/asvirido/usr/local/go/src
	dir: /home/asvirido/usr/local/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	expand root: /home/asvirido/usr/local/go/src
	expand dir: /home/asvirido/usr/local/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	separator: /
```
How fix this error?

**Comment by Roasbeef** [comment]
It looks like you've overlapped your `$GOROOT` (where go lives), and your `$GOPATH`. They should be distinct directories.
