### ISSUE TITLE
Create a lighning Network org on Docker Hub, and create a automatic build

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lnd#722]
Hi!

Cna someone with access to the repo create a automatic build of `LND`?

To create an automatic build, you first have to link your account to Docker Hub, then choose "Create" in the nav-menu, then select the appropriate repo :)

![bilde](https://user-images.githubusercontent.com/5749715/35769444-3b784c7a-090b-11e8-8846-31d61562c2cb.png)

**Comment by i25959341** [comment]
yes that would be a very nice feature to add

**Comment by alingenhag** [comment]
For those who come here, I created a separate repository which does this [here](https://github.com/f-u-z-z-l-e/docker-lnd)

It builds the image daily. Furthermore I created another image which supports all known cli options to be set as environment variables. Feel free to try it out.

**Comment by tyzbit** [comment]
I'm adding a Dockerfile that just builds lnd, which will allow this to be set up for auto-builds.  That should get us most of the way to satisfying this issue.

**Comment by Roasbeef** [comment]
Closed in #1164.
