### ISSUE TITLE
[bug]: The problem with processing IP & Alias from a gossip protocol?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#7223]
### Background

The problem with the announcement of Alias + IP addresses of LND servers after changing IP & Alias.
Most of the network does not see the changes made in LND 0.15.4-beta after the server was moved to a new IP and the Alias was changed (even after a week). At the same time, most of my other nodes do not see these changes (roughly speaking, 3/4 nodes or more). There is clearly some kind of bug.

### Your environment

* version of `lnd` 0.15.4-beta

### Steps to reproduce

Change the IP and Alias and do this at least 3-4 times with different nodes. I think at least on one you will see that other nodes of the network will not see changes about him in the graph even after a week.

### Expected behaviour

Changes to IP and Alias should occur fairly quickly on other nodes of the network. Otherwise, it doesn't make sense to use Lightning.

### Actual behaviour

Example - more than a week ago I moved `lnd-02` to another server, the IP address was changed and I changed the Alias.  At first [I thought the problem was that I changed the `externalip`](https://github.com/lightningnetwork/lnd/issues/6128#issuecomment-1327856238) option to `externalhosts` for simplification (+ `/etc/hosts` for this). But afterwards I tried to go back to the `externalip` option again (with certain IP address) and restarted the lnd server many times. But it didn't help, so I returned the `externhosts` option. Now I suppose it doesn't matter which of the two options is used.

For example, `lnd-02` was moved to another server now it's `lnd-25`. But even after a week, even my other nodes see it as (`lncli getnodeinfo`):

lnd-05, lnd-26:

```
        "pub_key": "03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618",
        "alias": "LNBIG.com [lnd-25/old-lnd-02]",
        "addresses": [
            {
                "network": "tcp",
                "addr": "213.174.156.69:9735"
            }
        ],
```

lnd-20, lnd-21, lnd-27, lnd-28, lnd-39, lnd-40 (old IP & Alias!):

```
        "pub_key": "03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618",
        "alias": "LNBIG.com [lnd-02]",
        "addresses": [
            {
                "network": "tcp",
                "addr": "46.229.165.138:9735"
            }
        ],
```

The `lnd-25` (old `lnd-02`) itself now is:

```
l getinfo
{
    "version": "0.15.4-beta commit=v0.15.4-beta",
    "commit_hash": "96fe51e2e5c2ee0c97909499e0e96a3d3755757e",
    "identity_pubkey": "03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618",
    "alias": "LNBIG.com [lnd-25/old-lnd-02]",
    "color": "#3399ff",
    "num_pending_channels": 0,
    "num_active_channels": 84,
    "num_inactive_channels": 200,
    "num_peers": 85,
    "block_height": 765487,
    "block_hash": "0000000000000000000023bd2e094e70822bd9dccd2e63ed4ae253e810af94c3",
    "best_header_timestamp": "1669910883",
    "synced_to_chain": true,
    "synced_to_graph": true,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "mainnet"
        }
    ],
    "uris": [
        "03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618@213.174.156.69:9735"
    ],
...
```

**Comment by LNBIG-COM** [comment]
And I have a lot of similar problems with other servers that I have also moved. From the latest ones:

```
lnd-06 -> lnd-05
lnd-07 -> lnd-26
lnd-01 -> lnd-17
lnd-31 -> lnd-51
lnd-32 -> lnd-52
lnd-33 -> lnd-15
```

**Comment by LNBIG-COM** [comment]
I see sources now.

https://github.com/lightningnetwork/lnd/blob/master/netann/host_ann.go#L24

> 
	// AdvertisedIPs is the set of IPs that we've already announced with
	// our current NodeAnnouncement. This set will be constructed to avoid
	// unnecessary node NodeAnnouncement updates.
	AdvertisedIPs map[string]struct{}

As I understand it, when the server starts, [the AdvertisedIPs structure is filled with the current IP addresses](https://github.com/lightningnetwork/lnd/blob/master/server.go#L1529), and only if they are subsequently changed - an announcement to the network occurs. Is that true?

That is, if I run lnd, and the hostname itself does not resolve to different IP, then there is no announcement by gossip?

I suspect that such logic can be simple with the `externalip` option - in what cases is the announcement of a new IP?

**Comment by bitromortac** [comment]
My node sees the same as your `lnd-05, lnd-26` nodes (IP starts with 213), so there was some partial gossip propagation. On amboss and 1ml it's still `lnd-02` (IP starts with 46). I'm still investigating, but I just wanted to make you aware of this rpc https://api.lightning.community/#updatenodeannouncement, perhaps it can help you for a workaround.

**Comment by LNBIG-COM** [comment]
@bitromortac Thanks!
I used now the `l peers updatenodeannouncement --address_add NEW_IP --address_remove OLD_IP --alias 'alias'` command. It works, writes JSON data to the screen, which has changed (I even ran it many times with other data to force the update) and which has been broadcast. But even on my nodes minutes later - there is no update for `lnd-25/old-lnd-02` node. It feels like update nodes are not working. :(

Another problem is that some wallets ([SBW](https://sbw.app/) for example) stop working with the channels of the node that was transferred, because for some reason the idea that the nodes are tied to an IP address is being persistently promoted in the lightning network. Although it would be better if they were tied to the DNS name, not the IP, that was saved for the node. This is the Achilles' heel - the IP address and its replacement. :(

**Comment by LNBIG-COM** [comment]
May be @guggero or @Roasbeef will help to me?

The problem is very serious. I'll try to describe it again in simple words here: when I move a node to another server, my IP changes. The port (9735) is open, there are no problems with the connection. But [`node_announcement`](https://github.com/lightning/bolts/blob/master/07-routing-gossip.md#the-node_announcement-message) updates don't seem to work. Even in manual mode via the `lncli peers updatenodeannouncement ...` command (peersrpc is there in lnd). I haven't been able to get update of graph at many other nodes (even on my ones!) the new IP and Alias for more than a week! For example [`lnd-02`](https://amboss.space/node/03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618) [was moved to other IP](https://github.com/lightningnetwork/lnd/issues/6128#issuecomment-1327856238) and more one week the world sees this as old IP & Alias!

At lnd-02 now there is:

```
    "num_active_channels": 87,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    "num_inactive_channels": 196,
```

I do not know how to make the world know about the new IP! I assumed that gossip existed for this. But your buggy LND doesn't want to do that!

**Comment by devastgh** [comment]
> For example, `lnd-02` was moved to another server now it's `lnd-25`. But even after a week, even my other nodes see it as (`lncli getnodeinfo`):

Your cln peers can see your node announcements properly, so i guess the issue is with lnd not processing your announcement, while it is being generated and gossiped properly by your node.

This is what i see of 02:
```
lightning@devzorln:~$ lightning-cli listnodes 03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
{
   "nodes": [
      {
         "nodeid": "03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618",
         "alias": "LNBiG.com🇺🇦[lnd-25/lnd-02]",
         "color": "3399ff",
         "last_timestamp": 1669923084,
         "features": "800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888a52a1",
         "addresses": [
            {
               "type": "ipv4",
               "address": "213.174.156.69",
               "port": 9735
            }
         ]
      }
   ]
}
```

**Comment by LNBIG-COM** [comment]
I agree that the problem may be that the problem is not in sending update nodes messages, but in their processing when received by the LND itself. Is your abbreviation `cln` - it's `c-lightning` software? All my other nodes are LND, and 3/4 of them have the old data of the former lnd-02. Same with the [other nodes I moved three days ago](https://github.com/lightningnetwork/lnd/issues/7223#issuecomment-1334037133).

**Comment by guggero** [comment]
Unfortunately I'm not very familiar with the p2p/announcement code of lnd. But it does look like there is something wrong with processing the announcements (apparently sending them out isn't the issue).

We did fix something in that area recently: https://github.com/lightningnetwork/lnd/pull/7186
If you're willing to try this out, I can create a rebased branch of `v0.15.5` with just that PR on top.

**Comment by LNBIG-COM** [comment]
> We did fix something in that area recently: https://github.com/lightningnetwork/lnd/pull/7186

Ok, or I can try to make `git pull` some commands to merge your patches.

**Comment by guggero** [comment]
The PR is on top of `master` which contains some DB migrations and would make it impossible for you to revert back to `v0.15.5`. So let me just do this quickly, one moment.

**Comment by devastgh** [comment]
> I agree that the problem may be that the problem is not in sending update nodes messages, but in their processing when received by the LND itself. Is your abbreviation `cln` - it's `c-lightning` software? All my other nodes are LND, and 3/4 of them have the old data of the former lnd-02. Same with the [other nodes I moved three days ago](https://github.com/lightningnetwork/lnd/issues/7223#issuecomment-1334037133).

Yes, i'm running core lightning. I just checked all the nodes you mentioned, i can see the new alias/ip address on all of them. Checking on amboss (as they run lnd) vs my data, lnd-33 is the only other i could find thats wrong there, but okay in my gossip data.

**Comment by guggero** [comment]
Okay, you can check out the branch `pr-7186-v0-15-5-branch` which is `v0.15.5-beta` with a rebased version of #7186 on top.
So `git fetch && git checkout pr-7186-v0-15-5-branch`.

**Comment by LNBIG-COM** [comment]
> Okay, you can check out the branch `pr-7186-v0-15-5-branch` which is `v0.15.5-beta` with a rebased version of #7186 on top. So `git fetch && git checkout pr-7186-v0-15-5-branch`.

Thank you. I go to do it! Thanks!

**Comment by guggero** [comment]
That PR also adds some additional logging. If you could set `DISC=debug` that would also help figure out what the problem is (if this doesn't fix it).

**Comment by LNBIG-COM** [comment]
> Okay, you can check out the branch `pr-7186-v0-15-5-branch` which is `v0.15.5-beta` with a rebased version of #7186 on top. So `git fetch && git checkout pr-7186-v0-15-5-branch`.

Question - I am currently doing this on lnd-25 (old lnd-02), but if the problem is on the receiving nodes of gossip, then it turns out that I need to run this version on the contrary - on all other nodes except lnd-25?

**Comment by bitromortac** [comment]
You would need to run it on a node that doesn't have an accurate node announcement from the updated node.

**Comment by LNBIG-COM** [comment]
> You would need to run it on a node that doesn't have an accurate node announcement from the updated node.

Ok, I will do it now... But I updated already the lnd-25. I hope this won't spoil the purity of the experiment?

**Comment by guggero** [comment]
> I can downgrade it for clean experiement, @guggero ?

Yes, if you use the branch I created you will be able to downgrade to `v0.15.5-beta` normally.

**Comment by LNBIG-COM** [comment]
lnd-20 (patched) has old info about lnd-02, after `DISC=debug` there I see in lnd-20 a following lines only:

```
2022-12-02 12:55:32.559 [DBG] DISC: Processing NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 12:53:33 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
2022-12-02 12:55:33.073 [DBG] DISC: Processed NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 12:53:33 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
```

I don't see a packet info there. In that time I at lnd-25 (lnd-02 old) did a `lncli peers updatenodeannouncement` commands. Now I restarted the lnd-25 with DISC=debug option and I wait of starting. I will see there logs...

**Comment by LNBIG-COM** [comment]
lnd-25 patched:

```
date; l peers updatenodeannouncement --address_remove '213.174.156.69:9735' --alias 'LnBiG.com [lnd-25/lnd-02]'
Fri Dec  2 13:09:00 CET 2022
{
    "ops": [
        {
            "entity": "alias",
            "actions": [
                "changed to LnBiG.com [lnd-25/lnd-02]"
            ]
        },
        {
            "entity": "addresses",
            "actions": [
                "213.174.156.69:9735 removed"
            ]
        }
    ]
}
```

lnd-20 patched:

```
2022-12-02 13:10:33.334 [DBG] DISC: Processing NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:09:00 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
2022-12-02 13:10:33.868 [DBG] DISC: Processed NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:09:00 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
```

lnd-25 patched:

```
date; l peers updatenodeannouncement --address_add $(dig +short a ip-external) --alias 'LNBiG.com🇺🇦[lnd-25/lnd-02]'
Fri Dec  2 13:09:20 CET 2022
{
    "ops": [
        {
            "entity": "alias",
            "actions": [
                "changed to LNBiG.com🇺🇦[lnd-25/lnd-02]"
            ]
        },
        {
            "entity": "addresses",
            "actions": [
                "213.174.156.69:9735 added"
            ]
        }
    ]
}
```

lnd-20 patched:

```
2022-12-02 13:12:02.805 [DBG] DISC: Processing NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:09:20 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
2022-12-02 13:12:03.329 [DBG] DISC: Processed NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:09:20 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
```

It's all...

**Comment by LNBIG-COM** [comment]
@guggero , you patch works at lnd-20 (removing/adding IP and changing alias)! Some commands and logs. And gossip only from `024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf` peer (deezy). No other announcements from other nodes including my ones! So I think propograing of nodeannouncement doesn't work in current LND.

```
lnd-25:

date; l peers updatenodeannouncement --address_remove $(dig +short a ip-external) --alias 'LnBiG.com🇺🇦[lnd-25/lnd-02]'
Fri Dec  2 13:24:34 CET 2022
{
    "ops": [
        {
            "entity": "addresses",
            "actions": [
                "213.174.156.69:9735 removed"
            ]
        }
    ]
}

lnd-20:

2022-12-02 13:27:02.850 [DBG] DISC: Processing NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:24:34 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
2022-12-02 13:27:03.369 [DBG] DISC: Processed NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:24:34 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618

l getnodeinfo 03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618|grep -E 'alias|addr'
        "alias": "LnBiG.com🇺🇦[lnd-25/lnd-02]",
        "addresses": [
                "name": "payment-addr",

lnd-25:

date; l peers updatenodeannouncement --address_add $(dig +short a ip-external) --alias 'LNBiG.com🇺🇦[lnd-25/lnd-02]'
Fri Dec  2 13:27:23 CET 2022
{
    "ops": [
        {
            "entity": "alias",
            "actions": [
                "changed to LNBiG.com🇺🇦[lnd-25/lnd-02]"
            ]
        },
        {
            "entity": "addresses",
            "actions": [
                "213.174.156.69:9735 added"
            ]
        }
    ]
}

lnd-20:

2022-12-02 13:29:57.732 [DBG] DISC: Processing NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:27:23 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618
2022-12-02 13:29:58.254 [DBG] DISC: Processed NodeAnnouncement: peer=024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf@52.1.72.207:9735, timestamp=2022-12-02 13:27:23 +0100 CET, node=03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618

l getnodeinfo 03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618|grep -E 'alias|addr'
        "alias": "LNBiG.com🇺🇦[lnd-25/lnd-02]",
        "addresses": [
                "addr": "213.174.156.69:9735"
                "name": "payment-addr",
```

Now I'll see what happens on lnd-21 (not-patched yet!) when debugging `DISC=debug` is enabled...

**Comment by LNBIG-COM** [comment]
When I change Alias at lnd-25 I see in lnd-21 a following lines only from other nodes:

```
2022-12-02 13:42:03.189 [DBG] DISC: Processing network message: peer=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776@170.75.170.33:51960, source=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:03.209 [DBG] DISC: Processing network message: peer=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776@170.75.170.33:51960, source=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:03.209 [DBG] DISC: Processing network message: peer=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776@170.75.170.33:51960, source=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:03.209 [DBG] DISC: Processing network message: peer=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776@170.75.170.33:51960, source=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:30.270 [DBG] DISC: Processing network message: peer=033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025@34.65.85.39:9735, source=033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:32.699 [DBG] DISC: Processing network message: peer=039f121dc02dbaf102d2003d3dac09a636067badb782e5bc09fe2547f688f79bde@93.95.226.212:41156, source=039f121dc02dbaf102d2003d3dac09a636067badb782e5bc09fe2547f688f79bde, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:42:35.009 [DBG] DISC: Processing network message: peer=0366d8a3608b352daca0d29c6c0ca464be81bef261153339b2571da8e1f7ff8228@23.128.248.16:35825, source=0366d8a3608b352daca0d29c6c0ca464be81bef261153339b2571da8e1f7ff8228, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:43:26.088 [DBG] DISC: Processing network message: peer=02a8ecd5eddc7e2b0a34c9bfdff8c5e1e767e1e8e987d87516c43bd16de89a8cec@45.61.184.137:17106, source=02a8ecd5eddc7e2b0a34c9bfdff8c5e1e767e1e8e987d87516c43bd16de89a8cec, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:44:03.190 [DBG] DISC: Processing network message: peer=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776@170.75.170.33:51960, source=036578a930856b958fa6ee136cf27a1620c48a2280a3315257b33bd1b58174a776, msg=NodeAnnouncement, is_remote=true
2022-12-02 13:44:12.499 [DBG] DISC: Processing network message: peer=03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7@118.163.74.161:49481, source=03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7, msg=NodeAnnouncement, is_remote=true
```

It is striking that all the strings have the nodeid of the peer equal to source's nodeid. If I understand correctly, source is the node that made the NodeAnnouncement, and peer is who sent it. If this is the case, then everything is quite strange - there should be a lot of lines from peers that relay announcements from other peers, that is, source should not coincide with peer

**Comment by LNBIG-COM** [comment]
I want to note that lnd-21 does not have a direct connection (as peer) to lnd-25 (old lnd-02) and does not  have with lnd-20. 

A few months ago I started using the "star" scheme with three nodes ("hub"): 'lnd-19', 'lnd-22', 'lnd-49'. That is, these three nodes are connected to each other by fat channels, and the remaining 22 nodes are each connected to these three. Therefore, **if the lnd accepts signed messages only by the nodes from which it receives them**, this explains why many of my nodes do not know about the address change of my other nodes. However, for example, node lnd-05 had a new IP address about lnd-25. But this could happen from the fact that he once had a direct connection from lnd-25 and got signed NodeAnnouncement from lnd-25 directly. There is no such connection now.

**Comment by guggero** [comment]
> So I think propograing of nodeannouncement doesn't work in current LND.

> I want to note that lnd-21 does not have a direct connection (as peer) to lnd-25 (old lnd-02) and does not have with lnd-20.

If you don't have a direct connection that would mean there's a node inbetween your nodes that is not patched. Which would explain why it it doesn't work reliably yet. So if the patch indeed fixes the propagation issue as well then it should get better and better once nodes update (once we release the patch).
But keep in mind that there's also always a time component in there, if you do too many updates in a short time you still might be throttled, even with the patch applied.

Catching up on all the other messages, trying to find out if the `peer == source` is just unfortunate logging or an issue indeed.

**Comment by guggero** [comment]
Okay, so the `source` field should indeed be the original sender of the message. But assuming that nodes without the patch don't yet correctly propagate announcements, seeing `peer == source` would make sense. Unless you have `A <-> B <-> C` with all patched nodes (your nodes), then when updating something on node A you should see node C receive that with `source=A, peer=B`. Not sure if you could maybe test that with how your nodes are set up?

**Comment by LNBIG-COM** [comment]
After all, I wrote above that the lnd-21 (not patched by you) node outputs to the log only those messages where  source==peer only. There are no others there! Therefore, I conclude that the current version 0.15.4 and 0.15.5 accept (without your patch) only those messages where source == peer. 

This may explain why for more than a week the majority of the network has not been aware of the lnd-02 changes - they simply do not pass due to a bug in the LND! And therefore on 1ml.com and amboss.space the old IP - they work on LND.

**Comment by LNBIG-COM** [comment]
@guggero , can I apply your patch (the branch `pr-7186-v0-15-5-branch`) for all my nodes now? What do you think?

**Comment by LNBIG-COM** [comment]
> Catching up on all the other messages, trying to find out if the `peer == source` is just unfortunate logging or an issue indeed

I did only this at lnd-21:

```
$ grep NodeAnnouncement mainnet-lnd-run.log |grep 'DBG' > 1.txt
$ wc -l 1.txt
3496 1.txt
$ sed -r -e 's/.*peer=([a-f0-9]+)@.*?source=([a-f0-9]+),.*/\1 \2/' 1.txt|awk 'BEGIN{a=0; b=0;}{if ($1 == $2) {a++;} else {b++;} } END{print "a="a", b="b}' 
a=3496, b=0
```

**Comment by hazrulnizam** [comment]
I am encountering this issue as well. My node changed IP address after a power failure a few weeks ago, but explorers such as amboss.space and 1ml.com seem to not take this change into account.

However, I know gossip was propagated because other explorers such as lightningnetwork.plus and mempool.space did update my node's information to the new IP address.

I suspect explorers that use LND as their backend are not processing this information change properly while others that are using other implementations do not have this problem.

**Comment by guggero** [comment]
> After all, I wrote above that the lnd-21 (not patched by you) node outputs to the log only those messages where source==peer only. There are no others there! Therefore, I conclude that the current version 0.15.4 and 0.15.5 accept (without your patch) only those messages where source == peer.

Yes, I understand that. What I would like to know is whether on a node you patched, do you see messages where `peer != source`? Meaning: Is the patch definitely working at fixing the propagation bug?

> can I apply your patch (the branch pr-7186-v0-15-5-branch) for all my nodes now? What do you think?

Sure, if you think the patch is working it might make sense to roll it out more widely.

**Comment by spyhuntergenral** [comment]
I was wondering why my node IP was not updating on 1ml, (when everything looked fine on my end), this all makes sense now, 
This kind of issue, should really be a P0 and i would suspect the majority of node operators that have had an ip change on the affected versions aren't even aware, that most of the network cannot see there node anymore. 

Good troubleshooting above!

**Comment by LNBIG-COM** [comment]
> Yes, I understand that. What I would like to know is whether on a node you patched, do you see messages where `peer != source`? Meaning: Is the patch definitely working at fixing the propagation bug?

I have written to you about this a long time ago and exactly what you are asking.

https://github.com/lightningnetwork/lnd/issues/7223#issuecomment-1335168902

> you patch works at lnd-20 (removing/adding IP and changing alias)!

2022-12-02 13:29:57.732 [DBG] DISC: Processing NodeAnnouncement: peer=**024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf**@52.1.72.207:9735, timestamp=2022-12-02 13:27:23 +0100 CET, node=**03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618**
2022-12-02 13:29:58.254 [DBG] DISC: Processed NodeAnnouncement: peer=**024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf**@52.1.72.207:9735, timestamp=2022-12-02 13:27:23 +0100 CET, node=**03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618**

So peer != source

**Comment by LNBIG-COM** [comment]
> operators that have had an ip change on the affected versions

As far as I understand, the root of the problem is the reason in the receiving nodes. That is, it doesn't matter which version you have when you change IP or Alias - it matters which version is on another node, on which much may depend (1ml, amboss or may be router node).

**Comment by LNBIG-COM** [comment]
> Sure, if you think the patch is working it might make sense to roll it out more widely.

Now, after a little thought, it seems to me that it is very important to apply the patch not to me, but so that it is applied in the new release as soon as possible (@Roasbeef  ?)!  It may be that by fixing myself, I will solve the problem of updating IP addresses in the graph only between my nodes and some that are connected to me. But this will not solve the problems about the main part of the network - they will still have the old IP addresses. Just because they have the current version of LND (1ml, amboss and other big nodes)!

I still believe that the problem may be due to what I described here:

https://github.com/lightningnetwork/lnd/issues/7223#issuecomment-1335180169

**Comment by yyforyongyu** [comment]
> It is striking that all the strings have the nodeid of the peer equal to source's nodeid. If I understand correctly, source is the node that made the NodeAnnouncement, and peer is who sent it.

No, they are the same node, both meaning the peer who relayed the message. The log needs to be updated a bit tho to make it more clear, and this is the [code](https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L757-L758).

> A few months ago I started using the "star" scheme with three nodes ("hub"): 'lnd-19', 'lnd-22', 'lnd-49'. That is, these three nodes are connected to each other by fat channels, and the remaining 22 nodes are each connected to these three.

I'm trying to understand the topology here. So each node is connecting to the three start nodes right? And these star nodes are also connected to each other? What about the non-star nodes?

**Comment by Roasbeef** [comment]
Just created #7239 which aims to make sure we prioritize broadcasting our local announcements.
