### ISSUE TITLE
Interoperability: Cannot open zero conf anchor channel to core lightning node

### ISSUE THREAD

**Issue by JssDWt** [lightningnetwork/lnd#7230]
### Background
There is an incompatibility between LND and CLN currently. LND is unable to open a zero conf anchor channel to a CLN node, because LND sets the required feature option_anchors_zero_fee_htlc_tx, which CLN does not support.

### Your environment

* v0.15.4

### Steps to reproduce

- Spin up an LND node with --protocol.zero-conf and --protocol.option-scid-alias
- Spin up a CLN node with a zero conf accepting plugin
- Open a channel from LND to CLN with commitmenttype anchors and zero conf
- Feature negotation will fail, because CLN does not support `option_anchors_zero_fee_htlc_tx`, the error is `requested channel type not supported`

### Expected behaviour

LND negotiates an anchor channel with CLN without `option_anchors_zero_fee_htlc_tx`

### Actual behaviour

Feature negotation will fail, because CLN does not support `option_anchors_zero_fee_htlc_tx`, the error is `requested channel type not supported`

Here's the relevant lines that add `option_anchors_zero_fee_htlc_tx` as a required feature: https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L2064-L2068

Since this is an interoperability issue, here's the issue in the core lightning repository: https://github.com/ElementsProject/lightning/issues/5770

**Comment by Roasbeef** [comment]
>  because LND sets the required feature option_anchors_zero_fee_htlc_tx, which CLN does not support.

Yes we only support zero fee anchors. CLN is working on finalizing their implementation, I think on target to ship w/ their next major implementation. 

Given that there's a tracking issue in the CLN repo, I think we can close this now?

**Comment by Roasbeef** [comment]
@JssDWt correct. I don't think they're very far off though.

**Comment by JssDWt** [comment]
Closing in favor of https://github.com/ElementsProject/lightning/issues/5770
