### ISSUE TITLE
[bug]: Unable to lookup SRV records via primary seed on machine with multiple network interfaces

### ISSUE THREAD

**Issue by mishfit** [lightningnetwork/lnd#7235]
### Background

```
022-12-05 17:11:21.778 [TRC] DISC: Unable to lookup SRV records via primary seed (nodes.lightning.directory): lookup _nodes._tcp.nodes.lightning.direct     ory on 10.0.1.1:53: read udp 10.0.1.31:44770->10.0.1.1:53: i/o timeout
```

### Your environment

* version of `lnd`: `0.15.5-beta`
* which operating system (`uname -a` on *Nix) : `debian 11 bullseye`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind v23.0.0`
* any other relevant environment details

There are 2 physical interfaces mapped to 6 ipv4 addresses. `lnd` is using an internal only ip address to perform the DNS lookup and there's no way to force it to use the other interface even though it is listening only on the correct address using `--listen=`.

### Steps to reproduce

Setup an up to date linux machine with an internal and an external network. Setup `lnd` to listen only on the external network. 

### Expected behaviour

`lnd` should find peers using the external network

### Actual behaviour

`lnd` is unable to find bootstrap peers

**Comment by positiveblue** [comment]
I think lnd is using the [default dns resolver in pure go](https://pkg.go.dev/net#hdr-Name_Resolution). 

Are you using a custom docker image/setting `GODEBUG=netdns=cgo`? This is [what we do](https://github.com/lightningnetwork/lnd/blob/master/Dockerfile#L11) it in our docker image.

**Comment by mishfit** [comment]
That appears to have resolved it.
