### ISSUE TITLE
REST api returning "Not found" for various APIs

### ISSUE THREAD

**Issue by starrymoonlight** [lightningnetwork/lnd#724]
When I run several commands via REST api, they are successful for example: 
curl -k https://localhost:8001/v1/getinfo
{"identity_pubkey":"034497ff44f0c70cb11eee1f692b4807320810c1c6af91f95f06f581e8ea806155","alias":"034497ff44f0c70cb11e","block_height":1118,"block_hash":"6dab0eab1cdea0e7c4da0ecffc71532fd87204035b49523d7422aac0500ff276","chains":["bitcoin"]}

But some of the other documented APIs return "Not Found":

$ curl -k https://localhost:8001/v1/listpeers
Not Found
$ curl -k https://localhost:8001/v1/sendcoins
Not Found

**Comment by Roasbeef** [comment]
We definitely need to document the REST interface better. For now, you've gotta look directly at the proto file: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L178

For example: 
```
⛰ curl -k https://localhost:8089/v1/peers
{}%
  master ✘ ✭  roasbeef  ...github.com/lightningnetwork/lnd 
⛰ curl -k https://localhost:8089/v1/balance/channels
{}%
```

**Comment by starrymoonlight** [comment]
That gave me what I need. Thx!

**Comment by starrymoonlight** [comment]
Sorry to bug you again on this, but it seems from the page you linked, the addinvoice command links to '/v1/invoices?amt=XXXXX'. When I try that command via curl, it returns a list of invoices but does not add the invoice that I'm trying to add. Any way I can understand better how these APIs work? I tried looking through the code, but having no luck. I also have a similar question about the sendpayment command.

**Comment by Roasbeef** [comment]
You need to ensure you're using a POST method as required. If you send a GET to `/v1/invoices`, it'll return all the known invoices. The sendpayment command is _also_ a POST.

**Comment by MMuArFF** [comment]
to help https://app.swaggerhub.com/apis/lnd-rest/rpc-proto/master
some php work with rest api here : https://gitlab.com/MMuArFF/lnd-php-wallet
