### ISSUE TITLE
[bug]: itest: regtest difficulty retarget for backend=bitcoind

### ISSUE THREAD

**Issue by morehouse** [lightningnetwork/lnd#7241]
### Background

bitcoind disables difficulty retargeting on regtest, while btcd does not.  When we run itests with `backend=bitcoind`, the btcd miner generates blocks and sends them to the bitcoind backend.  If btcd modifies the difficulty target, its mined blocks get rejected by bitcoind.

So far, we seem to have avoided this issue because our itests generate fewer than 4032 blocks in aggregate (the first retarget at block 2016 doesn't modify difficulty).  But #7228 adds a test that pushes us over 4032 blocks, so the new itests are failing in CI.

### Steps to reproduce

See #7228 CI.  Look at the new itests with `backend=bitcoind`.

### How to fix

There are multiple ways to fix this.  Some ideas:

- Make btcd regtest behavior match bitcoind (or add an option for this).
- Restart miner when it gets close to the retarget height.
- Use bitcoind to mine blocks instead of btcd.

**Comment by Roasbeef** [comment]
Related issues: https://github.com/lightninglabs/neutrino/issues/255 https://github.com/btcsuite/btcd/issues/1819

**Comment by yyforyongyu** [comment]
> Restart miner when it gets close to the retarget height.

I thought about this too. Not relating to retargeting but in general it should make our itest faster.

**Comment by guggero** [comment]
Fixed for `btcd` in  https://github.com/btcsuite/btcd/pull/1985 and for Neutrino in https://github.com/lightninglabs/neutrino/pull/281.
