### ISSUE TITLE
[bug]: Lnd does not update the localbalance fast enough when doing fast rebalances

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7246]
### Background

I was implementing fast rebalances when I noticed that I overshooted my target, after logging the ouput it seems like lnd is lagging behind in updating the localchannelbalance. In the following I have an example.

I was using golang and  the rpc-request `ListChannelsRequest` with the Peer specified to fetch the channelbalance from lnd
1. Initial Channelbalance before the rebalance started : 1515505,3483113
2. First attempt is tried with 20k (it got paid) no channel balances printed
3. Now 40k is tried => now we see the channelbalance of local 1515505 and 3463113 (-20k) expected also a different local here
4. Now 80k is tried (rapid rebalance attempt 2)  local  1535505 (only -20k) and remote 3423113 (-40k) expected 1555505 local
5. Now 40k is tried again (going back the binary tree) local 1575505 (+40k) and remote 3343113 (-80k) expected 1655505 local
6. Now 20 k is tried local 1695505 (+120k) and remote 3303208 (-40k) now everything seems to got caught up again
7. finished

My question is, how it could be that local and remote balance of a channel does not change in the same cycle. It seems to be lagging behind. If you wanna checkout the code with which I simulated this behaviour checkout: https://github.com/rkfg/regolancer/pull/45/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L249

Grateful for any further help :)

```
2022/12/12 14:56:50 Attempt #1, amount: 20000 (max fee: 1 sat | 50 ppm )
Total fee: 0.481 sat | 24 ppm
818079532063981568        [x|NordicRails|260ch|25.47,537,182sat|033d9e73a183c9714545f292875fb90c4372bddc9c2cc302b265d15e7969a5ed60]
837793775601319937 0      [x|Sunny Sarah ☀️|314ch|26.66,398,027sat|03423790614f023e3c0cdaa654a3578e919947e4c3a14bf5044e7c787ebd11af1a]
829510054964756481 0      [x|RatPoisonSquared|57ch|3.01,017,195sat|03ae641aa89c4d2c0034b31bad23a4f80f841d593ddd52f7f35cf7896d0ef8a594]
800634680599314433 81     [x|02f324df7694f57b7d80|178ch|9.30,451,969sat|02f324df7694f57b7d800d5a64f62fb226eabc8fbacb997f3ac5cd230e37944fbf]
800525829038538753 400    [x|RISE_AND_GRIND|68ch|3.18,545,455sat|02826f50035eca93c7ebfbad4f9621a8eb201f4e28f994db5b6b5af32a65efb6b9]

2022/12/12 14:56:59 Success! Paid 0.481 in fees, 24 ppm

2022/12/12 14:56:59 Rapid rebalance attempt 1, amount: 40000
2022/12/12 14:57:00 localbalance 1515505,3463113, 800525829038538753,722,1288
2022/12/12 14:57:00 remoteBalance 2093328, 818079532063981568
2022/12/12 14:57:00 rapid fire starting with amount 40000

2022/12/12 14:57:09 Success! Paid 0.961 in fees, 24 ppm

2022/12/12 14:57:09 Rapid rebalance attempt 2, amount: 80000
2022/12/12 14:57:09 localbalance 1535505,3423113, 800525829038538753,722,1288
2022/12/12 14:57:09 remoteBalance 2093233, 818079532063981568
2022/12/12 14:57:09 rapid fire starting with amount 80000

2022/12/12 14:57:19 Success! Paid 1 in fees, 24 ppm

2022/12/12 14:57:19 Rapid rebalance attempt 3, amount: 40000
2022/12/12 14:57:19 localbalance 1575505,3343113, 800525829038538753,722,1288
2022/12/12 14:57:19 remoteBalance 2213331, 818079532063981568
2022/12/12 14:57:19 rapid fire starting with amount 40000

2022/12/12 14:57:34 Success! Paid 0.961 in fees, 24 ppm

2022/12/12 14:57:34 Rapid rebalance attempt 4, amount: 20000
2022/12/12 14:57:34 localbalance 1695505,3303208, 800525829038538753,627,1116
2022/12/12 14:57:34 remoteBalance 2213236, 818079532063981568
2022/12/12 14:57:34 rapid fire starting with amount 20000

2022/12/12 14:57:43 Success! Paid 0.481 in fees, 24 ppm

2022/12/12 14:57:43 4 rapid rebalances were successful
2022/12/12 14:57:43 Finished rapid rebalancing
2022/12/12 14:57:43 Saving node cache to nodecache.db

```

### Your environment

* version of `lnd`: lnd 15.5
* linux armv8

**Comment by Roasbeef** [comment]
> My question is, how it could be that local and remote balance of a channel does not change in the same cycle. It seems to be lagging behind.

So internally, our local balance comes from our view of _our_ version of the commitment transaction. When you initiate a new state, our version is the one that's updated last (remote party gets a sig, revokes, then sends a sig to us). During the update process, things are fully consistent, eg: you could modify lnd to _stop_ after it gets a sig to confirm that it isn't reflected there as we only look at the final remote local commitment.

AFAICT, nothing is out of place here and it might be an issue w/ logging timestamps (looking above it all happens within 20 seconds or so of each other). Also it's the case that if concurrent updates are in flight (eg: the other side is also rebalancing at the same time), it may take an extra state or two for the asymmetric commitments to be fully synchronized (w/ the current state machine, no side ever blocks to wait for the other to do something).

**Comment by ziggie1984** [comment]
(Maybe its important but I disabled forwarding bos tools). Thanks for the quick reply, so to conclude the balances I see there are currently the settled balances for local and remote of my Commitment Tx? Meaning that at the time of querying my channel it had exactly the local and remote balance. But what I don't really get, I am checking to the SendToRouteV2 method to report back, so basically this function will only report if funds are settled or ? Only then am I querying the channelstate,  so I anticipated that at least the channel state is fully updated with the amount I send prior before the SendToRouteV2 method reports a success ?

**Comment by ziggie1984** [comment]
Because of the Lightning Protocol it could happen that my peers send me an incoming HTLC which I will accept and fail immediately (disabling forwards) and by the time it coincidentally messes up my local amount.  Thats a scenario but whats so interesting that it adds up exactly with the anticipated balances. always one cycle behind and then boom it catches up again. I mitigated this behavior in the software by also checking the remote amount before rebalancing which tends to fix the issue for my use case, but just wanted to bring it up. Thanks for the feedback :)

**Comment by saubyk** [comment]
Closing this issue, as there is no expected action to take here. Feel free to open a discussion or an issue if further inputs are needed.
