### ISSUE TITLE
Bitcoind cannot run lnd, zmq issues

### ISSUE THREAD

**Issue by yashbhutwala** [lightningnetwork/lnd#725]
I'm running into issues trying to run lnd with a bitcoind testnet backend. I've made sure bitcoind is configured with zeromq, but lnd still says connection refused. Following is my bitcoind configs:

```
testnet=1
server=1
rest=1
rpcallowip=127.0.0.1
txindex=1
zmqpubhashtx=tcp://127.0.0.1:18501
zmqpubrawtx=tcp://127.0.0.1:18501
zmqpubrawblock=tcp://127.0.0.1:18501
```

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/5788514/35772039-27aecb16-0905-11e8-9c6d-8e1d0e93f561.png">

**Comment by yashbhutwala** [comment]
Yup, I tried building `bitcoind` from scratch. Is there a way to check if it is enabled?

**Comment by Roasbeef** [comment]
> Is there a way to check if it is enabled?

Atm, just gotta try to use it. If it isn't enabled, you'll get failures like this. 

Double check that you have this installed: https://github.com/zeromq/libzmq

**Comment by yashbhutwala** [comment]
Definitely have it installed.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/5788514/35772152-092cf72e-0907-11e8-9b66-ce15cb85c2c3.png">

**Comment by Roasbeef** [comment]
Can you confirm that your `bitcoind` is _indeed_ listening on those require ports?

**Comment by yashbhutwala** [comment]
You're right, it seems bitcoind is not listening on those ports. I'm not sure what to try next; already tried rebuilding bitcoind and refreshing network settings.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/5788514/35772540-59fbbf70-090f-11e8-88d5-2df18fbdcc82.png">

**Comment by Roasbeef** [comment]
Closing this as this isn't an issue with `lnd`, you just need to compile `bitcoind` properly. Ideally `bitcoind` adds a warning if you try to use `zmq` without it properly being linked in. You may want to open an issue on their tracker concerning this.
