### ISSUE TITLE
Issue in unconfirmed transaction in LND

### ISSUE THREAD

**Issue by Neoblock8** [lightningnetwork/lnd#7255]
Hi,
  Am running bitcoin and LND server. I have unconfirmed balance in LND, but the transaction has been confirmed in bitcoin explorer.
  Why this issue happens? Kindly solve this issue.

### Your environment
* version of `lnd`
lnd version 0.12.1-beta commit=v0.12.1-beta  

* which operating system (`uname -a` on *Nix)
Linux 20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux   

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core version v23.99.0

**Comment by GeorgeTsagk** [comment]
Hi @Neoblock8 

How many confirmations did the tx have on the explorer at the time you observed this behavior?

Does the balance still appear as unconfirmed today?

**Comment by Neoblock8** [comment]
> Hi @Neoblock8
> 
> How many confirmations did the tx have on the explorer at the time you observed this behavior?
> 
> Does the balance still appear as unconfirmed today?

Hi @GeorgeTsagk 

     It has 8474 confirmations for that transaction. Yes, Still it is in unconfirmed state

**Comment by alexbosworth** [comment]
did you try updating lnd to the latest version

**Comment by Neoblock8** [comment]
> did you try updating lnd to the latest version

Hi @alexbosworth 

    I tried with latest version. But Iam getting this error.
    "**error creating wallet config: unable to create partial chain control: unable to subscribe for zmq tx events: dial tcp 0.0.0.0:0: i/o timeout** "
    
    **Command for running BTC:** bitcoind -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -zmqpubhashtx=tcp://0.0.0.0:28333 -zmqpubrawblock=tcp://0.0.0.0:28332

    **Command for running LND:** lnd --bitcoin.mainnet --bitcoin.active --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=XYZ --bitcoind.rpcpass=ABC --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=8332
   
    **LND Version:** "lnd version 0.15.99-beta commit=tlv/v1.1.0-51-gd9febbb9f-dirty  "

**Comment by guggero** [comment]
You need to set `--bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333` instead of just `8332`.
Also, please don't update to `lnd` master but instead use the latest [released version](https://github.com/lightningnetwork/lnd/releases/tag/v0.15.5-beta)

**Comment by guggero** [comment]
Closing the issue as the potential solution was offered. Feel free to re-open if the problem persists after fixing the ZMQ related flags.
