### ISSUE TITLE
[bug]: "synced_to_chain": false even the actual block height shows up

### ISSUE THREAD

**Issue by lingo21m** [lightningnetwork/lnd#7259]
### Background

Because of electricity cut off for several days my node (raspiblitz) went offline. Currently I have no peers. I tried to add a new peer and I am receiving the info that the lnd daemon could be down.

### Your environment

lnd version 0.15.5-beta commit=v0.15.5-beta
Bitcoin Core version v23.0.0

### Steps to reproduce

lncli getinfo

 "synced_to_chain": false,

bitcoin.conf

   "synced_to_chain": false,

# bitcoin.conf:

 bitcoind configuration
some values might be overruled directly systemd-service exec call parameters

 mainnet/testnet
testnet=0

 Bitcoind options
server=1
daemon=1
txindex=0
disablewallet=1
peerbloomfilters=1
datadir=/mnt/hdd/bitcoin

Connection settings
rpcuser=raspibolt
rpcpassword=passwordB
main.rpcport=8332
test.rpcport=18332
rpcallowip=127.0.0.1
main.rpcbind=127.0.0.1:8332
test.rpcbind=127.0.0.1:18332
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

 Raspberry Pi optimizations
dbcache=128
maxorphantx=10
maxmempool=300
maxconnections=40
maxuploadtarget=5000

tor by default
onlynet=onion
proxy=127.0.0.1:9050
main.bind=127.0.0.1
test.bind=127.0.0.1
dnsseed=0
dns=0

#  lnd.conf

[Application Options]
debuglevel=debug
maxpendingchannels=5
alias=
color=#68F442
nat=false

Avoid historical graph data sync
ignore-historical-gossip-filters=1
Avoid slow startup time
sync-freelist=1
Avoid high startup overhead
stagger-initial-reconnect=1

 Delete and recreate RPC TLS certificate when details change or cert expires
tlsautorefresh=1
 Do not include IPs in the RPC TLS certificate
tlsdisableautofill=1

RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
 REST open to all connections on Port 8080
restlisten=0.0.0.0:8080

[Bitcoin]
bitcoin.active=1
bitcoin.node=bitcoind
 enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6

[bolt]
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=672h

[bitcoind]
bitcoind.rpchost=127.0.0.1:8332
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[workers]
workers.sig=4
workers.write=4

[tor]
tor.active=true
tor.v3=true
tor.privatekeypath=/mnt/hdd/lnd/v3_onion_private_key
tor.socks=9050
tor.control=9051

### Expected behaviour

 "synced_to_chain": true when I run lncli getinfo

### Actual behaviour

 "synced_to_chain": false when I run lncli getinfo

**Comment by positiveblue** [comment]
what is the `block_height` your lnd sees? `lncli getinfo | grep block_height`

What is the output of `bitcoin-cli --getinfo` for the node your lnd is connected to?

**Comment by Tommzs** [comment]
Hello,
I have the same issue. Any idea what could be wrong? I think it happened some time after lnd v0.15.2-beta release. I have tested updating to 0.15.5-beta and also updating the bitcoind, restarting RPI, but so far no change.

Response to commands @positiveblue specified:
$ bitcoin-cli --getinfo
Chain: main
Blocks: 768255
Headers: 768255
Verification progress: 99.9997%
Difficulty: 35364065900457.12

Network: in 11, out 10, total 21
Version: 240001
Time offset (s): 0
Proxies: 127.0.0.1:9050 (ipv4, ipv6, onion, cjdns)
Min tx relay fee rate (BTC/kvB): 0.00001000

Warnings: (none)
$ lncli getinfo | grep block_height
    "block_height": 768255,

---------------------------------------------------------------------------------
-----[bitcoin.conf]-----
# RaspiBolt: bitcoind configuration
# /home/bitcoin/.bitcoin/bitcoin.conf

# Bitcoin daemon
server=1
txindex=1

# File permissions, necessary for cookie authentication
sysperms=1
disablewallet=1

# Network
listen=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1

# Connections
rpcauth=[removed]
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
whitelist=download@127.0.0.1          # for Electrs

# Raspberry Pi optimizations
maxconnections=40
maxuploadtarget=5000

# Initial block download optimizations
#dbcache=2000
#blocksonly=1

-----[lnd.conf]-----
# RaspiBolt: lnd configuration
# /data/lnd/lnd.conf

[Application Options]
alias=[removed]
debuglevel=info
maxpendingchannels=5
listen=localhost
backupfilepath=/mnt/data/lnd-backup/channel.backup
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0
restlisten=localhost:8080
# Password: automatically unlock wallet with the password in this file
# -- comment out to manually unlock wallet, and see RaspiBolt guide for more secure options
wallet-unlock-password-file=/data/lnd/password.txt
wallet-unlock-allow-create=true

# Channel settings
bitcoin.basefee=1000
bitcoin.feerate=1
minchansize=100000
accept-amp=true
protocol.wumbo-channels=true
protocol.no-anchors=false
coop-close-target-confs=24

# Watchtower
wtclient.active=true

# Performance
gc-canceled-invoices-on-startup=true
gc-canceled-invoices-on-the-fly=true
ignore-historical-gossip-filters=1
sync-freelist=true
stagger-initial-reconnect=true
routing.strictgraphpruning=true

# Database
[bolt]
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=168h

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

**Comment by Tommzs** [comment]
Small update...
after another reboot I actually got "synced_to_chain": true,
however "synced_to_graph" is still false.

**Comment by yyforyongyu** [comment]
> Because of electricity cut off for several days my node (raspiblitz) went offline.

I think it's expected to have `synced_to_chain` be false as the node needs time to sync.

**Comment by lingo21m** [comment]
Yes the update to 0.15.5-beta and restart and waiting some hours did it for me aswell. I think it was related to the lnd bug found in the version 0.10.0 or something...
