### ISSUE TITLE
[feature]: Avoid recreating ChannelUpdates for disabled channels

### ISSUE THREAD

**Issue by matheusd** [lightningnetwork/lnd#7269]
ChannelUpdates are [updated, signed and re-transmitted](https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L1484) every 24 hours for every channel of the node.

This seems somewhat undesirable for channels that have been disabled and cannot be used for routing anymore: sending refreshed ChannelUpdates keeps the channels present in the overall network graph (of other nodes), even though the channel may be in fact never again become active. This also prevents active clients in the network from pruning nodes that have no active channels anymore, because their counterparty may still be signing ChannelUpdates.

For those reasons, it seems it would be better to avoid refreshing the ChannelUpdate if the update is for a disabled edge.

Additionally, it would probably be helpful to avoid updating the local view of remote edges if the only change received in the corresponding ChannelUpdate for a disabled edge is a timestamp update. This would make it possible to track the time when the first update that disabled an edge was received so that information could be used to prune remote channels and nodes that have been disabled for too long.

The change to avoid refreshing disabled edges is a simple one. I'm looking for clarification on whether that would in fact be a desired behavior prior to sending a PR to address it.

Somewhat related to https://github.com/lightningnetwork/lnd/pull/5817

**Comment by alexbosworth** [comment]
I think if you enable strict pruning then both sides do need to sign updates otherwise the node will be pruned

**Comment by matheusd** [comment]
Ah, thank you! I wasn't aware of that config option.

**Comment by alexbosworth** [comment]
It could still be interesting to control announcement behavior, maybe separately
