### ISSUE TITLE
[bug]: Channels are disconnected after an "unknown message" error

### ISSUE THREAD

**Issue by ekimber** [lightningnetwork/lnd#7273]
### Background

Channels with core lightning nodes (most recent 22.11 version and master) frequently disconnect after an "unknown message" error

### Your environment

* version of `lnd` 0.15.5-beta
* 5.15.81 1-NixOS x86_64
* bitcoind v.24.01

### Steps to reproduce

`
Dec 25 00:06:55 lnd[538311]: 2022-12-25 00:06:55.363 [INF] PEER: Peer(02e8f0717f412f455bbcafabc7119f3e3bc1e6c7efeff3df14c98f4da14278dc95): unable to read message from peer: unable to parse message of unknown>
Dec 25 00:06:55 lnd[538311]: 2022-12-25 00:06:55.364 [INF] PEER: Peer(02e8f0717f412f455bbcafabc7119f3e3bc1e6c7efeff3df14c98f4da14278dc95): unable to read message from peer: EOF
Dec 25 00:06:55 lnd[538311]: 2022-12-25 00:06:55.364 [INF] PEER: Peer(02e8f0717f412f455bbcafabc7119f3e3bc1e6c7efeff3df14c98f4da14278dc95): disconnecting 02e8f0717f412f455bbcafabc7119f3e3bc1e6c7efeff3df14c98f>
Dec 25 00:06:55 lnd[538311]: 2022-12-25 00:06:55.364 [INF] NTFN: Cancelling epoch notification, epoch_id=6259
`

This happens frequently, perhaps several times in an hour.

### Expected behaviour

Not disconnecting, or providing more information about the parse error so that it might be investigated

### Actual behaviour

Peers frequently disconnect. I cannot exclude the possibility that some of them are LND peers but so far I have identified two of them as core lightning nodes

**Comment by ellemouton** [comment]
@ekimber, is this the full log line? `unable to parse message of unknown`?
The full line should be something like: `unable to parse message of unknown type <type number here>`
Which will help us understand if cln is sending a type they should not send or if it is something else.

**Comment by Roasbeef** [comment]
The disconnect seems to be from something else: 
```
[INF] PEER: Peer(02e8f0717f412f455bbcafabc7119f3e3bc1e6c7efeff3df14c98f4da14278dc95): unable to read message from peer: EOF 
```

We'll parse unknown messages and just ignore them and have for some time now. If you run w/ the trace debug level, then you'll be able to see the message itself. We should update this log to print useful info tho: https://github.com/lightningnetwork/lnd/blob/c03de26dcc391a6ce22da1f6f262e9b912e72ae6/lnwire/message.go#L138

**Comment by ekimber** [comment]
@ellemouton The message type is "of unknown type <unknown>"

@Roasbeef So I am guessing that ignoring the message is somehow causing the peer to disconnect because it happens right after the unknown message. What module do I need to run with trace level to see the message itself? It does not log the messages with PEER set to trace.

**Comment by ekimber** [comment]
I believe the reason I do not see the message in the logs is because `brontide.go` never reaches line 1128 of the `readNextMessage` function:
`p.logWireMessage(nextMsg, true)`
when the message type is unknown.

**Comment by guggero** [comment]
Could this be related to https://github.com/lightningnetwork/lnd/issues/7290? Is your peer a cln node?

**Comment by ekimber** [comment]
@yaslama I suspect that I am seeing the same issue. Thanks for the patch, however, I do stick to a policy of only running released binaries on mainnet

**Comment by btweenthebars** [comment]
I (CLN 22.11) have a LND peer (v0.15.5-beta) who executed the SCB. My node received the invalid revocation number but somehow it did not automatically fire the force close, I guess because the connection was terminated by "unknow message" error.

in my log
```
2023-01-04 23:06:16.381Z INFO    03xxx-chan#22678: Peer transient failure in CHANNELD_NORMAL: Disconnected
2023-01-04 23:06:16.683Z INFO    03xxx-chan#22678: Peer transient failure in CHANNELD_NORMAL: channeld WARNING: bad reestablish revocation_number: 477 vs 483
```

in his log
```
2023-01-04 22:49:16.877 [INF] PEER: Peer(02xxx): loading ChannelPoint(67xx:0)
2023-01-04 22:49:16.877 [WRN] PEER: Peer(02xxx): ChannelPoint(67xx:0) has status ChanStatusLocalDataLoss, won't start.
2023-01-04 22:49:16.877 [INF] PEER: Peer(02xxx): Sending 1 channel sync messages to peer after loading active channels
2023-01-04 22:49:16.877 [INF] PEER: Peer(02xxx): Negotiated chan series queries
2023-01-04 22:49:16.877 [INF] NTFN: New block epoch subscription
2023-01-04 22:49:16.877 [INF] DISC: Creating new GossipSyncer for peer=02xxx
2023-01-04 22:49:21.192 [ERR] PEER: Peer(02xxx): resend failed: unable to fetch channel sync messages for peer 02xxx@127.0.0.1:50724: unable to find closed channel summary
2023-01-04 22:49:21.745 [WRN] DISC: ignoring remote ChannelAnnouncement for own channel
2023-01-04 22:49:25.626 [ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: channel not found
2023-01-04 22:49:26.437 [INF] PEER: Peer(02xxx): unable to read message from peer: unable to parse message of unknown type: <unknown>
2023-01-04 22:49:26.438 [INF] PEER: Peer(02xxx): unable to read message from peer: EOF
2023-01-04 22:49:26.438 [INF] PEER: Peer(02xxx): disconnecting 02xxx@127.0.0.1:50724, reason: read handler closed
```

**Comment by Roasbeef** [comment]
Thanks for all the info y'all! I think we traced things down to a CLN change that modified behavior to send a warning then close the connection after they get the bad chan reest message. Because they close the connection, this means they might not actually read our incoming `Error` message, so then we reconnect and the entire thing starts over again.

**Comment by Crypt-iQ** [comment]
If you are experiencing this issue on `v0.15.5-beta`, the following steps should resolve the issue:

- Ensure that you have already tried connecting to the CLN node and received `Warning` followed by a disconnect.
- Checkout https://github.com/Crypt-iQ/lnd/tree/scb_cln_issue_7301_v0.15.5-beta
- Build `lnd` with the `dev` build tag.
- Boot up the newer version of `lnd` with the flag `--protocol.custom-message=17`.
- If you have logs, try to fetch the 32-byte (64 hexadecimal characters) `chan_id`/`ChannelID`/`channel_id` value. This may be appear with `ChannelLink` logs in the `HSWC` category. If you can't fetch it, feel free to post a comment asking for help.
- Once you have the 32-byte `chan_id`/`ChannelID`/`channel_id` value, fetch the peer's hexadecimal pubkey. This should appear in `listpeers` if you are connected to the peer or in some of your logs.
- Finally, use the `sendcustom` API like so:
```
lncli sendcustom --peer=<peer pubkey in hex> --type=17 --data=`chan_id`0000
```
- Note that the `data` field in the `sendcustom` call is the `chan_id` followed by 4 zeros.
- Once you see that your channel has been force closed via the `lnd` API, continue using the original `v0.15.5-beta`. This patch is only meant to be used temporarily.

If you are uncomfortable with using my personal branch and would instead prefer a temporary release, please let us know. Or if you don't know how to perform any of the steps above, leave a comment and I can help out.
