### ISSUE TITLE
[bug]: release verification difficulties

### ISSUE THREAD

**Issue by SerafV1** [lightningnetwork/lnd#7274]
Getting error when trying to signature check.

* Signature check for beta 15.5 
* Ubuntu 22.04

gpg --verify manifest-roasbeef-v0.15.5-beta.sig manifest-v0.15.5-beta.txt returns
WARNING: This key is not certified with a trusted signature!

ots verify manifest-roasbeef-v0.15.5-beta.sig.ots -f manifest-roasbeef-v0.15.5-beta.sig returns
Unknown option -f

**Comment by ffranr** [comment]
It looks like you just need to verify the key, see here:
https://security.stackexchange.com/questions/147447/gpg-why-is-my-trusted-key-not-certified-with-a-trusted-signature

The information you've provided so far does not suggest that the signature is invalid, only that you haven't trusted the associated key.

**Comment by SerafV1** [comment]
> 

Ok, What about second -f unknown option?

**Comment by ffranr** [comment]
> Ok, What about second -f unknown option?

Instructions for verifying a release can be found here: https://github.com/lightningnetwork/lnd/blob/master/docs/release.md

The instructions do not mention the use of `ots` during verification. The error you've quoted is specific to `ots`.

**Comment by ellemouton** [comment]
@ffranr , I think @SerafV1 is talking about the instructions in https://github.com/lightningnetwork/lnd/releases.

@SerafV1, I think it might just be a typo. I verify with `ots` as follows:

```
ots verify manifest-roasbeef-v0.15.5-beta.sig.ots
```

which will work as long as `manifest-roasbeef-v0.15.5-beta.sig` is in the same directory

**Comment by Roasbeef** [comment]
> Unknown option -f

That's set to specify the file: https://github.com/opentimestamps/opentimestamps-client/blob/master/otsclient/args.py#L201-L203

**Comment by SerafV1** [comment]
Followed raspibolt instructions and end up with this issues...
