### ISSUE TITLE
[bug]: lncli addinvoice documentation incorrect expiry value

### ISSUE THREAD

**Issue by zx9r** [lightningnetwork/lnd#7278]
### Background

`lncli addinvoice` should create an invoice with an expiry time of 3600 seconds (1 hour) if not specified, according to his own help message shown after a `lncli addinvoice -h`:

> --expiry value            the invoice's expiry time in seconds. If not specified an expiry of 3600 seconds (1 hour) is implied. (default: 0)

### Your environment

* version of `lnd` : v0.15.5-beta
* which operating system (`uname -a` on *Nix) : Ubuntu 22.04 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: N/A
* any other relevant environment details: N/A

### Steps to reproduce

Create an invoice with `lncli addinvoice` without specify a expiry time
Decode the created invoice with `lncli decodepayreq`

### Expected behaviour

invoice "expiry" should have a value of "3600", according to the help message information

Another valid option would be that the help message shows that the default expiry time is 86400 (24h)

### Actual behaviour

invoice "expiry" have a value of "86400" (24h)

**Comment by ellemouton** [comment]
here is the culprit: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L35

Wonder if we should change this to 1 hour or if we should just change the comment to reflect this 24 hour default

**Comment by Roasbeef** [comment]
Yeah we increased it, just need to update the help here.

**Comment by YusukeShimizu** [comment]
I would like to work on this.

**Comment by positiveblue** [comment]
Fixed in #7306
