### ISSUE TITLE
Document required versions of protoc-gen-go, grpc, protoc

### ISSUE THREAD

**Issue by bryanvu** [lightningnetwork/lnd#73]
In order to generate and compile the protobufs in lnrpc (using gen_protos.sh), versions of protoc-gen-go and grpc must be compatible. This should be rarely encountered, but will be necessary for developers looking to extend the lnd rpcs.

protoc-gen-go at commit df1d3ca07d2d07 is compatible with grpc version 1.0.0, as both use support package version 3.

protoc-gen-go at commit 8ee79997227b is compatible with grpc version 1.0.4, as both use support package version 4.

protoc version 3.0.0 works in both scenarios.

**Comment by bryanvu** [comment]
Note that some versions or combinations of the above versions of protoc-gen-go and grpc will result in a rpc.pb.go file with both camelCase and snake_case json names, and some versions will result in just snake_case. This should be resolved when we set the version numbers.

**Comment by Roasbeef** [comment]
Will be fixed by #169.
