### ISSUE TITLE
TEMPORARY_CHANNEL_FAILURE codes

### ISSUE THREAD

**Issue by martinoshub** [lightningnetwork/lnd#7304]
I saw Roasbeef mention regarding TEMPORARY_CHANNEL_FAILURE:

> "If you're seeing @1, then that means the very first hop beyond you doesn't have sufficient balance for the route"

I've been getting @2 and @3 and @4 and can't find what these refer to. Is it in the documentation? If so, can someone please point me to the right place? I've googled all over and still don't know why so many of my payments fail.

If it's not part of the documentation, I vote for adding it. Thanks for your kind consideration.

**Comment by yyforyongyu** [comment]
There are two docs can be referenced here. The first is BOLT#4, under [`failure messages`](https://github.com/lightning/bolts/blob/master/04-onion-routing.md#failure-messages). The second is this [API docs](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2#lnrpcfailurefailurecode).

**Comment by guggero** [comment]
The @ just refers to the number of the hop in your route. So in a payment from A (you) to E (destination) through A->B->C->D->E, B would be @1, C would be @2 and so on.
