### ISSUE TITLE
[Question] How to get the private key for a generated address?

### ISSUE THREAD

**Issue by nopara73** [lightningnetwork/lnd#732]
Assuming I'm using the `lnd` daemon. I don't seem to find a way to do this. Maybe I can get the master extended private key somehow? Or am I supposed to do it manually? Find the wallet file, decrypt it and go on with my life?

**Comment by Roasbeef** [comment]
There's no way to extract private keys from the daemon currently. All key handling and signing are abstracted behind a set of core interfaces. Assuming a `btcwallet` implementation for these interfaces, one would need to find the wallet file, decrypt it, etc. 

What use case do you have in mind?

**Comment by nopara73** [comment]
> There's no way to extract private keys from the daemon currently.

Is it a security consideration or it just wasn't implemented?

> What use case do you have in mind?

I am looking at the possibility of replacing HiddenWallet's back end, which is custom code right now with `lnd`, because of Neutrino and the possibility of seamless future LN integration. I must sign an arbitrary message, build transactions with shuffled input and output indexing, sign CoinJoin transactions partially, these comes to my mind, but there are many more. As I also figured there is no transaction hex propagation through the daemon, either, so I am starting to think there are too many walls to climb here.

**Comment by Roasbeef** [comment]
Well it's just that we haven't added such an interface _yet_, not that we'll never do so.

**Comment by halseth** [comment]
Well ww do have the `SignMessage` RPC, maybe it could be extended to specify which address to sign for?

**Comment by plantOS** [comment]
Any progress on this?

**Comment by patch-master** [comment]
Hi there, any progress on enabling the extraction of private keys?

**Comment by merclyn** [comment]
Could we export the extended public Key?

**Comment by jacohend** [comment]
@Roasbeef I second @merclyn, I need to get my wallet's public key so I can use the SignOutputRaw grpc, which requires either a "key_locator" or a wallet public key as an argument

**Comment by yohaaan** [comment]
any update on this? I'd use private key extraction as well

**Comment by AzerChainToken** [comment]
Hello people! Haved a any tools for export private key from Zap Wallet?

**Comment by guggero** [comment]
There is a PR that adds a command line utility to extract the `xprv` HD extended root key and individual private keys: https://github.com/lightningnetwork/lnd/pull/2373

@jacohend you can find out the derivation path for the node public key here: https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go
It is `m/1017'/0'/6'/0/0`

**Comment by KriptoQraf** [comment]
I'm new and I didn’t understand anything
