### ISSUE TITLE
[feature]: add get transaction rpc 

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#7323]
**Is your feature request related to a problem? Please describe.**

There should be a get transaction rpc instead of having to use the get transactions rpc and find the specific transaction you want. 

My node has done over 1k transactions and it would be nice to not have to load it all into memory and find something myself when lnd could easily do it.

**Comment by positiveblue** [comment]
Are we talking about the `lncli listchaintxns` here? What do you usually search by: `tx_hash`, `previous_outpoints`?

**Comment by benthecarman** [comment]
Yeah exactly

**Comment by ErikEk** [comment]
Looks like there is a pending PR for btcwallet (https://github.com/btcsuite/btcwallet/pull/779).

**Comment by gnapoli23** [comment]
Hi, a newcomer here! I would like to work on it, can you give me a bit of context? Thanks! :)

**Comment by ErikEk** [comment]
I almost completed it.

**Comment by gnapoli23** [comment]
> @gnapoli23 I almost completed it. But since you are new here you can get the code if you want to finish it.

Oh, nevermind. Keep on going. I'll take a look for something else :)

**Comment by ErikEk** [comment]
Great thx

**Comment by gnapoli23** [comment]
I didn't see any PR linked to the issue in a week, so I started to work on it.

**Comment by ErikEk** [comment]
@gnapoli23 I didn't abandon it. Was waiting for the 0.16 release. If you want to do it instead, go ahead.

**Comment by positiveblue** [comment]
@ErikEk Do you mind chiming in #7378? You said you were almost done so feel free to create a draft PR. 

Given that you had already implemented a working (or almost) version of it, do you mind sharing what approach you followed?

**Comment by ErikEk** [comment]
@positiveblue Absolutely.

**Comment by benthecarman** [comment]
Any updates on this? This is desperately needed, my node has reached the point where it is greater than the grpc max message size when calling get transactions.

**Comment by ErikEk** [comment]
I will see what I can. Looks like the guy abandoned it.

**Comment by abitcoinperson** [comment]
Gonna bump this again.

**Comment by saubyk** [comment]
> Gonna bump this again.

Looks like the pr has made some progress and got some reviews. Tagging this issue for 0.17.1

**Comment by markettes** [comment]
Is progress being made here or may I jump into this?

**Comment by ErikEk** [comment]
@markettes Almost done. Had to change btcwallet so it took some extra time.
https://github.com/lightningnetwork/lnd/pull/7654

**Comment by markettes** [comment]
Sure, no worries. I was looking for something to work on 😃
