### ISSUE TITLE
No longer able to compile lnd

### ISSUE THREAD

**Issue by lnuser** [lightningnetwork/lnd#735]
After doing a git pull today it is no longer possible to compile lnd

`glide install` returns the following
[glide.txt](https://github.com/lightningnetwork/lnd/files/1695495/glide.txt)

and `go install . ./cmd/...` returns 
[go.txt](https://github.com/lightningnetwork/lnd/files/1695500/go.txt)

This is on Centos7. Last week it was possible to compile and run lnd

**Comment by aakselrod** [comment]
Looks like your glide cache might be nerfed. Try `rm -rf vendor && glide cc && glide install`.

**Comment by lnuser** [comment]
Thank you @aakselrod That did the trick
