### ISSUE TITLE
[bug]: trying to use /v2/invoices/subscribe/{r_has} doesn't always work due to "/" sometimes being present

### ISSUE THREAD

**Issue by jmoasth** [lightningnetwork/lnd#7358]
### Background

I'm trying to subscribe to an invoice using the rest api (/v2/invoices/subscribe/{r_hash}), but I'm getting 404 about half the time. I've tried using encodeURIComponent on the r_hash but this never works (always 404). When the r_hash doesn't contain any "/" characters, I'm able to listen to updates just fine. 

### Your environment

* version of `lnd`: 0.15.5-beta
* which operating system (`uname -a` on *Nix): Linux Ubuntu
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core client v24.0.0
* any other relevant environment details

**Comment by jmoasth** [comment]
My current workaround is regenerating invoices until I get one that doesn't have a forward slash (/).

**Comment by guggero** [comment]
You need to use base64 URL encoding for parts that are in the URI. See https://lightning.engineering/api-docs/api/lnd/#rest-encoding or https://github.com/lightningnetwork/lnd/issues/6029.
