### ISSUE TITLE
[bug]: run unit tests (btcd unit-cover) failure due to build tag mismatch 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#7362]
### Background

A test run for one of my PRs failed with:
```
Error: cannot read source of file "/home/runner/work/lnd/lnd/kvdb/postgres/db_conn_set.go": open /home/runner/work/lnd/lnd/kvdb/postgres/db_conn_set.go: no such file or directory
Error: Error: The process '/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64' failed with exit code 1
```

It looks like the postgres file it thinks should be there isn't (due to lack of a set build tag?), so even though the tests pass, it fails on sending out the coverage report.

**Comment by guggero** [comment]
Will be fixed by bumping the `kvdb` tag in the main go module (done by https://github.com/lightningnetwork/lnd/pull/7252). See https://github.com/lightningnetwork/lnd/pull/7251#issuecomment-1373285627.
