### ISSUE TITLE
[bug]:  negative num_confirmations at onChain transaction

### ISSUE THREAD

**Issue by SebiCreator** [lightningnetwork/lnd#7369]
### Background

Started lnd + RTL, send sats to lnd onChain.
bitcoin-cli shows that the transaction has 100+ confirmations, lnd shows as negative confirmed lol.
See screenshots below.

### Your environment

* version of lnd: lnd version 0.15.5-beta commit=v0.15.5-beta
* which operating system: Linux coreserver 5.15.84-v7l+  1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
* version of bitcoind: Bitcoin Core version v22.0.0
* bitcoin.conf
<img width="577" alt="Bildschirm­foto 2023-01-30 um 10 03 33" src="https://user-images.githubusercontent.com/63467522/215435362-04265902-9c20-449a-bbed-34269a8f989a.png">
* lnd.conf
<img width="541" alt="Bildschirm­foto 2023-01-30 um 10 04 47" src="https://user-images.githubusercontent.com/63467522/215435419-aae9dfe2-443e-4203-b6b7-814a04381581.png">
<img width="654" alt="Bildschirm­foto 2023-01-30 um 10 06 21" src="https://user-images.githubusercontent.com/63467522/215435468-78423712-a0eb-496e-875f-b2af27f4f3dd.png">
<img width="658" alt="Bildschirm­foto 2023-01-30 um 10 07 30" src="https://user-images.githubusercontent.com/63467522/215435538-cab3472b-1533-4513-8be6-b0b6fcb3581b.png">

similar issue:
https://github.com/lightningnetwork/lnd/issues/7255

### Steps to reproduce

1. Install via git clone & make 
2. Send stats onChain via RTL

### Expected behaviour

confirmed transaction shows as unconfirmed

### Actual behaviour

transaction should be confirmed

**Comment by SebiCreator** [comment]
Thank you for your answer.

Now my question is why is my node not synced and how do i fix this?

**Comment by positiveblue** [comment]
Is it still not synced? If it was disconnected for a while your node needs to catch up with everything that happens while it was "sleeping".

If it is not synced I would recommend you to check the logs.

**Comment by SebiCreator** [comment]
Now its synced. I dont expected that the catch up takes so much time.

Thank you very much for your help.
