### ISSUE TITLE
Problems parsing Macaroons after PR #692

### ISSUE THREAD

**Issue by herrvendil** [lightningnetwork/lnd#738]
Hi

I’m working on a Java API for the LND node to release it open—source and have detected a problem parsing macaroons after PR #692 . I use jmacaroons (https://github.com/nitram509/jmacaroons) as library and it was working until a week ago.

I guess it has to do with the upgrade to V2 macaroons which doesn’t seem to be supported by jmacaroons.

My question is if there is any use-case for a client to ever construct their own macaroons, and is parsing really needed by clients. Or is it sufficient to just use the binary data of the LND generated macaroon and attach it to the GRPC header in hex format.

Regards
Philip Vendil

**Comment by halseth** [comment]
As long as you are not gonna add additional restrictions to you macaroon ("baking" a new macaroon), then it should be enough to just attach the data without parsing it.

**Comment by herrvendil** [comment]
Thanks for the answer. I will change my code to just use the binary macaroon file in my request until the jmacaroon library supports V2 macaroons.

Closing the issue.
