### ISSUE TITLE
node seems ok but logs show many: rpc error: code = NotFound desc = unable to find node

### ISSUE THREAD

**Issue by The34Goon** [lightningnetwork/lnd#7398]
### Background

Describe your issue here.
Logs show a bunch of
[ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node
yet all my channels are active.
### Your environment

* version of `lnd` v0.15.5-beta
* which operating system (`uname -a` on *Nix) 5.15.0-58-generic
* version of `btcd`, `bitcoind`, or other backend 24.0.1
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen
LND shouldn't be complaining
### Actual behaviour

Tell us what happens instead
mimimi all day

**Comment by positiveblue** [comment]
It looks like your node has no information about the pubkey you are searching for (in your graph). What pubkey are you looking up?

**Comment by The34Goon** [comment]
That's the thing, I'm not looking for a pubkey and all my channels are fine.  At first I thought it was a watchtower, but they also seem to be ok.

**Comment by guggero** [comment]
Do you run any UI software? Like RTL or Thunderhub? It's probably some kind of management software that queries for nodes that don't exist.

**Comment by The34Goon** [comment]
Zeus and RTL. 
Thx for clearing that up.
