### ISSUE TITLE
Document or change installation location for grpc-ecosystem

### ISSUE THREAD

**Issue by bryanvu** [lightningnetwork/lnd#74]
In order to generate new protobuf files using lnrpc/gen_protos.sh, the grpc-ecosystem repo must be cloned into $GOPATH/src/github.com.

Alternatively, the include path in gen_protos.sh could be changed to point to $GOPATH/src/github.com/lightningnetwork/lnd/vendor/github.com.

**Comment by Roasbeef** [comment]
Fixed by b4fff97d14ee8807cbc4fb09d08704b5663d0926.

Closing.
