### ISSUE TITLE
README.md claims segwit support has not been merged into master

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lnd#740]
But it has, see https://github.com/btcsuite/btcd/pull/656

**Comment by snavsenv** [comment]
sounds like you should make a pull request

**Comment by ysangkok** [comment]
But there is still a reason to use roasbeef's btcd, I don't know what it is, exactly. So I can't write a PR.

**Comment by halseth** [comment]
You are right that the README is wrong on that point. Reason the roasbeef fork is still needed is because it has `neutrino` related additions, that's not merged to master.

**Comment by Roasbeef** [comment]
Fixed by #754.
