### ISSUE TITLE
[bug]: lnd stops responding and becomes unkillable on openbsd 7.2

### ISSUE THREAD

**Issue by lnproxy** [lightningnetwork/lnd#7409]
### Background

I've been running lnd on openbsd for months with great results.  Recently I upgraded to openbsd 7.2 from 7.1 and have not been able to get lnd working since.

lnd will run normally for some time but eventually stops adding new lines to `.lnd/logs/bitcoin/mainnet/lnd.log`, responds to all `lncli` requests with `[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"` and does not die even with `kill -9`.

This never happened on openbsd 7.1 so it's probably not related to: https://github.com/golang/go/issues/34988

### Your environment

* version of `lnd`: lnd version 0.15.5-beta
* which operating system (`uname -a` on *Nix): OpenBSD 7.2 GENERIC.MP#1049 amd64
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v24.0.1

### Steps to reproduce

Just start lnd, unlock the wallet, and wait.

### Expected behaviour

I'd expect lnd to continue running normally, or at least shutdown gracefully.

### Actual behaviour

As described above, completely freezes and stops responding even to OS signals.  PC requires a hard reboot to get back to a functional state.  Even calling `ps -p` on the broken lnd's pid causes the whole system to freeze.

Even with logging at the most detailed level, there's nothing out of place in the logs.

**Comment by jrick** [comment]
you're hitting this: https://marc.info/?t=166694295600001&r=1&w=2

**Comment by guggero** [comment]
@jrick thanks a lot for the link! I quickly scanned the conversation and I didn't see any hint of a possible workaround. So this needs to be patched in OpenBSD itself or could something be done on the `bbolt` side?

**Comment by jrick** [comment]
i don't know if any userland workaround, but if you run the bbolt unit tests, it is always the same test that causes the hang.  so whatever it is doing, try avoiding that? but the real fix has to be done in the kernel.

the syscall change is unrelated, it won't fix this bug.

**Comment by guggero** [comment]
> the syscall change is unrelated, it won't fix this bug.

Ah okay, I misinterpreted the comments in the PR.

**Comment by lnproxy** [comment]
Thank you @jrick and @guggero.  I'll close the issue since it seems not to be an lnd bug.

**Comment by lnproxy** [comment]
In case anyone runs into this, lnd works great in the latest openbsd snapshot.  `sysupgrade -s`.
