### ISSUE TITLE
[bug]: payment to self won't route through a single hop

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#7417]
### Background

payment to self won't route through private channel

### Your environment

* `lnd-v0.15.4`
* `Linux 5.3.0-40-generic`
* `bitcoind`

### Steps to reproduce

1. Create a private channel with your other test node
2. On the other node, send a keysend back to the node that opened the channel so that there is capacity balanced on both ends
3. Create an invoice for something small like 1000 sat.
4. `lncli sendpayment --allow_self_payment  --outgoing_chan_id xxxxxxxxxxxxxxxx --last_hop pubkeyoftheothernode --pay_req YYYYYYYYYYYYYYYYYYY`

### Expected behaviour

Payment should route.

### Actual behaviour

`Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE`

Note: If I remove `--last_hop` then it will work, but will go through an additional node.

**Comment by guggero** [comment]
Does your peer have very high fees set on the private channel? It could be that your max fee settings when sending the payment aren't sufficient to use that channel. Does it work if you ramp up `--fee_limit`?

**Comment by AndySchroder** [comment]
I tried `--fee_limit_percent 100` and `--fee_limit 1000` but neither worked. The invoice was for `1001`, so I think those should both have been plenty high.

**Comment by AndySchroder** [comment]
Doing more testing, this may not be isolated to private channels. Here is a more general command that also does not work:

`lncli sendpayment -f --allow_self_payment --last_hop $(lncli listchannels --public_only --active_only|jq -jr .channels[1].remote_pubkey) --pay_req $(lncli addinvoice 11 --private -memo "small test to myself"|jq -jr .payment_request)`

however, this command works:

`lncli sendpayment -f --allow_self_payment --outgoing_chan_id $(lncli listchannels --public_only --active_only|jq -jr .channels[1].chan_id) --pay_req $(lncli addinvoice 11 --private -memo "small test to myself"|jq -jr .payment_request)`

Could I be using the `--last_hop` option wrong, or is there a minimum number of hops?

**Comment by AndySchroder** [comment]
The command

`lncli sendpayment -f --allow_self_payment --pay_req $(lncli addinvoice 11 --private -memo "small test to myself"|jq -jr .payment_request)`

routes only through `03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f` (ACINQ) but then when I try to use

`lncli sendpayment -f --allow_self_payment channelIdIHaveWithACINQ --pay_req $(lncli addinvoice 11 --private -memo "small test to myself"|jq -jr .payment_request)` it adds a second hop through `023d70f2f76d283c6c4e58109ee3a2816eb9d8feb40b23d62469060a2b2867b77f` (gameb_1).

Does this provide any more useful information?

**Comment by guggero** [comment]
Just to narrow it down further, does it work if you use the `--private` flag when creating the invoice?

**Comment by AndySchroder** [comment]
Note, I fixed an error in my previous comment and also expanded on some more information in the edits.

**Comment by AndySchroder** [comment]
The `--private` flag is used in the above examples. I've tried with and without it and I can't seem to notice a difference.

**Comment by AndySchroder** [comment]
I did some more testing on another node. The other node had more channels that worked, but many still didn't. A few channels that did work:

- https://1ml.com/node/02e01367e1d7818a7e9a0e8a52badd5c32615e07568dbe0497b6a47f9bef89d6af which shows it is using c-lightning
- https://1ml.com/node/0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f which also shows to be using c-lightning
- https://1ml.com/node/02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69 which doesn't indicate the node implementation used

I'm not going to share much more about my nodes connectivity, but I'll say that looking up the channels on 1ml for the ones that didn't work, those that did indicate a node implementation showed lnd.

So, I'm wondering if LND is struggling to route payments this way.

**Comment by AndySchroder** [comment]
Here's another example that doesn't work. This creates the route I want, but it fails to send the payment.

`lncli queryroutes --outgoing_chanid  $(lncli listchannels --private_only --active_only|jq -jr .channels[0].chan_id) --dest $(lncli getinfo|jq -jr .identity_pubkey) --amt 10|lncli sendtoroute --payment_hash=$(lncli addinvoice 10 -memo "small test to myself"|jq -jr .r_hash) -`

**Comment by guggero** [comment]
Ah, thanks for all the additional info. It just occurred to me that this probably is the safety feature that was added to make channel jamming a tiny bit harder:
```
--allow-circular-route                                                 If true, our node will allow htlc forwards that arrive and depart on the same
                                                                             channel.
```

If you set that to true on your second node you want to route through, does it work?

**Comment by AndySchroder** [comment]
That worked! However, https://github.com/lightningnetwork/lnd/blob/d44823f6e8580d2fa5f193a5382be351610f7c2b/sample-lnd.conf#L431 leads me to believe this is the default. Seems like `sample-lnd.conf` should show the defaults in its examples, but it usually doesn't.

Here are some one liner test commands:

- `channelNum=0;lncli sendpayment -f --allow_self_payment --outgoing_chan_id $(lncli listchannels --private_only --active_only|jq -jr .channels[$channelNum].chan_id) --last_hop $(lncli listchannels --private_only --active_only|jq -jr .channels[$channelNum].remote_pubkey) --pay_req $(lncli addinvoice 11 -memo "small test to myself"|jq -jr .payment_request)`
- `InvoiceJSON=$(lncli addinvoice 10 -memo "small test to myself");lncli buildroute --amt 10 --hops $(lncli listchannels --private_only --active_only|jq -jr .channels[0].remote_pubkey),$(lncli getinfo|jq -jr .identity_pubkey) --payment_addr $(echo $InvoiceJSON |jq -jr .payment_addr)|lncli sendtoroute --payment_hash=$(echo $InvoiceJSON |jq -jr .r_hash) -`
- `InvoiceJSON=$(lncli addinvoice 10 -memo "small test to myself");lncli sendpayment --allow_self_payment --payment_hash=$(echo $InvoiceJSON |jq -jr .r_hash) --dest=$(lncli getinfo|jq -jr .identity_pubkey) --outgoing_chan_id  $(lncli listchannels --private_only --active_only|jq -jr .channels[0].chan_id) --amt=11 --pay_addr=$(echo $InvoiceJSON |jq -jr .payment_addr)`

Note: The previous `sendtoroute` examples I had above in my earlier comments won't work because the `payment_addr` is not defined.

I guess the moral of the story here is that this is peer specific and https://github.com/lightningnetwork/lnd/issues/7419 is even more critical to reliably avoid fees on self payments.

**Comment by guggero** [comment]
> leads me to believe this is the default.

Since it's a boolean flag, its default is `false` (since with the library we use you cannot set a boolean flag to false on the command line).

>  should show the defaults in its examples,

Since the defaults are usually empty or false, we decided to instead show some actual values and their formats in the example conf. You can get the actual default values from `lnd --help`.

> this is peer specific 

Yes, it looks that way. I think we can discuss turning this flag off by default, but since it's a security feature I don't think that will get a lot of votes.

I do think it makes sense to look into #7419 to support self-settlement. So given that this particular "mystery" has been solved, do you agree that we can close the issue?

**Comment by AndySchroder** [comment]
Yes, we can close it. https://github.com/lightningnetwork/lnd/issues/7419 is definitely the real solution, but for right now setting `allow-circular-route=true`, opening a private channel with a second node, and setting fees on that private channel to 0 is a temporary workaround.
