### ISSUE TITLE
[bug]: unknown field "fee_rate" when opening channel using REST API

### ISSUE THREAD

**Issue by rolznz** [lightningnetwork/lnd#7421]
### Background

fee_rate and base_fee cannot be passed to open-channel-sync despite being listed as valid parameters in the documentation: https://lightning.engineering/api-docs/api/lnd/lightning/open-channel-sync

### Your environment

Bitcoin core v24.0, LND 0.15.5-beta running in Polar (Windows)

### Steps to reproduce

Create two nodes and try to create a channel between them using the following:

`
curl --location --request POST 'https://127.0.0.1:8081/v1/channels' \
--header 'Grpc-Metadata-macaroon: your_macaroon_here' \
--header 'Content-Type: application/json' \
--data-raw '{
    "node_pubkey": "pubkey_here",
    "local_funding_amount": "100000",
    "fee_rate": "1000"
}'`

### Expected behaviour

Channel should be created with fee_rate set

### Actual behaviour

API call returns an error message
```
{
    "code": 3,
    "message": "proto: (line 4:5): unknown field \"fee_rate\"",
    "details": []
}
```

Removing the fee_rate parameter results in the channel being created.

**Comment by positiveblue** [comment]
The field was added in #6753 and it targets LND v0.16.0-beta so it is expected to not he working in v0.15.5-beta
