### ISSUE TITLE
[bug]: funding_txid_str not returned when opening channel using REST API

### ISSUE THREAD

**Issue by rolznz** [lightningnetwork/lnd#7422]
### Background

the response of creating a channel does not return `funding_txid_str` as one of the fields despite being listed as valid parameters in the documentation: https://lightning.engineering/api-docs/api/lnd/lightning/open-channel-sync

### Your environment

Bitcoin core v24.0, LND 0.15.5-beta running in Polar (Windows)

### Steps to reproduce

Create two nodes and create a channel between them using the following:

`
curl --location --request POST 'https://127.0.0.1:8081/v1/channels' \
--header 'Grpc-Metadata-macaroon: your_macaroon_here' \
--header 'Content-Type: application/json' \
--data-raw '{
    "node_pubkey": "pubkey_here",
    "local_funding_amount": "100000"
}'`

### Expected behaviour

Response should include `funding_txid_str` alongside `funding_txid_bytes` and `output_index`

### Actual behaviour

API call returns the following:
```
{
    "funding_txid_bytes": "iNGB21WBmdcPr/JC4kuvbu61swks+VV5NVvYc/i7gZk=",
    "output_index": 0
}
```

**Comment by positiveblue** [comment]
Same as in #7421, this feature targets v0.16.0-beta

I will update this comment with how you can check the docs for a targeted version

**Comment by rolznz** [comment]
@positiveblue thanks. By "can only contain one of the values" does this mean that we need to check for the existence of both?

**Comment by positiveblue** [comment]
@rolznz yes, one of those values will always be `undefined`/`null`, but it is up to the method implementation to decide which one. Changing it now would be breaking the API (because people may not be checking which one is set but assuming that it will always be the one that was there when they tried it)

**Comment by rolznz** [comment]
@positiveblue is there an implementation that returns funding_txid_str, so we can test it?

**Comment by positiveblue** [comment]
@rolznz I do not know any endpoint that sets the str version instead of the byte one
