### ISSUE TITLE
LookupHtlc returns error 'unknown htlc' for htlcs that are not finalized

### ISSUE THREAD

**Issue by JssDWt** [lightningnetwork/lnd#7428]
### Background

The new LookupHtlc rpc returns an error _unknown htlc_ if you lookup a htlc that is not yet finalized. 

### Your environment

* version of `lnd`: based on master https://github.com/lightningnetwork/lnd/commit/0f079729c16952a636eedc12ae0f6c99c0af042c

### Steps to reproduce

- Start LND with `StoreFinalHtlcResolutions = true`
- Create an invoice
- Subscribe to the invoice stream
- Pay invoice with other client
- Wait for an event with invoice state SETTLED
- Follow procedure described in this PR https://github.com/lightningnetwork/lnd/pull/6517#issue-1229844699

### Expected behaviour

I'd expect the LookupHtlc rpc to return `settled: false`. Or an additional field `finalized: false`.

### Actual behaviour

LookupHtlc returns an error _unknown htlc_ if called before the htlc is settled.

**Comment by ellemouton** [comment]
cc @joostjager

**Comment by alexbosworth** [comment]
I see this "not found" issue in `daily-testing-20230207` but not in `daily-testing-20230206`

**Comment by yyforyongyu** [comment]
> I'd expect the LookupHtlc rpc to return settled: false. Or an additional field finalized: false.

I think the additional field would be nice. The field `settled` means it's already in a terminal condition and the htlc is either settled or failed.

> Wait for an event with invoice state SETTLED

I think the htlc should be there if the invoice has been marked as settled.

> The new LookupHtlc rpc returns an error unknown htlc if you lookup a htlc that is not yet finalized.

The original idea is to provide "a single source of truth" once an invoice is settled, I guess that's the reason why the info won't be available before it's settled. That being said, this endpoint name is somewhat confusing - it should be named `LookupFinalHtlc`. With `LookupHtlc`, I'd expect more information there.

**Comment by joostjager** [comment]
I didn't add another db write for non-final htlcs because for the use cases that I had in mind, it is not necessary.

**Comment by joostjager** [comment]
@alexbosworth what scenario did you try exactly?

**Comment by yyforyongyu** [comment]
> I also tried polling longer, on daily-testing-20230206 it can return the error a couple times with polling but then reveal the state, on 07 it remains unknown with many polling retries

Did it eventually give you the result?

**Comment by joostjager** [comment]
As a side note: if you want minimal latency, polling is probably not the best way to do it. The final resolution event is also broadcast on the htlc event stream. Here is some example code of how to use the lookup and htlc event stream in combination: https://github.com/lightningnetwork/lnd/compare/master...bottlepay:lnd:lookup-htlc-test

**Comment by joostjager** [comment]
@alexbosworth when using the newer version, did you run lnd with `--store-final-htlc-resolutions`? (https://github.com/lightningnetwork/lnd/pull/7341)

**Comment by alexbosworth** [comment]
> @alexbosworth when using the newer version, did you run lnd with `--store-final-htlc-resolutions`? (#7341)
> 
> I didn't manage to translate daily-testing-20230207 to a commit hash, but on v0.16.0-beta.rc1 I can't reproduce your problem.

Ah great this solves the issue for me, I thought that had to do with persisting across restarts
