### ISSUE TITLE
[bug]: broadcasted old channel state db, some force closures stuck

### ISSUE THREAD

**Issue by ardevd** [lightningnetwork/lnd#7433]
For some reason, during an lnd upgrade back on Feb 2nd, my node decided to broadcast old channel states, resulting in most/all of my channels force closing. However, some channels are stuck in a weird state where they are listed as force closing on my end, but no on the other peer's end. 

On my end, I see the channel as force closing (been that way for three weeks now). But the peer typically sees the following in their lnd log:

`2023-02-21T04:35:34.488Z INFO    027ecdd3c509f7db2d8ade67381bb2e8ed88ccbfab8805d24076c4a0fd131f71ff-chan#1218: Peer transient failure in CHANNELD_NORMAL: channeld WARNING: bad reestablish revocation_number: 282514 vs 282881`

How can this get cleaned up and funds recovered? The only thing that seems to work is getting the other peer to force close on their end as well, but I don't have contact information for all the affected nodes. RTL lists the channels as "Awaiting Close"

**Comment by guggero** [comment]
Did you copy your node's data directory or the channel.db file or do some other kind of file based backup/restore? Sounds like you started lnd with an old state, which can be very dangerous. Luckily lnd didn't force close on its own, otherwise there is a real risk of loss of funds. DO NOT FORCE CLOSE yourself!

I would suggest to export the channel backup for each of the affected channels (using the `--chan_point` flag, creating one file per channel), then use the `abandonchannel` command to delete them from the DB and afterwards restore the individual channel backups.

**Comment by ardevd** [comment]
Thanks. I didn't copy or move anything but this all happened during an update of Umbrel's Lightning app which also updated lnd. Apparently, something weird happened at that point which I was never able to figure out except from realizing that somehow, and older channel state was broadcast at some point.

I'll give your suggestion a go. Thank you.

**Comment by guggero** [comment]
Please take a look at the output of `lncli abandonchannel --help`.

**Comment by ardevd** [comment]
`--i_know_what_i_am_doing` flag noted, thanks.

That only leaves the issue of not being able to store backup of a single channel to file. Can I simply copy the value from `chan_backup` in the json output and pass that to `restorechanbackup --single_backup`? I tried to verify with `verifychanbackup` but it just returned an empty json response.

**Comment by ardevd** [comment]
So here is what I did.

1. created a single channel backup.
2. abandoned channel
3. restored with `lncli restorechanbackup --single_backup <chan_backup_value>

logs indicate the channel is restored but I can't find it anywhere, but it now shows up under closed channels so I guess that's all good. I'm entirely sure how to figure out if my funds are recovered though.

**Comment by ardevd** [comment]
This is related to https://github.com/lightningnetwork/lnd/issues/7301. Closing this one and urge anyone affected to read up on issue #7301
