### ISSUE TITLE
[feature]: show channel funding TX expiry in `listchannels`

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#7434]
Related to https://github.com/lightningnetwork/lnd/issues/7426#issuecomment-1437605556.

Given that the [spec](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#the-funding_created-message) suggests that the responder of a channel should cancel the channel funding after 2016 blocks of its funding transaction not being confirmed, `lnd` should show some indicator that the channel is about to expire and be canceled.

My suggestion is to add the following to the `Channel` RPC message:
```
    // The number of blocks until the funding transaction is considered expired.
    // If this value gets close to zero, there is a risk that the channel
    // funding will be canceled by the channel responder. The channel should be
    // fee bumped using CPFP (see walletrpc.BumpFee) to ensure that the channel
    // confirms in time. Otherwise a force-close will be necessary if the
    // channel confirms after the funding transaction expires. A value of -1
    // indicates that the channel has at least one confirmation and this field
    // can be safely ignored.
    int32 funding_expiry_blocks = 34;
```

**Comment by maxwellsayles** [comment]
New to lnd and the codebase. Looking at this as a good first issue.

**Comment by maxwellsayles** [comment]
Chipping away at this as time permits. Got a local cluster running on simnet with `lnd` and `btcd`. Looking at making the changes and how to appropriately test this next.

**Comment by maxwellsayles** [comment]
Found the lightning.proto and was able to add the field. Just to clarify, is the feature request to also populate the response and surface it in LND? Any special handling of the response ? Thanks! cc @guggero

**Comment by guggero** [comment]
Yes, the idea is to also populate the value for each channel. Most likely in `https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L3350`. There's a field called `FundingBroadcastHeight` on each pending channel which you can use to calculate the number.

**Comment by maxwellsayles** [comment]
Quick update. Added the field to `lightning.proto` and got `lnrpc/gen_protos.sh` to run. Setup a simnet with alice,bob,charlie and opened a channel between alice->bob. `lncli listchannels` now shows a field `"funding_expiry_blocks": 0`. 

Was also able to verify that `rpcserver.ListChannels` is hit on `lncli listchannels` with an `rpcsLog.Infof(...)`.  On the other hand, looks like `rpcserver.fetchPendingOpenChannels` is hit on `lncli pendingchannels` (I didn't see it hit with "listchannels" or on "openchannel").

I can also force the value of `FundingExpiryBlocks` inside `rpcserver.ListChannels` and it's displayed with `lncli listchannels`.

Just confirming, we want this information displayed with `lncli listchannels` and not with `lncli pendingchannels` right?  

I'll work on computing the value in `ListChannels` in that case. Happy to put up a CR early if that's easier to talk about.

Also, looked into some existing tests: `itest/list_on_test.go`, `itest/lnd_misc_test.go`, and `itest/lnd_rpc_middleware_interceptor_test.go`. I did not see anything directly use `ListChannels`. Any tips on how to write a test for this, or an existing test that can by mimicked or modified? Thanks!

**Comment by yyforyongyu** [comment]
> Any tips on how to write a test for this, or an existing test that can by mimicked or modified? Thanks!

So [this line](https://github.com/lightningnetwork/lnd/blob/master/itest/lnd_misc_test.go#L273) returns a `lnrpc.Channel` which can be used for testing. `QueryChannelByChanPoint` wraps a `ListChannels` call and checks the returned value. You can then test the field by checking `aliceChannel.FundingExpiryBlocks`

**Comment by maxwellsayles** [comment]
> So [this line](https://github.com/lightningnetwork/lnd/blob/master/itest/lnd_misc_test.go#L273) returns a lnrpc.Channel which can be used for testing. QueryChannelByChanPoint wraps a ListChannels call and checks the returned value. You can then test the field by checking aliceChannel.FundingExpiryBlocks

^ this is a great tip! #thanks @yyforyongyu I'll use this for testing!

I saw `QueryChannelByChanPoint`, but didn't realize that it wrapped a `ListChannels` call! How does that work? I must understand this :)

**Comment by maxwellsayles** [comment]
I'm new to everything here: LND, Go Lang, github PRs.  I cloned the [lnd](https://github.com/lightningnetwork/lnd) repo and made a local branch with changes to add `funding_expiry_blocks` and compute its value in `lncli listchannels`. I still need to write a test for this, but have some manual testing. Just trying to figure out how to put up a PR for early feedback. Hopefully not too much effort and get my workflow ironed out.

**Comment by maxwellsayles** [comment]
PR #7479 exposes `funding_expiry_blocks` in `listchannels`, while #7480 exposes it through `pendingchannels`. Intuitively, this feels more closely associated to `pendingchannels`, but I'll defer to the reviewers on the direction this should take. Thanks!

**Comment by maxwellsayles** [comment]
PR #7480 is up for review at your leisure (y)  I went with the `PendingOpenChannel` message and this has an integration test now. Thanks for all the feedback so far!

**Comment by maxwellsayles** [comment]
@guggero @yyforyongyu would love to get a review or feedback on the associated PR. I can abandon the PR if it's not relevant, or wrap this up if you want it included. Thanks!

**Comment by saubyk** [comment]
> Related to [#7426 (comment)](https://github.com/lightningnetwork/lnd/issues/7426#issuecomment-1437605556).
> 
> Given that the [spec](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#the-funding_created-message) suggests that the responder of a channel should cancel the channel funding after 2016 blocks of its funding transaction not being confirmed, `lnd` should show some indicator that the channel is about to expire and be canceled.

Hi @guggero slightly different question, albeit related to the main objective of the issue, can you please provide some clarification on the "cancel" operation? What would the responder specifically do, after 2016 blocks have passed and the funding is still not confirmed? There is no way really to cancel the pending on-chain transaction. Is the responder just forgetting about the pending channel?
