### ISSUE TITLE
[bug]: exportchanbackup --output_file argument does nothing when chanpoint is provided

### ISSUE THREAD

**Issue by ardevd** [lightningnetwork/lnd#7436]
When exporting a channel backup, the manual states that an optional `--output_file <filename>` option can be provided to write a serialized version of the backup to disk. 

However, in `lncli version 0.15.5-beta commit=v0.15.5-beta` it doesnt seem to do anything when a chanpoint is also provided.

adding `--output_file test.backup` to my `lncli exportchanbackup <channel_point>` still prints out json output and doesnt write anything to disk for me.

**Comment by ardevd** [comment]
Studying the source, as far as I can tell, specifying `--output_file` should have the command return directly from `ioutil.WriteFile()` and not proceed to print out the json output.

**Comment by ardevd** [comment]
I stand corrected, when specifying chan_point, the function returns before output_file writing is handled. I'll make a PR with a fix as I presume this is not intended behavior?

**Comment by ardevd** [comment]
@guggero you can assign this issue to me if you want.

**Comment by ardevd** [comment]
This can probably be closed now

**Comment by guggero** [comment]
Fixed in #7437.
