### ISSUE TITLE
[bug]: LND fail on restart

### ISSUE THREAD

**Issue by scissorstail** [lightningnetwork/lnd#7449]
### Background

I saw some rare error.

### Your environment

* 0.15.5-beta
* Linux umbrel 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aaGNU/Linux
* bitcoind:v24.0.1

### Steps to reproduce

none

### Expected behaviour

Running well

### Actual behaviour

After restart lnd, below error occured and lnd stopped. Running well after another restart.
Maybe It is better to handle this error... 

```
2023-02-24 02:08:43.165 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
2023-02-24 02:08:43.670 [ERR] RPCS: [/routerrpc.Router/SubscribeHtlcEvents]: the RPC server is in the process of starting up, but not yet ready to accept calls
panic: unable to synchronize wallet to chain: -8: Block height out of range

goroutine 1754 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0x400978cb40)
        github.com/btcsuite/btcwallet@v0.16.5/wallet/chainntfns.go:117 +0xe08
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
        github.com/btcsuite/btcwallet@v0.16.5/wallet/wallet.go:213 +0x3c8
```

**Comment by ellemouton** [comment]
Thanks for reporting @scissorstail  - looks related to https://github.com/lightningnetwork/lnd/issues/4818 which noted that this could happen if LND is started while bitcoind is still syncing. Defs something that should be addressed.
Perhaps a simple retry-ever-x-seconds-until-success will do

**Comment by guggero** [comment]
This can also happen if you point lnd to the wrong chain backend. Are you by any chance using mainnet and testnet on the same machine and got something mixed up?

**Comment by scissorstail** [comment]
@guggero No, only mainnet.

**Comment by scissorstail** [comment]
@sputn1ck No, there are no issues now. The node sync has completed.

**Comment by vostrnad** [comment]
Happened to me as well on 0.16.0-beta. Started lnd when bitcoind was still syncing, then when it finished lnd crashed:
```
panic: unable to synchronize wallet to chain: -8: Block height out of range

goroutine 451 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc008ad26c0)
        github.com/btcsuite/btcwallet@v0.16.7/wallet/chainntfns.go:117 +0x1065
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
        github.com/btcsuite/btcwallet@v0.16.7/wallet/wallet.go:213 +0x25c
```
Someone please reopen the issue, or I can open a new one.
