### ISSUE TITLE
Unable to start server after last commit caused by unresolved address type.

### ISSUE THREAD

**Issue by rem0g** [lightningnetwork/lnd#745]
After pulling the last commit I'm getting this error: 

2018-02-08 14:06:19.742 [ERR] SRVR: unable to start server: address type cannot be resolved

I have looked to repo for the origin of error code. After some researching,I've led to believe this commit https://github.com/lightningnetwork/lnd/commit/4b1cc988081232bef770dea30b2edee9431ba581 could cause the issue. 

It seems it could not find the type (IPV4 or IPV6) of the address. There is no documentation about the address setting expect I've set externalip in lnd.conf.

**Comment by echto** [comment]
I just updated and get the same error. 

2018-02-08 11:00:43.216 [ERR] SRVR: unable to start server: address type cannot be resolved

**Comment by Roasbeef** [comment]
A breaking database changed occurred with the way we store addresses. You can use `git reflog` to checkout the commit you were on before you updated to master. Once you're on that commit, close out all your channels, then roll forward to the latest commit.
