### ISSUE TITLE
[bug]: Cannot advertise multiple addresses

### ISSUE THREAD

**Issue by kroese** [lightningnetwork/lnd#7450]
### Background

When specifying a single `externalip` in lnd.conf with an IPv4 address, it advertises two addresses correctly (IPv4 + Tor).

But when adding a second `externalip` with an IPv6 address, it will not advertise all three addresses, but only IPv6 + Tor, and not IPv4 + IPv6 + Tor.

I am sure this behaviour was different in the past (in version 0.14). Because I had LND advertise all three adresses in the past.

So I suspect something in 0.15 changed making this impossible.

### Your environment

* LND 0.15.5-beta
* Ubuntu 22.10
* bitcoind v24.01

### Steps to reproduce

Enter multiple `externalip` lines

### Expected behaviour

All of them should be advertised

### Actual behaviour

Only the last one gets advertised

**Comment by ellemouton** [comment]
Hi @kroese - does your `getinfo` call also only show the last address? If you are using something like 1ML to see the addresses then it might just be a matter of waiting for the message to propagate.
