### ISSUE TITLE
Witness_Type in 2 packages diverged

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7460]
We have the variable `witness_type` in 2 places but they divereged: [input/witnessgen.go](https://github.com/lightningnetwork/lnd/blob/dceb10144f7188a09f5fcdbe04ce4ef9adf6960a/input/witnessgen.go#L44) and in [walletrpc.proto](https://github.com/lightningnetwork/lnd/blob/f94500281f17296070a4809c781da4324a42e2f4/lnrpc/walletrpc/walletkit.proto#L778) 
I want to bring them back to unity and was also thinking of using the same order(same enum value) in both, which makes it easier to compare. Or are types only appended in the protofiles and never rearrange because of backwards compatibility (which shouldn't be a problem IMO)

I found out about it when sweeping a TX: 
`lncli wallet pendingsweeps` showed me:  UNKNOWN_WITNESS  

But the log was also clear about it: 
```2023-02-26 16:39:32.956 [WRN] WLKT: Unhandled witness type HtlcOfferedTimeoutSecondLevelInputConfirmed for input e7a90e891c56b5a3fea4977a161aa1be77f4cee4977c6112ea410d3ac01a2761:4```

Feel free to assign it to me, if we wanna fix this.

**Comment by guggero** [comment]
Makes sense to get them re-aligned. I think we should add a comment in `input/witnessgen.go` that these enum values are used in gRPC so we don't forget to update the RPC enum. Or maybe add a test that detects divergences?

**Comment by emilioziniades** [comment]
Hi there, I'd like to give this a go.

I'll do both: add a comment and write a test to detect divergence

**Comment by ziggie1984** [comment]
Sounds good, have fun :)
