### ISSUE TITLE
[bug]: cannot close channel with state: ChanStatusLocalDataLoss|ChanStatusRestored

### ISSUE THREAD

**Issue by tmaiorca** [lightningnetwork/lnd#7474]
### Background

My channel partner and I both had our nodes go offline for a few weeks. Upon restoring the wallet and channel.backup file, the channel is stuck in `waiting_close_channels` for a week now. 

{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "039910a225afe022698e41afdc69ef7b23832cb03baf632476b42d1b7ccc596fcf",
                "channel_point": "c2c5e72c007f87325e633233d4c0d27a29dd90a9dac6755333f4d0504383b42a:0",
                "capacity": "110000",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusLocalDataLoss|ChanStatusRestored",
                "private": true
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "",
                "remote_txid": "",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "0",
                "remote_commit_fee_sat": "0",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        },
        {
            "channel": {
                "remote_node_pub": "039910a225afe022698e41afdc69ef7b23832cb03baf632476b42d1b7ccc596fcf",
                "channel_point": "48c9fc5606311257c24e2310ee766b28ac1054da6d824c807707422034cd914e:1",
                "capacity": "110000",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusLocalDataLoss|ChanStatusRestored",
                "private": true
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "",
                "remote_txid": "",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "0",
                "remote_commit_fee_sat": "0",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}

Attempted a force closing of the channel from my side via `lncli closechannel c2c5e72c007f87325e633233d4c0d27a29dd90a9dac6755333f4d0504383b42a 0` results in the following error:

`[lncli] rpc error: code = Unknown desc = cannot close channel with state: ChanStatusLocalDataLoss|ChanStatusRestored`

### Your environment

* lnd v0.15.4-beta
* Linux raspberrypi 5.15.32-v8+
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

**Comment by alexbosworth** [comment]
did both sides lose the database?

**Comment by tmaiorca** [comment]
> 

To my knowledge, yes. At least from my side. Presumably so from there end as well.

**Comment by guggero** [comment]
@tmaiorca if both sides lost the channel state, then only manual recovery with [`chantools zombierecovery`](https://github.com/guggero/chantools/blob/master/doc/chantools_zombierecovery.md) is possible. There's a guide here: https://github.com/guggero/chantools/blob/master/doc/zombierecovery.md

**Comment by tmaiorca** [comment]
> @tmaiorca if both sides lost the channel state, then only manual recovery with [`chantools zombierecovery`](https://github.com/guggero/chantools/blob/master/doc/chantools_zombierecovery.md) is possible. There's a guide here: https://github.com/guggero/chantools/blob/master/doc/zombierecovery.md

Thanks guggero! My peer and I are going to attempt the `chantools zombierecovery`. Fortunately, we're in contact with one another.
