### ISSUE TITLE
unable to open channel with API: lightning.openChannelSync

### ISSUE THREAD

**Issue by ghanavati27** [lightningnetwork/lnd#748]
Today i  fetch new changes of source code and compiled it, i deleted my old 'Lnd' folder in appdata and everything is fresh.
I trying to open new channel but i see this error.
"/lnrpc.Lightning/OpenChannelSync: unknown permissions required for method"
rpc.proto and admin macaroon are fresh also.
My OS is windows server 2012R2           

Opening channel with lncli.exe is working very well.

**Comment by Roasbeef** [comment]
`OpenChannelSync` is meant really to only be used over the REST API. But it seems that we forgot to add it to the set of authorized methods for the new macaroons setup. For now, I'd recommend using the streaming variant.
