### ISSUE TITLE
Wrong Comment in GetInfo function

### ISSUE THREAD

**Issue by Chinwendu20** [lightningnetwork/lnd#7482]
https://github.com/lightningnetwork/lnd/blob/530a2059e5bc9f144aba186c53852f0ad42ed232/lnrpc/watchtowerrpc/handler.go#L147-L150
It seeems like the description for AddTower is used for GetInfo function

**Comment by ellemouton** [comment]
good catch @Chinwendu20! Are you up for opening a PR to fix this comment?

**Comment by Chinwendu20** [comment]
Okay thank you

**Comment by Satarupa22-SD** [comment]
hi, I have created a PR for this issue. Please review it.
