### ISSUE TITLE
[bug|Feature]: Check for Reasonable CFee when Channel is not opened by us

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7488]
### Background

There are nodes on the network which do not support Anchor Channels but they enforce really low fees on the Commitment transaction. In this mempool conditions its really dangerous because first you risk losing funds when the outgoing HTLC is not confirmed by time and secondly you will also risk losing 2 channels because the channel with the corresponding incoming HTLC will FC too. I recommend adding rigorous checks for the fees of the Commitment Transaction especially for non-anchor channels, or at least give the user a config setting to decide whether he wanna enforce stricter rules for non-initiated channel-fee updates.

The node doing this for now is `Bcash_Is_Trash` but without a reasonable fee-check this could attract some bad behaviour.

Some examples:

https://mempool.space/tx/0d95150553b81da7ad2e03f5c2d2668c34513d9990a28f46a2278ca258d66e8c

https://mempool.space/tx/de2364ce92b22163e3dddb0af66df50b5a43b6055150c9f0de60fa2bb3345893

**Comment by Roasbeef** [comment]
Do you want to be able to only accept anchor channels? That can be done with a channel acceptor. We want to make it be the default and only channel type, but not all other implementations support the final version of it. 

>  recommend adding rigorous checks for the fees of the Commitment Transaction especially for non-anchor channels, 

If we can and find fees that are very low, controlled by the initiator, what do you propose we do? Force close is the only thing one can do, but then if the fees are already too low, you'd enter a limbo state for the channel. I guess this is better than having HTLCs, and not being able to actually resolve them on chain.

**Comment by ziggie1984** [comment]
I agree, using the channel-acceptor is the best way to prevent this kind of behaviour. Checking the fees and not allowing any HTLC on the commitment transaction would lead to many more force-closes I guess and too strict behaviour. 
Thinking it through again it's definitely something which should be handled on upper layers not in lnd. Thanks for your thoughts

**Comment by scissorstail** [comment]
How to bump fee for these transactions? I have one now...
Maybe, Transaction Accelerator is helpful. but It costs 75 USD for a single transaction now

**Comment by hazrulnizam** [comment]
Apologies for necromancing a closed issue, but with the mempool going back down to near 1sat/vB last week, the Bcash_Is_Trash node is really wreaking havoc with force closes. My node had a non-anchor channel with this node which was opened by them, that had to force close with the following error log entries:

```
2023-10-03 12:50:42.916 [ERR] HSWC: ChannelLink(2f1fba221a8daf6217e86d00e74943bc127f61e60ff8616ccec140a502320871:8): failing link: ChannelPoint(2f1fba221a8daf6217e86d00e74943bc127f61e60ff8616ccec140a502320871:8): unable to accept new commitment: commitment fee per kw 250 sat/kw below fee floor 253 sat/kw with error: invalid commitment
2023-10-03 12:50:42.916 [ERR] HSWC: ChannelLink(2f1fba221a8daf6217e86d00e74943bc127f61e60ff8616ccec140a502320871:8): link failed, exiting htlcManager
2023-10-03 12:50:42.916 [INF] HSWC: ChannelLink(2f1fba221a8daf6217e86d00e74943bc127f61e60ff8616ccec140a502320871:8): exited
2023-10-03 12:50:42.916 [INF] HSWC: ChannelLink(2f1fba221a8daf6217e86d00e74943bc127f61e60ff8616ccec140a502320871:8): stopping
2023-10-03 12:50:42.917 [WRN] PEER: Peer(0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f): Force closing link(723985:1100:8)
```

and the transaction is now stuck without me being able to do anything about it except hope and wait the mempool clears. 

https://mempool.space/tx/db1ecbd132b815505db3a6cee4beebc7c9e00cf6a36e6d44797099c969e667c3

Tried to find contact details for the Bcash_Is_Trash node operator to ask them to CPFP the transaction but it is proving to be futile. Some other people are resorting to sending messages on amboss.space to beg and plead for a CPFP:

![image](https://github.com/lightningnetwork/lnd/assets/47681422/bd49ba9a-dc56-4ed6-8aa1-29ed4d73b0bb)

Here are some other examples of this tragedy taking place:
https://mempool.space/tx/be065bb22552ca53f26841733ea844da70fba72dd08506245cbb234e34e59c84#vin=0
https://mempool.space/tx/cadc7bbdf7499f86bd12f867107c9ee8efcff4d3dcfd7cd1d3ce36e3b1258685#vin=0
https://mempool.space/tx/7d027ca0bdd411b613ce68b567dc1d62689bd5e5e86cc0787093da73d36e881e#vin=0
https://mempool.space/tx/f58bc779bd8a74dd33f6ca2e80da1d62865f0ccd2af6c4094737ac7b85e3ad3e#vin=0
https://mempool.space/tx/7bb78ab6d9b9e4606b20b5c5b49c1bce3d8daec621ff767c6bec754913a94630#vin=0
https://mempool.space/tx/f9c55670f53f471f5dd759baf4679bb954a48617915b1172850e531db7ca52ed#vin=0
https://mempool.space/tx/1f0cb7d5da42bb2d76f13a2578c1ec2f71fb57a979c57ab14993b8a36345207d#vin=0
https://mempool.space/tx/6eb0b9127af4af4cf533238fad6f49559ef91f7e2bc29707aa91cb8688ed98e7#vin=0
https://mempool.space/tx/ae109dd3eccb1b7611e0f46c73e4f697153adc156a48bc3e5714e23c884f2df0#vin=0
https://mempool.space/tx/22a5c21790379a4a10b88b7551b3adb1774e93a6b231049139c6c1efe1670a70#vin=0
https://mempool.space/tx/6368fea16448e7fb5284e8ce0453ba044145eb4e07d7b52d601cb1b3e1590f43#vin=0

and those are just from the first few pages of the Bcash_Is_Trash channel list on Amboss.

I really hope we have an easier way to force anchor channels. Using channel acceptor seems to be too daunting for non-techies like myself.
