### ISSUE TITLE
unable to start server: address type cannot be resolved

### ISSUE THREAD

**Issue by BenBHG** [lightningnetwork/lnd#749]
After a day or so of use, I noticed lnd had started to use all of my cpu time after unlocking it.  Rebooted, pulled latest master branch.  Now every time I unlock lnd, I get this error after a few seconds, directly after the graph pruning is complete.

2018-02-09 22:37:35.317 [ERR] SRVR: unable to start server: address type cannot be resolved

The process exits.  This is on mainnet since I am reckless, so I am hoping there is a recovery option at least eventually.  The problem started shortly after I was able to purchase some blockstream swag, so at least I got that going for me.

**Comment by cfromknecht** [comment]
Our address serialization changed to support tor addresses, try reverting back to your old commit. Breaking changes are being pushed daily, just assume updating will break compatibility
