### ISSUE TITLE
[bug]: LND rejecting message number 7?

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#7498]
### Background

We've got at least one report of LND disconnecting when it received (unknown msg) 7: https://github.com/ElementsProject/lightning/issues/6065#issuecomment-1455172259

This happens when people turn on the `experimental-peer-storage` option in core lightning.

### Your environment

admin ~ ฿ lncli getinfo
{
    "version": "0.15.5-beta commit=v0.15.5-beta",
    "commit_hash": "c0a09209782b1c62c3393fcea0844e095c25046b",
    "identity_pubkey": "037f66e84e38fc2787d578599dfe1fcb7b71f9de4fb1e453c5ab85c05f5ce8c2e3",
    "alias": "HODLmeTight",

### Steps to reproduce

I can probably send one manually, though we are doing to change our code to only send to peers if they advertize the peer-backup feature for now.

### Expected behaviour

Nothing, `it's OK to be odd`.

### Actual behaviour

Disconnection and eventual unhappiness :(

**Comment by Roasbeef** [comment]
Odd (no pun intended lol), we should just log that and keep chugging: https://github.com/lightningnetwork/lnd/blob/master/peer/brontide.go#L1484-L1491 and [also have for some time](https://github.com/lightningnetwork/lnd/commit/f82d957c9080a80caf8e58e28c195085b2ef1815). The log line is expected, but if _that's_ what caused a disconnect, there should be another log below like `EOF` or w/e. 

We should definitely not be disconnecting, but a feature bit could be used in theory to only send to those that know of the feature bit, which might also be useful in finding peers in the wild that support the peer storage feature as well.

**Comment by rustyrussell** [comment]
Red herring then?  OK, something else is going on, thanks!
