### ISSUE TITLE
[bug]: rebalance payment stuck and cause force close

### ISSUE THREAD

**Issue by scissorstail** [lightningnetwork/lnd#7509]
### Background

Describe your issue here.

### Your environment

* 0.15.5-beta
* Linux server 5.15.0-67-generic x86_64 x86_64 x86_64 GNU/Linux
* bitcoind:v24.0.1
* Using docker image from **lightninglabs/lnd:v0.15.5-beta**, bitcoind is running on another machine and connected with RPC

### Steps to reproduce

During rebalancing, sometimes certain attempts do not resolve until they are force-closed.
I have confirmed that all nodes on the rebalancing path are alive.

There are currently two HTLCs in the same situation, with ~64(resolved) and~ 95 hours left until expiration, respectively.
I am losing channels little by little. 

### Expected behaviour

Rebalance HTLC resolved

### Actual behaviour

Rebalance HTLC not resolved and finally force-closed

**Comment by alexbosworth** [comment]
what is your cltv delta?

**Comment by scissorstail** [comment]
It is 144.

**Comment by ziggie1984** [comment]
```
; A period to wait before for closing channels with outgoing htlcs that have
; timed out and are a result of this nodes instead payment. In addition to our
; current block based deadline, if specified this grace period will also be taken
; into account. Valid time units are {s, m, h}.
; payments-expiration-grace-period=30s
```


Set this in your config to a very high value and you should be fine!

**Comment by scissorstail** [comment]
Since the two mentioned HTLCs have been resolved, I cannot be certain if the rebalance was the cause. As it's resolved now, I close this issue. thanks.

**Comment by scissorstail** [comment]
It happened again today in front of me and I checked the logs. It is a duplicate of #7180
But I don't know why this is happening almost once a week. I think it would be better to reduce the rebalance attempts.
