### ISSUE TITLE
Macaroon revoke

### ISSUE THREAD

**Issue by petrkr** [lightningnetwork/lnd#7523]
After security issue at GB ATM ( https://generalbytes.atlassian.net/wiki/spaces/ESD/pages/2885222430/Security+Incident+March+17-18th+2023 )
is important to have some mechanism to revoke macaroons used in such systems. Now only way would be  close all channels and create new wallet. That is huge FAIL

**Comment by alexbosworth** [comment]
did you try deleting the macaroons db?

**Comment by petrkr** [comment]
no.. I do not want delete all. but maybe it could be better solution than recreate whole wallet.. but I tried list macaroonids, but it gives only one.

```
 $ ./lncli listmacaroonids
{
    "root_key_ids": [
        "0"
    ]
}
```
I can not see others and I know I bake like 4 or 5 already, also some testing which never was used. But I do not know why I not see them on this list

**Comment by alexbosworth** [comment]
ok, if you provisioned macaroons you could also try the `DeleteMacaroonId` API?

**Comment by petrkr** [comment]
> ok, if you provisioned macaroons you could also try the `DeleteMacaroonId` API?

but where I can get those ID if list ids not return any than one?

I bake them by using web ui (that other than RTL, do not remember it name now)

**Comment by alexbosworth** [comment]
When you use the `BakeMacaroon` API to provision the access credential you can give it the the ID that you want

**Comment by guggero** [comment]
All default macaroons are created from the root key with ID `0`.
You can revoke those macaroons by deleting the root key ID 0 as documented here: https://github.com/lightningnetwork/lnd/blob/master/macaroons/README.md#root-key-rotation
The alternative is to delete the `macaroons.db` completely (as mentioned above, which basically has the same effect).

If you want more control over what to revoke, you need to bake your own macaroons, using custom keys.
The way to invalidate macaroons has also been documented for a while in our safety doc: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#macaroons

**Comment by petrkr** [comment]
based on that documentation `That means, individual tokens cannot currently be invalidated, only all of them at once.`

But still better than new wallet... I think it's best thing what I can do,, for lucky I do not have too much macaroons around, maybe like 2-3 systems. So it would be enough to re-issue...

I somewhere in documentation read that rotate was in TODO list, but now I can not find that page. There is lot of documentation and if you do not know what to look for, you simply can not find it in some subfolder's README

**Comment by guggero** [comment]
The main safety doc (which is linked to in the top level README) links to both macaroon README docs in the sub folders.

I think the only TODO left is automatic rotation. But that brings a lot of user experience gotchas with it (when to rotate? how to inform the user? how configurable), so for now there is just the manual rotation.

I'm going to close the issue as everything you are asking for has already been implemented and documented.
