### ISSUE TITLE
double-spend when closing channel

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#753]
1. Connect to https://faucet.lightning.community/
2. Open channel from https://faucet.lightning.community/
3. Close channel using lncli close
4. Double spent transaction occurs:
https://live.blockcypher.com/btc-testnet/tx/0ccfa67b4f2a4b36f100ee4b9cee5e090c0e31ea4315de012c894a2fb7ccf1f2/

**Comment by Roasbeef** [comment]
Can you elaborate on point 4? It's possible that if your fees differ, then both parties my broadcast a distinct closing transaction. This isn't an issue though, as we'll watch for all possible closes and reconcile our database state once one of them actually confirms.

**Comment by halseth** [comment]
Looks like the outputs of both transactions are P2WKH, so this means they somehow disagreed during close negotiation?

**Comment by Roasbeef** [comment]
Even if they were `p2wkh` it's no issue (or should be) due to the way we watch for _every_ signed state. Even if both sides broadcasted diff closing transactions, only _one_ will get into the chain. That's the one that we _should_ use to mark the channel closed using.

**Comment by halseth** [comment]
Yeah, but cooperative close means that they were able to agree on some final fee, right? Haven't looked at that logic in a while, but two different cooperative close transactions means that they both signed twice, which sounds buggy.

**Comment by MrHash** [comment]
Could be same as #538

**Comment by Roasbeef** [comment]
Fixed in #1017.
