### ISSUE TITLE
LND does not recover limbo balance from Borked channels

### ISSUE THREAD

**Issue by pvorangecrush** [lightningnetwork/lnd#7548]
### Background
I had 4 force closes that got "ChanStatusBorked". The limbo_balance which should be owed to me just sits in a V0_P2WSH output. I can't find any evidence that LND is tracking these outputs and will attempt to claim them into the wallet. For one of these closures it has been 2041 confirmations, so I think csv_delay has likely been passed. To me it seems LND is not trying to claim these funds. How do I do so? Are the funds lost for all time?

### Your environment

* LND: "v0.15.5-beta",
* Linux: "19.0-35-generic 36~22.04.1-Ubuntu"
* bitcoind: v24.99.0-78aee0fe2ca7

### Steps to reproduce

All channels that have channel status ChanStatusBorked fail to claim limbo funds to wallet.

ChannelPoint: d6e99309184e39e44b2c645d2f092e639ba9ff8fd4b571199131a40bde0fad5d:0
ClosingTx: 1e71b62453757b32246fcfe07e257e055572f675295143d3657dcf05f3bcbbfe

ChannelPoint: 2a150dea324cc6ae0da58d7d4e69417402bac0a0dc36bb07410ca776ec987da6:1
ClosingTx: 22fdea129652378ed6c12045754e692ca3a5472eb614efc59b434be9d86d2f22

ChannelPoint: af25ab94051503e0a44f0672af2bf6547859b771b0a73315dc2e410ec19f9c0a:2
ClosingTx: 45e034087408f1156bb86ede9d056cd9224e148d39764c68fe84bc9162c16e69

ChannelPoint: 739db084c4093385e993c745e72f1b21e886a6f61388532851d51e8b3cbddcb0:0
ClosingTx: 78b8c3c58e210f9fd73db6aa544d7f6d4887602c738b257d3509149be46a8044

### Expected behaviour
Limbo funds should be spendable in wallet.

### Actual behaviour
Limbo funds are not spendable in wallet.

**Comment by guggero** [comment]
The funds are definitely not lost. The main question is why they got into the borked state in the first place. Do you remember why or when exactly it happened? Did you experience data corruption or other issues with your `channel.db`?

Also, how do these channels show up in your `lnd`? Are they in the `lncli pendingchannels` output?
What side issued the force close?

Can you also check your log please? It could be that lnd is attempting to sweep the funds but is unable to because of the fee rate (or mempool size).

**Comment by pvorangecrush** [comment]
They are all four in my pending channels:
2 were force closed by remote and 2 by local.
Of note, I was having this issue, #6434 but resolved that issue just now by upgrading to v0.16.0-beta

The channels became borked in different ways:
This one says "INITIATOR_LOCAL" and my local closing txid was confirmed to blockchain. The channel partner was offline for an extended period and lnd intiated the force close
ChannelPoint: d6e99309184e39e44b2c645d2f092e639ba9ff8fd4b571199131a40bde0fad5d:0
ClosingTx: 1e71b62453757b32246fcfe07e257e055572f675295143d3657dcf05f3bcbbfe

This one says "INITIATOR_REMOTE" *but* my local closing txid was confirmed to blockchain not the remote close transaction. I attempted cooperative close, but then accidently closed the running "lncli closechannel" . After that, I initiated a --force close
ChannelPoint: 2a150dea324cc6ae0da58d7d4e69417402bac0a0dc36bb07410ca776ec987da6:1
ClosingTx: 22fdea129652378ed6c12045754e692ca3a5472eb614efc59b434be9d86d2f22


This one says "INITIATOR_LOCAL" and my local closing txid was confirmed to blockchain. The channel partner was offline for an extended period and lnd intiated the force close
ChannelPoint: af25ab94051503e0a44f0672af2bf6547859b771b0a73315dc2e410ec19f9c0a:2
ClosingTx: 45e034087408f1156bb86ede9d056cd9224e148d39764c68fe84bc9162c16e69

This one says "INITIATOR_REMOTE" and my local txid is listed in closing_txid but the remote closing tx was accepted to the blockchain (I listed the remote closing txid below). The channel was incorrectly set as active, though the closing transaction had been published by the peer days earlier when my node was offline for 2 hours. I restarted LND and LND then recognized a force close had taken place but adopted the "Borked" status.
ChannelPoint: 739db084c4093385e993c745e72f1b21e886a6f61388532851d51e8b3cbddcb0:0
ClosingTx: 78b8c3c58e210f9fd73db6aa544d7f6d4887602c738b257d3509149be46a8044

In all cases the correct limbo balance was moved to an address that is not listed in my lncli listunspent. Could this be related to the bug where I had spent UTXOs in my "listunspent" caused by zero change transactions? Its like the wallet just doesn't claim anything from these channels. The outputs equal to the limbo balance from the closing tx's remain unspent for now.

**Comment by guggero** [comment]
I think the `INITIATOR_*` value just indicates who _opened_ the channel initially.

Hmm, none of these actions would explain the "borked" status. Quite weird.

>  was moved to an address that is not listed in my lncli listunspent.

That is normal, if your node force closes then those funds are time locked and need to be sweeped into a non-script wallet address. Can you check your logs by grepping for one of the closing transactions please? Anything with the SWPR prefix should be interesting.

**Comment by pvorangecrush** [comment]
The odd part is that it is trying to sweep an output:
22fdea129652378ed6c12045754e692ca3a5472eb614efc59b434be9d86d2f22:1

that has already been spent here:
6348df063362b20feca73266f8246b2394cae912af0f7d60a8d9e6d55ccc800f

`2023-03-29 12:05:08.045 [INF] SWPR: Sweep request received: out_point=22fdea129652378ed6c12045754e692ca3a5472eb614efc59b434be9d86d2f22:1, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc009520c98)
2023-03-29 12:05:08.047 [INF] SWPR: Sweep request received: out_point=a152b779301dd0431c2052c65ca7e98af6f4df0d9f5847fe38a0904683baba47:1, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc009520c98)
`
This outpoint a152b779301dd0431c2052c65ca7e98af6f4df0d9f5847fe38a0904683baba47:1 is from the remote_closing_txid which was never published to blockchain.

**Comment by pvorangecrush** [comment]
Also, it does look like the fee preference is too low, so it is not attempting publishing (at whence point might it recognize that the outputs were previously swept??)

```
2023-03-29 13:34:28.146 [WRN] SWPR: Skipping input 78b8c3c58e210f9fd73db6aa544d7f6d4887602c738b257d3509149be46a8044:1: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.148 [WRN] SWPR: Skipping input a152b779301dd0431c2052c65ca7e98af6f4df0d9f5847fe38a0904683baba47:1: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.149 [WRN] SWPR: Skipping input 1e71b62453757b32246fcfe07e257e055572f675295143d3657dcf05f3bcbbfe:0: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.151 [WRN] SWPR: Skipping input 22fdea129652378ed6c12045754e692ca3a5472eb614efc59b434be9d86d2f22:1: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.152 [WRN] SWPR: Skipping input f2436b4616ee0b19a32b522597afe31f6ce499b79ba2dc5abd3564796de6e76b:0: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.154 [WRN] SWPR: Skipping input b637390f27a9cc1e6ee1ee633a7954776a2ed326d5602ac601f3fdbb99fc4ea8:1: fee preference resulted in invalid fee rate 514 sat/kw, minimum is 522 sat/kw
2023-03-29 13:34:28.155 [INF] SWPR: Sweep candidates at height=783075 with fee_rate=7446 sat/kw, yield 0 distinct txns
2023-03-29 13:34:28.155 [INF] SWPR: Sweep candidates at height=783075 with fee_rate=7446 sat/kw, yield 0 distinct txns
2023-03-29 13:34:28.155 [INF] SWPR: Sweep candidates at height=783075 with fee_rate=7446 sat/kw, yield 0 distinct txns
2023-03-29 13:34:28.162 [INF] HSWC: Garbage collected 163 shared secret hashes at height=783075
```

**Comment by pvorangecrush** [comment]
I may be narrowing in on the problem. I noticed that all sweep transactions give reference to an already on-chain transaction:

```
2023-03-28 16:00:37.836 [INF] SWPR: Creating sweep transaction 58753f16633349fcb964ef59be0adf240ea9473426923fa9349533f617bdc8c1 for 2 inputs (cc9b7a013610507bf3dff67b2df6bcdd3aad914f71e606f8488395fef1c9bc92:1 (CommitmentAnchor), 9a2d91786efd8865cdac8257872ebc987b2cc5d14feaf2fb533587a80260da73:0 (TaprootPubKeySpend)) using 6162 sat/kw, tx_weight=725, tx_fee=0.00009163 BTC, parents_count=1, parents_fee=0.00003241 BTC, parents_weight=1288
```

**9a2d91786efd8865cdac8257872ebc987b2cc5d14feaf2fb533587a80260da73** was confirmed two days ago. Following the resolution of issue #7390 I have re-published this previously spent transaction with lncli wallet publishtx <hex of transaction 9a2d...da73>, which will hopefully free the sweeper up. I did the same for all the previous force closes so that sweeper will recognize those transactions as spent as well. I also went back and republished the channel open transactions and interestingly, one of them was not recognized as previously published despite it being a prior channel point.

**Comment by guggero** [comment]
Okay, so good to know that `lnd` is still attempting to sweep. So it is indeed a mempool/fee issue. What size is your bitcoind's mempool allowance? (`-maxmempool`)? And are you using a non-default value in lnd for `--bitcoind.estimatemode`?

Can you try upgrading to 0.16.0 that was just released? That improved some things around transaction broadcasting. If that still doesn't help, you can try to rescan your unspent outputs by starting with `--reset-wallet-transactions`.

**Comment by guggero** [comment]
Hmm, I'm not sure how you can convince the sweeper to forget those swept anchors. We'll take a look at it.
In the meantime, you could use [`chantools sweeptimelockmanual`](https://github.com/guggero/chantools/blob/master/doc/chantools_sweeptimelockmanual.md) to sweep them yourself, as a workaround.

**Comment by pvorangecrush** [comment]
@guggero 

> To get the value for --timelockaddr you must look up the channel's funding output on chain, then follow it to the force close output. The time locked address is always the one that's longer (because it's P2WSH and not P2PKH).

It is not clear what this means as all the output in the closing transaction were P2WSH. Do you mean the unspent output address of the closing transaction?

**Comment by guggero** [comment]
Oh, I just realized I never updated `chantools` to work with anchor channels... That's probably why things don't work as expected. Also, I'd be very careful when doing things with the channel DB directly. That could have bad impact on any online channels. So please don't run any random commands. You will be able to recover the funds, don't worry. Just a bit of patience is needed.

**Comment by pvorangecrush** [comment]
Yes, I’ve only been exploring a csv dump of an offline copy I made of the channel.db to see what information is there. My node is still online. Is there some guide or spec for force close anchor transactions? Most of the information I find through GitHub or Google searches is woefully outdated so I must be looking in the wrong places.

**Comment by pvorangecrush** [comment]
@guggero First, **thank you for your continued assistance**. I am using the correct revocation base point from the remote config. I am running again with --maxnumchanupdates set at 500000 and --maxnumchanstotal set 1000. Should take a while judging form how long the first key test is taking. 

My anchor sweeps are still broken while the SWPR keeps trying to bundle these old spent transactions. Seeing about 50-100 per day. Not sure how to remove them from pending sweeps since I can't abandon the channels until I get the funds out. But would abandoning the channels help? Once the funds are recaptured, of course.

**Comment by guggero** [comment]
You're welcome!
Ah, yes, if the remote peer force closed, then you need to run `sweepremoteclosed`, which requires far fewer arguments.

I think once the channel funds are swept manually, lnd should recognize there's nothing to sweep anymore and should also stop trying to sweep the anchor (I think/hope). If not, then yes, abandoning might help (but be double certain that all funds were swept first).

**Comment by pvorangecrush** [comment]
1 of 4 recovered. Thank you so much! The remaining 3 were all locally initiated, so I will search for the key using `chantools sweeptimelockmanual`.

Then, it will be getting those pesky anchor sweeps cleared out of LND and I'll have a node I can trust again.

**Comment by pvorangecrush** [comment]
@guggero what triggers a channel update? I frequently (every 60s) update the fees and max_htlc with management scripts. Would each of these calls cause an **update** to the channel? This information is needed to estimate what number I should use with `--maxnumchanupdates`. At 50,000 updates, I did not uncover any keys. Trying again with 500,000 but it will take about a week to get through each channel (I am running each `chantools sweeptimelockmanual` call in parallel). If I need to go higher, then I will likely need to fork the chantools code for asynchronous execution.

Also, LND still has not cleared the _already swept_ anchor sweep transactions, so I don't anticipate that problem correcting itself.

**Comment by guggero** [comment]
No, channel forwarding fees or max HTLC settings don't cause a channel update. Only forwarded HTLCs, payments or chain fee updates (for pre-anchor channels).
Oh, 4 weeks is a lot... Maybe try with smaller values for the other flags? For example, you can use `chantools dumpbackup` to get a human-readable version of your channel backup file. Then check each derivation path (e.g. `Path: (string) (len=18) "m/1017'/0'/0'/0/18",`) and pick the highest value you see for the last number (in the example `18`) as the value for `--maxnumchanstotal`. That should speed up things a bit already.

**Comment by eliotcougar** [comment]
I have the same issue right now.
Two days ago the anchor has been swept by a third party, and since then I get `Unable to rebroadcast transaction e0242fef13159320adac6cfcf286a054919466f184f94006f34eb59b8b852339: -25: bad-txns-inputs-missingorspent` every minute...
There are no pending sweeps, but the rebroadcaster doesn't seem to check if the anchors have been swept already.

**Comment by guggero** [comment]
With the mempool now clearing and a few fixes added around sweeping/publishing, can you try again with `lnd 0.16.1-beta` that was just released? Maybe the broadcast works now. If not, please hit me up on [Slack](https://lightning.engineering/slack.html), I have some ideas to speed up the `sweeptimelock` command to allow you to search for more updates.

**Comment by pvorangecrush** [comment]
@guggero nudging this cold case. do you have any idea how I can get the sats out?  Was my revocation point out of date? Maybe the other channel party has the correct revocation point? What specifically should I ask them?

**Comment by guggero** [comment]
You can try running this PR of `chantools` directly, which speeds up the key brute force considerably, allowing you to try more channel updates (I would recommend trying at least 2 million). Also, you can run this on any computer, so you might want to try a faster desktop or laptop in case your node is on a Raspberry Pi.

**Comment by pvorangecrush** [comment]
@guggero Thank you! I will try the PR. I was running on a good workstation with ample resources. Is it possible my revocation point was out of date? And is it possible to recover the correct revocation point from someone else? My channel counterpart?

**Comment by pvorangecrush** [comment]
@guggero I was never able to recover the balance with chantools. By some lightning magic, i was able to recover this balance and other borked channel balances by restoring my wallet to an umbrel lightning node then recovering the channel.backup by command line on the umbrel. For posterity, I would caution others to not to blindly follow in this path, any open channel balances might be lost. But... never ever thought it would work but it did! Issue closed: LND recovered the balances on latest version after restoring node from seed then restoring channel.backup.

Happy new year!
