### ISSUE TITLE
Multi-signature wallet question

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#755]
When testing LND, I often corrupt the wallet by upgrading LND and tracking on-chain transactions is not as intuitive as with a GUI wallet.

How can connect LND to a multi-signature wallet with 2 cosigners and 1 required signature so that I can move funds during upgrades and track on-chain transactions via an GUI wallet?

**Comment by dabura667** [comment]
You can’t.

**Comment by alevchuk** [comment]
Can I get the public key out of the lnd wallet to run a watch-only GUI wallet?

**Comment by dabura667** [comment]
For the onchain funds, yes. for the channel funds, no.

You need to write a script using btcwallet package from go, though.

**Comment by Roasbeef** [comment]
> When testing LND, I often corrupt the wallet by upgrading LND and tracking on-chain transactions is not as intuitive as with a GUI wallet.

The upgrading then everything breaks is a temporary phase during this period of instability before the initial stable release. You'd need to write your own `WalletController` and `Signer` implementations in order to accomplish something like this.

**Comment by tlindi** [comment]
[Similar question to https://github.com/lightningnetwork/lnd/issues/3933](https://github.com/lightningnetwork/lnd/issues/3933#issuecomment-1346348818)
