### ISSUE TITLE
lncli: unify handling of positional and flag command line arguments

### ISSUE THREAD

**Issue by merehap** [lightningnetwork/lnd#756]
When using lncli commands and passing in arguments that can be either a flag or positional, different results are printed to the screen in the event of an error. When passing an invalid positional arg, one error message is supplied, while passing an invalid flag arg results in a different error message being supplied and the usage being printed. This occurs for openchannel, as seen below, but also most other commands. 

Positional Local Amount:
```
sean@dmt:~$ lncli openchannel 03324ef21e77714cdc1ad7fadda808a7aca2b7f8d31cd737923d42164dac00a02d InvalidLocalAmount 3000
[lncli] unable to decode local amt: strconv.ParseInt: parsing "InvalidLocalAmount": invalid syntax
```

Flag Local Amount:
```
sean@dmt:~$ lncli openchannel --local_amt InvalidLocalAmount 03324ef21e77714cdc1ad7fadda808a7aca2b7f8d31cd737923d42164dac00a02d 3000
Incorrect Usage: invalid value "InvalidLocalAmount" for flag -local_amt: strconv.ParseInt: parsing "InvalidLocalAmount": invalid syntax

NAME:
   lncli openchannel - Open a channel to an existing peer.

USAGE:
   lncli openchannel [command options] node-key local-amt push-amt

DESCRIPTION:
   
  Attempt to open a new channel to an existing peer with the key node-key
  optionally blocking until the channel is 'open'.

  The channel will be initialized with local-amt satoshis local and push-amt
  satoshis for the remote node. Once the channel is open, a channelPoint (txid:vout) 
  of the funding output is returned. 

  One can manually set the fee to be used for the funding transaction via either
  the --conf_target or --sat_per_byte arguments. This is optional.
    
  NOTE: peer_id and node_key are mutually exclusive, only one should be used, not both.

OPTIONS:
   --peer_id value        the relative id of the peer to open a channel with (default: 0)
   --node_key value       the identity public key of the target peer serialized in compressed format
   --local_amt value      the number of satoshis the wallet should commit to the channel (default: 0)
   --push_amt value       the number of satoshis to push to the remote side as part of the initial commitment state (default: 0)
   --block                block and wait until the channel is fully open
   --conf_target value    (optional) the number of blocks that the transaction *should* confirm in, will be used for fee estimation (default: 0)
   --sat_per_byte value   (optional) a manual fee expressed in sat/byte that should be used when crafting the transaction (default: 0)
   --private              make the channel private, such that it won't be announced to the greater network, and nodes other than the two channel endpoints must be explicitly told about it to be able to route through it
   --min_htlc_msat value  (optional) the minimum value we will require for incoming HTLCs on the channel (default: 0)
   
[lncli] invalid value "InvalidLocalAmount" for flag -local_amt: strconv.ParseInt: parsing "InvalidLocalAmount": invalid syntax

```

There are multiple benefits to unifying the argument handling:

1. User experience will be more consistent, including for scripts that call lncli.
2. Error handling can be done at a single level, rather than done in commands.go for positional args and done in the cli library for flag args (which is currently the case).
3. A decent amount of lines of redundant code can be removed.
4. Adding new parameters in the future will be less error prone since there will be an established, known-good helper function to handle it.
5. Essentially the same unit tests can be written for both cases, whereas now the unit tests have to be significantly different.

If the argument-handling methods are unified, what should be printed? Just the error message, or the error message and usage? It seems preferable to just print the error message as its unclear what help the usage is in this context.

I can prepare a PR for this change, but I'd like to have unit tests in place first. Currently getting unit tests in place is blocked on approval/merging of #728. I have unit tests in my repository that document the current behavior here:
https://github.com/merehap/lnd/blob/cli_errors/cmd/lncli/open_channel_test.go#L174
versus
https://github.com/merehap/lnd/blob/cli_errors/cmd/lncli/open_channel_test.go#L184

**Comment by Roasbeef** [comment]
Closing this for now since momentum died out, and most of the newer CLI commands are following this principle.
