### ISSUE TITLE
[feature]: Init watchOnly wallet on Lnd node with external xpub keys

### ISSUE THREAD

**Issue by Jaccccc8** [lightningnetwork/lnd#7567]
We're evaluating the integration of Lightning, we've a mandate rule that all keys/seed are generated by algorithm, the private/credentials ones are stored in our own database, only pubKeys could be revealed/imported to nodes.

Now we encounter blocker issues when trying to call InitWallet(https://lightning.engineering/api-docs/api/lnd/wallet-unlocker/init-wallet/index.html) with external xpub keys, we followed https://github.com/lightningnetwork/lnd/blob/master/docs/remote-signing.md ("The signer node" ignored, since we will implement our own signer service unrelated to Lnd nodes), but got error:

> unable to create wallet: address manager is watching-only
2023-04-04 03:56:12.016 [ERR] LTND: Shutting down because error in main method: error loading chain control: unable to create chain control: unable to create wallet: address manager is watching-only
2023-04-04 03:56:12.017 [INF] LTND: Shutdown complete
error loading chain control: unable to create chain control: unable to create wallet: address manager is watching-only

How to solve this and is there a way to meet our requirements? any advise is appreciated.

**Comment by Roasbeef** [comment]
> "The signer node" ignored, since we will implement our own signer service unrelated to Lnd nodes

Can you elaborate on this? The guide there is based on an assumption that lnd is used as the other signer. 

Here's an example of a 3rd party signer: https://github.com/bottlepay/lndsigner

Are you able to reliable reproduce with clean slate on all sides? Can you list you steps in series so we can try to see where things mess up?

**Comment by Jaccccc8** [comment]
@Roasbeef 
First, i have read https://github.com/bottlepay/lndsigner last week, 

Second, the steps are simpe enough.
1. a brand new Lnd node, set [remotesigner] in lnd.conf:
```
remotesigner.enable=true
remotesigner.rpchost=ip:port --a fake one, we've not implemented signer yet
remotesigner.tlscertpath=/server/signer.tls.cert
remotesigner.macaroonpath=/server/signer.custom.macaroon
```
2. use /v1/initwallet to create a watch-only wallet.
xpubs are copied(partly) from a pervious normal Lnd wallet.
```
curl -X POST -H "Content-Type: application/json" --data '{"wallet_password":"xxxx", "recovery_window":10, "watch_only": {"accounts": [{
	"xpub": "ypub6XztcrJC97zpRr9h7RuHxhrpMyCEtzU2zAxboqZ13CCF63DventyrQbMjZZb65mFjSad5nZukAa5LaNJqE8JV6XMsNGartNjgS98CqUwVAn",
    "purpose": "49",
	"coin_type": 0,
	"account": 0
}, {
	"xpub": "zpub6r8HTATwVYw8dES5j7ysjQuzVrAnjsQNwMVbv4KnJzyoUPBZ6i3gmr3Kd8tn1wutZJnU5Mp6c6aGuT9B2DbzXbsDRggGD4NYw5zPoM17Agw",
    "purpose": "84",
	"coin_type": 0,
	"account": 0
}, {
	"xpub": "xpub6DAKzSLh3xUymX44pTNbP2vU83jpMwDTo4Yrpa4kWNn1nteBuMfrMv9cTRQGYz5m9hd2o3tzTkT3FYDeXJboRzcSxDsQgSHXVUgXojdfAVE",
    "purpose": "86",
	"coin_type": 0,
	"account": 0
}, {
	"xpub": "xpub6CRPRWLes4GdFjDUsXcFDBBWX5dquyVWXGRYWQ7dNDUxHZfDsMFtvhBPZTzDyXav8FnexPLSYpXhP29sCfLNdDpTgjf6xv7KumrHn5YSYoW",
    "purpose": "1017",
	"coin_type": 0,
	"account": 0
}, {
	"xpub": "xpub6CRPRWLes4GdHYHaVLNXresnHaXjrqviBhw8BDnRKsYvet7cQSs7TK6oS8sRtbuSdSpWnNGccYSh5Qqo1NmEUfDXXfVNt9n93UhWrsNx6Kw",
    "purpose": "1017",
	"coin_type": 0,
	"account": 1
} ]} } ' https://lnd**/v1/initwallet  -k
```
so my post errors was due to that remote signer <-> Lnd node communication error, can you tell the tech details?

**Comment by johnsonco** [comment]
> > "The signer node" ignored, since we will implement our own signer service unrelated to Lnd nodes
> 
> Can you elaborate on this? The guide there is based on an assumption that lnd is used as the other signer.
> 
> Here's an example of a 3rd party signer: https://github.com/bottlepay/lndsigner
> 
> Are you able to reliable reproduce with clean slate on all sides? Can you list you steps in series so we can try to see where things mess up?

We want to deploy a watch-only lnd and import our pre-generated xpubs. The steps I used are exactly the same as this document: https://github.com/lightningnetwork/lnd/blob/master/docs/remote-signing.md#the-watch-only-node

## Deploy a full seed lnd
lnd.conf
```
[Application Options]
nolisten=true
nobootstrap=true

rpclisten=0.0.0.0:10009
[bitcoin]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=nochainbackend
```
The first time launched it prompts to create a wallet:
```
2023-04-10 08:30:20.166 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
```
I used `lncli create` to create a wallet and saved the words.
```
./lncli create
```

Create the `signer.custom.macaroon` file
```
./lncli bakemacaroon --save_to signer.custom.macaroon \
                message:write signer:generate address:read onchain:write
```

Now the lnd is good to go:
```
2023-04-10 08:31:09.223 [INF] CHNF: ChannelNotifier starting
2023-04-10 08:31:09.223 [INF] PRNF: PeerNotifier starting
2023-04-10 08:31:09.223 [INF] HSWC: HtlcNotifier starting
2023-04-10 08:31:09.223 [INF] SWPR: Sweeper starting
2023-04-10 08:31:09.223 [INF] UTXN: UTXO nursery starting
2023-04-10 08:31:09.223 [INF] BRAR: Breach arbiter starting
2023-04-10 08:31:09.223 [INF] FNDG: Funding manager starting
2023-04-10 08:31:09.223 [INF] HSWC: HTLC Switch starting
2023-04-10 08:31:09.223 [INF] CNCT: ChainArbitrator starting
2023-04-10 08:31:09.223 [INF] DISC: Authenticated Gossiper starting
2023-04-10 08:31:09.223 [INF] BRAR: Starting contract observer, watching for breaches.
2023-04-10 08:31:09.223 [INF] CRTR: Channel Router starting
2023-04-10 08:31:09.223 [INF] CRTR: Filtering chain using 0 channels active
2023-04-10 08:31:09.223 [INF] CRTR: Prune tip for Channel Graph: height=1, hash=0000000000000000000000000000000000000000000000000000000000000001
2023-04-10 08:31:09.224 [INF] INVC: InvoiceRegistry starting
2023-04-10 08:31:09.224 [INF] HSWC: Onion processor starting
2023-04-10 08:31:09.224 [INF] NANN: Channel Status Manager starting
2023-04-10 08:31:09.224 [INF] CHFT: ChannelEventStore starting
2023-04-10 08:31:09.224 [INF] CHFT: Adding 0 channels to event store
2023-04-10 08:31:09.225 [INF] CHBU: chanbackup.SubSwapper starting
2023-04-10 08:31:09.229 [INF] CHBU: Updating backup file at /home/ubuntu/.lnd/data/chain/bitcoin/mainnet/channel.backup
2023-04-10 08:31:09.230 [INF] CHBU: Swapping old multi backup file from /home/ubuntu/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.backup to /home/ubuntu/.lnd/data/chain/bitcoin/mainnet/channel.backup
2023-04-10 08:31:09.231 [INF] SRVR: Auto peer bootstrapping is disabled
```

## Deploy a watch-only lnd
Copy `tls.cert` and `signer.custom.macaroon` files from `full seed lnd` to `watch-only lnd`

lnd.conf
```
[Application Options]
datadir=/data/data
restlisten=127.0.0.1:8080
no-rest-tls=true
logdir=/server/data/logs
wallet-unlock-password-file=/data/wallet-password
wallet-unlock-allow-create=true
no-macaroons=true

[Bitcoin]
bitcoin.active=true
bitcoin.chaindir=/data/chain/bitcoin
bitcoin.mainnet=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcpolling=true
bitcoind.blockpollinginterval=1m
bitcoind.txpollinginterval=30s

bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=rpc
bitcoind.rpcpass=rpc
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[remotesigner]
remotesigner.enable=true
remotesigner.rpchost={{ full_seed_lnd }}:10009
remotesigner.tlscertpath=/data/signer.tls.cert
remotesigner.macaroonpath=/data/signer.custom.macaroon
```
The first time launched it prompts to create a wallet:
```
2023-04-10 08:26:45.324 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
```
I used `lncli createwatchonly` to create the wallet with pre-edited json file. Got no reponse this step.
```
$ ./lncli createwatchonly lightning-import.json
Input wallet password:
Confirm password:

Input an optional wallet birthday unix timestamp of first block to start scanning from (default 0):
Input an optional address look-ahead used to scan for used keys (default 2500):
```

lightning-import.json
```
    "accounts": [
        {
            "name": "default",
            "address_type": "HYBRID_NESTED_WITNESS_PUBKEY_HASH",
            "extended_public_key": "ypubdummypublickeywhatever",
            "master_key_fingerprint": null,
            "derivation_path": "m/49'/0'/0'",
            "external_key_count": 0,
            "internal_key_count": 0,
            "watch_only": false
        },
        xxx
```

Check the stdout of `lnd`
```
2023-04-10 08:33:40.902 [INF] LTND: Attempting automatic wallet unlock with password provided in file
2023-04-10 08:33:41.763 [INF] LNWL: Opened wallet
2023-04-10 08:33:41.763 [INF] CHRE: Primary chain is set to: bitcoin
2023-04-10 08:33:41.778 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
2023-04-10 08:33:41.778 [INF] LNWL: Started polling for new bitcoind blocks via RPC at height 784759
2023-04-10 08:33:41.778 [INF] LNWL: Started polling for new bitcoind transactions via RPC.
2023-04-10 08:33:41.788 [ERR] LTND: unable to create chain control: unable to create wallet: address manager is watching-only
2023-04-10 08:33:41.789 [ERR] LTND: Shutting down because error in main method: error loading chain control: unable to create chain control: unable to create wallet: address manager is watching-only
2023-04-10 08:33:41.789 [INF] LTND: Shutdown complete

error loading chain control: unable to create chain control: unable to create wallet: address manager is watching-only
```
---
We got stuck here, any suggestions? Thanks in advance

**Comment by Roasbeef** [comment]
Thanks for the extra information! 

I went to repro, fixed [a blocking bug](https://github.com/lightningnetwork/lnd/pull/7588) and was able to properly initialize a new hot/old node set up as described in the docs above. 

Here're all my commands with in line config arguments so it can easily be copy/pasted to reproduce: 
```

(start hot node)

./lnd-debug --bitcoin.active --nolisten --nobootstrap --rpclisten=localhost:10017 --lnddir=test_lnd --debuglevel=debug --bitcoin.simnet --bitcoin.node=nochainbackend

(init it)

lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd create

(make the accounts json)

lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd wallet accounts list > accounts-signer.json

(generate the custom macaroon) 

lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd bakemacaroon --save_to signer.custom.macaroon message:write signer:generate address:read onchain:write

(start the cold node) 

 ./lnd-debug --bitcoin.active --bitcoin.simnet --btcd.rpcuser=kek --btcd.rpcpass=kek --listen=localhost:10020 --rpclisten=localhost:10018 --lnddir=test_lnd2 --debuglevel=debug --nobootstrap --debuglevel=trace --profile=9094 --restlisten=localhost:8084 --minchansize=30000 --accept-amp --debuglevel=BTCN=trace --remotesigner.rpchost=localhost:10017 --remotesigner.tlscertpath=test_lnd/tls.cert --remotesigner.macaroonpath=signer.custom.macaroon --remotesigner.enable

(create it) 

 lncli --network=simnet --rpcserver=localhost:10018 --lnddir=test_lnd2 createwatchonly accounts-signer.json

```

Start up logs to show it succeeded: 
```
6 2023-04-10 12:10:01.902 [INF] LNWL: Opened wallet
  7 2023-04-10 12:10:05.383 [INF] LTND: Wallet recovery mode enabled with address lookahead of 2500 addresses
  8 2023-04-10 12:10:05.554 [INF] CHRE: Primary chain is set to: bitcoin
  9 2023-04-10 12:10:05.692 [INF] CHRE: LightningWallet opened
 10 2023-04-10 12:10:05.735 [INF] HSWC: Cleaning circuits from disk for closed channels
 11 2023-04-10 12:10:05.735 [INF] HSWC: Finished cleaning: no closed channels found, no actions taken.
 12 2023-04-10 12:10:05.735 [INF] HSWC: Restoring in-memory circuit state from disk
 13 2023-04-10 12:10:05.746 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
 14 2023-04-10 12:10:05.758 [INF] LNWL: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_wi    ndow=2500
 15 2023-04-10 12:10:05.763 [INF] LNWL: Seed birthday surpassed, starting recovery of wallet from height=1 hash    =0692760ed1bb79edf5c7df07fd1e622245a7df39b42d0ed351cd556f195e0984 with recovery-window=2500
 16 2023-04-10 12:10:05.801 [INF] SWPR: Migrating UTXO nursery finalized TXIDs
 17 2023-04-10 12:10:05.811 [INF] LTND: Channel backup proxy channel notifier starting
 18 2023-04-10 12:10:05.811 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0    .600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
 19 2023-04-10 12:10:05.812 [INF] WLKT: Baking macaroons for WalletKit RPC Server at: test_lnd2/data/chain/bitc
    oin/simnet/walletkit.macaroon
 20 2023-04-10 12:10:05.824 [INF] IRPC: Baking macaroons for invoices RPC Server at: test_lnd2/data/chain/bitco    in/simnet/invoices.macaroon
 21 2023-04-10 12:10:05.834 [INF] SGNR: Making macaroons for Signer RPC Server at: test_lnd2/data/chain/bitcoin    /simnet/signer.macaroon
 22 2023-04-10 12:10:05.858 [INF] RRPC: Making macaroons for Router RPC Server at: test_lnd2/data/chain/bitcoin    /simnet/router.macaroon
 23 2023-04-10 12:10:05.869 [INF] NTFR: Baking macaroons for ChainNotifier RPC Server at: test_lnd2/data/chain/    bitcoin/simnet/chainnotifier.macaroon
 24 2023-04-10 12:10:05.881 [INF] LTND: We're not running within systemd or the service type is not 'notify'
 25 2023-04-10 12:10:05.881 [INF] LTND: Waiting for chain backend to finish sync, start_height=3181
 26 2023-04-10 12:10:06.194 [INF] LNWL: Scanning 2000 blocks for recoverable addresses
```

**Comment by Roasbeef** [comment]
Are you starting with a _clean_ slate each time you attempt to repro?

**Comment by Roasbeef** [comment]
> wallet-unlock-password-file=/data/wallet-password
> wallet-unlock-allow-create=true

If you remove these lines, then try again (you'll need to manually unlock), do things work?

**Comment by guggero** [comment]
I will update the docs around this, since this requirement was added for Loop/Pool support after the initial docs were written.

**Comment by Jaccccc8** [comment]
https://github.com/lightningnetwork/lnd/blob/v0.15.5-beta/lnrpc/walletrpc/walletkit.proto#L885

https://github.com/bottlepay/lndsigner/blob/master/walletkit_server.go#L82

these 2 codes do not comply with each other, someone can advise ?

**Comment by Jaccccc8** [comment]
https://github.com/lightningnetwork/lnd/blob/v0.15.5-beta/lnrpc/signrpc/signer.proto#L390

https://github.com/bottlepay/lndsigner/blob/master/proto/signer.proto#L77

these 2 codes do not comply with each other either.
the Lnd node reported error when startup: error loading chain control: unable to create RPC remote signing wallet error connecting to the remote signing node through RPC: unable to connect to RPC server: context deadline exceeded

i wrote a grpc client using bottlepay proto connecting to bottlepay grpc server, there's no such error.

**Comment by guggero** [comment]
That seems to be a version issue. The `SignedInputs` field was added in 0.16.0. But gRPC _should_ be backward compatible and not fail with an error and just ignore the fields.
See https://github.com/lightningnetwork/lnd/blob/v0.16.0-beta/lnrpc/walletrpc/walletkit.proto#L1137.

**Comment by Jaccccc8** [comment]
> That seems to be a version issue. The `SignedInputs` field was added in 0.16.0. But gRPC _should_ be backward compatible and not fail with an error and just ignore the fields. See https://github.com/lightningnetwork/lnd/blob/v0.16.0-beta/lnrpc/walletrpc/walletkit.proto#L1137.

my own local grpc client is ok to access my local bottlepay gpc server,
could you advise what could cause "connecting to the remote signing node through RPC: unable to connect to RPC server: context deadline exceeded" in Lnd node, and calling what rpc.
Lnd startup command is :

`./lnd --bitcoin.active --bitcoin.mainnet --bitcoin.node=bitcoind --bitcoind.rpcuser=depositqa --bitcoind.rpcpass=depositqa --bitcoind.rpchost=10.xx --bitcoind.rpcpolling --bitcoind.blockpollinginterval=1m --bitcoind.txpollinginterval=30s --lnddir=test_lnd2 --remotesigner.rpchost=10.yyy:10021 --remotesigner.tlscertpath=test_lnd2/tls.cert --remotesigner.macaroonpath=any.macaroon --remotesigner.enable --debuglevel=LTND=trace --remotesigner.timeout=10s --debuglevel=trace`

**Comment by guggero** [comment]
Could be a firewall or connection issue? The error seems to come from the initial connection establishment in the RPC key ring: https://github.com/lightningnetwork/lnd/blob/4da26fb65a669fbee68fa36e60259a8da8ef6d3b/lnwallet/rpcwallet/rpcwallet.go#L87

Can you confirm that you can connect to the remote signer directly? For example with `openssl s_client -connect 10.yyy:10021`?

**Comment by johnsonco** [comment]
$ openssl s_client -connect 10.yyy:10021
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 O = lnd autogenerated cert, CN = lightning-watch-only
verify error:num=18:self signed certificate
verify return:1
depth=0 O = lnd autogenerated cert, CN = lightning-watch-only
verify return:1
---
Certificate chain

---
Looks ok though, bit weird

**Comment by guggero** [comment]
So `10.yyy:10021` is the bottlepay gRPC server running on the same host? Ah, I think the issue is: `--remotesigner.tlscertpath=test_lnd2/tls.cert`. That needs to be the certificate of the remote signer, not the watch-only node itself. The same with the macaroon.

**Comment by johnsonco** [comment]
Ok noted will try. Thanks!

**Comment by johnsonco** [comment]
> Thanks for the extra information!
> 
> I went to repro, fixed [a blocking bug](https://github.com/lightningnetwork/lnd/pull/7588) and was able to properly initialize a new hot/old node set up as described in the docs above.
> 
> Here're all my commands with in line config arguments so it can easily be copy/pasted to reproduce:
> 
> ```
> 
> (start hot node)
> 
> ./lnd-debug --bitcoin.active --nolisten --nobootstrap --rpclisten=localhost:10017 --lnddir=test_lnd --debuglevel=debug --bitcoin.simnet --bitcoin.node=nochainbackend
> 
> (init it)
> 
> lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd create
> 
> (make the accounts json)
> 
> lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd wallet accounts list > accounts-signer.json
> 
> (generate the custom macaroon) 
> 
> lncli --network=simnet --rpcserver=localhost:10017 --lnddir=test_lnd bakemacaroon --save_to signer.custom.macaroon message:write signer:generate address:read onchain:write
> 
> (start the cold node) 
> 
>  ./lnd-debug --bitcoin.active --bitcoin.simnet --btcd.rpcuser=kek --btcd.rpcpass=kek --listen=localhost:10020 --rpclisten=localhost:10018 --lnddir=test_lnd2 --debuglevel=debug --nobootstrap --debuglevel=trace --profile=9094 --restlisten=localhost:8084 --minchansize=30000 --accept-amp --debuglevel=BTCN=trace --remotesigner.rpchost=localhost:10017 --remotesigner.tlscertpath=test_lnd/tls.cert --remotesigner.macaroonpath=signer.custom.macaroon --remotesigner.enable
> 
> (create it) 
> 
>  lncli --network=simnet --rpcserver=localhost:10018 --lnddir=test_lnd2 createwatchonly accounts-signer.json
> ```
> 
> Start up logs to show it succeeded:
> 
> ```
> 6 2023-04-10 12:10:01.902 [INF] LNWL: Opened wallet
>   7 2023-04-10 12:10:05.383 [INF] LTND: Wallet recovery mode enabled with address lookahead of 2500 addresses
>   8 2023-04-10 12:10:05.554 [INF] CHRE: Primary chain is set to: bitcoin
>   9 2023-04-10 12:10:05.692 [INF] CHRE: LightningWallet opened
>  10 2023-04-10 12:10:05.735 [INF] HSWC: Cleaning circuits from disk for closed channels
>  11 2023-04-10 12:10:05.735 [INF] HSWC: Finished cleaning: no closed channels found, no actions taken.
>  12 2023-04-10 12:10:05.735 [INF] HSWC: Restoring in-memory circuit state from disk
>  13 2023-04-10 12:10:05.746 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
>  14 2023-04-10 12:10:05.758 [INF] LNWL: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_wi    ndow=2500
>  15 2023-04-10 12:10:05.763 [INF] LNWL: Seed birthday surpassed, starting recovery of wallet from height=1 hash    =0692760ed1bb79edf5c7df07fd1e622245a7df39b42d0ed351cd556f195e0984 with recovery-window=2500
>  16 2023-04-10 12:10:05.801 [INF] SWPR: Migrating UTXO nursery finalized TXIDs
>  17 2023-04-10 12:10:05.811 [INF] LTND: Channel backup proxy channel notifier starting
>  18 2023-04-10 12:10:05.811 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0    .600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
>  19 2023-04-10 12:10:05.812 [INF] WLKT: Baking macaroons for WalletKit RPC Server at: test_lnd2/data/chain/bitc
>     oin/simnet/walletkit.macaroon
>  20 2023-04-10 12:10:05.824 [INF] IRPC: Baking macaroons for invoices RPC Server at: test_lnd2/data/chain/bitco    in/simnet/invoices.macaroon
>  21 2023-04-10 12:10:05.834 [INF] SGNR: Making macaroons for Signer RPC Server at: test_lnd2/data/chain/bitcoin    /simnet/signer.macaroon
>  22 2023-04-10 12:10:05.858 [INF] RRPC: Making macaroons for Router RPC Server at: test_lnd2/data/chain/bitcoin    /simnet/router.macaroon
>  23 2023-04-10 12:10:05.869 [INF] NTFR: Baking macaroons for ChainNotifier RPC Server at: test_lnd2/data/chain/    bitcoin/simnet/chainnotifier.macaroon
>  24 2023-04-10 12:10:05.881 [INF] LTND: We're not running within systemd or the service type is not 'notify'
>  25 2023-04-10 12:10:05.881 [INF] LTND: Waiting for chain backend to finish sync, start_height=3181
>  26 2023-04-10 12:10:06.194 [INF] LNWL: Scanning 2000 blocks for recoverable addresses
> ```

Also thank you for the detailed steps! We have resolved the issue, appreciated!

**Comment by guggero** [comment]
Cool, happy to hear :tada:

**Comment by 0x3f97** [comment]
`lncli --network=simnet --rpcserver=localhost:10019 --lnddir=/home/ec2-user/remote-sign-mode/nodes/lnd-signer wallet accounts list > accounts-signer.json
No help topic for 'wallet'`

Why can't I export public key information?

**Comment by 0x3f97** [comment]
```bash
lncli --network=simnet --rpcserver=localhost:10019 --lnddir=/home/ec2-user/remote-sign-mode/nodes/lnd-signer wallet accounts list > accounts-signer.json
No help topic for 'wallet'
```

> `lncli --network=simnet --rpcserver=localhost:10019 --lnddir=/home/ec2-user/remote-sign-mode/nodes/lnd-signer wallet accounts list > accounts-signer.json No help topic for 'wallet'`
> 
> Why can't I export public key information?

**Comment by guggero** [comment]
Use `make release-install` to compile the correct binary. You are missing the `walletrpc` build tag.
