### ISSUE TITLE
walletbalance shows all funds as unconfirmed after 100+ confirmations

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#757]
I'm running 65d6d77ef409741c7ad8562cb9781dd5894a5117 (Feb 11) on Testnet

All funds show up as unconfirmed:

```
$ lncli walletbalance
{
    "total_balance": "618214348",
    "confirmed_balance": "0",
    "unconfirmed_balance": "618214348"
}
```
The node only had the transaction to fund the wallet:

https://www.blocktrail.com/tBTC/tx/66ff738113cc0c721c318968a0cb19fd901aadab830ce64ba11482ab6c3763aa

```
$ lncli listchaintxns
{
    "transactions": [
        {
            "tx_hash": "66ff738113cc0c721c318968a0cb19fd901aadab830ce64ba11482a
b6c3763aa",
            "amount": "635000000",
            "num_confirmations": 109,
            "block_hash": "000000000000072b61aac34a03d7fd7e90232e7717f67a72fc15ac945fe0b4ce",
            "block_height": 1281477,
            "time_stamp": "1518400102",
            "total_fees": "0",
            "dest_addresses": [
                "tb1qtp2xqsnw2xgdxm77ty8d2cs0lq04v4thnemedc",
                "2My1bLaY3MKxaEkwgXzjxENo9j6zeVuwT9Y"
            ]
        }
    ]
}

$ lncli channelbalance
{
    "balance": "0"
}

$ lncli listchannels
{
    "channels": [
    ]
}
```

**Comment by Roasbeef** [comment]
Is your node fully synced? Did you have any pending channels? If you have a channel in limbo, it may be there for a bit as right now, there's a lack of miners that are segwit enabled, so things may take some time to confirm.

**Comment by alevchuk** [comment]
It got confirmed. Maybe btcd was out of date.

Not sure how to check for pending channels. `lncli listchannels` as I posted was empty.
