### ISSUE TITLE
Unable to create a package  [Makefile:54: build-stayrtr] Error 2

### ISSUE THREAD

**Issue by usmanmehr** [lightningnetwork/lnd#7570]
Hi 

Environment RHEL 8.7
go go1.18.10

docker-compose -f docker-compose-pkg.yml up
 exits with this error

docker-compose -f docker-compose-pkg.yml up
Starting stayrtr-master_packager_1 ... done
Attaching to stayrtr-master_packager_1
packager_1  | fatal: not a git repository (or any parent up to mount point /)
packager_1  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
packager_1  | mkdir -p dist/
packager_1  | go build -trimpath -ldflags '-X main.version= -X main.buildinfos=(2023-04-04T15:26:59+0000)' -o dist/stayrtr--linux-x86_64 cmd/stayrtr/stayrtr.go
packager_1  | # golang.org/x/crypto/ssh
packager_1  | /root/go/pkg/mod/golang.org/x/crypto@v0.6.0/ssh/cipher.go:499:13: undefined: io.Discard
packager_1  | /root/go/pkg/mod/golang.org/x/crypto@v0.6.0/ssh/session.go:508:14: undefined: io.Discard
packager_1  | /root/go/pkg/mod/golang.org/x/crypto@v0.6.0/ssh/session.go:521:14: undefined: io.Discard
packager_1  | note: module requires Go 1.17
packager_1  | # golang.org/x/sys/unix
packager_1  | /root/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
packager_1  | /root/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_linux.go:2271:9: undefined: unsafe.Slice
packager_1  | /root/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
packager_1  | /root/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
packager_1  | note: module requires Go 1.17
packager_1  | # github.com/bgp/stayrtr/utils
packager_1  | utils/utils.go:167:15: undefined: io.ReadAll
packager_1  | note: module requires Go 1.17
packager_1  | make: *** [Makefile:54: build-stayrtr] Error 2
stayrtr-master_packager_1 exited with code 2

I have tried running "**go clean -modcache**" Any help in resolving this issue is appreciated

Thanks
Usman

**Comment by positiveblue** [comment]
The go version of your host is `go 1.18.10` but what is the version used to build the package (the one used in `docker-compose-pkg.yml`)

Some of the modules require a minimum version of Go because they use things that were not part of the std lib, runtime etc before. `unsafe.Slice` was introduced in v0.17.0, you may be using a version older than that one.

Also, what version of LND are you building? It is possible that you need to bump your compiler to `v0.19.x`

**Comment by Roasbeef** [comment]
Looks like you need to reinstall Go.
