### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by papercheck** [lightningnetwork/lnd#7571]
### Background

Upgraded to lnd-v0.16.0

### Your environment

* version of `lnd`: v0.16.0
* which operating system (`uname -a` on *Nix): 5.15.0-67-generic #74~20.04.1-Ubuntu
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v24.0.1 
* any other relevant environment details

### Steps to reproduce
sudo systemctl start lnd.service

### Expected behaviour

lnd should start normally

### Actual behaviour

unknown option: routerrpc.apriorihopprob
unknown option: routerrpc.aprioriweight
unknown option: aprioripenaltyhalflife

To get lnd to run, I had to comment these options out of lnd.conf under the [routerrpc] section.

I am following: [https://docs.lightning.engineering/lightning-network-tools/lnd/optimal-configuration-of-a-routing-node#routerrpc](https://docs.lightning.engineering/lightning-network-tools/lnd/optimal-configuration-of-a-routing-node#routerrpc)

**Comment by saubyk** [comment]
Hi @papercheck please update your config settings to 
routerrpc.apriori.hopprob
routerrpc.apriori.weight
routerrpc.aprioripenalty.halflife

These updated config variables are available in the `sample-lnd.conf`
https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf

**Comment by saubyk** [comment]
Working on getting the documentation updated, thanks for pointing this out

**Comment by papercheck** [comment]
Thank you @saubyk! I had initially commented out the option, but after adding your suggestions, I was able to get lnd-v0.16.0 to run successfully.

**Comment by saubyk** [comment]
closing this issue now, as the document has been updated. Thanks
