### ISSUE TITLE
Unrestrict config parsing to allow private ip addresses with "--no-macaroons" option

### ISSUE THREAD

**Issue by ssokolenko** [lightningnetwork/lnd#758]
The commit [#e953c6a](https://github.com/lightningnetwork/lnd/commit/e953c6abcf564e77a8a538e37ef5ddd28b38de9d) makes it impossible to use `--no-macaroons` option with `--rpclisten=<address>` and `--restlisten=<address>` assigned to addresses other than `localhost` or `127.0.0.1` which is good for security, but it is very inconvenient if `rpclisten` and/or `restlisten` are assigned to private network addresses, e.g. if lnd and rpc client are running in two docker containers connected via private network.

The simplest solution would be to white-list the reserved ip-ranges for private networks [as defined by IANA](https://en.wikipedia.org/wiki/Private_network), but this is bad option since those addresses may be bound to public network.

The best option as I see it is to define a config setting, e.g. `--trusted-subnet=<CIDR>` and allow less stricter security for addresses in this range(s).

P.S. I'd like to introduce PR, but due to my limited proficiency in GO I can only highlight the problem :-)

**Comment by dabura667** [comment]
NACK

imo `--no-macaroons` as an option is a mistake... and should be disallowed for mainnet deployment.

**Comment by ssokolenko** [comment]
@dabura667 There is nothing wrong with `--no-macaroons` as long as your lnd RPC service is not accessible from public network.

**Comment by Roasbeef** [comment]
I agree with @dabura667 . `no-macaroons` was only added for testing infrastructure to make it easier. We *will not* allow users to run on public interfaces w/o authentication. 

> but it is very inconvenient if rpclisten and/or restlisten are assigned to private network addresses, e.g. if lnd and rpc client are running in two docker containers connected via private network.
I don't see what's so difficult about this? Your infra should just fetch the macaroons accordingly.

**Comment by ssokolenko** [comment]
>> I don't see what's so difficult about this? Your infra should just fetch the macaroons accordingly.

@Roasbeef thanks for clarifying the future of `no-macaroons` option.

Well, I agree, it's not difficult, but this is an extra work which is merely needed in docker based setups where RPC network is not exposed to the public; gRPC with SSL/TLS + private network is already enough in this case.

Anyways, if it's planned to remove `mo-mcaroons`, this issue also makes no sense, closing it.
