### ISSUE TITLE
[bug]: batchopenchannel return the change on a P2WPKH address instead of P2TR

### ISSUE THREAD

**Issue by bota87** [lightningnetwork/lnd#7601]
Since 0.15.1 (https://github.com/lightningnetwork/lnd/pull/6810) for the change on opening transaction it's used a taproot address but that's not the behavior on batch opening

**Comment by ziggie1984** [comment]
cc @Torakushi I think you forgot to add the ability to add the change_scope for the batch_channel_openings command, I think we could also set the default change_scope for batch_channel_openings to p2tr?

**Comment by Torakushi** [comment]
Right! I don't think we need to make it configurable. only defaulting to P2TR should be enough. what do you think?

**Comment by ziggie1984** [comment]
makes sense let's default to P2TR, should be a quick change do you wanna do it (I can do it too if you have no time)?

**Comment by Torakushi** [comment]
I will do it tomorrow! should be straight forward
