### ISSUE TITLE
[bug]: v0.16.1-beta.rc1 - version mismatch

### ISSUE THREAD

**Issue by blckbx** [lightningnetwork/lnd#7620]
### Background

Upgrading from `v0.16.0-beta` to `v0.16.1-beta.rc1`, noticed a version mismatch in both lnd / lncli binaries:

```sh
$ lncli --version
lncli version 0.16.0-beta.rc3 commit=v0.16.1-beta.rc1

$ lnd --version
lnd version 0.16.0-beta.rc3 commit=v0.16.1-beta.rc1
```

### Your environment

* version of `lnd`: v0.16.1-beta.rc1
* which operating system (`uname -a` on *Nix): Linux node 5.15.0-69-generic 76-Ubuntu
* version of `btcd`, `bitcoind`, or other backend: bitcoind v 24.0.1

### Steps to reproduce

- build LND from source by checking out v0.16.1-beta.rc1
- run `~/go/bin/lncli --version`
- run `~/go/bin/lnd --version`

### Expected behaviour

```sh
$ lncli --version
lncli version 0.16.1-beta.rc1 commit=v0.16.1-beta.rc1

$ lnd --version
lnd version 0.16.1-beta.rc1 commit=v0.16.1-beta.rc1
```

### Actual behaviour

```sh
$ lncli --version
lncli version 0.16.0-beta.rc3 commit=v0.16.1-beta.rc1

$ lnd --version
lnd version 0.16.0-beta.rc3 commit=v0.16.1-beta.rc1
```

**Comment by guggero** [comment]
Thanks for the report. It looks like we forgot to bump the version in https://github.com/lightningnetwork/lnd/pull/7611. We'll fix that for RC2.

**Comment by blckbx** [comment]
Fixed on rc3.
