### ISSUE TITLE
Update golang version in lnrpc Dockerfile

### ISSUE THREAD

**Issue by MG-ng** [lightningnetwork/lnd#7629]
I think from the security and code quality standpoint the following line: 
golang:1.19.2-buster 

should be updated to: 
golang:1.20.3-bullseye 

in 
https://github.com/lightningnetwork/lnd/blob/588a7eb9caf4c24c18088c3b7ae57617770c5614/lnrpc/Dockerfile#L1 

But I haven't tested it yet. It would be nice if you could take a look at that.

**Comment by guggero** [comment]
The `[lnd/lnrpc/Dockerfile](https://github.com/lightningnetwork/lnd/blob/588a7eb9caf4c24c18088c3b7ae57617770c5614/lnrpc/Dockerfile#L1)` file is only used to build the gRPC stubs. The end result should be completely independent from the Golang version used. But I agree it would be nice to keep it up to date with all our other `Dockerfile`s.
