### ISSUE TITLE
Internal wallet doesn't recognize transaction replacement

### ISSUE THREAD

**Issue by veqtrus** [lightningnetwork/lnd#763]
After using RBF lnd doesn't remove the conflicting transaction even after the replacement has been confirmed. The conflicting transaction remains counted towards the unconfirmed balance.

**Comment by Roasbeef** [comment]
You mean the case where a transaction that pays to `lnd`'s internal wallet is RBF'd?

**Comment by veqtrus** [comment]
@Roasbeef yes
