### ISSUE TITLE
[feature]: Add custom TLV fields to HTLC interceptor

### ISSUE THREAD

**Issue by carlaKC** [lightningnetwork/lnd#7650]
**Describe the solution you'd like**
Add the ability to return custom range TLVs from the `HTLCInterceptor` API.

LND's `HLTCInterceptor` API is a powerful tool for folks looking to implement custom code on top on LND. Upgrading its [reponses](https://lightning.engineering/api-docs/api/lnd/router/htlc-interceptor#routerrpcforwardhtlcinterceptresponse) to include custom records increases the flexibility of custom features that can be built with it.

**Additional context**
As described in #7297, this `ExtraData` will not persisted across restarts so there's a possibility that it is dropped. I think the feature is still useful with some lack of reliability (eg, if you're experimenting with odd features your peers may ignore them anyway), and once `update_add_htlc` TLVs are persisted then this issue is resolved.

**Comment by carlaKC** [comment]
Will eventually pick this up myself, but opening now in case anybody's eager to give it a try!

**Comment by guggero** [comment]
Can this be closed now with the latest changes to the HTLC interceptor?

**Comment by carlaKC** [comment]
> Can this be closed now with the latest changes to the HTLC interceptor?

Yes 🎉

**Comment by Gary19751957** [comment]
Do not block any of my assets this has been reported to the fbi

Gary Wayne Rollins
