### ISSUE TITLE
[bug]: Pending Force close channels never closed..

### ISSUE THREAD

**Issue by tagcoin** [lightningnetwork/lnd#7660]
LND 0.16.1 on btcpayserver

Had these 2 channels stuck for over a month and not quite sure what to do with them. TX was confirmed a month ago

Not quite sure what to do to get rid of them...LND node has been restarted a  number of times over last couple of weeks

There is 15 million sats in 2 transactions...pretty sure that has gone to my onchain wallet, but just checking here...I can run abandon channel command...

Any ideas?

    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "039b3cab2a452a0ec921c417009817a8ae871b2098454078dd439e5f328a1108e6",
                "channel_point": "06a1325f186b2e89d6bc7b5d3c10d1fb48b74d4fb3bf2116066b7effeb671d42:1",
                "capacity": "5000000",
                "local_balance": "53123",
                "remote_balance": "4943041",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "closing_txid": "f8456d3c3a05792ca16d9d25e28229445f49579dd54c67be9888ee35f4f93e8c",
            "limbo_balance": "463",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "330",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "463",
                    "outpoint": "58eefc76eea1c5ff516a6d280741b5d2aa1ddd1c64fe901052ddbb91ff94ff11:0",
                    "maturity_height": 782767,
                    "blocks_til_maturity": -5001,
                    "stage": 1
                }
            ],
            "anchor": "RECOVERED"
        },
        {
            "channel": {
                "remote_node_pub": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
                "channel_point": "68606f14aa5bd3415054f45fb5e5bc59e0ed399d4178fb85da764f0491ae9c51:1",
                "capacity": "10000000",
                "local_balance": "9540531",
                "remote_balance": "454565",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "closing_txid": "2806159a5c9d4efb78c8e43d652637224bb8d59cea6b0f6cc6c8699fac1c3930",
            "limbo_balance": "1003",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "330",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "1003",
                    "outpoint": "197fca683520be7cc5e5edecb366c9823ace809e83a3132f122809f58b98f0b0:0",
                    "maturity_height": 787189,
                    "blocks_til_maturity": -579,
                    "stage": 2
                }
            ],
            "anchor": "RECOVERED"
        }
    ],

**Comment by positiveblue** [comment]
In this case `abandonchannel` is not recommended, given that the channel already confirmed.

The channels appear in `pending_force_closing_channels` because "technically" the force close did not finish yet. They have htcls that still need to be resolved on chain. The node did not spend the funds of the htlcs yet because the amounts are too small which make it uneconomical (you would spend more on fees than the amount you would claim). 

As you said that does not affect to other outputs in those transactions that have already been spent without any problem. 

When fees go down and make it makes sense to sweep those funds your node will do it.
