### ISSUE TITLE
[bug]: Force closure of channels while 'waiting close' gives output txid, but does not effect force close - and channel status becomes 'borked'

### ISSUE THREAD

**Issue by michaelg-au** [lightningnetwork/lnd#7661]
### Background

I closed a lot of channels in recent days - but for some of them (eight) I left the confirmation fee too low. I'm hoping the mempool will clear in the coming week and they will confirm.

Is there a way to speed up the closure process - or even force close them? I tried to force close two of them but it hasn't worked - they remain 'waiting close'. Also - running 'lncli pendingchannels' shows that those two channels now have a 'ChanStatusBorked' status flag. Also tried RBF using 'wallet bumpfee' command on one of the 'anchor' channels - but that also doesn't seem to work.

All in all - keen to understand if I need to act proactively at this stage - or just wait. If I wait and they don't confirm - is it just a matter of retrying force close in a few weeks?

### Your environment

Closed channels on LND 0.15.4. Upgraded to LND 0.16.2 in recent days.

### Steps to reproduce

Generally - attempt to cooperatively close channels with confirmation fee that is too low.
In relation to 'borked' channels - attempt cooperative close with confirmation fee that is too low. Then try to force close channel almost immediately (within 24 hours) of cooperative attempt.

### Expected behaviour

Generally - unsure about result of fee being too low.
In relation to 'borked' channels - expected force close to have been successful at any time, even when cooperative 'waiting close'.

### Actual behaviour

Generally - unsure about result of fee being too low.
In relation to 'borked' channels - when I ran the force close channel command - a tx id was output, giving me the impression that the force close was successful. However, note that this tx is not discoverable in bitcoin explorers and did not move my channel out of the 'waiting close' list to 'Pending force closing'.

**Comment by michaelg-au** [comment]
The command I used: 
lncli wallet bumpfee --sat_per_vbyte 30 _txid_:1

with txid being the original closing transaction. I note that it appeared to work the first time I tried with the child transaction confirming on the same block as parent - and funds successfully claimed to wallet. I then tried two more times on two other original closure attempts - with the child (and parent) not confirming. Based on my reading today, that could be just due to my child fee not being high enough to incentive confirmation by miners... I'll assume that is the case for now while I keep observing.

As for the two channels which I attempted a force close. I note that 'pending channels' output shows a new 'closing_txid' which I understand would be the force close transaction. However, this does not appear in web bitcoin explorers. I also note that my UTXO listing only shows the original cooperative close attemps. At this stage, I presume that I still wait for the cooperative close (if fees fall) - but for some reason my force close attempts are just not going through - which, for clarity, **I would like to highlight as the main intent of this 'bug' report.**

**Comment by michaelg-au** [comment]
Ok - I think the 'bug' I reported is not with LND/Lightning - but with some fundamental points of my own understanding. For reference of anyone else in this situation - I understand the solution for my situation would simply be to use the `wallet bumpfee` command on all my waiting close transactions that I set too low a fee for. I had misunderstood that only 'anchor' channels as listed in `pendingchannels` could be bumped with CPFP. I now understand that this can occur for all closing transactions - anchor or static remote key. The relevance of anchor channels is that force close settlement transactions can be bumped (i.e. where the originally set commitment transaction chain fee is too low). 

In my situation - I have propagated eight cooperative close transactions which have been accepted by my peers - they are all that exists for now and can't be overridden by any force close transaction. The deal has been done - and my only recourse is to bump the fees - taking care to provide a high enough CPFP bump fee that will be accepted by miners. Understand that there is an algorithm to work out what CPFP fee is sufficient, but I'm not aware of how to do that yet - will try to learn. Also understand that this might eventually be added as a functionality to the LND code.

In relation to my two attempted force closes and the status of 'Chanborked' - I suspect that these transactions were created when I ran the force close command-line command - and note that they provided a new TXID - however, my observation is that the UXTOs still reference the original closing transactions and the 'new' force close TXID does not appear in bitcoin explorers (mempool). On this basis, I will assume these two force close commands have just been ignored and I am safe to run a `bumpfee` on these two channels as well. Will do this after I see how I go running bumpfee on the other six channels which I didn't mess around with.

On the basis of the above - I understand this Issue is not a true bug report and can be closed. Unless there is some residual learning/potential fix in relation to my force close attempts giving a TXID and adjusting the output of pendingchannels as borked and showing the new TXID which is discrepant to the UTXO showing in my wallet.

**Comment by michaelg-au** [comment]
My Issue is resolved - just needed to learn how to properly use the wallet `bumpfee` command that can be used on cooperative close TXIDs that have confirmation fee set too low. Also note that there is a wallet `bumpclosefee `command for bumping force close commitment transactions - noting that this is only available on 'anchor' channels which can be looked up with the `pendingclose `command.

**Comment by Raapop** [comment]
@michaelg-au hey, I seem to run into the same issue as you describe. You say you learned to properly use the bumpfee command. May I ask what worked for you? It doesn't seem to work for me, the bumpfee command does either nothing or give some text. The bumpclosefee says it will bump the fee but doesn't seem to anything (nothing changed when looking at the tx in the mempool)

**Comment by michaelg-au** [comment]
The fees are quite high now. When you bumpfee, you need to pretty much double the fee to cover the stuck transaction and your new child transaction. If you don't pay enough... They'll both be stuck until fees drop. Maybe share the transaction id if you like.

**Comment by Raapop** [comment]
thanks for the response. I've managed to do it on 2 of the 3 channel by now, not sure why it doesn't work on the last one. 

This one is stil waiting:

"waiting_close_channels":  [
        {
            "channel":  {
                "remote_node_pub":  "03df420127f61c40ddc9fa4f75f4df42dbec020ac791066e98b649893043a6ee4d",
                "channel_point":  "1e4e1dbe0171bdd02370072205ff2dac3b6aad7a53822398320f9eb88e64cfcb:1",
                "capacity":  "250000",
                "local_balance":  "242812",
                "remote_balance":  "4576",
                "local_chan_reserve_sat":  "2500",
                "remote_chan_reserve_sat":  "2500",
                "initiator":  "INITIATOR_REMOTE",
                "commitment_type":  "ANCHORS",
                "num_forwarding_packages":  "0",
                "chan_status_flags":  "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator",
                "private":  false,
                "memo":  ""
            },
            "limbo_balance":  "242812",
            "commitments":  {
                "local_txid":  "d4d6d90f704e361db33c9597653f30ef7a5fad69ad591035ea4a11e5dd4701fb",
                "remote_txid":  "6ec440e67eebd6e60910ec7ecaa9032be3b62675d46479a2c093ea96b665e4a0",
                "remote_pending_txid":  "",
                "local_commit_fee_sat":  "1951",
                "remote_commit_fee_sat":  "1951",
                "remote_pending_commit_fee_sat":  "0"
            },
            "closing_txid":  "d4d6d90f704e361db33c9597653f30ef7a5fad69ad591035ea4a11e5dd4701fb"
        }
    ]
}



---------

when i try the bumpclosefee command on the channelpoint it now says that it's bumping the fee, but noting happens. When I try the command now it returns nothing. Might it be that i don't have sats in the wallet to generate the bump transaction?

Btw, when i used the command when it worked, bumpclosefee 50v byte would generate a 109s/vb transaction to in total get a 50 s/vb transaction.

**Comment by michaelg-au** [comment]
It's been a while since I had this problem and since closed my lightning node. From memory, you need to use 'bumpfee', not 'bumpclosefee'. And you need to bump the closing transaction id: d4d6d90f704e361db33c9597653f30ef7a5fad69ad591035ea4a11e5dd4701fb.

Not the original transaction id you used to set up the channel (1e4e1dbe0171bdd02370072205ff2dac3b6aad7a53822398320f9eb88e64cfcb:1).

Looking in an explorer I see your closing transaction set at 7 sat/vb. Too low and that's why it's stuck. You need to bump with a (much) higher fee. If you want immediate confirmation, probably somewhere about 300 sat/vb looking at the mempool. (I.e. 150 sat/vb for the child and about the same for the parent as the 7 sat/vb doesn't pay for much).

**Comment by michaelg-au** [comment]
I'm working from memory. 1) I think remove the "txid" letters from your command. Look at the way the guy above did it. 2) add the channel point... I.e. 3f8eea8bbcfadf98a414411815ceebc845542c3aa0d8f15397dfd1289a3ecf22:2 OR txid:3f8eea8bbcfadf98a414411815ceebc845542c3aa0d8f15397dfd1289a3ecf22:3 depending on which output you control.

**Comment by Raapop** [comment]
I had to do a couple things. First i needed to force closes the channel. Your channel has no closing tx id, so try channelclose --force command (and then the channel point.

When there was a channel id, I had to make sure I had enough sats in the lnd wallet to pay for the bump and that my nodes mempool memory was large enough to be able to see the tx (not sure about this though, but my node couldn't find the closing tx since it was trowing out low fee transactions and only had succes when the fees dropped). 

I also only used the bumpclosefee command. And just like when force closing, use the channelpoint:index ( 9f77ac48b9904f4d13b5b004ef9c83fa2ffcf2a7288026d2a7337c5552ba7df7:1 )

**Comment by vmartrix** [comment]
Hello
After running
`sudo ~/umbrel/scripts/app compose lightning exec lnd lncli closechannel --force 9f77ac48b9904f4d13b5b004ef9c83fa2ffcf2a7288026d2a7337c5552ba7df7 1`

I get this error message:
`[lncli] rpc error: code = Unknown desc = cannot close channel with state: ChanStatusLocalDataLoss|ChanStatusRestored`

**Comment by Raapop** [comment]
Sorry familiar with this issue.

Perhaps there's an solution in this thread 

https://github.com/lightningnetwork/lnd/issues/6173

**Comment by podkilla** [comment]
I have the exact same problem.


~ ❯ docker exec lightning_lnd_1 lncli pendingchannels                                                                                                                                                                                                                 
```
{
    "total_limbo_balance": "1228612",
    "pending_open_channels": [],
    "pending_closing_channels": [],
    "pending_force_closing_channels": [],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "035d4267c0d340a8c8bb3394567553254709ba2188a3941f5f964339e3e644181c",
                "channel_point": "7782d63cb04cc00ccb097b01cb0350f49a593c2ce5d43af3a1d0b8e09688c62d:1",
                "capacity": "5000000",
                "local_balance": "1228612",
                "remote_balance": "3767917",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
                "private": false,
                "memo": ""
            },
            "limbo_balance": "1228612",
            "commitments": {
                "local_txid": "c103890c8dd771c8f527e6624f6da78654853ef34b016f8c9be9be964ad100b9",
                "remote_txid": "02a96827c5ad104f6a38542a80626a75c6f47a40d09bf669a0afe8bae280020b",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2810",
                "remote_commit_fee_sat": "2810",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": "c103890c8dd771c8f527e6624f6da78654853ef34b016f8c9be9be964ad100b9"
        }
    ]
}
```

trying to bump the fees gives me this

~ ❯ docker exec lightning_lnd_1 lncli wallet bumpclosefee --sat_per_vbyte 50  7782d63cb04cc00ccb097b01cb0350f49a593c2ce5d43af3a1d0b8e09688c62d:1                                                                                      
```
Bumping fee of c103890c8dd771c8f527e6624f6da78654853ef34b016f8c9be9be964ad100b9:1
Bumping fee of 02a96827c5ad104f6a38542a80626a75c6f47a40d09bf669a0afe8bae280020b:1
```

the output suggests that it might have worked, but it did not.
