### ISSUE TITLE
[bug]: Channels in WaitingClose for many months already

### ISSUE THREAD

**Issue by AgXCz** [lightningnetwork/lnd#7662]
### Background

I have two channels in the WaitingClose state for many months already. 
I am unable to get rid of them.

 "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "0306dc1dc707635e81c3cd90c60abc0b98009fc55d3ecb078b2704091cb7f1863c",
                "channel_point": "0cd21e4d15ec9b52a82dd48c267621c8af42922ff23fd68d15714dff715bd1f9:1",
                "capacity": "1000000",
                "local_balance": "996530",
                "remote_balance": "0",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
                "private": false
            },
            "limbo_balance": "996530",
            "commitments": {
                "local_txid": "646501adb403f81aafca85746c83e965473462db8920c345050eb943c16f9576",
                "remote_txid": "0f5f46eadbe9708c97a14397650ef5d3dfa77f3bd1dfdc375dbdeee60362ddbf",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2810",
                "remote_commit_fee_sat": "2810",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": "646501adb403f81aafca85746c83e965473462db8920c345050eb943c16f9576"
        },
        {
            "channel": {
                "remote_node_pub": "03c4c5c4d04e3f8dbf47d9ebdf20db6cd6d704b8f03f3e70797b21b76df3f1c73b",
                "channel_point": "bb8d441dcb57dd59ba2920f1d9a6380bfd7d08751f67e576951cb5f81fadfc3f:0",
                "capacity": "120000",
                "local_balance": "117834",
                "remote_balance": "0",
                "local_chan_reserve_sat": "1200",
                "remote_chan_reserve_sat": "1200",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
                "private": false
            },
            "limbo_balance": "117834",
            "commitments": {
                "local_txid": "c0b50b3324c6b0acfbe56edd295d02100c4e8a7914d67fd0799fd6af2bea3272",
                "remote_txid": "ee373b6d9f39b90188c8170844834ba64e38bf04777074a547828c39a845802c",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2166",
                "remote_commit_fee_sat": "2166",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": "c0b50b3324c6b0acfbe56edd295d02100c4e8a7914d67fd0799fd6af2bea3272"
        }
    ]

### Your environment

* version of `lnd` - 0.16.2-beta - but issue occurred already in some previous version
* which operating system (`uname -a` on *Nix) - Windows 10 PRO
* version of `btcd`, `bitcoind`, or other backend - Bitcoin Core verze v24.0.1

### Steps to reproduce

I am not sure what happened, probably there was some issue during the opening.
The opening transaction is not found in the blockchain and chaennels have never been opened.
Later I tried to force close them. Channels are still in this state.

### Expected behaviour

I would expect that after a certain time, it will disappear.
I tried to force-close it, but it is still there.

### Actual behaviour

It is listed as pending closing. I am unable to get rid of it.

**Comment by positiveblue** [comment]
It is possible that the txs were never propagated through the network/dropped from the mempool(s). 

In this case you won't be able to force close the channel because it was never open. You can use the `lncli abandonchannel` subcommand to make your node "forget" about these channels. 

*Disclaimer* : for anyone reading this in the future. The use of `abandonchannel` can lead to loss of funds. If the channel ever confirmed after using the command your node would not be able to close (recover) the funds. You need to be sure that the channel did not confirmed and if possible make sure that it would not be able to confirm in the future (spend the input utxos)

**Comment by AgXCz** [comment]
Thanks @positiveblue for your answer. 
Is it possible to get lnd for Windows but built in debug mode?
The standard version shows [lncli] rpc error: code = Unknown desc = AbandonChannel RPC call only available in dev builds

**Comment by guggero** [comment]
Try `lncli abandonchannel --help` and read the instructions carefully. No dev build needed.

**Comment by AgXCz** [comment]
Aha, perfect, thanks. I used lncli abandonchannel --i_know_what_i_am_doing
Those channels disappeared. Problem solved.
