### ISSUE TITLE
Channel force close stuck when min relay or mempool fee not met

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#7686]
This issue is related to #7512, but for channel force-close transactions specifically. The difference with the aforementioned issue is that commitment transactions may have been created at a time when the min mempool fee was lower still.

I did some testing on lnd v0.16.2-beta where I use a patch to force the commit tx fee to 253 sat/kw.
* Set bitcoin core min relay fee to 100 sat/b
* Alice and Bob open a channel
* Bob goes offline, Alice force-closes

As expected, the logs shows: `[ERR] CNCT: ChannelArbitrator(5dbde9dac766745bee8843be9fdff49eaef43b31f68962a04e1fbfdbc920cda9:0): unable to broadcast close tx: unmatched backend error: -26: min relay fee not met, 284 < 27900`

At this point `lncli pendingchannels` shows the channel, but it doesn't seem to get out of this again? Is it expected that a retry happens at some point automatically? I see that a restart of lnd does a retry though.

I thought that https://github.com/lightningnetwork/lnd/pull/7448 would take care of it, but after a minute (default timeout) of waiting, is doesn't seem that it does.

**Comment by joostjager** [comment]
Digging a little deeper, it seems that the rebroadcaster logs `[ERR] BTCN: Broadcast attempt failed: -26: min relay fee not met, 2810 < 27900` and then also doesn't store the tx for rebroadcast.

https://github.com/lightninglabs/neutrino/blob/9badd7f8a27f0c24e9ba8cc191d58e7899e5e47f/pushtx/broadcaster.go#L177

**Comment by bitromortac** [comment]
The fix seems to be to parse the error string and to save the transaction if we encounter `min relay fee not met`. I could take a look at this.

**Comment by joostjager** [comment]
Yes, and also the other one, min mempool fee not met.

**Comment by Roasbeef** [comment]
@bitromortac the current `IsBroadcastError` was created mainly for neutrino, and also back when bitcoind actually sent `reject` messages (they removed it, but `btcd` still sends them). What we want to do here is also expand it to check the set of JSON RPC error messages, which we observe here: https://github.com/btcsuite/btcwallet/blob/4383930e9c4c07dba5cf7444b0c08c47bd2be30a/wallet/wallet.go#L3655-L3795

After that, we can get rid of this hack: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/wallet.go#L476-L486

**Comment by bitromortac** [comment]
I reproduced your issue with `min relay fee not met` by setting `-minrelaytxfee=0.00100000` :+1:. Something I'm not 100% clear on is why you needed to patch lnd to use a lower ctx fee?

**Comment by joostjager** [comment]
Ah I think I wanted to be sure that the commit fee wouldn't exceed min relay tx fee. But on a test network that is indeed not going to happen anyway. No patching required.

**Comment by Roasbeef** [comment]
@saubyk #7726 doesn't fix this.
