### ISSUE TITLE
[bug]: In flight status for payment without HTLCs

### ISSUE THREAD

**Issue by dolcalmi** [lightningnetwork/lnd#7697]
### Background

`lncli trackpayment` returns `"status": "IN_FLIGHT"` for expired payment without HTLCs 

### Your environment

* version of `lnd`: 0.16.2-beta
* operating system: Linux
* version of `bitcoind`: v24.0.1

### Steps to reproduce

Seems to be a random error, in April happened 1 time https://github.com/alexbosworth/lightning/issues/133 (with 0.15 version) but this month has happened 3 times with 0.16.2

lncli response:
```
lncli trackpayment 23c16377d3f89...d4c722220afba41 --json
{
    "payment_hash": "23c16377d3f89...d4c722220afba41",
    "value": "378367",
    "creation_date": "1684160327",
    "fee": "0",
    "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
    "value_sat": "378367",
    "value_msat": "378367000",
    "payment_request": "",
    "status": "IN_FLIGHT",
    "fee_sat": "0",
    "fee_msat": "0",
    "creation_time_ns": "1684160327604024015",
    "htlcs": [
    ],
    "payment_index": "222457",
    "failure_reason": "FAILURE_REASON_NONE"
}
```

### Expected behaviour

Return failed if the payment has no HTLC

**Comment by hazrulnizam** [comment]
Similar to https://github.com/lightningnetwork/lnd/issues/6834?

**Comment by yyforyongyu** [comment]
Will be fixed by #7503

**Comment by leesalminen** [comment]
Just coming in that I am experiencing the same issue that @dolcalmi has reported here. We're running a very similar stack.

**Comment by Roasbeef** [comment]
Closing as https://github.com/lightningnetwork/lnd/pull/7503 was merged. Let me know if otherwise @yyforyongyu
