### ISSUE TITLE
Replace elkrem with shachain throughout wallet 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#77]
## Isssue 
Currently within the codebase, `elkrem` is used as a revocation tree to derive the revocation hashes we use during the commitment updates. In the current draft of the spec, `shachain` is used instead as it's a bit more efficient and is a bit more generalized. 

There's currently a `shachain` package within the project, however it is incomplete and doesn't have any tests .

## Steps to Completion 

- [ ] The `shachain` package within the project should be finalized. The implementation should be finished with tests exercising the important cases like derivation, tree folding (as leaves are exposed), and quickly deriving a particular state number. 
    * See the following section in the spec for details: https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#per-commitment-secret-requirements

- [ ] All usage of `elkrem` within the codebase should be replaced with usage of `shachain`
   * This includes all derivations, and the current storage within `channeldb`. 

- [ ] The `elkrem` package should be removed.

**Comment by AndrewSamokhvalov** [comment]
will take this one

**Comment by Roasbeef** [comment]
Fixed by #89
