### ISSUE TITLE
[bug]: Incoming HTLC can be failed although outgoing HTLC is still unresolved.

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7701]
## Description

So basically this refers to this #7683 but is an issue in itself .

And to state it beforehand, I find this unintended behavior useful.

We have the situation where with these high Mempool Fees its sometimes very likely that Offered HTLCs are not resolved in time leading to the Incoming HTLC needing to be resolved onchain. I kinda find this situation not productive regarding costs of FCs. I propose a config setting for the htlcswitch, so that noderunners can decided by themselves whether they want to accept the risk of funds in case the Offered HTLC is swept via the preimage after timeout (which is very unlikely and when this happens its basically a race to the bottom, both can RBF each other until almost no sats are earned, tho there might be the possibility to bin it so it depends). For Dust HTLCs we already do this as I learned from CryptoIQ

Something like 

--htlcswitch.FailIncomingHTLCIfOutgoingIsNotResolvedInTime

Analysis why we fail Incoming although Outgoing is still not Resolved when we Reconnect the Incoming Link:

Since LND 15.5 (I think) every Forward is checked for its timeout in the Interceptor Code. Now when we reconnect a link with an  Incoming HTLC being in the grace-period (timout + 13 blocks) we fail it back without checking the corresponding Offered HTLC status.

https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/interceptable_switch.go#L475

https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/interceptable_switch.go#L562

Logs from such a situation:

```
2023-05-15 10:53:58.060 [DBG] HSWC: Interception rejected because htlc expires too soon: circuit=(Chan ID=204:1:0, HTLC ID=3), height=216, incoming_timeout=333
2023-05-15 10:53:58.060 [DBG] HSWC: ChannelLink(3bb535672973053a3184cf77ced48583204c4252521221518c05e619fbcccd19:0): queueing removal of FAIL closed circuit: (Chan ID=204:1:0, HTLC ID=3)->(Chan ID=199:2:0, HTLC ID=0)
```

If we find consens how to design this behaviour I would like to tackle this.

**Comment by Crypt-iQ** [comment]
@joostjager I don't think this was intentional?

**Comment by joostjager** [comment]
If I remember correctly, this is intentional. Because if we'd forward, a new block event would cancel the incoming htlc anyway in https://github.com/lightningnetwork/lnd/blob/bdb41e58677836390f817b481fd784148f310571/htlcswitch/interceptable_switch.go#L293

**Comment by ziggie1984** [comment]
Hmm not sure, but this concerns HLTCs which are held in the queue, meaning the Intercepter Client did not react to this HTLC, normally it sends a message to `resume` so its not effected by the failing when a new block comes in.

**Comment by yyforyongyu** [comment]
I think we didn't consider the case that the outgoing htlc might be stuck in mempool that long.

>Something like
>
>--htlcswitch.FailIncomingHTLCIfOutgoingIsNotResolvedInTime

I think this should be a channel-specific config.

**Comment by ziggie1984** [comment]
> I think this should be a channel-specific config.

Yes thats even better I agree but comes with config overhead or? What do you think about ChannelType tho? For Anchor Channels Funds are lost anyways if the HTLC is not swept in time, meaning both parties can RBF the value basically to 0 (excluding FeePinning here), but for Static_Remote it's save to not cancel the Incoming because with the Preimage you can always attach higher fees than the one sweeping the timeout clause?

When going with channel-specific we need to always specify the outgoing channel I think or? Meaning that we allow to fail the incoming if we trust the outgoing peer, so a bit tricky imo

**Comment by Crypt-iQ** [comment]
> If I remember correctly, this is intentional. Because if we'd forward, a new block event would cancel the incoming htlc anyway in
> 
> https://github.com/lightningnetwork/lnd/blob/bdb41e58677836390f817b481fd784148f310571/htlcswitch/interceptable_switch.go#L293

In this example it seems that the HTLC has already hit the outgoing side and the incoming link is reconnecting? But to be fair, I haven't looked into the details to verify this.

**Comment by Crypt-iQ** [comment]
I looked into it and the current behavior seems fine. I don't think we need this issue open though. Adding more code to a pretty complicated part of the codebase is not the way forward IMO.

**Comment by ziggie1984** [comment]
Feel free to close if we wanna keep it the way it is now, maybe it's really better to keep the codebase not overcomplicated.
