### ISSUE TITLE
require bitcoind >= v24.0 or conditionally use `gettxspendingprevout`

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#7703]
The mempool issues should be solvable by using the `gettxspendingprevout` RPC so we don't have to scan the mempool at the `btcwallet` level. We could either conditionally call this if the bitcoind version is >= v24.0 or we could require people to upgrade their bitcoind versions.

**Comment by shaurya947** [comment]
Hi @Crypt-iQ I was hoping to learn more about the specific _mempool issues_ that you mentioned. Could you please offer a high-level explanation or link me to any other issues/docs that have some explanations? I would like to potentially attempt this once I can understand it better :pray:

**Comment by Crypt-iQ** [comment]
Hi @shaurya947 unfortunately I don't think this is suitable for newer contributors to attempt and we'll probably do this one internally

**Comment by yyforyongyu** [comment]
If we are upgrading bitcoind version, we can also make use of [`getblockfrompeer`](https://github.com/bitcoin/bitcoin/pull/20295/commits/dce8c4c38111556ca480aa0e63c46b71f66b508f) when running pruned bitcoins, and deprecate the custom logic introduced in `btcwallet.chain`.

**Comment by Crypt-iQ** [comment]
> If we are upgrading bitcoind version, we can also make use of [`getblockfrompeer`](https://github.com/bitcoin/bitcoin/pull/20295/commits/dce8c4c38111556ca480aa0e63c46b71f66b508f) when running pruned bitcoins, and deprecate the custom logic introduced in `btcwallet.chain`.

What do we do in `btcwallet.chain`? I think `getblockfrompeer` can fail

**Comment by Crypt-iQ** [comment]
> > What do we do in btcwallet.chain?
> 
> We use it [here](https://github.com/btcsuite/btcwallet/blob/master/chain/bitcoind_conn.go#L159). When running in pruned mode we'd fetch blocks from our peers when needed.
> 
> > I think getblockfrompeer can fail
> 
> Fail as the block cannot be found or the peer doesn't support it?

It should be fine to use, since we're copying what it does already. It uses regular block fetching under the hood

**Comment by Crypt-iQ** [comment]
PR https://github.com/btcsuite/btcwallet/pull/887

**Comment by Roasbeef** [comment]
https://github.com/btcsuite/btcwallet/pull/887 has been merged, so we can close this after we bump the `btcwallet` version in lnd.

**Comment by Crypt-iQ** [comment]
This should be fixed with https://github.com/lightningnetwork/lnd/pull/8019 since the batch PR will get merged after the already merged btcsuite/btcwallet#887
