### ISSUE TITLE
[troubleshooting]: opened a channel, the transaction doesn't exist in any mempool

### ISSUE THREAD

**Issue by anycolo** [lightningnetwork/lnd#7713]
I sent some funds with a low fee to the lnd wallet, then used the web interface "Ride the Lightning" to open a channel using the unconfirmed outputs + whatever was left in the lnd wallet. I can see the channel in pending opens, but if i lookup the transaction id in the block explorers, it doesn't exist. How can i fix this?

**Comment by saubyk** [comment]
Hi @anycolo, are your onchain funds confirmed now?

**Comment by saubyk** [comment]
Also, when you opened the channel with unconfirmed outputs, did you set a low fee again?

**Comment by anycolo** [comment]
No, and i don't think they ever will. It's already been 2 days. It's not available in any mempool website.

I used the target block confirmation and set to 6.

**Comment by saubyk** [comment]
@anycolo so, if the original funds transfer has been pushed out of the mempool, so any descending transactions (channel open) will also get pushed out, so your channel open will never go through. There is nothing really to "fix" here, other than ensuring that you should still have your funds on the wallet from where you funded LND onchain.

As for any of the onchain funds which you already had on your LND, you should still have those, as those have not been spent. You should be able to find them on the UTXOs tab of the RTL `On-Chain` page.

**Comment by anycolo** [comment]
The first transaction confirmed, eventually, but the second one wasn't probably accepted by any bitcoin node, because it doesn't appear in any block explorer. LND shows the channel as 'pending', and the corresponding transaction id is not found in any mempool. The on chain funds where the return funds should have been is has 0 transactions in all block explorers.

**Comment by saubyk** [comment]
Hi @anycolo may be you can share some screenshots and transaction Ids of the transactions you're referring to has the "first" and "second", so that we can understand the context better

**Comment by anycolo** [comment]
Can you give me your email address, so i can send the logs there?

**Comment by chostorg** [comment]
I think i have the same issue:
I have opened a channel with fixedfloat using an unspent output, and it shows as pending in the ThunderHub web UI, but when i click on the transaction id, it takes me to:
https://mempool.space/tx/89cac18fc6b2d20f5bdc03d48306729e6da64de6fd58c0759871f850ba2e0baf
This is the unconfirmed transaction which confirmed in the mean time:
https://mempool.space/tx/b392ed9c5ae1fa6c1dfa5f4f1013de8d3e9fed9e4e51ae9f9afc73b6878a815b

**Comment by saubyk** [comment]
> The second transaction was not accepted by the bitcoin daemon or it failed to broadcast for whatever reason. I think LND generated an invalid transaction, which is not accepted by the mempool, but in it's own database, lnd considers it valid.

You can reach out to me on the LND Slack, Twitter or Telegram. My username on all of these platforms is My2Sats

It's not possible for LND to generate an invalid transaction. At best what could've happened is, you've specified a low fee rate and as a result your transaction is getting rejected by the Bitcoin network. LND will keep trying to rebroadcast the transaction but unless the fee rate goes down, it will not get confirmed.

**Comment by anycolo** [comment]
Twitter doesn't allow sending you direct messages.

**Comment by anycolo** [comment]
I closed all the channels and recovered the funds using the seed. Will start a new LND node at some point.
