### ISSUE TITLE
4k outgoing connections in SYN_SENT: Can't accept connection

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#772]
I get failures trying to do basic operations against my lnd node: walletbalance, listchannels
The command just hang.

I'm running 7abdd30a878efb3673ce4dfe0070570a6c9444c8

Log is filled with
```
2018-02-20 11:28:29.657 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
2018-02-20 11:28:29.657 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
2018-02-20 11:28:29.658 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
```

looking at `lsof -n` there are 4060 connections held by the lnd process:
```
lsof -n | grep ^lnd -c
4060
```
All of those are in SYN_SENT and my host is the TCP source.

**Comment by alevchuk** [comment]
When `Ctrl-\` I get the stacks:

```
goroutine 4839031 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c5d3a1130, 0x77, 0x7f9c5d3a1138)
        /home/ligtning/src/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4217b7918, 0x77, 0xc471183200, 0xc471183288, 0xc471183201)
        /home/ligtning/src/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc4217b7918, 0xc4217b7900, 0x0, 0x0)
        /home/ligtning/src/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc4217b7900, 0xc4200121d8, 0xc4200121d8)
        /home/ligtning/src/go/src/internal/poll/fd_unix.go:403 +0x37
net.(*netFD).connect(0xc4217b7900, 0x1527860, 0xc4200121d8, 0x0, 0x0, 0x151de60, 0xc423363620, 0x0, 0x0, 0x0, ...)
        /home/ligtning/src/go/src/net/fd_unix.go:152 +0x2b6
net.(*netFD).dial(0xc4217b7900, 0x1527860, 0xc4200121d8, 0x152cc60, 0x0, 0x152cc60, 0xc468a53470, 0xc471183498, 0x58df2e)
        /home/ligtning/src/go/src/net/sock_posix.go:142 +0xe9
net.socket(0x1527860, 0xc4200121d8, 0xeae8c8, 0x3, 0x2, 0x1, 0x0, 0x0, 0x152cc60, 0x0, ...)
        /home/ligtning/src/go/src/net/sock_posix.go:93 +0x1a5
net.internetSocket(0x1527860, 0xc4200121d8, 0xeae8c8, 0x3, 0x152cc60, 0x0, 0x152cc60, 0xc468a53470, 0x1, 0x0, ...)
        /home/ligtning/src/go/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0x1527860, 0xc4200121d8, 0xeae8c8, 0x3, 0x0, 0xc468a53470, 0xc4711837d8, 0x561c84, 0x157a570)
        /home/ligtning/src/go/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x1527860, 0xc4200121d8, 0xeae8c8, 0x3, 0x0, 0xc468a53470, 0x44d9b8, 0xb84827bbbc416, 0x31e26444)
        /home/ligtning/src/go/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x1527860, 0xc4200121d8, 0xc4217b7880, 0x1522020, 0xc468a53470, 0x0, 0x0, 0x0, 0x0)
        /home/ligtning/src/go/src/net/dial.go:547 +0x3e2
net.dialSerial(0x1527860, 0xc4200121d8, 0xc4217b7880, 0xc4269a1260, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/ligtning/src/go/src/net/dial.go:515 +0x247
net.(*Dialer).DialContext(0xc471183a10, 0x1527860, 0xc4200121d8, 0xeae8c8, 0x3, 0xc423363600, 0x12, 0x0, 0x0, 0x0, ...)
        /home/ligtning/src/go/src/net/dial.go:397 +0x6ee
net.(*Dialer).Dial(0xc425e50a10, 0xeae8c8, 0x3, 0xc423363600, 0x12, 0xc425e50a30, 0x448997, 0x0, 0xc425e50a48)
        /home/ligtning/src/go/src/net/dial.go:320 +0x75
net.Dial(0xeae8c8, 0x3, 0xc423363600, 0x12, 0xc425e50b10, 0x58b6ea, 0xc42a7b9184, 0xc)
        /home/ligtning/src/go/src/net/dial.go:291 +0x99
github.com/lightningnetwork/lnd/torsvc.(*RegularNet).Dial(0x159c7f0, 0xeae8c8, 0x3, 0xc423363600, 0x12, 0xc, 0xc42001f300, 0xc42a7b9184, 0x7f9c3822d
095)
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/torsvc/net.go:14 +0x49
github.com/lightningnetwork/lnd/torsvc.(Net).Dial-fm(0xeae8c8, 0x3, 0xc423363600, 0x12, 0x43e73f, 0x0, 0x2, 0x2)
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/config.go:686 +0x5b
github.com/lightningnetwork/lnd/brontide.Dial(0xc420540630, 0xc4205abbc0, 0xc425e50cc8, 0xc4280e6ce0, 0x412cc8, 0x10)
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/brontide/conn.go:40 +0x81
main.noiseDial.func1(0x1521560, 0xc4205abbc0, 0x1b, 0xc4269a1250, 0x1, 0x1)
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/config.go:686 +0x8d
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).Connect(0xc4200fae10, 0xc4240c4280)
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:436 +0x106
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).handleFailedConn.func1()
        /home/ligtning/src/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:205 +0x33
created by time.goFunc
        /home/ligtning/src/go/src/time/sleep.go:170 +0x44
```

**Comment by Roasbeef** [comment]
How many peers did you have? Were you connected to any `clightning` nodes? They fixed an issue recently that would cause very rapid reconnects in the case of an error state. 

If all those are in the `SYN_SENT` state, then would this indicate that the receiving peer is purposefully not finishing the handshake? Though in this case, I'd guess that a time out in the kernel would be triggered.

**Comment by alevchuk** [comment]
I counted the unique IPs in the output of lsof. It's only 3.
Out of the 4k SYN_SENT connections originating from LND, there were 3775 connections to 35.198.73.46 
which resolves to 46.73.198.35.bc.googleusercontent.com

**Comment by alevchuk** [comment]
35.198.73.46 appears 40 times in lnd logs, all in the last 2 days:

all 40 occurrences are of this form:
/home/ligtning/.lnd/logs/bitcoin/testnet/lnd.log:2018-02-21 20:50:21.937 [INF] SRVR: Established connection to: 35.198.73.46:9735
/home/ligtning/.lnd/logs/bitcoin/testnet/lnd.log:2018-02-21 20:50:22.271 [INF] PEER: unable to read message from 35.198.73.46:9735: read tcp MY_IP:MY_PORT->35.198.73.46:9735: use of closed network connection

Why would lnd running 7abdd30 initiate so many connections to a single peer?

**Comment by alevchuk** [comment]
35.198.73.46 is 
pub_key 024c873f489141f6581c78a8af32a6209eb23847ca55c18b4032e6789af1abfcd0

this node has something like 70 channels which are all updated in the last 2 days:
```
lncli describegraph  | grep 024c873f489141f6581c78a8af32a6209eb23847ca55c18b4032e6789af1abfcd0 -B1 | grep last_update | awk -F: '{print $2}' | sort -nr
```

**Comment by Roasbeef** [comment]
What autopilot settings were you running with?

**Comment by alevchuk** [comment]
```
[autopilot]

; If the autopilot agent should be active or not. The autopilot agent will
; attempt to automatically open up channels to put your node in an advantageous
; position within the network graph.
autopilot.active=1

; The maximum number of channels that should be created.
autopilot.maxchannels=30

; The percentage of total funds that should be committed to automatic channel
; establishment
autopilot.allocation=1.0
```

**Comment by alevchuk** [comment]
It's happening again on 83b779dcdf535be5004c4254b805f797aa5b1d0c

logs say:
```
...
2018-02-27 11:05:23.995 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
2018-02-27 11:05:23.995 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
2018-02-27 11:05:24.145 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files
```

I'm able `lncli walletbalance` 
but `lncli listpeers` hangs forever

lsof is dominated by 3,501 connections from me to
46.73.198.35.bc.googleusercontent.com

```
lnd        6440 32587         ligtning  445u     IPv4            3477334       0t0        TCP myip:myport->46.73.198.35.bc.googleusercontent.com:45312 (SYN_SENT)
lnd        6440 32587         ligtning  446u     IPv4            3477977       0t0        TCP myip:myport->46.73.198.35.bc.googleusercontent.com:48590 (SYN_SENT)
lnd        6440 32587         ligtning  447u     IPv4            3477978       0t0        TCP myip:myport->46.73.198.35.bc.googleusercontent.com:49122 (SYN_SENT)
lnd        6440 32587         ligtning  448u     IPv4            3477979       0t0        TCP myip:myport->46.73.198.35.bc.googleusercontent.com:52624 (SYN_SENT)
lnd        6440 32587         ligtning  449u     IPv4            3477981       0t0        TCP myip:myport->46.73.198.35.bc.googleusercontent.com:51878 (SYN_SENT)
```

destinations ports are evenly distributed: 9 connections per unique port of 46.73.198.35.bc.googleusercontent.com

```
lsof > too-many-open-files-2018-02-28
cat too-many-open-files-2018-02-28  | grep "^lnd" | awk '{print $10}' | awk -F\> '{print $2}' | awk -F: '{print $1}' | sort | uniq -c | sort -n
      ...
      9 static.74.98.99.88.clients.your-server.de
      9 static.88-99-169-74.clients.your-server.de
      9 static.93.216.99.88.clients.your-server.de
     81 localhost
    673
   3501 46.73.198.35.bc.googleusercontent.com
```

This is on Ubuntu 16.04.3
I have another node that has 18,445 (!) connections to the same destination IP and seems to be doing fine.

**Comment by Roasbeef** [comment]
We've tracked this down to an issue with a high max chans setting in
autopilot. For now, if you set the max chans to a lower value, you'll
sidestep it until we fix the exact issue.

On Feb 28, 2018 8:11 AM, "Aleksandr Levchuk" <notifications@github.com>
wrote:

It's happening again on 83b779d
<https://github.com/lightningnetwork/lnd/commit/83b779dcdf535be5004c4254b805f797aa5b1d0c>

logs say:

...
2018-02-27 11:05:23.995 [ERR] CMGR: Can't accept connection: accept
tcp [::]:9735: accept4: too many open files
2018-02-27 11:05:23.995 [ERR] CMGR: Can't accept connection: accept
tcp [::]:9735: accept4: too many open files
2018-02-27 11:05:24.145 [ERR] CMGR: Can't accept connection: accept
tcp [::]:9735: accept4: too many open files

I'm able lncli walletbalance
but lncli listpeers hangs forever

lsof is dominated by 3,501 connections from me to
46.73.198.35.bc.googleusercontent.com

lnd        6440 32587         ligtning  445u     IPv4
3477334       0t0        TCP
myip:myport->46.73.198.35.bc.googleusercontent.com:45312 (SYN_SENT)
lnd        6440 32587         ligtning  446u     IPv4
3477977       0t0        TCP
myip:myport->46.73.198.35.bc.googleusercontent.com:48590 (SYN_SENT)
lnd        6440 32587         ligtning  447u     IPv4
3477978       0t0        TCP
myip:myport->46.73.198.35.bc.googleusercontent.com:49122 (SYN_SENT)
lnd        6440 32587         ligtning  448u     IPv4
3477979       0t0        TCP
myip:myport->46.73.198.35.bc.googleusercontent.com:52624 (SYN_SENT)
lnd        6440 32587         ligtning  449u     IPv4
3477981       0t0        TCP
myip:myport->46.73.198.35.bc.googleusercontent.com:51878 (SYN_SENT)

destinations ports are evenly distributed: 9 connections per unique port of
46.73.198.35.bc.googleusercontent.com

lsof > too-many-open-files-2018-02-28
cat too-many-open-files-2018-02-28  | grep "^lnd" | awk '{print $10}'
| awk -F\> '{print $2}' | awk -F: '{print $1}' | sort | uniq -c | sort
-n
      ...
      9 static.74.98.99.88.clients.your-server.de
      9 static.88-99-169-74.clients.your-server.de
      9 static.93.216.99.88.clients.your-server.de
     81 localhost
    673
   3501 46.73.198.35.bc.googleusercontent.com

This is on Ubuntu 16.04.3
I have another node that has 18,445 (!) connections to the same destination
IP and seems to be doing fine.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/772#issuecomment-369288762>,
or mute the thread

**Comment by alevchuk** [comment]
I found and confirmed a workaround: Increasing the OS limits. Ran for over a week with the increased limits and there are no more connection issues.

I documented the workaround here: https://github.com/alevchuk/pstm/blob/master/lnd-e2e-testing/OTHER.md#open-many-channels

**Comment by joaodealmeida** [comment]
I also got this error while running with autopilot off.

2018-03-28 00:55:47.999 [ERR] CMGR: Can't accept connection: accept tcp [::]:9735: accept4: too many open files

At this time I had 20 active channels and 31 peers.
