### ISSUE TITLE
[bug]: implement "fee spike buffer" from spec

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7721]
A channel initialized by the local node can only *receive* funds if the *local* balance is high enough to pay additional on-chain fees for the added (incoming) HTLC in case we need to go on-chain (force close). If the local balance is too low (which can also happen if the on-chain fees rise), the channel is rather unusable: only dust amounts can be received until the local balance is high enough.

In this "low balance" situation, lnd complains when *sending* to a peer that initiated the channel. If the balance on the peer's side is too low, the local lnd does not allow forwarding of non-dust amounts:

`[INF] LNWL: ChannelPoint(xxx:0): Reducing local balance (from 29xxxxxxxx mSAT to 353999 mSAT): remote side does not have enough funds (3510xxx mSAT < 3571000 mSAT) to pay for non-dust HTLC in case of unilateral close.`

(In this example the peer only has 3,510 sat on their side, which is below the current threshold of 3,571 sat. Because of this, a forward of 2.9 million sat did not happen)

See #7108 and https://github.com/lightning/bolts/issues/728 for a discussion of this. The solution according to https://github.com/lightning/bolts/pull/740 is to implement a "fee spike buffer" so that nodes don't deplete their balance if this reduction could cause the channel to be unusable.

See #7717 for a mitigation idea.

**Comment by ellemouton** [comment]
@C-Otto  - what do you think of just allowing the payment even if it goes below the initiators reserve as described here: https://github.com/lightning/bolts/pull/1083

**Comment by C-Otto** [comment]
Oh that's very recent discussion, thanks for pointing me there. I agree, that also sounds like a decent fix!
