### ISSUE TITLE
[Doc]: Wrong comment in handleStaleTower function coment

### ISSUE THREAD

**Issue by Chinwendu20** [lightningnetwork/lnd#7725]
The comment in the handlesStaleTower function seems to be same as the one in the handleNewTower function

https://github.com/lightningnetwork/lnd/blob/c3a2368f46af05120defd1eccfef6f51c73d19da/watchtower/wtclient/client.go#L1248-L1251

**Comment by ellemouton** [comment]
do you want to open a PR for this @Chinwendu20 ?

**Comment by ellemouton** [comment]
otherwise I can just fix it in one of my current open PRs. It is just a one word change

**Comment by Chinwendu20** [comment]
Okay no problem @ellemouton you can change it in your current PR.
