### ISSUE TITLE
[bug]: RegisterBlockEpochNtfn is sending the same event twice

### ISSUE THREAD

**Issue by dolcalmi** [lightningnetwork/lnd#7745]
### Background

RegisterBlockEpochNtfn is sending 2 events (same data) for block updates 

### Your environment

* version of `lnd`: 0.16.2-beta
* operating system: Linux
* version of `bitcoind`: v24.0.1

### Steps to reproduce

use code provided here https://lightning.engineering/api-docs/api/lnd/chain-notifier/register-block-epoch-ntfn or use Alex Library https://github.com/alexbosworth/ln-service#subscribetoblocks

### Expected behaviour

Send only 1 event per block

### Actual behaviour

Send 2 events per block (same data)

**Comment by Roasbeef** [comment]
Do you see this happening all the time, or only occasionally?

**Comment by dolcalmi** [comment]
> Do you see this happening all the time, or only occasionally?

it is happening all the time

**Comment by alexbosworth** [comment]
i don't see this on regtest

https://github.com/alexbosworth/ln-service/blob/master/test/chainrpc-integration/test_subscribe_to_blocks.js

block events only emit once for me

**Comment by guggero** [comment]
You're calling the RPC with `height`. Do you only get repeated blocks for that height or for all subsequent blocks?

**Comment by dolcalmi** [comment]
@alexbosworth @guggero this a test project where you can see the behavior https://github.com/dolcalmi/lnd-subscribe-to-blocks-test (please check the readme.. although is just run `yarn install` and then `make start`)

**Comment by alexbosworth** [comment]
did you see the behavior on the above test in ln-service? just need to do npm install on the repo and then node filename to run the file, as long as you have docker installed

can log out blocks array to see which block events were generated

**Comment by dolcalmi** [comment]
> did you see the behavior on the above test in ln-service? just need to do npm install on the repo and then node filename to run the file, as long as you have docker installed
> 
> can log out blocks array to see which block events were generated

**did you see the behavior on the above test in ln-service?**
no, but we had to debounce in galoy backend https://github.com/GaloyMoney/galoy/blob/main/src/servers/trigger.ts#L322 (same is happening  in signet and mainnet)

Not sure to underestand this `can log out blocks array` but here is a log https://github.com/dolcalmi/lnd-subscribe-to-blocks-test/blob/main/logs.txt#L2058 of lnd

**Comment by alexbosworth** [comment]
like if you run the subscribe to blocks file and you do console.log on blocks at the end of the test or in the foreach at the end, does it show repetition for you?

**Comment by dolcalmi** [comment]
> like if you run the subscribe to blocks file and you do console.log on blocks at the end of the test or in the foreach at the end, does it show repetition for you?

yes, same behavior https://github.com/dolcalmi/lnd-subscribe-to-blocks-test/blob/main/test-blocks.js#L51
```
From grpc client -> Height: 201 - 09d6c1e3515a71a63534a6b0de09970cabaedc0d904d104693cd837bb975bda0
from lnService -> Height: 201 - 09d6c1e3515a71a63534a6b0de09970cabaedc0d904d104693cd837bb975bda0
From grpc client -> Height: 201 - 09d6c1e3515a71a63534a6b0de09970cabaedc0d904d104693cd837bb975bda0
from lnService -> Height: 201 - 09d6c1e3515a71a63534a6b0de09970cabaedc0d904d104693cd837bb975bda0
from lnService -> Height: 202 - 40664ee2ef52654fd0b9ba65205f0f184a8764e68902d29a0dbc805569861293
From grpc client -> Height: 202 - 40664ee2ef52654fd0b9ba65205f0f184a8764e68902d29a0dbc805569861293
from lnService -> Height: 202 - 40664ee2ef52654fd0b9ba65205f0f184a8764e68902d29a0dbc805569861293
From grpc client -> Height: 202 - 40664ee2ef52654fd0b9ba65205f0f184a8764e68902d29a0dbc805569861293
```

**Comment by alexbosworth** [comment]
sorry i mean if you run https://github.com/alexbosworth/ln-service/blob/master/test/chainrpc-integration/test_subscribe_to_blocks.js

and modify the end of the test to do console.log(blocks) does it show duplicates

**Comment by dolcalmi** [comment]
> sorry i mean if you run https://github.com/alexbosworth/ln-service/blob/master/test/chainrpc-integration/test_subscribe_to_blocks.js
> 
> and modify the end of the test to do console.log(blocks) does it show duplicates

:thinking: it does not show duplicates... I did some tests and I think I found it... it is happening with this setting `zmqpubrawblock`

bitcoind config: https://github.com/dolcalmi/lnd-subscribe-to-blocks-test/blob/main/dev/bitcoind/bitcoin.conf#L9
lnd config: https://github.com/dolcalmi/lnd-subscribe-to-blocks-test/blob/main/dev/lnd/lnd.conf#L34

**Comment by guggero** [comment]
I just took a quick look at the log file in your test and see this:

```
Possible reorg at block: height=188, hash=1596dbacc5e72da3ce0a38f1fbd47e4258bb49206bc034481690f5563a516560
...
Disconnecting block: height=188, hash=1596dbacc5e72da3ce0a38f1fbd47e4258bb49206bc034481690f5563a516560
```

So it looks like your test is doing a re-org, in which case it would be expected to be notified about a block multiple times. So I'd say something is up with the test logic itself.

**Comment by guggero** [comment]
Thank you for the test project. I now took a look at it and can say with a large degree of certainty that the multiple notifications happen because `lnd` thinks there is a re-org (the log lines I posted above).

I changed to another `bitcoind` docker image and the problem was gone:

```
  bitcoind:
    image: ruimarinho/bitcoin-core:23
    ports:
      - "18443:18443"
    environment:
      - HOME=/home/bitcoin
    volumes:
      - ${PWD}/dev/bitcoind/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
```

So I'm pretty sure something in how ZMQ works is broken or different in your `lncm` variant of the `bitcoind` docker image.

**Comment by guggero** [comment]
Closing this as I'm pretty sure this is an issue of the specific fork/build of `bitcoind` and not `lnd`.

@dolcalmi I looked at the `Dockerfile` for `lncm/bitcoind` and it looks like the ZMQ parameters are supplied as command line arguments: https://github.com/lncm/docker-bitcoind/blob/master/24.0/Dockerfile#L256
Maybe adding the same values in the config file actually creates **two** ZMQ endpoints under the same address which ends up pushing the events twice? No idea how ZMQ works under the hood, but if that is the case then you should be fine with just removing those two lines from your `bitcoin.conf` and things should work normally.
