### ISSUE TITLE
[bug]: The UpdateChannelPolicy doesn't change min_htlc_msat for channel.

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#7751]
### Background

The gRPC `UpdateChannelPolicy` doesn't change `min_htlc_msat` for channel.
I am trying to change the `min_htlc_msat` parameter for all channels, but it remains the same.

For example: I use `lnd-async` node module as:

```
...
client.updateChannelPolicy({
    chan_point: {
        funding_txid_str: hash,
        output_index:     index
    },
    time_lock_delta: FOREIGN_DELTA_CLTV,
    base_fee_msat: Math.round(baseFee),
    fee_rate_ppm: Math.round(ppm),
    min_htlc_msat: 900,
    min_htlc_msat_specified: true
})
...
```

Here I specifically set it as `900` for verification. After that I watch it through the cli command for channels:

```
lncli listchannels|grep min_htlc_msat
```

And there are all the old values: 1 or 1000, for example. But not 900. Absolutely for all channels! Both for active and not for active.

The same will happen if you specify via the command line:

```
lncli updatechanpolicy --min_htlc_msat 900 --chan_point TX_ID:1 --base_fee_msat 125 --fee_rate_ppm 5 --time_lock_delta 80
```

After:

```
        {
            "active": true,
            "remote_pubkey": "XXXXX",
            "channel_point": "TX_ID:1",
             ...
            "local_constraints": {
                "csv_delay": 2016,
                "chan_reserve_sat": "276855",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "27408715000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            ....
```

### Your environment

* version of `lnd` - 0.16.2-beta
* which operating system (`uname -a` on *Nix) - Ubuntu 20.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind

### Steps to reproduce

To see [Background](#Background) section

### Expected behaviour

If it is described in the [documentation](https://lightning.engineering/api-docs/api/lnd/lightning/update-channel-policy) that it can be changed, it should change. In practice, it does not change at all - there are always those values that were specified at the time of opening the channel.

### Actual behaviour

To see [Background](#Background) section

**Comment by hieblmi** [comment]
Hi @LNBIG-COM, thanks for reporting. Interesting, I just tried your `lncli` command with `v0.16.3-beta` and it sets the `min_htlc_msat` to 900.
```
"node2_policy": {
        "time_lock_delta": 144,
        "min_htlc": "900",
        "fee_base_msat": "125",
        "fee_rate_milli_msat": "5",
        "disabled": false,
        "max_htlc_msat": "xxx",
        "last_update": xxx,
        "custom_records": {
        }
    },
```

What does your `lncli getchaninfo` report for your side of the channel?

**Comment by LNBIG-COM** [comment]
I also noticed such a feature/bug. If the remote node is offline, then after I call the `UpdateChannelPolicy` function, the `min_htlc` data does not change even in `getchaninfo`. Apparently this is due to the fact that my changes fall into the buffer/queue for the node, which will be transferred to it only when the node is online and only after that (by agreement with him?) they will be sent to the network graph, where they will then be visible in `getchaninfo`. Is it right, @Roasbeef ?

At the same time, changes in fees on my part (base_fee/rate ppm) are immediately reflected in `feereport`.

There is a strange collision. How can I use through API to get the current data (`min_htlc` amount in my case) for the node (I need it to update those nodes where the data has changed from my side)? After all, it turns out that one part of the data is reflected in the LND completely (fee rates), the other is apparently waiting for the node to appear online (which may appear even in a month) and only then is updated (`min_htlc`?). If I mistakenly cause a constant change of `min_htlc` for a node, mistakenly believing that it is old, then while the node appears online, the internal buffer of the LND may overflow, or when the remote node goes online, I will fill it up with old updates in huge quantities?

**Comment by saubyk** [comment]
closing this issue based on the comment above. feel free to reopen if you feel otherwise. thanks.
