### ISSUE TITLE
[bug]: channel close transaction swept by another party using RBF, LND still waiting for original transaction to confirm

### ISSUE THREAD

**Issue by puck2** [lightningnetwork/lnd#7754]
### Background

After lightning node reset and restoration from channel backup, anchor sweep transaction was created, and then that transaction was replaced by someone else. My node is still waiting for the original transaction to confirm, so funds are stuck in lightning wallet.

### Your environment

* version of `lnd` :  **0.16.3-beta** 

* which operating system (`uname -a` on *Nix): **umbrel 0.5.3**

* version of `btcd`, `bitcoind`, or other backend: **Bitcoin Core 25.0.0**

* any other relevant environment details

### Steps to reproduce

Lightning node crashes, restored from backup. Force close transactions are sent to network. Force close transaction is replaced by fee by another party. LND continues to look for original transaction?

### Expected behaviour

LND should find transaction that replaced original and notice that it has confirmed (leaving original unconfirmed).

### Actual behaviour

LND continues to wait for original transaction to confirm, leaving funds stuck.

**Comment by Crypt-iQ** [comment]
The force close transaction typically can't be RBF'd

**Comment by puck2** [comment]
ok, well it finally went through so I guess this isn't a bug?

**Comment by puck2** [comment]
I can delete if necessary

**Comment by puck2** [comment]
resolved just as issue was posted
