### ISSUE TITLE
[feature]: Macaroon for just open/close channels + making invoices

### ISSUE THREAD

**Issue by massmux** [lightningnetwork/lnd#7761]
After a talk to Alex, we considered it would be nice to have the possibility to bake macaroons with just those functionalities:

- open a channel
- close a channel either forced or cooperative
- issue a LN invoice

**Comment by guggero** [comment]
This can already be done today by specifying the URIs for those RPC calls in the permissions.
See `lncli bakemacaroon --help` or https://github.com/lightningnetwork/lnd/blob/master/macaroons/README.md#bakery

**Comment by alexbosworth** [comment]
I forget the context but i think part of the discussion was also limiting the power of those commands

open a channel has the power to gift the balance to the opposite side, so you should use rpc middleware to stop that

close a channel has the power to close the local balance out to an arbitrary address, so more rpc middleware
