### ISSUE TITLE
[bug]: Default values of watchtower and wtclient are not displayed in lnd --help

### ISSUE THREAD

**Issue by feelancer21** [lightningnetwork/lnd#7769]
### Background

During my work on #7612 I realized that there are several default values for the watchtower and wtclient in the code. But the defaults are not shown in `lnd --help`

Defaults for wtclient
https://github.com/lightningnetwork/lnd/blob/cf1f44ab10c773ace4039f30c401daf8da47ed85/watchtower/wtclient/client.go#L32

But there are no defaults linked here:
https://github.com/lightningnetwork/lnd/blob/cf1f44ab10c773ace4039f30c401daf8da47ed85/config.go#L526

### Expected behaviour

All defaults should be shown

**Comment by ellemouton** [comment]
Thanks for the issue @feelancer21  - I opened a fix in #7771
