### ISSUE TITLE
Force closed channel stuck in Limbo past maturity

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lightningnetwork/lnd#7795]
### Background

Since the last update to v0.16.3 I have a peculiar issue on two of my nodes, where force closed channels are stuck in Limbo. I checked previous issues like this, but suggested resolutions don't work.

### Your environment

* version of `lnd` v0.16.3
* which operating system (`uname -a` on *Nix) Debian 11 (Host) - golang:1.19.2-alpine (Docker) 
* version of `btcd`, `bitcoind`, or other backend - bitcoind via Neutrino
* any other relevant environment details

### Steps to reproduce

After upgrade to new version, from 0.16.2

### Expected behaviour

Channels are recognized as past maturity, so sats should be in onchain wallet, channels should not be in Limbo.

### Actual behaviour

Channels are stuck in Limbo, even though closing transaction and maturity are detected correctly, here is one example:
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "03d58a9b39eaa2edc19ed2a98e74887e538e5dd3694d9580419bfac839d993f358",
                "channel_point": "83ad47a6e0db46a7ef164044f04fe285ff10c38715889769b2b6816048afa765:1",
                "capacity": "1500000",
                "local_balance": "840",
                "remote_balance": "1495690",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "closing_txid": "435d1f952eb5de010be18d14be2b1b7a0e6124423a8d31a8e0f628628f8d0ef4",
            "limbo_balance": "1170",
            "maturity_height": 794465,
            "blocks_til_maturity": -1686,
            "recovered_balance": "0",
            "pending_htlcs": [
            ],
            "anchor": "LIMBO"
        }
    ],
    "waiting_close_channels": [
    ]
}

Already tried rescanning the chain, didn't help.

**Comment by Roasbeef** [comment]
> "local_balance": "840",

You have a very small amount pending to be swept. At the current fee rate, `lnd` won't automatically sweep it as we may pay more in fees than the actual channel amount. Once fees come down, then this can be swept eventually, or you can force it to be swept (likely paying more than the amt for it to be swept).

**Comment by MichaelAntonFischer** [comment]
That cannot be the reason. The transaction was confirmed over 2016 blocks ago. Also one of the other stuck channels has 4 Mio. of my sats in Limbo.

**Comment by ziggie1984** [comment]
Lnd will only move the channel from `pending_force_closing_channels ` to the final `closedchannels` if all contract which belong to you are resolved. In your shown case as Roasbeef pointed out there is the `to_local` output of 840 sats which are not economical to sweep at current fee-conditions so the contract remains open therefore the channel still appears in the `pending_force_closing_channels ` list. Could you show the problem with the other channel where you say that 4 mio are still in limbo ?

**Comment by MichaelAntonFischer** [comment]
The other channel has in the meantime switched to closed state, but my node still shows the Sats as pending and unspendable.

https://mempool.space/address/bc1qyf9grjjptcgs888ttl2nwx7nf04t0v7fwc4qq4n4dy9cn4lgsvaqpxlpsj

Can you please clarify if I fundamentally misunderstand how Lightning works… I had understood that the sweep of Sats is when the channel transaction is broadcast to the miners.

You make it sound like a second on-chain transaction was necessary for that.

**Comment by ziggie1984** [comment]
> The other channel has in the meantime switched to closed state, but my node still shows the Sats as pending and unspendable.

Not sure why they are shown unspendable in your situation. You do not see this utxo (`3e603255556e2debed1b2de4005090ea884eff292f31b107719b850ab09c24ac:0`) in your `lncli listunspent` output? The chain makes it clear that the funds are already in a wallet (using a p2tr address which lnd currently uses for its user-controlled wallet)

> Can you please clarify if I fundamentally misunderstand how Lightning works… I had understood that the sweep of Sats is when the channel transaction is broadcast to the miners.

So there are plenty of resources out there, I try to make a short explanation. In case a contract (channel) has to be resolved onchain alias "force closed" there are different set of outputs (alias contracts) on the commitment transaction which have different requirements when these can be taken (swept by the owner). When you force-close the channel your funds on the commitment tx are locked. They need a second sweep transaction when the lock expires to take it back into your normal wallet. HTLC outputs on the commitment tx which belong to you have a 2-stage locking meaning that you will have to sweep them 2 times until they are available to your wallet. For detailed infos see [Bolt3](https://github.com/lightning/bolts/blob/master/03-transactions.md#commitment-transaction-outputs). Until all those outputs which belong to you are still not swept, this channel is in a pending state. 

In regards of your 4 mio output tx, these funds should. be available. So there we need more info why they seem to be unspendable in your case.

**Comment by saubyk** [comment]
Closing this issue based on the explanations provided above, if you still have questions, feel free to reopen.

**Comment by MichaelAntonFischer** [comment]
@ziggie1984 I was hoping for this to resolve itself, aber even after restarting and rescanning the chain I still have this issue that two transactions totaling over 5 million Sats are flagged as pending, cannot be spent.

I checked lncli listunspent they are listed, here the 4mio:
                        "address_type": 4,
                        "address": "bc1pw58xdf247wrv7jzt94c9avrf3j2zurvckpcalahdwvc33lvemdysqjctsh",
                        "amount_sat": 4523226,
                        "pk_script": "5120750e66a555f386cf484b2d705eb0698c942e0d98b071dff6ed733118fd99db49",
                        "outpoint": "b31aa27944dd3d6d12c8905b40d24775d1dafd467fc24116488b4c1141ad0329:0",
                        "confirmations": 0

**Comment by ziggie1984** [comment]
> @ziggie1984 I was hoping for this to resolve itself, but even after restarting and rescanning the chain I still have this issue that two transactions totaling over 5 million Sats are flagged as pending, cannot be spent.

I think you ran most likely in this problem: #7790 

Could you change the backend and let it resolve itself for you?  I think this transaction blocks one of your inputs as described in the linked issue. Backend switch is the only solution here for now,  because then this invalid transaction will be rebroadcasted but immediately removed because a full-node gives you an error when broadcasting a transaction without a valid (unkown) previous output. Neutrino however will mark it as orphan and will be just fine.

**Comment by MichaelAntonFischer** [comment]
Thanks for the response, the current setup on this node doesn't give me the option to directly connect a full bitcoin node. Any other ideas?

**Comment by ziggie1984** [comment]
One other solution: Setup a pruned node maybe that would suffice as well, you just need a mempool for the fix.

If that's not available there is still another method.

So this other method involves psbts which is not super easy but if you are a technical person should be doable as well:

1. You need to know which input is locked by this never confirming transaction, normally when restarting lnd look for the transaction with this txid: `b31aa27944dd3d6d12c8905b40d24775d1dafd467fc24116488b4c1141ad0329 ` and check the logs there must be also the hex-tx logged somewhere.

2. When you were able to fish this transaction you need someone with a running bitcoin node (pruned or normal does not matter). And run `bitcoin-cli decoderawtransaction <hex transaction>`. There we can extract the input which you would like to spend but is currently locked. When you have this txid of the input the psbt creating process begins.

3. You or someone with a btc node creates a psbt with the inputs and outputs you want. Use the following command

```bitcoin-cli  createpsbt "[{\"txid\":\"310468bfa056cc7fec627aea2040b3c198445af7c191d5df74633f9cabc9b3b6\",\"vout\":1}]" "[{\"bcrt1pdrhytxncrlpuafn67uu5p8d2748n2uk2kgaq3tqn53ldj653rejsrw4q6d\":0.97993080}]" ```

=> Result: `cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAAA`

Here the locked input is: 310468bfa056cc7fec627aea2040b3c198445af7c191d5df74633f9cabc9b3b6:1

the address is the output I want to receive funds to. Make sure you substract fees from the amount and they have to be sufficient to confirm soon. A tx with 1 input and 1 output has around 130 vbytes. So depending on your Inputs and outputs you create you have to account for sufficient fees.

Now you need to update the resulting psbt with information use the following command:

` bitcoin-cli  utxoupdatepsbt cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAAA``

=> Result: `cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkAAA==`

Almost done now:

Now you need to sign this transaction for this switch to your lightning node:

Signing the tx with the following command:

```
rlncli wallet psbt finalize cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkAAA==
```

=> Result: ```{
	"psbt": "cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkBCEIBQP1LH3LKGV8glMjDDwBfV6X8N2SBA0Ag4VgTprYHoVwb4HwnB+1/wH0d0huA2qQGzyN4+VcOwRuKU6u4BSIp5zkAAA==",
	"final_tx": "02000000000101b6b3c9ab9c3f6374dfd591c1f75a4498c1b34020ea7a62ec7fcc56a0bf6804310100000000fdffffff017841d7050000000022512068ee459a781fc3cea67af739409daaf54f3572cab23a08ac13a47ed96a911e650140fd4b1f72ca195f2094c8c30f005f57a5fc376481034020e15813a6b607a15c1be07c2707ed7fc07d1dd21b80daa406cf2378f9570ec11b8a53abb8052229e73900000000"
}```


Now you are done, you have the tx, double check the tx with the command: `bitcoin-cli decoderawtransaction ...`


If it is good broadcast it:

```
rlncli wallet publishtx --label "own-sweep" 02000000000101b6b3c9ab9c3f6374dfd591c1f75a4498c1b34020ea7a62ec7fcc56a0bf6804310100000000fdffffff017841d7050000000022512068ee459a781fc3cea67af739409daaf54f3572cab23a08ac13a47ed96a911e650140fd4b1f72ca195f2094c8c30f005f57a5fc376481034020e15813a6b607a15c1be07c2707ed7fc07d1dd21b80daa406cf2378f9570ec11b8a53abb8052229e73900000000
```

Now wait until a block is found and your balance should be resolved.

**Comment by ziggie1984** [comment]
For questions, you can write me on the lnd slack ;)

**Comment by aplnx** [comment]
> One other solution: Setup a pruned node maybe that would suffice as well, you just need a mempool for the fix.
> 
> If that's not available there is still another method.
> 
> So this other method involves psbts which is not super easy but if you are a technical person should be doable as well:
> 
>     1. You need to know which input is locked by this never confirming transaction, normally when restarting lnd look for the transaction with this txid: `b31aa27944dd3d6d12c8905b40d24775d1dafd467fc24116488b4c1141ad0329 ` and check the logs there must be also the hex-tx logged somewhere.
> 
>     2. When you were able to fish this transaction you need someone with a running bitcoin node (pruned or normal does not matter). And run `bitcoin-cli decoderawtransaction <hex transaction>`. There we can extract the input which you would like to spend but is currently locked. When you have this txid of the input the psbt creating process begins.
> 
>     3. You or someone with a btc node creates a psbt with the inputs and outputs you want. Use the following command
> 
> 
> `bitcoin-cli createpsbt "[{\"txid\":\"310468bfa056cc7fec627aea2040b3c198445af7c191d5df74633f9cabc9b3b6\",\"vout\":1}]" "[{\"bcrt1pdrhytxncrlpuafn67uu5p8d2748n2uk2kgaq3tqn53ldj653rejsrw4q6d\":0.97993080}]" `
> 
> => Result: `cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAAA`
> 
> Here the locked input is: 310468bfa056cc7fec627aea2040b3c198445af7c191d5df74633f9cabc9b3b6:1
> 
> the address is the output I want to receive funds to. Make sure you substract fees from the amount and they have to be sufficient to confirm soon. A tx with 1 input and 1 output has around 130 vbytes. So depending on your Inputs and outputs you create you have to account for sufficient fees.
> 
> Now you need to update the resulting psbt with information use the following command:
> 
> ` bitcoin-cli utxoupdatepsbt cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAAA``
> 
> => Result: `cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkAAA==`
> 
> Almost done now:
> 
> Now you need to sign this transaction for this switch to your lightning node:
> 
> Signing the tx with the following command:
> 
> ```
> rlncli wallet psbt finalize cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkAAA==
> ```
> 
> => Result: `{ "psbt": "cHNidP8BAF4CAAAAAbazyaucP2N039WRwfdaRJjBs0Ag6npi7H/MVqC/aAQxAQAAAAD9////AXhB1wUAAAAAIlEgaO5Fmngfw86mevc5QJ2q9U81csqyOgisE6R+2WqRHmUAAAAAAAEBK9lC1wUAAAAAIlEg+edkbYkKUOZIEwiRDoEgjJIVRIsYaUa3sGEB7QwlHOkBCEIBQP1LH3LKGV8glMjDDwBfV6X8N2SBA0Ag4VgTprYHoVwb4HwnB+1/wH0d0huA2qQGzyN4+VcOwRuKU6u4BSIp5zkAAA==", "final_tx": "02000000000101b6b3c9ab9c3f6374dfd591c1f75a4498c1b34020ea7a62ec7fcc56a0bf6804310100000000fdffffff017841d7050000000022512068ee459a781fc3cea67af739409daaf54f3572cab23a08ac13a47ed96a911e650140fd4b1f72ca195f2094c8c30f005f57a5fc376481034020e15813a6b607a15c1be07c2707ed7fc07d1dd21b80daa406cf2378f9570ec11b8a53abb8052229e73900000000" }`
> 
> Now you are done, you have the tx, double check the tx with the command: `bitcoin-cli decoderawtransaction ...`
> 
> If it is good broadcast it:
> 
> ```
> rlncli wallet publishtx --label "own-sweep" 02000000000101b6b3c9ab9c3f6374dfd591c1f75a4498c1b34020ea7a62ec7fcc56a0bf6804310100000000fdffffff017841d7050000000022512068ee459a781fc3cea67af739409daaf54f3572cab23a08ac13a47ed96a911e650140fd4b1f72ca195f2094c8c30f005f57a5fc376481034020e15813a6b607a15c1be07c2707ed7fc07d1dd21b80daa406cf2378f9570ec11b8a53abb8052229e73900000000
> ```
> 
> Now wait until a block is found and your balance should be resolved.

I have a comment on #7790. I am trying to understand issues here too because they correlate with my problem. If I have questions I will continuing to post here...
