### ISSUE TITLE
Creates invoices for payments we've sent

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#78]
## Issue 
Currently within the daemon, we keep records of all payments we've requested and fulfilled successfully. The code for this lives in [`channeldb/invoices.go`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/invoices.go) and also within the [`invoiceregistry.go`](https://github.com/lightningnetwork/lnd/blob/master/invoiceregistry.go). With this code in place users/merchants/exchanges are able to maintain full records about all pending and settled payments they've requested.

However, records for the opposite don't currently exist within the daemon. By the opposite I mean tracking records for all _outgoing_ payments we've sent. This excludes outgoing payments sent due to the forwarding of HTLC's, as those amy happen automatically based on daemon settings, those shouldn't be recorded. 

It's important to maintain records about all user triggered outgoing payments for the following reasons: 
  * UI's can show outgoing payments in-line with regular Bitcoin payments if they so choose. 
  * Tracking outgoing payments lets us track stats such as the average path length, fees paid, frequency of payments, etc. 
   * ... 

## Steps to Completion 

- [ ] A new bucket in the database should be created in order to house payments _we've_ successfully settled. 
   * The current `channeldb.Invoice` struct and the related serialization methods can likely be re-used. 

- [ ] In addition to the information stored within `channeldb.Invoice`, the following attributes for outgoing payments should be tracked (for each payment): 
   * Fee paid
   * Path length
   * Possibly the entire path?
   * Total time-lock length

  The ultimate struct will likely use struct embedding for composition purposes. 

- [ ] Within the `SendPayment` RPC, if the goroutine spawned to send the payment receives a non-nil error, then the record described above should be written to disk. 

- [ ] A new RPC should be added to `lnrpc` and implemented within `rpcserver.go` which returns a list of all outgoing payments.

**Comment by BitfuryLightning** [comment]
Will take this one.

**Comment by BitfuryLightning** [comment]
Some initial work
https://github.com/lightningnetwork/lnd/pull/88
