### ISSUE TITLE
Can't sweep remaining funds

### ISSUE THREAD

**Issue by georgeorwell23** [lightningnetwork/lnd#7810]
Hi, 

I opened 2 channels 2 months ago or so. It never hitted the chain and was dropped out of the mempools (purged) due to the high fee enviroment. I closed down this node sweeped all the funds and there is still 20K sats left that i can't sweep https://mempool.space/tx/dfcdf81c8efa2685bffa91229336dde89fd8f979e443389a0f25faf35b0a9b08

When i run lncli pendingchannels i see this:

 "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "02b92193a4c9d035c81f8076ae4a4aba04b7ea8e04058eb3296f894e6ccd5f2e6e",
                "channel_point": "0fc3e20a8335fc4c5ea67e2a3e1ca0026179068ebf007ea60af527809f7bf476:1",
                "capacity": "1000000",
                "local_balance": "996530",
                "remote_balance": "0",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "commit_fee": "2810",
            "commit_weight": "772",
            "fee_per_kw": "2500"
        },
        {
            "channel": {
                "remote_node_pub": "03e5a10bd9d700cfefd89dcfb423e3b8124895feae20be70a967db4443594106e7",
                "channel_point": "0fc3e20a8335fc4c5ea67e2a3e1ca0026179068ebf007ea60af527809f7bf476:2",
                "capacity": "1000000",
                "local_balance": "996530",
                "remote_balance": "0",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "commit_fee": "2810",
            "commit_weight": "772",
            "fee_per_kw": "2500"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

I tried [#6301 & #7505 ] but after those steps i was still not able to sweep the funds. How can i fix this?

### Your environment

lnd version 0.16.3-beta
Bitcoin Core RPC client version v25.0

**Comment by georgeorwell23** [comment]
When i run lncli listunspent i see this:

{
        "utxos": [
                {
                        "address_type": 4,
                        "address": "bc1pru0qcakuddy7lt74nlapqdmmcntp635e82n7k5rrel9dzd3vycrscnwjzh",
                        "amount_sat": 20000,
                        "pk_script": "51201f1e0c76dc6b49efafd59ffa10377bc4d61d46993aa7eb5063cfcad1362c2607",
                        "outpoint": "dfcdf81c8efa2685bffa91229336dde89fd8f979e443389a0f25faf35b0a9b08:0",
                        "confirmations": 4
                }
        ]
}

**Comment by Roasbeef** [comment]
AFAICT, those funds don't exist. The transaction was never published, so there aren't any coins to sweep on chain.

**Comment by georgeorwell23** [comment]
Thanks for your reaction. But why can't i spend the 20K sats? As far as i understand the 20K sats are the local channel reserve

**Comment by ziggie1984** [comment]
So you will first need to abandon both of the open channels which never made it into mempool, only then will you be able to sweep the remaining 20k sats. This is the anchor reserve for each pending open channel (10k for each). Lnd keeps an anchor reserve for any pending channel.

So what you need to do:

`lncli abandonchannel ...`

then 

`lncli sendcoins --sweepall ....`

**Comment by georgeorwell23** [comment]
@ziggie1984 thanks for your reply! Was able to figure it out and sweeped all the funds.
