### ISSUE TITLE
[bug]:  Blockchain Progress: 100.00% - Lightning Progress: prepare sync 

### ISSUE THREAD

**Issue by felivix** [lightningnetwork/lnd#7813]
### Background

After update to 1.9.0 and after each reboot the process gets stuck after blockchain has synched to 100%. 
"Lightning Progress: prepare sync". The process is stuck here for hours and possibly days.

CLN v23.02.2
Not Started | Not Ready Yet | No Data

I'm running RaspiBlitz v1.9.0

**Comment by saubyk** [comment]
Hi @felivix it appears that you're running core lightning on your Raspiblitz. This is not the right repo for core lightning issues, please open your issue on the below repos:
https://github.com/raspiblitz/raspiblitz
or
https://github.com/ElementsProject/lightning

hope this helps. thanks.
