### ISSUE TITLE
[bug]: TrackPaymentV2 REST Request Failure

### ISSUE THREAD

**Issue by originalix** [lightningnetwork/lnd#7821]
### Background

I’m encountering an issue while using the TrackPaymentV2 APIs via REST. While making a request, I always receive the following error:

```js
{
  "error": {
    "code": 2,
    "message": "invalid hash length of 48, want 32",
    "details": []
  }
}
```

However, the same API works as expected when accessed via gRPC.

### Your environment

* version of `lnd`: lnd version 0.16.3-beta commit=v0.16.3-beta
* which operating system (`uname -a` on *Nix): Linux ip-172-31-27-211 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Satoshi:25.0.0
* any other relevant environment details

### Steps to reproduce

Request TrackPaymentV2 api as documentation example

### Expected behaviour

Returns the same response as grpc

**Comment by ziggie1984** [comment]
Good find, this seems to be the case for all REST requests with the specific parameter prop. Just tested with the `buildroute` cmd alias `/v2/router/route` for the type `hop_pubkeys`where the parameter has the same properties as the one for the trackpayment:

```
   "items": {
            "type": "string",
            "format": "byte"
          },
```

Leads to the same error: 

`{"code":2,"message":"invalid vertex length of 49, want 33","details":[]}%`

**Comment by originalix** [comment]
Absolutely, is it possible to fix this issue as soon as possible?

**Comment by ziggie1984** [comment]
yes I have a fix, you need to convert the value to base64

**Comment by ziggie1984** [comment]
So I think there still needs to be some documentation fix because for some protofiles we especially comment that for REST the byte values have to be [base64-encoded](https://github.com/lightningnetwork/lnd/blob/33b470b4a668873bbad6d1ce03f22816db4f931a/lnrpc/lightning.proto#L781-L782) but for the trackpayment command would be useful as well I guess:
https://github.com/lightningnetwork/lnd/blob/33b470b4a668873bbad6d1ce03f22816db4f931a/lnrpc/routerrpc/router.proto#L308-L309

**Comment by originalix** [comment]
Yes, I was also confused about this part before I raised the issue, until I tested it and found that base64 encoding is possible, but I didn't find a description in the documentation

**Comment by guggero** [comment]
This is a known issue with the library we use for translating gRPC calls into REST: Any field that has the `bytes` type must be declared as base64 in REST. And if it appears in the URL, it must be base64url encoded.
This is documented here: https://lightning.engineering/api-docs/api/lnd/#rest-encoding

**Comment by originalix** [comment]
Thank you @guggero , that works for me ! 🎉
