### ISSUE TITLE
[bug]: Does not sync even after days waiting

### ISSUE THREAD

**Issue by frnandu** [lightningnetwork/lnd#7850]
### Background

I had a pending open channel for few days even tough the opening transaction had already >100 confirmations,
so I tried to restart my lnd (umbrel) with reset-wallet-transactions=1 and now it cannot sync, logs attached.
What can I do, to fix this?

### Your environment

LND 0.16.4-beta  (umbrel)
Linux 5.19.0-46-generic #47~22.04.1-Ubuntu
Bitcoin Core 24.0.1
Umbrel 0.5.4

Logs attached
[lnd.log](https://github.com/lightningnetwork/lnd/files/12134824/lnd.log)

**Comment by guggero** [comment]
It looks like your connectivity to the internet through Tor could be the issue. Try restarting your complete node, not just `lnd`.

**Comment by saubyk** [comment]
Hi @frnandu closing this assuming your issue has been addressed. Feel free reopen, if that's not the case.
