### ISSUE TITLE
[bug]: sending update_fail_malformed_htlc with error code 4103 (aka temporary_channel_failure)?

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#7851]
### Background

Report that Bitrefill is sending these, and CLN is issuing a warning and closing the connection:

   https://github.com/ElementsProject/lightning/pull/6425

Seems weird, but pretty sure they're LND?

### Steps to reproduce

It obviously doesn't happen very often: the result of this would be a channel closure when we eventually get sick of the HTLC and it times out.

Posting here in case it's a known issue or been reported before?

**Comment by Roasbeef** [comment]
Perhaps there's an _onion replay_ happening somewhere in the route? See this issue for an example: https://github.com/lightningnetwork/lnd/issues/5792#issuecomment-930805556 

There's a known bug where we don't properly transform the error internally before sending out on the wire: https://github.com/lightningnetwork/lnd/issues/5443#issuecomment-869977886. Looks like this fell through the cracks shortly after the realization in that issue, will reprio....
