### ISSUE TITLE
[bug]: lnd 0.16.4 crash

### ISSUE THREAD

**Issue by yaslama** [lightningnetwork/lnd#7853]
### Background
After upgrading from 0.16.2 to 0.16.4, the node ran for few hours then crashed

### Your environment

* version of `lnd`: 0.16.4
* which operating system (`uname -a` on *Nix): linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind 

### Steps to reproduce
 The crash occurred once:
```
Jul 23 11:19:34 breez1 lnd[919914]: panic: sync: WaitGroup is reused before previous Wait has returned
Jul 23 11:19:34 breez1 lnd[919914]: goroutine 5844388 [running]:
Jul 23 11:19:34 breez1 lnd[919914]: sync.(*WaitGroup).Wait(0xc03dc1de70?)
Jul 23 11:19:34 breez1 lnd[919914]:         sync/waitgroup.go:118 +0x7f
Jul 23 11:19:34 breez1 lnd[919914]: github.com/lightningnetwork/lnd/peer.(*Brontide).WaitForDisconnect(...)
Jul 23 11:19:34 breez1 lnd[919914]:         github.com/lightningnetwork/lnd/peer/brontide.go:1064
Jul 23 11:19:34 breez1 lnd[919914]: github.com/lightningnetwork/lnd.(*server).peerTerminationWatcher(0xc0014f6600, 0xc0248d8000, 0xc0fd425ce0?)
Jul 23 11:19:34 breez1 lnd[919914]:         github.com/lightningnetwork/lnd/server.go:3958 +0xea
Jul 23 11:19:34 breez1 lnd[919914]: created by github.com/lightningnetwork/lnd.(*server).peerInitializer
Jul 23 11:19:34 breez1 lnd[919914]:         github.com/lightningnetwork/lnd/server.go:3914 +0x14a0
```

**Comment by bitromortac** [comment]
Could be related to https://github.com/lightningnetwork/lnd/pull/7711. Are there more logs around this event for the `PEER` subsystem, maybe those could give some insights (particularly grep for `Force closing link`)?

**Comment by Roasbeef** [comment]
What version of Go were y'all running? 

Potentially related to: https://github.com/lightningnetwork/lnd/issues/6788

**Comment by yaslama** [comment]
> What version of Go were y'all running?

go1.20.6
