### ISSUE TITLE
[bug]: cannot start LND: unknown option: lnd.feeurl

### ISSUE THREAD

**Issue by jangorecki** [lightningnetwork/lnd#7861]
### Background

I am not able to start LND using latest release and configuration according according to getting started guide.

### Your environment

* version of `lnd`: `0.16.4-beta`
* which operating system (`uname -a` on *Nix): `Linux workstation1 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `neutrino`

### Steps to reproduce

1. Unpack `lnd-linux-amd64-v0.16.4-beta.tar.gz`
2. Write `~/.lnd/lnd.conf` according to https://docs.lightning.engineering/lightning-network-tools/lnd/run-lnd#docs-internal-guid-1c142120-7fff-1b35-7b66-af56937af371
```
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=neutrino
lnd.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
```
3. start lnd `./lnd` from the directory where it has been unpacked

### Expected behaviour

LND started successfully.

### Actual behaviour

Getting error
```
failed to load config: /home/jan/.lnd/lnd.conf:4: unknown option: lnd.feeurl
```

**Comment by alexbosworth** [comment]
try using sections like in https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf

**Comment by saubyk** [comment]
change `lnd.feeurl` to just `feeurl` and retry

**Comment by jangorecki** [comment]
does the job, looks like documentation is out of sync then

**Comment by saubyk** [comment]
hi @jangorecki documentation seems to be fine. `lnd.feeurl` is the setting for `lit.conf` not `lnd.conf`
Can you point to the document you are referring to?

**Comment by saubyk** [comment]
never mind, just saw that you linked the document above.

**Comment by saubyk** [comment]
cc: @Liongrass

**Comment by Liongrass** [comment]
Thanks for the notice! This has been corrected in the guides!
