### ISSUE TITLE
[bug]: LND lockup on restart 

### ISSUE THREAD

**Issue by mmbbee** [lightningnetwork/lnd#7866]
### Background

Following up from [this comment](https://github.com/lightningnetwork/lnd/pull/7856#issuecomment-1660001885) 

After successful upgrade to v0.16.4 we, we saw issue https://github.com/lightningnetwork/lnd/issues/7853 and wanted to apply that patch to avoid that edge case. We applied [this patch](https://github.com/lightningnetwork/lnd/files/12237321/0001-peer-disconnect.patch) to v0.16.4 and redeployed

Upon restart, lnd made it through db loading and started to re-init connections, but eventually go locked up so that no cli/api commands were returning and the only logs were `Can't accept connection: unable to accept connection from X.X.X.X EOF`

Kill signal sent to LND was received (logged), but lnd was unable to gracefully shutdown, so it had to be force killed.

Restarting from base v0.16.4 (non-patched), it was able to successfully startup again. 

From original comment
> While we're here: is the node using tor? Also is this reproducible upon each start up?

Node is not using tor. Not sure if reproducible. I tested the patched lnd version on regtest / testnet without issue, but node has significantly less peers on these setups. Was weary to try to reproduce on production because we had to force kill LND the first time, and I am scared of causing db corruption. 

Full logs have been DM'd to LL team.

### Your environment

lnd v0.16.4 patched with https://github.com/lightningnetwork/lnd/pull/7856 
bitcoind v25.0.0
running on linux inside docker with phusion base image

**Comment by Roasbeef** [comment]
Was this persistent? In other words, did a restart resolve this, or does the node enter this stage each time?

**Comment by Roasbeef** [comment]
We have a candidate fix here: https://github.com/lightningnetwork/lnd/issues/7928
