### ISSUE TITLE
[bug]: Force closes for commitment not revoked, probable SQLite management issue

### ISSUE THREAD

**Issue by KnockOnWoodNode** [lightningnetwork/lnd#7869]
### Background

This is but the last occurrence of the issue, but the only one where the peer sent out a logs snippet.
I am constantly online, lnd runs on a beefy 64GB ECC Xeon server with OpenZFS mirrored partition across 6 SSD's.
`payments-expiration-grace-period=110000h` in lnd.conf
My rebalance script, using rebalance-lnd as backend, is firing away, limited only to one outgoing htlc for each channel (won't even start if there are other pending outgoing htlcs on the same channel).
Peer will publish a unilateral close on me.

For what is worth, this is my second node, and it basically works just the same as my previous one, lnd.conf is the same except the alias and color, I added `max-channel-fee-allocation=1` as suggested by Ziggie, and only other differences from my previous node are SQLite backend instead of postgres, cltv set to 210 instead of 144, and a MUCH beefier hardware vs an old laptop. Another difference is that I never got FCs like these on previous node. Noteworthy, I had disabled rebalances altogether on the old node during the april and may mempool madness, and never resumed it, but up until march I was rebalancing like crazy there as well.

Relevant logs from peer:
```
[ERR] HSWC: ChannelLink(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): failing link: ChannelPoint(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): unable to accept new commitment: not enough HTLC signatures with error: invalid commitment
[ERR] HSWC: ChannelLink(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): link failed, exiting htlcManager
[INF] HSWC: ChannelLink(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): exited
[INF] HSWC: ChannelLink(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): stopping
[INF] HSWC: Removing channel link with ChannelID(c8a649baf5e88cfc0f36c6d247bb0c2f278f84f063e95ce43a28e6a9eef2602c)
[WRN] PEER: Peer(039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1): Force closing link(799966:2401:0)
[INF] CNCT: Attempting to force close ChannelPoint(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0)
[INF] NANN: Announcing channel(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0) disabled [requested]
[INF] CNCT: ChannelArbitrator(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): force closing chan
```

FC tx: db847d85d362835c6ade2eb5f9d10f909f702e481d721b4e6432e75e9c482566

The 9_504 output should correlate to a 9_500 outgoing rebalance htlc started about 40 minutes before the FC, which probably had a 4sat routing fee, at least that's what I find in my rebalance script log.

### Your environment

* version of `lnd` 0.16.4
* which operating system (`uname -a` on *Nix)  5.10.0-23-amd64 #1 SMP Debian 5.10.179-2 (2023-07-14) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend  bitcoind
* any other relevant environment details SQLite backend

### Steps to reproduce

Dunno... have my node, rebalance?

### Expected behaviour

Not getting FC by peer

### Actual behaviour

Getting FC by peer.

**Comment by KnockOnWoodNode** [comment]
On a side note, please suggest the loglevel to be set for having the most granular information available about force closes. I had
`debuglevel=CNCT=debug,CRTR=debug,HSWC=debug,NTFN=debug,RPCS=debug,CHDB=debug`
on previous node, but I reverted to just `info` on this one as logs will be unreadable otherwise, plus will take GBs of space for a week.

**Comment by KnockOnWoodNode** [comment]
Addon details: all FCs included at least one pending htlcs, and none of them were near expiry, plus I have valid reason to suspect all of them were my own rebalances going out of the same channel, I didn't have the chance to verify all, but those that I could, had a FC onchain output equal to rebalance amt + floor(fee).
One peer on eclair also FCed on me, and they said they got an invalided revocation error on their side.
Looks like my node is sending out garbage commitment data to peers for some reason? SQLite is the cause?

**Comment by KnockOnWoodNode** [comment]
Got another log, referring to this FC:
24f94a6aaa2198f02f83de9272d1243e803c56176b649f24083399e58f5c6a7f
```
[DBG] PEER: Peer(039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1): Received UpdateAddHTLC(chan_id=71f0f5de08907a225c0614a354ddea23dc913bfbd82edc8428310b87cb14e54b, id=1578, amt=20323012 mSAT, expiry=801977, hash=3903128d660f7fe6a572489c673d7cd83740da4441902d3d9c707bd6e47cd219) from 039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1@51.254.98.177:9735
[DBG] PEER: Peer(039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1): Received CommitSig(chan_id=71f0f5de08907a225c0614a354ddea23dc913bfbd82edc8428310b87cb14e54b, num_htlcs=1) from 039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1@51.254.98.177:9735
[WRN] PEER: Peer(039e05e271f537cfa1c060d2364b960b85bd509ac89bae524e4a01948a07b3e8d1): Force closing link(799633:1003:1)
```
but I had prompted peer to grep for my pubkey instead of channel point, so this is probably useless...

**Comment by KnockOnWoodNode** [comment]
zgrepping for `SQLITE_BUSY` returns a LOT of results. Is this normal in any way? Doesn't lnd use wal for the sqlite database, and isn't it the only process accessing the database for writes anyway? why should the database be busy at all?

**Comment by KnockOnWoodNode** [comment]
This in particular:
`[ERR] HSWC: ChannelLink(2c60f2eea9e6283ae45ce963f0848f272f0cbb47d2c6360ffc8ce8f5ba49a6c8:0): unable to revoke commitment: database is locked (5) (SQLITE_BUSY)`
relating to the channel that got FCed 36 minutes later.... is SQLite implementation experimental? Why isn't there a big red warning sign about this?

**Comment by GeorgeTsagk** [comment]
> For what is worth, this is my second node,

Just to make sure: Is the beefy setup corresponding to a fresh node or did you migrate your old node to this new machine?

**Comment by KnockOnWoodNode** [comment]
> > For what is worth, this is my second node,
> 
> Just to make sure: Is the beefy setup corresponding to a fresh node or did you migrate your old node to this new machine?

new node, you probably missed how the SQLite backend is a new thing on this node, and I couldn't have migrated.

But I guess dumping postgres and importing into SQLite, or vice-versa, could also work as a migration.

**Comment by GeorgeTsagk** [comment]
So when you stop rebalancing you also stop noticing FCs?

Did you notice any other issues like payments failing or causing FCs themselves?

Also could you try using `bos rebalance` and see if it also causes an FC?

**Comment by ziggie1984** [comment]
I analysed the problem (I guess at least 😅).

The main problem is that in his case lnd fails before it sends the revocation to the peer But advances the local chain which generates the main problem which manifests later in an FC, as soon as he tries to add another HTLC to the Channel (outgoing from his view). I was able to reproduce it on regtest.

So his setup fails here:
https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L1969-L1973. The database does not allow an access in `RevokeCurrentCommitment`(https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L4869)

Now imagine the database error happend when trying to revoke an UpdateFailHTLC msg. Lets say we run into this timeout error so the revocation is not sent to the peer. Because we advanced the state prior to this error (https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L4856). Now when we are trying to add a new HTLC to the Channel we will include everything from the `RemoteUpdateLog` until the index of the `localchain.theirMessageIndex` and this includes the removal of the HTLC which we never acked. (So we basically increased the remote index up to which we include updates when signing the new Commitment Tx) This can be seen here:
https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3792

Testing some solutions now, but maybe we should just advance the localchain after the revocation msg was sent out?

**Comment by Roasbeef** [comment]
Re `SQLITE_BUSY`, the current logic just sets a value, but then doesn't actually try re-execute the transaction before reporting the error back to the caller. The new SQL scaffolding we have prepped for the upcoming SQL invoice schema introduction properly attempts to retry once we get a busy error: https://github.com/lightningnetwork/lnd/blob/bf5aab9d5246daede3f499af880a5d7be6c6ee88/sqldb/interfaces.go#L219-L231. We should unify the abstractions here so we can have all the serialization error retries in a single place.

**Comment by ziggie1984** [comment]
> DB handling aside, I think the root issue here is that any db failure (w.r.t operations) should trigger a tear down of the link, similar to stalled commitments. If the logic halts there and doesn't proceed (rn it'll continue with that unclean state), then I think the issue here would've been averted all together.

Really good idea, I think we should split the fix into 2 PR then? The one failing the channel with an error so the link is inactive and a channel reestablishment can recover the state (smaller fix), and the db retries in another ?

Regarding the failing of the channel, wondering if we should send a warning to the peer:

The spec mostly states this when there are problems advancing the state:

```
MAY send a warning and close the connection, or send an error and fail the channel
```

In the above case, where we were not able to access the DB and continued with an unclean state, we could maybe send a warning to the peer so that he closes the connection and we could recover the channel during a channel-reestablishment cycle? 
I think LND currently only sends either an Error Msg or does just fail the channel without sending and error:
https://github.com/lightningnetwork/lnd/blob/master/peer/brontide.go#L3038

Wondering if it makes sense to add the function where we send out a warning msg or should we proceed with the current architecture, so in the above case failing the link but not sending an error to our peer so that we do not risk an FC?

**Comment by bigdaddy77x** [comment]
details: all FCs included at least one pending htlc, and none of them were near expiry, plus I have valid reason to suspect all of them were my own rebalances going out of the same channel, I didn't have the chance to verify all, but those that I could, had a FC onchain output equal to rebalance amt + floor(offchain fee).
One peer on eclair also FCed on me, and they said they got an "invalided revocation" error on their side.
Looks like my node is sending out garbage commitment data to peers for some reason? Is SQLite the cause

**Comment by KnockOnWoodNode** [comment]
> details: all FCs included at least one pending htlc, and none of them were near expiry, plus I have valid reason to suspect all of them were my own rebalances going out of the same channel, I didn't have the chance to verify all, but those that I could, had a FC onchain output equal to rebalance amt + floor(offchain fee). One peer on eclair also FCed on me, and they said they got an "invalided revocation" error on their side. Looks like my node is sending out garbage commitment data to peers for some reason? Is SQLite the cause

What are you cloning my posts for?


In any case, been more than a week and after increasing BUSY_TIMEOUT (first to 1m, then 10m) I got no more timeout errors not FCs, KNOCK ON WOOD, and the node is much busier than before.

**Comment by bigdaddy77x** [comment]
I really need help

**Comment by bigdaddy77x** [comment]
Hello

**Comment by KnockOnWoodNode** [comment]
Just to update on this, my sqlite timeout in conf is set to probably 10m, and since there no more sqlite busy errors ever appeared, and I've been pushing many rebalances and constantly have upwards of 10 pending htlcs.

**Comment by saubyk** [comment]
> Just to update on this, my sqlite timeout in conf is set to probably 10m, and since then no more sqlite busy errors ever appeared, and I've been pushing many rebalances and constantly have upwards of 10 pending htlcs.

Are you running the 0.17 rc2 or still on 16.4?

**Comment by KnockOnWoodNode** [comment]
> > Just to update on this, my sqlite timeout in conf is set to probably 10m, and since then no more sqlite busy errors ever appeared, and I've been pushing many rebalances and constantly have upwards of 10 pending htlcs.
> 
> Are you running the 0.17 rc2 or still on 16.4?

0.16.4, I don't do rc's and even for proper releases I wait a few weeks before other runners do not report any issues
