### ISSUE TITLE
Naming mismatch between ListInvoice and DecodePayReq

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#789]
I noticed ListInvoices has a field creation_date while DecodePayReq has a field timestamp. Unless I'm mistaken, these represent the same thing. 

I'd recommend updating DecodePayReq to list creation_date. It is more detailed than timestamp. 

Steps to Repeat
lncli addinvoice 1
lncli listinvoices
lncli decodePayReq (of the most recent invoice)
Observe the differing field names with matching values.

**Comment by Roasbeef** [comment]
A payreq is an encoded invoice. The `timestamp` field is used as part of `BOLT11` as we'll use this to compute if it's been expired or not.
