### ISSUE TITLE
[bug]: received cancel resolution for (Chan ID=108:1:0, HTLC ID=0) with outcome: invoice not found

### ISSUE THREAD

**Issue by Christewart** [lightningnetwork/lnd#7890]
### Background

[I'm upgrading the `lnd` dependency on bitcoin-s from `0.16.0` -> `0.16.4`](https://github.com/bitcoin-s/bitcoin-s/pull/5194)

[These test cases are failing with the upgrade to `0.16.1`](https://github.com/bitcoin-s/bitcoin-s/blob/1d1af1d52e05c2c4e4a82d536cba4ff42748fe86/lnd-rpc-test/src/test/scala/org/bitcoins/lnd/rpc/LndRpcClientPairTest.scala#L387C1-L387C1) (and also fail on `0.16.2`, `0.16.3`, `0.16.4`), but pass on 0.16.0.

The unit test is simple, Bob is paying Alice directly through a channel. There is no hops, Alice and Bob are directly connected.

### Your environment

* version of `lnd` `0.16.1`
* which operating system `Darwin chris 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64`
* `bitcoind`

### Steps to reproduce

Clone the repo and run `sbt 'lndRpcTest/testOnly *LndRpcClientPairTest* -- -z "probe and pay"'`

### Expected behaviour

Test should pass, payment should complete.

### Actual behaviour

It appears that I fail to add the invoice to `Alice`'s node. I believe it is related to this on the release notes for `0.16.1`

>[The default CLTV delta delay has increased from 40 blocks to 80 blocks.](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.16.1.md) (#7609)

I add the invoice on Alice's node

>2023-08-13 09:22:12.975 [DBG] INVC: Invoice(pay_hash=443c9abe2520e486a094d9710ef0648dba89e9d00e036f1dc2da901e722d1a9b): added with terms amt=1000000 mSAT, expiry=24h0m0s, final_cltv_delta=80

And then I see this log 

>2023-08-13 09:22:14.188 [DBG] INVC: Invoice(pay_hash=443c9abe2520e486a094d9710ef0648dba89e9d00e036f1dc2da901e722d1a9b, pay_addr=57e9edf9eef31a2da545f9876981895dcfb2db49d68fc4bb67f690a966f62b53): failure resolution result outcome: expiry too soon, at accept height: 113, amt=1000000 mSAT, expiry=153, circuit=(Chan ID=108:1:0, HTLC ID=1), mpp=total=1000000 mSAT, addr=57e9edf9eef31a2da545f9876981895dcfb2db49d68fc4bb67f690a966f62b53, amp=<nil>, metadata=<nil>

It seems like the `expiry` (`expiry=153`) is not what i'm expecting it to be? I'm assuming that `expiry` is `cltv_expiry`, which is set to `final_cltv_delta=80` in the line before? 

Ultimately, the payment fails from Bob's perspective with this error

>2023-08-13 09:22:13.699 [WRN] CRTR: Attempt 1 for payment c56d4ac4d594d4e5bbdfbd44070617eb9f519b0383e516993f5d561573aa3c13 failed: IncorrectOrUnknownPaymentDetails(amt=1000000 mSAT, height=113)@1

Logs attached below

[alice-lnd.log](https://github.com/lightningnetwork/lnd/files/12329711/alice-lnd.log)
[bob-lnd.log](https://github.com/lightningnetwork/lnd/files/12329714/bob-lnd.log)

**Comment by alexbosworth** [comment]
try increasing the cltv delta

**Comment by Christewart** [comment]
> try increasing the cltv delta

I've tried values `0`, `8`, `80`, and `800`. None of them work.

The interesting thing is the parameters (AFAICT) do not seem to get reflected consistenlty in the internal lnd logs. Its acknowledged on the invoice line 

>2023-08-13 09:22:12.975 [DBG] INVC: Invoice(pay_hash=443c9abe2520e486a094d9710ef0648dba89e9d00e036f1dc2da901e722d1a9b): added with terms amt=1000000 mSAT, expiry=24h0m0s, **final_cltv_delta=80**

but not acknowledged on this line: 

>expiry too soon, at accept height: 113, amt=1000000 mSAT, **expiry=153**, circuit=(Chan ID=108:1:0, HTLC ID=1), mpp=total=1000000 mSAT,

**Comment by alexbosworth** [comment]
maybe it's a delta internal to the route, so the wrong one is being increased? generally too-high expiries will be accepted but too-low will be rejected

**Comment by Christewart** [comment]
> maybe it's a delta internal to the route, so the wrong one is being increased? generally too-high expiries will be accepted but too-low will be rejected

Does this make sense if the route is just `Alice <-> Bob` ?

**Comment by ziggie1984** [comment]
https://github.com/bitcoin-s/bitcoin-s/blob/e423de01e11b7d0f2e962166a20fb897a47e5229/lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/internal/LndRouterClient.scala#L39 

seems like you are using 40 for your queryroute request ?

**Comment by Christewart** [comment]
> 

Your correct. Thank you.
