### ISSUE TITLE
[bug]: Lost of funds? 

### ISSUE THREAD

**Issue by talvasconcelos** [lightningnetwork/lnd#7892]
### Background

I opened a channel from CLN to LND (both my nodes) and pushed 50% to LND. Channel got force closed, don't know why! The CLN node got it's part of the funds back but LND doesn't even show the channel! There's 5M sats lost somewhere that i can't get back. 

### Your environment

I'm on 16.4 now, but was going back and forward between 16.2 and 16.3 at the time (maybe something got screwed with this)
Raspiblitz (debian)
bitcoin core 0.25

### Steps to reproduce

Can't really tell...

### Expected behaviour

After the FC, LND should have got the funds on it's side of the channel...

### Actual behaviour

Funds are nowhere to be seen....

Here's the funding tx: `4002af6f6495541f447362f3c550f9bc9d1904240c19a9a8a603818a05d38a20`

And the closing tx: `8278cc1f2db87552db568503bacd0fdca4a149e20da3c6d1b36253fe8dfa6c77`

**Comment by guggero** [comment]
From `lncli openchannel --help`:

```
--push_amt value                         the number of satoshis to give the remote side as part of the initial commitment state, this is equivalent to first opening a channel and sending the remote party funds, but done all in one step (default: 0)
```

So basically you donated 5 million sats to the other side... The only thing you can do is try to contact the remote peer and tell them your mistake. And hope they give you back the 5 million sats.

**Comment by guggero** [comment]
Can you print the state of `lncli pendingchannels`?

**Comment by talvasconcelos** [comment]
> Can you print the state of `lncli pendingchannels`?

It's empty...

**Comment by guggero** [comment]
Does the channel appear in either `lncli closedchannels` or `lncli listchannels`? Did you ever use the `lncli abandonchannel` command? Or did you move/delete/rename any files on RaspiBlitz during the migration? Could it be that your `channel.db` file wasn't restored/migrated properly? E.g. do you have _any_ channels left on the node?

Either way, you can use the [`chantools sweepremoteclosed`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_sweepremoteclosed.md) command to get the funds back. But it would be interesting to find out why `lnd` didn't pick them up automatically.

**Comment by talvasconcelos** [comment]
Neither closedchannels or listchannels show the actual channel. Never used abandonchannel...

I'll take chantools a go... `chantools sweepremoteclosed --publish --sweepaddr <a new addr from the node>` ?

Yes i'd like to know why it happened, i suspect the "downgrade" from 16.3 to 16.2 and Blitz's freezes on 1.9 (and 1.10 BTW) may have caused some corruption.

**Comment by guggero** [comment]
Yes, `--sweepaddr` is where the funds should go to, so usually a new address.

See my question about any channels still being there. An unexpected force close could also mean you accidentally used an old version of the `channel.db` file. Did you restore any manually created file based backup?

**Comment by talvasconcelos** [comment]
No manual restore. But probably it got screwed in the process....

**Comment by talvasconcelos** [comment]
Oh man, you're a life saver... chantools found the utxo, it's already published and showing on the node! 

Thank you so much!
