### ISSUE TITLE
incorrect use of p2wkh weight

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#7893]
Should be p2tr weight since we only make p2tr outputs. This won't lead us to create invalid sweep transactions but isn't correct:

https://github.com/lightningnetwork/lnd/blob/b565f4f5366dfaecfdcc5d7d682fd8bd6307226f/sweep/tx_input_set.go#L77-L79

**Comment by yyforyongyu** [comment]
When fixing this issue we should also update`DustLimitForSize` to include `P2TRSize` here,
https://github.com/lightningnetwork/lnd/blob/13568fd5b09435f8254a91527996091bef30996e/lnwallet/parameters.go#L56-L58

Atm it won't create any errors, when seeing an `input.P2TRSize` it will implicitly go to `input.P2WSHSize`. We should fix it tho as it looks confusing.

**Comment by Crypt-iQ** [comment]
I dont think we can have two identical cases, maybe a comment that says that p2tr and p2wsh are equal
