### ISSUE TITLE
[bug]: unable to close channel: rpc error: code = Unknown desc = link failed to shutdown

### ISSUE THREAD

**Issue by Silarous** [lightningnetwork/lnd#7903]
### Background

I am attempting to close my last channel on this node and when I enter "lncli closechannel" or "lncli closeallchannels" it produces the error 

"unable to close channel: rpc error: code = Unknown desc = link failed to shutdown"

I've closed all my other channels on this node without issue.  This is the last one.  The channel is listed as active in both RTL and when I run "lncli listchannels".  This channel is over 3 years old.

### Your environment

* LND 0.16.1-beta commit=v0.16.1-beta
* Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
* Bitcoin Core RPC client version v24.0.0

### Steps to reproduce

lncli closechannel
lncli closeallchannels

### Expected behaviour

Close the channel

### Actual behaviour

Produces the error "unable to close channel: rpc error: code = Unknown desc = link failed to shutdown"

**Comment by Roasbeef** [comment]
You may need to force close the channel, what do you see in the logs when you try to do a co-op close?

**Comment by Crypt-iQ** [comment]
you have outstanding updates on your commitment tx, this should be fixed with #6039
