### ISSUE TITLE
[Public capacity error in LNDg]: 

### ISSUE THREAD

**Issue by amtexugo** [lightningnetwork/lnd#7913]
Background MY NODE
https://amboss.space/node/022db2e3a531bb8f85d258c134ba013b7d17bc04d6984efebf9c1f0f63e9c0f596

Hello friends!
There was an error in the public capacity of my channel. See in LND it is 10 million and in Amboss is 79 million which is correct. What could have happened?...Thank you

Your environment

https://user-images.githubusercontent.com/127704297/262739986-6cb827e1-696d-47e6-a85a-313d99edadd2.jpg

SETUP 
    LNDg v1.7.0`
    RASPIOS 4 UMBREL
    Bitcoin Core 25.0.0
    LND 0.16.4-beta
 
thanks

**Comment by hieblmi** [comment]
Hi, 79 million is the capacity (sum of all public channels) of your node - 10 million is likely the capacity of one of your channels.

**Comment by amtexugo** [comment]
Sorry bro, the correcto print is this: https://user-images.githubusercontent.com/127704297/262739986-6cb827e1-696d-47e6-a85a-313d99edadd2.jpg

**Comment by guggero** [comment]
This seems to be a screenshot of `LNDg`. This is the `lnd` repo. Try here: https://github.com/cryptosharks131/lndg.
