### ISSUE TITLE
[feature]: support multiple outgoing channel IDs in lncli

### ISSUE THREAD

**Issue by The34Goon** [lightningnetwork/lnd#7915]
**I want to pay an invoice using either all channels except A B C or define them X Y Z**

lncli payinvoice --timeout 20m --fee_limit 35 --outgoing_chan_id XXX YYY ZZZ --pay_req
**results in only XXX being used.**

lncli payinvoice --timeout 20m --fee_limit 35 —outgoing_chan_id XXX —outgoing_chan_id YYY —outgoing_chan_id ZZZ --pay_req
**results in only ZZZ being used.**

response when using the **--outgoing_chan_ids** flag [described in api-docs ](https://lightning.engineering/api-docs/api/lnd/router/send-payment#routerrpcsendpaymentrequest)
_[lncli] flag provided but not defined: -outgoing_chan_ids_

LND_0.16.4-beta

what am I missing?

**Comment by alexbosworth** [comment]
The API docs don't describe LNCLI, they describe the API that LNCLI uses

**Comment by markettes** [comment]
May I take this one?

**Comment by markettes** [comment]
By the way, for the query routes call, I would say we need to change it to accept the same as the payment, an array of strings for the outgoing_chan_id.

**Comment by saubyk** [comment]
reopening as the pr is not merged yet
