### ISSUE TITLE
[bug]: PSBT funding for SIMPLE_TAPROOT channels returns inconsistent funding address

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#7929]
### Background

When using the PSBT shim in the OpenChannel API, an invalid address is returned for the funding address. Because these are inconsistent, sending to one would suggest chain funds potentially getting stuck

### Your environment

- lnd v0.17.0 RC1

### Steps to reproduce

- Use the OpenChannel API with the PSBT shim
- Look at the result of `psbt_fund` which will return `funding_address` and `psbt`

### Expected behavior

- The `funding_address` and `psbt` internally should reflect an identical address to fund for the channel
- This address should be a P2TR address

### Actual behavior

- `funding_address` returns a V0 segwit address
- `psbt` contains a V1 P2TR address

Example output:

- `funding_address`: `bcrt1q0dz5fktjdemgf04nvla3fxdcye5pwuk5pt0wznudc0mmvrcr4c3q5m7g7h`
- `psbt`: `cHNidP8BADUCAAAAAAFAQg8AAAAAACJRIB3p6kApstllpoGVEYAa6VuHM/H8bqdQa7gm+D4+ac8TAAAAAAAA`

**Comment by guggero** [comment]
Found the issue, working on a fix.
