### ISSUE TITLE
build: remove usage of glide and switch over to dep 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#794]
`glide`, which we currently use for dependency management is no longer being actively developed. Instead, a new tool called `dep` is the current candidate for the "official" build system for: https://github.com/golang/dep. 

All around, `dep` seems to be a superior, easier to use tool for dependency management. As a result, we should switch over to `dep` and abandon `glide`. 

## Steps To Completion 

- [ ] Remove old glide files

- [ ] Add new dep configuration files 

- [ ] Update the travis build to use dep properly 

- [ ] Update `gotest.sh` to use dep properly

**Comment by wilmerpaulino** [comment]
I’ll pick this up 👍

**Comment by PaulCapestany** [comment]
For whomever may not have been closely following the whole Go packaging/vendoring/dependency situation, a few weeks ago there was a bit of a big kerfluffle about some folks from the Go team releasing their own dep-ish tool, [vgo](https://github.com/golang/go/wiki/vgo)

**Comment by Roasbeef** [comment]
vgo requires Go 1.10+

**Comment by Roasbeef** [comment]
It's also still experimental at this point (literally a few weeks old)
