### ISSUE TITLE
[bug]: Wrong documentation on lncli

### ISSUE THREAD

**Issue by FeatureSpitter** [lightningnetwork/lnd#7946]
The following is the closechannel command help/hint:

> $ lncli1 closechannel
>    NAME:
>       lncli closechannel - Close an existing channel.
> 
>    USAGE:
>       **lncli closechannel [command options] funding_txid [output_index]**
> 
>    CATEGORY:
>       Channels
> 
>    DESCRIPTION:
> 
>    Close an existing channel. The channel can be closed either cooperatively,
>    or unilaterally (--force).
> 
>    A unilateral channel closure means that the latest commitment
>    transaction will be broadcast to the network. As a result, any settled
>    funds will be time locked for a few blocks before they can be spent.
> 
>    In the case of a cooperative closure, one can manually set the fee to
>    be used for the closing transaction via either the --conf_target or
>    --sat_per_vbyte arguments. This will be the starting value used during
>    fee negotiation. This is optional.
> 
>    In the case of a cooperative closure, one can manually set the address
>    to deliver funds to upon closure. This is optional, and may only be used
>    if an upfront shutdown address has not already been set. If neither are
>    set the funds will be delivered to a new wallet address.
> 
>    To view which funding_txids/output_indexes can be used for a channel close,
>    see the channel_point values within the listchannels command output.
>    The format for a channel_point is 'funding_txid:output_index'.
> 
>    OPTIONS:
>       --funding_txid value   the txid of the channel's funding transaction
>       --output_index value   the output index for the funding output of the funding transaction (default: 0)
>       --chan_point value     (optional) the channel point. If set, funding_txid and output_index flags and positional arguments will be ignored
>       --force                attempt an uncooperative closure
>       --block                block until the channel is closed
>       --conf_target value    (optional) the number of blocks that the transaction *should* confirm in, will be used for fee estimation. If not set, then the conf-target value set in the main lnd config will be used. (default: 0)
>       --sat_per_vbyte value  (optional) a manual fee expressed in sat/vbyte that should be used when crafting the transaction (default: 0)
>       --delivery_addr value  (optional) an address to deliver funds upon cooperative channel closing, may only be used if an upfront shutdown address is not already set

So, you state that `lncli closechannel [command options] funding_txid [output_index]` is enough to close the channel.

Thus for the channel:
```
$ lncli1 listchannels
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266",
            "channel_point": "baaa90fd4e6912b1137ce5d3c5255549a3f8f793b91480c207a661967ff20e75:1",
            "chan_id": "885928195586654209",
            "capacity": "269874",
(...)
```
`baaa90fd4e6912b1137ce5d3c5255549a3f8f793b91480c207a661967ff20e75` should be enough of an argument to close it, correct?

However...
```
$ lncli1 closechannel baaa90fd4e6912b1137ce5d3c5255549a3f8f793b91480c207a661967ff20e75 --sat_per_vbyte 15
[lncli] rpc error: code = Unknown desc = channel not found
```

But, if I write the output index:
```
$ lncli1 closechannel baaa90fd4e6912b1137ce5d3c5255549a3f8f793b91480c207a661967ff20e75 1 --sat_per_vbyte 15
```

Then the close operation flows as expected.

This means that the documentation should state:
`lncli closechannel [command options] funding_txid output_index`
Instead of
`lncli closechannel [command options] funding_txid [output_index]` (notice the optionality **[** **]**).

Still, I would make this command friendlier. If you call it `funding_txid` in one place, you should call it that everywhere else for consistency. The same with `output_index`.

I hope this helps improving UX.

**Comment by catatonist** [comment]
Should not [command options] be placed before funding_txid? Is order of arguments free to choose?

**Comment by feelancer21** [comment]
Default for output_index is 0, but yours was 1. If you use the default the output_index should be optional.

**Comment by mohamedawnallah** [comment]
I'd like to work on this issue!

**Comment by mohamedawnallah** [comment]
I'd like to work on this issue, Thanks!

**Comment by mani2310** [comment]
@FeatureSpitter I have raised PR to fix this, can someone from the team please review this : https://github.com/lightningnetwork/lnd/pull/8339

**Comment by ziggie1984** [comment]
closed with: https://github.com/lightningnetwork/lnd/pull/8339
