### ISSUE TITLE
SSL problem with grpc when connecting from node.js

### ISSUE THREAD

**Issue by Metalsprzet** [lightningnetwork/lnd#795]
After upgrade lnd we have problem with connect from node.js by gprc.

New tls.cert and tls.key was generated ( we delete old ones before run lnd after update ) 

Error  3261 ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.

Part of code in node.js: ( which work before lnd update )

const lndCert 			= fs.readFileSync("/home/administrator/.lnd/tls.cert")
const credentials 		= grpc.credentials.createSsl(lndCert)
const lnrpcDescriptor 	= grpc.load("rpc.proto")
const lnrpc 			= lnrpcDescriptor.lnrpc

var metadata = new grpc.Metadata();
const macaroonHex = fs.readFileSync("/home/administrator/.lnd/admin.macaroon").toString("hex");
metadata.add('macaroon', macaroonHex);

const macaroonCreds = grpc.credentials.createFromMetadataGenerator((params, callback) =>
    callback(null, metadata)
)

const creds = grpc.credentials.combineChannelCredentials(credentials, macaroonCreds);

const lightning = new lnrpc.Lightning('localhost:10009', creds)

**Comment by vegardengen** [comment]
I have the same problem from python.

**Comment by Metalsprzet** [comment]
I decoded certificate for see more

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            84:c6:..........................
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=lnd autogenerated cert, CN=ubuntu
        Validity
            Not Before: Feb 28 16:28:11 2018 GMT
            Not After : Apr 25 16:28:11 2019 GMT
        Subject: O=lnd autogenerated cert, CN=ubuntu
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:7b:ff:05..........
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Alternative Name:
                DNS:ubuntu, DNS:localhost, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:192.168.0.40, IP Address......
    Signature Algorithm: ecdsa-with-SHA256
         30:44:...

**Comment by Metalsprzet** [comment]
I add 
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
process.env.GRPC_SSL_CIPHER_SUITES = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384"

At it works 
Bezpol helps

**Comment by lobsterpub** [comment]
I'm having this issue with Python, Care to elaborate on your fix @Metalsprzet  ?

**Comment by dabura667** [comment]
```python
import os
os.environ['GRPC_SSL_CIPHER_SUITES'] = 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384'
```
Or the easier to read version
```python
import os
os.environ['GRPC_SSL_CIPHER_SUITES'] = '' + \
    '' + \
    'ECDHE-RSA-AES128-GCM-SHA256:' + \
    'ECDHE-RSA-AES128-SHA256:' + \
    'ECDHE-RSA-AES256-SHA384:' + \
    'ECDHE-RSA-AES256-GCM-SHA384:' + \
    'ECDHE-ECDSA-AES128-GCM-SHA256:' + \
    'ECDHE-ECDSA-AES128-SHA256:' + \
    'ECDHE-ECDSA-AES256-SHA384:' + \
    'ECDHE-ECDSA-AES256-GCM-SHA384'
```
You're telling GRPC (via env variables) which algorithms to use for SSL.

**Comment by lobsterpub** [comment]
Awesome, works. Thanks!

Is this going to be 'fixed' in the future? or are we going to need to import the cipher's every time?
