### ISSUE TITLE
[bug]: sweeper (bumpfee) creates invalid transaction (not paying higher fees when necessary)

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7972]
### Background

The sweeper creates a combined sweep transaction, using another pending sweep transaction's input as an input, without raising the fee rate. The resulting combined transaction cannot be broadcast because of that.

### Your environment

* version of lnd: 0.16.4
* which operating system (uname -a on *Nix): Linux server 6.1.0-11-amd64 #<i></i>1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
* version of btcd, bitcoind, or other backend: bitcoind v25

### Steps to reproduce

Run bumpfee for input A and 15 sat/vByte, resulting in a sweep transaction paying 15 sat/vByte.
Wait for the sweep transaction to broadcast.
Run bumpfee for input B and 15 sat/vByte before the sweep for input A is confirmed.

### Expected behaviour

Input A is not used as an input for the sweep transaction for input B.

### Actual behaviour

It is used, resulting in an error:
```
2023-09-10 11:59:22.323 [INF] SWPR: Creating sweep transaction xxx for 2 inputs (xxx:0 (CommitmentAnchor), xxx:0 (CommitmentAnchor)) using 253 sat/kw, tx_weight=774, tx_fee=0.00000195 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2023-09-10 11:59:22.333 [ERR] BTCN: Broadcast attempt failed: -26: insufficient fee, rejecting replacement xxx; new feerate 0.00001010 BTC/kvB <= old feerate 0.00004508 BTC/kvB
2023-09-10 11:59:22.337 [INF] LNWL: Inserting unconfirmed transaction xxx
2023-09-10 11:59:22.345 [INF] LNWL: xxx: broadcast failed because of: unable to replace transaction: -26: insufficient fee, rejecting replacement xxx; new feerate 0.00001010 BTC/kvB <= old feerate 0.00004508 BTC/kvB
2023-09-10 11:59:22.353 [ERR] SWPR: Publish sweep tx xxx got error: transaction rejected: output already spent
```

**Comment by yyforyongyu** [comment]
Looks like it's the issue mentioned [here](https://github.com/lightningnetwork/lnd/pull/7965/files#diff-62d8801a847bb36337cf399070ea0615bcfdc5ea4ceb5ae5aa441869bd81862eR1233).

Do you also see the sweeping transaction for input B only being created?

**Comment by C-Otto** [comment]
I don't understand the question. I posted the logs, what exactly are you looking for?

**Comment by yyforyongyu** [comment]
Something like `[INF] SWPR: Creating sweep transaction xxx for 1 inputs...`. So I was wondering if there were two sweeping transactions being created - the first was the one shown above, and a second one which only contained input B.

**Comment by C-Otto** [comment]
Please have another look at my issue. The first transaction is unproblematic and ends up in the mempool. The second transaction is the one for which I showed the logs, including the resulting error. I still don't understand what kind of information is missing.

**Comment by C-Otto** [comment]
Ah. I think I understand what you're asking for, let me have a look.

**Comment by yyforyongyu** [comment]
So I think what's happening here is that we always create two input sets [here](https://github.com/lightningnetwork/lnd/blob/master/sweep/sweeper.go#L1222). Each of the input sets is used to create a sweeping transaction. This means,
1. when seeing input A, we'd create and publish a sweeping transaction using it.
2. before the above tx is confirmed, input B is received by the sweeper.
3. the sweeper will then create two transactions, tx1 has input B, tx2 has input A and input B.
4. tx2 is most likely to fail because of the RBF constraints.

The solution is,
1. stop creating transactions using the same input.
2. start tracking individual input's state to precisely control whether to sweep it or not.
