### ISSUE TITLE
[bug]: lnd not forgetting channel when opening canceled

### ISSUE THREAD

**Issue by daywalker90** [lightningnetwork/lnd#7982]
I tried opening channels with cln to lnd nodes and encountered this [bug ](https://github.com/ElementsProject/lightning/issues/6664) in cln where outputs>inputs and the tx was not broadcast.

I then canceled the openings from my side with cln's fundchannel_cancel  and from my side the channels were gone and everything was "back to 0".

However after another try i get "Number of pending channels exceed maximum" from some lnd nodes and apparently they have to run abandonchannel so i can open again. 

I expected that when i run fundchannel_cancel my node partners would do the same on their side.

**Comment by Roasbeef** [comment]
`fundchannel_cancel` sounds like a CLN specific command. By default `lnd` will hold onto that channel for a week or so, and only allows a small amount of pending channels per peer. If you want to get rid of that channel, you can run `lncli abandonchannel`.

**Comment by daywalker90** [comment]
Is it not in the lightning protocol that you can cancel a channel funding if the tx hasnt confirmed in a block? Also small amount seems to be 1. I have to potentially contact 16 peers so that they run abandonchannel or wait for a week.

**Comment by saubyk** [comment]
> Is it not in the lightning protocol that you can cancel a channel funding if the tx hasnt confirmed in a block?

As far as I am aware there is nothing of the sort in the protocol spec. If the transaction doesn't confirm, the only thing left to do is a cleanup of UTXO locks (if any), which each implementation can handle in its own way.

> I have to potentially contact 16 peers so that they run abandonchannel or wait for a week

You don't need to take any such action, as there is no economic impact to you or your peers in this case. It's their prerogative on how to handle this situation.

Closing this issue now, as there is not much else to add for us here.
