### ISSUE TITLE
[bug]: 0.17.0-rc3 doesn't start - "unable to start server: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss"

### ISSUE THREAD

**Issue by xmrk-btc** [lightningnetwork/lnd#7984]
### Background

Cannot start lnd after updating to 0.17.0-rc3 from rc2:
```
2023-09-13 21:50:34.964 [INF] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): starting state=S
tateBroadcastCommit, trigger=chainTrigger, triggerHeight=807528
2023-09-13 21:50:34.964 [INF] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): force closing chan
2023-09-13 21:50:35.595 [ERR] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): unable to force close: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss
2023-09-13 21:50:35.598 [ERR] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): unable to advance state: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss
2023-09-13 21:50:35.598 [INF] CNCT: ChainArbitrator shutting down


2023-09-13 21:50:35.624 [ERR] LTND: Shutting down because error in main method: unable to start server: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss

```

When I ran rc3 for the first time, it decided to force close said channel:
```
2023-09-13 21:05:53.924 [INF] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): starting state=StateBroadcastCommit, trigger=chainTrigger, triggerHeight=807526
2023-09-13 21:05:53.925 [INF] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): force closing chan
2023-09-13 21:05:54.003 [ERR] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): unable to force close: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss
2023-09-13 21:05:54.003 [ERR] CNCT: ChannelArbitrator(9f84ce15e40d08a15414cfe0ceb5b78e2d60b83ffcf1ffa4c995c89ffb556b5f:1): unable to advance state: cannot force close channel with state: ChanStatusBorked|ChanStatusLocalDataLoss

```

I didn't find logs of rc2 starting, nor more info about that channel. My logs only go back 2 days.

### Additional info
I had a kernel panic 2023-09-10, while running rc2, this seems to have caused some data loss and around 20 force closures.  (But this is surprising to me, I though the data would be flushed to disk before sending ACK to the peer.  At least one FC was caused by data loss,  my node having  update number x and peer claiming update number x+2 . )

I was running bitcoind with `permitbaremultisig=0` until today, I guess this could cause my fee estimates to be too low. (https://nitter.net/wtogami/status/1699484964721492016#m ) . Restarted today with `permitbaremultisig=1` and got this problem.

lnd 0.17.0-rc2 doesn't start either, gives similar error.

### Your environment

* version of `lnd`; 0.17.0-rc3
* which operating system (`uname -a` on *Nix): Linux ubuntu 5.15.0-1036-raspi 
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.25.0

### Steps to reproduce

Start lnd and wait... 

### Expected behaviour
lnd should start, perhaps ignoring the borked channel.

**Comment by Roasbeef** [comment]
> I had a kernel panic 2023-09-10, while running rc2, this seems to have caused some data loss and around 20 force closures. (But this is surprising to me, I though the data would be flushed to disk before sending ACK to the peer. At

That should be the case, as the databases always uses an `fdatasync` before returning to the caller. However, I'm not sure what effect a kernel panic would have on disk durability, and also lnd's operation if it happened _while_ `lnd` was running. In 0.17 we also fixed a case where the db would fail, but the peer link/connection wasn't properly torn down. 

Do you have logs before the force close decision? It should tell you _why_ it decided to do that. In this case I'm guessing an HTLC was close to timeout so it went on chain. We'll never go on chain ourselves if we think we lost data, instead we rly on the remote peer for that. It'll also say what the "trigger" was as well. 

The log you're seeing was put in place to ensure that if you _did_ actually lose data, then it wouldn't automatically try to force close (an unclean state, can result in loss of funds): https://github.com/lightningnetwork/lnd/blob/90effda090e752662500aa47eaed8b8619687e4e/lnwallet/channel.go#L7317-L7323

If you apply this patch, you should be able to start up again: 
```git
diff --git a/contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go
index ffd26e66a..06b737687 100644
--- a/contractcourt/chain_arbitrator.go
+++ b/contractcourt/chain_arbitrator.go
@@ -705,8 +705,9 @@ func (c *ChainArbitrator) Start() error {
 		}
 
 		if err := arbitrator.Start(startState); err != nil {
-			stopAndLog()
-			return err
+			log.Error("unable to ChannelArbitrator(%v): %v",
+				arbitrator.cfg.ChanPoint, err)
+			continue
 		}
 	}
 ```

We'll look into exactly what happened given the information presented. The shutdown here was a safety mechanism (don't want to continue if for w/e reason critical sub-systems can't start up). In your case, AFAICT, while the channel arb was still starting up, a peer connected, we realized it might be a data loss case, and then the db state was updated. Later on the channel arb finishes starting, then we realize a force close isn't possible.

**Comment by Roasbeef** [comment]
> When I ran rc3 for the first time, it decided to force close said channel:
> Cannot start lnd after updating to 0.17.0-rc3 from rc2:

Did you try to manually force close once you were on `rc3`? 

Looking at the logs again, it shows a `chainTrigger`, which means it went to chain in order to timeout an HTLC.

**Comment by Roasbeef** [comment]
I've prepared a candidate patch here: https://github.com/lightningnetwork/lnd/pull/7985

What I think most likely happened is:
  * We detect data loss, mark as borked, tear stuff down. 
  * W/e state we still have is still active in the channel arb. 
  * That state has an expiring HTLC, we want to go to chain for that. 
  * We then try to force close, that fails since we're in DLP. 
  * On restart error out again. 

With the above patch, we'll error, but not terminate, and wait for something to be confirmed.

**Comment by xmrk-btc** [comment]
Thanks for fast response, trying the patch, seems to work, at least lnd started. 

The borked channel is in fact being closed, the closing tx is not confirmed - https://mempool.space/tx/92105b4e416360742006e242bc09d5c9e405c09dbb5da7e764764de06d55e033 . My own bitcoin node knows about it. first seen 2023-09-10 22:56 UTC.  So perhaps a workaround would be waiting for this tx to confirm. 

Unfortunately I only have logs since 2023-09-12 18:27, even with maxlogfiles=50. I get many repeated lines like  `CRTR: ShortChannelID=753700:644:1: link not found: channel link not found`, I guess I'll open a separate issue about this, because it complicates bug reporting.

**Comment by Crypt-iQ** [comment]
>  I had a kernel panic 2023-09-10, while running rc2, this seems to have caused some data loss and around 20 force closures. (But this is surprising to me, I though the data would be flushed to disk before sending ACK to the peer. At

> That should be the case, as the databases always uses an fdatasync before returning to the caller.

Disks can also "lie" about whether they've flushed the data when really they've just cached the data
