### ISSUE TITLE
Persist active onion circuits before forwarding 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#80]
## Issue 

Currently within the daemon, the `htlcSwitch` manages the teardown/setup of [onion-circuits](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch.go#L66) generated during the forwarding of multi-hop payments. However, as implemented currently, a well timed daemon restart may lead to possibly loss of funds. This is due the fact that the onion circuits are currently kept in [volatile memory](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch.go#L135), and not persisted to disk before forwarding. 

Onion circuits are uniquely defined with the following struct: 
```go
type onionCircuit struct {
    rHash         [32]byte
    clearNode  *btcec.PublicKey
    settleNode *btcec.PublicKey
}
```

where: 
  * `clearNode` is the node that originally forwarded the HTLC to us, clearing it on the incoming channel
  * and `settleNode` is the node we sent the outgoing HTLC to

Once the `settleNode` sends us an HTLC settle message, we the switch needs to forward the settle message to the `clearNode` in order to claim the funds and in the process gain the fee related to the HTLC. 

## Steps to Completion 

Persist the `htlcManager's` `paymentCircuits` map to disk. Ideally, the map should be removed all together and modifications to the prior map should instead take the form of disk accesses in order to side-step any potential consistency issues related to maintain the state both in memory and on disk.

**Comment by mkl-** [comment]
Will take this one.

**Comment by AndrewSamokhvalov** [comment]
will take this one

**Comment by halseth** [comment]
hehe, `beginner` issue

**Comment by Roasbeef** [comment]
LOL, dem edge cases tho

On Mar 7, 2018 10:33 AM, "Johan T. Halseth" <notifications@github.com>
wrote:

hehe, beginner issue

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/80#issuecomment-371176889>,
or mute the thread
