### ISSUE TITLE
[Feature request] Allow setting channel parameters manually when opening channel

### ISSUE THREAD

**Issue by takaya-imai** [lightningnetwork/lnd#800]
I want to set max_htlc_value_in_flight_msat to new value to open a channel different from default but I could not find how to set it.

This is given by lnd boot option? but no options in sample lnd.conf.
https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf

**Comment by Roasbeef** [comment]
We don't allow users to set it atm, it's set by itself with a scaling factor.

**Comment by takaya-imai** [comment]
@Roasbeef thanks.

**Comment by halseth** [comment]
Reopening this as a feature request. There are currently several parameters we might consider letting the user set manually when opening a channel (overriding the defaults):

- [ ] max value in flight
- [ ] channel reserve
- [ ] max number of HTLCs
- [ ] dust limit
- [ ] minimum HTLC value

These are set in the `OpenChannel` message when funding a channel: https://github.com/lightningnetwork/lnd/blob/116406c7ec11672542005727ceb055e4177fc6a4/fundingmanager.go#L2468

and should also be possible to specify at `lnd` startup for incoming channels.

**Comment by vctt94** [comment]
Hey, can I work on this issue? I can start with max value in flight and then max number of HTLCs  as requested when opened the issue.

**Comment by Lldenaurois** [comment]
HI @vctt94 you need any help with this? I can start on other parameters and we burn the candle at both ends

**Comment by vctt94** [comment]
Hey @Lldenaurois 
Yeah, sure! Let's do it :)
It is my first issue, I am still getting used to the code. So all help is welcome!

**Comment by Lldenaurois** [comment]
@vctt94 Sounds good man. I'm gonna go to bed now and then start working on this tomorrow. Do we want to Skype or something like that to discuss a plan?

**Comment by vctt94** [comment]
Can be @Lldenaurois , I believe we are from different timezones, but we can find a time good for both of us. We can discuss a good time at lnd chanel https://webchat.freenode.net/?channels=lnd. I'll be there tomorrow :)

**Comment by offerm** [comment]
@vctt94 @Lldenaurois  are you making progress with a PR? Let me know if you like another hand.

Offer

**Comment by vctt94** [comment]
I have #971 opened right now, which add max value in flight flag, but we still have many others to work on. Feel free to pick one! :)

**Comment by hieblmi** [comment]
Referencing https://github.com/lightningnetwork/lnd/issues/6706 which aims to implement `base_fee_rate` and `fee_rate_ppm` to be applied immediately after a channel has been confirmed.
