### ISSUE TITLE
unable to force close channel 

### ISSUE THREAD

**Issue by ashjkl159** [lightningnetwork/lnd#8010]
### Background
First I tried to openchannel with low onchain fee. After more then 2 weeks of not-confirming, I did `lncli bump fee channelpoint:outputindex`. Channel got finally confirmed but was inactive probably because of longer then 2week of not-confirming. Therefore, i tried to force close it. After force closing it (via LiT terminal), it shows in `lncli pendingchannels` but not as "pending_force_closing_channels" but in "waiting_close_channels" with "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator", when i do `lncli closechannel --funding_txid --output_index --force` to force close it again, it throws error ... "channel is already in the process of being force closed". I can see closing_txid in mempool.space, but `lncli walletbalance` cannot see those funds "unconfirmed"

### Your environment

* version of `lnd` lnd 16.4
* which operating system (`uname -a` on *Nix) ubuntu server 22  5.15.0-83
* version of `btcd`, `bitcoind`, or other backend - bitcoind
* any other relevant environment details

### Steps to reproduce

lncli openchannel
lncli wallet bumpfee --sat_per_byte xx outputpoint:index
force closing channel via LiT terminal (v10.5)

### Expected behaviour

I was expecting to have this channel force closed, in `lncli pendingchannels` as "pending_force_closing_channels"

### Actual behaviour

in `lncli pendingchannels` i have this channel under "waiting_close_channels" with "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator"

**Comment by bitromortac** [comment]
Was the force close transaction confirmed? If yes then the next step is that you have to wait for the CSV timelock to expire in order to get the channel fully resolved, which could take some days.

**Comment by ashjkl159** [comment]
could it be that when i was bumping fee in openning channel (lncli wallet bumpfee --sat_per_byte xx outputpoint:index) .... i accidentaly put --sat_per_byte (not --sat_per_vbyte) so channel got openned with closing non segwit address and that is why i cannot see it in my onchain segwit wallet?

**Comment by bitromortac** [comment]
That shouldn't have to do with it. It would be helpful if you could share the txid or give more info about the confirmation status of the force close.

**Comment by saubyk** [comment]
Moving this issue to a discuss thread, as there is nothing for us to fix here
