### ISSUE TITLE
[question]: does taproot channel require reserved funds?

### ISSUE THREAD

**Issue by starius** [lightningnetwork/lnd#8020]
### Background

I used LND version v0.17.0-beta.rc3 and opened a **taproot** channel on **testnet**. I discovered that I have no reserved funds after that. Is it a expected behavior for a taproot channel? If yes, how does it work in case reserved funds would be needed for an old channel?

### Your environment

* version of `lnd`: v0.17.0-beta.rc3
* which operating system (`uname -a` on *Nix): `Linux dev 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: neutrino
* any other relevant environment details

Command line of LND:
```
lnd \
        --accept-keysend \
        --bitcoin.active \
        --bitcoin.testnet \
        --debuglevel=info \
        --bitcoin.node=neutrino \
        --neutrino.addpeer btcd-testnet.lightning.computer \
        --neutrino.addpeer lnd.bitrefill.com:18333 \
        --neutrino.addpeer faucet.lightning.community \
        --neutrino.addpeer testnet1-btcd.zaphq.io \
        --neutrino.addpeer testnet2-btcd.zaphq.io \
        --neutrino.addpeer testnet3-btcd.zaphq.io \
        --neutrino.addpeer testnet4-btcd.zaphq.io \
        --neutrino.feeurl https://nodes.lightning.computer/fees/v1/btctestnet-fee-estimates.json \
        --listen=0.0.0.0:9735 \
        --externalip=1.2.3.4 \
        --db.bolt.auto-compact \
        --maxpendingchannels=3 \
        --protocol.simple-taproot-chans \
        --protocol.wumbo-channels
```

### Steps to reproduce

```
lncli openchannel --fundmax --channel_type taproot --private --node_key <another peer's node ID>
lncli walletbalance
...
"reserved_balance_anchor_chan": "0",
...
```

### Expected behaviour

I thought 10k sats should had left onchain to use in case the node needs them to bump force close transaction. At least, that happened in mainnet for regular channels.

### Actual behaviour

No funds left onchain.

**Comment by alexbosworth** [comment]
private channels are exempt

**Comment by starius** [comment]
Can you elaborate on that, please? Why are private channels exempt?

**Comment by alexbosworth** [comment]
```
Since private channels (most likely) won't be
used for routing other than the last hop, they bear a smaller
risk that we must force close them in order to resolve a HTLC
up/downstream. Hence we exclude them from the count of anchor
channels
```

**Comment by starius** [comment]
Thank you!

Private channels don't provide anchors, do they?

**Comment by alexbosworth** [comment]
they do

**Comment by starius** [comment]
How such anchors would be used in absence of reserve funds?

**Comment by alexbosworth** [comment]
Without any on chain funds the anchors can't be used because the child tx couldn't be formed to do CPFP
