### ISSUE TITLE
[bug]: 0-conf Simple Taproot channel becomes inactive after payment is made

### ISSUE THREAD

**Issue by kaloudis** [lightningnetwork/lnd#8036]
### Background

After opening up a 0-conf Simple Taproot channel and then completing a payment, the channel becomes inactive, erroring while trying to update the commitment.

`
01:09:32.357 [ERR] HSWC: ChannelLink(85a8547f268528e5473b58883561e30134756d4ab2aadccd8338508346917ec2:0): failing link: unable to update commitment: height=2, for ChannelPoint(85a8547f268528e5473b58883561e30134756d4ab2aadccd8338508346917ec2:0) attempts to create commitment with feerate 218 sat/kw: (*lnwallet.unsignedCommitmentTx)(0x400150a700)({
`

After talking with roasbeef, it sounds like this feerate is set incorrectly and should be set to min of 253 sat/kw everywhere.

The same error was hit opening up a channel, both via RPC and CLI.

Also attempted to open a non 0-conf chan afterwards and hit the following error:

`[lncli] rpc error: code = Unknown desc = non-zero-conf channel has min depth zero`

Can provide more logs upon request.

### Your environment

Initiator
* `lnd` v0.17.0-beta.rc5 (also occurred back with rc1 + rc2)
* Ubuntu Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-156-generic x86_64)
* `bitcoind` v24.01

Acceptor
* Mobile
* `lnd` v0.17.0-beta.rc5 (also occurred back with rc1 + rc2)
* Android 9 + 12
* `bitcoind` v24.01

### Steps to reproduce

Open up a 0-conf Simple Taproot channel to a mobile LND node, and then complete a payment across the channel.

### Expected behaviour

The channel should remain active.

### Actual behaviour

The channel becomes inactive after failing to update the commitment.

**Comment by Roasbeef** [comment]
Attempted to repro with a similar set up (testnet node, neutrino mode, using mainnet fee estimation) but unable to hit it myself.

**Comment by Roasbeef** [comment]
I also spotted this in some logs which looks odd: 
```
01:08:27.755 [INF] CHFD: Performing funding tx coin selection using 0 sat/kw as fee rate
```
