### ISSUE TITLE
[bug]: 0.17.0-rc5 - lncli getinfo hangs, lnd has 20000 files opened

### ISSUE THREAD

**Issue by xmrk-btc** [lightningnetwork/lnd#8039]
### Background

I observe those symptoms, which seem related:
* lncli calls hang indefinitely
* lnd opens ridiculous amount of files, as reported by lsof. Most of them have "protocol: TCPv6" instead of addresses. When filtered out those, the number is sane, corresponds roughly to number of open channels (400). When lnd&lncli work normally, the number of open files in about 300-500.
```
$ lsof -n -p $(pgrep ^lnd$) > /root/lnd_hangs_20230927_lsof.txt
$ cat /root/lnd_hangs_20230927_lsof.txt | wc -l
24130
$ grep -v "protocol: TCPv6"  /root/lnd_hangs_20230927_lsof.txt| wc -l
524    
```
* new peers have problem connecting, but some forwading is going on. Anecdotally, node operators are complaining they cannot connect. Tested network connectivity with one peer and seemed ok, netcat connected. (I had some doubts because I am using tunnelsats.) In logs, last "Finalizing connection" message is 10 hours ago.

Seemed similar to https://github.com/lightningnetwork/lnd/issues/7917 , but I am having this problem on 0.17.0 (various RCs), even on rc5 where said issue should be fixed, and I get i/o timeouts instead of broken pipe:
```
2023-09-27 15:53:19.862 [ERR] CMGR: Can't accept connection: unable to accept connection from 185.220.101.184:19013: read tcp 10.9.0.78:9735->185.220.101.184:19013: i/o timeout
```

Profile with http://localhost:19737/debug/pprof/goroutine?debug=1 :   https://pastebin.com/gpig9UUE . I have profile with debug=2, but it has 15 MB.

I would blame slow raspberry pi, but those open files suggest there is a problem in lnd. Also, I am rate limiting incoming connections by iptables, accepting 5 per second and rejecting anything over.  Moreover, with lnd 0.16.4 I  didn't have this problem, or much less frequent. (I am not sure. I started rate limiting on 6 Sep, so I must have seen some problem by then. ) 

dstat doesn't look like system is under load, lnd data is on sda and sdc as RAID1, both SSD disks:
```
----total-usage---- dsk/mmcblk0---dsk/sda-----dsk/sdb-----dsk/sdc-- -net/total- ------memory-usage----- ----swap--- ---total---
usr sys idl wai stl| read  writ: read  writ: read  writ: read  writ| recv  send| used  free  buf   cach| used  free| read  writ
  1   0  98   0   0|   0     0 :   0    12k:   0     0 :   0    12k|6259B   16k|3144M  245M   10M  361M| 149M  875M|   0     0 
  2   1  98   0   0|   0     0 :   0    12k:   0     0 :   0    12k|6187B   20k|3144M  245M   10M  361M| 149M  875M|   0     0 
  1   1  97   0   0|   0     0 :   0    24k:   0     0 :   0    24k|5416B   30k|3144M  245M   10M  361M| 149M  875M|   0     0 
  2   1  97   0   0|   0    24k:   0    24k:   0     0 :   0    24k|7585B   28k|3144M  244M   10M  361M| 149M  875M|   0     0 
  2   4  93   2   0|   0     0 :   0  1166k:   0     0 :   0  1166k|  36k 1245k|3145M  243M   10M  361M| 149M  875M|   0     0 
  2   1  97   0   0|   0     0 :   0    24k:   0     0 :   0    24k|  12k   30k|3145M  243M   10M  361M| 149M  875M|   0     0 
 10   0  89   0   0|   0     0 :   0    24k:   0     0 :   0    24k|6257B   28k|3145M  243M   10M  361M| 149M  875M|   0     0 
  1   1  98   0   0|   0     0 :   0    12k:   0     0 :   0    12k|2673B   14k|3145M  243M   10M  361M| 149M  875M|   0     0 
  1   0  98   0   0|   0    16k:   0    12k:   0     0 :   0    12k|2771B   16k|3145M  243M   10M  361M| 149M  875M|   0     0 
  1   3  94   1   0|   0     0 :   0  1129k:   0     0 :   0  1129k|  34k 1200k|3146M  243M   10M  361M| 149M  875M|   0     0 
  1   0  97   0   0|   0     0 :   0    24k:   0     0 :   0    24k|4723B   30k|3146M  243M   10M  361M| 149M  875M|   0     0 
  2   0  98   0   0|   0     0 :   0    12k:   0  4099B:   0    12k|6938B   16k|3146M  243M   10M  361M| 149M  875M|   0  4099B
  2   1  97   0   0|   0     0 :   0    36k:   0     0 :   0    36k|8017B   43k|3146M  243M   10M  361M| 149M  875M|   0     0 
```

### Your environment

* lnd 0.17.0-rc5 (happens with various RCs of 0.17.0)
* lnd running on raspberry pi 4 4GB RAM, Ubuntu 22.04 LTS
* bitcoind 0.25.0 on separate laptop

### To reproduce
It happens 2 out of 3 times when starting lnd. Probably also can be triggered by putting too much load on lnd, too many simultaneous gRPC calls.

**Comment by saubyk** [comment]
400 channels on a raspberry pi node! 👀

**Comment by Roasbeef** [comment]
This stands out in the trace: 
```
1 @ 0x47fe0 0x589fc 0xcb4c48 0xd6a7b0 0xd665d0 0x7a064
#	0xcb4c47	github.com/lightningnetwork/lnd/peer.(*Brontide).Disconnect+0xb7	/home/marek/programs/lnd/peer/brontide.go:1115
#	0xd6a7af	github.com/lightningnetwork/lnd.(*server).removePeer+0xdf		/home/marek/programs/lnd/server.go:4309
#	0xd665cf	github.com/lightningnetwork/lnd.(*server).InboundPeerConnected+0x5ff	/home/marek/programs/lnd/server.go:3586
```

The goroutine is blocked on waiting on the `p.startReady` channel to be closed. 

```
3 @ 0x47fe0 0x598dc 0x598b9 0x75c18 0x92e24 0x94630 0x945d9 0xd6495c 0xcb1ef8 0xd685e0 0x7a064
#	0x75c17		sync.runtime_SemacquireMutex+0x27						/usr/lib/go/src/runtime/sema.go:77
#	0x92e23		sync.(*Mutex).lockSlow+0x173							/usr/lib/go/src/sync/mutex.go:171
#	0x9462f		sync.(*Mutex).Lock+0x6f								/usr/lib/go/src/sync/mutex.go:90
#	0x945d8		sync.(*RWMutex).Lock+0x18							/usr/lib/go/src/sync/rwmutex.go:147
#	0xd6495b	github.com/lightningnetwork/lnd.(*server).prunePersistentPeerConnection+0x4b	/home/marek/programs/lnd/server.go:3259
#	0xcb1ef7	github.com/lightningnetwork/lnd/peer.(*Brontide).Start+0x207			/home/marek/programs/lnd/peer/brontide.go:554
#	0xd685df	github.com/lightningnetwork/lnd.(*server).peerInitializer+0xff			/home/marek/programs/lnd/server.go:3977
```

It's blocked on removing the old persistent peer connections. This blocks `Disconnect` from being called. 

The main gossiper event loop wants to retransmit our node ann, and to do so it needs to obtain a server mutex to do so: 
```
1 @ 0x47fe0 0x598dc 0x598b9 0x75c18 0x92e24 0x94630 0x945d9 0xd62d70 0xb31f7c 0xb30f24 0x7a064
#	0x75c17		sync.runtime_SemacquireMutex+0x27								/usr/lib/go/src/runtime/sema.go:77
#	0x92e23		sync.(*Mutex).lockSlow+0x173									/usr/lib/go/src/sync/mutex.go:171
#	0x9462f		sync.(*Mutex).Lock+0x6f										/usr/lib/go/src/sync/mutex.go:90
#	0x945d8		sync.(*RWMutex).Lock+0x18									/usr/lib/go/src/sync/rwmutex.go:147
#	0xd62d6f	github.com/lightningnetwork/lnd.(*server).getNodeAnnouncement+0x4f				/home/marek/programs/lnd/server.go:2960
#	0xb31f7b	github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).retransmitStaleAnns+0x3ab	/home/marek/programs/lnd/discovery/gossiper.go:1666
#	0xb30f23	github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler+0x973		/home/marek/programs/lnd/discovery/gossiper.go:1454
```

That's blocked while all the other peer goroutines try and wait for the incoming gossip messages to be processed.

**Comment by Roasbeef** [comment]
Here's a version of the goroutine dump stripped down slightly to the essentials: https://paste.sh/I0V0nS6z#bmHA97AKogqtO1VJSlPk-Rhj

**Comment by xmrk-btc** [comment]
FWIW, just finished migrating to better hw (Ryzen 3 PRO 2300U notebook), and got the same problem again. Profile: https://pastebin.com/UQPe7NMJ . One difference is that there is no `getNodeAnnouncement`.

**Comment by Roasbeef** [comment]
Correct, no `getNodeAnnouncement`, but we do have `prunePersistentPeerConnection` blocking still:
```
1 @ 0x43c256 0x44d1be 0x44d195 0x4695a5 0x483c45 0x485236 0x485215 0x12e3ef3 0x1215197 0x12e8897 0x46d721
#	0x4695a4	sync.runtime_SemacquireMutex+0x24						/usr/lib/go-1.19/src/runtime/sema.go:77
#	0x483c44	sync.(*Mutex).lockSlow+0x164							/usr/lib/go-1.19/src/sync/mutex.go:171
#	0x485235	sync.(*Mutex).Lock+0x35								/usr/lib/go-1.19/src/sync/mutex.go:90
#	0x485214	sync.(*RWMutex).Lock+0x14							/usr/lib/go-1.19/src/sync/rwmutex.go:147
#	0x12e3ef2	github.com/lightningnetwork/lnd.(*server).prunePersistentPeerConnection+0x72	/home/marek/programs/lnd/server.go:3259
#	0x1215196	github.com/lightningnetwork/lnd/peer.(*Brontide).Start+0x256			/home/marek/programs/lnd/peer/brontide.go:554
#	0x12e8896	github.com/lightningnetwork/lnd.(*server).peerInitializer+0x156			/home/marek/programs/lnd/server.go:3977
```

**Comment by Roasbeef** [comment]
Along with this: 
```
1 @ 0x43c256 0x44c0fc 0x121886e 0x12eb190 0x12e609a 0x46d721
#	0x121886d	github.com/lightningnetwork/lnd/peer.(*Brontide).Disconnect+0xad	/home/marek/programs/lnd/peer/brontide.go:1115
#	0x12eb18f	github.com/lightningnetwork/lnd.(*server).removePeer+0x10f		/home/marek/programs/lnd/server.go:4309
#	0x12e6099	github.com/lightningnetwork/lnd.(*server).InboundPeerConnected+0x739	/home/marek/programs/lnd/server.go:3586
```

`InboundPeerConnected` holds the server mutex, and wants to go call `Disconnect`, but in the other goroutine, `Start` hasn't finished, so `p.startReady` isn't closed, which means `Disconnect` can't proceed.

**Comment by Roasbeef** [comment]
@xmrk-btc thanks for all the great debug info! If you're able, can you try out this PR: https://github.com/lightningnetwork/lnd/pull/8041?

**Comment by xmrk-btc** [comment]
Yes, tried, started twice without problems. Second time I tried to do a stress test, running several times  `for i in $(seq 1 50); do ~/go/bin/lncli listchannels > /dev/null & done` while lnd was doing initial connect to peers. All those lncli ended successfully. Also, no rate limiting of incoming connections .
Only tested on new hw.

I think you can close the issue, or perhaps suggest how should I test.
