### ISSUE TITLE
[bug]: link to reproducible builds page is broken on release page

### ISSUE THREAD

**Issue by starius** [lightningnetwork/lnd#8055]
### Background

The [release page](https://github.com/lightningnetwork/lnd/releases/tag/v0.17.0-beta) has the following section:

> Our release binaries are fully reproducible. Third parties are able to verify that the release binaries were produced properly without having to trust the release manager(s). See our [reproducible builds guide](https://github.com/lightningnetwork/lnd/tree/master/build/release) for how this can be achieved.

The link "reproducible builds guide" is broken (404 - page not found).

**Comment by guggero** [comment]
Thanks, will fix in a moment. In the meantime, the correct link is: https://github.com/lightningnetwork/lnd/blob/master/docs/release.md
