### ISSUE TITLE
`--value` still used instead of `--amt`

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lnd#807]
https://github.com/lightningnetwork/lnd/blob/116406c7ec11672542005727ceb055e4177fc6a4/lnrpc/rpc.swagger.json#L1835

https://github.com/lightningnetwork/lnd/blob/116406c7ec11672542005727ceb055e4177fc6a4/lnrpc/rpc.swagger.json#L1505

https://github.com/lightningnetwork/lnd/blob/116406c7ec11672542005727ceb055e4177fc6a4/lnrpc/rpc.proto#L1436

https://github.com/lightningnetwork/lnd/blob/116406c7ec11672542005727ceb055e4177fc6a4/lnrpc/rpc.proto#L1365

**Comment by Roasbeef** [comment]
What's the issue here? The command line, and the protos are _distinct_. They don't always map 1 to 1.

**Comment by ysangkok** [comment]
Ok, just thought it was supposed to be consistent. Sorry for the inconvenience.
