### ISSUE TITLE
[bug]: Can't open channels after upgrading to v0.17.0 beta

### ISSUE THREAD

**Issue by InnocuousFinch** [lightningnetwork/lnd#8071]
### Background

When attempting to open a channel, I get a "channel rejected" funding error. Not sure how to resolve or if there is anything I can do to resolve the issue. I've tried restarting LND, entire device, etc and it does not help. I have enough confirmed UTXOs to be able to easily open this channel.

COMMAND LINE: 
`sudo -u bitcoin /usr/local/bin/lncli -n=mainnet --rpcserver localhost:10009 openchannel --conf_target=1 031b301307574bbe9b9ac7b79cbe1700e31e544513eae0b5d7497483083f99e581 2000000 0`

### Your environment

* LND v0.17.0 beta
* Raspiblitz v1.0.9
* bitcoin v24.0.1

### Steps to reproduce

1. Upgraded node to LND v0.17.0 beta using Raspiblitz menu in CLI
2. Attempt to open channel a channel.

### Expected behaviour

Channel should be opened

### Actual behaviour

Receive below error message:
`[lncli] rpc error: code = Unknown desc = received funding error from 031b301307574bbe9b9ac7b79cbe1700e31e544513eae0b5d7497483083f99e581: chan_id=cb025f50462e656c8d16a41146285a68a3a03fecc0a0e74963ac35e6618d3a48, err=channel rejected`

**Comment by hieblmi** [comment]
The remote peer is rejecting your channel opening. I get

```
[lncli] rpc error: code = Unknown desc = received funding error from 031b301307574bbe9b9ac7b79cbe1700e31e544513eae0b5d7497483083f99e581: chan_id=<redacted>, err=Currently not accepting public, broadcasted channel opens from you node. Please try again with an unannounced channel or reach out to the Zeus team to apply to be whitelisted.
```

**Comment by InnocuousFinch** [comment]
> The remote peer is rejecting your channel opening. I get
> 
> ```
> [lncli] rpc error: code = Unknown desc = received funding error from 031b301307574bbe9b9ac7b79cbe1700e31e544513eae0b5d7497483083f99e581: chan_id=<redacted>, 
> err=Currently not accepting public, broadcasted channel opens from you node. 
> Please try again with an unannounced channel or reach out to the Zeus team to apply to be whitelisted.
> ```

I believe you are correct. I have tried with opening a channel to a different node and that worked fine. Sorry about that. Closing the issue as it doesn't appear to be an LND related issue/bug.
