### ISSUE TITLE
Build Fail on Brontide

### ISSUE THREAD

**Issue by hxsquid** [lightningnetwork/lnd#809]
Trying to compile the brontide pkg isn't working:

./conn.go:47:53: cannot use netAddr.IdentityKey (type *"github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec".PublicKey) as type *"github.com/roasbeef/btcd/btcec".PublicKey in argument to NewBrontideMachine

I'm a novice in go land!

**Comment by Roasbeef** [comment]
You can't compile the package. It's not a `main` package, so it doesn't produce a binary.
