### ISSUE TITLE
Implement proper HTLC failure within the htlcSwitch 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#81]
## Issue 
Currently within the `htlcSwitch`, handling forwarding failures aren't properly implemented. In case of any of the errors described below forwarding will either fail silently, trigger an error, lead to an invalid commitment state, or a "stuck" HTLC. 

## Steps to Completion 

The following error cases need to be properly handled: 

* The outgoing interface/link for an HTLC sent over the `htlcSwtich`'s `htlcPlex` channel has an insufficient capacity to send the HTLC over. 
* The outgoing interface a `htlcPacket` sent over the `htlcPlex` channel _doesn't exist_ 

This issue is related to #79 as the `htlcManager` goroutine who receives the error message will need to generate an onion-wrapped error message to the peer who originally sent the HTLC.  

Additionally, the `htlcSwitch` will need to be extended to handle cancel requests within the switch statement after a read from the `htlcPlex` channel.

**Comment by AndrewSamokhvalov** [comment]
will take this one

**Comment by Roasbeef** [comment]
Closed by 6bd0e068c6653bc7d17bb26b3a74f644d4aa040e.
