### ISSUE TITLE
activate `listchannels --active_only`

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#810]
`--active_only` / `-a` is a flag that can be passed to `lncli listchannels`. Currently passing this flag does nothing. 

### Steps to resolve:
- [ ] Add the flag to `ListChannelsRequest`: https://github.com/lightningnetwork/lnd/blob/51a3cab39c30341b8e9517cb7ec760d0fc37cff2/lnrpc/rpc.proto#L825
- [ ] Within the `rpcserver`, only add the channel to the response if it is considered `active`: https://github.com/lightningnetwork/lnd/blob/51a3cab39c30341b8e9517cb7ec760d0fc37cff2/rpcserver.go#L1542
- [ ] Pass the flag parsed from the command line and add it to the request: https://github.com/lightningnetwork/lnd/blob/51a3cab39c30341b8e9517cb7ec760d0fc37cff2/cmd/lncli/commands.go#L1163

**Comment by CTP-chowell** [comment]
@halseth i'll start working on this request if that's okay with you?

**Comment by wilmerpaulino** [comment]
Sorry @CTP-chowell, I should've mentioned I was already working on this.
