### ISSUE TITLE
Reconnect peers needed for channels.

### ISSUE THREAD

**Issue by Metalsprzet** [lightningnetwork/lnd#811]
LND does not reconnect to peers which close connection, but are needed for active channels. It makes it only restart lnd.

**Comment by Metalsprzet** [comment]
Maybe I don't know everything, but see the problems in my lnd.

**Comment by Roasbeef** [comment]
No, `lnd` automatically reconnects to any peers that it established channels with. If a peer isn't online, or has changed it's IP, then it may not be able to immediately connect.

**Comment by halseth** [comment]
It should reconnect peers it has channels with. If no, it's a bug.

@Metalsprzet Do you experience this with nodes you know that really is online? If so, could you post some logs?

**Comment by Roasbeef** [comment]
Will re-open if revived by the OP.
