### ISSUE TITLE
[bug]: [ERR] PEER

### ISSUE THREAD

**Issue by HotCrypt** [lightningnetwork/lnd#8122]
Hi, my node works very well after a new reinstallation without the chan.backup file(Lost), just with the seed phrase and I was able to recover my on-chain funds.
For the off-chain, I lost 3 channels, so they are zombie channels?

I reconnected to a node with which I had opened a channel but i noted some suspicious lines:

`[ERR] PEER: Peer (xxxxx): resend failed: unable to fetch channel sync messages for peer xxxx@xxx:xxxx: unable to find closed channel summary`

`[INF] PEER: Peer (xxxxx): negociated chan series queries`

`[INF] PEER: Peer(xxxxx): unable to read message from peer: read next header: EOF`

Thank you.
Sincerely,

### Your environment
LND V0.17.0-beta tor/clearnet
Btc core v25.1
Rasp 4 8go

**Comment by bitromortac** [comment]
This is probably related to https://github.com/lightningnetwork/lnd/discussions/8077 (and https://github.com/lightninglabs/chantools/discussions/89), let's keep the discussion there to keep information in one place (I will answer on https://github.com/lightningnetwork/lnd/discussions/8077). Feel free to reopen otherwise.

**Comment by HotCrypt** [comment]
Thanks 👌, I'm going to look at that.

I also forgot to specify that I can't delete this peer (the disconnnect clit) it looks like a bug, maybe because of the old channel (now 🧟‍♀️🧟‍♂️chan) open with it? Now I wonder if LND keeps traces? It's the same node on the same local network. I had Clean All my hard drive and I reinstalled without off-chain backup

**Comment by HotCrypt** [comment]
Also I have 800k sat blocks in my 3 old channels, if someone wants to help me (with command) get them backup with chantools, I donate half sat 🙂✌️
