### ISSUE TITLE
GRPC - queryRoutes empty routes array

### ISSUE THREAD

**Issue by Metalsprzet** [lightningnetwork/lnd#813]
Problem.
lncli queryroutes ... ... return  routes full array  but rpc queryRoutes at the same moment  response with no error and routes [] length - 0

**Comment by Roasbeef** [comment]
The `queryroutes` command for `lncli`, actually just hits the `QueryRoutes` RPC. I'd check your manual arguments to the RPC.

**Comment by Roasbeef** [comment]
Resolved on IRC.

**Comment by Metalsprzet** [comment]
My mistake.
