### ISSUE TITLE
payment: fix compatibility issue for the new payment status

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lnd#8143]
A point I wanted to highlight concerning compatibility issues with the new payment status is that an outdated `lncli payinvoice` will report an error because it doesn't know the status `initiated`, but the launched payment may be successful. This has the potential to break people's scripts if they only upgraded lnd but not lncli (which may happen in some cases).

Also, if endpoint consumers interpret the unknown status code as as a failure then this could lead to several payouts. An example would be if somebody tries to pay out funds from a custodial system (e.g. lit accounts) and operators haven't upgraded their accounting to reflect the status code (and they interpret it as a failure) this may lead to cases where the user is not debited.

_Originally posted by @bitromortac in https://github.com/lightningnetwork/lnd/issues/7503#issuecomment-1781320920_

The fix:

One way to handle it maybe would be: clients for the subscription call pass in a new flag that states they want the new enum value, and we only send it if so. In "compatibility mode", we just send in flight.

_Originally posted by @Roasbeef in https://github.com/lightningnetwork/lnd/issues/7503#issuecomment-1788104004_

**Comment by alexbosworth** [comment]
To me initiated and in_flight seem pretty similar in definition so I'd appreciate a flag to opt in to getting the difference broken out and otherwise combine them? Like payment starts in_flight and then goes to succeeded or failed

**Comment by yyforyongyu** [comment]
This new status can be helpful to fix cases like #7697.
