### ISSUE TITLE
Syntax error in type declaration in circuit.go line 21

### ISSUE THREAD

**Issue by deinerson1** [lightningnetwork/lnd#815]
Hi,
This error happens during compilation, and showed up recently:

```
[INFO]  Replacing existing vendor dependencies
# github.com/lightningnetwork/lnd/htlcswitch
htlcswitch/circuit.go:21: syntax error: unexpected = in type declaration
```

lnd version 0.3.0-alpha

The error occurs after commit 2b8cad2, which successfully builds.

I am using go version go1.8.3 linux/amd64.

Thank you for your work,
Dave

**Comment by halseth** [comment]
Seems like it is a `type alias`, which was introduced in `go 1.9`: https://golang.org/doc/go1.9#language

We should update the instructions to require `go >= 1.9`

**Comment by rodasmith** [comment]
Does https://github.com/lightningnetwork/lnd/blob/master/docker/lnd/Dockerfile#L1 need updated to use go >= 1.9?
> FROM golang:1.8

**Comment by deinerson1** [comment]
On Ubuntu server (artful),
```
sudo apt-get install golang-1.8 golang-1.9 golang-1.10
```

Change to and list the /usr/lib directory to see what go versions are installed.
Edit ~/.bashrc to export the GOROOT environment variable. Change the GOROOT version directory as needed.

```
# On Ubuntu server the go install path is /usr/lib/go-1.10/bin
export GOROOT=/usr/lib/go-1.10
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
```
