### ISSUE TITLE
[bug]: the "tlsencryptkey" parameter avoids starting a new instance (without seeds saved)

### ISSUE THREAD

**Issue by twofaktor** [lightningnetwork/lnd#8165]
### Background

The `tls.cert` file is not created on a new LND node instance due to having the `tlsencryptkey=true` parameter on the `lnd.conf`

https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L74-L75

when you exec `lncli` to create the wallet and import or generate new seeds, the prompt shows you the next error output:

```
[lncli] could not load global options: could not load TLS cert file: open /home/lnd/.lnd/tls.cert: no such file or directory
```  

![errortls-tlsencryptkey](https://github.com/lightningnetwork/lnd/assets/89636253/9b3342c4-b6d4-4397-9b54-d60010bb48a9)

I think the `tls.cert` needed to use `lncli` is not created, due to `tls.key` is not created, because there are no existing seeds for encryption yet

### Your environment

* version of `lnd`: v17.0
* which operating system: Ubuntu Server 22.04.3 LTS
* version of bitcoind: Bitcoin Core v25.1

### Steps to reproduce

On a new LND node (without seeds saved)

1. Set `tlsencryptkey=true` on the `lnd.conf` file
2. Start LND
3. Exec `lncli create`
4. ...the previously mentioned error appears...

### Expected behaviour

the startup routine should be changed and the `tls.key` file should be encrypted with node seeds automatically **only after the wallet** has been created or the existing wallet opened, and the seed's storage

### Actual behaviour

```
[lncli] could not load global options: could not load TLS cert file: open /home/lnd/.lnd/tls.cert: no such file or directory
```

#### The manual fix:
If you delete or comment the `tlsencryptkey=true` parameter of the `lnd.conf` file, you can start LND without issues and then create the wallet. Finally include again or uncomment the `tlsencryptkey=true` and restart LND, the parameter takes effect and the `tls.key` file is encrypted, but I think that it shouldn't be necessary to do manually, and LND should include the necessary logic on the startup routine to prevent your startup from not working in the first instance (without seeds) due to having that parameter enabled.

**Comment by bitromortac** [comment]
> I think the tls.cert needed to use lncli is not created, due to tls.key is not created, because there are no existing seeds for encryption yet

There's a `tls.cert.tmp` that's created in your .lnd folder which you should be able to use for wallet creation.

**Comment by twofaktor** [comment]
Ok, I solved this by adding the `--tlscertpath` flag with the path of the `tls.cert.tmp` file to the `lncli create` command

eg. `lncli --tlscertpath /.lnd/tls.cert.tmp create`

Is there any provision for this logic to be included in the LND code without having to use this command in the first instance?

If not, you can close that issue as solved.
