### ISSUE TITLE
[bug]: trackpayment shows payment IN_FLIGHT but logs shows failed: no_route

### ISSUE THREAD

**Issue by jr21M** [lightningnetwork/lnd#8178]
### Background

Tried to pay an invoice, and I got Payment status: IN_FLIGHT for a while. However checking the logs the payment shows as failed. In the listchannels I do not see pending HTLCs related to this payment either. 

Tried to restart the node, payment still shows IN_FLIGHT

### Your environment

* version of `lnd`: 0.17.0-beta commit=v0.17.0-beta
* which operating system (`uname -a` on *Nix): Linux ldn-vpn 5.15.0-88-generic # 98-Ubuntu SMP
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.25.0
* any other relevant environment details: pruned node to 4GB 

### Steps to reproduce

lncli payinvoice --outgoing_chan_id xxxxxxxxxxxxx --pay_req lnbcxxxxxxxxxxxxx

lncli trackpayment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e

LOGS AFTER PAYMENT ATTEMPT:

lnd[3045]: 2023-11-14 12:04:10.747 [WRN] CRTR: Failed to find route for payment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e: unable to find a path to destination

ldn-vpn lnd[3045]: 2023-11-14 12:04:10.760 [ERR] CRTR: Payment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e failed: no_route

LOGS AFTER NODE REBOOT:

ldn-vpn lnd[101761]: 2023-11-14 12:59:11.838 [INF] CRTR: Resuming payment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e

ldn-vpn lnd[101761]: 2023-11-14 12:59:11.844 [INF] CRTR: Resuming payment shard 2000 for payment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e

lncli trackpayment c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e

Payment hash:   c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e
Payment status: IN_FLIGHT

### Expected behaviour

lncli payinvoice should show a few routing attempts and then shows failure reason.

trackpayment should then show status failed. 

trackpayment should show payment failed after node reboot.

### Actual behaviour

lncli payinvoice showed only 1 attempt and got stuck on IN_FLIGHT.

trackpayment still shows status IN_FLIGHT even after node reboot

**Comment by yyforyongyu** [comment]
Could you try restart your node with `--debuglevel=debug,HSWC=trace,CRTR=trace` and share the logs with me?

**Comment by jr21M** [comment]
Thanks, which part you are interested in? Asking bc the log is massive, and actually I tried to grep for the payment hash in question but no results...However, on lncli trackpayment it still shows as IN_FLIGHT

**Comment by yyforyongyu** [comment]
Thanks for the logs! Could you do a `lncli listpayments` and paste the results here?

**Comment by jr21M** [comment]
Hi, I have executed the command and there are all the payments done, but nothing about that payment hash c59b891cfca402d62756228c4b8593b466f4eec8d07b510ea992824b363fd01e

**Comment by yyforyongyu** [comment]
In that case, I'd say wait for 0.18 to resolve this issue, where we've refactored the payment handling to enhance its stability and, fixed the stuck payment issue in #8174

**Comment by yyforyongyu** [comment]
@lukaszsamson yeah it'd be great if you have some debug logs!
