### ISSUE TITLE
Error during "go install" on ARM platforms (Pi & Odroid)

### ISSUE THREAD

**Issue by Stadicus** [lightningnetwork/lnd#819]
When I documented the build and installation of LND about three weeks ago in a [guide](https://medium.com/@stadicus/perfect-low-cost-%EF%B8%8Flightning%EF%B8%8F-node-4c2f42a4ff7b) (see section 8) for usage on a ARM-based Odroid HC2, the installation of LND as described in the Github installation instructions worked flawlessly.

Starting last week, I got several feedbacks of users (see [this](https://medium.com/@bobby.morse83/hello-thank-you-for-putting-together-this-guide-f643e135a3f4) and [this](https://www.reddit.com/r/Bitcoin/comments/8156us/the_perfect_bitcoin_lightning_node_diy_for_100/dvhjpm9/)) that get the following error:

```
$ cd $GOPATH/src/github.com/lightningnetwork/lnd
$ git pull && glide install
$ go install . ./cmd/...
# github.com/lightningnetwork/lnd/htlcswitch
htlcswitch/circuit.go:21: syntax error: unexpected = in type declaration
```

Today, I retested my guide on two machines and ran into the same error.
- Raspberry Pi 3 with Raspbian GNU/Linux 9.3 (stretch)
- Odroid HC2 with  Ubuntu 16.04.4 LTS

Some parameters:
```
$ uname -r
4.9.59-v7+ (Raspberry Pi)
4.14.20-108 (Odroid HC2)
$ go version
go version go1.8 linux/arm
$ echo $GOPATH
/home/pi/go
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/pi/go/bin
```

Any idea what's causing this? Any additional info that I can provide?

**Comment by MeshCollider** [comment]
The minimum version of Go was changed to 1.10, because this error is due to a type alias, a feature introduced in go1.9, and you only have 1.8 installed.

See https://github.com/lightningnetwork/lnd/pull/818 & https://github.com/lightningnetwork/lnd/issues/815

**Comment by Stadicus** [comment]
Thanks, I just tested it for myself and when using go1.10 it works.
