### ISSUE TITLE
[bug]: When lnrpc is used in golang, the UseHexForBytes attribute in the rpc_utils.go file in the lnrpc folder is incorrect

### ISSUE THREAD

**Issue by mmdi1** [lightningnetwork/lnd#8212]
### Background

Describe your issue here.

### Your environment

* version of `lnd`
* github.com/lightningnetwork/lnd v0.17.1-beta
### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
<img width="699" alt="image" src="https://github.com/lightningnetwork/lnd/assets/24910959/5902be8c-8965-44b6-9afd-f8af8a6e1ec7">

### Expected behaviour
no err
Tell us what should happen
unable to run

**Comment by mmdi1** [comment]
file path:lnrpc>rpc_utils.go

**Comment by hieblmi** [comment]
There's a new `go.mod` replace directive in `v0.17.1`:
```
// We want to format raw bytes as hex instead of base64. The forked version     
208 // allows us to specify that as an option.                                      
209 replace google.golang.org/protobuf => github.com/lightninglabs/protobuf-go-hex-display v1.30.0-hex-display
```

could you try to `go mod tidy` once.

**Comment by guggero** [comment]
Yes, unfortunately you need to use the `replace` directive mentioned above if you use `lnrpc` as a library in your Golang project.

**Comment by Nsandomeno** [comment]
@hieblmi @guggero is there lost functionality of `google.golang.org/protobuf` in doing this, namely common `encodings `and `types` from `protobuf`? Struggling to compile after this, seemingly from lost functionality in `protobuf` used elsewhere in `lnrpc`.

Notably, the `rpc_utils.go` errors related to `UseHexForBytes` is resolved by adding @hieblmi 's recommendation to the bottom of my `go.mod` and running go mod tidy. 

In ideas on how to use replace without stripping `protobuf` from any other code that may need it or what I may be missing related to the replace go feature?

**Comment by guggero** [comment]
I'm not sure I understand what you mean by "lost functionality". Are you saying your code or dependencies of your code use a version of `google.golang.org/protobuf` that is newer than the one we forked?
We forked `v1.30.0` and the latest available version is `v1.32.0`.
There was some new functionality added in `v1.31.0` but I'm not sure that is what you are referring to?

**Comment by Nsandomeno** [comment]
Sorry to be vague there. Here is an example error message (one of many) that occurs in the `go.mod` after adding the line mentioned above to the bottom of my `go.mod` file.

```
error while importing github.com/lightninglabs/taproot-assets/taprpc: missing go.sum entry for module providing package google.golang.org/protobuf/proto (imported by github.com/lightningnetwork/lnd/lnrpc); to add:
	go get github.com/lightningnetwork/lnd/lnrpc@v0.17.3-beta
```

Is this suggesting that the `go.mod` of other dependencies, needs the replace directive as well?

**Comment by guggero** [comment]
Ah yes. Unfortunately `replace` directives of dependencies are ignored by `go mod`. So you need to use the same replace directive in any project where you import `lnd`. See for example: https://github.com/lightninglabs/taproot-assets/blob/main/go.mod#L215
