### ISSUE TITLE
[feature]: multiple nodes in one node / Multinode

### ISSUE THREAD

**Issue by eliaspfeffer** [lightningnetwork/lnd#8229]
Feature: I want to run multiple nodes with separate password and separate seed phrases at once in one LND.exe .

Solution: Give LND Wallet a name, control this specific wallet via this name.
e.g.
`lncli unlock satoshiswallet`

`lncli lock halfinneyswallet`

Alternative1: Run multiple LND.exe files with different ports at once and run port-forwarding software. Bad, because not scalable + a lot of overhead.
Alternative2: Run one node for multiple owners. Bad, because not secure.

**Comment by Roasbeef** [comment]
This is possible today with a wrapper program that spins up two instances in the same process. `litd` linked above does pretty much this, and also spins up other related daemons. 

Current plans are this type of feature won't be added _directly_ to `lnd`, but we'll refactor the top-level configuration with additional abstractions to make this type of deployment easier. 

Closing this as it's possible today (with a wrapper program), and we're tracking further progress in these issues:
  * https://github.com/lightningnetwork/lnd/issues/6694
  * https://github.com/lightningnetwork/lnd/issues/6294
  * https://github.com/lightningnetwork/lnd/issues/3944
