### ISSUE TITLE
LND user data is consuming 450 Mb, is there some workaround to not consume that much?

### ISSUE THREAD

**Issue by sezaru** [lightningnetwork/lnd#825]
I’m running a `LND` node on `testnet`, I am using `neutrino` (with your faucet server) as a light client since my node need to use the minimum amount of resources possible, however it is still syncing and downloading 450+ Mb before it is usable.

I also tried to use `bitcoind` as a remote full node, but again the `LND` would start to consume more and more data as it would check (or it seems like) every transaction block and save something from it inside wallet.db.

Since I intend to use `LND` into a embedded system, I cannot afford a data app that would increase considerably over time. 

Is there some option to remove it? Or is that by design or some kind of bug or future improvement?

**Comment by Roasbeef** [comment]
450MB? That sounds off. For example, the faucet uses 128MB or so (not including logs). As a lower bound, there are 1288048 blocks on testnet. We currently store _all_ the block headers, so at 80MB each, that puts us at 103MB. We didn't initially store all the block headers, but then shifted to doing so in order to handle some of the crazy re-orgs (like 10k+ blocks) that can happen on testnet at times.

**Comment by Roasbeef** [comment]
> as it would check (or it seems like) every transaction block and save something from it inside wallet.db

We don't store every transaction, only those that are ours. For `bitcoind` since there isn't an easy to use external rescan API, we're forced to do so manually ourselves. 

> I am using neutrino (with your faucet server) as a light client since my node need to use the minimum amount of resources possible

We currently store _all_ the filters, but don't need to at all. Following from the header size/space calculation above, we also have the filter headers which are 32 bytes each, two diff chains of them, so that means 82MB for that storage. Again, we don't necessarily need to store _all_ of them, and we can discard the remaining after validation.

**Comment by Roasbeef** [comment]
Also it's worth noting that this is testnet, which has a chain that's 2.5x the size of mainnet. So all those numbers are slimmed down a bit on actual Bitcoin.

**Comment by sezaru** [comment]
So, if I understood that correctly, we need to store it to do the needed validations right? Is that because we don't trust the bitcoin full node validation and so it's safer to do it inside LND too?

Is that something that can be disabled somehow? I mean, I plan to have my own remote full node that I can trust. But my LND node will be inside a very restrictive embedded device, so hard-drive space is critical.

**Comment by Roasbeef** [comment]
We need to store the headers, just to ensure we can handle a re-org of _any_ length. We don't necessarily need to store _all_ of them, but we do so atm just for safety reasons. It can probably safely be reduced to like 50k or so headers.

**Comment by sezaru** [comment]
I see now, so I would guess that in the main net we would just need something around 6~10 headers right?

Also, can this be considered as a future fix/improvement for LND so it can be more easily used in embedded systems?

**Comment by Roasbeef** [comment]
> I see now, so I would guess that in the main net we would just need something around 6~10 headers right?

More like 100-200, but yes. 

> Also, can this be considered as a future fix/improvement for LND so it can be more easily used in embedded systems?

Sure, but it isn't a priority for us atm. If it scratches your itch, then patches reducing the header horizon would be accepted.

**Comment by sezaru** [comment]
Thanks for the fast answers!

I will take a look at it with my team then and see if we can fix our problems with a possible header reduction patch.

**Comment by Roasbeef** [comment]
One correction to my prior breakdown: we only store the _header hashes_ in the wallet. 

Cool!

Most of the relevant work would actually be _outside_ of `lnd`. [All the backend interfaces are abstracted away](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/interface.go). 

The wallet code (where we currently store the header hashes) can be found here: https://github.com/Roasbeef/btcwallet/. The chain backend is again abstracted away, and is where the logic that decides how many headers to store on disk lives. Previously, there was a limit w.r.t to the [number of headers stored](https://github.com/btcsuite/btcwallet/blob/master/waddrmgr/sync.go#L191). The new logic now instead [stores each header](https://github.com/Roasbeef/btcwallet/blob/master/waddrmgr/sync.go#L61). 

In [neutrino](https://github.com/lightninglabs/neutrino/), we'll always write the filter to disk, meaning we'll store all filters we ever fetch (even though in most cases, we can fetch it, then not need ti any longer). The solution here would be to either only keep the filter in some in-memory cache, or just persist the cache to disk (meaning some cap on the total number of stored entries).

**Comment by biscottigelato** [comment]
I am also seeing 400+MB. It seems the bulk of it is from neutrino.db and wallet.db, not from the header or filters? I am almost certain I'm misunderstanding something.
<img width="473" alt="screen shot 2018-05-29 at 16 34 06" src="https://user-images.githubusercontent.com/24286268/40691023-d019dbb6-635e-11e8-944a-a398d7b0d7b7.png">

**Comment by Roasbeef** [comment]
See the above comment. Filters are stored in neutrino.db. Testnet has over 1.3mil headers so it's nearly 3x the size of mainnet as is now.

**Comment by Roasbeef** [comment]
The new version of neutrino will no longer store all the filters to disk, as we can add higher level caching to ensure that we only fetch each filter once during normal operation. Similarly, we only need to store say the first 5000 headers or so in the wallet as a re-org beyond that would be disastrous. Arguably, the same could be optionally done for neutrino if the application doesn't need access to the historical header state.
