### ISSUE TITLE
Adding sat_per_vbyte to SendCoins function

### ISSUE THREAD

**Issue by omegacr** [lightningnetwork/lnd#8265]
Hello, I am using the senCoins function from the Lightning Network API to send BTC, but when I add the sat_per_vbyte parameter to the request, it sends me this error: "DECODE PAYMENT DATA ERROR Error: 2 UNKNOWN: only FeeRate or ConfTarget should be set for FeePreferences". I should mention that I am using a wrapper to interact with the API, which is lnd-grpc. If I don't send this parameter, it works fine, but I want to be able to set the fee using this parameter. If anyone has any help or guidance, I would appreciate it.

Nodejs
lnd-grpc 0.5.3

**Comment by guggero** [comment]
Do you set the `conf_target` parameter? If yes, then you need to remove that. Either you specify a fee rate or the number of blocks you want to confirm within (allowing `lnd` to do the rate estimation based on that) but not both.

**Comment by omegacr** [comment]
Hi @guggero, yes I did I set that parameter too, and I will remove it, and just let the sat_per_vbyte, thanks a lot for your answer.
