### ISSUE TITLE
[bug]: strange no-deterministic configuration error parsing 

### ISSUE THREAD

**Issue by vincenzopalazzo** [lightningnetwork/lnd#8286]
### Background

I have my lnd configuration in a separate SSD and also the configuration, however, looks like the configuration is not loaded correctly.

### Your environment

* version of `lnd`: commit ac9ca024a4bfb2890e2cd450666bd94d221fe172
* which operating system (`uname -a` on *Nix): Linux vincenzopalazzo-arch-dev 6.1.67-1-lts
* version of `btcd`, `bitcoind`, or other backend: neutrino
* any other relevant environment details: no really

### Steps to reproduce

```
➜  lnd git:(master) ./lnd-debug --configfile /run/media/vincent/VincentSSD/.lndir/lnd.conf
failed to load config: ValidateConfig: either --bitcoin.mainnet, or bitcoin.testnet,bitcoin.simnet, bitcoin.regtest or bitcoin.signet must be specified
➜  lnd git:(master) ./lnd-debug --configfile /run/media/vincent/VincentSSD/.lndir/lnd.conf
failed to load config: ValidateConfig: either --bitcoin.mainnet, or bitcoin.testnet,bitcoin.simnet, bitcoin.regtest or bitcoin.signet must be specified
➜  lnd git:(master) ./lnd-debug --lnddir /run/media/vincent/VincentSSD/.lndir
failed to load config: ValidateConfig: either --bitcoin.mainnet, or bitcoin.testnet,bitcoin.simnet, bitcoin.regtest or bitcoin.signet must be specified
➜  lnd git:(master) ./lnd-debug --lnddir /run/media/vincent/VincentSSD/.lndir
failed to load config: ValidateConfig: either --bitcoin.mainnet, or bitcoin.testnet,bitcoin.simnet, bitcoin.regtest or bitcoin.signet must be specified
➜  lnd git:(master) ./lnd-debug --lnddir /run/media/vincent/VincentSSD/.lndir
2023-12-17 21:05:34.330 [WRN] LTND: could not find option group `Ltcd'
2023-12-17 21:05:34.330 [INF] LTND: Version: 0.17.0-beta commit=, build=development, logging=default, debuglevel=info
2023-12-17 21:05:34.330 [INF] LTND: Active chain: Bitcoin (network=testnet)
2023-12-17 21:05:34.331 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2023-12-17 21:05:34.332 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
```

### Expected behaviour

Should work at the first attempt

### Actual behaviour

Sometimes the configuration is parsed in the wrong way

**Comment by guggero** [comment]
I think this might rather be an issue with the config file itself. Unfortunately the library we use to parse the config file is a bit weird around the section headers (e.g. `[Application Options]`).
If you use those section headers, then you have to use them everywhere, before each new block.
Or if you don't want to use them, you need to remove _all_ of them.

> `LTND: could not find option group `Ltcd'`

This is what makes me think this is an issue with the file not being parsed correctly rather than the path itself.

**Comment by hieblmi** [comment]
> 
> > `LTND: could not find option group `Ltcd'`
> 
> This is what makes me think this is an issue with the file not being parsed correctly rather than the path itself.

Wasn't Ltc support removed from LND which included this option?

**Comment by guggero** [comment]
Ah yes, that as well.

**Comment by guggero** [comment]
@vincenzopalazzo if you could send me the config file as it is now (while it is causing the weird behavior) in its full content in a DM somewhere, that would be great. Maybe I can then reproduce the issue.

**Comment by vincenzopalazzo** [comment]
@guggero yesh I can send it to you, but I copied and paste from the documentation itself https://docs.lightning.engineering/lightning-network-tools/lnd/lnd.conf

Maybe it is not the update one?

**Comment by guggero** [comment]
Yeah, that document is probably not up-to-date and also just an old copy of the `sample-lnd.conf` file itself... I'll see if we can update it.

Though I guess it does say "This file exists purely for illustrative purposes, and do not serve as a template for an ideal node".

**Comment by vincenzopalazzo** [comment]
Ah yeah

>Though I guess it does say "This file exists purely for illustrative purposes, and do not serve as a template for an ideal node".

I read this as "Do not use without modifying it because it is all commented" :) my bad

**Comment by vincenzopalazzo** [comment]
Ok using the sample-lnd.conf fixed the problem, thanks @guggero
