### ISSUE TITLE
Convert signatures sent over the wire to a bare 64-byte encoding

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#83]
## Issue 

Currently within the codebase, signatures are sent over using Bitcoin's DER encoding. Within the current spec draft, signatures instead are sent using only `64-bytes` meaning the `R` and `S` values are sent over as raw big-endian integer values. 

## Steps to Completion 

In order to conform to the spec, the `lnwire` package should be modified to encode signatures as `64-bytes` rather than Bitcoin's (possibly) variable length format. 

Additionally sections of the code within the daemon itself will also need to be modified to properly parse the new signature encoding.

**Comment by bryanvu** [comment]
Will take this one.

**Comment by aakselrod** [comment]
I'll take this one; @bryanvu is aware.

**Comment by aakselrod** [comment]
Opened PR #86 to resolve this issue.
