### ISSUE TITLE
Error in connecting  to my node by trying some different node

### ISSUE THREAD

**Issue by Dhara-Openxcell** [lightningnetwork/lnd#831]
I  have created my own node ,as shown below:

root@admin:~$ lncli getnodeinfo 03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6{    "node": {        "last_update": 1520946982,        "pub_key": "03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6",      
  "alias": "03371209cf3513eed05c",      
  "addresses": [            {                "network": "tcp",                "addr": "172.17.0.1:9735"            }        ],        "color": "#3399ff"    },    "num_channels": 9,    "total_capacity": "8100000"}

Now when I try to connect this node by   any other node , I am getting following error:
"Connection Timeout . Cannot Find Peer id".

**Comment by Roasbeef** [comment]
How are you trying to connect to the peer? There's no such thing as "peer id" in the current code.

**Comment by Dhara-Openxcell** [comment]
The command i am using is:
"_lncli connect 03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6@172.17.0.1:9735_"

"_openchannel --node_key=03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6 --local_amt=1000000_"

and i am getting this error: 
"_Open New Channel Create a new channel with others.
 Dashboard Open New Channel
 Error
connection attempt to 03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6@172.17.0.1:9735 is pending_"
"_Open New Channel Create a new channel with others.
 Dashboard Open New Channel
 Error
unable to find peer nodeID(03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6), peerID(0)_"

Does anyone have idea about that?

**Comment by Roasbeef** [comment]
> connection attempt to 03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6@172.17.0.1:9735 is pending"

That means that the connection attempt you have to `03371209cf3513eed05c103973276676ae0602370077dbd1c79bd101198eb828f6` is pending. You can't open a channel with the peer until you actually connect to them.

**Comment by halseth** [comment]
There's also a `--connect=host:port` flag that can be passed to `openchannel`.

**Comment by Dhara-Openxcell** [comment]
Do you have any idea why i am not able to connect to peer. My peer have public ip and visible on acinq explorer, but still can't open a channel via other peer.
How to set external ip for my node so that other nodes can open channels with me?

Thanks in advance

**Comment by halseth** [comment]
You must make sure you're not behind a firewall blocking the port (default 9735).

**Comment by Dhara-Openxcell** [comment]
![screen shot 2018-03-14 at 4 12 42 pm](https://user-images.githubusercontent.com/35023605/37397930-e8fe48bc-27a2-11e8-8011-c09d1949ac01.png)

This is the status of my firewall . Still its not working. @halseth

**Comment by halseth** [comment]
Please Google "forwarding ports" and then use something like this to check that you port is open: https://www.yougetsignal.com/tools/open-ports/

**Comment by Dhara-Openxcell** [comment]
Thanks for quick reply
![screen shot 2018-03-14 at 4 48 51 pm](https://user-images.githubusercontent.com/35023605/37399556-f79634b6-27a7-11e8-94e8-2f038140a4b1.png)

how to open port for this ip address as shown in figure @halseth 
Can u help me with this issue as i am begineer?

Thanks

**Comment by halseth** [comment]
Just goole something like "how to forward ports", there are plenty of guides out there :)

If you know what router you have, you can also refer to its manual.

**Comment by Dhara-Openxcell** [comment]
I am providing --externalip=x.x.x.x randomly like this 254.1.2.3
so will it work or we have to provide particular ip only

Thanks

**Comment by halseth** [comment]
You'll have to provide your real, non-random IP.

Closing, as this is not an issue with `lnd`.
