### ISSUE TITLE
[bug]: error in lnrpc

### ISSUE THREAD

**Issue by snakedye** [lightningnetwork/lnd#8326]
### Background

lnrpc fails to compile.

### Your environment

# System Details Report
---

## Report details
- **Date generated:**                              2023-12-30 09:30:17

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. ZenBook UX462DA
- **Memory:**                                      12.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 3700U with Radeon™ Vega Mobile Gfx × 8
- **Graphics:**                                    AMD Radeon™ Vega 10 Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            UX462DA.307
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.8-200.fc39.x86_64

## Editor / Go

- **go version** : go1.21.5 linux/amd64
- https://flathub.org/apps/com.visualstudio.code

### Steps to reproduce

Add the latest version of lnrpc and trying to run a test.

### Expected behaviour

The code should compile.

### Actual behaviour

```
Running tool: /usr/lib/sdk/golang/bin/go test -timeout 30s -run ^TestMint$ lsat

# github.com/lightningnetwork/lnd/lnrpc
/home/snakedye/.local/go/pkg/mod/github.com/lightningnetwork/lnd@v0.17.3-beta.rc1/lnrpc/rpc_utils.go:32:3: unknown field UseHexForBytes in struct literal of type protojson.MarshalOptions
/home/snakedye/.local/go/pkg/mod/github.com/lightningnetwork/lnd@v0.17.3-beta.rc1/lnrpc/rpc_utils.go:40:3: unknown field UseHexForBytes in struct literal of type protojson.UnmarshalOptions
```

**Comment by bitromortac** [comment]
Do you try to include lnrpc in your own project? If so, you would need to add `replace google.golang.org/protobuf => github.com/lightninglabs/protobuf-go-hex-display v1.30.0-hex-display` to your go.mod (see lnd's go.mod file for an explanation).

**Comment by guggero** [comment]
Yes, the `replace` directive mentioned by @bitromortac should solve this problem. Unfortunately there isn't an easier way to allow us to add some features to the `protobuf` library without also needing this replace directive.

**Comment by AbhayBhan** [comment]
Can Confirm that the replace directive fixes this issue. 

`replace google.golang.org/protobuf => github.com/lightninglabs/protobuf-go-hex-display v1.34.2-hex-display`
