### ISSUE TITLE
Never returning an error on a function returning an error

### ISSUE THREAD

**Issue by markettes** [lightningnetwork/lnd#8344]
### Background
This function doesn't return any error and checks for error next.
https://github.com/lightningnetwork/lnd/blob/6bd30047c1b1188029e8af6ee8a135cf86e7dc4b/lnrpc/routerrpc/router_server.go#L321

### Expected behaviour
Returning an error.

### Actual behaviour
Not returning errors.

**Comment by hieblmi** [comment]
In the latest master version this seems to be ok https://github.com/lightningnetwork/lnd/blob/695bfc841456816d20b8a8e3b2674f2369334cc3/lnrpc/routerrpc/router_server.go#L351

**Comment by yyforyongyu** [comment]
Closing as the referenced code 6bd30047c1b1188029e8af6ee8a135cf86e7dc4b seems to be 0.16.4, while in our latest branch this is no longer the case.

**Comment by ellemouton** [comment]
I think @markettes is saying that the actual method `SendPaymentAsync` can not possibly return an error. Which is still correct with latest master

**Comment by hieblmi** [comment]
True, the returned `error` is a leftover from de01e412.

**Comment by yyforyongyu** [comment]
oh I see, fix coming up now

**Comment by markettes** [comment]
Thanks!! :D
