### ISSUE TITLE
[feature]: Support Configuring IPv4/IPv6 primary over TOR in uri/address list

### ISSUE THREAD

**Issue by zapomatic** [lightningnetwork/lnd#8349]
**Is your feature request related to a problem? Please describe.**

My node is configured in hybrid mode with IPv4 and tor and exposes itself on ipv4 using the `externalhosts` config. However, the tor uri is listed as the first entry in the node `uris`:
```
"uris": [
    "026d0169e8c220d8e789de1e7543f84b9041bbb3e819ab14b9824d37caa94f1eb2@adbn42l4svmgz6i44s4jt2pqngyq5h6bpz6frcgv7yxvf3hkukftheqd.onion:9735",
    "026d0169e8c220d8e789de1e7543f84b9041bbb3e819ab14b9824d37caa94f1eb2@5.78.104.214:38297"
],
```
This is leading prospective clients to think that I prefer tor over clearnet. In the case of Amboss, my listing shows tor as the primary address for connections and is causing a problem when trying to buy a magma order from someone who is configured to deny tor purchases: https://amboss.space/node/026d0169e8c220d8e789de1e7543f84b9041bbb3e819ab14b9824d37caa94f1eb2

**Describe the solution you'd like**

Provide the ability in lnd.conf to specify the ordering of uris, or that one connection type should be primary.

Forgive me if I missed an obvious config somewhere but I have been unable to find a way to re-order this...

**Comment by Roasbeef** [comment]
This assumes all clients always select the very first address though? I don't think there's any sort of standard or uniform behavior there.

**Comment by zapomatic** [comment]
@Roasbeef that's fair. I think we can just push this to clients to go through the array and order them by ipv4/ipv6/tor or whatever they prefer.
