### ISSUE TITLE
Add value for externalip to certificate SANs

### ISSUE THREAD

**Issue by stevenroose** [lightningnetwork/lnd#835]
Currently only `localhost` and the machines hostname are added. Adding the value for `--externalip` allows the RPC to be used outside of the host machine.

**Comment by Roasbeef** [comment]
I think the `--tlsextraip=` flag handles this?

**Comment by dabura667** [comment]
Is there a --tlsextradomain? That way we could add a domain to the tls cert at startup?

**Comment by Roasbeef** [comment]
Note _yet_, but would certainly accept a PR adding it!

**Comment by stevenroose** [comment]
I always thought `externalip` took domains as well, both here and in btcd. I must have been mistaken. `tlsextraip` did the job, domains is not an alpha feature :)
