### ISSUE TITLE
Unacceptable channel constraints: minimum HTLC value is too large: 0 ?

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#836]
See https://github.com/ElementsProject/lightning/issues/1213

**Comment by Roasbeef** [comment]
This has been fixed on our side. Seems the user was connecting to an `lnd` node that hasn't yet updated.

**Comment by Roasbeef** [comment]
Basically we had singed ints in most places, when it should've actually been unsigned.

**Comment by rustyrussell** [comment]
Ack, thanks!
