### ISSUE TITLE
[bug]: CPFP in force close is too aggressive

### ISSUE THREAD

**Issue by Impa10r** [lightningnetwork/lnd#8370]
### Background

Had a force close with a fee rate 53.1 sat/vB, which I was happy to wait out. LND immediately bumped the fee to effective rate 254, overpaying the market x4. Moreover, it took several small UTXOs from the wallet, making me pay 403,525 sats ($181.83) on fees. My commitment fee limit is 100 sats/vB.

https://mempool.space/tx/294bff64bde2f215df8367b4f84264977d0555050f26f9262e4aa7722095a140

### Your environment

* version of `lnd` 0.17.3-beta
* which operating system (`uname -a` on *Nix) umbrel
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core 25.1.0
* any other relevant environment details

### Steps to reproduce

Cannot be reproduced it regrest/testnet since they have no chain fee volatility 

### Expected behaviour

Better estimate chain fees. Allow to specify UTXO preference in automatic fee bumps.

### Actual behaviour

It does not care to save my money

**Comment by zynos** [comment]
Maybe related 
https://github.com/lightningnetwork/lnd/issues/8299
