### ISSUE TITLE
[spec]: retransmit `shutdown` on reestablish

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#8397]
[BOLT2](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#message-retransmission) states that "upon reconnection, if [a node] has sent a previous `shutdown`, [it] MUST retransmit `shutdown`".

We currently do this if the channel has status `ChanStatusCoopBroadcasted`:
https://github.com/lightningnetwork/lnd/blob/ba4021cad98887b2a63be6b61bf0ad46b07c221a/peer/brontide.go#L905-L909

Prior to https://github.com/lightningnetwork/lnd/pull/8167 this means that if `shutdown` was sent, it will be re-transmitted since `initChanShutdown` calls `MarkCoopBroadcasted`:
https://github.com/lightningnetwork/lnd/blob/ba4021cad98887b2a63be6b61bf0ad46b07c221a/lnwallet/chancloser/chancloser.go#L342-L350

With #8167, the call to `MarkCoopBroadcasted` is delayed until we are ready to send `closing_signed`. This means that the logic in `restartCoopClose` won't be called before this point. Because of this, if LND has sent `shutdown`, but hasn't reached the point where it sends `closing_signed`, and then disconnects with its peer, LND won't retransmit `shutdown`. To fix this, some state needs to be persisted right before we send `shutdown` such that LND can restart the coop close process on reestablish. This is especially important in light of https://github.com/lightningnetwork/lnd/issues/8393 where LND <-> LND coop close may not happen on restart as neither side re-transmits `shutdown`.

Additional things to take note of:
- the pkscript that is re-transmitted in `shutdown` must be identical to the prior `shutdown`'s pkscript
- if an `update_*` and `commit_sig` are owed as well as a `shutdown`, the original ordering must be maintained

**Comment by Roasbeef** [comment]
Note that this new scenario is only applicable post #8167. So we'll need to drive that to final completion first, then take this on.
