### ISSUE TITLE
[bug]: Missing ots files on v0.17.4 release

### ISSUE THREAD

**Issue by twofaktor** [lightningnetwork/lnd#8465]
Trying OTS verification to install the new v0.17.4 release, I realize the OTS files do not exist on the GitHub assets

![imagen](https://github.com/lightningnetwork/lnd/assets/89636253/31516608-060a-4bbc-aa92-c494bfc65fcb)

**Comment by Roasbeef** [comment]
Fixed! 

Thanks for verifying 😎
