### ISSUE TITLE
[bug]: Cannot install via go get

### ISSUE THREAD

**Issue by liorwavebl** [lightningnetwork/lnd#8495]
### Background

I'm trying to install `lnd` via `go get` command.

### Your environment

* which operating system (`uname -a` on *Nix)- Ubuntu 23.04
* version of `btcd`, `bitcoind`, or other backend- btcd v0.23.4

### Steps to reproduce
In terminal run `go get github.com/lightningnetwork/lnd`

### Expected behaviour

`lnd` package is installed correctly.

### Actual behaviour

During installation I'm getting this error: 

```
github.com/lightningnetwork/lnd imports
	github.com/roasbeef/btcwallet/waddrmgr: github.com/roasbeef/btcwallet@v0.11.0: parsing go.mod:
	module declares its path as: github.com/btcsuite/btcwallet
	        but was required as: github.com/roasbeef/btcwallet
```

**Comment by guggero** [comment]
You need to specify a specific version. See https://github.com/lightningnetwork/lnd/issues/5907 and https://github.com/lightningnetwork/lnd/issues/4021.
