### ISSUE TITLE
coin select: add coin selection strategy option to all on-chain RPCs

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#8498]
Comment from https://github.com/lightningnetwork/lnd/pull/8378:

              Yeah, I think that makes sense. Though it feels like that would be a different PR, as we'd probably also want to add such new parameters to the existing RPCs that currently use the config-level strategy (`FundPsbt`, `EstimateFee`, `SendCoins`, `SendOutputs`).

_Originally posted by @guggero in https://github.com/lightningnetwork/lnd/pull/8378#discussion_r1452286904_
            

Currently, the coin selection strategy can only be configured globally, via the `--coin-selection-strategy=[largest|random]` config/CLI option.
But because the strategy might be something a user wants to decide upon for every spend, a similar option should be added to all on-chain RPCs such as the ones mentioned in the original comment above.

**Comment by mohamedawnallah** [comment]
@guggero I found there is no CLI command for the `SendOutputs` RPC in the code and [Lightning Engineering API Docs - SendOutputs RPC Call](https://lightning.engineering/api-docs/api/lnd/wallet-kit/send-outputs/index.html). Is it okay to submit a PR for adding this feature + configuring the coin selection strategy option on the CLI level?

**Comment by guggero** [comment]
I don't think that is needed. That would require you to specify the pk scripts on the command line, which is kind of awkward. I think in the CLI the `sendcoins` command should cover all requirements. Or why exactly do you think we'd need a new command?
Also, please keep in mind that reviewing PRs, especially from new contributors, takes a lot of time from the maintainers. So if you really want to support the project, I'd suggest to also start looking into testing and reviewing pull requests from other people instead of writing more code.

**Comment by mohamedawnallah** [comment]
Got it @guggero! Thanks for clarifying :)
