### ISSUE TITLE
cfg: Surface Experimental OM Config Options in Protocol Cfg

### ISSUE THREAD

**Issue by carlaKC** [lightningnetwork/lnd#8536]
LND's [experimental](https://github.com/lightningnetwork/lnd/blob/master/lncfg/protocol_experimental_on.go#L16) custom messaging and feature big flags allow users to facilitate onion message forwarding on behalf of the network using [LNDK](https://github.com/lndk-org/lndk/releases/tag/v0.0.1), but they require users to re-build with the `dev` flag enabled. We'd had a [request](https://github.com/lndk-org/lndk/issues/94#issuecomment-1971911635) to move these options to the default LND build so that people don't need to re-compile/ can rely on release binaries. 

Opening this issue to propose moving those options to the [regular protocol cfg](https://github.com/lightningnetwork/lnd/blob/master/lncfg/protocol.go#L10).

**Comment by moneyball** [comment]
I believe this issue can now be closed https://github.com/lightningnetwork/lnd/pull/8744
