### ISSUE TITLE
[feature]: any way to identify a hold invoice

### ISSUE THREAD

**Issue by vanditshah99** [lightningnetwork/lnd#8539]
Is there a way to identify that the invoice is hold or not? Like can we have a field, let's say in decode invoice stating that, the following invoice is hold or not? 

The usefulness of this field will be for the application which are built on LND, as to stop processing hold invoices.

**Comment by ViktorTigerstrom** [comment]
Hi @vanditshah99! If you run:
`lncli listinvoices`

You can identify hold invoices in the result hold invoices will have the `r_preimage` field set to an empty string (`""`), and also importantly the `is_amp` field set to `false`.

Does that satisfy what you need, or do you need a specific field that signals if the invoice is a hold invoice or not?

**Comment by vanditshah99** [comment]
Hi Viktor, Invoices not necessarily need to belong to our lnd node, it can be generated from any other nodes/application, we use decode invoice api, which is indepedent of the node, so would it be possible to gather an information if the invoice is hold or not at decode invoice api?

**Comment by ViktorTigerstrom** [comment]
Unfortunately I don't think that would it would be possible to add support for that in a way that would apply to all hold invoices... I don't think you can identify an hold invoice when decoding it, as there's to the best of my knowledge, no unique combination of values that's set for a BOLT11 invoice that indicates that it's a hold invoice. At least in a way that is applicable for all hold invoices.

**Comment by ViktorTigerstrom** [comment]
There's a proposal to standardize the metadata of invoices that would make it possible support what you're requesting @vanditshah99:
https://github.com/lightningnetwork/lnd/issues/8445

Is ok for you that I close this issue in favor of that one, as that issue is actively being worked on?

**Comment by vanditshah99** [comment]
yes please, thanks for the help!
