### ISSUE TITLE
Force-closing channel stuck forever with blocks_til_maturity = 0

### ISSUE THREAD

**Issue by dlaptev** [lightningnetwork/lnd#8541]
### Background

I have the following pending channel that seems to be stuck with non-trivial `limbo_balance`, even though the `closing_txid` was confirmed >3 years ago:

```
        {
            "channel": {
                "remote_node_pub": "02731b798b39a09f9f14e90ee601afb6ebb796d6e5797de14582a978770b33700f",
                "channel_point": "8e07d28eb4de8cda303d058b7a51c03d3c5b4f4e02b1359b513e2e3d413d001e:1",
                "capacity": "2000000",
                "local_balance": "1484463",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_UNKNOWN",
                "commitment_type": "UNKNOWN_COMMITMENT_TYPE",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "closing_txid": "3d7e3d1ee8c5dd26f21dec3a894eab2da7e06fb9c42198734f01b0df1387d252",
            "limbo_balance": "1484463",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ],
            "anchor": "LIMBO"
        }
```

Looks similar to #6670, but I am not sure how to confirm that the funds are safe before I abandon the channel.

### Your environment

* version of `lnd`: `0.16.4-beta commit=v0.16.4-beta`
* which operating system (`uname -a` on *Nix): `Ubuntu 18.04.6 LTS (GNU/Linux 4.4.0-210-generic x86_64)`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v23.2.0`

**Comment by hieblmi** [comment]
Hi @dlaptev, thanks for submitting this issue. The limbo balance should've been sent back to your wallet in this transaction: https://mempool.space/tx/a3c7de86afcdaa9b80c492c905b91095c510703f0e96491c5188f6dca7c3cdea. Just lookup the `closing_txid`. If you ensured that you have the funds you can abandon the channel closure with `lncli abandonchannel`.

**Comment by dlaptev** [comment]
Thank you, both, for the suggestions! I confirmed that the funds actually went to the address that belongs to my wallet, so I can now safely abandon the channel! It seems like `height-hint-cache-query-disable` did not help to clear the channel, though.
