### ISSUE TITLE
[bug]: Don't allow unconfirmed Inputs for Channel Openings which are used/labeled by the sweeper subsytem.

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#8543]
Make sure we don't use sweeper related unconfirmed outputs for channel openings. Because those Inputs are actively rebroadcasted leading to RBF situations. This is especially critical for `zeroconf channels` which could potentially RBFed without the operator of the Channel noticing leading to fractional reserve problems where the node operator allocates more funds into channels than he actually has.

**Comment by ziggie1984** [comment]
relates to https://github.com/lightningnetwork/lnd/issues/8540.

**Comment by babikpatient6** [comment]
We definitely want to disallow anchor sweeps as inputs, they only cause mess. However do we also want to disallow commitment sweeps as inputs? I don't think I've ever seen commitment sweep being replaced. 🤔
