### ISSUE TITLE
[bug]: max_htlc_msat failed update does not report an error anymore?

### ISSUE THREAD

**Issue by bartoli** [lightningnetwork/lnd#8553]
I am on lnd 17.0.0

I used to get errors when setting max_htlc_msat to 0 on some channels where min_htlc was not null (in 17.0.0 also).

But a few days ago,  the script that updates max_htlc value for my channels got stuck trying to update the value for a channel to 0.
Indeed, now it seems that doing it does not report anymore the error that max cannot be below min? But also does not set the 0 value

So my script got stuck in a loop consistently picking the same channel to try to update

Are there some conditions where this error is not triggered? Shouldn't the action report the error if it still does nothing?

**Comment by ViktorTigerstrom** [comment]
Hi @bartoli,
If you specify `--max_htlc_msat=0` in the `updatechanpolicy` rpc call, that gets treated as if you did not specify any `max_htlc_msat` value at all. The `max_htlc_msat` for the channel update for the channel(s) will then remain at the value they were previously set to.
Now if you specify a `--min_htlc_msat` value at the same time, you'll only get an error if that value is higher than the `max_htlc_msat` value. Let's say you had previously set `--max_htlc_msat=10000` in a previous call, and now make a `updatechanpolicy` call with `--max_htlc_msat=0` & `--min_htlc_msat=100`, that will succeed as the `max_htlc_msat` will remain at `10000` as setting the param to `0` will be treated as if the param wasn't set, and `min_htlc_msat=100` < `--max_htlc_msat=10000`.
Though if you'd make a call with `--max_htlc_msat=0` & `--min_htlc_msat=10001`, that would fail as `min_htlc_msat=10001` > `--max_htlc_msat=10000`.

Hope that explains the behaviour you're experiencing!

**Comment by bartoli** [comment]
Oh ok, thanks that makes sense. I'll check the actual values after the command instead of relying on the succes of the command.
And also remember to think about it when in RTL, which also reports no error in those cases.
