### ISSUE TITLE
Is payment_hash not required in SendRequest?

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#856]
I'm looking at your example here, and SendRequest only has a dest and amt, but no payment_hash. How is it possible to send a payment with no payment_hash?

https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md#bidirectional-streaming-rpc

When I look at BOLT 11, the payment_hash is a required field.

**Comment by Roasbeef** [comment]
Ah, that's an incomplete example. If you [take a look at our API docs](http://api.lightning.community/#sendpayment) you'll see all the available arguments for the call.

**Comment by AndySchroder** [comment]
Okay. Thanks, that makes much more sense. A couple other questions I have about your API documentation:

1. Invoice has a field r_hash. SendRequest has a field payment_hash. Assuming both nodes are running lnd, is this the same thing, and if so, why are the names different?

2. When running LookupInvoice, does the Invoice object that is returned include a "value" field if the original invoice did not have that defined? I'm just trying to understand if I can detect how much was paid to an invoice if the invoice doesn't have a required amount.

**Comment by Roasbeef** [comment]
> Invoice has a field r_hash. SendRequest has a field payment_hash. Assuming both nodes are running lnd, is this the same thing, and if so, why are the names different?

Yes they're identical. No particular reason why the name are different, iirc the definition of that proto outdates the creation of BOLT 11. 

> When running LookupInvoice, does the Invoice object that is returned include a "value" field if the original invoice did not have that defined? I'm just trying to understand if I can detect how much was paid to an invoice if the invoice doesn't have a required amount.

Yep, although I _think_ there might be a lingering bug where if we get a payment from an invoice that didn't specify a value, then we won't record that value. Easy fix though...(goes to fix)

**Comment by AndySchroder** [comment]
By "won't record that value", do you mean it works, but if I shutdown lnd and restart the value is lost? Or the "value" field exists, but it is always equal to 0?

What do you mean by "goes to fix"?

**Comment by Roasbeef** [comment]
I mean that atm, it'll show the invoice as paid, but we don't yet store the amount of the invoice. 

> What do you mean by "goes to fix"?

Was meant in jest, that the fix was so small, I immediately coded it locally to start to test the fix.

**Comment by wpaulino** [comment]
Closed by #856.
