### ISSUE TITLE
[bug]: sendcoins fails in bitcoind after v27

### ISSUE THREAD

**Issue by YusukeShimizu** [lightningnetwork/lnd#8571]
### Background
`sendcoins` fails with bitcoin core version 27.

#### bitcoind before v26.0
`lnd sendcoins bcrt1qgy6djk4t4e3l6ldu29r4834zsye2dv9s2h8t5f 1000` succeed.

#### bitcoind v27.0
`lnd sendcoins bcrt1qlzjdmnhhglca7d6l6vpc89jkvly7hq9qs8g6kl 1000`

```sh
rpc error: code = Unknown desc = unmatched backend error: -8: Fee rates larger than or equal to 1BTC/kvB are not accepted
```

### Your environment

* version of `lnd` : v0.17.2-beta
* which operating system : Darwin Kernel Version 23.2.0 arm64
* version of `bitcoind`: v27.0rc1

### Steps to reproduce
Prepare regtest environment, start lnd with bitcoind v27.0 backend and execute the following command.
`lnd sendcoins --addr <addr> --amt <amt>`

### Expected behaviour
Sendcoins should succeed.

### Actual behaviour
Sendcoins fails with the following error.
```sh
rpc error: code = Unknown desc = unmatched backend error: -8: Fee rates larger than or equal to 1BTC/kvB are not accepted
```

### Additional context
This is found in the peerswap operation check.
https://github.com/ElementsProject/peerswap/issues/289

Below is my guess.

#### Possible cause
`maxfeerate` is set to [1e8 / 10(sat/kb)](https://github.com/btcsuite/btcd/blob/master/rpcclient/rawtransactions.go#L370) as a parameter when calling `SendRawTransaction`.
But [BTC/kvB](https://bitcoincore.org/en/doc/26.0.0/rpc/rawtransactions/sendrawtransaction/) is the expected value, so the units would be wrong.

#### Reason for error in v27.0
https://github.com/bitcoin/bitcoin/pull/29434 adds a sanity check for maxfeerate and does not accept values above 1BTC/kvB.
The error message in that case is

> Fee rates larger than or equal to 1BTC/kvB are not accepted

**Comment by YusukeShimizu** [comment]
I have created a PR to clarify my issue

https://github.com/btcsuite/btcd/pull/2142

**Comment by Roasbeef** [comment]
Should still be open as we need to merge #8573 still.

**Comment by blckbx** [comment]
Also seeing this on a sweep tx of a force close on testnet:
```
[INF] SWPR: Candidate sweep set of size=1 (+1 wallet inputs), has yield=0.00000159 BTC, weight=677
[INF] SWPR: Creating sweep transaction 270669fef2898be93b1711c8c5e46272e7da0565aa503ced16ed9ee5dcd7ac97 for 2 inputs (0b7e3cc018368257d4c3ec0e1da41a9cd5e1f489c1a864bf2091209d60029942:0 (CommitmentAnchor), 8d15a2f128a874e07f8ff221462d2f7df28bdc480320beab8fee100d0336f67a:7 (TaprootPubKeySpend)) using 253 sat/kw, tx_weight=725, tx_fee=0.00000183 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
[INF] LNWL: Inserting unconfirmed transaction 270669fef2898be93b1711c8c5e46272e7da0565aa503ced16ed9ee5dcd7ac97
[INF] LNWL: 270669fef2898be93b1711c8c5e46272e7da0565aa503ced16ed9ee5dcd7ac97: broadcast failed because of: unmatched backend error: -8: Fee rates larger than or equal to 1BTC/kvB are not accepted
[INF] LNWL: Removed invalid transaction: 270669fef2898be93b1711c8c5e46272e7da0565aa503ced16ed9ee5dcd7ac97
[ERR] SWPR: input cluster sweep: unable to sweep inputs: publish tx: unmatched backend error: -8: Fee rates larger than or equal to 1BTC/kvB are not accepted
```

**Comment by twofaktor** [comment]
Thank you for your advice

I can see in the description:

> 
>     bitcoind before v26.0
>     lnd sendcoins bcrt1qgy6djk4t4e3l6ldu29r4834zsye2dv9s2h8t5f 1000 succeed.
> 

Does that mean it also happens with v26.1 same as v27?

**Comment by Roasbeef** [comment]
The fix has been merged into master, so things should work now. 

I think we're looking at making a v0.17.5 release for those that are quick to upgrade to the latest version of bitcoind.
