### ISSUE TITLE
Cannot accept channel connections from other nodes

### ISSUE THREAD

**Issue by kishancr7** [lightningnetwork/lnd#858]
We have started our lnd node on testnet using this command and our btcd is also  running in backend

" lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --btcd.rpcuser=kishan --btcd.rpcpass=kishan --externalip=103.240.162.84 "

Below we are pasting photo of our node on World Map of " https://explorer.acinq.co/#/n/039475b7a118118e50a5a183c2cb681b9f659c6f5c35fff14a86d27fa84cdd04bc"

![screenshot from 2018-03-16 11-41-18](https://user-images.githubusercontent.com/34764107/37506304-3a4b4a36-290f-11e8-8d67-bc6e5ba6a179.png)

All the things like connection to other nodes ,payments a,etc . are all working great.
But when I try to open channel to my node using:

1. Using Eclair Mobile Test application 
2. Using Lnd.fun 
3. Using Another node running on another IP

we tend to get the following error 
"Cannot open connection.Connection Failed "

So, I cannot able to open channel from other node to my node.

**Comment by Metalsprzet** [comment]
2018-03-16 09:51:00.848 [DBG] PEER: Received NodeAnnouncement(node=024a893cd5387a357cf3da416abc63b47c7c23565990ab86701c1fab924c169dc2, update_time=2018-01-19 19:47:58 +0100 CET) from 5.102.147.62:9735

After received this  my lnd shutdown. It is old update time.

**Comment by halseth** [comment]
Make sure the port `9735` is open.

**Comment by kishancr7** [comment]
![screenshot from 2018-03-16 15-47-39](https://user-images.githubusercontent.com/34764107/37515718-be9c4cbe-2931-11e8-9580-edc41e9e9b01.png)
@halseth 

This is the status of my ip and port . Any other solution  can be done?

Thanks

**Comment by halseth** [comment]
It's hard to tell, I just tried connecting to your node, no success. My guess is that the port is not forwarded correctly to the node where LND is running.

**Comment by kishancr7** [comment]
thanks for helping me .

Is there any other way I can solve the issue. Or help me in "port forwarding in correct manner "

And in command prompt how can I check that my port is open for lnd and where actually lnd is running in background.

And is there any way to get the details about the ,nodes which are trying to connect my node

can you suggest any tool or applications which I can use to open channel with my node

Thanks again. @halseth

**Comment by halseth** [comment]
`netstat -a` should show all the ports you are listening on. For the actual port forwarding you must consult your router's manual or find a tutorial online.

**Comment by kishancr7** [comment]
![screenshot from 2018-03-16 18-03-36](https://user-images.githubusercontent.com/34764107/37520807-7d6cd4c6-2944-11e8-965b-84b66ce55805.png)

Is this right or the port has some issues. It shows tcpv6 and [::]:9735. There is no ip address shown before the port number.
So Is it OK or have some issues?

Thanks again @halseth

**Comment by kishancr7** [comment]
Actually I can not be able to understand what you want to say ..So can you point this issue in more detail.

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 16, 2018 at 2:33 PM, Metalsprzet<notifications@github.com> wrote:   
2018-03-16 09:51:00.848 [DBG] PEER: Received NodeAnnouncement(node=024a893cd5387a357cf3da416abc63b47c7c23565990ab86701c1fab924c169dc2, update_time=2018-01-19 19:47:58 +0100 CET) from 5.102.147.62:9735

After received this my lnd shutdown. It is old update time.

**Comment by Roasbeef** [comment]
If you're behind a NAT, then you won't be able to accept incoming connections. That may be fine though, as you can still establish outbound payments.

**Comment by kishancr7** [comment]
Hello  Roasbeef,

Can you say what is NAT ? And how can we disable it to accept incoming connections ?

Thanks

**Comment by halseth** [comment]
@kishancr7 Not trying to be rude by any means, but this is not really a question that belongs on this repo. NAT is basic networking terminology, and you can easily find tons of information about it by googling it. Thanks.
