### ISSUE TITLE
running last version of lnd failed

### ISSUE THREAD

**Issue by ghanavati27** [lightningnetwork/lnd#860]
I rebuild lnd from source code and trying to run it with flags. 
lnd.exe --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=myuser --bitcoind.rpcpass=mypass --bitcoind.zmqpath=tcp://127.0.0.1:29000  --externalip=myip --noencryptwallet

![lnd](https://user-images.githubusercontent.com/33449079/37520407-186629f2-28da-11e8-9eee-cb6379703471.PNG)

**Comment by Roasbeef** [comment]
You need to ensure that you're setting the arguments properly (password, etc). Ensure that your `bitcoind` nodes is listening on the proper RPC port, and also that you've set up `zmq` properly. Nothing as far as our connection to `bitcoind` has changed recently.

**Comment by ghanavati27** [comment]
I'm ensure my settings are correct. my lnd instance working very well with a clean lnd.conf (take a look it in https://github.com/lightningnetwork/lnd/issues/861)

**Comment by Roasbeef** [comment]
Now that #861 has been resolved, is this one still lingering?

**Comment by ghanavati27** [comment]
@Roasbeef , this issue also resolved . thank you
