### ISSUE TITLE
[bug] SendCoins request using CraftSweepAllTx swapped function arguments "maxFeeRate" and "feePerKw"

### ISSUE THREAD

**Issue by Chinwendu20** [lightningnetwork/lnd#8608]
https://github.com/lightningnetwork/lnd/blob/1d61de28c02893dea308231a2c596457557e396a/rpcserver.go#L1366

The maxFeeRate is used for the feerate in the code linked above. I am wondering if this is an oversight or maybe it is intentional. If this is intentional, then maybe add comment explaining why?

**Comment by ziggie1984** [comment]
Thanks for reporting this issue, yes this is definitely a bug, fortunately it has no effect on the logic but we should change this definitely. 

Do you want to provide a fix ?

**Comment by Chinwendu20** [comment]
> Thanks for reporting this issue, yes this is definitely a bug, fortunately it has no effect on the logic but we should change this definitely.
> 
> Do you want to provide a fix ?
> 
> EDIT:
> 
> This behaviour applies to both cases in the code where we use `CraftSweepAllTx`
> 
> and I think a unit test is missing for the fee-capping, there we would have caught this issue supplying a feerate of 0 which would have resulted in a transaction with the MaxFeeRate selected, so definitely need to patch a test as well.

Thanks a lot, I think there is a [unit test for the fee capping](https://github.com/lightningnetwork/lnd/blob/24fa35ec8015073cb792190d755f9dae10f4a649/sweep/weight_estimator_test.go#L84-L85). It is just the caller, `SendCoins` function that appears not to be calling it correctly. Maybe we would switch the args and then see if anything breaks in the CI. We have a number of itests that call SendCoins already for their tests.

**Comment by ziggie1984** [comment]
You are right, just switch the values,  because we validate the sweeper max default feerate we would have never been able to trigger a misbehaviour of the fee function in any ways (even itests). So switching the values should be the way to go here.
