### ISSUE TITLE
Better API support for inbound payments

### ISSUE THREAD

**Issue by RHavar** [lightningnetwork/lnd#862]
It's not really obvious to me how use the lnd API for robustly handling inbound payments. `ListInvoices` returns too much (everything) to process, and `SubscribeInvoices` is not super useful as I need to handle the cases I missed some messages (e.g. problems in my service or what ever).

Ideally I'd be looking for something like `ListInboundPayments` where each was given a monotonically increasing id, and I could also provide a `since` to get all payments since the last one I processed. This would make it really easy to implement a robust polling mechanism that would never skip any payments. 

And to optimize over a manually polling, it'd be good to have a `SubscribeInbound` that just notifies when ever there's a new inbound payment, so I can trigger my checking logic.

(Sorry about the horrible issue, just my thoughts after spending a few minutes playing with the API)

**Comment by Roasbeef** [comment]
There's already `SubcribeInvoices` streaming RPC to be notified of new incoming payments. We can easily add timestamp (and offset) based pagination to `ListInvoices` to ensure you pick up from a known point.

**Comment by RHavar** [comment]
Having a `since` argument would be great, to pick up from a known point (the last inbound payment you processed)

However, I'm not sure that `Invoices` is really the right granularity for an API. At least I would definitely rather a sort of `InvoiceEvent`type object(s), which represents an event to an invoice, rather than working with mutable Invoices.

Also one issue with timestamp based offsets I've experienced in APIs is ambiguity/complication around things that happen in the same millisecond. Unless you can guarantee that timestamps monotonically increase, I'd definitely rather just an `id` counter

**Comment by shesek** [comment]
Was just going to open an issue about the same thing. Would love to have this feature as well.

c-lightning has a similar feature for its [`waitanyinvoice`](https://github.com/ElementsProject/lightning/blob/master/doc/lightning-waitanyinvoice.7.txt) RPC call, in the form of a `lastpay_index` field and argument.

I also think that an `InvoiceEvent` type object with just the relevant fields (`settle=true` and `settle_date`, possibly also `value_received` [for overpaid or any-amount invoices, which appears to be missing?]) would be nice to have, but that's not high-priority for me.

**Comment by NicolasDorier** [comment]
The way c-lightning is doing with `lastpay_index` is perfect. When my server is starting I call waitanyinvoice with `999999` as index, so it returns when the next invoice is received. 

When I receive an invoice `lastpay_index` is set to the invoice's value.

**Comment by RHavar** [comment]
Yup the whole `pay_index` in `c-lightning` is really perfect, as a "merchant" sort of use-case it's exactly what I need to be able to reliably process payments.
