### ISSUE TITLE
Problem with update_channel gossip propagation across LND nodes (wrongly marked as zombie channels?).

### ISSUE THREAD

**Issue by urza** [lightningnetwork/lnd#8624]
I have small routing node.
It is running Core Lightning 24.02.
My node is active for more than 2 years and is running on proper server 24/7 the whole time.
It has just few channels, because I am not trying to be big routing node, the purpose of this node is to serve me and my friends and family.

Recently I noticed that LND nodes that are not my direct peers have very wrong information about my channels.

For example here is my **direct peer** (we have channel) with LND node, here is how his node sees my channels:
https://gist.github.com/urza/f5e758b2fdc56f79c2d64e02e43084fd
**They see all 7 channels in active state with correct fee info.**

But here is LND node just **one hop away** sees my channels:
https://gist.github.com/urza/05d2c97cee6c948500a2229c3c91fa2c
**They only know about 2 of my channels!! The rest is not even listed!**

When I asked if they would run getchaninfo about one of the missing channels, the direct LND peer returned correct information about the channel, however the one hop away node returned:

`[lncli] rpc error: code = Unknown desc = edge marked as zombie`

However the channel is alive and working. I tried to rebalance this channel from both sides and it worked without any issues.

Also for the last few days I changed fees on all of my channels once a day to be sure that update_channel gossip is sent out about all my channels.

I also connected to other nodes besides those that I have channel with. CLN should be sending update_channel to all connected peers.

But still the same result.

My direct peers and CLN nodes that are farther away see my channels correctly, but LND nodes that are not my direct peers see wrong information and miss most of my channels.

From this I suspect that LND nodes somehow mark most of my channels as zombie and refuse to propagate the gossip.

This is bad for me as it decreases my ability to receive payments if senders might not know about most of my channels. And is also bad for network if LND nodes have such inaccurate information about the network graph.

**Comment by urza** [comment]
I connected to a friend with LND node (we don't have channel) and he has this in his terminal:

GossipSyncer - applying new update horizon: start=2106-02-07 07:23:15, end=2242-03-16 13:56:30

![image](https://github.com/lightningnetwork/lnd/assets/189804/de9eeffe-abbd-405c-a32c-5fb5292804d7)

We have no idea what it means, but it doesn't look healthy :)

**Comment by ellemouton** [comment]
For the part relating to channels being marked as zombies when they have recent `channel_updates`, I think that will be addressed in the next release when https://github.com/lightningnetwork/lnd/pull/8030 is included. 

As for the weird update horizon.... that seems like a different issue 🤔

**Comment by C-Otto** [comment]
The two dates, when interpreted as seconds since 1970, correspond to 8589934590 and 4294967295 (ignoring the time zone?). The first number is double the second number. Furthermore, 4294967295 is 2^32 - 1. To me, this looks like some kind of default is used for both values.

**Comment by ellemouton** [comment]
ah also - if the LND node is printing this after receiving the `GossipTimestampRange` message from you (CLN) node, then it looks like it is CLN sending these dates

**Comment by urza** [comment]
@saubyk I believe this deserves higher priority then P3. Because LND has such a high share of the whole lightning network, this issue causes that almost all nodes have very distorted view of the network graph.

This can be seen in public network explorers like amboss, 1ML and ligthtning lab's terminal. They have very wrong information about nodes. In last week I talked to many node operators trying to figure out my gossip issues, and almost nobody has correct information on these explorers about their node.

I now believe it is becuase LND doesn't propagate `channel_update `gossip messages when it should. And because it has such a high share of the network it is serious issue for the whole network.

**Comment by ellemouton** [comment]
@urza  - as mentioned before, this should be addressed by https://github.com/lightningnetwork/lnd/pull/8030 which will be in the next release. So I dont think there is any work that needs to be done... hence the P3 status

**Comment by ellemouton** [comment]
In fact, I think we could even close this issue.

**Comment by urza** [comment]
> @urza - as mentioned before, this should be addressed by #8030 which will be in the next release. So I dont think there is any work that needs to be done... hence the P3 status

Ok, I was more reacting to the "nice to have" description in P3 label.
