### ISSUE TITLE
[bug]: lnd let's me force close a channel that is already being cooperatively closed and fails to broadcast tx

### ISSUE THREAD

**Issue by kilrau** [lightningnetwork/lnd#8625]
### Background

I can reliably reproduce lnd trying to force close a channel that is already in a cooperative close if I tell it to do so via `lncli`. It simply prints the commitment tx as closing tx id. I stumbled upon this because this closing tx was not to be found in the mempool 👀

What happened is that the bitcoin core chain backend rejected the force close tx and it didn't get broadcast. The cooperative close should go through, but let's see how lnd even handles this and doesn't get confused.

LND definitely shouldn't allow this.

### Your environment

* version of `lnd`: 0.17.4-beta
* which operating system (`uname -a` on *Nix): Linux 5.15.0-94-generic 104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core v26.0
* any other relevant environment details

### Steps to reproduce

1. Cooperatively close channel: `lncli closechannel --chan_point abc:0 --sat_per_vbyte 21`
2. Try to force close same channel point: `lncli closechannel --chan_point abc:0 --force`
3. LND does this without warning or complaining
```
{
	"closing_txid": "cba"
}
```

Now check logs - broadcast failed and force close is not in the mempool

### Expected behaviour

lnd throws `This channel is already being closed.` and doesn't allow this.

### Actual behaviour

LND actually tries to force close.

**Comment by kilrau** [comment]
Update: so this issue is actually more severe than I thought: lnd actually tries to force close the channel and the closing tx id is not random but the commitment tx.

BUT core rejects this tx because the normal close is rbf. The cooperative close should go through, but let's see how lnd even handles this and doesn't get confused.

One thing I am sure: LND shouldn't allow this to happen

**Comment by Roasbeef** [comment]
IIUC, that second `txid` you see is actually the `txid` of your latest commitment (the force close). With that, I think this is indirectly working as intended:
  1. You try to coop close, that goes through.
  2. If you try again, that'll fail. 
  3. You then do a force close, that unilaterally broadcasts the latest state. 

If we prevented you from doing step 3, then if the coop close txn was stuck in the mempool, or never was broadcasted, you wouldn't have a way to actually exit the channel. 

Ultimately only one of those transactions will confirm on chain, and lnd will act on that.

**Comment by kilrau** [comment]
Thanks for the quick reply. I updated my issue after my initial write-up: the force close transaction didn't broadcast - I think this should be handled.

In summary I think:
1. lnd should at least throw a warning when I'm trying to force close a channel that is already cooperatively closing. In my case it was unintended. I suspect this can happen on other larger node's spring cleaning too.
2. the force close was never broadcast (`unable to broadcast close tx: transaction rejected: output already spent`). I agree with the use case you are describing, but it's not working.

**Comment by Roasbeef** [comment]
> the force close transaction didn't broadcast - I think this should be handled.

If the co-op close transaction was accepted to your local mempool, and it was a higher fee rate than the force close transaction (should always be the case), then it won't be accepted. As mentioned, all that matters to `lnd` here is what actually confirms on chain. 

> lnd should at least throw a warning when I'm trying to force close a channel that is already cooperatively closing. In my case it was unintended. 

Do you mean an API level warning? The opt-in is already present with the existence of the `Force` flag.

> the force close was never broadcast (unable to broadcast close tx: transaction rejected: output already spent). I agree with the use case you are describing, but it's not working.

It was _broadcasted_, but not accepted to your local mempool. As noted above, if it's a lower fee rate, then this is working as intended.
