### ISSUE TITLE
Sign tags

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#863]
Maybe I'm just talking to an attacker (github) presenting me unsigned repo, so this issue is waste of time, but in case I don't, please sign tags.

```
$ git verify-tag v0.4-beta
error: v0.4-beta: cannot verify a non-tag object of type commit.
```

**Comment by petertodd** [comment]
Heh, I was just about to open this issue myself. :) Definitely needs to be fixed.

**Comment by Roasbeef** [comment]
The latest [release](https://github.com/lightningnetwork/lnd/releases/tag/v0.4.1-beta) includes a signed tag: 
```
⛰ git verify-tag v0.4.1-beta
gpg: Signature made Mon Apr  2 17:10:37 2018 PDT
gpg:                using RSA key 964EA263DD637C21
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [ultimate]
```

> Maybe I'm just talking to an attacker (github) presenting me unsigned repo

All commits by major contributors are also signed.
