### ISSUE TITLE
[ERR] CRTR: Attempt to send payment, failed: UnknownNextPeer

### ISSUE THREAD

**Issue by remyers** [lightningnetwork/lnd#868]
I'm trying to pay an invoice and get "`unable to route payment to destination: UnknownNextPeer`" error followed by "`unable to find a path to destination`" despite `queryroutes` finding many routes, including a two hop route.

I'm running Version 0.4.0-alpha on Windows x64 connecting to bitcoind (mainnet).  I'm attaching my log file along with the outputs of decodepayreq and queryroutes output.   I have 5 channels funded.

I'm also attaching my lnd.conf and bitcoin.conf files.

[issue_data.zip](https://github.com/lightningnetwork/lnd/files/1821846/issue_data.zip)

I'd be happy to run more tests, but after looking at the log I didn't see any obvious next things to try.

Thanks! I'm excited to test out lightning and learn more about how to use it.

**Comment by Roasbeef** [comment]
The `queryroutes` command looks at the graph and returns possible _paths_. When you actually go to send a payment, we seek a proper _route_. A path may exist on the graph, but if a node isn't online, then we can't actually use that route for example. Also keep in mind that most node on the network are very old, and may be faulty as they were spun up by users that hacked prior implementations to enable mainnet. As people are upgrading nodes, and getting more educated about how to run a node, network conditions should improve. 

The `UnknownNextPeer` error just means that a node in the route wasn't online, so the payment was cancelled.

**Comment by Roasbeef** [comment]
Closing out for now as it seems just the target node wasn't there. As people are upgrading their nodes, etc right now, things can be a bit weird as many nodes were just spun up to buy stickers.
