### ISSUE TITLE
Error on Mac OS High Sierra 10.13.1 on step 'go install . ./cmd/...'

### ISSUE THREAD

**Issue by olegbabak** [lightningnetwork/lnd#869]
Hello dear team,

I just tried to install lnd using https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md
on Mac OS High Sierra 10.13.1 , and on step:

go install . ./cmd/...

I see the following error in Terminal:

unexpected directory layout:
	import path: github.com/btcsuite/btclog
	root: /Users/user/gocode/src
	dir: /Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btclog
	expand root: /Users/user/gocode/src
	expand dir: /Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btclog
	separator: /

Could you please help to figure out why it could happen? Thanks in advance.

**Comment by Roasbeef** [comment]
Check your $GOPATH to ensure it has been set properly, and also that you did `dep ensure` before attempting to install anything.

**Comment by neogeno** [comment]
Also upgrade to the latest version of go - the default version with Mac OS home brew is too old.

**Comment by olegbabak** [comment]
@Roasbeef, for $GOPATH settings I ran the following commands:
export GOPATH=~/gocode
export PATH=$PATH:$GOPATH/bin

After this 'printenv' returns:

TERM_PROGRAM=Apple_Terminal
INSTALL_DIRECTORY=/usr/local/bin
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/tz/t4xjctkd0wl_t5f07mcq04fm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OTdeJ1f13P/Render
TERM_PROGRAM_VERSION=400
OLDPWD=/Users/user/gocode/src/github.com/lightningnetwork
TERM_SESSION_ID=A18FEB59-8C88-4DE3-9016-816C3F3F265F
USER=user
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.GCkdjDTwqD/Listeners
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/user/gocode/bin
PWD=/Users/user/gocode/src/github.com/lightningnetwork/lnd
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/user
LOGNAME=user
GOPATH=/Users/user/gocode
_=/usr/bin/printenv


Regarding 'dep ensure' - I ran it with the following results in Terminal:

MacBook-Air:lnd user$ dep ensure
MacBook-Air:lnd user$ 

So looks like no errors were there.

**Comment by olegbabak** [comment]
@neogeno, for me 'go version' returns: _go version go1.10 darwin/amd64_

Looks like it's the last available version on https://golang.org/doc/devel/release.html

**Comment by Roasbeef** [comment]
Ensure that your $GOROOT and your $GOPATH are not overlapping.

**Comment by olegbabak** [comment]
Thanks, @Roasbeef , there was no GOROOT env variable in my configuration, so I added it and the issue disappeared. But now when I run 'dep ensure' and 'go install . ./cmd/...' I get: 

vendor/github.com/golang/protobuf/proto/text.go:37:2: cannot find package "bufio" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/bufio (vendor tree)
	/Users/user/goworkspace/src/bufio (from $GOROOT)
	/Users/user/gocode/src/bufio (from $GOPATH)
breacharbiter.go:4:2: cannot find package "bytes" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/bytes (vendor tree)
	/Users/user/goworkspace/src/bytes (from $GOROOT)
	/Users/user/gocode/src/bytes (from $GOPATH)
vendor/github.com/jrick/logrotate/rotator/rotator.go:33:2: cannot find package "compress/gzip" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/compress/gzip (vendor tree)
	/Users/user/goworkspace/src/compress/gzip (from $GOROOT)
	/Users/user/gocode/src/compress/gzip (from $GOPATH)
vendor/github.com/roasbeef/btcd/btcec/precompute.go:8:2: cannot find package "compress/zlib" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/compress/zlib (vendor tree)
	/Users/user/goworkspace/src/compress/zlib (from $GOROOT)
	/Users/user/gocode/src/compress/zlib (from $GOPATH)
routing/pathfind.go:9:2: cannot find package "container/heap" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/container/heap (vendor tree)
	/Users/user/goworkspace/src/container/heap (from $GOROOT)
	/Users/user/gocode/src/container/heap (from $GOPATH)
peer.go:4:2: cannot find package "container/list" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/container/list (vendor tree)
	/Users/user/goworkspace/src/container/list (from $GOROOT)
	/Users/user/gocode/src/container/list (from $GOPATH)
vendor/golang.org/x/net/context/go17.go:10:2: cannot find package "context" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/context (vendor tree)
	/Users/user/goworkspace/src/context (from $GOROOT)
	/Users/user/gocode/src/context (from $GOPATH)
vendor/github.com/btcsuite/golangcrypto/ripemd160/ripemd160.go:13:2: cannot find package "crypto" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/crypto (vendor tree)
	/Users/user/goworkspace/src/crypto (from $GOROOT)
	/Users/user/gocode/src/crypto (from $GOPATH)
vendor/github.com/roasbeef/btcd/btcec/ciphering.go:9:2: cannot find package "crypto/aes" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/crypto/aes (vendor tree)
	/Users/user/goworkspace/src/crypto/aes (from $GOROOT)
	/Users/user/gocode/src/crypto/aes (from $GOPATH)
vendor/github.com/roasbeef/btcd/btcec/ciphering.go:10:2: cannot find package "crypto/cipher" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/crypto/cipher (vendor tree)
	/Users/user/goworkspace/src/crypto/cipher (from $GOROOT)
	/Users/user/gocode/src/crypto/cipher (from $GOPATH)

....(plenty of similar errors)....

vendor/github.com/awalterschulze/gographviz/escape.go:22:2: cannot find package "text/template" in any of:
	/Users/user/gocode/src/github.com/lightningnetwork/lnd/vendor/text/template (vendor tree)
	/Users/user/goworkspace/src/text/template (from $GOROOT)
	/Users/user/gocode/src/text/template (from $GOPATH)


Could you please advise what should I do yo obtain the missing packages? I did 

git clone https://github.com/lightningnetwork/lnd $GOPATH/src/github.com/lightningnetwork/lnd

but after the repository cloning I don't have such packages.

**Comment by Roasbeef** [comment]
I'd try to start from a fresh installation of Go, [following this tutorial])https://golang.org/doc/install#testing).

**Comment by Roasbeef** [comment]
I'd try to start from a fresh installation of Go, [following this tutorial](https://golang.org/doc/install#testing).

**Comment by halseth** [comment]
You can also do `dep ensure -v` to get more info from dep.
