### ISSUE TITLE
[bug]: lncli openchannel breaking change - fee preference

### ISSUE THREAD

**Issue by carlaKC** [lightningnetwork/lnd#8691]
Just rebased to 2089a88f4 and noticed that `openchannel` no longer works without explicitly setting fee preferences? 

```
lncli openchannel --node_key=02e6837df35ec3cf08544a7506ba4c42b1aa01ec71013d8a0e56d878a6545a9815 --local_amt=100000
[lncli] rpc error: code = Unknown desc = no fee preference specified
```

Feel free to close if this was intentionally updated, just wondered if a default got accidentally removed somewhere!

**Comment by saubyk** [comment]
cc @yyforyongyu 

This will be a breaking change and should be addressed

**Comment by yyforyongyu** [comment]
Thanks for testing it out! yea it's in the [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.0.md#rpc-updates), maybe we should put it under breaking change when releasing it.
