### ISSUE TITLE
NewAddress returns duplicate addresses

### ISSUE THREAD

**Issue by remnantdev** [lightningnetwork/lnd#8697]
### Background

We have noticed that gRPC call to `NewAddress` did return the same address twice.

From what I can see in our logs the node was in the process of starting.

Is getting a new address guaranteed to return a new address or was it an invalid assumption on our part?

### Your environment

* version of `lnd` : lnd.017.2.beta
* which operating system: Alpine Linux v3.18

### Steps to reproduce

Not able to reproduce

**Comment by alexbosworth** [comment]
In address type, which type did you select? The options:

```
    WITNESS_PUBKEY_HASH = 0;
    NESTED_PUBKEY_HASH = 1;
    UNUSED_WITNESS_PUBKEY_HASH = 2;
    UNUSED_NESTED_PUBKEY_HASH = 3;
    TAPROOT_PUBKEY = 4;
    UNUSED_TAPROOT_PUBKEY = 5;
```

**Comment by remnantdev** [comment]
> In address type, which type did you select? The options:
> 
> ```
>     WITNESS_PUBKEY_HASH = 0;
>     NESTED_PUBKEY_HASH = 1;
>     UNUSED_WITNESS_PUBKEY_HASH = 2;
>     UNUSED_NESTED_PUBKEY_HASH = 3;
>     TAPROOT_PUBKEY = 4;
>     UNUSED_TAPROOT_PUBKEY = 5;
> ```

We only use `WITNESS_PUBKEY_HASH`

**Comment by guggero** [comment]
With `WITNESS_PUBKEY_HASH` you should be guaranteed to receive a new address every time. Are you sure you didn't use `UNUSED_WITNESS_PUBKEY_HASH`? Which would return the _same_ address until some on-chain funds are detected on it (marking it as "used").
If you can reproduce, then please share the logs of both calls.

**Comment by remnantdev** [comment]
We are sure we used `WITNESS_PUBKEY_HASH `. We have one usage of `UNUSED_WITNESS_PUBKEY_HASH ` but it is in a totally different context.

I was not able to reproduce, we only noticed it occuring this time because the address was actually used in a transaction but going through our db I could find some duplicate address going all the way back to 2021.

**Comment by saraogiraj94** [comment]
Hi we too got same address twice, despite passing WITNESS_PUBKEY_HASH.
Like this is 1 in say 100k cases, like we have been generating lot of onchain addresses and in very very rare scenario got this case of duplicate address. 
One thing to noticed was that the address api was called multiple time at same timestamp with microseconds different then only got this same address.

**Comment by guggero** [comment]
Thanks for the additional detail. Sounds like a race condition and/or missing database level lock... Should help us find the bug more quickly.
