### ISSUE TITLE
INSTALL.md: glide is no longer used to install btcd

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#870]
Need to replace "glide" with "dep" for btcd installing guide  https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-btcd
>go get -u github.com/Masterminds/glide
git clone https://github.com/roasbeef/btcd $GOPATH/src/github.com/roasbeef/btcd
cd $GOPATH/src/github.com/roasbeef/btcd
glide install
go install . ./cmd/...

**Comment by wilmerpaulino** [comment]
This is fine since it’s installing btcd’s dependencies, which still uses glide.

**Comment by molxyz** [comment]
@wilmerpaulino  oh really... thanks, and I suck even at making a post on github issue, or it sucks at telling me how to quote anything lol
