### ISSUE TITLE
Channel with out proper id?

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#871]
` "channels": [
        {
            "active": false,
            "remote_pubkey": "024b82d69859d63f9fce375041a34e61f4bfd445494b41d873ae7505322323d384",
            "channel_point": ---",
            "chan_id": "0",
            "capacity": "120000",
            "local_balance": "119276",
            "remote_balance": "0",
            "commit_fee": "724",
            "commit_weight": "600",
            "fee_per_kw": "1000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144
        },
`

I removed channel point but can send it to you via email if needed. This channel id is 0. Looks like a bug to me.

Anyway how to  close channel? Command description says i have to use funding txt id but it dosen't work. It results with error:

`[lncli] rpc error: code = Unknown desc = channel with chan_id=$txtIdHere not found`

**Comment by Roasbeef** [comment]
What node are you using? Is the node synced to the chain? Do you see `lnd` getting new blocks in? 

The channel isn't active, which means that the remote node isn't online. As a result, if you want to close the channel immediately, you'll need to force close the channel, and incur the CSV delay.

**Comment by abolsen** [comment]
Same deal here. lnd is getting new blocks in. Not sure how to close the channel either - same error as halfik. I use the tx_hash as the funding_txid

**Comment by Roasbeef** [comment]
If you look at `lncli closechannel -h`, you'll see that you also need to specify the output index. Which node backend are you using @abolsen?

**Comment by abolsen** [comment]
"identity_pubkey": "03f8109578aae1e5cfc497e466cf6ae6625497cd31886e87b2f4f54f3f0f46b539",
    "alias": "LION",
    "num_pending_channels": 1,
    "num_active_channels": 3,
    "num_peers": 9,
    "block_height": 513996,
    "block_hash": "0000000000000000003cb3e6f32a0c470522d74c70ae5268839745527aeade52",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "03f8109578aae1e5cfc497e466cf6ae6625497cd31886e87b2f4f54f3f0f46b539@13.81.122.76:9735"
    ],
    "best_header_timestamp": "1521326011"

**Comment by abolsen** [comment]
Adding `--output_index 1` didn't do the trick on it's own (still said it wasn't found). I had to add `--force` as well, and voila; added to `pending_force_closing_channels`

**Comment by Roasbeef** [comment]
Yes, if the remote node isn't online, you'll need to add the `--force` flag (as documented in `lncli closechannel -h`. Note that in this case, you'll need to wait out the CSV delay before funds can actually be spent.

**Comment by halfik** [comment]
@Roasbeef im using bitcoin core 15.1
LND is reciving blocks i just opened a new channel. When i was closing channels one by one with closeallchannels command it showed proper id after closing it. so it list wrong only on listchannels.
