### ISSUE TITLE
[bug]: sweep: data race on TxPublisher.currentHeight

### ISSUE THREAD

**Issue by morehouse** [lightningnetwork/lnd#8715]
`TxPublisher.currentHeight` is not guarded by a mutex but is accessed from multiple goroutines:

- in the `monitor` goroutine https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L718
- from outside calls to `Broadcast` https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L376  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L544-L545  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L1124-L1126  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L1181
- in the `handleFeeBumpTx` goroutine  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L856-L857  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L864-L865  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L1124-L1126  https://github.com/lightningnetwork/lnd/blob/e8a1d4876eb6477dbbaf0287e711ce9de56084ee/sweep/fee_bumper.go#L1181

**Comment by Roasbeef** [comment]
Can prob throw in a https://pkg.go.dev/sync/atomic#Int32

**Comment by yyforyongyu** [comment]
Thanks for reporting! Also found this issue while fixing the itest flakes and have a local branch already - still needs more work, meanwhile will use `atomic` to provide a temp fix.
