### ISSUE TITLE
lack of rpc reconnection for bitcoind backend

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#875]
We've received a few reports of user's node's failing to recognize a channel as confirmed, or even spent. In all instances, users were using the `bitcoind` backend. Reporst seem to indicate the for some reason the connection to the bitcoind backend (both zmq and the json-rpc connection) were broken. We don't detect disconnects and automatically reconnect for the `bitcoind` backend as we do for `btcd`. 

To remedy this the library we use for zmq (https://github.com/lightninglabs/gozmq) should be modified to detect disconnects, and automatically reconnect using exponential backoff. . 

Related to #871, #857.

**Comment by Perlover** [comment]
I think there is related problem but with more fresh version of lnd

https://github.com/lightningnetwork/lnd/issues/640#issuecomment-397193556
