### ISSUE TITLE
[bug]: Channels without zero-conf feature but `minimum_depth` 0 are rejected

### ISSUE THREAD

**Issue by tnull** [lightningnetwork/lnd#8783]
### Background

As per BOLT 2, a node receiving `open_channel` can communicate the number of confirmations of the funding transaction it deems reasonable via [`accept_channel`](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#the-accept_channel-message)'s `minimum_depth` field:

```
if channel_type includes option_zeroconf:

    MUST set minimum_depth to zero.

otherwise:

    SHOULD set minimum_depth to a number of blocks it considers reasonable to avoid double-spending of the funding transaction.
```

However, LND currently does not only check that `minimum_depth` is `0` if the zero conf. feature is set, but also *that `minimum_depth` is non-zero otherwise*.

In particular, it rejects any channel without the feature that sets `minimum_depth` to 0:

https://github.com/lightningnetwork/lnd/blob/bc6292f8bd37ddcb4283e79418861be37a36a618/funding/manager.go#L2023-L2030

Unfortunately, this means LND is currently unnecessarily failing channel opens *on a more permissive counterparty limit*.

LDK currently does *not* set the optional zero-conf feature bit, but just sets `minimum_depth` to zero in `accept_channel` via a specific [API method](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.accept_inbound_channel_from_trusted_peer_0conf) via which users can opt into trusting the counterparty for 0conf. However, if we now do this on a per-peer basis and the LND counterparty tries to open a *non-zero conf* channel to us, it will always be rejected due to `non-zero-conf channel has min depth zero`. 

That is, due to this arbitrary restriction, users will have to know beforehand whether the LND counterparty will open a zero-conf or non-zero-conf channel.

### Steps to reproduce

Try to open a non-zero-conf channel from LND to a LDK node that trusts its LND counterparty for zero-conf channels.

### Expected behaviour

The channel should be opened.

### Actual behaviour

The channel is unnecessarily rejected.

**Comment by Roasbeef** [comment]
> I believe this has been discussed quite a bit in the past, so I don't intend to fully restart the discussions around whether or not to set the optional feature bit here. 

You seem to be doing just that by opening this issue. 

> Could you explain what benefit the above cited 'early failure' of the channel has to which party?

If a node expects a zero conf channel (sets the bit), but the responder doesn't want one, then they can reject the channel opening with an error. If a user expects a zero conf channel, but the initiator doesn't, then without this strict behavior, the user's channel would be silently downgraded (which can lead to UX issue if the user expects to be able to recv an HTLC over a zero conf channel).

As you note above, this is a trusted channel type, thus it should be _explicit_ that such a channel is or isn't accepted. 

Can you explain what _prevents_ LDK from conditionally setting `min_depth` based on the incoming feature bit and the user's configured settings? The logic should be straight forward, if you need some inspiration, you can see how lnd does it with the [`ChannelAcceptor`](https://lightning.engineering/api-docs/api/lnd/lightning/channel-acceptor) API.

**Comment by ellemouton** [comment]
makes sense. also looks like the other way around is handled correctly: we do allow a peer to send us an OpenChannel that does set the channel type to zero conf explicitly and then we will send back a min-depth of 0 if our channelAcceptor interceptor allows it/requires it. So we expect the peer to be ok with this & hence we should be ok when the peer does the same to us

**Comment by ellemouton** [comment]
^ opened a patch if yall wanna test it out

**Comment by Roasbeef** [comment]
> Because then the peer would reject the channel if they don't want 0conf? 

That's ideal behavior imo. You want the channel to be zero conf (vastly diff trust relationship that normal channels), it should be set explicitly at the protocol level what expectations are. This is implicit vs explicit, fast fail vs silently fail.
