### ISSUE TITLE
Not connecting to peers?

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#879]
I don't know why by i can't connect to any new peer. They are online (used thttps://graph.lndexplorer.com/ to check if they are reachable). There is no error when i try to connect but they do not appear on peers list:

https://justpaste.it/1iff3

**Comment by abolsen** [comment]
Seems to me that it does appear. The one you connect to `104.198.32.198:9735` - is the one at the bottom of your `listpeers`

**Comment by halfik** [comment]
Tested it again and seems to work.
