### ISSUE TITLE
wrong BOLT11 prefix in regtest 

### ISSUE THREAD

**Issue by DanielWeigl** [lightningnetwork/lnd#882]
Running the node in regtest and generating an invoice returns a `lntb...` bolt11 invoice (testnet), but according to https://github.com/bitcoin/bitcoin/issues/12314 it should return `lnbcrt...`

`c-lightning` already returns an `lnbcrt...` invoice in regtest, so now it not possible to pay invoices between the two implementations. (both in regtest mode)

See other issue for more details: https://github.com/ElementsProject/lightning/issues/1241

Maybe also clarify in https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part

**Comment by vapopov** [comment]
Hi, may I take this task

**Comment by DanielWeigl** [comment]
> Hi, may I take this task
That would be great!

Maybe also have a look on https://github.com/cdecker/lightning-integration to first extend it with a test so this error shows up

**Comment by Lldenaurois** [comment]
@vapopov: Are you still working on this?

**Comment by vapopov** [comment]
@Lldenaurois yep, waiting response from pull requests

**Comment by Roasbeef** [comment]
Fixed by #898.

**Comment by dpc** [comment]
I'm looking around trying to find some arguments why would we even need a different prefix for a regtest network, [and I don't really see any, while there's a lot of reasons not to have it](https://github.com/bitcoin/bitcoin/issues/12314#issuecomment-580846197).
