### ISSUE TITLE
tls handshake failure between lnd 0.4 and lncli on windows

### ISSUE THREAD

**Issue by stefanwouldgo** [lightningnetwork/lnd#883]
In windows power shell, lnd 0.4 is running. It does this for any lncli command.

PS C:\Users\Stefan\Downloads\lnd-windows-amd64-v0.4-beta\lnd-windows-amd64-v0.4-beta> .\lncli.exe stop
[lncli] rpc error: code = Internal desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"

**Comment by halseth** [comment]
Try setting `lncli --lnddir=<dir>` to the `lnd` directory containing the tls certificates.

**Comment by stefanwouldgo** [comment]
Thank you. It had the correct lnddir, but maybe the dir had the wrong certificates. I deleted it and it appears to work, but now there's a problem which looks similar to the bitcoind connection problem: 

unable to start wallet: Post http://localhost:8332: dial tcp [::1]:8332: connectex: No connection could be made because the target machine actively refused it.
unable to create chain control: Post http://localhost:8332: dial tcp [::1]:8332: connectex: No connection could be made because the target machine actively refused it.
Post http://localhost:8332: dial tcp [::1]:8332: connectex: No connection could be made because the target machine actively refused it.

**Comment by Roasbeef** [comment]
Ensure that your `bitcoind` node is actually listening.

**Comment by stefanwouldgo** [comment]
Thank you. I have a bitcoind node running sometimes in WSL and sometimes in Windows proper, with the same shared .bitcoin directory. This was when running in Windows proper, and I assume that under Windows, bitcoind doesn't read its bitcoin.conf correctly when formatted in linux, so the listen=1 had been overlooked. It works with the bitcoind running in WSL (but still runs into the well-known bitcoind disconnect bug). So thanks again for helping me debug bitcoind/Windows instead of lnd ;)

**Comment by renepickhardt** [comment]
I have the same problem (however running on macOS) and cannot fix this. I have a bitcoind running via: 
```bitcoind --server=1 --rpcuser=REPLACEME --rpcpassword=REPLACEME --rpcport=8332 --datadir=. --conf=~/Library/Application\ Support/Bitcoin/bitcoin.conf --zmqpubrawblock=tcp://127.0.0.1:28332 --zmqpubrawtx=tcp://127.0.0.1:28332```

also I ran lnd via: 
```lnd --bitcoin.active --bitcoin.mainnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=REPLACEME --bitcoind.rpcpass=REPLACEME --bitcoind.zmqpath=tcp://127.0.0.1:28332 --externalip=95.91.216.131```

following the discussion here and the suggestion by @halseth I tried the argument `lnddir`: 
```lncli --lnddir=~/Library/Application\ Support/Lnd/ create``` on mac os this is infact the folder in which lnd created some files in particular the tls certificates
at least `ls ~/Library/Application\ Support/Lnd/` states:
```admin.macaroon		logs			tls.cert data			readonly.macaroon	tls.key```

@Roasbeef should I have set rpcport in the bitcoind command differently? I can communicate to bitcoind via bitcoin-cli so I thought this should not be the problem.
