### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by kishancr7** [lightningnetwork/lnd#885]
hello, 

This my  node on the " https://explorer.acinq.co/#/n/02ffa8264720893618a6b7f3c2f21ec2cd6b8b1c5f60f8ba74eaf04d8fba99e653"

![screenshot from 2018-03-19 17-30-11](https://user-images.githubusercontent.com/34764107/37594484-4345deba-2b9b-11e8-8d55-d0ac586c4be7.png)

When i try to connect to my node with the help of Eclair application following error is coming.
and when I try to connect my node to other same connection error is coming .

![screenshot_20180319-171416 1](https://user-images.githubusercontent.com/34764107/37594385-f9e8a720-2b9a-11e8-86ab-aeb7f12fdc29.png) 

Can anybody solve my issue.

Thanks

**Comment by stevenroose** [comment]
Can the Eclair app connect to the API of lnd nodes?

**Comment by Roasbeef** [comment]
Ensure that you've figured out your NAT setup. If you have issues after that, I'd report this to the eclair repo.
