### ISSUE TITLE
add config option to specify autopilot fees

### ISSUE THREAD

**Issue by Technifocal** [lightningnetwork/lnd#886]
[Looking at the sample configuration](https://github.com/lightningnetwork/lnd/blob/0c1b619e53ac88ad53f3a88e5d1129c25ddeaf13/sample-lnd.conf#L251), there doesn't seem to be anything related to specifying the autopilot's on-chain transaction fee. As autopilot is something that is primarily done in the background, and not (from what I can tell) time sensitive, it makes sense to allow the user to customise the fee to their specific use-case, either estimated blocks to be confirmed (I.E. "6 blocks") or a static fee per byte (I.E. "1 sat/vbyte").

Sorry if this is already exists/is a duplicate, I couldn't find it anywhere.

**Comment by Roasbeef** [comment]
Atm, it uses 6 blocks for a confirmation target. Adding a config option to specify the fee rate definitely makes sense!

**Comment by aunyks** [comment]
@Roasbeef Are autopilot options ever extracted from a config file or command line flags? I don't ever see them changing from their default values in [lnd/config.go](https://github.com/lightningnetwork/lnd/blob/master/config.go).

**Comment by halseth** [comment]
@aunyks They should be! If you experience otherwise, please file a bug report 👍

**Comment by aunyks** [comment]
Ah, I see: I didn't understand how the `flags` package worked, but I see after taking a look at its README. 

With this being said, however, do we want the fee to be specified as a confirmation target, # of sats/byte, or (somehow) both?

**Comment by Technifocal** [comment]
@aunyks I genuinely believe it should be both. Some users, such as myself, would want to keep fees low when creating automatic channels (they're a lower priority), so I'd like to specify a static low fee such as 1-2 sat/byte and leave it as-is. However other users, especially during peak transaction times, might want to make sure their channels are still being opened and thus would like to specify a block duration (6 blocks, for example).

I haven't personally looked at the code, but would having two variables, one you set and another you leave unset work? For example, in the configuration:

```
# autopilot.fee_sat_per_vbyte = 2
# autopilot.fee_esimated_blocks = 6
```

and the user can use which ever they would prefer.

**Comment by aunyks** [comment]
That's along what I had in mind. I'd be happy to implement this.

**Comment by MrManPew** [comment]
This is actually a serious issue, if it is now set to 6 blocks it could be extremely high if the mempool is full.
