### ISSUE TITLE
lnd crash while synchronizing bitcoind with blockchain

### ISSUE THREAD

**Issue by pantadeusz** [lightningnetwork/lnd#888]
I had the following problem with LND - it was running while bitcoind was updating database.
[lnderrors.txt](https://github.com/lightningnetwork/lnd/files/1826290/lnderrors.txt)

command line:

```bash
./lnd --bitcoin.active --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=*** --bitcoind.rpcpass=*** --bitcoind.zmqpath=tcp://127.0.0.1:29332 --tor.socks=9050 --tor.dns=nodes.lightning.directory --bitcoin.mainnet
```

**Comment by Roasbeef** [comment]
Depending on your `dbcache` parameters for `bitcoind` it may have actually consumed all the available RAM not leaving any for `lnd` to continue its catch up.

**Comment by pantadeusz** [comment]
Ok. If the problem appear again I will check bitcoid also. Thank you.

**Comment by MeshCollider** [comment]
Please reopen if the issue persists
