### ISSUE TITLE
[bug]: GossipSyncer should remove unreliable Peers from syncing the ChannelGraph

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#8889]
There are peers in the network which have a very old ChannelGraph view and when connected to them it requires LND to do a lot of unnecessary work to check for the validity of their out of date graph data. Moreover for pruned nodes this comes with a burden in terms of bandwidth because for channels the node doesn't have the blockdata anymore they need to be fetched from peers which is very bandwidth intensive especially if you use VPN services for your node which restrict the bandwidth at certain points. 

I think we should first introduce some sanity checks, if our channel-graph and the channel-graph of our peers is too far apart, we should trust ourselves more and remove the peer from syncing the data. Probably we should also ban that peer at some point.

This is how an out of date peer sync could look like (form a mainnet node):

```
 DISC: GossipSyncer(02dfe525d9c5b4bb52a55aa3d67115fa4a6326599c686dbd1083cffe0f45c114f8): starting query for 164060 new chans
2024-06-29 11:20:06.456 [INF] DISC: GossipSyncer(02dfe525d9c5b4bb52a55aa3d67115fa4a6326599c686dbd1083cffe0f45c114f8): querying for 500 new channels
2024-06-29 11:20:06.717 [INF] DISC: GossipSyncer(02dfe525d9c5b4bb52a55aa3d67115fa4a6326599c686dbd1083cffe0f45c114f8): querying for 500 new channels
2024-06-29 11:20:06.894 [ERR] CRTR: process network updates got: unable to fetch utxo for chan_id=556369376388317185, chan_point=8450839336340be66e5e1bf02d6ab046d4e83b44d97f034f0b8da609e4f74df1:1: target output has been spent
2024-06-29 11:20:06.988 [ERR] CRTR: process network updates got: unable to fetch utxo for chan_id=556449640836104192, chan_point=6950a0ad8d4d3751f26afd8ab09c32e28b017e721503adefdf6d1f06ae2b19d4:0: target output has been spent
2024-06-29 11:20:07.210 [ERR] CRTR: process network updates got: unable to fetch utxo for chan_id=556484825143181312, chan_point=8ca07553aff9287badc5a792f85e6785aaccd8c8596b3d7664eb7499e9de67fb:0: target output has been spent
2024-06-29 11:20:07.567 [ERR] CRTR: process network updates got: unable to fetch utxo for chan_id=556816877593165824, chan_point=1451d36ff82bb6faa74eae09486b520eef1702a41273ea3c5e6785daaff2fd40:0: target output has been spent

....
```

**Comment by Roasbeef** [comment]
Re sanity checks, today we _do_ have a reject cache here to ensure that we won't continue validating channels that we already deemed to be invalid.

**Comment by Impa10r** [comment]
Happened to me twice this week. LND *quietly* becomes unresponsive and the node must be rebooted. How do I find out which peer is causing this, so I can close the channel?

**Comment by Impa10r** [comment]
I identified a certain peer as the cause, so I limited my sync peers to Boltz, WoS and Bfx. All was fine for a few days, but today the problem returned. LND log and all three archives are completely full with 'unable to fetch utxo', so I cannot find 'starting query for'...

**Comment by Impa10r** [comment]
> use specific peers for the acitve peer sync

Well, this did not work. I pinned the peers, but still see  `starting query for <large number>` from other peers, some of which causing the above problem. LND 0.18.0...

**Comment by Crypt-iQ** [comment]
> I identified a certain peer as the cause, so I limited my sync peers to Boltz, WoS and Bfx

Can you share the peer's NodeID? I want to connect to it and see what's happening.

**Comment by ziggie1984** [comment]
The peer I identified while analysing the issue was this one: https://amboss.space/node/02dfe525d9c5b4bb52a55aa3d67115fa4a6326599c686dbd1083cffe0f45c114f8

**Comment by Impa10r** [comment]
> Can you share the peer's NodeID? I want to connect to it and see what's happening.

Sure, by bad peers are:
023e09c43b215bd3dbf483bcb409da3322ea5ea3b046f74698b89ee9ea785dd30a
0309bf5fe006bd2b14d61126723481c6c685bda44efe093800908527dfe9cd8db7
02ce7abb5e625990f7898520bca721b7ae316165eef81133dcfe4068fcfbe37ac6

**Comment by Impa10r** [comment]
Two of my bad peers are running 0.18.0. the other two did not respond ..

**Comment by Crypt-iQ** [comment]
@Impa10r what kind of hardware is your node running on?

**Comment by Impa10r** [comment]
> @Impa10r what kind of hardware is your node running on?

Raspi4 8gb. It can be that this is not a new problem, but LND 0.18 is more CPU intensive.

**Comment by dunkfan** [comment]
I also saw this on a Raspi4 8gb. The pinned peers suggestion seems to have fixed it, running a few days now.
I'm running 0.18.2

**Comment by dunkfan** [comment]
Happened again today. Needed a restart to recover
2024-08-01 08:07:57.089 [INF] DISC: GossipSyncer(023e09c43b215bd3dbf483bcb409da3322ea5ea3b046f74698b89ee9ea785dd30a): querying for 500 new channels
The query appeared in a seemingly endless loop, 500 channels a time

**Comment by Impa10r** [comment]
I had 1101 from a different peer, but LND did not restart this time.

**Comment by Crypt-iQ** [comment]
Do any of you have zero-conf channels?

**Comment by dunkfan** [comment]
lncli listchannels shows zero_conf as false on all channels
I do have one private channel operational

**Comment by Impa10r** [comment]
> lncli listchannels shows zero_conf as false on all channels I do have one private channel operational

private are normally not zero_conf. https://github.com/blckbx/NodeTools/blob/main/private-trusted-zero-conf-channels.md

**Comment by dunkfan** [comment]
listchannels reports private as true and zero_conf for that channel as false
I have since moved bitcoin core from 24.0.1 to 25.2
So far 1 day no sign of the issue. Will stay vigilant

**Comment by dunkfan** [comment]
No that made no difference, same problem twice today. Seems to be caused by the same peer node

**Comment by ziggie1984** [comment]
For all people struggling with this problem can you set the following config setting until a proper fix is out.

```numgraphsyncpeers=0```

this showly guarantees that only the pinned peers will be used for a historical scan of the channel graph rather than some other random peers.

Will keep you updated while working on a proper fix.

**Comment by saubyk** [comment]
> this soley guarantees that only the pinned peers will be used for a historical scan of the channel graph rather than some other random peers

By "pinned peers" you mean peers which a node has active channels with, correct?

**Comment by ziggie1984** [comment]
> By "pinned peers" you mean peers which a node has active channels with, correct?

Good question, yes only peers you have channels with should be used for pinned peers, pinned peers can basically be selected via the lnd.conf file:


https://github.com/lightningnetwork/lnd/blob/2f2efc782436944ce98b1e0e13bde125951b2b36/sample-lnd.conf#L1620-L1637

**Comment by Crypt-iQ** [comment]
> So one problem is that we would reply in the reply_channel_range with a future timestamp for channels we would not have real ChanUpdate for so that would trigger the querying node to resurrect all its Zombie Channels and query them during the sync.

Great catch! I agree that `reply_channel_range` with bogus timestamps are part of the problem; that explains why I was seeing future timestamps. I think something else is happening that is causing these nodes to broadcast announcements for outdated channels. LND has the following behavior related to spent outputs and zombies:
- prunes (deletes) graph edges that have had their funding outpoints spent.
- deletes edges when channels are marked as zombies.
- cleans up the zombies after a certain interval. Since LND deletes these zombie edges, these spamming nodes can't force LND to resurrect deleted zombie channels.
- resurrects zombie channels upon receiving a `ChannelUpdate` with more recent timestamps via `MarkEdgeLive`. Note that this only means the zombie edge is removed from the zombie bucket if it exists. [It does not mean that we insert an edge into the `edgeIndexBucket`.](https://github.com/lightningnetwork/lnd/blob/0aced5ce2dfb618a0ee6dcec931212308085d8f5/channeldb/graph.go#L3714-L3732) I think this means we can ignore [point 2](https://github.com/lightningnetwork/lnd/issues/8889#issuecomment-2289135744) above.

Given the behavior above, non-neutrino LND nodes will do the following when receiving a `reply_channel_range` with bogus timestamp entries:
- look in the graph and find the entry in either the zombie bucket or not find it at all
- request the channel's `ChannelAnnouncement` + `ChannelUpdate` via `QueryShortChanIDs`
- receive the associated `ChannelAnnouncement` and fail to validate it, marking the channel as a zombie

This points to the spam-serving nodes being neutrino nodes as they won't validate the `ChannelAnnouncement` due to `AssumeChannelValid` being true. If the spammy nodes are running neutrino, I'm not sure _how_ they were first "infected" with old channels. I'll try fingerprinting the spammy nodes and see if they are running neutrino.

**Comment by ziggie1984** [comment]
> This points to the spam-serving nodes being neutrino nodes as they won't validate the ChannelAnnouncement due to AssumeChannelValid being true. If the spammy nodes are running neutrino, I'm not sure how they were first "infected" with old channels. I'll try fingerprinting the spammy nodes and see if they are running neutrino.

Very good analysis, I think also running for a short period of time in neutrino mode and then switching back could also infect us with all those channels which are already closed. I think we would never get rid of them without dropping the chan-graph.

> resurrects zombie channels upon receiving a ChannelUpdate with more recent timestamps via MarkEdgeLive ...

I think as long as we introduce the `banman` we can ignore the timestamp check in the `reply_channel_range ` msg as you mentioned. Otherwise I think it might serve at least as some kind of protection, for example if we would not have marked edges live again based on the timestamp, all of the channels not validateable would have all ended up in the zombieIndex and hence never requested again. So I think without the ban-protection letting a peer resurrect all our zombiechannels and send us all the ChanAnnouncments over and over again might be a vulnerability (in case the rejectCache remains the same size as is today)

**Comment by Crypt-iQ** [comment]
It seems that these nodes are not neutrino nodes, so I'm not sure how they are storing old announcements...

**Comment by ziggie1984** [comment]
So one other problem we have to think about is, that those nodes are not pruning those old announcements, I think the culprit is, that they have also no ChanUpdate for those announcements hence no entry in the `edgeUpdateIndexBucket` bucket which means they will not be picked up by the `pruneZombieChans` job. I think we are missing an entry in this bucket when receiving a chan announcement in general here:

https://github.com/lightningnetwork/lnd/blob/0aced5ce2dfb618a0ee6dcec931212308085d8f5/channeldb/graph.go#L4404-L4416

we probably need to insert a dummy timestamp into the `edgeUpdateIndexBucket` (maybe the current timestamp) so we also remove channels which don't receive any chanupdate after 2 weeks via the pruning job.

**Comment by HamishMacEwan** [comment]
In case more examples are useful:

```
admin@myNode:~ $ sudo journalctl --no-page -u lnd.service | grep "starting query for"
Aug 24 18:48:31 myNode lnd[10853]: 2024-08-24 18:48:31.474 [INF] DISC: GossipSyncer(026ec3e3438308519a75ca4496822a6c1e229174fbcaadeeb174704c377112c331): starting query for 423 new chans
Aug 24 20:48:32 myNode lnd[10853]: 2024-08-24 20:48:32.949 [INF] DISC: GossipSyncer(03e691f81f08c56fa876cc4ef5c9e8b727bd682cf35605be25d48607a802526053): starting query for 1 new chans
Aug 24 23:48:37 myNode lnd[10853]: 2024-08-24 23:48:37.677 [INF] DISC: GossipSyncer(02f95c6f3498caf4f6811c5edc4ac9806ba345534a18391e94ae9f7af41104df18): starting query for 5 new chans
Aug 25 01:48:29 myNode lnd[10853]: 2024-08-25 01:48:29.672 [INF] DISC: GossipSyncer(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f): starting query for 2 new chans
Aug 25 02:48:29 myNode lnd[10853]: 2024-08-25 02:48:29.779 [INF] DISC: GossipSyncer(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f): starting query for 1 new chans
Aug 25 04:48:50 myNode lnd[10853]: 2024-08-25 04:48:50.125 [INF] DISC: GossipSyncer(0236e577964da670c730e7f362fa0c561b75dc9af02c0d822179f155e1455b20bd): starting query for 118268 new chans
Aug 25 05:48:33 myNode lnd[10853]: 2024-08-25 05:48:33.962 [INF] DISC: GossipSyncer(034ea80f8b148c750463546bd999bf7321a0e6dfc60aaf84bd0400a2e8d376c0d5): starting query for 53 new chans
Aug 25 06:48:31 myNode lnd[10853]: 2024-08-25 06:48:31.282 [INF] DISC: GossipSyncer(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f): starting query for 2 new chans
admin@myNode:~ $
```

118268 new chans 🙄

**Comment by saubyk** [comment]
Closed with https://github.com/lightningnetwork/lnd/pull/9009 and https://github.com/lightningnetwork/lnd/pull/9011
