### ISSUE TITLE
admin.macaroon missing

### ISSUE THREAD

**Issue by Stadicus** [lightningnetwork/lnd#890]
I am opening this issue on behalf of several users that followed my RaspiBolt guide and had the issue that the admin.macaroon was not created.

* Guide: https://github.com/Stadicus/guides/tree/master/raspibolt
* Issue: https://github.com/Stadicus/guides/issues/8

Would you mind glancing over the installation part in my guide to check if I missed something? Personally, I never had this issue and everything went as expected...

* Install LND:  
  https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_40_lnd.md#install-lnd

Thanks!

**Comment by Roasbeef** [comment]
If they had a partial installation, then their data directory might have been messed up from a prior installation. If they delete the macaroons, then they'll be regenerated.

**Comment by GeorgeSpark-Stahl** [comment]
I'm also seeing this issue, although I didn't follow that guide to get setup.   I had an existing lnd installation which I deleted when I upgraded.  But now only macaroons.db is getting recreated.  I've searched around to see if the files were created elsewhere, but I haven't been able to find them. This is on macOS High Sierra.

**Comment by Roasbeef** [comment]
Are you starting `lnd` with `--no-macaroons`? In that case macaroons won't be generated at all if you do it upon initial set up.

**Comment by GeorgeSpark-Stahl** [comment]
I was not originally running with `--no-macaroons`, although I had added it as a workaround.  I went to go recreate the issue by removing `--no-macaroons` and it recreated the correct macaroons, so everything is great now.  🤷‍♂️

**Comment by aakselrod** [comment]
@Stadicus, do people notice the macaroon issue after switching from testnet to mainnet, or is it present when they first start in testnet mode? The macaroon DB is encrypted with the same password as the wallet, so if you're moving to a new wallet, you need to delete the macaroon DB and any macaroons generated from that DB, which is missing from the instructions for moving to mainnet.

**Comment by Stadicus** [comment]
I guess that could be the issue. I'll adjust the guide asap to clean up before the switch. Best to delete everything, or only specific files?

**Comment by cootpursuits** [comment]
I had this issue when I first started in testnet mode. `macaroons.db` was generated, but `admin.macaroon` and `readonly.macaroon` were not.

**Comment by aakselrod** [comment]
@cootpursuits Are you running both `lnd` and `lncli` as the `bitcoin` user? Under what directory is the `macaroons.db` being generated?

**Comment by Stadicus** [comment]
When should `admin.macaroon` and readonly.macaroon` be created exactly? Right on the first startup of `lnd`, or after the wallet creation? Sorry, can't test for myself atm without closing all mainnet channels...

**Comment by aakselrod** [comment]
@Stadicus It's created right after the wallet password is input:

https://github.com/lightningnetwork/lnd/blob/master/lnd.go#L222

Based on that, there's another interesting possible way to make it fail:

* Start `lnd`, create wallet with password with `lncli create`
* Stop `lnd`, delete `macaroons.db` and `*.macaroon`
* Start `lnd`, enter the wrong password using `lncli unlock`

This will create a new `macaroons.db`, which will be encrypted with the wrong password. After that, the wallet decryption will fail. If you start `lnd` again, it will only be able to open one of `macaroons.db` or `wallet.db`.

**Comment by Stadicus** [comment]
Thanks a lot for the clarification. I removed my question as not to bother you with trivial stuff and tested myself (as described in https://github.com/Stadicus/guides/issues/8).

**Comment by aakselrod** [comment]
Happy to help, just can't seem to reproduce it myself without a mismatched wallet/macaroon DB password.

**Comment by Stadicus** [comment]
I just thought that I was able to recreate the issue, but it was my own error. For testing purposes, I quickly entered the password "12345" and got the following response:

```
bitcoin@RaspiBolt:/mnt/hdd $ lncli create
Input wallet password:
Confirm wallet password:

Do you have an existing cipher seed mnemonic you want to use? (Enter y/n): n

Your cipher seed can optionally be encrypted.
Input your passphrase you wish to encrypt it (or press enter to proceed without a cipher seed passphrase):

Generating fresh cipher seed...

!!!YOU MUST WRITE DOWN THIS SEED TO BE ABLE TO RESTORE THE WALLET!!!

---------------BEGIN LND CIPHER SEED---------------
 1. above      2. apart      3. charge   4. auto
 5. option     6. cousin     7. stick    8. buzz
 9. frost     10. skirt     11. flash   12. movie
13. announce  14. logic     15. want    16. apology
17. impose    18. attitude  19. broken  20. vessel
21. slow      22. away      23. true    24. item
---------------END LND CIPHER SEED-----------------

!!!YOU MUST WRITE DOWN THIS SEED TO BE ABLE TO RESTORE THE WALLET!!!
[lncli] rpc error: code = Unknown desc = password must have at least 8 characters
bitcoin@RaspiBolt:/mnt/hdd $
```

IMHO it's very easy to miss the error output on the last line. I think it would be a good idea to not even cancel the `create` command right after the password entry, and not ask for for additional information and even generate a mnemonicon.

Just my 5 satoshis. :-)

**Comment by Stadicus** [comment]
Another question (I am in the process of retracing all steps, but it takes time until the blockchain is synced again). When I set up my initial configuration, I created the wallet for testnet. AFAIK I could switch very easily to mainnet, without deleting any macaroons or wallet. 

I am not sure now, but I don't think I had to create a new seed for mainnet. At least I did not note anything about creating in my guide, which I tested step by step.

Is this possible? Then it shouldn't be necessary to delete anything or create a new wallet, right?

**Comment by Roasbeef** [comment]
>  For testing purposes, I quickly entered the password "12345" and got the following response:

The error in the command shows that the password was invalid.

**Comment by Stadicus** [comment]
> IMHO it's very easy to miss the error output on the last line.

Yes, I got that later on. It just not what one expects to get the error three steps after entering the password. But certainly not a high priority issue, more something in regards to UX.

**Comment by Stadicus** [comment]
Issue seems RAM related as stated by @aakselrod in this [issue](https://github.com/Stadicus/guides/issues/8). Creating an additional swap file seems to solve it. Closing this issue for now.

**Comment by marshabl** [comment]
FWIW, I commented out the CONF_SWAPSIZE=1000 @Stadicus 's guide, then deleted everything in the downloads folder and restarted bitcoind and lnd. This worked for me, so hopefully it works for others. I am no expert here, but do we need to have CONF_SWAPSIZE=1000?? Perhaps delete from guide?

This guide: https://brettmorrison.com/running-a-bitcoin-lightning-full-node-on-raspberry-pi
has some helpful pointers, particularly in the comments section.

**Comment by rek79** [comment]
Resolved the issue (I think).  Please reference my post here:
https://github.com/Stadicus/guides/issues/8#issuecomment-423858292

**Comment by ddolgov** [comment]
What is the solution to this issue?

I've closely followed the Thundroid guide on a fresh odroid system and the `.macaroon` files are nowhere to be found after I successfully ran `lncli create` command:
```
---------------END LND CIPHER SEED-----------------

!!!YOU MUST WRITE DOWN THIS SEED TO BE ABLE TO RESTORE THE WALLET!!!

lnd successfully initialized!
bitcoin@odroid:/home/admin/download$
.....
admin@odroid:~/download$ sudo find / -name '*macaroons*' 2>/dev/null
/mnt/hdd/lnd/data/chain/bitcoin/testnet/macaroons.db
admin@odroid:~/download$
```
The only difference with the guide was that I've installed lnd-0.5.2 and it uses ZMQ interface with bitcoind, so the zmq lines in `bitcoin.conf` have to point to different ports.

Here is the `journalctl` logging from `lnd`:
```
Mar 13 15:17:33 odroid systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Mar 13 15:17:33 odroid systemd[1]: Stopped LND Lightning Daemon.
Mar 13 15:17:33 odroid systemd[1]: Started LND Lightning Daemon.
Mar 13 15:17:33 odroid lnd[1546]: Attempting automatic RPC configuration to bitcoind
Mar 13 15:17:33 odroid lnd[1546]: Automatically obtained bitcoind's RPC credentials
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.711 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.712 [INF] LTND: Active chain: Bitcoin (network=testnet)
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.729 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.729 [INF] RPCS: Generating TLS certificates...
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.732 [INF] RPCS: Done generating TLS certificates
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.734 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.734 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
Mar 13 15:17:33 odroid lnd[1546]: 2019-03-13 15:17:33.734 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Mar 13 15:42:56 odroid lnd[1546]: 2019-03-13 15:42:56.011 [INF] LNWL: Opened wallet
Mar 13 15:42:56 odroid lnd[1546]: 2019-03-13 15:42:56.300 [INF] LTND: Primary chain is set to: bitcoin
Mar 13 15:42:56 odroid lnd[1546]: 2019-03-13 15:42:56.360 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:28332
Mar 13 15:42:56 odroid lnd[1546]: 2019-03-13 15:42:56.360 [INF] LTND: Initializing bitcoind backed fee estimator
Mar 13 15:42:56 odroid lnd[1546]: 2019-03-13 15:42:56.360 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:28333
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.486 [INF] LNWL: The wallet has been unlocked without a time limit
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.543 [INF] LTND: LightningWallet opened
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.643 [INF] HSWC: Restoring in-memory circuit state from disk
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.653 [INF] LNWL: Caught up to height 0
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.661 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.780 [INF] RPCS: RPC server listening on 127.0.0.1:10009
Mar 13 15:43:00 odroid lnd[1546]: 2019-03-13 15:43:00.782 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
Mar 13 15:43:01 odroid lnd[1546]: 2019-03-13 15:43:01.469 [INF] LTND: Waiting for chain backend to finish sync, start_height=497774
Mar 13 15:47:31 odroid lnd[1546]: 2019-03-13 15:47:31.245 [INF] LNWL: Caught up to height 10000
Mar 13 15:49:43 odroid lnd[1546]: 2019-03-13 15:49:43.862 [INF] LNWL: Caught up to height 20000
```

**Comment by halseth** [comment]
@ddolgov If it works, you're fine 👍
