### ISSUE TITLE
Forced channel closing still showed as pending after 90+ confs

### ISSUE THREAD

**Issue by lobsterpub** [lightningnetwork/lnd#895]
I forced closed a channel yesterday and it is still showing up as "pending_force_closing_channels" after 90+ bitcoin testnet onchain confirmations.

The channel was opened by a remote peer and my node had a zero balance in the channel.

My bitcoind is running and fully synced.  I also tried restarting LND and it was still showing pending.

I am on commit b0c35d5

**Comment by Roasbeef** [comment]
Is your `lnd` node still connected to your `bitcoind` node if you examine the logs? [After this PR lands](https://github.com/Roasbeef/btcwallet/pull/21) , it'll properly reconnect in the case of a `zmq` connection drop. 


If you check the logs, was there a sweep transaction that was broadcast?

**Comment by Roasbeef** [comment]
If your node had zero balance in the channel, [then it should've skipped straight to the resolution phase](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L1367).

**Comment by lobsterpub** [comment]
I check the logs but they only go back about an hour so didn't find anything about the ZMQ being dropped.  On restart it shows it connected to ZMQ. Still shows channel as pending.

**Comment by Roasbeef** [comment]
Upon restart, if you grep for `CTFN`, what log lines appear? It should re-request confirmation notifications for that channel or other channels. Another relevant sub-system here is `CNCT` as if you are waiting for a timelock sweep, then that may persist. 

When you do `pendingchannels` what shows up as `blocks_til_maturity`? With current params on testnet, it may be in the high hundreds of blocks.

**Comment by Roasbeef** [comment]
Since you force closed the channel, you'll need to wait for the relative CSV timelock.

**Comment by lobsterpub** [comment]
Ok, just realized that I actually had funds in this channel, the remote node was the one with zero balance.  Time til Maturity is 291 blocks.  I think this issue can be CLOSED. Thanks.

**Comment by Roasbeef** [comment]
NP!
