### ISSUE TITLE
[Request] Include a pending_balance in channelbalance response

### ISSUE THREAD

**Issue by MDrollette** [lightningnetwork/lnd#896]
Currently, if you open a channel, the funds are not counted in `walletbalance` and do not yet show in `channelbalance`. It would be helpful to be able to see all the totals necessary to determine the full balance of your node. This could be a new rpc method, or adding additional totals to existing methods. Possibly the response of `channelbalance` could include "pending_balance" as well as "available_balance" (or "unavailable_balance"?)

**Comment by vapopov** [comment]
I'll take this issue
