### ISSUE TITLE
Route Blinding Receive: follow ups

### ISSUE THREAD

**Issue by ellemouton** [lightningnetwork/lnd#8965]
Issue just to track adding some UX improvements for route blinding receives before we ship them in 0.18.3. 

Shout out to @Roasbeef for all the testing & suggestions. Linking the main points here:

- https://github.com/lightningnetwork/lnd/pull/8764#issuecomment-2261809680
- https://github.com/lightningnetwork/lnd/pull/8764#issuecomment-2261820106

I'll get on these first thing Monday ⚡

**Comment by Roasbeef** [comment]
One other request: a tester tried to pay an invoice from an unupdated node and got "no route found". We should do stricter checks up front to detect that there's an unknown required feature bit, error'ing out with a nice message.

**Comment by ellemouton** [comment]
> a tester tried to pay an invoice from an unupdated node and got "no route found". We should do stricter checks up front to detect that there's an unknown required feature bit, error'ing out with a nice message.

cool yeah we actually already do the strict check so it's just a matter of a nicer error message. 

https://github.com/lightningnetwork/lnd/blob/c46b1a467afd96109c9e5f1fced1eae8aed6c98d/routing/payment_session.go#L107-L117

where we switch out `errUnknownRequiredFeature` to `channeldb.FailureReasonNoRoute`

The issue is that we persist things as `channeldb.FailureReasonNoRoute`... so i dont think its as simple as adding a new channeldb Failure reason since then past errors are inconsistent with newer ones. 

So perhaps rather a matter of just passing the `noRouteError` back through to the CLI so the user can see this more useful error

**Comment by ellemouton** [comment]
ok the error message for the above should be more clear now with the latest update in the PR. the only thing is that this will only be useful for the _next_ unknown feature bit since any node that has updated to the code with the better error message will also understand the route blinding feature bit 🤓
