### ISSUE TITLE
Curious: relationship to ElementsProject/lightning

### ISSUE THREAD

**Issue by redsquirrel** [LightningNetwork/lnd#9]
Just a Lightning newbie trying to wrap my head around the work that's going in this space.... What's the relationship between [lnd](https://github.com/LightningNetwork/lnd) and [ElementsProject/lightning](https://github.com/ElementsProject/lightning)? Thanks!

**Comment by PaulCapestany** [comment]
@redsquirrel would be curious to hear if the ["Other Lightning Network implementations"](https://github.com/paulcapestany/lnd/tree/readme#other-lightning-network-implementations) section in PR https://github.com/LightningNetwork/lnd/pull/10/ helps answer your question?

**Comment by redsquirrel** [comment]
@PaulCapestany I just read it, and it absolutely does. Thanks! :+1:

**Comment by PaulCapestany** [comment]
Good stuff 👍
