### ISSUE TITLE
ListPayments query is very slow

### ISSUE THREAD

**Issue by saubyk** [lightningnetwork/lnd#9015]
### Discussed in https://github.com/lightningnetwork/lnd/discussions/9012

<div type='discussions-op-text'>

<sup>Originally posted by **Jaccccc8** August 15, 2024</sup>
hi, we've run a LND node on 8c16g instance for over 1 year, sending payments for CEX users. 

Recently we've encounter some very slow ListPayments query, e.g. curl -L "localhost:8080/v1/payments?creation_date_start=1723701296&creation_date_end=1723709096&max_payments=100&include_incomplete=true"

the *date_start & *ate_end range is roughly 2 hours, but it takes over 8859ms to complete.
How could i speed up this RPC query? will there be optimization for this?</div>

**Comment by Roasbeef** [comment]
Closing to track in #9069
