### ISSUE TITLE
Missing satoshis

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#903]
Saturday I've started lnd with autopilot, opened a channel and made a few payments. After a while I noticed that reported balance is suspiciously low. I started investigating so I listed wallet transactions and balance:

Onchain:

Timestamp Delta
1521290038 500000
1521297346 -100704
1521300690 -58060
1521304730 -38543

Payments:

Timestamp Delta
1521297471 100
1521297773 100
1521298168 100
1521302603 100
1521302875 100
1521302996 100
1521303032 100
1521305297 1500
1521305392 100

walletbalance: 302693
channelbalance: 91397

Wallet balance seems OK (500000-100704-58060-38543 == 302693)
One would expect channel balance to be (100704+58060+38543)-(8*100+1500) == 195007.

Of course, there are blockchain fees, so the difference is the blockchain fees? 195007-91397 == 103610.
That seems too high. It would mean I paid 25902.5 satoshis per transaction, which is ridiculously high given that the fee rate is around 1sat/B and transaction should be under 500B. In other words, it'd mean I paid ~52sat/B.

Are fees set by lnd really this high or am I missing something?

**Comment by Roasbeef** [comment]
Suspiciously low? If we're making pending channels, then those inputs will be locked to avoid double spends, and won't be reflected in the `walletbalance` or `channelbalance`. Also note that we use higher-ish fees on the commitment transaction to ensure that if we need to broadcast, then it gets into the block in a timely manner. You can look at all the fees on your channels using `listchannels`. You can also check the fee estimates that your node is returning using the `estimatefee` command.

**Comment by Kixunil** [comment]
I'm still confused, I will investigate again when I'm not drunk. :)
