### ISSUE TITLE
[bug]: CommitSig deficiency causes HTLCs insufficiently populated on node restart

### ISSUE THREAD

**Issue by dstadulis** [lightningnetwork/lnd#9031]
### Background

[incomplete background]
1) In the scenario where one nodes hangs during of path finding,
2) The data which lnd `CommitSig` handles ?results in a deficient state
3) Which results in downstream uses of lnd (tapd in this case) where HT sigs are blank

## Initial CommitSig deficiency
https://github.com/lightningnetwork/lnd/blob/dcd921ad6945f26dd9786b025f45aab944d13d68/lnwallet/channel.go#L4096-L4108

## This should be set:
https://github.com/lightningnetwork/lnd/blob/1b353b0bfd58a6dfeafc2878111404048826b41d/lnwallet/channel.go#L4745

## TODO
- [ ] Assess if these gaps could causes `UnpackSigs` to fail:
https://github.com/lightninglabs/taproot-assets/blob/8eb6c5345f77d07b07ca9fbb5a76943678049eff/tapchannel/aux_leaf_signer.go#L147

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/9032
