### ISSUE TITLE
Incorrect number of channels on getinfo?

### ISSUE THREAD

**Issue by Fr4nZ82** [lightningnetwork/lnd#905]
If i do lncli listchannels i see 2 active channels, if i do lncli getinfo i see 2 pending and 2 active.
Restarted lnd and wait 60 min...
If i do lncli listchannels i see 3 active channels, if i do lncli getinfo i see 3 pending and 2 active.
autopilot is active
im in testnet

**Comment by Roasbeef** [comment]
Active on `getinfo` means actually able to use and online. It consults the peers directly. A channel may actually be active, but the peer haven't yet loaded the channel. `listchannels` will hit the database, then check the switch itself to ensure the channel is present. If you have pending channels that are nearly finalized, the two values can diverge. But it's just cosmetic.
