### ISSUE TITLE
[bug]: Unable to run lnd 0.18.3rc2 with bitcoin core v28.0rc1

### ISSUE THREAD

**Issue by bufo24** [lightningnetwork/lnd#9053]
### Background

I am getting an error after unlocking lnd:

```
Sep 01 16:32:46 bitcoin-mainnet lnd[423674]: 2024-09-01 16:32:46.792 [ERR] LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
Sep 01 16:32:46 bitcoin-mainnet lnd[423674]: 2024-09-01 16:32:46.792 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
```

### Your environment

* lnd v0.18.3-beta.rc2
* Linux 6.1.0-21-amd64 Debian 6.1.90-1 (2024-05-03) x86_64 
* Bitcoin v28.0rc1

### Steps to reproduce

I upgraded bitcoin core from v27.0 to v28.0rc1, while lnd was still on v0.18.0, got the error as describe above. Then I upgraded lnd to v0.18.3rc2 and still got the same error.

### Expected behaviour

LND should run with bitcoin core v28.0

### Actual behaviour

LND cannot start using bitcoin core v28.0 as backend

**Comment by guggero** [comment]
Thanks a lot for testing with the RC! This was broken by https://github.com/bitcoin/bitcoin/pull/29845. I've created a fix here: https://github.com/btcsuite/btcd/pull/2245.

**Comment by Sjors** [comment]
Please also open an issue on the Bitcoin Core when something like this happens... :-)

**Comment by Sjors** [comment]
I would be useful to know if the current Lnd master branch works now that  https://github.com/barebitcoin/btcd/pull/4 was merged.

**Comment by ziggie1984** [comment]
We still need to bump the version of the btcd package so current master won't work.

**Comment by Sjors** [comment]
Bitcoin Core v28.0 will be released very soon(tm).

**Comment by twofaktor** [comment]
Hello, will this fix be applied with LND v18.4 before Bitcoin Core v28 is released?

I still don't see any precompiled binaries for LND v18.4, but I do see precompiled binaries for Bitcoin Core v28....

**Comment by bufo24** [comment]
@twofaktor LND v0.18.4 isn't released yet.

**Comment by twofaktor** [comment]
> @twofaktor LND v0.18.4 isn't released yet.

I know, and that worries me since it seems that Bitcoin Core v28 will be released earlier and LND v018.3 is not compatible with Bitcoin Core v28...

**Comment by orangeshyguy21** [comment]
+1 to this issue 
Trying to run lnd v 0.18.3-beta with btc core v28.0 and getting the original thread error
chain set to testnet3

Have any temporary measures been found to overcome the fault?

**Comment by bufo24** [comment]
You have to enable the deprecated warnings rpc on bitcoin core using: `-deprecatedrpc=warnings`
