### ISSUE TITLE
[bug]: Node stuck during synchronization when using --neutrino.connect=faucet.lightning.community

### ISSUE THREAD

**Issue by AleAndForCode** [lightningnetwork/lnd#9054]
### Background

While setting up an lnd node on testnet, following the [example in Docker Instructions](https://github.com/lightningnetwork/lnd/blob/master/docs/DOCKER.md#example), the node gets stuck during synchronization when using --neutrino.connect=faucet.lightning.community. The node operates normally without this parameter.

The output of lncli --network=testnet neutrino status shows:
```
{
    "active": true,
    "synced": false,
    "block_height": 0,
    "block_hash": "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943",
    "peers": []
}
```

Attempts to manually add peers with lncli neutrino addpeer fail:
```
[ERR] RPCS: [/neutrinorpc.NeutrinoKit/AddPeer]: could not found peer: [peer-ip]:[peer-port]
```

### Environment

lnd version: v0.18.2-beta
Docker on Apple Silicon
Testnet with Neutrino backend

docker-compose.yaml:
```
version: '3'

services:
    lnd:
      image: lightninglabs/lnd:v0.18.2-beta
      container_name: lnd-testnet
      volumes:
        - ./data:/root/.lnd
      command: >
        --bitcoin.active
        --bitcoin.testnet
        --bitcoin.node=neutrino
        --neutrino.connect=faucet.lightning.community
        --feeurl https://pastacity.nl/VjtaVK73NZwGBAisrA3iFg
        --debuglevel=debug
```

### Steps to reproduce

Start the lnd service and monitor the logs.
Check status with `lncli --network=testnet neutrino status`.
Attempt to add any available peer using lncli neutrino addpeer.

Try to connect with faucet.lightning.community using the port number from the lnd log via telnet:
```
telnet faucet.lightning.community 18333
Trying 159.203.125.125...
telnet: connect to address 159.203.125.125: Connection refused
telnet: Unable to connect to remote host
```

[lnd.log](https://github.com/user-attachments/files/16830469/lnd.log)
[lnd-after-unlock.log](https://github.com/user-attachments/files/16830470/lnd-after-unlock.log)

### Expected behaviour

The node should operate normally with the parameters mentioned in the documentation.

### Actual behaviour

The node fails to connect to faucet.lightning.community and gets stuck in the synchronization state and manual another peers addition fails with "could not found peer."

**Comment by guggero** [comment]
We'll look into it.
In the meantime, can you try some other nodes?


```
[neutrino]
# Testnet addpeers
neutrino.addpeer=btcd-testnet.lightning.computer
neutrino.addpeer=lnd.bitrefill.com:18333
neutrino.addpeer=faucet.lightning.community
```
From: https://github.com/alexbosworth/run-lnd?tab=readme-ov-file#install-lnd

**Comment by guggero** [comment]
The node `faucet.lightning.community` was restarted and should work again.
