### ISSUE TITLE
[bug]: Why is listpayments so slow?

### ISSUE THREAD

**Issue by Impa10r** [lightningnetwork/lnd#9069]
### Background

I have only 209 payments, but it takes 43 seconds to list them:
```
$ time lncli listpayments | jq '.payments | length'
209

real    0m43.422s
user    0m0.188s
sys     0m0.142s
```

For comparison, pulling 349,464 of forwards takes less than a second:
```
$ time lncli forwardinghistory > nul

real    0m0.394s
user    0m0.082s
sys     0m0.058s
```

### Your environment

* version of `lnd` 0.18.0
* which operating system (`uname -a` on *Nix) Umbrel 0.54 debian
* version of `btcd`, `bitcoind`, or other backend bitcoind 27.0.0
* any other relevant environment details
![image](https://github.com/user-attachments/assets/d5188fed-fd5b-49c1-8dd7-be21fe299ee6)

**Comment by Impa10r** [comment]
Update: excluding incomplete crashed my node! It is unresponsive now ((

`$ time lncli listpayments --include_incomplete false |  jq '.payments | length'`

**Comment by saubyk** [comment]
Hi @Impa10r what database do you have for LND? Is it regular bbolt (which is the default) or are you running postgres/sqlite?

**Comment by Impa10r** [comment]
> Hi @Impa10r what database do you have for LND? Is it regular bbolt (which is the default) or are you running postgres/sqlite?

regular bolt, DB Size: 1.834 GB Total States Updates: 7,712,708

**Comment by Roasbeef** [comment]
Will close https://github.com/lightningnetwork/lnd/issues/9015 in favor of this, as it's a bit more detailed.

**Comment by Impa10r** [comment]
Update 2: my testnet node with LND 0.18.0 does not suffer from this:
```
$ time lncli listpayments --include_incomplete false | jq '.payments | length'
2371

real    0m0,418s
user    0m0,168s
sys     0m0,488s
```
channel.db size 70mb

**Comment by Roasbeef** [comment]
If you can obtain a [CPU profile](https://github.com/lightningnetwork/lnd/blob/master/docs/debugging_lnd.md#capturing-pprof-data-with-lnd) of a sample run and post the `SVG` or raw file here, that would be super helpful.

**Comment by Impa10r** [comment]
> If you can obtain a [CPU profile](https://github.com/lightningnetwork/lnd/blob/master/docs/debugging_lnd.md#capturing-pprof-data-with-lnd) of a sample run and post the `SVG` or raw file here, that would be super helpful.

Mine runs in docker, not sure how to start it like that ((

**Comment by calvinrzachman** [comment]
How do you spin up your docker container? You can forward a port on your host machine to a port inside the container using something like:
```bash
docker run -p 9736:9736 my-lnd-container
```
Then the `curl` command to `localhost` will hit the container.

Ahh, I've never used Umbrel, but looks like there's some information on how to modify `lnd` config here:
- https://community.umbrel.com/t/can-t-access-lnd-conf/13502
- https://github.com/getumbrel/umbrel-apps/pull/759

**Comment by Impa10r** [comment]
> If you can obtain a [CPU profile](https://github.com/lightningnetwork/lnd/blob/master/docs/debugging_lnd.md#capturing-pprof-data-with-lnd) of a sample run and post the `SVG` or raw file here, that would be super helpful.

taken while `[profile.txt](https://github.com/user-attachments/files/16917248/profile.txt)` was running in another terminal

**Comment by Impa10r** [comment]
> How do you spin up your docker container? You can forward a port on your host machine to a port inside the container using something like:
> 
> ```shell
> docker run -p 9736:9736 my-lnd-container
> ```
> 
> Then the `curl` command to `localhost` will hit the container.
> 
> Ahh, I've never used Umbrel, but looks like there's some information on how to modify `lnd` config here:
> 
> * https://community.umbrel.com/t/can-t-access-lnd-conf/13502
> * [Update docker-compose.yml to reflect umbrel-lnd.conf update getumbrel/umbrel-apps#759](https://github.com/getumbrel/umbrel-apps/pull/759)

I used `umbrel@umbrel:~ $ docker exec -it lightning_lnd_1 /bin/bash`, then `curl`

**Comment by Roasbeef** [comment]
@Impa10r close, that we just a goroutine dump, what we want is an active _profile_. You can hit this endpoint: `http://HOST:PORT/debug/pprof/profile`

**Comment by Impa10r** [comment]
> @Impa10r close, that we just a goroutine dump, what we want is an active _profile_. You can hit this endpoint: `http://HOST:PORT/debug/pprof/profile`


I wish I knew how.
```
umbrel@umbrel:~ $ docker exec -it lightning_lnd_1 /bin/bash
umbrel:/$ curl http://localhost:9736/debug/pprof/profile
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
umbrel:/$ curl http://localhost:9736/debug/pprof/profile --output profile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0Warning: Failed to open the file profile: Permission denied
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (23) Failure writing output to destination, passed 2048 returned 4294967295
umbrel:/$ whoami
whoami: unknown uid 1000
umbrel:/$ su -
su: must be suid to work properly
umbrel:/$ sudo curl http://localhost:9736/debug/pprof/profile --output profile
bash: sudo: command not found
umbrel:/$ apt install sudo
bash: apt: command not found
umbrel:/$ apt-get install sudo
bash: apt-get: command not found
```

**Comment by Impa10r** [comment]
Solved thanks to @ziggie1984!
[profile.zip](https://github.com/user-attachments/files/17084044/profile.zip)

**Comment by ziggie1984** [comment]
![Uploading cpu_profile_impa10r.svg…]()

**Comment by ziggie1984** [comment]
![Uploading cpu_profile_impa10r.svg…]()

**Comment by ziggie1984** [comment]
![Uploading cpu_profile_impalator.png…]()

**Comment by ziggie1984** [comment]
[Uploading cpu_profile.pdf…]()

**Comment by ziggie1984** [comment]
Judging form the cpu profile it seems like most of the cpu time is used on allocgc/scanObject garbage collection calls. I think the main bottleneck is the memory on the system which runs probably on full capacity (the swap as well) and then all the gc calls take way much time and throttle the cpu.

This will be fixed with the new payment sql schema.

Until then we can decide to either: Add a flag to the listpayments which does not fetch the HTLC data, which is probably not always needed.

Moreover we should also limit the max_payments query parameter to a sane amount and not use MaxUint64:

https://github.com/lightningnetwork/lnd/blob/84c91f701cab21c70c5f4292b82a8bcce9a79e63/rpcserver.go#L7202-L7206

This can also be a problem for much performant systems because the payments are all kept in ram.

**Comment by Impa10r** [comment]
So, the conclusion was RAM swapping to disk causing this. I run Elements in addition to LND and Bitcoin full node, so 8 Gb is not enough ((
