### ISSUE TITLE
lncli getinfo does not reflect the port set in lnd.conf

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#907]
I have clighting running on the default port 9735 and lnd.conf with lnd configured to use port 9745.
lncli getinfo returns that it is running on the default when it is not.

lncli getinfo
{
    "identity_pubkey": "03ee83ec25fc43cf1d683be47fd5e2ac39713a489b03fed4350d9623be1ff0d817",
    "alias": "Geektech lnd",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_peers": 3,
    "block_height": 1288747,
    "block_hash": "00000000e01a3990e4da455c8defd7c4456d187186596a801275d2700ae5b5d1",
    "synced_to_chain": true,
    "testnet": true,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "03ee83ec25fc43cf1d683be47fd5e2ac39713a489b03fed4350d9623be1ff0d817@203.86.204.88:9735"
    ],
    "best_header_timestamp": "1521598988"
}

**Comment by Roasbeef** [comment]
Do you mean that your advertised _external IP_ uses port 9745, or that you set `--listen` to use port 9745? The uri shows what we advertise as our external reachable interface, as that might be different from the interface that we're listening on. An example is if you're running a TCP loadbalancer or proxy in front of your node.

**Comment by redstorm1** [comment]
No proxy but you tipped me off to the issue. the external IP still had the default port listed in lnd.conf i have corrected and now getinfo reports the correct port. Closing.
