### ISSUE TITLE
Dep `revision` constraint field

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#909]
Not an urgent. But while trying to import `lnd` in our project faced the issue with dep:
```
Solving failure: No versions of github.com/lightningnetwork/lnd met constraints:
	0.4-beta: Could not introduce github.com/lightningnetwork/lnd@0.4-beta, as it has a 
dependency on google.golang.org/grpc with constraint b3ddf786825de56a4178401b7e174ee332173b66, which has no overlap with existing constraint 
^1.10.0 from (root)
```

Basically if I understand that correctly `revision` field in your dep files forces everybody who import your project to adjust their version accordingly. So, any reason for using `revision` instead of `version`? 

From the the dep docs:
```
revision

A revision is the underlying immutable identifier - like a git commit SHA1. While it is allowed to
 constrain to a revision, doing so is almost always an antipattern.

Usually, folks are inclined to pin to a revision because they feel it will somehow improve their 
project's reproducibility. That is not a good reason. Gopkg.lock provides reproducibility. Only use 
revision if you have a good reason to believe that no other version of that dependency could work.

```

**Comment by Roasbeef** [comment]
We use revision as its a stronger binding that a version. With the version, it's possible that the version of the library changes from under us if it follows semantic versioning. As a result, we instead prefer commit hashes as these are deterministic.

**Comment by AndrewSamokhvalov** [comment]
Agree that this is much better from stability standpoint, but also probably worth to look at it from developers standpoint. For now I just manually changed all versions in our dep files to use `revision` to be compatible with `lnd`, if this would result in some issues I will try to reach you out, but for now it is good. 

So, anyway that it worth mentioning, probably someone else experience the same situation, and it would help.
