### ISSUE TITLE
[bug]: DNS Seed Down (Server Misbehaving)

### ISSUE THREAD

**Issue by apectgmq** [lightningnetwork/lnd#9139]
This seems like a huge issue... lnd won't work. Any idea when it will be fixed? Should be more decentralized.

```failed to load config: ValidateConfig: error parsing tor dns: lookup nodes.lightning.directory: server misbehaving```

**Comment by dstadulis** [comment]
Parsing of the config file has failed

Does the config file confirm to the requirements?
https://github.com/lightningnetwork/lnd/blob/84c91f701cab21c70c5f4292b82a8bcce9a79e63/docs/configuring_tor.md?plain=1#L79
e.g. is the port specified?

**Comment by dstadulis** [comment]
Closing as config parsing functionality seems correct.

Can reopen if the correct DNS address doesn't parse correctly
