### ISSUE TITLE
[bug]: PendingSweeps CLI missing from web documentation

### ISSUE THREAD

**Issue by AndySchroder** [lightningnetwork/lnd#9156]
At https://lightning.engineering/api-docs/api/lnd/wallet-kit/pending-sweeps/index.html it says `# There is no CLI command for this RPC`, however, `lncli wallet help|grep pendingsweeps` yields `pendingsweeps      List all outputs that are pending to be swept within lnd.` and the command works. Please update the web based documentation so people can find this command without using the command line.

**Comment by feelancer21** [comment]
Same for `lncli wallet estimatefeerate` which I added some months ago. Maybe some other commands too. I have no idea where the mapping for doc between proto file and lncli is.

**Comment by guggero** [comment]
To add the commands to the web documentation, the corresponding RPC methods need to start with a special comment.
Example: https://github.com/lightningnetwork/lnd/blob/d72de4cdbc68d9590090705fb949456f436f4c0a/lnrpc/lightning.proto#L47
