### ISSUE TITLE
[bug]: LND v0.18.3 not start with Bitcoin Core v28

### ISSUE THREAD

**Issue by twofaktor** [lightningnetwork/lnd#9163]
### Background

After the update to Bitcoin Core v28, LND v0.18.3 did not start

https://github.com/bitcoin/bitcoin/releases/tag/v28.0

### Your environment

* LND v0.18.3
* Ubuntu server Jammy / Raspberry Pi Bullseye / Bookworm
* bitcoind v28.0

### Steps to reproduce

- Update to Bitcoin Core v28.0
- Start LND v0.18.3

### Expected behaviour

Start without issues

### Actual behaviour

```
lnd[423674]: 2024-09-01 16:32:46.792 [ERR] LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
lnd[423674]: 2024-09-01 16:32:46.792 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
```

Related issue and PR:
https://github.com/lightningnetwork/lnd/issues/9053
https://github.com/btcsuite/btcd/pull/2245
https://github.com/lightningnetwork/lnd/pull/9154

Please release LND v0.18.4 that includes the fix, and provide precompiled binaries **urgently**

**Comment by DerEwige** [comment]
try this option in your bitcoin core:

`deprecatedrpc=warnings`
source: https://github.com/bitcoin/bitcoin/pull/29845

**Comment by twofaktor** [comment]
> try this option in your bitcoin core:
> 
> `deprecatedrpc=warnings` source: [bitcoin/bitcoin#29845](https://github.com/bitcoin/bitcoin/pull/29845)

Thanks, it worked, but I think they should release the final fix by releasing LND v0.18.4

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/issues/9053 

As suggested above, you should set the `deprecatedrpc=warnings` config flag if you want to run with the latest version of bitcoind.

**Comment by twofaktor** [comment]
> See #9053
> 
> As suggested above, you should set the `deprecatedrpc=warnings` config flag if you want to run with the latest version of bitcoind.

Why did you not release the LND v0.18.4 with the fix yet? Why is it not considered a problem of considerable urgency to be solved with precompiled binaries that include the hotfix if right now there is no compatibility between Bitcoin Core and LND?

**Comment by Scully78** [comment]
> try this option in your bitcoin core:
> 
> `deprecatedrpc=warnings` source: [bitcoin/bitcoin#29845](https://github.com/bitcoin/bitcoin/pull/29845)

Hi, I've been trying to set up LND 18.3 with bitcoin 28 but i keep getting that warning mentioned above,where can i change that 'deprecatedrpc=warnings' setting to get LND to run?

**Comment by twofaktor** [comment]
> > try this option in your bitcoin core:
> > `deprecatedrpc=warnings` source: [bitcoin/bitcoin#29845](https://github.com/bitcoin/bitcoin/pull/29845)
> 
> Hi, I've been trying to set up LND 18.3 with bitcoin 28 but i keep getting that warning mentioned above,where can i change that 'deprecatedrpc=warnings' setting to get LND to run?

In the `bitcoin.conf` file of the Bitcoin Core

**Comment by Scully78** [comment]
> > > try this option in your bitcoin core:
> > > `deprecatedrpc=warnings` source: [bitcoin/bitcoin#29845](https://github.com/bitcoin/bitcoin/pull/29845)
> > 
> > 
> > Hi, I've been trying to set up LND 18.3 with bitcoin 28 but i keep getting that warning mentioned above,where can i change that 'deprecatedrpc=warnings' setting to get LND to run?
> 
> In the `bitcoin.conf` file of the Bitcoin Core

Great, thank you very much, that worked

**Comment by pjw65** [comment]
It is still not solved after more than a month. 
The change in bitcoin.conf is only a workaround.
I don't like how the LND Developers ignowre it's users.

**Comment by guggero** [comment]
> It is still not solved after more than a month. The change in bitcoin.conf is only a workaround. I don't like how the LND Developers ignowre it's users.

- Nobody is being ignored. The fix was merged, just not released yet. Bundling a release is a lot of effort. And the upcoming (ETA for an RC this week) `v0.18.4` will have way more than just this single bug fix.
- `lnd` doesn't promise to be forward-compatible. normally that's not an issue, but:
- `bitcoind` **broke** one of its APIs. Meaning it no longer is backward compatible without the flag. Why do we get all the slack for that?
- There is a low-effort workaround available. Which further takes merit away from derailing an already parallel running version release cycle due to a single fix.
