### ISSUE TITLE
[release]: Cherry Pick Commits for LND v0.18.4 Release

### ISSUE THREAD

**Issue by dstadulis** [lightningnetwork/lnd#9173]
## Description:

Create a new branch off of `lnd` v0.18.3 and cherry pick desired commits for the v0.18.4 release.

To facilitate this process, use the script: https://gist.github.com/Roasbeef/b76730b6e5548a4eb2813da0bcf4d82c. 
Note: occasional rebase failures may require manual intervention via a no-ff merge.

## Task:

* Create new branch from `lnd` v0.18.3
* Cherry pick desired commits using the provided script
* Resolve any rebase conflicts or perform manual no-ff merges as needed

**Comment by guggero** [comment]
Resolved by https://github.com/lightningnetwork/lnd/pull/9174.
