### ISSUE TITLE
[custom channels]: finish sweeping of custom channel HTLCs (part 6/5)

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#9176]
The custom channel saga is almost complete, the only missing part is to finish some of the HTLC sweeping code for custom channels.

**Comment by dstadulis** [comment]
Concepts considered during previous design sessions:
During forced HTLC sweeps, create a `sharedGotoChain` call to enhance lnd's decision to go to chain or not.

**Comment by dstadulis** [comment]
Related PRs:
https://github.com/lightningnetwork/lnd/pull/9194
https://github.com/lightninglabs/taproot-assets/pull/1154
