### ISSUE TITLE
addinvoice and listinvoices return "permission denied" error

### ISSUE THREAD

**Issue by mariodian** [lightningnetwork/lnd#921]
When trying to add an invoice or list all invoices I get the following error (in both cases):

`[lncli] rpc error: code = Unknown desc = permission denied`

No related message shows up in logs.

Using the latest commit 807b84e. I could use both commands some days ago (I used the compiled binary at the time).

**Comment by Roasbeef** [comment]
We recently modified the macaroon capabilities structure to allow a new `invoice.macaroon` which only has access to invoice related RPC's. As a result, you'll need to delete your old set of macaroons so a new set can be generated.
