### ISSUE TITLE
Tracking issue: kvdb/postgres-Remove global application level lock

### ISSUE THREAD

**Issue by saubyk** [lightningnetwork/lnd#9229]
Need to remove the global application level lock from the postgres backend. This lock prevents multiple write transactions from happening at the same time, and will also block a writer if a read is on going.

There was a pr merged to address the issue: https://github.com/lightningnetwork/lnd/pull/8644. The change since has been reverted with this pr: https://github.com/lightningnetwork/lnd/pull/9212

Would need a new pr to address the global application level lock issue

**Comment by aakselrod** [comment]
I believe this is because some of the functions passed for retrying aren't idempotent (e.g. they reverse txid bytes with every attempt, so with a retry, channel IDs are written incorrectly reversed).
