### ISSUE TITLE
[protofsm]: `TestStateMachineMsgMapper` is failing in race test

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lnd#9300]
Currently on master, looks like the new state machine test is failing in the race test,

```
--- FAIL: TestStateMachineMsgMapper (0.00s)
    state_machine_test.go:165: 
        	Error Trace:	/home/runner/work/lnd/lnd/protofsm/state_machine_test.go:165
        	            				/home/runner/work/lnd/lnd/protofsm/state_machine_test.go:451
        	Error:      	Object expected to be of type *protofsm.dummyStateStart, but was *protofsm.dummyStateFin
        	Test:       	TestStateMachineMsgMapper
FAIL
FAIL	github.com/lightningnetwork/lnd/protofsm	0.116s
FAIL
```

**Comment by Roasbeef** [comment]
Will check it out, thought had resolved it. When I looked last, everything was being emitted properly, but potential pointed to a race condition in the event dispatcher implementation we use for the notifications.

**Comment by Roasbeef** [comment]
The first state (in this case `dummyStateStart`) is always emitted before processing any events: https://github.com/lightningnetwork/lnd/blob/94f7ed46deab346cc19ff1e6aa00cecdfe3eb775/protofsm/state_machine.go#L634-L636
