### ISSUE TITLE
[bug]:  unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings

### ISSUE THREAD

**Issue by reivanen** [lightningnetwork/lnd#9310]
### Background

Tried to start lnd after not using it since version 0.17.4 and got this error:

> #Attempting automatic RPC configuration to bitcoind
> Automatically obtained bitcoind's RPC credentials
> 2024-11-27 02:02:37.096 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
> 2024-11-27 02:02:37.096 [INF] LTND: Version: 0.18.3-beta commit=v0.18.3-beta, build=production, logging=default, debuglevel=info
> 2024-11-27 02:02:37.097 [INF] LTND: Active chain: Bitcoin (network=mainnet)
> 2024-11-27 02:02:37.097 [INF] RPCS: RPC server listening on 127.0.0.1:10009
> 2024-11-27 02:02:37.101 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
> 2024-11-27 02:02:37.101 [INF] LTND: Opening the main database, this might take a few minutes...
> 2024-11-27 02:02:37.101 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
> 2024-11-27 02:02:37.142 [INF] LTND: Creating local graph and channel state DB instances
> 2024-11-27 02:02:37.205 [INF] CHDB: Checking for schema update: latest_version=31, db_version=31
> 2024-11-27 02:02:37.205 [INF] CHDB: Checking for optional update: prune_revocation_log=false, db_version=empty
> 2024-11-27 02:02:37.209 [INF] LTND: Database(s) now open (time_to_open=107.850799ms)!
> 2024-11-27 02:02:37.209 [INF] LTND: Attempting automatic wallet unlock with password provided in file
> 2024-11-27 02:02:37.806 [INF] LNWL: Opened wallet
> 2024-11-27 02:02:37.863 [ERR] LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
> 2024-11-27 02:02:37.864 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
> 2024-11-27 02:02:37.867 [INF] LTND: Shutdown complete
> 
> error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string

Now i am not able to start version 0.17.4 any more because it says watchtower version is too new.

### Your environment

0.18.3
Linux6.12.1-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat, 23 Nov 2024 09:21:40 +0000 x86_64 GNU/Linux
28.0

### Steps to reproduce
start lnd

**Comment by Roasbeef** [comment]
See this issue: https://github.com/lightningnetwork/lnd/issues/9163

The first release candidate for lnd v0.18.4 (includes the fix) is out. Until the final version of that is released, you can implement this work around: https://github.com/lightningnetwork/lnd/issues/9163#issuecomment-2395220899

**Comment by reivanen** [comment]
thanks, never would have even known about this issue if i had just grabbed the latest  version, it works.
