### ISSUE TITLE
Compilation error: undefined: lnrpc.Channel

### ISSUE THREAD

**Issue by sheepy0905** [lightningnetwork/lnd#932]
go install . ./cmd/...
\# lnd/cmd/lncli
cmd/lncli/commands.go:821:25: undefined: lnrpc.Channel
cmd/lncli/commands.go:907:20: undefined: lnrpc.Channel
cmd/lncli/commands.go:1413:13: unknown field 'ActiveOnly' in struct literal of type lnrpc.ListChannelsRequest
cmd/lncli/commands.go:1414:15: unknown field 'InactiveOnly' in struct literal of type lnrpc.ListChannelsRequest
cmd/lncli/commands.go:1415:13: unknown field 'PublicOnly' in struct literal of type lnrpc.ListChannelsRequest
cmd/lncli/commands.go:1416:14: unknown field 'PrivateOnly' in struct literal of type lnrpc.ListChannelsRequest
\# lnd
./rpcserver.go:1508:7: in.ActiveOnly undefined (type *lnrpc.ListChannelsRequest has no field or method ActiveOnly)
./rpcserver.go:1508:24: in.InactiveOnly undefined (type *lnrpc.ListChannelsRequest has no field or method InactiveOnly)
./rpcserver.go:1513:7: in.PublicOnly undefined (type *lnrpc.ListChannelsRequest has no field or method PublicOnly)
./rpcserver.go:1513:24: in.PrivateOnly undefined (type *lnrpc.ListChannelsRequest has no field or method PrivateOnly)
./rpcserver.go:1566:10: in.ActiveOnly undefined (type *lnrpc.ListChannelsRequest has no field or method ActiveOnly)
./rpcserver.go:1568:10: in.InactiveOnly undefined (type *lnrpc.ListChannelsRequest has no field or method InactiveOnly)
./rpcserver.go:1570:10: in.PublicOnly undefined (type *lnrpc.ListChannelsRequest has no field or method PublicOnly)
./rpcserver.go:1572:10: in.PrivateOnly undefined (type *lnrpc.ListChannelsRequest has no field or method PrivateOnly)
./rpcserver.go:1602:15: undefined: lnrpc.Channel

**Comment by Roasbeef** [comment]
Did you run `dep ensure` first?

**Comment by sheepy0905** [comment]
@Roasbeef Yes I did run through dep ensure. In comparison, if I git pull from tags/v0.4-beta then compilation would pass.

**Comment by Roasbeef** [comment]
I'm confused, are you trying to compile master, or the 0.4-beta tag? If the latter, those structs weren't defined at that point. Evidence that everything builds can be found in our passing travis-ci builds.

**Comment by Roasbeef** [comment]
I think you have some stale data in your working directory.

**Comment by sheepy0905** [comment]
You are right. I think I messed up my compilation directory. I wiped it then recloned. It passes compilation now. Closing.
