### ISSUE TITLE
[bug]: min relay fee rate for `fee.url`

### ISSUE THREAD

**Issue by dzdidi** [lightningnetwork/lnd#9354]
### Background

If LND is using remote fee estimator it will always have `MinRelayFeerate` of `253 sat/kw` 
https://github.com/lightningnetwork/lnd/blob/master/lnwallet/chainfee/estimator.go#L661-L680

Thus will not be able to open channels with other node implementations.

### Your environment

* version of `lnd`: v0.18
* which operating system (`uname -a` on *Nix) - all
* version of `btcd`, `bitcoind`, or other backend - all
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

set config var for fee url `fee.url=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json`
watch logs for `[ERR] LNWL: No min relay fee rate available, using default 253 sat/kw` 

This line https://github.com/lightningnetwork/lnd/blob/master/lnwallet/chainfee/estimator.go#L673-L677
Caused by this instantiation https://github.com/lightningnetwork/lnd/blob/master/lnwallet/chainfee/estimator.go#L664-L667

### Expected behaviour

Use actual minimum relay fee from the network

### Actual behaviour

returns `253 sat/kw`

**Comment by ziggie1984** [comment]
I am actually not convinced that the problem should be solved in LND, but the fee-estimator should provide a good Min_relay estimation rather than LND now mixing fee data from the external fee-service and its own chain-backend.

**Comment by dzdidi** [comment]
@ziggie1984 thank you for a quick response!


I do see your point and agree that fee estimator service should provide minimum relay fee. 

The problem however, if I read referenced code right, is that even if it would, LND will not parse it and`253`  will be used by LND regardless of the data provided by fee estimator.

If I am wrong please let me know in what format should I provide fees via service behind `fee.url` so that `MinRelayFeerate` will be accepted and used by LND. 

Also note that example of fee estimator given by LND does not provide it https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json (and fee estimation is similar to bitcoincore's fee estimation)

**Comment by ziggie1984** [comment]
so if you have the min_relay fee set you will have the correct feerate:

```
	if err := jsonReader.Decode(&resp); err != nil {
		return WebAPIResponse{}, err
	}

	if resp.MinRelayFeerate == 0 {
		log.Errorf("No min relay fee rate available, using default %v",
			FeePerKwFloor)
		resp.MinRelayFeerate = FeePerKwFloor.FeePerKVByte()
	}
```
it only falls back if the `MinRelayFeerate` is still 0 after parsing the json.

**Comment by dzdidi** [comment]
@ziggie1984 then I am reading code wrong. Thank you!

**Comment by dzdidi** [comment]
Thank you @ziggie1984  and @djkazic
