### ISSUE TITLE
Different zmqpath ports in install dokumentations

### ISSUE THREAD

**Issue by littleskunk** [lightningnetwork/lnd#936]
As new user I would like to follow the default configuration. Bitcoin.conf and lnd.conf contain different zmqpath ports. Which one is the recommended default port?

Port 28332: https://github.com/lightningnetwork/lnd/blob/47329c9267f03887a2f1596a99f23446dc7d4176/docs/INSTALL.md#L215
Port 18501 https://github.com/lightningnetwork/lnd/blob/0c1b619e53ac88ad53f3a88e5d1129c25ddeaf13/sample-lnd.conf#L190

**Comment by nalinbhardwaj** [comment]
Per [`47329c9`](https://github.com/lightningnetwork/lnd/commit/47329c9267f03887a2f1596a99f23446dc7d4176), `28332` is recommended. A fix for the sample config is a part of #911.
