### ISSUE TITLE
[bug]: 0.18.4 regression: go: go.mod requires go >= 1.22.6 (running go 1.22.5; GOTOOLCHAIN=local)

### ISSUE THREAD

**Issue by schildbach** [lightningnetwork/lnd#9372]
### Background

When building with Docker:

```
21.70 HEAD is now at ddeb83516 Merge pull request #9367 from lightningnetwork/0-18-4-branch-rc3
21.81 go: go.mod requires go >= 1.22.6 (running go 1.22.5; GOTOOLCHAIN=local)
21.81 \033[0;32m Installing release lnd and lncli.\033[0m
21.81 env CGO_ENABLED=0 GOEXPERIMENT=loopvar go install -v -v -trimpath -ldflags=" -s -w -buildid= -X github.com/lightningnetwork/lnd/build.Commit=v0.18.4-beta" -tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc neutrinorpc monitoring peersrpc kvdb_postgres kvdb_etcd kvdb_sqlite" github.com/lightningnetwork/lnd/cmd/lnd
21.82 go: go.mod requires go >= 1.22.6 (running go 1.22.5; GOTOOLCHAIN=local)
21.82 make: *** [Makefile:156: release-install] Error 1
------
Dockerfile:19
--------------------
  18 |     # Install dependencies and build the binaries.
  19 | >>> RUN apk add --no-cache --update alpine-sdk \
  20 | >>>     git \
  21 | >>>     make \
  22 | >>>     gcc \
  23 | >>> &&  git clone $git_url /go/src/github.com/lightningnetwork/lnd \
  24 | >>> &&  cd /go/src/github.com/lightningnetwork/lnd \
  25 | >>> &&  git checkout $checkout \
  26 | >>> &&  make release-install
  27 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache --update alpine-sdk     git     make     gcc &&  git clone $git_url /go/src/github.com/lightningnetwork/lnd &&  cd /go/src/github.com/lightningnetwork/lnd &&  git checkout $checkout &&  make release-install" did not complete successfully: exit code: 2
```

### Your environment

* 0.18.4
* Docker on Ubuntu 24.04

### Steps to reproduce

```
$ docker build --build-arg checkout=v0.18.4-beta --pull --no-cache .
```

### Expected behaviour

Docker image is built without errors.

### Actual behaviour

Docker image is not built, throws error.

**Comment by schildbach** [comment]
Sorry, my bad.

**Comment by guggero** [comment]
Just out of curiosity: What was the issue? Just in case someone else runs into the same problem.

**Comment by schildbach** [comment]
I adapted the `checkout` build argument to 0.18.4, but forgot to switch to the 0.18.4 tag in my local workspace. So it used the Dockerfile from 0.18.3 to build 0.18.4 I guess.

**Comment by schildbach** [comment]
Btw. it's a bit weird that a Dockerfile checks out its own repository. Typical Docker projects do their Docker build just with the source code added to the Docker context, maybe downloading dependencies, but not "checking out itself from git".

**Comment by Roasbeef** [comment]
> Typical Docker projects do their Docker build just with the source code added to the Docker context, maybe downloading dependencies, but not "checking out itself from git".

We have a file that does that: [`dev.Dockerfile`](https://github.com/lightningnetwork/lnd/blob/master/dev.Dockerfile).
