### ISSUE TITLE
[bug]: Can't download ots of 18.4

### ISSUE THREAD

**Issue by soc7** [lightningnetwork/lnd#9373]
`$ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/manifest-v$VERSION-beta.txt.ots
--2024-12-18 19:00:28--  https://github.com/lightningnetwork/lnd/releases/download/v0.18.4-beta/manifest-v0.18.4-beta.txt.ots
Resolving github.com (github.com)... 20.201.28.151
Connecting to github.com (github.com)|20.201.28.151|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-18 19:00:28 ERROR 404: Not Found.

`

**Comment by guggero** [comment]
I've added the file. Can you try again please?

**Comment by soc7** [comment]
Thanks, but the one from roastbeef is still missing:
$ wget https://github.com/lightningnetwork/lnd/releases/download/v$VERSION-beta/manifest-roasbeef-v$VERSION-beta.sig.ots
--2024-12-18 19:10:58--  https://github.com/lightningnetwork/lnd/releases/download/v0.18.4-beta/manifest-roasbeef-v0.18.4-beta.sig.ots
Resolving github.com (github.com)... 20.201.28.151
Connecting to github.com (github.com)|20.201.28.151|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-18 19:10:58 ERROR 404: Not Found.

**Comment by guggero** [comment]
Yes, he didn't sign the release yet...

**Comment by guggero** [comment]
cc @Roasbeef

**Comment by soc7** [comment]
It's almost christmas, let the genious rest a bit

**Comment by Roasbeef** [comment]
Fixed!
