### ISSUE TITLE
[bug]: unlocking wallet crashes lnd server with bitcoin-core 28

### ISSUE THREAD

**Issue by asyncmind0** [lightningnetwork/lnd#9389]
### Background

Start lnd, get crash.

probably related to #7256
```
Dec 26 17:28:00 threadripper0 lnd[3126373]: 2024-12-26 17:28:00.559 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Dec 26 17:28:08 threadripper0 lnd[3126373]: 2024-12-26 17:28:08.888 [INF] LNWL: Opened wallet
Dec 26 17:28:09 threadripper0 lnd[3126373]: 2024-12-26 17:28:09.393 [ERR] LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
Dec 26 17:28:09 threadripper0 lnd[3126373]: 2024-12-26 17:28:09.393 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
Dec 26 17:28:09 threadripper0 lnd[3126373]: 2024-12-26 17:28:09.400 [INF] LTND: Shutdown complete
Dec 26 17:28:09 threadripper0 lnd[3126373]: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: unable to detect bitcoind version: json: cannot unmarshal array into Go struct field GetNetworkInfoResult.warnings of type string
```

### Your environment

* version of `lnd`: lnd version 0.18.2-beta
* which operating system (`uname -a` on *Nix): ```Linux threadripper0 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC  x86_64 GNU/Linux```
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v28.0.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by marks909** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by guggero** [comment]
You need to update to the latest version (`v0.18.4-beta`). See https://github.com/lightningnetwork/lnd/issues/9310.
