### ISSUE TITLE
Incorrect satoshi rounding

### ISSUE THREAD

**Issue by pokazef** [lightningnetwork/lnd#939]
Some code is based on the assumption that `satoshiAmount = int64(bitcoinAmount * 1e8)`. This seems to be incorrect. For example, the go code:

    a := 3e-8
    fmt.Println(int64(a * 1e8))
prints `2`, not `3`.

This happens in [btcwallet.go](https://github.com/lightningnetwork/lnd/blob/18e6705d97840bfe4040a8a373ba40bc6a1b4b59/lnwallet/btcwallet/btcwallet.go#L335), where the value of some UTXOs is off by one satoshi which makes the wallet balance report wrong. Here, using the `btcutil.NewAmount` function instead (which does correct rounding) would solve the problem.

But the issue seems to be present in other places (e.g. blockchain.go) which do not depend on btcutil and thus might need to be explicitly rounded.

**Comment by zavan** [comment]
I see an error that may be a result of this:

```
{
	"payment_error": "unable to route payment to destination: TemporaryChannelFailure: insufficient capacity in available outgoing links: need 175120982 mSAT, max available is 174696018 mSAT",
	"payment_preimage": "",
	"payment_route": null
}
```

Looks like it's picking up a route based on a rounded down value.

**Comment by Roasbeef** [comment]
@zavan I don't think that's related at all, this issue is isolated to the way we convert BTC from the rpc calls into satoshis that we'll use for manipulation internally.

**Comment by zavan** [comment]
@roasbeef oh ok. That’s another problem I was getting earlier, which later evolved to the ones I told you about on Twitter and #940, I can’t reproduce it anymore.
