### ISSUE TITLE
Failed to close channel on LTC mainnet

### ISSUE THREAD

**Issue by Jasonhcwong** [lightningnetwork/lnd#944]
I was testing lightning over LTC on mainnet.
I managed to establish a channel between my two nodes but failed to close the channel.
The channel opened at around 2018-03-24 21:34:23.541.
The other node tried to close the channel at around 2018-03-25 00:04:45.128
It failed to broadcast the close tx with error msg: 2018-03-25 00:04:45.661 [ERR] PEER: unable to process close msg: -26: 64: dust
lnd was shutdown accidentally some time later.
When I tried to start lnd again, it exited when the same error message while trying to close the channel.

Any idea?

[lnd.log](https://github.com/lightningnetwork/lnd/files/1847618/lnd.log)

**Comment by Roasbeef** [comment]
Hmm, looks to be a misconfigured dust limit for LTC itself. The output is 5k SAT, which is will above dust for BTC, but seems LTC policy is rejecting that value at present.

**Comment by Jasonhcwong** [comment]
I did some debug/hacking:
1. change file "vendor/github.com/roasbeef/btcwallet/wallet/txrules/rules.go":   
```
    func GetDustThreshold(scriptSize int, relayFeePerKb btcutil.Amount) btcutil.Amount {
        return 1
}  
    func IsDustAmount(amount btcutil.Amount, scriptSize int, relayFeePerKb btcutil.Amount) bool {
        return false
}  
    func IsDustOutput(output *wire.TxOut, relayFeePerKb btcutil.Amount) bool {
        return false
} 
```
2. change litecoind config:  
```
discardfee=0.00000001
mintxfee=0.00000001
minrelaytxfee=0.00000001
```  
But, none of them helps.

**Comment by Roasbeef** [comment]
The commitment already has what seems to be a "dusty" output, so modifying those checks won't have any effect.

**Comment by cfromknecht** [comment]
@Jasonhcwong what version of litecoind are you running?

**Comment by Jasonhcwong** [comment]
@cfromknecht I am using 0.15.1

**Comment by Jasonhcwong** [comment]
some questions:
1. Does it means that the min balance of a node should be at least 54600 sat when closing a channel? What will happen if the balance is smaller?
2. Is it possible to ask LND to reopen the closing transaction?
3. Or try to edit the channel db to remove the closing transaction?

**Comment by Jasonhcwong** [comment]
Another question: the DustThreshold of LTC is dynamic and depends on whether it is a segwit transaction :
````
jason@ubuntu-s-2vcpu-2gb-ams3-01:~/litecoin$ grep IsDust ~/.litecoin/debug.log 
2018-03-28 20:57:22 IsDust: txout.nValue: 574986951, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 114561049, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 599320000, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 899217200, DustThreshold: 54000
2018-03-28 20:57:22 IsDust: txout.nValue: 169900000, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 9031189722, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 99000000, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 299000000, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 51860889, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 19900000, DustThreshold: 54600
2018-03-28 20:57:22 IsDust: txout.nValue: 92423682, DustThreshold: 54000
2018-03-28 20:57:22 IsDust: txout.nValue: 58860, DustThreshold: 29400
````
Is it possible to make the dust limit for LTC in LND dynamic too?

**Comment by Roasbeef** [comment]
We've pushed a commit to use the correct dust limit value. You can't update the dust limit of that channel, what you _can_ do though is send the other party enough satoshis to get above the dust limit. After that you'll be able to close as normal. If you can't update the channel, then you'll need to attempt to submit that transaction directly to a miner so it can be mined.
