### ISSUE TITLE
CMGR: Can't accept connection: accept tcp [::]:9745: accept4: too many open files

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#946]
error repeating in the console.
lnd non responsive to commands from lncli.

Error:
2018-03-27 10:20:51.050 [ERR] CMGR: Can't accept connection: accept tcp [::]:9745: accept4: too many open files

Log:
http://paste.ubuntu.com/p/yHnkwWtzkR/

**Comment by Roasbeef** [comment]
I'd check your FD limit within the kernel. There have been some nodes reporting TCP half-open attacks, so you'll either need to limit the number of pending connections within `iptables` for bump up your file descriptor limit.

**Comment by redstorm1** [comment]
I think i might be the architect of my own demise here.

The setup.

I have clightinging running on 9735 and lnd on 9745 on the same box. 
Before i forwarded 9735 & 9745 in IPTABLES as well as from my router i had established a channel using my private IP using:

lncli connect key@192.168.1.1:9735 

to establish a channel between the two implementations locally. 
In the log i see "use of closed network connection" its possible that lnd is not sending the close packet to the syn_ack ?? thus depleting the connection over time.

2018-03-27 15:24:40.598 [INF] PEER: unable to read message from 203.86.204.88:41680: read tcp 192.168.1.1:9745->203.86.204.88:41680: use of closed network connection
2018-03-27 15:24:40.598 [INF] HSWC: Removing channel link with ChannelID(1c87a74d40af32969d1b15f10909b43396f43fc0efa2df5a91c2c17fce58b890)
2018-03-27 15:24:40.598 [INF] HSWC: ChannelLink(90b858ce7fc1c2915adfa2efc03ff49633b40909f1151b9d9632af404da7871c:0) is stopping


If i can forcibly forget the channel on both sides it may resolve.

**Comment by Roasbeef** [comment]
> use of closed network connection

This looks like somehow it's trying to re-use an existing descriptor that's been closed? Or somehow the gateway is trying to forward the outbound connection?

**Comment by redstorm1** [comment]
"pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
                "channel_point": "6472b2ed0ae2eb0093b5510b21a86feb00c41e3443a25e7115fd6e4267320ce9:0",
                "capacity": "777777",
                "local_balance": "472134",
                "remote_balance": "0"
            },
            "closing_txid": "987798822181cc8fce835c4640f79065d705b1ce0e8dd991db319e53a57564e1",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ]

The closing tx has 429 confirmations but yet the channel remains pending?

**Comment by Roasbeef** [comment]
Look at the transaction, you still have an HTLC that isn't yet swept.

**Comment by Roasbeef** [comment]
Looks like that second output has been swept. Closing.
