### ISSUE TITLE
[lncli] rpc error: code = Unknown desc = channel with chan_id=79aa066... not found

### ISSUE THREAD

**Issue by jsgoyette** [lightningnetwork/lnd#947]
I am unable to close any of my channels marked as inactive (as indicated by the `active` flag in the `listchannels` response). I can successfully close active channels, but when I try to close one of my inactive channels it responds with an rpc error saying that it cannot find the channel by `chan_id`. Curiously, the `chan_id` that it reports back with is the **reverse** of the `chan_id` that I entered.

```
> lncli closechannel 8e89043a9430f12e0ffd867b34dd582db4ab9547438718c80032a5656906aa79
[lncli] rpc error: code = Unknown desc = channel with chan_id=79aa066965a53200c81887434795abb42d58dd347b86fd0f2ef130943a04898e not found
```

ARCH = arm7l (Odroid)
KERNEL = Linux 4.14.28-124
BACKEND = bitcoind -testnet
LND VERSION = 0.4.0

**Comment by Roasbeef** [comment]
If a channel is shown as "inactive", then that means the remote peer isn't online. As a result, if you want to immediately start the process of accessing your funds, then you'll need to force close the channel. For closing means that you'll need to wait for a CSV delay before your funds are available again. You can see what this delay is using the `listchannels` command. The delay is displayed in blocks.
