### ISSUE TITLE
Crazy high CPU usage on Mac when bundled in Zap

### ISSUE THREAD

**Issue by pors** [lightningnetwork/lnd#948]
See https://github.com/LN-Zap/zap-desktop/issues/344 for details

**Comment by Empact** [comment]
This relates to 0.3.0. We’ll want to see about reproing with lnd 0.4.0.

**Comment by Roasbeef** [comment]
I'd open this issue on the zap repo itself, I'm not sure how they bundle `lnd` .

**Comment by pors** [comment]
Hmm, stuck in a loop :)

**Comment by Empact** [comment]
Not a loop, @pors! We just need to repro with more specificity so that the report can be informative to LND. To start, we need to repro with the current version of LND, because the cpu issue may already be solved. Let's continue in LN-Zap/zap-desktop#344.
