### ISSUE TITLE
Node type configuration parameter should not be optional

### ISSUE THREAD

**Issue by MrHash** [lightningnetwork/lnd#950]
Instead of defaulting `lnd` to start with the `bitcoin.node` value defaulted to `btcd`, i would suggest that it be an explicitly required config parameter. In my case `lnd` was hanging waiting for the `btcd` backed fee estimator while my configuration was for `bitcoind`.

**Comment by BitfuryLightning** [comment]
May i take this issue?

**Comment by cbarraford** [comment]
I took on this issue and opened a PR (since its been months), https://github.com/cbarraford/lnd/pull/1. Thanks!

**Comment by Roasbeef** [comment]
@cbarraford you opened it on the wrong repo. That PR should be opened on _this_ repo, not your fork.

**Comment by cbarraford** [comment]
@Roasbeef apologies, closed that PR and opened a new one. https://github.com/lightningnetwork/lnd/pull/1534

**Comment by Roasbeef** [comment]
Closing this as it would be a pretty big breaking change from the config level (ppl that aren't setting the node type and using the default).
