### ISSUE TITLE
Question: fee updates greater than channel balances DDOS vector?

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#951]
Is this a DDOS attack vector?

Nodes that try to see the fee to a large amount, Greedy nodes should be routed around and disconnected?

2018-03-28 08:15:29.391 [INF] HSWC: ChannelPoint(744f715b509adab01bd69ed33e474a4db13a359ab1684ef903bc963919f4091e:0): updating commit fee to 176500 sat/kw
2018-03-28 08:15:29.391 [ERR] HSWC: unable to update fee rate: cannot apply fee_update=176500 sat/kw, new fee of 127786000 mSAT is greater than balance of 99819000 mSAT

**Comment by Roasbeef** [comment]
This isn't a DoS vector, it's that we try to increase the fees (seems this is likely on testnet) but we don't have enough funds to do so, so we don't.

**Comment by redstorm1** [comment]
This is an excessive amount though 127786000 mSAT (0.00127786tBTC), not cheap at all.

**Comment by Roasbeef** [comment]
Yes, but as this is testnet, fees don't matter, meaning users just set arbitrary fees. On mainnet, the fee estimator actually outputs relevant results (as fees actually matter).

**Comment by redstorm1** [comment]
I would have expected testnet to produce estimated fees inline with mainnet as a test. will close as appears to be a none issue.

**Comment by Roasbeef** [comment]
The models have certain economic assumptions which exist on mainnet, but
not testnet.
