### ISSUE TITLE
Connection issues.  Please help

### ISSUE THREAD

**Issue by bitcoinbeeman** [lightningnetwork/lnd#952]
I cannot connect to any node.  Have tried multiple times and keep getting "Connection failed".  23.94.196.136:9735  

any help would be much appreciated.

Thanks

**Comment by Roasbeef** [comment]
What error are you getting? Perhaps this would better be solved on one of our chats? 

If a peer isn't listening, then you can't connect outbound to them.

**Comment by bitcoinbeeman** [comment]
![o3ehakoitv dky5krayxsg](https://user-images.githubusercontent.com/37850979/37998183-41f2cbe2-31e3-11e8-87ef-7bfa43c59ec1.jpg)

**Comment by bitcoinbeeman** [comment]
It is strange since I have attempted to connect to probably 100 different nodes and not one will connect to me.

**Comment by bitcoinbeeman** [comment]
Thank you for responding
I sent a picture of the error message.
Let me know if you can help

 

    On Tuesday, March 27, 2018, 5:06:08 PM CDT, Olaoluwa Osuntokun <notifications@github.com> wrote:  
 
 
What error are you getting? Perhaps this would better be solved on one of our chats?

If a peer isn't listening, then you can't connect outbound to them.

**Comment by aakselrod** [comment]
You appear to be using the Eclair wallet. Are you also using `lnd`? If so, can you give us any error messages from that?

**Comment by TrabbipG** [comment]
@Roasbeef Would you be so kind and link some of those chats? I'm playing around with lnd aswell and I'm experiencing some connectivity problems, but I'm not confident enough yet  to open a new issue here. I'd rather talk with some helpful people on a chat and let you do your work instead of wasting your time with probable incompetence.

**Comment by Roasbeef** [comment]
Either `#lnd` on freenode, or our developer slack (which is linked to in the RAEDME).

**Comment by TrabbipG** [comment]
Thanks!

**Comment by bitcoinbeeman** [comment]
Yes I also would not want to waste your time here.  Sorry I am new to this as well and will try some other place.

**Comment by MeshCollider** [comment]
Closing then, can be reopened if this is due to a bug rather than just a support question :)
