### ISSUE TITLE
Can not open a channel

### ISSUE THREAD

**Issue by takaya-imai** [lightningnetwork/lnd#96]
I try to open a channel but I got an error. How could I open a channel?

```
$ lncli openchannel --node_key=... --local_amt=10000000 --remote_amt=10000000 --num_confs=1
[INF] FNDG: Initiating fundingRequest(localAmt=0.1 BTC, remoteAmt=0.1 BTC, capacity=0.00000573 BTC, numConfs=0.2 BTC, addr=1, dustLimit=xxx.xxx.xxx.xxx:10011)
[ERR] RPCS: unable to open channel to identityPub(&{...}) nor peerID(0): -5: Invalid address or key: QWyyAQGXe8mCbnFSY6nbM9jEqULb4Qj3vVfR
```

That invalid address or key "QWyyAQGXe8mCbnFSY6nbM9jEqULb4Qj3vVfR" appeared as error in log file.

```
[ERR] LNWL: Rescan for 27 addresses failed: -5: Rescan address QWyzMVu23ZP42bbnrhxtJxzDBnfAu4quYYpo: decoded address is of unknown size
```

**Comment by Roasbeef** [comment]
Are you running the `btcd` and `lnd` using testnet or simnet? It looks like `btcd` received an addresses from a different chain that the one it's operating on. 

I've recently pushed some modifications which remove the `remote_amt` field as currently in the wire protocol only single funder transactions are supported. However, I've also added a `push_amt` option whcih allows you to push some funds to the remote side as part of the initial channel funding. If this field is non-zero, then the other side starts with a certain amount of BTC as part of the first commitment transaction.

**Comment by takaya-imai** [comment]
@Roasbeef, Thanks for your response.
>Are you running the btcd and lnd using testnet or simnet?

testnet3
simnet is necessary?

**Comment by AndrewSamokhvalov** [comment]
Hello @takaya-imai! First of all thank you for dedicating your time on `lnd`! 

I don't want you to be bored and until @Roasbeef is there I want suggest you to try slightly different approach - use `simnet` for first time. The result in this case should be more deterministic. After that I believe that you will feel more confident with usage of `lnd`. We have an article about ["How to create lightning network cluster in simnet"](https://github.com/lightningnetwork/lnd/tree/master/docker). I hope that this will help you!

**Comment by Roasbeef** [comment]
@takaya-imai nope, you can run on `testnet3. If you update your local version of my [btcd fork](https://github.com/roasbeef/btcd), then you should be able to bring up `lnd` can connect out to the rest of the network.

**Comment by takaya-imai** [comment]
@AndrewSamokhvalov, Thanks.
>We have an article - "How to create lightning network cluster in simnet?" and I hope it will help you!

The article is a good one!

**Comment by takaya-imai** [comment]
@Roasbeef, I try to install your btcd fork but I got the following warning messages.
How do I install your btcd fork? This warning is not critical one?

```
$ git clone https://github.com/Roasbeef/btcd $GOPATH/src/github.com/Roasbeef/btcd
$ cd $GOPATH/src/github.com/Roasbeef/btcd
$ glide install
[WARN]	The name listed in the config file (github.com/roasbeef/btcd) does not match the current location (github.com/Roasbeef/btcd)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/btcsuite/btclog 73889fb79bd687870312b6e40effcecffbd57d30!
[INFO]	--> Found desired version locally github.com/btcsuite/fastsha256 637e656429416087660c84436a2a035d69d54e2e!
[INFO]	--> Found desired version locally github.com/btcsuite/go-flags 6c288d648c1cc1befcb90cb5511dcacf64ae8e61!
[INFO]	--> Found desired version locally github.com/btcsuite/go-socks 4720035b7bfd2a9bb130b1c184f8bbe41b6f0d0f!
...
```

**Comment by Roasbeef** [comment]
@takaya-imai those logging messages aren't critical. That's just `glide` printing some verbose logging describing what it's doing at each step.

**Comment by takaya-imai** [comment]
@Roasbeef I got errors after `go install . ./cmd/...` like [error.txt](https://github.com/lightningnetwork/lnd/files/708028/error.txt).

So I executed the followings to build your btcd fork.

```
$ cd $GOPATH/src/github.com/Roasbeef/btcd/vendor/github.com/
$ git clone https://github.com/Roasbeef/btcd.git
$ cd ../../
$ go install . ./cmd/...
```

**Comment by AndrewSamokhvalov** [comment]
Hello @takaya-imai! Seems, that you forgot to do `glide install`.

**Comment by AndrewSamokhvalov** [comment]
@takaya-imai I edited previous comment, hope it helped you!

**Comment by takaya-imai** [comment]
@AndrewSamokhvalov thanks for useful command `go get -u -v github.com/roasbeef/btcd/...`.

I try again to install [roasbeef/btcd](https://github.com/roasbeef/btcd) then no errors appear... It might that I had a bad environment.
