### ISSUE TITLE
Add Sender-Side Check to Not Pay Same Preimage Twice

### ISSUE THREAD

**Issue by cfromknecht** [lightningnetwork/lnd#973]
Overview
=======
With the recent changes to the switch persistence, we removed the check that would previously reject a duplicate payment to the same invoice for reasons concerning external consistency/fault tolerance. Either way, this check _should_ be done by the sender, instead of relying on the receiver to play nice. That being said, attempting paying an invoice twice is bound to happen due to user error or other bugs, so it would be preferable to have some internal protection against this occurance.

Description
=========
In reality, we aren't concerned so much with payments to individual invoices, so much as payments to the same payment hash. Since different invoices can be crafted with the same preimage, we should opt for the latter as it offers stronger protection. Additionally, we would want these checks to have durability, such that restarting does not compromise our sanity checks.

Payment States
---------------
There are three primary cases we want to consider:
 1. `Grounded` - We initiate a payment and receive an intermittent failure.
 1. `InFlight` - We initiate a payment, but a response has not been received
 1. `Completed` - We initiate a payment and complete a payment successfully

In case 3, we have already paid and naturally don't want to pay again. In case 2, we don't know if it is safe to reinitiate a payment if there is already a payment in flight, so we should withhold any additional attempts to send to that payment hash. Case 1 is the exception, as it is safe to reattempt a payment if we know that we haven't left one in flight prior to restarting. The starting state should be treated equivalently to `Grounded`.

State Transitions
-----------------
These checks/state transitions should be performed by the `htlcswitch.Switch`. When sending via [`SendHTLC`][1], we should check if the payment hash is marked `Completed` or `InFlight`, returning an appropriate error if so. If no entry exists or we are in `Grounded`, the same check should return no error, and atomically transition the payment state to `InFlight`. This should permit `SendHTLC` to proceed as normal.

When we finally receive a response in the switch's [`handleLocalDispatch`][2], we can safely move the payment back to `Grounded` or `Completed`, before attempting to return errors to the router/rpcserver/application. This should happen regardless of whether we are able to find the associated `pendingPayment`. Pending payments are only held in memory, and we may receive a response after having shutdown. However, this allows the user to retry in the event that some response is redelivered.

Steps to completion
==============
- [ ] Create a `PaymentStatus` enum encapsulating the cases , `Grounded`, `InFlight`, and `Completed`. 
- [ ] Add a db bucket `channeldb/payments` mapping `PaymentHash` -> `PaymentStatus`.
- [ ] Abstract the functionality behind an interface, naming suggestion: `ControlTower`.
- [ ] Implement methods performing checks/state transitions, and unit test the behavior.
- [ ] Integrate checks/transitions into switch.
- [ ] Add an integration test to test the fault tolerance of when failing in any of the states outlined above.
- [ ] Add migration to retroactively `Complete` all previous payments.

[1]: https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L290 (htlcswitch.SendHtlc)
[2]: https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/switch.go#L702 (htlcswitch.handleLocalDispatch)

**Comment by vapopov** [comment]
I'll take this issue

**Comment by cfromknecht** [comment]
@vapopov awesome! Ping me if you need anything or want to discuss in more detail

**Comment by vapopov** [comment]
@cfromknecht could you please participate in code review https://github.com/lightningnetwork/lnd/pull/1070 to be sure that I understood everything correct

**Comment by baryluk** [comment]
`lncli lookuppayment` by payment_hash please too :) and include payment status in result too, as well in `lncli listpayments`. Thanks.

**Comment by cfromknecht** [comment]
@baryluk that's a great idea, can you make an issue so we keep track of it?
