### ISSUE TITLE
lnd hangs whit [ERR] SRVR: unable to start server: -22: TX rejected: transaction has no outputs

### ISSUE THREAD

**Issue by Fr4nZ82** [lightningnetwork/lnd#975]
I closed all long time inactive channels, changing some autopilot settings and restart.
After the lncli unlock lnd hangs whit:
2018-03-30 14:21:45.315 [ERR] CNCT: ChannelArbitrator(26bd7fac6bc2eed2b253c36f9e1994f86935b98d44da70d14be5196652ed9b01:0): unable to broadcast close tx: -22: TX rejected: transaction has no outputs
2018-03-30 14:21:45.315 [ERR] CNCT: unable to advance state: -22: TX rejected: transaction has no outputs
2018-03-30 14:21:45.315 [ERR] SRVR: unable to start server: -22: TX rejected: transaction has no outputs

-22: TX rejected: transaction has no outputs

The lncli command i used for close channels was
lncli closechannel 26bd7fac6bc2eed2b253c36f9e1994f86935b98d44da70d14be5196652ed9b01 0 --force
All others channel was closed properly, only this has the problem.
How i can solve and restart lnd?

### Your environment

* version of `lnd` 
0.4-beta (updated today)
* which operating system (`uname -a` on *Nix) 
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
BTCD: Version 0.12.0-beta
* any other relevant environment details

**Comment by Roasbeef** [comment]
This issue has been fixed in the latest version of `lnd`, and there'll be a patch release soon packaging the fix. Applying this small patch, will temporarily allow your node to start up again: 
```diff
diff --git a/contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go
index 8c8ab1ec..602512fc 100644
--- a/contractcourt/chain_arbitrator.go
+++ b/contractcourt/chain_arbitrator.go
@@ -419,7 +419,7 @@ func (c *ChainArbitrator) Start() error {
 	}
 	for _, arbitrator := range c.activeChannels {
 		if err := arbitrator.Start(); err != nil {
-			return err
+			continue
 		}
 	}
```

**Comment by Fr4nZ82** [comment]
Thanks!
