### ISSUE TITLE
LND with Bitcoind connection refused

### ISSUE THREAD

**Issue by tartachyov** [lightningnetwork/lnd#976]
Starting:

bitcoind -txindex -server -daemon -rpcallowip=::/0 -zmqpubrawblock=tcp://127.0.0.1:28332 -zmqpubrawtx=tcp://127.0.0.1:28332 -rpcuser=xxx -rpcpassword=xxx -datadir=/bitcoin -externalip=138.197.176.174 -rpcbind=127.0.0.1 -rpcport 8332

lnd --logdir=/data --bitcoin.active --bitcoin.mainnet --bitcoin.node=bitcoind --bitcoind.rpcuser=xxx --bitcoind.rpcpass=xxx --bitcoind.rpchost=127.0.0.1:8332 --bitcoind.zmqpath=tcp://127.0.0.1:28332 --externalip=138.197.176.174

The result:

2018-03-31 10:34:26.397 [INF] LNWL: Opened wallet
unable to start wallet: dial tcp 127.0.0.1:28332: connect: connection refused
unable to create chain control: dial tcp 127.0.0.1:28332: connect: connection refused
dial tcp 127.0.0.1:28332: connect: connection refused

What's can be wrong with it?

**Comment by Roasbeef** [comment]
This would mean that the node isn't actually listening on the target port. You can use commands like `lsof` to detect if the node is actually listening. You'll also need to ensure that your `bitcoind` node was compiled _with_ `zmq`. Otherwise it will silently fail to create the server.

**Comment by blockchainsolutionshi** [comment]
Can I add zmq after syncing bitcoind, or do I have to do the whole thing over again?

**Comment by halseth** [comment]
@blockchainsolutionshi You can add it after sync :)
