### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BitBargain** [lightningnetwork/lnd#977]
LND stopped. I'm not sure if there's much to do about this or anything but it's certainly unexpected/undesired. I'm hoping the shutdown logs may help to fix an issue. Feel free to close this one if it's not helpful.

Version 0.4, on a Debian 4.9.20-grsec, 25G free RAM, Bitcoin Core RPC client version v0.15.99.0-9cf6393a4

2018-03-29 04:49:24.813 [INF] CRTR: Block 000000000000000000155720ac9c425fc94b9c6343e2da0a4bb43dbb735544e0 (height=515624) clo
sed 0 channels
2018-03-29 04:49:24.867 [INF] NTFN: New block: height=515624, sha=000000000000000000155720ac9c425fc94b9c6343e2da0a4bb43dbb7355
44e0
2018-03-29 04:49:24.867 [INF] UTXN: Attempting to graduate height=515624: num_kids=0, num_babies=0
2018-03-29 04:49:26.692 [INF] CRTR: Updated vertex data for node=0312c02755c6a3475f872be27e71fdb7703a61a25777401a26125e1c772c7e0f6a
2018-03-29 04:49:30.203 [INF] NTFN: Cancelling epoch notification, epoch_id=15092
2018-03-29 04:49:30.203 [INF] HSWC: ChannelLink(393a14959e5e974f2b1af08f50da837baf08a9cd47a78e1c8f91e50dbab8bf13:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e8ef7]

goroutine 118602734 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*commitmentChain).tail(...)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1051
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).ReceiveNewCommitment(0xc5bb1ed200, 0x95876f9c07166d0e, 0xf027ee841935e65a, 0xca69236234982f72, 0xea563ca1e51eebb5, 0x56846c853f5fe541, 0xf2b3242d3bd13a74, 0x514c87875ae5ef7b, 0xd600a49189a4583f, 0x0, ...)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3648 +0xb7
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).handleUpstreamMsg(0xc5e688a5a0, 0x15b93c0, 0xc4ba8da300)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1235 +0xf08
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc5e688a5a0)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:921 +0x90e
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:391 +0x150

**Comment by Roasbeef** [comment]
Did you have any locally applied patches? Also do you have log messages of _right_ before the restart? Thanks!

**Comment by halseth** [comment]
@wpaulino Can you see if you can find anything interesting here? :)

**Comment by plantOS** [comment]
LND keeps crashing with similar error but different address. @Roasbeef what do you think is going on here? Kinda frustrating as we are trying to build a LN wallet service here in Southeast Asia. Please help.

**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x8cb15d]**

goroutine 124754 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).logUpdateToPayDesc(0xc4208c2a20, 0xc420a5f528, 0xc421093080, 0x4b, 0x2bf2, 0xc421b048a0, 0x23d, 0xc4206c6b80, 0xc4206c6ba0, 0xc4206c6bc0)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1546 +0x55d
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc4208c2a20, 0xc4216fc3c0, 0xc4216fc480, 0xc4216fc540, 0xc420931a00, 0xc421b048a0, 0x0, 0x0)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1755 +0x6dc
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc4208c2a20, 0xc4218b37f0, 0xc420a5f770, 0xc421092fc0, 0xc421093080, 0x0, 0xc4218f7170)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1673 +0x47b
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x10acec0, 0xc420086fc0, 0x7fc05d625d88, 0xc4200838c0, 0xc420dad200, 0xeb67b9, 0xc, 0xc420040e00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1372 +0x654
main.(*peer).loadActiveChannels(0xc422156000, 0xc420788f08, 0x1, 0x1, 0x2, 0x2)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/peer.go:311 +0x128
main.(*peer).Start(0xc422156000, 0xc4209c9180, 0x0)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/peer.go:293 +0x74e
main.(*server).peerConnected(0xc4200b23c0, 0x10b91e0, 0xc4209c9180, 0x0, 0x15acc00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:1434 +0x28a
main.(*server).InboundPeerConnected(0xc4200b23c0, 0x10b91e0, 0xc4209c9180)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:1526 +0x2c1
main.(*server).InboundPeerConnected-fm(0x10b91e0, 0xc4209c9180)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:498 +0x3e
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).listenHandler
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:494 +0x1e6

**Comment by halseth** [comment]
@plantOS What commit are you running? Also, did you start seeing this after you recently upgraded? Thanks!

**Comment by plantOS** [comment]
@halseth Appreciate prompt response. Commit details attached below:

```
commit bdf3f4d7753ce950bd14ed56ad96c12097f1b4c9
Merge: 9017d18 7af699f
Author: Olaoluwa Osuntokun <laolu32@gmail.com>
Date:   Fri May 4 12:22:02 2018 -0700

```

**Comment by halseth** [comment]
@plantOS Any reason you are not using the latest commit? 

`master` has a fix that is related to the problem you are seeing, so I would advise you to try pulling the latest version if you can :)

**Comment by plantOS** [comment]
@halseth Good point. Just updated to latest commit. Unfortunately problem still persists and pc has changed

```
commit 6382215346968b69b8b0f5553b7c0bf39e01c550
Merge: 5c42a88 4a200d2
Author: Olaoluwa Osuntokun <laolu32@gmail.com>
Date:   Wed May 23 15:39:30 2018 -0700

```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 **pc=0x8c9a1d**]

goroutine 26430 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).logUpdateToPayDesc(0xc4200c2c60, 0xc4213fb510, 0xc4209ace40, 0x4b, 0x2bf2, 0xc4215ae0c0, 0x23d, 0xc420276040, 0xc420276060, 0xc420276080)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1543 +0x55d
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc4200c2c60, 0xc420c4de00, 0xc420c4dec0, 0xc420482540, 0xc4200cee00, 0xc4215ae0c0, 0x0, 0x0)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1732 +0x3a8
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc4200c2c60, 0xc4207c1808, 0xc4213fb788, 0x0, 0xc4201b9050)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1676 +0x497
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x10b3280, 0xc42007eea0, 0x7f2443d8bab0, 0xc42007ae40, 0xc4202b2c00, 0xebc676, 0xc, 0xc420040e00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1371 +0x63e
main.(*peer).loadActiveChannels(0xc4213a0000, 0xc42096c2f8, 0x1, 0x1, 0x2, 0x2)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/peer.go:313 +0x128
main.(*peer).Start(0xc4213a0000, 0xc4208fea00, 0x0)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/peer.go:295 +0x74e
main.(*server).peerConnected(0xc4200aa3c0, 0x10bf620, 0xc4208fea00, 0x0, 0x15b3d00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:1487 +0x28a
main.(*server).InboundPeerConnected(0xc4200aa3c0, 0x10bf620, 0xc4208fea00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:1563 +0x624
main.(*server).InboundPeerConnected-fm(0x10bf620, 0xc4208fea00)
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/server.go:534 +0x3e
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).listenHandler
	/home/d3vt4r/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:494 +0x1e6
```

**Comment by halseth** [comment]
@plantOS Ok, I will try to get to figure out why this is happening. Can you post the logs from `lnd` from startup until it crashes? (make sure to set the loglevel to `debug`)

**Comment by plantOS** [comment]
@halseth Thanks dude. Logs attached with debug flag on
[lnd_log3.txt](https://github.com/lightningnetwork/lnd/files/2035074/lnd_log3.txt)

**Comment by halseth** [comment]
Thanks! I think I see what is going on.

For some reason the `pending remote commitment` contains log updates (one of them being an `UpdateFailHtlc` that reference HTLCs that are not found on the locked in commitments. So when these updates are processed at startup, they won't find the HTLCs in the update log.

Now the question is how we got into this state. It should not be possible to add a `FailHTLC` to the update log for an HTLC that is not already in the log: https://github.com/lightningnetwork/lnd/blob/6382215346968b69b8b0f5553b7c0bf39e01c550/lnwallet/channel.go#L4439

@cfromknecht Could we end up trying to fail an HTLC twice? In that case I can imagine we would fail the HTLC once and remove it from the commitment, but before we got around to remove it from the update logs (`compactLogs`), we would fail it again, passing the above check. On startup we would now restore the logs with the `Fail` not having any parent HTLC in the index.

@plantOS How comfortable are you making changes to the code? It would be helpful if you could print the content of the  `LogUpdates`. Basically just adding  something like

```go
walletLog.Debugf("ChannelPoint(%v), pending remote LogUpdates: %v", 
                         lc.channelState.FundingOutpoint,
			newLogClosure(func() string {
				return spew.Sdump(pendingRemoteCommitDiff.LogUpdates)
			}),
		)
```

Maybe this would give us some information about what HTLC is trying to be failed, and if we can find it in `lncli fwdinghistory --start_time 1`

**Comment by halseth** [comment]
It could also be the result of the bug that was recently fixed, where the `logIndex` and `htlcIndex` got out of sync after a restore. Not totally sure how this could lead to this crash though..

**Comment by plantOS** [comment]
@halseth Yeap doing it with my team. Ok have amended said code in lnd/lnwallet/channel.go (Line 1719). New log file attached below:
[lnd_log4.txt](https://github.com/lightningnetwork/lnd/files/2036093/lnd_log4.txt)

output from` lncli fwdinghistory --start_time 1`:

```
$ lncli fwdinghistory --start_time 1
{
    "forwarding_events": [
    ],
    "last_offset_index": 0
}

```

**Comment by Roasbeef** [comment]
@plantOS note that this has been fixed in _master_, but you're running a dated version. 0.4.2 that packages up this fix and many others will be released in the next few days.

**Comment by plantOS** [comment]
@Roasbeef Updating and recompiling lnd & **btcd** resolved issue. Our [node](https://explorer.acinq.co/n/02fbd533cfa7e30493d8eae9f4fb53689ff7abea56edaf921e160c40333cec267c) appears to be working now on same commit dated May 23rd. Will keep monitoring status. Appreciate prompt response and looking forward to 0.4.2

```
cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull
make && make install
make btcd
```
