### ISSUE TITLE
Feature Request: Add configuration option to start lnd without the value limits

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#980]
### Background

For Litecoin the current value limits the usage pegged to current about $4.80 USD, to increase those for mainnet usage would be code that later has to be thrown away.

### Your environment

* lnd version 0.4.0-beta
* Linux name 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* litecoind 0.16
* any other relevant environment details

### Steps to reproduce

Try to initiate a Litecoin Lightning payment to BitRefill.  The limit makes this impossible currently because the cheapest Steam voucher is $5.

### Expected behaviour

The max value should around $380 or be the node should be able to disable the limits.

### Actual behaviour

The max value is $4.80 USD.

**Comment by Roasbeef** [comment]
Max values shouldn't be set based on a USD quote. 1 BTC = 1 BTC ;) 

I'd simply use BTC until we add a feature bit to signal larger payment amounts.

**Comment by Roasbeef** [comment]
IIRC, we're the only implementation that has an actively maintained LTC mode, so perhaps we can just bump up those limits when LTC mode is active.

**Comment by PWKad** [comment]
That's actually what I think it should be (using the feature bit, not the USD value) just using a real life example to make the point.  Is there another issue open for the feature bit?  If so I can close this.

**Comment by juscamarena** [comment]
+1 for bumping limit are for ltc. I’d run it.

**Comment by losh11** [comment]
+1 right now LN on Litecoin is pretty much unusable without this feature request.

**Comment by Roasbeef** [comment]
Closing this as we've already bumped up for LTC.
