### ISSUE TITLE
Wrong error message on paying 0 value invoices

### ISSUE THREAD

**Issue by littleskunk** [lightningnetwork/lnd#985]
### Background

Wrong error message.

### Your environment

* lncli version 0.4
* LXC Debian Jessie
* Bitcoin Core RPC client version v0.16.0

### Steps to reproduce

>Invoices without an amount can be created by not supplying any parameters or providing an amount of 0. These invoices allow the payee to specify the amount of satoshis they wish to send.
> `lncli addinvoice --help`

A friend creates a 0 value invoice `lncli addinvoice --memo 'Test' --amt 0`

I try to pay that invoice `lncli payinvoice --pay_req ...`

### Expected behaviour

Error message telling me that the invoice has no value. Please add --amt value.
`lncli payinvoice --pay_req ... --amt 1`

### Actual behaviour

Wrong error message
```
{
        "payment_error": "unable to find a path to destination",
        "payment_preimage": "",
        "payment_route": null
}
```

**Comment by Roasbeef** [comment]
The `payinvoice` command can't be used to pay zero valued invoices. Instead you must use the `sendpayment` command. There's no actual `payinvoice` RPC, instead it just proxies to `sendpayment`.

**Comment by littleskunk** [comment]
`payinvoice --amt 1` will work ;)

**Comment by Roasbeef** [comment]
Sure, but for _custom_ payment conditions (meaning everything isn't in the invoice), for now you'll need to use `sendpayment`.

**Comment by Roasbeef** [comment]
Actually, I'm wrong lol it _does_ properly proxy that value amount. I've tested this locally and it works properly.

**Comment by wpaulino** [comment]
I think what @littleskunk is referring to is that we should return an error to the user if they're attempting to pay an invoice without an amount without specifying one with the `amt` flag.

So something like the following:
```
$ lncli-alice addinvoice
{
	"pay_req": "lnsb1pdtlldepp5fndmye0zgkes0ass8k0py6nn5pu9j9hesawggzdntnxj468t7a7qdqqcqzysnf0ye40ghshhrnpxjlppsadgpfv58hh2sqvjfutzx0cxjmdectanda6nlkqcuht68q0e6eymnv72xd8z6crdc3vd8fydaxkgkyc776gpwaz3lq"
}
$ lncli-bob payinvoice lnsb1...
```
should return an error stating that the user should provide an amount rather than attempting to dispatch the payment.

**Comment by littleskunk** [comment]
Yes the error message is still wrong and doen't give me any hint what I did wrong.

**Comment by mecampbellsoup** [comment]
@Roasbeef @halseth what would the exact requirements be for the fix here please? Thanks :)

**Comment by halseth** [comment]
@mecampbellsoup It should return an error in case an invoice is paid with no a mount specified.

**Comment by 5hanth** [comment]
should we not restrict creating an invoice with `--amt=0` and throw error when attempted in first place?

**Comment by littleskunk** [comment]
>Invoices without an amount can be created by not supplying any
parameters or providing an amount of 0. These invoices allow the payee
to specify the amount of satoshis they wish to send.
> lncli addinvoice --help

That feature is needed for donations and other payments with an unknow amount.

**Comment by dannypaz** [comment]
I received this error with 0.42, when I was setting an invoice's value to 0 and trying to pay it through another node. Once the value was updated, the payment went through.
