### ISSUE TITLE
Autopilot can create impossible channel requests, which fail due to occupying funds without room for transaction fees

### ISSUE THREAD

**Issue by Empact** [lightningnetwork/lnd#986]
### Background

If you configure autopilot to control the entire wallet, it will attempt to open channels with all available funds, which will result in destined-to-fail openChannel directives due to the need to pay fees on opening

### Your environment

* lnd 0.4.0, but also present in master
* mac os
* bitcoind

### Steps to reproduce

Set `autopilot.allocation=1`
Have enough funds for < `autopilot.maxchannels` channels in the wallet.

### Expected behaviour

Autopilot should be able to control the full wallet and account for fees in the final channel opening directive

### Actual behaviour

```
2018-03-31 04:04:09.657 [INF] ATPL: Triggering attachment directive dispatch, total_funds=0.02493046 BTC
2018-03-31 04:04:10.729 [INF] ATPL: Attempting to execute channel attachment directives: ([]autopilot.AttachmentDirective) (len=1 cap=1) {
 (autopilot.AttachmentDirective) {
  PeerKey: (*btcec.PublicKey)(0xXXXX)({
   Curve: (elliptic.Curve) <nil>,
   X: (*big.Int)(0x)(XXXXX),
   Y: (*big.Int)(0x)(YYYYY)
  }),
  ChanAmt: (btcutil.Amount) 0.02493046 BTC,
  Addrs: ([]net.Addr) (len=1 cap=1) {
   (*net.TCPAddr)(0x)(X.X.X.X)
  }
 }
}

2018-03-31 04:04:11.856 [INF] FNDG: Initiating fundingRequest(localAmt=0.02493046 BTC, remoteAmt=0 mSAT, capacity=0.02493046 BTC, chainhash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, addr=X.X.X.X, dustLimit=0.00000573 BTC)
2018-03-31 04:04:11.858 [INF] LNWL: Performing funding tx coin selection using 4 sat/vbyte as fee rate
2018-03-31 04:04:11.858 [WRN] ATPL: Unable to open channel to XXX of 0.02493046 BTC: not enough witness outputs to create funding transaction, need 0.02493658 BTC only have 0.02493046 BTC  available
```

**Comment by Empact** [comment]
Seems like the Heuristics need to try to account for fees, or LND should have a convention whereby the fees are taken out of the channel fund allocation, rather than added to it. The latter seems simpler to me.

Here's where the heuristic sets the problematic amount AFAICT: https://github.com/lightningnetwork/lnd/blob/master/autopilot/prefattach.go#L277

**Comment by Roasbeef** [comment]
At this stage, the `minchansize` and `maxchansize` config params for autopilot should be used. Otherwise, it'll just attempt to shove everything into a giant channel which is typically undesirable.

**Comment by Roasbeef** [comment]
The latter suggested option is a bit difficult as we'd then need to also _lock_ outpoints just for fee quotes.

**Comment by halfik** [comment]
Same issue. Autopilot dosen't leave space for free and tryied to open channel with all sat available:


> 2018-04-15 16:48:10.928 [WRN] ATPL: Unable to open channel to 028c227313d6e31a4559c13988998d40cc7aac980d064dbe80cafb687bd86dded3 of 0.0004411 BTC: not enough witness outputs to create funding transaction, need 0.0004777 BTC only have 0.0004411 BTC  available


`pi@raspberrypi:~ $ lncli walletbalance
{
    "total_balance": "233927",
    "confirmed_balance": "44110",
    "unconfirmed_balance": "189817"
}
`

**Comment by Roasbeef** [comment]
You can set the min and max channel sizes to create with `autopilot.minchansize` and `autopilot.maxchansize`.

**Comment by halfik** [comment]
@Roasbeef how does this helps? If i have lets say 10k sat in wallet and minchainsize=10k and maxchainsize=100k will it somehow solve problem with autopilot not leaving any sat for fee?

**Comment by ashleyholman** [comment]
I hit this as well.  When I set allocation to 1.0, I would expect it to spend exactly all of my available wallet funds on opening channels where possible.

Setting min/max channel size helps to prevent it but doesn't fix the root cause which is miscalculation of fees.
