### ISSUE TITLE
After upgrading to HEAD, listinvoices and addinvoice return "permission denied"

### ISSUE THREAD

**Issue by Raulo** [lightningnetwork/lnd#987]
### Background

After upgrading to HEAD and restarting lnd, lncli listinvoices and addinvoice exit with error
$ lncli listinvoices
[lncli] rpc error: code = Unknown desc = permission denied

It works fine after downgrading to v0.4 (b866806d67)

### Your environment

lnd 0.4 2526827b6d
Linux 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bitcoind 0.16.0

**Comment by cfromknecht** [comment]
Delete your macaroons and macaroon.db, then restart lnd. We recently added an `invoice.macaroon` that will be generated automatically.
